= 0731
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 731: Hints and Innuendo.
This is English as a Second Language Podcast episode 731. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Eslpod.com, that’s our website. Go there and become a member of ESL Podcast and help keep this podcast going.
This episode is a dialogue between Roberta and John about vocabulary related to “innuendo,” when we indirectly communicate meaning to other people. Let’s get started.
[start of dialogue]
Roberta: You know, my birthday is coming up.
John: Yeah, I know. What are you getting at?
Roberta: Nothing. I was just thinking that it’s kind of an important birthday, a major birthday.
John: Yes, I know. Spit it out. What are you driving at?
Roberta: I was just thinking that some people might not know what to get me for such an important birthday, since some people don’t like to put a lot of thought into presents.
John: What are you implying? Are you insinuating that I don’t get you good presents for your birthdays?
Roberta: No, of course not. I just don’t want you to have to rack your brain to think of the perfect gift, that’s all.
John: Just tell me. What should I get you for your very important birthday?
Roberta: What? Just blurt it out? I can’t do that. I can give you a hint, but since you love me so much, I’m sure you can read my mind.
John: That’s where you’re wrong. If I had a nickel for every time a woman thought I should be able to read her mind, I’d be the richest man in the world! I don’t have an inkling of what you have on your mind.
Roberta: All right, I’ll make it more than a hint. I’ll give you three clues.
John: Great. That’ll make things crystal clear.
[end of dialogue]
Our dialogue begins with Roberta saying to John, “You know, my birthday is coming up.” Something that is “coming up” is something that will be happening in the near future, something that will occur soon. John says, “Yeah, I know. What are you getting at?” “To get at” is to say something indirectly, to communicate something to another person without saying it directly. You’re suggesting something. Roberta says, “Nothing (she’s not getting at anything). I was just thinking that it’s kind of an important birthday, a major birthday.” John says, “Yes, I know. Spit it out.” “Spit (spit) it out” is an expression that means say something quickly, stop trying to hide it. It’s often used when someone will talk about something that is embarrassing or difficult, or perhaps critical of the other person. But when you say “spit it out,” you’re saying to the person just say it now, directly. John says, “What are you driving at?” “To drive at” means the same as “to get at,” to say indirectly.
Roberta says, “I was just thinking that some people might not know what to get me for such an important birthday, since some people don’t like to put a lot of thought into presents.” “Some people,” if you notice the way Roberta says it, is a way that we say something about another person without using their name. We’re really saying “you,” but you’re trying to be polite or perhaps funny by just putting it in this neutral third person – or in this case, third people – “some people.” “Some people (meaning you) might not know what to get me for such an important birthday, since some people (you, John) don’t like to put a lot of thought into presents (or gifts).” “To put a lot of thought into (something)” is to think about something seriously for a long time, give it a lot of thought, a lot of serious considering before making a decision.
John says, “What are you implying?” “To imply” (imply) means to strongly suggest something without saying it directly. Well, John is asking what Roberta is implying. He says, “Are you insinuating that I don’t get you good presents for your birthdays?” “To insinuate” (insinuate) means to suggest that something is bad, something is wrong, without saying it directly. It’s similar to “imply,” but it always has a negative connotation; something bad is being implied.
Roberta says, “No, of course not (of course she wasn’t insinuating that John gives her bad presents for her birthdays). I just don’t want you to have to rack your brain to think of the perfect gift, that’s all.” So, Roberta is saying these things to help John, that’s what she says. She doesn’t want John to rack (rack) his brain. “To rack your brain” means to put a lot of thought into something, to take a long time to think of something. We also use this if we’re having difficulty remembering something or someone. “I’m racking my brain trying to think of the name of the girl who sat next me in social studies class when I was a senior in high school.” I think her first name was Linda…Lydia…I can’t remember. Anyway, that’s what racking your brain is, trying to think of something, spending a lot of time and energy doing it.
So Roberta says she’s trying to help John, and John says, “Just tell me. What should I get you for your very important birthday?” Roberta says, “What? Just blurt it out?” “To blurt (blurt) (something) out” is a phrasal verb meaning to say something without first thinking carefully about what you are saying or how you will say it. Sometimes people say things, and then they realize that it was a mistake to tell someone something. Maybe they’re nervous, maybe they’re excited; they blurt something out, they say something they shouldn’t.
Roberta says that she doesn’t really want to blurt it out, to tell John directly. She says, “I can’t do that. I can give you a hint, but since you love me so much, I’m sure you can read my mind.” A “hint” (hint) is a small piece of information that suggests something else. It’s a clue; it’s to help you guess something or figure something else out. “To read someone’s mind” means to know what the other person is thinking. So Roberta is saying here that she can give John a clue – a hint, but because John loves her so much he should be able to read her mind. Now, this is something that many women believe about men – wives about their husbands, girlfriends about their boyfriends – that because they love them they should know what they want for their birthday. But of course, we men know this isn’t true!
John says, “That’s where you’re wrong. If I had a nickel for every time a woman thought I should be able to read her mind, I’d be the richest man in the world!” This phrase, “if I had a nickel (which is five cents) for every time something happens, I’d be rich,” the idea is that this has happened to you many, many times. If each time it happened you got a very small amount, say a nickel, which is five American cents, you would be rich because it has happened to you so many times. You could say “if I had a dollar” or “if I had a quarter.” It has to be a small amount of money. John is saying that many women in his life have thought that he should be able to read their minds. He says, “I don’t have an inkling of what you have on your mind.” An “inkling” (inkling) is a little bit of knowledge, a small idea; you know a little bit, but not very much. John says he doesn’t have an inkling. He doesn’t have any idea what is on Roberta’s mind, what she’s thinking, what she wants for her birthday.
Roberta says, “All right, I’ll make it more than a hint. I’ll give you three clues.” A “clue” (clue) is a piece of information that helps you solve a problem, usually when there’s some sort of crime or mystery involved. Roberta’s going to give John three clues to what she wants to have for her birthday. Notice we say “clues to (something).” You have clues to the gift, in this case.
John says, “Great. That’ll make things crystal clear.” The expression “crystal (crystal) clear” means easy to understand, no doubt about something. It’s obvious almost; you know exactly what it is. That’s something that is crystal clear. “The professor gave crystal clear definitions about what he was talking about,” they were easy to understand. We’re not sure here if John is being sarcastic, if he’s making a joke, because of course a clue is not the same as the actual answer to the problem. But we hope John will buy the right gift and figure it out!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Roberta: You know, my birthday is coming up.
John: Yeah, I know. What are you getting at?
Roberta: Nothing. I was just thinking that it’s kind of an important birthday, a major birthday.
John: Yes, I know. Spit it out. What are you driving at?
Roberta: I was just thinking that some people might not know what to get me for such an important birthday, since some people don’t like to put a lot of thought into presents.
John: What are you implying? Are you insinuating that I don’t get you good presents for your birthdays?
Roberta: No, of course not. I just don’t want you to have to rack your brain to think of the perfect gift, that’s all.
John: Just tell me. What should I get you for your very important birthday?
Roberta: What? Just blurt it out? I can’t do that. I can give you a hint, but since you love me so much, I’m sure you can read my mind.
John: That’s where you’re wrong. If I had a nickel for every time a woman thought I should be able to read her mind, I’d be the richest man in the world! I don’t have an inkling of what you have on your mind.
Roberta: All right, I’ll make it more than a hint. I’ll give you three clues.
John: Great. That’ll make things crystal clear.
[end of dialogue]
Our scriptwriter puts a lot of thought into these wonderful scripts. We thank you Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
coming up – happening in the near future; occurring soon
* Coming up next, we’ll talk to a man who has three pet bears.
to get at – to say indirectly; to communicate something to another person without saying it directly; to strongly suggest something without saying it
* Why are all of you moving your chairs away from me and holding your noses? What are getting at?
to spit (something) out – to say something quickly and without delay that may be difficult, embarrassing, or hurtful to say or for another person to hear
* I’m asking you children who broke Mom’s favorite vase? Spit it out!
to drive at – to say indirectly; to communicate something to another person without saying it directly; to strongly suggest something without saying it
* After 40 minutes, Carl finally found out what his sister was driving at. She wanted to borrow money from him.
to put a lot of thought into (something) – to think about something a lot before taking action; to consider many things before making a decision
* Manuel put a lot of thought into the gift he bought his new girlfriend.
to imply – to strongly suggest something without saying it; to communicate that something exists or is the truth without stating it
* Our boss implied that there would be less money for bonuses this year, but he wouldn’t answer any direct questions about it.
to insinuate – to make a suggestion that something bad is true without stating it
* Beth was tired of her relatives insinuating that she was too old to find a husband.
to rack (one’s) brain – to use a lot of effort to think of or to remember something
* Deng racked his brain for a half hour, but couldn’t remember the combination to the lock on the safe.
to blurt (something) out – to say something without first thinking about what one will say, how one will say it, and/or how others will react
* If I tell you a secret, don’t blurt it out when you’re with your friends, okay?
hint – a small or indirect suggestion about something; a clue
* My parents won’t tell me what I’m getting as a Christmas gift, but they gave me a hint that it was related to my computer.
to read (one’s) mind – to be able to know what someone is thinking without that person telling you; for someone to know something about another person without having to be told
* The architect must have read my mind because the plans for the new house are exactly what I wanted.
If I had a nickel for every time…(I’d be rich) – a phrase used to say that something happens a lot or that something is very common
* If I had a nickel for every time Olah made an excuse when he was late, I’d be rich.
inkling – a slight idea; a little bit of knowledge that will give some information about something else; a hint
* Do you have an inkling why James is wearing a thick coat on a hot summer day?
clue – a piece of information or idea that helps to solve a problem; information used to solve a crime or mystery
* The footprint in the mud was an important clue to solving the crime.
crystal clear – easy to understand or see; having no doubt about something
* None of the students had a crystal clear idea about the difficult concept their teacher talked about in class, but reading their textbook helped them better understand it.
Comprehension Questions
1. What does Rebecca want John to do?
a) Buy her a gift.
b) Give her a nickel.
c) Drive her to the store.
2. What is crystal clear?
a) Rebecca wants to buy John a birthday gift.
b) Rebecca wants a special gift for her birthday.
c) Rebecca is John’s sister.
Answers at bottom.
What Else Does It Mean?
coming up
In this podcast, “coming up” means for something to happen in the near future or for something to occur soon: “Our vacation to New York is coming up, so we’ll need to reserve a hotel room.” “To come up with” means to think of new ideas or useful pieces of information: “Can you come up with some ideas for entertainment appropriate for both children and adults?” Or, “Stop coming up with excuses for not cleaning out the garage!” “To come up for air” means to begin to relax after a very busy period of time: “Our dress shop has more orders than we can handle and I don’t know when we’ll come up for air.”
clue
In this podcast, a “clue” is a piece of information or idea that helps to solve a problem, or information used to solve a crime or mystery: “I know that you’ve planned a surprise, but could you give me a clue about where you’re taking me?” “To clue (someone) in” means to tell someone about something that he or she doesn’t already know about: “After thinking a lot about it, Genise finally clued her friend in that her friend’s husband was not being faithful to her.” Or, “Can you clue me in on how to use the new fax machine?” “To not have a clue” means to not know anything about something or to not know how to do something: “Javier has no clue where he’ll get the money to help his parents, but he’ll do anything to help them keep their house.”
Culture Note
Teenage Milestone Birthdays and the Selective Service System
In a typical American’s “lifetime” (the period of time a person is alive), he or she experiences several “milestone” birthdays. “Milestones” are significant periods or events “indicating” (showing; marking) significant changes or stages in development.
For teenage girls, their 16th birthday is sometimes celebrated with a “sweet 16” party, indicating that she is “on the verge of” (nearly) becoming a woman. The 16th birthday is important also because most states allow people 16 years old or older to apply for a driver’s license.
For both boys and girls, their 18th birthday is important because this is the age typically considered the beginning of “adulthood” (the state of being an adult; not childhood). At age 18, most teenagers have graduated high school and are expected to either attend college or begin working. Many 18-year-olds move out of their parents’ home, another “rite of passage” (event that indicates that a person is maturing and becoming like an adult).
Teenage boys at age 18 are required by law to register with the Selective Service System. The Selective Service System is the U.S. government’s way of keeping information about men who are “eligible for” (meet the requirements for) the “draft,” when the government requires that men serve in the military, usually because there is a war and not enough “voluntary” (done by one’s own choice or decision) soldiers. Men who are between the ages of 18 and 25 are required to register with the Selective Service System, and those “turning” (becoming) 18 years old are required to register within 30 days of their 18th birthday.
Comprehension Answers
1 - a
2 - b