
= TED 003 - 3 questions to ask yourself about everything you do | Stacey Abrams
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 初心的原因

When I was in high school at the age of 17 --  I graduated from high school in Decatur, Georgia,  as valedictorian （毕业典礼上）致告别辞的最优秀毕业生 of my high school --  I was very proud of myself.



I was from a low-income community, I had grown up in Mississippi,  we'd moved from Mississippi to Georgia   +
so my parents could pursue their degrees as United Methodist  卫理公会教派的 ministers 牧师;（英国及其他许多国家的）部长，大臣;公使；外交使节.

[.my2]
这样我父母就可以继续攻读联合卫理公会牧师的学位了。

We were poor, but they didn't think we were poor enough,  so they were going for permanent  永久的，永恒的 poverty.

(Laughter)   +

And so, while they studied at Emory,  I studied at Avondale, and I became valedictorian （毕业典礼上）致告别辞的最优秀毕业生.

Well, one of the joys 令人高兴的人（或事）；乐事；乐趣 of being valedictorian in the state of Georgia +
is that  you get invited to meet the governor of Georgia.

[.my2]
可以获邀拜访佐治亚州的州长。

I was mildly 轻微地；稍微地 interested in meeting him.

It was kind of cool.

I was more intrigued  着迷的，感兴趣的 by the fact that  he lived in a mansion 大厦，宅邸；<英>公寓楼,   +
because I watched a lot of "General Hospital" 综合医院 and "Dynasty" 王朝；朝，代  as a child.


(Laughter)

And so I got up that morning, ready to go to visit the governor.

My mom and my dad, who were also invited, got up,  and we went outside.

But we didn't *get in* 进入,上车 our car.

And in the South, a car is a necessary thing 必需品.

We don't have a lot of _public transit_ 交通运输系统, there aren't a lot of options.

But if you're lucky enough to live in a community  where you don't have a car,  the only option is _public transit_ 公共交通.

And that's what we had to take.

And so we got on the bus.

And we took the bus from Decatur *all the way to* Buckhead,  where the Governor's Mansion sat (v.) on this really beautiful acreage 面积，英亩数 of land,  with these long black gates that ran (v.) the length of the property.

[.my2]
州长官邸, 就坐落在这片美丽辽阔的土地上，
长长的黑色大门, 一直通向这座建筑的尽头。

We get to the Governor's Mansion,  we pull the little lever 后定 that lets them know this is our stop,  we get off the bus,  my mom, my dad and I, we walk across the street.

[.my2]
我们拉了一下小拉杆，好让他们知道我们到站了。

We walk up the driveway  （从建筑物，住房，车库等通往大路的）私人车道, because there are cars *coming up* 接近，靠近;即将到来,   +
cars bringing in students from all across 在…各处；遍及 the state of Georgia.

So we're walking along the side.

[.my2]
走上了车道，因为有车开过来，
这些汽车带来了从佐治亚州各地来的学生，
所以我们只好沿着路边走了。

And as we walk *single file* 单列排列;一路纵队；单行 along the side,   +
my mom and dad sandwiching (v.)把…夹（或插）在…中间 me  +
*to make sure* I don't get hit (v.) by one of the cars  bringing in the other valedictorians,   +
we approach the guard gate.

[.my2]
当我们排成纵队沿着人行道走的时候，爸爸妈妈把我夹在中间，以确保我不会被运载其他毕业生的汽车撞到，我们走近了警卫门。

When we get to the guard gate, the guard comes out.

He looks at me, and he looks at my parents,  and he says, "You don't belong here, this is a private event 社交场合，既定活动；赛事."

My dad says, "No, this is my daughter, Stacey.  She's one of the valedictorians."

But the guard doesn't look at the checklist （记事）清单，一览表 that's in his hands.

He doesn't ask my mom for the invitation   +
后定 that's at the bottom of her very voluminous 很大的;肥大的；宽松的；用布料多的 purse 钱包，皮夹子（尤指女用的）.

[.my2]
他没有向我妈妈要请柬，请柬就在她那大钱包的底部。

Instead, he *looks* over our shoulder *at* the bus,  because in his mind, the bus is telling him a story about who should be there.

[.my2]
相反，他越过我们的肩膀看着巴士 (反之他看向了我们身后的那辆公交车)

And the fact 后定 that we were *too* poor *to* have our own car --  that was a story he told himself.

And he may have seen something in my skin color 肤色,  he may have seen something in my attire  <正式>服装，衣服;  I don't know what went through his mind.

[.my2]
我不知道他在想什么。

But his conclusion was *to look at* me again,  and with a look of disdain (n.)鄙视，蔑视, say,  "I told you, this is a private event. You don't belong here."

[.my2]
但他得出的结论是又看了我一眼，带着轻蔑的神情，

[.my1]
.案例
====
.disdain
-> dis-, 不，非，使相反。-dain, 同-dign, 尊贵，词源同dignity, decent.即使不尊贵，蔑视。
====

Now, my parents were studying to become United Methodist ministers,  but they were not pastors 牧师 yet.

(Laughter)

And so they proceeded (v.)继续做（或从事、进行） *to engage* （使）从事，参加 this gentleman  *in* a very robust 强劲的；富有活力的 discussion of his decision-making (a.)决策的 skills.

[.my2]
于是他们开始和这位先生进行一场非常激烈的讨论，讨论他的决策能力。

(Laughter)

My father may have mentioned that  +
he was going *to spend (v.) eternity* 无穷无尽的时间；永恒，永久；永生 in a very fiery (a.)火一般的；火的;充满激情的；（尤指）怒气冲冲的;暴躁的；易怒的 place   +
if he didn't find my name on that checklist.

[.my2]
父亲似乎向我提到过，如果那个警卫员没在名单上找我的名字的话, 他将和他一直激烈地讨论下去。


And indeed, the man checks (v.) the checklist eventually  最终，结果,  and he found my name, and he let us inside.

But I don't remember meeting the governor of Georgia.

I don't recall (v.)记起，回想起 meeting my fellow valedictorians  from 180 school districts 区域；地域.

[.my2]
但我已经想不起与佐治亚州州长会面的情形了，也记不清来自180个学校的和我一样的学生代表。

The only #clear memory# I have #of# that day   +
was a man standing in front of the most powerful place in Georgia,   +
looking at me and telling me I don't belong.

And so *I decided*, 20-some-odd （用于数字后）大约，左右 years later,  *to be* the person who *got to* 有机会,能够 open the gates.

[.my2]
“成为那个能够打开大门的人”或“有机会成为打开大门的人”。这里的“打开大门”是比喻意义，暗指突破障碍、实现改变，尤其是与前面提到的“不属于这里”的经历形成对比.

[.my1]
.案例
====
get to 常用于表达某人有机会、能做某事，或有权去做某事。
- I got to meet my favorite author last week. 我上周有机会见到了我最喜欢的作者。
====

(Cheers)  (Applause)

Unfortunately, you may have read the rest of the story.

It didn't quite *work out* 成功地发展 that way.

[.my2]
事实并不全如所愿。

And now I'm tasked (v.)交给某人（任务）；派给某人（工作） with figuring out: How do I move forward?   +
Because, you see, I didn't just want to open the gates for young black women   +
who had been underestimated (v.)低估；看轻 and told they don't belong.

[.my2]
而我现在的任务是弄清楚：我该如何前进？
因为，我并不只是想为那些被低估
并且被告诉不属于这里的年轻黑人女性打开大门。

I wanted to open those gates for Latinas and for Asian Americans.

I wanted to open those gates for the undocumented 无事实证明的；无正式文件的 and the documented 备有证明文件的.

[.my2]
我想为那些有证和无证的人们打开大门；

I wanted to open those gates *as* an ally 盟友，支持者 of the LGBTQ community.

I wanted to open those gates  for the families  +
that *have to* 必须,不得不 call 称呼；把…叫做;认为…是；把…看作 themselves the victims of gun violence.

[.my2]
为那些不得不称自己为枪支暴力受害者的家庭, 打开大门。

I wanted to open those gates wide for everyone in Georgia,  because that is our state, and this is our nation,  and we all belong here.

(Cheers)  (Applause)

But what I recognized is that  +
the first try wasn't enough.

And my question became: How do I move forward?   +
How do I get beyond the bitterness 苦味；苦难；怨恨  +
and the sadness 悲伤，悲痛  +
and the lethargy 无精打采；没有热情；冷漠  +
and watching an inordinate (a.)过度的；无节制的；紊乱的 amount of television as I eat ice cream?  //即, 如何避免雄心沉沦

[.my1]
.案例
====
.lethargy
-> 来自希腊语lethargia,遗忘，忘却，lethe,忘记，词源同latent,Lethe,argos,无精神，来自a-,无，没有，-erg,工作，趋动，词源同work,synergy.即如同游魂，无精打采，冷漠。
====

(Laughter)

'''

== 你做每一件事时, 都要问自己三个问题

What do I do next?
And I'm going to do what I've always done.

I'm going to move forward, because *going backwards* isn't an option   +
and standing still 静止不动 is not enough.

(Applause)

You see, I began my race 竞争；角逐 for governor   +
by analyzing (v.) _who I was_ and _what I wanted to be_.

[.my2]
我在竞选州长之初, 就分析了我是谁，我想成为什么样的人。

And there are three questions I *ask* myself *about* everything I do,   +
*whether* it's running for office 竞选公职 *or* starting a business;   +
when I decided to start the New Georgia Project  to _register people_ to vote (v.);   +
*or* when I started the latest action, Fair Fight 公平斗争 Georgia.

[.my2]
对我做的每一件事，我都会问自己三个问题，
无论是当我在竞选, 还是创业时;
当我决定启动新佐治亚州项目, 让选民去登记选票时；
当我开始最新倡议 Fair Fight Georgia时。


No matter what I do, I ask myself three questions:   +
What do I want?   +
Why do I want it?   +
And how do I get it?   +
And in this case, I know what I want.

I want change.

That is what I want.

'''

=== 问题1: 你对你所追求的东西, 真实度有多大? 即, 你真的喜欢你追求的东西吗?

But the question is:  What change do I want to see?   +
And I know that the questions I have to ask myself are:  +

One, am I honest about the scope （做或实现某事的）机会，能力 of my ambition?   +
Because it's easy to figure out that /once you didn't get what you wanted,   +
then maybe you *should have set* your sights 视力范围；视野 a little lower,   +
but I'm here to tell you to be aggressive (a.)挑衅的；侵略的；富于攻击性的;志在必得的 about your ambition.

[.my1]
.案例
====
.scope
~ (for sth) |~ (for sb) (to do sth) :the opportunity or ability to do or achieve sth （做或实现某事的）机会，能力 +
SYN potential +
•First try to do something that is within your scope . 你先试着做一件自己力所能及的事。 +
•There's still plenty of scope for improvement.还有很大的改进余地。

.should have + done 过去分词：
表示对过去的事情进行反思，意思是“本应该……但没有”。 +
- You should have studied harder for the test. （你本应该更努力复习考试。）
====

[.my2]
====
第一，我对自己的抱负是否诚实？
因为一旦你没有得到你想要的, 你就很容易发现这一点.
也许你**本应该**把你的眼光放低一点，
但是我在这告诉你, #一定要对自己的目标有进取心。不要让挫折阻碍你。#

**注意: maybe you should have set your sights a little lower 表面上看起来貌似作者在说, “也许你本应该把目标定得低一些, 可能更容易实现，结果会好一点。” 但其实, 在整个语境中，作者实际上是在鼓励听众不要因此降低目标，而是积极追求自己的雄心壮志。所以这句话更多是一种反面论点，**用来对比后续的观点：要有侵略性地追求自己的目标，不要轻易妥协。
====

Do not allow setbacks 挫折；阻碍 to set you back.

(Applause)

'''

=== 问题2: 当出现问题时, 你要分清, 哪些是源于你的, 哪些并非是你的, 而是别人产生的.

Number two, let yourself understand your mistakes.
But also understand their mistakes,  because, as women *in particular*,  we're taught that if something doesn't work out,  it's probably our fault.

[.my2]
第二，要清楚自己的错误。
但同时也要清楚他人的错误。
因为，尤其作为女性，
大家总认为如果事情没有成功，
那肯定是我们的问题。

And usually, there is something we could do better,  but we've been told (v.) not to investigate too much  what the other side *could have done* 本可以做某事.

[.my2]
通常，有些事情我们可以做得更好，但我们被告知不要过多地调查对方本可以做的事情。

And this isn't partisan (a.n.)（对某个人、团体或思想）过分支持的，偏护的，盲目拥护的;坚定的支持者；铁杆拥护者; 党派的,具有党派偏见的 -- it's people.

[.my2]
这不是关于党派立场的问题，而是关于人性的普遍现象。 +
(这句话旨在说明，女性在面对挫折或失败时, 常常被教导认为是自身的问题，但实际上这种现象并不局限于某个特定群体或党派，而是普遍的人性现象。)


We're too often told that our mistakes are ours alone,  but victory is a shared benefit.

[.my2]
我们经常被告知错误是我们自己的，
但胜利又是大家共同享有的利益。

And so what I tell you to do is understand your mistakes,  but understand the mistakes of others.

And be clearheaded (a.)头脑清楚的 about it.

And be honest with yourself and honest with those who support you.

But once you know what you want,  understand why you want it.

And even though it feels good, revenge 报复，报仇；报复欲望，复仇心 is not a good reason.

(Laughter)

Instead, make sure you want it  *because* there's something *not* that you should do,  *but* something you must do.

[.my2]
还有，#确保你想做一件事情
不是因为你应该这么做，
而是因为必须要这么做。#

It has to be something 后定 that doesn't allow you to sleep at night  *unless* you're dreaming about it;   +
something that *wakes you up* in the morning /and gets you excited 激动的，兴奋的 about it;   +
or something that makes you so angry,  you know you have to do something about it.

[.my2]
#这一定是令你晚上
魂牵梦萦的事情；
或者是早上醒来就足够让你兴奋的事情；#
又或者是能够让你很愤怒的事情，
你知道你必须要做点什么。

But know why you're doing it.

And know why it must be done.

You've listened to women from across this world  *talk about* why things have to happen.

[.my2]
你们应该听过很多世界各地的女性
谈论过为什么有些事必须去做。

But figure out what the "why" is for you,  because `主` *jumping from* the "what" *to* the "do"  `系` is meaningless if you don't know why.


Because when it gets hard, when it gets tough (a.)困难的，棘手的；艰难的，困苦的，难熬的,  when your friends *walk away 远离，摆脱 from* you,  when your supporters forget you,  when you don't win your first race --  if you don't know why, you can't try again.

[.my2]
即, #如果你对你所做的, 背后没有坚实的信念支撑的话, 你一旦遇到困难阻力, 阻力越大, 你就不会撑住, 而更会轻易放弃它.# 比如, 你对"设计"这个工作没真正兴趣, 一旦加班压力增大, 你就会轻易放弃掉它. 的确如此.


'''

=== 问题3: 对你的目标, 你打算如何实现它? 方法论是什么?

So, first know (v.) what you want.

Second, know why you want it,  but third, know how you're going to get it done.

[.my2]
第三，你要知道你将如何实现它。

I faced a few obstacles 障碍；障碍物；阻碍 in this race.

(Laughter)

Just a few.

[.my2]
有过几次。

But in the pursuit,  I became the first black woman to ever 曾经，从来，在任何时候 become _the nominee 被提名者，被任命者 for governor_ 州长 in the history of the United States of America for a major party.

[.my2]
但在追求的过程中，我成为了美国历史上第一位 被主要政党提名为州长的黑人女性。

(Cheers)  (Applause)

But more importantly, in this process,  we *turned out* 出席（某项活动）；在场; 动员,使…参加投票 1.2 million African American voters in Georgia.


That is *more* voters 选民，投票人 *than* voted (v.) on _the Democratic side_ of the ticket 票；券 in 2014.

[.my2]
这比2014年投票支持民主党的选民还要多。

(Applause)

Our campaign （有计划的）活动，运动 tripled (v.)成三倍，增至三倍 the number of Latinos 拉丁美洲人 who believed their voices mattered (v.) in the state of Georgia.

[.my2]
我们的竞选活动, 使得相信他们的呼声对佐治亚州很重要的拉美裔人的数, 量翻了三倍。

We tripled (v.) the number of Asian Americans   +
who stood up and said, "This is our state, too."

Those are successes 后定 that tell me how I can get it done.

[.my2]
这些成功事例告诉我如何能把事情做好。

But they also let me understand `主` the obstacles `系` aren't insurmountable 不能克服的；不能超越的；难以对付的.

They're just a little high.

But I also understand  that there are three things that always *hold us hostage* 人质.

The first is finances.

Now, you may have heard, I'm in a little bit of debt.

[.my2]
我欠了一点债

If you didn't hear about it, you did not go outside 离开室内;出门.

(Laughter)

And finances are something that *holds us back* 拦阻；阻挡 so often,  our dreams are bounded by how much we have in resources.

[.my2]
我们的梦想, 受到我们拥有多少资源的限制

But we hear again and again  the stories 故事 of those 后定 who overcome (v.) those resource challenges.

But you can't overcome something you don't talk about.

And that's why I didn't allow them to debt-shame (v.)用债务来羞辱 me in my campaign.

I didn't allow anyone to tell me that  +
my lack of opportunity  was a reason to disqualify (v.)取消…的资格 me from running.

And believe me, people tried to tell me I shouldn't run 参加竞选.

Friends told me not to run.

Allies told me not to run.

"USA Today" mentioned (v.)提到；写到；说到 maybe I shouldn't run.

[.my2]
就连”今日美国“也曾报道说，或许我不该参加竞选。

(Laughter)

But no matter who it was,  I understood that finances are often a reason we don't let ourselves dream.

[.my2]
我明白, 财务问题往往是我们不敢梦想的原因。

I can't say that you will always overcome those obstacles,  but I will tell you, you will be damned (v.)强烈指责；谴责；狠狠批评;令（某人）下地狱 if you do not try.

[.my2]
#我不能说你能一直克服那些障碍，
但是我想告诉你，如果连尝试都不敢，那你注定完蛋。#

(Applause)

The second is fear.

And fear is real.

It is paralyzing 使…瘫痪，使…麻痹.

It is terrifying 吓人的，令人害怕的.

But it can also be energizing
给（某人）增添能量（或精力、活力、干劲）,  because once you know what you're afraid of,  you can *figure out* 弄清楚，弄明白; 找到答案，解决 how to get around 绕过，规避 it.

And the third is fatigue 疲乏，厌倦.

Sometimes you just get tired of trying.

You get tired of reading about _processes 过程；进程 and politics  and the things_ that stop you from getting where you want to be.

Sometimes, fatigue means that we *accept* (v.) position *instead of* power.

[.my2]
有时候，疲劳意味着, 我们甘愿接受位置, 而非权力。

We let someone give us a title as a consolation (n.)安慰，起安慰作用的人（物） prize,  rather than 而不是 realizing (v.) we know _what we want_ and _we're going to get it_,  even if we're tired.

[.my2]
我们让别人给我们一个头衔作为安慰奖，
而非我们认识到, 我们知道自己想要什么, 并会努力实现梦想，即便我们会疲劳。 +
(我们让别人把一个头衔当作安慰奖给了我们，而没有意识到，我们清楚自己想要什么，并且即使感到疲惫，也会去争取实现它。)

That's why God created (v.) naps （日间的）小睡，打盹.

(Laughter)

But we also learn in those moments  that  +
fatigue is an opportunity to evaluate (v.)评价，评估，估值 how much we want it.

Because if you are beaten (v.)打败 down,  if you have worked (v.) as hard as you can,  if you have done everything you said you should,  and it still doesn't work out 成功，顺利进行,  fatigue can *sap* (v.)使削弱，使虚弱 you *of* your energy.

[.my2]
如果你尽可能地努力了，
如果你应该做的都做了，
当仍然无济于事，
疲劳就会消耗你的精力。

[.my1]
.案例
====
.sap
[ VN] ~ sth | ~ sb (of sth) : to make sth/sb weaker; to destroy sth gradually使虚弱；削弱；逐渐破坏 +
-> 来自中古法语 saper,挖地道，来自拉丁语 sappa,铲子，词源可能同 spade,铲子。其比喻义削 弱，破坏可能受上一词义影响。
====

But that's why _you go back to the "why" of it_.

[.my2]
但这就是为什么你要回到“为什么”的原因。

Because I know  +
we *have to* have women  +
who *speak for* the voiceless  无声的；沉默的.

[.my2]
因为我知道，我们必须要有"为弱势群体说话的女性"。

I know we *have to* have people of good conscience  良知，良心 +
who stand up against oppression 压迫，压制.

[.my2]
我知道我们必须要有良知的人们
站出来反抗压迫。

I know we have to have people   +
who understand that social justice belongs to us all.

And *that wakes (v.) me up* every morning,  and *that makes me fight* even harder.

[.my2]
这让我每天早上醒来，
让我更加努力地奋斗。

Because I am moving forward, knowing what is in my past.

[.my2]
因为我在前进，知道我的过去是什么样。


I know the obstacles they have for me.

[.my2]
我知道他们为我设置的障碍。

I know what they're going to do,  and I'm fairly  相当地，颇 certain (a.) they're energizing 使充满热情;为…提供电力（或能量）；使通电 and creating new obstacles now.


But they've got four years to figure it out.

[.my2]
但他们有四年的时间来搞清楚这个问题。

(Laughter)  (Applause)

Maybe two.

(Cheers)  (Applause)

But here's my point:  I know what I want, and that is justice.

[.my2]
我知道我要什么，那就是公正。

I know why I want it,  because poverty 贫穷，贫困 is immoral 不道德的，邪恶的, and it is a stain 污点，污渍 on our nation.

And I know how I'm going to get it:  by moving forward every single day.

Thank you so much.

(Cheers)  (Applause)

'''