= 0157
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 157: Taking the Bus.
You’re listening to English as a Second Language Podcast episode 157. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this podcast, we’re going to take a ride on the bus. Here we go!
[start of story]
I just moved to L.A. and don’t have a car. Everybody says that you can’t get around this city without one, but I wanted to prove them wrong.
I asked my neighbor to take me to the downtown bus station so I could try taking the bus home. She thought I was crazy, but gave me a ride. When I got there, I went inside and got a bus schedule. I looked at the map and figured out that I needed to take three buses to get home. The fare was $1.75 per ride and I could buy a single ticket, a booklet of 20, or a bus pass. I would need transfers, too, to change buses.
I took my map and went outside to wait at the bus stop for the Number 8 bus. Soon, it pulled up and I got on. I gave my ticket to the bus driver and took a seat. At the stop where I needed to get off, I rang the bell, the bus stopped, and I got off. I waited for the next bus. I waited and waited. A man who was also waiting for the Number 14 bus said that it wasn’t unusual for the bus to be delayed. It finally got there and I found out that the bus had broken down along the route and they had to get another bus to take its place. By this time, I was getting pretty tired. Maybe getting a car in L.A. wasn’t such a bad idea.
[end of story]
We’re taking the bus in this podcast. I have to say that this is definitely a fictional story – a made up story, one that is not true – because I have lived in Los Angeles for about 15 years and I have never taken a bus here in Los Angeles. I used to take a bus all the time when I lived back in Minnesota, but the public bus system in Los Angeles – the public transportation system is very poor compared to most big cities in the world. It is not a very convenient way to move from one part of the city to another, to get from one part of the city to another. So, I had to make this story up. Actually, Dr. Tse had to make this story up, but it is the same pretty much in any American city, the way the bus system works.
Well, our story begins by me saying that “Everybody says that you can’t get around in this city – in Los Angeles – without a car. But I wanted to prove them wrong.” Everybody says you can’t get around. “To get around” – two words – means to be able to go from one place to another – not a specific place. For example, you wouldn’t say, “I need to get around from my house to the beach.” When you use the verb “to get around,” you mean in general, getting from one place to another within the city. “How do you get around?” “I have a car,” or “I take the bus.” I said that I wanted to “prove other people wrong” about not owning a car in Los Angeles – not having a car in Los Angeles. “To prove someone wrong,” of course, means to show them that they are wrong – to give them evidence that they are wrong. You can prove someone wrong. You can prove someone right. But usually, you try to prove people wrong – that’s just the way we are as humans, I guess.
Well, I asked my neighbor to take me to the downtown bus station. And “bus station” – two words – is the main place where the buses are located. Usually, it’s near a downtown area. But most people don’t go to the bus station to get a bus because, of course, the buses go around the city. You can pick them up anywhere in the city. But the buses all begin, usually, from a bus station. Of course, you can have a bus station. You can have a train station. We sometimes call these stations – these places – “terminals” (terminal). A “terminal” is where something ends, but when we talk about a bus terminal, or a train terminal, those are usually for buses and trains that are going to other cities – to other places.
So, I’m at the downtown bus station in our story. My neighbor “gave me a ride” to the bus station. And, of course, “to give someone a ride (ride)” means that you drive them there. They go with you in your car. When I got to the bus station, I went inside and got a “bus schedule.” And, of course, the bus schedule is a list of all the times and places where the buses travel to. “I looked at the map and I found out I needed to take three buses from downtown to my house.” There wasn’t one bus that went directly near my house. So, I had to take three of these.
Well, the “fare” (fare) for the bus ride was $1.75, one dollar, seventy five cents. And, of course, the “fare” is the amount of money that you have to pay. We use the word “fare” for buses. We use it for airplanes. “How much is the airfare?” “How much is the bus fare?” “How much is the train fare?” – anything that has to do with transportation. We even say, “How much is the cab, or taxi cab, fare?” It’s the price that you pay. Well, you can buy a single ticket, which means it’s only one ride. You can buy a booklet of twenty tickets. A “booklet” (booklet) is a small book, but it’s not a book that you read. A “booklet,” in this case, is just a collection of tickets that you can use for the bus. We can use booklet as something you do read. A small book could be called a booklet. Usually, we use the term “booklet” for things that are informational. So, if you go to the doctor and you have a certain problem, he may give you a booklet to read with information about it. But here, “booklet” is just a collection of tickets. Another thing that you can get to ride a bus is a “pass” (pass). A “pass” – you pay usually, a certain amount of money for a week or a month. And you can use the bus as much as you want during that time. There are bus passes, there are train passes, but I don’t think there are any airline or airplane passes.
One of the things you have to do sometimes, and I have to do in this story, is to “change buses.” And usually, they will give you – when you get on the bus – what’s called a “transfer.” A “transfer” (transfer) is a little – it’s like a ticket that says you already paid for this ride. So, you don’t have to pay again when you get on another bus going in the same direction. So, we call these “transfers.” If you want to change buses or go to another bus, you need a transfer. The way things work in buses is that when you first get on the bus, you have to pay. You put money in a machine or you give the driver, the bus driver, a ticket, or you show the bus driver your pass. You can’t get on the bus without paying.
In most American buses, you can only get on the bus in the front of the bus. There’s usually two doors, one in the front and one in the middle for you to get out of the bus. But you can only get on, on the front door. Well, I said I took my map and I went outside to wait at a “bus stop.” A “bus stop – two words – (bus stop) – is a place, obviously, where the bus stops. There are bus stops that are marked (marked). “To be marked” means there’s a sign that says, “This is a bus stop.” And often, in many cities, there will be a place for you to sit by the bus stop. We usually call that a “bench” (bench). Sometimes, there’s a little shelter and a “bus shelter” is a small – it’s like a small, little house but it’s not a house. It’s a place where you can stand in case it is raining to keep dry. So, there’s a little roof with usually, some side walls. But it’s not a big thing. It’s maybe, 5 or 6 people could stand underneath the bus shelter. These are more popular in northern cities like Minneapolis, St. Paul – where I’m from – Chicago, New York – those places probably will have bus shelters more than here in Los Angeles because, of course, it’s always sunny here in Los Angeles; that’s why it’s so beautiful. That’s not true, of course. It’s raining right now, outside, as I record the podcast. But normally, it’s sunny.
Well, I am waiting for the number 8 bus. And buses usually have numbers as they do in most countries. And we say “the number 8 bus.” We would not say, “I’m waiting for number 8 bus.” We would use the indefinite article “the.” Sometimes, people will say, “I’m waiting for the 8 bus.” They won’t even say the word number, but the 8 bus, or the number 8 bus.
Well, the bus “pulled up” and I got on. When we say a bus “pulled up” we mean that it drove to where I was standing and stopped. So, the bus pulled up. A car can pull up, meaning you’re standing somewhere and a car comes and parks right near you. We would say, the car “pulled up” to you. “The bus pulled up and I got on,” meaning I entered the bus. I gave my ticket to the bus driver. I took a seat. And at the stop where I needed to “get off,” meaning at the place where I needed to get off the bus, I rang the bell. And in many American buses, there’s a button or a cord – a string that you pull so that the bell rings and the driver knows that you want to get off at the next stop. Of course, it’s important to ring the bell before you get to the stop.
Well, I got off and I waited for the next bus and I waited a very long time. And someone told me that “it wasn’t unusual” for the bus to be delayed. “It wasn’t unusual” means it’s usual. Of course, when you have two negative ideas in a sentence in English, it’s a positive – the idea is a positive one. So, if we say “it wasn’t unusual,” we mean it is usual, it is common. “It wasn’t unusual for the bus to be delayed.” “To be delayed” (delayed) means to be late – not to be there on time. It’s delayed. If you go to the airport and you look up at the television screen – the computer monitor that has the airplane information – if it says “delayed” next to the place where you’re going – next to your airplane – that means that it’s not going to leave on time – that’s maybe the worst thing you want to see in an airport, is that your flight has been delayed, your plane has been delayed.
Well, here in the story, the bus was delayed. The bus had “broken down.” When we say an automobile or a bus, or any sort of machine “breaks down,” we mean it stops working. This bus broke down along the route. The “route” (route) – which some people pronounce “route” – the “route” is the places where the bus travels. A “route” is like a path. It is a place where something goes, travels across. In this case, the route could be up Sunset Boulevard and then down La Brea Avenue and then across Wilshire Avenue to Santa Monica – that would be the route. You can talk about a “route,” also for a parade. Someone says, “Where is the parade route?” We just had a marathon race here in Los Angeles a couple of weeks ago, the Los Angeles marathon, and there was a marathon route. So, they block the streets so that the runners can run. Not me, but, you know, people who run. “Runners,” I guess, we would call them. So, in this case, the bus broke down and the company had to get another bus to take its place – that is, another bus that would pick up the riders or the passengers for the bus that broke down.
I should also mention that most buses are operated by the government, the local government. So, the city has a company that runs the buses. Well, I was getting pretty tired and at the end of the story, I concluded – I came to the conclusion – that L.A really requires a car – that “getting a car wasn’t such a bad idea.” Once again you see two negatives here. “Bad” is negative and “was not” is negative. So, someone says, “It wasn’t such a bad idea,” what they’re saying is it’s a good idea. So, you’ll often hear, even though you don’t normally put two negatives in a sentence – there are some common expressions where we use two negative words such as this case, it wasn’t such a bad idea.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of story]
I just moved to L.A. and don’t have a car. Everybody says that you can’t get around this city without one, but I wanted to prove them wrong.
I asked my neighbor to take me to the downtown bus station so I could try taking the bus home. She thought I was crazy, but gave me a ride. When I got there, I went inside and got a bus schedule. I looked at the map and figured out that I needed to take three buses to get home. The fare was $1.75 per ride and I could buy a single ticket, a booklet of 20, or a bus pass. I would need transfers, too, to change buses.
I took my map and went outside to wait at the bus stop for the Number 8 bus. Soon, it pulled up and I got on. I gave my ticket to the bus driver and took a seat. At the stop where I needed to get off, I rang the bell, the bus stopped, and I got off. I waited for the next bus. I waited and waited. A man who was also waiting for the Number 14 bus said that it wasn’t unusual for the bus to be delayed. It finally got there and I found out that the bus had broken down along the route and they had to get another bus to take its place. By this time, I was getting pretty tired. Maybe getting a car in L.A. wasn’t such a bad idea.
[end of story]
Our script for today’s podcast was written by Dr. Lucy Tse.
Remember to visit our website at www.eslpod.com for a script for today’s story and more information about this podcast.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
to prove (someone) wrong – to show someone that something that they said or did is not right; to show someone that one can achieve something that others did not think they could achieve
* My brother didn’t believe I could get a good grade on my test, so I studied hard and proved him wrong.
bus station – a building where buses leave from in the morning and come back to at the end of the day; a place where people can go to ride a bus
* When I got on the bus this morning, I accidentally left my purse at the bus station.
bus schedule – a list or map of the streets that a bus will travel, along with the times that the bus will be stopping at each place
* I needed to look at the bus schedule to see what time the bus would stop near my house.
fare – the amount of money one has to pay to ride a bus, train, boat, or other form of transportation
* I wanted to ride the bus home from school, but the fare was too high, so I walked.
single ticket – one ticket; one pass used to get on a bus or a train, or to watch a performance
* Since I was going to the concert alone, I only bought a single ticket.
booklet – a small book with a few pages; a small book of many tickets
* Mrs. Godoy needed enough tickets for her entire kindergarten class, so she bought a booklet of 50 tickets.
bus pass – a small card or piece of paper that allows a person to ride the bus without paying for each ride separately; a card or piece of paper that one pays for before riding the bus so that ones does not have to pay each time he or she rides
* With a bus pass, I don’t have to worry about carrying money with me when travel around the city.
transfer – a piece of paper that allows one to get off of one bus or train and get onto another one without paying additional money; to move something from one place to another
* Get a bus transfer before you get off the first bus and give it to the bus driver of the next bus you ride.
bus stop – a place (usually with a bench or a roof), where a person can stand and wait for the bus; the place near the end of a street where a bus stops to let people get on or off
* I waited at the bus stop for over an hour before the bus finally arrived.
to pull up – for a vehicle to stop; to drive up to a place and stop
* As I waited at the end of the street, my father pulled up in the car to drive me home.
to get on – to step or climb up onto something; to go through open doors to enter a bus or train
* As soon as the rollercoaster stopped, I got on.
stop – a bus stop; the place where a bus or a car stops to let people get on or off
* By the time that the bus drove down the street, there were already twelve people at the stop waiting for the next bus.
to get off – to climb off of something; to climb down; to leave a bus or train
* I got off the bus at the end of Sasha’s street so that I could go visit her.
to ring – to cause something to make a sound like a bell that brings attention to it; to make a sound using a bell or a buzzer
* When the phone rang, I knew I had to answer it.
to be delayed – to be late; to not be on time; to be forced to do something at a time later than expected
* Because of the rain, the baseball game was delayed.
to break down – to stop working; to not function properly, usually used for machine
* On my way to the dance, my car broke down and I had to fix it.
route – the streets and path that a car or vehicle drives on to get somewhere; the way that one travels to get from one place to another
* Seymour was late to the party because he made a wrong turn and ended up taking the long route around the lake to get there.
Culture Note
Carmageddon
A “neologism” is a newly created word that has not yet been widely accepted or used, a word not found in a dictionary. Neologisms are often the result of some new event or activity, and sometimes are formed by changing or combining existing words. For example, the word “Armageddon” refers to the end of the world, as some people think is “depicted” (shown; described) in the last book of the Christian Bible. The term is more generally used now to mean a terrible disaster, bigger than anything previously seen.
That brings us to the neologism “Carmageddon,” a combination of the words “car” and “Armageddon.” So what is the Carmageddon? The term was used to describe something that happen in Los Angeles on July 16 and 17, 2011, when a 10-mile “stretch” (section of a road or highway) of one of the “major” (most important; busiest) freeways – Interstate 405 -- was completely closed for more than two days for “construction” (building). Some experts predicted that this would be a big disaster, with people unable to move or travel “due to” (because of) all of the “traffic” (cars) that would be “diverted” (moved) to other streets and freeways. People expected large “traffic jams” (where cars are stopped or are moving very slowly) on all of the streets and roads. The 405 Freeway in Los Angeles “carries” (has on it) more than 280,000 cars per day.
It is important to understand that closing a freeway in Los Angeles is unlike a similar event in most other cities. Los Angeles has a ‘”car culture,” where owning and driving a car is considered “essential” (necessary) for most people. Los Angeles does not have a good public system of transportation like other big cities in the U.S., such as New York or Chicago, so almost everyone drives.
People were told to stay home that weekend, not to try to drive anywhere unless it was an emergency. The warnings must have worked, because despite all of the predictions, there were no major problems. Perhaps because everyone expected major traffic jams, they stayed away from the 405 Freeway. Although Carmageddon did not turn out to be a big disaster, the term will always be associated with major traffic problems.