= 0179
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast Number 179, “Shopping for a Cell Phone.”
This is English as a Second Language Podcast Number 179. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today's podcast is called, “Shopping for a Cell Phone.” Let's go.
[start of story]
Greg: I needed a new cell phone, and my friend recommended the company he used. I went into the store to take a look.
Woman: Hi, have you been helped?
Greg: No, I haven't. I'm looking for a new phone.
Woman: Are you with our company right now?
Greg: No, I'm thinking about switching.
Woman: Okay, let me show you our most popular phone. This one has a lot of good features. It's got a camera phone, a video recorder, instant messaging, and you can download music or ring tones.
Greg: I'm really looking for a flip phone.
Woman: Oh, in that case, this is the one you want. Let me tell you a little about our plans. With our $59.99 plan, you get 400 minutes, unlimited night and weekend minutes, and free mobile-to-mobile.
Greg: Do the minutes roll over if I don't use them all in one month, and do I need to sign an agreement?
Woman: We don't have rollover minutes, but if you think 400 isn't enough, we have higher plans for 700, 1000, and unlimited minutes. The $59.99 plan requires a one-year agreement.
Greg: Okay, let me think about it.
Woman: No problem. Just let me know if you have other questions.
[end of story]
We're looking today to buy a new cell phone or cellular phone. “Cell” is short for “cellular.” These are often called mobile phones as well, but most people now call them a cell phone, or simply a cell. Someone says, “I don't have my cell with me,” they mean their cell phone. Well, in the story, the person in the story, Greg, he needs a new cell phone, and his friend recommended the company he was using. In the United States, there are probably four or five big companies that you can get cell phone service from. And so, in this case, in this story, he goes to the store where that company has their phones. Many of the companies have their own stores. There are some stores that sell for different companies. So, you can look at two or three different companies in one store. It depends on the company that you are interested in.
Well, the salesman begins by saying, “Hi, have you been helped?” So, the salesperson walks up - it’s a salesperson here, not a salesman because it’s a woman; so it’s a saleswoman. The saleswoman walks up to Greg and says, “Have you been helped?” meaning, Is anyone helping you? Has someone come up to you already and asked to help you? The other expression you might hear when you walk into a store is “May I help you?” Do you need any help? You may also hear someone say, a salesperson say, “Can I help you find anything?” and you either say, “Yes, I'm looking for this…,” or you say, “No thanks, I'm just looking.” You can also say “No thank you, I'm just browsing.” “To browse” means to be looking, but at a very relaxed rate…very…not in a hurry.
Greg says that he hasn't been helped, that he's looking for a new phone, which is a good thing because he's in a cell phone store. Greg's a smart person. The salesperson says, “Are you with our company right now?” What she means is do you have a phone, a cell phone right now that's connected with our company that you get telephone service with our company. So, she says, “Are you with our company?” meaning do you have a contract, do you have a plan right now for your phone with our company. Greg says, “No, I'm thinking about switching.” “To switch,” as a verb, means to change, to change one thing for another thing. So if you own a Windows PC, a Windows computer with Microsoft Windows operating system and you decide to switch to a Mac, like I did, that would be a use of that verb, “to switch.” To take one thing and to put something else there instead.
So, Greg is thinking of moving, or switching, to this company. The saleswoman says, “Okay, let me show you our most popular phone. This one has a lot of good features.” A “feature” is something about the thing that you want to buy, some good thing about the item or the thing that you are buying. Almost anything can have features. A computer can have different features. One of its features is it has a small screen or it has a good keyboard or it has lots of memory. Those would all be features of a computer. The features of a cell phone of course are different. The saleswoman says, “I've got a camera phone,” or rather the phone she is showing him has a camera phone. She says, “It's got a camera phone.” That's a somewhat informal use for it has a camera phone, but it's very common: “It's got a camera phone.” A “camera phone,” you probably know, is a little camera inside the cell phone. You can take a picture. A “video recorder,” and here is again with a little camera you can record a small movie, a video recorder.
Instant messaging - so you can use your phone to talk to somebody else. Usually, instant messaging on a phone, it is with what we call “text” or “text messaging.” Text messaging is when you send a message to someone else's phone by using the letters that are on what we would call the “pad” or the “keypad” of the phone. The pad or the keypad of the phone is the numbers that you press. And, of course, the numbers have letters connected to them that you can send a message. You can also download music or ring tones with this phone. Well, to “download,” you know from the Internet means to take something from one computer and put it on another computer. So, you can download things onto this phone. In this case, you can download music. Some of the phones now you can download music directly from iTunes, for example. Or, you could download ring tones. “Ring tones,” two words, is the sound that the phone makes when it rings, and many people have special ring tones that are songs or different kinds of music. I don't have any of this. I just have whatever the ring tone that was in the phone when I bought it. That's my ring tone.
Greg says, “I'm looking for a flip phone.” A flip phone is a phone that opens up. Some phones you just have a little phone, and you don't have to open anything. A flip phone is one that you flip open or you open up. I have a flip phone, for example. The saleswoman says, “Oh, in that case, this is the one you want.” “In that case,” meaning in that situation. Oh, for your situation, for what you want, this is the phone for you. So, in that case, this is the one you want.
“Let me tell you a little about our plans “ she says. Their “plans” for a cell phone mean the amount of minutes that you get, and the kinds of things you get with your cell phone. In the story, the plan has 400 minutes, unlimited weekend and night minutes, night and weekend minutes. “Unlimited” means, of course, that there is no limit, that you can use as many as you want. So, you get 400 minutes during the day, unlimited night and weekend minutes, and free mobile-to-mobile. “Mobile-to-mobile” or “cell-to-cell” means that you can call another cell phone that has the same company and they won't charge you any money. All of this is for $59.99, fifty-nine dollars and ninety?nine cents. Sounds like a great deal.
Many times the cell phones in the United States now will also come, the newer phones will come with a voice plan and a data plan. The voice plan is for using your phone as a regular phone to talk to people. The data plan is when you use your phone to connect your computer to the Internet, for example, and those phones are more expensive and the plans are more expensive. I think the typical phone with the Internet connection on it would probably be about $80 a month or so.
One thing you need to understand if you don't live in the United States is that the United States, in terms of its cell phones, is not as advanced as other countries, especially in Europe and Japan. We are, just this year really, getting good phones that you can connect to the Internet. Many of the best cell phones that are in Europe and Japan are not here in the United States.
Well, Greg asks the saleswoman if the 400 minutes that he gets will roll over. “To roll over,” as a verb, means that…let's say you have 400 minutes in July, and you only use 200 minutes. If the minutes roll over, in August you would have 600 minutes: 400 for August and then 200 that rollover from July. So, Greg is asking if the minutes roll over from month to month. He also wants to know if he has to sign an agreement. An “agreement” here means the same as a contract, saying I will be a customer for one year or two years or 25 years. Probably not 25 years, but at least a couple of years. The salesman says—I’m sorry, the saleswoman–says, “We don't have rolllover minutes,” but if 400 minutes a month isn't enough, they have plans that you can buy more minutes with. Greg says, “Okay, let me think about it,” and the saleswoman says, “No problem” - means It's okay, no problem. We use that expression “No problem” a lot. It's something that you would say to someone who, for example, thanks you for something. “Thank you for helping me.” You might say “No problem.” Here, no problem means don't worry, go ahead, and take your time to think about it. The saleswoman ends by saying, “Just let me know if you have any other questions.”
Now let's listen to the dialogue, this time at a native rate of speech.
[start of story]
Greg: I needed a new cell phone, and my friend recommended the company he used. I went into the store to take a look.
Woman: Hi, have you been helped?
Greg: No, I haven't. I'm looking for a new phone.
Woman: Are you with our company right now?
Greg: No, I'm thinking about switching.
Woman: Okay, let me show you our most popular phone. This one has a lot of good features. It's got a camera phone, a video recorder, instant messaging, and you can download music or ring tones.
Greg: I'm really looking for a flip phone.
Woman: Oh, in that case, this is the one you want. Let me tell you a little about our plans. With our $59.99 plan, you get 400 minutes, unlimited night and weekend minutes, and free mobile-to-mobile.
Greg: Do the minutes roll over if I don't use them all in one month, and do I need to sign an agreement?
Woman: We don't have rollover minutes, but if you think 400 isn't enough, we have higher plans for 700, 1000, and unlimited minutes. The $59.99 plan requires a one-year agreement.
Greg: Okay, let me think about it.
Woman: No problem. Just let me know if you have other questions.
[end of story]
The script for today's podcast was written by Dr. Lucy Tse. Remember, if you have ideas or questions about our podcast, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
Have you been helped? – another way of asking “can I help you?”
* I walked into a store and right away, a salesperson asked, “Have you been helped?”
to be with our company – to be using a product or service of a business or group
* You would be paying less for your internet if you were with our company.
to switch – to change from one to another
* He moved all of the time so he was always switching jobs.
features – parts of a product, service, or thing
* One of the best features of vacationing in Mexico are the great beaches.
camera phone – a phone that can take and keep pictures like a camera
* She forgot her camera at home, but luckily, her friend had a camera phone with her.
video recorder – a machine that can record video or movies
* No one saw who broke the window, but the store has a video recorder running 24 hours a day, so they should be able to find who did it.
instant messaging – an internet program that lets you talk to people by typing, sending, and getting back messages at the same speed of speaking
* She didn’t call me, but she told me by instant messaging to meet her at six o’clock.
download – to get something from the internet and keep it in your computer or phone
* It took 20 minutes for my computer to download that movie!
ring tones – the sound or music your phone makes when you get a call
* My phone has fifteen different ring tones.
flip phone – a cell phone that you fold open to use
* Her new flip phone is so small that it can fit in her pocket.
in that case – another way of saying “if that should happen”
* She has a test tomorrow? In that case, she can’t go to the movies tonight.
plan – the type of service that a company or business can offer for a set amount of money
* The two plans looked the same so I chose the least expensive one.
unlimited – without limit; as much as possible
* His parents are rich so he has an unlimited amount of money to spend.
mobile-to-mobile – a cell phone call made to another cell phone
* I only call her mobile-to-mobile because I’ve forgotten her home telephone number.
to roll over (verb)/rollover (adjective) – to take something from one to the other
* If I change banks, the money from my old account will roll over into the new account in twenty-four hours.
agreement – where people or groups promise each other something
* We have an agreement that if she gets an A in the class, I would take her to Disneyland.
Comprehension Questions
1. Why doesn’t Greg like the first phone the salesperson shows him?
a) It’s not a camera phone.
b) It’s not a flip phone.
c) It’s not a phone that can download music and ring tones.
2. Which is not a feature of the phone the salesperson shows Greg:
a) E-mail.
b) Video recorder.
c) Instant messaging.
Answers at bottom.
What Else Does It Mean?
plans
The word “plans,” in this podcast, means the types of service that you can choose for a set amount of money: “Which plan gives me the most minutes each month?” But “plans” can have different meanings. It can mean the design of an object to be built: “She drew plans for the house she wanted to build.” Or, “The plans for the new machine don’t work.” “Plans” can also be used to mean what someone is going to do in order to reach a goal: “We made plans to save money for a vacation.” It is also used in phrases like “according to plans,” which means for something to happen without problems: “The party went according to plans.”
with our company
In this podcast, the phrase “with our company” means to be a customer of a company or business: “If you are already with our company, you will get a discount.” But it can also mean to be working for a company: “His name tag let me know that he was with our company.” Or, “Jan has been with our company for over 30 years.” Although “with our company” is a common phrase, “with our…” can be used with other words, too, such as “with our group,” “with our team,” or “with our school”: “That teacher has been with our school since she graduated from college.”
Culture Note
In the U.S. today, cell phones are very common, so common that they have created problems. In some states, places such as law courts, schools, and churches now ask people to turn off their cell phones before entering the building. In places like movie theaters, people are asked to use their cell phones only outside theater. However, most restaurants have no restrictions on the use of cell phones and it is common to see and hear people answer their cell phones or make cell phone calls in a restaurant.
Using a cell phone while driving has been the cause of many accidents on the road. In 2001, the state of New York passed a law prohibiting, or not allow, people to drive and talk on the cell phone at the same time. However, the law does allow people to dial, or call a phone number, while driving and they can use a “hands-free kit,” so they can talk on their cell phones without holding it in their hands. Other states, like California, are thinking about passing a similar law.
There are usually rules about using cell phones in schools. However, since schools are governed by each state and not by the federal, or national, government, the rules may be different from one state to another, and from one district (group of schools, usually in one city or part of a city) to another. Some schools have banned, or made a rule against, using cell phone completely. Other schools do not allow students to use cell phones in class, but they may use them in between classes or after school, even if they are still in the school building.
Comprehension Answers
1 - b
2 - a