= 0195
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 195, “At an Amusement Park.”
You're listening to English as a Second Language Podcast episode 195. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today's podcast is about having fun at an amusement park. Let's go!
[Start of story]
My brother, his wife, and their two daughters are in town and I had promised the girls that I would take them to an amusement park. I don’t really like roller coasters, but I knew the kids would like it.
On Saturday morning, we drove down to the theme park. We parked and took a shuttle to the park entrance. We looked at the ticket prices and decided to buy a day pass for each of us. Maria, the younger of the two kids, is only 2-years-old, and children under three get in free.
The first thing we did was stand in line for the biggest attraction in the park: a really big roller coaster. Actually, only Grace and I stood in line since Maria was too young to ride it. My brother and my sister-in-law took Maria to ride the Ferris wheel and carousel, and afterwards, we planned to meet near the concession stands so we could watch the parade at 2 o’clock. Grace and I finally made it to the head of the line and we got on the ride. I really don’t like roller coasters. When we got off, I felt queasy and had to sit down for a few minutes before I could walk again.
All in all, we had a good day at the amusement park. But, it will be long time before I go on a roller coaster again!
[End of story]
Today's podcast is called, “At an Amusement Park.” An amusement park, “amusement,” park, “park,” is a place where they have lots of fun things to do, usually there are lots of rides. A ride, “ride,” in an amusement park means that these are machines that you can get on and they'll take you up and down and all around, you can go in circles. There are lots of different machines that we call, in an amusement park, a ride. So, a ride is a fun thing that you do in an amusement park.
An example of a ride would be a roller coaster, “roller coaster.” A roller coaster is a ride where you usually sit in a little - looks like a little car; it's a very small space where you sit. There are lots of these little cars that are connected, and you go on what looks to be a mountain or a hill that goes up and down, up and down, and you ride it like you would on a train, except it goes up and down and around. A roller coaster is an example of a ride at an amusement park.
In our story, I say that, “My brother, his wife, and their two daughters are in town,” meaning they are visiting us from another town. I live in Los Angeles; they live in St. Paul/Minneapolis area of the state of Minnesota, so when they visit and stay here, we say they are in town. Well, they're “in town and I had promised the girls” - the two daughters, my - what we would call nieces, “nieces,” those are the daughters of my brother's family. The boy would be called a nephew, “nephew.” Well, I took my two nieces to the amusement park. “I don’t really like roller coasters,” I said, “but I knew” that “the kids would like it.” So, “On Saturday morning we drove to the theme park.” A theme, “theme,” park is a type of amusement park. It's usually an amusement park that has one special, or one particular idea - one main idea for the park. This could be, for example, Disneyland or Disney World. Disneyland is here in Southern California; Disney World is in Florida - the state of Florida, and there are other Disney theme parks in different cities. There's one outside of Paris; there's one in Hong Kong. And these are amusement parks where everything is based on, or comes from a Disney cartoon or a Disney movie that is famous and people will recognize. You can also have an amusement park that is not a theme park, that you'd go to and there are just lots of fun rides, but there isn't any particular main idea. A main idea is also called a theme, and that's why we have the word theme park.
We went to “the theme park. We parked and took a shuttle to the park entrance.” A shuttle, “shuttle,” is a small bus that takes people a very short distance, usually from one part the parking lot to the place where you go into the park, what we would call the entrance, “entrance.” So, a shuttle can take you from a parking lot to the airport, or it could take you from one side of a university campus to another side of a college or university campus. A shuttle can also be what we call a van, “van,” which is a big car that you can put, maybe, seven, eight, ten people in. If it's bigger, it would probably be called a bus.
Well, we took the shuttle to the entrance, and that's the place where you buy your ticket, usually, and walk into the park. We use that word, entrance, for a park, but you could also use it for a building or for anywhere where you have to go into something, that would have an entrance, the place where you enter.
We went into the park entrance and we looked at the price of the ticket, that would be the ticket that would get us into the park, and we “decided to buy a day pass for each of us.” A day pass, “pass,” is the same as a ticket for the whole day. You could also buy a month pass, or a monthly pass, and that would get you into the park every day for one month. My brother's youngest daughter was only two-years-old, so she got in for free, or she got in free. To get in free means you do not have to pay any money, and for many parks and other places, children under five, or under three, sometimes even under 12-years-old - they are less than 12-years-old - don't have to pay in order to enter into the park and use it. The same is true in a theater, for example. Some movie theaters, you get in free if you are less than a certain age.
Well, “The first thing we did” is “stand in line for the biggest attraction in the park.” To stand in line means that you wait with other people in a line. In Great Britain this is called queuing; to queue means to stand in line. The attraction is one of the interesting things about the park, so a theme park like Disneyland has many attractions. There are the rides, but there are also shows and other things that happen in the theme park that could be called attractions. Well, the biggest attraction was the roller coaster, and so one of my nieces, Grace and I, we “stood in line, and my brother and sister-in-law took Maria,” my younger niece, “to ride the Ferris wheel and the carousel.” I said that it was “my brother and my sister-in-law;” my sister-in-law is my brother's wife. So, my sister-in-law and my brother took Maria to the Ferris wheel. Ferris wheel, “Ferris wheel,” two words, is a ride that you sit in a little car, but the whole thing is like a big circle. The circle goes around, and you go to the very top, so you're very high off the ground, and then the circle comes back around and you're at the bottom. So, it's a round wheel that goes up into the air.
A carousel is also a wheel, but it's a wheel that is completely on the ground. You don't go up; you just go around in a circle. Carousels, which are also sometimes called merry-go-rounds, “merry-go-round,” a carousel or a merry-go-round is a wheel that goes around. Usually, there are fake horses - plastic horses that the little children can sit on, and the horses go up and down, just one or two feet, as the wheel goes around. That's a carousel.
After, we had decided that we would go to “the concession stands so we could watch the parade at two o'clock.” A concession stand, “concession,” stand, “stand,” is a place in a amusement park, or at a baseball or football stadium where you can buy food and something to drink. A parade, “parade,” is when you have people who walk down the street; usually they are dressed to look like someone. Sometimes you have musical bands, in a parade, that are playing music, and you sit on the side of the street and you watch them walk down the street in front of you.
Well, Grace and I - my niece and I - were waiting in the line and we “finally made it to the head of the line.” To make it to the head of the line means you are in the front or you are the person that is now able to buy their ticket - you are at the front of the line. Well, “we got on the roller coaster,” and I said, “I don't like roller coasters. When we got off” the roller coaster - when we exited the roller coaster, “I felt queasy.” To feel queasy, “queasy,” means that you feel sick, like you might vomit, “vomit,” or throw up, which means that what's in your stomach comes out of your mouth. Not a very nice thing! But, that's if you feel queasy, you feel that you might have to vomit, or you might have to throw up, so your stomach doesn't feel very good. If you eat 25 hot dogs at one dinner, you might feel a little queasy, for example.
I end the story by saying, “All in all, we had a good day.” All in all means considering everything. If we think about the whole day, or the whole situation, we had a good time.
Now, let's listen to the story, this time at a native rate of speech.
[Start of story]
My brother, his wife, and their two daughters are in town and I had promised the girls that I would take them to an amusement park. I don’t really like roller coasters, but I knew the kids would like it.
On Saturday morning, we drove down to the theme park. We parked and took a shuttle to the park entrance. We looked at the ticket prices and decided to buy a day pass for each of us. Maria, the younger of the two kids, is only 2-years-old, and children under three get in free.
The first thing we did was stand in line for the biggest attraction in the park: a really big roller coaster. Actually, only Grace and I stood in line since Maria was too young to ride it. My brother and my sister-in-law took Maria to ride the Ferris wheel and carousel, and afterwards, we planned to meet near the concession stands so we could watch the parade at 2 o’clock. Grace and I finally made it to the head of the line and we got on the ride. I really don’t like roller coasters. When we got off, I felt queasy and had to sit down for a few minutes before I could walk again.
All in all, we had a good day at the amusement park. But, it will be long time before I go on a roller coaster again!
[End of story]
The script for today's podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
amusement park – a large outdoor area with rides, food, games, and entertainment
* How many rides do you plan to go on at the amusement park today?
roller coaster – a ride at an amusement park where people sit or stand in small cars and the cars go along a thin track moving very fast
* This is the fastest and most dangerous roller coaster in the world!
theme park – an amusement park that is built around one main idea
* Both Disneyland and Universal Studios are popular theme parks in the southern California area.
shuttle – a car, van, or bus that travels regularly between two places, usually a short distance
* Since so many of our employees live in that new housing area, the company is thinking providing them with a shuttle to work.
entrance – an opening, such as a door or a gate, where people enter a place
* I walked around the building three times, but I still couldn’t find an entrance.
day pass – a ticket that allows people to have access to a place or to use services for an entire day
* If you plan to be there more than three hours than I think it worth it to buy a day pass.
to get in (for) free – to enter a place for free that normally charges a fee
* If you get to the theater ten minutes before a performance and there aren’t very many people in the audience, you may get in for free.
to stand in line – to wait with other people by standing one in front of the other
* No matter what time you go to get your driver’s license, you’ll need to stand in line for at least an hour.
attraction – a place or thing that visitors want to see
* There are so many attractions in Hong Kong. I think we should stay more than three days on our visit.
sister/brother-in-law – a woman (sister-in-law) or man (brother-in-law) who is married to your brother or sister
* Whenever I go to San Antonio for business, I always stay with my sister and brother-in-law.
Ferris wheel – a ride at an amusement park; a very large round wheel with people sitting its small cars as it goes around and around
* You can see the entire city from the top of the Ferris wheel.
carousel – a ride with fake horses and other animals that people sit on as it goes around and around; also called a “merry-go-round”
* The younger kids like to ride the carousel at the park.
concession stand – a place where you can buy drinks and food; also called a “refreshment stand”
* When you go to the concession stand, can you get me a hot dog and some candy?
parade – a celebration with people dressed in special clothing walking along a path, often with music; usually to celebrate a special day or event
* This year, our school band is marching in the Independence Day parade.
head of the line – to be at the beginning of a line; to be the next one to be served
* The store was just closing when he finally got to the head of the line.
queasy – to feel sick in your stomach
* Our whole family felt queasy after eating too much at the party.
all in all – after everything has been thought about; considering the entire situation or event
* I wasn’t sure if I would like camping, but all in all, I had a good time.
Comprehension Questions
1.Why did the man in the story go to an amusement park?
a) He likes to ride roller coasters and Ferris wheels.
b) He wants his brother and sister-in-law’s children to have fun on their visit.
c) He likes to feel queasy.
2. Who went on the roller coaster?
a) Grace
b) Maria
c) the entire family
Answers at bottom.
What Else Does It Mean?
to get in (for) free
The phrase “to get in (for) free,” in this podcast, means to enter a place without paying: “My brother works at that movie theater and he told me that we could get in for free.” Another term we use for getting entry to a place without paying is “free admission”: “There was a sign at the store that read: ‘If you buy 10 cans of corn, you can get free admission to a movie.’” A more formal way of describing something that is free is to use the term “complimentary,” such as “complimentary tickets,” or “complimentary drinks” at a bar. An informal way of talking about free things is to use the word “freebie”: “I got this hat as a freebie when I went to the opening of that new store.”
attraction
In this podcast, the word “attraction” means places or things that visitors like to see: “One of the most popular attractions in Washington DC is the White House.” “Attraction,” as a noun, can also mean a romantic feeling you feel toward someone else: “As soon as I met him at the party, I knew that we had a strong attraction.” There was a popular 1987 American movie called “Fatal Attraction,” where a man has a romantic relationship with a woman who is not his wife. The man tried to stop seeing the woman, but she does not want to stop their relationship, and she does terrible things to him and his family. Now, the phrase “fatal attraction” is use to describe a situation where one person wants to end a relationship but the other person does not, and continues to bother the other person: “I hope this isn’t one of these fatal attractions.”
Culture Note
Most people around the world know that Disneyland (in California) and Walt Disney World (in Florida) are popular theme parks in the U.S. But, there are many theme parks around the country that you many not have heard of.
One of these is Dollywood, which is a theme park located in Pigeon Falls, in state of Tennessee, in the southern part of the United States. Dollywood is partly owned by a well-known country singer named Dolly Parton, who became famous in the 1970’s and 1980’s when she had many “hit,” or very popular, songs. Dollywood has many of the rides you would find at other amusement parks, but it also has country music entertainment and “crafts,” or handmade things, from the southern part of the U.S.
Another amusement park that is not as well known is Cedar Point in Sandusky, Ohio, a state near the center of the country. Cedar Point is the largest amusement park in the world and is located on 364 acres, or 1.5 kilometers. It has 16 roller coasters, including the second tallest roller coaster in the world. The park also has a long beach area, two “water parks,” or amusement parks with rides and games that use water. It is the second oldest amusement park in North America. (The oldest is Lake Compounce, an amusement park in Connecticut, in the northeastern part of the U.S.)
Comprehension Answers
1 - b
2 - a