= 1589
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 284.
This is English as a Second Language Podcast’s English Café episode 284. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some help in improving your English.
On this Café, we’re going to talk about a famous American by the name of John Audubon and the Audubon Society, which is an important conservation organization in the United States. We’ll also continue our series on famous songs, in this episode focusing on “On Top of Old Smokey”. And, as always, we’ll answer a few of your questions. Let’s get started.
John Audubon was not born John Audubon; he was born with the name Jean Rabin in Haiti in 1785. Haiti is a country in the Caribbean, southeast of the United States; Haiti was ruled by the French. Jean Rabin was born there, but he spent most of his childhood in France. At the age of 18, however, he decided to come to the United States, and he changed his name from Jean to the English version John; actually, he changed his name to John James, and from Rabin to Audubon. He eventually became the most famous American “ornithologist,” or a scientist who studies birds.
Even as a young boy, John always liked birds. He enjoyed observing them and, perhaps most importantly, sketching them. To “sketch” (sketch) means to draw, especially to create a quick drawing of something to help you remember it later. John enjoyed walking outdoors and observing birds. He was what we would call a “naturalist.” A “naturalist” is a person who’s interested in nature, things outside of buildings and houses.
What made Audubon famous – and people still know his name now in the United States – was his ability to draw, and to illustrate those drawings of birds in a way that was much more realistic than other artists were doing at the time. “To illustrate” means to draw, usually something that will be in a book or a magazine, often to explain a concept or to show what something looks like. Photography was still a very new idea in the 19th century when Audubon was working. In addition to his illustrations, Audubon also conducted the first bird-banding experiments. A “band” is a small piece of metal or plastic that’s in the shape of a ring. A “bird-band” is a band placed around the leg of a bird in order to identify specific birds and to be able to track them; that is, to be able to tell when they left and when they came back.
Later, Audubon studied “taxidermy” (taxidermy). Taxidermy is basically taking dead animals and putting things inside of them so that they look like they are live animals, often to be shown in a museum. Audubon began collecting dead birds and animals in order to create a museum.
He continued to improve his drawing, painting, and taxidermy skills, and eventually his collection of different kinds of birds – different bird species – became larger. He wasn’t able to make very much money in the United States, but in 1826 he took his drawings of the birds to England, where they were very popular. He printed a book, his most famous book, called Birds of America, which had 435 “prints” or images of his drawings and paintings, representing almost 15 years of work. Audubon was particularly famous for illustrating birds in their real size, so that he had even large birds on large pieces of paper so that you could see how big the bird actually was, what we would call “actual size,” or perhaps more commonly “life size.” When something is “life size,” it is the actual size it is in real life.
John returned to the United States and continued to work as a naturalist and an artist, publishing his second book, Ornithological Biography. He, himself, discovered 25 new “species” or types of birds, and was elected to several important scientific organizations before he passed away or died in 1851.
Today, they are many places are named after Audubon, there is a city of Audubon in Pennsylvania, which is in the eastern part of the U.S.; there is an Audubon County, which is a division or a section of a state, in the state of Iowa, in the center part of the U.S.; and there’s also a John James Audubon State Park in the state of Kentucky in the central-eastern part of the U.S. People now think of Audubon as being one of the first environmentalists in the U.S., people who care about the natural environment and want to help it and protect it.
It is because of Audubon’s fame, his being well known as a naturalist and an illustrator, that when an organization was started to help continue his work in protecting and preserving the environment it was named after him. This organization, called the National Audubon Society, was created in 1905, more than 50 years after he died. The National Audubon Society is still around; that is, it is still active. It is a very important conservation organization that works to protect and conserve the national environment. Unhappily, several of the birds that Audubon studied have already become extinct, meaning that all of the species has died, often because of things done by we humans. The National Audubon Society tries to prevent other birds and animals from becoming extinct.
The Society is made up of 500 local chapters. A “chapter” is like a small organization that is part of a larger organization. Members in the Audubon Society participate in bird-watching activities, where they go out and try to identify different kinds of birds, as well as in conservation-related activities. I, myself, have never gone bird watching; I’ve never really been that interested, but I know few people who are very avid bird watchers. “Avid” (avid) is someone who does something a lot, and with great enthusiasm.
Now let’s continue on the Café to our series on famous songs. Today we’ll be talking about – and of course I’ll be singing – a song known to most Americans, especially American children, called “On Top of Old Smokey”. It’s a folk song – a traditional song – that has been sung for many years, especially by people from a particular area. The phrase “Old Smokey” seems to refer to the name of a mountain; we have the Smoky Mountains in the eastern part of the United States. This song seems to refer to a mountain either in that area or in a set of mountains in the more central part of the U.S., the Ozarks, but nobody actually knows for sure what mountain it refers to.
There are many different verses or sections of the song – different parts of the lyrics. We’ll go back and talk about each one of these. I’ll start by singing the first two verses, and then we’ll explain what it is all about.
On top of Old Smokey,
All covered with snow,
I lost my true lover,
For courting too slow.
For courting’s a pleasure,
But parting is grief,
And a false-hearted lover,
Is worse than a thief.
It’s a sad love song about a man who did not get the woman that he wanted for romantic purposes. It begins by saying “On top of Old Smokey (so on top of perhaps this mountain) all covered with snow (meaning the snow is on top of the mountain), I lost my true lover for courting too slow.” His true lover is the person that he was in love with, and perhaps was in love with him. Why did he lose her? Because he courted her too slowly. He says, “I lost my true lover for courting too slow.” The reason was he was courting too slow. “To court” is an old word – an old idea, perhaps – that is similar to what we would now more commonly call dating. It was a way to show a woman that you were interested in her. While you were courting her, you may go to her home and spend time speaking with her. It wasn’t like dating – or isn’t like dating in a modern sense, where you go to a bunch of movies and have dinner. It was a more traditional form of a man expressing interest in a woman that he wanted to be his wife. Unfortunately, the person in this song courted too slow, meaning he took too much time perhaps before he asked her to marry him, and so what happened is that he lost her. He did not get to marry her; she married someone else.
The second verse says that courting, this process of trying to get a woman to marry you, is a pleasure, but parting is grief. “Parting” means separating, or being separated from someone, in this case from your true love. “Grief” (grief) means extreme sadness, usually because someone has died, but here because he has lost his true lover. So the second verse is “For courting’s a pleasure (meaning courting is a pleasure), but parting is grief (separation is sadness), and a false-hearted lover is worse than a thief.” A false-hearted lover would be someone who tells you that he loves you, or she loves you, but isn’t really in love with you, and that sort of person is worse than a thief. A thief is someone who steals things; a thief is a criminal; we might also call him a robber, someone who robs you or steals things from you. A false-hearted lover who says that he or she loves you, but doesn’t, is worse than a thief; they steal your heart.
There are other verses, but rather than sing those lyrics I’m going to tell you about a more famous, in some way is, version of the song, what we would call a parody. A “parody” (parody) is a funny imitation or copying of something; it’s making fun of the original version. For example, there was a parody of the movie Star Wars called Spaceballs; that’s an example.
Many parodies have been made of the song “On Top of Old Smokey”, but the best-known one, the one that I learned as a child, is called “On Top of Spaghetti”. “Spaghetti” is the food, what we call a pasta, long, thin noodles that are served with tomato sauce and usually balls of meat – meatballs. It’s an Italian dish – an Italian kind of food. Here are the parody words that were created by a singer named Tom Glazer in 1963 as a children’s song.
On top of spaghetti,
All covered with cheese,
I lost my poor meatball,
When somebody sneezed.
It rolled off the table,
And onto the floor,
And then my poor meatball,
Rolled out of the door.
So, “On top of spaghetti (on the top of your plate of spaghetti), all covered with cheese (instead of snow, as in the original version), I lost my poor meatball,” “my poor,” here, means my unfortunate meatball – remember, a meatball is just a round ball of meat, of beef usually. He lost the poor meatball when somebody sneezed. “To sneeze” is to go “a-choo!” So, obviously when the person sneezed they blew the meatball, we assume, off of the plate. Then, the meatball rolled off the table, meaning the meatball rolled on the table and then fell down onto the floor, and then it continued rolling out of the door, meaning it went past the door into the outside – into the garden or into the lawn.
It’s a silly song. The rest of the song – and there are more verses to the song – talk about how the meatball eventually goes into the garden and grows into a meatball tree, which of course is impossible. It’s a silly song. Many children like it, and I bet most Americans can sing at least some of the words because they remember them from their own childhood, at least those from my generation. So one more time with the parody:
On top of spaghetti,
All covered with cheese,
I lost my poor meatball,
When somebody sneezed.
It rolled off the table,
And onto the floor,
And then my poor meatball,
Rolled out of the door.
Now let’s answer some of your questions.
Ana (Ana) from Brazil wants to know the difference between “sign” (sign) and “signal” (signal). Well, you can tell they’re pronounced somewhat differently. “Sign” is pronounced the “g” silent; “signal” includes “g” in the pronunciation.
“Sign” can have a couple of different meanings. A “sign” can be an action to communicate an idea or an object to communicate an idea. “The police officer gave the sign for the cars to move forward (to move ahead).” Maybe he moved his arm back and forth. That’s a sign; it indicates something, it communicates an idea. A “sign” can be a written symbol that stands for an idea. In mathematics, what we call in English a “plus sign” (+) indicates that you add two numbers together; a “minus sign” (-) means that you subtract one number from the other. That’s a sign.
A “sign” can also be something that has been left behind, an indication that there was something here. If you are walking in the outdoors and you see little holes in the ground, you can look carefully and you may be able to tell if they were made by an animal. Those little holes in the ground are signs that that animal was there.
A “signal” has a similar use as the first meaning I gave for “sign,” that is, an action to communicate an idea. For example: “The police officer waved his hands (moved his arms back and forth) giving the signal for the cars to move forward.” We refer to a traffic signal as three lights – red, yellow, and green – that indicate whether you should stop, go forward, or move forward with caution – carefully.
“Signal” has an additional meaning, which is communication that is transmitted via, or through, something like radio waves; they’re transmitted through the air. So, you might have radio waves that come into your radio and you’re able to listen to radio stations. Those waves – we call them, just like the waves in an ocean – would be called a radio signal. You have television signals. You even have, for your computer, things like Wi-Fi signals.
It’s often difficult to figure out when to use “sign” and “signal” in the first definition that I gave, meaning communicating an idea. Sometimes we use “signal,” sometimes we use “sign.” When you’re talking about traffic, for example, a traffic signal is almost always something that is electric with lights, often lights that change colors or turn on and off quickly – flash, we would say. However, things like pieces of metal or wood that say “stop” or “yield,” those are traffic signs. When they are just painted on a piece of metal or a piece of wood, those would typically be called traffic signs.
If you’re not sure when to use “signal” or “sign” in the first meaning of those words that we discussed, you can usually use “sign,” people will know what you’re talking about. It’s a little more common.
Roger, originally from Brazil but now living in Japan, wants to know the difference between two phrasal verbs: “to figure out” and “to find out.”
“To figure out” means to solve a problem or to answer a question. “Can you help me figure out this math problem?” You’re asking the person to help you get the solution – the answer. “To find out” can also mean to learn the answer to a question, but you could learn it by yourself or someone could tell you. If someone tells you the answer, you found out the answer but you didn’t figure out the answer. Usually “figure out,” even if you’re getting help, is something that you mostly do yourself.
“To find out’ has an additional meaning, which to learn the truth when someone has done something wrong – to discover the truth. “I found out who killed the President of the United States. His name was Lee Harvey Oswald, acting alone in 1963.” I’m sorry, that’s who did it! I found that out by reading a book. You can find things out many different ways. “I found out that my brother is allergic to certain kinds of fish,” meaning he can’t eat certain kinds of fish. I found out by giving him some fish and then watching his face turn red. Not really – turned blue, I think!
So that’s “figure out,” solve a problem, usually by yourself or with someone’s help; and “find out,” to learn the answer to a problem or the solution to a problem, or to learn the truth of something, about someone who did something wrong.
Finally, Gabriel (Gabriel) in Italy wants to know the meaning of an expression: “to beat a dead horse” – or sometimes “to beat a dead cat,” which is my preferred version!
First of all, “to beat” means to hit a person many times or to hit an animal many times in order to hurt it – to injure it. “To beat a dead horse” means to waste time trying to do something that has already been done, or already been attempted or tried. If the horse is dead, you don’t need to hit it, it’s already dead. “To beat a dead horse” is to do something that is useless. “To beat a dead cat” means the same thing; it’s not very common however, although perhaps it should be!
The British English version of this phrase is “flogging a dead horse.” “To flog” (flog) means the same as “to beat,” and you will also hear that word “flog,” usually if it’s in American English in a historical context talking about, for example, when the owners of slaves would flog their slaves. They would take a – what we would call a whip, a long piece of rope or leather, and hit the slave with that. That would be “to flog,” but in American English it’s “to beat a dead horse.”
By the way, you can also use this expression to mean that there’s no chance of what you are doing is going to be successful or is going to have a different result from the result you already have received. “Stop beating a dead horse, you didn’t get the girl.” You didn’t get the girl to say yes when you wanted her to go out on a date. That’s good advice for everyone!
If you have a question, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
ornithologist – a scientist who studies birds
* We think we saw a new type of bird that no one has identified before, but only a knowledgeable ornithologist can tell us if we’re right.
to sketch – to draw, especially to create a quick drawing of something to help one remember it later
* Jun makes extra money drawing sketches of tourists at the Eiffel Tower.
naturalist – a person who is interested in the natural world and tries to learn a lot about it, mostly through observation
* Betty is a naturalist, who has lived for 20 years on this island observing rare insects and animals.
to illustrate – to draw; using a drawing or other type of picture in a book or magazine to explain a concept or show what something looks like without using a photograph
* Look at the drawing on this page. It illustrates the major parts of the human body.
bird-banding – the practice of placing a small piece of metal or plastic in the shape of a ring on a bird’s leg so that it can be followed or identified later
* Using bird-banding, the scientists are able to follow these birds for 12 months to track their movement.
taxidermy – the act of filling dead animal bodies with special materials so that they look like live animals, usually to display in a home or museum
* Raul’s hobby is taxidermy and his house is filled with animals he’s hunted and killed.
to become extinct – to have no living examples of an animal, insect, or other living thing, often because they have all been killed or because of harmful human activity
* If these animals become extinct, our children and grandchildren will never have an opportunity to see them.
to court – an old-fashioned term meaning to show a woman that one is interested in her by doing kind and thoughtful things and giving her special attention
* In the movie, the young man courted the young woman for six months before he asked her to marry him.
grief – extreme sadness, usually because someone has died
* When Roxanne’s mother died, she had trouble recovering from the grief.
parody – a funny copy of something, making fun of the original version
* Have you heard the parody of Michael Jackson’s song “Beat It,” called “Eat it”?
spaghetti – long, thin noodles (pasta) normally served with a tomato sauce and meatballs (large, round balls of cooked ground beef)
* I like eating spaghetti with meatballs, but it always makes a mess on my white shirts!
to sneeze – to blow a lot of air out of one’s nose with a loud noise, often because one has a cold or allergies
* Keela is allergic to cats and sneezes every time she goes near one.
sign – an action or object used to communicate an idea; a written symbol that stands for an idea
* With flowers starting to bloom and leaves growing on trees, we’re finally seeing signs of spring.
signal – an action used to communicate an idea; something that causes action or communicates a need for action; communication transmitted using waves (such as radio waves)
* The army captain gave a signal for the soldiers to begin their attack.
to figure out – to solve a problem, answer a question, or come to understanding something
* We can’t figure out how to use the remote control on our new TV.
to find out – learn the answer to a question or the solution to a problem; learn the truth, especially when someone has done something wrong; to discover
* How did you find out that your parents were getting a divorce?
to beat a dead horse – to waste time trying to do something that has already been tried; to talk about or to try to do something again when one has already failed or when there’s no chance of a different outcome
* You’ve asked Jenny for a date three times already and she has said ‘no’. Stop beating a dead horse.
What Insiders Know
The Birds – The Book and the Film
The famous English film director Alfred Hitchcock (1899-1980) often directed films based on “novels” (long stories; a book not based on true events). One of his most famous films, The Birds, was based on a “novelette” (short novel) by the English author Daphne du Maurier.
The Birds is a “horror” (scary; designed to frighten) movie about a “coastal” (near the ocean; bordering on the sea) town in California that is suddenly “subjected to” (made to experience something negative or hurtful) attacks by a large number of birds. The large birds chase and attack humans, and working as a group, cause a lot of damage.
The characters, a handsome lawyer and a beautiful “socialite” (a person well know for his/her social life and being with fashionable people in society) meet and are the “focal point” (the center of interest or activity) of the attacks. They try to hide inside the lawyer’s house, but the birds try to break windows and doors to try to get in.
The Birds is not the only film based on a novel by Daphne du Maurier. Another of Hitchcock’s most “celebrated” (honored) films, Rebecca, was based on du Maurier’s 1938 novel also called Rebecca. The novel Rebecca became very popular after it was published and made du Maurier one of the most popular authors of that time. Hitchcock made the film Rebecca in 1940 and it won the Academy Award, the most “prestigious” (well-respected) film award in the U.S., in that same year.