= 1577
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 272.
This is English as a Second Language Podcast’s English Café episode 272. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to continue our series on famous American songs, focusing on God Bless America and one of its most famous performers or singers, Kate Smith. We’re also going to talk about something called the American Girl products, which are books and dolls that are currently very popular among young girls in the United States. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on famous songs. Today we’re going to talk about the song God Bless America, which is a patriotic song. Something that is “patriotic” (patriotic) is something that shows your love for your country, coming from the Latin word “patria,” meaning country. You can be patriotic by, for example, putting your country’s flag in front of your house, or perhaps volunteering to serve in the military – the armed forces, or by volunteering to help other people in your country to make your country better. You can also be patriotic by celebrating your national day, for many countries the Independence Day if they were once part of another country. You can also sing songs like God Bless America – well, if you’re American. If you’re not then you would sing, of course, a different song about your country.
God Bless America was written by one of the most famous composers in the early 20th century Irving Berlin in the year 1918. Berlin, at the time, was serving in the U.S. Army; this is during the end of World War I. After he wrote it he set it aside because he was working on other things. The phrase “to set (something) aside” (aside) means to decide not to continue working on something right now, to save it for later. Berlin set aside his new song for 20 years, and finally in 1938 he started working on it again; we might say he picked it up again. “To pick (something) up” can mean to take your hand and to lift it up in the air, but it also can mean to start working on something. We often use it with musical instruments: “I want to pick up the piano.” That doesn’t mean you want to lift the piano in the air, which would be a little difficult. Instead, it means you want to learn how to play the piano. Well, in this case, when we say Berlin picked it up again, we mean he started working on it again.
He changed the song from being a song about war to being a song about peace. The song, in fact, is written as a prayer. “Prayer” is the notion that you are talking to God or having a conversation with God. When God “blesses” someone or something, God helps and protects that person or that thing. That’s the idea when we say God blesses something or God bless you. That means we want God – if we believe in God – to protect you, to take care of you. That’s why when someone sneezes (achoo) people often say “God bless you,” meaning we hope God protects you and keeps you healthy. And by the way, don’t get too close. I don’t want to get your cold! So, in God Bless America we are asking God to bless this country – to protect this country.
I’m now going to sing the song, first without music, then we will explain the lyrics, and then I’ll sing it again with music. Of course I have to sing, that’s why I record these podcasts! My real ambition – what I really want to do is be a professional singer some day. Unfortunately, I don’t sing very well. Well, here we go!
God Bless America,
Land that I love.
Stand beside her, and guide her
Through the night with a light from above.
From the mountains, to the prairies,
To the oceans, white with foam
God Bless America,
My home sweet home.
God Bless America,
My home sweet home.
Now let’s look at the “lyrics,” or the words in the song. The singer, as I mentioned, is asking God to bless America, the United States, the land that I love – the country that I love. We’re asking God to stand beside her and guide her. “To stand beside (someone)” means to be loyal to that person, to support him or her in good times as well as in bad times. So we say stand beside her and guide her, or help her along her path. As in many places in English, a country is often referred to using the female pronoun “she,” so we say guide her.
Then the song asks God to bless America from the mountains to the prairies (prairies). A “prairie” is a large, flat area of land covered by grass. And in the United States, you may know, there are two mountain ranges, places where there are a lot of mountains: in the east, the Appalachian Mountains, and in the west, the Rocky Mountains. In between is the agricultural center of the United States, and these are where you will find the prairies. So, we’re asking God to bless America from the mountains to the prairies – the entire country. That doesn’t include California – but, well, maybe God doesn’t want to bless California! I’m not sure. Anyway, we’re also asking God to bless America all the way to the oceans. Okay, so here we go, we’re part of that! We are telling Him – asking Him to bless this country to the oceans white with foam. “Foam” (foam) refers to a lot of white bubbles on the top of some liquid; you could have foam on your milk. You could have foam in the ocean, when the water comes up against the land – the shore, we would call it.
Finally, the song ends with “God Bless America, my home sweet home.” The phrase “home sweet home” is often used to talk about where you live and how much you like it, how comfortable it makes you feel. Sometimes people will have little signs on their door that say “Home Sweet Home,” they’re saying that they like the place where they live. Here, of course, we are using the expression to talk about the country that we live in.
One more time let’s take a listen to the song. This time I am going to be helped by my friends, some musicians. I’ll introduce them after the song.
God Bless America,
Land that I love.
Stand beside her, and guide her
Through the night with a light from above.
From the mountains, to the prairies,
To the oceans, white with foam
God Bless America,
My home sweet home.
Take it away boys!
God Bless America,
Land that I love.
Stand beside her, and guide her
Through the night with a light from above.
From the mountains, to the prairies,
To the oceans, white with foam
God Bless America,
My home sweet home.
I want to thank the band and singers from the United States Marine Corps at Parris Island. That’s Parris (Parris) Island, South Carolina for their wonderful playing, and of course, for their singing as well.
When sung by someone who knows how to sing – that is, someone other than me, this is a very beautiful song. It was made famous, or really it was popularized by one singer by the name of Kate Smith. She is the one who introduced the song back in 1938. She sang it with a full “orchestra,” or a large band with many instruments, and it’s a very powerful what we would call rendition of the song. “Rendition” (rendition) refers to a particular performance of the song. You heard my rendition, you should really hear Kate Smith’s rendition! Kate Smith continued to sing this song at big events throughout her career. If you have a chance to hear the Kate Smith version I think you will like it.
God Bless America is not our national “anthem,” or song that identifies our country. Our national anthem is The Star-Spangled Banner, which we talked about way back in English Café 153; you can take a listen to that. Some people, however, think God Bless America should be our national anthem and they have attempted to change it, but I’m guessing they probably will not be successful. We’ll keep The Star-Spangled Banner, I’m sure!
Even though God Bless America isn’t the national anthem, the song is still heard a lot. In particular, you can hear it at a baseball game – a professional baseball game, during something that we call the “seventh-inning stretch.” An “inning” (inning) is a part of baseball game. In soccer, what most of the world calls football, there are two halves to the game. In baseball there are actually nine parts of the game – nine innings. During the seventh inning, in the middle of the seventh inning, the tradition in the United States is for everyone to stand up and to stretch. “To stretch” means literally to take your arms and extend them out so that you are stretching your muscles. The idea is that you have been sitting for a long time so now you need to get a little exercise, if you will. During the seventh-inning stretch now in professional baseball you can hear the song God Bless America.
Now you might ask why it is sung in baseball games? Well, it was never sung when I was growing up. However, after the terrorist attacks on September 11th, 2001 many people wanted a way of remembering those attacks, but also as a way of honoring those who are in the U.S. military. So they added this song, God Bless America, and they have someone come out and sing it. You never will hear a record or a CD – a recording. There will almost always be someone there, a singer singing the song. Members of the U.S. Congress, our legislative body, sang the song on the night of the September 11th attacks, and the song was also recorded by the Canadian artist Celine Dion as a way of making money for the people who were injured or hurt in some way by the attacks, as well as their families.
Not everyone loved the song when it was first released. In fact one singer, a folk singer by the name of Woody Guthrie actually wrote a song in response to God Bless America called This Land is Your Land. We’ll try to talk about that one on another Café.
Our next topic is a line of dolls and books called American Girl. A “line,” or a “product line” is a group of related products. So you may have a company that sells hair supplies, things that you would use with your hair. This is something that’s, of course, very important to me! So they may have brushes and combs; those would be considered a product line, they’re all related. They might even have the same color or the same style.
American Girl is a product line that includes dolls and books. A “doll” (doll) is a toy that is made to look like a human usually. Traditionally, girls play with dolls, although sometimes boys do – probably more of a recent thing. Boys also play with little things that look like humans, but they generally don’t call them dolls; they call them things like action figures. They’re really dolls, but there is a, uh, a difference, and you certainly wouldn’t want to little boy that he was playing with a doll – at least most little boys may not like that.
In any case, the American Girl line was started by a woman named Pleasant Rowland. Rowland was looking to give some dolls to her nieces, but she couldn’t find exactly what she wanted. She saw a lot of baby dolls, which are meant to let girls, for example, pretend to be mothers, and she saw older dolls, which were meant to let girls pretend to be adults and play with clothing and hair. She, however, wanted to find a doll that would be appropriate for a pre-teen girl, or a girl who is almost a teenager, but not quite yet. Usually that’s considered between the ages of 9 and 12. Once a child turns 13 they are then officially a teenager. Of course, the word “teenager” comes from the fact that the ages between 13 and 19 all end with “teen.”
Anyway, the American Girl dolls are based on historical characters. The product actually tries to teach a little history to American girls by getting them interested in characters who lived during specific periods of American history. For example, one of the dolls, named – I think it’s pronounced – Kaya (Kaya), is a Native American from the Nez Perce tribe, living in the year 1764, when the United States was still part of the British Empire. Another doll is called Felicity Merriman; she lives in Williamsburg, Virginia in the year 1774. We talked about Williamsburg, Virginia on English Café 260. You might want to listen to that one. There’s another doll called Kirsten Larson, who is an immigrant from Sweden, in northern Europe, living in 1854.
There are books that go along with the dolls that explain who they are, as well as the historical setting – that is, the situation in American history at the time that these people were actually living. Although the books are meant for children, they do covers some important topics in history such as slavery, racism (where you discriminate against people based on the color of their skin), alcoholism (the problem of people who are addicted to drinking alcohol), war, and “child labor,” or the practice of having very young children working in factories, in places that are often dangerous.
Girls who like the books also buy the dolls for each character, as well as many “accessories,” things such as clothing or little furniture. Today, many dolls and accessories are available for purchase in this line of American Girl products.
There are also – believe it or not – American Girl movies. The first movie was made in 2004 and was called Samantha: An American Girl Holiday. Since then, several other American Girl movies have been made. And if you are between the ages of 9 and 12, or have children of that age you can go and find out what they are. I must admit I’ve never seen any of the movies, but I’m sure that someday I will see one. I’m just kidding, I probably will never see one! But, there they are. There’s even an American Girl magazine and an American Girl website – of course – where girls can learn more about their favorite characters. They can also take “quizzes,” or tests based on the books, and play different games. As I say, I’ve never actually seen an American Girl doll. But if you know any American pre-teen girls I’m sure they can tell you a lot more about it.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Savor (Savor) in China. The question has to do with the difference between the phrases “provided that” and “as long as.” “Provided that” usually means the same, in most cases, as “if.” It can also mean “with the understanding that” or “assuming” some situation. For example: “Provided that Marie does her job, the boss plans to give her a raise (give her more money).” “Provided that” is this same here as “if.” “If Marie does her job well.” Or, another example: “This office will close right away, provided that all of the paperwork (the forms and papers you have to fill out) are completed.” “Provided that” means if this condition is met, if this situation is true.
“As long as” can also mean the exact same thing: “As long as Marie does her job well, the boss plans to give her a raise.” It means same as “provided that.” However, “as long as” has an additional meaning. It can also means for a certain period of time: “As long as you need me, I’ll be there.” I’ll be there to help you as long as you need me, for the period of time, however long it is that you need me. I’m willing to work as long as necessary to complete my job, the things I have to do today. It could be an hour; it could be four hours. That’s as long as.
What’s the difference between the use of “provided that” and “as long as” when they both mean “if” or “with the understanding that”? Basically, “provided that” is a little more formal; it sounds a little more formal. “As long as” perhaps although it’s okay in a formal situation, it’s also common in informal situations.
One more thing, it’s usually possible to drop, or not say the word “that” in the phrase “provided that.” You could say, “Provided Marie does her job well, the boss plans to give her more money.” You don’t even have to say “that.”
Next, Sergey (Sergey) from Ukraine wants to know the meaning of something that he saw on a television show, somebody said, “Hey, it’s my G!”
Well, the letter “g” actually has a lot of different meanings in English; it’s used informally for a couple of different things. The most common modern use, within the last 25-30 or so, is for it to stand for another word that begins with a “g”, which is “gangster,” or as it is pronounced in the slang “gangsta.” A person who is a “gangster” is in a group or a gang of criminals, people who do things that are illegal. However, it has become, through movies and songs, more popular so that sometimes you’ll hear just men particularly, or boys, say, “Hey G, what’s going on?” It doesn’t necessarily mean that person is a gangster. Again, it depends on the group that you are with. I would never use the term, but people who are younger, for example, might use it informally. But originally, it was an abbreviation for the word “gangster.”
An older meaning of the letter “g” is that it is an abbreviation for “a grand,” or 1,000 dollars. You could say, “I spent 20 Gs on my car,” meaning I spent 20,000 dollars on my car.
Finally, “g” can also stand for the word “gram,” which is a metric unit of measurement. This is also an informal use, however because usually when it’s used this way you’re talking about some sort of illegal like marijuana, which is measured in grams. So for example: “The man was caught by the police trying to sell two Gs of marijuana to someone else.” The “g” there stands for “gram.”
Using “g” as an abbreviation for any of these meanings is very informal. Sometimes it’s only used, as I said, by certain groups – young men, teenagers and those in their 20s, sometimes by women, especially in certain urban or city areas.
Finally, Surya (Surya) in India wants to know what it means when someone says, “this movie sucks,” or “this song sucks.” Well, “suck” (suck) is a very informal, slang really, use of the verb. Normally, “to suck” means to pull liquid into your mouth by using your lips and your tongue around something like a straw, where you take liquid from a cup and you put it into your mouth through a long tube. However, the very informal meaning is to be of poor quality, to be very bad, not to be very good. “The movie I saw sucked,” it was terrible. You can also just say, “Oh, this sucks,” meaning this is a terrible situation.
I have to emphasize, however, that these expressions, which are sometimes used by teenagers or young adults, are not to be used in any formal situation. In fact, you probably want to avoid using these expressions too much. Many people still consider them somewhat rude, somewhat vulgar, inappropriate in most circumstances, so it’s best to avoid trying to use this one too much. It would only be used around, say, close friends and family. I say they’re used by teenagers and young adults; they’re also used older adults, but it’s a very informal, and again, somewhat dangerous expression shall we say. You probably are best to avoid it. But of course, you will read it and hear it, and now you know what it means: something that is a very poor quality, something that is very bad.
Something that is very good is when you email us your comments and questions. You can email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
patriotic – saying or doing something that shows one’s love of one’s own country; having strong feelings of support for one’s own country
* Each year on the Fourth of July, the Abrahams family shows its patriotic feelings by displaying an American flag in their front yard.
to set (something) aside – to decide not to have or to work on something right now, instead saving it for later
* Liam will be home late from work. I’ll set aside some food for him in the oven.
prayer – a conversation that one has with God, thanking God for what one has and perhaps asking for what one wants
* Mian hopes that her prayers will be answered and her mother will recover from her illness soon.
to bless – for God to help and protect a person, giving him or her success, health, and other good things in life
* Chiniqua felt blessed to have five happy children and eight healthy grandchildren.
to stand beside – to be loyal to someone and support him or her in good times and in bad times
* Erin’s husband stood beside her through her many years battling cancer.
foam – the group of many white bubbles on top of a liquid, usually on top of a hot drink or on the sea or ocean
* I can’t drink this hot chocolate until the foam disappears or it will tickle my nose.
rendition – a particular performance of a song; a person’s performance or interpretation of a piece of music
* Have you heard Jeff McQuillan’s rendition of “Fly Me to the Moon”?
seventh-inning stretch – a break that occurs in the middle of the seventh inning (part) of a baseball game, when people can get up to move around and get a snack
* Let’s go get sodas and some snacks during the seventh-inning stretch.
line – product line; a group of related products made by a company
* This bicycle company released a line of bicycles with wider seats that are more comfortable.
doll – a toy made to look like a human; a toy made to look like a person
* Samantha takes her doll with her everywhere and sleeps with it at night.
child labor – the practice of having very young children work in factories for very little pay
* The police arrested the factory owner after they found evidence of child labor.
accessory – something that can be added to something else so that it can be more useful or attractive
* I bought a couple of accessories for my new cell phone: a case and an extra battery.
provided that – if; with the understanding that
* Jim can come with us on the trip, provided that he pays for his own expenses.
as long as – if; with the understanding that; for a certain period of time
* You can borrow my guitar for as long as you need, as long as you take good care of it.
“g” – short for “gangster” or the informal “gangsta”, which is a person who is in a group or gang of criminals, or someone who acts like a criminal or does illegal things; someone who speaks and behaves like someone who is in a gang
* On the weekends, Phil tells everybody he’s a “g,” but he’s really an accountant.
to suck – to be inadequate, bad, or displeasing; to be of poor quality
* That movie sucked! I want my money back!
What Insiders Know
Bobblehead Dolls
Many sports “franchises” (organization that includes many teams) want to attract sports fans and to get them to buy tickets to the games. One way to do this is to offer special “promotions” (special objects or services) at specific games. A popular promotion is to give special “collector’s items” (items made in limited numbers that may be valuable to fans and/or that may gain value over time) to people who enter the park or “stadium” (large place with a field in the middle and many seats around it where sports are played). Sometimes, sports fans receive t-shirts or small towels on these special promotion days. Other times, fans are given a “pennant,” which is a narrow flag with the team’s name on it that fans can “wave” (move back and forth) at the game to show their support and enthusiasm.
One of the most popular promotions at games are bobblehead dolls of popular players on the “home team” (the team playing in its own city). This special type of doll or toy is made to look like a specific player. The head of the player is usually “oversized” and is much larger than the body. The head is attached to the body by a “spring,” which is a strong wire that is formed into to “coil,” like a circle with ends that do not meet, and that can pulled or pushed, but returns to its original shape. The spring allows the head to be “tapped” (touched lightly) to cause the head to “bobble” (move slightly back and forth, and up and down at the same time). This is how the doll got its name.
The first modern bobblehead dolls appeared in the 1950s. In 1960, Major League Baseball, the main organization of professional baseball teams in the U.S., produced a bobblehead doll series for some of the championship players that year. These bobbleheads have become collector’s items. Outside of sports, one of the most valuable sets of bobblehead dolls is of the well-known band The Beatles.