= 1590
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 285.
This is English as a Second Language Podcast’s English Café episode 285. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current lessons, or episodes, that will give you some additional help in improving your English. If you want even more help, you can go to our ESL Podcast Store and buy separate courses on a variety of business and daily English topics, and if that isn’t enough, we also have a ESL Podcast Blog on our website.
On this Café, we’re going to continue our series on American presidents, focusing on our third president, Thomas Jefferson. We’re also going to talk about something that was probably more popular in the 70s and 80s but it’s becoming popular again, something called a celebrity roast. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on American presidents, focusing on Thomas Jefferson, who was the third president of these United States.
Thomas Jefferson was born in the then British colony of Virginia, one of the largest of the 13 colonies – maybe even the largest; I’m not sure. In any case, Virginia is located in the eastern part of what is now the United States on the Atlantic coast, sort of in the middle going north to south. Jefferson was born in 1743. He received a good education; he was a very good student, we might say a dedicated student. He was interested in lots of different things – in many topics, but he mainly (he primarily) wanted to study law. Throughout his life, Jefferson remained curious, always wanting to know more about different subjects; he was a real intellectual, we might say nowadays. He also invented many things, including automatic doors as well as a swivel chair. A “swivel (swivel) chair” is a chair that can move around in a circle, like the one I’m sitting on right now.
Jefferson had a very strong interest also in architecture. In 1768, he began to build what we would now call a “mansion” (mansion), a very large, expensive house that became known as Monticello, and you can still go and visit that house of Monticello. Many people visit it; it’s near Charlottesville, Virginia, and it’s a great way to learn about early American history. I went there when I was young boy and it was pretty cool, I’m sure that I thought.
When Thomas was a young man – Thomas Jefferson, many people were upset, were angry, about the way the British were controlling or ruling the colonists – the 13 colonies. Many people living in North America were “colonists,” they were under the British government. The word “colony” here refers to some land that a government owns but it’s not near the country. So the Spanish, the British, the Portuguese, the French, Netherlands – many European countries had colonies in different parts of the world. This was a British colony – the United States was before we achieved our independence. But in the late 1760s-early 1770s we did not have our independence, and men like Jefferson began to argue that the United States should be its own country, separate from England.
Well soon after, in the mid 1770s, the American Revolutionary War began, where the Americans were fighting against the British. It was at this time that Jefferson became a delegate to what was called the Second Continental Congress. A “delegate” (delegate) is like a representative, someone who is chosen from a larger group to represent them at some meeting. In this case, it was a meeting of delegates from all 13 colonies. In that role, as a delegate, it was Thomas Jefferson who drafted, or wrote, our Declaration of Independence, the document that said that America, the colonies, no longer wanted to be part of England and that they were going to become independent. The Declaration of Independence begins “When in the course of human events…” The Declaration itself is a list of the problems, the complaints, that the colonies had.
Eventually, the colonies did achieve, or obtain, or get their independence. Afterwards, Thomas Jefferson became governor, or leader, of the State of Virginia. He was also a member of the new national legislature, the Congress as we call it, and he served as Minister to France; he represented the United States in the country of France. After the Americans reorganized their government by having another convention – another meeting of all the representatives of the new states that were now independent, we elected our first president, George Washington. Thomas Jefferson was the Secretary of State for George Washington. In other countries, he might be called the “Minister of Foreign Affairs,” or “of Foreign Relations”; it’s the person in the government that usually tries to make sure the government is not causing problems with other governments or that other governments are not causing problems with us. These are where you have your ambassadors and diplomats, people who represent your country in other countries. In the U.S., that department is called the State Department, and Thomas Jefferson was the Secretary of State for George Washington. Then he became the vice president, working under President John Adams, our second president, who we’ll talk about some other day.
In 1801, Thomas Jefferson became the third President of the U.S. As president, one of the most important things he did was to arrange and coordinate something called the Louisiana Purchase. The French had claim to a lot of land in the central part of what is now the United States, including part of my state of Minnesota, where I was born – not when I was born, I’m not that old! But back in the early 19th century and the late 18th century, this land belonged to France and France decided to sell it. Remember, France in the early 19th century had a lot of issues – a lot of problems in terms of its government: you had Napoleon and all of the other things that were going on. So, the French decided they would sell this land to the United States – to this new country. It was one of the largest purchases that the United States ever made; in fact, it doubled the size of the United States – it made it twice as big, and it is an area that is about 25 percent of the current United States.
Jefferson wanted to explore this newly purchased land. He also wanted to know whether there was a good way to travel from the eastern part of the U.S. to the western part, and so he arranged – he gave money for an “expedition.” This is a long journey of exploration, and the two men who led, or who were the leaders of that, were named Meriwether Lewis and William Clark. Most Americans know it simply as the Lewis and Clark Expedition. It’s very famous in American history, because they were among the first Americans to go into the territory of the Louisiana Purchase and continue on to the very western edge of the United States – what is now the United States. They provided a lot of information about the people, the Native Americans or American Indians that were living in that area, as well as animal and plant life.
As president, one of Thomas Jefferson’s goals was to eliminate, to get rid of, the Alien and Sedition Acts. An “act,” when we’re talking about the government, is the same as a law. These were four laws that the previous president, the second president, John Adams thought were necessary to protect the United States from aliens living in this country. An “alien” (alien) is sometimes used to talk about some sort of living beings from other planets that come and live on Earth; this is science fiction, not actually have happened – although I think my neighbor might be an alien, it’s possible! Anyway, “aliens” in this situation refer to someone who was born in another country and is still loyal to that country. “Sedition” (sedition) is anything that is said or written that would make people want to fight the government, to “rebel” we might say, to disobey the laws of the government. John Adams thought that the Alien and Sedition Acts would protect the United States, but Thomas Jefferson thought they were too harsh, too strong. In fact, he thought they were unconstitutional. When you say something in the U.S. is “unconstitutional” you mean that it violates or breaks the basic law of the United States, which is our Constitution; that’s the highest law in the U.S. So when he became president, he began to release, or let go, people who were in prison – who had been arrested, or put in prison or jail because of the Alien and Sedition Acts, in particular the Sedition Act. That act, or law, actually ended before Jefferson became president, but Jefferson released people who were arrested, or at least many of them, under that act from the previous president.
As president, Jefferson also helped increase the strength of the U.S. military. He established or created a special school for military officers called West Point, and in fact West Point is still the school where the military leaders of the Army usually attend. He also began the United States’ first war overseas; that is, not next to the United States. That was the First Barbary War, which was fought between 1801 and 1805. This was a war to try to stop a problem, which is still with us 200 years later, where you have pirates, criminals who capture and take over ships and take what’s on the ship, or nowadays they try to get governments to pay them money to get the ship back.
Jefferson was president for two terms – two four-year periods; his presidency ended in 1809. He continued to be involved in politics as well as education in the U.S. He began, or founded the University of Virginia, in his state of Virginia, which gave, among other things, students the option – the opportunity to choose their own electives. At a university, an “elective” (elective) is a class that you are not required to take; it may not even be in your main area of study, but you are allowed to study it anyway. Taking electives in college was very unusual at this time. Jefferson also planned the architecture of the university, which was also quite different than other buildings in the United States.
Jefferson died on July 4th, 1826. Now you may know July 4th is an important date; that was the date of the Declaration of Independence, written by Thomas Jefferson. He died exactly 50 years after the Declaration of Independence was adopted, and in fact just a few hours before his political enemy, the second President of the United States, John Adams. Interestingly, Jefferson specified, or said what he wanted, on his epitaph. An “epitaph” (epitaph) are the words that are sometimes written on what we call a “tombstone,” a large piece of rock that is usually put above where someone’s body is buried. His epitaph said:
Here was buried (here was put into the ground after he died) Thomas Jefferson
Author of the Declaration of American Independence
Of the Statute (or law) of Virginia for religious freedom
And father (or founder) of the University of Virginia.
Notice that this epitaph doesn’t mention the fact that he was President of the United States or any of his other political work. These were the three things, then, that Jefferson thought were the most important parts of his contribution to the United States: the Declaration of American Independence, the Statute of (or law of) Virginia for religious freedom, and starting the University of Virginia, which is still around today, it is still a university. You can read this epitaph if you visit Jefferson’s home, Monticello.
And now, for something completely different, we’re going to talk about celebrity roasts very briefly. A “celebrity” is someone who’s famous, someone who is very well known, especially when we’re talking about a singer or an actor. A “roast” (roast) usually refers to a kind of food; it’s a large piece of meat – of beef, from a cow that is cooked very slowly, or it could also be from a pig, a pork roast. A celebrity roast is not where we cook the person slowly, at least not literally – not actually. In this context, a “roast” is a party or a celebration of someone – of a celebrity, but they make jokes about that person. So perhaps that’s why it’s called a roast, because they turn on the heat, if you will. They usually tell jokes that are somewhat insulting to the person. It sounds very strange, I know, but it was quite popular back in the 1970s, when I was growing up. They would show these celebrity roasts on TV, and they’ve become popular again more recently. The person who is the honoree, the person who the roast is for, or of, has to have a good sense of humor, meaning he has to be able to laugh at himself, otherwise it wouldn’t be very fun.
Some the earliest roasts – celebrity roasts were done in New York City at a place called the Friars Club; this was back in the 1920s. When these roasts began to be televised, or shown on TV, in the 1960s and 70s, they became, as I mentioned, very popular. Each year, the Friars Club roasts one of its own members. This might seem cruel, but the club members say “We only roast the ones we love.”
I watched many of these as a child in the 1970s. The Dean Martin Show was a comedy show between 1965 and 1974, and that show had many special episodes that were celebrity roasts. Dean Martin was a singer and actor popular at the time.
One of the most popular comics that would appear at these roasts is a man by the name of Don Rickles. Rickles is what we might refer to as an “insult comic,” a comedian who’s funny because he insults, or says mean things about other people. But he says that he only insults people he likes and respects. The Friars Club roasted Don Rickles once, back in 1968. Rickles is still alive at the time of this recording, and still appearing as a comedian.
From 1998 to 2002, the celebrity roasts at the Friars Club were shown on television, on something called the Comedy Central channel, which is a TV cable channel or satellite channel that has comedy shows on it. If you’re interested, you can go on YouTube and find many clips – many short parts of these roasts. The jokes, of course, are going to be in very fast English and may be a little difficult to understand. But, when someone talks about a roast or a celebrity roast, they’re usually referring to the Friars Club and especially to their annual roast of a famous person.
Now let’s answer some of the questions you sent us.
Molly (Molly) in China wants to know the difference in the words “splash,” “spray,” and “sprinkle.” This is a good question, and a little difficult to answer. Let’s start with “splash” (splash). “To splash” means to cause some liquid, like water or coffee or soda, to fly in the air – to go up into the air. If you’re walking down the street and it has rained, there might be what we call “puddles” (puddles); these are little places where water collects. Little children sometimes like to splash in the puddles; they go into the puddle – into the water, and they put their foot down on the ground very hard, and the water goes all over the place. Well, little boys like to do that anyway; I know I did!
“Spray” (spray) is also like “splash,” it can mean to cause some liquid to fly in the air toward something. Usually, “spray” is used when you are trying to get something wet, when the liquid is actually being directed to a certain point or a certain spot. For example, if you are drinking coffee and some of it falls on your shirt, when you wash your shirt you might take some special cleaner and spray it on your shirt, going right for the spots where the coffee was to remove them – to get rid of them. That’s “spray,” and in fact we talk about “spray bottles.” These are containers that have liquid in them that you use for a lot of different things. You can use them for cleaning; you can use them for other purposes. A spray bottle could just have water in it; you might use it if you are very hot.
“Sprinkle” (sprinkle) is usually referring to water that is falling from the sky; it’s a type of rain, in other words, but a very what we might describe as light rain. Just a little bit of water is coming down, that would be a “sprinkle” as a noun. As a verb, “to sprinkle” means to make little drops of water fall on something, or it could be something else that is sprinkled. You can sprinkle sugar on your cereal in the morning to make it sweeter. You could take your hand and you are putting the sugar on your cereal so that it is on all different parts of the cereal. That could also be sprinkling. The idea is that you are distributing small amounts of this substance in various places over a certain area.
So, “splash” is when a lot of water or liquid goes up into the air, usually in all different directions. “Spray” is when you are directing liquid, often with a bottle, that you want to go on a certain spot or in a certain area, and “sprinkle” can mean either the rain, light rain that comes down, or taking water or some other substance and distributing a little bit of it in different places over a specific area.
Daniele (Daniele) in Italy wants to know the meaning of the word “hearing” as a noun. “Hearing” can refer to the ability of a person to hear through your ears. “Hearing,” however, also can mean a formal legal meeting, something like a trial with a judge. A “hearing” can be held – we used the verb “to hold” a hearing – either by a judge or it could be by a government official. “The senator held hearings about a certain problems.” In that case, you have people who come and what we would call “testify,” give their official opinion or present certain facts about a certain topic. The United States Congress, our legislative, or law-making part of the U.S. government, has many different hearings about the different laws that people are proposing. So, that’s what a “hearing” is.
Finally, Frank in China wants to know the meaning of the phrase “to be of.” For example: “This computer is of a new type.” The word “of” (of) can be used in many different ways; I want to talk about that first. “Of” can mean coming from, it can mean “caused by,” it can mean “made of,” and it could also mean “characterized” or “described as.” Usually, “of” is the beginning of a prepositional phrase, a group of words that follows a preposition. “Of” is a preposition, “to” (to) is a preposition, “from” is a preposition, and when you have prepositions you often have words after them that are part of what we call a prepositional phrase. A “phrase” is a part of a sentence.
The prepositional phrases are often used to modify or to describe a noun; they’re used as adjectives. In the sentence “He is the greatest writer of his time,” the prepositional phrase “of his time” is describing – is giving you more information about the noun “writer.” When was he a great writer? He was a great writer, the greatest writer of his time.
“Of” prepositional phrases can also be used to show the cause of something. “His and death was of cancer,” that was the cause of his death. We probably would say, more simply, “He died of cancer.”
“Of” can also indicate what something is made of, the material. “She wore a dress of silk.” The dress was made of silk, that was the material that was used to make the dress.
That’s all we have time for today. If you have a question or comment, you can email us at eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
swivel chair – a chair that can spin around in a circle; a chair that can move in a circle without moving the base
* Jim’s desk is in the middle of the room, so he sits in a swivel chair that allows him to turn and speak to any of the other employees working around him.
mansion – a very large, expensive house; a house with many rooms and is very impressive for others to see
* Fausto just bought a mansion with 12 bedrooms, 10 bathrooms, two swimming pools, and a basketball court!
colonist – a resident of a colony; a person living in an area (colony) owned by another country
* The colonists didn’t want to pay taxes to support a government that didn’t make laws for their benefit.
delegate – a representative; someone chosen to express the views of a larger group of people at a particular meeting or gathering
* At the meeting, the delegates from each state will have a chance to tell us their views on the proposed law.
alien – a person who was born in another country and is still loyal to that country; someone who is not a citizen of this country
* No aliens are allowed to enter this military building.
sedition – anything that is said or written in order to make people disobey or rebel against a government
* The political magazine that Zola works for publishes controversial articles that some say is sedition.
elective – a course that a student can choose to take, not necessarily related to his or her main area of study
* This semester, I plan to take two electives: a course in music and one in art.
epitaph – the words that are written on the large piece of rock (tombstone) placed where one is buried
* On my father’s tombstone is the epitaph: “A loving father and husband, who was loved by all who knew him.”
celebrity – a person who is famous, especially a singer or actor; someone who is very well-known
* Celebrities often have to wear a disguise when they leave their house if they don’t want to be recognized.
roast – a party or celebration where many people make insulting jokes about the person who is being honored
* When Paul retired, his coworkers had a roast for him, and he enjoyed the good-natured jokes told about him.
sense of humor – the ability to appreciate funny or humorous things; the quality of being able to laugh easily at humorous things
* Amy’s boyfriend has no sense of humor! He took everything we said seriously.
insult comic – a comedian who makes jokes by insulting other people; a person whose job is to make others laugh by saying mean things about other people
* We’re so tired of that insult comic making the same jokes about the president on every show.
to splash – to cause some liquid to fly in the air toward something, usually accidentally
* When the car drove by, the rainwater splashed on my new dress and ruined it.
to spray – to cause small drops of liquid to fly in the air toward something, usually to cover an object with water, chemicals, or other liquid
* Jemima sprayed her roses with a chemical to keep the bugs from eating the flowers.
to sprinkle – to let small drops of liquid fall; to let small, solid bits or parts of something fall; to add a small amount of something as if by scattering it randomly
* I’m almost done making these cookies. I just need to sprinkle some sugar on top of them.
hearing – a formal legal meeting, similar to a trial
* The school board held a hearing to determine whether the high school principal had acted appropriately when she closed the school because a few students had brought toy guns to school.
What Insiders Know
Sarah “Sally” Hemings
Sarah Hemings was a mixed race slave owned by President Thomas Jefferson. (She was called “Sally” instead of Sarah by nearly everyone who knew her). While Jefferson was “in office” (serving as President) and for the years following, “journalists” (reporters) claimed that President Jefferson “fathered” (was the father of) seven children with Sally Hemings.
“Rumors” (stories or reports, often without evidence or proof) continued from the 18th century to the present. In 1998, the British scientific journal Nature published the findings of DNA (genetic material) testing showing that the male part of Thomas Jefferson’s “genetic line” (genetic information passed from a male to males in the next generations) matched that of the Hemings family’s, which is believed to be evidence that Thomas Jefferson fathered at least one of Sally Hemings’ children. However, this was not “conclusive” (final; definite) evidence and the question remains in many people’s minds today.
If Thomas Jefferson was indeed the father of at least one of Sally Hemings’ children, there would be an entire “arm” (division; branch) of Thomas Jefferson’s “decendents” (children, grandchildren, great-grandchildren, etc.) that has not been acknowledged or recognized. It would also provide “insight” (a view into; give understanding of) the relationship between Jefferson and Hemings, and between slave owners and slaves.
The relationship between Thomas Jefferson and Sally Hemings was “dramatized” (made into a story) in the 1995 film Jefferson in Paris. Thomas Jefferson was the American “ambassador” (important diplomat; most senior official representative of another government) to France before he became president, and it is believed that he began his relationship with Sally Hemings in Paris at that time.