= 1596
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 291.
This is ESL Podcast’s English Café episode 291. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English that you will enjoy, I think. You can also download the Learning Guide for this episode, and every current episode.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – at a normal speed. We’re going to listen to them and then explain what they’re talking about. Today we’re going to talk about a new U.S. program that sends artists from the United States to other countries of the world. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is a federal government or national U.S. government program, called smART Power. That’s smART with lowercase, or small “sm” and uppercase “ART,” capitalized “ART.” smART is a program that sends artists “overseas,” that is, to other countries of the world, as ambassadors. “Overseas” can in general mean foreign, or we might use the term “abroad,” but technically it would be a country that is separated from your country by an ocean, but it’s used more generally to mean foreign countries – other countries. An “ambassador” is normally someone who represents his or her country in an official, political way. Countries send ambassadors – one ambassador to another country, and that is their representative with the government of the other country. In this program, however, the word “ambassador” is used a little more broadly, a little more loosely to mean someone who is representing the United States, and these ambassadors are artists.
We’re going to listen to some people talk about this new smART program. First we’ll listen to Holly Block, who is the director of The Bronx Museum of the Arts in New York City. Bronx is one of the five sections of New York City – one of the five “boroughs,” we call them. We’ll listen to her first as she explains how the program works. As always, try to understand as much as you can, and then we’ll go back and explain what she said. Let’s listen.
[recording]
They will submit their materials with a concept and we’ll expect them to write a small narrative on what they would like to do. But the idea about this project is it’s really special in the sense that you really need to think about community and think about visiting this place and creating a project that’s in relationship with maybe some topic that’s already going on there, or some of the ideas that you bring to them. We will be working very closely with the artists in selecting partner sites to receive the artists and to help them realize their work.
[end of recording]
Ms. Block begins by explaining that artists will need to submit or present their materials with a concept. “To submit” usually means to give a piece of paper or to give some information that is for an application to do something, or perhaps to get a job. It could be to get something back from the government, some official document. The artists have to submit their materials, their information, with a concept. A “concept” is a general, broad idea. To be good at math – at mathematics for example, you need to understand the concept of addition and subtraction before you can be expected to solve math problems. In a similar way, artists are expected to explain the concept behind the art that they are proposing to do – the project they want to do.
She says that the people making the decisions about who will be the ambassadors expect the artists to write a small narrative on what they would like to do. A “narrative” is a written essay or document, especially one that tells a story; we think about “narrative” as being storytelling, telling a story from the beginning to the end. In the case of applications and what are called “grants,” where you’re asking an organization for money for you work, a narrative is a story but it’s really a description, a complete description of what it is you are planning on doing. The artists need to present their concept and a narrative that gives their work some context, some importance why they want to do what they want to do.
She then explains that the idea behind this project, the reason for this project is very special. She says it’s really special; it’s very unique and different from other projects, in the sense that artists need to think about the community. They need to think about the people who live in the place in the country where they are going. She says they need to think about the place they are visiting and then create a project that is related or connected to something that is happening in that country. She says, “But the idea about this project is really special in the sense that you really need to think about community and think about visiting this place and creating a project that’s in relationship with maybe some topic that’s already going on there, or some of the ideas that you bring to them.” If it’s “going on there” it’s happening there, it’s taking place there.
Finally, she says that her museum working very closely with these artists to select or choose partner sites. A “site” is a place, in this case the country and city where you will be working, perhaps even the museum that you will be working with, if you work with a museum. A “partner” is someone who does a certain activity with you and has a certain relationship with you. Your husband or wife could be your partner; you could have a partner in business, someone who owns half of the company along with you. The idea is that partners work together. So, in this smART program, each artist have a partner site, a place where they are assigned to work.
These partner sites will receive the artists, or welcome the artists, and help them realize their work. “To realize” (realize) often means simply to understand. But in this context, “to realize one’s work” means to create and finish what you are working on, to make something happen. The artists realize their works by finishing their projects and seeing them on display – seeing them being put so that other people can see them – at the partners site.
Let’s listen to the quote one more time.
[recording]
They will submit their materials with a concept and we’ll expect them to write a small narrative on what they would like to do. But the idea about this project is it’s really special in the sense that you really need to think about community and think about visiting this place and creating a project that’s in relationship with maybe some topic that’s already going on there, or some of the ideas that you bring to them. We will be working very closely with the artists in selecting partner sites to receive the artists and to help them realize their work.
[end of recording]
Now we’re going to listen to another artist, a man by the name of Tim Rollins. He serves or is on the Leadership Board, the Board of Directors, for the Bronx Museum. Here he’s going to talk about his experience working in other countries. Let’s listen.
[recording]
In my own personal experiences – working in all these different places – local artists tend to want to meet you. They want to be involved. They want to know what’s going on in the U.S. And so it’s not competitive and it’s not spiteful. It’s a genuine curiosity. And that’s one of the most exciting and rewarding aspects of this sort of collaboration is the fact that you meet so many wonderful new people and they’re like-minded and creative. And it’s all good.
[end of recording]
Mr. Rollins begins by saying, “In my own personal experiences.” He’s trying to emphasize that he’s talking about things that have happened to him, what he has experienced, without trying to say that all artists would have the same experience. He continues, “working in all these different places (meaning when I have worked in many different places around the world), local artists (the artists who live in those places) tend to want to meet you.” The local artists are curious, and they want to meet the visiting American artist. He says, “They want to be involved. They want to know what’s going on (what is happening, what is taking place) in the U.S.” He says the relationship is “not competitive,” meaning that the artists aren’t trying to prove who’s better, who’s the better artist, and he says that the relationship isn’t spiteful, either. “To be spiteful” (spiteful) means to do or say something mean, something bad about someone just to try to hurt that other person, to try to make them upset or angry. Instead of being spiteful, he says, the relationship is one of genuine curiosity. “Genuine” means real; “curiosity” means that you want to know more about something.
He continues, “And that’s one of the most exciting and rewarding aspects of this sort of collaboration. An “aspect” is a feature or a characteristic. “Collaboration” is the act of working together with someone in order to makes something happen. “One of the most exciting and rewarding (something that gives you a lot of benefit or pleasure) aspects of this sort of collaboration,” he says, “is the fact that you meet so many wonderful new people and they are like-minded and creative.” Someone who is “like-minded” thinks similarly and has similar interests, beliefs, perhaps opinions as you do. Our friends are usually like-minded; we tend to spend time with people who share our opinions and our interests. He also says that the artists are “creative,” meaning they’re able to create new things that no one else has thought of before. Our scriptwriter, Dr. Lucy Tse, is very creative with her dialogues. I don’t know where she gets all of the ideas that she does, but she does! Mr. Rollins is talking about artists being like-minded and creative. He ends with a very informal expression, “it’s all good.” This has become popular in the last few years or so. When someone says, “Oh, it’s all good,” they mean everything is fine, everything is okay, there are no problems. You may say that, for example, if someone is worried that have too much work to do, or that perhaps they said something that made you upset, and you say, “Nope, it’s all good.” Everything is fine, there’s no problem.
Let’s listen to this quote one more time.
[recording]
In my own personal experiences – working in all these different places – local artists tend to want to meet you. They want to be involved. They want to know what’s going on in the U.S. And so it’s not competitive and it’s not spiteful. It’s a genuine curiosity. And that’s one of the most exciting and rewarding aspects of this sort of collaboration is the fact that you meet so many wonderful new people and they’re like-minded and creative. And it’s all good.
[end of recording]
Our final quote is also from Mr. Rollins. He’s going to talk about the artists’ role, what they actually do, within the smART project. Let’s listen.
[recording]
Part of the excitement of coming up with projects is to figure out what’s going to work. So it isn’t just that the government is sponsoring your vision as an artist in a selfish way. Really it is about what can we do, what can we come up with, which will engage the community that we’re going to be visiting? And that’s what we are – we’re visitors. And, yeah, play the role of being a visitor as opposed to being a tourist, or as opposed to being a propaganda instrument for the U.S. That won’t work. What will work is a genuine dialogue between the communities to produce something that is of lasting, excellent and cultural value.
[end of recording]
So, he begins by saying, “Part of the excitement of coming up with projects (of creating, of thinking of projects) is to figure out what’s going to work,” to be able to understand what will work and what will not work. He continues, “So it isn’t just the government sponsoring your vision as an artist in a selfish way.” “To sponsor” means to support something, especially by giving that person or that organization money. The government is paying the artists to go to these different countries; they are sponsoring them through this program. But the government isn’t sponsoring the artist’s vision in a selfish way he says. Your “vision” here refers to your dream of what you want to create, what your goal is, the way you see your art. “Vision” can also refer simply your ability to see, anyone’s ability to see with their eyes. But here, it means the dream or the goal, the idea the artist wants to create. If the government were just sponsoring the artist’s vision, he says that would be a little selfish (selfish). “Selfish” means that it would only be about you, not about other people. But, Rollins explains that the government is really sponsoring what the artist and the community can do together. The artist needs to come up with something which will engage the community they’re going to be visiting. “To engage” (engage) means to involve someone or to make someone interested in what you are doing.
The whole purpose of the smART program is to engage the community the artist is visiting. He says, “And that’s what we are – we are visitors. And, yeah, play the role of being a visitor as opposed to being a tourist.” He says that the artists are visiting these communities, they are not just tourists; they’re not just there to take something from the community, they’re there to give something to the community. They’re visiting, but much more like someone who is from the community. He says that the artists are not there to be a propaganda instrument for the United States. He says, “play the role of being a visitor as opposed to being a propaganda instrument for the U.S.” “As opposed to” means instead of being something else. A “propaganda instrument” would be something that a government uses to make people believe things that perhaps aren’t true or are said just to give people a good impression of their country. Rollins says artists are not being sent as propaganda instruments, he says that would not work. “What will work,” he says, “is a genuine (real) dialogue (or conversation) between the communities to produce something (to make something) that is of lasting, excellent and cultural value.” Something that is “lasting” is something that survives for a long time, something that will continue to be in existence for many years. It’s the opposite of temporary; it’s almost like permanent. That’s the idea of lasting.
Now let’s listen to Mr. Rollins one more time.
[recording]
Part of the excitement of coming up with projects is to figure out what’s going to work. So it isn’t just that the government is sponsoring your vision as an artist in a selfish way. Really it is about what can we do, what can we come up with, which will engage the community that we’re going to be visiting? And that’s what we are – we’re visitors. And, yeah, play the role of being a visitor as opposed to being a tourist, or as opposed to being a propaganda instrument for the U.S. That won’t work. What will work is a genuine dialogue between the communities to produce something that is of lasting, excellent and cultural value.
[end of recording]
I don’t know whether this new smART program will really do all of the things it hopes to do, but it will be interesting to watch and see.
Now let’s answer a few of your questions.
Our first question is from Chad (Chad), the person, not the country. Chad is a name of a gentleman living in Taiwan. Chad wants to know the meaning of three similar words: “log,” timber,” and “lumber.”
“Log” (log) is a large piece of a tree; it’s from the main part – the largest part of the tree, what we call the “trunk” (trunk). It could also be from a large part of the tree that goes off from or goes out from the trunk, what would call a “branch” (branch). So, a “log” is something that you might find in a forest, in a place that has lots of trees. A “log” is something that you might put in your fireplace to burn so that you have heat in your house. When I was growing up, I grew up in a house that was built from logs, called a “log cabin.” And, we had to go out and chop or cut these logs every day. Oh, wait minute. No, that…that wasn’t me! That was Abraham Lincoln in the 19th century.
But anyway, “timber” (timber) is simply a piece of wood that you use for building something. It’s the same wood as the log, but we call it something different because we cut it in a way that we can use it for building a house or building something else. In order to actually use timber, you have to cut it, and after you cut it we call it “lumber” (lumber). “Lumber” are boards of a regular size that are used in making buildings, for example, or putting up a wall in a house, we use what is called “lumber.” You buy lumber in a place called a “lumber yard,” that’s a store that sells wood. And the wood comes in what I call “standard measurements.” In other words, they’re ones that everyone uses. For example, you can buy a board that is 2 inches wide and 4 inches tall of varying lengths; a 2 foot, 4 foot, 10 foot piece of lumber that is 2 inches by 4 inches, we call it a 2x4 [2 by 4]. You could also buy a 4x4 or a 2x6. These are ways of describing these regular pieces of cut wood.
So to review, “log” is what we use to talk about a tree that may fall by itself, or a large piece of a tree that someone has cut down. But a log isn’t normally ready to use until it is prepared some way. The only way a log is typically used nowadays is for burning, to keep a house warm or for light at night or whatever. Although in the old days, many years ago, it was common to make houses out of logs – like the one I did not grow up in as a child! “Timber” and “lumber” are both used to talk about logs that have been cut up and made in such a way that you can use them to build something.
Juan Manuel (Juan Manuel) in Argentina wants to know the meaning of a phrase he heard, “to bump into someone.” “To bump (bump) into someone” normally means to meet someone by chance, to meet someone you had not previously set up a meeting with. “I was at the grocery store yesterday and I bumped into my neighbor.” That means I saw my neighbor and talked to him even though I wasn’t planning on it before I went to the grocery store. I didn’t know that he was going to be there. If I had, I wouldn’t have gone!
“To bump into” can also mean to hit or knock against something lightly. If you’re on a crowded subway train it’s hard not to bump into other people, to hit other people lightly as you are walking through the train if it’s crowded.
There’s another expression related to “bump,” very different. It’s “to bump off.” “To bump off” is a phrasal verb that means to kill someone. Usually it’s an expression you would hear among criminals, people who kill other people for criminal reasons. If the Mafia wants to kill someone they may tell one of their men, “I want you to go bump off Jeff McQuillan. He says he doesn’t like cats and we don’t want anyone around who doesn’t like cats.” So, he orders this person to bump me off. Good luck, I’ve got a gun. Okay, I don’t have a gun, but I know how to run really fast!
If you have a question, you can email us. I promise we won’t bump you off for asking! Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
concept – a broad, overarching idea
* Concepts like gravity and magnetism are important in physics.
narrative – a written essay or document, especially one that tells a story
* Have you read Charles’ narrative about his travels in the Pacific Northwest?
partner – somebody one does a certain activity with or has a certain relationship with
* Sasha and his business partner rarely agree on how they should invest their money.
to realize – to understand; to implement or create something; to make something happen
* How long did it take your division to realize the cost savings?
spiteful – related to doing or saying something to try to hurt another person’s feelings
* Knowing that she said all those spiteful things, I never want to be her friend again.
collaboration – the act or process of working together to make something
* Did you do this by yourself, or was it a collaboration?
like-minded – thinking in similar ways, with similar interests, beliefs, and opinions
* After we moved to a bigger city, it took us a few months to find like-minded people and start making friends.
creative – able to create new things that nobody else has thought of before
* Wow, that’s such a creative idea! How did you think of it?
to sponsor – to support something, especially financially by giving money
* Do you think any local companies will want to sponsor the volleyball team?
vision – what one sees; one’s dream of what one would like to create in the future
* Right now, Paul owns only one store, but his vision is to have hundreds of stores across the country.
to engage – to involve someone in something; to make someone become interested in something
* Teachers often experiment with different methods to try to engage their students in new ways.
propaganda – information that is shared by a government to make people believe something that is untrue or only partially true
* I’m so tired of hearing all the political propaganda! When will the elections be over!
lasting – for a long period of time; not temporary; permanent or almost permanent
* I hope this is the beginning of a lasting friendship.
log – a large piece of a tree (the trunk, the largest part) or a large branch (one of the pieces growing out of the trunk) that has fallen or been cut down
* Early pioneers used to build their homes out of logs.
timber – a piece of wood used for building
* Are you going to paint the timbers in the ceiling, or leave them exposed?
lumber – wood that is made into boards of a regular size
* How much did the lumber cost to make that long fence around your house?
to bump into (someone/something) – to meet someone by chance; to meet someone you had not previously set up a meeting with; to hit or knock against something lightly
* After bumping into a car while riding his bicycle, Henrique’s clothes were torn, so he hoped we wouldn’t bump into anyone he knew.
What Insiders Know
Shepard Fairey and the Hope Poster Controversy
In 2008, an artist named Shepard Fairey created a “poster” (a large piece of paper with images and/or words hung on a wall) with an image of “then-presidential candidate” (a person who was running for election as president at that time) Barack Obama. The poster shows a “stylized” (drawn in a way that does not look natural, but is nice) “portrait” (a drawing or photograph or a person) of Obama in red, white, and blue and it has the word “hope” at the bottom.
The poster was very popular and Fairey was able to sell 350 copies of his poster right away. As it began to be used more and more, it became “widely” (by many people) recognized as a symbol of the Obama election “campaign” (efforts to make people vote a particular way).
In 2009, the Associated Press, a very large U.S. news organization, began “demanding” (strongly asking for) “compensation” (payment for a product or service), because it believed the poster was “based on” (modeled after; using something as a source) a photograph taken by Mannie Garcia while he was “freelancing” (working independently) for the Associated Press. “As such” (in that context), the photograph was “copyrighted” (legally protected from being copied without permission).
The photographer, Mannie Garcia, has said that he likes the poster and is glad his photograph was used that way, but that it was wrong for it to be used without permission. Fairey argues that his poster was “fair use” of the photograph, which would be allowed under copyright law. Under “fair use,” people can quote or use something briefly if the user makes it clear where it came from originally.
Fairey and the Associated Press “settled” (reached an agreement) in January 2011, but they kept the details “confidential” (secret), so nobody knows how much was paid.