
= 1.3 The NORTHERN Renaissance
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Okay, it's time to talk about how the Renaissance 文艺复兴 spread from Italy -- the place of its birth -- to the rest of the European continent 欧洲大陆. So if you're ready to get them brain cows milked, well then, let's get to it.  +

So in the last video, we talked about the main themes 主题 of the Renaissance, which included humanistic thinking 人文主义思想 and an emphasis on 强调 the revival 复兴 of classical literature 古典文学 from ancient Greece and Rome. Now, with the help of the printing press 印刷机 -- on which more in the next video -- these ideas began to spread north of the Italian Alps 阿尔卑斯山 into the European continent.  +

In fact, by 1500, there was something like a thousand printers scattered throughout 分散在 Europe, and they were pumping out 大量生产 printed material 印刷品 by the metric butt load 大量地, which is to say about 40,000 different titles 书目, many of which were religious 宗教的 and many of which were reproductions 复制品 of classical literature.  +

Now, as the Renaissance spread to various parts of Europe -- what's known as the Northern Renaissance 北方文艺复兴 -- the main ideas remained intact 保持不变, but the emphases 侧重点 began to change. Recall 回想 that in Italy, some Renaissance thinkers championed 拥护 individualism 个人主义 and secularism 世俗主义, but thinkers in the Northern Renaissance retained 保留 a more religious -- which is to say, Christian -- framework 框架 for thought.  +

For example, the Northern Renaissance art was still naturalistic 自然主义的, but a key distinguishing feature 关键区别特征 of it is that it was more human-centered 以人为中心. And what I mean by that is that it considered ordinary objects and people as appropriate subjects 合适的主题 for art.  +

For example, Pieter Bruegel the Elder 老彼得·勃鲁盖尔 of the Dutch and Flemish Renaissance 荷兰和佛兰德斯文艺复兴 painted this scene 场景, which you would never see in the Italian Renaissance. It's called *Netherlandish Proverbs*《尼德兰箴言》, and it depicts 描绘 peasants 农民 and animals who are the subject of, you know, Netherlandish proverbs 尼德兰谚语.  +

And the thing to notice here is that Bruegel depicts not merely ordinary subjects but those on the bottom of the social ladder 社会底层 -- namely 即, peasants. And you can see the naturalism is still there. These people look real, and their setting 场景 feels like one you could walk around in.  +

Or consider one of the greatest artists of the Dutch Renaissance, Rembrandt 伦勃朗. Here's his painting called *Slaughtered Ox*《宰杀的牛》, and you know, there's no symbolism 象征意义 here. I mean, it's a painting of a slaughtered ox. This is in no way an elitist theme 精英主义主题 that you'd see in the Italian Renaissance but rather a scene from ordinary life 日常生活场景.  +

Now, that's not to say that Northern Renaissance painters didn't take up 选取 religious themes as well. They absolutely did. One of Rembrandt's most famous paintings is his depiction of *The Return of the Prodigal Son*《浪子回头》, which is a parable 寓言 spoken by Jesus in the New Testament 新约圣经.  +

Bruegel's painting *The Procession to Calvary*《前往各各他的行列》 depicts Christ carrying his cross to the place of his execution 处决. So the point is, yeah, the Northern Renaissance artist also depicted biblical scenes 圣经场景 like the Italian Renaissance artist, but there was much more emphasis on the ordinary people in their depictions 描绘.  +

Now, as humanism 人文主义 spread north from Italy, it also changed emphasis. In the Northern Renaissance, there was still a preoccupation with 关注 Greek and Roman classics 古希腊罗马经典, but once humanism reached the Low Countries 低地国家, France, Germany, and England, people took pains to 努力 synthesize 融合 humanistic thought 人文主义思想 with Christian tradition 基督教传统 as well.  +

This meant that in addition to 除了 seeking out 寻找 Greek and Roman classics, Northern Renaissance thinkers also sought out early Christian writings 早期基督教著作 as well, especially from folks like Saint Augustine 圣奥古斯丁 and Jerome 哲罗姆. And what they discovered in those ancient writings was a Christianity that seemed far simpler and more pure 纯粹的 than the complex church hierarchy 教会等级制度 of their own day.  +

And so they sought to return to that simplicity. And if you want to put a term on this -- and I know that you do -- the blending of 融合 Christianity and humanism became known as Christian humanism 基督教人文主义, which, you know, it's a good name.  +

Now, astute 敏锐的 students will immediately grow a question mark over their head. Doesn't humanism teach that human beings had unlimited potential 无限潜力, and isn't that not what Christianity teaches? Well done, my dear people, you are correct.  +

So the way Christian humanism worked out was to teach that human beings were actually far more capable 有能力的 than previously believed, and if we could just get a healthy dose of 适量的 religious enthusiasm 宗教热情 into them, then that would lead to efforts to reform society 改革社会 from a Christian posture 立场.  +

So that's the key thing to remember: Christian humanism led to an impulse for reform 改革冲动 in the Northern Renaissance. Now, there is a Christian humanist you have to know by name, so let me introduce you to my boy Erasmus 伊拉斯谟.  +

His book *In Praise of Folly*《愚人颂》 was a satire 讽刺作品 which sought to undermine 削弱 political and social institutions 政治和社会制度 and which criticized the corrupt aspects 腐败方面 of religious hierarchy. That shouldn't surprise you, since Christian humanists were trying to recover 恢复 an ancient or simpler version of Christianity.  +

Additionally 此外, Erasmus believed that education in the classics and the Bible was the first step in lasting societal reform 持久的社会改革 and that such renewals 革新 should be based not on secular principles 世俗原则 but on what he called the "philosophy of Christ" 基督哲学, which emphasized individual morality 个人道德 and spirituality 精神性.  +

Okay, the next place you need to go is right here to my AP Euro Unit 1 playlist 播放列表, where I cover all the topics of this unit. All right, click right here to grab my AP Euro Review Pack 美国大学预修课程欧洲历史复习资料包, which has everything you need to get an A in your class and a five on your exam in May.  +

I'll catch you on the flip-flop. Heimler out.  +

'''

== 中文释义

好的，是时候谈谈文艺复兴是如何从它的诞生地意大利, 传播到欧洲大陆其他地区的了。所以，如果你准备好让自己的大脑运转起来，那么，我们开始吧。 +

在上一个视频中，我们谈到了**文艺复兴**的主要主题，包括人文主义思想, 以及对古希腊和古罗马经典文学复兴的强调。现在，*在印刷术的帮助下*——关于印刷术我们会在下一个视频中详细介绍——*这些思想开始从意大利阿尔卑斯山, 向北传播到欧洲大陆。* +

事实上，到1500年，大约有一千名印刷工分散在欧洲各地，他们大量地印刷各种材料，也就是说大约有4万种不同的书籍，其中许多是宗教书籍，还有许多是古典文学的复制品。 +

现在，**当文艺复兴传播到欧洲各地——也就是所谓的"北方文艺复兴"——其文艺复兴中的主要思想依然存在，但重点开始发生变化。**回想一下，*#在意大利，一些文艺复兴时期的思想家, 倡导个人主义和世俗主义，但"北方文艺复兴"时期的思想家, 保留了一个更具宗教性——也就是说，基督教的——思想框架。#* +

例如，**#"北方文艺复兴"时期的艺术,# 仍然具有"自然主义"风格，但它的一个关键区别特征是: #更加"以人为本"。#**我的意思是，*它将普通的物体和人, 视为合适的艺术题材。* +

比如，荷兰和佛兰德斯"文艺复兴"时期的老彼得·勃鲁盖尔（Pieter Bruegel the Elder）, 绘制了这样一幅画，这是在"意大利文艺复兴时期"永远看不到的场景。这幅画叫《尼德兰箴言》（Netherlandish Proverbs），**它描绘了农民和动物，**而这些都是尼德兰箴言的主题。 +

**这里需要注意的是，勃鲁盖尔描绘的, 不仅仅是普通的题材，而是社会底层的人物——也就是农民。而且你可以看到自然主义风格依然存在。**这些人看起来很真实，他们所处的场景让人感觉可以走进去。 +

或者想想荷兰文艺复兴时期, 最伟大的艺术家之一伦勃朗（Rembrandt）。这是他的画作《宰杀的公牛》（Slaughtered Ox），你知道，*这幅画没有什么象征意义。我的意思是，这只是一幅宰杀公牛的画。这绝不是在"意大利文艺复兴时期"能看到的那种"精英主义"主题，而是普通生活中的一个场景。* +

**当然，这并不是说"北方文艺复兴时期"的画家, 不描绘宗教主题。他们当然会描绘。**伦勃朗最著名的画作之一是他对《浪子回头》（The Return of the Prodigal Son）的描绘，这是新约中耶稣讲的一个寓言故事。 +

勃鲁盖尔的画作《前往髑髅地的行列》（The Procession to Calvary）, 描绘了基督背着十字架走向被处决之地的场景。所以重点是，*是的，#北方文艺复兴时期的艺术家也像意大利文艺复兴时期的艺术家一样描绘圣经场景，但在他们的描绘中更加注重普通人。#* +

*现在，当人文主义从意大利向北传播时，它的重点也发生了变化。在"北方文艺复兴"时期，人们仍然关注希腊和罗马经典著作，#但一旦"人文主义"传播到低地国家、法国、德国和英国，人们就努力将人文主义思想, 与基督教传统结合起来。#* +

**这意味着，除了寻找希腊和罗马经典著作外，"北方文艺复兴"时期的思想家, 也寻找早期基督教的著作，**尤其是像圣奥古斯丁（Saint Augustine）和哲罗姆（Jerome）等人的著作。*他们在这些古代著作中发现的基督教，比他们那个时代复杂的教会等级制度, 要简单纯粹得多。* +

**所以他们试图回归那种简单。**如果你想给**这种现象**起个名字——我知道你想——*基督教人文主义*（Christian humanism），这个名字很合适。 +

现在，聪明的学生马上会在脑海中产生一个疑问。**#人文主义不是教导人们"人类有无限的潜力"吗，而这不是与基督教的教义不同吗？#**干得好，亲爱的朋友们，你们说得对。 +

*#所以"基督教人文主义"的观点是，人类实际上比以前认为的更有能力，如果我们能让人们充满宗教热情，那么这将促使人们以基督教的姿态, 去改革社会。#* +

**#所以关键要记住："基督教人文主义"在北方文艺复兴时期, 引发了"改革"的冲动。#**现在，有一位基督教人文主义者你必须知道他的名字，让我给你介绍一下我的朋友伊拉斯谟（Erasmus）。 +

他的书《愚人颂》（In Praise of Folly）是一部讽刺作品，旨在削弱政治和社会制度，并批评"宗教等级制度"的腐败方面。这并不奇怪，因为**"基督教人文主义者"试图恢复古代更简单版本的基督教。** +

此外，*伊拉斯谟认为，对经典著作和《圣经》的教育, 是实现"持久社会改革"的第一步，而且这种复兴, 不应该基于世俗原则，而应该基于他所说的 “基督的哲学”，这种哲学强调个人道德和精神性。* +

好的，接下来你需要点击这里, 进入我的AP欧洲历史第一单元的播放列表，在那里我涵盖了这个单元的所有主题。好了，点击这里获取我的AP欧洲历史复习资料包，它包含了你在课堂上取得A的成绩以及在五月份的考试中获得5分所需的一切内容。 +

回头见。海姆勒（Heimler）下线。 +

'''

== pure


Okay, it's time to talk about how the Renaissance spread from Italy -- the place of its birth -- to the rest of the European continent. So if you're ready to get them brain cows milked, well then, let's get to it.

So in the last video, we talked about the main themes of the Renaissance, which included humanistic thinking and an emphasis on the revival of classical literature from ancient Greece and Rome. Now, with the help of the printing press -- on which more in the next video -- these ideas began to spread north of the Italian Alps into the European continent.

In fact, by 1500, there was something like a thousand printers scattered throughout Europe, and they were pumping out printed material by the metric butt load, which is to say about 40,000 different titles, many of which were religious and many of which were reproductions of classical literature.

Now, as the Renaissance spread to various parts of Europe -- what's known as the Northern Renaissance -- the main ideas remained intact, but the emphases began to change. Recall that in Italy, some Renaissance thinkers championed individualism and secularism, but thinkers in the Northern Renaissance retained a more religious -- which is to say, Christian -- framework for thought.

For example, the Northern Renaissance art was still naturalistic, but a key distinguishing feature of it is that it was more human-centered. And what I mean by that is that it considered ordinary objects and people as appropriate subjects for art.

For example, Pieter Bruegel the Elder of the Dutch and Flemish Renaissance painted this scene, which you would never see in the Italian Renaissance. It's called *Netherlandish Proverbs*, and it depicts peasants and animals who are the subject of, you know, Netherlandish proverbs.

And the thing to notice here is that Bruegel depicts not merely ordinary subjects but those on the bottom of the social ladder -- namely, peasants. And you can see the naturalism is still there. These people look real, and their setting feels like one you could walk around in.

Or consider one of the greatest artists of the Dutch Renaissance, Rembrandt. Here's his painting called *Slaughtered Ox*, and you know, there's no symbolism here. I mean, it's a painting of a slaughtered ox. This is in no way an elitist theme that you'd see in the Italian Renaissance but rather a scene from ordinary life.

Now, that's not to say that Northern Renaissance painters didn't take up religious themes as well. They absolutely did. One of Rembrandt's most famous paintings is his depiction of *The Return of the Prodigal Son*, which is a parable spoken by Jesus in the New Testament.

Bruegel's painting *The Procession to Calvary* depicts Christ carrying his cross to the place of his execution. So the point is, yeah, the Northern Renaissance artist also depicted biblical scenes like the Italian Renaissance artist, but there was much more emphasis on the ordinary people in their depictions.

Now, as humanism spread north from Italy, it also changed emphasis. In the Northern Renaissance, there was still a preoccupation with Greek and Roman classics, but once humanism reached the Low Countries, France, Germany, and England, people took pains to synthesize humanistic thought with Christian tradition as well.

This meant that in addition to seeking out Greek and Roman classics, Northern Renaissance thinkers also sought out early Christian writings as well, especially from folks like Saint Augustine and Jerome. And what they discovered in those ancient writings was a Christianity that seemed far simpler and more pure than the complex church hierarchy of their own day.

And so they sought to return to that simplicity. And if you want to put a term on this -- and I know that you do -- the blending of Christianity and humanism became known as Christian humanism, which, you know, it's a good name.

Now, astute students will immediately grow a question mark over their head. Doesn't humanism teach that human beings had unlimited potential, and isn't that not what Christianity teaches? Well done, my dear people, you are correct.

So the way Christian humanism worked out was to teach that human beings were actually far more capable than previously believed, and if we could just get a healthy dose of religious enthusiasm into them, then that would lead to efforts to reform society from a Christian posture.

So that's the key thing to remember: Christian humanism led to an impulse for reform in the Northern Renaissance. Now, there is a Christian humanist you have to know by name, so let me introduce you to my boy Erasmus.

His book *In Praise of Folly* was a satire which sought to undermine political and social institutions and which criticized the corrupt aspects of religious hierarchy. That shouldn't surprise you, since Christian humanists were trying to recover an ancient or simpler version of Christianity.

Additionally, Erasmus believed that education in the classics and the Bible was the first step in lasting societal reform and that such renewals should be based not on secular principles but on what he called the "philosophy of Christ," which emphasized individual morality and spirituality.

Okay, the next place you need to go is right here to my AP Euro Unit 1 playlist, where I cover all the topics of this unit. All right, click right here to grab my AP Euro Review Pack, which has everything you need to get an A in your class and a five on your exam in May.

I'll catch you on the flip-flop. Heimler out.

'''