
= 1.9 - The African Slave Trade
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

A hemorrhoid  痔；痔疮 is a swollen vein  肿胀的静脉, usually around the area of your butt  屁股, that is extremely painful  极其疼痛的. Now you clicked on an AP European history video, and now you're wondering why am I bringing up hemorrhoids? Well, it's because in this video we're going to talk about the African slave trade  非洲奴隶贸易 that rose up  兴起 in response to  作为对……的回应 European empire building  欧洲帝国建设 in the 16th and 17th centuries. And if empire building is the badonkus  （此处为形象化表述，可理解为“重要部分”） of European history, then the slave trade is the hemorrhoids squarely  正好地；正当地 in the crack  缝隙. Am I taking this too far? I don't think you've taken it far enough. Hello. Okay, if you're ready to get them brain cows milked, let's get to it. +

Now in order to understand the African slave trade, we need to talk first about the causes and second about its effects. Now the main cause for the rise and acceleration  加速 of the African slave trade was the establishment of a plantation economy  种植园经济 in the colonies of the New World  新大陆殖民地. +

Now remember, European states are going out and exploring during this period in no small part  很大程度上 because of their economic system known as mercantilism  重商主义. This system majored on  专注于 getting as much mineral wealth  矿物财富 -- which is to say gold and silver  金银 -- into the national coffers  国库；国家金库 as possible. And so when Spain, for example, extended  扩大；扩展 their empire into the Americas, their first goal was to find as much gold and silver as possible, and they ended up fighting quite a lot. +

But eventually it became clear -- because of the climate, especially in this region right here -- that growing crops on plantations  种植园 for export  出口 would be the more profitable  有利可图的；赚钱的 way to go. So the plantation economy was born in these warm areas that virtually  几乎；实际上 had year-round growing season  全年生长季. And the plantation economy was ordered around  围绕……安排 cash crops  经济作物, which means that a plantation would focus on growing only one or two crops, and that the purpose of those crops was to be exported for profit. And sugarcane  甘蔗 and coffee  咖啡 were among the major crops -- you know, just in case you're interested. +

And as it turned out  结果是, these crops fetched  售得；卖得 an extraordinary amount of boom boom  （此处可理解为“大量金钱”） for their parent economy  母国经济. Now you may think that Spain, for example, sent Spaniards across the ocean to do this back-breaking  累人的；繁重艰苦的 agricultural work  农业工作, and if so you would be wrong. No, their first solution was to force the indigenous populations  土著居民 to do the farming for them. +

But as it turned out, that created a problem. Not only did the natives of the land know the geography  地理环境 way better than the colonizers  殖民者 did -- which meant that they were able to escape in respectable numbers  大量逃脱 -- they also kept dying because of European diseases. And so European imperial states  欧洲帝国 had a problem on their hands. We've got this massive plantation economy that is making us filthy dirty nasty rich  非常富有, but our enslaved labor force  被奴役的劳动力 is really letting us down  让我们失望. So maybe we should cease  停止 perpetuating  使持续；使长存 this great injustice  不公正 and just focus on our own people at home and make an honest living there. Wouldn't that be hilarious  滑稽的；可笑的 if that's what they did? +

No. In order to solve the problem of their dwindling  减少的；逐渐变小的 indigenous labor force, they turned to  求助于；转向 Africa and the abundance  丰富；充裕 of enslaved people that they could buy there. And so that became the solution. Now as imperial European states got richer and richer, the demand for enslaved people from Africa began to spike  急剧上升. +

And the enslaved Africans solved both of their problems. First, because Africans had been in contact with Europeans for millennia  千年, they had already had a decent amount of immunity  免疫力 to European diseases. Second, the Africans who were shipped to the New World didn't know the land as well and thus were less likely to escape the plantation  种植园. +

Now admittedly  诚然；不可否认地, I've been talking about this purely  纯粹地 in terms of  就……而言 economic problems and solutions, but the truth is African slavery in the New World was a brutal  残酷的；野蛮的 system of coerced labor  强迫劳动制度. After being captured  捕获 and taken from their homes, the enslaved Africans were sold to Europeans who began showing up on the west coast of Africa more and more frequently. And then they were made to endure  忍受 the brutal Middle Passage  中间航程（指从非洲到美洲的奴隶运输航程） across the Atlantic  大西洋. +

Depending on the weather, it could take between two and six weeks to cross, and the conditions were inhuman  不人道的；无人性的. Now if you're able to get inside the mind of the captain of one of these slave ships -- which I admit is a frightening prospect  前景；可能性, but you know if you do -- then you're going to see that to him, the more goods  货物（此处指奴隶） (which is to say people) that he could fit in the cargo hold  货舱, the more money he stood to make  有可能赚得 on the other side of the Atlantic. So the economic incentive  经济激励 to pack these ships full of enslaved Africans was profound  深刻的；深远的. +

In some cases, we have accounts  描述；叙述 of these ships being so full that each person below had to lay on their side  侧躺 because there wasn't enough room to lay flat on their back  平躺着. In addition, with so many other people close together, diseases ran rampant  猖獗；肆虐 and killed many of them along the way  一路上. Africans were malnourished  营养不良的, treated shamefully  受到恶劣对待, and if they made it alive to the New World, a life of brutal plantation slavery  残酷的种植园奴隶制 awaited them. +

But over the course of the next two centuries, the plantation economy would become more and more profitable, and the demand for enslaved people from Africa would only continue to spike along with... +

Okay, now the next place you should go is right here to watch the rest of my Unit One videos. Click right here to grab my AP Euro review pack, which has everything you need to get an A in your class and a five on your exam in May. I appreciate you coming around, and I'll catch you on the flip-flop. I'm out. +

'''

== 中文释义

痔疮是一种肿胀的血管，通常出现在臀部周围，会极其疼痛。现在你点击了一个美国大学预修课程欧洲历史的视频，然后你在想我为什么要提起痔疮呢？嗯，这是因为在这个视频中，我们要谈论的是16和17世纪为了响应欧洲帝国的建立, 而兴起的非洲奴隶贸易。如果说帝国的建立是欧洲历史的关键部分，那么奴隶贸易就是欧洲历史裂缝中明显的“痔疮”。我是不是说得太过分了？我觉得还不够呢。你好。好了，如果你准备好获取知识，那我们开始吧。  +

现在，为了理解非洲奴隶贸易，我们首先需要谈谈其原因，其次再谈谈其影响。现在，非洲奴隶贸易兴起和加速的主要原因, 是新世界殖民地"种植园经济"（plantation economy）的建立。  +

记住，**#欧洲各国在这个时期外出探索，很大程度上是因为他们的经济体系，也就是"重商主义"（mercantilism）。这个体系主要是尽可能多地将矿物财富，也就是黄金和白银，纳入国家金库。#**所以，例如西班牙将他们的帝国扩展到美洲时，他们的首要目标是尽可能多地找到黄金和白银，并且他们最终进行了大量的争夺。  +

**##但最终很明显，由于气候原因，尤其是在这个地区，在种植园种植作物用于出口, 会是更有利可图的方式。所以种植园经济诞生于这些几乎全年都适合种植的温暖地区。种植园经济围绕着"经济作物"（cash crops）展开，这意味着一个种植园会专注于种植一两种作物，并且这些作物的目的, 是出口以获取利润。##甘蔗（sugarcane）和咖啡（coffee）是主要作物之一，**顺便提一下，以防你感兴趣。  +

事实证明，**这些作物, 为其宗主国经济带来了巨额财富。**现在你可能认为，例如西班牙会派遣西班牙人跨越大洋去做这种繁重的农业工作，但如果你这么想就错了。不，*他们的第一个(人力上的)解决方案, 是强迫原住民为他们耕种。*  +

但事实证明，**这带来了一个问题。原住民不仅比殖民者更了解当地的地理情况，这意味着他们能够大量逃脱，而且他们还因为欧洲的疾病不断死亡。**所以欧洲的帝国国家遇到了一个问题。我们拥有这种庞大的种植园经济，它让我们变得非常富有，但我们的奴隶劳动力却让我们大失所望。那么也许我们应该停止这种极大的不公，专注于本国的人民，在国内诚实地谋生。如果他们真的这么做了，是不是很可笑呢？  +

不。**为了解决原住民劳动力不断减少的问题，他们转向了非洲，那里有大量可以购买的奴隶。**所以这就成了解决办法。现在**随着欧洲帝国国家越来越富有，对来自非洲的奴隶的需求开始急剧上升。**  +

而被奴役的非洲人, 解决了他们的两个问题。首先，因为非洲人与欧洲人接触了几千年，他们对欧洲的疾病已经有了一定的免疫力。其次，*被运往新世界的非洲人对当地土地不太了解，因此不太可能逃离种植园。*  +

诚然，我一直纯粹从经济问题和解决方案的角度, 来谈论这个问题，但事实是，新世界的非洲奴隶制, 是一种残酷的强迫劳动（coerced labor）制度。被奴役的非洲人被俘虏, 并从他们的家乡带走后，被卖给了越来越频繁出现在非洲西海岸的欧洲人。然后他们不得不忍受穿越大西洋的残酷的“中间航程”（Middle Passage）。  +

根据天气情况，穿越大西洋可能需要两到六周的时间，而且条件非常不人道。现在，如果你能设身处地为这些奴隶船的船长着想——我承认这是一个可怕的设想，但如果你这么做了——那么你会发现，对他来说，他**在货舱里装的货物（也就是人, 奴隶）越多，他在大西洋彼岸能赚到的钱就越多。**所以把这些船装满被奴役的非洲人的经济动机是非常强烈的。  +

在某些情况下，我们了解到**这些船非常拥挤，下面的每个人都只能侧着身子躺着，因为没有足够的空间让他们平躺着。**此外，这么多人挤在一起，疾病肆虐，沿途夺走了许多人的生命。非洲人营养不良，受到恶劣对待，如果他们活着到达新世界，等待他们的是残酷的种植园奴隶制生活。  +

但是在接下来的两个世纪里，种植园经济变得越来越有利可图，对来自非洲的奴隶的需求也只会随着……  +

好的，现在你接下来应该点击这里观看我第一单元的其他视频。点击这里获取我的美国大学预修课程欧洲历史复习资料包，它包含了你在课堂上取得A以及在五月份的考试中获得5分所需要的一切。感谢你的观看，回头见。我下线了。  +

'''

== pure

A hemorrhoid is a swollen vein, usually around the area of your butt, that is extremely painful. Now you clicked on an AP European history video, and now you're wondering why am I bringing up hemorrhoids? Well, it's because in this video we're going to talk about the African slave trade that rose up in response to European empire building in the 16th and 17th centuries. And if empire building is the badonkus of European history, then the slave trade is the hemorrhoids squarely in the crack. Am I taking this too far? I don't think you've taken it far enough. Hello. Okay, if you're ready to get them brain cows milked, let's get to it.

Now in order to understand the African slave trade, we need to talk first about the causes and second about its effects. Now the main cause for the rise and acceleration of the African slave trade was the establishment of a plantation economy in the colonies of the New World.

Now remember, European states are going out and exploring during this period in no small part because of their economic system known as mercantilism. This system majored on getting as much mineral wealth -- which is to say gold and silver -- into the national coffers as possible. And so when Spain, for example, extended their empire into the Americas, their first goal was to find as much gold and silver as possible, and they ended up fighting quite a lot.

But eventually it became clear -- because of the climate, especially in this region right here -- that growing crops on plantations for export would be the more profitable way to go. So the plantation economy was born in these warm areas that virtually had year-round growing season. And the plantation economy was ordered around cash crops, which means that a plantation would focus on growing only one or two crops, and that the purpose of those crops was to be exported for profit. And sugarcane and coffee were among the major crops -- you know, just in case you're interested.

And as it turned out, these crops fetched an extraordinary amount of boom boom for their parent economy. Now you may think that Spain, for example, sent Spaniards across the ocean to do this back-breaking agricultural work, and if so you would be wrong. No, their first solution was to force the indigenous populations to do the farming for them.

But as it turned out, that created a problem. Not only did the natives of the land know the geography way better than the colonizers did -- which meant that they were able to escape in respectable numbers -- they also kept dying because of European diseases. And so European imperial states had a problem on their hands. We've got this massive plantation economy that is making us filthy dirty nasty rich, but our enslaved labor force is really letting us down. So maybe we should cease perpetuating this great injustice and just focus on our own people at home and make an honest living there. Wouldn't that be hilarious if that's what they did?

No. In order to solve the problem of their dwindling indigenous labor force, they turned to Africa and the abundance of enslaved people that they could buy there. And so that became the solution. Now as imperial European states got richer and richer, the demand for enslaved people from Africa began to spike.

And the enslaved Africans solved both of their problems. First, because Africans had been in contact with Europeans for millennia, they had already had a decent amount of immunity to European diseases. Second, the Africans who were shipped to the New World didn't know the land as well and thus were less likely to escape the plantation.

Now admittedly, I've been talking about this purely in terms of economic problems and solutions, but the truth is African slavery in the New World was a brutal system of coerced labor. After being captured and taken from their homes, the enslaved Africans were sold to Europeans who began showing up on the west coast of Africa more and more frequently. And then they were made to endure the brutal Middle Passage across the Atlantic.

Depending on the weather, it could take between two and six weeks to cross, and the conditions were inhuman. Now if you're able to get inside the mind of the captain of one of these slave ships -- which I admit is a frightening prospect, but you know if you do -- then you're going to see that to him, the more goods (which is to say people) that he could fit in the cargo hold, the more money he stood to make on the other side of the Atlantic. So the economic incentive to pack these ships full of enslaved Africans was profound.

In some cases, we have accounts of these ships being so full that each person below had to lay on their side because there wasn't enough room to lay flat on their back. In addition, with so many other people close together, diseases ran rampant and killed many of them along the way. Africans were malnourished, treated shamefully, and if they made it alive to the New World, a life of brutal plantation slavery awaited them.

But over the course of the next two centuries, the plantation economy would become more and more profitable, and the demand for enslaved people from Africa would only continue to spike along with...

Okay, now the next place you should go is right here to watch the rest of my Unit One videos. Click right here to grab my AP Euro review pack, which has everything you need to get an A in your class and a five on your exam in May. I appreciate you coming around, and I'll catch you on the flip-flop. I'm out.

'''