
= 3.7 - The Rise of ABSOLUTISM
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

We've talked about everything in this unit except the rise of absolutist rulers 专制统治者 in the period 1648 to 1850. So let me put it this way: if the kings of the Middle Ages were like Charmander, and the new monarchs 君主 of the 16th and 17th centuries were like Charmeleon, than the kings of this period are like the first edition shadowless holographic Charizard -- which is to say that since the beginning of this course, monarchs continue to grow in power, and now we're going to talk about the high water mark 最高点, namely absolutism 专制主义. Hey, credit where credit is due 该归功于谁就归功于谁 -- that Pokemon example came from O'Hara through the eras over on Tick Tock. It's brilliant. Hey, if you want follow-along note guides 配套笔记指南 for this video and all my videos, the link is in the description. So if you're ready to get them brain cows milked, let's get to it. +

Now let's start with a definition. Absolutism 专制主义 indicates 表明 the process by which political power 政治权力 was transferred away from 从……转移 the nobility 贵族 and the church and toward the monarch 君主. And that way, it was the monarch that held most of the power in these absolute estates 专制国家. Before I introduce you to several of these big cheese （俚语，重要人物） kings and queens, let's talk about the factors that led to this new form of governance 治理形式. +

The first factor was the weakened influence 影响力减弱 of the Catholic Church 天主教会 due to a growing acceptance and a tolerance of Protestant practice 新教活动 and a lack of interest in religious warfare 宗教战争 after the Peace of Westphalia 威斯特伐利亚和约. The second factor has to do with 与……有关 economics 经济. As we've talked about in other videos, merchant classes 商人阶层 were expanding rapidly 迅速扩张 during this period of global trade 全球贸易, and they in some measure 在某种程度上 desired 渴望 absolute monarchs 专制君主 for the economic and political stability 经济和政治稳定 that they could provide. +

Now one of the main means 主要方式 by which absolute monarchs consolidated their power 巩固权力 under themselves was by weakening the nobility 削弱贵族. Prior to 在……之前 this age, the noble class 贵族阶级 in many European states held a lot of power, and they did a lot of the work of administration 行政管理工作 in the kingdom 王国. But now, absolute monarchs are going to start siphoning that power away from 抽取权力 the nobility by creating giant bureaucracies 庞大的官僚机构 that handle most of the administration of the kingdom. And the big difference here is that the bureaucrats 官僚 were answerable directly to 直接对……负责 the king, whereas the nobility was less so. +

Okay, now let's meet some of these absolutist monarchs 专制君主, and I reckon 认为 we ought to start in England with James the First 詹姆斯一世. You watched my video on the English Civil War 英国内战, you'll remember that James the First was significantly influenced by the idea of the divine right of kings 君权神授观念. This was the idea that a king had been granted political authority 政治权力 by God and was thus answerable only to God -- not to the nobility, not to the people -- God alone. And so James tried to act in accordance with 按照 his divine right by spending money that was unapproved by Parliament 未经议会批准. But that presented a problem in England that won't be a problem in any other attempt at absolutism 专制主义尝试. In England, they had the Magna Carta 大宪章 ratified 批准 in 1215 which officially limited the power of the monarchy 君主权力. So Parliament was always pushing back against 抵制 James's attempts at absolutism. So in the end, England fought a civil war to establish the limited power of the monarch, and so James the First's attempts at absolutism -- you know, they were a failure 失败. +

Now over in Spain, absolutism reached its peak 达到顶峰 in Philip II 腓力二世 in the second half of the 16th century. Philip was able to unite the Iberian Peninsula 伊比利亚半岛 by capturing Portugal 占领葡萄牙 and repulse 击退 those pesky Ottomans 讨厌的奥斯曼人 in the Mediterranean 地中海. But unfortunately for Philip, the rebellion 叛乱 in the Spanish Netherlands 西属尼德兰 -- which we talked about in another video -- and the failure of the Spanish Armada 西班牙无敌舰队 to successfully invade England led to a decline of Spain's power 西班牙国力衰落 over the next century. +

But James and Philip were just the appetizers 开胃菜 of this magnificent absolutist meal, and now we get to the main course 主菜. If there was one monarch that had all the absolutist flavors baked in 具备所有专制主义特征, it was our boy Louis XIV of France 法国的路易十四. In fact, Louie had a little catchphrase 口号 that he was fond of using 喜欢用, namely "L'état, c'est moi," which when being translated means "I am the state." In other words 换句话说, by Louie's reckoning 据路易的理解, the military is not the state, the nobility is not the state, the people are not the state -- I, with my towering butt cut 高耸的发型 and magnificent tights 华丽的紧身衣, am the state. All power belongs to me. +

Now this "I am the state" business didn't arise out of thin air 凭空出现. As a child, Louis was significantly impacted by the rebellion of the nobility and the commoners 贵族与平民的叛乱 that was known as the Fronde 投石党运动 that began in 1648. Alarmed by the increasingly autocratic measures 专制措施 taken by France's chief minister 首席大臣 Cardinal Mazarin 马扎然红衣主教, the judicial nobility 司法贵族 encouraged commoners to riot 煽动平民暴动. And long story short 长话短说, the chaos 混乱 forced young Louis and his mother to flee Paris for safety 逃离巴黎避难. And while the violence died down 平息 a few years later, Louis never forgot the humiliation 屈辱 of fleeing Paris at the hands of the nobility and the chaotic rabble of commoners 贵族和平民暴徒. +

Now let's take a closer look at how Louis XIV, once he came of age 成年后, consolidated power under himself 巩固权力. The first way he did it was by means of 通过 the intendant system 监察官制度. Louis sent bureaucratic agents 官僚代理人 called intendants 监察官 to the various districts of France who acted as avatars of Louis himself 路易的化身. And as such, whatever policies Louis passed, his intendants would make sure that they were obeyed throughout France 确保在法国全境得到执行. This undermined the authority of 削弱……的权威 local governors and authorities to make sure all parts of Louie's kingdom were made to obey his will 服从他的意志. +

And the second way Louis consolidated power under himself was the construction of his magnificent Palace of Versailles 凡尔赛宫. He mandated 命令 that the nobles live at least part of the year within the walls of Versailles. And in that way, Louis was able to keep his eye on 监视 their behavior. Additionally 此外, by establishing an elaborate set of court rituals 复杂的宫廷仪式, nobles began to fight amongst themselves over who would be closest to the king and thus earn his favor 赢得他的青睐 both for themselves and the regions they represented. And just for poops and giggles （俚语，开玩笑地）, the most coveted position 最令人垂涎的职位 -- I kid you not （俚语，不骗你） -- was reserved for the guy who got to hand Louie his shirt in the morning. And by creating this kind of competition among the nobility 在贵族中制造这种竞争, Louis was able to secure their loyalty and cooperation 确保他们的忠诚与合作 and thus consolidated more power under himself. +

The third way Louis consolidated power under himself was by imposing religious uniformity 强制实行宗教统一 throughout France. If you've been around since unit 2, you'll remember that in France there were a growing number of Huguenots 胡格诺派 -- which is to say Protestant Calvinists 新教加尔文派 -- that caused a lot of trouble in France, none of which I'll rehash here 在此不再赘述. But Henry IV 亨利四世 put in place 实施 the Edict of Nantes 南特敕令 which established an almost unheard of degree of religious tolerance 前所未有的宗教宽容 in France for the Protestant minority 新教少数派. Louis XIV decided that to have a state whose people did not all conform to 符合 his own religious beliefs -- which is to say Catholicism 天主教 -- wasn't a good look for a man who desired absolute power 对于渴望绝对权力的人来说不是好事. And therefore in 1685, Louis revoked 废除 the Edict of Nantes, removing protection for the Huguenots. Hundreds of thousands of them migrated to more tolerant states 迁移到更宽容的国家, robbing France of a healthy portion of their merchant class 使法国失去大量商人阶层. +

And the fourth way Louis consolidated power was through his endless wars of expansion 无休止的扩张战争. In order to finance 为……提供资金 Louie's endless wars, his finance minister Jean-Baptiste Colbert 让 - 巴蒂斯特·柯尔贝尔 shaped the French economy according to mercantilist policy 重商主义政策. This had the effect of decreasing France's debt 减少法国债务, it breathed new life into 注入新活力 domestic industries 国内产业, it expanded France's colonial holdings 扩大法国殖民地 and created a favorable balance of trade 贸易顺差. Well done, Colbert. But Louie's endless wars of French conquest 法国的征服战争 cost a metric butt load of money 花费巨额资金, and most of Colbert's work on this front was undone to finance them 为战争提供资金而前功尽弃. +

And finally, let's head over to Russia and see how absolutism is taking shape 形成 over there under Peter the Great 彼得大帝. Now by the time Peter became Tsar 沙皇 in 1682, Russia was still organized according to medieval standards 中世纪标准. Other European nations in the west had adopted new technology and new methods of education and finance 教育和金融新方法, while Russia lagged behind 落后 with a sort of feudalistic society 封建主义社会. And to Peter, that was about as acceptable as a Russian man with a beard （幽默表达）. That joke will make more sense in a minute, but trust me, it's hilarious （幽默表达）. +

Anyway, Peter went on a trip to some of these western nations to see how they did things and returned home convinced that Russia had to westernize 西方化 or else be overtaken by 被……超越 the western nations. So Peter was determined to transform Russia's political, cultural and religious institutions 制度. In terms of 在……方面 political institutions, Peter required nobles to serve in the army or civil administration 军队或民政管理部门. He created a series of ranks 一系列等级 that nobles could move through which meant that experts ended up on top 专家位居高位 -- and this was essential to a modern government 现代政府. Additionally 此外, this made the nobility answerable to Peter himself 直接对彼得负责, and that's how you get absolute power 绝对权力. +

In terms of cultural institutions, Peter didn't see any men sporting beards 留胡子 over in Western Europe, so he required the nobility to shave their beards 剃须 and wear western-style clothing 穿西式服装. He actually created kind of like a fashion police 时尚警察 who would walk around the streets cutting off beards and trimming men's coats to an acceptable western length 修剪成可接受的西式长度. This wasn't just for funsies （俚语，好玩） -- according to the Russian Orthodox Church 俄罗斯东正教会, an unshorn beard 未修剪的胡须 was a sign of piety 虔诚, and thus Peter was challenging the authority of the church by requiring the shaving of beards 挑战教会权威. But don't worry -- if you wanted to keep your beard, then Peter established a beard tax 胡须税 that allowed anyone to keep their lustrous chin music flowing （幽默表达，保留胡须）. +

In terms of religious institutions, Peter reorganized the Russian Orthodox Church 重组俄罗斯东正教会 by eliminating the role of patriarch 牧首职位 -- which is kind of like the pope of the Orthodox church 东正教的教皇 -- and he replaced it with the Holy Synod 神圣宗教会议 which Peter populated with officials and ministers who would do Peter's bidding 听命于彼得. Now in order to pull all this off 完成这一切, Peter tripled taxes 税收增加三倍, and that meant most of the peasantry despised Peter's reforms 厌恶彼得的改革. However, Peter's work to westernize Russia brought the nation into the mainstream of European development 使俄罗斯融入欧洲发展主流. That process was continued through his heir Catherine the Great 叶卡捷琳娜大帝, on whom more in another video. +

All right, click here to keep reviewing unit 3. And since we're at the end of the unit and you are most likely getting ready for an exam, you can click right here to grab my AP Euro review pack 美国大学预修课程欧洲历史复习资料包 which will help you get an A in your class and a five on your exam in May. Hey, I'll catch you on the flip-flop. Heimler out. +

'''

== 中文释义

在这个单元里，我们几乎谈论了所有内容，除了1648年至1850年期间专制统治者的崛起。所以让我这样说吧：如果中世纪的国王就像小火龙（Charmander），16和17世纪的新君主就像火恐龙（Charmeleon），那么这个时期的国王就像第一版无阴影全息喷火龙（Charizard）——也就是说，自从这门课程开始以来，君主的权力不断增长，现在我们要谈论的是权力的顶峰，也就是专制主义。嘿，该归功于谁就归功于谁——那个宝可梦（Pokemon）的例子来自TikTok上的奥哈拉（O'Hara）。这个例子太妙了。嘿，如果你想要这个视频以及我所有视频的配套笔记指南，链接在描述里。所以，如果你准备好充实自己的知识，那我们开始吧。  +

现在让我们从定义开始。专制主义指的是政治权力从贵族和教会手中转移到君主手中的过程。通过这种方式，在这些专制国家里，君主掌握了大部分权力。在我向你介绍几位重要的专制国王和女王之前，让我们谈谈导致这种新治理形式的因素。  +

第一个因素是，由于对新教实践的接受和宽容不断增加，以及《威斯特伐利亚和约》之后人们对宗教战争缺乏兴趣，天主教会的影响力被削弱。第二个因素与经济有关。正如我们在其他视频中谈到的，在这个全球贸易时期，商人阶级迅速扩张，在某种程度上，他们渴望有专制君主，因为专制君主能带来经济和政治稳定。  +

专制君主巩固自身权力的主要手段之一是削弱贵族的权力。在这个时代之前，许多欧洲国家的贵族阶级拥有很大权力，并且他们承担了王国的许多行政工作。但现在，专制君主开始通过建立庞大的官僚机构来处理王国的大部分行政事务，从而削弱贵族的权力。这里的重大区别是，官僚们直接向国王负责，而贵族则并非如此。  +

好的，现在让我们认识一些专制君主，我认为我们应该从英国的詹姆斯一世（James the First）开始。如果你看过我关于英国内战的视频，你会记得詹姆斯一世深受君权神授思想的影响。君权神授的思想是指国王的政治权力由上帝授予，因此只向上帝负责——而不是向贵族或人民负责，只向上帝负责。所以詹姆斯一世试图依据他的神授权力行事，花了一些未经议会批准的钱。但这在英国引发了一个问题，而这个问题在其他专制尝试中不会出现。在英国，1215年批准的《大宪章》（Magna Carta）正式限制了君主的权力。所以议会一直在抵制詹姆斯一世的专制尝试。所以最终，英国爆发了内战，以确立君主的有限权力，因此詹姆斯一世的专制尝试失败了。  +

在西班牙，16世纪后半叶，专制主义在菲利普二世（Philip II）时期达到了顶峰。菲利普二世通过占领葡萄牙并击退地中海地区讨厌的奥斯曼人，成功统一了伊比利亚半岛（Iberian Peninsula）。但对菲利普二世来说不幸的是，西班牙尼德兰（Spanish Netherlands）的叛乱——我们在另一个视频中谈到过——以及西班牙无敌舰队（Spanish Armada）入侵英国的失败，导致西班牙在下个世纪权力衰落。  +

但是詹姆斯一世和菲利普二世只是这顿华丽专制大餐的开胃菜，现在我们要谈的是主菜。如果说有一位君主完全体现了专制主义的特点，那就是法国的路易十四（Louis XIV）。事实上，路易十四有一句他很喜欢用的口头禅，即“L'état, c'est moi”，翻译成中文就是“我即国家”。换句话说，在路易十四看来，军队不是国家，贵族不是国家，人民不是国家——我，有着高耸的发型和华丽的紧身裤，我就是国家。所有权力都属于我。  +

这种“我即国家”的说法并非凭空产生。路易十四小时候，1648年开始的被称为“投石党运动”（Fronde）的贵族和平民叛乱对他产生了重大影响。法国首席大臣马扎然（Cardinal Mazarin）采取的日益专制的措施让司法贵族感到震惊，他们鼓动平民叛乱。长话短说，这场混乱迫使年轻的路易十四和他的母亲为了安全逃离巴黎。虽然几年后暴力事件平息了，但路易十四永远不会忘记被贵族和平民的混乱逼迫逃离巴黎的屈辱。  +

现在让我们仔细看看路易十四成年后是如何巩固自己的权力的。他采取的第一个方法是通过总督制度（intendant system）。路易十四派遣被称为总督（intendants）的官僚代理人到法国的各个地区，这些总督充当路易十四的化身。因此，无论路易十四通过什么政策，他的总督们都会确保这些政策在法国各地得到执行。这削弱了地方总督和当局的权力，以确保路易十四王国的各个部分都服从他的意志。  +

路易十四巩固自身权力的第二个方法是建造宏伟的凡尔赛宫（Palace of Versailles）。他规定贵族每年至少有一部分时间要住在凡尔赛宫的围墙内。通过这种方式，路易十四能够监视他们的行为。此外，通过建立一套精心设计的宫廷仪式，贵族们开始相互争斗，争夺谁能最接近国王，从而为自己和他们所代表的地区赢得国王的青睐。说真的，最令人垂涎的职位——我没开玩笑——是那个早上为路易十四递衬衫的人。通过在贵族之间制造这种竞争，路易十四能够确保他们的忠诚与合作，从而巩固了自己的权力。  +

路易十四巩固权力的第三个方法是在法国推行宗教统一。如果你从第二单元开始就在关注，你会记得在法国，胡格诺派（Huguenots，也就是新教加尔文主义者）的数量不断增加，这在法国引发了很多麻烦，这里我就不再赘述了。但亨利四世（Henry IV）颁布了《南特敕令》（Edict of Nantes），在法国为新教少数派建立了一种几乎前所未有的宗教宽容程度。路易十四认为，对于一个渴望绝对权力的人来说，一个人民不完全服从他宗教信仰（即天主教）的国家看起来不太好。因此，1683年，路易十四废除了《南特敕令》，取消了对胡格诺派的保护。成千上万的胡格诺派迁移到更宽容的国家，法国的商人阶级也因此失去了很大一部分力量。  +

路易十四巩固权力的第四个方法是进行无休止的扩张战争。为了给路易十四无休止的战争提供资金，他的财政大臣让 - 巴蒂斯特·科尔贝（Jean-Baptiste Colbert）根据重商主义政策塑造了法国经济。这一举措减少了法国的债务，为国内产业注入了新的活力，扩大了法国的殖民地，并创造了贸易顺差。科尔贝做得很好。但是路易十四无休止的征服战争花费了大量的钱，为了给这些战争提供资金，科尔贝在这方面的大部分努力都付诸东流了。  +

最后，让我们前往俄罗斯，看看在彼得大帝（Peter the Great）的统治下，专制主义是如何在那里形成的。1682年彼得成为沙皇（Tsar）时，俄罗斯仍然按照中世纪的标准组织。西方的其他欧洲国家已经采用了新的技术、新的教育和金融方法，而俄罗斯则在封建社会中落后了。对彼得来说，这就像一个留着胡子的俄罗斯人一样让人难以接受。这个笑话一会儿你就会明白，相信我，它很有趣。  +

不管怎样，彼得前往一些西方国家，看看他们是如何做事的，回到家后他深信俄罗斯必须西化，否则就会被西方国家超越。所以彼得决心改变俄罗斯的政治、文化和宗教机构。在政治机构方面，彼得要求贵族在军队或民政管理部门服役。他建立了一系列贵族可以晋升的等级制度，这意味着专家最终会处于高位——这对现代政府来说至关重要。此外，这使得贵族们要向彼得大帝本人负责，这就是获取绝对权力的方式。  +

在文化机构方面，彼得发现西欧没有男人留胡子，所以他要求贵族们刮掉胡子，穿上西式服装。他实际上创建了一种“时尚警察”，这些人会在街头走动，剪掉胡子，并把男人们的外套修剪到符合西方标准的长度。这不仅仅是为了好玩——根据俄罗斯东正教会（Russian Orthodox Church）的说法，不修剪的胡子是虔诚的象征，因此彼得要求刮胡子是在挑战教会的权威。但别担心——如果你想保留胡子，彼得设立了胡子税，让任何想留胡子的人都可以继续留着他们漂亮的胡须。  +

在宗教机构方面，彼得重组了俄罗斯东正教会，取消了牧首（patriarch，类似于东正教的教皇）的角色，并用神圣宗教会议（Holy Synod）取而代之，彼得让那些听命于他的官员和牧师来管理神圣宗教会议。为了实现这一切，彼得将税收增加了两倍，这意味着大多数农民都讨厌彼得的改革。然而，彼得使俄罗斯西化的努力让这个国家融入了欧洲发展的主流。这一进程在他的继承人叶卡捷琳娜大帝（Catherine the Great）时期得以延续，我们会在另一个视频中详细介绍她。  +

好的，点击这里继续复习第三单元。既然我们已经到了这个单元的结尾，而你很可能正在准备考试，你可以点击这里获取我的美国大学预修课程欧洲历史复习资料包，它将帮助你在课堂上得A，在五月份的考试中得5分。嘿，我们下次再见。海姆勒下线了。  +

'''

== pure

We've talked about everything in this unit except the rise of absolutist rulers in the period 1648 to 1850. So let me put it this way: if the kings of the Middle Ages were like Charmander, and the new monarchs of the 16th and 17th centuries were like Charmeleon, than the kings of this period are like the first edition shadowless holographic Charizard -- which is to say that since the beginning of this course, monarchs continue to grow in power, and now we're going to talk about the high water mark, namely absolutism. Hey, credit where credit is due -- that Pokemon example came from O'Hara through the eras over on Tick Tock. It's brilliant. Hey, if you want follow-along note guides for this video and all my videos, the link is in the description. So if you're ready to get them brain cows milked, let's get to it.

Now let's start with a definition. Absolutism indicates the process by which political power was transferred away from the nobility and the church and toward the monarch. And that way, it was the monarch that held most of the power in these absolute estates. Before I introduce you to several of these big cheese kings and queens, let's talk about the factors that led to this new form of governance.

The first factor was the weakened influence of the Catholic Church due to a growing acceptance and a tolerance of Protestant practice and a lack of interest in religious warfare after the Peace of Westphalia. The second factor has to do with economics. As we've talked about in other videos, merchant classes were expanding rapidly during this period of global trade, and they in some measure desired absolute monarchs for the economic and political stability that they could provide.

Now one of the main means by which absolute monarchs consolidated their power under themselves was by weakening the nobility. Prior to this age, the noble class in many European states held a lot of power, and they did a lot of the work of administration in the kingdom. But now, absolute monarchs are going to start siphoning that power away from the nobility by creating giant bureaucracies that handle most of the administration of the kingdom. And the big difference here is that the bureaucrats were answerable directly to the king, whereas the nobility was less so.

Okay, now let's meet some of these absolutist monarchs, and I reckon we ought to start in England with James the First. You watched my video on the English Civil War, you'll remember that James the First was significantly influenced by the idea of the divine right of kings. This was the idea that a king had been granted political authority by God and was thus answerable only to God -- not to the nobility, not to the people -- God alone. And so James tried to act in accordance with his divine right by spending money that was unapproved by Parliament. But that presented a problem in England that won't be a problem in any other attempt at absolutism. In England, they had the Magna Carta ratified in 1215 which officially limited the power of the monarchy. So Parliament was always pushing back against James's attempts at absolutism. So in the end, England fought a civil war to establish the limited power of the monarch, and so James the First's attempts at absolutism -- you know, they were a failure.

Now over in Spain, absolutism reached its peak in Philip II in the second half of the 16th century. Philip was able to unite the Iberian Peninsula by capturing Portugal and repulse those pesky Ottomans in the Mediterranean. But unfortunately for Philip, the rebellion in the Spanish Netherlands -- which we talked about in another video -- and the failure of the Spanish Armada to successfully invade England led to a decline of Spain's power over the next century.

But James and Philip were just the appetizers of this magnificent absolutist meal, and now we get to the main course. If there was one monarch that had all the absolutist flavors baked in, it was our boy Louis XIV of France. In fact, Louie had a little catchphrase that he was fond of using, namely "L'état, c'est moi," which when being translated means "I am the state." In other words, by Louie's reckoning, the military is not the state, the nobility is not the state, the people are not the state -- I, with my towering butt cut and magnificent tights, am the state. All power belongs to me.

Now this "I am the state" business didn't arise out of thin air. As a child, Louis was significantly impacted by the rebellion of the nobility and the commoners that was known as the Fronde that began in 1648. Alarmed by the increasingly autocratic measures taken by France's chief minister Cardinal Mazarin, the judicial nobility encouraged commoners to riot. And long story short, the chaos forced young Louis and his mother to flee Paris for safety. And while the violence died down a few years later, Louis never forgot the humiliation of fleeing Paris at the hands of the nobility and the chaotic rabble of commoners.

Now let's take a closer look at how Louis XIV, once he came of age, consolidated power under himself. The first way he did it was by means of the intendant system. Louis sent bureaucratic agents called intendants to the various districts of France who acted as avatars of Louis himself. And as such, whatever policies Louis passed, his intendants would make sure that they were obeyed throughout France. This undermined the authority of local governors and authorities to make sure all parts of Louie's kingdom were made to obey his will.

And the second way Louis consolidated power under himself was the construction of his magnificent Palace of Versailles. He mandated that the nobles live at least part of the year within the walls of Versailles. And in that way, Louis was able to keep his eye on their behavior. Additionally, by establishing an elaborate set of court rituals, nobles began to fight amongst themselves over who would be closest to the king and thus earn his favor both for themselves and the regions they represented. And just for poops and giggles, the most coveted position -- I kid you not -- was reserved for the guy who got to hand Louie his shirt in the morning. And by creating this kind of competition among the nobility, Louis was able to secure their loyalty and cooperation and thus consolidated more power under himself.

The third way Louis consolidated power under himself was by imposing religious uniformity throughout France. If you've been around since unit 2, you'll remember that in France there were a growing number of Huguenots -- which is to say Protestant Calvinists -- that caused a lot of trouble in France, none of which I'll rehash here. But Henry IV put in place the Edict of Nantes which established an almost unheard of degree of religious tolerance in France for the Protestant minority. Louis XIV decided that to have a state whose people did not all conform to his own religious beliefs -- which is to say Catholicism -- wasn't a good look for a man who desired absolute power. And therefore in 1685, Louis revoked the Edict of Nantes, removing protection for the Huguenots. Hundreds of thousands of them migrated to more tolerant states, robbing France of a healthy portion of their merchant class.

And the fourth way Louis consolidated power was through his endless wars of expansion. In order to finance Louie's endless wars, his finance minister Jean-Baptiste Colbert shaped the French economy according to mercantilist policy. This had the effect of decreasing France's debt, it breathed new life into domestic industries, it expanded France's colonial holdings and created a favorable balance of trade. Well done, Colbert. But Louie's endless wars of French conquest cost a metric butt load of money, and most of Colbert's work on this front was undone to finance them.

And finally, let's head over to Russia and see how absolutism is taking shape over there under Peter the Great. Now by the time Peter became Tsar in 1682, Russia was still organized according to medieval standards. Other European nations in the west had adopted new technology and new methods of education and finance, while Russia lagged behind with a sort of feudalistic society. And to Peter, that was about as acceptable as a Russian man with a beard. That joke will make more sense in a minute, but trust me, it's hilarious.

Anyway, Peter went on a trip to some of these western nations to see how they did things and returned home convinced that Russia had to westernize or else be overtaken by the western nations. So Peter was determined to transform Russia's political, cultural and religious institutions. In terms of political institutions, Peter required nobles to serve in the army or civil administration. He created a series of ranks that nobles could move through which meant that experts ended up on top -- and this was essential to a modern government. Additionally, this made the nobility answerable to Peter himself, and that's how you get absolute power.

In terms of cultural institutions, Peter didn't see any men sporting beards over in Western Europe, so he required the nobility to shave their beards and wear western-style clothing. He actually created kind of like a fashion police who would walk around the streets cutting off beards and trimming men's coats to an acceptable western length. This wasn't just for funsies -- according to the Russian Orthodox Church, an unshorn beard was a sign of piety, and thus Peter was challenging the authority of the church by requiring the shaving of beards. But don't worry -- if you wanted to keep your beard, then Peter established a beard tax that allowed anyone to keep their lustrous chin music flowing.

In terms of religious institutions, Peter reorganized the Russian Orthodox Church by eliminating the role of patriarch -- which is kind of like the pope of the Orthodox church -- and he replaced it with the Holy Synod which Peter populated with officials and ministers who would do Peter's bidding. Now in order to pull all this off, Peter tripled taxes, and that meant most of the peasantry despised Peter's reforms. However, Peter's work to westernize Russia brought the nation into the mainstream of European development. That process was continued through his heir Catherine the Great, on whom more in another video.

All right, click here to keep reviewing unit 3. And since we're at the end of the unit and you are most likely getting ready for an exam, you can click right here to grab my AP Euro review pack which will help you get an A in your class and a five on your exam in May. Hey, I'll catch you on the flip-flop. Heimler out.


'''