
= 5.7 - The CONGRESS of VIENNA
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

So while Napoleon is living his best life exiled 流放；放逐 on the island of Saint Helena -- I mean, look at him, he's just so -- the rest of the powers 强国 in Europe have to clean up the mess 收拾烂摊子 he caused on the continent 大陆. And they did that in the Congress of Vienna 维也纳会议, and that is what this video is all about. So if you're ready to get them brain cows milked, let's get to it. By the way, if you want note guides 笔记指南 to follow along with 跟随；伴随 this video, then check the link in the description 说明；描述. +

So recall 回忆；回想 from the previous video on Napoleon that he basically made all of Europe his little plaything 玩物, and that seriously disrupted 扰乱；破坏 the balance of power 权力平衡 on the continent. And I hope that sounds familiar 熟悉的 because we talked about it those many videos ago in Unit 3. Remember that the Peace of Westphalia 威斯特伐利亚和约 in 1648 brought an end to 结束 religion as a cause for European states to go to war. But after that, the main reason states fought was to maintain 维持 that delicate 微妙的 balance of power in Europe. +

And the idea behind the balance of power is that no one wanted any one state to be more powerful than any other state because that would be disastrous 灾难性的. And I'd say that age of Napoleon proved them right. +

So by 1814, about a year before Napoleon's final defeat at Waterloo 滑铁卢, the Quadruple Alliance 四国同盟 -- which included Russia, Prussia, Austria, and Great Britain -- got together 聚集 in what was known as the Congress of Vienna. They completed their work in 1815 after Napoleon's defeat, and that era 时代；时期 is definitely one to know. It is a massive 巨大的 turning point 转折点 in European history precisely 恰恰；正好 because of the work the Congress did. +

So let's talk about the first thing you need to know: that the monarchies 君主制国家 represented in the Quadruple Alliance were pushing for 争取；推动 conservative 保守的 measures 措施. Now, the emphasis 重点；强调 of conservatism 保守主义 during that period was a reliance on 依赖 tradition 传统 and inherited 世袭的 structure 结构. After all 毕竟, look what the liberal 自由的 reforms accomplished in France -- when people are allowed to think for themselves, they'd be cutting people's heads off. +

So these conservative rulers aimed to roll back 撤销；倒退 or at least temper 缓和 the liberal reforms that came out of the French Revolution and hearken back to 回想起 aristocratic 贵族的 and church and monarchical 君主制的 institutions 机构 that had the patina 光泽；表层 of age and stability 稳定 about them. +

The second thing you need to know is that the principal 主要的 driving 推动的 their decisions at the Congress of Vienna was the re-establishment 重新建立 of the balance of power. You can see how important that was to them by the fact that they invited France to the negotiating table 谈判桌. Like, when have you ever heard of a defeated 被打败的 power being offered a seat and an opinion for how things are going to go after they're defeated? +

But the Quadruple Alliance understood that Europe benefited from a strong France -- not too strong, but just strong enough to hold the other powers in bounds 约束；限制. But despite this leniency 宽大；仁慈 toward France, the members of the Congress decided to beef up 加强 defenses 防御 around France as well. Belgium and Holland united under the Dutch monarchy 君主制 and were together a force strong enough to oppose 反对 French aggression 侵略. And Prussia received territory 领土 in France's eastern border, which would help them also keep France in check 控制；制止. +

And the third thing you need to know is the guy who basically orchestrated 精心安排；策划 the Congress, namely 即；也就是 the Austrian foreign minister 外交部长, Clemens von Metternich 克莱门斯·冯·梅特涅. Under his conservative leadership, the Congress basically rolled back the borders of France about 20 years, as it was in 1792. And while this was drastically 极大地 less territory than they had under Napoleon's reign 统治, it was more than they had at the start of the French Revolution. +

So nice. However, while they were working all this out, that was about the time Napoleon escaped from exile 流放, came back to France, and tried to reassert 重申；再次坚持 his power. And after he was defeated, the supremely 极其地 annoyed 恼怒的 Congress took a little more territory from France. But it was still a good deal 划算的交易 for them. I mean, remember, France was the defeated party 战败方 here -- the fact that they're getting anything is pretty great. +

Now, the work of this Congress, conservative as it was, would ultimately 最终 usher in 开创；迎来 50 years of peace on the European continent, a period of time known as the Age of Metternich 梅特涅时代. But we'll revisit 重新审视 that in the next era. +

All right, click here to keep reviewing Unit 5 of AP Euro. And if you need help getting an A in your class and a five on your exam in May, then click right here to grab my AP Euro review pack, which would make all your dreams come true. I'll catch you on the flip-flop. I'm learned. +

'''

== 中文释义

所以当拿破仑在圣赫勒拿岛（Saint Helena）上度过他被流放的日子时——我是说，看看他，他就是这样——欧洲的其他强国, 不得不收拾他在欧洲大陆上留下的烂摊子。他们在"维也纳会议"（Congress of Vienna）上处理了这些问题，而这就是这个视频要讲的内容。所以，如果你准备好充实自己的知识，那我们开始吧。顺便说一下，如果你想要这个视频的笔记指南，那就查看描述中的链接。  +

还记得之前关于**拿破仑**的视频中提到的，他基本上把整个欧洲当作他的玩物，这**严重破坏了欧洲大陆的"权力平衡"。**我希望这听起来很熟悉，因为我们在之前的很多视频的第三单元中谈到过这个。*还记得1648年的《威斯特伐利亚和约》（Peace of Westphalia）结束了宗教作为欧洲各国开战的理由。但在那之后，各国开战的主要原因是为了维持欧洲微妙的"权力平衡"。*  +

*"权力平衡"背后的理念是，没有人希望任何一个国家比其他国家更强大，因为那将是灾难性的。而且我得说，拿破仑时代证明了这一理念的正确性。*  +

所以在1814年，也就是拿破仑在滑铁卢（Waterloo）最终战败的前一年，**四国同盟（Quadruple Alliance，包括俄罗斯、普鲁士、奥地利和英国）在"维也纳会议"上相聚。**在拿破仑战败后的1815年，他们完成了会议的工作，而那个时代绝对是一个需要了解的时代。正是因为**"维也纳会议"所做的工作，它成为了欧洲历史上一个重大的转折点。**  +

所以我们来谈谈你需要知道的第一件事：**四国同盟所代表的"君主制"国家, 推行了保守措施。**在那个时期，保守主义的重点, 是依赖传统和世袭制度。毕竟，看看法国的自由改革带来了什么后果——当人们被允许自主思考时，他们就开始砍别人的头。  +

所以**这些保守的统治者, 旨在推翻或至少缓和"法国大革命"带来的"自由改革"，并回归那些具有历史底蕴和稳定性的贵族、教会, 和君主制机构。**  +

你需要知道的第二件事是，"维也纳会议"上推动他们做决策的主要因素, 是**重新建立"权力平衡"。**从**他们邀请法国参加谈判这件事上，**你可以看出这对他们来说有多重要。我的意思是，*你什么时候听说过一个战败国在战败后, 还能在事务的处理上拥有一席之地并发表意见呢？*  +

**但##四国同盟明白，一个强大的法国, 对欧洲是有益的——不要太强大，但要强大到足以制衡其他强国。##**不过，尽管对法国很宽容，*#会议成员还是决定加强法国周边的防御。比利时和荷兰, 在荷兰君主制下联合起来，成为了一支足以对抗法国侵略的力量。普鲁士在法国东部边境获得了领土，这也有助于他们制衡法国。#*  +

你需要知道的第三件事是，**基本上是奥地利外交大臣克莱门斯·冯·梅特涅（Clemens von Metternich）主导了"维也纳会议"。**在他的保守领导下，会议基本上把法国的边界, 恢复到了大约20年前，也就是1792年的状态。虽然这比拿破仑统治时期的领土少了很多，但比"法国大革命"开始时的领土要多。  +

所以还不错。然而，就在他们解决这些问题的时候，拿破仑从流放中逃脱，回到了法国，并试图重新掌权。在他再次战败后，极其恼怒的会议, 又从法国那里拿走了一些领土。但这对法国来说仍然是不错的结果。我的意思是，记住，*法国是战败国——他们还能保有一些东西已经很不错了。*  +

现在，*#尽管"维也纳会议"是保守的，但它最终带来了欧洲大陆50年的和平(宋辽澶渊之盟, 也给双方带来了120年和平)，这个时期被称为"梅特涅时代"#*（Age of Metternich）。但我们将在下一个时期再回顾这个时代。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第五单元。如果你需要帮助，想在课堂上得A，并在五月份的考试中得5分，那就点击这里获取我的美国大学预修课程欧洲历史复习资料包，它会让你实现所有梦想。我们下次再见。我讲完了。  +

'''

== pure

So while Napoleon is living his best life exiled on the island of Saint Helena -- I mean, look at him, he's just so -- the rest of the powers in Europe have to clean up the mess he caused on the continent. And they did that in the Congress of Vienna, and that is what this video is all about. So if you're ready to get them brain cows milked, let's get to it. By the way, if you want note guides to follow along with this video, then check the link in the description.

So recall from the previous video on Napoleon that he basically made all of Europe his little plaything, and that seriously disrupted the balance of power on the continent. And I hope that sounds familiar because we talked about it those many videos ago in Unit 3. Remember that the Peace of Westphalia in 1648 brought an end to religion as a cause for European states to go to war. But after that, the main reason states fought was to maintain that delicate balance of power in Europe.

And the idea behind the balance of power is that no one wanted any one state to be more powerful than any other state because that would be disastrous. And I'd say that age of Napoleon proved them right.

So by 1814, about a year before Napoleon's final defeat at Waterloo, the Quadruple Alliance -- which included Russia, Prussia, Austria, and Great Britain -- got together in what was known as the Congress of Vienna. They completed their work in 1815 after Napoleon's defeat, and that era is definitely one to know. It is a massive turning point in European history precisely because of the work the Congress did.

So let's talk about the first thing you need to know: that the monarchies represented in the Quadruple Alliance were pushing for conservative measures. Now, the emphasis of conservatism during that period was a reliance on tradition and inherited structure. After all, look what the liberal reforms accomplished in France -- when people are allowed to think for themselves, they'd be cutting people's heads off.

So these conservative rulers aimed to roll back or at least temper the liberal reforms that came out of the French Revolution and hearken back to aristocratic and church and monarchical institutions that had the patina of age and stability about them.

The second thing you need to know is that the principal driving their decisions at the Congress of Vienna was the re-establishment of the balance of power. You can see how important that was to them by the fact that they invited France to the negotiating table. Like, when have you ever heard of a defeated power being offered a seat and an opinion for how things are going to go after they're defeated?

But the Quadruple Alliance understood that Europe benefited from a strong France -- not too strong, but just strong enough to hold the other powers in bounds. But despite this leniency toward France, the members of the Congress decided to beef up defenses around France as well. Belgium and Holland united under the Dutch monarchy and were together a force strong enough to oppose French aggression. And Prussia received territory in France's eastern border, which would help them also keep France in check.

And the third thing you need to know is the guy who basically orchestrated the Congress, namely the Austrian foreign minister, Clemens von Metternich. Under his conservative leadership, the Congress basically rolled back the borders of France about 20 years, as it was in 1792. And while this was drastically less territory than they had under Napoleon's reign, it was more than they had at the start of the French Revolution.

So nice. However, while they were working all this out, that was about the time Napoleon escaped from exile, came back to France, and tried to reassert his power. And after he was defeated, the supremely annoyed Congress took a little more territory from France. But it was still a good deal for them. I mean, remember, France was the defeated party here -- the fact that they're getting anything is pretty great.

Now, the work of this Congress, conservative as it was, would ultimately usher in 50 years of peace on the European continent, a period of time known as the Age of Metternich. But we'll revisit that in the next era.

All right, click here to keep reviewing Unit 5 of AP Euro. And if you need help getting an A in your class and a five on your exam in May, then click right here to grab my AP Euro review pack, which would make all your dreams come true. I'll catch you on the flip-flop. I'm learned.

'''