
= 7.2 NATIONALISM
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Welcome to unit 7 of AP European History. I'm Steve Heimler, and we are still in the time period 1815-1914. And this video is all about how a strong sense of nationalism 民族主义 swept across the European continent in the 19th century, and all the consequences 后果 of said nationalism. So if you're ready to get them brain cows milked, let's get to it. +

Okay, the idea of the nation-state 民族国家 came to dominate 统治；支配 Europe during this period, and it was definitely a new way to organize the continent politically. We look at a map of Europe today, or anywhere else for that matter, we're used to seeing that these little lines separate one country from another. But if you walk to the place where that border 边界 exists on a map, you would not see a line on the ground marking this country from that country. +

Those lines are made up by powerful people, and those lines didn't really become a thing until the period we're talking about in this video. By the way, since we're in unit seven and you have exams coming up and the national exam looming 逼近；隐约出现 in the not too distant future, you might want to check out my AP Euro review pack, which has practice questions and exclusive 独有的；排他的 review videos and everything you need to get an A in your course and a five on your examination. To get that, clicky finger out and check the link in the description. +

Okay, so what was it that created the occasion for these imaginary 想象的；虚构的 lines? Well, in short, it was the rise of nationalism during this period. Nationalism, as I've mentioned before, is a feeling of strong identification 认同；身份认同 with one's own people and one's own cultural heritage 文化遗产, and those bonds 纽带；联系 are strengthened by a shared history and a shared language. +

So now you have two elements 要素；元素 that make up the nation-state. There's the nation, which is to say the people who share the language and the culture, and then there's the state, which is the land on which they live, surrounded by borders on a map, and the government which rules over them. +

So think about it this way. I live in Georgia, and that means I live much closer to Cuba than I do to California. And yet I feel more identified with people who live in California than people who live in Cuba. And why? Because Californians are Americans, and we share a cultural heritage and a history and, for the most part, a common language -- even though America doesn't really have an official language. But Cubans speak a different language, bear a different history and cultural artifacts 手工艺品；文物 that do not properly belong to me. +

So I feel more identified with Californians than I do with Cubans. Now to be clear, I'm not saying one is better than another -- it's just identification. Nationalism will go there by the end of this video, but that's not what I'm saying now. +

Okay, so a rising sense of nationalism during this period of European history is going to cause more and more Europeans to demand their own state where they lived with their own people. So now we need to talk about how this growing nationalism encouraged loyalty 忠诚；忠心 to a state. +

The first way nationalism gripped 吸引；抓住 people was because of romantic idealism 浪漫主义理想. Remember when we talked about the rise of Romanticism 浪漫主义 in the last unit? Romantic artists and writers glorified 赞美；颂扬 their people's past, and in doing so created an emotional fervor 热情；狂热 in the people to reclaim 收回；恢复 that past. +

For example, the Grimm Brothers in Germany collected and published German fairy tales 童话 and folk tales 民间故事. And these were the stories of the German people, and when they read them, it wasn't just entertainment -- it had the effect of making them feel more German. +

Or take the French writer Victor Hugo, whose novel "Les Misérables" was the story of the triumph 胜利；凯旋 of the French people against tyrants 暴君. All of these artists had a way of binding 捆绑；结合 their people together as a people. +

Okay, second, nationalism was on the rise because of liberal reform 自由改革. The guy you need to associate with this was Francis Napoleon III, nephew of Bonaparte. He opened the way for international trade through cooperation with foreign markets, and that boosted 促进；推动 the French economy. +

And he also instituted 制定；设立 universal male suffrage 男性普选权, which made him exceedingly 极其；非常 popular. And with his complete overhaul 彻底改革 of the new Paris combined with everything else I just said, French nationalism grew significantly. +

And then third, nationalism was encouraged by movements of political unification 政治统一运动. For example, in the Italian states, Giuseppe Mazzini pushed to unite the various Italian political entities 实体 into a single nation-state. To that end, he formed an Italian unification movement called Young Italy and staged 发动 uprisings 起义 around Italy. +

Now ultimately Mazzini wasn't successful in his unification efforts, but his work set the stage for 为…做好准备 Italian unification, which we will consider in another video. +

Fourth, this growing nationalism encouraged a growing racialism 种族主义, which was the idea that one race is superior to 优于；胜过 another. That shouldn't be surprising since nationalism is a strong identification with one's own people -- it's only a small step to believing that our people are better than yours. +

Now there's a positive side to racialism and a negative side. The positive side is represented by the pan-Slavic movement 泛斯拉夫运动 in Eastern and Central Europe. In these areas, there were significant groups of Slavic peoples who were under the imperial fist of the Austro-Hungarian and Ottoman Empires. +

And because they began to feel real identification with their own people, they longed to have a state of their own. Because Russia was a Slavic nation, they supported this movement, and that support would eventually lead to war with Ottomans. But we'll consider that in another video as well. +

Now the dark side of racialism came in the form of anti-Semitism 反犹主义, and I reckon 认为；估计 it needs its own heading. Now anti-Semitism by definition includes racist beliefs against the Jewish people. +

European Jews, for the most part, had a long history of marginalization 边缘化 in and around Europe. But by this period, while anti-Semitism was still present, many states had passed laws recognizing Jewish equality and ending much of the harassment 骚扰 that they had endured. +

Both the rise of nationalism and anti-Semitism rose right along with it. One of the key events that helped spark 引发；激起 it was the Dreyfus Affair 德雷福斯事件 in France. Alfred Dreyfus was the captain in the French army who happened to be Jewish. +

In 1894, he was accused of treason 叛国罪 because he allegedly 据说；据称 leaked secret information to Germany. He was tried and found guilty, but the affair divided French society. Some argued that he was being accused simply because he was Jewish, and others, precisely because he was Jewish, viewed him with suspicion 怀疑 and thought the charges were believable. +

After 10 years, Dreyfus was pardoned 赦免, but not before the news had spread throughout Europe and resurrected 复活；复兴 the anti-Semitism that had long lain dormant 潜伏的；休眠的 in Eastern Europe. This discrimination 歧视 resulted in pogroms 大屠杀 in which Jews were evicted 驱逐 from their homes and violently attacked without reason. +

Now in response to this growing anti-Semitism, a Jewish nationalist movement known as Zionism 犹太复国主义 rose up to defend against it. Theodore Herzl was a German Jew who argued in 1895 that Jews should have a land of their own, and that land ought to be their ancestral 祖先的；祖传的 home in Palestine. +

That would remain only a dream until after World War II, but the origins of the nation of Israel began with Herzl's nationalist movement. +

All right, I know this is a lot of information to digest 消化；理解, so slap yourself in the face, wake up, and let's keep going. +

So if you've been with me from unit 6, you already know that thanks to Clemens von Metternich and his engineering 策划；密谋 of the Concert of Europe, conservatism 保守主义 reigned supreme 占主导地位 across the European continent during the 19th century. If you want a quick review of that, my AP Euro review pack will get it to you quicker than it hurts. +

But now we get to a new generation of neoconservative 新保守主义的 leaders who are going to use nationalism to strengthen their grip on state. Now I already mentioned how Napoleon III did this with his liberal reforms in France, so let me introduce you to another one of these conservative leaders, namely Otto von Bismarck of Prussia. +

Now remember what we would call Germany today during this period was still a massive collection of smallish states, and among the most powerful of these states was Prussia. And it was Bismarck who was able to harness 利用 German nationalism as Prussian foreign minister and then prime minister to take steps toward German unification. +

In fact, we're going to see in the next video how Bismarck intentionally 故意地；有意地 provoked 激起；引发 wars in order to rile the German people up with an overwhelming sense of nationalism so that German unification could become a reality. +

But nationalism was also the key in creating the dual monarchy 二元君主制 of Austria-Hungary. After the Revolutions of 1848, the Austrians attempted to suppress 镇压；压制 the rising Hungarian nationalism but were ultimately unsuccessful. +

The compromise 妥协；折衷 is that they would create a dual monarchy with Austrian and Hungarian monarchs. This was their solution to stabilize 使稳定 the state by reconfiguring 重新配置 their concept of national union. +

So the point is, many of the results of this rise of nationalism won't occur until the next video. But when it does, we'll begin to see that imaginary lines drawn on maps become a real and abiding 持久的；永久的 reality. +

All right, click right here to keep reviewing unit 7 of AP European History, and click here to grab my video note guides which follow along exactly with my videos here on YouTube and can help you learn all the content of the course. I'll catch you on the flip-flop. I'm Heimler. +

'''

== 中文释义

欢迎来到美国大学预修课程欧洲历史的第七单元。我是史蒂夫·海姆勒，我们仍然处于**1815年至1914年这个时间段。**这个视频主要讲述的是19世纪一股强烈的"民族主义"浪潮席卷欧洲大陆，以及上述民族主义所带来的所有后果。所以，如果你准备好充实自己的知识，那我们开始吧。  +

好的，**##"民族国家"的概念, 在这个时期开始主导欧洲，##这绝对是一种在政治上组织欧洲大陆的新方式。**我们看看今天欧洲的地图，或者在其他任何地方也是如此，我们已经习惯看到这些分界线, 把一个国家和另一个国家分隔开来。但如果你走到地图上分界线所在的地方，你在地面上是看不到标记着这个国家和那个国家的分界线的。  +

这些分界线是由有权势的人划定的，而且这些分界线直到我们在这个视频中讨论的时期, 才真正成为一种存在。顺便说一下，因为我们现在在第七单元，而且你即将迎来考试，全国性考试也在不远处，你可能想要查看我的美国大学预修课程欧洲历史复习资料包，里面有练习题、独家复习视频，以及你在课程中得A和在考试中得5分所需要的一切。要获取它，动动手指，查看描述中的链接。  +

那么，是什么促成了这些想象中的分界线的出现呢？简而言之，是这个时期民族主义的兴起。正如我之前提到的，民族主义是一种对自己的民族和文化遗产的强烈认同感，而且这些联系通过共同的历史和共同的语言, 得到加强。  +

所以, 现在有两个要素构成了民族国家。一个是民族，也就是说拥有共同语言和文化的人民，另一个是国家，也就是他们生活的土地，在地图上有边界，并且有统治他们的政府。  +

所以这样来考虑。我住在佐治亚州（Georgia），这意味着我离古巴（Cuba）比离加利福尼亚州（California）更近。然而，我对住在加利福尼亚州的人, 比对住在古巴的人有更强的认同感。为什么呢？因为加利福尼亚人是美国人，我们拥有共同的文化遗产和历史，而且在很大程度上，还有共同的语言——尽管美国实际上并没有官方语言。但古巴人说不同的语言，拥有不同的历史和文化产物，这些都与我无关。  +

所以我对加利福尼亚人的认同感, 比对古巴人的更强。需要明确的是，我不是说一方比另一方更好——这只是一种认同感。在这个视频结束时我们还会谈到民族主义，但这不是我现在要说的。  +

好的，在欧洲历史的**这个时期，不断高涨的民族主义情绪, 导致越来越多的欧洲人要求建立他们自己的国家，**在那里和自己的人民生活在一起。所以现在我们需要谈谈这种日益增长的民族主义, 是如何激发人们对国家的忠诚的。  +

民族主义影响人们的第一个方面, 是因为浪漫主义理想主义。还记得我们在上一单元谈到的浪漫主义的兴起吗？浪漫主义艺术家和作家歌颂他们民族的过去，这样做在人民中引发了一种情感上的狂热，让他们想要重新夺回那段历史。  +

例如，德国的格林兄弟（Grimm Brothers）收集并出版了德国的童话故事和民间故事。这些是德国人民的故事，当他们阅读这些故事时，这不仅仅是娱乐——它让他们更有身为德国人的感觉。  +

或者以法国作家维克多·雨果（Victor Hugo）为例，他的小说《悲惨世界》（“Les Misérables”）讲述的是法国人民战胜暴君的故事。所有这些艺术家都有一种把他们的人民凝聚在一起的方式。  +

好的，民族主义兴起的第二个原因, 是自由主义改革。与这一点相关的人物是波拿巴（Bonaparte）的侄子弗朗西斯·拿破仑三世（Francis Napoleon III）。他通过与国外市场合作, 开辟了国际贸易的道路，这促进了法国经济的发展。  +

而且他还实行了男性普选权，这使他非常受欢迎。再加上他对新巴黎的全面改造, 以及我刚才提到的其他所有因素，法国的民族主义显著增强。  +

第三，政治统一运动也推动了民族主义的发展。例如，在意大利各邦，朱塞佩·马志尼（Giuseppe Mazzini）推动将各个意大利政治实体统一成一个单一的民族国家。为此，他成立了一个名为“青年意大利”（Young Italy）的意大利统一运动，并在意大利各地发动起义。  +

最终，马志尼的统一努力没有成功，但他的工作为意大利的统一奠定了基础，我们会在另一个视频中探讨这一点。  +

第四，不断增长的民族主义催生了日益严重的种族主义，其观点是一个种族比另一个种族优越。这并不奇怪，因为民族主义是对自己民族的强烈认同——从这种认同到认为我们的民族比你们的民族更好，只是一小步。  +

种族主义有积极的一面，也有消极的一面。积极的一面以东欧和中欧的泛斯拉夫运动为代表。在这些地区，有大量的斯拉夫民族处于奥匈帝国和奥斯曼帝国的统治之下。  +

因为他们开始对自己的民族产生强烈的认同感，他们渴望拥有自己的国家。由于俄罗斯（Russia）是一个斯拉夫民族的国家，他们支持这个运动，而这种支持最终导致了与奥斯曼帝国的战争。但我们也会在另一个视频中探讨这个问题。  +

现在，种族主义的黑暗面以反犹主义的形式出现，我认为这一点需要单独来讲。从定义上来说，反犹主义包含了对犹太人的种族主义信仰。  +

在欧洲，大部分犹太人在欧洲及其周边地区长期处于被边缘化的状态。但在这个时期，尽管反犹主义仍然存在，许多国家还是通过了法律，承认犹太人的平等地位，并结束了他们长期遭受的许多骚扰。  +

民族主义的兴起和反犹主义的出现是同时发生的。其中一个引发反犹主义的关键事件是法国的德雷福斯事件（Dreyfus Affair）。阿尔弗雷德·德雷福斯（Alfred Dreyfus）是法国军队的一名上尉，他恰好是犹太人。  +

1894年，他被指控叛国，因为据说他向德国泄露了秘密信息。他受审并被判有罪，但这一事件使法国社会产生了分裂。一些人认为他仅仅因为是犹太人而被指控，而另一些人则因为他是犹太人而对他持怀疑态度，认为这些指控是可信的。  +

10年后，德雷福斯被赦免，但在此之前，这个消息已经传遍了欧洲，复活了东欧长期潜伏的反犹主义。这种歧视导致了大屠杀，犹太人被驱逐出家园，并遭到无端的暴力攻击。  +

为了应对日益严重的反犹主义，一场名为犹太复国主义（Zionism）的犹太民族主义运动兴起以进行反抗。西奥多·赫茨尔（Theodore Herzl）是一名德国犹太人，他在1895年主张犹太人应该拥有自己的土地，而这片土地应该是他们在巴勒斯坦（Palestine）的祖传家园。  +

直到第二次世界大战后，这仍然只是一个梦想，但以色列国的起源始于赫茨尔的民族主义运动。  +

好的，我知道这里有很多信息需要消化，所以拍拍自己的脸，清醒一下，我们继续。  +

所以如果你从第六单元一直跟我学到现在，你已经知道，多亏了克莱门斯·冯·梅特涅（Clemens von Metternich）以及他策划的欧洲协调（Concert of Europe），19世纪保守主义在欧洲大陆占据主导地位。如果你想快速回顾一下，我的美国大学预修课程欧洲历史复习资料包能比你受伤的速度还快地让你了解相关内容。  +

但现在我们要谈谈新一代的新保守主义领导人，他们将利用民族主义来加强对国家的控制。我已经提到过拿破仑三世通过在法国的自由主义改革做到了这一点，所以让我给你介绍另一位这样的保守主义领导人，即普鲁士（Prussia）的奥托·冯·俾斯麦（Otto von Bismarck）。  +

记住，在这个时期我们现在所说的德国仍然是由许多小邦组成的庞大集合，而普鲁士是其中最强大的邦之一。正是俾斯麦作为普鲁士的外交大臣，后来又担任首相，利用德国的民族主义朝着德国统一迈出了步伐。  +

事实上，我们将在下一个视频中看到俾斯麦是如何故意挑起战争，用强烈的民族主义情绪煽动德国人民，从而使德国统一成为现实的。  +

但民族主义也是建立奥匈帝国二元君主制的关键。1848年革命（Revolutions of 1848）之后，奥地利人试图镇压不断高涨的匈牙利民族主义，但最终没有成功。  +

他们的妥协方案是建立一个由奥地利和匈牙利君主组成的二元君主制国家。这是他们通过重新配置民族联盟的概念来稳定国家的解决方案。  +

所以重点是，民族主义兴起所带来的许多结果要到下一个视频才会呈现。但到那时，我们将开始看到地图上那些想象中的分界线变成真实且持久的现实。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第七单元，点击这里获取我的视频笔记指南，它与我在YouTube上的视频完全配套，可以帮助你学习课程的所有内容。我们下次再见。我是海姆勒。  +

'''

== pure

Welcome to unit 7 of AP European History. I'm Steve Heimler, and we are still in the time period 1815-1914. And this video is all about how a strong sense of nationalism swept across the European continent in the 19th century, and all the consequences of said nationalism. So if you're ready to get them brain cows milked, let's get to it.

Okay, the idea of the nation-state came to dominate Europe during this period, and it was definitely a new way to organize the continent politically. We look at a map of Europe today, or anywhere else for that matter, we're used to seeing that these little lines separate one country from another. But if you walk to the place where that border exists on a map, you would not see a line on the ground marking this country from that country.

Those lines are made up by powerful people, and those lines didn't really become a thing until the period we're talking about in this video. By the way, since we're in unit seven and you have exams coming up and the national exam looming in the not too distant future, you might want to check out my AP Euro review pack, which has practice questions and exclusive review videos and everything you need to get an A in your course and a five on your examination. To get that, clicky finger out and check the link in the description.

Okay, so what was it that created the occasion for these imaginary lines? Well, in short, it was the rise of nationalism during this period. Nationalism, as I've mentioned before, is a feeling of strong identification with one's own people and one's own cultural heritage, and those bonds are strengthened by a shared history and a shared language.

So now you have two elements that make up the nation-state. There's the nation, which is to say the people who share the language and the culture, and then there's the state, which is the land on which they live, surrounded by borders on a map, and the government which rules over them.

So think about it this way. I live in Georgia, and that means I live much closer to Cuba than I do to California. And yet I feel more identified with people who live in California than people who live in Cuba. And why? Because Californians are Americans, and we share a cultural heritage and a history and, for the most part, a common language -- even though America doesn't really have an official language. But Cubans speak a different language, bear a different history and cultural artifacts that do not properly belong to me.

So I feel more identified with Californians than I do with Cubans. Now to be clear, I'm not saying one is better than another -- it's just identification. Nationalism will go there by the end of this video, but that's not what I'm saying now.

Okay, so a rising sense of nationalism during this period of European history is going to cause more and more Europeans to demand their own state where they live with their own people. So now we need to talk about how this growing nationalism encouraged loyalty to a state.

The first way nationalism gripped people was because of romantic idealism. Remember when we talked about the rise of Romanticism in the last unit? Romantic artists and writers glorified their people's past, and in doing so created an emotional fervor in the people to reclaim that past.

For example, the Grimm Brothers in Germany collected and published German fairy tales and folk tales. And these were the stories of the German people, and when they read them, it wasn't just entertainment -- it had the effect of making them feel more German.

Or take the French writer Victor Hugo, whose novel "Les Misérables" was the story of the triumph of the French people against tyrants. All of these artists had a way of binding their people together as a people.

Okay, second, nationalism was on the rise because of liberal reform. The guy you need to associate with this was Francis Napoleon III, nephew of Bonaparte. He opened the way for international trade through cooperation with foreign markets, and that boosted the French economy.

And he also instituted universal male suffrage, which made him exceedingly popular. And with his complete overhaul of the new Paris combined with everything else I just said, French nationalism grew significantly.

And then third, nationalism was encouraged by movements of political unification. For example, in the Italian states, Giuseppe Mazzini pushed to unite the various Italian political entities into a single nation-state. To that end, he formed an Italian unification movement called Young Italy and staged uprisings around Italy.

Now ultimately Mazzini wasn't successful in his unification efforts, but his work set the stage for Italian unification, which we will consider in another video.

Fourth, this growing nationalism encouraged a growing racialism, which was the idea that one race is superior to another. That shouldn't be surprising since nationalism is a strong identification with one's own people -- it's only a small step to believing that our people are better than yours.

Now there's a positive side to racialism and a negative side. The positive side is represented by the pan-Slavic movement in Eastern and Central Europe. In these areas, there were significant groups of Slavic peoples who were under the imperial fist of the Austro-Hungarian and Ottoman Empires.

And because they began to feel real identification with their own people, they longed to have a state of their own. Because Russia was a Slavic nation, they supported this movement, and that support would eventually lead to war with Ottomans. But we'll consider that in another video as well.

Now the dark side of racialism came in the form of anti-Semitism, and I reckon it needs its own heading. Now anti-Semitism by definition includes racist beliefs against the Jewish people.

European Jews, for the most part, had a long history of marginalization in and around Europe. But by this period, while anti-Semitism was still present, many states had passed laws recognizing Jewish equality and ending much of the harassment that they had endured.

Both the rise of nationalism and anti-Semitism rose right along with it. One of the key events that helped spark it was the Dreyfus Affair in France. Alfred Dreyfus was the captain in the French army who happened to be Jewish.

In 1894, he was accused of treason because he allegedly leaked secret information to Germany. He was tried and found guilty, but the affair divided French society. Some argued that he was being accused simply because he was Jewish, and others, precisely because he was Jewish, viewed him with suspicion and thought the charges were believable.

After 10 years, Dreyfus was pardoned, but not before the news had spread throughout Europe and resurrected the anti-Semitism that had long lain dormant in Eastern Europe. This discrimination resulted in pogroms in which Jews were evicted from their homes and violently attacked without reason.

Now in response to this growing anti-Semitism, a Jewish nationalist movement known as Zionism rose up to defend against it. Theodore Herzl was a German Jew who argued in 1895 that Jews should have a land of their own, and that land ought to be their ancestral home in Palestine.

That would remain only a dream until after World War II, but the origins of the nation of Israel began with Herzl's nationalist movement.

All right, I know this is a lot of information to digest, so slap yourself in the face, wake up, and let's keep going.

So if you've been with me from unit 6, you already know that thanks to Clemens von Metternich and his engineering of the Concert of Europe, conservatism reigned supreme across the European continent during the 19th century. If you want a quick review of that, my AP Euro review pack will get it to you quicker than it hurts.

But now we get to a new generation of neoconservative leaders who are going to use nationalism to strengthen their grip on state. Now I already mentioned how Napoleon III did this with his liberal reforms in France, so let me introduce you to another one of these conservative leaders, namely Otto von Bismarck of Prussia.

Now remember what we would call Germany today during this period was still a massive collection of smallish states, and among the most powerful of these states was Prussia. And it was Bismarck who was able to harness German nationalism as Prussian foreign minister and then prime minister to take steps toward German unification.

In fact, we're going to see in the next video how Bismarck intentionally provoked wars in order to rile the German people up with an overwhelming sense of nationalism so that German unification could become a reality.

But nationalism was also the key in creating the dual monarchy of Austria-Hungary. After the Revolutions of 1848, the Austrians attempted to suppress the rising Hungarian nationalism but were ultimately unsuccessful.

The compromise is that they would create a dual monarchy with Austrian and Hungarian monarchs. This was their solution to stabilize the state by reconfiguring their concept of national union.

So the point is, many of the results of this rise of nationalism won't occur until the next video. But when it does, we'll begin to see that imaginary lines drawn on maps become a real and abiding reality.

All right, click right here to keep reviewing unit 7 of AP European History, and click here to grab my video note guides which follow along exactly with my videos here on YouTube and can help you learn all the content of the course. I'll catch you on the flip-flop. I'm Heimler.

'''