
= 7.6 Second Wave IMPERIALISM
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

All right, it's time for a new wave of imperialism 帝国主义 in European history. So I reckon 认为；估计 we ought to talk about why the Europeans did it -- which is to say their motivations -- and how the Europeans did it -- which is to say their methods. So if you're ready to get them brain cows milked, let's get to it. +

So remember that when this course began in 1450, there was a surge 激增；汹涌 in European imperialism as Western European states began sailing west across the Atlantic and east into the Indian Ocean. And in this period, there is a new wave of European imperialism, and it's going to focus on Africa and Asia. +

Now by definition, imperialism is when one country extends political dominance 统治；支配 over another country. And why would another country want to do that? Well, I got three reasons for it. Oh, and if you're studying for an exam, don't forget to check out my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May. Link in description. +

Okay, the first motivation 动机；动力 for the second wave of European imperialism was economic. Now remember, many of the states in Western Europe were in the heyday 全盛时期 of the Industrial Revolution during this period, and they were getting fabulously 极其；非常 wealthy as a result. But in order to keep those factories working, states needed two things: raw materials 原材料 and markets. +

They needed raw materials like cotton and rubber and iron in order to make the final manufactured goods coming out of the factory. Once a nation had tapped 开发；利用 all their own resources, they went looking in other places of the world to get those raw materials. So there was a significant motivation there for the new imperial events. +

But once the goods were finished, they also needed people to buy those manufactured goods. And when the markets at home became saturated 饱和的, they needed to go take over other countries so they could open those new markets in other places. For example, once the British government took control over India after the Sepoy Rebellion 印度土兵起义 in 1857, they began to exploit 剥削；利用 the Indians to gain valuable raw materials -- not least cotton -- but also since there was something like 300 million people living in India, the British now had 300 million people to whom they could sell those manufactured textiles 纺织品. And the wealth came pouring into the British coffers 金库；国库 as a result. +

Starting in this period, the British colonized 殖民；开拓殖民地 a few places in West Africa, and then a huge swath 大片；大块 of territory right down the eastern side of the entire continent in Africa. The British were mainly interested in gaining access to raw materials like coal and oil and copper. +

The British also turned their imperialistic 帝国主义的；扩张主义的 gaze 注视；凝视 upon China. But in China, they engaged in economic imperialism rather than political imperialism. And the story went a little something like this: the British trade with the Chinese was fundamentally 根本地；基础地 out of balance. The Brits wanted Chinese tea by the metric ton, but there wasn't as much the Chinese wanted from the British. So as British money is flowing into China, there is no Chinese money flowing into Britain. And that's going to be a problem for the British. +

Now I'd like to tell you that the British addressed 处理；解决 this issue by asking the Chinese what kinds of products they wanted, and then used innovative 创新的；革新的 thinking to create goods that the Chinese wanted, and the trade imbalance 不平衡 was corrected. But that's not what the British did. Instead, they began smuggling 走私 the highly addictive 使人上瘾的 drug called opium 鸦片 into China from India. And it didn't take long for the Chinese to get hooked on this drug. And because India had prime 主要的；首要的 growing conditions for opium, the British illegally imported it into China by the metric ton. +

But if that sounds a little underhanded 不光明正大的；暗中的 to you, well then the Chinese officials of that time would agree with you. In 1839, the Chinese government seized 没收；扣押 like 20,000 pounds of opium being imported into China and destroyed it. And along with a couple other smaller incidents, this event led to the first Opium War 鸦片战争 between Britain and China. +

Now China had been exceedingly 极其；非常 sluggish 缓慢的；迟缓的 when it came to adapting to the new industrial world, but not Britain. Remember, Britain was essentially 本质上；根本上 the first mover in the Industrial Revolution, and so they had a much greater advantage in weaponry 武器；军备 against the Chinese. Needless to say, the British won this war -- and the second Opium War, which also included France -- and forcibly 强行地；强制地 opened trading rights into China. +

Okay, now the second motivation for the second wave of imperialism was political. Now I've been talking a lot about Britain because they were arguably 可以说；按理说 the big dog of the second wave of European imperialism, but that doesn't mean that other European states didn't get in on the party too. Several European nations were clamoring for 强烈要求；吵着要 territory in Africa, including the French and the Dutch and the Belgians. And this became known as the Scramble for Africa 非洲争夺战. +

This dirty clamoring for African territory began to cause significant tension among these states. Once the interior 内部；内地 of Africa was mapped by agents of Belgian King Leopold, European states raced to claim territories before other states got to them. And that would cause significant tension that we're going to consider in the next video. +

And the third motivation for the second wave of imperialism was a belief in racial superiority 优越；优势. Recall 回忆；回想 a couple videos ago when we talked about the budding 萌芽的；初现的 racialist 种族主义的 philosophy called social Darwinism 社会达尔文主义. By the late 19th century, that ideology 意识形态；思想体系 had taken full root and provided the motivation for strong nations with advanced civilizations -- that you know, at least that's how they sell themselves -- to take over weak nations with primitive 原始的；落后的 civilizations. +

Like when you contrasted 对比；对照 the wealth and power that industrialized nations in Europe had accumulated 积累；积聚 with the relative poverty of places in Africa, a social Darwinist would conclude that clearly Western nations were superior. Western nations have adapted better to their environment and thus are not only surviving but thriving 繁荣；兴旺. Therefore, if the strong eat the weak by the laws of nature, why shouldn't the strong nations eat the weak nations? +

But if you would ask these Europeans directly if what they were doing was morally 道德上；道义上 wrong, yeah, they would have laughed. Of course it's not wrong. And one of the main reasons is because they truly believe they were bringing the glories of Western civilization to bear on people who desperately 极度地；非常地 needed it. The French term for this was the mission civilisatrice 文明使命, which when being translated means the civilizing mission. In other words, by European reckoning 估计；推断, imperialism was good for the colonized 殖民地居民 because they got access to the best culture the world had to offer. +

And probably the clearest manifestation 表现；显示 of the beliefs of European racial superiority is a poem by Rudyard Kipling called "White Man's Burden." It talks about the peoples of Africa and calls them "half devil and half child." Therefore, the white man ought to "send the best ye breed" in order to "serve your captives' need." And so if this was the belief imperial nations clung to, then it was not an evil to imperialize 使帝国主义化；实行帝国主义 another weaker nation, but rather benevolent 仁慈的；慈善的 in mercy to bring them the glories of Western culture. +

Now I probably don't need to tell you that Africans and Asians were not as jazzed 兴奋的；热情的 about the glories of Western culture as the Europeans were. In fact, in many cases, they put up stiff 激烈的；顽强的 resistance 抵抗；反抗 against European intrusion 入侵；干涉 into their homeland. But unfortunately, Europeans had several advantages that gave them the upper hand 优势；有利地位 against those who resisted. +

The first advantage Europeans had was advanced weapons. And I cannot emphasize 强调；着重 enough just how much the Industrial Revolution contributed to this advantage. Guns were updated to include a rifled barrel 膛线枪管, which means there were spiral grooves 螺旋形凹槽 cut along the inside of them, which increased the accuracy 准确性；精确度 of the shot. Additionally, the Minié ball 米尼弹 was invented, which was a conical 圆锥的；圆锥形的 bullet which was more accurate and did way more damage than the traditional musket 滑膛枪；火绳枪. +

Additional Europeans manufactured the breech-loading rifle 后装步枪 in which bullets could be loaded much quicker, and they had access to machine gun technology which could fire hundreds of rounds at great speed. The point is, Europeans had weapons that could deliver lead into the bodies of those who opposed them much quicker than anyone who resisted. +

The second advantage Europeans had was new communication and transportation technology. Communication was enhanced 增强；提高 by the speed of the telegraph 电报 and the ability to run cables under the water and at great length. This enabled coordination 协调；配合 in both conquering territory and maintaining power once it was conquered. And once territories were conquered, imperializing nations got to work quickly building up infrastructure 基础设施, the most significant of which was railroads. In this way, raw materials and manufactured goods could be transported in and out and around these colonies with great speed. +

And the third advantage Europeans had was advances in medicine. Now the reason Europeans hadn't pushed into the interior of Africa prior to this was because of a disease found there called malaria 疟疾. But thanks to French scientists who discovered that quinine 奎宁 could fend off 抵御；抵抗 the disease, Europeans could invade the interior of Africa without fear of contracting 感染；患上 it. +

Additionally, thanks to the work of French chemist Louis Pasteur, Europeans finally began to understand what caused diseases. He discovered the germ theory of disease 疾病细菌理论, which said that people got sick -- or you know, amputated limbs got infected or whatever -- because of tiny microorganisms 微生物 called germs. Once you discovered this, a new revolution in hospital care emerged in which antiseptics 防腐剂；消毒剂 were used and cleanliness of surgical tools was paramount 至关重要的；至高无上的. +

I know that sounds pretty great, but in terms of imperialism, that meant that European troops could be vaccinated 接种疫苗 against diseases and thus remain healthier here on the battlefield. And if they got hurt, then they would have a much better chance of survival. +

Okay, click here to keep reviewing for AP Euro unit 7. Additionally, click here if you want note guides to follow along with these videos so you can actually learn the material I'm giving. And hey, I'll catch you on the flip-flop. I'm out. +

'''

== 中文释义

好的，欧洲历史上的新一轮帝国主义浪潮来临了。所以我认为我们应该谈谈欧洲人这么做的原因——也就是他们的动机——以及欧洲人是如何做的——也就是他们的手段。所以，如果你准备好充实自己的知识，那我们开始吧。  +

记住，当本课程所涉及的历史从1450年开始时，西欧国家开始向西穿越大西洋、向东进入印度洋，欧洲帝国主义出现了一股浪潮。在这个时期，又出现了新一轮的欧洲帝国主义浪潮，这次的重点是非洲和亚洲。  +

从定义上来说，帝国主义是指一个国家将政治统治扩展到另一个国家。那么为什么一个国家想要这么做呢？嗯，我有三个原因。哦，如果你正在为考试学习，别忘了查看我的美国大学预修课程欧洲历史复习资料包，里面有你在课堂上得A以及在五月份的考试中得5分所需要的一切。描述中有链接。  +

好的，欧洲新一轮帝国主义浪潮的第一个动机是经济方面的。记住，在这个时期，许多西欧国家正处于工业革命的鼎盛时期，因此它们变得极其富有。但是为了让工厂持续运转，国家需要两样东西：原材料和市场。  +

他们需要像棉花、橡胶和铁这样的原材料，以便制造出最终的工业制成品。一旦一个国家耗尽了自己的资源，它们就会到世界其他地方去获取这些原材料。所以这是新一轮帝国主义活动的一个重要动机。  +

但是一旦商品生产出来，他们还需要有人来购买这些制成品。当国内市场饱和时，他们就需要占领其他国家，这样就能在其他地方开辟新市场。例如，在1857年印度土兵起义（Sepoy Rebellion）后，英国政府控制了印度，他们开始剥削印度人以获取宝贵的原材料——尤其是棉花——而且由于印度有大约3亿人口，英国人现在有了3亿可以向其销售制成品（如纺织品）的对象。结果，财富源源不断地流入英国的国库。  +

从这个时期开始，英国殖民了西非的一些地方，然后又在非洲大陆东侧殖民了大片领土。英国人主要对获取像煤炭、石油和铜这样的原材料感兴趣。  +

英国也将其帝国主义目光投向了中国。但在中国，他们实行的是经济帝国主义而非政治帝国主义。事情是这样的：英国与中国的贸易基本上是不平衡的。英国人想要大量的中国茶叶，但中国对英国商品的需求却没那么大。所以当英国的钱流入中国时，却没有中国的钱流入英国。这对英国来说是个问题。  +

我本想告诉你，英国通过询问中国人想要什么样的产品来解决这个问题，然后运用创新思维生产出中国人想要的商品，从而纠正贸易不平衡。但英国人并没有这么做。相反，他们开始从印度向中国走私一种极易上瘾的毒品——鸦片。很快，中国人就对这种毒品上瘾了。而且由于印度具备种植鸦片的绝佳条件，英国人就大量非法向中国进口鸦片。  +

但如果你觉得这有点不正当，当时的中国官员也会同意你的看法。1839年，中国政府查获了大约2万磅正在被进口到中国的鸦片并销毁了它们。连同其他一些小事件，这一事件引发了中英之间的第一次鸦片战争。  +

当时，中国在适应新的工业世界方面极其迟缓，但英国却不是。记住，英国基本上是工业革命的先行者，所以他们在武器方面相对于中国有很大的优势。不用说，英国赢得了这场战争——还有第二次鸦片战争，法国也参与了——并强行打开了与中国的贸易权。  +

好的，新一轮帝国主义浪潮的第二个动机是政治方面的。我一直在谈论英国，因为可以说英国是欧洲新一轮帝国主义浪潮中的主导者，但这并不意味着其他欧洲国家没有参与其中。几个欧洲国家都在争夺非洲的领土，包括法国、荷兰和比利时。这被称为“非洲争夺战（Scramble for Africa）”。  +

这种对非洲领土的丑恶争夺在这些国家之间引发了严重的紧张局势。一旦比利时国王利奥波德（Leopold）的代理人绘制出了非洲内陆的地图，欧洲各国就竞相在其他国家之前宣称对这些领土的所有权。这将引发严重的紧张局势，我们将在下一个视频中探讨。  +

新一轮帝国主义浪潮的第三个动机是对种族优越性的信仰。回想一下，在几个视频之前我们谈到了新兴的种族主义哲学——社会达尔文主义（social Darwinism）。到19世纪后期，这种意识形态已经深深扎根，为那些拥有先进文明的强国——至少他们是这样自我标榜的——征服拥有原始文明的弱国提供了动机。  +

比如，当你将欧洲工业化国家积累的财富和权力与非洲一些地方的相对贫困进行对比时，一个社会达尔文主义者会得出这样的结论：显然西方国家更优越。西方国家更好地适应了他们的环境，因此不仅生存了下来，而且繁荣发展。所以，如果按照自然法则强者吃掉弱者，那么强国为什么不能征服弱国呢？  +

但是如果你直接问这些欧洲人他们的行为在道德上是否错误，是的，他们会嘲笑你。当然没错。其中一个主要原因是他们真的认为他们正在把西方文明的荣耀带给那些迫切需要的人。法语中称其为“文明使命（mission civilisatrice）”，意思就是传播文明的使命。换句话说，按照欧洲人的说法，帝国主义对殖民地人民是有益的，因为他们能够接触到世界上最优秀的文化。  +

欧洲种族优越性信仰最明显的体现可能是鲁德亚德·吉卜林（Rudyard Kipling）的一首名为《白人的负担（White Man's Burden）》的诗。诗中谈到了非洲人民，称他们“半是魔鬼，半是孩童”。因此，白人应该“派出你们最优秀的人”来“满足被征服人民的需求”。所以如果帝国主义国家坚持这种信仰，那么对另一个弱国实行帝国主义统治就不是恶行，而是怀着仁慈之心将西方文化的荣耀带给他们。  +

我可能不需要告诉你，非洲人和亚洲人并不像欧洲人那样对西方文化的荣耀感到兴奋。事实上，在很多情况下，他们对欧洲人入侵他们的家园进行了顽强的抵抗。但不幸的是，欧洲人有几个优势，使他们在对抗那些抵抗者时占据上风。  +

欧洲人的第一个优势是先进的武器。我再怎么强调工业革命对这一优势的贡献都不为过。枪支进行了更新，采用了膛线，也就是说在枪管内部切割出螺旋形的凹槽，这提高了射击的准确性。此外，米尼弹（Minié ball）被发明出来，这是一种锥形子弹，比传统的滑膛枪子弹更准确，造成的伤害也更大。  +

另外，欧洲人制造了后装步枪，这种步枪装弹速度更快，而且他们掌握了机枪技术，机枪能够快速发射数百发子弹。重点是，欧洲人的武器能够比任何抵抗者更快地向反对他们的人发射子弹。  +

欧洲人的第二个优势是新的通信和交通技术。电报的速度以及在水下铺设长电缆的能力增强了通信。这使得在征服领土以及在征服后维持统治方面的协调更加有效。一旦领土被征服，帝国主义国家就迅速开展工作，建设基础设施，其中最重要的是铁路。通过这种方式，原材料和制成品能够快速运进运出这些殖民地。  +

欧洲人的第三个优势是医学方面的进步。在此之前，欧洲人没有深入非洲内陆的原因是那里有一种疾病——疟疾。但多亏了法国科学家发现奎宁可以抵御这种疾病，欧洲人可以毫无顾忌地入侵非洲内陆。  +

此外，多亏了法国化学家路易斯·巴斯德（Louis Pasteur）的工作，欧洲人终于开始了解疾病的成因。他发现了疾病的细菌理论，即人们生病——或者比如说，截肢的肢体受到感染等等——是因为一种叫做细菌的微小微生物。一旦发现了这一点，医院护理领域出现了一场新的革命，开始使用防腐剂，并且外科手术工具的清洁变得至关重要。  +

我知道这听起来相当不错，但就帝国主义而言，这意味着欧洲军队可以接种疫苗预防疾病，从而在战场上保持更健康的状态。而且如果他们受伤了，存活的机会也会大得多。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第七单元。另外，如果你想要与这些视频配套的笔记指南，点击这里，这样你就能真正学到我所讲的内容。好了，我们下次再见。我走了。  +

'''

== pure

All right, it's time for a new wave of imperialism in European history. So I reckon we ought to talk about why the Europeans did it -- which is to say their motivations -- and how the Europeans did it -- which is to say their methods. So if you're ready to get them brain cows milked, let's get to it.

So remember that when this course began in 1450, there was a surge in European imperialism as Western European states began sailing west across the Atlantic and east into the Indian Ocean. And in this period, there is a new wave of European imperialism, and it's going to focus on Africa and Asia.

Now by definition, imperialism is when one country extends political dominance over another country. And why would another country want to do that? Well, I got three reasons for it. Oh, and if you're studying for an exam, don't forget to check out my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May. Link in description.

Okay, the first motivation for the second wave of European imperialism was economic. Now remember, many of the states in Western Europe were in the heyday of the Industrial Revolution during this period, and they were getting fabulously wealthy as a result. But in order to keep those factories working, states needed two things: raw materials and markets.

They needed raw materials like cotton and rubber and iron in order to make the final manufactured goods coming out of the factory. Once a nation had tapped all their own resources, they went looking in other places of the world to get those raw materials. So there was a significant motivation there for the new imperial events.

But once the goods were finished, they also needed people to buy those manufactured goods. And when the markets at home became saturated, they needed to go take over other countries so they could open those new markets in other places. For example, once the British government took control over India after the Sepoy Rebellion in 1857, they began to exploit the Indians to gain valuable raw materials -- not least cotton -- but also since there was something like 300 million people living in India, the British now had 300 million people to whom they could sell those manufactured textiles. And the wealth came pouring into the British coffers as a result.

Starting in this period, the British colonized a few places in West Africa, and then a huge swath of territory right down the eastern side of the entire continent in Africa. The British were mainly interested in gaining access to raw materials like coal and oil and copper.

The British also turned their imperialistic gaze upon China. But in China, they engaged in economic imperialism rather than political imperialism. And the story went a little something like this: the British trade with the Chinese was fundamentally out of balance. The Brits wanted Chinese tea by the metric ton, but there wasn't as much the Chinese wanted from the British. So as British money is flowing into China, there is no Chinese money flowing into Britain. And that's going to be a problem for the British.

Now I'd like to tell you that the British addressed this issue by asking the Chinese what kinds of products they wanted, and then used innovative thinking to create goods that the Chinese wanted, and the trade imbalance was corrected. But that's not what the British did. Instead, they began smuggling the highly addictive drug called opium into China from India. And it didn't take long for the Chinese to get hooked on this drug. And because India had prime growing conditions for opium, the British illegally imported it into China by the metric ton.

But if that sounds a little underhanded to you, well then the Chinese officials of that time would agree with you. In 1839, the Chinese government seized like 20,000 pounds of opium being imported into China and destroyed it. And along with a couple other smaller incidents, this event led to the first Opium War between Britain and China.

Now China had been exceedingly sluggish when it came to adapting to the new industrial world, but not Britain. Remember, Britain was essentially the first mover in the Industrial Revolution, and so they had a much greater advantage in weaponry against the Chinese. Needless to say, the British won this war -- and the second Opium War, which also included France -- and forcibly opened trading rights into China.

Okay, now the second motivation for the second wave of imperialism was political. Now I've been talking a lot about Britain because they were arguably the big dog of the second wave of European imperialism, but that doesn't mean that other European states didn't get in on the party too. Several European nations were clamoring for territory in Africa, including the French and the Dutch and the Belgians. And this became known as the Scramble for Africa.

This dirty clamoring for African territory began to cause significant tension among these states. Once the interior of Africa was mapped by agents of Belgian King Leopold, European states raced to claim territories before other states got to them. And that would cause significant tension that we're going to consider in the next video.

And the third motivation for the second wave of imperialism was a belief in racial superiority. Recall a couple videos ago when we talked about the budding racialist philosophy called social Darwinism. By the late 19th century, that ideology had taken full root and provided the motivation for strong nations with advanced civilizations -- that you know, at least that's how they sell themselves -- to take over weak nations with primitive civilizations.

Like when you contrasted the wealth and power that industrialized nations in Europe had accumulated with the relative poverty of places in Africa, a social Darwinist would conclude that clearly Western nations were superior. Western nations have adapted better to their environment and thus are not only surviving but thriving. Therefore, if the strong eat the weak by the laws of nature, why shouldn't the strong nations eat the weak nations?

But if you would ask these Europeans directly if what they were doing was morally wrong, yeah, they would have laughed. Of course it's not wrong. And one of the main reasons is because they truly believe they were bringing the glories of Western civilization to bear on people who desperately needed it. The French term for this was the mission civilisatrice, which when being translated means the civilizing mission. In other words, by European reckoning, imperialism was good for the colonized because they got access to the best culture the world had to offer.

And probably the clearest manifestation of the beliefs of European racial superiority is a poem by Rudyard Kipling called "White Man's Burden." It talks about the peoples of Africa and calls them "half devil and half child." Therefore, the white man ought to "send the best ye breed" in order to "serve your captives' need." And so if this was the belief imperial nations clung to, then it was not an evil to imperialize another weaker nation, but rather benevolent in mercy to bring them the glories of Western culture.

Now I probably don't need to tell you that Africans and Asians were not as jazzed about the glories of Western culture as the Europeans were. In fact, in many cases, they put up stiff resistance against European intrusion into their homeland. But unfortunately, Europeans had several advantages that gave them the upper hand against those who resisted.

The first advantage Europeans had was advanced weapons. And I cannot emphasize enough just how much the Industrial Revolution contributed to this advantage. Guns were updated to include a rifled barrel, which means there were spiral grooves cut along the inside of them, which increased the accuracy of the shot. Additionally, the Minié ball was invented, which was a conical bullet which was more accurate and did way more damage than the traditional musket.

Additional Europeans manufactured the breech-loading rifle in which bullets could be loaded much quicker, and they had access to machine gun technology which could fire hundreds of rounds at great speed. The point is, Europeans had weapons that could deliver lead into the bodies of those who opposed them much quicker than anyone who resisted.

The second advantage Europeans had was new communication and transportation technology. Communication was enhanced by the speed of the telegraph and the ability to run cables under the water and at great length. This enabled coordination in both conquering territory and maintaining power once it was conquered. And once territories were conquered, imperializing nations got to work quickly building up infrastructure, the most significant of which was railroads. In this way, raw materials and manufactured goods could be transported in and out and around these colonies with great speed.

And the third advantage Europeans had was advances in medicine. Now the reason Europeans hadn't pushed into the interior of Africa prior to this was because of a disease found there called malaria. But thanks to French scientists who discovered that quinine could fend off the disease, Europeans could invade the interior of Africa without fear of contracting it.

Additionally, thanks to the work of French chemist Louis Pasteur, Europeans finally began to understand what caused diseases. He discovered the germ theory of disease, which said that people got sick -- or you know, amputated limbs got infected or whatever -- because of tiny microorganisms called germs. Once you discovered this, a new revolution in hospital care emerged in which antiseptics were used and cleanliness of surgical tools was paramount.

I know that sounds pretty great, but in terms of imperialism, that meant that European troops could be vaccinated against diseases and thus remain healthier here on the battlefield. And if they got hurt, then they would have a much better chance of survival.

Okay, click here to keep reviewing for AP Euro unit 7. Additionally, click here if you want note guides to follow along with these videos so you can actually learn the material I'm giving. And hey, I'll catch you on the flip-flop. I'm out.

'''