
= 8.2 World War I
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

So my question is, how did a small regional conflict in the Balkan States blow up into the biggest, most devastating 毁灭性的 war the world had ever seen? That war was World War One, and this video is all about it. So if you're ready to get them brain cows milked Total War style, then let's get to it. +

Let's begin with the causes of World War One, and there are four long-term causes you need to know and one short-term cause. By the way, if you want all of Unit 8 in a single review video along with note guides and practice questions, then check out my AP Euro review pack and all your dreams will come true. Link in description. +

Anyway, the first long-term cause you need to know is the rise of militarism 军国主义. Now militarism, by definition, is the idea that states desire to increase their military capacity 军事能力 in order to defend and pursue their national interests. Now there are of course other ways to defend and pursue your national interest -- like, you know, diplomacy 外交手段, which means coming to an agreement through negotiation 谈判 using your mouth hole. But because of the terrific explosion in states' capacity to make weapons thanks to the Industrial Revolution, solving problems through diplomacy seemed less and less attractive. +

In fact, during the Second Industrial Revolution, the major powers of Europe nearly doubled their spending on their military. And in the same way you'd want to drive a new car if you spend a bunch of money on it, if you spend a bunch of money on your military, you kind of want to go blow things up. +

Okay, now the second long-term cause of the war was the growth of antagonistic 敌对的 alliances 联盟. Remember how we talked in Unit 7 about Otto von Bismarck of Germany and how his leadership led to an increasing antagonism 对抗；敌对 between Germany on one side and Britain and France on the other? Well, those antagonistic alliances are going to bloom fully in the years leading up to World War One. +

Bismarck led the creation of the Triple Alliance 三国同盟 between Germany, Austria-Hungary, and Italy. And in response, Britain, Russia, and France created the Triple Entente 三国协约. Each set of nations stood apart from each other with their giant militaries built up and said, "Rock, come at me. Oh, I wish you would." +

Okay, and the third long-term cause was imperialism 帝国主义. Remember in the last unit we talked about the Scramble for Africa 非洲争夺战 and all the imperial competition in Asia at the hands of European powers. This competition led to increasing strain 紧张局势 among European powers. For example, we talked about the Moroccan Crisis in Africa, which nearly led to war between Germany and Britain and France because each side wanted power over that territory. +

And then the fourth long-term cause for World War One was nationalism 民族主义. The solidifying 巩固 of nationalism as a binding force for the modern nation-state led to tensions. Also in that day, most military leaders of European states believed that war was an acceptable means of vindicating 维护；证明……有理 their national honor and keeping their interests safe. For example, as a result of the Franco-Prussian War 普法战争 from the last period, Germany secured two French territories -- Alsace and Lorraine -- and French leaders had no qualms 疑虑；不安 about potentially using military aggression 军事侵略 to restore to France what rightly belonged to them. Like, it was a matter of national honor. +

And so, gripped by nationalist visions, each of these great powers of Europe saw their own people and their own culture and their own nation as superior to others. And that is a recipe for disaster. +

Okay, and now let's talk about the short-term or immediate cause of the war. And by all accounts, it should not have led to a war as cataclysmic 灾难性的 as World War One, but it did. So, you know, let's talk about it. The immediate cause of the war was the assassination 暗杀 of the Austrian Archduke Franz Ferdinand in 1914. He and his wife were on a parade through the streets of Sarajevo, which was the capital of Bosnia. +

Now follow me here. Bosnia had been annexed 吞并 by Austria-Hungary a few years earlier. So you've got Bosnians living under the rule of Austria-Hungary. And what have we seen over and over again when that happens? Nationalism sprouts up among the conquered peoples, and they desire to be free and to have a nation of their own. So that is what's going on here. +

So on the day of the parade, a Bosnian-Serbian nationalist named Gavrilo Princip shot and killed the Archduke. Now to be clear, Princip lived in Bosnia, but he was a Serb. The Serbian government, as far as we know, had precisely 恰好；正是 nothing to do with the assassination. So really what we have here is a conflict between Serbia and Austria-Hungary, and that's it. +

The truth is, assassinations like these had happened in the recent past, and in those cases, those involved managed to keep the conflict local. But when an assassination like this occurs in the context of those long-term causes I just mentioned, then you've got a different scenario 情况；局面 altogether. +

So Austria-Hungary, seeing an opportunity to weaken Serbian influence in the Balkans, revved up 加速；加快 that sweet military that they've been building up and decided to intervene 干预；干涉. They called on their ally Germany to assist them, and Germany was like, "Uh, sure." So Austria-Hungary declares war on Serbia. And that was entirely unpalatable 令人不快的；难以接受的 to the Russians. They had suffered some humiliating 丢脸的；屈辱的 defeats in the previous Balkan crises, and so they rushed to Serbia's aid. And so Germany declares war on Russia, and the rest of the alliance system lights up with activity. And that's how you get a World War. +

Now once the fighting began, it became clear that this was an entirely new kind of war that confounded 使困惑；使糊涂 traditional military strategies 军事战略. And much of this newness came from the munitions 军火；军需品 technologies that were freshly minted 新出现的. First of all, let me tell you about the machine gun 机枪 and barbed wire 铁丝网. But in order to understand why those were so devastating 毁灭性的, you need to understand the main method of fighting this war, namely trench warfare 堑壕战. +

Now armies had hunkered down 蹲伏；隐蔽 in trenches in many wars prior to this, so it wasn't really new. But when you combine the trenches with machine guns and barbed wire, things get nasty. So each side would dig their trenches opposite to each other and then line the land in front of them with barbed wire and then station 部署；驻扎 machine guns across the top, which were capable of delivering hundreds of rounds of ammunition 弹药 at great speed. +

So when one side got tired of waiting, they'd charge up out of their trench, get caught in the barbed wire, where they would be summarily 迅速地；立即地 mowed down 扫射；扫倒 by machine gun fire. That lasted until they retreated. And then the other side got tired of waiting, and then they'd charge out, and the same thing would happen. +

Additionally, Germans introduced chemical weapons 化学武器 like chlorine gas 氯气 that, without the protection of a gas mask 防毒面具, would blind and choke 使窒息 those that came into contact with it. Also, Germans developed submarines 潜艇, which were able to attack ships from underneath the surface of the water. Also, airplanes were used in battle for the first time, and although bombing techniques 轰炸技术 wouldn't be perfected until the Second World War, airplanes were still formidable 强大的；可怕的 in their own right. +

So the point is, take all these new technologies together, and you had the deadliest war that had ever been fought. The casualties 伤亡人员 were staggering 惊人的. +

Okay, now World War One was what's called a total war 总体战, which means that all of the state's resources -- both at home and on the battlefield -- were used to fight. That means that textile factories were converted into munitions factories, and people had to ration 定量供应；配给 food in order to make sure the troops were fed, and on and on and on. And since the people at home were sacrificing for what seemed to be an unwinnable war with devastating casualties, discontent 不满；不满情绪 began growing, and that led to protest 抗议 and insurrection 起义；暴动 at home. +

One insurrection was the Russian Revolution, but that's going to get its own video. So let's focus here on the Easter Rebellion in Ireland. The Irish had long sought to be free of British rule. One manifestation 表现；显示 of that was the Home Rule movement 地方自治运动. Just prior to the outbreak of the war, the British Parliament had passed a Home Rule bill that would have granted Ireland their independence, but they put that on hold while the war was being waged. +

Even so, Irish soldiers enlisted 应征入伍 by the tens of thousands to fight with the British during the war. However, the heavy casualties of the Irish and the growing frustration at home convinced them that the British had no intention of actually following through with the Home Rule bill. As a result, on Easter Sunday 1916, Irish rebels took to fighting the British in the streets of Dublin. Now it wasn't long before the British were able to subdue 镇压；征服 them, but it demonstrates how the stalemates 僵局 and the casualties abroad were causing tensions at home. +

Now there were essentially two reasons why this was called a World War. First, because of the massive efforts of imperial expansion in the last period, imperial powers called up colonial soldiers to fight for them. For example, Indian troops fought for the British, and North African troops fought for the French. But the second reason this was a World War is because the theaters of war 战区；战场 spilled beyond the borders of Europe. +

First example is the Armenian genocide 亚美尼亚种族大屠杀, in which the Ottoman officials encouraged the slaughter 屠杀；杀戮 of Armenian Christian minorities living within their borders. Second, all the way across the globe, Japan got in the action by declaring war on Germany, then systematically 系统地 seized German colonial possessions 殖民地 in China and the South Pacific. +

Okay, now in 1917, the United States entered the war because of the unrelenting 持续的；不懈的 aggression of German submarines and a few other factors. And though the United States troops initially saw little action, their entry on the side of the Triple Entente was a significant factor in turning the tide of the war in their favor. And ultimately, it was the Triple Entente that won the war. +

And all that was settled in 18 in the Treaty of Versailles 凡尔赛和约. And the end of this war significantly altered 改变；变更 the global balance of power 全球权力平衡. First of all, the United States emerged far more wealthy and far more powerful than it had been before the war, and so they became a true global power. Second, old European empires were disbanded 解散；解体 after the war, which is to say the Austro-Hungarian Empire and the Ottoman Empire were dissolved 解散；瓦解. Germany was severely punished in the Treaty of Versailles and thus lost its vaunted 自夸的；吹嘘的 position as a major European power. And then under the mandate system 委任统治制度, the victorious powers took control of Germany's colonial possessions. +

And all of this unbalancing and the punishment of Germany is going to lead us squarely into World War II, but we're going to save that for another video. +

Okay, click here to keep reviewing for Unit 8 of AP Euro. Click here to grab my AP Euro review pack, which does everything you need to get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. Heimler out. +

'''

== 中文释义

那么我的问题是，巴尔干国家的一场小规模地区冲突是如何演变成一场世界前所未见的、规模最大且最具破坏性的战争呢？这场战争就是第一次世界大战（World War One），而这个视频讲的就是它。所以，如果你准备好以“全面战争”的风格充实自己的知识，那就开始吧。  +

让我们从第一次世界大战的起因说起，有四个长期原因和一个短期原因是你需要了解的。顺便说一下，如果你想在一个复习视频中了解第八单元的所有内容，以及笔记指南和练习题，那就查看我的美国大学预修课程欧洲历史复习资料包吧，你所有的愿望都会实现的。描述中有链接。  +

不管怎样，第一个长期原因是军国主义的兴起。从定义上来说，军国主义是指国家渴望增强其军事能力，以捍卫和追求国家利益。当然，还有其他捍卫和追求国家利益的方式，比如外交，也就是通过谈判达成协议。但由于工业革命，国家制造武器的能力大幅提升，通过外交解决问题的吸引力越来越小。  +

事实上，在第二次工业革命期间，欧洲列强在军事上的支出几乎翻倍。就像你花了一大笔钱买了一辆新车后就想开车一样，如果你在军事上投入了大量资金，你就有点想发动战争。  +

好的，这场战争的第二个长期原因是敌对联盟的发展。还记得我们在第七单元谈到德国的奥托·冯·俾斯麦（Otto von Bismarck），以及他的领导是如何导致德国与英国、法国之间的对抗日益加剧的吗？嗯，这些敌对联盟在第一次世界大战爆发前的几年里全面形成。  +

俾斯麦主导建立了德国、奥匈帝国（Austria-Hungary）和意大利之间的三国同盟（Triple Alliance）。作为回应，英国、俄罗斯和法国建立了三国协约（Triple Entente）。每一组国家都建立了强大的军事力量，彼此对立，仿佛在说：“放马过来吧。哦，真希望你敢来。”  +

好的，第一次世界大战的第三个长期原因是帝国主义。还记得上一单元我们谈到的对非洲的争夺（Scramble for Africa），以及欧洲列强在亚洲的所有帝国主义竞争吗？这种竞争导致欧洲列强之间的紧张关系日益加剧。例如，我们谈到了非洲的摩洛哥危机（Moroccan Crisis），这场危机几乎导致德国与英国、法国之间爆发战争，因为各方都想控制那个地区。  +

第一次世界大战的第四个长期原因是民族主义。民族主义作为一种凝聚现代民族国家的力量得以巩固，这引发了紧张局势。而且在那个时期，欧洲各国的大多数军事领导人认为，战争是维护国家荣誉和保障国家利益的可接受手段。例如，由于上一时期的普法战争（Franco-Prussian War），德国获得了法国的两个地区——阿尔萨斯（Alsace）和洛林（Lorraine），而法国领导人毫不犹豫地认为可以通过军事侵略来夺回原本属于法国的东西。这关乎国家荣誉。  +

所以，在民族主义观念的影响下，欧洲的这些列强都认为自己的人民、自己的文化和自己的国家比其他国家优越。这简直就是灾难的根源。  +

好的，现在让我们谈谈这场战争的短期原因，也就是直接原因。从各方面来看，这个原因本不应该导致像第一次世界大战这样的大灾难，但它确实导致了。所以，让我们来谈谈。这场战争的直接原因是1914年奥匈帝国大公弗朗茨·斐迪南（Austrian Archduke Franz Ferdinand）遇刺。他和他的妻子当时正在波斯尼亚（Bosnia）首都萨拉热窝（Sarajevo）的街道上参加游行。  +

接着听我说。波斯尼亚几年前被奥匈帝国吞并。所以有波斯尼亚人生活在奥匈帝国的统治之下。当这种情况发生时，我们一次又一次地看到了什么呢？被征服的人民中兴起了民族主义，他们渴望自由，渴望拥有自己的国家。这就是当时的情况。  +

所以在游行那天，一个名叫加夫里洛·普林西普（Gavrilo Princip）的波斯尼亚-塞尔维亚民族主义者开枪打死了大公。需要明确的是，普林西普生活在波斯尼亚，但他是塞尔维亚人。据我们所知，塞尔维亚政府与这次暗杀毫无关系。所以实际上，这是塞尔维亚和奥匈帝国之间的冲突，就是这样。  +

事实上，类似这样的暗杀在近期也发生过，在那些情况下，相关各方都设法将冲突控制在局部范围内。但当这样的暗杀发生在我刚才提到的那些长期原因的背景下时，情况就完全不同了。  +

所以奥匈帝国认为这是削弱塞尔维亚在巴尔干半岛影响力的机会，于是动用了他们一直建立起来的强大军事力量，决定进行干预。他们呼吁盟友德国帮忙，德国说：“嗯，当然可以。” 于是奥匈帝国向塞尔维亚宣战。而俄罗斯对此完全无法接受。他们在前几次巴尔干危机中遭受了屈辱性的失败，所以他们急忙去援助塞尔维亚。接着德国向俄罗斯宣战，联盟体系的其他部分也活跃起来。这就是第一次世界大战爆发的过程。  +

战争一旦爆发，很明显这是一场全新的战争，传统的军事战略在这场战争中完全行不通。这种“新”在很大程度上来自于新出现的弹药技术。首先，让我给你讲讲机关枪和铁丝网。但为了理解它们的破坏力，你需要了解这场战争的主要作战方式，也就是堑壕战（trench warfare）。  +

在这场战争之前的许多战争中，军队就已经在战壕中坚守阵地了，所以这并不是什么新鲜事。但当你把战壕、机关枪和铁丝网结合起来时，情况就变得很糟糕。所以双方会在彼此对面挖掘战壕，然后在战壕前方铺设铁丝网，并在战壕上方部署机关枪，机关枪能够快速发射数百发弹药。  +

所以当一方等得不耐烦时，他们会从战壕中冲出来，却被铁丝网困住，然后被机关枪火力扫射。这种情况会持续到他们撤退。然后另一方等得不耐烦了，他们冲出来，同样的事情又会发生。  +

此外，德国人引入了像氯气这样的化学武器，如果没有防毒面具的保护，接触到氯气的人会失明并窒息。而且，德国人还研发了潜艇，潜艇能够从水下攻击船只。同时，飞机首次被用于战斗，虽然轰炸技术在第二次世界大战时才得以完善，但飞机本身就已经很厉害了。  +

所以重点是，把所有这些新技术结合起来，就造就了有史以来最致命的战争。伤亡人数惊人。  +

好的，第一次世界大战是一场所谓的全面战争（total war），这意味着国家的所有资源，无论是国内的还是战场上的，都被用于战争。这意味着纺织厂被改造成了军工厂，人们必须实行食物配给，以确保军队有食物供应，诸如此类。而且由于国内的人们为了一场看似无法获胜且伤亡惨重的战争做出了牺牲，不满情绪开始增长，这导致了国内的抗议和起义。  +

其中一场起义是俄国革命（Russian Revolution），不过这将在另一个视频中单独讲述。所以让我们把重点放在爱尔兰的复活节起义（Easter Rebellion）上。爱尔兰人长期以来一直寻求摆脱英国的统治。其中一个表现就是自治运动（Home Rule movement）。在战争爆发前，英国议会通过了一项自治法案，该法案本应给予爱尔兰独立，但在战争期间，这项法案被搁置了。  +

即便如此，成千上万的爱尔兰士兵在战争期间应征入伍，为英国作战。然而，爱尔兰的惨重伤亡以及国内日益增长的挫败感让他们相信，英国实际上无意履行自治法案。结果，在1916年的复活节星期天，爱尔兰叛军在都柏林（Dublin）的街道上与英国作战。没过多久，英国就镇压了他们，但这表明了国外的僵局和伤亡是如何在国内引发紧张局势的。  +

实际上，这场战争被称为世界大战有两个原因。首先，由于上一时期大规模的帝国扩张，帝国主义列强征召殖民地士兵为他们作战。例如，印度军队为英国作战，北非军队为法国作战。其次，这场战争被称为世界大战是因为战争的战场超出了欧洲的边界。  +

第一个例子是亚美尼亚大屠杀（Armenian genocide），在这场屠杀中，奥斯曼帝国官员鼓励屠杀生活在其境内的亚美尼亚基督教少数群体。其次，在全球范围内，日本也参与其中，日本向德国宣战，然后有计划地夺取了德国在中国和南太平洋的殖民地。  +

好的，1917年，由于德国潜艇的持续侵略以及其他一些因素，美国加入了战争。虽然美国军队最初几乎没有参与战斗，但他们加入三国协约一方成为了扭转战局的重要因素。最终，三国协约赢得了战争。  +

所有这些问题在1918年的《凡尔赛条约》（Treaty of Versailles）中得到了解决。这场战争的结束极大地改变了全球的权力平衡。首先，美国变得比战前更加富有和强大，成为了一个真正的全球大国。其次，老牌欧洲帝国在战后解体，也就是说奥匈帝国和奥斯曼帝国瓦解了。德国在《凡尔赛条约》中受到了严厉惩罚，因此失去了其作为欧洲主要大国的显赫地位。然后在委任统治制度下，战胜国控制了德国的殖民地。  +

所有这些权力失衡以及对德国的惩罚将我们直接引向了第二次世界大战（World War II），但我们会在另一个视频中讲述这个内容。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第八单元。点击这里获取我的美国大学预修课程欧洲历史复习资料包，它能满足你在课堂上得A以及在五月份的考试中得5分的所有需求。我们下次再见。海姆勒下线。  +

'''

== pure
So my question is, how did a small regional conflict in the Balkan States blow up into the biggest, most devastating war the world had ever seen? That war was World War One, and this video is all about it. So if you're ready to get them brain cows milked Total War style, then let's get to it.

Let's begin with the causes of World War One, and there are four long-term causes you need to know and one short-term cause. By the way, if you want all of Unit 8 in a single review video along with note guides and practice questions, then check out my AP Euro review pack and all your dreams will come true. Link in description.

Anyway, the first long-term cause you need to know is the rise of militarism. Now militarism, by definition, is the idea that states desire to increase their military capacity in order to defend and pursue their national interests. Now there are of course other ways to defend and pursue your national interest -- like, you know, diplomacy, which means coming to an agreement through negotiation using your mouth hole. But because of the terrific explosion in states' capacity to make weapons thanks to the Industrial Revolution, solving problems through diplomacy seemed less and less attractive.

In fact, during the Second Industrial Revolution, the major powers of Europe nearly doubled their spending on their military. And in the same way you'd want to drive a new car if you spend a bunch of money on it, if you spend a bunch of money on your military, you kind of want to go blow things up.

Okay, now the second long-term cause of the war was the growth of antagonistic alliances. Remember how we talked in Unit 7 about Otto von Bismarck of Germany and how his leadership led to an increasing antagonism between Germany on one side and Britain and France on the other? Well, those antagonistic alliances are going to bloom fully in the years leading up to World War One.

Bismarck led the creation of the Triple Alliance between Germany, Austria-Hungary, and Italy. And in response, Britain, Russia, and France created the Triple Entente. Each set of nations stood apart from each other with their giant militaries built up and said, "Rock, come at me. Oh, I wish you would."

Okay, and the third long-term cause was imperialism. Remember in the last unit we talked about the Scramble for Africa and all the imperial competition in Asia at the hands of European powers. This competition led to increasing strain among European powers. For example, we talked about the Moroccan Crisis in Africa, which nearly led to war between Germany and Britain and France because each side wanted power over that territory.

And then the fourth long-term cause for World War One was nationalism. The solidifying of nationalism as a binding force for the modern nation-state led to tensions. Also in that day, most military leaders of European states believed that war was an acceptable means of vindicating their national honor and keeping their interests safe. For example, as a result of the Franco-Prussian War from the last period, Germany secured two French territories -- Alsace and Lorraine -- and French leaders had no qualms about potentially using military aggression to restore to France what rightly belonged to them. Like, it was a matter of national honor.

And so, gripped by nationalist visions, each of these great powers of Europe saw their own people and their own culture and their own nation as superior to others. And that is a recipe for disaster.

Okay, and now let's talk about the short-term or immediate cause of the war. And by all accounts, it should not have led to a war as cataclysmic as World War One, but it did. So, you know, let's talk about it. The immediate cause of the war was the assassination of the Austrian Archduke Franz Ferdinand in 1914. He and his wife were on a parade through the streets of Sarajevo, which was the capital of Bosnia.

Now follow me here. Bosnia had been annexed by Austria-Hungary a few years earlier. So you've got Bosnians living under the rule of Austria-Hungary. And what have we seen over and over again when that happens? Nationalism sprouts up among the conquered peoples, and they desire to be free and to have a nation of their own. So that is what's going on here.

So on the day of the parade, a Bosnian-Serbian nationalist named Gavrilo Princip shot and killed the Archduke. Now to be clear, Princip lived in Bosnia, but he was a Serb. The Serbian government, as far as we know, had precisely nothing to do with the assassination. So really what we have here is a conflict between Serbia and Austria-Hungary, and that's it.

The truth is, assassinations like these had happened in the recent past, and in those cases, those involved managed to keep the conflict local. But when an assassination like this occurs in the context of those long-term causes I just mentioned, then you've got a different scenario altogether.

So Austria-Hungary, seeing an opportunity to weaken Serbian influence in the Balkans, revved up that sweet military that they've been building up and decided to intervene. They called on their ally Germany to assist them, and Germany was like, "Uh, sure." So Austria-Hungary declares war on Serbia. And that was entirely unpalatable to the Russians. They had suffered some humiliating defeats in the previous Balkan crises, and so they rushed to Serbia's aid. And so Germany declares war on Russia, and the rest of the alliance system lights up with activity. And that's how you get a World War.

Now once the fighting began, it became clear that this was an entirely new kind of war that confounded traditional military strategies. And much of this newness came from the munitions technologies that were freshly minted. First of all, let me tell you about the machine gun and barbed wire. But in order to understand why those were so devastating, you need to understand the main method of fighting this war, namely trench warfare.

Now armies had hunkered down in trenches in many wars prior to this, so it wasn't really new. But when you combine the trenches with machine guns and barbed wire, things get nasty. So each side would dig their trenches opposite to each other and then line the land in front of them with barbed wire and then station machine guns across the top, which were capable of delivering hundreds of rounds of ammunition at great speed.

So when one side got tired of waiting, they'd charge up out of their trench, get caught in the barbed wire, where they would be summarily mowed down by machine gun fire. That lasted until they retreated. And then the other side got tired of waiting, and then they'd charge out, and the same thing would happen.

Additionally, Germans introduced chemical weapons like chlorine gas that, without the protection of a gas mask, would blind and choke those that came into contact with it. Also, Germans developed submarines, which were able to attack ships from underneath the surface of the water. Also, airplanes were used in battle for the first time, and although bombing techniques wouldn't be perfected until the Second World War, airplanes were still formidable in their own right.

So the point is, take all these new technologies together, and you had the deadliest war that had ever been fought. The casualties were staggering.

Okay, now World War One was what's called a total war, which means that all of the state's resources -- both at home and on the battlefield -- were used to fight. That means that textile factories were converted into munitions factories, and people had to ration food in order to make sure the troops were fed, and on and on and on. And since the people at home were sacrificing for what seemed to be an unwinnable war with devastating casualties, discontent began growing, and that led to protest and insurrection at home.

One insurrection was the Russian Revolution, but that's going to get its own video. So let's focus here on the Easter Rebellion in Ireland. The Irish had long sought to be free of British rule. One manifestation of that was the Home Rule movement. Just prior to the outbreak of the war, the British Parliament had passed a Home Rule bill that would have granted Ireland their independence, but they put that on hold while the war was being waged.

Even so, Irish soldiers enlisted by the tens of thousands to fight with the British during the war. However, the heavy casualties of the Irish and the growing frustration at home convinced them that the British had no intention of actually following through with the Home Rule bill. As a result, on Easter Sunday 1916, Irish rebels took to fighting the British in the streets of Dublin. Now it wasn't long before the British were able to subdue them, but it demonstrates how the stalemates and the casualties abroad were causing tensions at home.

Now there were essentially two reasons why this was called a World War. First, because of the massive efforts of imperial expansion in the last period, imperial powers called up colonial soldiers to fight for them. For example, Indian troops fought for the British, and North African troops fought for the French. But the second reason this was a World War is because the theaters of war spilled beyond the borders of Europe.

First example is the Armenian genocide, in which the Ottoman officials encouraged the slaughter of Armenian Christian minorities living within their borders. Second, all the way across the globe, Japan got in the action by declaring war on Germany, then systematically seizing German colonial possessions in China and the South Pacific.

Okay, now in 1917, the United States entered the war because of the unrelenting aggression of German submarines and a few other factors. And though the United States troops initially saw little action, their entry on the side of the Triple Entente was a significant factor in turning the tide of the war in their favor. And ultimately, it was the Triple Entente that won the war.

And all that was settled in 1918 in the Treaty of Versailles. And the end of this war significantly altered the global balance of power. First of all, the United States emerged far more wealthy and far more powerful than it had been before the war, and so they became a true global power. Second, old European empires were disbanded after the war, which is to say the Austro-Hungarian Empire and the Ottoman Empire were dissolved. Germany was severely punished in the Treaty of Versailles and thus lost its vaunted position as a major European power. And then under the mandate system, the victorious powers took control of Germany's colonial possessions.

And all of this unbalancing and the punishment of Germany is going to lead us squarely into World War II, but we're going to save that for another video.

Okay, click here to keep reviewing for Unit 8 of AP Euro. Click here to grab my AP Euro review pack, which does everything you need to get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. Heimler out.

'''