
= 9.7 The FALL of the SOVIET UNION
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

So by now you know that the Cold War was a long-standing 长期存在的 tension in the 20th century between the United States and the Soviet Union. But starting in the 1980s, seemingly out of nowhere, the Soviet Union just flat tumbled down the stairs, crashed into the landing, and then just collapsed and died. So how in the fresh heck did that happen? Well, that's what this video is all about. So if you're ready to get them brain cows milked, let's get to it. +

So in 1964, a guy named Leonid Brezhnev 列昂尼德·勃列日涅夫 rose to power in the Soviet Union, and Brezhnev was a status quo 现状 kind of guy. By his reckoning 据他估计, the Soviet Union was just fine. But in the late 60s and into the 70s, economic realities began to contradict that estimation. The Soviet people had been told over and over again that the communist utopia 共产主义乌托邦 was just around the corner -- just wait and it will come. But instead of Soviet life improving, it continued to get worse. +

By the way, is that national AP Euro exam breathing down your neck? Then check out my AP Euro review pack, which has exclusive videos and practice questions and practice tests. It has everything you need to get a five on that exam. You know, if Brezhnev would have had that, maybe the Soviet Union wouldn't have collapsed. I mean, anyway. +

Part of the economic trouble had to do with the way the Soviet economy was organized, which is to say it was a planned economy 计划经济. That means the government made all the decisions about what jobs people had and what they made when they went to their job. In a market economy 市场经济, consumers tell manufacturers what they wanted, the manufacturers respond -- which is a very simplified way of talking about supply and demand 供求关系. But under the dictates 命令；规定 of a planned economy, it's the government who decides what is manufactured and what is not. +

Now in order to make such a centralized system 集权体制 work, it required a huge bureaucracy 官僚机构 of tens of thousands of people to implement. By the 70s and 80s, that bureaucracy was plagued with inefficiency 效率低下 and waste, which led to a decline in worker productivity 工人生产力下降. +

Another part of the economic trouble was the malaise 萎靡不振；不满情绪 of workers in a planned economy. There's precisely no incentive 激励；动机 to work harder than is absolutely necessary, since communism was collective 集体的 by nature. Anyone who worked harder or innovated in any way saw the spoils 利益 of that increased productivity and innovation go to everyone else. It had a way of discouraging hard work and innovation. +

And third, crop failures 农作物歉收 in the early 70s plunged the Soviet Union even further into trouble. Now the Soviet Union is, to use the technical term, butt cold, and much of its land is not suitable for agriculture 农业. And that meant that crop failures were not uncommon. But add to that reality -- a drought 干旱 hit Europe in 1972, and the Soviet government was unable to feed its people. And so to rectify 纠正 that situation, they turned to the last place you would imagine -- the United States. No, that's right, me from that side of the screen. They called up the United States, their chief rival in the Cold War, and asked for grain 粮食. +

So the Americans, happy to be in the superior position, said, "Sure, we'll let you buy 750 million dollars worth of grain on credit 赊账 over three years." But apparently things were so bad in the Soviet Union that they spent that 750 million in one month. Like, one month, people. So the point is, things were not good in the Soviet Union during this time. The people were hungry, and the economy had completely stagnated 停滞不前. +

So into that economic stagnation, a new leader emerged, namely Mikhail Gorbachev 米哈伊尔·戈尔巴乔夫, who rose to power in 1982. Now contrary to Brezhnev's status quo-ery, Gorbachev was a serious reformer 改革者 by nature. And although he was a communist through and through 彻头彻尾, he was enough of a realist 现实主义者 to understand that the way communism was being implemented was leading to disaster. So to that end, Gorbachev introduced two new categories of reform in the Soviet Union that would ultimately lead to its collapse. +

The first reform was called perestroika 改革, which was an effort to restructure 重组 the Soviet economy by introducing some limited free market 有限的自由市场. For example, under the perestroika reforms, government price controls 政府价格管制 on many items were taken away, and there was a move to allow more private property 私有财产. And you know, initially these reforms saw some moderate success in staving off 避开；延缓 Soviet economic collapse, but by 1988 the economy grew sluggish 疲软的 once again. +

The second reform was called glasnost 公开性, which is a word that means "openness." Under this reform, Gorbachev wanted people to be able to speak freely about the problems facing the Soviet Union, which was kind of a big deal after decades of repression 镇压 under previous leaders. Under this heading, more than one candidate was allowed to compete for office, political parties other than the Communist Party were legalized 合法化, and those who had been imprisoned for speaking negatively about the party or the state were released. +

And really, you can see the extent of the openness when you consider what happened after one of the worst environmental disasters of the 20th century, namely the explosion of a nuclear power plant in Chernobyl 切尔诺贝利 in April of 1986. One of the reactors 反应堆 exploded and sent massive amounts of radiation 辐射 into the environment. Under previous leaders, this would certainly have never been exposed to the outside world since it would communicate weakness on the part of the Soviets. But under the rubric of glasnost, almost daily communications about the disaster were made. +

Now all that sounds great -- the Soviet Union is chilling out 放松；冷静下来 a little and leaving all the policies of past repression behind them. Here's where I remind you of what I said a minute ago, namely that Gorbachev's reforms actually led to the collapse of the Soviet Union. You see, under the iron fist 铁腕 of previous authoritarian rulers 独裁统治者, ethnic tensions 种族紧张关系 between many of the Soviet Union's various groups remained tamped down 压制；打压. But even with just a little breathing room 喘息空间 introduced by these reforms, those tensions flared up mightily 猛烈地；强烈地. +

When Gorbachev invited openness, plenty of these ethnic minorities 少数民族 started protesting the discrimination 歧视 that they had experienced in the long years of Soviet rule, and in some cases that led to violent conflict 暴力冲突. Okay everybody, let's just rein that openness back in. Everybody chill. But they patently 明显地 did not chill. And as a result of these people having freedom to express their pent-up desires 压抑的欲望, a wave of nationalism 民族主义 spread throughout the Soviet Union in places like Georgia 格鲁吉亚 and Azerbaijan 阿塞拜疆, and in the states of the Soviet Bloc 苏联集团. +

And speaking of the Soviet Bloc, in 1989 Gorbachev broke significantly with his predecessors 前任 and announced that the Soviet Union would no longer intervene militarily in those states to prop up 支持；支撑 their communist governments. And with that announcement, revolts 起义；反抗 in Eastern Europe began almost immediately. +

Anyway, a good example of this was the Polish elections 波兰选举 of 1989. Now Poland had always been kind of a problem for the Soviets -- they just didn't submit well to communist rule. And by 1989, a labor party called Solidarity 团结工会 had led large-scale agitations 大规模的煽动 against any attempt by the Soviets to repress their freedom. In that year, the Soviets finally agreed to legalize their party and allow for free elections 自由选举. And that might seem like a risky proposition 提议；主张 to you, but to the Soviets who were enamored by communism, like they thought there was no way that the Poles would vote out their communist leaders. I mean, everybody in Poland loves communism, right? Right? +

But as it turned out, Solidarity candidates won the majority of the elections in that year and started the process of dissolving 解散 the bonds between Poland and the Soviet Union. +

And maybe there is no more potent 强有力的 symbol of crumbling 崩溃；瓦解 Soviet power than the fall of the Berlin Wall 柏林墙. Remember that this wall was erected 建造；竖立 by Stalin in 1961 to keep East Berliners from fleeing to the democratic West. But by 1989, so many Germans had fled to the west, and the Soviet government was so flagged 衰退的, that finally the border was opened and the wall came down. +

So ultimately, all these factors combined -- along with a thousand complementary 互补的 ones -- led to the fall of the Soviet Union in 1991. This of course officially ended the Cold War, and also led to the establishment of capitalist economies 资本主义经济 and democratic governments throughout Eastern Europe and the former Soviet Bloc countries. More than that, Germany was reunited at last, Czechoslovakia 捷克斯洛伐克 split into the Czech Republic 捷克共和国 and Slovakia 斯洛伐克, Yugoslavia 南斯拉夫 broke into several ethnically defined states 按民族划分的几个国家, and the European Union 欧盟 -- which we'll talk about more in another video -- was enlarged by the entry of many new nations. +

Okay, click here if you want to keep reviewing for Unit 9 of AP European History, and click here to grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May. And I'll catch you on the flip flop. Heimler out. +

'''

== 中文释义

所以现在你们都知道，冷战（Cold War）是 20 世纪美国（United States）和苏维埃社会主义共和国联盟（Soviet Union）之间长期存在的紧张关系。但是从 1980 年代开始，似乎凭空出现，苏维埃社会主义共和国联盟（Soviet Union）就那样直接从楼梯上摔了下来，撞到了平台，然后就崩溃死亡了。那么这到底是怎么发生的呢？嗯，这就是这个视频的全部内容。所以如果你准备好挤压你大脑里的奶牛，让我们开始吧。 +

因此，1964 年，一个名叫列昂尼德·勃列日涅夫（Leonid Brezhnev）的人在苏维埃社会主义共和国联盟（Soviet Union）崛起掌权，勃列日涅夫（Brezhnev）是一个维持现状的人。在他看来，苏维埃社会主义共和国联盟（Soviet Union）一切都很好。但是到了 60 年代末和 70 年代，经济现实开始与这种估计相矛盾。苏联人民一次又一次地被告知，共产主义的乌托邦就在眼前——只要等待，它就会到来。但是，苏联人民的生活并没有改善，反而持续恶化。 +

顺便问一下，全国性的 AP 欧洲史（AP Euro）考试是不是让你感到压力很大？那么看看我的 AP 欧洲史复习包，它有独家视频、练习题和模拟测试。它包含了你在那次考试中获得五分所需的一切。你知道，如果勃列日涅夫（Brezhnev）拥有那个复习包，也许苏联就不会崩溃了。我的意思是，无论如何。 +

部分经济困境与苏联经济的组织方式有关，也就是说，它是一个计划经济（planned economy）。这意味着政府对人们从事什么工作以及他们上班时的收入做出所有决定。在市场经济（market economy）中，消费者告诉制造商他们想要什么，制造商做出回应——这是一种非常简化的供需关系描述方式。但是在计划经济（planned economy）的指令下，是政府决定生产什么和不生产什么。 +

现在，为了使这样一个中央集权系统运作，它需要一个庞大的官僚机构，由成千上万的人来实施。到了 70 年代和 80 年代，这个官僚机构充斥着低效和浪费，这导致了工人生产力的下降。 +

经济困境的另一个原因是计划经济（planned economy）中工人的萎靡不振。由于共产主义本质上是集体主义的，因此根本没有激励人们比绝对必要更努力地工作。任何更努力工作或以任何方式进行创新的人，都会看到这种生产力和创新带来的好处归于其他人。这导致了对努力工作和创新的抑制。 +

第三，70 年代初的农作物歉收使苏维埃社会主义共和国联盟（Soviet Union）陷入了更深的困境。现在，苏维埃社会主义共和国联盟（Soviet Union），用一个技术术语来说，是极度寒冷的，其大部分土地不适合农业。这意味着农作物歉收并不罕见。但更糟糕的是——1972 年欧洲遭受了干旱，而苏联政府无法养活其人民。因此，为了纠正这种情况，他们求助于你最意想不到的地方——美国（United States）。不，没错，就是屏幕那边的我。他们给美国（United States），他们在冷战（Cold War）中的主要对手打电话，请求粮食援助。 +

因此，美国人很高兴处于优势地位，他们说：“当然，我们允许你们在三年内赊购价值 7.5 亿美元的谷物。”但显然苏联的情况非常糟糕，他们在一个月内就花光了那 7.5 亿美元。一个月，各位。所以关键是，当时苏联的情况并不好。人民饥饿，经济完全停滞不前。 +

就在这种经济停滞不前的背景下，一位新领导人出现了，他就是 1982 年上台的米哈伊尔·戈尔巴乔夫（Mikhail Gorbachev）。与勃列日涅夫（Brezhnev）的维持现状不同，戈尔巴乔夫（Gorbachev）本质上是一位严肃的改革者。虽然他彻头彻尾是一位共产主义者，但他足够现实，能够理解共产主义的实施方式正导致灾难。为此，戈尔巴乔夫（Gorbachev）在苏维埃社会主义共和国联盟（Soviet Union）推行了两项新的改革，这两项改革最终将导致其崩溃。 +

第一项改革被称为“改革”（perestroika），旨在通过引入一些有限的自由市场来重组苏联经济。例如，在“改革”（perestroika）措施下，许多商品的价格管制被取消，并朝着允许更多私有财产的方向发展。你知道，最初这些改革在一定程度上成功地阻止了苏联经济的崩溃，但是到了 1988 年，经济再次变得迟缓。 +

第二项改革被称为“公开性”（glasnost），这个词的意思是“开放”。在这项改革下，戈尔巴乔夫（Gorbachev）希望人民能够自由地谈论苏维埃社会主义共和国联盟（Soviet Union）面临的问题，这在先前领导人几十年压制之后是一件大事。在这项措施下，允许多名候选人竞争公职，共产党以外的政党合法化，那些因负面评价党或国家而被监禁的人获释。 +

当你考虑到 20 世纪最严重的几起环境灾难之一，即 1986 年 4 月切尔诺比利（Chernobyl）核电站爆炸事件发生后的情况时，你就能真正看到这种开放的程度。其中一个反应堆爆炸，向环境释放了大量的辐射。在前几任领导人统治下，这种情况肯定不会暴露给外界，因为它会暴露苏联的弱点。但是在“公开性”（glasnost）的原则下，几乎每天都会发布关于这场灾难的通报。 +

这一切听起来都很棒——苏维埃社会主义共和国联盟（Soviet Union）正在放松一些，并抛弃过去压制的所有政策。现在我要提醒你我刚才说过的话，即戈尔巴乔夫（Gorbachev）的改革实际上导致了苏维埃社会主义共和国联盟（Soviet Union）的崩溃。你看，在前几任独裁统治者的铁腕统治下，苏维埃社会主义共和国联盟（Soviet Union）各民族之间的民族矛盾一直被压制着。但是，即使这些改革只带来了一点喘息的空间，这些矛盾也剧烈地爆发出来。 +

当戈尔巴乔夫（Gorbachev）倡导公开性时，许多少数民族开始抗议他们在苏联统治漫长岁月里所遭受的歧视，在某些情况下，这导致了暴力冲突。好了各位，让我们稍微收回一下这种开放性。大家都冷静点。但是他们显然没有冷静下来。结果，由于这些人有表达他们长期压抑的愿望的自由，民族主义浪潮席卷了苏维埃社会主义共和国联盟（Soviet Union）的格鲁吉亚（Georgia）和阿塞拜疆（Azerbaijan）等地，以及苏联集团（Soviet Bloc）的国家。 +

说到苏联集团（Soviet Bloc），1989 年，戈尔巴乔夫（Gorbachev）显著地背离了他的前任，并宣布苏维埃社会主义共和国联盟（Soviet Union）将不再以军事手段干预这些国家以支持其共产主义政府。随着这一宣布，东欧的起义几乎立即开始。 +

无论如何，一个很好的例子是 1989 年的波兰选举。波兰对苏联来说一直是个麻烦——他们不太顺从共产党的统治。到 1989 年，一个名为团结工会（Solidarity）的劳工组织领导了大规模的抗议活动，反对苏联任何压制他们自由的企图。在那一年，苏联最终同意承认他们的政党合法化并允许自由选举。这在你看来可能是一个冒险的提议，但对于那些迷恋共产主义的苏联人来说，他们认为波兰人不可能投票反对他们的共产党领导人。我的意思是，波兰的每个人都热爱共产主义，对吧？对吧？ +

但事实证明，团结工会（Solidarity）的候选人在那年的选举中赢得了多数席位，并开始了瓦解波兰和苏维埃社会主义共和国联盟（Soviet Union）之间联系的进程。 +

也许没有比柏林墙（Berlin Wall）的倒塌更能象征苏联权力崩溃的有力标志了。记住，这堵墙是斯大林（Stalin）在 1961 年建造的，目的是阻止东柏林人逃往民主的西方。但是到了 1989 年，如此多的德国人逃往西方，苏联政府也如此疲惫不堪，以至于最终边界被打开，柏林墙（Berlin Wall）倒塌了。 +

因此，最终，所有这些因素——以及一千个补充因素——共同导致了 1991 年苏维埃社会主义共和国联盟（Soviet Union）的解体。这当然正式结束了冷战（Cold War），也导致了资本主义经济和民主政府在整个东欧和前苏联集团（Soviet Bloc）国家的建立。不仅如此，德国最终重新统一，捷克斯洛伐克分裂为捷克共和国（Czech Republic）和斯洛伐克（Slovakia），南斯拉夫分裂为几个民族国家，而欧洲联盟（European Union）——我们将在另一个视频中更多地讨论它——因许多新国家的加入而扩大。 +

好的，如果你想继续复习 AP 欧洲史第九单元，点击这里，点击这里获取我的 AP 欧洲史复习包，它包含了你在课堂上获得 A 和五月份考试中获得五分所需的一切。我稍后会再见。海姆勒走了。 +

'''

== pure

So by now you know that the Cold War was a long-standing tension in the 20th century between the United States and the Soviet Union. But starting in the 1980s, seemingly out of nowhere, the Soviet Union just flat tumbled down the stairs, crashed into the landing, and then just collapsed and died. So how in the fresh heck did that happen? Well, that's what this video is all about. So if you're ready to get them brain cows milked, let's get to it.

So in 1964, a guy named Leonid Brezhnev rose to power in the Soviet Union, and Brezhnev was a status quo kind of guy. By his reckoning, the Soviet Union was just fine. But in the late 60s and into the 70s, economic realities began to contradict that estimation. The Soviet people had been told over and over again that the communist utopia was just around the corner -- just wait and it will come. But instead of Soviet life improving, it continued to get worse.

By the way, is that national AP Euro exam breathing down your neck? Then check out my AP Euro review pack, which has exclusive videos and practice questions and practice tests. It has everything you need to get a five on that exam. You know, if Brezhnev would have had that, maybe the Soviet Union wouldn't have collapsed. I mean, anyway.

Part of the economic trouble had to do with the way the Soviet economy was organized, which is to say it was a planned economy. That means the government made all the decisions about what jobs people had and what they made when they went to their job. In a market economy, consumers tell manufacturers what they wanted, the manufacturers respond -- which is a very simplified way of talking about supply and demand. But under the dictates of a planned economy, it's the government who decides what is manufactured and what is not.

Now in order to make such a centralized system work, it required a huge bureaucracy of tens of thousands of people to implement. By the 70s and 80s, that bureaucracy was plagued with inefficiency and waste, which led to a decline in worker productivity.

Another part of the economic trouble was the malaise of workers in a planned economy. There's precisely no incentive to work harder than is absolutely necessary, since communism was collective by nature. Anyone who worked harder or innovated in any way saw the spoils of that increased productivity and innovation go to everyone else. It had a way of discouraging hard work and innovation.

And third, crop failures in the early 70s plunged the Soviet Union even further into trouble. Now the Soviet Union is, to use the technical term, butt cold, and much of its land is not suitable for agriculture. And that meant that crop failures were not uncommon. But add to that reality -- a drought hit Europe in 1972, and the Soviet government was unable to feed its people. And so to rectify that situation, they turned to the last place you would imagine -- the United States. No, that's right, me from that side of the screen. They called up the United States, their chief rival in the Cold War, and asked for grain.

So the Americans, happy to be in the superior position, said, "Sure, we'll let you buy 750 million dollars worth of grain on credit over three years." But apparently things were so bad in the Soviet Union that they spent that 750 million in one month. Like, one month, people. So the point is, things were not good in the Soviet Union during this time. The people were hungry, and the economy had completely stagnated.

So into that economic stagnation, a new leader emerged, namely Mikhail Gorbachev, who rose to power in 1982. Now contrary to Brezhnev's status quo-ery, Gorbachev was a serious reformer by nature. And although he was a communist through and through, he was enough of a realist to understand that the way communism was being implemented was leading to disaster. So to that end, Gorbachev introduced two new categories of reform in the Soviet Union that would ultimately lead to its collapse.

The first reform was called perestroika, which was an effort to restructure the Soviet economy by introducing some limited free market. For example, under the perestroika reforms, government price controls on many items were taken away, and there was a move to allow more private property. And you know, initially these reforms saw some moderate success in staving off Soviet economic collapse, but by 1988 the economy grew sluggish once again.

The second reform was called glasnost, which is a word that means "openness." Under this reform, Gorbachev wanted people to be able to speak freely about the problems facing the Soviet Union, which was kind of a big deal after decades of repression under previous leaders. Under this heading, more than one candidate was allowed to compete for office, political parties other than the Communist Party were legalized, and those who had been imprisoned for speaking negatively about the party or the state were released.

And really, you can see the extent of the openness when you consider what happened after one of the worst environmental disasters of the 20th century, namely the explosion of a nuclear power plant in Chernobyl in April of 1986. One of the reactors exploded and sent massive amounts of radiation into the environment. Under previous leaders, this would certainly have never been exposed to the outside world since it would communicate weakness on the part of the Soviets. But under the rubric of glasnost, almost daily communications about the disaster were made.

Now all that sounds great -- the Soviet Union is chilling out a little and leaving all the policies of past repression behind them. Here's where I remind you of what I said a minute ago, namely that Gorbachev's reforms actually led to the collapse of the Soviet Union. You see, under the iron fist of previous authoritarian rulers, ethnic tensions between many of the Soviet Union's various groups remained tamped down. But even with just a little breathing room introduced by these reforms, those tensions flared up mightily.

When Gorbachev invited openness, plenty of these ethnic minorities started protesting the discrimination that they had experienced in the long years of Soviet rule, and in some cases that led to violent conflict. Okay everybody, let's just rein that openness back in. Everybody chill. But they patently did not chill. And as a result of these people having freedom to express their pent-up desires, a wave of nationalism spread throughout the Soviet Union in places like Georgia and Azerbaijan, and in the states of the Soviet Bloc.

And speaking of the Soviet Bloc, in 1989 Gorbachev broke significantly with his predecessors and announced that the Soviet Union would no longer intervene militarily in those states to prop up their communist governments. And with that announcement, revolts in Eastern Europe began almost immediately.

Anyway, a good example of this was the Polish elections of 1989. Now Poland had always been kind of a problem for the Soviets -- they just didn't submit well to communist rule. And by 1989, a labor party called Solidarity had led large-scale agitations against any attempt by the Soviets to repress their freedom. In that year, the Soviets finally agreed to legalize their party and allow for free elections. And that might seem like a risky proposition to you, but to the Soviets who were enamored by communism, like they thought there was no way that the Poles would vote out their communist leaders. I mean, everybody in Poland loves communism, right? Right?

But as it turned out, Solidarity candidates won the majority of the elections in that year and started the process of dissolving the bonds between Poland and the Soviet Union.

And maybe there is no more potent symbol of crumbling Soviet power than the fall of the Berlin Wall. Remember that this wall was erected by Stalin in 1961 to keep East Berliners from fleeing to the democratic West. But by 1989, so many Germans had fled to the west, and the Soviet government was so flagged, that finally the border was opened and the wall came down.

So ultimately, all these factors combined -- along with a thousand complementary ones -- led to the fall of the Soviet Union in 1991. This of course officially ended the Cold War, and also led to the establishment of capitalist economies and democratic governments throughout Eastern Europe and the former Soviet Bloc countries. More than that, Germany was reunited at last, Czechoslovakia split into the Czech Republic and Slovakia, Yugoslavia broke into several ethnically defined states, and the European Union -- which we'll talk about more in another video -- was enlarged by the entry of many new nations.

Okay, click here if you want to keep reviewing for Unit 9 of AP European History, and click here to grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May. And I'll catch you on the flip flop. Heimler out.

'''