
= 9.9 DECOLONIZATION
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Okay, it's time to talk about decolonization 去殖民化. And if you, my friend, are ready to hear all about how European empires fell apart after World War II, then this is the video for you. So I think it's high time we got them brain cows milked. Let's get to it. +

So hopefully, if you've made it this far in the AP European History curriculum 课程, you know by now that European empire building has been a major theme that runs from the beginning of this course all the way through the end. Dang near every European state at one time or another has looked at the rest of the world and was like, "I'll take that, and that, and that." But after World War II, we're gonna see how this centuries-long project of European empire falls apart, and the name for it is decolonization. +

Really, it started after World War One thanks to American President Woodrow Wilson. Remember that one of his big pushes during this peace process was the encouragement of self-determination 自决权 for all the states involved and all the states around the world. What this means is that any given people should have the right to determine their own political structure -- like should be able to choose their own government without the interference 干涉；干预 of European imperial powers. +

And look, I myself am no fan of worldwide imperial domination 统治, but I am a fan of you positively dominating your AP exam in May. And if you do too, then check out my AP Euro review pack, which is linked down in the description. Anyway, while old Woodrow was waxing eloquent 滔滔不绝地说 about self-determination at Versailles, everyone in India and Algeria and South Africa and dang near every colonized 被殖民的 people in the world were like, "Uh, yes please." And you know, add in the fact that European empires had called up colonial soldiers to fight in World War One, and the calls for independence grew even louder. +

But old imperial habits are hard to break, and once push came to shove 到了紧要关头, European imperial powers were reluctant 不情愿的；勉强的 to give up their vast empires. Then came along World War II, and again colonial soldiers fought in their imperial parents' war. But this time, once the war was over, major imperial powers no longer had the wealth or military power to quell 镇压；平息 the rising demands for independence around the world. And thus began the process of decolonization, which happened over the span of decades. +

I'd like to tell you that decolonization happened easily once European powers decided that they can no longer hold on to their empires, but then I'd be lying to you. In some cases it did happen quickly and quietly, but in other cases -- you know, Europeans be Europeans -- and their reluctance to let go of their colonies meant that a war was fought. So let's consider how the process took place first in Africa and then in Asia. +

Now remember that European powers had carved up 瓜分 Africa like their little plaything during the second wave of imperialism, and this became known as the Scramble for Africa 非洲争夺战 in the 19th century. After World War II, indigenous 本土的；土著的 nationalist movements sprang up demanding independence. In Algeria, for example, which had been a French colony, things got uh... tense 紧张的. You see, France had already recognized the independence of two of its colonies -- Morocco and Tunisia -- but they also had Algeria under their thumb 控制；支配 as well. But the French didn't want to grant Algeria independence because the problem in Algeria is that almost a million French citizens had migrated to Algeria and settled there. +

So in response to this reluctance, in the 1950s a nationalist Muslim group called the National Liberation Front 民族解放阵线 began rebelling against their colonizers. And so to protect French citizens living in Algeria along with hundreds of thousands of other white Europeans, France sent troops to crush 镇压；粉碎 the rebellion, which -- you know -- they did. But it instigated 激起；引发 a bloody eight-year civil war, and it came to an end with the return of Charles de Gaulle, who became the French president in 1958. He recognized Algeria's right to self-determination and officially recognized their independence. +

Now something similar was going on over in Egypt, which had been a British colony. Now technically Egypt became independent in 1922 after World War One, but the British engineered 策划；操纵 the independence so they were basically still in charge. Therefore, a nationalist political party was formed in Egypt called the Wafd, which began campaigning 发起运动 for full Egyptian independence. Now the problem was that the Wafd weren't big fans of the Egyptian monarch 君主 either, and so in 1952 the Egyptian army led a coup 政变 to overthrow the monarch and officially throw off British intrusion 入侵 in their state. +

Okay, now let's head over to Asia and see how the decolonization process was going over there, and we'll start in India. By 1920, Mohandas Gandhi led the Indian National Congress 印度国民大会党 in the movement for Indian independence from Britain. And Gandhi's chosen means of leadership to this end was non-violent civil disobedience 非暴力不合作运动. The British were essentially exhausted and broke from fighting World War II, and in light of 鉴于；由于 all this resistance from Indians, they realized they simply didn't have the resources or the power to maintain colonial rule in India. And so in 1947, India -- through negotiation 谈判；协商 with Britain -- became an independent nation. +

Now remember that all this is going on right smack in the middle of the Cold War. So as these nations are gaining their independence, both the United States and the Soviet Union came knocking on their doors to persuade 说服；劝说 them to join one side or the other. Now India resisted both powers and remained independent of the struggle, and thus paved the way for 为……铺平道路 what became known as the non-aligned movement 不结盟运动, which several other newly independent nations would also take. +

But for other states fighting for their independence, remaining non-aligned was more difficult. For example, in Indonesia -- which had gained its independence from the Dutch in 1949 -- the Soviets made significant inroads 进展；取得突破. The president of Indonesia, a guy by the name of Sukarno, was a socialist, and he gladly accepted support for his policies from the Soviet Union and communist China. However, an Indonesian nationalist movement formed during his tenure 任期, mostly comprised of 由……组成 the military and conservative Muslims, and they overthrew Sukarno in 1965 and then established a new government and aligned themselves with the West. +

And finally, the world witnessed a similar struggle as Vietnam sought its independence from France. In the 1950s, a Vietnamese nationalist leader named Ho Chi Minh organized a resistance group called the Viet Minh 越盟, whose goal was to overthrow the French. The Viet Minh won a decisive 决定性的 battle against the French in 1954, and so the French divided Vietnam into two in order to prepare them for elections and independence in 1956. The north became dominated by communist sympathies while the south was more loyal to Western powers. And if you remember from Unit 8, the Soviet Union and the United States ended up fighting a proxy war 代理人战争 here that ultimately ended in... however, after all was said and done, Vietnam gained its independence in 1975. +

Okay, click here to keep reviewing Unit 9 of AP Euro, and since you have that national exam breathing down your neck, you can click here and grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam. I'll catch you on the flip-flop. I'm Lauren. +

'''

== 中文释义

好的，是时候谈谈去殖民化了。如果你，我的朋友，准备好了解二战后欧洲帝国是如何瓦解的，那么这个视频就是为你准备的。所以我觉得是时候获取知识了。让我们开始吧。 +

希望如果你已经学习到AP欧洲历史课程的这个阶段，你现在知道欧洲的帝国构建是一个贯穿这门课程始终的主要主题。几乎每一个欧洲国家都曾一度看着世界其他地方，想着：“我要这个，还有那个，还有那个。” 但是在第二次世界大战之后，我们将看到这个长达几个世纪的欧洲帝国计划是如何瓦解的，这个过程被称为去殖民化。 +

实际上，这始于第一次世界大战之后，这要归功于美国总统伍德罗·威尔逊（Woodrow Wilson）。记住，在和平进程中，他的一个重大推动是鼓励所有相关国家以及世界各国的自决。这意味着任何特定的民族都应该有权决定自己的政治结构 —— 比如应该能够在没有欧洲帝国列强干涉的情况下选择自己的政府。 +

听着，我自己并不支持全球帝国统治，但我支持你在五月份的AP考试中取得好成绩。如果你也想取得好成绩，那就看看我的AP欧洲史复习资料包，简介里有链接。不管怎样，当老伍德罗在凡尔赛滔滔不绝地谈论自决时，印度、阿尔及利亚、南非以及几乎世界上每一个被殖民的民族都在想：“呃，好啊。” 而且你知道，再加上欧洲帝国征召殖民士兵参加第一次世界大战这个事实，要求独立的呼声变得更响亮了。 +

但是旧有的帝国习惯很难改变，一旦到了关键时刻，欧洲的帝国列强不愿意放弃他们庞大的帝国。然后第二次世界大战爆发了，殖民士兵又一次为他们的帝国宗主国参战。但是这一次，战争结束后，主要的帝国列强不再有财力或军事力量来镇压世界各地日益高涨的独立要求。于是去殖民化的进程开始了，这个进程持续了几十年。 +

我想告诉你，一旦欧洲列强决定他们再也无法维持他们的帝国，去殖民化就轻松地发生了，但那我就是在骗你。在某些情况下，去殖民化确实迅速而平静地发生了，但在其他情况下 —— 你知道，欧洲人毕竟是欧洲人 —— 他们不愿意放弃殖民地，这意味着要打一场战争。所以让我们先看看这个进程在非洲是如何发生的，然后再看看在亚洲的情况。 +

记住，在第二次帝国主义浪潮中，欧洲列强把非洲当作他们的玩物进行了瓜分，这在19世纪被称为 “非洲争夺战”（the Scramble for Africa）。第二次世界大战后，本土的民族主义运动兴起，要求独立。例如在曾是法国殖民地的阿尔及利亚，局势变得呃…… 紧张起来。你看，法国已经承认了它的两个殖民地 —— 摩洛哥和突尼斯 —— 的独立，但他们也控制着阿尔及利亚。但是法国不想给予阿尔及利亚独立，因为阿尔及利亚的问题是，有近百万法国公民移民到了阿尔及利亚并在那里定居。 +

为了应对这种不情愿，在20世纪50年代，一个名为民族解放阵线（the National Liberation Front）的穆斯林民族主义团体开始反抗他们的殖民者。所以为了保护生活在阿尔及利亚的法国公民以及数十万其他欧洲白人，法国派兵镇压了反抗，你知道，他们做到了。但这引发了一场血腥的八年内战，1958年夏尔·戴高乐（Charles de Gaulle）成为法国总统后，内战结束。他承认了阿尔及利亚的自决权，并正式承认了阿尔及利亚的独立。 +

在曾是英国殖民地的埃及也发生了类似的事情。从技术上讲，埃及在第一次世界大战后的1922年就获得了独立，但英国操纵了埃及的独立，所以实际上英国仍然掌控着局面。因此，埃及成立了一个名为华夫脱党（the Wafd）的民族主义政党，该党开始为埃及的完全独立而开展运动。问题是华夫脱党也不喜欢埃及的君主制，所以在1952年，埃及军队发动政变推翻了君主制，并正式摆脱了英国对其国家的干涉。 +

好的，现在让我们看看亚洲，看看那里的去殖民化进程是如何进行的，我们从印度开始说起。到1920年，莫罕达斯·甘地（Mohandas Gandhi）领导印度国民大会党（the Indian National Congress）开展了从英国手中争取印度独立的运动。甘地为此选择的领导方式是非暴力的公民不服从。英国基本上因为第二次世界大战而疲惫不堪且财政枯竭，鉴于印度人的所有反抗，他们意识到他们根本没有资源或力量来维持对印度的殖民统治。所以在1947年，印度通过与英国的谈判成为了一个独立的国家。 +

记住，这一切都发生在冷战期间。所以当这些国家获得独立时，美国和苏联都找上门来，劝说它们加入自己一方。印度抵制了这两个大国，在这场争斗中保持独立，从而为所谓的不结盟运动（the non-aligned movement）铺平了道路，其他几个新独立的国家也加入了不结盟运动。 +

但对于其他争取独立的国家来说，保持不结盟更加困难。例如在1949年从荷兰手中获得独立的印度尼西亚，苏联取得了重大进展。印度尼西亚总统苏加诺（Sukarno）是一名社会主义者，他欣然接受了苏联和共产主义中国对他政策的支持。然而，在他的任期内，一个印度尼西亚民族主义运动形成了，这个运动主要由军队和保守的穆斯林组成，他们在1965年推翻了苏加诺，然后建立了一个新政府，并与西方结盟。 +

最后，世界见证了越南从法国手中争取独立时类似的斗争。在20世纪50年代，一位名叫胡志明（Ho Chi Minh）的越南民族主义领导人组织了一个名为越盟（the Viet Minh）的抵抗组织，其目标是推翻法国的统治。1954年，越盟在与法国的一场决定性战斗中获胜，所以法国将越南一分为二，为1956年的选举和独立做准备。北越倾向于共产主义，而南越更忠于西方列强。如果你还记得第8单元的内容，苏联和美国最终在这里打了一场代理人战争，最终…… 不管怎样，在一切尘埃落定后，越南在1975年获得了独立。 +

好的，点击这里继续复习AP欧洲史第9单元，既然全国性考试已经迫在眉睫，你可以点击这里获取我的AP欧洲史复习资料包，它包含了你在课堂上得A、在考试中得5分所需的一切。回头见。我是劳伦（Lauren）。 +

'''

== pure

Okay, it's time to talk about decolonization. And if you, my friend, are ready to hear all about how European empires fell apart after World War II, then this is the video for you. So I think it's high time we got them brain cows milked. Let's get to it.

So hopefully, if you've made it this far in the AP European History curriculum, you know by now that European empire building has been a major theme that runs from the beginning of this course all the way through the end. Dang near every European state at one time or another has looked at the rest of the world and was like, "I'll take that, and that, and that." But after World War II, we're gonna see how this centuries-long project of European empire falls apart, and the name for it is decolonization.

Really, it started after World War One thanks to American President Woodrow Wilson. Remember that one of his big pushes during this peace process was the encouragement of self-determination for all the states involved and all the states around the world. What this means is that any given people should have the right to determine their own political structure -- like should be able to choose their own government without the interference of European imperial powers.

And look, I myself am no fan of worldwide imperial domination, but I am a fan of you positively dominating your AP exam in May. And if you do too, then check out my AP Euro review pack, which is linked down in the description. Anyway, while old Woodrow was waxing eloquent about self-determination at Versailles, everyone in India and Algeria and South Africa and dang near every colonized people in the world were like, "Uh, yes please." And you know, add in the fact that European empires had called up colonial soldiers to fight in World War One, and the calls for independence grew even louder.

But old imperial habits are hard to break, and once push came to shove, European imperial powers were reluctant to give up their vast empires. Then came along World War II, and again colonial soldiers fought in their imperial parents' war. But this time, once the war was over, major imperial powers no longer had the wealth or military power to quell the rising demands for independence around the world. And thus began the process of decolonization, which happened over the span of decades.

I'd like to tell you that decolonization happened easily once European powers decided that they can no longer hold on to their empires, but then I'd be lying to you. In some cases it did happen quickly and quietly, but in other cases -- you know, Europeans be Europeans -- and their reluctance to let go of their colonies meant that a war was fought. So let's consider how the process took place first in Africa and then in Asia.

Now remember that European powers had carved up Africa like their little plaything during the second wave of imperialism, and this became known as the Scramble for Africa in the 19th century. After World War II, indigenous nationalist movements sprang up demanding independence. In Algeria, for example, which had been a French colony, things got uh... tense. You see, France had already recognized the independence of two of its colonies -- Morocco and Tunisia -- but they also had Algeria under their thumb as well. But the French didn't want to grant Algeria independence because the problem in Algeria is that almost a million French citizens had migrated to Algeria and settled there.

So in response to this reluctance, in the 1950s a nationalist Muslim group called the National Liberation Front began rebelling against their colonizers. And so to protect French citizens living in Algeria along with hundreds of thousands of other white Europeans, France sent troops to crush the rebellion, which -- you know -- they did. But it instigated a bloody eight-year civil war, and it came to an end with the return of Charles de Gaulle, who became the French president in 1958. He recognized Algeria's right to self-determination and officially recognized their independence.

Now something similar was going on over in Egypt, which had been a British colony. Now technically Egypt became independent in 1922 after World War One, but the British engineered the independence so they were basically still in charge. Therefore, a nationalist political party was formed in Egypt called the Wafd, which began campaigning for full Egyptian independence. Now the problem was that the Wafd weren't big fans of the Egyptian monarch either, and so in 1952 the Egyptian army led a coup to overthrow the monarch and officially throw off British intrusion in their state.

Okay, now let's head over to Asia and see how the decolonization process was going over there, and we'll start in India. By 1920, Mohandas Gandhi led the Indian National Congress in the movement for Indian independence from Britain. And Gandhi's chosen means of leadership to this end was non-violent civil disobedience. The British were essentially exhausted and broke from fighting World War II, and in light of all this resistance from Indians, they realized they simply didn't have the resources or the power to maintain colonial rule in India. And so in 1947, India -- through negotiation with Britain -- became an independent nation.

Now remember that all this is going on right smack in the middle of the Cold War. So as these nations are gaining their independence, both the United States and the Soviet Union came knocking on their doors to persuade them to join one side or the other. Now India resisted both powers and remained independent of the struggle, and thus paved the way for what became known as the non-aligned movement, which several other newly independent nations would also take.

But for other states fighting for their independence, remaining non-aligned was more difficult. For example, in Indonesia -- which had gained its independence from the Dutch in 1949 -- the Soviets made significant inroads. The president of Indonesia, a guy by the name of Sukarno, was a socialist, and he gladly accepted support for his policies from the Soviet Union and communist China. However, an Indonesian nationalist movement formed during his tenure, mostly comprised of the military and conservative Muslims, and they overthrew Sukarno in 1965 and then established a new government and aligned themselves with the West.

And finally, the world witnessed a similar struggle as Vietnam sought its independence from France. In the 1950s, a Vietnamese nationalist leader named Ho Chi Minh organized a resistance group called the Viet Minh, whose goal was to overthrow the French. The Viet Minh won a decisive battle against the French in 1954, and so the French divided Vietnam into two in order to prepare them for elections and independence in 1956. The north became dominated by communist sympathies while the south was more loyal to Western powers. And if you remember from Unit 8, the Soviet Union and the United States ended up fighting a proxy war here that ultimately ended in... however, after all was said and done, Vietnam gained its independence in 1975.

Okay, click here to keep reviewing Unit 9 of AP Euro, and since you have that national exam breathing down your neck, you can click here and grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam. I'll catch you on the flip-flop. I'm Lauren.

'''