= 0510
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 510: Taking a Shower or Bath.
This is English as a Second Language Podcast episode 510. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there today to download a Learning Guide that will help you improve your English even faster. You can become a member of ESL Podcast, or if you’d like to support our efforts, send us a small donation. More information can be found on our website.
This episode is a story about someone taking a shower or a bath. When your body is dirty, you have to clean it, and that’s what we’re going to do in this episode. Let’s get started.
[start of story]
I spent the day helping my friend, Babbit, on his farm. When I got home, my wife said, “You stink!” I headed straight for the shower.
I ran the water, closed the shower curtain, and adjusted the showerhead. I worked the soap into a lather and scrubbed from head to toe. I rinsed off the soap and toweled off.
When I went back into the living room, my wife said, “You still stink! You need to soak in a bath!”
I went back into the bathroom, put the stopper in the bathtub, and turned on the faucet. I didn’t want to take any chances. I took some of my wife’s bubble bath and poured it into the bathtub. When the bath was ready, I got in. I soaked for a half hour and I washed every nook and cranny.
When I went back into the living room, my wife said, “Wow, you smell as pretty as a flower!” That wasn’t exactly what I was going for, but I’d rather smell like flowers than pigs!
[end of story]
Our story begins with me saying that I spent the day helping my friend, Babbit, on his farm. A “farm” is a place where you may have animals, you may be growing food in the ground; it’s a place outside of the city, usually. When I got home, my wife said, “You stink!” The verb “to stink” is an informal way of saying that someone smells bad, they have an unpleasant smell or an unpleasant odor. “Odor” (odor) is the same as smell. So, when someone doesn’t smell very good because they’re dirty, you could say, “You stink.” However, it’s a very strong thing to say; it’s a very negative thing to say, so you would not want to say that to anyone that you didn’t know very well. We also use the verb “to stink” to mean to be poor at something, to not be very good at something. I could say, “I stink at chess,” meaning I’m not a very good chess player.
But in this case, when my wife says that I stink, she means I smell bad, so I headed straight for the shower. “To head for (something)” is to go in the direction of. When I say I headed straight for the shower, I mean I went directly to the shower; I didn’t do anything else first. That’s the meaning of the word “straight” here. A “shower” is the part of the bathroom where you stand under water to get clean; you stand up and the water goes over you to clean you. I say that I ran the water. “To run the water” means to turn the water on and, usually, wait until the water gets warm enough. So, “to run the water” means to turn the water on. I ran the water, and then I closed the shower curtain. The “shower curtain” is a large piece of plastic that hangs around the shower, separates the shower from the rest of the bathroom to prevent the water from going outside. Some showers have doors, and you slide the door back and forth, often made of glass. Other showers have a shower curtain. A curtain is also a word we use to describe things that you put over your windows to keep the light out; those are also curtains, when they’re made of some kind of material – some kind of fabric. I also adjusted the showerhead. The “showerhead” is the piece of metal that the water comes out of in a shower. It’s attached to a pipe in the wall where the water comes from, and it’s what sprays the water over you – that is, it distributes the water over you. That’s the showerhead.
I said that I worked the soap into a lather. “To work the soap” means I did something to the soap; in this case, I put the soap on my skin and I moved it back and forth – I rubbed it until it was in the form of lather. “Lather” (lather) is when you have a lot of soap bubbles on your skin so that it looks white. Or for example, you could put soap on your hands, and if you move them together very quickly you will work the soap into a lather.
I scrubbed (meaning I rubbed very hard in order to get clean) from head to toe. The expression “from head to toe” means from the top of your body where your head is to the bottom of your body where your foot and toe are. Your “toes,” of course, are the five little digits that come out of your foot. Then, I rinsed off the soap and toweled off. “To rinse (something)” means to pour water on it to, usually, get rid of the soap that you are using to clean something. “To rinse off” means the same; we use “off” here for emphasis. It’s very common in English to add a preposition like “off” after a verb to give it the idea of motion – of action. In this case, to rinse off means to put the water on me so that the soap (that solid or liquid substance that you use to clean something) goes off of my body. So, I rinsed off the soap and I toweled off. “To towel off” means to take something to dry your body, what we call a “towel,” which is a big piece of fabric – of material that you use to dry something with. “To towel off” is the same as “to dry off,” to take something and remove water from something else; in this case, from my body.
When I went back into the living room after showering, my wife said, “You still stink!” In other words, I did not get rid of all of the bad smell. She says, “You need to soak in a bath!” “To soak” (soak), here, means to be covered in water for a long period of time, usually we do that to make something easier to clean. So if you are cooking and you have a pan that is very dirty, you may put water on it – or water in it and let the pan soak – use the water to help make the pan easier to clean. So maybe an hour later, you would come back and then clean the pan. Well here, we’re talking about soaking your body because it’s so dirty, and so you get into what we call a “bathtub,” which is a large, usually rectangular container in the bathroom that you can sit in or lie down in and put water over you.
I went back into the bathroom then and put the stopper in the bathtub. The “stopper” is a small piece of metal or plastic that you put in the hole that is at the bottom of the bathtub or of a sink so that water can’t flow out; the water stays in the bathtub or the sink. If you want to take a bath, you have to put a stopper there so that you have water inside the bathtub. I turned on the faucet after that. The “faucet” (faucet) is a long, metal piece that is above the sink or bathtub that the water comes out of. So, “to turn on the faucet” means to allow the water to come out and fill up the bathtub. I said, “I didn’t want to take any chances,” I wanted to be sure I was going to be clean. So, I took some of my wife’s bubble bath and poured it into the bathtub. “Bubble bath” is a liquid that smells nice that women sometimes, or children, put in their bath to make them smell nice. It’s not something that a man would normally do, but because I was so dirty I wanted to make sure I smelled good.
When the bath was ready, then I got in. I soaked for a half hour and I washed every nook and cranny. The expression “nook (nook) and cranny (cranny)” means small places, but here, when we say “I washed every nook and cranny,” we mean you did a hundred percent of everything; you cleaned everything. You might say, “I was looking for my car keys, because I lost them. I looked in every nook and cranny of my house,” meaning I looked everywhere. So here, we’re saying that I cleaned every part of my body.
When I went back into the living room, my wife said, “Wow, you smell as pretty as a flower!” I say that that wasn’t exactly what I was going for. “To go for,” in this case, means what I wanted, what I intended, what I was trying to make happen. I wasn’t trying to smell pretty, I was just trying not to smell bad. “To go” plus a preposition is a very common expression in English; take a look at our Learning Guide for some more explanations of that, as well as the verb – or the word “soak.” I said, “I’d rather smell like flowers than pigs!” Remember, I was working on a farm, and so one of the animals that you have on a farm is a pig, which people think tends to smell badly.
Now that I’m all clean and smelling like a flower, let’s listen to the dialogue again at a normal speed.
[start of story]
I spent the day helping my friend, Babbit, on his farm. When I got home, my wife said, “You stink!” I headed straight for the shower.
I ran the water, closed the shower curtain, and adjusted the showerhead. I worked the soap into a lather and scrubbed from head to toe. I rinsed off the soap and toweled off.
When I went back into the living room, my wife said, “You still stink! You need to soak in a bath!”
I went back into the bathroom, put the stopper in the bathtub, and turned on the faucet. I didn’t want to take any chances. I took some of my wife’s bubble bath and poured it into the bathtub. When the bath was ready, I got in. I soaked for a half hour and I washed every nook and cranny.
When I went back into the living room, my wife said, “Wow, you smell as pretty as a flower!” That wasn’t exactly what I was going for, but I’d rather smell like flowers than pigs!
[end of story]
The script for this episode was by someone who never stinks at writing scripts, or any other way, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to stink – to smell bad; to have an unpleasant odor
* Our fridge stinks! When was the last time we cleaned it?
shower – the part of a bathroom where one stands under water to get clean, usually surrounded by walls and a door or curtain
* Becca keeps shampoo and soap in her shower.
to run the water – to turn the water on and let it move, usually while waiting for it to get warmer
* On cold winter mornings, they have to run the water for two minutes before it starts to get warm.
shower curtain – a large piece of fabric or plastic that hangs between a shower and the rest of the bathroom to keep the water inside the shower and keep the rest of the bathroom dry.
* The entire bathroom is wet because there is a hole in the shower curtain.
showerhead – the piece of metal that water comes out of in a shower, falling over one’s head, used to control how hard or soft the water is when it falls
* They bought a special showerhead that makes the water feel like a massage.
lather – a group of many soap bubbles on one’s skin, so that it seems to be white, created by rubbing soap and water between one’s hands
* The little boy laughed when he learned how to work soap into a lather.
to scrub – to rub something very hard to clean it
* After the children came indoors with their dirty shoes on, I had to scrub the floor to get it clean again.
from head to toe – over one’s entire body; over all parts of one’s body, not missing any spots
* We had to walk home in the rain, so we were wet from head to toe.
to rinse off – to move water over one’s body or something else to remove soap and leave it clean
* As she was rinsing off the wine glass, it fell out of her hands and broke.
soap – a solid or liquid substance that is rubbed against one’s body or something else to clean it and is removed by rinsing it with water
* Restaurant workers are supposed to wash their hands with soap and warm water after using the restroom.
to towel off – to dry off; to move a large piece of soft fabric over one’s wet body to make it dry
* Harriet forgot to bring a towel to the pool, so instead of toweling off, she just waited for the sun and warm air to dry her body.
to soak – to be immersed in water; to be covered in water for a long period of time, usually to make something softer or easier to clean
* They soaked the beans in water overnight before boiling them.
stopper – a small piece of metal or plastic that is placed in the hole in the bottom of a sink or bathtub so that water cannot flow out, used to fill the sink or bathtub with water
* Filippe put the stopper in the sink and filled it with warm water before shaving.
bathtub – the large, rectangular, porcelain container in a bathroom, used for a person to sit or lie down in when it is filled with water
* Delilah’s mother filled the bathtub with soapy water and toys.
faucet – the piece of long metal above a sink or bathtub that water comes out of
* Old sinks used to have two faucets: one for hot water and one for cold water. Today, most sinks have one faucet that lets us control the temperature.
bubble bath – a liquid that has a nice smell and creates many bubbles (soap mixed with water and air) when put in a bathtub with warm water
* After a long week at work, she likes to take a long, hot bath with lots of bubble bath while listening to good music and drinking a glass of wine.
every nook and cranny – including every small piece and fold, not excluding anything; including 100% of something
* When Mr. Priestley lost his glasses, we searched every nook and cranny in the house, but we couldn’t find them.
to go for (something) – to want or intend to do something; to try to make something happen
* I can’t believe you colored your hair purple! Was this really the look you were going for?
Comprehension Questions
1. Which of these would not want to use on your body?
a) Stopper.
b) Soap.
c) Bubble bath.
2. What does he mean when he says, “I ran the water”?
a) He ran to the bathroom very quickly.
b) He turned on the water and checked the temperature.
c) He made the water as hot as possible.
Answers at bottom.
What Else Does It Mean?
to soak
The verb “to soak,” in this podcast, means to be covered in water for a long period of time, usually to make something softer or to clean something: “The first part of a pedicure involves soaking your feet in warm, soapy water to make them softer.” The phrase “to soak (something) off” means to remove something by soaking it: “These pots are too hard to clean, so let’s soak off the grease by leaving them filled with soapy water overnight.” The phrase “to soak (something) up” means to absorb, or to take the liquid into something else: “Can you please give me a paper towel to soak up the spilled milk?” The same phrase can also mean to learn something very quickly and enthusiastically: “He loves school and soaks up everything the teacher says.”
to go for
In this podcast, the phrase “to go for (something)” means to want or intend to do something, or to try to make something happen: “The artist was going for a shocking image that would capture people’s attention.” The phrase “to go for (an amount)” means to be sold for a certain amount of money: “Can you believe that house went for almost $800,000?” The phrase “to go with (something)” means to match, or to look or taste good in combination with something else: “The chef said that fish goes with white wine – not red wine.” The phrase “don’t go there” is used to let another person know that one’s doesn’t want to think or talk about a particular topic: “Please don’t go there! I don’t want to even think about that.”
Culture Note
American “drugstores” (stores that sell medicine, personal products and toiletries) sell many different kinds of “bath products” (things that are used to clean one’s body). There are many types of “bar soap” (solid rectangles of soap), “body wash” (bottles of liquid soap for washing one’s body), and “shower gels” (bottles of liquid “gel” (a thick liquid) for washing one’s body). Some of the soaps are “scented” (with a nice smell) and others are “unscented” (without any scent) for “sensitive skin” (skin that becomes red, irritated, or itchy with exposure to certain chemicals).
There are also “loofahs,” which are “rough” (not soft) sponges that are rubbed against one’s skin to remove dead and “flaking” (coming off in small pieces) skin. Some loofahs are on long “handles” (the part that one puts in one’s hand) as “back scrubbers” (a long device used to help one reach the middle of one’s back). Other loofahs are shaped especially for scrubbing one’s “heels” (the large, round part on the bottom of one’s foot).
People who want to make their skin look younger might buy “exfoliating scrubs,” or special creams with very small, hard pieces that are rubbed against the skin to remove old or dead skin and “reveal” (show) the newer, younger-looking skin underneath.
Soap “tends to be” (often is) “drying,” meaning that one’s skin becomes very dry if one uses a lot of soaps and heavy scrubbing, so drugstores also sell many types of “lotions” (creamy liquids that make one’s skin feel softer) that are supposed to be “applied” (put on one’s body) immediately after bathing or showering.
Comprehension Answers
1 - a
2 - b
Dialogue/Story
Slow Speed begins at: 1:19
Explanation begins at: 3:12
Normal Speed begins at: 14:44
Complete Transcript
Welcome to English as a Second Language Podcast number 510: Taking a Shower or Bath.
This is English as a Second Language Podcast episode 510. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there today to download a Learning Guide that will help you improve your English even faster. You can become a member of ESL Podcast, or if you’d like to support our efforts, send us a small donation. More information can be found on our website.
This episode is a story about someone taking a shower or a bath. When your body is dirty, you have to clean it, and that’s what we’re going to do in this episode. Let’s get started.
[start of story]
I spent the day helping my friend, Babbit, on his farm. When I got home, my wife said, “You stink!” I headed straight for the shower.
I ran the water, closed the shower curtain, and adjusted the showerhead. I worked the soap into a lather and scrubbed from head to toe. I rinsed off the soap and toweled off.
When I went back into the living room, my wife said, “You still stink! You need to soak in a bath!”
I went back into the bathroom, put the stopper in the bathtub, and turned on the faucet. I didn’t want to take any chances. I took some of my wife’s bubble bath and poured it into the bathtub. When the bath was ready, I got in. I soaked for a half hour and I washed every nook and cranny.
When I went back into the living room, my wife said, “Wow, you smell as pretty as a flower!” That wasn’t exactly what I was going for, but I’d rather smell like flowers than pigs!
[end of story]
Our story begins with me saying that I spent the day helping my friend, Babbit, on his farm. A “farm” is a place where you may have animals, you may be growing food in the ground; it’s a place outside of the city, usually. When I got home, my wife said, “You stink!” The verb “to stink” is an informal way of saying that someone smells bad, they have an unpleasant smell or an unpleasant odor. “Odor” (odor) is the same as smell. So, when someone doesn’t smell very good because they’re dirty, you could say, “You stink.” However, it’s a very strong thing to say; it’s a very negative thing to say, so you would not want to say that to anyone that you didn’t know very well. We also use the verb “to stink” to mean to be poor at something, to not be very good at something. I could say, “I stink at chess,” meaning I’m not a very good chess player.
But in this case, when my wife says that I stink, she means I smell bad, so I headed straight for the shower. “To head for (something)” is to go in the direction of. When I say I headed straight for the shower, I mean I went directly to the shower; I didn’t do anything else first. That’s the meaning of the word “straight” here. A “shower” is the part of the bathroom where you stand under water to get clean; you stand up and the water goes over you to clean you. I say that I ran the water. “To run the water” means to turn the water on and, usually, wait until the water gets warm enough. So, “to run the water” means to turn the water on. I ran the water, and then I closed the shower curtain. The “shower curtain” is a large piece of plastic that hangs around the shower, separates the shower from the rest of the bathroom to prevent the water from going outside. Some showers have doors, and you slide the door back and forth, often made of glass. Other showers have a shower curtain. A curtain is also a word we use to describe things that you put over your windows to keep the light out; those are also curtains, when they’re made of some kind of material – some kind of fabric. I also adjusted the showerhead. The “showerhead” is the piece of metal that the water comes out of in a shower. It’s attached to a pipe in the wall where the water comes from, and it’s what sprays the water over you – that is, it distributes the water over you. That’s the showerhead.
I said that I worked the soap into a lather. “To work the soap” means I did something to the soap; in this case, I put the soap on my skin and I moved it back and forth – I rubbed it until it was in the form of lather. “Lather” (lather) is when you have a lot of soap bubbles on your skin so that it looks white. Or for example, you could put soap on your hands, and if you move them together very quickly you will work the soap into a lather.
I scrubbed (meaning I rubbed very hard in order to get clean) from head to toe. The expression “from head to toe” means from the top of your body where your head is to the bottom of your body where your foot and toe are. Your “toes,” of course, are the five little digits that come out of your foot. Then, I rinsed off the soap and toweled off. “To rinse (something)” means to pour water on it to, usually, get rid of the soap that you are using to clean something. “To rinse off” means the same; we use “off” here for emphasis. It’s very common in English to add a preposition like “off” after a verb to give it the idea of motion – of action. In this case, to rinse off means to put the water on me so that the soap (that solid or liquid substance that you use to clean something) goes off of my body. So, I rinsed off the soap and I toweled off. “To towel off” means to take something to dry your body, what we call a “towel,” which is a big piece of fabric – of material that you use to dry something with. “To towel off” is the same as “to dry off,” to take something and remove water from something else; in this case, from my body.
When I went back into the living room after showering, my wife said, “You still stink!” In other words, I did not get rid of all of the bad smell. She says, “You need to soak in a bath!” “To soak” (soak), here, means to be covered in water for a long period of time, usually we do that to make something easier to clean. So if you are cooking and you have a pan that is very dirty, you may put water on it – or water in it and let the pan soak – use the water to help make the pan easier to clean. So maybe an hour later, you would come back and then clean the pan. Well here, we’re talking about soaking your body because it’s so dirty, and so you get into what we call a “bathtub,” which is a large, usually rectangular container in the bathroom that you can sit in or lie down in and put water over you.
I went back into the bathroom then and put the stopper in the bathtub. The “stopper” is a small piece of metal or plastic that you put in the hole that is at the bottom of the bathtub or of a sink so that water can’t flow out; the water stays in the bathtub or the sink. If you want to take a bath, you have to put a stopper there so that you have water inside the bathtub. I turned on the faucet after that. The “faucet” (faucet) is a long, metal piece that is above the sink or bathtub that the water comes out of. So, “to turn on the faucet” means to allow the water to come out and fill up the bathtub. I said, “I didn’t want to take any chances,” I wanted to be sure I was going to be clean. So, I took some of my wife’s bubble bath and poured it into the bathtub. “Bubble bath” is a liquid that smells nice that women sometimes, or children, put in their bath to make them smell nice. It’s not something that a man would normally do, but because I was so dirty I wanted to make sure I smelled good.
When the bath was ready, then I got in. I soaked for a half hour and I washed every nook and cranny. The expression “nook (nook) and cranny (cranny)” means small places, but here, when we say “I washed every nook and cranny,” we mean you did a hundred percent of everything; you cleaned everything. You might say, “I was looking for my car keys, because I lost them. I looked in every nook and cranny of my house,” meaning I looked everywhere. So here, we’re saying that I cleaned every part of my body.
When I went back into the living room, my wife said, “Wow, you smell as pretty as a flower!” I say that that wasn’t exactly what I was going for. “To go for,” in this case, means what I wanted, what I intended, what I was trying to make happen. I wasn’t trying to smell pretty, I was just trying not to smell bad. “To go” plus a preposition is a very common expression in English; take a look at our Learning Guide for some more explanations of that, as well as the verb – or the word “soak.” I said, “I’d rather smell like flowers than pigs!” Remember, I was working on a farm, and so one of the animals that you have on a farm is a pig, which people think tends to smell badly.
Now that I’m all clean and smelling like a flower, let’s listen to the dialogue again at a normal speed.
[start of story]
I spent the day helping my friend, Babbit, on his farm. When I got home, my wife said, “You stink!” I headed straight for the shower.
I ran the water, closed the shower curtain, and adjusted the showerhead. I worked the soap into a lather and scrubbed from head to toe. I rinsed off the soap and toweled off.
When I went back into the living room, my wife said, “You still stink! You need to soak in a bath!”
I went back into the bathroom, put the stopper in the bathtub, and turned on the faucet. I didn’t want to take any chances. I took some of my wife’s bubble bath and poured it into the bathtub. When the bath was ready, I got in. I soaked for a half hour and I washed every nook and cranny.
When I went back into the living room, my wife said, “Wow, you smell as pretty as a flower!” That wasn’t exactly what I was going for, but I’d rather smell like flowers than pigs!
[end of story]
The script for this episode was by someone who never stinks at writing scripts, or any other way, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to stink – to smell bad; to have an unpleasant odor
* Our fridge stinks! When was the last time we cleaned it?
shower – the part of a bathroom where one stands under water to get clean, usually surrounded by walls and a door or curtain
* Becca keeps shampoo and soap in her shower.
to run the water – to turn the water on and let it move, usually while waiting for it to get warmer
* On cold winter mornings, they have to run the water for two minutes before it starts to get warm.
shower curtain – a large piece of fabric or plastic that hangs between a shower and the rest of the bathroom to keep the water inside the shower and keep the rest of the bathroom dry.
* The entire bathroom is wet because there is a hole in the shower curtain.
showerhead – the piece of metal that water comes out of in a shower, falling over one’s head, used to control how hard or soft the water is when it falls
* They bought a special showerhead that makes the water feel like a massage.
lather – a group of many soap bubbles on one’s skin, so that it seems to be white, created by rubbing soap and water between one’s hands
* The little boy laughed when he learned how to work soap into a lather.
to scrub – to rub something very hard to clean it
* After the children came indoors with their dirty shoes on, I had to scrub the floor to get it clean again.
from head to toe – over one’s entire body; over all parts of one’s body, not missing any spots
* We had to walk home in the rain, so we were wet from head to toe.
to rinse off – to move water over one’s body or something else to remove soap and leave it clean
* As she was rinsing off the wine glass, it fell out of her hands and broke.
soap – a solid or liquid substance that is rubbed against one’s body or something else to clean it and is removed by rinsing it with water
* Restaurant workers are supposed to wash their hands with soap and warm water after using the restroom.
to towel off – to dry off; to move a large piece of soft fabric over one’s wet body to make it dry
* Harriet forgot to bring a towel to the pool, so instead of toweling off, she just waited for the sun and warm air to dry her body.
to soak – to be immersed in water; to be covered in water for a long period of time, usually to make something softer or easier to clean
* They soaked the beans in water overnight before boiling them.
stopper – a small piece of metal or plastic that is placed in the hole in the bottom of a sink or bathtub so that water cannot flow out, used to fill the sink or bathtub with water
* Filippe put the stopper in the sink and filled it with warm water before shaving.
bathtub – the large, rectangular, porcelain container in a bathroom, used for a person to sit or lie down in when it is filled with water
* Delilah’s mother filled the bathtub with soapy water and toys.
faucet – the piece of long metal above a sink or bathtub that water comes out of
* Old sinks used to have two faucets: one for hot water and one for cold water. Today, most sinks have one faucet that lets us control the temperature.
bubble bath – a liquid that has a nice smell and creates many bubbles (soap mixed with water and air) when put in a bathtub with warm water
* After a long week at work, she likes to take a long, hot bath with lots of bubble bath while listening to good music and drinking a glass of wine.
every nook and cranny – including every small piece and fold, not excluding anything; including 100% of something
* When Mr. Priestley lost his glasses, we searched every nook and cranny in the house, but we couldn’t find them.
to go for (something) – to want or intend to do something; to try to make something happen
* I can’t believe you colored your hair purple! Was this really the look you were going for?
Comprehension Questions
1. Which of these would not want to use on your body?
a) Stopper.
b) Soap.
c) Bubble bath.
2. What does he mean when he says, “I ran the water”?
a) He ran to the bathroom very quickly.
b) He turned on the water and checked the temperature.
c) He made the water as hot as possible.
Answers at bottom.
What Else Does It Mean?
to soak
The verb “to soak,” in this podcast, means to be covered in water for a long period of time, usually to make something softer or to clean something: “The first part of a pedicure involves soaking your feet in warm, soapy water to make them softer.” The phrase “to soak (something) off” means to remove something by soaking it: “These pots are too hard to clean, so let’s soak off the grease by leaving them filled with soapy water overnight.” The phrase “to soak (something) up” means to absorb, or to take the liquid into something else: “Can you please give me a paper towel to soak up the spilled milk?” The same phrase can also mean to learn something very quickly and enthusiastically: “He loves school and soaks up everything the teacher says.”
to go for
In this podcast, the phrase “to go for (something)” means to want or intend to do something, or to try to make something happen: “The artist was going for a shocking image that would capture people’s attention.” The phrase “to go for (an amount)” means to be sold for a certain amount of money: “Can you believe that house went for almost $800,000?” The phrase “to go with (something)” means to match, or to look or taste good in combination with something else: “The chef said that fish goes with white wine – not red wine.” The phrase “don’t go there” is used to let another person know that one’s doesn’t want to think or talk about a particular topic: “Please don’t go there! I don’t want to even think about that.”
Culture Note
American “drugstores” (stores that sell medicine, personal products and toiletries) sell many different kinds of “bath products” (things that are used to clean one’s body). There are many types of “bar soap” (solid rectangles of soap), “body wash” (bottles of liquid soap for washing one’s body), and “shower gels” (bottles of liquid “gel” (a thick liquid) for washing one’s body). Some of the soaps are “scented” (with a nice smell) and others are “unscented” (without any scent) for “sensitive skin” (skin that becomes red, irritated, or itchy with exposure to certain chemicals).
There are also “loofahs,” which are “rough” (not soft) sponges that are rubbed against one’s skin to remove dead and “flaking” (coming off in small pieces) skin. Some loofahs are on long “handles” (the part that one puts in one’s hand) as “back scrubbers” (a long device used to help one reach the middle of one’s back). Other loofahs are shaped especially for scrubbing one’s “heels” (the large, round part on the bottom of one’s foot).
People who want to make their skin look younger might buy “exfoliating scrubs,” or special creams with very small, hard pieces that are rubbed against the skin to remove old or dead skin and “reveal” (show) the newer, younger-looking skin underneath.
Soap “tends to be” (often is) “drying,” meaning that one’s skin becomes very dry if one uses a lot of soaps and heavy scrubbing, so drugstores also sell many types of “lotions” (creamy liquids that make one’s skin feel softer) that are supposed to be “applied” (put on one’s body) immediately after bathing or showering.
Comprehension Answers
1 - a
2 - b