= 0511
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 511: Getting Plastic Surgery.
This is English as a Second Language Podcast episode 511. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
If you go to our website, eslpod.com, you can download a Learning Guide for this episode, an to 8- to 10-page guide that contains our vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and, most importantly, a complete transcript of everything we say on this episode.
This episode is a dialogue between George and Joan about “plastic surgery,” when people have medical procedures (surgeries) on their body to change the way it looks. Let’s get started.
[start of dialogue]
George: What are you doing?
Joan: I’m looking through these magazines to try and decide which plastic surgery procedures I should have next year.
George: You’re not thinking of going under the knife.
Joan: Yes, I am. I’ve always wanted to improve on the way I look, and I’m tired of these wrinkles and sagging skin. I want to look 25 again!
George: That’s ridiculous. Nobody who is 45 can look 25. People who get Botox, have facelifts, or tummy tucks look weird.
Joan: That’s because they didn’t go to the best plastic surgeons. I won’t make that mistake. Help me decide. Should I get liposuction and a nose job, or should I go all out and get breast implants, too?
George: I think you’ve gone off the deep end. We’ve been friends for over 20 years and you don’t need any cosmetic surgery. You’re perfect the way you are.
Joan: You can’t be serious!
George: I’m dead serious, and if you get all of that plastic surgery, you’ll look like an over-the-hill Barbie doll, and I’m not going to be seen in public with you.
Joan: What’s wrong with a little plastic surgery? I just want to feel better about myself.
George: You don’t need plastic surgery to do that. You just need to spend more time with me and your other friends who like you just the way you are!
Joan: Sagging skin and all?
George: What sagging skin?
Joan: I feel younger already.
[end of dialogue]
The dialogue begins with George saying to Joan, “What are you doing?” Joan says, “I’m looking through these magazines to try and decide which plastic surgery procedures I should have next year.” “Plastic surgery,” sometimes called “cosmetic surgery,” is one of many different medical procedures that involve cutting into your skin, usually to make you more attractive or more beautiful. If you think your nose is too big, you may have plastic surgery to make your nose smaller. My wife thinks my mouth is too big, so she wants me to have plastic surgery to make it smaller!
Joan is interested in plastic surgery, which is very popular especially in cities like Los Angeles where everyone is trying to look beautiful, especially those who are on television or the movies. I, of course, am on a podcast, so you can guess how ugly I am!
George says, “You’re not going under the knife.” The expression “to go under the knife” means to have surgery; not plastic surgery exclusively, it could be any kind of surgery. If you had a car accident you might have to have surgery, where the doctor cuts open your body. That’s going under the knife. Plastic surgery is just one type of surgery.
Joan says, “Yes, I am. I’ve always wanted to improve on the way I look (to make myself look better), and I’m tired of these wrinkles and sagging skin.” “Wrinkles” are small lines (or folds, we might call them) in your skin, usually caused by age. As you get older, you have more wrinkles. They may also be caused by sun damage. People who like to go out into the sun and get a tan so they look younger, well, the problem is later in life then you have even more wrinkles and you look even older. “Sagging skin” is skin that hangs down; it is not as tight as it used to be. It would be, for example, loose skin on your face, rather than having your skin that was tight, as you would see among younger people. Not me, people who are really young! The word “sag” (sag) has several different meanings in English; take a look at that Learning Guide for some additional explanations.
Joan says, “I want to look 25 again.” George says, “That’s ridiculous. Nobody who is 45 can look 25.” That’s true; I’m 45 and I will never look 25. In fact, even when I was 25, I didn’t look 25! George says, “People who get Botox, have facelifts, or tummy tucks look weird (look strange).” “Botox” (Botox) is a chemical substance that is injected or put into your skin on your face so that you have fewer wrinkles. It makes your skin smoother. It also makes your skin unable to move so that when you smile or try to have some expression on your face, your skin just stays the way it is; it doesn’t move. It looks very strange. It’s very popular among a lot of people here in Hollywood; they get Botox, especially women, but not just women. “To have a facelift” (one word) is to remove lose skin on your face, making it tighter. The idea is to try to make you look younger. A “tummy tuck” is a surgical procedure that cuts away fat and skin from your abdomen – from what we call your tummy, which is in the middle part of your body. The idea of a tummy tuck is to make you look thinner.
Joan says that people who get Botox, have facelifts, or tummy tucks look weird because they don’t go to the best plastic surgeons. A “surgeon” is someone who does surgery. A “plastic surgeon” is a medical doctor who does surgeries that make people look better or younger. Joan says, “I won’t make that mistake,” I won’t go to any thing but the best plastic surgeons. If you ever are in Los Angeles and you pick up one of the weekly entertainment magazines or newspapers, which are often distributed for free at coffee shops and restaurants, you can open up the newspaper or magazine and you can see advertisements from doctors who are plastic surgeons. It’s sort of funny; they’re so popular here in Los Angeles that they advertise in the newspaper. Usually, the advertisement has a beautiful woman in a bikini who has a very – how should we say – large top of her body and a very small bottom of her body, obviously the result of plastic surgery.
Joan says, “Help me decide (meaning help me make a decision George). Should I get liposuction and a nose job, or should I go all out and get breast implants?” “Liposuction” is a type of plastic surgery that removes unwanted fat from your belly – your abdomen, your tummy. It pulls the fat out of your body so that you look less fat. The “nose job” is when you get surgery to make your nose smaller or to make it have a different shape. The expression “to go all out” means to do 100 percent of something, to do everything possible, to go to the extreme, to try very hard to do something. These are all meanings of “to go all out.” “They’re going to go all out on their wedding,” they’re going to invite 500 people and spend 50,000 dollars – they’re going to go all out. “To go out” has several different meanings in English; take a look at the Learning Guide for some additional explanations of that phrasal verb.
So, Joan is wondering if she should go all out and get breast implants. “To implant (something)” is to put something underneath your skin or in your body. “Breast implants,” for women usually, are when the woman’s breasts (her chest; the top front of her body) are changed, usually made bigger by putting in little bags of a type of plastic – of silicone. When I was talking about the advertisements for the plastic surgeons in the newspapers in Los Angeles, well, usually those are of women in bikinis who have breast implants.
George says to Joan, “I think you’ve gone off the deep end.” “To go off the deep end” means to go crazy, to stop being realistic. George says, “We’ve been friends for over 20 years and you don’t need any cosmetic surgery.” Remember, cosmetics surgery is the same as plastic surgery. “You’re perfect the way you are.” Joan says, “You can’t be serious (meaning you’re kidding, right?)!”
George says, “I’m dead serious.” When someone says they’re “dead serious,” they’re saying they’re very serious, they’re extremely serious, they’re not joking at all. George says, “if you get all of that plastic surgery, you’ll look like an over-the-hill Barbie doll.” There’s two expressions there: first, “over the hill” means old; it’s an informal expression, somewhat of a negative expression. If somebody says, “You’re over the hill,” they mean that you have already gotten to the top of your life, and now you’re on the second part of your life. You’re old, in other words. That’s what my nieces and nephews tell me, I’m over the hill: “You’re over the hill Uncle Jeff!” A “Barbie doll” is a child’s toy, usually a young girl’s toy. It’s a small doll that has, usually, blonde hair. It’s been around for several years, since probably the middle part of the 20th century. They’re very popular. Usually they are dolls that are very beautiful women with large breasts and a small waist – a small bottom. George says, “I’m not going to be seen in public with you.”
Joan says, “What’s wrong with a little plastic surgery? I just want to feel better about myself.” And, of course, that’s one unfortunate reason why some women have plastic surgery, I think. George says, “You don’t need plastic surgery to (feel better about yourself). You just need to spend more time with me and your other friends who like you just the way you are!” Joan says, “Sagging skin and all?” The phrase “and all” is used to emphasize that something is included in the discussion. It would be another way of “even my sagging skin.” George says, “What sagging skin?” Joan says, “I feel younger already,” meaning telling me that makes me feel younger.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
George: What are you doing?
Joan: I’m looking through these magazines to try and decide which plastic surgery procedures I should have next year.
George: You’re not thinking of going under the knife.
Joan: Yes, I am. I’ve always wanted to improve on the way I look, and I’m tired of these wrinkles and sagging skin. I want to look 25 again!
George: That’s ridiculous. Nobody who is 45 can look 25. People who get Botox, have facelifts, or tummy tucks look weird.
Joan: That’s because they didn’t go to the best plastic surgeons. I won’t make that mistake. Help me decide. Should I get liposuction and a nose job, or should I go all out and get breast implants, too?
George: I think you’ve gone off the deep end. We’ve been friends for over 20 years and you don’t need any cosmetic surgery. You’re perfect the way you are.
Joan: You can’t be serious!
George: I’m dead serious, and if you get all of that plastic surgery, you’ll look like an over-the-hill Barbie doll, and I’m not going to be seen in public with you.
Joan: What’s wrong with a little plastic surgery? I just want to feel better about myself.
George: You don’t need plastic surgery to do that. You just need to spend more time with me and your other friends who like you just the way you are!
Joan: Sagging skin and all?
George: What sagging skin?
Joan: I feel younger already.
[end of dialogue]
The script for this episode was written by someone who never goes off the deep end, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
plastic surgery / cosmetic surgery – one of many medical procedures that involves cutting into one’s skin to make one more attractive or beautiful
* She’s thinking about having plastic surgery to make her nose smaller.
to go under the knife – to have surgery; to have a medical procedure that involves cutting into one’s skin
* After the car accident, Kashif had to go under the knife three times for his knee and shoulder injuries.
wrinkle – a small fold or line in one’s skin, usually caused by age and sun damage
* Norah looked in the mirror and was surprised to see so many wrinkles around her eyes.
sagging – hanging down and stretched longer than something should be
* Jim’s pants are sagging. I think it’s because he has lost over 50 pounds in the past year.
Botox – a chemical substance that is injected into the skin on one’s face to reduce the appearance of wrinkles, making the skin smoother
* Have you considered using Botox to get rid of the lines on your forehead?
facelift – a surgical procedure that removes loose skin on one’s face, making one’s face look younger
* I wonder what percentage of movie stars have facelifts as they start to get older?
tummy tuck – a surgical procedure that cuts away unwanted fat and skin on one’s abdomen (belly) to make one look thinner
* Janice decided to get a tummy tuck so that she’d look better in her swimsuit.
plastic surgeon – a medical professional who does surgeries to improve people’s physical appearance, even if there are no health benefits
* Lana became a plastic surgeon to help people with face injuries.
liposuction – a surgical procedure that removes unwanted fat from one’s abdomen (belly) by using suction, pulling the fat out of one’s body
* Mohamed was overweight and had liposuction, but he continued to eat too much food, so within a year he had a big belly again.
nose job – a surgical procedure to change the shape of one’s nose, usually to make it smaller or straighter
* I hate my big nose! Do you think I should get a nose job?
to go all out – to do 100% of something; to do all of something, not missing or skipping anything; to do something to an extreme; to try very hard to do something
* They went all out for their wedding, inviting more than 500 guests and serving them the best food and wine available.
breast implants – bags of silicone that are placed inside a woman’s breasts through a surgical procedure to make her breasts bigger
* Do men think women with breast implants are more attractive?
to go off the deep end – to go crazy; to stop thinking or acting realistically or normally
* When Shelby saw how inexpensive stocks were, she went off the deep end and spent all her money on stocks, not realizing how risky the investment was.
dead serious – extremely serious; not joking; speaking the truth
* At first we thought he was joking about wanting to start his own business, but now we realize he was dead serious.
over-the-hill – old; past the best part of one’s life
* On Hal’s 50th birthday, his employees decorated his office with balloons that read “over-the-hill.”
Barbie doll – a children’s toy; a small plastic doll that looks like a very beautiful woman, with large breasts, a small waist, and wide hips; a woman who works hard to make her body perfect
* Yevgeny won’t let his daughter play with Barbie dolls because he thinks it will make her unhappy with her own body.
(something) and all – a phrase used to emphasize that something is included in the discussion
* It’s time that we got rid of all this stuff we never use, CDs and all.
Comprehension Questions
1. Which of these treatments doesn’t require going under the knife?
a) A Botox injection.
b) A facelift.
c) A tummy tuck.
2. Which of these treatments would an overweight person be most interested in?
a) Liposuction.
b) A nose job.
c) Breast implants.
Answers at bottom.
What Else Does It Mean?
sagging
The word “sagging,” in this podcast, means hanging down and stretched longer than something should be: “Have you noticed the sagging skin around my eyes?” Something that is “sagging” can also be weak or slow: “We need to find out why our company’s sales have been sagging.” As a verb, “to sag” means to be pulled down by something heavy: “The tree branches are sagging under the weight of so many apples.” The verb “to sag” can also mean to sit heavily, deep into a chair, especially when one is tired: “He sagged into his favorite chair at the end of the long day.” Finally, the acronym “SAG” represents the Screen Actors’ Guild, which is a professional group for American actors and actresses who work in television and the movies: “Are you a member of SAG?”
to go all out
In this podcast, the phrase “to go all out” means to do 100% of something, not missing or skipping anything, or to do something to an extreme: “They went all out decorating their daughter’s room. Absolutely everything is pink!” The phrase “to go out” means to leave one’s home to do something: “Do you go out most Friday nights?” Or, “I’m going out to get some milk.” The phrase “to go out with (someone)” means to date someone or to have a romantic relationship with someone: “Did you hear that Charity is going out with Albert?” Finally, the phrase “to go in to (something)” means to begin working in a certain field or to start a certain type of business: “Why did you decide to go into car sales?” Or, “Do you think our company should go into the book publishing business?”
Culture Note
Doctors have to meet many “requirements” (things that must be done) before they can “practice” (work as doctors) in the United States. They have to complete a certain amount of general education, general medical education, and education in their “specialty” (an area of specialization, or the type of medicine a doctor focuses on). Doctors also have to complete a “residency” (a period of time where a new doctor works under the close supervision of another, more experienced doctor).
Many “boards” (professional organizations) “certify” (officially say that someone has met specific requirements) that someone has met published standards in particular specialties. These are usually a combination of education and experience, as well as an exam. When the doctor has been certified by a board, we say that he or she is “board certified.” Certification usually lasts only a few years, so the doctors must recertify. This may require courses for “continuing education” (education after one has already earned the degree) and additional exams.
The American Board of Medical Specialties helps 24 different boards develop standards for different medical specialties. One of them, the American Board of Plastic Surgery (ABPS) certifies plastic surgeons in the United States. If you want to find a good plastic surgeon, ABPS can help you find a board-certified plastic surgeon in your area. Most people agree that working with a board-certified plastic surgeon – or any other type of medical professional – is a good idea. If you don’t select a board-certified doctor, you “run the risk” (accept the chance that something bad might happen) of selecting a doctor who doesn’t have enough experience or education to correctly perform the surgery or procedure you need.
Comprehension Answers
1 - a
2 - a