= 0534
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 534: Types of Guns and Weapons.
This is English as a Second Language Podcast episode 534. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that will help you improve your English faster. You can download a Learning Guide by becoming a Learning Guide member, and help support this podcast as well.
This episode is called “Types of Guns and Weapons,” somewhat of an unusual topic for us. It’s going to be a dialogue between Bobbie, who is a woman in this dialogue, and Emmanuel. Let’s get started.
[start of dialogue]
Bobbie: I’ve always pegged you as the non-violent type. What’s with your fascination with guns and that sort of thing?
Emmanuel: I come from a long line of military officers and I grew up with all of it. Believe it or not, I learned how to fire pistols and rifles before I was 10 years old, and by the time I was 14, I was a pretty good shot.
Bobbie: I hope you fired at targets and not at people.
Emmanuel: No, not people. We did do some hunting when I was young, but I mainly honed my skills with target practice.
Bobbie: I’d like to try target practice – with a machine gun or a grenade launcher! I’m sure I’d at least hit something.
Emmanuel: Yeah, right. What really interests me are the big weapons, like missiles – you know, like antiballistic missiles and torpedoes.
Bobbie: You can have all of the missiles you want. I’ll be hiding in the tank!
[end of dialogue]
Bobbie begins by saying to Emmanuel, “I’ve always pegged you as a non-violent type.” “To peg (peg) (someone) as (something)” means to believe that that person has certain characteristics or will behave in a certain way. For example, you might say, “I’ve always pegged you as a good swimmer,” meaning I’ve always thought that you were or believed that you were a good swimmer. You could also say, “I always pegged him as a great decision-maker,” someone who could make good decisions. Bobbie says that she’s always pegged Emmanuel as the non-violent type. “Non-violent” means you don’t believe that people should hurt each other, usually that means you’re not interested in things like guns and weapons. A “weapon” is merely anything you use to hurt someone or to protect yourself, so a knife could be a weapon for example. A gun is a weapon.
Bobbie then says, “What’s with your fascination with guns and that sort of thing?” “What’s with” is a construction we use to mean tell me more about, or why do you do that, I don’t understand why you are acting this way. Someone may be feeling sad and they may be crying, and you may say, “What’s with the crying? What’s wrong?” There’s something of a challenge there, too, when we use this expression sometimes: “What’s with your bad attitude?” It’s almost like you’re puzzled – you’re surprised, and perhaps you’re a little critical, though not always.
So, Bobbie says, “What’s with your fascination (your extreme interest) with guns and that sort of thing?” “That sort of thing” means related things. Emmanuel says, “I come from a long line of military officers.” He’s trying to explain why he’s interested in guns. He says, “I come from a long line of military officers.” The expression “to come from a long line of (something)” means that you had relatives (your father, your grandfather, your great-grandfather, your great-great-grandfather) or other people who came before you in your family who were interested in some particular area or who had a certain job. For example, I come from a long line of plumbers. My grandfather was a plumber, my great-grandfather was a plumber, my great-great-grandfather was a plumber, my uncles were all plumbers. My father was the only one – the only male in his family that wasn’t a plumber, but I could say I come from a long line of plumbers. I could say that – I don’t actually say that, especially to my wife, because then she wants me to fix the sink!
Emmanuel, however, comes from a long line of “military officers,” people in the army, the navy – soldiers. An “officer” is someone who is in charge soldiers; so a lieutenant, a sergeant, a captain, a general, these would all be military officers. Emmanuel says, “I grew up with all of it,” meaning it was something I saw as a young child. He says, “Believe it or not,” an expression we use when we’re about to say something that the person might not believe, something surprising, “Believe they’re not,” he says, “I learned how to fire pistols and rifles before I was 10 years old.” “To fire a gun” means to make the gun shoot, to pull what we call the “trigger,” moving your finger so that the bullet will leave the gun. That’s to fire a gun. This particular gun is a pistol. A “pistol” is a small gun that you can hold in your hand. Someone who is robbing a bank (who is trying to steal money from a bank) might have a pistol. A “rifle” is a large, long gun, usually used for hunting. It can also be used in a war, however.
So, Emmanuel learned how to fire – how to use pistols and rifles even before he was 10 years old, “and by the time I was 14, I was a pretty good shot.” “To be a good shot” means that you can use a gun or a rifle very well. You can, for example, hit a bird flying up in the air with just one bullet – one shot. That would be a good shot. In the police and in the military forces they train soldiers to use guns. If you are very good at what you do, if you’re an excellent what we would call “marksman” or “markswoman,” then they would call you a “sniper” (sniper) or a “sharpshooter.” These are both terms used to describe someone who is an excellent shot, not just a good shot, a very good shot.
Bobbie says, “I hope you fired at targets and not at people.” When we talk about shooting guns, a “target” is an object or a thing that you try to hit with the bullet of your gun. You can go, for example, to special places where they have targets that are small circles; we would call them “concentric” circles, one circle inside of a larger circle, inside of a larger circle, and you try to hit the middle of this circle. That would be a target. She is saying here that she hopes that Emmanuel was firing at (was shooting at) targets and not at people.
Emmanuel says, “No, not people. We did do some hunting when I was young.” Notice here, he could of just said “we hunted when I was young,” but to express the past tense he instead uses “we did do some hunting.” This is to emphasize, usually in a case where you are making a distinction so that the other person understands well, no, I didn’t do this, but I did do this. “Hunting” is when you go out and try to kill animals. Hunting is legal in many states; it’s only legal, usually, for a certain number of weeks and during a certain time of year. The fall is a very common time when there is hunting season. This is especially popular in states such as Minnesota and Wisconsin, where it is legal during certain times of the year to go and hunt deer and hunt certain kinds of birds. I know people who have done this; they own guns and they get a license to go and hunt. You need to get a license – you need to get permission from the government.
Emmanuel says, “We did do some hunting when I was young, but I mainly (meaning I mostly) honed my skills with target practice.” “To hone (hone) your skills” means to improve your ability to do something, to get better at something. You might say, “I’m going to hone my typing skills.” I’m going to sit at my keyboard and improve my typing. That would be to hone your skills, to make them better. Emmanuel says that he honed his skills with a gun by doing target practice. “Target practice” is shooting at targets we talked about before. There are places where you can go that are called “shooting ranges,” and you can go and practice shooting at these targets. There are clubs – gun clubs that you can join that have these special buildings that have target practice shooting ranges.
Bobbie says, “I’d like to try target practice – with a machine gun or a grenade launcher!” A “machine gun” is a large gun that fires many bullets automatically and very quickly. It’s the sort of thing that you would use in a war; it’s not the sort of thing you would normally use, for example, with the police. Although, if you remember the 1920s and 30s in the United States, and ever saw any of the movies about the “gangsters,” people who were professional criminals, sometimes in the movies you see them with machine guns. Of course, sometimes you saw them in real life with machine guns! That is a criminal use of machine guns. But, the idea here is that Bobbie would have to use a machine gun because, she says, “I’m sure I’d at least hit something,” meaning she’s not a very good shot, so she would need something like a machine gun in order to hit something – in order to have the bullet go through something. A “grenade” is a small, hand-held bomb that is usually used by soldiers in a war. A “grenade launcher” is a machine that throws these bombs a long distance.
Emmanuel says, “Yeah, right. What really interests me are the big weapons, like missiles – you know, like antiballistic missiles and torpedoes.” We’ve already talked about what weapons are, anything you use to hurt someone else or something else. A “missile” is a bomb that is sent through the air at a long distance. Sometimes it is dropped by a plane, sometimes it is “launched,” it is shot from the ground. An “antiballistic missile” is a bomb that is made to hit other bombs that are in the air, so it’s sort of a missile to stop another missile. A “torpedo” is a missile that shot by a “submarine,” a ship that is underneath the water.
Bobbie says, “You can have all the missiles you want. I’ll be hiding in the tank!” A “tank” (tank) is a very large, heavy vehicle. It’s like a big truck that is used by the army, and it has a large gun on the top of it for fighting. “Tank,” like the word “fire” we used earlier, has a couple of different meanings in English, so take a look at the Learning Guide for some additional explanations.
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Bobbie: I’ve always pegged you as the non-violent type. What’s with your fascination with guns and that sort of thing?
Emmanuel: I come from a long line of military officers and I grew up with all of it. Believe it or not, I learned how to fire pistols and rifles before I was 10 years old, and by the time I was 14, I was a pretty good shot.
Bobbie: I hope you fired at targets and not at people.
Emmanuel: No, not people. We did do some hunting when I was young, but I mainly honed my skills with target practice.
Bobbie: I’d like to try target practice – with a machine gun or a grenade launcher! I’m sure I’d at least hit something.
Emmanuel: Yeah, right. What really interests me are the big weapons, like missiles – you know, like antiballistic missiles and torpedoes.
Bobbie: You can have all of the missiles you want. I’ll be hiding in the tank!
[end of dialogue]
The script for this episode was written by someone who has honed her skills for many years at writing, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time, won’t you, on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to peg (someone) as (something) – to believe that someone has certain characteristics or will behave a certain way
* I always pegged Sinclair as a great decision-maker, so I was really surprised by his indecisiveness yesterday.
non-violent – not believing that people should hurt each other, and uninterested in guns and other weapons
* They only let their children watch non-violent movies that won’t scare them.
fascination – an extreme interest; having a strong feeling toward and an interest in something
* Growing up on an island, he has always had a fascination with dolphins and whales.
to come from a long line of (something) – to be descended from many people who have had the same job; for many of one’s relatives to have worked in the same field
* Although Almendra comes from a long line of musicians, she doesn’t know how to play any musical instruments.
military officer – a person who has a leadership role in the army, navy, air force, or a similar organization
* He became a military officer in 1983, and now he is an army general.
to fire – to move one’s finger while holding a gun so that it makes a loud noise and sends out a bullet that moves very quickly; to make a gun or another weapon work
* Bruno fired his gun at the birds several times, but he didn’t hit anything.
pistol – a small gun that one can hold in just one hand
* A pistol is very small, but deadly.
rifle – a very long gun that one shoots by putting the back end against one’s shoulder
* Last weekend, they took their rifles into the woods, but they didn’t find any deer.
good shot – a person who knows how to use a gun and is able to make the bullet go where he or she wants it to go
* She’s a very good shot and can hit almost anything from 300 feet away.
target – an object that people try to hit with a gun or arrow to improve their aim (their ability to send something in a particular direction)
* Trainees have to spend many hours shooting at targets before they can become police officers.
hunting – the practice of killing animals, usually with a gun or arrow, either for food or for fun
* Alejandra hates all types of hunting, because she thinks killing animals is wrong.
to hone (one’s) skills – to improve one’s ability to do something; to get better at doing something
* Joachim studied in Paris for a year to hone his cooking skills.
target practice – the activity of shooting at targets to improve one’s ability to control where a bullet will go
* They put some tin cans on the fence and shot at them from a distance for target practice.
machine gun – a large gun that fires many bullets automatically and very quickly
* Machine guns allow soldiers to shoot more quickly, because they don’t have to reload their gun manually between shots.
grenade launcher – a machine that sends a grenade (a small, handheld bomb normally thrown by a soldier) very far through the air
* Grenade launchers let soldiers throw grenades further than they could throw them with their hand.
weapon – a tool that is used to hurt or kill another person or animal
* When Stephen heard a loud noise in the middle of the night, he picked up a baseball bat and planned to use it as a weapon against the intruder.
missile – a bomb that is sent through the air for a long distance and explodes when it hits a building or the ground
* The missile was supposed to hit the army headquarters, but it hit a hospital instead by mistake.
antiballistic missile – a bomb that is made to hit another missile while it is still in the air, making it explode before it hits something else and kills people
* How often do antiballistic missiles actually hit another missile, and how often do they miss?
torpedo – a bomb that is sent through the ocean water, deep below the surface, usually by a submarine (a boat that travels in deep water) and explodes when it hits something
* How many submarines were destroyed by torpedoes during the Cold War?
tank – a very large, heavy vehicle that is used by the army, with thick metal sides to protect the people inside, and with large guns for fighting
* The soldiers shot at the tank, but their bullets didn’t do any damage to it.
Comprehension Questions
1. Which of these would most likely be used for hunting?
a) A rifle.
b) A machine gun.
c) A grenade launcher.
2. What does Emmanuel mean when he says, “I mainly honed my skills with target practice”?
a) He first learned how to shoot during target practice.
b) He taught other people how to shoot at target practice.
c) He became a better shooter through target practice.
Answers at bottom.
What Else Does It Mean?
to fire
The verb “to fire,” in this podcast, means to move one’s finger while holding a gun so that it makes a loud noise and sends out a bullet that moves very quickly: “The soldier got in trouble for firing at the enemy before his commanding officer gave the order.” When talking about work, the verb “to fire” means to make someone lose their job, or to tell someone that he or she no longer has a job: “If you keep coming to work late like this, you’re going to get fired.” The phrase “to fire questions at (someone)” means to ask many questions very quickly: “The reporter fired questions at the mayor.” Finally, the phrase “to fire (someone) up” means to make someone excited and enthusiastic about something: “All the members of the football team are really fired up about tonight’s game.”
tank
In this podcast, the word “tank” means a very large, heavy vehicle that is used by the army, with thick metal sides to protect the people inside, and with guns for fighting: “Tanks have metal belts over their wheels so that they can move over rocky, uneven ground.” A “tank” is also a large container for holding water or another liquid or gas: “Mr. Hansen carries around an oxygen tank to help him breathe.” Or, “How many gallons does your car’s gas tank hold?” A “tank top” is a shirt that has no sleeves, instead having a small piece of fabric over each shoulder: “The girls wore tank tops all summer.” Finally, the informal verb “to tank” means to fail or to not be successful: “They opened a new restaurant, but it tanked within the first few months.”
Culture Note
The second “amendment” (addition or change) to the U.S. “Constitution” (the most important legal document in the United States) gives people the right to “bear arms” (carry guns). But there are many “federal” (national) and state laws that “restrict” (put limitations on) what kind of “firearms” (guns) people can own, how they can buy them, and how they can use them.
The Gun Control Act of 1968 “bans” (does not allow) certain types of people from owning guns. These include “convicted felons” (people who have been found guilty of a serious crime), people who have a dangerous “mental illness” (a health problem that affects how one thinks and acts), and “minors” (people who are less than 18 years old).
The Brady Handgun Violence Prevention Act of 1993 “mandated” (legally required) a five-day “waiting period” before someone could purchase a gun. This waiting period was supposed to be a “cooling-off period” (a period of time when one can calm down) so that people wouldn’t be able to buy a gun while they were still very angry about something. It was also supposed to give “dealers” (businesses that sell guns) enough time to “run” (do; perform) a “background check” (research into a person’s past activities) to make sure that the gun buyer isn’t a convicted felon.
However, the waiting period “expired” (was no longer required) in 1998, when background checks became computerized. Today some states still have “mandatory” (required) waiting periods, but in other states a buyer can purchase a gun as soon as he or she receives “authorization” (permission) from the computerized system.
Comprehension Answers
1 - a
2 - c