= 0205
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 205, “Shopping for Shoes.”
This is English as a Second Language Podcast episode 205. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On This podcast, we’re going to go to the store and buy some shoes. Let’s go!
[Start of story]
Clerk: Can I help you find something?
Alissa: Yes, I’m looking for some dress shoes for work, something with a low heel.
Clerk: Have you tried this brand? They make really comfortable shoes. This company makes several styles of dress shoes, including a sandal, a low boot, and a loafer. These right here are open toe and those over there have a strap in the back.
Alissa: Oh, I like these slip-ons, but they seem too narrow. My feet are pretty wide.
Clerk: Those actually come in three widths: narrow, medium, and wide. Do you want to try them on?
Alissa: Sure. Do you have them in a 6-and-a-half or a 7, in black or brown?
Clerk: I’m not sure. I’ll have to check in the back…Here you are. How does the 6-and-a-half fit?
Alissa: They’re a little too tight in the toe. Let me try the 7. Oh, that’s better, but now the heel is a little too loose.
Clerk: Keep in mind that since they’re leather, they’ll stretch a little.
Alissa: In that case, I’ll take the black pair in the 6-and-a-half.
Clerk: Great. I can ring you up over here.
[End of story]
The podcast today is called “Shopping for Shoes.” Everyone needs to wear shoes – well, almost everyone! The dialogue begins with the clerk – the person who works at the store – asking Alissa, “Can I help you find something?” Alissa says, “Yes, I’m looking for some dress shoes for work.” A dress, “dress,” shoe just means a formal shoe. It could be something you wear with a dress, but we also use that term for a man’s shoe that is formal we say it’s a dress shoe. The man could wear a dress too, I guess!
The one that Alissa is looking for is a low heel shoe. We should probably talk a little bit about the parts of the foot because we use different vocabulary to talk about those related to shoes. Your foot has, on the bottom in the back what we call a heel, “heel,” and that’s the bottom back of your foot. It’s also what we call the back bottom of a shoe. The opposite of your heel are your toes. The foot is connected to your leg by something called an ankle, “ankle.” An ankle is that bone that sticks out that is above your foot that allows you to move your foot back and forth.
You have a heel on your foot, and a shoe also has a heel. The heel is either high or low. A high heel is when it is tall. So, women, for example, and, I don’t know, some men, wear shoes that have high heels, and it’s like a little stick that sticks on the back of the shoe, and that makes the woman taller. A low heel shoe is one that doesn’t have a very big heel, it’s more flat. What Alissa is looking for is a shoe with a low heel.
The Clerk says, “Have you tried this brand?” A brand, “brand,” is a type of something sold by a company. Diet Coca-Cola, for example is a brand. It’s a type of product sold by a company. The clerk asks Alissa if she has tried this particular brand that he is showing her. He says that the company that makes this shoe has several different styles, “including a sandal,” “sandal.” A sandal is a shoe that doesn’t have a top on it, usually. It has a bottom, of course, what we would call the sole of the shoe, “sole” is the whole bottom of the shoe, but it doesn’t have a top. Instead, it has what we call straps, “straps.” A strap is like a little...little piece of leather, or like a little rope, really, that holds your foot onto the bottom. But a sandal, usually you can see the toes of the person and the top of their feet.
A boot, “boot,” is a heavier shoe, usually one that goes above the ankle, or covers the ankle. Remember, the ankle is that bone that connects your foot to your leg. The other kind of shoe that the clerk says this company makes is a loafer, “loafer.” And, a loafer is a low heel shoe – could be for a man or a woman – and it has a flat bottom and it’s a very simple shoe. Usually it’s a shoe that you can just put your foot into, and you don’t have to do anything else: you don’t have to tie the shoelaces. A shoelace, “shoelace,” all one word, is the little string or rope that you use to make your shoe tighter on you so that it doesn’t fall off. A loafer doesn’t have any shoelaces; it doesn’t have any buckles, “buckles.” A buckle is similar to a shoelace: it helps keep your foot in the shoe, but it’s usually made of metal, and it has two parts that connect. You have a buckle on your belt. If you wear pants, the belt, “belt,” keeps your pants from falling down, and the buckle connects the belt together. Well, shoes can have shoelaces or buckles, but if it’s a loafer, it doesn’t have either of those.
The clerk also says that the company makes some open toe shoes. Open toe means that you can see the toe. They also have slip-ons. A slip-on, “slip-on,” is a shoe that you don’t need a shoelace or a buckle for. A loafer is a type of slip-on, but you could have other types of shoes that were slip-ons. If you don’t have to do anything to keep the shoe on your foot, you don’t have to tie up the shoelaces or fasten the buckle – the verb to fasten, “fasten,” is used when we talk about connecting the two parts of a buckle – then you have a slip-on shoe.
Well, Alissa says that the shoes that she is trying are too narrow – that her “feet are pretty wide.” The clerk says well, these shoes “come in,” or are available in, “three widths.” The width, “width,” of a shoe is how big it is from side to side. It could be a very wide width, so if you have a foot that is very wide, you would have a wide width shoe. It could be a narrow width, which would be something with a skinnier foot, and then in between is a medium width.
The clerk asks Alissa if she want to “try them on,” and Alissa says, “Sure. Do you have them in a six-and-a-half or a seven” – she’s asking for the size of the shoe. The clerk says, “I’m not sure. I’ll have to check in back,” meaning I’ll have to go to the back of the store to see if I have any. He does that, comes back and asks Alissa how “the six-and-a-half fit” – that is, how does the shoe of size six-and-a-half fit her foot. The verb to fit, “fit,” means that something is not too big; it’s not too small; it’s just right. You can say a shoe “fits me well,” meaning it’s very comfortable. You can also say that a shirt, or a pair of pants, or any kind of clothing fits you – means it’s not too big; it’s not too small.
Alissa says that the shoes are “little tight in the toe.” When a shoe is too small, we say it’s tight, “tight.” The opposite of that would be loose, “loose.” If it’s too big, the shoe will be loose – your foot will move around and the shoe will fall off. If it’s too tight, that will hurt your feet. So, you want something that isn’t too tight and is not too loose.
The clerk says to Alissa that she should, “Keep in mind that they’re leather” – the shoes are made of leather. The expression, to keep something in mind, means the same as remember – be sure to consider. Somebody says, “Keep in mind that our store closes at 9 p.m.” – they’re saying be sure that you know, or be sure that you remember that our store closes at nine. So, the clerk says, “Keep in mind that since” the shoes are made of leather, “leather,” “they’ll stretch a little.” Leather is the skin of an animal that we use to make clothing out of. You can have a leather jacket, a leather coat; you could have leather shoes. I have a nice pair of leather pants. Leather is usually from a cow or some other animal.
The verb to stretch, “stretch,” means that something will get bigger. When we say, for example, that the leather will stretch, we mean that after you start wearing the shoes, the leather – the actual skin of the shoe – will get a little bigger because of your feet being inside of them – they will stretch – they will become a little bigger.
Alissa says, “In that case, I’ll take a black pair in the 6-and-a-half.” “In that case,” meaning well, if they’re going to stretch, if they will get a little bigger, then I want to buy a pair of shoes size 6-and-a-half.
The clerk says, “Great. I’ll ring you up over here.” To ring, “ring,” someone up means that you are going to take their money, that you are going over and you will take their cash or their credit card so they can pay for the item.
Now let’s listen to the dialogue, this time at a native rate of speech.
[Start of story]
Clerk: Can I help you find something?
Alissa: Yes, I’m looking for some dress shoes for work, something with a low heel.
Clerk: Have you tried this brand? They make really comfortable shoes. This company makes several styles of dress shoes, including a sandal, a low boot, and a loafer. These right here are open toe and those over there have a strap in the back.
Alissa: Oh, I like these slip-ons, but they seem too narrow. My feet are pretty wide.
Clerk: Those actually come in three widths: narrow, medium, and wide. Do you want to try them on?
Alissa: Sure. Do you have them in a 6-and-a-half or a 7, in black or brown?
Clerk: I’m not sure. I’ll have to check in the back…Here you are. How does the 6-and-a-half fit?
Alissa: They’re a little too tight in the toe. Let me try the 7. Oh, that’s better, but now the heel is a little too loose.
Clerk: Keep in mind that since they’re leather, they’ll stretch a little.
Alissa: In that case, I’ll take the black pair in the 6-and-a-half.
Clerk: Great. I can ring you up over here.
[End of story]
Our script today was written by Dr. Lucy Tse.
If you want more information about today’s topic, including all of the vocabulary words that we used and some additional vocabulary about shopping for shoes, go to our website at eslpod.com and download the Learning Guide for this podcast.
From Los Angeles, California, I’m Jeff McQuillan, thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
dress shoes – formal shoes worn with formal or business clothes
* My brother asked me to help him pick out a pair of dress shoes to go with his new suit.
heel – the back part of a shoe under the ankle; the bottom back part of the foot
* She stepped on some gum with the heel of her left shoe and had trouble getting it off.
brand – the name of the company that makes the things you find in stores
* I’ve never heard of this brand of televisions. Do you recommend them?
sandal – a type of shoe made with straps so that the foot is easily seen
* Summer is the perfect time of year to wear sandals.
boot – a type of shoe with a tall top so that part of your leg is covered
* Make sure you wear your winter boots if you plan to be out in then snow all afternoon.
loafer – a type of shoe that is flat or has a low heel, with no shoelaces or buckles
* He prefers wearing a loafer because they are easier to put on and to take off.
open toe – a type of shoe that doesn’t cover the toes
* People do not normally wear open toe shoes in the winter.
strap – a long, thin piece of material, such as leather or cloth
* When she got on the crowded subway, she held on tightly to the strap of her bag so that no one would be able to steal it from her.
slip-on – any type of shoe without shoelaces or buckles that someone can put on simply by putting their foot into the shoe
* Slip-ons for young kids are a good idea because many of them haven’t learned how to tie shoelaces yet.
width – size of the foot when measured across, from side to side
* She liked the shoes, but none of the widths it came in fit her correctly.
narrow – a thin space that is longer than it is wide
* Those big trucks are having problems driving through the narrow streets of London.
wide – a large or big distance from side to side
* The purpose for building this bridge is to make it possible for cars to cross that wide river between the two cities.
to fit – to be the right size and shape for something
* She didn’t buy the sweater because it wasn’t a good fit.
tight – not enough room for something; too little space
* The jacket looked like it was the right size, but when he tried it on, he thought it was too tight.
loose – too much room for something; too much space; not strongly fixed or attached onto something
* Some of the book’s pages are loose and keep falling out of the book.
to keep in mind that... – to remember; to think about; to consider
* My wife decided to buy a large couch to replace a smaller one even though I told her to keep in mind that there may not be enough space in the house for it.
leather – the dried skin of an animal used to make clothes, shoes, bags, and other things
* He’s a vegetarian and he doesn’t buy anything made of leather.
to stretch – to make wider, longer, or larger by pushing or pulling
* I don’t want to try on your sweater. I’m bigger than you are and I’ll probably stretch it.
to ring (someone) up – when a salesperson adds up and records on a cash register the things you want to buy
* You look like you’re ready. I can ring you up over here.
Comprehension Questions
1. What type of dress shoes did Alissa buy?
a) Boots
b) Slip-ons
c) Loafers
2. Alissa bought shoes in what size?
a) 6
b) 6 1/2
c) 7
Answers at bottom.
What Else Does It Mean?
heel
The word “heel,” in this podcast, means the bottom part of the back of a shoe under the ankle: “You can tell that she walks a lot because of the worn-out heel on her shoes.” “Heel” can also mean the back part of a foot: “She had some trouble walking because of a cut on her left heel.” A term that is often used for women’s shoes is “high-heels,” a type of shoe that has a tall, thin heel: “I like the look of these high heels but I can’t walk in them!” The word “heel” is also used for the bottom part of a hand that connects with the arm: “The heel of my hand felt sore yesterday after making bread all day.”
boot
In this podcast, the word “boot” means a type of shoe with a tall top that covers the lower part of your leg: “Before going into the river, the fishermen put on their rubber boots.” As a verb, “to boot” is an informal term that means to dismiss someone, usually from a job or a position: “After he was found stealing, he was booted by his company and told to never come back.” Or, “She was on a reality show, but was booted after the first show.” “To boot,” as a verb, can also mean to start a computer: “We had to boot the computer again after the new software was installed.”
Culture Note
In the United States, there are different sets of shoe sizes for men, women, and children. Shoe sizes are “determined,” or found, by measuring how long a foot is, from the tip of the largest toe to the very back part of the heel. This is normally done in shoe stores where there is a foot-shaped metal plate with numbers to measure feet. The width is also measured and is given a letter on this plate. Most stores use the same kind of template made by the same company, so it’s almost certain that the size you get in one store will be the same size you’ll get in another store.
Women’s sizes are equal to men’s sizes plus 1.5., so that a size 7 in men’s shoes is a size 8.5 (or 8 ?) in women’s shoes. For children’s shoes, sizes for girls and boys are the same.
Women Shoe Sizes
English		2	2.5	3	3.5	4	4.5	5	5.5	6	6.5	7	7.5	8
European	34	35	35.5	36	37	37.5	38	39	39.5	40	40.5	41	42
American		4.5	5	5.5	6	6.5	7	7.5	8	8.5	9	9.5	10	10.5
Japanese		21.5	22	22.5	23	23	23.5	24	24	24.5	25	25.5	26	26.5
Men Shoe Sizes
English		5	5.5	6	6.5	7	7.5	8	8.5	9	9.5	10	10.5	11	11.5	12
European	38	38.7	39.3	40	40.5	41	42	42.5	43	44	44.5	45	46	46.5	47
American		5.5	6	6.5	7	7.5	8	8.5	9	9.5	10	10.5	11	11.5	12	12.5
Japanese		23.5	24	24.5	25	25.5	26	26.5	27	27.5	28	28.5	29	29.5	30	30.5
Children Shoe Sizes
English		9	9.5	10	10.5	11	11.5	12	12.5	13	13.5	14	14.5	15	15.5	16
European	27	27.5	28	28.5	29	30	30.5	31	31.5	32	32.5	33	33.5	34	34.5
American		9.5	10	10.5	11	11.5	12	13.5	13	13.5	14	14.5	15	15.5	16	17
Japanese		15.5	16	16.5	17	17.5	18	18.5	19	19.5	20	20.5	21	21.5	22	22.5
Comprehension Answers
1 - b
2 - b