= 0214
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 214, “A Jealous Girlfriend.”
This is English as a Second Language Podcast episode 214. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com and take a look at the Learning Guide for this podcast that contains all of the words that we discuss, their definitions, sample sentences, additional definitions that we don't talk about on the podcast, cultural notes and a complete transcript of this podcast.
Today's podcast is called, “A Jealous Girlfriend.” Sounds interesting. Here we go!
[Start of story]
Sarya: Hey Dom, I haven’t seen you in so long. Where have you been?
Dominick: Oh, I’ve been busy.
Sarya: I’ve missed hanging out together. How’s Leslie?
Dominick: She’s okay, but things haven’t been that great between us.
Sarya: I’m really sorry to hear that. What’s up?
Dominick: Leslie is great, but she’s so jealous of my friends, especially my female friends. She doesn’t like it when I see them or even if I talk to them on the phone. To be honest, that’s why I haven’t called you lately.
Sarya: I got the feeling that you’ve been avoiding me. Now I understand that it’s the green-eyed monster at work. Have you been doing anything to make her jealous?
Dominick: No! I go out with my friends sometimes but I’m always up front with Leslie and tell her what I’m doing. But, she’s so possessive. Even when I go out with my guy friends, she flips out sometimes. I don’t know why she won’t trust me.
Sarya: Maybe she’s just insecure about herself, or maybe she feels insecure about your relationship. But either way, I’d stop this in its tracks before it gets any worse. Have you talked to her about it?
Dominick: Not really. We usually get into a big fight and then we make up, but we don’t ever get at the root of the matter.
Sarya: I wish I could help.
Dominick: You already have. Talking about it helps. Whatever it takes, I’m going to get this under control. Other than this jealousy problem, we have a great relationship. I don’t want anything to jeopardize it.
Sarya: Good luck with everything and let me know if I there’s anything I can do.
Dominick: Thanks. I will.
[End of story]
The podcast we just listened to is called, “A Jealous Girlfriend.” To be jealous, “jealous,” means to want something that someone else has. Usually when we say a jealous girlfriend or a jealous boyfriend we mean that the girlfriend or boyfriend doesn't like his or her partner, doesn't like the other person, to be seen with other women or other men. So, a jealous girlfriend wants to keep her boyfriend to herself and doesn't want the boyfriend talking to or getting involved with other women. To be jealous means to want something for yourself and for no one else to have it. It's similar to the word envious, “envious.” To be envious means to want something that someone else has.
Our dialogue begins by the friend of Dominick saying, “Hey Dom, I haven’t seen you in so long. Where have you been?” Dom, “Dom,” is short here for Dominick. So, she says, I have not seen you in a long time, and Dominick says that he's “been busy.” This is something we often use as an excuse in English. When we don't want to talk to someone we say, “Oh, I've been busy. I'm too busy. I have too much to do.” Dominick's friend Sarya says, “I’ve missed hanging out together.” To hang out, “hang out,” two words, means to spend time together. So, when two people spend time together having fun, not working but relaxing, going to movies, talking - that is hanging out. It's an informal term to mean spend time together.
Sarya asks about the Leslie, who is Dominick's girlfriend. Dominick says, “She’s okay, but things haven’t been that great between us.” In other words, we've been having problems. Sarya says, “I’m sorry to hear that. What’s up?” When someone tells you bad news, it's common for you to say, “Oh, I'm sorry to hear that.” Well, Dominick explains that Leslie is very jealous of Dominick's friends, especially his female friends. Of course, once you get into a relationship - once you have a girlfriend - the other female friends that you have may cause your girlfriend to be jealous. So, men, watch out! Back to the story.
Dominick says that she doesn't like it when he sees or talks to other women. If he sees them or talks to them on the phone, she gets jealous. He says, “To be honest,” or honestly, “that’s why I haven’t called you lately.” So, he tells her the truth. To be honest, to tell the truth, honestly - all of those expressions mean that I'm going to tell you the truth.
Sarya says, “I got the feeling that you’ve been avoiding me,” meaning that's what I thought. I knew that you were not talking to me. To avoid, “avoid,” someone means to not talk to them, to not see them, to try not to have any contact with them. No communication. You may say, “I'm avoiding my friend Joe because I owe him ten dollars.” He gave me ten dollars and now I need to give it back, and I don't have ten dollars so I'm going to avoid him. This is the way I do it!
Sarya says, “Now I understand that it’s the green-eyed monster at work.” The expression green-eyed monster, “green-eyed,” monster, “monster,” means that it's the person being jealous. A monster is someone like Frankenstein, someone who is very large, ugly, someone that could scare you. This is an imaginary person, kind of like the host of ESL Podcast - big, ugly! A monster, then, is a bad thing, something that would scare you. The color green is the color that we use to indicate someone is jealous or someone is envious. I'm not sure why green, but we use the color green. We have an expression, “He's green with envy,” meaning he's very jealous, he's very envious. The green-eyed monster, then, would be this monster that is very jealous, very envious, and it's an expression, an informal expression to mean, simply, jealousy.
Sarya says to Dominick, Have you done anything to make your girlfriend jealous? In other words, what have you been doing, Dominick? And Dominick says, “No!” He says he has not done anything. He goes out with his friends - to go out with here means the same as to hang out with - but he says he's “always up front with Leslie.” When you are up front with someone, you are honest with them, you are direct with them, you tell them the truth right away.
He says he's “up front with Leslie,” but Leslie, his girlfriend is very “possessive.” To be possessive, “possessive,” means something similar to being jealous. To be possessive means that you want to have something for yourself. To possess, as a verb, means to own, to have something. You can say, “I possess three shirts,” or “I possess a good sense of humor” - whatever you, whatever you own, whatever you have. So, Leslie is being possessive, it means she wants something and she doesn't want anyone else to have it, and that's the way she feels about Dominick. You can think of possessive as wanting something for yourself, your things and no one else can have them. To be jealous means that you want something that someone else has. So, there is a small difference between them.
Dominick says that even when he goes out with his guy friends - the word guy, “guy,” means male or man friends - even when he goes out with his friends who are men, Leslie “flips out.” To flip, “flip,” out, “out,” means to get very - in this case, very angry. They go crazy. It's the opposite of staying calm. Dominick says, “I don't know why” my girlfriend doesn't “trust me.” To trust, “trust,” in this sentence means to have confidence in someone, to have faith in someone, to believe that someone is telling the truth, for example. Trust has a couple of other different meanings in English. We talk about those on today's Learning Guide.
Sarya says that, “Maybe” Leslie is “just insecure about herself.” When you say someone is insecure, “insecure,” you mean that they don't have confidence in themselves. They don't feel confident about themselves. Sarya says that Dominick should “stop this in its tracks before it gets any worse.” To stop something in its tracks, “tracks,” means to end something before it becomes a problem, to stop something before the problem gets more serious.
Dominick says that usually they “get into a big fight,” and afterwards they “make up.” To make up, “make up,” two words, means to get over an argument, to become friends again, to be nice to each other again. Again, this word has a lot of different meanings - make up. Take a look at the Learning Guide for today for those additional meanings.
Dominick says that he and his girlfriend, when they have a fight, never get to “the root of the matter.” To get to the root, “root,” of the matter means to get to the cause of the problem, to get to the real reason why they are having this difficulty.
Dominick thanks Sarya for her help. He says, “Whatever it takes, I’m going to get this under control.” Whatever it takes is an expression that means I will do anything or anything and everything that has to be done I will do. To get something under control means to get it to a normal condition, to a situation that you can manage. The opposite of under control is not over control, it's out of control. So, if you say something is out of control, you mean you do not have it manageable. It is something that you cannot take care of, you cannot handle. In this case, Dominick is saying he wants to get it under control. He wants to be able to manage it correctly.
He says he doesn't want to do “anything to jeopardize” his relationship with his girlfriend. To jeopardize, “jeopardize,” means to put something in danger, to put something in a situation that might harm you or harm the relationship, in this case.
There are several popular television shows in the United States that talk about relationships and problems that boyfriends and girlfriends have, and in our Learning Guide today we have a whole cultural note about those programs.
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
Sarya: Hey Dom, I haven’t seen you in so long. Where have you been?
Dominick: Oh, I’ve been busy.
Sarya: I’ve missed hanging out together. How’s Leslie?
Dominick: She’s okay, but things haven’t been that great between us.
Sarya: I’m really sorry to hear that. What’s up?
Dominick: Leslie is great, but she’s so jealous of my friends, especially my female friends. She doesn’t like it when I see them or even if I talk to them on the phone. To be honest, that’s why I haven’t called you lately.
Sarya: I got the feeling that you’ve been avoiding me. Now I understand that it’s the green-eyed monster at work. Have you been doing anything to make her jealous?
Dominick: No! I go out with my friends sometimes but I’m always up front with Leslie and tell her what I’m doing. But, she’s so possessive. Even when I go out with my guy friends, she flips out sometimes. I don’t know why she won’t trust me.
Sarya: Maybe she’s just insecure about herself, or maybe she feels insecure about your relationship. But either way, I’d stop this in its tracks before it gets any worse. Have you talked to her about it?
Dominick: Not really. We usually get into a big fight and then we make up, but we don’t ever get at the root of the matter.
Sarya: I wish I could help.
Dominick: You already have. Talking about it helps. Whatever it takes, I’m going to get this under control. Other than this jealousy problem, we have a great relationship. I don’t want anything to jeopardize it.
Sarya: Good luck with everything and let me know if I there’s anything I can do.
Dominick: Thanks. I will.
[End of story]
The script for today's podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
to hang out – to spend free time with others
* Mary wanted to go to the movies with Josh, but he was already hanging out with Kim that afternoon.
jealous – wanting something or someone that belongs to another person
* After getting a short haircut, Lisa couldn't help but be jealous of other women with long hair.
to avoid – to stay away from someone or something; to stop oneself from doing something
* Kelly knew that Michael was avoiding her when he didn’t go to class for two days.
green-eyed monster – jealousy; the feeling of wanting something or someone that belongs to another person
* It’s hard to avoid the green-eyed monster when you have a girlfriend who is a famous model.
to be up front – to be honest; to be direct when speaking
* Wanting to be up front with the boss, Jake told him that he was looking for another job and would be leaving the company soon.
possessive – wanting very badly to control things or other people; wanting very much to keep what one has to oneself
* She was possessive about her baby the first three months after it was born and would not let anyone near him.
to flip out – (slang) to go crazy; to suddenly be out of control
* Coming home after a long day at work, my mother flips out if the house is a mess.
to trust – to have faith or confidence in something or someone
* Even after the mistakes she’s made, I still trust her to get the job done correctly and on time.
insecure – not have confidence in oneself
* He’s insecure about his skinny body and always wears clothes that are too big for him.
to stop (something) in its tracks – to stop something right away, usually before it becomes a problem or a bigger problem
* Unless we stop this in its tracks, the bad news about our company will be in all the newspapers by the end of the week.
to make up – to have good feelings again after a fight; to say sorry after a disagreement
* Jen was trying to make up with Britney, but Britney was still mad and wouldn’t talk to her on the phone.
the root of the matter – the source or main reason, usually of an issue or problem
* The root of the matter is that she's lazy, and that's why she was taken off this project.
whatever it takes – doing everything possible to make something happen or to complete a task
* Whatever it takes, I’m going to save up enough money to go to Europe this summer.
under control – in a normal state or condition
* She got the noisy kids under control when she offered to buy them ice cream.
to jeopardize – to risk; to put in danger
* Getting fired from his job would jeopardize his plans to buy a house next year.
Comprehension Questions
1. Why has Dominick been avoiding Sarya?
a) They had a fight.
b) He doesn't like Sarya.
c) His girlfriend gets jealous when he hangs out with other people.
2. Sarya thinks Leslie gets jealous because:
a) Dominick doesn't invite her when he goes out with his friends.
b) She is insecure about herself.
c) Dominick has been calling Sarya too much.
Answers at bottom.
What Else Does It Mean?
to trust
The verb “to trust” in this podcast means to have faith or confidence in a person or thing: “I proved to her that she can trust me to take care of her cat while she's on vacation.” “Trust” can also mean to hope for something, with confidence: “I trust that you will be home on time.” Or, “We trust that this will be the last time that you’ll miss a deadline.” When this word is used as a noun, it is a legal term for property owned by one person or group being held and run by another person or group: “Before Dana’s uncle died, he arranged to put his money into a trust that is managed by the bank and that pays out money every year to Dana and her sisters.”
to make up
In this podcast, the verb “to make up” means to say or be sorry for something and to get along with someone again: “My sister and I fight often, but we usually make up right afterwards.” The phrase also means to do something good for someone after having done something wrong or bad to them: “To make up for using the car without asking, her son made dinner for the whole family.” Or, “I don’t know how I’ll ever make up for letting you down.” “Makeup,” as one word, is a noun that means cosmetics, usually worn by women, such as lipstick and eye shadow: “For Halloween, she wore dark makeup to look scary.” Or, “Don’t you think that she’s too young to wear all of that makeup?”
Culture Note
In the U.S., personal problems are often used as topics on T.V. shows. Shows like The Jerry Springer Show, The Montel Williams Show, and Maury are talk shows that “air” or are shown during the day and that have people telling private and sometimes secret things about their lives. There is usually a large audience that then gets to offer comments, both good and bad, and some advice. Guests of these shows usually talk about problems like “cheating” or unfaithful husbands and wives or boyfriends and girlfriends; out of control sons and daughters; or drug and alcohol problems in the family. These shows focus not so much on what is being said, but on the way that things are said and then on the reaction of the audience when they hear them. People on these shows often cry, yell, fight, and sometimes even become “violent” or try to hurt other people physically. The conversations between the guests and the audience, which usually result in yelling and “insults,” or bad things said to hurt someone else, is what people who watch these shows like the best.
Today, shows like these are considered reality T.V. Realty T.V. shows follow and film ordinary or normal people as they are put into unusual or difficult situations. A TV show called Cheaters has “private investigators,” or people hired to do investigations, spy on someone's girlfriend or boyfriend, or husband or wife. When they are caught cheating with another person, usually in a public place like a restaurant, they are “confronted,” or met face to face, by the person they are cheating on while the entire situation is filmed.
Other popular daytime reality shows have real judges who listen to and then make decisions about a case or argument between two people. These includeCourt T.V., Divorce Court, and People’s Court. Like the daytime talk shows, these shows focus on people talking about their “dirty laundry,” or personal problems and secrets that cause embarrassment, in front of strangers and getting the audience’s reactions.
Comprehension Answers
1 - c
2 - b