= 0226
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 226: Holiday Decorating.
This is English as a Second Language Podcast episode 226. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com. You can find there the Learning Guide for this episode, which contains all of the vocabulary words, definitions, sample sentences, additional cultural notes, explanations of words we that don't talk about on the podcast and a complete transcript of this episode.
This podcast is about “Holiday Decorating.” Let's get started.
[Start of story]
Now that the holidays are here, it’s time to decorate the house. Every year, we always go all out. We buy a Christmas tree and the kids decorate it with ornaments that we’ve bought and made over the years, and with silver and gold tinsel. We also hang a wreath on our front door and I make sure that there’s mistletoe above every door. Around the chimney, we hang our stockings, and when we get holiday cards from our friends and neighbors, we put them all around the room.
Outside of the house, we have lawn ornaments that we put in the front yard. People who visit our house will see snowmen (and snowwomen), reindeer, and of course, Santa Claus. The best part is the outdoor lights. I string them across the front of the house, around our trees, and in our fence. When I turn them all on, you can probably see our house from miles away. It’s no wonder that people come from all over town just to see our house at night. I have to say that I enjoy the holiday season as much as the kids...and maybe just a little more!
[End of story]
Our podcast is called “Holiday Decorating.” Holiday usually refers to Christmas and New Years and perhaps Chanukah, the Jewish celebration. This particular episode is mostly about Christmas decorations, since that is probably the most popular holiday celebration, at least in the United States.
The story begins by me saying that “the holidays are here,” meaning we are now in the time of the holidays, and “it's time to decorate the house.” To decorate, “decorate,” means to make something more beautiful or more attractive, usually by putting objects - putting something on it, like your house or a tree. There are other meanings of this word to decorate that we discuss in the Learning Guide for this episode.
The story continues that “Every year, we always go all out.” That expression, to go all out, “out,” means to put all of your energy into something - that you are going to do something using the maximum amount of effort. In this case, going all out means that we bought a Christmas tree. A Christmas tree is a large, usually green, tree that people buy.
In many American cities, there are Christmas tree lots, “lots.” A lot is just an empty space, usually outside, that has, in this case, lots of Christmas trees and you can go and buy them. You can't buy a Christmas tree, at least a real tree, in a store - in a regular store; you need to go to one of these temporary stores - these Christmas tree lots - to buy a tree. If you want an artificial tree - a tree made of plastic or metal - then you can get that at a store.
Now, this is something I really don't have much experience with; we never had a real Christmas tree when I was growing up. But this is the story, and in the story, there's a Christmas tree. All the kids are going to decorate the tree with ornaments. An ornament, “ornament,” is an object that you use to decorate. Ornaments are little things for a Christmas tree that you hang on the tree or put on the branches of the tree. Often, these ornaments are round and they have a little piece of metal on top that you can hang it on the branch of the tree - the arms of the tree that come out.
We've also bought some “silver and gold tinsel.” Tinsel, “tinsel,” is another one of those words that you usually only hear during the Christmas season. Tinsel is a narrow piece of a shiny material that's used for decoration. It's usually like a long string, and the string has metal on it often, or something that is very shiny - something that reflects the light. And often, pieces of tinsel are different colors. In this case, they're silver and gold tinsel. It's traditional to have both Christmas ornaments and tinsel on your Christmas tree.
“We also hang a wreath on our front door and I make sure that there’s mistletoe above every door.” A wreath, “wreath,” is a circle - a round thing - that is made of tree branches usually. It could also be made of flowers. And, it is something that, in the United States, is often found on the door - outside door - of your house during the Christmas season - during the time of Christmas.
I remember when I was young boy, I was a member of the Boy Scouts, which is a voluntary organization of boys - to keep them from causing trouble, I think - and we used to sell these Christmas wreaths in order to make money for the Boy Scout organization. So, I have many memories of going and selling Christmas wreaths.
In addition to a Christmas wreath in the story, there's also mistletoe. Mistletoe, “mistletoe,” (one word) is a special plant that has green leaves and little white what we would call berries - little round things. And, this little plant, or a piece of a plant, is used in Christmas; it is often hung up on the top of a door. Now, the tradition is that if you are standing under a mistletoe with someone else, you are supposed to kiss that person. The other person, you hope, wants to kiss you as well. If not, then in addition to a kiss, you will also get a black eye when they hit you, especially if you're a man trying to kiss a woman. Well, that's been my experience!
The story continues by saying that “Around the chimney, we hang our stockings.” The chimney, “chimney,” is a brick or rock part of the house. It is connected to something called a fireplace, “fireplace.” A fireplace is where you burn wood inside a house to keep it warm.
Many houses, now, don't have fireplaces; my house doesn't have a fireplace, but older houses or houses of rich people sometimes have these old fireplaces. If you burn wood, you will have smoke, and so you need to take the smoke out of the room, and you do that through the chimney. It's a long, narrow part of the house. On the top of the chimney is at the top of the house, and that's where the smoke goes outside.
Traditionally, Santa Claus, when he comes to visit, will land on the top of your house - the roof of your house - and then come down the chimney. That's why his clothes always get dirty, because he's climbing in those chimneys!
Well, “Around the chimney,” - around the fireplace - “we hang our stockings.” Stockings, “stockings,” are large, usually very colorful socks. They're big socks, not real socks that you would put on your feet. But, they are large socks that are filled with presents on the night before Christmas. Again traditionally, you put things in the stockings - a parent would put gifts in stockings for their children.
In my house, growing up, we had a stocking for everyone in the house, which means we had 13 stockings. So, it was sort of like walking into our house and it looked like my mother was drying the clothes because we had so many of these stockings!
The things you put in a stocking - the gifts - are usually small gifts. They're sometimes called stocking stuffers, “stuffers.” To stuff means to put something into something else; that's what you do with a stocking stuffer, a small gift.
Another tradition is the holiday card or the Christmas card. These are cards that people send each other. We may also call them greeting cards. The cards have a picture of something related to Christmas - a Christmas tree or perhaps Santa Claus - and you write notes in to your friends and family and wish them a Merry Christmas.
You can also make your own cards. Some families make cards with pictures of their children and send them to you. It was very popular, and still is in some families, to send out a Christmas letter, where you would describe to your friends and family everything you did or all the most important things that happened to you in the past year. These are always very entertaining to get. I suppose nowadays you could just have a blog and you wouldn't need to send anyone a letter.
The story goes on to say that “Outside of the house, we have lawn ornaments that we put in the front yard.” The lawn, “lawn,” is the - is the area of grass in front of the house. There's also, often, a lawn in the back of your house. Lawn ornaments are figures - objects - statues - that you put in front of your house that are about Christmas or related to Christmas. Some of these ornaments or statues are of snowmen. Snowmen are made of snow - round balls of snow - to look like a man. Usually three balls of snow: one large one, one medium one and one small one. The small one is the head. There's also lawn ornaments that look like reindeers. A reindeer, “reindeer,” is the animal, which according to tradition, is part of Santa Claus' transportation. And of course, Santa Claus himself.
“The best part,” I say in the story, “is the outdoor lights.” It's become very popular in the United States to put Christmas lights on the outside of your house. Not just one or two strings of lights, we would call them, but hundreds and hundreds of lights, very sophisticated, complicated sets of lights with different colors. This has almost become a competition in some cities, where people try to have the most complicated or most beautiful set of outdoor lights. This is not something that I do, ever, but it is interesting to see because at night you can drive by the house and it looks very beautiful with all of these lights on it.
The verb that we use is to string. When we say we're going to string lights, we mean we're going to hang them in a line. The lights usually come on something like a long rope, and there are lots of lights in a straight line and you can string those, or put those, in the front of your house.
I say at the end that “It’s no wonder that people come from all over town just to see our house at night.” It's no wonder is an expression that means it isn't surprising - it's logical - it would be expected that people would come from all over town.
Now let's listen to the story, this time at a native rate of speech.
[Start of story]
Now that the holidays are here, it’s time to decorate the house. Every year, we always go all out. We buy a Christmas tree and the kids decorate it with ornaments that we’ve bought and made over the years, and with silver and gold tinsel. We also hang a wreath on our front door and I make sure that there’s mistletoe above every door. Around the chimney, we hang our stockings, and when we get holiday cards from our friends and neighbors, we put them all around the room.
Outside of the house, we have lawn ornaments that we put in the front yard. People who visit our house will see snowmen (and snowwomen), reindeer, and of course, Santa Claus. The best part is the outdoor lights. I string them across the front of the house, around our trees, and in our fence. When I turn them all on, you can probably see our house from miles away. It’s no wonder that people come from all over town just to see our house at night. I have to say that I enjoy the holiday season as much as the kids...and maybe just a little more!
[End of story]
The script for today's podcast was written by Dr. Lucy Tse.
That's all we have time for today. From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
to decorate – to make something more attractive by putting objects on it
* The students are going to decorate the high school gym so that it looks like a dance club for their dance on Friday night.
to go all out – to put all of one’s energy and effort into doing something
* She went all out during the race and finished in first place.
Christmas tree – a pine tree (or a plastic tree) that people decorate and place in their homes to celebrate Christmas
* Please put all of the presents from your grandparents under the Christmas tree.
ornament – a small object used for decoration, usually with a string for hanging on the branches of a Christmas tree
* My favorite Christmas tree ornament is the blue glass ball that my daughter gave me three years ago.
tinsel – narrow, thin strips of shiny material used for decoration
* The children were supposed to put the tinsel on the Christmas tree, but they had more fun putting it in each other’s hair.
wreath – a circle of flowers and leaves hung on a door or wall for decoration
* Everyone who visits their house admires the beautiful Christmas wreath hanging on their front door.
mistletoe – a plant with green leaves and white berries that is used as decoration during the Christmas holiday
* I’m hanging mistletoe above the doors because tradition says that if a man and a woman stand under the mistletoe, they have to kiss each other.
chimney – a brick or rock structure that carries smoke from a fireplace, through the roof and outside of a house
* When we lit the fire, the room started to fill with smoke because we had forgotten to open the chimney.
stocking – a very large, colorful sock that is hung near the chimney and filled with presents the night before Christmas
* Last year, Josiah made a giant stocking because he thought he would get more presents that way.
holiday cards – a piece of paper folded in half, with a picture on the front and a message inside, sent to friends and family to wish them happy holidays
* This year we are sending a photograph of the children inside our holiday cards, so that our family and friends can see how much they’ve grown since last year.
lawn ornaments – statues and other objects placed on the grass in front of a house as decoration
* Look at the lawn ornaments across the street! That family must be very excited about the holidays.
snowman – snow shaped in the form of a person
* Myung and Oscar made a snowman with cookies for eyes and a carrot for a nose.
reindeer – a large animal that looks like a deer with long antlers (horns that look like tree branches) on its head that lives in the snow
* According to Christmas stories and songs, Santa Claus uses flying reindeer to help him go from house to house, delivering Christmas presents.
Santa Claus – an imaginary fat, jolly (cheerful) man with a white beard and red clothing who delivers Christmas presents to good boys and girls
* Many children behave very well in December because their parents tell them that Santa Claus will bring them presents only if they are good.
outdoor lights – lines of multi-colored, white, or blue lights that are placed along the roofs, doors, and windows of houses as Christmas decorations
* Some neighborhoods are famous for their outdoor lights at Christmas, and many people drive by to see their decorations.
to string – to hang decorations in a line
* When we learned that Katie was pregnant, we celebrated by stringing pink and blue decorations all around the living room.
it’s no wonder that – it isn’t surprising that
* It’s no wonder that you passed the exam. You have been studying every night for almost two months!
Comprehension Questions
1. Why is the family decorating the house?
a) Because the house hasn’t been decorated for many years.
b) Because this is how the family celebrates the holidays.
c) Because Santa Claus visits only decorated houses.
2. Where does the family put its holiday decorations?
a) Only inside the house.
b) Only outside of the house.
c) Both inside and outside of the house.
Answers at bottom.
What Else Does It Mean?
to decorate
The verb “to decorate,” in this podcast, means to make something more attractive by putting objects on it. For example, “For their wedding, they decorated the room with white, yellow, and gold fabric.” The verb “to decorate” can also mean to be placed on something to make it look more attractive: “Paintings of kings and queens decorated the walls of the old castle.” “To decorate” can also mean to give someone a medal or another honor: “The soldier was decorated for his bravery in the battle.” A “decorator” is someone whose job is to decorate homes: “We want to hire an interior decorator to decorate our dining room because we don’t think we can do a good job without professional help.”
stockings
In this podcast, the word “stockings” means very large, colorful socks that are hung near the chimney and filled with presents the night before Christmas. In a popular poem, “The Night Before Christmas,” the author wrote: “Stockings were hung by the chimney with care, in hopes that St. Nicholas (Santa Claus) soon would be there.” The word “stockings” can also refer to a thin piece of clothing that a woman wears over her feet and legs, such as nylons or tights. For example, “Do you think black or skin-colored stockings would look better with this dress?” As a verb, “to stock” means to have a supply of goods to sell: “We need to stock more of those notebooks because they are selling very quickly.”
Culture Note
In the United States, many families celebrate Christmas and New Year’s Day by stringing outdoor lights around their houses. Although many non-Christian families also do this, people of other religions may not. These strings of lights can be all one color, or a mixture of red, blue, green, and yellow. The lights are usually strung along the roof, around doors and windows, and sometimes around trees in the “front lawn” (the grass-covered area in front of a home). Sometimes people use lawn ornaments that have lights, too. Popular lawn ornaments include Santa Claus, reindeer, snowmen, and stars. Other people prefer to display Christian lawn ornaments that relate to a “nativity scene” or a scene showing the birth of Jesus in the Christian religion, and includes the baby Jesus and his parents, Mary and Joseph.
Some families compete with their neighbors to have the biggest or most beautiful “lawn displays” or the group of objects they place in front of their homes for other people to see. For this reason, the best lawn displays are often found near one another and some neighborhoods become well known for their lawn displays. Often local newspapers provide lists of these neighborhoods so that people can drive through those neighborhoods at night to enjoy the lawn displays.
Some cities and towns organize larger displays during the weeks before Christmas. During the day, they have holiday parades. At night, they often have “light shows” (moving, colorful lights decorating the lawn ornaments). The people who come to these displays usually buy holiday food, such as Christmas cookies and peppermint candy, and drinks, such as hot chocolate and “apple cider” (hot apple juice with cinnamon and other flavors). The money that cities earn from these sales is usually used for social projects.
Comprehension Answers
1 - b
2 - c