= 0239
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 239: A Birthday Party.
This is English as a Second Language Podcast episode 239. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
As always, we ask that you visit our website at eslpod.com, and download the Learning Guide for this episode. You can also now download some special premium courses that we have in our new ESL Podcast Store.
Our episode is called "A Birthday Party." Here we go!
[start of story]
My sister called me at the last minute to help her with my nephew’s birthday party. She was feeling really sick and couldn’t get out of bed. I’d never given a children’s party before, but how hard could it be? Well, I found out.
First, I had to go to the party supply store to get a few things. I couldn’t believe all of the stuff people could buy for children’s parties. There was an aisle with all kinds of party invitations and another one with party favors, streamers, and other decorations. Fortunately, my sister had already bought most of the things we needed earlier in the week. All I needed to pick up were some candles for the birthday cake and some helium balloons.
After the party supply store, I stopped at the grocery store to pick up the birthday cake. My sister had ordered it the week before, so all I had to do was to pay for it and to make sure my nephew’s name was spelled correctly on the top in icing.
Two hours later, I was ready for the party. When the kids arrived with their parents, I took the birthday cards and presents they had brought, and I handed each child some party favors. I was so glad when the clown my sister had hired arrived, and she entertained the kids with games. I have never seen so many kids with so much energy! A little later, we sang “Happy Birthday,” my nephew blew out the candles, and we cut the cake. My nephew opened his presents and the kids played with his new toys. The kids had a good time and so did my nephew.
I have to hand it to my sister. I don’t know how she does it. After three hours with 15 young kids, I’m exhausted and my ears are ringing!
[end of story]
In this episode, I plan a birthday party. This is completely fictional, of course. I would never do this because I am not very good at planning! But, in the story, I say that "My sister called me at the last minute to help her with my nephew’s birthday party." When we say we are going to do something at the last minute, we mean at the latest possible time before something happens. It's usually something that happens when there's an emergency or you didn't expect it. Sometimes it can be because you like to do things right at the end - right before they have to be done. Students often do their assignments at the last minute. At least, I did; now I pay my taxes at the last minute!
My sister says that she was "feeling sick," and she "couldn't get out of bed," meaning she was so sick she had to lay down."
I said that I have "never given a children's birthday party, but how hard" can "it be," meaning it could not be very difficult. Of course, I was wrong!
"First," I say, "I had to go to the party supply store to get a few things." A party supply, "supply," store is a store that sells things for - that's right - having a party. The word supply, as a noun, usually means a set of things that you need to do something - that you can use to do something. So, you can have, for example, a supply of Coca-Cola; that would be many bottles of Coca-Cola that you can use for your parties and so forth.
Well, I go to a party supply store, and "I couldn’t believe all the stuff people could buy for children’s parties. There was an aisle with all kinds of party invitations." An aisle, "aisle," is a place where you walk in a store. Usually there are things on both sides of the aisle, so it's like a space between where they have the thing that you want to buy. And, there were "all kinds of," or many different kinds of "party invitations." An invitation is a piece of paper that asks you to go somewhere, usually for a party or for a special occasion - a special event. For example, if you get married - I don't recommend it, but if you get married, you will have a wedding invitation that you will send to your friends and family asking them to come to your wedding and, you hope, bring nice gifts! A party invitation is an invitation to a party.
Well, some of the things that are in the store included "party favors, streamers, and other decorations." A party favor, "favor," is a small gift that you give to people who come to your party, especially for children. It's very common in the US at birthday parties for all the children to receive a small gift, even if it isn't their birthday. Now, when I was growing up we didn't have children's birthday parties very much because there were too many of us children, so we didn't have gifts for people who came over - very sad, I know!
A streamer, "streamer," (the plural is streamers) is a long, narrow piece of paper, usually a colored paper - red, blue, green - that you put on the walls and the doors for a party. It's usually one or two inches wide and it's long, and it looks nice to decorate the room with streamers
"Fortunately," I say, "my sister had already bought most of the things. All I needed to pick up," meaning the only things I needed to buy, "were some candles for the birthday cake and some helium balloons." Candles, "candles," are pieces of wax that have a string in it that burns and gives you light. A birthday cake, "cake," is what you eat. It's the sweet thing that you eat at a birthday party. You can also have a wedding cake.
There are also "helium balloons." A balloon, "balloon," is a thin, round piece of plastic that you put air into. You can also put a special gas called helium, "helium," and that will make the balloon rise up in the air.
"After the party supply store" - after going to the party supply store - I went to "the grocery store" and picked up the cake. I had to make sure that they had spelled my nephew's name "correctly on the top in icing." Icing, "icing," is a sweet, thick, usually colored mix of sugar, milk, butter that you use to write words on a cake. The icing is the sweet top part. We sometimes use the expression it's icing on the cake, that means that it is an additional benefit. After something else good that you get, it is something additional that is also good. Here, icing refers to the sweet icing they use to write the name on the cake.
I was now "ready for the party," so "When the kids arrived," I gave them all their presents. A present, "present," is just another word for a gift. There are actually a couple of meanings, however, of the word present; take a look at our Learning Guide for more information on that.
I was very "glad," I say, "when the clown my sister had hired arrived." A clown, "clown," is a person usually that has white paint on their face and other colors, and they're dressed in very - what we would call - bright, "bright," colors, and these would be yellow or red or something that is very easy to see. And, a clown does things to make people laugh, especially children.
The clown came and "entertained the kids." After a little while, "we sang 'Happy Birthday,'" and "my nephew blew out the candles." To blow, "blow," out (blew, "blew," is the past tense) the candles means to - to push air through your mouth to stop the little fire on top of the candle from burning.
The song, "Happy Birthday," in English is one you may know; I will attempt now to sing it:
Happy birthday to you,
Happy birthday to you.
Happy birthday dear Jeffrey,
Happy birthday to you.
And then sometimes we add:
And many more.
Yes, I really do need someone to teach me how sing!
At the end of the party, "the kids played with" my nephews "new toys." A toy, "toy," is something that children play with.
I end the story by saying that I had "to hand it to my sister." The expression to hand it to someone means to say that someone did something very well - to recognize that someone did something very well. So, I have to hand it to my sister. There are actually couple of meanings of that word or expression; take a look at our Learning Guide for more information.
At the end of the story I say, "I’m exhausted and my ears are ringing!" When we say your ears are ringing, "ringing," we mean that you can still hear the noise of something after the noise stops - you can hear it in your ears. If you go to a rock concert and they play loud music, when you come home your ears are often ringing - you can still feel, or hear rather, the noise in your ears.
Now let's listen to the dialogue, this time at a native rate of speech.
[start of story]
My sister called me at the last minute to help her with my nephew’s birthday party. She was really feeling sick and couldn’t get out of bed. I’d never given a children’s party before, but how hard could it be? Well, I found out.
First, I had to go to the party supply store to get a few things. I couldn’t believe all the stuff people could buy for children’s parties. There was an aisle with all kinds of party invitations and another one with party favors, streamers, and other decorations. Fortunately, my sister had already bought most of the things we needed earlier in the week. All I needed to pick up were some candles for the birthday cake and some helium balloons.
After the party supply store, I stopped at the grocery store to pick up the birthday cake. My sister had ordered it the week before, so all I had to do was to pay for it and to make sure nephew’s name was spelled correctly on the top in icing.
Two hours later, I was ready for the party. When the kids arrived with their parents, I took the birthday cards and presents they had brought, and I handed each child some party favors. I was so glad when the clown my sister had hired arrived, and she entertained the kids with games. I have never seen so many kids with so much energy! A little later, we sang “Happy Birthday,” my nephew blew out the candles, and we cut the cake. My nephew opened his presents and the kids played with his new toys. The kids had a good time and so did my nephew.
I have to hand it to my sister. I don’t know how she does it. After three hours with 15 young kids, I’m exhausted and my ears are ringing!
[end of story]
The script for today's podcast was by Dr. Lucy Tse.
That's all we have time for. From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
last minute- – the latest possible time before something happens; without very much notice before something happens
* We wanted to go to the movies together, but at the last minute, Becky decided not to go because she had a headache.
party supply store – a store that sells things used for having parties, such as invitations, balloons, and decorations
* We had to go to two party supply stores to buy everything we needed for the office New Year’s party because the first one didn’t have enough table cloths.
aisle – a place to walk in a store, with things for sale on both sides; a hallway in a store
* Excuse me. Could you tell me which aisle the ice cream is on?
party invitation – a piece of paper that one puts in an envelope and sends to other people, asking them to be guests at a party
* Liliana is crying because all of her friends received party invitations for Mickey’s birthday and she didn’t get one.
party favor – a small gift given to guests at a party, especially for children
* At Christopher’s birthday party, all the children received a bag of party favors with a small toy and some candy.
streamer – long, narrow strips of colored paper that are hung on walls and doors for a party
* Her family put up pink, yellow, and white streamers all over the house to welcome home the new baby.
candle – a stick of wax with a string in the middle that is lit with fire to give light
* There was no electricity during the storm, so we lit candles in the living room.
birthday cake – a cake (a sweet, bread-like dessert) that is used to celebrate someone’s birthday and is usually decorated with the person’s name
* Ahmed received two birthday cakes last year: one from his co-workers at the office, and another one from his family and friends at home.
helium balloon – a thin, round piece of plastic that is filled with helium gas and then tied at the bottom, so that it rises (floats up) in the air
* When Frederick broke his leg, his friends gave him big helium balloons that said, “Get well soon!”
icing – a sweet, thick, colored mixture of sugar, milk, butter, and coloring that is used to write words on cakes as decoration
* Damian asked Leticia to marry him by writing, “Will you marry me?,” in red icing on a white cake.
present – a gift; something given to someone else, usually for a special event
* I received three presents for my birthday: a new sweater, a basketball, and a new book by my favorite author.
clown – a person who has a painted face and is dressed in bright colors, who does silly things to make people laugh
* Chuck laughed when he saw the clown with a red nose and big shoes walking in the park.
to blow out the candles – to push air out of one’s mouth to stop the fire burning on candles that are on top of a birthday cake
* We turned off the lights and sang “Happy Birthday,” and then we waited for Henry to blow out the candles so we could start eating the cake.
toy – something for children to play with, such as a small doll, truck, or ball
* When I was a child, toys were simple, but now, toys are usually electronic and need batteries.
to hand it to (someone) – to say that someone does something well; to recognize that someone does something well
* I have to hand it to Kai for making the best food I have ever eaten.
(one’s) ears are ringing – the feeling that one can still hear the noise from a noisy event that has already ended
* That concert was too loud. Our ears were ringing for hours after it was over.
Comprehension Questions
1. Why does the birthday cake have icing?
a) Because the icing keeps the cake cold.
b) Because the icing decorates the cake.
c) Because the icing holds the candles on the cake.
2. What kind of presents did the nephew receive?
a) Toys
b) Balloons
c) Candles
Answers at bottom.
What Else Does It Mean?
present
The word “present,” in this podcast, means a gift or something that is given to someone else: “I need to buy a present for Annie, because tomorrow is her birthday.” The word “present” also means something that is current or happening now, not in the past or future: “Considering the present economy, I think we should wait a few years to buy a house.” As a verb, “to present (someone)” means to introduce someone to another person: “Yessenia, I’d like to present my mother, Irma.” Or, “Ladies and Gentlemen, I’d like to present our speaker for today, Dr. Jeff McQuillan.” The verb “to present (someone) with (something)” means to give something to someone, especially an award or honor: “The soldier was presented with a medal of honor for his bravery in the war.”
to hand it to
In this podcast, the phrase “to hand it to (someone)” means to say or recognize that someone does something well: “You have to hand it to Bea that she’s the best soccer player on the team.” “To give a hand to (someone)” means to applaud or clap your hands together to make noise to show someone that you like what they have done: “Please give a hand to the musicians.” “To lend (someone) a hand” means to help someone with something: “Can you please lend me a hand with these boxes? They’re very heavy.” “To lay or get (one’s) hands on (something)” means to find or get something: “As soon as I get my hands on some money, I’m going to buy that new pair of shoes.”
Culture Note
In the United States, most parents organize birthday parties for their young children. Sometimes the party is at a park or restaurant, but usually the “guests” or people who come to a party come to the child’s home.
When they “arrive” or come to the home, the children give the “birthday boy” or “birthday girl” a present, which is put on a table. Then the children play together. Once all the children have arrived, the parents ask them to sit at a table and eat. They might have sandwiches or pizza, or any other kind of food that children like and that is easy to eat.
When everyone has finished eating, the parents turn off the lights and bring in the birthday cake with lighted candles. The cake usually has one candle for each year of the child’s age, meaning that a birthday cake for an eight-year-old child would have eight candles. The guests sing the song, “Happy Birthday.” Then the birthday boy or girl closes his or her eyes, “makes a wish” (thinks about something that he or she wants to get or have happen), and blows out the candles. If the birthday boy or girl is able to blow out all the candles in only one breath, it means that the wish will come true. Then the birthday boy or girl opens presents and thanks the guests for them. The children usually play with the new toys until their parents come to take them home.
At many parties, there are simple games for the children to play. Sometimes there are clowns or “cartoon characters” (like Mickey Mouse) who play with the children. Some birthday parties are very expensive and “elaborate” (with many arranged parts or details) but other birthday parties are quite simple.
Comprehension Answers
1 - b
2 - a