

= hormone replacement therapy 激素替代疗法 -> 对绝经后女人的健康有好处
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css



'''


== Millions of women are missing out on hormone replacement therapy 数以百万计的女性, 错过了"激素替代疗法"

Menopause (n.)绝经期；（妇女的）更年期 harms (v.) women’s bones, brains, hearts and immune systems.
It is associated with a higher risk of osteoporosis 骨质疏松；骨质疏松症 and fragility 脆弱性;易碎性 fractures （指状态）骨折，断裂, increased (v.) _abdominal 腹部的 fat_ 脂肪, and a heightened (v.a.)加剧 risk of contracting 感染,得（病） diabetes 糖尿病, explains Susan Davis, a professor of women’s health at Monash University in Australia.


The hormonal (a.)荷尔蒙的，激素的 changes of menopause `谓` also seem to make women age (v.)变老 faster.
They speed up _cellular (a.)由细胞组成的，细胞的 ageing_ (n.) by about 6%, when age is measured by the genetic changes in the blood.
It is suspected (a.)怀疑；感觉有问题；不信任 that /`主` the insomnia 失眠（症）  后定 associated (a.)有关联的；相关的 with menopause `谓` could be causing this.

Oestrogen 雌激素 is particularly important in maintaining (v.) the health of women’s hearts.
Before menopause /women have fewer _heart attacks_ than men.
After menopause /the risk increases (v.) as `主` the elasticity 弹性；弹力 of _the coronary (a.)冠状动脉的 arteries_ 动脉 `谓` decreases (v.)减少,降低 along with their oestrogen 雌激素 levels.

[.my2]
更年期会损害女性的骨骼、大脑、心脏和免疫系统。澳大利亚莫纳什大学(Monash University)的女性健康教授苏珊•戴维斯(Susan Davis)解释说，##肥胖会增加"骨质疏松"和"脆性骨折"的风险，##增加腹部脂肪，并增加患糖尿病的风险。 +
更年期的荷尔蒙变化, 似乎也会让女性衰老得更快。当通过血液中的基因变化, 来测量年龄时，它们会使细胞衰老速度加快约6%。人们怀疑与更年期相关的失眠, 可能是造成这一现象的原因。##雌激素在维持女性心脏健康方面, 尤为重要。##绝经前女性的心脏病发作, 比男性少。#绝经后，随着冠状动脉弹性的降低, 和雌激素水平的降低，患病风险增加。#

[.my1]
.标题
====
.menopause
/ˈmenə-pɔːz/ 绝经期；（妇女的）更年期 +
-> 来自拉丁语menopausis,停经，来自menses,月经，词源同moon,pausis,暂停，停止，词源同pause.引申词义更年期。


.osteoporosis
/ˌɑːstioʊ-pəˈroʊ-sɪs/ 骨质疏松；骨质疏松症 +
⇒ osteo-,骨的，-por,孔，洞，词源同port,porous.引申词义骨质疏松症。

.fracture
⇒ -fract-打破,打碎 + -ure. 词源同break, fragment, fraction.用于医学名词。

.insomnia
/ɪnˈsɑːm-niə/ 失眠（症） +
in-,不，非，-somn,睡觉，词源同somnolent,somnambulist.即没法睡觉，引申词义失眠。

.oestrogen
/ˈestrə-dʒən/  雌激素


.coronary
⇒ 词源同corolla, 花冠。解剖学术语，因心脏上面的血管形似花冠而得名。

.elasticity
/ˌiːlæ-ˈstɪ-səti/ 弹性；弹力


====



In 1966 Robert Wilson, a doctor, wrote a book called “Feminine （指气质或外貌）女性特有的，女性的 Forever”.
In it, he argued that /主 women’s loss of hormones after menopause 谓 /give rise to a serious, painful and often crippling (a.)严重损害健康的; 致残的 illness, known as oestrogen 雌激素-deficiency (n.)缺乏；缺少；不足 disease.
主 A regular (a.)规则的；有规律的；定时的 course 行动方式,（医疗、服药等的）疗程 of oestrogen supplements 补充（物）；添加物 /系 was the solution, he suggested.


By the turn of the millennium 一千年，千年期（尤指公元纪年） hormone-replacement therapy 治疗；疗法 was extremely popular.
In America [before 2001] some 20% of post-menopausal 绝经后的 women used it at some point.

By then /a synthetic 人造的；（人工）合成的 form of progesterone 孕酮；黄体酮 was being administered  给予，施用（药物等） /to make sure that sth is done fairly 公平合理地；公正地 and [in the correct way] 施行；执行 alongside oestrogen; it had been shown  证明；表明 /to protect women from an increased risk of uterine (a.)有关子宫的 cancer /caused by giving oestrogen 雌激素 [on its own].

[.my2]
那时, 一种合成形式的"黄体酮", 与"雌激素"一起使用; 它已经被证明可以保护妇女避免因单独注射"雌激素"而增加的患"子宫癌"的风险。 +
 +
1966年，医生罗伯特·威尔逊写了一本名为《永远女性化》的书。在这本书中，他认为女性在绝经后失去荷尔蒙, 会导致一种严重的、痛苦的、常常是致命的疾病，即雌激素缺乏症。他建议，解决方案是定期服用雌激素补充剂。 +
在世纪之交，激素替代疗法还是非常流行。在2001年以前，美国有20%的绝经后妇女使用过它。那时, 一种合成形式的黄体酮, 与雌激素一起使用; 它已经被证明可以保护妇女避免因单独注射雌激素而增加的患子宫癌的风险。

[.my1]
.标题
====
.cripple
⇒ 同源词：creep 归类词：lame (adj.) 跛的,瘸的cripple (n.) 跛子,瘸子;(vt.)使跛limp (v.) 跛行,一瘸一拐地走

.A regular course of oestrogen supplements
定期服用雌激素补充剂

.synthetic ⇒ syn-共同,同时 + thesis放置(sis略) + -tic形容词词尾 同源词：thesis

.uterine
/ˈjuːtə-raɪn/ 子宫的 +
-> From Middle French utérin, from Late Latin uterinus ‎(“pertaining to the womb" also "born of the same mother”), from Latin uterus ‎(“womb”).

====


The benefits of HRT seemed (v.) clear. Most immediately 紧接地；直接地, it offered relief (n.) （焦虑、痛苦等的）减轻，缓和 from the miserable  痛苦的；非常难受的；可怜的 symptoms of menopause.
In the longer term /it reduced the risk of osteoporosis 骨质疏松 (which rises (v.) after menopause) /and therefore the risk of bone fractures.
Women `谓` liked that /it seemed to stop their skin thinning (probably because it boosts (v.) the levels of collagen 胶原蛋白, a protein).
It was thought 它被认为 /to reduce (v.) the risk of cognitive 认知的；感知的 decline.

But most importantly, studies suggested that /it prevented the onset (n.)开端，发生，肇始（尤指不快的事件） of cardiovascular (a.) 心血管 disease  —  one of the biggest killers of women.


[.my2]
HRT的好处似乎很明显。最直接的是，它缓解了更年期的痛苦症状。从长期来看，它降低了骨质疏松症(绝经后会增加)的风险，因此也降低了骨折的风险。女性还喜欢它似乎能阻止皮肤变薄(可能是因为它能提高胶原蛋白的水平)。它被认为可以降低认知能力下降的风险。但最重要的是，研究表明，它可以预防心血管疾病 — 女性的最大杀手之一。

[.my1]
.标题
====
.collagen
⇒ coll, 胶，词源同cling, glue. -gen, 产生，词源同antigen, generate.

.onset
(n.)[ sing.] the beginning of sth, especially sth unpleasant 开端，发生，肇始（尤指不快的事件） +
-> on,在上，向上，set,开始。 +
- the onset of disease/old age/winter 疾病的发作；老年的开始；冬天的来临

.cardiovascular
/ˌkɑːr-dioʊ-ˈvæ-skjələr/ (a.) 心血管的 +
-> card, 心脏。-vas, 管，容器，词源同vase, vessel.


====


But then /a bombshell 出乎意料的事情，意外消息（常指不幸） dropped.
In 2002 主 the results of a large randomised (a.)随机化的 trial （对能力、质量、性能等的）试验，试用 /conducted by America’s National Institutes of Health, known as the Women’s Health Initiative 倡议；新方案 (WHI), /谓 were rushed （使）仓促行事，匆忙行事，做事草率 into publication.

It concluded that /`主` taking oestrogen with synthetic 人造的 progesterone 孕酮 /`谓` increased women’s risk of breast （女子的）乳房 cancer, heart attacks, strokes 中风 and blood clots 血凝块；血块.
Women were told that /the dangers of HRT `谓` mostly outweighed 重于；大于； (在重要性或意义上) 超过 any benefits.

But `主` the first conclusions of _the WHI 妇女健康倡议 study_, #on# which /so much antipathy (n.)厌恶；反感 to HRT is still #based#, 谓 were almost entirely wrong.
The study had hoped to look at strategies 策略 for preventing heart disease, cancer and osteoporosis 骨质疏松 /in post-menopausal women.


[.my2]
但接着一颗重磅炸弹落了下来。2002年，由美国国立卫生研究院进行的一项大型随机试验，即妇女健康倡议(WHI)的结果, 被迅速发表。研究得出的结论是，将雌激素与人造黄体酮一起服用, 会增加女性患乳腺癌、心脏病、中风和血栓的风险。妇女们被告知，荷尔蒙替代疗法的危险远远大于益处。 +
但是，WHI研究的第一个结论, 几乎是完全错误的，而对激素替代疗法的许多反感, 仍然是基于此第一个结论而做出。这项研究, 希望着眼于探寻策略, 用来预防绝经后妇女会患心脏病、癌症和骨质疏松症。

[.my1]
.标题
====
.bombshell
⇒ bomb, 炸弹。shell, 弹壳。

.rush
(v.) ~ (sb) (into sth/into doing sth)to do sth or to make sb do sth without thinking about it carefully （使）仓促行事，匆忙行事，做事草率 +
快速运输；速送 +
- Ambulances rushed the injured to the hospital. 救护车迅速将伤员送往医院。

.WHI
妇女健康倡议Women’s Health Initiative


====


It is now clear that /主 the long-term benefits of HRT for women /given 考虑到 it as they enter menopause /系 are significant.
A careful reanalysis 重新分析 of the studies showed that /women in their 50s were actually 31% less likely to die /in the five to seven years 后定 that they were taking hormones.
For women who have had their uterus 子宫 removed /or who start menopause before the age of 45, it is life-saving, preventing osteoporosis and heart disease for as long as 18 years.

There is a tiny increase in the rates of breast cancer among HRT-users /after five years of the treatment.  This was lower *than* the risk 后定 from working as a flight attendant  服务员；侍者.


[.my2]
现在很清楚，激素替代疗法, 对进入更年期的妇女的长期益处, 是显著的。
对这些研究进行仔细地重新分析后, 表明，在服用激素的五到七年内，50多岁的女性的死亡率, 实际上降低了31%。
对于那些已经摘除子宫, 或在45岁之前进入更年期的女性来说，这是一种救命的方法，可以预防骨质疏松症和心脏病, 长达18年之久。 +
虽然接受"荷尔蒙替代疗法"治疗5年后，"乳腺癌"的发病率略有上升, 但这比做空乘的风险还要低。

[.my1]
.案例
====
.that they were taking hormones
中的 "that" 是引导一个定语从句的连词，修饰先行词 "the five to seven years"，整个句子可以理解为"在她们服用激素的五到七年期间"。
====



主 A study published in the Lancet, a British medical journal, earlier this year /谓 has reignited（使）重新燃烧；再点燃 controversy (n.)（公开的）争论，辩论，论战 over _the level of risk of breast cancer_ that comes with hormone therapy.
But Ms Davis and others worry that /its conclusions are not reliable. Moreover /any increase in risk must be weighed 认真考虑；权衡；斟酌 against that of developing other diseases.

[.my2]
今年早些时候发表在英国医学杂志《柳叶刀》(Lancet)上的一项研究，再次引发了关于激素疗法会导致乳腺癌风险水平的争议。
但是戴维斯女士和其他人担心, 其结论不可靠。此外，#某项治疗可能造成的任何风险的增加, 都必须与"不用这种治疗, 而发展出其他疾病"的风险, 进行权衡。# +
chatgpt : 任何风险增加, 都必须与"患其他疾病的风险"相对比。



In the absence of such studies, HRT remains 方式状 in medical limbo （尤指因等待他人作决定）处于不定状态. And so /women in their late 40s and early 50s /are losing out 得不到（需要或觉得应有的东西）.
The window of opportunity to begin HRT in order to capture (v.) its full benefits — including resisting 抵制；阻挡; 使不受…的伤害 the effects of cognitive decline — 系 may be *as little as* two or three years.

[.my2]
在缺乏此类研究的情况下，HRT仍处于医学上悬而未决的状态。因此，40多岁和50多岁的女性, 正在失去被治疗的机会。
开始进行"激素替代疗法", 以获得其全部好处(包括抵抗认知衰退的影响)的机会, 窗口期可能只有两到三年。

[.my1]
.标题
====
.ignite
⇒ -ign-火 + -ite动词词尾

.weigh :
~ sth (up) /~ (up) sth (against sth) : to consider sth carefully before making a decision 认真考虑；权衡；斟酌

.limbo
⇒ 词源不详，可能来自limber, 柔软的，灵活的，用来指西印度群岛的一种舞蹈，舞者需后仰，且越来越低，引申词义处于不定状态。 +
灵薄狱（limbo），意思是“地狱的边缘”，指天堂与地狱之间的区域。电影《盗梦空间》中，limbo被译成了“迷失域”，指的是潜意识的边缘。

.LOSE OUT (ON STH) :
to not get sth you wanted or feel you should have 得不到（需要或觉得应有的东西）
====


'''

== <pure> Millions of women are missing out on hormone replacement therapy


Menopause harms  women’s bones, brains, hearts and immune systems. It is associated with a higher risk of osteoporosis and fragility fractures, increased abdominal fat, and a heightened risk of contracting diabetes, explains Susan Davis, a professor of women’s health at Monash University in Australia.

The hormonal changes of menopause  also seem to make women age faster. They speed up cellular ageing by about 6%, when age is measured by the genetic changes in the blood. It is suspected that  the insomnia associated with menopause could be causing this. Oestrogen is particularly important in maintaining  the health of women’s hearts. [Before menopause] women have fewer heart attacks than men. [After menopause] the risk increases  as the elasticity of the coronary arteries decreases  along with their oestrogen levels.


In 1966 Robert Wilson, a doctor, wrote a book called “Feminine Forever”. In it, he argued that women’s loss of hormones after menopause give rise to a serious, painful and often crippling illness, known as oestrogen-deficiency disease. A regular course of oestrogen supplements was the solution, he suggested.

[by the turn of the millennium] hormone-replacement therapy was extremely popular. [In America before 2001] some 20% of post-menopausal women used it [at some point]. [By then] a synthetic form of progesterone was being administered alongside oestrogen; it had been shown to protect women from an increased risk of uterine cancer caused by giving oestrogen [on its own].


The benefits of HRT seemed clear. Most immediately, it offered relief from the miserable symptoms of menopause. [In the longer term] it reduced the risk of osteoporosis (which rises after menopause) and therefore the risk of bone fractures. Women liked that it seemed to stop their skin thinning (probably because it boosts the levels of collagen, a protein). It was thought to reduce the risk of cognitive decline. But most importantly, studies suggested that it prevented the onset of cardiovascular disease — one of the biggest killers of women.


But then a bombshell dropped.

In 2002 the results of a large randomised trial conducted by America’s National Institutes of Health, known as the Women’s Health Initiative (WHI),  were rushed into publication. It concluded that taking oestrogen with synthetic progesterone increased women’s risk of breast cancer, heart attacks, strokes and blood clots. Women were told that the dangers of HRT mostly outweighed  any benefits.

But the first conclusions of the WHI study, on which so much antipathy to HRT is still based ,  were almost entirely wrong. The study had hoped to look at strategies for preventing  heart disease, cancer and osteoporosis in post-menopausal women.


It is now clear that the long-term benefits of HRT for women given it as they enter menopause are significant. A careful reanalysis of the studies showed that women in their 50s were actually 31% less likely to die in the five to seven years that they were taking hormones. For women who have had their uterus removed  or who start  menopause before the age of 45, it is life-saving, preventing osteoporosis and heart disease for as long as 18 years. There is a tiny increase in the rates of breast cancer among HRT-users after five years of the treatment. This was lower than the risk from working as a flight attendant.


A study published in the Lancet, a British medical journal, earlier this year has reignited controversy over the level of risk of breast cancer that comes with hormone therapy. But Ms Davis and others worry that its conclusions are not reliable. [Moreover] any increase in risk must be weighed against that of developing other diseases.



'''
