= 1155
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,155 – Getting an Online Degree.
This is English as a Second Language Podcast episode 1,155. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. Why? Well, so you can download the Learning Guide for this episode. The Learning Guide contains a complete transcript of everything we say, in addition to a complete list of the vocabulary words and a culture note related to this episode’s topic.
The topic of this episode is getting an online degree – getting a college degree from a college on the Internet. Sounds cool. Let’s get started.
[start of dialogue]
Carlos: So where are you planning on attending college?
Torrie: I’ve picked Harford University.
Carlos: The only Harford University I’ve heard of is a degree mill.
Torrie: I’m sure it’s not the same one. The Harford University I’m attending is accredited, at least I’m pretty sure it is. The best part of going to Harford is I’ll never have to attend classes on campus. I can do all of my coursework online.
Carlos: You want to attend an online university? There are some legitimate ones that offer good distance education, but many have low admissions standards and don’t provide a very good education.
Torrie: Not Harford. It’s a good degree-granting institution, and they even give you credit for relevant life experience. I won’t need to take very many courses to graduate.
Carlos: That sounds pretty fishy to me.
Torrie: Don’t worry. My transcript and degree will be indistinguishable from those from a traditional university, without nearly as much work.
Carlos: That should tell you something. How is their job placement rate?
Torrie: I’m not sure, but I’m pretty sure I’ll be as competitive as any other college graduate.
Carlos: If you say so. What are you doing right now?
Torrie: I’m playing a video game stealing cars. At Harford, that’s considered relevant life experience. Cool, huh?
Carlos: Yeah, cool.
[end of dialogue]
Carlos says to Torrie, “So where are you planning on attending college?” “To attend (attend) college” means to be a student at a college, to go to a university. Torrie says, “I’ve picked Harford University.” “To pick” (pick) means to select, to choose. Carlos says, “The only Harford University I’ve heard of is a degree mill.” A “degree” (degree) is what you get after you complete a course of study at a university. If you study for four years, you usually get a bachelor’s degree.
A “degree mill” (mill), however, is actually a business that sells degrees, basically. It looks like a college or university on the Internet, or in the newspaper, but really it just gives out degrees – pieces of paper – without you having to do very much. Torrie says, “I’m sure it’s not the same one.” She’s sure that the Harford University she’s going to study at isn’t a degree mill.
She says, “The Harford University I’m attending is accredited, at least I’m pretty sure it is.” For a university to be “accredited” (accredited) means that some professional organization, some professional association, has examined the college and determined that it meets certain standards. Who runs this organization? Well, the colleges that accredit themselves. It’s an interesting system. Anyway, in the United States, most people try to get a degree from an accredited university because it’s recognized, rightly or wrongly, as having a certain level of quality.
Torrie says, “The best part of going to Harford is I’ll never have to attend classes on campus.” A “campus” (campus) is the land and the buildings that a college or university has. Some colleges have more than one campus. They have buildings and land in different parts of the city, or even a state or country. Torrie says that she will not have to “attend,” or go to, “classes on campus.” She says, “I can do all of my coursework online.” “Coursework” (coursework) – one word – here just means classes, the classes that you are taking. Carlos says, “You want to attend an online university?”
An “online university” is a university that offers all or most of its classes over the Internet. This isn’t really a new idea, in the sense that colleges and universities and schools sometimes offered classes before the Internet using what we would call “correspondence courses.” They would mail things to you and you would read the books and take the tests and then mail them back to the university. So, the idea of getting an education without actually going to a school building or going on campus isn’t completely new.
Carlos says, “There are some legitimate ones,” meaning legitimate online universities, “that offer good distance education, but many have low admissions standards and don’t provide a very good education.” “Legitimate” (legitimate) means real or not false, not fake – “valid,” we might say. A “legitimate university” is one that does what a university is supposed to do.
“Distance education” is a general term that refers to any kind of education or coursework that is done without you going to a school’s campus. Distance education could involve video education – having video courses, or even seeing a lecture by a professor over the Internet on live video. It could include sending things in the mail. It could include going to a website. All of these are kinds of distance education. Carlos warns, however, that many of these online universities have low admissions standards.
“Admissions standards” refers to the requirements that you have to have in order to get into a college, university, or school. To have “low admissions standards” means it’s not very difficult to get into the school. Again, people associate the difficulty of getting into a college with the quality of that college. I don’t think that’s always the case, but that’s what people think, just like people think accredited universities are somehow better than unaccredited universities. That might be true in general, but it isn’t always true. Anyway, I’m giving my own opinions here. Let’s get back to the story.
Torrie says that Harford it is not one of these universities that has low admissions standards. She says, “It’s a good degree-granting institution.” “Degree-granting institutions” are ones that, well, give you a degree, such as a bachelor’s degree or some other kind of degree. Torrie says, “They even give you credit for relevant life experience.”
There are two kinds of classes you can take at a university or college. One is a “credit (credit) class.” The other is a “non-credit class.” A “credit class” is a class that counts towards, or is included in, the total number of classes that you need to take in order to graduate. Most universities assign, or give, classes a certain number of credits. You need a certain number of credits then to graduate. You could take a class that gives you five credits – usually that’s a class that meets more or has more class time and is more work than a class that is only three credits.
To graduate from a university or college in the United States usually requires I think around 180 credits or so, more or less. The number is arbitrary in a way, but the university needs a way of determining how much education you are getting, and it needs some sort of standard to determine how much is enough to get a degree. A “non-credit class” is a class that you take but doesn’t count toward your degree – that is, the university won’t include those credits when it counts up the number that you need to graduate, to get a degree.
Torrie says that Harford University gives you credit for “relevant (relevant) life experience.” “Relevant” means it’s related to or is significant for some particular purpose or topic. Some colleges and universities will look at your experience – say, if you worked in business for many years – and give you a certain number of credits for that experience so you don’t have to take classes about things that you already know about.
Now, most colleges and universities don’t do very much of this, but there are some that will give you credit for relevant life experience if it is connected to the content of a certain class. Torrie says, “I won’t need to take very many courses” (or classes) “to graduate,” to finish. Carlos says, “That sounds pretty fishy (fishy) to me.” Something that is “fishy” is something that is suspicious, something that doesn’t seem right, something that may be dishonest, even.
Torrie says, however, “Don’t worry. My transcript and degree will be indistinguishable from those from a traditional university, without nearly as much work.” Your “transcript” (transcript) is an official list of the classes or courses that you took and the grades that you received in a college or university – or any school, really. “To be indistinguishable,” (indistinguishable) means to be unable to tell the difference between two different things. “To be indistinguishable” means that you can’t tell the difference. You can’t say this one is from here and this one is from there.
What Torrie is saying here is that her transcript and degree will be the same, or will look the same, as any traditional university’s transcript and degree, but she won’t have to do very much work. Carlos then says, “That should tell you something.” That expression, “that should tell you something,” means you should realize that there’s a problem here. You should realize that there’s something wrong.
He then asks, “How is their job placement rate?” “Job placement” refers to getting a job once you finish your degree. So, Carlos is asking how good is this college at getting its graduates, the people who finish studying there, a job when they’re done – when they’re done with their education. Torrie says, “I’m not sure, but I’m pretty sure I’ll be as competitive as any other college graduate.” “To be competitive” (competitive) here means to have the same qualifications as someone from a different college.
The word “competitive” can also refer to someone who likes to win, who likes to beat other people in games and contests. Here, however, it really just means that you have the same talent or you have the same qualifications as someone else so that you will have as good a chance as another person of getting a job. A “graduate” (graduate) is a person who has finished his or her education and has, we would say, “earned (earned) a degree.” You can be a high school graduate. You can be a college graduate.
Carlos says, “If you say so.” That expression, depending on how it’s said, usually indicates that the person doesn’t really believe you. “Well, if you say so” – that means I don’t think you’re right, but I’m not going to argue with you. Carlos continues, “What are you doing right now?” Torrie says, “I’m playing a video game stealing cars. At Harford, that’s considered relevant life experience. Cool, huh?”
So, Torrie says that she’s playing a video game, and at this online university she’s going to, they will give her credit for that life experience. She’ll get college credit for playing video games. Torrie says, “Cool, huh?” She thinks it’s okay. She thinks it’s wonderful. Carlos says, “Yeah, cool,” but he says it in such a way to mean, “Well, unfortunately that means that you really are going to a college that is a degree mill” – that this university isn’t really legitimate.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Carlos: So where are you planning on attending college?
Torrie: I’ve picked Harford University.
Carlos: The only Harford University I’ve heard of is a degree mill.
Torrie: I’m sure it’s not the same one. The Harford University I’m attending is accredited, at least I’m pretty sure it is. The best part of going to Harford is I’ll never have to attend classes on campus. I can do all of my coursework online.
Carlos: You want to attend an online university? There are some legitimate ones that offer good distance education, but many have low admissions standards and don’t provide a very good education.
Torrie: Not Harford. It’s a good degree-granting institution, and they even give you credit for relevant life experience. I won’t need to take very many courses to graduate.
Carlos: That sounds pretty fishy to me.
Torrie: Don’t worry. My transcript and degree will be indistinguishable from those from a traditional university, without nearly as much work.
Carlos: That should tell you something. How is their job placement rate?
Torrie: I’m not sure, but I’m pretty sure I’ll be as competitive as any other college graduate.
Carlos: If you say so. What are you doing right now?
Torrie: I’m playing a video game stealing cars. At Harford, that’s considered relevant life experience. Cool, huh?
Carlos: Yeah, cool.
[end of dialogue]
Our thanks to the wonderful Dr. Lucy Tse for her wonderful script.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
degree mill – a business that tries to look like a college or university, but gives out many degrees with very little value to many people with little or no qualifications
* Why doesn’t the government enact a law to shut down these degree mills, so they can’t trick any more students into paying a lot of money for tuition?
accredited – recognized as having met certain standards established by a professional educational association
* If you’re want a degree from a good business school, make sure it’s accredited.
campus – the land and buildings of a college or university
* The university has a beautiful campus with grounds that look like parks, so many students study outdoors on the grass on sunny days.
coursework – the classes that one takes and the studying, reading, writing, and exams that one must complete in order to pass the class
* Are students allowed to work with a partner to complete their coursework, or are they expected to do everything independently?
online university – an academic institution that does not have physical buildings or face-to-face classes, but instead offers all instruction through the Internet
* Online universities have the potential to reach many students, but some people worry that students never personally interact with their professors or each other.
legitimate – real; valid; not false, fake, or pretend
* If that’s a legitimate offer, they should be willing to put it in writing.
distance education – a way of delivering education and instruction to students who are not physically present in a traditional classroom
* High school students in small towns may take advanced math and science classes through distance education.
admissions standards – the requirements that students must meet and the qualifications that they must demonstrate to be accepted as students at a particular school, college, or university
* The top medical schools have high admissions standards.
degree-granting – able to give students academic degrees when they have completed certain coursework and met certain requirements
* We give scholarships to students attending degree-granting institutions.
credit – recognition for completing a certain number of hours of a course in a college or university, or for achieving equivalent experience and knowledge
* How many more credits do you need in order to graduate?
relevant – related to or have significance for a particular topic or subject
* The auditors want to investigate our expenses on the Acme project. Please gather all the relevant receipts for their review.
fishy – suspicious; not honest, straightforward, or transparent; potentially corrupt or dishonest in some way
* Strange people are coming and in and out of my neighbor’s house at all hours. I think something fishy is going on.
transcript – an official document that lists all the courses that a student has taken, including when, with which professor, and what grade the student received
* The attached transcript documents my coursework in information technology.
degree – recognition that one has completed all the requirements for a particular course of study
* Jeremiah earned a degree in economics with a minor in history.
indistinguishable – not able to be differentiated from something else; extremely similar to something else so that people cannot identify differences
* This lamp is indistinguishable from the one I broke. Do you think Mom will notice the difference?
job placement rate – a measure of a university or other organization’s success in helping people find jobs after graduation or the completion of a program, usually expressed as the percentage of people who have accepted a job a certain number of months after graduation
* The university has an impressive job placement rate, but have you noticed how it doesn’t specify the average starting salary?
competitive – having the same or better qualifications, talent, or experience as other people who want to have what one is pursuing, so that one is considered for the opportunity and has a chance to receive or do it
* We receive thousands of applications for each job, so only the most competitive applicants receive an invitation for an interview.
graduate – a person who has earned a diploma or degree
* The university encourages graduates to stay in touch with each other and maintain a strong professional network.
Comprehension Questions
1. What is a degree mill?
a) A place that controls the temperature.
b) A place that grinds cereals into flour.
c) A place that sells worthless academic qualifications.
2. What does Carlos mean when he says, “That sounds pretty fishy to me”?
a) He doesn’t believe everything that Torrie is saying about the university.
b) He thinks the university will offer courses about ocean life.
c) He thinks the program will help Torrie become a better cook.
Answers at bottom.
What Else Does It Mean?
credit
The word “credit,” in this podcast, means recognition for completing a certain number of hours of a course in a university, or for achieving equivalent experience and knowledge: “This semester, I’m taking a three-credit course in organic chemistry and a four-credit course in accounting.” The word “credit” also means praise or recognition for what one has done: “Juanita gets most of the credit for our success. She put in more work than anyone else.” Finally, the phrase “to give credit where credit is due” means to recognize someone for his or her hard work on contributions: “Let’s give credit where credit is due. None of us would be celebrating this sale if Jackson hadn’t spent all night preparing his sales pitch.”
degree
In this podcast, the word “degree” means an academic rank, or recognition that one has completed all the requirements for a particular course of study: “Ivan has two undergraduate degrees from Boston University and a graduate degree from the University of Rochester.” The word “degree” is also used to measure temperature: “Please set the thermostat to 68 degrees.” In mathematics, the word “degree” is used to measure the angle between two lines: “Please draw a triangle with two 30-degree angles.” The word “degree” means extent, or how far something goes: “I agree with you to a certain degree, but not completely.” Finally, the phrase “by degrees” means gradually or very slowly: “Their marriage deteriorated by degrees, but they refused to get a divorce.”
Culture Note
Accreditation for Institutions of Higher Education
In the United States, most “credible” (trustworthy) “institutions of higher education” (universities and colleges; institutions that offer education after high school) seek “accreditation” (recognition of the quality of an educational program by a professional organization). Currently there are 52 “recognized” (on a list published by the U.S. Secretary of Education) national accrediting “bodies” (organizations), and many more regional accrediting bodies. Other accrediting bodies are for particular specialties or professions, or are related to religious organizations.
Accreditation is a “voluntary” (not required) review process; it is not required by law or performed by the government. During the accreditation process, a university or academic program “submits” (gives to organization) information about the quality of its programs, “faculty” (the people who teach), and “facilities” (the buildings and equipment that are used). Some people argue that accreditation places too much “emphasis” (focus and importance) on “inputs” (things that are used to produce something) rather than “outputs” (results), or the students and what they know upon graduation.
Through a “peer review” process, faculty members and administrators from other universities are involved in reviewing the quality of the program. The accrediting team visits the university, usually multiple times, to gather additional information and “obtain” (get) and make “first-hand” (related to what one sees and hears directly, not through another person) observations.
The team “affirms” (says yes to) or “denies” (rejects; says no to) the institution’s accreditation status, but the institution must “maintain” (keep) that status. It must “undergo” (participate in) a reaccreditation process every few years, but the “frequency” (how often something happens) depends on the rules of the particular accrediting body.
Comprehension Answers
1 - c
2 - a