= 1163
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,163 – Types of Religious Leaders.
This is English as a Second Language Podcast episode 1,163. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. I promise, there’ll be no singing if you go there. When you do go there, you can become a member of ESL Podcast and download the Learning Guide for this episode. You can also take a look at the ESL Podcast Store with additional courses in Business and Daily English. And why not like us on Facebook? Go to facebook.com/eslpod.
This episode is a dialogue between Mary and Alexei about types of religious leaders. Let’s get started.
[start of dialogue]
Mary: I feel like an idiot!
Alexei: Why? What happened?
Mary: I just called the bishop over there “Pope.”
Alexei: That’s not so bad. You gave him a promotion. At least you didn’t call him “Rabbi.”
Mary: Don’t laugh! When I agreed to work at this interfaith conference, I didn’t know I’d need a crash course in identifying religious leaders from their dress.
Alexei: It can’t be that hard. That man over there is clearly a cardinal, and the woman next to him is probably a minister by the look of her clerical collar.
Mary: What about the man in robes over there?
Alexei: He’s probably a lama or a guru. He’s definitely not an imam, but I’m not entirely sure how I would address him.
Mary: See what I mean? I keep saying the wrong thing.
Alexei: These religious leaders don’t expect laypeople like you and me to know as much as they do about religious dress.
Mary: That’s what you think! I called that man over there “Preacher” and he gave me a dirty look.
Alexei: No wonder. He’s the caterer.
[end of dialogue]
Mary begins our dialogue by saying, “I feel like an idiot!” An “idiot” (idiot) is a person who isn’t very smart, who is not very intelligent. Alexei says, “Why? What happened?” Mary says, “I just called the bishop over there ‘Pope.’” Our dialogue is about types or names of religious leaders. Mary mentions two names, “bishop” (bishop) and “pope” (pope).
A “bishop” is a senior leader, we might say, in a Christian church. There are different Christian “congregations,” we might call them, or groups that use this term “bishop” for their leaders. The Catholic Church, or the Roman Catholic Church, uses this term “bishop” for its leaders.
The Catholic Church also has another term – as do some other Christian churches, but it’s usually associated with the Catholic Church – and that is “pope.” The “pope” is the leader of the Catholic Church who lives in Vatican City, which is located inside the country of Italy. There are, I should add, a few other Christian churches which also use the term “pope.”
In the Roman Catholic Church, the pope is himself a bishop, but is considered the highest leader of the church. Alexei says, “That’s not so bad. You gave him a promotion.” A “promotion” is when you get a better job in a company. Alexei is making a little joke here. He’s saying that by calling this bishop the “pope,” he’s giving the bishop, in essence, a more important job than he already has.
Alexei says. “At least you didn’t call him ‘Rabbi.’” A “rabbi” (rabbi) is a leader of a Jewish synagogue. A “rabbi” may also be a religious scholar of the religion of Judaism. Mary says, “Don’t laugh. When I agreed to work at this interfaith conference, I didn’t know I’d need a crash course in identifying religious leaders from their dress.” An “interfaith (interfaith) conference,” or meeting, would be something involving two or more religions, especially groups or meetings that involve different religious leaders talking about issues and ideas that they may have in common or that they may differ about.
Mary says that she didn’t know she’d need a “crash course.” A “crash (crash) course” is a very short, usually what we might describe as “intense,” period of studying about something or learning about something, usually because you need to know something right away in order to do something or to perform some action.
For example, if you get a new computer and the computer has software that you have never used before and you have to use it tomorrow to do something, you may decide to take a “crash course” in how to use it. You may decide to spend many hours tonight studying on how to use this particular software. That would be an example of a “crash course” – when you have to learn something very quickly.
“Religious leaders” refer to leaders of particular religions. “Religions” are systems of belief that usually talk about the meaning of life and the origins of life. I think most people know what religion is. Mary says that she didn’t know she needed to take a crash course on identifying, or figuring out, religious leaders from their dress. “From their dress” means how they are dressed. She means that she doesn’t know how to identify religious leaders just looking at the way they are dressed because different religious leaders often dress differently.
Alexei said, “It can’t be that hard,” meaning it isn’t really that difficult. “That man over there,” he says, “is clearly a cardinal, and the woman next to him is probably a minister by the look of her clerical collar.” A “cardinal” (cardinal) is a religious leader, once again in the Catholic Church. A cardinal usually dresses somewhat differently than another kind of religious leader, a bishop. In fact, most cardinals, though not all, are bishops themselves. Cardinals are religious leaders in the Catholic Church that, among other things, participate in electing the next pope, or leader of the Catholic Church.
A “minister” (minister) is a leader of a Christian church. It could be any kind of Christian church, not necessarily a Catholic church. It could be a Baptist church or a Presbyterian church or any one of a variety of Christian groups. In some Christian groups or churches, ministers wear what’s called a “clerical collar.” The word “clerical” (clerical) comes from the word “cleric.” A “cleric” is a religious leader.
“Collar” (collar) here refers to something worn around the neck. The word “collar” usually refers to jewelry or something worn around a person’s neck. You can think of your dog having a collar – that’s something the goes around the dog’s neck that usually you connect something to in order to control the dog – a long rope or a long piece of material called a “leash” (leash).
Well, we’re not talking about dog collars here. We’re talking about religious collars, which are usually pieces of white material – stiff, thick, white material that goes around the neck of a religious leader, a Christian religious leader. Many ministers often wear a black shirt with this white collar that goes around the neck. Mary says, “What about that man in robes over there?” A “robe” (robe) is something you wear over your body, that is very long. It’s almost like a very large dress. It could be worn by a man or a woman.
Alexei says that the man that Mary is pointing at is probably a lama or a guru. A “lama” (lama) is a Tibetan or Buddhist monk, or a title for a religious leader of Buddhism. You can think perhaps of the Dalai Lama, from Tibet. A “guru” (guru) is a spiritual teacher usually associated with Hinduism or Buddhism, or possibly a leader in the “Sikh” (Sikh) religion. Alexei says the man that Mary is pointing at is probably a lama or a guru.
He says, “He’s definitely not an imam, but I’m not entirely sure how I would address him.” An “imam” (imam) is a Muslim religious leader, a leader of a group that believes in Islam (Islam). Alexei says he’s “not entirely sure,” meaning he’s not exactly sure, “how I would address him.” “To address” (address) someone is to speak to someone in a particular way, especially using some sort of title, some sort of name for that person.
For example, if you meet the president of the United States, you would probably say, “It’s nice to meet you, Mr. President.” That’s how we would address the president of the United States. If you were talking to the pope of the Catholic Church, you would say, “Your Holiness” or “Holy Father.” Those are terms of address – how you would talk to that person when you first talk to that person. If you are in a courtroom and you are talking to a judge, the proper form of address is probably “Your Honor” (honor). That’s how you would address, or talk to, that person.
Alexei is not sure how to address some of the religious leaders. Mary says, “See what I mean? I keep saying the wrong thing.” Alexei says, “These religious leaders don’t expect laypeople like you and me to know as much as they do about religious dress.” A “lay (lay) person” is someone who is not a religious leader or who doesn’t have a position of religious leadership within a church or religious group.
Another term for “laypeople” would be “laymen,” although it’s become more popular now to say “laypeople,” but it means the same thing usually, unless someone is distinguishing between a man and a woman, in which case you may say “layman” or “laywoman.” Alexei is basically telling Mary not to worry too much – that these religious leaders don’t expect her to know who’s who, if you will, by their religious dress.
Mary says, “That’s what you think.” The expression “That’s what you think” is usually used to show that you disagree with what the other person says. Usually you say this right before you’re going to present an example of why you think the other person is wrong, and that’s exactly what Mary does. She disagrees with Alexei. She says, “That’s what you think.” And then she gives her example of why Alexei is wrong. She says, “I called that man over there ‘Preacher’ and he gave me a dirty look.”
The term “preacher” (preacher) is another religious title that could be applied to the lots of different people, not just a leader of a religious community or a Christian church, though there are many Christian churches who use “preacher” in the same way that other religious groups use “minister.” Mary says she just called someone “preacher” and that person gave her a “dirty look.” “To give someone a dirty look” means to look at them as if you were angry, to show that you didn’t like what that person said.
Alexei says, “No wonder,” meaning “Well, that’s not surprising.” The person that Mary was talking to is the “caterer.” The “caterer” (caterer) is the person whose job it is to prepare and serve food at a meeting or event. Mary called the caterer, who of course is not a religious leader in any sense, a “preacher,” and that’s why the caterer gave her a dirty look.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mary: I feel like an idiot!
Alexei: Why? What happened?
Mary: I just called the bishop over there “Pope.”
Alexei: That’s not so bad. You gave him a promotion. At least you didn’t call him “Rabbi.”
Mary: Don’t laugh! When I agreed to work at this interfaith conference, I didn’t know I’d need a crash course in identifying religious leaders from their dress.
Alexei: It can’t be that hard. That man over there is clearly a cardinal, and the woman next to him is probably a minister by the look of her clerical collar.
Mary: What about the man in robes over there?
Alexei: He’s probably a lama or a guru. He’s definitely not an imam, but I’m not entirely sure how I would address him.
Mary: See what I mean? I keep saying the wrong thing.
Alexei: These religious leaders don’t expect laypeople like you and me to know as much as they do about religious dress.
Mary: That’s what you think! I called that man over there “Preacher” and he gave me a dirty look.
Alexei: No wonder. He’s the caterer.
[end of dialogue]
If you need a crash course in any kind of special vocabulary, you should talk to our wonderful scriptwriter, Dr. Lucy Tse – or better yet, just listen to her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
bishop – a senior leader in a Christian church, usually with authority and responsibility over a number of churches or church duties
* The bishops are having a meeting to discuss whether women should be allowed to be ministers.
pope – the leader of the Catholic church, who lives in Vatican City
* When the pope traveled to South America, thousands of Spanish-speaking Catholics went to see him.
rabbi – a leader in a Jewish synagogue; a religious scholar of Judaism
* The rabbi explained the importance of eating a kosher diet.
interfaith – involving two or more religions, especially referring to relationships between people of different religions
* They have an interfaith marriage, so their children celebrate both Christmas and Hanukah.
crash course – a rapid, short, and intense period of studying something or learning about something
* They took a crash course in emergency medicine and then went to the site of the earthquake to see what they could do to help.
religious – related to a religion, or a system of beliefs about the origins and meaning of life, particularly control by gods or another higher power
* Heath grew up in a very religious family. He attended church three times a week, prayed before every meal, and listened to only religious music.
cardinal – a high-level leader in the Catholic church, who participates in the selection of a pope
* Wouldn’t it be interesting to sit in on the meetings of the cardinals when they select the next pope?
minister – a leader of a Christian church, especially a Protestant church
* The minister gave a beautiful sermon about the importance of loving one’s neighbor.
clerical – related to the clergy (all the people who have religious duties, or who have been officially approved to perform certain tasks within the church)
* During the week, the minister meets with church members in the clerical office.
collar – a band of stiff fabric wrapped around one’s neck or at the top of one’s shirt
* Please fold your collar down over your tie on the back and sides of your neck.
robes – long, flowing gowns, like a very large dress, usually worn to show one’s position or status and often worn for professional or special occasions
* The arms of the priest’s robes almost caught on fire when he held them too close to the candle flame.
lama – a Tibetan or Buddhist monk, or the title for such a religious leader
* The Dalai Lama is a religious leader who lives and works outside of his homeland.
guru – a spiritual teacher in Hinduism or Buddhism, or a leader in the Sikh religion
* Have you ever asked a guru about the meaning of life?
imam – a Muslim leader; a religious leader in the Islam religion
* The imam wore a turban on his head, covering his hair.
to address – to speak to someone in a particular way, especially using a particular title or formal greeting
* Please address the judge as “your honor.”
layperson – a person without specialized knowledge of a particular subject; an ordinary person, not an expert
* Many scientists struggle to explain their research to laypeople.
that’s what you think – a phrase used to show that one disagrees with what another person says, often immediately before presenting an example of why the other person is wrong
* A: Your wife’s cooking looks great.
B: That’s what you think! Wait until you taste it. It’s always overcooked.
preacher – a person who delivers sermons; a person who speaks in front of the members of a Christian church, delivering a message and interpreting the Bible
* The preacher offers free counseling to young men and women who are planning to get married.
caterer – a person whose job is to prepare and serve food at an event
* Which caterers did you select for the retirement party?
Comprehension Questions
1. Which of these religious leaders would you not expect to see in a Christian church?
a) A bishop
b) A lama
c) A preacher
2. Why does Mary need a crash course?
a) So that she doesn’t keep bumping into people
b) So that she can learn to recognize religious leaders
c) So that she can become an expert on world religions
Answers at bottom.
What Else Does It Mean?
crash course
The phrase “crash course,” in this podcast, means a rapid, short, and intense period of studying something or learning about something: “They took a crash course in Chinese to learn some basic phrases for their trip.” The phrase “crash diet” refers to one’s efforts to eat very little food in order to lose weight very quickly: “Research has shown that although people can lose a lot of weight on a crash diet, they typically gain it back very quickly.” A “crash landing” happens when a pilot has to bring a plane to the ground very quickly in an unsafe way, because there is a major problem with the airplane: “Passengers, please prepare yourselves for a crash landing.” Finally, a “crash” can be a loud noise, especially of things falling: “Did you hear a crash when the tree fell down?”
layperson
In this podcast, the word “layperson” means a person without specialized knowledge of a particular subject: “I can help you reformat your hard drive, but I’m just a layperson. You’ll need to hire a computer specialist for more complicated problems.” The phrase “to get the lay of the land” means to assess and analyze a particular situation at a particular point in time: “The new CEO spent the first few days getting the lay of the land and determining what her focus should be.” Finally, the phrase “the lay of (something)” means what something looks like and how it is laid out, or where the different parts of something are: “Taxi drivers in New York City have a very good understanding of the lay of the city.”
Culture Note
The 700 Club
The 700 Club is an American television show produced by the Christian Broadcasting Network. It “features” (shows) Christian programming, including “profiles” (brief information about) Christian “lifestyles” (ways of living), Christian music, “ministry” (lessons or lectures based on the Bible), “testimony” (statements from people about how their love of God has changed their life), and daily news.
In 1961, a TV station called WYAH-TV began “broadcasting” (showing on TV) Christian programming, but it couldn’t make enough money to continue. So the “host” (the person who leads a show), Pat Robertson, created a “telethon” (a TV show in which people encourage viewers to call in and donate money) to try to get 700 people to donate $10 each. He succeeded, and the show became The 700 Club. It became a daily show in 1966.
The show has approximately one million viewers each day in the United States, and it is also broadcasted in 138 countries in 39 languages. The Christian Broadcasting Networks “estimates” (believes that a number is close to being correct, even though the exact amount is unknown) that the show “reaches” (is seen by) 360 million people each year.
The show encourages people to “call in” (place a phone call to the show). Each day, more than 11,000 people call the show’s “prayer line” (a phone number on which people can make requests for “prayers” (conversations with God), and many others request spiritual “guidance” (advice and help) through email.
The show “tends to be” (is usually) very “conservative” (with traditional ideas), and the hosts have made “controversial” (with strong argument) statements about “homosexuals” (people who are attracted to members of the same sex), “abortion” (the end of a pregnancy), and religious explanations for “terrorist attacks” (efforts to harm people for political or religious reasons) and “natural disasters” (events like hurricanes, earthquakes, and floods).
Comprehension Answers
1 -b
2 - b