= 1165
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,165 – Eating Spicy Foods.
This is English as a Second Language Podcast episode 1,165. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store. Go shopping for courses in Business and Daily English. You can also become a member of ESL Podcast and download the Learning Guide for this episode. All of that, right on our website.
This episode is a dialogue between Akim and Wendy about eating food that is spicy. Let’s get started.
[start of dialogue]
Akim: Oh, this is so good! Why are your eyes watering?
Wendy: It’s so spicy! When you invited me over for curry, I didn’t know it’d be so hot.
Akim: This is mild or maybe medium. I make another version of this that’s much hotter. In fact, I like mine with some extra peppers and some hot sauce. Do you want any?
Wendy: Are you kidding me?! The roof of my mouth is on fire.
Akim: You must have very sensitive taste buds. This has a little kick to it and it’s pungent and zesty, but it’s not too spicy.
Wendy: You must have no taste buds at all if you think this is mild. My mouth needs to cool down from all that heat. I need more water – now!
Akim: All right, but you don’t want to fill up on water. I’ve made a special dessert.
Wendy: Is that supposed to be mild, too?
Akim: No, that really is spicy!
[end of dialogue]
This episode is about eating spicy food. The adjective “spicy” (spicy) refers to a very strong flavor in your mouth that feels like your mouth is on fire, that your mouth is burning. When you eat spicy food, you might have to immediately drink some water because it’s as if your mouth were on fire. Of course, it isn’t actually on fire, but that’s the meaning of this adjective “spicy” when describing food.
Akim says, “Oh, this is so good!” Then he asks Wendy, “Why are your eyes watering?” If your eyes “water,” your eyes begin to fill with what we call “tears” (tears), which is basically fluid that is in your eye that is more than what your eye needs, and of course if there’s more fluid there, then the fluid – the tears come out of your eyes and go down your face. Usually people have their eyes water when they are sad, when they are in pain, or as in the case of our dialogue, perhaps when the food is very spicy.
Wendy says, “It’s so spicy,” referring to the food. “When you invited me over for curry, I didn’t know it’d be so hot.” “Curry” (curry) is a dish usually associated with India, in which you cook meat and or vegetables in a spicy sauce. There are other kinds of curry as well. There’s Japanese curry, which I really like. I also like Indian curry, just to be fair. However, here it appears that Wendy and Akim are eating Indian curry.
Wendy was “invited over” by Akim, meaning Akim said, “Come to my house and we will eat a meal.” Curry can also be one of those foods that is very hot because of the, what we would call, “spices” (spices). The word “spicy” of course comes from the word “spice.” We usually describe spicy food as being “hot.” The word “hot” can be used to describe food in two different ways.
A food or a dish is “hot” when it is physically at a high temperature. The opposite of “hot” in that case would be “cold.” So, food can be hot. Food can be cold. Here, however, “hot” means very spicy. The opposite of “spicy food” is not “cold,” but “mild” (mild). So, we have “hot” and “cold” food, referring to temperature. We have “hot” and “mild” food, referring to the spiciness of the food.
Akim says, “This is mild or maybe medium.” In between “hot” and “mild” food, in terms of spiciness, is “medium” (medium). “Medium spicy” is a little spicy but not too spicy. Of course, that really depends on your taste for food whether you think something is “mild” or “medium.”
Lots of other kinds of dishes can be spicy. Mexican food, for example, can often be spicy. So can food from Thailand and many other countries. I know there are many different types of food out there. I could spend all day mentioning the different kinds of food, but today we’re using as an example Indian curry as being “hot,” “mild,” or “medium.”
Akim says, “I make another dish of this” – that is, of curry – “that’s much hotter. In fact, I like mine,” meaning my curry, “with some extra peppers and some hot sauce.” “Peppers” (peppers) are vegetables that can often make food very spicy, especially the seeds inside of the peppers. Peppers come in different colors, and many peppers aren’t spicy at all, but some of them can be very spicy. Akim also mentions “hot sauce.” Hot sauce is a liquid that some people put on their food that is usually made from spicy peppers.
Akim says, “Do you want any?” meaning any extra peppers and hot sauce. Wendy says, “Are you kidding me?” That expression “Are you kidding me?” when said in a certain way, means “Are you joking with me? Are you crazy?” In other words, it’s said in disbelief – you can’t believe the person is actually telling you what he’s telling you. In this case, Wendy can’t believe Akim actually thinks she wants her food to be even spicier.
She says, “The roof of my mouth is on fire.” The “roof (roof) of your mouth” is the top part of your mouth, the part above your tongue. You have a roof on your house, of course – that’s the top of your house. The roof of your mouth is the top of your mouth. “To be on fire” can mean to be actually burning with a flame, but here it just means to have a burning feeling or sensation because the food is so spicy.
There’s another meaning of the expression “on fire” that’s a little more recent in terms of its use. “To be on fire” can also mean to be doing something very well, to really be excelling or performing in a way that is the best that you can do, perhaps the best that anyone around you is doing.
For example, if you’re a basketball player and you’re scoring a lot of points in a single game, we might describe you as being “on fire,” meaning you’re doing really, really well. We could also say that you’re “hot.” In baseball, a “hot hitter” is someone who’s getting a lot of hits, especially in a short period of time. There is also the song you might have heard by Alicia Keys a few years ago: “This girl is on fire.” Well, she sang it a little better than I did. I’m not really on fire when it comes to my singing right now.
Back to the dialogue. Akim says, “You must have very sensitive taste buds.” “Taste buds” (buds) are those points on your tongue and in the inside of your mouth that can sense the taste of food. We call those “taste buds.” Akim says, “This,” meaning this curry, “has a little kick to it.” When we describe food as having “a little kick (kick) to it,” we mean it’s a little bit spicy. It’s not very spicy.
Akim says, “The food is pungent and zesty, but it’s not too spicy.” “Pungent” (pungent) means having a very strong smell or taste. “Zesty” (zesty) usually refers to food that has a slightly spicy flavor. It’s mild but it’s a little bit spicy. Wendy says, jokingly perhaps, to Akim, “You must have no taste buds at all if you think this is mild. My mouth needs to cool down from all that heat. I need more water – now!” Wendy says that Akim must not have any taste buds if he doesn’t think this food is spicy.
She says, “My mouth needs to cool down from all that heat.” “To cool down” means to lower the temperature of something. Here it just means to feel less of the burning sensation. “Heat” (heat), again, means here something that is caused by very spicy food. People often drink water after they eat spicy food thinking that that will cool down their mouth and make the sensation of the burning disappear. I’m not sure if that actually happens, but people do it. I heard somewhere that if you put salt in your mouth, that will help with the burning sensation. I don’t know. Don’t ask me. I’m not an expert.
Anyway Akim tells Wendy not to “fill up on water” because he’s made a special dessert. “To fill up on” something means to eat or drink a lot of something, so much so that you’re no longer hungry. If you are going to someone’s house for dinner and you have, say, a bag of Macadamia nuts (which are my favorite kind of nuts, by the way, in case anyone’s looking for a Christmas present to buy me), you don’t want to eat all of your bag of nuts. You don’t want to fill up on the macadamia nuts, because then you won’t be hungry for the dinner that you are going to go and eat, or are supposed to eat.
Akim says, “I’ve made a special dessert” (dessert). A “dessert” is usually, in the United States anyway, a sweet food that is served at the end of a meal. Wendy says, “Is that supposed to be mild, too?” She wants to know if the dessert is going to be mild. Akim says, “No, that’s really spicy.” Akim, of course, thinks his curry is mild, so if the dessert is supposed to be spicy, well then it will be really spicy for Wendy.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Akim: Oh, this is so good! Why are your eyes watering?
Wendy: It’s so spicy! When you invited me over for curry, I didn’t know it’d be so hot.
Akim: This is mild or maybe medium. I make another version of this that’s much hotter. In fact, I like mine with some extra peppers and some hot sauce. Do you want any?
Wendy: Are you kidding me?! The roof of my mouth is on fire.
Akim: You must have very sensitive taste buds. This has a little kick to it and it’s pungent and zesty, but it’s not too spicy.
Wendy: You must have no taste buds at all if you think this is mild. My mouth needs to cool down from all that heat. I need more water – now!
Akim: All right, but you don’t want to fill up on water. I’ve made a special dessert.
Wendy: Is that supposed to be mild, too?
Akim: No, that really is spicy!
[end of dialogue]
We serve our English spicy here at ESL Podcast. That’s because our scriptwriter is on fire – Dr. Lucy Tse, of course.
From Los Angeles California, I’m a very mild Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
for eyes to water – for one’s eyes to fill with tears, usually because one is very sad, in pain, or looking at a bright light
* Taking a walk in the snow without sunglasses makes my eyes water.
spicy – flavored with very strong plant substances that produce a burning sensation in one’s mouth
* Mexican food can be spicy, but you can limit it by leaving out the jalapeno peppers.
curry – an Indian dish made by cooking meat and/or vegetables in a spicy sauce flavored with curry, turmeric, and other spices, typically yellow, red, or green
* They ordered the chicken curry and rice.
hot – very spicy; with a flavor that causes a burning sensation in one’s mouth
* At this restaurant, diners can tell the waiter how hot they want the food to be.
mild – not very spicy; only a little bit spicy
* This salsa is too mild. I think it just has tomatoes and onions, and they forgot to put any hot peppers in it
medium – a little bit spicy, but not uncomfortably so
* It’s hard to cook for people who ask for something with “medium” spice, because that can mean very different things to different people
pepper – a green, yellow, orange, or red vegetable that grows on a small bush and may be sweet or spicy, with seeds inside an open interior and flesh (skin) that people eat
* They made a colorful stir-fry with red and green bell peppers.
hot sauce – a flavorful liquid added to prepared foods to make them spicy, typically made by soaking spicy peppers in vinegar and salt
* Would you like hot sauce or ketchup for your scrambled eggs?
the roof of (one’s) mouth – to top part of one’s mouth, above one’s tongue
* Wow, that caramel is really sticky. It’s stuck to the roof of my mouth.
on fire – burning or with a burning sensation because something is very spicy
* How can you eat a raw habanero chili pepper? My mouth would be on fire.
taste bud – one of thousands of points on the tongue and interior of the mouth that can sense taste
* Is it true that some taste buds perceive sweetness, and others perceive saltiness?
a little kick to it – with a little bit of spice or excitement, enough to keep things interesting
* This is the pasta I normally make, but I decided to put some hot sauce in it to give a little kick to it.
pungent – with a very strong smell or taste
* Many children dislike pungent cheeses like blue cheese.
zesty – with an exciting, energizing, pleasant, and slightly spicy flavor
* These lemons are so zesty! The flavor really woke me up.
to cool down – to become cooler; to reduce the temperature of something
* Wait for those hard-boiled eggs to cool down before you try to peel them.
heat – a high temperature; the sensation produced by very spicy food
* Eat a tortilla to cut the heat of the salsa.
to fill up on – to eat or drink a lot of something so that one is no longer hungry
* Stop filling up on the bread, or you won’t be hungry when the waiter finally brings our food.
dessert – a sweet food served at the end of a meal
* What would you prefer for dessert: pudding, ice cream, or cake?
Comprehension Questions
1. Why are Wendy’s eyes watering?
a) Because she is feeling sad.
b) Because she is embarrassed by her reaction.
c) Because the flavor of the food is too intense.
2. What does Wendy mean when she says, “The roof of my mouth is on fire”?
a) She does not like the taste of the food.
b) She bit her tongue and is in pain.
c) She is experiencing a burning sensation from the spices.
Answers at bottom.
What Else Does It Mean?
curry
The word “curry,” in this podcast, means an Indian dish made by cooking meat and vegetables in a spicy sauce flavored with curry, turmeric, and other spices, typically yellow, red, or green: “They made a lamb curry with potatoes, green beans, and apricots, and served it over rice.” The word “curried” means cooked with spicy flavors: “This curried beef is delicious, but too spicy for me.” Finally, the phrase “to curry favor with (someone)” means to do something that is bad or wrong to get other people to like oneself or do what one wants them to do: “Some of the students are trying to curry favor with the teacher before their big exam by bringing her coffee, doughnuts, and flowers.”
heat
In this podcast, the word “heat” means a high temperature, or a feeling of strong spiciness: “The meals served at that restaurant have a lot of heat, but not much flavor.” The phrase “the heat” also refers to the temperature of the surface over which something is cooked: “Please turn down the heat once the water starts to boil.” A “heat wave” is a period of time with extremely high temperatures: “We had an unusual heat wave for a few weeks in late July.” Finally, the phrase “a dead heat” refers to a race or competition where two or more competitors are extremely close or at exactly the same place or number of points, and nobody knows which one will win: “The horse race ended in a dead heat and no one could say who won and who lost.”
Culture Note
Spicy American Foods
In general, American foods aren’t known for being very spicy. However, there are some common traditional foods that are “quite” (very) spicy, such as chili and buffalo wings.
“Chili” is a thick “stew” (a thick soup) typically made from onions, tomatoes “kidney beans” (red beans in a crescent shape), chili powder, and ground beef or turkey. It is usually topped with “grated” (torn into small pieces) cheddar cheese or “chopped” (cut into small pieces) onions and served with “corn bread” (bread made with “ground-up” (mashed into very small pieces, similar to the size of sand) corn), and it is popular in the southwestern United States. Some versions are spicier than others, and every “chef” (cook) has his or her own “variation” (a particular way of doing something) on the basic “recipe” (instructions on how to cook a dish). In the summer, many “festivals” (community celebrations) and fairs (community gatherings) have “chili cook-offs” where people compete to make the best chili, and sometimes there is a special category for making the spiciest chili.
“Buffalo wings” are another popular spicy food. Buffalo wings are chicken wings that are “not breaded” (not covered in breadcrumbs), but “deep-fried” (cooked in a pot of very hot oil) and then “coated” (covered) with a mixture of vinegar, salt, and cayenne pepper. They are usually bright orange, eaten “with the fingers” (without silverware), and are often served with beer in bars. Most bars offer several different types of buffalo wings ranging from mild to hot to extremely hot, and sometimes there are contests to see who can eat the spiciest buffalo wings, or who can eat the greatest number of buffalo wings in a particular amount of time.
Comprehension Answers
1 - c
2 - c