= 1178
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,178 – Using Profanity.
This is English as a Second Language Podcast episode 1,178. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store while you’re there. We have some additional courses in Business and Daily English I think you might be interested in. You can also like us on Facebook. Go to facebook.com/eslpod. This episode is a dialogue between Cameron and Dorothy about using bad language. Let’s get started.
[start of dialogue]
Cameron: Oh, f***!
Dorothy: Watch your language. I don’t want the kids to hear foul language.
Cameron: Sorry, I stubbed my toe. What’s the big deal? Kids hear all kinds of cursing on TV and in movies.
Dorothy: Not my kids, at least not yet. I don’t want them learning to swear before they learn to walk. I don’t want them to grow up to be rude and offensive people.
Cameron: You can’t protect them from every damn thing people say.
Dorothy: Okay, that’s it. If you’re going to live here, we’ll need a swear jar.
Cameron: A what?!
Dorothy: A swear jar. For every swear word you say, you’ll need to put a dollar into the jar. We’ll save the money for the kids’ education.
Cameron: What the f***?!
Dorothy: Hey, there will be no profanity of any kind in this house. I don’t want you to be a bad influence on my children. Go ahead. Put a dollar into that jar.
Cameron: I’m not putting a dollar into that jar.
Dorothy: My house, my rules.
Cameron: Unbelievable!
[end of dialogue]
Cameron begins by saying, “Oh, f***!” Well, we don’t actually hear the word that Cameron is about to use or was going to use, but it begins with the letter F. And you probably already know, without me having to explain it to you, that a very bad word in English begins with the letter F and ends with the letter K and is four letters long.
Dorothy says to Cameron, “Watch your language.” The expression “to watch your language” means to be careful with your words – in particular, to be careful that you don’t say any bad words, any “profanity” (profanity). “Profanity” would be a very bad word, what we might call “foul language” – words that you do not want your children to hear, words that are considered “vulgar” (vulgar). A vulgar word is a word that is a bad word, that is inappropriate for most situations. Dorothy says, “Watch your language. I don’t want the kids” – the children – “to hear foul language” (once again, “foul language” meaning bad words).
Cameron says, “Sorry, I stubbed my toe.” Your “toe” is on your foot. Your hand has fingers. Your feet have toes. “To stub (stub) your toe” is to hit your toe accidentally against something hard. We have all done this. You’re walking around your house without any shoes on and you accidentally hit your foot against the chair and stub your toe. Your toe hits the chair and it hurts a lot, and sometimes when we get hurt, we like to use foul language to express our pain or to express the emotion we’re going through when we feel that pain. That’s what Cameron did. He stubbed his toe.
Cameron doesn’t understand why Dorothy is upset with him. He says, “What’s the big deal?” A “big deal” is something that is important, something that is very significant. So when he asks, “What’s the big deal,” he’s saying, “Why do you think this is so important?” When someone says, “What’s the big deal?” he’s really saying, “I don’t think this is important. Why do you?” Cameron says, “Kids hear all kinds of cursing on TV and in movies.” “To curse” (curse) means to use bad words, to use foul language.
Dorothy says, “Not my kids, at least not yet.” She means she doesn’t apparently allow her kids to watch TV shows and movies that have cursing in them, that have foul language in them. And that’s very difficult to do nowadays. Even television in the United States has a lot of foul language that you would not want your children to hear. Dorothy continues, “I don’t want them,” meaning her children, “learning to swear before they learn to walk.” “To swear” (swear) means the same as “to curse.” It means to use foul language, to use vulgarities, to use bad words, to use profanity.
I should point out that technically, or at least, one meaning of “to curse” would be to use the name of God or some higher authority when you are swearing – in particular, to perhaps ask God to do something bad to another person or even the situation in which you are in. The word “God” often gets connected with the word “damn” (damn) followed by the word “it” or a person. Someone who is frustrated, for example, might say, “God damn it.” I don’t like the term and I would not suggest you use that term. It is considered foul language in polite conversation.
Dorothy says she doesn’t want her children “to learn to swear before they learn to walk,” meaning her children are probably very young since children learn to walk at a young age. “I don’t want them to grow up to be rude and offensive people.” “Rude” (rude) means not polite. Someone who is rude to you says something bad to you or isn’t very polite to you. “Offensive” (offensive) is when you hurt another person’s feelings or when you insult someone. Cameron says, “You can’t protect them from every damn thing people say.”
Remember, I said the word “damn” is sometimes used with the word “God,” but “damn” itself is also considered a foul word or a swear word. Certainly my mother would never allow me to use that word in our house when I was growing up. It’s used as an adjective when you are frustrated or when you are angry at something. Again, it’s considered rude. It’s considered foul language and not the sort of thing you would use in public, and certainly not the sort of thing you would want to use around children, although I’m sure some parents do when they’re angry.
Dorothy doesn’t like it. She says, “Okay, that’s it. If you’re going to live here, we’ll need a swear jar.” A “swear jar” (jar) is a container that some people use in some families as a way of trying to punish people, children in a family, from using foul language. Every time you use a bad word, you have to put money into the swear jar as a punishment. “Jars” are containers that are usually made out of glass. When you buy certain kinds of food like, I don’t know, jam or pickles or olives, they’re typically are sold in the stores in jars, in glass containers.
Well, Dorothy is going to have Cameron put money into a swear jar every time he uses a bad word. She explains this. She says, “For every swear word you say, you’ll need to put a dollar into the jar. We’ll save the money for the kids’ education.” I’m not exactly sure what the relationship is between Dorothy and Cameron; perhaps Cameron is some sort of relative who is staying with Dorothy, a brother or a cousin perhaps. Dorothy says the money in the swear jar will be used for their children’s education. Cameron is shocked, surprised by this. So he almost swears again. He says, “What the f***?!”
Dorothy says, “Hey, there will be no profanity of any kind in this house. I don’t want you to be a bad influence on my children.” A “bad influence” would be something or someone that causes another person to be worse. Parents often worry about their children’s friends because they don’t want their children to have bad influences in their life – other children who may make their children worse perhaps than they already are. Movies, books, television programs could also be considered bad influences, depending on their contents, of course.
Dorothy says, “Go ahead. Put a dollar into that jar.” Cameron says, “I’m not putting a dollar into that jar.” Dorothy then says something that many parents will say to their teenage children or adult children who are living with them: “My house, my rules,” meaning I own this house, therefore you must follow my rules, my regulations.
Cameron says, “Unbelievable!” The word here, “unbelievable,” is used to express frustration about how surprised you are by something because you think it is so unreasonable, because you think it is wrong. Nevertheless, it is Dorothy’s house, and so Cameron – if he wants to live there, whoever he is – will have to follow her rules.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cameron: Oh, f***!
Dorothy: Watch your language. I don’t want the kids to hear foul language.
Cameron: Sorry, I stubbed my toe. What’s the big deal? Kids hear all kinds of cursing on TV and in movies.
Dorothy: Not my kids, at least not yet. I don’t want them learning to swear before they learn to walk. I don’t want them to grow up to be rude and offensive people.
Cameron: You can’t protect them from every damn thing people say.
Dorothy: Okay, that’s it. If you’re going to live here, we’ll need a swear jar.
Cameron: A what?!
Dorothy: A swear jar. For every swear word you say, you’ll need to put a dollar into the jar. We’ll save the money for the kids’ education.
Cameron: What the f***?!
Dorothy: Hey, there will be no profanity of any kind in this house. I don’t want you to be a bad influence on my children. Go ahead. Put a dollar into that jar.
Cameron: I’m not putting a dollar into that jar.
Dorothy: My house, my rules.
Cameron: Unbelievable!
[end of dialogue]
You won’t hear any foul language coming from our scriptwriter, Dr. Lucy Tse – in her own life or in her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to watch (one’s) language – to be careful with one’s words; to avoid saying vulgarities (bad words that are inappropriate in many social circumstances)
* We’re in church! Watch your language.
foul language – bad words; vulgarities; words that are inappropriate in many social circumstances
* Grandma used to wash her children’s mouths out with soap when she heard them use foul language.
to stub (one’s) toe – to accidentally hit one’s toe against a hard surface, typically a wall or door, while moving forward, causing a lot of pain
* Josephina stubbed her toe while trying to walk to the bathroom in the dark in the middle of the night.
big deal – something that is important or significant; not a minor thing
* Getting the highest possible score on the hardest exam of the year is a big deal. Congratulations!
cursing – the use of swear words; the use of foul language
* Why does this novel contain so much cursing? I don’t think I want my 10-year-old son to read it.
to swear – to use foul language; to use bad words
* Many people swear more than usual when they are under the influence of alcohol.
rude – not polite; insulting and offensive
* It’s very rude to not say “thank you” when someone gives you a gift, even if the giver is a member of your family.
offensive – hurting another person’s feelings; insulting
* Those jokes you told about fat people are offensive. Please don’t tell anymore of them at work.
damn – a word used to express frustration, anger, or unpleasant surprise
* Damn, I thought we were going to finish that proposal on time, but I missed the deadline by two hours.
swear jar – a jar that people must put money into every time they say a bad word, used to help people change their behavior and stop using foul language
* Conner is still swearing, but less than he used to, and now we have enough money in the swear jar for a family trip to Disneyland!
profanity – a formal term for foul language or bad words; words that are inappropriate in many social circumstances
* Television news programs have to block profanity in interviews.
bad influence – something or someone that causes another person or thing to become worse or less admirable
* Balah fears that his daughter’s boyfriend is a bad influence on her, and wants her to stop seeing him.
rules – regulations; statements about what should be done, including when and how
* The corporation has several rules related to employees’ dress, such as rules that they have to wear pants and closed-toe shoes.
unbelievable – a word used out of frustration or exasperation to show that one is surprised and irritated by something, and does not think it is reasonable
* Hannah’s boyfriend cheated on her, and now he thinks that sending some roses will make everything okay? Unbelievable!
Comprehension Questions
1. Why did Cameron use foul language?
a) Because he wanted to make Dorothy mad.
b) Because he was very angry.
c) Because he was in pain.
2. What happened to Cameron?
a) He dropped something on his foot.
b) He accidentally hit his foot against something.
c) He wore shoes that were too small.
Answers at bottom.
What Else Does It Mean?
to swear
The verb “to swear,” in this podcast, means to use foul language or to use bad words: “The soldiers in this army swear a lot while under pressure.” The verb “to swear” can also mean to take an oath or to make a promise: “I swear I would never do anything to hurt you.” Or, “Do you swear to tell me the truth?” The phrase “to swear (someone) to secrecy” means to make another person promise not to share a secret with others: “She wore us to secrecy before telling us that she was pregnant.” Finally, the phrase “to swear (someone) in” means to administer an oath, or to have someone make an official promise, before accepting an important job or position: “Who swears in the President of the United States?”
rules
In this podcast, the word “rules” means regulations, or statements about what should be done, including when and how: “Their parents have a lot of rules about what is appropriate at the dinner table, such as always saying ‘please’ and not chewing with your mouth open.” The phrase “to stretch/bend the rules” means to make an exception to the rules, or do something that is not normally allowed: “Normally, we have to show two pieces of photo ID, but the clerk agreed to bend the rules for us this time.” A “rule of thumb” is something that is normally true, based on one’s experience: “As a rule of thumb, try to keep your housing costs at less than 30% of your income.” Finally, the phrase “to make it a rule” means to try to always do something: “He makes it a rule never to date his co-workers.”
Culture Note
Regulation of Obscenity, Decency, and Profanity
The Federal Communications Commission (FCC, an agency or department of the federal (national) government) regulates “obscenity, decency, and profanity” in “programming” (things that are shown on TV or heard over the radio). “Obscene” material is sexual, without artistic value. “Indecent” material is sexual or “excretory” (related to feces or poop; humans’ solid waste). And “profane” materials uses very bad words that are not acceptable in most social situations.
Federal law “prohibits” (does not allow) obscene programming at any time, and it limits indecent or profane programming to certain times of day, “presumably” (one assumes) when children are not watching, specifically between 10:00 p.m. and 6:00 a.m.
If the FCC determines that these laws have been “violated” (broken; not followed), it can issue a “fine” (money that must be paid as punishment) or “revoke” (take back) a “license” (official permission to do something, in this case, for a station to broadcast programs). In some cases, people can even be sent to jail for up to two years.
However, the FCC must carefully balance these restrictions with “freedom of speech” (the right of people to state their beliefs without interference from the government). The freedom of speech is a “fundamental” (basic and important) U.S. “right” (what all citizens in a country are allowed or should expect).
People who believe that a station has broadcasted obscene, indecent, or profane materials can file a complaint in writing in the form of a letter, fax, or email, or by phone. They should identify the “offending” (causing the problem) station and the time when the “objectionable” (something that one does not like) material was “aired” (seen on TV or heard on the radio). The FCC then “investigates” (researches) the “incident” (something bad that has happened) and determines whether the laws have been broken.
Comprehension Answers
1 - c
2 - b