= 1181
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,181 – Making a Comeback.
This is English as a Second Language Podcast episode 1,181. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store with additional courses in Business and Daily English. You can also like us on Facebook. Go to facebook.com/eslpod. And why not follow us on Twitter at @eslpod.
This episode is a dialogue between Eileen and Dex about someone who was popular a long time ago who wants to be popular again. Let’s get started.
[start of dialogue]
Eileen: What are you doing with all that band equipment?
Dex: The guys in the band are planning a reunion. It’s time for our comeback. It will be the stuff of legends!
Eileen: Aren’t you afraid of being called has-beens after all these years?
Dex: Bite your tongue. There is a groundswell of support for this reunion and we’re not going to disappoint the fans.
Eileen: Groundswell? Are you referring to that local news article about one-hit wonders asking, “Where are they now?”
Dex: There was a lot of good response to my quote about our possible reunion. After a 20-year hiatus, I think fans are ready for more music from us. It should lead to a tour.
Eileen: Resurrecting your music career might be harder than you guys think.
Dex: Stop being such a killjoy. This reunion could lead to an entire new generation of fans.
Eileen: Or you could become the laughingstock of the music world.
Dex: Okay, that’s enough. You’re officially out of the band.
Eileen: I didn’t know I was in the band.
Dex: I had considered making you a backup singer, but I can’t deal with your negativity.
Eileen: Oh, poor me. I’ll never find stardom.
Dex: You’ve had your chance!
[end of dialogue]
The title of this episode is “Making a Comeback” (comeback). A “comeback” is usually when a famous person, someone in sports or entertainment, becomes popular after many years of no longer being popular. So, they’re popular, and then they’re not popular, and then they become popular again. Some old actors and singers try to make a comeback. They try to become popular again after 10, 15, or 20 years of not being popular. You see this a lot in music, and that’s the topic of today’s dialogue.
Eileen says to Dex, “What are you doing with all that band equipment?” “Band” (band) is a group of musicians who perform together. Guitars, drums, speakers – those are things that might be part of the “band equipment” that Eileen is talking about. Dex says, “The guys,” meaning probably the men in the band, “are planning a reunion.” A “reunion” (reunion) is an event that is for people who used to be related in some way to get back together again and have a party or have some sort of celebration.
The members of Dex’s band are planning a reunion. He says, “It’s time for our comeback. It will be the stuff of legends!” The expressions “stuff (stuff) of legends (legends)” means that it is going to be very famous, something that is well known, something that will be popular, that many people will be talking about. Eileen says, “Aren’t you afraid of being called has-beens after all these years?”
The term “has (has) – been (been)” refers to someone who used to be popular and successful but is no longer popular, but this person continues to talk about it. You can find lots of has-been actors here in Los Angeles. The term “has-been” is definitely an insulting one. It is used to refer to someone who isn’t famous anymore but was once famous. It could also refer to someone who was once good at something but is no longer good at that thing.
Dex responds to Eileen, “Bite your tongue.” This expression “to bite (bite) your tongue (tongue)” means be silent, be quiet, don’t say what you want to say right now. “There is a groundswell of support for this reunion,” Dex says, “and we’re not going to disappoint the fans.” A “groundswell” (groundswell) is an increase in something, especially in public opinion – when people start liking something. Usually this happens very quickly.
A “fan” (fan) is someone who likes a particular person or thing. It could be a celebrity. It could be a movie. It could be a sports team. It could be even a particular kind of food. “I’m a fan of shrimp.” That means I really like shrimp. Or “I’m a fan of the Los Angeles Dodgers.” I really like that baseball team. Eileen, however, doubts that Dex is correct about this groundswell. She says, “Groundswell? Are you referring to that local news article about one-hit wonders asking, ‘Where Are They Now?’”
A “one-hit wonder” (wonder) is a person or a group that had one popular song and then nothing else. The person or group only had one popular song that everybody knows and everybody can sing, but that was it. That was the only hit, the only success they had. That’s a “one-hit wonder.” Eileen says there was an article in the newspaper – or perhaps the Internet website – about one-hit wonders, asking what these people or what these groups are doing now. Dex says, “There was a lot of good response to my quote about our possible reunion.”
So apparently Dex was interviewed for this article, and there is something that he said in the article. That’s what he means by “my quote” (quote). “After a 20-year hiatus, I think fans are ready for more music from us.” A “hiatus” (hiatus) is a break, a pause, often a very long pause, in some activity – in this case, a 20-year break. “It should lead to a tour,” Dex says. He’s referring to this reunion concert that they are planning on giving. A “tour” (tour) is when a musician or a band travels from city to city giving performances.
Eileen says, “Resurrecting your music career might be harder than you guys think.” “To resurrect” (resurrect) refers to bringing something or someone back to life. More generally, it means to try to make something popular that was once popular in the past but is no longer so. Dex says, “Stop being such a killjoy.” A “killjoy” (killjoy) is a person who makes it difficult for other people to enjoy something, who makes it difficult for other people to have fun, perhaps by making negative comments.
Eileen doubts that Dex and his band will be able to make a comeback, but Dex says, “Stop being such a killjoy. This reunion could lead to an entire new generation of fans,” meaning a whole new group of younger people who will like their music. Eileen says, “Or you could become the laughingstock of the music world.” A “laughingstock” (laughingstock) – one word – is a person that other people make fun of, that other people laugh at, usually because that person is doing something embarrassing or stupid that other people laugh at.
Eileen thinks that Dex and his band will be “the laughingstock of the music world,” meaning everyone else who is involved in making and selling music. Dex says, “Okay, that’s enough. You’re officially out of the band,” meaning you will not be a member of the band. Eileen says, “I didn’t know I was in the band.” Dex responds, “I had considered making you a backup singer, but I can’t deal with your negativity.”
A “backup singer” is someone who provides help for the lead or main singer in a band. You still see this in some musical groups. There will usually be two people, maybe more, who are standing in the back who are also singing the song, helping the main singer of the song – the person we would call the “lead (lead) singer” of the band.
Dex says he had considered making Eileen a backup singer, but he can’t deal with her “negativity” (negativity). “Negativity” is the same as being pessimistic – having negative thoughts and feelings about something or talking in a negative way: always criticizing, always complaining, or always seeing the bad side of things. Eileen somewhat jokingly says, “Oh, poor me. I’ll never find stardom.” “Stardom” (stardom) refers to having your name and your work known by lots of different people – being a star, being famous.
Dex, however, says to her, “You’ve had your chance.” “You’ve had your chance” is a phrase we use to tell someone that he or she has lost a good opportunity by not taking advantage of it during a certain period of time. Eileen doesn’t really feel sorry. She doesn’t really think she was going to be a star. But Dex is mad at her and says, “Well you’ve had your chance,” meaning you could have been famous, but because of your negativity, you won’t.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Eileen: What are you doing with all that band equipment?
Dex: The guys in the band are planning a reunion. It’s time for our comeback. It will be the stuff of legends!
Eileen: Aren’t you afraid of being called has-beens after all these years?
Dex: Bite your tongue. There is a groundswell of support for this reunion and we’re not going to disappoint the fans.
Eileen: Groundswell? Are you referring to that local news article about one-hit wonders asking, “Where are they now?”
Dex: There was a lot of good response to my quote about our possible reunion. After a 20-year hiatus, I think fans are ready for more music from us. It should lead to a tour.
Eileen: Resurrecting your music career might be harder than you guys think.
Dex: Stop being such a killjoy. This reunion could lead to an entire new generation of fans.
Eileen: Or you could become the laughingstock of the music world.
Dex: Okay, that’s enough. You’re officially out of the band.
Eileen: I didn’t know I was in the band.
Dex: I had considered making you a backup singer, but I can’t deal with your negativity.
Eileen: Oh, poor me. I’ll never find stardom.
Dex: You’ve had your chance!
[end of dialogue]
The scripts by our wonderful scriptwriter, Dr. Lucy Tse, are definitely the stuff of legends.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
band – a group of musicians who perform together
* Their band includes two singers, a guitarist, a bass player, and a drummer.
reunion – an event where many people meet because they have some affiliation or relationship and have not seen each other in a long time, especially referring to members of an extended family
* Every five years, they go to Colorado for a family reunion with all their aunts, uncles, cousins, and other relatives.
comeback – a return by famous people, such as entertainers or sports players, to the activity for which they are known; a return to popularity
* Several singers from the 1970s are making comeback by partnering with current recording artists.
stuff of legends – something that is very famous, well known, and popular, that many people talk about and remember fondly
* Giorgio’s homemade lasagna is the best I’ve tasted. It’s the stuff of legends!
has-been – a person who used to be popular or successful, and continues to talk and dream about it, but is not longer admired by others
* Alan thinks he’s a fantastic computer programmer, but really he’s just a has-been who hasn’t kept up with advances in information technology.
to bite (one’s) tongue – to not say what one wants to say; to avoid saying the first thing that one thinks of; to edit one’s words before speaking
* Bite your tongue! You shouldn’t criticize the proposal before you’ve even heard everything she has to say.
groundswell – an increase in something, especially when referring to public opinion
* How can politicians take advantage of the groundswell of interest in gun control?
fan – fanatic; a person who has a strong interest and passion in someone or something, especially a celebrity, sports team, or performer
* We’re big fans of 1980s new wave music.
one-hit wonder – a performer who is well known for one song that became extremely successful, but whose other work has not been nearly as popular
* It’s great that our song is a huge success, but what can we do on our next album to make sure we don’t become a one-hit wonder?
hiatus – a break; a pause in one’s work or activities
* We all took a hiatus from product development over the holidays.
tour – a period when a musician or band travels to many different places to perform in front of large audiences
* The new Madonna tour through Asia will begin in June.
to resurrect – to bring something or someone back to life; to make something popular, useful, or commonplace again
* After that scandal, is it even possible to resurrect her career?
killjoy – a person who spoils the fun, making it difficult or impossible for other people to enjoy something
* Why would you want to invite Cecilia to your party? She’s a killjoy who makes everyone else miserable.
laughingstock – a person who is made fun of or laughed at by many other people
* Heather said that if her mother made her wear that outfit to school, she would be the laughingstock of the whole town.
backup singer – a person who provides singing support for the leader singer in a band or on a particular song
* Backup singers of the 1950s often sang made-up words like “doo wop” and “bee bop.”
negativity – pessimism; negative thoughts and feelings; a negative outlook in which one expects the worst to happen
* Being around Craig and all of his negative is very depressing.
stardom – fame; having one’s name and work known by many people
* Achieving stardom is easier than ever, now that anyone can put a video on the Internet and have it seen by people all over the world.
you’ve had your chance – a phrase used to tell someone that he or she has lost a good opportunity by failing to take advantage of it within a certain period of time
* You’ve had your chance to fix the production problems, but it didn’t work, so now we’re bringing in some consultants to find a solution.
Comprehension Questions
1. Who would be excited about the band’s comeback?
a) The has-beens
b) The fans
c) The one-hit wonders
2. What were Dex and his band mates doing during their 20-year hiatus?
a) They were writing new songs and practicing.
b) They were taking a break from music.
c) They were studying other musicians’ work.
Answers at bottom.
What Else Does It Mean?
band
The word “band,” in this podcast, means a group of musicians who perform together: “The jazz band is looking for a new saxophonist.” A “band” can also be a group of people who share an interest or activity: “We spend our Saturday mornings with a band of volunteers at the local food bank.” A “band” can also be a strap, or a flat, narrow piece that wraps around something to form a circle: “What’s wrong with your watch? Is the band broken, or do you just need a new battery?” Finally, a “rubber band” is a stretchy, thin piece of rubber that is used to hold things together: “Please put a rubber band around those receipts before you put them in the filing cabinet.”
backup
In this podcast, the phrase “backup singer” means a person who provides vocal (singing) support for the leader singer in a band or on a particular song: “Mariah works as a backup singer, but she dreams of performing as a soloist.” The word “backup” can also refer to an athlete who will play in a particular position if another team member is unable to play: “When Kian broke his knee, Ezekiel was the backup goalie.” When talking about computers, a “backup” is the process or duplicating all the data on a computer, or the file that results from performing a backup: “It’s important to do a backup of all your files at least once a month, so that you won’t lose everything if your computer stops working.” Or, “When my laptop was stolen, I was able to find the contract I had been working on in the backup.”
Culture Note
The “Miracle on Ice”
The “Miracle on Ice” refers to an “ice hockey” (a game played by people on ice skates with long sticks who are trying to get a “puck” (small, black, round piece of hard rubber) into the goal at either end of the ice rink) game that was played during the Winter Olympics in New York in 1980. The U.S. men’s hockey team “defeated” (beat; won over) the Soviet Union’s men’s hockey team, which had won six of the previous seven Olympic games.
The Soviet Union team was “heavily favored to win” (everyone expected that team to win), given its “winning streak” (a large number of wins in a row). Due to the “Cold War” (the period of tension and hostility between the United States and the Soviet Union, among other countries, between approximately 1947 and 1991), there was a lot of public interest in the game and it was viewed as more than just a “sports match” (competition between two teams). Almost 9,000 people attended the game, “waving” (moving in the air for others to see) flags and signing “patriotic” (related to love for one’s country) songs.
When the United States won 4-3, many people thought it was a “miracle” (something that cannot be explained by the laws of science, typically something produced by God). After that game, the United States went on to win its last “match” (game) against Finland, and in doing so, won the “gold medal” (first-place prize). The team was named “Sportsmen of the Year” by Sports Illustrated magazine, and “Athlete of the Year” by the Associated Press.
Comprehension Answers
1 -b
2 - b