= 1193
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,193 – Reducing Food Waste.
This is English as a Second Language Podcast episode 1,193. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Yeah.
Visit our website at ESLPod.com. Take a look at our other ESL courses in Business and Daily English. We have lots on our website for you to choose from. Take a look at our Facebook page at facebook.com/eslpod. All the cool kids are doing it.
This episode is a dialogue between Jon and Marta about not wasting your food. Let’s get started.
[start of dialogue]
Jon: Wait! What are doing with that squishy tomato?
Marta: I’m tossing it. It’s no good anymore.
Jon: I’ll take it, and I’ll take that stale bread, too.
Marta: Stop! You can’t fish that out of the trash.
Jon: I’m trying to do my part to reduce food waste. Tired vegetables are still okay to eat, as are bruised fruit.
Marta: Fine, but not once they’ve been discarded. Stay out of my trash.
Jon: What you are going to do with this graying meat?
Marta: I was going to throw that out, too.
Jon: I’ll take it. I’m sure I can make something edible with it.
Marta: You can’t be serious. I’m all for doing my part, but I draw the line at eating spoiled meat.
Jon: It’s not spoiled. It’s just beyond the peak of freshness.
Marta: Well, be my guest. You can have all of this food.
Jon: And to show my thanks, I’ll invite you over to lunch tomorrow.
Marta: Thanks, but no thanks.
[end of dialogue]
Jon says to Marta, “Wait! What are you doing with that squishy tomato?” “Squishy” (squishy) is something that is soft, usually something that you can change the shape of easily by squeezing it or putting your hands around it. A “squishy tomato” would be a tomato that is no longer hard or “firm” (firm), meaning when you pick it up, it would fall apart. Basically, Jon is asking Marta what she is doing with a tomato that seems to be squishy.
Marta says, “I’m tossing it. It’s no good anymore.” “To toss” (toss) here means to throw away, to get rid of. Jon says, “I’ll take it, and I’ll take that stale bread, too.” Jon wants Marta to give him this squishy tomato as well as some “stale (stale) bread.” Bread that is “stale” is no longer fresh. It’s old and dried out. Often, it’s hard. Marta says, “Stop! You can’t fish that out of the trash.” “To fish” (fish) something out of something else means to take something out of a container where it is surrounded by other things.
So for example, if you open up a drawer that has lots of different things in it, you may “fish out” something. You may take something out that is mixed up with or in a pile of other things. In this case, Jon is trying to fish something “out of the trash” (trash). “Trash” here refers to garbage or things that are being thrown away. Most people in their houses have a container, an object that they use to put trash into or to put garbage into – things that they are throwing away, things that they are getting rid of.
Well, Jon is apparently trying to take some food out of a trash container, which sounds pretty awful, pretty disgusting. Jon says, however, that he’s trying to do his part to “reduce food waste.” “Food waste” (waste) is food that is not eaten but instead thrown away when in fact it could still be used. Jon says that he’s trying “to reduce food waste.” He’s trying to make sure that we don’t waste too much food. He says, “Tired vegetables are still okay to eat, as are bruised fruit.”
“Tired” (tired) usually means the same as sleepy – of not having a lot of energy. But “tired vegetables” would refer to older vegetables that start to look like they aren’t very fresh, that you may not want to eat them. But Jon says it’s okay to eat tired vegetables – vegetables that are older. He also says it’s okay to eat “bruised (bruised) fruit.” If fruit is “bruised,” it has small dark spots on the skin and is usually soft in those particular spots, those areas. If you have a banana that’s bruised, it will often be black because of the bruise, and it will be soft when you touch it.
Jon says it’s okay to eat bruised fruit. Marta says, “Fine, but not once they’ve been discarded.” She’s saying maybe it’s okay to eat tired vegetables and bruised fruit, but not once they have been “discarded” (discarded). “To discard” means to throw something away – to put something, in this case, in the garbage container. She then tells Jon, “Stay out of my trash,” meaning don’t go looking in my trash container and taking things out of it. “To stay out of” someplace means not to go there or not to go in there.
Jon then asks her, “What are you going to do with this graying meat?” “Graying” (graying) comes from the color “gray” (gray). Meat can turn gray when it gets old, and it’s usually a sign you don’t want to eat it. That’s why Marta says, “I was going to throw that out, too.” She was going to get rid of the graying meat. But Jon says, “I’ll take it. I’m sure I can make something edible with it.” “Edible” (edible) means able to be eaten, something you can eat without getting sick.
Jon thinks he can take this graying meat, this old meat, and make something out of it, cook something that would allow him to eat it. I’m not so sure. Neither is Marta. She says, “You can’t be serious,” meaning you must be joking. “I’m all for,” meaning I’m in favor of, “doing my part.” “To do your part” means to help in a group effort or to do your fair share of the work.
If someone says, “I want to do my part,” that person wants to help the group do something. Not everything, but what that person thinks would be his responsibility or his part of the work that needs to be done. Marta wants to do her part to stop wasting food. But she says, “I draw the line at eating spoiled meat.” The expression “to draw (draw) the line” means to indicate that you will not do anything beyond a certain point. You are indicating the limits of something. You are saying how much you will accept and what you won’t accept.
Notice she says, “I will draw the line at,” and then she says, “eating spoiled meat.” What she’s saying here is that she’s not going to eat spoil meat. That’s the limit to what she will do in terms of stopping food waste. She won’t do that. She’s drawing the line at this particular action – eating “spoiled” (spoiled) meat. “Spoiled food” is food that you can no longer eat, usually because it is too old and has become what we would describe as “rotten” (rotten). If food is “rotten,” it will make you sick if you eat it.
Sometimes we use that adjective “rotten” when we’re talking about a person who misbehaves, or who does things wrong or acts badly. You may talk about a “rotten child” – a child who is always screaming and causing problems and not being very nice. There was a famous punk rock star of the 1970s called Johnny Rotten. Well, here we’re not talking about rock stars. We’re talking about food that you should not eat, and Marta doesn’t want to eat food that is spoiled or rotten.
Jon (no relation, I think, to Johnny Rotten – meaning I don’t think the two are brothers or anything) says, “It’s not spoiled. It’s just beyond the peak of freshness.” “To be beyond (beyond)” means to be past something. The “peak” (peak) of something is the highest point. You can think of a mountain having a “peak.” It’s the highest point, the highest place on a mountain. “Freshness” (freshness) is when food is at its best, when it is best to eat. If something is “beyond the peak of freshness,” then, it is no longer the best time to eat it, but it’s still okay to eat it. That’s what Jon is saying.
Marta says, “Well, be my guest.” This is a very common expression in conversational English. “Be my guest” means go ahead and do it. You are telling someone it’s okay for him to do something. Sometimes, however – often, in fact – we use it somewhat as a joke or use it “sarcastically,” meaning we don’t really mean it or we are saying that we don’t want to do something, but if you want to, then you can do it.
For example, let’s say your neighbor’s dog is barking. And you start yelling at the dog, and the dog, of course, being stupid as dogs are, doesn’t do anything. And your wife says to you, “Why don’t you tell that dog to be quiet?” And you say, “I’ve already tried.” She says, “Well, I’m going to try.” And you say, “Okay, be my guest.” You’re telling her to go and try to get the dog to be quiet, but you’re probably saying it in such a way as to indicate that you don’t think she will be very successful.
One thing you might try to do is to give the dog some spoiled meat. That might eventually cause the dog to no longer bark. Just kidding, of course. You shouldn’t do that. I am not recommending that to anyone. Please don’t email and tell me that I’m a rotten person. Anyway, Marta says, “Well, be my guest.” “You can have all of this food,” she says. Jon says, “And to show my thanks” – to thank you – “I’ll invite you over to lunch tomorrow.” Jon is inviting Marta to come over to his house and have lunch. Marta says, “Thanks, but no thanks.”
If someone asks you to do something that you think is dangerous or perhaps is going to be unpleasant, and you want to indicate that the person probably shouldn’t have even asked you to do this, you might use this expression, “Thanks, but no thanks.” It means no, I really don’t want to do that. You’re thanking the person, but you’re saying “no thanks,” meaning no, I don’t want to.
Of course, Marta doesn’t want to go over to Jon’s house and eat all of the food that Jon has taken from her.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jon: Wait! What are doing with that squishy tomato?
Marta: I’m tossing it. It’s no good anymore.
Jon: I’ll take it, and I’ll take that stale bread, too.
Marta: Stop! You can’t fish that out of the trash.
Jon: I’m trying to do my part to reduce food waste. Tired vegetables are still okay to eat, as are bruised fruit.
Marta: Fine, but not once they’ve been discarded. Stay out of my trash.
Jon: What you are going to do with this graying meat?
Marta: I was going to throw that out, too.
Jon: I’ll take it. I’m sure I can make something edible with it.
Marta: You can’t be serious. I’m all for doing my part, but I draw the line at eating spoiled meat.
Jon: It’s not spoiled. It’s just beyond the peak of freshness.
Marta: Well, be my guest. You can have all of this food.
Jon: And to show my thanks, I’ll invite you over to lunch tomorrow.
Marta: Thanks, but no thanks.
[end of dialogue]
There’s nothing stale, bruised, or graying about our dialogues. They’re all at the peak of freshness thanks to our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
squishy – soft and losing one’s shape; with a soft, flexible skin that one can push into gently
* Are the dinner rolls supposed to be squishy, or crunchy?
to toss – to throw something away; to discard
* Why did you toss those shirts? You could have donated them to a charity.
stale – not fresh or pleasant; old and dried out, used when referring to bread or crackers
* These crackers are too stale to eat by themselves, but we can crush them into small pieces and add them to the casserole.
to fish (something) out – to take something out of a container where it is surrounded by other things
* It’s hard to fish coins out of my pocket because I also keep my cell phone and keys in it.
trash – garbage; refuse; things that are being thrown away
* I need to remember to take out the trash tonight, because the garbage truck will come early tomorrow morning.
food waste – food that is not eaten, but instead thrown away in wasteful, careless way
* Managers of the university’s cafeteria realized they had a big problem with food waste, and found a way to donate uneaten food to a nearby homeless shelter.
tired – worn out; old; no longer fresh
* These tired carrots don’t look very good, but they’ll be tasty in a soup.
bruised – with small, dark spots on the skin where something or someone has been hit
* The peaches are bruised, because we accidentally dropped the bucket while we were picking them.
to discard – to throw something away; to put something in the garbage
* Please discard these cardboard boxes. We don’t need them anymore.
graying – becoming older and/or more gray in color
* Economists are worried about the cost of providing healthcare to a rapidly graying population.
edible – able to be eaten; consumable; something that one can eat without getting sick
* Some of these cake decorations look like metal or plastic, but they are all edible.
to do (one’s) part – to contribute; to do one’s fair share of the work; to help in a group effort
* I don’t have time to lead a committee, but I’ll volunteer a few hours to do my part.
to draw the line – to indicate the limits of something; to state how much of something one will tolerate, or the point at which one will not continue to have, do, or accept something
* Every marriage faces challenges, but I draw the line at drug use and adultery.
spoiled – rotten; no longer good or safe to eat; with toxins, especially from being left out at a warm temperature for too long
* We forgot to put the fish in the refrigerator and accidentally left it out overnight, so now it’s spoiled.
beyond – past; further than a certain point
* Beyond these basic qualifications, what are you looking for in a job candidate?
peak of freshness – the period of time when a food is extremely fresh, ripe, and ready to eat; when a food tastes best
* We ate these cherries at the peak of freshness and they were very juicy and sweet.
to be (one’s) guest – a phrase used to invite someone to have or do something, sometimes used sarcastically
* If you really want to pay for dinner tonight, be my guest!
Comprehension Questions
1. What is wrong with the meat?
a) It is burnt.
b) It is infected.
c) It is too old.
2. What does Marta mean when she says, “I draw the line at eating spoiled meat”?
a) She draws pictures of spoiled meat.
b) She believes spoiled meat is healthy to eat.
c) She refuses to eat spoiled meat.
Answers at bottom.
What Else Does It Mean?
to fish out
The phrase “to fish out,” in this podcast, means to take something out of a container where it is surrounded by other things: “You have small fingers. Could you please try to my ring out of the drain? It fell down the sink.” The phrase “to fish around for (something)” means to look for something in a bag or container: “Esther has a huge purse and had to fish around in it for a few minutes to find her car keys.” Finally, the phrase “to fish for compliments” means to try to get other people to say nice things about oneself, often by criticizing oneself: “She always talks about needing to go on a diet, but she’s just fishing for compliments, hoping that other people will tell her she’s thin and doesn’t need to lose weight.”
beyond
In this podcast, the word “beyond” means past something, or further than a certain point: “Once we climb to the top of that hill, we should be able to see beyond the city limits.” Or, “Is understanding the meaning of life beyond human ability?” The phrase “beyond repair” means completely damaged or destroyed so that something can no longer be fixed: “The mechanic looked at the engine, but said our car is beyond repair and that we should buy a new one.” Finally, the phrase “to be beyond (someone)” means that something is too complex, difficult, or confusing for someone to understand: “Those physics equations are beyond me.” Or, “The reasons for her unusual behavior are beyond me.”
Culture Note
Food Businesses’ Efforts to Reduce Waste
The food industry, which includes restaurants, grocery stores, and “produce” (fruit and vegetable) markets, are “increasingly” (more and more) aware of food waste and feel the need to “do something about it” (address a problem in some way). Especially when many people are “going hungry” (do not have enough food to eat), wasting food seems “irresponsible” (not meeting one’s obligations) and “immoral” (wrong).
In 2011, the Grocery Manufacturers Association created the Food Waste Reduction Alliance to try to reduce food waste in grocery stores and restaurants. They “take a three-pronged approach” (focus on three areas): reducing the amount of food waste that is “generated” (produced), increasing the amount of food that is donated to needy people and organizations, and recycling or “composting” (turning into soil) wasted food rather than putting it into “landfills “(large areas where garbage is dumped).
Many universities and similar institutions that have large cafeterias are “partnering” (working closely) with local organization that feed the homeless. They find safe ways for their uneaten food to be shared with people who would “not otherwise” (without it) be able to eat.
Other people and organizations focus on “consumer education” (teaching people in ways that affect their buying decisions). Americans have become “accustomed to” (used to) seeing “uniform” (all the same) sizes and shapes in the “produce section” (the part of the store where fruits and vegetables are sold), and expect “blemish-free” (without any marks or bruises) skin on fruits and vegetables. So these organizations are trying to convince American to buy and eat odd-shaped fruits and vegetables that are “nutritious” (beneficial for the body) and delicious, so that these “outcasts” (things that are not chosen) do not have to be thrown away.
Comprehension Answers
1 - c
2 - c