
= 2-06. 国际秩序 (当代)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


==  欧洲的区域经济合作组织

As a result, not only was it able to provide funds to war-torn nations to rebuild their economies and their infrastructure as part of the Marshall Plan, but U.S.-manufactured goods also flooded into markets around the world.

作为"马歇尔计划"的一部分，美国不仅能为饱受战争蹂躏的国家提供资金, 来重建其经济和基础设施，而且美国制造的商品, 也能涌入世界各地的市场。

Among the forces driving European economic integration was a desire for Europe to be more independent of the United States.

推动欧洲经济一体化的力量之一, 是希望欧洲更加独立于美国.

'''

===   英国加入”欧洲经济共同体” (1973)

Although Britain supported the EEC’s economic goals, it was initially not interested in the political cooperation the group represented.

When it did signal its desire to join, Britain wanted special protections for its agriculture and other exceptions for its Commonwealth connections, such as Canada. This meant negotiating with France, then the EEC’s most powerful member. Since decisions at that time were made unanimously and member countries had the power to unilaterally veto, France’s approval was crucial. President Charles de Gaulle of France did not approve, however.

Over the next several years, Britain officially applied for EEC membership twice. Both times de Gaulle worried that admitting Britain, with its strong ties to the United States, would transform the organization into an Atlantic community controlled by Washington. Britain was admitted in 1973 (along with Denmark and Ireland), when de Gaulle was no longer president of France. It took a UK referendum in 1975 to confirm the country’s EEC membership.

尽管英国支持"欧洲经济共同体"的经济目标，但最初它对该组织所代表的政治合作, 并不感兴趣。

当英国确实表示愿意加入时，它希望对其农业, 和其他与英联邦有联系的国家（如加拿大）, 提供特殊保护。这意味着要与当时"欧洲经济共同体"最强大的成员--法国,进行谈判。由于当时的决定是一致做出的， 成员国拥有"单方面否决权"，因此法国的批准至关重要。 然而，法国总统戴高乐并没有批准.

在接下来的几年里，英国两次正式申请加入"欧洲经济共同体." 两次戴高乐都担心, 接纳与美国关系密切的英国，将把该组织转变为由华盛顿控制的"大西洋共同体"。

英国（以及丹麦和爱尔兰）最终于 1973 年加入，因为当时戴高乐已不再担任法国总统了。1975年，英国举行全民公投，确认该国加入"欧洲经济共同体"。

'''

=== 欧盟建立 (1993)

By 1993, the EEC had been integrated into the newly created European Union (EU). The EU was conceived as a single market for the free movement of goods, services, money, and people. Citizens of member countries can freely move to other EU countries and legally work there, just as they can in their own country.

In 1999, the EU introduced its own currency, the euro. The euro was not universally adopted by member states, though. The United Kingdom, Denmark, Sweden, and a few others kept their own currencies.

到 1993 年，欧洲经济共同体, 已并入新成立的"欧盟"（EU）. 欧盟被视为商品、服务、资金和人员自由流动的单一市场。成员国公民可以自由移居到其他欧盟国家, 并在那里合法工作，就像在自己的国家一样。

1999年，欧盟推出了自己的货币欧元。不过，欧元并未被成员国普遍采用。英国、丹麦、瑞典和其他一些国家保留了自己的货币。

'''

=== 英国脱离欧盟 (2016)

In 2016, however, 52 percent of the citizens of the United Kingdom voted to leave the EU.

Many also disliked the fact that its membership in the EU made it easier for people from elsewhere in Europe, including recent immigrants from the Middle East and Africa, to enter Britain.

Some also argued that losing the trade advantages that came with belonging to the EU could result in shortages in stores and more expensive products.

然而，2016年，52%的英国公民, 投票决定脱离欧盟.

(赞成脱离欧盟者的观点:) 许多人还不喜欢这样一个事实：英国加入欧盟, 使得欧洲其他地方的人（包括来自中东和非洲的新移民）更容易进入英国。

(反对脱离欧盟者的观点:) 一些人还认为，失去欧盟带来的贸易优势, 可能会导致商店短缺, 和更昂贵的产品。

In Europe, the European Parliament, the EU’s legislative body, was angry that Brexit might threaten the entire EU project. To show its displeasure and possibly to deter any other member states from leaving, the European Parliament wanted the separation to be as painful for the United Kingdom as possible, and many member countries supported this hardline stance.

In today’s post-Brexit world, there are new regulations on British goods entering the EU and no automatic recognition of British professional licenses in the EU. Britons seeking to make long-term stays in EU countries now must apply for visas.

在欧洲，欧盟立法机构"欧洲议会", 对英国脱欧可能威胁到整个欧盟项目, 感到愤怒。为了表达不满, 并可能阻止任何其他成员国脱欧，欧洲议会希望脱欧对英国造成尽可能的痛苦，许多成员国支持这一强硬立场。

在当今"脱欧"后的世界中，英国商品进入欧盟有新的规定，并且欧盟不会自动承认英国的专业许可证。寻求在欧盟国家长期居留的英国人, 现在必须申请签证。

'''

== 北美的区域经济合作组织

It also encouraged some national leaders to seek regional international economic integration along lines similar to Western Europe’s achievement.

它(欧盟的出现)也鼓励一些国家领导人, 效仿西欧的成就，寻求"区域性国际经济一体化"。从20世纪80年代开始，美国和加拿大开始谈判建立各自的"区域自由贸易区"。

'''

==  美国-加拿大 自由贸易协定 (1988)

Beginning in the 1980s, the United States and Canada entered into negotiations to create their own regional free-trading zone. In 1988, the two countries agreed to the Canada-U.S. Free Trade Agreement (Canada-US FTA), which eliminated barriers to the movement of goods and services between the two.

1988年，两国同意《加拿大-美国自由贸易协定》 （Canada-US FTA），消除了两国之间商品和服务流动的障碍。

'''

===  NAFTA 北美自由贸易协定 (1992) → 美国, 加拿大, 墨西哥

Almost immediately, Mexico signaled its interest in creating a similar free trade agreement with the United States. Ultimately, Canada joined the plan with Mexico as well, and by the end of 1992, all three countries had signed the North American Free Trade Agreement (NAFTA).

The intent of NAFTA was to reduce trade barriers and allow goods to flow freely among the three countries. Despite considerable resistance within the United States, largely from industrial workers who feared their factories and jobs would be relocated to Mexico where wages were far lower, the agreement was ratified by all three countries and went into effect in 1994.

墨西哥几乎立即表示有兴趣, 与美国建立类似的"自由贸易协定"。最终，加拿大和墨西哥也加入了该计划，到 1992 年底，这三个国家都签署了"北美自由贸易协定"（NAFTA）。

北美自由贸易协定的目的, 是减少贸易壁垒, 并允许货物在这三个国家之间自由流动。尽管美国国内遭到了相当大的抵制，主要是来自产业工人，他们担心他们的工厂和工作岗位, 会被转移到工资低得多的墨西哥，但该协议还是得到了所有三个国家的批准，并于 1994 年生效。

The creation of Canada-US FTA and later NAFTA represented an important policy shift for the United States.

"加拿大-美国自由贸易协定", 和后来的"北美自由贸易协定"的建立, 代表了美国的重要政策转变。

'''

===  USMCA 美墨加三国协议 (2020)

The impression that NAFTA and globalization have brought poverty and misery to the working class in the United States remains strong and has influenced the nation’s politics since the 1990s.

Responding to these beliefs, in 2017, President Donald Trump instigated a renegotiation of NAFTA, creating the United States-Mexico-Canada Agreement (USMCA). The USMCA included strong property rights protections, compelled Canada to open its dairy market more broadly, and required that workers in the automotive sector in all three countries be paid competitive wages. The agreement replaced NAFTA and went into effect in 2020.

"北美自由贸易协定"和"全球化" (跨国公司, 工作外包到低薪国家 ), 给美国工人阶级带来了(失业)贫困和苦难的印象, 仍然很强烈，并且自 20 世纪 90 年代以来, 一直影响着美国的政治。

为了回应这些信念，唐纳德·特朗普总统于 2017 年发起了"北美自由贸易协定"的重新谈判，制定了"美国-墨西哥-加拿大协议"( USMCA )。 USMCA 包括强有力的"产权保护"，迫使加拿大更广泛地开放其乳制品市场，并要求这三 个国家的汽车行业工人, 获得有竞争力的工资。该协议取代 NAFTA(北美自由贸易协定),  并于 2020 年生效。

'''

===  南美的区域经济合作组织

As the creation of the EU and NAFTA demonstrate, the signing of international trade agreements like GATT, which was ratified by countries on six continents, did not prevent regions from establishing their own free trade blocs like MERCOSUR, the South American trading bloc created in 1991.

正如"欧盟"和"北美自由贸易协定"的创建, 所表明的那样，签署得到六大洲国家批准的"关贸总协定"等国际贸易协定, 并没有阻止各地区建立自己的自由贸易集团，例如 MERCOSUR （1991 年创建的"南美贸易集团"）.

'''

==  亚太的区域经济合作组织

Nor have such blocs been confined to the West. The most notable to emerge in Asia are the Association of Southeast Asian Nations (ASEAN) and the Asia-Pacific Economic Cooperation (APEC).

这些集团也不只限于西方。亚洲最引人注目的新兴组织, 是"东南亚国家联盟(东盟)"（ ASEAN ）和"亚太经济合作组织"（ APEC ）.

'''

===  ASEAN  东盟 (1967. 8)

ASEAN had its beginnings in the 1960s when Indonesia, Malaysia, the Philippines, Singapore, and Thailand agreed to cooperate economically to foster regional development and resist the expansion of communism in Asia. By the early 2000s, it was openly advocating the creation of EU-style integration in the area.

"东盟"成立于 20 世纪 60 年代，当时印度尼西亚、马来西亚、菲律宾、新加坡和泰国, 同意进行经济合作，以促进区域发展, 并抵制共产主义在亚洲的扩张。到2000年代初，它公开主张在该地区建立"欧盟式"的一体化。

'''

===   APEC 亚太经合组织 (1989)

APEC, launched in 1989, was in many ways a response to the growth of regional trading blocs like ASEAN and the EEC. It promotes free trade and international economic cooperation among its members.

1989 年成立的"亚太经合组织", 在很多方面都是对"东盟"和"欧洲经济共同体"等区域贸易集团发展的回应。它促进其成员之间的自由贸易, 和国际经济合作。


'''

==   世界性的经济合作组织

Until the early 1980s, the country had largely avoided limited regional trading deals, preferring instead to seek comprehensive global agreements.

直到 20 世纪 80 年代初，美国基本上避免了有限的"区域贸易协议"，而是更愿意寻求全面的"全球协议"。

'''

===  世界贸易组织 (1995) → 其前身是 “GATT 关税及贸易总协定” (1947)

Such efforts had begun relatively soon after World War II in the form of the General Agreement on Tariffs and Trade (GATT), signed in 1947 by twenty-three countries. Initially conceived as a way to reinforce other postwar economic recovery efforts, GATT was designed to prevent the reemergence of prewar-style trade barriers, to lower trade barriers overall, and to create a system for arbitrating international trade disputes.

此类努力在第二次世界大战后不久, 就以"关税及贸易总协定" (GATT)的形式开始，由 23 个国家于 1947 年签署。"关贸总协定"最初被认为是加强其他战后经济复苏努力的一种方式，旨在防止战前风格的"贸易壁垒"再次出现，总体降低贸易壁垒，并建立一个能"仲裁国际贸易争端"的体系。

In 1995, at the Uruguay Round, GATT transformed itself into the World Trade Organization (WTO) and cleared the path for free trade among 123 countries.

Like GATT, the intent of the WTO was to support international trade, reduce trade barriers, and resolve trade disputes between countries.

Unlike GATT, however, the WTO is not a free trade agreement. Rather, it is an organization that ensures nondiscriminatory trade between WTO countries. This means that trade barriers are allowed, but they must apply equally to all members.

1995年，"乌拉圭回合谈判"中，"关贸总协定"转型为"世界贸易组织"（ WTO ），这为123个国家之间的自由贸易扫清了道路。

与"关贸总协定"一样，"世贸组织"的目的是: 支持国际贸易、减少贸易壁垒, 并解决国家之间的贸易争端。

然而，与"关贸总协定"不同的是，"世贸组织"不是"自由贸易协定"。相反，它是一个"确保世贸组织国家之间非歧视性贸易"的组织。这意味着"贸易壁垒"是允许的，但它们必须平等地适用于所有成员。
Many observers saw the creation of the WTO as a triumph of globalization, or the emergence of a single integrated global economy.

China joined in 2001, a clear sign of its integration into global market systems.

许多观察家将"世贸组织"的创建, 视为"全球化"的胜利，或者"单一的一体化全球经济"的出现。中国于2001 年加入，这是其融入全球市场体系的明显标志。

'''

==  跨国公司 → 对公司管理层有利, 但对底层工人有害 (会因工作转移到低薪国家, 而导致工人失业)

The growing global economic integration represented by the rise of the WTO and regional trading blocs opened new opportunities for multinational corporations (MNC) to extend their reach and influence around the world.

MNCs are not new. Some, like the British East India Company and the Hudson’s Bay Company, exerted great influence during Europe’s imperial expansion in the early modern and modern periods.

以"世贸组织"和"区域贸易集团"的崛起为代表的全球经济一体化, 不断发展，为跨国公司在全球范围内扩大影响力, 提供了新的机遇。跨国公司并不新鲜。英国东印度公司、哈德逊湾公司等一些公司, 在近代早期和近代欧洲帝国扩张过程中, 就发挥过巨大影响.

'''

===  贸易壁垒降低, 给跨国公司领导层带来的利益 → 工作可外包给低薪国家

Companies in the developed world faced challenges rooted in the high cost of living and resulting high wages they had to pay to their employees. Globalization offered a solution in the form of outsourcing and offshoring.

发达国家的公司, 面临着源于"高生活成本"以及由此导致的"高工资"的挑战，他们必须向员工支付高工资。全球化则提供了"外包"和"离岸外包"形式的解决方案.

Multinationals have also benefited greatly from the lowering of trading barriers around the world. In Mexico, for example, workers are paid lower wages than they are in countries like Germany, Japan, South Korea, or the United States. This translates to significant cost savings and thus higher profits for them. And because Mexico is part of a free trade bloc with the United States and Canada, cars made there can be exported for sale in the United States or Canada without the need to pay tariffs.

跨国公司也从世界各地"贸易壁垒"的降低中, 获益匪浅。例如，墨西哥工人的工资, 低于德国、日本、韩国, 美国。这意味着成本的显着节省，从而为他们带来更高的利润。由于墨西哥是"美国和加拿大自由贸易区"的一部分，在那里生产的汽车, 可以出口到美国或加拿大销售，而无需缴纳"关税"。

'''

===  跨国公司, 给本国的底层员工, 带来的伤害 → 工作转移到了低薪外国, 自己失业

Between 1993 and 2021, the United States lost nearly eighteen million manufacturing jobs when some companies found it more profitable to relocate to Mexico. Not all these job losses can be attributed to NAFTA, but many can, as manufacturing that otherwise would have taken place in the United States was moved to maquiladoras, factories in Mexico along the U.S. border that employ people for low wages.

Workers in the automobile industry, once the backbone of the U.S. industrial sector, suffered as jobs and automotive plants were relocated to Mexico.

Some economists, however, argue that the use of inexpensive parts produced in maquiladoras allowed the U.S. automobile industry to survive. Jobs in the clothing industry also declined 85 percent. There were simply fewer obvious advantages to keeping such jobs in the United States.

但从 1993 年到 2021 年，当一些公司发现搬迁到墨西哥更有利可图时，美国失去了近 1800 万个制造业岗位。并非所有这些失业, 都可以归因于"北美自由贸易协定"，但很多都可以归因，因为原本在美国进行的制造业, 转移到了美国边境沿线的墨西哥工厂，以低工资雇用工人。

汽车行业曾经是美国工业部门的支柱，但随着工作岗位和汽车工厂, 迁往墨西哥，汽车行业的工人遭受了苦难。

然而，一些经济学家认为，使用加工厂生产的廉价零部件, 也使美国汽车工业得以生存。服装行业的就业机会也减少了 85%。将这些工作留在美国并没有什么明显的优势。(可见, 用外国低薪工人，对不同位置的人有不同的影响 — 本国企业主得利，工人失业)

'''

===  承接外包的低薪国家的公司, 由很难受到监管, 就成为"血汗工厂".

Those hired overseas experienced their own problems, however, because outsourcing often led to the rise of sweatshops, factories where poorly paid workers labor in dangerous environments.

然而，那些在海外受雇的人, 也遇到了自己的问题，因为外包往往导致"血汗工厂"的兴起，这些工厂的工资很低，工人在危险的环境中劳动。

Even when MNCs commit to providing a safe working environment and fair wages abroad, the practice of subcontracting often makes this impossible to guarantee. Foreign companies to whom multinationals send work often distribute it among a number of smaller companies that may also subcontract it, in turn. It is sometimes difficult for MNCs to know exactly where their goods are actually produced and thus to enforce rules about wages and working conditions.

即使跨国公司承诺, 在国外提供安全的工作环境和公平的工资，但"分包"的做法, 也往往使这一点无法得到保证。跨国公司外包给的外国公司, 通常会继续将其外包给许多较小的公司，这些公司也可能依次将其"分包" (层层外包)。这就使跨国公司有时很难准确了解其产品的"实际生产地"，从而很难执行有关"工资"和"工作条件"的规则。

'''

==  对伊斯兰激进主义的打击

In 2011, the withdrawal of U.S. combat troops from Iraq was completed, eight long years after the invasion. Hopes that peace in Iraq would last were dashed, however, with the rise of the Islamic State of Iraq and the Levant (ISIL), a fundamentalist and militant Islamic group also referred to as the Islamic State.

ISIL leaders proclaimed themselves the heads of a new caliphate, an Islamic state led by a ruler claiming to be a successor to Muhammad, with religious and political authority over all Muslims. This is a claim most of the world’s Muslims reject.

2011年，距入侵伊拉克已有八年之久，美国作战部队完成从伊拉克撤军。然而，随着伊拉克和"黎凡特伊斯兰国"（ ISIL ）的崛起，伊拉克持久和平的希望破灭了，该组织是一个原教旨主义和激进的伊斯兰组织，也被称为"伊斯兰国"。伊斯兰国领导人宣称自己是"新哈里发国"的首脑，这是一个由自称是穆罕默德继承人的统治者领导的伊斯兰国家，对所有穆斯林拥有宗教和政治权威。这是世界上大多数穆斯林拒绝接受的说法。

In 2014, it attacked Iraqi security forces and drove them from a number of cities, including Ramadi, Fallujah, and Mosul. In response, a military coalition led by the United States returned to Iraq following a request by the Iraqi government.

Meanwhile, ISIL’s counterpart in Syria, known as the Islamic State of Iraq and Syria, waged war against both the government of Syria and other nonfundamentalist groups that were also seeking to oust Syria’s president Bashar al- Assad. The U.S.-led coalition that returned to Iraq to fight the Islamic State there intervened in Syria as well.

2014 年，该组织袭击了伊拉克安全部队，将其赶出拉马迪、费卢杰和摩苏尔等多个城市. 作为回应，美国领导的军事联盟, 应伊拉克政府的要求返回伊拉克。

与此同时，“伊斯兰国”在叙利亚的对应组织 “伊拉克和叙利亚伊斯兰国”, 对叙利亚政府和其他同样寻求推翻叙利亚总统巴沙尔·阿萨德的"非原教旨主义"团体, 发动了战争。以美国为首的联军返回伊拉克, 打击伊斯兰国，也对叙利亚进行了干预。

'''



