
= 2-15 基督教制度演变
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== 基督教出现 (1世纪)

In the first century CE, Christians joined this landscape. Christians generally disapproved of animal sacrifice and worship of the emperor.


'''

==  教会改革

=== 教会从领主手中, 获得独立权

The chaotic aftermath of the collapse of the Carolingian Empire led to a complicated situation between secular rulers and the Christian Church. According to German law, lords had the right to control everything on their land, including churches and monasteries. This control even extended to the appointment of officeholders to church positions such as abbot or bishop. To ensure they had the loyalty of church officials, lords staffed these offices with their family members or even sold them to the highest bidder. The consequence was that those without religious vocations, or even familiarity with Christian doctrine, could be installed into church leadership. Even the position of the pope, the bishop of Rome, could come up for sale.


Revulsion at this treatment of religious office led to a reform movement intended to remove the influence of secular lords from the management of the church. The movement is often associated with the monastery of Cluny in France, which managed to get independence from the local aristocrat.


[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|-> 解决"买卖官职"的问题 → 非经正常途径选举出来者 , 直接开除.

|They condemned the sale of offices as a sin called simony and insisted that bishops should be elected by clergy, independent of a lord. Any clergy member who had bought an office or had it bought for them could be removed.


|-> 解决教会体制内"父传子"的问题 → 让牧师无后代, 单身

|To end the practice of treating church positions like a fief to be passed on to the officeholder’s children, priests were told to practice celibacy and were forbidden to marry.


|-> 对想干涉”教会人事任命”的国王, 就将他驱逐出教会

|The church declared that a king who tried to appoint a bishop or asked for a bribe could be excommunicated (placed outside the church, its communion, and the sacraments, in hopes of reforming the offender). Excommunication could threaten the king’s position and lead to rebellions.

|===


The reform movement unintentionally made divisions sharper.


=== 如何区分"(宗教)战争合法性"问题

The reformers were also interested in creating a thoroughly Christianized society by distinguishing between legitimate and illegitimate warfare. The church argued that Christian soldiers, especially knights, should obey a code of conduct that reflected the church’s values. These principles contributed to the ideals of chivalry.


'''

==  东西方基督教的分裂 (1054年大分裂) : 西方天主教, 东方东正教




[.small]
[options="autowidth" cols="1a,1a"]
|===
|the pope in Rome 罗马教皇 |the patriarch of Constantinople 君士坦丁堡宗主教

|- the church in the west operated in Latin


|- The church in the east used Greek


|- insisted on a celibate clergy


|- permitted priests to marry (although tradition held that bishops should be unmarried)


|- elevated the pope as the final authority for all matters regarding the church everywhere.


|- believed other patriarchs were just as authoritative as the pope.

|===


Following this Great Schism of 1054, the eastern church became known as the Eastern Orthodox Church, and the western half the Catholic Church.


'''

==  罗马教皇为了促进宗教改革, 和建立自己的军事力量, 以与日耳曼国王竞争, 就借助”十字军东征”为达到这些目的的途径.

In 1095, facing invasion on all sides, the Byzantine ruler Alexios I sent ambassadors to plead for help from the pope and an opportunity for a reconciliation between the two churches. Urban answered the Byzantine emperor’s call for aid.


Urban’s goal at this point was to free the Holy Land from non-Christian rulers in defense of the Christians living there; it was not a blanket endorsement of violence against Muslims. 

These limitations were later eased, however, as the popes discovered the power of calling repeated crusades to promote the reforming goals of the church and to compete with political rivals in Europe, like the German emperors.



The popes had no armies, and they often had to depend on the unreliable aristocracy for protection when disagreements over church policy resulted in armed conflict with the princes of Europe. If they were to maintain their control over the church in contests with kings and emperors, it would be useful to see what happened when a pope rallied common Christians to a religious cause as a test of faith.


'''

== (14世纪) 教会和君主关系紧张动荡, 导致教皇权威削弱, 及教会内部分裂

In contrast to the stability that had defined much of the thirteenth century for the European Christian Church, it began experiencing significant destabilization in the beginning of the fourteenth century, when tensions between the pope and national monarchs led to a weakening of papal authority and division within the church.


'''

==  新教改革

=== 新教改革前, 教会的腐败状态

The Protestant Reformation began in 1517, but its seeds had been sown years earlier. Over the course of the Middle Ages, the Catholic Church had grown richer, and its higher clerical offices had become dominated by people motivated more by the desire for wealth and power than by spiritual concerns. Although Europe’s peasants remained devoutly attached to their faith, critics claimed that

- popes acted less like Christ’s representatives on earth and more like secular princes, intervening in European political affairs and even commanding armies.
- Members of the clergy often lived lavishly in palatial surroundings and dressed themselves in silks and furs.
- Some had mistresses and illegitimate children, who were often given positions in the church.
- Wealthy families often purchased church offices for their members,
- and some men held bishoprics (areas under the authority of a bishop) in more than one place at a time by hiring other men to perform their offices.

Secular rulers, kings, and princes jealous of the church’s power sometimes vied with the pope for control of the churches in their territory and welcomed opportunities to reject the church’s authority.



'''

===  赎罪券

Indulgences were a way to reduce or even cancel the time after death during which people needed to suffer in purgatory to atone for their sins before reaching heaven. These rewards could be earned by performing actions of great religious merit, such as going on Crusade. However, the church also taught that the pope controlled a store of merit amassed by Jesus and the Christian saints, whose virtue was so great they had entered heaven with grace left over. The church could allot this “extra” virtue to someone else in the form of an indulgence.


'''

===  (路德) 对"赎罪券"的批判, 论证

A German monk named Martin Luther began the Protestant Reformation. Luther was outraged at the selling of indulgences. He drafted ninety-five arguments explaining why the sale of indulgences was wrong.





论证逻辑:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |

|-> 有信仰就能超生, 而不在于行动 (*即"全由上帝决定,非人力可改变,命定论"*)
|- He believed only God could grant forgiveness and that humans could do nothing to ensure their salvation, which depended entirely upon God. This is known as the doctrine of justification by faith.


The Catholic Church taught that salvation was achieved through a combination of religious faith and good works. Buying an indulgence was regarded as a good work because the money went to the church. Luther taught that faith alone was sufficient for salvation and that humans were unable to work toward their own redemption, which depended entirely upon God.


|-> 圣经是唯一的指导内容, 而非后人添加的其他习俗
|- Luther also said the pope had no control over purgatory and that there was no foundation in the Bible for the belief that the merit amassed by Jesus and the saints could be given to others.


- Furthermore, adherence to centuries’ worth of Catholic tradition was not necessary to be a good Christian. Luther contended that scripture alone should be the source of Christian belief and practice. His followers thus abandoned many traditional Catholic practices, including clerical celibacy.


|-> 人能否赎罪,不取决于"赎罪券"
|- Any truly repentant Christian has a right to full remission of penalty and guilt, even without indulgence letters.


|-> "买赎罪券"不是真正的"善行"
|- Christians are to be taught that he who gives to the poor or lends to the needy does a better deed than he who buys indulgences.

Christians are to be taught that the pope would and should wish to give of his own money, even though he had to sell the basilica of St. Peter, to many of those from whom certain hawkers of indulgences cajole money.


|->
|- Protestants also called for the abolition of religious orders of monks and nuns. A life in the clergy, which the Catholic Church had proclaimed the greatest of all callings, was considered no better than the pursuit of any other vocation in life.


|===


In 1521, he was excommunicated (excluded from participating in the life of the church).


'''

===  (加尔文) 的观点 → 命定论

Another center of Protestant thought was the city of Geneva in what is now Switzerland. The city’s religious leader, John Calvin, espoused a doctrine known as predestination, which held that God had predetermined which souls would be granted salvation upon death and which were destined for hell. No person could ever know for certain whether they were saved or damned, and there was nothing they could do to ensure salvation. Calvinists embraced the doctrine, despite denying human agency.


'''

===  路德 & 加尔文 理论的区别

'''

===  作为自救(反腐), 天主教的自我改革

The Catholic Reformation, also called the Counter-Reformation, was the Catholic Church’s effort to address Luther’s challenges as well as to effect other necessary reforms.

- Indulgences were retained, but their sale was forbidden.
- The council prohibited church officials from appointing relatives to church offices,
- limited bishops to holding office in only one bishopric,
- and took steps to improve the education of Catholic clergy and curb their luxurious habits.



'''

==  英国国王(亨利八世) 摆脱教皇, 自立为英国国教首脑

Efforts to silence Martin Luther were unsuccessful, and the new form of Christianity called Protestantism spread throughout the German-speaking lands. Often the new religion was welcomed by rulers as a reason to reject the pope’s authority.


The English Reformation, however, was of a different character. In England, reform was initially imposed from the top down, not by a committed convert but by a king looking for an expedient way to exchange one queen for another.


Henry VIII of England decided to remove himself from under the pope’s authority. Henry declared the English church no longer bound by the pope’s authority. In 1534, Parliament passed the Act of Supremacy, establishing the Church of England with the English monarch as its head.

Under Henry’s leadership, the Church of England (also known as the Anglican Church) remained largely Catholic in terms of both doctrine and ritual, but his failure to purge the English Church of all elements of Roman Catholicism did not sit well with many Protestants.



'''

==  英国"清教徒"(加尔文派), 去往北美, 建立自己的理想宗教"山巅之城” (17世纪初)

During Elizabeth’s reign, English Calvinists, known as Puritans, attempted unsuccessfully to move the Church of England even further from the doctrine and ritual of the Catholic Church.


By the 1570s and 1580s, Puritans had also come to oppose the structure of the Church of England, in which the monarch was the head of the church. They believed churches should be independent and governed by groups of elected elders instead of a king or queen. Elizabeth was unwilling to change the manner in which the Church of England was governed, however.


During the reign of her successor James I, Puritans who wished to separate from the Church of England (known as Separatists) began to depart England for places, including mainland Europe and North America, where they believed they would be able to establish ideal Christian communities.


'''

==  法国确立”天主教”为国教 (1598)

The transition from Catholicism to Protestantism in England was more peaceful than elsewhere. Outside England, the dispute over whether a kingdom should be Catholic or Protestant could be quite violent.

France officially issued the Edict of Nantes in 1598. The edict established Catholicism as the official religion of France.



'''

==  西班牙 (国教: 天主教)

In the Spanish Netherlands, Philip II of Spain fought against Calvinist rebels. The seven northern provinces established their independence from Spain as the United Provinces of the Netherlands. The Netherlands was not the only place in which Philip II, who regarded himself and Spain as defenders of Catholicism, fought to maintain the church’s supremacy. In 1588, he launched a naval attack on England with the intent of restoring it to the Catholic Church and ending its support for Protestant rebels in the Spanish Netherlands. The invasion failed.


'''

==  三十年战争 (新教和天主教之间的宗教战争)

The wars of religion continued into the seventeenth century. From 1618 to 1648, the Thirty Years’ War between Catholic and Protestant states raged in the Holy Roman Empire. As German Catholics, Lutherans, and Calvinists fought one another, other European countries entered the fray.

In the end, the German Protestants were victorious. The Peace of Westphalia, which ended the war in 1648, established the independence of each of the entities, numbering nearly one thousand, that had made up the Holy Roman Empire.


'''

==  基督教, 是要兼容当地文化, 还是严守纯正基督教义的问题 (对中国清朝)

Kangxi tolerated other religions, including Christianity. The Jesuits’ efforts to learn the Chinese language and their respect for Chinese culture made them more successful at winning converts than the Dominicans and Franciscans. But members of these other orders grew jealous and complained to the Pope about the Jesuits’ willingness to accommodate Chinese practices. 

When the Vatican ruled that all church services must be conducted in Latin and that Chinese Christians must be ordered to abandon their ancestral rites, Kangxi decreed that missionaries who complied would have to leave China.


'''
