
= 2-19 人权发展, 工人生存状态的改变, 与工人权力的发展, 社会福利发展
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

Some of the most profound changes brought by industrialization were those that affected the workplace, bringing new challenges while also transforming the nature of labor.


'''

==  反技术变革的努力 (卢德分子, 1811)

Some workers rebelled against industrialization, which threatened their status as skilled laborers. Beginning in 1811, a secretive group of British textile workers calling themselves Luddites began destroying textile machinery, rioting, and setting fires in response to the industrialization of their workplaces. Today, “Luddite” is often used as a generic description of anyone opposed to technological change.


'''

==  (工业革命后) 工人面临恶劣的工作生态

=== 工作条件不掌握在自己手里 ← 从传统社会的自给自足, 到给资本家打工后, 工人失去了”工作条件”上自我控制权.

Industrialization, motivated and enabled by capitalism, created tremendous wealth for business owners and middle-class professionals, but their profits often came at a high cost to workers. The production of goods shifted from the handiwork of highly skilled middle-class artisans to mechanized production done by low-paid unskilled laborers.

Workers did enjoy access to new consumer goods made cheaper by industrialization, but to afford those goods they had to work long hours, in difficult and often dangerous conditions. Perhaps most importantly, workers lost control over their working conditions. Farmers and artisans, particularly those who owned their land or shops, were free to decide how and when they worked, whereas factory owners carefully regulated every aspect of their workers’ professional and even personal lives.



'''

===  工作时间长  ← 有了电之后, 晚上工厂也能运行, 导致工人的工作时间大大加长

With electric lights, the factory floor could be lit twenty-four hours a day, and workers could labor long into the night in all seasons.


Luckily for the subjects of the tsar, the majority of Russian factory workers could look forward to nearly one hundred holidays per year. They would have been envied by Japan’s cotton spinners, teenaged women who often worked for seventeen-hour stretches punctuated only by short breaks.


'''

===  工伤致残

The pace and long hours of mechanized labor took a toll on workers’ health and safety. Injuries were common. 

Fingers and hands were often lost to moving machine parts. 

Constant standing resulted in back problems, swollen feet, and miscarriages. 

In textile factories, inhaled fibers caused breathing problems that left workers permanently disabled. 

The constant noise of machinery led to hearing loss. 

Summer temperatures combined with the heat generated by machinery and moving bodies left workers on the brink of heat exhaustion. 

Laborers in Japan’s silk industry were often scalded while boiling silkworm cocoons. 

Toxic chemicals used in largely unregulated production processes also played havoc with workers’ health and safety. 

In some places, workers, especially women, were beaten by their supervisors; young women sent to work in the Japanese cotton industry by their impoverished parents were often caned or whipped.


Living in a working-class quarter, coming in contact with laborers and their wives, I could not fail to hear tales of the dangers that workingmen faced, of cases of carbonmonoxide gassing in the great steel mills, of painters disabled by lead palsy, of pneumonia and rheumatism among the men in the stockyards. Illinois then had no legislation providing compensation for accident or disease caused by occupation. . .


.磷中毒性颌骨坏死

Phossy jaw is a very distressing form of industrial disease. It comes from breathing the fumes of white or yellow phosphorus, which gives off fumes at room temperature, or from putting into the mouth food or gum or fingers smeared with phosphorus. Even drinking from a glass which has stood on the workbench is dangerous. The phosphorus penetrates into a defective tooth and down through the roots to the jawbone, killing the tissue cells which then become the prey of suppurative germs from the mouth, and abscesses form. The jaw swells and the pain is intense. . . . Sometimes the abscess forms in the upper jaw and works up into the orbit, causing the loss of an eye. In severe cases one lower jawbone may have to be removed, or an upper jawbone—perhaps both.


Occupational Disease: Phosphorus Necrosis +
This set of undated photographs depicts a Dutch woman whose lower jaw has been eaten away by phosphorus, a condition commonly known as “phossy jaw.” The use of phosphorus for match production in the Netherlands was banned in 1901.


'''

===  两害相权取其轻

Despite low pay, long hours, and difficult conditions of factory work, many working-class people preferred it to other types of available labor. Jobs like driving wagons and unloading ships were also low-paying jobs but required working outside in all kinds of weather. Railroad workers were vulnerable to incapacitating injuries from being caught between railcars or falling under their wheels. Miners toiled in dark, cramped environments, where temperatures sometimes rose so high they had to work naked to keep from passing out. Cave-ins were a constant threat. Industrial labor, regardless of the type, was also more highly paid than agricultural labor.


'''

===  环境污染造成的健康伤害 → 呼吸系统疾病

City air was also dirty in the late nineteenth century. Coal was burned to generate both steam power and electricity, and coal smoke plagued industrial cities as they grew in size.

Respiratory problems caused by the inhalation of coal smoke affected many in the nineteenth century. Emphysema, chronic bronchitis, and asthma were common. Approximately one-third of child deaths in nineteenth-century England were attributed to respiratory ailments.



'''

===  卖淫导致性病传播

Prostitution, both formal and informal, was common in nineteenth-century cities. Some prostitutes were professionals who lived in brothels, but many others were simply young single women who could not survive on their meager wages alone.

Sexually transmitted diseases were rampant, however. Many prostitutes and their clients suffered from syphilis, and married men sometimes infected their wives. The result was infertility or babies who were stillborn or blind or had mental disabilities. With no effective cure, syphilis killed its victims after years of agony.



'''

===  失业 ← 不再自给自足后, 由于经济周期, 资本主义下工厂会关闭, 导致工人周期性失业

Work was not always steady; workplaces sometimes shut down unexpectedly when raw materials or work orders fell short. This meant that low pay was often accompanied by periodic unemployment, for which workers had no safety net. Most governments did not provide unemployment insurance, and government-subsidized housing for the poor did not exist. When workers lost their jobs, they were forced to turn to religious institutions or private charities for money for food and rent.


Between 1873 and the end of the century, periodic recessions and depressions alternated with boom periods, rocking economies around the world.


'''

===  未婚女性的工作生态

Factory work was especially desirable to unmarried women, whose most common alternative was domestic service. Living in their employers’ homes, domestic workers were expected to be available at all times of the day and night, were constantly watched, and made very little money. On the factory floor, unmarried young women might be sexually harassed by male employers, supervisors, or coworkers.


Because women were paid less than men, unmarried women did not earn enough to live independently. They tended to live at home, where they were expected to give their wages to their parents and accept a small allowance in return. Even if they rented living quarters with other female workers and shared expenses, they might grant sexual favors to young men in exchange for meals or clothes, a form of casual prostitution known as "treating."

Nevertheless, many young female factory workers enjoyed relative independence before marriage, and the inexpensive entertainment found in industrial cities.



'''

==  罢工合法化 (英国, 1871, 1875)

In 1871, the British government legalized their existence, and in 1875, Parliament made it legal for workers to strike as well.


'''

==  工厂中的妇女减少 (19世纪末)

Early in the Industrial Revolution, women and children worked in factories, but by the end of the nineteenth century, this situation had changed. Although increasing mechanization meant that workers needed less physical strength, the presence of women and children in the workplace declined.


'''

===  工作女性减少的原因

Indeed, many male laborers blamed women’s willingness to accept low wages for keeping their own pay low, and they sought to push women out of the workplace.


'''

===  到20世纪初时, 女性倾向于在家工作

by the beginning of the twentieth century in the United States, France, Great Britain, and Germany, working-class wives tended to supplement the family’s income by working at home, not outside it. Unmarried women and those whose husbands were disabled or absent still sought factory work, but married women more commonly earned money in ways that did not require them to leave the home.

Some cared for the children of working neighbors and took in laundry.

If the family’s living space were large enough, they might take in boarders.

Many women did piecework at home, compensated based on the number of items produced. They collected materials from local businesses and assembled small items like toys, costume jewelry, or artificial flowers. Some stitched together items of clothing.

They were often joined by their children, who might also hawk newspapers and peddle wares on the street.




'''

==  童工现象减少  (19世纪末)

=== 童工能禁止的原因

In the United States and western Europe, children also had largely ceased working in most factories by the beginning of the twentieth century. Greater mechanization of the workplace eliminated the jobs that children had once been employed to do. Increasingly, too, governments passed laws that attempted to ban child labor.

Britain, the first nation to industrialize, led the way in eliminating child labor.

In the face of such opposition to limits on it, child labor continued until laws requiring compulsory education helped to move children from factories to schoolrooms. By the end of the nineteenth century, new laws in the United States and western and central Europe mandated schooling, largely eliminating formal wage work by children under the age of fourteen.




'''

==  第一次世界大战, 令女性获得投票权, 选举权

The sense of independence and the novelty of making their own money spurred many women involved in the war effort to see political reform and voting rights as the next step. For example, many women in Britain viewed the extension of voting rights as a way to reward them for their war work. 

Suffragists had been protesting for years about the need to include women among the voting population in numerous countries such as Britain, Germany, and the United States. 

In 1918, Britain extended the right to vote to property-owning women over thirty. Germany gave women the vote in 1918, the first country to grant universal adult female suffrage, as did the United States in 1920.



'''

==  一战后, 美国原住民获得美国公民身份

Several minority groups in the United States hoped military service would gain them wider acceptance and rights. More than eleven thousand Native Americans served in the military during the war, and many hoped this volunteer service would provide them U.S. citizenship. Native Americans were in fact granted citizenship in 1924.



Another group hoping for change were African Americans. Long subject to discriminatory laws and racial segregation, African Americans felt World War I offered them an opportunity to prove themselves loyal citizens. The United States operated a segregated military, and all-Black service member units serving overseas had a unique chance to see how other places treated them. Those in France, in particular, were struck by the freedom of movement and acceptance they found there. They were allowed in combat, while U.S. units kept them largely in support roles. There was genuine optimism that life in the United States would be different after the war.

However, after 1918, many found that little had changed. Discriminatory laws remained in place, and poor treatment even of veterans was commonplace.



'''

==  二战时, 人民的生活 → 粮食短缺, 配给供应

Where economies were less modern, it was difficult to increase production. Laborers were lost, either through death or because they were sent to Germany to work. As many as twelve million forced laborers from twenty different countries, mostly in eastern and central Europe, fell under German control, further depressing the production of civilian goods.

Since most resources were funneled toward the Germans and away from local populations, much of Europe had to solve the problems of food shortages, rationing, and black markets.



'''

===  东欧情况

Despite German hopes, eastern Europe exported to Germany only 800,000 tons of bread over the course of the war, and hunger and starvation became common experiences for resident populations.



In Norway, the country lost all its foreign trade partners, and its entire economy became tilted toward Germany. The result was that only about 40 percent of Norwegian production was left for consumption by Norwegians, necessitating rationing.


'''

===  希腊情况

In Greece, the appropriation of foodstuffs led to a famine that killed a quarter of a million people in the winter of 1941–1942, including 90 percent of the babies born.


'''

===  德国情况

The Germans instituted a four-year economic plan in 1936, and rationing began in August 1939. The first few years of the war brought little change in their standard of living, but by early 1945, rationing had grown uncomfortably tight.


'''

==  二战是场全民战争, 几乎不分前线和后方

For European countries in World War II, the distance between the battlefield and the home front was often very short or nonexistent. Total war, fought using all available resources with no restrictions on weapons or their targets, took the conflict to millions.


The Allied bombing of Japan was severe as well. The U.S. Air Force destroyed sixty-nine Japanese cities. The March 1945 raid on Tokyo alone killed between 80,000 and 100,000 people and destroyed the homes of a million more. By 1945, Japan was on the verge of economic collapse.


'''

==  二战中, 各国的死亡人数

The United States and the United Kingdom emerged less battered, with 416,000 American and 384,000 British deaths. 

Japan lost 2.1 million military and another million civilians. 

Germany had suffered 5.5 million military deaths and lost as many as three million civilians. 

China’s military deaths can only be approximated but may have been as high as four million, with another sixteen million civilians. 

Soviet military deaths were estimated at 8.8 to 10.7 million, and more than thirteen million civilian deaths were attributed to the war.






'''

==  非洲人也参与二战, 以此作为战后自己国家能独立的”前提贡献”.

Along with becoming a theater of battle in its northern lands, Africa was also drawn into World War II when Africans were enlisted into the armies fighting fascism. More than a million African soldiers fought in Europe, North Africa, Southeast Asia, and the Pacific or provided labor for colonial forces during the war. Most were forcibly recruited and paid far less than White European soldiers. The colonial holdings of the European powers throughout the continent meant that Africa’s resources were available for the war effort. Many Africans saw their loyal contribution to the Allies as a down payment for greater self-determination and independence after the war.


'''

==  联合国在人权上的宣言 (1948)

Beginning in 1948, the United Nations (UN) established a series of universal declarations that conceived of all people as deserving of human rights and dignity (Figure 1.3). Three such declarations further affirmed the rights of women (Convention on the Elimination of All Forms of Discrimination Against Women, also known as CEDAW, 1979), of children (The Declaration of the Rights of the Child, 1959), and of people with disabilities (The Declaration on the Rights of Disabled Persons, 1975). The UN regularly requires that member nations report on progress in these areas.


'''