
= 0121. Ways to Extend Your Healthy Years, Not Just Your Life 延长健康年限而不仅仅是延长生命的方法
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css


'''

==  Ways to Extend Your Healthy Years, Not Just Your Life  延长健康年限而不仅仅是延长生命的方法

`主` healthspans 健康寿命，健康期, usually defined as _the period of life_ 后定 free (a.)不含有害物的；不受…伤害（或影响等的） of  chronic disease or disability, /`谓` do not always match (v.)  longevity 长寿；长命；持久.
By one calculation, based on the World Health Organization’s _healthy life expectancy indicator_ 指示信号；标志；迹象, `主` an American who expects to live (v.) to 79 /`谓` might first face (v.) serious disease at 63.
That could mean /15 years (20 percent of life) lived (v.) in sickness.
Indeed, aging is the biggest risk factor /for cancer, heart disease and dementia 痴呆；精神错乱. +

[.my2]
健康寿命的跨度, 通常定义为没有慢性疾病或残疾的生命周期，并不总是与长寿相匹配。
根据世界卫生组织的"健康预期寿命指标"计算，预计活到 79 岁的美国人可能会在 63 岁时首次面临严重疾病。
这可能意味着 15 年（生命的 20%）都生活在疾病之中。
事实上，衰老是癌症、心脏病和痴呆症的最大危险因素。 +

for decades, _biomedical 生物医学的 research_ and _clinical practice_ 临床实践 have focused on treating (v.) individual diseases, which can extend lives /but not necessarily 不一定；未必 healthspan (n.)健康寿命，健康期. +

We’re now saying /our focus should be on extending (v.) healthy life *rather than* just length of life, and _slowing (v.) aging_ is the tool to do it.
There are molecular and cellular processes in all our tissues and organs 后定 that determine (v.)决定；形成；支配；影响 both life span and healthspan.
These “pillars  柱子，（组织、制度、信仰等的）核心，基础，支柱 of aging” include DNA damage, the aging or senescence (n.)衰老；老年化 of individual cells, inflammation, and stress responses. +

[.my2]
几十年来，生物医学研究和临床实践一直专注于治疗个别疾病，这可以延长生命，但不一定能延长健康寿命。  +
我们现在说, 我们的重点应该是延长健康寿命, 而不仅仅是延长寿命，而"延缓衰老"就是实现这一目标的工具。
我们所有的组织和器官中, 都有分子和细胞过程, 决定寿命和健康寿命。
这些“衰老的支柱”包括 DNA 损伤、单个细胞的衰老或衰老、炎症和应激反应。 +



[.my1]
.案例
====
.NOT NECESˈSARILY
used to say that sth is possibly true but not definitely or always true 不一定；未必 +
- ‘We're going to lose.’ ‘Not necessarily.’ “我们会输的。”“未必。”

.senescence
-> sen-,年老，-esce,表起始，词源同 adolescence.引申词义衰老，老年化。
====

Natural variations 自然变异 in these factors /are mostly the result of environmental differences.
Genes also play (v.) a role, *accounting for* 占比 about 25 percent of the variability (n.) 可变性；易变性；反复不定, more in extreme cases.
(Very long-lived smokers /probably won (v.) the genetic lottery.) The upshot  最后结果；结局 is that /some people age (v.) faster than others, and [with _biological aging_ 生物性衰老] comes (v.) susceptibility (n.)易受影响（或伤害等）的特性；敏感性；过敏性 to disease and disability. +

[.my2]
这些因素的自然变化, 主要是环境差异的结果。
基因也发挥着一定作用，约占变异性的 25%，在极端情况下影响更大。
（非常长寿的吸烟者, 可能赢得了基因彩票。）结果是，有些人比其他人衰老得更快，而且随着生物衰老，人们更容易患上疾病和残疾。 +




[.my1]
.案例
====
.susceptibility
(n.)[ Using.] ~ (to sth) : the state of being very likely to be influenced, harmed or affected by sth 易受影响（或伤害等）的特性；敏感性；过敏性 +
• susceptibility (n.) to disease 易患病的体质
====

How do you assess (v.) biological age? `主` _Molecular markers_ 分子标记 *such as* _chemical modifications_ 化学修饰 to DNA  /`系`  are one way.
Do your cells have a pattern of chemical tags like someone who is 20 or 30 or 40? +

[.my2]
您如何评估生物年龄？ DNA 化学修饰等分子标记是一种方法。
您的细胞是否有像 20 岁、30 岁或 40 岁的人一样的化学标签模式？ +


[.my1]
.案例
====
.chemical modifications to DNA
发生在DNA、RNA碱基和核糖上的各种化学修饰 +
"核酸修饰"是指发生在DNA、RNA碱基和核糖上的各种化学修饰。这些修饰通常不会改变基因的序列，但会影响基因的表达，从而调控多种生理功能。
====


Geroscientists 似乎像杂志名 have yet to deliver (v.)发表；宣布；发布; 交出；交付；移交 a pill or treatment /that can slow (v.) or reverse (v.)颠倒；彻底转变；使完全相反 what _the pillars 支柱 of aging_ do.
But they are excited (a.) about some possibilities.

For example, senolytic (n.)一种小分子名 drugs *target* (v.) senescent 衰老的；变老的；老化的 cells, which no longer divide (v.) but linger (v.)继续存留；缓慢消失; 流连；逗留；徘徊；花很长时间做（某事）；磨蹭 in the body /*instead of* being cleared by the immune system. +

[.my2]
老年科学家尚未开发出能够"减缓或逆转衰老"的药物或治疗方法。
但他们对一些可能性感到兴奋。
例如，抗衰老药物针对衰老细胞，这些细胞不再分裂，而是滞留在体内，而不是被免疫系统清除。


[.my1]
.案例
====
.senolytic
Senolytic 来自 senescence（衰老）+lytic（破坏）

A senolytic (from the words senescence and -lytic, "destroying") is among a class of small molecules under basic research to determine if they can selectively 有选择地 induce (v.) death of senescent 衰老的；变老的；老化的 cells and improve health in humans.  +
A goal of this research is to discover (v.) or develop agents (n.)原动力，动因（指对事态起重要作用的人、事物） to delay, prevent, alleviate (v.)减轻；缓和；缓解, or reverse (v.) age-related diseases.  +
A related concept is "senostatic", which means to suppress (v.)压制；阻止；抑制 senescence. +

senolytic（来自衰老和溶解，“破坏”）是一类正在进行基础研究的小分子，以确定它们是否可以选择性诱导衰老细胞死亡并改善人类健康。这项研究的目标是发现或开发延迟、预防、减轻或逆转与年龄相关的疾病的药物。一个相关的概念是“senostatic”，意思是抑制衰老。

.linger
(v.) 1.~ (on) : to continue to exist for longer than expected 继续存留；缓慢消失
• The faint smell of her perfume lingered in the room. 房间里仍飘溢着她那淡淡的香水味。 +
• The civil war lingered on well (ad.)完全地；彻底地；全部地;很；相当；大大地；远远地 into the 1930s. 这次内战到20世纪30年代还拖了好几年。  +

2.[ usually + adv./prep.] to stay somewhere for longer because you do not want to leave; to spend a long time doing sth 流连；逗留；徘徊；花很长时间做（某事）；磨蹭 +
• She lingered for a few minutes to talk to Nick. 她多待了几分钟，想跟尼克谈一谈。

====

Research has shown that /these “zombie cells” secrete (v.)分泌 proteins that interfere (v.)妨碍；干扰 with other cells' health.
The zombies have been linked to osteoarthritis 骨关节炎, cancer and dementia 痴呆，精神错乱. +

For a 2015 study, researchers used (v.) senolytics 一种小分子名 to remove senescent 衰老的；老化的 cells in mice /and delayed (v.), prevented (v.) or alleviated (v.)减轻；缓和；缓解 multiple disorders. Clinical trials are underway (a.)在进行中的 in people /but are years from completion, so researchers are cautious. +

[.my2]
研究表明，这些“僵尸细胞”会分泌一种蛋白质, 能干扰其他细胞的健康。
僵尸与骨关节炎、癌症和痴呆症有关。 +
在 2015 年的一项研究中，研究人员使用 senolytics 去除小鼠体内的衰老细胞，并延迟、预防或减轻多种疾病。
人体临床试验正在进行中，但距离完成还需要数年时间，因此研究人员持谨慎态度。 +

[.my1]
.案例
====
.osteo-arth-ritis
/ˌɑːstioʊɑːrˈθraɪtɪs/ +
( medical 医) a disease that causes painful swelling and permanent damage in the joints of the body, especially the hips, knees and thumbs 骨关节炎 +
--> osteo-,骨的，arthritis,关节炎，词源同art,articulate.
====


They also note (v.) that /`主` few _popular wellness (n.)健康 claims_ (n.) about “prolonging your youth” /`系`  are grounded (a.)以…为基础；基于 in evidence. +

[.my2]
他们还指出，关于“延长青春”的流行健康主张, 很少有证据支持。 +


[.my1]
.案例
====
.(BE) ˈGROUNDED IN/ON STH
(to be) based on sth 以…为基础；基于 +
• His views are grounded (a.) on the assumption that all people are equal. 他的观点建立在人人平等的假设之上。

.grounded
adj. /ˈɡraʊndɪd/  +
having a sensible and realistic attitude to life （对生活）持有合理和现实态度的 +
• Away from Hollywood, he relies on his family and friends to keep him grounded (a.). 离开好莱坞之后，他靠家人和朋友使自己保持平衡心态。
====

For now, one way to extend healthspan /is through 以；凭借；因为；由于 unsurprising  不令人惊讶的；不足为奇的 preventive (a.)预防性的；防备的 maintenance. +
Experts recommend (v.) checkups 体检, *staying on top of* 持续关注 cholesterol 胆固醇 levels and blood pressure, and following guidelines such as those from _the American Journal of Clinical Nutrition_ 临床营养学 for _body fat percentage_ 体脂率, lean  (a.)脂肪少的；无脂肪的 body mass and _bone density_ 骨密度. +

[.my2]
目前，延长健康寿命的一种方法, 是进行预防性维护。
专家建议进行检查，掌握胆固醇水平和血压，并遵循《美国临床营养学杂志》等指南中关于"体脂百分比"、"去脂体重"和"骨密度"的指南。 +

[.my1]
.案例
====
.through
prep. by means of; because of 以；凭借；因为；由于 +
• You can only achieve success through hard work. 你得孜孜不倦方能成功。 +
• It was through him (= as a result of his help) that I got the job. 我全靠他的帮助才找到这份工作。 +
• The accident happened through no fault of mine. 发生事故并不是我的过错。

.stay on top of
To “stay on top of” something /means to be continuously aware of it and give it your regular attention. +
to “stay on top of” 意味着"持续意识到它并给予定期关注"。

.cholesterol
-> chol, 胆囊，同gall。-ster, 固化，见sterile. -ol, 化学名词后缀，醇，见xylitol.
====

Those steps are also familiar: `主` common-sense (a.)常识的；有生活经验得来的 nutrition, sleep, exercise and social connection /`系` are the four main factors.
The reason those things work (v.) /is because they modulate (v.)调整；调节；控制 the biology 生理 of aging.
For example, regular low- or moderate-intensity exercise /helps (v.) to prevent _cardiovascular 心血管的 disease_ and _type 2 diabetes_.
How much extra health /can these steps get us? Ten years is probably pretty realistic. +

[.my2]
这些步骤也很熟悉：常识性营养、睡眠、锻炼和社交联系是四个主要因素。
这些东西起作用的原因, 是它们能调节生理中的"衰老"变化。
例如，定期进行低强度或中等强度的运, 动有助于预防"心血管疾病"和"2型糖尿病"。
这些步骤可以为我们带来多少额外的健康？十年可能是很现实的。



'''


== Ways to Extend Your Healthy Years, Not Just Your Life

healthspans, usually defined as the period of life free of chronic disease or disability, do not always match longevity.

By one calculation, based on the World Health Organization's healthy life expectancy indicator, an American who expects to live to 79 might first face serious disease at 63. That could mean 15 years (20 percent of life) lived in sickness. Indeed, aging is the biggest risk factor for cancer, heart disease and dementia.

for decades, biomedical research and clinical practice have focused on treating individual diseases, which can extend lives but not necessarily healthspan.

We're now saying our focus should be on extending healthy life rather than just length of life, and slowing aging is the tool to do it. There are molecular and cellular processes in all our tissues and organs that determine both life span and healthspan. These “pillars of aging” include DNA damage, the aging or senescence of individual cells, inflammation, and stress responses.

Natural variations in these factors are mostly the result of environmental differences. Genes also play a role, accounting for about 25 percent of the variability, more in extreme cases. (Very long-lived smokers probably won the genetic lottery.) The upshot is that some people age faster than others, and with biological aging comes susceptibility to disease and disability.

How do you assess biological age? Molecular markers such as chemical modifications to DNA are one way. Do your cells have a pattern of chemical tags like someone who is 20 or 30 or 40?

Geroscientists have yet to deliver a pill or treatment that can slow or reverse what the pillars of aging do. But they are excited about some possibilities. For example, senolytic drugs target senescent cells, which no longer divide but linger in the body instead of being cleared by the immune system. Research has shown that these “zombie cells” secrete proteins that interfere with other cells' health. The zombies have been linked to osteoarthritis, cancer and dementia. For a 2015 study, researchers used senolytics to remove senescent cells in mice and delayed, prevented or alleviated multiple disorders. Clinical trials are underway in people but are years from completion, so researchers are cautious. They also note that few popular wellness claims about “prolonging your youth” are grounded in evidence.

For now, one way to extend healthspan is through unsurprising preventive maintenance. Experts recommend checkups, staying on top of cholesterol levels and blood pressure, and following guidelines such as those from the American Journal of Clinical Nutrition for body fat percentage, lean body mass and bone density.


Those steps are also familiar: common-sense nutrition, sleep, exercise and social connection are the four main factors. The reason those things work is because they modulate the biology of aging. For example, regular low- or moderate-intensity exercise helps to prevent cardiovascular disease and type 2 diabetes. How much extra health can these steps get us? Ten years is probably pretty realistic.

'''


































