
= 0150. Why Children’s Medications Are Not Fully Tested 为什么儿童药物没有经过充分测试
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css

'''





== Why Children’s Medications Are Not Fully Tested 为什么儿童药物没有经过充分测试


Very few medicines are developed with young people in mind.

[.my2]
很少有药物是在开发时考虑到年轻人的。


Turner is referring to the lack of research into how different medications perform in children. When drugs get approved, it’s usually on the basis of how they function in adults. This holds true for nearly all conditions, including mental health disorders, cancer, and rare diseases.

[.my2]
特纳指的是**缺乏对不同药物在儿童中效果的研究。当药物获得批准时，通常是基于它们在成人中的作用。**这几乎适用于所有疾病，包括精神健康障碍、癌症和罕见疾病。


As a result, children are usually prescribed medication “off-label,” meaning the drug is being used differently from what’s specifically outlined on the package insert. Most drugs used for newborns are given off-label, as well as about half of those prescribed for older children.

[.my2]
**因此，儿童的处方药通常是“标签外”的，这意味着药物的使用, 与包装说明书上明确列出的不同。** 大多数用于新生儿的药物都是未经核准的，大约一半用于年龄较大的儿童的处方药也是如此。

This can leave physicians and parents with a difficult dilemma. Although the vast majority of drugs that are used off-label for kids appear to be safe, the lack of proper testing puts children at a relatively higher risk of side effects than adults, experts told Undark. And medications that work well in adults might also be less effective in young people. Further, in dire situations, when the need for medication is urgent, physicians and parents may find that they lack access to clinical trials, which historically excluded children. The reasons for all of this, experts said, are both practical and financial.

[.my2]
这可能会让医生和家长陷入两难的境地。专家告诉 Undark，**尽管绝大多数超适应症用于儿童的药物似乎是安全的，但由于缺乏适当的测试，儿童出现副作用的风险比成人相对较高。对成年人有效的药物对年轻人也可能不太有效。此外，在严峻的情况下，当迫切需要药物时，医生和家长可能会发现他们无法参加临床试验，而临床试验历来将儿童排除在外。**专家表示，这一切的原因既有实际原因，也有经济原因。

The American Academy of Pediatrics has stressed that off-label prescribing does not necessarily entail great risk. Rather, it means that the medication has not met FDA guidelines, which call for studies to be conducted in the population that will use the drug: in this case, children.

[.my2]
美国儿科学会强调，超适应症处方并不一定会带来很大的风险。相反，这意味着该药物不符合 FDA 指南，该指南要求在将使用该药物的人群中进行研究：在这种情况下，是儿童。


Absent such evidence, medical groups create dosing guidelines based on expert consensus. That consensus may be based on a combination of clinical expertise and systematic reviews of the literature, and on input from regulators or organizations such as the World Health Organization. It’s not guesswork in the sense of tossing a coin, explained Turner, who is involved in a European effort to support pediatric clinical trials. Still, he added, it’s less-than-ideal when kids’ medications don’t meet the same bar that everyone expects for adults.

[.my2]
如果没有这样的证据，医疗团体就会根据"专家共识"制定剂量指南。该共识可能基于临床专业知识, 和文献系统回顾的结合，以及监管机构或世界卫生组织等组织的投入。参与欧洲支持儿科临床试验的特纳解释说，这不是抛硬币意义上的猜测。不过，他补充说，当儿童药物达不到每个人对成人的期望标准时，那就不太理想了。

Medicines were developed on an ad-hoc basis until the 1960s, when the Thalidomide scandal led to the reform of the U.S. Food and Drug Administration’s drug approval process. The agency began requiring drugs and medical devices to be tested for specific conditions in clinical trials before they could be widely prescribed. For decades, regulators and medical ethicists argued that children should be excluded from these trials because they are a vulnerable population, considered to be at risk of exploitation by researchers.

[.my2]
直到20世纪60年代，药物都是在临时基础上开发的，当时沙利度胺丑闻导致了美国食品和药物管理局药物审批程序的改革。该机构开始要求药物和医疗器械在广泛开处方之前，必须在临床试验中进行特定条件的测试。*几十年来，监管机构和医学伦理学家认为，儿童应该被排除在这些试验之外，因为他们是弱势群体，被认为有被研究人员剥削的风险。*

These days, scientists agree that research is appropriately safe for children, who have much to gain from participation in clinical trials. But change has been slow. “For the most part, drugs are never developed for kids,” said Florence Bourgeois, an associate professor of pediatrics at Harvard Medical School. “Drugs are developed for use in adults, and then in some cases tested for use in kids.” This allows for greater uncertainty about the safety and effectiveness of medications when they are used in pediatric populations.

[.my2]
如今，科学家们一致认为，研究对于儿童来说是适当安全的，他们可以从参与临床试验中获益匪浅。但变化进展缓慢。 “*在很大程度上，药物从来都不是为儿童开发的，*”哈佛医学院儿科副教授弗洛伦斯·布尔乔亚 (Florence Bourgeois) 说。 “*药物被开发用于成人，然后在某些情况下测试用于儿童。”这使得药物在"儿科人群"中使用时的安全性和有效性, 存在更大的不确定性。*


Children are vulnerable to more or different side effects because their bodies differ significantly from those of adults. For one thing, they grow and develop relatively quickly. Ideally, scientific studies would assess the effect of medicines at each developmental stage, experts said. It’s not a question of dividing a dose by two for teens and four for newborns. Practitioners need to take into account how long a medicine taken by mouth spends in a patient’s stomach, and how it interacts with the liver, kidneys, guts, and intestines.

[.my2]
*儿童很容易受到更多或不同的副作用，因为他们的身体与成人有很大不同。一方面，它们的成长和发展相对较快。专家表示，理想情况下，科学研究将评估药物在每个发育阶段的效果。这不是将青少年剂量除以二、新生儿剂量除以四的问题。医生需要考虑口服药物在患者胃中停留的时间，以及它如何与肝脏、肾脏、内脏和肠道相互作用。*


Additionally, some organs function differently in children. Their kidneys, for example, are less active than those of adults, which could lead to a build-up of toxins or could make the drugs less effective. Babies and toddlers also process food more quickly than their grown-up peers, and they have less fat. And newborns are “much more watery, less fatty than everybody else,” Turner said.

[.my2]
此外，儿童的某些器官的功能, 和成人有不同。例如，**他们的肾脏不如成年人活跃，这可能导致毒素积聚或降低药物的疗效。**婴儿和幼儿比成年人处理食物的速度更快，而且脂肪含量也更少。特纳说，新生儿“比其他人水样多，脂肪少”。

These biological realities make it particularly tricky to provide medical care to babies in neonatal intensive care. Nearly all of the medicines they receive, including even food dispensed through intravenous drips, are untested in humans their size. In these children, it can be hard to distinguish disease symptoms from drug side effects. About 10 adverse drug reactions in babies are reported to the U.K.’s national reporting system each year, but that number is too low to be believed, said Turner. When he and his colleagues did a careful study of a single hospital, they found that 35 out of 193 newborns, or roughly 18 percent, experienced adverse drug reactions. These included fever, increased heart rate, and impaired kidney function.

[.my2]
**这些生物学现实, 使得在"新生儿重症监护室"为婴儿提供医疗护理, 变得特别棘手。他们收到的几乎所有药物，甚至包括通过静脉滴注分配的食物，都未经在同体型的人体中进行过测试。对于这些儿童来说，很难区分"疾病症状"和"药物副作用"。**特纳说，英国国家报告系统, 每年都会报告大约 10 起婴儿药物不良反应，但这个数字太低了，令人难以置信。*当他和同事对一家医院进行仔细研究时，他们发现 193 名新生儿中有 35 名（约 18%）出现过药物不良反应。这些包括发烧、心率加快和肾功能受损。*

“There must be more adverse drug reactions” than are officially counted, said Turner. Doctors just don’t know how to identify these events with certainty.

[.my2]
特纳说，“药物不良反应肯定比官方统计的还要多”。医生只是不知道如何确定地识别这些事件。


And even when the risk of side effects is low, physicians may be unsure about a medicine’s efficacy in pediatric populations, said Harvard’s Bourgeois, who studied the status of off-label prescription in 52 U.S. children’s hospitals. All too often, she said, “we use drugs in kids that ultimately just don’t work.”

[.my2]
哈佛大学的布尔乔亚研究了美国 52 家儿童医院的超说明书处方情况，他表示，*即使副作用的风险很低，医生也可能不确定药物对儿科人群的疗效。她说，“我们经常对孩子使用药物，但最终却不起作用。”*


The relatively poor state of pediatric research also means that children with rare diseases may struggle to access experimental treatments that are available to adults enrolled in clinical trials.

[.my2]
儿科研究状况相对较差, 也意味着患有罕见疾病的儿童, 可能很难获得参加临床试验的成年人可以获得的实验性治疗。



Experts who spoke with Undark pointed to two main reasons for the lack of children in clinical trials: financial incentives and logistics.

[.my2]
接受 Undark 采访的专家指出了**"临床试验中缺乏儿童"的两个主要原因：经济激励和后勤保障。**

Many top-grossing medications are for conditions that primarily affect adults, including rheumatoid arthritis and age-related macular degeneration. In the world of cancer, people under 20 account for just 1 percent of patients.  “That’s 1 percent of the market,” he said. Drug companies don’t stand to earn much from running additional trials, so they don’t. Drug companies will choose what to study “based on the large adult revenue as opposed to considering pediatric need.”

[.my2]
*许多最畅销的药物, 都是针对主要影响成年人的疾病，包括"类风湿性关节炎"和年龄相关性"黄斑变性"。在癌症领域，20岁以下的患者仅占患者的1%。 “那是市场的 1%，”他说。制药公司无法从进行额外的试验中获得太多收益，所以他们也没有这样做。* 制药公司将“根据大量成人收入而不是考虑儿科需求”来选择研究内容。

There are non-monetary hurdles, too. As a group, kids are healthier than adults, making it harder for companies to recruit enough patients for clinical trials. If a hospital wanted to run a clinical trial for a drug to treat ASMD, it would likely need to recruit young patients who live out of state or even in another country. And with neurodevelopmental conditions, such as cerebral palsy, it can take years to understand a therapy’s impact.

[.my2]
也存在"非盈利障碍的原因"。**作为一个群体，儿童比成年人更健康，这使得公司更难招募足够的患者进行临床试验。如果一家医院想要对一种治疗 ASMD 的药物进行临床试验，它可能需要招募居住在州外甚至另一个国家的年轻患者。**对于脑瘫等神经发育疾病，可能需要数年时间才能了解治疗的影响。



Government agencies and politicians have been trying to address the issue. In 2002, Congress passed the Best Pharmaceuticals for Children Act, which offers drug companies six months of extra exclusivity on a patent if they include children in their clinical trial for a drug approval. And in 2003, Congress passed the Pediatric Research Equity Act, which gave the FDA authority to oblige pharmaceutical companies to perform certain initial studies on children. In Europe, these measures were combined in the Pediatric Regulation of 2007.

[.my2]
政府机构和政治家一直在努力解决这个问题。 2002年，国会通过了《儿童最佳药品法案》，*该法案规定，如果制药公司将儿童纳入其药物批准的临床试验中，则他们将获得六个月的额外专利独占权。* 2003 年，国会通过了《儿科研究公平法案》，该法案赋予 FDA 权力，要求制药公司对儿童进行某些初步研究。在欧洲，这些措施被纳入 2007 年的儿科法规中。







'''

== (pure) Why Children’s Medications Are Not Fully Tested



Very few medicines are developed with young people in mind.




Turner is referring to the lack of research into how different medications perform in children. When drugs get approved, it’s usually on the basis of how they function in adults. This holds true for nearly all conditions, including mental health disorders, cancer, and rare diseases.


As a result, children are usually prescribed medication “off-label,” meaning the drug is being used differently from what’s specifically outlined on the package insert. Most drugs used for newborns are given off-label, as well as about half of those prescribed for older children.


This can leave physicians and parents with a difficult dilemma. Although the vast majority of drugs that are used off-label for kids appear to be safe, the lack of proper testing puts children at a relatively higher risk of side effects than adults, experts told Undark. And medications that work well in adults might also be less effective in young people. Further, in dire situations, when the need for medication is urgent, physicians and parents may find that they lack access to clinical trials, which historically excluded children. The reasons for all of this, experts said, are both practical and financial.



The American Academy of Pediatrics has stressed that off-label prescribing does not necessarily entail great risk. Rather, it means that the medication has not met FDA guidelines, which call for studies to be conducted in the population that will use the drug: in this case, children.


Absent such evidence, medical groups create dosing guidelines based on expert consensus. That consensus may be based on a combination of clinical expertise and systematic reviews of the literature, and on input from regulators or organizations such as the World Health Organization. It’s not guesswork in the sense of tossing a coin, explained Turner, who is involved in a European effort to support pediatric clinical trials. Still, he added, it’s less-than-ideal when kids’ medications don’t meet the same bar that everyone expects for adults.


Medicines were developed on an ad-hoc basis until the 1960s, when the Thalidomide scandal led to the reform of the U.S. Food and Drug Administration’s drug approval process. The agency began requiring drugs and medical devices to be tested for specific conditions in clinical trials before they could be widely prescribed. For decades, regulators and medical ethicists argued that children should be excluded from these trials because they are a vulnerable population, considered to be at risk of exploitation by researchers.


These days, scientists agree that research is appropriately safe for children, who have much to gain from participation in clinical trials. But change has been slow. “For the most part, drugs are never developed for kids,” said Florence Bourgeois, an associate professor of pediatrics at Harvard Medical School. “Drugs are developed for use in adults, and then in some cases tested for use in kids.” This allows for greater uncertainty about the safety and effectiveness of medications when they are used in pediatric populations.


Children are vulnerable to more or different side effects because their bodies differ significantly from those of adults. For one thing, they grow and develop relatively quickly. Ideally, scientific studies would assess the effect of medicines at each developmental stage, experts said. It’s not a question of dividing a dose by two for teens and four for newborns. Practitioners need to take into account how long a medicine taken by mouth spends in a patient’s stomach, and how it interacts with the liver, kidneys, guts, and intestines.



Additionally, some organs function differently in children. Their kidneys, for example, are less active than those of adults, which could lead to a build-up of toxins or could make the drugs less effective. Babies and toddlers also process food more quickly than their grown-up peers, and they have less fat. And newborns are “much more watery, less fatty than everybody else,” Turner said.


These biological realities make it particularly tricky to provide medical care to babies in neonatal intensive care. Nearly all of the medicines they receive, including even food dispensed through intravenous drips, are untested in humans their size. In these children, it can be hard to distinguish disease symptoms from drug side effects. About 10 adverse drug reactions in babies are reported to the U.K.’s national reporting system each year, but that number is too low to be believed, said Turner. When he and his colleagues did a careful study of a single hospital, they found that 35 out of 193 newborns, or roughly 18 percent, experienced adverse drug reactions. These included fever, increased heart rate, and impaired kidney function.



“There must be more adverse drug reactions” than are officially counted, said Turner. Doctors just don’t know how to identify these events with certainty.



And even when the risk of side effects is low, physicians may be unsure about a medicine’s efficacy in pediatric populations, said Harvard’s Bourgeois, who studied the status of off-label prescription in 52 U.S. children’s hospitals. All too often, she said, “we use drugs in kids that ultimately just don’t work.”


The relatively poor state of pediatric research also means that children with rare diseases may struggle to access experimental treatments that are available to adults enrolled in clinical trials.


Experts who spoke with Undark pointed to two main reasons for the lack of children in clinical trials: financial incentives and logistics.


Many top-grossing medications are for conditions that primarily affect adults, including rheumatoid arthritis and age-related macular degeneration. In the world of cancer, people under 20 account for just 1 percent of patients.  “That’s 1 percent of the market,” he said. Drug companies don’t stand to earn much from running additional trials, so they don’t. Drug companies will choose what to study “based on the large adult revenue as opposed to considering pediatric need.”

There are non-monetary hurdles, too. As a group, kids are healthier than adults, making it harder for companies to recruit enough patients for clinical trials. If a hospital wanted to run a clinical trial for a drug to treat ASMD, it would likely need to recruit young patients who live out of state or even in another country. And with neurodevelopmental conditions, such as cerebral palsy, it can take years to understand a therapy’s impact.



Government agencies and politicians have been trying to address the issue. In 2002, Congress passed the Best Pharmaceuticals for Children Act, which offers drug companies six months of extra exclusivity on a patent if they include children in their clinical trial for a drug approval. And in 2003, Congress passed the Pediatric Research Equity Act, which gave the FDA authority to oblige pharmaceutical companies to perform certain initial studies on children. In Europe, these measures were combined in the Pediatric Regulation of 2007.


'''
