= 0555
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 555: Lying and Telling the Truth.
This is English as a Second Language Podcast episode 555. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You probably know that. But did you know you can become a Learning Guide member and download Learning Guides for all of our current episodes that will help you improve your English even faster?
This episode is a dialogue between Elizabeth and Leo. It’s going to use a lot of vocabulary related to expressions of lying, or how we talk about telling the truth. Honestly! Let’s get started.
[start of dialogue]
Elizabeth: You’re full of it!
Leo: I’m telling you the God’s honest truth. Why would I eat the last piece of cake when I know that you had your heart set on it?
Elizabeth: That’s the question, isn’t it? Why would you go behind my back and eat it, and then try to put one over on me?
Leo: Would I be able to look you in the eye if I were lying? Look at me. I’m the picture of Honest Abe.
Elizabeth: Do you expect me to believe that?
Leo: There’s not a dishonest bone in my body. I may tell a white lie here and there, but I would never try to tell you a bald-faced lie like this.
Elizabeth: Oh, really? Do you swear?
Leo: I swear that I didn’t eat the last piece of cake.
Elizabeth: There’s something fishy about the way you said that.
Leo: I don’t know what you mean.
Elizabeth: You didn’t eat the last piece of cake, but you know who did.
Leo: I’m pleading the Fifth.
Elizabeth: Spill it, Abe!
Leo: Not on your life!
[end of dialogue]
Elizabeth begins by saying, “You’re full of it!” To say someone is “full of it” means that they are lying, that they are not telling the truth. It’s an informal expression, and a very strong expression. You don’t want to say this to anyone that you work for or work with. It’s a very strong expression. It actually comes from a vulgar expression, which we won’t talk about, but if you put an “sh” in front of the last word, you’ll know what I mean!
Leo says, “I’m telling you the God’s honest truth.” The expression “the God’s honest truth” means it is absolutely, completely true. You say this, or you could say this when someone thinks that you’re lying and you’re trying to convince them that you are telling the truth. Leo says, “Why would I eat the last piece of cake when I know that you had your heart set on it?” So, Elizabeth is mad because she thinks Leo ate the last piece of cake, probably in the refrigerator. Elizabeth had her heart set on it. “To have your heart set on (something)” means that you want it very much; you are planning on getting it. We’ll often use this expression when we don’t get what we were planning on getting. For example, you go to your favorite Japanese restaurant and you want to get a certain kind of sushi, but when you get there they don’t have that sushi today and you’re disappointed. You say, “I had my heart set on the spicy tuna roll,” or whatever it is.
So Leo asks Elizabeth why he would eat the last piece of cake when he knew that Elizabeth had her heart set on it. Elizabeth says, “That’s the question, isn’t it (meaning yes, why did you do that)? Why would you go behind my back and eat it, and then try to put one over on me?” “To go behind (someone’s) back” means to do something without telling the other person, to do something secretly, often something that will affect the other person or that the other person probably did not want you to do. So if your wife tells you that she does not want you to buy a new car, but one day when she is gone you go and you buy a new car, you have gone behind her back. And you are in big trouble buddy, let me tell you, if you did that! “To put one over on (someone)” is a rather complicated sounding expression. It means to trick another person into thinking something that isn’t true. Basically, it’s to lie to the other person, to get them to think something that is false – that is not true: to put one over on someone. “The students really put one over on their teacher, making her think that today was a holiday and there should be no school.” Elizabeth is accusing – she’s saying to Leo that he’s lying.
Leo says, “Would I be able to look you in the eye if I were lying?” The expression “to look (someone) in the eye” means that you can look at someone and honestly tell them the truth. The idea is that you can’t look someone in the eye – look directly at them and still tell a lie. That’s not true, but many people, when they tell a lie, don’t look directly at the other person because they will indicate by the way they are looking at them that they are not telling the truth, that they are lying. That’s the idea, I’m not sure if that’s true. Leo says, “Look at me. I’m the picture of Honest Abe.” “The picture of (something)” means I am just like, I am identical with. “Honest Abe” refers to Abraham Lincoln, the 16th president of the United States in the middle of the 19th century. Abe Lincoln had the reputation for being very honest. I’m not sure if that was true or not, but in the U.S. there is this expression: “Honest Abe.” Honest Abe is somebody who is very honest, who never lies.
So, Elizabeth is being told by Leo that he would never lie to her. Elizabeth says, “Do you expect me to believe that?” Leo says, “There’s not a dishonest bone in my body.” This phrase, “there’s not a dishonest bone in my body,” means that I am not able to lie, it is not even possible for me to lie. Leo continues, “I may tell a white lie here and there, but I would never try to tell you a bald-faced lie like this.” A “white lie” means it’s a small, unimportant matter; it was a lie about something, but not something very important, not something serious. Leo says, “I may tell a white lie here and there (meaning sometimes, occasionally), but I would never try to tell you a bald-faced lie.” A “bald-faced lie” is a lie where you are almost not even trying to hide the fact that you are lying. It’s a bold lie, often a lie about something that you know is completely wrong. That would be a bald-faced lie. “Bald” (bald) usually means someone without hair. “Bald-faced” would be someone who has no hair on their face, meaning they don’t have a beard or a mustache. The idea is that people with beards and mustaches might be dishonest; they’re trying to hide something. I’ve always thought this was true, actually. Never trust a man in a beard!
Elizabeth says, “Oh, really? Do you swear?” Here, “to swear” (swear) means to promise that you are telling the truth, to say very strongly that you are not lying. “Swear” has some other meanings in English very different from this meaning. You can find those in our Learning Guide for this episode.
Leo says, “I swear that I didn’t eat the last piece of cake.” “Elizabeth says, “There’s something fishy about the way you said that.” When you say something is “fishy” (fishy) you mean there’s something strange, something dishonest, something wrong. “There’s something fishy going on here,” meaning there’s something wrong here. Elizabeth says there’s something fishy about the way that Leo said he didn’t eat the last piece of cake, meaning somehow, again, he’s lying.
Leo says, “I don’t know what you mean.” Elizabeth says, “You didn’t eat the last piece of cake, but you know who did (who did eat it).” Leo says, “I’m pleading the Fifth.” This expression means I’m not going to tell you, I refuse to tell you that information because it could harm me. This actually refers, in the U.S., to the Fifth Amendment to the Constitution of the United States, which says that no one can be “compelled,” meaning you can’t make someone say that they committed a crime, especially in a courtroom. So, “to plead the Fifth” means that you have the right, if you will, to protect yourself by not saying that you did something wrong.
Elizabeth says to Leo, “Spill it, Abe!” “Abe,” of course, referring back to Honest Abe. “To spill (something)” in this case means to say something that should be a secret, to tell someone a secret. “Spill” has other meanings also. Once again, take a look at the Learning Guide for those.
Finally, Leo says, “Not on your life!” “Not on your life” is a phrase used to mean that something is not going to happen, even if you kill me I’m not going to tell you. It can also mean absolutely not. If someone asks me, “Jeff, are you going to buy a cat today?” and I say, “Not on your life!”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Elizabeth: You’re full of it!
Leo: I’m telling you the God’s honest truth. Why would I eat the last piece of cake when I know that you had your heart set on it?
Elizabeth: That’s the question, isn’t it? Why would you go behind my back and eat it, and then try to put one over on me?
Leo: Would I be able to look you in the eye if I were lying? Look at me. I’m the picture of Honest Abe.
Elizabeth: Do you expect me to believe that?
Leo: There’s not a dishonest bone in my body. I may tell a white lie here and there, but I would never try to tell you a bald-faced lie like this.
Elizabeth: Oh, really? Do you swear?
Leo: I swear that I didn’t eat the last piece of cake.
Elizabeth: There’s something fishy about the way you said that.
Leo: I don’t know what you mean.
Elizabeth: You didn’t eat the last piece of cake, but you know who did.
Leo: I’m pleading the Fifth.
Elizabeth: Spill it, Abe!
Leo: Not on your life!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse. I swear!
From Los Angeles, California, I’m Jeff McQuillan. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
full of it – saying something that isn’t true; lying or exaggerating
* You’re so full of it! There’s no way you used to be a professional football player. I don’t believe you.
God’s honest truth – something that is absolutely true; used when one wants to emphasize that what one is saying is not a lie
* I would never hurt you, and that’s the God’s honest truth!
to have (one’s) heart set on (something) – to want to be, have, or do something very much
* Capac had his heart set on becoming a doctor, so he was devastated when he wasn’t accepted into medical school.
to go behind (one’s) back – to do something secretly, without letting another person know about it
* How could you go behind my back and read my diary? That’s personal!
to put one over on (someone) – to do something to trick another person and make him or her believe something that isn’t true
* The students really put one over on their teacher, making her think that she had given them the wrong information about when the test would be.
to look (someone) in the eye – to make eye contact with another person, assuming that one can do so only if one is telling the truth, because one would be too ashamed or guilty to look into another person’s eyes if one were lying
* I knew you were lying, because you couldn’t look me in the eye.
the picture of Honest Abe – a person who never tells a lie and is just like former U.S. President Abraham Lincoln who, according to legend, never told a lie
* Luke is the picture of Honest Abe. I don’t think he has ever told a lie.
there’s not a dishonest bone in (one’s) body – a phrase meaning that one does not lie and is not able to lie
* There’s not a dishonest bone in her body. If she said something, then it must be true.
white lie – a small, unimportant lie that doesn’t hurt anyone and doesn’t really matter
* Do you believe there are white lies, or are all lies wrong?
bald-faced lie – a brazen, bold lie; without trying to hide the fact that one is lying
* We couldn’t believe our ears when our own daughter told us such a bald-faced lie about where she had been all evening.
to swear – to promise that one is telling the truth; to say very strongly that one is not lying
* If you swear you’re telling the truth, then I’ll believe you.
fishy – seeming wrong, dishonest, strange, or bad
* There’s something fishy going on here, and as soon as I figure out what it is, you’re going to be in a lot of trouble.
to plead the Fifth – to refuse to share information that could be used against oneself, referring to the Fifth Amendment to the Constitution of the United States, which says that no citizen “shall be compelled in any criminal case to be a witness against himself”
* The man pleaded the Fifth and refused to answer any of the lawyer’s questions.
to spill (something) – to say something that should be kept a secret; to tell a secret; to share information that one did not want to share
* Who spilled it that we were planning a surprise birthday party for Mabelle?
not on (one’s) life – a phrase used to mean that something absolutely will not happen under any circumstances, even if one is facing death; a phrase used to strongly oppose what another person has proposed or suggested
* - You’ll never tell anyone what happened here today, right?
* - Not on your life!
Comprehension Questions
1. What does Elizabeth mean by asking, “Why would you go behind my back and eat it?”
a) She wants to know why he ate the cake while she was in the room.
b) She wants to know why he ate the cake without her knowledge.
c) She wants to know why he ate the cake while standing behind her.
2. What does Elizabeth mean when she says, “there’s something fishy”?
a) She thinks the cake was in the shape of a fish.
b) She thinks the cake had a fish-like flavor.
c) She thinks something doesn’t sound right.
Answers at bottom.
What Else Does It Mean?
to swear
The verb “to swear,” in this podcast, means to promise that one is telling the truth, or to say very strongly that one is not lying: “I swear I’ve never seen her before in my life. Honestly!” The verb “to swear” also means to use vulgar language or bad words: “Please don’t swear in front of the children.” The phrase “to swear an oath” means to make a serious promise, usually when accepting a new job or responsibility: “New police officers have to swear an oath promising to do their job to the best of their abilities.” Finally, the phrase “I could have sworn” means that one really thought one was correct about something, but now one realizes that one was wrong: “I could have sworn I left my glasses on the kitchen table, but now I can’t find them.”
to spill (something)
In this podcast, the phrase “to spill (something)” means to say something that should be kept a secret, or to share information that one did not want to share: “Why did you spill everything to James? I thought we agreed to keep it a secret.” The phrase “to spill the beans” means to accidentally say something that was supposed to have been a secret: “How did you find out what we were planning? Who spilled the beans?” The phrase “to spill (one’s) guts” means to share a lot of personal information that normally wouldn’t be shared: “After a few beers, he was spilling his guts to anyone in the bar who was willing to listen.” Finally, the phrase “to cry over spilt milk” means to spend time feeing sad or bad about something that happened in the past, but cannot be changed: “There’s no reason to cry over spilt milk.”
Culture Note
American children do many things to “prove” (show that something is true) that they are not lying. Children might “swear on their mother’s grave,” where a “grave” is the place where a dead body is buried under the earth. Swearing on one’s mother’s grave means that one is telling the truth, because one wouldn’t want to disrespect one’s mother by lying while standing on or near her grave.
Children also “emphasize” (give importance to) when they are telling the truth by saying, “Cross my heart and hope to die.” This is just a phrase that they repeat without really thinking about the meaning, but it really means that they promise that what they’re saying is true, and that they even hope they die if what they are saying isn’t true.
When a child hears another child say something that is difficult to believe, he or she might ask the other child to “swear” or “double swear” that it’s true. The other child then says, “I swear!” or “I double swear!” to show that he or she is telling the real, serious truth.
American children also do things that they think let them lie with “impunity” (without fear of being punished). Many children believe that if they “cross their fingers” (put their middle finger over their index finger) behind their back, then it “cancels out” (makes something else unimportant) the lie that they are saying. Later, if the child is “accused of” (told that one has done something bad) lying, he or she might say, “But I had my fingers crossed, so it doesn’t ‘count’ (matter).”
Comprehension Answers
1 - b
2 - c