= 0573
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 573: Discussing Social Class.
This is English as a Second Language Podcast episode 573. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download the Learning Guide for this episode, a special 8- to 10-page guide we provide for all of our episodes to help you improve your English even faster.
This episode is called “Discussing Social Class.” It’s a dialogue between Hector and Sophia using a lot of vocabulary related to talking about people at different social and economic levels in a country. Let’s get started.
[start of dialogue]
Hector: Can you believe James? All evening, he tried to tell me how this country would be better if we had no social classes. He’s out of his mind.
Sophia: He was just trying to get a rise out of you. We all know that the two of you don’t see eye to eye.
Hector: He thinks that just because he comes from a working-class background, he can criticize anyone who is middle class or upper class. I just can’t stand his holier-than-thou attitude.
Sophia: He knows you, and he knows which buttons to push to get you worked up. I don’t think he was serious when he said he thought class warfare was a good idea.
Hector: Well, he was downright insulting. He talks as though we have no sense of social responsibility. We do our share for the poor. What more does he want from me?
Sophia: I think he has a chip on his shoulder, because his parents are blue collar and he now lives in a white-collar world. He feels he has to stand up for the marginalized people in our society.
Hector: Okay, but does that mean I have to allow him to insult me under my own roof?
Sophia: Of course not. Next week, we’re having dinner at their house.
[end of dialogue]
Hector says to Sophia, “Can you believe James? All evening, he tried to tell me how this country would be better if we had no social classes. He’s out of his mind.” “Social class” refers to a large group of people who have approximately the same wealth (the same amount of money), education, and what we call “social status,” power and importance in a community or in a society. So Hector is saying his friend James thinks that the United States would be better if we had no social classes, if everyone had the same kind of education and wealth. Hector thinks that he is “out of his mind,” which means he’s crazy.
Sophia says, “He was just trying to get a rise out of you.” “To get a rise (rise) out of (someone)” means to make someone react strongly, usually by getting them angry about something or upset. You don’t really mean sometimes what you say but for fun or for whatever reason you’re trying to get the other person to react – to get angry, so you say something that you know will make him or her upset. Sophia says that that is what James is doing, “We all know that the two of you (Hector and James) don’t see eye to eye.” The phrase “to see eye (eye) to eye,” the things that you have in your head that you use to see, means to agree with someone, to have the same opinion as someone. The Republicans and the Democrats, the two large political parties or groups in the U.S., don’t see eye to eye on many things – on many issues; they don’t agree.
Hector says, “James thinks that just because he comes from a working-class background, he can criticize anyone who is middle class or upper class.” These are three terms we use in talking about social classes. The first one is “working class,” this is a class – a social class made up of people who have less education, who often work in low-paying jobs, usually jobs where you get paid by the hour, that is you don’t get one amount of money for the whole week or month, it depends on how many hours you work. Normally, this is considered those who are less wealthy – have less money than most other people in the society, often people who work at physical or manual labor jobs. Hector says that James comes from a working-class background, meaning his parents were working class, so he thinks he can criticize anyone who is middle class or upper class. Well, if “working class” is the lower class, the “upper class” would be those who have a lot of money – a lot of importance and power in a society. The “middle class” are those that are somewhere in between; you’re not rich but you’re not poor. You have some education, perhaps you went to college, but you’re not necessarily extremely wealthy – you don’t have lot of money. In the United States, most everyone likes to think of themselves as being middle class; it’s the largest group. It sounds not too poor, not too rich. So there are, however, no definitions – no official amount that you have to make in order to be in the middle class or the upper class. These are just terms that people use, often without defining them very carefully.
Hector says, “I just can’t stand James’ holier-than-thou attitude.” He can’t stand it – he can’t tolerate it, it makes him angry. What makes him angry is James’ holier-than-thou attitude. “Holier (holier) -than-thou (thou)” is an expression we use to describe someone who thinks they are better than another person, who feels superior, to be at a higher moral level, more ethical, a better person. Someone who thinks that, we might say, has a holier-than-thou attitude.
Sophia says, “He knows you, and he knows which buttons to push to get you worked up.” “To know which buttons to push” means to know what will make another person react in a certain way. If you have a good friend, you know what makes him angry or what makes him happy. This is especially true with people who are married. They know which buttons to push if they want to get their wife angry or their husband angry; they know what to say that will make him or her mad. That, of course, is one of the great advantages of marriage! Sophia says that James knows which buttons to push to get Hector worked up. “To get worked up,” means to get angry, to get annoyed, to have very negative emotional reactions. There’s actually a couple of meanings of this term, those can be found in the Learning Guide.
Sophia continues, “I don’t think he was serious when he said he thought class warfare was a good idea.” “Warfare” comes from the word “war,” or has the word “war” in it; it means when two groups or two countries are fighting. So, “class warfare” would be when different groups – different social classes in a country or a society are fighting with each other. The poor – the working class are trying to take the money away from the rich and the upper class; that would be an example of class warfare, or the other way around.
Hector says, “Well, he was downright insulting.” “Downright” (downright) is here used as an adverb to emphasize something. Basically, here it means very: “He was downright insulting,” he was very insulting. Usually we use it for a negative adjective. “Insulting” is a negative adjective: it means to be rude, to not be very nice to someone, to say bad things about them to their face – directly to them. Hector says that James talks as though we have no sense of social responsibility. “Social responsibility” is the idea that people who have a lot of money will help those who have less money or less power. He says, “We do our share for the poor.” “To do your share” (share) means to help, to do your part. It means to usually participate in some larger project or larger movement to help people who need help. “Do your share” can also simply mean do what you are supposed to do as part of a larger group. So if you have a group of people at work, you may tell someone to do their share if they’re not working. Probably in that case, we would say to do their part. To do one’s share is often used to describe helping people who need help.
So, Hector says that we do our share for the poor. “What more does he want from me?” he asks. Sophia says, “I think he has a chip on his shoulder.” “To have a chip (chip) on your shoulder” means that you cannot forgive someone for something happened in the past; you feel angry. We might also use the expression “to hold a grudge” (grudge). To have a chip on your shoulder: to have a negative attitude because you’re still angry about something. Sophia says that James’ parents are blue collar and he (James) now lives in a white-collar world. “Blue collar” and “white collar” are two additional terms in English we use to describe different social classes. “Blue collar” is someone who is in the working class, someone who doesn’t make a lot of money. “White collar” refers to people who have professional jobs. Your “collar” is the part of your shirt that goes around the neck, that is next to your neck. If you work in an office, you probably have to wear a shirt that has a collar, and traditionally white shirts were used in business, and still are, often for a man with a tie. So, to be a white-collar worker means to be a teacher, a professor, a lawyer, a businessperson – someone who works in an office. A blue-collar worker tends to be someone who works, again, more manual labor type jobs, working with their hands and their muscles.
Sophia says that James feels he has to stand up for marginalized people in our society – he has to stand up for the marginalized people. “To stand up for” means to defend. “Marginalized” means people who feel unimportant, people who feel they don’t have any power, perhaps because of their race, their skin color, because of the fact that they’re, for example, a woman. Because they have less education and money they don’t feel as though they have power – political power, economic power – in the society where they live.
Hector says, “Okay, but does that mean I have to allow him to insult me under my own roof (roof)?” “Under your own roof” means in your home, where you live; not in public, not at work but at home. So James is at, we are guessing, Hector’s house and he’s still saying these what Hector believes are insulting things. Sophia says, “Of course, not.” You do not have to allow him – permit him – let him insult you in your own house, under your own roof. She says, “Next week, we’ll have dinner at their house.” Hector and Sophia I guess are husband and wife. Sophia is actually joking here, she’s trying to be funny. She’s saying that, well, next week he can insult you at his house, which of course is not what Hector wants either!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Hector: Can you believe James? All evening, he tried to tell me how this country would be better if we had no social classes. He’s out of his mind.
Sophia: He was just trying to get a rise out of you. We all know that the two of you don’t see eye to eye.
Hector: He thinks that just because he comes from a working-class background, he can criticize anyone who is middle class or upper class. I just can’t stand his holier-than-thou attitude.
Sophia: He knows you, and he knows which buttons to push to get you worked up. I don’t think he was serious when he said he thought class warfare was a good idea.
Hector: Well, he was downright insulting. He talks as though we have no sense of social responsibility. We do our share for the poor. What more does he want from me?
Sophia: I think he has a chip on his shoulder, because his parents are blue collar and he now lives in a white-collar world. He feels he has to stand up for the marginalized people in our society.
Hector: Okay, but does that mean I have to allow him to insult me under my own roof?
Sophia: Of course not. Next week, we’re having dinner at their house.
[end of dialogue]
The script for this episode was written by our own white-collar employee here, Dr. Lucy Tse. We’re both what you would call white-collar workers, working in an office.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
social class – a large group of people who have approximately the same wealth (money), education, and social status (power and importance)
* Do you think people in the upper social classes have an obligation to help people in the lower social classes?
to get a rise out of (someone) – to make someone react strongly, usually in anger; to do something just to make another person angry or upset
* Did you do that on purpose just to get a rise out of me?
to see eye to eye – to agree with someone; to share another person’s opinion
* They don’t see eye to eye on politics, but they are best friends anyway.
working class – a social class made up of people who have relatively little education, work in low-paying jobs usually paid by the hour, and normally don’t own property or other assets
* Jeminah grew up in a working-class family and was determined to go to college so that she could become a professional.
middle class – a social class that has moderate wealth, education, and social status; below the upper class, but above the working class
* As the cost of a college education continues to increase, many middle-class families are having a hard time sending their children to a university.
upper class – the wealthiest (richest) and most powerful social class
* Many who attend the symphony and the opera are upper class.
holier-than-thou – thinking that one is better than another person; with feelings of superiority, especially related to moral issues
* Ever since he became a doctor, Frank has had a holier-than-thou attitude toward all his relatives.
to know which buttons to push – to know what to do or say to make another person react in a certain way, especially angrily
* After 20 years of marriage, she knows which buttons to push during an argument with her husband.
worked up – agitated, angry, and annoyed; reacting with strong, negative emotions
* I always get worked up whenever I hear my grandfather talking about his conservative political beliefs.
class warfare – fighting or disagreement between social classes, usually with the lower classes trying to take power and money away from the upper classes
* Some people think that class warfare is unavoidable and that as the upper classes continue to get richer, the lower classes will start a revolution.
downright – used to emphasize that something is completely or totally wrong, bad, or false
* That’s a downright lie! How can you say such a thing?
insulting – very offensive and rude
* Most women consider it insulting if you make a comment about their weight.
social responsibility – the idea that people who are fortunate, lucky, powerful, and wealthy should do things to help people who are less fortunate, lucky, powerful, and wealthy
* Through our social responsibility programs, our company sends thousands of dollars to low-income families each year.
to do (one’s) share – to do one’s part; to help; to participate in a larger project
* Each spring, they try to do their share to take care of the planet by picking up garbage along the beach.
to have a chip on (one’s) shoulder – to hold a grudge; to not be able to forgive someone for something that happened in the past; to feel angry and resentful
* How can you still have a chip on your shoulder? That happened more than three years ago, and it was an accident!
blue collar – related to the working class; related to people who work in low-paying jobs, usually paid by the hour, and often for working with their hands
* She spent her life working in blue-collar jobs in local factories.
white collar – related to professional jobs; related to people who work in higher-paying jobs that require higher education, usually receiving a salary (an amount of money paid each year)
* There are a lot of lawyers, bankers, and other white-collar workers at the party.
marginalized – feeling powerless and unimportant, often because of one’s race (skin color), gender (sex), level of education, or wealth
* Many women feel marginalized in the male-dominated army and navy.
under (one’s) own roof – in one’s own home, not in a public area or in a building owned by another person
* Once you’re living under your own roof, you can follow your own rules. Until then, we expect you to help clean the house and come home no later than 9:00 p.m. each night.
Comprehension Questions
1. Which social class does James belong to?
a) The upper class.
b) The middle class.
c) The working class.
2. What does Hector mean when he says, “we do our share for the poor”?
a) They give money to the poor.
b) They used to be poor.
c) They like poor people.
Answers at bottom.
What Else Does It Mean?
worked up
The phrase “worked up,” in this podcast, means agitated, angry, and annoyed, or reacting with strong, negative emotions: “Why do you get so worked up each time you watch the news?” The phrase “to work up an appetite” means to do a lot of physical activity so that one becomes very hungry: “They really worked up an appetite by going on such a long walk.” The phrase “to work up the courage” means to make oneself become brave enough to do something: “I’ll marry you as soon as I can work up the courage to tell my parents that you don’t have a job!” Finally, the phrase “to work up to (something)” means to gradually prepare to do something that will be difficult or unpleasant: “Bettina is slowly working herself up to a marathon, running a little bit further each day.”
to do (one’s) share
In this podcast, the phrase “to do (one’s) share” means to do one’s part or to help in a larger project or effort: “It makes me really mad when I see that my co-workers aren’t doing their share.” The phrase “(one’s) fair share” is used to talk about an experience that one has had a lot of: “Ingrid has had her fair share of heartache over the years.” Finally, the phrase “the lion’s share of (something)” is used to talk about the largest part of something: “We all ate some of the birthday cake, but Ryan ate the lion’s share of it.”
Culture Note
Many American believe there are three social classes: the upper class, the middle class, and the lower class. However, “social scientists” (people who study society and how people interact with one another) believe this “point of view” (way of understanding things) is too “simplistic” (basic). They have proposed systems with many additional social classes. However, the “dividing lines” (the ways that categories are separated) are “blurry” (unclear), so no one can say how many Americans belong to each class.
Most of the definitions of social class are based on the type of work people do, how much money they make, and how much education they have. The following chart shows one “grouping” (way of organizing things) that has five social classes:
Comprehension Answers
1 - c
2 - a