= 0597
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 597: Describing Touch and Textures.
This is English as a Second Language Podcast episode 597. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com to download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Describing Touch and Textures.” It’s a dialogue between Tommy and Louisa that will use a lot of vocabulary related to the way things physically feel. Let’s get started.
[start of dialogue]
Tommy: It’s just our luck that there’s a major power failure while we’re shopping in this outdoor bazaar.
Louisa: How are we going to find our way back to the hotel?
Tommy: Follow me and stay close. I’ll lead the way.
Louisa: This road is so rough. I keep tripping over the stones. Ah!
Tommy: What happened?
Louisa: I just fell into something wet and sticky. Gross! I don’t know what it is. It has a weird texture.
Tommy: Don’t think about it. If you’re not hurt, then try to get up and keep moving. Give me your hand. Ugh, it’s all slimy!
Louisa: Yeah, and my dress is all greasy, too. You know what? I think I did hurt myself. My foot feels all tingly, like it’s asleep.
Tommy: Try to walk the best you can and let’s try to make it back to the hotel. The road is smooth, not too bumpy, on this side. Let me help you.
Louisa: Thanks. I think I’ll be okay. Well, I guess if we don’t get to see very much more of the city, we’ll at least know what it feels like.
[end of dialogue]
Tommy begins by saying, “It’s just our luck that there’s a major power failure while we’re shopping in this outdoor bazaar.” “It’s just our luck” is a phrase used when something bad has happened, you have been unlucky, and you want to show your frustration. Perhaps it is one of many bad things that have happened. Well here, the bad thing that has happened to Tommy and Louisa is that there has been a “power failure.” In other words there is no electricity, perhaps because there is a storm. Bad weather may have interrupted the “power lines,” that is, the wires that bring electricity to your house. Well, this is a “major power failure,” meaning a large one, usually one that is over a large area. A whole city, for example, could have a power failure.
Tommy and Louisa are shopping in an outdoor bazaar (bazaar). A “bazaar” is a large market, usually outdoors, where people come to sell things and buy things. It’s unusual that they would be complaining about a power failure for the outdoor bazaar unless, of course, it is nighttime, in which case they wouldn’t have any light, unless the moon was full. But, well, we’ll just go with the story here.
Louisa says, “How are we going to find our way back to the hotel?” Tommy says, “Follow me and stay close.” “Follow me (walk behind me) and stay close (make sure that you are physically close to me).” Tommy says, “I’ll lead the way.” The expression “to lead (lead) the way” means to walk in front of someone showing where they should go, so the other person follows you. You will lead the way.
Louisa says, “This road is so rough. I keep tripping over the stones.” “Rough” (rough) is the opposite of “smooth.” A rough surface is where there are many bumps and holes. It is the opposite of smooth; something that is “smooth” has no bumps, no holes, it is straight. The word “rough” has some other meanings in English that can be found in the Learning Guide for this episode on our website. Louisa says she keeps tripping over the stones. “To trip over” is a two-word phrasal verb meaning to accidentally hit your foot against something and to fall down or almost fall down. In this case, “the stones,” which is a kind of material that the street is made of, are not even and so she keeps tripping over them. It’s dark, so she can’t see where she’s walking, of course.
Tommy says, “What happened?” Louisa says, “I just fell into something wet and sticky.” Something that is “sticky” (sticky) is something almost like glue; something that is sticky is able to hold two things together like glue. We sometimes, at least in my family, refer to the small, yellow pieces of paper that you can use to put on things and they will stay there – they will stick – they’re called Post-it Notes, we sometimes call them “stickies.” I don’t know if other people do that, maybe it’s just my family.
Well, poor Louisa fell into something that was wet and sticky. She says, “Gross!” Something that is “gross” is something that is disgusting, something that is very unpleasant, something that is “icky,” we might say (icky). “I don’t know what it is,” she says, “It has a weird texture (texture).” The “texture” of something is the way it feels, whether it’s hard or soft, rough or smooth for example.
Tommy says, “Don’t think about it. If you’re not hurt, then try to get up and keep moving. Give me your hand,” he says, “Ugh, it’s all slimy!” “Slimy” (slimy) is something that is slippery, something that is wet, but it’s also thick, sort of like a thick liquid. Slimy as a texture is very unpleasant to touch. “Slimy” can also be used as an adjective to describe a person who is very unpleasant, someone who perhaps does illegal or unethical things.
Tommy has touched Louisa’s hand and it is slimy, because remember she tripped and fell into something wet and sticky. Louisa says, “Yeah, and my dress is all greasy, too.” Something that is “greasy” (greasy) is something that is oily, something has a lot of oil or fat. If you go to a restaurant – a diner, a particular kind of restaurant – traditional restaurant in the United States, you can get hamburgers, and the hamburgers have a lot of fat in them, so they may taste greasy. They have a lot of fat. Of course, that’s also what makes them taste good! Sometimes we call these diners – these small restaurants “greasy spoons.” The idea is that because they use so much grease everything has grease on them, including the spoons. It also implies the restaurant isn’t very clean. I think that’s what it means, or why we say it. I could be wrong. I often am wrong, my wife tells me that every day!
Louisa goes on to say, “You know what (you know something else, meaning I’m going to tell you something else)? I think I did hurt myself.” Notice she uses “did” here for emphasis. She could just say, “I think I hurt myself,” but she says, “I think I did hurt myself,” because Tommy had said earlier, “If you’re not hurt, then try to get up.” She’s saying that I am, in fact, hurt. She says, “My foot feels all tingly, like it’s asleep.” “Tingly” (tingly) is this usual feeling on your skin as if someone is taking a small pin or needle and touching you rapidly, many times. That’s a tingly feeling or a tingly sensation. Louisa says that her foot feels like it is asleep. When we say “my arm is asleep” or “my foot is asleep” we mean that it feels strange because it was sitting in or staying in one position and suddenly we move it and the blood needs to flow again. Sometimes if you put your foot underneath yourself when you sit, your foot might fall asleep so that you need to give it time to have the blood to keep flowing in there so you don’t have that strange, tingly sensation.
Tommy says, “Try to walk the best you can (as best as you can) and let’s try to make it back (to return) to the hotel. The road is smooth, not too bumpy, on this side. Let me help you.” “The road is smooth (remember smooth is the opposite of rough), not too bumpy,” is how Tommy describes the road. A “bump” is when you have a flat surface, but there are some parts of the surface that go suddenly up and then down, almost like a little hill. “To be bumpy,” then, means to have lots of bumps.
Louisa says, “Thanks. I think I’ll be okay. Well, I guess if we don’t get to see very much more of the city, at least we know what it feels like.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Tommy: It’s just our luck that there’s a major power failure while we’re shopping in this outdoor bazaar.
Louisa: How are we going to find our way back to the hotel?
Tommy: Follow me and stay close. I’ll lead the way.
Louisa: This road is so rough. I keep tripping over the stones. Ah!
Tommy: What happened?
Louisa: I just fell into something wet and sticky. Gross! I don’t know what it is. It has a weird texture.
Tommy: Don’t think about it. If you’re not hurt, then try to get up and keep moving. Give me your hand. Ugh, it’s all slimy!
Louisa: Yeah, and my dress is all greasy, too. You know what? I think I did hurt myself. My foot feels all tingly, like it’s asleep.
Tommy: Try to walk the best you can and let’s try to make it back to the hotel. The road is smooth, not too bumpy, on this side. Let me help you.
Louisa: Thanks. I think I’ll be okay. Well, I guess if we don’t get to see very much more of the city, we’ll at least know what it feels like.
[end of dialogue]
We hope you didn’t find this script too gross. It was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
just our luck – a phrase used when something bad has happened and one wants to show frustration about something that was beyond one’s control, especially when the event is one of many bad things that have happened recently
* It’s just our luck that it rains the day of the big outdoor concert.
power failure – a period of time when there is no electricity, often because of a storm
* The windstorm knocked over several trees that hit the power lines, causing a power failure in our neighborhood.
bazaar – a large market; an open area, usually outdoors, where things are bought and sold by many people
* Holly found some great Christmas presents for her relatives and friends at the craft bazaar.
to lead the way – to walk in front of someone else, showing him or her where to go
* I’ve been on this trail many times in the past and I know where I’m going, so let me lead the way.
rough – not smooth; with an uneven surface; with many bumps and holes
* The wood feels rough now, but it will be nice and smooth once we’ve finished building this dresser.
to trip over – to accidentally hit one’s foot against something and fall or almost fall
* Be careful not to trip over the sleeping dog!
sticky – gluey or glue-like; with the ability to make two things hold together
* These candies are so sticky! I can’t get them off my tongue and teeth!
gross – icky; disgusting; very unpleasant
* Don’t pick your nose in public. It’s so gross!
texture – the way a surface feels, especially whether it is soft or hard, rough or smooth
* Why do most walls have a bumpy texture instead of just being flat?
slimy – slippery, wet, and thick, making one’s fingers slide against each other when touched
* Slugs and snails leave a slimy trail behind them.
greasy – oily; with a lot of oil or fat
* Those French fries were delicious, but very greasy.
tingly – with an unusual feeling on one’s skin as if one is being poked by many small needles
* If I sit with my legs crossed for too long, sometimes they feel tingly when I stand up.
asleep – the strange feeling of a body part after it is suddenly moved from an unusual position and blood begins to flow more freely again
* Last night, he slept on top of his arm, and when he woke up, he realized that his arm had fallen asleep and he could barely move it.
smooth – flat, allowing one’s fingers to move over a surface with no bumps, holes, or gaps
* A baby’s skin is so warm, soft, and smooth!
bumpy – uneven; with many high and low parts on a surface, making it difficult to move over
* This is a bumpy road, so wear your seat belt and hang on!
Comprehension Questions
1. What does Louisa mean when she says that the wet and slimy thing is “gross”?
a) It is very unpleasant.
b) It is very warm.
c) It is very heavy.
2. Why does Louisa say that her foot feels like it is asleep?
a) Because she’s tired of walking.
b) Because she can feel the blood flowing through her foot.
c) Because she wants to go to the hotel to sleep.
Answers at bottom.
What Else Does It Mean?
rough
The word “rough,” in this podcast, means not smooth, or with an uneven surface that has many bumps and holes: “His unshaven face was rough against her hand.” The word “rough” can also mean approximate: “He didn’t know the exact answer, but he made a rough guess.” The word “rough” can be used to describe a difficult period of time when one has many problems: “Last year was rough, with her divorce and her father’s death, but so far this year has been much better.” A “rough night” is a night when one wasn’t able to sleep very well: “The neighbors played loud music until almost 4:00 a.m., so we had a rough night.” Finally, when describing behavior, “rough” means rowdy, violent, very physical, or not gentle: “Don’t be too rough when you play with your little sister.”
gross
In this podcast, the word “gross” means icky, disgusting, or very unpleasant: “It’s so gross to watch people eat with their mouth open!” The phrase “to gross (someone) out” means to make someone else feel disgusted: “Ramona grossed out her brothers by eating a worm.” When talking about money, “gross” is used to describe the total amount of money received before money is taken away for expenses and taxes: “The business has gross revenues of $800,000, but after taxes and expenses, there are no profits.” The verb “to gross” has a related meaning: “The movie grossed more than two million dollars in ticket sales during its first weekend.” Finally, the word “gross” can describe something that is obviously bad or wrong: “Stealing is an example of gross misconduct.”
Culture Note
Adults in the United States don’t touch each other as often as they do in many other countries. American adults often shake hands, especially in a “work setting” (work-related environment), but other “physical contact” (touching) is unusual.
Adult women who are friends may hug each other to say hello or goodbye, but they rarely hold hands or “link arms” (bend one’s arm against another person’s elbow). They generally don’t kiss each other on the cheek (or anywhere else), either.
Adult men are even less likely to hug each other, although very close friends might do so. Men might give each other a “high-five” (a single clap high in the air between the right hand of two people), but any touching beyond that is unusual. Adult men almost never kiss each other, even if they are related.
“Couples” (pairs of people in a romantic relationship) many show more “affection” (care for another person) through physical touching, but “public displays of affection” (things people do to show they like each other when they are around other people) are different from people to people and from place to place. In general, younger couples are more likely to “engage in” (have; do) public displays of affection, kissing and hugging each other, or sitting on one another’s “lap” (the area formed on the top of one’s legs when one is seated). Older couples may hold hands, but are less likely to kiss “in public” (where they can be seen by other people).
Adults casually touch children, often holding hands, hugging, and kissing them. This behavior becomes “rarer” (less common) as the child grows older. And most adults avoid physical contact with children whom they do not know well, because it could be “perceived” (interpreted) as inappropriate touching or “harassment” (unwanted attention or contact).
Comprehension Answers
1 - a
2 - b