= 0600
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 600: Talking About Sight.
This is English as a Second Language Podcast episode 600. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Become a member of ESL Podcast and you can get our Learning Guides for each of our current episodes that will help you improve your English even faster.
This episode is called “Talking About Sight,” about how you see and vocabulary related to seeing. Let’s get started.
[start of dialogue]
Sue: This medication I’m taking is messing with my vision. Everything is blurry.
Hamed: That’s a good reason for you to stay home from work today.
Sue: I can’t. I have to give a presentation this afternoon and I can’t flake out on my coworkers.
Hamed: What good are you to them if you’re blind as a bat?
Sue: Everybody else will have crystal clear vision, so all I have to do is to put in an appearance. Things may not be as sharp as I’d like them to be, but I can still make out people and objects – as long as they’re really big.
Hamed: I don’t think your coworkers are going to want you to blindside them today with your strange behavior. You’re going to do more harm than good.
Sue: I can see well enough. I only see double if I move my head like this. Whoa…
Hamed: At this point, I don’t care if you have X-ray vision. That medication is affecting more than your vision. It’s impairing your better judgment!
[end of dialogue]
Sue begins our dialogue by saying, “This medication I’m taking is messing with my vision. Everything is blurry.” “Medication” is just another word for medicine, or a drug that you take to help your health. “To mess with” is an informal expression meaning to interfere with something or someone, to make something more difficult for someone, to get in someone’s way in order to make something more difficult for them. You may say to someone, “Don’t mess with me.” That’s a rather strong statement; you’re saying if you interfere with me or what I’m trying to do, I am going to do something bad to you; I am going to perhaps hurt you. Here, however, Sue just means that the medication is interfering with, or affecting in a negative way, her vision. “Vision” (vision) is another word for eyesight, which means how well or how poorly you’re able to see things. If you have what we might call perfect eyesight, we would say you have 20-20 vision, meaning you are able to see without any glasses. Well, Sue does not have 20-20 vision. She says, “Everything is blurry (blurry).” When things are “blurry” they are unclear, we would say they are not in focus. Your eyes can’t see them clearly, it’s sort of like there are clouds around them. Or, you can’t see where one thing begins and another ends. Another adjective we might use in this situation when talking about vision is “fuzzy” (fuzzy). “Blurry” is probably more common however.
Hamed says, “That’s a good reason for you to stay home from work today.” He’s telling her that she should not go to work because her vision is blurry. Sue, however, says, “I can’t (I can’t stay home). I have to give a presentation this afternoon and I can’t flake out on my coworkers.” The expression “to flake (flake) out” is a two-word phrasal verb meaning not to do something you are supposed to do, especially something you are supposed to do with another person. For example, you say that you are going to go to a movie with your friend and that you will meet at the movie theater. But then you decide you’re not going to go to the movie and you don’t even tell your friend. That would be “to flake out.” Even if you did tell your friend that could also be considered “flaking out,” especially if you do it at the last minute, meaning right before the actual time you are supposed to go to the movie. We can also used the verb “to flake” to mean the same thing, but “to flake out” is probably more common, the two-word phrasal version.
Sue is giving a presentation with some of her “coworkers,” people with whom she works, and so cannot stay home. Hamed says, “What good are you to them if you’re blind as a bat?” “What good are you to them (means how are you going to help them) if you are blind as a bat?” This is an old expression in English. “To be blind” means to be unable to see. A “bat” is an animal that, I was told in school, doesn’t see. So, “to be blind as a bat” means that you cannot see; you’re unable to see very well.
Sue says, “Everybody else will have crystal clear vision.” Things that are “crystal (crystal) clear” are things that are very clear, very easy to see, or very easy to understand. You can use this not just for vision – eyesight, you can also use it to talk about an explanation for example. “This explanation is crystal clear,” I can understand it easily. We hope these explanations are crystal clear to you! Sue says all she else to do is to put in an appearance. “To put in an appearance” means to show up, to be seen in a particular place even if you don’t do anything important, even if you don’t stay there very long: My friend is getting married, I don’t really want to go to the party after the wedding, what we call the wedding reception, but I need to put in an appearance at the church where he’s getting married. I need to go there and be seen.
Sue says, “Things may not be as sharp as I’d like them to be, but I can still make out people and objects – as long as they’re really big.” “Sharp” here means easy to see, easy to understand, clearly defined, something similar to “crystal clear.” “Sharp,” however, has several other meanings in English, and those can be found in our Learning Guide. She says that she can still make out people and objects. “To make out” is a two-word phrasal verb that means to be able to see something when it is otherwise difficult to see, usually because it is too far away. You see someone walking toward you, but they are far away and you can’t make out if it’s a man or a woman; you can’t see clearly enough.
Hamed says, “I don’t think your coworkers are going to want you to blindside them today with your strange behavior.” “To blindside” (one word) means to surprise someone but in a bad way, in a negative way, to do something unexpected that is very negative. “We were all blindsided when Jenna shared the company’s secrets with the television reporters,” we were all surprised in a very negative way. Hamed says that Sue will blindside her colleagues – her coworkers if she can’t see. He says, “You’re going to do more harm than good.” The expression “to do more harm than good” means that your actions or words will create more problems than they solve, it will be more negative than positive.
Sue says, “I can see well enough. I only see double if I move my head like this. Whoa…” “To see double” means to see two images of something. If you have too much to drink or you have taken some medicine you may start to see double – at least, some kinds of medicine. Sue says that she is seeing two of everything. She only has that problem when she moves her head in a certain way. But when she does this she appears to be affected by it; she says, “Whoa,” which is a way of expressing that you are experiencing something strange or something unusual.
Hamed says, “At this point, I don’t care if you have X-ray vision. That medication is affecting more than your vision.” “X-ray vision” is the ability to see through objects, to see what’s inside of something. If you go to the doctor and the doctor thinks that you may have broken a bone, say in your arm or leg, they may take an X-ray. They may take a special picture which can see inside, if you will, your arm or leg. “To have X-ray vision” is just another way of saying to have incredibly good eyesight, magically good eyesight. I think Superman had X-ray vision; he could see inside of things. I’m not sure; I’ll have to ask him when I talk to him again!
Hamed says the medication – the drugs that Sue is taking is impairing her better judgment. “To impair” (impair) means to make something worse, to make something not as good as it would normally be. Talking on a cell phone while you are driving impairs your ability to drive. That’s true. In fact, some research says that talking on the cell phone and driving is as bad as drinking and driving. Both of those things impair your ability to drive. Your “better judgment” is your ability to know what is right and wrong, or what you should do or say in a particular situation. Hamed is saying that the medication is impairing Sue’s better judgment; she’s not able to think clearly because of the drugs she’s been taking.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sue: This medication I’m taking is messing with my vision. Everything is blurry.
Hamed: That’s a good reason for you to stay home from work today.
Sue: I can’t. I have to give a presentation this afternoon and I can’t flake out on my coworkers.
Hamed: What good are you to them if you’re blind as a bat?
Sue: Everybody else will have crystal clear vision, so all I have to do is to put in an appearance. Things may not be as sharp as I’d like them to be, but I can still make out people and objects – as long as they’re really big.
Hamed: I don’t think your coworkers are going to want you to blindside them today with your strange behavior. You’re going to do more harm than good.
Sue: I can see well enough. I only see double if I move my head like this. Whoa…
Hamed: At this point, I don’t care if you have X-ray vision. That medication is affecting more than your vision. It’s impairing your better judgment!
[end of dialogue]
Don’t mess with the writer of today’s script. That’s because it was Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here at ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
medication – medicine; a substance swallowed or injected to treat an illness or make one feel better
* The doctor gave her a new medication for her high blood pressure.
to mess with – to interfere with something; to change the way something works, making it less effective or more difficult
* Do you think the government has the right to mess with how banks lend money?
vision – eyesight; how well or poorly someone is able to focus the eyes and see things
* Harold had perfect vision until he was a teenager, but then he had to start wearing glasses
blurry – unclear; not in focus
* All of our photos are blurry because there was not enough light.
to flake out – to not do something that one is supposed to do, especially if it makes things difficult or awkward for another person
* I missed our first appointment, so it’s really important that I don’t flake out and forget about the one that has been rescheduled for tomorrow.
blind as a bat – blind or almost blind; unable to see, or unable to see very well
* It’s so dark in here. I’m blind as a bat!
crystal clear – very clear; very easy to see and/or understand; without any difficulty seeing something
* With text that large, the billboard is crystal clear for people to read as they drive by.
to put in an appearance – to be seen in a particular place, even if one doesn’t stay there very long or do anything important while there
* The mayor has three meetings at the same time, but he promised to put in an appearance at our conference, even if it’s only for a few minutes.
sharp – clearly defined; easily seen and understood
* Do you like the sharp lines in this painting?
to make out – to be able to see something when it is very difficult to see, usually because it is too far away
* The detective used a magnifying glass to make out the words on the sign in the photograph.
to blindside – to surprise someone in a bad or negative way; to do something unexpected that has negative consequences
* We were all blindsided when Jenna shared the company’s secrets with reporters.
to do more harm than good – for one’s actions or words to create more problems than they solve; to have a negative impact by doing or saying something
* I know you want to help Shawn, but offering him money might hurt his pride and end up doing more harm than good.
to see double – to see two images of everything, often because one is drunk or has taken medicine
* Luke saw double for a few minutes after he got hit in the head with a baseball.
X-ray vision – the ability to see through objects, either seeing what is inside them or what is on the other side of them
* If airport security guards had X-ray vision, they’d be able to see whether passengers were carrying any weapons.
to impair – to hinder; to make something worse; to make something not as good as it normally is or should be
* Drunk driving is illegal because alcohol consumption impairs a driver’s decision-making and reaction time.
(one’s) better judgment – one’s ability to know what is right and wrong, or what one should do or say in a particular situation
* Against my better judgment, I agreed to let Tara drive my car even though I knew she had been in several car accidents.
Comprehension Questions
1. What does Sue say about her medication?
a) That it is affecting her vision.
b) That it is supposed to improve her vision.
c) That it should make things blurry.
2. If someone is “blind as a bat,” what does he or she see?
a) Everything is blurry.
b) Everything is crystal clear.
c) Everything is sharp.
Answers at bottom.
What Else Does It Mean?
sharp
The word “sharp,” in this podcast, means clearly defined, or easily seen and understood: “The professor’s definition draws a sharp line between conservative and liberal politics.” The word “sharp” also means clever or intelligent: “Maggie is really sharp! She always understands new concepts immediately.” Someone who is “sharp-eared” or “sharp-eyed” is able to hear or see very well: “She wants to get a sharp-eared dog that will hear any intruders.” Someone who is “sharp-tongued” is very direct and says mean or unfriendly things that hurt other people’s feelings: “If you want to be successful in your career, you’ll have to find a way to be less sharp-tongued.” Finally, someone who is “sharp-witted” is able to think very quickly and create clever responses in very little time: “Sharp-witted students do very well on the school’s debate team.”
to see double
In this podcast, the phrase “to see double” means to see two images of everything, often because one is drunk or medicated: “When you start seeing double, you know you’ve had too much to drink.” The phrase “to be seeing things” means to see things that aren’t really there: “I’m so tired that I’m seeing things. I definitely need to get some sleep soon.” The phrase “to have seen better days” means for something or someone to be worse than it once was, or to be in poor condition: “They bought their car new, but that was over 10 years ago, and it has definitely seen better days.” Finally, the phrase “to see the light” means to realize that something is true after one has not believed it for a long period of time: “Karina’s parents finally saw the light and agreed to help her pay for college.”
Culture Note
Many people who are blind or “visually impaired” (not able to see very well) use “guide dogs,” or dogs that have been “trained” (instructed; taught) to lead people around “obstacles” (things that are in one’s way and must be walked over or around). Many “breeds” (types) of dogs can be trained as guide dogs, but Golden Retrievers, Labradors, and German Shepherds are the most common ones.
Of course, guide dogs cannot read street signs, and they are “partially” (partly, not completely) “color-blind” (unable to see differences in some or all colors), so they cannot “navigate” (give directions) for their owner. The blind or visually impaired individual must know how to go from one place to another. The guide dog is there to help the individual get there safely. For example, guide dogs can help their owner stay on the sidewalk, avoid “bumping into” (hitting) other people or buildings, avoid “tripping” (hitting something with one’s foot and falling or almost falling) over “uneven” (not smooth) pavement, and stop at “intersections” (where two or more streets cross).
Normally, dogs and other animals are not allowed in restaurants and stores in the United States. However, different rules are applied to guide dogs. The Americans with Disabilities “Act” (law) “prevents” (does not allow) businesses from “barring” (not allowing) guide dogs on the “premises” (the place of business; where work is done). In addition, “landlords” (people who own homes or apartments and rent them to other people) have to let “tenants” (people who rent a home or apartment) live with their guide dog and cannot charge them an extra “fee” (money that must be paid for a particular purpose) as they can do for other tenants who choose to have “pets” (animals that live with people for entertainment and companionship).
Comprehension Answers
1 - a
2 - a