
= eco 2020.01 (02)
:toc:

---

== 02. Taiwan’s China-sceptic president, Tsai Ing-wen, may win again

But the threat from Beijing *is not going away*

对中国持怀疑态度的台湾总统蔡英文, 可能会再次获胜 +
但来自北京的威胁不会消失

Jan 2nd 2020 | KAOHSIUNG 高雄 AND TAIPEI

ELECTION RALLIES(`=rally : a large public meeting, especially one held to support a particular idea or political party 公众集会，群众大会（尤指支持某信念或政党的）`) in Taiwan *often feel like* festivals with a dash(`=~ (of sth) a small amount of sth that is added to sth else 少量，少许（添加物）`) of politics *thrown 投；掷；抛；扔 in*.

At a recent one [in Taiwan’s capital, Taipei], thousands of people *watched* a fireworks (大量烟火同时燃放的)烟花表演 display, then *heard* a blind blues(n.)布鲁斯音乐， 蓝调 （源于美国南部黑人，节奏感强、缓慢忧郁） singer.

Eventually the show’s political star *took to the stage*: Enoch Wu, a young would-be(a.)(`=used to describe sb who is hoping to become the type of person mentioned （形容想要成为…的人）未来的`) legislator(`= a member of a group of people that has the power to make laws 立法委员`) for the ruling(a.)(`=having control over a particular group, country, etc. 统治的；支配的；占统治地位的`) Democratic Progressive Party (DPP).

China’s leader, Xi Jinping, “*is watching to see* if we *are sure(a.) to defend* our homeland,” he *told* the crowd. “We *are*,” his fans *roared 吼叫,咆哮; 叫喊,大声地说 back*.

====
- ruling : a. having control over a particular group, country, etc. 统治的；支配的；占统治地位的 +
-> *the ruling party* 执政党
====
台湾的选举集会, 常常感觉像是在节日中掺杂了政治活动。最近在台湾首都台北举行的一场活动中，数千人观看了焰火表演，然后听到一位盲人布鲁斯歌手的唱歌。最终，本活动的政治明星走上了舞台:Enoch Wu，一个有望成为当前执政民进党的立法委员的年轻人。他对人群说, 中国领导人习近平“正在观察我们是否一定能保卫我们的国家，是的!” 他的粉丝们也大声回应。


One question *always looms largest* in Taiwan’s elections for president and parliament, *held simultaneously* 同时地 every four years, this time on January 11th: *how to handle* the island’s twitchy(a.)(`=nervous or anxious about sth 神经紧张的；焦急的；焦虑不安的; /making sudden quick movements 抽搐的；抽动的；痉挛的`) relations with an ever more powerful China.

Many of Taiwan’s nearly 24m people *have been warily 警惕地；谨慎地；留心地 watching* the unrest(n.)(`=a political situation in which people are angry and likely to protest or fight 动荡；动乱；骚动`) in Hong Kong.

Twice in 2019 Mr Xi *declared that* Taiwan *should reunify with* the mainland under a “one country, two systems” formula(`=a particular method of doing or achieving sth 方案；方法`), as Hong Kong did.

China’s ability *to force* such a solution on Taiwan *is increasingly plain*(a.)(`=easy to see or understand 清楚的；明显的；浅白的`).

On December 26th China *sent* its newly commissioned(`=to choose sb as an officer in one of the armed forces 任命…为军官`) aircraft-carrier 航空母舰, the Shandong, *through* the Taiwan Strait for the second time in as many months.

每四年一次的台湾总统选举, 和议会选举, 将在1月11日同时举行，其中一个最突出的问题是: 如何处理台湾与日益强大的中国大陆之间的紧张关系。台湾近2400万人口中的许多人, 一直在留心注意着香港的骚乱。习近平曾在2019年两次宣布，台湾应该按照“一国两制”的模式与大陆统一，就像香港那样。中国迫使台湾接受这种解决方案的能力, 已经越来越明显。12月26日，中国派遣其新服役的航空母舰“山东号”, 在几个月内第二次通过了台湾海峡。

Since 2000 Taiwanese voters’ main choice for president *has been [either]* a candidate who *leans*(`=to have a tendency to prefer sth, especially a particular opinion or interest 倾向，偏向（尤指某意见或利益）;/ 前俯（或后仰）；倾斜`) *toward* independence from China, thereby *incurring* China’s wrath(n.)(`=extreme anger 盛怒；震怒；怒火`), *[or]* one who *wants* closer ties despite the risk of ensnarement(n.)诱捕，诱入圈套 by the mainland’s Communists.

====
- wrath => 来自 PIE wreit,弯，转，扭曲，词源同 wreath, writhe. 引申词义愤怒，尤指神的愤怒。
====

[So far] the China-sceptic 惯持怀疑态度的人；怀疑论者, pro-independence DPP(`=民进党（Democratic Progressive Party）`) *has won* three times and the China-embracing Kuomintang (KMT) twice.

The legislature 立法机关；立法机构, however, *has usually been controlled by* China-friendly types -- until 2016, when the DPP *secured* [*both*] the presidency 主席的职位（或任期等）；总统的职位（或任期等） -- with Tsai Ing-wen *becoming* Taiwan’s first female leader -- [*and*] a majority in the Legislative Yuan 立法院, *as* the parliament *is known*.

自2000年以来，台湾选民所选择的总统候选人, 大多数时候, 要么是那些倾向于从中国独立，从而招致中国的愤怒的候选人; 要么是希望与大陆建立更紧密联系的候选人人，尽管会冒着踏上大陆圈套的风险。到目前为止，对中国持怀疑态度、支持台独的民进党, 赢得了三次大选; 支持中国的国民党, 赢得了两次大选。然而，立法机关通常是由亲大陆的一派控制的 —— 这种情况直到2016年为止，改年, 民进党在蔡英文, 成为台湾首位女领导人. 并且民进党派在获得总统职位的同时, 还获得了立法院的多数席位。立法院, 等同于众所周知的国会.

Ms Tsai’s support for Hong Kong’s protesters *seems to have boosted her chance of* winning again.

American talk of “*decoupling*”(v.)(`=*decouple sth (from sth)* : ( formal ) to end the connection or relationship between two things （使两事物）分离，隔断`) *from* China’s economy, particularly in technology, *has helped* her, too.

Taiwan’s tech giants *do not want to risk* losing access to Western markets *by siding with* China.

Some *are moving out of China* and *are investing more in* South-East Asia and *in* Taiwan itself.

Less(ad.) *focused on* the mainland, some Taiwanese businessmen *are becoming keener*(a.)(`= *~ on sb/sth/on doing sth* ( BrE informal ) : liking sb/sth very much; very interested in sb/sth 喜爱；（对…）着迷，有兴趣; // *~ (to do sth) /~ (that...) /~ (on doing sth)* :  ( especially BrE ) wanting to do sth or wanting sth to happen very much 渴望；热切；热衷于`) *on* the DPP.

====
- decouple => de-, 不，非，使相反。couple, 成对，夫妇。
====

蔡英文对香港抗议者的支持, 似乎增加了她再次获胜的机会。美国人关于与中国经济“脱钩”的言论，特别是在技术方面，也帮助了她。台湾的科技巨头不想冒着失去进入西方市场的风险而站在中国一边。一些人正在离开中国，并在东南亚和台湾本身进行更多的投资。一些台商对大陆的关注度降低，对民进党越来越感兴趣。

Ms Tsai’s main opponent *is* the KMT’s Han Kuo-yu 韩国瑜, the mayor of the southern port city of Kaohsiung, which *is* usually a DPP stronghold(`=堡垒；要塞；据点;/ 有广泛支持的地方；势力强大的地方`).

His chances *dipped*(`=to go downwards or to a lower level; to make sth do this （使）下降，下沉;/蘸；浸`) in November when another China-friendly politician, James Soong 宋楚瑜 of the People First Party 亲民党, *entered* the fray(n.)(`=a fight, a competition or an argument, especially one that is exciting or seen as a test of your ability 打斗，竞争，争辩（尤指激烈或视为检验能力的）`). Mr Soong *may peel 剥（水果、蔬菜等的）皮；去皮 away*(`=*peel (sth) away/off/back* : to remove a layer, covering, etc. from the surface of sth; to come off the surface of sth 剥掉；揭掉；剥落`) some of Mr Han’s supporters.

====
- fray => 缩写自affray, 打架滋事，闹事，使恐慌，词源同afraid. +
-> *to enter/join the fray* 加入争辩 +
-> At 71, he *has now retired from the political fray*. 他现年71岁，已经退出了政治角逐。
====

蔡英文的主要对手是国民党的韩国瑜，他是南部港口城市高雄的市长，高雄通常是民进党的大本营。他的机会在11月下降，当时另一位对中国友好的政客，亲民党的宋楚瑜加入了竞争。宋楚瑜可能会剥离韩先生的一些支持者。

The president *hammers （用锤子）敲，锤打 home*(`=*hammer sth home* : to emphasize a point, an idea, etc. so that people fully understand it 反复讲透，重点讲清（要点、想法等）`) her China point.

In a televised 在电视上播放 presidential debate she *read out* a letter from a young Hong Konger. “I *ask* Taiwan’s people *not believe* the Chinese Communists,” the author *said*. “*Don’t fall into* China’s money trap.” Ms Tsai *also boasts that* the economy under the DPP *has grown*, *following* a recession 经济衰退；经济萎缩 under the previous KMT government.

总统反复强调她的中国观点。在一场电视总统辩论中，她宣读了一封来自一位年轻香港人的信。“我要求台湾人民不要相信中共，”作者说。“不要落入中国的金钱陷阱.” 蔡英文还吹嘘说，民进党领导下的经济, 在经历了前国民党政府的衰退后, 已经增长。

Some voters *are not persuaded*. Salaries, they *grumble*(`=*~ (at/to sb) (about/at sb/sth)* : to complain about sb/sth in a bad-tempered way 咕哝；嘟囔；发牢骚`), *have been virtually flat*(a.)(`=水平的；平坦的; /not very successful because very little is being sold 不景气的；萧条的；生意清淡的`) for almost two decades.

The average monthly full-time wage is NT$49,170 ($1,635), *including* bonuses, *far lower than* in other rich countries in the region, such as Singapore where it is about S$4,560 ($3,390).

Poorer and older people *tend to back*(`=to give help or support to sb/sth 帮助；支持;/to bet money on a horse in a race, a team in a competition, etc. 下赌注于（赛马、参赛队伍等）`) Mr Han, who *harks back to*(`=*HARK BACK (TO STH)* : to remember or talk about sth that happened in the past 回忆起，重提（过去的事）;/ to remind you of, or to be like, sth in the past 使想起；和（过去的事物）相似`) the boom years of the 1970s and 1980s under the KMT. (He *avoids reminding* them *that* Taiwan was then a one-party dictatorship 独裁国家).

====
- hark => 来自hear,听，-k,表强调。比较tale,talk. +
-> She'*s always harking back to*(`=to remember or talk about sth that happened in the past 回忆起，重提（过去的事）`) how things used to be. 她总是念叨以前的世道。 +
-> The newest styles *hark back to*(`=to remind you of, or to be like, sth in the past 使想起；和（过去的事物）相似`) the clothes of the Seventies. 最新的款式使人想起七十年代的服装
====

一些选民没有被说服。他们抱怨说，近20年来，工资几乎没有增长。包括奖金在内，平均的月全职工资, 为49，170元新台币(合1，635美元)，远低于该地区的其他富裕国家，如新加坡，约为4，560新元(合3，390美元)。穷人和老年人倾向于支持韩先生，他让人回想起国民党统治下的20世纪70年代和80年代的繁荣时期。(他避免了去提醒他们, 台湾当时是一党专政的(就跟现在的中国大陆一样))。

Mr Han *is* unlikely *to win* the presidency, but *there is* more of a question-mark 疑问; 不确定性;问号 over the legislature. `主` Mr Wu, the DPP(`=民进党 Democratic Progressive Party`) candidate who *tried to whip 鞭打；鞭策 up*(`=*whip sb/sth up* : to deliberately try and make people excited or feel strongly about sth 激发；激励；煽动`) support(n.) 方式状 *with* fireworks and blues, `谓` *may have excited* his backers 方式状 *with* talk of a Chinese threat.

But *that is because* his KMT rival *is* Wayne 韦恩 Chiang 蒋万安 -- a great-grandson of Chiang Kai-shek 蒋介石(音译:常凯申) and grandson of Chiang Ching-kuo 蒋经国, rulers 统治者；支配者 of Taiwan during nearly four decades of martial law(`=*martial law* : a situation where the army of a country controls an area instead of the police during a time of trouble 军事管制；戒严`).

Though the Chiangs *hated* the Communists *for* ousting(v.)(`=*oust sb (from sth/as sth)* : to force sb out of a job or position of power, especially in order to take their place 剥夺；罢免；革职`) them from China, DPP loyalists （尤指在变动时期对统治者、政府或政党）忠诚的人 *consider* them China incarnate(a.)(`= (usually after nouns 通常在名词之后) ( formal ) in human form 人体化的；化身的；拟人化的`): mainland-born autocrats(`=a ruler who has complete power 独裁者；专制统治者；专制君主`) who *tried to crush* Taiwanese culture.

All the same 尽管如此;依然, `主` Wayne Chiang, an incumbent(`=a person who has an official position 在职者；现任者`) MP(`=国会议员（Member of Parliament）`) with a local following(n.)(`=a group of supporters （统称）拥护者，追随者`), `系` *will be hard to beat*.

====
- incarnate => in-,进入，使，-carn,肉，词源同carnal,carnage.即肉体化，引申词义具体化，拟人化。
- incumbent => in-,进入，使，在上面，-cumb,躺，词源同incubate,succumb.即躺在上面的，引申词义在任者。
====

韩先生不太可能赢得总统宝座，但立法机构有更多的问题。民进党候选人吴先生曾试图用烟花和蓝调来激起民众的支持，但他关于中国威胁的言论可能已经让他的支持者们兴奋不已。但这是因为他的国民党对手蒋万安, 是蒋介石的曾孙，也是蒋经国的孙子，蒋经国是台湾近40年戒严时期的统治者。尽管蒋介石憎恨共产党将他们赶出中国，但民进党的忠诚者却认为他们是中国的化身：他们是出生自大陆的独裁者, 并且试图粉碎台湾文化。尽管如此，拥有当地追随者的现任议员蒋万安(Wayne Chiang)也并不容易被击败。

If the DPP *loses control of* the 113-strong(`=strong : used after numbers to show the size of a group （用于数字后，表示某集体的规模）多达…的，计有…的`) parliament, where it now *has* 68 seats, Ms Tsai *will have a hard time* ruling.

The KMT and its allies *could block bills* disliked by China, such as a law *passed* on December 31st *making it illegal* to accept Chinese funds for political activities. (台湾《反渗透法》)

The KMT *says* it *supports* measures *to strengthen* national security, but *condemns* the recent bill *as* too sweeping(a.)(`=too general and failing to think about or understand particular examples （过分）笼统的；一概而论的`).

如果民进党失去对议会的控制, 该议会总共有113人的名额, 民进党目前控制了其中68个席位，蔡英文将很难执政。国民党及其盟友可以禁止掉令中国不喜欢的法案，比如在12月31日通过的一项法律(《反渗透法》)，该法律规定, 接受中国资金用于政治活动的行为, 是非法的。国民党表示, 它对能加强国家安全的措施，是支持的, 但谴责最近通过的这项《反渗透法》法案过于笼统。

China *has denounced*(`=to strongly criticize sb/sth that you think is wrong, illegal, etc. 谴责；指责；斥责`) it, too, but *has largely refrained from* sabre-rattling(n.)(`= the act of trying to frighten sb by threatening to use force 武力威胁；武力恫吓. / sabre :（弯刃）军刀，马刀;（击剑运动用的）佩剑 /rattle :（使）发出咔嗒咔嗒的声音`) during the campaign *to avoid playing into Ms Tsai’s hands*(`=*play into someones hand* : 正中下怀`).

After she *was elected*, China *bolstered*(`=*bolster sth (up)* : to improve sth or make it stronger 改善；加强`) its military posturing(n.)(`=behaviour that is not natural or sincere but is intended to attract attention or to have a particular effect 做作的举止；忸怩作态；虚伪表现`), *for instance* with bomber-jets *flying around* the island.

It also *persuaded* seven of Taiwan’s diplomatic allies *to switch to* China, *reducing* the number *to* 15.

But [since the middle of 2019] the jets *have stopped their exercises*. The aircraft-carrier’s 航空母舰 transits(n.)(`=the act of going through a place on the way to somewhere else 通过；经过；通行；过境；中转`) *raised* eyebrows(`=*raise your eyebrows (at sth)* : to show that you disapprove of or are surprised by sth 扬起眉毛（表示不赞同或惊讶）`) in Taiwan, but Andrew Yang, a former deputy 副手；副职；代理;（某些国家的）议员 defence minister for the KMT, *says* they were routine tests.

中国也谴责了这种行为，但在竞选期间，为了避免正中蔡英文的下怀，中国在很大程度上避免了进行武力恫吓。在她当选后，中国加强了其军事姿态，例如用轰炸机环岛飞行。它还说服了台湾的7个外交盟友转投中国大陆，将这一数字降至15个。但自2019年年中以来，这些战机停止了演习。这艘航母的过境在台湾引起了关注，但国民党前国防部副部长 Andrew Yang 表示，这只是大陆的例行测试。

Should （表示可能）假如，万一 the DPP *win* both the presidency and legislature, China *will certainly be unhappy*. But Ms Tsai *is* a pragmatist 实用主义者；务实. She *would probably use* a new mandate(n.)(`=the authority to do sth, given to a government or other organization by the people who vote for it in an election （政府或组织等经选举而获得的）授权; / 委托书；授权令; / the period of time for which a government is given power （政府的）任期`) *to keep* Taiwan on the same course, *rebuffing*(`=an unkind refusal of a friendly offer, request or suggestion 粗暴回绝；生硬的拒绝`) China’s political demands while *trying not to pick quarrels*(`=*pick a fight/quarrel (with sb)* : to deliberately start a fight or an argument with sb 找碴儿；找麻烦；挑衅`) that *could risk* a military conflict.

American diplomats 外交官 *would welcome* this. They *were rattled*(`=to make sb nervous or frightened 使紧张；使恐惧;/（使）发出咔嗒咔嗒的声音`) *by* the more confrontational(`=tending to deal with people in an aggressive way that is likely to cause arguments, rather than discussing things with them 对抗性的；挑起冲突的`) approach of the DPP’s Chen Shui-bian, Taiwan’s president from 2000 to 2008, who *enraged*(`=to make sb very angry 使异常愤怒；激怒；触怒`) China 方式状 with his efforts *to assert*(`=to state clearly and firmly that sth is true 明确肯定；断言`) Taiwan’s separate identity.

如果民进党同时赢得总统和立法机关，中国肯定会不高兴。但蔡英文是一位实用主义者。她可能会利用新的任期授权，让台湾保持同样的路线，拒绝中国的政治要求，同时努力避免引发可能引发军事冲突的挑衅。美国外交官对此表示欢迎。他们对民进党的陈水扁(2000年至2008年担任台湾总统)采取的更具对抗性的方式感到不安。陈水扁试图维护台湾的独立身份，激怒了中国大陆。

But four more years of Ms Tsai *would not guarantee peace*. President Donald Trump *appears to have little interest in* sparring(v.)(`=to argue with sb, usually in a friendly way （多指在友好气氛中）辩论，争论;/ (练习时或试探对手反应时的) 轻拳出击；虚晃一拳`) with China over Taiwan, but some of his appointees(`=a person who has been chosen for a job or position of responsibility 被任命者；被委任者`), *egged on*(`=*egg sb on* : to encourage sb to do sth, especially sth that they should not do 鼓动；怂恿；煽动`) by many members of Congress, *are keen to strengthen* America’s unofficial ties with the island.

In August the State Department *approved* the sale of 66 F-16 fighter jets to Taiwan. China’s patience *may one day wear thin*(`=*wear thin* : to begin to become weaker or less acceptable 开始变弱；变得不受欢迎；变得兴趣索然`).

但是蔡英文再多执政四年, 也并不能保证和平。唐纳德·特朗普(Donald Trump)总统似乎对在台湾问题上与中国发生争执兴趣不大，但他任命的一些人在许多国会议员的怂恿下，热衷于加强美国与台湾的非官方关系。今年8月，美国国务院批准向台湾出售66架F-16战斗机。中国的耐心总有一天可能会消失。

---

== 02. Taiwan’s China-sceptic president, Tsai Ing-wen, may win again 纯净版

But the threat from Beijing is not going away



Jan 2nd 2020 | KAOHSIUNG AND TAIPEI

ELECTION RALLIES in Taiwan often *feel like* festivals with a dash of politics *thrown in*. At a recent one in Taiwan’s capital, Taipei, thousands of people *watched* a fireworks display, then *heard* a blind blues singer. Eventually the show’s political star *took to the stage*: Enoch Wu, a young would-be legislator for the ruling Democratic Progressive Party (DPP). China’s leader, Xi Jinping, “*is watching to see* if we are sure(a.) *to defend* our homeland,” he *told* the crowd. “We are,” his fans *roared back*.

One question *always looms largest* in Taiwan’s elections for president and parliament, *held simultaneously* every four years, this time on January 11th: *how to handle* the island’s twitchy relations with an ever more powerful China. Many of Taiwan’s nearly 24m people *have been warily watching* the unrest in Hong Kong. Twice in 2019 Mr Xi *declared that* Taiwan *should reunify with* the mainland under a “one country, two systems” formula, as Hong Kong did. `主` China’s ability *to force* such a solution on Taiwan `系` *is increasingly plain*. On December 26th China *sent* its newly commissioned aircraft-carrier, the Shandong, *through* the Taiwan Strait for the second time in as many months.

[Since 2000] Taiwanese voters’ main choice for president *has been either* a candidate who *leans toward* independence from China, thereby *incurring* China’s wrath, *or* one who *wants* closer ties despite the risk of ensnarement by the mainland’s Communists. [So far] the China-sceptic, pro-independence DPP *has won* three times and the China-embracing Kuomintang (KMT) twice. The legislature, however, *has usually been controlled by* China-friendly types -- until 2016, when the DPP *secured both* the presidency -- with Tsai Ing-wen *becoming* Taiwan’s first female leader -- *and* a majority in the Legislative Yuan, as the parliament is known.

Ms Tsai’s support for Hong Kong’s protesters *seems to have boosted* her chance of winning again. `主` American *talk of* *“decoupling”(v.) from* China’s economy, particularly in technology, `谓` *has helped* her, too. Taiwan’s tech giants *do not want to risk* losing(v.) access to Western markets *by siding with* China. Some *are moving out of China* and *are investing more in* South-East Asia and *in* Taiwan itself. *Less focused on* the mainland, some Taiwanese businessmen *are becoming keener on* the DPP.

Ms Tsai’s main opponent *is* the KMT’s Han Kuo-yu, the mayor of the southern port city of Kaohsiung, which *is* usually a DPP stronghold. His chances *dipped* [in November] when another China-friendly politician, James Soong of the People First Party, *entered* the fray. Mr Soong *may peel away* some of Mr Han’s supporters.

The president *hammers home* her China point. [In a televised presidential debate] she *read out* a letter from a young Hong Konger. “I *ask* Taiwan’s people *not believe* the Chinese Communists,” the author said. “*Don’t fall into* China’s money trap.” Ms Tsai also *boasts that* the economy under the DPP *has grown*, *following* a recession under the previous KMT government.

Some voters *are not persuaded*. Salaries, they *grumble*, *have been virtually flat* for almost two decades. The average monthly full-time wage *is* NT$49,170 ($1,635), *including* bonuses, *far lower than* in other rich countries in the region, such as Singapore where it is about S$4,560 ($3,390). Poorer and older people *tend to back* Mr Han, who *harks back to* the boom years of the 1970s and 1980s under the KMT. (He *avoids reminding them that* Taiwan *was* then a one-party dictatorship).

Mr Han *is unlikely to win* the presidency, but there is more of a question-mark over the legislature. Mr Wu, the DPP candidate who *tried to whip up* support(n.) [with fireworks and blues], *may have excited* his backers [with *talk of* a Chinese threat]. But that is because his KMT rival *is* Wayne Chiang -- a great-grandson of Chiang Kai-shek /and grandson of Chiang Ching-kuo, rulers of Taiwan during nearly four decades of martial law. Though the Chiangs *hated* the Communists for *ousting* them *from* China, DPP loyalists *consider* them China incarnate: mainland-born autocrats who *tried to crush* Taiwanese culture. All the same, `主` Wayne Chiang, an incumbent MP with a local following, `系` *will be hard to beat*.

If the DPP *loses control of* the 113-strong parliament, where it now *has* 68 seats, Ms Tsai *will have a hard time ruling*. The KMT and its allies *could block bills* disliked by China, such as a law *passed* on December 31st *making it illegal* to accept(v.) Chinese funds for political activities. The KMT *says* it *supports measures* to strengthen national security, but *condemns* the recent bill *as* too sweeping.

China *has denounced it*, too, but *has largely refrained from sabre-rattling* during the campaign *to avoid playing into Ms Tsai’s hands*. After she *was elected*, China *bolstered* its military posturing, for instance *with* bomber-jets *flying around* the island. It also *persuaded* seven of Taiwan’s diplomatic allies *to switch to* China, *reducing* the number *to* 15. But [since the middle of 2019] the jets *have stopped* their exercises. The aircraft-carrier’s transits *raised eyebrows* in Taiwan, but Andrew Yang, a former deputy defence minister for the KMT, *says* they were routine tests.

*Should* the DPP *win* both the presidency and legislature, China *will certainly be unhappy*. But Ms Tsai *is* a pragmatist. She *would probably use* a new mandate *to keep Taiwan on the same course*, *rebuffing* China’s political demands while *trying not to pick quarrels* that *could risk* a military conflict. American diplomats *would welcome* this. They *were rattled by* the more confrontational approach of the DPP’s Chen Shui-bian, Taiwan’s president from 2000 to 2008, who *enraged* China [with his efforts *to assert* Taiwan’s separate identity].

But four more years of Ms Tsai *would not guarantee peace*. President Donald Trump *appears to have little interest in* sparring(v.) with China over Taiwan, but some of his appointees, *egged on by* many members of Congress, *are keen*(a.) to strengthen(v.) America’s unofficial ties with the island. In August the State Department *approved* the sale of 66 F-16 fighter jets to Taiwan. China’s patience *may one day wear thin*.

---


== 03. The subtle ways that discrimination(n.) 区别对待；歧视；偏袒 works(v.)

In the workplace, it’s still a man’s world

歧视起作用的微妙方式
在工作场所，这仍然是一个男人的世界 +

Apr 20th 2019

PREGNANT WOMEN *have* limited mobility(`=the ability to move or travel around easily 移动的能力；易于行走的能力`).

That *is* obvious to anyone who *has had a baby*, but *didn’t occur to*(`=*OCCUR TO SB* : (of an idea or a thought 观念或想法) to come into your mind 被想到；出现在头脑中`) the founders of Google when they *designed* their car park.

When Sheryl Sandberg, then head(n.) of online sales, *became pregnant*(a.)怀孕的；妊娠的 in 2004, she *made a simple request*: parking spaces 停车位 for expectant women *as* close to the building entrance *as possible*.

孕妇行动不便。这对任何有过孩子的人来说都是显而易见的，但谷歌的创始人在设计他们的停车场时, 却没有想到这一点。2004年，当时任在线销售主管的谢丽尔•桑德伯格(Sheryl Sandberg)怀孕时，她提出了一个简单的要求: 在尽可能靠近大楼入口的地方, 为孕妇提供停车位。

That is just one example of how many aspects of the workplace *lack* the female perspective(`=a particular attitude towards sth; a way of thinking about sth 态度；观点；思考方法`).

In her brilliant(`=very good; excellent 很好的；杰出的; /very successful 很成功的`) book “Invisible Women: *Exposing* Data Bias 偏见；偏心；偏向 *In* A World (Designed For Men)”, Caroline Criado Perez *shows* how widespread these subtle biases *can be*.

这只是在职场的很多方面中, 缺失从女性视角来考虑问题的一个例子。卡罗琳·克里亚多·佩雷斯(Caroline Criado Perez)在她精彩的著作“看不见的女人：揭露为男性设计的世界中的数据偏见”中，展示了这些微妙的偏见, 会是多么普遍。

It *starts* at the recruitment 招聘 stage. Women *are put off*(`=*PUT SB OFF* : to cancel a meeting or an arrangement that you have made with sb 取消，撤销（与某人的会晤或安排）;/停车卸（客）；让…下车; /*PUT SB OFF STH/SB* : to make sb lose interest in or enthusiasm for sth/sb 使失去兴趣（或热情）`) *from* applying for jobs that *use words* in their adverts such as “aggressive” or “ambitious”.

When one company *changed* its ad *to focus on* qualities such as enthusiasm and innovation, and *used* a photo of a woman *rather than* a man, the proportion of female applicants *rose from 5% to 40%*.

这种偏见, 从招聘阶段开始就显现出来。当招聘广告中使用了“有进取心”或“雄心勃勃”等字眼时, 女性去申请这些工作, 却会被拒之门外。但当一家公司把广告的重点, 放在热情和创新等品质上，并且使用女性而非男性的照片作为画面时，女性申请者的比例就从5%上升到了40%。

Once you *have a job*, you must *get to the office*. Because they often *care for* children or elderly relatives, women *are* likelier 更可能的 *to make* multiple journeys 多次往返.

`主` Those who *use* public transport `谓` *often need* radial  放射状的；辐射状的 routes whereas （用以比较或对比两个事实）然而，但是，尽管 most systems *favour* commuters 通勤者;（远距离）上下班往返的人 *heading(v.)朝（某方向）行进 from* the suburb *to* the centre of town. This *means* female journeys(`=an act of travelling from one place to another, especially when they are far apart （尤指长途）旅行，行程`) *can be* much longer *than* male ones, making *it* difficult for them *to get to work* on time.

一旦你有了工作，你就必须去办公室上班。由于女性经常需要照顾孩子或年长的亲属，所以她们更可能进行多次往返于城市中。因此, 那些乘坐公共交通的女性, 常常需要走辐射状的路线，然而, 大多数交通工具的行驶线路, 却是为从郊区到市中心来的通勤者设计的。这意味着女性花在路上的行程, 可能要比男性要长得多，这就使得她们很难上班不迟到。

Women *experience* more work-related stress *than* men, *according to* research(n.) by _Britain’s Health and Safety Executive （政府的）行政部门_, and *face* a particular problem with long working hours.

But a study *found that* unencumbered(a.)(`=not having or carrying anything heavy or anything that makes you go more slowly 无负担的；没有阻碍的；不受妨碍的`) people of both sexes (those with few or no caring(`=care : 照料；护理; 关注；在意；担忧`) responsibilities) *could cope equally well with* a 48-hour week.

The stress *occurred*(`=to happen 发生；出现`) because women *struggled to combine* their caring responsibilities *with* work, a problem *faced by* a smaller number of men.

英国健康与安全执行局的一项研究表明，女性比男性承受着更多的工作压力，尤其面临着工作时间过长这个问题。一项研究发现，无论是男是女, 如果他们没有上老下小需要照料的话, 他们同样都可以应付起每周48小时的工作。因此, 女性身上有压力的原因在于，她们需要同时承担起照顾家人, 和处理工作上的问题, 这两件事. 这使她们很难, 而很少有男性会面临这个问题。

Those responsibilities *may also mean that* women *find* it more difficult *to take part in* after-work 下班后;工作之余的 bonding(n.)(`=the process of forming a special relationship with sb or with a group of people 人与人之间的关系（或联结）`) activities *like* 例如；譬如；比方 dinners, Ms Criado Perez *argues*.

Many companies *allow* workers *to put the cost of* food and drink at such events *on expenses* （由雇主报销的）费用，开支，花销，业务费, but *not* the cost of a babysitter 临时保姆；代人临时照看小孩的人.

That is a problem for single parents, and women *comprise*(`= to have sb/sth as parts or members 包括；包含；由…组成; /to be the parts or members that form sth 是（某事物的）组成部分；组成；构成`) 80% of that category(`=a group of people or things with particular features in common （人或事物的）类别，种类`) in America /and 90% in Britain.

克里亚多•佩雷斯认为，这些对家庭成员的照顾责任, 可能还意味着，女性发现, 她们很难参加下班后的聚餐等增进感情的活动。许多公司允许员工们报销食品和饮料的费用，但却不包括他们在外聚餐时, 家里老小无人照顾, 需要请保姆的费用。对单亲父母来说, 这是个问题. 在美国，这类单亲父母, 女性占80%，在英国则占90%。

When their performance *is reviewed*(`=to write a report of a book, play, film/movie, etc. in which you give your opinion of it 写（关于书籍、戏剧、电影等的）评论；评介`), Ms Criado Perez *argues that* women *are criticised*(`=criticize : *~ sb/sth (for sth)* : to say that you disapprove of sb/sth; to say what you do not like or think is wrong about sb/sth 批评；批判；挑剔；指责`) *for* being bossy(a.)(`=always telling people what to do 好指挥人的；专横的`), abrasive(a.)(`=rude and unkind; acting in a way that may hurt other people's feelings 生硬粗暴的；粗鲁的；伤人感情的;/有研磨作用的；研磨的`) or strident(a.)(`=aggressive and determined 强硬的；咄咄逼人的`), whereas （用以比较或对比两个事实）然而，但是，尽管 men *are encouraged to be* more aggressive.

But if women *are warm and friendly*, they *get criticised for* being insufficiently 不够地；不能胜任地 professional.

克里亚多·佩雷斯女士认为，当评估他们的表现时，女性会因为专横、粗暴或咄咄逼人的, 而受到批评，而男性则会被鼓励去变得更具攻击性。但是，当女性反过来去变得热情友好，她们又会被批评为不够专业 (里外都有话说, 欲加之罪何患无辞)。


Women’s physical health, too, *may be affected by* male-dominated design. Their bodies *absorb* chemicals more quickly than men’s do.

`主` The long-term effects of *inhaled*(`=inhale : to take air, smoke, gas, etc. into your lungs as you breathe 吸入；吸气`) particles [on (mostly male) miners] `谓` *have been studied extensively*(ad.)(`=covering a large area; great in amount 广阔的；广大的；大量的`); `主` those of cleaning products (on (mostly female) cleaners) `谓` *have not*.

女性的身体健康, 也受到只为男性而设计的工具的影响. 女性的身体, 在吸收化学物质时, 也比男性更快. 人体吸收进颗粒物质时, 对身体健康的长期影响, 已经被广泛研究(主要是针对男性, 尤其是矿工), 但是清洁产品对女性身体健康有何种影响, 这种研究还没有过.


In construction and engineering, tools and safety jackets *are designed for* male hands and bodies, *not* female ones.

Bulletproof(a.)(`=that can stop bullets from passing through it 防弹的`) and stabproof 防刺,耐穿刺 jackets *are also designed for* men /and thus *do not fit* women comfortably; a British police officer *removed* her jacket *so* she *could use* a hydraulic(`= moved through pipes, etc. under pressure （通过水管等）液压的，水力的; 液压驱动的`) ram(`=a part in a machine that is used for hitting sth very hard or for lifting or moving things 夯锤；撞击装置;/公羊`) 挤压杆 *to enter* a flat, *only to be stabbed and killed*.

建筑和工程领域的工具, 还有安全夹克, 是专门针对男性的手和身体而设计的, 而非针对女性来设计. 同样, 防弹和防刺夹克, 也是为男性而设计的，它们穿在女性身上并不舒服. 一名英国的女警在出警时, 为了用挤压杆来进入一栋公寓, 不得不脱掉她的安全夹克, 结果导致她进入后, 被罪犯刺死.

====
- pressure ram 挤压杆
====


Many men *do not realise* {there is a problem}. `主` Those who *believe* {they are objective [when *recruiting*]} `系` *are* nevertheless(`=despite sth that you have just mentioned 尽管如此；不过；然而`) *more likely to hire* another man *than* a woman (with identical(`=similar in every detail 完全同样的；相同的; /the same 同一的`) qualifications), as a paper from 2007 *showed*.

很多男人没有意识到这是个问题。然而，2007年的一篇论文显示，那些认为自己在招聘时客观的人, 更有可能聘用另一名男性，而不是拥有相同资历的女性。

A similar issue *is* apparent with race, *as* Jennifer Eberhardt, a professor at Stanford University, *describes* in her book “Biased: The New Science of Race and Inequality”.

An American study *showed that* candidates （竞选或求职的）候选人，申请人 with black-sounding names *get* fewer callbacks *than* those with traditional European names.

Even highly qualified African-Americans *received* fewer calls for interview *than* whites with lesser qualifications.

White people with a criminal record *received* *as many* callbacks from employers *as* black people who *had never committed* an offence.

And this *was* true [*whether or not* the company *described itself as* an “equal opportunity employer”].

正如斯坦福大学(Stanford University)教授珍妮弗•埃伯哈特(Jennifer Eberhardt)在其著作《偏见:种族与不平等的新科学》(:The New Science of race and Inequality)中所描述的那样，在种族问题上, 显然也存在类似的问题。

美国的一项研究表明，名字听起来像黑人的候选人, 比名字听起来像欧洲人的候选人, 得到的应聘回复要少。即使是具有高资历的非洲裔美国人, 接到的面试电话, 也比资历较低的白人要少。有犯罪记录的白人, 和从未犯罪的黑人, 接到的雇主回电话一样多。不管公司是否将自己描述为“机会均等的雇主”，这种偏见都是事实。

*It* is natural [if you *have succeeded in* work] *to assume* {this *was down to* 可归因于; 因为 your own merits(`=the quality of being good and of deserving praise, reward or admiration 优点；美德；价值`)}.

But the existence of hidden biases *shows that* the playing field 运动场；操场 *is not* level(a.)(`=having a flat surface that does not slope 平的；平坦的`).

*As* both authors *argue*, `主` *preventing* discrimination `谓` *depends not on* white men *discovering* their inner(`=private and secret; not expressed or shown to other people 内心的；未表达出来的；隐藏的`) liberal 理解且尊重他人意见的人；宽容的人；开明的人;支持（社会、政治或宗教）变革的人 *but on* decisions *being taken by* those with broader perspectives(`=a particular attitude towards sth; a way of thinking about sth 态度；观点；思考方法`).

If every executive *carries* a hammer, it *might not occur to them* that some jobs *need* a screwdriver 螺丝刀；改锥.

如果你在工作中取得了成功，你自然会认为这归因于你自己的优点。但隐性偏见的存在表明，竞争环境并不公平。正如两位作者都认为的那样，防止歧视, 并不取决于白人男性自认为是否开明，而是取决于那些能换个角度看问题, 即能从女性的角度来看待工作环境的人, 所做出的决定。如果每个高管都带着锤子，他们很可能不会想到有些工作需要螺丝刀。

---

== 03. The subtle ways that discrimination works 纯净版

In the workplace, it’s still a man’s world


Apr 20th 2019

PREGNANT WOMEN *have* limited mobility. That is obvious to anyone who has had a baby, but *didn’t occur to* the founders of Google when they designed their car park. When Sheryl Sandberg, then head of online sales, *became pregnant* in 2004, she made a simple request: parking spaces for expectant women *as* close to the building entrance *as possible*.

That is just one example of how many aspects of the workplace *lack* the female perspective. In her brilliant book “Invisible Women: *Exposing* Data Bias [In A World Designed For Men]”, Caroline Criado Perez *shows* how widespread these subtle biases can be.

It *starts* at the recruitment stage. Women *are put off from* applying for jobs that use(v.) words in their adverts such as “aggressive” or “ambitious”. When one company *changed* its ad *to focus on* qualities such as enthusiasm and innovation, and *used* a photo of a woman rather than a man, the proportion of female applicants *rose from 5% to 40%*.

Once you have a job, you must get to the office. Because they often *care for* children or elderly relatives, women are likelier to make multiple journeys. Those who *use* public transport *often need* radial routes *whereas* most systems *favour* commuters *heading from* the suburb *to* the centre of town. This *means* female journeys *can be* much longer *than* male ones, *making it difficult* for them *to get to work* on time.

Women *experience* more work-related stress *than* men, according to research by Britain’s Health and Safety Executive, and *face* a particular problem with long working hours. But a study *found that* `主` unencumbered people of both sexes (those with few or no caring responsibilities) `谓` *could cope [equally well] with* a 48-hour week. The stress *occurred* because women *struggled to combine* their caring responsibilities *with* work, a problem *faced by* a smaller number of men.

Those responsibilities *may also mean that* women *find* it more difficult *to take part in* after-work bonding activities like dinners, Ms Criado Perez *argues*. Many companies *allow* workers *to put the cost of* food and drink at such events *on expenses*, but *not* the cost of a babysitter. That is a problem for single parents, and women *comprise* 80% of that category in America and 90% in Britain.

When their performance *is reviewed*, Ms Criado Perez *argues that* women *are criticised for* being bossy, abrasive or strident, whereas men *are encouraged to be* more aggressive. But if women are warm and friendly, they *get criticised for* being insufficiently professional.

Women’s physical health, too, *may be affected by* male-dominated design. Their bodies *absorb* chemicals more quickly than men’s do. `主` The long-term effects of *inhaled* particles on (mostly male) miners `谓` *have been studied extensively*; `主` those of cleaning products on (mostly female) cleaners `谓` *have not*. In construction and engineering, tools and safety jackets *are designed for* male hands and bodies, *not* female ones. Bulletproof and stabproof jackets *are also designed for* men /and thus *do not fit* women *comfortably*; a British police officer *removed* her jacket so she *could use* a hydraulic ram *to enter* a flat, only *to be stabbed and killed*.

Many men *do not realise* there is a problem. `主` Those who *believe* {they are objective when *recruiting*} `谓` *are nevertheless more likely to hire* another man *than* a woman with identical qualifications, *as* a paper from 2007 *showed*.

A similar issue *is apparent* with race, *as* Jennifer Eberhardt, a professor at Stanford University, *describes* in her book “Biased: The New Science of Race and Inequality”. An American study *showed that* {candidates with black-sounding names *get* fewer callbacks *than* those with traditional European names}. Even highly qualified African-Americans *received* fewer calls for interview *than* whites with lesser qualifications. `主` White people with a criminal record `谓` *received* *as many* callbacks from employers *as* black people who *had never committed* an offence. And this *was* true [*whether or not* the company *described itself as* an “equal opportunity employer”].

It is natural [if you *have succeeded in* work] *to assume* {this *was down to* your own merits}. But the existence of hidden biases *shows that* {the playing field *is not* level}. *As* both authors *argue*, `主` *preventing* discrimination `谓` *depends not on* white men (*discovering* their inner liberal) *but on* decisions (*being taken by* those with broader perspectives). If every executive *carries* a hammer, it *might not occur to them* that {some jobs *need* a screwdriver}.

---

== 熟听单词


|===
|Header 1 |Header 2

|rally|公众集会，群众大会（尤指支持某信念或政党的）
|simultaneously |同时地
|twitchy|神经紧张的；焦急的；焦虑不安的; /抽搐的；抽动的；痉挛的
|warily |警惕地；谨慎地；留心地
|unrest|n. 政治动荡；动乱；骚动
|formula|a particular method of doing or achieving sth 方案；方法
|wrath|n. extreme anger 盛怒；震怒；怒火
|ensnarement|n. 诱捕，诱入圈套
|sceptic|惯持怀疑态度的人；怀疑论者
|presidency|主席的职位（或任期等）；总统的职位（或任期等）
|decouple|v. decouple sth (from sth) : ( formal ) to end the connection or relationship between two things （使两事物）分离，隔断
|keener|a. *~ on sb/sth/on doing sth* ( BrE informal ) : liking sb/sth very much; very interested in sb/sth 喜爱；（对…）着迷，有兴趣; // *~ (to do sth) /~ (that…​) /~ (on doing sth)* : ( especially BrE ) wanting to do sth or wanting sth to happen very much 渴望；热切；热衷于
|fray|n. 打斗，竞争，争辩（尤指激烈或视为检验能力的）=> 政治角逐 /加入争辩
|Communist|
|recession |经济衰退；经济萎缩
|bonus|
|hark|*HARK BACK (TO STH)* : 回忆起，重提（过去的事）;/ to remind you of, or to be like, sth in the past 使想起；和（过去的事物）相似
|presidency|
|martial|
|oust|*oust sb (from sth/as sth)* : 剥夺；罢免；革职
|loyalist|（尤指在变动时期对统治者、政府或政党）忠诚的人
|incarnate|a.  (usually after nouns 通常在名词之后) ( formal ) in human form  +
人体化的；化身的；拟人化的  +
=> 魔鬼的化身  devil incarnate
|autocrat |a ruler who has complete power  +
独裁者；专制统治者；专制君主
|incumbent|在职者；现任者
|refrain|
|sabre|（弯刃）军刀，马刀
|rattle |（使）发出咔嗒咔嗒的声音
|bolster| bolster sth (up) 改善；加强
|posturing|n. 做作的举止；忸怩作态；虚伪表现
|transit |n. 通过；经过；通行；过境；中转
|deputy|副手；副职；代理;（某些国家的）议员
|pragmatist|实用主义者；务实
|mandate|n. （政府或组织等经选举而获得的）授权; / 委托书；授权令
|rebuff | v.n. 粗暴回绝；生硬的拒绝
|diplomat |外交官
|confrontational|对抗性的；挑起冲突的
|enrage|使异常愤怒；激怒；触怒
|assert|明确肯定；断言
|guarantee|
|spar|（多指在友好气氛中）辩论，争论;/ (练习时或试探对手反应时的) 轻拳出击；虚晃一拳
|appointee|被任命者；被委任者
|---|---


|founder|
|expectant|
|recruitment|招聘
|journey|（尤指长途）旅行，行程
|radial |放射状的；辐射状的
|whereas |（用以比较或对比两个事实）然而，但是，尽管
|commuter |通勤者;（远距离）上下班往返的人
|Executive |（政府的）行政部门
|unencumbered|not having or carrying anything heavy or anything that makes you go more slowly  无负担的；没有阻碍的；不受妨碍的
|bonding|人与人之间的关系（或联结）
|babysitter |临时保姆；代人临时照看小孩的人
|comprise|包括；包含；由…组成
|category| （人或事物的）类别，种类
|criticize| 批评；批判；挑剔；指责
|boss|y好指挥人的；专横的
|abrasive|生硬粗暴的；粗鲁的；伤人感情的;/有研磨作用的；研磨的
|strident|强硬的；咄咄逼人的
|insufficiently|不够地；不能胜任地
|inhale|吸入；吸气
|extensively|广阔的；广大的；大量的
|bulletproof|防弹的
|stabproof|防刺,耐穿刺
|hydraulic| （通过水管等）液压的，水力的; 液压驱动的
|nevertheless|尽管如此；不过；然而
|identical|完全同样的；相同的
|merit|优点；美德；价值
|inner|内心的；未表达出来的；隐藏的
|liberal| 理解且尊重他人意见的人；宽容的人；开明的人;支持（社会、政治或宗教）变革的人
|perspective|态度；观点；思考方法
|screwdriver|螺丝刀；改锥

|===

---




