
= 生活医学常识
:toc: left
:toclevels: 3
:sectnums:

'''

== 本质认识


=== ☆ 一切医疗只起"支持"的作用, 核心治愈靠人体自身的修复.

.一切医疗, 都是用来支持"人体的自我修复"的. 人体的自我修复, 主要靠细胞分裂。
真正治好病的，是病人自己。所有的医疗行为，只是起到支持的作用。*医疗的本质是支持生命自我修复。* 在疾病面前，*尤其是大病，医疗的支持作用是必不可少的。因为这个时候，人体的自我修复垮了。医疗的支持，就是给自我修复赢得时间、创造条件，等待自我修复最终发挥作用、战胜疾病。* +
首先是人体的自我修复，然后才是医学的支持。*人体的自我修复是核心，是关键。*

- ICU，也就是重症医学科，是疾病最重、距离死亡最近的地方。里面几乎所有的救命手段都是支持。 +
-> 呼吸机 : 是支持肺，让肺休息，等待自愈. +
-> 床旁的血液净化 : 是支持肾，替代肾脏的功能，等待自愈. +
-> ECMO 魔肺 : 是对心脏和肺，提供最高级别的支持. +
*所有这些顶级的医疗设备，都是为了先把命保住，给自我修复赢得时间、创造条件，然后等待"人体的自我修复"发挥作用。*

- 得了肺炎，先用抗生素杀死大部分细菌，但是总有耐药的，没被杀死的细菌。怎么办？这个时候，人体的白细胞发挥作用 (即自我修复)，消灭剩下的细菌，让肺炎痊愈。


.如果人体失去了自我修复能力, 那么前面的任何医疗手段, 就都没有用了 (皮之不存,毛将焉附?).

- "秋水仙碱"本来是一种治疗痛风的药，小剂量可以治病，但是超过剂量很容易中毒，甚至死亡。这种毒根本没有解药。*服用致死量的秋水仙碱，会阻断细胞的分裂，让细胞在分裂中期死亡。细胞不再分裂了，不再产生新的细胞了，这就剥夺了疾病治愈最基本的环节——自我修复。*

- 同样是肺炎，但是白血病病人, 或者艾滋病病人, 就没有这么幸运了，会非常难治. *因为这类病人的白细胞吞噬功能差，自我修复能力低下.* 因此，再强大的抗生素效果也不好。

- 如果"癌症细胞"可以逃过人体免疫细胞的监视，那么说明这个时候"自我修复"垮了。如果不能够恢复这种自我修复，病人再怎么手术、放疗，效果都不好。

'''

=== ☆ 医学的目的 : 是先保证让人活下来, 然后才有其他治疗可能.

医学存在的目的, 是先保证人活着. 先活下来，然后才有其他可能。

- ICU 重症医学科 : 工作就是把所有最危急的病人的生命体征, 先稳定下来，再送回其他科室进行后续的原发病的治疗。

'''

=== ★ 不怕难题有多难，就怕没有解决方法.

学医之后我体会到 : 不怕难题有多难，怕的是没有办法解决。只要有办法，我总会一步一步地搞定它。

'''

=== 人体有"代偿机制", 这就导致 -> 疾病不是突然发生的，而是突然发现的

很多病没有症状，一旦发现就是中晚期. 因为所有严重的慢性疾病都不是突然发生的，而是突然被发现的。 +
-> 结肠癌，从一个良性的腺瘤, 逐步演变成恶性肿瘤，通常需要15年。 +
-> 女性持续的高危型HPV感染, 到发生"宫颈癌"，一般需要大约十几年（高危型，就是最容易引起宫颈癌的病毒类型）。 +
-> 中国人死亡原因第一的心脑血管病，*也是从青壮年开始，血管上就开始出现斑块，经过20-30年的进展，血管逐步狭窄。当狭窄超过一定范围，才会出现"心脏病"或"脑血管病"的症状。*


.*之所以人体能够在疾病状态下，十几年甚至几十年都不出现明显的症状，是因为人体有一种"代偿机制"。 所有的慢性病，人体都会启动代偿。*

*代偿, 即是代替、补偿。身体某些组织或者器官持续受损，已经没办法修复原样了，人体就调动没有受损的部分，加快补充或者代替受损的部分完成工作。* 代偿, 是慢病进展过程中, 人体的妥协. +

- 幽门螺旋杆菌会持续攻击胃的细胞，引起胃炎，细胞就会死亡。这个时候，人体就会启动代偿机制，让深层的干细胞加速分裂，赶紧补充死亡的细胞。这样就防止发生严重的穿孔、出血。
- 比如高血压。血压持续增高，心脏射血的负担就会增加。所以，心肌就会变得肥厚，射血才更有劲。这是代偿。
- 甚至冠心病病人，血管狭窄了、堵了，这根堵了的血管周围的小血管, 就会变粗、变长，甚至长出新生的血管，替代这根堵了的血管给心肌供血，防止发生致命性的心肌梗死。这也是代偿。

所以，人体的代偿, 能够让器官在持续损伤的状态下，基本上能够满足功能，也就是凑合着用，所以才不会出现明显的症状。*只有到了疾病晚期，代偿不动或者超过极限了，症状才会出现。* 代偿的最终目的, 是保证器官能基本运行。

*这种机制, 让我们在没办法去除持续损伤因素的情况下，先妥协着活下来。这本身是有利的一面，但也有另一面，即同时也掩盖了病情。*





'''


=== 医学的开拓, 面临不确定性. 这就对开拓者造成, 其名望, 要么上天堂, 要么下地狱的结果.

医学(包括医学开拓) 面临的一个现实就是"不确定"。每个病人都是不同的个体，治疗的反应因人而异，结果也不同。

.案例
====
几十年前，心脏外科就面临着一个难题，就是没办法把心脏里的血引出来，这样就不可能打开心脏做手术。 +
美国医生 Lillehei 不能眼睁睁看着这些孩子死, 他设计了一种大胆的手术方案 ...。Lillehei 不做，没人会说什么。但是一旦失败，父子俩人的命都没了，而且李拉海的职业生涯也会到此结束。
====



'''

== 疾病_癌症

=== 一级致癌物

*一级致癌物指的是 : 有明确证据表明可以致癌的物质*，比如雾霾、烟草、槟榔、黄曲霉素等等。


=== 胃癌

很多胃癌的病人, 早期没有明显症状。"幽门螺旋杆菌"感染, 可以导致胃癌. 世界卫生组织把这种细菌列为一级致癌物。







=== CAR-T治疗 (免疫疗法之一)

CAR-T的原理就是把病人杀肿瘤的T细胞抽出来，在体外进行修饰，加上一个专门寻找癌细胞的“GPS”，然后，把这些加了“导航”的细胞扩增，再回输到病人体内，让它们攻击癌症细胞。 +
CAR-T治疗是由一系列微观研究促成的。包括"癌症基因"的研究、"免疫细胞"的研究、"细胞表面受体"的研究，以及"免疫细胞如何识别癌细胞". 所以, CAR-T治疗是百年来无数微观研究的综合成果。



'''

== 疾病

=== 心衰

慢性心衰, 也就是心脏功能逐渐衰竭. 到最后，病人甚至连平躺都成了奢望。想要治愈只能心脏移植。

'''

=== 骨折

骨折之后，骨折的地方会长出骨痂 jiā，逐渐让断裂的部分愈合，靠的也是细胞分裂。

'''
















