= 0111
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to another sports lesson with us here 
at EnglishPod! My name is Marco. +
E: And I'm Erica. +
M: And today we're gonna be talking about a very interesting and very difficult game to play 
and it's golf. +
E: So, we've got some golf vocabulary for you in this lesson, um, and I think we… we better 
actually look at a few vocabulary words in “vocabulary preview” before we start with the
dialogue. +
Voice: Vocabulary preview. +
M: On vocabulary preview today we have three words and the first one is aficionado. +
E: Aficionado. +
M: An aficionado. +
E: A golf aficionado. +
M: Alright, so, this basically is a very fancy word of… is a very fancy way of saying “a fan”. +
E: Yes, someone who likes something a lot. +
M: Okay, so, you are an aficionado – I like golf. +
E: Yeah, you can also be an a… a wine aficionado. +
M: Okay, so, it's kind of like a hobby. +
E: Yeah, you know a lot about it and you like it. +
M: Uhu, and now our second word is not anywhere in the dialogue. +
E: No, but we're gonna use it when we explain some of these words, so you need to know 
it. +
M: Okay, the word is club. +
E: Club. +
M: A golf club. +
E: Okay, so, a golf club is the tool you use to hit the golf ball. +
M: Right, so, it's a long tube, basically, that… looks like a J, kind of. +
E: Yeah, so, and you hit the ball with it. +
M: Uhu, so, that's a golf club. +
E: Uhu. +
M: And now our third word is golf course. +
E: Golf course. +
M: A golf course. +
E: A course. +
M: So, this is the area where you play golf. +
E: Yeah, it's… like the golf field. +
M: Uh, exactly. +
E: Yep. +
M: So, it's a very big green area where you play golf. So, those are the three words we 
have for vocabulary preview, so now we could listen to our dialogue for the first time as we
listen to our sports announcers Rick Fields and Bob Copeland and see what happens on this
occasion. +
A: Good morning golf aficionados! My name is Rick 
Fields, and you guessed it, I am here with my
main man, Bob Copeland. +
B: Thank you, Rick! As you can see, ladies and gen- 
tleman, we are here in beautiful Pebble Beach
where the top golfers in the world are trying to
win the grand prize of one million dollars! +
A: Whoa, that’s a lot of cash! Let’s go to the course 
and see how Tiger Woods is doing. +
B: All right, were’re here at the eighth hole. It’s a par 
four, and has some very difficult hazards which
many golfers find difficult to avoid. Although, I did
see Jack Nicklaus hit a hole in one on this very
same hole! +
A: Tiger Woods is about to tee off, and let’s see if 
he has the same luck as Jack. Tiger is asking
his caddie for his driver and, he seems to be very
nervous. +
B: Oh no! Not a good swing at all! It’s definitely not 
his day today. On the seventh hole he got a bo-
gey and before that he barely made par. He will
definitely not get a birdie on this shot. +
A: It seems that his ball has flown somewhere deep 
in the trees. He is having a hard time finding it
and even his caddie has climbed a tree to try and
spot it. +
B: Oh no! A bear! Run, Tiger, run! Somebody call 
animal control! +
E: So, a pretty exciting ending to that dialogue there… +
M: Bear… +
E: A bear on the… on the golf course. +
M: Yeah, I wonder if Tiger's okay. Hehe. +
E: I sure hope so, cause it would be a huge loss to the world of golf. +
M: Right, so, we did learn a lot about golf, because they used some very specific and 
technical words for golf, so, let's look at these now in “language takeaway”. +
Voice: Language takeaway. +
E: Alright, so, the announcers were talking about the game and they… and they… they're 
talking about the course and they s… and they're “here on the eighth hole” and they said
that last time Jack Nicklaus hit a hole in one. +
M: Hole in one. +
E: A hole in one. +
M: Okay, a hole in one. +
E: So, this is when you hit the ball once and the ball goes in the hole. +
M: Exactly, so, it something very difficult to do. +
E: Yes. +
M: Right? A hole in one. +
E: I've certainly never made one. +
M: Hehe. Okay, so, sometimes it's also called an ace. So, it can be ahole in one or called 
an ace. +
E: Uh, okay. +
M: Now, for our second word… now, once we get to the hole, to the ninth hole or the tenth 
hole, we have to tee off. +
E: To tee off. +
M: Tee off. +
E: So, when you tee off, um, you begin playing. +
M: Right, so, it's the very first instance, where you put the little ball on the tee. +
E: Uhu, and you hit the ball for the first time. +
M: Exactly. So, to tee off. +
E: Now, another, um, golf vocabulary, they're… they were talking about a caddie. +
M: Right, a caddie. +
E: A caddie. +
M: Now, a caddie is a person. +
E: Yes, it's the person who carries your golf clubs. +
M: Exactly, so, he carries your bag… +
E: Yep. +
M: Your golf clubs and basically helps you while you're playing golf. +
E: Yeah, he tells you which way you should hit the ball and maybe, you know, gives you a 
nice cold drink and… +
M: Hehe. Yes. +
E: Looks after you. +
M: Very good. So, that's a caddie. +
E: Uhu. +
M: And now, the caddie, since he has to carry all the golf clubs, Tiger Woods asked him for 
his driver. +
E: A driver. +
M: Driver. +
E: A driver. +
M: Now, a driver is a type of golf club. +
E: Right, it's not a person. +
M: No, no, it's a type of golf club and it's a very big and heavy golf club that is used to tee 
off. +
E: So, it's used to hit the ball a very long way. +
M: Yes, that is called the driver. +
E: Okay, so, and the next thing they were talking about were, um, some different types of 
scores that you could get on a hole. And the first one they mentioned was par. +
M: Okay, so, you can make par. +
E: Okay, or the par of the course can be 'four'. +
M: Okay, very good. So, basically, the par is the maximum number 
ofswings or strokes you can make before putting the ball into the hole. +
E: Right, so, it's like… it's like the… the… right, so, when the… the… when the… when a hole 
is par four, you should only hit the ball four times. +
M: Four times or less. +
E: Yep. +
M: Uhu, very good, now, if you don't make par, there're some options. +
E: You can make a bogey. +
M: Alright, a bogey. +
E: A bogey. +
M: Now, sometimes the golf course is very difficult. +
E: Yeah. +
M: So, instead of putting the ball in the hall, let's say in four 'turns'… +
E: Yeah. +
M: You do it in five. +
E: Okay, so, it's one over par. +
M: One over par. +
E: So, that's bad. +
M: Yeah, that's bad, because… +
E: Yeah. +
M: You get a point, so, it's kind of strange, because in golf the more points you have… +
E: The worse you are. +
M: The worse you are. +
E: Yeah. +
M: So, that is a bogey. +
E: Now, they also talked about a birdie. +
M: Birdie is the opposite – if you hit one under par. +
E: So, that's good. +
M: Yeah, that's good, because you have minus one – one less than par. +
E: Alright, so, this is actually a lot of weird crazy strange +
language:birdie, bogey, caddie, driver. +
M: Hehe. +
E: Why don't we listen to the dialogue one more time to help us understand? +
A: Good morning golf aficionados! My name is Rick 
Fields, and you guessed it, I am here with my
main man, Bob Copeland. +
B: Thank you, Rick! As you can see, ladies and gen- 
tleman, we are here in beautiful Pebble Beach
where the top golfers in the world are trying to
win the grand prize of one million dollars! +
A: Whoa, that’s a lot of cash! Let’s go to the course 
and see how Tiger Woods is doing. +
B: All right, were’re here at the eighth hole. It’s a par 
four, and has some very difficult hazards which
many golfers find difficult to avoid. Although, I did
see Jack Nicklaus hit a hole in one on this very
same hole! +
A: Tiger Woods is about to tee off, and let’s see if 
he has the same luck as Jack. Tiger is asking
his caddie for his driver and, he seems to be very
nervous. +
B: Oh no! Not a good swing at all! It’s definitely not 
his day today. On the seventh hole he got a bo-
gey and before that he barely made par. He will
definitely not get a birdie on this shot. +
A: It seems that his ball has flown somewhere deep 
in the trees. He is having a hard time finding it
and even his caddie has climbed a tree to try and
spot it. +
B: Oh no! A bear! Run, Tiger, run! Somebody call 
animal control! +
M: Alright, great, so, I think it's clear now what type of rules they have in golf and how it 
works. So, why don't we take a look now at some of the phrases that we heard in the
dialogue in “fluency builder”? +
Voice: Fluency builder. +
E: Okay, well, one of the phrases I wanna talk about is something that Bob Copeland said. 
He said “As you can see, ladies and gentlemen, we're here at beautiful Pebble Beach”. +
M: Okay, as you can see. +
E: As you can see. +
M: So, this usually goes in the beginning of a sentence. +
E: Yeah, it's a way to say “I know you can see this”, “I'm telling you something you know”. +
M: Okay, so, maybe I'm showing you my house… +
E: Uhu. +
M: And I can say “As you can see, our living room is very spacious”. +
E: Yes, so, this is actually a really helpful phrase. It can help sound you really native-like, 
so, why don't we hear some examples of how it's used. +
Voice: Example one. +
A: As you can see we recently remodeled our entire kitchen. +
Voice: Example two. +
B: As you can see here the damage to the building is very serious. +
Voice: Example three. +
C: As you can see the hairstylist made a mistake when cutting my hair. +
M: Alright, great, so, as you can see. Now, for our second phrase, well, Tiger Woods wasn't 
doing very well and the announcer said it’s not his day. +
E: It's not his day. +
M: It's not his day today. +
E: Alright, so, when it's not your day, um, you're having a bad time or a bad day. +
M: Right, maybe you're having difficulties or you're having bad luckthat day. +
E: Yeah, so, for example “Today, um, I, mm… had a headache and I ripped my pants and I 
spilled coffee on myself, so, it really wasn't my day”. +
M: Okay, it's not your day today. +
E: No. +
M: Great phrase and also very common and s… makes you sound very native. +
E: That's right. Now, the last phrase, um, similar to it’s not your day, we also heard that 
Tiger was having a hard time. +
M: Okay, to have a hard time. +
E: To have a hard time. +
M: Now, if you have a hard time with something… +
E: You have difficulty with it. +
M: Okay, now, it's not only related to golf, right? +
E: Of course you can talk about anything like this, so, “Oh, I'm having a hard time 
understanding what this word means”. +
M: Okay, or when I was in school I had a hard time with math. +
E: Alright, me too. +
M: Hehe. So, to have a hard time means that you have difficulties with something. So, 
great phrases, great words. Let's listen to this dialogue for the last time and then we'll come
back and talk a little bit more about golf. +
A: Good morning golf aficionados! My name is Rick 
Fields, and you guessed it, I am here with my
main man, Bob Copeland. +
B: Thank you, Rick! As you can see, ladies and gen- 
tleman, we are here in beautiful Pebble Beach
where the top golfers in the world are trying to
win the grand prize of one million dollars! +
A: Whoa, that’s a lot of cash! Let’s go to the course 
and see how Tiger Woods is doing. +
B: All right, were’re here at the eighth hole. It’s a par 
four, and has some very difficult hazards which
many golfers find difficult to avoid. Although, I did
see Jack Nicklaus hit a hole in one on this very
same hole! +
A: Tiger Woods is about to tee off, and let’s see if 
he has the same luck as Jack. Tiger is asking
his caddie for his driver and, he seems to be very
nervous. +
B: Oh no! Not a good swing at all! It’s definitely not 
his day today. On the seventh hole he got a bo-
gey and before that he barely made par. He will
definitely not get a birdie on this shot. +
A: It seems that his ball has flown somewhere deep 
in the trees. He is having a hard time finding it
and even his caddie has climbed a tree to try and
spot it. +
B: Oh no! A bear! Run, Tiger, run! Somebody call 
animal control! +
E: Alright, so, Marco, I know that in, um, the Western business world golf is actually super 
important for your career, isn't it? +
M: Well, many times, you know, when you see in movies or the stereotype is that business 
is done on a golf course. +
E: Yeah. +
M: And yeah, it is true. Many times, you know, people will invite you out to a golf course 
and you'll be playing a game and, you know, talking business and relaxing at the same
time. +
E: So, maybe you… you negotiate a g… a deal out on the golf course. +
M: Exactly, and of course, if you lose, it's a good thing, because then the deal will pull 
through. +
E: Aha, okay. Well, actually, I know that is so important for people, um, who are wanting to 
do well in business and many people who don't speak English as their first language take
golf English lessons. +
M: Right, so, not only golf lessons like… +
E: Yeah. +
M: How to play golf, but also in English. +
E: Like how to talk about golf, how to, um, you know, talk to other people and make deals 
while you're on the golf course. +
M: Uhu, yeah, cause like in many other sports golf has also its slang and… +
E: Yep. +
M: Its terms and stuff. So, yeah, it's very interesting and it's one of those cultural things. +
E: That's right. So, if you have any questions or comments about today's lesson, why don't 
you visit our website at englishpod.com. +
M: Right, we're always there to answer any questions or doubts you might have and until 
next time, we'll see you there. +
E: Good bye! +
M: Bye! 

  
