= 0131
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to another great lesson here at EnglishPod! My 
name is Marco. +
C: And my name is Catherine, so, Marco, today we’ve got a little bit of an unusual lesson, 
because we’re talking about hypothetical situations. +
M: Right, we’re talking about a… unreal situation or something that may happen or may not 
happen. +
C: Okay, so we’re gonna hear all about this in today’s dialogue. We’re gonna hear it a 
couple of times and then we’ll come back. We’ll be breaking it down for you, so you know all
about this great phrases and how to talk about not real situations with your friends. +
A: Okay, next question. If Eric asked you out on a 
date, what would you say? +
B: Duh! I would say yes! Eric is the most popular kid 
in school! Okay, my turn. What would you do if
you won the lottery? +
A: Let’s see.... If I won the lottery, I would buy two 
tickets for a trip around the world. +
B: If you buy me a ticket I will go with you for sure! +
A: My dad will freak out if I even mention a trip like 
that! +
B: Alright this is a good one. What would your mom 
say if you told her you are going to get married? +
A: If I told her that, she would faint and have me com- 
mitted! +
M: Alright, so I think that was clear and, well, a very common situation – two teenage girls 
talking to each other about, you know, boys and what would you do and duh-duh-duh. +
C: Guys do this too… +
M: Uuuh… +
C: So don’t just put this on the girls, okay? +
M: Hehe. I don’t think we do it like this though. +
C: No, but it’s actually a very popular game in the car to play – thewhat-if game. +
M: The what-if game. +
C: Yeah. +
M: Exactly, and that’s exactly the topic that we wanna talk about today is the 
structure what-if, which is actually called a conditional. +
C: Alright, so conditional, because the results – the… the thing that happens – depends on 
something else. +
M: Exactly. +
C: So let’s, uh… let’s actually take a look at the words in today’s “language takeaway” 
before we talk about all this grammar stuff. +
Voice: Language takeaway. +
M: Okay, so we’ll start off with some basic words. Um, well, you know, they were talking 
about guys and she said if Eric asked you out. +
C: Hahah. +
M: Hehe. Right? So, to ask somebody out. +
C: Okay, so this might be a little bit strange, because you think, okay, to ask is “to ask a 
question”. But to ask out, it’s a fixed phrase… +
M: Uhu. +
C: It’s something you say; these two words go together, right? +
M: Uhu. +
C: So I want to ask someone out, it means I want to invite someone on a date. +
M: On a romantic date, usually. +
C: So, yeah, “I want to ask him out to dinner” or “he asked me out to the movies”. +
M: Uhu. Now, if I didn’t want to ask somebody out on a romantic date, what would… 
what verb would you use? +
C: I’d say you could invite someone out, uh, but then again, it’s always a little bit, uh… 
well, you can say invite for someone if you’re gonna ask someone on a date too, so… +
M: Yeah. +
C: I’d say to ask out is always romantic. +
M: Uhu. +
C: And to invite can be romantic or just friends. +
M: Okay, so to ask somebody out. Now, uh, she… they were talking about other situations, 
maybe they would go on a trip or something and she said my dad would freak out. +
C: Uh! Wah, this is a great phrase. This is something that I used a lot, when I was a 
teenager. +
M: The word freak out? +
C: Freak out, so the verb to freak out means to be really angry or upset or, you know, it 
could be a… good thing or a bad thing… +
M: Uhu. +
C: But usually when we’re talking about our parents, it’s a bad thing. +
M: It’s a bad thing, so they get angry, they start yelling at you. +
C: Yeah, so… +
M: Freak out. +
C: Freak out means like overreact. +
M: Alright. And the last word that we have on language takeaway today is committed. +
C: Well, let’s look at the whole phrase, he says “she would have me committed”, so this is 
actually being done to someone. +
M: Uhu. Now, we l… did look at this word before, but basically for… for marriage, right? To… 
to commit to somebody - to promise. +
C: Yeah, but to have someone committed… +
M: Uhu. +
C: Means that you’re going to send them away to maybe a mental institution. +
M: Exactly. +
C: So this means that they have psychological problems and someone else sends them to 
the hospital, because they can’t send themselves. +
M: Exactly, so it’s always used to have someone committed, right? +
C: Right, cause it’s… it’s being done to them. They don’t want it to happen. +
M: Uhu. +
C: It’s involuntary. +
M: Okay, so she had him committed. +
C: My mom’s gonna have me committed if I keep working twenty hours a day. +
M: Hehe. Exactly, so that’s the way you use it and, so now you have another way of using 
this verb. But now I think we should listen to this dialogue again. We’re gonna slow it down
a little bit and then we’ll come back and look at this grammar focus that we wanna talk
about. +
A: Okay, next question. If Eric asked you out on a 
date, what would you say? +
B: Duh! I would say yes! Eric is the most popular kid 
in school! Okay, my turn. What would you do if
you won the lottery? +
A: Let’s see.... If I won the lottery, I would buy two 
tickets for a trip around the world. +
B: If you buy me a ticket I will go with you for sure! +
A: My dad will freak out if I even mention a trip like 
that! +
B: Alright this is a good one. What would your mom 
say if you told her you are going to get married? +
A: If I told her that, she would faint and have me com- 
mitted! +
M: Alright, so, uh, we understood all the vocab now. Now let’s take a look at these unreal 
situations and - what we were saying though –what-if game. +
C: Right, so I think it’s important to push these into two different categories, right? +
M: Uhu. +
C: We have one kind where it’s very unrealistic, it’s probably not going to happen… +
M: Uhu. +
C: That kind of a situation. And the other one is a situation that could very well happen, 
something that’s probably very common. +
M: Uhu. +
C: Okay, so the first one we’re gonna talk about is very unrealistic situations… +
M: Okay. +
C: Things that probably won’t happen. +
M: Okay, so let’s take a look at, ah, an example that we found in the dialogue. The most 
common one and I think everybody gets asked this question is if you won the lottery,
what would you do? +
C: Okay, if you won the lottery, so this is a situation that’s very uncommon, right? +
M: Right. +
C: Not many people win a lottery, so… +
M: Uhu. +
C: We have to say if you won the lottery, we use this… this… thisverb in the past tense. +
M: Uhu. +
C: If you won the lottery, if this happened, what would you do? +
M: Right. +
C: Alright. +
M: So, Catherine, if you won the lottery, what would you do? +
C: If I won the lottery, I would buy a boat and sail around the world… +
M: Wow. +
C: With my friends. +
M: Hehe. Alright, so another example, again, using the same structure, right? The verb in 
the simple past tense, we would say if you were stuck on an island with one other
person, who would that be? +
C: Alright, so if you were… +
M: Uhu. +
C: Stuck on a desert island with one person, who would that person be? +
M: Uhu. +
C: So, Marco, I’m gonna ask you, who would it be? +
M: Uh, I think it would be an engineer or a scientist that could probably get me off the 
island? +
C: What about your girlfriend? Hehe. +
M: No, well, you know, that’s the point if… I can get to her quicker. +
C: Uh, okay. Uh, I would say maybe kind of romantic, but ??? kind of that. +
M: Hehe. +
C: So that’s the first situation. We’ve got the situations like being stuck on an island, 
winning the lottery - these are very unlikely. But what about the other kind? +
M: Uh, but before we move on to that, uh, you noticed that we used the verb was, we 
didn’t say I was on an island, I said if I were, right? +
C: Uhu. +
M: Or if you were. +
C: Uhu. +
M: So this is the way that you use it in these conditionals – If I wereyou or if you were 
president of the United States. +
C: And this is a rule, so this is a grammar rule. We’re not gonna describe WHY it happens, 
because it’s very, very complicated and you can look it up on our site, but we’re gonna
describe HOW to use it, that’s the most important. +
M: Uhu. +
C: So we can say, for example, “Marco, if I were you, I would dye my hair red”. +
M: Hehe. Why? +
C: I don’t know, I think it would be cool. +
M: Uh, I don’t think so. +
C: So if I were you, I would or… +
M: Aha. +
C: If you were me, what would you do? +
M: Uhu. Exactly, so we always use it like this, right? If you’re gonna use this conditional, 
always use were for the subject, never was. +
C: Right, so you can tell, this is very, very big grammar issue, a lot of English speakers 
make this mistake. +
M: Yes. +
C: Uhu. +
M: Very many, so… but now you know that you shouldn’t make this mistake and you can 
speak properly. Alright, so now that we’ve seen these, uh, semi-unreal situations, let’s
move on to something that’s a little bit more probable, that it may happen. +
C: Right, so we’ve got these, uh… these situations that are common or likely. Um, for 
example, in this lesson we hear “I will go with you for sure”, so this “if you buy me a ticket
to travel, of course I will go with you”. +
M: Uhu. +
C: So if you buy, this is in the present tense… +
M: Uhu. +
C: If you buy, then I will. +
M: Right. +
C: Right. +
M: So now we… you noticed the difference. The verb is in thepresent and then we use… 
instead of would we use will. So again, I can say “if it rains tomorrow, I will stay home and
watch TV all day”. +
C: Okay, so think about this. We… before we talked about going todevert… desert islands, 
now we’re talking about rain and the weather. They’re very, very different. +
M: Uhu. +
C: The rain is… is, you know, is very common, so we can say “if it rains tomorrow, I will 
need an umbrella”. +
M: Uhu. +
C: What about this? If we have lunch tomorrow, what will we eat? +
M: So… okay, so we have lunch pretty much everyday, right? +
C: Yeah, pretty much. +
M: So again, it’s a k… it’s a situation that is very probable, so if, uh, we have lunch 
tomorrow, uh, we will probably eat, I don’t know, pasta, I think. +
C: Yeah. +
M: Um, kind of like pasta, tomorrow. +
C: Pasta. +
M: Yes. +
C: Noodles. +
M: Yeah. +
C: Alright, so, Marco, let’s take another listen to some of these phrases and try and figure 
out while you’re listening which kind ofconditional it is – first or the second. +
Voice: Example one. +
A: If it’s sunny today, we will go to the park. +
Voice: Example two. +
B: I would get a divorce if I were you. +
Voice: Example three. +
C: Mary will be very sad if Joe leaves. +
Voice: Example four. +
C: We wouldn’t be so late if Nick drove faster. +
M: Very good, so we heard different examples and the first conditional is the one that we 
mentioned is very probable and thesecond conditional is the one that’s not so probable.
So they’re very easy to distinguish, you don’t really need to know the names, just know
how to use them, right? +
C: Exactly, and so just remember if you were me, what would you do? We’ve got these 
kind of pairs, these words that go together. +
M: Uhu. +
C: And the other one is more common. It’s if we… if it rains tomorrow, I will bring an 
umbrella. +
M: Uhu. Perfect, so why don’t we listen to this, uh, dialogue for the last time just to kind of 
reinforce everything and then we’ll come back and talk a little bit more. +
A: Okay, next question. If Eric asked you out on a 
date, what would you say? +
B: Duh! I would say yes! Eric is the most popular kid 
in school! Okay, my turn. What would you do if
you won the lottery? +
A: Let’s see.... If I won the lottery, I would buy two 
tickets for a trip around the world. +
B: If you buy me a ticket I will go with you for sure! +
A: My dad will freak out if I even mention a trip like 
that! +
B: Alright this is a good one. What would your mom 
say if you told her you are going to get married? +
A: If I told her that, she would faint and have me com- 
mitted! +
C: So, Marco, if we talk anymore about grammar, someone’s gonna have to have me 
committed. +
M: Hehe. It is a little bit difficult to talk about grammar, especially on a podcast, cause it’s 
such a difficult topic and it’s also kind of heavy, right? +
C: It is, but I’ll tell you this: these are very, very common phrases. People, they use these 
all the time. We talk it… we’re talkinghypotheticals very often. +
M: Yeah. +
C: So, um, if you’re asking for advice, for example, or if you’re just playing a game in the 
car, uh, you’re gonna encounter these and it’s very important to be able to know how to use
them. +
M: Uhu. So and this is what we wanna see now. Please, come to our website 
at englishpod.com and l… you have a million questions, you have a million hypotheticals
that you can leave on our website, so let us know, ask us the craziest,
funniest, weirdest questions that you can, right? +
C: Exactly, and if you have questions about the stuff that we’ve been talking about, you’re 
not really clear on some things, just ask us, because we’re happy to answer your questions
and give more examples on the website. +
M: Alright, so we’ll see you guys there and, uh, until next time… +
C: Bye everyone! +
M: Bye! 

 
