= 0136
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! Um, welcome back to another great lesson here atEnglishPod! My 
name is Marco. +
C: My name is Catherine, hello everyone! And today we’ve got a great lesson for you at 
the upper intermediate level. +
M: We’re gonna be talking about an interesting, uh, topic, which isgambling. +
C: Yeah, I don’t know if you like to do this, Marco, go, you know… +
M: I’m actually… +
C: Play some cards. +
M: Yeah. +
C: Play some, uh, poker, black jack, throw the dice. +
M: I’m actually, uh, a bit of a fan of the roulette. +
C: You have to throw the ball into the wheel, that’s spinning and lands into… in like a 
little compartment, in a number. +
M: Right, so you can win like, uh, based on the number and the color. But it’s interesting, 
because if you get the number right, it pays you thirty-five times your bet. +
C: Wow! That’s a l… +
M: So… +
C: That’s a lot of money to win. +
M: Yeah. +
C: A lot of potential there, but there’re a lot of numbers on that wheel. +
M: But, uh, that’s the thing – some people like gambling, some people don’t like it and in 
some countries, in some states it’s illegal, right? +
C: Exactly, so today we’re talking about a city that’s looking to legalize this sport, so we’re 
gonna take a listen, hear it one time; we come back, we’re talking all about what’s going on
in today’s lesson. +
A: Did you hear? The state is thinking of legalizing 
gambling in our city! Soon we are gonna have
amazing hotels and casinos here which will be
good for our business! +
B: Are you serious? Gambling is a vice industry built 
on deception and fed by the intentional exploita-
tion of human weakness for the sole purpose of
monetary gain! It disgusts me. +
A: What are you talking about? How does it exploit 
people? +
B: Well, to begin with, Gambling is addictive, ruins 
marriages, destroys families and bankrupts com-
munities. Once you are addicted it is very diffi-
cult to stop. People have lost their houses, cars
and been left out on the street after becoming
addicted. Secondly, it exploits because men be-
come addicted to gambling most often because
of the action and risk. Women gamble to escape,
and senior citizens will start gambling for the so-
cial interaction. Underage gamblers often start
gambling on sports with friends and then illegal
bookies. +
A: Geez! Now that I think about it, maybe legalizing 
gambling isn’t such a good idea! Although, I have
been to Las Vegas, and I didn’t become addicted
or anything like that. +
B: You cannot predict who will become addicted to 
gambling. Now excuse me, I have a protest rally
to organize! +
M: Alright, so, uh, very strong opinions against gambling, right? +
C: Absolutely, so we’ve got someone, who hasn’t really thought it through, and another 
person, who has thought way too much about what’s going on. +
M: Hehe. Right. And, well, he did point out some very interesting, um, arguments against 
gambling and so we’re gonna take a look at some of the language that person used today in
“language takeaway”. +
Voice: Language takeaway. +
C: Well, this first word we’ve got here is a word that has to do with a topic of today’s lesson, 
so legalizing gambling. What does it mean tolegalize? +
M: Right, so to legalize – to make it legal. +
C: Uhu. +
M: Uhu. +
C: So legal is the word that refers to law. +
M: Uhu. +
C: And so that means to make something “okay”; it means to allow something in a state or 
a country. +
M: Exactly, so in many countries it’s illegal, uh, to gamble, so in this case this city is looking 
to legalize it, to make it legal. +
C: Alright, so, many young people in America would like to see, uh, this law changed: 
you’re not allowed to drink until you’re twenty one years old, drink alcohol that is. So they
would like to see the legalization ofunderage drinking. +
M: Now, is it twenty one in all states… +
C: Yes. +
M: Or in majority? Really? +
C: All states. +
M: Oh, I thought it was only in some of them. +
C: No, it changed in the late seventies I think, but, uh, you absolutely cannot drink until 
you’re twenty one. +
M: Wow, what do you think? Is that okay or is that… +
C: I think that it encourages young people to drink irresponsibly and so, I believe, we 
should, uh, legalize drinking at the age of eighteen. +
M: Mm. +
C: Because it would make people learn how to be more responsible. +
M: Right, interesting. Aright, so we want to legalize underage drinking here at EnglishPod. +
C: Alright, no, let’s not manipulate my words, but… +
M: Alright. +
C: Uh, this next word is very, very important. +
M: He’s saying that gambling or the gambling industry exploits people. +
C: Okay, exploit, you might have heard this in the news before. Uh, we talk about often in 
the news “the exploitation of people”. +
M: Uhu. +
C: Um, but in this case we’re talking about… yeah, exploiting people through money and 
gambling. +
M: Right, so to exploit, basically, is to take advantage of them, right? +
C: Yeah, to use them for something. +
M: To… +
C: Not to treat them as people, but to use them as a way to get something. +
M: Alright, so we often hear about it as you say in the news about, you know, factories or 
companies exploiting their employees or something of this sort. +
C: We can also exploit the earth for its resources by taking oil and taking diamonds and 
taking gold. +
M: Okay, so “to take advantage of”, interesting. So, uh, to exploit is the verb, 
but exploitation is the noun. +
C: Alright, that’s the thing, so we talk about “the exploitation of people in this country” or 
“the exploitation of the earth”. +
M: Uhu, and they’re talking about how gambling exploits people and how it’s a vice. +
C: Ooh! Vices… so for those of you, uh, Christians out there you might be very familiar with 
the… the sins, right? +
M: Uhu. +
C: The seven deadly sins. Well, these are all vices – things that you do that are bad. +
M: Uhu. +
C: So drinking too much is a vice. +
M: Right, or eating too much, right? +
C: Right, or spending money without to having money maybe a vice for you. +
M: Hehe. So addictions are also a type of vice, right? Like drinking, smoking or drug abuse. +
C: Exactly, these are all vices. So a vice is a bad thing. +
M: Now, we often… Now, we may remember this show – popular American show – called 
Miami Vice, so, well, what is that? +
C: Ooh, well, Miami Vice, it’s in the city of Miami and it’s about police officers. So in the 
police, there’s sometimes a group called the vice squad. +
M: Uhu. +
C: These are people who go out and try and stop people who are doing things that are 
vices. +
M: Oh, like drugs and… and gambling… +
C: Yeah. +
M: And stuff like that, uhu. +
C: Exactly. +
M: Vice squad, interesting. Alright, and now for the last word on language takeaway we 
have this, uh, interesting word – a bookie. +
C: Oh, right, so if any of you like to go to the horse races, you might be familiar with this 
one. A bookie is someone who helps you make a bet; it’s his job to help you make a bet. +
M: Uhu, so we often see it in movies, maybe you are betting, uh, on a sports competition, 
right? And you are betting, I don’t know, ten dollars against this team, so you would go to a
bookie to place your bet, because there’re not really any legal place where you can do it. +
C: Exactly, or if I wanna, say… okay, tonight the Chicago Bulls are playing the [Phoenix] 
Suns and you wanna put a hundred dollars on the Chicago Bulls; that means they’re going
to win. So you use a bookie and he helps you put the money down; he helps you bet. +
M: Now, usually this is illegal, right? +
C: Generally it’s illegal, yeah. +
M: Uhu. +
C: It depends on… I guess you… you can go to a bookie at the horse races… +
M: Right. +
C: And it’s legal, but, uh… +
M: At the horse track. +
C: Yeah, generally it’s illegal, I think. +
M: Okay, so a sports bookie. We would say a sports bookie, right? +
C: Uhu, yeah. +
M: Interesting words; a lot of words related to, as we said, addictions and vices, but that’s I 
guess kind of what, ah, the whole gambling industry involves, right? +
C: Absolutely. +
M: Alright, so now that we’ve seen those great words on language takeaway, let’s move on 
now to “fluency builder”. +
Voice: Fluency builder. +
C: Okay, fluency builder is where we get into some of this really exciting stuff, stuff where 
we hear some opinions from a person who is not very happy with the gambling industry. So
this first one: “Gambling is an industry built on deception”. +
M: Okay, so it’s built on deception. So, well, it’s an industry, so it’s not really tangible. +
C: Right, so this is a metaphor; it’s like saying that, uh, the… this industry is, uh, 
dependent on something. And what is it dependent on? +
M: Deception. +
C: Deception. So what’s deception? +
M: So, ba… to deceive, right? +
C: Uhu. +
M: That comes from the verb deceive, which basically says… it’s like a false appearance, 
right? Not really being completely truthful. +
C: Okay, this is a really good, so a lot of movies that we like to watch or theater, uh, is 
based on deception in a good way, because it… uh, you get the idea that something is, uh,
a certain way, but it really isn’t in real lives. +
M: Uhu. +
C: So deception is… is in a theater maybe a good thing, but in general… +
M: Uhu. +
C: Deception is a bad thing. I could say: “Marco, I’m sorry I deceived you”. +
M: Oh, you lied to me, basically. +
C: I lied to you. +
M: Yeah. +
C: Yeah, so… +
M: Alright. +
C: Deception usually involves lies or, um, trying to make something seem like something 
that it’s not in reality. +
M: Right. Okay, so it’s this industry is built on deception. And he said that the sole 
purpose of this industry is to make money. +
C: Exactly, so this… this phrase sole purpose is very, very common, you hear this a lot. 
Um, sole… +
M: Uhu. +
C: Like the sole. +
M: Like your human soul. +
C: Like your human soul. It’s spelled differently S-O-L-E, so we’re talking about the one 
thing. +
M: One and only. +
C: Yup, so my sole love. +
M: Okay. +
C: I only have one love. My sole pair of shoes. +
M: Uhu. +
C: I have only one pair of shoes. +
M: Right. +
C: So it’s one thing. +
M: One. +
C: But the sole purpose, so the only reason that this industry exists is what? +
M: For monetary gain. +
C: Mmm, so monetary. +
M: Monetary. +
C: You might have heard the International Monetary Fund. +
M: Exactly, the IMF. And, uh, so monetary refers to money. +
C: Money! +
M: Okay, and… +
C: As the other door said it’s a gas. [???] +
M: Hehe. And gain, which means… basically means… +
C: Making it. +
M: To… to get more money. +
C: Yeah. +
M: So that’s the point that this person is making that… that the sole purpose of the 
gambling industry is to make money. +
C: Ouch, so he’s saying there’s no other reason to gamble. People are in thins industry just 
to make money, it’s greedy. +
M: Uhu, well, I mean, uh, basically, you could probably say that almost about… almost all 
the con… all the companies, right? +
C: What about education companies like ours? +
M: That’s different, right? +
C: Hehe. Alright, ??? +
M: Education is very different. +
C: Absolutely, so what’s another industry that has a sole purpose? +
M: Uh, for example, non-profit organizations. +
C: Uh. +
M: Their sole purpose is to help people. +
C: Alright, okay, I can get into that. +
M: Uhu. +
C: Yeah, cool, so… +
M: Alright. +
C: Uh, sole purpose and monetary gain – very useful phrases, but, uh, let’s take another 
listen to today’s dialogue and, uh, put to usesome of these great, great new words. +
A: Did you hear? The state is thinking of legalizing 
gambling in our city! Soon we are gonna have
amazing hotels and casinos here which will be
good for our business! +
B: Are you serious? Gambling is a vice industry built 
on deception and fed by the intentional exploita-
tion of human weakness for the sole purpose of
monetary gain! It disgusts me. +
A: What are you talking about? How does it exploit 
people? +
B: Well, to begin with, Gambling is addictive, ruins 
marriages, destroys families and bankrupts com-
munities. Once you are addicted it is very diffi-
cult to stop. People have lost their houses, cars
and been left out on the street after becoming
addicted. Secondly, it exploits because men be-
come addicted to gambling most often because
of the action and risk. Women gamble to escape,
and senior citizens will start gambling for the so-
cial interaction. Underage gamblers often start
gambling on sports with friends and then illegal
bookies. +
A: Geez! Now that I think about it, maybe legalizing 
gambling isn’t such a good idea! Although, I have
been to Las Vegas, and I didn’t become addicted
or anything like that. +
B: You cannot predict who will become addicted to 
gambling. Now excuse me, I have a protest rally
to organize! +
M: Alright, so gambling. What are you… what are your opinions about it? Pro- 
gambling or anti-gambling? +
C: Okay, well, here’s the thing. Gambling is a sport… +
M: Uhu. +
C: And some… it involves money obviously, but people also don’t… I don’t think should have 
other people telling them how to spend their money, unless they have some kind of…
problem. +
M: Uhu. +
C: Right, so the law doesn't get involved, um, if you have a drinking problem… +
M: Uhu. +
C: Until you harmful to people around you. +
M: Uhu. +
C: So I don’t think that it’s right for the… for the government to be able to say “listen, you 
can’t gamble”, because it’s your own money. If it makes you’re happy, it makes you’re
happy +
M: Hm, interesting. No, we’ve… we’ve seen very, uh, specific cities or places where you can 
actually gamble in this way. You have, uh, Monaco… +
C: Yeah. +
M: Or Las Vegas or… +
C: Macao. +
M: Macao, more recently, right? So very interesting cities or countries that have been built 
on the gambling industry which apparently is a multibillion dollar industry. +
C: Uhu, absolutely. I don’t know, what do you think? Do you… are you against gambling? 
Are you for gambling? I mean it is one of those things that you can really… +
M: Or do you maybe even like it? Maybe some people don’t even really care for it… they 
don’t find fun to play black jack or go to the… play a round of poker or something like that. +
C: Uh, well, that’s their problem. I enjoy it. Hehe. +
M: Hehe. +
C: Uh, it’s fun, I mean, as long as, uh, with anything you do it in moderation… +
M: In moderation. +
C: It means you don’t do it to much… +
M: Uhu. +
C: I think it’s okay. +
M: Alright, so, ah, listeners come to our website englishpod.com to the comments section 
where you can tell us, well, what are your opinions. If you do like gambling, tell us what
game you like. So, uh… and also if you have any questions or comments, we’re always
there to answer them, right? +
C: It can be kind of, um, a big issue to talk about, because some people are really against 
it, some people are really for it. +
M: Yeah. +
C: So, uh, curious to hear your opinions. +
M: Yeah, we look forward to your opinions and, uh, we’ll see you guys later. +
C: Bye everyone! +
M: Bye! 

  
