= 0143
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! And welcome back to EnglishPod! My name isMarco. +
C: And my name is Catherine. +
M: And today we’re gonna be visiting one of my favorite places I must say. +
C: Really, so you’re… you’re a big meat eater. +
M: I am. I have to have meat everyday, so that’s why I usually go to the butcher. +
C: Alright, so vegetarians, be warned. +
M: Hehe. +
C: Today’s dialogue is all about eating meat and where to go to get meat, so as Marco said, 
that place is called the butcher’s. +
M: So we’re gonna be visiting the butcher and we’re gonna learn all the different types of 
meat you can find there. +
C: Great, so, uh, we don’t have anything to preview, but before we get started [I] just like 
to mention that you’re gonna hear a lot of different kinds of words and we’ll be back in a
minute to talk about what they mean. +
Butcher: Hi. What can I get for you? +
Gina: I’d like a half a pound of ground beef, 
please. +
Butcher: Good choice! Our ground beef is extra 
lean, if you know what I mean. +
Gina: Could I also have half a dozen pork 
chops and two pounds of boneless
chicken breasts? +
Butcher: No, no no no chicken breasts at the mo- 
ment, but we have some nice chicken
thighs. +
Gina: No, that won’t do. I’ll take this smoked 
ham you have here. +
Butcher: Okay, is there anything else? +
Gina: Do you have any other cold cuts? Is this 
salami and bologna you have here? +
Butcher: Yes! It’s very fine meat! Made it myself... +
Gina: Sounds good. Okay, that’s it. +
Butcher: Wait! We have T-bone, rib eye, and sir- 
loin steaks. They are very fresh! Just
came from the slaughter house... +
Gina: Mmm... No that’s okay, really. I think 
that’s all for today. +
Butcher: Okay. That will be thirty-four dollars and 
fifty cents. +
M: Alright, we’re back, so this butcher was kind of creepy in the beginning. +
C: Very creepy at the beginning. +
M: I think that’s usually the conception that you have of butchers, because they always 
have a knife or… and they’re always covered in blood, but it’s not human blood, right? +
C: Right, like the movie Sweeney Todd. Did you see that? +
M: Yeah, like Sweeney Todd. +
C: Butcher of Fleet Street. Hehe. +
M: Hehe. So, uh… so, but we actually took a look at a lot of different types of meat that the 
woman was ordering, uh, so why don’t we take a look at these now in “language
takeaway”? +
Voice: Language takeaway. +
C: Okay, so the first is a classic cut – this is something that we had in my house about once 
a week growing up – it’s called a pork chop. +
M: Pork chop. +
C: Uhu. +
M: So, uh, a pork chop comes from the animal – a pork or a pig. +
C: Yeah, we actually don’t say pork to mean the animal. Pork just means the kind of meats 
that comes form a pig. So big difference there when we’re talking about food, we say
“pork”. +
M: Oh, wow. And, uh, what about a pork chop? So what exactly is that? +
C: Chop is usually just on the bone and, uh, oftentimes it’s fried, um… +
M: Uhu. +
C: Or baked, I guess. But, uh, it’s just a piece of pork on the bone. And, uh, a chop, you 
just imagine a knife… phew… chopping something. +
M: Hehe. Alright, so a pork chop, very good. And after pork chops we were ordering 
some ground beef. +
C: Alright, so ground beef is another important one. Ground beef is beef that’s been 
chopped up and pushed through a machine that kind of pushes it out in very, very small bits
and pieces. +
M: Okay… +
C: There’s no bone. +
M: So, uh, ground comes from the verb “to grind”. +
C: Uhu. +
M: So to grind up meat – make it very, very small pieces. +
C: Right, so if you wanna make a Spaghetti Bolognese, the kind of beef you use is ground 
beef. +
M: Uhu. +
C: Or even hamburgers. +
M: What are… oh, yeah, exactly. So ground beef, you ground up beef. What other things 
would you grind? +
C: Uh, you could grind your teeth. +
M: Hehe. You can grind… +
C: Some people do that when they are sleeping, they grind their teeth. Um, you can grind, 
um… you have pepper grinders, you know… +
M: Uh. +
C: Peppers sometimes come in balls and you have to grind them to make them smaller and 
broken down. +
M: Very good, so that’s ground beef and from the verb to grind. Uh, now we are buying 
some boneless chicken breasts. +
C: Alright, so boneless, as you have guessed, means without bones. +
M: Uhu. +
C: And, uh, chicken breasts are usually just, uh, really nice juicy kind of tender cut of 
meat from the chicken, from the kind of underside of the chicken where obviously, uh… +
M: Hehe. +
C: Yeah, they have… it’s not a wing, it’s not a leg, it’s just a chicken breast. +
M: Alright, so, boneless chicken breasts. Now usually it is boneless, right, when you buy it 
at the supermarket. +
C: Yeah, yeah. +
M: Uhu. +
C: Next up we’ve got some, uh, classic deli counter favorites. These are our cold cuts. +
M: Alright, so cold cuts. Now this means that they are cold. +
C: Oh, well, yeah, they’re cold, but, uh, I think cold cuts, the most important thing to 
remember here is the… they’re mostly like, uh, kinds of salami or, um, cured meats, so
these are salt-cured or, um, they’re dried meats. And you usually have them on
sandwiches, so like a salami sandwich. +
M: So like cured meat you mean that meat has… hasn’t been cooked. +
C: Oh, no it’s not been cooked, but it’s treated in a way that allows it to last for a very long 
time. +
M: Alright, so… +
C: So they look like long, long tubes of meat. +
M: Or jer… they look very dry, so… +
C: Look very dry… +
M: Alright. +
C: Like beef jerky, for example. +
M: Alright, so cured meat, now, for example, we have salami… +
C: Uhu. +
M: And, uh, bologna. +
C: Bologna. +
M: Now, it’s interesting, because bologna is actually spelled B-O-L-O-G-N-A, so you would 
say bolona, bolokhna or something like that. +
C: Well, I think it comes from the Italian “bologna”. +
M: Right. +
C: Um, but, uh, it’s definitely a change that happened in the English language when it came 
over from Italy. But bologna is a kind of meat that’s ge… yeah, it’s got a very funny looking
name. +
M: Mm, you see, you more sophisticated than I am, that’s why you know this deference 
between sala… +
C: I just speak Italian, so, well, no. +
M: Alright, so, you have salami, bologna and, uh… +
C: Pastrami. +
M: Pastrami. What about ham? Is that… is that considered a cold cut? +
C: You can have ham in the cold cuts section, because, uh, ham sometimes comes in tubes 
you slice. Uh, but ham is also just a normal kind of por… pork. But ham is cured, you know. +
M: Like a smoked ham. +
C: Exactly. +
M: Alright. +
C: Or smoked turkey – one of my favorites. +
M: Mm, very good. And, uh, well, now moving on from the cold cuts, we’re gonna 
concentrate on steaks. +
C: Ooh, steaks, so there are a thousand kinds of steaks in this world and every city seems 
to have its own kind. +
M: Mm. +
C: But here we’re only looking at three, the first of which is the T-bone. +
M: Alright, the T-bone steak, I think is one of the most popular ones. +
C: Definitely. +
M: Um, it’s a steak, that’s pretty big, right? +
C: Yeah, well, yeah, it can be. +
M: Hehe. And it has a bone inside that looks like a T. +
C: Alright, so, um, you’re saying Marco that the T-bone is named after the shape and the 
look of this steak. +
M: Yeah. +
C: Uhu. +
M: T-bone steak. +
C: Alright… +
M: And as well as our next one is also a rib eye. +
C: Okay, so the rib eye, I think, actually, has a piece of the rib in it. +
M: Mm. +
C: So rib is the bone and there’s a circle, which is kind of a… it’s… it’s… the piece of meat 
that’s sliced of the rib and the circle’s actually a part of that rib. So there’s a little bit a bone
in it. +
M: Uhu. +
C: Uh, but it’s not as bony as the T-bone. +
M: Right. So it does have one small bone that kind of looks like an eye, because you could 
see through it. +
C: Uhu. +
M: And our next steak has no bone and it’s the most tender and the best steak you can 
have – sirloin steak. +
C: So I think that the sirloin is definitely the most expensive if you are in a restaurant, 
definitely the most tender, I think, of all those kind of cuts. +
M: It’s delicious. +
C: Uhu. +
M: And usually you can have like a big sirloin steak like a half a kilo, like a four hundred 
gram sirloin steak. +
C: I had a friend who ate a full kilo… +
M: Really? +
C: Sirloin steak, uh, yeah. +
M: Wow. For… this was a competition or? +
C: No, there’s a kind of steak called “la Bistecca alla Fiorentina” in Italy. +
M: Uhu. +
C: It’s the… the Florentine Beef Steak and it is… it can be about a kilo meat. +
M: Wow. +
C: Just… yeah, delicious. +
M: I bet you can’t even move after that. +
C: No, you’re… +
M: Hehe. +
C: You fall asleep with your head in your soup on the table. +
M: Hehe. Alright, so that’s all the… the meet related words that we have for you today. So 
why don’t we move on now to “fluency builder”, where we’re gonna take a look at some of
the phrases in this dialogue? +
Voice: Fluency builder. +
C: We’re gonna look at the phrases, if you know what I mean. +
M: If you know what I mean. Now, I love this phrase if you know what I mean. +
C: I do know what you mean. +
M: Well, it’s… it’s weird. +
C: I like it too. +
M: Hehe. So you can use it for sarcasm. +
C: Yeah. +
M: Right? Or you can use it to kind of insinuate something, right? +
C: Exactly, yeah, so here what you’re saying – you’re saying there’s a double meaning… +
M: Uhu. +
C: In what I want to say, so… +
M: Uhu. +
C: There’s two things I could say, and I’m not gonna say it outright, but, you know, this 
thing that we can’t really say. +
M: So, for example, we can say… +
C: She likes to go out, if you know what I mean. +
M: Alright, so you’re insinuating that not only does she like to go out, but maybe… +
C: Maybe she goes out a lot. +
M: A lot, or maybe she gets drunk or something like that. +
C: Yeah. +
M: So it’s kind of like a double meaning, but you’re trying to be subtle. +
C: Yeah, but it’s not so subtle, cause you you’re actually saying like this is not what I mean. +
M: Hehe. +
C: Or, um, she’s eating for two, if you know what I mean. +
M: Oh, there we go. So you’re insinuating that… well, you’re not really insinuating, you’re 
telling me that. +
C: She’s pregnant. +
M: Pregnant. +
C: Eating for two is a common idiom in English that means that a person… a woman, uh, 
has a… well, is going to have a baby. So here I’m saying: hey, do you know this idiom?
She’s eating for two, if you know what I mean. +
M: Right. +
C: Wink-wink-wink. +
M: Hehe. Wink-wink. So now, why don’t we take a look at some other examples of how we 
could use if you know what I mean in different circumstances when you’re trying to
insinuate something? +
Voice: Example one. +
A: She’s eating for two now, if you know what I mean. +
Voice: Example two. +
B: Tim hit a home run today, if you know what I mean. [NOTE: this can have a sexual 
meaning] +
Voice: Example three. +
C: Jim and Laura are going their separate ways, if you know what I mean. +
M: Alright, we’re back, so, um, now that that’s clear, why don’t we move on to our next 
phrase? +
C: So this one is a counting phrase and for those of you who have heard the 
word dozen before, it might not be so new. The phrase ishalf a dozen. +
M: Half a dozen. So that means half of twelve. +
C: Of twelve. So a dozen is twelve. Um, and it’s, I’m not really sure when this started being 
used in English, but a dozen is twelve and half a dozen is then six. +
M: Uhu. Now, there’s another phrase or another saying that’s very common – a dime a 
dozen. +
C: He’s a dime a dozen. +
M: Uhu, so that means you can get twelve of the same type of guys for ten cents. +
C: Right, so they’re easy to find. +
M: They’re easy to find. +
C: Yeah. +
M: A dime a dozen. Alright, very good. And moving on to our last one, um, when they were 
talking they said something about the meat beinglean, extra lean. +
C: Okay, lean – this is not mean, uh, lean on a door… +
M: Right. +
C: This is not like resting on something. This is actually a kind of, um, way to describe 
food. +
M: Uhu. +
C: And so food is lean if it’s not got much fat, it’s not fatty. +
M: Okay, so if it’s lean, it doesn’t have much fat. +
C: Exactly, so I prefer to eat lean meats, so I often eat, um, birds andpoultry, so… +
M: Oh. +
C: Chicken, I like it pretty lean and if it’s got fat on it, I’ll cut the fat off. +
M: Oh, okay, like the skin. +
C: Uhu. +
M: The skin is fat, right? +
C: Yeah. +
M: Alright, so you can have lean beef. It doesn’t much fat around it. +
C: Yeah, and in America actually on the… the packages at the supermarket it often says the 
percentage of meat that you have. So it’s ninety five percent (95%) lean. +
M: Wow. +
C: Or ninety eight percent (98%) lean. +
M: So that means you have three percent (3%) fat in there. +
C: Exactly. +
M: Or two. +
C: Or two percent. +
M: Ninety eight… Hehe. My math skills are amazing. Alright, so, um, now that we’ve finished 
with all of these words on fluency builder, let’s take a look at our dialogue for the last time. +
Butcher: Hi. What can I get for you? +
Gina: I’d like a half a pound of ground beef, 
please. +
Butcher: Good choice! Our ground beef is extra 
lean, if you know what I mean. +
Gina: Could I also have half a dozen pork 
chops and two pounds of boneless
chicken breasts? +
Butcher: No, no no no chicken breasts at the mo- 
ment, but we have some nice chicken
thighs. +
Gina: No, that won’t do. I’ll take this smoked 
ham you have here. +
Butcher: Okay, is there anything else? +
Gina: Do you have any other cold cuts? Is this 
salami and bologna you have here? +
Butcher: Yes! It’s very fine meat! Made it myself... +
Gina: Sounds good. Okay, that’s it. +
Butcher: Wait! We have T-bone, rib eye, and sir- 
loin steaks. They are very fresh! Just
came from the slaughter house... +
Gina: Mmm... No that’s okay, really. I think 
that’s all for today. +
Butcher: Okay. That will be thirty-four dollars and 
fifty cents. +
M: Alright, we’re back, so, uh, Catherine, are you a big beef or meat eater? +
C: Definitely am. It helps that, uh, my partner in crime is from Kansas City and they have 
the best among the best steaks in our entire country, in Kansas City. +
M: Really? +
C: Yeah. +
M: Wow. I actually miss, um… there was back in California we had the six dollar burger 
from Carl’s Jr. +
C: Ooh. +
M: It was just basically beef, bacon, cheese, which is like this huge burger with full of… of 
meat and obviously a lot of calories. +
C: Oh, yeah. +
M: Hehe. But it was delicious, I’m, uh… in Ecuador we are very used to having some meat 
product everyday with our food. +
C: Yeah, well, it’s the same in the Midwest, actually, from where we're from, um, the… 
it’s the same in the Mid West, because people in the Midwest generally think that if you not
eating meat, then what you’re eating? +
M: Hehe. +
C: Bread? +
M: Right. +
C: Corn? +
M: Yeah. +
C: So, uh… so meat is considered a healthy part of the day. And, uh, you definitely eat it 
with your meals. +
M: Yeah, and I’m sure all our vegetarian listeners might not appreciate this, but, you know, 
it’s just kind of different, uh, diet. Some people eat, for example, rice every day. +
C: Uhu +
M: So where in other countries you wouldn’t really have rice every day. Or, for example, 
when I was in Chile, I had a lot of potatoes. +
C: Really? +
M: A lot of potato. +
C: Have you ever had an Argentine steak? I heard they had the best beef in the world. +
M: They are not only delicious, but they are very inexpensive and it’s amazing. You can 
have a s… like a complete, um, steak buffet for like, I don’t know… I can’t remember, but
it was just… I sat there for three hours and couldn’t move and kept eating. +
C: Oh, my! +
M: Hehe. +
C: Yeah, was it… is it true you can eat it with a spoon? It’s so soft? +
M: Some of the meat is very, very tender. And not if it’s grilled, you can’t really do that, but 
in other preparations it’s almost like that. +
C: Mmm. With a nice butter sauce. Mmm, herbs. +
M: Alright, so… +
C: Making me hungry. +
M: I know, you’ve made me hungry. I think we’ve gotta take off and have some, uh, 
burgers, something like that. +
C: Hehe. +
M: Alright, so if you have any questions, any comments, please come to our website 
at englishpod.com and we’re there to answer any doubts. +
C: And we’d love to know what your favorite foods are, meat or otherwise, so post 
something on our website. +
M: Alright. +
C: Hope to see you there soon. +
M: Bye! +
C: Bye! 

  
