
= New Concept English book 4
:toc: .toc
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss0.css

'''

== Training elephants

Two main techniques have been used for training elephants, which we may call respectively the tough and the gentle. The former method simply consists of setting an elephant to work and beating him until he does what is expected of him. Apart from any moral considerations this is a stupid method of training, for it produces a resentful animal who at a later stage may well turn man-killer. The gentle method requires more patience in the early stages, but produces a cheerful, good-tempered elephant who will give many years of loyal service.

The first essential in elephant training is to assign to the animal a single mahout who will be entirely responsible for the job. Elephants like to have one master just as dogs do, and are capable of a considerable degree of personal affection. There are even stories of half-trained elephant calves who have refused to feed and pined to death when by some unavoidable circumstance they have been deprived of their own trainer. Such extreme cases must probably be taken with a grain of salt, but they do underline the general principle that the relationship between elephant and mahout is the key to successful training.

The most economical age to capture an elephant for training is between fifteen and twenty years, for it is then almost ready to undertake heavy work and can begin to earn its keep straight away. But animals of this age do not easily become subservient to man, and a very firm hand must be employed in the early stages. The captive elephant, still roped to a tree, plunges and screams every time a man approaches, and for several days will probably refuse all food through anger and fear. Sometimes a tame elephant is tethered nearby to give the wild one confidence, and in most cases the captive gradually quietens down and begins to accept its food. The next stage is to get the elephant to the training establishment, a ticklish business which is achieved with the aid of two tame elephants roped to the captive on either side.

When several elephants are being trained at one time, it is customary for the new arrival to be placed between the stalls of two captives whose training is already well advanced. It is then left completely undisturbed with plenty of food and water so that it can absorb the atmosphere of its new home and see that nothing particularly alarming is happening to its companions. When it is eating normally, its own training begins. The trainer stands in front of the elephant holding a long stick with a sharp metal point. Two assistants, mounted on tame elephants, control the captive from either side, while others rub their hands over his skin to the accompaniment of a monotonous and soothing chant. This is supposed to induce pleasurable sensations in the elephant, and its effects are reinforced by the use of endearing epithets, such as 'ho! my son', or 'ho! my father', or 'my mother', according to the age and sex of the captive. The elephant is not immediately susceptible to such blandishments, however, and usually lashes fiercely with its trunk in all directions. These movements are controlled by the trainer with the metal-pointed stick, and the trunk eventually becomes so sore that the elephant curls it up and seldom afterwards uses it for offensive purposes.

'''

== Recording an earthquake

An earthquake comes like a thief in the night, without warning. It was necessary, therefore, to invent instruments that neither slumbered nor slept. Some devices were quite simple. One, for instance, consisted of rods of various lengths and thicknesses which would stand up on end like ninepins. When a shock came, it shook the rigid table upon which these stood. If it were gentle, only the more unstable rods fell. If it were severe, they all fell. Thus the rods, by falling, and by the direction in which they fell, recorded for the slumbering scientist the strength of a shock that was too weak to waken him, and the direction from which it came.

But instruments far more delicate than that were needed if any really serious advance was to be made. The ideal to be aimed at was to devise an instrument that could record with a pen on paper, the movements of the ground or of the table as the quake passed by. While I write my pen moves, but the paper keeps still. With practice, no doubt, I could in time learn to write by holding the pen still while the paper moved. That sounds a silly suggestion, but that was precisely the idea adopted in some of the early instruments (seismometers) for recording earthquake waves. But when table, penholder and paper are all moving, how is it possible to write legibly? The key to a solution of that problem lay in an everyday observation. Why does a person standing in a bus or train tend to fall when a sudden start is made? It is because his feet move on, but his head stays still. A simple experiment will help us a little further. Tie a heavy weight at the end of a long piece of string. With the hand held high in the air, hold the string so that the weight nearly touches the ground. Now move the hand to and fro and around but not up and down. It will be found that the weight moves but slightly or not at all. Imagine a pen attached to the weight in such a way that its point rests upon a piece of paper on the floor. Imagine an earthquake shock shaking the floor, the paper, you and your hand. In the midst of all this movement, the weight and the pen would be still. But as the paper moved from side to side under the pen point, its movement would be recorded in ink upon its surface. It was upon this principle that the first instruments were made, but the paper was wrapped round a drum which rotated slowly. As long as all was still, the pen drew a straight line, but while the drum was being shaken, the line that the pen was drawing wriggled from side to side. The apparatus thus described, however, records only the horizontal component of the wave movement, which is, in fact, much more complicated. If we could actually see the path described by a particle, such as a sand grain in the rock, it would be more like that of a bluebottle buzzing round the room; it would be up and down, to and fro and from side to side. Instruments have been devised and can be so placed that all three elements can be recorded in different graphs.

When the instrument is situated at more than 700 miles from the earthquake centre, the graphic record shows three waves arriving one after the other at short intervals. The first records the arrival of longitudinal vibrations. The second marks the arrival of transverse vibrations which travel more slowly and arrive several minutes after the first. These two have travelled through the earth. It was from the study of these that so much was learnt about the interior of the earth. The third, or main wave, is the slowest and has travelled round the earth through the surface rocks.

'''

== Are there strangers in space?

We must conclude from the work of those who have studied the origin of life, that given a planet only approximately like our own, life is almost certain to start. Of all the planets in our own solar system, we are now pretty certain the Earth is the only one on which life can survive. Mars is too dry and poor in oxygen, Venus far too hot, and so is Mercury, and the outer planets have temperatures near absolute zero and hydrogen-dominated atmospheres. But other suns, stars as the astronomers call them, are bound to have planets like our own, and as the number of stars in the universe is so vast, this possibility becomes virtual certainty. There are one hundred thousand million stars in our own Milky Way alone, and then there are three thousand million other Milky Ways, or galaxies, in the universe. So the number of stars that we know exist is now estimated at about 300 million million million.

Although perhaps only 1 per cent of the life that has started somewhere will develop into highly complex and intelligent patterns, so vast is the number of planets, that intelligent life is bound to be a natural part of the universe.

If then we are so certain that other intelligent life exists in the universe, why have we had no visitors from outer space yet? First of all, they may have come to this planet of ours thousands or millions of years ago, and found our then prevailing primitive state completely uninteresting to their own advanced knowledge. Professor Ronald Bracewell, a leading American radio astronomer, argued in Nature that such a superior civilization, on a visit to our own solar system, may have left an automatic messenger behind to await the possible awakening of an advanced civilization. Such a messenger, receiving our radio and television signals, might well re-transmit them back to its home-planet, although what impression any other civilization would thus get from us is best left unsaid.

But here we come up against the most difficult of all obstacles to contact with people on other planets—the astronomical distances which separate us. As a reasonable guess, they might, on an average, be 100 light years away. (A light year is the distance which light travels at 186,000 miles per second in one year, namely 6 million million miles.) Radio waves also travel at the speed of light, and assuming such an automatic messenger picked up our first broadcasts of the 1920's, the message to its home planet is barely halfway there. Similarly, our own present primitive chemical rockets, though good enough to orbit men, have no chance of transporting us to the nearest other star, four light years away, let alone distances of tens or hundreds of light years.

Fortunately, there is a 'uniquely rational way' for us to communicate with other intelligent beings, as Walter Sullivan has put it in his excellent book, We Are not Alone. This depends on the precise radio frequency of the 21-cm wavelength, or 1420 megacycles per second. It is the natural frequency of emission of the hydrogen atoms in space and was discovered by us in 1951; it must be known to any kind of radio astronomer in the universe.

Once the existence of this wave-length had been discovered, it was not long before its use as the uniquely recognizable broadcasting frequency for interstellar communication was suggested. Without something of this kind, searching for intelligences on other planets would be like trying to meet a friend in London without a pre-arranged rendezvous and absurdly wandering the streets in the hope of a chance encounter.

'''

== Patterns of culture

Custom has not commonly been regarded as a subject of any great moment. The inner workings of our own brains we feel to be uniquely worthy of investigation, but custom, we have a way of thinking, is behaviour at its most commonplace. As a matter of fact, it is the other way around. Traditional custom, taken the world over, is a mass of detailed behaviour more astonishing than what any one person can ever evolve in individual actions, no matter how aberrant. Yet that is a rather trivial aspect of the matter. The fact of first-rate importance is the predominant role that custom plays in experience and in belief, and the very great varieties it may manifest.

No man ever looks at the world with pristine eyes. He sees it edited by a definite set of customs and institutions and ways of thinking. Even in his philosophical probings he cannot go behind these stereotypes; his very concepts of the true and the false will still have reference to his particular traditional customs. John Dewey has said in all seriousness that the part played by custom in shaping the behaviour of the individual, as against any way in which he can affect traditional custom, is as the proportion of the total vocabulary of his mother tongue against those words of his own baby talk that are taken up into the vernacular of his family. When one seriously studies the social orders that have had the opportunity to develop autonomously, the figure becomes no more than an exact and matter-of-fact observation. The life history of the individual is first and foremost an accommodation to the patterns and standards traditionally handed down in his community. From the moment of his birth, the customs into which he is born shape his experience and behaviour. By the time he can talk, he is the little creature of his culture, and by the time he is grown and able to take part in its activities, its habits are his habits, its beliefs his beliefs, its impossibilities his impossibilities. Every child that is born into his group will share them with him, and no child born into one on the opposite side of the globe can ever achieve the thousandth part. There is no social problem it is more incumbent upon us to understand than this of the role of custom. Until we are intelligent as to its laws and varieties, the main complicating facts of human life must remain unintelligible.

The study of custom can be profitable only after certain preliminary propositions have been accepted, and some of these propositions have been violently opposed. In the first place, any scientific study requires that there be no preferential weighting of one or another of the items in the series it selects for its consideration. In all the less controversial fields, like the study of cacti or termites or the nature of nebulae, the necessary method of study is to group the relevant material and to take note of all possible variant forms and conditions. In this way, we have learned all that we know of the laws of astronomy, or of the habits of the social insects, let us say. It is only in the study of man himself that the major social sciences have substituted the study of one local variation, that of Western civilization.

Anthropology was by definition impossible, as long as these distinctions between ourselves and the primitive, ourselves and the barbarian, ourselves and the pagan, held sway over people's minds. It was necessary first to arrive at that degree of sophistication where we no longer set our own belief against our neighbour's superstition. It was necessary to recognize that these institutions which are based on the same premises, let us say the supernatural, must be considered together, our own among the rest.

'''

== Of men and galaxies

In man's early days, competition with other creatures must have been critical. But this phase of our development is now finished. Indeed, we lack practice and experience nowadays in dealing with primitive conditions. I am sure that, without modern weapons, I would make a very poor show of disputing the ownership of a cave with a bear, and in this I do not think that I stand alone. The last creature to compete with man was the mosquito. But even the mosquito has been subdued by attention to drainage and by chemical sprays.

Competition between ourselves, person against person, community against community, still persists, however; and it is as fierce as it ever was.

But the competition of man against man is not the simple process envisioned in biology. It is not a simple competition for a fixed amount of food determined by the physical environment, because the environment that determines our evolution is no longer essentially physical. Our environment is chiefly conditioned by the things we believe. Morocco and California are bits of the Earth in very similar latitudes, both on the west coasts of continents with similar climates, and probably with rather similar natural resources. Yet their present development is wholly different, not so much because of different people even, but because of the different thoughts that exist in the minds of their inhabitants. This is the point I wish to emphasize. The most important factor in our environment is the state of our own minds.

It is well known that where the white man has invaded a primitive culture, the most destructive effects have come not from physical weapons but from ideas. Ideas are dangerous. The Holy Office knew this full well when it caused heretics to be burned in days gone by. Indeed, the concept of free speech only exists in our modern society because when you are inside a community, you are conditioned by the conventions of the community to such a degree that it is very difficult to conceive of anything really destructive. It is only someone looking on from outside that can inject the dangerous thoughts. I do not doubt that it would be possible to inject ideas into the modern world that would utterly destroy us. I would like to give you an example, but fortunately I cannot do so. Perhaps it will suffice to mention the nuclear bomb. Imagine the effect on a reasonably advanced technological society, one that still does not possess the bomb, of making it aware of the possibility, of supplying sufficient details to enable the thing to be constructed. Twenty or thirty pages of information handed to any of the major world powers around the year 1925 would have been sufficient to change the course of world history. It is a strange thought, but I believe a correct one, that twenty or thirty pages of ideas and information would be capable of turning the present-day world upside down, or even destroying it. I have often tried to conceive of what those pages might contain, but of course I cannot do so because I am a prisoner of the present-day world, just as all of you are. We cannot think outside the particular patterns that our brains are conditioned to, or, to be more accurate, we can think only a very little way outside, and then only if we are very original.

'''

==  Hobbies

A gifted American psychologist has said, 'Worry is a spasm of the emotion; the mind catches hold of something and will not let it go.' It is useless to argue with the mind in this condition. The stronger the will, the more futile the task. One can only gently insinuate something else into its convulsive grasp. And if this something else is rightly chosen, if it is really attended by the illumination of another field of interest, gradually, and often quite swiftly, the old undue grip relaxes and the process of recuperation and repair begins.

The cultivation of a hobby and new forms of interest is therefore a policy of the first importance to a public man. But this is not a business that can be undertaken in a day or swiftly improvised by a mere command of the will. The growth of alternative mental interests is a long process. The seeds must be carefully chosen; they must fall on good ground; they must be sedulously tended, if the vivifying fruits are to be at hand when needed.

To be really happy and really safe, one ought to have at least two or three hobbies, and they must all be real. It is no use starting late in life to say: 'I will take an interest in this or that.' Such an attempt only aggravates the strain of mental effort. A man may acquire great knowledge of topics unconnected with his daily work, and yet get hardly any benefit or relief. It is no use doing what you like; you have got to like what you do. Broadly speaking, human beings may be divided into three classes: those who are toiled to death, those who are worried to death, and those who are bored to death. It is no use offering the manual labourer, tired out with a hard week's sweat and effort, the chance of playing a game of football or baseball on Saturday afternoon. It is no use inviting the politician or the professional or business man, who has been working or worrying about serious things for six days, to work or worry about trifling things at the weekend.

As for the unfortunate people who can command everything they want, who can gratify every caprice and lay their hands on almost every object of desire—for them a new pleasure, a new excitement is only an additional satiation. In vain they rush frantically round from place to place, trying to escape from avenging boredom by mere clatter and motion. For them discipline in one form or another is the most hopeful path.

It may also be said that rational, industrious, useful human beings are divided into two classes: first, those whose work is work and whose pleasure is pleasure; and secondly, those whose work and pleasure are one. Of these the former are the majority. They have their compensations. The long hours in the office or the factory bring with them as their reward, not only the means of sustenance, but a keen appetite for pleasure even in its simplest and most modest forms. But Fortune's favoured children belong to the second class. Their life is a natural harmony. For them the working hours are never long enough. Each day is a holiday, and ordinary holidays, when they come, are grudged as enforced interruptions in an absorbing vocation. Yet to both classes, the need of an alternative outlook, of a change of atmosphere, of a diversion of effort, is essential. Indeed, it may well be that those whose work is their pleasure are those who most need the means of banishing it at intervals from their minds.

'''

==  The great escape

Economy is one powerful motive for camping, since after the initial outlay upon equipment, or through hiring it, the total expense can be far less than the cost of hotels. But, contrary to a popular assumption, it is far from being the only one, or even the greatest. The man who manoeuvres carelessly into his twenty pounds' worth of space at one of Europe's myriad permanent sites may find himself bumping a Bentley. More likely, Ford Escort will be hub to hub with Renault or Mercedes, but rarely with bicycles made for two.

That the equipment of modern camping becomes yearly more sophisticated is an entertaining paradox for the cynic, a brighter promise for the hopeful traveller who has sworn to get away from it all. It also provides—and some student sociologist might care to base his thesis upon the phenomenon—an escape of another kind. The modern traveller is often a man who dislikes the Splendide and the Bellavista, not because he cannot afford, or shuns their material comforts, but because he is afraid of them. Affluent he may be, but he is by no means sure what to tip the doorman or the chambermaid. Master in his own house, he has little idea of when to say boo to a maître d'hôtel.

From all such fears camping releases him. Granted, a snobbery of camping itself, based upon equipment and techniques, already exists; but it is of a kind that, if he meets it, he can readily understand and deal with. There is no superior 'they' in the shape of managements and hotel hierarchies to darken his holiday days.

To such motives, yet another must be added. The contemporary phenomenon of car worship is to be explained not least by the sense of independence and freedom that ownership entails. To this pleasure camping gives an exquisite refinement.

From one's own front door to home or foreign hills or sands and back again, everything is to hand. Not only are the means of arriving at the holiday paradise entirely within one's own command and keeping, but the means of escape from holiday hell (if the beach proves too crowded, the local weather too inclement) are there, outside—or, as likely, part of—the tent.

Idealists have objected to the practice of camping, as to the package tour, that the traveller abroad thereby denies himself the opportunity of getting to know the people of the country visited. Insularity and self-containment, it is argued, go hand in hand. The opinion does not survive experience of a popular Continental camping place. Holiday hotels tend to cater for one nationality of visitors especially, sometimes exclusively. Camping sites, by contrast, are highly cosmopolitan. Granted, a preponderance of Germans is a characteristic that seems common to most Mediterranean sites; but as yet there is no overwhelmingly specialized patronage. Notices forbidding the open-air drying of clothes, or the use of water points for car washing, or those inviting 'our camping friends' to a dance or a boat trip are printed not only in French or Italian or Spanish, but also in English, German and Dutch. At meal times the odour of sauerkraut vies with that of garlic. The Frenchman's breakfast coffee competes with the Englishman's bacon and eggs.

Whether the remarkable growth of organized camping means the eventual death of the more independent kind is hard to say. Municipalities naturally want to secure the campers' site fees and other custom. Police are wary of itinerants who cannot be traced to a recognized camp boundary or to four walls. But most probably it will all depend upon campers themselves: how many heath fires they cause; how much litter they leave; in short, whether or not they wholly alienate landowners and those who live in the countryside. Only good scouting is likely to preserve the freedoms so dear to the heart of the eternal Boy Scout.

'''

== Planning a share portfolio

There is no shortage of tipsters around offering 'get-rich-quick' opportunities. But if you are a serious private investor, leave the Las Vegas mentality to those with money to fritter. The serious investor needs a proper 'portfolio'—a well-planned selection of investments, with a definite structure and a clear aim. But exactly how does a newcomer to the stock market go about achieving that?

Well, if you go to five reputable stock brokers and ask them what you should do with your money, you're likely to get five different answers—even if you give all the relevant information about your age, family, finances and what you want from your investments. Moral? There is no one 'right' way to structure a portfolio. However, there are undoubtedly some wrong ways, and you can be sure that none of our five advisers would have suggested sinking all (or perhaps any) of your money into Periwigs.

So what should you do? We'll assume that you have sorted out the basics—like mortgages, pensions, insurance and access to sufficient cash reserves. You should then establish your own individual aims. These are partly a matter of personal circumstances, partly a matter of psychology.

For instance, if you are older you have less time to recover from any major losses, and you may well wish to boost your pension income. So preserving your capital and generating extra income are your main priorities. In this case, you'd probably construct a portfolio with some shares (but not high risk ones), along with gilts, cash deposits, and perhaps convertibles or the income shares of split capital investment trusts.

If you are younger, and in a solid financial position, you may decide to take an aggressive approach—but only if you're blessed with a sanguine disposition and won't suffer sleepless nights over share prices. If you recognize yourself in this description, you might include a couple of heady growth stocks in your portfolio, alongside your more pedestrian investments. Once you have decided on your investment aims, you can then decide where to put your money. The golden rule here is spread your risk—if you put all of your money into Periwigs International, you're setting yourself up as a hostage to fortune.

'''