= 0167
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 167, “A Marriage Proposal (Part II).”
This is English as a Second Language Podcast episode number 167. I'm your host, Dr. Jeff McQuillan coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This is the second part of our two-part podcast on a man asking a woman to marry him. Let's get started.
I had been stressing out about it for a couple of weeks. How do I ask my girlfriend to marry me? We were getting some dinner at a fast food restaurant before going to the movies.
Fiona: Tell me the truth. What's up with you lately?
Doug: Me? Nothing. Why do you ask?
Fiona: You haven't been yourself. You've been quiet and distant. Are you seeing someone else?
Doug: No, of course I'm not! I would never cheat on you.
Fiona: Then, do you want to break up with me?
Doug: No way! That's the last thing I want to do. You've got it all wrong.
Fiona: Then tell me what's on your mind.
Doug: I...well...it's just that...oh, I can't stand it anymore. I've been carrying around this ring in my pocket for two weeks, trying to get up the nerve to ask you. Fiona, will you marry me?
Fiona: Ah, I can't believe it! Are you serious?
Doug: I've never been more serious. This wasn't the way I wanted to ask you, but will you?
Fiona: Yes, I'll marry you! And I thought you wanted to break up.
Doug: No, I don't, silly! I want us to be together for the rest of our lives. Don't you know that?
We heard the conclusion, the second part of our podcast, “A Marriage Proposal.” The story begins by the man, whose name is Doug…he says he's been “stressing out” about something for a couple of weeks. “To stress out” about something means to be very nervous, to be anxious, to be worrying about something. Someone may say to you, “What are you stressed out about?” “Well, I'm stressed out about work or the homework I have to do for school.” This Doug is stressed out about asking his girlfriend to marry him. He doesn't know how to do that.
He says that he and his girlfriend were getting some dinner at a fast food restaurant before going to the movies. A “fast food restaurant” is a restaurant, you probably know, that serves your food, gives you your food very quickly. Usually, you stand in line and order your food, and then they give it to you a few minutes later. This is very popular, of course, in the United States, restaurants like McDonald's, for example, are fast food restaurants.
They are at a fast food restaurant and they are going to a movie when Fiona, who is the woman, she says to Doug: “Tell me the truth. What's up with you lately?” “Tell me the truth” means “be honest with me,” tell me what is actually happening here. “What's up with you?” means “What is your problem?” It's always…it’s not just “what is happening?,” but “what is the problem that you are having?” If you say to someone, “what's up?,” you just mean what's happening, what's going on, how are you? But if you say, “What's up with you?” with that preposition “with,” “what's up with you?” or “what's up with him?” means what is their problem, there's something wrong. So, Fiona says, “What's up with you lately?,” meaning recently. And Doug says: “Me? Nothing. Why do you ask?” Fiona says that, “You haven't been yourself.” The expression “to be yourself” here means to be acting normal, to be doing things the way you normally do things. So, if someone says, “you haven't been yourself lately,” “you haven't been yourself this week,” they mean you've been acting different, there's something wrong, there's some problem.
Fiona says that Doug has been quiet and distant. To be “distant,” in referring to a person, we say “that person is very distant from me,” we mean that they are not very close, they're not very connected to that person. So, if you see two people, for example, and one of them is talking and the second person is looking out, not paying attention to the person talking to him, he's very distant from them. Well, a man and a woman in a romantic relationship, when they say “he's very distant” or “she's very distant” means that they are not very loving, they're not very connected. And this is the problem that Fiona has with Doug.
Finally, she says, “Are you seeing someone else?” To be “seeing someone” means to be dating someone, to be romantically involved with someone. So, Fiona is asking if Doug is seeing another woman, is dating another woman, in addition to her. That would not be very nice, Doug. Well, Doug says, “No, of course I'm not!” - absolutely not, no way. “I would never cheat on you.” To “cheat on someone” means that when you are dating them or married to them, you get involved romantically with another person. So, if you are married and you are cheating on your wife, that means you are having a romantic relationship with another woman, not your wife. And that is not a good idea, generally speaking, if you want to stay married, that is.
So, Fiona says, “Then, do you want to break up with me?” because Doug says he is not cheating on her and she asked “you want to “break up with me?” To “break up” (two words) with someone means that you stop your romantic relationship, you end your dating, you're no longer going to be boyfriend and girlfriend. That's also a noun, a “breakup.” When we say, “Oh, I had a bad breakup” means that I had a difficult time when my girlfriend and I stopped dating each other. Doug says, “No way!,” and of course, “no way” is an informal way, an informal method or manner, of saying no, absolutely not. He says, “That's the last thing I want to do,” meaning I don't want to do that at all. When someone says “that's the last thing I want to do” or “that's the last place I want to visit,” they don't mean really that they want to visit that after several other places or do that thing after several other things; they mean they don't want that at all. That's the last thing I want to do, I don't want to do that at all.
“You've got it all wrong,” Doug says to Fiona. “You've got it all wrong”…here, to “get it” means that you've understood it incorrectly, you haven't understood it, you haven't comprehended it. “You've got it all wrong” - you have the wrong idea. Fiona says, “Then tell me what's on your mind.” “On your mind” means what you are thinking. Tell me what you are thinking, tell me what's on your mind. Usually, when someone says, “Tell me what's on your mind,” they are saying, “It looks like you have a problem. Tell me about it.”
Well, Doug says, “I...well...it's just that...” - he's nervous, right? Of course, he starts to stumble over his words, we would say, to “stumble” means to fall. And “to stumble over your words” means that you speak without confidence, that you are nervous. Doug says, finally, “I can't stand it anymore.“ To “stand something” means to tolerate something, to put up with something, to accept something, to just say, “Okay, that I accept the situation. I accept the situation is okay.” That means to stand something. So, if you cannot stand something, means that you cannot tolerate it, that you won't accept it, that you don't want it to continue. Well, what Doug doesn't want to continue here is being nervous about asking her to marry him. He says, “I can't stand it anymore.” “I've been carrying around this ring” - to “carry around” means to have it with you, usually, when you're going many different places; it's the same really as to carry. “I've been carrying around this ring for two weeks trying to get up the nerve,” to get the confidence, “to ask you.”
And then, he says, “Fiona, will you marry me?” And Fiona says, “Ah, I can't believe it! Are you serious?” And Doug says, “I've never been more serious,” meaning “yes, I am very serious.” “This wasn't the way I wanted to ask you,” he says, “but will you?” - meaning, will you marry me? And Fiona, of course - because the story has to have a happy ending, right, this is Los Angeles, this is the home of Hollywood, where all the movies have a happy ending, well, sometimes and our story has a happy ending - says, “ Yes, I'll marry you! And I thought you wanted to break up,” meaning she has the wrong idea. Doug says, “No, I don't, silly!” “Silly” as a noun, means a person who is silly, to be silly means to be foolish. But, he's not insulting Fiona, he's not saying, “You're a fool!” It's more of an affectionate, a loving way that two people might refer to each other when the other person is saying something that is wrong. In this case, he says, “No, I don't, silly! I want us to be together for the rest of our lives. “
Now let's listen to the dialogue this time at a native rate of speech.
I had been stressing out about it for a couple of weeks. How do I ask my girlfriend to marry me? We were getting some dinner at a fast food restaurant before going to the movies.
Fiona: Tell me the truth. What's up with you lately?
Doug: Me? Nothing. Why do you ask?
Fiona: You haven't been yourself. You've been quiet and distant. Are you seeing someone else?
Doug: No, of course I'm not! I would never cheat on you.
Fiona: Then, do you want to break up with me?
Doug: No way! That's the last thing I want to do. You've got it all wrong.
Fiona: Then tell me what's on your mind.
Doug: I...well...it's just that...oh, I can't stand it anymore. I've been carrying around this ring in my pocket for two weeks, trying to get up the nerve to ask you. Fiona, will you marry me?
Fiona: Ah, I can't believe it! Are you serious?
Doug: I've never been more serious. This wasn't the way I wanted to ask you, but
will you?
Fiona: Yes, I'll marry you! And I thought you wanted to break up.
Doug: No, I don't, silly! I want us to be together for the rest of our lives. Don't you know that?
Today's story was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
to stress out – to be worried or concerned about something
* Stop stressing out about your driving test or you won’t pass.
fast food restaurant – a place that gives you your food in a very short amount of time
* He eats at a fast food restaurant for lunch everyday.
Tell me the truth – “Be honest with me;” usually used when you think the other person may try to hide something because it will hurt your feelings
* Tell me the truth. Do you think I have a good chance of getting the job?
What’s up with you lately? – used to ask about what change has taken place in someone’s behavior; usually indicates the person has a problem
* You seem tired all the time. What’s up with you lately?
haven’t been yourself – have not been acting the same as you normally do
*I’ve noticed that you haven’t been yourself the past month. You seem nervous all the time.
distant – not very friendly
* We have been good friends for years but she’s been distant ever since she got promoted.
to see someone else – to date someone else
* I’m convinced that he’s seeing someone else when I’m out of town.
to cheat on – to date someone else secretly while you are already married or have a boy/girlfriend
* He loves you too much to cheat on you with another woman.
to break up with – to end a romantic relationship; to stop being boyfriend and girlfriend
* I intend to break up with him before he breaks up with me.
No way! – absolutely not
* No way would I visit Minnesota again in the wintertime!
You’ve got it all wrong – you have misunderstood the situation
* I’m sure you’ll find out that you’ve got it all wrong and that they intended to give you the prize all along.
on your mind – worried about something, thinking about something
* I can see that you have something important on your mind.
can’t stand it – am not able to tolerate or put up with something
* My dogs can’t stand it when I don’t take them for a walk everyday.
silly – to be foolish, like a child
* People look very silly when they try to play children’s games.
Comprehension Questions
1. Doug wanted to:
a) ask his girlfriend to marry him in a fast food restaurant.
b) ask his girlfriend to marry him but to keep the ring for himself.
c) ask his girlfriend to marry him but didn’t intend to do it at the fast food restaurant.
2. Before Doug asked her to marry him, Fiona thought that:
a) Doug wanted to work at the fast food restaurant.
b) Doug wanted to break up with her.
c) Doug was very silly.
Answers at bottom.
What Else Does It Mean?
distant
The word “distant,” in this podcast, means not to be close to someone: “Ever since Dan found out that Emily got the promotion instead of him, he’s been very distant.” We can also use “distant” to refer to family relationships that are not close: “His grandmother is my grandfather’s sister so we are only distant cousins.” Or, “We have the same last name but I don’t think we are even distant relations.”
to break up with
In this podcast, the phrase “to break up with” someone means to no longer be someone’s boyfriend or girlfriend: “They broke up after dating for years.” But, the phrase “something/someone is breaking up” means that it is difficult to hear or see them, such as on the telephone: “I can’t hear you; you’re breaking up. Hang up and I’ll call you back.” Or, “I was watching the football game when the signal broke up and I didn’t get to watch the second half.”
Culture Note
More than half of all marriages in the United States today will end in a divorce; that is, the married couple will end their marriage and each person will become single again. That is one reason why some couples wait for a long time before getting married. Most U.S. states now have what are called “no fault” divorces. In a no fault divorce, both the man and the woman agree that they want to end their marriage, and that it isn’t just one person’s fault or responsibility. Married couples who want to get a divorce have to fill out legal forms and give them to the local government.
Of course, not everyone who gets married in the U.S. will get divorced! There are many couples who stay married for many years. After 25 years of marriage, these couples usually have a special celebration or party for their “silver” anniversary. After 50 years, they have another party called a “golden” anniversary.
Comprehension Answers
1 - c
2 - b