= 0187
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast Number 187, “Enjoying the Outdoors.”
This is English as a Second Language Podcast Episode 187. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. How are you today?
Today's podcast is called “Enjoying the Outdoors.” Let's go.
[Start of story]
My favorite time of year is the summer. I like being outdoors, doing anything from hiking to going to the beach. One thing about working in an office all week is that I don’t get much fresh air. With summer here, I plan to take full advantage.
Last week, I went to the beach with some friends. I was glad I brought sunscreen since it was a really hot day, and I’m sure I would have gotten a sunburn within 15 minutes! We set up our beach umbrella and beach chairs, and played some volleyball. A few of us went into the ocean for a swim, but most of my friends just lounged around on the sand.
This weekend, I’m going hiking. I stopped by the store and got some insect repellent. The last time I hiked in the mountains, I came back with big mosquito bites all over my legs. This time, I’m going to be prepared. I was going to try a new trail and I wasn’t going to let a few mosquitoes get in the way.
[End of story]
In this podcast we are enjoying the outdoors. The “outdoors,” which is all one word, is the same as “out of doors,” and both of those expressions mean to be outside of your house or outside of the building. When people say the outdoors, they often are referring to, or talking about, going to the beach, or going to a park, or going camping. That's all considered outdoors.
I say in the story here, which is definitely a fictional story, because I am not like the person in this story at all. I say my favorite time of year is summer. Well, that's true for me. “The time of year” is the same as the season, in this case. “My favorite time of year is the fall,” my favorite season is the fall. You can also talk about this if you are referring to, for example, Christmas time. “My favorite time of year is Christmas,” the weeks around the Christmas holiday, for example. I say that I like being outdoors doing, anything from going hiking to going to the beach. The expression, “anything from to,” “anything from X to Y,” “anything from hiking to going to the beach” means that you are talking about a variety, or a range of possibilities. There are many things you could do outdoors, and so the person in this story is giving some examples - anything from hiking to going to the beach.
“Hiking,” it comes from the verb “to hike,” and to hike is to walk, usually to walk out in a park or in a desert, I suppose, or in the mountains, to walk somewhere, often, to walk up and down a hill or a mountain. So, the person in this story, not me, likes to hike; I don't like to hike, but this person does. They also like going to the beach. I do like going to the “beach.” The beach is where the ocean or a lake meets the land, where you have area right by the lake, or right by an ocean, is the beach. I live about two miles from Santa Monica Beach, here in California.
The person in the story says, “One thing about working in an office all week is that I don’t get much fresh air.” The expression here, “all week,” is the same as the entire week. You're trying to emphasize the length of time here. So one thing about working in an office during the week, or the entire week, or all week is that “I don't get much fresh air.” “Fresh air,” two words, is being outside, is the…is going outside, and when we say something is fresh, we mean it's either new or it is in a very original or pure state. In this case, the expression, fresh air, means being able to breathe the air outside.
Here, in Los Angeles, breathing the air outside is not always a good thing because there's so much pollution, but we'll go with the story here. He wants to go outside to get some fresh air. “With summer here,” he says, “I plan to take full advantage.” “To take advantage,” or “to take full advantage,” advantage is “advantage,” means to enjoy, to get the most that you can out of an experience. “I'm going to take advantage of the weekend to watch a lot of movies,” I'm going to use my time well, I'm going to use it so that I can get the most out of it, or the most, in this case, enjoyment out of it. There's another expression, “to take advantage of (someone),” that has a negative meaning. When you say, “I'm going to take advantage of a person,” that can also mean that you are going to get something from them, more than what you should, something that isn't fair, from that person. For example, “I'm going to take advantage of our friendship and ask you to give your car for this afternoon,” to let me use your car. To take advantage of means I'm going to use my friendship to get something more than I should, so it has a negative meaning. The positive meaning, in this story here, means to enjoy or make use of something, to make good use of something.
The story continues that, “Last week, I went to the beach with some friends. I was glad I brought sunscreen since it was a really hot day.” “Sunscreen,” one word, is the, usually, white liquid that you put on your arms and your legs, maybe your face, so that the sun doesn't make your skin red. For people like me, who come originally from northern Europe where the skin is very white, this is important because if I don't put sunscreen on when I go outside in the sun, after 15, 20 minutes, my skin becomes red and I look a little like a tomato. So I have to put on sunscreen when I go outside for a long period of time, and so does the person in this story. He was glad that he put on sunscreen since it was a really hot day, meaning that it was a sunny day; sun was out, you could see the sun. He says, “ I’m sure that I would have gotten a sunburn within 15 minutes,” means if he did not put on the sunscreen, he would have gotten a sunburn. “Sunburn,” is when your skin gets very red. Sometimes it gets so red that it begins to hurt you. That's a sunburn, or to get a sunburn. That's also a verb, to sunburn. Usually it's an expression, we say, “I got sunburned,” or “I was sunburned,” with an “ed” at the end.
The story says that the person went to the beach and they set up, or put up, their beach umbrella. An “umbrella” is something you use to keep the rain from hitting you. That would be a rain umbrella. A beach umbrella is something you use to keep the sun from hitting you, or from getting to you, so you can have “shade.” “Shade” is when you have something that blocks the sun, like an umbrella, and it's dark underneath. A beach chair is a kind of chair that you would use on a beach. Usually, these chairs are light and sometimes made of plastic. Usually, they are folding chairs. “Folding” means the chair collapses or becomes smaller, so you can carry it easily.
They also, in the story, “played some volleyball.” “Volleyball,” all one word, is when you have two teams, one on each side, and you have a “net” in between you, that's called a “volleyball net,” and you hit a little white ball back and forth over the net. That is the game of volleyball. I'm not a very good volleyball player. “A few of us,” according to the story, “went into the ocean.” An “ocean” is the same as the sea. I live near the Pacific Ocean. “We went in for a swim,” Here, swim is a noun. “To go for a swim,” “we went in for a swim” - these both mean to go swimming or to swim, we went swimming. “But most of my friends just lounged around in the sand.” “To lounge,” is a verb which means to relax, to sit, usually in a chair and not move, just to relax. The “sand” is what the beach is usually made of. It's, we hope, white or brown, and it's soft, and it is what you usually find near a ocean or a lake.
Well, this weekend, the story says, the person is going hiking. He says he “stopped by the store,” meaning he went to the store, “and he got,” or he bought, “some insect repellent.” “Insect” is a word which means the same as a bug or a fly, things that…little animals that fly around and can sometimes bite you, or cause a mark on your skin. A “repellent” is something that stops the insects, or the flies, from biting you, from biting your skin. Well, the last time this person went hiking in the mountains, he says, he came back, or returned, “with big mosquito bites.” A “mosquito” is a type of bug, a type of fly, a type of animal that likes to bite you, and after it bites you, you have a little red spot, a little red area on your skin from the mosquito taking a little of bit of blood from you. That's what they do when they bite you. When I lived in Minnesota, growing up, there were always lots of mosquitoes during the summertime, and I always had a lot of mosquito bites because the mosquitoes liked my blood, I think.
Well, in this story he says that he's going to be prepared this time. He wants to try a new “trail.” A “trail” is the same as a path or a little road that you can walk on, usually in a park or in the mountains there's a trail where other people have walked before, and that makes it easier for you to walk.
The story ends by the person saying that he “wasn't going to let a few mosquitoes “get in the way.” “To get in the way” here means to prevent you from doing something, to stop you from doing something. “Don't let that get in the way,” means don't let that stop you, don't let that prevent you from doing what you want to do.
Now let's listen to the story, this time at a native rate of speech.
[Start of story]
My favorite time of year is the summer. I like being outdoors, doing anything from hiking to going to the beach. One thing about working in an office all week is that I don’t get much fresh air. With summer here, I plan to take full advantage.
Last week, I went to the beach with some friends. I was glad I brought sunscreen since it was a really hot day, and I’m sure I would have gotten a sunburn within 15 minutes! We set up our beach umbrella and beach chairs, and played some volleyball. A few of us went into the ocean for a swim, but most of my friends just lounged around on the sand.
This weekend, I’m going hiking. I stopped by the store and got some insect repellent. The last time I hiked in the mountains, I came back with big mosquito bites all over my legs. This time, I’m going to be prepared. I was going to try a new trail and I wasn’t going to let a few mosquitoes get in the way.
[End of story]
Our script today was written by Dr. Lucy Tse. That's all we have time for now on this edition of ESL Podcast. Remember to visit our website for more information about our podcast, at eslpod.com. From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
time of year – a season in a year; a specific time of the year such as Christmas or summertime
* Winter is the time of the year to wear sweaters and coats.
outdoors – outside
* We had lunch outdoors because the weather was so nice.
anything from…to… – used to give a range of things, often to show a large variety
* I was willing to work all sorts of jobs as a teenager, anything from washing cars to painting houses.
hiking – a long walk, usually through places with a lot of plants and dirt like parks with hills and mountains
* We are planning to go hiking through the hills of Yosemite National Park this summer.
beach – a sandy area right next to a large amount of water such as a lake or ocean
* Everyone I know goes to the beach on summer vacation because it’s always cooler near the water.
fresh air – to be outside
* Lunchtime is always a good opportunity for some fresh air.
to take full advantage – to use as much as possible or every way possible
* Taking full advantage of my time off from work, I got up late every morning for an entire week.
sunscreen – a cream or lotion used to block the harmful parts of the sun’s light
* Many people use sunscreen to protect themselves from skin cancer.
sunburn – when your skin in red and painful because you have been in the sun too long
* She fell asleep for two hours at the beach yesterday and got a bad sunburn.
beach umbrella – a large umbrella people use at the beach for shade so that they’re not always in the sun
* He thought it was too hot and decided to stay under the beach umbrella most of the afternoon.
beach chairs – short, folding chairs that people use at the beach
* I reminded everyone to bring beach chairs so that we wouldn’t have to sit on the hot sand.
volleyball – a sport with a net high above the ground and two to four people on each side, where a ball is hit back and forth over the net and each side tries not to allow the ball to hit the ground
* She is a really good volleyball player. Does she want to join our team?
to swim – to move through water by moving parts of the body like arms and legs
* I learned how to swim when I was five, and since then, I have always liked swimming in a pool or in the ocean.
to lounge – to rest in a relaxed position
* After a very busy day at work, he went home and lounged in front of the TV until bedtime.
sand – very small and smooth pieces of rock that is seen on beaches and in deserts
* I like going to the beach, but I don’t like getting sand all over my clothes and things.
insect repellant – a cream or lotion to prevent a person from being bitten by insects or other little bugs
* She made sure to bring a bottle of insect repellant so that she wouldn’t get so many mosquito bites in the park.
mosquito bites – little, red, itchy bumps that people get from small insects that land on and cut the skin to suck tiny amounts of blood
* The mosquito bites he got last weekend from camping had him scratching his arms and legs all week long.
trail – a thin strip or piece of road for walking, usually away from main roads and busy highways
* The trail took us from one side of the campsite to another.
to get in the way – to have something that prevents someone from doing something
* People talking on cell phones in theatres get in the way of me enjoying a good show.
Comprehension Questions
1. The people on the beach did not:
a) set up beach chairs and play volleyball.
b) go for a swim in the ocean and lounge around on the sand.
c) finish some work they brought from the office.
2. What did the person in the story get at the store before going hiking?
a) sunscreen so that he wouldn’t get a sunburn
b) a volleyball to play volleyball
c) insect repellant so that he wouldn’t get bitten by mosquitoes
Answers at bottom.
What Else Does It Mean?
fresh air
The phrase “fresh air,” in this podcast, means the outdoors or the outside, usually of a building: “He watched T.V. until his mom told him to go outside and get some fresh air.” This means that he was inside, and his mother telling him to get some fresh air is a way of telling him to go outside. “Fresh air” can also be used to describe something new, or something different. You can describe something as a “breath of fresh air,” which means it is new and different: “He didn’t like his old boss, so getting a new job is like a breath of fresh air.” Or, “Moving to Atlanta after living in New York City for 10 years was a breath of fresh air.”
trail
In this podcast, the word “trail” is a noun which means a thin piece of road meant for walking or bicycling, away from majors roads and highways: “I like taking the bike trail because cars are not allowed on it.” “Trail” also has another meaning. A “trail” can mean traces or tracks, like footprints or pieces of information that can lead to a person or thing: “The police found a trail of evidence against the criminal.” Or, “I lost my dog, but by following his trail, I found her at my neighbor’s house.” The word can also be used as a verb, “to trail,” to mean to follow someone or something slowly: “I trailed his car for several miles so that I wouldn’t get lost in the mountains.”
Culture Note
CULTURE NOTE
National and state parks are good places to spend time outdoors. These parks are more common in the United States and Mexico than in other parts of the world, and are large areas of land protected and preserved by the federal government (called “national parks”) and state governments (called “state parks”) because of their natural beauty, importance in history, or importance to the environment. Both national and state parks are usually located in undeveloped places where there are no people, businesses, buildings, or cars. These areas often have “rare,” or not often found, animals, plants, and other parts of nature. Money to maintain them come from the national and state taxes, and from “admission fees,” or money people pay to enter.
National and state parks are popular “tourist attractions,” or places where visitors go. At these parks, you can look at the scenery, hike and camp, and do other things like go horseback riding and mountain climbing. Some of the most famous national parks in the U.S. are Yosemite National Park in California, Grand Canyon National Park in Arizona, Yellowstone National Park in the states of Wyoming, Montana, and Idaho, and Zion National Park in Utah.
Comprehension Answers
1 - c
2 - c