= 0706
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 706: Feeling Ill from Food While Traveling.
This is English as a Second Language Podcast episode 706. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode to help you improve your English – and your love life!
This episode is called “Feeling Ill (or sick) from Food While Traveling.” Sounds like fun! Let’s get started.
[start of dialogue]
Rumi: I’m as sick as a dog!
Hugo: It serves you right. I warned you not to eat food sold by food vendors on the street. Cleanliness is not a priority at some of those food stands.
Rumi: I’m not one to turn up my nose up at street food. On the street is where you’ll find the most authentic food, the food the locals eat. And plus, I have a stomach of steel.
Hugo: You had a stomach of steel, and there’s no way to guard against undercooked or contaminated food.
Rumi: Okay, you’re right.
Hugo: It’ll probably take days for whatever it is that’s making you sick to work itself out of your system. Some vacation!
Rumi: Just be grateful you’re not puking your guts out like I am.
Hugo: Believe me, I’m thanking my lucky stars.
[end of dialogue]
Rumi begins our dialogue by saying, “I’m as sick as a dog!” This is an old expression that means to be very sick, to be very ill: “I’m sick as a dog.” Hugo says, “It serves you right.” The expression or phrase “it serves you right” means that you deserve the negative consequences that you are suffering now; you did something wrong, and now you are paying the price. “It serves you right” implies that you did something wrong, and because you did something wrong now you are suffering. Hugo says, “I warned you’” – meaning I told you something bad would happen – “I warned you not to eat food sold by food vendors on the street.” A “vendor” (vendor) is anyone who sells something, but we usually use the term in talking about people selling things from small carts or just from their own pockets on the street; that’s one association of the word. A “food vendor” would be a person who’s selling food on the street, often from a truck or some small vehicle. Hugo says, “Cleanliness is not a priority at some of those food stands.” “Cleanliness” means very clean. He’s saying that some of the food vendors on the street aren’t very clean, and this is why Rumi is sick. He says it’s not a “priority,” meaning it’s not important to them.
He calls the food vendors “food stands.” The “stand” is actually the physical place where the person is selling the food. A “food stand” is small, a place where you have the person keeping the food or perhaps cooking the food, and then selling it to you. This happens in many cities, not in Los Angeles very much. But I know if you go, for example, to New York City there will be – or used to be, the last time I was there – people selling hot dogs on the streets for example. And many cities have this custom of selling food on the streets. Los Angeles has food trucks that go around and sell different kinds of food. Of course, Los Angeles is very much a car culture; that is, everyone has a car, and you can’t travel very easily without one. So logically, the food vendors have trucks rather than just stands on the street.
Rumi says, “I’m not one to turn up my nose up at street food.” The expression “to not turn your nose up at (something)” is a complicated way of saying that you don’t think that you are too good for something; you don’t think that you are better than someone or something. If you just say, “I’m a person who turns his nose up at taking the bus,” for example in Los Angeles, that means that you think you’re too good to do that, you are better than other people; you are superior, we would say. Rumi says she’s not someone who turns her nose up at street food. “On the street is where you’ll find the most authentic food,” she says, “the food that locals eat.” “Locals” means people who live in the area where you are visiting, not tourists; the opposite of a tourist would be a local. In Los Angeles, I’m a local. If you live in Tokyo, you are a local in Tokyo. Rumi says the street is where you find the most authentic food. “Authentic” means real, true, something that actually exists. In this case, really the best food, the food that is most like what people in that area or city eat. “And plus,” Rumi says, “I have a stomach of steel.” “To have a stomach of steel,” or simply a “steel stomach,” means that you can eat almost anything and not get sick.
Hugo says, “You had a stomach of steel.” He’s using the verb in the past tense, saying well, maybe you used to in the past but not anymore. He says, “there’s no way to guard against undercooked or contaminated food.” “To guard against (something)” means to protect yourself from something, to do something to prevent something bad from happening to you. The best way to guard yourself against getting sick is to always wash your hands before you eat. That’s just an example; that’s not always true of course, but it’s a good idea I think. Hugo says, “there’s no way to guard against undercooked food.” “Undercooked” food is not cooked enough; it’s food that needs to be cooked more. If it’s not cooked properly, some of the food could be “raw,” meaning uncooked, and some food is dangerous when it is uncooked. Pork, for example, the meat of a pig, is often unsafe when undercooked. “Contaminated” food is food that has something in it that is not food or that is dangerous. So for example, if we say the water is “contaminated,” we mean that there is something in the water that should not be there and that will make you sick if you drink it.
Rumi says, “Okay, you’re right,” meaning you are correct. Hugo says, “It’ll probably take days for whatever that is making you sick to work itself out of your system.” That’s a kind of complicated sentence. Hugo says it will take days – many days – for this thing that is making you sick, it’s going to take some time for that to work itself out of your system. “To work itself out of your system” means for your body to be no longer affected by it. Really, it’s another way of saying it will take a while for you to get better. Sometimes, sickness caused by a virus or by bacterial infection takes a while to work itself out of your system, so that you are no longer affected by it. Hugo says, “Some vacation!” Now, “some” is a common word in English, with many meanings, some of which you can find in our Learning Guide. Here, however, when used in an expression like this, it’s used to mean “not,” or “this is not,” or something that would be negative. For example, you are going to take a walk in the park, and suddenly it starts to rain; you might say, “Oh! Some walk!” meaning this is not a good walk. You’re saying that whatever follows the word “some” is bad or is not as good as you wanted it to be; it’s showing your disappointment. “Some wedding! The bride never showed up.” The “bride” is the woman who’s getting married. “Some wedding!” meaning, boy, that was a terrible wedding. In fact, it wasn’t even a wedding at all, because the bride did not go – which is always a problem if you’re getting married! Some advice from me, who is married, always make sure that the other person is also there to get married with you, because if they’re not, well, you’re going to have some problems!
Rumi says, “Just be grateful you’re not puking your guts out like I am.” “Just be grateful” means you should be thankful; you should think yourself fortunate that you are not “puking your guts out.” This is a rather ugly phrase; “to puke” (puke) means to vomit, to throw up, when the food that was in your stomach suddenly goes out your mouth the wrong way. Your “guts” are a general way of referring to your stomach or the lower part of your abdomen. The expression means to be sick a lot, to be vomiting a lot.
Hugo says, “Believe me, I’m thanking my lucky stars.” This is an old expression; “to thank your lucky stars” means to be very grateful for something, to be very appreciative, to be in this case happy that something bad did not happen to you. Remember that song, I think it was from the 70s? “And I thank my lucky stars that you are who you are and not just another…(something something) come to break my heart” – something like that. Remember that? No?
Okay, now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Rumi: I’m as sick as a dog!
Hugo: It serves you right. I warned you not to eat food sold by food vendors on the street. Cleanliness is not a priority at some of those food stands.
Rumi: I’m not one to turn up my nose up at street food. On the street is where you’ll find the most authentic food, the food the locals eat. And plus, I have a stomach of steel.
Hugo: You had a stomach of steel, and there’s no way to guard against undercooked or contaminated food.
Rumi: Okay, you’re right.
Hugo: It’ll probably take days for whatever it is that’s making you sick to work itself out of your system. Some vacation!
Rumi: Just be grateful you’re not puking your guts out like I am.
Hugo: Believe me, I’m thanking my lucky stars.
[end of dialogue]
We thank our lucky stars that we have the wonderful Dr. Lucy Tse to write our scripts. By the way, the song that I was thinking of, that’s James Taylor, “Your Smiling Face,” 1977. I know, you probably didn’t care!
From Los Angeles, California, we do care, and I thank you for listening. I know it’s been a weird episode, but I’m hoping that you’ll come back and listen to us again soon here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
sick as a dog – very sick; very ill; with many physical symptoms of not being healthy or well
* After eating an entire bag of cookies, Hank felt sick as a dog.
it serves you right – a phrase used when one feels another person deserves the negative consequences of his or her actions; a phrase used to show that one has no sympathy for the bad things another person is experiencing, because one believes they are the result of his or her own actions
* It serves you right that you lost your job. You shouldn’t have stolen money from your employer.
to warn – to tell someone about the negative consequences that may happen if things do not change; to alert someone to a danger or problem that may or will occur
* The instruction manual warned us not to turn on the coffeemaker before reading all the instructions.
food vendor – a person or small business that sells food, usually in a small, wheeled cart or truck on the street or sidewalk
* Some of the best hot dogs in New York City are sold by food vendors, not in restaurants.
cleanliness – the state of being clean, sanitary, hygienic, and orderly; the state of not being dirty
* When we went into Abbe’s apartment, we saw rats in the kitchen and cockroaches in the bathroom. It was clear that cleanliness is not very important to her.
stand – a booth where things are sold, especially when the building is temporary (not permanent) and can be moved easily
* When they go to the carnival, the first thing they did was to look for the food stands selling cotton candy.
to turn up (one’s) nose up at – to act as if one is better than or superior to something and does not want or need it; to think something is not good enough for oneself
* If you were really hungry, you wouldn’t turn up your nose at the food your parents serve. Instead, you’d eat whatever was available.
authentic – real; true; something that actually exists
* Is that an authentic Gucci purse?
stomach of steel – a phrase referring to one’s ability to eat almost anything without getting sick, regardless of how unhealthy, unclean, or unusual it is
* You must have a stomach of steel to be able to eat fried chicken, creamy pasta, and spicy beef in a single meal!
to guard against – to protect oneself from something; to take precautions against something or to prevent something from happening
* The doctor said that the best way to guard against infection is to wash our hands after using the bathroom and before eating.
undercooked – not cooked enough; not cooked thoroughly; cooked, but without having reached a safe temperature at which all the bacteria are killed
* If the pork is pink, it’s probably undercooked and we shouldn’t eat it.
contaminated – not clean or pure; with some harmful or dangerous substance mixed in
* That water is contaminated! We shouldn’t drink it without boiling it first.
to work itself out of (one’s) system – for a virus or bacterial infection to stop affecting one’s body and stop making one ill; for one’s body to get rid of an illness or infection
* The doctor said I should stay in bed for a few days until the flu works itself out of my system.
some – a word used to emphasize that something is not what it should be, or that it is the opposite of what it should be
* Some wedding! The groom never showed up and the bride just cried and cried.
to puke (one’s) guts out – to vomit, throw up, or regurgitate a lot
* If Oliver keeps drinking this much, he’ll start puking his guts out in front of all his friends.
to thank (one’s) lucky stars – to be grateful for something; to be appreciative of someone or something; to be glad, happy, and relieved that something has happened in a particular way
* She thanks her lucky stars that she was late that morning and didn’t ride her regular bus, which was in an accident that day.
Comprehension Questions
1. Why did Rumi want to eat at the food stands?
a) Because it was cheaper than the food in restaurants.
b) Because it is usually better than other types of food.
c) Because it is more typical of the types of food eaten in that area.
2. What is wrong with Rumi?
a) She has a fever.
b) She is vomiting.
c) She needs surgery.
Answers at bottom.
What Else Does It Mean?
to guard against
The phrase “to guard against,” in this podcast, means to protect oneself from something: “For many people, cutting up their credit cards is the best way to guard against overspending.” The verb “to guard” can mean to protect a person or object by standing near it and looking for threats: “How many people guard the Queen’s jewels?” In a prison, the verb “to guard” means to watch over a prisoner so that he or she cannot escape: “The most dangerous criminals are sometimes guarded by several police officers.” A “security guard” is a person whose job is to protect a building and/or control who can enter that building: “When you arrive at the front desk, just tell the security guard you’re here to see me.”
some
In this podcast, the word “some” is used to emphasize that something is not what it should be, or that it is the opposite of what it should be: “Some job! As a restaurant reviewer, she gets paid to travel and eat!” The word “some” can also describe something that was very good or impressive: “That’s some car you’re driving! How much did it cost?” Sometimes the word “some” can be used to mean that something is large or significant in size: “Wow, that’s some hamburger! Do you think you can eat it all by yourself?” Finally, the phrase “and then some” is used after a number to show that one thinks the real number is probably even bigger: “Top actors can earn one million dollars per episode of popular TV shows, and then some!”
Culture Note
Items Not Allowed to be Brought into the United States
U.S. Customs and Border Protection (CBP) is the part of the U.S. government that “secures” (keeps safe) the nation’s “borders” (geographic lines between countries). One of its responsibilities is to “restrict” (put limits on) what can be brought into the United States from other countries, including food.
CBP “confiscates” (takes away) any “agricultural items” that travelers bring into the country. This is because “plant and animal products” (things made from plants and animals) might carry “pests” (insects or fungi that damage or kill certain plants) or diseases that could “wreak havoc” (create serious problems) if they “came into contact with” (touched) U.S. agriculture.
Specifically, travelers are not allowed to bring in any fresh meat, fruits, vegetables, or plants. Normally “processed” (changed and packaged) foods are allowed. For example, travelers can usually bring “jerky” (dried meat), but not “raw” (uncooked) meat. “Likewise” (similarly), they can usually bring a package of dried apples, a jar of apple butter, or canned applesauce, but not fresh apples.
Travelers are expected to “declare” (officially state) any agricultural products that they are bringing into the country. They do this by writing the information down on the back of the “customs form” travelers must fill out when they enter the country. Some travelers’ “bags” (luggage) will be selected for inspection, where CBP “officials” (government employees) look for “prohibited” (not allowed) items. If they find “undeclared” (not listed) agricultural products, the traveler may be “fined” (forced to pay money as a punishment).
Comprehension Answers
1 - c
2 - b