= 0709
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 709: Taking Someone for Granted.
This is English as a Second Language Podcast episode 709. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You probably know that, but did you know that we rely on – we count on your support to keep us going. Please consider becoming a member of ESL Podcast by going to our website today.
This episode is a conversation between Phil and Cameron; Cameron is the woman in the dialogue. It’s about taking someone for granted, always a dangerous thing in a relationship. Let’s get started.
[start of dialogue]
Phil: Did you hear that Melissa has finally left Eric? It’s about time!
Cameron: Oh, that’s sad. It’s always sad when two people can’t make it work.
Phil: Well, it wasn’t for a lack of trying, on Melissa’s part. She bent over backwards trying to please Eric and he always took her for granted. If you ask me, Melissa was always too good for him.
Cameron: Really? I don’t know Eric too well, but he seemed nice.
Phil: Yeah, he’s nice on the surface, but he’s really a slimeball. Trust me, I know.
Cameron: I believe you, but what’s Melissa going to do now?
Phil: I think she should find a nice guy who’ll appreciate her.
Cameron: Someone like you?
Phil: She could do worse. I’d treat her right and make her happy.
Cameron: You sound like a man with a plan.
Phil: “Be prepared.” Isn’t that what the Boy Scouts say?
[end of dialogue]
Phil begins by saying to Cameron, “Did you hear that Melissa has finally left Eric? It’s about time!” “Did you hear,” meaning did someone tell you or did you have this information. The information is that Melissa – a girl, a woman – has finally left Eric. The expression “to leave (someone),” when we’re talking about a romantic relationship, is to end the relationship. Another way of saying this would be “to break up.” We often use “to break up” when we’re talking about two people ending their romantic connection – their romantic relationship, but you can also simply use the verb “to leave.” “To leave” has many other meanings, of course; those can be found – some of them – in our Learning Guide. Phil says, “It’s about time!” That’s a phrase to show that you are happy, you are relieved that something has finally happened; you would hoped it would happen earlier, but now finally it has happened. Phil is happy that Melissa has left Eric. Cameron says, “Oh, that’s sad. It’s always sad when two people can’t make it work.” “Make it work” means to try very hard to make something successful. You’ll often hear that when people are talking about relationships: “They couldn’t make it work,” meaning they tried but it was not possible for them to continue their relationship.
So, Cameron is sad. Phil says, “Well, it wasn’t for lack of trying, on Melissa’s part.” He’s saying that Melissa tried to make it work. The expression “not for a lack of trying” is used to mean that someone did try very hard; they did attempt to do something, especially something that was difficult or perhaps unpleasant. It’s almost always used in negative: “It’s not for a lack of trying that I was not able to visit my brother today.” I tried very hard. I drove many miles, but the weather was bad and I wasn’t able to arrive on time; but it was not for a lack of trying, meaning I tried very hard. Phil says that Melissa tried very hard also. He uses the expression “on Melissa’s part,” which means simply by Melissa. Phil says that Melissa bent over backwards to try to please Eric. “To bend over backwards” is an expression that means to do everything possible for something to happen, especially when you are trying to make things easier for another person. “Bent” is the past tense of the verb “to bend.” So, Melissa bent over backwards, she tried very hard to please Eric. “To please,” as a verb, means to make someone happy or to make someone satisfied. “Please” has other meanings as well, and some of those are in our Learning Guide for this episode.
Phil says that Eric took Melissa for granted. “To take (someone) for granted” means not to appreciate what another person is doing, to not appreciate his or her actions or behaviors, to not thank them, to not recognize that they are doing something for you. This is often something that might happen in a relationship: you take the other person for granted. Husbands, do not take your wives for granted, they will not be very happy – trust me, I know! So, Phil says that Eric took Melissa for granted. He says, “If you ask me (meaning if you want my opinion), Melissa was always too good for him.” When you say someone “is too good for” someone else, you mean that they are better than someone, that that other person was not as good as they are and that the other person did not deserve to be with this person that you think is too good for the other one. So, if Melissa is too good for Eric, that means that Eric is not as good a person as Melissa, and Melissa should try to find someone else.
Cameron says, “Really? I don’t know Eric too well, but he seemed nice.” Phil says, “Yeah, he’s nice on the surface, but he’s really a slimeball.” “On the surface” means related to how you seem at first, before you really understand the other person; another word we might use is “superficially.” It means that it appears that a person is one way, but once you get to know them better you realize that they aren’t that friendly, or they aren’t that nice, or they aren’t that smart, and so forth. Phil says that Eric is nice on the surface, but he’s really – he’s truly, actually – a slimeball. A “slimeball” (slimeball) is an informal word describing someone who you don’t want to spend a lot of time with because you don’t respect him; you don’t think that he’s a good person. He does bad things; he does tricky things; he does things in secret, perhaps, that are not very nice, or he’s not honest with the other person. It’s a very negative way to describe someone, usually a man, often used to talk about a man who is not nice to his romantic partners.
Phil says, “Trust me, I know.” Cameron says, “I believe you, but what’s Melissa going to do now?” Phil says, “I think she should find a nice guy who’ll appreciate her.” Phil thinks that Melissa should get a new romantic partner, someone who is a nice guy who will appreciate her. “To appreciate” is the opposite of “to take for granted. “To appreciate (someone)” is to recognize their good qualities, to value them, to let them know that you are happy, to thank them.
Cameron asks Phil, “Someone like you?” meaning should Melissa be your romantic partner. Phil says, “She could do worse.” This is an interesting expression. When you say someone “could do worse,” you’re talking about something that isn’t perfect, but it’s not bad, and it’s better than most other similar things. In this case, Phil is saying that he’s not perfect – he’s not the perfect person, but he’s a pretty good person, a good choice for Melissa. It’s often used to talk about romantic relationships; when you say that someone could do worse you mean that the person they are with isn’t perfect, but there are a lot of other people who are worse. Phil says, “I’d treat her right and make her happy.” I would treat Melissa right, meaning I would be kind, I would be appreciative, thoughtful, nice, considerate of this person; I would not do bad things to them.
Cameron says, “You sound like a man with a plan.” “A man with a plan” is someone who knows what he wants to do, who already has thought of things to do in order to accomplish what he wants to. Phil says, “‘Be prepared.’ Isn’t that what the Boy Scouts say?” “The Boy Scouts” is an organization that teaches young boys practical skills, values, and so forth. I was a Boy Scout, I think, when I was a young boy. The saying – the motto of the Boy Scouts – the expression that they use is “Be prepared,” meaning always be ready. In order to be prepared, of course, you have to work hard, you have to practice, you have to train, and those are some of the values that the Boy Scouts are supposed to teach the young boys. There’s also, of course, the Girl Scouts, which is a similar organization for young girls.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Phil: Did you hear that Melissa has finally left Eric? It’s about time!
Cameron: Oh, that’s sad. It’s always sad when two people can’t make it work.
Phil: Well, it wasn’t for a lack of trying, on Melissa’s part. She bent over backwards trying to please Eric and he always took her for granted. If you ask me, Melissa was always too good for him.
Cameron: Really? I don’t know Eric too well, but he seemed nice.
Phil: Yeah, he’s nice on the surface, but he’s really a slimeball. Trust me, I know.
Cameron: I believe you, but what’s Melissa going to do now?
Phil: I think she should find a nice guy who’ll appreciate her.
Cameron: Someone like you?
Phil: She could do worse. I’d treat her right and make her happy.
Cameron: You sound like a man with a plan.
Phil: “Be prepared.” Isn’t that what the Boy Scouts say?
[end of dialogue]
We never want to take our scriptwriter for granted. We appreciate what she does. That’s why we thank her on the end of every ESL Podcast. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
to leave (someone) – to choose to end a romantic relationship with another person, especially when that other person does not want to end the relationship
* Brian’s father left his mother when Brian was just three years old.
it’s about time – a phrase used to show that one is glad or relieved that something has finally happened, and that one wishes it had happened sooner
* It’s about time you asked your boss for a raise! You’ve been with the company for 10 years, and they’re still paying you the same salary.
to make (something) work – to try very hard to make something be successful, especially when talking about a relationship
* They tried to keep the restaurant open, but in the end they just couldn’t make it work and they had to close their business.
for a lack of trying – due to one’s unwillingness to try to do something that is difficult or unpleasant, usually used in the negative
* Nancy studied really hard, so if she fails the exam, it won’t be for a lack of trying.
on (someone’s) part – referring to one person’s involvement or participation in something, or to one person’s opinion or belief about something
* There were a lot of bad feelings on Liu’s part. He has never been able to forgive his sister for what she did.
to bend over backwards – to do everything possible to make something happen, especially to make something easier for another person
* The customer service representatives are fantastic! They always bend over backwards to solve their customers’ problems.
to please – to make someone happy or satisfied; to do or say something that another person will like
* Jessina always tried to please her parents by earning good grades in school.
to take (someone) for granted – to not appreciate another person and/or his or her actions and behaviors; to not recognize someone for the good things he or she does
* Don’t let your boss take you for granted! Make sure she knows just how much you contribute to the team.
too good for (someone) – superior to someone; better than someone
* Becca’s parents have always thought their daughter was too good for their son-in-law, and it has really affected Becca’s marriage.
on the surface – superficially; relating to how someone or something seems at first, before one really understands he, she, or it well
* Being a lawyer seems like a great career on the surface, but soon you realize how much stress it involves.
slimeball – someone who does bad, sneaky, tricky things and whom one does not want to spend time with because one does not respect him or her
* That guy is such a slimeball! He was dating three women at once, without letting them know it.
to appreciate (someone) – to value another person; to recognize the good qualities or characteristics of another person and let that person know that he or she is admired
* We really appreciate our employees, and we try to prove it to them by offering generous compensation and vacation leave.
to be able to do worse – a phrase used to talk about something that is not perfect, but is not bad and is actually better than many other similar things
* The job isn’t perfect, but he likes it and he could do worse.
to treat (someone) right – to be kind, thoughtful, and considerate toward another person, not abusing or mistreating him or her
* Our nonprofit organization tries to help women whose boyfriends or husbands don’t treat them right.
Boy Scouts – an organization that teaches boys practical skills, values, and strong morals as they grow up
* Sammy learned how to survive in the wilderness, tie knots, and start a fire while he was in the Boy Scouts.
Comprehension Questions
1. Why is Cameron sad that Melissa has left Eric?
a) Because they won’t be able to continue to work together.
b) Because she doesn’t like to see relationships end.
c) Because she thought they would get married.
2. What does Phil mean by saying that Melissa “bent over backwards trying to please Eric”?
a) She joined a gym and exercised to impress Eric.
b) She spent all her money to buy things for Eric.
c) She did everything she could to make Eric happy.
Answers at bottom.
What Else Does It Mean?
to leave
The verb “to leave,” in this podcast, means to choose to end a romantic relationship with another person, especially when that other person does not want to end the relationship: “What percentage of men leave their wife for a younger woman?” The phrase “to leave home” means to move out of one’s parents’ home: “In the past, many Americans left home when they were 18 years old.” The phrase “to leave well enough alone” means to stop trying to change a situation because its current state is acceptable: “Politicians need to learn to leave well enough alone and stop making more silly laws for us to follow.” Finally, the phrase “to leave it at that” is used to show that one will not continue to do more of something: “We’re about 80% done, so let’s leave it at that for today and finish the report tomorrow morning.”
to please
In this podcast, the verb “to please” means to make someone happy or satisfied, or to do or say something that another person will like: “It’s impossible to please Mr. Haftl! No matter what we say or do, he’s never content.” The phrase “if you please” is put on the end of a command to make it very polite and a little old-fashioned: “Close the window, if you please, so the cold air can’t get in.” The phrase “as (one) pleases” is used to talk about someone doing something the way he or she wants to do it, without considering how other people think it should be done: “Do you think parents should let their children do as they please, or should they control their children’s activities?”
Culture Note
Legal Separation
Sometime married couples who are having “marital” (related to marriage) trouble choose to “file for” (legally request) “legal separation” before they “divorce” (officially end a marriage). Sometimes the people who are legally separated are able to “reconcile” (reach agreement) and continue living together as husband and wife. Other people who are legally separated “end up” (ultimately) filing for divorce.
Legal separation is a helpful tool to allow a husband and wife to make the legal and financial “arrangements” (plans) that will “govern” (control) their divorce. For example, legal separation can help the husband and wife “establish” (determine) who will pay bills, who will “retain” (keep) “jointly owned” (owned by both people) property, and whether “alimony” (payments made by a former husband to his former wife, or by a former wife to her former husband) should be paid.
Legal separation can also be helpful in “deciding custody” (legally determining who will take care of the children after a marriage ends). In the legal separation, the court may determine where the children should live and who should pay their expenses.
Other people file for legal separation because they believe divorce is wrong, or because their church does not allow it. They do not want to continue to be married, but they are not willing to get a divorce, so legal separation is a “viable” (possible; acceptable) option.
In the United States, married couples can file for a legal separation in any state except Delaware, Florida, Georgia, Mississippi, Pennsylvania, and Texas.
Comprehension Answers
1 - b
2 - c