= 0721
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 721: A Widespread Epidemic.
This is English as a Second Language Podcast episode 721. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can become a member of ESL Podcast and download a Learning Guide for this episode, all on our wonderful website.
This episode is a dialogue between Alan and Katja about sicknesses or illnesses that spread very quickly, that affect many people in a short amount of time. Let’s get started.
[start of dialogue]
Alan: Did you see today’s news? There’s been an outbreak of Podcaster’s Disease in the city.
Katja: Oh, my God, not Podcaster’s Disease! I would not want to come down with that.
Alan: The first outbreak was at the local high school, and the health authorities thought it was localized. But a second, more widespread, outbreak has been reported at the city’s government offices.
Katja: That’s terrible! I thought Podcaster’s Disease was very rare.
Alan: It is, and that’s why the authorities are so alarmed. It’s highly communicable, so they’re hoping it won’t turn into an epidemic, or worse, a pandemic.
Katja: I’ve heard that this disease is horrible, but I’m not sure what the symptoms are. Do you know?
Alan: From what I’ve read, sufferers of Podcaster’s Disease can’t stop talking and they speak in an announcer’s voice all the time.
Katja: Oh, my God, what a terrible fate!
[end of dialogue]
Our dialogue begins with Alan saying to Katja, “Did you see today’s news? There’s been an outbreak of Podcaster’s Disease in the city.” An “outbreak” (outbreak – one word) is the moment when something begins and it starts to affect many people quickly. Usually, an outbreak is related to some illness or sickness that people are starting to get. A “disease” is just another word for an illness, a sickness. So, this is an imaginary disease called Podcaster’s Disease.
Katja says, “Oh, my God, not Podcaster’s Disease! I would not want to come down with that.” The expression “to come down with (something)” means to get a particular illness, to become sick with something. “I’m coming down with a cold” means that I am starting to get a cold. “I’m coming down with the flu” means I’m starting to get the influenza illness – the flu.
“The first outbreak,” Alan says, “was at the local high school, and the health authorities thought it was localized.” The “health authorities” would be the government doctors and other important officials who make decisions about issues of health in a state or area. To say something is “localized” means it’s just affecting one small particular area, it doesn’t affect things around it. Because the first outbreak was at the local high school, the local high school kids got sick, they thought it was just there. “But a second, more widespread, outbreak has been reported at the city’s government offices.” So there are now two places where people are getting sick. When we say something is “widespread” (one word), we mean it covers or affects a very large area.
Katja says, “That’s terrible! I thought Podcaster’s Disease was very rare.” Something that is “rare” is unusual, uncommon, not typical. Alan says, “It is (meaning it is rare), and that’s why the authorities are so alarmed.” “To be alarmed” means to be surprised and worried. You might be worried about something bad that is happening; you might be “shocked,” we would say. Alan says that this disease is highly communicable. When we talk about an illness or a disease being “communicable,” we mean that it can be passed from one person to another or from one animal to another very easily. “Highly communicable diseases” are diseases that can spread very easily from one person to another. Another word for this is “contagious” (contagious). Alan says that the health authorities are hoping that this disease won’t turn into – won’t develop into or become – an epidemic. An “epidemic” (epidemic) is when many people become sick from a particular disease in a short period of time. An epidemic can affect a large group of people. A “pandemic” (pandemic) is an illness that affects people in many different parts of the whole world. So, a “pandemic” would be a disease that many people suffer in many different countries.
Katja says, “I’ve heard that this disease is horrible, but I’m not sure what the symptoms are.” A “symptom” (symptom) is something that is wrong with your body that indicates that there’s a problem. If you have a cold, your symptoms might be a sore throat or sneezing a lot. Katja says, “Do you know (what the symptoms are)?” Alan says, “From what I’ve read, sufferers of Podcaster’s Disease can’t stop talking.” A “sufferer” (sufferer) comes from the verb “to suffer.” It’s a person who has a disease that feels pain and discomfort. Sometimes we use the expression “I suffer from….” “I suffer from allergies.” That means that allergies bother me, they affect me, I have that disease. “Sufferers” are the people who have a disease. Allen says that the sufferers of Podcaster’s Disease can’t stop talking and they speak in an announcer’s voice all of the time. An “announcer” is a person usually who presents information, especially on a television or radio program. The sports announcer is the person who describes what is happening in the game to the people watching or listening. A news announcer is someone who announces or gives – tells people about the news. So, Podcaster’s Disease causes people to talk as if they were announcers all of the time. An announcer usually has a certain voice on television. [In a deep voice] “Hello and welcome to the news. My name is Jeff McQuillan. In tonight’s top stories….” That’s kind of an announcer’s voice. Some people say I talk in an announcer’s voice. Usually my wife tells me that sometimes. Not always, sometimes. Maybe I have Podcaster’s Disease!
Katja says, once again, “Oh, my God.” “Oh my God” is a very common expression nowadays, especially among young people. On email or in text messages or instant messages it’s sometimes abbreviated “OMG.” And now, people even talk in abbreviations; someone might even say to you, “OMG,” meaning oh, my God. It’s an expression of shock – of surprise. It’s become popular in the last, I don’t know, maybe 10 or 15 years. It’s always been an expression in English, but for whatever reason it’s become more popular among younger people on the Internet. Some people don’t like the expression; religious people think that you shouldn’t use the name of God that way. It is, however, a very common thing that you will hear.
Katja says, “Oh, my God, what a terrible fate!” “Terrible” is very bad, awful, horrible. “Fate” (fate) is the outcome of a particular situation, what happens as a result of a certain situation. Some people talk about “fate” as being what will happen to you that you cannot control. Some people believe that there is someone controlling you or some thing controlling you, and you can’t avoid it and you can’t do anything about it; you can’t control it in any way. This is a very old idea; it goes back at least to the ancient Greeks, who believed in a form of fate.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Alan: Did you see today’s news? There’s been an outbreak of Podcaster’s Disease in the city.
Katja: Oh, my God, not Podcaster’s Disease! I would not want to come down with that.
Alan: The first outbreak was at the local high school, and the health authorities thought it was localized. But a second, more widespread, outbreak has been reported at the city’s government offices.
Katja: That’s terrible! I thought Podcaster’s Disease was very rare.
Alan: It is, and that’s why the authorities are so alarmed. It’s highly communicable, so they’re hoping it won’t turn into an epidemic, or worse, a pandemic.
Katja: I’ve heard that this disease is horrible, but I’m not sure what the symptoms are. Do you know?
Alan: From what I’ve read, sufferers of Podcaster’s Disease can’t stop talking and they speak in an announcer’s voice all the time.
Katja: Oh, my God, what a terrible fate!
[end of dialogue]
Good scriptwriters are rare. That’s why we’re so happy to have one here at ESL Podcast in our own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
outbreak – the moment when something begins to happen very suddenly, affecting many people
* The outbreak of war caused panic in the streets.
disease – illness; something that makes a person sick
* Dominic suffers from a rare disease that makes his legs weak.
to come down with – to begin to have a particular illness; to become sick
* I’ve had a headache all day and my nose is stuffed up. I think I’m coming down with a cold.
health authorities – a government agency and/or important doctors who are responsible for monitoring people’s health and/or preventing illnesses
* The health authorities require restaurant workers to wash their hands after using the bathroom and before touching food.
localized – concentrated in a particular area; limited to a particular area, not affecting the surrounding area
* The wildfires are still localized, but if it gets windy, they’ll probably move into a larger area.
widespread – covering or affecting a very large area
* The central bank’s announcement has led to widespread fears that prices will go up.
rare – unusual; uncommon; not typical
* Due to changes in this area, finding wolves in the wild is very rare.
alarmed – shocked, surprised, and worried about something
* Ollie was alarmed when he realized it was 11:00 and his daughter still hadn’t come home.
communicable – contagious; referring to a disease that can be passed among people or animals
* Covering your mouth and nose when you cough or sneeze is one way to slow down the spread of communicable diseases.
epidemic – when many people are sickened by a particular disease in a short period of time
* When the water treatment facilities stopped working, everyone became worried about a cholera epidemic.
pandemic – when many people are sickened by a particular disease throughout a very large part of the world
* Much of Africa is facing an AIDS pandemic.
symptom – something that is wrong with one’s body and indicates a medical problem or an illness
* Some of the symptoms of a heart attack include shortness of breath, dizziness, and chest pain.
sufferer – a person who has a disease or medical condition and feels pain or discomfort
* Pharmaceutical companies are trying to create new drugs that will help sufferers of muscular dystrophy.
announcer – a person who presents information, especially on a TV show or a radio program
* A good announcer needs to be able to read aloud very clearly.
fate – the outcome of particular situation; the course of one’s life, perhaps beyond one’s control
* Bin’s brother failed the test, but Bin plans to take it next year and hopes he won’t follow the same fate.
Comprehension Questions
1. What news story is Alan referring to?
a) Health authorities just identified the cause of Podcaster’s Disease.
b) Many people are coming down with Podcaster’s Disease.
c) Scientists just found a cure for Podcaster’s Disease.
2. What would you expect a sufferer of Podcaster’s Disease to do?
a) To speak very loudly and clearly.
b) To speak very quickly.
c) To speak with an unusual accent.
Answers at bottom.
What Else Does It Mean?
to come down with
The phrase “to come down with,” in this podcast, means to begin to have a particular illness or to become sick: “How do doctors avoid coming down with everything their patients have?” The phrase “to come down to” can mean to travel toward the south: “How often do your parents come down from Alaska to visit you?” The phrase “to come down to” can also mean to agree to sell something at a lower price: “I’d like to buy your boat, but I can’t afford that price. Can you come down to $3,700?” Finally, the phrase “to come down [hard] on (someone)” means to criticize someone: “Yes, you need to punish your son, but don’t come down too hard on him.”
alarmed
In this podcast, the word “alarmed” means shocked, surprised, and worried about something: “The manager became alarmed when she realized her department was over budget.” Normally an “alarm” is something that makes a loud noise as a warning: “When there’s a problem at the power station, a siren goes off and red lights begin to flash as an alarm.” An “alarm clock” is a small electronic device that makes a noise at a certain time to wake someone up: “Hunter sets his alarm clock for 6:00 every weekday, and for 8:30 each Saturday.” Finally, a “smoke alarm” is a small electronic device that hangs on the ceiling and makes a loud noise if there is smoke from a fire: “If you hear a smoke alarm, run outside and call the fire department.”
Culture Note
Worst Epidemics in U.S. History
The worst epidemic in U.S. History was an outbreak of Spanish “influenza” (flu) in 1918. Although the flu normally lasts only a few days, causing “congestion” (difficulty breathing through one’s nose), coughing, and a fever, the influenza in 1918 killed more than half a million people – more than any other epidemic in the country.
The United States has “seen” (experienced) several epidemics of yellow fever. Yellow fever killed 4,000 residents of Philadelphia in 1793, as well as almost 8,000 in New Orleans in the mid 1800s, and more than 13,000 in the Southern States around the Mississippi Valley in 1878.
“Cholera” (a disease caused by drinking contaminated water or eating contaminated food) has also been “deadly” (killing many people). In 1832, cholera epidemics killed more than 3,000 people in New York City and more than 4,000 people in New Orleans. Another 5,000 people died from cholera in New York City in 1848.
In 1916, “polio” (a disease that affects nerves in the spine (back), making the sufferer unable to move certain muscles) “claimed the lives of” (killed) more than 7,000 and affected more than 27,000 others, with other major outbreaks in 1949 and 1952.
The AIDS epidemic was a major concern between 1981 and 2005, when it affected “nearly” (almost) a million people in the United States, resulting in more than 550,000 deaths.
The most recent epidemic in the United States was H1N1 or “swine flu.” According to the Centers for Disease Control (CDC; health authorities in the U.S.), 22 million people in the country were infected with the virus. Almost 100,000 of them had to be “hospitalized” (spend time in the hospital for treatment) and almost 4,000 died from H1N1.
Comprehension Answers
1 - b
2 - a