= 0736
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 736: Following One’s Dream.
This is English as a Second Language Podcast episode 736. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com and download a Learning Guide for this episode to help you improve your English even faster. You can also join us on Facebook at Facebook.com/eslpod, and you can follow us on Twitter at ESLPod.
This episode is a dialogue between Cassandra and Lazlo. It’s going to be talking about following your dream – your goal for the future. Let’s get started.
[start of dialogue]
Cassandra: I’ve had it! I’m quitting and I’m not coming back. I was meant for greater things than working in this pathetic place. Life is passing me by.
Lazlo: You can’t quit. You need the money and you have responsibilities, remember?
Cassandra: I’ve sacrificed enough for security. I want to make a difference. I want to do big things. I want to have an impact on the world.
Lazlo: That’s very admirable. Most people want to make a difference in the world, but don’t have the guts to try.
Cassandra: You are so right! But I’m going to make it happen. I aspire to do great things and I won’t rest until I do. I want to follow my dream.
Lazlo: What is your dream?
Cassandra: Um, well, I’m not quite sure what I’m destined to do yet, but as soon as I figure out my true vocation, I’m following my heart.
Lazlo: That’s great. Until then, lunch break is over. Could we get back to work?
[end of dialogue]
Our dialogue begins with Cassandra saying, “I’ve had it!” When you say, “I’ve had it” you mean I have had enough; it’s an expression of frustration. You don’t want to continue doing what you’re doing or experiencing what you’re experiencing anymore. Cassandra says, “I’m quitting (I’m leaving my job) and I’m not coming back. I was meant for greater things than working in this pathetic place.” When you say that you are “meant for” something you mean you are intended for something, or you have specific expectations for yourself about something. I feel I was meant for podcasting; this is what my life has been preparing me to do. Well, probably not, but that’s the idea. “Pathetic” (pathetic) means it’s very uninteresting, it doesn’t deserve any respect. Someone says, “Oh, that was a pathetic attempt to make me laugh” meaning it was a very weak, uninteresting, not a good attempt. So this is a pathetic place, Cassandra says, “Life is passing me by.” “To pass (someone) by” means to go on without you, especially we say this when time is passing very quickly and you feel as though you are missing opportunities in life. “Life is passing me by,” I’m getting older but I’m not experiencing anything better.
Lazlo says, “You can’t quit. You need the money and you have responsibilities, remember?” Cassandra says, “I’ve sacrificed enough for security.” “To sacrifice” as a verb means to give something up, to decide not to do something because you think there is some greater good – there is some greater benefit in the future. Sometimes you have to sacrifice your appetite for food in order to lose weight; you have to give something up. Or, people make sacrifices; they sacrifice so that their children can have a better life. The parents work more hours or work harder so that their children can go to a better school. That would be an example of a sacrifice.
Cassandra says that she has sacrificed enough for security. “Security” here means a feeling of safety, of stability, that you have money and a house or a place to live. She says, “I want to make a difference.” “To make a difference” means to change the world in some positive way, to change what is happening around you in some positive way. There was a song back in the 1980s you may remember called “We Are the World.” I think it was Michael Jackson who wrote the song; he was trying to make a difference in the world. You remember: “We are the world / We are the children / We are the ones who make a brighter day / So let’s start giving / So let’s start giving.” Never liked that song, really?
Anyway, Cassandra says that she wants to make a difference – hopefully not singing “We Are the World!” She says, “I want to do big things (I want to do something that is important). I want to have an impact on the world.” “To have an impact” (impact) is to have an affect on the world, to do something that changes some other activity or some other people. Nowadays, people use the word “impact” as a verb. I don’t like this use; I don’t use it myself, but it’s become acceptable to say that I am going to impact something. Personally, I hate that use of the word, but it is becoming common.
Cassandra wants to have an impact. That’s okay, “impact” as a noun there, as it’s supposed to be. Lazlo says, “That’s very admirable.” When you say something is “admirable” you mean that you respect it, you value it. “Admirable” comes from the verb “to admire” (admire). When you admire something you respect it, you think it’s good; you may want to be like it. Lazlo says, “Most people want to make a difference in the world, but don’t have the guts to try.” The word “guts” (guts) here means courage, bravery, willing to do something that is difficult or even dangerous. There are other meanings of the word “gut.” Take a look at our Learning Guide to find those.
Cassandra says, “You are so right!” She’s saying to Lazlo that she agrees with him. “But,” she says, “I’m going to make it happen. I aspire to do great things and I won’t rest until I do (until I do great things).” “To aspire” (aspire) means to try to do something that is difficult but important. “He aspires to be in the Olympics.” It’s not easy; it’s a very difficult goal, but he wants to do it – he aspires to do that. Cassandra says she aspires to do great things and she won’t rest, meaning she’ll continue working until she does something great. She says, “I want to follow my dream.” This expression, “to follow your dream,” means to follow your goal, to do what you want to do. To do what you’ve always thought you should do, that’s to follow your dream.
Lazlo says, “What is your dream?” Good question. Cassandra says, “Um, well, I’m not quite sure (I’m not very sure) what I’m destined to do yet.” “To be destined (destined) to (something)” means to be intended to be in the future or to have in the future. It can simply mean the purpose of something: “This man is destined to be a great leader.” It’s almost as though that is the way that nature or God or fate has made this person. They will eventually become great – they are destined to be great. We have another word, “destination,” that’s the place where you are going. You can see they are sort of related ideas. Your goal, your object, your destination; they’re related to this idea of being destined or intended for something.
Cassandra says she’s not sure what she’s destined to do yet, but as soon she figures out her true vocation, she will follow her heart. A “vocation” (vocation) is what you believe that you should do – what career, what job you should do, but it’s a little more than just a job. We have another word, which is related to the meaning of “vocation,” which is “calling.” “What is your calling?” It often relates to some deeper, sometimes even spiritual purpose or religious purpose. We talk about vocations to the priesthood – to the ministry in the Christian churches. That’s the idea; it’s a deeper sense of what you should be doing.
Cassandra says she doesn’t know what her true vocation is, but when she finds out – when she figures it out – she’s following her heart. “To follow your heart” means to do what you believe is right, to do what you think is good or correct. It can also be used, as I think it is here, to mean the same as to follow your dream. Lazlo says, “That’s great. Until then (until you figure it out), lunch break is over.” “Lunch break” is the time in the middle of the day, usually at noon – at 12 p.m. in most places in the U.S., where you stop and eat a meal, your lunch. Lazlo says, “lunch break is over. Could we get back to work?” So, Cassandra has all these ideas and all these dreams, but she’s not really sure what she wants to do.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cassandra: I’ve had it! I’m quitting and I’m not coming back. I was meant for greater things than working in this pathetic place. Life is passing me by.
Lazlo: You can’t quit. You need the money and you have responsibilities, remember?
Cassandra: I’ve sacrificed enough for security. I want to make a difference. I want to do big things. I want to have an impact on the world.
Lazlo: That’s very admirable. Most people want to make a difference in the world, but don’t have the guts to try.
Cassandra: You are so right! But I’m going to make it happen. I aspire to do great things and I won’t rest until I do. I want to follow my dream.
Lazlo: What is your dream?
Cassandra: Um, well, I’m not quite sure what I’m destined to do yet, but as soon as I figure out my true vocation, I’m following my heart.
Lazlo: That’s great. Until then, lunch break is over. Could we get back to work?
[end of dialogue]
I think Dr. Lucy Tse was meant for writing scripts, because she does such an admirable job. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
to quit – to stop working in a particular job; to announce that one will not continue to work in a position or organization
* If Jens’ boss won’t give him a raise, he’s going to quit.
to be meant for – to be intended for; to have specific expectations for oneself
* Quentin felt like he was meant for a career in engineering because he’s always wanted to know how things worked.
pathetic – not deserving respect or interest; very weak, uninteresting, or unhelpful
* That is a pathetic attempt to make others feel sorry for you so that you don’t have to do your work!
to pass (one) by – to proceed without involving oneself, especially when it seems like time is passing very quickly and one is missing opportunities
* Naori is taking a lot of classes in the evening, because she’s worried that promotions will pass her by at work.
to sacrifice – to give something up; to decide not to do or have something because it will result in some benefit in the future; to accept a temporary disadvantage because one expects to receive some advantage later as a result
* They’re sacrificing a lot right now to pay off their mortgage early, but they’re looking forward to being debt-free.
security – stability; the feeling of safety and predictability, especially related to having enough money and housing
* Liam said that being a software developer may not be very exciting, but it provides a lot of security.
to make a difference – to make a valuable contribution in the world; to change society in a positive way
* Ilya joined the Peace Corps to try to make a difference.
to do big things – to do something that is important and impressive
* Olga dreams of doing big things when she grows up, such as being a civil rights activist.
to have an impact – to do something that is important, produces many changes, and is noticed by many people
* It’s amazing how much the Internet has had an impact on our daily life in the past 20 years.
admirable – something that one respects and looks up to; something that is valued
* Patrice’s honesty is admirable, but I wish she wouldn’t share her opinions so openly.
guts – bravery; courage; willingness to do something that is difficult, dangerous, or risky
* It took a lot of guts for you to tell the truth about what happened. Thank you.
to aspire – to try to do something that is difficult, ambitious, and important
* Dmitry aspires to become a millionaire by the time he is 30.
to follow (one’s) dream – to do what one wants to do; to do what is most important; to achieve one’s goals and ambitions
* Yvonne is determined to follow her dream of becoming an astronaut, so she’s studying physics and astronomy.
destined – intended to have or be in the future; meant to be
* Everyone could tell Wei was destined for greatness, even as a child.
vocation – calling; what one believes one should do, especially as a career
* I think Ingrid missed her true vocation. She should have been a composer.
to follow (one’s) heart – to do what one believes is right, correct, and good, especially if other people disagree
* Missy knows she’ll never make much money as a teacher, but she wants to follow her heart.
Comprehension Questions
1. What does Cassandra want to do?
a) She wants to travel to many different places.
b) She wants to tell her boss she hates her job.
c) She wants to do something that is meaningful.
2. What does Cassandra mean when she says, “I want to follow my dream”?
a) She wants to do what she believes is most important.
b) She wants to understand what her dreams mean.
c) She wants to sleep more so that she can dream more.
Answers at bottom.
What Else Does It Mean?
to pass (one) by
The phrase “to pass (one) by,” in this podcast, means to proceed without involving oneself, especially when it seems like time is passing very quickly and one is missing opportunities: “Don’t let this opportunity pass you by!” The phrase “to pass away” or “to pass on” means to die: “Did you hear that Carole passed away?” The phrase “to pass down” means to teach something to someone who is younger than oneself: “These stories have been passed down for generations.” Finally, the phrase “to pass (something) up” means to not take advantage of an opportunity to do something: “They’re selling the car at a great price, but we just don’t have enough money to buy it right now, so we’re going to pass it up.”
guts
In this podcast, the word “guts” means bravery, courage, or a willingness to do something that is difficult, dangerous, or risky: “Sheryl has a lot of guts if she intends to tell her boss that she thinks he’s wrong.” The phrase “a gut feeling” refers to an instinct, or to a belief one has without knowing the reason for it: “Tien had a gut feeling the project would fail, but he couldn’t explain why.” The word “guts” refers to the organs inside a person’s or animal’s body, especially when used as part of the phrase “blood and guts”: “I hate watching violent movies with blood and guts.” Finally, the phrase “to spill (one’s) guts” means to tell a secret: “Whenever Blake has too much to drink, he spills his guts.”
Culture Note
The Survivalism Movement
The “survivalism movement” refers to people and groups that are preparing for future “disruptions” (interruptions; problems) in “society” (how people are organized to live together). Some “survivalists” are worried about “natural disasters” (events like earthquakes, hurricanes, and tornadoes) or “pandemics” (diseases affecting many people). Other survivalists are worried about the “collapse” (fall and destruction) of political or economic systems. “Regardless” (no matter) of their specific concerns, survivalists try to “gather” (collect) the things they will need in order to “survive” (continue to live; not die) any “disaster” (a serious, dangerous situation).
The survivalism movement “has been around” (has existed) since the 1970s, but it experienced a “resurgence” (increased interest, growth, and participation) in the 2000s after the terrorist attacks in New York and Washington, D.C. on September 11th, 2001. The economic crisis and fears related to “swine flu” (a disease many people thought would cause many deaths in 2009) have also “prompted” (initiated; made someone do something) people to prepare for disaster in recent years.
Many books and websites have been published, advising people on how they can prepare for survival. These books contains lists of the things people will need to have, such as food, clothing, and medicine, as well as “skills” (the ability to do certain things) they should try to “develop” (learn and improve).
Some survivalists try to build a “hidden” (secretive; not seen) “retreat” (a place where one can go for isolation, away from other people). Other survivalists belong to organizations of people who are planning to work together and help one another during the “impending” (happening soon) disaster.
Comprehension Answers
1 - c
2 - a