= 0738
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 738: Talking to a Mechanic.
This is English as a Second Language Podcast episode 738. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Talking to a Mechanic.” A “mechanic” is a person who fixes cars – automobiles. Let’s get started.
[start of dialogue]
Mechanic: Hi, I’m the mechanic. What can I do for you?
Amy: My car is making a very weird noise. It sounds like this: gulug, gulug, gulug…
Mechanic: Hm, that doesn’t sound good. Where is it coming from?
Amy: I’m not sure. When I’m in the car, it sounds like it’s coming from the engine, but when I get out of the car, it sounds like it’s coming from directly under the trunk, maybe the muffler?
Mechanic: That’s not a noise a muffler would make. Let me take a look. Can you start the car and pop the hood?
Amy: Sure.
Mechanic: Well, I don’t hear the sound right now, but your battery needs replacing, you have a coolant leak, your carburetor needs adjusting, and your spark plugs are shot. I need to look under the car.
Amy: Okay, go ahead.
Mechanic: Your brake pads need replacing and your tires need balancing.
Amy: But are any of those problems causing that horrible noise?
Mechanic: I don’t know. I don’t hear the noise right now, so it’s hard to tell. But that’s all work you need to have done on this car anyway for it to run right. It’s only a matter of time before your car stops working if you don’t take care of those problems.
Amy: I come in with one problem and you find 10 others. I guess you should go ahead. What else can I do?
Mechanic: Um, buy a bus pass?
[end of dialogue]
Our episode begins with the “mechanic,” the person who fixes cars, asking – or rather saying, “I am the mechanic. What can I do for you?” How can I help you? Amy says, “My car is making a very weird noise (a very strange noise). It sounds like this: gulug, gulug, gulug…” The mechanic says, “Hm, that doesn’t sound good. Where is it coming from?” Where is the sound coming from? Amy says, “I’m not sure. When I’m in the car, it sounds like it’s coming from the engine.” The “engine” is the motor; it’s the part of the car, usually in front, that makes the car go; it gives it power. Amy says, “but when I get out of the car, the noise sounds like it’s coming from directly under the trunk, maybe the muffler?” The “trunk” (trunk) is the back part of the car, the part that usually you store things in – you put things in to keep while you are driving. Amy says that the sound sounds like it’s coming from under or underneath the trunk. “Maybe,” she’s guessing, “the muffler?” A “muffler” (muffler) is a part of the car that muffles or covers – lessens – the noise from the car.
The mechanic says, “That’s not a noise a muffler would make.” So the sound that Amy made didn’t sound like a sound a muffler would make, according to the mechanic. He says, “Let me take a look. Can you start the car (can you turn the car on) and pop the hood?” The “hood” (hood) here means the cover of the front of the car. We talked about the trunk of the car in the back. The front of the car has a metal cover over it, and we call that the “hood.” “To pop the hood” means to open the hood. In many cars, there’s a little button that you either push or pull that unlocks the hood; you push it in or you pull it out. That’s where we get the verb “to pop,” to unleash, to unlock in one quick action.
So, the mechanic opens the hood after Amy pops the hood, and although the dialogue doesn’t indicate he clearly had to take some time to look at the engine and the parts underneath the hood. He comes back and says, “Well, I don’t hear the sound right now, but your battery needs replacing.” Your “battery” is a source of stored electrical power that is used to help start the car, as well as for other parts of your car that require electricity. The mechanic also tells Amy that she has a coolant leak. “Coolant” (coolant) is a liquid that you put into the car’s motor – technically into the radiator of the car – that helps keep the engine cool so it doesn’t get too hot. A “radiator” is something that gives off or radiates heat, in this case to try to get rid of the heat. You can also have a radiator in your house. It’s not the same as a car radiator, but it has the same function of giving off heat to help warm up your house. Some old houses still have radiators. The house that I grew up in had metal radiators all along and through the house. But anyway, we’re talking about cars, not my old house.
The mechanic thinks that Amy has a coolant leak. A “leak” (leak) here means the slow movement of liquid coming out of some container or some hose, usually through a small hole that you don’t want to be there. The mechanic also says that Amy’s carburetor needs adjusting. A “carburetor” (carburetor) is the part of the car engine that mixes the gasoline with air so that it can be used in the engine. The mechanic also says that Amy’s spark plugs are shot. The “spark (spark) plugs” are the parts of the car that create a spark, it’s almost like a small, quick fire to make the gasoline burn and to help run the engine. When we say something is “shot” (shot) – that can have a couple of different meanings – here it means completely ruined, no longer able to work or function properly. That’s one meaning of “shot.” There are other meanings that can be found in our Learning Guide. Our Learning Guide also, in this episode, talks about other meanings of the word “trunk,” which we talked about earlier.
So the mechanic finds all these problems. Then he says, “I need to look under (or underneath) the car.” Amy says, “Okay, go ahead.” And again, we assume that the mechanic has taken some time even though it isn’t indicated in our dialogue. Either that, or he’s the most intelligent mechanic in the world! The mechanic says, “Your brake pads need replacing and your tires need balancing.” Your “brakes” are the parts of the car that slow the car down or stop the car. A “brake pad” is a part of the brakes that pushes against part of the wheel in order to slow it or stop it, and typically after so many miles you need to replace or get new brake pads, and that’s what the mechanic is saying Amy needs to do. She also needs to have her tires balanced. Cars typically have four wheels, and around the wheel there is something made of rubber that’s called a “tire” (tire). When you put new tires on sometimes they have to be balanced so that they’re all basically the same in terms of how they’re adjusted.
Amy says, “But are any of those problems causing that horrible noise?” That bad noise that she came in and asked the mechanic about at the beginning of our dialogue. The mechanic says, “I don’t know. I don’t hear the noise right now, so it’s hard to tell.” When we say something is “hard to tell” we mean it’s difficult to know, it’s difficult to determine or figure out. “But that’s all work (all of those repairs) you need to have done on this car anyway for it to run right (for it to operate correctly). It’s only a matter of time,” he says, “before your car stops working if you don’t take care of those problems.” “It’s only a matter of time” means that something will definitely happen in the future, eventually. You don’t know when exactly, but you know if things continue as they are now this thing will eventually happen. It’s only a matter of time that all of us are going to die; it will happen to every one of us. We don’t know when, someday, hopefully not too soon for most of us.
Amy then says, “I come in (meaning I come here) with one problem (the noise) and you find 10 others. I guess you should go ahead (meaning I guess you should go ahead and do the repairs). What else can I do?” That’s something that many of us feel when we go into a mechanic. We don’t know what the problem is. They tell us they know what the problem is, and they fix it, but we’re never really sure exactly, in most cases, what the problem was. We have to trust the mechanic to a certain extent. Amy asks, “What else can I do?” What other choice do I have but to get these repairs made?
The mechanic says, “Um, buy a bus pass?” A “bus pass” is usually a little card or a piece of paper that allows you to get on and off of the public buses. You usually pay a certain amount for a week or a month or 10 days. Or sometimes you pay for the number of rides that you take, you can get on the bus 10 times for example. All of these are examples of bus passes. You can have a pass to a lot of things. In many cases, it means a ticket to something, and that’s really what a bus pass is. It’s a ticket to get on and off – well, to get on the bus. They don’t usually ask for a ticket to get off the bus, although that might be a good way of making some more money, I’m not sure.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mechanic: Hi, I’m the mechanic. What can I do for you?
Amy: My car is making a very weird noise. It sounds like this: gulug, gulug, gulug…
Mechanic: Hm, that doesn’t sound good. Where’s it coming from?
Amy: I’m not sure. When I’m in the car, it sounds like it’s coming from the engine, but when I get out of the car, it sounds like it’s coming from directly under the trunk, maybe the muffler?
Mechanic: That’s not a noise a muffler would make. Let me take a look. Can you start the car and pop the hood?
Amy: Sure.
Mechanic: Well, I don’t hear the sound right now, but your battery needs replacing, you have a coolant leak, your carburetor needs adjusting, and your spark plugs are shot. I need to look under the car.
Amy: Okay, go ahead.
Mechanic: Your brake pads need replacing and your tires need balancing.
Amy: But are any of those problems causing that horrible noise?
Mechanic: I don’t know. I don’t hear the noise right now, so it’s hard to tell. But that’s all work you need to have done on this car anyway for it to run right. It’s only a matter of time before your car stops working if you don’t take care of those problems.
Amy: I come in with one problem and you find 10 others. I guess you should go ahead. What else can I do?
Mechanic: Um, buy a bus pass?
[end of dialogue]
It’s hard to tell what our scriptwriter Dr. Lucy Tse looks like by going to our website. But trust me, she really does exist, and she’s the best podcast scriptwriter in the world!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
mechanic – a person whose job is to maintain and repair cars or other types of machines
* Do you pay a mechanic to change the oil in your car, or do you do it yourself?
engine – the inside part of a car that makes it move
* The engine got really hot while we were driving up into the mountains, so we had to stop and let the car rest for a while.
trunk – the back section of a car that has a large lid that opens, used for storage
* Do you think all of these suitcases will fit in the trunk?
muffler – the part of a car that makes it quieter
* Wow, Cason’s car is really loud. Maybe he needs to replace the muffler.
to pop the hood – to push a small button inside a car that unlocks the piece of metal that covers the front, top section of a car, so that it can be opened and people can see the engine
* Please pop the hood so I can add more windshield washing fluid.
battery – a source of stored electricity for a vehicle or machine, so that it does not need to be plugged in
* How often do you change the batteries in the smoke detectors in your house?
coolant – a liquid used to keep a car engine cool or prevent it from becoming too hot
* It’s a good idea to make sure your car has enough coolant before driving through the desert.
leak – the slow movement of liquid out of a container through a small, unwanted hole
* How much will it cost to repair the leak in the roof?
carburetor – the part of a car that mixes gasoline with air for burning
* When Randolph noticed a sudden decrease in his car’s fuel efficiency, he thought it might be the carburetor.
spark plug – the part of a car that creates a spark (a very small, quick fire) to make the gasoline burn
* Spark plugs made from copper often last longer than other types of spark plugs.
shot – worn out; used thoroughly, so that very little or nothing is left
* Yuri has had his cell phone for years, but now it’s shot and he needs to buy a new one.
brake pad – the part of a car that pushes against the moving part of a wheel to make the car slow down and/or stop
* The repair shop recommends replacing the brake pads every 20,000 miles.
tire – the large, circular rubber pieces that are placed around wheels and filled with air
* Don’t drive over that broken glass, or you might ruin your tires.
to balance – to even something out; to make things equal in some way
* A lot of people struggle to balance the demands of work and family.
hard to tell – difficult to determine; difficult to know something
* It’s hard to tell if the boss is in a good mood because she never smiles.
to run – to operate, especially when talking about a car, machine, or computer program
* The juice shop needs strong blenders, because they run most of the day.
it’s only a matter of time – a phrase used to talk about something that definitely will happen in the future, but one does not know exactly when
* It’s only a matter of time before you’ll start to feel tooth pain, so we recommend filling these cavities soon.
bus pass – a card or a small piece of paper that allows someone to use a bus system for a certain period of time without paying for each individual ride
* The university gives free bus passes to all its students to encourage them to use public transportation.
Comprehension Questions
1. What does it mean when something is “shot”?
a) It will no longer work.
b) It will work like a gun.
c) It will be too hot to touch.
2. What does Amy do when the mechanic asks her to pop the hood?
a) She hits the top of her car.
b) She opens the front part of the car so he can see the engine.
c) She pays him $20 for his time.
Answers at bottom.
What Else Does It Mean?
trunk
The word “trunk,” in this podcast, means the back section of a car that has a large lid that opens, used for storage: “Marko always keeps bottled water, snacks, a blanket, and a flashlight in the trunk of his car, just in case of an emergency.” The word “trunk” also refers to a large, wooden container with a lid that closes: “Emma keeps extra bedding in a cedar trunk in the guest bedroom.” When talking about trees, a “trunk” is the large wooden, up and down section: “He carved ‘J.M. + L.E.’ in a heart shape on the trunk of the tree.” Finally, a “trunk” also refers to the long nose of an elephant: “The children laughed as the elephant sprayed water from its trunk.”
shot
In this podcast, the word “shot” means worn out, or used so thoroughly that very little or nothing is left: “This couch is shot! When are you going to buy a new one?” The phrase “a shot in the arm” describes something that gives one energy, enthusiasm, and motivation to be more successful and do something well: “Getting such a nice letter of recommendation was a shot in the arm for Harvey during his job search.” The phrase “not by a long shot” is used to describe something that is extremely unlikely: “The business is failing and there’s no way they’ll be able to keep it open next year, not by a long shot.” Finally, the phrase “to give (something) (one’s) best shot” means to try to do something: “Normally Lacey is scared of speaking in public, but she agreed to give it her best shot.”
Culture Note
Roadside Assistance Programs
“Roadside assistance programs” or “emergency roadside assistance programs” provide “assistance” (help) to drivers when they have problems while they are driving. Companies go to the “roadside” (next to the road where the driver has stopped) to provide assistance, so the driver doesn’t need to call a “tow truck” (a vehicle that pulls cars that cannot move on their own).
Usually the driver pays a monthly or annual fee to have access to the roadside assistance program. If the driver is “locked out” (unable to enter a vehicle or building because one’s keys are locked inside), he or she can call the program and someone will come to help the driver open the car. If the car has a “flat tire” (a tire that has lost all its air and cannot be driven on), someone will come to help put a new tire on the car. If the driver “runs out of gas” (drives until no gasoline remains), the company will send someone to deliver enough “fuel” (gasoline) so the car can “make it to” (be able to arrive at) the nearest gas station. If the car “breaks down,” the company will send someone to try to fix the car or, if it cannot be fixed quickly, to “tow” (pull with another vehicle) to the nearest mechanic’s “shop” (place of business, where cars are fixed).
Roadside assistance programs offer other benefits, too. The most popular roadside assistance program, AAA (pronounced “triple A”), offers its members free maps and “travel guides” (books with information about what to visit, where to eat, and where to sleep in a certain area). In addition, AAA members “are eligible for” (can get; meet the requirements for) “discounts” (lower prices) at many hotels, restaurants, and other places when they show their membership card.
Comprehension Answers
1 - a
2 - b