= 1207
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,207 – Gauging the Doneness of Meat.
This is English as a Second Language Podcast episode 1,207. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
I highly recommend you go to ESLPod.com and become a member of ESL Podcast so you can download the Learning Guide for this episode. The Learning Guide contains all of what we say in a transcript, as well as a complete glossary of definitions and sample sentences. We also have an ESL Podcast Store on our website that sells additional courses in Business and Daily English.
This episode is a dialogue talking about meat and how it is cooked, giving you some important words to describe how meat is cooked that will become very useful to you if you ever go to a restaurant and need to order meat in English. Well, I’m hungry. Let’s get started.
[start of dialogue]
Chris: How do you like your steak?
Ruth: Well done. I don’t like any pink showing and I don’t mind if it’s a little charred.
Chris: I’ll cook it the way you want it, but it’ll be dry and tough.
Ruth: Yes, but a longer cooking time kills foodborne illnesses. I don’t want to eat anything that’s undercooked.
Chris: It doesn’t have to be burnt to be safe to eat. It’s easy to gauge when meat is done. How about if I brown each side to seal in the juices and then cook it to medium doneness?
Ruth: No, I don’t want to take any chances. I’d rather the steak is overcooked than undercooked. Are you going to eat that?
Chris: Yes, I like my steak juicy.
Ruth: But that’s raw!
Chris: No, it’s cooked rare, not raw. I’ll cut into it so you can see that it’s cooked.
Ruth: It’s oozing red! That is definitely not cooked.
Chris: I’ll prove it to you. I’ll eat this piece and live to tell about it.
Ruth: Don’t put that in your mouth! You’re risking your health.
Chris: I think I’ll survive.
[end of dialogue]
Chris begins our dialogue by saying to Ruth, “How do you like your steak?” A “steak” (steak) here refers to a thick slice, or piece, of “beef” (beef). “Beef” is meat from a cow. There are many different kinds of steak that come from a cow. We’re not sure exactly what kind Chris is asking Ruth about. Ruth answers, however, that she wants her steak “well done.” A piece of beef that is cooked “well done” is cooked so that there is no longer any red or pink in it – that is, there’s no longer any sign of the red meat that is typically what you see when you have a piece of beef.
Ruth says, “I don’t like any pink showing and I don’t mind if it’s a little charred” (charred). “Charred” meat is meat that has become black from being cooked too long or from being too close to a source of heat.
Now, people who like their beef “charred” don’t think there’s anything wrong with that. That’s the way they like it. But that’s not the way Chris likes it.
Chris says, “I’ll cook it the way you want it, but it will be dry and tough” (tough). When we describe meat as being “tough,” we’re saying that it is difficult to chew. “Tough” is the opposite of “tender” (tender), which is when the meat is soft and often full of juices, full of liquid. Chris says that cooking the beef well done will make it dry and tough. However, not all meat that is cooked well done is dry and tough. Apparently, however, that’s what Chris believes will happen if he cooks this steak the way Ruth wants it.
Ruth says, “Yes” – she oddly agrees with him – “but a longer cooking time kills foodborne illnesses.” “Cooking time” is how long something is cooked, how long something is put in or over a source of heat. “Illnesses” describe diseases that your body can get that make you sick. “Foodborne” (foodborne) refers to things that are present in food.
“Foodborne illnesses” are illnesses you can get from eating food that is in a certain condition – perhaps the food was left out too long outside of a refrigerator. You might get sick from eating food like that. That would be a “foodborne illness” – a disease or illness that is passed through or transferred through food. Ruth says, “I don’t want to eat anything that’s undercooked.” Something that is “undercooked” is something that is not cooked long enough, something that is not cooked enough. The opposite of “undercooked” would be “overcooked” – something that is cooked for too long.
Chris says, “It doesn’t have to be burnt to be safe to eat.” Chris is describing the steak when he uses the word “it” here. “It” – that is, the steak – “doesn’t have to be burnt (burnt) to be safe to eat.” “Burnt” comes from the verb “to burn” (burn). If you “burn” food, you cook it too long so that it often becomes black. Chris thinks cooking the food to the point of being well done means that it will be burnt. Perhaps Chris hasn’t cooked very many steaks. I’m not sure.
He believes, however, that a piece of food doesn’t have to be burnt to be safe to eat. He says, “It’s easy to gauge when meat is done.” “To gauge” (gauge) is to measure something, to determine how much of something there is. The name of this episode is “Gauging the Doneness of Meat.” “Doneness” (doneness) refers to how long or how much a piece of meat has been cooked.
Just as we have the words “undercooked” and “overcooked,” we have the terms “underdone” and “overdone.” Meat that is “underdone” hasn’t been cooked long enough. Meat that is “overdone” has been cooked too long. Chris says it’s easy to gauge the doneness of meat. He says, “How about if I brown each side to seal in the juices and then cook it to medium doneness?”
“To brown” (brown) meat is to cook it for a short time, often at a high temperature, so that the outside of the meat gets cooked and turns the color brown. Sometimes a cook will do this “to seal (seal) in the juices (juices).” “To seal in the juices” means to cook something quickly on the outside so that the liquid inside of the meat doesn’t escape. It stays in the meat so that when you eat the meat, it has more flavor. That’s why Chris is suggesting to brown each side and then cook it to “medium (medium) doneness.” “Medium doneness” is cooking meat so that there is a little bit of pink inside.
The terms we use in describing meat as they relate to how much the meat is cooked are “rare” (rare), which is when the meat is still very red; “medium rare,” which means it’s a little more cooked but still fairly red; “medium,” which is in between being completely cooked – no red and rare – “medium well,” which is when there’s a little bit of pink but not very much; and finally, “well done,” when there is no pinkness – when the meat is completely cooked through.
Chris is suggesting cooking the steak to medium doneness. Ruth says, “No, I don’t want to take any chances” – that is, I don’t want to have any risks of getting sick. “I’d rather the steak is overcooked than undercooked.” She then looks at Chris’s steak and says, “Are you going to eat that?” Chris says, “Yes. I like my steak juicy” – with lots of liquid that comes out of the steak.
Ruth says, “But that’s raw!” (raw). Meat that is “raw” is not cooked at all. That’s not the same as “rare,” where the meat is cooked but there’s still a lot of redness in the middle. Chris corrects Ruth and says, “No, it’s cooked rare, not raw. I’ll cut into it so you can see that it’s cooked.” Ruth says, however, “It’s oozing red!” “To ooze” (ooze) is for liquid to slowly come out of something. In this case, the liquid is the blood from the meat that is coming out. Ruth says, “That is definitely not cooked.”
Chris says, “I’ll prove it to you. I’ll eat this piece and live to tell about it.” The expression “to live to tell about” something means to do something dangerous and then be able to survive it – not to be killed by that experience. Chris is making a joke here. He doesn’t really think that he going to die by eating this piece of meat. So he’s sort of making fun of Ruth who thinks that it is unsafe, that it is dangerous for him to eat this meat that is cooked rare instead of well done. He is going to eat it and then “live to tell about it.”
Ruth says, “Don’t put that in your mouth! You’re risking your health,” meaning you could get sick. Chris doesn’t think so. He says, “I think I’ll survive” (survive). “To survive” is to go through a dangerous situation and still live, and still be okay. It’s the opposite here of “to die.” Chris doesn’t think he’s going to die from eating meat that is not well done.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Chris: How do you like your steak?
Ruth: Well done. I don’t like any pink showing and I don’t mind if it’s a little charred.
Chris: I’ll cook it the way you want it, but it’ll be dry and tough.
Ruth: Yes, but a longer cooking time kills foodborne illnesses. I don’t want to eat anything that’s undercooked.
Chris: It doesn’t have to be burnt to be safe to eat. It’s easy to gauge when meat is done. How about if I brown each side to seal in the juices and then cook it to medium doneness?
Ruth: No, I don’t want to take any chances. I’d rather the steak is overcooked than undercooked. Are you going to eat that?
Chris: Yes, I like my steak juicy.
Ruth: But that’s raw!
Chris: No, it’s cooked rare, not raw. I’ll cut into it so you can see that it’s cooked.
Ruth: It’s oozing red! That is definitely not cooked.
Chris: I’ll prove it to you. I’ll eat this piece and live to tell about it.
Ruth: Don’t put that in your mouth! You’re risking your health.
Chris: I think I’ll survive.
[end of dialogue]
We thank our scriptwriter, Dr. Lucy Tse, for her perfectly cooked scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
steak – a thick slice of beef (meat from a cow), typically considered to be high-quality meat
* This steak has been marinated in garlic, olive oil, and soy sauce
well done – cooked thoroughly so that meat is no longer red or pink
* Waiter, I asked for the hamburger to be well done, but it’s still pink in the middle. Please ask the chef to cook it a bit longer.
charred – burnt; with a surface that has become black from being cooked for too long or too close to a source of heat
* Hold the marshmallow farther from the flame, or it will get charred.
tough – difficult to chew; not tender
* This jerky is delicious, but it’s very tough, so it takes a long time to chew and eat it.
cooking time – the amount of time that something is cooked; the length of time that a food is exposed to heat
* This recipe requires about an hour, but most of that is cooking time. You’ll only need about ten minutes to prepare the ingredients and place everything in the oven.
foodborne illness – a disease that is transmitted (passed to a person) through food; a disease that is transferred when something is eaten
* Many foodborne illnesses are caused by not cooking food well enough, or by cooks who do not wash their hands before cooking.
undercooked – not cooked enough; cooked for too short a period of time
* That cake looks nice, but I think it’s undercooked in the middle.
burnt – cooked too much so that something is black
* The sauce burnt, so it’s going to be extremely difficult to clean the pot.
to gauge – to measure something; to determine how much of something there is
* How do teachers gauge their students’ progress in developing writing skills?
to brown – to cook something, usually meat, for a short period of time so that part of it changes to a brown color
* It’s a good idea to brown the meat in a pan before placing it in the slow cooker.
to seal in the juices – to quickly cook the outer sides of a piece of meat so that the liquids stay inside it while it cooks for a long time at a lower temperature
* Grandma taught us how to seal in the juices, but some foods scientists say that doesn’t actually work.
medium – meat cooked a moderate amount, so that it is still a little bit pink
* A medium steak is done when it’s still a little bit soft to the touch.
doneness – a measure of how cooked something is, especially when talking about meat
* How do chefs keep track of the doneness of each piece of meat when they’re cooking for so many people at once?
overcooked – cooked too much; cooked for too long
* Please stir the oatmeal and turn it off before it becomes overcooked.
raw – not cooked at all; without any heat preparation
* Do you prefer to eat cooked carrots or raw carrots?
rare – cooked very little, so that meat almost appears to be raw
* That meat is so rare that it still looks bloody!
to ooze – for a liquid to slowly come out of something else, especially when being squeezed
* This dessert is oozing with chocolate!
to live to tell about (something) – to survive a particularly dangerous and/or exciting experience, ready to share one’s stories about it with others
* Sure, crossing Antarctica is dangerous, but imagine the stories we’ll have if we live to tell about it!
Comprehension Questions
1. Which of these is cooked the most?
a) A steak cooked to medium doneness
b) A steak that is raw
c) A steak that is rare
2. Why doesn’t Chris like steak that is well done?
a) Because it doesn’t taste very good.
b) Because it is difficult to chew.
c) Because it is too hot.
Answers at bottom.
What Else Does It Mean?
tough
The word “tough,” in this podcast, means to difficult to chew and not tender: “These cabbage leaves are really tough unless you boil them.” The phrase “tough love” describes a way of being kind to other people, but also very strict to teach them a lesson: “They believe in tough love, so when their daughter ran out of money before her next paycheck, they fed her but refused to give her cash.” The phrase “tough as nails” means very strong and able to succeed in difficult situations: “Wow, that man must be tough as nails if he survived alone in the forest for that long.” Finally, the phrase “When the going gets tough, the tough get going” means that the strongest people do whatever is necessary in order to survive and succeed in difficult situations.
raw
In this podcast, the word “raw” means not cooked at all, and describes food prepared without any heat used: “Is it safe to eat raw eggs?” The phrase “raw materials” refers to things that are in their natural condition and have not been processed: “This factory takes raw materials and produces lumber and other building materials for the construction industry.” The phrase “raw data” refers to information, especially numbers, that have been gathered but have not yet been organized or analyzed: “Please analyze the raw data and give us a one-page memo about your findings.” Finally, the phrase “rubbed raw” describes skin that is red and painful, and possibly bleeding, from repeated contact with a surface: “His feet were rubbed raw after hiking in new boots all day.”
Culture Note
Classic Dishes Made With Ground Beef
Many traditional American “dishes” (prepared foods) are made with “ground beef” (beef that is cut into very small pieces). Perhaps the best-known dish is a hamburger, made with a “hamburger patty” (made by pressing ground beef into a small, round, flat shape) and vegetables between two pieces of bread.
“Meatloaf” is made by mixing ground beef with eggs, “bread crumbs” (very small pieces of bread), “ketchup” (a sweet, tomato-based sauce), and “spices” (dried parts of plants used for flavoring) and then shaping the mixture into a “loaf” (the shape of bread) and baking it in the oven. It is typically sliced and served for dinner, but the “leftover” (saved for later because something was not eaten the first time it was prepared or served) slices might be eaten in a sandwich.
“Salisbury steak” is similar to meatloaf, but it is shaped to look like a piece of steak rather than a loaf. It is usually baked and served with side dishes, often potatoes or other vegetables.
A “sloppy joe” is similar to meatloaf, but it has more ketchup or tomato sauce and is more like a sauce. It is eaten on bread, but is very “sloppy” (messy) and falls out of the bread and onto the plate.
Finally, many Americans like to make “meatballs” out of ground beef, mixing it with onion, spices, and tomato sauce, and often serving it in a tomato-based sauce over “pasta” (noodles).
Comprehension Answers
1 - a
2 - b