= 1212
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,212 – Providing Tech Support.
This is English as a Second Language Podcast episode 1,212. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Yeah.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode.
This episode is a dialogue between Max and Grace about providing “tech,” or “technical,” support. Let’s get started.
[start of dialogue]
Max: Hello, hello, is this call-in tech support?
Grace: Yes, my name is Grace and this is the help desk. How can I help you today?
Max: I’m having a problem with my machine and I don’t know what to do.
Grace: Have you tried reading our online troubleshooting guide or asking your question on the support forum?
Max: The what?
Grace: Never mind. Can you describe the problem you’re having?
Max: It doesn’t work.
Grace: I understand that. What exactly is the malfunction?
Max: It’s not working.
Grace: For me to diagnose whether it’s a software or hardware problem, I’ll need more information. Unfortunately, I can’t repair it remotely.
Max: Okay, I understand.
Grace: Good. We offer all kinds of support, from setup to customization to disaster recovery, but I can’t do anything if I don’t understand the problem.
Max: Okay.
Grace: Could you walk me through what happens when you turn on the machine?
Max: Nothing.
Grace: Nothing? Nothing at all?
Max: Zip, zilch, zero.
Grace: Sir, is the machine plugged in?
Max: Oh, it needs to be plugged in?
[end of dialogue]
We are listening to a telephone conversation in today’s dialogue. Max calls the “tech support,” or “technical support,” department of a company. “Tech support” refers to the people who help you with some problem usually related to your computer or a piece of software – a computer program or application on your computer.
Max says, “Hello, hello, is this call-in tech support?” “Call-in” refers to someone who is calling by telephone to get help on something. Max is calling the tech support department. He’s not emailing them or going in and visiting them in person. Grace says, “Yes, my name is Grace and this is the help desk.” The “help desk” is the department that provides tech support and other assistance at a company. The help desk might also answer your questions about “billing” – that is, paying for your software or some service you are getting.
Grace says, “This is the help desk. How can I help you today?” Max responds, “I’m having a problem with my machine and I don’t know what to do.” His “machine,” here, is his computer. Grace says, “Have you tried reading our online troubleshooting guide?” “Online” means on the internet, on the web. “Troubleshooting” (troubleshooting) – all one word – refers to the process of identifying the cause or reason for a problem and finding a solution for it. Many websites have a “troubleshooting guide” that will help you find the answer to the question you have or a solution to the problem you have.
Grace also asks Max if he’s asked a “question on the support forum” (forum). A “support forum” is a website or message board on which people put questions and other people put answers. Some big companies have support forums where you can go and ask a question and another person, often another person who uses the same application or the same computer, will be able to answer that question.
Max is confused by Grace’s question. He says, “The what?” He doesn’t know what Grace is talking about when she refers to the “troubleshooting guide” and the “support forum.” Grace says, “Never mind.” This is a very common expression in English, “Never mind.” It’s a phrase that we use to show that we don’t need an answer to the question we just asked or simply to indicate that something is not important enough to repeat. Grace is telling Max to forget about the question she just asked.
Instead, Grace asks another question. She says, “Can you describe the problem you’re having?” Max says, “It doesn’t work.” Well, this doesn’t help very much. Max says, “It doesn’t work.” Well, what doesn’t work? What do you mean it doesn’t work? Max is not giving a very good description of this problem.
But Grace is very patient. She says, “I understand that. What exactly is the malfunction?” A “malfunction” (malfunction) is when something doesn’t work correctly, when it doesn’t function correctly. “Function” is another word here for “work,” as in “operate,” as in “do what it’s supposed to do.” But we still don’t know what exactly is the problem. And Max doesn’t help very much. He says, “It’s not working.” Well, once again, this is not a very good answer since we don’t know what Max is talking about.
Grace says, “For me to diagnose whether it’s a software or hardware problem, I’ll need more information.” The verb “to diagnose” (diagnose) means to identify the cause or the reason for a problem. It is often used in medicine by doctors. Doctors “diagnose” the illness or the disease that patients have. The doctor tries to figure out what is wrong with you. That is the process of “diagnosing” the illness.
Tech support people also diagnose problems. They try to find out why your computer software or your computer isn’t working correctly. That’s what Grace is trying to do. She’s trying to diagnose whether this problem is related to “software” or “hardware.” “Software” (software) refers to computer applications, or what we now simply refer to as “apps” (apps). “Software” is made by writing what is called “code” (code), which is basically a set of instructions that tell your computer what to do. “Hardware” (hardware) refers to the physical computer itself.
Grace says she needs more information from Max. “Unfortunately,” she says, “I can’t repair it remotely.” “To repair” (repair) means to fix something that is broken. “Remotely” (remotely) means, here, “from a distance.” Many people nowadays work “remotely.” They don’t go to their company, to the office where their company is located, to work. They work from their house or from a café. That’s working remotely. Grace says she cannot fix Max’s problem remotely – that is, from where she is now.
Max says, “Okay, I understand.” Grace says, “Good. We offer all kinds of support, from setup to customization to disaster recovery, but I can’t do anything if I don’t understand the problem.” Grace mentions some things that her tech support department does, including “setup” (setup). “Setup,” as a noun, is the process of preparing a computer to use it for the first time.
“Customization” (customization) is when you change something so that it fits your particular needs or wishes. It does exactly what you want it to do. Often, software will come with certain features, certain things that it does, but you want it to only work in a certain way, so you go in and you change the software somehow so that it works exactly the way you want it to work for what you want it to do. That’s “customization.”
“Disaster recovery” is usually the process of helping you get your computer working again after a major problem. If you drop your computer into the water, for example, that would probably ruin your computer. It would cause it to stop working. You might need “disaster recovery” in order to get the information off of your computer – the “data,” we would say, off of your computer. That’s an example of “disaster recovery,” I think.
Grace says, “Could you walk me through what happens when you turn on the machine?” “To walk someone through” means to explain something to someone else step-by-step, using very specific details about what is happening. If you ask someone “to walk you through a problem,” you’re asking the person to tell you exactly what happens first, and then second, and then third, and so forth. Grace is asking Max to walk her through what happens when he turns on the machine. Max says, “Nothing.”
Grace is confused. “Nothing? Nothing at all?” she says. Max says, “Zip, zilch, zero.” Grace is asking Max what happens when he tries to turn the machine on, and Max says nothing happens. Grace is surprised that nothing happens. Max then says, “Zip, zilch, zero.” “Zip (zip), zilch (zilch), zero (zero),” all mean the same thing: “nothing.” It’s an informal way to emphasize that nothing is happening. In the U.S. sometimes people use the Spanish word nowadays, “nada” (nada), which also means “nothing.”
Grace says, “Sir, is the machine plugged in?” Notice the use of the word “sir” (sir) here. It’s a formal way of addressing a man, of saying something to a man. You might hear it in a formal business situation such as this. Grace, after all, is working for a company, trying to help the company’s customer.
Grace asks Max if the machine is “plugged (plugged) in.” A computer and most machines nowadays require some sort of electrical power. You get that power either from the battery or from the electrical system in your house or building. You have to connect your computer to the electrical system by using a long piece of wire. The verb we use to connect that wire to the electrical system is “to plug in.” You “plug in” your computer. You connect your computer to the electrical power in the building or house where you are.
Max says, “Oh, it needs to be plugged in?” Max doesn’t realize that his computer needs electrical power, which of course means that Max isn’t all that intelligent. He’s not very bright. He’s kind of stupid, in other words. Grace doesn’t say anything. She just sighs. She goes [sigh]. Grace can’t believe that Max didn’t even plug the computer in. That, of course, is Max’s problem.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Max: Hello, hello, is this call-in tech support?
Grace: Yes, my name is Grace and this is the help desk. How can I help you today?
Max: I’m having a problem with my machine and I don’t know what to do.
Grace: Have you tried reading our online troubleshooting guide or asking your question on the support forum?
Max: The what?
Grace: Never mind. Can you describe the problem you’re having?
Max: It doesn’t work.
Grace: I understand that. What exactly is the malfunction?
Max: It’s not working.
Grace: For me to diagnose whether it’s a software or hardware problem, I’ll need more information. Unfortunately, I can’t repair it remotely.
Max: Okay, I understand.
Grace: Good. We offer all kinds of support, from setup to customization to disaster recovery, but I can’t do anything if I don’t understand the problem.
Max: Okay.
Grace: Could you walk me through what happens when you turn on the machine?
Max: Nothing.
Grace: Nothing? Nothing at all?
Max: Zip, zilch, zero.
Grace: Sir, is the machine plugged in?
Max: Oh, it needs to be plugged in?
[end of dialogue]
Your English will never malfunction if you listen to and learn from the wonderful scripts written by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
call-in – receiving questions and comments by phone calls from the public or from a listening audience, without knowing ahead of time who will call
* Every Friday evening, the radio station has a call-in program where listeners call in with questions about relationships and the host tries to provide advice.
tech support – technical support; assistance in operating a piece of equipment, hardware or software, especially related to computers
* Does your company still provide tech support for the 2007 version of the software?
help desk – the department and area where people provide technical support and other assistance to people who request it
* The people at the help desk have software that allows them to take control of computers remotely so that they can see what is actually happening.
troubleshooting – the process of identify the cause of a problem and finding the solution to it
* Through careful troubleshooting, they were able to determine that the cause of the error was a poor connection between two wires.
support forum – a website or online message board on which people post questions about how to do something or how to use a particular piece of hardware or software, and answers are suggested by other users and/or people employed by the company that sells the product
* Please search for answers to your questions in the support forum before you call the company to request technical support.
never mind – a phrase used to show that one does not want to answer a question or to show that something is not important enough to repeat
* A: What did you say?
B: Never mind, it isn’t important.
malfunction – an instance in which something does not work correctly, especially when talking about a computer program; a problem that results in an error message
* The space shuttle experienced a minor malfunction, but fortunately, it didn’t put the astronauts in any danger.
to diagnose – to identify the nature and cause of a problem or illness
* The doctor diagnosed him as having a stomach disorder.
software – a coded program that runs on a computer and makes it perform in a certain way or complete particular calculations or tasks
* The ideal candidate for the job will have expertise in statistical software.
hardware – machinery, tools, and computers; equipment
* What kind of hardware will we need if we want every employee to have access to the new system?
remotely – from a distance; off-site; not at a specified location
* I’ll be in Singapore during the meeting, so I’ll call in to participate remotely.
setup – the process of preparing a computer or other equipment for its first use, including all the settings and configurations
* The initial setup of the new computer required hooking up a lot of hardware and rebooting several times.
customization – the selection of specific features, settings, and configurations so that a product more closely meets one’s needs and wishes
* The auto industry is providing more customization to customers, allowing them to select the fabrics, colors, sound systems, and other features that they want to have in their new cars.
disaster recovery – the process of helping a company return to its original state after a major problem, such as a flood or fire that destroys buildings and data
* Software companies must have a disaster recovery plan that specifies how they will protect and retrieve customers’ data if there is a natural disaster.
to walk (someone) through – to explain something to someone in great detail, step by step, and in order
* Who is going to walk the new employee through our accounts payable system?
zip, zilch, zero – absolutely nothing, said informally for great emphasis
* A: You haven’t lost a single pound after being on a diet for three weeks?
B: Zip. Zilch. Zero.
plugged in – connected to an electrical wall outlet by a cable
* If the lamp is plugged in, but won’t turn on, you probably need to replace the light bulb.
Comprehension Questions
1. What would you expect to find in an online troubleshooting guide?
a) A list of everything that has gone wrong.
b) A list of all the potential problems.
c) A list of suggestions for fixing problems.
2. What does Grace mean when she says, “I can’t repair it remotely”?
a) She can’t fix it from a distance.
b) She can’t fix it by herself.
c) She can’t fix it without receiving compensation.
Answers at bottom.
What Else Does It Mean?
remotely
The word “remotely,” in this podcast, means from a distance, off-site, and not at a specified location: “More and more companies are allowing their employees to work remotely, as long as they prove they can get the work done on time.” When used negatively, as in “not remotely,” the word can mean not at all or not in any way: “They were not remotely interested in our proposal.” Or, “Why does he keep telling those stupid jokes? They’re not remotely funny.” Sometimes the word “remotely” means slightly or only a little bit: “That smell is remotely familiar, but I can’t quite figure out what it is.” Finally, a “remote control” is the small device that allows one to change the channel and control the volume on a TV without being physically attached to the TV: “I want to change the channel. Who has the remote control?”
zip, zilch, zero
In this podcast, the words “zip,” “zilch,” and “zero” all mean none or nothing, and can be used separately or in combination: “These are all volunteers, so they receive zip, zilch, zero for their work.” Or, “Do you have any money left?” “Nope, zilch.” As a verb, “to zip” means to close or fasten something together with a zipper (long rows of metal or plastic teeth that hook into each other): “If you’re cold, try zipping your jacket closed to prevent the wind from making you feel colder.” The verb “to zip” also means to go somewhere or do something very quickly: “How did you zip through the grocery store in less than 10 minutes?” Finally, the phrase “zip it” is a rude way to tell someone to shut up, be quiet, and not say anything else: “I don’t want to hear you complain about that again. Just zip it!”
Culture Note
Multi-tiered Tech Support
Businesses often offer multi-tiered tech support to improve their customer service. Multi-tiered tech support allows businesses to place technical support “personnel” (staff; employees) and services into different “tiers” (groups) to meet their customers’ needs.
The lowest tier, sometimes referred to as “Tier 0” is a “self-help” tier in which customers can try to find the information themselves, without speaking to employees. This tier might include “FAQs” (a list of frequently asked questions and their answers) or online “manuals” (written instructions) in which users might find the answers to their questions and troubleshoot their problems without speaking to anyone.
The next tier, “Tier 1,” focuses on the most common and simplest problems. The tech support specialists in Tier 1 collect basic information about customers, such as names, phone numbers, email addresses, which “version” (edition) of the software is being used, and a simple description of the problem. In Tier 1, the representative might go through simple list of questions with the customer to identify the problem and possible solutions.
If the problem cannot be solved in Tier 1, it might be “bumped” (moved up) to “Tier 2” in which the tech support specialists have more technical knowledge. If they cannot identify or solve the problem, then the issue might be bumped to “Tier 3” where “programmers” (people who write software; coders) work.
If the problem still cannot be “resolved” (solved; with a solution found), the complaint might go to “Tier 4,” which is outside of the business. At this point, a “vendor” (the company that sells something) of related hardware or software might need to become involved in finding a solution.
Comprehension Answers
1 - c
2 - a