= 1213
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,213 – Using Different Payment Systems.
This is English as a Second Language Podcast episode 1,213. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store with additional courses in Business and Daily English to help you improve your English even faster than you are now by listening to this podcast.
This episode is a dialogue between Petra and Ken about trying to pay for something using different payment systems. Let’s get started.
[start of dialogue]
Petra: Damn! That didn’t work either.
Ken: What are you doing?
Petra: I’m trying to pay for a new service I ordered, but the website won’t accept my credit card as payment. I even tried my debit card, but it’s been rejected, too.
Ken: Why don’t you just write a check and mail it in?
Petra: I don’t have any checks. In this day and age, I should be able to use one of the many electronic funds transfer options.
Ken: What are going to do now?
Petra: I might try sending a wire, but my bank charges a large fee for wires.
Ken: How about signing up for direct deposit?
Petra: If this were an ongoing service I would, but this is a one-time thing. Do you think I could try your credit card?
Ken: I don’t know about that . . .
Petra: All right, if you feel funny about doing that then could you buy me a gift card for this website and then I can turn around and use the balance?
Ken: That seems kind of involved. Would you pay me back in cash?
Petra: Of course. I will write you an IOU right now and then go to the bank tomorrow.
Ken: How about if you go to the bank now. I’ll even give you a ride.
Petra: Is that really necessary? We don’t even know if it’s going to work.
Ken: When it comes to money, I always say “better safe than sorry.”
[end of dialogue]
Petra begins our dialogue a little angry, so angry he uses a “swear (swear) word.” A “swear word” is a word you use when you are angry that is not a very nice word, not a word you should use in front of children or your boss. Petra says, “Damn! That didn’t work either.” The swear word here, of course, is “damn” (damn). It’s a word some people use when they are frustrated or angry. Petra seems to be angry because something didn’t work.
Petra explains, “I’m trying to pay for a new service I ordered, but the website won’t accept my credit card as payment.” Petra is buying something on the web, on the internet, but the website she is using won’t accept her credit card as payment. A “credit card,” you probably know, is a small plastic card that you can use to pay for things. There are a couple of large companies that have credit cards you can use, including MasterCard and Visa as well as several others. You can use your credit card on the internet as well by putting the numbers of your card into the website.
Petra says this website won’t accept her credit card as “payment” – that is, money that you give to someone from whom you are buying something. Petra says, “I even tried my debit (debit) card.” A “debit card” is a card that takes money directly out of your bank account. A “credit card” is when you buy something and a company, a bank, lends you money, basically, until you pay it back. If you pay it back within 30 days, usually the bank will not charge you any money. When you use a credit card, you are essentially making a series of loans from the bank, and these are loans that you have to pay back.
If you don’t pay them back, the bank will charge you interest. That’s what we call a “finance (finance) charge.” Some people have to pay lots of money every month in “finance charges” because they don’t have enough money to pay for the loans that they took out that month from their credit card company. We don’t usually call them “loans.” We call them “charges” (charges). When you call them “charges,” people don’t think of them as loans anymore. This is a very smart way that credit card companies get you to spend more money.
Anyway, Petra is angry because she hasn’t been able to use either her credit card or her debit card. She says, “The debit card has been rejected” (rejected). When your credit card is “rejected,” you are not allowed to use it. Another word here would be “denied” (denied). If your credit card is “denied,” you are not able to use it. The bank is saying, “No, you can’t use it.” Ken says, “Why don’t you just write a check and mail it in?” A “check” (check) is a small piece of paper that you can use to take money out of your bank account.
Remember, a “debit card” is a way of electronically taking money directly out of your bank account. A “check” is another way of taking money out of your bank account in order to give it to another person. The problem is that Petra doesn’t have any checks. This isn’t that unusual nowadays. Many people don’t have paper checks anymore because they pay for everything either with a credit card or a debit card or some other way of paying electronically.
In fact, that’s exactly what Petra says. “In this day and age,” she says, “I should be able to use one of the many electronic funds transfer options.” The expression “in this day and age” means nowadays or in modern times, I guess you might say. She’s saying she should be able to use an electronic funds transfer option. “Electronic Funds Transfer” is moving money between two bank accounts or two different financial accounts without using any paper money or any paper checks.
Ken says, “What are you going to do now?” Petra says, “I might try sending a wire, but my bank charges a large fee for wires.” A “wire” (wire) is when you send money electronically between two banks. It’s a particular way of sending especially large amounts of money between two banks. This can be more expensive because banks often charge or make you pay a large fee, a large amount of money, for wires.
Ken says, “How about signing up for direct deposit?” “Direct deposit” is another way of electronically transferring money from one bank account to another. Usually “direct deposit” is the term we use when your company pays you by giving you money not with a paper check, but by depositing or putting that money directly into your bank account. In other words, the money is transferred from your company’s bank account to your bank account. However, sometimes this term is used to describe the way people pay their bills electronically.
For example, every month I have to pay the gas company the money that I owe them. But I don’t send them a check. I have that money directly withdrawn, or taken from my bank account, and put into their bank account. That arrangement can also be called sometimes a “direct deposit payment.” I’m not sending the company, the gas company, money through the mail. I’m paying them electronically from my bank account to their bank account.
Petra says, “If this were an ongoing service, I would. But this is a one-time thing.” An “ongoing (ongoing) service” is one that continues over a long period of time, one that repeats every month or every six months or every week, even. Petra doesn’t want to use a direct deposit system because “this is a one-time thing.” “One-time” means it is only going to happen a single time. It is only happening once. “Do you think I could try your credit card?” Petra asks. Ken says, “I don’t know about that.” Ken doesn’t want Petra using his credit card to buy this thing over the internet.
Petra says, “All right. If you feel funny about doing that,” meaning if you don’t think it’s a good idea, you think it’s strange, or you feel uncomfortable about it, “then could you buy me a gift card for this website and then I can turn around and use the balance?” A “gift card” is usually a small plastic card like a credit card that you buy for someone else so that that person can use it to buy things at a certain store. So, you go to a big store and you buy a $50 gift card for someone. That person can then buy something at that store, but only at that store, using that $50 gift card.
Gift cards now can also be used electronically. That’s what Petra is suggesting that Ken do for her. She will then use this gift card that Ken buys her to buy something on that website. That’s what she means by the expression “use the balance” (balance). The “balance” refers to the amount of money on the gift card, in this case. “Balance” can also refer to the amount of money you have in your bank account.
Ken says, “That seems kind of involved,” meaning this seems a little complicated – too complicated. He then asks, “Would you pay me back in cash?” “To pay someone back” is a two-word phrasal verb meaning to return the money that you borrowed from someone else. If I loan you $100, I expect you to pay me back – to give that money back to me in the future. Ken asks if Petra is going to pay him back “in cash” – that is, in paper money.
Petra says, “Of course. I will write you an IOU right now and then go to the bank tomorrow.” An “IOU” is a piece of paper, usually, with the three letters I, O, and U. “IOU” means “I owe (owe) you (you)” money. It’s a way of indicating that you have borrowed money from someone and that you are promising to pay it back. That’s not the same, of course, as getting the money back in cash, which is what Ken wants.
Ken says, “How about if you go to the bank now. I’ll even give you a ride.” Ken says to Petra, “I will drive you to the bank so you can get this money for me and give it to me right now instead of waiting until tomorrow.” Petra says, “Is that really necessary? We don’t even know if it’s going to work.” Petra doesn’t think it’s necessary that they go and get the money right away. Ken says, “When it comes to money,” meaning when we’re talking about or dealing with money, “I always say ‘better safe than sorry.’”
This is an old expression, “better safe (safe) than sorry (sorry).” This expression means that it is better to spend some extra time and do something so that you don’t hurt yourself or take any unnecessary risks, because if you don’t take that extra time – if you are not safe – then later you could be sorry. You could get hurt, and therefore you will be not very happy. So, it’s better to be cautious. It’s better to be safe – to move slowly, to do things very carefully – rather than moving quickly or carelessly and getting hurt or getting injured.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Petra: Damn! That didn’t work either.
Ken: What are you doing?
Petra: I’m trying to pay for a new service I ordered, but the website won’t accept my credit card as payment. I even tried my debit card, but it’s been rejected, too.
Ken: Why don’t you just write a check and mail it in?
Petra: I don’t have any checks. In this day and age, I should be able to use one of the many electronic funds transfer options.
Ken: What are going to do now?
Petra: I might try sending a wire, but my bank charges a large fee for wires.
Ken: How about signing up for direct deposit?
Petra: If this were an ongoing service I would, but this is a one-time thing. Do you think I could try your credit card?
Ken: I don’t know about that . . .
Petra: All right, if you feel funny about doing that then could you buy me a gift card for this website and then I can turn around and use the balance?
Ken: That seems kind of involved. Would you pay me back in cash?
Petra: Of course. I will write you an IOU right now and then go to the bank tomorrow.
Ken: How about if you go to the bank now. I’ll even give you a ride.
Petra: Is that really necessary? We don’t even know if it’s going to work.
Ken: When it comes to money, I always say “better safe than sorry.”
[end of dialogue]
The best way to improve your English is to listen to ESL Podcast on an ongoing basis – every day, if possible. That way, you’ll get to hear the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
credit card – a small plastic card that one uses to pay for items without paying cash, with an expectation to pay back the credit card company within a certain amount of time, often with interest
* Someone stole my credit card and starting buying things online!
payment – money given to a seller in order to receive some product or service
* How many car payments do you have left before you own your car?
debit card – a small plastic card that one uses to pay for items with money from one’s bank account
* Debit cards can help people control their spending, because they aren’t able to use it if there isn’t enough money in their bank account.
to be rejected – to not be allowed to have or do something; to be denied permission
* Her request for more time to submit the essay was rejected by the professor.
check – a small piece of paper with numbers that correspond to a bank account, filled in with the name of the payee (the person receiving money), the date, the amount of the payment, and the signature of the person making the payment, used to transfer money to another person or business
* Yes, we accept checks, but I’ll need to see two pieces of identification with your full name and at least one with your photo.
In this day and age – in modern times; these days
* In this day and age, it’s unusual to see men wearing formal hats.
electronic funds transfer – the movement of money between two accounts digitally, without actual paper bills or coins being involved
* Our rent is paid automatically each month using an electronic funds transfer. That way we don’t forget to make the payment on time.
wire – wire transfer; an electronic transfer of money between two banks
* When she teaches workshops overseas, her clients pay with a wire to her bank in the United States.
direct deposit – an electronic payment or transfer between two accounts that happens automatically, typically once per month, often used for salary or wages
* Most of our employees receive their paycheck via direct deposit, but a few of them prefer to receive paper checks.
ongoing – continuing; happening repeatedly over time, usually at regular intervals (times periods with pauses in between)
* They’ve been involved in an ongoing argument for almost 20 years!
one-time – happening just once; happening only a single time
* We’ve waived the late fee as a one-time courtesy, but in the future, you must pay your bills on time or you will have to pay a fine.
gift card – a small plastic card that represents a certain amount of money that can be spent in a particular store, typically given as a gift when the giver does not know what to buy
* Grandma and grandpa send each of the grandkids a $20 gift card to the bookstore on their birthdays.
balance – the amount of money in a bank account, on a gift card, or on a bill
* Many credit card owners pay off the full balance each month to avoid paying interest.
involved – complex or complicated, with a lot of details and things to pay attention to; not simple
* These calculations are really involved. Could you please help me with them?
to pay (someone) back – to return the money that one borrowed from someone earlier; to repay
* If you give me $20 today, I promise I’ll pay you back when I get paid on Friday.
cash – paper money and/or coins; not money on a debit or credit card or in a bank account
* Why do you keep so much cash in the house? It would be safer in a bank account.
IOU – I owe you; a small piece of paper with three letters (“IOU”) indicating that one has borrowed money but will pay the person back soon
* Clarke borrowed a few dollars from his daughter’s coin jar, but put in an IOU promising to pay her back later.
better safe than sorry – a phrase meaning that one is very cautious and wants to be careful, not taking any risks
* Making the kids wear helmets and brightly colored vests for a short bike ride around the neighborhood might seem to be too much, but better safe than sorry.
Comprehension Questions
1. Which of these forms of payment allows someone to borrow money?
a) A credit card
b) A debit card
c) An electronic funds transfer
2. What is a wire?
a) A promise to send payment later
b) An electronic money transfer
c) A deposit into one’s bank account
Answers at bottom.
What Else Does It Mean?
to be rejected
The phrase “to be rejected,” in this podcast, means to not be allowed to have or do something, or to be denied permission: “More than 10 job applications were rejected before he finally got an interview.” The verb “to reject” means to not accept someone or something: “Why did all the girls reject his invitation to the school dance?” Or, “The vice-president thanks us for our proposal, but rejected it.” The verb “to reject” also means to throw something away because it isn’t good enough: “What do grocery stores do with all the fruits and vegetables that are rejected by customers?” A “reject” is the object that is thrown away: “The computer manufacturer destroys all rejects so that they can’t be found and copied by competitors.” Finally, “reject” is a rude term for a person who is disliked or not accepted: “The prisons are filled with society’s rejects.”
wire
In this podcast, the word “wire” means a wire transfer, or an electronic transfer of money between two banks: “Once we receive your wire, we’ll provide instructions for opening your membership account and downloading the files.” A “wire” is usually a long, thin piece of metal that looks like a thread or small rope: “Do you know how to connect all the wires inside a car radio?” The phrase “to get (one’s) wires crossed” means to become confused in a conversation: “They almost missed their flight because they got their wires crossed while speaking with the clerk at the airline check-in counter.” Finally, the phrase “to come down to the wire” means to happen at the last minute, or to be finished immediately before the deadline: “We’re coming down to the wire, but very few of the students have submitted their assignments.”
Culture Note
Early Credit-based Payment Systems
Before the “advent” (creation and appearance) of credit cards, there was a large “untapped” (unmet; unfulfilled) need for credit. One of the first ways that stores and hotels “issued” (provided; offered) credit was through the use of “charge coins.” These were small, round coins made from plastic or metal with a small hole in the middle. People could put the coin on a “key chain” (the small ring of metal or plastic used to hold one’s keys together) and then, when they wanted to make a purchase, show the charge coin to the “clerk” (the person who accepts money in a transaction). The clerk would copy the number on the charge coin to a “sales slip” (receipt) and the person would be billed later. Charge coins became increasingly common the late 1800s through the 1930s.
Unfortunately, the charge coin did not include the name of the person who would be “held responsible for” (made to pay for) the charges, so it was easily stolen, resulting in “fraudulent” (dishonest and illegal) charges.
Beginning in the 1930s, stores began using the “Charga-Plate,” which was a small rectangle of metal that had the customer’s name and address. The plate was put into an “imprinter,” or a machine that transferred the “embossed” (raised print) letters onto the sales slip, at the same time creating a copy for the customer. Customers were able to sign the back of the card, and that way the clerk could compare the buyer’s signature to the signature on the back of the card, reducing the “potential for” (possibility of) fraud.
Comprehension Answers
1 - a
2 - b