= 1216
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,216 – Working in a Job You Love.
This is English as a Second Language Podcast episode 1,216. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com. When you do, you can take a look at our ESL Podcast Store, with additional courses in Business and Daily English. This episode is a dialogue between Lorna and Deangelo about working somewhere you really love to work. Let’s get started.
[start of dialogue]
Lorna: It’s great to be alive, isn’t it?
Deangelo: What are you so happy about?
Lorna: I’m just happy to come to work.
Deangelo: What?!
Lorna: I’ve come to realize that this is more than a job. It’s a vocation. I’m doing valuable work that I’m well suited for.
Deangelo: Are you on something?
Lorna: I’m high on life and my newfound sense of purpose. I realize that I’m doing this job because I have a calling and this is what I’m meant to do.
Deangelo: I’m serious. Are you coming down with something?
Lorna: Of course not. Yesterday, it occurred to me the legacy I’ll be leaving behind after my life’s work is done.
Deangelo: Life’s work?
Lorna: Yes, I’ll be remembered in posterity as someone who made a difference.
Deangelo: You do remember what you do for a living, right?
Lorna: I provide salve to people who need it. I give succor to those in need.
Deangelo: You serve drinks in a bar.
Lorna: I provide a shoulder to cry on, a calm voice in a crazy world.
Deangelo: Talk about delusions of grandeur!
[end of dialogue]
Lorna begins our dialogue by saying to Deangelo, “It’s great to be alive, isn’t it?” Lorna is very happy. She’s saying how wonderful it is to be alive. It is something you would say when you’re very happy. Deangelo says, “What are you so happy about?” Lorna responds, “I’m just happy to come to work.” Deangelo is shocked, very surprised by this answer. He says, “What?!”
Lorna says, “I’ve come to realize” – that is, I now understand – “that this is more than a job. It’s a vocation.” A “vocation” (vocation) is something that you feel you are called to do as your life’s work. The word “vocation” comes from the Latin term meaning “to call” – “vocare.” Your “calling,” then, is what you feel that God or destiny has given you as your life’s work, the thing that you believe you should be doing on this earth.
We sometimes use the word “vocation” to refer to those who go into the Christian priesthood or ministry. If you are going to become a minister or a reverend or a priest, we might say that is your “vocation.” But “vocation” can also be used to describe anything – any career, job, or work that you feel is something you are meant to do or destined to do or simply called to do by some greater power than yourself.
Lorna believes her job is a vocation. She says, “I’m doing valuable work that I’m well suited for.” “To be well suited” (suited) means to be appropriate for something, to be well matched. Some people are well suited to be athletes. They are born with bodies that are good for certain kinds of athletic activities. A thing may be well suited to a certain use. A hammer is well suited for putting nails into the wall. In fact, it is designed to do that. So, Lorna feels she is somehow designed to do the work she is doing. She’s well suited for it.
Deangelo still can’t believe that Lorna is saying what she is saying. That’s why he makes a joke in the next sentence. He asks Lorna, “Are you on something?” The expression “to be on something” means to be under the influence of drugs, especially illegal drugs. Lorna is not on drugs. She’s not on something. She’s not taking drugs. In fact, she says she’s just “high on life.”
The expression “to be high on life” means that you are just happy about your situation. The word “high” (high) usually means to be under the influence of illegal drugs such as marijuana. People who smoke marijuana “get high,” we say – that is, they get intoxicated by this drug in such a way that it changes their mood, the way they feel and think. Lorna is high on life, however, not on any drug.
She says she has a “newfound sense of purpose.” Something that is “newfound” (newfound) is something recently found or discovered, or perhaps just realized. I have a newfound respect for mothers. In talking to my own mother last weekend, I realized how much work it was to raise 11 children as she did. So, I now realize something I didn’t realize before, or I discovered something new. I have a “newfound sense of respect.” Lorna has a “newfound sense of purpose.” “Sense of purpose” is a reason for doing a particular thing, or perhaps a reason for living.
Lorna has a “sense of purpose” about her life. She now realizes why she is here on this earth, perhaps. She says, “I realize that I’m doing this job because I have a calling and this is what I’m meant to do.” A “calling” is the same as a “vocation.” Remember, we said that “vocation” actually comes from the Latin word meaning “calling.” That is, someone is calling you, someone is addressing you and saying “Do this.” Usually that someone is identified as God, in the traditional sense of a “calling” or “vocation.”
Deangelo says, “I’m serious.” He still can’t believe that Lorna is saying what she is saying. He says, “Are you coming down with something?” The expression “to come down with something” means to begin to feel sick, often with some common illness such as a cold or a flu. Someone may say, “I feel like I’m coming down with something.” He means, “I feel as though I’m getting sick.” Deangelo really thinks that Lorna is sick because she’s saying what he thinks are very strange things about loving her job.
Lorna says, “Of course not,” meaning no, I am not coming down with something. “Yesterday,” she continues, “it occurred to me the legacy I’ll be leaving behind after my life’s work is done.” Lorna says yesterday she realized the “legacy” she’ll be leaving behind. A “legacy” (legacy) is something that you do in life that will be remembered after you are dead, or something valuable that you have done that will continue to be valuable after you die.
A “legacy” is something you “leave behind” – that is, you leave for others to enjoy even after you are dead. Lorna believes she will be leaving a legacy after her “life’s work is done.” Your “life’s work” is everything you do or the most important things you do in your life. Perhaps someday my legacy will be ESL Podcast. Who knows?
Deangelo, once again, is still puzzled, still confused by Lorna and what she is saying. He says, “Life’s work?” He’s asking what she means by this phrase “life’s work” – what specifically is she talking about. Lorna says, “Yes, I’ll be remembered in posterity as someone who made a difference.” “Posterity” (posterity) refers to people born after you, many years, perhaps, after you. We might also use the expression “future generations” to describe “posterity.”
Lorna believes she is going to be remembered by people in the future as someone who made a difference – that is, who did something important or significant that changed the world somehow. Deangelo says, “You do remember what you do for a living, right?” The expression “do for a living” means what you do to earn money – your job or your work. Lorna says she does remember what she does for a living.
She says, “I provide salve for people who need it.” The word “salve” (salve) refers to a cream or a lotion, a thick liquid that protects your skin or heals your skin. It’s something you put on your body when you damage your skin. The word is not very common. It’s something that is a little poetic here. Lorna doesn’t actually put lotion on someone’s skin. She believes psychologically or emotionally, she is helping other people.
She says, once again continuing in this poetic way, “I give succor to those in need.” “Succor” (succor) means help or assistance or support for another person. It’s not a very common word in conversational English; neither is “salve.” But Lorna is being a bit poetic here.
Deangelo then reminds Lorna what her actual job is. He says, “You serve drinks in a bar.” That is, she gives people alcoholic drinks in a bar, which doesn’t sound like the kind of job that will make a big difference in people’s lives, though of course any job, if done well, could make a difference, so we shouldn’t be too skeptical of Lorna’s claims, though Deangelo certainly is.
Lorna in fact reminds him of an important part of her job. She says, “I provide a shoulder to cry on.” A “shoulder to cry (cry) on” refers to a person who is willing to listen to your problems, especially if things are going badly for you, and you perhaps feel like crying. “A shoulder to cry on” is a person who will listen to you, especially when you are going through difficult times. Lorna says she is “a calm voice in a crazy world.”
Deangelo still isn’t convinced. He says, “Talk about delusions of grandeur!” The phrase “talk about” is used to emphasize that another person’s comments are crazy or perhaps extreme or extraordinary. It’s often used when you are criticizing another person, or it might be used to give an example of something, a perfect example of something. Let’s say I go to a movie and it isn’t very good. I may tell my friend, “Talk about a horrible movie. That movie I saw last night was awful.”
Deangelo says, “Talk about delusions of grandeur!” Here he’s criticizing Lorna for what she is saying about how important her job is. The expression “delusions (delusions) of grandeur (grandeur)” refers to a belief that you are more important or more significant than you actually are. If you think you are the most important thing in the world, you probably have delusions of grandeur.
A “delusion” is a belief that is false – something that perhaps a crazy person might think of. Someone who thinks that he is Napoleon Bonaparte is having a delusion. He thinks something is true that isn’t true. “Delusions of grandeur” refer to someone who thinks that he is great or wonderful or perhaps famous, when he isn’t any of those things. Deangelo thinks Lorna has delusions of grandeur by thinking that her job is so important.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lorna: It’s great to be alive, isn’t it?
Deangelo: What are you so happy about?
Lorna: I’m just happy to come to work.
Deangelo: What?!
Lorna: I’ve come to realize that this is more than a job. It’s a vocation. I’m doing valuable work that I’m well suited for.
Deangelo: Are you on something?
Lorna: I’m high on life and my newfound sense of purpose. I realize that I’m doing this job because I have a calling and this is what I’m meant to do.
Deangelo: I’m serious. Are you coming down with something?
Lorna: Of course not. Yesterday, it occurred to me the legacy I’ll be leaving behind after my life’s work is done.
Deangelo: Life’s work?
Lorna: Yes, I’ll be remembered in posterity as someone who made a difference.
Deangelo: You do remember what you do for a living, right?
Lorna: I provide salve to people who need it. I give succor to those in need.
Deangelo: You serve drinks in a bar.
Lorna: I provide a shoulder to cry on, a calm voice in a crazy world.
Deangelo: Talk about delusions of grandeur!
[end of dialogue]
Our scriptwriter is well suited for her job of writing wonderful scripts. I speak, of course, of the one, the only, Dr. Lucy Tse, who makes a difference in the world of English.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
vocation – one’s job or career, especially one involving a lot of passion, dedication, and fulfillment, as well as a feeling that one was meant to do a particular type of work
* Very few college students have identified their true vocation, so they spend the first two years taking classes to explore many different types of careers.
well suited – well matched; adapted and appropriate for something; having the desired characteristics to fit something or someone else
* People who are good with numbers are well suited for jobs in finance, accounting, and engineering.
on something – under the influence of drugs, especially illegal drugs taken in order to improve one’s mood; not able to think clearly or rationally because one has taken drugs or medication
* You’re driving like you’re drunk! Are you on something?
high – under the influence of illegal drugs that cause one to feel very good and happy
* Have you heard about teenagers sniffing hairspray and glue to try to get high?
newfound – recently discovered, found, identified, or realized
* These newfound medicines will change the way that we treat cancer.
sense of purpose – a reason for existence; a reason for being a particular way or doing a particular thing; a feeling that what one does is important and significant
* Many people begin going to church to find a sense of purpose in life.
calling – what one is meant to do; the intended purpose of one’s life; the thing that one feels passionate about and is very good at doing
* Even as a young child, Wendy felt her calling was to help others.
to come down with something – to begin to feel sick with the common cold; to begin to have symptoms of an illness
* I’ve been sneezing all morning and I think I’m getting a fever. I must be coming down with something.
legacy – something that one does in one’s life that is remembered and continues to provides benefits or value after one’s death
* Rockefeller’s charitable donations left a legacy for future generations.
(one’s) life’s work – referring to all of the most important things that one has done in life, especially in one’s professional life
* This book summarizes my entire life’s work in biomedical research.
posterity – all future generations, especially the future generations in one’s own family
* We must find ways to preserve wild areas and natural environments for posterity.
to make a difference – to do significant and important things that have a real impact, especially things that help others or improve society in some way
* Becoming a teacher is one of the best ways to make a difference in the lives of others.
to do for a living – to earn money through one’s work; to make money to cover one’s living expenses
* We asked Jenny what she does for a living, and we were surprised to learn that she is a professional clown.
salve – a cream or lotion that protects or heals the skin, or something that provides comfort to another person
* His kind words were a salve for her hurt feelings.
succor – help, assistance, and support for another person who needs it
* What kinds of programs does the federal government offer as succor to low-income families?
shoulder to cry on – someone who is supportive and willing to listen to another person’s problems or sorrows and be sympathetic
* It sounds like you’re going through a difficult period. If you ever need a shoulder to cry on, I’m here.
talk about – a phrase used to emphasize that another person’s comments are obvious, extreme, or extraordinary
* Talk about a bad idea! Inviting your three sisters to spend a month in our house is the last thing I want to do.
delusions of grandeur – a belief that one is more important, significant, influential, or necessary than one actually is
* Kristoff suffers from delusions of grandeur. He seems to think this company would fall apart without his leadership.
Comprehension Questions
1. What does Lorna mean when she says, “I’m high on life”?
a) She is getting too old.
b) She is very happy to be alive.
c) She is pregnant.
2. What does Deangelo mean when he asks, “Are you coming down with something?”
a) He wants to know if Lorna is depressed.
b) He wants to know if Lorna needs a loan.
c) He wants to know if Lorna is feeling ill.
Answers at bottom.
What Else Does It Mean?
calling
The word “calling,” in this podcast, means what one is meant to do, or the thing that one feels passionate about and is very good at doing: “Jimmy’s calling has always been to entertain and to make other people laugh.” The word often refers to religious work: “The priest recognized his calling when he was quite young.” The phrase “name-calling” describes trying to insult or offend other people by using mean words to describe them: “The students were removed from the playground as punishment for their name-calling when the teacher heard them call each other ‘dummy’ and ‘idiot.’” Finally, a “calling card” is something that one leaves behind, indicating that one was there: “Those droppings are calling cards from the deer that live in the nearby woods.”
to do for a living
In this podcast, the phrase “to do for a living” means to earn money through one’s work, or to make money to cover one’s living expenses: “I don’t want to meet your parents until I’m able to tell them with pride what I do for a living.” The phrase “cost of living” describes how much money a typical person needs to pay the costs of housing, food, transportation, and other basic expenses in a particular place: “The cost of living in New York City and San Francisco is much higher than in rural areas.” Finally, a “living wage” refers to payment for one’s work that are enough to cover basic expenses: “This city needs more jobs that pay a living wage, or we will always have significant problems with homelessness.”
Culture Note
Job Corps
Since 1964, the U.S. Department of Labor has “administered” (operated; managed and run) the Job Corps, a program through which it provides education and “vocational training” (experience to prepare someone for a particular job or career) for people who are between 16 and 24 years old. The program began as part of former President Johnson’s “War on Poverty,” a number of efforts to reduce “poverty” (the condition of having little or no money) among American families. Job Corps provides assistance to about 60,000 young people each year and has provided services for approximately two million young people since its “inception” (when the program began).
The “beneficiaries” (people who benefit from something; people who receive services) of the program must be “legal U.S. residents” (people who have permission to live in the United States) who can “demonstrate” (prove with evidence) that they have a low income and need additional education and/or experience to get a job. They must not use illegal drugs and they must not have certain “behavioral problems” (unacceptable ways of acting).
The people who participate in Jobs Corps “pass through” (participate in and complete) four phases. The first is “outreach and admissions,” when they register for the program, provide information, and receive transportation to one of the job centers. The second phase is “career preparation” when they are tested and they receive training in basic job skills. The third phase is “career development,” when they receive more specific training in preparation for a specific vocation. And the final phase is “career transition” when Job Corps helps the students find a job as well as “housing” (a place to live) and other resources they will need for success.
Comprehension Answers
1 - b
2 - c