= 1221
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,221 – Buffing Up Home Security.
This is English as a Second Language Podcast episode 1,221. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and become a member of ESL Podcast or take a look at our ESL Podcast Store, which has additional courses in Business and Daily English that I know you’re going to like.
This episode is a dialogue between Joselyn and Martin about increasing or improving your security at home – making sure you are safe in your house. Let’s get started.
[start of dialogue]
Martin: Why do you look so upset?
Joselyn: Our neighbor’s house was broken into last night. The burglar stole her laptop and some jewelry. Like us, she doesn’t have a security system.
Martin: Burglar alarms aren’t foolproof. Well, I’m not letting any burglars get close to our house. Let’s go.
Joselyn: Where are we going?
Martin: To the home improvement store. We need to buff up our security. I want to install motion detectors, floodlights, and security cameras to the outside of the house.
Joselyn: I suppose that’s a good idea.
Martin: I also want to put a timer on our indoor lights and a better deadbolt for the front door.
Joselyn: Those will probably help.
Martin: We can find out the cost of metal bars for the windows and a security door.
Joselyn: Whoa, I think that might be a bit much.
Martin: Nonsense. If we’re going to do something, we’re going to do it right. Barbed wire on top of our fence would probably be next . . .
Joselyn: That’s not a good idea . . .
Martin: And last but not least, we’ll need an attack dog.
Joselyn: An attack dog?! This is sounding more like a military compound than a home.
Martin: That’s right. When I’m done, Fort Knox will have nothing on us!
[end of dialogue]
Martin asks Joselyn, “Why do you look so upset?” “Upset” (upset) means angry or concerned or worried. Joselyn says, “Our neighbor’s house was broken into last night.” The house of Joselyn’s neighbor – the person who lives next to her – was “broken into.” The phrasal verb “to break into” means to go into someone’s house or a building or a car without permission, usually to steal something. If the house was “broken into,” the house was entered by someone who probably went in to steal something.
In fact, that’s exactly what happened, as we learn in the next sentence. Joselyn says, “The burglar stole her laptop and some jewelry.” A “burglar” (burglar) is another word for a person who steals things – a “thief,” we might also call him. This “burglar” stole her neighbor’s laptop computer and some jewelry. Joselyn says, “Like us, she doesn’t have a security system.”
Joselyn’s neighbor does not have a “security system,” which is an electronic system that makes a loud noise or automatically calls the police if someone goes into a home or building without permission. Where I live here in west Los Angeles, lots of houses have security systems. Sometimes security systems are called “burglar alarms.” An “alarm” (alarm) is a noise or some sort of signal that tells you that there is a problem or that indicates that something needs your attention. A “burglar alarm” is another term for a security system.
Martin says, “Burglar alarms aren’t foolproof.” If something is “foolproof” (foolproof), it is very easy to use and cannot fail. The idea is that even a foolish or stupid person can use it correctly. Here it also refers to something that will always work, that will always be effective. But Martin says burglar alarms are not foolproof. Then he says to Joselyn, “I’m not letting,” or allowing, “any burglars get close to our house. Let’s go.”
Joselyn says, “Where are we going?” Martin says, “To the home improvement store.” A “home improvement store” is a store that sells things for fixing your house or making changes to your house. Martin says, “We need to buff up our security.” The phrasal verb “to buff (buff) up” means to make stronger or to increase the size or quantity of something. If you’re going “to buff up” your security, you’re going to make it stronger or increase your security.
We also use this word when talking about the human body. If you’re going “to buff up,” you’re going to make yourself stronger. You’re going to have bigger muscles. We might describe a man or a woman who has big muscles as being “buff.” That’s an adjective. As a verb, “to buff up” means to increase strength or size. Martin wants to buff up his security.
He says, “I want to install motion detectors, flood lights, and security cameras to the outside of the house.” These are three ways of increasing your security or how safe you are in a given place. One thing Martin wants to install, or put in, is a “motion detector.” The word “detector” comes from the verb “to detect” (detect). “To detect” means to notice or identify. A “motion detector” is an object that can notice or detect when someone is moving in front of it. A motion detector usually has a light attached to it so when you walk in front of it, the light automatically comes on.
“Floodlights” (floodlights) are large lights that produce a lot of illumination, a lot of light over a large area. They’re very strong lights. “Security cameras” are cameras that record videos of a certain area. Some buildings, for example, have security cameras. Martin wants to get security cameras for his house. Jocelyn says, “I suppose that’s a good idea,” referring to the idea of buffing up their security.
Martin says, “I also want to put a timer on our indoor lights and a better deadbolt for the front door.” A “timer” (timer) is a device, a little machine that automatically turns something on or off at a certain time every day. A timer on your indoor lights would automatically turn, say, a lamp or other light on inside your house so that people think that there is someone home, there is someone inside your house, even when you’re not there.
A “deadbolt” (deadbolt) is a lock on your door that is basically a piece of metal that goes through a hole. You have to use a key to turn the deadbolt to get the piece of metal to come out of the hole so you can open the door. It’s a more secure kind of lock on your door. Joselyn agrees that these things will probably help in buffing up home security. Martin continues, however: “We can find out the cost” – we can find out how much the price is – “of metal bars for the windows and a security door.”
Martin thinks perhaps they should get “metal (metal) bars (bars).” “Metal bars” are long, heavy or thick pieces of metal that go over your windows. In some houses here in Los Angeles, especially in some of the poorer neighborhoods, you will see metal bars on the windows. This prevents people from coming into the window. You can’t just break the window and enter the house because the metal bars will block you. Martin wants metal bars, or at least he wants to investigate putting metal bars on the windows of their house.
He also wants to get a security door. A “security door” is a very thick, strong door, often made of metal, but it could just be wood that is put on the front of a house or a building to protect it. Joselyn now thinks that Martin is perhaps overreacting – doing too much. She says, “Whoa,” meaning stop or wait, “I think that might be a bit much,” meaning too much. Martin says, “Nonsense.” He disagrees with Joselyn. That’s what that word “nonsense” means in this case: “I disagree strongly.” “If we’re going to do something, we’re going to do it right,” meaning we’re going to do it correctly.
He then says, “Barbed wire on the top of our fence would probably be next.” “Barbed (barbed) wire” are long, thin pieces of metal that have short, what we would describe as “spiky” bits to them – parts to them that will cut you if you touch them. You will sometimes see barbed wire on the top of fences or walls around some very secure area – a military installation or some other area where the business wants to prevent people from getting into that area.
“Barbed wire” is a pretty serious thing to put on top of your fence, and some cities don’t allow barbed wire unless you get special permission to put it there. Joselyn doesn’t think this is a good idea. Martin says, “And last but not least” – meaning this is the last thing I will mention, but it isn’t the least important – “we’ll need an attack dog.” An “attack dog” would be a dog that has been trained to attack people when ordered to do so, You could think of a big dog such as a German Shepherd or a Doberman Pincher.
Joselyn is now surprised at what Martin is saying. She says, “An attack dog? This is sounding more like a military compound than a home.” A “military compound” (compound) is an area of land that is owned by the army or some other military organization that is protected with a lot of security. Martin says, “That’s right. When I’m done, Fort Knox will have nothing on us.”
“Fort Knox” (Knox) is an army base located in the state of Kentucky in the United States, where the United States government traditionally has stored gold as part of the property of the U.S. government. Fort Knox is considered one of the most secure places in the U.S., or at least, traditionally was considered that way. People use that place now as sort of a representation of a very, very secure place. To say that my house is like Fort Knox means that my house is as secure or as safe as Fort Knox because it is protected very well.
That’s why Martin says when he’s done, Fort Knox will have nothing on them. When you use the expression “to have nothing on” someone, you mean that it will not be as good as what you have. So if you say, “He has nothing on me,” you mean he is not better than I am. I am better than he is, or at least I’m as good as he is. I could say, for example, “Well, Brad Pitt is handsome, but he has nothing on me when it comes to charm, when it comes to personality, when it comes to not having any hair.” He has nothing on me. He’s not better than me in those areas.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Martin: Why do you look so upset?
Joselyn: Our neighbor’s house was broken into last night. The burglar stole her laptop and some jewelry. Like us, she doesn’t have a security system.
Martin: Burglar alarms aren’t foolproof. Well, I’m not letting any burglars get close to our house. Let’s go.
Joselyn: Where are we going?
Martin: To the home improvement store. We need to buff up our security. I want to install motion detectors, floodlights, and security cameras to the outside of the house.
Joselyn: I suppose that’s a good idea.
Martin: I also want to put a timer on our indoor lights and a better deadbolt for the front door.
Joselyn: Those will probably help.
Martin: We can find out the cost of metal bars for the windows and a security door.
Joselyn: Whoa, I think that might be a bit much.
Martin: Nonsense. If we’re going to do something, we’re going to do it right. Barbed wire on top of our fence would probably be next . . .
Joselyn: That’s not a good idea . . .
Martin: And last but not least, we’ll need an attack dog.
Joselyn: An attack dog?! This is sounding more like a military compound than a home.
Martin: That’s right. When I’m done, Fort Knox will have nothing on us!
[end of dialogue]
Oscar-winning scriptwriters have nothing on our scriptwriter, Dr. Lucy Tse. She writes the best scripts here in Los Angeles.
From the home of Hollywood, I am Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to break into – to enter a home, another building, or a car without permission, usually by breaking a window or door, and usually to steal something
* Someone broke into our car last night and stole the radio.
burglar – thief; a person who steals things; a person who takes thing without permission
* The neighbors thought they heard a burglar last night, but it was just a neighborhood cat.
security system – an electronic system that makes a loud noise and/or automatically calls the police if someone enters the home without permission
* They gave their housecleaner the code for the security system so that she could enter and leave without setting off the alarm.
burglar alarm – a security system; an electronic system that makes a loud noise and/or automatically calls the police if someone enters the home without permission
* The burglar alarm went off and frightened away the thief.
foolproof – something that cannot fail; something that is very easy to operate or use, so that even a foolish or silly person can use it correctly
* This copy machine is foolproof. Just plug it in and push “copy.”
to buff up – to increase the strength, size, or quantity of something
* We need to buff up our anti-virus program so that our computer is safer.
motion detector – a light that turns on when someone or something moves in front of it, used to make it seem as if someone is home and scare away unwanted visitors
* Every time their cat walks across the driveway, the motion detector turns on.
floodlight – a large light that produces a lot of light over a large area
* The stadium has floodlights so that players can see what they’re doing when they practice and play games at night.
security camera – surveillance camera; a small, hidden video camera that records what happens at all times, especially when people are not aware that they’re being filmed
* Police officers were able to identify the bank robber when they saw his face on the footage from the security camera.
timer – a device that automatically turns something on or off at a particular time each day
* They programmed their timer so that their garden is watered each morning.
deadbolt – a door lock that requires turning a key or metal piece in the hole, not just relying on a spring
* Meghan asked her new landlord to install a deadbolt on the front door before she agreed to move in.
metal bars – long, heavy pieces of metal, sometimes plain and straight and sometimes decorative, placed in front of a window or door to make it impossible for someone to enter a home or building without permission
* In many cities, it’s common to see metal bars on doors and windows on the first and second floors, but not on higher floors.
security door – a door that offers extra protection and is very thick and strong, making it difficult or impossible for people to enter without permission
* Having a security door can keep your belongings safe, but only if you remember to lock it each time you leave the house.
barbed wire – wire (long, thin pieces of metal) that has many sections with short, spiky wire that are painful to touch, used to discourage or prevent people from moving past or over a fence or wall
* The prison yard is surrounding by several rows of barbed wire to make it more difficult for prisoners to escape.
attack dog – a dog that has been trained to attack people when it is commanded (ordered) to do so, especially to protect a certain person or piece of property
* They have an attack dog that is trained to bite any unwelcome visitors.
military compound – an area of land with many buildings and strong fences, used for housing and training soldiers
* The soldiers have to request special permission to leave the military compound and explore the city on weekends.
Fort Knox – a place that is almost impossible to enter or leave because it is very secure and safe, referring to an Army base in Kentucky
* This building has so many locks and scanners that it’s almost like Fort Knox!
to have nothing on (someone) – to not be as good, strong, or impressive as another person or thing
* That team has nothing on us! We’re going to win by at least 20 points.
Comprehension Questions
1. Which of these things turns on and off by itself?
a) Motion detectors
b) Floodlights
c) Security cameras
2. Which of these is most likely to cut your skin?
a) A deadbolt
b) Metal bars
c) Barbed wire
Answers at bottom.
What Else Does It Mean?
timer
The word “timer,” in this podcast, means a device that turns something on or off at a particular time each day: “Whenever they travel, they connect their lights to a timer to make it seem like they’re at home.” A “timer” is also a device that allows a particular amount of time to pass and then makes a loud noise: “Let’s put these cookies in the oven and then set the timer for 12 minutes so we remember to take them out before they burn.” A “part-timer” or “full-timer” is someone who works part time (less than 40 hours per week) or full time (40 or more hours per week): “We don’t have enough full-time employees, so we’ll hire a few part-time ones to help during the holiday months.” Finally, an “old timer” has lived somewhere for a long time and knows a lot about it: “The old timers remember the flood of 1947.”
compound
In this podcast, the phrase “military compound” means an area of land with many buildings and strong fences, used for housing and training soldiers: “Do you think they’re developing bombs and missiles on that military compound?” A “compound” is something made from at least two elements: “Table salt is a compound made from sodium and chloride.” A “compound word” is a word made by joining two other words: “The kindergarten students are learning about compound words like ‘sunlight,’ ‘fingernail,’ and ‘sailboat.’” Finally, when talking about finance, “compound interest” refers to how the amount of money grows when one receives interest, and then receives interest on the original money plus that interest that accumulates over time: “Thanks to compound interest, if you start saving early you can easily have one million dollars by retirement.”
Culture Note
Civil Defense Sirens
“Civil defense sirens” are “sirens” (things that make a loud noise as a warning to others) that are used to warn “civilians” (ordinary people who are not part of the military) about an “approaching” (going to happen soon) “danger” (something that can cause harm or death). They were first used in World War II to warn Americans about “air raids” (attacks from the air, specifically from airplanes or bombs). When Americans heard the civil defense sirens, they were supposed to run to a “bomb shelter” (a place designed to be strong enough to keep people safe during an explosion, often underground) or another safe place.
The sirens could produce a few different sounds. Some were “alerts” that were supposed to tell people to be “extra” (more than usual) “cautious” (careful). Other sounds warned people of an actual “attack” (an attempt to cause harm, damage, or death). During World War II, most of the sirens in the United States were designed to “sound” (make a noise) for a period of between three and five minutes.
Today, many of the World War II sirens have been “repurposed” (adapted for another type of use) to warn people about natural disasters. Some communities use the sirens to warn “residents” (the people who live somewhere) about dangerous “tornadoes” (very strong and very damaging windstorms) or even “tsunamis” (very large waves that cause damage to seaside towns after underwater earthquakes). Many of the sirens have been replaced by the use of the Emergency Alert System, which plays emergency messages on all local television and radio stations, as well as cell phones.
Comprehension Answers
1 - a
2 - c