= 1226
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,226 – Describing Sounds.
This is English as a Second Language Podcast episode 1,226. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode. You can also like us on Facebook. Go to facebook.com/eslpod.
This episode is a dialogue between Naomi and Omar about describing sounds that are made by humans and non-humans. Let’s get started.
[start of dialogue]
Naomi: Stop! Stop!
Omar: What’s the matter?
Naomi: My bike is making a strange sound.
Omar: What kind of sound?
Naomi: It’s a clanging sound followed by a hissing or buzzing noise. I need to pinpoint where it’s coming from.
Omar: Walk your bike and we’ll both listen, you on one side and me on the other.
Naomi: Okay, here goes. Hear that?
Omar: Yeah, but it’s more of a popping or pinging sound.
Naomi: It sounded different when I was riding it. I’ll get on and you run alongside. What do you hear?
Omar: I hear the whirring of the pedals and the creaking and rattling of the chain, but no clanging sound.
Naomi: I’ll speed up. What do you hear now?
Omar: Nothing, just the rustling of my own clothes.
Naomi: The sound gets louder as I speed up. I’ll go faster. Now what do you hear?
Omar: Just my own panting and . . . my . . . last gasp . . .
[end of dialogue]
Naomi shouts at Omar, “Stop! Stop!” Omar says, “What’s the matter?” meaning “What is wrong?” Naomi says, “My bike is making a strange sound.” A “bike” (bike) is a bicycle, something with two wheels and a seat, that you move by moving your legs up and down in a circle. Naomi says her bike is “making a strange sound,” a strange noise. Omar says, “What kind of sound?”
Naomi says, “It’s a clanging sound followed by a hissing or buzzing noise. I need to pinpoint where it’s coming from.” A “clanging (clanging) sound” comes when you have two pieces of metal that are hitting each other, such as two pans in your kitchen, something like this [clanging]. That’s a “clanging” sound. “Clanging” comes from the verb “to clang” (clang).
Naomi says the clanging sound made by her bike is followed by a “hissing” sound, or a “hissing noise.” “To hiss” (hiss) means to make a sound similar to what I guess a snake would make. In fact, we often describe the sound made by a snake as being a “hissing sound.” It sounds a bit like [hisses] – a bit like that. Naomi says her bike, which seems to be an amazing sound machine, also makes a “buzzing noise.” “To buzz” (buzz) is to make a sound like a bee – something like this [buzzes].
Naomi says that she needs “to pinpoint where it’s coming from.” “To pinpoint” (pinpoint) is to identify or find the exact place or location of something. Naomi wants “to pinpoint” where this noise is coming from. Omar says, “Walk your bike and we’ll both listen, you on one side and me on the other.” Omar is telling Naomi to get off of her bike and walk with the bike in her hands so that she can listen on one side of the bike and Omar can listen on the other side of the bike.
Naomi says, “Okay, here goes.” That expression “here goes” is used immediately before you try to do something, especially if you’re not sure if what you are going to do will be successful. For example, you may say to someone, “I’m going to sing you a song. I’m not a very good singer but, well, here goes,” meaning I’m now going to do it. I’m now going to, in this case, sing, even though I may not sing very well. I should probably say that every time before I try singing.
Naomi then says to Omar, “Hear that?” meaning “Do you hear that sound, that noise?” By the way, I’ve been using both the word “sound” and “noise” in this explanation. A “noise” is usually a sound that isn’t pleasant, that you don’t want to hear. If someone describes your singing as “noise,” as my singing has often been described, well, that means the person doesn’t like your singing very much. In any case, in our dialogue, Omar is trying to hear the noise that Naomi hears.
He says, “Yeah” – meaning yes, I hear that noise – “but it’s more of a popping or pinging sound.” Omar thinks that the sound the bike is making is more of a “popping” sound. “Popping” comes from the verb “to pop” (pop) which is to make a loud, short sound that is made, for example, if you have a balloon and then suddenly the balloon breaks. The verb we would use in that case would be “pop.” “The balloon pops.” It sounds something like this [popping sound].
Did I scare you there? Were you drinking your coffee and suddenly I made you spill it? Sorry about that. Oops, there I go again. That’s a popping sound. “To ping” (ping) is to make a higher pitched sound. It is made by two things hitting against each other. It sounds something like this [pinging sound]. We would describe that as a “pinging” sound, I think.
Naomi says, “It sounded different when I was riding it,” meaning the bike was making a different sound when Naomi was actually on the bike, riding it, rather than walking it as she was just now. She says, “I’ll get on” – meaning I will get on the bicycle – “and you run alongside. What do you hear?” “To run alongside” (alongside) means to run next to something or someone. Omar says, “I hear the whirring of the pedals and the creaking and rattling of the chain, but no clanging sound.”
Omar says he hears some sounds as Naomi is riding the bicycle, but they are different sounds. One of the sounds is coming from the “pedals” (pedals). The “pedals” of a bicycle are those two things you put your feet on in order to move the bicycle, in order to make the bicycle go forward. Your foot goes on the pedal. The “chain” (chain) of a bicycle connects the little wheel that you are spinning when you are moving the pedals up and down and the wheel in back of the bicycle – that round metal loop is called a “chain.”
The pedals, according to Omar, are making a “whirring” sound. “Whirring” (whirring) is a sound made by objects that are moving very quickly through the air. Another whirring sound would be made by a helicopter, for example [whirring sound]. Of course, a pedal doesn’t make a sound that loud. That’s a helicopter making a whirring sound. Omar describes the sound that the chain is making as a “creaking and rattling sound.”
We usually use the verb “to creak” when we are describing a piece of wood that you are walking on and is making a sound. An old floor made of wood, for example, would probably creak. I’m not sure if a bicycle chain would creak, but I guess it’s possible that something made of metal that is put under a lot of pressure might also creak, making a high-pitched sound again. Here’s wood “creaking” [creaking sound].
Interestingly enough, there’s another word we used to describe noise which is “squeaking” (squeaking). “Squeaking” sounds like “creaking” except it has a much higher pitch. The sound is a lot higher. Here would be an example of a door squeaking [squeaking sound]. So “creaking” is like “squeaking,” except it’s a lower sound.
“Rattling” is a noise that is made when two things are hitting each other. They could be made of metal or some other material. If you have a set of keys in your pocket, they could be “rattling” together, or a bunch of coins could “rattle” as they hit each other and made noise. Here would be an example of something “rattling” (rattling) – [rattling sound]. That’s a chain rattling. So, Omar doesn’t hear the “clanging sound” that Naomi heard. Naomi says, “I’ll speed up.” “To speed up” means to go faster, to increase your speed. Remember, Naomi is riding on her bicycle.
“What do you hear now?” Naomi asks. Omar says, “Nothing, just the rustling of my own clothes.” A “rustling” (rustling) sound is what we would describe as a gentle sound made by a soft object that is rubbing against another soft object. You can think of the leaves in a tree as rustling against each other as the wind blows through the trees. Here would be an example of a rustling sound, although it sounds like the wind is blowing rather strong in this example. Let’s listen [rustling sound]. That might be paper rustling in that example.
Omar says the only thing he hears is the rustling of his own clothes. He’s running so fast that he hears the wind against his own clothing. Naomi says, “The sound gets louder as I speed up. I’ll go faster.” Remember, Naomi is riding the bicycle and Omar is running next to her. She then says, “Now what do you hear?” Omar says, “Just my own panting and . . . my . . . last gasp . . .”
Omar is too tired to continue running. He says the only thing he hears is his own “panting.” “To pant” (pant) is something that a human or other animal does when it breathes very quickly. You can hear the sound coming from your mouth because you are very tired. If you run suddenly, or walk up a lot of stairs, you might pant. Because you are so tired, you have problems breathing.
Omar is panting and the only thing he can hear is the panting and his “last gasp.” Your “last gasp” (gasp) is the last thing you do before you die. It’s your dying breath. Sometimes you will hear on a TV show or movie someone who is just about to die, and the last thing you hear is their “last gasp” and then they die. Well, I didn’t die. I just finished our explanation.
And now we’ll listen to the dialogue one more time.
[start of dialogue]
Naomi: Stop! Stop!
Omar: What’s the matter?
Naomi: My bike is making a strange sound.
Omar: What kind of sound?
Naomi: It’s a clanging sound followed by a hissing or buzzing noise. I need to pinpoint where it’s coming from.
Omar: Walk your bike and we’ll both listen, you on one side and me on the other.
Naomi: Okay, here goes. Hear that?
Omar: Yeah, but it’s more of a popping or pinging sound.
Naomi: It sounded different when I was riding it. I’ll get on and you run alongside. What do you hear?
Omar: I hear the whirring of the pedals and the creaking and rattling of the chain, but no clanging sound.
Naomi: I’ll speed up. What do you hear now?
Omar: Nothing, just the rustling of my own clothes.
Naomi: The sound gets louder as I speed up. I’ll go faster. Now what do you hear?
Omar: Just my own panting and . . . my . . . last gasp . . .
[end of dialogue]
We love all the sounds made by our wonderful scriptwriter, Dr. Lucy Tse, and we thank her for her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
bike – a human-powered vehicle with two wheels, one seat, a handlebar, and no engine or motor
* Kevin often rides his bike to work so that he can save money on gas and get some exercise.
to clang – for two pieces of metal to hit each other, making a loud noise
* The children stayed up late on Christmas Eve, hoping to hear the clanging of the bells from Santa's sleigh.
to hiss – to make a sound like what is produced when air is pushed through a small opening, or a sound similar to that of a snake
* Normally, a snake will hiss as a warning before it attacks or bites a human.
to buzz – to make sounds like a low, rapid vibration, similar to the sound produced by a bee, fly, or other flying insect
* Whose phone is buzzing?
to pinpoint – to identify the exact location or identity of something
* We need to pinpoint the source of the leak so we can fix it.
here goes – an informal phrase used immediately before one tries to do something, especially if one does not believe it will succeed
* I don't think our plan will work, but we don't have any other options. Here goes.
to pop – to make a loud, short sound like the one produced when a balloon breaks
* Listen to the sound of the popcorn popping, and when the pops are two seconds apart, turn off the microwave.
to ping – to create a short, high-pitched electronic beeping or ringing sound, usually as a notification
* As the computer searches the atmosphere, it pings if it finds unusual radio signals.
alongside – next to something else, especially if both things are moving at the same speed
* Sheila's dog runs alongside her whenever she goes jogging.
whirring – the sound made by objects moving rapidly through the air
* It was hard to hear each other speak over the whirring of the helicopter blades.
pedal – one of two parts of a bicycle that one places one’s feet on to push and move a bicycle forward
* On steep hills, children sometimes stand on the pedals of their bicycles to have more power.
creaking – the sound made when a piece of metal or wood is under a lot of pressure and/or bends
* The screen door blows in the wind and makes a scary creaking sound at night.
rattling – the sound of two or more objects gently hitting against each other repeatedly as they move
* In many stories, people hear the rattling of chains before they see ghosts.
chain – the rope-like line of small metal loops or rings that transfer movement of the pedals into the movement of wheels on a bicycle
* Many cyclists wear shorts or tie their pants tightly around their ankles so that their pants don’t get caught in the bicycle chain.
to speed up – to increase one’s speed or velocity; to go faster
* They asked the taxi driver to speed up so that they could get to the airport on time.
rustling – the gentle sound of pieces of paper, fabric, or other soft objects rubbing against each other
* In the silence of the library, the rustling of papers seemed very loud.
to pant –to breathe quickly and loudly with one’s mouth open because one is very tired from physical effort or needs to cool off from extreme heat
* Why are you panting like that? Did you run here?
last gasp – dying breath; the last inhalation (breathing in air) before one dies, often used humorously
* I’d like to see the Grand Canyon before I take my last gasp.
Comprehension Questions
1. Which of these sounds could be made by metal?
a) Clanging
b) Hissing
c) Buzzing
2. What does Omar hear at the end of the episode?
a) The noise of a broken bicycle
b) The sound of the wind in his ears
c) His own heavy breathing
Answers at bottom.
What Else Does It Mean?
here goes
The phrase “here goes,” in this podcast, is used immediately before one tries to do something, especially if one does not believe it will succeed: “I don’t think this will work, but we don’t have any other options, so here goes.” The phrase is often expressed as “here goes nothing” to show that one is beginning to do something that will fail or not work as intended: “Our bid probably won’t be competitive against the other offers, but here goes nothing.” The phrase “it just goes to show” is used to emphasize the moral or lesson of a story: “They were audited by the IRS. It just goes to show that you should never lie on your tax return.” Finally, the phrase “it goes without saying” refers to something that most people understand: “It goes without saying that falling in love sometimes ends in heartbreak.”
chain
In this podcast, the word “chain” means the rope-like line of small metal loops or rings that transfer movement of the pedals into the movement of wheels on a bicycle: “The bike chain slipped off while I was riding up the hill, so I had to stop and fix it.” The word “chain” also refers to any other rope-like strand of metal loops: “Be gentle with that necklace, or the chain might break.” Or, “The prisoners were connected by chains.” A “chain” can also refer to many stores, restaurants, or hotels that have the same name and are owned by the same company: “Which grocery store chains are popular in the southern United States?” Finally, the phrase “a mountain/island chain” refers to a group of mountains or islands that appear to form a line: “Have you visited the Hawaiian island chain?
Culture Note
Jack Foley and the Art of Foley
Jack Foley (1891-1967) “left his mark on” (became well known and remembered for) the film industry by developing techniques for many popular “sound effects” (sounds heard in a movie, play, or TV show, but not made by the actors). He is best known for “incorporating” (including) “environmental” or “ambient” (in the surrounding area; happening around something) sounds into films, and the people who do this type of work today are known as Foley artists.
Previously, some people had used “pre-recorded” (created earlier) sounds and added them to films, but Foley changed this by creating the sounds “in real time” (when they were needed in the films). The sounds could include anything, such as a telephone ring, a “squeaky” (making a high-pitched sound) door, “footsteps” (the sound of one’s feet hitting the ground as one walks), or the sound of clothing rustling as one walks.
The sound effects are intended to “enhance” (improve; make better) the film, making it feel more “realistic” (similar to real life). Without those sound effects, films feel “empty” (missing something), too quiet, and even uncomfortable for the viewers. The sound effects should feel “seamless” (without being separate or different), so the audience doesn’t realize that those sounds are not what the actors are actually producing or interacting with.
Foley effects are especially important when films are “dubbed in another language” (with the dialogue being presented in another language), because when the dubbing replaces the original language, it also replaces all other sounds. As a result, those sounds must be added back in with each dubbed version.
Comprehension Answers
1 - a
2 - c