= 1242
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,242 – Having Difficulty Reaching a Group Decision.
This is English as a Second Language Podcast episode 1,242. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Join us on Facebook. Go to facebook.com/eslpod.
This episode is a dialogue between Derrick and Liz about having to agree with other people. It’s not easy, as we’ll learn. Let’s get started.
[start of dialogue]
Derrick: That does it. I give up!
Liz: Don’t lose heart. We’ll come to a consensus sooner or later.
Derrick: No, we won’t. We’re hopelessly deadlocked.
Liz: It’s true we’re evenly split right now, but we only need one person to change their mind to break the tie.
Derrick: The trouble is, everybody seems to have made up their minds and they’re beginning to dig in their heels.
Liz: Before they do, let’s take one more vote. Maybe somebody has changed their mind.
Derrick: I doubt it. Nobody wants to be outvoted so both sides are trying to maintain the status quo. They’d rather be deadlocked than on the losing side.
Liz: But if we don’t reach an agreement, we’ll have to come back tomorrow and continue our discussions and deliberations.
Derrick: You’re right! I can’t spend another day in this room. I’ve held out long enough.
Liz: What do you mean?
Derrick: The only way I’m getting out of here is to change sides!
[end of dialogue]
Derrick begins our dialogue by saying to Liz, “That does it. I give up!” The expression “That does (does) it” is used when you are angry and frustrated and you don’t want to put up with, or accept, or tolerate something any longer. If your neighbor’s dog is barking, making a lot of noise, you may decide after an hour that you don’t want to tolerate or accept that noise any more. So you say, “That does it. I’m going over to my neighbor’s house to tell the owner of that dog to keep him quiet.”
Derrick says, “That does it. I give up!” The phrasal verb “to give up” means to stop trying to do something, usually because it is too difficult. Liz, however, says, “Don’t lose heart.” “To lose (lose) heart (heart)” means to begin to think that something is impossible and that you should stop trying, in effect, that you should give up. “To lose heart” means, we could also say, “to be discouraged” – to feel as though you will not succeed at something.
Liz is telling Derrick not to give up, not to lose heart. “To lose heart” is a psychological or mental condition, if you will. “To give up” is an action – to stop doing something. “To lose heart” is to become discouraged, to think that you will not be successful. Liz says, “We’ll come to a consensus sooner or later.” A “consensus” (consensus) means an agreement, a situation in which most people in a group agree on something. So, obviously the situation here is that Derrick and Liz are in a meeting and not everyone agrees on what to do.
Liz thinks that the people in the meeting will eventually “come to a consensus.” Notice the use of the verb “to come to” a consensus. We might also say “to reach” a consensus. Derrick says, “No, we won’t. We’re hopelessly deadlocked.” “To be deadlocked” (deadlocked) means when people have very strong opinions on two sides of an issue – I think one thing, you think another – and they can’t agree on something. They can’t come to an agreement.
This happens sometimes with the government and government unions, or a big business and the workers for that business. They may become “deadlocked.” “To be hopelessly (hopelessly) deadlocked” means you have no chance of agreeing. “Hopelessly” means that there is no hope. There is no possibility of changing the situation.
Liz says, “It’s true we’re evenly split right now, but we only need one person to change their mind to break the tie.” “To be evenly split” (split) means that you have the same number on both sides of the issue or argument. So, if you have a group of six people, three people say one thing, three people say something else. They’re evenly split. “To change your mind” (mind) means to change your opinion – to say, “Well, I think I was wrong. I think this is correct instead.”
Liz thinks only one person has to change his or her mind in order “to break the tie.” A “tie” (tie) is the same as being evenly split – when in a group you have the same number of people saying yes and no. “To break (break) a tie” means that you are no longer evenly split. One person may change his mind and that would break the tie. There would be, that is, a “majority” – more than 50 percent of people who say one thing.
Derrick doesn’t agree. He says, “The trouble is,” meaning the problem here is, “everybody seems to have made up their minds and they’re beginning to dig in their heels.” There are two important expressions in that sentence. The first one is “to make up your mind.” “To make up your mind” means to reach a decision after having thought about something for a while. “To make up your mind” also usually means that you are certain about something, meaning you probably won’t change your mind in the future.
That’s why Derrick uses the second expression, “to dig (dig) in your heels (heels).” “To dig” as a verb usually means to take something and put it in the ground in order to remove dirt or some other substance. We use a “shovel” (shovel) to dig a hole in the ground. You move the dirt from one place so that you have a hole, a depression, a space that goes down in the ground. That’s “to dig.”
Your “heels” are the back part of your feet. If you are wearing shoes, the “heels” of the shoes are the back parts of the shoes that are on the ground underneath the back part of your foot, which we call the “heel.” So, if we put these two things together, “to dig in your heels” means literally to take the backs of your feet and to create a small hole in the ground with them. However, we use this expression as a way of saying “to be very stubborn” – to refuse to change your opinion, to refuse to change your mind.
You can sort of see the connection. If you are, for example, pulling on a rope and one person is pulling in one direction and you’re pulling in the opposite direction, you would naturally try to use your heels to dig in the ground to prevent your body from moving forward. That is more or less what the meaning of this expression is. It means to be stubborn, not to change your mind.
Liz says, however, that before people begin to dig in their heels, she wants to “take one more vote” (vote). “To vote” is when people indicate how they think about a certain matter or what their opinion is about a certain issue. She says, “Maybe somebody has changed their mind” – that is, maybe someone has changed his or her mind. Derrick says, “I doubt it.” He doesn’t think anyone has changed his mind.
He says, “Nobody wants to be outvoted.” “To be outvoted” (outvoted) is to lose a vote because one side has more votes than you do. Derrick thinks nobody wants to be outvoted, “so both sides,” both groups of people, “are trying to maintain the status quo.” The “status (status) quo (quo)” refers to the way things are now. “Status quo” is a Latin expression, and it refers to the current situation, the way things are right now without changing anything.
Derrick thinks people “are trying to maintain the status quo,” meaning they don’t want to change anything. He says instead “they’d rather be deadlocked than on the losing side.” In other words, they would rather not have an agreement than lose the vote, than to be on the losing side – the losing group, if you will – in the vote.
Liz says, “But if we don’t reach an agreement” – if we don’t come to a consensus – “we’ll have to come back,” or return, “tomorrow and continue our discussions and deliberations.” “Deliberations” (deliberation) means usually a careful, slow, detailed consideration of something. We talk about a group of people who are deciding whether someone is guilty or innocent of a crime – we call that group a “jury” (jury) – “deliberating” – that is, they’re making their decision carefully and slowly and by thinking and talking a lot about it.
Derrick says, “You’re right! I can’t spend another day in this room. I’ve held out long enough.” “To hold out” is a two-word phrasal verb meaning to continue to hold your position or to continue to have a certain opinion even when the situation is difficult or the situation is dangerous. “To hold out” means to stay where you are or to keep your opinion even though it is difficult.
Derrick says, “I’ve held out long enough.” Liz says, “What do you mean?” Derrick says, “The only way I’m getting out of here is to change sides!” “To change sides” (sides) means to change your opinion and join the other group – in this case, to join the group with whom you previously disagreed. So, Derrick is going to change his mind and change his vote so that the group is no longer deadlocked, so that they reach a consensus.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Derrick: That does it. I give up!
Liz: Don’t lose heart. We’ll come to a consensus sooner or later.
Derrick: No, we won’t. We’re hopelessly deadlocked.
Liz: It’s true we’re evenly split right now, but we only need one person to change their mind to break the tie.
Derrick: The trouble is, everybody seems to have made up their minds and they’re beginning to dig in their heels.
Liz: Before they do, let’s take one more vote. Maybe somebody has changed their mind.
Derrick: I doubt it. Nobody wants to be outvoted so both sides are trying to maintain the status quo. They’d rather be deadlocked than on the losing side.
Liz: But if we don’t reach an agreement, we’ll have to come back tomorrow and continue our discussions and deliberations.
Derrick: You’re right! I can’t spend another day in this room. I’ve held out long enough.
Liz: What do you mean?
Derrick: The only way I’m getting out of here is to change sides!
[end of dialogue]
The consensus is that the world’s greatest scriptwriter is our very own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
that does it – a phrase used in anger when one is very frustrated and will not accept or tolerate something any longer
* That does it! The next person who complains about my cooking is going to be sent to bed without any dinner!
to give up – to stop trying to do something, usually because it seems too difficult and one does not believe one can succeed
* Don’t give up now. You’re almost done! Just two more miles to go!
to lose heart – to become discouraged; to begin to think that something is impossible and that one should stop trying
* What would have happened if the Wright brothers had lost heart when their first airplanes didn’t fly? Airplanes may not have been invented until many years later.
consensus – agreement; a situation in which most people agree on something
* We’re going to stay in this conference room until we can reach a consensus on how to handle this difficult situation.
hopelessly deadlocked – with people strongly on both sides of an issue so that they clearly cannot and will not reach an agreement
* The jury became hopelessly deadlocked, even after the judge gave them more time for discussion.
evenly split – with an equal number of people on each of two sides of an issue, so that an agreement cannot be reached
* With three people voting ‘yes’ and three people voting ‘no,’ the committee was evenly split.
to change (one’s) mind – to change one’s opinion; to no longer believe what one used to believe
* Marguerite was going to wear a blue dress to the awards ceremony, but then she changed her mind and wore a red dress instead.
to break the tie – to enter a situation where people are evenly split (see above) and to state one’s opinion or place one’s vote so that one side becomes the winner by having more supporters than the other side
* If the committee members cannot reach an agreement, then the committee chair must vote to break the tie.
to make up (one’s) mind – to reach a decision after one has been uncertain; to become certain about one’s decision or position
* How did you make up your mind on which job offer to accept?
to dig in (one’s) heels – to be very stubborn; to refuse to give up or give in; to refuse to change one’s opinion or decision
* The more you try to persuade Kevin, the more likely he is to dig in his heels.
vote – a process through which people indicate which person or idea they are in favor of, usually by raising their hand or indicating their choice in writing
* How long will it take the state to count up the vote in the elections?
to be outvoted – to lose because the other side has received more votes
* Mom wants to have dinner at home, but she was outvoted by the rest of the family.
status quo – the way things are now; the current situation or circumstances as they would normally remain if nobody interfered
* We need to spend less. If we choose to maintain the status quo, we’ll be bankrupt within two years.
on the losing side – being part of the group that is losing an election or competition and has less support than the opposing group
* Jacob doesn’t like to be on the losing side of any fight and will continue to argue no matter what.
deliberation – continued discussion and debate; careful, slow, and detailed consideration of something
* They’ve been discussing the issue for hours. How much longer do you think their deliberations will continue?
to hold out – to continue to survive or hold one’s position under difficult, challenging, or dangerous circumstances
* The few remaining soldiers won’t be able to hold out much longer. We need to send in additional troops.
to change sides – to change one’s opinion and join the group that one previously disagreed with or opposed; to switch sides
* The new research results caused many scientists to change sides in the debate about global warming.
Comprehension Questions
1. What does Derrick mean when he says, “We’re hopelessly deadlocked”?
a) He thinks their lives are in danger.
b) He would rather die than continue to disagree.
c) He doesn’t think they’ll ever reach an agreement.
2. What happens if someone maintains the status quo?
a) The person begins to appear more important or powerful.
b) Nothing changes and things continue as they always have.
c) The person finds a way to end a serious disagreement.
Answers at bottom.
What Else Does It Mean?
to lose heart
The phrase “to lose heart,” in this podcast, means to become discouraged or to begin to think that something is impossible and that one should stop trying: “How do doctors avoid losing heart when so many of their patients die?” The phrase “from the bottom of (one’s) heart” means sincerely, with one’s strongest beliefs and feelings: “Thank you from the bottom of my heart.” The phrase “the heart of (something)” means the core or essence of something, or the main or most important part of something: “The heart of the problem is really a lack of communication.” Finally, the phrase “at/in the heart of (something)” means in the middle or center of something: “They bought a small home in the heart of the downtown area.”
to hold out
In this podcast, the phrase “to hold out” means to continue to survive or hold one’s position under difficult, challenging, or dangerous circumstances: “How long do you think we can hold out against this storm?” In a negotiation, the phrase “to hold out” means to not accept an offer and instead continue to wait for something better: “We thought they would accept our last offer, but I guess they’re still holding out for more money.” The phrase “to hold (one’s) own” means to perform well or defend oneself against someone who is stronger or better prepared: “We were all impressed that the team was able to hold its own against much older and bigger players.” Finally, the phrase “to hold sway” means to have a lot of influence or power: “The CEO’s opinion holds sway throughout all of our business dealings.”
Culture Note
Grounds for Mistrial
A “mistrial” happens when a “trial” (legal proceedings; a court case) is “rendered invalid” (found to not be proper or legally applicable) because of problems in the “proceedings” (the official steps of the trial). The “grounds” for mistrials are the reasons the trail was rendered invalid, and they include many possibilities.
Sometimes mistrials are “called” (determined and announced) when something happens during the trial that “unduly” (too much; improperly) influences the “jurors” (the group of people who decide whether someone has broken the law). For example, there could be an “outburst” (a loud, emotional response to something) in the courtroom, or it could be proven that one of the jurors had a close relationship with the person on trial or his or her lawyer. Sometimes mistrials are called because a juror was found to have drunk alcohol during a break.
If a lawyer, “judge” (the top authority in a courtroom), or juror becomes ill or injured, or is unable to continue participating in the trial for any major reason, that could be grounds for mistrial. And if there is a “hung jury” (a jury that is “deadlocked” and cannot reach agreement), that can also be grounds for a mistrial.
When there is a mistrial, the trial has to be rescheduled. This benefits the “defendant” (the person who is trying to prove his or her innocence), because the “witnesses’” (the people who observed a crime or can speak about the people involved) memories “fade” (become less) over time, and “victims” (people who were hurt by a crime) are often “reluctant” (do not want) to “relive” (experience something again) the crime in a second trial.
Comprehension Answers
1 - c
2 - b