= 1779
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 474.
This is English as a Second Language Podcast’s English Café episode 474. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member of ESL Podcast. If you do, you can download a Learning Guide for this episode. Are you on Facebook? Hey! So are we. Go to facebook.com/eslpod and like us – and you can follow us on Twitter, why not, at @eslpod.
On this Café, we’re going to talk about how you can work in one of the fastest-growing medical areas in the United States, dentistry. We’re also going to talk a little bit about a law that was passed back in 1856 in the United States that allowed anyone to claim that a piece of land belonged to the United States – the so-called “Guano Island Act.” And, as always, we’ll answer a few of your questions. Let’s get started.
Our first topic in today’s Café is about becoming a dentist. A “dentist” (dentist) is a doctor that takes care of your teeth. Dentists also take care of other parts of your mouth – in particular, your gums. Your “gums” (gums) are the parts of your mouth that the teeth grow out of.
Most people visit their dentist, well, at least once a year, often even more frequently – say, every six months – in order to get a checkup and a cleaning, what we might call a “routine cleaning.” A “checkup” is when the dentist looks at your teeth, perhaps take some x-rays – some special photographs of your teeth – to make sure that you don’t have any problems.
A routine cleaning is when the assistant to the dentist, a person we call the “dental hygienist,” uses special tools to make sure that your teeth are very clean. We call it a “routine cleaning” because “routine” (routine) means something that is done as part of a regular process. You don’t say to yourself, “Oh, my teeth seem dirty. I’m going to have them cleaned.” Instead, you go for a routine cleaning, which is every six months or every year you get your teeth cleaned just as part of keeping them healthy.
One of the things that the dental hygienist does when he or she cleans your teeth is remove what is called “plaque.” “Plaque” (plaque) is a covering on your teeth, a substance on your teeth, where bacteria can grow and potentially damage your teeth. So, you want to get rid of this plaque, and that’s what the dental hygienist does. The dentist, in addition to looking at your gums and making sure they are okay, that they’re healthy – the dentist also repairs any teeth that have holes in them or that might somehow be broken. We call holes in the tooth “cavities” (cavities).
If you brush your teeth every day – if you clean them, as well as remove any food in between the teeth using a process we would call “flossing” (flossing), then you shouldn’t have any, or are unlikely to have any, cavities. But if the dentist discovers cavities, the dentist will have to fix them. Some dentists may also talk to you about the food that you eat, what we would call your “diet” (diet) to make sure you’re not eating any kinds of food or drinking any kinds of drink that might damage your teeth, especially things with a lot of sugar, I guess. At least that’s what my dentist told me.
How do you become a dentist in the United States? Well, you have to go, not surprisingly, to a place called “dental school.” Before you can go to dental school, however, first you must graduate with a four-year bachelor’s degree. This is different than the way it works in some countries. In some countries, you can go from high school to studying medicine, including dentistry.
But in the United States, first you have to get a four-year, what we would call, “undergraduate degree.” Usually that’s in some sort of scientific area, though I suppose it could be in another kind of area as well. You’re not required to have a degree in science, but most people who become dentists do. In order to go to dental school in the U.S., as is true in other areas of what we would call “graduate education” – the kind of education you get after your four-year bachelor’s degree – you have to take a test.
In the case of dentistry, it’s called the “Dental Admission Test.” This is a test that you take normally in your third, or “junior,” year of college. While the test doesn’t guarantee – doesn’t promise you – that you will have a place in dental school, it does help dental schools decide which students they want to accept. Schools look at your Dental Admission Test scores as well as your grades in college to determine if you are going to be someone they want to “admit,” or let study at their institution.
Once you make it into dental school, you will take a variety of courses to learn about dentistry. You take courses in a lot of different areas. One area is involved with giving a patient anesthesia. “Anesthesia” (anesthesia) is basically a kind of drug that is given a patient so that the patient doesn’t feel any pain. If the dentist is going to work on your teeth, he or she will want to make sure that it isn’t going to be too painful. So, the dentist might give you an injection of a certain kind of drug (the most common is called “Novocain”) that prevents you from feeling pain.
In dental school, you also have to study anatomy. “Anatomy” (anatomy) is the basic study of the human body – where the different parts of the body are, how they function, and so forth. We want our dentists to know something about the rest of your body. a dental school student would also typically study something called “Periodontics.” “Periodontics” (periodontics) is the general study of the mouth and of diseases that can affect your mouth, especially the gums in your mouth.
In addition to taking classes, dental students also usually work with patients under the supervision of a licensed dentist. In most states in the United States, probably in all of them, in order to be a dentist, you have to get a license from the state government. There are no national dental licenses, just as there are no national licenses for doctors. Everything in the U.S. is done – when it comes to medical licenses, that is – by the individual states.
A “licensed dentist,” then, is someone who has permission from the state to be a dentist. Dental schools will often give care at a very low cost to members of the community who want it. However, in order to get that care, you have to agree that one of the students will be working you. Now, I did this when I was in college. I didn’t have a lot of money. I was in graduate school. I needed to go to the dentist, so I went to the USC Dental School. I was attending as a student at the University of Southern California, so it made sense for me to go to their dental school.
I must say it was pretty cheap. I’m not sure how good a job they did, but I still have all my teeth. So, I guess they did okay. Anyway, the dental school students need to practice on real live human beings, and so that’s why usually dental schools will have these special clinics where people can come in and the dental students can work on them under the supervision of a licensed dentist. In other words, the licensed dentist is making sure the student is doing the right thing.
Some dental students continue their studies to specialize in a specific area of dentistry. These would include such things as “oral surgery,” involving, say, cutting a tooth out of your mouth or putting a new tooth in. Other areas include “orthodontics” and “pediatric medicine.” “Pediatric” (pediatric) refers to children. So, a pediatric dentist is a dentist that specializes in giving dental care to children.
“Orthodontics” usually is related to straightening the teeth – making sure the teeth are straight, that they are not crooked. An orthodontist usually can charge more money than a regular dentist. It can be quite expensive to get care from an orthodontist, but if you need to straighten your teeth – if your teeth are crooked – well, that’s the person you go to.
I mentioned one of the specialties in dentistry is being an oral surgeon. Oral surgeons, in addition to taking care of people’s teeth when they’re older, often work with children who have what we would call “birth defects.” A “birth defect” (defect) is a condition that a baby is born with that requires typically some sort of medical intervention. You need, for example, to fix something with the child that the child was born with that isn’t working properly.
I think it’s safe to say – I think I can say this without being too controversial or with too many people disagreeing with me – that most people don’t like going to the dentist. It’s sometimes uncomfortable; sometimes it hurts, especially if you’re getting your teeth cleaned or if the dentist has to fix a cavity. However, dentists are often the only doctor that some people visit on a regular basis.
That’s why dentists have to know about more than just teeth. They have to also be able to detect or notice problems in other parts of the body that are displayed or that can be noticed in the mouth. It might be something like cancer or even heart disease. Many diseases affect the mouth even though the source of the disease is somewhere else in the body. Dentists will often see problems in the mouth that require the patient to go and see another doctor.
It normally takes you about four years to complete your dental school training, although some do it in a shorter amount of time, but four years is the average. So, the total amount of schooling after you leave high school is about eight years.
Once you’ve finished dental school, you still have to pass the examination that the individual state will give you in order to get a license to practice, or work as a dentist, in that state, and if you want to be a specialist – say, an orthodontist – you have to study even more – in addition to the four years you spend in dental school, often two to three years more – in order to be able to be a specialist in one of these areas of dentistry.
So, it takes a long time to become a dentist, just as it takes a long time to become a doctor in the U.S. If you’re in it for the money – that is, if you are doing something because you want to make a lot of money – dentistry is a pretty good option. The average dentist in the U.S. makes about $145,000 dollars a year. However, you can make even more if you become a physician. The average physician makes close to $200,000 a year.
Our second topic on this Café is, I think, a very interesting one. It has to do with a law that was passed in the middle of the nineteenth century here in the U.S. – the year was 1856 to be exact. The name of the law is the Guano Island Act. Now, most Americans have never heard of the Guano Island Act. I had never heard of it until I saw an article about it recently.
At the time that the act was passed, the United States was searching for natural resources that were important in making fertilizer. The U.S. had, of course, a large part of its population working in the area of agriculture – growing food – and one of the things that helps when you’re growing food is to have fertilizer. “Fertilizer” (fertilizer) is a substance or product that you put in the dirt to help the plants grow.
I said the U.S. was looking for some natural resources to make fertilizer. A “natural resource” would be something that is made, if you will, by nature, something that you can take and change and make money from – copper and gold and silver could be considered natural resources. The ability to generate power from water might be considered a natural resource. The water would be the natural resource. You take something that you find, and you are able to use it somehow to help your economy or to make money.
Now, most fertilizer traditionally has been made from what we would call “excrement.” “Excrement,” not to get too detailed, is basically that which comes out of your body from the food that you eat. I think you get the idea. Another word we might use for that is – especially from animals – is “dung” (dung). Well, “guano” is a kind of bird dung, and in the nineteenth century, this guano, this bird dung, was added to fertilizer.
As the United States grew and its population increased, it needed more fertilizer in order to grow food, and therefore, it needed more guano. The Guano Island Act, amazingly, said that any U.S. citizen who found large quantities of guano was allowed to say that the place where they found it was part of the United States. Now, you could only do this in land that no other country had claimed.
You couldn’t just, say, go to Canada and say, “Oh, here is some guano. I claim this for the United States. I’m saying this belongs to the United States.” That’s not what the act said you could do. It said you could do this if the land was not claimed by any other country or if no one from the country that claimed that land was actually living there.
Now, we talk about land here. We’re really referring to islands in the ocean. Many islands are claimed by countries even though no one actually lives on them. After the Guano Island Act was passed, people started going out and finding these islands where no one was living and claiming them as part of the United States. This happened in the Caribbean, in the Atlantic Ocean. It also happened in the South Pacific, where islands had lots of guano and no humans.
After 1900, people started using fertilizer that was made from artificial materials instead of guano. When I say “artificial” (artificial), I mean they’re made by man, by human beings. They’re not found in nature like guano. This meant that the U.S. no longer needed all of this guano for its fertilizer. So, the government began to give the land back to the countries that the land originally belonged to and that the United States basically stole from.
They gave back a lot of land, but not all of it. Some of the land that was taken under the Guano Island Act still belongs to the United States government or is controlled by the U.S. There is an island, for example, near the country of Haiti in the Caribbean called Navassa Island. No one lives on this island, but the U.S. government still holds onto it even though Haiti claims, probably rightly, that it is part of their country.
Navassa Island is only about 5 miles square (that would be about a little more than 14 kilometers square). It is run by the U.S. Department of the Interior. This is a part of the federal or national government that is in charge of national parks and energy resources. One of the reasons the United States continues to hold onto Navassa Island is because of the very good fishing that exists just off the island. Because the U.S. controls the island, it also controls the valuable water around the island.
Another island that has remained in the possession of the U.S. government that was not returned to the original country to which is belonged is called the Johnston Atoll. An “atoll” (atoll) is a small island formed by a hard substance called coral. You will find lots of the atolls in the South Pacific, and that’s where the Johnston Atoll is. It’s about 940 miles or so (that would be a little more than 1500 kilometers) west of the Hawaiian Islands in the Pacific. Once the United States no longer needed the guano on the island, it found another use for the island a few decades later: nuclear testing.
Back in the 1950s and the 1960s, when the United States was testing nuclear weapons, it used the Johnston Atoll as a place for testing these weapons, these bombs. The atoll was later used to keep dangerous chemical weapons. Nowadays it is still controlled by the military and the national government. You can’t just go to the atoll. You need special permission in order to visit. I’m not sure why you’d want to visit it, although some scientists are interested in studying the water and the wildlife in the area. Although I’m surprised there is any wildlife after all of that nuclear testing.
The Guano Island Act would probably not be considered legal under international law standards today – perhaps it wasn’t even back in the nineteenth century – but when countries want things, they often come up with good reasons or what they think are good reasons to get them, and in the nineteenth century, the reason was bird dung.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Khaled (Khaled) in Egypt. Khaled wants to know the difference between “classic” and “classical.” The word “classic” (classic) means that it is considered to be a very high quality, something that is one of the best of that sort of thing. For example, we could talk about “classic American movies” like The Godfather or Casablanca. “Classic” here means that, judged against other types of works across time or over a historical period, this is one of the best.
“Classical” is slightly different. “Classical” (classical) can refer to either a certain historical period – specifically, the ancient Greek and Roman periods – or it can refer to a kind of music – actually, a couple of different kinds of music, as we’ll see. When we talk about “classical Greek literature” or “classical literature in Latin,” we’re talking about the ancient world between . . . let’s say 600 BC and 580 AD roughly, okay. We’re talking about the ancient Greek and Roman civilizations for the most part.
“Classical” refers to things from that time period. People who study that period, especially the literature of that period, are called “classicists,” and the field of study at the university might be called “classics,” but notice there’s an “s” at the end. The first word we defined, “classic,” is singular – has no “s.” The study of the ancient world, especially ancient literature, is called “classics,” with an “s” at the end. It’s very confusing, I know.
There’s another meaning of “classical” – the second word – which refers to a type of music, or actually both a type of music and a type of art (or perhaps more properly a style of art). When talking about music, “classical” can refer just to any kind of serious music, music that is not considered pop music – music such as the works of Beethoven and Bach and, I don’t know, Grieg and Tchaikovsky and Dvorak – all of these would be considered classical composers who write classical music.
Classical music also has a specific historical period that we call “classical” to distinguish it from, say, music that was older. That period begins roughly in the early eighteenth century and ends in the early nineteenth century. It would include composers such as Mozart and Haydn and some of Beethoven’s earlier works. That style of music is sometimes called classical, although in some books – to make even more confusing – they’ll call it “classic music.” But “classical” is probably a bit more common to refer to the musical style.
Similarly, artwork from this period – paintings and sculptures – is also sometimes referred to as “classical” or, again, “classic,” but classic in the sense of referring to a specific style and “sensibility,” we could say, not to the fact that it was considered among the greatest of that period.
So, to review: the normal meaning of “classic,” if you see it in a sentence such as “the classic novels” or “the classic movies” of a country, refers to the highest quality art or highest quality works in a specific field. Confusingly, both “classic,” as we’ve seen, but most particularly “classical,” are also used to talk about specific historical periods in art and music. “Classical” also refers generally to any kind of serious music by composers whose works would probably be played by an orchestra. The word “classical” is also applied to the art, culture, and literature of ancient Greece and Rome.
Our next question comes from Gilsa (Gilsa) in Brazil. Gilsa wants to know the meaning of a couple of expressions that often appear in love songs in English. The first expression is “to be there for” someone – “I’ll be there for you.” The second expression is “I will take you there.” Well, let’s start with the first one.
“To be there (there) for” someone means to support someone, to help someone who may need help. There was a song that was used for the television show Friends that had the words “I’ll be there for you” – something like that. That’s the idea that you will be there to support that person, to help that person, and to love that person, although it doesn’t necessarily mean that you are in love with the person. “To be there for” someone means to be helping them, to be assisting them in some way.
When someone says “I will take you there,” they are referring to bringing the person to a different place or perhaps to a different emotional state. It really depends on the song – I suppose there could be some sort of sexual meaning also to the expression. It would depend on what the song was about.
Finally Ali (Ali) in Iran wants to know the meaning of the expression “after full deliberation.” Let’s start with the word “deliberation” (deliberation). “Deliberation” comes from the verb “to deliberate,” which means to consider or think about something very carefully. “Full deliberation” would be thinking about everything necessary in order to make a decision or to reach a conclusion. So, “after full deliberation” would be after you have taken time to think about it thoroughly, to think about all the possible aspects of this situation.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
routine – something that is done as part of a regular process and not for any special reason; actions done regularly
* Our morning routine is to get up at 6:30 a.m., eat breakfast, and leave the house by 7:30.
plaque – a sticky substance on teeth where bacteria (very small living things that cause disease) can grow and then eat away at the tooth
* Most toothpastes claim to fight plaque all day long, but some do a better job than others.
diet – the kinds of food that a person or animal normally eats each day
* Some people are allergic to dairy products like milk and cheese so have to follow a strict diet to avoid them.
anesthesia – a drug that is given to patients to help them not feel any pain, usually given before a medical procedure or operation
* Javier needed surgery to repair the broken bones in his foot and was given anesthesia so that he would be asleep for the entire procedure.
anatomy – the study of the body structure of humans, animals, and other living things
* The anatomy of a pig is very similar to that of a human, despite the fact that pigs and people look nothing alike.
periodontics – the general study of the mouth and of diseases that can affect the mouth
* When her teeth started falling out, Sadia’s friend who had studied periodontics, suggested that she might have a rare gum disease.
licensed – having passed a test given by the government or another recognized organization and/or satisfied certain requirements and been given permission to work in a specific area
* If you need to replace the water lines, it’s best to hire a licensed plumber.
birth defect – a medical condition that is not considered normal and that a person is born with
* Hank was born with a birth defect and only has three fingers on his left hand.
natural resource – a substance or material existing in nature that can be used, often to make money, such and water and trees
* Oil is a natural resource that this country is very dependent on for heating and transportation.
fertilizer – a substance that is put on dirt or soil to help plants grow
* The farmers put fertilizer on their newly planted crops each year to ensure that the plants grow quickly.
guano – bird dung; bird excrement; the waste that comes out of a bird’s body
* Petra could tell that the birds were back and nesting in the trees outside her house again because of all the guano on the sidewalk.
artificial – man-made; not appearing in nature
* Amir lost his leg in a car accident but was able to get an artificial leg made for him that allowed him to walk.
classic – judged over time to be of the highest quality and outstanding of its kind
* Do you like to watch classic movies, or do you prefer the latest releases?
classical – (art or music) representing the best or the traditional standard; traditional and long-established; relating to ancient Greek or Latin literature, art, or culture
* This museum has very good examples of classical art from Bali.
to be there for (someone) – being available to listen and support another person, especially when that person has problems or needs help
* Your mother will always be there for you no matter how old you are.
to take (someone) there – to be able to bring or go with another person to a place, time, or a situation
* Jamal said he would take Linda there before going to work.
after full deliberation – following one’s long and careful consideration of an idea, issue, or problem
* The board of directors decided to fire the current president after full deliberation of his unethical actions.
What Insiders Know
The United States Minor Outlying Islands
The United States Minor Outlying Islands “consist of” (are made of; include) nine United States “island” (land surrounded on all sides by water) areas called “insular areas.” An “insular area” is a United States territory that is not part of the 50 states but are actually independent nations that have signed a Compact of Free Association with the United States.
Eight of these islands are located in the Pacific Ocean – Baker Island, Howland Island, Jarvis Island, Johnson Atoll, Kingman “Reef” (a ridge of sharp rock or sand just above or below the surface of the sea), Midway Islands, Palmyra “Atoll” (a ring-shaped island formed of “coral,” color rock formations under water), and Wake Island. The other island, Navassa Island, is located in the Caribbean Sea.
Among these territories, only Palmyra Atoll is an “incorporated territory,” which means that the U.S. Constitution – the most important legal document in the United States – is to be applied to the local government in the same way that it applies to the local governments and residents of the 50 U.S. states.
Baker Island, Howland Island, and Jarvis Island were acquired on October 28, 1856, Navassa Island on October 31, 1858, Johnson Atoll on September 6, 1859, Kingman Reef on February 8, 1860, Midway Atoll on August 28, 1867, Wake Island on January 17, 1899, and Palmyra Atoll on August 28, 1867.
None of the islands have any “permanent residents” (people who live there), and the only human population consists of temporarily “stationed” (assigned) scientific and military “personnel” (employees). A “census” (counting of people by the government) in 2000, counted 315 people on Johnson Atoll, and 1 person on Wake Island.
The islands are grouped together as for “convenience” (making things easier) only, and not because they share a single cultural or political history related to the United States.