= 0668
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 668: Having Cash Flow Problems.
This is English as a Second Language Podcast episode 668. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful – a little rainy, but otherwise beautiful Los Angeles, California.
This episode, like all of our episodes, has a Learning Guide. Go to our website at eslpod.com and download it. You’ll improve your English much faster by having a transcript, vocabulary, and additional cultural and vocabulary information included in the Guide.
This episode is about business. It’s about something called “cash flow.” Let’s get started.
[start of dialogue]
Kylie: I’ve just crunched the numbers and we’re not going to be able to meet payroll next month because of cash flow problems.
Miguel: That can’t be. The cash flow projections from last month showed that we’d be fine.
Kylie: We didn’t anticipate a shortfall in income this month and didn’t set aside enough cash to hedge against a cash flow problem.
Miguel: What can we do? We need a stopgap solution now.
Kylie: Well, we could try to extend our line of credit at the bank.
Miguel: We’re already overextended at the bank. I don’t want to push our luck.
Kylie: The other option is to hold off on paying our suppliers and hope that our income goes up next month, as predicted.
Miguel: Do you really think we can hold them off for that long?
Kylie: I’ll have a talk with our biggest suppliers and give them assurances that they’ll get paid. Let’s just hope they’re not having cash flow problems of their own!
[end of dialogue]
Kylie begins our dialogue by saying to Miguel, “I’ve just crunched the numbers and we’re not going to be able to meet payroll next month because of cash flow problems.” “To crunch (crunch) the numbers” means to make a calculation: to add, subtract, multiply, or divide to get an answer or a result. Usually we use this expression in business, when we are talking about the cost of something or how much money the company will have at the end of the year we crunch the numbers, we do the calculations to see. “Payroll” (payroll) is a general term to describe the money that is paid to the employees. “To meet payroll” means you have enough money to pay for the people who work for you. So if you’re a company and you can’t meet payroll, well then, your employees won’t get paid – and they probably will stop working as well! “Cash flow” is also called, by a more technical name, “liquidity” (liquidity). You may recognize the word “liquid,” it’s something that, like water, can move easily. “Cash flow” refers to the amount of money a company has to pay its bills and other expenses without considering how much the company has invested. So for example, if you have a company that sells…I don’t know…cats let’s say, and you have 50 cats that you are trying to sell. The cats can’t be given to your employees as payment. Well, you could give them, maybe as a punishment! But, cats are what we call an “asset” (asset). An “asset” is something that you own but that you can’t use for something else like paying bills or paying your employees. “Cash flow” refers to money in a bank or money that you have in cash or in a check, something that represents cash, that you can use to pay other people with. So, a company needs to be bringing in enough money – enough cash – so that it can pay its expenses. If you don’t to that, well then, you have a cash flow problem.
Kylie and Miguel have a cash flow problem. She’s crunched the numbers and they’re not going to be able to meet payroll next month. Miguel said, “That can’t be.” “That cannot be correct” is what he means. “The cash flow projections from last month showed that we’d be fine.” A “projection” is also called a “forecast,” it’s a guess about what is going to happen in the future. We would call it an “educated guess,” meaning you have some information, it’s not just random, you have some information on which your projection is based.
Kylie says, “We didn’t anticipate a shortfall in income this month.” “To anticipate” in this case means to believe that something will happen in the future; we might also say “to foresee.” “I anticipate that it will rain tomorrow because there are clouds in the sky.” That’s my belief, my expectation. Kylie says their company did not expect a shortfall in income. A “shortfall” (one word) it is when you don’t have enough of something that you need; we might also call it a “shortage” or a “lack” (lack). Well, this is a shortfall in income; that is, money that the company gets from selling, in this case, its cats. So Kylie says, “We didn’t anticipate a shortfall in the income this month and didn’t set aside enough cash to hedge against a cash flow problem.” Let’s start with the expression “to set aside,” which is a two-word phrasal verb meaning to decide to save part of what you have now; we might say to “reserve” it. I have 100 dollars and I don’t have any bills to pay today, but next month I’m going to have to buy my wife a present – and no, it will not be a cat! I set aside 95 dollars, because I’m a loving husband and of course I would give my wife the best possible – right honey? So I put 95 dollars aside, and that is what I will save so I can buy something next month.
Unfortunately, Miguel and Kylie are not perhaps the best businesspeople; they didn’t set aside enough cash to hedge against a cash flow problem. “To hedge” (hedge) means to protect yourself against certain risks, especially financial risks; to do something that will reduce a potential – a possible – problem in the future, especially when we’re talking about money. We have a common expression, “to hedge your bets,” that means you wouldn’t want to bet all of your money on one thing, or gamble – risk – your money on one thing. “To hedge your bets” means to set aside extra money in case things don’t go as well as you planned. That’s something Kylie and Miguel didn’t do.
Miguel says, “What can we do? We need a stopgap solution now.” “Stopgap” (stopgap – one word) is a temporary solution, a temporary fix. It won’t solve the problem permanently – forever – but it will fix it for now. You have a lot of cats and you don’t have room for them in your store, so you ask your neighbor if he can keep 10 of your cats at his house just until you get enough room to bring them back to your store. That’s a stopgap measure, a stopgap solution.
Kylie says, “Well, we could try to extend our line of credit at the bank.” A “line of credit” is another word for a “loan.” A “loan” is when someone gives you something, like money, and says you have to give it back in the future, in a year or two years, whenever. In addition, you have to pay that person some additional money for being able to use their money today. Well, a line of credit is when a bank says you can use this money whenever you want; you don’t have to take it now, when you need it you can take it.
Miguel says, “We’re already overextended at the bank.” “To overextend” means to have too many loans, too many “debts” we would say (debts), where you have to give other people money you have borrowed from them. That’s what happened to Kylie and Miguel. He says, “I don’t want to push our luck.” “To push your luck” means to try to get too much of a good thing, to try to take advantage of a situation that may put you in a worse position in the future. You may have had good luck before – good fortune – but there’s no guarantee that will continue. So, for example, if you have a gun and you put four bullets in the gun and you shoot the gun and no bullets come out, you have been very lucky. You don’t want to push your luck by continuing to try to shoot the gun because you may hurt someone or kill someone.
Kylie says, “The other option (the other possible solution) is to hold off on paying our suppliers.” “To hold off on” is sort of a three-word phrasal verb; it means to postpone or delay something, to decide not to do something now but instead do it in the future: “I’m going to hold off on buying a new car until the prices are lower.” They want to hold off on paying their suppliers. I should mention that “hold” has many different meanings in English, as does the word “hedge,” and you can find those additional meanings in our Learning Guide. A “supplier” is someone who sells your company something: a product, a good, or a service we would call it. So whoever sells Kylie and Miguel cats is a supplier. Kylie says we can “hope that our income goes up next month as predicted,” meaning as expected.
Miguel says, “Do you really think we can hold them off for that long?” Do you really think we cannot pay them for a whole month? Kylie says, “I’ll have to talk with our biggest suppliers (the company that gives them the most or sells them the most things that they use) and give them assurances that they’ll get paid.” “To give (someone) assurances” means to tell them things that will make them feel confident that something will happen, to tell them that everything is going to be okay, they don’t have to worry about it. The word “assurances” comes from the verb “to assure” (assure), which means the same thing really, to tell someone that it’s going to be okay, you’re going to have more money next month, and so forth. Kylie says, “Let’s just hope they’re not having cash flow problems of their own,” meaning maybe the suppliers, if you don’t pay them, will have their own cash flow problems.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Kylie: I’ve just crunched the numbers and we’re not going to be able to meet payroll next month because of cash flow problems.
Miguel: That can’t be. The cash flow projections from last month showed that we’d be fine.
Kylie: We didn’t anticipate a shortfall in income this month and didn’t set aside enough cash to hedge against a cash flow problem.
Miguel: What can we do? We need a stopgap solution now.
Kylie: Well, we could try to extend our line of credit at the bank.
Miguel: We’re already overextended at the bank. I don’t want to push our luck.
Kylie: The other option is to hold off on paying our suppliers and hope that our income goes up next month, as predicted.
Miguel: Do you really think we can hold them off for that long?
Kylie: I’ll have a talk with our biggest suppliers and give them assurances that they’ll get paid. Let’s just hope they’re not having cash flow problems of their own!
[end of dialogue]
We always anticipate a good script here on ESL Podcast, and we got one today, as expected, from our own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
to crunch the numbers – to make a calculation, especially in accounting or finance; to perform a mathematical operation, such as adding, subtracting, multiplying, or dividing to get an result or answer
* I wonder whether these students would be able to crunch the numbers without a calculator.
to meet payroll – to be able to pay the salaries of one’s employees; to be able to pay people the money they are owed for the work they have done
* If the company isn’t able to meet payroll, why is anyone still working there?
cash flow – liquidity; the amount of money a company has available to pay its bills and other expenses, without considering how much money a company has invested in assets
* Many companies struggle with cash flow for the first two years, because all of the money they make from sales has to be used to pay off loans and invest in growth.
projection – forecast; an educated guess about what will happen in the future based on what has happened in the past
* Our projections show that the firm will double in size by 2014.
to anticipate – to foresee; to believe that something will happen in the future and prepare for it
* I didn’t anticipate it would rain today. If I had, I would have brought an umbrella.
shortfall – a shortage; a lack; a situation in which one does not have enough of something
* When the government collects fewer taxes, schools have to find creative ways to cover their funding shortfall.
income – revenue; the amount of money that is received; the amount of money coming into an organization or business during a certain period of time
* It’s often easier to reduce expenses than to increase income.
to set aside – to reserve; to determine that one will not use part or all of something right now, instead saving it for later or for someone else
* It’s a good idea to set aside a little money each month, just in case we need it in a future emergency.
to hedge – to protect oneself against certain risks, especially financial risks; to do something that will reduce the problems created by some future event, especially related to finance
* They’re investing in gold to hedge against fluctuation in the housing market.
stopgap – a temporary fix or solution; something that will temporarily fix a problem, although it will not last forever
* They hired temporary workers as a stopgap for the heavy workload they had last month.
line of credit – a loan; an amount of money that one takes from a bank, although one must pay it back later with interest
* Which bank gave you a line of credit to make repairs on your house?
to overextend – to have too much debt or too many commitments; to not be able to keep one’s promises, especially related to one’s time or the money one owes to another person
* Annie already works two jobs and takes care of her three children, so she really overextended herself by agreeing to lead the parent-teacher association.
to push (one’s) luck – to try to get too much of a good thing, so that one fails and ends up in a worse position; to try to continue one’s history of having very good luck or having unexpected successes, even though there are no guarantees that one will continue to be that lucky
* It didn’t snow at all last week while we repaired our home, so we decided to push our luck and replace the roof, even though we know it normally snows a lot this time of year.
to hold off on – to delay or postpone something; to decide to not to do something now, instead doing it at some future time
* They’ve decided to hold off on the wedding until they’ve saved enough money for a house.
supplier – a company that sells goods or products to another company
* Trey really likes shopping at this grocery store, because most of the suppliers are local farmers.
as predicted – as expected; as one had believed would happen; a phrase used when one’s prediction comes true
* As predicted, the cost of health care increased again last year.
to give (someone) assurances – to give someone a feeling of confidence that something will happen; to tell someone that everything is okay; to help someone stop worrying about something
* If you want people to vote for you, you need to give them assurances that their lives will become easier once you are president.
Comprehension Questions
1. What did Kylie do when she crunched the numbers?
a) She made an error in her calculations.
b) She performed some calculations.
c) She copied her calculations from someone else.
2. According to Kylie, what might be the consequence of the company’s cash flow problems?
a) The company won’t be able to hire any new employees.
b) The company won’t be able to apply for a new line of credit.
c) The company won’t be able to pay employees’ salaries and wages.
Answers at bottom.
What Else Does It Mean?
to hedge
The verb “to hedge,” in this podcast, means to protect oneself against certain risks, especially financial risks, or to do something that will reduce the problems created by some future event: “How can we hedge against foreign exchange risk?” The phrase “to hedge (one’s) bets” means to reduce the likelihood that something bad will happen by doing many different things: “We know most goldfish die within a few days, so we’re hedging our bets by buying lots of them.” The phrase “to be hedged in” means to not have enough space, or to be surrounded by something: “Their backyard is hedged in by the railroad tracks.” Finally, a “hedge” is a small group of plants that are planted in a row very close to each other, usually to separate two parts of a property: “They trim the hedge along their walkway each spring.”
to hold off
In this podcast, the phrase “to hold off on (something)” means to delay or postpone something, or to decide to not to do something now, instead doing it at some future time: “Reyna is going to hold off on going to college until she can save up a little more money.” The phrase “hold on” is used to ask someone to wait a short period of time: “Hold on! I want to go with you, but I need to put on my jacket first.” The phrase “to hold onto (something)” means to keep something and not sell it or throw it away: “Why did you hold onto these comic books for so many years?” Finally, the phrase “to be held up” means to be delayed by something: “I’m sorry I came to the meeting a few minutes late, but I was held up in traffic.”
Culture Note
Many Americans “mistakenly” (incorrectly) believe that the U.S. government “awards” (gives to the winner of a competition) “grants” (money that is given to a person or organization for a particular purpose and does not need to be paid back) to open or “expand” (grow) small businesses, but this simply is not true. “Entrepreneurs” (people who start their own business) are often “sorely” (very) disappointed when they learn that “federal” (national) grants are available only to nonprofit organizations and local and state government agencies.
For example, the federal government often awards grants to nonprofit organizations involved in medical research or the development of more “efficient” (producing more with less) sources of energy. These activities benefit all members of “society” (the people living together in a particular country, region and/or culture), so it makes sense for the federal government to support those activities financially. In most cases, it does not make sense for the federal government to award grants to an entrepreneur opening a new restaurant or a retail store, because those businesses benefit only the owner and a “handful” (a small number) of employees.
Some state and local government agencies award grants to entrepreneurs, but the entrepreneurs usually have to “match” (provide an equal amount) those grants with bank loans or personal funds. These grants are usually awarded to “stimulate” (improve; make something grow) the local economy – not just to help someone start a new business. However, entrepreneurs can benefit from many programs that are designed to help them apply for low-interest loans and receive inexpensive or free business advice.
Comprehension Answers
1 - b
2 - c