= 0677
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 677: Feeding a Picky Eater.
This is English as a Second Language Podcast episode 677. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California, on a beautiful sunny day here in Los Angeles. I’m not so sunny; I have allergies, I have problems that affect my nose and throat today. So if I sound stranger than usual – I mean I always sound a little strange, right? – now you know why.
Oh, by the way, we have a Learning Guide for this episode. You do not to want to miss it; you want to get it at our website at eslpod.com.
This episode is called “Feeding a Picky Eater.” It’s a dialogue between Jeremy and Keeley. Let’s get started.
[start of dialogue]
Jeremy: It’s really nice of you to make dinner for me tonight.
Keeley: I’m glad to do it. You’re been so helpful to me, it’s only fair that I return the favor. I hope you’ve brought your appetite.
Jeremy: You bet.
Keeley: Great! Here’s the first course, a light soup. How do you like it?
Jeremy: It has an interesting flavor.
Keeley: You don’t care for it.
Jeremy: It’s just a little greasy for my taste.
Keeley: Sorry about that. Why don’t you try this dish? It’s an old family recipe. What’s wrong?
Jeremy: Oh, nothing. I just don’t think it’s agreeing with me. Maybe it’s an acquired taste.
Keeley: Okay, maybe I can whip up something else for you…
Jeremy: I don’t want to put you to all that trouble. Sorry to be so fussy.
Keeley: No, no trouble at all.
…
I like cooking, but with such a picky eater like Jeremy, I might be cooking into next Tuesday!
[end of dialogue]
Our dialogue begins with Jeremy saying to Keeley, “It’s really nice of you to make dinner for me.” Keeley says, “I’m glad to do it (I’m happy to do it). You’re been so helpful to me (you’ve helped me so much), it’s only fair that I return the favor.” The expression “it’s only fair” means that it is just, it is right. When you do something nice for someone and they say, “Oh, you should not do that,” and you are in fact doing something nice because they have already done something nice for you, you can say, “Well, it’s only fair. It’s only fair that I return the favor.” “To return the favor” means to do something nice for someone after they have done something nice for you. Keeley says, “I hope you’ve brought your appetite.” Remember, Keeley is making dinner – making some food for Jeremy – and so she says, “I hope you’ve brought your appetite.” This expression means that I hope you came here feeling hungry. Especially when you are coming to someone’s home for a meal they might say that. Your “appetite” (appetite) is the amount of hunger that you feel, how hungry you are. Jeremy says, “You bet.” “You bet” is an expression that means yes, absolutely, of course. Where I’m from, in Minnesota, we say “You betcha.” Don’t ask me why!
Keeley says, “Great! Here’s the first course, a light soup.” A “course” is a part of a meal, one of several things that you eat in a certain order. For an American meal, a soup or salad is usually part of the first course; then you have meat or fish, what we call an entrée as a second course; and then you might have something sweet for the for the third course, which is dessert. Keeley’s having Jeremy eat a light soup. “Light” here means it doesn’t have a lot of cream, butter, or oil. Keeley says, “How do you like it?” Jeremy says, “It has an interesting flavor.” Before I go on, the word “course” has some other meanings in English, and those can be found in the wonderful, fantastic Learning Guide prepared by our own Dr. Lucy Tse just for you. “Flavor” is the way something tastes. Now when someone says in English – in American English “that has an interesting flavor,” after someone has asked how they like it, they’re really saying I don’t want to be rude but it really isn’t something I like very much. Someone may say “How do you like this dress?” and you say “Well, that’s interesting.” That’s a bad thing to say. The person knows that you don’t like it, but you’re trying to be polite; you’re trying not to be insulting to the person.
Keeley says, understanding exactly what Jeremy means, “You don’t care for it.” “To not care for (something)” means not to like something, not to enjoy something, to think it is bad. I don’t care for mustard, that orange-y liquid that you put on a hamburger or a hotdog. I don’t like mustard – I don’t care for mustard. Well, Keeley says Jeremy doesn’t care for her soup. Jeremy says, “It’s just a little greasy for my taste.” Something that is “greasy” (greasy) is something that is oily, something that has a lot of fat and oil in it. The expression “for my taste” means in my opinion. It can be used for things other than food. You can say, “Well, that movie wasn’t very good, for my taste anyway.”
I had to stop and drink some tea for my voice, I apologize. Where were we? Oh yeah.
Keeley says, “Sorry about that,” Jeremy you idiot, I made you this dinner and now you tell me that you don’t like it. No, she doesn’t say that actually! She just says, “Sorry about that. Why don’t you try (why don’t you taste) this dish (this food that I’ve made)? It’s an old family recipe.” A “recipe” (recipe) are instructions for how to prepare some kind of food. Then Keeley says to Jeremy, looking at his face as he is trying this other type of food, “What’s wrong?” Jeremy says, “Oh, nothing. I just don’t think it’s agreeing with me.” When we’re talking about food, especially the phrase “to agree with” means that you like it, you find it pleasant, it doesn’t bother your stomach. Something that doesn’t agree with you is food that perhaps made you a little sick. Jeremy doesn’t think that the old family recipe, the food that was made, agrees with him. Then he says, “Maybe it’s an acquired taste.” Something that you “acquire” (acquire) is something that you get over time, not right away. Sort of something that you’ve learned; in this case that you’ve learned to like food, a kind of taste that you’ve grown to like. When I first came to Los Angeles I didn’t like eating crab because where I’m from, in Minnesota, we don’t eat a lot of crab; it’s very expensive, a kind of seafood. But, I began to like it the more I ate it, and now I enjoy eating crab – when I have the money to buy some!
In the dialogue, however, Jeremy is being a little insulting again by saying that the dish that Keeley is serving him is an “acquired taste,” meaning he hasn’t learned to like it. It doesn’t have to be an insult, but I think in this case it is in part. Keeley says, “Okay, maybe I can whip up something else for you.” “To whip (whip) up” is a two-word phrasal verb meaning to cook something quickly, when little effort is required: “I’ll whip up some scrambled eggs for you.” It’s easy to do; it won’t take a lot of time. There are other meanings of this expression; those can be found, once again, in our Learning Guide.
Jeremy says, “I don’t want to put you to all that trouble.” “To put (someone) to all that trouble,” or “all the trouble,” means to create a lot of work for another person, to do something that makes another person have to do a lot of work, especially when it’s for your benefit – when it’s for you. Jeremy says, “Sorry to be so fussy.” “Fussy” (fussy) is a word that we don’t use as much anymore, but you’ll still hear it. It’s the same as “picky” (picky). A “picky” or “fussy” person is difficult to please, someone who is hard to make happy, someone who has a lot of requirements and preferences, someone who’s very difficult to please.
Keeley says, “No, no trouble at all.” Then at the end, she gives us her real opinion. She says, “I like cooking, but with such a picky eater” – an “eater” is a person who eats, so a “picky eater” is someone who eats but is difficult to please – “with such a picky eater like Jeremy, I might be cooking into next Tuesday!” “Into” here is used in a slightly unusual way, but still something that you will definitely hear and read. In means I’m going to be doing this activity from now until some future point in time, until next month, until tomorrow. So “into” here means until and through. “I will be cooking until now until next Tuesday,” that’s how long it will take me because Jeremy is such a picky eater I have to cook many different things to find something that he likes. The other possibility, of course, is to tell Jeremy to go home or go to a restaurant get his own food!
Now let’s listen to the dialogue, this time at a native speed.
[start of dialogue]
Jeremy: It’s really nice of you to make dinner for me tonight.
Keeley: I’m glad to do it. You’re been so helpful to me, it’s only fair that I return the favor. I hope you’ve brought your appetite.
Jeremy: You bet.
Keeley: Great! Here’s the first course, a light soup. How do you like it?
Jeremy: It has an interesting flavor.
Keeley: You don’t care for it.
Jeremy: It’s just a little greasy for my taste.
Keeley: Sorry about that. Why don’t you try this dish? It’s an old family recipe. What’s wrong?
Jeremy: Oh, nothing. I just don’t think it’s agreeing with me. Maybe it’s an acquired taste.
Keeley: Okay, maybe I can whip up something else for you…
Jeremy: I don’t want to put you to all that trouble. Sorry to be so fussy.
Keeley: No, no trouble at all.
…
I like cooking, but with such a picky eater like Jeremy, I might be cooking into next Tuesday!
[end of dialogue]
I hope you do care for the scripts we have here on ESL Podcast. That’s because they’re written by the wonderful Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
it’s only fair – it is nice and just; a phrase used to present something that one should do to be nice
* Since you washed the dishes last night, it’s only fair if I wash them tonight.
to return the favor – to do something nice for someone after he or she has done something nice for oneself
* Thank you so much for lending me money when I needed it. I hope someday I can return the favor.
to bring (one’s) appetite – to come to an event feeling hungry, especially when coming to someone’s home for a meal
* I asked Heather if we should bring anything to her dinner party, but she said we should just bring our appetite.
course – one of several things eaten in order during a meal, usually soup or salad, an entrée, and dessert
* This is a five-course meal, so don’t fill up on salad and bread
flavor – the way something tastes, especially whether it is sweet, salty, sour, or bitter
* How many flavors of ice cream does this shop offer?
to not care for (something) – to not like something; to not enjoy something and think it is bad
* Generally, I don’t care for horror movies. They leave me scared for days.
greasy – oily; with a lot of fat and oil
* These French fries are so greasy that my fingers are covered in oil.
for (one’s) taste – in one’s opinion; according to one’s likes and preferences
* The climate in Alaska is too cold for my taste. I prefer warmer parts of the country.
recipe – instructions for cooking or baking something
* This recipe calls for one cup of flour and half a cup of sugar.
to agree with (someone) – to be pleasant for someone; for someone to like something and not be bothered by it, especially when talking about food
* Something I ate last night didn’t agree with me, and my stomach has hurt all day.
acquired taste – something that one learns to enjoy eating over time; something that one does not enjoy the first time one eats or drinks it, but later learns to appreciate it
* For many people, wine is an acquired taste.
to whip up – to cook something quickly, especially when little effort is required
* Grandma Mable is amazing. She can whip up a batch of chocolate cookies in just a few minutes.
to put (someone) to all the/that trouble – to create a lot of work for another person; to do something that makes another person need to do a lot of work, especially for one’s benefit
* When I accepted your invitation to stay at your house, I didn’t know I’d be putting you to all the trouble of borrowing a bed and moving it here.
fussy – picky; difficult to please; with many requirements and preferences that are difficult to meet.
* Karina is a fussy housekeeper, who wants everything to be exactly in its place.
picky eater – a person who eats few things and has many requirements for the food that he or she will eat; a person who dislikes many types of food and drink
* As a child, Earle was a picky eater who wouldn’t eat anything that was green.
into – until and through; to be doing an activity from now until a future point in time
* That garage is such a mess that we’ll be cleaning it into next month.
Comprehension Questions
1. What does Keeley mean when she says she wants to “return the favor”?
a) She wants to pay him money for helping her.
b) She wants to give back the gift he gave her.
c) She wants to do something nice in exchange for what Jeremy did for her.
2. Why doesn’t Jeremy like the first course?
a) It is too oily.
b) It is too salty.
c) It is too spicy.
Answers at bottom.
What Else Does It Mean?
course
The word “course,” in this podcast, means one of several things eaten in order during a meal, usually soup or salad, an entrée, and dessert: “For the first course, we could choose between chicken-noodle soup and tomato soup.” The phrase “of course” is used when one is sharing information that is understood and will not be surprising: “Of course, we should buy tickets early just in case they sell out.” The phrase “par for the course” refers to something one would expect to happen, especially when it is a bad or unpleasant thing: “Melissa behaved terribly at the family reunion, which was par for the course, considering her bad feelings about most family members.” The phrase “in due course” means in the future at an appropriate time: “We’ll talk about the possibility of a raise in due course.”
to whip up
In this podcast, the phrase “to whip up” means to cook something quickly, especially when little effort is required: “We’re going to whip up a quick breakfast and then drive to the coast for the day.” The phrase “to whip” means to hit a person or animal’s back with a long piece of rope or leather, usually as a punishment: “Sherman thinks it’s wrong to make horses run faster by whipping them.” The phrase “to whip through (something)” means to do something very quickly: “How did you whip through the math problems so quickly?” Finally, the phrase “to whip around” means to turn very quickly: “We didn’t realize Jake was listening to our conversation until, all of a sudden, he whipped around and starting telling us his opinion.”
Culture Note
Many “toddlers” (children ages 1-2) and “preschoolers” (children ages 3-4) are picky eaters. Some eat food only of a certain color, while others “refuse” (won’t do) to eat food that touches other types of food. Parents who are worried about whether their children are getting the “nutrition” (combination of calories, fat, proteins, vitamins, minerals, etc.) they need have found many ways to “cope with” (work around a problem) picky eaters.
Most young children like “dips” (thick sauces that the tips of food can be placed in before eaten), so parents can “encourage” (help something to happen) them to eat more fruits and vegetables by giving them dips. Many picky eaters are more likely to eat carrots, celery, and broccoli if they can dip “bite-sized” (cut into a size that can be placed in one’s mouth) pieces into “Ranch dressing” (a creamy white salad dressing) or “hummus” (a spread made from garbanzo beans, olive oil, and sesame seeds). Apple slices and other pieces of fruit can be dipped into yogurt or honey. And small pieces of meat and potatoes can be dipped into sour cream, mustard, or ketchup.
Other parents try to “trick” (make someone believe something that isn’t true) their children by “disguising” food, making it appear to be something else. For example, some books teach parents how to “hide” (not let something be seen) spinach “purees” (food that has been put in a blender so it appears to be a thick liquid) in “brownies” (a chocolate dessert). Parents can also put green or red peppers, broccoli, and other vegetables in a blender with tomato sauce and then use the “vitamin-packed” (with a lot of vitamins) tomato sauce to serve “kid-friendly” (liked by children) foods like pizza and spaghetti.
Comprehension Answers
1 - c
2 - a