= 0678
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 678: Reporting Damaged Luggage.
This is English as a Second Language Podcast episode 678. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there today to download a Learning Guide for this episode to help you improve your English – and live longer. It’s true!
This episode is called “Reporting Damaged Luggage.” “Luggage” is what you use to carry your clothing and other things when you go on a trip. Let’s get started.
[start of dialogue]
I picked up my luggage off of the baggage carousel and noticed that the handle was broken and some of my clothes were falling out of the open zipper. The bag looked like it had been mishandled, but could someone have tampered with it, too? I went to the baggage claim office to report what I found.
Clerk: Next. How can I help you?
Jordan: I retrieved my bag and found that it’s been damaged.
Clerk: What’s the problem?
Jordan: The handle is broken and I think someone has gone through my bag.
Clerk: That was probably security. They may have searched your luggage.
Jordan: Yes, but my camera is missing and everything is in disarray. I’m not sure if other things are missing.
Clerk: Why don’t you make a more thorough inspection over there and then you can file a claim for anything that’s missing or broken.
Jordan: Will I be compensated for the damage to my luggage and for my missing camera?
Clerk: I really can’t say.
Jordan: How long will it take for someone to contact me?
Clerk: I really can’t say. Next!
…
I knew a blow off when I heard it, but I looked through my bag anyway and filled out the forms. Who knows? Miracles do happen, don’t they?
[end of dialogue]
Our story begins with Jordan telling us about the unfortunate problems she had on her trip. She says, “I picked up my luggage (I removed my luggage) off of the baggage carousel and noticed that the handle was broken.” “Luggage” is the same as suitcases; we might call them “baggage.” They are the things that you put your clothing and other objects into when you travel. Especially if you are traveling on a train or a plane, you will typically bring some luggage with you. “Baggage” is another word for “luggage.” “Carousel” (carousel) is actually, in its original meaning, something that you would find at a fair or an amusement park. It’s a round ride – a round game that moves in circles, and there are typically horses that go up and down. It’s a thing that you would bring a four or five-year-old to. That’s a carousel; it’s also called a “merry-go-round.” But here, the “baggage carousel” is a round – typically round thing that has your luggage. What they do is they have what’s called a “conveyor belt,” which is a long piece of plastic or rubber that moves around and around. They put the luggage on top of that; it moves it – it conveys it to the carousel, and the carousel spins around and when you see your luggage – your baggage – you pick it up, you take it off of the baggage carousel. The “handle” of a piece of luggage is the part that fits into your hand and is used to lift up the suitcase – the piece of luggage – the baggage. A “handle” can be anything that you grab onto with your hand in order to move it or open it. Most bags or suitcases have handles.
So Jordan notices that her handle is broken – it’s not working correctly – and that some of her clothes were falling out of the open zipper. A “zipper” is something you use with a piece of clothing or a bag to close it, to bring two parts of the object together. A zipper is made with two long pieces of metal or plastic that have many small what we call “teeth,” and the teeth, which are little parts that stick out, sort of like what you will see on a comb for your hair – anyway, these teeth come together and they stay together, and they keep the two parts of the bag or the parts of your clothing where there is a zipper together. Men often have zippers on the top of their pants in the front for reasons you probably can guess.
So Jordan has a problem with her luggage. She says, “The bag looked like it had been mishandled.” “To mishandle” means to use something in a way that will damage it, to treat it poorly. She says, “how could someone have tampered with it, too?” “To tamper (tamper) with (something)” is more than just mishandling it; it’s really different from mishandling. “To tamper with” is to purposely – on purpose, intentionally – try to damage or do something with an object that you do not have permission to do, usually with something that belongs to someone else. She said, “I went to the baggage claim office to report what I found. The “baggage claim office” would be the place in the airport or train or bus station that takes care of problems people have with their luggage.
The clerk says, “Next. How can I help you?” You have to think that there’s a line of people – several people waiting, so when the clerk says “next” he means the next person should come forward, should come and talk to him. Jordan says, “I retrieved my bag and found that it’s been damaged.” “To retrieve” means to get back, to get something that you didn’t have and now you have it again. In this case, you give the airline or the bus company or train company your luggage; you put it in a separate area, and then when you arrive at the place you are going – your destination – you then retrieve it, you get it back.
The clerk says, “What’s the problem?” Jordan says, “The handle is broken and I think someone has gone through my bag.” To “go through” is a two-word phrasal verb meaning to open something and look through it very quickly. It’s what you would do if you were looking for something, trying to find something. Jordan says that someone went through her luggage. The clerk says, “That was probably security. They may have searched your luggage.” “To search” is to look for something. In the United States, for example, when you give the airline your piece of luggage – your suitcase – sometimes they will look through it. They will look at it even after it has been given to them and you are already on the plane. Before the bags go on the plane, underneath in the bottom part of the plane, there may be security officers who are inspecting it for any possible dangerous object.
Jordan says, “Yes, but my camera is missing and everything is in disarray.” Something that is “missing” is something that cannot be found, something that is lost, something that is no longer there. “Disarray” (disarray) means messy, things are not in their proper place. Another word we might use for “disarray” is “disorder.” The prefix (dis) is similar to the prefix “un” (un); when put before a word it often gives it the opposite meaning or something that is not that thing. So, “disorganization” is the opposite of “organization.”
Anyway, Jordan is complaining that her camera is missing; she says, “I’m not sure if other things are missing.” The clerk says, “Why don’t you make a more thorough (a more complete) inspection over there and then you can file a claim for anything that’s missing or broken.” “To inspect” means to look at very carefully. So, an “inspection” is the noun, which is the act of looking or searching for something. The clerk is telling her to go to another place to look through her luggage carefully, write down all of the things that she thinks are missing or damaged, and then come back to him to file a claim. A “claim” (claim) here means an official report describing something, usually something that you would give to an insurance agency or a company asking for money, money for something that has been stolen or lost. In this case, it’s the airline that would be responsible. But if you have accident with your car, you would file a claim with the insurance agency so they can pay you money to fix your car.
Jordan says, “Will I be compensated for the damage to my luggage and for my missing camera?” “To compensate” means to pay someone for a specific purpose. It may be because they made a mistake and they have to give you money in order to basically apologize, say that they’re sorry. You can also use “compensate” to mean simply pay: “I compensate my employees,” I pay them a salary. “To be compensated” means that someone will give you some money for the damage to your luggage and for anything that’s missing. Jordan asks if she will be compensated for these things; the clerk says, “I really can’t say.” When someone says they “can’t say,” they mean they don’t know the answer; it’s another way of saying “I don’t know.” It’s a little more formal perhaps, a little more polite. Jordan says, “How long will it take for someone to contact me?” The clerk says, again, “I really can’t say. Next!” When he says “next,” he’s saying to Jordan “I’m not going to talk to you anymore,” and he’s asking the next person waiting in line to come forward.
Jordan says, “I knew a blow off when I heard it.” “To blow off” is a two-word phrasal verb, an informal way of saying an excuse, usually when someone says something to avoid answering your question or to avoid dealing with a certain problem, perhaps because they don’t think it’s very important. “I talked to the manager but she blew me off.” She stopped talking to me or she made some excuse; she didn’t want to have to deal with me, to talk to me. Jordan says, “I looked through my bag anyway and filled out (or completed) the forms,” the pieces of paper to file the claim. “Who knows?” she says, “Miracles do happen, don’t they?” A “miracle” is something that happens that cannot be explained by the normal laws of science or laws of nature. The idea is that it is something supernatural, something that perhaps God has done, or some higher power; that’s a miracle. “To blow off” has some additional meanings; you can find those in our Learning Guide.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
I picked up my luggage off of the baggage carousel and noticed that the handle was broken and some of my clothes were falling out of the open zipper. The bag looked like it had been mishandled, but could someone have tampered with it, too? I went to the baggage claim office to report what I found.
Clerk: Next. How can I help you?
Jordan: I retrieved my bag and found that it’s been damaged.
Clerk: What’s the problem?
Jordan: The handle is broken and I think someone has gone through my bag.
Clerk: That was probably security. They may have searched your luggage.
Jordan: Yes, but my camera is missing and everything is in disarray. I’m not sure if other things are missing.
Clerk: Why don’t you make a more thorough inspection over there and then you can file a claim for anything that’s missing or broken.
Jordan: Will I be compensated for the damage to my luggage and for my missing camera?
Clerk: I really can’t say.
Jordan: How long will it take for someone to contact me?
Clerk: I really can’t say. Next!
…
I knew a blow off when I heard it, but I looked through my bag anyway and filled out the forms. Who knows? Miracles do happen, don’t they?
[end of dialogue]
Our scripts are not in disarray thanks to our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
luggage – suitcases; baggage; the cloth, leather, or plastic containers that one fills with objects one wants to have while traveling
* This airline allows each passenger to check two pieces of luggage.
baggage carousel – the large conveyor belt in an airport that moves passengers’ luggage slowly in a circle so that passengers can find their bag and take it off the device when they arrive at their final destination
* Most suitcases are placed on the baggage carousel, but very large items like large musical instruments and skis are placed over here.
handle – the part of something that fits in one’s hand and is used to lift up and carry objects
* When she dropped the tea kettle, the handle broke.
zipper – two long pieces of metal or plastic with many small teeth that are attached together with a small piece of metal or plastic that is moved up and down to separate or connect two pieces of fabric, often used on clothing
* Do you prefer jackets with zippers or buttons?
to mishandle – to treat something poorly; to use something in an inappropriate way, often damaging it
* Our application was mishandled, and that’s why we had not received a response.
to tamper with – to do something that damages an object, especially when one does not have permission to touch or look at it
* It looks like someone tampered with the lock on our car.
to retrieve – to get back; to obtain again; to find and recover something that one has not had for a period of time
* Do you know how I can retrieve my sent messages in this email program?
to go through – to open something and quickly look at all the different pieces inside it, often when searching for something
* Harriet went through everything in her purse three times, but she still hasn’t been able to find her keys.
to search – to look for something; to seek
* The security guards searched everyone’s backpacks and bags before they let them into the football stadium.
missing – something that cannot be found; something that has been misplaced and whose current location is unknown
* How long have your sunglasses been missing?
disarray – disorder; messy; without things being put in their proper place
* After the robbery, the entire house was in disarray.
inspection – investigation; the act of reviewing something, often when searching for a particular piece of information
* The health department conducts inspections of all the restaurants in the city at least once each year.
claim – an official report describing a problem and requesting payment or compensation as a solution
* Somebody hit our car while it was parked on the street last night, so now we need to file a claim with the insurance company.
to compensate – to pay someone for a specific purpose, often for a service that has been provided or to apologize for one’s mistake
* In my opinion, getting more vacation time doesn’t compensate for reducing my salary.
to not be able to say – to not know the answer to something and not know how to respond to another person’s question
* A: Do you think it will rain tomorrow?
* B: I really can’t say.
blow off – an excuse; something one says to avoid answering another person’s question, or to avoid dealing with a certain problem, especially because one thinks it is unimportant
* If this company really cared about customer service, it wouldn’t send these standard letters as a blow off every time a customer complained about something.
miracle – something that happens and cannot be explained by nature or science; something that has been performed by a supernatural force or God
* Jean thought it was a miracle that her husband was able to walk again after the bad car accident.
Comprehension Questions
1. What does she mean when he says it looks like her bag had been mishandled?
a) The handle was broken.
b) The handle was missing.
c) The bag was treated poorly.
2. What does she mean when she says that everything is in disarray?
a) Everything is very messy.
b) Everything is broken.
c) Everything is expensive.
Answers at bottom.
What Else Does It Mean?
handle
The word “handle,” in this podcast, means the part of something that fits in one’s hand and is used to lift up and carry objects: “The handle on my briefcase broke while I was walking down the street, but my laptop wasn’t damaged when it fell to the ground.” As a verb, “to handle” means to deal with or cope with a situation: “Do you think you can handle taking care of five kids all day by yourself?” The phrase “to handle” can also mean to be responsible for completing some work: “I’ll handle the billing while you’re on vacation next month.” Finally, the phrase “to handle” can mean to control an animal or drive a vehicle: “How old were you when you learned to handle wild horses?” Or, “Was it difficult to learn how to handle a motorcycle?”
to blow off
In this podcast, the phrase “to blow off” means to make an excuse or to say something to avoid answering another person’s question or avoid dealing with a certain problem, especially because one thinks it is unimportant: “Reporters are starting to ask questions about our company’s scandal and we can’t just blow it off. We need to give them real answers.” The phrase “to blow off steam” means to engage in some activity to become calmer and less angry or stressed: “Exercising can be a great way to blow off steam when work gets too stressful.” Finally, the phrase “to blow over” means for something unpleasant to be forgotten: “I know she’s angry at you right now, but this will all blow over in a few weeks.”
Culture Note
If your luggage or the “contents” (the things that were kept inside) are damaged by an airline, it is important to “notify” (officially let someone know) the airline right away. In general, you need to file a complaint within 24 hours for a “domestic” (within the country) flight, and within seven days for an international flight.
When you file a complaint, you’ll need to “present” (show) your “boarding pass” (the document one shows when stepping onto an airplane), “baggage claim ticket” (a small piece of paper with the same number shown on the piece of paper attached to your bag), and identification. The airline may give you a form to fill out.
You’ll also need to describe the damage. If you notice the damage at the airport, you can show your suitcase to the airline employee. If you don’t notice the damage until you have already left, take a picture of the damage, preferably with a “date stamp” (text placed on a photograph by a digital camera showing the date).
If you had “travel insurance” (a policy that gives you money if something bad happens while you are traveling), don’t forget to report the damage to the insurance company, too. They might file the claim “on your behalf” (for you) and they might pay you even if the airline doesn’t.
Finally, if the airline doesn’t reply quickly, “follow up” (continue to contact someone until you receive an answer). “Otherwise” (if you don’t), the airline might lose your complaint and never “get back to you” (contact you with an answer).
Comprehension Answers
1 - c
2 - a