= 0697
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 697: Eating a School Lunch.
This is English as a Second Language Podcast episode 697. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Support this podcast by becoming a member of ESL Podcast and getting the Learning Guides for each episode.
This episode is called “Eating a School Lunch.” It’s a dialogue between Chris and Sybil related to kids – high school students; elementary school students – eating lunch at their school. Let’s get started.
[start of dialogue]
Chris: What are you doing? Let’s get into the hot lunch line.
Sybil: See this lunchbox? My mom made me brown-bag it today. She says that the lunches served at school aren’t nutritious enough.
Chris: That sucks. What did she make you?
Sybil: A salad.
Chris: Oh, gross. I really feel sorry for you. What else?
Sybil: Let me see. There are some carrot sticks, too.
Chris: Sucker! You should have thrown a fit. I wouldn’t have taken it lying down. Listen to me. You should ditch that lunch and buy lunch instead, like me.
Sybil: I can’t. I don’t have any lunch money. Do you want to trade some of yours for mine?
Chris: You’re dreaming. There’s no way I’m trading my pizza for your salad and carrot sticks.
Sybil: Not even if I do your math homework?
Chris: Math homework? Now you’ve got my attention.
Sybil: Only if you give me the entire slice of pizza.
Chris: You drive a hard bargain. How about this? I’ll split the pizza with you, if you’ll do my homework.
Sybil: You must really think I’m a sucker if you think I’d agree to that!
[end of dialogue]
Chris begins by saying to Sybil, “What are you doing? Let’s get into the hot lunch line.” At most schools in the United States, the school gives students the opportunity – the option of buying their lunch, a hot lunch cooked at the school. The school has a kitchen and a place where the students can eat called a “cafeteria.” My school, when I was growing up, did not have a hot lunch program. But this school, and most schools, do have them.
Chris says to Sybil, “Let’s get into the hot lunch line,” the line where people are waiting to get their food. Sybil says, “See this lunchbox? My mom made me brown-bag it today.” A “lunchbox” is a small, usually metal or plastic box or container that put your food into. When I was growing up, as I said, there was no hot lunch program so many kids, especially the smaller children, had lunchboxes. These were metal; they often had pictures of cartoons or sports figures on them. I had one; I don’t remember what was on it. But, lunchboxes were the way that you took your lunch to school. The other way you could take your lunch is put it in a paper bag, a brown bag – I’m not sure why, but the bags were always brown – and that is what Sybil is referring to. In fact, she’s using this as a verb; “to brown-bag it” means to bring your lunch – cold lunch in a bag, not to buy lunch at school.
Sybil says her mother says that the lunches served at school aren’t nutritious enough. “Nutritious” (nutritious) is another word for healthy, food that has vitamins, minerals, other good things, and not too much sugar, fat, or salt – all the things that taste good! That’s a nutritious lunch or a nutritious meal, and Sybil’s mother says that the lunches at school are not nutritious. This has actually been a common complaint or problem in the United States, especially in the last few years. People have been saying that we need to change the lunch programs in our schools so that they serve more nutritious food, because all the American kids are getting fat. Well, maybe because they are sitting at home playing video games. Maybe it’s because their parents don’t let them go out anymore on a bicycle unless they have the latest safety equipment on their head. I don’t know, but they are getting fatter.
Chris says, “That sucks.” The expression “that sucks” means that’s very bad or that’s very disappointing. It’s a very informal term used by a lot of young people, not something you want to say to your boss, and it means that it’s very unfortunate or very sad. Chris says, “What did she (your mother) make you?” Sybil says, “A salad.” Chris says, “Oh, gross.” “Gross” means disgusting, something that is very unpleasant, usually related to food but not always. Another informal term we might use is “yuck” or “yucky.” That’s the general idea. Chris says, “I really feel sorry for you. What else?” meaning what else did she make. Sybil says, “Let me see. There are some carrot sticks, too,” little carrots that are cut up.
Chris says, “Sucker!” “Sucker” is a rude word used to describe someone who has been tricked or manipulated or used by another person. It’s definitely a negative description of someone; it’s saying that person is stupid, in a way, for being deceived, for being used or tricked. Chris says, “You should have thrown a fit.” “To throw a fit” means to get very angry, to start yelling and screaming; it’s something you expect a little child to do. In fact, when a child does it it’s sometimes called also a “temper tantrum.” Chris says, “I wouldn’t have taken it lying down.” “To take (something) lying down” means to accept something without opposing or protesting it even though you’re not very happy. You don’t say anything, you just accept it. That’s to take something lying down. Chris says, “Listen to me. You should ditch that lunch and buy lunch instead, like me,” like I am going to do. “To ditch” (ditch) here means to get rid of something, to throw something away. “I’m going to ditch my old boxes in the garage,” I’m going to throw them away. We also use this verb in schools, especially, to mean not to go to class when you are supposed to. “I’m going to ditch my chemistry class today,” I’m not going to go. That’s what we used to say, and that’s probably something I did when I was in school – ditch chemistry class, that is. Not my favorite subject, if I’m being completely honest.
Chris says that Sybil should ditch her lunch, should throw it away and buy lunch instead. Sybil says, “I can’t. I don’t have any lunch money,” any money you can use to buy lunch, of course. She says, “Do you want to trade some of yours for mine?” “To trade” means I give you something and you give me something else; we exchange it. Chris responds by saying, “You’re dreaming.” The expression “you’re dreaming” is an informal way of saying that what the person just said or just suggested is completely unacceptable or silly. It’s another way of saying “no way, absolutely not.” “You’re dreaming. There’s no way I’m trading my pizza for your salad and carrot sticks.” So, Chris isn’t going to give Sybil some pizza in order to get some salad and carrot sticks.
Then, Sybil tries to convince Chris to trade with her. She says, “Not even if I do your math homework?” Sybil is offering to do Chris’s math “homework,” what the teacher gave them as work to do at home, in exchange for some of his pizza. Chris says, “Math homework? Now you’ve got my attention,” meaning okay, maybe this is something I will do; I’m now paying attention. Sybil says, “Only if you give me the entire slice of pizza.” A “slice” is a piece of something, a piece of food typically, cut from a larger portion or piece of food. We use “slice” when we’re talking about bread; we use it when we’re talking about cakes; we use it when we’re talking about pies, cheese, and sometimes meat. “I want a slice of turkey on my sandwich, with a slice of cheese, on two slices of white bread. For dessert, I’m going to have a slice of pie and two slices of cake.” Of course, here we’re talking about pizza, which is also a type of food we use this word “slice” (slice) with.
Chris says, “You drive a hard bargain.” “To drive a hard bargain” means that you are good at negotiating something; you get a lot of things when you negotiate, when you are trading with someone, when you are trying to get someone to agree with you. He says, “How about this? I’ll split the pizza with you, if you’ll do my homework.” Chris is saying, “Well, I don’t want to give you the entire slice of pizza; I’ll give you half of that.” That’s what he means by saying, “I’ll split the pizza with you.” “To split” means to share it, each person gets half of it or some part of it. “Split” has a couple of other meanings in English; take a look at the wonderful Learning Guide for some more information.
Sybil then says, “You must really think I’m a sucker if you think I’d agree to that!” She’s saying here that Chris must think she is stupid, that she’s a sucker, if he thinks that she will do his homework for only half a slice of pizza.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Chris: What are you doing? Let’s get into the hot lunch line.
Sybil: See this lunchbox? My mom made me brown-bag it today. She says that the lunches served at school aren’t nutritious enough.
Chris: That sucks. What did she make you?
Sybil: A salad.
Chris: Oh, gross. I really feel sorry for you. What else?
Sybil: Let me see. There are some carrot sticks, too.
Chris: Sucker! You should have thrown a fit. I wouldn’t have taken it lying down. Listen to me. You should ditch that lunch and buy lunch instead, like me.
Sybil: I can’t. I don’t have any lunch money. Do you want to trade some of yours for mine?
Chris: You’re dreaming. There’s no way I’m trading my pizza for your salad and carrot sticks.
Sybil: Not even if I do your math homework?
Chris: Math homework? Now you’ve got my attention.
Sybil: Only if you give me the entire slice of pizza.
Chris: You drive a hard bargain. How about this? I’ll split the pizza with you, if you’ll do my homework.
Sybil: You must really think I’m a sucker if you think I’d agree to that!
[end of dialogue]
Our scripts never suck; that’s because they’re written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
lunch line – the line of people waiting to receive food and pay for it in a cafeteria, especially in a school or hospital
* If you like the food and want more of something, you’ll need to stand in the lunch line again.
lunchbox – a container used to bring food for lunch from home to one’s school or workplace
* Sofia’s daughter wanted a lunchbox with a picture of Mickey Mouse.
to brown-bag it – to bring food for lunch from home to one’s school or workplace instead of paying for a lunch in a restaurant or cafeteria
* They realized they could save hundreds of dollars each year by brown-bagging it instead of going to restaurants
nutritious – healthy; referring to food that has many vitamins, minerals, and fiber, without too much sugar, fat, or salt
* Most people prefer cookies and candy over more nutritious sweet foods, like apples and bananas.
to suck – to be bad, unpleasant, disappointing, or unwanted
* This sucks! I waited in line for almost two hours, and now when I finally reach the ticket counter they’re telling me the show is sold out!
gross – yucky; icky; disgusting; very unpleasant or unattractive
* That bathroom is so gross! The shower is covered with mildew and it doesn’t look like the toilet has ever been cleaned in months.
sucker – a rude word used to describe a person who has been tricked, used, or manipulated by another person
* Did you really buy that old car for $7,500? Sucker! I bet it breaks down the first time you take it on the highway.
to throw a fit – to have a temper tantrum; to express one’s anger or disappointment loudly by screaming or yelling and generally behaving badly
* The little boy threw a fit in the toy store when his mother said he couldn’t buy a toy gun.
to take (something) lying down – to accept something without protesting or opposing it even though one is unhappy about it or disappointed by it
* Did you hear the company plans to cut everyone’s salary by 10%? We won’t take it lying down!
to ditch – to get rid of something; to throw away something; to not use or have something
* Sheila finally ditched her old computer and bought a newer, faster one.
lunch money – money used to buy lunch in a cafeteria or restaurant, especially when referring to money given to a young child by his or her parents
* Becca accidentally left her lunch at home this morning, but her teacher lent her some lunch money.
to trade – to exchange; to give someone something so that he or she will give one something else
* Blue is my favorite color, but I was given a red balloon. Would you trade with me?
you’re dreaming – an informal phrase used to show that whatever another person has just proposed or suggested is completely unacceptable and silly or naive; no way
* If you think I’m going to clean your room for you, you’re dreaming!
slice – a piece of food that is cut from a larger piece of food, especially when talking about bread, pies, cakes, cheese or meat
* How many slices of turkey would you like on your sandwich?
to drive a hard bargain – to be a good negotiator; to be good at getting other people to agree to what one wants
* The sellers drove a hard bargain and we ended up paying the full asking price for the house.
to split – to share something, with each person getting one part of something
* When you go out on a date, do you always let the man pay, or do you split the bill?
Comprehension Questions
1. What does Chris mean when he says, “I wouldn’t have taken it lying down”?
a) He would have refused to bring a lunch from home.
b) He would have stayed in bed if his mother made his lunch.
c) He would have eaten the food while lying down.
2. What will Chris do if Sybil does his homework?
a) He will buy a piece of pizza for Sybil.
b) He will give Sybil his pizza.
c) He will share his pizza with Sybil.
Answers at bottom.
What Else Does It Mean?
gross
The word “gross,” in this podcast, is an informal word meaning yucky, icky, disgusting, and very unpleasant or unattractive: “Don’t pick your nose! That’s gross!” The phrase “to gross (someone) out” means to do something that makes another person feel disgusted: “It really grosses me out when I see you chew with your mouth open.” When talking about money, “gross” is the amount of money earned or received before subtracting any expenses or taxes: “His gross income was over $150,000, but after paying rent, wages, and insurance, his actual income was just around $43,000.” The verb “to gross” means to make a certain amount of money: “Our business should be grossing a million dollars per year within three years.” Finally, the word “gross” can also mean very wrong, unethical, or immoral: “Those shootings were a gross violation of the law.”
to split
In this podcast, the verb “to split” means to share something, with each person getting one part of something: “I don’t think I can eat an entire order of French fries. Do you want to split them with me?” The phrase “to split hairs” means to argue over a very small, unimportant difference: “Is there really an important difference in beliefs between the two churches, or are they just splitting hairs?” The phrase “to split the difference” means to divide an amount of money into two equal parts: “He wanted to sell it for $50 and she didn’t want to pay more than $30, but in the end they decided to split the difference at $40.” Finally, the phrase “to split up” means to break up or to end a romantic relationship: “They’ve decided to split up and start dating other people.”
Culture Note
The Head Start Program
The U.S. Department of Health and Human Services manages the “Head Start Program” to help low-income children and their families become ready for school. It focuses on education, health, nutrition, and “parent involvement” (encouraging people to spend more time interacting with their children). The program was created in 1965 as a “summer school program” (a program that runs in June, July and August to supplement what is taught during the school year) to prepare low-income children for “kindergarten” (the first year of school, when most students are five or six years old). The program has grown significantly since then.
More than 22 million “preschool-age” (ages 3 to 4) children have participated in Head Start. Most of them attend a Head Start preschool, which is less expensive than “comparable” (similar) preschools and offers programs to prepare children for school.
Head Start also includes many health “screenings” (physical examinations to determine whether one has a medical problem) for general medical, “vision” (eyesight), hearing, and “dental” (related to teeth) problems.
Head Start’s social services include programs to help low-income families understand and receive “assistance” (help) from local community programs, such as health insurance, “food distribution” (programs that give food to poor people), and “abuse” (hurting other people) “prevention” (efforts to not let something happen).
Head Start programs mainly help children from families that are “slightly” (a little bit) above, at, or below the “poverty level” (the amount of income officially defined as poor). However, some families with higher incomes can be “eligible for” (meeting the requirements to participate in) the program if they are in an emergency situation or if the children have “disabilities” (physical or mental problems that affect their performance).
Comprehension Answers
1 - a
2 - c