= 0954
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 954 – Participating in Winter Sports.
This is English as a Second Language Podcast episode 954. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is still ESLPod.com. That's right – it hasn't changed this week. It's still ESLPod.com. Go there, become a member, and download a Learning Guide for this episode.
This episode is a dialogue between Hanna and Ahmed about playing sports in the wintertime. Let’s get started.
[start of dialogue]
Hanna: It’s finally snowing outside! Soon we’ll be able to get out the sled.
Ahmed: Sledding is for kids. I’m going downhill skiing as soon as there’s enough powder. I can’t wait to feel the wind in my hair as I careen down the side of a mountain.
Hanna: You’re more likely to be on the bunny slopes! You’ve only been on a snowmobile once and gone cross-country skiing a few times. What makes you think you’ll be able to ski the slopes like an expert?
Ahmed: I can ice skate better than you can, so no matter what, I know I’ll be better at it than you’ll be. When I get the hang of skiing, I’ll probably try snowboarding.
Hanna: Now I know you’re blowing smoke. You don’t have the nerve.
Ahmed: Oh, yeah? I challenge you a game of one-on-one ice hockey.
Hanna: You’re twice my size! Make it a snowball fight.
Ahmed: You’re on!
[end of dialogue]
Hannah begins by saying, “It's finally snowing outside!” “To snow” means for small, soft ice crystals to fall from the sky. I think most of you have probably seen snow. It snows in cold places like Minnesota during the wintertime, which in the northern hemisphere is anywhere between November and, say, March.
Hanna says, “Soon we’ll be able to get out the sled.” “To get out” here means to remove from where it is stored – to take something out of a place where you have been keeping it until you are ready to use it again. “To get out” can also mean to leave. It's often used as a command, as an order. If you say to someone, “Get out,” you’re telling them to leave. It's not a very nice way to tell someone to leave, but here we're not talking about leaving, we’re talking about sledding.
A “sled” (sled) is something you use to go down a hill, usually one that has snow or ice on it. You usually have one, perhaps two people in a sled. The sled is usually flat and allows you to either lie down on the sled or sit on the sled and then slide down, or move down, a hill that has snow or ice on it. The word “sled” can also be a verb, “to sled,” which means the action of going down a hill with snow or ice on it in something called a “sled.”
Ahmed says, “Sledding is for kids.” He says it's not something adults do. It’s something children do. He says, “I’m going downhill skiing as soon as there’s enough powder.” “To ski” (ski) is also related to going down a hill with snow and/or ice on it. However, skis are long flat pieces of wood or other material that you put your feet into. You don't lie down or sit down. You stand when you ski – or at least, you're supposed to stand when you ski. I know the one time I tried skiing, I didn't stand very much. I spent most of the afternoon on the ground because I wasn't very good at skiing.
“Downhill skiing” is skiing down a hill or a mountain. There's another kind of skiing called “cross-country skiing,” which Hanna will mention in a second. “Cross- (cross) country (country) skiing (skiing)” is skiing, but not going down a hill – rather, going across flat land, going across the ground but moving your legs so that you are able to move forward. When you ski downhill, you more or less naturally go forward because it is a hill or a mountain. In cross-country skiing, you have to really use your legs and arms in order to move yourself forward across the flat ground.
Ahmed is going downhill skiing as soon as there is enough powder. “Powder” (powder) usually refers to snow that has recently fallen on the ground and is still somewhat loose. Apparently, this is better for skiing. Since I don't downhill ski, I don't know if that's true. But that's what I'm told. Ahmed says, “I can't wait to feel the wind in my hair as I careen down the side of a mountain.” Ahmed is speaking very eloquently here, almost like he's writing a novel. “I can't wait to feel the wind in my hair.” That means he can't wait to feel the wind rushing and blowing through his hair. I guess he's not going to wear a hat.
“To careen” (careen) means to move at a very high speed toward a specific place, usually going from side to side and slightly out of control. We often talk about careening in a car or some other vehicle. Ahmed is talking about careening down the side of a mountain. You have to have some experience in skiing in order to ski down the side of a mountain, because you will be going very fast and it would be easy to hurt yourself, or at least easy to fall down every 10 feet. However, Ahmed says he can do that. He could ski down the side of a mountain.
Hanna doesn't believe him. She says, “You're more likely to be on the bunny slopes!” “Bunny (bunny) slopes (slopes)” are low hills covered with snow, used by people who are just learning how to ski. They will not cause you to go down at a very high speed, and that's why they are used to teach people how to ski. We call those the “bunny slopes.” I think I've been on a bunny slope once. That was the one time I tried to learn how to ski.
Hanna says, “You've only been on a snowmobile once and gone cross-country skiing a few times. What makes you think you'll be able to ski the slopes like an expert?” Hanna says Ahmed has only been on a snowmobile once. A “snowmobile” (snowmobile) is a vehicle – something you move in that has an engine or a motor in it. It's sort of like a motorcycle that allows you to go across the snow.
“Cross-country skiing,” we've already explained, is skiing across flat land using your arms and your legs in a very different way than if you go downhill skiing. Hanna doesn't think that Ahmed will be able to “ski the slopes like an expert” – that is, to ski with a lot of expertise, to ski as though he were someone who was a very good skier. Ahmed says, “I can ice skate better than you can. So no matter what, I know I'll be better at it you'll be. When I get the hang of skiing, I'll probably try snowboarding.”
Ahmed says he can “ice skate” (skate). “To ice skate” means to move across a flat piece of ice, wearing special shoes that have what are called “blades” (blades) on them. The blades allow you to move across the ice. In order to play the sport of hockey, for example, you have to use ice skates. People also use ice skates to perform on the ice in the Olympics. For example, you will see ice skating as one of the events. I'm speaking, of course, of the Winter Olympics. Ahmed says because he knows how to ice skate, he will be better at skiing than Hanna. I'm not sure if that's necessarily true, but that's what Ahmed thinks is true.
He says, “When I get the hang of skiing, I'll probably try snowboarding.” “To get the hang (hang) of” something means to learn how to do something – to learn how to do something well enough so that you can perform it with some competence. You are able to do it pretty well. I never “got the hang of” skiing, at least downhill skiing. I know how to cross-country ski and have cross-country skied many times. I never liked it. It was a lot of work. I found it much easier just to take a car.
Well, Ahmed says that he, after getting the hang of skiing, will probably try snowboarding. “To snowboard” (snowboard) is to use a flat, short board to go down a hill of snow or ice, just like you would with skis. But skis are two separate pieces of equipment that attach to your feet. A “snowboard” is one piece of equipment, if you will – one piece of wood, or whatever the material it is made out of – that you put your feet on and use to slide down a hill with snow on it. A “snowboard” looks sort of like a skateboard, but without the wheels.
Hanna says, “Now I know you're blowing smoke. You don't have the nerve.” The expression “to blow smoke” (smoke) means very informally “to exaggerate” – to say something that isn't true while trying to make yourself appear better than other people. Hanna says, “You don't have the nerve” (nerve). “To have the nerve” to do something means to have the courage, to have the strength – especially when we are talking about something that may be difficult or inappropriate, even. If someone says, “He has a lot of nerve,” he's not giving a compliment or saying something nice about that person. He's saying that that person has done something arrogant or rude that most polite people would not do.
Ahmed says, “Oh, yeah? I challenge you to a game of one-on-one ice hockey.” “To challenge” someone is to say, “I want to compete with you. I want to play a game with you.” “One-on-one” means there are just two people in the game. “Ice hockey” is a sport usually played by two teams of players that try to get a small black disc called a “puck” (puck) into a net. It's sort of like soccer, but with sticks and ice skates and a lot of hitting the other player. That's hockey. A lot of fighting takes place in ice hockey, at least in the United States. I played ice hockey. Yeah, I did. When I was seven.
Hanna says, “You’re twice my size,” meaning you are twice as big as I am, physically. “Make it a snowball fight.” “Make it” means “let's change it” or “let's do this.” Hanna wants to have a snowball fight. A “snowball” is a round ball of snow, of course, that you make with your hands, and you throw it at other people. This is something that people who live in places where there is a lot of snow in the wintertime like to do. Certainly, when I was a kid, we used to have snowball fights all the time, especially with my brothers and sisters.
Ahmed says, “You're on.” That expression, “You're on,” is used to show that you agree with and accept what the other person has proposed, especially if it's a challenge to play a game or to have a contest of some sort.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Hanna: It’s finally snowing outside! Soon we’ll be able to get out the sled.
Ahmed: Sledding is for kids. I’m going downhill skiing as soon as there’s enough powder. I can’t wait to feel the wind in my hair as I careen down the side of a mountain.
Hanna: You’re more likely to be on the bunny slopes! You’ve only been on a snowmobile once and gone cross-country skiing a few times. What makes you think you’ll be able to ski the slopes like an expert?
Ahmed: I can ice skate better than you can, so no matter what, I know I’ll be better at it than you’ll be. When I get the hang of skiing, I’ll probably try snowboarding.
Hanna: Now I know you’re blowing smoke. You don’t have the nerve.
Ahmed: Oh, yeah? I challenge you a game of one-on-one ice hockey.
Hanna: You’re twice my size! Make it a snowball fight.
Ahmed: You’re on!
[end of dialogue]
She’s an excellent downhill skier and an amazing hockey player – really. I'm speaking of our very own scriptwriter, Dr. Lucy Tse. She's pretty good at scriptwriting, too.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to snow – for small, soft ice crystals to fall from the sky, usually sticking together
* If the weather gets a little colder tonight, it might snow. Otherwise, it will rain.
sled – several pieces of wood attached to a metal frame, used to sit or lie down on top of as one slides down a ramp or hill covered with snow
* Be careful the sled doesn’t crash into a tree!
downhill skiing – the sport and recreational activity of sliding down a mountain with skis (long, flat, narrow pieces) attached to one’s shoes, usually at a very fast speed
* Before you go downhill skiing, you’ll need to buy warm clothing, a waterproof jacket, a hat, gloves, and goggles.
powder – snow that has recently fallen and is still dry and loose, not yet compacted (pressed together)
* This powder is great for skiing, but not for making snowballs.
to careen – to move without control at a very high speed toward a specific palce, especially in a vehicle
* The driver ignored the speed limit and careened down the dangerous cliff.
bunny slope – a low hill covered with snow, used by people who are just beginning to ski or snowboard so that they can practice on the easiest paths without going very quickly
* Most children stay on the bunny slopes, but Craig was on some of the mountain’s hardest trails by the time he was nine years old.
snowmobile – a motorized vehicle that one or more people sit on top of, similar to a motorcycle, but with ski-like pieces instead of wheels
* In the wintertime, we use snowmobiles to get to the more distant fields.
cross-country skiing – the sport and recreational activity of moving over snow with skis (long, flat, narrow pieces) attached to one’s shoes, usually slowly over relatively flat surfaces
* Cross-country skiing offers a great workout, because it’s a lot of work to glide over the snow!
ice skate – to move over a flat surface of ice while wearing special shoes with a single blade on each foot
* I used to dream of doing jumps and spins while ice skating, but at this point, I’d be happy if I could just go in a straight line without falling down!
to get the hang of (something) – to become good at something; to learn to do something that is difficult or tricky
* If you keep practicing every night, you’ll get the hang of knitting in no time.
to snowboard – to slide downhill over snow with one’s feet attached to a flat, oval-shaped board like a skateboard without wheels, often while jumping and performing special tricks
* Snowboarding is very popular with young people, while older people tend to prefer skiing.
to blow smoke – to exaggerate; to say something that isn’t true while trying to make one appear better than one actually is
* Min says he can speak five languages fluently, but I think he’s blowing smoke.
to have the nerve – to be very bold in doing something that is rude, arrogant, or inappropriate
* I can’t believe she had the nerve to criticize the way you dress, considering that she wears shorts and flip-flops to the office.
ice hockey – a game played by two teams on the ice, trying to get the puck (a small disc) into a net at either end of the ice rink, similar to soccer
* Which sport is more violent: American football or ice hockey?
make it – a phrase used when one is making a suggestion, especially changing what another person has just proposed
* A: Let’s go get some hamburgers.
B: Make it pizza, and I’ll be ready to go in two minutes.
snowball fight – a playful game where people throw balls of snow at each other, usually without really trying to hurt the other person and without keeping score
* It hardly ever snows here, but when it does, the college students go to the main lawn and have a huge snowball fight.
you’re on – a phrase used to show that one agrees to and accepts what another person has proposed, especially when it is a challenge or an opportunity to compete
* When Brandon proposed a 3-mile race, Sheila smiled and said, “You’re on!”
Comprehension Questions
1. Which of these sports involves the slowest movements?
a) Downhill skiing
b) Cross-country skiing
c) Snowboarding
2. What does Hannah mean when she says that Ahmed is “blowing smoke”?
a) She can see water vapor coming out of his mouth in the cold air.
b) She thinks Ahmed smokes too much to be a good athlete.
c) She doesn’t believe that Ahmed can do what he says he’ll do.
Answers at bottom.
What Else Does It Mean?
powder
The word “powder,” in this podcast, means snow that has recently fallen and is still dry and loose, not yet compacted (pressed together): “Driving in powder isn’t too difficult, but watch out for icy roads!” When talking about makeup, “face powder” is a colored dust applied to a woman’s face to make it have a consistent, tanned color: “A little bit of powder can brighten your face and hide blemishes.” When talking about weapons, “gun powder” is the explosive substance put into a gun: “Please don’t smoke around the gun powder.” Finally, “baking powder” is a white substance added to baked goods to make them airier or lighter: “The muffins were really dense, so next time we’ll add some more baking powder.”
to blow smoke
In this podcast, the phrase “to blow smoke” means to exaggerate, or to say something that isn’t true while trying to make one appear better than one actually is: “Was she really an Olympic-level athlete, or is she just blowing smoke?” The phrase “to go up in smoke” means for something to fail or for continued progress to be impossible: “When Marcus was seriously hurt in the car accident, he saw many of his dreams go up in smoke.” Finally, the phrase “where there’s smoke, there’s fire” means that if something bad is being said about a person or organization, it’s probably true: “It’s hard to believe the rumors about their financial problems, but they’re probably true. After all, where there’s smoke, there’s fire.”
Culture Note
Unusual Winter Sports
Many Americans like to participate in “traditional” (common; with a long history) winter sports, such as skiing, sledding, ice skating, “snowshoeing” (walking over snow with large, flat objects attached to one’s shoes) and, more recently, snowboarding. But there are some more unusual winter sports that are becoming popular with “thrill-seekers” (people who look for excitement by participating in more dangerous activities).
For example, “ice diving” is the sport and recreational activity of “diving” (going underwater) under ice. Usually, the area is covered with a thick sheet of ice, so the diver has only one “point of entry” (where one enters something), which “doubles as” (is also) the only “point of exit.” If the diver becomes “disoriented” (not able to navigate; not sure where one is), he or she could have trouble finding the point of exit. That is why most ice divers are “tethered” (tied with a rope or cable) to something above the surface. Ice diving is also challenging because of the very cold temperature of the water and the air.
Another unusual winter sport is “skijoring,” where a person wearing skis is pulled over the snow by a strong dog, a horse, or a motorized vehicle. Sometimes this sport is complicated by “slaloms” (flags or other objects placed on a snow-covered course for the athletes to “maneuver” (move) around and/or “jumps” (ramps that the athlete moves over quickly so that he or she is in the air after leaving the highest point).
And some people even participate in “ski biking,” which is like bicycling, but the bicycle wheels have been replaced with skis, and the bike is pointed down a snow-covered mountain. The sport is “growing in popularity” (becoming more popular and common).
Comprehension Answers
1 - b
2 - c