= 0962
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 962 – Recovering After a Setback.
This is English as a Second Language Podcast episode 962. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this episode. You can also like us on Facebook at facebook.com/eslpod.
On this episode, we’re going to hear a dialogue between Carl and Shelly about someone who’s had some bad luck and is trying to recover. Let’s get started.
[start of dialogue]
Carl: Come on, let’s go. I have $500 burning a hole in my pocket.
Shelly: Where are we going?
Carl: We’re going to the track. I have a tip on a sure thing for one of this afternoon’s races. This is exactly what I need after last week’s setback.
Shelly: You mean after losing all of your money last week.
Carl: Right, but all I need to do is to get that monkey off my back and then I’ll have a reversal of fortune. Winning big this afternoon will be the start of a new winning streak.
Shelly: Maybe what happened last week is really a sign of things to come. Maybe it was the start of a losing streak.
Carl: Don’t jinx me with that kind of negativity. I’ve always believed that when you meet with a setback, come back with all you’ve got.
Shelly: Does that mean what I think it means?
Carl: Yes, that’s right. I’m plunking down all $500 on that race. I can’t lose.
Shelly: But what if –
Carl: Don’t say another word. When I win and get back in my stride, you can say, “Congratulations!”
[end of dialogue]
Carl begins our dialogue by saying, “Come on, let’s go. I have $500 burning a hole in my pocket.” “Come on” means “Let’s move. Let’s leave” – in this case, “Let’s go.” Carl and Shelly are going somewhere. It seems as though they’re going to gamble to try to win money by doing some sort of gambling. Carl says he has “$500 burning a hole in his pocket.” “To have money burning a hole (hole) in your pocket (pocket)” means to have some money that you want to spend and spend quickly, especially if it’s cash – if it’s paper money or coins.
Literally, your “pocket” is where you keep your keys and your money in your pants. Most pairs of pants have at least two pockets, one on each side. You’ll often have pockets in the back of the pants – to put a wallet, for example – at least, most men’s pants have a pocket in the back. “To burn a hole in your pocket” would mean that the money in your pocket would fall out. It would fall out through the hole that was burned by the money. It’s just an expression that we use when we have some money and we really want to go out and spend it, often spend it on things that aren’t very important or things that are just for fun.
Shelly says, “Where are we going?” Carl says, “We’re going to the track.” The “track” (track) here means the racetrack, a place where horses or dogs run around an oval-shaped path. You could also have a track for runners. In the Olympics, for example, there are races that go around the track. It’s like a large circle, but in the shape of an oval. Carl wants to go to the racetrack to bet money so he can win more money.
Carl says, “I have a tip on a sure thing for one of this afternoon’s races.” A “tip” (tip) here means some secret information that was given him that would give him some advantage in, in this case, winning money at the racetrack. Perhaps somebody who knows the horse or knows the person riding the horse – we call that person a “jockey” – gave this information to Carl. A “sure thing” is something you know will definitely happen. It’s guaranteed. It doesn’t involve any risk. It will 100 percent, for certain happen. Carl thinks that this horse – or dog, we’re not sure which – will definitely win the race, and so by betting on that horse or dog, Carl is sure that he will win.
“Races” are competitions – in this case, a race with different animals. Carl says, “This is exactly what I need after last week’s setback.” A “setback” (setback) is when you’re having good luck, or things are going well for you, and then suddenly something bad happens – something happens that delays or slows your progress. But you know it’s only temporary. You’re not worried about it.
A setback is a small, typically temporary problem that you think will go away, and in the very near future you will continue to be successful. That term is also sometimes used when someone is sick, especially in a hospital or with some illness or disease that lasts a long time. Someone may be getting better, and then they have a setback. They stopped getting better. They get a little worse.
Shelly says, “You mean after losing all of your money last week?” Carl’s setback was that he lost all of his money, at least all of the money he was gambling. Carl says, “Right,” meaning yes. “But all I need to do is to get that monkey off my back and then I’ll have a reversal of fortune.” The expression “to have a monkey (monkey) on your back” means that you have a serious problem that lasts a long time and is very difficult to resolve, or solve. “To have a monkey on your back” is to have a problem that lasts for a long time. It is been with you for a long time. Carl says that he has a monkey on his back, and so he wants to get the monkey off his back. “To have a monkey on your back” is to have a problem. “To get a monkey off your back” is to get rid of the problem.
Carl says if this happens – if he can get rid of this bad luck, basically – he’ll have a “reversal of fortune.” “Fortune” (fortune) means something very good, often a lot of money. We talk about someone “making a fortune in the stock market” – we mean this person made a lot of money in the stock market. A “reversal” (reversal) is when something changes, something changes completely, so that instead of winning, you are losing – or, instead of losing, you are winning. That would be a reversal. A “reversal of fortune” would be a change in your luck – suddenly, things are going well for you instead of poorly for you.
Carl thinks his luck is going to change. He says, “Winning big” – meaning winning a lot of money – “this afternoon will be the start of a new winning streak.” A “streak” (streak) is a series of things that happen one after the other. “To have a winning streak” means to be winning each and every competition that you enter. If a baseball team has a winning streak, they are winning every game, maybe 5 games “in a row (row),” we would say. When something happens consecutively, one after the other, we use the expression “in a row.” So, a winning streak might be winning 5 games in a row, or 10 games in a row.
Carl thinks that if he wins big this afternoon, he will be starting a new winning streak. Shelly says, “Maybe what happened last week is really a sign of things to come.” The expression “a sign (sign) of things to come” means that what has happened in the past will be the same thing that will happen in the future; it will give you an idea about what will happen in the future. The fact that Carl lost in the past, according to Shelly, may be a sign of things to come – that he will continue losing, not that he will have a reversal of fortune. Shelly says, “Maybe it was the start of a losing streak.” Just as you can win several games in a row, or several competitions, so you can lose several games or competitions in a row, and that’s what Shelly is saying here.
Carl says, “Don’t jinx me with that kind of negativity.” “To jinx” (jinx) someone means to bring bad luck to someone – to do something or say something that will cause problems for other people. People who are superstitious, or who believe in bad luck, worry about other people jinxing their projects – somehow causing them to have bad luck by something that they say, usually something negative. And that’s why Carl says, “Don’t jinx me with that kind of negativity.” “Negativity” is the idea of being pessimistic, of thinking that things will go poorly in the future.
Carl says, “I’ve always believed that when you meet with a setback” – when you have some difficulty – “come back with all you’ve got,” meaning you should respond with all of your energy, with full effort. Shelly says, “Does that mean what I think it means?” Carl says, “Yes, that’s right. I’m plunking down all $500 on that race.” “To plunk (plunk) down” means to spend a lot of money on something. “I’m going to plunk down $500 on a new iPad.” Well, I’m not, but that’s an example. “I’m going to plunk down a thousand dollars to buy my beautiful wife a new ring.” I’m not going to do that, either.
Carl says, “I can’t lose.” Shelly says, “But what if?” and then Carl interrupts her. Carl says, “Don’t say another word. When I win and get back in my stride, you can say ‘Congratulations.’” “To get back in your stride” or “into your stride” (stride) means to return to doing something well after a period of not doing it well – to start having success after you’ve had several failures. Carl thinks he’s going to win at the racetrack today and doesn’t want Shelly to bring him any bad luck.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Carl: Come on, let’s go. I have $500 burning a hole in my pocket.
Shelly: Where are we going?
Carl: We’re going to the track. I have a tip on a sure thing for one of this afternoon’s races. This is exactly what I need after last week’s setback.
Shelly: You mean after losing all of your money last week.
Carl: Right, but all I need to do is to get that monkey off my back and then I’ll have a reversal of fortune. Winning big this afternoon will be the start of a new winning streak.
Shelly: Maybe what happened last week is really a sign of things to come. Maybe it was the start of a losing streak.
Carl: Don’t jinx me with that kind of negativity. I’ve always believed that when you meet with a setback, come back with all you’ve got.
Shelly: Does that mean what I think it means?
Carl: Yes, that’s right. I’m plunking down all $500 on that race. I can’t lose.
Shelly: But what if –
Carl: Don’t say another word. When I win and get back in my stride, you can say, “Congratulations!”
[end of dialogue]
If there is a sure thing for improving your English, it’s the scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
burning a hole in (one’s) pocket – a phrase used to describe the tendency for people to spend money very quickly and easily, especially when they’re holding cash (paper and coin money)
* I wish our employer would deposit our earnings directly into our bank accounts. Then, I wouldn’t have all this cash burning a hole in my pocket.
track – an oval-shaped path used by runners, horses, or cars for racing
* This is a quarter-mile track, so you have to run four laps to complete one mile.
tip – secret or privileged information that provides some advantage, especially for solving a mystery or making money
* As the bank CEO, Hal could go to prison for sharing investment tips related to the company’s stock.
sure thing – something that will definitely happen; something that is guaranteed to happen and does not involve any risk
* Anyone who says that a new business is a sure thing is lying. It’s impossible to know which businesses will succeed and which ones will fail.
race – an organized event where people, cars, horses, or other things compete to see which one can go the fastest and be the first to travel a certain distance, especially when observers are making bets to win
* Pete lost more that $300 at the dog races last weekend.
setback – a temporary pause or reversal of one’s progress or good luck; a challenging situation that delays or slows one’s progress, but that is not expected to last forever
* The government shutdown presented a setback to restaurants and hotels near national parks, because they depending on tourists’ business.
monkey on (one’s) back – a serious problem that lasts a long time and is difficult to resolve
* This student loan is a monkey on my back. I can’t wait to pay it off!
reversal of fortune – a change in luck, especially to good luck after a period of bad luck
* After receiving more than 50 rejection letters, the author finally received an acceptance letter and celebrated his reversal of fortune.
winning streak – a period of time when a team or a better has many wins and no losses; an uninterrupted series of wins
* The team had a terrific winning streak until late November, when the best player broke his ankle. Then the team started losing.
sign of things to come – an omen; a signal; the idea that what has just happened provides insight into what will happen in the future
* In the past few years, extreme weather has become more common. Is this a sign of things to come as a result of global warming, or is it just a coincidence?
to jinx (someone) – to bring bad luck to someone; to do or say something that creates problems for another person
* Never jinx an actor by saying “good luck” before a show! Don’t you know you’re supposed to say, “Break a leg”?
negativity – pessimism; a tendency to think that things are bad and that more bad things will happen
* I hope the new employee is more optimistic than the last person who worked in that position. It’s awful to work in an office with so much negativity!
with all you’ve got – with full effort; trying as much as possible
* Yes, the exam is going to be hard, but if you study with all you’ve got, I’m sure you’ll pass.
to plunk down – to spend a lot of money on something
* It seems crazy to plunk down $400,000 on a small, one-bedroom apartment, but housing prices are very high in the city.
to get back in (one’s) stride – to return to doing something well after a period of not doing something well; to resume one’s progress or success
* Sarah is a professional athlete who got in a serious car accident. It has taken a few months, but she’s finally getting back in her stride after recovering from her injuries.
Comprehension Questions
1. What does Carl mean when he says, “Don’t jinx me with that kind of negativity”?
a) He thinks she’s going to give him bad luck.
b) He thinks she’s being offensive.
c) He thinks she’s jealous of his success.
2. What could end a winning streak?
a) A tip.
b) A setback.
c) Negativity.
Answers at bottom.
What Else Does It Mean?
tip
The word “tip,” in this podcast, means secret or privileged information that provides some advantage, especially for solving a mystery or making money: “Here’s an investment tip: if a deal sounds too good to be true, it probably is.” A “tip” can also be a suggestion for how to do something well: “Do you have any tips for getting a red wine stain out of white carpet?” A “tip” is also money given to someone to thank him or her for good service: “Sheila always leaves a 15% tip for waiters and waitresses.” Or, “How often do pizza delivery boys receive tips?” Finally, the phrase “on the tip of (one’s) tongue” describes an inability to find the word one is looking for to describe something: “His name is on the tip of my tongue, but I can’t quite remember it.”
stride
In this podcast, the phrase “to get back in (one’s) stride” means to return to doing something well after a period of not doing something well, or to resume one’s progress or success: “Sales have been low for the past few months, but once we open the new store we should get back in our stride.” The phrase “to take (something) in stride” means to not let something bother, upset, or annoy you: “Chloe has had a lot of unexpected expenses this past month, but so far she’s taking it in stride.” Finally, the word “stride” means one step while walking: “He has long legs and such a big stride that his daughter has to run to keep up with him.”
Culture Note
Horse Racing Phrases in Everyday English
Many popular phrases in modern English come from horse racing, although American speakers may be unaware of the phrases’ “origins” (where something comes from or how something was first used).
For example, the phrase “off to a flying start” describes beginning something with a lot of energy, without a gradual start: “Their new business is off to a flying start, but I wonder how long it can last.” And the phrase “off and running” has a similar meaning: “The new campaign should be off and running by early spring.”
The phrase “a run for (one’s) money” means a challenge, even if no money is actually involved. Someone might say, “That cold really gave me a run for my money, but fortunately, I’m feeling much better now.”
The phrase “to back the wrong horse” means to support something that loses or fails. “Yes, we were backing the wrong horse when we advocated for opening an office in North Dakota, but this time, we’re sure expansion is the right move.” The phrase “to beat a dead horse” means to do something that is “futile” (pointless because it cannot work or succeed): “Every time you buy her flowers or chocolates and sing outside her window, you’re just beating a dead horse. She doesn’t want to date you anymore.”
Finally, the phrase “to win by a nose” means to win when the second-place person is right behind, in a very “close race” (a competition that almost ends in a tie, with no real winner), just as a horse race could be won if one horse is just a nose’s length in front of the next horse: “Wow, that was close! The basketball team won by a nose in the last minute of the game.”
Comprehension Answers
1 - a
2 - b