= 0996
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 996 – Importing Goods to the U.S.
This is English as a Second Language Podcast episode 996. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. This episode is a dialogue between Muriel and Daniel about importing, or bringing into the United States, goods – things to sell. Let’s get started.
[start of dialogue]
Daniel: You look like you’re sitting on pins and needles.
Muriel: I am. I’m waiting to hear if our goods have cleared customs yet. We’re in big trouble if our 50 crates aren’t released soon.
Daniel: You’ve filled out the proper paperwork. What could go wrong?
Muriel: You have no idea how much red tape there is when importing goods to the U.S. There are all kinds of rules to follow, and we have to pay the correct tariffs.
Daniel: But I thought we had a free-trade agreement with Niebuhrland. All goods imported from and exported to Niebuhrland should be duty-free.
Muriel: Most things are duty-free, but not everything. There are tariffs on spirits, and the tax rate varies depending on the type of spirits. It’s all very confusing.
Daniel: Well, sitting here fretting won’t do any good.
Muriel: If only I had access to those 50 crates of spirits . . .
[end of dialogue]
Daniel begins our dialogue by saying, “You look like you’re sitting on pins and needles.” Daniel is talking to Muriel. The expression “to be sitting on pins (pins) and needles (needles)” means to be very nervous, to be worried, to be anxious, especially while you’re waiting for something to happen. If you’ve taken an important examination and you’re waiting for the results, you could say that you are “sitting on pins and needles.”
Pins and needles are sharp objects, and obviously if you were sitting on a sharp object, it would be very painful. So, waiting for news – being worried about something that may happen – can be a little painful. That’s what the expression here means, “sitting on pins and needles.” Muriel says, “I am.” I am, basically, anxious or worried. “I’m waiting to hear if our goods have cleared customs yet.” “Goods” is a general word meaning “products,” things that you make.
We usually distinguish “goods” from “services,” things that you do for people. So, a lawyer provides a “service,” and a store may provide a “good.” You buy some milk from the grocery store – that’s a “good.” You ask a lawyer to help you with some legal issue – that’s a “service.” Muriel is “waiting to hear” – that is, waiting to find out – “if our goods have cleared customs yet.” “Customs” (customs) here means the process that a country has for checking to make sure that things that are brought into the country are legal and, depending on the item, have been assessed a tax.
When you bring things into a country, the country will often have taxes that you have to pay to bring that item into the country, especially if you’re going to sell it in the country. So, when you import – when you bring things into a country – here in the United States, you may have to pay certain taxes when you bring the items into the country, and the place where you pay those taxes, the office that takes care of that for the U.S. government, is called “customs.”
The opposite of “import” is “export” (export). That means to send things to another country. But here we’re talking about importing goods into the United States. Muriel says, “We’re in big trouble if our 50 crates aren’t released soon.” A “crate” (crate) is a large, usually wooden container that typically has holes in it. We often use crates when we are transporting food such as fruit and vegetables. “To be released” means to be let go. In this case, it means that the crates are with the customs office, and you are waiting for the customs office to let you pick them up – take them away.
Daniel says, “You’ve filled out the proper paperwork. What could go wrong?” “Paperwork” is a general term referring to documents that you have to complete, forms that you have to fill out in order to get something done. The government – all governments – require lots of paperwork. You have to fill out this form, and then you have to give them this document, and so forth.
Muriel says, “You have no idea how much red tape there is when importing goods to the U.S.” The term “red tape” refers to difficult rules or requirements, usually by the government, that you must follow in order to do something. “Red tape” could involve regulations and rules. It could also involve filling out lots of forms – that is, a lot of paperwork.
You may wonder why we call it “red tape.” The answer is that the expression was originally used in England. The British government, when it had official papers, official documents to send, would tie them up with this red tape, and you had to untie the tape in order to read the documents and then tie them back up and send them to the next place. So, eventually this expression became a way of indicating useless and needless delays when it took too long for something to happen, and that’s how it is used today to talk about government regulations and rules that take a lot of time but don’t seem very necessary. They don’t seem useful.
Muriel says, “There’s a lot of red tape when you are importing,” or bringing into the country, “goods.” She says, “There are all kinds of rules to follow, and we have to pay the correct tariffs.” A “tariff” (tariff) is what we call that special tax you have to pay when you bring things into a country. The tariffs have to be paid before you are allowed to bring things in, before you are allowed to take them and sell them. Daniel says, “But I thought we had a free-trade agreement with Niebuhrland?” Niebuhrland is not a real place, although I do know someone named Niebuhr.
“Free-trade agreements” are treaties – agreements between countries that allow businesses in each of those countries to sell their products without having to pay tariffs. Here in North America, we have something called NAFTA, the “North American Free Trade Agreement,” which is supposed to allow businesses in Canada, the U.S., and Mexico to sell to customers in those three countries without having to pay a lot of special tariffs. Of course, it usually doesn’t work out exactly that way. There are usually exceptions to any sort of free-trade agreement, but that’s the general idea.
Daniel continues, “All goods imported from and exported to Niebuhrland should be duty-free.” We already talked about the meaning of the verb “to export.” The term “duty (duty) free” means that you don’t have to pay any taxes or tariffs. In many countries, at the airport, if you are traveling internationally, if you are leaving the country, there will be a “duty-free shop,” a place where you can buy expensive things – watches, alcohol, and so forth – without paying the local taxes. That’s a duty-free shop. Well, being able to import and export duty-free means you don’t have to pay any special taxes as a business. You don’t have to pay any tariffs.
Muriel says, “Most things are duty-free, but not everything. There are tariffs on spirits, and the tax rate varies depending on the type of spirits. It’s all very confusing.” “Spirits” (spirits) here refers to alcohol. It’s sort of an older word, but you will still see it, especially when you’re talking about tariffs and taxes. Muriel says, “There are tariffs on spirits, and the tax rate varies.” The “tax rate” is the amount, or percentage of the price of the good, that you have to pay to the government. “Varies” means it changes. In this case, it changes depending on the type of alcohol, the type of spirits.
Daniel says, “Well, sitting here fretting won’t do any good.” “To fret” (fret) means to worry about something, especially something that you don’t have any control over. Of course, if you can’t control something, there’s no reason to worry about it, but we all do. We all fret over things that we can’t control.
Muriel says, “If only I had access to those 50 crates of spirits.” “To have access to” means to be able to reach them. Muriel is making a joke here. She’s saying that if she had access to the alcohol, then she wouldn’t have to worry as much because she could drink the alcohol. That’s the general idea.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Daniel: You look like you’re sitting on pins and needles.
Muriel: I am. I’m waiting to hear if our goods have cleared customs yet. We’re in big trouble if our 50 crates aren’t released soon.
Daniel: You’ve filled out the proper paperwork. What could go wrong?
Muriel: You have no idea how much red tape there is when importing goods to the U.S. There are all kinds of rules to follow, and we have to pay the correct tariffs.
Daniel: But I thought we had a free-trade agreement with Niebuhrland. All goods imported from and exported to Niebuhrland should be duty-free.
Muriel: Most things are duty-free, but not everything. There are tariffs on spirits, and the tax rate varies depending on the type of spirits. It’s all very confusing.
Daniel: Well, sitting here fretting won’t do any good.
Muriel: If only I had access to those 50 crates of spirits . . .
[end of dialogue]
The quality of our scripts never varies – it’s always very high, thanks to our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
to sit on pins and needles – to be very anxious, nervous, and worried, especially while waiting for something to happen
* Jan’s husband was sitting on pins and needles during her surgery.
goods – products; items that are produced, bought, and sold
* If our suppliers can’t deliver the goods by Friday, we won’t be able to open our new store on Monday.
to clear – to complete a process and be approved so that one can pass through and no longer be subject to certain requirements or regulations
* As soon as this budget is cleared by the executives, we can begin implementation.
customs – the process of checking for illegal items and collecting taxes on legal items being brought into a country, as well as the agency or department responsible for that work
* You can take a personal computer through customs, but if you take several computers, they’ll think you’re planning to sell them and you’ll have to pay a fee.
crate – a large wooden or plastic box with an open top and holes in the sides and bottom, usually used to transport bottles, fruits, or vegetables
* How many crates of peaches can you pick in one day?
to be released – to be freed from some restrictions or limitations and allowed to move forward or proceed
* Once the money is released by the accounting department, we can usually mailed out payments within two business days.
paperwork – documents that have to be completed, usually in order to obtain permission from the government in order to do or have something
* I never realized how much paperwork would be involved in starting a new business.
red tape – inconvenient and difficult rules or requirements that make it difficult to do something
* Adopting a child internationally is difficult to do. There is a lot of red tape.
to import – to bring something into a country so that it can be sold there
* The United States imports a lot of cars from Japan and Germany.
tariff – a tax on products that enter a country and that must be paid before they can be sold
* Tariffs can be used to protect domestic manufacturers from being underpriced by international competitors.
free-trade agreement – an official document signed by two or more countries that have agreed to import and export goods without charging tariffs or other taxes on them, used to encourage greater trade and economic growth
* Many people are opposed to the free-trade agreement because they think it means having fewer jobs in this country.
to export – to send something out of a country so that it can be sold in another country
* Instead of exporting low-value raw materials, we should be exporting high-value, finished products.
duty-free – tax-free; not having to pay any tariffs or taxes
* Whenever Kip flies internationally, he buys cigarettes and perfume in the duty-free shop inside the airport.
spirits – alcoholic drinks
* Many cities have made it illegal to buy or sell spirits on Sunday.
tax rate – the percentage of a price or value that is charged as tax
* The local sales tax rate is 7.4%.
to vary – to differ; to have different values or amounts in different locations or circumstances
* How many miles Alinda runs each week varies depending on how much time and energy she has.
to fret – to worry about something, especially something that one does not have control over
* Tanner spends too much time fretting over his investments.
to have access to – to be able to reach or have something; to be allowed to have or do something
* Bryan will be out of the office next week, but he will have access to his voicemail and email in case anything urgent comes up.
Comprehension Questions
1. Why is Muriel sitting on pins and needles?
a) Because she is very worried about something.
b) Because she has an uncomfortable chair.
c) Because she is spending a lot of money in customs.
2. What does Muriel mean when she says, “You have no idea how much red tape there is”?
a) He doesn’t understand how expensive the process is.
b) He doesn’t understand how many people are involved.
c) He doesn’t understand how many regulations there are.
Answers at bottom.
What Else Does It Mean?
to be released
The phrase “to be released,” in this podcast, means to be freed from some restrictions or limitations and allowed to move forward or proceed: “Due to the snowstorm, all employees are released from their regular duties for the rest of the day and may go home early.” The phrase “to be released” also means to free someone from jail so that he or she can leave: “If those criminals are released, they’ll just commit more crimes.” When a movie is “released,” is it made available to the public for viewing: “When was that film released on DVD?” Finally, the verb “to release” can simply mean to let go of something and stop holding it so that it returns to its normal position: “Release the brake on the car slowly.”
spirits
In this podcast, the word “spirits” means alcoholic drinks: “Their kitchen is stocked with rum, whisky, gin, vodka, and other spirits.” The phrase “high spirits” describes a good mood: “Why are you in such high spirits today? Did you receive some good news?” The word “spirits” can also refer to ghosts: “Shania says that spirits haunt the third floor of this old house, but I don’t believe in ghosts.” The phrase “that’s the spirit” shows approval of what someone is saying or doing, but sometimes it is used sarcastically: “When Devon said, ‘I guess I can try,’ his friend said, ‘That’s the spirit!’” Finally, the phrase “to get into the spirit of (something)” means to begin to feel excited and happy about something, especially so that one can participate: “It took Shane a long time to get into the spirit of the party and start having fun.”
Culture Note
Harmonized Tariff Schedule for the United States
The Harmonized Tariff Schedule for the United States is a detailed “schedule” (list) of nearly all products that may be imported into the United States, as well as their “tariff classifications” (groups having to pay specific tax rates). The Schedule “assigns” (gives; names) a “10-digit” (with 10 numerals) number to goods based on their name, use, and “make-up” (what something is made from).
The Schedule has 22 sections and 99 chapters, and finding a specific type of product can be “daunting” (intimidating because something is very difficult). For example, the first part of Section “XI” (11 in Roman numerals) looks like this:
Section XI: “Textile” (items made from cloth) and Textile Articles
Chapter 50 “Silk” (very fine fabric made from the “cocoons” (shelters for larva before they become butterflies) of silkworms)
Chapter 51 Wool, fine or coarse animal hair; horsehair yarn and woven fabric
Chapter 52 Cotton
Chapter 53 Other vegetable textile fibers; paper yarn and woven fabric of paper yarn
Chapter 54 Man-made “filaments” (thin thread-like objects)
Chapter 55 Man-made “staple fibers” (wool, cotton, hemp, and other natural substances that can be made into yarn)
Chapter 56 “Wadding” (soft, thick material often used for packing fragile items), felt and nonwovens; special yarns, twine, cordage, ropes and cables and articles “thereof” (part of the things just mentioned)
Chapter 57 Carpets and other textile floor coverings
Chapter 58 Special woven fabrics; tufted textile fabrics; “lace” (delicate fabric with many holes, often used for women’s “lingerie” (sexy underwear)), “tapestries” (woven pieces of art hung on the wall); trimmings; embroidery
Comprehension Answers
1 - a
2 - c