= 0999
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 999 – Being Vague and Unfocused.
Going to party like it’s episode 999.
Oh, hi. Welcome to English as a Second Language Podcast episode 999. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
I’m happy today. This is episode 999. You can visit our website at ESLPod.com. On this episode, we’re going to listen to a dialogue between Thierry and Bonnie about being vague and unfocused. Let’s get started.
[start of dialogue]
Thierry: I’m pumped and ready to help paint the community center this weekend. What time are we supposed to get there in the morning?
Bonnie: I’m not sure. Sophia was a little vague about that. She told people to show up when they can make it.
Thierry: That doesn’t sound like an auspicious start. How many people are supposed to be there?
Bonnie: I’m a little fuzzy on that, too. Sophia didn’t have a sign-up sheet. She just told people to show up if they could.
Thierry: I hate to say it, but Sophia is the worst person to be organizing this. Her heart is in the right place, but her head is in the clouds. I don’t think I’ve ever met a more absentminded person.
Bonnie: I know what you mean. She always seems to be daydreaming.
Thierry: I’m going to call her right now and pin her down. She needs to attend to the nitty-gritty if this is project is going to get done.
Bonnie: What if she’s as vague as she usually is?
Thierry: I’ll try speaking to her on a different frequency: Earth to Sophia, Earth to Sophia . . .
[end of dialogue]
Our dialogue begins with Thierry saying, “I’m pumped and ready to help paint the community center this weekend.” “To be pumped” (pumped) means to be very excited, to be prepared and eager to do something, to do something with a lot of in enthusiasm. That’s what Thierry is saying here. He’s pumped to paint the community center this weekend. A “community center” would be a building that is used by people in a certain neighborhood, a certain part of town, for meetings and classes and things of that nature. Community centers are usually built by the local government.
He says, “What time are we supposed to get there in the morning?” Bonnie says, “I’m not sure. Sophia was a little vague about that.” To be vague” (vague) means to be unclear, not very specific. Bonnie says that Sophia was “a little vague” – somewhat vague – about what time they should get to the community center in the morning to paint. Bonnie says, “She told people to show up when they can make it.” “To show up” is a two-word phrasal verb meaning to appear, to come, to be present at some event or at some location.
Normally, you show up for work at eight o’clock in the morning or maybe nine o’clock in the morning. That’s one possible use of “to show up.” Often it’s used to mean to attend: “How many people showed up at the meeting last night?” How many people attended? How many people went to the meeting? Bonnie says that Sophia said that people should “show up when they can make it.” “To make it” here means to be able to do something, especially to be able to go somewhere for some purpose. I wanted to go to the movie last night, but it was raining and I didn’t make it. I didn’t actually go.
Thierry says, “That doesn’t sound like an auspicious start.” “Auspicious” (auspicious) means favorable, indicating that something good will happen. It’s not a common word in English conversation, but you will read it. You will sometimes also hear people say “auspicious” when talking about something that indicates that this event is going to go well, or in this case, that this event is not going to go well. Thierry says this doesn’t – this does not – sound like an auspicious start.
“How many people are supposed to be there?” He asks. Bonnie says, “I’m a little fuzzy on that too.” “To be fuzzy” (fuzzy) here means to be vague, to be unclear, not to be very specific. Bonnie says, “Sophia didn’t have a sign-up sheet.” The word “sheet” (sheet) here means a sheet of paper, a piece of paper. A “sign-up sheet” is a piece of paper where you put your name down to indicate that you are going to participate in something or you are going to do something. A sign-up sheet would be used for some event for which you want to know who is coming or how many people are coming.
Thierry says, “I hate to say it, but Sophia is the worst person to be organizing this. Her heart is in the right place, but her head is in the clouds.” There are two common expressions there. First, “to have your heart (heart) in the right place.” “To have your heart in the right place” means that you have good intentions. You want to do the right thing. You want to do good.
“To have your head in the clouds” means that you’re not a very practical person. You’re not a person who worries about the details, about the specifics, of something. In other words, you’re not a very good person to plan or organize something, because you’re not paying attention to the specific details that you need to pay attention to. Sophia, then, wants to do the right thing, but she’s not a very practical person. “Her heart is in the right place, but her head is in the clouds.”
Thierry says, “I don’t think I’ve ever met a more absentminded person.” “To be absentminded” (absentminded) – one word – means to be forgetful, to be unable to concentrate or focus. There’s an old expression, “the absentminded professor,” referring to someone who teaches at the university. We think of professors as being absentminded because although they are very smart – they have a lot of intelligence – they are often not very practical. So, we have this image of the absentminded professor.
Sophia is also considered to be absentminded by Thierry. Bonnie says, “I know what you mean. She always seems to be daydreaming.” “To daydream” is to imagine things that aren’t actually happening right now, and may never happen, during the middle of the day. Normally, we think about dreaming as something that you do at night when you’re sleeping. “Daydreaming” is to be imagining things happening right now, instead of, of course, actually doing your work.
If you are sitting at your desk in your office at work and daydreaming, your boss will not be very happy. You’re supposed to be working, not dreaming about your vacation next year in Hawaii or in France or wherever you take your vacation. You daydream about pleasant things, things that you want to happen or that might happen.
Thierry says, “I’m going to call her right now and pin her down.” “To pin (pin) someone down” is a phrasal verb meaning to make them give you a specific answer to your question, to make them give you the details of something, especially when that person has been vague about the issue that you are asking about. Thierry says “She,” meaning Sophia, “needs to attend to the nitty-gritty if this project is going to get done.”
“To attend (attend) to” something means to pay attention to something, to address something, to take care of something. Notice that you use this expression with the preposition “to” at the end. It’s always something you are attending to. This is different than the verb “to attend,” which can mean something similar as “to attend to,” but it could also mean “to show up” – to go to a certain place. Here in this sentence, it means to take care of or pay attention to something.
Thierry wants Sophia “to attend to the nitty-gritty.” “Nitty (nitty) – gritty (gritty)” refers to the specific details. Sophia hasn’t attended to the nitty-gritty here. She hasn’t told people exactly what time they should be there or found out even how many people are going. Bonnie says, “What if she’s as vague as she usually is?” What if, in other words, she doesn’t give Thierry the details he’s looking for? Thierry says, “I’ll try speaking to her on a different frequency: Earth to Sophia, Earth to Sophia . . .”
Thierry’s making a joke here. The word “frequency” is normally used to talk about measuring radio waves. Here, really it refers more to a particular channel for audio or radio communication. In order for two people to talk to each other on the radio, they both have to be on the same frequency, on the same channel – and that, in fact, is another common expression in English: “to be on the same frequency.”
We even say “to be on the same wavelength” when we are talking about someone who is thinking the same way we are, someone to whom we can communicate our ideas easily. “Wavelength” is another term you will hear people use in talking about radio communication. When Thierry says he is going to try to speak to Sophia “on a different frequency,” he means he’s going to try to reach her – to communicate with her – because she doesn’t seem to understand normal human communication.
Then he uses the expression “Earth to Sophia.” When you say, “Earth to” someone, you are trying to get their attention, but the idea is that this person isn’t paying attention. It’s almost as if this person were from another planet and you, being on planet Earth, are trying to communicate to this person. Perhaps this expression became popular during the era of space exploration in the twentieth century, I’m not sure. But it means that you are trying to communicate with someone who seems to not be listening or not be paying attention to what you are talking about.
It’s a somewhat insulting way to talk to someone. If you feel as though someone isn’t listening to you or isn’t paying attention to you, you might use this expression as a joke to get the person to pay attention. We may also use this expression when someone has an idea that is completely unrealistic or very incorrect, very wrong. The person doesn’t seem to be thinking rationally. Someone says, “I’m going to walk from New York City to Paris.” Well, you might use the expression here, “Earth to Jeff, you can’t walk from New York to Paris” – at least not very easily.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Thierry: I’m pumped and ready to help paint the community center this weekend. What time are we supposed to get there in the morning?
Bonnie: I’m not sure. Sophia was a little vague about that. She told people to show up when they can make it.
Thierry: That doesn’t sound like an auspicious start. How many people are supposed to be there?
Bonnie: I’m a little fuzzy on that, too. Sophia didn’t have a sign-up sheet. She just told people to show up if they could.
Thierry: I hate to say it, but Sophia is the worst person to be organizing this. Her heart is in the right place, but her head is in the clouds. I don’t think I’ve ever met a more absentminded person.
Bonnie: I know what you mean. She always seems to be daydreaming.
Thierry: I’m going to call her right now and pin her down. She needs to attend to the nitty-gritty if this is project is going to get done.
Bonnie: What if she’s as vague as she usually is?
Thierry: I’ll try speaking to her on a different frequency: Earth to Sophia, Earth to Sophia . . .
[end of dialogue]
There’s nothing vague or unfocused about our wonderful scripts here on ESL Podcast. That’s because they’re written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
pumped – very excited and eager to do something; prepared and ready to do something with a lot of enthusiasm
* Jenna is pumped about going to the concert this weekend.
vague – unclear, without enough detail or clarity; not specific
* The job description sounds interesting, but it’s really vague about the salary and benefits.
to show up – to appear; to be present at a location or event; to come, especially without a formal commitment to do so
* What time did Anastasia finally show up for the dinner party?
to make it – to be able to do something, especially to be able to go somewhere for some purpose
* Do you think you’ll make it in time for the opening remarks of her speech?
auspicious – favorable; an omen or indication that something good will happen
* The sunny weather was an auspicious beginning to his first day in the new job.
fuzzy – vague; unclear, without enough detail or clarity; not specific
* Childhood memories seem to become fuzzier as I get older.
sign-up sheet – a piece of paper where everyone who comes to an event or participates in an activity writes down his or her name and possibly contact information
* Please use the sign-up sheet, take one packet, and find an empty seat.
(one’s) heart is in the right place – a phrased used to mean that one has good intentions and wants to do the right thing
* Clarke wants to help, but everything he does seems to make the situation worse. At least his heart is in the right place.
(one’s) head is in the clouds – a phrase used to describe a dreamer, someone who is lost in thought, but not practical and not concerned with the details
* Sheila is an artist whose head is in the clouds, always thinking about her next great piece of art.
absentminded – inattentive and forgetful, unable to concentrate or focus
* Oliver is so absentminded that he accidentally put his car keys in the washing machine.
to daydream – to think about pleasant things, almost as if dreaming, but while one is awake, especially while one should be focusing on something else
* These class notes don’t make sense. I must have been daydreaming while the professor was talking.
to pin (someone) down – to make someone respond clearly, providing a definite answer or a piece of information, especially when that person would prefer to be vague
* How did you finally pin him down and get him to make a decision?
to attend to – to pay attention to something; to address, handle, or manage something; to be aware of something and in control of it
* Don’t forget to attend to those bills before they become overdue.
nitty-gritty – specific details; the practical, meaningful facts related to something
* We’ve verbally agreed to work together, but now we need to review the nitty-gritty during contract negotiations.
frequency – a measurement of the number of radio waves per second; a channel for radio
* Which frequency should we tune into for radio news updates during an emergency?
Earth to (someone) – an informal, slightly rude phrase used to get someone’s attention when that person is clearly thinking about something else, as if that person were on another planet
* I had been talking for five minutes when I realized that Sara wasn’t listening to me at all. I said, “Earth to Sara, can you hear me?”
Comprehension Questions
1. What does Thierry mean when he says, “I’m pumped”?
a) He has been lifting weights, so he’s strong enough for the painting project.
b) He has finally saved up enough money for the painting project.
c) He is really excited about the painting project.
2. What is Thierry going to do when he “pins” Sophia down?
a) He’s going to ask her for more specific information.
b) He’s going to criticize her for being so disorganized.
c) He’s going to start doing her job for her.
Answers at bottom.
What Else Does It Mean?
to be pumped
The phrase “to be pumped,” in this podcast, means to be very excited and eager to do something, or prepared and ready to do something with a lot of enthusiasm: “The builders are almost finished with the new home and we’re pumped to move in.” The phrase “to pump iron” means to lift weights for exercise in order to build muscle: “As a professional bodybuilder, Trent spends hours pumping iron in the gym each day.” Finally, the phrase “to pump money into (something)” means to invest a lot of money in a project: “Pharmaceutical companies sometimes have to pump money into drug development for years before they have a product they can sell.”
to pin (someone) down
In this podcast, the phrase “to pin (someone) down” means to make someone respond clearly, providing a definite answer or a piece of information, especially when that person would prefer to be vague: “Try to pin him down on a sales price early in the negotiations.” When talking about wrestling, the phrase “to pin (someone) down” means to use one’s weight on top of another person’s body so that he or she cannot get up or cannot move: “How did you pin down your opponent so quickly?” Finally, the phrase “to pin the blame on (someone)” means to blame another person, saying that he or she is the cause of a problem even though it isn’t true, “Hey, don’t pin the blame on your sister when you were equally responsible for what happened.”
Culture Note
Community Organizing and Grassroots Efforts
In the United States, people who are dissatisfied with the “status quo” (the way things are) have three options: they can ask their “elected representatives” (the people who were voted into positions to represent others in the government) to “address” (deal with) the issue, they can “learn to live with it” (become accustomed to the unpleasant way things are), or they can fight for change. People who fight for change often turn to “community organizing” and “grassroots efforts,” or loosely organized groups of ordinary people who feel “passionately” (very strongly) about a particular “cause” (a movement; something that needs to change) and spend a lot of time and energy promoting that cause.
Community activists and grassroots leaders face great “obstacles” (things that make it difficult to achieve one’s goals), but they are “persistent” (don’t stop trying). They often “cite” (repeat words said by someone else) Margaret Mead, an author who said, ““Never ‘doubt’ (thinking that something might not be true) that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has.”
Most grassroots efforts begin at the local level, sometimes even focusing on a particular building, such as when the “tenants” (renters; people who live in a building owned by someone else) of an apartment building organize themselves to demand repairs or better living conditions. But other groups have a much larger “scope” (the topics and area one wants to cover) and “end up” (eventually; in the end) becoming national movements, such as the “civil rights movement” (efforts to ensure that all people are treated fairly) and “anti-war movements” (efforts to prevent and/or end wars).
Comprehension Answers
1 - c
2 - a