
= Chapter 9
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

Bargain hard 努力讨价还价；认真议价。

[.my2]
努力讨价还价。

A few years ago, I fell in love with 爱上；迷恋上 a red Toyota 4Erunner.

[.my2]
几年前，我迷上了一辆红色的丰田 4Runner。

Actually, not just red, but salsa red pearl 莎莎红珍珠色；一种特殊的红色。

[.my2]
实际上，不只是红色，而是莎莎红珍珠色。

Kind of a smoldering 阴燃的；闷燃的 red that seemed to glow 发光；闪耀 at night.

[.my2]
一种闷燃的红色，似乎在夜间会发光。

How sexy 迷人的；性感的 is that? I just had to have it.

[.my2]
那多迷人？我就是得拥有它。

Getting one became my obsession 着迷；痴迷。

[.my2]
得到一辆成为了我的痴迷。

I searched the dealers 经销商；代理商 in metropolitan 大都市的；大城市的 Washington DC, and I quickly realized 意识到；认识到 that I wasn't the only one obsessed with 着迷于；痴迷于 getting that truck.

[.my2]
我搜索了华盛顿特区大都市地区的经销商，我很快意识到，不只有我一个人痴迷于得到那辆卡车。

There weren't any in that color in the entire area.

[.my2]
整个地区没有任何那种颜色的（卡车）。

None at all, save at 除了；除了…之外 one dealer.

[.my2]
根本没有，除了一家经销商。

You know how they tell you not to shop for groceries 购买杂货；买菜 when you're hungry? Well, I was hungry.

[.my2]
你知道他们怎么告诉你饿着的时候不要去买菜吗？嗯，我当时很“饿”。

Very hungry.

[.my2]
非常“饿”。

Actually, I was in love.

[.my2]
实际上，我是迷恋上了。

I sat down, centered myself 集中注意力；保持冷静, and strategized 制定战略；谋划。

[.my2]
我坐下来，集中注意力，制定了战略。

This lot 交易；这批货 was my only shot 唯一的机会；唯一的希望。

[.my2]
这一批货是我唯一的机会。

I had to make it count 产生价值；很重要。

[.my2]
我必须让它有价值。

I drove to the dealer on a sunny Friday afternoon.

[.my2]
我在一个阳光明媚的周五下午开车去了经销商那里。

I sat down across from 坐在对面；面对面 the salesman, a nice enough guy named Stan, and told him how gorgeous 华丽的；极好的 the vehicle 车辆；机动车 was.

[.my2]
我坐在销售员（一个名叫斯坦的不错的人）对面，告诉他这辆车有多华丽。

He offered me the usual smile.

[.my2]
他给了我通常的微笑。

He had me, he thought, and mentioned the sticker price 标价；建议零售价 on that beautiful vehicle, $36,000$.

[.my2]
他认为他已经抓住了我，并提到了那辆漂亮车辆的标价，$36,000$ 美元。

I gave him an understanding nod 理解地；赞同地点头 and pursed my lips 噘嘴；抿紧嘴唇。

[.my2]
我理解地点了点头，抿紧了嘴唇。

The key to beginning a haggle 讨价还价；争论 is to rattle 使紧张；使不安 the other guy ever so gently 极其温和地；非常轻柔地。

[.my2]
开始讨价还价的关键是极其温和地使对方不安。

You do it in the nicest way possible.

[.my2]
你以最友好的方式去做。

If I could thread that needle 穿针引线；顺利解决, I had a good chance at 很好的机会；很大希望 getting my price.

[.my2]
如果我能顺利解决这个难题，我就有很大希望得到我的价格。

I can pay $30,000$, I said, and I can pay it upfront 预先；提前, all cash 现金；全款。

[.my2]
“我可以支付 $30,000$ 美元，”我说，“我可以预先全款支付。

I'll write a check today for the full amount.

[.my2]
我今天就会写一张全额支票。

I'm sorry.

[.my2]
对不起。

I'm afraid I just can't pay anymore.” His smile flickered 闪烁；忽隐忽现 a little bit at the edges 边缘；边角, as if it were losing focus 失去焦点；走神, but he tightened it down 绷紧；收紧 and shook his head 摇头；拒绝。

[.my2]
恐怕我不能再付更多了。”他的笑容在边缘稍微闪烁了一下，仿佛失去了焦点，但他绷紧了笑容，摇了摇头。

I'm sure you can understand we can't do that.

[.my2]
“我确信你能理解我们不能那么做。

The sticker price is $36,000$ after all 毕竟；终究。

[.my2]
毕竟，标价是 $36,000$ 美元。”

How am I supposed to do that? I asked differentially 恭敬地；尊重地。

[.my2]
“我该怎么做到呢？”我恭敬地问。

I'm sure, he said, then paused 停顿；间歇 as if he wasn't sure what he'd meant to say.

[.my2]
“我确信，”他说，然后停顿了一下，仿佛不确定他本来想说什么。

I'm sure we can figure something out 解决；想出办法 with financing 融资；筹资 the $36,000$.

[.my2]
“我确信我们可以想出一些融资 $36,000$ 美元的办法。

It's a beautiful truck.

[.my2]
这是一辆漂亮的卡车。

Really amazing 令人惊叹的；了不起的.

[.my2]
真的令人惊叹。”

I can't tell you how much I'd love to have it.

[.my2]
“我无法告诉你我多想拥有它。

It's worth more than what I'm offering.

[.my2]
它比我的报价更值钱。

I'm sorry.

[.my2]
对不起。

This is really embarrassing 尴尬的；令人难为情的.

[.my2]
这真的很尴尬。

I just can't do that price.” He stared at 盯着；凝视 me in silence 沉默；无言, a little befuddled 困惑的；糊涂的 now.

[.my2]
我就是不能接受那个价格。”他沉默地盯着我，现在有点困惑。

Then he stood and went into the back for what seemed like an eternity 永恒；很久。

[.my2]
然后他站起来走到后面，时间之久仿佛过了一个永恒。

He was gone so long that I remember saying to myself, "Damn, I should have come in lower.

[.my2]
他离开得太久了，我记得自己对自己说：“该死，我应该出价更低的。

They're going to come all the way down.” Any response 反应；回应 that's not an outright rejection 彻底拒绝；完全拒绝 of your offer means you have the edge 优势；上风。

[.my2]
他们会一直降价的。”任何不是彻底拒绝你的报价的反应都意味着你占有优势。

He returned and told me like it was Christmas 像过圣诞节一样；高兴地 that his boss had okayed 同意；批准 a new price, $34,000$.

[.my2]
他回来了，像过圣诞节一样高兴地告诉我，他的老板已经同意了一个新的价格，$34,000$ 美元。

"Wow, your offer is very generous and this is the car of my dreams 梦想中的车；理想汽车,” I said.

[.my2]
“哇，你的报价非常慷慨，这是我梦想中的车，”我说。

"I really wish I could do that.

[.my2]
“我真的希望我能接受。

I really do.

[.my2]
我真的很想。

This is so embarrassing." "I simply 简直；简直是 can't." He dropped into silence, and I didn't take the bait 上钩；中计。

[.my2]
这太尴尬了。”“我简直不能。”他陷入了沉默，我没有上钩。

I let the silence linger 持续；逗留 and then with a sigh 叹息；叹气 he trudged off 缓慢地走开；艰难地走开 again.

[.my2]
我让沉默持续，然后他叹了口气，又缓慢地走开了。

He returned after another eternity.

[.my2]
他又过了仿佛一个永恒才回来。

You win, he said.

[.my2]
“你赢了，”他说。

My manager oayed $32,500$.

[.my2]
我的经理同意了 $32,500$ 美元。

He pushed a paper across the desk that even said you win in big letters.

[.my2]
他把一张纸推过桌子，上面甚至用大写字母写着“你赢了”。

The words were even surrounded with smiley faces 笑脸；笑脸符号。

[.my2]
这些词甚至被笑脸包围着。

I am so grateful 感激的；感谢的.

[.my2]
“我非常感激。

You've been very generous and I can't thank you enough 非常感谢；感激不尽.

[.my2]
你一直非常慷慨，我感激不尽。

The truck is no doubt 毫无疑问；肯定 worth more than my price, I said.

[.my2]
毫无疑问，这辆卡车比我的价格更值钱，”我说。

I'm sorry.

[.my2]
对不起。

I just can't do that.” Up he stood again.

[.my2]
我就是不能接受。”他又站了起来。

No smile now, still befuddled.

[.my2]
现在没有了笑容，仍然很困惑。

After a few seconds, he walked back to his manager and I leaned back 往后靠；放松。

[.my2]
几秒钟后，他走回了他的经理那里，我往后靠着。

I could taste victory 尝到胜利的滋味；感受到胜利。

[.my2]
我能感受到胜利。

A minute later, no eternity this time, he returned and sat.

[.my2]
一分钟后，这次没有等一个永恒，他回来坐下了。

We can do that, he said.

[.my2]
“我们可以做到，”他说。

Two days later, I drove off in my Salsa Red Pearl Toyota 4Erunner for $30,000$.

[.my2]
两天后，我以 $30,000$ 美元开着我的莎莎红珍珠色丰田 4Runner 离开了。

God, I love that truck.

[.my2]
天啊，我爱那辆卡车。

Still drive it today.

[.my2]
今天仍然在开它。

Most negotiations hit that inevitable 不可避免的；必然发生的 point where the slightly loose 宽松的；不严格的 and informal 非正式的；不拘礼节的 interplay 相互作用；相互影响 between two people turns to confrontation 对抗；冲突 and the proverbial 谚语的；众所周知的 brass tax 实际问题；实质性问题。

[.my2]
大多数谈判都会遇到不可避免的那一点，两个人之间略显宽松和非正式的相互作用转向对抗和众所周知的实质性问题。

You know the moment.

[.my2]
你知道这个时刻。

You've mirrored and labeled your way to a degree of rapport 融洽关系；友好关系。

[.my2]
你已经通过镜像和标签建立了一定程度的融洽关系。

An accusation audit has cleared 消除；清除 any lingering 持续的；挥之不去的 mental or emotional obstacles 情感障碍；精神障碍, and you've identified 识别；确定 and summarized 总结；概括 the interests and positions at stake 处于危险之中；利害攸关, eliciting 引起；诱发 a that's right, and now it's time to bargain.

[.my2]
一份指控审计已经消除了任何挥之不去的精神或情感障碍，你已经识别并总结了利害攸关的利益和立场，引起了一个“对”，现在是时候讨价还价了。

Here it is, the clash for cash 现金冲突；金钱争夺, an uneasy 令人不安的；不舒服的 dance of offers and counters that send most people into a cold sweat 出冷汗；感到不安。

[.my2]
就是它了，金钱争夺，一个令人不安的报价和还价的舞蹈，让大多数人感到不安。

If you count yourself among 认为自己是…；属于 that majority 多数；大部分, regarding 认为；视作 the inevitable moment as nothing more than 仅仅是；只不过是 a necessary evil 不得不做的坏事；必要的恶, there's a good chance 很大可能；很有可能 you regularly get your clock cleaned 被击败；被打败 by those who have learned to embrace 接受；拥抱 it.

[.my2]
如果你认为自己属于多数，将这个不可避免的时刻仅仅视为不得不做的坏事，你很有可能经常被那些学会接受它的人击败。

No part of a negotiation induces 引起；导致 more anxiety 焦虑；不安 and unfocused aggression 不集中的攻击性；分散的侵略性 than bargaining, which is why it's the part that is more often fumbled 搞砸；笨手笨脚地处理 and mishandled 处理不当；弄错 than any other.

[.my2]
谈判的任何部分都没有比讨价还价引起更多焦虑和分散的攻击性，这就是为什么它比任何其他部分更经常被搞砸和处理不当。

It's simply not a comfortable dynamic 舒适的动态；舒服的机制 for most people.

[.my2]
对大多数人来说，它根本不是一个舒服的机制。

Even when we have the best laid plans 制定得最好的计划；精心设计的方案, a lot of us wimp out 胆怯；退缩 when we get to the moment of exchanging prices 交换价格；互相报价。

[.my2]
即使我们有精心设计的方案，当我们到达互相报价的时刻，我们很多人会退缩。

In this chapter, I'm going to explain the tactics 策略；手段；招数 that make up 构成；组成 the bargaining process 谈判过程；议价过程 and look at how psychological dynamics 心理动态；心理机制 determine 决定；确定 which tactics should be used and how they should be implemented 实施；执行。

[.my2]
在本章中，我将解释构成谈判过程的策略，并探讨心理机制如何决定应该使用哪些策略以及如何实施它们。

Now, bargaining is not rocket science 复杂的学问；高深莫测的事, but it's not simple intuition 直觉；预感 or mathematics 数学；计算 either.

[.my2]
现在，讨价还价不是什么复杂的学问，但它也不是简单的直觉或数学。

To bargain well, you need to shed 摆脱；去除 your assumptions 假设；设想 about the haggling process 讨价还价的过程；议价过程 and learn to recognize 识别；认识 the subtle psychological strategies 心理策略；心理战术 that play vital roles 扮演重要角色；起关键作用 at the bargaining table 谈判桌；议价桌。

[.my2]
为了很好地讨价还价，你需要摆脱你对议价过程的假设，并学会识别在谈判桌上扮演关键角色的微妙心理策略。

Skilled bargainers 熟练的谈判者；议价高手 see more than just opening offers 开价；最初的报价, counter offers 反报价；还价, and closing moves 结束的动作；最终的行动。

[.my2]
熟练的谈判者看到的不只是开价、反报价和结束的行动。

They see the psychological currents 心理潮流；心理趋势 that run below the surface 在表面之下运行；隐藏在深处。

[.my2]
他们看到隐藏在深处的心理趋势。

Once you've learned to identify these currents, you'll be able to read bargaining situations more accurately 准确地；精确地 and confidently 自信地；有信心地。

[.my2]
一旦你学会识别这些趋势，你将能够更准确、更自信地解读讨价还价的情况。

Answer the tactical questions 战术问题；策略问题 that dog 困扰；使苦恼 even the best negotiators.

[.my2]
回答困扰即使是最好的谈判者的战术问题。

You'll be ready for the bare knuckle 徒手的；赤手空拳的 bargaining and they'll never see it coming 没想到；意想不到。

[.my2]
你将为赤手空拳的讨价还价做好准备，而他们将意想不到。

What type are you? A few years ago, I was on my boat with one of my employees 员工；雇员, a great guy named Kenan.

[.my2]
你是什么类型？几年前，我和我的一个员工（一个叫基南的很棒的人）在我的船上。

I was supposed to be giving him a pep talk 鼓舞士气的谈话；打气 and performance review 绩效评估；业绩考核。

[.my2]
我本应给他打气和进行绩效评估。

When I think of what we do, I describe it as uncovering the riptide 离岸流；回流。

[.my2]
当我想到我们所做的事情时，我将其描述为揭示离岸流。

I said, "Uncovering the riptide." Kenan said, "Yes, the idea is that we, you and I, and everyone here have the skills to identify the psychological forces 心理力量；心理作用 that are pulling us away from 让我们远离；拉开距离 shore 岸边；海岸 and use them to get somewhere more productive 更有成效的；更有效率的." "Somewhere more productive," Kenan said.

[.my2]
我说：“揭示离岸流。”基南说：“是的，这个想法是我们，你和我，以及这里的每个人都有识别将我们拉离岸边的心理力量，并利用它们到达更有成效的地方的技能。”“更有成效的地方，”基南说。

"Exactly," I said.

[.my2]
“没错，”我说。

"To a place where we can." We had talked for about $45$ minutes when my son Brandon, who runs operations 运营；运作 for the Black Swan Group, broke out laughing 突然大笑；爆发大笑。

[.my2]
“到一个我们可以（实现价值）的地方。”我们谈了大约 45 分钟，这时我的儿子布兰登（他负责黑天鹅集团的运营）突然大笑起来。

I can't take it anymore 无法忍受；受不了。

[.my2]
“我受不了了。

Don't you see? Really, Dad? Don't you see? I blinked 眨眼；闪烁。

[.my2]
你难道没看到吗？真的吗，爸爸？你难道没看到吗？”我眨了眨眼。

Did I see what? I asked him.

[.my2]
“我看到了什么？”我问他。

All Keenan is doing is mirroring you, and he's been doing it for almost an hour.

[.my2]
“基南所做的只是在镜像你，他已经做了将近一个小时了。”

Oh, I said, my face going red as Kenan began to laugh.

[.my2]
“哦，”我说，我的脸红了，基南开始大笑。

He was totally right 完全正确；说得没错。

[.my2]
他完全正确。

Kenan had been playing with me 玩弄；戏弄 the entire time, using the psychological tool 心理工具；心理手段 that works most effectively 最有效地；最管用地 with assertive 坚定的；自信的 guys like me, the mirror.

[.my2]
基南一直在戏弄我，使用对像我这样坚定的人最有效地心理工具——镜像。

Your personal negotiation style 个人谈判风格；个人协商风格 and that of your counterpart is formed through childhood 童年；孩童时期, schooling 学校教育；求学经历, family 家庭；家人, culture 文化；文明, and a million other factors 因素；要素。

[.my2]
你的个人谈判风格以及你的对手的风格是通过童年、学校教育、家庭、文化和一百万个其他因素形成的。

By recognizing 识别；认出 it, you can identify 确定；发现 your negotiating strengths 谈判优势；协商强项 and weaknesses 弱点；劣势 and those of your counterpart and adjust 调整；适应 your mindset 心态；思维模式 and strategies accordingly 相应地；依此。

[.my2]
通过识别它，你可以确定你的谈判优势和劣势，以及你对手的优势和劣势，并相应地调整你的心态和策略。

Negotiation style is a crucial variable 关键变量；重要因素 in bargaining.

[.my2]
谈判风格是讨价还价中一个关键变量。

If you don't know what instinct 本能；直觉 will tell you or the other side to do in various circumstances 各种情况；不同情形, you'll have massive trouble 巨大的麻烦；很大的困难 gaming out 制定策略；设计策略 effective strategies and tactics.

[.my2]
如果你不知道在各种情况下本能会告诉你或对方做什么，你在制定有效策略和战术时将有很大困难。

You and your counterpart have habits of mind 思维习惯；心智习性和 behavior 行为；举止。

[.my2]
你和你的对手有思维习惯和行为。

And once you identify them, you can leverage 利用；借用 them in a strategic manner 战略方式；策略性地, just like Kenan did.

[.my2]
一旦你识别它们，你就可以以战略方式利用它们，就像基南所做的那样。

There's an entire library unto itself 独立完整的图书馆；浩如烟海 of research into the archetypes 原型；典型 and behavioral profiles 行为特征；行为模式 of all the possible people you're bound to meet 必然遇到；注定遇见 at the negotiating table.

[.my2]
关于你必然在谈判桌上遇到的所有可能的人的原型和行为特征的研究浩如烟海。

It's flatout 彻底地；完全地 overwhelming 压倒性的；难以承受的.

[.my2]
它彻底是压倒性的。

So much so that it loses its utility 用处；效用。

[.my2]
以至于它失去了它的效用。

Over the last few years, in an effort primarily led by 主要由…领导；主要归功于 my son Brandon, we've consolidated 巩固；整合 and simplified 简化；使简单 all that research, cross-referencing 交叉参考；比对 it with our experiences in the field 领域；实战 and the case studies 案例研究；个案研究 of our business school students and found that people fall into 属于；分成 three broad categories 广泛的类别；大类。

[.my2]
在过去的几年里，主要归功于我儿子布兰登的努力，我们整合并简化了所有这些研究，将其与我们在实战中的经验和我们商学院学生的案例研究进行比对，发现人们属于三个大类。

Some people are accommodators 迁就者；随和的人, others, like me are basically assertive 坚定的；自信的 and the rest are data loving analysts 分析师；分析家。

[.my2]
有些人是迁就者，其他的，像我这样的基本上是坚定的，其余的是热爱数据的分析师。

Hollywood negotiation scenes suggest 建议；表明 that an assertive style is required for effective bargaining, but each of the styles can be effective.

[.my2]
好莱坞谈判场景表明坚定的风格是有效讨价还价所必需的，但每种风格都可以是有效的。

And to truly be effective, you need elements 元素；要素 from all three.

[.my2]
而要真正有效，你需要来自所有三种风格的元素。

A study of American lawyer negotiators, one found that $65\%$ of attorneys 律师；检察官 from two major US cities used a cooperative 合作的；协作的 style while only $24\%$ were truly assertive.

[.my2]
一项对美国律师谈判者的研究发现，来自美国两个主要城市的 $65\%$ 的律师使用合作的风格，而只有$24\%$是真正坚定的。

And when these lawyers were graded for effectiveness 评估有效性；评定效力, more than $75\%$ of the effective group came from the cooperative type 合作型；协作型。

[.my2]
当这些律师被评估其有效性时，超过$75\%$的有效群体来自合作型。

Only $12\%$ were assertive.

[.my2]
只有$12\%$是坚定的。

So if you're not assertive, don't despair 绝望；灰心。

[.my2]
所以如果你不坚定，不要灰心。

Blunt 钝的；直言不讳的 assertion 断言；坚持己见 is actually counterproductive 适得其反的；产生反效果的 most of the time.

[.my2]
直言不讳的坚持己见实际上大部分时间是适得其反的。

And remember, your personal negotiating style is not a straight jacket 约束；束缚。

[.my2]
并记住，你的个人谈判风格不是一种束缚。

No one is exclusively 独有地；排他地 one style.

[.my2]
没有人是独有一种风格的。

Most of us have the capacity 能力；才能 to throttle up 加速；提高 our non-dominant styles 非主导风格；非主要风格 should the situation call for it 需要；要求。

[.my2]
我们大多数人都有能力在情况需要时提高我们的非主导风格。

But there is one basic truth 基本事实；基本真理 about a successful bargaining style.

[.my2]
但关于成功讨价还价风格有一个基本事实。

To be good, you have to learn to be yourself at the bargaining table.

[.my2]
要想做得好，你必须学会在谈判桌上做自己。

To be great, you have to add to 增加；增添 your strengths, not replace 取代；替换 them.

[.my2]
要想做得好，你必须学会在谈判桌上做自己。要想做得更好，你必须增加你的优势，而不是取代它们。

Here's a quick guide 快速指南；简要指导 to classifying 分类；归类 the type of negotiator you're facing and the tactics that will be most fitting 适合的；恰当的 for you.

[.my2]
这里有一个快速指南来分类你正面对的谈判者的类型，以及最适合你的策略。

analyst 分析师；分析家。

[.my2]
分析师。

Analysts 分析师；分析家 are methodical 有条不紊的；系统化的 and diligent 勤奋的；刻苦的。

[.my2]
分析师做事有条不紊且勤奋。

They are not in a big rush 匆忙；赶时间。

[.my2]
他们并不匆忙。

Instead, they believe that as long as they are working toward 努力实现；致力于 the best result in a thorough 彻底的；详尽的 and systematic 系统的；有条理的 way, time is of little consequence 不重要；影响不大。

[.my2]
相反，他们相信只要他们正以彻底和系统化的方式努力实现最佳结果，时间就不重要。

Their self-image 自我形象；自我认知 is linked to 与...相关联；与...挂钩 minimizing 最小化；尽量减少 mistakes 错误；失误。

[.my2]
他们的自我形象与尽量减少错误相关联。

Their motto 座右铭；格言, as much time as it takes to get it right 做到正确所需的时间；花足够的时间把事情做对。

[.my2]
他们的座右铭是：花足够的时间把事情做对。

Classic analysts prefer to work on their own 独自工作；单干 and rarely deviate from 偏离；背离 their goals 目标；目的。

[.my2]
典型的分析师喜欢独自工作，很少偏离他们的目标。

They rarely show emotion 表现情感；流露情绪 and they often use what is very close to the FM DJ voice 电台DJ声音；调频电台主持人的声音 I talked about in chapter 3, slow and measured 缓慢而有分寸的；沉稳的 with a downward inflection 语调下降；降调。

[.my2]
他们很少流露情绪，他们经常使用非常接近我在第 3 章中谈到的调频电台主持人的声音，缓慢而有分寸地带着降调。

However, analysts often speak in a way that is distant 疏远的；冷漠的 and cold 冰冷的；冷淡的 instead of soothing 抚慰人心的；使人平静的。

[.my2]
然而，分析师说话的方式通常是疏远的和冷淡的，而不是抚慰人心的。

This puts people off 使人反感；使人厌恶 without them knowing it and actually limits 限制；局限 them from putting their counterpart at ease 使…放松；使…自在 and opening them up 使…开放；使…畅所欲言。

[.my2]
这在他们不知不觉中使人反感，实际上限制了他们让他们的对手放松并畅所欲言。

Analysts pride themselves on 以...为荣；引以为傲 not missing any details 遗漏任何细节；错过任何细节 in their extensive 广泛的；大量的 preparation 准备；预备。

[.my2]
分析师以他们在他们广泛的准备中不遗漏任何细节为荣。

They will research for two weeks to get data they might have gotten in 15 minutes at the negotiating table just to keep from being surprised 避免被惊讶；避免意外。

[.my2]
他们会研究两周以获取他们可能在谈判桌上 15 分钟内就已获得的数据，只是为了避免意外。

Analysts hate surprises 讨厌意外；不喜欢突发事件。

[.my2]
分析师讨厌意外。

They are reserved 矜持的；内敛的 problem solvers 问题解决者；解决问题的人 and information aggregators 信息聚合者；信息收集者 and are hyper sensitive to 对…高度敏感 reciprocity 互惠；对等。

[.my2]
他们是内敛的问题解决者和信息聚合者，并对互惠高度敏感。

They will give you a piece 一部分信息；一点东西, but if they don't get a piece in return 回报；回馈 within a certain period of time 一定时期内；某个时间段内, they lose trust 失去信任；不再信任 and will disengage 脱离；退出。

[.my2]
他们会给你一部分（信息/东西），但如果他们在一定时期内没有得到回报，他们就会失去信任并会退出。

This can often seem to come out of nowhere 凭空出现；突然发生。

[.my2]
这通常似乎是凭空出现的。

But remember, since they like working on things alone, the fact that they are talking to you at all 从根本上说；压根儿 the fact that they are talking to you at all is from their perspective 观点；角度 a concession 让步；妥协。

[.my2]
但请记住，既然他们喜欢独自做事情，他们压根儿与你交谈这一事实，从他们的角度来看，就是一种让步。

They will often view concessions by their counterpart as a new piece of information to be taken back 带回；拿回去 and evaluated 评估；评价。

[.my2]
他们通常会将对手的让步视为一个新的信息，需要带回去评估。

Don't expect immediate counterproposals 立即的反建议；立刻的还价 from them.

[.my2]
不要期望他们会立即给出反建议。

People like this are skeptical 怀疑的；多疑的 by nature 本性上；本质上。

[.my2]
这样的人本质上是多疑的。

So asking too many questions to start is a bad idea because they're not going to want to answer until they understand all the implications 含义；影响。

[.my2]
所以一开始问太多问题是个坏主意，因为在他们理解所有的含义之前，他们不会想回答。

With them, it's vital to be prepared 至关重要；极其重要。

[.my2]
与他们打交道，做好准备至关重要。

Use clear data to drive your reason 支撑你的论点；驱动你的推理。

[.my2]
使用清晰的数据来支撑你的论点。

Don't add lib 即兴发挥；随意添加。

[.my2]
不要即兴发挥。

Use data comparisons 数据比较；数据对比 to disagree and focus on the facts.

[.my2]
使用数据比较来表达不同意见，并关注事实。

Warn them of issues early and avoid surprises.

[.my2]
尽早警告他们问题，并避免意外。

Silence to them is an opportunity 机会；时机 to think.

[.my2]
对他们而言，沉默是思考的机会。

They're not mad at you 生气；发火 and they're not trying to give you a chance to talk more.

[.my2]
他们没有对你生气，他们也不是在试图给你一个多说话的机会。

If you feel they don't see things the way you do, give them a chance to think first.

[.my2]
如果你觉得他们看待事物的方式与你不同，先给他们一个思考的机会。

Apologies 道歉；歉意 have little value 几乎没有价值；作用不大 to them since they see the negotiation and their relationship with you as a person largely as separate things 分开的事物；独立的事情。

[.my2]
道歉对他们来说几乎没有价值，因为他们很大程度上将谈判和他们与你作为一个人的关系视为分开的事物。

They respond fairly well 反应良好；回应得很好 in the moment 立即；当下 to labels 标签；标记。

[.my2]
他们对标签立即反应良好。

They are not quick to answer calibrated questions 经过校准的问题；精确设计的问题 or closedended questions 封闭式问题；非开放性问题 when the answer is yes.

[.my2]
当答案是“是”时，他们不急于回答经过校准的问题或封闭式问题。

They may need a few days to respond.

[.my2]
他们可能需要几天来回应。

If you're an analyst, you should be worried about cutting yourself off from 切断；使自己孤立于 an essential source of data 必不可少的数据来源；重要的数据源, your counterpart.

[.my2]
如果你是一个分析师，你应该担心切断自己与一个必不可少的数据来源，你的对手。

The single biggest thing 你能做的最重要的一件事；最重要的一点 you can do is to smile when you speak.

[.my2]
你能做的最重要的一点就是说话时微笑。

People will be more forthcoming 乐于提供信息；更愿意合作 with information to you as a result.

[.my2]
因此，人们会更乐于提供信息给你。

Smiling can also become a habit that makes it easy for you to mask 掩饰；隐藏 any moments you've been caught off guard 措手不及；毫无防备。

[.my2]
微笑也可以成为一种习惯，使你更容易掩饰任何你措手不及的时刻。

Accommodator 迁就者；随和的人。

[.my2]
迁就者。

The most important thing to this type of negotiator 谈判者；协商者 is the time spent building the relationship 建立关系；培养交情。

[.my2]
对这种谈判者来说最重要的事情是花在建立关系上的时间。

Accommodators think as long as there is a free flowing continuous exchange 持续交流；不间断交换 of information, time is being well spent 花费得很好；值得。

[.my2]
迁就者认为只要有持续的信息交流，时间就是值得的。

As long as they're communicating, they're happy.

[.my2]
只要他们在沟通，他们就高兴。

Their goal is to be on great terms with 关系极好；保持良好关系 their counterpart.

[.my2]
他们的目标是与他们的对手保持良好关系。

They love the win-win 双赢；互利。

[.my2]
他们喜欢双赢。

Of the three types, they are most likely to build great rapport 建立极好的关系；形成很好的默契 without actually accomplishing anything 真正完成任何事情；取得任何成就。

[.my2]
在这三种类型中，他们最有可能在没有真正完成任何事情的情况下建立极好的关系。

Accommodators want to remain friends with their counterpart even if they can't reach an agreement 达成协议；取得一致。

[.my2]
迁就者想与他们的对手保持朋友关系，即使他们不能达成协议。

They are very easy to talk to 很容易交谈；很好说话, extremely friendly 极其友好；非常友善, and have pleasant voices 悦耳的声音；好听的声音。

[.my2]
他们很容易交谈，极其友好，并有悦耳的声音。

They will yield a concession 做出让步；妥协 to appease 安抚；抚慰 or acquies 默认；默许 and hope the other side reciprocates 报答；回报。

[.my2]
他们会做出让步来安抚或默认，并希望对方会回报。

If your counterparts are sociable 好交际的；合群的, peace-seeking 寻求和平的；爱好和平的, optimistic 乐观的；乐天的, distractable 易分心的；注意力不集中 and poor time managers 时间管理差；不善于管理时间, they're probably accommodators.

[.my2]
如果你的对手是好交际、寻求和平、乐观、易分心和不善于管理时间的，他们可能是迁就者。

If they're your counterpart, be sociable and friendly.

[.my2]
如果他们是你的对手，要好交际和友好。

Listen to them talk about their ideas and use calibrated questions focused specifically on implementation 实施；执行 to nudge them along 推动他们；促使他们 and find ways to translate 转化；转换 their talk into action.

[.my2]
听他们谈论他们的想法，并使用专门针对实施的经过校准的问题来推动他们，并找到将他们的谈话转化为行动的方法。

Due to their tendency 倾向；趋势 to be the first to activate 激活；启动 the reciprocity cycle 互惠循环；互惠周期, they may have agreed to give you something they can't actually deliver 交付；实现。

[.my2]
由于他们倾向于第一个启动互惠循环，他们可能已经同意给你一些他们实际上无法实现的东西。

Their approach to preparation 方法；途径 can be lacking 缺乏；不足 as they are much more focused on the person behind the table 幕后的人；决策者。

[.my2]
他们对准备的方法可能有所缺乏，因为他们更关注幕后的人。

They want to get to know you 了解你；认识你。

[.my2]
他们想了解你。

They have a tremendous passion 巨大的热情；极大的热忱 for the spirit 精神；主旨 of negotiation and what it takes not only to manage emotions 管理情绪；控制情感 but also to satisfy 满足；使满意 them.

[.my2]
他们对谈判的精神以及不仅管理情绪而且满足它们所需的一切有着巨大的热情。

While it is very easy to disagree with 很容易不同意；很容易反驳 an accommodator because they want nothing more than 极其渴望；非常想 to hear what you have to say, uncovering their objections 反对意见；异议 can be difficult.

[.my2]
虽然很容易反驳迁就者，因为他们极其渴望听到你要说的话，但揭示他们的反对意见可能很困难。

They will have identified potential problem areas 潜在问题领域；可能出现问题的方面 beforehand 事先；预先 and will leave those areas unressed 未被处理；未被解决 out of fear of the conflict 冲突；矛盾 they may cause.

[.my2]
他们会事先确定潜在的问题领域，并会出于对他们可能引起的冲突的恐惧而不解决这些领域。

If you have identified yourself as an accommodator, stick to 坚持；紧抓不放 your ability to be very likable 招人喜欢；讨人喜欢, but do not sacrifice 牺牲；舍弃 your objections.

[.my2]
如果你确定自己是一个迁就者，坚持你招人喜欢的能力，但不要牺牲你的反对意见。

Not only do the other two types need to hear your point of view 观点；看法, if you are dealing with another accommodator, they will welcome 欢迎；乐于接受 it.

[.my2]
其他两种类型不仅需要听到你的观点，如果你正与另一个迁就者打交道，他们会欢迎它。

Also, be conscious of 意识到；留意 excess chitchat 闲聊；废话。

[.my2]
另外，要意识到多余的闲聊。

The other two types have no use for 对…没有用处；不需要 it.

[.my2]
其他两种类型不需要它。

And if you're sitting across the table from 坐在…对面；面对面 someone like yourself, you will be prone to interactions 容易进行互动；倾向于互动 where nothing gets done 没有任何进展；一事无成。

[.my2]
如果你正坐在与你自己相似的人对面，你将倾向于进行没有任何进展的互动。

Assertive 坚定的；自信的。

[.my2]
坚定型。

The assertive type believes time is money 时间就是金钱；时间宝贵。

[.my2]
坚定型相信时间就是金钱。

Every wasted minute 浪费的每一分钟；虚度的每一分钟 is a wasted dollar 浪费的每一美元；损失的每一元钱。

[.my2]
浪费的每一分钟就是损失的每一元钱。

Their self-image is linked to how many things they can get accomplished 完成；实现 in a period of time 一段时间内；一段时期内。

[.my2]
他们的自我形象与他们在一段时间内可以完成多少事情相关联。

For them, getting the solution perfect isn't as important as getting it done.

[.my2]
对他们而言，让解决方案完美不如完成它重要。

Assertives are fiery 激烈的；火热的 people who love winning above all else 最重要的是；高于一切, often at the expense of others 以牺牲他人为代价；损害他人利益。

[.my2]
坚定型是激烈的人，他们热爱胜利高于一切，通常以牺牲他人为代价。

Their colleagues 同事；同僚 and counterparts never question where they stand 质疑他们的立场；怀疑他们的态度 because they are always direct and candid 坦诚的；直率的。

[.my2]
他们的同事和对手从不质疑他们的立场，因为他们总是直接而坦诚的。

They have an aggressive 咄咄逼人的；有攻击性的 communication style 沟通方式；交流风格 and they don't worry about future interactions 未来互动；以后的接触。

[.my2]
他们有一个咄咄逼人的沟通方式，他们不担心未来的互动。

Their view of business relationships 商业关系；业务关系 is based on respect 尊重；敬重, nothing more and nothing less 仅此而已；不多不少。

[.my2]
他们对商业关系的看法基于尊重，仅此而已。

Most of all, the assertive wants to be heard 被倾听；被听见。

[.my2]
最重要的是，坚定型想被倾听。

And not only do they want to be heard, but they don't actually have the ability to listen 倾听；听取意见 to you until they know that you've heard them.

[.my2]
他们不仅想被倾听，而且在他们知道你已经听到了他们之前，他们实际上没有能力倾听你。

They focus on their own goals rather than people, and they tell rather than ask.

[.my2]
他们关注自己的目标而不是人，他们是告知而不是询问。

When you're dealing with assertive types, it's best to focus on what they have to say.

[.my2]
当你与坚定型打交道时，最好关注他们要说的话。

Because once they are convinced 相信；确信 you understand them, then and only then 只有在那时；唯有如此 will they listen for your point of view.

[.my2]
因为一旦他们确信你理解他们，只有在那时，他们才会听取你的观点。

To an assertive, every silence is an opportunity to speak more.

[.my2]
对坚定型而言，每一次沉默都是多说话的机会。

Mirrors are a wonderful tool 极好的工具；很棒的手段 with this type.

[.my2]
镜像是对付这种类型的极好的工具。

So are calibrated questions, labels, and summaries.

[.my2]
经过校准的问题、标签和总结也是如此。

The most important thing to get from an assertive will be a that's right that may come in the form of 采取…形式；表现为 that's it exactly or you hit it on the head 猜中；说中要害。

[.my2]
从坚定型那里获得最重要的事情将是一个“对”，它可能表现为“完全正确”或“你说中要害了”。

When it comes to reciprocity, this type is of the give an inch take a mile 贪得无厌；得寸进尺 mentality 思想；心态。

[.my2]
当谈到互惠时，这种类型具有贪得无厌的心态。

They will have figured 认为；估计 they deserve 值得；应得 whatever you have given them.

[.my2]
他们会认为他们值得你给他们的任何东西。

So they will be oblivious to 没注意到；没意识到 expectations 期望；预期 of owing something in return 欠回报；应该回报。

[.my2]
所以他们会没注意到应该回报的预期。

They will actually simply be looking for the opportunity to receive more.

[.my2]
他们实际上只是在寻找接收更多东西的机会。

If they have given some kind of concession, they are surely counting the seconds 数秒；焦急地等待 until they get something in return.

[.my2]
如果他们做了某种让步，他们肯定在焦急地等待直到得到回报。

If you are an assertive, be particularly conscious of 尤其留意；特别注意 your tone 语气；语调。

[.my2]
如果你是一个坚定型，要尤其留意你的语气。

You will not intend to be overly harsh 过于苛刻；过于严厉, but you will often come off that way 给人留下那种印象；显得如此。

[.my2]
你可能不想过于苛刻，但你经常会显得如此。

Intentionally 故意地；有意识地 soften 软化；缓和 your tone and work to make it more pleasant 令人愉快的；友好的。

[.my2]
有意识地缓和你的语气，并努力使它更友好。

Use calibrated questions and labels with your counterpart since that will also make you more approachable 容易接近的；平易近人的 and increase the chances for collaboration 合作；协作。

[.my2]
对你的对手使用经过校准的问题和标签，因为这也会使你更平易近人，并增加合作的机会。

We've seen how each of these groups views the importance of time differently.

[.my2]
我们已经看到这些群体中的每一个如何看待时间的重要性不同。

Time equals preparation 准备；预备。

[.my2]
时间等于准备。

Time equals relationship 关系；交情。

[.my2]
时间等于关系。

Time equals money 金钱；财富。

[.my2]
时间等于金钱。

They also have completely different interpretations 解释；理解 of silence.

[.my2]
他们对沉默也有完全不同的解释。

I'm definitely 肯定；无疑 an assertive.

[.my2]
我肯定是一个坚定型。

And at a conference, this accommodator type told me that he blew up a deal 搞砸了交易；毁掉了一笔交易。

[.my2]
在一个会议上，这个迁就型告诉我他搞砸了一笔交易。

I thought, what did you do? Scream at the other guy and leave? Because that's me blowing up a deal.

[.my2]
我想，你做了什么？对着对方大喊大叫然后离开了吗？因为那是我搞砸一笔交易的方式。

But it turned out that 结果是；原来是 he went silent.

[.my2]
但结果是他变得沉默了。

For an accommodator type, silence is anger 愤怒；生气。

[.my2]
对迁就型而言，沉默就是愤怒。

For analysts though, silence means they want to think.

[.my2]
然而，对分析师而言，沉默意味着他们想思考。

And assertive types interpret 解释；理解 your silence as either you don't have anything to say or you want them to talk.

[.my2]
而坚定型将你的沉默解释为要么你没什么好说的，要么你想让他们说话。

I'm one, so I know the only time I'm silent is when I've run out of things to say 说完所有要说的话；无话可说。

[.my2]
我就是其中之一，所以我知道我唯一沉默的时候就是我无话可说的时候。

The funny thing is when these cross over 交叉；混用, when an analyst pauses to think, their accommodator counterpart gets nervous 紧张的；不安的 and an assertive one starts talking, thereby 从而；因此 annoying 惹恼；使烦躁 the analyst who thinks to herself, "Every time I try to think, you take that as an opportunity to talk some more.

[.my2]
有趣的是当这些风格混用时，当一个分析师停顿思考时，他们的迁就型对手会变得紧张，而一个坚定型的则开始说话，从而惹恼了分析师，她心想：“每一次我尝试思考，你就将其视为一个多说话的机会。

Won't you ever shut up 闭嘴；停止说话?" Before we move on, I want to talk about why people often fail to identify 识别；认出 their counterpart style.

[.my2]
你难道就不会闭嘴吗？”在我们继续之前，我想谈谈为什么人们经常无法识别他们对手的风格。

The greatest obstacle 最大的障碍；主要阻碍 to accurately 准确地；精确地 identifying someone else's style is what I call the I am normal paradox 我是正常的悖论；自认正常矛盾。

[.my2]
准确识别别人的风格最大的障碍是我称之为我是正常的悖论。

That is our hypothesis 假设；推测 that the world should look to others as it looks to us.

[.my2]
那就是我们的假设，世界对别人来说应该就像它对我们来说一样。

After all, who wouldn't make that assumption? But while innocent 无辜的；无害的 and understandable 可理解的；情有可原的, thinking you're normal is one of the most damaging 破坏性的；有害的 assumptions in negotiations.

[.my2]
毕竟，谁不会做出那样的假设呢？但虽然是无害且情有可原的，认为你是正常的是谈判中最具破坏性的假设之一。

With it, we unconsciously 不知不觉地；无意识地 project 投射；预测 our own style on the other side.

[.my2]
有了它，我们不知不觉地将我们自己的风格投射到对方身上。

But with three types of negotiators in the world, there's a $66\%$ chance 机会；可能性 your counterpart has a different style than yours, a different normal.

[.my2]
但世界上有三种类型的谈判者，你的对手有$66\%$的可能性拥有与你不同的风格，一个不同的“正常”。

A CEO 首席执行官；总裁 once told me he expected nine of $10$ negotiations to fail 失败；以失败告终。

[.my2]
一位首席执行官曾告诉我，他预计 10 次谈判中有 9 次会失败。

This CEO was likely projecting his beliefs onto the other side.

[.my2]
这位首席执行官很可能将自己的信念投射到对方身上。

In reality, he probably only matched with 匹配；遇到 someone like-minded 志同道合的；想法一致的 one of $10$ times.

[.my2]
实际上，他可能只有 10 分之 1 的时间与志同道合的人匹配。

If he understood that his counterpart was different from him, he would most surely 肯定；无疑 have increased his success rate 成功率；成功比率。

[.my2]
如果他理解他的对手与他不同，他肯定会提高他的成功率。

From the way they prepare to the way they engage in dialogue 进行对话；参与交流, the three types negotiate differently.

[.my2]
从他们准备的方式到他们进行对话的方式，这三种类型的谈判都不同。

So before you can even think about bargaining effectively, you have to understand your counterparts normal.

[.my2]
所以在你甚至可以考虑有效讨价还价之前，你必须理解你的对手的“正常”。

You have to identify their type by opening yourself to 愿意接受；对自己开放 their difference.

[.my2]
你必须通过愿意接受他们的不同来识别他们的类型。

Because when it comes to negotiating 谈到谈判；说到协商, the golden rule 黄金法则；基本原则 is wrong.

[.my2]
因为谈到谈判，黄金法则是错的。

The black swan rule is don't treat others the way you want to be treated.

[.my2]
黑天鹅法则是：不要以你希望被对待的方式对待别人。

Treat them the way they need to be treated.

[.my2]
以他们需要被对待的方式对待他们。

I've got a complimentary 免费的；赠送的 PDF available that will help you identify your type and that of those around you.

[.my2]
我有一个免费的 PDF 可供使用，它将帮助你识别你的类型以及你周围的人的类型。

Please visit info.blackswanltd.com.

[.my2]
请访问 info.blackswanltd.com。

Three types.

[.my2]
三种类型。

Taking a punch 承受打击；经受考验。

[.my2]
承受打击。

Negotiation.

[.my2]
谈判。

Academics 学者；学术界人士 like to treat bargaining as a rational 理性的；合理的 process devoid of 缺乏；没有 emotion 情感；情绪。

[.my2]
学者喜欢将讨价还价视为一个缺乏情感的理性过程。

They talk about the zopa or zone of possible agreement 可能达成协议的区域；ZOPA, which is where the sellers and buyer zones cross 交叉；重叠。

[.my2]
他们谈论可能达成协议的区域（ZOPA），那是卖方和买方区域重叠的地方。

Say Tony wants to sell his car and won't take less than $5,000$.

[.my2]
假设托尼想卖掉他的车，并且不会接受低于 $5,000$ 美元的价格。

And Samantha wants to buy but won't pay more than $6,000$.

[.my2]
而萨曼莎想买，但不会支付超过 $6,000$ 美元的价格。

The zopa or zone of possible agreement 可能达成协议的区域；ZOPA runs from $5,000$ to $6,000$.

[.my2]
可能达成协议的区域（ZOPA）从 $5,000$ 美元延伸到 $6,000$ 美元。

Some deals 有些交易；有些买卖 have zas and some don't.

[.my2]
有些交易有 ZOPA，有些则没有。

It's all very rational 理性的；合理的.

[.my2]
这一切都非常理性。

Or so they'd have you think.

[.my2]
或者他们想让你这么认为。

You need to disabuse yourself of 消除…的错误想法；使…醒悟 that notion 观念；想法。

[.my2]
你需要消除自己的那个错误想法。

In a real bargaining session 谈判会议；议价过程, kick-ass 厉害的；了不起的 negotiators don't use ZOPA.

[.my2]
在真正的谈判会议中，厉害的谈判者不使用 ZOPA。

Experienced negotiators 经验丰富的谈判者；老练的协商者 often lead with 以…开场；先提出 a ridiculous offer 荒谬的报价；离谱的出价, an extreme anchor 极端锚点；极端的起始价。

[.my2]
经验丰富的谈判者经常以一个荒谬的报价，一个极端锚点开场。

And if you're not prepared to handle 处理；应对 it, you'll lose your moorings 失去立足之地；迷失方向 and immediately go to your maximum 最大限度；最高限度。

[.my2]
如果你没有准备好应对它，你将失去立足之地，并立即达到你的最高限度。

It's human nature 人性；人之常情。

[.my2]
这是人性。

Like the great earbiting 咬耳朵的 pugilist 拳击手；斗士 Mike Tyson once said, "Everybody has a plan until they get punched in the mouth 被打到嘴巴；受到痛击。” As a well-prepared negotiator who seeks information and gathers it relentlessly 不懈地；无情地, you're actually going to want the other guy to name a price first because you want to see his hand 看到他的牌；摸清他的底牌。

[.my2]
就像伟大的咬耳朵拳击手迈克·泰森曾经说的：“每个人都有一个计划直到他们受到痛击。”作为一个准备充分的谈判者，他寻求信息并不懈地收集它，你实际上会希望对方先开价，因为你想摸清他的底牌。

You're going to welcome 欢迎；乐于接受 the extreme anchor.

[.my2]
你会欢迎极端锚点。

But extreme anchoring is powerful and you're human.

[.my2]
但极端锚定是强大的，而你是个人。

Your emotions may well up 涌上心头；强烈爆发。

[.my2]
你的情绪可能会强烈爆发。

If they do, there are ways to weather the storm 渡过难关；经受住考验 without bidding against yourself 与自己竞价；自相残杀 or responding with anger 愤怒地回应；带着怒气回应。

[.my2]
如果是这样，有办法可以渡过难关，而不用自相残杀或带着怒气回应。

Once you learn these tactics 策略；手段；招数, you'll be prepared to withstand 承受；经受 the hit and counter 反击；回击 with panache 神气十足地；充满自信地。

[.my2]
一旦你学会这些策略，你将做好准备承受打击并神气十足地反击。

First, deflect 转移；使转向 the punch in a way that opens up your counterpart.

[.my2]
首先，以一种使你的对手开放的方式转移打击。

Successful negotiators 成功的谈判者；协商高手 often say no in one of the many ways we've talked about, "How am I supposed to accept that?" or deflect the anchor with questions like, "What are we trying to accomplish here 试图实现什么；想要达成什么目的? Responses like these are great ways to refocus 重新集中注意力；重新关注 your counterpart when you feel you're being pulled into 被拉入；被卷入 the compromise trap 妥协陷阱；折中圈套。

[.my2]
成功的谈判者经常以我们谈论过的许多方式中的一种说不，“我怎么可能接受那个？”或用诸如“我们在这里试图实现什么目的？”之类的问题转移锚点。像这样的回应是当你觉得自己被卷入妥协陷阱时重新集中注意力在你的对手身上的好方法。

You can also respond to a punch in the face 迎面一拳；当面一击 anchor by simply pivoting to 转向；以…为中心 terms 条件；条款。

[.my2]
你也可以通过简单地转向条款来回应当面一击的锚点。

What I mean by this is that when you feel you're being dragged into 被拖入；陷入 a haggle 讨价还价；争论, you can detour 绕道；转移 the conversation to the non-monetary issues 非金钱问题；非货币性问题 that make any final price work.

[.my2]
我的意思是，当你觉得自己陷入讨价还价时，你可以将对话转移到使任何最终价格奏效的非金钱问题。

You can do this directly 直接地；直截了当地 by saying in an encouraging tone of voice 鼓舞人心的语气；鼓励的语调, "Let's put price off to the side 放到一边；暂不考虑 for a moment and talk about what would make this a good deal 好的交易；划算的买卖." Or you could go at it more obliquely 更间接地；更含蓄地 by asking, "What else would you be able to offer to make that a good price for me?" And if the other side pushes you to go first, wrigle from his grip 挣脱他的控制；摆脱他的掌控。

[.my2]
你可以直接地用一种鼓舞人心的语调说：“让我们暂时将价格放到一边，谈谈什么能使这成为一个划算的买卖。”或者你可以更间接地来处理，询问：“你还能提供什么来使这对我来说是一个好价格？”如果对方催促你先开价，挣脱他的控制。

Instead of naming a price 开价；说出价格, allude to 提到；暗指 an incredibly high number 极高的数字；令人难以置信的高价 that someone else might charge 收费；索价。

[.my2]
不要说出价格，暗指一个别人可能会索要的极高的数字。

Once when a hospital chain 连锁医院；医院集团 wanted me to name a price first, I said, "Well, if you go to Harvard Business School, they're going to charge you $2500 a day per student." No matter what happens 无论发生什么；不管怎样, the point here is to sponge up 吸收；吸取 information from your counterpart.

[.my2]
有一次，一家连锁医院想让我先开价，我说：“嗯，如果你去哈佛商学院，他们会向你收取每学生每天 $2500$ 美元。”不管怎样，这里的重点是从你的对手那里吸取信息。

Letting your counterpart anchor first will give you a tremendous feel for 对…有很好的感觉；对…有很好的了解 him.

[.my2]
让你的对手先锚定会让你对他有很好的了解。

All you need to learn is how to take the first punch 承受第一次打击；接招。

[.my2]
你所需要学习的就是如何接招。

One of my Georgetown MBA students, a guy named Farooq, showed how not to fold 屈服；放弃 after being punched when he went to hit up 寻求；索要 the MBA dean for funds 资金；经费 to hold a big alumni event 校友活动；校友聚会 in Dubai.

[.my2]
我的一个乔治城MBA学生，一个名叫法鲁克的人，展示了在受到打击后如何不屈服，当时他去向 MBA 院长寻求资金在迪拜举办一个大型的校友活动。

It was a desperate situation 绝望的境地；危急的情况 because he needed $600$ and she was his last stop 最后一站；最后的希望。

[.my2]
那是一个危急的情况，因为他需要 $600$ 美元，而她是他最后的希望。

At the meeting, Farooq told the dean about how excited 兴奋的；激动的 the students were about the trip and how beneficial 有益的；有利的 it would be for the Georgetown MBA brand 品牌；名誉 in the region 地区；区域。

[.my2]
在会议上，法鲁克告诉院长学生对这次旅行有多兴奋，以及这对乔治城 MBA 品牌在该地区会有多有利。

Before he could even finish, the dean jumped in 插话；介入。

[.my2]
在他甚至还没有说完之前，院长插了进来。

"Sounds like a great trip you guys are planning," she said.

[.my2]
“听起来像是你们正计划一次很棒的旅行，”她说。

"But money is tight 钱紧；资金紧张, and I could authorize 授权；批准 no more than $300$." Farooq hadn't expected the dean to go so quickly, but things don't always go according to plan 总是按计划进行；事事如愿。

[.my2]
“但资金紧张，我最多只能批准 $300$ 美元。”法鲁克没有想到院长会这么快就开价，但事情并不总是事事如愿。

That is a very generous offer 慷慨的报价；大方的出价 given your budget limits 考虑到你的预算限制；鉴于你的预算限制, but I am not sure how that would help us achieve a great reception 很好的招待；盛情款待 for the alums 校友；毕业生 in the region, Farooq said, acknowledging 承认；认可 her limits, but saying no without using the word.

[.my2]
“考虑到你的预算限制，那是一个非常慷慨的报价，但我不确定那将如何帮助我们在该地区为校友实现盛情款待，”法鲁克说，承认了她的限制，但没有使用“不”这个词就说了不。

Then he dropped an extreme anchor 抛出一个极端锚点；提出一个极端的起始价。

[.my2]
然后他抛出了一个极端锚点。

I have a very high amount in my head.

[.my2]
“我心里有一个非常高的金额。

$1,000$ is what we need.

[.my2]
$1,000$ 美元是我们需要的。

As expected 正如所料；不出所料, the extreme anchor quickly knocked the dean off her limit 使院长超出她的限制；让院长打破她的底线。

[.my2]
正如所料，极端锚点很快让院长打破了她的底线。

That is severely 严重地；非常 out of my range 超出我的范围；超出了我的权限 and I am sure I can't authorize that.

[.my2]
“那非常超出了我的权限，我确信我不能批准那个。

However, I will give you $500$.

[.my2]
然而，我会给你 $500$ 美元。”

Farooq was half tempted to fold 有点想屈服；几乎要放弃。

[.my2]
法鲁克有点想屈服。

Being $100$ short 差 $100$ 美元；短缺 $100$ 美元 wasn't make or break 成败关键；决定性因素, but he remembered the curse of aiming low 目标定低；低目标。

[.my2]
差 $100$ 美元不是成败关键，但他记得低目标的弊端。

He decided to push forward 推向前进；继续努力。

[.my2]
他决定继续努力。

The $500$ got him closer to the goal, but not quite there 还没有完全达到；还差一点。

[.my2]
$500$ 美元使他更接近目标，但还没有完全达到。

He said $850$ would work.

[.my2]
他说 $850$ 美元会奏效。

The dean replied by saying that she was already giving more than what she wanted and $500$ was reasonable 合理的；公道的。

[.my2]
院长回答说她已经给出了比她想给的更多，而 $500$ 美元是合理的。

At this point, if Farooq had been less prepared, he would have given up 放弃；投降。

[.my2]
在这一点上，如果法鲁克准备得不充分，他就会放弃。

But he was ready for the punches 准备好承受打击；准备好接招。

[.my2]
但他已经准备好接招。

I think your offer is very reasonable, and I understand your restrictions 限制；约束。

[.my2]
“我认为你的报价非常合理，我理解你的限制。

But I need more money to put on a great show 办一场盛大的展示；搞一次精彩的活动 for the school, he said.

[.my2]
但我需要更多钱为学校搞一次精彩的活动，”他说。

How about $775$? The dean smiled, and Farooq knew he had her 赢得了她的心；抓住了她的关键。

[.my2]
“$775$ 美元怎么样？”院长笑了，法鲁克知道他抓住了她的关键。

You seem to have a specific number 特定的数字；明确的数目 in your head that you are trying to get to, she said.

[.my2]
“你似乎心里有一个你正试图达到的特定数字，”她说。

Just tell it to me.

[.my2]
“就告诉我吧。”

At that point, Farooq was happy to give her his number as he felt she was sincere 真诚的；诚恳的。

[.my2]
在那个时候，法鲁克很乐意告诉她他的数字，因为他觉得她是真诚的。

I need $737.50$ to make this work and you are my last stop, he said.

[.my2]
“我需要 $737.50$ 美元才能让这奏效，你是我的最后一站，”他说。

She laughed.

[.my2]
她笑了。

The dean then praised him for 赞扬；表扬 knowing what he wanted and said she'd check her budget 预算；经费。

[.my2]
然后院长赞扬他知道自己想要什么，并说她会查看她的预算。

2 days later, Farooq got an email saying her office would put in 投入；提供 $750$, punching back using assertion 坚持己见；果断而自信 and without getting used by it 不被利用；不被影响。

[.my2]
两天后，法鲁克收到一封邮件，说她的办公室会投入 $750$ 美元，通过坚持己见进行反击，同时没有被其影响。

When a negotiation is far from resolution 离解决还很远；遥遥无期 and going nowhere fast 进展缓慢；没有快速进展, you need to shake things up 彻底改变；使情况发生变化 and get your counterpart out of their rigid 僵硬的；刻板的 mindset 心态；思维定势。

[.my2]
当谈判遥遥无期并进展缓慢时，你需要彻底改变局面，让你的对手摆脱他们刻板的心态。

In times like this, strong moves 强硬举动；强硬行动 can be enormously 极其；非常 effective tools.

[.my2]
在这种时候，强硬举动可以是极其有效的工具。

Sometimes a situation simply calls for 要求；需要 you to be the aggressor 侵略者；主动攻击者 and punch the other side in the face 当面痛击；直接打击。

[.my2]
有时情况只是要求你成为主动攻击者，并直接打击对方。

That said, if you are basically a nice person, it will be a real stretch 很难做到；费劲 to hit the other guy like Mike Tyson.

[.my2]
话虽如此，如果你基本上是个好人，像迈克·泰森那样打击对方将会很难做到。

You can't be what you're not 你不可能成为你不是的人；做不到。

[.my2]
你做不到。

As the Danish folk saying 丹麦民间谚语 goes, you bake with the flower you have, but anyone can learn a few tools.

[.my2]
正如丹麦民间谚语所说，你用你拥有的面粉烘焙，但任何人都可以学习一些工具。

Here are effective ways to assert smartly 巧妙地坚持己见；聪明地主张。

[.my2]
这里有巧妙地坚持己见的有效方法。

real anger 真正的愤怒, threats without anger 没有愤怒的威胁, and strategic umbrage 战略性地表现不满；故意摆出不悦的样子。

[.my2]
真正的愤怒，没有愤怒的威胁，以及战略性地表现不满。

Marwan Sonaser of INSAD and Stanford University's Lissa Titans found that expressions of anger 表达愤怒；发脾气 increase a negotiator's advantage 优势；有利条件 and final take 最终获得；最终成果。

[.my2]
英士国际商学院的马尔万·索纳瑟和斯坦福大学的丽莎·泰坦发现，表达愤怒会增加谈判者的优势和最终成果。

Two, anger shows passion 热情；激情 and conviction 坚信；信念 that can help sway 说服；使动摇 the other side to accept less.

[.my2]
第二，愤怒展现了热情和信念，可以帮助说服对方接受更少。

However, by heightening 提高；增强 your counterparts sensitivity 敏感性；敏感度 to danger and fear, your anger reduces the resources 资源；能力 they have for other cognitive activity 认知活动；思维活动, setting them up to make bad concessions 做出糟糕的让步；做出不利的妥协 that will likely lead to implementation problems 实施问题；执行问题, thus reducing your gains 收益；好处。

[.my2]
然而，通过提高你的对手对危险和恐惧的敏感性，你的愤怒减少了他们进行其他认知活动的能力，使他们做出糟糕的让步，这很可能导致实施问题，从而减少你的收益。

Also, beware 小心；警惕。

[.my2]
另外，要警惕。

Researchers have also found that disingenuous 不真诚的；不诚实的 expressions of unfelt anger 表达未感受到的愤怒；假装生气, you know, faking it 假装；伪装, backfire 适得其反；产生反效果, leading to intractable 难对付的；棘手的 demands 要求；需求 and destroying trust 破坏信任；摧毁信任。

[.my2]
研究人员还发现不真诚地表达未感受到的愤怒（你知道，假装），会适得其反，导致棘手的要求并破坏信任。

For anger to be effective, it has to be real.

[.my2]
要使愤怒有效，它必须是真实的。

The key for it is to be under control 在控制之下；受到控制。

[.my2]
它的关键在于受到控制。

Because anger also reduces our cognitive ability 认知能力；思维能力。

[.my2]
因为愤怒也会减少我们的认知能力。

And so when someone puts out 提出；公布 a ridiculous offer, one that really pisses you off 惹你生气；使你大发雷霆, take a deep breath 深呼吸；冷静下来, allow little anger, and channel it at 引导至；将…引向 the proposal 提议；方案, not the person, and say, "I don't see how that would ever work." Such well-timed 适时的；及时的 offense taking 感到被冒犯；表示不悦 known as strategic umbrage 战略性地表现不满；故意摆出不悦的样子 can wake your counterpart to the problem 使你的对手意识到问题；让对方注意到问题。

[.my2]
因此，当有人提出一个荒谬的报价，一个真正惹你生气的报价时，深呼吸，允许一点愤怒，并将它引向提议，而不是人，并说：“我不觉得那会奏效。”这种适时的表示不悦，被称为战略性地表现不满，可以使你的对手意识到问题。

In studies by Columbia University academics Daniel Ames and Abby Wlawek, people on the receiving end 接受方；接收者 of strategic umbrage were more likely to rate 评定；评估 themselves as over assertive 过于自信的；过于坚持己见的 even when the counterpart didn't think so.

[.my2]
在哥伦比亚大学学者丹尼尔·艾姆斯和艾比·布拉韦克的研究中，战略性地表现不满的接受方更可能将自己评定为过于坚持己见，即使对手不这么认为。

The real lesson 真正的教训；真正的启示 here is being aware of 意识到；察觉到 how this might be used on you.

[.my2]
这里真正的启示是要意识到这可能如何被用在你身上。

Please don't allow yourself to fall victim to 成为受害者；受害于 strategic umbrage.

[.my2]
请不要让自己受害于战略性地表现不满。

Threats delivered without anger, but with poise 沉着；泰然自若, that is confidence 自信；信心 and self-control 自我控制；自制力, are great tools.

[.my2]
没有愤怒，但沉着地（即自信和自制力）发出的威胁，是很棒的工具。

Saying, "I'm sorry, that just doesn't work for me." with poise works.

[.my2]
沉着地说：“对不起，那对我来说就是行不通。”是有效的。

Why questions? Back in chapter 7, I talked about the problems with why.

[.my2]
为什么的问题？回到第 7 章，我谈了“为什么”的问题。

Across our planet and around the universe 宇宙；世界, why makes people defensive 产生防卫心理；辩护。

[.my2]
在我们的星球上和整个世界，“为什么”使人产生防卫心理。

As an experiment 实验；试验, the next time your boss wants something done, ask him or her why and watch what happens.

[.my2]
作为一个实验，下次你的老板想让某事完成时，问他或她为什么，并观察会发生什么。

Then try it with a peer 同事；同辈, a subordinate 下属；部下, and a friend.

[.my2]
然后对同事、下属和朋友试试。

Observe 观察；注意到 their reactions 反应；回应 and tell me if you don't find some level of defensiveness 防卫心理；防御性 across the spectrum 范围；领域。

[.my2]
观察他们的反应，然后告诉我你是不是在整个范围内都发现了一定程度的防卫心理。

Don't do this too much though where you'll lose your job and all your friends.

[.my2]
不过不要做太多，否则你会失去你的工作和所有的朋友。

The only time I say why did you do that in a negotiation is when I want to knock someone back 使某人退缩；使某人拒绝。

[.my2]
我在谈判中说“你为什么那么做”的唯一一次是当我想使某人退缩时。

It's an iffy 不确定的；冒险的 technique though and I wouldn't advocate 提倡；支持 it.

[.my2]
不过，这是一个冒险的技巧，我不提倡它。

There is however another way to use why effectively 有效地使用；有效地运用。

[.my2]
然而，有另一种方法可以有效地运用“为什么”。

The idea is to employ 利用；使用 the defensiveness the question triggers 触发；引起 to get your counterpart to defend your position 捍卫你的立场；支持你的观点。

[.my2]
这个想法是利用这个问题引起的防卫心理来让你的对手捍卫你的立场。

I know it sounds weird 奇怪的；怪异的, but it works.

[.my2]
我知道这听起来很奇怪，但它奏效。

The basic format 基本形式；基本格式 goes like this.

[.my2]
基本形式是这样的。

When you want to flip a dubious 怀疑的；不确定的 counterpart to your side 转向你这一边；支持你的观点, ask them, "Why would you do that?" But in a way that the that favors you 对你有利；对你有利。

[.my2]
当你想让一个不确定的对手转向你这一边时，问他们，“你为什么会那么做？”但以一种对你有利的方式。

Let me explain.

[.my2]
让我解释一下。

If you are working to lure 吸引；引诱 a client away from 远离；从…身边拉走 a competitor 竞争者；竞争对手, you might say, "Why would you ever do business with me? Why would you ever change from your existing supplier 现有供应商；目前的供货商? They're great." In these questions, the why coaxes 哄骗；诱劝 your counterpart into working for you 为你工作；为你说话。

[.my2]
如果你正努力从一个竞争者身边拉走一个客户，你可能会说：“你为什么会想和我做生意？你为什么会想从你现有的供应商那里更换？他们很棒。”在这些问题中，“为什么”诱劝你的对手为你说话。

I messages.

[.my2]
“我”信息。

Using the first person singular pronoun 第一人称单数代词；“我” is another great way to set a boundary 设定界限；划清界限 without escalating into 升级为；演变成 confrontation 对抗；冲突。

[.my2]
使用第一人称单数代词是另一种很棒的方式来设定界限，而不会升级为对抗。

When you say, "I'm sorry, that doesn't work for me." The word I strategically 策略性地；有战略地 focuses your counterpart's attention onto 集中注意力在；关注 you long enough for you to make a point 表明观点；阐述要点。

[.my2]
当你说：“对不起，那对我来说行不通。”“我”这个词策略性地将你对手的注意力集中在你身上，时间足够你表明观点。

The traditional IM message is to use I to hit the pause button 按下暂停键；暂停 and step out of 退出；摆脱 a bad dynamic 不好的态势；糟糕的局面。

[.my2]
传统的“我”信息是使用“我”来按下暂停键并摆脱一个糟糕的态势。

When you want to counteract 抵消；对抗 unproductive statements 徒劳的陈述；没有建设性的话 from your counterpart, you can say I feel when you because and that demands a timeout 要求暂停；需要时间。

[.my2]
当你想对抗你的对手徒劳的陈述时，你可以说“我感觉，当你，因为”，那要求暂停。

But be careful with 小心；注意 the big eye “大我”；自我中心。

[.my2]
但要小心“大我”。

You have to be mindful 不忘；注意 not to use a tone that is aggressive 咄咄逼人的；有攻击性的 or creates an argument 引起争论；引发冲突。

[.my2]
你必须注意不要使用一个咄咄逼人的语气或引起冲突的语气。

It's got to be cool and level 冷静且平稳的；沉着。

[.my2]
它必须是沉着的。

No neediness 毫无需要；不急切。

[.my2]
不急切。

Having the ready to walk mindset 准备好走人的心态；随时可以离开的心理准备。

[.my2]
拥有随时可以离开的心理准备。

We've said previously that no deal is better than a bad deal 以前说过；之前说过。

[.my2]
我们之前说过没有交易好过糟糕的交易。

If you feel you can't say no, then you've taken yourself hostage 劫持自己；困住自己。

[.my2]
如果你觉得你不能说不，那么你已经困住自己了。

Once you're clear on what your bottom line 底线；最低要求 is, you have to be willing to walk away 愿意离开；愿意退出。

[.my2]
一旦你清楚你的底线是什么，你必须愿意离开。

Never be needy for a deal 对交易急切；渴望达成交易。

[.my2]
永远不要对交易急切。

Before we move on, I want to emphasize 强调；着重指出 how important it is to maintain a collaborative relationship 合作关系；协作关系。

[.my2]
在我们继续之前，我想强调保持合作关系是多么重要。

Even when you're setting boundaries, your response must always be expressed in the form of 以…形式表达；体现为 strong yet empathetic 有同理心的；善解人意的 limit setting boundaries 设定界限；划定限制。

[.my2]
即使当你在设定界限时，你的回应必须始终体现为强硬但有同理心的划定限制。

That is tough love 严厉的爱；苛刻的爱, not as hatred 憎恨；仇恨 or violence 暴力；激烈。

[.my2]
那是严厉的爱，而不是憎恨或激烈。

Anger and other strong emotions can on rare occasions 在极少数情况下；偶尔 be effective, but only as calculated acts 精心策划的行为；有意的举动, never a personal attack 人身攻击；个人抨击。

[.my2]
愤怒和其他强烈情绪在极少数情况下可能有效，但只能作为精心策划的行为，绝不是人身攻击。

In any bare knuckle 徒手的；赤手空拳的 bargaining session, the most vital principle 最重要的原则；核心准则 to keep in mind 记住；牢记 is never to look at your counterpart as an enemy 敌人；对手。

[.my2]
在任何赤手空拳的谈判会议中，要牢记最重要的原则是永远不要将你的对手视为敌人。

The person across the table is never the problem.

[.my2]
坐在对面的人永远不是问题。

The unsolved issue 未解决的问题；悬而未决的争端 is.

[.my2]
未解决的问题才是。

So focus on the issue.

[.my2]
所以关注问题。

This is one of the most basic tactics for avoiding emotional escalations 情感升级；情绪失控。

[.my2]
这是避免情绪失控最基本的策略之一。

Our culture demonizes 妖魔化；丑化 people in movies and politics which creates the mentality that if we only got rid of 摆脱；除掉 the person, then everything would be okay.

[.my2]
我们的文化在电影和政治中妖魔化人，这创造了一种心态，即如果我们能除掉那个人，那么一切就会好起来。

But this dynamic 态势；动态 is toxic to 对…有害；对…有毒 any negotiation.

[.my2]
但这种态势对任何谈判都是有害的。

Punching back 反击；回击 is a last resort 最后手段；最后的选择。

[.my2]
反击是最后手段。

Before you go there, I always suggest an attempt at deescalating 降级；缓和 the situation.

[.my2]
在你到达那里之前，我总是建议尝试缓和局势。

Suggest a timeout 建议暂停；要求休息。

[.my2]
建议暂停。

When your counterparts step back and take a breath, they'll no longer feel that they are hostage to 被劫持；受制于 a bad situation.

[.my2]
当你的对手退后一步并深呼吸时，他们将不再觉得自己受制于一个糟糕的局面。

They'll regain a sense of agency 自主权；主导权 and power, and they'll appreciate 欣赏；感激 you for that.

[.my2]
他们将重新获得自主权和权力，他们会因此感激你。

Think of punching back 反击；回击 and boundary setting 设定界限；划定限制 tactics 策略；手段；招数 as a flattened 扁平的；平缓的 s-curve S形曲线。

[.my2]
将反击和设定界限的策略想象成一条扁平的 S 形曲线。

You've accelerated 加速；加快 up the slope 斜坡；斜面 of a negotiation and hit a plateau 高原期；稳定期 that requires you to temporarily 暂时地；临时地 stop any progress 任何进展；任何进步, escalate 升级；加剧 or deescalate 降级；缓和 the issue, acting as the obstacle 障碍；阻碍, and eventually 最终；最后 bring the relationship back to a state of rapport 建立默契；恢复和谐关系 and get back on the slope。

[.my2]
你已经加快了谈判的斜坡，并达到了一个高原期，它要求你暂时停止任何进展，升级或缓和问题，充当障碍，最终将关系带回到和谐关系的状态并回到斜坡上。

Taking a positive, constructive 建设性的；积极的 approach to conflict 冲突；矛盾 involves understanding that the bond 关系；联系 is fundamental 基础的；根本的 to any resolution 解决；决议。

[.my2]
以积极、建设性的方法对待冲突涉及理解这种联系是任何解决的基础。

Never create an enemy 制造敌人；树敌。

[.my2]
永远不要树敌。

Aurman bargaining 奥尔曼议价；奥尔曼谈判。

[.my2]
奥尔曼议价。

I've spent a lot of time talking about the psychological judo 心理柔术；心理战术 that I've made my stock in trade 惯用手段；看家本领。

[.my2]
我花了很多时间谈论我一直作为看家本领的心理柔术。

The calibrated questions 经过校准的问题；精确设计的问题, the mirrors 镜像；重复对方最后一句话, the tools for knocking my counterpart off his game 使我的对手失常；打乱对方阵脚 and getting him to bid against himself 与自己竞价；自相残杀。

[.my2]
经过校准的问题、镜像、打乱我的对手阵脚并让他自相残杀的工具。

But negotiation still comes down to 归结为；最终是 determining 决定；确定 who gets which slice of the pie 哪一片馅饼；哪一份利益。

[.my2]
但谈判仍然归结为确定谁得到哪一份利益。

And from time to time 偶尔；有时, you're going to be forced into 被迫进行；不得不 bare knuckle bargaining 徒手议价；赤手空拳地谈判 with a hard ass 强硬的；难缠的 haggler 讨价还价者；议价者。

[.my2]
有时，你会被迫与一个难缠的议价者进行一些真正的徒手议价。

I faced bare- knuckle bargaining all the time in the hostage world 人质世界；人质谈判领域。

[.my2]
我在人质谈判领域一直面临徒手议价。

I haggled with 讨价还价；争论 a lot of guys who stuck to 坚持；紧守 their game plan 比赛计划；策略 and were used to getting their way 习惯于随心所欲；习惯于得逞。

[.my2]
我与很多坚持他们策略并习惯于得逞的人讨价还价。

Pay or will kill, they'd say, and they meant it 认真；当真。

[.my2]
“付钱或杀人，”他们会说，而且他们是当真的。

You had to have your skills drum tight 技能娴熟；能力过硬 to negotiate them down 压低价格；谈下来。

[.my2]
你必须技能娴熟才能将他们谈下来。

You need tools.

[.my2]
你需要工具。

Back at FBI negotiation training, I learned the haggling system that I use to this day, and I swear by it 相信；非常推崇。

[.my2]
回到联邦调查局的谈判培训，我学了我至今仍使用的议价系统，而且我非常推崇它。

I call the system the Acriman model 阿克曼模型 because it came from this guy Mike Acriman, an ex CIA type who founded a kidnap for ransom 绑架勒索；为赎金而绑架 consulting company 咨询公司；顾问公司 based out of 设在；总部位于 Miami.

[.my2]
我称这个系统为阿克曼模型，因为它来自这个叫迈克·阿克曼的人，一个前中央情报局的人，他创立了一家总部位于迈阿密的绑架勒索咨询公司。

On many kidnappings, we'd constantly be paired with 与…配对；与…合作 Acriman guys, never Mike himself, who helped design the haggle.

[.my2]
在许多绑架案中，我们会不断与阿克曼公司的人合作，从不是迈克本人，他们帮助设计了议价。

After I retired from the FBI, I finally met Mike on a trip to Miami.

[.my2]
在我从联邦调查局退休后，我终于在一次去迈阿密的旅行中遇到了迈克。

When I told him I also use the system for business negotiations 商业谈判；商务协商, he laughed and said he'd run the system by 向…提交系统；让…过目 Howard Rafa, a legendary 传奇的；赫赫有名的 Harvard negotiation guy.

[.my2]
当我告诉他我也将这个系统用于商业谈判时，他笑了，并说他已经向一位传奇的哈佛谈判专家霍华德·拉法提交了这个系统。

And Howard had said it would work in any situation 任何情况；任何场合。

[.my2]
霍华德曾说它在任何情况下都会奏效。

So I felt pretty justified by 感到相当合理；觉得理所当然 that.

[.my2]
所以我对此感到相当合理。

The Acriman model is an offer counter offer method 报盘还盘法；报价和反报价的方法, at least on the surface 至少表面上；至少看起来, but it is a very effective system for beating the usual lackluster 缺乏活力的；平庸的 bargaining dynamic 议价态势；谈判格局 which has the predictable result 可预测的结果；意料之中的结果 of meeting in the middle 中间相遇；折中。

[.my2]
阿克曼模型至少表面上是一种报盘还盘方法，但它是一个非常有效的系统来击败通常缺乏活力的议价态势，这种态势有中间相遇的可预测结果。

The systematized 系统化的；有系统的 and easy to remember process has only four steps.

[.my2]
这个系统化且容易记住的过程只有四个步骤。

One, set your target price 目标价格；预期价, your goal.

[.my2]
一、设定你的目标价格，你的目标。

Two, set your first offer at $65\%$ of your target price.

[.my2]
二、将你的第一个报价设定为你目标价格的 $65\%$。

Three, calculate three raises of decreasing increments 递减的增量；越来越小的增加额 to $85, 95$, and $100\%$.

[.my2]
三、计算三次递减增量的加价，达到 $85\%$、 $95\%$ 和 $100\%$。

Four, use lots of empathy 同理心；共情 and different ways of saying no to get the other side to counter 还价；反报价 before you increase your offer.

[.my2]
四、使用大量的同理心和不同的说不的方式来让对方在你增加你的报价之前还价。

Five, when calculating the final amount 最终金额；最后数目, use precise non-round numbers 精确的非整数；非整齐的数字 like say $37,893$ rather than $38,000$.

[.my2]
五、在计算最终金额时，使用精确的非整数，比如 $37,893$ 美元，而不是 $38,000$ 美元。

It gives the number credibility 可信度；可靠性 and weight 重要性；分量。

[.my2]
它赋予这个数字可信度和分量。

Six.

[.my2]
六。

On your final number, throw in 加入；包括 a non-monetary item 非金钱项目；非货币性物品 that they probably don't want to show you're at your limit 达到你的极限；达到你的底线。

[.my2]
在你的最终数字上，加入一个他们可能不想要的非金钱项目来显示你已经达到你的底线。

The genius 天才之处；精妙之处 of this system is that it incorporates 包含；纳入 the psychological tactics 心理策略；心理战术 we've discussed: reciprocity 互惠；对等, extreme anchors 极端锚点；极端的起始价, loss aversion 损失厌恶；厌恶损失, and so on without you needing to think about them.

[.my2]
这个系统的精妙之处在于它纳入了我们讨论过的心理策略：互惠、极端锚点、损失厌恶等，而你不需要去思考它们。

If you'll bear with me for a moment 请耐心听我讲；请稍等, I'll go over 仔细检查；回顾 the steps so you see what I mean.

[.my2]
如果你愿意耐心听我讲一会，我将回顾这些步骤，这样你就能明白我的意思。

First, the original offer of $65\%$ of your target price will set an extreme anchor, a big slap in the face 当面一巴掌；狠狠一击 that might bring your counterpart right to their price limit 价格限制；最高出价。

[.my2]
首先，你目标价格的 $65\%$ 的最初报价将设置一个极端锚点，一个狠狠一击，可能会将你的对手直接带到他们的价格限制。

The shock 震惊；冲击 of an extreme anchor will induce 引起；导致 a fight-or-flight reaction 战斗或逃跑反应；应激反应 in all but the most experienced negotiators, limiting their cognitive abilities and pushing them into rash action 轻率的行动；鲁莽的举动。

[.my2]
极端锚点的冲击会在除了最有经验的谈判者之外的所有人中引起应激反应，限制他们的认知能力并将他们推入轻率的行动。

Now, look at the progressive offer increases 逐步增加的报价；渐进式加价 to $85, 95$, and $100\%$ of the target price.

[.my2]
现在，看看目标价格的 $85\%$、 $95\%$ 和 $100\%$ 的渐进式加价。

You're going to drop these in sparingly 节制地；谨慎地 after the counterpart has made another offer on their end 在他们那边；由他们提出 and after you've thrown out 提出；抛出 a few calibrated questions to see if you can bait them into 诱使；引诱 bidding against themselves.

[.my2]
在对手提出另一个报价后，以及在你抛出一些经过校准的问题来看是否可以诱使他们自相残杀之后，你将谨慎地提出这些加价。

When you make these offers, they work on various levels 在不同层面发挥作用；在多个层次起作用。

[.my2]
当你提出这些报价时，它们在多个层次起作用。

First, they play on the norm of reciprocity 互惠规范；互惠原则。

[.my2]
首先，它们利用互惠原则。

They inspire 激励；鼓舞 your counterpart to make a concession 做出让步；妥协, too.

[.my2]
它们也激励你的对手做出让步。

Just like people are more likely to send Christmas cards to people who first send cards to them, they are more likely to make bargaining concessions 议价让步；谈判妥协 to those who have made compromises 妥协；让步 in their direction.

[.my2]
就像人们更可能给先给他们寄卡片的人寄圣诞卡一样，他们更可能向那些已经在他们的方向做出妥协的人做出议价让步。

Second, the diminishing size 递减的规模；逐渐减小的幅度 of the increases, notice that they decrease by half each time, convinces 说服；使相信 your counterpart that he's squeezing you 挤压你；让你难以忍受 to the point of breaking 濒临崩溃；快要到极限。

[.my2]
其次，加价递减的幅度（注意到它们每次减少一半），说服你的对手他正将你挤压到濒临崩溃的地步。

By the time they get to the last one, they'll feel that they've really gotten every last drop 获得每一滴；榨干所有。

[.my2]
到他们得到最后一个时，他们会觉得他们真的榨干了所有。

This really juices 激发；增强 their self-esteem 自尊；自尊心。

[.my2]
这真的激发了他们的自尊心。

Researchers have found that people getting concessions often feel better about the bargaining process than those who are given a single firm fair offer 坚定的公平报价；唯一的公正出价。

[.my2]
研究人员发现获得让步的人通常对议价过程感觉比那些获得一个坚定的公平报价的人更好。

In fact, they feel better even when they end up paying more 最终支付更多；最后付出更多 or receiving less than they otherwise might 否则可能；本来可能。

[.my2]
事实上，即使他们最终支付更多或收到比他们本来可能收到的更少，他们感觉也更好。

Finally, the power of non-round numbers bears reiterating 值得重申；需要再次强调。

[.my2]
最后，非整数的力量值得重申。

Back in Haiti, I used to use the Acriman system ferociously 猛烈地；激烈地。

[.my2]
回到海地，我曾经激烈地使用阿克曼系统。

Over 18 months, we got two or three kidnappings a week.

[.my2]
在 18 个月里，我们每周有两到三起绑架案。

So, from experience, we knew the market prices 市场价格；行情 were $15,000$ to $75,000$ per victim.

[.my2]
所以，根据经验，我们知道每个受害者的市场价格是 $15,000$ 到 $75,000$ 美元。

Because I was a hard ass, I made it my goal to get in under $5,000$ in every kidnapping that I ran 主导；负责。

[.my2]
因为我是一个难缠的人，我把我主导的每起绑架案中的价格控制在 $5,000$ 美元以下作为我的目标。

One really stands out 脱颖而出；非常突出, the first one I mentioned in this book.

[.my2]
有一起特别突出，就是我在这本书中提到的第一起。

I went through the acriman process, knocking them off their game with an extreme anchor, hitting them with calibrated questions and slowly gave progressively smaller concessions 逐渐更小的让步；越来越少的妥协。

[.my2]
我经历了阿克曼过程，用一个极端锚点打乱了他们的阵脚，用经过校准的问题打击他们，并慢慢给予逐渐更少的让步。

Finally, I dropped the weird number 奇怪的数字；不寻常的数目 that closed the deal 敲定交易；达成协议。

[.my2]
最后，我抛出了敲定交易的那个奇怪的数字。

I'll never forget the head of the Miami FBI office calling my colleague the next day and saying, "Vos got this guy out for $4,751$.

[.my2]
我永远不会忘记迈阿密联邦调查局办公室的负责人第二天给我的同事打电话说：“沃斯以 $4,751$ 美元把这个人救了出来。

How does one make a difference 起作用；产生影响?" They were howling with laughter 狂笑；大笑 and they had a point 有道理；言之有理。

[.my2]
一美元怎么会起作用？”他们狂笑，而且他们言之有理。

That $1$ is ridiculous 荒谬的；可笑的, but it works on our human nature.

[.my2]
那 $1$ 美元是可笑的，但它对我们的人性起作用。

Notice that you can't buy anything for $2$, but you can buy a million things for $1.99$.

[.my2]
注意到你不能用 $2$ 美元买任何东西，但你可以用 $1.99$ 美元买一百万件东西。

How does a scent change anything? It doesn't, but it makes a difference every time.

[.my2]
一美分如何改变任何事情？它没有，但它每次都起作用。

We just like $1.99$ more than $2.00$, even if we know it's a trick 诡计；花招。

[.my2]
我们只是比 $2.00$ 美元更喜欢 $1.99$ 美元，即使我们知道这是一个花招。

negotiating a rent cut 租金削减；降低租金 after receiving notice of an increase 收到涨价通知；收到涨价警告。

[.my2]
在收到涨价通知后协商降低租金。

Eight months after a Georgetown MBA student of mine named Mishiri signed a rental contract 租赁合同；租房合同 for $1,850$ a month, he got some unwelcome news 不受欢迎的消息；坏消息。

[.my2]
在我的一个乔治城 MBA 学生米希里签署了每月 $1,850$ 美元的租赁合同八个月后，他收到了一些坏消息。

His landlord 房东；出租人 informed him that if he wanted to reup 续约；再次签约, it would be $2,100$ a month for $10$ months or $2,000$ a month for a year.

[.my2]
他的房东通知他，如果他想续约，将是每月 $2,100$ 美元持续 10 个月，或每月 $2,000$ 美元持续一年。

Mishiri loved the place and didn't think he'd find a better one.

[.my2]
米希里喜欢这个地方，不认为他会找到一个更好的。

But the price was already high and he couldn't afford 负担得起；买得起 more.

[.my2]
但价格已经很高，他负担不起更多。

Taking to heart 铭记在心；牢记 our class slogan 口号；标语, you fall to your highest level of preparation 你会落到你最高水平的准备；你的表现不会超出你的准备水平, he dove into 投入；一头扎进 the real estate listings 房产列表；房地产信息 and found that prices for comparable 相当的；可比较的 apartments were $1,800$ to $1950$ a month, but none of them were in as good a building.

[.my2]
他牢记我们的课堂口号（你的表现不会超出你的准备水平），他一头扎进房地产信息中，发现可比较的公寓价格是每月 $1,800$ 到 $1,950$ 美元，但没有一栋在同样好的建筑中。

He then examined 检查；细查 his own finances 财务状况；经济情况 and figured 认为；估计 the rent he wanted to pay was $1830$.

[.my2]
然后他检查了自己的财务状况，估计他想支付的租金是 $1830$ 美元。

He requested a sit down with 与…面谈；要求会面 his rental agent 租赁中介；房屋经纪人。

[.my2]
他要求与他的房屋经纪人面谈。

This was going to be tough 艰难的；困难的。

[.my2]
这将是艰难的。

At their meeting, Mishari laid out 摆出；解释 his situation 处境；情况。

[.my2]
在他们的会议上，米沙里解释了他的处境。

His experience in the building had been really positive 积极的；好的, he said, and he pointed out 指出；提到 he always paid on time 按时付款；准时支付。

[.my2]
他说，他在这栋楼里的经历一直非常好，他指出他总是按时付款。

It would be sad for him to leave, he said, and sad for the landlord to lose a good tenant 租客；房客。

[.my2]
他说，他离开会很难过，房东失去一个好租客也会很难过。

The agent nodded 点头；表示同意。

[.my2]
中介点了头。

Totally in agreement 完全同意；完全赞同, he said.

[.my2]
“完全同意，”他说。

That's why I think it will benefit both of us to agree on renewing the lease 同意续租；同意更新租约。

[.my2]
这就是为什么我认为同意续租对我们双方都有益。

Here, Mishari pulled out 拿出；取出 his research 研究资料；调查结果。

[.my2]
在这里，米沙里拿出了他的研究资料。

Buildings around the neighborhood 附近；邻近地区 were offering much lower prices, he said.

[.my2]
他说，附近的建筑提供的价格要低得多。

Even though your building is better in terms of location and services 服务方面；服务质量, how am I supposed to pay $200$ extra? The negotiation was on 谈判开始了；谈判进行中。

[.my2]
尽管你的建筑在位置和服务方面更好，但我怎么可能多付 $200$ 美元？谈判开始了。

The agent went silent 保持沉默；不说话 for a few moments and then said, "You make a good point 提出了一个好观点；说得有道理, but this is still a good price, and as you noted 指出；提到, we can charge a premium 溢价；额外费用。” Misher then dropped an extreme anchor 提出了一个极端锚点；抛出一个极端的起始价。

[.my2]
中介沉默了一会儿，然后说：“你说得有道理，但这仍然是一个好价格，而且正如你提到的，我们可以收取溢价。”米沙里随后提出了一个极端锚点。

"I fully understand 完全理解；完全明白, you do have a better location and amenities 便利设施；配套设施, but I'm sorry, I just can't," he said.

[.my2]
“我完全理解，你确实有更好的位置和便利设施，但很抱歉，我就是做不到，”他说。

"Would $1,730$ a month for a year lease 一年租约；一年期租赁 sound fair 公平的；合理的 to you?" The agent laughed and when he finished said there was no way to accept that number because it was way below 远低于；远远低于 market price 市场价格；市价。

[.my2]
“每月 $1,730$ 美元的一年租约对你来说听起来公平吗？”中介笑了，当他笑完后，说没有办法接受那个数字，因为它远远低于市场价格。

Instead of getting pulled into 被卷入；陷入 a haggle 讨价还价；争论, Missy smartly pivoted to 巧妙地转向；聪明地转向 calibrated questions 经过校准的问题；精确设计的问题。

[.my2]
米希里没有陷入讨价还价，而是巧妙地转向了经过校准的问题。

Okay, so please help me understand how do you price lease renewals 租约续签；租赁续期? The agent didn't say anything shocking 令人震惊的；出人意料的, merely that they used factors 因素；要素 like area prices and supply and demand 供求关系；供需。

[.my2]
“好的，那么请帮我理解你如何为租约续签定价？”中介没有说任何令人震惊的事情，只是说他们使用了诸如区域价格和供求关系之类的因素。

But that gave Misher the opening to argue 有机会争辩；得到了一个切入点 that his leaving would open the landlord to the risk of having an unrened apartment 未出租的公寓；空置的单元 and the cost of repainting 重新粉刷；重新油漆的费用。

[.my2]
但这给了米希里一个争辩的切入点，即他的离开会使房东面临拥有一个空置的单元和重新粉刷的费用的风险。

One month unrened would be a $2,000$ loss, he said.

[.my2]
他说，一个月空置将是 $2,000$ 美元的损失。

Then he made another offer.

[.my2]
然后他提出了另一个报价。

Now, you're probably shaking your head 摇头；表示不同意 that he's making two offers without receiving one in return 作为回报；作为交换。

[.my2]
现在，你可能正摇着头，因为他提出了两个报价而没有收到一个作为交换。

And you're right, normally that's verboten 被禁止的；被视为禁忌的, but you have to be able to improvise 即兴创作；随机应变。

[.my2]
你是对的，通常那是被禁止的，但你必须能够随机应变。

If you feel in control of 掌控；控制 a negotiation, you can do two or three moves at a time 同时做两三个动作；一次进行两三个步骤。

[.my2]
如果你感觉掌控着谈判，你可以一次进行两三个步骤。

Don't let the rules ruin the flow 破坏流程；打断节奏。

[.my2]
不要让规则破坏流程。

Let me try and move along with you 跟着你的思路；和你一起进展。

[.my2]
让我试着跟着你的思路进展。

How about $1,790$ for $12$ months? The agent paused 暂停；沉默。

[.my2]
12 个月以 $1,790$ 美元怎么样？中介沉默了。

Sir, I understand your concerns 担忧；顾虑 and what you said makes sense 有道理；合乎情理。

[.my2]
“先生，我理解你的顾虑，你说的有道理。

He said, your number though is very low.

[.my2]
他说，不过你的数字非常低。

However, give me time to think this out 想清楚；仔细考虑 and we can meet at another time.

[.my2]
然而，给我时间仔细考虑一下，我们可以另找时间见面。

How does that sound? Remember, any response that is not an outright rejection 彻底拒绝；明确拒绝 means you have the edge 优势；有利条件。

[.my2]
听起来怎么样？”记住，任何不是彻底拒绝的回应都意味着你有优势。

5 days later, the two met again.

[.my2]
5 天后，两人再次见面。

I ran the numbers 计算数字；做了计算 and believe me, this is a good deal, the agent started.

[.my2]
“我做了计算，相信我，这是一个好交易，”中介开始说。

I am able to offer you $1,950$ a month for a year.

[.my2]
“我能以每月 $1,950$ 美元的价格提供给你一年。”

Mishari knew he'd won.

[.my2]
米沙里知道他赢了。

The agent just needed a little push 一点推动；一点鼓励。

[.my2]
中介只是需要一点推动。

So, he praised 赞扬；表扬 the agent and said no without saying no.

[.my2]
所以，他赞扬了中介，并在没有说“不”的情况下说了不。

And notice how he brilliantly mislabels 巧妙地贴错标签；聪明地误称 in order to get the guy to open up 坦诚；敞开心扉。

[.my2]
并注意他如何巧妙地误称，以便让对方敞开心扉。

That is generous 大方的；慷慨的 of you.

[.my2]
“你真大方。

But how am I supposed to accept it when I can move a few blocks away 搬到几个街区之外；搬到附近 and stay for $1,800$? $150$ a month means a lot to me.

[.my2]
但当我可以搬到附近并以 $1,800$ 美元住下来时，我怎么可能接受它？每月 $150$ 美元对我来说意义重大。

You know, I am a student.

[.my2]
你知道，我是一个学生。

I don't know.

[.my2]
我不知道。

It seems like you would rather run the risk 承担风险；冒风险 of keeping the place unrened。

[.my2]
看来你宁愿冒着让这个地方空置的风险。”

It's not that the agent answered, but I can't give you a number lower than the market.

[.my2]
“不是那样，”中介回答道，“但我不能给你一个低于市场的数字。”

Misher made a dramatic pause 戏剧性的停顿；引人注目的沉默 as if the agent was extracting every cent 榨取每一分钱；竭尽所能地压榨 he had.

[.my2]
米沙里做了一个引人注目的停顿，仿佛中介正竭尽所能地压榨他的每一分钱。

Then I tell you what, I initially 最初；开始时 went up from $1,730$ to $1,790$, he said, sighing 叹气；叹息。

[.my2]
“那么我告诉你吧，我最初从 $1,730$ 美元加到 $1,790$ 美元，”他叹着气说。

I will bring it up to 提高到；增加到 $1,810$ and I think this works well for both.

[.my2]
“我会将它增加到 $1,810$ 美元，我认为这对双方都很好。”

The agent shook his head 摇头；表示不赞同。

[.my2]
中介摇了头。

This is still lower than the market, sir, and I cannot do that.

[.my2]
“先生，这仍然低于市场，我不能那样做。”

Misher then prepared to give the last of his acriman offers.

[.my2]
米沙里随后准备给出他最后的阿克曼报价。

He went silent for a while and then asked the agent for a pen and paper 笔和纸；文具。

[.my2]
他沉默了一会儿，然后向中介要了笔和纸。

Then he started doing fake calculations 假装计算；虚假计算 to seem like he was really pushing himself 真的在逼自己；竭尽全力。

[.my2]
然后他开始假装计算，看起来像是真的在逼自己。

Finally, he's looked up at the agent and said, "I did some numbers, and the maximum I can afford 负担得起；能承受 is $1,829$." Warm.

[.my2]
最后，他抬头看着中介说：“我算了一些数字，我能承受的最高金额是 $1,829$ 美元。”接近了。

The agent bobbed his head 上下晃动他的头；点点头 from side to side 左右；来回 as if getting his mind around 领会；理解 the offer.

[.my2]
中介左右晃动着他的头，仿佛在领会这个报价。

At last 终于；最后, he spoke.

[.my2]
终于，他说话了。

"Wow, $1,829$," he said.

[.my2]
“哇，$1,829$ 美元，”他说。

"You seem very precise 精确的；严谨的.

[.my2]
“你看起来非常严谨。

You must be an accountant 会计师；账房." Mishari was not.

[.my2]
你一定是个会计师。”米沙里不是。

Listen, I value 重视；珍视 you wanting to renew with us.

[.my2]
“听着，我珍视你想和我们续约。

And for that, I think we can make this work for a $12$-month lease.

[.my2]
因此，我认为我们可以让这个为一个 12 个月的租约奏效。

Kaching 钱到账的拟声词；成功了。

[.my2]
成功了。

Notice this brilliant combination 巧妙的结合；绝妙的搭配 of decreasing acrement offers 递减增量的报价；增量逐渐减小的出价, non-round numbers 非整数；非整齐的数字, deep research 深入研究；透彻调查, smart labeling 巧妙的贴标签；聪明的称呼, and saying no without saying no.

[.my2]
注意这种递减增量报价、非整数、深入研究、巧妙贴标签、以及在没有说“不”的情况下说“不”的绝妙搭配。

That's what gets you a rent discount 租金折扣；房租减免 when a landlord wanted to raise his monthly take 月收入；每月所得。

[.my2]
这就是当房东想提高他的月收入时能让你获得租金折扣的原因。

Key lessons 关键教训；核心要点。

[.my2]
关键要点。

When push comes to shove 到了关键时刻；在紧要关头, and it will, you're going to find yourself sitting across the table from 与…面对面坐着；与…谈判 a bare knuckle negotiator 赤手空拳的谈判者；强硬的议价者。

[.my2]
到了关键时刻（而且它会来的），你会发现自己与一个强硬的议价者面对面坐着。

After you finished all the psychologically nuanced stuff 心理上微妙的东西；微妙的心理技巧, the labeling and mirroring and calibrating 校准；调整, you are going to have to hash out the brass tax 敲定实质性问题；解决实际问题。

[.my2]
在你完成了所有微妙的心理技巧，即贴标签、镜像和校准之后，你将不得不敲定实质性问题。

For most of us, that ain't fun 不好玩；没有乐趣。

[.my2]
对我们大多数人来说，那不好玩。

Top negotiators 顶级谈判者；谈判高手 know, however, that conflict is often the path to great deals 达成大交易；获得巨大成功, and the best find ways to actually have fun engaging in 参与；从事 it.

[.my2]
然而，顶级谈判者知道冲突通常是获得巨大成功的途径，而最好的谈判者会找到方法来实际享受参与其中的乐趣。

Conflict brings out 带来；展现 truth, creativity 创造力；创新精神, and resolution 解决；决心。

[.my2]
冲突带来真相、创造力和解决。

So, the next time you find yourself face to face with 面对面；与…遭遇 a bare knuckle bargainer, remember the lessons in this chapter.

[.my2]
所以，下次你发现自己与一个强硬的议价者面对面时，记住本章的教训。

Identify your counterparts negotiating style 谈判风格；协商模式。

[.my2]
识别你的对手的谈判风格。

Once you know whether they are accommodator 迁就型；迎合型, assertive 坚定型；自信型, or analyst 分析型；分析师型, you'll know the correct way to approach them 接近他们；与他们打交道。

[.my2]
一旦你知道他们是迁就型、坚定型还是分析型，你就会知道与他们打交道的正确方法。

Prepare, prepare, prepare.

[.my2]
准备，准备，再准备。

When the pressure is on 压力很大；形势紧张, you don't rise to the occasion 应付自如；抓住机会。

[.my2]
当形势紧张时，你不会应付自如。

You fall to your highest level of preparation。

[.my2]
你会落到你最高水平的准备。

So, design an ambitious 雄心勃勃的；有抱负的 but legitimate 合法的；合理的 goal and then game out 模拟；推演 the labels, calibrated questions, and responses you'll use to get there.

[.my2]
所以，设计一个雄心勃勃但合理的目标，然后推演你将用来达到目标的标签、经过校准的问题和回应。

That way, once you're at the bargaining table 谈判桌；谈判会场, you won't have to wing it 即兴发挥；临场发挥。

[.my2]
那样一来，一旦你在谈判桌上，你就不必临场发挥了。

Get ready to take a punch 准备好承受打击；准备接招。

[.my2]
准备接招。

Kick-ass negotiators 厉害的谈判者；了不起的协商者 usually lead with an extreme anchor to knock you off your game 使你失常；打乱你的阵脚。

[.my2]
厉害的谈判者通常以一个极端锚点开场来打乱你的阵脚。

If you're not ready, you'll flee to 逃往；奔向 your maximum without a fight 没有战斗；不战而降。

[.my2]
如果你没有准备好，你会不战而降地奔向你的最大限度。

So, prepare your dodging 躲避；闪避 tactics to avoid getting sucked into 被卷入；陷入 the compromise trap 妥协陷阱；折中圈套。

[.my2]
所以，准备你的躲避策略来避免陷入妥协陷阱。

Set boundaries and learn to take a punch or punch back without anger。

[.my2]
设定界限，并学会承受打击或在没有愤怒的情况下反击。

The guy across the table is not the problem.

[.my2]
桌子对面的人不是问题。

the situation is.

[.my2]
情况是。

Prepare an acriman plan 阿克曼计划；阿克曼方案。

[.my2]
准备一个阿克曼计划。

Before you head into the weeds 陷入困境；迷失方向 of bargaining, you'll need a plan of extreme anchor, calibrated questions, and well-defined 明确界定的；清晰界定的 offers.

[.my2]
在你陷入谈判的困境之前，你需要一个极端锚点、经过校准的问题和明确界定的报价的计划。

Remember, $65, 85, 95, 100\%$.

[.my2]
记住， $65\%$、 $85\%$、 $95\%$、 $100\%$。

Decreasing raises 递减的加价；逐渐减少的增加额 and ending on non-round numbers will get your counterpart to believe that he's squeezing you for all you're worth 榨取你的全部价值；榨干你所有价值 when you're really getting to the number you want。

[.my2]
递减的加价和以非整数结束会让你的对手相信他正在榨取你所有价值，而你实际上正在达到你想要的数字。

'''

== pure

Bargain hard. + 

A few years ago, I fell in love with a red Toyota 4Erunner. + 

Actually, not just red, but salsa red pearl. + 

Kind of a smoldering red that seemed to glow at night. + 

How sexy is that? I just had to have it. + 

Getting one became my obsession. + 

I searched the dealers in metropolitan Washington DC, and I quickly realized that I wasn't the only one obsessed with getting that truck. + 

There weren't any in that color in the entire area. + 

None at all, save at one dealer. + 

You know how they tell you not to shop for groceries when you're hungry? Well, I was hungry. + 

Very hungry. + 

Actually, I was in love. + 

I sat down, centered myself, and strategized. + 

This lot was my only shot. + 

I had to make it count. + 

I drove to the dealer on a sunny Friday afternoon. + 

I sat down across from the salesman, a nice enough guy named Stan, and told him how gorgeous the vehicle was. + 

He offered me the usual smile. + 

He had me, he thought, and mentioned the sticker price on that beautiful vehicle, $36,000. + 

I gave him an understanding nod and pursed my lips. + 

The key to beginning a haggle is to rattle the other guy ever so gently. + 

You do it in the nicest way possible. + 

If I could thread that needle, I had a good chance at getting my price. + 

I can pay $30,000, I said, and I can pay it upfront, all cash. + 

I'll write a check today for the full amount. + 

I'm sorry. + 

I'm afraid I just can't pay anymore. + 

His smile flickered a little bit at the edges, as if it were losing focus, but he tightened it down and shook his head. + 

I'm sure you can understand we can't do that. + 

The sticker price is $36,000 after all. + 

How am I supposed to do that? I asked differentially. + 

I'm sure, he said, then paused as if he wasn't sure what he'd meant to say. + 

I'm sure we can figure something out with financing the $36,000. + 

It's a beautiful truck. + 

Really amazing. + 

I can't tell you how much I'd love to have it. + 

It's worth more than what I'm offering. + 

I'm sorry. + 

This is really embarrassing. + 

I just can't do that price. + 

He stared at me in silence, a little befuddled now. + 

Then he stood and went into the back for what seemed like an eternity. + 

He was gone so long that I remember saying to myself, "Damn, I should have come in lower. + 

They're going to come all the way down." Any response that's not an outright rejection of your offer means you have the edge. + 

He returned and told me like it was Christmas that his boss had okayed a new price, $34,000. + 

"Wow, your offer is very generous and this is the car of my dreams," I said. + 

"I really wish I could do that. + 

I really do. + 

This is so embarrassing." "I simply can't." He dropped into silence, and I didn't take the bait. + 

I let the silence linger and then with a sigh he trudged off again. + 

He returned after another eternity. + 

You win, he said. + 

My manager oayed $32,500. + 

He pushed a paper across the desk that even said you win in big letters. + 

The words were even surrounded with smiley faces. + 

I am so grateful. + 

You've been very generous and I can't thank you enough. + 

The truck is no doubt worth more than my price, I said. + 

I'm sorry. + 

I just can't do that. + 

Up he stood again. + 

No smile now, still befuddled. + 

After a few seconds, he walked back to his manager and I leaned back. + 

I could taste victory. + 

A minute later, no eternity this time, he returned and sat. + 

We can do that, he said. + 

Two days later, I drove off in my Salsa Red Pearl Toyota 4Erunner for $30,000. + 

God, I love that truck. + 

Still drive it today. + 

Most negotiations hit that inevitable point where the slightly loose and informal interplay between two people turns to confrontation and the proverbial brass tax. + 

You know the moment. + 

You've mirrored and labeled your way to a degree of rapport. + 

An accusation audit has cleared any lingering mental or emotional obstacles, and you've identified and summarized the interests and positions at stake, eliciting a that's right, and now it's time to bargain. + 

Here it is, the clash for cash, an uneasy dance of offers and counters that send most people into a cold sweat. + 

If you count yourself among that majority, regarding the inevitable moment as nothing more than a necessary evil, there's a good chance you regularly get your clock cleaned by those who have learned to embrace it. + 

No part of a negotiation induces more anxiety and unfocused aggression than bargaining, which is why it's the part that is more often fumbled and mishandled than any other. + 

It's simply not a comfortable dynamic for most people. + 

Even when we have the best laid plans, a lot of us wimp out when we get to the moment of exchanging prices. + 

In this chapter, I'm going to explain the tactics that make up the bargaining process and look at how psychological dynamics determine which tactics should be used and how they should be implemented. + 

Now, bargaining is not rocket science, but it's not simple intuition or mathematics either. + 

To bargain well, you need to shed your assumptions about the haggling process and learn to recognize the subtle psychological strategies that play vital roles at the bargaining table. + 

Skilled bargainers see more than just opening offers, counter offers, and closing moves. + 

They see the psychological currents that run below the surface. + 

Once you've learned to identify these currents, you'll be able to read bargaining situations more accurately and confidently. + 

Answer the tactical questions that dog even the best negotiators. + 

You'll be ready for the bare knuckle bargaining and they'll never see it coming. + 

What type are you? A few years ago, I was on my boat with one of my employees, a great guy named Kenan. + 

I was supposed to be giving him a pep talk and performance review. + 

When I think of what we do, I describe it as uncovering the riptide. + 

I said, "Uncovering the riptide." Kenan said, "Yes, the idea is that we, you and I, and everyone here have the skills to identify the psychological forces that are pulling us away from shore and use them to get somewhere more productive." "Somewhere more productive," Kenan said. + 

"Exactly," I said. + 

"To a place where we can." We had talked for about 45 minutes when my son Brandon, who runs operations for the Black Swan Group, broke out laughing. + 

I can't take it anymore. + 

Don't you see? Really, Dad? Don't you see? I blinked. + 

Did I see what? I asked him. + 

All Keenan is doing is mirroring you, and he's been doing it for almost an hour. + 

Oh, I said, my face going red as Kenan began to laugh. + 

He was totally right. + 

Kenan had been playing with me the entire time, using the psychological tool that works most effectively with assertive guys like me, the mirror. + 

Your personal negotiation style and that of your counterpart is formed through childhood, schooling, family, culture, and a million other factors. + 

By recognizing it, you can identify your negotiating strengths and weaknesses and those of your counterpart and adjust your mindset and strategies accordingly. + 

Negotiation style is a crucial variable in bargaining. + 

If you don't know what instinct will tell you or the other side to do in various circumstances, you'll have massive trouble gaming out effective strategies and tactics. + 

You and your counterpart have habits of mind and behavior. + 

And once you identify them, you can leverage them in a strategic manner, just like Kenan did. + 

There's an entire library unto itself of research into the archetypes and behavioral profiles of all the possible people you're bound to meet at the negotiating table. + 

It's flatout overwhelming. + 

So much so that it loses its utility. + 

Over the last few years, in an effort primarily led by my son Brandon, we've consolidated and simplified all that research, cross-referencing it with our experiences in the field and the case studies of our business school students and found that people fall into three broad categories. + 

Some people are accommodators, others, like me are basically assertive and the rest are data loving analysts. + 

Hollywood negotiation scenes suggest that an assertive style is required for effective bargaining, but each of the styles can be effective. + 

And to truly be effective, you need elements from all three. + 

A study of American lawyer negotiators, one found that 65% of attorneys from two major US cities used a cooperative style while only 24% were truly assertive. + 

And when these lawyers were graded for effectiveness, more than 75% of the effective group came from the cooperative type. + 

Only 12% were assertive. + 

So if you're not assertive, don't despair. + 

Blunt assertion is actually counterproductive most of the time. + 

And remember, your personal negotiating style is not a straight jacket. + 

No one is exclusively one style. + 

Most of us have the capacity to throttle up our non-dominant styles should the situation call for it. + 

But there is one basic truth about a successful bargaining style. + 

To be good, you have to learn to be yourself at the bargaining table. + 

To be great, you have to add to your strengths, not replace them. + 

Here's a quick guide to classifying the type of negotiator you're facing and the tactics that will be most fitting for you. + 

analyst. + 

Analysts are methodical and diligent. + 

They are not in a big rush. + 

Instead, they believe that as long as they are working toward the best result in a thorough and systematic way, time is of little consequence. + 

Their self-image is linked to minimizing mistakes. + 

Their motto, as much time as it takes to get it right. + 

Classic analysts prefer to work on their own and rarely deviate from their goals. + 

They rarely show emotion and they often use what is very close to the FM DJ voice I talked about in chapter 3, slow and measured with a downward inflection. + 

However, analysts often speak in a way that is distant and cold instead of soothing. + 

This puts people off without them knowing it and actually limits them from putting their counterpart at ease and opening them up. + 

Analysts pride themselves on not missing any details in their extensive preparation. + 

They will research for two weeks to get data they might have gotten in 15 minutes at the negotiating table just to keep from being surprised. + 

Analysts hate surprises. + 

They are reserved problem solvers and information aggregators and are hyper sensitive to reciprocity. + 

They will give you a piece, but if they don't get a piece in return within a certain period of time, they lose trust and will disengage. + 

This can often seem to come out of nowhere. + 

But remember, since they like working on things alone, the fact that they are talking to you at all is from their perspective a concession. + 

They will often view concessions by their counterpart as a new piece of information to be taken back and evaluated. + 

Don't expect immediate counterproposals from them. + 

People like this are skeptical by nature. + 

So asking too many questions to start is a bad idea because they're not going to want to answer until they understand all the implications. + 

With them, it's vital to be prepared. + 

Use clear data to drive your reason. + 

Don't add lib. + 

Use data comparisons to disagree and focus on the facts. + 

Warn them of issues early and avoid surprises. + 

Silence to them is an opportunity to think. + 

They're not mad at you and they're not trying to give you a chance to talk more. + 

If you feel they don't see things the way you do, give them a chance to think first. + 

Apologies have little value to them since they see the negotiation and their relationship with you as a person largely as separate things. + 

They respond fairly well in the moment to labels. + 

They are not quick to answer calibrated questions or closedended questions when the answer is yes. + 

They may need a few days to respond. + 

If you're an analyst, you should be worried about cutting yourself off from an essential source of data, your counterpart. + 

The single biggest thing you can do is to smile when you speak. + 

People will be more forthcoming with information to you as a result. + 

Smiling can also become a habit that makes it easy for you to mask any moments you've been caught off guard. + 

Accommodator. + 

The most important thing to this type of negotiator is the time spent building the relationship. + 

Accommodators think as long as there is a free flowing continuous exchange of information, time is being well spent. + 

As long as they're communicating, they're happy. + 

Their goal is to be on great terms with their counterpart. + 

They love the win-win. + 

Of the three types, they are most likely to build great rapport without actually accomplishing anything. + 

Accommodators want to remain friends with their counterpart even if they can't reach an agreement. + 

They are very easy to talk to, extremely friendly, and have pleasant voices. + 

They will yield a concession to appease or acquies and hope the other side reciprocates. + 

If your counterparts are sociable, peace-seeking, optimistic, distractable, and poor time managers, they're probably accommodators. + 

If they're your counterpart, be sociable and friendly. + 

Listen to them talk about their ideas and use calibrated questions focused specifically on implementation to nudge them along and find ways to translate their talk into action. + 

Due to their tendency to be the first to activate the reciprocity cycle, they may have agreed to give you something they can't actually deliver. + 

Their approach to preparation can be lacking as they are much more focused on the person behind the table. + 

They want to get to know you. + 

They have a tremendous passion for the spirit of negotiation and what it takes not only to manage emotions but also to satisfy them. + 

While it is very easy to disagree with an accommodator because they want nothing more than to hear what you have to say, uncovering their objections can be difficult. + 

They will have identified potential problem areas beforehand and will leave those areas unressed out of fear of the conflict they may cause. + 

If you have identified yourself as an accommodator, stick to your ability to be very likable, but do not sacrifice your objections. + 

Not only do the other two types need to hear your point of view, if you are dealing with another accommodator, they will welcome it. + 

Also, be conscious of excess chitchat. + 

The other two types have no use for it. + 

And if you're sitting across the table from someone like yourself, you will be prone to interactions where nothing gets done. + 

Assertive. + 

The assertive type believes time is money. + 

Every wasted minute is a wasted dollar. + 

Their self-image is linked to how many things they can get accomplished in a period of time. + 

For them, getting the solution perfect isn't as important as getting it done. + 

Assertives are fiery people who love winning above all else, often at the expense of others. + 

Their colleagues and counterparts never question where they stand because they are always direct and candid. + 

They have an aggressive communication style and they don't worry about future interactions. + 

Their view of business relationships is based on respect, nothing more and nothing less. + 

Most of all, the assertive wants to be heard. + 

And not only do they want to be heard, but they don't actually have the ability to listen to you until they know that you've heard them. + 

They focus on their own goals rather than people, and they tell rather than ask. + 

When you're dealing with assertive types, it's best to focus on what they have to say. + 

Because once they are convinced you understand them, then and only then will they listen for your point of view. + 

To an assertive, every silence is an opportunity to speak more. + 

Mirrors are a wonderful tool with this type. + 

So are calibrated questions, labels, and summaries. + 

The most important thing to get from an assertive will be a that's right that may come in the form of that's it exactly or you hit it on the head. + 

When it comes to reciprocity, this type is of the give an inch take a mile mentality. + 

They will have figured they deserve whatever you have given them. + 

So they will be oblivious to expectations of owing something in return. + 

They will actually simply be looking for the opportunity to receive more. + 

If they have given some kind of concession, they are surely counting the seconds until they get something in return. + 

If you are an assertive, be particularly conscious of your tone. + 

You will not intend to be overly harsh, but you will often come off that way. + 

Intentionally soften your tone and work to make it more pleasant. + 

Use calibrated questions and labels with your counterpart since that will also make you more approachable and increase the chances for collaboration. + 

We've seen how each of these groups views the importance of time differently. + 

Time equals preparation. + 

Time equals relationship. + 

Time equals money. + 

They also have completely different interpretations of silence. + 

I'm definitely an assertive. + 

And at a conference, this accommodator type told me that he blew up a deal. + 

I thought, what did you do? Scream at the other guy and leave? Because that's me blowing up a deal. + 

But it turned out that he went silent. + 

For an accommodator type, silence is anger. + 

For analysts though, silence means they want to think. + 

And assertive types interpret your silence as either you don't have anything to say or you want them to talk. + 

I'm one, so I know the only time I'm silent is when I've run out of things to say. + 

The funny thing is when these cross over, when an analyst pauses to think, their accommodator counterpart gets nervous and an assertive one starts talking, thereby annoying the analyst who thinks to herself, "Every time I try to think, you take that as an opportunity to talk some more. + 

Won't you ever shut up?" Before we move on, I want to talk about why people often fail to identify their counterpart style. + 

The greatest obstacle to accurately identifying someone else's style is what I call the I am normal paradox. + 

That is our hypothesis that the world should look to others as it looks to us. + 

After all, who wouldn't make that assumption? But while innocent and understandable, thinking you're normal is one of the most damaging assumptions in negotiations. + 

With it, we unconsciously project our own style on the other side. + 

But with three types of negotiators in the world, there's a 66% chance your counterpart has a different style than yours, a different normal. + 

A CEO once told me he expected nine of 10 negotiations to fail. + 

This CEO was likely projecting his beliefs onto the other side. + 

In reality, he probably only matched with someone like-minded one of 10 times. + 

If he understood that his counterpart was different from him, he would most surely have increased his success rate. + 

From the way they prepare to the way they engage in dialogue, the three types negotiate differently. + 

So before you can even think about bargaining effectively, you have to understand your counterparts normal. + 

You have to identify their type by opening yourself to their difference. + 

Because when it comes to negotiating, the golden rule is wrong. + 

The black swan rule is don't treat others the way you want to be treated. + 

Treat them the way they need to be treated. + 

I've got a complimentary PDF available that will help you identify your type and that of those around you. + 

Please visit info.blackswanltd.com. + 

Three types. + 

Taking a punch. + 

Negotiation. + 

Academics like to treat bargaining as a rational process devoid of emotion. + 

They talk about the zopa or zone of possible agreement, which is where the sellers and buyer zones cross. + 

Say Tony wants to sell his car and won't take less than $5,000. + 

And Samantha wants to buy but won't pay more than $6,000. + 

The zopa runs from $5,000 to $6,000. + 

Some deals have zas and some don't. + 

It's all very rational. + 

Or so they'd have you think. + 

You need to disabuse yourself of that notion. + 

In a real bargaining session, kick-ass negotiators don't use ZOPA. + 

Experienced negotiators often lead with a ridiculous offer, an extreme anchor. + 

And if you're not prepared to handle it, you'll lose your moorings and immediately go to your maximum. + 

It's human nature. + 

Like the great earbiting pugilist Mike Tyson once said, "Everybody has a plan until they get punched in the mouth." As a well-prepared negotiator who seeks information and gathers it relentlessly, you're actually going to want the other guy to name a price first because you want to see his hand. + 

You're going to welcome the extreme anchor. + 

But extreme anchoring is powerful and you're human. + 

Your emotions may well up. + 

If they do, there are ways to weather the storm without bidding against yourself or responding with anger. + 

Once you learn these tactics, you'll be prepared to withstand the hit and counter with panache. + 

First, deflect the punch in a way that opens up your counterpart. + 

Successful negotiators often say no in one of the many ways we've talked about, "How am I supposed to accept that?" or deflect the anchor with questions like, "What are we trying to accomplish here? Responses like these are great ways to refocus your counterpart when you feel you're being pulled into the compromise trap. + 

You can also respond to a punch in the face anchor by simply pivoting to terms. + 

What I mean by this is that when you feel you're being dragged into a haggle, you can detour the conversation to the non-monetary issues that make any final price work. + 

You can do this directly by saying in an encouraging tone of voice, "Let's put price off to the side for a moment and talk about what would make this a good deal." Or you could go at it more obliquely by asking, "What else would you be able to offer to make that a good price for me?" And if the other side pushes you to go first, wrigle from his grip. + 

Instead of naming a price, allude to an incredibly high number that someone else might charge. + 

Once when a hospital chain wanted me to name a price first, I said, "Well, if you go to Harvard Business School, they're going to charge you $2500 a day per student." No matter what happens, the point here is to sponge up information from your counterpart. + 

Letting your counterpart anchor first will give you a tremendous feel for him. + 

All you need to learn is how to take the first punch. + 

One of my Georgetown MBA students, a guy named Farooq, showed how not to fold after being punched when he went to hit up the MBA dean for funds to hold a big alumni event in Dubai. + 

It was a desperate situation because he needed $600 and she was his last stop. + 

At the meeting, Farooq told the dean about how excited the students were about the trip and how beneficial it would be for the Georgetown MBA brand in the region. + 

Before he could even finish, the dean jumped in. + 

"Sounds like a great trip you guys are planning," she said. + 

"But money is tight, and I could authorize no more than $300." Farooq hadn't expected the dean to go so quickly, but things don't always go according to plan. + 

That is a very generous offer given your budget limits, but I am not sure how that would help us achieve a great reception for the alums in the region, Farooq said, acknowledging her limits, but saying no without using the word. + 

Then he dropped an extreme anchor. + 

I have a very high amount in my head. + 

$1,000 is what we need. + 

As expected, the extreme anchor quickly knocked the dean off her limit. + 

That is severely out of my range and I am sure I can't authorize that. + 

However, I will give you $500. + 

Farooq was half tempted to fold. + 

Being 100 short wasn't make or break, but he remembered the curse of aiming low. + 

He decided to push forward. + 

The 500 got him closer to the goal, but not quite there. + 

He said 850 would work. + 

The dean replied by saying that she was already giving more than what she wanted and 500 was reasonable. + 

At this point, if Farooq had been less prepared, he would have given up. + 

But he was ready for the punches. + 

I think your offer is very reasonable, and I understand your restrictions. + 

But I need more money to put on a great show for the school, he said. + 

How about 775? The dean smiled, and Farooq knew he had her. + 

You seem to have a specific number in your head that you are trying to get to, she said. + 

Just tell it to me. + 

At that point, Farooq was happy to give her his number as he felt she was sincere. + 

I need $73750 to make this work and you are my last stop, he said. + 

She laughed. + 

The dean then praised him for knowing what he wanted and said she'd check her budget. + 

2 days later, Farooq got an email saying her office would put in $750, punching back using assertion without getting used by it. + 

When a negotiation is far from resolution and going nowhere fast, you need to shake things up and get your counterpart out of their rigid mindset. + 

In times like this, strong moves can be enormously effective tools. + 

Sometimes a situation simply calls for you to be the aggressor and punch the other side in the face. + 

That said, if you are basically a nice person, it will be a real stretch to hit the other guy like Mike Tyson. + 

You can't be what you're not. + 

As the Danish folk saying goes, you bake with the flower you have, but anyone can learn a few tools. + 

Here are effective ways to assert smartly. + 

real anger, threats without anger, and strategic umbrage. + 

Marwan Sonaser of INSAD and Stanford University's Lissa Titans found that expressions of anger increase a negotiator's advantage and final take. + 

Two, anger shows passion and conviction that can help sway the other side to accept less. + 

However, by heightening your counterparts sensitivity to danger and fear, your anger reduces the resources they have for other cognitive activity, setting them up to make bad concessions that will likely lead to implementation problems, thus reducing your gains. + 

Also, beware. + 

Researchers have also found that disingenuous expressions of unfelt anger, you know, faking it, backfire, leading to intractable demands and destroying trust. + 

For anger to be effective, it has to be real. + 

The key for it is to be under control. + 

Because anger also reduces our cognitive ability. + 

And so when someone puts out a ridiculous offer, one that really pisses you off, take a deep breath, allow little anger, and channel it at the proposal, not the person, and say, "I don't see how that would ever work." Such well-timed offense taking known as strategic umbrage can wake your counterpart to the problem. + 

In studies by Columbia University academics Daniel Ames and Abby Wlawek, people on the receiving end of strategic umbrage were more likely to rate themselves as over assertive even when the counterpart didn't think so. + 

The real lesson here is being aware of how this might be used on you. + 

Please don't allow yourself to fall victim to strategic umbrage. + 

Threats delivered without anger, but with poise, that is confidence and self-control, are great tools. + 

Saying, "I'm sorry, that just doesn't work for me with poise works. + 

Why questions?" Back in chapter 7, I talked about the problems with why. + 

Across our planet and around the universe, why makes people defensive. + 

As an experiment, the next time your boss wants something done, ask him or her why and watch what happens. + 

Then try it with a peer, a subordinate, and a friend. + 

Observe their reactions and tell me if you don't find some level of defensiveness across the spectrum. + 

Don't do this too much though where you'll lose your job and all your friends. + 

The only time I say why did you do that in a negotiation is when I want to knock someone back. + 

It's an iffy technique though and I wouldn't advocate it. + 

There is however another way to use why effectively. + 

The idea is to employ the defensiveness the question triggers to get your counterpart to defend your position. + 

I know it sounds weird, but it works. + 

The basic format goes like this. + 

When you want to flip a dubious counterpart to your side, ask them, "Why would you do that?" But in a way that the that favors you. + 

Let me explain. + 

If you are working to lure a client away from a competitor, you might say, "Why would you ever do business with me? Why would you ever change from your existing supplier? They're great." In these questions, the why coaxes your counterpart into working for you. + 

I messages. + 

Using the first person singular pronoun is another great way to set a boundary without escalating into confrontation. + 

When you say, "I'm sorry, that doesn't work for me." The word I strategically focuses your counterpart's attention onto you long enough for you to make a point. + 

The traditional IM message is to use I to hit the pause button and step out of a bad dynamic. + 

When you want to counteract unproductive statements from your counterpart, you can say I feel when you because and that demands a timeout from the other person. + 

But be careful with the big eye. + 

You have to be mindful not to use a tone that is aggressive or creates an argument. + 

It's got to be cool and level. + 

No neediness. + 

Having the ready to walk mindset. + 

We've said previously that no deal is better than a bad deal. + 

If you feel you can't say no, then you've taken yourself hostage. + 

Once you're clear on what your bottom line is, you have to be willing to walk away. + 

Never be needy for a deal. + 

Before we move on, I want to emphasize how important it is to maintain a collaborative relationship. + 

Even when you're setting boundaries, your response must always be expressed in the form of strong yet empathetic limit setting boundaries. + 

That is tough love, not as hatred or violence. + 

Anger and other strong emotions can on rare occasions be effective, but only as calculated acts, never a personal attack. + 

In any bare knuckle bargaining session, the most vital principle to keep in mind is never to look at your counterpart as an enemy. + 

The person across the table is never the problem. + 

The unsolved issue is. + 

So focus on the issue. + 

This is one of the most basic tactics for avoiding emotional escalations. + 

Our culture demonizes people in movies and politics which creates the mentality that if we only got rid of the person, then everything would be okay. + 

But this dynamic is toxic to any negotiation. + 

Punching back is a last resort. + 

Before you go there, I always suggest an attempt at deescalating the situation. + 

Suggest a timeout. + 

When your counterparts step back and take a breath, they'll no longer feel that they are hostage to a bad situation. + 

They'll regain a sense of agency and power, and they'll appreciate you for that. + 

Think of punching back and boundary setting tactics as a flattened scurve. + 

You've accelerated up the slope of a negotiation and hit a plateau that requires you to temporarily stop any progress, escalate or deescalate the issue, acting as the obstacle, and eventually bring the relationship back to a state of rapport and get back on the slope. + 

Taking a positive, constructive approach to conflict involves understanding that the bond is fundamental to any resolution. + 

Never create an enemy. + 

Aurman bargaining. + 

I've spent a lot of time talking about the psychological judo that I've made my stock in trade. + 

The calibrated questions, the mirrors, the tools for knocking my counterpart off his game and getting him to bid against himself. + 

But negotiation still comes down to determining who gets which slice of the pie. + 

And from time to time, you're going to be forced into some real bare knuckle bargaining with a hard ass haggler. + 

I faced bare- knuckle bargaining all the time in the hostage world. + 

I haggled with a lot of guys who stuck to their game plan and were used to getting their way. + 

Pay or will kill, they'd say, and they meant it. + 

You had to have your skills drumtight to negotiate them down. + 

You need tools. + 

Back at FBI negotiation training, I learned the haggling system that I use to this day, and I swear by it. + 

I call the system the Acriman model because it came from this guy Mike Acriman, an ex CIA type who founded a kidnap for ransom consulting company based out of Miami. + 

On many kidnappings, we'd constantly be paired with Acriman guys, never Mike himself, who helped design the haggle. + 

After I retired from the FBI, I finally met Mike on a trip to Miami. + 

When I told him I also use the system for business negotiations, he laughed and said he'd run the system by Howard Rafa, a legendary Harvard negotiation guy. + 

And Howard had said it would work in any situation. + 

So I felt pretty justified by that. + 

The Acriman model is an offer counter offer method, at least on the surface, but it is a very effective system for beating the usual lackluster bargaining dynamic which has the predictable result of meeting in the middle. + 

The systematized and easy to remember process has only four steps. + 

One, set your target price, your goal. + 

Two, set your first offer at 65% of your target price. + 

Three, calculate three raises of decreasing increments to 85, 95, and 100%. + 

Four, use lots of empathy and different ways of saying no to get the other side to counter before you increase your offer. + 

Five, when calculating the final amount, use precise non-round numbers like say $37,893 rather than $38,000. + 

It gives the number credibility and weight. + 

Six. + 

On your final number, throw in a non-monetary item that they probably don't want to show you're at your limit. + 

The genius of this system is that it incorporates the psychological tactics we've discussed: reciprocity, extreme anchors, loss aversion, and so on without you needing to think about them. + 

If you'll bear with me for a moment, I'll go over the steps so you see what I mean. + 

First, the original offer of 65% of your target price will set an extreme anchor, a big slap in the face that might bring your counterpart right to their price limit. + 

The shock of an extreme anchor will induce a fightor-flight reaction in all but the most experienced negotiators, limiting their cognitive abilities and pushing them into rash action. + 

Now, look at the progressive offer increases to 85, 95, and 100% of the target price. + 

You're going to drop these in sparingly after the counterpart has made another offer on their end and after you've thrown out a few calibrated questions to see if you can bait them into bidding against themselves. + 

When you make these offers, they work on various levels. + 

First, they play on the norm of reciprocity. + 

They inspire your counterpart to make a concession, too. + 

Just like people are more likely to send Christmas cards to people who first send cards to them, they are more likely to make bargaining concessions to those who have made compromises in their direction. + 

Second, the diminishing size of the increases, notice that they decrease by half each time, convinces your counterpart that he's squeezing you to the point of breaking. + 

By the time they get to the last one, they'll feel that they've really gotten every last drop. + 

This really juices their self-esteem. + 

Researchers have found that people getting concessions often feel better about the bargaining process than those who are given a single firm fair offer. + 

In fact, they feel better even when they end up paying more or receiving less than they otherwise might. + 

Finally, the power of non-round numbers bears reiterating. + 

Back in Haiti, I used to use the Acriman system ferociously. + 

Over 18 months, we got two or three kidnappings a week. + 

So, from experience, we knew the market prices were $15,000 to $75,000 per victim. + 

Because I was a hard ass, I made it my goal to get in under $5,000 in every kidnapping that I ran. + 

One really stands out, the first one I mentioned in this book. + 

I went through the acriman process, knocking them off their game with an extreme anchor, hitting them with calibrated questions and slowly gave progressively smaller concessions. + 

Finally, I dropped the weird number that closed the deal. + 

I'll never forget the head of the Miami FBI office calling my colleague the next day and saying, "Vos got this guy out for $4,751. + 

How does one make a difference?" They were howling with laughter and they had a point. + 

That $1 is ridiculous, but it works on our human nature. + 

Notice that you can't buy anything for $2, but you can buy a million things for $1.99. + 

How does a scent change anything? It doesn't, but it makes a difference every time. + 

We just like $1.99 more than $200, even if we know it's a trick. + 

negotiating a rent cut after receiving notice of an increase. + 

Eight months after a Georgetown MBA student of mine named Mishiri signed a rental contract for $1,850 a month, he got some unwelcome news. + 

His landlord informed him that if he wanted to reup, it would be $2,100 a month for 10 months or $2,000 a month for a year. + 

Mishiri loved the place and didn't think he'd find a better one. + 

But the price was already high and he couldn't afford more. + 

Taking to heart our class slogan, you fall to your highest level of preparation, he dove into the real estate listings and found that prices for comparable apartments were $1,800 to $1950 a month, but none of them were in as good a building. + 

He then examined his own finances and figured the rent he wanted to pay was $1830. + 

He requested a sit down with his rental agent. + 

This was going to be tough. + 

At their meeting, Mishari laid out his situation. + 

His experience in the building had been really positive, he said, and he pointed out he always paid on time. + 

It would be sad for him to leave, he said, and sad for the landlord to lose a good tenant. + 

The agent nodded. + 

Totally in agreement, he said. + 

That's why I think it will benefit both of us to agree on renewing the lease. + 

Here, Mishari pulled out his research. + 

Buildings around the neighborhood were offering much lower prices, he said. + 

Even though your building is better in terms of location and services, how am I supposed to pay $200 extra? The negotiation was on. + 

The agent went silent for a few moments and then said, "You make a good point, but this is still a good price, and as you noted, we can charge a premium." Misher then dropped an extreme anchor. + 

"I fully understand, you do have a better location and amenities, but I'm sorry, I just can't," he said. + 

"Would $1,730 a month for a year lease sound fair to you?" The agent laughed and when he finished said there was no way to accept that number because it was way below market price. + 

Instead of getting pulled into a haggle, Missy smartly pivoted to calibrated questions. + 

Okay, so please help me understand how do you price lease renewals? The agent didn't say anything shocking, merely that they used factors like area prices and supply and demand. + 

But that gave Misher the opening to argue that his leaving would open the landlord to the risk of having an unrened apartment and the cost of repainting. + 

One month unrened would be a $2,000 loss, he said. + 

Then he made another offer. + 

Now, you're probably shaking your head that he's making two offers without receiving one in return. + 

And you're right, normally that's verboten, but you have to be able to improvise. + 

If you feel in control of a negotiation, you can do two or three moves at a time. + 

Don't let the rules ruin the flow. + 

Let me try and move along with you. + 

How about 1790 for 12 months? The agent paused. + 

Sir, I understand your concerns and what you said makes sense. + 

He said, your number though is very low. + 

However, give me time to think this out and we can meet at another time. + 

How does that sound? Remember, any response that is not an outright rejection means you have the edge. + 

5 days later, the two met again. + 

I ran the numbers and believe me, this is a good deal, the agent started. + 

I am able to offer you $1,950 a month for a year. + 

Mishari knew he'd won. + 

The agent just needed a little push. + 

So, he praised the agent and said no without saying no. + 

And notice how he brilliantly mislabels in order to get the guy to open up. + 

That is generous of you. + 

But how am I supposed to accept it when I can move a few blocks away and stay for $1,800? $150 a month means a lot to me. + 

You know, I am a student. + 

I don't know. + 

It seems like you would rather run the risk of keeping the place unrened. + 

It's not that the agent answered, but I can't give you a number lower than the market. + 

Misher made a dramatic pause as if the agent was extracting every cent he had. + 

Then I tell you what, I initially went up from $1,730 to $1,790, he said, sighing. + 

I will bring it up to $1,810 and I think this works well for both. + 

The agent shook his head. + 

This is still lower than the market, sir, and I cannot do that. + 

Misher then prepared to give the last of his acriman offers. + 

He went silent for a while and then asked the agent for a pen and paper. + 

Then he started doing fake calculations to seem like he was really pushing himself. + 

Finally, he's looked up at the agent and said, "I did some numbers, and the maximum I can afford is $1,829." Warm. + 

The agent bobbed his head from side to side as if getting his mind around the offer. + 

At last, he spoke. + 

"Wow, $1,829," he said. + 

"You seem very precise. + 

You must be an accountant." Mishari was not. + 

Listen, I value you wanting to renew with us. + 

And for that, I think we can make this work for a 12-month lease. + 

Kaching. + 

Notice this brilliant combination of decreasing acrement offers, non-round numbers, deep research, smart labeling, and saying no without saying no. + 

That's what gets you a rent discount when a landlord wanted to raise his monthly take. + 

Key lessons. + 

When push comes to shove, and it will, you're going to find yourself sitting across the table from a bare knuckle negotiator. + 

After you finished all the psychologically nuanced stuff, the labeling and mirroring and calibrating, you are going to have to hash out the brass tax. + 

For most of us, that ain't fun. + 

Top negotiators know, however, that conflict is often the path to great deals, and the best find ways to actually have fun engaging in it. + 

Conflict brings out truth, creativity, and resolution. + 

So, the next time you find yourself face to face with a bare knuckle bargainer, remember the lessons in this chapter. + 

Identify your counterparts negotiating style. + 

Once you know whether they are accommodator, assertive, or analyst, you'll know the correct way to approach them. + 

Prepare, prepare, prepare. + 

When the pressure is on, you don't rise to the occasion. + 

You fall to your highest level of preparation. + 

So, design an ambitious but legitimate goal and then game out the labels, calibrated questions, and responses you'll use to get there. + 

That way, once you're at the bargaining table, you won't have to wing it. + 

Get ready to take a punch. + 

Kick-ass negotiators usually lead with an extreme anchor to knock you off your game. + 

If you're not ready, you'll flee to your maximum without a fight. + 

So, prepare your dodging tactics to avoid getting sucked into the compromise trap. + 

Set boundaries and learn to take a punch or punch back without anger. + 

The guy across the table is not the problem. + 

the situation is. + 

Prepare an acriman plan. + 

Before you head into the weeds of bargaining, you'll need a plan of extreme anchor, calibrated questions, and well-defined offers. + 

Remember, 65, 85, 95, 100%. + 

Decreasing raises and ending on non-round numbers will get your counterpart to believe that he's squeezing you for all you're worth when you're really getting to the number you want. + 

[Music]

'''