
= 2012年
:toc:

---

== 2012-1


Come on ——Everybody’s doing it. 主 That whispered(`=to speak very quietly to sb`) message, half invitation and half forcing, 谓 *is* what most of us *think of* [when we *hear* the words 同位 peer 同辈；身份(或地位)相同的人 pressure]. 

It(就是指"Come on ——Everybody’s doing it."这句话) usually *leads to* no good-drinking, drugs and casual 漫不经心的;(故作)随意的 sex. 

But in her new book _Join the Club_, Tina Rosenberg *contends*(`=to say that sth is true, especially in an argument`) that {peer pressure *can also be* a positive force [through 通过；凭借 what she *calls* the social cure 治愈,治好, in which organizations and officials 行政官员 *use* the power of group dynamics 团体动态,集体动态 *to help* individuals *improve* their lives and possibly the world]}.
====
- dynamic : dynamics [ pl. ] *the way in which people or things behave and react to each other* in a particular situation (人或事物)相互作用的方式,动态 +
-> the dynamics of political change 政治变化动态
====

得了吧, 每个人都这样啊.  这种说法一半是邀请,一半是强制。当我们听到“同辈(趋同)压力”这个词组的时候, 我们想到的就是这种说法。这种信息一般让人想到不好的事情,比如喝酒,吸毒,一夜情。 +
但是,在她的新书《加入俱乐部》中,Tina Rosenberg 认为,同侪压力也是一种积极的力量,通过她所称的社会治疗,各机构和官员可以使用群体力量去帮助个人改善生活,甚至可能改变世界。

Rosenberg, the recipient 接受者；领受人 of a Pulitzer Prize 普利策奖, *offers* a host(`=a large number of sth`) of example of the social cure (in action 在运转, 在操作):  +
① In South Carolina, a state-sponsored 赞助,资助 antismoking program (*called* Rage(`=to show that you are very angry about sth or with sb`) Against the Haze(阴)霾;雾霭,雾状物) *sets out* 开始;着手 to make cigarettes uncool 不“酷”的.  +
② In South Africa, an HIV-prevention initiative(n.)(`=an important act or statement that is intended to solve a problem`) (*known as* LoveLife) *recruits* 招募；征召 young people *to promote*(`=to help sth to happen or develop`) safe sex among their peers.
====
- initiative 倡议；新方案 => it=go,表示"行走"。initiative a 起步的 n. 原动力(initiate 开始+ive)
====

Rosenberg是普利策奖获得者,他提供了许多社会治疗的例子：在南卡罗莱纳州,一个州资助的反对抽烟的项目叫做“向烟雾宣战”, 就旨在控制好烟草销售。在南非,预防HIV,即众所周知的“热爱生命”活动, 要求年轻人要安全性生活。

The idea *seems* promising 大有希望的；很有前途的；前景很好的,and Rosenberg is a perceptive(`=having or showing the ability to see or understand things quickly, especially things that are not obvious`) observer 观察者. 

Her(指Rosenberg) critique (n.)评论;评论文章 of the lameness 跛,残废 of many pubic-health campaigns 系 *is* spot-on(`=absolutely correct; very accurate`): they *fail to mobilize* 动员;鼓动,(人们)动员起来 peer pressure *for* healthy habits, and they *demonstrate*(`= to show by your actions that you have a particular quality, feeling or opinion`) a seriously flawed understanding of psychology 心理学.” 

这个观点似乎很有希望,而且Rosenberg是个敏锐的观察家。她对于许多公共健康活动缺点的批评是中肯的：他们没能动员同辈压力来建立健康的习惯,他们展示的是对心理学的严重误解。

*Dare* to be different, please don’t smoke!” *pleads* 恳求；请求 one billboard 广告牌；布告栏 campaign (*aimed at* reducing smoking among teenagers) —— teenagers, who *desire* nothing *more than* fitting in.  +
Rosenberg *argues(`=to give reasons why you think that sth is right/wrong`) convincingly* 令人信服地；有说服力地 that {public-health advocates *ought to* take a page 效仿榜样 from advertisers, so skilled 熟练的；有技能的 at *applying* 应用;运用 peer pressure}.
====
- “Dare to be different, please don’t smoke!”*pleads*(v.) one billboard campaign aimed at... 这是一个倒装句，自然语序为 one billboard campaign… *pleads*(v.), “Dare to be different, please don’t smoke!” 由于该句中修饰主语的后置定语(aimed at...)过长，故将谓语pleads前置, 形成主谓倒装.  +
引号内的内容(Dare to be...)为直接引语，充当pleads的宾语。 +
破折号后的内容是破折号前teenagers的同位语，对其进行解释说明。

- fit in : PHRASAL VERB If you *fit in* as part of a group, *you seem to belong there because you are similar to the other people in it*. 相处融洽
====

一个旨在在青少年中禁烟的广告牌写着：“就敢与众不同,请勿吸烟！” 青少年最渴望的是融入群体。Rosenberg认为,公共健康建议应该效仿广告商,广告商懂得如何应用同辈压力。

But on the general 广泛的；普遍的 effectiveness 效力 of the social cure, Rosenberg *is* less persuasive 有说服力的；令人信服的. Join the Club ① *is filled with* too much irrelevant(`=not important to or connected with a situation`) detail and ② not enough exploration 考察, 探索 of the social and biological factors (that *make* peer pressure(n.) *so* powerful). 

The most glaring(`=very easily seen`) flaw of the social cure [*as* it’s *presented* here] 系 *is* that {it *doesn’t work very well* for very long}.  +
_Rage Against the Haze_ 书名 *failed* [once state funding(n.)(`=money for a particular purpose`) *was cut*].  +
Evidence (that _the LoveLife program_ *produces* 产生；引起；造成 lasting changes) 系 *is* limited and mixed(`=consisting of different types of the same thing`).

但对于社会治疗的广泛效果,Rosenberg就没有那么有说服力了。《加入俱乐部》一书写了太多无关细节,没有认真探讨社会和生物因素,这些因素能使同辈压力变得很有影响力。这里说的社会治疗的明显缺点是,它有效期不长。一旦资金来源消失,那么“向烟雾宣战”的活动就会失败。“热爱生命”活动能产生持久的影响这种说法的证据不足。

There’s no doubt that our peer groups *exert*(`=to use power or influence to affect sb/sth`) enormous influence *on* our behavior.  +
An emerging 新兴的；出现的；形成的 body(`=a large amount or collection of sth`) of research *shows* that {positive health habits —— as well as negative ones —— *spread* through 通过；凭借 networks of friends [*via*(`=by means of`) social communication]}.  + 
This is a subtle(`= not very noticeable or obvious`) form of peer pressure: we unconsciously *imitate* 模仿;仿效;模拟 the behavior we see every day.
====
- through networks of friends 和 via social communication 都是方式状语,表示“通过……的方式”。
====

毫无疑问,我们的同龄人会对我们的行为产生巨大影响。研究显示,积极的健康习惯,以及负面的习惯,会通过社会交流在朋友之间传播。这是同辈压力的一种微妙的形式：我们会无意识模仿我们每天看到的行为。

Far less 远远比不上,大大小于 certain 很难确定的是, however, *is* 表 how successfully experts and bureaucrats 官僚；官僚主义者 *can select* our peer groups /and *steer* 驾驶, 掌舵；引导,指导(某人采取某种行动或态度) their activities [in virtuous(`=behaving in a very good and moral way`) directions].  

但是,很难确定的是,专家和官员能否成功选择我们的同辈,控制好他们的行为能在道德的道路上发展。

It’s like the teacher who *breaks up* (使)分裂；(被)拆分 the troublemakers 捣乱分子 in the back row [by *pairing* 使配对 them *with* better-behaved classmates]. The tactic 战术;策略;招数 never *really works*.  +
And that’s the problem with a social cure (*engineered*(`=to design and build sth`) from the outside): in the real world, as in school, we *insist 坚持;坚决认为(或主张、要求) on* choosing our own friends.

这就像老师,通过让问题学生和好学生坐在一起的方法,让后排学生不要凑在一起胡闹。这种方法从来就没有什么收效。这就是从外界设计出的社会治疗会产生问题所在：在真实的社会里,正如在学校,我们坚持会选择自己的朋友。


---

== 2012-1 纯净版

Come on -- Everybody’s doing it. ② `主` That whispered message, half invitation and half forcing, `系` *is* what most of us *think of* [when we *hear* the words peer pressure]. ③ It usually *leads to* no good-drinking, drugs and casual sex. ③ But in her new book Join the Club, `主` Tina Rosenberg `谓` *contends* that {peer pressure *can also be* a positive force [*through* what she *calls* the social cure], in which organizations and officials *use* the power of group dynamics *to help* individuals *improve* their lives and possibly the word}.

Rosenberg, the recipient of a Pulitzer Prize, *offers* a host of example of the social cure (in action): In South Carolina, `主` a state-sponsored antismoking program (*called* Rage Against the Haze) *sets out to make* cigarettes uncool. ② In South Africa, an HIV-prevention initiative (*known as* LoveLife) *recruits* young people *to promote* safe sex among their peers.

The idea *seems* promising，and Rosenberg *is* a perceptive observer. ② Her critique (of the lameness of many pubic-health campaigns) *is* `表` spot-on: they *fail to mobilize* peer pressure *for* healthy habits, and they *demonstrate* a seriously flawed understanding of psychology.” ③ *Dare* to be different, please don’t smoke!” *pleads* one billboard campaign *aimed at* reducing smoking *among* teenagers-teenagers, who *desire* nothing more than *fitting in*. ④ Rosenberg *argues convincingly* that {public-health advocates *ought to take a page from* advertisers, so skilled at *applying* peer pressure}.

But [on the general effectiveness of the social cure], Rosenberg *is* less persuasive. ② `主` Join the Club `谓` *is filled with* too much irrelevant detail /and *not* enough exploration of the social and biological factors (that *make* peer pressure so powerful). ③ `主` The most glaring flaw of the social cure *as* it’s presented here `系` *is* that {it *doesn’t work very well* for very long}. ④ Rage Against the Haze *failed* [once state funding *was cut*]. ⑤ `主` Evidence (that the LoveLife program *produces* lasting changes) `系` *is* limited and mixed.

There’s no doubt that {our peer groups *exert* enormous influence *on* our behavior}. ② An emerging body of research *shows* that {positive health habits -- as well as negative ones -- *spread through* networks of friends [*via* social communication]}. ③ This is a subtle form of peer pressure: we *unconsciously imitate* the behavior (we see every day).

`主` Far less certain, however, `系` *is* {how successfully experts and bureaucrats *can select* our peer groups /and *steer* their activities *in virtuous directions*}. ② It’s like the teacher (who *breaks up* the troublemakers (in the back row) by *pairing* them *with* better-behaved classmates). ③ The tactic *never really works*. ④ And that’s the problem *with* a social cure engineered *from* the outside: in the real world, as in school, we *insist on* choosing our own friends.

---

== 2012-2

A deal is a deal 交易就是交易,一言为定 —— *except*, apparently , when Entergy 公司名 *is involved*.  +
The company, a major energy supplier in New England, 谓 *provoked*(`=to cause a particular reaction`) justified(a.)(做…)有正当理由的 outrage(`=a strong feeling of shock and anger`) in Vermont last week [when it *announced* {it *was reneging(`=to break a promise`) on* a longstanding 长期存在的；由来已久的 commitment 承诺;许诺 (*to abide(`=to accept and act according to a law`) by* the strict nuclear regulations(`=an official rule`))}].
====
- 本句的骨架是: The company provoked(v.) outrage [when it announced ...]

- *renege (v.)~ (on sth)* : ( formal ) to break a promise, an agreement, etc. 违背(诺言)；背信弃义；食言  +
-> *to renege on a deal/debt/contract*, etc. 违背协定、赖债、违背合约等 +
=> neg=deny,表示"否认"

- *ABIDE BY STH* : to accept and act according to a law, an agreement, etc. 遵守,遵循(法律、协议、协定等)
====

承诺就是承诺 — 很明显,当Entergy公司牵涉在内的话就除外。这个公司是新英格兰主要的能源供应商,它曾承诺要一直遵守严格的核能源规范条例,但上周它宣布要违背这个承诺,理所当然地,它激起了佛蒙特州的义愤。  
 
Instead 作为替代;反而;相反地, the company *has done precisely* {what it *had long promised* it would not} : 同位 *challenge* the constitutionality 符合宪法;合宪性 of Vermont’s rules [in the federal court], *as* part of a desperate(a.)(因绝望而)孤注一掷的,铤而走险的,拼命的 effort (*to keep* its Vermont Yankee nuclear power plant 工厂,车间 *running*). It’s a stunning(`=extremely surprising or shocking`) move.

相反，这家公司的所作所为恰恰是它长期以来承诺不会做的事情——在联邦法院质疑佛蒙特州的各项规定是否符合宪法，这是它拼命保证佛蒙特扬基核电站能够运营所做的努力的一部分。这一举动令人震惊。
  
The conflict *has been surfacing* 升到水面;浮出水面 since 2002, when the corporation *bought* Vermont’s only nuclear power plant, an aging 老化 reactor 反应堆 in Vernon.  +
As a condition (尤指写入合同或法律的)条件,条款 of *receiving* state approval(`=agreement to, or permission for sth`) for the sale, the company *agreed* 宾 to seek permission from state regulators 管理者;调控者 *to operate* [past 2012].  +
In 2006, the state *went* a step [further], *requiring* 要求;命令 that {any extension 展期；延长期 of the plant’s license(`=to give sb official permission to do, own, or use sth`) *be subject(a.)受…支配的;服从于…的 to* Vermont legislature’s 立法机关；议会 approval}. Then, too, the company *went along*.

2002年公司购买了佛蒙特州唯一的核能源工厂,即位于弗农古老的核反应堆。自此,冲突开始浮出水面。公司同意2012年之后都会寻求本州调整者的许可,作为接受本州同意销售的条件。2006年,佛蒙特更进一步要求, 延长这一核工厂的许可证必须得到佛蒙特州立法机关的许可。公司也同意了。  
 
Either Entergy 公司名 never *really intended* 打算；想要 to live by those commitments 承诺;许诺, or it simply *didn’t foresee* 预见;预知;预料 what would happen next.  +
主 A string of(=a series of) accidents, *including* ① the partial 局部的；部分的 collapse of a cooling tower in 207 and ② the discovery of an underground pipe system leakage(n.)(液体或气) 泄漏,  谓 *raised* serious questions about both Vermont Yankee’s safety and Entergy’s management —— especially after the company *made misleading 误导性的；欺骗性的 statements 陈述,声明 about* the pipe.  +
*Enraged(`=to make sb very angry`) by* Entergy’s behavior, the Vermont Senate 参议院, 上院 *voted* 26 *to* 4 [last year] *against* allowing an extension.

Entergy可能不想真正地遵守这些承诺,或者简单来说, 它并没有预见将要发生的事情。一系列事故,如207冷却塔部分坍塌,发现地下管道系统漏泄,这些都引发了关于佛蒙特州美国人的安全,及Entergy公司经营等方面的严重问题 — 尤其在公司关于管道问题做了令人误解的声明之后。因Entergy的所作所为而震怒,去年佛蒙特州参议院以26:4的选票结果,反对允许延长它的许可证。   

Now the company *is suddenly claiming*(`=to say that sth is true although it has not been proved`) ① that {the 2002 agreement 协议；协定；协约 *is* invalid because of the 2006 legislation(`=a law`)}, and ② that {only the federal government *has* regulatory(a.)(对工商业)具有监管权的,监管的 power *over* nuclear issues}. 

The legal 法律(上)的 issues (in the case) *are* obscure(`=difficult to understand`): *whereas*(表示对比)但是,然而 the Supreme Court *has ruled* 判定;裁决 that 宾 {states do 的确 *have* some regulatory(a.) authority(`=the power or right`) *over* nuclear power}, legal scholars say that {Vermont case *will offer* a precedent-setting 先例 test of how far those powers *extend* 扩及;波及;包括}.  
====
- whereas : *used to compare or contrast two facts* （用以比较或对比两个事实）然而，但是，尽管 +
-> Some of the studies show positive results, *whereas* others do not. 有一些研究结果令人满意，*然而* 其他的则不然。
====

Certainly, there are valid(`=based on sensible reasoning`) concerns about the patchwork(a.)拼缀的；拼缝的 regulations(`=rules`) (that *could result*(`=to make sth happen`) [if every state *sets* its own rules]).  +
But *had* Entergy *kept its word*, (that debate 辩论,争论,讨论 *would be* beside the point 离题,不中肯；无关紧要).
====
- patchwork : ADJ A patchwork quilt, cushion, or piece of clothing *is made by sewing together small pieces of material of different colours or patterns*. 拼缝的
====

现在公司突然宣布,因2006法规2002协议无效,只有联邦政府才有权调控核事件。 +
这一案例中的法律问题模糊不清：最高法院曾宣布各州确实对核能源有调控权力,但法律学者认为,佛蒙特案件将验证这些权力到底有多大。 +
当然,如果每一个州都设定自己的法律条例,由此而导致的混乱,确实能引起合理的关注。但是如果Entergy信守诺言,那这场争论就偏离主题了。   

The company seems *to have concluded* that {its reputation (in Vermont) is already *so* damaged /*that* it *has nothing left to lose* by *going to war with* the state}.  But there should be consequences(`=a result of sth that has happened`).  

Permission (*to run* a nuclear plant) *is* a public trust. Entergy 公司名 *runs* 11 other reactors 反应堆 in the United States, *including* Pilgrim Nuclear station in Plymouth.  +
*Pledging(`=to formally promise to give or do sth`) to run* Pilgrim [safely(adv.)], the company *has applied for* 申请;请求 federal permission *to keep it open* for another 20 years.  +
But [*as* the Nuclear Regulatory Commission(委员会;调查团)核管理委员会(NRC) *reviews* 检查;审查 the company’s application申请,申请书], it *should keep it mind* 牢记;放在心上 {what promises 承诺,允诺 from Entergy *are* worth}.
====
- pledge :V-T When someone *pledges to do* something, *they promise in a serious way to do it*. When they *pledge* something, *they promise to give it*. 保证 (做某事); 保证给予 (某物)
====

公司似乎下了这样的论断：它在佛蒙特的声望已被损害,即使与佛蒙特州作战也没什么好失去的。但是这有一定的后果。 +
允许经营核工厂体现了公众的信任。在美国Entergy还经营了其他11个反应堆,包括普利茅斯的Pilgrim核电站。公司承诺安全经营Pilgrim,已向联邦提出申请,要求再经营20年。但是当核管理委员会审查了公司的申请时,应该记住Entergy的承诺能有什么样的价值。


---

== 2012-2 纯净版

A deal *is* a deal -- except, apparently , when Entergy *is involved*. ② `主` The company, a major energy supplier in New England, `谓` *provoked* justified outrage in Vermont last week [when it *announced* {it *was reneging on* a longstanding commitment (*to abide by* the strict nuclear regulations)}].

Instead, the company `谓` *has done precisely* `宾` {what it *had long promised* it would not} : *challenge* the constitutionality of Vermont’s rules [in the federal court], *as* part of a desperate effort *to keep* its Vermont Yankee nuclear power plant *running*. ② It’s a stunning move.

The conflict *has been surfacing* since 2002, when the corporation *bought* Vermont’s only nuclear power plant, an aging reactor in Vernon. ② As a condition of *receiving* state approval *for* the sale, `主` the company `谓` *agreed to seek* permission *from* state regulators *to operate* past 2012. ③ In 2006, the state *went a step further*, *requiring* that {any extension of the plant’s license *be subject to* Vermont legislature’s approval}. ④ Then, too, the company *went along*.

*Either* Entergy *never really intended to live by* those commitments, *or* it simply *didn’t foresee* what would happen next. ② `主` A string of accidents, *including* the partial collapse of a cooling tower in 207 /and the discovery of an underground pipe system leakage, `谓` *raised* serious questions *about* both Vermont Yankee’s safety and Entergy’s management -– especially after the company *made* misleading statements *about* the pipe. ③ *Enraged by* Entergy’s behavior, the Vermont Senate *voted* 26 *to* 4 last year *against* allowing an extension.

Now the company *is suddenly claiming that* {the 2002 agreement *is* invalid *because of* the 2006 legislation, and *that* only the federal government *has* regulatory power *over* nuclear issues}. ② The legal issues in the case *are* obscure: *whereas* the Supreme Court *has ruled* that {states *do have* some regulatory authority *over* nuclear power}, legal scholars *say* that {Vermont case *will offer* a precedent-setting test of how far those powers *extend*}. ③ Certainly, there `系` *are* valid concerns *about* the patchwork regulations (that *could result* [if every state *sets* its own rules]). ④ But [*had* Entergy *kept its word*], that debate *would be beside* the point.

The company *seems to have concluded that* its reputation in Vermont is already *so* damaged *that* it *has nothing left to lose* by *going to war with* the state. ② But there *should be* consequences. ③ Permission *to run* a nuclear plant *is* a public trust. ④ Entergy *runs* 11 other reactors in the United States, *including* Pilgrim Nuclear station in Plymouth. ⑤ *Pledging to run* Pilgrim safely, the company *has applied for* federal permission *to keep it open* for another 20 years. But [*as* the Nuclear Regulatory Commission (NRC) *reviews* the company’s application], it *should keep it mind* {what promises from Entergy *are* worth}.


---

== 2012-3


In the idealized(a.) version of how science is done, 主 facts (about the world) 谓 *are waiting* to be observed(`=to see or notice`) and collected by objective 客观的; 不带偏见的 researchers (who *use* the scientific method *to carry out*(`=do it`) their work).  

But [in the everyday practice of science], discovery(n.) *frequently follows* an ambiguous 模棱两可的, 含糊不清的 and complicated route.  +
We *aim* to be objective 客观的; 不带偏见的, but we *cannot escape* the context (想法、事件等的)背景,环境 of our unique life experience.  +
Prior(`=happening or existing before sth else`) knowledge and interest *influence* ① what we *experience*, ② what we *think* our experiences(n.) mean, ③ and the subsequent(`=happening or coming after sth else`) actions we take.  +
Opportunities for misinterpretation 误解;曲解, error, and self-deception 自欺;自我欺骗 *abound*(`= to exist in great numbers or quantities`).

在科学研究的理想状态下,关于世界的事实,正在等待着那些客观的研究者来观察和搜集,研究者们会用科学的方法来进行他们的工作。但是在每天的科学实践中,发现通常遵循一条模糊和复杂的路径。我们的目标,是做到客观,但是我们却不能逃离我们所处的独特的生活经验的环境。之前的知识和兴趣会影响我们所经历的,会影响我们对于经验意义的思考,以及我们会采取的随后的行动。这里充满着误读,错误,和自我欺骗的机会。

Consequently(`=as a result; therefore`), discovery claims(n.) *should be thought of as* proto-science 前科学,科学雏形. *Similar to* newly staked 提出权利要求;主张权利 mining 矿业；采矿 claims, they *are* full of potential. 

But it *takes* collective(`=done or shared by all members of a group of people`) scrutiny(n.)(`=careful and thorough examination`) and acceptance *to transform* a discovery claim *into* a mature(`=fully grown and developed`) discovery.  +
This is the credibility 可信性;可靠性 process, 方式状[through 通过；凭借 which] the individual researcher’s me, here, now *becomes* the community’s anyone, anywhere, anytime. Objective knowledge *is* the goal, *not* the starting point 起始点；出发点.

====
- stake：n.桩,赌注；v.系…于桩上；把…押下打赌
- If you *stake a claim*, *you say that something is yours* or that you have a right to it. 提出权利要求;主张权利 
- newly staked mining claims：这段话讲的就是对所有权的要求或申明,这里 claims 是名词,“(对所有权的)提出/申明”,mining claims 指的就是“对采矿权的申明/要求”, *stake(out)就是“对......提出所有权要求；声称对......有所有权”*, 在这里staked是过去分词, 作定语修饰 mining claims, 意思是“被提出的”。

- scrutiny => scrut,scrutin=search 表示"检查", tiny微小的 。→检查微小的必须「细看」。
====

所以,对于发现的申明,应该被当做是科学的原型。这与新近开发的采矿资源比较类似,他们都充满着可能性。但是将发现的申明变为一个成熟的发现,是需要集体的审查,和集体的接受。这个过程就配称之为“信用的过程”,通过这个过程,一个单个研究者的“我”,在这里就变成了这个社区中的任何人,任何地方,和任何时间。客观的知识不应该是起点,而是目标。

Once a discovery claim *becomes* public, the discoverer *receives* intellectual credit(`=praise or approval`). But, unlike with mining claims, the community *takes control of* what happens next. 

Within the complex social structure of the scientific community, researchers *make* discoveries; editors and reviewers *act as* gatekeepers 看门人；守门人 *by controlling* the publication 出版；发行 process; other scientists *use* the new finding *to suit*(`=to be convenient or useful for sb`) their own purposes; and finally, the public (including other scientists) *receives* the new discovery and possibly accompanying technology.  
====
- suit : v. to be convenient or useful for sb 对（某人）方便；满足（某人）需要；合（某人）心意 +
-> If we met at 2, would that *suit you*? 我们两点钟见面，你方便吗？
====

一旦一个科学发现变成公开的,那么发现者就获得了知识的认可。但是和采矿权不一样的是,科学协会将控制接下来会发生的事情。在复杂的科研机构的社会结构中,研究者去做出发现；编辑和审稿者通过控制出版过程,扮演着看门人的角色；其他的科学家使用新的发现,来满足他们自己的目标；最后,公众(也包括其他科学家)接受到新的发现,和可能相伴随的技术。

[当 As a discovery claim *works*(`=to move or pass to a particular place`) it *through* the community], 主 the interaction 相互作用,交互 and confrontation(`=a dispute, fight, or battle`) (between shared and competing 相互冲突的;相互矛盾的 beliefs about the science and the technology (involved)) 谓 *transforms* an individual’s discovery claim *into* the community’s credible(`=able to be trusted or believed`) discovery.
====
- work : v. *to move or pass to a particular place or state, usually gradually* （逐渐地）移动（到某位置）；（逐步）变成（某状态） +
-> He *worked* his way *to* the top of his profession. 他一步一步努力，终于成为行业内的翘楚。 +
-> I was tied up, but managed *to work myself free*. 我被捆绑起来，但设法挣脱了绳索。 +
-> The screw *had worked loose* . 这螺丝钉松动了。

- competing : ADJ Competing ideas, requirements, or interests *cannot all be right or satisfied at the same time*. (想法、要求或利益)相互矛盾的; 相互抵触的 +
-> ...*the competing demands* of work and family. 
 ...工作和家庭互相矛盾的要求。
====

当一个发现的声明最终通过了机构的审查,在有关所涉及到的共享的和抵触的信念之间的互动和冲突,将把一个人的发现,变为一个机构的可信的发现。

Two paradoxes 悖论；自相矛盾的说法 *exist* throughout 自始至终;从头到尾;贯穿 this credibility process.  

First, scientific work *tends to focus on* some aspect of prevailing(`=existing or most common at a particular time`) Knowledge that *is viewed 考虑;看待 as* incomplete 未完成的;未结束的 or incorrect.  +
Little reward *accompanies* duplication 重复 and confirmation 确认 of what is already known and believed. The goal is new-search, not re-search. 

Not surprisingly, 主 newly published discovery claims and credible discoveries (that *appear to be* important and convincing 令人信服的;有说服力的) 谓 will always *be open(a.)(`=likely to suffer sth`) to* challenge and potential modification 更改,改变,修改 or refutation (对观点、指责或理论的)驳斥; 反驳 *by* future researchers.  
====
- confirmation : a statement, letter, etc. *that shows that sth is true, correct or definite* 证实；确认书；证明书 +
-> I'm still waiting for *confirmation of the test results*. 我仍在等待考试结果的通知书。

- *open (v.) ~ (to sth)* : likely to suffer sth such as criticism, injury, etc. 易受损害；脆弱 +
-> The system is *open(a.) to abuse*. 这项制度容易被滥用。 +
-> He has laid himself *wide open(a.) to political attack*. 他在政治上已经处于极易受到攻击的境地。
====

在整个信任的过程中,存在着两个悖论, +
第一：科学工作,倾向于关注一些流行科学的某些方面,而这些方面又是被认为是不完全和不正确的。去复制和确认已经被人所知和所信的东西,不会有多少回报。科学要做的是去探究新的东西,而不是再次探究。不足为奇的是,新发表的重要的,有说服力发现,和可信的发现,将会被后来的研究者质疑,并带来潜在的修改,甚至驳斥。

Second, 主 novelty(`=the quality of being new, different and interesting`) itself  谓 frequently *provokes* 激起；引起 disbelief 不相信;怀疑.  +
Nobel Laureate 戴桂冠的；得奖者 and physiologist 生理学者 Albert Azent-Gyorgyi once *described* discovery *as* “*seeing* what everybody has seen /and *thinking* what nobody has thought.” But ｛*thinking* what nobody else has thought /and *telling* others what they have missed｝ *may not change* their views.  Sometimes years *are required* for truly novel discovery claims *to be accepted and appreciated*(`=to understand that sth is true`).

第二个悖论是：新颖的东西本身就经常会招致怀疑。诺贝尔奖获得者,生理学家Albert Azent-Gyorgyi曾经将发现描述为：“观察每个人观察的,思考没有人想到的。”但是思考其他人没有想到的,并且告诉其他人他们所遗漏的,可能并不会改变这些人的观点。有时候,真正新颖的科学发现被人们所接受和认可,将会花好多年的时间。

In the end, credibility *“happens” to* 发生(在…身上);(某人)遭到;遇到 a discovery claim —— a process that *corresponds to*(`=to be the same as or match sth`)相一致；符合 what philosopher Annette Baier *has described as* the commons of the mind. “We ① *reason*(v.)(`=to form a judgement`) together, ② *challenge*(v.)质询；质疑, ③ *revise*(v.)(`=to change your opinions or plans in order to correct or improve it`), and ④ *complete*(v.)(`=to make sth whole or perfect`) each other’s reasoning 推理；论证 and each other’s conceptions(`=the process of forming an idea or a plan`)构想 of reason 原因；理由；解释.”
====
- revise => vis,vid=see表示"看"。revise v 修正,改订(re 再+vis+e→再看一遍→修正)
- conception : n. the process of forming an idea or a plan 构思；构想；设想 +
-> The plan was *brilliant in its conception* but failed because of lack of money. 尽管这计划构想绝妙，但终因资金不足而告流产。

====

最后,一个科学的发现获得了信任,这个过程是与哲学家Annette Baier所描述的心灵的共性的观点是一致的。“我们共同去推理,去质疑,其修改并且完善各自的推理,以及各自的推理概念。

---

== 2012-3 纯净版

In the idealized version of how science is done, facts about the world *are waiting to be observed and collected* by objective researchers who *use* the scientific method *to carry out* their work. ② But [in the everyday practice of science], discovery *frequently follows* an ambiguous and complicated route. ③ We *aim to be* objective, but we *cannot escape* the context of our unique life experience. ④ `主` Prior knowledge and interest `谓` *influence* what we *experience*, what we *think* {our experiences *mean*}, and the subsequent actions we take. ⑤ Opportunities for misinterpretation, error, and self-deception *abound*.

Consequently, discovery claims *should be thought of as* protoscience. ② *Similar to* newly staked mining claims, they are full of potential. ③ But it *takes* collective scrutiny and acceptance *to transform* a discovery claim *into* a mature discovery. ④ This is the credibility process, [through which] the individual researcher’s me, here, now *becomes* the community’s anyone, anywhere, anytime. ⑤ Objective knowledge *is* the goal, *not* the starting point.

Once a discovery claim *becomes* public, the discoverer *receives* intellectual credit. ② But, *unlike with* mining claims, the community *takes control of* what happens next. ③ Within the complex social structure of the scientific community, `主` researchers `谓` *make* discoveries; `主` editors and reviewers `谓` *act as* gatekeepers *by controlling* the publication process; `主` other scientists `谓` *use* the new finding *to suit* their own purposes; and finally, `主` the public (including other scientists) `谓` *receives* the new discovery and possibly accompanying technology. ④ As a discovery claim *works* it *through* the community, the interaction and confrontation (*between* shared *and* competing beliefs *about* the science and the technology (involved)) *transforms* an individual’s discovery claim *into* the community’s credible discovery.

Two paradoxes *exist* [throughout this credibility process]. ② First, scientific work *tends to focus on* some aspect of prevailing Knowledge (that *is viewed as* incomplete or incorrect). ③ Little reward *accompanies* duplication and confirmation of what *is already known and believed*. ④ The goal *is* new-search, *not* re-search. ⑤ Not surprisingly, `主` newly published discovery claims and credible discoveries (that *appear to be* important and convincing) `谓` *will always be open to* challenge and potential modification or refutation *by* future researchers. ⑥ Second, novelty itself *frequently provokes* disbelief. ⑦ Nobel Laureate and physiologist Albert Azent-Gyorgyi once *described* discovery *as* “*seeing* what everybody has seen /and *thinking* what nobody has thought.” ⑧ But `主` {*thinking* what nobody else has thought /and *telling* others what they have missed} `谓` *may not change* their views. ⑨ [Sometimes] years *are required* for truly novel discovery claims *to be accepted and appreciated*.

In the end, credibility *“happens” to* a discovery claim -- a process that *corresponds to* what philosopher Annette Baier *has described as* the commons of the mind. ② “We *reason* together, *challenge*, *revise*, and *complete* each other’s reasoning and each other’s conceptions of reason.”

---

== 2012-4

If the trade(`=a particular type of business`) unionist 工会会员 Jimmy Hoffa *were* alive today, he *would probably represent* civil servant 公务员,文职人员.  +
When Hoffa’s Teamsters *were* in their prime(`=the time in your life when you are strongest or most successful`) in 1960, only one in ten American government workers *belonged to* a union; now 36% *do*.  +
[In 2009] the number of unionists 工会会员 in America’s public sector 部门；扇形,扇区 *passed*(`=greater than`) that of their fellow伙伴的;同伴的;同类的 members in the private sector.  +
In Britain, *more than* half of public-sector workers *but only about* 15% of private-sector ones *are unionized*(`=to become a member of a trade/labor union`).

如果工会会员Jimmy Hoffa今天还活着,他也许会是公务员的代表。1960年Hoffa的组织Teamsters,处于全盛时期,美国政府工作人员中,只有十分之一的人属于某一个公会;现在这个比率是36%。2009年任职于美国公共部门的工会会员人数,超过了任职于私营部门的工会会员人数。在英国,在公共部门的工作人员中,半数以上参加了工会;而私营部门的工作人员,只有大约15%的人参加了工会组织。   

There are three reasons for the public-sector unions’ thriving(`=do well and are successful, healthy, or strong`).  +
① First, they can *shut(`=to make sth close; to become closed`) things down*(`=to stop a factory, shop/store, etc. from opening for business`) without *suffering much* in the way of consequences.  +
② Second, they *are* mostly bright(`=intelligent; quick to learn`) and well-educated. A quarter of America’s public-sector workers *have* a university degree.  +
③ Third, they now *dominate*(`=to control or have a lot of influence over sb/sth`) left-of-centre (人或政党)中间偏左的 politics. Some of their ties(`=a strong connection between people`) *go back* 追溯到；回溯到 a long way.  +
Britain’s Labor Party, *as* its name *implies* 暗指;暗示, *has long been associated with* trade unionism(联合主义；统一主义) 工会制;工会主义.  +
Its current leader, Ed Miliband, *owes*(`=to admit that sth is true`) his position *to* votes(n.) (from public-sector unions).
====
- *shut sth down* : to stop a factory, shop/store, etc. from opening for business; to stop a machine from working （使）关张，停业，倒闭，关闭，停止运转
- dominate => 来自拉丁语domus, 家，词源同domain. 即一家之主，支配，控制。

- unionism : N-UNCOUNT Unionism is any set of political principles based on the idea that *two or more political or national units should be joined or remain together*, for example that Quebec should remain part of Canada. 统一主义 /工会主义是基于"两个或两个以上的政治或国家单位应该联合或保持在一起的"任何一套政治原则，例如魁北克应该仍然是加拿大的一部分。

- *Trade unionism* is the system, practices, and beliefs of trade unions. 工联主义

- *own (v.) ~ to sth/to doing sth* : ( old-fashioned ) to admit that sth is true 承认 +
-> He *owned to* a feeling of guilt. 他承认有歉疚感。 +
-> She *owned (that)* she had been present. 她承认她当时在场。

- 最后一句的votes, 是一个n. 而不是v. 因为如果它是v. 它是没有 votes from... 这种用法的, 而只有: +
*vote (v.)~ (for/against sb/sth) /~ (on sth)* :  to show formally [by marking a paper or raising your hand] which person (you want to win an election), or which plan or idea you support 投票（赞成╱反对）；表决（支持╱不支持）；选举
====


公共部门工会如此盛行的原因有三个。第一,他们能够脱身,而不用承担太多后果。第二,他们中间大部分人聪明,受过良好教育。美国公共部门的工作人员中,四分之一的人有大学学位。第三,他们现在在政治中的左翼力量中,占主导地位。其中有些关系有很长的历史。正如其名,英国工党和工会组织的关系,由来已久。其现任领导Miliband把自己得到的位置,归功于来自公共部门工会组织的投票。   

[At the state level] their influence *can be* even more fearsome(a.)(`= making people feel very frightened`).  +
Mark Baldassare of the Public Policy Institute of California *points out* that {much of the state’s budget *is patrolled(`=move around it in order to make sure that there is no trouble there`) by* unions}.  +
① The teachers’ unions *keep an eye on* (`=to take care of sb/sth and make sure that they are not harmed, damaged, etc`)照看；留意；密切注视 schools, ② the CCPOA(=California Correctional Peace Officers Association) *on* prisons and ③ a variety(`=several different sorts of the same thing`) of labor groups *on* health care.

从州范围来看,他们的影响更为吓人。加利福尼亚州公共政策研究院的Mark Baldassare指出,本州大部分预算,都由工会来检查。教师工会关注学校；加利福尼亚感化治安官协会,关心监狱；各型各色的劳工团体,关注卫生保健。   

[In many rich countries] average wages 工资；报酬 (in the state sector) *are higher than* in the private one. But the real gains(`=an increase in the amount of sth, especially in wealth or weight`) *come in*(`=receive it regularly as your income`) benefits and work practices.  

Politicians 政客 *have repeatedly “ backloaded ”* public-sector pay deals(`=the way that sb/sth is treated`) 工资协议,工资待遇, *keeping* the pay *increases* modest(`=not very large, expensive, important, etc`) but *adding to* holidays and especially pensions 退休金；养老金 that *are* already generous(`=more than is necessary; large`).
====
- backload [bækləud](v.)(签订协议后的)增加费用
- public sector 公共部门
- private sector 私人部门

- deal : (n.) (1)*an agreement, especially in business, on particular conditions for buying or doing sth* 协议；（尤指）交易 +
-> *to make/sign/conclude/close a deal (with sb)* （与某人）达成一笔交易 +
(2) [ Cusually sing. ] *the way that sb/sth is treated* 待遇 +
-> They knew *they'd been given a raw/rough deal* (= been treated unfairly) . 他们知道自己受到了不公正待遇。
====

在很多富裕国家,公共部门的平均工资,要高于私营部门的平均工资。但是真正的收入,来源于利润和工作表现。政客已不停地加强公共部门的工资待遇,工资涨幅不大,但却加长本来就不少的假期,特别是增加本来就很多的养老保险金。   

Reform 改革 *has been vigorously(ad.)(`=very active, determined or full of energy`) opposed*(`=to disagree strongly with`), perhaps most egregiously(`=very bad and offensive`) in education, where charter 特许状，许可证 schools, academies(`=schools and colleges, especially those specializing in particular subjects or skills, or private high schools in the United States`) and merit(`=a good feature that deserves praise, reward or admiration`) pay 绩效工资 *all faced* drawn-out(`=lasts or takes longer than you would like it to`) battles.  

Even though 尽管;虽然 there is plenty of evidence that the quality of the teachers is the most important variable 变量,可变因素, teachers’ unions *have fought against* getting rid of 扔掉;摆脱 bad ones and *promoting*(`=to move sb to a higher rank or more senior job`) good ones.
====
- egregious : e-, 向外。-greg, 群，集中，词源同yard, gregarious. 原义为鹤立鸡群的，极好的，现义贬义化。参照拉丁文egregium, 非凡，伟业。

- charter school : 是美国州政府在公共教育体系之外特许的中小学水平的教育机构，中文一般称为"特许学校"。相比一般州立中小学，特许学校需要遵守的规定更少，但同时获得的资金支持也更少。特许学校同样分为营利和非营利，其中非营利特许学校不可从私人处获得资金捐助。 +
在《不让一个孩子掉队》的法令下,一个公立学校如果连续三年,在州标准化统考中不合格,将面临被关闭的制裁。当一所学校面临被关闭的厄运时,州政府,当地的社会机构,企业,甚至个人可以将其接管,转为charter school。charter school的启动基金来自州政府。 +
charter school与一般公立学校最大的不同是, 它不受一般公立学校的法令条例限制.

- *merit pay* : 绩效工资

====
对于变革的反对一直都很强烈,在教育方面最为惊人。在教育方面,契约学校、专科学校、绩效奖都面临着持久战。尽管有大量证据表明,教师的质量是最重要的变量,但教师工会反对解雇不好的教师,提升好教师。   

原因状从 *As* the cost to everyone else *has become* clearer, politicians *have begun to* clamp down(`=to take strict action in order to prevent sth, especially crime`).  +
[In Wisconsin] the unions *have rallied*(`=to come together or bring people together in order to help or support sb/sth`) thousands of supporters *against* Scott Walker, the hardline(`=firm and uncompromising`) Republican governor. But many (within the public sector) *suffer* under the current system, too.
====
- The cost 指某种代价，这种代价变得日益明显.
- clamp : a tool for holding things tightly together, usually by means of a screw 夹具；夹子；夹钳
- clampdown : N-COUNT A clampdown is *a sudden restriction on a particular activity by a government or other authority*. 制裁
- PHRASAL VERB To *clamp down on* people or activities means *to take strong official action to stop or control them*. 取缔; 严加限制

- *rally (v.) ~ (sb/sth) (around/behind/to sb/sth)* : to come together or bring people together in order to help or support sb/sth 召集；集合 +
-> The cabinet *rallied behind* the Prime Minister. 内阁团结一致支持首相。
====

对其他每个人的支出变得更为清晰,政客开始强制执行。在威斯康辛州,工会集结了成千上万的支持者,反对走强硬路线的州长,即共和党人Scott Walker。但很多任职于公共部门的工作人员,也在目前的体制下受罪。   

John Donahue at Harvard’s Kennedy School *points out* that {the norms(`=standards of behaviour`) of culture in Western civil services *suit* those who want to stay put 留在原处不动 /but *is bad for* high achievers(`=a person who achieves the particular level of success`)}.  +
The only American public-sector workers (who *earn well 大大地,远远地 above* $250,000 a year) *are* university sports coaches 教练 and the president of the United States.  +
Bankers’ fat(`=large in quantity; worth a lot of money`) pay packets 一大笔钱 *have attracted* much criticism, but 主 a public-sector system (that *does not reward* high achievers 谓 *may be* a much bigger problem for America.
====
- stay put : ( informal ) if sb/sth *stays put* , they continue to be in the place where they are or where they have been put 待在原地；留在原处
- packet:包装袋;(扁平的)小包裹; +
一大笔钱 You can refer to *a lot of money* as *a packet* .

====
哈佛肯尼迪学院的John Donahue指出,西方公务员系统的文化准则,适合这些想留在原地过安逸生活的人们,但并不适合那些表现好的人们。任职于美国公共部门的工作人员中,只有大学体育教练,和美国总统,每年的收入远远高于250,000美元。银行的高收入招致了很多批评,但对于美国来讲,在公共部门体制中,没有给表现好的工作人员足够的回报,可能会成为更为严重的问题。

---

== 2012-4 纯净版

If the trade unionist Jimmy Hoffa *were alive* today, he *would probably represent* civil servant. ② When Hoffa’s Teamsters *were* in their prime in 1960, only one in ten American government workers *belonged to* a union; now 36% *do*. ③ In 2009 the number of unionists in America’s public sector *passed* that of their fellow members in the private sector. ④ In Britain, more than half of public-sector workers but only about 15% of private-sector ones *are unionized*.

There *are* three reasons for the public-sector unions’ thriving. ② First, they *can shut things down* without suffering much in the way of consequences. ② Second, they *are* mostly bright and well-educated. ③ A quarter of America’s public-sector workers *have* a university degree. ④ Third, they now *dominate* left-of-centre politics. ⑤ Some of their ties *go back a long way*. ⑥ Britain’s Labor Party, *as* its name *implies*, *has long been associated with* trade unionism. ⑦ Its current leader, Ed Miliband, *owes* his position *to* votes from public-sector unions.

[At the state level] their influence *can be* even more fearsome. ② Mark Baldassare of the Public Policy Institute of California *points out that* much of the state’s budget *is patrolled by* unions. ③ The teachers’ unions *keep an eye on* schools, the CCPOA *on* prisons /and a variety of labor groups *on* health care.

[In many rich countries] average wages in the state sector *are higher than* in the private one. ② But the real gains *come in* benefits and work practices. ③ Politicians *have repeatedly “backloaded”* public-sector pay deals, *keeping* the pay *increases* modest /but *adding to* holidays and especially pensions (that are already generous).

Reform *has been vigorously opposed*, perhaps most egregiously in education, where charter schools, academies and merit pay *all faced* drawn-out battles. ② Even though there *is* plenty of evidence *that* the quality of the teachers is the most important variable, teachers’ unions *have fought against* {*getting rid of* bad ones /and *promoting* good ones}.

As the cost to everyone else *has become clearer*, politicians *have begun to clamp down*. ② [In Wisconsin] the unions *have rallied* thousands of supporters *against* Scott Walker, the hardline Republican governor. ③ But many within the public sector *suffer* under the current system, too.

John Donahue at Harvard’s Kennedy School *points out that* {the norms of culture in Western civil services *suit* those who want to stay put /but *is bad for* high achievers}. ② The only American public-sector workers (who *earn well* above $250,000 a year) *are* university sports coaches and the president of the United States. ③ Bankers’ fat pay packets *have attracted* much criticism, but a public-sector system (that *does not reward* high achievers) *may be* a much bigger problem for America.


