= 1442
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 137.
This is ESL Podcast’s English Café number 137. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com to download a Learning Guide for this episode. This is an 8 to 10 page guide that gives you all of the vocabulary, definitions, sample sentences, cultural notes, and a complete transcript of this episode.
This episode is going to be an “Ask an American” episode, where we listen to other native speakers talking about a topic, and then explain what it is that they are saying. This gives you a chance to hear someone’s voice other than mine, as well as people speaking at a native rate of speech.
Today’s topic is a very popular form of music in the United States called “bluegrass.” We’ll talk about what bluegrass music is and listen to some descriptions, and even some samples of it. As always, we’ll answer a few of your questions as well. Let’s get started.
Our “Ask an American” segment today is about bluegrass music. Bluegrass is a very interesting American style of music. It started, or we might say it “had its roots” – it had its beginnings – in traditional music from Ireland, Scotland, and England. What happened was these immigrants came can they settled in the United States, many of them in an area called Appalachia. Appalachia is an area that includes the Appalachian Mountains, which are on the eastern side of the United States. Appalachia has been, and still is in some ways, a poor, rural, mountainous area. The states of Kentucky and Tennessee, for example, have poor areas still in this Appalachian Mountain chain.
The immigrants came and they brought with them their traditional music, and they combined it with some other American music forms such as blues and jazz, and you get this combination coming together in this particular style of – I guess we could call it country music; it’s a type of country music called bluegrass. Let’s first listen to a small sample of bluegrass music, and then we’ll talk more about it.
[music]
In bluegrass music, just as in jazz, one instrument – one musical instrument – plays the melody and the other instruments provide backing, or “accompaniment,” they go along with that main melody. The “melody” is the main notes of a particular piece of music or song. Bluegrass music has all of the instruments playing the melody at some time, but unlike traditional music, they don’t all play it together. So first the banjo will play it, and then the fiddle will play it, and then a different instrument will play the melody, and the melody gets, we might say, “passed around.” It gets moved from one instrument to the other as you are listening to it.
We’ll listen now to a description of the origins, or beginnings, of bluegrass music, from someone who is a teacher. Let’s listen, and then we’ll go back and talk about what he said,
[recording]
It was brought over from the old country, but then it was developed in the Blue Ridges and that, and developed father-son, and as it – each time it’s passed down to another generation, it gets a new personality. So, it is truly American music.
[recording ends]
This gentleman describes bluegrass music, saying it was brought over from the old country. It was “brought over,” meaning it was taken from one place and brought here, in this case, to the United States. The “old country” is a traditional expression, at least in American English, to refer to Europe, the countries where most of the white immigrants to this nation came from. We talk about the “old country,” meaning the countries where the first European immigrants came from. Now it could be used to describe any country – original country where someone came from, but traditionally it referred to European countries. This, of course, would be in contrast to the United States, which is a new country. In fact, the Americas are sometimes called the “New World.”
Well, this gentleman says that bluegrass was brought over from the old country, but then it was developed in the Blue Ridges. The Blue Ridges is a part of the Appalachian Mountains; sometimes we refer to a part of them as the Blue Ridge Mountains. The “ridge” is like the edge or the top of a mountain. If you travel to the Blue Ridge Mountain area, you can actually see why it is called the Blue Ridge Mountains, because there is a certain bluish color when you look at them from a distance that is caused, in part, by the trees that are native to that area – that grow in that area.
So, this music was developed in the Blue Ridges – the Blue Ridge Mountains – this gentleman says. It continued to develop within families. This gentleman says it developed father to son, and each time it’s passed down to a new generation, it gets a new personality. “To pass something down” means to give it to someone, usually a son, or a cousin, or someone who is younger than you are. Often we use this expression in talking about things that are in a family, that belong to a member of the family and that person gives it to his or her son or daughter, and they give it to his or her son or daughter, and so forth, so it continues to be part that one family. Well, bluegrass music developed within families in this area, and each time it gets passed down – each time a new generation of people begin to play it, it takes on what he calls “a new personality” – a new style or a new particular emphasis. Let’s listen again.
[recording]
It was brought over from the old country, but then it was developed in the Blue Ridges and that, and developed father-son, and as it – each time it’s passed down to another generation, it gets a new personality. So, it is truly American music.
[recording ends]
Bluegrass music uses mostly what we would call “acoustical” instruments. The word “acoustics” refers to the study of how sound move through the air. Here, however, it means the opposite of electric; these are non-electric instruments. There’s one exception to that; sometimes the electric bass guitar is used with bluegrass music. But most of the instruments are acoustic instruments; most of them are “stringed” instruments, meaning you have you have strings that you play on, like a guitar, a “banjo,” which is a special kind of guitar; a “fiddle” (fiddle), which is just another word for a violin, but when the violin is used in this kind of music, it’s sometimes called a fiddle. There’s also a “mandolin,” another kind of guitar – or looks like a guitar, and a “bass,” which is something you would also see in a symphony orchestra. It’s a large instrument that plays very low notes. The bass is often used in jazz music as well.
I said a fiddle is really the same thing as a violin; let’s listen now to this instructor – this teacher – talk about how the fiddle is different than the normal, or regular, violin.
[recording]
The real difference is the – the traditional fiddle player, because they play several strings or several notes, will flatten the bridge. They basically customize a violin. They’ll pull the sound post back a little bit to get more of the “wangy” sound, and they’ll use a harder, a more steel-type string.
[recording ends]
We get some vocabulary related to the violin here, and musical instruments. He begins by saying the real difference – that is, the real difference between a violin and a fiddle – is that the traditional, the normal, the regular fiddle player, because they have to play several notes at the same time will flatten the bridge. “To flatten” means to make flat. The “bridge” is the little part of a violin or fiddle that is where the strings sit on top of, towards the end of the violin – the round end of the violin, to put it that way. He says they “flatten the bridge. They basically (they essentially) customize the violin.” “To customize” means to makes something specifically for your purpose, to take something else and change it. He says the fiddle players will pull the sound post back a little bit. The “sound post” is the part of the violin that’s inside the violin that helps produce the sound that a violin makes when you play the strings. They do this in order to get more of a “wangy” sound. I’m not exactly sure what he means by “wangy” here. We have a similar word, however, which is “twang” (twang), which is a kind of sound that you sometimes hear in American country music, so I’m thinking that is what he is referring to here when he says “wangy.” He says also that the fiddle players use a harder, more steel-like string, as compared to a classical violin player.
Once again, it’s the same basic instrument, just modified and customized. Let’s listen again.
[recording]
The real difference is the – the traditional fiddle player, because they play several strings or several notes, will flatten the bridge. They basically customize a violin. They’ll pull the sound post back a little bit to get more of the “wangy” sound, and they’ll use a harder, a more steel-type string.
[recording ends]
Bluegrass music is relatively new; it was developed, really, in the 1940s in the Appalachian Mountain area. It was a combination of, as I said before, traditional music brought over from Scotland and Ireland, as well as the blues and jazz that were prominent that was to be found in many places in the American South, especially among African American, or black musicians.
Nowadays, you can hear country singers who specialize in bluegrass music. Dolly Parton is a very popular country singer who has recorded some bluegrass albums. There was a movie a few years ago with George Clooney called O Brother, Where Art Thou? that also used a lot of bluegrass music, so if you rent that movie, you’ll see a little, or hear a little bluegrass music. And you’ll see it being played, too, I guess!
Our final quote here comes from someone who’s talking about the reputation of bluegrass music in American culture. When you say bluegrass music, people will often think of country music, and when you say country music, they think of farms, what we would call “rural” areas, places away from the big cities. This person says that that is not a complete picture of what bluegrass music is. Let’s listen.
[recording]
You know, you see it on a lot of truck commercials and that kind of thing, but I think it has a lot more application than that, and it has a lot more deep roots and – and feeling than just being used in some car commercial somewhere.
[recording ends]
He starts by saying, “you see it,” meaning really you hear bluegrass, “on a lot of truck commercials and that kind of thing.” Trucks are often associated, at least in American culture, with rural areas, places outside of the city. There’s also something of an association that people who live in rural areas are somehow not as sophisticated, perhaps not as intelligent as those who live in the city. So, it’s sort of a negative connotation, that is, a negative meaning that is implied here. He says, “I think (bluegrass) has a lot more application than that,” meaning it can be found in other contexts. It’s not just for truck commercials; it’s real music that you can listen to and enjoy. He says, “it has a lot more deep roots,” that is, a lot deeper roots or origins, “and feeling than just being used in some car commercial somewhere.” So, he’s saying here that it is a more serious and important kind of music; it is not just something that you should listen to when you are watching a truck commercial, or advertisement. Let’s listen again.
[recording]
You know, you see it on a lot of truck commercials and that kind of thing, but I think it has a lot more application than that, and it has a lot more deep roots and – and feeling than just being used in some car commercial somewhere.
[recording ends]
Bluegrass music, like jazz, blues, and other kinds of country music, is an American kind of music; it began in the United States, but now, just as with jazz and blues, you will see people from other countries also recording bluegrass music. In fact, there’s a group from the Czech Republic in Europe, which is very famous for recording bluegrass music. If you have a chance to listen to some, I think you’ll enjoy it. It will certainly remind you, if you watch American movies, of the Appalachian Mountain area, the rural areas in the eastern part of the United States.
Now let’s answer a few of your questions.
Our first question comes from Baku (Baku) in Azerbaijan. Baku wants to know the difference between a “resume” and a “CV,” or “curriculum vitae.”
A “resume” is usually a single page or a small number of pages that summarize your skills, experience, and educational background. When you’re applying for a job – most jobs – they ask for a resume, a summary of your qualifications.
A “curriculum vitae,” which is sometimes simply called a “CV,” is a longer, more in depth kind of resume. It usually is something we use when you are applying for a more professional or higher level job. It involves detailed information about your educational training, where you went to school, whether you have taught or done research, any published books or articles that you had, any speeches or presentations that you may have made, perhaps any awards or honors that you’ve been given; this would all be part of a CV. A CV is often used in university jobs; if you are applying to be a professor they will ask for your CV, your complete and detailed list of all of your accomplishments.
Many companies and organizations require a resume. Sometimes an organization will ask for something called a CV, and that is often a company that is involved in education or in science or in some research area. Resume is the more general, more common term that most companies use.
Juan from Columbia wants to know how we spell or pronounce certain numbers, whether we say “zero” (0) or we say “O,” the letter.
Sometimes in English, people will pronounce the number zero like the letter “O.” For example, the famous character James Bond from the British movies is “double O seven.” We don’t say “zero zero seven” (007), or “double zero seven,” we say “double O seven.” This is just a shorter way of saying zero; it means the same thing. In telephone numbers, also, you will sometimes hear people say “O” instead of zero: “My number is five five five, O three O four.” That would be the same situation. You could say, “My number is five five five, zero three zero four,” it would mean the same thing.
As a general rule, it’s safest to use “zero” when you’re not sure whether you can say “zero” or “O.” That’s because there are some circumstances where you can’t say “O” instead of “zero.” For example, you may say, “We received zero responses to our advertisement.” You can’t say, “We received O responses,” you have to use the number zero. That’s why I say if you’re not sure, it’s easiest and safest to say zero when you mean zero, and use “O” only if you know that that is a situation where it is acceptable, like a telephone number – or double O seven!
Yevgen (Yevgen) from Ukraine wants to know the meaning of the expression “one over the other.” For example, your boss may say to you, “I want you tell me your reasons for choosing one over the other.”
The expression “one over the other” is used when you are comparing two possibilities – two options – which are similar, but one is better than the other. If I’m looking for a cake for my son’s birthday, I taste one cake, a chocolate cake; I taste another cake, a lemon cake, I have to choose one over the other. I have to make a decision, and decide which one is best. I chose chocolate over lemon.
We thank you for choosing ESL Podcast over other podcasts you may listen to. If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
to bring over – to take from one place to another; to carry from one location to another location as one moves to a new place
* Would you please call Cecil and ask him to bring over some extra chairs when he comes over for dinner?
to pass down (something) – to teach something to the next generation; to give information, skills, traditions, and other things to one’s children or grandchildren
* I made this cake from a recipe that was passed down to me by my grandmother.
to flatten – to make flat; to make something wide, but not high or deep
* Tim wasn’t watching where he was going. He drove over the girl’s ball and flattened it.
bridge – a small piece of wood on a musical instrument over which the strings are stretched; a small piece of curved wood that keeps the strings off the instrument so it can be played
* The bridge on this violin is broken so we need to replace it before the concert tonight.
basically – essentially; fundamentally; simply
* You’re giving us a lot of facts, but basically you’re saying that we don’t have enough money for this year’s events. Is that right?
roots – relating or connected to something, usually in the past; the place situation, or traditions from which something comes
* Alesia tried for many years, but couldn’t figure out the roots of her fear of dogs.
origin – the place, situation, or tradition from which something comes; the place where something started or was founded
* The professor gave a lecture about the origins of humans on Earth.
melody – a series of single musical notes; the main musical notes in a song
* It’s difficult to hear the melody in this song because the drummer in the group is playing too loudly.
acoustic – music produced without electronic equipment to make it louder or to change its sound
* You can better hear the rock singer’s good voice when he performs the acoustic version of his hit song.
fiddle – informal term for violin, a musical instrument with strings that is played with a bow (long stick with horse-hair stretched between its ends)
* Will you play your fiddle at the country dance this year?
banjo – a musical instrument with strings, a long neck, and a round body, played by plucking (using the fingertips to move) the strings, often used for American folk music
* She is the best banjo player in this state. She plays so fast that it’s hard to follow her fingers!
bass – a large musical instrument with strings that looks like a very large violin, played with a bow (long stick with horse-hair stretched between its ends)
* At the concert, the first song began with the deep notes of the bass.
resume – a short, usually one-page, summary of one’s education, past experience, accomplishments, and other things, often used to apply for jobs
* If you want to apply for the job, submit your resume before five p.m. today.
curriculum vitae (CV) – a summary of one’s education, past experience, accomplishments, and other things, usually used to apply for jobs, especially in the academic and technical fields
* Don’t forget to list the awards you’ve won on your CV.
What Insiders Know
O Brother, Where Art Thou? and The Soggy Bottom Boys
O Brother, Where Art Thou? is a comedy film released in 2000. The movie is set in the state of Mississippi during the “Great Depression,” a period of great economic problems, which began in the U.S. in 1929. “Where art thou?” is an example of English spoken long ago and means “Where are you?” The film is “loosely” (not closely) based on the story of Homer’s Odyssey, a very old Greek book about one man’s very long journey to return home after a great war.
The movie includes a “quartet” (group of four musicians) called the “Soggy Bottom Boys.” “Soggy” means wet, and “bottom,” in this case, refers to the part of the body above the legs and below the waist used for sitting down.
A lot of the music in the film is American folk and bluegrass music. After the film was released, the “fictional” (not real) band became so popular that the well-known bluegrass musicians who played and sang the music won a Grammy Award for their “collaboration” (cooperation on a project) and went on “tour” (traveling to different cities to perform). The “soundtrack,” the recorded music used in the movie, won a Grammy Award, the most prestigious and respected music award in the U.S., for Album of the Year in 2001.
In the movie, the “lead” (main) guitarist character of the Soggy Bottom Boys was “supposedly” (believed to be) based on the famous and well-respected blues musician Robert Johnson. Robert Johnson claimed that he sold his “soul” (spirit) to the devil in return for being able to play the guitar.