= 1436
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 131.
This is English as a Second Language Podcast’s English Café episode 131. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can download a Learning Guide for this episode. You can also take a look at our ESL Podcast Store, which has additional courses for you in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about a famous U.S. government agency known as the FBI, or the Federal Bureau of Investigation. We’re also going to talk about a very popular magazine called Reader’s Digest. And as always, we’ll answer a few of your questions. Let’s get started.
You may have seen American movies or, perhaps, read stories in the newspaper about the FBI, which stands for Federal Bureau of Investigation. In the movies, people who work for the FBI, who are what we would call “FBI agents,” are sometimes referred to as “g-men,” the “g” stands for government, because they work for the national, or federal, government. The Federal Bureau – or office, agency – of Investigation is the closest thing we have to a national police force.
The FBI was founded, or created – we sometimes say “established” – in 1908, 100 years ago. It was originally called the Bureau of Investigation. It changed its name to the Federal Bureau of Investigation in 1935. The “mission” or reason the organization exists is “to protect and defend the United States against terrorist and foreign intelligence threats, to uphold and enforce the criminal laws of the United States, and to provide leadership and criminal justice services.” This is the official mission from the FBI website.
The mission, I’m sure, has changed over the years. You notice now that the first part of their purpose is protecting and defending the U.S. against terrorist threats. They also have the purpose of upholding and enforcing the criminal laws of the United States. “To uphold” usually means to make sure that people are following the law. Enforcing the law is similar; “to enforce a law” means to actually go and check to see if people are doing what they are supposed to be doing, according to the law. The FBI is concerned with “criminal law,” law that is related to committing crimes, such as robbing a bank, or other things.
Most crimes in the United States are taken care of by the local city or state police forces. The FBI only gets involved in certain kinds of crimes. They also are responsible for providing “leadership and criminal justice services.” The term “criminal justice” is another word for “law enforcement,” doing things to help the police; the FBI will sometimes help the local or the state police with a particularly difficult case.
The FBI investigates federal crimes and provides domestic intelligence. The first part, “federal crimes,” is the activity of the FBI that you will most often see in the movies or in books. There have been many television shows and movies about the FBI, usually when they are investigating some sort of crime. The FBI, especially recently, has become more involved in domestic intelligence. The word “intelligence,” here, usually refers to how smart a person is – my wife will say, “Jeff, you are not very intelligent!” We also use the word “intelligence” to refer to information that a country needs for its own protection, or thinks it needs for its own protection. Sometimes, domestic intelligence is not always necessary for protecting the country. Sometimes governments have domestic intelligence to control its own people. But, the idea here is that the FBI is gathering intelligence, or information, about, perhaps, what people inside the United States are doing. The opposite of “domestic,” which refers to things in this country, is “foreign.” Foreign intelligence is supposed to be gathered by the Central Intelligence Agency, or CIA.
If a crime occurs in one state, the state government, as I said, usually investigates it, or the local government. However, if a crime occurs in more than one state, then the FBI will often investigate it. If a federal employee or a U.S. President is attacked or killed, once again it’s the FBI that will be responsible for investigating the crime.
When the FBI investigates federal crimes, what are some of the crimes the FBI investigates? Well, one of them would be serial killers. “Serial” (serial) is someone who does something one after another after another, in a series. A “serial killer” is someone who kills many different people. Be careful, there’s another word that sounds the same, spelled (cereal), that’s the kind of cereal that you would eat in the morning as food. A serial killer is not someone who kills for food; it’s someone who kills many people over a long period of time, usually.
The FBI also investigates child predators, people who, unfortunately, abuse or take advantage, in a sexual way, of children. The FBI is also responsible for investigating Internet crimes, especially people who are hackers. “To hack” means to get access to a computer or a computer program that you do not have permission for. Internet hackers sometimes try to get into the official government websites and steal things, or change things.
As a domestic intelligence agency, the FBI tries to get information about people inside the United States who, they think, are trying to hurt the country. Sometimes these are terrorists; sometimes it involves people who are spies. A “spy” is someone who is working for another country, trying to get information from the United States. Once again, the movies are full of examples of spies working in the U.S. or in other countries. The most famous example, from Great Britain, would be James Bond, who is a spy for the British government. The FBI, then, investigates spies who are here in the U.S., sending information, perhaps, back to their own countries.
Most of the “charges,” or accusations, that result from FBI investigations are related to bank robberies. When someone tries to steal money from the bank, usually a lot of money since the bank has a lot of money, these are considered crimes that the FBI investigates, even if it only happens in one state. This is, perhaps, because the federal government considers this kind of robbery very serious, and so investigates the issue itself. Other types of crimes the FBI investigates include drug crimes, conspiracies – a “conspiracy” is a large, detailed plan to do something bad. Conspiracies are usually things where people are trying to do illegal actions.
After September 11, 2001, and the attacks on the World Trade Center in New York City as well as the Pentagon and Flight 93 that crashed in Pennsylvania, the FBI had its powers grow considerably. That is, the U.S. government, specifically the Congress in the U.S.A. Patriot Act began to allow the FBI to watch people in the United States in ways that they were not allowed to before. This is especially true with the Internet. They have been allowed to enter people’s homes without letting them know about it until afterwards. They even now have the power to get your library records. When you “check out a book,” or take a book from the public library, the FBI can find out what you’re reading. I don’t think, if they looked at my library record, they would find anything very interesting!
There are many people who are worried that in the last seven-eight years the FBI’s power has grown too much. Other people think that the FBI has to have these powers in order to investigate and protect the country.
The FBI is a very large “agency,” or organization. It has an annual budget of about eight billion dollars. A “budget” (budget) is the amount of money that an organization spends. The FBI has more than 30,000 employees. Most of them are in Washington, D.C., at the “headquarters,” or main office of the FBI. If you visit Washington D.C., you can actually take a tour of the FBI. When I went to Washington back in the late 1980s, with a couple of friends, we took a tour of the FBI. The FBI takes itself very seriously, meaning it considers its job to be very important. Sometimes it took itself a little too seriously when we were taking our tour! But, it’s a very interesting tour; it’s about an hour or so long. The FBI is, as you might expect, very “secretive,” meaning it doesn’t like to talk about what it does publicly very much, but you can learn some things by taking the tour from the FBI, and finding out the way it works.
The FBI also has offices in all the big, major cities of the United States. It is very difficult to become an FBI agent; you have to go through many different steps before the government will hire you to work for the FBI. I don’t know anyone, myself, who has ever worked for the FBI. If I did, I couldn’t tell you, it’s a secret!
Next we’re going to talk about perhaps the most popular magazine, or one of the most popular magazines in the United States, called Reader’s Digest. A “digest” (digest) is a summary of something, especially when it is in a magazine that summarizes many other articles, or stories. Reader’s Digest, then, is a publication that takes many of its articles from other magazines and it condenses them. “To condense” means to make something shorter or smaller. The Reader’s Digest magazine publishes condensed stories from other publications. These are usually general-interest stories, meaning they’re not specialized, but are interesting to many different people.
Because the magazine is general-interest, it has many different kinds of stories. They have articles about entertainment, government, medicine, science, sports, business, education, and many other topics. Any “edition,” or version, of the magazine has an article called “Face to Face,” where they interview a famous person. That’s one of the regular “features,” or parts of the magazine. The magazine is published once a month, meaning there are 12 published every year.
Reader’s Digest also usually has some sort of adventure story, a story about some exciting event that took place. There is usually an advice column, or a short section that gives readers advice or suggestions about different things in life. The Reader’s Digest is also famous for having a book excerpt. An “excerpt” (excerpt) is when take part of a book – not the whole book, but part of it if – and publish it. In fact, the magazine has books that are condensed versions of other books. Many people don’t like this; they like to read the whole book, but some people prefer just to read the excerpts, or the sections from the book that are the most interesting.
Reader’s Digest also has a humor section. “Humor” means funny or comical. For example, they have a section called “Humor in Uniform” which has jokes about the United States military, the Army and the Navy for example. You can actually send your own joke into the Reader’s Digest magazine, and they sometimes pick the jokes that readers send in to publish in the magazine.
Reader’s Digest is extremely popular; it’s “circulation,” or number of copies that it sells each month is very high. In the US, more than 10 million copies are sold every month. Most American families, at one time or another, have probably subscribed to Reader’s Digest, or know someone who subscribed to Reader’s Digest. We had a subscription when I was growing up, back 25-30 years ago. More than 38 million magazines are actually read by Americans, there are another 40 million people who read Reader’s Digest in other languages, in other countries.
Reader’s Digest is actually a pretty good magazine to read if you are learning English. The stories are short and are usually fairly easy to read. You can also learn more about American culture by reading Reader’s Digest in English. I won’t say it’s the best-written magazine in the United States, but it is easier than some of the other magazine you may pick up, and as I say, the stories are usually pretty short.
Now let’s answer a few of your questions.
Yevgen (Yevgen) from Ukraine wants to know the difference between the words “consent” (consent) and “assent” (assent).
“To consent” is a verb, which means to agree or to except what someone has asked or suggested. For example: “My father gave his consent to my marriage to my now wife.” “To give his consent” means he said, “Okay, it is all right creation for you to marry.” I think the actual words my father said were, “Thank God, you’re finally getting married!” Something like that!
“To assent” also means to agree; it’s very similar to “consent.” “To assent” is a verb we might use in a more formal situation, especially in writing. “The president assented to the idea” – he agreed with it.
Yevgen also wants to know the difference between the words “concord” (concord) and “accord” (accord).
Both of these words are nouns. “Concord” is an agreement of interest or feelings. It’s when two things or two situations seem to be agreeing with each other. It can be used about people or countries. For example: “The two countries were in concord about the need to end the war” – they were in agreement.
An “accord” is usually official agreement between two countries or two organizations; it is what you actually call the agreement. Most often, this word is used for official agreements between two different people or two different countries. For example, if two countries have been fighting each other, they might try to have a “peace accord,” an agreement to stop fighting and to live in peace. This is something we hope for all countries, include ours.
Marr (Marr) in Taiwan wants to know the meaning of the expression “the long and the short of it.”
This is an interesting expression; it’s a casual expression, an informal expression. It means that is the summary, or that is the basic information about something. We talked about “digest” meaning a summary; the expression “that’s the long and short of it” means what I just told you is a summary.
The phrase comes from the idea that there’s a long version of a story and a short version of a story. After you hear both, then you should understand the story very well. So, if you tell someone the long and the short of something, you’re giving them a very good summary of the information that you have for them.
If you have a question or comment for the Café, you can email us at eslpod@eslpod.com, and we’ll to try to answer as many we can here on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
federal – national; relating to the entire country instead of just one state
* Is this a federal highway or a state highway?
domestic intelligence – information about what people are doing inside a country, used to protect that country’s security and safety
* Do you think it is okay for domestic intelligence agencies to listen to citizens’ private phone calls?
serial killer – a person who kills other people one at a time, resting between each murder, often killing them in the same way
* Ted Bundy was a serial killer who murdered many young women in the 1970s.
child predator – a person who abuses children, often sexually
* Many schools protect their students from child predators by not letting adults into the building unless they work there.
Internet hacker – a person who creates or destroys computer programs to destroy computers and businesses
* An Internet hacker created a program that is sent via email and automatically deletes all of the files on a computer.
conspiracy – a secret, detailed plan by two or more people to do something bad or to cause harm or damage
* A new movie tries to show that the death of John F. Kennedy was a government conspiracy.
secretive – without sharing information openly about oneself; closed; keeping one’s thoughts, opinions, and actions hidden from other people
* Mila is one of the most secretive people I know. She never tells anyone what she is doing.
digest – a summary; a piece of writing that gives the most important details about something else; a magazine that summarizes what has been written in many other publications
* I wish there were a digest of all these scientific articles so I can easily keep up with the latest developments.
to condense – to make something shorter and/or more compact; to fit something into a smaller space
* This book has 100 pages, but it is so wordy that it could be condensed into just 30 pages without losing any of the meaning.
excerpt – a small part of something; a small piece taken from a book, article, song, movie, etc.
* Raquel heard an excerpt of a beautiful song on the radio and now she wants to buy the full CD.
humor – something that is funny, comical, and makes people laugh
* Vincent has a great sense of humor and is always saying things that make other people laugh.
consent – permission to do something
* Are you going to ask for her father’s consent before you ask her to marry you?
assent – agreement or approval
* Mr. Steinway nodded in assent as the president was describing the company’s new strategy.
concord – having a friendly, non-confrontational relationship between two or more people, without stress or disagreement
* People who have been married for 50 years know the secret to living in concord with another person.
accord – agreement; not contradicting
* They are always in accord with each other and never argue over anything!
the long and the short of it – in summary; a phrase used when wants to present a complicated idea very quickly
* I don’t want to describe the reasons for my decision in detail, but the long and short of it is that I’ve decided not to go to college.
What Insiders Know
J. Edgar Hoover
J. Edgar Hoover was the director of the Federal Bureau of Investigation (FBI) for 48 years, from 1924 to 1972, during eight “presidential administrations” (the time when one president in is office). Most of the public “admired” (respected and liked) him very much, but of course he did some things that people have “questioned” (asked whether something was appropriate).
Many people “accused” (said that someone did something wrong) Hoover of abusing his “authority” (official power). In the 1960s, he often had the FBI investigate groups because of their political beliefs, even if they weren’t necessarily “suspected” (thought to have done something wrong) of criminal activity. He also treated FBI employees badly, “firing” (taking away someone’s job) them if they became too popular. Some people say that he did this because he was “jealous” (wanted what another person had) of their popularity.
Hoover led the FBI during the “Great Depression” (a period of time in the 1930s when the U.S. economy performed very poorly) and four wars: World War II, the Korean War, the Vietnam War, and the Cold War. The importance of the FBI grew “steadily” (constantly) throughout the time that he was the director. Hoover played a major role in how the agency became what it is today.
Hoover was in office for a very long time and “amassed” (gathered and collected) a lot of power. “Consequently” (as a result), FBI directors now have a “maximum term limit” (the maximum amount of time that one can work in a particular position, especially in a government position) of 10 years.