= 0306
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 306: Giving First Aid.
This is English as a Second Language Podcast episode 306. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com. You can download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions not found on the podcast, cultural notes, and a complete transcript of this episode.
This episode is called “Giving First Aid.” It’s a conversation between two people talking about common injuries – things that you would need to give medical help for; we call that “first aid.” Let’s get started.
[start of dialogue]
Jeng: What did you do this summer?
Cynthia: I worked at a summer camp as a nurse’s aide. I thought we would be giving simple first aid, but you wouldn’t believe the kinds of injuries the kids came in with.
Jeng: You mean like poison ivy, bee stings, bug bites, and scraped knees?
Cynthia: Yeah, we had those, but we also had some pretty serious cases. For instance, the second day of the camp, one of the boys who didn’t know how to swim fell into the lake. He must have hit his head because he was unconscious when they brought him in. We couldn’t find his pulse and the nurse did CPR. Luckily, we got him breathing again right away, but that little boy had a concussion.
Jeng: Wow! You’re kidding. That’s serious.
Cynthia: That wasn’t all. It’s true that most of the kids came in with superficial scrapes, but some of them had some major wounds. We had to stop the bleeding and bandage them up. We had one girl who needed 12 stitches after she fell out of a tree.
Jeng: Geez, I never knew going to camp could be so hazardous to your health!
[end of dialogue]
Our dialogue is called “Giving First Aid.” “First aid” is medical help that someone, who is usually not a doctor, gives to another person.
In the dialogue, Jeng asks Cynthia, “What did you do this summer?” Cynthia says, “I worked at a summer camp as a nurse’s aide.” A “summer camp” would be a place where you send children, usually for a week or two weeks. Often, it is in a big park or next to a lake, and they haves games and other types of activities for the children. Normally these happen during the summertime when children are not in school.
I went to a camp when I was 12 years old. It was for one week, and I absolutely hated it! I think it was the worst experience of my life – one of the worst. It was not very comfortable; you had to sleep in a big room with 20 other boys. I don’t really like going out into the forest or on the lake so it wasn’t a good experience for me, but some children really like it.
A “nurse’s aide” (aide) is an assistant, a person who helps a nurse. A “nurse” is a medical professional who helps a doctor, but isn’t as highly educated as a doctor. Nurses work with the doctors, so a “nurse’s aide” is someone who’s helping the nurse.
Cynthia says, “I thought we would be giving simple first aid, but you wouldn’t believe the kinds of injuries the kids came in with.” “You wouldn’t believe” means it was quite unusual, something that you wouldn’t expect: “You wouldn’t believe the kinds of injuries.” An “injury” (injury) is damage or harm that is done to someone’s body. For example, you break your leg, that’s an injury.
Cynthia is talking about the injuries that the children had at the summer camp. Jeng then lists some common problems that you may have in a camp. He says, “You mean like poison ivy, bee stings, bug bites, and scraped knees?” “Poison ivy” (two words) is a kind of plant that when you touch it, makes your skin itch. A “bee sting” is when a bee, which is a small insect that is often yellow and black and makes what we would call a “buzzing” sound, [Jeff makes a buzzing sound] that would be a bee (bee). A “bee sting” is when the bee attacks you – makes a small hole in your skin that often hurts, that’s a bee sting. A “bug bite” is also when an insect, what we would call often simply a “bug,” comes and bites you – makes a hole in your skin, so that your skin becomes red and it’s itchy, and it often hurts. A “scraped knee” is when your knee, which is part of your leg, has some of the skin taken off. If you, for example, fall on the ground and you hit your knee, you may scrape it. Some of the skin may off and you may begin to bleed – to have blood come out of your knee; that would be a scraped knee. The verb “to scrape” (scrape) means to remove the top layer or top part of something. So, Jeng is saying did you have these common problems of poison ivy, bee stings, bug bites, and scraped knees; the kinds of problems you would expect children to have at a summer camp.
Cynthia says, “Yeah, we had those, but we had some pretty serious cases. For instance (for example), the second day of the camp, one of the boys who didn’t know how to swim fell into the lake.” To “fall into” means to go into, but usually by accident – you didn’t want to. So, this boy doesn’t know how to swim and he fell into the water. “He must have hit his head,” Cynthia says, meaning it is very likely that he hit the top of his head, “because he was unconscious when they brought him in.” So he went into the water, he hit his head, and then he was unconscious. To be “unconscious” means you are not aware of what is happening around you, usually because you are hurt. So, if you hit your head you may become unconscious. It’s like you’re sleeping, almost.
Cynthia says that they could not find the boy’s pulse. Your “pulse” (pulse) is the same as your heartbeat. It’s the speed and strength of the blood moving through your body, and at certain points of your body you can feel that movement and we call that the “pulse.” So they couldn’t find the boy’s pulse; the nurse then did CPR. “CPR” are initials that stand for cardiopulmonary resuscitation. “Cardio” relates to your heart; “pulmonary” relates to your lungs – your ability to breathe in and out; “resuscitation” means to revive someone, someone who is not breathing – make them breathe again. So cardiopulmonary resuscitation is called, for short, “CPR.” Many people, especially nurses and teachers and others who work with children, have CPR training. They go to a day or two days where a nurse explains to them how to help someone who has stopped breathing. CPR usually involves blowing air into the person’s mouth and pushing on his or her chest, over the heart, with your hands to get the heart moving again – to get the heart working again.
So in the story, the nurse performs, or does, CPR on the boy – you do CPR “on” someone. “Luckily,” she says, “we got him breathing again right away (immediately), but that little boy had a concussion.” To “breathe” means to move air in and out of your lungs, [Jeff makes a breathing sound] that’s breathing. A “concussion” is when you lose consciousness because you are hit on your head. This can be very dangerous, to have a concussion when you get hit very hard on your head
Jeng says to Cynthia, “Wow! You’re kidding. That’s serious.” Note when he says “You’re kidding,” he doesn’t really mean “you are joking,” which is what we would normally mean when we say “you’re kidding.” “You’re kidding” here is when you are surprised at something, when you can’t believe something because it is so usual. So, Jeng says, “You’re kidding,” meaning “Wow, that’s unusual."
Cynthia says, “That wasn’t all,” meaning there was more that happened. “It’s true,” she says, “that most of the kids came in with superficial scrapes, but some of them had some major wounds.” “Superficial” means on the surface, not very serious usually. A “scrape,” we know, comes from the verb “to scrape,” when part of the skin is removed and the person starts to bleed. To “bleed” means to have blood coming out of your body. A “wound” (wound) is another word for an injury. Often when blood is coming out of your body, on your arm or on your leg or on your head, we would call that a “wound.”
Cynthia says, “the kids came in with superficial scrapes, but some of them had some major (or serious) wounds.” She says, “We had to stop the bleeding and bandage them up.” “To bandage (bandage) someone up” is a phrase that means to put cloth on someone’s injury – someone’s wound – so that it stops bleeding – to put something on the skin so that it doesn’t bleed, so that no more blood comes out.
Cynthia said, “We had one girl who needed 12 stitches after she fell out of a tree.” A “stitch” is a small line of thread that a doctor uses to put two pieces of skin together – to sew two pieces of skin. So if you cut your arm, for example, the doctor may put some of this string – this thread – in your skin to keep the skin together so that the wound can heal (heal). To “heal” means to get better. We would say you had to “get stitches”: “I had to get stitches on my arm because I had a wound and I wanted it to heal."
Finally, Jeng says, “Geez (or wow), I never knew going to camp could be so hazardous to your health!” Something that is “hazardous to your health” is something that is dangerous, something that is not safe: “Driving and trying to talk on your cell phone can be very hazardous.”
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Jeng: What did you do this summer?
Cynthia: I worked at a summer camp as a nurse’s aide. I thought we would be giving simple first aid, but you wouldn’t believe the kinds of injuries the kids came in with.
Jeng: You mean like poison ivy, bee stings, bug bites, and scraped knees?
Cynthia: Yeah, we had those, but we also had some pretty serious cases. For instance, the second day of the camp, one of the boys who didn’t know how to swim fell into the lake. He must have hit his head because he was unconscious when they brought him in. We couldn’t find his pulse and the nurse did CPR. Luckily, we got him breathing again right away, but that little boy had a concussion.
Jeng: Wow! You’re kidding. That’s serious.
Cynthia: That wasn’t all. It’s true that most of the kids came in with superficial scrapes, but some of them had some major wounds. We had to stop the bleeding and bandage them up. We had one girl who needed 12 stitches after she fell out of a tree.
Jeng: Geez, I never knew going to camp could be so hazardous to your health!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
nurse – a medical professional who helps a doctor; a person who provides basic medial services, but isn’t as highly trained and educated as a doctor
* If you like taking care of people, but you don’t want to be a medical student for six years, you might want to become a nurse.
aide – an assistant; a person whose job is to help another person
* In many schools, a teacher’s aide helps the teacher work with students and do other classroom tasks.
first aid – basic medical treatment; medical help given to someone before that person can be taken to a hospital or doctor’s office
* Francine is taking a first aid class to learn what to do if her children get hurt.
injury – damage or harm done to a person’s body
* Vincent was in a bad car accident and he was relieved when the doctor told him he had only a minor neck injury.
poison ivy – a plant whose leaves have a chemical that makes people’s skin red, itchy, and painful when they touch it
* Don’t touch that plant! It’s poison ivy.
bee sting – a very small hole made in one’s skin by the sharp part of a bee’s body, so that the skin around it become red, itchy, and painful
* Chuck got three bee stings on his arms while he was picking blackberries.
bug bite – a very small hole made in one’s skin by an insect’s mouth, so that the skin around it becomes red, itchy, and painful
* Ingrid woke up with bug bites on her legs. There must have been a spider in her bed.
scraped knee – a knee where some of the skin has been rubbed off, leaving painful red skin and blood on the knee
* Ashley has scraped knees because she fell off of her bicycle while she was wearing shorts.
unconscious – without consciousness; not aware of what is happening around oneself because one is hurt and seems to be asleep
* After Zack was hit on the head with a baseball, he was unconscious for almost five minutes.
pulse – heartbeat or heart rate; the speed and strength of blood moving through one’s body, so that it can be felt through the skin over one’s wrists and neck
* After running for 20 minutes, the runner felt her pulse to see how quickly her heart was beating.
CPR – cardiopulmonary resuscitation; when a person is not breathing, trying to keep that person alive by pushing on his or her chest over the heart and blowing air into his or her mouth
* Horace saved Jackie’s life by performing CPR after she was kicked by a horse.
to breathe – to move air in and out of one’s lungs; to move air in and out of one’s body
* It’s difficult to breathe when you’re high in the mountains because there isn’t very much oxygen.
concussion – the loss of consciousness when one is hit hard in the head; the period of time when one is not aware of anything after one has been hit on the head
* Sammy fell out of a tree and had a concussion that lasted an entire day.
superficial – only on the surface; not internal; not serious
* Maggie has a superficial burn on her hand, but the doctor said it isn’t anything to worry about.
wound – an injury; a hole in the skin so that blood comes out
* Kelly has a wound on her leg from where the dog bit her.
bleeding – the action of blood (a red liquid) coming out of one’s body
* When Shane cut his face while shaving, there was a lot of bleeding, even though the cut wasn’t very deep.
to bandage (someone or something) up – to put a cloth on someone’s injury to make it stop bleeding
* Reggie bandaged up his hand with an old shirt and then asked his friend to drive him to the hospital.
stitch – a small line of thread that doctors use to sew two pieces of skin together around a cut or other injury
* Brook had to have nine stitches on her foot after she stepped on broken glass.
hazardous – dangerous; unsafe; not safe
* The label on the cigarettes said that smoking is hazardous for your health.
Comprehension Questions
1. Why did the nurse give CPR to the little boy?
a) Because he couldn’t find his pulse.
b) Because he had a concussion.
c) Because he wasn’t breathing.
2. Which of these is an example of a superficial wound?
a) Poison ivy.
b) Scraped knee.
c) Stitches.
Answers at bottom.
What Else Does It Mean?
aid
The phrase “first aid,” in this podcast, means basic medical treatment that is given to someone before he or she can be taken to a hospital: “All police officers and firefighters are trained in first aid.” By itself, the word “aid” means help or assistance: “Did you know that the United Nations is giving millions of dollars in food aid to Africa this year?” An “aid” is also an object that helps one do something: “Grandpa isn’t able to hear very well anymore, so he’s going to get a hearing aid.” Or, “What kind of visual aids are you going to use during your presentation?” As a verb, “to aid” means to help: “The country’s economic growth was aided by new tax laws and better education.”
superficial
In this podcast, the word “superficial” is used to talk about injuries that are on the surface and aren’t serious: “We thought that the cut on Dana’s arm was only superficial, but the doctors said that it was dangerously infected.” The word “superficial” is also used to talk about things that only deal with the obvious, and don’t go into detail: “This book has a superficial description of the reasons for World War II, and it makes things seem too simple.” The word “superficial” also means something that appears to be important or true, but really isn’t: “Good looks are only superficial; a person’s personality is more important.” Finally, if a person is “superficial,” he or she is shallow and interested only in unimportant things: “Greg is so superficial that he thinks having an expensive car is the most important thing in life.”
Culture Note
In the United States, many people have a “first aid kit,” or a small box that has the things people need to provide first aid when someone gets hurt. A first aid kit is usually a white plastic or metal box with a red “cross” (a shape like a plus sign “+”) painted on it, because a red cross is a “symbol” (an image that represents something else) for first aid.
Many people keep their first aid kits in the bathroom, usually in the “medicine cabinet” (a small mirrored cupboard above the bathroom sink). Other people carry them in the “glove box” (a small drawer in front of the front-seat passenger) of their cars. Most school busses, classrooms, and offices also have first aid kits to “handle” (manage and control) emergencies.
First aid kits have all the basic “supplies” (medicines and other things that are needed) for providing first aid. These include “bandages” (small pieces of cloth that are used to cover a wound and make it stop bleeding), “gauze” (white cotton cloth that is used to clean up blood), and “medical tape” (sticky cloth or paper used to put the bandages and gauze on the body). First aid kits also have scissors to cut the bandages, gauze, and medical tape.
Other supplies in first aid kits include basic medicines, like ibuprofen and aspirin for pain and “antibiotic” (bacteria-fighting) creams for cuts and scrapes. “Hot/cold packs” are small packets of chemicals that can be used to make something hot or cold almost immediately, and are used for “sprained joints” (ankles, elbows, and knees that are hurt by bending the wrong way). Finally, first aid kits usually have “instructions” (written details for doing something) for performing CPR.
Comprehension Answers
1 - c
2 - b