= 0323
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 323: Rooms in a House.
This is ESL Podcast episode three-two-three (323). I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and take a look at our ESL Podcast Store, which has some business and daily English courses we think you’ll enjoy. You can also take a look at our ESL Podcast Blog, where you can get news and additional English by going to our website each day.
This episode is called “Rooms in a House.” It is, of course, going to talk about the different parts of the house and what is in the different parts of the house, some useful daily vocabulary. Let’s get started.
[start of story]
I don’t like cats. That’s not really true. I like cats, but they don’t like me.
Last week, my friend Sara asked me to babysit her cat for two days while she was out of town. Normally, I would have said no, but she was in a jam, so I said okay.
As I said, cats don’t like me. When I got home from work, I couldn’t find her. I was sure she was hiding from me. I looked all over the house.
I started with the bedrooms, looking in the closets and under the bed. I looked in the bathroom and even behind the shower curtain. I went downstairs and searched the basement. No cat. Next, I looked all over the living room, checking under the couch and behind the TV. I also looked in the pantry and then the laundry room, thinking that the cat must be hiding behind the washer or dryer. Still, no cat.
Finally, I looked in the kitchen. There was the cat. She was sitting on the counter. Somehow she had managed to open a box of cookies and there she sat eating them all. When the cat saw me, she started mewing. I don’t speak the language of cats, but I could have sworn that she was asking me for some milk!
[end of story]
Our story begins by me saying, “I don’t like cats.” Now, the scripts for our episodes, as you know, are written by Dr. Lucy Tse. In this case, Lucy knows that this is true; I don’t like cats. But then I say, “That’s not really true. I like cats, but they don’t like me.” This is my problem.
“Last week, my friend Sara asked me to babysit her cat for two days while she was out of town.” To “babysit” (babysit – one word) usually means to take care of someone else’s child. This is something, for example, that a teenager might do for his or her neighbor; they would watch the child while the neighbor’s parents went somewhere. To “babysit” can also be used sometimes to refer to “pets,” or animals that people own – usually it’s for children.
In this case, I was asked to babysit for Sara “while she was out of town,” meaning while she was gone – she was going to another city. “Normally, I would have said no,” under normal circumstances, my answer would be no, but Sara “was in a jam, so I said okay.” If you are “in a jam” (jam), you are in a difficult situation; you have problems, you’re in trouble – “I’m in a jam, can you help me?”
The story continues, “As I said, cats don’t like me. When I got home from work, I couldn’t find her,” meaning the cat. I was sure the cat was hiding from me. “I looked all over the house. I started with the bedrooms, looking in the closets and under the bed.” The “bedroom” is the place where you sleep – you sleep on your bed. “Closets” are places where you put your clothing. You usually hang your clothing, and it is a place for storing things as well.
“I looked in the bathroom (the place where you have a toilet and a sink, often a shower or a bathtub) and even behind the shower curtain.” The “shower curtain” is a piece of plastic usually, that you put, or rather pull across the shower so that the water doesn’t go outside of the shower area. Some people have showers that have glass doors, other people have showers that have a curtain, just like the curtain that you might put on your windows of your house, except this is one for the shower – for the bathroom.
“I went downstairs and searched the basement.” The “basement” is a large room below the rest of the house. Most of the houses in cold areas have basements. In Southern California, however, most houses do not have basements.
I couldn’t find the cat. “Next, I looked all over the living room.” The “living room” is the main room of the house, where you sit and sometimes watch television or talk to each other. I checked under – I looked “under the couch and behind the TV. I also looked in the pantry.” The “pantry” (pantry) is a small room near the kitchen where you put dry foods. Rice, for example, cans of soup or vegetables – you would put these in your pantry. It’s a special place next to the kitchen. Not every house has a pantry, usually just a big house. My house does not have a pantry, for example.
“I looked in the pantry and then the laundry room.” The “laundry room” is the place where you wash your clothing. “Laundry” (laundry) is another word for clothing. In the laundry room you will find a washer and usually a dryer. A “washer” is a large of piece equipment where you put your clothes in and it washes them with water and soap. The “dryer” dries your clothes out. Some people put their clothes outside to dry, on what we would call a “clothesline” – they hang it on a clothesline. Most people, however, use a dryer, and they have a washer and a dryer in their house. Some people don’t have room, and so they will go to a local area – a local store called a “Laundromat,” and you can pay money and put your clothes in a washer and a dryer. I used to do this when I was a student; I didn’t have any washer or dryer in my apartment so I would go to the Laundromat and have that done.
“Finally, I looked in the kitchen. There was the cat.” The “kitchen” is the place where food is prepared, in a room where you do the cooking. The cat “was sitting on the counter.” The “counter” is a long surface – a long area that is sort of like a table. Usually you find a counter in a kitchen or a bathroom; it’s a place where you can put things. Often underneath the counter – below the counter, there are places to store things, or drawers to store things.
“Somehow” the cat “had managed to open a box of cookies,” I say. “Somehow” meaning in some way – I’m not sure how, but somehow she “managed to” – she was able to do something that is difficult – “she managed to open a box of cookies.” “There she sat eating” the cookies – the cat was sitting there eating the cookies. “When the cat saw me, she started mewing.” To “mew” (mew) is the verb we use for the noise that a cat makes. In English, we say a cat goes “meow, meow,” spelled M-E-O-W. Other languages, cats speak something different, I guess, but in English in English we say “meow,” or “meow.” I’m pretty good as a cat!
I said at the end of the story that “I don’t speak the language of cats, but I could have sworn that she was asking me for some milk!” It’s common when you have cookies to also drink milk in the U.S., at least for little children. The expression “I could have sworn” (sworn) is a phrase used to show that you thought something was true or that you believed something, but it was, in fact, wrong – it was incorrect. “I could have sworn I put my keys on the table, but I look on the table and there are no keys.” “I could have sworn” – I thought it was true, but it isn’t true
Now let’s listen to the story, this time at a normal speed.
[start of story]
I don’t like cats. That’s not really true. I like cats, but they don’t like me.
Last week, my friend Sara asked me to babysit her cat for two days while she was out of town. Normally, I would have said no, but she was in a jam, so I said okay.
As I said, cats don’t like me. When I got home from work, I couldn’t find her. I was sure she was hiding from me. I looked all over the house.
I started with the bedrooms, looking in the closets and under the bed. I looked in the bathroom and even behind the shower curtain. I went downstairs and searched the basement. No cat. Next, I looked all over the living room, checking under the couch and behind the TV. I also looked in the pantry and then the laundry room, thinking that the cat must be hiding behind the washer or dryer. Still, no cat.
Finally, I looked in the kitchen. There was the cat. She was sitting on the counter. Somehow she had managed to open a box of cookies and there she sat eating them all. When the cat saw me, she started mewing. I don’t speak the language of cats, but I could have sworn that she was asking me for some milk!
[end of story]
The script for this episode was written by our own Dr. Lucy Tse. Thank you
Lucy!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to babysit – to take care of another person’s children or pets (animals) for a short period of time, usually in exchange for money
* Olivia started babysitting her neighbor’s children when she was 14 years old, for $7 per hour.
in a jam – in a difficult situation; with problems; in trouble
* Gregory was in a jam when the person who promised him a ride home from work left without him.
bedroom – in a house, a room where one sleeps, usually with a bed, a small table, and a place to store clothes
* When you were a child, did you have your own bedroom or did you have to share one with your brother?
closet – an area built into a wall inside a home that has a door and is used to store clothes, towels, or other objects
* Maggie has so many shoes that they don’t fit in her closet, so she has to keep them in a box under her bed.
bathroom – a room with a toilet, sink, and often a shower and/or bathtub
* We keep extra towels in the bathroom, on the shelves above the toilet.
shower curtain – a large piece of plastic or cloth that is hung in front of a shower to keep water from getting on the floor
* If the shower doesn’t have a door, we’ll need to buy a shower curtain.
basement – a large room, usually unfinished, below the rest of a house
* The basement doesn’t have carpet or painted walls, so we use it to store things we don’t need very often.
living room – a large room where a family spends most of its time, and where it entertains guests, usually with sofas and other comfortable furniture
* The family spends Tuesday evenings playing cards together in the living room.
pantry – a small room near the kitchen where dry foods are kept
* Please go to the pantry and bring me the flour, sugar, and salt.
laundry room – a room where clothes, towels, and sheets are washed, dried, and folded
* Please leave your dirty clothes in the laundry room and I’ll wash them this afternoon.
washer/dryer – large pieces of equipment that wash and dry clothes easily
* Could you please move the clothes from the washer into the dryer, and then put these towels into the washer?
kitchen – a room where food is prepared; a room for cooking and baking
* Pat spent all day baking cookies, and the kitchen smells wonderful!
counter – a long, table-like surface, usually in a kitchen or bathroom
* Who left these dirty dishes on the kitchen counter?
somehow – in some way; in a way, but one isn’t sure how
* The dog somehow got out of the house and ran outside, and now we can’t find her.
to manage to – to be able to do something that is difficult
* How did you manage to finish writing the essay so quickly?
to mew – to make the “meow” noise that cats make
* The poor cat mewed loudly when Ronnie accidentally stepped on her tail.
could have sworn – a phrase used to show that one thought something was true, or that one believed something, but was incorrect
* I could have sworn that the professor said the test would be next week, but it was actually today!
Comprehension Questions
1. Why was Sara in a jam?
a) Because she was making jams and jellies.
b) Because she didn’t have any other options.
c) Because she was in a part of town known as “the jam.”
2. Why does he say, “I could have sworn that she was asking me for milk”?
a) Because he was angry and saying bad words (swearing).
b) Because he was ready to take an oath about the cat.
c) Because he believed the cat was asking him for milk.
Answers at bottom.
What Else Does It Mean?
in a jam
The phrase “in a jam,” in this podcast, means in a difficult situation: “Iva knew she was in a jam when she realized that she didn’t have enough money to pay for the taxi she was in.” A “traffic jam” is traffic that is very slow because there are too many cars on the road: “Seattle has horrible traffic jams around 6:00 p.m.” If a place is “jam-packed,” it means that the place has many people and it is very crowded: “The movie theater was jam-packed because everyone wanted to see the new movie that night.” Finally, a “jam session” happens when a group of musicians meet and play music informally, often without written music, making up the songs as they play: “Why don’t you bring your saxophone and come over for a jam session at my house on Saturday?”
counter
In this podcast, the word “counter” means a long, table-like surface, usually in a kitchen or bathroom: “If you spill toothpaste on the bathroom counter, please clean it up.” A “counter” is also a person or device that counts things: “This website has a counter that shows how many people have visited the site.” A “bean counter” is an informal and sometimes impolite way to talk about an accountant, or a person who counts money for a company: “We may be bean counters in this company, but without us, the company would be in a financial mess.” An “over-the-counter” drug is a medicine that one can buy at a pharmacy or other store without a doctor’s written permission: “Is acetaminophen an over-the-counter drug, or do I need to speak with my doctor first?”
Culture Note
American homes have many rooms that aren’t mentioned in the script of this podcast. An “attic,” for example, is a large room on the top floor, above the rest of the house, just like a “basement” is a large room below the rest of the house. Most attics and basements are “unfinished” (without nice walls, floors, and ceilings), so people don’t spend time in their attics and basements. Instead, they use them for “storage” (keeping things in a place when one doesn’t need to use them very often). Sometimes a basement that is used for storage, especially for food or wines, is called a “cellar.”
All homes have a living room, but some larger homes also have a “family room,” too. In a home with a living room and a family room, the living room is more “formal” or official and is used to entertain guests. The “family room” becomes the room where the family spends most of its time, and it is more “informal” or relaxed.
Some large homes also have a “game room” where children can play games and keep their toys. Other large homes may have a “library” where books are kept.
In most homes, the bedrooms are on one side of the house and are attached to a “hall,” or “hallway,” which is a long, narrow room with many doors along its sides that lead to bathrooms and bedrooms. Often people make an extra bedroom into a “home office,” “study,” or “den,” where parents can work at home and children can study. A home office usually has a computer desk and chairs.
Comprehension Answers
1 - b
2 - c