= 0335
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 335: Getting a Car Serviced.
This is English as a Second Language Podcast episode 335. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com; download a Learning Guide for this episode. You can also take a look at our ESL Podcast Blog and our ESL Podcast Store, which has additional courses in business and daily English that you may be interested in.
This episode is a dialogue between Sophia and her mechanic; she’s getting her car serviced. We’ll find out with that means, and learn some car vocabulary in this episode. Let’s get started.
[start of dialogue]
Sophia: Is my car ready?
Mechanic: I’m finished with your oil change and I replaced the oil filter. I’ve also replaced the wiper blades in your windshield wipers. But I’ve had a good look under your hood, and your car needs a lot of work.
Sophia: Really?
Mechanic: Yes, you have some serious problems. I bet your engine is running really rough. Your transmission is leaking, your shocks need to be replaced, and you need new brake pads. Your battery is very low and it should replaced, too.
Sophia: I can’t believe it.
Mechanic: It’s true. Your tires need to be rotated, too, and I also suggest getting a wheel alignment.
Sophia: Well, this is all a big surprise, especially since I just bought this used car a couple of months ago.
Mechanic: You did? Well, you got ripped off. Whoever sold you this car is a crook. Where did you buy it?
Sophia: I bought it here! I bought this from the owner of this garage. He said that it was in tip-top shape!
[end of dialogue]
Our dialogue begins with Sophia saying to her “mechanic,” the person who fixes a car, “Is my car ready?” The mechanic says, “I’m finished with your oil change and I replaced the oil filter.” When you have your car serviced, there’s nothing wrong with the car but you need to do certain things to keep your car running smoothly so that you won’t have any problems. Part of that is usually having your oil changed. “Oil” is what you put into the engine to help it work properly, so that the parts of the engine move properly – smoothly. An “oil change” is when you take out the oil in the engine and you put in new oil. The “oil filter” is a small part of the engine that cleans the oil – takes away the dirt in the oil or other objects so that the oil can do its job. So when you change your oil, you often change your oil filter.
The mechanic says, “I’ve also replaced the wiper blades on your windshield wipers.” Most cars have two windshield wipers. Your “windshield” is that piece of glass in the front of the car that protects you. The “windshield wipers” are two long metal and plastic bars – long pieces of metal – that are on the bottom of your window and clean your window – remove the water from your window. They go side to side in what we would call a “partial semi-circle,” that’s how you clean the water from your car. For example, if it’s raining, you need your windshield wiper. A “wiper” comes from the verb “to wipe” (wipe), which is to dry something with a cloth or some other instrument. Now, the windshield wipers have blades in them. A “blade” (blade) is usually a small rubber or plastic piece that actually touches the window. You don’t have metal touching your window, you have this rubber or plastic blade that touches the window and removes the water from it. The word “blade” has several different meanings in English; take a look at our “What Else Does It Mean” section in this episode’s Learning Guide for some additional explanations.
Well, the mechanic says that he’s “replaced the wiper blades in your windshield wipers. But I’ve had a good look under your hood, and your car needs a lot of work.” To say “I’ve had a good look” means I’ve examined very closely – I’ve looked at very carefully. In this case, the mechanic has looked carefully under the hood. The “hood” (hood) in American English is a large, flat piece of metal that covers the front of your car. If your engine is in the front of your car – in most cars it is – the “hood” is the metal that covers it. It’s like a door that you lift up in order to get to the engine. The little door in the back of your car is called the “trunk,” or the “trunk door”; in the front, it’s called the “hood.”
So, he looked at the engine – he looked under the hood – and the car, he thinks, need a lot of work. Of course, whenever you go to a mechanic, many mechanics will try to tell you you need to do more work on your car. Unfortunately, mechanics don’t have a very good reputation, at least in the United States, for telling you the truth all the time. That’s why it’s so hard to find a good mechanic – probably harder than finding a good doctor.
The mechanic says, “you have some serious problems. I bet your engine is running really rough.” “I bet” means I’m guessing, or I believe, “your engine (the motor of your car that keeps the car running) is running really rough,” meaning it’s not working very smoothly. “Your transmission is leaking, your shocks need to be replaced, and you need new brake pads.” These are three parts of the car. Your “transmission” is the part of the car that transmits the energy from the car’s engine to the wheels. You can have either an automatic transmission or a manual transmission, what we sometimes call a “stick shift.” In both cases, the transmission controls the “gears,” small round wheels that help transfer the power coming from your engine and direct that, if you will, to the rest of the car. It controls it – it controls how fast you can go.
The “transmission is leaking.” “To leak” means to allow a small amount of liquid to escape, usually by accident – you don’t want it to. You could say, “My roof is leaking” – it rains and there is water coming down through my house into the inside of the house. The roof – the top of the house – is leaking. Well here, the “transmission is leaking,” meaning there’s transmission oil coming out of the car. It should not be, and that’s a problem.
Your “shocks” (shocks) is another word for your “shock absorbers.” This is the part of the car that makes the ride smoother. Instead of having the car go up and down quickly, the shocks help keep the car from going up and down as you are driving down the road and hit a bump, for example. So, the shock absorbers need to be replaced, according to the mechanic. The word “shock” actually has several different meanings in English; once again, take a look at the Learning Guide for this episode for more explanations.
The mechanic also says Sophia needs new brake pads. The “brake pad” is the part of the car that stops the wheels from moving when you want to slow down or stop the car. The “brakes” is the name of the system that stops the wheels; the “pads” are the actual parts that go against the wheel to slow it or stop it.
The mechanic says, “Your battery is very low and should replaced, too.” The “battery” is the part of the car that stores electrical energy. So, the mechanic is saying that the battery needs to be replaced as well.
Sophia says, “I can’t believe it.” The mechanic says, “It’s true. Your tires need to be rotated, too.” The “tire” is the thick rubber part that goes around the wheel. You have a tire with a car, a bicycle, or some other machines. The “tires need to be rotated,” the mechanic says. “To rotate your tires” means to move them in different positions. You have typically two tires in the front, two tires in the back. To rotate them would mean to put the ones on the front on the back, and some on the back on the front.
The mechanic also suggests Sophia get a wheel alignment. A “wheel alignment” is when you make a change to the position of a car’s wheels so that they are all going straight. If you’re driving a car and you let go of the steering wheel – you’re not touching the steering wheel – and you notice your car moves to the left or moves to the right, that could be because you need a wheel alignment, where the mechanic makes sure the car’s wheels are all pointed in the same direction so the car goes straight.
Sophia says, “Well, this is all a big surprise, especially since I just bought this used car a couple of months ago.” The mechanic says, “You did?” – you did buy it a few months ago? He’s obviously surprised. He says, “Well, you got ripped off.” “To get ripped off” means to lose money because someone else has stolen it from you or lied about something – someone has cheated you – this is “to get ripped off.” When someone is dishonest – when someone basically tries to steal your money, that is also another way we can use this expression.
The mechanic says, “Whoever sold this car to you,” or “Whoever sold you this car is a crook.” A “crook” (crook) is another word for a thief, a criminal, someone who steals things. The mechanic asks, “Where did you buy it?” and Sophia says, “I bought it here! I bought this from the owner of this garage.” She’s saying that she bought car where the mechanic works. The place where a mechanic works is called the “garage.” We also use that word for the place where you store or park your car at home or at work, but it’s also used as a word to describe the place where you get your car fixed, a place where there are mechanics.
Sophia says she bought the car “from the owner of this garage.” The owner told her “that it was in tip-top shape.” The expression “tip- (hyphen) top” means perfect, best, excellent, without any problems.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sophia: Is my car ready?
Mechanic: I’m finished with your oil change and I replaced the oil filter. I’ve also replaced the wiper blades in your windshield wipers. But I’ve had a good look under your hood, and your car needs a lot of work.
Sophia: Really?
Mechanic: Yes, you have some serious problems. I bet your engine is running really rough. Your transmission is leaking, your shocks need to be replaced, and you need new brake pads. Your battery is very low and it should replaced, too.
Sophia: I can’t believe it.
Mechanic: It’s true. Your tires need to be rotated, too, and I also suggest getting a wheel alignment.
Sophia: Well, this is all a big surprise, especially since I just bought this used car a couple of months ago.
Mechanic: You did? Well, you got ripped off. Whoever sold you this car is a crook. Where did you buy it?
Sophia: I bought it here! I bought this from the owner of this garage. He said that it was in tip-top shape!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
oil change – the process of changing the thick, black, petroleum-based liquid in one’s car that helps parts move against each other more smoothly
* Is it true that you should get an oil change every 3,000 miles?
oil filter – the small part of a car engine that cleans the thick, black, petroleum-based liquid, taking away dirt and other small objects so that other parts can move against each other more smoothly
* If you use low-quality oil, you will probably need to change your oil filter more frequently because the oil is dirtier.
blade – the rubber and/or plastic piece that is moved across the window in the front of one’s car to move away rain so that the driver can see more clearly
* The wiper blades on his car are very dirty, so he can’t see very well while he drives.
windshield wiper – one of two long metal and plastic bars that rests at the bottom of the window in the front of one’s car and is turned on to move across the window when it is raining, removing water so that the driver can see more clearly
* When it is raining heavily, I turn on my windshield wipers to the highest speed.
hood – the large, flat piece of metal on the front of a car that lifts up so that one can see the engine and other parts underneath
* When Minnie’s car started making a strange noise, she stopped driving and looked under the hood to see what was wrong.
engine – the part of the car that has many moving parts and makes the energy needed to make the car move
* We knew there was a problem when we saw smoke start to come out of the car engine.
transmission – the part of a car that transfers energy from the car’s engine to its wheels; the part of a car that uses energy from the engine to turn the wheels
* Do you drive a car with an automatic or manual transmission?
to leak – to allow a small amount of a liquid to escape by accident, usually through a small hole
* Our roof started leaking during the rainstorm and everything got wet.
shocks – shock absorbers; the parts of a car that make the ride smoother; the parts of a car that make bumpy up-and-down movements seem smaller and smoother for the people riding inside
* The jeep had really bad shocks, so they were in a lot of pain after riding in it all day on unpaved roads.
brake pad – the part of a car that pushes against a wheel when the driver wants to slow down or stop
* Having old brake pads is very dangerous because if they stop working you might not be able to stop your car quickly.
battery – a device that stores energy for a car or another machine
* When was the last time that you changed the battery in your smoke detector?
tire – a thick, rubber circle that fits around the wheel of a car, bicycle, or other machine
* We accidentally drove over some broken glass and now we have to buy new tires.
rotated – moved to a different position; changed with other pieces so that each piece has a different position than it used to have
* The medical students were rotated through all of the hospital’s departments.
wheel alignment – the process of changing the position of a car’s wheels so that they are all facing forward and the car doesn’t go toward the right or left
* Francine’s car is always moving toward the right, so she knows that she needs to get a wheel alignment soon.
to get ripped off – to lose money when another person cheats, steals, and/or lies about something; to be cheated out of money by another person
* The man said that it was a real diamond and gold necklace, but I got ripped off, because after I bought it I found out that the diamonds were fake.
crook – a thief; a criminal; a person who lies and steals things
* That man is a crook! I’ll never do business with him again.
garage – a building that is used to park and/or fix cars
* This is the best garage in town for fixing foreign-made cars.
tip-top – perfect; best; excellent; without any flaws or problems
* Bernie is running ten miles each day to be in tip-top health for her medical exam next month.
Comprehension Questions
1. Why does the mechanic say that the battery is very low?
a) Because it will stop working soon.
b) Because it is placed too low in the engine.
c) Because it is a very low-cost battery.
2. Which of the following car parts are found under the hood?
a) Windshield wipers.
b) Battery.
c) Brake pads.
Answers at bottom.
What Else Does It Mean?
blade
The word “blade,” in this podcast, means the rubber and/or plastic piece that is moved across the window in the front of one’s car to move away rain so that the driver can see more clearly: “If your car’s front window is always dirty, you might want to buy new wiper blades.” A “blade” is also the sharp part of a knife or another tool: “Camilo accidentally cut his cheek with his razor blade this morning.” Sometimes a “blade” is a single, long and flat leaf on a plant, especially grass: “Andrew picked a blade of grass and chewed on it as he walked over the hills.” Finally, a “blade” is often one of the long, flat parts of a machine that moves around in a circle: “Don’t put your fingers into the fan because you might get hurt by the blades.”
shocks
In this podcast, the word “shocks” means the parts of a car that make the ride smoother: “This car has very good shocks, and we almost didn’t notice how bad the road was.” A “shock” can also be a strong feeling of surprise, either negative or positive: “Hearing that she had won one million dollars was a huge shock for everyone.” In medicine, “shock” is a medical problem that happens when one has suffered a major injury, has probably lost a lot of blood, and is very weak: “Rebecca was in shock after the accident, so the doctors kept her in the hospital for two days.” Finally, a “shock” can be the painful feeling that one gets when accidentally touching electricity: “If you touch that electric fence, you’ll get a shock!”
Culture Note
Many car parts were not “mentioned” (talked about) in this podcast script. Here are some common car parts that you may need to talk about in English.
A “rear-view mirror” is the small, rectangular mirror inside a car that is attached to the window in the front of a car and allows the driver to see behind the car without turning his or her head. A “side-view mirror” is one of the two small mirrors outside of the car, on the sides, that let the driver see the sides of the car. Of course, even with one rear-view mirror and two side-view mirrors, cars still have a “blind spot” (the spot on the right-hand rear side of a car that cannot be seen in any mirrors), so drivers have to turn their head to see that part.
Just as a car has a hood in the front, it also has a “trunk” that opens up in the back and is used to “store” (keep something in a place when it is not being used) things. The trunk usually has a “spare tire” (a small tire that can be used temporarily when there is a problem with a regular tire) and a “jack” (a tool that helps one raise a car off the ground to change the tire).
Many cars also have front and rear “bumpers” (a long piece of metal and plastic that goes across the front and back of a car) that protects the car when it hits something else. Another “safety feature” (something that makes the people inside a car safer if there is an accident) that many cars have is an “airbag” (a bag that automatically fills with air in an accident and prevents a person from hitting the inside of the car dangerously).
Comprehension Answers
1 - a
2 - c