= 1508
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 203.
This is English as a Second Language Podcast’s English Café episode 203. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide; you know what that is, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look, while you’re there, at our ESL Podcast Store, with additional courses in business and daily English, and our ESL Podcast Blog, where several times a week we provide even more help in improving your English.
On this Café, we’re going to talk about an organization called the American Red Cross. You probably are familiar with the Red Cross; we’re going to talk about the American version. We’re also going to talk about a very well-known movie, perhaps one of the best-known movies of the 20th century, Casablanca. And as always, we’ll answer a few of your questions as well. Let’s get started.
We begin this Café talking about the American Red Cross. A “cross” is a shape that looks like a “t”, except it would be a small “t”, where you have two lines crossing each other. The cross is, as you know, a religious symbol for Christianity, because the founder of Christianity, Jesus Christ, had, according to the Christian Bible, been “crucified” (or hung; killed) on a cross. It’s also the logo or symbol for the American Red Cross, but it’s a red cross on a white background, and it actually looks more like what we would call in English a “plus” sign (+), because the length of the two lines – the horizontal and vertical lines are equal.
The American Red Cross is part of the International Federation (or association) of Red Cross and Red Crescent Societies. A “crescent” is a curved shape, sort of like a moon, and it’s used instead of the cross in many predominantly (or mostly) Muslim countries. The International Federation of Red Cross and Red Crescent Societies uses both symbols (the cross and the crescent) to be more inclusive, meaning that it is welcoming organizations in both Christian and Muslim countries, as well as people and organizations from countries with other religions.
The American Red Cross and the International Federation are not actually religious organizations however. Internationally, the organization provides humanitarian care to the victims of war. “Humanitarian,” or a “humanitarian organization” is one that tries to make the quality of life better for people, try to make sure that they are treated fairly; it may involve giving them food or giving them a place to stay. Helping poor people is a humanitarian effort, and the Red Cross’s humanitarian work focuses on, among other things, on the helping of war victims, people who have been hurt or lost their homes because of wars. A “victim” is a person who has been hurt by something or someone.
The American Red Cross supports international humanitarian work for the victims of war, but it focuses mostly on what we would call domestic assistance, or helping people here in the United States. The American Red Cross helps the victims of natural disasters, like earthquakes, tornadoes, hurricanes, and floods. Most Americans are probably more familiar with the Red Cross’s work with the victims of natural disasters here in the U.S. than with the victims of war, though they do both things.
The American Red Cross is also involved in other kinds of activities. It provides community services to help poor people, it supports people who are serving in the military and their families, it provides education about health and safety, and it also operates blood drives. A “blood drive” is an effort to get people to donate (or give) some of their blood so that it can be used to help other people who need it. Many large organizations and schools will often organize a blood drive a few times a year, where the Red Cross brings in a van or a large bus and students or employees – members of the organization can go there to donate blood. About four million Americans donate blood to the Red Cross on average each year. If you have surgery at an American hospital, you might, in fact, receive blood that was donated to the Red Cross.
Many Americans also take classes offered by the Red Cross, at least at one point in their life. For example, many people, including young teenagers, have taken classes about how to be good babysitters and what to do if there’s an emergency when they’re taking care of someone else’s child or their own child. Americans of all ages also take classes in first aid so that they can learn to help someone having a medical emergency, for example someone isn’t able to breathe, or someone has a heart attack.
When we were preparing for this podcast a few months ago, there were some big fires in California, close to Los Angeles in a city called Santa Barbara. These fires destroyed or burned down many homes, and there were people who had no place to go – no place to sleep. The Red Cross then set up shelters, where people who needed a place to stay could stay. A “shelter” is a place to stay where you can be warm and dry, usually a place to sleep. For most of us, our shelter is a house or an apartment, but the shelters that the Red Cross provides during a natural disaster might be tents, they might be inside of a large building such as a school gymnasium. People who have been “displaced,” or forced to leave their homes, can stay at these temporary shelters until it is safe for them to go back to their homes, or until they have a new home. You might have read about how the Red Cross helped people during Hurricane Katrina a few years ago, which destroyed most of the city of New Orleans, Louisiana. The Red Cross gave them shelter, food, and water, along with the federal government as well – eventually.
The Red Cross is an important organization, although it isn’t part of the U.S. government, all Americans do rely on the Red Cross to provide help in emergency situations. Many Americans support the Red Cross by donating money or volunteering for the organization.
I volunteered for the Red Cross when I was much younger. Back when I was 12 or 13, I was very active in something called amateur radio, where you would communicate with other people on the radio (this is before the Internet was born), and part of the service that amateur radio operators do is to help provide communication. When there’s a natural disaster like a flood, the phone lines and other means of communication are disrupted, meaning you can no longer use them, so often radio communication is the only way to communicate, and I did some work with the Red Cross as a teenager during one of the floods that took place in the state of Minnesota. Of course, being only 12 or 13, I’m not sure how much help I really provided. But, I do remember doing that, and it was a lot of fun; it was an interesting thing to do despite the fact that it was a disaster for many people.
Now let’s turn to our next topic, about a different kind of disaster called World War II. This is a well-known movie called Casablanca. It’s a classic movie, a movie that has been very successful over time – very popular over time. Even though it is old, most people today seem to know it and have seen it.
Casablanca is a romantic drama that was made in 1942. It’s set in the city of Casablanca in Morocco, in northern Africa, during World War II. Notice we use the phrase “to be set” to talk about where or when a story happens in a movie or book. Star Wars is set in outer space (the expression is really “to be set in”). A new movie that has become very popular recently, based on some books by the same title, is Twilight, and Twilight is set in the state of Washington, which is in the northwest corner of the U.S. Well, Casablanca was set in Casablanca, Morocco in World War II.
It’s a movie is about a man named Rick who is played by – that is, the actor who is Rick in the movie is Humphrey Bogart. Rick owns a nightclub in Casablanca. His former (or ex) lover, Ilsa, arrives in Casablanca with her husband, Victor, but there’s a problem. Victor is wanted by the Nazis, those that were in control of Germany at the time. When we say someone is “wanted by” someone else, we mean usually that the police or the government of some country is searching for that person, trying to punish him or her for doing something wrong. Victor is wanted by Nazi Germany and he tries to escape or get away from Casablanca. Unfortunately, the Nazis are already in Casablanca, and Rick tries to help his former lover, Ilsa. Ilsa admits to Rick that she still loves him, even though she’s married to Victor. To “admit” means to say something that is very difficult to say, maybe because it’s embarrassing or uncomfortable.
Well, I don’t want to tell you the whole plot of the movie, there would be no reason for you to go see it. But, it’s a wonderful story of these three characters: of Rick, Victor, and Ilsa – mostly Rick and Ilsa, and the tensions and the problems that are involved with this particular escape that involves Victor. At least, that’s what they’re going to try to do, I won’t tell you what happens however.
The movie is famous not just because it’s considered one of the great movies of the 20th century; it’s also famous because there are many popular lines from the movie. A “line” is a quote, something that someone says in a movie or a song. The plot has many unexpected changes, the “plot” being the story, of course. But the famous lines from the movie are the ones that if you watch it – if you’re an American and watch it, you will recognize. I remember I first saw Casablanca when I was a freshman or sophomore in college. One of the things that was most interesting was how I recognized so much of the movie even though I had never seen the movie, because these expressions became very famous in popular culture.
One of the most famous lines of all American movies is from Casablanca; it’s “Here’s looking at you, kid.” This is something that Rick says to Ilsa, who’s very beautiful. Ilsa, by the way, is played by the wonderful and very beautiful actress, Ingrid Bergman. Rick is still in love with Ilsa, and when he says “Here’s looking at you, kid,” he means he loves to look at her, she’s so beautiful, and he wishes, one supposes, that he could look at her forever, but that may not be possible.
A couple of other of the famous lines from Casablanca that most Americans have heard, even if they don’t know where the line comes from (they may not even know it comes from Casablanca) is “Round up the usual suspects.” There’s a point in the movie where someone is killed, and the captain in charge (someone who is in charge of keeping the law, such as it was) says, “Round up the usual suspects.” “To round up” means to get together, to gather, to bring together. “The usual suspects” refers to people who they normally think would have committed this crime. The police have people who they suspect commit many crimes, and so when there’s a crime they may go and talk to those people even though they don’t have any specific evidence about them. There was another wonderful movie made called The Usual Suspects with Kevin Spacey. This is where that line comes from, or at least was made popular.
My favorite line from Casablanca is when Rick (who remember is the main character who owns a nightclub – who owns a bar where people dance in Casablanca) says to another one of the characters, “I came to Casablanca for the waters.” “Waters” could refer to rivers or oceans, lakes. But Casablanca is in the middle of a dessert and there are no waters, so the other character says, “The waters? What waters? We’re in the dessert!” and Rick then says, “I was misinformed.” “To be misinformed” means that someone gave you the wrong information. Of course, he didn’t really come to Casablanca for the waters, but it’s a wonderful line, the idea that you would go somewhere for something and then say, “Oh, I was misinformed.” For some reason I found it very funny.
So, if you have a chance to see Casablanca, if you haven’t seen it already, I strongly suggest you do, and possibly see it in English this time. The English is somewhat slower in the older movies, or least there was more of a pause – more of a break in between the lines of the dialogue in some of the older movies.
Casablanca won three Oscars, also called the Academy Awards. It won three Academy Awards including Best Picture. In 2005, one of the big magazines here in the United States, Time Magazine, included Casablanca on its list of the 100 best films. I think you’ll enjoy watching it, if you have the opportunity. And again, try watching it in English this time for, you’ll be able to hear some of these famous lines.
Now let’s answer some of the questions that you have sent us.
Our first question comes from Veg (Veg) in Moscow, although originally from Armenia. The question has to do with the meaning of the words “estimate,” “appreciate,” and “evaluate.”
An “estimate” or “to estimate” means to judge or predict a situation, or to try to calculate the cost of something. “The builder estimates that it will take four months to build a new house.” He estimates; that’s his estimate, if we use it as a noun. Notice a slight change in pronunciation: “estimate” and “to estimate.”
“Evaluate” means to determine the value of something, not necessarily something that costs money. A teacher could evaluate a student’s writing, for example.
“To appreciate” means a couple of things; one meaning is to increase in value or number or price. “The value of our house appreciated 20 percent in the past five years.” That means the price went up, it is worth more now.
So you have these three words: “Estimate,” which means to try to judge or predict a certain situation, including, possibly, the price of something or the length that something will take. “To evaluate” almost always means judging the worth or value of something, and “to appreciate,” when we talk about value, means to go up.
The verb “appreciate” has another meaning, which means to understand the worth or quality of something; not necessarily an increase but simply an understanding. “I appreciate good cooking,” I understand the value of it.
“Estimate” usually is something you do after you look at facts or other information. Someone may come to fix your house; they’ll first look at the problem, think about how much it will cost to fix it, and then estimate how much the price will be. “Evaluate” is usually to judge how good something is, to see how worthy it is. So if, for example, you have someone who fixes your house, your wife or husband may come home and evaluate the quality of the job. Did they do a good job? Did they do a bad job? Workers – employees are often evaluated by their bosses. So there are some differences, then, between “estimate” and “evaluate.”
I should also say that the verb “appreciate” is often used in thanking someone. “I appreciate your efforts,” you’re thanking them for what they did.
Raul (Raul) in Peru wants to know the meaning of the expression “to let (someone or something) be.” Someone says, “Oh, just let her be,” or “just let him be,” what does that mean?
“To let (someone or something) be” means to leave it alone, not to disturb it, not to bother it. A variation on this expression is “leave it be”: “Oh, just leave him be.” Both “leave” and “let” are, in this context, the same as “allow.” A similar phrase is “to leave (or let) someone alone.” “Leave it alone” means don’t touch it, don’t bother it, don’t concern yourself about it.
You may also be familiar with the famous Beatles song called “Let It Be,” which was a popular song from, I believe, the year 1970. That was more about a philosophy or attitude toward life, meaning not being too concerned about things that go right or go wrong. I’m not sure if that’s a good philosophy or not, but rather than talking about it more, we’ll just let it be!
Finally Juergen, whose name I am almost certainly mispronouncing (Juergen), in Germany wants to know the difference between an “aim” (aim) and a “goal” (goal).
An “aim” is a clear intention: “My aim is to lose 10 pounds this month.” That’s probably too much, but that’s my aim. You could also say the same sentence with “goal”: “My goal is to lose 10 pounds this month.” So those two words can mean the same thing.
“Aim” has an additional definition, which is to point something in a certain direction. For example if you have a gun, someone may say, “Don’t aim your gun at me,” meaning don’t point your gun like you are going to shoot me; don’t point your gun in my direction.
So, “aim” and “goal” can both mean a clear intention to do something, or something that you want to achieve or accomplish. “Goal,” however, is often used to mean something very definite, something very specific. Especially in schools or in organizations when they talk about their goals, they usually are talking about something very specific they want to achieve.
“Goal,” also, unlike “aim,” is not used as a verb, whereas “aim” can be used as a verb. Someone may say to you, “What do you aim to do?” (what is your aim), but you would not say “What do you goal to do?” “Goal” would only be used, at least with this meaning, as a noun. “Goal” is also the word we use when in what we call soccer, what the rest of the world calls football, someone puts the ball into the other team’s net, and they say “Goaaaaal!” Just like that; I promise I will never do that again!
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
cross – a shape or symbol that looks like a lower-case “t” with two straight lines that cross each other at 90-degrees; “ ? ”
* The church is easy to find. It’s the building with the cross on the roof.
crescent – a curved shape like the moon
* In the sky, a crescent moon is not as bright as a full moon.
humanitarian – concerned with making the quality of life better for people; efforts to make sure that people are treated fairly
* Part of our humanitarian effort is to bring donated clothing to people who lost their homes in the flood.
victim – a person who has been hurt by something, such as a crime, accident, or someone else’s bad actions
* In court, the family of the victim watched the trial and hoped that the criminal would be found guilty.
natural disaster – something that happens in nature that causes a lot of damage, injuries, and/or deaths, such as earthquakes, tornadoes, hurricanes, and floods
* In case of a natural disaster, everyone should gather at the local high school and wait for instructions.
blood drive – an effort to get people to donate some of their blood so that it can be used to help other people who have medical problems
* The blood drive is voluntary, but we hope that all employees will choose to give blood.
first aid – actions taken in a medical emergency to help people until doctors or other medical professionals arrive
* Sam’s arm is bleeding. We’ll need to give him first aid until the ambulance arrives.
shelter – a place to stay where one can stay warm and dry
* For people without jobs, having food and shelter are among their biggest concerns.
to be set in – where and when a story happens in a movie, television show, play, or book
* This book is set in the American Southwest during the late 1900s.
to be wanted by – having the police or a government searching for a person, usually to punish him or her for doing something wrong
* That man is wanted by the U.S. government for not paying his taxes.
to admit – to say something when it is very difficult for one to say it, perhaps because it is embarrassing or uncomfortable
* I don’t like to admit it, but I was as scared as my children to fly in an airplane for the first time.
plot – story in a book, movie, play, or television show
* I stopped watch that TV show, because the plot became so confusing that I couldn’t follow it.
to estimate – to give an approximate number or value to something; to judge or predict an amount or cost
* The plumber estimated that it would cost $300 to replace our sink with a new one.
to evaluate – to judge the worth or value of something
* Why don’t you bring the painting to my house and I’ll ask my artist friend to evaluate it for you?
to appreciate – to understand the worth or quality of something
* Our children can appreciate the value of money, because they have to work and save up for anything they want to buy.
to let (someone/something) be – to leave someone/something alone; to allow something/someone to exist as is; to not bother to change something or be concerned with it
* Although Lonnie is crying, we should let him be. I don’t think he wants to talk about his problems right now.
aim – a clear intention; something one tries to do or achieve for the future, often used for something general; goal
* Sally’s aim in saving all of her money now is so she can open her own business sometime in the future.
goal – a clear intention; something specific one tries to do or achieve for the future; aim
* Benicio’s goal is to lose 20 pounds in six months.
What Insiders Know
The classic film Casablanca is “memorable” (difficult to forget) for its beautiful story and “exceptional” (outstanding; excellent) acting, but it also had memorable music. One of the most “notable” (important) scenes involves a “duel” (fight between two people or two groups) of songs.
A Rick’s cafe where the movie is set, there is a group of Nazi soldiers, who begin to sing a German song. To “counter” (fight against) this show of German “patriotism” (pride in one’s country), the piano player begins to play the French “national anthem” (national song), “La Marseillaise.” The two songs battle each other and allow the characters to show their strong feelings for each side in the war.
Another memorable musical element of Casablanca is a song from its “soundtrack” (album/CD of music from a movie) called “As Time Goes By.” It is played during some very emotional scenes from the movie, and this song has become an American “standard” (song known by most people and is sung a lot). In lists of the most memorable and loved songs from movies, it is “consistently” (almost always; frequently) placed near the top of the list.
Here are the most famous lines from the song:
You must remember this
A kiss is just a kiss, a sigh is just a sigh.
The fundamental things apply
As time goes by.
sigh – a long deep breathe, usually taken when one is tired, relieved, or sad
fundamental – the most important part; basic
to go by – to pass, usually used for time