= 1547
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 242.
This is English as a Second Language Podcast’s English Café number 242. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to talk about a serious subject: preventing violence in American schools, especially after the 1999 event in a high school in Colorado. We’re also going to continue our series on American Territories, this time we’ll talk about the U.S. Virgin Islands. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin by talking about preventing violence in American schools. A “tragic” (tragic), or very sad event occurred in April of 1999 at a high school in Columbine, Colorado, near the state capital of Denver, Colorado. Colorado is located in the western – central western part of the U.S. One morning at the high school, two friends entered the school and started a campus massacre. A “campus” (campus) is the area and the buildings of the school, so the buildings and the area around it. We talk about a campus for a high school; it could be for a university. Some companies also talk about their headquarters or their offices as being on a campus. A “massacre” (massacre) means an unnecessary and random killing of many, many people all at once. We use the word “massacre” only for very serious crimes; it could be something that happens during a war, for example.
On this morning that the two students came into the high school, there were twelve students and one teacher who were killed by gunshots at Columbine High. Twenty-four other people were injured. After these two young boys – young men did this they killed themselves. The two friends were considered “outcasts” (outcasts) at the school. Many people said that they were bullied by other students before this event happened. To “cast” (cast) means to send someone away because he or she is no longer welcome in a particular group or a particular area. That’s one meaning of the word “cast.” An “outcast” refers to the people who are not accepted by their peers, the people around them; they probably don’t have very many friends. They feel unpopular. Outcasts are sometimes “bullied” in schools, which means they are made fun of; we might say they are “teased” (teased), or insulted by those students who are perhaps physically stronger or more popular. The verb is “to bully” (bully). “Bully” can also be a noun to describe a person who bullies others.
The massacre at Columbine started a national, or nationwide discussion about topics related to trying to prevent this from happening again. These topics include gun control laws, the possible role of violent movies and violent video games, bullying at schools, and the general issue of school security. We’ll talk a little bit about each of these things that were discussed after Columbine.
Gun control laws refer to how easy it is to buy or to get a gun. As we’ve talked about before on the Café, the U.S. Constitution allows people to own guns, but many people disagree about how easy or difficult it should be for someone to actually go and buy one. “Minors” for example, people who are under the age of 18 are not allowed to buy a gun, but each state has different laws about this. There has been a debate about what kind of laws we should have to prevent this sort of tragedy from occurring again.
Many people believe that if we had stronger gun control laws we would have prevented this problem. In the State of Colorado, there is no limit on the number of guns one person can own. A person who owns multiple guns might not immediately notice, for example, that one of them has been stolen. In this case, the two boys stole guns from their parents.
Other people believe that violence in movies and video games contributed to this school violence. They “claim,” or believe, and say that playing violent video games, for example, makes children and teenagers less sensitive to real-life violence, meaning that playing these games makes it easier for people to commit violence in real life. People who believe this think children should not be allowed to watch violent movies or play violent video games. I have never played a violent video game; in fact, I haven’t played a video game since 1983. I guess they have become more sophisticated since then. In any case, there has been a long debate about the influence that movies and video games have on children. Some people think watching certain movies is good for children; then it would seem logical that watching some movies might be bad for children, but I have not looked at the research on it – the scientific studies about it.
Many of the students involved in these school shootings, the use of guns at school, have at one time been bullied; they’ve been made fun of by other students. They generally were not accepted into popular cliques of other students. “Cliques” (cliques) are small, exclusive groups of people, like for example the popular kids in school. Of course, a lot of people aren’t part of the popular clique – me for one, I certainly was not – but they don’t necessarily organize school shootings, either. I did not organize any school shootings, though some of my teachers might have wanted to shoot me!
There are lots of things that kids can be bullied about. They can be bullied about their weight, how smart they are, how they look, how they act, who their family is. When someone is bullied this way, they may become very sad – very depressed, or they may become very upset and try to retaliate. “Retaliate” means to take revenge, to get back at others, to somehow pay them back, make them suffer the way you suffered. At Columbine, the students who had been bullied retaliated against other students through this violence.
Another idea for preventing school violence is to have better school security systems. Many schools have security systems, including metal detectors, that if you walk through them like at an airport, they will indicate if you have a gun on you. There are other systems as well, including security officers on campus. When I worked at a public school back in Minnesota we had security officers on campus, although my high school – the one I attended did not have any security guards.
Unfortunately, none of these ideas has managed to put an end to school violence, although they may have reduced it somewhat. So, school violence is a problem in American schools. Not just schools in what we call bad areas of the city, where there’s a lot of crime outside of the school, but it’s also a problem at smaller rural schools or schools that are out in rich suburbs, like Columbine.
We go now from that happy topic to on our series on American Territories. Today we will talk about the U.S. Virgin Islands. This is a group of islands in the Caribbean (or Caribbean, either pronunciation is possible). When we say the Caribbean, we’re referring to the Caribbean Sea, which is south and east of the U.S.; it’s also east of Mexico. The Caribbean refers to the Caribbean Sea, as well as the area in the southeast part of what is called the Gulf of Mexico. The main islands that make up the U.S. Virgin Islands, which are located in the Caribbean, are Saint Croix, Saint John, and Saint Thomas. There are about 108,000 people who live on the Virgin Islands, so not very many.
The United States purchased, or bought, these islands in 1917 from Denmark – the country of Denmark, for 25 million dollars. In 1927, the U.S. granted American citizenship to all of the islands’ inhabitants. “Inhabitants” are the people who live, and we would say reside in a certain place. The verb is “to inhabit” (inhabit).
Today, tourism is the primary economic activity for the Virgin Islands, people coming to visit to take a vacation on the Islands. The U.S. Virgin Islands are a good place for tourism, because like the islands in the Caribbean sea around it, it has very warm climate, so Americans may consider it “exotic” (exotic), meaning unusual, unique, interesting, sometimes foreign.
The U.S. Virgin Islands are famous for their beaches, as well as the unique, or different, cultures that you will find in the different towns on the islands. Many people like to visit the Virgin Islands because they can see the beautiful blue ocean and the beautiful sandy beaches, which are popular for vacations. “Sandy” comes from the word “sand” (sand), which is what you find next to the ocean, what you walk on or lay on. The Virgin Islands, then, are popular destinations for people who want to have a nice vacation. Diving is popular on the Virgin Islands. “Diving” refers to scuba (scuba) diving. This is where you put on a mask and have a tank of oxygen (a tank is a container, something that holds something else, in this case oxygen so you can breathe), and you can swim down below the water and look at everything that is below the water’s surface, on the bottom of the ocean in the case of the Virgin Islands. You can also see fish and underwater plants that you can’t normally see when you are swimming. I have never been scuba diving, and kind of doubt I ever will!
People who go to the Virgin Islands often go there for what some people call “destination weddings.” A “destination” is a place to which you are traveling. If I am going from Los Angeles to St. Paul, my destination is St. Paul; it’s where I am trying to get to. A “destination wedding” is when a couple will fly to another place, perhaps even another country to get married. It’s very popular, for example, if you go to Hawaii, to Honolulu, you will often see young Japanese couples who fly there to get married. That would be a destination wedding. The Virgin Islands is also a popular place for destination weddings; it’s also popular for honeymoons. The “honeymoon” is the period of time, usually a week or two weeks after you get married when you go and relax and do what one does after you get married.
There are also many cruises to the Virgin Islands. “Cruises” are vacations that happen on large ships called cruise ships. They typically travel between islands or from what we would call the mainland – United States. The “mainland” are the 48 states that are on the North American continent that touch each other, so not Hawaii or Alaska, and of course not the territories such as the Virgin Islands, which are islands.
The climate of the Virgin Islands, as I mentioned, is very pleasant. The daytime temperature is usually around 78 degrees Fahrenheit. The only bad time to be on the islands is during hurricane season. “Hurricanes” are large, dangerous storms that go through that part of the world. In 1995, Hurricane Marilyn hit Saint Thomas Island, one of the three main islands, and over 10,000 people were left without a home.
The official language of the Virgin Islands is English, as it is for all of the American territories, although Creole is spoken in informal situations. Creole is a language that is based on English, but has West African words and grammatical structures.
U.S. citizens can travel to the Virgin Islands easily. You can fly from many U.S. cities. And of course, if you are a U.S. citizen you don’t need a passport to visit the Islands. Sounds like a good place for all of us to go on vacation. I’ll see you there next week!
Now let’s answer a few of your questions.
Our first question comes from Ricardo (Ricardo) in Spain. Ricardo wants to know the difference between “although” and “even though.” Both “although” and “even though” mean but, however, in spite of the fact that. It’s possible to use these two interchangeably, one for the other, but there is a general rule about when we use one and when we use the other that we follow most of the time in English.
“Although” is used when the part of the sentence – the part that comes right after the word “although” is positive, and the result is negative. For example “Although I studied for my test last night, I did not pass it today.” So the first part, with “although,” that’s positive; I did something, but I didn’t pass my test anyway. Here’s another example: “There is not any more room on this bus, although another one is coming in two minutes.” “Although” is on the second part of the sentence, but after it is a positive statement: there is another bus coming. That’s the good news; the bad news is that there isn’t any room on this bus. So once again, “although” with the positive condition, the other part of the sentence with the negative condition.
“Even though” is just the opposite. “Even though” is followed by something that is negative, but the result is still positive. For example: “Even though my brother did not study for his test, he got a good grade.” He passed his test. So what follows “even though” is a negative – he didn’t study, but the second part of the sentence is positive – he did get a good grade. Or I could say, “This cake turned out great (it ended up tasting good), even though I didn’t follow the recipe.” I didn’t follow the instructions. Once again, after “even though” is a negative statement – I didn’t follow the recipe, but the result was still positive.
Again, those are very general rules. Sometimes we don’t always follow them.
José Ignacio (José Ignacio) in Chile wants to know the meaning of the word “lite” spelled (lite). “Lite” is a different spelling for (light); (lite), when it’s spelled that way, is usually referring to something that is less than the full version of a product. For example, if you like to drink beer – I don’t, I don’t like beer. But if you like to drink beer, you can buy certain lite beers. These beers have less calories than the regular beers; they’re not as strong, usually.
“Lite,” when it refers to software for your computer or for your phone, means that it is not the full version of the software; you’re getting part of it but not all of it. For example, you might only get certain features; you might not be able to get tech support – technical support, help from the company that made it if something goes wrong. There might be advertisements on the product. These are typical of lite versions of software for computers.
Sometimes the word is used to describe something that is less important, less meaningful, lacking a certain substance. Sometimes it can be used as a criticism – as a negative way to describe something: “Today’s newspaper is really a newspaper lite.” It’s not what it should be; it’s lacking something; it doesn’t have something. “Lite” (lite) can also be used to describe a softer kind of music.
So those are the various meanings of the word “lite” when it is spelled (lite).
Finally, Yoss (Yoss) in Israel wants to know the difference between the words “rate” (rate) and “rank” (rank).
Both “rate” and “rank” have some common definitions; they can both mean to decide on the value of one thing compared to another, or the worth of one thing compared to another. If there is a competition or a contest, sometimes there are judges who will rate the people competing. At the Olympics, there are judges for figure skating that rate the skaters, they give them points, or in the Summer Olympics, for gymnastics.
You can rate or rank almost anything that can be compared: “How do you rank that song?” “I rank it about a 5 out of 10,” meaning I don’t rank it very high – I don’t rate it very high.
There are some special meanings of these two words however. “Rank” Is especially used when we are talking about the position of something compared to another. “My car is ranked higher than your car in this car magazine,” for example. Or, “His test scores were ranked above the ones of the other students in the class.” So it’s his position; it’s not merely comparing him, it’s saying where he is, more precisely, compared to others. Sometimes we give a specific position. For example: “California ranks number one in the United States in murders.” Probably pretty close to that if it’s not number one! “Iowa ranks 50th of the states that you would want to visit,” meaning it’s the last state you would ever want to visit. I’m just kidding. No, seriously, you don’t want to go to Iowa for anything!
“Rate” means specifically to think about and make a decision about someone. “I rate time with my family as very important.” I think about it and I decide it is very important compared to everything else. “Rate” as a noun can be used to talk about the quantity of something. For example, if you go to an English tutor, you may ask what his rate is, meaning how much money does he charge per hour or for every 30 minutes. We can also talk about “rate” sometimes to mean percentage: “What is the rate of unemployment in the Unites States?” What percent of the people do not have a job?
We hope that you rank ESL Podcast number one in your list of English language learning methods. You can email us at eslpod@eslpod.com. We don’t have time to answer all of your comments and questions, but we will try to get to as many as we can.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
campus – the area or the grounds that contain all of the buildings of a school, college, or university
* Are there places for students to eat on campus or do we need to go elsewhere to get a meal?
massacre – the unnecessary and random killing of many people at one time; the killing of a large group of people in a short amount of time
* The massacre of animals on Luke’s farm was a senseless crime.
outcast – people who are not accepted by their peers and do not have many friends; people who are not accepted by society
* There will be a new student in our class and I don’t want her to be made to feel like an outcast.
bullied – teased in a mean way or insulted by someone who is stronger or more socially popular
* Tom felt like he was bullied by his co-workers to keep quiet about his unusual ideas.
minor – a person under the age of 18 who is not yet considered an adult legally
* In this state, you can be arrested for helping minors buy alcohol.
to claim – to say something is true, usually without proof or evidence
* Giorgio claimed that he saw a giant bear on his camping trip, but I’m not sure I believe him.
clique – small, exclusive groups of people, such as the socially popular students in school
* This school has so many cliques that it’s hard for a new student to fit in.
to retaliate – to take revenge; to get back at others and to repay them for something bad they did to one
* Lisa drove my car without asking me, so I’m retaliating by riding her bike without her permission.
Caribbean – the region of the Caribbean Sea and its islands, including the coastlines southeast of the Gulf of Mexico
* Because there are fewer tourists, this a great time of year to visit the Caribbean.
inhabitant – a person who lives in a certain place; the people who make up the population of a certain place
* Do all of the inhabitants of this region speak both French and German?
exotic – foreign, unusual, unique, and interesting
* For the party, Doddy dressed in an exotic costume with feathers and silk scarves.
diving – scuba diving; a sport where you put on a mask and an oxygen tank and swim down and explore the bottom of the ocean
* Before I go diving, I need to learn how to swim!
destination wedding – when a couple decides to get married far away on vacation, inviting just a few friends or relatives to join them
* The islands of Hawaii are very popular for destination weddings.
cruise – vacations that occur on very large ships that hold hundreds of people and travel between different locations
* We took a cruise that traveled around Alaska, and we saw scenery and animals we’d never seen before.
although – but; however; in spite of the fact that
* Although I love Indian food, I don’t want to have it every night of the week!
even though – but; however; in spite of the fact that
* We still want to go for a walk outside, even though there’s a chance of rain.
lite – a version of software that is simpler or that doesn’t have all of the features that are in the regular or full version; something that contains less fat or sugar than the original
* Sam is trying to lose weight and only drinks lite beer.
to rate – to decide the quality, worth, or value of something compared to others
* On a scale of 1 to 10, I rate this movie a 7.
to rank – to decide the position of something compared to others based on its quality, worth, or value; to have a position or spot compared to others
* Our high school football team is ranked number three in the city.
What Insiders Know
The Television Show Jackass
American parents have many things to worry about, including violence in schools. Many are also concerned about violence in the “media” – on television, in movies, on the Internet, and in video games. One television show that “sparked off” (started) a lot of concern and “criticism” (negative judgment) was a television show called Jackass.
The television show Jackass was first shown on the music cable television station MTV in 2000. “Jackass” is an informal and insulting term for a stupid person, and the show itself consisted of people, usually young men, performing different dangerous, silly, and difficult “stunts” (physical tricks) and “pranks” (practical jokes; jokes to make fun of other people). Many of the people who did the stunts and pranks got injured, but that was simply part of the show.
Considering the dangerous and violent content of the show, at the beginning and throughout each episode, there were written warnings for people not to “imitate” (do the same thing as what they’ve seen or heard) what they see on the show at home. “Nevertheless” (despite this; even so), many parents blamed the show for causing the deaths or injuries of teenagers and children who tried to imitate what they saw performed as part of the show.
In 2001, a politician, U.S. Senator Joseph Lieberman from the state of Connecticut, “denounced” (publicly called something wrong or bad) the show and said that it was responsible for a 13-year-old boy from Connecticut who received serious burns after he tried to imitate one of the stunts on the show. Under pressure from Senator Lieberman and others, MTV first decided not to air episodes before 10:00 p.m., and then later, to not air the program at all. The show went “off the air” (was no longer shown) in 2002. Since then, there have been two “feature” (major) Jackass films, and in 2007, a Jackass videogame was released.