= 1552
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 247.
This is English as a Second Language Podcast’s English Café episode 247. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to talk about a famous English filmmaker, who however worked largely in the United States, Alfred Hitchcock, specifically focusing on one of his most famous movies Psycho. We’re also going to discuss one of the most famous speeches in American history, also one of the shortest, the Gettysburg Address. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café begins by exploring the life and work of Alfred Hitchcock. Hitchcock was a very famous “filmmaker,” someone who makes movies, and “producer,” someone who helps organize the movie, largely the funding for the movie. He focused on what we would call suspense and psychological themed movies. Movies with these themes are often called “thrillers,” which are very exciting but uncertain stories kind of like mysteries; you don’t know exactly what is going to happen but you are very excited to find out.
Hitchcock, himself, was born in 1899 at the end of the 19th century, and began his career – began his work in the United Kingdom in Great Britain, but moved to Hollywood, California, here, that is, to Los Angeles to continue his career. In 1956, he actually became an American citizen, so we can call him our own. Throughout his filmmaking career, Hitchcock directed more than 50 feature films – that is, more than 50 movies. He worked in the filmmaking industry – the film making business for more than 60 years, quite a long time. Some experts believe that he was perhaps the most talented – the best, or one of the best filmmakers in history.
Hitchcock produced many films throughout the 1930s, 1940s, and 1950s. In 1960, however, he released a film – he made his film available, it began to show – called Psycho. That’s probably his most recognized film, the film known by the largest number of people. The word “psycho” commonly refers to someone who is a psychopath. A “psychopath” is a crazy person, a person with a mental illness that often leads to violence. The film Psycho was adapted from a novel that was written one year before the movie was produced. “To adapt” means to adjust to different conditions or different circumstances. When we talk about making movies, it means to take a book and turn it into a new form, what we would call a screenplay, that then is used to make the movie. Typically, adapted screenplays, as they’re called, are shorter – have less than the book would have because, of course, you only have two hours at most.
If you haven’t seen the movie, or even if you have, I’ll give you a little summary of the plot – what happens in the movie. Psycho is about a secretary named Marion who steals 40,000 dollars from her employer – from her company so that she can marry her boyfriend. She leaves town – she leaves where she’s living before she gets caught by the local police. She then trades in her car; she goes to a place that sells cars and gets a new car, giving then her old car. And during a storm, when it’s raining out very heavily, she goes into a motel called the Bates Motel. Once there, the motel’s “proprietor,” the owner, a man named Norman Bates, invites her to dinner at his family’s house, which she thinks perhaps is rather nice.
When Marion arrives at Norman’s house, she hears him and his mother arguing about her being there, so Marion and Norman return to the hotel and they eat their dinner there; they don’t stay. After the dinner, Norman spies on Marion, meaning he watches her through a small hole he has in the wall. Well, you know something bad is going to happen to someone in the movie, and in fact someone does get murdered, and the body – I won’t say whose – is put into a nearby swamp. A “swamp” (swamp) is a very wet area of land – lots of water, but also grass and other things.
Part of the excitement – part of the suspense of the movie is when people begin to look for the person who is murdered, and try to trace this person’s path – where they went. “To trace” (trace) means to find someone by investigating and searching, so that’s part of the excitement. At the end of the movie, there is a very what would probably call disturbing, unexpected, strange, frightening conclusion. Again, I won’t tell you what it is, but I think you will enjoy the movie if you go see it.
Psycho was very successful as a movie. The actor who played Norman, Anthony Perkins, became famous from the film and went on to have a leading role – that is, to be the most important person in and number of other movies.
The most famous scene – the most famous part of the movie is what is called the shower scene, because Marion, our secretary/thief, is taking a shower and something happens when she’s taking her shower, and that’s part of the excitement of the movie.
Today, you can actually come here to Los Angeles and go to Universal Studios, where they will show you where the film was made, and you can actually see the Bates Hotel. I’ve done this a couple times by myself and with students, showing them the place where the movie, at least that part of the movie was filmed.
Psycho was only one of Alfred Hitchcock’s successful films. Others include Rebecca, which was released in 1940; Rear Window, released in 1954; Vertigo, which was released or came out, we might say, in 1958; and one of my favorites North by Northwest, released in 1959.
Hitchcock lived to a very old age; he was 80 years old. I remember when he died. Four of his films won the Best Picture Oscar award, and he received around 50 nominations for awards – for Academy Awards, as we call them, which are the highest awards for movies in the U.S. He’s still considered one of the great directors of all time. I’ve seen most his movies, and I think you would enjoy them if you like thrillers, like I do.
Now we’re move on to not a thriller, but a very important part of American history, the Gettysburg Address. An “address” is simply another word for a speech. The Gettysburg Address was given by one of our most famous presidents, President Abraham Lincoln, during the U.S. Civil War. Like most civil wars, the U.S. Civil War was a very bloody one; that is, many people were killed during the war, and in 1863 there were more than 160,000 soldiers who fought in a particular battle called the Battle of Gettysburg. The Battle of Gettysburg took place in Pennsylvania, which is in the central east part of the United States.
The Battle of Gettysburg was an extremely important one because it is, or was what we would call the turning point in the Civil War. A “turning point” describes an important moment when some change takes place, especially in something like a war. The Battle of Gettysburg was a turning point, because it was clear afterwards that the Northern Army – the Union Army of Lincoln would probably win the war. The battle killed more than 7,500 men and women, mostly men – soldiers, even though the town where the battle took place, Gettysburg, Pennsylvania, only had about 2,400 residents. The high number of deaths was a huge shock for this small town.
After this battle, the governor of the state of Pennsylvania allowed the city of Gettysburg to purchase – to buy the land and create a national cemetery for the soldiers. A “cemetery” is an area of land where you put dead bodies. It’s where you have what we called graves, which is the place where after you die they put your body. Once the cemetery was finished, many politicians were invited to the dedication of the cemetery, and the President of the United States, Abraham Lincoln, was one of those who was invited. A “dedication” is a ceremony that officially recognizes – we would say officially marks (indicates) the completion of a building, a monument, in this case a cemetery.
President Lincoln arrived the day before the dedication, which was on November 19th, 1863. He finished writing his speech after he arrived. On the next day, there were approximately 15,000 people who attended the dedication ceremony.
The goal of Lincoln’s speech was to keep their spirits up for the rest of the war. “To keep (someone’s) spirits up” means to stay positive, to encourage the person, to try to get them to see there is hope. At the time of the speech, the Civil War had already killed more than 250,000 soldiers, and Lincoln was becoming, not surprisingly, an unpopular president. Therefore, he wanted this speech to leave a good impression, a good feeling, a good idea in people’s minds about the war.
I’m going to read the Gettysburg Address – it’s fairly short – first and explain it as I read it. Then we’ll go back and I’ll give you the complete speech without my explanations, which I think by that time you will be able to enjoy more and appreciate.
The Gettysburg Address begins with one of the most famous lines now in American history: “Four score and seven years ago our fathers brought forth on this continent a new nation.” “Four score” means 4 times 20. A “score” is an old word in English for 20, so “four score and seven” would mean 87 years ago; 87 years ago from 1863, if you calculate, will give you 1776, which was when the United States declared its independence from Great Britain.
So, “Four score and seven years ago our fathers brought forth on this continent a new nation.” When Lincoln says “fathers” he means the “founding fathers,” the politicians, the men who were extremely important in leading the country during America’s War of Independence from Great Britain. “To bring forth” means to invent or create. So, the founding fathers “brought forth on this continent (the North American continent) a new nation, conceived in liberty (that is, begun in liberty – in freedom), and dedicated to the proposition that all men are created equal.” “Dedicated to” here means with the goal – with the purpose of creating a society where all men (“men” here means men and women) are created equal.
Next Lincoln says, “Now we are engaged (we are taking part) in a great civil war, testing whether that nation, or any nation, so conceived and so dedicated, can long endure.” “Now we are engaged in a great civil war, testing (in other words, putting to the test – determining if it is true) whether that nation (the United States), or any nation (any country), so conceived and so dedicated,” that is, a country that was begun the way the U.S. began (“conceived in liberty,” remember Lincoln said, which had the same goals and purposes of this country, “dedicated to the proposition that all men are created equal”), “whether that nation can long endure.” “To endure” means to last, to go a long time. So, will our country continue?
He says, “We are met on a great battlefield (a place where the battle – the fight took place) of that war. We have come to dedicate a portion (a part) of that field (of that area of land), as a final resting place (as a cemetery, the place that you will go at the very end) for those who here (in this place) gave their lives that nation might live (they died so we could continue living). It is altogether fitting (it is completely appropriate) and proper (correct) that we should do this (this is the right thing to do).”
“But,” Lincoln continues, “in a larger sense, we cannot dedicate, we cannot consecrate, we cannot hallow this ground.” “To concentrate” means to make holy; it has a religious meaning to it. “To hallow,” again, “hallow” means holy – to make holy; in this case, to honor this ground, this place where these men died and will now be buried.
He continues, “The brave men, living and dead, who struggled here (who fought here), have consecrated it (they made holy by their sacrifice), far above our poor power to add or to detract.” In other words, their actions are much more important than anything we can do. We don’t have more power than they do; we cannot add or subtract – here he says, “detract,” to take away from. “The world will little note (meaning will not even notice), nor long remember what we say here (there, Lincoln was wrong; we are of course remembering it right now), but it can never forget what they did here (what these soldiers did here). It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced.” What he’s saying here is that it’s our job, to dedicate ourselves – to have as our goal – to finish or complete the unfinished work which the soldiers who fought here have thus far (have so far) nobly advanced. “To advance” means to move forward. “Nobly” here means to have a high moral status.
Lincoln continues, “It is rather for us to be here dedicated to the great task (the great thing we have to do) remaining before us – that from these honored dead (the soldiers) we take increased devotion to that cause for which they gave the last full measure of devotion.” “Devotion” means dedication; it’s similar, but it has, again, a more religious meaning, or can. He’s saying that we need to be more dedicated to this cause – this cause of winning the war because that was the cause these men died for. “They gave the last full measure of devotion,” that was the last thing they did, dying in order to win the war.
He continues, “that we here highly resolve (we promise) that these dead shall not have died in vain.” When something is done “in vain” it was done for no reason; it eventually wasn’t successful. “That this nation,” he continues, “under God (being led by or looked over by God), shall have a new birth of freedom – and that government of the people, by the people, for the people, shall not perish from the earth.” “To perish” (perish) means to die, basically. So what he’s saying is that we don’t want our government, a government that is of the people – it is by the people, it is created by the people, and it is for the people. This phrase – these phrases are related to the Declaration of Independence, which begins “We the people.” It’s saying we represent the people. Lincoln is saying that the government that our founding fathers began is threatened; it may perish unless we continue to fight. We need to “prevail,” that is we need to succeed, to win.
I’ll now read the entire address again without interruption:
Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal.
Now we are engaged in a great civil war, testing whether that nation, or any nation, so conceived and so dedicated, can long endure. We are met on a great battlefield of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.
But, in a larger sense, we cannot dedicate, we cannot consecrate, we cannot hallow this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us – that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion – that we here highly resolve that these dead shall not have died in vain – that this nation, under God, shall have a new birth of freedom – and that government of the people, by the people, and for the people, shall not perish from this earth.
The Gettysburg Address is still popular today. Most Americans have not memorized it, but sometimes in school schoolchildren memorize it as part of a patriotic act. Something that is “patriotic” shows your love and support for your country. As a tribute to the address – as a way of acknowledging the importance of Lincoln, the great civil rights leader Martin Luther King in a famous speech that he gave began the speech: “Five score years ago,” once again echoing, or taking from the language of Lincoln and his Gettysburg Address.
Now let’s answer a few of your questions.
Our first question comes from Carles (Carles) in Spain. The question is what the difference is between “get the most out of” and “to take advantage of.” Both of these expressions mean to take all of the opportunities and benefits that you can from a certain experience; there are slight differences in use. “Get the most out of” usually is used when we are talking about the whole thing, whereas “take advantage of” is talking more about some part of the larger whole. For example: “I want to take advantage of all the fun choices at the hotel while we’re on vacation.” That would be pieces of the whole: this here, this here, but not everything. That’s why we say “to take advantage of.” If it’s the whole, then we would probably say “get the most out of.” For example: “I want to get the most out of our vacation.” I’m talking now about the whole thing. Another example: “I want to get the most out of my biology class.” We’re talking about the whole biology class. “I want to take advantage of the extra study sessions in my biology class.” Now we’re just talking about part of the class, a piece of the class.
“To take advantage of” has some additional meanings. “To take advantage of” can mean to use something to benefit yourself but it is often used in a negative way. For example, to take advantage of someone who is blind by stealing their money. That would be a very negative thing, and that is generally how “take advantage of” in this sense is used. “Take advantage of’ can also have a sexual meaning. When you try to kiss or touch someone without their agreement – without them giving you permission, that would be to take advantage of someone. We hope no one is doing that!
Iradukunda (Iradukunda) in Egypt asks about the difference between “who” (who) and “whom” (whom). Both “who” and “whom” are what we call pronouns. “Who” means what or which person, usually it’s used for the person that is doing the action. “Whom” also means what or which person, but it’s used as the object of a verb or a preposition that comes before it.
“Who” and “whom” are used by native speakers not always in the traditionally correct grammatical way. So you will not necessarily hear, especially in informal conversation, these two words used correctly, which causes, of course, more confusion for people who don’t speak English as a native language.
The basic rule is that “who” is used in what we would call the subject place of a sentence, or part of a sentence – a clause. “Whom” or “whomever” is used as the object of a sentence. The subject is the person doing the action typically, the object is that to which the action is done. For example: “You will be working with Jaime, who is excited to meet you.” “Who” is taking the place of “Jaime,” and is really the subject of the second part of the sentence. We could say, “You will be working with Jaime, Jaime is excited to meet you.” We take out the second “Jaime” and put in “who,” that becomes the subject of that part of the sentence – that clause. That’s different than the following sentence. “You will be working with Jaime, whom you will meet later.” We could say, “You will be working with Jaime, you will meet Jaime later.” Now, “Jaime” is the object of the verb. Jaime is not the person doing the action, you are the person doing the action. You will be working with Jaime, whom you will meet later.
“Whom” is used when the pronoun is substituting for the object of a verb; it’s also used when it is substituting for the object of a preposition, such as “to” or “of” or “for.” You might say for example: “For whom are these books?” That would be the correct way. “Who are these books for?” however would probably be the one you would actually hear in spoken English. But the “correct” form would be “For whom are these books?” “These books are for John.” The “whom” is taking the place of the object of the preposition “for.”
Finally, Akira (Akira) in Japan wants to know the meaning of the word – or phrase “status (status) quo (quo).” “Status quo” is a Latin phrase that we use in English that means the way things are right now; the way things have been for a long time and are that way currently. This phrase is often used to talk about big problems that a country or a society is facing. We may talk about the status quo of women in the United States – what is their current situation, thinking of it as a big issue. That’s status quo. Or someone may say, “I think we should maintain (or keep) the status quo.” That is, we shouldn’t change the way we do things now.
As they say in television, I’m running long, meaning this podcast is too long so I have to stop here.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
thriller – a story, play, or movie with a very exciting story; a very exciting plot that makes people want to know the outcome
* Jacob stayed up until 2 a.m. reading this thriller. He really wanted to know how the book ended.
to adapt – to modify, change, or rework something into a new form
* The movie was so successful that it’s being adapted into a play!
proprietor – owner of a business
* “Excuse me, sir, are you the proprietor of this shop?” asked the stranger.
swamp – a natural area where there is a lot of water and the ground is wet; a very wet natural area
* We thought we were getting a good deal when we bought that piece of land, but it’s nothing but swamp!
to trace – to find someone or something by investigating or by searching; to locate someone by following where he or she has been
* We thought we would never see our dog again, but Dad traced him to the park three mile away.
turning point – a critical moment when an important change takes place; a important time when a major change happens
* It was a turning point in their relationship when Karl asked Maria to marry him.
cemetery – an area or piece of land that contains many graves where dead bodies are buried and funerals take place
* On Memorial Day, family members visit the cemetery to show respect for their dead relatives.
dedication – a ceremony that officially marks the completion or opening of a building, institution, or monument
* The mayor of the city attended the dedication of the new public library.
to keep (one’s) spirits up – for someone to stay positive and committed to something even though it is difficult
* After unsuccessfully looking for a job for three months, Quentin tried to keep his spirits up by volunteering in the community.
founding fathers – the politicians and other men who were very important in winning America's independence from Great Britain
* The founding fathers didn’t always agree on how the new U.S. government should operate, but did agree that Great Britain should no longer be its ruling power.
to prevail – to succeed; to be dominant; to win
* After losing three games to the other team, we finally prevailed.
patriotic – feelings or actions that show one's love, support, and loyalty to a country
* Are children taught to sing patriotic songs in schools these days?
to get the most out of – to get the maximum benefit out of something; to use every opportunity available
* Jeremy is reading all of the materials for this course to get the most out of it.
to take advantage of – to use an opportunity; to get the maximum benefit out of something
* To take advantage of our special offer, call this phone number today!
who – which person(s); which individual or group of individuals
* Do you know who will be coming to the wedding?
whom – which person(s); which individual or group of individuals
* I know he was dating two women at once, but whom did he marry in the end?
status quo – a Latin phrase that means the way things are right now, or the way things have been for a while
* Our political party is not satisfied with the status quo and we plan to make major changes in how this state operates.
What Insiders Know
Talking Heads and “Psycho Killer”
If you were “around” (alive) in the 1970s and 1980s in the United States, you may have been listening to new wave music. “New wave music” combined many musical styles, including “pop” or popular music, “funk” (mixing of jazz, soul music, and rhythm and blues), and the harder rock sounds of “punk rock.” One band that was “on the scene” (popular; involved) at that time was the Talking Heads.
The Talking Heads formed in New York City in 1974 and continued to make music until 1991. The band had four members, and it’s lead singer and “principal” (main) songwriter was David Byrne, a musician born in Scotland.
The Talking Heads was known for its strange and “esoteric” (understood by only a few people with special knowledge) “lyrics” or words. The band had several “hits” (very popular songs) and is considered one of the most “critically acclaimed” (respected) bands of that period.
The song that many people “associate with” (connect with) the Talking Heads is a song called “Psycho Killer,” which was on their 1977 album. Many people believe that the lyrics are about an actual killer “committing” (doing) murders. Despite this strange topic, the song had a “catchy” (easy to remember) “tune” (series of main notes), and an “upbeat tempo” (musical speed).
The Talking Heads’ albums regularly appear on lists of the greatest or best rock music albums of all time. In 2002, the band was “inducted into” (entered formally) the Rock and Roll Hall of Fame, which honors the best in rock and roll music.