= 1525
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 220.
This is English as a Second Language Podcast’s English Café episode 220. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog. All of that can be found on eslpod.com.
On this Café, we’re going to talk about Disneyland, which is, as you probably know, a popular theme park here in California. It calls itself “the happiest place on earth.” Then we’ll talk about government property seizures, what happens when the government takes land and other belongings – other things that you own from you, at least here in the United States. And as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café talking about Disneyland. Disneyland is a theme park located in Anaheim, California, which is south of beautiful Los Angeles. It’s about probably an hour or so south of Los Angeles, maybe a little less. In Los Angeles, we don’t think about distance in miles or kilometers, we think about distance in minutes and hours because there’s so much traffic here the distance in miles is not necessarily the same as how long it will take to get there. So I would say it’s probably an hour to 45 minutes from Los Angeles. A “theme” (theme) is the main idea, usually, of a book, a play, or a movie. A “theme park” is a large park where there are many fun things to do and everything is based on a single idea; everything is somehow related. So, these are places for entertainment – places where you can go and have fun, and the things inside of the park are all related to this common theme. Some theme parks are about space exploration or water. Disneyland is a theme park that calls itself “the happiest place on earth,” and it is related to the characters and the movies connected to Walt Disney.
Walt Disney was the original creator of characters such as Mickey Mouse, Goofy, and Donald Duck. He was an “animator,” that is someone who draws cartoon characters. The Walt Disney Company, what most people simply call Disney, is a major movie producer, and the characters and stories in these movies are part of the theme of Disneyland. They include Cinderella, Snow White and the Seven Dwarves, Roger Rabbit, and even Indiana Jones, if you remember those movies. All of those were created by Disney, and some of which are included as part of Disneyland.
Like other theme parks, Disneyland has a lot of rides. “Rides,” as a plural noun, refers to big machines that people sit in and that move around in ways that some people find exciting and fun. A Ferris wheel, for example, is a ride that people sit on, and it moves slowly in a big circle, taking people high up into the air and then all the way back down again. A roller coaster is another ride. Roller coasters have little cars, they would be called I guess, that you sit in and you go along a track that goes up and down and around very fast. Disneyland has rides that are mainly for older children and adults, as well as rides for younger children.
I’m told when you first enter Disneyland you walk down what’s called Main Street, U.S.A. Main Street is a very common name for a street in the downtown or central part of a U.S. city or town. “Main” is another word for principal, most important, most often used. So the most popular, largest street in a town or a city might be called Main Street. Main Street, U.S.A. at Disneyland is supposed to be just like any other street in a small town in the United States. There are many stores and restaurants that you can visit along Main Street.
As you walk down Main Street, you will end up at Sleeping Beauty Castle. A “castle” is a large building, usually made of stone, that kings and queens live in. Visitors can walk through the castle to go to the part of the park – a separate part of the park known as Fantasyland. “Fantasy” refers to the imagination, or things that people think about but don’t actually experience – don’t actually happen. Fantasyland has rides related to fairy tales (stories that you would tell children) about characters such as Peter Pan and Alice in Wonderland.
Other parts of Disneyland include Tomorrowland, which is supposed to have rides related to the future. Another part of Disneyland is called Adventureland; this is where you go on adventures into jungles or large tropical forests. There’s also something called Frontierland, which has rides related to the American frontier (frontier). A “frontier” can be the area of land or a place that is at the very extreme or farthest end of a territory or a country. When we talk about the American frontier, however, we’re usually referring to western part of the United States during the 19th century, during the 1800s especially, where there were very, or relatively few European Americans living, and the Americans who lived on the east coast were moving into these new territories in the west. If you’ve seen movies about cowboys and Indians, movies by actors such as John Wayne, this is an example of the American frontier, that was what we called the American frontier. We don’t call the western part of the United States the frontier anymore. But in Frontierland in Disneyland you have rides that are related to this old period in American history. There’s also a section called Mickey’s Toontown, where “toon” (toon) means “cartoon,” the animated drawings of Mickey Mouse and other characters.
Disneyland has more than just rides, however. There are also many performances. There are bands, there are parades, at nighttime there are fireworks (big explosions of light in the night sky). Disneyland has people dressed up as Disney characters, who are walking around Disneyland, acting as if they were in the stories, letting people take photos with them. So you can walk around Disneyland and see Donald Duck or Mickey Mouse walking on the street. Of course, there are actors who are inside of these costumes. It’s often fun for the small children to go up to these characters and have their picture taken with them.
Since Disneyland first opened in 1955, it has had almost 15 million visitors, making it the second most visited theme park in the world; it is second only to Disneyworld in Florida, which is also, of course, owned by the Walt Disney Company. Disneyworld is very similar to Disneyland, but it is even bigger and has even more “attractions,” or things for people to go and do. The Walt Disney Company is a huge company, not just involved in movies and entertainment and theme parks. There is also a major television network, ABC, which is part of the Disney Company. If you come to the city of Los Angeles, you will be able to see something called the Disney Concert Hall. A “concert hall” is like a large theater, where you can go and hear music played. The Los Angeles Symphony Orchestra plays in the Disney Concert Hall. It’s called the Disney Concert Hall because part of the money to build the concert hall was given by Walt Disney’s widow. After he died, his wife gave money to help build this concert hall.
Many people ask me how many times I have been to Disneyland, since it is only, as I said, maybe an hour from where I live here in Los Angeles. The answer is only once. I went to Disneyland in 1972 when I was nine years old. I was with my parents and we were traveling through California during the summertime. I’ve lived in Los Angeles for almost 20 years now, as an adult, and I have never been to Disneyland. There are good reasons for this: Number one, I don’t like rides; I don’t like roller coasters. I don’t like going up and down and around and fast, it makes me sick. I just have absolutely no interest in that sort of thing. I’m too old to want to go see Mickey Mouse and Donald Duck, so there’s really no reason for me to go to Disneyland, and therefore, the last time was in Disneyland, and the only time, was 37 years ago.
Now let’s jump to our next topic, which is government property seizures and auctions. To “seize” (seize) means to grab or take something by force. When somebody doesn’t want to you take it but you take it anyway, that’s to seize something. To seize means to take something without the other person’s permission.
Well, the United States government sometimes seizes “property,” or land, buildings, and equipment from the people who own it. The U.S. Constitution, our most important legal document, protects Americans from something called unreasonable search and seizure. Something that’s “unreasonable” is something that is beyond the normal, is not something that you could justify, for any good reason. However, the government can seize property when it proves that its action is reasonable – if there’s a good reason to take your property, there’s a fair reason to take it.
Sometimes property is seized when people haven’t paid their taxes. If you don’t pay your taxes, the government can come and take your house, it can take your car, it can take your wife. Okay, it won’t take your wife, but it can take all of your physical property. Sometimes the government will seize property because it is “tied to,” or connected with, a crime. For example, if police search a car and find a lot of drugs or drug money in the car, they can seize the car – they can take the car away from the owner. If the court agrees there was a crime, then the car and the money become property of the United States government. Similarly, if the police find a home that is being used to make and sell drugs, they can seize the home; they can take the home away and it becomes government property.
As you can imagine, it is somewhat controversial for the government to seize property, even property related to a crime. It is even more controversial when the government seizes property for other reasons, including economic development. In 2005, the Supreme Court, the most powerful court in the United States, decided that local governments can force property owners to sell their land to the government in order to make way for private economic development. To “make way for” something means to allow something to happen. For example, the government can tell a group of homeowners they must sell their land to the government, at a price the government considers fair, in order to build a new shopping mall or sell the land to somebody who wants to develop it for economic purposes. This was a very controversial court ruling, or interpretation, called the Kelo (Kelo) Decision. Many people thought that the Kelo Decision was too extreme, that the government should not be allowed to take your property just because they want to have more economic development. Most people would agree that the government seizing, for example, the house of a drug dealer or private property where they’re going to put in a freeway or a new street, that these things would be okay. But many people think that taking the land for other reasons is not okay, but is legal according to the United States Supreme Court.
So what does the government do when it seizes his property? Well, usually it tries to sell it through an auction. An “auction” (auction) is a way of selling something where people are asked how much they want to pay for it. People continue to offer more and more until there’s only one person left, because nobody else wants to pay as much as that person is willing to pay. People submit or send in what are called “bids” (bids). Bids are statements about how much they’re willing to pay, as well as proof that they have the money to pay. Now, not all auctions work that way; some auctions you simply raise your hand or raise something that has your number on it. Everyone is given a number; these are usually small, round pieces of wood that we call “paddles.” That’s the way some auctions work. But government auctions, the bids are usually written. In other words, you say I would pay 2,000 dollars for that, and then if you are the person that is willing to pay the most, what we would call the highest bidder, then you get the property.
Today many government property auctions are held online, although some are still held in person, where you actually have to go somewhere. The Federal Drug Enforcement Agency, the national government organization that catches criminals who are involved in drugs, has its own auction website called deaauctions.com, where you can go and actually see the things that they have taken from drug dealers (from people selling drugs) and you can bid on them. We’ve used the word “bid” three different ways now: The verb “to bid,” meaning to say that you will pay a certain price; the noun “bid,” or “bids,” which is the price that you are paying, it’s the action of saying you are going to pay for something or writing it down. Finally we have “bidder” (bidder), which is the person who makes a bid, or who bids. Not all of the government auctions are seized property; some of them also sell what we would call “surplus (surplus) goods.” Surplus goods are goods that the government no longer needs anymore. For example there may be cars that are getting old that they decide to sell.
Sometimes people find some very good deals at government auctions, meaning they find things for a cheap price. But you have to be very careful; you have to do a lot of research if you are going to buy something in a government auction. Remember that many of the houses, for example, that were taken from the drug dealers – that were seized may be in neighborhoods that are not very good.
The money that the government makes from auction sales is often used to pay for the police work to help catch the criminal and seize their property. The “proceeds,” or the money made through the auctions, can also be given to the “victim,” the person who may have been hurt by a crime. When the seizure occurs because someone didn’t pay his or her taxes, that money actually belongs to the tax agency – the Internal Revenue Service (or IRS). Luckily, I have never had anything seized by the U.S. government, and I hope that it will stay that way!
Now let’s answer a few of your questions.
Our first question comes from Aimee (Aimee) in Taiwan. Aimee wants to know the correct usage of the word “state.” This is a good question.
A “state” can be a place that is defined by having its own independent government. In this meaning, state is the same as country. There are many countries in Africa that are independent states – that have their own government. A state in the United States, and in some countries, is used for part of the country: one of the territories, if you will, inside of the country, although “territory” itself is used with a special meaning in the United States. There are states in the U.S., there are territories in the U.S., and there’s one federal district: the District of Columbia, what we call Washington, D.C.
A state, then, can be a country with its own government, or it’s one section or division of that particular country. In the U.S., we have 50 states; I currently live in the State of California. “State” has other meanings however, but when we’re talking about legal terminology, those are the basic definitions for a state.
Aimee also wants to know the meaning of the term “state university” refers to. State university, when it is used in the United States, describes a university or college that receives government funding and is controlled by the government. That doesn’t mean that it’s free to be a student there; you still have to pay money to take classes, what we would call “tuition.” But state university is a government-run university.
Some state universities are very good, very high quality. Here in California, we have the University of California, Berkeley, University of California, Los Angeles, and others that are good quality universities. Some state universities are lower in quality, not quite as good. And, of course, there are also in the U.S. private universities, some of which are very good (Harvard, Yale), some of which are not so good. I won’t mention any names!
Parham (Parham) in Canada wants to know the meaning of the expression “on the prowl” (prowl).
“On the prowl” is used in a couple of different ways. It can mean to be on a hunt, especially if we’re talking about a cat or a lion. “To be on the prowl” means that the cat is looking for something to kill and eat; they’re hunting for something. “On the prowl” can also mean to be moving around very quietly – a human being: “I thought I saw a man prowling in the backyard.” In fact, we use the noun a “prowler” for someone who is moving around very quietly, usually in order to steal something from you – or to go into your house and steal something, that would probably be the more common definition.
A third meaning of “on the prowl” is when a man or a woman is looking for a romantic relationship. They’re hunting, if you will, for a man or a woman to have as their romantic partner. This is a slightly negative expression however; when used to talk about a man or a woman looking for a romantic partner, it usually means that the person is looking very aggressively and isn’t very selective. They just want to find someone to have a romantic relationship with. This is sometimes common after someone breaks up from a relationship. To say that they’re “on the prowl” means they’re just looking for somebody else, perhaps, to fill that emotional hole that may come from breaking up with your girlfriend or boyfriend.
Vagner (Vagner), originally from Brazil and now living in Atlanta, Georgia, wants to know about how certain words are pronounced. We have a list of words here. Most of them involve “ee” or “ea” in the spelling, compared to words that are spelled with an “i”. For example: (eat) “eat” – (it) “it,” “eat” – “it”; (deep) “deep” – (dip) “dip,” “deep” – “dip”; (heat) “heat” – (hit) “hit,” “heat” – “hit.” You can hear the difference there. A few others would be “feel” (feel) and “fill” (fill), “feel” – “fill.” The “e” is what we would call long, with the “ee” or the “ea” in the middle of the word; the “i” is short, so “e” and “i.”
Finally, Seiichi (Seiichi) – I’m probably mispronouncing that – in Japan wants to know the meaning of the expression “time after time.”
“Time after time” means again and again, over and over, something that is repeated: “Time after time I’ve asked my boss for a raise, and finally he gave me one last week.” There’s a similar expression, “time and again”: “Time and again I have asked my boss for a raise.” It means the same thing: repeatedly, over and over and over again.
Time and again we’ve asked you to send your questions, if you have any. Our email is eslpod@eslpod.com. We won’t have time to answer all of your questions, but we’ll do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
theme park – a large park where there are many fun things to do and everything is based on a single idea
* The entire family spent the day at the theme park, going on rides, eating junk food, and having fun!
ride – a big machine that people sit in and move around in, in exciting and fun ways
* This ride went up and down so quickly that at times, I felt I was weightless.
fantasy – imaginary things; things that people think about but can’t really happen
* Jim’s fantasy is to have a house in every country and enough money to live like a king.
frontier – the land in the Western part of the United States where few people lived and the people who moved there had to deal with the wilderness
* Many of the men and women who lived on the frontier built their own homes and raised their own food.
to seize – to grab suddenly and with force; to take very forcefully
* The police officers seized the thief when he tried to run away.
property – land, buildings, and equipment that someone owns
* When Deanna dies, all of her property will go to her two grandsons.
tied to – connected with; closely related to
* Our health is tied to the quality of our diet and the amount of exercise we get.
to make way for – to take away what exists in order to create space for something new; to clear away something so that something else can take its place
* Let’s move the desk and bookcase out of this bedroom to make way for a crib.
auction – a way of selling something where each person continues offering more and more until only one person is left, because nobody else wants to pay as much as that person is willing to pay
* Three people at the auction wanted to buy that chair, but Holly got it because she was willing to pay the most.
bid – spoken or written statement of how much someone is willing to pay for something; a price one is willing to pay at an auction
* The company with the lowest bid to rebuild this bridge will be given the contract.
surplus goods – things that someone, especially the government, has too much of
* This store sells surplus goods and we can get a good deal on old military clothing and equipment.
proceeds – the money made through a sale; the money received in fundraising
* Selina gave the proceeds from the sale of her family’s jewelry to charity.
state – a place that has its own independent government, like a country; one of the territories within a country that has a smaller government
* None of the factories in this state are state-owned. They are all privately owned.
to be on the prowl – to be on a hunt, especially referring to a cat or catlike animal; to sneak around quietly, as a cat would; to go out looking for a man or woman for a romantic relationship
* The thieves were on the prowl for tourists careless with their wallets and purses.
time after time – again and again; over and over; referring to something repeated
* I’ve told the children time after time to close this gate when they leave the house so the dog can’t get out, but they forgot again!
What Insiders Know
Disney University
Parents want their children to get a good education and many want their children to attend a good university. Sometimes, though, American teenagers pick universities that may not “meet with” (get) the approval of their parents. What would you do if your child wanted to “enroll in” (officially attend) Disney University?
Don’t panic! Your child is not choosing a career, but most likely getting a part-time job. Disney University isn’t really a college or university. It is a training school for employees who work at Disneyland. Employees at Disneyland are called “cast members,” whether they wear costumes and act the part of one of Disney’s famous characters or not. A Disney University is located at or near each of the Disneyland locations, with the main location in Anaheim, California.
What do students learn at Disney University? Every new “student” learns the “traditions” of the Disney organization, including the important parts of Disney’s history and the many things that the Disney organization is involved in. In addition to watching “training films” (films made to give employees important information about an organization and to teach them new skills), the new employees get “hands-on” (with their active participation) training.
The Disney University training “facility” (space; buildings) has classrooms that include many of the things found at Disneyland itself, such as “cash registers,” where people pay for items they buy; ticketing machines; and ticket “turnstiles,” the mechanical gate that only allows one person to enter at a time. This way, the new employees can be trained and have plenty of practice before starting their new jobs. After this “initial” (at the beginning) training, the cast members get more training “on-site” (at the actual location; at Disneyland).