= 1548
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 243.
This is English as a Second Language Podcast’s English Café episode 243. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, as well as our ESL Podcast Blog. And don’t forget to follow us on Twitter at eslpod.
On this Café, we’re going to talk about some famous television animals, animals that have become famous by being on popular American television shows. We’re also going to talk about a famous tourist site in the U.S. called Niagara Falls. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion about famous television animals. Since television was introduced into American homes in the 1930s, although really in terms of the majority of homes probably not until the 1950s, certain animal characters have captured people’s hearts. They become famous, almost as famous as the human actors they work with. The expression “to capture someone’s heart” means to make someone fall in love with you. “To capture,” as a verb, can also mean to find an animal, for example a wild animal, and catch it and put it in a cage, so you are taking it against its will. You could say, “I captured my neighbors cat and put it in the freezer.” I’m just kidding, you should not put your cat in the freezer – unless it’s hot! “To capture someone’s heart” means to make them fall in love with you. The first time I saw her, my now wife captured my heart. Well, these are television animals that captured people’s hearts.
The best example of a famous television animal in the United States would have to be Lassie. Lassie was a “collie” (collie); it’s a type of dog, a longhaired, medium-sized, brown-and-white dog. Lassie was first introduced to the public through a novel written in 1940, which was later made into a movie, about three years later. The story of Lassie the novel was set in the “Depression,” the period of time in the 1930s when there was great economic difficulty across the globe – all over the world, and especially here in the U.S. The story “depicted,” or showed the long journey that this dog, Lassie, had to make to be reunited with its owners – that is, to meet up again with its owners after they were forced to sell her for money. So, it’s sort of a story of survival.
The movie Lassie was so popular that the film company – the film studio, we would call it – produced six more movies with this dog Lassie as the main character. Following the movies’ success, there was a television show called Lassie that was on the air – that is, that was shown on television from 1954 to 1973, 19 years. Almost all Americans, especially those of my age or older, know about Lassie; we grew up watching Lassie on TV. On the TV series – on the TV show, Lassie lived on a farm with a family and the “storyline,” which is the general story or plot of the show, often had Lassie rescuing or saving one of the human characters from danger.
The television show, as I mentioned, was very popular, and Lassie became the second-longest-running television show in television history, at least up to that time. Today, the name Lassie symbolizes loyalty and courage. “Courage” means to be brave, to be able to face or handle danger without being afraid. The character and the show also changed the way many people viewed dogs. Before the movies and the television show, a lot of people saw dogs as sort of working farm animals. However, on the show, Lassie was treated sort of like a member of the family. Dog collars, cozy beds, fancy dog food were all introduced after the show changed the way people viewed their pets. “Cozy” means comfortable; a “dog collar” is what goes around the neck of a dog to control it if you are walking for example. All of these things, bizarrely, came after this show Lassie, and the world has never been the same since – and not necessarily for the better! Lassie is still popular; you can find numerous websites and even an official fan page for Lassie on the Internet, run by people who have nothing better to do!
Another famous and well-known television animal, again from my generation, is Mr. Ed. Mr. Ed was the name of a “comedy,” a funny show with a happy and always cheerful ending; there was never anything bad or tragic that happened on this show, or on any comedy usually. The show Mr. Ed was a comedy that featured, or had as its main character, a horse who could talk. Now Lassie was brave, Lassie had courage, but he could not talk! Mr. Ed could talk. The horse’s name, of course, was Mr. Ed. The song as the beginning of the show went: [Jeff sings] A horse is a horse, of course, of course, and no one can talk to a horse, of course. That is, of course, unless the horse is the famous Mister Ed! Oh, I loved Mr. ED; I watched it all the time when I was a child.
The horse’s name, as I said, was Mr. Ed. The owner of the horse was a man named Wilbur (Wilbur). He was the only person who could understand Mr. Ed – who could hear Mr. Ed talk. Mr. Ed would often call him by name: “Wilbur,” sort of like a horse, you see. Mr. Ed was a troublemaker, meaning he created a lot of problems for Wilbur. He would often frustrate Wilbur by doing things like talking on the phone, riding a surfboard, flying an airplane, driving a truck – I mean Mr. Ed was amazing!
The show Mr. Ed was on television from 1961 to 1966, which means I was watching what we would call reruns of the show in the late 60s-early 70s. “Reruns” are when the show is no longer being produced, or when you are watching an old episode. The horse that played Mr. Ed – and I’m just finding out now that Mr. Ed was not a real horse who could talk – did almost all of his own stunts, but sometimes a zebra was brought in to do certain stunts for the show. A “stunt” (stunt) is a performance or act that requires a lot of skill or athletic talent, usually it’s done to attract attention or to entertain. To film the show, the directors gave the horse a lot of peanut butter. The horse loved peanut butter. The horse would then lick his lips until every part of the peanut butter was eaten, and this made Mr. Ed look like he was talking. Although again, I think he actually was talking!
Another famous television character, again from my youth – from the old days, was called Flipper. Flipper was the name of the TV show and of the title character, the main character that the show is named after. Flipper was a “dolphin,” which is an animal that is in the water, although it is not a fish. In the show, Flipper was the pet of a man named Porter Ricks. The Ricks family lived near the ocean and the father, Porter, was the warden of a “marine,” or ocean, park. A “warden” (warden) is a person in charge of something like a park, a zoo; we also use the word for someone in charge of a jail or prison. Flipper helped to protect the marine park and in many shows, just like Lassie, Flipper saved members of the Rick family who were in danger, so you see this theme of animals saving humans.
Characters like Lassie, Mr. Ed, and Flipper became so popular that, as I said, they are still well-know today. You may also sometimes hear about other popular TV animals: Benji the dog, Trigger the horse, and one of my favorites, Gentle Ben the black bear. Yes, we had a television show once about a black bear here in the U.S. – those were the days!
Now we’ll move on to our second topic for today, which is Niagara Falls. Niagara (Niagara) Falls are giant waterfalls that are located on the border between the United States in the state of New York and Canada in the Canadian province of Ontario. You have a waterfall when you have a river, and then suddenly there is a big drop in the ground that goes down many, many feet and the water goes over it. That’s a waterfall – the water falls down. Although the name Niagara Falls specifically refers to the actual waterfalls, when people talk about Niagara Falls, they often mean not just the waterfalls but all of the things that are around there: the hotels, the entertainment, other things you can find in the Niagara Falls area.
Niagara Falls is impressive and it is famous because it is very wide. More than six million cubic feet of water run over the falls every minute during its highest flow, or the time of the year when there is the most water. Niagara Falls is the most popular waterfall by far in North America. The falls are very beautiful. I have been there once, when I was 10 years old I think. The falls are also a source of energy; they produce what we would call “hydroelectric power,” power that is produced by the water. The people in charge of managing the Niagara Falls area often try to balance the natural beauty of the falls with other commercial and industrial interests in Niagara Falls. It’s so popular that many people go there.
Many people believe Niagara Falls is a U.S. National Park, but it is not. It’s technically a National Heritage Area. This is a title given by the U.S. Congress that signifies that it is an important region – an important part of American history and culture. Usually the National Heritage Areas are managed by groups of organizations, often ones that are related to tourism and economic development. They want people to come, but they also want to preserve, or keep some of the natural beauty of the falls.
As I’ve mentioned, Niagara Falls is very popular for people to go on vacation to – a popular destination. It’s a particularly popular destination for people who are going to get married or who are going on their “honeymoon,” which is the vacation that a couple often takes right after they get married. Niagara Falls, like Las Vegas, is a popular place people go to get married. Niagara Falls, however, is also popular for going on a honeymoon.
Niagara Falls has become very commercialized – very touristy, we would say, over the past 50 years. There are lots of weird things that people do when they go to Niagara Falls. One of the strangest things is the barrel rides over the falls. A “barrel” (barrel) is a large container that is usually made from wood; you put things inside of it, food for example, or liquid. There developed at Niagara Falls the tradition of people getting into one of these barrels and actually going over the falls – getting into the river and then going down and falling down with the water to the bottom of the falls. At its deepest, that’s 173 feet, or about 53 meters. In 1901, a 63-year-old schoolteacher climbed into a barrel and rode it over the falls. She survived – she was alive, and since her ride more than 100 years ago, there have been 14 other crazy people who have tried to ride barrels over the falls. Some of them didn’t survive – some of them died, some of them survived. It is now illegal to do this – to get into a barrel and go over the falls, whether you are on the U.S. side of the falls or the Canadian falls, since the falls are on the border between U.S. and Canada. So if you want to come to the U.S. and get into a barrel and go over the waterfalls, I’m sorry, we don’t allow that anymore!
Another popular attraction at Niagara Falls is a boat ride called Maids of the Mist. The word “maid” (maid) refers to, in the old days, to an unmarried girl – an unmarried woman. It can also, nowadays, refer more commonly to someone who cleans in a house, someone that you hire – you bring into your house to clean it. Or in a hotel, the people that clean the rooms after you leave are called maids. This “maid,” however, I believe is related more to the first meaning. Maids of the Mist. “Mist” is water that is in little drops, and the mist is in the air. It’s sort of like fog, but mist, if you walk through it, will make you wet.
Now, Maids of Mist is a boat ride that takes people directly into the base, or the bottom of the falls. Because the falls are so powerful, visitors generally get “misted,” that is, they get wet because the water is right there – the mist is right there. Maids of the Mist has appeared, actually, in many American movies and TV shows, so that’s certainly good advertisement for them.
As I mentioned, Niagara Falls is popular for weddings and honeymoons. Some couples choose to get married in the Sky Chapel. This is a helicopter ride over the falls, and the wedding ceremony is performed in the sky during this helicopter ride. For couples who are not that adventurous, not willing to do something so risky or unusual, there are also many chapels on the ground. A “chapel” (chapel) is a small church or a small space within a church that is dedicated to special services like weddings.
Since the early 1950s, Niagara Falls has been called the “Honeymoon Capital of the World.” It is a place with a lot of “luxury hotels,” these are very nice, expensive hotels where you can enjoy things like massages, when someone rubs your muscles to relax them. Honeymoons at Niagara Falls are also popular because some people believe that the falling waters act as an aphrodisiac. An “aphrodisiac” (aphrodisiac) is a food or something that you drink that is supposed to stimulate your sexual desire. That’s an aphrodisiac. I’ll leave the Freudian analysis to you!
Overall, Niagara Falls is a great place for families and couples to visit, because of its beauty and because there are entertaining things to do for some people. Unfortunately, it’s located several hours from major cities, so it is not as easy or convenient to get to as some other sites.
Now let’s answer a few of your questions.
Our first question comes from Nima (Nima) in an unknown country, although I will guess it is Iran. The question has to do with the words “closed caption” (caption) and “subtitle.” This is a good question because sometimes people use these two terms to mean the same thing, and they are very similar.
A “closed caption” is a system on television – it’s here in the U.S. – where the words that are being spoken are shown on the screen, you can read them. Typically this is something that is done in the same language. So for example, sometimes when I watch a television show from England, and I have problems understanding their accent – because you know they talk kind of weird over there – I use the closed caption and I’m able to read what they say if I can’t hear and understand it. “Subtitles” are typically translations, so it’s a different language. You’re watching a movie in English and it’s subtitled in French or in Farsi or whatever your language is.
In everyday conversation, closed caption is, in the U.S., usually referring to that special service that we have on most of our television shows that is mainly for people who are deaf – people who are not able to hear or not able to hear very well. However, as I say, sometimes I use it, not because I’m deaf, but because I’m American.
Our next question is also from Iran, if I guessed right on the first one. This question comes from Khashayar (Khashayar). The question has to do with the difference between the words “meantime” and “meanwhile.” Both “meantime” and “meanwhile” are one word. That is to say, “mean” and “time” form a single word, and “mean” and “while” form a single word. We’ll start with “meanwhile.”
“Meanwhile” is an adverb, and it means happening at the same time, simultaneously. “I went to work today, meanwhile my brother stayed home and watched Oprah on the television.” Oprah is a famous TV host who has a show every day. “Meantime” is a noun. It also means happening at the same time, but it’s typically used in a phrase: “in the meantime,” or, “for the meantime.” “We can’t get the car fixed until next week. In the meantime, you will have to take a bus.” During the time that we cannot get the car fixed, you will have to ride on a bus. Or, “I’m moving to a new apartment in three months, but for the meantime I’m living with my parents,” so during that time when I cannot do the other thing.
So, “meantime” and “meanwhile” mean the same thing; basically one is an adverb, the other is a noun. However, “meantime” is almost never used by itself as a noun; it’s always in a prepositional phrase such as “in the meantime” or “for the meantime.”
Finally, Robin (Robin) in France would like to know how we use the colon (colon) in English. A colon in writing are two dots (:), one on top of the other. The question really has to do with whether we capitalize the letter after the word that comes after the colon.
Typically, there are four things that can come after the colon: it could be a list; it could be something we call an appositive, which I’ll explain in a second; it could be a quotation, something that someone said; or it could be an independent clause, another subject and verb. It’s only with these last two, the quotation and the independent clause, where you might capitalize the word after the colon. We’ll talk about that in a second.
Let’s go back and talk about the list after a colon; this is a very common use after a colon when you are going to give a list of things. For example: “I need to go to the grocery store. These are the things I need: apples, milk, bread, and cheese.” That would be one use of the colon.
An appositive (appositive) is another word, or words for a term that you have already used in the sentence; you are giving another way of saying the same thing. For example: “The awards this year were given to the best employees: Maria and Antonio.” Maria and Antonio are the best employees. Another example: “I’m going to order my favorite meal tonight at the restaurant: spaghetti and meatballs.” Spaghetti and meatballs are my favorite meal, at least in this sample sentence – although I really do like spaghetti and meatballs!
Using the colon with a quotation is easy; the quotation comes after the colon. For example: “Albert Einstein said the following: ‘Imagination is more important than knowledge.’” Well, “imagination” begins the quotation, and that word – that first word would be capitalized typically.
Finally, you can use a colon between two independent clauses. An independent clause is a subject and a verb that can stand alone as a separate sentence. But sometimes we combine these sentences – these independent clauses into one sentence, especially if the second clause explains or emphasizes, gives more information about something in the first part of the sentence. For example: “Take it from me: You should always study hard in school.” “Take it from me” is the first independent clause. “Take” is a command form of the verb. “You” are the implied subject. After the colon is another sentence, “you should always study hard at school.”
Some people capitalize the first letter of that second clause, so in this case it would be “You” would be capitalized after the colon. Some people don’t. There really isn’t one rule; it depends on the style of writing. Different newspapers, for example, have different rules about this. I usually do capitalize the word after the colon, but it is definitely not something that you have to do. So, it depends on the kind of style that you are writing in.
We’ll take your question in any style: Colon or no colon. You can email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
to capture (one's) heart – to cause one to fall in love with someone or something
* Eli’s novel about a young girl with a rare disease captured the hearts of millions.
storyline – plot; the main events in a book, TV show, movie, or play
* This TV show’s storyline has become so unbelievable and strange!
courage – bravery; being able to face danger without fear
* If you don’t have enough courage to ask Ula out on a date, I will!
stunt – an act that requires a lot of skill or athletic talent, which is usually done to attract attention or to entertain
* Do you think that most actors do their own stunts in action movies?
warden – a person in charge of a prison; a person in charge of a place where animals are kept, such as a zoo
* The prisoners tried to complain to the warden about the poor medical treatment they receive, but he wouldn’t listen.
hydroelectric power – power and energy produced by falling water
* In the future, many of the homes in this region will be powered by hydroelectric power.
honeymoon – a trip that couples take right after they get married to celebrate and relax, and to start their life together
* Lane and Zack took a two-week honeymoon and traveled to Japan and Korea.
barrel – a large container that is round on the sides and flat on the top and bottom, that is usually made from wood and used to carry liquids
* The barrels were damaged during transport, but I think the beer inside is still all right.
mist – very small drops of water that hang in the air
* Normally you can see the tops of these hills, but today, the mist is too heavy.
chapel – a small church or a space within a church used for specific services, such as weddings
* In this church, Monica likes to pray in the side chapel where there are fewer visitors.
luxury hotel – a very nice and expensive hotel where guests can enjoy things that are not found at other hotels, such as spa services and golf courses
* In this poor economy, fewer travelers are going to luxury hotels, staying in budget hotels instead.
aphrodisiac – a food or drug that stimulates sexual desire
* Have you heard people say that eating oysters is an aphrodisiac?
closed caption – a system on television or on video that shows on the screen the written version of the spoken words or that adds more information to what is being said
* When Grandma began to lose her hearing, she began watching television with the closed caption turned on.
subtitle – a system on television or on video that shows on the screen the translated version of what is being said in another language
* Can you rewind the movie? I couldn’t read the subtitles fast enough and I’m not sure what happened in the last scene.
meanwhile – concurrently; happening at the same time
* The babysitter fell asleep. Meanwhile, the children went into the kitchen and ate all the cookies.
meantime – while something else is happening
* We’ve called the police about the burglary. In the meantime, we shouldn’t touch anything.
colon (:) – a form of punctuation used mostly to draw attention to what comes after it or to introduce a list
* Janus packed his luggage and included everything he’d need on vacation: bathing trunks, suntan lotion, and money.
What Insiders Know
Top U.S. Honeymoon Destinations
In this episode, we talked about Niagara Falls as a favorite “destination” (place to go) for honeymooners. Other top honeymoon destinations within the United States include Hawaii, Florida, and California.
It’s not surprising that the State of Hawaii is a favorite among honeymooners. Hawaii “boasts” (claims with pride) some of the best beaches in the world. Those interested in “water sports,” such as “surfing” (riding on top of the water using a long board) or “sailing” (traveling on water using a boat or other watercraft), can find plenty to do on most of the eight main islands that “make up” (are included in) Hawaii. Many people enjoy the “scenery” (views of nature) and beautiful “sunsets” (the view of the sky when the sun is about to disappear each day).
Florida is another state that attracts honeymooners. In the city of Orlando, honeymooners can visit Walt Disney World, one of the largest “amusement parks” (large park with rides and games) in the world. Those not interested in amusement parks can visit the city of Miami, which has a very active “nightlife” (social activities, such as dancing and entertainment, offered at night) and a lot of places for “high-end” (expensive; high-quality) shopping. Those looking for beaches can also visit Miami or Key West, where there are many “resorts” (large, fancy hotels) to choose from.
Finally, California is another very popular honeymoon destination. While some people prefer the active life of the big cities, such as Los Angeles and San Francisco, others “opt for” (prefer; select) a slower “pace” (speed). In Northern California, honeymooners can visit Napa Valley, California’s “wine country,” which is an area with many “fine” (very good) “vineyards” (places where grapes are grown), making wine for sale. Visitors can tour vineyards and taste the wines made there. Many of the smaller “seaside” (by the sea) towns up and down the state of California contain small “bed and breakfasts,” which are small, independently-owned hotels that have a “homey” (like home) feel and often include breakfast and social activities for guests.