= 1474
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 169.
This is English as a Second Language Podcast’s English Café episode 169. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, which has additional courses in business, daily, and children’s English.
On this Café, we’re going to talk about alternative energy, or energy that is better for the natural environment because it doesn’t come from oil and other what we call “nonrenewable resources.” We’ll talk about what that term means. Then we’ll talk about Monticello, a place that most Americans know about. It was the home, or estate, of Thomas Jefferson, the third president of the United States. And as always, we’ll answer a few of your questions. Let’s get started.
These days, there is a lot of interest in alternative energy, not only in the United States, but also in almost every other country. If something is “alternative” it means it is an option, it is something that we can use or choose to do. Listening to our English Café is one alternative you have for learning English. Other alternatives would be to talk to a native speaker or perhaps to read a book.
Alternative energy is an alternative to energy that is “derived,” or made from, nonrenewable resources. “Nonrenewable resources” are things that you cannot make more of – that we cannot make more of. Oil, natural gas, and coal are examples of nonrenewable resources. There is, in other words, a “finite” (finite) or limited amount of these resources. There is a finite amount of oil on this planet. If we use all of the oil to make gasoline for our cars, someday there won’t be any oil left. Since we can’t make oil, this is a nonrenewable resource.
Well, alternative energy is made by using what are called “renewable resources,” or things that we can always get more of. Common types of alternative energy include wind power; “solar” power, or energy from the sun; “hydroelectric” power, or energy made by having the water in a river push through a certain machine; “geothermal” power is energy made by using hot temperatures underneath the surface – underneath the ground of the planet. Even if we used wind power, for example, for all of our energy needs, there would always be more wind and we would never run out of or no longer have any wind to use.
These types of alternative energy are more environmentally friendly than energy made from nonrenewable resources. When we say something is “environmentally friendly,” we mean it doesn’t hurt the environment. We use that expression “friendly” when we are talking about things that are good for or that can be used with a certain thing or a certain group of people. For example, cartoons on the television are usually “kid friendly,” meaning they are things that kids can watch and enjoy. Another term for alternative energy is “green energy.” Green energy is important, because every time we use energy from nonrenewable resources, we are often “contributing,” or participating in something called “global climate change.” Global climate change, sometimes called “global warming,” is what many scientists think will slowly increase the temperature of the planet and this will create many environmental problems. So, one interest in alternative energy is to slow down this global climate change – this global warming.
One of the people most associated with this idea of alternative energy is
Al Gore, who was vice president of the United States when Bill Clinton was president in the 1990s. Gore created a “documentary,” or an educational movie in 2006 called An Inconvenient Truth. The documentary is about global climate change. Specifically, it’s about how our energy choices can contribute to global warming and what we can do to slow it down. The documentary became very popular, in fact it won Best Documentary Award for the Academy Awards, what we call the “Oscars.”
Many people think of Al Gore as an “environmentalist,” or someone who is interested in protecting the natural environment. But people on both ends of what we call the “political spectrum” have an interest in alternative, or green energy. The political spectrum (spectrum) is the range of ideas that people have about government and how government should be run. On one side of the political spectrum are people are people we call “liberals,” people who have liberal beliefs, sometimes called the “left side” of the political spectrum. The term we actually use in English is “left wing” (wing). A “wing” is normally a part of a large building. The other side of the political spectrum is the “right wing,” which is the conservative side, people who have different political beliefs.
The terms “liberal” and “conservative” mean something different in every country. Someone who is liberal in the United States may not be considered liberal in another country. But, there are people on both ends of the political spectrum, both left and right, who think that alternative energy is an important issue. For example, there is a very rich man in the U.S.; his name is T. Boone Pickens. He’s one of the richest people in the United States. He made most of his money in oil and natural gas, so you might not expect him to be in favor of – to be an advocate for alternative energy, but in fact, he is. To “advocate for” something means to think that something is a good idea and to actually try to change the laws and change people’s opinions so that it can happen. T. Boone Pickens is a person who advocates for alternative energy. So, when you have people on both sides of the political spectrum – both ends of the political spectrum – interested in an issue, usually that means that something will happen in government policy. We’ll have to wait and see!
The second topic today is not related to energy, in fact it was before we had cars and planes and many other things that use oil and gasoline today. I’m talking about a place that became very famous in the early part of the history of the U.S., called Monticello. Monticello was the “estate,” or the large home of Thomas Jefferson, who was the third president of the United States. Monticello was designed by Jefferson, and it is located near the Town of Charlottesville in the State of Virginia. Virginia is on the east coast of the United States; it’s one of the oldest states. It is next to our nation’s capital, Washington, D.C.
Monticello is a beautiful building, and many Americans have either visited or recognize the photograph when they see it. In fact, the building can be seen on the two-dollar “bill,” or piece of paper money worth two dollars, although the two-dollar bill is not very popular. You can also see the building on the “nickel,” which is the five-cent coin in the United States.
Thomas Jefferson, who in addition to being the vice president of the United States, wrote one of the most famous documents in the U.S., the Declaration of Independence in 1776, when the United States separated from Great Britain.
Jefferson, as I was saying, built this beautiful building called Monticello. He began building his house in 1768, but it took a long time to build and didn’t really finish it until 1809, more than 40 years after he had begun. This is, I think, encouraging for those of us who are trying to make changes in our own homes. My wife asked me to do something about the door in the back of our house, and it’s only been a year or two, so I have at least 38 more years before I can be considered late, I think, using Thomas Jefferson has an example!
Monticello has many “elements,” or parts that show the personal interest of Jefferson. For example, Jefferson loved to read books, so his home has a very large library. Jefferson was also interested in exploring the western United States. He sent two men known as Lewis and Clark to explore the area, and many of the objects – many of the things that they sent back to him can be seen in the house “on display,” meaning they are put where people can see them and learn from them.
Monticello does not have a lot of furniture inside of it. This is because Jefferson thought that furniture – chairs and tables – wasted space. To “waste,” in this case, means not to use something well or to use it in an unimportant way. Because Jefferson thought that furniture wasted space, he put the beds into special areas that were cut into the walls, so they wouldn’t use very much space in the rooms. He also made sure that the dining table was only available during “mealtimes,” when it was time to eat. In between the meals, his servants put the dining table away so that it wouldn’t take up so much space – wouldn’t waste so much space. I’m not sure what Mrs. Jefferson thought about all of this!
Monticello, today, is considered an average-sized house, but it’s located on a very large “plantation,” or a large farm of about 5,000 acres, or 20 square kilometers. There were about 150 slaves who worked there. “Slaves” are people who are forced to work without getting paid. In the United States, slaves at that time were black, or African American.
Although Jefferson had many slaves and a nice house, he also had financial problems. In fact, he had a lot of debt – he owed money to a lot of people, especially toward the end of his life. Eventually, when Jefferson died in 1826, his daughter inherited the estate. To “inherit” means to receive something as a gift for someone, usually a relative who has died. Unfortunately, the daughter didn’t have enough money, so she sold the estate a few years later. It was finally purchased again by the Thomas Jefferson Foundation in 1923, after having been bought and sold many times over that almost hundred year period. This Foundation repaired most of the home and now uses it and the land as a museum. In 1987, Monticello was declared a World Heritage Site. Today many people go and visit the museum to learn about this very interesting man, Thomas Jefferson. I visited Monticello when I was nine years old, with my parents and brothers and sisters – some of them, anyway. We went to Monticello to visit the house. I remember it very well; it was something that I was very excited about because American school children learn about Monticello in school. It was very hot. It was in the summertime, and Virginia is very hot during the summer, and I remember feeling kind of ill and having to lay down because I was feeling a little dizzy. But, it was a beautiful house, a beautiful area, and if you have a chance to visit the eastern United States and are in Virginia, you should try to go and visit Monticello yourself.
Now let’s answer a few of your questions.
Our first question comes from Gustavo (Gustavo) in Uruguay. Gustavo wants to know the meanings of the words “criticize,” “chastise,” and “chasten.”
“To criticize” means to judge and evaluate someone, usually finding something wrong with what they did or what they said. For example: “The teacher criticized the student’s writing when she read her paper.” She criticized it – she said there was something wrong with it. “Criticize” can sometimes also mean to find positive as well as negative aspects of something. Normally in conversation it means you find something negative, but it would also be possible to say: “I criticized the artist’s painting” – I analyzed it.
Other forms of this word, “criticize,” are the noun “criticism,” which is the act of judging or finding something wrong with something. You could say: “My only criticism of the play was that it was too long.” “Critic” (critic) is a person who criticizes, or a person who makes judgments about others. Normally, when we say “critic,” we’re referring to someone who writes for the newspaper or is on television who gives their opinion about movies or books or whatever their special area is.
“To chastise” (chastise) means to punish someone or to criticize them very severely – to criticize them a great deal. “The little boy was chastised for breaking the rules at school” – he was punished.
“To chasten” (chasten) means to discipline or correct someone by punishing them. So, it’s a little different than “chastise”; it’s related. But, “to chasten” means that you are trying to make the person change, to make them better, we hope.
These, then, are the various ways we use “criticize,” “chasten,” and “chastise.”
Our next question comes from Hirose (Hirose) in Japan. The question has to do with the difference between the expressions “please inform” and “please be informed.”
When you say “please inform” someone, you’re saying please tell someone. For example: “Please inform Suzy that the boss wants to see her.” That means please tell Suzy – please give Suzy this message: the boss wants to see her.
“Please be informed of” or “please be informed that.” “To be informed,” there, means to be told something by someone else. When you say “please inform him,” you’re saying to someone else that that person should tell a third person. If you say “please be informed of” something, that person is telling you the message; you’re not giving someone else the news, you’re receiving the news. So, if your boss says “Please be informed that we have a meeting today at 3:00,” your boss is not asking you to tell anyone else, he’s telling you. It’s just another way for someone to say “I have some news for you” – “please be informed that you are fired.” Well, you want to don’t hear that kind of news!
So, once again, “please inform (someone)” is when you are asking someone else to tell a third person something. “Please be informed” is when someone is telling you something for your own information.
Finally, Khatu (Khatu) in Vietnam wants to know how to use the verb “to denominate.”
“To denominate” is somewhat of a rare word; it is not a word that you will normally hear in spoken English or read in written English. It’s not used very much. But, it means to give a name to something or to give a value to something. So, it, when it is used, usually refers to money or some number. However, we don’t use it usually; when we want to talk about naming something we simply say “to name.”
A much more common word is “denomination,” which is a noun that comes from the verb “to denominate.” “Denomination” has two meanings. First, it can mean the value of money: “I have a one-dollar, a five-dollar, and a 10-dollar bill.” Those are the denominations of the bills. You can also talk about the value of a stamp: “I want to buy 10 stamps in one-dollar denominations.” So, 10 one-dollar stamps.
“Denomination” also has a very different meaning, which can be a group of religious people, actually, a division in a religious group. So, for example, the Christian religion has many different, smaller denominations: the Catholic Church, the Baptist Church, the Anglican Church, etc., etc. All of those are denominations of Christianity.
If you have a question or comment, something you don’t know, don’t worry! We won’t criticize you! Just email the question to eslpod@eslpod.com, and we’ll do our best to answer it here on the Café.
From Los Angeles, California, I am Jeff McQuillan. I thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
alternative – a choice that we can make to use or do something else; something that we can use instead of what is usually used
* If a person has a bad tooth, he has two alternatives: he can either fix the tooth, or he can pull it out.
nonrenewable resources – useful things that we cannot make more of; things that cannot be replaced once they are used
* We should be careful to protect the Earth for our children and not waste nonrenewable resources such as oil and gas.
environmentally friendly – not hurting nature; not polluting (putting dangerous things into) the natural world
* Nowadays, car companies are trying to make more environmentally friendly cars that use less gas and cause less pollution.
documentary – a television show or movie that teaches people about a certain topic; an educational or informative show about real people and real events
* Watching the documentary on Australian animals made me realize that there are so many different and strange animals in the world.
political spectrum – the different ideas that people have about the government and its laws; the range of ideas that people have about how country should be ruled
* No matter where people are on the political spectrum and no matter how they disagree on different laws, everyone wants to live in a peaceful and safe country.
to advocate for – to promote an idea; to encourage people to think that something is a good idea
* Martin Luther King, Junior strongly advocated for equal rights for blacks, and he made powerful speeches to help people understand that all people should be treated equally.
estate – a large home or piece of land owned by someone
* Whenever the New York millionaire wanted to take a break, he would fly to his large estate in France where he could enjoy some quiet rest.
on display – to put something where people can see it or learn from it; to put something in public so that everyone can see or enjoy it
* This month, the art museum is going to put on display a special collection of art from ancient China.
to waste – to not use something well; to use something without purpose
* People who go to all-you-can-eat restaurants sometimes waste a lot of food because they often take more food than they can eat.
plantation – a large piece of land or farm that is often used to grow a certain kind of crop or plant
* The plantation owner hired more than two hundred workers to help with his rice plantation.
slaves – people who are owned by other people and forced to work without getting paid
* The Civil War in the United States started because people in the north believed that slavery was wrong, and they wanted the south to stop using slaves.
to inherit – to receive money, land, or possessions from someone who has died; to get a gift from someone, usually a relative, who has died
* Johannas was surprised to receive a letter one day telling him that he had inherited $10,000 from his rich uncle who had just passed away.
to criticize – to find fault with someone or something; to say that is something is wrong with someone or something
* The girl broke up with her boyfriend because he was always criticizing her for being too fat.
to chastise – to punish or judge something very harshly; to find fault with someone and to strongly punish them
* When Trang’s father found out that Trang had stolen money, Trang’s father chastised him by spanking him and making him return the money.
to chasten – to correct someone for bad behavior; to let someone know that what they did was wrong
* Ling was chastened by her teacher for not finishing her work on time.
please inform – to tell someone something; to give news to someone
* Please inform all the workers that there is a meeting at 4:00 this afternoon.
please be informed – to receive news about something; to be told about something by someone
* Please be informed that starting this month, everyone riding a motorcycle must wear a helmet.
denomination – the value of money or stamps; the different sections in a religious group
* Although Jim and Lan are both Christians, they are from different denominations, and their churches have slightly different beliefs and practices.
What Insiders Know
President Thomas Jefferson and Sally Hemings
For more than 200 years, people have been trying to solve a “mystery” (something that does not have a clear answer and is not easy to understand): Did President Thomas Jefferson have a secret relationship with one of his black slaves, Sally Hemings? And did they have children together?
When Jefferson became U. S. President in 1801, there were already some people who were saying that Jefferson was having a relationship with a slave – something that was not acceptable at that time. Many people have done “research” (careful study) to find out if Jefferson really did have children with Sally Hemings, but to this day, no one is completely sure of the truth.
One group of people believes that Jefferson and Hemings had children together. They believe this because of several reasons. First, Hemings’ children were all light-skinned and some of them look like Jefferson. Second, DNA tests that were done in 1998 showed that Hemings’ last child was related to the Jefferson family, though it could be any member of the family. Third, Jefferson freed all of Hemings’ children so that they were no longer slaves. This is something that Jefferson did not do for any other slave family.
“In contrast” (taking an opposite view), another group of people do not believe that Jefferson and Hemings had children together. These people do not believe this story because Jefferson never showed any special interest toward Hemings, and he treated her like all the other slaves. Also, Jefferson’s daughter and her children all say that it was morally impossible for Jefferson to have a sexual relationship with a slave, since he was not that kind of man. And even though Hemings’ children were light-skinned, it did not mean that Jefferson was the father, since Hemings herself was “fair” (had light-colored skin).
Even after all the research, nobody knows the truth about Jefferson and Hemings. Maybe this is a question that will always remain a mystery.