= 1499
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 194.
This is English as a Second Language Podcast’s English Café episode 194. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about royalties, or the money that authors and artists receive when their work is used by other people or organizations. Specifically, we’re going to talk about an organization called the American Society of Composers, Authors and Publishers (ASCAP) and some of the artists who have made a lot of money through royalties. Then we’re going to talk about talk about a strange idea called “house swapping,” the practice of people exchanging their homes for a short period of time, often for a vacation. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café by talking about “royalties” the money that authors (people who write books) and artists should receive when their work is used by other people or other organizations. When an author writes something or an artist paints or draws something, their work is known as intellectual property. Normally “property” is something physical that you own, like a car or a house or a piece of land, something you can touch. Intellectual property, however, is something that you own, but it refers to things that you have created through your mind, things that have been a result of your knowledge or creativity.
Authors and artists who own intellectual property usually get copyrights for their work. A “copyright” is the right or ability to use that intellectual property, such as a book, song, a painting, for a certain amount of time. During that time, no one else is allowed to use that intellectual property as a way to make money unless he or she has permission from the author or artist. So for example, when we create ESL Podcast, this audio file and our PDF Learning Guide are copyrighted; it’s protected by U.S. law for a certain amount of time. It’s copyrighted and you cannot use it unless you have our permission, that’s what a copyright is. Or if you write a book, you will normally have the book copyrighted; it will be protected by this special law.
People who want to use copyrighted materials then have to ask the author or the artist for permission; sometimes they have to pay them some money in order to use their work. The money that they pay is the “royalty,” the money that the person or organization has to pay you to allow them to use your property. Now, sometimes people don’t charge royalties; authors and artists will allow their work to be used by non-profit organizations, organizations that perhaps have an important cause. A “cause” is an issue, like giving food to the poor or finding homes for cats and dogs. Well, dogs anyway, cats don’t really need homes, do they? So, these cases of non-profit organizations are usually ones that don’t result in royalties because the person gives it to them to use, perhaps to help them make money themselves for their organization.
When a business or a company is going to use someone’s copyrighted materials, they don’t usually pay royalties directly to the author or the artist. Instead, there is an organization in the United States called the American Society of Composers, Authors and Publishers, or ASCAP for short. An “author” is someone who writes a book or a screenplay, that is, something that is used for a movie, or any other sort of script. Dr. Lucy Tse is an author; she writes our scripts. A “composer” is someone who writes songs, either the words, the music, or both. Usually, a composer is someone who writes the music specifically. A “publisher” is someone and takes that artistic work and puts it in a form that can be sold to the public. So we have the American Society of Composers, Authors and Publishers, or ASCAP for short, using the initials ASCAP. ASCAP protects the copyrights of authors, artists, musicians, and other creators of intellectual property.
How does it work? Well, for example, when a song is “broadcast” on the radio – when it is played on the radio, ASCAP collects “fees,” or amounts of money from whomever used the music. So in this case, if it’s on a radio, it collects the money from the radio station. Then it gives most of that money to the musician, or whoever has the royalties. It’s not always the case that the person who wrote it legally owns the royalties; royalties can be bought and sold. You can write a book and then sell the royalties to someone else. That someone else would then get any money that you received – or rather that your copyrighted work received.
This system is a lot easier for authors and artists because they don’t have to spend a lot of time and money trying to figure out who’s using their intellectual property and then trying to collect money for them. ASCAP does this work for them.
There’s a lot of money to be made in royalties. In the year 2005, ASCAP collected $750 million, and paid almost $650 million in royalties. Of course, some authors, artists, and musicians get a lot more money than others, the ones that have popular works. Elvis Presley, the great American rock musician, he’s known as the “king of rock and roll,” died in 1977, but his “estate,” the collection of everything that is owned under his name, still received $45 million in royalties in 2005. Here’s a case where the royalties continue even though the person is dead. That was, in fact, more than any other person that year in terms of money received in royalties, and it was the fifth year in a row (the fifth consecutive year) that Elvis was the top royalty earner, the person who made the most money from royalties. The second person on that list is Charles Schulz, who created the Peanuts cartoon, a series of funny drawings about a boy named Charlie Brown and his dog named Snoopy. He earned $35 million in royalties. Again, we probably shouldn’t say “he earned” because he’s dead; his estate – the people, usually his family, own the estate and they got the money. John Lennon, who is, of course, also dead, the famous musician from the band The Beatles, was number three with $22 million in royalties. Again, that went mostly, I’m guessing, to his wife and child.
Here at the Center for Educational Development, the podcasts we produce are intellectual property. As I mentioned before, our materials are copyrighted, and it says that on our website. However, we are not a member of ASCAP. Not every artist, not every author, not every musician is a member of ASCAP, or uses ASCAP for collecting royalties. Usually only the big authors, the big, well known musicians, people who sell a lot of songs or books are members of ASCAP.
Although you can own the copyright to a certain piece of intellectual property, it’s often difficult to enforce this copyright. “Enforcing” a copyright means making sure people follow the copyright, they don’t use your intellectual property without your permission. This is extremely difficult, especially on the Internet. There isn’t a lot that you can do to stop this, especially if you’re a small independent publisher like the Center for Educational Development. People who steal your materials, well, there’s not a lot you can do. You can ask them to stop stealing your materials, but of course, that doesn’t always work. Some of the big record companies and music producers, as well as movie companies, have tried to enforce copyright, especially in other countries where their materials are being stolen, but they’re not always successful in stopping people from stealing their work.
We’re going to turn to a very different topic now on this Café, and that’s house swapping. Normally the verb “to swap” (swap) means to trade or exchange something. For example, your child might be eating lunch at school and decide to swap his apple for another child’s candy bar or sweet. He exchanges, or trades one thing for another.
House swapping happens when people exchange the use of their house, usually for a short period of time. House swapping used to be used primarily for vacations. Here’s how it works. Let’s say you have a home in a nice place, say, Los Angeles, California. You like living there, but you want to visit another beautiful place, such as a small city in Colorado named Boulder, which is famous for its mountains and its skiing. So you decide that you’re going to try to find someone who will swap houses with you, someone who wants to visit Los Angeles and stay in your house while you go to Boulder and stay in their house. This way, you don’t have to spend a lot of money on hotel rooms. This is one solution, to swap houses.
Of course, first we have to find each other; since we probably don’t know each other we are “strangers,” we are unknown to each other. But the Internet has made this much easier, and there are now many websites where you can put information about your house on the website, and then describe or list the places that you want to visit, places you would like to swap houses with. So I post a photograph of my house on the website, and say I want to go to Boulder, Colorado, and Seattle, Washington, and, I don’t know, Honolulu, Hawaii. Then someone who lives in Hawaii will see your posting – will see your information and say, “Oh, I want to go to Los Angeles.” So, the website will match you up.
The phrase “to match (something) up” means to find two things that go together, two things that belong with each other. If you have a lot of socks, as I do, and the socks are all a little bit different, after you wash them you have to match them up – you have to find the sock that goes with the other sock.
The computer matches up people who have places that each wants to visit. That is, someone in Honolulu wants to visit Los Angeles; I’m in Los Angeles, I want to go to Honolulu, so the computer matches us. Then we can email each other and ask questions about our homes, and if we decide to swap houses then we can make the final “arrangements,” the detailed plans about what time we’re going to arrive, how we’re going to get the key to the house, what happens if there’s an emergency; these would be final arrangements.
During the house swap, we’ll use each other’s houses as if they were our own. That is, I’ll sleep in your bed, use your dishes, maybe even eat your food, although that probably isn’t very common. I might drive your car, though I probably wouldn’t wear your clothing – unless I like your clothes, of course! Usually, however, it’s just using the house, not using the personal things of that person.
I, myself, have never done a house swap. I’d be a little afraid of people coming into my house and using it, but for some people, they really like the idea. It saves them a lot of money.
Nowadays, some people are using house swapping to change the place or the way that they live, instead of just for a vacation. The U.S. economy and the U.S. housing market, that is, the selling and buying of homes in the United States, is sometimes not in very good shape, such as now, meaning people have a difficult time selling their house, getting the price that they want. So sometimes if they need to move to a different city they may do a house swap, at least until they can sell their house at a price they want.
Some people are “desperate” to sell their homes, they’re very worried about selling their homes; they have to sell their homes. So house swapping may prevent problems, or at least prevent them from having to sell their home at too low of a price. However, house swapping is normally still associated with people who take vacations for short periods of time.
Now let’s answer some of the questions that you have sent us.
Our first question comes from Luc (Luc) in France. Luc wants to know the meanings of the expressions “hop in,” “pop in,” and “drop in.” All three of these phrases mean to enter somewhere very quickly, or with very little notice, the person doesn’t even know that you’re coming. It’s also a way of saying making an informal visit, something that wasn’t planned, wasn’t scheduled.
They have slightly different uses, however. “Hop in” (hop in) refers usually to a car or a train, rather than a visit to a person or a place. For example, you are driving down the street and you see a friend of yours and you stop your car and you say, “Do you need a ride?” and the person says, “Well yes, thank you,” and you say, “Hop in,” meaning get into my car. You’re telling them to enter quickly into this place – into this car. It doesn’t, however, refer to an informal visit. The other two expressions do, “drop in” and “pop in.” Let’s start with “drop in.”
“Drop in” is usually used to refer to someone who is visiting a person or a person’s house: “I was driving near my friend’s house and I decided to drop in.” I wasn’t planning on going to their house, I might not even tell them I’m coming. I may just come up to their door, knock on it, and say “Hi, I was in the neighborhood, I was close to your house, so I decided to drop in.” And then they may tell you to go away, that they’re busy, depends on how good a friend they are! You can also use the expression “drop by,” it means the same thing: “to drop by.”
“Pop in” is usually used to imply a very short visit, often to some place, not the house of someone. It’s possible to use it for someone’s house, but it’s more likely to be used for a store or an office or some other place. I am driving down the street and I see a pharmacy, I decide to pop in the pharmacy to buy some drugs that I need for my headache. This is a good use of the verb “to pop in.” “Drop in” is more to visit a person that you know, somebody’s house. “Pop in” can be used more generally. You could even say, “I’m going to pop in the restroom (the bathroom) before I get into my car,” I’m going to make a short visit. You would not say, “I going to drop in to the bathroom,” you would say, “I’m going to pop in.” So, “drop in” for people and houses, “pop in” more for businesses.
If you’re in an office, it’s possible to use either one. You could say to somebody, “When you are free this afternoon (when you have time), drop in and see me,” or, “Drop by and see me in my office.” You could also be walking by someone’s office and say, “Can I pop in for a minute to tell you something?” Both of those are possible.
So, “hop in” for a car, “drop in” to visit someone’s house or to visit someone’s office perhaps, “pop in” for most other places that you are making a short visit to.
Phouc (Phouc) in Vietnam wants to know what we mean by the expression “a compound noun.” A compound noun is a word we use in grammar to describe a combination of two or more nouns. For example, you have the noun “week,” meaning seven days; you have the noun “end,” meaning the last part of something, you combine them together and you get the noun “weekend.” This is one single word.
Sometimes compound nouns are formed by putting a hyphen, a short line in between the two words, a word, for example, like “baby-sitter.” A “sitter” is someone who watches something, so a “baby-sitter” is someone who watches babies. “Baby-sitter” is also commonly spelled as just one word, without a hyphen, at least anymore. Another compound noun would be “toothpaste.” “Tooth” is the small white things in your mouth that you use to eat with. “Paste” is sort of a liquid thick substance. In this case, “toothpaste” is a substance you use to help clean your teeth. That would be two nouns combined for a compound noun.
Sometimes adjectives, verbs, and prepositions are also combined with nouns to form one word or one idea. A “swimming pool” combines a form of the verb “to swim” with “pool” to describe a place where you might jump in the water and move about. “Underground” combines a preposition, “under,” with the noun “ground, to refer to where something is located, below the earth – below the ground: “underground.”
Sometimes compound nouns are formed more like a phrase, so there are two separate words but they serve as one noun, for example “monthly pass.” If you ride the bus or a subway (a metro) and you have a ticket that allows you to go on for one whole month whenever you want, we would call that a “monthly pass.” That’s an adjective, “monthly,” combined with a noun to form a noun – a compound noun.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. We’ll try to answer as many of your questions as we can, but we, unfortunately, don’t have the opportunity to answer all of them or to answer any questions by email. But if you email us the questions, we’ll try to be answered them hear on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
royalties – the money that authors and artists receive when their work is used by other people or organizations
* Although the band’s song was released 50 years ago, they continue to receive royalties.
intellectual property – knowledge or ideas that a person owns and have the right to use; things that people have created through their knowledge and creativity and that they own
* When Hakim leaves the company, he wants to take his ideas for the new products with him as part of his intellectual property.
copyright – the right or ability to use something, such as a book, song, or painting, for a certain period of time
* You can’t post copies of that book on the Internet! It’s under copyright!
cause – social issue that one feels strongly about; something that one believes in and wants to promote or defend
* People donate money to many different causes, from cancer research to animal rights.
estate – the collection of everything that is owned under a person’s or a family’s name
* After Aunt Lily died, we had an estate sale for the valuable art and furniture she collected over her lifetime.
to enforce – to make sure that people follow a law or rule
* There are laws against smoking in bars, but they aren’t enforced in this city.
to swap – to trade; to exchange
* I have a small car and you have motorcycle. Do you want to swap?
stranger – people who don’t know each other; someone whom one doesn’t know
* Who was that stranger who came to our party, but who didn’t talk to anyone?
to match (someone) up – to find two things that go together; to find two things that belong with each other
* It’s hard to match dancers up as partners when we have too few boys for the large number of girls.
arrangement – detailed plans; preparations for a future event
* What arrangements did you make for your family’s visit this weekend?
housing market – the way that homes are bought and sold; the prices of homes sold in an area at a particular time
* If the housing market doesn’t improve soon, we’ll have to sell our house for 20% less than we bought it for four years ago.
desperate – feeling very worried and being willing to try anything to avoid a bad outcome; feeling hopeless about a situation that is impossible to deal with
* Nancy’s car broke down and she was desperate to get to school on time to take her big test.
to hop in – to enter quickly, often used for getting into a car or other vehicle
* My boyfriend stopped his car outside of my house and yelled: “Hop in! If we don’t hurry, we’ll be late for the movie.”
to pop in – to make a short and an informal visit, often to do a specific task, such as to buy something from a store
* Let’s pop in at my father’s office so I can drop off the lunch he forgot to take with him this morning to work.
to drop in – to enter quickly or with short advance notice; to make an informal visit, usually to visit a person
* Grandma likes it when we drop in to see her, anytime of the day.
What Insiders Know
Missing Children on Milk Cartons
Imagine you are a parent whose child disappears. Your child is “missing” (cannot be found) and you want to do everything you can to try to find him or her. You want as many people as possible looking for your child, and so, you try to get your child’s picture shown in as many places as possible. One way to do this is to have your child’s picture placed on the side of a milk “carton” (thick paper container) so that the many people buying milk at the grocery store can see your child’s picture and hopefully help you find him or her.
Putting photographs of missing children on the side of milk cartons began in the 1980’s with one of the most well known cases of a missing child. Etan Patz was a six-year-old boy who disappeared from New York City. The media – newspapers, television stations, and radio stations – followed the search for Etan closely and Etan’s father, a professional photographer, “passed out” (gave to many people) pictures of his son hoping that others will help find him.
During this same time in Atlanta, Georgia, a lot of children went missing. In total, 29 bodies were “recovered” (found). The killer of all of these children was found, “convicted” (found guilty by a law court), and sentenced. This, and the “high-profile” (known by many people) disappearance of the boy Etan Patz started a “movement” (many people wanting to achieve the same goal) to develop a “nationwide” (across the country) effort to find missing children. Putting the photographs of children on the side of a milk carton was one of the results of this movement.
Although photos on milk cartons have become less common these days, they did help find missing children. Sadly, Etan Patz was never found. In 1991, a convicted child sex abuser “confessed” (admitted) to killing Etan. He was a former friend of the boy’s babysitter. The killer was already in jail by this time for other “offenses” (things done against the law).