= 0163
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast 163, “Saving and Spending Money”
This is English as a Second Language Podcast episode 163. I’m your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development, in beautiful Los Angeles, California.
This Podcast is about how people spend money, and how people save it. Let’s go!
[start of story]
In my family, there are penny- pinchers and spendthrifts, and everything in between. My brother Frank has the reputation for being stingy with money. He likes to save up and only spend when he has to. I bet he has a lot stashed away. He's careful with money but he does spend it when he thinks it's necessary, and his wife and kids are very comfortable.
On the other hand, my brother Jack is known as a spendthrift. It's not that he's a big spender or a high roller, it's just that he's not very careful with money, and doesn't think it's that important. When he has it, he doesn't think twice about spending it. With his friends, he's generous to a fault. So, what am I? A penny-pincher or a spendthrift? I guess I’m a little of both. It depends on who’s asking, and how much they want to borrow.
[end of story]
We’re talking today about the ways that people spend and save money, our story begins by me describing my family. I say, “In my family, there are penny-pinchers and spendthrifts, and everything in between. A “penny-pincher” (penny-pincher) penny-pinchers, plural - penny-pincher without the ‘s’, singular. A penny-pincher is someone who does not spend very much money, who watches every penny, and of course a penny is, in American money, the smallest amount that you can have. One penny, it’s also called, one cent, (cent), it’s one one-hundredth of a dollar. So to be a penny-pincher, and to pinch, (pincher) here means, to save. To be a penny-pincher means you save every penny that you have. You don’t spend very much money.
Now the opposite of a penny-pincher would be a spendthrift, and a “spendthrift,” (spendthrift), all one word, is someone who spends all of their money, who doesn’t save their money. They get a dollar, they spend a dollar. They don’t try to, what we would say, “put it aside,” To “put something aside” means to save it for a later time. Now, a spendthrift and a penny-pincher are both somewhat negative expressions to describe someone. Most people would not describe themselves as either a spendthrift or a penny-pincher, but spendthrift is particularly negative. Some people might say, “I’m a penny-pincher,” but no one would say, “I’m a spendthrift,” because it’s sort of an insult, it’s a negative expression.
Well I said, “In my family, there are penny-pinchers and spendthrifts, and everything in between,” meaning, there are people between the two opposites of saving all your money, and spending all your money, everything in between. Now, my brother Frank has the reputation for being stingy with money. “Reputation” (reputation) is what someone is known for, what other people say about him or her. So you could have a good reputation, or you could have a bad reputation, depends on what people say about you. I think I have mostly a bad reputation. No, I hope not. Well, my brother Frank has a reputation for being stingy, and to be “stingy” (stingy) is the same as being a penny-pincher, but it’s definitely a negative expression, it’s not a positive adjective. You say someone is stingy, means even if they should spend money, they don’t. That is the meaning of the adjective stingy. Well, Frank has the reputation for being stingy, we say stingy with money, but you can just say, stingy. He likes to save up, and only spend when he has to. The expression, “to save up,” two words, that verb means basically the same as “to save.” It’s like a lot of two-word verbs where you have a preposition like “up” that comes after the verb. It’s more to give emphasis. So I’m going to save to buy a new car. I’m going to save up, to buy a new car. They mean basically the same, but the “up” gives it a little more emphasis.
Well, my brother likes to save up and only spend when he has to, and of course “spend” (spend) means when you give someone else your money for something. I say that “I bet he has a lot stashed away.” I “bet” (bet) means I’m guessing. Of course, to bet as a verb, is something you do when you gamble. “I’m going to play poker,” or “I’m going to Las Vegas and play in the casino, and when I go there, I bet,” but here, when someone says, “I bet that” or “I bet he is a spendthrift,” what we mean is that, I guess, in my opinion.
Well, I say that “I bet my brother has a lot stashed away.” “To stash (stash) away” is a verb which means to save, but usually to save a large amount of something, and you’re saving it for a long period of time. “I have some money stashed away,” means I have money that I’m going to use in the future. The noun, “stash” means that money that you have. So, “Here’s my stash” means here’s my money that I’m saving. I say that my brother is “careful with money.” “To be careful with money” means of course that you watch what you spend, that you don’t just buy things because you want to, and you see it and you like it. “I see the new 17-inch Mac PowerBook, and I want to go and buy it,” but, if I’m careful with my money, I wait or I’m very slow to buy something.
Well, my brother Frank is careful with money, but I say he does spend it when he thinks it’s necessary, when he has to, he spends it and his wife and children are comfortable,” meaning they’re not without food, or a house. They’re very comfortable. They have a good life.
Now, I have another brother who is not a penny-pincher, and I say in the story, “On the other hand, my brother Jack, is known is a spendthrift.” “On the other hand” is when we are going to give in a story a different example, or an opposite example. Usually, you hear those two expressions together, “On the one hand, I don’t want to go to the movie,” “On the other hand, I have a free ticket, so I should go,”- so when you’re comparing two different things that are different or opposite.
Well, I say, “On the other hand, my brother Jack is known as a spendthrift,” someone who spends a lot of money. “It’s not that he’s a big spender or a high-roller,” when we say someone is a big spender, we mean, you can guess that they spend a lot of money. A high-roller, high (high) roller (roller), a high-roller is an expression that comes from gambling. When you gamble for example, in Las Vegas or in Monte Carlo or other places, many times you gamble by rolling the dice - two little squares that have numbers on them, right? We call those dice (dice). When you roll the dice, you throw the dice down. The most famous game for that is called craps” (craps), which is kind of a strange word in English, but that’s what it’s called “craps.” Well, someone who’s a high-roller is someone who spends a lot of money, either by gambling or by going out and spending their money to buy different things. And it’s a term that means the person isn’t very good with money. Usually, they’ll spend a lot of money, that’s a high-roller. Now, it’s not necessarily a negative term. If you are rich, you can be a high-roller. You can spend a lot of money, because you have a lot money.
Well I say that, “It’s not that my brother is a big spender, or a high-roller, it’s just that he’s not very careful with money.” Notice the expression, “It’s not that, it’s just that”. When we are explaining something to someone and you want to give them the reason why something happened, or why someone did something, you can start by giving them something that isn’t true, “It’s not that I don’t like Tom Cruise, it’s just that I think he’s not the best person to marry.” That would be an example, it’s not that, it’s just that. So when you say, “It’s just that,” you’re giving the real reason - the true reason, and when you say, “It’s not that,” you’re saying what isn’t true - what you don’t believe is true.
Well, my brother is not careful with money. He doesn’t think that being careful with money is important. When he has it, meaning when he has money, he doesn’t think twice about spending it. The expression, “to think twice” (twice), two times, to think twice means to be careful - to think about something before you make a decision, before you take an action. So someone may say to you, “Think twice about not going to school today, because there’s a big test, and if you don’t go, you will get a poor grade”. The expression, “He doesn’t think twice,” “Don’t think twice,” means they don’t think about it at all. They just go ahead and do whatever it means. It’s a neutral expression, it’s neither positive nor negative. Someone says, “Don’t think twice about calling me for help,” means “Don’t worry, you can call me for help anytime.”
Well here I say that, “My brother doesn’t think twice about spending his money.” “With his friends” I say, “he’s generous to a fault”. To be “generous” (generous), means that you give someone money or time, or something that will help them, someone who is generous gives other people money who need help. The expression, “to be generous to a fault,” (fault) means basically that they are very generous, that they help everyone that they can. He’s generous to a fault, he likes to help everyone who needs help, and that’s what the expression means here.
Well, I end the story by asking what I am. “Am I a penny-pincher, or a spendthrift?” and I say, “I’m a little of both,” means of course, I’m partly a penny-pincher and I’m partly a spendthrift. “It depends on who’s asking and how much they want to borrow,” means it depends on who’s asking me for money. “To borrow” (borrow) means that you ask someone else for money. So it depends on who wants money from me. I might be a spendthrift if I like them, and I might be a penny-pincher if I don’t.
Now let’s listen to the story this time at a native rate of speech.
[start of story]
In my family, there are penny- pinchers and spendthrifts, and everything in between. My brother Frank has the reputation for being stingy with money. He likes to save up and only spend when he has to. I bet he has a lot stashed away. He's careful with money but he does spend it when he thinks it's necessary, and his wife and kids are very comfortable.
On the other hand, my brother Jack is known as a spendthrift. It's not that he's a big spender or a high roller, it’s just that he's not very careful with money, and doesn't think it's that important. When he has it, he doesn't think twice about spending it. With his friends, he's generous to a fault. So, what am I? A penny-pincher, or a spendthrift? I guess I’m a little of both. It depends on who’s asking, and how much they want to borrow.
[end of story]
The script today was written by Dr. Lucy Tse. We thank her as always. Remember to visit our website at www.eslpod.com for the script for today’s podcast, and more information about ESL Podcast. From Los Angeles, California, I’m Jeff McQuillan, thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. McQuillan. This podcast is copyright, 2006.
Glossary
penny-pincher – a person not willing to spend money; miserly; cheap
* Betty has always been a penny-pincher, cutting coupons and only buying things she really needs.
spendthrift – a person who likes to spend a lot of money in an irresponsible way
* If Paolo weren’t such a spendthrift, he would have saved enough money by now to buy a house.
everything in between – everything between two extremes; all that is included between two opposite things
* She speaks so many languages – Urdu, French, and everything in between.
reputation – opinions most people generally have about something or someone
* Our company has the reputation for excellent customer service.
stingy – unwilling to give or spend money; not generous
* Our boss is so stingy that no employee has received a raise in three years!
to save up – to keep and not spend money, collecting it for a specific purpose
* Xiang wants a bicycle and is saving up his money to buy one.
to spend – to use money to buy things or services
* How much money do you think we’ll have to spend to buy a reliable used car?
to stash away – to store something safely and secretly; to keep and not use something
* Julie’s parents have been stashing away money for over 10 years to pay for college for Julie and her sister.
careful with money – not spending in a careless or irresponsible way; giving thought and consideration to how one will use one’s money
* My brother is very careful with money and won’t make a major purchase unless he has given it a lot of thought.
big spender – a person who spends a lot and without care, usually on luxuries and entertainment
* After winning the lottery, Cherise became a big spender, buying gifts for all her friends.
high roller – a person who gambles or spends a lot of money
* There are a lot of high rollers in Las Vegas, who enjoy gambling and partying.
to think twice about – to think about something before taking an action; to think carefully about something before making a decision
* This is a very good investment. I wouldn’t think twice about putting your money into it.
generous to a fault – being too willing to give money and other valuable things to others to the point of creating problems
* The priest at our church is generous to a fault, being willing to give away all of his money to the poor and not even having enough money for his own meals!
a little of both – not only one or the other, but some of both options; with characteristics of both
* The turkey and ham both look delicious. I’ll have a little of both.
to borrow – to take and use, with the understanding and intention of return it at a later time
* Can I borrow your car to take my girlfriend to the movies?
Culture Note
Experiments in Deprivation
In the world of book publishing, “trends” (what is popular) come and go. In recent years, one trend has been to publish books about “deprivation,” living without basic needs or at least living with far less than a person had before.
Could you live on $1 a day for food? Two California high school teachers decided to try spending just $1 a day, and they wrote a blog about their experience. The blog “took off,” or became very popular, and they wrote a book based on their experience called On a Dollar a Day.
Another recent book called No Impact Man “grew out of” (resulted from) another blog by a New York man who spent one year trying to live without any “negative impact” or effect on the environment. Another blog is “devoted to” (with most of its time and energy spent on) not riding in an automobile. Yet another blog is written by a a Seattle woman who describes herself as a “fashionista” (a close follower of fashion) and is about not buying any new clothes, other than underwear, for one year.
What is the motivation behind these deprivation experiments? Some of them are being done to “raise awareness” (make more people aware of) important issues, such as saving the environment. Others are trying to save money in a bad economy. Still others are trying to make a change in their lives for the good. And, of course, some are gathering material for a book.