= 0180
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast Number 180, “Airport Layover.”
This is English as a Second Language Podcast Episode 180. I'm your host Dr. Jeff McQuillan coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today's podcast is about going to an airport and having to wait for your plane. Let's get started.
[start of story]
I was going to see a friend of mine in Oklahoma City and decided to use my frequent flyer miles. I booked a flight, but the only one they had had a long layover in Denver. I had three hours to kill and I decided to get something to eat at the food court.
Unfortunately, I didn't check my bags and had my roller bag and carry-on with me. I lugged them with me, but when I got to the food court, all of the tables were taken.
Man: Do you want to share my table?
Anne: Oh, uh, thanks, that would be great. It's packed in here.
Man: Yeah, it's always like this on Friday afternoons.
Anne: You must travel a lot.
Man: Yeah, it's part of my job. It looks like you've got a lot of stuff with you. Do you want me to keep an eye on it while you get your food?
Anne: Thanks, but I think I'll take it with me. But, if you could save this seat for me, that would be great.
Man: Sure, you got it.
[end of story]
We're spending some time in the airport in this podcast. The podcast is called, “Airport Layover.” A “layover” – all one word – is when you have to take a plane to another city, but you can't go directly from your city to the city you’re traveling to. You have to stop at a third city and get another plane to take to your city. For example, if you were going to fly from Los Angeles to London, you may have to take a plane from Los Angeles to New York, and then a second plane from New York to London. We would call that a layover. You have a layover in New York.
Well, this is about an airport layover. The story begins by Anne saying that she was going to see a friend of hers in Oklahoma City. Oklahoma City is in the state of Oklahoma. And Oklahoma is located right in the middle, really, of the United States, just to the south of the middle part of the United States, the center part. Oklahoma is north of the state of Texas, south of the state of Kansas, and that is Oklahoma.
Well, Oklahoma City is where Anne is going. She says that she decided to use her frequent flyer miles. “Frequent flyer miles” refers to a program that many airplane companies, airlines have. And, that is that, every time you fly, they give you certain number of points. And, if you get enough points, you can have a free flight, you can get a free trip. So, we call these programs “frequent flyers” because “frequent” means something you do a lot, many times, and a “flyer” is a noun is the person who flies, is in this case called the flyer. So, the frequent flyer miles or points is what she's using. She's going to use those to get a free airplane ticket to go to Oklahoma City. Well, she booked a flight and “to book” as a verb means to make a reservation. She reserved a place on the plane. She reserved a ticket for herself. We use the verb to book for planes, you can use it for hotels. “I booked myself into the hotel” or “I booked a hotel room,” means I made a reservation. I called the hotel and asked them for a room.
Well, she books a flight, or a trip, to Oklahoma City, but the plane didn't go directly from Los Angeles. She had a layover in Denver. She had to stop in Denver first before she could go to Oklahoma City. She then says that she had three hours to kill. When we say we have “time to kill,” we mean that we have extra time, that we don't have anything else to do. Usually its time that you would prefer not to have to be somewhere. But, sometimes, for example when you’re traveling, you have a layover and the layover may be one, two, three, maybe even six or seven hours in the airport. Well, you can't go anywhere else, so you have to kill that time, you have to do something to keep yourself busy because you don't have the option of leaving, you can't leave that place. In this case, you can't leave the airport. So, she has three hours to kill in the airport. Her layover is three hours, we would also say. She has three hours to kill so she decides to go and eat something at the food court. The “food court” – two words – is a place in an airport or in a shopping mall or in another building where you have lots of restaurants that sell food and they are usually restaurants that you walk up to and order your food and you take your food and you sit at a table. So, there will be a large area with lots of tables and then several restaurants. Often, these are fast food restaurants. “Fast food” means that give you your food quickly. Restaurants like McDonald's hamburgers. That's a fast food restaurant that you would probably see in a food court.
Well, she goes to this food court in Denver. She says that unfortunately, she didn't check her bags. “To check” your bags means; well first of all, the word bags here means your luggage. So, someone says how many bags do you have when you're traveling, they mean how many pieces of luggage. How many suitcases do you have or other sorts of bags. “To check your bags” means that you go to the ticket counter at the airport, and the “ticket counter” is where you can buy tickets and you can reserve your tickets. It's also where you check in. To “check in” means to say, "Yes, I'm here," and they give you what's called a boarding pass, and that's like your permission to go on the airplane. Well, when you go to the airplane or airline ticket counter at the airport, you can give them your baggage. You can give them your luggage. Baggage is another word for luggage. So, your baggage or your luggage, you give them that and so you don't have to take it with you on the airplane. You don't have to take it all the way through the airport. When you land at the city where you are going, in this case, Oklahoma City, you can go and pick up your luggage. The area where you go and get your luggage in the airport is called the “luggage claim area.” “Claim” is, here means the same as pick up, to get back. So, you go the luggage claim area, or the baggage claim area to claim your luggage, to get your luggage.
Well, in this story, Anne did not check her bags. She instead had a roller bag and a carry on with her. A “roller bag” is a suitcase that has wheels on it and that you can fit easily in the airplane. When you go into the airplane, you have two places you can put your luggage or your bags. One is in front of you, below the seat of the person in front of you. The other is in what we would call the overhead compartments. The “overhead compartments” - a compartment is just a space; an overhead is something over your head, so something above you. The roller bags are designed to fit into the overhead compartments. They're sometimes called the overhead bins; it’s the same thing – an overhead compartment, an overhead bin. So, you take the roller bag and put it above you. She has a roller bag in our story, but Anne also has another carry on. “Carry-on” is any luggage that you take with you onto the airplane. So, technically, actually, the roller bag is also a carry-on. But, when someone says I have a roller bag and another carry-on, or and a carry-on, they usually mean a smaller bag like a purse, for example.
Anne says the she lugged her roller bag and her carry-on with her. “To lug,” as a verb, means to carry or to take with you, but the idea is that it is difficult, it causes you problems, its, for example, very heavy, or very big. So, you can lug something which is difficult to move or is…gives you some problems. That's the verb, to lug, to move something big or heavy. There's another word that you will, a Yiddish word, which is “to schlep.” It's a word that you will hear in cities like New York or Los Angeles, with a large Jewish population, that language of Yiddish. And, we have lots of words in English now that come from Yiddish, “schlep” is one of them and it means the same as, here, to lug, to carry.
Well, Anne says that she lugged her bags with her and when she got to the food court, all the tables were taken. When we say the tables, or the chairs are taken we don't mean somebody takes them from you, we mean there is somebody already there, somebody already sitting in that space. So, for example you could be at a movie theater and you're with your friend and you sit down and your friend goes to buy some popcorn and some soda. Someone comes to you and points to the seat next to you, where your friend is going to sit, and says, "Oh, is that seat taken?" You say, "Yes, this is taken." - means someone else is already sitting here. Well, all the tables were taken in the food court. A man sitting at one of the tables asks Anne, "Do you want to share my table?" “To share” means that you let someone else use something that you have. You are both going to use it - that is to share. We also use that verb, to share, sometimes to mean to, tell a group of people something that you feel or some opinion you have. We may say, "Does anyone want to share their opinions?" - meaning tell the rest of you and its usually with a group of people, but it doesn’t have to be. Here, however, share has the more common meaning of to let someone else use something that you have.
Anne says, "Thanks, that would be great. It's packed in here." “It's packed.” When we say it's packed in a place, we mean there's lots of people there, it's very crowded, there's many people in a small space - we say it's packed. You can say that about a plane, you can say that about a restaurant, you can say that about a movie theater - any place where there are lots of people, you can say it's packed, if there are a lot of them or too many of them. Well, the man says that's it's always packed in the food court on Friday afternoons. Anne asked the man, "Well you must travel a lot." – meaning it seems likely that you travel a lot because you know that it is always crowded on Friday afternoons. The man says, "Yeah, its part of my job." It's part of what he has to do.
"It looks like you've got a lot of stuff with you." “Stuff” is the same as things, it’s an informal way of saying things. And, people use the word stuff to mean almost any collection of things. You, for example, go to a meeting and you have a presentation that you are giving and you have some paper that you want to give to people that has the information on it and you forget it in your office. You go to the meeting and you’re going to say, "Oh, I forgot my stuff." – means I forgot the things that I wanted to bring. So, stuff has a lot of different uses. Here, the man says, "You've got a lot of stuff." He means you've got a lot of bags, a lot of luggage. He asks Anne if she wants him to keep an eye on her luggage while she gets her food. “To keep an eye on something” means to watch something. Usually to watch something for someone who has to leave for a short period of time and then come back. For example, when I go to the cafe, I may have my computer with me and some books. And, I have to use the restroom, the bathroom. So, I say to the person sitting next to me, "Can you keep an eye on my stuff?" and we see both of those words. "Can you keep an eye on my stuff?" - meaning can you watch my computer and my books so that no one steals them. It’s often the case that we often ask that of people who we don't know. But, because they are sitting there, we somehow trust them. I think someday I'm going to ask someone to watch my stuff and I'm going to come back and my stuff and that person are going to be gone. I hope that doesn't happen.
Well, Anne says that she decided that she will take her stuff with her. She says, "Thanks, but I think I'll take it with me." - or take my stuff with me. This means she does not want to leave it there with the man. She's going to take it herself and that's probably a good idea. You don't want to trust people in a place like an airport, a public place, people that you don't know. There are lots of thieves, lots of people who steal things in airports, so you have to be very careful. Well, she says that she's going to take it with her, but she asks the man if he can save this seat for her. “To save a seat” means to say to anyone else who wants to sit there that that seat is taken. So, I'm going to make sure no one else sits here. I'm going to save your seat. And, people do that…again to use the example of a movie theater, they may come to the movie theater and their friend hasn't arrived yet. Well, they'll sit down and they’ll put a coat or something, a hat on the seat next to them to save it for their friend. So, when their friend comes, they have a place to sit. The man says, sure, he can save Anne's seat. And, he ends by saying, "You got it!" “You got it” is the informal way of saying, “You have it!” "You have got it!" or "You've got it!" But, you sometimes hear people say, "You got it!" It's an informal way of saying "Yes, I will do that for you.” “I will help you in that way."
Now, let's listen to the dialogue, this time at a native rate of speech.
[start of story]
I was going to see a friend of mine in Oklahoma City and decided to use my frequent flyer miles. I booked a flight, but the only one they had had a long layover in Denver. I had three hours to kill and I decided to get something to eat at the food court.
Unfortunately, I didn't check my bags and had my roller bag and carry-on with me. I lugged them with me, but when I got to the food court, all of the tables were taken.
Man: Do you want to share my table?
Anne: Oh, uh, thanks, that would be great. It's packed in here.
Man: Yeah, it's always like this on Friday afternoons.
Anne: You must travel a lot.
Man: Yeah, it's part of my job. It looks like you've got a lot of stuff with you. Do you want me to keep an eye on it while you get your food?
Anne: Thanks, but I think I'll take it with me. But, if you could save this seat for me, that would be great.
Man: Sure, you got it.
[end of story]
The script for today's podcast was written by our own Dr. Lucy Tse. Remember you can email us your questions and comments about this podcast. You can go to our website at eslpod.com, or just send us an email. Our address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
frequent flyer miles – points airline companies give to customers who fly on their airline; customers can use the points to get things such as free airline tickets or to stay for free at hotels
* Because I flew to Europe so many times last year, I have enough frequent flyer miles to go to Australia this summer.
booked – to purchase; to make a reservation
* Have you booked the room for our weekend in Palm Springs yet?
layover – the period of time you must wait between flights when you are changing from one flight to another
* The layover in New York is just enough time for us to take a break and eat a real dinner.
to kill – to spend or to waste, usually while waiting for something
* I have so much time to kill now that I have finished my work early.
food court – an area with several different fast food shops; usually the shops are around an area with tables and chairs where customers can eat
* At the food court, I usually eat McDonalds and my friend gets Chinese food.
to check (one’s) bags – to give your luggage to the airline to be put into the airplane; not luggage you plan to take on the airplane
* The first thing I do at the airport is to check my bags, because I hate carrying them around while I wait for my flight.
roller bag – a suitcase or backpack with wheels on the bottom and a handle on the top
* I’m so glad I bought a roller bag. Now, I don’t need to carry the heavy bag all over the airport.
carry on – hand luggage that is small enough to be taken on an airplane
* Since I’ll need my book and my computer on the plane, I put them in my carry on.
to lug – to carry or to take heavy things; usually used for things that are difficult to carry
* I need to find Richard. I’ve been lugging his textbooks around for him all day.
to be taken – to be unavailable; to be occupied
* At the theater, we wanted to sit together in the middle, but all of the good seats were taken.
to share – to divide; to give parts of something to other people
* You must be hungry. Do you want to share my sandwich?
to be packed – to be crowded
* The grocery store is always packed when I go there after work.
stuff – things or objects
* My desk is so messy. There is always so much stuff on it, I can’t find anything.
to keep an eye on – to watch; to guard
* In soccer, you should keep your eye on the ball so you know where the action is.
to take it with (someone) – to keep something near you
* I’d rather not take the book with me. It’s too heavy.
to save a seat – to keep the seat free; not let anyone else sit there
* Jimmy said he would be coming. We should save this seat him.
you got it – “I'll certainly do it for you."; [informal]
* You want some French fries and a soda? No problem. You got it!
Comprehension Questions
1. The person in the story has a friend in
a) the food court.
b) Oklahoma City
c) Denver
2. When is the food court always packed?
a) Sunday nights
b) Tuesday mornings
c) Friday afternoons
Answers at bottom.
What Else Does It Mean?
packed
The word “packed,” in this podcast, means crowded, or filled with many people or things: “The room was packed when we arrived late for the presentation.” Or, “The books are really packed in that box.” “To pack” is also commonly used as a verb meaning to prepare for travel, when you put clothes and other personal things into a suitcase or bag: “I packed yesterday for my trip this weekend.” Or, “Did you remember to pack your swimsuit?”
to kill
In this podcast, the phrase “to kill” means to spend or waste time. It’s usually used to refer to free time, or unoccupied time. You could “kill time” because you don’t have any work to do or if you are waiting for something else to happen: “I have three hours to kill before my kids get home from school.” “To kill” can also be used as a verb meaning to end something. It is possible “to kill a conversation” by saying something that no one can respond to or that other people don’t like: “It killed the conversation when she started complaining about her best friend.”
Culture Note
Since 9/11/2001, when terrorists, or people who use violence for political reasons, attacked New York City, U.S. airports have given a lot more attention to security to make sure that travelers are safe.
Before 9/11, people could travel with simple objects, like nail clippers used for cutting your nails. But now, these types of things are not allowed on airplanes because they may be used as weapons to hurt other people. If a security guard finds these objects in your luggage, they will take them from you. Even tools and sports equipment, such as baseball bats or golf clubs, are not allowed. Lighters and matches are not allowed past the security checkpoint, the area where the security guards stop you. After these things are confiscated, or taken from you, you will not be able to get them back.
The security guards check your luggage, but they also check to make sure you are not carrying any dangerous things on your body or in your clothing. If you are wearing a coat or jacket, you will be asked to remove it before you pass through the security checkpoint. You must also show photo identification before you are allowed to go past certain points at the airport.
All travelers, including visitors from other countries, need to go through the same security check. It is a good idea to have the address where you plan to travel to in case you are asked. Make sure your flight plans include enough time at U.S. airports for these security checks.
Comprehension Answers
1 - b
2 - c