= 0192
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 192, “Winning the Lottery.”
This is English as a Second Language Podcast episode 192. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today's podcast is about being very lucky, about “Winning the Lottery.” Let's go.
[Start of story]
Daniela: I got our lottery tickets during my lunch break. The jackpot is up to $168 million dollars. Imagine if we won.
Boris: Thanks for getting mine, too. When is the drawing?
Daniela: Saturday at 6 PM. It’s being televised on Channel 4.
Boris: What would you do if you had $168 million dollars?
Daniela: The first thing I would do is quit my job! No more slaving away for me. What would you do?
Boris: If I were rich, I would travel around the world. If I were younger, I’d learn how to fly a plane. I’ve always wanted to do that.
Daniela: It’s never too late. You could still do that.
Boris: You can’t teach an old dog new tricks. I’d probably just retire and buy myself a nice new house.
Daniela: Yeah, that sounds nice. I suppose I’d have a lot of family and friends asking for money.
Boris: I know I would. I can just see them coming out of the woodwork and pestering me. Maybe winning the lottery isn’t such a good thing.
Daniela: You’re right. It’s a curse. When you win, you can give me all of the money.
Boris: Yeah, right. Don’t hold your breath!
[End of story]
Today's podcast is about winning the lottery. The “lottery,” sometimes called the “lotto,” is a contest, usually run by the government where you can win a lot of money by buying a ticket, and you buy a ticket that has the right numbers. Usually, there are five or six numbers, and if you have the same numbers as the winning number, then you win the prize. Here in the United States, there is no national lottery, but we do have state lotteries. Individual states have lotteries and some groups of states have lotteries. California has a lottery and it is also part of a group of, I think, 10 or 11 states that has a bigger lottery. Well the lottery is, of course, almost impossible to win. Usually the chances of you winning are very low. That means that you will probably not win the lottery if you buy a ticket, but of course, people want to believe that they will someday win the lottery, so it's still very popular.
Our dialogue begins with Daniela saying that she “got our lottery tickets during” her “lunch break.” A “tickets” is the piece of paper that has your lottery numbers on it. You can pick your lottery numbers, you can decide which numbers you want, or you can let the computer give you some numbers. When you win a lottery, the money is called the “jackpot,” all one word. The “jackpot” is the money that you win if you win the first prize, you match all of the numbers for the lottery, and in this example, the jackpot is $169 million dollars. That is actually possible in some lotteries. Normally, the jackpot is at least seven or ten million dollars for a state lottery, and sometimes it can go up to two or even three hundred million dollars. But mostly it's between, say, 10 and 50 million dollars. Only 10 to 50 million dollars! You see that's why I don't normally buy a lottery ticket.
We actually use the verb “to play” the lottery. Like you play sports, you can play the lottery. I don't normally play the lottery myself unless the jackpot is more than 100 million dollars because, you know, for 50 million dollars, it doesn't seem like it is worth my trouble to go to the store!
Well, Daniela says that, “The jackpot is $168 million. Imagine if we won.” “Imagine” here is used as a command form of the verb, what we would sometimes call the imperative form of the verb where you are telling someone to do something, you are ordering someone to do something. But here, it's not, it's not something that she's really ordering. She's saying to Boris, her friend, “Imagine if we won,” try to imagine if we won. Notice that the verb “won” is in the past tense, and this is the way that this particular construction in English works. The grammar in English is that if you are thinking about something which isn't true, which is just in your imagination, we often use the past tense verb. So, “Imagine if we went to Japan;” “Imagine if President Bush were a woman.” Okay, don't imagine that, but you get the idea. “Imagine” takes the past tense of the verb because it is a made up situation.
Well, Boris thanks Daniela for getting his lottery ticket. He asks her, “When is the drawing?” The “drawing” is when they select the winning numbers. Usually there is a…like a box that has all of the numbers in them, and there are usually little balls, like golf balls or ping pong balls, small balls with the numbers, and there is a machine that selects the numbers for the winning ticket, and that usually happens once or twice a week. Here in California, we have a lottery twice a week, so there are two drawings each week. “To draw” means to take something out, in this case. Daniela says the drawing is “Saturday at 6 PM. It’s being televised on channel 4.” “To be televised” means that it will be on the television. They will, you will be able to see it on the television; it will be televised.
Boris says, “What would you do if you had $168 million dollars?” This expression, “What would you do if…?” is asking the person to imagine what they would do. The word “would” is here used as a conditional, meaning if a certain situation, or a certain condition, were true, what would you do? Notice also that the verb in the second part of the sentence is in the past tense, just like in the example about, “Imagine if we won.” Boris says, “What would you do if you had,” past tense, “$168 million dollars?” Daniela says, “The first thing I would do is quit my job!” “The first thing I would do” is a expression to indicate what the most important thing you would do. “The first thing I would do if I had $168 million dollars is to buy a new house.” It's the thing I would do before anything else. Now, you could then go on and say, “the second thing,” “the third thing,” and so forth. We use that word, “thing,” in English a lot to mean the first event or the first action.
Well, the first action that Daniela would take would be to quit her job. She says, “No more slaving away for me.” “To slave,” or “to slave away,” means to work very hard, like you are a slave. A “slave,” as a noun, means a person who is owned by another person. Here in the United States, we had slaves up until the U.S. Civil War in the 19th century, which was from 1861 to 1865. Well, Daniela says that she won't be “slaving away,” she won't be working for someone else if she won the lottery. Boris said, “If I were rich,” notice again the past tense, “If I were rich, I would travel around the world.” There again is a sentence with would as conditional and the past tense in the other part of the sentence. So, “If I were rich, I would travel around the world,” in that situation. “If I were younger,” Boris says, “I’d learn how to fly a plane. I’ve always wanted to do that.” “I've always wanted to meet the queen of England.” “I've always wanted to be able to eat as much as I wanted to and not get fat.” This expression, “I've always wanted to,” is expressing something that has been your desire for a long time.
Daniela says, “It’s never too late,” meaning Boris can still learn how to fly a plane, even though he's not young anymore. “It’s never too late;” there's still a chance, there's still an opportunity. Boris replies that, “You can’t teach an old dog new tricks.” You can’t teach an old dog new “tricks.” Well, you know what a dog is; a trick is something that you teach the dog to do. Usually it's something simple, like sitting down when you say to the dog, “sit”; or the dog goes on its back and turns around, what we would say, “roll over,” the dog rolls over. “To roll over” means the dog lays on the ground and turns on the other side and then gets up. Well, these are tricks that you might teach a dog. There's a(n) old expression in English, “You can’t teach an old dog new tricks,” which means if you are a person who is older or if you have been doing something the same way for a long time, it's more difficult for you to learn to do something new, something different.
Boris says that he'd “probably just retire and buy” himself a “new house.” “To retire,” as a verb, means to stop working, to quit your job and to live on the money that you have saved. Daniela says, “Yeah, that sounds nice. I suppose I’d have a lot of family and friends asking for money.” “I suppose” means something similar to “I would guess” or “it is likely that.” “I suppose I’d have a lot of family and friends asking for money;” it is likely, or it is probable that I would have a lot of friends asking for money.
Boris says, “I know I would” meaning I know I would have a lot of family asking for money. “I can just see them coming out of the woodwork.” “To come out of the woodwork,” all one word, is an expression we use when people who normally you don't see or don't talk to suddenly start to call you or to talk to you because you have some money, or you have something that they want. “The woodwork” is any part of the room that has wood, the walls or the windows. So when someone says, “they are coming out of the woodwork,” it means they are coming from everywhere. Boris says his friends and family will start to pester him. “To pester,” as a verb, means to bother. So to pester someone is to bother them, to constantly ask them questions, or to call them, for example.
Boris says, “Maybe winning the lottery isn’t such a good thing.” And Daniela says, “You’re right. It’s a curse.” A “curse” is a bad thing that happens to you. So Daniela makes a joke here and says, “When you win, you can give me all of the money.” Boris replies, “Yeah, right” meaning “no.” When you say, “Yeah, right” in a certain intonation, like “Yeah, right,” that means that you are telling the person “No, absolutely not.” Boris finally says, “Don’t hold your breath!” “Don’t hold your breath.” To hold your breath is to stop breathing, to go, for example, when you are going into the water, you may hold your breath. Well, when you say to someone, as an expression, “Don’t hold your breath” means you shouldn't expect that to happen. That's not going to happen.
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
Daniela: I got our lottery tickets during my lunch break. The jackpot is up to $168 million dollars. Imagine if we won.
Boris: Thanks for getting mine, too. When is the drawing?
Daniela: Saturday at 6 PM. It’s being televised on Channel 4.
Boris: What would you do if you had $168 million dollars?
Daniela: The first thing I would do is quit my job! No more slaving away for me. What would you do?
Boris: If I were rich, I would travel around the world. If I were younger, I’d learn how to fly a plane. I’ve always wanted to do that.
Daniela: It’s never too late. You could still do that.
Boris: You can’t teach an old dog new tricks. I’d probably just retire and buy myself a nice new house.
Daniela: Yeah, that sounds nice. I suppose I’d have a lot of family and friends asking for money.
Boris: I know I would. I can just see them coming out of the woodwork and pestering me. Maybe winning the lottery isn’t such a good thing.
Daniela: You’re right. It’s a curse. When you win, you can give me all of the money.
Boris: Yeah, right. Don’t hold your breath!
[End of story]
The script for today's podcast was by Dr. Lucy Tse. That's all we have time for for this podcast. Remember, if you have a question or a comment, you can e-mail us at eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
lottery ticket – a small piece of paper that you buy for a game of luck where you pick numbers and you win if your numbers are the same numbers picked by a machine
* Most people believe that the more lottery tickets you buy, the better your chances are of winning.
jackpot – the large cash prize
* All of the newspapers wrote about the winner of the $200 million jackpot.
to imagine – to suppose; to see in your mind
* It’s hard to imagine how different my life would be if I had been born 150 years earlier.
drawing – the choosing of a winner in a game of luck
* Her husband bought six tickets hoping to win the big-screen TV.
o be televised – to be shown on television
* This year’s World Cup games were televised in over 50 countries around the world.
what would you do if… – a phrase used to ask how someone would react in a situation
* What would you do if your daughter had a big party for her entire school at your house while you were out of town?
the first thing I would do – a phrase used to tell someone what you would do before anything else in a situation
* If my house caught fire, the first thing I would do is to get the kids out of the house.
to slave – to work very hard for little or no money
* His computer job has him slaving away for 15 hours a day!
If I were…I would – a phrase used to tell someone what you would do in a situation
* If I were rich, I would go on vacation whenever and wherever I wanted.
I’ve always wanted to… – a phrase used for something that you have been thinking about doing for a long time but have not yet done
* She went mountain climbing in Fance? I’ve always wanted to do that!
It’s never too late to… – a phrase used to say that there is still time to do something
* It’s never too late to learn how to ride a bicycle.
you can’t teach on old dog new tricks – a phrase meaning you are not too old to change, to do something different, or to learn something new
* He was teaching his father how to send email, but his father said, “You can’t teach on old dog new tricks.”
retire – to stop working and to live on money you have saved, usually after many years of work
* Many people in the U.S. retire when they are 65 years old.
to suppose – to guess, usually about something you aren’t sure about
* I suppose we’d have to move if he gets a job in another city.
coming out of the woodwork – something coming from somewhere not obvious or easily seen
* When that great job was advertised online, a lot of people came out of the woodwork to apply.
to pester – to bother or annoy
* The neighbors keep pestering us to cut that big tree in our front yard, but I like it just the way it is.
curse – something that is believe to cause harm or bad luck
* Sometimes I think that being tall is a curse because I am always hitting my head against things.
don’t hold your breath – a phrase used for something that is unlikely to ever happen
* Don’t hold your breath if you think I’m going to do your work for you over the weekend.
Comprehension Questions
1. What would Daniela do if she wins the lottery?
a) Travel.
b) Tell all her friends and family about the money.
c) Quit her job.
2. If Boris were younger and he won the lottery, he would:
a) Lean to fly a plane.
b) Buy a new house.
c) Give away the money.
Answers at bottom.
What Else Does It Mean?
drawing
The word “drawing,” in this podcast, is used as a noun to mean the choosing of a winner in a game of luck, like the lottery: “I’m sure I’m going to win the big prize in tomorrow’s drawing.” It can also be used as a verb, “to draw,” to mean to pick: “He was hoping to draw the number 8, but he got the number 6 instead.” The most common use of the word “drawing,” though, is to mean a picture that you someone makes: “Her drawings are always colorful.” And, “to draw,” in this case, means to make a picture: “It’s difficult to draw good pictures of people because their eyes and mouth move often and quickly.”
retires
In this podcast, the word “retire” means to stop working: “The president of the company held a big meeting to announce that she would retire at the end of the month.” This is the way the word is generally used. But the word can mean something else. “To retire” is a formal way to say to go to bed or to go to sleep: “I retired at 2 a.m. last night, right after the last party guest left.” We can also retire things, or stop using them because they have a special meaning, usually in sports: “When Joe DiMaggio retired from baseball, they retired his number and no player for the Yankees will ever have the number 5 again.”
Culture Note
In the United States, lotteries are run by the states. For example, in California, you can buy a lottery ticket for the California Super Lotto. There are also lotteries formed by several states together. These are called “interstate,” or more than one state, lotteries and they have very big jackpots. The more popular ones are the Tri-State Lotto for the states of Maine, New Hampshire, and Vermont; Mega Millions for the states of Georgia, Illinois, Maryland, Massachusetts, Michigan, Virginia, New Jersey, New York, Ohio, Washington, Texas, and California; and Powerball in which 29 states, Washington, D.C. and the U.S. Virgin Islands all participate. In all of these lotteries, you pick a group of numbers to match the set of numbers chosen by a machine.
When someone buys a lottery ticket, they have a choice of how they want their money if they win. They can choose the “lump sum” option to get the money all at one time right away, but the amount of money they get is about half of the actual jackpot. Or, they can get the money “in annual installments,” which means that the jackpot will be paid to them over many years, such as 20, but they will get most of the jackpot amount.
There are also smaller lotteries that do not pay as much, but that are still popular because they can know right away if they have won. Instant tickets, also known as “scratch cards” or “scratchers” are small paper cards that have a covering over the pictures or numbers. You “scratch,” or rub, the covering off to see if you are a winner. If you win, you can normally get your prize right away by bringing it back to the place where you bought it.
Comprehension Answers
1 - c
2 - a