

= 继承之战 S04 - 03
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



== 释义



'''

== pure




Hey, Pop. -Hey, son

I've thought it over, and I really think

you should come and see the Swede, get inside this

Oh, okay. I, uh... Yeah, yeah, yeah, yeah.

Oh, come on, he likes you

You'll keep it light. -Well, you know, the only thing is, um.

Con's wedding. -Oh, it'll be okay.

Are you gonna make it at all?

Hmm, we... we got him some, uh.

uh, Napoleon thing, you said?

Napoleon and Josephine letters

Let him know that I'll call him when I have a minute

-Right. -And, listen.

U h, I'm... I'm feeling now, more and more.

I'm uncomfortable with Gerri. How she's handled things.

On the DOJ number, on the spin-off.

Oh, yeah? -Yeah.

I think we wanna let her go

Uh, right. Right. Uh, okay, well, let's discuss

So, will you give her the heads-up?

Me? -Yeah, I... I think

it would be nicer coming from you

I mean, you two, you know, you were... you were close.

--Uh, Dad... -I mean, you are with me?

You weren't just fucking me around?

Uh, well, sure, yeah. Okay, yeah

We'll make it tidy afterwards.

Just give her the word today. Thank you

-No. -Just... Just checking, uh

he definitely doesn't want me coming with you guys?

He doesn't, correct.

And should I speak to him direct or..

Or to Kerry to apologize?

No, you're in the bad books. Just keep your head down.

Well, I have a... A little list of, um,

of nice things to say to Kerry

Well, that sounds creepy

It's not creepy, it's.

No, listen. Look, Greg, it's not your fault

but he just finds you visually aggravating right now.

" Visually aggravating "

He's so petty. I don't know, do you...

Do you have all the support that you need for Sweden?

Oh, yeah. I got, like, three, four people

Gregging for me.

" Gregging "? -Yeah.

roped in a few little mini Gregs from the pig pen.

Little, uh, Greg lets.

Okay, well, don't turn me into a word, To m. I'm a guy.

Why... Why do you have all these little guys?

These little Gregg ies running around?

Who are these little Gregs?

Well, the boat leaves in 30, and there's champagne

and canape still Ellis Island,

and then after that, there'll be something more,

you know, substantial after the ceremony

Look at that boat. -Yeah.

Will a, it's like you're a princess in a film.

Thankyou. I mean, all and all,

I guess it's not exactly what we expected.

but... It's fine, so.

He'll look after you.-He will.

I'm not looking.

-I'm not looking. -Okay, I'll go. I'm going

No bad luck.

Hi. -Oh, Connor, it's all so lovely.

Yeah.

Oh, my God. Look at all the young people

I heard a few of them moaning about the rich

Yeah, well, they don't mind the taste of your champagne.

Mr. Scrooge just happened to be a huge wealth creator.

They don't mention that in Mr. Dickens's books, do they?

No, they do not. Very convenient

Hail Logan us Maximus, slayer of Vikings!

Morning, sir. How are you?

So... what have you got on Mats son for me?

Well, he's playing hardball,

but everybody says he still wants the deal.

So we might have to weave a little.

There's still a bit of grumbles about the ATN carve-out, but...

Well, that's not on the table. -Well, right.

But, if... You know, he's playing tough.

but if there was no upside, he wouldn't be making the time, so.

I think today's the day.

I'll talk to Cyd

Oh, you mean, like..

And, uh, Gerri. Find out when he's done it.

Okay.

-Karolina! -Yes?

Gerri's getting the push

Oh, okay.

-What? -Nothing

We'll tell her today, swing in the legals

We can begin to let it seep.

Hang Cruises around her neck.

Sort of incompetence or worse. Yeah

I think the idea would be that she took her eye off the ball

Clean out the stalls, strategic refocus

A bit more fucking aggressive

You push Cyd,

Roman knifes Gerri. All in a day's work

Hey What you heard about Mats son? The deal gonna be all right?

--You all right? -Hm? Yeah... Fuck you.

-I'm great, why? --I don't know, fuck you

-I'm just asking. -Fuck you. I'm fine

Okay! -Let's just enjoy

this sham marriage and the death of romance. It's gonna be great

Okay.

Let me know if you hear from him

Let me know if..

-Fuck off. -You are.

Yeah, what, what? Talk, talk, talk. What?

Hey, you done it? Your dad wants to know.

Have you done it yet?

No, Jesus fucking Chri... I just got off the phone

With him, okay? Like, she's... she's no t here yet.

Are you going to do it? -Yes, I'm going to do it.

I'll let you know, okay? And back off, you inflatable dicky-dick

Oh, fucking asshole

Oh, hello, Gerri. How are you doing?

-You look well. -Thank you

I saw a client of mine in there.

Oh, no worries. -Excuse me a minute.

He didn't have to go. r

What, no stupid jokes about Martyn or...

-Martyn, okay. -... something disgusting

about dicks or maybe vaginas?

Okay, I'm just being nice. Can a guy not be nice anymore?

What?

What? -Why are you not looking at me?

I... I will stare at you

as long as you want, if that's what you so desperately desire

What's going on, Roman? -Nothing, I'm just..

You make me go weird, as you know and fully intend

Uh, but we, um... Let's talk later, okay?

Like, in, like, 30 or whatever

once we set sail, we should have a chat.

What is it?

What's going on? Tell me. -I just need to talk

with you, that's all. And we should do it later.

It'd be better if we did it later because, um

you can no doubt tell

just from looking at me that it's not great.

But, you know, Dad said it. So, it's a message.

Is this why I'm not going to Europe?

-Look, it's not... -What the fuck?

... official. And I'm just

heads-upping you here, okay? But, yeah, early warning

I did not intend to talk about this right now.

But, yeah, you're... -Why?

I guess that he's just unhappy about how long it took for you

to settle with the DOJ. -Bullshit!

Well, the number and I think the fine, too big

I danced us through a fucking thunderstorm

-without us getting wet. -Okay. Guess you just lost

-his confidence. -Oh, since when?

Since you sent me repeated images of your genitalia?

Okay, no. -He really loved that

when that happened. -Don't be so stupid

and reductive, okay? I'm doing you the courtesy

of letting you know. I mean, you can go legal

if you like, but we are gonna stuff your mouth

with so much fucking gold. This is...

I mean, you know that I am on, like, a human level

like, obviously sad, but.

-I am. I'm sorry. Like, I... -I'm good

This is fine. This is nothing at all.

Thank you for the consideration.

Don't...

Hi.

We'll be boarding. We'll start our boarding process,

and we're gonna start with the red invites.

Family and friends. Welcome aboard

I'm sorry.

-The cake. -Yes.

It's inadequate

So, I'm saying that we can have it as display, obviously.

but I do not want it served, okay?

I don't want to see the internal..

qualities. Yes? -Okay

-Yes. -Yes?

Okay. -Thank you.

Uh, hey, Dad, can you, uh.

can you call me back? That was, uh...

Uh, it was horrible with Gerri, so, uh, I'm just in.

I don't know if... And don't listen to this

if you don't want to, but I'm not...

U h, I'm not totally okay with, uh..

Are you kind of just being shitty with me?

Cause your son is getting married

and you can't fucking keep expecting me to bend over

for you, like, being cunty. So, I'm just asking. So, uh.

Yeah, that's the question. Are you a cunt?

Okay, give me a buzz

Kidney chop!

-Good. -Good?

Good, that was a good one.

Shall we go? -Yeah, let's go

Let's, uh, may be get a head start

on all the fucky-fucky face-people, so..

Hi. Look how lovely. -Hi.

Oh, smooches.

-Nice boat. -Thanks

-Hi, congratulations. -Thank you

How's the groom? --Oh, you know,

he's nervous about you guys

and his dad, and he invited the press.

But he's fixated on the cake

He says it's a " Loony cake "?

Yeah, okay.

What is that?

U h, it's...

I believe..

when they told Connor's mom was getting, you know..

Going to the funny farm. -... taken into..

into mental health care, they gave him cake

Dad and whoever, just to calm him down.

You know, dab of sugar, bite of cake.

So, he was eating Victoria sponge

for, like, a week straight.

Oh, right. Okay.

So, " Looney cake." -Yeah.

So, Will a, I'm really looking forward to saying hi to everyone

and mixing it up and whatnot. But is there an area where we can,

you know, so we don't get Roy'd to fuck

Uh, yeah. Yeah, um.

On the second floor, there's an area.

Thank you. I mean, I want to meet everyone and get into it all

about their fucking jobs... -Hey, Julie, can you, um,

-help them get upstairs. -children and everything but, you know

thank you. -Unbelievable, Julie

Can you believe this guy? -Who's Julie? You Julie?

Yes. -This is Julie

-Hi. -It's right this way

Okay. -So, uh, what are you hearing?

-Is he coming by? -Hey. Uh, I..

I have no idea, I don't know

U h, I'm hearing Stockholm, gone or going

Yeah.

Okay.

Mats son wouldn't fix it with him on a phone r?

Journalism, taking quotes and kicking asses

Oh, you shouldn't talk to him.

He likes to whip it out to see if anyone notices.

It's a sick game, Greggy...

. stop playing it. No, bad.

Hey, nice to see you. Hey, guys

Hey. -Hey. Hey, guys

-Hey, can I grab you for a sec? -No.

No. I... I... Sorry.

Pass. -I just... I just want to congratulate you

on everything... -Don't touch me.

Get your nose out of our trough, Greggy

You think Mats son is gonna tell Dad to just fuck off?

He'll approve the offer is what will happen

Dad's gotta go fucking

lingonberry picking with Mats son.

Fucking puppet mastering the old bastard

Okay, well, what if the deal falls apart, though, Ken?

What's the... what's the latest from Nan and Naomi?

-Still in touch with Naomi? --He'll land it.

And we will pocket that sweet bonus loot

There he is. -Hey, hi, hi, hi.

Uh, hey, so, the idea is, uh, that Dad will pop by

be dockside, and you guys are up here

And I think that's just the cleanest.

Oh, okay.

-You think he's gonna pop by? -Spoke with Kerry. He's hoping

Oh, okay then. -Okay

All right, thanks. Okay

Well, someone's gotta tell him. We should tell him.

We should tell him.

-No, come on. Really? -He likes you

Fine.

-Fine. -I'll be the wedding Grinch

Fuck you.

Good luck.

Oh, my. Fucking leave me...

Yeah, hello! Fucky-sucky brigade. How can I help you?

Are you... -Calling, yeah.

-Hey, Roman. -Yeah

He y, uh, your dad is very sick

-He's very, very sick. -What?

What? Okay? -It's Tom. Apparently, Dad's sick

Uh, what do you mean he's sick? Like, sick, like..

-What's going on? -Tom?

Tom! Are you still there? -Is he okay?

What's going on? What is it? -We don't know.

Is he okay? -He seems kind of hurt.

Who's with him?

He had a very serious...

-Serious, what? -We don't know. It's... it's..

It is very, very bad. It seems very bad

I'm so sorry to call you like this

Can you put him on the phone?

Who's there, Tom? What's going on?

What happened? -Uh, so,

he was short of breath and he went into the bathroom,

and he was gone and then what it was, uh, someone heard something

and he was... we were concerned and then they went in there

They... they went in, they broke in?

They broke in. They, uh, they had the key and they got in there.

but he's nonresponsive. --Is he still in there? Did..

He's... he's... he's nonresponsive?

-Yeah. They're... -Is he talking?

--Can he... can he talk? -Is he breathing?

They're doing chest compressions.

Oh, fuck! -Has his heart stopped?

-Has his heart stopped? -Uh, I don't know

-Do you guys... -I don't know.

Do you have the machine on board?

-The fucking heart thing? -The defibrillator.

Do you have that? -Well, unless his heart has stopped

Well, okay, I don't fucking know.

What's going on, Tom? Who's in charge?

--I... Is Shiv there? Is Siobhan there? -Who's in charge?

What is going on right now? -No, she's not.

Karl said that may be he's... He's breathing, may be

Who is medically competent there? -Okay, he is breathing?

They're trained... The... the people... The attendant is trained

I'm gonna put you on speaker

hold on. -The fucking flight attendant?

The captain has spoke... The captain's been in touch

He is in touch and, the, uh, the cabin staff

they're receiving medical, uh, advice from their service.

-From who? -The cabin service.

You have a service? Okay

what is that service? -Okay, can we be..

What's the name of that service?

Guys, can we be looped in on that? Karl?

-They... they should talk to him. -You tell'em, go ahead

They should speak to him. -Is that Frank?

What did he say?

So, Frank... Frank thinks you should speak to your dad

and I can hold the phone..

can hold the phone near him if you like

Why does Frank think that, Tom?

I guess, if... if it's a chance to,

you know. I... I think in case it's the last chance.

Fuck do you mean, Tom?

He's not in good shape, Roman. He's not in good shape.

They're doing chest compressions

Well, should they be doing that?

They're getting good advice. They're good people

But I think you should talk to him

I... I'm not sure he's breathing.

You serious right now, Frank? Fuck me, man!

We just heard that he was breathing

You shouldn't do CPR to someone whose heart is going, Frank

What the fuck is going on? -Can you breathe without a heart?

Can you? -What is going on?

I'm gonna take you to him

I'm taking you to him now, and I'm gonna put you by his ear.

Okay, he'll be able to hear you.

That's... -If he can hear.

he'll be able to hear you.

Uh, you might wanna get, uh.

Yeah, yeah, yeah. We'll get Shiv, we'll get Shiv.

We'll get Shiv. -You might wanna get Shiv.

Okay, I'm putting you by his ear now.

Can he hear me? Is he okay?

Tom! Is he okay? -No, Rome, he's not okay

But you can speak into his ear, right now

Go ahead.

Uh, hey, Dad, uh...

Uh, I hope you're okay.

Uh, you're okay. You're... You're going to be okay

Uh, because you're... you're a monster.

And you're gonna win.'Cause you just..

You just win and, uh, you're a good.

You're a good man. You're a good dad.

You're a very, very good dad.

You did a good job

No! I don't... I'm sorry, I don't know how to do that.

You can... I can't. Your turn.

-Am I by his ear? -Yeah

You're by his ear. If he can hear it,

he can hear you.

Go ahead. -Okay

Uh... hang in there.

Yeah, um...

" Be okay..." -It'll be okay

And know we love you, Dad. Okay? We love you

I love you, Dad.

I do. I love you. Okay?

And it's okay.

Uh, even though you fucking.

I don't know. I can't... I can't forgive you

But, uh...

Yeah, but I... I, uh

It's okay, um.

And... and... and... and I love you, uh

I don't... I don't...

-Hello, Tom? -Is Siobhan there?

Ken's going to get her right now.

He's not here, I don't think

He's, uh... Ken's gonna get Shiv.

I'm gonna get Shiv.

He's going to get her.

Can you... can you put me back to his ear?

Thanks for making me do that.

Uh, sorry, just a sec... -Shiv.

-Shivy, honey. -Mom?

-D ad, he's in trouble. -What?

-What's happened? -Uh, he's on the plane

And he got

Uh, I don't... It's bad and, uh,

they're doing chest compressions

What?

What? What, Ken?

Come on, this way

I don't know everything, um..

He's with Tom and Frank and Karl.

-and they're on the line to doctors and, uh... -Um, okay

I don't know, he was in the bathroom

And he had trouble breathing

Like, I don't know... It's, uh... And.

And they started doing chest compressions

-and he was still breathing a minute ago... -Okay.

... but it's... it's very bad. -Okay, yeah

--So, Shiv's coming, uh... -Okay

He y, um...

They...they think he's gone  -What?

--They think he's gone. -What happened?

-What do you mean? -Well, they think..

-They think Dad died. -What?

-Yeah. -No.

-I'm sorry. -No!

No, I can't have that!

Hey, hey, Tom.

Hey, can she do it? Can Shiv.

uh, speak to him? -They've been putting us

to Dad's ear, just to speak to him

Can you put her next to his ear? Okay.

-I'm... I'm giving you to Shiv. -Okay

-What? -Hey, Shiv, I'm putting you by his ear.

Okay.

U h, is he hearing? Is he still hearing?

Uh, I don't know. But I'm putting you there, okay?

And you're by his ear, you can go now.

you're talking to him now. -Okay! Hey!

Hey, Dad. Uh, hello

Um, you're gonna be okay. And I'm sorry..

-Is he dead? -I don't know.

I don't know if he's dead. I s he fucking dead?

I don't know!

Tom?

Hey, hey.

Is he... is he even alive?

-I don't know, honey. -Is... is he..

Are you just being nice to me? Is he gone?

He's, uh... I don't... I don't know. We... He, uh.

We don't know. We don't know

Okay, I'm putting you back there, okay?

Uh, okay. Well, um..

I don't know what to do.

You're by his ear.

Okay.

I'm gonna put you back there. -Okay, just, like, go private.

Be somewhere private, just speak. It's weird, but speak, okay?

-Like, you never know, he might hear you. -Uh, Dad?

Um, hey

Dad?

Daddy, uh, I love you.

Uh, don't go, please, not now.

No, I, uh... I love you, you fucking.

God! I don't... Um, there's no excuses for the..

But, I.

But, I... Fuck!

I don't know. I do love you

And it's okay.

It's okay, Daddy. It's okay, I love you

I...

Do you want to stay on?

Do you want me to take it away? -I don't want it

Please, please.

Um, Tom? Tom? -Hey, Roman

What's happening? What's... What, precisely..

Like, tell me, precisely, what is happening right now.

Okay, so, um...

Yeah, so we're all here,

and I'm... and I'm heading to the back

of the plane. -Stand clear of patient.

And they're..

-Shocking. Everybody clear. -He's at the front.

on the floor, and they're doing chest compressions and, uh.

Okay, so they're still doing chest compressions?

Yeah, yeah, they are. But not because...

I think they have to. I think they have to keep doing that

In the plane, people are lovely, and they're good people

I think he's...

I think they've made him very comfortable

What? But... but is... Is... is he gone... -What?

-He's gone... -To m, is he, uh.

Is he okay, at all?

He's not okay. No, he's not.

Is... is he gone, Tom?

I mean, they say his heart has stopped

and his breathing has stopped

For a while, may be.

Okay, but that doesn't mean that he's dead, medically?

Right?

I don't know, they're... They're still doing

the chest compressions. -Okay, and... and

And when do you land?

Have you turned around? Are you coming back?

Yeah, I don't... I think yes. Yes.

We're coming to... We're heading back, I think.

Okay.

Can you put me through to the flight deck?

Can I speak with the pilot, please, Tom?

You know what, I'll call Frank's phone

and he can take me to the flight deck

Okay. Okay

So, Frank, Kendall's going to call your phone

to be taken through to the pilot, okay

Okay, that's happening

-Hey, Ken. -Jess, I need a few things

Yeah. -Uh, my dad's dying.

--I'm just going to do facts, okay? -Sure. Got it

-I need my doctor and, uh, I need... -Are you okay?

Do... Do they have his doctor? -Uh, do you have

his doctor on the line?

Do they... Uh, do we have his doctor on..

No, I think we got... We... we have their service.

Their medical service which they have

and we have Karl's guy listening in

but we couldn't get ahold of his doctor. -No, no, no, no.

They don't have his.

And...and uh and Dad's doctor, Doctor fucking judith.

Get that lazy fucking bastard, and get him

and get the best heart doctor in the world

and the best airplane medicine expert in the world

and get them conference d in and waiting.

and send a conference call number to me

and to Tom and Karl's phone, and any or all of those things

I will take, but I would like that in the next minute,

-two minutes, please, Jess. Okay? -Sure. I'm on it, Ken.

Okay?

Oh, boy.

-Hey, Ken. -Can I speak with the pilot?

Can you put me through to the pilot?

Um, the pilot can't speak to you right now, Ken.

Yes, he can. Yes, he can

He's... he's flying the plane, son

Okay, what's, uh... What's happening?

Frank, I need, uh... What's... Where's the information?

We're gonna...! We're turning the plane around

We're coming back to Teterboro

Uh-huh, okay.

Well, just fucking tell them... Tell them to do it, uh

to do it right, okay?

I will, I will.

I'm sorry, Ken.

Yeah.

Is he gone?

Frank, I mean, uh..

Is he gone?

I don't know.

I...He...he...

He got very short of breath and he was hurting

and then very...... I don't know.

I don't want to bullshit you, Ken.

I think he went. I think he's gone.

Okay.

Thank you, Frank. Thank you.

Frank think s he's gone.

Why didn't you come and get me? -I did. I did.

Shiv, we did. -No, but I was.

-I was right out there. -I'm so sorry. I'm sorry

How long was it happening before?

I'm sorry, I wasn't... -No, no, no.

We did... we did but I wasn't... -No!

There was, like, no time  -I wasn't thinking.

-There was no time. -I'm sorry. I didn't..

-I'm sorry. I'm sorry. -It's okay

I'm sorry. -It's okay

It's just..

Tom said that Kerry spoke to him, quite a bit.

Right, well, I don't... I don't know.

I mean,we don't know if he could hear us

Yeah. Just I'm sad, I guess

Do we know if he was on his phone?

He checked his messages?

-Rome, it's okay. -Yeah, I know

-it's just... -We're okay

I don't know. I just don't know.

-Like if I said... -You did good

I feel... I feel like I didn't...

Did I say I loved him?

-I think so, yeah. --I'm pretty sure I didn't.

No, I... I... I think you did

No, I don't think so. Uh, Tom, could you put me back

to his ear? Or... Fuck it. Never mind.

Uh, never... I don't know. I don't..

Maybe just... Let's just keep the line open.

I'll tell you if anything happens

-Okay. -That... this cake is fucked

Toss it over -Oh fuck

We need to get Connor. We need to tell him.

Can you do it, Ken?

I think... I don't think I can.

I mean, I could. I definitely could, I just

Thank you.

It's okay. -Do you want me to.

Yeah.

Yeah

Oh, fuck. -Fuck this

That's my brother and sister.

-Hey, Con. -Fucking cake nightmare, okay

Con, Con. -Would you take care of that for me?

-Con. Come here. -Yeah? What is it?

-Come... -Come here.

-What is it? -It's just... It's private.

It's serious, come here.

-Five, okay. -Yeah.

-Come here, buddy. -What is it? Is it important?

-Come here for a sec. -What?

Let's get you, um...

Is it Pop?

Is he okay?

What is it? Is he sick?

What is it? -Dad's on an airplane to Sweden,

but they're coming back

We think he died.

They... They think he's dead

Well, is he?

Well, uh, everyone says he is.

I mean, we don't know.

They're doing heart compressions.

Oh, man.

He never even liked me.

Hey, Con... -Hey... Sorry

You know what? I'm sorry. I'm sorry

I don't even know what I mean. He did. He did

I just... I never got the chance to make him proud of me.

He's dead.

-He's... -Roman is on the phone

-to the plane. -Jesus.

Do you... If you wanna talk to him.

Oh, man. -He's...

-Hi, Con. -I don't know, I don't know.

Anything?

I can't do this, okay? I can't.

I can't. I can't do this, okay?

Hi.

Thank you.

What happened?

What happened? -I'm sorry, man. I'm sorry, I'm sorry

He, uh, uh..

He was on the plane and, um.

--he got short of breath, u h... -I said... I said, " Hello

fucky-sucky brigade," And he was in the bathroom

He was... he was in the bathroom?

Yeah, I don't know. He was in trouble, I guess, so

Wha... wha... wha... wha... What was it?

He got short of breath. -Well, we don't actually know

I mean, like, we don't know he's gone

Uh, okay, so,

he was in the... the airplane toilet.

-Oh, fuck. Shiv, come on. -And.

No, but can we please get this straight?

Yeah, let's just... -How about we get some doctors in there?

Some proper doctors, and then we'll know what actually happened

-Then we can talk about it. -Sure, I mean..

he has gone.

-I think he has died. -Well, Ken, we don't know that.

-So... -Sure. I get it.

But, like, I think they know. -Okay, okay, may be

-Maybe is all. -Roman, I think

you have to accept that.

Okay, I'm not, like, saying anything

All I'm saying is that we actually don't know.

That's it, that's all I'm saying.

Okay, right. Well, yes, but you sound delusional

I sound... Wha... What am I, out-fucking-voted here?

No, Rome, I'm just saying... Come on, you know that...

-What?  -They know..

-No, no, they don't. -that he's..

No! -It's okay.

-That he's... -He's fucking dead!

Well, okay! But there's no need to fucking say that, right?

Until we know there's no goddamn.

What's the point of keep on saying it? All I'm saying.

I'm not being crazy. I'm stating a fact.

I'm saying we don't know.

And until we do know, it's not a very nice thing

-to say, is it? -Okay.

So, fucking stop!

Okay. -Okay.

Sorry. -It's okay.

Come here, come here.

Well, I, uh... I'm gonna have a little, uh, stiffener here.

Just... Uh, gents.

Karolina, pardon me.

Let's drink to him.

Well, I guess we're off the clock.

No, I think it might be smart for us to..

start putting together a timeline

And also, I've been drawing up, just in case, you know,

if we need to, a contact list

Oh, God! He's just... They're still pumping on him

back there, Karolina. -Well, I'm not happy

about it, Karl. -No. No, I know

And I think we're all being respectful.

I'm being respectful, but this is going

to be a very complicated situation to handle

So, you know, if we get a miracle,

we get a miracle. God bless us all.

If we don't, I just have to prepare,

that's all. Right? -Absolutely! Go, go

Okay, so I think we should call Mats son and let him know.

Well, then we should at least call him and tell him that we're..

that he's delayed.

Oh, he's heavily fucking delayed

Yeah. And then, in no particular order

not in this order anyway, um, the board.

Gerri, POTUS, um...

Hey, how are you?

He y, um, that was fucking.

-nuts! That was fucking crazy, right? -Yeah

-Yeah. -It is, it is.

We were... we're in shock. Yeah. -Yeah

That's so fucking weird. Jesus, wow!

-You guys okay? -Yeah.

-We're good. Thank you. -We're good

--Um, Kerry? -Yeah?

If it's all right with you, we're just using this space

to coordinate a response to, you know

if we need to send out an... Do you mind if..

Is that okay? If we..

But... Yeah. Uh, yeah. Do you... Uh, do you want..

-So, do you want me to help? -Oh, no.

No, no, that's so kind, but you're in shock

and I think you should go back there.

And we'll make you comfortable, and we'll bring you

whatever you need, yeah?

Okay. So, do you want me to be, uh.

part of that, of the response and the...

That'd be great, Kerry

Why don't you-rest up in there?

Let us get our ducks in a row and we'll get your input

Yeah. -Okay.

-Okay. Okay. -Okay, I'm gonna be back here.

-There. -Yes.

What the fuck? -I think she's freaking out, Tom.

Yeah. -Oh, yeah?

Yeah. -Judging by her grin

it looks like she caught a foul ball at Yankee Stadium.

-I mean, Jesus. -Okay!

Here is the list of names. I think we divide up

as soon as we get the..

Well, not the... Not the all clear but..

once those 30 minutes are up... -Some of those it's.

It's small for you. I think we should get Kerry to do them

Oh, now you want Kerry to do it?

Good. -Chuckles the Clown?

I think not.

Wait.

Hold that thought. -Sure

-Hey, Tom. -Hey, Greg, hey

So, I might need you to whiz into the office for me

Um, it's a wedding day, Tom. Why?

Why, um, because Logan is dead

Uncle Logan, really? Uh, how... what... what..

So, listen to me, you... You have to stick to Cyd

like a limpet, okay?

And you delete my folder marked " Logistics,

And then you delete that from the trash

And I might need you

calling around with my narrative

You sing my song

-Merry Christmas, Greg. -What? What do you mean?

Well, he's passed away and you've lucked out.

And, yeah, what's at the bottom of your stocking, Greg, huh?

An old guy who fucking hated you

Tom, man!

Easy, dude, like... -I'm sorry, I'm sorry. I'm sorry.

Are you okay? Jesus

I'm not okay. I'm not okay

I'm sad

Uh, but I'm sorry

Yeah. But, um, Fuck

I don't know. It was pretty grim, man

Yes.

-It's a horrible... -I lost my protector.

Okay? And... and

... this is total lockdown.

Okay, Greg? Total lockdown. If this leaks,

it's a stock price rodeo

and a fucking slit throat for the big mouth, okay?

Okay, but people... people should know

that I was with him, okay?

Okay. Okay, man. Okay, bye

Everything all right?

Oh, yeah, yeah. Fine, uh.

Do you think your uncle's gonna make it?

Do I what? -Sorry.

Is your uncle gonna make it to the wedding?

Hey, guys.

Are you... What? Have you heard already or..

Yeah, well, the folks on the plane

thought it'd be a good idea for me to act

as a liaison with you guys

I am so, so sorry for your loss

Okay, yeah. But we don't know shit, okay?

They're still working on him. -Right, absolutely

What if this is a drill? What if it's a big fucking test?

-You don't know.  -No.

If it was a test, I'd say hats off

-to the planning department. -Yeah, well, I just..

It does not feel likely that he's, you know.

You guys want me to wait outside?

Hey, Tom.

Fine. Okay, thank you.

They stopped the CPR

I don't think they should, though

Yeah. Hugo, Karolina wants you

Hey, Kay.

I mean, all good, um.

under... under the circumstances, yeah

-Are we going? -We... we'll.

What the fuck?

No, no, I... I get it. I'll... I'll.. We'll discuss it.

-Yeah, I think we're going. -No

Okay. -Where are we going?

I gotta go, okay? -Hugo? Hugo?

Can you find out what the fuck is going on?

Where are we going? -Uh, yes, I will

Uh, and for your information, they're, um,

they're starting to draft a statement.

How do you mean?

Uh, Karolina and Frank, and

Karl and Tom are putting something together

for when we're ready to release the news

The... they're on the state... statement?

Who asked them to? -I don't know,

but they're doing it. -That feels.

that feels... -Yeah, that feels...

-Right? -Yeah.

Yeah. -Yeah

Hey, Hugo, can you fuck off and find out

what the fuck's going on with this boat?

-Yeah. Okay. -We want to go back

Yes. I'm on it. I'm on it. -Get the fuck out.

Yeah. Hi, folks. Uh, you're on speaker now.

Hey, uh...

So, what's going on with this statement?

Yeah, so we're just starting to put the bones together

for when... when we're going to announce this, um.

Sorry for your loss

Oh, okay. Well, feels pretty fucking presumptuous.

Uh, well, sorry, that's how it seemed

but, you know, regardless of our personal-feeling

of loss, in terms of a business position,

this is... it is a material event

We just need the board to put something together

to reassure the market. -Oh, the market?

Yes, will someone please think of the market?

I'm trying to do my job. He's, like, 12 feet away

and I knew him for 40 years. We're not pulling anything here.

We just thought that since you were estranged

we thought that you might want us to be

-at the hub on this. -We're not estranged

We weren't estranged. -All right

Uh, Kendall, no, I just simply meant that..

We've all had communications with him.

We had a family function last night, in fact

Estranged is a strong word and not accurate.

Fine. All good. Uh, we got it

Yeah, look, he y. Uh, let's stay close, huh?

And the best to you guys. Good strength, friends

I think, you know, they're very much

still processing.

Fucking great.

Shit

How are you all doing?

I briefed her.

I'm really sorry

I'm very sorry.

He was...

He was an important man in all our lives

but especially yours

Thanks, Gerr, I'm welling up.

I mean, he was a lot of things, but

We don't know yet

that he's dead, okay? No doctor has actually seen him

Gerri, in terms of the breathing space,

we have a bit of time to think, right? Until he..

Are you... -Until they land?

Are you thinking, can we hold this information

till the markets close?

Because, obviously

this is a very significant, private thing

Is it? Is it significant?

But it's also a big thing in terms of the public

In terms of the company. -I honestly don't know

how much I can get into this. How long till they land?

I will... I will check.

Gerri, we can't think straight

Can we, keep it up there for an extra beat?

-Just until we can... you know  -What?

-while we gather... -The fucking plane?

Yeah, I mean, I'm not ready to.

Wait. We need to get him on the ground

We need to get a fucking doctor

-on that plane. -No. God! I've got a headache.

Look, I think it's really good

for you guys to stay across this.

Do you, do you want me to ask if they can circle?

No. -No, but..

Karolina. -Not till the markets open

on Monday, but just, you know, so we can think?

Absolutely not.

Can you get... Yeah, and can you get me

-an Advil, please? Hugo? -Of course.

And... and can we get back to fucking land?

We want to go to him, yeah? -Yeah

Thanks for getting Gerri, but back to land.

I'm on it. -Do your job, thanks

Look, this is very surreal

And just to say...

every single thing we say and do today

is going in the memoirs

going in the fucking congressional record

It's coming up at board meetings, it's going

in SEC filings. It's like.

And we tell them to circle for half an hour

so we can get our heads straight and then some

fucking rumor starts, we get crucified

for being cold-hearted, or I don't even know.

We are highly liable to misinterpretation.

So, what we do today will always be what we did

the day our father died

So, let... you know, let's..

grieve and whatever, but..

not do anything that restricts our future freedom of movement

What do you think?

Let's cancel, yeah?

I think it is cancelled.

What do we tell'em?

I mean, everyone will assume that..

it's you backing out and that's fine.

Or...

could something good come out of something bad?

Too weird, right?

-Or is it?-Con.

Con, it feels like you kind of want to do it.

I don't know. I don't..

I guess the truth is..

I'm scared if we don't, that.

that you'll walk away

I'm always scared you're gonna walk away.

I'm so much older than you, Will a

You're young and you're full of life,

and I'm...

I don't know.

My father's dead and I feel old.

It's okay.

And I'm sorry.

I don't know, that I stole you away

from the world. -Con. Come on, no.

Are you just with me for money, Will a?

Basically?

I mean, there is something about money

and safety here, yeah

Yeah, yeah, there is.

But...

I'm happy.

-I am. -You okay?

It's okay.

I'm not gonna walk

Not today anyway

I'm sorry.

What was that like?

When he told you?

I thought I knew.

And actually, I thought it was Dad

But I said, " Mom," Right?

Yeah, you asked if it was Mom.

Yeah, I was thinking Dad. But I sorta...

think I...

Think I was hoping it was Mom.

-Jesus. -shit.

The fucking lists, the everything.

-I don't know if I can do it. -You don't have to

You don't have to do anything, our dad just died.

We'll be okay.

We'll get people.

We'll get a funeral off the rack

We can do Reagan's with tweaks

I have Karolina

So, Karolina, I'm with the kids now

and I'm'going to put you on speakerphone, okay?

Karolina, you're on... You're on speakerphone.

Hey, So, I just got a call

from a reporter who's already heard a rumor

about Logan's... health.

-From where? -I don't know what the source was.

I just said there was nothing on that

Which is n't great, but..

-Man. How? How? -I don't know.

Plane to ground comms, our tail number

we're turning, they're tracking. I don't know

what goes on down there. Eavesdrop, Kerry

We... We probably do just need

to figure out the choreography.

-Oh, yeah? -... here.

You want to choreograph some steps

with my dead father, Tom? That the dance you like?

Sorry.

That's okay. It's... It's a difficult day

So, we're gonna need the statement

Do guys want to do it? Do you want us to do it?

I know that this is tough for you guys, I understand that.

So, if you like, we can give the word

Frank, Karl, myself, Karolina, we could handle

the immediate chowder. And if you like

you could be excused from

the board meeting on compassionate grounds

Thanks, Gerri. I need some air.

Can you give us five before we do anything, yeah?

-Yeah, sure. -Thanks!

I don't know.

I mean, I...

I don't really want to be

the one to have to say things. I feel like

you're looking at me and, yeah, but.

It's okay.

Ken.

It's okay. We..

You can say, " I don't think anything of it.

It's... You can say. -Okay. I mean, just.

I mean, who knows? Maybe we.

Tomorrow, hand in the crown

probably a good idea, finish the sale, great

but just...

Should we keep our options open?

One second, Hugo

Um, yeah, I just don't know that I can

literally do anything or talk to anyone

We need to be on the statement though, Rome

-I know. --Otherwise.

it could be all Frank and Karl and... and Gerri and..

You know, even just overnight, whatever the text is

the subtext has to be..

Logan Roy, you know. But Roman Roy and Kendall Roy

and Shiv Roy. We're all here, yeah?

Okay, and..

I just don't want Karolina to just handle it..

It's just for this statement. -Okay

You know, it'll be for the board to decide

But... but I think until then.

you know, just for the markets.

we need to be in control

Us. -Yeah

Until the board can meet

Yeah, uh-huh, I mean, I would

I don't want anything happening that we don't, like, approve, so

Yeah.

Yeah

Hugo?

We'll draft the statement, okay?

Great. Great. Great

Um, we'll need them to sign off

It'll need to come from Frank, or Simon, or the board..

Yeah, but we'll draft, okay?

And who will call Mats son?

I know but..

Oh, I gotta get off the phone, sorry

-Fuck me. -Okay. Okay

I Hey. -Hey.

Uh, yeah. I kind of need the room

Oh, sure, of course.

I'm, uh.

I'm pretty sad.

I mean, I'm actually, right now, totally numb

but theoretically, you would say that I'm..

-Yeah, that I'm sad. -Yeah.

Well. The room's all yours

It's a fucking mess.

Okay.

-Hey. -I don't know what to say.

Sorry. I'm so sorry, I.

-Hey. -I'm so sorry.

Yeah

Hey. Uh, how are we getting him off?

Uh, I don't know, Jesus. U h, I'll handle it

You... you got the edits on the statement?

We do feel that for market competence, it's important for Karl

myself and Gerri to be mentioned by name

Great, I'll get that out right away

Uh, and, look, we got

shutterbugs all over the perimeter

and we're looking at a feeding frenzy

if we don't talk. So, we're gonna

get some comments from the family

-and I primed our friendlies. -Duty calls

O h, uh, the press conference is happening in there

and the kids are already in, so..

I'm gonna... -Yeah. Go, go, go. Yeah, I know.

Hey. Hi. So.

Hello. Hello, everyone.

Are we gonna be okay?

Yeah. Yeah.

We'll be okay

You're not gonna be okay

Well, you're not gonna be okay either

You're not gonna be okay

-You're fucked. -You are fucked

You're totally fucked. -You're very fucked

-Okay. Hi. Everybody ready? -Yeah

-Shiv? -Ready?

Sure?

All right.

I... Thank you.

As you know, my father, Logan Roy, was pronounced dead

on arrival at Teterboro Airport this afternoon

I'd like to thank the press for their respect at this time.

You'll understand that I won't be taking any questions

But my brothers and I just want to say

that Logan Roy built a great American family company

And as you know, the board will be convening

in the next hours to decide on the leadership

of the company going forward

This nation has lost a passionate champion

and an American Titan, and we lost a beloved father

-Thank you. -And in terms

of your roles at the company?

We intend to..

We intend to shepherd it through it's

Whatever its future may be, but we'll be there.

We intend to be there

Guys, guys, thank you! No more questions!

Guys, no more questions. No more questions, please

Respect the privacy of the family

Thank you very much.

Hey.

There he is.

That is Dad.

Okay, so, we gonna go see him?

Do you want to?

Shouldn't we?

I mean, he's not gonna get angry if we don't.

Yeah, right.

Hey, Tom! Can you..

go through it again? What happened?

I'm gonna go... I'm gonna go see him

Do you wanna?

Uh, I'm gonna... I'm gonna...

watch him down from here. -Okay

Okay, so...

Yeah. Okay.
