

= 继承之战 S04 - 08
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



== 释义



'''

== pure



He's sleepwalking into oblivion

Uncontrolled migration, hyper-inflation

rampant crime

rampant crime, cultural Marxists..

Here we go. The 5.00pm.

All good?   -yeah, I'm good, Greg

considering it's my first post-Logan election

and I have Cyd running around town

spitting poison like a fucking king cobra with an i Phone.

I have PGN to the left of me, and I have FVA to the right

I gotta deliver the best election numbers ever

cause my bosses wanna rip my heart out as a peace offering to all comers

so, no, Greg, you know, I'm a little bit tense.

Just a little bit. A little bit tense.

Well, yeah, I'm feel in 'pretty good

I got to the polling location at 11.00am.

I thought it was very odd that the line was so short

Hey, Tom.   -Hey, Ken.

You good? You feeling good?

Needs to be gangbusters tonight, man, yeah?

Yeah. You got it, you got it.

All right. Need those numbers, T.

Really wanna see those numbers, Tom.

Okay? Market's watching.   -Okay

First Super Bowl, how we gonna cope without the king, right?

Okay, got it, Ken. All good, all good

Hey, Pam. How's it looking?

A bit of crackle.

We have a news van in a bit of trouble in Oregon

Things looking fight y in Milwaukee.

Did you see the viral thing about the woman

who voted, like, 40 times for Jimenez under her dead mom's name?

We tracked her down. Not super reliable

She's not a well person.   -She's..

Well, you're not a doctor, Pam.

Until you qualify, why don't you get her on the air?

Long night in dress shoes?

Cyd used to go for these sort of slip-ons with a padded sock

Yeah, probably 'cause she couldn't get her cloven hooves

into her regular shoes.

I'm perfectly comfortable, Pam

I've got good arches.

They've been remarked upon.

5.00pm exit polls. Come on, 5.00pm

Hey, Darwin, you don't... Oh, they're cool

You don't... You don't do anything special tonight, do you?

It's just somebody was talking about adult diapers?

Oh, no, I think there's always time for the bathroom

Fine. Okay. Thanks.

Okay, excuse me. Coming through. Coming through here, coming-through

Hey, everybody. So, terms and conditions.

Forgive me, those of you who already know this.

Did you get... get some rest, though?

No. No, marital strife

Can I hear a "got it "?

Got it.

Thank you. Also.

How was your night?

With Matsson? Pretty monstrous

His crew knows some unseemly venues

I danced with an old man.

What?

Yeah, he didn't wanna dance

but they made us dance

He was so confused.

I drank... things that.

aren't normally drinks

And I... I got the impression...

Do you know about Matsson with Shiv and their sort of

like, their... their business alliance agreement?

Well, I'm sure I don't know what you're talking about.

Okay, I didn't think so.

You wanna strategize?

You wanna fry her ass up?

Information, Greg

It's like a bottle of fine wine.

You store it, you hoard it, you save it for a special occasion.

And then you smash someone's fuckin'face in with it.

Nice.

So, what we're hearing is..

and remember, this is not decisive

what we're seeing is Mencken

may be over performing in Georgia and Arizona.

So, our early read would be closer than polls have suggested

Close, but Jimenez likely edging on what we've seen.

Listen, this is privileged information.

Leaks that suppress or encourage turn out

could result in our ejection from the National Election Pool

Okay?   -Yeah.

Yeah, you heard the man. Zip it.

That's great.

Okay, Tom says exit polls say looks like Jimenez.

No leaks.   -That's great.

I mean, I got four smileys from Gil. They think they've got it

Well, I have got eggplant, eggplant, flag from Mencken.

Well, two eggplants is not as much as four smileys, obviously

Four smileys is symptomatic

of the complacency at the heart of his out-of-touch campaign.

Eggplant, eggplant, flag reeks of the misogynistic bravado

that has so repelled the median voter

Jesus. Ah, I feel sick

Oh, why? It's fun.

My team's playing your team.

It's only spicy 'cause if my team wins

they're gonna shoot your team.

Okay, but what are you hearing, seriously?

Are these your vans, the Nazi vans?

The van? Oh, the... the fun vans?

The... The fun buses? Yeah

Yeah, in Florida they picked people up

telling them they were taking them to vote

and then a kid got left by the highway

It's fucking kidnapping, Rome

It's fucking kidnapping now?

False flag. Nice try

Kidnapping. It's kidnapping

-Hey.   -Lukas, hey

So, it's looking like Jimenez

which is good for democracy and great for us

So, either way, I think that we consider releasing your..

you know, your funky numbers may be tomorrow

Day after tomorrow.

Just get ahead of the numbers

and, you know, I can come up with some language

Yeah, I was... I was talking..

I ast night to Oskar and Gregory Peggory about that

I'm sorry, you spoke to Greg about this?

Yeah, well, he was part of a conversation just as a normal ist

And... yeah, then I was wondering, you know, maybe we.

maybe we keep my... my terrible secret a secret, you know?

Okay...

Yeah, look, let me have a think about that

I gotta... I gotta take this. I'll... I'll call you back

Nate. How's things in Mission Control Denver?

Are you in at ATN, Shiv?

Upstairs.

Leave it to them. Dad's rules

Well, they need to be covering the intimidation s

It's pretty dark, Shiv.

Who watches the watchmen? I fucking do

Are you getting good numbers?

Good. Just watching the weather.

Storm clouds in Nevada

We got people in line

A disturbance in Wisconsin, but.

Yeah, scared but good.

Precinct data's..

Pennsylvania, Arizona could be tough

Let's keep this channel open.

On all things Matsson and me and the new ATN, yeah?

All things good

All right, so Jimenez wins

and he just waves the fuckin' deal through

and then we're what?

I guess fuckin'last ditch, the board?

The shareholders?

Okay, Jeryd wants face-to-face.

Okay. Me, too?

I doubt it. I'm asking

Do you wanna try Gil or maybe direct to Jimenez?

It feels kinda sweaty. Maybe I wait a day

A day... I mean, I guess today's the fucking day, right?

Like, today's the day the rooster puts its head in our hands

Today is the moment of maximum leverage

Yep. No, it looks like just me

-It's a bit tight for both of us.   -Fuck him.

All right, go... Sure, sure.   -Going

Let me know what you come up with

-Hey, Rava.   -Hey, listen.

-We... We are all okay, but...   -Yeah

we're a bit freaked out

There is an SUV with..

Well, we think there's an SUV, and it's... it's following us.

So, can we come to the office?

Because you... you have good security at the office

What's the license plate?

The license, it's T... 3, I think.   -Is it T, TR? Right

'Cause it's probably... it's probably mine.

I didn't want Sophie to freak, so I just... I just action ed it

Are you? You're..

Oh, my god, you're having me followed?

This is covert surveillance to show you care?

The actual fuck, Ken?

Just an extra layer of bubble wrap

Are you guys okay? You okay?

Is she okay?   -She's scared, Ken

Okay? I'm... I am scared.   -Rava. Rava, listen.

Just...   -I don't know what they're...

There is... There is shit burning, there is intimidation.

I don't understand what's...   -Relax

Okay? Relax.

Tell Sophie I love her,

and that is why I do everything I do

Okay, Soph?

Soph, I love you, sweetie, okay?

Nothing's gonna happen.

Exit polls say Jimenez, okay?

I won't let the world push you. Okay, sweetie?

Okay.

Ken.

Hey, man. Just... Just calling to say good luck

-Great numbers.   -Thanks, man

And listen, apologies if... if things got a bit heated.

A lot of shit going down.

Victory vans, his shitheads kicking off in Milwaukee

ATN wanna cover?   -yeah, I'll... talk

but gotta let them do their thing, but yeah

Yeah.   -Okay.

Listen, you got Daniel there?

You know, let me... let me see.

Yeah, come in

Sir, you here for Kendall Roy?

-Hey, Kendall.   -Hey, Dan.

Hey, man.

Good luck

Good luck. Just... just best of luck

Thanks, man. Great to speak

But... But when this is over

I think there needs to be a big conversation about tech

is all I'd say.

Great to speak. I'm gonna put Nate back on

Sure, and... may the best man

who will, you know, protect American jobs

and rein in tech and is called Daniel win, you know?

Let's catch up. Have... have a good one, man.

Yeah, sure. Sure, man.

You know, tonight, my eye is just right here

making sure it's fair as fuck, all right?

Have a good night, man.

Stay hydrated.

-Hey. Come on.   -Yeah. Hell yeah

Thank you.

Busy, busy. Hello, hello

Look at you, loss in'it.

Like a massive fuckin'loser.

Yeah. Well, I blame you.

Couldn't deliver Connor, huh?

ATN scared to run all the fraud.

Well, I keep my hands out, you know?

Fuck you. What is this?  'Cause, you know, I'm quite busy

You're busy?   -Yes, I am busy.

I don't run around town like some fuckin' food bike guy, you know?

Just wanted to say a couple things

Yeah.

Very directly

-We still think we can win.   -Sure

But I am very focused on losing.

All right.

Winning is easy

-Winning would take care of itself.   -Sure.

But if I lose..

I need to work on what assholes would call "the narrative."

Like "insurgent campaign unfairly maligned as extremist

by the coastal masturbation factories."

Exactly, if I lose,

I want it correctly characterized as a huge victory

Over performed. All right?

I wanna be a president.

I want you to be a partner in that

and if it isn't tonight, it will be next time.

" Even if you're not going to be the president

you're going to be our president."

Exactly. " You, me, we'll go far..."

" Over the road and into the bar.

So, listen, at... at some point tonight, can we do a chat

in terms of the... the "me" of things and, like, how to play it?

Because Matsson, he treated me quite abominably

But it felt like trusting

and he was saying a lot of things

and quite relaxed...   -Okay, okay. Enough..

Where's my coffee?

Tom, I don't do coffee anymore, man.

No, Greg.

Greg, I have to be clear. I have to.

If I get drowsy

and I... mis-call Colorado

Instability, right?

And the US loses credibility

China spots an opportunity and invades Taiwan.

Tactical nukes.

Fuckin' shit goes kablooie and we're back to amoeba

It's a long way back from pond life

cause you failed to get me a double shot, okay?

Okay, well do you...

do you want some of what you asked for?

No, I don't. I don't think so. What do you think?

Maybe no. I mean, election night.

Your call. I mean..

Yeah, hit me.

But this is not a... not a thing, okay?

It's not going in a book

-Let's just...   -Yeah.

-Yeah. Okay.   -Quick, quick

Quick as a whistle

What do we have here? What's one the.

-What's on the board?   -the board?

All right.   -There is..

Just rubbing the board innocently

Simply cleaning the whiteboard here.

Okay. Here we go.

-No... Not for me. No, I...   -What?

No, I'm just starting to feel normal from last night

What? You'll do it with Matsson and not with me?

I don't want you looking all judgy all night, come on.

No, I need a clear head, and I don't wanna get addicted

-Two nights in a row.   -Shut up, Greg. Don't be Mom.

Come on.   -I don't want to. Please.

Greg, it's medically good for your brain?

It is.

What are you saying, all Aztecs are stupid?

Don't be a racist little bitch about it

Come on.

-Yeah, okay.   -Come on.

Don't... What? Are you pretending?

-No...   -Are you pretending to do coke?

Some got up.   -Fucking do it.

There. God

Okay.

What the fuck is that?   -Oh, that.

I guess they... they were ordering some for folks.

I said why not get you one?

Bodega sushi? Are you insane?

I... No, that's not me. That's Samson

No, not Samson, Greg!

Not Samson! Not!

I want you Gregg ing for me

You're busted back down to Greg tonight

No.   -Yeah, tonight.

My digestive system is basically part of the constitution, okay?

Microwaved milk and ginger shots

American bottled water, and spaghetti and olive oil, okay?

-Okay?   -Okay.

Okay.

Hey, Con.

Tom.

Yeah, I got this crew here

and they're filming the stuff

but none of it is making it on the show, dude

Is there any film in these cameras?

Yeah, I think we are... we are planning to feature, Con

Well, no. Because I'm watching

Now, I expected to be frozen out by all those other mooks

but you guys? Come on.

Give me some sugar, man.

I mean, maybe everyone voted for me.

We don't know.

Schrodinger's cat,

Schrodinger's cat, Tom.

Until we open the boxes..

I'm just as much president as the other two.

Yeah? Come on.   -Let's go, let's go

If I do it, that's the story of all time.

Okay, well, I'll think... I... I've gotta go

But I'll see what I can do. But I've gotta go

'Cause the polls are closing.   -Yeah

Okay, if it's gonna happen anywhere, it's gonna happen in Kentucky

Anything can happen.

Anything can happen, anything can happen

Yeah.

So glad I didn't drop out.

It just makes an election so much more interesting when you're in it

You gotta be in it to win it.

And it is seven o'clock on the East Coast

which means polls have just closed in half a dozen states

The most closely watched states at this hour, Georgia

with its 16 electoral votes

and Virginia with its 13,

both key battleground states

As of this moment, it is too early to project a winner in either.

But our decision desk can announce at this hour -Okay.

that Representative Jeryd Mencken

will defeat Governor Daniel Jimenez in the Commonwealth of Kentucky

as well as in the state of Indiana

where Mencken has enjoyed a lead over Jimenez

-in the pre-election polling.   -Okay

Governor Jimenez will win in the state of Vermont

no big surprises there,

in the early part of the evening

We will need to look at more data before we can make a projection.

Hey. Fuck Kentucky, Con

-No.   -Yes, fuck'em

No.

I...

I shan't become that. No

Alas, Kentucky, Willa

Alas, vanity

Voters have made their voices heard

This could be the most important election in our lifetime

-So, with polls about to close...   -No, I told you

You can give it to me, Billy, thank you

As we heat up, Tom

how much do you wanna give to.

Fair bit of intimidation.

His folks and ours.

So, like, fire in Wisconsin, in Milwaukee could be nasty

Could be electrical failure, might be Mencken ists.

Camera smashed, crew harassed in Portland

That's the m.   -I trust you.

Again, a little board malfunction here.

What's he doing? What's this?

-Hey, Pam. What's going on?   -Hold... Hold on.

The touch... The touch screen.   -Hold on, we're checking it out

What's happening with the touch screen?

Tell him to stop touching the touch screen

-We have a replacement in place.   -The touch screen is malfunctioning!

-It's fine, it's fine.   -Not fine

You can see that it's not fine!

-We have a replacement on the way.   -It's malfunctioning! Fuck

Touchscreen's malfunctioning

And we're gonna zoom in..

Right, as you can see, right here.

The board seems to be acting up

What is going on with the touch screen?

The touch screen is malfunctioning

What... what's going on? What the fuck is going on?

Right, we're on it.

A graphics generator, just... It... It shat the bed

What?   -Where is my touchscreen?

Don't, you're losing it, Dave.   -On main desk

On main desk.   -Don't lose it, Dave.

Don't lose it tonight, Dave.

It is now 9.00pm on the East Coast

Okay, can we get an ETA on that replacement?

What the fuck's going on with the touch screen, Tom?

I'm on it. I'm all over it.

You're not on it. Fucking get on it

Figure it out.

Yeah? Figure it out. Now.

It's happening. Ken, it's happening. He's already..

We're about to get a new batch, Greg

and if we drop numbers now, I'm gonna come down there

and put your fucking head through that touchscreen.

-It's all in motion.   -Fix it..

No need to cat astro phi ze.

Where's the touch screen, Pam? Is it loading up?

It's loaded up.   -Well, get it on air

Get the new one on air. We're gonna be hemorrhaging.

We're gonna be a laughingstock

We're on it, Tom

No one will notice. Okay?

We've done this before.

We have three, and they're all lined up.

No one will notice? I noticed.

Am I no one?

Do I look like no one, huh?

Do I?

I mean, how the fuck are we behind social media on this?

All right? We need to be leading this

-Hey, Tom.   -Hello?

You got this fire in Wisconsin. You... Have you got this?

Yes, I think we... Yes, I think we have that.

-Yeah. Electrical.   -Why aren't we covering, Tom?

Well, because we always have to choose what to focus on

and just because something is on fire doesn't make it news.

Electrical failure?   -Not what we hear.

No, it's... it's not what Nate hears, Tom.

Well, bully for Nate.

-Hey, Tom.   -Hey, Nate

We need to be all over this, Tom.

Yeah. I... Okay

I just think it's important to... to keep our unique perspective

because we are getting conflicting reporting

What about the actual photos I can see of it happening

on my fucking phone?

Look, there are many, many things happening in this nation right now.

There are-a million-data points

and we... we have to select the ones that are consequential

If these nutjobs are going paramilitary, we could say that.

Yeah.

Yes, we just need to respect our viewership

By not telling them anything they don't wanna hear?

You guys get this about the Antifa firebombing in Milwaukee?

Well, we... we hear it's his people, Mencken's.

Okay, when it becomes a story, then we'll run the story.

Well, this is happening in what?

A vote-counting center? So...   -Yeah, it's a story

Tom, it's a story.   -On it.

-Do not micromanage me, please.   -Tom?

-Yes, yes.   -Tom, they're evacuating

We've got a local chopper up and a reporter on the way

Okay. Guys, I've got To manage this

I'm gonna... But, I mean, I'll keep you looped, yeah?

Talk to Greg, yeah?

Yeah. Hey, hey.

Happy to keep you fully abreast here.

We're not talking to Greg.   -I can be your link up guy

No. What the fuck?

Amateur hour down there

Okay, so, if it happened in Milwaukee and if it's deliberate

then it's Mencken ists

False flag. Could be.

You can't just say "false flag'

-every time you don't...   -False flag

-fucking agree with something.   -False flag.

Okay, guys.

We wanna report about a fire in Milwaukee

initially thought to have been caused by an electrical failure.

But now there are claims and some counterclaims

being made by groups who were protesting

-alleged voting irregularities...   -Hey

Okay, well, do you know if any of the ballots are intact?

It doesn't look likely

Where are you at?

Depends how many votes have gone

But ballots have been lost?   -Oh, yeah.

We're chartering flights to milwaukee.

A ton of number-crunching by our analytics team

We're trying to check the Milwaukee County voter rolls

to see who's voted so far, but..

Listen, can you help with the narrative?

Oh, yeah.

Okay, well, have you got all the bodies that you need?

Yeah. Yeah, we have bodies.

We have a SWAT team on it

They're interfacing with the Wisconsin team

Apparently, he's just touching too hard

Greg.

What?   -He's touching way...

What? No. Rome.

Roman, no brass on the battlefield, okay?

That's one of Logan's Geneva Conventions

-Please, please.   -Just a pop-in. What's going on?

They evacuated the count center?

No, I don't know.

I've just lost another touchscreen.

I'm down Tomy last fucking touchscreen.

What's going on?   -Oh, nothing.

Tom just thinks that China's hacking his tech.

I do not, but I do think you would be more comfortable upstairs.

Greg, will you please.

-Will you please help them upstairs?   -Oh, yes.

I think you will be comfortable upstairs

-Do we mind if what?   -Hello? Tom

-Hello, Siobhan.   --Can I just wrangle you...

"Wrangle? " Stop saying "wrangle." -Were the ballots still in there?

Okay. Where... Where are we?   -What's going on?

-Tom, can you catch us up?   -Greg, can you please take the VIPs

to upstairs setting?   -Yes

-Can I grab the three of you and...   -Greg, can I.

-Tom. Reporter on the way.   -Yes?

-Three, four out.   -Okay. All right, all right

-Tom?   -Yes?

Can I... Can I have a word?

Really?   -Won't take long, Tom.

-I really can't.   -I know, but just let me..

Okay, I just...

Can you please?

I just wanted to apologize

for some of the things that I said last night, okay?

Okay, okay.

And to... you know, give you an opportunity to..

Well, I can't do it to that, so..

How should I frame my face?

Are you scared that I'm gonna blab about you and Matsson?

My father just died, yeah? My..

Like, my father just died.   -Yeah

So, maybe, you know, I can get a little consideration on that

and for, you know, a number of reasons I've been feeling off-kilter,

So I'm sorry, but..

could I get a modicum of?   -Sure, sure.

What does that mean?   -Sure.

-" Sure?" -It means you hated him, Siobhan.

didn't hate him. I love him

Well, it was complicated

but sometimes, you certainly hated him

and... and you also sorta killed him

What the...   -Sort of.

Sort of.

That's the part that I'm gonna remember.

Thanks. No, thank you. Thanks. No, thank you

Okay, you know what? Actually, also, I'm pregnant

Yeah. By you.

And there's... never a good time to say

but you need to know, so okay

-Now you know.   -Right

It's

That even true?

What?

Like, is that even true?

Or is that, like, a new position or a tactic?

Or what? What?

Okay

We... So, we have an area.

I guess we... Is it the upstairs?

Yeah, this way.   -Are you okay?

Yeah. Yep. I'm...

Look, I think things are tough.

with... with my situation and Tom, but

You want us to have him killed?

-I could do that.   -Yeah, may be. I.

I mean, I think, you know, he's just..

He's just a piece of filth

and there's stuff I would like to tell you, but I.

Hey, I've been trying to get them Tomove

not in a aggressive way, but... if..

Yeah, I mean, you just can't trust him

Yeah. We got you.

-In terms of the fire, it is still burning -Thanks

and crews are struggling to contain, let alone extinguish.

Are there any reports, so far, of injuries?

None for now, fortunately.

The building was evacuated immediately

and all workers have been accounted for

Well, I'm gonna sneak, now that we're all in here.

Who's responsible?

That’s the story, right?

Who burnt this place down?

Tome, it always comes down to a couple old favorites

The blacks or the Jews.

I'm kidding. It's a fuckin'joke.   -Would you please? Please?

Got it.   -All right, here.

-Shiv, just follow me. Follow me.   -Hey, Connor.

Rome.

Jeryd isn't picking up

Yeah, I... I wonder if it's a busy night for him

Because I wondered if what we talked about might still be on offer.

Ambassador ship-wise?

Yeah, well, that was kind of a yesterday offer, Connor.

You know if he doesn't make this

you're gonna be partially fucking responsible

-Hope you're cool with that.   -Rome...

I've spent, like, a hundred mill here.

Couldn't I get a sniff of even a little guy?

Organize a little coup down in old Peru?

Put me in a van to Tajikistan?

Couldn't I just be our fun guy in Uruguay?

Your rhymes are compelling, but what's in it for him, Con?

Oh, maybe just one of the finest political operators

of his generation sorting shit out?

Okay, yeah. I'll... I'll get back to you.

Just this one

Yeah, every four years, in fact.

It's probably going to come down to a handful of states

I ike Wisconsin, Ohio.

Pennsylvania, Georgia, and Arizona.

Ignore the narratives early on

and just realize that

that we're going to be in for a dogfight for late night

in those last couple of states

It is 11.00pm on the East Coast.

Polls have just closed in four more key states.

Okay, thanks.   -The ATN Decision Desk

can now project that Daniel

So, under state law, the vote can't be certified

until the absentee ballots are counted

So, no Wisconsin result is valid

until the absentee ballots are counted

Okay. And how does Daniel feel?

Confident, but terrified

I don't know. Is the re a... Is there a name for that feeling?

" Cuspy "?

Rome, so under Wisconsin law, the vote can't be certified.

Mencken says we're done. Wisconsin's done.

That's their position.   -But, well, no.

There's, like, 100,000 absentee Milwaukee ballots missing

So, we have to figure out a way to go forward.

-knowing that information.   -Go forward? To undermine Mencken's lead?

Does he have a lead?

-I mean, is... is that right?   -Yep. Yes

An artificial lead.

With 100,000 Milwaukee absentee ballots missing

Every vote must be counted

-I think she's right.   -What?

I think she's right there.   -Well... Well, yeah, okay

But we... we can count the votes that we have.

However, unfortunately, some are lost, so...

" Unfortunately, some are lost "?

Meaning what? Fascist fuck heads burnt them.

We literally do not know that.

It could very easily be your fucks. They love fires

You're making hay from political violence.

Or your guys knew they were going to lose

so they did something crazy to throw it into question

-and get a revote.   -You don't believe that

Yeah, maybe I do. I don't know.

Okay, well, Jimenez is gonna take Pennsylvania, Michigan, and Arizona

so I don't know why you're getting so fucking uppity about this shit

Why are you getting so uppity about this shit if you're so confident?

Because if Mencken wins, it's the end of the world, okay?

So, I'd like a little fucking cushion.

Jimenez won't block the Go Jo deal,

so fuck the guy, right?

Well, who knows? Maybe he would.

And that's not... You can not let that be the thing that's..

That's not the thing, right? Ken?

-Ken.   -I don't know.

No, don't... don't get cynical.

It's not... not cynical. No, it's just..

What's happening is happening

-I'm a realist.   -Oh, yeah.

Says the man who'd cut his son's throat

and the n eat him on the high pass

Hey, so FVA is saying they have enough vote reported to call Wisconsin

So, Freedom Voice America and Vera News are calling it

Great, the maniacs.

Well, can't get outflanked, and we need to be fast

so I think we should call it, right?

-Wait, hold on, hold on.   -No..

Tom, what... what is, like, an independent?

Can... Can you get us Decision Desk Darwin?

Yes. Yep.

I want to say a few words about the emerging situation in Milwaukee.

A situation the American people are watching with increasing concern

We have a process, and it is..

" Respect the process. Count every vote."

He's so fucking dull.

Flop your dick out. Pop a nut. Do something

That decision will have no legitimacy

if it does not account for all the ballots cast.

Okay, Dar. Thank you.

And we have some thoughts and some questions. And.

Thank you, Darwin. Do you have a result as it stands in Wisconsin?

We've tallied the vote totals so far.

Yeah, I know. And?

The margin for Mencken is significant

Couldn't be made up by outstanding existing uncounted votes.

Only the ones destroyed

Okay, and we're not waiting for burned votes, so we call it.

-No, I... I think...   -Right?

I think they have to hold it again.

No? Like, a revote

I would say re vote is incredibly rare and complex

because while we theoretically know

everyone who requested an absentee ballot

we don't entirely know how many turned them in

and there's nothing in Wisconsin law that really covers what to do, so..

Exactly. You can't do it. Boom, Mencken. Thank you.

But, of course, we think... we... the team knows.

we know how the missing votes would have broken down.

Well, they're gone.

There's no way to know what was on those ballots

Well, we... we do know because past elections

Milwaukee overwhelmingly votes Democrat.

But you don't actually know.   -Sure

I just, basically, do know.   -We do know.

Because you're so plugged in,

you know how the little peasants vote

what's in their hearts, 'cause you don't know.

Rome, Come on. This is the grown-ups 'table. Be serious

This is serious.

This is serious. Ballots get lost every election.

You can't get burnt ballots back

Bullshit. Just bullshit.

Bullshit...   -It's not bullshit

-Full of fucking bullshit.   -Shiv.

Shiv.   -What?

-You sound a little unhinged.   -You fucking watch it, Tom.

-We do know.   -Okay, okay.

There's no way to say in here how people would have voted

I mean, you wanna just run your model and not bother with all the people?

We're saying. historically, people overwhelmingly

Historically, people used to burn witches.

Are you saying we should do that?   -What the fuck? Burn witches?

Rome, look,

we just know that the fire would have destroyed

a lot of Jimenez ballots.

Oh, so fire favors GOP, claims mad witch

We just know.   -Okay

Well, we're not gonna rerun the election

and if the right gets wrongly blamed for this, what would that do?

If the left does? Could get nasty

Where are you going?

I am going to the bathroom to shit.

Would you like me to live stream it?

Ken, you wanna weigh in?

-I just think it's hard.   -But we know.

We just do.

That if the lost votes were counted, Jimenez would take the state

Mark is commenting directly, ATN voice.

...national politicos who, time after time, come up with

isn't this funny.

with polls which under-count support for traditional values

So, yeah, maybe some of the crazies heard they were underperforming

and decided to stop the counting and destroy the evidence.

And so, yeah, you just stay quiet.

Roman sent talking points

We'll guess what we think was on those ballots.

We'll decide, yeah?

Is he down there?

They know best, right?

And you'll eat what's for dinner

because they don't really care for folks who answer back

or ask too many questions.

Shut up. In numerate residuum.

We'll figure it out

and issue you with your new government to march into your homes

and take whatever we want in the way of your mechanisms of self-defense

and tell your son she's actually your daughter

or the other way around, and then.

Hey, Shiv, do you mind actually not going on the floor?

Shiv?

And the new president is opening up his borders to his friends

Bullshit. Bullshit, Roman. Fuck you

It's obvious, painful

We need to be smarter than this, better than this

We need a fucking opposing viewpoint

Would you call security?

Sorry, you can't come down here. It's... It's not me. It's just.

Hey, Lukas.

What the fuck is going on?

Yeah. Great fucking question.

Powerful commentary, huh?

I don't feel good necessarily about this, Rome

Shucks.

Is it okay? Do I need to hustle?

Do I need to get ready to be cozy with this fucking Mr. Scary here?

No. No, I can handle. I can handle it

Yeah,'cause Greg tells me it's getting kinda hairy in there.

Don't let them break my toy, Shiv, okay?

No. All good. I'll be in touch.   -Yeah. Got you

Sorry, we just need you off the floor, if that's okay

Yeah. Got a minute?

And now, apparently the Democrats are accusing this fire of being biased

That's right. Yeah

That sounds pretty much something out of their camp.

It only burnt Democratic votes

Yeah, you know, it's one of those... it's one of those picky fires.

Come on in.   -Yeah

So...   -Yeah, just wanted to check in.

You know? It's been busy, so.

Right. Yeah, on election day.

Yeah, yeah.

So, how was your night last night with Lukas?

Shiv, I... I went for a drink with them.

That... That's not my fault

Do you find me attractive, Gregory?

I don't think of things such as that

Oh, I thought you were a disgusting brother

Is that... Oh, was that too disgusting for you?

This is not appropriate.

Yeah, I... I'm sorry.

Cause I'm just letting you know...

that if you try to fuck me.

I'll kill you

Got it.

Got it. Sorry. Yeah.

I guess my... my only question..

would be if... if anything did come to pass... in terms of you and he..

you know, silence is golden

Like, how golden?

Is there an offer?

Yeah

How about I offer for you to keep all your internal organs on your insides

rather than I pull them out your ass hole?

Go on. You're lumber.

Keep your snout out.

Simultaneously destroying diversity of opinion wherever possible

Hey, guess what?

Mencken will block the deal

Straight up. He'll kill it.

If he wins, he'll refer to FTC, whatever.

New law, foreign ownership tightening

Whatever. He'll screw it up

In exchange for our support tonight

In, like, in so many words? Or?

In those words

Shall I get Tom?

Shall I get the human abacus?

Shall I? Let's do it.

This is good news.

Hey.   -So, thanks for whatever.

We have the votes, so..

Can't rerun fairly

and can't let lefty terrorism affect us

So let's call it.

On what precedent?

By... By what authority?

By the power of me, the CEO of Waystar

telling you what to put on the telly-box mouth people.

I don't think we can do that, guys

I think we can do it, Dar.

If we call it and the... the others went his way..

Right, well, look, there are still outstanding states.

There's Michigan, Ohio, Georgia, Arizona.

It's really not that big a deal. It's one state.

I'm worried it's not a decision that I could necessarily.

Yeah, thank you,

and everyone respects you, Darwin

but this isn't actually a numbers thing

I mean, the Wisconsin Elections Commission

the Milwaukee Election Commission will go to court

and the camps will litigate it

and it'll be a jurisdiction fight that I think Mencken might shake

but, you know, I..

-We can't... I can't just...   -Yeah. That's... That's great.

But I'm just gonna say we're good and that's on me.

The votes that exist have been tallied

and that gives Mencken the state

But you don't... you don't make the call

make the call

We're gonna make the call together, Tom

You can't make the call until I make the call

Okay, so I'm... And I'm not gonna make you do anything

This is the situation in Wisconsin

How would you feel if we were to... not "call it " call it, but..

Like, pending. We could call it pending.

You could even explain it.

We can get a camera on you to explain it to people.

I could explain.

And could there be a graphic that makes it clear

the call isn't... a "call " call?

Pending call.

Sorry.

All right, so...   -Yeah?

Satisfied, fucky fucks?   -Okay

-Sure we can.   -Great.

What's up?

You okay? What?

There's something in my eyes.

Greg. Hey.   -Wasabi.

Is it wasabi?

There's wasabi in my eyes?

Oh, Jesus.   -I've got wasabi in my eyes?

Oh, wait... Hold on.

-Here.   -No, it's gone more in.

It's gone more in

-What's going on?   -It's on my fingers.

It's on my fingers.   -Are you okay?

What did you do to him?   -It stings.

Get some water or something, Greg

Holy mother, mother of God

fuck me slowly, this smarts!

-Okay, Greg...   -Put... Put water in it.

Put... Put water in

It's was a bi...   -That's lemon! It's lemon, Greg

-That's clear! It's La Croix!  -Jesus! Fuck!

Greg, what are you doing?   -It's lemony

-It's lemony! -Jesus H. Christ!

No, it's natural, like medical.

Give it to me. Oh, my gosh

It's not that lemony. It's just a hint of lemon.

Darwin? You good to call it?

He can't fucking call it, Rome.

We're calling it, Shiv. He just called it.

-Great.   -Okay?

Greg, do not put any more lemon water or wasabi in his eyes

Okay?

-Do we look okay?   -Yeah.

Hey, Con. You shouldn't really be in here

And a very good evening to you, too.

Hey, Presidente.   -Rome.

Sweetheart... One sec.

Would you wait over here for me a second, baby?

Fellas, would you wait over here for me a second?

-Yeah, yeah?   -Rome. One thought

How about I concede in his direction?

scratch his balls, he scratches mine?

That's interesting. Perhaps-ish

Let me check on that. Yeah

Perhaps-ish?   -Perhaps-ish, yeah

Come on.   -I'm coming.

Pam, we're calling

Wisconsin for Mencken. Get the graphics up

Dave, let them know we're five out from calling Wisconsin

All right, we are calling Wisconsin for Mencken, five minutes

Is that graphic ready?

There is a big ol'call to make right now

and that is ATN is projecting that Jeryd Mencken

has won the state of Wisconsin

You know, we've been reporting on that fire in the Milwaukee vote count center.

Nonetheless, our decision desk is confident in making this call

Jeryd Mencken has won the state of Wisconsin

and there goes the Blue Wall

That's ten electoral votes

That brings Mencken up to 246.

Okay, man. Okay. There's something there

Sordid back seat fuck job.

Oh, tell me more.

-He wants to keep up the momentum.   -Jeryd Mencken is now

24 electoral votes away from winning the presidency

Do you really want it?

Slovenia, Willa

I mean, I am torn, and he's very right wing

But...

Vienna for lunch, Venice for dinner..

And Dubrovnik for breakfast

My fellow Americans, it's becoming clear tonight that as far as we can tell

that as far as we can tell, Mr. Jeryd Mencken will likely be

the next president of the United States

Yes.   -And I, for one, wish him well

Connor was running for president?

For although I set out a clear and compelling path.

Okay. All right.   -America, in her divine wisdom

has chosen to take another.

Well, good luck

And I'd like to say, Tomy first running mate

who I will not dignify with a name-check

but had that woman not dropped out

and then had I not had to replace her with another figure

who turned out not to be able to bear the weight of public scrutiny

had I not been betrayed by those two... jackrabbits

who knows?

Politics of envy. Ugly game.

I happen to be a billionaire

Sorry.

But honestly, America, you flunked it

I guess you're gonna have to find some other poor mook's paps

to suck le on.   -Okay.

The corrupt bipartisan system zombie

All right.   -marches on.

And so, I call out to my friends tonight

to my people

I say, Con heads, I salute you.

And America, be afraid.

be warned..

for the Con heads are coming

Thank you. God bless America

ATN Decision Desk is now projecting Daniel Jimenez

has won the state of Michigan over Jeryd Mencken.

That's 15 electoral votes.

Our tally now i goes.

Are you ready for this?   -All right

262 for Mencken

-and 262 for Daniel Jimenez.   -A dead heat.

Polls will be closing soon in Alaska

the only state yet to be called other than Arizona

and its 11 electoral votes.

Let's may be go harass the decision desk.

Guys just a heads-up.

We hear, we are getting it from the campaign

said the data nerds are hearing that..

Well, Dar, you say it

So, Arizona is gonna go red.

All right, well, then that's... that would be it, right?

I mean, we're... we're kinda boxed in because of Wisconsin.

I mean, I... I don't feel comfortable calling it.

I mean, PGN is gonna be calling it, right, Tom?   -Yeah, I mean..

I mean, they're gonna call Arizona.

Because if we call it because of Wisconsin.

We... We called Wisconsin pending, so..

Yeah, we already called Wisconsin.

Okay? We can't uncall Wisconsin, can we?

That would make us all look pretty unprofessional?

So, Arizona, we're calling the election?

-Yeah.   -No, no.

-No? It's math, dude.   -No.

Tom, will you guys give us a minute, please?

-Fuck.   -Sure. Okay.

One minute. Be back in one minute, please.

What?

-That's it, that's it.   -I don't know, Rome

Like, may be... maybe we...

revisit Wisconsin.

Because, yeah, we, I mean, we... That was kinda.

Yeah... Okay, I get it.   -Right?

No, you're gonna, like, "big brother " it right now.

That's what you're gonna do?

No. Like what?

Like when, you know, if you want roast chicken

and I wanted steak, we always had chicken.

Because you... you'd freak out. you had tantrums, so they thought..

I would fucking tantrum because I never had fucking steak

Well, I think they got scared if

It's... You know, if you tantrum, then you'd think you'd won

so they couldn't let you have the steak.

I never won. It was always fucking chicken.

So, because we had so much chicken when we were kids

-I have to like the fascist?   -Yeah.

If we don't call it early and he wins anyway, which is perfectly possible,

which is perfectly possible, but without us tonight?

Think about that.

With FVA and Vera News backing him

we're left the most dickless eunuchs in cuck town

We call it? We call this?

-We push it.   -Yeah?

-Maybe it happens.   -Yeah

We give it to Mencken, Mencken blocks the deal.

He's not fuckin' wishy-washy. He's a guy.

I don't know, dude. I mean...

My kids, the whole thing...

" America."

Well, I mean, it is kind of a nice idea, you know?

All the different people together?

What?

All right, what... what would Dad do?

Oh, come on.   -I don't know.

-I don't actually know.   -Yes, you fucking do, man.

The guy in the pocket?

The guy that's gonna answer our calls?

The fucking guy printing US dollars.

This is all upside

Apart from the matter of him smashing the country to pieces.

Oh, God. Don't be such a fuckin'prissy.

Okay, may be... maybe we could deal with a dose of that, right?

Like, a nice little dose of the frighteners?

Wind shit back 20?

You know, one of those fucking guys pushed my daughter.

-She's okay?   -If we do this...

people... people are gonna say shit

Yeah. We'll be in the West Wing

Nothing matters, Ken. Nothing fucking matters.

Dad's dead and the country's just a big pussy waitin' to get fucked.

Fuckin' action, okay?

We can pay for any damages.

Let's just jam our fuckin' heads in the bosom of history and just.

Right? I mean...

Or we sit on our hands like a couple of damsels in distress

and, you know, watch our chance slip away

PGN has a major projection to announce

and that is that Jeryd Mencken will win Arizona.

So, he is the winner of 11 electoral votes in Arizona.

Can we talk for a minute?

Yeah, We're fucked, Ken. We're fucked

Because we called, it's fucked

I don't know what we should do.

I feel like my head is... Just, like, I can't... I can't..

get the scale of it, what this is.

I mean, we can recant. Yeah?

His team is being very direct

They will block Matsson's deal

Well, he says he will

We call it for him, that gives him legitimacy to declare

I mean, we're in bed with him, I think, yeah?

Yeah I.

I mean, it'll get ground out in the courts, whatever we say

Sure, right, but..

Yeah, look, shall we be... totally honest in here?

I have sometimes felt like I could do it

You know, like I should do it. Me.

Just me.

But I don't want that to be an end to the family thing, right?

I would just, I would like to be able to talk openly

about that feeling, may be

Sure. Yeah, no, I appreciate... I appreciate that.

Mencken is kinda Roman's guy, so that's complicated

Yeah. Right.

And, honestly, I feel... threatened, maybe, by their relationship and.

So, I want... a piece of me wants to not support that.

And that's may be in there, pulling away from Mencken.

But also, you're a good guy

Well... I don't know.

Sure. You are.   -Thank you.

No, essentially, you're... you're a good guy

But we... we all wanna stop Matsson, right?

That's the thing?

Yeah.

Good. Go on

Well, I think whatever..

Whatever advantage to us

as... as corporate players in the short term.

you know...

He's... Mencken's the nightmare

Yeah?

Plausible in a decadent era.

He says the bad shit, he believes the bad shit

We wouldn't actually be making him president

Oh, sure, we might not be able to crown him

but we can... we can stop him.

He gets momentum tonight, it makes it possible

He needs our call.

I don't think I'm a very good father

You are. You're

You're okay. You've tried.

That's all we can do.

-May be the poison drips through.   -No

No. And you know what?

I don't think even Dad would back him tonight

He basically picked him.

Sure, but we throw the papers and the whole thing in for him

and the n in a...in a month, a week from now

the courts go the other way?

It's... We're essentially done as a news organization

It's just hard to think we'd give it all away to Matsson

Could we try, could you try, once

direct to Nate to get something from them to block the deal?

Yeah

Yeah.   -Sure.

One of these?   -Yeah.

You're a good guy

Okay, yeah.

Yeah. I'm just calling with a quick... check-in inquiry

-Yeah.   -We're sorry

-The number you have reached -To be honest, I'm just wondering

-if Jimenez, I don't know..   -is not in service.

Please check the number or try your call again

So.

Yeah, Shiv's seeing what we can get from the Dems

Oh, get the fuck outta here. Why?

-We've got it.   -I really need to know what we're doing, guys

If we wanna stick with Wisconsin and call it for...

Hey, one moment. One moment, Tom. One moment

So?

Did you talk to him?

Yeah, I think there is... There's something there.

No, there's not.

Like? Like...

Like, they might be... I mean, they are willing to think.

Oh, they might be or maybe they are willing to think maybe

-That sounds like horseshit.   -No, Rome.

They're just not so direct.

Yeah? I... I think we can probably get them to stop it

Oh, they probably... Yeah, go. Sorry, no

Game over. Bullshit

No. We have to call it. Mencken is rock solid

Roman, even Dad, even... even Dad in this situation

would respect the process

No, Dad did whatever the fuck he wanted

He... One fax, he took out a government.

He did, the " Fuck Lyle." Send

And that was it. That's all it took

Fucking Canada, here, he didn't give a shit.

He liked stability, Rome.

He pushed, but he didn't want shit to unravel.

He... He helped end.... I mean, he ended wars.

He ended wars that he started. He did whatever the fuck he wanted.

What did they say, Shiv? Like, what did Nate actually say?

He said they would talk and that they could see the arguments

and I... I think it's encouraging.

You felt like it was encouraging? ?   -It was. It was encouraging

It was a feeling. I got something real.

This is fucking pointless. What a waste of time.

What are you doing?   -I'm gonna call

I... I'm just gonna... I'm gonna be very direct.

We just... We just need a little bit more.

Don't call him.   -Why?

They're... They're busy.

Can't have uncertainty. Can't. Fucking market.

The chaos of trying to rerun an entire election

could just send the country into meltdown, you know?

Okay, bad faith argument.   -I'm telling you.

I'm just telling you, you can not have uncertainty.

-China is coming.   -China is coming?

China's coming.   --China's already been. Next.

It's not like the fucking final, final, anyway

Okay, there's the court shit and it all kinda just fuzz es along, you know?

It's just waste of fucking time.

That we don't have, by the way

Hey, Greg, can I ask you a question?

What's up?

Do you know if there's something going on..

What else Nate and Gil and fucking Jimenez offer you?

Unlimited social security spending with this one weird trick?

How was that call?

What'd you get? Whole bunch of not much?

Really?

What?

" I think you're a good guy?'

Well, I found it hard to get Nate so I summarized some impressions.

Oh, right... Smart. Really good, Shiv

But you lied. Right?

She didn't get anything from Nate.   -Really?

She didn't speak to Nate. And she's in with Matsson

Sorry, what?   -No. I.. No.

No, I... I did what we all agreed to.

that I got close to him so that I could help for the

Shiv's fucking us, right?

Right, Shivy?

No.

I...was...

I fucking asked you some real questions, Shiv

I wondered why you looked like a goose

trying to shit a house brick, you piece of dirt

Okay, what, you got yourself a little fuck in'side deal here?

No, no. I have some options.

I... I was... I was going through with the plan

-and then you two...   -Well, Mencken. Mencken, right?

-Mencken.   -No. What?

Tom!

No, you even wanted to push us, us out of the fucking nest.

Sure, sis. Sure...   -Please.

Ken, aside from all this, this is not the right thing.

Aside from the fact that you lied to us

and that doing what you want precisely plays into your own interests, yeah?

Oh, and this doesn't? Yeah?

Ken, please, come on. Come on, who are we?

Oh, well, " Will no one think of the children?'

You know what? No, I'm not gonna let this happen.

There comes a time when you have to stand

" There comes a time.

Seriously. This is real. Okay?

I have a concern for the state of the republic

and... and pluralism and..

and the future of this country.   -So boring

And it... And it is real.   -You're such a bore, Shiv. Jesus.

Fuck you. Ken?

He's right.

Yeah. You're boring

And you don't have a pass for in here.

Okay, well, fine. You know what? I'm... I'm... May be I'll go...

I'l...'ll go public.

yeah?   -I'll go to the papers and people

and tell 'em what you're actually fucking doing, which is..

If you're just gonna be hysterical

we're gonna have to, you know, ask you to leave

-Fuck you.   -People are trying to do some serious work in here

Fuck you. This is about the future of the country

No, I think it's because you broke up with your boyfriend

Jesus, you're a prick.   -Hello

So, call it. You can call it.   -No

-We're calling it?   -Yeah, we called Wisconsin

now we're gonna call Arizona, so we call the election.

We call the election?   -Call it.

-Call it.   -No. No, Tom.

No. You're making a terrible mistake. Please don't

Hey, guys, it's not my call.

It's not my call.

Okay. It's our call.   -It's your call. It's up to you.

If you say so.   -I say so.

Fucking Pontius Pilate.

No one cares. No one... no one cares.

Hey, yeah.   -Hey. Tell'em I'm coming down.

Yes. We're gonna call it.

-Yeah, we're calling for Mencken.   -All right.

Okay, tell'em I'm coming. All right

-Okay.   -Great work, Tom.

Thank you.

Good stuff. Great night.

Fuck.

You okay?

Yeah. I.

I have to go... tell them.

I think, we're callin'it. For Mencken.

Yeah.

-So, I should... I should go.   -Right. Yeah.

I'll get in trouble if I don't go.

Okay, dude. I mean..

Yeah, I mean, it's not really my choice, right?

Sure. I mean, right. Yeah

Yeah, I'm just... I'm pressing the button.

Or I'm not even pressing the button, I'm...

I'm asking them to prepare to press the button.

Right, and all that does is just, like, launch a nuclear attack.

So...

It's not gonna change anything if I don't go, so..

Couple minutes. So, I mean..

Right, right.

Realistically.

-Crazy.   -Yeah.

Crazy

Crazy one.

So, Tom just told me.

Everybody, calling it for Mencken

He's calling it for Mencken.

-Everybody.   -What he said, yeah?

I just said.   -I'm... I'm calling it for Mencken

Okay.

Okay.   -Okay. Yeah.

Okay. Well, then, Dave?

Okay. Lydia, get me " Mencken Wins."

Get the ticker going on ATN Citizens.

Let the people know two mins and ATN is gonna call it.

We are gonna make this call now.

The ATN Decision Desk has looked at the numbers..

and is ready to declare Arizona for Jeryd Mencken

This means that Mencken will be the next president of the United States

winning the most unreal, surreal election

we have ever seen in this country

his candidacy starting in Virginia only six months ago

against a dozen other Republican candidates

in the wake of the President saying he wasn't going to run for re-election

What started off as an unlikely impossibility

now a reality, it is Mencken

Well...

It's now clear I have won sufficient electoral votes..

to be declared the next president of the United States

and I find the responsibility awesome.

Now, I know there are some who feel there is something left to contest

But votes have been cast, votes have been tallied

On another day, in another time

they might have fallen in another fashion

The election has been called for me by an authority of known integrity

Maybe we should get, like, a history guy?

You know, like a brain, like a real brainiac

to say why this sort of thing has happened in the past

and that it'll all be fine?

To my critics

I am not a demagogue

I am a defender of democracy.

But democracy, it has this tendency that we have to beware

to become mere transaction.

I give you this. You give me that

I come begging for your vote.

Welfare checkbook out.

Crowning the welfare kings and queens

until everyone has become a little tyrant

crowned by the state

The model that I follow isn't from the scorched marketplace

where cunning men haggle for the best price

That's not me.

The democracy I believe in

is where a leader emerged from the people

willed, almost, into being

brought forth by the great sweetness of the virtue

of the combined wisdom of the good people of this republic

Don't we long, sometimes

for something clean

once in this polluted land?

That's what I hope to bring.

Not something grubby with compromise

Something clean and true and refreshing

He's a guy we can do business with.

-Yeah.   -Something proud and pure

-He'll play ball.   -Thank you very much

You should hear him talk semiconductors.

-And God bless the United States of America.   -The market's holding the leash

We just made a night of good TV.

That's what we've done. Nothing happens

Things do happen, Rome

President calling.

Hocus-POTUS. Sitting in the POTUS position. What's up?

Hey, man. I... Look, no time, but just, just thanks, yeah?

You and me, man. We'll go far.

Over the road and into the bar.

an election unlike anything we've ever seen

followed by a speech for the ages.

The legal process is gonna be lengthy.

When do you think it'll all be over?

This... this could be going on for the next three months.

Hey, Tom? Your phone.

It's... It's red hot, Tom. It..

A lot of very important people wanna scream at you.

This is a little pointed

..by ATN boss Tom Wambsgans

Darwin wants to know when to do his caveats

Is there time for him to do it?

No.

So, it's unclear whether Wa mbs gans'alleged action

-was an error of judgment -Hello?

or there was a personal -No

or political dimension to the decision.

He is, of course, known to be an associate of Jeryd Mencken.

-What's going on?   -Those funky numbers?

I'm sending you words, yeah?

Let's get 'em out in the next 24. Lot of fuckin' news.

You guys are crazy.

Yeah, it's more than just fucking crazy, Lukas

No, but this is crazy.

Yeah, well, we're gonna do a number on 'em.

We're gonna fuck them so hard we're gonna fix this, yeah?

Fuck

Can I come see the kids?

They're asleep, Ken.   -Just... I know. Yeah

Well, I can... I can wait up for them

I should be asleep, but I... I can't

Okay, I'll... I'll see you tomorrow.

I'll see you at the funeral. Okay?

Some people just can't cut a deal, Fikret

