
= Lesson 9
:toc:

---


== Section 1

Dialogue 1:
—I'm going to clean the blackboard.
—But you can't do that.
—Why can't I?
—We haven't got a duster.
Dialogue 2:
—I'm going to drink some of this milk.
—But you mustn't.
—Why not?
—Because it's sour.
Dialogue 3:
—Excuse me, Madam, did you drop your glove?
—I beg your pardon?
—I said "Did you drop your glove".
—Oh, yes, I did. Thank you so much.
—Not at all. It's a pleasure.
Dialogue 4:
—Are you a millionaire, Peter?
—Of course I’m not. Why do you ask, Roberto?
—I only wanted to practice my English.
—Oh, I see. You want to make use of me.
Dialogue 5:
—Where have you been?
—To the cinema.
—Who did you go with?
—I went with Jone Judge.
Dialogue 6:
—What can I do for you?
—I have damaged my wrist, doctor.
—How did you do that?
—I fell on it while I was playing tennis.
Dialogue 7:
—What's wrong?
—I have a pain in my chest.
—Why not go and see your doctor?
—Yes. That's a good idea. I will.
Dialogue 8:
—Excuse me, but is it seven o’clock yet?
—I’m sorry, but I haven’t a watch. Try the lady over there. She will know.
—Thank you. I will.
Dialogue 9:
—What are you going to do this evening?
—I'm going to p1ay cards.
—Are you going to play cards tomorrow evening, too?
—No. I'm going to make a new dress.
Dialogue 10:
—Do you like boiled eggs?
—Yes. I love them. Thank you.
—Do you prefer hard ones or soft ones?
—I really don't mind. Thank you.
Dialogue 11:
—Did you buy anything when you were in the town?
—Yes. I bought a blouse.
—What's it like?
—It's a blue one with a high neck.
Dialogue 12:
—Did you walk to the match?
—No. I went by car.
—Did John go by car, too?
—No. He cycled.
Dialogue 13:
—Hello, and how did you spend the holiday?
—I played tennis till lunch time.
—What did you do after lunch?
—I went for a swim with John.
Dialogue 14:
—Hello, why aren't you playing tennis?
—I haven't brought my racket.
—You can borrow mine, if you like.
—Oh, thank you. That's very kind of you.
Dialogue 15:
—What are those shirts made of?
—They are made of cotton.
—Are shirts always made of cotton?
—No. They are sometimes made of wool or nylon.
Section 2
A. An Invitation to a Volleyball Match.
Female: I've got two tickets for a volleyball match this evening. Why don't you come?
Male: Uh ... no, thanks. I ... I'm not very interested in volleyball.
Female: Oh, why not? Have you ever seen it played?
Male: No, I haven't, but I really don't th...
Female: That's what I thought. You don't know what you're missing.
Male: Don't I? Why?
Female: Because it's very fast, with lots of action.
Male: Really? Who's playing?
Female: Two of the best women's teams in the world, one from Finland and the other from
Belgium.
Male: Hmm. It sounds exciting.
Female: Yes, it is! Very!
Male: Hmm. Well, perhaps I'll come after all.
Female: Good! Now ... uh ... could you ... uh ... could I have five pounds, please?
Male: Five pounds? What for?
Female: Your ticket, of course. I bought two of them in advance, hoping I'd persuade you
to come with me.
Male: Oh ... uh ... You know, I've just remembered something.
Female: What?
Male: I've got to see some friends this evening.
Female: Oh ... I see ... I mean ... you won't be coming, after all, then?
Male: No, not unless...
Female: Unless what?
Male: Perhaps you could let me have the ticket for a bit less? Let's say three pounds.
Female: But you said you had to meet some friends!
Male: Come on. I was only joking. Here's your five pounds. Of course I'll come.
B. Telephone Conversation.
(sound of telephone ringing)
Tom: Tom Haley speaking.
Philip: Hello, Tom. It's Philip. I waited for a phone call from you but I can't wait any longer.
Tell me about your first week.
Tom: Hmmmmmm. It wasn't easy.
Philip: Wasn't it? Why? What did you have to do?
Tom: On Monday and Tuesday, I lifted heavy boxes. On Wednesday, I put hundreds of
bottles and tins and packets on shelves.
Philip: Was it boring?
Tom: Yes, very boring. And I dropped a lot of boxes.
Philip: Did you break anything?
Tom: Oh, just a few jars of jam and a lot of bottles of tomato juice.
Philip: Ugh. What a mess. So tell me about Thursday.
Tom: I'm afraid I was two hours late ... and the supervisor was really angry. Then I put
price labels on bottles and tins and packets. Very confusing.
Philip: Did you put the right labels on them?
Tom: Not always. I made one or two mistakes.
Philip: Only one or two? What did you do on Friday and Saturday?
Tom: I didn't do very much. I was fed up. The supermarket was open until 9 pm. They
wanted me to work overtime but I went home at six.
Philip: I see. Have you still got a job?
Tom: I don't know. I have to see the supervisor tomorrow.
Philip: Well, you'd better get up early. Good luck!
C. Monologues:
1. I hate the stairs. Sometimes the lift isn't working and you have to use the stairs. I can't
get up the stairs by myself; it's my back, you see. Jane, my friend, lives on the ground floor,
that's much easier. Nearly every morning I stop there for a cup of tea before I come back
up here.
2. I don't mind living in a tall building. I don't mind the stairs. I quite like the exercise. Of
course, it's difficult for older people but I don't mind if you live on the top floor, like Mrs.
Green, it's not easy. And I don't like the ground floor; I don't think it's safe. But I like my
place. I've got three floors below me and three above, I feel very safe. My Mum lives here
too, on the ground floor.
3. Alice comes every morning. Well, nearly every morning. She's not young any more, you
see, she's seventy-eight next birthday, and it's difficult for her to walk up to the top floor. I
can't go up; I can't move. It's my leg; I've got a bad leg. Carol comes to see me sometimes.
She lives here too, you know, in another flat. She's my daughter.
Section 3
Dictation.
Dictation 1:
We are going to Scotland for our holiday. We are leaving early on Saturday morning
and I hope we will get to York about eleven o'clock. We are spending the night in York,
then on Sunday we are driving up to Scotland. We are going to stay at a lovely little hotel
near a lake. Of course we will probably get some rain, but I am sure we will have a
fantastic holiday.
Dictation 2:
People often ask me for my telephone number. But I have not got a telephone, so I
tell them to ring me at work. Why don't I have a telephone? I think the telephone is
expensive and I prefer to write a letter. There aren't many people I want to speak to in the
evening and I do not want to speak to anybody at breakfast time. When I want to use the
telephone in the evening, I can always use the box at the end of the road.
Section 4
Song:
Maybe it’s because I’m a Londoner
That I love London so
Maybe it’s because I’m a Londoner
That I think of her wherever I go.
I get a funny feeling inside of me
Just walking up and down.
Maybe it’s because I’m a Londoner
That I love London town.

---
