
= CHAPTER 1 - RUSSIA
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义












'''


== pure


=== 俄罗斯扩张史

Russia as a concept dates back to the ninth century and a loose federation of East Slavic tribes known as Kievan Rus’, which was based in Kiev and other towns along the Dnieper River, in what is now Ukraine. The Mongols, expanding their empire, continually attacked the region from the south and east, eventually overrunning it in the thirteenth century. The fledgling Russia then relocated north-east in and around the city of Moscow. This early Russia, known as the Grand Principality of Muscovy, was indefensible. There were no mountains, no deserts and few rivers. In all directions lay flatland, and across the steppe to the south and east were the Mongols. The invader could advance at a place of his choosing, and there were few natural defensive positions to occupy.

[.my2]
**俄罗斯的概念可以追溯到九世纪，当时东斯拉夫部落组成了一个松散的联盟，称为"基辅罗斯"，其中心位于基辅, 以及第聂伯河沿岸的其他城镇，即今天的乌克兰境内。**蒙古人不断扩张帝国版图，从南部和东部入侵该地区，最终在十三世纪将其征服。 +
**新生的俄罗斯, 随后向东北方向迁徙，以莫斯科城及其周边地区为中心。**这个早期的俄罗斯，即"莫斯科大公国"，防御能力极差。这里没有山脉，没有沙漠，河流也寥寥无几。四面八方都是平原，而南部和东部的草原上则是蒙古人的领地。入侵者可以随意选择进攻地点，几乎没有天然的防御工事可供占据。

Enter Ivan the Terrible, the first Tsar. He put into practice the concept of attack as defence – i.e., beginning your expansion by consolidating at home and then moving outwards.

[.my2]
**伊凡雷帝，第一位沙皇，**登基了。他将“进攻即防守”的理念付诸实践——即先巩固国内，再向外扩张。

The fledgling Russia had begun a moderate expansion under Ivan’s grandfather, Ivan the Great, but that expansion accelerated after the younger Ivan came to power in 1533. It encroached east on the Urals, south to the Caspian Sea and north towards the Arctic Circle. It gained access to the Caspian, and later the Black Sea, thus taking advantage of the Caucasus Mountains as a partial barrier between it and the Mongols. A military base was built in Chechnya to deter any would-be attackers, be they the Mongol Golden Hordes, the Ottoman Empire or the Persians.

[.my2]
新生的俄罗斯, 在伊凡的祖父"伊凡大帝"统治时期, 就开始了适度的扩张，但自小伊凡于 1533 年继位后，扩张速度加快。俄罗斯向东推进至乌拉尔山脉，向南抵达里海，向北则到达北极圈。**它获得了里海的出口，后来又获得了黑海的出口，**从而利用高加索山脉, 作为其与蒙古人之间的部分屏障。为了威慑任何潜在的侵略者，无论是蒙古金帐汗国、奥斯曼帝国还是波斯人，俄罗斯还在车臣建立了一个军事基地。

There were setbacks, but over the next century Russia would push past the Urals and edge into Siberia, eventually incorporating all the land to the Pacific coast far to the east.

[.my2]
虽然遭遇过挫折，但**在接下来的一个世纪里，俄罗斯将越过乌拉尔山脉，进军西伯利亚，**最终吞并了远在东部的太平洋沿岸的所有土地。

Now the Russians had a partial buffer zone and a hinterland – strategic depth – somewhere to fall back to in the case of invasion. No one was going to attack them in force from the Arctic Sea, nor fight their way over the Urals to get to them. Their land was becoming what we know now as Russia, and to get to it from the south or south-east you had to have a huge army, a very long supply line, and fight your way past defensive positions.

[.my2]
**现在，俄罗斯人拥有了一部分缓冲区和腹地——战略纵深——一旦遭到入侵，便可退守。**没有人会从北冰洋大规模进攻他们，也没有人会翻越"乌拉尔山脉"抵达那里。他们的土地正在发展成为我们今天所知的俄罗斯，而要从南部或东南部攻入这片土地，就必须拥有一支庞大的军队、一条漫长的补给线，并且还要突破他们的防御阵地。

In the eighteenth century, Russia – under Peter the Great, who founded the Russian Empire in 1721, and then Empress Catherine the Great – looked westward, expanding the Empire to become one of the great powers of Europe, driven chiefly by trade and nationalism. A more secure and powerful Russia was now able to occupy Ukraine and reach the Carpathian Mountains. It took over most of what we now know as the Baltic States – Lithuania, Latvia and Estonia. Thus it was protected from any incursion via land that way, or from the Baltic Sea.

[.my2]
**十八世纪，在彼得大帝（他于1721年建立了俄罗斯帝国）, 和后来的叶卡捷琳娜大帝的统治下，俄罗斯向西扩张，**凭借"贸易"和"民族主义"的双重驱动，帝国迅速崛起，成为欧洲列强之一。一个更加安全强大的俄罗斯得以占领乌克兰，并抵达喀尔巴阡山脉。它吞并了如今波罗的海三国——立陶宛、拉脱维亚和爱沙尼亚——的大部分领土。由此，俄罗斯得以免受来自陆路和波罗的海的入侵。**(俄罗斯占领的面积越大, 它要保卫的边缘地带就越多, 它就越有对外侵略性.) **

From the Grand Principality of Muscovy, through Peter the Great, Stalin and now Putin, each Russian leader has been confronted by the same problems. It doesn’t matter if the ideology of those in control is tsarist, Communist or crony capitalist – the ports still freeze, and the North European Plain is still flat.

[.my2]
从莫斯科大公国到彼得大帝、斯大林，再到如今的普京，**每一位俄罗斯领导人都面临着同样的问题。**无论掌权者的意识形态是沙皇主义、共产主义, 还是裙带资本主义，都无关紧要——**港口依然会结冰，北欧平原依然平坦。**

A Russian island in the Bering Strait is two and a half miles from an American island in the Strait, Little Diomede Island, and can be seen with the naked eye. You can indeed see Russia from America.

[.my2]
白令海峡中的一个俄罗斯岛屿, 距离海峡中的美国岛屿——小迪奥米德岛——只有两英里半，肉眼可见。的确，从美国可以看到俄罗斯。

'''

=== 俄罗斯的担忧




==== 从"北欧平原(波德平原?)"进入俄罗斯

To the west of the Ural Mountains is European Russia. To their east is Siberia, stretching all the way to the Bering Sea and the Pacific Ocean.

[.my2]
乌拉尔山脉以西是俄罗斯欧洲部分，以东是西伯利亚，一直延伸到白令海和太平洋。

When Vladimir Putin isn’t thinking about God, and mountains, he’s thinking about pizza. In particular, the shape of a slice of pizza – a wedge.

[.my2]
当弗拉基米尔·普京不在思考上帝和山脉时，他就在思考披萨。特别是披萨片的形状——楔形。

The thin end of this wedge is Poland. Here, the vast North European Plain stretching from France to the Urals (which extend 1,000 miles south to north, forming a natural boundary between Europe and Asia) is only 300 miles wide. It runs from the Baltic Sea in the north to the Carpathian Mountains in the south. The North European Plain encompasses all of western and northern France, Belgium, the Netherlands, northern Germany and nearly all of Poland.

[.my2]
**这块楔形地带的窄端是波兰。从法国延伸到乌拉尔山脉（南北绵延1000英里，构成欧亚大陆的天然分界线）的广袤北欧平原，在这里仅有300英里宽。**它北起波罗的海，南至喀尔巴阡山脉。北欧平原涵盖了法国西部和北部、比利时、荷兰、德国北部以及几乎整个波兰。

From a Russian perspective this is a double-edged sword. Poland represents a relatively narrow corridor into which Russia could drive its armed forces if necessary and thus prevent an enemy from advancing towards Moscow. But from this point the wedge begins to broaden; by the time you get to Russia’s borders it is over 2,000 miles wide, and is flat all the way to Moscow and beyond. Even with a large army you would be hard-pressed to defend in strength along this line. However, Russia has never been conquered from this direction partially due to its strategic depth. By the time an army approaches Moscow it already has unsustainably long supply lines, a mistake that Napoleon made in 1812, and that Hitler repeated in 1941.

[.my2]
从俄罗斯的角度来看，这是一把双刃剑。**波兰是一条相对狭窄的通道，必要时俄罗斯可以将军队部署到这条通道内，从而阻止敌人向莫斯科推进。但从这里开始，楔形地带开始扩大；到俄罗斯边境时，宽度超过2000英里，而且一路平坦，直达莫斯科及更远的地方。即使拥有庞大的军队，沿着这条线也很难进行有效的防御。然而，俄罗斯从未被从这个方向征服，部分原因在于其战略纵深。当一支军队逼近莫斯科时，其补给线已经长得难以维持，**这是拿破仑在1812年犯下的错误，也是希特勒在1941年重蹈覆辙的。

You might think that no one is intent on invading Russia, but that is not how the Russians see it, and with good reason. In the past 500 years they have been invaded several times from the west. The Poles came across the North European Plain in 1605, followed by the Swedes under Charles XII in 1708, the French under Napoleon in 1812, and the Germans twice, in both world wars, in 1914 and 1941. Looking at it another way, if you count from Napoleon’s invasion of 1812, but this time include the Crimean War of 1853–6 and the two world wars up to 1945, then the Russians were fighting on average in or around the North European Plain once every thirty-three years.

[.my2]
你或许认为没人想入侵俄罗斯，但俄罗斯人并不这么认为，而且他们有充分的理由。过去五百年间，他们曾多次遭受来自西方的入侵: +
1605年，波兰人横穿北欧平原； +
1708年，查理十二世率领的瑞典人入侵； +
1812年，拿破仑率领的法国人入侵； +
1914年和1941年，德国人在两次世界大战中入侵俄罗斯。 +
换个角度来看，**如果从1812年拿破仑入侵算起，**但这次把1853-1856年的克里米亚战争, 以及两次世界大战（直至1945年）都算进去，**那么俄罗斯人平均每三十三年, 就要在北欧平原及其周边地区作战一次。**

President Putin is no fan of the last Soviet President, Mikhail Gorbachev. He blames him for undermining Russian security and has referred to the break-up of the former Soviet Union during the 1990s as ‘a major geopolitical disaster of the century’.

[.my2]
普京总统并不喜欢苏联最后一任总统米哈伊尔·戈尔巴乔夫。**他指责戈尔巴乔夫破坏了俄罗斯的安全，**并将上世纪90年代苏联的解体, 称为“本世纪最大的地缘政治灾难”。

Since then the Russians have watched anxiously as NATO has crept steadily closer, incorporating countries which Russia claims it was promised would not be joining: the Czech Republic, Hungary and Poland in 1999, Bulgaria, Estonia, Latvia, Lithuania, Romania and Slovakia in 2004 and Albania in 2009. NATO says no such assurances were given.

[.my2]
从那时起，俄罗斯就一直焦虑地关注着北约稳步扩张，吸纳了俄罗斯声称"他们曾被承诺不会加入北约"的国家： 1999 年的捷克、匈牙利和波兰，2004 年的保加利亚、爱沙尼亚、拉脱维亚、立陶宛、罗马尼亚和斯洛伐克，以及 2009 年的阿尔巴尼亚。但北约则表示，他们从未做出过此类保证。

Russia, like all great powers, is thinking in terms of the next 100 years and understands that in that time anything could happen. A century ago, who could have guessed that American armed forces would be stationed a few hundred miles from Moscow in Poland and the Baltic States? By 2004, just fifteen years from 1989, every single former Warsaw Pact state bar Russia was in NATO or the European Union.

[.my2]
**俄罗斯和所有大国一样，着眼于未来一百年，并且明白在这百年间任何事情都可能发生。一个世纪前，谁又能预料到美军会驻扎在距离莫斯科几百英里的波兰和波罗的海国家呢？**到2004年，也就是1989年之后仅仅十五年，除俄罗斯之外的所有前华沙条约成员国, 都加入了北约或欧盟。


''' 

==== 从”黑海沿岸的平原”(摩尔多瓦), 进入俄罗斯

This brings us to another gap in the wall and another region Moscow views as a potential buffer state. Firmly in the Kremlin’s sights is Moldova.

[.my2]
这就引出了柏林墙上的另一个缺口，以及**莫斯科视为潜在缓冲国的另一个地区。克里姆林宫的目光牢牢锁定在摩尔多瓦。**

Why would the Russians want Moldova? Because as the Carpathian Mountains curve round south-west to become the Transylvanian Alps, to the south-east is a plain leading down to the Black Sea. That plain can also be thought of as a flat corridor into Russia; and, just as the Russians would prefer to control the North European Plain at its narrow point in Poland, so they would like to control the plain by the Black Sea – also known as Moldova – in the region formerly known as Bessarabia.

[.my2]
**俄罗斯人为何想要摩尔多瓦？因为"喀尔巴阡山脉"向西南弯曲，最终汇入特兰西瓦尼亚阿尔卑斯山脉，而东南方向则是一片通往"黑海"的平原。这片平原也可以被视为通往俄罗斯的一条平坦走廊；正如俄罗斯人希望控制"北欧平原"在波兰境内的狭窄地带一样，他们也希望控制"黑海沿岸的平原"——也就是摩尔多瓦**——这片区域以前被称为"比萨拉比亚"。

After the Crimean War (fought between Russia and Western European allies to protect Ottoman Turkey from Russia), the 1856 Treaty of Paris returned parts of Bessarabia to Moldova, thus cutting Russia off from the River Danube. It took Russia almost a century to regain access to it, but with the collapse of the USSR, once more Russia had to retreat eastward.

[.my2]
**克里米亚战争（俄罗斯及其西欧盟国之间的战争, 后者的目的是为保护奥斯曼土耳其免受俄罗斯侵略）结束后，1856年的《巴黎条约》, 将"比萨拉比亚"的部分地区, 归还给摩尔多瓦，从而切断了俄罗斯与多瑙河的联系。俄罗斯花了近一个世纪, 才重新获得多瑙河的通行权，**但随着苏联解体，俄罗斯不得不再次向东撤退。

Moldova presents a different problem for all sides. An attack on the country by Russia would necessitate crossing through Ukraine, over the Dnieper River and then over another sovereign border into Moldova. It could be done – at the cost of significant loss of life and by using Odessa as a staging post – but there would no deniability. Although it might not trigger war with NATO (Moldova is not a member), it would provoke sanctions against Moscow at a level hitherto unseen, and confirm what this writer believes to already be the case – that the cooling relationship between Russia and the West is already the New Cold War.

[.my2]
对各方而言，摩尔多瓦都是一个不同的问题。俄罗斯若要攻击摩尔多瓦，就必须先穿越乌克兰，跨过第聂伯河，再越过另一条主权边界, 进入摩尔多瓦。这样做并非不可能—— 但代价是惨重的人员伤亡，并且需要以"敖德萨"为中转站 ——但一旦发动攻击，将无法否认。虽然这可能不会引发与北约的战争（摩尔多瓦并非北约成员国），但却会招致前所未有的对莫斯科制裁，并印证笔者一直以来的观点——俄罗斯与西方关系的降温, 已然演变为新冷战。

However, in effect the Russians do already control part of Moldova – a region called Transnistria, part of Moldova east of the Dniester River which borders Ukraine. Stalin, in his wisdom, settled large numbers of Russians there, just as he had in Crimea after deporting much of the Tatar population.

[.my2]
然而，**事实上，俄罗斯人已经控制了摩尔多瓦的部分地区**——德涅斯特河以东、与乌克兰接壤的"德涅斯特河"沿岸地区。**斯大林聪明地在那里安置了大量俄罗斯人(埋雷)，就像他在克里米亚驱逐了大量鞑靼人之后所做的那样。**

Modern Transnistria is now at least 50 percent Russian- or Ukrainian-speaking, and that part of the population is pro-Russian. When Moldova became independent in 1991 the Russian-speaking population rebelled and, after a brief period of fighting, declared a breakaway Republic of Transnistria. It helped that Russia had soldiers stationed there, and it retains a force of 2,000 troops to this day.

[.my2]
如今，**德涅斯特河沿岸地区, 至少有 50%的人口讲俄语或乌克兰语，而且这部分人口倾向于亲俄。 **1991 年摩尔多瓦独立后，讲俄语的人口发动叛乱，经过短暂的战斗后，宣布成立"德涅斯特河沿岸共和国"。俄罗斯当时在该地区驻扎军队，这对其成立起到了推动作用，而且至今俄罗斯仍在那里驻扎着 2000 名士兵。

A number of countries that were once members of the Soviet Union aspire to closer ties with Europe, but with certain regions, such as Transnistria in Moldova, remaining heavily pro-Russian, there is potential for future conflict.

[.my2]
许多曾经是苏联成员国的国家, 都渴望与欧洲建立更紧密的联系，但由于某些地区，例如**摩尔多瓦的德涅斯特河沿岸地区，仍然强烈亲俄，**因此未来存在发生冲突的可能性。

A Russian military advance in Moldova is unlikely, but the Kremlin can and does use its economic muscle and the volatile situation in Transnistria to try and influence the Moldovan government not to join the EU or NATO.

[.my2]
俄罗斯不太可能在摩尔多瓦发动军事进攻，但克里姆林宫可以而且确实利用其经济实力 和德涅斯特河沿岸地区的动荡局势，试图影响摩尔多瓦政府，使其不加入欧盟或北约。

Moldova is reliant on Russia for its energy needs, its crops go eastward and Russian imports of the excellent Moldovan wine tend to rise or fall according to the state of the relationship between the two countries.

[.my2]
摩尔多瓦的能源需求, 依赖俄罗斯，其农作物销往东方. 俄罗斯进口的优质摩尔多瓦葡萄酒的数量, 往往会随着两国关系的兴衰而增减。


''' 

==== 缺乏不冻港, 和直接的出海口

The ports on the Arctic, such as Murmansk, freeze for several months each year: Vladivostok, the largest Russian port on the Pacific Ocean, is ice-locked for about four months and is enclosed by the Sea of Japan, which is dominated by the Japanese. This does not just halt the flow of trade; it prevents the Russian fleet from operating as a global power. In addition, water-borne transport is much cheaper than land or airborne routes.

[.my2]
北极港口，例如摩尔曼斯克，每年都会结冰数月； +
俄罗斯在太平洋沿岸最大的港口"符拉迪沃斯托克"，每年约有四个月被冰封，并且被日本控制的日本海所包围。 +
**这不仅阻碍了贸易流通，也使俄罗斯舰队无法发挥全球力量的作用。此外，水路运输比陆路或空运便宜得多。**

This lack of a warm-water port with direct access to the oceans has always been Russia’s Achilles heel, as strategically important to it as the North European Plain. Russia is at a geographical disadvantage, saved from being a much weaker power only because of its oil and gas. No wonder, in his will of 1725, that Peter the Great advised his descendants to ‘approach as near as possible to Constantinople and India. Whoever governs there will be the true sovereign of the world. Consequently, excite continual wars, not only in Turkey, but in Persia … Penetrate as far as the Persian Gulf, advance as far as India.’

[.my2]
**缺乏直通海洋的"不冻港", 一直是俄罗斯的阿喀琉斯之踵，**其战略重要性堪比"北欧平原"。俄罗斯地理位置不利，仅凭石油和天然气资源才勉强维持至今。难怪彼得大帝在 1725 年的遗嘱中嘱咐后人“**尽可能靠近君士坦丁堡和印度。谁能统治那里，谁就是真正的世界君主。因此，要不断挑起战争，不仅在土耳其，还要在波斯……深入波斯湾，进军印度。**”

Crucially, the invasion of Afghanistan also gave hope to the great Russian dream of its army being able to ‘wash their boots in the warm waters of the Indian ocean’, in the words of the ultra-nationalistic Russian politician Vladimir Zhirinovsky, and thus achieve what it never had: a warm-water port where the water does not freeze in winter, with free access to the world’s major trading routes.

[.my2]
至关重要的是，入侵阿富汗， 也让俄罗斯的伟大梦想燃起了希望 (但阿富汗并不靠海呀). 正如俄罗斯极端民族主义政治家“弗拉基米尔·日里诺夫斯基”所言，**俄罗斯军队能够“在温暖的印度洋海水中洗靴子”，从而实现其从未拥有过的目标：一个冬季不结冰的"不冻港"，可以自由通达世界主要贸易航线。****  +

'''

==== -> 出黑海, 进入地中海, 或印度洋

Crimea was part of Russia for two centuries before being transferred to the Soviet Republic of Ukraine in 1954 by President Khrushchev at a time when it was envisaged that Soviet man would live forever and so be controlled by Moscow forever. Now that Ukraine was no longer Soviet, or even pro-Russian, Putin knew the situation had to change. Did the Western diplomats know? If they didn’t, then they were unaware of Rule A, Lesson One, in ‘Diplomacy for Beginners’: when faced with what is considered an existential threat, a great power will use force.

[.my2]
克里米亚曾作为是俄罗斯的一部分, 长达两个世纪，直到1954年赫鲁晓夫总统将其划归苏联乌克兰共和国。当时人们认为苏联人将永存，因此也将永远受莫斯科控制。如今，乌克兰不再是苏联的一部分，甚至不再亲俄，普京深知局势必须改变。西方外交官们是否了解这一点？如果他们不了解，那么他们就忽略了《外交入门》第一课的第一条原则：当面临被视为生存威胁的挑战时，大国会诉诸武力。

Sevastopol is Russia’s only true major warm-water port. However, access out of the Black Sea into the Mediterranean is restricted by the Montreux Convention of 1936, which gave Turkey – now a NATO member – control of the Bosporus. Russian naval ships do transit the strait, but in limited numbers, and this would not be permitted in the event of conflict.  +
Even after crossing the Bosporus the Russians need to navigate the Aegean Sea before accessing the Mediterranean, and would still have either to cross the Gibraltar Straits to gain access to the Atlantic Ocean, or be allowed down the Suez Canal to reach the Indian Ocean.

[.my2]
**"塞瓦斯托波尔"(在克里米亚半岛上)是俄罗斯唯一真正的大型不冻港。然而，由于1936年《蒙特勒条约》的限制，俄罗斯从"黑海"进入"地中海"的通道受到限制。该条约将"博斯普鲁斯海峡"的控制权, 授予了土耳其 ——现为北约成员国。俄罗斯海军舰艇确实会通过该海峡，但数量有限，而且一旦发生冲突，这种做法将被禁止。** +
**即使穿越"博斯普鲁斯海峡"，俄罗斯舰艇也需要先航行至"爱琴海", 才能进入"地中海". 而且要想进入大西洋，它们仍然需要穿过"直布罗陀海峡"，或者获准通过"苏伊士运河"抵达印度洋。**

Having annexed Crimea, the Russians are wasting no time. They are building up the Black Sea fleet at Sevastopol and constructing a new naval port in the Russian city of Novorossiysk which, although it does not have a natural deep harbour, will give the Russians extra capacity. Eighty new ships are being commissioned, as well as several submarines. The fleet will still not be strong enough to break out of the Black Sea during wartime, but its capacity is increasing.

[.my2]
吞并克里米亚后，俄罗斯人并未停歇。他们正在"塞瓦斯托波尔"扩建黑海舰队，并在俄罗斯"新罗西斯克市"建造一座新的海军港口。**尽管"新罗西斯克"没有天然深水港，但这座港口将为俄罗斯提供额外的吞吐能力。**目前，俄罗斯正在建造80艘新舰艇以及数艘潜艇。这支舰队的实力在战时仍不足以突破黑海封锁，但其作战能力正在不断增强。

To counter this, in the next decade we can expect to see the USA encouraging its NATO partner Romania to boost its fleet in the Black Sea whilst relying on Turkey to hold the line across the Bosporus.

[.my2]
为了应对这种情况，在未来十年，我们可以预见美国将鼓励其北约伙伴罗马尼亚, 加强其在黑海的舰队，同时依靠土耳其守住"博斯普鲁斯海峡"的防线。

The Russians do have a small naval presence in Tartus on Syria’s Mediterranean coast (this partially explains their support for the Syrian government when fighting broke out in 2011), but it is a limited supply and replenishment base, not a major force.

[.my2]
俄罗斯在叙利亚"地中海"沿岸的"塔尔图斯", 确实拥有少量海军力量（这在一定程度上解释了他们在 2011 年爆发冲突时, 对叙利亚政府的支持），但这只是一支有限的补给基地，而不是一支主要力量。

'''

==== -> 出波罗的海, 进入大西洋

Another strategic problem is that in the event of war the Russian navy cannot get out of the Baltic Sea either, due to the Skagerrak Strait, which connects to the North Sea. The narrow strait is controlled by NATO members Denmark and Norway; and even if the ships made it, the route to the Atlantic goes through what is known as the GIUK gap (Greenland/Iceland/UK) in the North Sea – which we will see more of when we look at Western Europe.

[.my2]
**另一个战略问题是，一旦发生战争，俄罗斯海军也无法撤出"波罗的海"，因为"斯卡格拉克海峡"连接着北海。这条狭窄的海峡, 由北约成员国丹麦和挪威控制. 即使舰船能够通过，通往大西洋的航线, 也必须经过北海的格陵兰/冰岛/英国海峡（GIUK 通道）**——我们将在讨论西欧时更详细地了解它。

Russia will continue to push its interests in the Baltic States. They are one of the weak links in its defence since the collapse of the USSR, another breach in the wall they would prefer to see forming an arc from the Baltic Sea, south, then south-east connecting to the Urals.

[.my2]
俄罗斯将继续在"波罗的海国家", 推进其利益。自苏联解体以来，这些国家一直是俄罗斯防御体系的薄弱环节之一，也是其防线上的又一个缺口。俄罗斯希望看到一道弧形防线, 从波罗的海向南延伸，再向东南连接到乌拉尔山脉。

In the case of the three Baltic States, NATO’s position is clear. As they are all members of the alliance, armed aggression against any of them by Russia would trigger Article 5 of NATO’s founding charter, which states: ‘An armed attack against one or more [NATO member states] in Europe or North America shall be considered an attack against them all’, and goes on to say NATO will come to the rescue if necessary. Article 5 was invoked after the terrorist attacks in the USA on 11 September 2001, paving the way for NATO involvement in Afghanistan.

[.my2]
就波罗的海三国而言，北约的立场很明确。由于它们都是北约成员国，俄罗斯若对其中任何一个国家发动武装侵略，都将触发**北约创始宪章第五条。该条款规定：“对欧洲或北美一个或多个[北约成员国]的武装攻击，应视为对所有成员国的攻击”，**并进一步指出，如有必要，北约将提供援助。2001年9月11日美国遭受恐怖袭击后，北约援引了第五条，为北约介入阿富汗战争铺平了道路。


''' 

==== 东侧的中国对远东的威胁

Whatever its European credentials, Russia is not an Asian power for many reasons. Although 75 percent of its territory is in Asia, only 22 percent of its population lives there. Siberia may be Russia’s ‘treasure chest’, containing the majority of the mineral wealth, oil, and gas, but it is a harsh land, freezing for months on end, with vast forests (taiga), poor soil for farming and large stretches of swampland.   +
Only two railway networks run west to east – the Trans-Siberian and the Baikal–Amur Mainline. There are few transport routes leading north to south and so no easy way for Russia to project power southward into modern Mongolia or China: it lacks the manpower and supply lines to do so.

[.my2]
无论其欧洲背景如何，俄罗斯在诸多方面都算不上亚洲强国。虽然其75%的领土位于亚洲，但只有22%的人口居住在亚洲。西伯利亚或许是俄罗斯的“宝库”，蕴藏着大部分矿产、石油和天然气，但那里环境恶劣，常年严寒，拥有广袤的森林（泰加林带）、贫瘠的土壤和大片沼泽地。 +
东西走向的铁路网只有两条——西伯利亚铁路， 和贝加尔-阿穆尔铁路。南北走向的交通路线寥寥无几，因此俄罗斯难以将力量向南投射到现代蒙古或中国：它缺乏足够的人力和补给线。

China may well eventually control parts of Siberia in the long-term future, but this would be through Russia’s declining birth rate and Chinese immigration moving north. Already, as far west as the swampy West Siberian Plain, between the Urals in the west and the Yenisei River 1,000 miles to the east, you can see Chinese restaurants in most of the towns and cities. Many more different businesses are coming. The empty depopulating spaces of Russia’s Far East are even more likely to come under Chinese cultural, and eventually political, control.

[.my2]
**从长远来看，中国最终或许会控制西伯利亚的部分地区，但这主要得益于俄罗斯不断下降的出生率, 以及中国移民北上。**如今，在西部沼泽遍布的西西伯利亚平原，从西部的乌拉尔山脉， 到东部1000英里外的叶尼塞河之间，大多数城镇中都能看到中国餐馆的身影。更多不同类型的企业正在涌入。***俄罗斯远东地区人口稀少、空旷的地区， 更有可能被中国文化乃至政治所掌控。***


''' 

==== 乌克兰, 即拥有不冻港, 也是”向西方扩张”和”南方扩张”的基地

As long as a pro-Russian government held sway in Kiev, the Russians could be confident that its buffer zone would remain intact and guard the North European Plain. Even a studiedly neutral Ukraine, which would promise not to join the EU or NATO and to uphold the lease Russia had on the warm-water port at Sevastopol in Crimea, would be acceptable. That Ukraine was reliant on Russia for energy also made its increasingly neutral stance acceptable, albeit irritating. But a pro-Western Ukraine with ambitions to join the two great Western alliances, and which threw into doubt Russia’s access to its Black Sea port? A Ukraine that one day might even host a NATO naval base? That could not stand.

[.my2]
**只要基辅(乌克兰)由亲俄政府把持，俄罗斯就能确信其缓冲区将保持完整，并能有效守卫北欧平原。**即便乌克兰刻意保持中立，承诺不加入欧盟或北约，并遵守俄罗斯对克里米亚"塞瓦斯托波尔不冻港"的租约，俄罗斯也能接受。乌克兰能源依赖俄罗斯，这也使得其日益中立的立场虽然令人恼火，但也尚可接受。然而，**一个亲西方的乌克兰，渴望加入西方两大联盟，并威胁到俄罗斯使用其黑海港口的权利？一个未来甚至可能成为北约海军基地所在地的乌克兰？这绝对不能容忍。**

All of the above explains why, in 2013, as the political battle for the direction of Ukraine heated up, Moscow concentrated hard.

[.my2]
所有这些, 都解释了为什么在2013年，当围绕"乌克兰走向"的政治斗争升温时，莫斯科会集中精力。

It is no surprise that, after seizing Crimea, Russia went on to encourage the uprisings by pro-Russians in the Ukrainian eastern industrial heartlands in Luhansk and Donetsk. Russia could easily drive militarily all the way to the eastern bank of the Dnieper River in Kiev. But it does not need the headache that would bring. It is far less painful, and cheaper, to encourage unrest in the eastern borders of Ukraine and remind Kiev who controls energy supplies, to ensure that Kiev’s infatuation with the flirtatious West does not turn into a marriage consummated in the chambers of the EU or NATO.

[.my2]
毫不奇怪，俄罗斯在吞并克里米亚后，又煽动乌克兰东部工业重镇卢甘斯克, 和顿涅茨克的亲俄武装起义。俄罗斯完全可以轻易地以武力, 直抵基辅所在的第聂伯河东岸。但它并不想为此付出代价。与其如此大动干戈，不如煽动乌克兰东部边境地区的动乱，提醒基辅, 谁控制着能源供应，从而确保基辅对西方暧昧的迷恋, 不会演变成在欧盟或北约的“联姻”。


''' 

==== 外缘的非俄罗斯族人

When you move outside of the Russian heartland, much of the population in the Russian Federation is not ethnically Russian and pays little allegiance to Moscow, which results in an aggressive security system similar to the one in Soviet days. During that era Russia was effectively a colonial power ruling over nations and people who felt they had nothing in common with their masters; parts of the Russian Federation – for example, Chechnya and Dagestan in the Caucasus – still feel the same way.

[.my2]
**当你离开俄罗斯的核心地带，你会发现俄罗斯联邦的大部分人口并非俄罗斯族，他们对莫斯科的忠诚度也很低**，这导致了一种类似于苏联时期的强硬安全体制。**在苏联时期，俄罗斯实际上是一个殖民强权，统治着那些"感觉与统治者毫无共同之处"的民族和人民；**俄罗斯联邦的部分地区——例如高加索地区的车臣, 和达吉斯坦——至今仍然抱有同样的感受。


''' 

==== 原苏联成员国对俄的”亲,中立, 反”倾向.

If you take the long view of history – and most diplomats and military planners do – then there is still everything to play for in each of the states which formerly made up the USSR, plus some of those previously in the Warsaw Pact military alliance. They can be divided three ways: those that are neutral, the pro-Western group and the pro-Russian camp.

[.my2]
如果从历史长河来看——而大多数外交官和军事策划者正是如此——那么，在曾经组成苏联的各个国家，以及一些曾经的"华沙条约组织"成员国中，仍然存在着各种可能性。它们可以分为三类：中立阵营、亲西方阵营, 和亲俄阵营。

In the pro-Russian camp are Kazakhstan, Kyrgyzstan, Tajikistan, Belarus and Armenia. Their economies are tied to Russia in the way that much of eastern Ukraine’s economy is (another reason for the rebellion there). The largest of these, Kazakhstan, leans towards Russia diplomatically and its large Russian-minority population is well integrated. Of the five, Kazakhstan and Belarus have joined Russia in the new Eurasian Union (a sort of poor man’s EU) and all are in a military alliance with Russia called the Collective Security Treaty Organization. The CSTO suffers from not having a name you can boil down to one word, and from being a watered-down Warsaw Bloc. Russia maintains a military presence in Kyrgyzstan, Tajikistan and Armenia.

[.my2]
**亲俄阵营**包括: 哈萨克斯坦、吉尔吉斯斯坦、塔吉克斯坦、白俄罗斯, 和亚美尼亚。**这些国家的经济与俄罗斯有着紧密的联系，就像乌克兰东部的大部分地区一样**（这也是那里发生叛乱的另一个原因）。 +
其中最大的哈萨克斯坦, 在外交上倾向于俄罗斯，其庞大的俄罗斯族人口, 也融入得相当良好。 +
这五个国家中，**哈萨克斯坦和白俄罗斯, 加入了俄罗斯新成立的"欧亚联盟"（类似于低配版的欧盟），并且它们都与俄罗斯结成了名为"集体安全条约组织"的军事联盟。**"集体安全条约组织"的问题在于, 其名称过于笼统，难以用一个词概括，而且它更像是一个弱化的华沙集团。俄罗斯在吉尔吉斯斯坦、塔吉克斯坦, 和亚美尼亚, 都保持着军事存在。

The neutral countries – Uzbekistan, Azerbaijan and Turkmenistan – are those with fewer reasons to ally themselves with Russia or the West. This is because all three produce their own energy and are not beholden to either side for their security or trade.

[.my2]
**中立国**——乌兹别克斯坦、阿塞拜疆和土库曼斯坦——"与俄罗斯或西方结盟"的理由较少。这是因为**这三个国家都能自给自足地生产能源，其安全和贸易都不依赖于任何一方。**

Then there are the pro-Western countries formerly in the Warsaw Pact but now all in NATO and/or the EU: Poland, Latvia, Lithuania, Estonia, the Czech Republic, Bulgaria, Hungary, Slovakia, Albania and Romania. By no coincidence, many are among the states which suffered most under Soviet tyranny. Add to these Georgia, Ukraine and Moldova, which would all like to join both organisations but are being held at arm’s length because of their geographic proximity to Russia and because all three have Russian troops or pro-Russian militia on their soil. NATO membership of any of these three could spark a war.

[.my2]
此外，还有一些**亲西方国家**，它们曾是华沙条约组织成员，但现在都加入了北约和/或欧盟：波兰、拉脱维亚、立陶宛、爱沙尼亚、捷克、保加利亚、匈牙利、斯洛伐克、阿尔巴尼亚和罗马尼亚。并非巧合的是，**其中许多国家都曾遭受苏联暴政的重创。**再加上格鲁吉亚、乌克兰和摩尔多瓦，这三个国家都希望加入北约和欧盟，但**由于它们地理位置靠近俄罗斯，而且境内都有俄罗斯军队或亲俄武装，因此被拒之门外。这三个国家中任何一个加入北约都可能引发战争。**


''' 

==== 本国人口增长率问题

At home it is facing many challenges, not least of which is demographic. The sharp decline in population growth may have been arrested, but it remains a problem. The average lifespan for a Russian man is below sixty-five, ranking Russia in the bottom half of the world’s 193 UN member states, and there are now only 144 million Russians (excluding Crimea).

[.my2]
俄罗斯在国内面临诸多挑战，其中最严峻的莫过于人口结构问题。尽管人口增长急剧下降的趋势可能已经得到遏制，但这仍然是一个不容忽视的问题。俄罗斯男性的平均预期寿命不足65岁，在联合国193个成员国中排名后半段，而俄罗斯人口（不包括克里米亚）目前仅有1.44亿。

'''

=== 俄罗斯的控制手段




==== 以夷制夷

When the Soviet Union broke apart, it split into fifteen countries. Geography had its revenge on the ideology of the Soviets and a more logical picture reappeared on the map, one in which mountains, rivers, lakes and seas delineate where people live, are separated from each other and thus how they develop different languages and customs. The exceptions to this rule are the ‘Stans’, such as Tajikistan, whose borders were deliberately drawn by Stalin so as to weaken each state by ensuring it had large minorities of people from other states.

[.my2]
**苏联解体后，分裂成十五个国家。**地理对苏联的意识形态进行了报复，一幅更"合乎逻辑"的画面重新出现在地图上：山脉、河流、湖泊和海洋, 划分了人们的居住地，将他们彼此分隔开来，也因此形成了不同的语言和习俗。**这条规则的例外是“斯坦国”，**例如塔吉克斯坦。**这些国家的边界, 是斯大林刻意划定的，目的是通过确保每个国家都拥有大量来自其他国家的少数民族, 来削弱它们。**


''' 

==== 长臂管辖境外的”俄罗斯族”人. 借口保护他们, 而干涉他国内政.

The Kremlin has a law which compels the government to protect ‘ethnic Russians’. A definition of that term is, by design, hard to come by because it will be defined as Russia chooses in each of the potential crises which may erupt in the former Soviet Union. When it suits the Kremlin, ethnic Russians will be defined simply as people who speak Russian as their first language. At other times the new citizenship law will be used, which states that if your grandparents lived in Russia, and Russian is your native language, you can take Russian citizenship. Given that, as the crises arise, people will be inclined to accept Russian passports to hedge their bets, this will be a lever for Russian entry into a conflict.

[.my2]
**克里姆林宫有一项法律，强制政府保护“俄罗斯族人”。这个术语的定义刻意模糊不清，因为在苏联解体后可能爆发的每一次危机中，俄罗斯都会根据自身需要来定义它(并以此为借口发动侵略战争)。**当克里姆林宫认为合适时，"俄罗斯族人"会被简单地定义为"以俄语为母语的人"。而在其他情况下，则会启用**新的公民法，该法规定，如果你的祖父母居住在俄罗斯，并且你的母语是俄语，你就可以获得俄罗斯国籍。**鉴于危机爆发时，人们会倾向于接受俄罗斯护照以求自保，**这将成为俄罗斯介入冲突的杠杆。**

Approximately 60 percent of Crimea’s population is ‘ethnically Russian’, so the Kremlin was pushing against an open door. President Putin would not be the man who ‘lost Crimea’, and with it the only proper warm-water port his country had access to.

[.my2]
克里米亚约有60%的人口是“俄罗斯族”，因此克里姆林宫实际上是在推开一扇敞开的大门。普京总统不想成为“失去克里米亚”的人，也不想失去俄罗斯唯一真正意义上的不冻港。

Energy as political power will be deployed time and again in the coming years, and the concept of ‘ethnic Russians’ will be used to justify whatever moves Russia makes.

[.my2]
未来几年，能源将一次又一次地被用作政治力量，而“俄罗斯族”的概念, 也将被用来为俄罗斯的任何举动辩护。

In a speech in 2014 President Putin briefly referred to ‘Novorossiya’ or ‘New Russia’. The Kremlin-watchers took a deep breath. He had revived the geographic title given to what is now southern and eastern Ukraine, which Russia had won from the Ottoman Empire during the reign of Catherine the Great in the late eighteenth century. Catherine went on to settle Russians in these regions and demanded that Russian be the first language. ‘Novorossiya’ was only ceded to the newly formed Ukrainian Soviet Socialist Republic in 1922. ‘Why?’ asked Putin rhetorically, ‘Let God judge them.’ In his speech he listed the Ukrainian regions of Kharkiv, Luhansk, Donetsk, Kherson, Mykolaiv and Odessa before saying, ‘Russia lost these territories for various reasons, but the people remained.’

[.my2]
2014 年，普京总统在一次演讲中简要提及了**“新俄罗斯”（Novorossiya）。**克里姆林宫观察人士不禁屏住了呼吸。他重新启用了这个地理名称，**指的是如今乌克兰南部和东部的地区。**这些地区是俄罗斯在 18 世纪末叶卡捷琳娜大帝统治时期, **从奥斯曼帝国手中夺取的。叶卡捷琳娜随后将俄罗斯人安置在这些地区，并要求俄语成为第一语言。**“新俄罗斯”直到 1922 年才被划归给新成立的乌克兰苏维埃社会主义共和国。“他们为什么这么做？”普京反问道，“让上帝来评判他们吧。”在演讲中，他列举了哈尔科夫、卢甘斯克、顿涅茨克、赫尔松、尼古拉耶夫和敖德萨等乌克兰地区，然后说道：“**俄罗斯由于各种原因失去了这些领土，但我们的人民依然存在在那里。**”

Several million ethnic Russians still remain inside what was the USSR, but outside Russia.

[.my2]
仍有数百万俄罗斯族人, 生活在原苏联境内，但位于俄罗斯境外。

Russia does not have to send an armoured division into Latvia, Lithuania or Estonia to influence events there, but if it ever does it would justify the action by claiming that the large Russian communities there are being discriminated against. In both Estonia and Latvia approximately one in four people are ethnically Russian and in Lithuania it is 5.8 percent. In Estonia the Russian speakers say they are under-represented in government and thousands do not have any form of citizenship. This does not mean they want to be part of Russia, but they are one of the levers Russia can pull to influence events.

[.my2]
**俄罗斯**无需派遣装甲师进入拉脱维亚、立陶宛, 或爱沙尼亚, 来影响当地局势，但**如果真的这么做了，它会以"当地庞大的俄罗斯族群体受到歧视"为由, 为其行动辩护。在爱沙尼亚和拉脱维亚，大约四分之一的人口是俄罗斯族，**而在立陶宛，这一比例为 5.8%。在爱沙尼亚，讲俄语的人表示, 他们在政府中的代表性不足，而且成千上万的人没有任何形式的公民身份。这并不意味着他们想成为俄罗斯的一部分，但他们是俄罗斯可以用来影响局势的杠杆之一。

The Russian-speaking populations in the Baltics can be stirred up to making life difficult. There are existing, fully formed political parties already representing many of them. Russia also controls the central heating in the homes of the Baltic people. It can set the price people pay for their heating bills each month, and, if it chooses, simply turn the heating off.

[.my2]
**波罗的海地区的俄语人口, 很容易被煽动起来，**制造混乱。**许多俄语人口已经拥有成熟的政党。**俄罗斯还控制着波罗的海地区居民的"集中供暖系统"。它可以设定居民每月的供暖费用，而且如果愿意，还可以随时切断供暖。


''' 

==== 以能源为武器, 卡欧洲脖子

No one rode to the rescue of Ukraine as it lost territory equivalent to the size of Belgium, or the US state of Maryland. Ukraine and its neighbours knew a geographic truth: that unless you are in NATO, Moscow is near, Washington DC is far away. For Russia this was an existential matter: they could not cope with losing Crimea, the West could.

[.my2]
当乌克兰失去相当于比利时或美国马里兰州面积的领土时，无人伸出援手。**乌克兰及其邻国都明白一个地理常识：除非加入北约，否则莫斯科近在咫尺，而华盛顿特区却遥不可及。**对俄罗斯而言，这关乎生死存亡：他们无法承受失去克里米亚的后果(真的不能吗? 还是只是俄为实现自己野心的借口?)，而西方国家却可以。

The EU imposed limited sanctions – limited because several European countries, Germany among them, are reliant on Russian energy to heat their homes in winter. The pipelines run east to west and the Kremlin can turn the taps on and off.

[.my2]
欧盟实施的制裁有限——之所以说有限，是因为**包括德国在内的几个欧洲国家, 在冬季取暖依赖俄罗斯能源。**这些管道东西走向，克里姆林宫可以随时控制能源供应。

Russia’s most powerful weapons now, leaving to one side nuclear missiles, are not the Russian army and air force, but gas and oil. Russia is second only to the USA as the world’s biggest supplier of natural gas, and of course it uses this power to its advantage. The better your relations with Russia, the less you pay for energy; for example, Finland gets a better deal than the Baltic States.  +

[.my2]
撇开核导弹不谈，俄罗斯如今最强大的武器, 并非其陆军和空军，而是天然气和石油。**俄罗斯是仅次于美国的世界第二大天然气供应国，**它自然会利用这一优势。与俄罗斯关系越好，能源价格就越低；例如，芬兰比波罗的海国家, 享受到更优惠的价格。 +

On average, more than 25 percent of Europe’s gas and oil comes from Russia; but often the closer a country is to Moscow, the greater its dependency. This in turn reduces that country’s foreign policy options. Latvia, Slovakia, Finland and Estonia are 100 percent reliant on Russian gas, the Czech Republic, Bulgaria and Lithuania are 80 percent dependent, and Greece, Austria and Hungary 60 percent. About half of Germany’s gas consumption comes from Russia which, along with extensive trade deals, is partly why German politicians tend to be slower to criticise the Kremlin for aggressive behaviour than a country such as Britain, which not only has 13 percent dependency, but also has its own gas-producing industry, including reserves of up to nine months’ supply.

[.my2]
**平均而言，欧洲超过25%的天然气和石油, 来自俄罗斯；但通常情况下，一个国家离莫斯科越近，其对俄罗斯的依赖程度就越高。这反过来又限制了该国的外交政策选择。** +
拉脱维亚、斯洛伐克、芬兰和爱沙尼亚100%依赖俄罗斯天然气.  +
捷克、保加利亚和立陶宛的依赖程度为80%， +
希腊、奥地利和匈牙利的依赖程度为60%。 +
德国约一半的天然气消费来自俄罗斯. 这与广泛的贸易协定一起，在一定程度上解释了为什么德国政界人士在批评克里姆林宫的侵略性行为时，往往比英国等国家更为谨慎。 +
英国不仅对俄罗斯的依赖程度只有13%，而且还拥有自己的"天然气"生产产业，包括可供应长达九个月的储量。

There are several major pipeline routes running east to west out of Russia, some for oil and some for gas. It is the gas lines which are the most important.

[.my2]
俄罗斯境内有多条"东西走向"的主要管道线路，部分输送石油，部分输送天然气。其中，"天然气管道"最为重要。

In the north, via the Baltic Sea, is the Nord Stream route, which connects directly to Germany. Below that, cutting through Belarus, is the Yamal pipeline, which feeds Poland and Germany. In the south is the Blue Stream, taking gas to Turkey via the Black Sea. Until early 2015 there was a planned project called South Stream, which was due to use the same route but branch off to Hungary, Austria, Serbia, Bulgaria and Italy. South Stream was Russia’s attempt to ensure that even during disputes with Ukraine it would still have a major route to large markets in Western Europe and the Balkans. Several EU countries put pressure on their neighbours to reject the plan, and Bulgaria effectively pulled the plug on the project by saying the pipelines would not come across its territory. President Putin reacted by reaching out to Turkey with a new proposal, sometimes known as Turk Stream.

[.my2]
北部经由波罗的海的“北溪”管道直接连接德国。 +
其南端，穿过白俄罗斯的是“亚马尔”管道，为波兰和德国供气。 +
南部是“蓝溪”管道，经由黑海向土耳其输送天然气。 +
直到 2015 年初，还有一个名为“南溪”的计划，该计划原定采用相同的路线，但会分岔通往匈牙利、奥地利、塞尔维亚、保加利亚和意大利。“南溪”是俄罗斯为确保"即使在与乌克兰发生争端期间， 也能拥有通往西欧和巴尔干地区大型市场的主要通道", 而提出的尝试。一些欧盟国家向邻国施压，要求其否决该计划，而保加利亚则以管道不会经过其领土为由，实际上终止了该项目。普京总统随即向土耳其提出了一项新的方案，有时被称为“土耳其溪”。

Russia’s South Stream and Turk Stream projects to circumvent Ukraine followed the price disputes between the two states of 2005–10, which at various times cut the gas supply to eighteen countries. European nations which stood to benefit from South Stream were markedly more restrained in their criticism of Russia during the Crimea crisis of 2014.

[.my2]
俄罗斯的“南溪”和“土耳其溪”天然气管道项目, 旨在绕过乌克兰.此前, 两国(俄乌)在2005年至2010年间发生价格纠纷，导致18个国家的天然气供应一度中断。在2014年克里米亚危机期间，那些有望从“南溪”管道项目中获益的欧洲国家, 对俄罗斯的批评明显更为克制。

This policy has been used so aggressively, and Russia has such a hold over Europe’s energy needs, that moves are afoot to blunt its impact. Many countries in Europe are attempting to wean themselves off their dependency on Russian energy, not via alternative pipelines from less aggressive countries but by building ports.

[.my2]
俄罗斯如此积极地运用这一政策，并牢牢掌控着欧洲的能源需求，以至于一些国家正在采取措施削弱其影响。**许多欧洲国家正试图摆脱对俄罗斯能源的依赖，但他们并没有选择从其他不那么咄咄逼人的国家铺设替代管道，而是通过"建设港口"来实现这一目标。**

Enter the Americans, with a win-win strategy for the USA and Europe. Noting that Europe wants gas, and not wanting to be seen to be weak in the face of Russian foreign policy, the Americans believe they have the answer. The massive boom in shale gas production in the USA is not only enabling it to be self-sufficient in energy, but also to sell its surplus to one of the great energy consumers – Europe.

[.my2]
美国人带着一项对美国和欧洲都有利的双赢策略, 登场了。他们注意到欧洲需要天然气，而且不愿在俄罗斯的外交政策面前显得软弱，因此认为他们找到了解决办法。**美国页岩气产量的大幅增长, 不仅使其能够实现能源自给自足，还能将其剩余天然气, 出售给能源消费大国之一——欧洲。**

To do this, the gas needs to be liquefied and shipped across the Atlantic. This in turn requires liquefied natural gas (LNG) terminals and ports to be built along the European coastlines to receive the cargo and turn it back into gas. Washington is already approving licences for export facilities, and Europe is beginning a long-term project to build more LNG terminals. Poland and Lithuania are constructing LNG terminals; other countries such as the Czech Republic want to build pipelines connecting to those terminals, knowing they could then benefit not just from American liquefied gas, but also supplies from North Africa and the Middle East. The Kremlin would no longer be able to turn the taps off.

[.my2]
**为此，天然气需要液化, 并跨大西洋运输。这反过来又需要在欧洲沿海地区建设"液化天然气（LNG）接收站和港口"，以便接收货物, 并将其重新恢复成天然气。**华盛顿已经开始批准"出口设施"(指用于出口商品的设施，包括仓库、码头、运输工具等)的许可证，欧洲也启动了一个建设更多 "LNG 接收站"的长期项目。 +
波兰和立陶宛正在建设 LNG 接收站；捷克等其他国家也希望建设连接这些"接收站"的管道，因为他们知道这样一来，不仅可以从美国获得"液化天然气"，还可以从北非和中东获得供应。克里姆林宫将再也无法切断天然气供应。

The Russians, seeing the long-term danger, point out that piped gas is cheaper than LNG, and President Putin, with a ‘what did I ever do wrong’ expression on his face, says that Europe already has a reliable and cheaper source of gas coming from his country.  +
LNG is unlikely to completely replace Russian gas, but it will strengthen what is a weak European hand in both price negotiation and foreign policy. To prepare for a potential reduction in revenue Russia is planning pipelines heading south-east and hopes to increase sales to China.

[.my2]
**俄罗斯人意识到长远风险，指出"管道天然气"比"液化天然气"更便宜。**普京总统脸上带着一副“我到底做错了什么”的表情，声称欧洲已经拥有来自俄罗斯的可靠且更便宜的"天然气"来源。 +
"液化天然气"不太可能完全取代俄罗斯"天然气"，但它将增强欧洲在"价格谈判"和"外交政策"方面, 原本薄弱的筹码。**为了应对潜在的收入减少，俄罗斯正在规划向东南方向延伸的管道，并希望增加对中国的天然气销售。**

This is an economic battle based on geography and one of the modern examples where technology is being utilised in an attempt to beat the geographic restraints of earlier eras.

[.my2]
这是一场基于地理位置的经济竞争，也是利用技术, 来克服"早期时代的地理限制"的一个例子。


''' 

==== 境外驻军

===== 格鲁吉亚案例

Across the Black Sea from Moldova lies another wine-producing nation: Georgia. It is not high on Russia’s list of places to control for two reasons. Firstly the Georgia–Russian war of 2008 left large parts of the country occupied by Russian troops, who now fully control the regions of Abkhazia and South Ossetia. Secondly, it lies south of the Caucasus Mountains and Russia also has troops stationed in neighbouring Armenia. Moscow would prefer an extra layer to their buffer zone, but can live without taking the rest of Georgia. That situation could potentially change if Georgia looked close to becoming a NATO member. This is precisely why it has so far been rebuffed by the NATO governments, which are keen to avoid the inevitable conflict with Russia.

[.my2]
摩尔多瓦的黑海对岸, 是另一个葡萄酒生产国：格鲁吉亚。出于两个原因，格鲁吉亚并非俄罗斯重点控制的目标: +
首先，2008年的格鲁吉亚-俄罗斯战争, 导致俄罗斯军队占领了该国大片领土，目前俄罗斯军队已完全控制了阿布哈兹和南奥塞梯地区。 +
其次，格鲁吉亚位于高加索山脉以南，而俄罗斯在邻国亚美尼亚也驻扎着军队。 +
**莫斯科更希望在其缓冲区之外, 再增加一层屏障，**但并不急于吞并格鲁吉亚的其他地区。然而，如果格鲁吉亚有望加入北约，情况可能会有所改变。这正是北约各国政府迄今为止拒绝格鲁吉亚的原因，它们都希望避免与俄罗斯发生不可避免的冲突。

A majority of the population in Georgia would like closer ties with the EU countries, but the shock of the 2008 war, when then President Mikheil Saakashvili naively thought the Americans might ride to his rescue after he provoked the Russians, has caused many to consider that hedging their bets may be safer. In 2013 they elected a government and president, Giorgi Margvelashvili, far more conciliatory to Moscow. As in Ukraine, people instinctively know the truism everyone in the neighbourhood recognises: that Washington is far away, and Moscow is near.

[.my2]
格鲁吉亚的大多数民众, 都希望与欧盟国家建立更紧密的联系，但2008年战争的冲击——当时总统米哈伊尔·萨卡什维利天真地以为，在他挑衅俄罗斯之后，美国会出手相救(,但事与愿违)—— 这让许多人开始考虑，对冲他们的赌注, 或许更为稳妥。于是2013年，他们选举了对莫斯科更为友好的政府, 和总统格奥尔基·马尔格韦拉什维利。**正如在乌克兰一样，人们本能地明白一个邻国都认同的真理：华盛顿远在天边，而莫斯科近在咫尺。(离天堂太远, 离俄罗斯太近)**



''' 

==== 结盟他国(反美国家)

Away from the heartland Russia does have a global political reach and uses its influence, notably in Latin America, where it buddies up to whichever South American country has the least friendly relationship with the United States, for example Venezuela. It tries to check American moves in the Middle East, or at least ensure it has a say in matters, it is spending massively on its Arctic military forces, and it consistently takes an interest in Greenland to maintain its territorial claims.  +
Since the fall of Communism it has focused less on Africa, but maintains what influence it can there albeit in a losing battle with China.

[.my2]
除了核心地带，俄罗斯在全球政治领域, 也拥有广泛的影响力，并积极运用这种影响力，尤其是在拉丁美洲。在拉丁美洲，俄罗斯会与那些与美国关系最不友好的南美国家结盟，例如委内瑞拉。**它试图遏制美国在中东的行动，或者至少确保自身在相关事务中拥有发言权。** +
俄罗斯在"北极"军事力量上投入巨资，并持续关注格陵兰岛，以维护其领土主张(俄罗斯队格陵兰岛还有领土主张?)。 +
自共产主义政权垮台以来，俄罗斯对非洲的关注有所减少，但仍在非洲维持着力所能及的影响力，尽管在与中国的博弈中处于劣势。

'''


=== 俄罗斯的经济

Its agricultural growing season is short.


[.my2]
俄罗斯的农业生长季较短.






























