
= 中国近代史
:toc: left
:toclevels: 3
:sectnums:

'''

== 用政治意识形态来教历史, 就是伪史

中国在历史教育上的问题 : *学校里的课, 名义上讲的是历史，实际上却不是在搞真正的历史研究，而是按政治课的性质开的. 其目的是想给学生灌输一种特定的意识形态.* 因此, *从是非和真伪角度来看，这样的历史就是伪史.*

以往我国的近代史说法,有一个范文澜、胡绳的基本模式。这种模式通常有两条线索: +
其一线索: 是"帝国主义侵略论" ——自鸦片战争以来，西方列强总是侵略、欺负中国。强调这样一条脉络，由此证明我们的落后是因为别人侵略、欺负我们造成的。这只会造成"怨妇心态".  +
其二线索: 是"革命线索" —— 从太平天国、义和团, 然后到辛亥革命. 这很容易使我们忽略从晚清以来的丰富变化. +
如果我们不知道近代中国是怎样融入世界体系的，或者完全无视这个过程，结果就只能是我们有人重新开始鼓噪排外。

晚清历史的本质, 就是西方把中国拖入它们的世界体系的过程。中国传统的体制是"朝贡体系". *朝贡体系就是国与国不平等关系.*


'''

== 中西"开放程度"与"发展速度"对比

*西方在"工业革命"之前, 已经经历了一场手工业革命*，航海船只的建造已经很精致了，还有为造枪炮、火药而制作的一些加工机械。所以工业革命不是一下子就蹦出来的。以前教科书里说，瓦特看着烧水的壶盖儿被蒸汽顶起来，就发明了蒸汽机。其实从科技史就可以知道，蒸汽机最早不是瓦特发明的，他只是把蒸汽机改进了而已。

所以对比西方，中国在明朝中叶的时候已经落后了. +
西方工业革命: 18世纪60年代起. +
中国明朝: 14世纪中叶-17世纪中叶 +

清朝在开放程度上, 远不如明朝:
[.small]
[options="autowidth" cols="1a,1a,1a"]
|===
| |明朝|清朝

|文明上的交流
|明朝的对外开放, 很大程度要归功于传教士. 因为早先来的传教士都认为，中国人祭祖不算是偶像崇拜.
|而到了康熙年间，罗马教廷坚持认为祭祖就是搞偶像崇拜，中国人要入教就不能祭祖. 结果清朝在雍正(康熙之子)时期完全禁教, 导致西方传教士的势力基本退出了中国。(相反, 日本的兰学(荷兰窗口)一直没断过)

|海外贸易
|明朝在中后期虽然也有海禁，但是海禁执行得不彻底，所以沿海的商业走私, 还是很活跃。
|但清朝的官员把海禁执行的很严格, 多数时候只有广州一口可以进行贸易。所以相对于明朝，清朝是一个更加内向的王朝。

|世界地理知识
|在明朝的时候, 利玛窦已经把世界地图和地球仪带到了中国.
|但是到了清朝，中国人对于世界的感知以及观念又发生了倒退.
|===



'''

== 清朝状况

==== 商业

传统中国是一个对商业不在乎的王朝, **基本不征收"商税"，只对一些商品收过路"关税"。由于不收"商税", 主要靠征收"田赋"和"盐税"这么点钱，是不可能有长期增长的，所以每年国库的盈余都不多。** 清朝在很长一段时期里，一般岁入就七八千万两，或六七千万两，大体上就在这个区间波动，收入上不去. 一旦前代的皇帝把钱
花光了，后面的财政就会很紧张.

'''

==== 外贸

早在北宋时, 中国就有"公行制度". **政府需要对进出口贸易进行管理，但是官员又懒得管，于是把所有的事情都委托给商人办理 -- 进出口贸易的具体手续都由商人处理，外商也由商人接待，官员只负责监督。** +
在公行制度下，招待、管理外国商人的相关事宜, 都是由"公行"来管; 贸易结算以及征收关税等事务, 也都是由商人打点。关税收入属于皇室的私家收入.

康熙时, 中国在沿海四个地方设了贸易口岸, 实际做起来的主要是宁波和广州。之后宁波也逐渐废掉，只剩广州.

'''

=== 思想专政

以前的中国, 皇帝只作为政治权威, 而儒家思想阐释权的权威, 是由士大夫来负责的. 但清朝却更加集权, 乾隆剥夺了士大夫的这种权力, 自己来阐释经典.


'''

== 西方打开中国国门, 将中国融入他们的世界体系中

十八世纪之后，英国称霸世界的时代开始了.

==== 马嘎尔尼使团

十八世纪末，英国和中国发生第一次接触, 马嘎尔尼 (George Macartney) 使团来华, 希望: 1,通商. 2,给英国商人提供一些据点，不要限制在广州一个地方。这两个目的都没能实现。不过，马嘎尔尼也收获了一批副产品 ——他在内地走了很多地方。在马嘎尔尼来之前，欧洲还流传着关于中国的神话, 尤其是马可·波罗以后，欧洲关于中国的神话很厉害. 但马嘎尔尼实地探访后, 发现中国完全不是那样.

'''

==== 第一次鸦片战争 -- 中英 《南京条约》 -- 利益均沾

早期英国对远东的贸易, 是由"东印度公司"专营的，这是一个商人的联合组织。1832年，*英国把东印度公司这种专营公司取消了，彻底地实行了自由贸易。* 以前让专营公司主持的时候，专营公司是有私人武装的，他们不需要国家的保护。专营制度取消以后，国家的责任就大了，导致国家必须直接地去保护对外商贸，推广商务。

从1833年到1840年，英国的商务监督一直无法与中国有实权的人物进行直接对话.

中国因进口鸦片, 支付了很多白银. *白银的总量少了，物以稀为贵, 银就升值了，而相应铜钱就贬值了. 这导致物价飞涨.*

林则徐禁烟, **当时英国商务监督, 让走私鸦片的英国商人把鸦片交出去，向他们保证，商人的损失由英国政府来承担 -- 这就变成中英政府之间的问题了。**所以后来鸦片战争的谈判有一项，就是要赔偿这个鸦片的损失。

**在那个时代，不论是英国还是其他欧洲国家，他们派出的使节都握有极大权力。**原因是当时的通信很不方便. 如今各种事情都可以打电话向国内请示。但那时候，一封信从英国寄送到中国，可能要几个月，因此当时驻外官员都是便宜行事，都是“将在外，君命有所不受”，可以先斩后奏。

英国希望如果能通过恐吓达到目的, 就没必要战争. 于是英国舰队直上天津白河口，因为这里离中国的首都更近, 恐吓效果会更好. 但清廷派出的琦善, 无法向欧洲国家一样, 在涉外谈判中可以全权代表国家。所以没有谈成. 英国就继续开进到第二个地理目标 --  长江三角洲, 也即漕运的起点. 掐断漕运路线, 清廷就没有粮食. 英军最终打到南京，清廷被迫签订《南京条约》.

.《南京条约》
====
- 割让香港岛
- 开放五处港口: 广州、厦门、福州、宁波, 上海
- 两国共同订立进出口关税；英商货物在其中一处通商口岸按例纳税后，即可由中国商人遍运中国各地，不得加重税。
====

注意: "领事裁判权"在<南京条约>之前, 就已经在广州通商口岸上实现了.
《南京条约》没有规定开放教禁，但附件中**有一项“利益均沾”条款，规定，清庭以后跟其他西方国家所签
订的条约，其效力应对所有的西方世界有用。**

<南京条约>, 清廷开放了五个口岸城市, 但**清廷却一直在抵抗贸易, 你们外国商人可以来, 但我让你卖不出东西. 由于具体的商贸规则还没有制定，中外贸易中还存在许多障碍.**

1850年以后，上海的对外贸易总额已经超过广州，成为中国最重要的对外贸易口岸。 +
在上海的外国人不愿意在城内居住，就在城外规划土地建房，这些地区, 就发展成"租界"的雏形. 现在的上海市就是围绕着租界开始发展的，原来老的县城反而被冷落了。当时"租界"外边是"华界"，华界也模仿租界的管理办法，于是，整个城市都以租界为模仿对象。



'''

==== 民间叙事中的两个神话

传统的灌输式历史教育, 给鸦片战争创造了两个神话 :

.神话1: 忠奸之分
有如民间传说中的杨家将、岳飞故事, 在这种故事的叙事中，忠于国家的将领在前线杀敌报国，一般来说是胜券在握的。但他们最后失败了，为什么呢？民间的说法就是有奸臣在后方捣乱。这种叙事的逻辑是：如果后方没有奸臣捣乱，中国人将每战必胜。 这种思维被套用到了林则徐身上. 但事实并非如此. 西方人怕林则徐吗？根本不怕.  +

看当时的材料就能发现，当时多数中国老百姓在战争中其实没什么立场，因为他们的观念是，兵和匪差不多。中国历史上，兵的纪律一向很不好，每到一个地方都会抢劫老百姓. *俗语说，"匪来如梳，兵来如篦bì".* (篦 : 是一种齿比梳子密的梳头用具. ) 所以老百姓见了兵是要躲的, *注意，这里躲的不是敌方的兵，而是自己的兵。* 从现有的材料来看，当时英军的军纪要比清军好. 老百姓们都没有什么立场，不能因此就说他们都是汉奸，当汉奸还是要有条件的。


.神话2 : 百姓怕官，官怕洋人，洋人怕百姓

三元里抗英这件事，被官方渲染成"大捷", 事实上, 英国就损失了一个人. 缺乏组织且没有什么先进武器的老百姓，怎么可能抵挡得住英国的正规军呢？

事实上, 当时政府也的确一直在发动群众，但效果不大.

'''

==== 中法《黄埔条约》(1844) -- 开放教禁

中法《黄埔条约》中，就规定了"开放教禁". 因为法国当时是罗马天主教教皇的护教国，它有支持宗教传播的责任。 +

虽然法国的意图只是开放"天主教"，但"新教"也通过条约得到了正式地位。*新教在传播, 给之后中国带来的影响十分重大* :

- 太平天国起义的诱因之一就是新教。
- **后来中国的变革，**从自强运动、洋务运动到戊戌维新，甚至到民国后的军阀时期，**很多都跟新教有关。**
- **真正在中国有影响的传教士，基本都是新教的传教士. **由新教教士创办的报纸, 如《万国公报》，对中国思想界起到了启蒙作用。*开放教禁, 西方的文明思想就能借着传教士渠道输入进来。*

'''


==== 第二次鸦片战争 -- <天津条约>(1858) -- 英国人管理中国关税

对英法, 他们依然面临着这些问题:

- 五个通商口岸太少, 必须让中国真正地开放市场，必须要让通商口岸扩大到沿海各处。
- 清廷当时没有外交部, 也没有什么衙门可以和英国使节交涉. 而英法希望要跟中国建立外交关系，也就是让中国政府承认外国公使的正当地位，允许其进驻北京，而且中国也必须派出使节到外国。

第二次鸦片战争, 发生在英国人和法国人要求续约的时候。由一件微不足道的小事“亚罗号事件”引发. 广州沦陷. 而此时太平天国势头正劲，清廷只能签订《天津条约》(中-英法 / 中-美 / 中-俄) 和《北京条约》(中-英 / 中-法 / 中-俄)

.中美天津条约
====
- “宽容条款” : 不仅外国传教士，连中国信徒也需受保护。
====


.中英法天津条约
====
- 享有领事裁判权。
- 关税由双方协定，每十年修订一次。
- 海关聘用英人帮办税务。
- 修改税则，以“值百抽五”(即5%)为原则。
- 双方互派公使；并进驻北京。
====


本来清政府已经答应了<天津条约>，后来英法公使进京换约，换约完成，《天津条约》就能正式生效. 但是咸丰不希望看到外国公使进京，乃至互派使节。担心如果外国公使见皇帝不下跪成为榜样，那么其他臣民见他也就不
会下跪了。英法公使从大沽口走, 遭到清军袭击. 最终就是英法联军进京, 并火烧圆明园. 其实, *国际政治的
道德水平是逐步提高的，那个时候还是丛林时代，法则还是属于"弱肉强食"的.* 清廷又败, 条约也得重新签 -- 即《北京条约》。

第二次鸦片战争后，清朝终于正式成立了"外交部" -- 总理衙门.

'''

==== 太平天国

传统中国: +
-> 南方主要是稻米，它产量比较高，但对田地质量的要求也比较高，要求土地平整，有充足的水源； +
-> 北方一般种植的是小米，它对土地质量的要求不高，什么地方都可以种，但是产量低.

但明朝中后期, 传入了番薯和玉米. 不仅适应性广，什么地方都能种, 而且都能高产. 所以此时很多山间的土地都被开发出来了.

以往历史研究里面有一个误区，常常认为，农民只要脱离了土地，就成了失地农民，是流民。但农民不种地, 未必都是流民，也可能从事其他行业了。*如果农民一直被禁锢在土地上，那么其他行业还怎么发展？*

民间的那些秘密宗教或秘密帮会，最初都不是秘密的，而是一些脱离土地的农民的自助组织.

太平天国爆发的背景, 并非是“土地兼并—农民流离—饥民遍地——起义蜂起”这一逻辑。






'''


68





















