



共产党(此时党员人数不到一千人), 策略是 : 在国民党外发展其中共组织, 并从国民党内控制该党 (成为核心部门的人员)。共产党人曾不断渗入黄埔军校, 但最终未能成功. 事实上, 之后随着国民党军队所起的作用越来越大, 共产党对国民党只进行纯政治控制, 就越来行不通了 (必须掌握军队). 同时, 国民党军队中占统治地位的反共力量, 也将中共最终踢出了国民党起了很大作用.

"五卅运动"等偏激事件, 共产党利用了这些机会, 使共产党员和共青团员的人数迅速增加.

共产党再次面临是继续与国民党合作还是转而反对它的选择。此时, 蒋介石为了北伐, 仍然需要与共产党合作, 和苏联的援助. 斯大林也需要与蒋介石合作，以此来作为驳倒托洛茨基的手段。

占领上海后, 蒋介石无视武汉政府,在国民党中央执行委员会大部分委员的支持下, 在南京建立了他自己的政府。

北伐之后, 中国名义上完成统一, 国民党政府开始努力废除不平等条约. 但这个行动在1931年之后有所减弱. 因为日本对中国的新侵略, 及苏联共产主义的威胁, 使国民党需要同西方的合作, 他们有共同的利害关系. 所以南京政府降低了攻击外国特权的调门.


20年代, 中共还很难有夺权成功的机会 :

- 寄生上 : 中共无法从国民党的内部来稿垮该党，因为共产国际为国民党提供了一个苏联模式的集中的政党结构，所以难以颠覆 (不像美国的党非常松散, 不存在纪律性)。
- 群众上 : 工会只能在少数几个港口城市中发展势力,而这里新的国民政府的领导力量和外国势力也最为集中。
- 军队上 : 由于没有本党的军队,共产党无法夺取城市。




南京政府的十年 (1928-1937) : 不幸的是，西方这个时期正被自身的问题所困扰: 苏联兴起了斯大林主义, 美国发生了大萧条, 德国产生了纳粹主义。

蒋介石面临的主要问题是, 如何与党早期的领袖，特别是左派的汪精卫, 和右派的胡汉民, 进行合作, 并从中进行离间。蒋分石在不同的时间里, 先后与他们中的一人合作来反对另一人。胡汉民死于1936年.

国民党从未能够对其党员实行严格的纪律.

国民党的一些部门, 会行使中央"行政系统"的部分职能。这样就是, 党和政府相互渗透, 实际上已无法区分开来(党政不分)。

.案例
====
如今中共中, 支持要"党政分开"的理由:

1.让自己变成了对立矛盾中的其中一方 :  +
党政不分, 使党委处于行政工作第一线，自身变成了矛盾(拥有"两个面")中的其中一个"面". 只有党政分开，才能使党处在超脱的地位, 从而发挥“协调各方”的领导作用。(即不要当运动员, 而要当裁判员.) 社会中各群体都有自己的利益, 党要做的是协调各种利益、各种矛盾, 而不能让自己变成矛盾(怒火)指向的直接对象. 党委若自己包办了政府的工作，就使党委变成了当事人的一方，使自己丧失了本来具有的协调矛盾的资格 (即变成了"即当运动员, 又当裁判员")。

2.让自己失去了监督资格 +
党政不分, 也使党委失去了"监督"的职能. 因为你自己不能监督自己。你自己包揽了行政工作，就失掉了监督行政的资格。

3.让自己失去了"思考大局"的时间精力 +
党政不分的话, 党委包揽政府事务，就把自己变成了政府. 领导者直接包揽被领导者的事情，是把自己降低到被领导者的地位。领导，要高瞻远瞩，不能陷到事务堆里。

4.老是在做别人的事, 而没做自己本身该做的事. 提他人做嫁衣裳. +
党政不分, 使党顾不上抓党的建设. “种了别人的地，荒了自己的田”。 别的方面的工作，有政府，有人大，有各种社会团体等组织在做, 要把他们的作用发挥出来 (不要让他们闲着)。而党的工作(思想建设等), 其他各种组织是无法替代的, 不能越俎代庖的。


反对"党政分开"的理由:



====


国民党创立国民党工会, 来对抗共产党的左翼工会. 但农民协会被普遍镇压, 相当于国民党放弃了农村群众的力量.

在蒋的领导下, 国民党的军队成为一个在创建它的领袖领导下的准政府, 而不是一支由国民党控制的苏式政党军队。黄埔军校的毕业生, 把持了军事委员会的高级职位 (相当于他们都是蒋介石的门生). 国军不受文官政府节制。也不受立法机关的制约。(军队变成了蒋介石的私家军, 而非政党的军队.)

国民政府从未彻底地控制其财政, 更不用说控制国家经济.

鲁迅断言: 好的文学作品从不依照别人的指令写成。


蒋介石正确地预料到日本的狂热侵略, 将会或迟或早地使其他列强对中国提供援助, 因此战争成了对耐力的考验.













499
