

= Economist 2019-11-(04)
:toc:

---

== 04 - Thirty years after the Berlin Wall *fell*

Germans still *don’t agree on* what reunification (国家等的)重新统一 *meant*

Discontent(n.)(`=a feeling of being unhappy because you are not satisfied with a particular situation; sth that makes you have this feeling`) *may even be growing*


Nov 2nd 2019 | BERLIN, BISCHOFFERODE 德国地名 AND LEIPZIG 莱比锡城

ON NOVEMBER 9TH 1989, as the Berlin Wall *tumbled*(`=to fall suddenly and in a dramatic way`), `主` Hans-Joachim Binder `系` *was* on night shift(`=a period of time worked by a group of workers who start work as another group finishes 班；轮班；轮班工作时间`) at the potash 钾碱 mine 矿井；矿 in Bischofferode, a village in the communist-ruled German Democratic Republic. ② `主` Mr Binder, a maintenance(`=the act of keeping sth in good condition by checking or repairing it regularly`) worker who *had toiled*(`=to work very hard and/or for a long time, usually doing hard physical work`) in the mine for 17 years, `谓` *had no idea of* the momentous(`=very important or serious, especially because there may be important results`) events *unfolding*(`=to be gradually made known; to gradually make sth known to other people`) 240km (150 miles) to the east. ③ The first sign (something was up(a.)(`=working 在运行`)) *was* when most of his colleagues *disappeared* to investigate(v.)(`=try to find out what happened or what is the truth`) what *was happening* at the border with West Germany, just ten minutes’ drive away. 开车只要十分钟 ④ Only three *returned* to complete(v.) their shift.
====
- tumble => 来自古英语 tumbian,跳舞，跳跃，翻滚，来自 Proto-Germanic tumona,*旋转，转动*，词源同 tumbler,tumbrel.-le,表反复。引申诸相关词义。
- toil (v.)（长时间）苦干，辛勤劳作 => 来自中古法语 toile,网，罗网，来自拉丁语 tela,网，来自 PIE*teks, 编织，纺织，词源同 texture,textile.拼写比较 regulate,rule.引申词义圈套。

- up : a. ( of a computer system 计算机系统 ) working 在运行 +
-> Our system *should be up* by this afternoon. 到今天下午，我们的电脑系统应该运行起来了。
====

[Less than a year later] Germany *was reunited*(`=to join together again separate areas or separate groups within an organization, a political party, etc.; to come together again`), *capping* 胜过；超过；比…更… one of the most extraordinary(`=not normal or ordinary; greater or better than usual`) stories in modern history. ② Not only *had* a communist dictatorship(n.)(`=government by a dictator 独裁；专政`) *collapsed*, *releasing* 16m people *from the fear of* the Stasi 斯塔西（前民主德国国家安全局） (secret police) and the stultification(`=cause to appear foolish; deprive of strength or efficiency; make useless or worthless`) of censorship(n.) (官方对书刊、剧本、电影或新闻报道的) 审查. ③ Unlike any other country *ever freed from* tyranny(n.)(`=unfair or cruel use of power or authority 专制暴政;暴君统治`), `主` the entire population of East Germany `谓` *was given* citizenship(`=the legal right to belong to a particular country`) of a big, rich democracy(`=a system of government in which all the people of a country can vote to elect their representatives`). ④ As a grand(a.)(`=behaving in a proud way because they are rich or from a high social class`), if ill-fated(`=not lucky and ending sadly, especially in death or failure 注定要倒霉的；时运不济的；（尤指）结局悲惨的`), gesture(`=something that you do or say to show a particular feeling or intention`) of welcome the West German chancellor(`=the head of government in Germany or Austria`), Helmut Kohl, *converted* some of their worthless savings *into* hard currency 硬通货（币值稳定，容易兑换） [at the preposterously(`=completely unreasonable`) generous 慷慨的；大方的 exchange rate 汇率；兑换率 of one Deutschmark 西德的马克 *to* one Ostmark 东德的马克].
====
- cap : v. ( especially BrE ) *to say or do sth that is funnier, more impressive, etc. than sth that has been said or done before* 胜过；超过；比…更… (cap的名词意思, 是 "（尤指男用有帽舌的）便帽，制服帽") +
-> What an amazing story. Can anyone *cap that*? 这真是个精彩的故事！还有人能讲得更精彩吗？

- stultify : V-T If something stultifies you, or if it stultifies your energy or ambition, *it makes you feel empty or dull in your mind, because it is so boring*. 使呆滞; 使厌烦 +
=> 来自拉丁语 stultificare,使变得愚蠢，来自 stultus,愚蠢的，缓慢的，迟钝的，原义为不想动的， 动不起来的，来自 PIE*stel,站立，放置，词源同 stall,still,stolid. +
-> We must fight low expectations because *they stultify(v.) ambition*.
我们一定要摆脱较低的期望，因为它们会磨灭我们的志向。

- preposterous (a.)荒唐的；极不合情理的 => 来自拉丁语praeposterus,矛盾的，前后颠倒的，来自prae,在前，post,在后。引申词义荒唐的，荒谬的。
====

More than 1m Ossies *took advantage of*(`=to make use of sth well; to make use of an opportunity`) their new freedom *by moving to* the West, where most thrived(`=to become, and continue to be, successful, strong, healthy, etc`). ② Official statistics *no longer counted* this group -- who *were* disproportionally young, clever(`=quick at learning and understanding things`), female and ambitious -- *as* East Germans. ③ For those who *stayed behind* 留下来在某处留下不走, however, `主` the 30 years (since the fall of the Wall) `谓` *have been* a mix of impressive progress, often *taken for granted*(`=to be so used to sb/sth that you do not recognize their true value any more and do not show that you are grateful （因习以为常）对…不予重视；（因视为当然而）不把…当回事`), and sour(`= not cheerful; bad-tempered and unpleasant`) disappointment.

然而，对于那些留下来的人来说，柏林墙倒塌后的30年, 既有令人印象深刻的进步，也有令人失望的地方 。

====
- *take advantage of sth/sb* : +
(1) *to make use of sth well; to make use of an opportunity* 利用；利用（机会） +
(2) *to make use of sb/sth in a way that is unfair or dishonest* 欺骗；占…的便宜 +
She took advantage of the children's absence to tidy their rooms. 她趁孩子们不在时收拾了他们的房间
-> She *took advantage of the children's absence* to tidy their rooms. 她趁孩子们不在时收拾了他们的房间

- *take it for granted (that...)* : to believe sth is true without first making sure that it is 为…是理所当然 +
-> *I just took it for granted that* he'd always be around. 我还想当然地以为他总能随叫随到呢。

- *take sb/sth for granted* : to be so used to sb/sth that you do not recognize their true value any more /and do not show that you are grateful （因习以为常）对…不予重视；（因视为当然而）不把…当回事 +
-> We *take* having an endless supply of clean water *for granted*. 我们想当然地认为洁净水的供应无穷无尽而不予以珍惜。

====


A price to pay 付出的代价

`主` The harm *wrought(`=caused sth to happen, especially a change`) by* four decades of oppression(`=the cruel or unfair treatment of a group of people`) and indoctrination(`=to force sb to accept a particular belief or set of beliefs and not allow them to consider any others`) `谓` *could not be undone(`=not fastened or tied 未扣；未系；松开`)* overnight. ② But `主` a people *brought up*(`=they grew up in that place or were taught those attitudes when they were growing up`) in a society where initiative(n.)(`=the ability to decide and act on your own without waiting for sb to tell you what to do`) *was ruthlessly(`=hard and cruel; determined to get what you want and not caring if you hurt other people 残酷无情的`) crushed* `谓` *had to adapt suddenly to* the rigours(`= the difficulties and unpleasant conditions of sth`) of capitalism. ③ Unsurprisingly, many *could not*. ④ Mr Binder *was laid off* 解雇. ⑤ So *were* hundreds of thousands of others who *previously toiled*(`=to work very hard and/or for a long time, usually doing hard physical work`) in safe, dreary(a.)(`=that makes you feel sad; dull and not interesting`) and unproductive(`=not producing very much; not producing good results`) state-backed 国家支持的 jobs. ⑥ Despite *attempts to save it*, *including* large protests(n.)(`=the expression of strong disagreement with or opposition to sth; a statement or an action that shows this`) and a hunger strike(`=the act of refusing to eat for a long period of time in order to protest about sth 绝食（抗议）`), the potash 钾碱 mine *was shut down* -- one of 8,500 companies in the east *privatised(`= to sell a business or an industry so that it is no longer owned by the government 使私有化；将…私营化`) or liquidated(`=to close a business and sell everything it owns in order to pay debts 清算，清盘（停业后将资产出售，偿还债务）`) by* the Treuhand 机构名, a new government agency. ⑦ Mr Binder *bounced around* in odd(`=of no particular type or size; various 各种各样的`) jobs for a while, eventually *winding up*(`=you finish it or stop doing it`) on Hartz IV, the stingiest(`=not given or giving willingly; not generous, especially with money 小气的；吝啬的`) of Germany’s unemployment benefits 失业津贴;失业救济;失业金, where he *languishes*(`=to be forced to stay somewhere or suffer sth unpleasant for a long time`) today. ⑧ Like many East German women, his wife *retrained* and *left for 动身前往 a job* in the west. ⑨ Asked how he *feels about* the reunification 重新统一；重新团结 of his country, he *shrugs*(`=to raise your shoulders and then drop them to show that you do not know or care about sth`). “My safe job *was gone*. For me, the GDR(`=原德意志民主共和国;东德（German Democratic Republic）`) *could have carried on*(`=continue to do it`).”

====
- wrought : V-T If something has wrought a change, *it has made it happen*. 使发生 +
=> 来自 work 的古过去分词形式，已完成的，造成，铸成。 +
-> Nuclear weapons *have wrought a revolution* in international relations.
核武器已经使国际关系发生了变革。

- dreary => 来自PIE*dhreu, 滴，掉落，词源同drip, drop. 原义为滴血的，引申义沉闷的，阴深的。
- liquidate => 来源于拉丁语动词liquere“清澈”、“清楚”的意义。 词根词缀： -liqu-液体→清澈,清楚 + -id形容词词尾 + -ate动词词尾 /来自liquid,流动，液体。用于经济学资产的流动性，清算，清偿等。
- stingy => sting,刺，叮，蜇，-y,形容词后缀。俚语。
- languish => 来自PIE*sleg,松的，松散的，词源同lax,slack.引申词义松软无力的，消瘦的，后用来指长期受苦，煎熬。
====

四十年的工作压迫和思想灌输所造成的伤害, 不可能一蹴而就地解决。但是，在"个人能动性"遭到无情践踏的社会中长大的人，不得不面临突然要适应资本主义的严酷的环境。不出所料，许多人做不到。宾德先生被解雇了，还有成千上万的人也被解雇了，他们之前都在政府支持的安全、沉闷、低效的岗位上辛勤工作。尽管试图拯救它(原工作岗位)，包括大规模的抗议和绝食抗议，钾矿还是被关闭了 ——这是东部8500家被私有化, 或被新的政府机构Treuhand清算的公司之一。 +
宾德先生曾在一段时间中做过各种零工，但最终在德国最吝啬的失业救济金Hartz IV上, 结束了自己的职业生涯。和许多东德妇女一样，他的妻子接受了再培训，并前往西德工作。当被问及对祖国统一的看法时，他耸了耸肩。“我以往的安稳工作没有了。对我来说，东德却可以继续前进。”


There was no manual 使用手册；说明书 *to guide* the absorption(`=the process of a smaller group, country, etc. becoming part of a larger group or country`) of east into west. ② `主` The policies that *failed*(`= to disappoint sb; to be unable to help when needed`) people like Mr Binder `谓` *were always going to be subject to*(`=to make sb/sth experience, suffer or be affected by sth, usually sth unpleasant 使经受；使遭受`) fierce(a.)(`=showing strong feelings or a lot of activity, often in a way that is violent`) dispute(`=an argument or a disagreement between two people, groups or countries; discussion about a subject where there is disagreement`). ③ `主` The surprise, as Germany *approaches*(`=to come near to sb/sth in distance or time`) the 30th anniversary 周年纪念日 of the fall of the Wall, `系` *is* the speed with which these debates *have roared(`=to make a very loud, deep sound; /to move very fast, making a lot of noise`) back into* the public sphere(`=an area of activity, influence or interest; a particular section of society 范围；领域；阶层；界`). ④ Newspapers and magazines *are full of* reassessments(`=you think about it and decide whether you need to change your opinion about it 重新评价`) of the Wiedervereinigung(`=德语, 意思就是英文中的reunification 重新统一`) (reunification); westerners *are lapping up*(`=to accept or receive sth with great enjoyment, without thinking about whether it is good, true or sincere`) memoirs 回忆录 and polemics(n.)(`=a speech or a piece of writing that argues very strongly for or against sth/sb`) by eastern authors. ⑤ Never before 以前从未有过;破天荒 *has* Germany *debated* its reunification [with such vigour(`=energy, force or enthusiasm`)]. Why?

====
- fail : v. *to disappoint sb; to be unable to help when needed* 使失望；有负于；无能为力 +
-> When he lost his job, he felt *he had failed(v.) his family*. 他失去工作以后，感到辜负了他的家庭。

- subject : V-T If you *subject* someone *to* something unpleasant, *you make them experience it*. 使遭受 +
->  ...the man *who had subjected her to four years of beatings and abuse*. …那个使她遭受了4年殴打和辱骂的男人。

-  *lap sth up* : +
(1) ( informal ) *to accept or receive sth with great enjoyment, without thinking about whether it is good, true or sincere* （不加考虑地）乐于接受 +
(2) *to drink all of sth with great enjoyment* 开怀畅饮 +
-> It's a terrible movie but audiences everywhere *are lapping it up*. 这是一部很糟糕的电影，可各地的观众却趋之若鹜。
====

没有手册来指导东方如何被合并入西方。像"导致宾德先生这样的人融入西德失败"的政策, 总是会引起激烈的争论。令人惊讶的是，在德国即将迎来柏林墙倒塌30周年之际，这些辩论以如此快的速度重新进入公共领域。报纸和杂志上充斥着对统一的重新评价;西方人对东方作家的回忆录和论辩津津乐道。德国从未如此激烈地讨论过统一问题。为什么?

Many observers *say* {the debate *grew louder* three or four years ago}. ② The most obvious explanation *is* therefore(`=used to introduce the logical result of sth that has just been mentioned 因此；所以；因而`) the migrant crisis of 2015-16. ③ Petra Köpping, the integration(`=the act or process of *mixing* people who have previously been separated, usually because of colour, race, religion, etc) minister in Saxony, one of the five eastern states (*established* at reunification), *says* that {when she *tried to explain to* her constituents(n.)(`=a person who lives, and can vote in a constituency`)) why the state *was helping refugees*, some *replied*: “*Integrate us* first!”} ④ Many easterners *resented*(`=to feel bitter or angry about sth, especially because you feel it is unfair`) the resources *being devoted to help* newcomers [when they *felt* left behind]. ⑤ They also *disliked* the labelling of their complaints *as* racist 种族主义者.

====
- resent => re-回,向后;相反,反对 + -sent-感觉 → 反感 /re-,表强调，-sent,感觉，感知，词源同 sense,consent.即强烈的感觉，后引申词义气愤，愤恨。
====

许多观察人士说，三、四年前，争论的声音越来越大。因此，最明显的解释是由2015-16年的移民危机所带来的。萨克森州,是德国统一时建立的五个东部州之一，该州融合部部长佩特拉•克索普(Petra k)表示，当她试图向选民解释为何政府要帮助难民时，一些人回答说:“首先让我们融入!". 许多原东德人, 对把资源用于帮助新的移民, 而自己却不被重视, 而感到不满。他们也不喜欢他们的投诉被贴上种族主义的标签。

But the refugee crisis *merely triggered*(`=to make sth happen suddenly`) a deeper shift(`=a change in position or direction`), *says* Christian Hirte, the government’s special commissioner(`=a member of a commission`) 特别专员 for east Germany. ② `主` One idea, *floated(`=to suggest an idea or a plan for other people to consider`) by* Angela Merkel, `主` who (*as* chancellor(`=the head of government in Germany or Austria`)) `系` *is* east Germany’s best-known 最有名的 export(`=a product that is sold to another country`), `系` *is* that {the east *is undergoing* something *comparable to* the experience of West Germany in 1968, when children *forced* their parents *to account for*(`=to give an explanation of sth`) their activities in the Nazi period}. ③ Now, the argument *runs*, young east Germans *seek explanations for* what *happened to* their parents in the early years of reunification. ④ “The long-term wounds *were concealed*(`=to hide sb/sth`) because people *were absorbed*(v.)(`=very interested in sth/sb so that you are not paying attention to anything else`) finding(a.) a place in the new society,” *says* Steffen Mau of Humboldt University in Berlin. “Perhaps you *need* 25 years *to realise(`=realize`)* this.”

政府的东德特别专员Christian Hirte说, 难民危机仅仅是触发了更深层次的转变。德国总理安格拉•默克尔(Angela Merkel)提出的一个观点是，东德正在经历类似于1968年西德的经历，当时孩子们强迫父母对他们在纳粹时期的活动做出解释。默克尔是东德最知名的"出口产品"。现在，争论继续着，年轻的东德人正在为他们的父母在统一初期的遭遇,寻找解释。柏林洪堡大学的Steffen Mau说:“长期的创伤被掩盖了，因为人们全神贯注于在新社会中寻找一个位置。”“也许你需要25年才能意识到这一点。”

This summer Marie-Sophie Schiller, a young Leipziger 莱比锡人 who *hosts*(`=to organize an event to which others are invited and make all the arrangements for them`) a podcast(`=A podcast is an audio file similar to a radio broadcast, that can be downloaded and listened to on a computer or iPod. 播客`) *called* “East -- A Guide”, *had an “emotional”(`=causing people to feel strong emotions`) talk with* her parents about their experiences after 1990. ② She *was astonished(`=very surprised about it`) to learn about* their daily hardships(`=a situation that is difficult and unpleasant because you do not have enough money, food, clothes, etc`) and humiliations(`=the embarrassment and shame you feel when someone makes you appear stupid, or when you make a mistake in public`). ③ Stefan Meyer, an activist(`=a person who works to achieve political or social change, especially as a member of an organization with particular aims`) who *grew up* in East Berlin, *remembers* {watching `主` his parents’ confidence `谓` *ebb*(`=to become gradually weaker or less`) as they *struggled to find their feet* (婴儿)能站立(或行走);能独立行动;在社会上站稳脚跟 in the new country}.

====
- *find one's foot* : (1).(婴儿)能站立(或行走) +
(2).[英国英语]站住脚；立足，确立地位，扎下根来；能独立地工作(或行动)；在社会上站稳脚跟；意识到自己的能力 +
(3).(病人)能下床行走，腿开始恢复功能
====

今年夏天，年轻的莱比锡人玛丽-索菲•席勒(Marie-Sophie Schiller)主持了一个名为“东方指南”(easta - Guide)的播客节目，她与父母就1990年后的经历, 进行了一次“具有感染力”的谈话。她惊讶地了解到他们日常的艰辛和屈辱。斯特凡·迈耶(Stefan Meyer)是一名在东柏林长大的社会活动人士，他还记得，当他的父母努力在这个新国家站稳脚跟时，他们的信心在减退。


After 1990 “the whole software of life *changed*” for east Germans, *says* Markus Kerber, a bigwig(`=an important person`) at the interior(`=a country's own affairs rather than those that involve other countries`) ministry. ② Short-term pain *was* inevitable. ③ Average labour productivity in the east *was* 30% of that in the west. ④ `主` Kohl’s decision *to exchange* Ostmarks *at* a 1:1 rate *for* Deutschmarks `谓` *made* swathes(`=a large strip or area of sth`) of firms *uncompetitive*(a.) (`=无竞争力的`) overnight. ⑤ `主` Those (that survived) `谓` *struggled with* the western rules (they *had to import [wholesale]*(a./ad.)(`= happening or done to a very large number of people or things 大规模的`)). ⑥ By one estimate, 80% of east Germans [at some point] *found* themselves *out of work*.


====
- bigwig : big, 大。wig, 假发。过去假发象征着一种社会地位。
====

1990年后，对于东德人来说，“整个生活的"软件"都改变了”，德国内政部要员Markus Kerber说。短期的痛苦是不可避免的。东部的平均劳动生产率只有西部的30%。科尔决定以1:1的比率兑换德国马克，这使得许多公司一夜之间失去了竞争力。那些幸存下来的公司,不得不大量接受西德的规则, 并与之作斗争。据估计，在某种程度上(在某一时刻), 80%的东德人都失去了工作。


Perhaps the Treuhand *could have proceeded(`=to continue doing sth that has already been started; to continue being done`) more gently*, some *argue* today. ② Maybe the unified country *should have developed* a new constitution(`=the system of laws and basic principles that a state, a country or an organization is governed by`) rather than *simply extending* the western one [eastwards](`=towards the east`). ③ The west *might have learned from* the more enlightened 开明的；有见识的；摆脱偏见的 aspects of life in the GDR, *such as* free child care /and *encouraging* women *to work* outside the home. ④ Radical(`=in favour of thorough and complete political or social change`) parties 激进党 on left and right *take such arguments [to a ludicrous(`=unreasonable; that you cannot take seriously`) extreme]*, *arguing* that {reunification *was* the “colonisation” of a bewildered(a.)(`=very confused and cannot understand something or decide what you should do`) people by an exploitative(a.)(`= treating sb unfairly in order to gain an advantage or to make money 剥削的；榨取的`) west}.

====
- exploit => ex-, 向外。-ploit, 卷，词源同imply, implicate. 即展开，结果，功绩。后在19世纪初由于法国空想社会主义者，尤其是圣西门用该词指剥削，压榨，使得这一词义广泛传播。
====

今天，一些人认为，也许特鲁汉的行动本可以更温和一些。也许统一后的国家应该制定一部新宪法，而不是简单地将西部片东扩。西方可能已经从民主德国生活中比较开明的方面学到了东西，比如免费的儿童看护和鼓励妇女外出工作。左翼和右翼的激进派, 将这种观点发挥到了可笑的极端，他们认为，"统一"是这样一种行为 -- 一个充满剥削的西德, 对不知所措的东德人民的“殖民”。

Understanding(n.)(`=the knowledge that sb has about a particular subject or situation`) required

Such views *tap(`=to hit sb/sth quickly and lightly`) into a feeling* among many easterners (that they *have struggled to take back control of* their own destiny). ② Ms Köpping *says* east Germans *hold* barely 4% of elite jobs in the east. ③ Many *rent flats*(`=a set of rooms for living in, including a kitchen, usually on one floor of a building 公寓；单元房`) from westerners, who *own* much of the eastern housing stock(`=a supply of sth that is available for use`). ④ “Sometimes east Germans *feel* that they’*re ruled by* others, not themselves,” says Klara Geywitz, a Brandenburger *running*(`=to be a candidate in an election for a political position, especially in the US`) to lead Germany’s Social Democrats. ⑤ Nor *have* east Germans *stormed*(`=to suddenly attack a place; /to say sth in a loud angry way`) the national citadels （旧时的）城堡，要塞，堡垒 of power. ⑥ [Almost 14 years after she *took office* 就职;上任] Mrs Merkel -- and Joachim Gauck, president from 2012-17 -- *remain* exceptions(`=a person or thing that is not included in a general statement`) *rather than* a vanguard(`=the leaders of a movement in society, for example in politics, art, industry, etc`). ⑦ Rarely one *to dwell on*(`= to think or talk a lot about sth, especially sth it would be better to forget`) her origins, Mrs Merkel *has lately begun to reflect(`=to think carefully and deeply about sth`) publicly on* the mixed(`=having both good and bad qualities or feelings`) legacy 遗产 of reunification. ⑧ “We *must all… learn to understand* why [for many people in east German states], German unity *is not* solely(`=only; not involving sb/sth else`) a positive experience,” she said on October 3rd.

====
- *Understanding : (n.) ~ (of sth)* :the knowledge that sb has about a particular subject or situation 理解；领悟；了解
-> The committee *has little or no understanding of the problem*. 委员会对这个问题了解不多或根本不了解。

- elite => 来自法语。e-, 向外。-lit, 选出，字母c脱落，词源同eligible, elect.

- *run : v. ~ (for sb/sth) +
~ (in sth)* : to be a candidate in an election for a political position, especially in the US （尤指在美国）参加竞选 +
-> to run for president 竞选总统 +
-> to run in the election 参加竞选

- citadel => 词源同city,城市，城堡。
- vanguard => 来自法语 avant-garde,先锋，先头部队，avant,前面，为 advance 原型，garde,护卫，词源同 guard.
====

这种观点, 扣进了很多东德人的心扉 -- 他们一直在努力重新掌握自己的命运。Köpping女士说,在东德的精英工作中, 东德人却占有4%的位置。许多东德人从西德人那里租房子，后者握有大量给东德人的住房供应。“有时候东德人觉得他们被别人掌握着命运，而不是他们自己。”勃兰登堡人(Brandenburger) Klara Geywitz, 他(竞选?)领导德国的社会民主党, 说, 东德人也没有攻占国家权力中心。默克尔就任总统近14年后，默克尔,和2012-17年的总统约阿希姆•高克,仍然是例外，而不是先锋。很少有人对默克尔的出身耿耿于怀，但她最近开始公开反思德国统一留下的复杂遗产。她在10月3日表示:“我们必须……学会理解，为什么对于东德各州的许多人来说，两德统一并不只是一种积极的体验。”


One obstacle(`=an object that is in your way and that makes it difficult for you to move forward`) to such understanding *is* that Germans *view* reunification [*differently*]. ② Half of west Germans *consider* the east a success. ③ Two-thirds of east Germans *disagree*. ④ Many westerners *were oblivious(a.)(`=not aware of sth`) to* the upheaval(n.)(`=a big change that causes a lot of confusion, worry and problems`) their new compatriots(`=a person who was born in, or is a citizen of, the same country as sb else 同胞；同国人`) *endured*(`=to experience and deal with sth that is painful or unpleasant, especially without complaining 忍耐；忍受`). ⑤ “On October 4th 1990 [=the day after reunification], [after a night of partying] I *carried on(`=to continue moving/doing`) my life* as normal,” says Mr Kerber. “Not a single east German *had* the same experience.” ⑥ [In places] western stereotypes(`=a fixed idea or image that many people have of a particular type of person or thing, but which is often not true in reality 刻板印象`) of easterners *have persisted*(`=to continue to exist`), the Jammerossi (=“complaining easterner”), ungrateful(`=not showing or expressing thanks for sth that sb has done for you or given to you`) for the largesse(`=the act or quality of being generous with money; money that you give to people who have less than you`) *showered* on the east after unification, or Dunkeldeutschland (=“dark Germany”), a cold-war term 术语 *implying* backwardness(`=the state of having made less progress than normal`). ⑦ More recent *is* the notion(`=an idea, a belief or an understanding of sth`) of the east *as* a cradle(`=the place where sth important began 摇篮;策源地；发源地`) of neo-Nazism 新纳粹主义, *bolstered(`=to improve sth or make it stronger`) by* the strength there of the far-right 极右派的 Alternative for Germany (AfD) 德国选择党. ⑧ Portrayals(n.)(`=the act of showing or describing sb/sth in a picture, play, book, etc.; a particular way in which this is done`) of the east in Germany’s national (for which read western) media *have often read like* dispatches(n.)(`=a report sent to a newspaper by a journalist who is working in a foreign country`) from an exotic(`=from or in another country, especially a tropical one; seeming exciting and unusual because it is connected with foreign countries`), troubled(`=having a lot of problems`) land, where the far right 极右翼分子 *are always marching* 游行示威；游行抗议 in the streets /or *thumping*(`=to hit sb/sth hard, especially with your closed hand`) immigrants.

====
- *oblivious (a.) ~ (of/to sth)* : not aware of sth 不知道；未注意；未察觉 +
=> oblivious => 来自ob-,相对，对着的，-lino,涂抹，词源同liniment,delete,obliterate.比喻用法。 +
=> He drove off, *oblivious(a.) of* the damage he had caused. 他车开走了，没有注意到他所造成的损害。

- upheaval => up,向上，heave,举起。引申词义剧变，动乱。
- compatriot => com-, 强调。-patri, 父亲，词源同father. 即同宗同祖的。

- bolster : V-T If you bolster something such as someone's confidence or courage, *you increase it*. 增强 +
=> 词源同ball, 原来指鼓起来的垫子，枕头，护垫等，主要作名词使用。后来做动词使用，指支持，保护。 +
-> Hopes of an early cut in interest rates *bolstered confidence*. 提前降低利率的希望增强了信心。

- thump => 可能来源于对锤击声音的模拟。 词根词缀： th + -ump名词词尾
====

这种理解的一个障碍是，德国人对统一的看法不同。半数西德人认为东德是成功的。三分之二的东德人却不同意。许多西德人没有注意到他们的新同胞所经历的剧变。“1990年10月4日(两德统一后的那一天)，在一个晚上的聚会后，我照常生活，”克贝尔说。没有一个东德人有同样的经历。在一些地方，西方对东方人的刻板印象依然存在，如“抱怨的东方人”(Jammerossi)、“忘恩负义的东方人”(ungrateful for the largesered on the east after unification)，或“黑暗的德国”(Dunkeldeutschland)，这是一个冷战时期的术语，意指落后。更近一些的观点认为，东方是新纳粹主义的摇篮，而极右翼的德国新选择党(AfD)则是新纳粹主义的摇篮。德国国家媒体对东德的描述，读起来常常像是从一个充满异域风情、动荡不安的国度发来的报道，极右翼分子总是在街上游行，或者是殴打移民。


Such accounts(n.)(`=a written or spoken description of sth that has happened`) *risk ignoring* the huge strides(n.)(`=one long step; the distance covered by a step`) *made by* east Germany since reunification. ② Citizens *were liberated(`=to free a country or a person from the control of sb else`) from* the humiliations(`=the embarrassment and shame you feel when someone makes you appear stupid, or when you make a mistake in public`) of life in a surveillance state. ③ They *were allowed to choose* their leaders, *express* their opinions /and *travel, to* west Germany and beyond. ④ Economically, despite the hardships of the early years, the east *soon began to converge(`=to move towards a place from different directions and meet`) with* the west, and life *improved drastically*(`=extreme in a way that has a sudden, serious or violent effect on sth`) across a range of measures. ⑤ Today some east German regions *have* lower unemployment rates *than* western post-industrial 后工业化的；不再依赖重工业的 regions like the Saarland 德国州名 or the Ruhr valley(`=an area of low land between hills or mountains, often with a river flowing through it; the land that a river flows through`). ⑥ `主` West-east transfers(`=the act of moving sb/sth from one place, group or job to another; an occasion when this happens`) of close to €2trn(`=TRILLION 万亿，兆`) ($2.2trn) `谓` *have reduced* the infrastructure 基础设施 gap. (Today they *run* at around €30bn(`=billion 十亿`) a year, mainly in the form of social-security 社会保险，社会保障 payments.) ⑦ Wages in the east *now stand(`= to be in a particular condition or situation`) at* around 85% of the level in the west, and the cost of living *is* lower. ⑧ The life-expectancy gap *has closed*(`=to make the distance or difference between two people or things smaller; to become smaller or narrower`), the air *is* cleaner, the buildings smarter. ⑨ According to Allensbach, a pollster(`=a person who makes or asks the questions in an opinion poll`), 53% of east Germans *are content with* their personal economic situation, the same figure *as* 像；如同 in the west. “It all *worked(`=to have a particular effect`) surprisingly well*, but this story *doesn’t fly*(`=to be talked about by many people`) in the east,” says Werner Jann of the University of Potsdam 波茨坦（德国北方都市）.

====
- *converge : v. ~ (on...)* ( of people or vehicles 人或车辆 ) (1) *to move towards a place from different directions and meet* 汇集；聚集；集中 +
(2) V-I If roads or lines converge, *they meet or join at a particular place*. (道路、江河等) 会合 +
(3) if ideas, policies, aims, etc. converge , *they become very similar or the same* （思想、政策、目标等）十分相似，相同 +
=> con-, 强调。-verge, 转，词源同diverge, versus. 即转到一起，汇集。 +
-> Thousands of supporters *converged(v.) on London* for the rally. 成千上万的支持者从四面八方汇聚伦敦举行集会。

- drastic => 来自drama, 戏剧。引申义戏剧般的，急剧的。

- transfer : n. *the act of moving sb/sth from one place, group or job to another; an occasion when this happens* 搬迁；转移；调动；变换 +
-> *the transfer of currency* from one country to another 货币从一国到另一国的汇划 +
-> After the election *there was a swift transfer of power* . 大选之后权力迅速交接。

- *stand v. : ~ at sth* : to be at a particular level, amount, height, etc. 达特定水平（或数量、高度等） +
-> Interest rates *stand at 3%*. 利率为3%。
====

这种说法可能会忽视东德自统一以来取得的巨大进步。在一个被监视的国家里，公民从生活的屈辱中解放出来。他们被允许选择自己的领导人，表达自己的意见，并到西德及其他地方旅行。在经济上，尽管早年困难重重，但东方很快就开始与西方趋同，通过一系列措施，生活水平大幅提高。如今，一些东德地区的失业率比萨尔地区或鲁尔河谷等后工业化地区要低。西-东转移近2万亿欧元(合2.2万亿美元)，缩小了基础设施缺口。(如今，他们每年的支出约为300亿欧元，主要是社会保障支出。)东部地区的工资水平, 目前约为西部地区的85%，生活成本也较低。预期寿命的差距缩小了，空气更清洁了，建筑物更智能了。根据民意调查公司阿伦斯巴赫(Allensbach)的数据，53%的东德人对他们的个人经济状况感到满意，这一数字与西方相同。波茨坦大学的Werner Jann说:“这一切都出人意料地奏效，但这个故事在东方行不通。”


One of the best

Last year Andrea Boltho, Wendy Carlin and Pasquale Scaramozzino, three economists, contrasted east Germany’s post-reunification performance favourably with the Mezzogiorno in Italy, where GDP per person remains little over half that of the north. Perhaps the most apt comparison is with other parts of Europe that shook off communism. East Germany’s per capita growth has outstripped most other eastern European countries (see chart), despite starting from a higher base. As Richard Schröder, a former East German dissident, notes, the application of western laws and practices saw off the threat of oligarchic corruption that has plagued many of Germany’s eastern neighbours.

====
-
====

Yet if east Germans do not always appreciate their good fortune, it is because their reference points have been Hamburg and Munich, not Bratislava or Budapest. Implicit in the promise of reunification was a pledge that east Germans could finally enjoy what they had so long envied in the west. For years they were forced to witness a lifestyle that remained out of reach, in the packets of coffee and sweets sent by relatives in the west, the western goods on display in Intershop outlets accessible only to those with hard currency, or the commercials on western television beamed across the border. In 1990 Chancellor Kohl promised east Germans “blooming landscapes”. Instead they got deindustrialisation and mass unemployment. “In 1990 300,000 people came to shout ‘Helmut!’ on Augustusplatz [in Leipzig],” recalls Kurt-Ulrich Mayer, who helped establish Kohl’s Christian Democratic Union (CDU) in Saxony. “Four years later he came back, and we needed umbrellas to protect him from all the eggs and tomatoes.” Unlike Poles or Hungarians, east Germans had someone else to blame when things went wrong.

The convergence between west and east eventually ground to a halt. Today just 7% of Germany’s most-valued 500 companies (and none listed in the DAX30 index) are headquartered in the east. This starves municipalities of tax revenue and contributes to the east-west productivity gap, which has stood at around 20% for 20 years. Most assets liquidated by the Treuhand fell into western or foreign hands, hindering the development of an eastern capitalist class.

For many, the best way to get western lifestyles was to move west. Over one-quarter of east Germans aged 18-30 did so, two-thirds of them women. Rural parts of the east were especially affected. As towns and villages emptied and tax revenues slumped, schools were closed, shops shuttered and housing blocks demolished. The mass emigration of youngsters led to a plummeting number of births. Since 2017 net east-west migration has been roughly zero, but there has been no growth in the number of people moving east; the westward exodus has simply fallen to match it.

The east is also much older than the west. Since 1990 the number of over-60s there has increased by 1.3m even as the overall population has fallen by 2.2m. IWH, a research outfit in Halle, thinks the working-age population in the east will fall by more than a third by 2060. By 2035, 23 of Germany’s 401 Kreise (administrative districts) will have shrunk by at least a fifth, says Susanne Dähner at the Berlin Institute for Population and Development; all of them are in the east. In some districts, there will be four funerals for every birth. Instead of losing people to the west, eastern Germany will lose them to the grave.

The constitutional pledge of “equivalent living conditions” across Germany thus looks unattainable. The government tries to help so-called “structurally weak” regions, in the east as well as the west. But although investment in infrastructure or technical universities may help some towns, it cannot stop the demographic decline in many east German regions.

Coming to terms

The picture is much brighter in some eastern cities. Potsdam, Jena and Dresden have clusters of industry and tourism as well as cheap housing; some, like Leipzig (“Hypezig”, to irritated locals), have been booming for years. The “bacon belt” around Berlin benefits from the success of the capital, especially as older workers move out to the suburbs. Yet even as overall emigration to the west dries up, eastern cities are sucking educated people away from already struggling small towns and villages. That trend may continue, as only half of east German workers work in cities, compared with three-quarters in the west.



The changes in the east have social, cultural and political consequences which are now coming to the fore. Last February thousands of Dynamo Dresden supporters at an away game in Hamburg began an unfamiliar chant: “Ost [east], Ost, Ostdeutschland!” A video of the episode went viral, sparking a lively debate: were the fans expressing a dubious “eastern” variant of militant German nationalism? Or was this a cheerful reappropriation of an identity that for so long was taken to connote stupidity and closed-mindedness?

“Identity is key to understanding east Germany,” says Franziska Schubert, a thoughtful Green who represents Görlitz in Saxony’s state parliament. Fully 47% of east Germans say they identify as easterners before Germans, a far higher proportion than at the euphoric moment of reunification. (The equivalent is true for 22% of westerners.) Regional identity is hardly abnormal in Germany—ask the Bavarians—but in the east it can seem grounded in politics as much as culture or tradition.

When Jana Hensel, a writer, recently gave a talk to a school in her home town of Leipzig, she was astonished to find herself spending half an hour fielding questions from teenagers about an Ossiquote (a proposal to give east Germans preference in public jobs). “More than 25 years after the end of the GDR, students have become east German again,” she says. “If we’re not careful, we’ll lose another generation.”

The AfD has exploited the power of eastern particularism. Under slogans like “The east rises up!” the party has scored 20%-plus in eastern state elections, most recently in Thuringia on October 27th. There, and in recent elections in Brandenburg and Saxony, it was only voters over 60 whose support for the established parties ensured that the AfD did not come first. In Saxony and Thuringia the AfD was the most popular party among under-30s. This is worrying in a part of the country where extremism has found fertile ground. More than half of Germany’s hate crimes take place in the east, though it has just 20% of the population and few immigrants.

But eastern identity is not the exclusive preserve of extremes. Many young easterners simply developed an “Ossi” identity after encountering ignorance or scorn in the west. Nor need it be only negative. Matthias Platzeck, a former Brandenburg premier now in charge of a commission for the 30th anniversary of reunification, says that the recent election in his state was the worst-tempered ever. Nonetheless, he hopes for the emergence in the east of healthy self-confidence, built on the back of success stories—and a new focus on the many problems that span east and west. His commission’s informal motto, he says, is “as little state celebration as necessary, as much discussion as possible.” And since the Berlin Wall has gone, no amount of debate will land anyone in jail.



---


== 04 - Thirty years after the Berlin Wall fell 纯净版

Germans still don’t agree on what reunification meant

Discontent may even be growing



Nov 2nd 2019 | BERLIN, BISCHOFFERODE AND LEIPZIG

ON NOVEMBER 9TH 1989, as the Berlin Wall tumbled, Hans-Joachim Binder was on night shift at the potash mine in Bischofferode, a village in the communist-ruled German Democratic Republic. Mr Binder, a maintenance worker who had toiled in the mine for 17 years, had no idea of the momentous events unfolding 240km (150 miles) to the east. The first sign something was up was when most of his colleagues disappeared to investigate what was happening at the border with West Germany, just ten minutes’ drive away. Only three returned to complete their shift.

Less than a year later Germany was reunited, capping one of the most extraordinary stories in modern history. Not only had a communist dictatorship collapsed, releasing 16m people from the fear of the Stasi (secret police) and the stultification of censorship. Unlike any other country ever freed from tyranny, the entire population of East Germany was given citizenship of a big, rich democracy. As a grand, if ill-fated, gesture of welcome the West German chancellor, Helmut Kohl, converted some of their worthless savings into hard currency at the preposterously generous exchange rate of one Deutschmark to one Ostmark.

More than 1m Ossies took advantage of their new freedom by moving to the West, where most thrived. Official statistics no longer counted this group—who were disproportionally young, clever, female and ambitious—as East Germans. For those who stayed behind, however, the 30 years since the fall of the Wall have been a mix of impressive progress, often taken for granted, and sour disappointment.

A price to pay

The harm wrought by four decades of oppression and indoctrination could not be undone overnight. But a people brought up in a society where initiative was ruthlessly crushed had to adapt suddenly to the rigours of capitalism. Unsurprisingly, many could not. Mr Binder was laid off. So were hundreds of thousands of others who previously toiled in safe, dreary and unproductive state-backed jobs. Despite attempts to save it, including large protests and a hunger strike, the potash mine was shut down—one of 8,500 companies in the east privatised or liquidated by the Treuhand, a new government agency. Mr Binder bounced around in odd jobs for a while, eventually winding up on Hartz IV, the stingiest of Germany’s unemployment benefits, where he languishes today. Like many East German women, his wife retrained and left for a job in the west. Asked how he feels about the reunification of his country, he shrugs. “My safe job was gone. For me, the GDR could have carried on.”

There was no manual to guide the absorption of east into west. The policies that failed people like Mr Binder were always going to be subject to fierce dispute. The surprise, as Germany approaches the 30th anniversary of the fall of the Wall, is the speed with which these debates have roared back into the public sphere. Newspapers and magazines are full of reassessments of the Wiedervereinigung (reunification); westerners are lapping up memoirs and polemics by eastern authors. Never before has Germany debated its reunification with such vigour. Why?

Many observers say the debate grew louder three or four years ago. The most obvious explanation is therefore the migrant crisis of 2015-16. Petra Köpping, the integration minister in Saxony, one of the five eastern states established at reunification, says that when she tried to explain to her constituents why the state was helping refugees, some replied: “Integrate us first!” Many easterners resented the resources being devoted to help newcomers when they felt left behind. They also disliked the labelling of their complaints as racist.

But the refugee crisis merely triggered a deeper shift, says Christian Hirte, the government’s special commissioner for east Germany. One idea, floated by Angela Merkel, who as chancellor is east Germany’s best-known export, is that the east is undergoing something comparable to the experience of West Germany in 1968, when children forced their parents to account for their activities in the Nazi period. Now, the argument runs, young east Germans seek explanations for what happened to their parents in the early years of reunification. “The long-term wounds were concealed because people were absorbed finding a place in the new society,” says Steffen Mau of Humboldt University in Berlin. “Perhaps you need 25 years to realise this.”

This summer Marie-Sophie Schiller, a young Leipziger who hosts a podcast called “East—A Guide”, had an “emotional” talk with her parents about their experiences after 1990. She was astonished to learn about their daily hardships and humiliations. Stefan Meyer, an activist who grew up in East Berlin, remembers watching his parents’ confidence ebb as they struggled to find their feet in the new country.

After 1990 “the whole software of life changed” for east Germans, says Markus Kerber, a bigwig at the interior ministry. Short-term pain was inevitable. Average labour productivity in the east was 30% of that in the west. Kohl’s decision to exchange Ostmarks at a 1:1 rate for Deutschmarks made swathes of firms uncompetitive overnight. Those that survived struggled with the western rules they had to import wholesale. By one estimate, 80% of east Germans at some point found themselves out of work.

Perhaps the Treuhand could have proceeded more gently, some argue today. Maybe the unified country should have developed a new constitution rather than simply extending the western one eastwards. The west might have learned from the more enlightened aspects of life in the GDR, such as free child care and encouraging women to work outside the home. Radical parties on left and right take such arguments to a ludicrous extreme, arguing that reunification was the “colonisation” of a bewildered people by an exploitative west.

Understanding required

Such views tap into a feeling among many easterners that they have struggled to take back control of their own destiny. Ms Köpping says east Germans hold barely 4% of elite jobs in the east. Many rent flats from westerners, who own much of the eastern housing stock. “Sometimes east Germans feel that they’re ruled by others, not themselves,” says Klara Geywitz, a Brandenburger running to lead Germany’s Social Democrats. Nor have east Germans stormed the national citadels of power. Almost 14 years after she took office Mrs Merkel—and Joachim Gauck, president from 2012-17—remain exceptions rather than a vanguard. Rarely one to dwell on her origins, Mrs Merkel has lately begun to reflect publicly on the mixed legacy of reunification. “We must all…learn to understand why for many people in east German states, German unity is not solely a positive experience,” she said on October 3rd.



One obstacle to such understanding is that Germans view reunification differently. Half of west Germans consider the east a success. Two-thirds of east Germans disagree. Many westerners were oblivious to the upheaval their new compatriots endured. “On October 4th 1990 [the day after reunification], after a night of partying I carried on my life as normal,” says Mr Kerber. “Not a single east German had the same experience.” In places western stereotypes of easterners have persisted, the Jammerossi (“complaining easterner”), ungrateful for the largesse showered on the east after unification, or Dunkeldeutschland (“dark Germany”), a cold-war term implying backwardness. More recent is the notion of the east as a cradle of neo-Nazism, bolstered by the strength there of the far-right Alternative for Germany (AfD). Portrayals of the east in Germany’s national (for which read western) media have often read like dispatches from an exotic, troubled land, where the far right are always marching in the streets or thumping immigrants.

Such accounts risk ignoring the huge strides made by east Germany since reunification. Citizens were liberated from the humiliations of life in a surveillance state. They were allowed to choose their leaders, express their opinions and travel, to west Germany and beyond. Economically, despite the hardships of the early years, the east soon began to converge with the west, and life improved drastically across a range of measures. Today some east German regions have lower unemployment rates than western post-industrial regions like the Saarland or the Ruhr valley. West-east transfers of close to €2trn ($2.2trn) have reduced the infrastructure gap. (Today they run at around €30bn a year, mainly in the form of social-security payments.) Wages in the east now stand at around 85% of the level in the west, and the cost of living is lower. The life-expectancy gap has closed, the air is cleaner, the buildings smarter. According to Allensbach, a pollster, 53% of east Germans are content with their personal economic situation, the same figure as in the west. “It all worked surprisingly well, but this story doesn’t fly in the east,” says Werner Jann of the University of Potsdam.

One of the best



Last year Andrea Boltho, Wendy Carlin and Pasquale Scaramozzino, three economists, contrasted east Germany’s post-reunification performance favourably with the Mezzogiorno in Italy, where GDP per person remains little over half that of the north. Perhaps the most apt comparison is with other parts of Europe that shook off communism. East Germany’s per capita growth has outstripped most other eastern European countries (see chart), despite starting from a higher base. As Richard Schröder, a former East German dissident, notes, the application of western laws and practices saw off the threat of oligarchic corruption that has plagued many of Germany’s eastern neighbours.

Yet if east Germans do not always appreciate their good fortune, it is because their reference points have been Hamburg and Munich, not Bratislava or Budapest. Implicit in the promise of reunification was a pledge that east Germans could finally enjoy what they had so long envied in the west. For years they were forced to witness a lifestyle that remained out of reach, in the packets of coffee and sweets sent by relatives in the west, the western goods on display in Intershop outlets accessible only to those with hard currency, or the commercials on western television beamed across the border. In 1990 Chancellor Kohl promised east Germans “blooming landscapes”. Instead they got deindustrialisation and mass unemployment. “In 1990 300,000 people came to shout ‘Helmut!’ on Augustusplatz [in Leipzig],” recalls Kurt-Ulrich Mayer, who helped establish Kohl’s Christian Democratic Union (CDU) in Saxony. “Four years later he came back, and we needed umbrellas to protect him from all the eggs and tomatoes.” Unlike Poles or Hungarians, east Germans had someone else to blame when things went wrong.

The convergence between west and east eventually ground to a halt. Today just 7% of Germany’s most-valued 500 companies (and none listed in the DAX30 index) are headquartered in the east. This starves municipalities of tax revenue and contributes to the east-west productivity gap, which has stood at around 20% for 20 years. Most assets liquidated by the Treuhand fell into western or foreign hands, hindering the development of an eastern capitalist class.

For many, the best way to get western lifestyles was to move west. Over one-quarter of east Germans aged 18-30 did so, two-thirds of them women. Rural parts of the east were especially affected. As towns and villages emptied and tax revenues slumped, schools were closed, shops shuttered and housing blocks demolished. The mass emigration of youngsters led to a plummeting number of births. Since 2017 net east-west migration has been roughly zero, but there has been no growth in the number of people moving east; the westward exodus has simply fallen to match it.

The east is also much older than the west. Since 1990 the number of over-60s there has increased by 1.3m even as the overall population has fallen by 2.2m. IWH, a research outfit in Halle, thinks the working-age population in the east will fall by more than a third by 2060. By 2035, 23 of Germany’s 401 Kreise (administrative districts) will have shrunk by at least a fifth, says Susanne Dähner at the Berlin Institute for Population and Development; all of them are in the east. In some districts, there will be four funerals for every birth. Instead of losing people to the west, eastern Germany will lose them to the grave.

The constitutional pledge of “equivalent living conditions” across Germany thus looks unattainable. The government tries to help so-called “structurally weak” regions, in the east as well as the west. But although investment in infrastructure or technical universities may help some towns, it cannot stop the demographic decline in many east German regions.

Coming to terms

The picture is much brighter in some eastern cities. Potsdam, Jena and Dresden have clusters of industry and tourism as well as cheap housing; some, like Leipzig (“Hypezig”, to irritated locals), have been booming for years. The “bacon belt” around Berlin benefits from the success of the capital, especially as older workers move out to the suburbs. Yet even as overall emigration to the west dries up, eastern cities are sucking educated people away from already struggling small towns and villages. That trend may continue, as only half of east German workers work in cities, compared with three-quarters in the west.



The changes in the east have social, cultural and political consequences which are now coming to the fore. Last February thousands of Dynamo Dresden supporters at an away game in Hamburg began an unfamiliar chant: “Ost [east], Ost, Ostdeutschland!” A video of the episode went viral, sparking a lively debate: were the fans expressing a dubious “eastern” variant of militant German nationalism? Or was this a cheerful reappropriation of an identity that for so long was taken to connote stupidity and closed-mindedness?

“Identity is key to understanding east Germany,” says Franziska Schubert, a thoughtful Green who represents Görlitz in Saxony’s state parliament. Fully 47% of east Germans say they identify as easterners before Germans, a far higher proportion than at the euphoric moment of reunification. (The equivalent is true for 22% of westerners.) Regional identity is hardly abnormal in Germany—ask the Bavarians—but in the east it can seem grounded in politics as much as culture or tradition.

When Jana Hensel, a writer, recently gave a talk to a school in her home town of Leipzig, she was astonished to find herself spending half an hour fielding questions from teenagers about an Ossiquote (a proposal to give east Germans preference in public jobs). “More than 25 years after the end of the GDR, students have become east German again,” she says. “If we’re not careful, we’ll lose another generation.”

The AfD has exploited the power of eastern particularism. Under slogans like “The east rises up!” the party has scored 20%-plus in eastern state elections, most recently in Thuringia on October 27th. There, and in recent elections in Brandenburg and Saxony, it was only voters over 60 whose support for the established parties ensured that the AfD did not come first. In Saxony and Thuringia the AfD was the most popular party among under-30s. This is worrying in a part of the country where extremism has found fertile ground. More than half of Germany’s hate crimes take place in the east, though it has just 20% of the population and few immigrants.

But eastern identity is not the exclusive preserve of extremes. Many young easterners simply developed an “Ossi” identity after encountering ignorance or scorn in the west. Nor need it be only negative. Matthias Platzeck, a former Brandenburg premier now in charge of a commission for the 30th anniversary of reunification, says that the recent election in his state was the worst-tempered ever. Nonetheless, he hopes for the emergence in the east of healthy self-confidence, built on the back of success stories—and a new focus on the many problems that span east and west. His commission’s informal motto, he says, is “as little state celebration as necessary, as much discussion as possible.” And since the Berlin Wall has gone, no amount of debate will land anyone in jail.

---

