
= eco 2019.02 (01-02)
:toc:

---

== 01 China tries to stop academics from taking its constitution literally

The bits(`=behaviour or ideas that are typical of a particular group, type of person or activity （某团体、某类人或活动的）典型行为，特有观念`) about the party’s rule, it *turns out*, *trump*(`=to beat sth (that sb says or does) by saying or doing sth even better 纸牌中的王牌; 赢；胜过；打败`) the bits about civil liberties(n.)自由（自己选择生活方式而不受政府及权威限制）

中国试图阻止学者从字面上理解其宪法 +
事实证明，有关政党统治的信息, 胜过有关公民自由的信息

Feb 14th 2019 | BEIJING

A YEAR BEFORE Xi Jinping *became* China’s leader, a 47-year-old professor at Peking University, Zhang Qianfan 张千帆, *delivered*(`=to give a speech, talk, etc. or other official statement 发表；宣布；发布`) *a talk* to mark(v.)(`= to celebrate or officially remember(v.) an event that you consider to be important 纪念；庆贺`) the 100th anniversary of the collapse of China’s last imperial(`=connected with an empire 帝国的；皇帝的`) dynasty(`=a series of rulers of a country who all belong to the same family 王朝；朝代`), in 1911, *charting*(`=to record or follow the progress or development of sb/sth 记录，跟踪（进展或发展）`) the history of efforts [since then] *to instil*(`=~ sth (in/into sb) : to gradually make sb feel, think or behave in a particular way over a period of time 逐渐灌输，逐步培养（感受、思想或行为）`) respect for constitutional principles.

Students *unable to find seats* in the packed(a.)(`=extremely full of people 异常拥挤的；挤满人的`) lecture （通常指大学里的）讲座，讲课，演讲 theatre(n.)(`=a building or an outdoor area where plays and similar types of entertainment are performed 戏院；剧场；露天剧场`) *stood* shoulder-to-shoulder 肩并肩地；齐心协力地 around the walls.

They *grinned*(`=~ (at sb) to smile widely 露齿而笑；咧着嘴笑；龇着牙笑`) and *clapped* 鼓掌，拍手（表示赞许或欣赏） when he *started* by saying: “I *have written down* my true feelings... They *may sound* fierce(`=showing strong feelings or a lot of activity, often in a way that is violent 狂热的；强烈的；猛烈的`). *Forgive me* if they *cause offence*(n.)(`=the act of upsetting or insulting sb 冒犯；搅扰；侮辱`).”

====
- dynasty => 来自希腊语dynamis, 力量，权力，统治者。引申词义朝代。
- offence =>  of-对面 + -fenc-打击 + -e
====

在习近平成为中国领导人的前一年，北京大学(Peking University) 47岁的教授张千帆, 在纪念中国最后一个封建王朝1911年覆灭100周年的演讲中，描绘了自那以来, 中国在向民众灌输尊重宪法原则方面所做的努力的历史。挤得水泄不通的大讲堂里，学生们肩并肩地站在墙边。在学生们的微笑与鼓掌声中, 张千帆说:“我已经写下了我的真实感受……它们可能听起来带有强烈的个人情感。如果冒犯了你，请原谅我。”


The thin, bespectacled(a.)(`= wearing spectacles 戴眼镜的`) academic *held* his audience spellbound(a.)(`=with your attention completely held by what you are listening to or watching 入迷；出神；着魔`).


====
- spellbound => spell,符咒，咒语，bound,绑定的。
====

Those who, *unable to find space* in the room, *had crowded*(`=to fill a place so there is little room to move 挤满；塞满；使…拥挤`) by the doorway, were still there [when he finished, almost two hours later].

That was fortunate(a.)(`=~ (to do sth) /~ (in having...) /~ (for sb)(that...) : having or bringing an advantage, an opportunity, a piece of good luck, etc. 幸运的；交好运的；吉利的`), because his final point(`= a thing that sb says or writes giving their opinion or stating a fact 论点；观点；见解`) *was* the most powerful in a lecture （通常指大学里的）讲座，讲课，演讲 *packed with* indictments(`= the act of officially accusing sb of a crime 控告；起诉`) of China’s failure(n.) *to implement*(`=to make sth that has been officially decided start to happen or be used 使生效；贯彻；执行；实施`) the guarantees(`=a firm promise that you will do sth or that sth will happen 保证；担保`) of its constitution, *including freedom of* speech, *of* assembly(n.)(`= the meeting together of a group of people for a particular purpose; a group of people who meet together for a particular purpose 集会；（统称）集会者`) and *of* association(`=an official group of people who have joined together for a particular purpose 协会；社团；联盟`).

他最后的观点是最有说服力的，因为他的演讲充斥着对中国未能履行宪法保障的控诉，包括言论、集会和结社自由。

Mr Zhang *wrapped up*(`=to complete sth such as an agreement or a meeting in an acceptable way 圆满完成，顺利结束（协议或会议等）`) *by listing* 12 places where authoritarian(a.)(`=believing that people should obey authority and rules, even when these are unfair, and even if it means that they lose their personal freedom 威权主义的；专制的`) rule *had (at least briefly) crumbled*(`=to break or break sth into very small pieces （使）破碎，成碎屑`), *from* the Soviet Union *to* Taiwan *to* countries that *had recently experienced* the Arab spring.

最后，张列举了12个威权统治已经(至少短暂地)崩溃的地方，从苏联到台湾，再到最近经历过“阿拉伯之春”的国家。

“What their people can do,” he said, “the Chinese” -- and here *he paused briefly* while the audience *began to laugh and clap* -- “people *can certainly do*.”

Wild(`=full of very strong feeling 感情炽烈的`) applause(n.)(`=the noise made by a group of people clapping their hands and sometimes shouting to show their approval or enjoyment 鼓掌；喝彩`) *ensued*(v.)(`= to happen after or as a result of another event 接着发生；因而产生`). Someone *cried*, “Good!”


====
- bespectacled => 前缀be-, 强调。词根spect, 看，同spectacle,眼镜。
- spellbound => spell,符咒，咒语，bound,绑定的。
- ensue => en-, 进入，使。-sue, 顺序，词源同suit, sequence.
====


Such a scene *was* extraordinary(a.)(`=not normal or ordinary; greater or better than usual 不平常的；不一般的；非凡的；卓越的`) [even at the time].

The authorities *were determined*(`=~ on sth/to do sth : to decide definitely to do sth 决定，决心（做某事）`) *to prevent* any attempt *to replicate*(`=to copy sth exactly 复制；（精确地）仿制`) the Arab uprisings(n.)(`=~ (against sth) : a situation in which a group of people join together in order to fight against the people who are in power 起义；暴动；造反`); anonymous *calls* online *for* public gatherings(n.)(`= a meeting of people for a particular purpose 聚集；聚会；集会`) *in support of* them `分词作状语` *drew*(`=~ sb (to sth) : to attract or interest sb 吸引；招引；使感兴趣; / ~ sth (from sb) : to produce a reaction or response 产生，引起，激起（反应或回应）`) more police than protesters.

即使在当时，这样的场面也是非同寻常的。当局决心阻止任何复制阿拉伯起义的企图; 网上的匿名人士呼吁公众集会以支持他们，但招来的警察比抗议者数量更多。


Mr Zhang *says* he *was reprimanded*(`=~ sb (for sth) : ( formal ) to tell sb officially that you do not approve of them or their actions 申斥；训斥；斥责`) *for* his speech.

====
- reprimand => 来自 re-,向后，往回，premere,按，压， 词源同 print,press.
====

`主` Invitations(`= ~ (to sth/to do sth) : a spoken or written request to sb to do sth or to go somewhere （口头或书面的）邀请`) for him to talk on campuses `谓` *dried up*(`=if a supply of sth dries up , there is gradually less of it until there is none left 逐渐枯竭；耗尽`).

But he *kept his job*. And *remarkably*(ad.)(`=unusual or surprising in a way that causes people to take notice 非凡的；奇异的；显著的；引人注目的`) his textbook, “An Introduction to the Study of Constitutional Law”, first published in 2004, *was republished* in 2014 by Law Press(`=newspapers and magazines 报章杂志；报刊；印刷媒体`), which *is controlled by* the Ministry of Justice.

The preface(`=an introduction to a book, especially one that explains the author's aims （书的）前言，序言`) *sets the tone*: “The study of constitutional law *must break down* forbidden(`=not allowed 禁止的；不准的`) ideological zones, because the rights of Chinese citizens *accept* no forbidden zones.”

张表示，他的演讲受到了斥责。邀请他在校园演讲的邀请逐渐绝迹。但他保住了工作。值得一提的是，他的教科书《宪法研究导论》(a Introduction to the Study of Constitutional Law) -- 于2004年首次出版 -- 2014年由司法部控制的法律出版社(Law Press)再版。序言定下了基调:“宪法研究必须打破思想禁区，因为中国公民的权利不接受任何禁区。”


Mr Xi initially(ad.)(`=at the beginning 开始；最初；起初`) *appeared to agree*, at least rhetorically(ad.)(`=connected with the art of rhetoric 讲究修辞地；在修辞学上`).

In 2012, shortly after he *took power*, he *gave a striking(`=interesting and unusual enough to attract attention 引人注目的；异乎寻常的；显著的`) speech on* the supremacy(n.)(`=~ (over sb/sth) : a position in which you have more power, authority or status than anyone else 至高无上；最大权力；最高权威；最高地位`) of the constitution /and how “no organisation or individual” *could stand above* it.

习近平起初似乎同意，至少在言辞上是这样。2012年，在他掌权后不久，他发表了一篇引人注目的演讲，阐述了宪法至高无上的地位，以及“没有任何组织或个人”能够凌驾于宪法之上。

Ceremonies(`=a public or religious occasion that includes a series of formal or traditional actions 典礼；仪式`) *to swear*(`=to make a serious promise to do sth 郑重承诺；发誓要；表示决心要`) *allegiance*(n.)(`=~ (to sb/sth) : a person's continued support for a political party, religion, ruler, etc. （对政党、宗教、统治者的）忠诚，效忠，拥戴`) *to* the constitution, *such as* the one *pictured*(`= ~ sb/sth as sth : to describe or present sb/sth in a particular way 描述；描写`), *proliferated*(v.)(`=to increase rapidly in number or amount 迅速繁殖（或增殖）；猛增`).

宣誓效忠宪法的仪式，如上图(文章配图照片)所示，越来越多。

But it soon *became clear that* his main interest *was* in Article(`=a separate item in an agreement or a contract （协议、契约的）条款，项`) 1, which *says*: “Disruption(`=When there is disruption of an event, system, or process, it is prevented from continuing or operating in a normal way. 妨碍; 扰乱`) of the socialist system *by* any organisation or individual *is prohibited*(a./v.)(`=to stop sth from being done or used especially by law （尤指以法令）禁止`).”

但很快就清楚了，他的主要兴趣在于宪法中的第一条:“禁止任何组织或个人破坏社会主义制度。”

In 2013, after small protests(`=~ (against sth) : the expression of strong disagreement with /or opposition to sth; a statement /or an action that shows this 抗议；抗议书（或行动）；反对`) *broke out* in the southern city of Guangzhou *over* censors’(`=a person whose job is to examine books, films/movies, etc. and remove parts which are considered to be offensive, immoral or a political threat （书籍、电影等的）审查员，审查官`) *efforts to prevent* a newspaper *from publishing* an editorial(n.)(`= an important article in a newspaper, that expresses the editor's opinion about an item of news or an issue; in the US also a comment on radio or television that expresses the opinion of the station or network （报刊的）社论；（美国电台或电视台的）评论`) *in praise(`=words that show approval of or admiration for sb/sth 赞扬；称赞；赞美`) of* “constitutionalism”(`=a belief in constitutional government 立宪主义`), `主` state media *launched* a propaganda(n.)(`=ideas or statements that may be false or exaggerated /and that are used in order to gain support for a political leader, party, etc. 宣传；鼓吹`) offensive(n.)(`=a military operation in which large numbers of soldiers, etc. attack another country 进攻；攻击；侵犯; /a series of actions aimed at achieving sth in a way that attracts a lot of attention （引人注意的）系列行动；运动；攻势`) *against* the term 术语；措辞.

They *said* it *was* just another way of *calling for* Western-style democracy(n.)(`=a system of government in which all the people of a country can vote to elect their representatives 民主政体；民主制度`).

To the dismay(`=a worried, sad feeling after you have received an unpleasant surprise 诧异；惊愕；灰心；丧气`) of liberals(n.)(`=a person who supports political, social and religious change 支持（社会、政治或宗教）变革的人`), Mr Xi last year *secured*(`=~ sth (for sb/sth) /~ sb sth : ( formal ) to obtain or achieve sth, especially when this means using a lot of effort （尤指经过努力）获得，取得，实现`) a constitutional revision(n.)(`= a change or set of changes to sth （一项、一轮等）修订，修改`) that *allows him to remain president* for life.

====
- allegiance -> al-加强意义 + leg(-lig-,e←→ i)约束 + -i-中缀 + -ance名词词尾 / 前缀al-同ad-. 单词liege, 臣子，臣民。原指臣子对君王的效忠。后该词多与词根lig相联系, lig, 绑定, 见ligature,韧带。
- proliferate => 来自拉丁语proles,子孙，后代，-fer,带来，生育，词源同bear,bring.后用于生物学指繁殖，增殖。
- offensive => of-对面 + -fens-打击 + -ive形容词词尾
- democracy => demo-, 人民。-cracy, 管理，统治。
====

2013年，中国南方城市广州爆发了小规模抗议活动，起因是审查机构试图阻止一家报纸发表一篇赞美“立宪”的社论。随后，官方媒体发起了针对“立宪”一词的宣传攻势。他们说这只是呼吁西式民主的另一种方式。令自由派失望的是，习近平去年修改了宪法，使他得以终身担任国家主席。


Under his rule, the Communist Party *has been waging*(`=~ sth (against/on sb/sth) : to begin and continue a war, a battle, etc. 开始，发动，进行，继续（战争、战斗等）`) its toughest(a.)(`=~ (on/with sb/sth) : demanding that particular rules be obeyed /and showing a lack of sympathy for any problems or suffering(n.) that this may cause 严厉的；强硬的；无情的`) campaign *against* dissent(n.)(`=the fact of having or expressing opinions that are different from those that are officially accepted （与官方的）不同意见，异议`) and liberal values *since* the aftermath(n.)(`=the situation that exists as a result of an important (and usually unpleasant) event, especially a war, an accident, etc. （战争、事故、不快事情的）后果，创伤`) of the Tiananmen Square protests nearly 30 years ago.

在他的统治下，共产党发动了自30年前tam事件以来最严厉的反对异见和自由价值观的运动。


In 2015 police *rounded up*(`=if police or soldiers round up a group of people, they find them and arrest or capture them 围捕；围剿`) hundreds of lawyers and legal(`=connected with the law 与法律有关的；法律的`) activists who *had been trying to help* citizens *use* the courts *to reverse*(`=to change sth completely so that it is the opposite of what it was before 颠倒；彻底转变；使完全相反; / to change a previous decision, law, etc. to the opposite one 撤销，废除（决定、法律等）`) injustices(n.)(`=the fact of a situation being unfair and of people not being treated equally; an unfair act or an example of unfair treatment 不公正，不公平（的对待或行为）`) *perpetrated(`= ~ sth (against/upon/on sb) : ( formal ) to commit a crime or do sth wrong or evil 犯（罪）；做（错事）；干（坏事）`) by* officials -- the kind of cases that, *as* Mr Zhang *says* in his textbook 教科书；课本；教材, *touch on* constitutional matters, *not just* ordinary legal ones.

2015年，警方围捕了数百名律师和法律活动人士，他们一直试图帮助公民利用法庭来扭转官员犯下的不公正行为 -- 正如张在他的教科书中所说，这类案件涉及宪法问题，而不仅仅是普通的法律问题。

Many of the detainees(n.)(`=a person who is kept in prison, usually because of his or her political opinions （通常因政治主张）被拘留者，被扣押者`) *have been released* but *banned from doing* legal work and *kept under* surveillance(n.)(`=the act of carefully watching a person suspected of a crime or a place where a crime may be committed （对犯罪嫌疑人或可能发生犯罪的地方的）监视`).

Some *have been tried(v.)(`=try sb (for sth)/ try sth : to examine evidence in court and decide whether sb is innocent or guilty 审理；审讯；审判`) and imprisoned*.

The final related trial *ended* on January 28th with the sentencing of Wang Quanzhang, a human-rights lawyer, *to* four-and-a-half years in prison for “subversion”(`= the attempt to weaken or destroy a political system or a government. 颠覆企图`).

许多被拘留者已被释放，但被禁止从事法律工作，并受到监视。有些人被审判和监禁。1月28日，人权律师王全章因“颠覆国家政权罪”被判处四年半有期徒刑。

====
- aftermath => after,在后。-math,割草，拟声词，同mow。原指割的第二遍草，即质量比较差的草，引申比喻义后果，余波。
- perpetrate => 来自拉丁语perpetrare,履行，执行，完成，*来自per-,整个的，patrare,执行，实施，来自pater,父亲，词源同father.其字面意思可能是生下小孩，成为父亲。其原义并无感情色情，后用于比喻用法始作俑者，犯罪，做恶。*
====


Now the party *is focusing more closely on* campuses(`=the buildings of a university or college and the land around them （大学、学院的）校园，校区`), where many legal scholars *still support* constitutionalism.

The party is right: the word for this, xianzheng, is often just a veiled(a.)(`=not expressed directly or clearly because you do not want your meaning to be obvious 戴面纱；戴面罩;含蓄的；掩饰的`) way of *referring to*(`=to mention or speak about sb/sth 提到；谈及；说起; / to describe or be connected to sb/sth 描述；涉及；与…相关`) Western-style democracy, or *at any rate* 不管怎样至少总而言之 just the nice bits of the constitution.

[In January] the Ministry of Education *ordered* every university *to report to* the authorities which textbooks they *were using for* constitutional studies.

It *said* reasons for this “thorough(a.)(`=done completely; with great attention to detail 彻底的；完全的；深入的；细致的`) investigation” *included* a need *to “implement*(`=to make sth that has been officially decided start to happen or be used 使生效；贯彻；执行；实施`) Xi Jinping Thought on socialism with Chinese characteristics for a new era” and “*revise*(`=to change your opinions or plans, for example because of sth you have learned 改变，修改（意见或计划）`) and *improve* textbooks in a timely(a.)(`=happening at exactly the right time 及时的；适时的`) manner(`= the way that sth is done or happens 方式；方法`)”.

====
- veil => 这个单词很好记，它和reveal（揭露）同源，其中re为前缀“往回”，veal为词根“面纱”，相当于单词veil，所以reveal的字面意思就是“揭回面纱”，将覆盖于事物之上的面纱去除，就是“揭露”了。逻辑很像discover（发现）“移除覆盖物”，及detect（查明）“移除盖子”。
====

现在，党更加关注校园，许多法律学者仍然支持宪政。中国共产党是对的:用“宪政”这个词来形容它，往往只是一种含蓄地暗指西方式的民主，或者至少是宪法中一些美好的部分。今年1月，教育部要求所有大学向当局报告他们使用哪些教科书进行宪法学习研究。声明称，此次“彻查”的原因包括“贯彻落实习近平新时代中国特色社会主义思想”和“及时修改和完善教材”。

Mr Zhang’s popular textbook *is likely to be* a victim(`=a person who has been attacked, injured or killed as the result of a crime, a disease, an accident, etc. 受害者；罹难者；罹病者；牺牲品`) of the purge(n.)(`=the act of removing people, often violently, from an organization because their views are unacceptable to the people who have power （对异己的）清洗，清除，排除`) that *is* all but sure *to follow*(`=to come after sth/sb else in time or order; to happen as a result of sth else （指时间或顺序）在…后发生，因…而发生`).

There is evidence that the book is in the party’s sights(`=the area or distance within which sb can see or sth can be seen 视力范围；视野`) already.

[In the past few days] online bookshops *have stopped selling* it.

Those trying to buy it *see* messages such as “this product *has been removed from* the shelves”(`=a flat board, made of wood, metal, glass, etc., fixed to the wall or forming part of a cupboard/closet, bookcase , etc., for things to be placed on （固定在墙上的或橱柜、书架等的）架子，搁板`) or in the case of Amazon’s website in China, “stock *is* currently not available”.

(Censors （书籍、电影等的）审查员，审查官, however, *have yet to eradicate*(`=~ sth (from sth) : to destroy or get rid of sth completely, especially sth bad 根除；消灭；杜绝`) a pirated(a.)盗版的；非法复制的 digital version of the book, a link to which *was circulated*(`=if a story, an idea, information, etc. circulates or if you circulate it, it spreads or it is passed from one person to another 传播；流传；散布`) in late January on Weibo, a microblog site, by an academic in central China.)

====
- victim => 来源于拉丁语victima(作祭品的动物)。 词根词缀： -vict-征服,战胜 + im
- purge => 来自拉丁语purgare,纯化，清洗，使干净，来自purigare,*使纯化*，来自purus,纯的，*词源同pure*,-ig,驱动，使，做，词源同agent,litigate.
- eradicate => e-, 向外。-rad, 根，词源同radish, root.即连根拔起，根除。
====

张广受欢迎的教科书很可能成为整肃的受害者，整肃几乎肯定会随之而来。有证据表明，这本书已经进入了共产党的视野。在过去的几天里，网上书店已经停止销售它。那些试图购买该产品的人看到的信息是“该产品已下架”，或者亚马逊中国网站上的信息是“目前无货”。(不过，审查机构尚未根除该书的盗版数字版本。1月底，一位华中地区的学者在微博网站新浪微博(Weibo)上传播了该书的一个链接。)


The authorities *have long tried to impose* orthodoxy(`=an idea or view that is generally accepted 正统观念；普遍接受的观点`) *on* campuses.

In 2015 they *ordered* tighter controls on the use of imported books that *spread* “Western values”.

The minister of education *urged*(`=to advise or try hard to persuade sb to do sth 敦促；催促；力劝`) universities *to ensure* that comments(`=~ (about/on sth) : something that you say or write which gives an opinion on or explains sb/sth 议论；评论；解释`) in classrooms *do not “attack or defame*(`=to harm sb by saying or writing bad or false things about them 诬蔑；诽谤；中伤`) the rule of the party or *smear*(`=to damage sb's reputation by saying unpleasant things about them that are not true （用油性或稀软物质）胡乱涂抹; 弄脏；弄上油污; 诽谤；诋毁`) socialism”.

*Nor*, he said, *should* they “*violate* the constitution and laws” -- *meaning*, presumably(`=used to say that you think that sth is probably true 很可能；大概；想必是`), the bits of the constitution that *affirm*(`=to state firmly or publicly that sth is true or that you support sth strongly 肯定属实；申明；断言`) the party’s primacy(n.)(`= the fact of being the most important person or thing 首要；至高无上`).

Closed-circuit(a.)(`=A closed-circuit television or video system is one that operates within a limited area such as a building. 闭路式的`) television cameras *have been installed in* many lecture 讲座 theatres *to allow* classes *to be monitored*(`=to watch and check sth over a period of time in order to see how it develops, so that you can make any necessary changes 监视；检查；跟踪调查`).

About 15 years ago the government *launched* what it *called* the “Marxism 马克思主义 Theory Research and Construction Project” *to produce*(`=to make things to be sold, especially in large quantities 生产；制造`) sanitised(`=to remove the parts of sth that could be considered unpleasant （用化学制剂）消毒，使清洁;去除…中使人不快的内容；净化`) textbooks.

Some universities *have begun to demand* that only these *be used for* legal studies.


====
- orthodox => ortho-,正确的，-dox (= -doc-教),观念，思想，词源同doctor,dogma.
- defame => de-, 不，非，使相反。fame, 名声。即诽谤，造成不好的名声。
- sanitize => 词源同 sane,健康的。-ize,使。引申词义净化，消毒。
====

长期以来，当局一直试图在校园推行正统教育。2015年，他们下令加强对传播“西方价值观”的进口书籍的使用控制。教育部部长敦促各大学确保课堂上的言论不“攻击或诋毁党的统治或诽谤社会主义”。他说，它们也不应该“违反宪法和法律” -- 大概是指宪法中确认党的首要地位的部分。许多大学讲堂都安装了闭路电视摄像机，以便对课堂进行监控。大约15年前，政府启动了它所谓的“马克思主义理论研究和建设项目”，以生产清洁的教科书。一些大学已经开始要求只把这些用于法律研究。


In spite of this, and the occasional sackings(n.)(`=an act of sacking sb (= dismissing them from their job) 解雇;把……装入麻袋;洗劫`) of academics for their political views, elite(`= a group of people in a society, etc. who are powerful and have a lot of influence, because they are rich, intelligent, etc. 上层集团；（统称）掌权人物，社会精英`) institutions(`=a large important organization that has a particular purpose, for example, a university or bank （大学、银行等规模大的）机构`) *are still full of* liberals.

Mr Zhang *reckons*(`= to think sth or have an opinion about sth 想；认为`) there are probably thousands of people who *teach constitutional law* in China.

He *suspects* most of them *share his views*.

*Cracking down*(`=crack down (on sb/sth): to try harder to prevent an illegal activity /and deal more severely with those who are caught doing it 竭力取缔；严厉打击；镇压`) is hard: many academics at leading(a.)(`=most important or most successful 最重要的；一流的`) universities *are* people who *have studied* in the West.

Mr Zhang *has* a PhD in biophysics(`=the science which uses the laws and methods of physics to study biology 生物物理学`) from Carnegie Mellon 卡内基梅隆 University and another one in the theory of government from the University of Texas at Austin.

*Purging*(`=purge sth (of sb) /purge sb (from sth) : to remove people from an organization, often violently, because their opinions or activities are unacceptable to the people in power 清除，清洗（组织中的异己分子）`) these professors *would be* a huge setback(n.)(`=a difficulty or problem that delays or prevents sth, or makes a situation worse 挫折；阻碍`) for China’s efforts *to attract* talent(n.)(`=people or a person with a natural ability to do sth well 有才能的人；人才；天才`) *from* abroad /and *create* world-class universities.

====
- purge => 来自拉丁语purgare,纯化，清洗，使干净，来自purigare,使纯化，来自purus,纯的，词源同pure,-ig,驱动，使，做，词源同agent,litigate.
====

尽管如此，偶尔也会有学者因其政治观点而遭解雇，但精英机构中仍充斥着自由派人士。张先生认为在中国可能有成千上万的人教授宪法。他怀疑他们中的大多数人都同意他的观点。镇压是困难的:许多顶尖大学的学者都是在西方学习过的人。张拥有卡内基梅隆大学(Carnegie Mellon University)生物物理学博士学位, 和德克萨斯大学奥斯汀分校(University of Texas at Austin)政府理论博士学位。对中国吸引海外人才、打造世界一流大学的努力来说，清除这些教授将是一个巨大的挫折。


But a sensitive(`=that you have to treat with great care because it may offend people or make them angry 须谨慎对待的；敏感的`) year *lies ahead*.

Officials *are mindful(a.)(`=mindful of sb/sth; mindful that... : ( formal ) remembering sb/sth and considering them or it when you do sth SYN conscious 记着；想着；考虑到`) of* two looming(`=to appear as a large shape that is not clear, especially in a frightening or threatening way 赫然耸现；（尤指）令人惊恐地隐现`) anniversaries 周年纪念日 : the 100th of a student movement that *called for* China *to introduce* (Western) science and democracy, on May 4th; and the 30th of the bloody suppression(`=the act of suppressing sth 镇压；压制；抑制`) of the Tiananmen Square protests, which *were also led by* students, on June 4th.

Mr Zhang’s institution, Peking University, *played a central role in* both upheavals(`=a big change that causes a lot of confusion, worry and problems 剧变；激变；动乱；动荡`).

In the coming months the authorities *will be* more than usually *worried about* scholars who *inspire(`=~ sb (with sth) /~ sth (in sb) : to make sb have a particular feeling or emotion 使产生（感觉或情感）`) students with* liberal views.


但未来一年将是敏感的一年。官员们注意到两个即将到来的纪念日:5月4日，要求中国引进(西方)科学和民主的学生运动100周年纪念日;6月4日，同样由学生领导的tam抗议. 张所在的北京大学(Peking University)在两场剧变中都发挥了核心作用。在接下来的几个月里，当局将比以往更担心那些激发学生自由主义观点的学者。


Some students *clearly support* Mr Zhang. On Peking University’s chat forum(`=~ (for sth) : a place where people can exchange opinions and ideas on a particular issue; a meeting organized for this purpose 公共讨论场所；论坛；讨论会`), several messages *have appeared* criticising the removal of his textbook from online bookshops (but also some *attacking* him).

Mr Zhang says that, *were he able to give* another lecture like the one he gave in 2011, students *would be* even more supportive(a.)(`=giving help, encouragement or sympathy to sb 给予帮助的；支持的；鼓励的；同情的`) than they were then.

“We *are moving even further away from* constitutionalism. Everybody *can feel* the restriction of speech,” he says. “More people *are discontented about* our political reality today.”

一些学生显然支持张先生。在北京大学的聊天论坛上，出现了几条批评他的教科书从网上书店下架的信息(但也有一些攻击他的)。张表示，如果他能像2011年那样再做一次讲座，学生们会比那时更支持他。“我们正在进一步远离宪政。每个人都能感受到言论的限制，”他说。“越来越多的人对我们今天的政治现实感到不满。”


---



== 01 China tries to stop academics from taking its constitution literally 纯净版
The bits about the party’s rule, it turns out, trump the bits about civil liberties


Feb 14th 2019 | BEIJING

A YEAR BEFORE Xi Jinping *became* China’s leader, a 47-year-old professor at Peking University, Zhang Qianfan, *delivered a talk* to mark(v.) the 100th anniversary of the collapse of China’s last imperial dynasty, in 1911, *charting* the history of efforts since then *to instil respect for* constitutional principles. Students *unable to find seats* in the packed lecture theatre *stood shoulder-to-shoulder* around the walls. They *grinned and clapped* when he started by saying: “I have written down my true feelings...They may sound fierce. *Forgive me* if they cause offence.”

The thin, bespectacled academic *held his audience spellbound*. Those who, unable to find space in the room, *had crowded* by the doorway, were still there when he finished, almost two hours later. That was fortunate, because his final point was the most powerful in a lecture *packed with indictments of* China’s failure *to implement the guarantees of* its constitution, including freedom of speech, of assembly and of association. Mr Zhang *wrapped up* by listing(v.) 12 places where authoritarian rule *had (at least briefly) crumbled*, from the Soviet Union to Taiwan to countries that *had recently experienced* the Arab spring. “What [their] people can do,” he said, “the Chinese” -- and here *he paused briefly* while the audience began to laugh and clap --“people can certainly do.” Wild applause *ensued*. Someone cried, “Good!”

Such a scene was extraordinary even at the time. The authorities *were determined* to prevent any attempt to replicate the Arab uprisings; `主` anonymous *calls online for* public gatherings *in support of* them `谓` *drew* more police than protesters. Mr Zhang says he *was reprimanded* for his speech. Invitations for him to talk on campuses *dried up*. But he kept his job. And *remarkably* his textbook, “An Introduction to the Study of Constitutional Law”, first published in 2004, *was republished* in 2014 by Law Press, which is controlled by the Ministry of Justice. The preface *sets the tone*: “The study of constitutional law *must break down* forbidden ideological zones, because the rights of Chinese citizens *accept* no forbidden zones.”

Mr Xi *initially appeared to agree*, at least rhetorically. In 2012, shortly after he took power, he gave a striking speech on the supremacy of the constitution and how “no organisation or individual” *could stand above* it. Ceremonies *to swear allegiance to* the constitution, such as the one *pictured*, *proliferated*. But *it soon became clear* that his main interest was in Article 1, which says: “Disruption of the socialist system by any organisation or individual *is prohibited*.” In 2013, after small protests *broke out* in the southern city of Guangzhou over censors’ efforts *to prevent* a newspaper *from* publishing an editorial *in praise of* “constitutionalism”, state media *launched a propaganda offensive against* the term. They said it was just another way of *calling for* Western-style democracy. To the dismay of liberals, Mr Xi last year *secured a constitutional revision* that allows him to remain president for life.

Under his rule, the Communist Party *has been waging its toughest campaign against* dissent and liberal values since the aftermath of the Tiananmen Square protests nearly 30 years ago. In 2015 police *rounded up* hundreds of lawyers and legal activists who had been trying to help citizens *use* the courts *to reverse injustices* perpetrated by officials -- `主` the kind of cases that, *as* Mr Zhang *says* in his textbook, `谓` *touch on* constitutional matters, *not just* ordinary legal ones. Many of the detainees *have been released* but *banned from doing legal work* and *kept under surveillance*. Some have been tried and imprisoned. The final related trial *ended* on January 28th *with the sentencing of* Wang Quanzhang, a human-rights lawyer, *to* four-and-a-half years in prison for “subversion”.

Now the party *is focusing more closely on* campuses, where many legal scholars still support constitutionalism. The party is right: the word for this, xianzheng, is often just a veiled way of *referring to* Western-style democracy, or *at any rate* just the nice bits of the constitution. In January the Ministry of Education *ordered every university to report to* the authorities which textbooks they were using for constitutional studies. It *said* reasons for this “thorough investigation” *included* a need *to “implement* Xi Jinping Thought on socialism with Chinese characteristics for a new era” and “*revise and improve textbooks* in a timely manner”.

Mr Zhang’s popular textbook *is likely to be* a victim of the purge that is all but sure to follow. There is evidence that the book is in the party’s sights already. In the past few days online bookshops have stopped selling it. Those trying to buy it *see messages* such as “this product has been removed from the shelves” or *in the case of* Amazon’s website in China, “stock is currently not available”. (Censors, however, *have yet to eradicate* a pirated digital version of the book, a link to which *was circulated* in late January on Weibo, a microblog site, by an academic in central China.)

The authorities *have long tried to impose orthodoxy on* campuses. In 2015 they *ordered tighter controls on* the use of imported books that *spread* “Western values”. The minister of education *urged universities to ensure that* comments in classrooms *do not “attack or defame* the rule of the party /or *smear* socialism”. Nor, he said, should they “*violate* the constitution and laws” -- meaning, presumably, the bits of the constitution that *affirm* the party’s primacy. Closed-circuit television cameras have been installed in many lecture theatres to allow classes to be monitored. About 15 years ago the government *launched* what it called the “Marxism Theory Research and Construction Project” *to produce* sanitised textbooks. Some universities *have begun to demand* that only these *be used for* legal studies.

In spite of this, and the occasional sackings of academics for their political views, elite institutions *are still full of* liberals. Mr Zhang *reckons* there are probably thousands of people who *teach constitutional law* in China. He *suspects* most of them *share his views*. *Cracking down* is hard: many academics at leading universities *are* people who have studied in the West. Mr Zhang has a PhD in biophysics from Carnegie Mellon University /and another one in the theory of government from the University of Texas at Austin. *Purging these professors* would be a huge setback for China’s efforts *to attract talent from abroad* and *create* world-class universities.

But a sensitive year *lies ahead*. Officials *are mindful of* two looming anniversaries: the 100th of a student movement that *called for* China *to introduce* (Western) science and democracy, on May 4th; and the 30th of the bloody suppression of the Tiananmen Square protests, which *were also led by* students, on June 4th. Mr Zhang’s institution, Peking University, *played a central role in* both upheavals. In the coming months the authorities *will be* more than usually *worried about* scholars who *inspire* students *with* liberal views.

Some students *clearly support* Mr Zhang. On Peking University’s chat forum, several messages *have appeared* criticising the removal of his textbook from online bookshops (but also some *attacking* him). Mr Zhang says that, *were he able to give another lecture* like the one he gave in 2011, students *would be* even more supportive than they were then. “We *are moving even further away from* constitutionalism. Everybody can feel the restriction of speech,” he says. “More people *are discontented about* our political reality today.”

---


== 02 Why so glum(a.)(`=sad, quiet and unhappy 忧郁的；死气沉沉的；闷闷不乐的`), China?

*Relative to* their level of prosperity(n.)(`= the state of being successful, especially in making money 兴旺；繁荣；成功；昌盛`), the Chinese are unhappy

====
- glum => 词源同gloom, 忧郁。
- prosperity => pro-前 + -sper-希望 + -ity名词词尾
====

为什么如此郁闷，中国? +
相对于他们的富裕程度，中国人并不幸福


Feb 14th 2019

IT *TOOK* 125 years for America’s Declaration(`=an official or formal statement, especially about the plans of a government or an organization; the act of making such a statement 公告；宣告；宣言`) of Independence *to reach* a wide Chinese audience, and when it did, some lofty(`=very high and impressive 巍峨的；高耸的; / showing a belief that you are worth more than other people 傲慢的；高傲的; /deserving praise because of its high moral quality 崇高的；高尚的`) phrases 短语；词组 *got lost*.

美国的《独立宣言》花了125年的时间才被广泛的中国读者所接受，而当它被广泛的中国读者所接受时，一些高谈阔论就消失了。

`主` The earliest known(a.)(`=known about, especially by a lot of people 知名的；出了名的；已知的`) Chinese translation 翻译;译本 of the declaration, published in 1901 by young nationalists *burning(`=~ (with sth) :to feel a very strong emotion or desire 有强烈的情感；渴望; / to make sb very angry 激怒；使大怒`) to overthrow* the Qing empire, `系` *is* an impatient, combative text.

1901年，渴望推翻清政府的年轻民族主义者发表了《独立宣言》，目前已知的最早的中文译本是一篇急躁、好斗的文章。

The document’s name, *noted* the scholar who *rediscovered* it, Frank Li of the Chinese Academy of Social Sciences, *became* the “American War Proclamation of Independence”.

The rights it *deemed*(`=to have a particular opinion about sth 认为；视为；相信`) inalienable(`=that cannot be taken away from you 不可剥夺（或分割）的`) -- “life, liberty and the pursuit of happiness” -- *turned into* something bleaker(a.)(`=exposed, empty, or with no pleasant features 无遮掩的；荒凉的；索然无味的;/ not encouraging or giving any reason to have hope 不乐观的；无望的；暗淡的`): “life, liberty and all interests”.

重新发现该文件的学者、中国社会科学院的弗兰克•李指出，该文件的名字成了“美国独立战争宣言”。它认为不可剥夺的权利——“生命、自由和追求幸福”——变成了更暗淡的东西:“生命、自由和所有利益”。 (happiness 被改成了 all interests)

====
- bleak => 词源同bleach, 漂白，指苍白的，暗淡的。 +
-> *bleak*(a.)(`=(of a place 地方) exposed, empty, or with no pleasant features 无遮掩的；荒凉的；索然无味的`) concrete housing 索然乏味的混凝土住宅群 +
-> a bleak(`=(of a situation 状况) not encouraging or giving any reason to have hope 不乐观的；无望的；暗淡的`) outlook/prospect 暗淡的前景╱前途 +
-> a bleak(a.)(`=(of the weather 天气) cold and unpleasant 阴冷的`) winter's day 一个阴冷的冬日

====


Happiness *remains a thorny(a.)(`=causing difficulty or disagreement 有刺的；多刺的;棘手的；麻烦的；引起争议的`) subject* in China.

Since 2012 the UN *has sponsored*(`=to arrange for sth official to take place 提议并组织 (商谈); 主办；举办；促成; / to support sb by paying for their training or education 资助（某人的培训或教育）`) a World Happiness Report, for which residents of about 150 countries *are asked* how satisfied they are with their lives.

China *ranked* 86th in the latest report, *below* Russia and even war-torn(a.)(`=a war-torn country or area is severely affected by the fighting that is taking place there 被战争撕裂的; 受战争严重破坏的；饱受战争蹂躏的`) Libya 利比亚;埃及以西的北非地方古名.

在中国，幸福仍然是一个棘手的话题。自2012年以来，联合国发起了一项《世界幸福报告》(World Happiness Report)，调查约150个国家的居民对生活的满意度。在最新的报告中，中国排在第86位，落后于俄罗斯，甚至落后于饱受战争摧残的利比亚。

Some foreign observers *find* {it easy *to explain* China’s relative gloom(n.)(`=a feeling of being sad and without hope 忧郁；愁闷；无望`)}.

They *see* a system *built on* an unsentimental(`=not having or expressing emotions such as love or pity; not allowing such emotions to influence what you do 没有（或不流露）感情的；不感情用事的`) bargain between rulers and ruled.

Citizens *may enjoy* the fruits of economic growth but *may not protest against* the costs, from pollution to yawning(a.)(`=to be very wide and often frightening and difficult to get across 非常宽；难以逾越`) inequality.

====
- yawn => 来自 PIE*ghai,张嘴，打呵欠，词源同 gas,chaos,gape. +
-> A crevasse *yawned*(v.)(`=(of a large hole or an empty space 大的洞穴或空间) to be very wide and often frightening and difficult to get across 非常宽；难以逾越`) at their feet. 他们的脚下是一条张开大口的裂缝。
-> There's *a yawning gap* between rich and poor. 贫富之间有一条鸿沟。
====

Such experts *scoff*(v.)(`=~ (at sb/sth) to talk about sb/sth in a way that makes it clear that you think they are stupid or ridiculous 嘲笑；讥讽`) when today’s Communist leaders *say* that they *set great store(`=set/put (great, etc.) store by sth : to consider sth to be important （十分）看重，重视（某事物）`) by* increasing public happiness as part of the Chinese Dream, President Xi Jinping’s campaign(n.)(`=~ (against/for sth) a series of planned activities that are intended to achieve a particular social, commercial or political aim 运动（为社会、商业或政治目的而进行的一系列有计划的活动）`) to make China great again.

These cynics(n.)(`=a person who believes that people only do things to help themselves, rather than for good or sincere reasons 认为人皆自私的人；愤世嫉俗者; /a person who does not believe that sth good will happen or that sth is important 悲观者；怀疑者`) *imagine* that {Team Xi’s true priority *is* to keep the economy growing quickly, on the assumption(`=a belief or feeling that sth is true or that sth will happen, although there is no proof 假定；假设`) that material gains *are* the only thing that *can keep* a long-suffering public *in line*(`=in line for sth : likely to get sth 有可能获得某物; /in (a) line (with sth)（与…）成一排，成一直线`)}.

====
- scoff => 来自古诺斯语 skop,嘲笑，嘲讽，同古英语 scop,游吟诗人，来自 Proto-Germanic*skapiz,形成， 创作，来自 PIE*skep,砍，切，削，词源同 shape.
- cynic => 来自词根can, 狗，见canine. 因古希腊词哲学家苏格拉底的学生安提西尼创立的犬儒学派而得名，该学派倡导简单生活，但后来哲学理念被后世有意或无意的曲解，词义也发生了变化。
- *in line for sth* : likely to get sth 有可能获得某物 +
-> She is *in line for promotion*. 她有可能得到提升。
====

一些外国观察人士发现，很容易解释中国经济的相对低迷。他们看到的是一个建立在统治者和被统治者之间无情交易基础上的体系。公民可以享受经济增长的果实，但不能抗议从污染到日益扩大的不平等的成本。当今天的共产党领导人说，他们非常重视增加公众的幸福感，把它作为中国梦的一部分，即习近平主席让中国再次伟大起来的运动时，这些专家对此嗤之以鼻。这些悲观的怀疑者认为，习近平团队真正的优先任务其实是保持经济快速增长，后者假设只有物质利益才是唯一能让长期受苦的公众来遵守规则的东西。


This cynical theory is popular but wrong. “Chinese Discourses(n.)(`=a long and serious treatment or discussion of a subject in speech or writing 论文；演讲`) on Happiness” *is* a timely(`=happening at exactly the right time 及时的；适时的`) new collection of essays(`=a short piece of writing on a particular subject, written in order to be published （用来刊登的）论说文；小品文`) *edited by* two sinologists 汉学家，研究中国文化者 *based* in Britain, Gerda Wielander and Derek Hird.

It *explores* how China’s propaganda machine *devotes*(`=DEVOTE STH TO STH : to give an amount of time, attention, etc. to sth 把…用于`) extraordinary efforts *to promoting*(`=to help sth to happen or develop 促进；推动`) the idea that the Chinese people *enjoy good and meaningful lives* under Communism -- precisely （加强同意的语气）对，的确如此，一点也不错 because economic growth alone *does a poor job of* generating happiness.

这种悲观怀疑,愤世嫉俗的理论很流行，但却是错误的。《中国幸福论》是由两位英国汉学家格尔达·维泽尔德和德里克·希尔德合编的最新文集。它探讨了中国的宣传机器如何做出非凡的努力来宣传这样一种观念，即在共产主义制度下，中国人享受着美好而有意义的生活 ——正是因为经济增长本身在产生幸福感方面做得不够。

[Back in 1974] Richard Easterlin, an American economist, *spotted*(`= to see or notice a person or thing, especially suddenly or when it is not easy to do so 看见；看出；注意到；发现`) a puzzle(`=something that is difficult to understand or explain 不解之谜；疑问`).

Although richer countries *are* generally more contented(a.)(`=showing or feeling happiness or satisfaction, especially because your life is good （尤指因生活好而）满意的，惬意的，满足的`), rising material prosperity *does not necessarily lead to* ever(`=all the time or every time; always 不断地；总是；始终`)-higher levels of self-reported well-being.

“Chinese Discourses” *calls* China a giant Easterlin 美国经济学家伊斯特林 Paradox 悖论.

====
- paradox => 来源于希腊语中由para(在旁)和doxa(观点)组成的复合词paradoxon(相反的观点)。 词根词缀： para-侧面 + dox(-doc-)教

- *Easterlin Paradox* 伊斯特林悖论 : 由美国南加州大学经济学教授理查德·伊斯特林（R.Easterlin）在1974年的著作《经济增长可以在多大程度上提高人们的快乐》中提出, 即他发现一个令人迷惑的重要问题是：为什么更多的财富并没有带来更大的幸福？对此的解释性理论包括:  +
1.经济学仅关注收入、财富和消费，而忽略了影响人们幸福的其他许多重要因素，包括：激励与创造、健康、政治参与、社会渴望、自由、利他主义的丧失、不平等、社会资本的减少和地位外部性。特别是，如果这些非经济因素与收入、财富和消费等经济因素呈负相关时，那么随着GDP的增长，许多影响幸福的非经济因素会下降，从而在不同程度上抵消经济因素带来的正面作用.  +
2.个人效用与自己的收入水平正相关，但与社会的平均收入水平（攀比水平）负相关；当社会变得更富裕时，攀比水平随之提高，导致收入—幸福曲线下移，从而使得总效用水平保持不变。一个人的主观福利与其相对地位有关。因此，地位竞争仅仅导致个人福利的再分配，而作为一个整体的社会的幸福并没有增加。
====

Chinese real GDP per person *grew* more than fivefold(`= -fold : 乘以；…倍；由…部分组成`) between 1990 and 2015.

Yet, rather than *climbing [in lockstep*(n.)(`=a way of walking together where people move their feet at the same time 齐步走（步伐）`)] with the economy, the self-reported happiness of the Chinese *fell sharply* from 1990, *reaching* a nadir(n.)(`=the worst moment of a particular situation 最糟糕的时刻；最低点`) in 2000-05 (a time of breakneck(a.)(`=very fast and dangerous 飞速惊险的;断颈`) GDP growth) before recovering.

It has probably yet(ad.)（用于否定句和疑问句，谈论尚未发生但可能发生的事） *to regain(`= to get back to a place that you have left 回到（原位）；返回`) the level of* 1990.

1974年，美国经济学家理查德•伊斯特林发现了一个难题。尽管较富裕的国家通常更满足，但不断增长的物质财富并不一定会带来更高水平的自我幸福感。《中国幸福论》称中国是一个巨大的伊斯特林悖论。从1990年到2015年，中国实际人均GDP增长了5倍多。然而，中国人自我报告的幸福指数并没有随着经济的增长而上升，而是从1990年开始急剧下降，在2000-05年(GDP增速极快的时期)达到最低点，之后才开始回升。它可能还没有恢复到1990年的水平。

====
- nadir => 来自阿拉伯语nazir,相反的，来自nazir as-samt,反方向的，与天顶相反的底点，词源同zenith.后引申词义最低点。
- yet : ad. used in negative sentences and questions to talk about sth that has not happened but that you expect to happen （用于否定句和疑问句，谈论尚未发生但可能发生的事） +
-> I *haven't received a letter* from him *yet*. 我还没有收到他的信呢。 +
-> ‘Are you ready?’ ‘No, *not yet*.’ “你准备好了吗？”“还没有。” +
-> We *have yet to decide* what action to take (= We have not decided what action to take) . 我们尚未决定采取何种行动。

====

A chapter of the 2017 World Happiness Report, *co-written by* Mr Easterlin, *dug into*(`=dig deep (into sth) : to search thoroughly for information 探究；搜集；细查; /掘（地）；凿（洞）；挖（土）`) Chinese data *from* the previous quarter-century /and *found* weak correlations(n.)(`=a connection between two things in which one thing changes as the other does 相互关系；相关；关联`) between happiness and several trends *commonly blamed for*(`= be to blame (for sth) : to be responsible for sth bad （对坏事）负有责任`) gloom.

====
- correlation => cor-共同 + re-回 + -lat-携带,拿取 + -ion名词词尾
====

伊斯特林与人合写的《2017年世界幸福报告》(2017 World Happiness Report)的一章, 深入研究了中国过去25年的数据，发现幸福与几个通常被认为是悲观的趋势之间, 存在微弱的相关性。

*Take*(`=used to introduce sb/sth as an example 以…为例；将…作为例证`) inequality of income(`=the money that a person, a region, a country, etc. earns from work, from investing money, from business, etc. 收入；收益；所得`), which in China *marched(`=to walk with stiff regular steps like a soldier 齐步走；行进`) upwards* between 1980 and about 2010.

[During the same period] levels of self-reported happiness *fell* and *rose* in a U-shape.

The chapter *studies* other “predictors”(`=something that can show what will happen in the future 预测器；预示物`) of happiness, *including* the consumption(`=the act of using energy, food or materials; the amount used （能量、食物或材料的）消耗，消耗量`) of coal 煤 (a proxy(`=something that you use to represent sth else that you are trying to measure or calculate （测算用的）代替物，指标`) for pollution), housing prices, GDP per person, healthy-life expectancy, self-reported levels of freedom *to make* big decisions /and corruption (*measured by* asking whether bribery is acceptable).

None of these indicators *tracks(`=to find sb/sth by following the marks, signs, information, etc., that they have left behind them 跟踪；追踪`) happiness closely* in China.

Two others *are* a good fit: unemployment and access to social safety nets.

Misery(n.)(`=great suffering of the mind or body 痛苦；悲惨; /very poor living conditions 穷困；悲惨的生活`), notably(ad.)(`=used for giving a good or the most important example of sth 尤其；特别`) among low-income Chinese, *deepened*(`=to become worse; to make sth worse （使）变糟，恶化，严重`) as unemployment *spiked*(v.)(`=to rise quickly and reach a high value 迅速升值；急剧增值; /用尖物刺入（或扎破）`) /and safety nets *collapsed* in 2000-05, as state-owned firms *were restructured*(`=to organize sth such as a system or a company in a new and different way 调整结构；改组；重建`).

*As* employment(`=work, especially when it is done to earn money; the state of being employed 工作；职业；受雇`) *rebounded*(`=(business 商) ( of prices, etc. 价格等 ) to rise again after they have fallen 回升；反弹`), so *did* happiness.

====
- spike =>  可能来自中古瑞典语 spijk,钉子，来自 Proto-Germanic*spikaz,钉子，来自 PIE*spei,尖刺，尖 头，词源同 spire,spoke,pin.词义麦穗来自该印欧词根衍生的拉丁语 spica,麦穗，穗状花序。
====

以收入不平等为例，从1980年到2010年，中国的收入不平等一直在上升。在同一时期，自我报告的幸福水平,呈u形下降和上升。这一章研究了其他幸福的“预测因素”，包括煤炭消费(污染的代表)、房价、人均GDP、健康预期寿命、自我报告的能做出重大决策的自由程度, 和腐败(通过询问被访者,贿赂是否可以被接受?)。这些指标中没有一个与中国人的幸福感密切相关。而另外两个却很适合:失业和社会保障。2000年至2005年，随着国有企业重组，失业率飙升，社会保障体系崩溃，中国人的苦难(尤其是低收入人群)进一步加深。而随着就业率的回升，幸福感也随之回升。


Even people *normally considered* clear beneficiaries(n.)(`=beneficiary :
a person who gains as a result of sth 受益者；受惠人`) of China’s economic opening -- the hundreds of millions of rural migrants who *found work* in cities over the past 30 years -- *are not* collectively 集体地，共同地 cheerier(a.)(`=cheery : happy and cheerful 高兴的；兴高采烈的`).

The most recent World Happiness Report, from 2018, *finds* that, on average, Chinese migrants *secure*(`=to obtain or achieve sth, especially when this means using a lot of effort （尤指经过努力）获得，取得，实现`) higher incomes *by moving to* cities but, once there, *say* they are less happy than long-established(`=to hold a position for long enough or succeed in sth well enough to make people accept and respect you 确立；使立足；使稳固`) city folk.

More surprisingly, such migrants *are* also unhappier than cousins(`=a person who is in your wider family but who is not closely related to you 远房亲戚；远亲; /a child of your aunt or uncle 同辈表亲（或堂亲）；堂兄（或弟、姊、妹）；表兄（或弟、姊、妹）`) who *stayed in* the countryside.

*Dig into* the numbers, and the jobs of the unhappiest migrants *are* unusually insecure(a.)(`=not safe or protected 不安全的；无保障的；不牢靠的`), harsh(`=cruel, severe and unkind 残酷的；严酷的；严厉的`) and badly paid, *thrusting(`= to push sth/sb suddenly or violently in a particular direction; to move quickly and suddenly in a particular direction 猛推；冲；搡；挤；塞`) them into* an underclass(n.)(`=a social class that is very poor and has no status 社会底层；贫困阶层`) *made more painful* by hukou 户口 residency(`=the state of living in a particular place 居住；定居`) laws that *limit their access to* schooling(n.)(`=the education you receive at school 学校教育`) *for* their children and other public services.

Rising prosperity *cannot compensate(`=~ (for sth) : to provide sth good to balance or reduce the bad effects of damage, loss, etc. 补偿；弥补`) for* a sense of *being left out* 忽视，不考虑；被遗忘; 排除在外.


即使是那些通常被认为是受益于中国经济开放的人 —— 在过去30年里, 在城市中找到工作的数亿农民工 ——总体上也并不乐观。最新的《世界幸福报告》(World Happiness Report)-- 从2018年开始发布 -- 该报告发现，平均而言，中国的移民, 通过移居到城市中来获得更高的收入，但一旦移居完成之后，他们却表示，自己的幸福感不如那些早在城市中定居的人。更令人惊讶的是，这些农民工甚至比留在农村中的表亲们,更不快乐。深入研究这些数据，你会发现，最不幸福的农民工的工作, 通常缺乏安全感、工作条件苛刻、收入微薄，这将他们推入了一个更痛苦的社会底层中，因为户籍法律限制了他们子女上学和享受其他公共服务的机会。日益繁荣的经济无法弥补他们被排除在外的感觉。


Happy *is* as happy is told to do

“Chinese Discourses” *suggests*(`=to put an idea into sb's mind; to make sb think that sth is true 使想到；使认为；表明`) that {party chiefs(`=a person with a high rank or the highest rank in a company or an organization （公司或机构的）首领，头目，最高领导人`) *have long worried about* such risks}.

In the 1950s they *pledged(`=to formally promise to give or do sth 保证给予（或做）；正式承诺`) to build* a “prosperous and happy socialist society”.

Today, in the Xi era, a similar message *is rammed(`=ram sth home : to emphasize an idea, argument, etc. very strongly to make sure people listen to it 强调（想法、论点等）以使人接受`) home* in television shows, posters 招贴画；海报 and websites *lauding*(`=to praise sb/sth 赞扬；赞美；称赞`) model citizens who *find joy* in serving the country.

Some propaganda is plain(ad.)(`=used to emphasize how bad, stupid, etc. sth is （用于强调）简直，绝对地`) sneaky(a.)(`= behaving in a secret and sometimes dishonest or unpleasant way 悄悄的；偷偷摸摸的；鬼鬼祟祟的`).

“中国幸福论”表明，中共领导人长期以来一直担心此类风险。上世纪50年代，他们承诺要建设一个“繁荣幸福的社会主义社会”。如今，在习近平时代，类似的信息在电视节目、海报和网站上反复出现，赞美那些从为国服务中找到快乐的模范公民。有些宣传简直是鬼鬼祟祟的。

====
- ram => 来自古英语 ramm,公羊。引申诸相关词义。 +
-> Two passengers were injured *when their taxi was rammed(`= ( of a vehicle, a ship, etc. 汽车、轮船等 ) to drive into or hit another vehicle, ship, etc. with force, sometimes deliberately 和…相撞；撞击`) from behind by a bus*. 公共汽车从后面撞来，出租车上的两位乘客受了伤。 +
-> She *rammed(`=to push sth somewhere with force 塞进；挤进`) the key into the lock*. 她将钥匙塞进锁眼。 +
-> The spending cuts *had been rammed through Congress*. 削减开支一事在国会强行通过。
====


A contributor(`=a person who writes articles for a magazine or a book, or who talks on a radio or television programme or at a meeting （杂志或书的）撰稿人，投稿人；（电台、电视节目中的）嘉宾；（会议的）发言人`) to the new book, Jigme Yeshe Lama of the University of Calcutta, *notes that* state media *declared* the tense(`= nervous or worried, and unable to relax 神经紧张的；担心的；不能松弛的`), heavily policed(`=to go around a particular area to make sure that nobody is breaking the law there 巡查；维护治安; / to make sure that a particular set of rules is obeyed 监督；管制`) Tibetan capital, Lhasa 拉萨, “China’s happiest city” for six years *in a row*.

That improbable(`=not likely to be true or to happen 不大可能真实的（或发生的）；不大可能的; /seeming strange because it is not what you would expect 奇异的；荒谬的`) feat(n.)(`=an action or a piece of work that needs skill, strength or courage 技艺；武艺；功绩；英勇事迹`) *was achieved(`=to succeed in reaching a particular goal, status or standard, especially by making an effort for a long time （凭长期努力）达到（某目标、地位、标准）`) by* *deeming*(`=to have a particular opinion about sth 认为；视为；相信`) government policies, from *imposing* tight security(`=the activities involved in protecting a country, building or person against attack, danger, etc. 保护措施；安全工作`) *to building* highways /or *pushing* Tibetans *into* modern jobs, *to be* the definition （尤指词典里的词或短语的）释义,定义,解释 of happiness.

====
- feat => feat和fact同源,它们的区别在于fact直接来源于拉丁语facere(做,作),而feat经由古法语fet间接来源于拉丁语facere。 即与词根-feat-(做,作)同源
====

这本新书的撰稿人之一、加尔各答大学的吉格梅•耶舍•拉马指出，官方媒体连续6年宣布, 紧张而戒备森严的西藏首府拉萨, 为“中国最幸福的城市”。这一怪异而不太可能的壮举是通过将政府政策视为幸福的定义而实现的，从实施严密的安全措施, 到修建高速公路, 或推动藏人从事现代化工作。


Other propaganda *is* more subtle(`=not very noticeable or obvious 不易察觉的；不明显的；微妙的; /behaving in a clever way, and using indirect methods, in order to achieve sth 机智的；机巧的；狡猾的`).

Party homilies(n.)(`=homily :  a speech or piece of writing giving advice on the correct way to behave, etc. （有关规矩等的）说教，说教作品`) about collective happiness, common in the 1950s, *have been replaced by* stories about well-being on two levels: the personal and the national.

====
- homily => 来自拉丁语homilia 布道，传道，来自希腊语homilos,人群，集会，来自PIE*sem,一，一起，词源同same,assembly.引申词义说教，并成为主要词义。
====

其他的宣传更加微妙。上世纪50年代常见的关于集体幸福的党的说教，如今已被关于个人和国家两个层面幸福的故事所取代。

Individuals *are told that* they are xingfu, or “happy and blessed(a.)(`=enjoyable in a way that gives you a sense of peace or a feeling of freedom from anxiety or pain 愉快安宁的；无忧无虑的; /lucky （宗教用语）有福的`)”, because Chinese families *are made strong by* traditional values.

In turn, Mr Xi *likes to say*, families *are made secure and prosperous by* loyal membership of “the great family of the Chinese nation”.

With his stories about tradition and belonging, Mr Xi *may just be* on to something.

A happiness gap between rich and poor *has narrowed* as the lowest earners *report* greater well-being, *to an extent that* economic growth numbers alone *do not explain*.

To stern(a.)(`=serious and often disapproving; expecting sb to obey you 严厉的；苛刻的；要求别人服从的`) Communist Party chiefs, few rights *are* inalienable(`= that cannot be taken away from you 不可剥夺（或分割）的`).

But the human *need to be promised* a good life? That is self-evident(a.)(`=obvious and needing no further proof or explanation 显而易见的；不言而喻的；明摆着的`).

每个人都被告知他们是幸福的，因为中国的家庭因传统价值观而变得强大。反过来，习近平喜欢说，“中华民族大家庭”的忠诚成员, 使家庭变得安全和繁荣。习所讲的关于传统和归属感的故事，可能说对了一些事情。富人和穷人之间的幸福差距已经缩小，因为最低收入者报告的幸福感更高，这在一定程度上不能仅凭经济增长数据来解释。对严厉的共产党领导人来说，几乎没有什么权利是不可剥夺的。但是人类需要被许诺美好的生活吗?这是不言而喻的。

---


== 02 Why so glum, China? 纯净版
Relative to their level of prosperity, the Chinese are unhappy


Feb 14th 2019

IT *TOOK* 125 years for America’s Declaration of Independence *to reach* a wide Chinese audience, and when it did, some lofty phrases *got lost*. The earliest known(a.) Chinese translation of the declaration, published in 1901 by young nationalists *burning to overthrow* the Qing empire, *is* an impatient, combative text. `主` The document’s name, *noted* the scholar who rediscovered it, Frank Li of the Chinese Academy of Social Sciences, `谓` became the “American War Proclamation of Independence”. The rights it *deemed* inalienable -- “life, liberty and the pursuit of happiness” -- *turned into* something bleaker: “life, liberty and all interests”.

Happiness *remains* a thorny subject in China. Since 2012 the UN *has sponsored* a World Happiness Report, for which residents of about 150 countries *are asked* how satisfied they are with their lives. China *ranked 86th* in the latest report, *below* Russia and even war-torn Libya. Some foreign observers *find* it easy to explain China’s relative gloom. They *see* a system *built on* an unsentimental bargain between rulers and ruled. Citizens *may enjoy* the fruits of economic growth *but may not protest against* the costs, *from* pollution *to* yawning inequality. Such experts *scoff* when today’s Communist leaders *say that* they *set great store* by *increasing* public happiness *as* part of the Chinese Dream, President Xi Jinping’s campaign *to make* China great again. These cynics *imagine that* Team Xi’s true priority *is* to keep the economy growing quickly, *on the assumption that* material gains *are* the only thing that *can keep a long-suffering public in line*.

This cynical theory *is* popular *but* wrong. “Chinese Discourses on Happiness” is a timely new collection of essays *edited by* two sinologists *based* in Britain, Gerda Wielander and Derek Hird. It *explores* how China’s propaganda machine *devotes extraordinary efforts* to promoting the idea that the Chinese people *enjoy good and meaningful lives* under Communism -- precisely because economic growth alone *does a poor job of* generating happiness.

Back in 1974 Richard Easterlin, an American economist, *spotted* a puzzle. Although richer countries *are generally more contented*, rising material prosperity *does not necessarily lead to* ever-higher levels of self-reported well-being. “Chinese Discourses” *calls* China a giant Easterlin Paradox. Chinese real GDP per person *grew more than fivefold* between 1990 and 2015. Yet, rather than *climbing [in lockstep] with* the economy, the self-reported happiness of the Chinese *fell sharply* from 1990, *reaching a nadir* in 2000-05 (a time of breakneck GDP growth) before recovering. It *has probably yet to regain the level of* 1990.

A chapter of the 2017 World Happiness Report, *co-written by* Mr Easterlin, *dug into* Chinese data *from* the previous quarter-century and *found weak correlations between* happiness *and* several trends *commonly blamed for* gloom. *Take* inequality of income, which in China *marched upwards* between 1980 and about 2010. During the same period levels of self-reported happiness *fell* and *rose* in a U-shape. The chapter *studies* other “predictors” of happiness, *including* the consumption of coal (a proxy for pollution), housing prices, GDP per person, healthy-life expectancy, self-reported levels of freedom to make big decisions and corruption (*measured by* asking whether bribery is acceptable). None of these indicators *tracks happiness closely* in China. Two others *are* a good fit: unemployment and access to social safety nets. Misery, notably among low-income Chinese, *deepened* as unemployment *spiked* and safety nets *collapsed* in 2000-05, *as* state-owned firms *were restructured*. As employment *rebounded*, so *did* happiness.

Even people (*normally considered* clear beneficiaries of China’s economic opening) -- the hundreds of millions of rural migrants who *found work in cities* over the past 30 years -- *are not* collectively cheerier. The most recent World Happiness Report, from 2018, *finds that*, on average, Chinese migrants *secure higher incomes* by moving to cities but, once there, *say* they are less happy than long-established city folk. More surprisingly, such migrants are also unhappier than cousins who stayed in the countryside. *Dig into* the numbers, and the jobs of the unhappiest migrants *are* unusually insecure, harsh and badly paid, *thrusting them into* an underclass *made* more painful by hukou residency laws that *limit* their access to schooling for their children and other public services. Rising prosperity *cannot compensate for* a sense of being left out.

Happy is as happy is told to do

“Chinese Discourses” *suggests that* party chiefs *have long worried about* such risks. In the 1950s they *pledged to build* a “prosperous and happy socialist society”. Today, in the Xi era, a similar message *is rammed home* in television shows, posters and websites *lauding* model citizens who *find joy* in serving the country. Some propaganda *is* plain sneaky. A contributor to the new book, Jigme Yeshe Lama of the University of Calcutta, *notes that* state media *declared* the tense, heavily policed Tibetan capital, Lhasa, “China’s happiest city” for six years *in a row*. That improbable feat *was achieved by* deeming government policies, from *imposing* tight security *to building highways* or *pushing Tibetans into* modern jobs, *to be* the definition of happiness.

Other propaganda is more subtle. `主` Party homilies about collective happiness, common in the 1950s, `谓` *have been replaced by* stories about well-being on two levels: the personal and the national. Individuals *are told that* they are xingfu, or “happy and blessed”, because Chinese families *are made strong by* traditional values. In turn, Mr Xi *likes to say*, families *are made* secure and prosperous *by* loyal membership of “the great family of the Chinese nation”. With his stories about tradition and belonging, Mr Xi *may just be on to something*. A happiness gap between rich and poor *has narrowed* [*as* the lowest earners *report* greater well-being], *to an extent that* economic growth numbers *alone do not explain*. To stern Communist Party chiefs, few rights *are* inalienable. But the human *need to be promised* a good life? That is self-evident.

---




