
= eco 2019-12 (01)
:toc:

---

== 01. In the UN, China uses threats and cajolery to promote its worldview

In the UN, China *uses* threats and cajolery(n.)(`=flattery intended to persuade 意在说服的奉承; 甜言蜜语；诱骗；谄媚`) *to promote* its worldview

Some countries *are pushing back* 推回; 推迟

在联合国，中国用威胁和甜言蜜语, 来宣扬自己的世界观 +
一些国家正在反击

Dec 7th 2019 | NEW YORK

*DESPITE* ITS veto-wielding(`=to have and use power, authority, etc. 拥有，运用，行使，支配（权力等）`) power in the United Nations, China *has long been reluctant to stick(`=to push sth, usually a sharp object, into sth; to be pushed into sth 将…刺入（或插入）；刺；戳；插入`) its neck out*(`=stick your neck out :to do or say sth when there is a risk that you may be wrong 做不保险的事；说不保险的话；冒险`).

It has been 20 years [since it last *stood alone* in *exercising* that right]. But in the UN’s backrooms 密室;幕后, the country’s diplomats 外交官 *are showing greater willingness* to flex(v.)屈伸，活动（四肢或肌肉，尤指为准备体力活动） muscle(`=*flex your muscles* : to show sb how powerful you are, especially as a warning or threat 显示实力，炫耀力量（尤指作为警告或威胁）`), and their Western counterparts *to fight back*.

*Not* [since the cold war] *has* the organisation *become* such a battleground *for competing*(v.)(`=compete : 竞争；对抗`) visions(`=the ability to think about or plan the future with great imagination and intelligence 想象力；眼力；远见卓识`) of the international order.

尽管中国在联合国拥有否决权，但它一直不愿冒风险。自上次单独行使这一权利以来已有20年。但是在联合国的密室里，这个国家的外交官们表现出了更大的意愿, 来展示他们的力量，而他们的西方同行们则在进行反击。自冷战以来，该组织从未成为国际秩序中各种不同愿景观点, 斗争的战场。

`主` *A struggle* [in October] *over* China’s mass(`= affecting or involving a large number of people or things 大批的；数量极多的；广泛的`) internment(n.)(`=the practice of putting people in prison for political reasons. 政治拘禁`) of Uighurs 维吾尔人, a Muslim ethnic(a.)(`=connected with or belonging to a nation, race or people that shares a cultural tradition 民族的；种族的`) minority 少数派；少数民族；少数群体, `谓` *suggests* how intense *the fight has become*.

去年10月，中国大规模拘留维族人的斗争表明，这场斗争已变得多么激烈。维族人是中国的穆斯林少数民族。
====
- ethnic => 在本世纪60年代race（种族，人种），racial（种族的，人种的）二词因常与racism（种族主义）一词相联系而多少受到感染，并蒙上了贬抑的感情色彩。在日常用语中有的人就用eihnic 一词来取代race和racial，race变成ethnic group（族群），racial pride（种族优越感）也变成ethnic pride，以避种族主义之嫌。
====

It *involved* Britain *taking an unusual leading role* in *condemning China’s human-rights record*.

The British representative 代表(人) at the UN 联合国代表, Karen Pierce, *issued a statement*(`=a formal or official account of facts or opinions 声明；陈述；报告`), *signed by* 22 other countries *including* America, *calling for* unfettered(a.)(`=not controlled or restricted 无限制的；不受约束的；自由的`) UN access to the prison camps in China’s far-western region of Xinjiang.

====
- fetter => 来自古英语fetor, 链子，特指"脚链"，词源同foot.
====

其中，在谴责中国人权记录方面, 英国扮演了不同寻常的领导角色。英国驻联合国代表卡伦·皮尔斯(Karen Pierce)发表了一份声明, 该声明由包括美国在内的22个国家所签署，呼吁联合国不受限制地进入处于中国西部偏远地区新疆的劳改营。

A diplomatic brawl(n.)(`=a noisy and violent fight involving a group of people, usually in a public place 喧闹；斗殴；闹事`) *ensued*(`= to happen after or as a result of another event 接着发生；因而产生`).

Chinese diplomats *persuaded* dozens of authoritarian(a.)(`=believing that people should obey authority and rules, even when these are unfair, and even if it means that they lose their personal freedom 威权主义的；专制的`) countries, *including* mostly Muslim ones in the Middle East, *to sign* a counter(n.)(`=~ (to sb/sth) : ( formal ) a response to sb/sth that opposes their ideas, position, etc. （对意见、立场等的）反对，反驳`)-statement *praising* China’s actions in Xinjiang *as* an enlightened(a.)(`=having or showing an understanding of people's needs, a situation, etc. that is not based on old-fashioned attitudes and prejudice 开明的；有见识的；摆脱偏见的`) effort *to fight terrorism*(`= the use of violent action in order to achieve political aims or to force a government to act 恐怖主义`) /and *eradicate*(`=~ sth (from sth) to destroy or get rid of sth completely, especially sth bad 根除；消灭；杜绝`) *religious extremism*(`=political, religious, etc. ideas or actions that are extreme and not normal, reasonable or acceptable to most people 极端主义；过激论`).

====
- brawl => 拟声词，同bray. 词源解释：来自古英语braulen（喊出、吵架）.  +
助记窍门：与形近字crawl（爬行）一起记：brawl→谐音“不弱”→不甘示弱→争吵、打架；crawl→谐音“可弱”→甘心示弱→匍匐、爬行
- eradicate => e-, 向外。-rad, 根，词源同radish, root.即连根拔起，根除。
====
接着发生了一场外交上的争吵。中国外交官说服数十个专制国家(包括中东的穆斯林国家)签署了一份反对声明，在其中称赞了中国在新疆的行动, 是打击恐怖主义和根除宗教极端主义的开明努力。

There *were* threats(n.) and reprisals(n.)(`=a violent or aggressive act towards sb because of sth bad that they have done towards you 报复；报复行动`), too.

====
- reprisal => re-,向后，往回，-pris,抓住，缩写自 prehens,词源同 prehensile,prison.即抓回，后引申词义报 复，特指国家间收回领土，财物等的军事行动。
====

Chinese diplomats *are said* 据说 *to have told* Austrian(a.)(`=belongs or relates to Austria, or to its people or culture 奥地利的; 奥地利人的; 奥地利文化的`) counterparts *that* if their country *were to sign* Britain’s statement, the Austrian government *would not get land* it wanted for a new embassy in Beijing.

The Austrians *signed anyway*.

还有威胁和报复。据说，中国外交官告诉奥地利同行，如果他们的国家签署英国的声明，奥地利政府将不会得到它想要的在北京建立新大使馆的土地。但奥地利人还是签了。

Chinese officials *cancelled a bilateral(a.)(`=involving two groups of people or two countries 双方的；双边的`) event* in Beijing with Albania  阿尔巴尼亚（位于欧洲）, another of the signatories(`=signatory的复数: a person, a country or an organization that has signed an official agreement （协议的）签署者，签署方，签署国`).

中国官员取消了与另一个签署国阿尔巴尼亚在北京举行的双边活动。
====
- bilateral => 前缀bi-, 二。词根later, 边，见multilateral, 多边的.
- signatory => 来自 *sign,签字，签署，签约，-ate,使，-ory,形容词后缀。* 即签署的，签约的，后形容词作名 词使用，引申词义签署方，签署国等。
====

“A lot of countries *came under a lot of pressure* today,” *tweeted* Jonathan Allen, Britain’s deputy(n.)(`=a person who is the next most important person below a business manager, a head of a school, a political leader, etc. and who does the person's job when he or she is away 副手；副职；代理`) ambassador to the UN, on the day of his country’s statement. “But we *must stand up for* our values and *for* human rights.”

====
- deputy => 来自depute, 授权，使担任副职，代表。来源于拉丁语putare(计算,考虑)的复合词deputare(分配,指派) 词根词缀： de-去掉 + -put-考虑 + -y名词和形容词后缀
====
英国驻联合国副大使乔纳森•艾伦(Jonathan Allen), 在英国发表声明当天, 发推文称:“许多国家今天承受了很大压力。但我们必须捍卫我们的价值观和人权。”

China’s efforts *span(`=to stretch right across sth, from one side to the other 横跨；跨越`) a broad range of* UN activity, *from* human rights *to* matters *relating to* economic development.

They *appear* to have two main aims. One *is* to create a safe space for the Chinese Communist Party by *ensuring that* other countries *do not criticise* its rule.

The country *has long bristled(v.)(`=~ (with sth) (at sth) to suddenly become very annoyed or offended at what sb says or does （对某人的言行）大为恼怒；被激怒; /（动物背部或颈部的毛,因惊吓或发怒）竖起，耸起`) at* any such “interference”(`=the act of interfering 干涉；干预；介入`).

Its officials *are now becoming tougher*(`=tough 的比较级. ~ (on/with sb/sth) : demanding that particular rules be obeyed and showing a lack of sympathy for any problems or suffering that this may cause 严厉的；强硬的；无情的`) in their response.

====
- bristle => 来自PIE bhars, 刺，硬毛。词源同barley, bur. *助记窍门：bristle →brush style（刷子的发型）→短而硬的毛→鬃毛* 衍生词：bristling（竖立的、发怒的）；bristly（有刚毛的、易怒的）
====
中国的努力涵盖了从人权到经济发展等一系列联合国活动。他们似乎有两个主要目的。一是通过确保其他国家不批评中国共产党的统治，为中国共产党创造一个安全的空间。长期以来，该国一直对此类“干预”感到愤怒。它的官员们现在的反应越来越强硬。


China’s other objective(`=something that you are trying to achieve 目标；目的`) *is* '表' *to inject*(v.)（给…）注射（药物等 wording 措辞；用词 *into* UN documents that *echoes*(`=to repeat an idea or opinion because you agree with it 重复，附和（想法或看法）; /发出回声；产生回响`) the language of the country’s leader, Xi Jinping.

China *is trying to “make* Chinese policies 宾补 UN policies,” says a diplomat on the UN Security Council.

====
- objective => ob-对面,相反 + -ject-投,射 + -ive. 来自object,目标，物体，-ive,名词后缀。引申词义目标，宗旨等。
====
中国的另一个目标是在联合国文件中, 加入同中国领导人习近平的语言相呼应的措辞。联合国安理会的一位外交官表示，中国正试图“使中国的政策, 成为联合国的政策”。

China *senses(`=to become aware of sth even though you cannot see it, hear it, etc. 感觉到；意识到；觉察出`) that* `主` President Donald Trump’s aversion(n.)(`=~ (to sb/sth) a strong feeling of not liking sb/sth 厌恶；憎恶`) to multilateral(a.)(`=in which three or more groups, nations, etc. take part 多边的；多国的`) institutions *such as* the UN `谓` *has given it more room* to manoeuvre(v.)(`=to control or influence a situation in a skilful but sometimes dishonest way 操纵；控制；使花招;/ to move or turn skilfully or carefully; to move or turn sth skilfully or carefully （使谨慎或熟练地）移动，运动；转动`) in them.

====
- aversion => a-离开 + -vers-转 + -ion名词词尾. / averse（反感的）+sion（名词后缀）→嫌恶、憎恨
- manoeuvre => 来自manu,手，词源同manual,operari,操作
====
中国意识到，唐纳德•特朗普(Donald Trump)总统对联合国(UN)等多边机构的厌恶，让中国有了更多操纵这些机构的空间。


[Since Mr Xi *took office* 就职,上任 in 2012] the country *has dramatically 戏剧地；引人注目地 increased its spending at the UN*. It is now the second-largest *contributor*(n.), after America, *to* both the general budget(`=the money that is available to a person or an organization and a plan of how it will be spent over a period of time 预算`) and the peacekeeping(a.)(`=intended to help stop people fighting and prevent war or violence in a place where this is likely 维护和平的`) one.

自习近平2012年上任以来，中国大幅增加了在联合国的支出。现在，无论是在"总预算", 还是"维和预算"方面，中国都是仅次于美国的第二大出资国。

It *has also secured*(`=to obtain or achieve sth, especially when this means using a lot of effort （尤指经过努力）获得，取得，实现`) leading roles *for* its diplomats 外交官 in several UN bodies, *including* the Rome-based Food and Agriculture Organisation (*beating*(`=~ sb (at sth) : to defeat sb in a game or competition （在比赛或竞争中）赢，打败（某人）`) a candidate *backed by* America, *to many people’s surprise*).

它还为其外交官, 在几个联合国机构中获得了领导地位，包括总部设在罗马的粮农组织(它击败了美国支持的候选人，这让许多人感到惊讶)。

Next year the country *will join* the three-member Board of Auditors(n.)(`=a person who officially examines the business and financial records of a company 审计员；稽核员`), which *keeps an eye on* the UN’s accounts.

明年，该国将加入由三名成员组成的审计委员会，该委员会负责监督联合国的账目。

`主` The senior jobs *being taken by* China’s diplomats `系` *are* mostly boring ones in institutions that few countries *care much about*.

But each post *gives China control of* tiny levers 杠杆 of bureaucratic(a.)(`=connected with a bureaucracy or bureaucrats and involving complicated official rules which may seem unnecessary 官僚的；官僚主义的`) power *as well as* the ability *to dispense*(`=to give out sth to people 分配；分发`) favours.

中国外交官担任的高级职位, 大多是一些无聊的工作，很少有国家会在意这些工作。但每一个职位, 都让中国控制了微小的官僚权力杠杆，以及施舍恩惠的能力。

“Each one of these slots(n.)(`=a long narrow opening, into which you put or fit sth （投放或插入东西的）窄缝，扁口`) *has* influence(n.) with somebody somewhere,” says a European diplomat.

When votes *are taken [on matters* (China *regards as* important)], its diplomats *often use* a blunt(`=very direct; saying exactly what you think without trying to be polite 嘴直的；直言的; /不锋利的；钝的`) transactional(a.)(`=a piece of business that is done between people, especially an act of buying or selling （一笔）交易，业务，买卖`) approach(n.)(`=~ (to sth) : a way of dealing with sb/sth; a way of doing or thinking about sth such as a problem or a task （待人接物或思考问题的）方式，方法，态度`) -- *offering financing for* projects, or *threatening* to turn off the tap 水龙头；旋塞.

This *buys* China clout(n.)(`=power and influence 影响力；势力`), *if not* affection(`=the feeling of liking or loving sb/sth very much and caring about them 喜爱；钟爱`), other diplomats say.

====
- clout => 词源同clod,clot,cloud.原指大块状的东西。
====
一位欧洲外交官说:“每一个位置, 都对某个地方的某个人有影响。” 当对中国认为重要的事情, 进行投票时，其外交官经常使用一种生硬的交易方式 ——为项目提供资金，或者威胁关闭水龙头。其他外交官说，这就算不能带来好感，也能为中国带来影响力。


Mr Xi’s influence *is* evident(a.)(`=clear; easily seen 清楚的；显而易见的；显然的`).

`主` Much of the language that Chinese officials *try to insert into* UN documents `谓` *uses* his catchphrases(`=a popular phrase that is connected with the politician or entertainer who used it and made it famous 名言；流行语；时兴的话`), such as “win-win co-operation” and “a community with a shared future for mankind”(`=all humans, thought about as one large group; the human race 人类`) (`主` *keep your hands off*(`=*(get/take your) hands off (sth/sb)* : used to tell sb not to touch sth/sb （命令）别动某物╱某人`) China, `系` *is* the underlying sentiment(`=a feeling or an opinion, especially one based on emotions （基于情感的）观点，看法；情绪`)).

习的影响力显而易见。中国官员试图在联合国文件中插入的许多语言, 都使用了他的口号，比如“合作共赢”和“人类命运共同体”(不要碰中国，这是基本的看法 / 把你的手从中国身上拿开，这是潜在的情绪)。

For three years *in a row*, Chinese diplomats *managed to inject* favourable(`=positive and showing your good opinion of sb/sth 肯定的；赞同的；支持的 /making people have a good opinion of sb/sth 给人好印象的`) references(n.)(`=~ (to sb/sth) : a thing you say or write that mentions sb/sth else; the act of mentioning sb/sth 说到（或写到）的事；提到；谈及；涉及`) to Mr Xi’s Belt and Road Initiative (BRI), a “win-win” global infrastructure-building scheme, *into* resolutions on Afghanistan.

中国外交官连续3年在有关阿富汗问题的决议中，积极提及习近平提出的“一带一路”倡议，这是一个“双赢”的全球基础设施建设计划。
====
- favourable : (1) adj. ~ (to/for sb/sth) good for sth and making it likely to be successful or have an advantage 有利的；有助于…的 +
-> The terms of the agreement *are favourable to both sides*. 协议条款对双方都有利。 +
-> *favourable* economic conditions 有利的经济环境

(2) adj. positive and showing your good opinion of sb/sth 肯定的；赞同的；支持的
-> favourable comments 好评
====

They *have persuaded* senior UN officials, *including* the secretary-general 秘书长；总书记, António Guterres, *to praise* the BRI in speeches *as* a model for global development.

他们说服包括联合国秘书长安东尼奥·古特雷斯在内的联合国高级官员, 在演讲中称赞“一带一路”是全球发展的典范。

In 2018 China *convinced*(`= ~ sb/yourself (of sth) : to make sb/yourself believe that sth is true 使确信；使相信；使信服 /to persuade sb to do sth 说服，劝说（某人做某事）`) the UN Human Rights Council in Geneva 日内瓦（瑞士西南部城市） (from which America *withdrew* later that year) *to endorse*(`=to say publicly that you support a person, statement or course of action （公开）赞同，支持，认可; /（在支票背面）签名，背书; /（在广告中）宣传，代言（某一产品）`) its preferred 偏爱的;优先的；首选的 approach of “*promoting* mutually(ad.)(`=felt or done equally by two or more people 相互地；彼此；共同地`) beneficial(a.)(`=improving a situation; having a helpful or useful effect 有利的；有裨益的；有用的`) co-operation” in this field, ie(`=即. i.e.是拉丁文id est 的缩写,它的意思就是“那就是说,换句话说”,等同于“that is,in other words” ,目的是用来进一步解释前面所说的观点`), *refraining(v.)(`= ~ (from sth/from doing sth) ( formal ) to stop yourself from doing sth, especially sth that you want to do 克制；节制；避免`) from* criticism(n.)(`=the act of expressing disapproval of sb/sth and opinions about their faults or bad qualities; a statement showing disapproval 批评；批判；责备；指责`).

2018年，中国说服位于日内瓦的联合国人权理事会(美国当年晚些时候退出了该理事会)支持其在这一领域“促进互利合作”的首选方式，即避免批评。
====
- convince => con-共同 + -vinc-征服 → 共同征服 → 使确信
- endorse => en-, 进入，使。-dors, 背，见dorsal. 财务术语，即在背后签字。
- beneficial => bene-好 + -fic-做,作 + -ial形容词词尾
- i.e.源自拉丁文id est +
e.g.源自拉丁文exempli gratia
- refrain => 来自拉丁语 refrenare,勒住马嚼子，勒住，控制，来自 *re-,向后，往回，frenare,控制，用绳子 勒住*，来自 frenum,缰绳，马勒，来自 PIE dher,握住，固定，*词源同 firm*, during.引申词义克 制，节制。
====


More than merely language *is involved*. In 2017 China *sought(`=seek`) successfully* to cut funding for a job *intended to ensure that* all of the UN’S agencies and programmes *promote* human rights.

That same year Wu Hongbo, a Chinese diplomat *who was then in charge of* the UN Department of Economic and Social Affairs, *expelled*(`=to officially make sb leave a school or an organization 把…开除（或除名）`) Dolkun Isa, a Uighur 维吾尔人;维吾尔族 activist, *from* a UN forum *to which* Mr Isa *was an invited delegate*(n.)(`= a person who is chosen or elected to represent the views of a group of people and vote and make decisions for them 代表；会议代表`), *representing* a German NGO(`=non-governmental organization (a charity, association, etc. that is independent of government and business) 非政府组织（独立于政府或商界的慈善机构、协会等）`) (Mr Isa *was eventually let back in* after protests from American and German diplomats).

====
- expel => ex-, 向外。-pel, 驱使，词源同pulse, impel.
====
不仅仅只是加入习的口号。2017年，对一项旨在确保联合国的所有机构和项目, 促进人权的工作, 中国成功地削减了其资金资助。 +
同年, 当时负责联合国经济和社会事务部的中国外交官吴红波 ,从联合国论坛驱逐了维吾尔族活动家 Dolkun Isa, 后者是一名特邀代表，代表一家德国非政府组织。(最终在美国和德国外交官抗议后, Isa被请了回来)。

Mr Wu, whose post(`=a job, especially an important one in a large organization 职位；（尤指）要职`) *required him to be* non-partisan(a.)(`=not supporting the ideas of one particular political party or group of people strongly 无党派之见的；中立的`), later *boasted about* his actions on Chinese state television. “We *have to strongly defend* the motherland’s interests,” he said.

吴的职位要求他无党派，他后来在中国国家电视台上吹嘘自己的行动时说, “我们必须坚决捍卫祖国的利益”.

Opposition(`=the act of strongly disagreeing with sb/sth, especially with the aim of preventing sth from happening （强烈的）反对，反抗，对抗`) to China’s more assertive(a.)(`=expressing opinions or desires strongly and with confidence, so that people take notice 坚定自信的；坚决主张的;独断的`) approach *may grow*.

“I think *they are overdoing(v.)(`=overdo : to do sth too much; to exaggerate sth 做得过分；做得过火；夸张`) it* and I think [at some stage] people *will start to resist*(`=to refuse to accept sth and try to stop it from happening 抵制；阻挡; /to fight back when attacked; to use force to stop sth from happening 反抗；回击；抵抗`),” says the Security Council diplomat.

反对中国采取更强硬态度的声音可能会越来越大。“我认为他们做得过头了，我认为在某个阶段，人们会开始抵制，”这位安理会外交官表示。

But some others at the UN *do not share that view*.

Smaller states in Africa and the Middle East, many of them dictatorships(`=government by a dictator 独裁；专政; /独裁国家`), *resent*(`=to feel bitter or angry about sth, especially because you feel it is unfair 愤恨；感到气愤；愤愤不平`) America’s post-cold-war dominance(n.)(`=The dominance of a particular person or thing is the fact that they are more powerful, successful, or important than other people or things. 优势; 统治地位`) of the UN.

Why *should* China *not push back*, *asks* a diplomat from one country in that part of the world.

但联合国的其他一些人, 则不同意这一观点。非洲和中东的一些小国(其中许多是独裁国家)对美国在冷战后主导联合国感到不满。来自那个地区的一位外交官问道，为什么中国不应该反击?

The envoy(`=a person who represents a government or an organization and is sent as a representative to talk to other governments and organizations 使者；使节；（谈判等的）代表`) *says that* countries *may be subjected(`=~ sth (to sth) : ( formal ) to bring a country or group of people under your control, especially by using force 使臣服；使顺从；（尤指）压服`) to pressure* from China when it *wants* something, but that America, albeit(`=although 尽管；虽然`) *not as* blunt(`=very direct; saying exactly what you think without trying to be polite 嘴直的；直言的`), *can also be* transactional 交易型的；事务性的；事务处理的.

Some smaller countries *may welcome* having two great powers *competing for* their favour(`= a thing that you do to help sb 帮助；好事；恩惠; /approval or support for sb/sth 赞同；支持`) [again].

这位特使说，当中国想要什么得到东西的时候，这些国家可能会受到来自中国的压力，但是美国，尽管不那么直接，也可以是交易型的。一些小国可能会欢迎两个大国再次争夺小国对它们的好感。 / 一些较小的国家可能会欢迎两个大国再次为他们的利益而竞争。
====
- envoy => en-, 进入，使。-voy, 路，词源同via, way. 所以envoy的字面义就是one who has been sent on the way to carry out a mission（被派遣去执行使命的人），在外交用语中即指“使者”或“使节”。
- albeit =>  al（though）+be + it→although it be（that）→虽然如此

- favour : n. +
-> Can I *ask a favour*(`=a thing that you do to help sb 帮助；好事；恩惠`) ? 请帮个忙行吗？ +
-> *Do yourself a favour* (= help yourself) and wear a helmet on the bike. 要照顾自己，骑车戴上头盔。 +
-> The programme *has lost favour(`= approval or support for sb/sth 赞同；支持`) with viewers* recently. 近来这个节目已不受观众欢迎。 +
-> The government looks *with favour upon* (= approves of) the report's recommendations. 政府赞同报告所提出的建议。 +
-> As an examiner, she showed *no favour(`=treatment that is generous to one person or group in a way that seems unfair to others 特别照顾；偏袒；偏爱`) to* any candidate. 作为主考人她没有偏袒任何应试者。
====

“There’s a degree of hypocrisy(n.)(`=behaviour in which sb pretends to have moral standards or opinions that they do not actually have 伪善；虚伪`) about it,” says Richard Gowan of the International Crisis Group, a conflict-prevention NGO.

“*It would be weird(a.)(`=very strange or unusual and difficult to explain 奇异的；不寻常的；怪诞的`) to imagine that* China as a rising power *wouldn’t want a bigger stake*(`=money that sb invests in a company 篱笆桩; 赌注; 股本；股份; / ~ in sth : an important part or share in a business, plan, etc. that is important to you and that you want to be successful （在公司、计划等中的）重大利益，重大利害关系`) in the multilateral system.” Few *would imagine that* now.

国际危机组织, 是一个预防冲突的非政府组织。“如果认为中国作为一个崛起的大国，却不希望在多边体系中获得更大的利益，这将是很奇怪的想法。" 现在很少有人会这样考虑中国。
====
- hypocrisy => 来自希腊语hypokrisis,舞台表演，演戏，来自 *hypo-,在下，-kris,分开，筛选，评论，词源同crisis,critic.* 来自于古希腊时期的一种舞台表演形式，即边说边紧跟着发表看法，评论或进行阐释，引申词义表演，演戏。现义伪善，虚伪义可能来自于此，*或来自hypo-,下面，欠缺，-kris,评论，观点，即不敢发表观点和看法的，掩饰真实情感的，引申词义伪善，虚伪。*
====

---

== 01. In the UN, China uses threats and cajolery to promote its worldview 纯净版

Some countries are pushing back



Dec 7th 2019 | NEW YORK

DESPITE ITS veto-wielding power in the United Nations, China *has long been reluctant to stick its neck out*. It has been 20 years [since it last *stood alone* in exercising(v.) that right]. But in the UN’s backrooms, the country’s diplomats *are showing greater willingness* to flex muscle, and their Western counterparts *to fight back*. *Not* [since the cold war] *has* the organisation *become such a battleground for* competing visions of the international order.

A struggle [in October] over China’s mass internment of Uighurs, a Muslim ethnic minority, *suggests* how intense *the fight has become*. It *involved* Britain (*taking an unusual leading role* in condemning(v.) China’s human-rights record). The British representative at the UN, Karen Pierce, *issued a statement*, *signed by* 22 other countries including America, *calling for* unfettered UN access to the prison camps in China’s far-western region of Xinjiang. A diplomatic brawl *ensued*. Chinese diplomats *persuaded* dozens of authoritarian countries, including mostly Muslim ones in the Middle East, *to sign a counter-statement* praising(v.) China’s actions in Xinjiang *as* an enlightened effort *to fight terrorism* and *eradicate religious extremism*.

There were threats and reprisals, too. Chinese diplomats *are said* to have told Austrian counterparts that if their country *were to sign Britain’s statement*, the Austrian government *would not get land it wanted* for a new embassy in Beijing. The Austrians *signed anyway*. Chinese officials *cancelled a bilateral event* in Beijing with Albania, another of the signatories. “A lot of countries *came under a lot of pressure* today,” *tweeted* Jonathan Allen, Britain’s deputy ambassador to the UN, on the day of his country’s statement. “But we *must stand up for* our values and *for* human rights.”

China’s efforts *span a broad range of* UN activity, *from* human rights *to* matters *relating to* economic development. They *appear* to have two main aims. One *is* to create a safe space for the Chinese Communist Party *by ensuring that* other countries *do not criticise* its rule. The country *has long bristled at* any such “interference”. Its officials *are now becoming tougher* in their response. China’s other objective *is* to inject wording(n.) into UN documents that *echoes* the language of the country’s leader, Xi Jinping. China *is trying to “make* Chinese policies UN policies,” *says* a diplomat on the UN Security Council.

China *senses* that President Donald Trump’s aversion to multilateral institutions such as the UN *has given it more room* to manoeuvre(v.) in them. Since Mr Xi *took office* in 2012 the country *has dramatically increased its spending* at the UN. It is now the second-largest *contributor*(n.), after America, *to* both the general budget and the peacekeeping one. It *has also secured leading roles* for its diplomats in several UN bodies, including the Rome-based Food and Agriculture Organisation (*beating* a candidate *backed by* America, to many people’s surprise). Next year the country *will join* the three-member Board of Auditors, which *keeps an eye on* the UN’s accounts.

The senior jobs *being taken by* China’s diplomats *are* mostly boring ones in institutions that few countries *care much about*. But each post *gives China control of* tiny levers of bureaucratic power *as well as* the ability *to dispense favours*. “Each one of these slots *has influence(n.) with* somebody somewhere,” says a European diplomat. When votes *are taken* on matters(n.) China *regards as* important, its diplomats *often use* a blunt transactional approach -- *offering financing for* projects, or *threatening to turn off the tap*. This *buys* China clout, if not affection, other diplomats say.

Mr Xi’s influence is evident. `主` Much of the language that Chinese officials *try to insert into* UN documents `谓` *uses* his catchphrases, such as “win-win co-operation” and “a community with a shared future for mankind” (*keep your hands off* China, *is* the underlying sentiment). For three years in a row, Chinese diplomats *managed to inject* favourable references to Mr Xi’s Belt and Road Initiative (BRI), a “win-win” global infrastructure-building scheme, *into* resolutions on Afghanistan. They *have persuaded* senior UN officials, including the secretary-general, António Guterres, *to praise* the BRI in speeches *as* a model for global development. In 2018 China *convinced* the UN Human Rights Council in Geneva (from which America *withdrew* later that year) *to endorse* its preferred approach of “*promoting* mutually beneficial co-operation” in this field, ie, *refraining from* criticism.

More than merely language *is involved*. In 2017 China *sought successfully to cut funding for* a job *intended to ensure that* all of the UN’S agencies and programmes *promote human rights*. That same year Wu Hongbo, a Chinese diplomat who was then *in charge of* the UN Department of Economic and Social Affairs, *expelled* Dolkun Isa, a Uighur activist, *from* a UN forum *to which* Mr Isa *was an invited delegate*, *representing* a German NGO (Mr Isa *was eventually let back in* after protests from American and German diplomats). Mr Wu, whose post *required him to be* non-partisan, later *boasted about his actions* on Chinese state television. “We *have to strongly defend* the motherland’s interests,” he said.

Opposition to China’s more assertive approach *may grow*. “I think *they are overdoing it* and I think at some stage *people will start to resist*,” says the Security Council diplomat. But some others at the UN *do not share that view*. Smaller states in Africa and the Middle East, many of them dictatorships, *resent* America’s post-cold-war dominance of the UN. *Why should China not push back*, *asks* a diplomat from one country in that part of the world. The envoy *says that* countries *may be subjected to pressure*(n.) from China when it wants something, but that America, albeit *not as blunt*, *can also be* transactional. Some smaller countries *may welcome* having two great powers *competing for* their favour again.

“There’s a degree of hypocrisy about it,” says Richard Gowan of the International Crisis Group, a conflict-prevention NGO. “It *would be weird* to imagine that China *as* a rising power *wouldn’t want a bigger stake* in the multilateral system.” Few *would imagine that* now.

---



