= 0100
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to another lesson here with us at EnglishPod! My 
name is Marco. +
E: And I’m Erica. +
M: And today we’re going to have a very casual, normal conversation. +
E: That’s right, we’re gonna listen in on some small talk between a taxi driver and the 
passenger. +
M: Small talk, so, that’s basically… +
E: Hmm, small short conversations you have with someone that you don’t know very well. +
M: Okay, so, typical questions like “How old are you?”, “Where are you from?” +
E: Yep. +
M: Et cetera. 
E. That’s right. And this can be really hard for English learners, cause they often don’t know
what the right thing to say or the right think to talk about, so, we’re gonna give you a lot of
phrases in this lesson that you can use in small talk. +
M: Okay, so, we don’t have anything to preview today, so, let’s listen to the dialogue for the 
first time and then we’ll come back. +
A: Where to, miss? +
B: Hi! Crenshaw and Hawthorne, at the Holiday Inn 
that is on that corner. +
A: Sure thing. So, where are you flying in from? +
B: From China. +
A: Really? You don’t look very Chinese to me, if you 
don’t mind me saying so. +
B: It’s fine. I am actually from Mexico. I was in China 
on a business trip, visiting some local companies
that manufacture bathroom products. +
A: Wow sounds interesting! Excuse me if I am being 
a bit nosy but, how old are you? +
B: Don’t you know it’s rude to ask a lady her age? +
A: Don’t get me wrong! It’s just that you seem so 
young and already doing business overseas! +
B: Well thank you! In that case, I am 26 years old, 
and what about yourself? +
A: I am 40 years old and was born and raised here 
in the good old U.S of A, although I have some
Colombian heritage. +
B: Really? That’s great! Do you speak some Span- 
ish? +
A: Uh... yeah.. of course! +
B: Que bien! Entonces podemos hablar en espanol! +
E: Alright, so, I don’t think this guy spoke much Spanish, do you? +
M: No, even though he has Colombian heritage, I think he doesn’t speak much, but maybe 
he’s just a little bit rusty. +
E: Maybe, but was he does speak is English and since this isEnglishPod, why don’t we look 
at some of the phases that they used for small talk in “fluency builder”? +
Voice: Fluency builder. +
M: Alright, so, today on fluency builder we’re gonna take a look at phrases that both the 
passenger and the taxi driver used to make small talk. So, why don’t we start with the first
one? +
E: Alright, so, the taxi driver tells the passenger that she doesn’t look very Chinese, if you 
don’t mind me saying so. +
M: Right, so, he said “you don’t look very Chinese to me, if you don’t mind me saying so”. +
E: If you don’t mind me saying so. +
M: So, what does he mean by this last part of the sentence? +
E: Well, this is a phrase that we use, um, to soften a sort of… a statement that might be a 
little bit rude. +
M: She could be Chinese. +
E: Yeah. +
M: Right? So, it maybe a little bit rude to say that, but he kind of apologizes. +
E: That’s right. +
M: Right? By saying if you don’t mind me saying so. +
E: Okay, so, for example, I could say “hey, Marco, you look a little tired today, if you don’t 
mind me saying so”. +
M: Okay, so, does it always go at the end? +
E: You could use it at the beginning – “if you don’ mind me saying so, I just don’t think this 
is a good idea”. +
M: Okay, very good. So, you can use this phrase in the beginning or at the end of 
a sentence. +
E: Right, and it makes your statement a little bit less rude. +
M: If you don’t mind me saying so. Now, again he also apologizes a little bit when he says 
”excuse me if I’m being a bit nosy, but…” +
E: Excuse me if I’m being a bit nosy, but. +
M: Excuse me if I’m being a bit nosy, but. +
E: Okay, so, let’s take a look this nosy, what’s this? +
M: Okay, when somebody is nosy, it means they’re very curious, they’re asking too many 
questions. +
E: Yeah, asking more questions, then they should ask. +
M: Right, so, he apologizes and says “well, excuse me if I’m asking too many questions” 
and then he asks her another question. +
E: He asked her how old she is. +
M: Right, so, again it’s a polite way of maybe asking a question that might be a little bit 
sensitive. +
E: Yeah, or a little bit impolite. +
M: Okay, so, of course, asking a woman her age maybe is a little bit impolite, right? +
E: Yes, typically women don’t like that too much. Um, but our next phrase – we heard the 
taxi driver say “don’t get me wrong”. +
M: Don’t get me wrong. +
E: Don’ get me wrong. +
M: Okay, so, don’t get me wrong - he says, well, “don’t misunderstand what I’m saying” +
E: That’s right, this phrase is used so commonly in English, though I think it would help us 
to hear some examples. +
Voice: Example one. +
A: Don’t get me wrong. It’s not that I think you stole my computer; it’s just that you were 
the only one who could get into my room. +
Voice: Example two. +
B: I do have a few problems with the plan, but don’t get me wrong, I still think it’s a good 
idea. +
Voice: Example three. +
C: Don’t get me wrong, I think John’s a nice guy, he’s just a bit disorganized. +
M: Alright, very good examples, so, don’t get me wrong, right? +
E: That’s right. +
M: And now for the final phrase on putting it together today. [NOTE: on fluency builder, 
actually] +
E: Well, the passenger, the woman, um, says her… her age, um, she says “I’m twenty six 
years old and what about yourself?” +
M: What about yourself. +
E: What about yourself. +
M: Alright, now, this sentence isn’t very correct, actually, right? +
E: Yeah, technically it’s not correct in grammar, but it is used so commonly everyday by 
American English speakers that we thought we’d show it to you. +
M: Okay, so, you would say “I’m twenty six years old and what about you?” +
E: That’s right. +
M: Okay, but commonly you will hear people say “what about yourself?” +
E: And if you use this, um, you’ll sound really fluent and really native-like. +
M: Okay, very good, so, what about yourself. +
E: So, again, it’s… it’s just like “what about you”, so, I could say, um, “hey, Marco, 
I’m… I’m going away on holiday this weekend and what about yourself?” +
M: Okay, what about yourself. So, we’ve taken a look at these four phrases on putting it 
together, why don’t we listen to the dialogue for the second time? We’re gonna slow it down
a little bit and then we’ll come back and take a look at some vocabulary words on
“language takeaway”. +
A: Where to, miss? +
B: Hi! Crenshaw and Hawthorne, at the Holiday Inn 
that is on that corner. +
A: Sure thing. So, where are you flying in from? +
B: From China. +
A: Really? You don’t look very Chinese to me, if you 
don’t mind me saying so. +
B: It’s fine. I am actually from Mexico. I was in China 
on a business trip, visiting some local companies
that manufacture bathroom products. +
A: Wow sounds interesting! Excuse me if I am being 
a bit nosy but, how old are you? +
B: Don’t you know it’s rude to ask a lady her age? +
A: Don’t get me wrong! It’s just that you seem so 
young and already doing business overseas! +
B: Well thank you! In that case, I am 26 years old, 
and what about yourself? +
A: I am 40 years old and was born and raised here 
in the good old U.S of A, although I have some
Colombian heritage. +
B: Really? That’s great! Do you speak some Span- 
ish? +
A: Uh... yeah.. of course! +
B: Que bien! Entonces podemos hablar en espanol! +
E: Well, we’ve got some interesting vocabulary words and phrases here in language 
takeaway and the first one… +
M: Well, after she gets in the taxi and tells him where she wants to go he answers by 
saying sure thing. +
E: Sure thing. +
M: Sure thing. +
E: Sure thing. +
M: So, if I say “yeah, sure thing”, what does that mean? +
E: Well, let’s listen to some examples to help us understand. +
Voice: Example one. +
A: Do you mind lending me a hundred bucks? +
B: Sure thing. +
Voice: Example two. +
C: Could you please send me the e-mail by the end of the day? +
D: Sure thing. +
Voice: Example three. +
E: Do you mind lending me a hundred bucks? +
F: Sure thing. +
G: Could you please send me the e-mail by the end of the day? +
H: Sure thing. +
Voice: Example four. +
I: Can you get some milk on your way home? +
J: Sure thing, I’m on my way now. +
M: Okay, so, sure thing, basically “yea, no problem” or “okay”. +
E: Or I’ll do it. +
M: I’ll do it. +
E: Yep. +
M: It’s fine. +
E: Yep. +
M: So, it’s a very common way, you will hear this a lot when somebody agrees or says “yes, 
no problem”. +
E: Yeah, and again it will help you sound really native-like to use this phrase. Well, the next 
one – the taxi driver says, um, “I was born and raised here”. +
M: I was born and raised here. +
E: Born and raised. +
M: Okay, so, this is a way of saying I was born in this country and I haven’t left this 
country. +
E: That’s right, so, I’m from this country. +
M: Okay, born and raised here in the good old U.S. of A. +
E: Good old U.S. of A. +
M: The good old U.S. of A. +
E: So, this is a pretty interesting way of saying America. +
M: Right, it’s actually more of a phrase, right? The good old U.S. of A. +
E: Yep. +
M: Okay, so, it means the good United States of America. +
E: Yeah, it’s kind of a fond way or friendly way of describing America. +
M: Alright, and we have one more word for language takeaway. +
E: Well, the taxi driver was talking about his Colombian heritage. +
M: Colombian heritage. +
E: Heritage. +
M: Alright, so, if I have Colombian heritage, what does that mean? +
E: Your grandmother or, you know, grandfather, great grandmother or someone in your 
family is from Colombia. +
M: Okay, and what about the word heritage by itself? +
E: Yeah, so, your heritage is basically your culture, um, your… +
M: Customs. +
E: Yeah, your customs, your… your history. +
M: Okay, so, heritage. +
E: Uhu. +
M: A country rich in heritage. +
E: Lots of, uh, good old historical culture in that country. +
M: Okay, very good, so, now it’s time for us to listen to the dialogue for the last time, now 
we can understand all this phrases and these great words that we’ve just looked at and then
we’ll come back and talk a little bit more. +
A: Where to, miss? +
B: Hi! Crenshaw and Hawthorne, at the Holiday Inn 
that is on that corner. +
A: Sure thing. So, where are you flying in from? +
B: From China. +
A: Really? You don’t look very Chinese to me, if you 
don’t mind me saying so. +
B: It’s fine. I am actually from Mexico. I was in China 
on a business trip, visiting some local companies
that manufacture bathroom products. +
A: Wow sounds interesting! Excuse me if I am being 
a bit nosy but, how old are you? +
B: Don’t you know it’s rude to ask a lady her age? +
A: Don’t get me wrong! It’s just that you seem so 
young and already doing business overseas! +
B: Well thank you! In that case, I am 26 years old, 
and what about yourself? +
A: I am 40 years old and was born and raised here 
in the good old U.S of A, although I have some
Colombian heritage. +
B: Really? That’s great! Do you speak some Span- 
ish? +
A: Uh... yeah.. of course! +
B: Que bien! Entonces podemos hablar en espanol! +
E: So, Macro, this, uh, taxi driver makes a bit of mistake when he asks the woman how old 
she is. +
M: Yes, um… Yeah, exactly, there’re a couple of questions that in some cultures are 
considered to be normal and okay. +
E: Uhu, yeah. +
M: But in other cultures they’re not really well-accepted. +
E: Okay, so, in Anglo culture, for example, um, it’s really impolite to ask a woman how 
old she is. +
M: Right, women are a little bit more sensitive about their age… Others aren’t so much, but 
it’s usually better to just not ask. +
E: Yep. And what else should we avoid talking about in small talk? +
M: Well, for example, when you ask a person their occupation… +
E: Yeah. +
M: You can ask what they do for a living, but don’t ask how much money they make. +
E: That’s right, Anglo people are really sensitive about taking about money. We hate talking 
about money. +
M: Hehe. Right, so, don’t ask somebody their salary or how much money they make, it’s 
just not considered to be polite. +
E: And another good one to be careful of is asking if someone is married or not. +
M: Right, sometimes you’re just being friendly and… +
E: Yeah. +
M: You wanna know if that person has family or something. +
E: Yeah. +
M: But you have to be careful when and where you ask this question. +
E: Right, so, if they’ve mentioned their family, if they’ve talked about their kids or, um, 
something else to do with their family, then it’s okay. +
M: Right, you can say, well, “oh, how long have you been married?” +
E: Yeah. +
M: But if a guy asks a girl “oh, are you married?”, it kind of sounds like maybe he’s 
interested in her or that he’s trying to… to come on to her and… and to be maybe more
than friendly, right? +
E: That’s right. +
M: Okay. +
E: So, some great small talk tips and phrases here at EnglishPod, now if you have any 
questions about this lesson or any other lessons, be sure to visit our website
at englishpod.com. +
M: And if you also have any doubts about which questions you think are appropriate of 
asking somebody, yeah, come in to the website and let us know. +
E: So, thanks for downloading you guys and until next time… Good bye! +
M: Bye! 

  
