= 0856
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 856: Training Salespeople.
This is English as a Second Language Podcast episode 856. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode is, like all of our episodes, one that has a Learning Guide. You can find that guide at ESLPod.com.
Today we’re going to talk about training salespeople – people who, well, sell things. Let’s get started.
[start of dialog]
Our company brought in a consultant to do sales training for our store. For some reason, we’d been getting some complaints from customers.
Consultant: My job in this training is to help your store improve its customer satisfaction, so that it can attract and retain more customers. When you interact with customers, you represent this store. It is very important that, from the get-go, customers are greeted in a friendly and positive way.
Employee: Sometimes, people are really rude. They don’t even say “hello” back.
Consultant: That may be true, but it’s still your job to make them feel welcomed. Each customer should feel that a salesperson is attentive and trying to meet their needs.
Employee: Some of them don’t even know what they want. They wander around and waste our time.
Consultant: Part of your job is to help them define their needs, offer them options, and lead them to a decision. I know that you’re not working on commission, but this is a very important part of your job.
Employee: You mean I have to hold their hand the whole time they’re in the store? Who am I, their mother?
Consultant: I can see that we have a lot of work to do. Let’s get started.
[end of dialog]
Our story begins with an employee of a certain company telling us that his company brought in a “consultant to do sales training for our store.” A “consultant” (consultant) is a person that a company hires to either complete a specific project or often, to provide help to employees, permanent employees, of a company. The consultant only works, typically, for a short amount of time. Maybe a company needs someone to help them with accounting or maybe they need someone to help them as, in the case of our story, with selling and helping their sales people sell better.
That’s what this consultant did. She came in to do sales training to help the sales people – the salesmen and saleswomen – sell better. “For some reason, we’ve been getting some complaints from customers.” “Complaints” (complaints) are when people say they don’t like what you are doing. Often, they are saying that things are not as good as they should be. This shirt is too small. It’s too cold in here. This food tastes horrible. Those would all be complaints in different areas to different kinds of companies. “To complain” is the verb.
Well, this company, this store, has been getting complaints from customers – people who buy things. The consultant begins by saying, “My job” – or my task – “is to help your store improve its customer satisfaction.” “Satisfaction” is a measure of how well you like something. So, “customer satisfaction” would be how much the people who buy from your store like what they’re getting, like the experience of buying in your store and so forth.
The consultant is doing this so that the store can attract and retain more customers. “To attract” means to get more. “To retain” (retain) means to keep them. So, in any sort of business where you sell something, first you have to get people to buy something from you once, and the idea is you want to keep them coming back and buying from you again and again. That’s to retain a customer.
The consultant says, “When you interact with customers, you represent this store.” “To interact” (interact) is to have some sort of communication with another person or some other sort of exchange of information. Talking to someone would be an “interaction,” to use the noun. “I am interacting with a customer.” We use this term as an adjective – “interactive” – to mean something that you can do on a computer or on an electrical device like a tablet or a phone, a smartphone, that allows you not just to get information but to give information back to whoever designed that particular program. So, “interact” has a couple of different meanings including, as I said, one that is now related to an adjective, “interactive,” in dealing with software, computer software.
Moving on here, the consultant says that “when you interact with customers, you represent this store.” When you “represent” some group or some organization, people see you as someone who is speaking for and acting on behalf of that organization. So, when you walk into a store and the person, the salesperson, isn’t very nice to you, you get a bad idea, a bad impression about that store. The salesperson represents the store. The store is represented by its salespeople.
The consultant continues, “It is very important that from the get-go, customers are greeted in a friendly and positive way.” The expression “from the get-go” means from the very beginning, from the very first moment. “I knew that he was going to lose the game from the get-go.” As soon as he started, I knew he was going to lose. It’s a somewhat informal expression, perhaps not quite as common as it was a few years ago.
In any case, the consultant says that “It is very important that from the get-go, customers are greeted in a friendly and positive way.” “To be greeted” means to have someone say ‘hello’ to you. “To greet” is to say, ‘hello,’ to make another person feel welcome. Many times when you walk into a store in the United States, there’ll be someone working for the store standing in the doorway or towards the front of the store, to welcome you into the store. “Hello, thank you for coming. Can I help you with anything?” That would be someone greeting you. “To greet” can also just mean to say “hello.” I greeted my friend when I saw her in the parking lot. I said “hello” to her.
The employee says, “Sometimes people are really rude. They don’t even say ‘hello’ back.” So the employee is already sort of doubting the consultant’s advice. He says, “Sometimes people are really rude. “To be rude (rude)” means not nice, not kind, to be mean, to be impolite. “They don’t even say ‘hello’ back,” meaning you say “hello” to them, but they don’t say “hello” to you. That’s what the word “back” means here – in return, in response to you.
The consultant says, “That maybe true” – maybe you’re right – “but it’s still your job to make them feel welcomed” - that is, make them feel like you’re happy they are there. “Each customer should feel that a salesperson is attentive and trying to meet their needs.” “To be attentive” (attentive) means to give your full attention or full focus to something, to be paying attention. A waiter in a restaurant who is attentive is always checking back to make sure if you need anything, is always making sure you have enough water or enough soda, or enough whatever it is that you’re drinking – beer, wine, whiskey. You get the idea.
The consultant says that a salesperson is attentive and tries to meet the customer’s needs. “To meet someone’s needs” is to do what that person needs or expects. The employee says, “Some of them” – meaning some of the customers – “don’t even know what they want. They wander around and waste our time.” “To wander (wander) around” means to walk around slowly through an area without any clear purpose, without any goal. You’re not quite sure what you’re doing. You’re just kind of walking. You’re wandering or wandering around. The employee is complaining some that some people come into the store and they wander around and they don’t really know what they want.
The consultant says, “Part of your job is to help them define their needs.” “To define (define)” can mean to give the meaning of a word. Here, however it means to identify, to describe something, to, we might say, “clarify,” to make clear what that person might want, or in this case, what they might need. So the consultant says that “Part of your job is to help them define their needs, offer them options” – choices – “and lead them to a decision. I know that you’re not working on commission but this is a very important part of your job.” “To be working on commission” means that you get a percentage of everything you sell. In some stores, especially those that sell expensive things, the salesperson will get a small percentage of every sale. This, of course, gives them a motivation, a good reason for wanting to do a good job. In other stores, the salesperson doesn’t get any commission, and often, when that happens, the salesperson doesn’t do a very good job.
The employee, who’s obviously not a very good salesperson, says, “You mean” – do you mean – “I have to hold their hand the whole time they’re in the store?” “To hold someone’s hand” here means to help them and to guide them every step of the way – giving them advice, giving them encouragement, telling them how good something looks on them, to be paying attention to them the whole time. The employee says, “You mean I have to hold their hand the whole time they’re in the store? Who am I, their mother?” The employee is making a joke saying, “Well, I’m not their mother. I don’t have to pay attention to them and hold their hand walking around the store.” When we say “to hold their hand,” we don’t mean you actually hold their hand with your hand. We mean to pay attention, to pay close attention to them. The consultant says, “I can see that we have a lot of work to do.” This expression means that there are a lot of problems here, as demonstrated by the responses of this employee – this salesperson. So, they have a lot of work to do, a lot of changes to make. “Let’s get started.”
Now let’s listen to the dialog, this time at a normal speed.
[start of dialog]
Our company brought in a consultant to do sales training for our store. For some reason, we’d been getting some complaints from customers.
Consultant: My job in this training is to help your store improve its customer satisfaction, so that it can attract and retain more customers. When you interact with customers, you represent this store. It is very important that, from the get-go, customers are greeted in a friendly and positive way.
Employee: Sometimes, people are really rude. They don’t even say “hello” back.
Consultant: That may be true, but it’s still your job to make them feel welcomed. Each customer should feel that a salesperson is attentive and trying to meet their needs.
Employee: Some of them don’t even know what they want. They wander around and waste our time.
Consultant: Part of your job is to help them define their needs, offer them options, and lead them to a decision. I know that you’re not working on commission, but this is a very important part of your job.
Employee: You mean I have to hold their hand the whole time they’re in the store? Who am I, their mother?
Consultant: I can see that we have a lot of work to do. Let’s get started.
[end of dialog]
She’s always trying to meet your needs as a learner of English. I speak, of course, of our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan, thank you for listening. Come back and listen to us again, right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
consultant – a person who is hired to complete a specific project or provide a specific service for a defined period of time
* The company hired a consultant to determine which types of computers and printers to buy.
sales – the process and technique used in encouraging customers to buy the goods and services a company is selling
* People who work in sales need to have great communications skills.
training – a formal effort to improve participants’ skills, knowledge, or abilities in a specific area
* Our employer pays for a lot of computer training for employees.
complaint – a statement that something did not meet one’s expectations or standards; a statement that something was not as good as it should have been
* If the unfair treatment doesn’t stop soon, Jessie is going to file a complaint with the human resources department.
customer satisfaction – a measure of how pleased or displeased customers are with their experience interacting with a company and its products and services
* Please fill out the enclosed customer satisfaction survey about your experience buying a camera in our store.
to retain – to keep someone or something, not letting him/her/it leave or get away
* It’s more cost-effective to focus on retaining current employees than hiring a lot of new employees.
to interact – to have some communication or an exchange with another person
* How many co-workers do you interact with on a normal day?
to represent – to be part of some group or organization and have one’s words and actions be perceived as relating to that group or organization
* If you wear your uniform, you’re representing the U.S. Army, even during the hours you’re not working.
from the get-go – from the very beginning; from the first moment
* She didn’t like him from the get-go and nothing he did changed her opinion.
to greet – to say hello to someone and make him or her feel welcome
* When I go into a store, I expect to be greeted within the first few seconds.
rude – impolite; treating people in a way that may be offensive, annoying, mean, or discourteous
* In most situations, it is rude to ask a woman how old she is or how much she weighs.
back – in return; in response; doing the same thing to a person that he or she just did to oneself
* If I had seen you wave, I would have waved back.
attentive – paying attention; giving one’s full attention to something
* Psychologists can learn a lot about their patients by being attentive to body language.
to meet (one’s) needs – to fulfill one’s needs; to produce or do what another person needs or expects
* Does this set of luggage meet your needs, or do you need suitcases that are larger?
to wander around – to walk slowly through and around an area without a clear purpose
* Why are all these students wandering around the halls? Shouldn’t they be in class?
to define – to clarify; to correctly identify something; to describe something in detail
* Real estate agents are trained to help buyers define what they are looking for in a new home.
commission – a fixed amount of money or a percentage of each sale that is given to the salesperson as a way for the company to encourage more sales
* Quentin works on commission, so during a month when he makes a lot of sales, he does very well, but during slower months he barely has enough money to pay his rent.
to hold (one’s) hand – to guide and help someone through every step of a process, providing detailed instruction, reassurance, and/or encouragement
* A mentor will provide information and support, but he won’t hold your hand through every step of opening your own business.
Comprehension Questions
1. Why does the store want to improve customer satisfaction?
a) So it can keep more of its customers.
b) So it can meet government requirements.
c) So it can avoid being reported to the Better Business Bureau.
2. According to the employee, what do customers do when they’re in the store?
a) They ask a lot of unimportant questions.
b) They try to steal the products.
c) They walk through the store without knowing what they want.
Answers at bottom.
What Else Does It Mean?
to retain
The verb “to retain,” in this podcast, means to keep someone or something and not letting him/her/it leave or get away: “How can we retain our employees when our competitors pay so much more than we do?” Or, “We’re supposed to retain our tax documentation for at least seven years.” The verb “to retain” can also mean to remember something: “Are you able to retain what you hear in lectures if you don’t take notes?” A “retainer” is an amount of money paid to keep a consultant or another professional working for oneself: “We pay Bethany a retainer of $1,000 per month.” Finally, A “retainer” is also a small piece of plastic and wire put in one’s mouth at night to prevent one’s teeth from moving back to an incorrect position: “Amanda takes out her retainer to eat, but she leaves it in during the rest of the day.”
back
In this podcast, the word “back” means in return or in response, doing the same thing to a person that he or she just did to oneself: “I’m pretty busy right now. Can I call you back in half an hour?” The word “back” also means putting something into its previous position: “You can look at the photo albums, but please put them back when you’re done.” The phrase “back home” refers to the place one comes from, especially if one no longer lives there: “Do you usually go back home for Thanksgiving?” Finally, the phrase “back to” refers to a time in the past, or something from history: “The first reports on this topic date back to the 1920s.”
Culture Note
Automated Customer Service
With the “advance” (progress; improvement) of technology, “automated customer service” or the practice of using machines to interact with customers instead of people, is becoming “increasingly common” (used more often). Automated customer service has many benefits, but it also has “drawbacks” (disadvantages).
From the company’s “perspective” (outlook; way of seeing things), automated customer service is less expensive, because the company does not need to hire as many “customer service representatives” (people who interact with customers). The computers can answer many “inquiries” (questions) from customers or at least “direct them” (point them toward) the appropriate department or individual. Automated customer service is also more “consistent” (happening in the same way each time), because each caller hears the same greeting and receives the same set of responses.
The drawbacks are more “apparent” (easily seen) from the customers’ perspective. Many callers become frustrated when their calls are answered by computers. People “tend to” (usually) dislike having to choose from a long “menu of options” (choices, such as “press 1 for billing, press 2 for location, etc.) when they believe it would be faster to ask their question to a “real live person” (not a computer). Callers also become frustrated if their response is misunderstood by the computer and they have to repeat it several times.
Another drawback is that automated customer service is not personalized. Many companies want to develop a long-term relationship with their customers, but the use of automated customer service “presents” (shows; creates) a “barrier” (obstacle) to that relationship. Some companies, particularly small banks, try to “differentiate themselves” (show how they are different from and better than competitors) from others by advertising that callers always have the opportunity to speak to a real person, not a computer.
Comprehension Answers
1 - a
2 - c