= 0863
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 863: Limiting Free Speech.
This is English as a Second Language Podcast episode 863. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast. If you do, you can download a Learning Guide for this episode.
This episode is a dialog between Toshi and Celeste, about freedom of speech. Let’s get started
[start of dialog]
Toshi: You can’t go outside looking like that! What are you thinking?
Celeste: I’m exercising my right of free speech. I’ve put on these clothes and painted my body this way to protest the treatment of women. I want to send a message.
Toshi: You’re crazy if you think people are going to take you seriously. What you’re wearing is offensive and those messages painted on your body are hate speech.
Celeste: It’s my basic human right to a freedom of expression, and this is how I choose to express myself.
Toshi: There are limits to free speech and expression, and you’ve crossed the line. In fact, you’re abusing those rights. Obscenity and hate speech aren’t protected, you know.
Celeste: If you feel so strongly about it, I have a suggestion for you.
Toshi: What?
Celeste: You can express your free speech by protesting against me. After all, it’s your inalienable right.
Toshi: I’m not wasting my time. Hey, you’re not really going outside looking like that, are you?
Celeste: You know what they say: The medium is the message. And I’m sending my message loud and clear!
[end of dialog]
Our dialog begins with Toshi saying to Celeste, “You can’t go outside looking like that! What are you thinking?” We’re not sure what Celeste looks like but Toshi doesn’t like it. Celeste says, “I’m exercising my right of free speech.” “To exercise” (exercise) here means to use, usually to use your abilities or your rights or your privileges to do something. The verb “to exercise” is often used with the word “right” or “”rights” in referring to your ability to do things that you are legally allowed to do.
“The right of free speech” is the legally protected ability that you have to give your opinion, to express your ideas in public. Of course, that’s not always true in every situation. In general, that’s the meaning of the term “free speech” – the ability to say what you want. “Free” here doesn’t mean the opposite of “expensive” or having to pay for it. It means that you have the freedom that you are allowed to say what you want. That’s what we mean by “free speech.”
Celeste says, “I’ve put on these clothes and painted my body” – put colored paint on her body – “this way to protest the treatment of women.” “To protest” (protest) means to fight against something, to express your disagreement of something, usually in public. Celeste says, “I want to send a message,” meaning I want to communicate my opinion, my ideas to someone else - in this case, to people who see her at this protest that I guess she’s going to.
Toshi says, “You’re crazy if you think people are going to take you seriously.” “You’re crazy” means that you have lost your mind, that you are not thinking properly. “You’re crazy if you think people are going to take you seriously,” Toshi says. “To take someone seriously” means to consider what another person is doing or saying, and thinking that it’s a serious message. You don’t think that they’re silly or stupid or foolish. “To take something seriously” can also mean to treat it as though it is an important thing, not just to ignore it or to think, “Oh, that’s not important.”
Toshi says, “What you’re wearing is offensive and those messages painted on your body are hate speech.” If something is “offensive” (offensive) it’s something that is insulting. It hurts other people’s feelings. It might be rude. It might make other people mad or upset. All of those things could be considered “offensive.” “Hate speech” is a relatively new idea that words that express very bad, negative things about other people because of certain characteristics they have, should somehow be treated differently than other opinions. So, there’s “free speech,” which is the freedom to say what you want. Now people, some people, talk about “hate speech,” which are things that you should not be allowed to say because they are so offensive to other people.
Celeste says, “It’s my basic human right to freedom of expression.” The term “human right” refers to something that everyone should be allowed to do, no matter where you are, where you live, what government you have. That would be a human right. Not everyone agrees on what those rights are, but most people believe that there are things such as human rights that everyone should have. Celeste believes that one of her “basic” – one of her fundamental, one of her most importan – human rights is “freedom of expression.” “Freedom of expression” is just another word for freedom of speech. “This is how I choose to express myself.” “Expression” can actually mean a little bit more than just speech, in the sense of “words.” “Expression” might also include your actions or, in this case, how you dress – or don’t dress.
Toshi says, “There are limits” – there are restrictions – “to free speech and expression, and you’ve crossed the line.” The phrase “to cross the line” means to go too far, to go beyond what you are allowed to do or what you should do. Toshi says, “In fact, you’re abusing those rights.” “To abuse” (abuse) means to use something for the wrong purpose, perhaps, to use too much of something or to hurt someone in some way that you do not have the right to do, that you should not do. Toshi thinks that Celeste is abusing her right of free speech.
He says, “Obscenity and hate speech aren’t protected you know?” “Obscenity” (obscenity) refers to words, images, or actions that are considered very rude, very offensive, especially when it refers to sex or sexuality. “Obscenity” is one of those things that is very difficult to define. There has been a debate in the United States for many years about what obscenity is. One of the famous quotes from the Supreme Court – one of the justices on the Supreme Court – about what obscenity is and how to define it, was, “I know it when I see it.” In other words, he couldn’t give a definition of obscenity but he knew what obscenity was when he saw it. A lot of people were not very happy with that definition but that’s what he said.
“Obscenity and hate speech,” Toshi says, “aren’t protected.” “Protected” means that the law allows you to do something – that the law prevents you from being punished because of your actions, in this case, your speech. Toshi says that “Obscenity and hate speech aren’t protected,” meaning you’re not allowed to do that and call it free speech. Celeste says, “If you feel so strongly about it” – if you have such a strong opinion about it – “I have a suggestion for you.” Toshi says, “What?” Celeste says, “You can express your free speech by protesting against me. After all, it’s your inalienable right.”
“Inalienable” (inalienable) is something that cannot be taken away from a person. The word was famously used in the Declaration of Independence, written by Thomas Jefferson, saying that the American colonies were no longer going to be part of Great Britain, that the colonists – the people who lived in the American colonies – had “inalienable rights,” rights that Great Britain could not take away from them. Jefferson named three – life, liberty (or freedom), and the pursuit of happiness – the right to be able to find things that make you happy.
Toshi says, “I’m not wasting my time. Hey, you’re not really going outside looking like that, are you?” Celeste says, “You know what they say: The medium is the message. And I’m sending my message loud and clear.” The phrase “the medium is the message” was used famously by the Canadian writer and philosopher Marshall McLuhan back in the 1960’s to mean that the way that a message is delivered affects its meaning, that a message changes depending on how the message is communicated, how it is delivered. That’s a very simple explanation of what McLuhan was talking about. Celeste says, “The medium is the message,” meaning I’m going to send a message by the way I’m dressed. She says she’s sending her message “loud and clear.” “Loud and clear” means everyone can understand it. There’s nothing hidden. It’s easy to understand.
Now let’s listen to the dialog this time, at a normal speed.
[start of dialog]
Toshi: You can’t go outside looking like that! What are you thinking?
Celeste: I’m exercising my right of free speech. I’ve put on these clothes and painted my body this way to protest the treatment of women. I want to send a message.
Toshi: You’re crazy if you think people are going to take you seriously. What you’re wearing is offensive and those messages painted on your body are hate speech.
Celeste: It’s my basic human right to a freedom of expression, and this is how I choose to express myself.
Toshi: There are limits to free speech and expression, and you’ve crossed the line. In fact, you’re abusing those rights. Obscenity and hate speech aren’t protected, you know.
Celeste: If you feel so strongly about it, I have a suggestion for you.
Toshi: What?
Celeste: You can express your free speech by protesting against me. After all, it’s your inalienable right.
Toshi: I’m not wasting my time. Hey, you’re not really going outside looking like that, are you?
Celeste: You know what they say: The medium is the message. And I’m sending my message loud and clear!
[end of dialog]
Our scriptwriter takes her job very seriously. I speak, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again, here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to exercise – to use an ability, right, or process; to do or implement something
* Why don’t you exercise your excellent organizational skills by helping us improve this community organization?
right of free speech – the legally protected ability to express one’s opinions and thoughts
* News reporters rely on the right of free speech to write unfavorable stories about important people in power.
to protest – to fight against something; to express one’s disagreement or disapproval; to oppose in a public way, usually with many other people
* Did you participate in the anti-war protests when you were a college student?
to take (someone) seriously – to truly consider what another person is doing or saying, without thinking that the person is foolish or silly
* If you go to a job interview with bright pink hair, do you think it will be hard for the employer to take you seriously?
offensive – insulting; hurting other people’s feelings or sensibilities; rude and upsetting to other people
* Jenna told the joke because she thought it was funny. She didn’t realize it would be so offensive to her co-workers.
hate speech – words that express very bad and mean things about other people based on their characteristics, such as their race (skin color) or sexual orientation, especially when used to make others feel the same way and/or act violently toward the group
* The police are investigating an instance of hate speech to determine whether a crime has been committed.
human right – something that all people should be allowed to do under the law
* Some people believe that a good education should be a basic human right.
freedom of expression – the legally protected ability to express one’s opinions and thoughts through words, dress, actions, and more
* When an artist puts Santa Claus on the Christian cross, is it freedom of expression or a sign of hatred against Christians?
to cross the line – to go too far; to upset others by taking something to an extreme, going beyond the normal limits or standards
* Barry has always been a difficult boss to work for, but he crossed the line when he started yelling at his employees in front of clients.
to abuse – to use something for the wrong purpose; to use too much of something in a way that is unfair or harmful to other people
* Why do so many dictators abuse their power?
obscenity – words, images, and actions that are very rude and offensive, especially in a sexual way
* The movie is rated R due to obscenity and violence.
protected – with laws that prevent something from being harmed or damaged
* This natural area is protected, so no hunting is allowed.
inalienable – something that cannot be taken away from a person; innate and natural
* Do you believe people have an inalienable right to choose which career to pursue?
the medium is the message – a phrase by Canadian philosopher Marshall McLuhan, meaning that the way in which a message is delivered affects its meaning and how it is understood
* Our company is trying to identify the best ways to communicate with customers. After all, the medium is the message.
loud and clear – easily understood; direct and straightforward, with nothing hidden or obscured
* When Peter was fired for being lazy, it sent a message that was loud and clear to all the other employees.
Comprehension Questions
1. Why does Celeste want to exercise her right of free speech?
a) Because she thinks it’s wrong to be paid for public speaking.
b) Because she wants society to change its treatment of women.
c) Because she needs to practice her singing voice.
2. Why does Toshi say that Celeste has “crossed the line”?
a) Because her dress is too short.
b) Because she is doing something that is unacceptable.
c) Because she is wasting all her money.
Answers at bottom.
What Else Does It Mean?
to exercise
The verb “to exercise,” in this podcast, means to use something or to do or implement something: “Julie is exercising her writing skills by keeping a blog to document her travels.” Or, “Nobody can exercise control over the weather.” The verb “to exercise” most often means to use one’s body in physical ways to become healthier and stronger and/or to lose weight: “Doctors are recommending at least 30 minutes of exercise at a time, four times a week.” Finally, the phrase “to exercise (an animal)” means to make an animal, usually a pet, engage in physical activity: “Having a dog is a lot of work, because you have to feed it and make sure you exercise it at least once a day.”
to abuse
In this podcast, the verb “to abuse” means to use something for the wrong purpose, or to use too much of something in a way that is unfair or harmful to other people: “Some of the people in this restaurant are really abusing this all-you-can-eat buffet. Just look at how much they’re putting on their plates!” The verb “to abuse” also means to hurt another person by treating him or her in a violent, mean, and/or sexual way: “When parents hit their children hard, it is considered child abuse.” Finally, the phrase “substance abuse” refers to someone’s addition to alcohol and/or other drugs: “Years of substance abuse have led to many medical problems.” Or, “His substance abuse began with marijuana and then moved onto heroin and cocaine.”
Culture Note
The Heckler's Veto
A “heckler’s veto” describes a situation where the government asks a person or organization to not do something in order to “preserve the peace” (keep everyone calm, safe, and controlled), because the government believes that if the action “takes place” (happens), another person or group will create problems, especially a dangerous situation.
For example, an organization may be planning a “controversial” (with many strong, differing opinions) speech. The government may be aware that a group of “demonstrators” (protestors) plans to react angrily or violently. In that situation, the government may issue a heckler’s veto, telling the organization that it cannot hold the speech as planned. Many people consider this to be a “violation” of the organization’s right of free speech, but in some cases the courts have “ruled” (officially decided) that the heckler’s veto is “permissible” (allowed) under the law, especially if the government has reason to believe that violence will “ensue” (happen as a result).
One famous “case” (legal decision) involving a heckler’s veto was Feiner v. New York. In 1949, a man named Irving Feiner was arrested for making an “inflammatory” (designed to make other people angry) speech. The police “anticipated” (believed something would happen) violence, so they asked Feiner to stop his speech. He “refused” (said no) three times, and then the police “arrested him” (too him to jail). Feiner argued that the arrest was a violation of his right of free speech. But the “Supreme Court” (the highest U.S. court) eventually ruled that the police had correctly used a heckler’s veto to “prevent” (not allow to happen) a violent situation.
Comprehension Answers
1 - b
2 - b