= 0864
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 864: Going to Business School.
This is English as a Second Language Podcast episode 864. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this episode.
This episode is a dialog between Karla and Joaquin, about going to school to get a university degree in business. Let’s get started.
[start of dialog]
Karla: I just heard that you’re taking a leave of absence to go to business school. Is that right?
Joaquin: Yeah, I’ve been thinking about it for a long time, and have finally taken the plunge. I need an MBA to get ahead in my career.
Karla: That’s great, but why don’t you go part-time?
Joaquin: I had considered taking classes on nights and weekends while I continue to work, but I’ve been admitted into an Ivy League school, and I want to take full advantage of the opportunities there.
Karla: Isn’t graduate school expensive, especially an Ivy League school?
Joaquin: Yeah, but I think it’s worth it, and I’ve been saving up. I have an undergraduate degree in accounting and finance, but that’s not enough if I want to work in the upper echelons of this or any other company.
Karla: I graduated with a degree marketing and information systems. Maybe I should be thinking about getting an MBA.
Joaquin: I’d recommend it, if you want to go further in your career. I’ll lend you all of my test prep materials for the GMAT.
Karla: The GMAT? I’d forgotten about the GMAT. That may be a deal breaker for me.
Joaquin: Why? You don’t like taking tests?
Karla: I like taking tests as much as I like getting a kick upside the head – maybe even less!
[end of dialog]
Our dialog begins with Karla saying to Joaquin, “I just heard that you’re taking a leave of absence to go to business school.” A “leave of absence” (absence) is a period of time when you leave your job but are allowed to come back to your job when you finish doing whatever you are leaving your job for. Some people may take a leave of absence because a family member is sick or they might take a leave of absence, as Joaquin is doing in the dialog, to go back to school and study some more. Not all companies allow you to take a leave of absence and typically, you’re not paid during your leave of absence. So, it has to be a situation that is either very serious or very important for you.
Joaquin is going to take a leave of absence to go to business school, usually that means going to get a graduate degree after you’ve already completed your undergraduate, bachelor’s degree. Joaquin says, “Yeah, I’ve been thinking about it for a long time and have finally taken the plunge.” The expression “to take the plunge” (plunge) means to decide to do something that is perhaps a little scary, a little risky. You’re not sure what is going to happen but you’re just going to go ahead and do it because you decide that the benefits are going to be greater than the costs; that is, it will help you more than it will hurt you. Joaquin says, “I need an MBA to get ahead in my career.” An “MBA” is a Masters of Business Administration. That’s an advanced degree that provides education for people who are in business or who want to go into the business world but need more education about topics such as finance, marketing, management, and other areas.
Karla says, “That’s great, but why don’t you go part-time?” “Part-time” would be going to school but also doing something else. So, you may be working full-time – eight hours a day – and then at night, you may be going to school part-time. Joaquin wants to go to school full-time. He wants to quit his job and only go to school, or at least, go to school for most of the day and perhaps have a part-time job at night. Joaquin said “I had considered” – I had thought about – “taking classes on nights and weekends while I continue to work, but I’ve been admitted into an Ivy League school and I want to take full advantages of the opportunities there.” The “Ivy (Ivy) League (League)” is a group of private colleges that are considered among the best colleges in the United States. There are, traditionally, eight Ivy League colleges – Columbia University, Brown, Cornell, Dartmouth, Harvard, Princeton, Yale and the University of Pennsylvania. So, Joaquin must be very smart and have a lot of money to get admitted into or accepted into an Ivy League school as a student.
Karla says, “Isn’t graduate school expensive, especially at an Ivy League school?” So immediately Karla asks the question that the average person would ask, which is, “Wow, how can you afford that?” “How can you have enough money?” “Graduate school” is any university education you receive after your bachelor’s degree that usually leads to a master’s degree or a Ph.D. or doctorate in some topic. Joaquin says, “Yeah, but I think it’s worth it and I’ve been saving up.” “To save up” is a two-word phrasal verb meaning to be saving your money for a specific or particular purpose. Maybe you decide not to buy a new car because you want to save up to buy a new house. You want to save your money. So, “to save up” is usually when we save our money for a specific purpose.
Joaquin says, “I have an undergraduate degree in accounting and finance but that’s not enough if I want to work in the upper echelons of this, or any other company.” An “undergraduate degree,” we referred to earlier, is usually called a bachelor’s degree. It’s something that you get after studying at least four years at the university, or in my case, seven years, because I wasn’t very intelligent. You see, it took me a long time.
“Accounting” is the activity of making sure you keep good records of how much money you bring into the company and how much you spend. It’s an organized, what we might describe as “systematic” way of keeping track of or knowing how much money you’re getting and how much money you’re spending. “Finance” is when you are managing a large amount of money for an organization – making sure that the organization has enough money. That would be part of finance.
Joaquin has a bachelor’s degree – an undergraduate degree – in accounting and finance, so he knows something about business. But he says, “That’s not enough” – that’s not sufficient – if he wants to work in the “upper echelons” of his company. The “upper echelons” (echelons) refers to the very top of a large organization or company. The presidents, the vice presidents, the top managers – we would call them the top “executives” who work in a company. They are part of the upper echelon.
Karla says, “I graduated with a degree in marketing and information systems.” “Marketing” is the area of a company or a business, responsible for letting other people know about your products, of trying to get people to buy your products by, for example, having advertising. That might be part of the marketing department in a company. “Information systems” is the part of the company that is responsible for the computer technology, especially how this information is used to help organize and run the company. That’s information systems – a relatively new part of business in the last 50 years or so.
Karla says, “Maybe I should be thinking about getting an MBA.” Joaquin says, “I’d recommend it” – I think it’s a good idea – “if you want to go further in your career” – in other words, if you want to get a better and higher-paying job in the future. Joaquin says, “I’ll lend you all of my test prep materials for the GMAT.” So, Joaquin is going to let Karla use his “test prep” materials. “Test prep” is short for “test preparation.” It’s the process of studying for a specific exam, learning what kind of questions will be asked, practicing your answers – that’s part of test prep.
“GMAT” is the Graduate Management Admissions Test. This is the test that most business schools use in the United States for their MBA programs. They give it to anyone who wants to go there, and you will need to get a certain score – a certain result – if you want to get into the school. The more difficult the school, the higher the GMAT score will be, the higher the GMAT score that you will need to get into that school. GMAT, like the SAT, like other similar tests, are used to decide who gets into the university and who doesn’t.
Karla says “The GMAT? I had forgotten about the GMAT. That maybe a deal breaker for me.” A “deal (deal) breaker (breaker)” is something that makes it impossible for you to do something because you don’t want to do it or you can’t do it. For example, I wanted to go out on a date with this beautiful girl but she was a smoker. And that was a deal breaker for me. She liked to smoke cigarettes and so I decide, “No. I could not date anyone who smoked cigarettes.” That’s not true, of course. When I was dating, I would date any woman who would say “yes” to going out with me, to going on a date with me. But some people might consider smoking, for example, to be a deal breaker.
Joaquin says, “Why? You don’t like taking tests?” Karla says, “I like taking tests as much as I like getting a kick upside the head.” A “kick upside (upside) the head” is an expression used when you have done something foolish or stupid. It’s almost as though someone were punishing you by kicking you in the head because you were so stupid. You were so dumb. Karla says that she likes taking tests as much as getting a kick upside the head. In other words, she doesn’t like it at all. And therefore, having to take this test – the GMAT – to go to graduate school would definitely be a deal breaker. It would be something that would make her decide that she was not going to do that.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Karla: I just heard that you’re taking a leave of absence to go to business school. Is that right?
Joaquin: Yeah, I’ve been thinking about it for a long time, and have finally taken the plunge. I need an MBA to get ahead in my career.
Karla: That’s great, but why don’t you go part-time?
Joaquin: I had considered taking classes on nights and weekends while I continue to work, but I’ve been admitted into an Ivy League school, and I want to take full advantage of the opportunities there.
Karla: Isn’t graduate school expensive, especially an Ivy League school?
Joaquin: Yeah, but I think it’s worth it, and I’ve been saving up. I have an undergraduate degree in accounting and finance, but that’s not enough if I want to work in the upper echelons of this or any other company.
Karla: I graduated with a degree marketing and information systems. Maybe I should be thinking about getting an MBA.
Joaquin: I’d recommend it, if you want to go further in your career. I’ll lend you all of my test prep materials for the GMAT.
Karla: The GMAT? I’d forgotten about the GMAT. That may be a deal breaker for me.
Joaquin: Why? You don’t like taking tests?
Karla: I like taking tests as much as I like getting a kick upside the head – maybe even less!
[end of dialog]
We hope our scriptwriter never takes a leave of absence because we love her wonderful scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
leave of absence – a long period of time when one has permission to not go to work but can return to one’s job afterwards, perhaps to write a book, to conduct research, or to take care of oneself or a family member with medical problems
* Hal wants to take a one-year leave of absence to bike across the country.
to take the plunge – to decide to do something that is risky or scary
* You’ve been writing short stories for years. Now it’s time to take the plunge and send them to a publisher.
MBA – Master of Business Administration; an advanced degree that provides a broad education on functions used in the business world, such as management, finance, marketing, operations, and human resources
* Jawad earned an MBA degree with a focus on financial analysis.
Ivy League – a group of eight private universities that are considered some of the best universities in the United States: Brown University, Columbia University, Cornell University, Dartmouth College, Harvard University, Princeton University, the University of Pennsylvania, and Yale University
* They were thrilled when their daughter was accepted to an Ivy League school, but then they started to worry about how they would pay for it.
graduate school – advanced educational programs in which people try to earn degrees after they have already earned an undergraduate/bachelor’s degree
* Meghan needs to go to graduate school to earn her Master in Teaching degree before she can apply for a job with the public schools.
to save up – to save a lot of money for some particular purpose; to reduce expenses and put the extra money into an account so that it can be used for a specific purpose in the future
* It took them years to save up enough money for a down payment on a new house.
undergraduate degree – bachelor’s degree; a degree normally earned after four years of study at a university
* In the past, people could get a good job with a high school diploma, but nowadays, you really need at least an undergraduate degree.
accounting – the study of recording financial transactions in a systematic, responsible way
* Does your company use the accrual method or the cash method of accounting?
finance – the management of large amounts of money for an organization, making sure that enough cash is available and that excess funds are invested
* Anyone who wants to work in finance needs to be comfortable using spreadsheets.
upper echelons – the top executives and decision-makers in an organization; top management; the people who hold power in an organization
* Ingrid plans to become a state senator by the time she’s 30, and she plans to be in the upper echelons of the federal government within another 15 years.
marketing – the business function related to promoting and selling products and services, demonstrating how they meet customers’ needs
* Our new marketing campaign is targeted at college-age women.
information systems – computer technology, especially networks, that controls how information is stored and shared within an organization
* The information systems department requires that we all change our password at least once every six weeks.
test prep – test preparation; the process of studying for an exam, focusing on the type of material covered and the format of the test, in order to get the highest score possible
* The test prep course really helped me master the math questions.
GMAT – the Graduate Management Admission Test; a standardized test required for admission to most business schools in the United States
* The GMAT is a 3.5-hour exam that covers quantitative skills, verbal skills, integrated reasoning, and analytical writing.
deal breaker – something that makes it impossible for one to do something, because it is unacceptable and cannot be negotiated
* Jenna has many friends, but smoking is a deal breaker for her. She will never spend time socially with anyone who smokes.
kick upside the head – an expression used when someone has done something foolish or stupid
* Is Yuki really considering plastic surgery? If so, she needs a kick upside the head. She’s beautiful just the way she is!
Comprehension Questions
1. What is Joaquin doing by “taking a leave of absence”?
a) He’s going to start working part-time.
b) He’s quitting his job with the company.
c) He’s going to stop working for a period of time.
2. Why does Joaquin want to get an MBA?
a) Because he loves to study.
b) Because he got a great scholarship.
c) Because he wants to get a better job.
Answers at bottom.
What Else Does It Mean?
to take the plunge
The phrase “to take the plunge,” in this podcast, means to decide to do something that is risky or scary: “Ryan and Martha have been dating for seven years, and they’ve finally decided to take the plunge and get married.” A “plunge” can be sudden, dramatic decrease: “What caused the recent plunge in the stock market?” When talking about swimming, a “plunge” is a jump or a dive into the water: “You have time for just one more plunge into the pool, and then we need to dry off and go home.” Finally, when talking about fashion, a “plunging neckline” describes the top part of a dress or shirt which has a very low opening at the top, so that the top part of the woman’s chest is exposed: “It’s never appropriate to wear a plunging neckline at work.”
deal breaker
In this podcast, the phrase “deal breaker” means something that makes it impossible for one to do something, because it is unacceptable and cannot be negotiated: “The job pays well and is in a great location, but they told me that I would only have five days of vacation per year, and that was a deal breaker.” An “ice breaker” is an activity designed to help people interact and feel more comfortable around each other: “The meeting began with a few ice breakers to help the attendees get to know each other.” Finally, a “wind breaker” is a light jacket that is not very warm, but prevents the wind from making one too cold: “It can be pretty windy on the coast even in the middle of summer, so you might want to pack a wind breaker.”
Culture Note
The Case Studies Approach
Many business schools have adopted the “case study approach” for teaching “principles” (main ideas) of management, marketing, finance, and other business topics. A “case study” is a detailed analysis of some organization, project, system, or decision. It usually provides “extensive” (a lot of) background information, as well as “profiles” (descriptions) of “key players” (people who have an important role). Then it presents a situation, problem, or “dilemma” (a situation where someone must choose among two or three things).
Students are given copies of the case study and asked to imagine that they are the decision-maker facing the problem or situation. The students may need to work alone or in small teams to identify their preferred solution and then explain their “rationale” (logic; reasoning), usually through an oral presentation, in a “memo” (memorandum; a one-page report used in business), or in a report.
In most cases, the case studies approach is more challenging than traditional teaching “methodologies” (ways of doing something), because they are “interdisciplinary” (involving more than one field). A traditional finance class might give the students specific problems to solve, but those problems are related only to financial calculations, without the need to consider the impact of those decisions on marketing or “R&D” (research and development). In contrast, the case studies methodology might describe a situation that requires using financial knowledge and analytical skills, but the students also have to consider the impact of their decision on the entire organization over time.
Comprehension Answers
1 - c
2 - c