= 0866
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 866: Using Renewable Energy
This is English as a Second Language Podcast episode 866. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there to download a Learning Guide for this episode. You can do that by becoming a member of ESL Podcast.
This episode is a dialog between Carl and Jody, about using energy wisely, using energy that is renewable. Let’s get started.
[start of dialog]
Carl: Uh! What’s that smell?
Jody: I’m working on my latest invention. I’m turning our old food into an energy source for our car and our house.
Carl: Why? There are already lots of types of renewable energy that power cars and homes, and none of them smell like this!
Jody: Well, I think I’m onto a better alternative. Imagine being able to recycle your unwanted food into fuel. That’s the wave of the future.
Carl: You mean you think that it would be more efficient than wind power and solar energy? There are geothermal and hydroelectric power plants that already provide energy for lots of homes and businesses.
Jody: But I’m using food that would otherwise be wasted.
Carl: I hate to break it to you, but if you want to convert food into fuel, there are already different types of biofuels that work pretty well.
Jody: You mean somebody has already beaten me to the punch?
Carl: Yes, and I bet they’ve found a way to do it without this stench!
[end of dialog]
Carl begins by saying, “Uh! What’s that smell?” – what is that smell? Jody says, “I’m working on my latest invention.” An “invention” (invention) is something that you create, that no one else has made before, something you make that solves some problem or does something that no one else has been able to do before. We might talk about the invention of the television or the invention of the Internet. Jody is working on an invention – her “latest,” meaning her most recent invention. She says, “I’m turning our old food into an energy source for our car and our house.” Jody is “turning” their old food “into” something, meaning she’s changing it. “To turn something into something else” is to transform it, to change it. She’s taking their old food and making it into an energy source. An energy source is a way of getting or obtaining energy needed to run some machine or to power some technology.
Jody is trying to create an energy source for their car and their house. Carl says, “Why? There are already lots of types of renewable energy that power cars and homes, and none of them smell like this!” The word “renewable” (renewable) is something you can use again or something that will not run out. “Renewable energy” is energy that comes from some natural resource that will never run out, or would take a very long time to use up, like the energy of the sun, for example, or water energy or wind energy. These might all be called “renewable energy sources.”
Carl says “There are lots of renewable energy sources and none of them smell like this,” meaning none of them smell like Jody’s invention of using old food. Jody responds, “Well, I think I’m onto a better alternative.” “To be onto something” means I’ve discovered, I’ve found. An “alternative” would be something you can use instead of, or in place of something else.
A bicycle is an alternative to your car – if you’re travelling short distances, that is. It’s an alternative to your car, perhaps, not my car! I still want to drive my car. I’m not against using a bicycle, of course – every couple of years.
Jody says, “I’m onto a better alternative. Imagine being able to recycle your unwanted food into fuel.” “To recycle” (recycle) means to take something that has been used already for a purpose and to use it again, often by cutting it up or breaking it up in some way and then re-using – using again – the material from that object, from that thing. Jody is saying that she can recycle unwanted fuel and turn it into fuel. “Fuel” (fuel) here really means the same as “energy.” Often we think of fuel as something that is burned in order to produce energy, but it could be used more generally to mean an energy source.
Jody says, “That’s the wave of the future.” That expression “the wave (wave) of the future” means something that will become very popular or something that will be normal in the future, not right now but someday soon. We use the word “wave” just like an ocean wave, which is water that moves up and travels across a certain distance or seems to travel – the water is pushed, of course. We use that idea of a wave in talking about how things will go into the future – they will be moving into the future in this direction. We might say, “The wave of the future is using mobile devices – telephones and tablets, iPads, that sort of thing – instead of computers sitting on your desk.” That might be a “wave of the future.”
Carl says, “You mean you think that it would be more efficient than wind power and solar energy?” “Efficient” means it does something in a smaller amount of time or that uses less money or fewer resources. “Wind energy,” or “wind power” as it’s called here, is the power or energy created by the wind, usually using some large piece of metal that moves around in a circle. We would call that a “windmill” (windmill). “Solar energy” is using energy from the sun, either to heat up water or to create electricity. In some parts of the United States where there’s a lot of sun throughout the year, people have “solar panels” – large pieces of material on their roofs in order to collect solar energy.
Carl goes on to mention a couple of other types of renewable energy sources. He says, “There are geothermal and hydroelectric power plants that already provide energy for lots of homes and businesses.” “Geothermal” (geothermal) refers to energy that you get from under the earth – from inside the ground, from a very hot area inside the ground. You are using that energy underground.
“Hydroelectric” refers to water that goes through a small area called a “dam” and the pressure or power of the water turns engines, turns these large pieces of metal – these wheels – which help create electricity, combining them with the use of magnetic force, typically, I believe.
Jody says, “But I’m using food that would otherwise be wasted,” meaning I’m using food that people are just going to throw away or destroy. Carl says, “I hate to break it to you, but if you want to convert food into fuel, there are already different types of biofuels that work pretty well.” So, Carl is basically saying, “You’re kind of an idiot, Jody. We’ve already done these things.”
The expression “I hate to break (break) it to you” means “I don’t like to give you bad news but I’m going to tell you some bad news.” You might say to someone, “I hate to break it to you but you didn’t get the job. You were not hired.” You’re telling them news they don’t want to hear – bad news. Carl says, “I hate to break it to you, but if you want to convert” – or change – “food into fuel” – or energy – “there are already different types of biofuels that work pretty well.” A “biofuel” (biofuel) is a fuel that is made from plants and animals. It’s a kind of fuel that you can burn, typically, to create energy.
Jody says, “You mean somebody has already beaten me to the punch?” “To beat someone to the punch (punch)” means to do something before another person has the opportunity to do it.
So, you and your sister are thinking about buying your mother a new set of dishes – something or her kitchen. You talk about it and then your sister goes out and she buys the dishes for your mother and gives them to her, and you find out after talking to your mother that your sister gave her the dishes that you were going to give to her. So, you might say to your sister, “Oh, you beat me to the punch.” You did it before I had an opportunity to do so. And now you’re mad at your sister because you don’t know what to get your mother, because, you know, your mother is sometimes difficult to buy for. And so, when you have a good idea and your sister takes it, or your sister does it before you, you’re not very happy with your sister. I’m just speaking hypothetically. This didn’t actually happen to me, of course.
So, Jody says, “You mean someone” – or somebody – “has already beaten me to the punch?” Carl says, “Yes and I bet they found a way to do it without this stench.” “Stench” (stench) is a very bad smell, a very unpleasant smell. Carl is saying that he thinks they have been able to do what Jody is trying to do without all of the bad smell.
Now let’s listen to the dialog, this time at a normal speed.
[start of dialog]
Carl: Uh! What’s that smell?
Jody: I’m working on my latest invention. I’m turning our old food into an energy source for our car and our house.
Carl: Why? There are already lots of types of renewable energy that power cars and homes, and none of them smell like this!
Jody: Well, I think I’m onto a better alternative. Imagine being able to recycle your unwanted food into fuel. That’s the wave of the future.
Carl: You mean you think that it would be more efficient than wind power and solar energy? There are geothermal and hydroelectric power plants that already provide energy for lots of homes and businesses.
Jody: But I’m using food that would otherwise be wasted.
Carl: I hate to break it to you, but if you want to convert food into fuel, there are already different types of biofuels that work pretty well.
Jody: You mean somebody has already beaten me to the punch?
Carl: Yes, and I bet they’ve found a way to do it without this stench!
[end of dialog]
Her scripts are the most important energy source that powers this podcast. I speak, of course, of the one, the only, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan, thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
invention – something that one has created, that nobody else has made before, usually to fill some need or with some special purpose, especially with hopes that it can be sold
* Somebody needs to come up with an invention that will fold and put away the laundry automatically!
energy source – a way of obtaining or getting the energy needed to power or operate machines
* Someday we will run out of oil, so we need to find alternative energy sources.
renewable energy – energy that comes from natural resources that cannot be depleted (cannot run out), like sun, wind, and water
* Many people say they care about the environment, but how many of them are willing to pay more for renewable energy?
to recycle – to take a used item and break it into its components (parts or pieces) so that they can be used to make a new item again
* In most cities, people can recycle plastic containers, but not the lids.
fuel – something that is burned to produce energy to power machines
* Do those trains run on diesel or some other kind of fuel?
the wave of the future – something that will become very popular and commonplace or normal in the future
* Working from home and connecting to the office online is the wave of the future.
efficient – doing something well with a small amount of time, money, or other resources
* We could make our factory more efficient if we found a way to use the heat that the machines generate to keep the buildings warm in the wintertime.
wind power – a way to create energy by using the natural wind to move large pieces of metal in a circle to produce energy
* Wind power is great for the environment, but many people complain about the way an area looks once it is covered in wind turbines.
solar energy – a way to create energy by using large, flat panels to collect energy from sunlight
* The Lopez family put special panels on their roof so that they can use solar energy to heat their water.
geothermal – related to a way of getting energy by accessing the very hot area inside the planet, underground
* Geothermal heat is a good energy source, because it does not create any pollution.
hydroelectric power plant – a construction that produces energy by having a large wall (dam) that holds back a lot of water, and that lets a small amount of water flow through at specific times when it is used to turn turbines that produce electricity
* How do hydroelectric power plants make sure that salmon and other types of fish are able to swim on the rivers without being killed by the dams?
to waste – to not use something fully; to throw away or destroy something that could have been used by others for a particular purpose
* If you turn off the water while brushing your teeth, you can avoid wasting so much water.
I hate to break it to you – a phrase used when delivering bad news, used to show that one does not want to disappoint someone or hurt his or her feelings
* I know you’ve been working really hard on these math problems, so I hate to break it to you, but the assignment was actually to do the problems on the next page.
to convert – to transform; to change something from one thing into another
* How can I convert a weight from pounds to kilos?
biofuel – a fuel (something that can be burned to produce energy) that is made from organic (plants and animals) substances
* How much of corn grown in the United States is used for biofuel versus food?
to beat (someone) to the punch – to do something before another person has an opportunity to do it
* Henrietta wanted to suggest a change to the company’s policy on paid vacations, but one of her co-workers beat her to the punch.
stench – a very bad smell; a very unpleasant smell
* There’s always a stench around that pig farm.
Comprehension Questions
1. Which of these energy sources depends on having a large amount of water?
a) Solar energy.
b) Geothermal energy.
c) Hydroelectric power plants.
2. What does Jody mean when she says that someone has beaten her to the punch?
a) Somebody told the news media about her idea.
b) Somebody already found a way to convert food into fuel.
c) Somebody has offered to pay for her invention.
Answers at bottom.
What Else Does It Mean?
to waste
The verb “to waste,” in this podcast, means to not use something fully, or to throw away or destroy something that could have been used by others for a particular purpose: “Why would anyone waste their money buying such an ugly painting?” The phrase “to waste (one’s) breath” means to say something when the other person will not listen or pay attention: “Don’t waste your breath telling Kevin about the dangers of smoking. He already knows it’s bad for his health, but he’ll never quit.” Finally, the phrase “to be wasted on (someone)” describes a situation where one does not fully appreciate how good or useful something is: “Susan doesn’t drink much wine, so don’t serve your nicest bottle as it will just be wasted on her.”
to convert
In this podcast, the verb “to convert” means to transform or to change something from one thing into another: “Can you convert this CD into a set of MP3 files?” Or, “They want to convert their large garage into a home office.” The verb “to convert” can also mean for someone to change to a different religion: “How old were you when you converted to Islam?” Finally, the phrase “to preach to the converted” means to talk to people about something when they already share one’s opinion on it: “Of course you had a good audience at the liberal universities, because you were preaching to the converted. Now try making that same presentation at conservative universities and see what happens!”
Culture Note
Companies Using Renewable Energy
In 2011, a company called Cooler Planet created an “infographic” (a graphic image that presents detailed information on a particular topic in a way that is easily understood) called “Companies Running on 100% Renewable Energy.” The infographic “highlights” (focuses on; showcases) 10 companies that “rely” (depend) “solely” (only) on renewable energy or, if they use non-renewable energy, have ways to “offset” (counter; undo the negative effects of something) of their “fossil fuel” (non-renewable energy sources) consumption.
The ten companies represented in the infographic are:
Retail: Whole Foods, Kohl’s
Banking: TD, HSBC, Deutsche Bank
Government: Environmental Protection Agency
Natural Resources: Mohawk
Food & Beverages: Dannon
Consulting: Pearson
Non-profit: The World Bank
Most of these companies’ energy is generated through wind power, followed by solar power. Some of the companies have more than 100% “green energy” (renewable energy) “utilization” (use), meaning that they “generate” (produce) more energy than they use, “feeding it back into the grid” (sharing their “surplus” (extra) energy with other companies and/or selling it to the utility). This helps all companies lower their fossil fuel consumption, as the utilities are able to “redistribute” (give to other people or companies) the surplus renewable energy instead of generating energy through traditional sources, like coal and national gas.
The “EPA” (Environmental Protection Agency; the U.S. government agency responsible for protecting the natural environment) maintains a list of “Green Power Partners” with “statistics” (data) about how much renewable energy they use, including their main sources.
Comprehension Answers
1 - c
2 - b