= 0877
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 877: Cheering Someone Up.
This is English as a Second Language Podcast episode 877. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. (That didn't sound very beautiful. I'm sorry.)
Our website is beautiful. It's at ESLPod.com.
This episode is a dialog between Eleanor and Porter, about trying to make someone happy who is sad, trying to cheer them up. Let's get started
[start of dialog]
Eleanor: Isn’t it a beautiful day? The sun is shining; the birds are singing. It’s good to be alive!
Porter: Okay, Pollyanna, go spread good cheer somewhere else.
Eleanor: What’s wrong with you? You must have woken up on the wrong side of the bed.
Porter: I’m just having a bad day – no, make that a bad month. Nothing is going my way.
Eleanor: Cheer up! Every cloud has a silver lining and it’s no use crying over spilled milk.
Porter: Spare me your platitudes, and let me wallow in my own misery.
Eleanor: I can’t do that. If your work isn’t going well, then practice makes perfect. You’ll just do better next time.
Porter: It’s not my work.
Eleanor: Is it your girlfriend? If your girlfriend isn’t being nice to you then there are plenty of fish in the sea. Don’t you see? Whatever the problem is, it’s not the end of the world.
Porter: My biggest problem right now is easy to fix.
Eleanor: How?
[Door slams.]
[end of dialog]
Our dialog begins with Eleanor saying to Porter, “Isn't it a beautiful day? The sun is shining” – the sun is out – “the birds are singing. It's good to be alive!” Eleanor is very happy, but Porter is not. Porter said, “Okay Pollyanna, go spread cheer somewhere else.” “Pollyanna” (Pollyanna) is the name of a character from a novel back in 1913, called Pollyanna. Pollyanna was always happy, always cheerful, always optimistic. Now it's used to describe someone who's like that. She's a Pollyanna. It sometimes used as almost an insult, however, to someone who's too happy, who’s too cheery, who's too optimistic.
“Cheer” (cheer) a noun and a verb. As a verb, it means to make someone happy who is sad. As a noun, it means happiness. “To spread good cheer” means to make other people happy by smiling, by talking to them and so forth. That's spreading good cheer – spreading happiness, giving other people happiness.
Eleanor says, “What's wrong with you? You must have woken up on the wrong side of the bed.” “To wake up on the wrong side of the bed” means to be in a very bad mood. I'm not sure exactly why we have this expression. Maybe if you wake up and you get out of bed on the wrong side, you'll hit a wall or you’ll fall over or I don't know. But that's the expression – “to wake up on the wrong side of the bed.” The “bed,” of course, is something that you sleep in at night.
Porter says, “I'm just having a bad day – no, make that a bad month.” The expression “make that” is used when we want to correct something we just said, especially if we are talking about numbers.
Porter says that nothing is going his way. “To go your way” means to go as you have planned it to go, as you want it to go, to be successful at something that you are attempting to do. That's “to go your way.” Don't confuse this with another expression, “to go your own (own) way.” “To go your own way” means to do something different from everyone else, to do something that is not like anyone else. I think there was actually a song back in the 70’s by Fleetwood Mac.
“You can go your own way. Go your own way.”
I think a woman sang it, though. Anyway…too much coffee today, Jeff!
Porter says that nothing is going his way. Eleanor says “Cheer up” – be happy. “To cheer up” is a phrasal verb. Like a lot of phrasal verbs, it is used to add emphasis. Instead of just saying “cheer,” we would say “cheer up.” You’re telling someone to be happy, to get happier. Eleanor says, “Every cloud has a silver lining.” This is an old expression, an old saying, “Every cloud has a silver lining.” A “cloud” is what's up in the sky. That's where rain comes from. The expression “a silver lining” means something that is good. For a cloud to have a silver lining means that even if it's a bad thing that is happening, like a cloud where it might rain, there's something good that may come out of it. It's not completely negative. There's always some positive things that you can find when something bad happens. “Every cloud has a silver lining.”
Eleanor is telling Porter that he needs to cheer up because even though he's having a bad month, something good will come from this bad month. She then uses another old expression, “It's no use crying over spilled milk.” “It's no use” means it's no good, it doesn't help you, “crying over spilled milk.” “To cry over something” is to cry because of something. “Milk” is what you get from, say, a cow, that you drink. I have milk every morning with my cereal. “Spilled” means that the milk was in a glass, for example, and you hit the glass and the milk fell on the ground. That would be “spilled milk.” You spilled it. The expression, putting all these things together, “It's no use crying over spilled milk,” means it doesn't help worrying about something that already happened. You can't go back and change it. You can't go back and do something different. That's not possible. You can't change history. So, you just have to worry about the future.
Porter says, “Spare me your platitudes and let me wallow in my own misery.” “Spare (spare) me” means stop doing something, or more typically, stop giving me this information. Stop talking to me about what you are talking about. I don't want to hear it anymore. It's uninteresting, or it's boring, or I disagree with it. Spare me your lecture. Spare me your advice. I don't want to hear it.
Porter says, “Spare me your platitudes.” A “platitude” (platitude) is an expression or a statement that is very common, that everyone says, and it's no longer very interesting. It's like saying, “Today is the first day of the rest of your life.” Today is the day that you will continue living. Well, yes that's true, but it's really not very interesting. That would be a platitude. Another word for platitude is a “cliché (cliché). A “cliché” is an expression that everyone uses so that it doesn't really mean anything anymore.
Porter says to Eleanor, “Let me wallow in my own misery.” “To wallow” (wallow) means to enjoy being sad, usually because you're trying to get sympathy or attention from other people. “He wallowed in his sadness.” He sat there looking sad but in a way hoping other people would notice he was looking sad so they would pay attention to him. Porter says, “Let me wallow in my own misery.” “Misery (misery) is suffering, sadness, often because you are sick or you don't have enough money.
Eleanor says, “I can't do that. If your work isn't going well, then practice makes perfect.” That's another old expression. “Practice makes perfect” means that if you do something enough times, you will get better at it. You will get perfect at it. Eleanor says, “You'll just do better next time.” Porter then says, “It's not my work.” He’s not sad because of his work. Eleanor says, “Is it your girlfriend? If your girlfriend isn't being nice to you, then there are plenty of fish in the sea.” The expression, “There are plenty of fish in the sea (sea)” is used to tell men and women who are single, who perhaps don't have a boyfriend or a girlfriend, or who have one that isn't very good, that there are other men and women out there, that you don't have to just stay with this person, that there are many different fish in the sea. There are many different men and women that you can go out and find and date.
Eleanor says, “Don't you see? Whatever the problem is, it's not the end of the world.” “The end of the world” is a phrase used to mean the worst possible thing that can happen. But Eleanor says, “It's not the end of the world.” It's a bad thing, but it's not the worst possible thing that can happen. Porter says, “My biggest problem right now is easy to fix.” “Easy to fix” means easy to solve. Eleanor says, “How?” And then we hear the door slam. This is Porter walking away from Eleanor and slamming the door. When you “slam (slam) the door,” you close it very loudly so that it makes a loud noise. Usually, we do this when were angry at someone, or when we’re trying to get away from someone, and Porter, I guess, is trying to get away from Eleanor
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialog]
Eleanor: Isn’t it a beautiful day? The sun is shining; the birds are singing. It’s good to be alive!
Porter: Okay, Pollyanna, go spread good cheer somewhere else.
Eleanor: What’s wrong with you? You must have woken up on the wrong side of the bed.
Porter: I’m just having a bad day – no, make that a bad month. Nothing is going my way.
Eleanor: Cheer up! Every cloud has a silver lining and it’s no use crying over spilled milk.
Porter: Spare me your platitudes, and let me wallow in my own misery.
Eleanor: I can’t do that. If your work isn’t going well, then practice makes perfect. You’ll just do better next time.
Porter: It’s not my work.
Eleanor: Is it your girlfriend? If your girlfriend isn’t being nice to you then there are plenty of fish in the sea. Don’t you see? Whatever the problem is, it’s not the end of the world.
Porter: My biggest problem right now is easy to fix.
Eleanor: How?
[Door slams.]
[end of dialog]
Her scripts usually spread good cheer. I speak of our own scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan thank you for listening. Come back and listen to us again right here on ESL Podcast
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development..
Glossary
Pollyanna – the main character in the 1913 novel Pollyanna; someone who is always happy, cheerful, and optimistic
* Ingrid is such a Pollyanna that anyone near her begins smiling and laughing.
to spread good cheer – to be happy and make other people feel happy through what one says and does
* Each year around Christmas time, they deliver cookies to all their neighbors as a way to spread good cheer.
to wake up on the wrong side of the bed – to be in a very bad mood, possibly without an explanation, for an entire day, from the moment one wakes up
* I’m sorry you woke up on the wrong side of the bed, but please don’t take it out on us!
make that – a phrase used to correct what one has just said, especially when talking about quantities
* I’ll have an 8-ounce coffee, please. No, make that an 16-once coffee.
to go (one’s) way – to proceed as one had planned or as one would like; to be successful and pleasing to someone
* Nothing is going my way today! I spilled coffee on my shirt, lost my keys, and accidentally deleted the report I’d been working on. What else could possibly go wrong?
to cheer up – to become happier; to improve one’s attitude or outlook
* Maybe this joke will help you cheer up!
every cloud has a silver lining – a phrase used to mean that every bad thing that happens has at least some good part, or that nothing is completely negative
* It’s too bad you lost your job, but maybe you’ll find a better one. Remember, every cloud has a silver lining.
to cry over spilled milk – to be very disappointed and continue to think about something bad that happened, when one has no control over it and cannot undo it
* They lost a lot of money in the stock market, but there’s no use crying over spilled milk. They’ll just have to work even harder now.
to spare (someone) – to stop doing something to someone; to stop giving someone a certain kind of information or explanation, because he or she finds it unpleasant or boring
* Please, spare me the lecture. I know smoking is dangerous, but I just can’t stop.
platitude – an expression or statement that is very common and has been heard many times, and is no longer interesting or helpful
* Julian wanted to be inspiring, but he could only think of platitudes, like, “Today is the first day of the rest of your life.”
to wallow – to enjoy being sad, trying to get attention or sympathy from other people
* I’m sorry your favorite mirror broke, but that’s no reason to wallow in tears.
misery – extreme suffering and sadness, especially resulting from being sick or not having enough money
* Their inability to buy food and clothing for their children brings them misery.
practice makes perfect – a phrase used to mean that one should do something many times to learn how to do it very well, or that if one practices enough, one will learn to do it well
* The first year of playing violin was really hard, but practice makes perfect and now he’s pretty good.
plenty of fish in the sea – a phrase used to mean that there are many single men and women with whom one can have a relationship, or that there are many other possibilities for a romantic relationship
* Trent was sad for a little while after his girlfriend left him, but he knew there were plenty of fish in the sea and he was looking forward to dating other women.
not the end of the world – a phrase used to give someone comfort and help that person understand that life will continue, even though a bad or sad thing has happened
* Yes, you lost your job, but it’s not the end of the world. You can wake up tomorrow and start looking for something different.
to slam – to close very noisily, with a lot of force
* Please don’t slam the door when you leave. The baby is sleeping.
Comprehension Questions
1. What would a Pollyanna do?
a) Spread good cheer.
b) Wake up on the wrong side of the bed.
c) Wallow in misery.
2. Why does Eleanor say, “there are plenty of fish in the sea”?
a) Because she thinks Porter will be able to date other women.
b) Because she wants to take Porter to a seafood restaurant.
c) Because she thinks Porter should take a beach vacation.
Answers at bottom.
What Else Does It Mean?
to go (one’s) way
The phrase “to go (one’s) way,” in this podcast, means for things to proceed as one had planned or as one would like, or for things to be successful and pleasing: “We hope the vote will go our way.” The phrase “to go (one’s) way” also means to travel in the same direction: “Do you need a ride home? I’m going your way.” The phrase “to go out of (one’s) way” means to do something extraordinary for another person, going beyond expectations: “Sheila went out of her way to cook a nice meal, so she was mad when her husband came home too late to eat it with her.” The phrase “to get (one’s) way” means to be able to do what one wants, even if other people would like you to do something different: “Her parents told her not to get a tattoo, but she always gets her way.”
to slam
In this podcast, the verb “to slam” means to close very noisily, with a lot of force: “Roberto was mad, so he slammed the door, but he didn’t realize that his fingers were in the way and he almost broke them.” The verb “to slam” also means to put something on another surface with a lot of force: “Jesse slammed his books onto the desk so loudly that it sounded like a gun being shot.” Informally, the verb “to slam” means to criticize or to say bad things about someone or something: “The company’s decision was slammed by the local newspaper.” Finally, the phrase “to slam on the brakes” means to stop a car very quickly: “Maria saw a dog in the road and slammed on her brakes to avoid hitting it, but then the car behind her hit her.”
Culture Note
Pollyanna
Pollyanna is a popular and well-known children’s book, but it has a wider influence among people who have not read the book. Most Americans are familiar with the story through the movie “adaptations” (portrayals of a book in a film). The best known “Pollyanna” movies are a 1960 Disney version starring Hayley Mills and a 1920 version starring Mary Pickford.
Sometimes you might hear people talking about the “Pollyanna Principle.” This is the idea that there is always something to be “glad” (happy) about, no matter how bad a situation may seem to be. For example, in the book, Pollyanna talks about when she was very poor and excited to receive free Christmas gifts, but the only gift left was a pair of “crutches” (tall metal sticks put under one’s armpits to help one walk without putting weight on one’s leg). At first she was “disappointed” (upset that something had not happened), but then she applied the Pollyanna Principle and decided to be glad that she didn’t have to use the crutches. Some people try to apply the Pollyanna Principle in their own lives, trying to become more “optimistic” (believing that good things will happen) and “positive” (thinking good, happy thoughts).
Between 1915 and 1967, there was a “board game” (a game played while seated at a table, with a large unfolded piece of cardboard with images and pieces that are moved on top of it) called The Glad Game, which was based on the Pollyanna story, but the game is no longer sold in stores.
Comprehension Answers
1 - a
2 - a