
= 3 - 1
:TOC:
---


Lesson 1

====
- hostage 人质
- appeal (v.)~ (to sb) (for sth) 呼吁；吁请；恳求
- captive 囚徒；俘虏；战俘 /(a.)被监禁的；被关起来的；被困住的
- remark 谈论；言论；评述
====

Freed American hostage, David Jacobsen, *appealed* today *for* the release of the remaining captives(n.) in Lebanon, saying, "Those guys are in hell and we've got to get them home." Jacobsen made his remarks as he arrived at Wiesbaden, West Germany, accompanied by Anglican Church envoy, Terry Waite, who worked to gain his release. And Waite says his efforts will continue. Jacobsen had a checkup at the air force hospital in Wiesbaden. And hospital director, Colonel Charles Moffitt says he is doing well. "Although Mr. Jacobsen is tired, our initial impression is that he is physically in very good condition. It also seems that he has dealt with the stresses of his captivity extremely well." Although Jacobsen criticized the US government's handling of the hostage situation in a videotape made during his captivity, today he thanked the Reagan Administration and said he was darn proud to be an American. The Reagan Administration had little to say today about the release of Jacobsen or the likelihood that other hostages may be freed. Boarding Air Force One in Las Vegas, the President said, "There's no way to tell right now. We've been working on that. We've had heart-breaking disappointments." Mr. Reagan was in Las Vegas campaigning for Republican candidate, Jim Santini, who is running behind Democrat, Harry Reed. In Mozambique today a new president was chosen to replace Samora Machel who died in a plane crash two weeks ago. NPR's John Madison reports: "The choice of the 130-member Central Committee of the ruling FRELIMO Party was announced on Mozambique radio this evening. He is Joaquim Chissano, Mozambique's Foreign Minister, No. 3 in the Party. Chissano, who is forty-seven, was Prime Minister of the nine-month transitional government that preceded independence from Portugal in 1975. He negotiated the transfer of power with Portugal. This much is clear tonight: an American held in Lebanon for almost a year and a half is free. David Jacobsen is recuperating in a hospital in Wiesbaden, West Germany. Twenty-four hours earlier, Jacobsen was released in Beirut by Islamic Jihad. But this remains a mystery: what precisely led to his freedom? Jacobsen will spend the next several days in the US air force facility in Wiesbaden for a medical examination. Diedre Barber reports. After preliminary medical checkups today, David Jacobsen's doctor said he was tired but physically in very good condition. US air force hospital commander, Charles Moffitt, said in a medical briefing this afternoon that Jacobsen had lost little weight and seemed extremely fit. He joked that he would not like to take up Jacobsen's challenge to reporters earlier in the day to a six-mile jog around the airport. Despite
his obvious fatigue, Jacobsen spent the afternoon being examined by hospital doctors. He was also seen by a member of the special stress-management team sent from Washington. Colonel Moffitt said that after an initial evaluation it seems as if Jacobsen coped extremely well with the stresses of his captivity. He said there was also no evidence at this point that the fifty-five-year-old hospital director had been tortured or physically abused. Jacobsen seemed very alert, asking detailed questions about the facilities of the Wiesbaden medical complex, according to Moffitt. So far, Jacobsen has refused to answer questions about his five hundred and twenty-four days as a hostage. Speaking briefly to reports after his arrival in Wiesbaden this morning, he said his joy at being free was somewhat diminished by his concern for the other hostages left behind. He thanked the US government and President Ronald Reagan for helping to secure his release. Jacobsen also gave special thanks to Terry Waite, an envoy of the Archbishop of Canterbury, for his help in the negotiation. Waite who accompanied Jacobsen from Beirut to Wiesbaden today, said he might be going to Beirut in several days. There are still seven American hostages being held in Lebanon by different political groups. Jacobsen will be joined in Wiesbaden tomorrow by his family. Hospital officials said they still do not know how many days Jacobsen will remain for tests and debriefing sessions before returning to the United States with his family. For National Public Radio, this is Diedre Barber, Wiesbaden. The leader of Chinese revolution, Mao Tsetong, died ten years ago today. During his lifetime, Mao became a cult figure, but the current government has tried to change that. Now his tomb and embalmed body in Beijing are just another tourist attraction. And no longer do millions of Chinese study or wave aloft the famous "Little Red Book" of Quotations from Chairman Mao. Along with the political writing, Mao wrote poetry as well—poems about the revolution, the Red Army, poems about nature. Willis Barnstone has translated some of Mao's work and considers him an original master, one of China's most important poets. "Had he not been a revolutionary, perhaps his poetry would not have been as interesting because his personal poetry was the history of China. At the same time because he was a famous revolutionary and leader, it has prejudiced most people, almost correctly, to dismiss his poetry as simply the work of a man who achieved fame elsewhere." "But his work was not dismissed within China though?" "Well, now it's almost consciously forgotten. But when I was there in '72, you could see his poems on every dining room wall, engraved on peach-pits ... During lunch hours, workers would study his poems. They were every place." "Is there, though, a revisionist thinking within literary circles? Are people saying Mao wasn't any good as a poet either?" "No. Well, at least in my conversations in the year I recently spent in Peking teaching at the university there, I found very few people who didn't think he was a very good poet. But they did feel that his suggestions which were that people not write in the
classical style, that they write in what he called the modern style, was very repressive. And as a result, of course, the restriction of publication during the ten years of the Cultural Revolution, poetry was abysmal." "When you say the modern style, would that be, for example, free verse?" "It would be free verse as opposed to classical rhymes or classical forms." "You write in the introduction to one of your translations of poems of Mao Tsetong that people ... you explain that leaders in China, and indeed in the a East, are expected to be accomplished poets." "Yes, I think that's true. The night that Tojo ... before Tojo died, he, ... in Japan, he wrote some poems. Ho Chi Minh was a poet. It was common. In fact, I think until early in the twentieth century, even to pass a bureaucratic exam, one had to know a huge number of classical forms. And especially, a leader should at least be a poet." "There is one poem which is political in nature which has to do with a parasitic disease in China." "Yes. Mao wrote some poems, two poems actually, about getting rid of a disease that was a plague for the country. And it's called 'Saying goodbye to the God of Disease.' And the poem needs annotation. In that sense, it's typical of classical Chinese poetry; he makes references to earlier emperors and places. Saying Goodbye to the God of Disease Mauve waters and green mountains are nothing When the great ancient doctor Hua Tuo Could not defeat a tiny worm. A thousand villages collapsed, were choked with weeds, Men were lost arrows, ghosts sang In the doorway of a few desolate houses. Yet now in a day, we leap around the earth, Or explore a thousand milky ways. And if the cowherd who loves on a star Asks about the God of plagues, Tell him, happy or sad, "The God is gone, Washed away in the waters." A poem by Mao Tsetong read by Willis Barnstone, Professor of Comparative Literature at Indiana University in Bloomington. He talked with us from WFIU.
