= 0106
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 106: High School Jobs.
English as a Second Language Podcast number 106. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about having a job in high school. Let’s get started!
[start of story]
I got my first part-time job when I was 15, working at a car wash in the summertime. A friend of mine, Rob, worked there and got me the job. I think it paid $2.90 an hour, which I considered a fortune. There were no allowances in my family, so most of my brothers and sisters started working as soon as they could to get spending money. I hated working at the car wash, drying cars all day. After only about six weeks working there (though it seemed much longer), I up and quit one day. I felt badly about not giving a two-week notice, but I had it up to here with the job. Luckily, another friend of mine got me a job working at a nursing home, washing dishes in the kitchen. I started the day after my 16th birthday, qualifying me for a slightly higher minimum wage.
Life scrubbing pots and pans was no picnic, let me tell you. I lasted there for only three months, working after school and on weekends while trying to keep up with my homework in high school. My next job was much better: Making keys at a locksmith. The working conditions were much better and I had flexible hours around my school schedule. I stayed at that job for nearly seven years, right through my college years at the University of Minnesota. To this day I still know the names of all the common key blanks, but it doesn't come in handy very often!
[end of story]
We’re talking about having a job, a part-time job in high school, in this podcast. I should explain that in the United States, it’s very common for many students to work in high school when they are still studying for their high school diploma. This is especially true among middle class and working class – those students who come from families with less money. It is very common to have people work after school and on the weekends and this is something which can cause a problem. Sometimes you have students who are working fifteen, maybe twenty hours a week and going to high school during the day. But as I say, it is quite common and getting jobs during the summertime or during the school year is a fact of life. It’s a common occurrence in many, many families, as it was in mine. I got my first “part-time job,” and a “part-time job,” in the United States, would be anything less than forty hours a week. I had a part-time job when I was fifteen, working at a car wash. Now, I should say that normally, it’s not legal to work in most jobs until you are 16 in the United States. However, there are some exceptions to that rule and it is sometimes possible to get a job at a lower salary, at a lower “wage,” and a “wage” (wage) is how much you get paid – at a lower wage, if you are fifteen. And when I was fifteen, I got a job at a “car wash.” A “car wash,” two words, is, of course, where you wash your car. In this case, it was an automatic car wash so it was washed by a machine and then it was “dried,” that is, you take a towel and you take the towel – put the towel on the car to take the water off. It was dried by hand. Sometimes, these are called “hand car wash” – “hand car washes,” rather, because the drying is done by hand.
I got this job in the “summertime,” all one word – “summertime,” “wintertime,” those two words are, of course -- mean the same as summer and winter. You can’t say, “fall time” or “autumn time” but you can say, “springtime.” I don’t know why but you can say “spring time,” “summertime,” “wintertime,” but not autumn or “fall time;” you just say “autumn,” or “fall.” Anyway, I got this job and it paid, I believe, $2.90 and I thought that was a “fortune.” A “fortune” (fortune) is a lot of money. And there is a magazine in the United States, a business magazine called “Fortune,” and every year, this company – this magazine publishes a list of the 500 biggest companies in the United States. This is called the “Fortune 500,” and if you are a Fortune 500 company, like Apple or Microsoft, McDonald’s, then you’re a very big company. The center for Educational Development, for example, is not a Fortune 500 company.
In my family, there were no “allowances.” An “allowance” (allowance) is money that parents give their children so they can spend it however they want to. So, in some families, each week or each month, the parents give the child, I don’t know, 15, 20, $30 in order to spend on buying candy or going to a movie or whatever the child wants to do. In my family, because I come from a family of eleven children, there were no allowances. We were lucky just to get food. No, I’m kidding, but there were no allowances and so, if you wanted to have “spending money” -- and “spending money” means, of course, money that you can spend that isn’t essential. If you wanted spending money, you had to get a job as soon as you were old enough. Even before, of course, we would work at other informal jobs like, cutting the grass of our neighbors, so we would “mow their lawn,” that is, cut the grass. We would, in Minnesota, shovel snow and get paid for shoveling the snow off the sidewalk of our neighbors.
The car washes, I say, was not a very happy place to work, not a very pleasant place, so after about six weeks, I “up and quit.” The expression, “I up and,” means I suddenly decided to do something. Usually, it has to do leaving a place. “I up and quit,” or “I up and left.” It’s just an idiomatic, strange expression. Don’t try to analyze it grammatically but it’s common – “I up and quit” as an informal – means I quit suddenly. I didn’t even give a “two week notice.” Again, a common custom, at least in the United States, is that when you leave or quit your job, you give your employer “two weeks’ notice,” meaning I tell you two weeks before I plan on leaving. I said, “I had it up to here” with the job. The expression, “to have it up to here,” means I was tired of the job, I could no longer tolerate, I could no longer put up with the job. So, you can say, “I’ve had it up to here with the bad weather” – means I can’t take it anymore. I can’t tolerate it anymore. Luckily another friend of mine got me a job at a “nursing home.” A “nursing home” is where usually older people who cannot take care of themselves go, and it’s usually – there are forty, fifty maybe a couple of hundred people. It’s not a hospital. It’s a place where they live, but it has medical care. I said that because I had started after my 16th birthday, “I qualified for a higher minimum wage.” “To qualify” means that you are able to do something. You have the “qualifications.” you have certain something that allows you to do something. For example, we use the term, “to qualify,” often for a sports event or in the Olympics. For example, a certain number of people qualify to be on the Olympic team and you compete against other players, and you “qualify” if you have what it takes to be on the team, and you can go to Torino for the winter Olympics this year – next year. The “minimum wage” is the lowest amount that a company can legally pay you. In the United States, a company normally has to pay you a minimum amount. They can’t just pay you a dollar or $2. It has to pay you a legal amount and each – the federal government – rather, the national government has a “minimum wage.” I think it’s $6.50 or $6.75 an hour.
I said that “life scrubbing pots and pans was no picnic, let me tell you.” “To scrub” means to rub very hard in order to clean. “Pots and Pans” are what you cook in, so you put soup or whatever you’re cooking and you put it on a stove. You turn on the fire – those are called “pots and pans,” the actual things that you cook with. I said it was – “life was no picnic.” That expression, “it was no picnic,” means it wasn’t easy. It wasn’t fun. A “picnic” (picnic) is when you go to a park or somewhere, to the beach and you have a little meal and you relax. “Well, this was no picnic, let me tell you.” That is a very common expression. “Let me tell you, it wasn’t easy,” meaning you should listen to me. I know what I am talking about. “Let me tell you.”
“I lasted only three months there,” meaning I stayed only three months, because I was having problems “keeping up” with my homework. “To keep up with” means to be able to do it – to do my homework on time. The “working conditions” of my next job were much better. My next job was at a “locksmith.” A “locksmith” (locksmith), all one word, is a place where you make keys, car keys, house keys, and so forth. “Working conditions” is a term we use to mean how comfortable, how nice of a place it was. It can include whether it’s a safe place, a clean place. All that is part of the “working conditions.” “I stayed at that job for seven years and “to this day, I still know the names of all the common key blanks.” The expression “to this day” means from then right up until now or still. Okay? I still know even after all these years, “to this day.” A “blank” – a “key blank” is a key before it is cut, so it has the shape but it doesn’t have the cuts in it.
I said that this doesn’t – this knowledge doesn’t come in handy very often. “To come in handy” – and “handy” is (handy) – “to come in handy” means to be useful.
Now let’s take a listen to the story this time at a native rate of speech.
[start of story]
I got my first part-time job when I was 15 working at a car wash in the summertime. A friend of mine, Rob, worked there and got me the job. I think it paid $2.90 an hour, which I considered a fortune. There were no allowances in my family, so most of my brothers and sisters started working as soon as they could to get spending money. I hated working at the car wash, drying cars all day. After only about six weeks working there (though it seemed much longer), I up and quit one day. I felt badly about not giving a two-week notice, but I had it up to here with the job. Luckily, another friend of mine got me a job working at a nursing home, washing dishes in the kitchen. I started the day after my 16th birthday, qualifying me for a slightly higher minimum wage.
Life scrubbing pots and pans was no picnic, let me tell you. I lasted there for only three months, working after school and on weekends while trying to keep up with my homework in high school. My next job was much better: Making keys at a locksmith. The working conditions were much better and I had flexible hours around my school schedule. I stayed at that job for nearly seven years, right through my college years at the University of Minnesota. To this day I still know the names of all the common key blanks, but it doesn't come in handy very often!
[end of story]
That’s all we have time for today. Thanks for listening. From Los Angeles, California, I’m Jeff McQuillan. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
part-time – when one works fewer hours at one’s job than at a normal or "full-time" job, usually done when one does not have enough time to work more hours because of other commitments, such as school or other jobs
* Wade worked part-time at the bookstore while he attended the university.
car wash – a business that washes and dries cars; a business where one pays to have other people wash and dry one’s car
* Charlene’s car was covered in mud, so she took it to the car wash to have it cleaned.
summertime – summer; the hottest season or period of the year, which comes between spring and winter
* Raoul enjoyed summertime because he loved the hot weather.
fortune – wealth; a very large amount of money
* Natalie earned a fortune after her business became successful.
allowance – money one gets from one’s parents for doing chores or work around the house; money one gets from one’s parents that one can spend on whatever one wants
* Sidney gave his son an allowance of $20 every week, and his son mowed the lawn and cleaned his room each week to earn it.
spending money – money that one can spend on whatever one wants; money that one can use to buy items that one wants but does not need to buy
* Helga had some extra spending money after paying her bills, so she spent it on a new book that she wanted to buy.
two-week notice – a standard warning one gives to the person or company one works for, telling that person or company that one will stop working there after two more weeks
* Barclay got a better job with a new company, so he planned on quitting his old job and gave his manager his two-week notice.
had it up to here – could not take it anymore; reached the limit; a phrase one uses to say that one is not able to handle a situation or do a task that one once did because one is too angry or frustrated to continue
* Marguerite had it up to here with the excuses Colby always made when he was late, and she told him that she was too angry to speak to him anymore.
nursing home – a business that provides older people a place to live after they are not able to provide for their own needs, usually giving them food, shelter, and a room to sleep in
* The local nursing home was known for providing great care and healthy food to the elderly who lived there.
to qualify – to make one eligible or able to get some benefit, such as a job or a larger amount of money
* Dean’s college degree qualified him to get a job fixing computers and making computer software.
minimum wage – the lowest amount of money one can legally be paid
* Peggy only earned minimum wage when she started working at the company, but she began earning more money after she completed her first year.
pots and pans – the dishes and containers used to cook food in, usually made of metal or glass
* The kitchen was filled with pots and pans in many different sizes, so the cook could make a large variety of meals.
no picnic – not easy; not fun; not enjoyable
* The driving exam was no picnic, and Arturo almost failed it because he was so nervous.
locksmith – a person or company that makes keys and locks; a person or company that fixes keys and locks that are broken
* Tasha lost the key to her house, so she needed to pay a locksmith to make a new key.
working conditions – the situation that one works in, including the place where one works, how one is treated by managers and other workers, how many hours one works, and how much money one earns
* Shelby liked working as a librarian, but the working conditions at the local library were not very good. The other workers were unfriendly and the pay was low.
to come in handy – to have a purpose or use; to be useful for something, like a task or job
* The large bag that Courtney carried came in handy when she needed to bring home a large pile of books and could not carry them in her arms
Culture Note
Dangerous Teenage Drivers
The car has always been an important part of American culture, especially of youth culture. The United States is a big country, with many cities that do not have good public transportation systems, so the car has become a “necessity” (something one must have) for most American families. Among teenagers and young adults, having a car is a sign of independence and freedom. In most states, you can get a “driver license” (legal permission to drive a car) at the age of 16, which means that many high school students drive and, if their parents are “wealthy” (rich; have money), have their own cars in high school and college.
But there’s “a price to pay” (a cost; something that you must give up) for having so many teenage drivers in the United States. According to driving “statistics” (information in the form of numbers), teenagers are among the most dangerous drivers in the country, perhaps because they are inexperienced at driving and not yet as mature as other older drivers. Most statistics show that teenage drivers have many more accidents and cause many more deaths than drivers who are older.
Some states have tried to solve this problem by placing “restrictions” (rules on things you cannot do) on teenage drivers. For example, in California, teenage drivers cannot drive between the hours of 11 p.m. and 5 a.m. for the first 12 months they have a license. In part, this is because many accidents are caused late at night, during these hours. Also, teenage drivers cannot have another teenage “passenger” (someone who is riding in the car but not driving) during the first 12 months of getting their license unless there is someone over 25 in the car . This means that a group of teenagers cannot go out on a Friday night driving unless there is an adult over 25 in the car with them.
Teenagers, of course, are not very happy about this law. But many adults in California are very happy that the government is doing something to lower the number of accidents caused by teen drivers.