= 0137
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 137: Meeting an Out of Town Friend.
You’re listening to English as a Second Language Podcast episode 137. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this podcast, we’re going to meet an old friend. Let’s get started!
[start of dialog]
Lucy: Hey Jeff, have you met my friend?
Jeff: No, I don't think I have.
Lucy: Well, this is my oldest and best friend, Marlene. She's visiting from out of town.
Jeff: Hi, I'm Jeff.
Marlene: Hi, it's nice meeting you.
Jeff: How long do you plan to be in town?
Marlene: I'm here for the long weekend, staying with Lucy. We're doing some catching up and I'm getting a break from work.
Jeff: Oh, what line of work are you in? Are you in the same field as Lucy?
Marlene: No, I'm in medicine. I'm a doctor, actually, a pediatrician. I enjoy the work, but it's nice to get away for a few days. What kind of work do you do?
Jeff: I work in the education field, but what I really want to do is to become a professional singer.
Lucy: Jeff has a great voice. He sounds exactly like Frank Sinatra.
Marlene: Really?
Jeff: No, she's just kidding and Lucy knows that I can't sing. We went to a karaoke bar once and people actually offered me money NOT to sing.
Lucy: That was a lot of fun. We should do that again sometime.
Jeff: Sure, anytime. Oh, I'd better go. It was nice meeting you Marlene, and Lucy, I'll talk to you next week.
Marlene: Nice to meet you, too.
Lucy: Okay, later.
[end of dialog]
In this podcast, we are meeting an out-of-town friend. When we say someone is “out of town” (town) we mean they are from somewhere other than where you live. So, if you live in Los Angeles, an out of town friend could be from San Francisco or New York City, or Houston, Texas – those would all be out of town friends, if they were coming to visit you. The dialog begins with Lucy saying to Jeff, “Have you met my friend?” “Have you met” (met) – of course, that’s the past tense of “to meet” – so, is this someone that you have met? You met them last week or two years ago. And I say, “No, I haven’t. I don’t think I have.” And Lucy says that this is her “oldest and best friend, Marlene.” When we use the term “oldest” when we’re talking about friends, we don’t normally mean older in terms of age like I’m 29 and my friend is 50. And he’s my oldest friend in age. That’s not what we normally mean. We normally mean this is one of the friends that I have known for the longest time – period of time – 10 years, 20 years, and so forth.
Well, Lucy says that she is visiting from out of town and then I introduce myself and I say, “Hi. I’m Jeff.” And she responds by saying, “Hi. It’s nice meeting you.” It’s nice meeting you is the same as “It’s nice to meet you.” It’s what we would say to someone the first time we meet them, but only the first time. And I say to Marlene – her friend – “How long do you plan to be in town?” meaning how many days or how many weeks will you be visiting this place. Notice the expression “in town.” When we say someone is “in town,” again, we mean they’re in the city or the place where you live. So, they would respond by saying, “I’m in town for three weeks” –means I will be here for three weeks – so, “out of town” and “in town.” Well, Marlene says that she’s here for a long weekend and when we say a “long (long) weekend,” we mean, usually, three or four days and that could be Friday, Saturday and Sunday or Thursday, Friday, Saturday and Sunday – possibly even Saturday, Sunday and Monday. Remember in the United States we like to have our national holidays on Mondays so we can have a long weekend.
Well, she’s staying – Marlene is staying with Lucy. And “to stay with someone” means that they are sleeping at their house or their apartment. She says that she wants to do some “catching up” and get a break from work. “To do some catching up” here means that she wants to talk to some of her friends that she hasn’t talked to in a long time, find out how they are doing. She wants to get a “break (break) from work” which means the same as – basically a vacation from work. A time when I don’t have to work would be a break.
I asked Marlene, “What line of work are you in?” “What line (line) of work are you in?” And that means what do you do for a living? What is your profession? What is your job, your occupation? You could be a lawyer, for example. You could be a truck driver – that would be your line of work. So, when we ask someone, “What is your line of work?” or “What line of work are you in?” – that is what we’re asking and I ask Marlene also, “Are you in the same field (field) as Lucy?” A “field” is just another way of saying the same profession, the same type of work. It does not mean the same company necessarily – just means the same kind of work or the same type of work. And Marlene says that she’s not in the same field as Lucy. She’s “in medicine.” “I’m in medicine” means I work in the medical field. I do my job – my job is related to medicine. You can say, “Well, I’m in the legal profession,” or “My job is in law (law)” – that would be someone who was a lawyer, for example. And she, in this case, is in medicine and says that she’s a “pediatrician.” And “pediatrician” is a long word – pediatrician) is someone who works with children and usually, in the United States, a pediatrician works with babies, children – usually up to the age of about 17 or so. So, they could work with children and teenagers – that would be a pediatrician.
She says she enjoys her work but “it’s nice to get away for a few days.” “To get away” means to take a short vacation somewhere else, somewhere not in your home town. To go to say, Las Vegas, and lose all of your money by gambling, because, of course, in Las Vegas, it’s a famous place to gamble your money in the United States and, what a great way to spend your time, losing all of your money.
Anyway, Marlene doesn’t go to Vegas, she goes – comes to Los Angeles. Marlene asked me, “What kind of work do you do?” – meaning very much the same as what line of work are you in – what kind of work do you do. And I say that I’m in the education field but, of course, my real goal is to become a professional singer. Lucy then says that I have a great voice – that I sound just like Frank Sinatra. Frank Sinatra, you probably know, is a famous American singer from the 1940’s and 50’s and 60’s, who has a very beautiful voice. Of course, Lucy is joking and I say, “She’s just kidding,” meaning Lucy is just kidding (kidding) – means she’s just joking. She’s just making a joke. I then say that once, we went to a karaoke bar. A “karaoke bar” is a place, you probably know, that you can sing songs and they put the lyrics, the words to the song. And you stand up in front of everyone else and you have a couple of beers – very important – and then you start singing. And usually, it’s pretty bad. And it was originally – very popular in Japan and then became popular in the United States and other countries as well. And I’m sure that’s not the pronunciation in Japan, but in English we say “karaoke.”
Well, Lucy says, “We should go to a karaoke bar again.” And I say, “Sure, anytime.” But, of course, I don’t want to go back. Then I say, “It was nice meeting you Marlene” – which is again the same with “It’s nice to meet you.” But when you first meet someone, in the United States, when you’re leaving, when you’re about to leave that person that you just met, you would say, “It was nice to meet you.” And she says, “Nice to meet you too,” meaning it was also nice for me to meet you. Lucy ends the dialog by saying, “Okay. Later.” And this is an informal expression you hear, especially among younger speakers. Somebody says, “Later” – means I’ll see you later – will talk to you later.”
Now let’s listen to the dialogue again, this time at a native rate of speech.
Lucy: Hey Jeff, have you met my friend?
Jeff: No, I don't think I have.
Lucy: Well, this is my oldest and best friend, Marlene. She's visiting from out of town.
Jeff: Hi, I'm Jeff.
Marlene: Hi, it's nice meeting you.
Jeff: How long do you plan to be in town?
Marlene: I'm here for the long weekend, staying with Lucy. We're doing some catching up and I'm getting a break from work.
Jeff: Oh, what line of work are you in? Are you in the same field as Lucy?
Marlene: No, I'm in medicine. I'm a doctor, actually, a pediatrician. I enjoy the work, but it's nice to get away for a few days. What kind of work do you do?
Jeff: I work in the education field, but what I really want to do is to become a professional singer.
Lucy: Jeff has a great voice. He sounds exactly like Frank Sinatra.
Marlene: Really?
Jeff: No, she's just kidding and Lucy knows that I can't sing. We went to a karaoke bar once and people actually offered me money NOT to sing.
Lucy: That was a lot of fun. We should do that again sometime.
Jeff: Sure, anytime. Oh, I'd better go. It was nice meeting you Marlene, and Lucy, I'll talk to you next week.
Marlene: Nice to meet you, too.
Lucy: Okay, later.
[end of dialog]
The script for today’s podcast was written by Dr. Lucy Tse. And we want to thank Dr. Marlene Rodriguez, who really is a doctor. Unlike me, she’s a real doctor and she was nice enough to help us with today’s dialog.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
to meet – to encounter; to see and learn about someone one does not know
* Ashley met Albert yesterday, but they did not know each other before then.
How long do you plan to be in town? – How many days or weeks will your visit be?; a question one asks to learn the amount of time or number of days someone else will be visiting
* When Bennett learned that his friend was visiting, he asked, "How long do you plan to be in town?"
long weekend – a vacation or break (change from normal activity) that lasts for one or two days more than a normal weekend; a weekend that includes Friday, Saturday, and Sunday, or Saturday, Sunday, and Monday
* Nicole did not have to work on Friday, so she’ll have a long weekend.
to stay with – to live with someone in that person's home for a short period of time; to spend several days with someone else in that person’s home
* Carson's brother lives in Florida, so Carson stayed with him during his vacation there.
to catch up – to learn about things that have happened in someone’s life since the last time you were in contact with them
* Kevin and Sarah had not seen each other since college, so they wanted to catch up and learn about each other's lives.
break – a change from normal activity; a change made for a short amount of time to allow one to relax
* The visit to his parents’ house was a nice break for Delon, since he had been very busy studying he was away at college.
What line of work are you in? – What type of job do you have?; a question asked to learn about the job or work someone else does to earn money
* Al said that he enjoyed his job, so Wendy asked, "What line of work are you in?"
field – the type of job or work one does to earn money
* Russell was in the field of education and worked at a university.
I'm in… – The type of work I do is…; a statement one makes when giving information about the type of work one does to make money
* Nora said, "I'm in art. I create paintings and sculptures."
pediatrician – a doctor who cares for babies and children
* The pediatrician was able to find out the cause of the illness and cure the child.
to get away – to leave; to go someplace else, usually away from one’s job to have time to relax
* Amir felt stressed and unhappy, so he wanted to get away for a few days.
kidding – joking; not being serious
* Rita was just kidding when she told her Italian boyfriend that she did not like pizza, but he did not understand the joke.
karaoke bar – a place of entertainment where people meet with friends and drink alcohol, and the customers volunteer to sing popular songs in front of the other customers
* Julian liked going to the karaoke bar with his friends, but he could not sing very well.
Culture Note
New Ways of Sharing
The expression “to share and share alike” is something you say when you want to remind someone, often a child, that it is good to give some of the things you have to others. When one child in a group of children has a lot of candy, he might be told by his mother or father to “share and share alike,” meaning that he should give some of the candy to his friends.
Sharing is good for adults, too, of course. The verb “to share” used to be used mostly with physical things like candy, but in the past few “decades” (10 year period), it has been used for people who give others information, usually about themselves, “as in” (such as the example) “I’d like to share with you what I did on my four-week vacation in Boise.” Sometimes we don’t really want to hear about other people’s lives, and so we’ll say, jokingly, “Thanks for sharing!” This usually means “I didn’t actually want to hear that – please stop!”
The Internet now uses share to mean to tell other people about a website. You can share by emailing or using one of the many social media sites, such as Facebook and Twitter. “To follow” normally means to go behind someone or to do what they are doing. On Twitter, it means that you will receive “tweets” (short, 140 character messages) on your Twitter account for those people you’re following.
Recently, Facebook has become very popular. The verbs often used with Facebook are “to like” and “to friend.” Facebook has pages for companies, websites, and groups that fans can “like.” “To like” is similar “to following” someone on Twitter – you get that page’s messages on your Facebook page. If you have a personal account, you can also “friend” people, meaning you can see their pages and will also get their “updates” (new messages they put on their own pages).