= 0138
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 138: Hotel Tour Desk.
You’re listening to English as a Second Language Podcast episode 138. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this podcast, we’re going to be talking about making a reservation in a hotel to take a tour. Let’s go!
[start of dialog]
Sam: Hi, is this where I can get information on tours?
Nan: Yes, I can help you with that. What type of tour are you thinking about? There are some great city tours that are half-day or full- day.
Sam: You know, we've explored the city a lot since we've been here. I was actually thinking of a side trip.
Nan: Oh, sure. We have excursions to nearby attractions. There are one-day trips or two-day overnight trips, depending on which one you pick.
Sam: I think I'm interested in a hiking trip to the mountains. I'm big on nature. Are the overnight trips expensive?
Nan: Not at all. They are very moderately priced, starting at $120 and up. Here's a brochure on the three hiking tours that are available. All three are guided tours, and meals and transportation are included.
Sam: Do I need to book ahead?
Nan: Yes, this company requires that you make a reservation 24 hours ahead.
Sam: Great. I'll take a look at the brochure. Can I book that here at the hotel tour desk, or do I call the company directly?
Nan: I can book that for you. Just stop by when you've made a decision and I'll take care of it for you.
Sam: That's great. Thanks a lot for your help.
Nan: It's my pleasure. Let me know if you have any questions.
Sam: I will. Thanks.
[end of dialog]
In this podcast, we are at a hotel and we are talking to the person who works at the tour desk – the place where you can go in a good hotel to reserve a tour. A “tour” (tour) can be anything from a couple of hours to a couple of weeks. A “tour” is a general term we use for – usually for when someone takes you somewhere and serves as your, we would call “guide” (guide) – and they’re called “the tour guide.” And that’s the person who knows all of the information and tells you the information and takes care of all of the arrangements that you need when you are travelling.
In the dialog, Sam asks Nan – the person working at the tour desk – if this is the place to get information on tours. She says it is, and asked “What kind of tour are you thinking about?” What are you planning? “There are some great city tours that are half-day and full-day,” she says. A “city tour” (city) – a “city tour,” of course, would be a tour of whatever city you are in. So, here in Los Angeles, the city tour would take you to the beach. It would take you to Hollywood and so forth.
A “half-day tour” (half-day) – “half-day,” of course, would be four hours usually – three to four hours. So, from eight in the morning until 12 noon or from one in the afternoon until five PM – that would be a half day tour. And a “full-day tour,” of course would be the entire eight hours or 10 hours. Sometimes, you go in a tour. It can last as much, a day tour of 12 hours.
Well, Sam says that they’ve explored the city and so he doesn’t want to take a city tour. To say “We have explored (explored) the city” means we’ve already looked around at the things to see here in the city. “To explore” usually means to go somewhere where very few people or no one has gone before, and we talk about the great explorers – people who went places where no one had gone before them. But here, as a verb, “to explore” just means to look at, to visit different places.
Sam says he’s actually thinking of a “side trip.” A “side (side) trip” – two words – would be, for example, you go to a big city like Los Angeles, but you want to travel down to see San Diego, which is about 2 hours from here, driving. So, you go down to San Diego, then you come back to Los Angeles, and stay in Los Angeles some more time. So, San Diego is a “side trip.” It’s a trip you take from the place where you are visiting.
Nan says that “We have excursions to nearby attractions.” An “excursion” (excursion) is usually, a short trip to somewhere, to some interesting place, usually, less than one day. So, we’re going to take an excursion to the Los Angeles Zoo, for example, to see the animals and the actors. We keep the actors in cages in a zoo here. I’m just kidding. We should, but we don’t.
So, you take an excursion to the zoo – that would be a short trip – or an excursion to the beach. An “attraction” (attraction) – an “attraction” is just an interesting place to visit, usually for someone who is a tourist. And, of course a “tourist” (tourist) is someone who is visiting – someone who is on vacation. And attractions could be, for example, Disneyland – could be an attraction. Venice Beach is an attraction – any place that’s interesting to visit is an attraction. The tour person also says that they have overnight trips. And of course, an “overnight (overnight) trip” is when you go somewhere and you stay at a hotel, maybe for one or two nights and then you come back to the hotel where you are staying. So, a side trip could be an overnight trip as well.
Sam says that he’s interested in a “hiking trip.” And “to hike” (hike) is to walk – usually in the mountains or somewhere out away from the city. He says that he’s “big on nature.” To say you are “big (big) on something” is an informal expression. It just means that you like it a lot. “I am big on singing.” I like to sing – not very well, but I am big on it. I like it. I enjoy it.
Sam asks if the tours are expensive and the tour operator – we would probably call her, or the tour desk person – says that they are moderately priced. When we say something is “moderately (moderately) priced (priced)” – to say something is “moderately priced” means it’s not expensive but it’s not “cheap” (cheap) either. “To be cheap” means to be very inexpensive – not to cost very much money. So, it’s not a lot of money, but it’s not a little money either. It’s somewhere in between – moderately priced.
The prices of the tours, according to the tour desk person, are “$120 and up.” When we use the expression with money, “and up” (up), we mean that it can be more expensive. It can cost more money. So, “The tours are $120 and up” means the cheapest tour, the least expensive tour, is $120, but there are more expensive tours also available - $140, $160 and so forth. So, the expression “and up” is used when you’re giving the lowest price of something but also telling the person that there are more expensive items or things that you are selling.
The person – Nan – then gives Sam a brochure, and a “brochure” (brochure) is a piece of paper – sometimes with pictures on it, sometimes it’s folded, and it gives you information about something that you are interested in buying. Usually – often we use brochures for tours, travel tours, so people can see pictures of where they are going to be visiting, get information about how long the tour lasts and so forth. You can also have a brochure for something you are selling. You’re selling, for example – if you are going to buy a car and you go to the place where they sell cars – what we would call a “car dealership” or a “car dealer” (dealer), someone who sells new cars – you can get a brochure about the car that will give you pretty pictures and information about it.
Nan says that all of the tours they have are “guided” tours – (guided) – “guided tours” and “to be guided” means, we’ve said before, that the person who runs the tour is the tour guide. Well, a “guided tour” is a tour that has someone who is in charge – someone who is giving you information and is the person who works for the tour company. Sam asks if he needs to “book ahead.” “To book,” (book) you probably know, means to make a reservation, to reserve. And “to book ahead” (ahead) means to make a reservation in advance – a day before or two days before you are going to go.
Nan says that “You do need do make a reservation 24 hours ahead.” Sam says, “Can I book here or do I call the company – the tour company – directly?” When we say, “I’m going to call them directly” (directly) we mean I’m going to call their headquarters. I’m going to call their company and make a reservation with the home or the main office. Nan says, “No. You can make the reservation here at the hotel. Just stop by when you’ve made a decision.” “To stop (stop) by (by)” – two words – means to go somewhere and in this case, to go back to the tour desk and give the information. So, “to stop by” means to return or to go somewhere for a short period of time.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of dialog]
Sam: Hi, is this where I can get information on tours?
Nan: Yes, I can help you with that. What type of tour are you thinking about? There are some great city tours that are half-day or full- day.
Sam: You know, we've explored the city a lot since we've been here. I was actually thinking of a side trip.
Nan: Oh, sure. We have excursions to nearby attractions. There are one-day trips or two-day overnight trips, depending on which one you pick.
Sam: I think I'm interested in a hiking trip to the mountains. I'm big on nature. Are the overnight trips expensive?
Nan: Not at all. They are very moderately priced, starting at $120 and up. Here's a brochure on the three hiking tours that are available. All three are guided tours, and meals and transportation are included.
Sam: Do I need to book ahead?
Nan: Yes, this company requires that you make a reservation 24 hours ahead.
Sam: Great. I'll take a look at the brochure. Can I book that here at the hotel tour desk, or do I call the company directly?
Nan: I can book that for you. Just stop by when you've made a decision and I'll take care of it for you.
Sam: That's great. Thanks a lot for your help.
Nan: It's my pleasure. Let me know if you have any questions.
Sam: I will. Thanks.
[end of dialog]
The script for today’s podcast was written as always, by Dr. Lucy Tse and we thank Lucy for her work.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
tour – excursion; an organized visit to one or more places so that one can become familiar with them and learn more about them, especially their cultural and historical importance
* They’re saving their money to go on a tour of Niagara Falls.
city tour – an organized trip to visit many places in a city, usually when one has never been to that city before
* New York City is so big that going on a city tour is really the only way to visit all the important sites in a short amount of time.
half-day / full-day – taking half or all of one day; needing four or eight hours
* Craig has a busy schedule, working five full-day shifts in his office job Monday through Friday, and two half-day shifts at the coffee shop on weekends.
to explore – to travel in and around an area to learn more about it and/or to discover something new
* Who was the first European to explore North America?
side trip – a short trip to an area outside of the city where one is staying; a tour of an area that isn’t visited by as many people as the main area
* While you’re staying in Portland, try to take a side trip to visit Multnomah Falls. It’s beautiful!
excursion – tour; trip; a visit to a particular place, usually for enjoyment and/or education
* While studying overseas, the students can pay an extra fee to go on interesting weekend excursions.
attraction – a place that is interesting to visit and that many tourists go to; a natural area or manmade building that has historical, scenic, or cultural importance and is fun and/or educational to visit
* Johnson Space Center is a major attraction in Houston for anyone interested in astronomy and space exploration.
overnight – including more than one day, so that participants sleep during the event
* Did you stay overnight at the coast, or did you go there and come back on the same day?
hiking – involving a long walk in a natural area, especially if it is physically challenging, but requiring no more than one day
* Whenever they go hiking, they take a large backpack filled with rain jackets, snacks, a whistle, and a medical kit.
big on – very interested in and excited by something; with a strong interest and passion for something
* Camilo has never been big on baseball, but he loves basketball and soccer.
moderately priced – not too expensive, but not extremely cheap; with a in-between price; not the most or least expensive
* Can you recommend a moderately priced restaurant where we can find a good hamburger for around $6-8?
and up – or higher; at least
* Our laptop computers are priced at $399 and up, depending on which features you want.
brochure – a folded piece of paper with text and images describing and providing information about something
* The doctor gave her a brochure about her skin condition and possible treatment options.
guided tour – a trip where a group of people are led by one individual who has a lot of knowledge about the area and its history and can provide information and answer questions
* I’m really glad we went on a guided tour of the art museum. If we had walked through it on our own, we wouldn’t have learned nearly as much.
to book ahead – to make a reservation in advance, before something happens or before something is needed; to make arrangements to have or do something at least one day before one needs to have or do it
* We recommend booking your hotel room at least a few months ahead of the graduation ceremony, because all the hotels in this city are really full that time of year.
directly – with personal interaction, without going through another person or company; without an intermediary; for Person/Company A to contact Person/Company B without needing help or assistance from Person/Company C
* The customer called with a complaint, but insisted on speaking with the CEO directly. He didn’t want to share his complaint with any other employees.
to stop by – to informally visit or go to a place without making arrangements ahead of time, instead doing it when it is most convenient for oneself
* Please feel free to stop by my office anytime during regular business hours, 8:00 to 5:00, Monday through Friday.
Culture Note
When booking a tour, it’s important to make sure the “travel agency” (the company that creates and leads the tour) is a “reputable” (with a good reputation) business. You can do this by reading about its services, speaking with people who have used its services in the past, and contacting the “Better Business Bureau” (a government agency that keeps track of complaints about businesses and their services).
Once you have found a reputable travel agency, research the types of tours it offers. Does it offer tours to the places you’re most interested in? Do those tours focus on historical information, cultural information, “extreme sports” (dangerous but fun physical games), or other things that you’re interested in? How often are the tours offered, and are those times “compatible with” (working well with; in alignment with) your “itinerary” (travel plans and schedule)? You’ll also want to know whether the tours are “within your budget” (not costing more than the amount of money one has available for a specific purpose).
If you have any “special needs” (requirements that most people don’t have), such as “food restrictions” (limitations on the kinds of food one can eat) or “disabilities” (things that one’s body cannot do), can the travel agency accommodate those needs? Other factors to consider include the tour guide’s experience and “depth of knowledge” (how much someone knows about something). The “tour group” (the people who participate in a tour) is important, too. Is there a minimum and maximum number of participants? Are there age restrictions? You might not want to be the youngest or oldest person in the tour group, so find out all you can about the other participants.