= 0466
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 466: Having a Good or Bad Bedside Manner.
This is English as a Second Language Podcast number 466. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
If you haven’t been to our website, please go to eslpod.com and download a Learning Guide for this episode to help your English even faster. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and a complete transcript of everything we say on this episode.
This episode is about bedside manner. It’s going to be a conversation about doctors, and it will use a lot of vocabulary that doctors might use when you go to visit them. Let’s get started.
[start of dialogue]
Cho: I’m not sure I’m cut out to be a doctor.
Joy: I think you’ll be great. I’ve seen you with patients and you have a great bedside manner – not like Gregory.
Cho: Why? What’s wrong with his bedside manner?
Joy: I’ve seen him with patients and he can be really callous. For instance, I was in the room last week when he was telling one of his patients that she was taking a turn for the worse.
Cho: What did he say?
Joy: He just blurted it out. He told her the diagnosis, and he didn’t even try to soften the news when she asked about her prognosis. He did absolutely nothing to try to comfort or reassure her.
Cho: I feel sorry for the patient.
Joy: That’s the point. Gregory didn’t, and it didn’t seem to faze him that the patient was very upset and close to hysterics.
Cho: That’s terrible. I’ll try to remember to be more compassionate with my patients.
Joy: Don’t worry. It’s against your nature to be anything but considerate.
[end of dialogue]
Our dialogue begins with Cho saying to Joy, “I’m not sure I’m cut out to be a doctor.” To be “cut out” means to be created to do something, something that is a good match for you, something that is intended for you. Someone might say, if you like to write and to ask people questions, you may be cut out to be a journalist (a reporter – someone who works at a newspaper). More often you’ll hear this expression in the negative: “He’s not cut out for that kind of work” – he is not made for that kind of work, he doesn’t have the talent for that kind of work.
Cho is a doctor, and says that he’s not cut out to be a doctor. Joy says, “I think you’ll be great. I’ve seen you with patients and you have great bedside manner.” “Patients” are people who are receiving medical care or attention from a doctor or a nurse. If you’re sick, you go in to see a doctor, you are a patient. “Bedside manner” refers to the way that a doctor or a nurse talks to people, how they give medical advice or instructions or other information. It’s a general term to refer to how doctors treat their patients – how they communicate with their patients, because that’s such an important part of medicine.
Joy says that Cho has great bedside manner – not like Gregory. Cho says, “Why? What’s wrong with his bedside manner?” Joy says, “I’ve seen him with patients and he can be really callous.” “Callous” (callous) means without considering another person’s feelings, somewhat mean, not being considerate of someone else, not thinking about the feelings of someone else. “Callous,” like the expression “cut out,” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations. Joy says, “For instance (for example), I was in the room last week when he was telling one of his patients that she was taking a turn for the worse.” The expression “to take a turn for the worse” means to be getting worse, to worsen; it’s the opposite of “getting better,” especially when you are talking about someone’s health. If you say, “She’s taken a turn for the worse,” you mean she has become sicker, she has become more ill.
Cho says, “What did he say?” meaning what did he say to this patient about taking a turn for the worse. Joy says, “He just blurted it out.” To “blurt (blurt) something out” is a phrasal verb meaning to say something without thinking about it first, without thinking about how it will sound to the other person or how that other person may react; it can be a good thing or a bad thing. In this case, it clearly was a bad thing because this other doctor, Gregory, told his patient the diagnosis and didn’t even try to soften the news when she asked about her prognosis. A “diagnosis” is the doctor’s conclusion about what the medical problem is; it’s the doctor’s idea about what the problem with your health is. “To soften (something)” here means to make it nicer, to make it easier to accept. So “to soften the news” means to tell someone something in such a way that it doesn’t upset them. We have an expression: “to soften the blow” (blow). “Blow” here means a punch or a hit. So if someone is going to give you bad news, they will try to soften the blow – to soften the news. Women sometimes do this to men who ask them out on a date. They’ll say, “Oh, I’m busy on Friday,” and the man says, “What about Saturday?” “Oh, I’m busy on Saturday, too.” If the man is intelligent, he’ll understand that she’s trying to soften the blow, instead of just saying, “No, you’re ugly!” for example. A “prognosis” (prognosis) is the doctor’s opinion about how your health will change in the future. So, “diagnosis” is what the doctor thinks is what is wrong with you; “prognosis” is what the doctor thinks the future will be for you. If you have a good prognosis, that means you will be healthy, or least live for a long time.
This doctor, however, did not try to soften the news about her prognosis; Joy says, “He did absolutely nothing to try to comfort or reassure her.” “To comfort” someone means to do or say something that will make the person feel better, make the person feel more comfortable. “To reassure” someone means to make them feel better about something; it’s similar to “comfort,” make them feel less worried about something or more confident about something. We have an expression: “Let me reassure you, there is nothing wrong with the American banking system.” The idea is that we are giving you confidence that everything is okay.
Cho says to Joy, “I feel sorry for the patient.” “To feel sorry for (someone)” is to understand the person’s difficulty, to empathize with someone. Joy says, “That’s the point. Gregory didn’t (meaning Gregory didn’t feel sorry for his patient), and it didn’t seem to faze him that the patient was very upset and close to hysterics.” The expression “didn’t seem to faze (faze) (someone)” is a phrase that means that you are surprised because someone else wasn’t affected by something or didn’t have a strong reaction to something. So, going back to our previous example: the man asks a woman out on a date, the woman says, “No, you’re ugly,” because she doesn’t try to soften the blow, you see – doesn’t try to comfort him, and the man is not fazed by her answer, he just turns to another woman and asks her out instead. He is not affected; he does not have a reaction to something that he should have a reaction to.
Now, Gregory was not fazed by what happened, even though the woman was close to hysterics. “Hysterics” (hysterics) is when you have uncontrolled emotions, when you can’t stop crying because the emotion is so strong in you. Cho says, “That’s terrible. I’ll try to remember to be more compassionate with my patients.” “To be compassionate” means to be caring, to be kind, to be nice to someone. Joy says, “Don’t worry. It’s against your nature to be anything but considerate.” The expression “to be against your nature” means it’s something that you can’t do because it’s not part of your personality; it’s not part of your character, it’s not part of who you are. “Anything but” is a phrase we use to emphasize the next word by saying it is definitely not true. For example: “The movie was anything but boring. It was, in fact, very exciting.” In this case, Joy is saying that Cho is anything but considerate. “To be considerate” means to be nice, to be aware of other people’s feelings. Joy is saying that it is against Cho’s nature, it is impossible for Cho to be anything but considerate; he is not going to be mean to his patients.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cho: I’m not sure I’m cut out to be a doctor.
Joy: I think you’ll be great. I’ve seen you with patients and you have a great bedside manner – not like Gregory.
Cho: Why? What’s wrong with his bedside manner?
Joy: I’ve seen him with patients and he can be really callous. For instance, I was in the room last week when he was telling one of his patients that she was taking a turn for the worse.
Cho: What did he say?
Joy: He just blurted it out. He told her the diagnosis, and he didn’t even try to soften the news when she asked about her prognosis. He did absolutely nothing to try to comfort or reassure her.
Cho: I feel sorry for the patient.
Joy: That’s the point. Gregory didn’t, and it didn’t seem to faze him that the patient was very upset and close to hysterics.
Cho: That’s terrible. I’ll try to remember to be more compassionate with my patients.
Joy: Don’t worry. It’s against your nature to be anything but considerate.
[end of dialogue]
It is against the nature of our scriptwriter, Dr. Lucy Tse, to be anything but brilliant in her scripts. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
cut out – intended for something; designed or created to do something; a good match for something
* If you like asking people questions and you enjoy writing, then you’re probably cut out to be a newspaper reporter.
patient – a person who receives medical care or attention from a doctor or nurse
* This hospital has beds for more than 700 patients.
bedside manner – the way that a doctor or nurse interacts with people when giving them medical advice, instructions, or other information
* Dr. Valls has a great bedside manner and always seems to have plenty of time to speak with us whenever we aren’t feeling well.
callous – unfeeling; without considering another person’s feelings; not courteous or considerate
*Jonna told her brother about the problems she was having at work, but his callous response was, “Why should I care?”
to take a turn for the worse – to worsen, especially when talking about one’s health or the success of a project or business
* The financial situation of their farm took a turn for the worse after the bad storm last month.
to blurt (something) out – to say something without first thinking about how it will sound to the other person, or without thinking about how that person will react
* When they offered the job to her, she blurted out “Hooray!” before she realized that it was inappropriate for them to hear her say that.
diagnosis – a doctor’s conclusion about a medical problem
* Santiago went to see the doctor because he had been having headaches, and he was surprised by the diagnosis.
to soften – to make something nicer, gentler, or easier to accept
* Do you think there’s a way to soften the news in telling Betty that she didn’t get the scholarship?
prognosis – a doctor’s opinion about how one’s health or medical condition will change in the future
* He was in a bad car accident, but the prognosis is good. He should be able to walk again within three months.
to comfort – to do or say something to make one feel better or more comfortable
* Sometimes simply giving a hug is the best way to comfort a friend who is sad or depressed.
to reassure – to make someone feel better about something; to make someone feel less worried about something, or more confident about one’s abilities to do something in a difficult situation
* The investors were reassured when they saw the company’s sales increase.
to feel sorry for (someone) – to empathize with someone; to spend time thinking about and understanding another person’s difficult experience and feeling sad about it
* I feel sorry for people who don’t live near their relatives. They must be lonely.
didn’t seem to faze (someone) – a phrase used when one is surprised that another person was not affected by something or did not have a strong reaction to something
* Everyone was surprised that it didn’t seem to faze Robb when his wife left him.
hysterics – uncontrolled emotions; when one cannot stop laughing or crying because one’s feelings are too strong to control
* Going into hysterics when your dog dies seems like an overreaction.
compassionate – caring, kind, and empathetic; feeling sad when other people feel sad
* Fortunately, he had a compassionate boss who let him take some time off work when he was having family problems.
against (one’s) nature – something that one cannot do or be because it isn’t part of one’s personality or character
* She is always very quiet, and it goes against her nature to yell at other people.
anything but – a phrase used to emphasize that the next word is definitely not true, or that the next word cannot be part of what one is talking about
* That movie was anything but interesting. We almost fell asleep halfway through it!
considerate – thoughtful; being aware of and concerned about other people’s feelings
* It was very considerate of you to make dinner for your neighbor when you knew he wasn’t feeling well.
Comprehension Questions
1. According to Cho, what’s wrong with Gregory’s bedside manner?
a) He’s too callous.
b) He’s too comforting.
c) He’s too compassionate.
2. How did the patient react when Gregory gave her his prognosis?
a) She became very angry and started yelling at him.
b) She began crying uncontrollably.
c) She became very quiet and wouldn’t say anything.
Answers at bottom.
What Else Does It Mean?
cut out
The phrase “cut out,” in this podcast, means intended, designed or created to do something: “If you’re afraid of heights, you probably aren’t cut out to be a pilot.” The informal phrase “cut it out” is used to ask someone to stop doing something: “Phil, cut it out! I’ve asked you not to do that a million times.” The phrase “to cut in line” means to go in front of other people who are standing in front of each other, waiting to do something: “Everyone started yelling when the woman cut in line at the bank.” Finally, the phrase “to be a cut above (something)” means to be better than something else or to have a higher quality: “That movie is definitely a cut above the rest.”
callous
In this podcast, the word “callous” means unfeeling, or without considering another person’s feelings: “He is a very callous man who never thinks about other people’s feelings.” The word is often used in the phrase “callous remark” to talk about a mean thing that someone said: “Her callous remark really hurt my feelings.” There is another word that sounds the same, but is spelled differently and has a different meaning: a “callus” is an area of very thick, hard skin, especially on the bottom of one’s foot: “She has a big callous on her finger from holding her pen too tightly.” Or, “He’s going to get a pedicure to try to get rid of the large calluses on his feet.”
Culture Note
Americans often “complain” (say negative things) about their doctors and other “healthcare providers” (people and institutions that provide medical care). Many Americans complain about how difficult it can be to schedule an appointment with their doctor. For example, “physicals” (annual exams of general health) sometimes have to be scheduled many months in advance. Another complaint is that once an appointment is scheduled, the patient is expected to arrive on time, but the doctor often comes late. The doctors sometimes get “behind schedule” (doing things later than planned) and the patients have to wait for a long time in the “waiting room” (the area where one sits until a nurse calls one’s name) and in the “medical exam room” (the small room where one speaks with a doctor).
One “common” (typical; usual) complaint is doctors don’t spend enough time with patients. In the United States, doctors are often “under a lot of pressure” (told that they need to do something) to see as many patients as possible each day. This is the best way for their medical office or hospital to make more money, but it means that each patient might see the doctor for only 5-10 minutes, or even less.
Americans also complain about the cost of seeing a doctor. Without health insurance, seeing the doctor is “prohibitively expensive” (so expensive that one cannot do something). Even a simple appointment may cost hundreds of dollars. Americans who don’t have health insurance rarely see a doctor until they have to go to the hospital for an “emergency” (a very critical, serious problem).
Comprehension Answers
1 - a
2 - b