= 0472
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 472: Feeling Nervous About Public Speaking.
This is English as a Second Language Podcast episode 472. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this episode.
This episode is called “Feeling Nervous About Public Speaking.” It’s a dialogue between Simone and Gabriel; they’re going to be talking about some common vocabulary used to describe when you get nervous before having to speak in front of a large group. Let’s get started.
[start of dialogue]
Simone: They’re about to introduce you. You’re on next. Are you ready?
Gabriel: No…yes…no!
Simone: You don’t look so well. Are you all right?
Gabriel: I don’t know. My palms are clammy, I’m breaking out into a cold sweat, and my legs feel like jelly.
Simone: It sounds like a bad case of stage fright, that’s all. Just take a deep breath. You’ll be fine.
Gabriel: I have butterflies in my stomach and my mouth is dry. Where can I get a glass of water?
Simone: I don’t know and there isn’t time.
Gabriel: Oh God, if I go out there, I’m going to freeze up or get tongue-tied. I just know it.
Simone: Get a hold of yourself. You’re well prepared and you’ll do a great job. Okay, they’ve just announced your name. Get out there!
Gabriel: I can’t!
Simone: The entire audience is waiting for you. Pull yourself together and get out there!
Gabriel: Here goes nothing!
[end of dialogue]
Our dialogue begins with Simone saying, “They’re about to introduce you. You’re on next. Are you ready?” Simone is talking to Gabriel; Gabriel is about to give a talk – a speech to a group of people. Simone says, “You’re on next,” meaning you are the next person to do something; it is your turn, we might also say. “Are you ready?” and Gabriel says, “No…yes…no!” Simone says, “You don’t look so well. Are you all right?” Gabriel says, “I don’t know. My palms are clammy.” Your “palms” are the insides of your hands, but not including your fingers. The word “palm” actually has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Gabriel’s palms are clammy (clammy). “Clammy” means a little bit wet, a little cold perhaps, not very pleasant to touch. Well, if you’re palms are clammy, typically that means you’re nervous. Gabriel says, “I’m breaking out into a cold sweat.” “To break out into a cold sweat” means to suddenly have your skin begin to feel wet, usually because you are very scared or nervous. Gabriel also says that his legs feel like jelly. “Jelly” is normally a sweet food made from fruit and sugar; it’s similar to another word, “jam” (jam). But here, it’s used to describe someone’s muscles feeling very weak. Somebody says, “My legs feel like jelly,” they mean my legs feel weak. Again, probably because you are nervous, at least that’s the case for Gabriel.
Simone says, “It sounds like a bad case of stage fright, that’s all.” “To have a bad case of (something)” means to have a serious or very severe instance or situation. You could have a bad case of coughing, if you were coughing a lot and it was causing you pain. Well, Gabriel has a bad case of stage fright. “Stage” describes the place where you stand to give a speech, or perhaps where the actors stand when they are performing a play. Usually it’s a little bit higher than the floor where you are sitting. “Fright” means to be afraid, so “stage fright” is fear of speaking or performing in front of a large group. When I was in high school, I was a member of the speech team. This was a group of students that competed with other students by giving speeches on different topics. I would always have some stage fright before it was my turn to speak.
Simone says to Gabriel, “Just take a deep breath. You’ll be fine.” “To take a deep breath” means to breathe in a lot of air very slowly; [Jeff inhales] that’s to take a deep breath. You let it out [Jeff exhales] and it helps relax you. Gabriel says, “I have butterflies in my stomach and my mouth is dry.” The expression “to have butterflies in your stomach” means that you feel very nervous and possibly sick. Your stomach, perhaps, is reacting to all the nervousness, the stress. So having butterflies in your stomach is another way of saying how nervous you are, so nervous that you might feel ill – you might feel sick.
Gabriel says, “Where can I get a glass of water?” Simone says, “I don’t know and there isn’t time” – you don’t have time to go get a glass of water. Gabriel says, “Oh God, if I go out there, I’m going to freeze up or get tongue-tied. I just know it.” When you “freeze up,” you are unable to move or do anything, usually because you are very scared or surprised at something. “To get tongue-tied” means to be unable to speak clearly or to say or make a complete sentence. So if you are freezing up and are tongue-tied, you’re not going to be able to talk. The verb “freeze” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Simone says, “Get a hold of yourself.” The expression “to get a hold of one’s self” means to calm down and control your words and actions. Someone who becomes very excited, very angry perhaps may be unable to control themselves. In Gabriel’s case, he’s very nervous, so Simone is saying get a hold of yourself, calm down, control your thoughts and actions. “You’re well prepared and you’ll do a great job.” “To be well prepared” means to be ready; you’ve done your work, you practiced – you are well prepared.
Simone then says, “Okay, they’ve just announced your name. Get out there!” Gabriel says, “I can’t!” Simone responds, “The entire audience is waiting for you.” The “audience” are the people who are waiting for Gabriel to speak. Simone says, “Pull yourself together and get out there!” “To pull yourself together” is a two-word phrasal verb meaning to calm down, to be able to do something. It is similar to “get a hold of yourself,” you have to calm down and perform – do whatever action you’re expected to do. In this case for Gabriel, it’s to give a speech.
Gabriel ends by saying, “Here goes nothing!” “Here goes nothing” is a phrase used to show that you are going to try to do something, but you don’t think you are going to be successful. When I was in college, every time I would ask a girl out on a date I would say to myself, “Here goes nothing!” I tried, but it usually wasn’t successful! Gabriel, however, is going to try to give his speech and get a hold of himself – pull himself together so that he can give the speech effectively.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Simone: They’re about to introduce you. You’re on next. Are you ready?
Gabriel: No…yes…no!
Simone: You don’t look so well. Are you all right?
Gabriel: I don’t know. My palms are clammy, I’m breaking out into a cold sweat, and my legs feel like jelly.
Simone: It sounds like a bad case of stage fright, that’s all. Just take a deep breath. You’ll be fine.
Gabriel: I have butterflies in my stomach and my mouth is dry. Where can I get a glass of water?
Simone: I don’t know and there isn’t time.
Gabriel: Oh God, if I go out there, I’m going to freeze up or get tongue-tied. I just know it.
Simone: Get a hold of yourself. You’re well prepared and you’ll do a great job. Okay, they’ve just announced your name. Get out there!
Gabriel: I can’t!
Simone: The entire audience is waiting for you. Pull yourself together and get out there!
Gabriel: Here goes nothing!
[end of dialogue]
The script for this episode was written by the well-prepared Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
you’re on – a phrase used to let someone know that it is his or her turn to do something
* Gabe will go first, followed by Declan and Kimberly. Then, you’re on!
palm – the inside part of one’s hand, not including one’s fingers
* She couldn’t find a piece of paper, so she wrote down the phone number on her palm.
clammy – damp or a little bit wet, cold, and unpleasant
* His hands were cold and clammy after he finished cutting the fish.
to break out into a cold sweat – to suddenly have one’s skin begin to get wet, usually because one is very nervous or scared
* Even though it was a cold day, he broke out into a cold sweat when he asked his girlfriend to marry him.
jelly – jam; a sweet food made from berries or fruit and sugar, also used to talk about the way one’s muscles feel when one is very weak and/or unable to control one’s movements
* After the doctor gave him anesthesia, his arms felt like jelly and he couldn’t control his hands.
a bad case of (something) – a serious, severe, or important instance or situation
* He thought he was having a heart attack, but the doctors said it was just a bad case of indigestion.
stage fright – the fear of speaking, acting, or performing in front of a large group of people
* How do professional actors avoid getting stage fright?
to take a deep breath – to breathe in a lot of air very slowly and then breathe it out again, usually to make oneself feel calmer
* When Dale gets angry, he takes a deep breath and counts to ten before he says anything.
butterflies in (one’s) stomach – a feeling of nervousness and possibly a sick feeling in one’s stomach because one is very scared or worried about something
* I wonder if reporters get butterflies in their stomach when they speak to world leaders.
to freeze up – to be unable to move or do something, usually because one is too scared or surprised
* Harvey really likes that actress, but when he saw her in a restaurant one day, he froze up and wasn’t able to do or say anything.
tongue-tied – unable to speak clearly or make a complete sentence
* As a teenager, he was always tongue-tied around girls.
to get a hold of (oneself) – to calm down and be able to control one’s words and actions
* Yes, we’re in a crisis situation, but it doesn’t do any good to panic. Get a hold of yourself and find a way to help!
well prepared – ready; having done all the necessary research, thinking, and other preparation so that one is ready to do something
* Their favorite professors are always well prepared for their lectures.
to pull (oneself) together – to calm down and be able to do something
* I can’t believe you’ve been crying over him for a whole month. Pull yourself together and start dating other people!
here goes nothing – a phrase used to show that one will try to do something, but that one doesn’t think it will be very successful
* This will never work, but if you insist, I’ll give it a try. Here goes nothing!
Comprehension Questions
1. Why is Gabriel’s mouth dry?
a) Because he has stage fright.
b) Because he took a deep breath.
c) Because he ate too many butterflies.
2. Why doesn’t Gabriel want to go onto the stage?
a) Because he didn’t prepare for his speech.
b) Because he thinks it’s too cold.
c) Because he’s afraid he won’t be able to speak well.
Answers at bottom.
What Else Does It Mean?
palm
The word “palm,” in this podcast, means the inside part of one’s hand, not including one’s fingers: “They gave each other a ‘high-five,’ hitting their palms against each other.” The phrase “to read (someone’s) palm” means to look at someone’s palm and know what is going to happen in the future: “A woman read his palm and said that he would live until he was 90 years old.” The phrase “to have (someone) in the palm of (one’s) hand” means to be able to control someone or make him or her do what one wants: “That boy is completely in love with you! You have him in the palm of your hand.” Finally, a “palm tree” is a type of tree that grows in warm, tropical climates with a few very large, pointed leaves at the top: “She wants to find a Hawaiian beach with lots of palm trees.”
to freeze up
In this podcast, the phrase “to freeze up” means to be unable to move or do something, usually because one is too scared or surprised: “Whenever she has to write an essay, she freezes up and doesn’t know how to begin.” The phrase “(one’s) blood freezes” means that one is very scared or frightened: “His blood freezes whenever he hears a baby scream like that.” The phrase “when hell freezes over” is used sarcastically when one doesn’t believe that something will ever happen because it is impossible: “A: Do you think you’ll ever jump out of an airplane? B: Sure, when hell freezes over!” Finally, the phrase “to freeze to death” means to feel very cold: “Can I borrow your jacket? I’m freezing to death!”
Culture Note
Some studies have shown that Americans fear public speaking more than anything else – even death! If you “express” (talk about) your fear of public speaking, Americans may offer you some “advice” (suggestions) for “getting over” (being able to not be affected by something) your stage fright. Much of the advice is “cliché” (a phrase that has been used so many times that it no longer has very much meaning), but it can be interesting, especially the first time you hear it.
Probably the most common clichéd advice for getting over stage fright is to “imagine” (think about something that isn’t real) your “audience” (the people listening to a speech) in their “underwear” (the clothing that people wear under their regular clothing). The idea is that you wouldn’t be “intimidated” (scared and frightened) by people wearing their underwear, just as you shouldn’t be intimidated by your audience. People also recommend avoiding “eye contact” (looking into another person’s eye), instead looking above the audience at the wall behind them.
Other people say that preparation is “key” (the most important thing). They recommend “rehearsing” (practicing) your speech “out loud” (with a spoken voice, not quietly in one’s head) many times. They also recommend rehearsing in front of a mirror so that you can see how you’ll appear on stage.
To “deal with” (control) some of the physical “symptoms” (things that happen on one’s body as a result of a condition) of stage fright, people sometimes recommend having a glass of water in case you get a dry mouth. If you have
“sweaty” (with liquid on one’s skin) palms, putting a special powder on your hands before speaking might help to keep them dry.
Comprehension Answers
1 - a
2 - c