= 0480
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 480: Riding in a Carpool.
This is English as a Second Language Podcast number 480. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode.
This episode is called “Riding in a Carpool.” A “carpool” is when several people ride together in one car to go, usually, to work. Let’s get started.
[start of dialogue]
Roberto: Hey, Loreto. Got a minute?
Loreto: I’m going to a meeting off-site, but we can talk if you don’t mind walking me to my car.
Roberto: Sure, okay. I just wanted to ask if you’re interested in carpooling to work. We only live a few blocks from each other.
Loreto: Thanks for asking, but I’m not sure carpooling would work for me. Sometimes I run late in the morning and I wouldn’t want to hold you up.
Roberto: We wouldn’t have to commute together every day, only on those days that are convenient for both of us. Carpooling has its advantages, too. In addition to doing our part for the environment, we could use the high-occupancy carpool lanes. That’ll save time, especially if there’s a lot of traffic congestion.
Loreto: Yeah, I guess that could cut down on our commute time.
Roberto: We also get preferential treatment for parking on the days we carpool.
Loreto: How would it work? Do we set up a schedule and take turns driving?
Roberto: Why don’t I swing by and pick you up tomorrow morning and we can talk more about it?
Loreto: If you don’t mind picking me up en route, that would be great. By the way, how do you know where I live?
Roberto: Oh, I asked around. See you tomorrow.
[end of dialogue]
Our episode begins with Roberto asking Loreto, “Hey, Loreto. Got a minute?” The word “hey,” nowadays, is sometimes used informally to say “hi” or “hello.” It’s a very informal use, however. Roberto asks if Loreto has got a minute, meaning do you have a short time to talk to me. When someone says, “Got a minute?” they mean I want to talk to you for a short amount of time, is this a good time.
Loreto says, “I’m going to a meeting off-site, but we can talk if you don’t mind walking me to my car.” “Off-site” means at a different location, not at your office in this case. Loreto asks Roberto to walk her to her car. “To walk (someone) to (somewhere)” means to accompany someone while they are walking; to walk alongside, we could say, that person – to walk with that person.
Roberto says, “Sure, okay. I just wanted to ask you if you’re interested in carpooling to work.” “To carpool” means to share a car with two or more people who are going to the same place. Usually carpooling relates to going to work, though you could carpool to a concert for example. Normally, however, it refers to two or more people riding in the same car. In many cities in the United States there are what are called “carpool lanes” on the freeways or the highways. These are parts of the road that only two or more people riding in the same car may use. It’s a way of encouraging people to not use as much energy, to cut down traffic – to reduce traffic by giving people a special lane on the freeway where they can drive if you have two or sometimes three or more people. These are very popular here in Los Angeles
Roberto says that he and Loreto only live a few blocks from each other, meaning they live very close to each other so it would makes sense for them to drive to work together. Loreto says, “Thanks for asking, but I’m not sure carpooling would work for me. Sometimes I run late in the morning and I wouldn’t want to hold you up.” “To run late” means to be behind your schedule, not to be on time, to do something later than you should. Someone says, “I’m running late,” they mean I have to go now, I am late for an appointment or I am behind my schedule. “Run” has many different meanings in English, as you probably know. Take a look at our Learning Guide for some additional explanations.
“To hold (someone) up,” as in when Loreto says, “I don’t want to hold you up,” means to delay someone, to do something so that the other person cannot get something done on time or as soon as he or she would like, to prevent someone from doing something on time or quickly. “To hold (someone) up,” then, means to delay them. Loreto was saying to Roberto sometimes I’m late in the morning and I don’t want you to be late, too – I don’t want to hold you up.
Roberto says, “We wouldn’t have to commute together every day, only on those days that are convenient for both of us.” “To commute” means to go from your home to your office and then back again. So, if Roberto and Loreto are going to carpool, they would be commuting from their homes to their office – assuming they work at the same office, which is normally the case. I carpooled – and notice we use it as a verb, as well – when I was commuting back in St. Paul, back in Minnesota when I live there many years ago. When I was teaching high school, I would with carpool with one of the other language teachers. She was a German teacher, I believe. That was commuting by using a carpool. We only did that a couple of days a week, on the other days we drove separately.
Roberto says, “Carpooling has its advantages, too. In addition to doing our part for the environment, we could use the high-occupancy carpool lanes.” “To do your part” means to help something happen, to contribute to something. “We want everyone to do their part,” we want everyone to do their share; we want everyone to do what they should do to help the larger group effort. A “high-occupancy carpool lane” is what I was talking about earlier when I mentioned carpool lanes; sometimes they’re called “high-occupancy.” “Occupancy” refers to how many people are there in a particular place or how many people could fit in a particular place. “High-occupancy” would be that you have many people, in this case in your car. The minimum is usually two people; sometimes the minimum to use these special carpool lanes is three people. In some states they’re called “HOV lanes,” where the “V” stands for vehicle, in this case a car or a truck. So, high-occupancy vehicle lanes or high-occupancy carpool lanes are the same thing.
Roberto says, “That will save time (meaning using the carpool lanes will save time), especially if there’s a lot of traffic congestion.” The idea here is that carpool lanes have fewer cars in them become most people drive themselves to work alone, so you can go faster in the carpool lane usually, especially if there is a lot of traffic congestion. “Traffic congestion” is when you have too many cars on the freeway or the highway, and it causes all of the cars to move very slowly.
Loreto says, “Yeah, I guess that could cut down on our commute time.” “To cut down on (something)” is a phrasal verb meaning to use less of something or to reduce something. Loreto is saying that yes, they could get to work faster if they used the carpool lanes. Roberto says, “We also get preferential treatment for parking on the days we carpool.” “Preferential treatment” is treating some people differently, being nicer to someone, or giving someone special benefits that you don’t give other people. In some companies, to encourage employees to carpool, they will give good parking spots for their cars if you carpool.
Loreto then asks, “How would it work? Do we set up a schedule and take turns driving?” “To take turns” means to do one thing after another: I do something and then you do something. Or if there are three of us, first I do something, then you do something, then the third person does something, and then I do something again, and so on, and so forth. That is “taking turns,” each person gets a chance to do something after the other person.
Roberto says, “Why don’t I swing by and pick you up tomorrow morning and we can talk more about it?” “To swing by,” when we’re talking about driving, means to go to a place for short period of time, especially someone’s office or home to visit with that person. In this case, Roberto is going to swing by – going to drive to her house and pick her up; that is, take her with him in his car. Loreto says, “If you don’t mind picking me up en route, that would be great.” “En route,” which is some times pronounced “en route” although the preferred pronunciation is “en route” or “en route,” is a French expression. In English, we use it to mean “on the way,” on the path between where you are starting and where you end up. So I go from my house, I stop and pick you up at your house, and together we go to work – I pick you up en route to work.
Loreto then says, “By the way, how do you know where I live?” Roberto answers, “Oh, I asked around.” “To ask around” means to get a piece of information by asking many different people until you find someone who knows the answer. “I asked around about someone who could recommend a good movie to me this weekend” – I asked many different people until I found someone who knew, who could give me that piece of information. Why Roberto was asking around about where Loreto lives is a little strange. It’s a little, ah, perhaps something that Loreto needs to be careful about, this Roberto – I don’t know, I don’t trust him!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Roberto: Hey, Loreto. Got a minute?
Loreto: I’m going to a meeting off-site, but we can talk if you don’t mind walking me to my car.
Roberto: Sure, okay. I just wanted to ask if you’re interested in carpooling to work. We only live a few blocks from each other.
Loreto: Thanks for asking, but I’m not sure carpooling would work for me. Sometimes I run late in the morning and I wouldn’t want to hold you up.
Roberto: We wouldn’t have to commute together every day, only on those days that are convenient for both of us. Carpooling has its advantages, too. In addition to doing our part for the environment, we could use the high-occupancy carpool lanes. That’ll save time, especially if there’s a lot of traffic congestion.
Loreto: Yeah, I guess that could cut down on our commute time.
Roberto: We also get preferential treatment for parking on the days we carpool.
Loreto: How would it work? Do we set up a schedule and take turns driving?
Roberto: Why don’t I swing by and pick you up tomorrow morning and we can talk more about it?
Loreto: If you don’t mind picking me up en route, that would be great. By the way, how do you know where I live?
Roberto: Oh, I asked around. See you tomorrow.
[end of dialogue]
If you ask around, I think you will find that the best scriptwriter is the one who wrote this script, Dr. Lucy Tse. Thank you Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
off-site – at a different location; not at the office
* The company’s old files are off-site, in a storage facility about a mile from the main office building.
to walk (someone) to (somewhere) – to accompany someone while walking somewhere; to walk alongside someone
* Please walk your little sister to school on her first day.
to carpool – to share a car when two or more people are going to the same place, often to work
* Do you want to carpool to the concert?
to run late – to be behind schedule; to not be on time; to be doing something later than one should
* Darham was running late this morning, so he didn’t eat breakfast before leaving for work.
to hold (someone) up – to delay someone; to do something so that another person cannot get something done on time or as soon as he or she would like; to prevent someone from doing something quickly or on time; to slow someone down
* I’d like to go running with you, but I’m a much slower runner than you are and I don’t want to hold you up.
to commute – to travel between one’s home and office every day
* Chantrelle dislikes commuting, so she’s considering moving closer to where she works.
to do (one’s) part – to contribute to something; to help something happen
* They’re doing their part to keep the park clean by picking up garbage once a month.
high-occupancy – with many people in a car, building, or a certain amount of space
* Giants Stadium in New Jersey is a high-occupancy stadium with seating for almost 80,000 people.
carpool lane – one straight, long part on a freeway or highway, separated by painted yellow or white lines, where cars can be driven only if two or more people are inside
* If you come with me, I can use the carpool lane and I’ll be able to get to the mall much more quickly.
traffic congestion – many slow-moving automobiles; many cars and trucks that cannot move quickly because there are too many automobiles on the road
* There’s a lot of traffic congestion on Highway 58 between 4:30 and 7:00 p.m. on weekdays because that’s when everyone is driving home after work.
to cut down on (something) – to reduce something; to have or use less of something
* Kai’s trying to cut down on coffee, drinking no more than two cups of coffee each day.
preferential treatment – the practice of treating people differently; the practice of being nicer or offering special benefits to one group of people
* That store gives preferential treatment to older people, giving them a 15% discount each Tuesday.
to take turns – to do something one after another; to do something so that it is first Person A, then Person B, then A, B, A, B, etc.
* Mindy and her husband take turns picking out which movie to watch on Friday nights.
to swing by – to go to a place for a short period of time, especially someone’s home or office; to visit a person for a short period of time
* Can I swing by your house tonight to pick up the books I accidentally left there last night?
en route – on the way; on the path between one’s starting and ending points
* They had planned to drive to the mountains without stopping, but they stopped en route to eat at a restaurant.
to ask around – to get a piece of information by asking many people until one finds the answer
* The company doesn’t have an official training program, so new employees spend a lot of time asking around to find things like the photocopy machines and fax machines.
Comprehension Questions
1. What reason does Roberto give for wanting to carpool with Loreto?
a) Because he wants to spend more time talking with her about work.
b) Because it’s a good way to save money on gasoline.
c) Because they’ll be able to get to work more quickly.
2. Where does Loreto want Roberto to pick her up?
a) On the street.
b) At her home.
c) At the office.
Answers at bottom.
What Else Does It Mean?
to run late
The phrase “to run late,” in this podcast, means to be behind schedule or to be doing something later than one should: “Declan called to say that he’s running late and we should start eating dinner without him.” The phrase “to run over” means to last too long, especially when talking about a presentation: “The speaker ran over by about 10 minutes, so we were late arriving at the next session.” When talking about feelings, the phrase “to run high” means to be very intense or extreme: “Excitement was running high as people waited for the president to give his speech.” Finally, the phrase “to run off with (someone)” means to secretly marry or begin to live with someone when other people think it is wrong: “We were all shocked that she ran off with Kyle.”
to cut down on
In this podcast, the phrase “to cut down on (something)” means to reduce something or to have or use less of something: “They’re trying to cut down on expenses by cooking at home instead of going to restaurants.” The phrase “to cut back on (something)” has the same meaning: “Mom says that if I cut back on the amount of time I spend watching TV, I’ll have more time to do my homework.” The phrase “to cut (someone) off” means to drive dangerously, passing another car and then quickly moving directly in front of that car: “Some guy cut us off on the freeway and we almost hit him!” The phrase “to cut (someone) off” also means to interrupt someone, or to begin speaking before another person has finished speaking: “I’m sorry to cut you off, but I have to go now. Can we finish this conversation tomorrow?”
Culture Note
In the United States, there are many types of programs that encourage people to drive less, usually because organizations or government “agencies” (parts of the government) want to reduce traffic congestion or protect the environment.
Many government agencies, businesses, and universities help people organize carpools. They might have websites where people can “upload” (copy information from one’s computer to a website) information about where they live and where they want to go, as well as when. The website “matches people up” (finds people with similar needs) and helps them exchange contact information so that they can begin carpooling.
Many cities with public transportation offer free “parking garages” (large buildings where cars can park on many levels) next to major “stations” (places where subways, busses, or trains stop) so that people can drive to the station from their home and park for free if they take public transportation the rest of the way to work.
Other cities offer “transit” (public transportation) “vouchers” (pieces of paper that can be used instead of money to get services or goods) to people who “give up” (stop using) their cars. If someone reduces his or her driving, or stops driving “altogether” (entirely), he or she receives vouchers that can be used on city buses.
Some states are considering “pay-as-you-drive” insurance. Most drivers pay a “fixed” (unchanging) amount for insurance twice a year, based on the type of car that they drive and their “driving history” (how well someone has driven in the past and whether he or she has received tickets or been in accidents). With pay-as-you-drive insurance, drivers pay insurance for each mile driven, and this provides a financial “incentive” (a reason to do something) for driving less.
Comprehension Answers
1 - c
2 - b