= 0486
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 486 – Having Limited Mobility.
This is English as a Second Language Podcast number 486. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there to download a Learning Guide for this episode, which contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and, best of all, a complete transcript of everything we say on this episode.
This episode is called “Having Limited Mobility.” “Mobility” is the ability to move around. It will be a dialogue between Gail and Mike using some vocabulary that would be related to people who are not able to move around with their body as easily as others. Let’s get started.
[start of dialogue]
Gail: Oh!
Mike: Are you okay?
Gail: Yeah, I’m just not used to these crutches yet. The doctor said I should start using them if I ever want to get out of this wheelchair, but I don’t have the strength to stand up.
Mike: You’ll get the hang of it. Don’t lose heart.
Gail: It should be easy now that my arm is out of the cast, but it just seems impossible. I feel I’m going to lose my balance each time I try to stand up.
Mike: Try again, and this time lean on me and I’ll try to serve as your legs until you can find your balance.
Gail: I wish I didn’t feel so utterly useless. It’s so frustrating!
Mike: I know. Just keep your eye on the ball and give it another try. The next thing you know, you’ll be limping along and then running a marathon. It’s just a matter of time before you get your mobility back.
Gail: Yeah, right. Okay, first things first. Let’s see if these useless legs of mine will cooperate this time.
[end of dialogue]
Our dialogue begins with Gail saying, “Oh!” She, we think, has hurt herself or is in pain. Mike says, “Are you okay?” Gail says, “Yeah, I’m just not used to these crutches yet.” She’s not used to – she’s not accustomed to these crutches. A “crutch” is a long stick that you put underneath your arms, in what we call the “armpit,” that’s the part that is underneath your shoulder. You use the crutches to move more easily when your legs are injured for some reason. So if you break your leg, you’ll probably be given two crutches to help you walk more easily.
Gail says, “The doctor said I should start using them (the crutches) if I ever want to get out of this wheelchair.” A “wheelchair” is a special chair that has wheels – not too surprisingly! It’s used by people who can’t walk easily or cannot walk at all because there is a problem with their legs. Gail says, “I don’t have the strength to stand up.” She’s saying I’m not strong enough to stand up. “Strength” means the energy and ability to use your muscles in a certain way; in this case, the muscles in her legs.
Mike says, “You’ll get the hang of it.” “To get the hang of (something)” means to learn to do something so that it becomes normal, easy for you, to be able to do something without having to think about it or put a lot of effort into it. If you drive a new car or you get a new piece of computer software, it may take you a while to get the hang of it – to get used to it, to do it well. Mike says, “Don’t lose heart.” This expression, “to lose heart,” means to give up, to think that you will never be able to do something. Mike says, “Do not lose heart,” meaning don’t give up.
Gail says, “It should be easy now that my arm is out of the cast, but it just seems impossible.” A “cast” (cast) here means a piece of plaster, which is a heavy, hard, white material that is put around a part of your body so that it won’t move. If you break your arm or your leg, they will usually put this big white cast on your leg or your arm so that you don’t move it. This allows the body to get better – to heal. “Cast” has a number of different meanings in English; take a look at our Learning Guide for some additional explanations.
Gail says, “I feel I’m going to lose my balance each time I stand up.” “To lose your balance” means to fall over or to start to fall over, perhaps because you are “dizzy,” meaning you feel somehow that your head is moving around and your body begins to become unsteady. Little boys, for example, sometimes like to turn around and around and around, if they do that too much, they get dizzy and they may lose their balance – they may fall down.
Gail says that she feels like she’s going to lose her balance each time she tries to stand up. Mike says, “Try again, and this time lean on me.” “To lean (lean) on (someone)” is a two-word phrasal verb meaning to support yourself against another person or thing, especially when you are standing. So for example if you hurt your leg, you may stand up and then lean on another person, put your arm or put your body against that person so that that person can help you stay standing so you won’t fall down. That’s the most common definition; there’s another meaning of this phrase, “to lean on (someone).” It can also mean to apply pressure, force, or perhaps even a threat to someone in order to get them to do something. It’s an expression you would probably hear if you are talking about a crime gang that is trying to pressure someone into doing something, perhaps even something illegal.
Mike says, “I’ll try to serve as your legs until you can find your balance.” “To serve as (something)” means to act as something, especially when the other thing is not available, to take the place of something else. For example, I have a big table that serves as my desk. It’s not a desk, it wasn’t designed to be a desk, it was made to be a table that you would sit and eat at, but I use it as my desk. It serves as – it takes the place of – it serves the function of my desk. The verb “serve” has many different meanings in English however; please take a look at today’s Learning Guide for some additional explanations.
Mike is telling Gail that he will help her stand up and help her walk. Gail says, “I wish I didn’t feel so utterly useless.” The word “utterly” (utterly) means completely, entirely, 100 percent. It’s often used to describe some sort of negative emotion. “I’m utterly exhausted today” means I’m completely tired; I’m very, very tired. In this case, Gail says she feels “utterly useless,” meaning 100 percent useless, completely useless. She says, “It’s so frustrating (it’s so discouraging)!”
Mike says, “I know. Just keep your eye on the ball and give it another try.” “To keep your eye on the ball” is an expression we use to mean to focus on your goal or objective; don’t get distracted by other things; don’t let other things bother you. If you are trying to win an Olympic gold medal, you need to keep your eye on the ball – you need to continue to focus and concentrate on something. You might hear the expression “he took his eye off the ball,” meaning he lost his focus, he didn’t pay attention to what he should of been paying attention.
Mike says, “The next thing you know, you’ll be limping along and then running a marathon.” The expression “the next thing you know” is used to say that something will happen very quickly, much more quickly than you thought, much sooner than you thought. So, sooner than you think, which is another way of saying this, “you’ll be limping.” “To limp” means to walk in a way that puts very little weight on one foot or leg, usually because you’re injured. So if you hurt your right leg, you will be limping, you will not be using your right leg very much, and so you will walk a little funny. Usually if you’re limping, you’re moving a little more slowly as well. A “marathon” is a long race for runners, approximately 26 miles. It’s a very common kind of long distance run, a “marathon.” It comes originally from Greek history – ancient Greek history, but we won’t talk about that now.
Mike says, “It’s just a matter of time before you get your mobility back,” before you get your ability to move around in your body easily. Gail says, “Yeah, right,” meaning she’s not really sure that’s true. “Yeah, right” is often used as an expression when someone doesn’t think it’s true. Even though they are saying something that sounds like they’re agreeing, in many cases – in most cases it means that they don’t agree with that. Gail says, “first things first.” We use this phrase to talk about the need to do things in order, one thing at a time. You have to do the most important thing first, the thing that comes first in order. She says, “Let’s see if these useless legs of mine will cooperate this time.” She’s saying yes, maybe someday I will be able to run a marathon, but first I need be able to walk, so she needs to get her legs to work properly for her.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Gail: Oh!
Mike: Are you okay?
Gail: Yeah, I’m just not used to these crutches yet. The doctor said I should start using them if I ever want to get out of this wheelchair, but I don’t have the strength to stand up.
Mike: You’ll get the hang of it. Don’t lose heart.
Gail: It should be easy now that my arm is out of the cast, but it just seems impossible. I feel I’m going to lose my balance each time I try to stand up.
Mike: Try again, and this time lean on me and I’ll try to serve as your legs until you can find your balance.
Gail: I wish I didn’t feel so utterly useless. It’s so frustrating!
Mike: I know. Just keep your eye on the ball and give it another try. The next thing you know, you’ll be limping along and then running a marathon. It’s just a matter of time before you get your mobility back.
Gail: Yeah, right. Okay, first things first. Let’s see if these useless legs of mine will cooperate this time.
[end of dialogue]
Our script for this episode was written by someone who always keeps her eye on the ball, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
crutch – one of two long sticks where one puts one end under one’s armpit (between one’s arm and body) and the other end reaches the ground, used to support one’s weight and help one walk when one cannot put very much weight on one’s legs
* She had to use crutches for six weeks after she broke her leg in a car accident.
wheelchair – a special chair on wheels, used by people who cannot walk
* The front entrance has a lot of stairs, so people in wheelchairs have to enter through the back entrance.
strength – enough energy to do something and the ability to use one’s muscles in a certain way
* He’s trying to increase the strength in his arms by lifting weights at the gym every morning.
to get the hang of (something) – to learn to do something so that one is comfortable doing it and it becomes easy and normal
* It took him many months to get the hang of the new computer software.
to lose heart – to give up; to think that one will never be able to do or have something because it is too difficult or expensive
* Dustin really wants to save their marriage, but he’s starting to lose heart.
cast – a piece of plaster (a heavy, hard, white material) that is put around a part of one’s body so that it cannot move while a broken bone is healing
* Doctor, how many weeks will I have to wear this cast on my arm?
to lose (one’s) balance – to fall over or start to fall over because one becomes a little bit dizzy or because the top of one’s body leans too far in one direction
* The little boy thinks it is fun to spin around in circles until he loses his balance.
to lean on – to support part of one’s weight against a person or thing while one is standing
* Victoria was tired of standing, but there was nowhere to sit down, so she leaned on a tree to rest.
to serve as (something) – to act as something, especially when that other thing is not available; to take the place of something else
* Michels is blind and has a special dog that serves as his eyes.
utterly – completely; entirely; 100%
* Jacques works really hard all week and is utterly exhausted by Friday.
frustrating – discouraging; the feeling of anger and disappointment usually caused by something being too difficult
* If reading the newspaper in Korean is too frustrating, why don’t you try reading some children’s stories instead?
to keep (one’s) eye on the ball – a phrase used to mean that one should focus on the goal or objective and not be distracted by other, less important things
* I know it’s hard to save money, but keep your eye on the ball and think about how great it will be to have money when you retire.
next thing you know – a phrase used to talk about something that will happen surprisingly soon if one does something else first
* Pay attention in class and study for the tests, and the next thing you know, you’ll be getting good grades.
to limp – to walk in a way that puts very little weight on one foot or leg, usually because it is injured or hurting
* Jan limped for a few days after he twisted his ankle.
marathon – a long race for runners, usually 26 miles (42 kilometers)
* He finished the marathon in 4 hours and 56 minutes.
mobility – the ability to move freely and easily
* This city doesn’t have very good public transportation, so without a car, you’ll have very limited mobility.
first things first – a phrase used to talk about the need to do things in order or one at a time
* It would be great to invite your parents over for dinner, but first things first. We need to pick up all the things that are on the floor, dust, and vacuum.
Comprehension Questions
1. What might you use if you have a broken arm?
a) Crutches.
b) A wheelchair.
c) A cast.
2. What does Mike mean when he tells Gail to keep her eye on the ball?
a) She should watch the basketball game.
b) She should learn to play sports in a wheelchair.
c) She should focus on trying to walk again.
Answers at bottom.
What Else Does It Mean?
cast
The word “cast,” in this podcast, means a piece of plaster (a heavy, hard, white material) that is put around a part of one’s body so that it cannot move while a broken bone is healing: “He has to wear a cast that goes all the way from his knee down to his toes.” A “cast” is also the group of actors who are in a play, TV show, or movie: “Are there any famous actors in the cast?” In a factory, a “cast” is the shape that hot, liquid plastic or metal is poured into so that it has that same shape when it cools: “This plastic toy is made by using three separate casts.” Finally, when talking about fishing, a “cast” is the way that a line is thrown into the water to catch a fish: “Jeremiah made a great cast and caught a fish right away.”
to serve as
In this podcast, the phrase “to serve as” means to act as something, or to take the place of something, especially when that other thing is not available: “She lives in a small apartment, so her dining table serves as her desk.” The phrase “to serve (something) up” means to give people something to eat as part of a meal: “Grandma Evelyn always serves up a big breakfast of eggs, sausage, and pancakes.” The phrase “to serve (something) out” means to do something for a period of time and finish it: “The president has to serve out a four-year term.” Finally, the phrase “to serve (somebody) right” is used when something bad happens to someone and one thinks it is a good punishment for something bad that he or she has done: “Losing his favorite toy serves him right. He’s never careful about where he puts his things.”
Culture Note
The United States Army has many hospitals, but the Walter Reed Army Medical Center in Washington, D.C. is the most well known “facility” (large building). It is only for people who are “serving” (working) in the “military” (the people and organizations who fight for the United States) and people who have “retired” (stopped working in old age) from the military.
The “site” (place; location) has been a hospital since 1898 and used to have a “bed capacity” (space for a specific number of patients) of only 80 patients. Since then, it has grown significantly. The Medical Center now has 5,500 rooms, with “room” (space) for more than 150,000 “patients” (sick or injured people who are being treated by a doctor). It was named after an army “physician” (doctor) named Walter Reed, who discovered that yellow fever was “transmitted” (shared among people) by “mosquitoes” (small insects).
In 2007, there was a “scandal” (something that surprises people in a bad way) about the Medical Center. The Washington Post, the most popular newspaper in Washington, D.C., “broke a story” (was the first to report) about “neglect” at the facility, where patients were not being treated well, the building was “deteriorating” (falling apart; becoming worse), and there were many “bureaucratic nightmares,” where families had to speak with a lot of people and do a lot of paperwork to get treatment for their loved ones.
However, in general, Walter Reed provides valuable medical care for many “soldiers” (people who fight in the military) who have been “wounded” (injured) while serving their country.
Comprehension Answers
1 - c
2 - c