

= 事件的独立性
:toc: left
:toclevels: 3
:sectnums:

---

== 事件的独立性

事件的独立性, 是指: A发生的概率, 不受B是否发生的影响. 即: stem:[ P(A|B)=P(A)],  +
即: 即使B发生的条件下, 来看A发生的情况, 其发生概率和A单独自己发生, 没有任何区别. 换言之, 有没有B先发生, 对A的发生概率毫无影响.

事件相互独立: 就是指一个事件发生，不会影响另一个事件的发生或不发生. 两个事件没有相关性，相关系数为0。

从数学语言上（即定义）：stem:[ P(AB)=P(A) \ cdot P(B)]

注意区别: +
[options="autowidth"]
|===
|事件A的"条件概率"stem:[ P(A丨B)] |事件A的"无条件概率" stem:[ P(A)]

|事件B的发生, 改变了事件A发生的概率，也即事件B对事件A有某种“影响”.
|这里, 事件B的发生, 对事件A的发生毫无影响，即有，stem:[ P(A丨B)=P(A)]. +
由此又可推出 stem:[ P(B丨A)=P(B)]，即事件A发生对B也无影响. 可见独立性是相互的。
|===

---

== A,B 是两个相互独立的事件, 则有: stem:[  P(AB)= P(A) \cdot P(B)]

两个相互独立的事件A和B 都发生的概率, 等于每个事件发生的概率的积. 即: stem:[ P(AB)=P(A ∩ B) = P(A) \cdot P(B)]

即, 若有 stem:[  P(AB)= P(A) \cdot P(B)], 则, A,B是两个相互独立的事件.

另外, "Φ 和 Ω" 与"任意事件A" 都独立.

---

== 若A,B是互相独立的事件, 则有: ① A与stem:[ \overline(B)]独立; ② stem:[ \overline(A)]与B独立; ③ stem:[ \overline(A)] 与 stem:[ \overline(B)] 独立

既然A,B 是相互独立的事件了, 所以彼此发生或不发生, 对另一方是毫无影响的, 所以, 比如对A来说, 无论B是 B的状态, 还是stem:[ \overline(B)]的状态, 它们与A都是互相独立的事件.

---

== 若 stem:[ P(A)=0 或 P(A)=1], 则 A与"任意事件"都互相独立.




https://www.bilibili.com/video/BV1ot411y7mU?p=16&spm_id_from=pageDriver&vd_source=52c6cb2c1143f8e222795afbab2ab1b5

14.34
