= 0967
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 967 – Feeling Embarrassed.
This is English as a Second Language Podcast episode 967. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this episode. You may also want to take a look at our ESL Podcast Store with some additional courses in English, as well as our ESL Podcast Blog.
On this episode, we’re going to hear a dialogue between Lois and Roger about being embarrassed. Let’s get started.
[start of dialogue]
Lois: Please don’t embarrass me at the party tonight.
Roger: Me, embarrass you? I’d never do that.
Lois: You have, though, more than once.
Roger: Name one.
Lois: At the Johnsons’ party, you danced on the table while singing “I Am Woman”!
Roger: I was being the life of the party. Everybody thought it was funny.
Lois: It was humiliating! Didn’t you notice more than one person cringing and the awkward silence in the room when your song ended?
Roger: No, I didn’t, but I did notice Malik laughing his head off and the Johnsons smiling.
Lois: That’s because Malik has your sense of humor and the Johnsons were humoring you. They were trying to put a good face on your impromptu performance.
Roger: I’m not going to be a wallflower just because you can’t take a joke. My exuberant personality is what gets us invited to so many parties.
Lois: Yeah, right. Can I at least get you to promise not to sing?
Roger: And disappoint my audience? Not a chance!
[end of dialogue]
Lois begins by saying to Roger, “Please don’t embarrass me at the party tonight.” “To embarrass” (embarrass) someone means to make someone feel uncomfortable, to make them feel, perhaps, self-conscious. Lois is asking Roger not to embarrass her at the party tonight. Roger says, “Me, embarrass you? I’d never do that.” Notice Roger says “me” instead of “I.” In informal English, in situations like this, we often use “me” instead of “I,” even though “I” is the grammatically correct form. Lois says, “You have, though, more than once,” meaning you have, in fact, embarrassed me more than one time.
Roger says, “Name one,” meaning give me a specific example. Lois then gives him a specific example. She says, “At the Johnsons’ party, you danced on the table while singing ‘I Am Woman’!” The Johnsons are probably friends of Roger and Lois. At the party that was held at the Johnsons’ house, Roger got up on top of a table and started dancing and singing the song “I Am Woman.” “I Am Woman” is a song from the 1970s by, I believe, Helen Reddy.
“I am woman, hear me roar,
In number’s too big to ignore . . .
Dah dah dah dah dah dah
Dah dah dah dah dah daaaah dah”
I really don’t know this song since I am not a woman.
Roger says, “I was being the life of the party.” That expression, “the life of the party,” means the person who is always very entertaining, someone who is always making jokes, perhaps. Roger says, “Everybody thought it was funny.” Lois disagrees. She says, “It was humiliating.” “Humiliating” (humiliating) is something that is very embarrassing, extremely embarrassing – something that makes you feel ashamed in front of other people, something that makes you feel really bad in front of other people. Lois thought that Roger’s singing was humiliating.
She says, “Didn’t you notice more than one person cringing and the awkward silence in the room when your song ended?” “To cringe” (cringe) means to have a very negative feeling caused by being embarrassed when someone does something unpleasant or difficult to watch. If your friend is doing something very badly, like singing or dancing, you might cringe. You might feel embarrassed for that person because they’re doing something that is very embarrassing. Lois says there were people “cringing” at Roger’s performance – his singing and dancing – and there was an “awkward silence in the room” when his song ended.
“Silence” is the absence of noise – when it is completely quiet. “Awkward” (awkward) is something that is uncomfortable, something that people don’t like, often in a certain situation. An “awkward silence” would be when people don’t say anything when you would expect them to say something. So, for example, if your friend sees you at a bar and you’re with your friend’s girlfriend, he might come up to you and not say anything. There would be a very awkward silence. He might hit you, but the situation would certainly be considered awkward.
Roger says, “No, I didn’t,” meaning no, I didn’t notice; I didn’t see people cringing or notice the awkward silence. “I did notice Malik laughing his head off and the Johnsons smiling.” “To laugh your head off” is to laugh very loudly for a long period of time because you think something is very, very funny. Lois says, “That’s because Malik has your sense of humor and the Johnsons were humoring you.” The phrase “sense (sense) of humor (humor)” refers to the kinds of things that someone thinks are funny, the kinds of things that someone would laugh at. That’s your “sense of humor.”
Some people laugh at very obvious physical humor or physical comedy – people falling, people falling down the stairs or falling over. Some people think that’s funny. That’s their “sense of humor.” Other people think other things are funny. Each of us has our own sense of humor, our own set of things that we find funny. Lois explains to Roger that Malik was laughing his head off because he has Roger’s sense of humor.
The Johnsons, however, were humoring Roger. “To humor” someone, as a verb, means to do or say something to make the other person happy or to make sure the other person doesn’t get angry. Usually the verb is used to indicate that the person is pretending, doesn’t really believe what they’re saying, or perhaps is not trying to cause any problems. So, they’re just agreeing with the other person. If someone is humoring you, they don’t really agree with you or they don’t really believe, perhaps, the things they are saying to you, but they don’t want you to get angry or upset. So, they say those things anyway.
Lois says, “They were trying to put a good face on your impromptu performance.” “To put a good face on” something means something similar to “to humor someone.” It means to pretend to be happy or satisfied with something, to try to be positive about something rather than negative. “Impromptu” (impromptu) means without any planning. We might also use the word “spontaneous.” Something that is “impromptu” is something that you do that you didn’t plan to do. You just decided to do it suddenly.
Roger says, “I am not going to be a wallflower just because you can’t take a joke.” A “wallflower” (wallflower) is a person who is very shy, who doesn’t talk to other people, especially at a party or a large gathering. “To take a joke” means to think something is funny, especially when people are laughing at you. If someone says you “can’t take a joke,” he means that you don’t think things are funny that everyone else thinks are funny.
Roger says, “My exuberant personality is what gets us invited to so many parties.” “Exuberant” (exuberant) means with a lot of enthusiasm and excitement. Roger is saying that it is because he is so exciting and interesting that he and Lois get invited to so many parties. Lois doesn’t believe this at all. She says, “Yeah, right.” Notice that even though it sounds as if she were agreeing with Roger, in fact she is disagreeing with Roger. We know that by the way that she says this expression: “Yeah, right.”
Lois says, “Can I at least get you to promise not to sing?” Roger replies, “And disappoint my audience? Not a chance.” “To disappoint” someone is to make someone feel sad by not meeting their expectations – by doing something less than what people thought you would do. Roger says his “audience” – that is, the people who will watch him sing and dance – would be disappointed if he didn’t do his thing. That’s why he ends the dialogue by saying, “Not a chance,” meaning no way; there is no possibility of that happening – in this case, of Roger not singing.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lois: Please don’t embarrass me at the party tonight.
Roger: Me, embarrass you? I’d never do that.
Lois: You have, though, more than once.
Roger: Name one.
Lois: At the Johnsons’ party, you danced on the table while singing “I Am Woman”!
Roger: I was being the life of the party. Everybody thought it was funny.
Lois: It was humiliating! Didn’t you notice more than one person cringing and the awkward silence in the room when your song ended?
Roger: No, I didn’t, but I did notice Malik laughing his head off and the Johnsons smiling.
Lois: That’s because Malik has your sense of humor and the Johnsons were humoring you. They were trying to put a good face on your impromptu performance.
Roger: I’m not going to be a wallflower just because you can’t take a joke. My exuberant personality is what gets us invited to so many parties.
Lois: Yeah, right. Can I at least get you to promise not to sing?
Roger: And disappoint my audience? Not a chance!
[end of dialogue]
Our scriptwriter is always the life of the party. That’s because she’s the wonderful, witty, exuberant Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
to embarrass (someone) – to make someone feel uncomfortable and self-conscious
* Dad, please don’t hug me in public. It embarrasses me!
the life of the party – a person who is very entertaining and fun to be around; the most exciting and interesting person at an event
* Trenton always tries to be the life of the party, but most people just find him to be annoying.
humiliating – extremely embarrassing; making one feel ashamed in front of other people
* Jaycee’s boyfriend broke up with her in front of a big group of friends. It was humiliating for her!
to cringe – to have a negative feeling of embarrassment when someone does something unpleasant or difficult to watch
* His dancing was so bad that everyone in the audience was cringing.
awkward silence – a period of time when nobody is speaking, because nobody can think of anything appropriate to say, but everyone would like someone else to say something because it is uncomfortable to be silent in the situation
* Winston asked Bethany to marry him in front of a large group of family and friends, so when she said “no,” there was a very awkward silence.
to laugh (one’s) head off – to laugh very loudly and uncontrollably for a long period of time because something is very funny
* The kids are laughing their heads off. What TV show are they watching?
sense of humor – the ability to perceive (understand) what makes things funny, laughing at other people’s jokes and telling jokes to make other people laugh
* Edgar has a great sense of humor and is always able to see the funny side of even the most serious situations.
to humor (someone) – to do or say something to make another person happy; to do what another person wants one to do so that he or she does not get upset; to pretend to agree with someone
* I know you don’t enjoy going having dinner with my friends, but please humor me and pretend you’re having a good time.
to put a good face on – to pretend to be happy or satisfied with something; to focus on the positive side of something that is mostly or entirely negative
* Kimi is trying to put a good face on her husband’s job loss by saying that now he’ll have more time to spend with the kids, but she’s really very worried about their loss of income.
impromptu – spontaneous; without previous planning
* The speaker is stuck in traffic. Could you please make an impromptu presentation while we wait for her to arrive?
wallflower – a person who is very shy and spends time on the edge of a group of people because he or she does not want to interact with others or does not know how to, especially at a dance
* Josie was such a wildflower when we were in high school, but now, 10 years later, she’s the center of attention!
to not be able to take a joke – to treat everything very seriously and not be able to recognize the humor in a situation, especially when one is being laughed at by others
* Oh, don’t be mad. It was supposed to be funny! We didn’t realize you can’t take a joke.
exuberant – with a lot of enthusiasm and excitement; without limits, restrictions, or hesitation
* As soon as the presenter announced the award recipient, the audience became exuberant.
to disappoint – to make someone feel sad by not meeting his or her expectations; to perform or occur at a level that is lower than what people were expecting or hoping for
* Were you disappointed when your daughter decided to become a teacher instead of a doctor?
not a chance – no way; a phrase used to show that there is no possibility of something happening
* Do you really think a bank will give you a loan when you’re unemployed? Not a chance!
Comprehension Questions
1. What was Malik doing when he was laughing his head off?
a) He was laughing in a mean, cruel way.
b) He was laughing uncontrollably because it was very funny.
c) He was refusing to laugh.
2. What does Roger mean when he says, “I was being the life of the party”?
a) He was being the funniest and most interesting person at the party.
b) He was trying to ask someone to dance.
c) He was being the host of the party.
Answers at bottom.
What Else Does It Mean?
to laugh (one's) head off
The phrase “to laugh (one's) head off,” in this podcast, means to laugh very loudly and uncontrollably for a long period of time because something is very funny: “The comedian gave a great performance and everyone was laughing their head off.” The phrase “to laugh all the way to the bank” means to make a lot of money easily, often by tricking others: “If they sign the contract, we’ll laugh all the way to the bank.” The phrase “no laughing matter” describes something that is very serious and should not be the subject of a joke: “Violence against children is no laughing matter.” Finally, the phrase “to laugh (something) off” means to laugh to pretend that something is less serious or important than it really is: “You can’t just laugh off a heart disease. You need to improve your diet and start to exercise.”
not a chance
In this podcast, the phrase “not a chance” means no way and is used to show that there is no possibility of something happening: “You thought I would watch your kids for free? Not a chance!” The phrase “on the off chance” describes doing something just in case a certain thing happens even though it is very unlikely: “Please bring your swimsuit, on the off chance that it’s warm enough to swim in the ocean.” The phrase “to have a chance” means for something to be possible: “Do you really think the team has a chance of winning?” Finally, the phrase “by any chance” is used to ask a question or make a request in a very polite way: “By any chance, could you loan me a pencil?”
Culture Note
Types of Parties
Most Americans love to go to parties where they can spend time with friends. Sometimes the parties are for annual events, such as Christmas parties and “4th of July” (Independence Day) parties. Birthday parties are common, especially for children. Americans sometimes have a “Sweet 16” party for a daughter when she “turns 16” (celebrates her 16th birthday), and some Latino families have a “quincea?era” party when their daughter turns 15.
Other parties celebrate special achievements. Many families organize “graduation parties” when their child completes high school or college. Other people might organize parties to celebrate the publication of a book or the release of a new album. At work, “colleagues” (co-workers) often organize “goodbye parties” when people leave their job to work for another company, or “retirement parties” for older workers who stop working.
Other parties are “purely” (entirely) “social” (designed for spending time with friends). For example, a “housewarming party” is “thrown” (organized and arranged) by people who move into a new apartment or home. The “hosts” (the people who arrange a party) usually provide “finger foods” (foods that can be eaten without silverware, such as forks, knifes, and spoons) and the guests bring gifts that can be used in the new home.
A “block party” or a “neighborhood party” is an outdoor party attended by people who live in a particular area. Simple neighborhood parties might involve grilling hamburgers and hot dogs while children play ball games. More “elaborate” (fancy, with many details) block parties might have live music and “vendors” (people who sell food and other things).
Comprehension Answers
1 - b
2 - a