= 0968
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 968 – Recording an Outgoing Voice Mail Message.
This is English as a Second Language Podcast episode 968. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast, won’t you? If you do, you can download the Learning Guide for this episode.
This episode is about recording a message that people will hear when they call you on the phone and you don’t answer. Let’s get started.
[start of story]
I hate the sound of my own voice. I always have. When I’m speaking to an audience, I always sound forced and unnatural. So when we had to set up our new voice mail system’s outgoing message, it took me a few tries to get it right.
“Hello, you’ve reached Martin Navra at McQ Corp. I’m not available to take your call right now. Please leave a message and I’ll call you back as soon as I can. Thank you for calling.”
No, that wasn’t quite right. I gave it another shot.
“Hello, you’ve reached the voice mail for Martin Navra at McQ Corp. I’m in a meeting or away from my desk. Please leave a message and I’ll call you back as soon as I can. If your call is urgent, please contact Julia Mann at 555-434-3232. Thank you.”
That seemed okay, but since I was leaving on vacation next week, I needed to record a temporary outgoing message as well. This is what I came up with:
“Hello, you’ve reached the voice mail of Martin Navra at McQ Corp. I will be on vacation from March 3rd through March 10th. If you need to reach someone immediately, please call Julia Mann at 555-434-3232, or dial “0” to reach reception. Otherwise, please leave a message and I’ll return your call when I return. Thank you.”
I was finally done. The good thing is, whenever I call to retrieve my voice mail messages, I can bypass my outgoing message. With any luck, I’ll never have to hear my own voice again – ever!
[end of story]
Our story begins with Martin saying, “I hate the sound of my own voice.” A lot of people say that. They don’t like to hear themselves in a recording. The person in our story says that he hates the sound of his own voice. “I always have,” he says. “When I’m speaking to an audience, I always sound forced and unnatural.” “Forced” (forced) here means trying to do something but having difficulty doing it in a natural way. Something that is “forced” is something that you know the person is having difficulty doing.
“Unnatural” is the opposite of “natural.” “Natural” is when you do something without thinking about it so that it seems completely normal. “Unnatural” would be something that is somehow not normal. Martin continues, “So when we had to set up our new voice mail system’s outgoing message, it took me a few tries to get it right.” “To set up” something, or “to set something up,” is a two-word phrasal verb meaning to get something ready to do something, especially if you are using it for the first time. If you buy a new television from a store, and you bring it back to your house or apartment, you have to set it up; you have to connect the cables and get it ready so that you can use it.
Martin is setting up his new voice mail system’s outgoing message. “Voice mail” is the system that records a message when you are not there to answer the phone. In the old days, we used to have little answering machines with small cassette tapes in them that would record messages. Nowadays, it’s more common that your phone company will set up a “voice mail box,” they’re called, for you.
Basically, it’s a place on their computers that they store the messages that people leave for you, and then you can call in and get the messages from the computer that recorded them. This is a system that is quite common in many places, and it is often used in companies so that the employees can receive messages even when they are not answering their phone.
Martin is setting up his new voice mail system’s outgoing message. Your “outgoing (outgoing) message” is the message that people hear when they call you. “Hi. I can’t come to the phone right now. Please leave a message and I’ll call you later” – that would be a typical outgoing message on someone’s personal phone. “I can’t come to the phone right now” means I am not able to answer the phone. Then you tell the person to leave a message and you will call them back later.
In our story, Martin is trying to set up his outgoing message, but he says, “It took me a few tries to get it right.” A “try” (try), as a noun, is an attempt – your effort to do something. “Tries” would be trying to do it more than once – many different attempts. We then hear Martin’s first outgoing message, the first one he records:
“Hello, you’ve reached Martin Navra at McQ Corp. I’m not available to take your call right now. Please leave a message and I’ll call you back as soon as I can. Thank you for calling.”
The outgoing message begins by Martin identifying himself – telling people his name. This is always a good idea in your outgoing message, to let people know what your name is so they know that they have reached the correct person, that they have gotten the right person for whom they can leave a message. Martin continues, “I’m not available to take your call.” When you say you’re “not available,” you mean you are not able to because you are busy doing other things like listening to podcasts or reading your email or watching videos of cats on YouTube. You know, important things.
Martin says, “Please leave a message and I’ll call you back as soon as I can.” “Please leave a message” – please give me the information you want to give me, which should include, of course, your name and your telephone number. “And,” Martin says, “I’ll call you back as soon as I can.” “To call someone back” means to return their telephone call. They call you, then you call them. That’s “calling someone back.”
Martin is not satisfied. He doesn’t like his first try at recording his outgoing message. He says that he “gave it another shot.” “To give something another shot” (shot) means to try something again. “To give something a shot” means to try it. “To give something another shot” means to try it again, especially if you were not able to do it correctly or successfully the first time. Now we hear Martin’s second outgoing message:
“Hello, you’ve reached the voice mail for Martin Navra at McQ Corp. I’m in a meeting or away from my desk. Please leave a message and I’ll call you back as soon as I can. If your call is urgent, please contact Julia Mann at 555-434-3232. Thank you.”
The second message that Martin records is a little different. He says, “You’ve reached the voice mail for Martin Navra” instead of “You’ve reached Martin Navra.” This is more correct technically, because if you’re listening to a recording, you haven’t reached – that is, you haven’t successfully contacted – Martin Navra. You’ve only reached his voice mail. Martin continues, “I’m in a meeting or away from my desk.” This is a very common thing for people to say in their outgoing message. They’re giving you basically a reason, an excuse, for why they could not answer your phone call.
“I’m in a meeting,” meaning I’m meeting with other people or I’m away from my desk. “To be away from your desk” means not to be sitting at your desk so you can answer the phone. They’re saying to you that I’m not just sitting here playing video games and ignoring my phone; I’m actually not here. Well, that’s what they say, anyway.
Martin continues, “If your call is urgent, please contact Julia Mann.” Something that is “urgent” (urgent) is something you need to do right away, something that has to be done immediately. Martin is saying that if what you are calling me about needs to be acted on immediately, you should call this other person. Here, it’s Julia Mann. And then he gives Julia’s telephone number. Notice that the telephone number begins “555.”
“555” is often used in American movies and television shows when someone is giving their telephone number because there are no telephone numbers in the United States that begin with “555.” So, you know it’s not a real number when someone says that their phone number is “555.” If you come to the United States and you meet a beautiful woman at a bar, and she gives you her telephone number and it says “555,” it’s not really her telephone number. Sorry, dude.
Martin says that his second recording “seemed okay.” “But since I was leaving on vacation next week,” he says, “I needed to record a temporary outgoing message as well.” “Temporary” means for a short time. Martin has to record a special outgoing message for the time when he is going to be on vacation. He says, “This is what I came up with.” “To come up with” something means to invent something or to create something.
“Hello, you’ve reached the voice mail of Martin Navra at McQ Corp. I will be on vacation from March 3rd through March 10th. If you need to reach someone immediately, please call Julia Mann at 555-434-3232, or dial zero to reach reception. Otherwise, please leave a message and I’ll return your call when I return. Thank you.”
In this “vacation message,” Martin says, “I’m going to be on vacation from March 3rd through March 10th. He continues, “If you need to reach someone immediately . . .” As we mentioned earlier, “to reach” someone means to successfully contact someone – to actually talk to the person you are trying to talk to. Martin says that if you need to talk to someone right now, please call Julia Mann, and then he gives her phone number. “Or,” he says, “dial zero to reach reception.” “To dial” (dial) nowadays means to press a number on what’s called a “keypad” for the telephone.
This verb “to dial” comes from telephones as they existed many years ago, when I was growing up, that had actual round circles on them called “dials.” A “dial” in general is the front of a watch or a clock that has numbers on it. Well, in the old days telephones had dials, and you would move the dial around in a circle in order to call a telephone number. We’ve kept that verb “to dial” to mean the same thing, but now you don’t actually move your fingers around on a dial. You simply press a number and it produces an electronic tone.
Martin says in his outgoing message that “you can dial zero to reach reception.” “Reception” (reception) is usually the area where people are greeted in an office building. When you first come into an office, there’s often someone sitting at a desk who asks your name, and who you are there to see, and so forth. In this case, it would be the person who answers general phone calls for the company. If you dial zero, you will reach someone who works for the company who can then perhaps connect you with another person, or of whom you can ask questions of, in order to get the information you need.
We finish the story by Martin saying, “I was finally done. The good thing is, whenever I call to retrieve my voice mail messages, I can bypass my outgoing message.” “To retrieve” (retrieve) means to get something – often, to get something back that you used to have. We use this verb also when we are talking about getting your voice mail messages, hearing your voice mail messages.
Remember we talked about how phone companies record your message for you, and then you call them and you can get your message from their computer. You are “retrieving” your message. You are getting it back, if you will. “To bypass” (bypass) is a verb meaning to get to where you want to go without having to go to a certain place, by using a different route or path to get to where you want to go. In this case, Martin wants to get to his voice mail messages so he can bypass his own outgoing message. He doesn’t have to listen to it. He can take a different route to get to his message.
The word “bypass” is most commonly used when we’re talking about driving. It is a road or a freeway that goes around a big city so that you don’t have to go through the middle of the city. You can “bypass” the city; you can go around the city to get to where you want to go on the other side of the city. Martin ends by saying, “With any luck” – that is, if he is lucky – “I’ll never have to hear my own voice again – ever!”
Now let’s listen to the story, this time at a normal speed.
[start of story]
I hate the sound of my own voice. I always have. When I’m speaking to an audience, I always sound forced and unnatural. So when we had to set up our new voice mail system’s outgoing message, it took me a few tries to get it right.
“Hello, you’ve reached Martin Navra at McQ Corp. I’m not available to take your call right now. Please leave a message and I’ll call you back as soon as I can. Thank you for calling.”
No, that wasn’t quite right. I gave it another shot.
“Hello, you’ve reached the voice mail for Martin Navra at McQ Corp. I’m in a meeting or away from my desk. Please leave a message and I’ll call you back as soon as I can. If your call is urgent, please contact Julia Mann at 555-434-3232. Thank you.”
That seemed okay, but since I was leaving on vacation next week, I needed to record a temporary outgoing message as well. This is what I came up with.
“Hello, you’ve reached the voice mail of Martin Navra at McQ Corp. I will be on vacation from March 3rd through March 10th. If you need to reach someone immediately, please call Julia Mann at 555-434-3232, or dial “0” to reach reception. Otherwise, please leave a message and I’ll return your call when I return. Thank you.”
I was finally done. The good thing is, whenever I call to retrieve my voice mail messages, I can bypass my outgoing message. With any luck, I’ll never have to hear my own voice again – ever!
[end of story]
There’s nothing forced or unnatural about the English used in our dialogues. That’s because they’re written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
forced – straining to try to do something a certain way; not natural or relaxed
* Heather’s voice sounded forced when she sang the high notes in the song.
unnatural – not natural; contrived; changed in some way from the natural way
* Why do so many women like having unnatural nails that are blue, green, or some other bright color?
to set up – to establish or create; to get something ready to do something, especially for the first time
* How long did it take you to set up your TV and DVD player?
voice mail – a system for recording messages left by callers when one does not answer the phone
* If I don’t answer your call, please leave a voice mail message and I’ll try to call you back as soon as I can.
outgoing message – a recorded message that other callers hear when one does not answer one’s phone
* Samantha lives alone, but for safety she had a male friend record her outgoing message.
try – attempt; one effort to do something, especially one of many
* It might take a few tries before we figure out how to do this.
to call (someone) back – to return someone’s call; to call a person after he or she tried to call earlier and left a message
* Have they called you back about the job?
to give (something) another shot – to try again when one’s first attempt was unsuccessful
* Of course you fell down the first time you tried to ski. That’s normal. But you need to give it another shot.
away from – not in a particular place because one has gone somewhere else temporarily; not where one normally is
* Everyone needs some time away from the office.
urgent – very important and needing to be done as soon as possible; regarding a very important piece of business
* Please go to the emergency room only if you have an urgent need for healthcare.
to contact – to call, email, or write to someone; to be in communication with another person
* Users can contact our technical support 24 hours a day, seven days a week.
temporary – not permanent; for a short, defined period of time; not forever
* This is just a temporary place to live until we can buy a house.
to reach (someone) – to be in communication with someone, especially by phone
* These automated phone systems make it very difficult to reach a real person!
to dial – to press one or more numbers on a keypad for a telephone
* For sales, dial 5. For technical support, dial 6. For all other questions, please dial 0.
reception – the physical desk or functional area where people are greeted when they come into an office and/or when they call, so that they can be directed to the person they need to speak with
* Please check in at the reception desk and tell them you have a meeting with me.
to retrieve – to get something, especially to get back something that one used to have
* Your father went over to the neighbor’s house to retrieve the tools he lent them last week.
to bypass – to avoid something by going around it or taking an a different route
* Is there a way to bypass all this traffic?
Comprehension Questions
1. Who will hear the outgoing message?
a) People who are fixing the phone system
b) People who enter his office when he isn’t there
c) People who call him and the call is not answered
2. What will happen if callers dial “0”?
a) They’ll be transferred to the main office phone line.
b) They’ll be transferred to his cell phone.
c) They’ll be transferred to another person in his department.
Answers at bottom.
What Else Does It Mean?
forced
The word “forced,” in this podcast, means straining to try to do something a certain way, not natural or relaxed: “The room filled with forced laughter, because everyone felt that theyhad to laugh at the CEO’s jokes, even though they weren’t really funny.” The word “forced” also describes something one has to do, without wanting to do it or intending to do it ahead of time: “The plane’s engine caught on fire, so we had to make a forced landing.” The phrase “forced entry” describes a crime where one enters a building without permission by breaking a door or window: “The home didn’t show any signs of forced entry, but many items had been stolen.” Finally, the phrase “forced labor” refers to slavery, or the practice of making people work without payment: “Millions of African Americans suffered under the system of forced labor.”
away from
In this podcast, the phrase “away from” means not in a particular place because one has gone somewhere else temporarily: “A security guard should never be away from his post.” The phrase “far and away” is used to provide emphasis and means extremely, or more than anything else: “That was far and away the best meal I’ve had in Austin.” The phrase “right away” and “straight away” mean immediately, without any delay: “Please take these papers to Harold right away.” Finally, when talking about sports, an “away” game is the opposite of a home game, because an away game is played on the competitors’ field: “It’s harder to win away games, because we can’t hear our fans cheering.”
Culture Note
Business Phone Etiquette
When answering a business “line” (phone attached to a particular phone number), it’s important to leave a good “impression” (how one is perceived) on the caller. For example, when answering, it’s important to speak “clearly” (with speed and pronunciation that help people understand one’s words) while stating one’s name and company, such as “Good afternoon, Acme Insurance, this is Rebecca. How may I help you?”
If the caller’s request has to be “transferred to another line” (forwarded to another person’s phone), it’s important to clearly tell the caller why the call is being transferred and to whom. It’s also important to request the caller’s “permission” (approval to do something) to transfer the call, For example, “Our accounting department should be able to answer that question. May I transfer you to Shane, who handles our small business accounts?”
Sometimes a call has to be put “on hold” (set aside for a short period of time). Again, it’s important to request the caller’s permission. Sometimes people simply say, “Please hold” and put the call on hold right away, but that can be considered “rude” (impolite). Instead, it’s a good idea to ask, “May I put you on hold for a moment?” and then wait for the caller’s response.
Finally, if the caller needs to speak to someone who is not available, it’s a good idea to give the caller several options, such as: “Would you like me to give her a message, or would you like me to transfer you to her voice mail?”
Comprehension Answers
1 - c
2 - a