= 0975
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 975 – Making Food from Scratch.
This is English as a Second Language Podcast episode 975. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also like us on Facebook. Why not? Go to facebook.com/eslpod.
On this episode, we’re going to listen to a dialogue about cooking food without using any canned food or other ingredients that you would buy that have been already prepared for you. Let’s get started.
[start of dialogue]
Ann: I’m so excited to have the entire family coming for a visit. For our first family dinner next Friday, I’m making everything from scratch. I’m pulling out all the stops.
Walt: But have you ever made anything from scratch?
Ann: Sure I have, plenty of times.
Walt: If you say so, but our pantry is full of canned foods and jars, and nearly everything we’ve cooked in the past year has been premixed. Are you sure you’re up to cooking a dinner for 12 from scratch?
Ann: How hard could it be? I just need to make sure that the ingredients I buy are fresh, follow the recipes closely, add plenty of fresh herbs and spices, and multitask.
Walt: You mean do a juggling act. It’ll take a lot of work and organization to pull this off.
Ann: I’m up to the challenge. And I have a backup plan.
Walt: And that is?
Ann: Have you ever heard of the raw food movement?
[end of dialogue]
Ann begins our dialogue by saying to Walt, “I’m so excited to have the entire family coming for a visit. For our first family dinner next Friday, I’m making everything from scratch.” Ann is excited because her entire family is coming to visit her, and she wants to cook something for them for dinner. She wants to make it “from scratch.” That expression, “from scratch,” means you start with basic ingredients and make everything yourself. You don’t use anything in a can or anything that has been prepared that you bought in the store.
So, if you’re going to make vegetable soup, you make your own “stock,” which is the liquid for a soup, you prepare the vegetables, and so forth. Ann says, “I’m pulling out all the stops.” “To pull out all the stops” means to do something in the best way that you can, to do something fully – to do something that would require a lot of work, but would be the most you could possibly do. This term actually comes from organ playing. When you play an organ very loudly, you pull out all of the stops. The stops are parts of the organ that you can pull out in order to make the organ louder. Well, Ann is pulling out all the stops to make a big family dinner.
Walt says, “But have you ever made anything from scratch?” Walt doesn’t think Ann has ever prepared a meal from scratch. Ann, however, says, “Sure I have, plenty of times” – lots of times. Walt says, “If you say so.” That expression, “If you say so,” is used when you really don’t believe what the other person is telling you, but you don’t want to argue with them. Walt says, “Our pantry is full of canned foods and jars.” A “pantry” (pantry) is a small room, usually next to the kitchen, that is used to store food that does not have to be kept cold – that does not have to be refrigerated. A “pantry” usually has “dry goods,” like sugar and flour and salt – things you don’t have to put in a refrigerator.
A pantry would probably also have “canned food.” “Canned food” is food that comes in a metal container – usually made of metal, of tin. Canned foods are very popular in the United States for all sorts of things, including soups and vegetables and other kinds of food. Canned foods are very convenient because you can buy them and then put them in your pantry and use them many weeks, or even months, later. A “jar” (jar) is a glass bottle that has a top on it, which we call a “lid” (lid). “Jars” are also used for storing things – for putting things into, including food.
Walt says, “Nearly everything we’ve cooked in the past year” – in the last 12 months – “has been premixed.” “To mix” (mix) is to combine different things together, to put things together. “Premixed” would be food, in this case, that has already been prepared and put together so you don’t have to do it yourself. Walt says, “Are you sure you’re up to cooking a dinner for 12 from scratch?” “To be up to” something here means to be ready for something, to be prepared to do something, to have the energy and the knowledge to do something.
Usually we use the word “challenge” after this expression. “Are you up to the challenge?” “Challenge” is a difficult thing to do. “Up to” can also be used to mean simply doing something. If someone says, “What are you up to tonight?” he means “What are you doing tonight? What are your plans? What activities are you doing tonight?” “Up to” can also be used when someone is perhaps doing something wrong, even illegal. “I think my neighbor is up to something” – I think that there is something strange going on, maybe even criminal. I think that’s true. I really do wonder what my neighbor is up to sometimes. I don’t know. Strange smells. You know what I’m saying?
Ann says that she is up to cooking a dinner from scratch. She says, “How hard could it be?” That question, “How hard could it be?” is used to indicate that you don’t think it is very difficult. You don’t think it will be difficult to do this. “How hard could it be to find a beautiful woman in Los Angeles and ask her out on a date?” Well, it’s actually quite easy to find a woman. Getting her to go on the date – that’s a little more difficult.
Ann says, “I just need to make sure that the ingredients I buy are fresh.” “Fresh” (fresh) is an adjective used to describe food that has only recently been prepared or has only recently been taken from where it would normally be found. For example, a fish that is “fresh” is one that has been brought from the lake or the river or the ocean very recently. It’s not a fish that was caught four months ago and now they’re bringing it to the store. That would not be a fresh fish. If you want fresh fish, you often have to go to the river or the lake or the ocean to buy it, if you want it really fresh, right out of the water.
We can use this adjective also to describe foods that are prepared – for example, “fresh bread.” “Fresh bread” would be bread that was baked or cooked very recently – maybe this morning or an hour ago. “Ingredients” are the things you use to make food. So, “fresh ingredients” would be things that you use to prepare your food that are fresh. Ann says she also needs to “follow the recipes closely.” A “recipe” (recipe) is a list of instructions for cooking or preparing something.
“To follow something closely” means to do it very carefully, to do everything that it says. “Following a recipe closely” would mean doing everything the recipe says, in the order it says to do it. Ann also wants to make sure that she uses “plenty” – or a lot – “of fresh herbs and spices.” “Herbs and spices” are small parts of plants, often dried, that have a lot of flavor in them. We use herbs and spices to give more flavor to the food.
Ann also says she needs to “multitask” (multitask). “To multitask” is to do many things at the same time. Walt says, “You mean do a juggling act?” “To juggle” (juggle) is to throw a lot of things up into the air and keep them all in the air to prevent them from falling, from dropping to the floor. However, here when Walt says a “juggling act,” he’s referring to something that is very complex, something that will require doing a lot of things at the same time. The idea here is that this would be very difficult to do because juggling can be difficult to do.
Walt says, “It’ll take a lot of work and organization to pull this off.” “To pull something off” is a two-word phrasal verb meaning to be able to do something that is very difficult or that is very challenging. Ann says, however, that she is “up to the challenge.” She is able to do this difficult thing. “And,” she says, “I have a backup plan.” A “backup (backup) plan” is an alternative if what you’re doing now doesn’t work. It’s what we might also call “plan B.” When people say, “I need a plan B,” they mean they need a backup plan. They need a plan to follow if what they are planning on doing goes wrong. That would be their “plan A,” their original or first plan.
Walt asks what Ann’s backup plan is. Ann tells him, “Have you ever heard of the raw food movement?” “Raw” (raw) is the opposite of cooked. If you buy some tomatoes at the supermarket and you bring them home, they’re raw. They haven’t been cooked yet. In the last few years, it has become popular for some restaurants, and people in their homes, to not cook food – to eat the food raw by preparing it in special ways.
There are, according to some people, health benefits from this. I don’t know if that’s true. I do know that Ann is just making a joke here. She’s saying that her backup plan is not to cook the food at all and to serve it, or to give it to her guests, raw.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ann: I’m so excited to have the entire family coming for a visit. For our first family dinner next Friday, I’m making everything from scratch. I’m pulling out all the stops.
Walt: But have you ever made anything from scratch?
Ann: Sure I have, plenty of times.
Walt: If you say so, but our pantry is full of canned foods and jars, and nearly everything we’ve cooked in the past year has been premixed. Are you sure you’re up to cooking a dinner for 12 from scratch?
Ann: How hard could it be? I just need to make sure that the ingredients I buy are fresh, follow the recipes closely, add plenty of fresh herbs and spices, and multitask.
Walt: You mean do a juggling act. It’ll take a lot of work and organization to pull this off.
Ann: I’m up to the challenge. And I have a backup plan.
Walt: And that is?
Ann: Have you ever heard of the raw food movement?
[end of dialogue]
Our scriptwriter pulls out all the stops on every script she writes. We thank the wonderful Dr. Lucy Tse for her work. We also thank you for listening.
From Los Angeles, California, I’m Jeff McQuillan. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
from scratch – starting with basic ingredients, not using any prepackaged or pre-prepared foods
* Why would you make pancakes from scratch when it’s so much easier to make them from this mix?
to pull out all the stops – to do something in a big, elaborate way; to do something fully and take it to an extreme; to do something in the best way one can
* When they redecorated their living room, they pulled out all the stops, with new furniture, flooring, paint, windows, curtains, and light fixtures.
pantry – a small room next to a kitchen used to store food that does not have to be refrigerated (kept cold)
* The pantry has a lot of jams and jellies from the berries we picked last summer.
canned food – food that is already prepared and sold in sealed tin cans that preserve it for many years
* It’s a good idea to have canned food in case of an earthquake or a similar emergency, but make sure you have a can opener, too.
jar – a glass bottle with a round opening and a lid that screws onto it
* Could you pick up a jar of peanut butter at the store?
premixed – with the ingredients already measure and stirred together
* The flour, sugar, salt, and baking powder are already premixed, so you just have to add an egg and some milk and then pour everything into a baking pan.
up to – ready and prepared to do something; having the energy, skills, knowledge, and commitment needed to do something
* Are you sure you’re up to watching the neighbors’ three-year-old sons? They are a lot of work.
ingredient – a food used in combination with other foods to cook or bake something else to eat
* This ice cream has just four ingredients: cream, milk, sugar, and vanilla.
fresh – recently picked or recently prepared; not stored for a long period of time
* Fresh beef has a reddish color. It shouldn’t be brown like that.
recipe – instructions for cooking or baking something
* The recipe calls for two tablespoons of lemon juice, but I don’t have any. Do you think I can use lime juice instead?
closely – with a lot of attention to detail; carefully
* Listen closely, because he’s only going to explain it once.
herbs and spices – small parts of plants, often dried, that have a lot of flavor in small quantities.
* Oregano, basil, and rosemary are common herbs and spices in Italian cooking.
to multitask – to do multiple things at the same time
* The receptionist will need to answer phone calls, greet customers, distribute the mail, and do data entry, so we’ll need to hire someone who can multitask well.
a juggling act – a complex performance that requires handling many things at the same time, paying attention to everything at once
* Hannah’s life is a juggling act. She’s a full-time employee, a community volunteer, a part-time student, and a mother!
to pull this off – to be able to do something that is difficult or challenging
* We have to find a new place to live in just four days. Do you really think we’ll be able to pull this off?
challenge – an invitation or dare to do something that will be difficult, especially when it represents an opportunity to compete against other people or to show that one is better at doing something than others are
* Running a marathon will be a huge challenge, but Henrique is determined and training very hard for it.
backup plan – a plan B; an alternative; what one will do if one’s first plan does not work
* Kevin hopes his band will become an international success, but he’s getting a degree in engineering as a backup plan.
raw food movement – interest or effort to promote the eating of foods that are not cooked
* People involved in the raw food movement argue that our bodies can get more nutrients out of uncooked foods, but some doctors disagree.
Comprehension Questions
1. What does Ann mean when she says, “I’m making everything from scratch”?
a) She’s making everything from basic ingredients.
b) She’s trying new recipes that she’s never followed before.
c) She’s cooking things that people aren’t allergic to.
2. What would you expect to see in a recipe?
a) An list of items in the pantry.
b) A menu for a dinner party.
c) A list of ingredients.
Answers at bottom.
What Else Does It Mean?
from scratch
The phrase “from scratch,” in this podcast, means starting with basic ingredients, not using any prepackaged or pre-prepared foods: “Sheila made the pie filling from scratch, but she bought the crust at the store.” The phrase “from scratch” can also mean doing something from the beginning: “Yuko’s grandfather started this company from scratch.” The phrase “scratch paper” refers to a small piece of inexpensive paper, possibly with other writing on one side, used to write down notes: “Do you have a piece of scratch paper so I can write down your phone number?” Finally, a “scratch” can be a small cut on the skin: “His legs were covered in scratches from the blackberry bushes he walked through on his hike.”
fresh
In this podcast, the word “fresh” means recently picked or recently prepared, not stored for a long period of time: “If the fish fresh, or has it been frozen?” Or, “Fresh tomatoes from the garden taste so much better than tomatoes that were picked a few days ago.” The phrase “fresh air” refers to clean-smelling air in the outdoors: “Let’s go for a walk and get some fresh air.” The phrase “fresh water” refers to water that is not salt water: “This fresh water looks clean, but we should still use a filter if we plan to drink it just to be safe.” Finally, the phrase “a fresh start” describes beginning something again in a new way after the first way was unsuccessful: “They spent some time apart, but now they’re ready to live together again as a fresh start for their marriage.”
Culture Note
Recent Food Movements
The United States has “witnessed” (seen) many food movements recently. Certain groups of people change the way they eat, usually for health or for “ethical” (dealing with what is right and wrong) reasons, such as the “humane” (fair and just) treatment of animals.
People who are involved in the raw food movement believe that humans should not eat any foods that have been cooked. All their foods are “raw” (not cooked), so they are mostly fruits and vegetables, and they are served “at room temperature” (without being heated or cooled).
The “slow food movement” offers an “alternative” (another option that is different) to fast food. It emphasizes the importance of food for good health, and the importance of slow meals for building relationships. The movement encourages people to plan their meals carefully, take time to cook, follow local “culinary” (related to cooking) traditions, and know where their food comes from.
The “local food market” encourages people to eat food that is grown and produced within a short distance of where they live. Most “advocates” (people who believe something is good and want others to agree) of the slow food movement focus on how local food is better for the environment, because it does not have to be transported very far. People also emphasize the economic benefits of supporting local farmers and keeping money within the local community.
Finally, the “organic food movement,” which is probably the most “mainstream” (adopted or supported by many people, not just a small group) movement, focuses on eating only “organic food” that has been grown without the use of chemicals. The people who advocate for organic food believe that it is healthier for our bodies and better for the planet.
Comprehension Answers
1 – a; 2 – c