= 0989
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 989 – Dealing with a Mass Transit Strike.
This is English as a Second Language Podcast episode 989. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download a Learning Guide by becoming a member of ESL Podcast. You can also like us on Facebook at facebook.com/eslpod.
This episode is a dialogue about a strike – when workers decide to stop working in order to negotiate for more money or more benefits at their job. We’re dealing today with a mass transit strike. That involves buses and subways and other means of transportation that people use in the city. Let’s get started.
[start of dialogue]
Marge: Where have you been? You should have been home over two hours ago!
Homer: I’ve been trying to get home. Haven’t you been watching the news? The Transportation Workers Union has voted to strike. There was a mass walkout at 4:30 p.m. today.
Marge: You’re kidding! I didn’t know anything about it. They walked off the job right before the afternoon commute?
Homer: Yeah, I think it was calculated to make the biggest impact so that the powers that be will sit up and take notice.
Marge: You mean the walkout has halted services on all public transportation – all buses, trains, and subways?
Homer: Yes, that’s right. Everything is at a standstill. There are a lot of disgruntled commuters out there.
Marge: When will services be restored?
Homer: I have no idea. I imagine things won’t get back to normal before tomorrow morning’s commute.
Marge: So what are you going to do?
Homer: I might have to stay home from work. I’m stranded with no mass transit services.
Marge: Oh, that’s a shame.
Homer: Isn’t it, though?
[end of dialogue]
Marge begins our dialogue by saying to Homer, “Where have you been? You should have been home over two hours ago.” Homer is two hours late. Homer says, “I’ve been trying to get home. Haven’t you been watching the news? The Transportation Workers Union has voted to strike. There was a mass walkout at 4:30 p.m. today.” Homer says he has been trying to get home, but he has been unable to because the Transportation Workers Union has voted to strike.
A “union” (union) is an organization created to protect the rights of workers so that the employers don’t do anything unfair to the workers. It’s a way of giving the workers more power in negotiating or trying to get better pay and better work conditions. Many countries have unions as part of the government. So, the people who work for the government are part of a union, and that seems to be what is happening here. Homer is talking about the Transportation Workers Union – the people who work on the buses and the subways and trains.
He says, “The union has voted to strike” (strike). “To strike” is to stop working temporarily because you’re not happy with the situation at your job. This is something that unions are typically allowed to do, even if they work for the government. Homer says, “There was a mass walkout at 4:30 p.m. today.” A “walkout” is when, in this case, the workers all leave their job as a protest. You might also have a walkout at a university. The students may all leave their classes because they’re not happy with something the university is doing. I wish my students would’ve had more walkouts when I was a university professor. I could have gone home early and not had to work.
Well, these are workers who are striking, and the mass walkout – the large-scale walkout – involves all of these different workers involved in the transportation system. The adjective “mass” (mass) refers to a large group of people, or a lot of people. Marge says, “You’re kidding!” – you’re joking. “I didn’t know anything about it. They walked off the job right before the afternoon commute?” Marge asks. Marge is referring to the transportation workers. She’s asking Homer, somewhat in disbelief perhaps, if these workers walked off the job right before the afternoon commute.
“To walk off your job” means to leave your job suddenly when you are supposed to continue working. “Right before” means immediately before or just before. The “commute” (commute) here refers to the period of time when most people are either going to work in the morning or coming home from work in the afternoon. Here in Los Angeles, the afternoon commute begins around 4:30, 5 o’clock in the afternoon and continues until about 7 or 7:30 at night. Those are times when most people are coming home from work.
Homer says, “Yeah, I think it” – meaning the strike – “was calculated to make the biggest impact so that the powers that be will sit up and take notice.” “Calculate” (calculate) usually means to consider something very carefully. When we say something was “calculated to” do something, we mean it was planned to do something – that was the intention. This strike was calculated to make the biggest or largest “impact” (impact). An “impact” is an effect. It’s a result. Nowadays, people also use “impact” as a verb. “To impact” something means to have an effect on something. It’s a relatively new use and not one that I particularly like.
In our story, Homer is talking about the impact made by this transportation strike “so that the powers that be will sit up and take notice.” The expression “the powers that be” refers to people in authority, the people who are making decisions, the people who have a lot of power and influence. The transportation workers are trying to make a statement to – they’re trying to communicate a message to – the powers that be, so that these people in authority “will sit up and take notice.” The expression “to sit up and take notice” means to pay attention to something, to focus on something. “To sit up,” as a phrasal verb, means to make sure that you are sitting completely straight up in your chair. “To take notice” means to pay attention or to focus on something.
Marge says, “You mean the walkout has halted services on all public transportation – all buses, trains and subways?” “To halt” (halt) means to make something stop. The strike has stopped services on all of the various modes of public transportation: buses, trains and subways. Homer says, “Yes, that’s right” -– that’s correct. “Everything is at a standstill.” “To be at a standstill” (standstill) means to be without any movement, to not be moving – the trains, buses, and subways are not moving.
“There are a lot of disgruntled commuters out there,” Homer says. “To be disgruntled” (disgruntled) means to be unhappy, to be dissatisfied. “Commuters” are people who commute, who go back and forth from work. Marge says, “When will services be restored?” The expression “to be restored” means to be returned to normal. If something is broken, it needs to be fixed. In this case, it means for the transportation workers to return to their jobs. Homer says, “I have no idea” – I don’t know. “I imagine things won’t get back to normal before tomorrow morning’s commute.” He’s saying that he doesn’t think the transportation workers will start working again before tomorrow morning.
Marge says, “So what are you going to do?” Homer says, “I might have to stay home from work. I’m stranded with no mass transit services.” “To be stranded” (stranded) means to be left somewhere without any way of getting back to where you want to go. So, if you fly to New York, and there’s a snowstorm, and you can’t leave the city because the planes aren’t flying, you are stranded in New York. You want to leave, but you can’t because there’s no way for you to leave.
Homer is talking about being stranded without mass transit services. “Mass transit” refers to the systems of transportation that move or transport a lot of people – buses, subways, and trains are the most common examples of mass transit in the city. Some cities have excellent mass transit services, such as New York City. Some cities, such as Los Angeles, have absolutely terrible mass transit services, public transportation services. You really need a car in this city if you are going to stay here for any amount of time.
Marge says, “Oh, that’s a shame.” She’s saying it’s unfortunate. “That’s a shame” (shame). It’s a phrase meaning, “That’s too bad.” But Homer, we suspect, doesn’t really think it’s bad news. He says, “Isn’t it, though?” meaning yes, it is. But of course, it isn’t really for Homer, because now he doesn’t have to go to work tomorrow.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Marge: Where have you been? You should have been home over two hours ago!
Homer: I’ve been trying to get home. Haven’t you been watching the news? The Transportation Workers Union has voted to strike. There was a mass walkout at 4:30 p.m. today.
Marge: You’re kidding! I didn’t know anything about it. They walked off the job right before the afternoon commute?
Homer: Yeah, I think it was calculated to make the biggest impact so that the powers that be will sit up and take notice.
Marge: You mean the walkout has halted services on all public transportation – all buses, trains, and subways?
Homer: Yes, that’s right. Everything is at a standstill. There are a lot of disgruntled commuters out there.
Marge: When will services be restored?
Homer: I have no idea. I imagine things won’t get back to normal before tomorrow morning’s commute.
Marge: So what are you going to do?
Homer: I might have to stay home from work. I’m stranded with no mass transit services.
Marge: Oh, that’s a shame.
Homer: Isn’t it, though?
[end of dialogue]
Our scriptwriter has not gone on strike yet, thankfully. And we do thank our scriptwriter, Dr. Lucy Tse, for her wonderful work.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
union – an organization created to protect the rights of workers, who are its members
* The teachers union is demanding higher salaries and a limit on class size.
to strike – for a group of people to temporarily stop working because they want to be treated better or have greater benefits
* If the airline employees strike, it will create a lot of problems for travelers.
mass – involving many people; including all people
* The mass movement of so many people makes it very difficult to drive in the city before and after important football games.
walkout – an event where all workers, students, meeting participants, or audience members leave to protest (show their disagreement with) something
* The students staged a walkout to show their disagreement with what the guest speaker was saying.
to walk off the job – to leave one’s job; to abruptly stop working when one should continue to work, especially to protect something
* If you walk off the job, don’t bother coming back tomorrow, because you’re fired.
commute – the period of time when most people drive from home to work, or from work to home
* During the morning commute, local radio stations have a lot of traffic updates to let people know where traffic is slow.
to calculate – to consider something very carefully and make a strategic decision that will provide some benefit to oneself
* Cigarette companies carefully calculated the advantages of marketing to young people, since getting them to smoke early will make them customers for life.
impact – affect; result; outcome
* Which invention has had the greatest impact on daily life: the automobile or the cell phone?
the powers that be – decision-makers; authorities; people with a lot of power and influence
* The powers that be refuse to tighten gun laws, even though most voters want to see the laws changed.
to sit up and take notice – to pay attention to something; to focus one’s attention and interest on something
* Mariah is normally so quiet, but when she spoke up in class and shared her opinion, everyone sat up and took notice.
to halt – to make something stop
* The police officer held up his hand to halt traffic in one direction.
standstill – without any movement; stillness
* When the space shuttle exploded, everyone stood at a standstill, unable to believe what they had seen.
disgruntled – unhappy, dissatisfied, and discontent
* This department is known for having disgruntled employees who don’t care about providing good customer service.
to be restored – to be fixed and returned to normal
* The power company apologized for the power outage and promises that electricity will be restored as soon as possible.
to be stranded – to be left somewhere without any way to leave that place; to be abandoned without a way to return
* If you were stranded on a deserted island and could have only one book, which book would it be, and why?
mass transit – public transportation; transportation services designed to move many people through a city and/or its surrounding area
* The mass transit system uses a combination of busses and light rail to move hundreds of thousands of people each year.
that’s a shame – that’s too bad; a phrase used to show that one feels bad about something or thinks it’s a pity
* A: Did you hear that Bryan’s new puppy ran away?
B: That’s a shame.
Comprehension Questions
1. Why did Laurent get home so late?
a) Because he wasn’t able to use public transportation.
b) Because he didn’t have enough money to pay for a ticket.
c) Because he got lost.
2. What does Laurent mean when he says, “Everything is at a standstill”?
a) No busses or trains are moving.
b) Nobody is talking about what’s happening.
c) People are very angry.
Answers at bottom.
What Else Does It Mean?
mass
The word “mass,” in this podcast, means involving many or all people: “The printing press made mass communication possible for the first time in history.” The phrase “the masses” refers to the general public, or all ordinary people who don’t have much power or influence: “What politicians say to the masses isn’t necessarily the same as what they say behind closed doors.” In the Catholic church, “mass” is the main ceremony for worshipping God: “Do you attend mass every Sunday?” The word “mass” can also refer to a large quantity of something: “The smart meters send a mass of data to the electric company, and it’s our job to analyze everything to draw meaningful conclusions.” Finally, in science, “mass” refers to the amount of material in something: “After the sun, which object in our solar system has the greatest mass?”
to be restored
In this podcast, the phrase “to be restored” means to be fixed and returned to normal: “The train derailed, but there were no injuries and the mechanics expect service to be restored within a few hours.” The verb “to restore” means to return something to its earlier condition: “Do you think these artifacts can be restored for display in the museum?” The verb “to restore” also means to bring back a positive feeling for people: “The experience restored Jacques’ belief in the existence of aliens.” Finally, the phrase “to restore (someone) to power” means to put a political leader back into a position of power after he or she lost it: “The rebels had power for a few months, but then the country’s former president was restored to power.”
Culture Note
Transit Strikes
Transit strikes are very “disruptive” (creating problems and interrupting people’s routines) in big cities where a large number of people depend on public transportation for their commute and daily activities. But they can also be very “effective” (able to get something done) “bargaining tools” (things people use to win in a negotiation) for transit workers.
Some of the biggest strikes in U.S. history have “occurred” (happened) in New York City. The 1966 New York City transit strike ended all service on the “subway” (underground trains) and busses, which affected millions of commuters. The 1980 New York City transit strike occurred when 34,000 union members refused to work, “halting” (stopping) all subways and busses for 10 days. Economists “estimate” (guess) that 15-20% of employees were not able to go to work during that time, and companies lost about $100 million per day as a result. And the 2005 New York City transit strike shut down service for two days.
Some transit strikes are “prompted” (caused; started) by social issues. In 1944, white transit workers in Philadelphia, Pennsylvania refused to work because they did not want to let black employees have “non-menial” (skilled; important) jobs within the transit company. Transportation was disrupted, but the city remained “calm” (not panicked), even though the military was sent to take over the Philadelphia Transportation Company during that time.
A few strikes are “longer-lasting” (taking a longer time). In Atlanta, Georgia, many people had been killed by taxis and “trolleys” (vehicles that are like busses, but run on rails). To make the city safer, the city began requiring that all taxi drivers and trolley drivers have a “permit” (official permission) to drive. The union disliked the new law and started a strike, which lasted from May 18 to November 16, 1950.
Comprehension Answers
1 - a
2 - a