
= Kidney failure (也叫 renal failure)  肾衰竭(肾功能衰竭)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css


'''

== A quirk in the law means that America’s kidney shortage costs taxpayers

主 Mr Glazer’s goal — to ensure that 主 all patients reliant (a.)依赖性的；依靠的 on blood-filtering 输血 dialysis (n.)渗析；透析（尤指将废物从肾病病人的血液中分离出来） machines, because of failing kidneys, 谓 would be covered by a then-newfangled (a.)新奇怪异的；时髦复杂的 programme called Medicare （美国） 国家老年人医疗保险制度, 主 the government health-insurance scheme for the elderly, regardless of age — 谓 soon became law.


[.my1]
.案例
====
.Kidney failure / renal failure
_Kidney failure_, also called _renal failure_, is when your kidneys no longer work (v.) properly. Your kidneys' main job is to clean your blood and make urine (wee 小便，排尿；尿). When the kidneys do not work properly, waste and fluid *builds up* in your body. +
"肾衰竭"，也称为"肾功能衰竭"，是指您的肾脏不再正常工作。肾脏的主要工作是净化血液并产生尿液（尿）。当肾脏不能正常工作时，废物和液体就会在体内积聚。 +

肾衰竭的定义, 通常是**依照"肾小球滤过率"（GFR）决定，亦即肾脏中"肾小球"的"滤过效率"。**可借由尿量增减，**血液中废物（如"肌酸酐"和"尿素"，正常状况下会随尿液排出）的含量来侦测。**血尿和蛋白尿也可能是"肾衰竭"的现象之一。
====


Dialysis (n.)渗析；透析（尤指将废物从肾病病人的血液中分离出来） is expensive: a machine must *filter out* toxins 毒素 and excess fluids from the blood, often for several hours a day and several times per week. It is a life-or-death (a.)生死攸关的 treatment. Still, two-thirds of patients with ESRD  终末期肾病 die (v.) within five years. A year of treatment in a specialised 专业化的; 专门的 centre costs (v.) $91,000.

[.my2]
格雷泽的目标是, 确保所有因肾脏衰竭而依赖血液过滤透析机的患者, 都能得到医疗保险的覆盖. 这在当时还是一项新奇的计划，即针对老年人的政府健康保险计划，无论他们的年龄 —— 格雷泽的这个目标, 很快就成为了法律。

但透析是昂贵的:机器必须过滤掉血液中的毒素和多余的液体，通常是每天几个小时，每周几次。这是一种生死攸关的治疗方法。然而，三分之二的ESRD患者, 还是会在五年内死亡。在专业中心, 一年的治疗费用为91000美元。

[.my1]
.标题
====
.newfangled
/ˌnuːˈfæŋɡld/ (a.)used to describe sth that has recently been invented or introduced, but that you do not like because it is not what you are used to, or is too complicated 新奇怪异的；时髦复杂的 ( disapproving)
⇒ new,新的，fang,牙齿，咬。引申词义咬住最新的，与时俱进的，新奇时髦的。

.ESRD  :
终末期肾病 end-stage renal disease


====


主 Diabetes 糖尿病 and high blood pressure, which have been rising, 系 are precursors (n.)前兆;先于某人[某事物]而导致或影响其发展的人或事物) of chronic kidney disease. +
For many patients /a kidney transplant is a much better option than several years of dialysis (n.)(肾的)透析 before death  — life expectancy is much longer, and that life is of higher quality.

It also saves money for the taxpayer, notes Mario Macis of Johns Hopkins University. “The math is such that /every kidney transplant generates (v.)  _savings (n.)节省 for Medicare_ of about $150,000,” says Mr Macis. +
The problem is that /there are almost 100,000 people on the waiting list, and the typical waiting time *is* more than four years, meaning /thousands die before their turn.

Incentivising (v.)激励(某人做某事);以奖励推广(某事) organ donations is morally fraught (a.)充满 (问题或风险) 的;令人担忧的.


[.my2]
不断上升的糖尿病和高血压, 是慢性肾病的前兆。 +
对许多患者来说，肾脏移植, 是比死前几年透析更好的选择 ——预期寿命会更长，生活质量更高。约翰霍普金斯大学的Mario Macis指出，这也为纳税人省了钱。Macis先生说:“从数学上讲，每一例肾脏移植, 都能为医疗保险节省大约15万美元。” +
问题是, 有将近10万人在等待的名单上，通常的等待时间, 超过四年，这意味着, 成千上万的人在轮到他们之前, 就死了。鼓励器官捐献, 在道德上令人担忧。






'''


== <pure> A quirk in the law means that America’s kidney shortage costs taxpayers



Mr Glazer’s goal — to ensure that all patients reliant on blood-filtering dialysis machines, because of failing kidneys, would be covered by a then-newfangled programme called Medicare, the government health-insurance scheme for the elderly, regardless of age — soon became law.

Dialysis is expensive: a machine must filter out toxins and excess fluids from the blood, often for several hours a day and several times per week. It is a life-or-death treatment. Still, two-thirds of patients with ESRD die within five years. A year of treatment in a specialised centre costs $91,000.


Diabetes and high blood pressure, which have been rising,  are precursors of chronic kidney disease.

For many patients a kidney transplant is a much better option than several years of dialysis before death — life expectancy is much longer, and that life is of higher quality. It also saves money for the taxpayer, notes Mario Macis of Johns Hopkins University. “The math is such that every kidney transplant generates savings for Medicare of about $150,000,” says Mr Macis.


The problem is that there are almost 100,000 people on the waiting list, and the typical waiting time is more than four years, meaning thousands die before their turn. Incentivising organ donations is morally fraught.

'''
