
= 锻炼能延长预期寿命
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css


'''

== 延年益寿的好办法


A little exercise each week can lead to big gains 获益 in life expectancy 预期寿命. And that's true *regardless of* 不论 your current weight, according to a new review study that included more than 650,000 people.

The World Health Organization recommends (V.)建议 two-and-a-half to five hours of brisk 轻快的 walking per week, or less time spent (v.) at a more vigorous 剧烈的 activity. People who got the full recommended 被推荐的 amount of exercise saw 看到 an average 3.4-year gain in life expectancy. People who got half as much 只有一半,一半那么多 exercise /still lived an average 1.8 years longer. The findings are in the journal PLoS Medicine (n.)医学.

In fact, exercise was a bigger factor *than* body weight in many cases. People who were normal weight but were inactive /actually lived an average of 3.1 fewer years *than* obese 过分肥胖的,臃肿的 people who kept up 保持 high levels of activity.


[.my2]
====
每周坚持锻炼一小会，寿命会大大延长。一项新的、调查对象超过65万人次的回顾性研究表明：#不论你目前的体重如何，坚持锻炼就会延长寿命。# +
世界卫生组织建议人们每周快走2.5至5个小时，或减少更剧烈的运动时间。那些完全按照建议行动的人平均寿命增加了3.4年。运动量只有建议一半的人平均寿命增加了1.8年。这项研究发表在《公共科学图书馆医学》期刊上。 +
实际上在许多情况下，##锻炼是比体重更重要的因素。##相比体型肥胖但活动量持续偏高的人，体重正常但不经常活动的人的平均寿命要短3.1年。
====

[.my1]
.标题
====
.PLoS
the Public Library of Science 美国科学公共图书馆
====


'''

== <pure> 延年益寿的好办法

A little exercise each week can lead to big gains in life expectancy. And that's true regardless of your current weight, according to a new review study that included more than 650,000 people.

The World Health Organization recommends two-and-a-half to five hours of brisk walking per week, or less time spent at a more vigorous activity. People who got the full recommended amount of exercise saw an average 3.4-year gain in life expectancy. People who got half as much exercise still lived an average 1.8 years longer. The findings are in the journal PLoS Medicine.

In fact, exercise was a bigger factor than body weight in many cases. People who were normal weight but were inactive actually lived an average of 3.1 fewer years than obese people who kept up high levels of activity.


'''
