= 1174
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,174 – Describing Video Quality.
I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our special courses in Business and Daily English. In addition to these wonderful podcast episodes, you can download some special courses to improve your English even faster.
This episode is a dialogue between Amelia and Victor about how we describe the quality of video, such as what you watch on television or perhaps on your computer. Let’s get started.
[start of dialogue]
Amelia: I wish we had hired a professional videographer to film it instead of asking your friend Lenny to do it.
Victor: This video isn’t so bad. The production quality isn’t the best, but he did a pretty good job.
Amelia: It’s not bad if you like your video out of focus. There are no transitions between scenes and the lighting is terrible. At best, it looks like a rough cut.
Victor: It is a little rough, I admit.
Amelia: There are problems with the audio, too. There are sections of dead air when the audio cuts out. And when there is audio, the volume isn’t uniform.
Victor: That’s true, too, I guess . . .
Amelia: And the handheld camera footage is so shaky that I feel ill watching it.
Victor: Lenny was just having a good time, getting into the spirit of it.
Amelia: Is that why he got close-up shots of all of the pretty women and none of the other guests?
Victor: Well, you know Lenny. He’ll do better next time.
Amelia: Next time?! How many times do you plan to get married?
[end of dialogue]
Amelia begins our dialogue by saying, “I wish we had hired a professional videographer to film it instead of asking your friend Lenny to do it.” Amelia mentions a “professional videographer” (videographer). A videographer is a person whose job it is to make movies of certain special events – to film special events such as birthdays, but more typically something such as a wedding, which is what we’re talking about in this dialogue.
Amelia and Victor asked Victor’s friend Lenny to film their wedding instead of getting someone who was a professional – someone who knew what he was doing, basically. Notice, “videographer” is like the word “photographer.” A photographer is someone who takes photos, what we would now call “stills” or “still photos.” A videographer is someone who makes or films video.
Victor says, “This video isn’t so bad,” meaning it’s not as bad as Amelia says it is. “The production quality isn’t the best, but he did a pretty good job.” “Production quality” refers to how professional a video looks, whether it looks like it was done by someone who knew what he was doing. Victor thinks his friend Lenny did a pretty good job, which means not the best job, but not a terrible job either.
Amelia doesn’t agree. She says, “It’s not bad if you like your video out of focus.” “Out of focus” means the same as “blurry” (blurry). Something that is “blurry” or “out of focus” is something that you can’t see clearly because the lens was not adjusted properly – the part of the camera that is responsible for making sure that the image is clear. The video is “out of focus.”
Amelia adds, “There are no transitions between scenes and the lighting is terrible.” A “scene” (scene) in a video is one part or section of a video that is about the same topic or that is showing the same area or people. A “transition” (transition) in a video is how you move or change from one scene to another. Sometimes in videos, the video will seem to move from right to left or top to bottom, or sometimes it will seem as though one scene magically fades away or goes away slowly and another one comes in slowly. These are called “transitions.”
Amelia says that their video doesn’t have any transitions. In addition, the “lighting” (lighting) is terrible, meaning that you can’t see properly. You can’t see things because there isn’t enough light or perhaps there’s too much light. “At best,” Amelia says,” it looks like a rough cut. The term “rough cut” (cut) refers to the first draft or the first attempt at editing a video.
If someone makes a video of, say, a wedding, he may sit down at his computer and put different parts of the wedding footage, or the things that he filmed, together, but it isn’t perfect yet. It’s only his first attempt to try to put the different parts of the wedding video together so that it looks good. That first attempt would be a “rough cut.” The opposite of a “rough cut” would be a “final cut.” This is when you’re all done – when you finish doing all the editing on the video.
Victor says, “It is a little rough, I admit.” “Rough” (rough) here means not perfect, still something that you’re working on. Amelia says, “There are problems with the audio, too.” The “audio” also has problems. The audio is the sound, of course, of the video. “There are sections of dead air when the audio cuts out.” “Dead air” (air) is when there is no sound, either on a radio or on a television program or in a video. This is when there is no sound, usually by accident. There should be sound but there isn’t any.
To say the audio “cuts out” means that it stops suddenly. You are listening to some audio and then suddenly . . . and then you don’t know what happened. That’s what we mean by the audio “cutting out.” “To cut out” can also be used in other circumstances meaning simply to stop something. “I’m going to cut out pizza and hot dogs from my diet.” I’m going to stop eating them completely.
Amelia says, “And when there is audio, the volume isn’t uniform.” The “volume” (volume) is how loud something is. “To be uniform” (uniform) here means to be constant or the same. If the volume isn’t uniform, sometimes it’s really loud and sometimes it’s what we would call really “soft.” You can barely hear it. Victor says, “That’s true, too, I guess.”
Amelia isn’t finished with her problems, her complaints. “And the handheld camera footage is so shaky that I feel ill watching it.” “Handheld” (handheld) means, of course, that you are holding something in your hand, such as a camera. “Footage” (footage) refers to part of a recording, part of the video. So, “handheld camera footage” would be part of the video that the person who was the videographer filmed not by using a special instrument called a “tripod” to keep the camera still and steady, but rather by using his hand and walking around with the video camera in his hand.
When you use a handheld camera, sometimes the footage is “shaky” (shaky). “Shaky” means that it’s not steady. It looks like the camera is moving back and forth all the time, and so it’s hard to watch the video because everything keeps moving up and down and from side to side. Lenny, according to Victor, “was just having a good time, getting into the spirit of it.” “To get into the spirit” (spirit) of something means to get involved or interested in something in such a way that you are excited about it.
Amelia says, “Is that why he got close-up shots of all the pretty women and none of the other guests?” A “close-up shot” (shot) is when you bring the camera very close to someone’s, usually, face so that you can see them very, what we would say, “close-up” – very near. The term “close-up” used as a noun refers to when the camera is right next to a person’s face. You can see the face very clearly. Apparently Lenny has a close-up of all the pretty women at the wedding and nobody else.
Victor says, “Well, you know Lenny. He’ll do better next time.” Amelia says, “Next time?! How many times do you plan to get married?
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Amelia: I wish we had hired a professional videographer to film it instead of asking your friend Lenny to do it.
Victor: This video isn’t so bad. The production quality isn’t the best, but he did a pretty good job.
Amelia: It’s not bad if you like your video out of focus. There are no transitions between scenes and the lighting is terrible. At best, it looks like a rough cut.
Victor: It is a little rough, I admit.
Amelia: There are problems with the audio, too. There are sections of dead air when the audio cuts out. And when there is audio, the volume isn’t uniform.
Victor: That’s true, too, I guess . . .
Amelia: And the handheld camera footage is so shaky that I feel ill watching it.
Victor: Lenny was just having a good time, getting into the spirit of it.
Amelia: Is that why he got close-up shots of all of the pretty women and none of the other guests?
Victor: Well, you know Lenny. He’ll do better next time.
Amelia: Next time?! How many times do you plan to get married?
[end of dialogue]
The quality of our scripts is uniformly great, thanks to the wonderful scriptwriter Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
videographer – a person whose job is to film events and make videos of them
* The user conference had a videographer who filmed the participants as they spoke about their experience using the software.
production quality – a measure of how good, professional, and polished a video appears to be
* With modern video editing software, almost anyone can achieve good production quality of home videos within just a few hours.
out of focus – blurry; with imprecise lines and an unclear image, caused by a lens that is not set correctly
* This medicine might make your eyes seem out of focus for a few hours, but the problem should go away soon.
rough cut – a first draft of video editing, enough to present a basic idea of what the video will be like, but without careful transitions or polish
* This is just a rough cut of our ideas for the commercial. If you like what you see, we’ll continue working on it and present a final copy by the end of next week.
transition – the way one thing blends into the next or is transformed into something new
* Words such as “however” and “moreover” help a document flow better by serving as transitions between paragraphs.
scene – all the acting or recording performed in a particular place and at a particular time
* In the opening scene, viewers see a gorgeous view of Central Park with the main characters sitting on a park bench having a conversation.
lighting – the way that lights illuminate people and objects, making them attractive and easy to see in a recording or performance
* The photographer asked Hannah to move closer to the window for better lighting.
audio – related to what one hears, not to what one sees; a recording
* Can you make a transcript of this audio file?
dead air – a part of a video with no sound, produced accidentally and viewed as a problem
* The video camera didn’t capture all the audio. Let’s add some music so we don’t have dead air in those sections.
to cut out – to repeatedly stop or disappear for short periods of time
* It’s hard to talk on a cell phone while driving in the mountains, because the signal cuts out.
volume – a measure of how loud something is, usually a recording or broadcast
* We can’t hear you from the back of the auditorium. Could you please turn up the volume for your microphone?
uniform – the same; constant; unchanging
* If you want that sweater to have uniform color, make sure all the yarn you buy was dyed at the same time.
handheld camera – a camera that is held in one’s hands and is moved as one moves one’s body, not placed on a tripod (a stand with three legs) or a wheeled device
* How do you hold so still while operating a handheld camera?
footage – recording; the images and sounds obtained while making a video
* We have more than three hours of footage from the kids’ soccer championships.
shaky – with many small, uncontrollable movements
* When it’s too cold in the office, everyone starts shivering and their hands are too shaky to write or type easily.
to get into the spirit – to become interested and involved in something; to become excited about something
* At first, people were too shy to sing at the karaoke bar, but as the night progressed, they started to get into the spirit of it and volunteered to sing on stage.
close-up shot – an image recorded at a very short distance from the object or person being photographed or filmed.
Comprehension Questions
1. What does Victor mean when he says, Lenny was just “getting into the spirit of it”?
a) Lenny wasn’t trying very hard.
b) Lenny was doing the work as a favor.
c) Lenny was becoming excited and involved in the events.
2. According to Amelia, what is wrong with the sound?
a) It’s too loud.
b) It’s too quiet.
c) It’s too inconsistent.
Answers at bottom.
What Else Does It Mean?
cut
The phrase “a rough cut,” in this podcast, means a first draft of video editing, enough to present a basic idea of what the video will be like, but without careful transitions or polish: “This is just a rough cut to see what everything looks like on the screen.” Also in this podcast, the phrase “to cut out” means to repeatedly stop or disappear for short periods of time: “What did you say? The phone cut out for a moment.” The phrase “to cut back” means to reduce, or to begin to use less of something: “If we cut back on eating out, we should be able to save some money to buy a new car.” Finally, the old-fashioned phrase “to cut a rug” means to dance: “Ooh, that’s one of my favorite old songs. Do you want to cut a rug with me?”
uniform
In this podcast, the word “uniform” means the same, constant, and unchanging: “Our policies have to be uniform across all offices.” Or, “These workers are responsible for sorting eggs so that a carton is filled with eggs of uniform size.” The word “uniform” also refers to clothing worn by all people who have a particular job in a particular organization: “You can identify employees of the car rental company by their uniform. They all wear an orange collared shirt and brown pants.” Or, “Do you think public schools should require school uniforms?” Finally, the word “uniformity” means conformity, or the idea that everything or everyone is the same: “Many teenagers rebel against uniformity by dying their hair or wearing unusual clothes.”
Culture Note
Wedding Videography
Wedding “videography” (the process of filming and producing or creating a finished video of an event) is popular, because most “brides and grooms” (the men and women who get married) want to have an easy way to remember their special day. Over time, wedding videography has become “increasingly” (more and more) “complex” (complicated and involved; not simple).
There are five common styles of Wedding videography. The first is a “journalistic” style where the final product is similar to a “documentary” (a factual report on an event or topic). Journalistic videos present the events as they happened.
The second style is a “cinematic” style that is similar to a professional movie. The footage is edited for “maximum” (as much as possible) emotional impact and is designed to “impress” (make someone think that something is very good or special) the viewer.
The third style of wedding videography is a “storytelling” style in which the videographer tells the story of the wedding couple’s love. The final product might include stories told by the bride and groom of how they first met or how the groom “proposed” (asked the woman to marry him). It might also include stories from friends and relatives.
“Short form wedding” is the fourth style of wedding videography. In this style, the footage is presented in as little as 15 minutes, and always under 60 minutes. The videographer films all of the wedding events, but only some of that footage is included in the final product, and it might not be presented “chronologically” (reflecting the order in which events actually happened).
Finally, the last style of wedding videography is the “traditional” style. These videos present the full footage of the wedding and all related events, presented in “chronological” (following the order in which events occurred) order. These videos may last for a few hours.
Comprehension Answers
1 - c
2 - c