= 1179
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,179 – Reading Food Labels.
This is English as a Second Language Podcast episode 1,179. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and become a member of ESL Podcast. When you do, you can download the eight- to ten-page Learning Guide that comes with this episode. It gives you a complete transcript of every word I say as well as vocabulary words, definitions, additional sample sentences, culture notes, and a whole lot more.
This episode is a dialogue between Amy and Giorgio about understanding what is in the food you buy from a store. Let’s get started.
[start of dialogue]
Amy: Put a big bag of those potato chips in the basket.
Giorgio: Have you read the nutritional label on these chips?
Amy: No, but look. This doesn’t have very much saturated fat, trans fat, or sodium.
Giorgio: Look at the serving size. It’s three potato chips. How often do you stop at three chips?
Amy: Okay, no potato chips. I’ll get this package of cookies. There aren’t many calories or carbohydrates in these, or much cholesterol or sugar either.
Giorgio: Look again. The serving size is one cookie. There are 40 cookies in each container.
Amy: Not everything has to be healthy and good for me.
Giorgio: No, but you have to get your protein and fiber from somewhere. If you look at the percent daily value on the things you’re eating, you’re not getting the nutrients, vitamins, and minerals your body needs.
Amy: This isn’t all I eat. I eat other things, too.
Giorgio: Like pizza, hamburgers, and fries?
Amy: I might not have the best diet, but I’m healthy as a horse.
Giorgio: Maybe a horse ready to be put out to pasture!
[end of dialogue]
Amy begins our dialogue by saying to Giorgio, “Put a big bag of those potato chips in the basket.” “Potato chips” are made, of course, from potatoes. They usually have salt on them. They’re very thin and are typically fried. A “basket” here refers to a shopping basket. It’s a container that you put things into when you are shopping at a grocery store, at a store where you buy food. Giorgio says, “Have you read the nutritional label on these chips?”
“Nutrition” (nutrition) refers to the kind of food you eat, and in particular, the quality of the food or the ingredients of the food – what’s in the food. “Nutritional labels” (labels) are found on most foods that you buy in a grocery store or another store in the U.S. The government requires that the makers of the food put a label – that is, a small piece of paper or something that is on the outside of the food package (what the food comes in) – that indicates what is in the food, in particular certain categories of ingredients or certain categories of nutrition. We’ll talk about those categories in a minute.
Amy says, “No” – she has not looked at or read the nutritional label. “But look,” she says, “This doesn’t have very much saturated fat, trans fat, or sodium.” Amy is now looking at the label and telling Giorgio that these potato chips that she wants to buy don’t have very much “saturated (saturated) fat.” Saturated fat, without going into a technical, scientific explanation, is usually fat that comes from animal products.
The word “saturated” refers to its chemical composition, how it is actually formed chemically. There are “saturated fats,” “mono saturated fats,” “poly saturated fats,” and “trans fats.” If you want a definition for all of those things, it’s best to look online. But a saturated fat is a fat that is solid or would be solid at room temperature. There are some people who think saturated fats are bad for you, other people who say it doesn’t really matter.
We’re not going to go into those arguments here, but many Americans have been told for many years that saturated fats are bad for them. That’s why Amy says look, it doesn’t have any, or “very much,” saturated fat. She says it doesn’t have very much “trans (trans) fat.” A trans fat is made usually from some sort of chemical process, and again, there are many people who think trans fat is very bad for your health. The third item Amy mentions is “sodium” (sodium). Sodium is basically salt.
Giorgio says, however, “Look at the serving size.” The “serving (serving) size” is the amount of food that the people who make the food say would be typical for one person to eat. If you make the serving size very small, then it will look as though that the amount of, say, sodium or trans fat is not very high. But oftentimes, the serving size on a package of food is not very realistic, but the company makes it really small so that when you look at the nutritional label, it doesn’t look as though there is a lot of, say, trans fat or sodium in it.
Giorgio says the serving size for these potato chips is three potato chips. “How often do you stop at three chips?” meaning “How often do you only eat three chips and not continue to eat more?” There was a famous advertisement for a potato chip company, and the ad said, “No one could eat just one,” meaning if you ate one potato chip, you would want to eat more – which of course is true for a lot of food such as potato chips. Amy says, “Okay, no potato chips,” meaning she won’t buy any potato chips.
She says, “I’ll get this package of cookies. There aren’t many calories or carbohydrates in these, or much cholesterol or sugar either.” Amy mentions a couple of other categories that are typically found on a nutritional label. The one that you will almost always find is “calories” (calories). A “calorie” is technically a unit of heat energy, but most people think of a calorie as how much energy you could get out of this particular kind of food. Most men eat around 2,000 to 3,000 in the United States per day. The average American woman eats around 1,800 calories per day.
“Carbohydrates” are one of the three major kinds of “nutrients,” we call them. There are “carbohydrates,” “fat,” and “protein.” Carbohydrates are basically foods that are or nutrients that are turned into sugar and used for energy. A lot of the foods we eat have a combination of carbohydrates, protein, and fat in them. Amy also mentions “cholesterol” (cholesterol). Cholesterol is something that your body needs in order to function. Cholesterol can in certain cases be bad for you, at least too much of a certain kind of cholesterol in your body.
Once again, there is a relationship between the cholesterol you eat and the cholesterol in your body, but it’s not the same thing. People sometimes confuse the two. Your body needs cholesterol. Cholesterol is a good thing. But there are debates about how much eating cholesterol may affect your body’s or blood’s cholesterol levels. “Sugar” (sugar), you’re probably familiar with, is the kind of thing that makes food sweet.
Giorgio says, “Look again. The serving size is one cookie. There are 40 cookies in each container” – that is, in each package. Once again Giorgio is pointing out that even though the nutritional label indicates there aren’t very many calories in this package of cookies, the serving size is only one. “Not everything has to be healthy and good for me,” Amy responds. Giorgio says, “No, but you have to get your protein and fiber from somewhere.” “Protein” (protein), we’ve already pointed out, is one of the three major types of nutrients – things that your body needs.
Your body needs protein for all sorts of things, including building muscles. “Fiber” (fiber) is actually a kind of carbohydrate. It’s the part of typically a plant that is eaten but is difficult for your body to digest. We won’t go into all the technical definitions of the different kinds of fiber – “soluble fiber,” “insoluble fiber,” and so forth – but fiber basically doesn’t get absorbed into your body. You eat it and then it ends up eventually going out of your body in a way that I think you probably can guess.
“If you look at the percent daily value on the things you’re eating,” Giorgio continues, “you’re not getting the nutrients, vitamins, and minerals your body needs.” The U.S. government has decided, or has recommended, that everyone get a certain amount of these different kinds of nutrients and other food elements every day. And so when you look on a nutritional label in the United States, you will see something called the “percent daily value.” That indicates how much of the recommended daily amount of that particular thing this food provides.
So, if a food says it provides 10 percent of the fiber that you need, you would know then that you still have 90 percent to go with the other food in order to get what the U.S. government thinks is the amount of fiber you need every day. These “percent daily values” are not all that useful for many people since some people need more of things than other people. Our bodies are different. But the government wants to give you some idea of what you need every day from your food.
Giorgio says, “You’re not getting the nutrients (nutrients) your body needs.” “Nutrients” refers to carbohydrates, protein, and fat, as well as vitamins and minerals. “Vitamins” (vitamins) refers to a substance that is required for growth or survival but that is usually only needed in a small amount. Once again, that’s not a very technical definition of a vitamin.
“Minerals” (minerals) are what we call “inorganic substances” – non-living things that are required, but once again are only needed in very small amounts. Vitamins in English are typically given letters. There’s vitamin A. There’s vitamin B. There might even be different types of different vitamin letters – vitamin B1, vitamin B12, and so forth.
Minerals are things like calcium, sodium, potassium, magnesium, that the body also uses.
Amy says, “This isn’t all I eat. I eat other things, too.” Giorgio says, “Like pizza, hamburgers, and fries?” Here, the word “fries” refers to French fries – potatoes that are cut up and put into oil. Amy says, “I might not have the best diet, but I’m healthy as a horse.” This expression, “healthy as a horse,” is an old one meaning very healthy. Although I have to be honest, I’ve never used it myself.
Giorgio says, “Maybe a horse ready to be put out to pasture!” Giorgio then makes a joke about this expression. When a horse is old and can no longer be used for riding or racing, we may put that horse “out to pasture” (pasture). “Pasture” is land that cattle or horses eat off of. It’s an area on a farm where you can put the animals because they can eat what is growing out of the ground.
“To put a horse out to pasture” means to retire the horse, to no longer use the horse, to let the horse live the rest of its days – live the rest of its life – just eating food and not doing anything. It’s another expression for “retiring” someone. Giorgio is making a joke here, saying that Amy isn’t healthy as a horse unless she means an old horse, a sick horse – a horse that is no longer healthy anymore, really.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Amy: Put a big bag of those potato chips in the basket.
Giorgio: Have you read the nutritional label on these chips?
Amy: No, but look. This doesn’t have very much saturated fat, trans fat, or sodium.
Giorgio: Look at the serving size. It’s three potato chips. How often do you stop at three chips?
Amy: Okay, no potato chips. I’ll get this package of cookies. There aren’t many calories or carbohydrates in these, or much cholesterol or sugar either.
Giorgio: Look again. The serving size is one cookie. There are 40 cookies in each container.
Amy: Not everything has to be healthy and good for me.
Giorgio: No, but you have to get your protein and fiber from somewhere. If you look at the percent daily value on the things you’re eating, you’re not getting the nutrients, vitamins, and minerals your body needs.
Amy: This isn’t all I eat. I eat other things, too.
Giorgio: Like pizza, hamburgers, and fries?
Amy: I might not have the best diet, but I’m healthy as a horse.
Giorgio: Maybe a horse ready to be put out to pasture!
[end of dialogue]
Dr. Lucy Tse feeds your brain with wonderful English in each of her wonderful scripts – the perfect food for your English.
From Los Angeles, California, I’m Jeff McQuillan, feeling hungry. I think I’m going to go eat. Come back and listen to us again, won’t you? Right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
nutritional label – information about how healthy a food is, with a listing of what the food contains, printed on the side of the container or package
* Jia always reads the nutritional labels before deciding which brand to buy.
saturated fat – fat that is solid at room temperature and typically comes from animal products
* Red meat, cheese, and eggs contain a lot of saturated fat.
trans fat – trans-fatty acid; an unhealthy type of fat made through a chemical process
* Many processed foods contain trans fat, but manufacturers are trying to change their recipes to make the foods healthier.
sodium – salt; NaCl; a white substance placed on food to make it tastier
* If you’re trying to lower your sodium intake, try seasoning your food with fresh herbs instead of salt.
serving size – the amount of food that is general served for one person to eat at one time; the amount of food used for listing contents on a nutritional label
* Many people eat more than the recommended serving size of fatty meats.
calorie – a unit of heat energy; a measure of the amount of energy provided by food
* On average, Lionel consumes about 2,000 calories per day.
carbohydrate – a type of nutrient that the body changes into sugar and uses for energy
* Runners often eat a lot of carbohydrates, like the ones found in bread and pasta, before a big race.
cholesterol – a substance that is needed in the body, but that can cause blood vessels (passages) to thicken, making it difficult for blood to pass through and raising one’s blood pressure
* Kristoff has a very high cholesterol level, which puts him at risk of having a heart attack.
sugar – a sweet substance found in foods that provides energy
* Jenna tried to make the cupcakes healthier by substituting honey for some of the white sugar.
container – an object that holds something, especially a plastic or metal box used to store food
* Could you please buy a small container of sour cream when you go to the grocery store?
protein – a type of nutrient that people eat that helps to build muscles
* Most people get their protein from meat, but vegetarians need to get their protein from combinations of nuts, grains, and beans.
fiber – the part of a plant that is eaten, but is more difficult for the body to digested (process)
* These are high-fiber bran muffins. If you eat too many of them, you might have to use the bathroom a lot.
percent daily value – an indication of how much of the recommended daily amount of a particular nutrient or mineral is provided by a particular amount of food
* This small bottle of orange juice provides 80 percent daily value of Vitamin C.
nutrient – a carbohydrate, protein, fat, vitamin, mineral, or related substance that is necessary for growth and survival
* Eating a varied diet is the best way to make sure you’re getting all the nutrients your body needs.
vitamin – an organic (related to living things) substance that is required for growth and survival, but needed in only small amounts and that must be obtained through one’s food, because they cannot be produced by the body
* Most of the milk sold at grocery stores is fortified with Vitamin D.
mineral – an inorganic (related to non-living things) substance that is required for growth and survival, but needed in only small amounts and that must be obtained through one’s diet, because they cannot be produced by the body
* Some people take minerals like zinc because they think it will prevent them from becoming sick.
healthy as a horse – extremely healthy; without any medical problems
* Bo has always been very athletic, and even at age 70, is as healthy as a horse.
to be put out to pasture – to be retired; to be discontinued or replaced; to be allowed to rest until one dies
* When Grandma had to move into an assisted living facility and stop helping to care for the grandchildren, she felt as if she had been put out to pasture.
Comprehension Questions
1. Which of these provides calories?
a) Saturated fat
b) Sodium
c) Minerals
2. What does Giorgio mean when he says, “Maybe a horse ready to be put out to pasture”?
a) He thinks Amy should become a vegetarian.
b) He thinks Amy isn’t as healthy as she thinks she is.
c) He thinks Amy looks like a horse.
Answers at bottom.
What Else Does It Mean?
sugar
The word “sugar,” in this podcast, means a sweet substance found in foods that provides energy: “Do you want sugar and cream with your coffee?” Or: ”On Halloween night, the children ate too much sugar and then felt sick.” The word “sugar” is sometimes used as a term of endearment for a loved one: “Hey, sugar, don’t forget to call me tonight.” A “sugar daddy” is an older man who gives a younger woman a lot of money and presents in exchange for a sexual relationship: “We thought Chelsea viewed Jake as a sugar daddy, but now she is talking about marrying him.” Finally, if something is “sugar-coated,” it is being made to seem better than it really is: “Don’t give me the sugar-coated version of my medical diagnosis. Just tell me the truth.”
fiber
In this podcast, the word “fiber” means the part of a plant that is eaten, but is more difficult to digest: “Foods like celery and kale have a lot of fiber, which make them low in calories and very filling.” The word “fiber” also refers to the threads used to make clothing or rope: “These wool fibers are irritating my skin.” Or, “Please dye these nylon fibers to match the color of the leaves.” The phrase “nerve fibers” or “muscle fibers” refers to small pieces within one’s body, used to transmit signals or messages: “Chronic pain patients have to learn to retrain their nerve fibers.” Finally, the phrase “with every fiber of (one’s) being” means very strongly, especially when describing emotions: “She loves him with ever fiber of her being.”
Culture Note
The American Heart Association
The American Heart Association is a well-known “nonprofit” (not intended to make money) organization that was founded by six “cardiologists” (doctors who specialize in the study and treatment of the heart) in 1924. Today, the organization’s “mission” (purpose) is to build healthier lives that are free of “cardiovascular diseases” (health problems related to the heart) and “stroke” (an attack caused by an interruption of blood flow in the brain). It also publishes “standards” (norms; things that everyone should follow) for healthy living.
The American Heart Association “funds” (provides money for) research, “advocates” (supports) stronger health policies, and provides public health education. The organization tries to help people connect their “lifestyle choices” (the decisions one make in life, such as whether to smoke, how much to exercise, and what to eat) with their “health outcomes” (how healthy someone is later in life). The organization also encourages “legislators” (people in government who make laws) to make their decisions based on “sound” (good and logical) science.
Today, the organization has a strong focus on raising awareness that heart disease affects women—not just men. The organization’s “Go Red for Women” “campaign” (a coordinated effort to do something) fights heart disease in women and teaches people the “warning signs” (signals that indicate something bad is going to happen) of heart attacks and strokes for both men and women, such as “numbness” (not being able to feel part of one’s body), “blurred vision” (an inability to see things clearly), “dizziness” (feeling like one might fall down), and a sudden headache.
Comprehension Answers
1 - a
2 - b