= 1191
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,191 – Living on the Fringes of Society.
This is English as a Second Language podcast episode 1,191. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Hey, it’s the Star Wars edition! Because everyone know I played Chewbacca in the original movie.
Visit our website at ESLPod.com and become a member of ESL Podcast to download the Learning Guide for this episode. You can also take a look at our ESL Podcast Store and like us on Facebook at facebook.com/eslpod.
This episode is a dialogue between Donald and Carla about living on the fringes of society. Let’s get started.
[start of dialogue]
Carla: Why do those teenagers have to dress like that? Don’t they want to fit in?
Donald: Maybe they feel marginalized and they’re showing their feelings of alienation through their clothes.
Carla: That’s just a bunch of psychobabble. Nobody is treating them like second-class citizens. They’re choosing to set themselves apart, to make themselves outcasts.
Donald: Maybe they don’t feel they have the same access and privileges that other people do because of social class, religious beliefs, or other factors.
Carla: Nobody is shunning them. They choose to live on the fringe of society. They need to stop making themselves conspicuous and integrate into society.
Donald: What if they doubt they’d be accepted?
Carla: That’s ridiculous.
Donald: Would you want one of them as your neighbor?
Carla: Well, I . . . well . . .
Donald: I think I’ve proved my point.
[end of dialogue]
This episode is called “Living on the Fringes (fringes) of Society.” The “fringes of society” refers to the people who are not accepted as normal members of the community, or who for a variety of reasons don’t feel like they’re part of a country or a society – a group of people. Carla begins our dialogue by asking, “Why do those teenagers have to dress like that? Don’t they want to fit in?” “To fit (fit) in” is a two-word phrasal verb meaning to be similar to the people around you, to be accepted by the people around you and feel comfortable with others.
Donald says, “Maybe they feel marginalized and they’re showing their feelings of alienation through their clothes,” or through their clothing. “To be marginalized” (marginalized) is to be treated as though you were unimportant or not necessary for a given group. The verb “to marginalize” someone means to treat them in a way that makes them feel unimportant. It’s a word mostly used in politics and sociology more than in everyday conversation. “Alienation” (alienation) is a feeling of not belonging or feeling part of a group.
Donald thinks that maybe these teenagers are dressing so differently from others because they don’t feel like they’re part of the group. They have feelings of “alienation.” Notice that that word “alienation” has the word “alien” inside of it. “Alien” is what we might use to describe a person from another country, a foreigner. We might also describe a being from another planet, if such beings exist, as being “aliens.” E.T., from the movie of the 1970s, was an alien. He was from another planet. My neighbor, I believe, is an alien. I think he’s from Mars. Yeah, seriously.
Anyway, Carla says to Donald, “That’s just a bunch of psychobabble.” “A bunch of” is an informal way of saying “a lot of.” “Psychobabble” (psychobabble) refers to terms or words that people use that come from psychology or psychotherapy, but that don’t really mean anything or that are not used very accurately by non-psychologists. It’s what we might call a “derogatory term.” It’s an insulting term to describe the way someone is using language inaccurately.
Carla says, “Nobody is treating them,” meaning these teenagers, “like second-class citizens.” “Second-class citizens” refers to people who are not perhaps respected or treated the way they should be. It might also refer to a group of people who are discriminated against in a given society or culture because of the way they look or because of who they are. But Carla says these teenagers are not being treated like second-class citizens.
She continues, “They’re choosing to set themselves apart, to make themselves outcasts.” “To set yourself apart” means to do something or say something that makes you seem different from other people. “To make yourself an outcast” (outcast) is to make yourself so different from other people that other people don’t accept you, that other people reject you. An “outcast” is a person not accepted, or rejected, by people in a given community or society.
Donald says, “Maybe they don’t feel they have the same access and privileges that other people do because of social class, religious beliefs, or other factors.” “Access” (access) is the ability to get something, is the ability to be able to obtain something. “Privilege” (privilege) refers to some advantage that you have over other people, often something that perhaps you don’t earn but are given because of circumstances or situations that have nothing to do with how smart you are or how hard you worked. That’s usually how the word is used nowadays.
If someone talks about a person’s “privileges,” he’s talking about things that person has that he didn’t have to work for, or perhaps didn’t have to earn. He got them just because of his parents or the place in which he was born. Donald talks about social class and religious beliefs. “Social (social) class” refers to the group of people you belong to based on how much money you make.
In the United States, we sometimes talk about the “upper class,” referring to rich people; the “middle class,” referring to people who are neither rich nor poor; and the “lower class” or the “working class” – people who are usually poor. The term “social class” might refer not just perhaps to how much money you make, but also to the certain kinds of values or the certain kind of culture that people in your class or in your group might have.
“Religious beliefs” refer to the things that you believe in terms of God and the existence of a higher or supernatural being. People around the world have different religious beliefs, and sometimes these religious beliefs may cause problems with those in the community who don’t share those beliefs. Carla says, however, “Nobody is shunning them.” “To shun” (shun) someone is to reject or ignore someone. It might include even not talking to the person or allowing the person into your house.
Carla continues, “They,” again referring to the teenagers, “choose to live on the fringe of society.” We described what we mean by “the fringes of society” earlier. “They need to stop making themselves conspicuous and integrate into society.” “To be conspicuous” (conspicuous) is to be easily noticed, to stand out, to be obvious. The teenagers, by dressing differently, are “conspicuous” – everyone notices them. Carla says instead they should “integrate (integrate) into society.” “To integrate” means to combine two things together so that they become one unit or one group.
Donald says, “What if they doubt they’d be accepted?” “To be accepted” means to be welcomed, to be appreciated as a member of a group. Carla says, “That’s ridiculous,” meaning that’s silly. Donald says, “Would you want one of them as your neighbor?” In other words, he’s asking Carla if she would accept one of these teenagers living next door to her, being her neighbor.
Carla doesn’t answer right away. She says, “Well, I . . . well . . .” You can tell the answer is no. Donald then says, “I think I’ve proved my point.” “To prove (prove) your point (point)” is to demonstrate that what you just said is true, that what you just said is correct. “To prove your point” is to provide evidence that shows that what you are saying is true.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Carla: Why do those teenagers have to dress like that? Don’t they want to fit in?
Donald: Maybe they feel marginalized and they’re showing their feelings of alienation through their clothes.
Carla: That’s just a bunch of psychobabble. Nobody is treating them like second-class citizens. They’re choosing to set themselves apart, to make themselves outcasts.
Donald: Maybe they don’t feel they have the same access and privileges that other people do because of social class, religious beliefs, or other factors.
Carla: Nobody is shunning them. They choose to live on the fringe of society. They need to stop making themselves conspicuous and integrate into society.
Donald: What if they doubt they’d be accepted?
Carla: That’s ridiculous.
Donald: Would you want one of them as your neighbor?
Carla: Well, I . . . well . . .
Donald: I think I’ve proved my point.
[end of dialogue]
Our scriptwriter never uses psychobabble in her scripts. Thank you, Dr. Lucy Tse, for your wonderful scriptwriting.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to fit in – to conform; to be similar to other people, understand one’s place and position in relationships with other people, and feel comfortable with others
* It’s hard to fit in if you’re the only person over the age of 40 in a class of new young college students.
to marginalize (someone) – to treat someone as if he or she is unimportant or unnecessary
* The manager’s comments marginalized the people who work in marketing, making them feel like their department isn’t valued.
alienation – feelings of not belonging, or not being part of a group
* As the only Muslim at his school, Mahmud often suffered from alienation as he was growing up.
psychobabble – words that are commonly used by non-psychologists to describe psychological conditions, often meaningless or confusing
* All the psychobabble on popular talk shows tends to make people think they understand complex mental health conditions.
second-class citizen – a person who is less important or respected than other people and who has fewer rights than others, often as a result of certain personal characteristics
* In Benoit’s speech, he said that women are not second-class citizens. They should have a right to vote and make laws, just like men do.
to set (oneself) apart – to do or say something that makes one seem different from other people
* James’ strong morals and ethics set him apart from most of the people he works with.
outcast – a person who does not fit in and has been rejected by or excluded from society in some way
* Her teenage daughter unwrapped the sweater and then started crying, saying, “I can’t wear that to school! I’ll be a social outcast if people see me in that!”
access – a way to have or do something that is not available to everyone
* The police investigating the burglary want to know who had access to the safe.
privilege – a right or advantage that only some people have, granted by other people
* Driving the family car is a privilege you’ll earn when you get better grades.
social class – a division of society, especially based on how much money one earns, which family one comes from, and/or who one interacts with
* They have friends from many different social classes, which results in some interesting interactions when they host large parties.
religious – related to one’s beliefs about the origin and purpose of life involving one or more supernatural powers
* The building is full of Christian religious symbols, such as crosses.
belief – what one thinks is true, especially when it affects one’s behaviors
* They are studying people’s belief in life on other planets.
to shun – to repeatedly reject or ignore someone or something
* The mangers consistently shun any attempt to raise prices, because they fear that would scare away customers.
on the fringe of society – not fitting into general society in one or more ways, being treated differently than other people
* What can we do to help the homeless so they don’t live on the fringe of society?
conspicuous – obvious; easily noticed; standing out; difficult to avoid seeing
* These brightly colored frogs are so conspicuous against the green leaves. I’m surprised they can survive at all in the jungle.
to integrate – to combine something with one or more other things so that they become part of the same unit
* How can we integrate our schools so that they better represent the different races and immigrant groups in our community?
to be accepted – to be welcomed and appreciated by other people and invited into their groups and activities, or at least not be excluded from them
* Teenagers’ desire to be accepted by their peers can sometimes lead to risky behaviors, such as drinking or doing drugs.
to prove (one’s) point – to show or demonstrate that what one believes or has said is definitely true
* When I was talking about how much you interrupt people, you interrupted me! That just proves my point.
Comprehension Questions
1. Why is Carla complaining about how the teenagers dress?
a) Because their clothes don’t fit.
b) Because they’re not doing what people expect.
c) Because they are second-class citizens.
2. How are people shunned?
a) By setting themselves apart.
b) By not giving them access and privileges.
c) By integrating them into society.
Answers at bottom.
What Else Does It Mean?
to set (oneself) apart
The phrase “to set (oneself) apart,” in this podcast, means to do or say something that makes one seem different from other people: “Kevin’s attention to detail sets him apart from other computer programmers.” The phrase “to set (oneself) against (something)” means to oppose an idea or action: “Samuel has set himself against running in the next election.” The phrase “to set (something) aside” means to reserve or save something for later: “Let’s set these candles aside for the next power outage.” The phrase “to set off” means to start to go somewhere: “They set off for their house on the coast around noon.” Finally, the phrase “to set out” means to start a long journey or trip: “They’re really excited to set out on a trip around the world.”
to prove (one’s) point
In this podcast, the phrase “to prove (one’s) point” means to show or demonstrate that what one believes or has said is definitely true: “The success of this new program will prove our point and demonstrate that we should adopt this program at all of the company’s office locations.” The phrase “the point of no return” refers to the point in time at which something cannot be stopped: “Once the space shuttle enters the upper atmosphere, we are beyond the point of no return, and we have to keep going forward.” The phrase “up to a point” means partially: “I agree with you up to a point, but there are some other things to consider.” Finally, the phrase “to make a point of doing (something)” means to do something intentionally or deliberately: “She makes a point of reading to her children every night at bedtime.”
Culture Note
Nonsense Terms
Sometimes people use “nonsense” (silly; without meaning) “terms” (words and phrases) as a “placeholder” (something that takes the place of something else) for “meaningless” (without clear meaning) or “overly technical” (understood by only a few highly educated and experienced people) words. For example, someone might refer to the use of a lot of words from psychology as “psychobabble,” or to a lot of technical “jargon” (vocabulary understood by only a small group of people within a particular industry or organization) as “technobabble.” This simply means that most “lay persons” (ordinary people without specialized knowledge of a particular topic) would not be able to understand what is being said.
When people talk about legal “contracts” (formal legal agreements), they sometimes refer to “legalese.” This is the text that must be repeated in many or all contracts, but is rarely read by the people signing those contracts. For example, we have to sign papers with a lot of legalese before buying a house, applying for a “loan” (borrowing money from a bank or other institution with the promise to pay it back with interest (additional money)), or even signing up for a new cell phone contract. The language is too “complex” (complicated) and “convoluted” (difficult to follow and understand) for most people to understand.
The words “gobbledygook” and “gibberish” are used to refer to things that cannot be understood even by specialists. For example, if a printer has an error and starts printing out strange characters that have no meaning, the user might refer to the “printouts” (the documents that come out of printer) as pages of gobbledygook. Or someone might listen to a young child’s gibberish – sounds that cannot be understood by adults.
Comprehension Answers
1 - b
2 - b