= 1194
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,194 – Using a Map Program.
This is English as a Second Language Podcast episode 1,194. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com to become a member of ESL Podcast and download the PDF Learning Guide for this episode. You can also take a look at our ESL Podcast Store with additional courses in Business and Daily English.
This dialogue is about using a software program – an application on a computer or a phone – related to a map. Let’s get started.
[start of dialogue]
Caroline: I just got an email from Sandra with her new address. I wish I knew what kind of neighborhood our daughter is living in.
Bryce: Let’s find out. I’ll type in her address on this map program.
Caroline: That will just tell us where she’s living within the city, not what kind of neighborhood it is.
Bryce: Just wait. I can show you the street view of her apartment and you can see what her building looks like.
Caroline: Wow, that’s amazing, but doesn’t the building look a little run-down?
Bryce: That’s what you get with high-resolution images. You see every detail. You can navigate around and see a panoramic view of her street.
Caroline: Oh, that doesn’t look very clean or safe.
Bryce: Let me show you an aerial view. The satellite view will give you a better idea of the entire area.
Caroline: Is that an airport nearby and are those factories? What will this other view show us?
Bryce: That provides real-time traffic information and allows for route planning. It looks like she lives on a highly congested street. Hey, where are you going?
Caroline: I’m going to visit our daughter. I want to see for myself what kind of hovel she’s living in!
[end of dialogue]
Caroline begins our dialogue by saying, “I just got an email from Sandra with her new address.” Your “address” (address) is information that allows someone to find you.
Usually an “address” will have the name of the street on which you live, the number of your house or apartment building, the city where you live – here in the United States, the state in which you live – and something called a “zip (zip) code (code).” In some countries, it’s called a “postal code.” It’s a number that is assigned to the general area or neighborhood in which you live. In some countries, the postal code is a combination of letters and numbers. In the United States, it’s just numbers. There are five digits in a standard zip code.
So, Caroline has the address of Sandra, and we learn that Sandra is her daughter – or I guess Carolyn and Bryce’s daughter – because she says, “I wish I knew what kind of neighborhood our daughter is living in.” Bryce says, “Let’s find out. I’ll type in her address on this map program.” “To type (type) in” means to use what we call a “keyboard” (keyboard) to enter information into a computer. A keyboard has the letters and numbers that you would use to enter information into your computer. I say “letters,” of course, referring here to the English alphabet.
A “map program” would be any sort of application or software program that would have a map associated with it and allow you to find people on the map. On my phone, for example, I have a couple of different map “apps” or applications, including Google and Apple. Caroline says, “That will just tell us where she’s living within the city, not what kind of neighborhood it is.” A “neighborhood” is in area of a city. Everyone lives in a neighborhood – an area or section of the city. Caroline is interested in finding out the kind of neighborhood her daughter is living in – not just where it is, but is it a good neighborhood, is it a bad neighborhood, what kind of people live there, and so forth.
Bryce says, “Just wait. I can show you the street view of her apartment and you can see what her building looks like.” On some map programs, including Google Maps, in many cities you can actually look at photographs of the different parts of the city – the buildings and houses in the city. That’s what “street view” allows you to do. It’s an image of, or a photograph of, the street and the buildings on that street. It’s almost as if you were walking down the street. This is an amazing thing you can do. Some people don’t like the idea of, say, Google going around and taking photographs of everyone’s house, but it can be convenient if you want to see what a house or building looks like.
Bryce says that is what he can do so that he and his wife, Caroline, can look at their daughter Sandra’s apartment. Caroline says, “Wow, that’s amazing, but doesn’t the building look a little run-down?” The term “run-down” means that it is not in very good condition, perhaps because it is old or has been used a lot. If we describe a building as being “run-down,” we’re saying the building is old and perhaps even falling apart. Maybe some of the walls aren’t painted and the ceilings – the top of the room – perhaps has holes in it. That would be a run-down building, or what we would describe as a “run-down building.”
You could describe yourself as being “run-down” if you’ve been working a lot recently, or perhaps have some sort of cold or flu. You may “feel run-down,” like you are falling apart. The phrasal verb “to fall apart,” usually refers to an object whose pieces are beginning to come apart. In other words, the object is breaking apart into smaller pieces. Caroline thinks the building her daughter Sandra lives in looks a little run-down. Her husband, Bryce, says, “That’s what you get with high-resolution images.” “High-resolution images” are images that are very high quality. They allow you to see the small details of an image.
In fact, that’s what Bryce says next. He says, “You can see every detail” (detail). “Details” are small specific pieces of information about something. A detail on a photograph could be a small part of the image. “Details,” in general, refer to specific pieces of information. You could have details about almost anything. I could give you the details of a story, the specific things that happened in a story, or you could give someone the details of the meeting you went to – all the things that happened in the meeting, the specific pieces of information.
Bryce says, “You can navigate around and see a panoramic view of her street.” “To navigate” (navigate) means to move around or move through something, especially if it is difficult. Here it refers to the ability to see different parts of the city or the, in this case, “street view.” You can – on for example the Google map program, when it is available – actually move down the street and see the different houses along the street. In this case, the map program allows Bryce to see a “panoramic (panoramic) view” of her street. “Panoramic” refers to a large, wide view of something.
Caroline says, “Oh, that doesn’t look very clean or safe.” She’s referring to the area where her daughter lives – perhaps the streets are dirty or the other buildings around her apartment are run-down as well. Bryce says, “Let me show you an aerial view.” “Aerial” (aerial) means from the air. Again, many map programs will show you a satellite photo of an area, as if you were up in the sky looking down at it. Bryce mentions this in his next sentence. He says, “The satellite (satellite) view will give you a better idea of an entire area.” A “satellite” is a piece of equipment that goes around the earth, way up in space. It “orbits,” or goes around the earth, and some satellites can take photographs of the earth.
Caroline says, “Is that an airport nearby and are those factories?” Caroline is now looking at the satellite or aerial photographs of the neighborhood in which her daughter lives. She’s asking if there is an airport nearby. She sees an airport on the photograph and she also sees some “factories” (factories). A “factory” is a large building where things are “manufactured” – where they’re made, where they’re produced. Normally you don’t find factories next to nice or good neighborhoods because factories can be noisy or they can have a lot of pollution associated with them. So, Caroline is concerned about the quality of this neighborhood if it’s right near an airport and has factories in it.
Then she says, “What will this other view show us?” She’s looking at the map program, probably pointing to some other feature on the program. Bryce says, “That provides real-time traffic information and allows for route planning.” On some map applications, you can find out what the traffic is like – how many cars are on the street or freeway. “Real-time” means right now – or more typically, within the last, say, five minutes. “Route” (route) refers to how you go from one place to another. “Route planning” would allow you to figure out which streets or freeways you should take to get from one part of the city to another.
Bryce says, “It looks like she lives on a highly congested street.” If a street is “congested” (congested), there are a lot of cars on it, a lot of traffic. It’s a very, what we would describe as, “busy” (busy) street. A “busy street” is a street that has a lot of cars going back and forth on it. Again, that is probably not the best place to live since it could be very noisy.
Bryce then asks Caroline, “Hey, where are you going?” Caroline says, “I’m going to visit our daughter. I want to see for myself what kind of hovel she’s living in.” Caroline is going to, I guess, drive over to her daughter’s house to see it for herself. She is worried that her daughter is living in a “hovel” (hovel). A “hovel” is a small, old, dirty building. Usually it’s a very negative way to describe someone’s house. Sandra, the daughter, lives in an apartment, but we use the term “hovel” in general to describe a small, not very nice place to live.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Caroline: I just got an email from Sandra with her new address. I wish I knew what kind of neighborhood our daughter is living in.
Bryce: Let’s find out. I’ll type in her address on this map program.
Caroline: That will just tell us where she’s living within the city, not what kind of neighborhood it is.
Bryce: Just wait. I can show you the street view of her apartment and you can see what her building looks like.
Caroline: Wow, that’s amazing, but doesn’t the building look a little run-down?
Bryce: That’s what you get with high-resolution images. You see every detail. You can navigate around and see a panoramic view of her street.
Caroline: Oh, that doesn’t look very clean or safe.
Bryce: Let me show you an aerial view. The satellite view will give you a better idea of the entire area.
Caroline: Is that an airport nearby and are those factories? What will this other view show us?
Bryce: That provides real-time traffic information and allows for route planning. It looks like she lives on a highly congested street. Hey, where are you going?
Caroline: I’m going to visit our daughter. I want to see for myself what kind of hovel she’s living in!
[end of dialogue]
Our dialogues give you all of the details on how to use English, thanks to the wonderful scriptwriting by our scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
address – information that allows someone to locate a home, specifically the house number, street name, city, and state
* Provide us with your mailing address and when the results are ready, we’ll mail you a copy.
to type in – to use a keyboard to enter information into a computer
* Just type in the customer’s last name and hit enter. Then you should be able to see the entire account history.
map program – a website or mobile application that provides detailed, interactive maps and driving directions
* The map program considers traffic when calculating driving times, so it knows that what might take one hour in the middle of the night might require three hours in mid-afternoon.
street view – an image of what a building or area looks like from the street in front of it
* Lei gets very nervous about driving in unknown areas, so she likes to preview the street view first so that she knows what to expect.
run-down – old, heavily used, and starting to fall apart
* Does that run-down car even start anymore?
high-resolution – describing a graphic image that has a lot of detail and can be made larger while still maintaining the quality of the image
* Please send a high-resolution image of your company’s logo so that we can include it in the printed brochures.
detail – small, very specific pieces of information about something
* The proposal sounds interesting, but we can’t make a decision until we have more details about the budget.
to navigate – to move around or through something, especially when it is complex
* It’s difficult to navigate the rules around health insurance.
panoramic – a very large, wide view of something; not tunnel-like vision
* The panoramic views from the top of that mountain are beautiful.
aerial – from the air, or related to the air or flying
* Salma is an aerial athlete who jumps out of airplanes and performs special moves and jumps while falling through the air.
satellite – a piece of equipment that orbits (goes around) the earth, taking photographs and measurements, or sending and receiving information
* Researchers are using satellites to measure the quantity of ice at the north and south poles.
factory – a large building where things are manufactured (produced)
* Have you ever gone on a tour of a cheese factory? It’s fascinating.
real-time – as something happens, not a recording of something that happened earlier
* With this technology, companies can receive customers’ electronic payments in real time.
route planning – the process of determining the best, fastest, or safest way of getting from one place to another, especially in a car or on public transportation
* When the freeway was closed due to a landslide, a lot of people had to work on their route planning to get to and from work on time.
congested – with a lot of traffic; crowded with too many cars and other vehicles
* The roads are always congested between 7:30 and 9:30, when many people are driving to work.
hovel – a small, old, dirty, and unpleasant building, especially when talking about someone’s home
* On that salary in New York City, you’ll barely be able to afford a one-room hovel.
Comprehension Questions
1. Which of these images would provide the most detail?
a) A street view
b) An aerial view
c) A map view
2. What does Bryce mean when he says, “She lives on a highly congested street”?
a) She lives on a popular street with a lot of bars and restaurants.
b) She lives on a street with a lot of traffic.
c) She lives on a street where many people are sick with sinus congestion.
Answers at bottom.
What Else Does It Mean?
to type in
The phrase “to type in,” in this podcast, means to use a keyboard to enter information into a computer: “Don’t let anyone see when you type in your personal identification number at the bank.” The phrase “to type (something) up means to type the information that is on a printed document or a handwritten note, so that it is saved electronically on a computer: “They’ve hired a few interns to type up these old, handwritten letters.” The phrase “to touch-type” means to type without looking at the keyboard: “Hal types with two fingers, because he never learned how to touch-type.” Finally, “blood type” refers to the type of blood that one has: “Which type of blood do you have: A, B, AB, or O?”
run-down
In this podcast, the phrase “run-down” means old, heavily used, and starting to fall apart: “Our company does great work, but when clients come to visit us in this run-down office, it give them a bad impression. It’s time to move into a nicer building.” A “run-in” is an argument, disagreement, or fight with someone: “He had a small run-in with the police on his way home last night, but he wasn’t given a ticket or arrested.” A “run-off” is a continuation of a competition when there isn’t a clear winner: “If nobody gets more than 50% of the votes, then we’ll have to have a run-off between the top two candidates.” Finally, a “run-through” is a rehearsal before an actual performance: “Let’s meet on Friday for a final run-through before the show begins.”
Culture Note
Google Map Controversies
Many Americans “turn to” (decide to use) Google Maps when they need to “pinpoint” (specify) the location of something or figure out how to drive somewhere. However, due to its popularity, Google Maps has become “mired” (involved in problems) in several controversies.
Some people criticize a “functionality” (something that software does) called Google Map Maker, which allows users to add data to maps. Once users “input” (contribute; provide) information, it is owned by Google, which can “profit” (make money) from it. “Critics” (people who do not like something) say that this isn’t fair, because “the public” (general, ordinary people) are doing the work for free.
More serious criticisms of Google Maps involve privacy. Google takes many images for its street view features, but the U.S. military has asked Google to remove some images of its “bases” (places where military officials work) due to “security concerns” (fears that something is not safe).
Sometimes Google’s images include “license plates” (the numbers on a piece of metal placed on cars for identification), faces, or even “nude” (naked) “sunbathers” (people who are trying to get tanned (browner skin) by the sun). Google has caught surprising images of a man appearing to “break into” (enter without permission) an apartment building, a man in the middle of a sneeze, and “tollbooth operators” (people whose job is to take money from drivers so that they can use a bridge or street) who did not know they were being photographed. When these are “discovered” (found) by map users, they are shared and sometimes “take on a life of their own” (become out of control), embarrassing, or creating problems for the people who are shown in those images.
Comprehension Answers
1 - a
2 - b