
= American Pageant - 002
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Welcome to another Joe's Productions video. Today we're taking a look at the Southern Colonies 南部殖民地 roughly from 1588 to 1733. And as always, no matter which APUSH 美国大学先修课程历史 book you are using, this video is going to help you with all the important content.

So it's important to keep in mind that England is a little bit slow to the colonization game 殖民竞赛. It wasn't until after England defeats the Spanish Armada 西班牙无敌舰队 in 1588 that England is really in a position of being powerful enough to challenge the other countries, especially Spain, and to begin the process of planting colonies 建立殖民地. English colonization is going to be different for a variety of reasons, but one important one to keep in mind is that England was a Protestant country 新教国家. We learned about in world history the Protestant Reformation 宗教改革, and England was a Protestant country whereas Spain was largely Catholic.

It's important to note the different types of colonies, how they're going to be paid for, and how they are run. For example, you have joint stock companies 股份公司 where stockholders 股东 invest in a company such as the Virginia Company of London 伦敦弗吉尼亚公司, and they share in the potential profits or losses from the colony. This can also be referred to as a corporate colony 公司殖民地. Another type of colony you're going to see is a proprietorship 领主殖民地 where land is given by the king to an individual or to a group of individuals. And then finally, a royal colony 皇家殖民地 - it's paid for and ruled directly by the monarchy 君主制.

England's first attempt at colonization is not going to go well. The colony of Roanoke 罗阿诺克殖民地 under Sir Walter Raleigh 沃尔特·雷利爵士 in 1587 in what is today North Carolina. In fact, Walter Raleigh goes back to Europe, and when some individuals return in 1590, the colony is found to be deserted 被遗弃的. All of the men and women are gone.

England's first success in colonization of North America is going to take place in the Chesapeake 切萨皮克地区. And make sure you know this geographic region. The Chesapeake colonies are going to refer to Virginia and Maryland. It's really in the upper South - you could see that right there in the Chesapeake Bay 切萨皮克湾. And the first permanent English colony 永久性殖民地 in North America will be established at Jamestown 詹姆斯敦 in 1607. Its motive was wealth. The king, King James the First, gives a charter 特许状 to the colonists, and in 1607 they establish Jamestown. It's set up under a joint stock company, the Virginia Company of London. Remember, they're going to share in the profits as well as the losses.

100 male settlers 男性定居者 arrive at Jamestown, and they suffer a starving period 饥荒时期. These are men who are wealthy - they're looking for gold like the Spanish had achieved. They're not wanting to do all the hard labor 艰苦劳动. Many of the original settlers die of disease and starvation 疾病和饥饿 because the land was hot, humid 潮湿的, mosquito-infested 蚊虫滋生的, and the settlers were not prepared for this hard work. Luckily, John Smith 约翰·史密斯 comes in and establishes military discipline 军事纪律 and saves the colony. He implements a "you don't work, you don't eat" policy 不劳无获政策, and the colony starts to stabilize 稳定. John Rolfe 约翰·罗尔夫 is gonna give the colony something to make money on when he introduces the cultivation of tobacco 烟草种植 in colonial Virginia.

So what's life like in colonial Virginia? Tobacco provided the colony with a cash crop 经济作物 and led to the rise of the plantation system 种植园体系. You have the rise of very large farms - you can see tobacco right there in the image. And with the cultivation of tobacco, you need a cheap labor supply 廉价劳动力. And early on in colonial Virginia/Jamestown's history, it's going to be indentured servants 契约奴仆. They are going to serve as the early labor force 劳动力 of Virginia. Indentured servants basically serve for a period of time, usually around four to seven years, in exchange for passage to the colony 前往殖民地的旅费. They would work, and at the end of their service, in theory, they would be granted their freedom and perhaps some land.

To encourage this, the headright system 人头权制度 was introduced where individuals would get land if you paid for somebody's journey to the colony. And what this ends up doing is the rich end up getting richer. The wealthy people are paying for indentured servants to come over and getting more and more land. And the sad part is many indentured servants weren't outliving the terms of their contract 活过契约期限 - they would die.

As the colony develops, they establish some government structures 政府结构. The House of Burgesses 弗吉尼亚议会 is established in 1619. This is a form of early representative government 代议制政府. In fact, it's the first in what will be the future United States. This elected representative government didn't happen in French or Spanish colonies, so this is unique to the British colonies. It starts a tradition of self-rule 自治传统, but the House of Burgesses was largely made up of the wealthy planters 富裕种植园主.

Problems are going to begin to develop in the colony. Tobacco destroyed the land - it always kind of required more and more land to cultivate this crop. And as the demand for land goes up, so does the demand for labor. And as this demand for land goes up, people keep moving further and further into the interior 内陆, into the frontier 边疆 as you can see on the map along the James River. Tensions increase with the natives as colonists move west into Native American land. And that's going to lead to two important developments: one, the relationship with Native Americans in the region, and the development of slavery 奴隶制.

So first things first: what was going on with the native people? There was a very hostile relationship 敌对关系 that developed between the colonists and the Powhatan tribe 波瓦坦部落. Powhatan was the chief in the area, and all the different tribes of the Chesapeake region kind of were lumped together under Chief Powhatan. As we already mentioned, tensions increased as the settlers moved west. You can see on the map the English settlements are very close to existing Native American settlements amongst the Powhatan Confederacy 波瓦坦联盟.

A series of wars are going to break out between the years 1610 to 1646. These are collectively known as the Anglo-Powhatan Wars 盎格鲁-波瓦坦战争. The first one ends in 1614 with the marriage between Pocahontas 波卡洪塔斯 and John Rolfe. They looked nothing like that at all. Peace is temporary with this first known interracial union 跨种族结合 in Virginia. This was very rare for the English and the natives to intermarry 通婚.

And another war will begin with the massacre of 1622 1622年大屠杀. Powhatan's Confederacy attacks in 1622, tired of the continual taking of their land and the decimation 毁灭 of their population by European diseases. With the massacre of 1622, over 300 colonists are killed, which is about one-third of the population. The war goes on for a while, and by 1624 Jamestown becomes a royal colony. The Virginia Company of London was bankrupt - the crown takes over colonial Virginia. And by 1646, the Powhatan Confederacy is largely defeated. There's a variety of reasons why they are defeated, and it's largely due to disease which had destroyed the population, disorganization 组织混乱 (keep in mind these tribes were different and so it was hard to put up a united front 统一战线), and they were disposable in the minds of the English - they had no need for them, so they're going to wipe them out 消灭他们.

It's important to note labor relations 劳工关系 in colonial Virginia and the transition to slavery. We've already seen in the early period the primary labor source was indentured servants. But the problem was eventually these individuals were outliving their contract and making demands on the colony. The first Africans were brought into the colony in 1619 aboard a Dutch ship, but in this early period, indentured servants were the majority of the workers.

So how does this change take place? Well, a very important event to keep in mind is Bacon's Rebellion 培根起义. It takes place in 1676. Bacon - and it has nothing to do with the tasty food. Here is the background to it: There was growing frustration with a lack of land. In fact, many of these indentured servants were beginning to outlive the end of their contract, and they wanted land. And Governor Berkeley 伯克利总督, the governor of the colony, did not allow land-hungry settlers 渴望土地的定居者 to move too far west. You can see on the map why - part of the reason is he wants to avoid clashes 冲突 with Native Americans on the frontier.

There also was frustration with the lack of political power 政治权力. Remember, the House of Burgesses was dominated by the plantation elite 种植园精英. So many of these former indentured servants had no political or economic opportunities in the colony. And finally, they wanted the government in Jamestown - the indentured servants and the free whites - wanted the government in Jamestown to do something about Native American attacks on the frontier. Governor Berkeley was reluctant to do so because he was benefiting from a lucrative fur trade 利润丰厚的皮毛贸易 with Native Americans on the frontier. And all of these tensions erupt into something called Bacon's Rebellion.

The leader of the rebellion is Nathaniel Bacon 纳撒尼尔·培根. He leads a group, a rebellion against the Indians on the frontier where they start randomly, indiscriminately killing Native Americans who had allegedly attacked the colonists. And they also moved their frustrations to Jamestown where they burned down the capital 烧毁首府. This is a big crisis in the colony. Nathaniel Bacon - I'd like to think wore this bacon-covered suit - but unfortunately for the rebels, Bacon suddenly dies of dysentery 痢疾. The rebellion collapses. Some of the rebels are hung, and peace comes to the colony.

The impact of Bacon's Rebellion would be huge. It would lead to a transition to African chattel slave labor 非洲奴隶劳工 - in other words, slavery based upon race where individuals would be considered property. And the idea was you could not enslave the native people for a variety of reasons. Indentured servants were outliving their contracts and demanding things. They'd then switch to African slave labor. Bacon's Rebellion also reveals tensions in colonial society between the wealthy and the poor, as well as regions - those poor farmers out in the frontier in the backcountry 偏远地区 versus the more wealthy tidewater elite 潮水区精英 in the east.

Another important colony in the Chesapeake that you should know about is Maryland 马里兰. It is north of Virginia - you can see there right along the Chesapeake Bay. Maryland is a proprietorship - unlike Virginia which was a joint stock company. The king gives land to Lord Baltimore 巴尔的摩勋爵, otherwise known as George Calvert 乔治·卡尔弗特. It's the first proprietor colony. And much like Virginia, tobacco plantations are going to be the thing in Maryland. But unlike Virginia, there was something unique because not only are they there to make money, but they're also there for religious reasons.

An Act of Toleration 宽容法案 is passed in 1649. This guarantees religious freedom 宗教自由 for all Christians, and it's intended specifically to protect Catholics 天主教徒. Catholics were seeking a refuge 避难所 from the hostility of England, and Maryland is going to be intended partially for that purpose. It is important to note that this is one of the first laws granting religious freedom to all Christians in the English colonies. But there are limits to it because it promised death to anyone who denied the divinity of Jesus 否认耶稣神性. So religious freedom did not extend to Jews, Muslims, and other religious groups who were not Christian.

Finally, the other colonies in the South - south of the Chesapeake region - we have North Carolina 北卡罗来纳, South Carolina 南卡罗来纳, and good old Georgia 佐治亚. South Carolina is going to be characterized by a cash crop economy - really rice plantations 水稻种植园 are going to be hugely important here. You're going to get the development of a very wealthy aristocratic elite 富裕的贵族精英, huge plantations, and very important African slave labor. South Carolina is going to be characterized by very long growing seasons 漫长的生长季节, and so plantation economy is going to be very profitable in this region.

North Carolina is going to be very different than South Carolina. It's going to be mainly small tobacco farmers - very similar to Virginia but much more small farming-centered, and there's going to be less of a reliance on slavery than in South Carolina. It's important you know that the British also had colonies in the Caribbean - Barbados 巴巴多斯 and Jamaica 牙买加 are two great examples. And in the Caribbean, they're going to have a very close relationship with South Carolina. They both have these long growing seasons, and they're both going to rely on cash crops and slave labor. In the case of the Caribbean, you're going to see sugar cane production 甘蔗生产 being the major economic enterprise, and they're going to have a very strict slave labor system 严格的奴隶劳动制度 to ensure this remains profitable.

And finally, the last colony to be established will be Georgia in 1733. It's intended to serve as a buffer colony 缓冲殖民地 against Spanish threats in Florida as well as French threats over there in Louisiana. Its original purpose was to serve as a penal colony 流放殖民地 for debtors 债务人 to kind of bring them over to the new world to start over. And originally it banned slavery and the sale of rum 朗姆酒. James Oglethorpe 詹姆斯·奥格尔索普 is one of its key figures early on in its period. He successfully defends the colony against the Spanish, but the problem is nobody really comes because of all these restrictions and the Spanish and French threat. So eventually they drop these restrictions, and in 1752 it becomes a royal colony fully controlled by the British, and it will become a plantation-based slave economy 基于种植园的奴隶经济 much like South Carolina.

That's going to do it for the Southern Colonies. If the video helped you out, click like. If you haven't done so, subscribe to the channel. Make sure you tell all your friends about Joe's Productions. If you have any questions or comments, you can put them in the comment section. And until next time, have a beautiful day. Peace!

'''

== 中文翻译


欢迎来到Joe's Productions的另一个视频。今天我们要看看大约从1588年到1733年的南部殖民地。和往常一样，不管你用哪本AP美国历史教材，这个视频都会帮你掌握所有重要内容。

需要记住的是，**##英国在殖民竞赛中起步较慢。直到1588年击败西班牙无敌舰队后，英国才有足够实力挑战其他国家（特别是西班牙），开始建立殖民地的进程。##英国殖民有许多不同之处，一个重要原因是英国是新教国家。**我们在世界史中学过**宗教改革，英国是新教国家，而西班牙主要是天主教国家。**

**需要了解不同类型的殖民地, 及其运营方式。**例如，1.有股份公司形式，比如伦敦弗吉尼亚公司，#*股东投资公司, 并分担殖民地的盈亏。这也可以称"为公司殖民地"。2.另一种是"领主殖民地"，由国王将土地赐予个人或团体。3.最后是"皇家殖民地"，由君主政体直接出资和统治。*#

英国首次殖民尝试, 并不顺利。1587年沃尔特·雷利爵士在现今北卡罗来纳地区建立的"罗阿诺克殖民地"。实际上，沃尔特·雷利返回欧洲后，当一些人在1590年回来时，发现殖民地已被遗弃。所有男女都不见了。

**#英国在北美殖民的第一个成功, 将发生在切萨皮克地区。#**请务必了解这个地理区域。##**"切萨皮克殖民地"指的是弗吉尼亚, 和马里兰。**##它实际上在上南部地区，你可以在"切萨皮克湾"看到。 +
##**北美第一个永久性英国殖民地, 将于1607年在"詹姆斯敦"建立。其动机是财富。**##国王詹姆斯一世向殖民者颁发特许状，1607年他们建立了"詹姆斯敦"。**#它是在股份公司"伦敦弗吉尼亚公司"下建立的。# **(迪士尼动画片"风中奇缘"里, 提到过弗吉尼亚公司)记住，他们将分担利润和亏损。

**100名男性殖民者来到詹姆斯敦，**经历了饥荒时期。这些人很富有，**他们像西班牙人一样寻找黄金。他们不愿意做艰苦的劳动。**许多最初的殖民者死于疾病和饥饿，因为这片土地炎热、潮湿、蚊虫滋生，殖民者没有准备好应对这种艰苦工作。*幸运的是，#约翰·史密斯到来并建立了军事纪律，拯救了殖民地。他实行"不工作就没饭吃"的政策，殖民地开始稳定。约翰·罗尔夫将在殖民地弗吉尼亚引入烟草种植，为殖民地带来赚钱的东西。#*

那么在殖民地弗吉尼亚的生活是怎样的？**烟草为殖民地提供了经济作物，并导致了种植园制度的兴起。出现了非常大的农场，**你可以在图片中看到烟草。**随着烟草种植，需要廉价劳动力。#在殖民地弗吉尼亚/詹姆斯敦的早期历史中，主要是"契约奴仆"。#**他们将成为弗吉尼亚早期的劳动力。*#契约奴仆基本上服务一段时间，通常是四到七年，以换取前往殖民地的旅费。他们会工作，在服务期满后，理论上他们将获得自由，也许还有一些土地。#*

**为了鼓励这一点，引入了"人头权制度"，如果你支付某人前往殖民地的旅费，就能获得土地。**最终结果是富人变得更富。**富人支付"契约奴仆"前来，并获得越来越多的土地。**可悲的是，*许"多契约奴仆"没能活过契约期限，他们会死去。*

随着殖民地的发展，他们建立了一些政府结构。**#1619年建立了弗吉尼亚议会。这是一种早期的"代议制政府"形式。事实上，这是未来美国的第一个。这种选举产生的代议制政府, 没有出现在法国或西班牙殖民地，所以这是英国殖民地独有的。它开创了自治传统，#**但弗吉尼亚议会, 主要由"富裕的种植园主"组成。

殖民地开始出现问题。**烟草破坏了土地，总是需要越来越多的土地来种植这种作物。随着对土地需求的增加，对劳动力的需求也在增加。随着对土地需求的增加，人们不断向内地、向边疆移动，**正如你在地图上沿詹姆斯河看到的那样。*随着殖民者向西进入美洲原住民的土地，与原住民的紧张关系加剧。这将导致两个重要发展：一是与该地区美洲原住民的关系，二是奴隶制的发展。*

首先：原住民发生了什么？殖民者与波瓦坦部落之间, 形成了非常敌对的关系。**波瓦坦是该地区(切萨皮克)的酋长，切萨皮克地区的所有不同部落, 都在波瓦坦酋长下联合起来。**正如我们已经提到的，随着定居者向西移动，紧张局势加剧。你可以在地图上看到，英国定居点非常接近"波瓦坦联盟"中现有的美洲原住民定居点。

1610年至1646年间将爆发一系列战争。这些统称为"盎格鲁-波瓦坦战争"。第一次战争于1614年, 以波卡洪塔斯和约翰·罗尔夫的婚姻结束。他们看起来完全不是那样。随着弗吉尼亚第一个已知的跨种族结合，*和平是暂时的。英国人和原住民通婚非常罕见。*

**另一场战争将以1622年的大屠杀开始。**波瓦坦联盟在1622年发动攻击，他们厌倦了土地不断被夺取, 和欧洲疾病导致的人口锐减。**1622年的大屠杀导致300多名殖民者死亡，约占人口的三分之一。**战争持续了一段时间，**#到1624年詹姆斯敦成为"皇家殖民地"。伦敦弗吉尼亚公司破产，王室接管了殖民地弗吉尼亚。#**到1646年，波瓦坦联盟基本被击败。他们被击败有多种原因，主要是疾病摧毁了人口，组织混乱（记住**这些部落不同，所以很难建立统一战线**），在英国人眼中他们是可牺牲的，不需要他们，所以要把他们消灭。

需要注意殖民地弗吉尼亚的劳工关系, 和向奴隶制的转变。我们在**早期**已经看到, **主要劳动力来源是"契约奴仆"。**但问题是, **最终这些人活过了契约期限, 并对殖民地提出要求。**第一批非洲人于1619年由一艘荷兰船带入殖民地，但在这个早期阶段，契约奴仆是工人的主体。

那么这种变化是如何发生的？需要记住的一个非常重要的事件是, 1676年的培根起义。培根，这与美味的食物无关。背景是：对土地匮乏的不满日益增长。事实上，许多"契约奴仆"开始活过契约期限，他们想要土地。**殖民地总督伯克利, 不允许渴望土地的定居者向西移动太远。**你可以在地图上看到原因，*部分原因是他想避免与边疆的美洲原住民发生冲突。*

对缺乏政治权力也有不满。记住，弗吉尼亚议会由种植园精英主导。所以许多前契约奴仆在殖民地没有政治或经济机会。最后，他们希望詹姆斯敦的政府，契约奴仆和自由白人，希望詹姆斯敦的政府对边疆的美洲原住民袭击采取行动。伯克利总督不愿这样做，因为他从与边疆美洲原住民的利润丰厚的皮毛贸易中获益。所有这些紧张局势爆发为所谓的培根起义。

起义的领导者是纳撒尼尔·培根。他领导一群人，在边疆反抗印第安人，开始随机、不分青红皂白地杀害据称袭击殖民者的美洲原住民。他们还把不满发泄到詹姆斯敦，烧毁了首府。这是殖民地的一个大危机。纳撒尼尔·培根，我想象他穿着培根覆盖的西装，但对反叛者来说不幸的是，培根突然死于痢疾。起义失败。一些反叛者被绞死，和平回到殖民地。

培根起义的影响将是巨大的。它将导致向非洲奴隶劳工的转变，换句话说，基于种族的奴隶制，个人被视为财产。这个想法是由于多种原因你不能奴役原住民。契约奴仆活过了契约期限并提出要求。然后他们会转向非洲奴隶劳工。培根起义还揭示了殖民地社会中富人与穷人之间以及地区之间的紧张关系，那些在边疆偏远地区的贫穷农民与东部更富裕的潮水区精英之间的对立。

你应该知道的切萨皮克地区的另一个重要殖民地是马里兰。它在弗吉尼亚以北，你可以看到就在切萨皮克湾沿岸。马里兰是一个领主殖民地，不像弗吉尼亚是股份公司。国王将土地赐予巴尔的摩勋爵，也就是乔治·卡尔弗特。这是第一个领主殖民地。和弗吉尼亚很像，烟草种植园将成为马里兰的特色。但与弗吉尼亚不同的是，它有一些独特之处，因为他们不仅是为了赚钱，也是为了宗教原因。

1649年通过了《宽容法案》。这保障了所有基督徒的宗教自由，特别旨在保护天主教徒。天主教徒寻求逃避英国的敌意，马里兰部分就是为了这个目的。需要注意的是，这是英国殖民地中最早授予所有基督徒宗教自由的法律之一。但它有限制，因为它宣布否认耶稣神性的人将被处死。所以宗教自由不适用于犹太人、穆斯林和其他非基督教宗教团体。

最后，南部其他殖民地，切萨皮克地区以南，我们有北卡罗来纳、南卡罗来纳和古老的佐治亚。南卡罗来纳将以经济作物经济为特征，水稻种植园在这里非常重要。你将看到一个非常富有的贵族精英阶层的发展，巨大的种植园，以及非常重要的非洲奴隶劳工。南卡罗来纳的特点是生长季节非常长，所以种植园经济在这个地区非常有利可图。

北卡罗来纳将与南卡罗来纳非常不同。主要是小型烟草农民，与弗吉尼亚非常相似，但更以小农为中心，对奴隶制的依赖比南卡罗来纳少。重要的是要知道英国在加勒比地区也有殖民地，巴巴多斯和牙买加是两个很好的例子。在加勒比地区，它们与南卡罗来纳关系非常密切。它们都有很长的生长季节，都依赖经济作物和奴隶劳动。在加勒比地区，甘蔗生产是主要的经济活动，他们将有一个非常严格的奴隶劳动制度以确保其盈利。

最后，建立的最后一个殖民地是1733年的佐治亚。它旨在作为对抗佛罗里达的西班牙威胁和路易斯安那的法国威胁的缓冲殖民地。最初目的是作为债务人的流放殖民地，把他们带到新世界重新开始。最初禁止奴隶制和朗姆酒销售。詹姆斯·奥格尔索普是其早期的关键人物之一。他成功地保卫了殖民地免受西班牙人侵害，但问题是由于所有这些限制和西班牙与法国的威胁，没有人真正来。所以他们最终取消了这些限制，1752年它成为完全由英国控制的皇家殖民地，并将成为像南卡罗来纳那样的基于种植园的奴隶经济。

关于南部殖民地就到这里。如果视频对你有帮助，请点赞。如果还没有，请订阅频道。确保告诉你的朋友们关于Joe's Productions。如果你有任何问题或意见，可以在评论区留言。下次见，祝你有个美好的一天。再见！

'''

== pure

Welcome to another Joe's Productions video. Today we're taking a look at the Southern Colonies roughly from 1588 to 1733. And as always, no matter which APUSH book you are using, this video is going to help you with all the important content.

So it's important to keep in mind that England is a little bit slow to the colonization game. It wasn't until after England defeats the Spanish Armada in 1588 that England is really in a position of being powerful enough to challenge the other countries, especially Spain, and to begin the process of planting colonies. English colonization is going to be different for a variety of reasons, but one important one to keep in mind is that England was a Protestant country. We learned about in world history the Protestant Reformation, and England was a Protestant country whereas Spain was largely Catholic.

It's important to note the different types of colonies, how they're going to be paid for, and how they are run. For example, you have joint stock companies where stockholders invest in a company such as the Virginia Company of London, and they share in the potential profits or losses from the colony. This can also be referred to as a corporate colony. Another type of colony you're going to see is a proprietorship where land is given by the king to an individual or to a group of individuals. And then finally, a royal colony - it's paid for and ruled directly by the monarchy.

England's first attempt at colonization is not going to go well. The colony of Roanoke under Sir Walter Raleigh in 1587 in what is today North Carolina. In fact, Walter Raleigh goes back to Europe, and when some individuals return in 1590, the colony is found to be deserted. All of the men and women are gone.

England's first success in colonization of North America is going to take place in the Chesapeake. And make sure you know this geographic region. The Chesapeake colonies are going to refer to Virginia and Maryland. It's really in the upper South - you could see that right there in the Chesapeake Bay. And the first permanent English colony in North America will be established at Jamestown in 1607. Its motive was wealth. The king, King James the First, gives a charter to the colonists, and in 1607 they establish Jamestown. It's set up under a joint stock company, the Virginia Company of London. Remember, they're going to share in the profits as well as the losses.

100 male settlers arrive at Jamestown, and they suffer a starving period. These are men who are wealthy - they're looking for gold like the Spanish had achieved. They're not wanting to do all the hard labor. Many of the original settlers die of disease and starvation because the land was hot, humid, mosquito-infested, and the settlers were not prepared for this hard work. Luckily, John Smith comes in and establishes military discipline and saves the colony. He implements a "you don't work, you don't eat" policy, and the colony starts to stabilize. John Rolfe is gonna give the colony something to make money on when he introduces the cultivation of tobacco in colonial Virginia.

So what's life like in colonial Virginia? Tobacco provided the colony with a cash crop and led to the rise of the plantation system. You have the rise of very large farms - you can see tobacco right there in the image. And with the cultivation of tobacco, you need a cheap labor supply. And early on in colonial Virginia/Jamestown's history, it's going to be indentured servants. They are going to serve as the early labor force of Virginia. Indentured servants basically serve for a period of time, usually around four to seven years, in exchange for passage to the colony. They would work, and at the end of their service, in theory, they would be granted their freedom and perhaps some land.

To encourage this, the headright system was introduced where individuals would get land if you paid for somebody's journey to the colony. And what this ends up doing is the rich end up getting richer. The wealthy people are paying for indentured servants to come over and getting more and more land. And the sad part is many indentured servants weren't outliving the terms of their contract - they would die.

As the colony develops, they establish some government structures. The House of Burgesses is established in 1619. This is a form of early representative government. In fact, it's the first in what will be the future United States. This elected representative government didn't happen in French or Spanish colonies, so this is unique to the British colonies. It starts a tradition of self-rule, but the House of Burgesses was largely made up of the wealthy planters.

Problems are going to begin to develop in the colony. Tobacco destroyed the land - it always kind of required more and more land to cultivate this crop. And as the demand for land goes up, so does the demand for labor. And as this demand for land goes up, people keep moving further and further into the interior, into the frontier as you can see on the map along the James River. Tensions increase with the natives as colonists move west into Native American land. And that's going to lead to two important developments: one, the relationship with Native Americans in the region, and the development of slavery.

So first things first: what was going on with the native people? There was a very hostile relationship that developed between the colonists and the Powhatan tribe. Powhatan was the chief in the area, and all the different tribes of the Chesapeake region kind of were lumped together under Chief Powhatan. As we already mentioned, tensions increased as the settlers moved west. You can see on the map the English settlements are very close to existing Native American settlements amongst the Powhatan Confederacy.

A series of wars are going to break out between the years 1610 to 1646. These are collectively known as the Anglo-Powhatan Wars. The first one ends in 1614 with the marriage between Pocahontas and John Rolfe. They looked nothing like that at all. Peace is temporary with this first known interracial union in Virginia. This was very rare for the English and the natives to intermarry.

And another war will begin with the massacre of 1622. Powhatan's Confederacy attacks in 1622, tired of the continual taking of their land and the decimation of their population by European diseases. With the massacre of 1622, over 300 colonists are killed, which is about one-third of the population. The war goes on for a while, and by 1624 Jamestown becomes a royal colony. The Virginia Company of London was bankrupt - the crown takes over colonial Virginia. And by 1646, the Powhatan Confederacy is largely defeated. There's a variety of reasons why they are defeated, and it's largely due to disease which had destroyed the population, disorganization (keep in mind these tribes were different and so it was hard to put up a united front), and they were disposable in the minds of the English - they had no need for them, so they're going to wipe them out.

It's important to note labor relations in colonial Virginia and the transition to slavery. We've already seen in the early period the primary labor source was indentured servants. But the problem was eventually these individuals were outliving their contract and making demands on the colony. The first Africans were brought into the colony in 1619 aboard a Dutch ship, but in this early period, indentured servants were the majority of the workers.

So how does this change take place? Well, a very important event to keep in mind is Bacon's Rebellion. It takes place in 1676. Bacon - and it has nothing to do with the tasty food. Here is the background to it: There was growing frustration with a lack of land. In fact, many of these indentured servants were beginning to outlive the end of their contract, and they wanted land. And Governor Berkeley, the governor of the colony, did not allow land-hungry settlers to move too far west. You can see on the map why - part of the reason is he wants to avoid clashes with Native Americans on the frontier.

There also was frustration with the lack of political power. Remember, the House of Burgesses was dominated by the plantation elite. So many of these former indentured servants had no political or economic opportunities in the colony. And finally, they wanted the government in Jamestown - the indentured servants and the free whites - wanted the government in Jamestown to do something about Native American attacks on the frontier. Governor Berkeley was reluctant to do so because he was benefiting from a lucrative fur trade with Native Americans on the frontier. And all of these tensions erupt into something called Bacon's Rebellion.

The leader of the rebellion is Nathaniel Bacon. He leads a group, a rebellion against the Indians on the frontier where they start randomly, indiscriminately killing Native Americans who had allegedly attacked the colonists. And they also moved their frustrations to Jamestown where they burned down the capital. This is a big crisis in the colony. Nathaniel Bacon - I'd like to think wore this bacon-covered suit - but unfortunately for the rebels, Bacon suddenly dies of dysentery. The rebellion collapses. Some of the rebels are hung, and peace comes to the colony.

The impact of Bacon's Rebellion would be huge. It would lead to a transition to African chattel slave labor - in other words, slavery based upon race where individuals would be considered property. And the idea was you could not enslave the native people for a variety of reasons. Indentured servants were outliving their contracts and demanding things. They'd then switch to African slave labor. Bacon's Rebellion also reveals tensions in colonial society between the wealthy and the poor, as well as regions - those poor farmers out in the frontier in the backcountry versus the more wealthy tidewater elite in the east.

Another important colony in the Chesapeake that you should know about is Maryland. It is north of Virginia - you can see there right along the Chesapeake Bay. Maryland is a proprietorship - unlike Virginia which was a joint stock company. The king gives land to Lord Baltimore, otherwise known as George Calvert. It's the first proprietor colony. And much like Virginia, tobacco plantations are going to be the thing in Maryland. But unlike Virginia, there was something unique because not only are they there to make money, but they're also there for religious reasons.

An Act of Toleration is passed in 1649. This guarantees religious freedom for all Christians, and it's intended specifically to protect Catholics. Catholics were seeking a refuge from the hostility of England, and Maryland is going to be intended partially for that purpose. It is important to note that this is one of the first laws granting religious freedom to all Christians in the English colonies. But there are limits to it because it promised death to anyone who denied the divinity of Jesus. So religious freedom did not extend to Jews, Muslims, and other religious groups who were not Christian.

Finally, the other colonies in the South - south of the Chesapeake region - we have North Carolina, South Carolina, and good old Georgia. South Carolina is going to be characterized by a cash crop economy - really rice plantations are going to be hugely important here. You're going to get the development of a very wealthy aristocratic elite, huge plantations, and very important African slave labor. South Carolina is going to be characterized by very long growing seasons, and so plantation economy is going to be very profitable in this region.

North Carolina is going to be very different than South Carolina. It's going to be mainly small tobacco farmers - very similar to Virginia but much more small farming-centered, and there's going to be less of a reliance on slavery than in South Carolina. It's important you know that the British also had colonies in the Caribbean - Barbados and Jamaica are two great examples. And in the Caribbean, they're going to have a very close relationship with South Carolina. They both have these long growing seasons, and they're both going to rely on cash crops and slave labor. In the case of the Caribbean, you're going to see sugar cane production being the major economic enterprise, and they're going to have a very strict slave labor system to ensure this remains profitable.

And finally, the last colony to be established will be Georgia in 1733. It's intended to serve as a buffer colony against Spanish threats in Florida as well as French threats over there in Louisiana. Its original purpose was to serve as a penal colony for debtors to kind of bring them over to the new world to start over. And originally it banned slavery and the sale of rum. James Oglethorpe is one of its key figures early on in its period. He successfully defends the colony against the Spanish, but the problem is nobody really comes because of all these restrictions and the Spanish and French threat. So eventually they drop these restrictions, and in 1752 it becomes a royal colony fully controlled by the British, and it will become a plantation-based slave economy much like South Carolina.

That's going to do it for the Southern Colonies. If the video helped you out, click like. If you haven't done so, subscribe to the channel. Make sure you tell all your friends about Joe's Productions. If you have any questions or comments, you can put them in the comment section. And until next time, have a beautiful day. Peace!