
= American Pageant - 027 (1890-1912)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Good day APUSH people. Today we're taking a look at the Progressive Movement 进步运动 roughly from 1890 to around 1912. This video is going to help you out 帮助你 with pretty much any APUSH textbook -- that's how the video lines up to 与……相符 some of the popular ones. Let's get started.

The Progressive Movement -- why does it take place 发生? Big important concept to understand: industrialization 工业化, urbanization 城市化 and immigration 移民 created significant changes -- a lot of them good but also some challenges for the United States. And the Progressive Movement was an effort to use government power to regulate 监管；调控 and improve society 改善社会. So this is a whole movement trying to improve society. It is a rejection of 拒绝；摒弃 the laissez-faire ideology 自由放任主义思想 of much of the Gilded Age 镀金时代 -- this idea that the government should not get involved 干预；介入 is rejected by many progressive reformers 进步改革者.

It's important to keep in mind it's not a radical movement 激进运动. They're not looking to overturn or overthrow capitalism 推翻资本主义. They're rejecting radical ideas like socialism 社会主义 and anarchism 无政府主义. They want to save and improve capitalism 拯救并改善资本主义. They want to make it more of a just society 公正的社会.

Who are the progressives 进步人士? This is a complicated question because many of the Progressive Era reformers 进步时代改革者 were middle class men and women, but there's a real diverse group of people 各种各样的人. The Progressive Movement was not a coherent organized movement 协调一致的有组织的运动 -- everyone working together for common goals 为共同目标而协作. So for instance you have Protestant church leaders 新教教会领袖 demanding temperance 戒酒；禁酒 or getting people to stop drinking. You have politicians regulating monopolies and trusts 垄断企业和托拉斯 -- they're part of the Progressive Movement. Union leaders 工会领袖 addressing the rights of workers 处理工人权利问题. Women demanding the right to vote 选举权. African-Americans demanding greater equality 平等. All of these are going on during the Progressive Movement, and it's really important you understand it's a diverse group of reformers.

And then finally it's important when you're studying for APUSH that you compare this to other reform periods -- back under the age of Jackson Andrew Jackson, the Populist reforms 民粹主义改革 of the farmers, and then later in the 1930s the New Deal 新政.

So how do you promote reform 推动改革? And that's where the muckrakers 黑幕揭发者 come into play 发挥作用. Muckrakers attempted to expose problems 揭露问题 in American society, and they write their very often journalistic pieces 新闻作品. They're writing very sensationalistic stories 耸人听闻的故事. They want to stir up public demand for action 激起公众的行动需求. They want to bring the problem to the attention of the middle classes 引起中产阶级的关注. They actually get the name from Theodore Roosevelt -- he did not mean it as a compliment 赞美；称赞.

And there's a whole bunch of examples you're going to come across 遇到 when you're reading about this time period. Ida Tarbell wrote A History of Standard Oil Company published in McClure's magazine 麦克卢尔杂志 -- a popular magazine at the time -- in which she exposed the kind of business practices utilized by these captains of industry 工业大亨 such as John D. Rockefeller 约翰·D·洛克菲勒. Jacob Riis 雅各布·里斯 is often times considered one of the first muckrakers with his How the Other Half Lives 《另一半人怎样生活》 in which he exposed the horrors of life in the slums of New York 在纽约贫民窟的生活惨状 in 1890. Lincoln Steffens 林肯·斯蒂芬斯 wrote a book called The Shame of the Cities 《城市的耻辱》 in 1904 which exposed the corruption 腐败 in city politics with the political machines 政治集团. And of course the one a lot of people know about -- Upton Sinclair's 《丛林》The Jungle. More on him a little later.

Another key thing about the Progressive Movement is the importance of women in the movement. Women played an important role in the Progressive Movement, and this really gave them an opportunity to break down the idea of the separate spheres  separate spheres：“领域分离”观念，即认为女性应局限于家庭领域  which was this idea that a woman's place was in the home. You know if you remember after the American Revolution this idea of Republican Motherhood 共和母亲理念 -- raising young boys mainly to be good citizens. Women did not have the right to vote, and yet during the Progressive Movement they're playing an active role in causes such as child labor 童工问题.

The National Child Labor Committee 全国童工委员会 fought for laws banning child labor 禁止童工的法律, and by 1907 about two-thirds of all states will have child labor laws put into place 实施. You have the National Consumers League 全国消费者联盟 which was headed by Florence Kelley 弗洛伦斯·凯利. Kelley remember was very active in the settlement house movement 定居点运动 with Jane Addams 简·亚当斯, and the National Consumers League advocated for 倡导；支持 the rights of women in the workplace along with against child labor and all sorts of other causes.

A court case you should be aware of is Muller v. Oregon 穆勒诉俄勒冈州案 in 1908. The Court ruled that laws protecting women workers that restricted women to 10-hour work days 限制女性每天工作10小时 were constitutional 合宪的, and the court rules that women deserved and needed special protections as women in the workplace.

An event that really kind of stimulates a lot of activism 激发大量行动 amongst women and workers is the Triangle Shirtwaist Fire 三角内衣厂火灾 in 1911. A 10-story building in New York -- a fire breaks out 爆发；发生 leading to the death of 146 workers -- most of them being women and immigrants. And this really sparks reforms 引发改革 and calls for increased safety standards 提高安全标准的呼吁. And another reform that we're going to take a look at in just a moment is women in the temperance movement 禁酒运动.

Important idea to keep in mind though is women are playing various roles in the Progressive Movement, and one of those which we're going to cover in our next video is the role of the woman's suffrage movement 妇女选举权运动.

Urban reform 城市改革 was a huge part of the Progressive Movement. If you recall throughout the Gilded Age people have been moving to the cities, and this creates all sorts of problems. Amongst those problems are urban poverty 城市贫困 and the rise of tenements 廉价公寓 and slums 贫民窟. You have political corruptions 政治腐败 and political machines 政治集团. And widespread alcoholism 酗酒 and all sorts of other issues in the cities. And we've already seen what Jane Addams and Florence Kelley and others were doing in places like Chicago with the settlement house movement trying to help people like you see in the image get out of urban poverty.

But you also see a desire during the Progressive Movement to take away power from political bosses 政治老板 by placing municipal services 市政服务 under public control 公共管理. Sanitation 卫生设施 was a huge problem in the cities, and one of the ways they felt they would be able to do this was by municipal government reform 市政府改革 such as voters electing the heads of city departments such as fire, police and sanitation so that things would be more efficient 高效的 and less corrupt 腐败的.

Progressive reformers also focus on state reform 州级改革. You get many progressive governors 进步州长 fighting against corporate control of state politics 企业对州政治的控制. In California you have Governor Hiram Johnson 希拉姆·约翰逊州长 who took on 对抗；对付 the very powerful Southern Pacific Railroad 南太平洋铁路公司. The big guy though is this handsome fellow Governor Robert La Follette 罗伯特·拉福莱特州长 of Wisconsin 威斯康星州, and he's going to pioneer many reforms in the state of Wisconsin. And really kind of the reform movements in Wisconsin become known as the Wisconsin Idea 威斯康星理念. And you could see him fighting -- showing what he's going to do to these big bad businesses 大型不良企业. He's going to regulate the public utilities 公用事业. He's going to take on the powerful railroad industry 强大的铁路行业. He's going to adopt many tax reforms 税收改革 and a whole bunch of political reforms 政治改革 which are going to be copied and utilized in other states.

So let's take a look at the political reforms 政治改革 of the Progressive Movement. There was this interest and this idea amongst progressives political reformers -- they wanted to increase democracy 民主 and reduce the control of trusts 托拉斯. The problem was the power of political machines and trusts and money was eroding Americans' faith in politics 削弱美国人对政治的信心. You can see that in this political cartoon 政治漫画 in which the trusts have taken over the Senate 参议院.

And so here's some of the things that were done in states such as Wisconsin. You have the Australian or secret ballot 澳大利亚式秘密投票法 which allowed voters to mark their choice for office secretly 秘密标记选票 so they would not be intimidated into voting for certain candidates 因受胁迫而投票给某些候选人 which was often done. The direct primary 直接初选 in which the nomination of candidates 候选人提名 placed into the hands of the voters 交由选民决定 -- so the voters would actually select who would be the candidate for the party. The recall 罢免权 allowed elected politicians they could be removed from office 被免职 by the voters before their term expired 任期结束前 -- so if they weren't doing a good job or if they were corrupt they can be removed in a special election 特别选举. The initiative 创制权 allowed voters could introduce laws 提出法律议案. And the referendum 公投权 allowed voters to directly vote on a law 直接对法律进行投票表决.

And the big amendment 修正案 that takes place -- one of the big amendments is the 17th Amendment 第十七条修正案. And this one's important because rather than the state legislature 州立法机构, voters would directly vote for US senators 美国参议员. So this would bring more democracy into American politics it was felt. And remember the Populist Party 民粹党 advocated for this in the 1890s -- it becomes reality with the 17th Amendment.

There also were some moralistic aspects 道德层面 to the Progressive Movement. Remember it was a very diverse set of reforms 多样化的改革, and there was all sorts of division 分歧 over the temperance movement 禁酒运动. Those in favor of drinking were known as wet 支持饮酒者 -- they were against prohibition 禁酒. Those who wanted to support temperance and prohibition -- the banning of alcohol legally banning alcohol -- were known as dry 禁酒主义者. And there was a growing conflict 冲突 between those two groups.

And it really came down to 归结为 Protestant native-born Americans very often versus Catholic immigrants 天主教移民. Catholic immigrants tended to be okay with drinking -- especially those so-called new immigrants from Southern and Eastern European countries. Very often there was division between rural areas 农村地区 which tended to be much more pro-temperance prohibition supporters 支持禁酒者 whereas in the cities they tended to be more of a support for allowing people to do what they wanted to do.

There were organizations that were created. You have the Women's Christian Temperance Union 基督教妇女禁酒联合会 -- a large organization of women advocating for temperance. They would encourage their members to take pledges 发誓 promising not to drink any longer. And the big one is in 1895 the Anti-Saloon League 反酒馆联盟 which was the leading organization advocating for legal prohibition 合法禁酒. They don't just want you to promise to not drink -- they want to get a law passed which would make it illegal to do so. And many states started adopting prohibition type laws 禁酒类法律. And of course in 1919 we'll see the 18th Amendment 第十八条修正案 go into place 生效 banning alcohol throughout the country.

Now a big moment in the Progressive Movement comes with the emergence of Theodore Roosevelt 西奥多·罗斯福 as president at the age of 42 years old. And once again Roosevelt is a firm believer in 坚信 an enlarged role for the president, and he's going to do things very differently. And one of those you can see in his labor policy 劳工政策 and his relationship with organized labor 有组织的劳工 and workers. And little kind of memory lane 回忆往事 right here -- remember McKinley during the Great Railroad Strike of 1877 sided with corporations 站在企业一边. Grover Cleveland during the Pullman Strike in 1894 also sided against organized labor 反对有组织的劳工.

And Theodore Roosevelt very very early on in his presidency was faced with a massive strike 大规模罢工 by the coal miners 煤矿工人 in 1902, and he actually tries to mediate the labor dispute 调解劳资纠纷 between management and the workers. And owners won't compromise 妥协, so Theodore Roosevelt threatens to take over the mines 接管煤矿 with federal troops 联邦军队. And this is a very big difference than previous presidents -- especially during the Gilded Age were very often the federal government was using troops against the workers.

Now Roosevelt himself was not necessarily Mr. Pro-labor union 支持工会的人. He believed in something what he referred to as the Square Deal 公平交易, and this was his Progressive Era reform program 进步时代改革计划. And there's three parts to it -- the three C's: corporations there should be control of corporations 控制企业; consumers there should be consumer protection 消费者保护; and conservation 资源保护 -- conservation of the environment and the Earth's natural resources 保护地球自然资源. So this is part of his Square Deal program.

For the APUSH exam it's really important you know about Roosevelt's program -- his Progressive Era policies 进步时代政策. And let's take a look at them. First -- corporations trust busting 反垄断. Roosevelt looked at things like the Sherman Antitrust Act 谢尔曼反托拉斯法 -- remember that was passed in 1890 -- and he realized it was relatively ineffective 无效的 at reducing the power of corporations and trusts. Remember in fact it was often times used against labor unions 工会. Roosevelt's going to change this. He's going to break up 解散 the Northern Securities Company 北方证券公司 -- a railroad monopoly 铁路垄断企业 with tremendous power 巨大权力. In fact Roosevelt his actions are upheld by the Supreme Court 最高法院 in 1904, and he is going to be very famously known for his trust busting 反垄断 during his presidency. He's going to bring on antitrust action 反垄断行动 against 40 corporations.

And Roosevelt distinguished between 区分 good and bad trusts. And good trusts were trusts that were efficient 高效的 and brought lower prices to consumers -- they weren't harmful to the economy 对经济无害. And bad trusts were harmful because they crushed competition 扼杀竞争 and they hurt consumers by dominating and fixing prices 垄断和操纵价格. And throughout his presidency he's going to increase the power of the federal government with regard to business 商业方面.

Another example of this is Roosevelt will also seek to increase the power of the Interstate Commerce Commission 州际商务委员会 -- remember that was intended to regulate railroad rates across state lines 州际铁路运费. It was also relatively weak throughout much of the Gilded Age. Couple of examples of how that power is increased -- you see that in the Elkins Act of 1903 1903年埃尔金斯法案. It increased the penalties 处罚；惩罚 for rate rebates 运费回扣 that railroad companies would try to get away with 试图逃避惩罚. And the Hepburn Act of 1906 1906年赫伯恩法案 gave the ICC the power to set maximum rates 设定最高费率 for the railroad companies.

So big idea here is Roosevelt is using the power of the federal government -- the presidency 总统职权 -- to control and regulate corporations and strengthening previous laws such as the Sherman Antitrust Act and the Interstate Commerce Act 州际商务法.

The other C -- the second one is consumer protections 消费者保护. Remember at this time it's a laissez-faire attitude 自由放任态度 with the economy, and there are relatively few protections for consumers. It was very common for food to be bad and people to get ill or die from it and medicine and other items to be mislabeled 贴错标签. Upton Sinclair's book The Jungle was intended -- Upton Sinclair was a muckraker and his intention was to increase support for socialism and workers' rights by writing this book about the life for a worker in the Chicago stockyards 芝加哥肉类加工场. What ends up happening though is the public focuses on the unsanitary nature 不卫生状况 of the meat industry that Sinclair writes about, and there's a huge outcry 强烈抗议 with regard to the conditions of the meat in this factory that Sinclair writes about.

There's a lot of public pressure for Theodore Roosevelt to act, and as a result of Sinclair's muckraking activity 黑幕揭发行为 the Meat Inspection Act of 1906 1906年肉类检验法 is passed which basically says the federal government would regulate and inspect the meat industry 监管和检验肉类行业. And you see the federal government employee checking that good old tasty carne asada 烤肉 out. Another significant law for consumer protection is the Pure Food and Drug Act 纯净食品和药品法 passed the same year, and this creates the FDA -- the Food and Drug Administration 食品药品监督管理局. And the FDA protected the public against the manufacture sale and transportation of mislabeled food and drugs 防止生产、销售和运输贴错标签的食品和药品. So people the public would have a right to know what's in the food and the drugs that they're purchasing 购买的食品和药品成分. So next time you eat your hot Cheetos 奇多辣味零食 you know exactly how you're killing yourself.

The third C is conservation 资源保护, and this is Roosevelt's big win domestically 国内的重大胜利. It's important to keep in mind the issue of conservation did not register as a national issue 未被视为全国性问题 -- people weren't talking about the environment as a big pressing problem 紧迫问题. And there were some groups such as the Sierra Club 塞拉俱乐部 which was founded in 1892 -- John Muir 约翰·缪尔 was a significant part of that movement advocating for the environment 倡导环境保护. But Roosevelt and working together -- there he is with John Muir -- is going to use the power of the government to protect the environment.

Roosevelt's going to use the Forest Reserve Act 森林保护区法案 which was passed in 1891 to protect 150 million acres of federal land 1.5亿英亩的联邦土地. And the Newlands Reclamation Act of 1902 1902年纽兰兹开垦法案 -- money from sale of public lands could be used for irrigation projects 灌溉项目 in the west. So you have this kind of conservation and protection of the Earth's natural resources 地球自然资源. And if you take a look at that map right there you can see some of the areas protected by Roosevelt.

One important thing to keep in mind is the contrast 对比；差异 those two words -- conservation versus preservation 保护（合理利用）与保存（维持原状）. Conservation is the planned regulated use of the environment 有计划的环境调控利用 whereas preservationist 自然保护主义者 -- which is what John Muir was -- was leaving nature alone just to be preserved in its natural state 让自然保持原始状态. And there was a big battle over the Hetch Hetchy project 赫奇赫奇山谷项目 near San Francisco in which preservationists lost -- in the Hetch Hetchy project the dam was built altering the physical environment of that region 改变该地区的自然环境.

Roosevelt serves until 1908, and he decides that he's going to honor the precedent 先例 of George Washington and he's not going to seek a third term 寻求第三届任期 even though he could have. And he hands over kind of the Republican Party leadership 共和党领导权 to the big guy over 300 pounds -- there's his bathtub -- William Howard Taft 威廉·霍华德·塔夫脱. And Taft is going to continue some of the progressive policies 进步政策 of Roosevelt. He's actually going to break up more trusts than Roosevelt -- little fun fact there most people think Roosevelt trustbuster 反垄断者 -- Taft broke more of them. And he's going to continue some of conservationist policies 保护主义政策 as well.

And when it comes to foreign policy 外交政策 Taft differs from Roosevelt's big stick foreign policy 大棒外交政策, and he favors something called Dollar Diplomacy 金元外交 in which he encouraged businesses to invest money -- private financial investments 私人金融投资 -- in areas of strategic concerns of the United States 美国战略利益地区. And the idea would be that this would lead to greater stability 带来更大的稳定 and would promote US interests 促进美国利益 without using force 不使用武力.

However when the election of 1912 comes up Roosevelt and Taft are going to be running against each other 相互竞争, but we're going to save that for another day another time. Thank you for watching. If the video helped you out click like 点赞. Have questions post a comment 发表评论. Peace.

'''


== 中文翻译

各位APUSH的同学们，大家好！今天我们要探讨进步运动，大致从1890年到1912年左右。这段视频将帮助你们理解几乎所有的APUSH教材——视频内容与一些流行的教材都有对应。让我们开始吧。

进步运动——它为什么会发生？理解一个重要的概念：工业化、城市化和移民带来了显著的变化——其中许多是好的，但也给美国带来了一些挑战。进步运动是利用政府力量来规范和改善社会的一种努力。这是一个旨在改善社会的整体运动。它否定了镀金时代大部分时期的自由放任思想——许多进步改革家都反对政府不应干预的这种观点。

重要的是要记住，这不是一场激进的运动。他们不是要推翻或颠覆资本主义。他们拒绝社会主义和无政府主义等激进思想。他们想要拯救和改善资本主义。他们想要使之成为一个更加公正的社会。

谁是进步人士？这是一个复杂的问题，因为许多进步时代的改革家是中产阶级的男男女女，但这是一个真正多元化的群体。进步运动不是一个有凝聚力的有组织的运动——并非所有人都为了共同的目标而共同努力。例如，你们有新教教会领袖要求禁酒或让人们停止饮酒。你们有政治家监管垄断和托拉斯——他们是进步运动的一部分。工会领袖关注工人的权利。妇女要求选举权。非裔美国人要求更大的平等。所有这些都在进步运动期间发生，理解这是一个多元化的改革者群体非常重要。

最后，当你们为APUSH考试学习时，将此与其他的改革时期进行比较是很重要的——回到安德鲁·杰克逊时代的杰克逊式民主时期，农民的民粹主义改革，以及后来的1930年代的新政。

那么如何促进改革呢？这就是扒粪运动发挥作用的地方。扒粪者试图揭露美国社会的问题，他们经常撰写新闻报道。他们写的故事非常耸人听闻。他们想要激起公众对采取行动的需求。他们想要引起中产阶级对这些问题的关注。这个名字实际上是西奥多·罗斯福起的——他并非出于赞美。

当你们阅读这一时期时，会遇到很多例子。艾达·塔贝尔在当时颇受欢迎的《麦克卢尔》杂志上发表了《标准石油公司史》，她在书中揭露了像约翰·D·洛克菲勒这样的产业巨头所采用的商业手段。雅各布·里斯通常被认为是早期的扒粪者之一，他的《另一半是如何生活的》在1890年揭露了纽约贫民窟生活的恐怖。林肯·斯蒂芬斯在1904年写了一本名为《城市的耻辱》的书，揭露了城市政治中政治机器的腐败。当然，很多人都知道的是厄普顿·辛克莱的《屠场》。稍后会详细介绍他。

进步运动的另一个关键是妇女在运动中的重要性。妇女在进步运动中发挥了重要作用，这确实给了她们打破“分离领域”观念的机会，“分离领域”是指妇女的地位在家庭中的这种观念。你们如果还记得美国革命之后出现的“共和母亲”的思想——主要是培养年轻男孩成为好公民。妇女没有选举权，但在进步运动期间，她们在诸如童工等事业中发挥着积极作用。

全国童工委员会争取禁止童工的法律，到1907年，大约三分之二的州都将制定童工法。你们有由弗洛伦斯·凯利领导的全国消费者联盟。记住，凯利曾与简·亚当斯一起在定居所运动中非常活跃，全国消费者联盟倡导妇女在工作场所的权利，反对童工以及各种其他事业。

你们应该了解的一个法院案例是1908年的《米勒诉俄勒冈州案》。法院裁定，保护女工、限制女性每天工作10小时的法律是合宪的，法院裁定女性在工作场所作为女性应该并且需要特殊的保护。

1911年的三角服装厂火灾真正激发了妇女和工人中的许多积极分子。纽约一座10层高的建筑发生火灾，导致146名工人死亡——其中大多数是妇女和移民。这真正引发了改革，并呼吁提高安全标准。我们稍后将看到的另一项改革是妇女在禁酒运动中的作用。

然而，需要记住的重要一点是，妇女在进步运动中扮演着各种各样的角色，其中之一我们将在下一段视频中介绍，那就是妇女选举权运动的作用。

城市改革是进步运动的重要组成部分。如果你们还记得，在整个镀金时代，人们一直在涌向城市，这造成了各种各样的问题。这些问题包括城市贫困和贫民窟的兴起。存在政治腐败和政治机器。以及城市中普遍存在的酗酒和其他各种问题。我们已经看到简·亚当斯、弗洛伦斯·凯利和其他人在芝加哥等地的定居所运动中所做的工作，试图帮助像图片中看到的那样的人们摆脱城市贫困。

但你们也看到了进步运动期间的一种愿望，那就是通过将市政服务置于公共控制之下，来剥夺政治老板的权力。卫生是城市中一个巨大的问题，他们认为能够做到这一点的方法之一是通过市政政府改革，例如选民选举消防、警察和卫生等城市部门的负责人，以便事情更加高效和减少腐败。

进步改革家也关注州一级的改革。许多进步州长都在与企业对州政治的控制作斗争。在加利福尼亚州，你们有州长海勒姆·约翰逊，他对抗了势力强大的南太平洋铁路公司。但真正的大人物是这位英俊的威斯康星州州长罗伯特·拉福莱特，他将在威斯康星州率先进行许多改革。实际上，威斯康星州的改革运动被称为“威斯康星理念”。你们可以看到他正在战斗——展示他将如何对付这些坏企业。他将监管公共事业。他将对抗强大的铁路行业。他将采纳许多税收改革和大量的政治改革，这些改革将被其他州效仿和采用。

因此，让我们看看进步运动的政治改革。进步政治改革家们普遍存在着一种兴趣和想法——他们想要增加民主，减少托拉斯的控制。问题是政治机器、托拉斯和金钱的力量正在侵蚀美国人民对政治的信任。你们可以在这幅政治漫画中看到，托拉斯已经控制了参议院。

因此，以下是在威斯康星州等州所做的一些事情。你们有澳大利亚式或秘密投票，允许选民秘密地标记他们对职位的选择，这样他们就不会像过去经常发生的那样，受到胁迫而投票给某些候选人。直接初选，将候选人的提名权交到选民手中——因此选民实际上会选择谁将成为该党的候选人。罢免允许选民在当选官员任期届满前将其免职——因此，如果他们工作不力或腐败，可以通过特别选举将其罢免。创制允许选民提出法律。复决允许选民直接对一项法律进行投票。

发生的一个重大修正案——其中一个重大修正案是第十七修正案。这项修正案很重要，因为它规定选民将直接投票选举美国参议员，而不是由州议会选举。人们认为这将给美国政治带来更多的民主。记住，人民党在1890年代就倡导这一点——它通过第十七修正案成为现实。

进步运动也存在一些道德主义的方面。记住，这是一系列非常多样化的改革，在禁酒运动中存在各种各样的分歧。赞成饮酒的人被称为“湿派”——他们反对禁酒。那些想要支持节制和禁酒——合法禁止酒精——的人被称为“干派”。这两派之间存在着日益增长的冲突。

这实际上归结为新教本土美国人与天主教移民之间的冲突。天主教移民往往可以接受饮酒——特别是那些来自南欧和东欧国家的所谓“新移民”。农村地区往往更加支持禁酒，而城市地区则更倾向于允许人们做自己想做的事情，这两者之间往往存在分歧。

成立了一些组织。你们有妇女基督教禁酒联盟——一个倡导禁酒的大型妇女组织。他们会鼓励其成员做出不再饮酒的承诺。而最重要的是1895年成立的反酒吧联盟，这是倡导合法禁酒的主要组织。他们不仅希望你承诺不再饮酒——他们还想通过一项法律，使饮酒成为非法行为。许多州开始采纳禁酒类型的法律。当然，在1919年，我们将看到第十八修正案生效，在全国范围内禁止酒精。

进步运动的一个重要时刻是西奥多·罗斯福以42岁的年龄成为总统。再一次，罗斯福坚信总统应该发挥更大的作用，他将采取非常不同的做法。其中之一你们可以在他的劳工政策以及他与有组织的劳工和工人之间的关系中看到。稍微回顾一下——记住，在1877年的大铁路罢工期间，麦金利站在了企业一边。1894年普尔曼罢工期间，格罗弗·克利夫兰也反对有组织的劳工。

西奥多·罗斯福在他总统任期的早期就面临着1902年煤矿工人的一次大规模罢工，他实际上试图调解劳资双方之间的纠纷。由于业主不肯妥协，西奥多·罗斯福威胁要用联邦军队接管矿井。这与之前的总统有很大的不同——尤其是在镀金时代，联邦政府经常使用军队对付工人。

罗斯福本人并不一定是一位亲工会人士。他信奉他所谓的“公平交易”，这是他的进步时代改革计划。它有三个部分——三个“C”：企业（Corporations），应该对企业进行控制；消费者（Consumers），应该保护消费者；保护（Conservation），保护环境和地球的自然资源。这是他的“公平交易”计划的一部分。

对于APUSH考试来说，了解罗斯福的计划——他的进步时代政策——非常重要。让我们来看看它们。首先——企业，打击托拉斯。罗斯福审视了《谢尔曼反托拉斯法》（记住那是1890年通过的），他意识到它在削弱企业和托拉斯的力量方面相对无效。记住，事实上它经常被用来对付工会。罗斯福将改变这一点。他将解散北方证券公司——一个拥有巨大权力的铁路垄断企业。事实上，罗斯福的行动在1904年得到了最高法院的支持，他将因其总统任期内的“托拉斯破坏者”而闻名。他将对40家公司提起反托拉斯诉讼。

罗斯福区分了好托拉斯和坏托拉斯。好托拉斯是那些高效并为消费者带来更低价格的托拉斯——它们对经济没有害处。而坏托拉斯是有害的，因为它们扼杀了竞争，并通过垄断和固定价格损害了消费者。在他的整个总统任期内，他将增加联邦政府在商业方面的权力。

这方面的另一个例子是，罗斯福还将寻求增加州际商务委员会（记住，其目的是监管跨州铁路运费）的权力。在镀金时代的大部分时间里，它也相对较弱。增加这种权力的几个例子——你们可以在1903年的《埃尔金斯法案》中看到这一点。它增加了对铁路公司试图逃避的运费回扣的处罚。1906年的《赫本法案》赋予州际商务委员会设定铁路公司最高运费的权力。

因此，这里的核心思想是，罗斯福正在利用联邦政府——总统——的权力来控制和监管企业，并加强之前的法律，如《谢尔曼反托拉斯法》和《州际商务法》。

另一个“C”——第二个是消费者保护。记住，当时经济上是自由放任的态度，对消费者的保护相对较少。食物变质导致人们生病或死亡，以及药品和其他物品被贴错标签非常普遍。厄普顿·辛克莱的书《屠场》的目的是——厄普顿·辛克莱是一位扒粪者，他的目的是通过写这本关于芝加哥牲畜屠宰场工人生活的书来增加对社会主义和工人权利的支持。然而，最终发生的是公众关注辛克莱所写的肉类工业的肮脏性质，对于辛克莱所写的这家工厂的肉类状况，公众强烈抗议。

公众强烈要求西奥多·罗斯福采取行动，结果，由于辛克莱的扒粪活动，1906年通过了《肉类检验法》，该法案基本上规定联邦政府将监管和检查肉类工业。你们可以看到联邦政府雇员正在检查那美味的烤肉卷饼。另一项重要的消费者保护法是同年通过的《纯净食品和药品法》，该法案创建了FDA——食品和药物管理局。FDA保护公众免受贴错标签的食品和药品的生产、销售和运输。因此，公众有权知道他们购买的食品和药品中含有什么。所以下次你们吃你们的辣芝士条时，你们就知道你们是如何慢慢“杀死”自己的了。

第三个“C”是保护（Conservation），这是罗斯福在国内取得的重大胜利。重要的是要记住，保护问题并没有成为一个全国性的问题——人们并没有将环境视为一个紧迫的大问题。有一些团体，如1892年成立的塞拉俱乐部——约翰·缪尔是该运动的重要组成部分，倡导环境保护。但罗斯福和他们一起努力——他和约翰·缪尔在一起——将利用政府的力量来保护环境。

罗斯福将利用1891年通过的《森林保护区法》来保护1.5亿英亩的联邦土地。1902年的《新lands垦荒法》规定，出售公共土地所得的资金可用于西部的灌溉项目。因此，你们看到了这种对地球自然资源的保护。如果你们看一下那张地图，你们可以看到罗斯福保护的一些区域。

需要记住的一个重要区别是这两个词——保护（conservation）与保存（preservation）。保护是对环境的有计划的、受管制的利用，而保存主义者——约翰·缪尔就是这样的人——则是让自然保持原样，仅仅是为了以其自然状态保存下来。在旧金山附近的赫奇赫奇项目上发生了一场激烈的战斗，保存主义者失败了——在赫奇赫奇项目中，修建了大坝，改变了该地区的自然环境。

罗斯福一直任职到1908年，他决定尊重乔治·华盛顿的先例，即使他可以连任，他也不会寻求第三个任期。他将共和党的领导权交给了这位体重超过300磅的大块头——这是他的浴缸——威廉·霍华德·塔夫脱。塔夫脱将继续罗斯福的一些进步政策。他实际上比罗斯福解散了更多的托拉斯——一个小趣闻，大多数人认为罗斯福是托拉斯破坏者——塔夫脱解散的更多。他还将继续一些保护政策。

在外交政策方面，塔夫脱与罗斯福的“大棒政策”不同，他倾向于一种叫做“金元外交”的政策，鼓励企业在美国具有战略意义的地区进行投资——私人金融投资。其想法是，这将导致更大的稳定，并在不使用武力的情况下促进美国的利益。

然而，当1912年大选来临时，罗斯福和塔夫脱将相互竞争，但我们将把这个问题留到以后再讨论。感谢观看。如果这个视频对你有帮助，请点赞。有问题请在评论中提问。再见。


'''


== pure

Good day APUSH people. Today we're taking a look at the Progressive Movement roughly from 1890 to around 1912. This video is going to help you out with pretty much any APUSH textbook -- that's how the video lines up to some of the popular ones. Let's get started.

The Progressive Movement -- why does it take place? Big important concept to understand: industrialization, urbanization and immigration created significant changes -- a lot of them good but also some challenges for the United States. And the Progressive Movement was an effort to use government power to regulate and improve society. So this is a whole movement trying to improve society. It is a rejection of the laissez-faire ideology of much of the Gilded Age -- this idea that the government should not get involved is rejected by many progressive reformers.

It's important to keep in mind it's not a radical movement. They're not looking to overturn or overthrow capitalism. They're rejecting radical ideas like socialism and anarchism. They want to save and improve capitalism. They want to make it more of a just society.

Who are the progressives? This is a complicated question because many of the Progressive Era reformers were middle class men and women, but there's a real diverse group of people. The Progressive Movement was not a coherent organized movement -- everyone working together for common goals. So for instance you have Protestant church leaders demanding temperance or getting people to stop drinking. You have politicians regulating monopolies and trusts -- they're part of the Progressive Movement. Union leaders addressing the rights of workers. Women demanding the right to vote. African-Americans demanding greater equality. All of these are going on during the Progressive Movement, and it's really important you understand it's a diverse group of reformers.

And then finally it's important when you're studying for APUSH that you compare this to other reform periods -- back under the age of Jackson Andrew Jackson, the Populist reforms of the farmers, and then later in the 1930s the New Deal.

So how do you promote reform? And that's where the muckrakers come into play. Muckrakers attempted to expose problems in American society, and they write their very often journalistic pieces. They're writing very sensationalistic stories. They want to stir up public demand for action. They want to bring the problem to the attention of the middle classes. They actually get the name from Theodore Roosevelt -- he did not mean it as a compliment.

And there's a whole bunch of examples you're going to come across when you're reading about this time period. Ida Tarbell wrote A History of Standard Oil Company published in McClure's magazine -- a popular magazine at the time -- in which she exposed the kind of business practices utilized by these captains of industry such as John D. Rockefeller. Jacob Riis is often times considered one of the first muckrakers with his How the Other Half Lives in which he exposed the horrors of life in the slums of New York in 1890. Lincoln Steffens wrote a book called The Shame of the Cities in 1904 which exposed the corruption in city politics with the political machines. And of course the one a lot of people know about -- Upton Sinclair's The Jungle. More on him a little later.

Another key thing about the Progressive Movement is the importance of women in the movement. Women played an important role in the Progressive Movement, and this really gave them an opportunity to break down the idea of the separate spheres which was this idea that a woman's place was in the home. You know if you remember after the American Revolution this idea of Republican Motherhood -- raising young boys mainly to be good citizens. Women did not have the right to vote, and yet during the Progressive Movement they're playing an active role in causes such as child labor.

The National Child Labor Committee fought for laws banning child labor, and by 1907 about two-thirds of all states will have child labor laws put into place. You have the National Consumers League which was headed by Florence Kelley. Kelley remember was very active in the settlement house movement with Jane Addams, and the National Consumers League advocated for the rights of women in the workplace along with against child labor and all sorts of other causes.

A court case you should be aware of is Muller v. Oregon in 1908. The Court ruled that laws protecting women workers that restricted women to 10-hour work days were constitutional, and the court rules that women deserved and needed special protections as women in the workplace.

An event that really kind of stimulates a lot of activism amongst women and workers is the Triangle Shirtwaist Fire in 1911. A 10-story building in New York -- a fire breaks out leading to the death of 146 workers -- most of them being women and immigrants. And this really sparks reforms and calls for increased safety standards. And another reform that we're going to take a look at in just a moment is women in the temperance movement.

Important idea to keep in mind though is women are playing various roles in the Progressive Movement, and one of those which we're going to cover in our next video is the role of the woman's suffrage movement.

Urban reform was a huge part of the Progressive Movement. If you recall throughout the Gilded Age people have been moving to the cities, and this creates all sorts of problems. Amongst those problems are urban poverty and the rise of tenements and slums. You have political corruptions and political machines. And widespread alcoholism and all sorts of other issues in the cities. And we've already seen what Jane Addams and Florence Kelley and others were doing in places like Chicago with the settlement house movement trying to help people like you see in the image get out of urban poverty.

But you also see a desire during the Progressive Movement to take away power from political bosses by placing municipal services under public control. Sanitation was a huge problem in the cities, and one of the ways they felt they would be able to do this was by municipal government reform such as voters electing the heads of city departments such as fire, police and sanitation so that things would be more efficient and less corrupt.

Progressive reformers also focus on state reform. You get many progressive governors fighting against corporate control of state politics. In California you have Governor Hiram Johnson who took on the very powerful Southern Pacific Railroad. The big guy though is this handsome fellow Governor Robert La Follette of Wisconsin, and he's going to pioneer many reforms in the state of Wisconsin. And really kind of the reform movements in Wisconsin become known as the Wisconsin Idea. And you could see him fighting -- showing what he's going to do to these big bad businesses. He's going to regulate the public utilities. He's going to take on the powerful railroad industry. He's going to adopt many tax reforms and a whole bunch of political reforms which are going to be copied and utilized in other states.

So let's take a look at the political reforms of the Progressive Movement. There was this interest and this idea amongst progressives political reformers -- they wanted to increase democracy and reduce the control of trusts. The problem was the power of political machines and trusts and money was eroding Americans' faith in politics. You can see that in this political cartoon in which the trusts have taken over the Senate.

And so here's some of the things that were done in states such as Wisconsin. You have the Australian or secret ballot which allowed voters to mark their choice for office secretly so they would not be intimidated into voting for certain candidates which was often done. The direct primary in which the nomination of candidates placed into the hands of the voters -- so the voters would actually select who would be the candidate for the party. The recall allowed elected politicians they could be removed from office by the voters before their term expired -- so if they weren't doing a good job or if they were corrupt they can be removed in a special election. The initiative allowed voters could introduce laws. And the referendum allowed voters to directly vote on a law.

And the big amendment that takes place -- one of the big amendments is the 17th Amendment. And this one's important because rather than the state legislature, voters would directly vote for US senators. So this would bring more democracy into American politics it was felt. And remember the Populist Party advocated for this in the 1890s -- it becomes reality with the 17th Amendment.

There also were some moralistic aspects to the Progressive Movement. Remember it was a very diverse set of reforms, and there was all sorts of division over the temperance movement. Those in favor of drinking were known as wet -- they were against prohibition. Those who wanted to support temperance and prohibition -- the banning of alcohol legally banning alcohol -- were known as dry. And there was a growing conflict between those two groups.

And it really came down to Protestant native-born Americans very often versus Catholic immigrants. Catholic immigrants tended to be okay with drinking -- especially those so-called new immigrants from Southern and Eastern European countries. Very often there was division between rural areas which tended to be much more pro-temperance prohibition supporters whereas in the cities they tended to be more of a support for allowing people to do what they wanted to do.

There were organizations that were created. You have the Women's Christian Temperance Union -- a large organization of women advocating for temperance. They would encourage their members to take pledges promising not to drink any longer. And the big one is in 1895 the Anti-Saloon League which was the leading organization advocating for legal prohibition. They don't just want you to promise to not drink -- they want to get a law passed which would make it illegal to do so. And many states started adopting prohibition type laws. And of course in 1919 we'll see the 18th Amendment go into place banning alcohol throughout the country.

Now a big moment in the Progressive Movement comes with the emergence of Theodore Roosevelt as president at the age of 42 years old. And once again Roosevelt is a firm believer in an enlarged role for the president, and he's going to do things very differently. And one of those you can see in his labor policy and his relationship with organized labor and workers. And little kind of memory lane right here -- remember McKinley during the Great Railroad Strike of 1877 sided with corporations. Grover Cleveland during the Pullman Strike in 1894 also sided against organized labor.

And Theodore Roosevelt very very early on in his presidency was faced with a massive strike by the coal miners in 1902, and he actually tries to mediate the labor dispute between management and the workers. And owners won't compromise, so Theodore Roosevelt threatens to take over the mines with federal troops. And this is a very big difference than previous presidents -- especially during the Gilded Age were very often the federal government was using troops against the workers.

Now Roosevelt himself was not necessarily Mr. Pro-labor union. He believed in something what he referred to as the Square Deal, and this was his Progressive Era reform program. And there's three parts to it -- the three C's: corporations there should be control of corporations; consumers there should be consumer protection; and conservation -- conservation of the environment and the Earth's natural resources. So this is part of his Square Deal program.

For the APUSH exam it's really important you know about Roosevelt's program -- his Progressive Era policies. And let's take a look at them. First -- corporations trust busting. Roosevelt looked at things like the Sherman Antitrust Act -- remember that was passed in 1890 -- and he realized it was relatively ineffective at reducing the power of corporations and trusts. Remember in fact it was often times used against labor unions. Roosevelt's going to change this. He's going to break up the Northern Securities Company -- a railroad monopoly with tremendous power. In fact Roosevelt his actions are upheld by the Supreme Court in 1904, and he is going to be very famously known for his trust busting during his presidency. He's going to bring on antitrust action against 40 corporations.

And Roosevelt distinguished between good and bad trusts. And good trusts were trusts that were efficient and brought lower prices to consumers -- they weren't harmful to the economy. And bad trusts were harmful because they crushed competition and they hurt consumers by dominating and fixing prices. And throughout his presidency he's going to increase the power of the federal government with regard to business.

Another example of this is Roosevelt will also seek to increase the power of the Interstate Commerce Commission -- remember that was intended to regulate railroad rates across state lines. It was also relatively weak throughout much of the Gilded Age. Couple of examples of how that power is increased -- you see that in the Elkins Act of 1903. It increased the penalties for rate rebates that railroad companies would try to get away with. And the Hepburn Act of 1906 gave the ICC the power to set maximum rates for the railroad companies.

So big idea here is Roosevelt is using the power of the federal government -- the presidency -- to control and regulate corporations and strengthening previous laws such as the Sherman Antitrust Act and the Interstate Commerce Act.

The other C -- the second one is consumer protections. Remember at this time it's a laissez-faire attitude with the economy, and there are relatively few protections for consumers. It was very common for food to be bad and people to get ill or die from it and medicine and other items to be mislabeled. Upton Sinclair's book The Jungle was intended -- Upton Sinclair was a muckraker and his intention was to increase support for socialism and workers' rights by writing this book about the life for a worker in the Chicago stockyards. What ends up happening though is the public focuses on the unsanitary nature of the meat industry that Sinclair writes about, and there's a huge outcry with regard to the conditions of the meat in this factory that Sinclair writes about.

There's a lot of public pressure for Theodore Roosevelt to act, and as a result of Sinclair's muckraking activity the Meat Inspection Act of 1906 is passed which basically says the federal government would regulate and inspect the meat industry. And you see the federal government employee checking that good old tasty carne asada out. Another significant law for consumer protection is the Pure Food and Drug Act passed the same year, and this creates the FDA -- the Food and Drug Administration. And the FDA protected the public against the manufacture sale and transportation of mislabeled food and drugs. So people the public would have a right to know what's in the food and the drugs that they're purchasing. So next time you eat your hot Cheetos you know exactly how you're killing yourself.

The third C is conservation, and this is Roosevelt's big win domestically. It's important to keep in mind the issue of conservation did not register as a national issue -- people weren't talking about the environment as a big pressing problem. And there were some groups such as the Sierra Club which was founded in 1892 -- John Muir was a significant part of that movement advocating for the environment. But Roosevelt and working together -- there he is with John Muir -- is going to use the power of the government to protect the environment.

Roosevelt's going to use the Forest Reserve Act which was passed in 1891 to protect 150 million acres of federal land. And the Newlands Reclamation Act of 1902 -- money from sale of public lands could be used for irrigation projects in the west. So you have this kind of conservation and protection of the Earth's natural resources. And if you take a look at that map right there you can see some of the areas protected by Roosevelt.

One important thing to keep in mind is the contrast those two words -- conservation versus preservation. Conservation is the planned regulated use of the environment whereas preservationist -- which is what John Muir was -- was leaving nature alone just to be preserved in its natural state. And there was a big battle over the Hetch Hetchy project near San Francisco in which preservationists lost -- in the Hetch Hetchy project the dam was built altering the physical environment of that region.

Roosevelt serves until 1908, and he decides that he's going to honor the precedent of George Washington and he's not going to seek a third term even though he could have. And he hands over kind of the Republican Party leadership to the big guy over 300 pounds -- there's his bathtub -- William Howard Taft. And Taft is going to continue some of the progressive policies of Roosevelt. He's actually going to break up more trusts than Roosevelt -- little fun fact there most people think Roosevelt trustbuster -- Taft broke more of them. And he's going to continue some of conservationist policies as well.

And when it comes to foreign policy Taft differs from Roosevelt's big stick foreign policy, and he favors something called Dollar Diplomacy in which he encouraged businesses to invest money -- private financial investments -- in areas of strategic concerns of the United States. And the idea would be that this would lead to greater stability and would promote US interests without using force.

However when the election of 1912 comes up Roosevelt and Taft are going to be running against each other, but we're going to save that for another day another time. Thank you for watching. If the video helped you out click like. Have questions post a comment. Peace.

'''
