
= American Pageant - 053 (1491-1877)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


All right, today we're going to start off with the lyrics of a really amazing song: "If you're lost you can look and you will find me time after time." That's what we're all about at APUSH Explained. Joe's Productions -- we got your back time after time, because today we're breaking down important dates and periods in U.S. history from 1491 to 1877.

These are the key things you should know. You should know these dates and kind of know the order of things, so let's just get started. 1491 -- really important -- that's pre-Columbian exchange 哥伦布大交换, so before Columbus, before the Europeans arrive. And make sure you know about the Native American diversity 多样性 -- right, a lot of native tribes are adapting to their environments and there's a lot of unique cultures. 1492 -- Columbus discovers the New World. This begins the process of colonization 殖民化. Spain's first, but many others will follow. In fact, Spain is first in the colonization of North America -- what will be the United States -- at St. Augustine in 1565. But in 1607, Jamestown will be founded -- the English colony -- and that is the first permanent settlement 永久定居点. Remember they tried to establish a colony at Roanoke and it fails. A year later, the French will be establishing their own colony at Quebec.

And throughout 1607 to 1700s, it's really about colonization. You have the English, the French, the Spanish and the Dutch colonizing the Western Hemisphere and what will be the United States. A couple things you should keep in mind is English colonization is going to be very regionally -- each area is going to be characterized by their region. So you have the New England colonies, the middle colonies, the southern colonies, and this includes the Chesapeake region and of course the West Indies as well. And there is periods of salutary neglect 有益的忽视 during this period, and what that means is England's not going to really manage the colonies as closely as they would have liked because they're dealing with internal and external issues.

1676 is another date you should remember -- that's Bacon's Rebellion 培根叛乱 in the Chesapeake colony of Virginia that leads to the transition or the growth of slavery from indentured servants 契约仆人 to slaves. And of course in 1680, you have the Pueblo Revolt 普韦布洛起义 where Spain suffers a setback 挫折 in their colonization when native people rebel.

Some more dates throughout the 1700s -- this is a period of colonial development 殖民发展. So you have colonial societies emerging in both the British and the French and other colonies. 1730s to 1750s, you have the Great Awakening 大觉醒运动 moving across the colonies -- one of these shared experiences that all the colonists are going to kind of -- one of the few things that unites them. And of course a big one is 1754 -- this is the start of the French and Indian War 法印战争 as it's known in North America, or the Seven Years' War 七年战争 as it is known in Europe.

Make sure you know 1763 -- this is the end of the French and Indian War. This is going to have huge consequences 后果. I even put it in red because no more salutary neglect. The British are going to focus on the colonies. They're going to implement and enforce their mercantile laws 重商主义法律 such as the Navigation Acts 航海条例 and a whole bunch of other taxes. Which leads me to this period -- 1763 to 1775 is really a lot of tension between the colonies and their mama, and you're going to see a lot of things. Here's some of the highlights -- the Quartering Act 驻军法, the Stamp Act 印花税法案, the Tea Act 茶叶法案, the Coercive Acts 强制法案. You don't need to memorize those dates, you know, but just know that they're all kind of going on during this time of 1763 to 1775. And of course 1775 -- we are the eve of the Declaration of Independence, and the fighting actually begins before we declare our independence at Lexington and Concord.

Couple more dates -- of course 1776 -- that's why we eat the hot dogs and shoot off the fireworks -- the Declaration of Independence 独立宣言. You know earlier in the year you have Thomas Paine's "Common Sense" 常识. And of course from 1776 to 1783, you have the American Revolution 美国独立战争. And a couple of highlights of that -- the Battle of Saratoga 萨拉托加战役 -- that's an important battle because after that the French officially join the United States, the colonies in an alliance 联盟. We become homies with France. And the treaty that ends the war -- the Treaty of Paris of 1783 1783年巴黎条约. And often times they're going to ask you, you know, how was 1783 a turning point 转折点? Did the American Revolution change things a lot politically, socially or economically?

In 1787, you have the Constitutional Convention 制宪会议 -- goodbye Articles of Confederation 邦联条例. Remember Shays' Rebellion 谢斯起义 showed the Articles was weak. There were other problems with the Articles, and so they decide in 1787 to meet up and to draft a new government which goes into effect in 1789. The new government under the Constitution is basically put in force, and George Washington -- Jorge Washington -- becomes president. And they're going to adopt the Bill of Rights 权利法案 -- remember that's to make the Anti-Federalists 反联邦主义者 happy, to you know guarantee protections against government power.

1790s is all going to be about George Washington and John Adams. You have the first party system 政党体系 -- we're talking the Federalists 联邦党人 versus the Democratic-Republicans 民主共和党人. A lot of stuff going on -- a lot of battles between the Secretary of the Treasury Alexander Hamilton and Thomas Jefferson. There's the issue of the bank, the tariff 关税, and of course we have the Kentucky and Virginia Resolutions 肯塔基和弗吉尼亚决议 by Jefferson and Madison against the Federalist policies in the Alien and Sedition Acts 客工法和煽动叛乱法.

In 1800, it's an important year because Thomas Jefferson is elected, and this of course is the first peaceful transition of power 权力过渡. The Federalists are never going to serve in the presidency again, and the Constitution worked. In the period 1800 to 1860, there's no exact date -- you have the Market Revolution 市场革命 going on -- you know textile mills 纺织厂, the New England areas, the South is growing their cotton. So you have transportation improvements that's going on throughout this period. In 1803, you have the Louisiana Purchase 路易斯安那购地案 -- one of the best real estate deals ever. Thomas Jefferson gets a huge chunk of land from Napoleon. And of course our first declared war -- 1812 to 1814 under the new Constitution -- is the War of 1812 1812年战争 -- fighting our mama again. And of course during that war you have the Hartford Convention 哈特福德会议 which really hurts the Federalist Party because they're seen as traitors 叛徒.

1814 to 1824 -- make sure you know about it -- it's the so-called Era of Good Feelings 和睦时代. You know there's only one major political party -- the Federalists are fading away roughly by around 1817, 1818. But was it really an Era of Good Feelings? Because there were debates over Henry Clay's American System 美国体系, the Second Bank of the United States 美国第二银行, the Tariff of 1816 -- all of which is a part of the American system. So the Republican Party is divided -- or the Democratic-Republican Party is divided amongst themselves.

Big kind of period I put it in red -- 1820 to 1860 -- you're going to have a lot of sectional conflict 地区冲突. And this really comes down to as the nation expands West as we get more land, and the issue is going to be slavery in the territories 领土. This is going to lead to drama. An example of that drama is of course the Missouri Compromise 密苏里妥协案 where they have a big old fight over what to do about admitting Missouri as a slave state, and they figure it out with the compromise which calms sectional tension temporarily. 1823 -- just know about the Monroe Doctrine 门罗主义 -- kind of our message to Europe and exerting ourselves on the world stage.

And a big moment again is 1828 when Andrew Jackson is elected president of the United States. He takes office in 1829, and Andrew Jackson kind of symbolizes amongst many this age of the Common Man 普通人时代. There's also at this time frame an age of reform 改革时代 going on with a lot of different reforms. Make sure you know about those reforms in the early 19th century. Keep in mind there are going to be crises 危机 that you should know about. Big one is the Nullification Crisis 州权废止危机 of 1833 -- Jackson battling the state of South Carolina over tariffs. And in 1838, you have the Trail of Tears 血泪之路 -- the forcible removal 强制迁移 of the Cherokee people.

1828 to 1854 -- you have the second party system 第二政党体系. This we're talking about the Whigs 辉格党 versus the Democrats 民主党. The Whigs emerged during Jackson's presidency protesting his policies, particularly his war on the bank. And 1845 to 1849 -- Polk is elected in '44, takes the presidency, and he's really known for fulfilling the goals of Manifest Destiny 昭昭天命 -- annexing Texas, taking Oregon, California and much more. So know about Polk in that time frame of the 1840s. Can't talk about Polk without talking about the Mexican-American War 美墨战争 which lasts for a little less than 2 years. And in 1848, not only does the Mexican-American War end with the Treaty of Guadalupe Hidalgo 瓜达卢佩-伊达尔戈条约, but also women meet with the Seneca Falls Convention 塞尼卡福尔斯会议, and this is seen as the birth of the women's rights movement -- women's suffrage 妇女选举权 in the country. And the Mexican-American War creates problems which eventually get temporarily resolved with the Compromise of 1850 1850年妥协案. California will be admitted as a free state, but the South's going to get a Fugitive Slave Act 逃奴法案.

Which leads us throughout the 1850s -- you have sectional crisis 地区危机 -- lots of sectional tension 地区紧张局势. The North hates the Fugitive Slave Act. Kansas-Nebraska Act 堪萨斯-内布拉斯加法案 destroys the Whig Party. You have Dred Scott 德雷德·斯科特案, you have Bleeding Kansas 流血的堪萨斯. There's a lot of sectional tension. So know 1850s sectional tensions. And in that same period post-1854 after Kansas-Nebraska, you get the emergence of the third party system -- the Republicans 共和党 versus the Democrats. The Whigs are goodbye -- say farewell. And in 1860, Lincoln is elected which begins secession 分裂 -- South Carolina being the first one to leave. And that'll lead us to following Fort Sumter -- the Civil War 美国内战 which will take place from 1861 to 1865.

And some key things you should know in terms of dates -- the Battle of Antietam 安提塔姆战役 which is important not only from a military standpoint but eventually leads to Lincoln announcing the Emancipation Proclamation 解放宣言. And during the war -- even before it ends before 1865 -- you have Reconstruction 重建时期 -- the process of bringing the Union back together, dealing with a post-slavery America. And you're going to get some amendments 修正案 -- some very important amendments -- the 13th, the 14th and 15th amendments. But Reconstruction will be a temporary revolution in some ways because in 1877 it will come to an end. Remember there's the election of 1876 -- it's disputed between Rutherford B. Hayes and Tilden. And following that there's a Compromise of 1877 1877年妥协案 which ends Reconstruction, and you get the rise of Jim Crow laws 吉姆·克劳法, sharecropping 佃农制, etc.

Make sure you check out APUSHExplained.com. If you scroll to the bottom of the page on the review section, click right there, you will come across all sorts of cool helpful information. But you will also come across right here the Period 1 to 5 timeline -- all the stuff you just saw broken down for you. I recommend you print it and just add some annotations 注释 and just know these time periods, these dates -- these are the core ones. You know these, you should be good for periods 1 through 5. As always, if the video helped you out, make sure click like, post any comments that you may have, and have a beautiful day. Peace!

'''


== 中文翻译

好的，今天我们从一首非常棒的歌曲的歌词开始：“如果你迷失了方向，你可以寻找，你会一次又一次地找到我。”这就是我们在APUSH Explained所做的。乔氏制作——我们会一次又一次地支持你，因为今天我们要分析美国历史上从1491年到1877年的重要日期和时期。

这些是你们应该知道的关键点。你们应该知道这些日期，并且大致了解事情的顺序，那么我们就开始吧。1491年——非常重要——那是前哥伦布时期，所以在哥伦布之前，在欧洲人到来之前。确保你们了解美洲原住民的多样性——对，许多原住民部落都在适应他们的环境，并且存在许多独特的文化。1492年——哥伦布发现新大陆。这开始了殖民化的进程。西班牙是第一个，但许多其他国家会紧随其后。事实上，西班牙是第一个在北美洲（未来的美国）进行殖民化的国家，地点是1565年的圣奥古斯丁。但在1607年，詹姆斯敦——英国殖民地——将建立，那是第一个永久定居点。记住，他们曾试图在罗阿诺克建立殖民地，但失败了。一年后，法国人将在魁北克建立他们自己的殖民地。

从1607年到1700年代，主要都是关于殖民化。英国人、法国人、西班牙人和荷兰人都在殖民西半球以及未来的美国。你们应该记住几件事，英国的殖民化在地域上非常不同——每个区域都将以其地区特征为标志。所以你们有新英格兰殖民地、中部殖民地、南部殖民地，这包括切萨皮克地区，当然还有西印度群岛。在此期间存在着“有益的忽视”时期，这意味着英国不会像他们希望的那样密切地管理殖民地，因为他们正在处理内部和外部问题。

1676年是你们应该记住的另一个日期——那是切萨皮克地区的弗吉尼亚殖民地的培根叛乱，这场叛乱导致了奴隶制从契约奴隶向奴隶的转变或增长。当然，在1680年，你们看到了普韦布洛起义，当当地居民反抗时，西班牙的殖民化遭受了一次挫折。

1700年代的更多日期——这是一个殖民发展的时期。因此，你们看到了在英国、法国和其他殖民地都出现了殖民社会。1730年代到1750年代，大觉醒运动席卷整个殖民地——这是所有殖民者都将经历的一种共同体验——少数几个将他们团结起来的事情之一。当然，一个重要的日期是1754年——这是北美洲所称的法国-印第安战争（七年战争在欧洲的称谓）的开始。

确保你们知道1763年——这是法国-印第安战争的结束。这将产生巨大的后果。我甚至用红色标出来了，因为不再有“有益的忽视”了。英国人将专注于殖民地。他们将实施并执行他们的重商主义法律，例如《航海法案》和一大堆其他税收。这就引出了这个时期——1763年到1775年实际上是殖民地和他们的“妈妈”之间充满紧张的时期，你们会看到很多事情发生。这里是一些重点——《住宿法案》、《印花税法案》、《茶叶法案》、《强制法案》。你们不需要记住这些日期，你们知道，但只要知道它们都发生在1763年到1775年这段时间。当然，1775年——我们正处于《独立宣言》的前夜，在我们宣布独立之前，战斗实际上已经在列克星敦和康科德开始了。

再提几个日期——当然是1776年——这就是我们吃热狗、放烟花的原因——《独立宣言》。你们知道，在今年早些时候，托马斯·潘恩发表了《常识》。当然，从1776年到1783年，你们看到了美国独立战争。这场战争的几个亮点——萨拉托加战役——这是一场重要的战役，因为在那之后，法国正式加入了美国，殖民地结成了联盟。我们和法国成了好朋友。结束战争的条约——1783年的《巴黎条约》。他们经常会问你们，你们知道，1783年是如何成为一个转折点的？美国独立战争在政治、社会或经济上是否带来了很大的变化？

1787年，你们看到了制宪会议——《邦联条例》再见了。记住，谢司叛乱表明《邦联条例》很软弱。《邦联条例》还有其他问题，所以他们在1787年决定会面并起草一份新的政府文件，这份文件于1789年生效。根据宪法建立的新政府基本上开始运作，乔治·华盛顿——豪尔赫·华盛顿——成为总统。他们将通过《权利法案》——记住，这是为了让反联邦党人高兴，为了保证免受政府权力侵犯的保护。

1790年代将完全是关于乔治·华盛顿和约翰·亚当斯。你们看到了第一个政党制度——我们指的是联邦党人和民主共和党人。发生了许多事情——财政部长亚历山大·汉密尔顿和托马斯·杰斐逊之间发生了许多争斗。存在银行问题、关税问题，当然，我们还有杰斐逊和麦迪逊反对联邦党人在《外国人和煽动叛乱法案》中政策的《肯塔基和弗吉尼亚决议》。

1800年是一个重要的年份，因为托马斯·杰斐逊当选总统，这当然是第一次和平的权力交接。联邦党人将再也不会担任总统职位，宪法奏效了。在1800年到1860年这段时期，没有确切的日期——你们看到了市场革命正在进行——你们知道，纺织厂、新英格兰地区，南方正在扩大棉花种植。所以，整个这段时期都存在着交通运输的改善。1803年，你们看到了路易斯安那购地——有史以来最好的房地产交易之一。托马斯·杰斐逊从拿破仑手中获得了大片土地。当然，我们的第一次正式宣战——1812年到1814年，在新宪法下——是1812年战争——再次与我们的“妈妈”作战。当然，在那场战争期间，你们看到了哈特福德会议，这真正损害了联邦党，因为他们被视为叛徒。

1814年到1824年——确保你们了解——这就是所谓的“美好时代”。你们知道，只有一个主要的政党——联邦党大约在1817年、1818年左右逐渐衰落。但这真的是一个“美好时代”吗？因为围绕着亨利·克莱的“美国体系”、美国第二银行、1816年关税（所有这些都是美国体系的一部分）存在着争论。所以，共和党——或者说民主共和党——内部出现了分裂。

我用红色标出的一个重要的时期——1820年到1860年——你们将看到许多地区冲突。这实际上归结为随着国家向西扩张，我们获得了更多的土地，而问题将是这些领土上的奴隶制。这将导致戏剧性的事件。这种戏剧性的一个例子当然是密苏里妥协案，他们就如何接纳密苏里成为一个蓄奴州进行了激烈的争吵，他们通过妥协解决了这个问题，暂时平息了地区紧张局势。1823年——只要了解门罗主义——这有点像我们向欧洲发出的信息，并在世界舞台上展现自己。

又一个重要的时刻是1828年，安德鲁·杰克逊当选为美国总统。他于1829年就职，安德鲁·杰克逊在许多人看来象征着这个“平民时代”。与此同时，也存在着一个改革时代，出现了许多不同的改革。确保你们了解19世纪初的这些改革。记住，你们应该了解一些危机。一个重要的危机是1833年的废止危机——杰克逊与南卡罗来纳州就关税问题展开斗争。而在1838年，你们看到了“血泪之路”——切罗基人被强行迁移。

1828年到1854年——你们看到了第二个政党制度。我们指的是辉格党和民主党。辉格党在杰克逊总统任期内出现，抗议他的政策，特别是他对银行的战争。1845年到1849年——波尔克在1844年当选，就任总统，他真正因实现“昭昭天命”的目标而闻名——吞并德克萨斯、夺取俄勒冈、加利福尼亚等等。所以，了解1840年代的波尔克。不谈美墨战争就无法谈论波尔克，这场战争持续了不到两年。1848年，不仅美墨战争以《瓜达卢佩-伊达尔戈条约》结束，而且妇女们在塞内卡瀑布会议上会面，这被视为美国女权运动——妇女选举权运动的诞生。美墨战争制造了问题，这些问题最终通过1850年妥协案得到暂时解决。加利福尼亚将作为自由州加入联邦，但南方将获得《逃亡奴隶法》。

这就引出了整个1850年代——你们看到了地区危机——大量的地区紧张局势。北方憎恨《逃亡奴隶法》。《堪萨斯-内布拉斯加法案》摧毁了辉格党。你们看到了德雷德·斯科特案，你们看到了“流血的堪萨斯”。存在着大量的地区紧张局势。所以，了解1850年代的地区紧张局势。在堪萨斯-内布拉斯加法案之后的同一时期（1854年后），你们看到了第三个政党制度的出现——共和党和民主党。辉格党再见了——说再见吧。而在1860年，林肯当选总统，这开始了分裂——南卡罗来纳州是第一个脱离联邦的州。这将导致我们关注萨姆特堡事件——从1861年到1865年发生的内战。

就日期而言，你们应该了解一些关键事件——安提塔姆战役，这场战役不仅从军事角度来看很重要，而且最终导致林肯宣布了《解放奴隶宣言》。在战争期间——甚至在1865年结束之前——你们看到了重建时期——将联邦重新统一，处理后奴隶制时期的美国。你们将看到一些修正案——一些非常重要的修正案——第十三条、第十四条和第十五条修正案。但重建在某种程度上将是一场暂时的革命，因为它将在1877年结束。记住，1876年大选——在拉瑟福德·B·海斯和蒂尔登之间存在争议。在那之后是1877年妥协案，该妥协案结束了重建，你们看到了吉姆·克劳法、分成制等的兴起。

请务必查看 APUSHExplained.com. 如果你滚动到评论部分的页面底部，点击那里，你将找到各种有用的信息。但你也会在这里看到1到5时期的时间轴——你刚才看到的所有内容都为你分解好了。我建议你打印出来，并添加一些注释，记住这些时期，这些日期——这些是核心的。你知道这些，你应该就能很好地掌握1到5时期。像往常一样，如果这个视频对你有帮助，请务必点赞，发表你可能有的任何评论，祝你度过美好的一天。再见！

'''


== pure

Here's the properly punctuated and formatted version of your transcript with corrections:

---

All right, today we're going to start off with the lyrics of a really amazing song: "If you're lost you can look and you will find me time after time." That's what we're all about at APUSH Explained. Joe's Productions -- we got your back time after time, because today we're breaking down important dates and periods in U.S. history from 1491 to 1877.

These are the key things you should know. You should know these dates and kind of know the order of things, so let's just get started. 1491 -- really important -- that's pre-Columbian exchange, so before Columbus, before the Europeans arrive. And make sure you know about the Native American diversity -- right, a lot of native tribes are adapting to their environments and there's a lot of unique cultures. 1492 -- Columbus discovers the New World. This begins the process of colonization. Spain's first, but many others will follow. In fact, Spain is first in the colonization of North America -- what will be the United States -- at St. Augustine in 1565. But in 1607, Jamestown will be founded -- the English colony -- and that is the first permanent settlement. Remember they tried to establish a colony at Roanoke and it fails. A year later, the French will be establishing their own colony at Quebec.

And throughout 1607 to 1700s, it's really about colonization. You have the English, the French, the Spanish and the Dutch colonizing the Western Hemisphere and what will be the United States. A couple things you should keep in mind is English colonization is going to be very regionally -- each area is going to be characterized by their region. So you have the New England colonies, the middle colonies, the southern colonies, and this includes the Chesapeake region and of course the West Indies as well. And there is periods of salutary neglect during this period, and what that means is England's not going to really manage the colonies as closely as they would have liked because they're dealing with internal and external issues.

1676 is another date you should remember -- that's Bacon's Rebellion in the Chesapeake colony of Virginia that leads to the transition or the growth of slavery from indentured servants to slaves. And of course in 1680, you have the Pueblo Revolt where Spain suffers a setback in their colonization when native people rebel.

Some more dates throughout the 1700s -- this is a period of colonial development. So you have colonial societies emerging in both the British and the French and other colonies. 1730s to 1750s, you have the Great Awakening moving across the colonies -- one of these shared experiences that all the colonists are going to kind of -- one of the few things that unites them. And of course a big one is 1754 -- this is the start of the French and Indian War as it's known in North America, or the Seven Years' War as it is known in Europe.

Make sure you know 1763 -- this is the end of the French and Indian War. This is going to have huge consequences. I even put it in red because no more salutary neglect. The British are going to focus on the colonies. They're going to implement and enforce their mercantile laws such as the Navigation Acts and a whole bunch of other taxes. Which leads me to this period -- 1763 to 1775 is really a lot of tension between the colonies and their mama, and you're going to see a lot of things. Here's some of the highlights -- the Quartering Act, the Stamp Act, the Tea Act, the Coercive Acts. You don't need to memorize those dates, you know, but just know that they're all kind of going on during this time of 1763 to 1775. And of course 1775 -- we are the eve of the Declaration of Independence, and the fighting actually begins before we declare our independence at Lexington and Concord.

Couple more dates -- of course 1776 -- that's why we eat the hot dogs and shoot off the fireworks -- the Declaration of Independence. You know earlier in the year you have Thomas Paine's "Common Sense." And of course from 1776 to 1783, you have the American Revolution. And a couple of highlights of that -- the Battle of Saratoga -- that's an important battle because after that the French officially join the United States, the colonies in an alliance. We become homies with France. And the treaty that ends the war -- the Treaty of Paris of 1783. And often times they're going to ask you, you know, how was 1783 a turning point? Did the American Revolution change things a lot politically, socially or economically?

In 1787, you have the Constitutional Convention -- goodbye Articles of Confederation. Remember Shays' Rebellion showed the Articles was weak. There were other problems with the Articles, and so they decide in 1787 to meet up and to draft a new government which goes into effect in 1789. The new government under the Constitution is basically put in force, and George Washington -- Jorge Washington -- becomes president. And they're going to adopt the Bill of Rights -- remember that's to make the Anti-Federalists happy, to you know guarantee protections against government power.

1790s is all going to be about George Washington and John Adams. You have the first party system -- we're talking the Federalists versus the Democratic-Republicans. A lot of stuff going on -- a lot of battles between the Secretary of the Treasury Alexander Hamilton and Thomas Jefferson. There's the issue of the bank, the tariff, and of course we have the Kentucky and Virginia Resolutions by Jefferson and Madison against the Federalist policies in the Alien and Sedition Acts.

In 1800, it's an important year because Thomas Jefferson is elected, and this of course is the first peaceful transition of power. The Federalists are never going to serve in the presidency again, and the Constitution worked. In the period 1800 to 1860, there's no exact date -- you have the Market Revolution going on -- you know textile mills, the New England areas, the South is growing their cotton. So you have transportation improvements that's going on throughout this period. In 1803, you have the Louisiana Purchase -- one of the best real estate deals ever. Thomas Jefferson gets a huge chunk of land from Napoleon. And of course our first declared war -- 1812 to 1814 under the new Constitution -- is the War of 1812 -- fighting our mama again. And of course during that war you have the Hartford Convention which really hurts the Federalist Party because they're seen as traitors.

1814 to 1824 -- make sure you know about it -- it's the so-called Era of Good Feelings. You know there's only one major political party -- the Federalists are fading away roughly by around 1817, 1818. But was it really an Era of Good Feelings? Because there were debates over Henry Clay's American System, the Second Bank of the United States, the Tariff of 1816 -- all of which is a part of the American system. So the Republican Party is divided -- or the Democratic-Republican Party is divided amongst themselves.

Big kind of period I put it in red -- 1820 to 1860 -- you're going to have a lot of sectional conflict. And this really comes down to as the nation expands West as we get more land, and the issue is going to be slavery in the territories. This is going to lead to drama. An example of that drama is of course the Missouri Compromise where they have a big old fight over what to do about admitting Missouri as a slave state, and they figure it out with the compromise which calms sectional tension temporarily. 1823 -- just know about the Monroe Doctrine -- kind of our message to Europe and exerting ourselves on the world stage.

And a big moment again is 1828 when Andrew Jackson is elected president of the United States. He takes office in 1829, and Andrew Jackson kind of symbolizes amongst many this age of the Common Man. There's also at this time frame an age of reform going on with a lot of different reforms. Make sure you know about those reforms in the early 19th century. Keep in mind there are going to be crises that you should know about. Big one is the Nullification Crisis of 1833 -- Jackson battling the state of South Carolina over tariffs. And in 1838, you have the Trail of Tears -- the forcible removal of the Cherokee people.

1828 to 1854 -- you have the second party system. This we're talking about the Whigs versus the Democrats. The Whigs emerged during Jackson's presidency protesting his policies, particularly his war on the bank. And 1845 to 1849 -- Polk is elected in '44, takes the presidency, and he's really known for fulfilling the goals of Manifest Destiny -- annexing Texas, taking Oregon, California and much more. So know about Polk in that time frame of the 1840s. Can't talk about Polk without talking about the Mexican-American War which lasts for a little less than 2 years. And in 1848, not only does the Mexican-American War end with the Treaty of Guadalupe Hidalgo, but also women meet with the Seneca Falls Convention, and this is seen as the birth of the women's rights movement -- women's suffrage in the country. And the Mexican-American War creates problems which eventually get temporarily resolved with the Compromise of 1850. California will be admitted as a free state, but the South's going to get a Fugitive Slave Act.

Which leads us throughout the 1850s -- you have sectional crisis -- lots of sectional tension. The North hates the Fugitive Slave Act. Kansas-Nebraska Act destroys the Whig Party. You have Dred Scott, you have Bleeding Kansas. There's a lot of sectional tension. So know 1850s sectional tensions. And in that same period post-1854 after Kansas-Nebraska, you get the emergence of the third party system -- the Republicans versus the Democrats. The Whigs are goodbye -- say farewell. And in 1860, Lincoln is elected which begins secession -- South Carolina being the first one to leave. And that'll lead us to following Fort Sumter -- the Civil War which will take place from 1861 to 1865.

And some key things you should know in terms of dates -- the Battle of Antietam which is important not only from a military standpoint but eventually leads to Lincoln announcing the Emancipation Proclamation. And during the war -- even before it ends before 1865 -- you have Reconstruction -- the process of bringing the Union back together, dealing with a post-slavery America. And you're going to get some amendments -- some very important amendments -- the 13th, the 14th and 15th amendments. But Reconstruction will be a temporary revolution in some ways because in 1877 it will come to an end. Remember there's the election of 1876 -- it's disputed between Rutherford B. Hayes and Tilden. And following that there's a Compromise of 1877 which ends Reconstruction, and you get the rise of Jim Crow laws, sharecropping, etc.

Make sure you check out APUSHExplained.com. If you scroll to the bottom of the page on the review section, click right there, you will come across all sorts of cool helpful information. But you will also come across right here the Period 1 to 5 timeline -- all the stuff you just saw broken down for you. I recommend you print it and just add some annotations and just know these time periods, these dates -- these are the core ones. You know these, you should be good for periods 1 through 5. As always, if the video helped you out, make sure click like, post any comments that you may have, and have a beautiful day. Peace!

'''
