= 1631
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 326.
This is ESL Podcast’s English Café episode 326. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English. You can also visit our ESL Podcast Blog, and you can like us on Facebook at facebook.com/eslpod.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech. Today we’re going to be talking about how U.S. families – families from the U.S. – live in other countries and how they “adapt,” how they get used to living in other countries. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café is how U.S. families adjust or adapt to life overseas. That word “overseas” (one word) means living in another country. Technically, of course, most of what is commonly considered North and South America is not overseas. “Seas” is another word for oceans. It’s not over the ocean, like Europe or Asia or Africa would be, but we use the term broadly – generally to mean in another country.
We’re going to listen to four people talking about their experiences as Americans living in other countries. The first one is going to be Richard Choi, whose family went to live in China, where he was sent to work. Before they left for China, Richard’s company tried to help the family prepare for the changes by giving them some advice about cultural differences between the U.S. and China. In this quote, he’s going to talk about a “manual” (manual), which is basically an instruction book, a book that tells you how to do something.
We’ll listen to Richard first, and then explain what he said. Let’s listen:
[recording]
There was a very large section on the corporate culture and how to behave in the workplace.
[end of recording]
Richard says that there was a very large section or part of the manual – the book – that was about corporate culture. “Corporate culture” refers to the kinds of behaviors and relationships that are expected at an office or at work. Sometimes very large businesses have their own kind of corporate culture. For example, Nike has a corporate culture where their employees are encouraged to be athletic and participate in team sports, even playing games during the workday. Google’s corporate culture also encourages game playing; it’s a very different kind of corporate culture than you would get in a bank in New York City, for example. Here, Richard is talking about the corporate culture not in one specific business, but in Chinese businesses as a whole – in general.
So, Richard says, “There was a very large section on the corporate culture and how to behave in the workplace.” “To behave” (behave) means to act, to do something. For example, someone who steals is behaving badly. Someone who is helpful and friendly we would say is behaving well. Sometimes we talk about children and how they behave. We may say, “That child is very well behaved,” meaning he doesn’t yell and kick and scream like my neighbor children. No, not my neighbor children. Well, yes actually, my neighbor children! Richard says the manual tells people how to behave in the workplace. The “workplace” (one word) is – you guessed it – the place where you work, where business is done. It could be an office, a factory, a store, a restaurant, a closet – wherever you work, that’s your workplace. There are many expectations about how we should behave in the workplace, and Richard is saying that those expectations may be different in the United States versus in China.
Let’s listen once again:
[recording]
There was a very large section on the corporate culture and how to behave in the workplace.
[end of recording]
Richard’s wife, Kim, also had to prepare for life in China. She took a test to learn how well she could adjust to Chinese culture, a test that the company gave her. Let’s listen as she talks about what she learned from taking this test:
[recording]
I learned actually that my personal space is quite important to me which was the one area that was of a concern to the consultants simply because in China there is no such thing as personal space.
[end of recording]
Kim says, “I learned actually that my personal space is quite important to me.” She says, “I learned actually,” meaning in fact; it’s sort of a way of emphasizing what she is saying. She learned that her personal space is quite important. “Personal space” refers physically to the area around us; we don’t like people being too close to us. Most Americans have a personal space that is probably about the length of their arm, maybe a foot or two, and if you come closer than that they feel you’re too close. You are going into their personal space and it makes them feel uncomfortable. Of course, there are exceptions to this. If you are with members of your family you may allow that personal space to be smaller. Sometimes you have to let people into your personal space if you are riding on a crowded bus or a subway. But in general, our personal space is the empty space around us where we don’t want other people coming in.
Kim says that her need for personal space was an area of concern to the consultants. She says this was one area – one topic – that was of concern to the consultants. “Consultants” are people that companies pay, usually from outside of the company, to provide some sort of service. “To be of concern” is something you are worried about, an issue or a topic that you are concerned or worried about. Kim’s need for personal space was an area of concern for the consultants, who I mentioned are people who give advice or guidance or sometimes a service to a company, but they don’t work for the company directly. They’re not employees, I should say. In this case, the company Richard works for hired consultants to help him and his family learn about Chinese culture and prepare for their adjustment.
Kim says that this was an area concern to the consultants simply, or just, because in China there is no such thing as personal space. Now, I’m not saying that’s true. That’s what Kim said. Please don’t email and tell me I’m wrong; I’m not saying that, that’s what Kim is saying. It may be true, I don’t know. But, that’s what Kim was told by these consultants.
Let’s listen to Kim talk about this one more time:
[recording]
I learned actually that my personal space is quite important to me which was the one area that was of a concern to the consultants simply because in China there is no such thing as personal space.
[end of recording]
Next we’re going to listen to Jo Danehl, who works for a company that provides these cultural training services. She’s sort of one of those consultants that a company might bring in to talk to people that they are sending to live in another country. Let’s listen, and then we’ll talk about what she said:
[recording]
Family adjustment is far and away the biggest reason that assignments fail. And if you think that international assignments can be in excess of a million dollars for companies, they are going to need to mitigate that opportunity for failure.
[end of recording]
Jo begins by saying that family adjustment is far and away the biggest reason that assignments fail. “Adjustment” (adjustment) is sort of like adaptation, when you’re getting used to something. People change their behavior in response to some change in their situation – their environment. For example, if you grow up in one country and culture, and suddenly move to another country, that’s a big adjustment. You may have a different language, they may eat different food, wear different clothing, and so forth. All of these things would require adjustment. Jo is saying that the biggest problem, when companies send people overseas, is the adjustment by the family members: the wife or the husband, the children, and so forth.
Jo says that family adjustment is far and away the biggest reason why assignments fail. The phrase “far and away” means a lot, very much. It’s used to describe something that makes up the majority or a very large percentage of what we are talking about. Lucy is far and away the best scriptwriter that I know of. I’ve worked with other scriptwriters, and Lucy is the best – the best of that group. That’s an example of “far and away.” Well, family adjustment is far and away the biggest reason why assignments fail. “Assignments” would be when someone is sent to do something; in this case, to work in another country.
She continues, “And if you think that international assignments can be in excess of a million dollars for companies, they are going to need to mitigate that opportunity for failure.” This is something of a long and complex sentence, made even more so by the business vocabulary, shall we call it, that Jo uses. Let’s try to figure out what she’s saying in plain English. She says that international assignments, sending people to work overseas, the cost of that can be in excess of a million dollars, meaning it can be more than. When we say something is “in excess (excess) of (something)” we mean it’s more than that. If you say someone makes an excess of 200,000 dollars a year, that means they make more than 200,000 dollars a year. You don’t know how much more, you just know that it’s more than that amount. Jo is saying that it can cost companies more than a million dollars to send people into another country to work. Because of that, these companies need to mitigate that opportunity for failure. “To mitigate” (mitigate) means to reduce or lower the risk of something, to make something safer or less likely to create problems. You can mitigate the risk of natural disasters by buying some sort of homeowners insurance. Here in California, you would want to buy earthquake insurance. You can mitigate the danger or risk of being attacked or robbed by not walking in dangerous neighborhoods at night. That’s how we use the verb “to mitigate.” Don’t confuse this word with “to litigate,” starts with an “l” and involves lawyers, something completely different and not pleasant.
Large companies know that family adjustment is one of the reasons why international assignments fail, so they try to mitigate what Jo calls the “opportunity for failure,” the possibility that things will go wrong.
Let’s listen one more time:
[recording]
Family adjustment is far and away the biggest reason that assignments fail. And if you think that international assignments can be in excess of a million dollars for companies, they are going to need to mitigate that opportunity for failure.
[end of recording]
Finally, we’re going to listen to a woman named Therese Gavin. She works for a company that helps employees’ husbands and wives find meaningful activities, things to do in the new country, such as a job or perhaps volunteer work. She’s another consultant.
Let’s listen:
[recording]
If the spouse is happy, then the employee is going to be more productive in their work.
[end of recording]
Therese begins by talking about the spouse. She says, “If the spouse is happy.” “Spouse” (spouse) is either your husband or your wife. “Spouse” can be either a man or a woman. We usually use this word in business settings. You may, for example, be invited to a business conference, and the invitation says that spouses are welcome, meaning you can also bring your husband or your wife. You can’t bring your dog or your cat; those are not spouses, although some people feel very close to them. Those are not usually welcome at these parties. Not my parties, anyway!
Therese says if the spouses are happy, then the employee is going to be more productive in their work. The “employee,” of course, is the person who actually works for the company. “To be productive” means to get more done, to be more effective, to produce more in the amount of time you are given than perhaps someone else. The general term is “productivity,” it’s a noun referring to this getting things done idea. “Productive” would be an adjective. So if you say that someone is going to be more productive, they’re going to get more things done in the same amount of time.
Let’s listen to Therese one more time:
[recording]
If the spouse is happy, then the employee is going to be more productive in their work.
[end of recording]
So, those are some ideas of people who have been assigned to live in other countries from the U.S., and some of the things that companies might do to prepare them for that change.
Now let’s answer some of your questions.
Our first question comes from Phoenix (Phoenix), like the city here in the United States. Phoenix, however, is not in Arizona; Phoenix is in China, and wants to know the meaning of the word “outpatient.”
“Outpatient” (outpatient – one word) is someone who is sick and in the hospital but they don’t stay there overnight, they go in the morning and leave in the afternoon. Or they go, they get their medicine or their treatment, and then they leave a couple of hours later. A “patient” is anyone who is going to the doctor in order to get some sort of medicine or treatment. “Outpatient” is someone who goes but doesn’t stay, for example, at a hospital or a clinic. The opposite would be “inpatient,” and that would be someone who sleeps there overnight, at least one night.
There are a couple of other terms associated with hospital care; one would be “intensive care unit,” what we sometimes call simply “ICU,” the initials. That’s the area where very sick people have to go, where they are watched all the time. “Intensive” here means with a lot of people paying attention to you. An “emergency room,” sometimes called an “ER,” is where people often go for things that they don’t have an appointment for, but they need medical attention right away. You could go to an ER and be either an inpatient or an outpatient; if you stay in the hospital you’d be an inpatient. I once had to go to the ER because I cut my finger. I was trying to cook something – that was my first mistake – and I cut my finger and had to go to the ER and I was an outpatient; I didn’t stay there, I came back home.
Our next question comes from Florens (Florens) in Germany. Florens wants to know the difference between two verbs: “to gobble” and “to gulp.” Let’s start with “to gulp” (gulp). “To gulp” means to swallow through your mouth into your throat and down into your stomach, to swallow a large amount of food or liquid – water, beer, whatever – very quickly. To swallow this food or liquid quickly is “to gulp.” Your mother may say, “Don’t gulp your food,” don’t eat it so quickly. Or, “I was so thirsty after running the marathon that I gulped down a bottle of water.” The “down” is just for emphasis; I could say “I gulped a bottled of water.” A few years ago – maybe they still have it – there was a store here in the United States that sold a – well, it wasn’t a bottle, it was a container of soda – of soda pop – that was huge. It was much bigger than what you normally get, and they called it “The Big Gulp,” because there was so much liquid inside. But normally “gulp” just means swallowing a large amount of something.
“To gobble” (gobble) also means to eat very quickly, not necessarily putting a lot of food in your mouth, but eating what you have very quickly: “I gobbled up my food, I was so hungry.” “Gobble” is also the sound that we, in English, say that the turkey – the animal the turkey – makes. We have turkey for Thanksgiving – the Thanksgiving holiday here in the United States, almost everyone has turkey. The sound that we would say the turkey makes is “gobble, gobble, gobble, gobble, gobble.” That’s not very good, is it? “Gobble, gobble, gobble, gobble,” eh, close. Anyway, that’s the word we use for the sound of a turkey. Is that actually the sound of a turkey? Hmm, depends what language the turkey is speaking!
Finally, Evaldo (Evaldo) in Brazil wants to know the meaning of the word “swell” (swell). He was watching an American television show – a popular show, I’ve never actually seen it – called Two and a Half Men, and one of the characters – one of the people on the show said, “that’s swell.”
“Swell” is a word that can mean a couple of different things; we’ll talk about a few different definitions. “Swell” can mean to get bigger or more intense. We might talk about the waves on the ocean or the waves on a large lake – the “waves” are the water that goes up and down – we may say they are “swelling” or they “swelled,” they got bigger or stronger.
You can also “swell with emotion.” “My heart swelled with love when I saw my beautiful wife.” It got bigger; it got fuller; the emotion became stronger.
“Swell” is also something that a part of your body can do when you injure it. I hit my thumb, I was trying to close the door – true story – trying to close the door and the door closed on my thumb. I’m sure we’ve all had that happen. And afterwards, the thumb began to swell, it got bigger. We would describe the thumb, then, as “swollen” (swollen). “Swollen” is the past participle of the verb “to swell.”
“Swell” can also mean good or something that is fashionable. It was a word that we used a lot back in the middle 20th century. In the 1950s and 60s people may say – or used to say things like, “Well, that’s swell,” “That’s a swell coat you have on (that’s a nice looking coat),” or, “We’re going to a party. Isn’t that swell?” Nowadays, however, if you say that you’re probably trying to be funny because it’s not an expression that’s used as much anymore, and when someone does say it they might be sarcastic in saying it. That is, they don’t really mean it; they mean the opposite, that it’s not good. If you say to me, “Oh, Jeff, here is some cabbage soup for you,” cabbage is a vegetable – a green vegetable; I don’t really like cabbage soup, and I might say to be funny, “Oh, that’s swell. Thank you,” meaning I don’t really want the cabbage or like the cabbage soup.
I do like getting emails and letters – well, not letters so much, emails. Nobody sends letters anymore, do they? You can send an email, however, to eslpod@eslpod.com, asking questions, giving us your comments, sharing your wisdom about life.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
corporate culture – the types of behavior and relationships that are expected in an office or at work; how people who work in an organization expect each other to behave
* Yolanda could never work in a bank, because she would never feel comfortable in the formal, conservative corporate culture.
to behave – to act in a certain way, especially in a good or bad way
* How do you get your children to behave so well?
workplace – where people work; where business is done, especially in an office, store, factory, or restaurant
* Sexist or racist jokes are never appropriate in the workplace.
personal space – the area around us that we don’t like other people to be in
* Chase was standing in my personal space and it made me very uncomfortable. He was so close that our noses were almost touching!
area of [a] concern – an issue or problem; something that people are worried about
* The patient’s high blood pressure is an area of concern, but these blood counts are even more troubling.
consultant – a person who is hired to provide advice or guidance, usually for a particular project for a set period of time
* The Chief Technology Officer is trying to decide whether the company should hire a full-time programmer, or just use the services of a consultant.
adjustment – adaptation; how people change their behavior in response to some change
* Moving from a large city to a small farming town was a huge adjustment.
far and away – very much; used to describe something that makes up the majority or a very large percentage of what one is talking about
* That singer is far and away the best performer I’ve ever heard.
in excess of – more than; greater than
* Police anticipate crowds in excess of 3,000 at tomorrow’s demonstration.
to mitigate – to make something less risky; to make something safer or less likely to create problems
* Buying a house is a huge decision, but you can mitigate your risk by conducting a thorough inspection.
productive – how efficient someone is, or how much work a person can do in a certain period of time with a certain amount of resources
* Our factory workers would be more productive if they had proper tools and safety equipment.
outpatient – a patient who is treated in the hospital but does not stay overnight
* Were you an outpatient when you had your mouth surgery, or did you have to stay at the hospital overnight?
to gulp – to swallow large amounts of food or liquid quickly; the act of swallowing a quantity of food; to make the sound of swallowing (sometimes as a way of expressing worry)
* Parker gulps his food so quickly that his parents are worried he might choke!
to gobble – to eat food very quickly; to make the sound a turkey makes
* Mindy hadn’t eaten all day, so she was very hungry and gobbled down her dinner in just a few minutes.
to swell – to get bigger or more intense; to fill with emotion; to rise (often from within some part of the body)
* His ankle began to swell immediately after he fell.
What Insiders Know
Adjustments When Living Abroad
Living “abroad” (in another country) can be a “huge” (very large) adjustment for Americans. In many cases, one of the biggest adjustments is the language, since many Americans speak only English and have not studied a foreign language. Moving to another country and suddenly not being able to communicate with the “locals” (the people who live in a particular area) can be very “challenging” (difficult to do).
Adjustments to a new “cuisine” (typical foods and common ways of cooking them) and “expectations” (what people think should happen) for how people should dress can also be challenging adjustments. But these adjustments are “superficial” (related to the outer part of something, but not deep within) and “relatively” (mostly) “predictable” (known or anticipated before something happens).
Other, less “visible” (able to be seen) cultural differences often present greater adjustment issues. For example, Americans generally “value” (think something is important) “punctuality” (doing things on time). When Americans schedule a meeting for 3:00, they think other people will arrive at 3:00. But in some other countries, it might be appropriate to arrive for a 3:00 meeting at 3:30 or 4:00. It might even be “rude” (not polite) to arrive at “precisely” (exactly) 3:00.
Americans also “tend to be” (are usually) “quite” (very) “direct” and “straightforward,” telling other people their opinions and beliefs openly, without “prefacing them” (putting other information before something else) with a lot of “small talk” (unimportant conversations). In many other cultures, this type of direct communication is rude. So American might become “frustrated” (irritated; annoyed) if the locals are not direct in answering questions or expressing opinions.