= 1651
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 346.
This is ESL Podcast’s English Café episode 346. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there, become a member, download a Learning Guide, buy some courses, read our blog, enjoy your life.
On this Café, we’re going to have another one of our Ask an American segments – oh, yes. We’re going to listen to other native speakers talking at a normal rate of speech – a normal speed. Today we’re going to hear about innovation – new ideas in business. And, as always, yes, we’ll answer your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is innovation. “Innovation” (innovation) is sort of the process of creating new ideas, new ways of doing things. We’re going to begin by listening to a man named Steven Johnson. Johnson is what we might call an entrepreneur. An “entrepreneur” (entrepreneur) is someone who invents new things or starts new businesses.
Johnson wrote a book called The Innovator’s Cookbook. An “innovator” is someone who likes to “innovate,” which is the verb from “innovation.” A “cookbook” is normally a book you use to make food. However, it can be used – at least it has been more recently – as a word describing a book that has information about how to do something; how to accomplish something even if it’s unrelated to, as it usually is, cooking. So even though it’s called a cookbook, it’s really more like a manual – a how-to-do something book.
In Johnson’s book, he interviews a lot of different innovative people and businesses. He interviewed one person, Tom Kelly, who has a successful design business, and Kelly told Johnson about how the people in his company think up new ideas at a weekly meeting. He has his top managers – his most important bosses – come together and they have a meeting where part of the meeting is to come up with or create some new ideas. Let’s listen to Johnson describe this Monday meeting that Tom Kelly has with his managers.
[recording]
That meeting, for 20 years, has started with show and tell. People are asked to kinda present interesting things that they stumbled across that weekend. Someone will say, “Hey, I went to see this, you know, movie with my kids last night,” or, “Have you guys seen this new game that, you know, my kids are playing?” Or like, “I went to this art gallery the other day and it was really interesting.” And Tom said it ends up triggering all these new associations and there’s – there’s something, you know, unpredictable about it and that leads to new ideas for their actual business.
[end of recording]
Johnson says that the meeting, which has been part of the company’s culture for 20 years, starts with a show and tell. “Show and tell” is a popular activity in American classrooms, especially in elementary school with young children. And what happens is the teacher asks the students to bring in something interesting from home, and the students talk about it in front of the class and show it to the other students. Johnson says that the meeting uses a kind of or a form of show and tell; people bring in interesting things. He says, “People are asked to kinda present.” “Kinda” is an informal pronunciation of “kind of,” and basically he’s saying they’re asking them to talk about – to present, like giving a presentation – to present interesting things that they stumbled across that weekend. “To stumble (stumble) across (something)” is a phrasal verb meaning you accidentally or without planning on it found something; “came across” is another phrasal verb – “stumble across,” “came across.” You weren’t looking for it, but there it was. You saw it. You went to a store and you stumbled across a sale in the back of the store, and so you bought a bunch of things.
Johnson says that people share new ideas with each other; they talk about the things that they found. It could be something as simple as a movie that the boss had gone to – the manager had gone to. He says, “Someone will say, ‘Hey, I went to see this, you know, movie with my kids last night.’” “You know,” as you probably know, is an expression Americans – English speakers in general – like to use. It doesn’t really mean anything; it’s sort of what we would call a space filler. While you’re thinking about other things to say it’s a word that you, you know, put in your sentence. Or, maybe one of the managers will say, “You guys seen this new game my kids are playing?” So, the managers may talk about a movie they went to, a game their kids are playing, they may talk about an art gallery that they went to. Any of those things could be used to trigger new associations. “To trigger” (trigger) means to cause something else to happen. You can trigger, or start, or cause something to happen really in any kind of situation: “I mentioned that I didn’t like people from New York City, and that triggered an argument.” It caused or started an argument among the people I was with. “Associations” are connections that we make our mind about things and ideas. You have an association, perhaps, between water and the ocean, or rain and Seattle, ‘cause they get a lot of rain up in Seattle in the northwest part of the United States. We all have these different associations.
Well, what happens at this innovators’ meeting – the manager meeting – is people talk about things that have happened to them in the past week, and this helps trigger new associations; it helps people think, “Oh, you know, that’s kind of related to this, which might be related to that,” and it gets them thinking about new ideas. Johnson says that it ends up triggering all these new associations, and there is something unpredictable about it. When we say something is “unpredictable” we mean it’s unexpected; you didn’t know it was going to happen. You couldn’t, in fact, have seen it was going to happen. And these new associations, Johnson says, help this company get new ideas for their actual – their real business, because, of course, the business is not about going to an art gallery or a new movie, it’s about design, but these ideas help trigger new associations that will lead to – that will eventually result in new innovations.
Let’s listen one more time.
[recording]
That meeting, for 20 years, has started with show and tell. People are asked to kinda present interesting things that they stumbled across that weekend. Someone will say, “Hey, I went to see this, you know, movie with my kids last night,” or, “Have you guys seen this new game that, you know, my kids are playing?” Or like, “I went to this art gallery the other day and it was really interesting.” And Tom said it ends up triggering all these new associations and there’s – there’s something, you know, unpredictable about it and that leads to new ideas for their actual business.
[end of recording]
Johnson’s book also includes essays or articles from researchers, people who study innovation at the university – which is not always a very innovative place actually! One of these essays was written by a very famous psychologist. I know her work; I’ve read many of her articles. Her name is Teresa Amabile; she’s from the Harvard Business School. Let’s listen to her talk about innovation and if it’s possible to kill innovation.
[recording]
Absolutely possible to kill creativity. In fact, it seems to be more common inside most workplaces for the work environment to undermine creativity, to kill it, rather than to stimulate it and keep it alive.
[end of recording]
Amabile says that it is absolutely possible to kill creativity. Our recording actually begins with the word “absolutely,” but we think she means it is absolutely. “Absolutely” means completely, she’s saying yes, it’s completely possible. It’s a way to emphasize that yes, this can happen. What can happen? You can kill creativity. “To kill” normally means to end someone else’s life, but in this case, it means to end or stop something. “Creativity” (creativity) is the use of your imagination, your thinking of new ideas, to produce something new. So what Amabile is saying is that it is possible to stop people from being creative, to stop them from thinking of new ideas.
She says, “In fact, it seems more common inside most workplaces for the work environment to undermine creativity.” “It seems (it appears) more common inside most workplaces,” she says. “Workplaces” is just another name for the place where you work: your company, your company’s building. She says it’s common at work, we could say, for the work environment – in other words, the atmosphere, the situation in a certain company – it’s possible for that environment to undermine creativity. “To undermine” (undermine) something is to do something to cause something else to fail or for it not to be possible. For example if you go to an interview – you are meeting to apply for a job, and you don’t wear a suit or a nice dress, you wear t-shirts and some shorts. Well, we could say you’re undermining your chances of getting that job; you’re doing something that will cause you not to get the job. That’s what happens in work environments, Amabile says. She’s saying the environments often undermine creativity; they kill it rather than stimulate it and keep it alive. “To stimulate” (stimulate) here means to encourage people to develop or do more of what they’re already doing. The government may try to stimulate the economy by printing more money. Or they may stimulate inflation by printing more money, which is what they’re actually doing! Anyway, you might try to stimulate someone’s interest in science by taking them to a science museum, or you might want to stimulate your child’s interest in animals by taking them to a zoo, or maybe buying a gun to go hunting. No, that really wouldn’t stimulate their interest in animals – well, in killing animals!
Let’s listen to Teresa Amabile one more time.
[recording]
Absolutely possible to kill creativity. In fact, it seems to be more common inside most workplaces for the work environment to undermine creativity, to kill it, rather than to stimulate it and keep it alive.
[end of recording]
Finally, we’ll listen to another quote from Dr. Amabile – Professor Amabile. She’s now going to talk about how you stimulate creativity, how you get people to be more creative in their workplace. Let’s listen.
[recording]
First of all, people need to feel that they have some degree of autonomy in what they’re doing. They also need to feel personally involved in what they’re doing, that they find it in some way interesting, satisfying, enjoyable, personally challenging. When people are in that mindset, they’re much more likely to come up with new and useful ideas. People also have to feel that, across the organization, they have encouragements for coming up with new ideas, that there are mechanisms for developing new ideas and for learning from problems that inevitably occur when you’re trying to do something different.
[end of recording]
Amabile gives us some things you can do at your work to stimulate creativity. She says, “First of all (the first thing), people need to feel that they have some degree of autonomy.” “Some degree of” means, really, some amount of autonomy. “Autonomy” (autonomy) means the ability to be able to control what you are doing, not to be controlled by someone else. Sometimes you’ll hear this word in politics, talking about for example a part of a country that wants to be autonomous; they don’t want to be controlled by what we might call the central government – the main government.
Amabile says people also need to feel personally involved in what they are doing. They need to feel like this is something that they’re interested in, that they want to do. She says people need to find what they’re doing interesting, satisfying, enjoyable – all good things – and personally challenging. Something that is “challenging” is a little bit difficult for you. But most of us like to have some things a little bit difficult, it gives us some motivation to do better. She says, “When people are in that mindset, they’re much more likely to come up with new and useful ideas.” Our “mindset” (mindset – one word) is our way of thinking; it’s our attitude toward something.
The good doctor continues by saying, “People also have to feel that, across the organization, they have encouragements for coming up with new ideas.” “Across the organization” means in the whole company, everyone working for the company. They have to feel like they will get some praise – they will get some encouragement for coming up with new ideas; they will be rewarded perhaps. She says there also needs to be mechanisms for developing new ideas. A “mechanism” (mechanism) is a process, in this case, for something to happen, a series of steps: this happens, then this happens, then that happens. A mechanism can also be a physical part of a machine. The word “mechanism” and “machine” come from the same root – the same basic word. She says there needs to be a mechanism for developing new ideas and for learning from problems that inevitably occur when you’re trying to do something different. So when you do something different, there will be problems. She says these problems are inevitable. Something that is “inevitable” (inevitable) is something you cannot avoid, something that is certain to happen. If you go to Minnesota in January and February, it is inevitable that it will be cold and snowy. But if you come to Los Angeles, it is inevitable it will be warm and sunny.
Let’s listen to Amabile talk one more time about what she believes is needed to encourage innovation.
[recording]
First of all, people need to feel that they have some degree of autonomy in what they’re doing. They also need to feel personally involved in what they’re doing, that they find it in some way interesting, satisfying, enjoyable, personally challenging. When people are in that mindset, they’re much more likely to come up with new and useful ideas. People also have to feel that, across the organization, they have encouragements for coming up with new ideas, that there are mechanisms for developing new ideas and for learning from problems that inevitably occur when you’re trying to do something different.
[end of recording]
Now you know all there is to know about coming up with new ideas. Now let’s answer some of the questions you have sent to us.
Our first question comes from Sergio (Sergio) from an unknown country – Country X, Country Y maybe. Sergio wants to know the meanings of three words: “pain,” “sorrow,” and “woe.” Well, that’s a happy question Sergio, thanks for asking!
“Pain” (pain) is when you have any sort of bad feeling in your body or in your mind. If you hit your head on a piece of wood you would have a pain, it would hurt. Or, if your girlfriend said she was leaving you for your brother you would also have a pain – and maybe a fight with your brother! “Sorrow” (sorrow) is a less common word, it means very sad; a deep sadness, we might say. When someone dies or when something terrible happens, you may feel this sense of sorrow. Notice the expression “a sense (sense) of sorrow.” “Woe” (woe) is also extreme sadness, a lot of sorrow. “Woe” is a word that would be used to describe a disaster or something that was really terrible that happened.
“Pain,” then, is a very general word to talk about something usually in your body or in your mind. “Sorrow” is an emotion; it’s a sadness. “Woe” is a lot of sorrow, it’s even worse than sorrow. “Woe” is a little – well, I don’t want to say old-fashioned. It’s still used, but it’s not as common as it was before I’m guessing. It’s something you would probably see in a book more than hear in a conversation. Someone might say, “Oh, I have a lot of woes.” I have a lot of problems; that’s one possible use of it that you might hear, but it’s not that common. People nowadays, if they use it at all, will use it to describe some big problem rather than an emotion of sadness as I mentioned before: “I have a lot of woes,” or we could talk about the economic woes of our country.
Our next question comes from Ayanle (Ayanle), originally from Somalia but now living in Minnesota. There are a lot of Somali people who live in Minnesota now. The question has to do with the word “manhood” (manhood). Well, there are some common uses of this word that you can use with anyone, and then there is a use of this word that is a little more vulgar, shall we say – informal. Let’s start with the ones that are commonly used and can be used with anyone.
The first is a period of time when one is a man; one is an adult male. In the United States, our common belief is that when you turn 18 years old you become a man. So, your “manhood” would be the time after you’re 18 years old if you are, of course, a male. “Manhood,” however, can also be used to describe the characteristics, the traditional things that we associate with being an adult man – an adult male: courage, determination, physical strength. Usually the expression that this is found in is when someone says, “He wants to test my manhood.” He wants to see how tough I am, how strong I am, whether I’m a real man. It’s sort of a macho thing.
Now, there’s a third meaning of “manhood,” which is somewhat vulgar and used only informally, and certainly not with anyone other than a close friend, and that’s to mean a man’s sexual organs – his genitals. In that use, “manhood” would be considered rather informal and, as I say, somewhat vulgar, not something you would ever use in daily conversation. It would be used jokingly in most cases.
Sherri (Sherri) is going to help us change the topic. Sherri’s from Hong Kong, and she has a question about a couple of expressions: “to be over (someone)” and “to be all over (something).” Well this is an interesting question, because these two words – these two expressions rather – are rather different. Well, I shouldn’t say that; there’s some connection. Let’s start, however, with the expression “to be over (someone).”
“To be over (someone)” means you no longer love that person. Maybe you were dating them for a while and you liked them a lot, maybe you even loved them, but then they left you. She left you and went with your brother, and now you say, “Oh, I’m over her. I’m over Cindy.” “I’m over...” I have to be careful not to use the names of any ex-girlfriends here! “I’m over Susie.” Did I have a girlfriend named Susie? No, no. So it means you are no longer in love with that person. “I’m over that person” means I’m no longer in love with that person.
Now, “to be all over (something)” can be a positive thing, it can be a negative thing, or it can be somewhere in between – a neutral thing. One meaning of “to be all over (someone)” – a person – would mean to be with your boyfriend or girlfriend, your husband or your wife, and to be touching them and kissing them in a romantic way, especially if you’re in public. Other people might say, “Wow. Did you see those two people? They were all over each other.” Or, “He was all over her.” Notice you have to say “all” here, you can’t say “he was over her,” you would have to say “he was all over her.” That’s something very different; that means that he was touching her and kissing her in a romantic way. That’s a positive, if you will, use of “to be all over (someone).” It can also be used in a negative way when you don’t like someone and what they’re doing and you start yelling at them. “My boss got angry at me for not finishing my project. He was all over me.” He was yelling at me, and telling me all the bad things that I did, and so on. To know the difference, you just have to know the context – the situation, the circumstances of the conversation you’re hearing or reading about to know which of those meanings “to be all over (someone)” is.
I mentioned that “to be over (someone)” means you no longer love them. You can also be over a situation or a certain thing. “I was mad at my brother for taking my girlfriend, but now I’m over it.” “It” being the fact that my brother took my girlfriend. I’m over it; it’s history, we might say informally. It doesn’t matter; I don’t care anymore, I’m not bothered by it. I’m over it.
My brother actually did go out with a girl that I went out with first, when I was in high school, and I didn’t really care. I didn’t like the girl that much, but it was kind of weird, you know, when your brother goes out with a girl that you were dating. Well, I was in high school; I can’t really say we were dating very much. We were friends more than anything. Yeah, I’d forgotten about that. Thanks a lot Steve! Thanks for taking my girlfriend, yeah! I’m not over it!
If you have a question or problem – well, a question, don’t send me your problems – email us at eslpod@eslpod.com, we’ll do our best to answer them.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
show and tell – an activity where each member of a class or a group brings something interesting to show and to talk about with the rest of the group
* During show and tell, Benoit showed the other students a house he had made using soda cans.
to stumble across – to meet something by chance; to see, hear, or experience something that one did not seek
* When I was at the library looking for books about home repair, I stumbled across a book about animals that my son might like to read.
to trigger – to cause something else to happen; for an event or thing to cause another event or action
* The government’s decision to raise taxes triggered protests in several large cities.
association – connection in one’s mind; one’s thinking linking ideas and things
* Because of a swimming accident when Laurent was 10 years old, he still has an association in mind of danger every time he sees water.
unpredictable – unexpected; uncertainty about the future
* The outcome of the contest was unpredictable because no one knew how many people would enter it.
to kill – to end another person’s life; to stop; to end
* The mayor killed a project to build a high-speed train between Los Angeles and San Francisco because there wasn’t enough money to complete it.
creativity – the use of one’s imagination to produce something new; the use of one’s mind to think of new ideas
* Writing science fiction books takes a lot of creativity.
to undermine – to damage; to make weaker; to act (or not act) so as to cause something to fail
* It doesn’t work when one parent undermines the other by not enforcing rules.
to stimulate – to encourage development; to cause an increase in activity
* Can you think of any ideas to stimulate sales of luxury cars in a slow economy?
autonomy – independence; being free of another person’s control; being able to make one’s own choices and decisions
* Many teenagers want autonomy to decide how best to spend their free time.
mindset – one’s way of thinking; one’s attitude toward something
* The weekend is not a productive time to work, because my mindset is on relaxing and spending time with my family.
mechanism – a process that has already been established for something to happen, such as routines, policies, or rules
* Is there a mechanism at this school for students to change their field of study after they’ve already a completed one year of coursework?
inevitable – unavoidable; something certain to happen
* If we believe that war is inevitable, we won’t do all we can to avoid it.
pain – any bad feeling in the body or the mind
* The pain in Gail’s leg was nothing compared to the pain she felt at seeing her only child hurt in the accident.
sorrow – deep sadness; feeling very sad
* Nic felt a great sorrow when he had to close the factory that his grandfather built.
woe – extreme sadness, especially from grief or major disasters
* This is a story of woe, with deaths in the family, disaster in the town, and suffering for everyone.
manhood – the state or period of time of being an adult male; traditional qualities related to a man; used informally to mean a man’s genitals/penis
* Parents want their sons to reach manhood having gained the knowledge and skills to live on their own.
to be over (someone) – to be finished feeling romantic love or liking for a certain person
* Marcia and Lev ended their relationship over six months ago, but Marcia still isn’t over Lev.
to be all over (someone) – to kiss or touch a person in a romantic way, especially in public
* The parents at the dance are supposed to keep the teenagers from being all over each other.
What Insiders Know
Dot Com Movies
The movie “industry” (business) has “taken notice of” (given attention to) the quick “rise” (rise in popularity) of Internet-based businesses in the past 20 to 30 years. These “dot com” movies are usually about a person or a group that starts a company or a website on the Internet and becomes “rich” (having a lot of money) and “famous” (well-known) from it, sometimes with “lasting” (for a long period of time) success and sometimes with “brief” (for a short time) success.
The most famous example of a dot com movie is The Social Network. This movie was made in 2010 and is about Mark Zuckerberg (played by Jesse Eisenberg in the movie), the creator of the “Facebook” website. Facebook is one of the most popular websites on the Internet and lets people send emails and “instant messages” (short, quick email-type messages) to their friends. It also lets them update others about their mood through “status updates” or short “public” (seen by everyone) statements that let everyone know what they are doing at that moment. Zuckerberg created this website when he was a student at Harvard University, but he was later “sued” (taken to court and asked to pay money) by a friend who helped him start the company, as well as by two brothers who said that he stole their idea. The Social Network shows the good side and the bad side of Zuckerberg’s fame, as well as that of his friends and “partners” (people he worked with on the website).
Another dot com movie is 1999’s Pirates of Silicon Valley, which is about the creation of the “home computer,” a version of the larger computer that is small and cheap enough to use in one’s own home. This movie, which was made for television instead of the movie theater, tells the story of the “rivalry” (competition) between Steve Jobs, the leader of the Apple computer company and Bill Gates, the leader of the Microsoft computer company. The movie shows how they fought at first, but later became partners. The movie was very popular with television audiences, and “starred” (included the actors) Noah Wyle as Steve Jobs and Anthony Michael Hall as Bill Gates.