= 1632
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 327.
This is English as a Second Language Podcast’s English Café episode 327. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and become a member of ESL Podcast, help support this podcast, help keep it going.
On this Café, we’re going to continue our series on famous Americans. We’re going to talk today about a very famous actress in the United States in the 20th century, Lucille Ball. We’re also going to talk about the Great Depression in the United States, and what that was, what that meant for the history of our country. And, as always, we’ll answer a few of your questions. Let’s get started.
We continue our series on famous Americans focusing, on this Café, on actress Lucille Ball. Lucille Désirée Ball, better known simply as Lucy, but not to be confused with our own dear scriptwriter, Lucy Tse. Lucy Ball was best known as an actress, but she was also a comedian, a model, and someone who made film and television productions, an “executive” we would call her.
Lucille Ball was born in Jamestown, New York in 1911. As a little girl, she loved theater and drama; she loved going to see plays. She studied at a drama school in New York City when she was a teenager, but she was told that she had no future as a performer. The phrase “to have no future as (something)” means that you will not be successful in that thing. Some people think they have no future as a mathematician or a singer, or a podcaster. But then, later in life, you discover yes, I can sing, I can podcast, and so forth. Just can’t do both, sing and podcast!
Lucy was told she had no future as an actress, but they were wrong. Lucy ended up being extremely successful, although not in the beginning – not at first, we would say. It did take some time. She got some small roles – some small jobs acting on Broadway in New York City, which is live theater. We talked about Broadway a couple times on the English Café: number 62 and number 140.
In the early 1930s, Lucille Ball moved to Hollywood – to Los Angeles, California. She began working as an actress in films – in movies, but people began to call her or to refer to her as the “Queen of the Bs.” That’s “B” as a capital letter, not “bee” the insect. The reason they called her the “Queen of the Bs” is that she made a lot of what were called “B-movies.” “B-movies” are movies that you don’t spend a lot of money on; they don’t have what we would call a “big budget,” a lot of money. The actors in B-movies aren’t as well known as the actors in the more expensive films. As the Queen of the Bs, Lucy also worked as an actress in radio, producing voices for characters, in order to earn more money.
Eventually Lucy earned stardom, not with a movie, but with a television show. You may have seen it, even in your country. It was made back in the 50s, called I Love Lucy. She entered stardom with this television show. “Stardom” means fame, you’re famous; people know who you are. Celebrities, actors, singers, musicians all achieve stardom when they become famous.
I Love Lucy ran as a television show – it was “on the air” we would say – from 1951 to 1957 and became at the time the most popular, the most-watched television show in the United States. Everyone who grew up in the 1950s had seen I Love Lucy – everyone who had a television. However, the show didn’t really end in 1957 because, just like they do nowadays, they began to show the old shows over again, what we would call “reruns” (reruns), where they repeat the same television show, often late at night or in the middle of the day. I grew up watching reruns of I Love Lucy in the 1970s, and I think you can still watch I Love Lucy on some of the satellite or cable television channels even today.
I Love Lucy was a “comedy,” it was a show that made people laugh, and the star was Lucy and her real-life husband, her actual husband, Desi Arnaz. In the television show Lucy and her real husband – and television husband – were living in a building and were friends with the owners of that building, another couple.
The show was considered at the time very pioneering. “To be pioneering,” or to be a “pioneer” (pioneer) means to do something that no one else has done before. Normally, as a person – as a noun the pioneers were the first people to go to a certain part of the country or to go to a new country. Well, they say I Love Lucy was a pioneering show because it did things that other shows – other TV shows – had never done. I Love Lucy was filmed or made in front of a live audience. In other words, they brought in a group of people to watch them make the television show, and you can hear those people laughing. This became very common. I don’t know if it’s still done today, but it was very common in the 70s and 80s I remember. The show was also pioneering for showing the white, red-headed Lucy in her marriage to a Latino, a man born in Cuba. It also was pioneering in showing Lucy on television while she was pregnant, and talking about her being pregnant. At the time, many people thought that was somewhat shocking, somewhat unusual. Now, of course, we wouldn’t think it was unusual at all.
I Love Lucy is often listed as one of the best television shows; some people think it was the best television show made in the 20th century because of the comedy and the other parts of the show. I’m not sure if I would say it’s the best show. It is a show, however, that has a lot of laughter in it, and a lot of physical humor. As someone learning English, it may, in some cases, be easier to understand than some of the modern comedy shows. The show was filmed in black and white; it’s not color. It was before the time when television shows were commonly in color.
I Love Lucy was produced by a company called Desilu, which was headed by her, Lucy, and her husband, Desi Arnaz. Lucy became very active and powerful in the television world after her series, and during her series in the 1950s. In 1960, she divorced her husband. She remarried – she married again – the following year and that marriage – that second marriage – lasted until her death in 1989.
Lucille Ball received many awards for her work, including the Presidential Medal of Freedom Award, one of the highest awards that can be given an American citizen. She was given that award just a few months before she died in 1989. People today who’ve seen her television show, which is probably most Americans or at least most Americans of my age, still remember Lucy “fondly,” that is, with affection; we think good things about her because she entertained us, she made us laugh. In August 2011, which would have been her 100th birthday, there were more than 900 look-alikes that got together in a party in her honor. A “look-alike” is someone who looks like someone else, especially someone famous. I’ve often thought of myself as a Brad Pitt look-alike. No one else seems to think the same, but I definitely think it’s true! Anyway, in August, almost 1,000 Lucy look-alikes put on red wigs – remember, she had red hair – and dressed like Lucy and got together for a big party.
So, if you haven’t seen I Love Lucy, you can find it, I’m sure, on the Internet nowadays, probably find old episodes on YouTube even. I think you might enjoy it.
Now let’s turn to our next topic, which is not a person but a time during the 20th century, which we call the Great Depression. Many people complain about the economy nowadays, now in the current years, in the year that this podcast is being recorded, but things were much worse during the early part of the 20th century, during the time we call the Great Depression.
We often use the word “depression” to talk about feeling sad, but economists use the word to describe the economy slowing down considerably, and having that slowdown – that lower amount of economic activity last for a long time.
The Great Depression began in 1929 and lasted throughout the 1930s, so more than 10 years really. In the United States, the Great Depression began, as I said, in 1929, in September of that year, when the stock prices started to fall dramatically. In October of that year, October 29th, there was something known as a stock market crash; we sometimes call it Black Tuesday. A “crash” usually is what happens when two cars hit each other, but it can also refer to a rapid drop in the price of something; in this case, the price of stocks. Well, the stock prices – and remember “stocks” are just partial ownership that people have in different companies – stock prices dropped dramatically on Black Tuesday.
The income that people were getting, both individually and their companies, began to fall also, and so, of course, the government did not have money because people couldn’t pay taxes on money they didn’t have – they didn’t have to because they weren’t making any money. Many people lost their jobs during this period. In fact, the unemployment rate – the number of people who didn’t have jobs – was around 25 percent during the Great Depression. This made it, of course, a very difficult time for American families.
The U.S. government didn’t really know what to do – that’s not unusual! They tried to stimulate the economy in many different ways. “To stimulate” means to make something happen, to help something grow. You could stimulate a plant by giving it more light and more water. The government was trying to stimulate the economy, to get the economy to grow. It tried a lot of different things. It tried reducing the amount of money it would charge to loan people money, what we would call the “interest rate.”
The president in 1929, Herbert Hoover, tried to stimulate the economy but wasn’t successful. Finally, a new president was elected, Franklin Delano Roosevelt, in 1932; he began as president in 1933. However, the situation became worse, especially due to a drought in the United States. A “drought” (drought) is a long period of time without rain. So in addition to the normal economic problems that were taking place there were also these natural problems, if you will, the problem of a drought.
Roosevelt responded with a group of government programs that were supposed to help people during this difficult time. These programs are called the New Deal; that’s what Roosevelt called them. A “deal” is like an agreement. So, this was like a new way of the government doing things with the people. He passed a lot of laws, what we would call “legislation,” to make sure that the money you put in banks was guaranteed; it was insured, technically; to regulate how stocks were bought and sold. He created something called the Social Security Administration, which was supposed to help people who were poor and people who were old and didn’t have any money after they left their jobs.
The New Deal also created a program called the Civilian Conservation Corps, or the CCC. This program gave jobs to more than 3 million young men, most of whom did or performed what we would call “manual labor.” “Manual labor” means working with your hands, not in an office. Many of the men in the CCC were sent to areas, especially in the Pacific Northwest, to build buildings, or what were called “lodges” (lodges), to improve the park system, and so forth. My uncle was one of the young men who work with the CCC; he was given a job by the CCC.
There were other famous organizations that Roosevelt started to give people jobs. One of the most famous was called the PWA, the Public Works Administration. This organization – government organization hired men and women to build buildings in cities and in towns that that needed, for example, a new library. Many of the libraries in the United States were built by the Public Works Administration. Parks and buildings for parks were also built. Where I grew up, in St. Paul, the library down the street, four blocks from where I grew up, was built by the PWA. The building for the playground where I played – well, I was going to say I played baseball, but I didn’t really play baseball; that’s a long story. Anyway, the playground building was also built by the Public Works Administration. So, you can still see many of these buildings built in the 1930s here in the U.S. if you visit one of our cities.
Roosevelt’s programs were somewhat successful in helping people who needed money to live, but they were also very expensive, and ultimately they did not help end the Great Depression. It wasn’t until 1941, when the United States entered World War II, that the economic depression ended. This, of course, wasn’t a very good way to end a depression, but it did end the Depression. And, still to this day, the Great Depression is something that people remember. There are fewer and fewer people, however, who were alive during that time. Both my mother and my father lived through the Great Depression. My mother was born in 1927, my father in 1923, so they were both children and teenagers going through this difficult time. Fortunately, both of their parents had jobs, but there wasn’t a lot of money around, and that was true for many American families during this difficult time.
Now let’s answer some of the questions that you have sent us.
Our first question comes from Riyadh (Riyadh) in Saudi Arabia. The question is about the meaning of three words: “hermit,” “loner,” and “introvert.” Let’s start with “hermit” (hermit). A “hermit” is a person who withdraws from society, who doesn’t live near anyone else; he lives by himself. Hermits have a long tradition, especially in the Christian church. There were traditionally hermits, who for religious reasons, would go and live by themselves somewhere. It’s a word nowadays that would probably be considered a negative description. If you say someone is a “hermit,” you’re saying they don’t like to associate with other people, so it’s definitely a negative thing.
A “loner” (loner) is a person who doesn’t live by themselves, but who has few friends; they may live by themselves, but they often avoid other people, not for any religious reasons. A “loner” is someone who, perhaps, just doesn’t make friends easily. It does have, again, something of a negative meaning; when you say someone’s a “loner” that may be negative thing, it depends on the situation.
“Introvert” (introvert) is a term from psychology to describe someone who’s very shy. This is a person who isn’t a loner. They may have friends, but they don’t like to talk a lot. They’re not, what we would call, “outgoing.” In fact, the opposite of an “introvert” is an “extrovert,” (extrovert) and that’s someone who likes to go out and talk to lots of different people.
But there is a connection among these three words of “hermit,” “loner,” and “introvert.” All three terms could be neutral; that is, they could be positive or negative or neither. However, “loner” is usually used when talking about younger teenage kids – high school students. “Introvert,” as I said, is a more psychological term – a more technical term, if you will – to describe people who don’t like to go out and talk to other people very much.
Our next question comes from Riaz (Riaz). I don’t know where Riaz is from, but I do have the question. The question is what is the difference between “other than” and “rather than.”
“Other than” means except for or aside from. For example: “Other than the F I got in chemistry, I got all A’s in my classes last semester.” In other words, there was one case where I didn’t get an A, that was in chemistry. Actually, for me the problem wasn’t chemistry, it was more physics. Physics was hard for me in high school. That’s why I’m not a physicist!
“Rather than” means in place of or instead of. “I’m going to take music rather than physics.” I’m going to take a music class instead of or in the place of physics. This is different, of course, “other than” means, again, except for. “Other than failing his test, not coming to class, and not doing his homework, Johnny is an excellent student.”
Finally, Ali (Ali) from Iran wants to know the meaning of an expression that he read: “Et tu, Brute?” This is actually a Latin expression: “Et” (Et), “tu” (tu), and then the name “Brute” (Brute). Literally, from the Latin, it means “And you, Brutus?” This is often used to accuse someone of being disloyal, of doing something to help your enemy or someone who’s trying to hurt you.
The expression comes from the play Julius Caesar by Shakespeare – unless he stole it from somewhere else, which is possible. What happens is, you probably know, Julius Caesar is killed by people who he thought were his friends, at least some of them. Brutus was his friend, and yet Brutus also kills Caesar with his knife. So, “Et tu, Brute?” is what Caesar said. “Even you, Brutus?” is what Caesar is saying.
We would use it, again, in a situation where someone has betrayed us, has been disloyal to us, has done something to help someone who is trying to hurt us. So, your girlfriend finds that you have stolen something and she calls the police, and the police come to take you, and they tell you that it was your girlfriend who called. You may turn to her, even though she can’t possibly be Brutus, and say, “Et tu, Brute?” Let’s hope that doesn’t happen to you!
If you’re a hermit listening to this podcast, you can still email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
to have no future as – for it to be unlikely that someone will be successful in doing something; to not have the skills, ability, talent, etc., to be successful at doing something
* James is afraid of needles, so he probably has no future as a nurse.
B-movie – a low-budget film; a movie made without spending very much money
* Before he became a big movie star, he acted in a lot of B-movies.
stardom – fame; known to or talked about by a lot of people because of something one has done or achieved
* Michael dreams of stardom as a professional basketball player.
rerun – repeated episodes of the show shown on television; the showing of a television show that had already been shown at least once before
* When Paola can’t sleep at night, she likes to watch reruns of her favorite sitcoms.
pioneering – for something or someone to do things that has never been done before; doing something new that no one else has done before
* Jamal is a researcher who is doing pioneering work in economic theory.
fondly – with affection; with warm and positive feelings
* Grandpa looked fondly at his grandchildren as they played silly games.
look-alike – a person who looks like someone else, especially a celebrity
* If you visit Hollywood Boulevard, you’ll see celebrity look-alikes of Elvis, Marilyn Monroe, and other stars.
depression – slow economic activity that lasts for a certain period of time; a period of time with major economic problems
* Do you think we are entering a depression, or do you think the economy will improve over the next year?
crash – a rapid drop related to money; a big and sudden decrease in price or value
* After our earnings report was released on Monday, the price of our company’s stock crashed.
to stimulate – to do something that will cause something else to happen; to do something to help something grow or increase
* To stimulate interest in using public transportation instead of driving cars, the city government is giving away one-week bus passes for a limited time.
drought – a long period of time with very little or no rain; not having enough water because of little or no rain
* If the drought doesn’t end soon, the crops on our farm will be destroyed and we will have no income this year.
manual labor – working with one’s hands; doing physical work
* Miyung and Suki both work in offices all week, so they like doing manual labor around their ranch on weekends for a change.
hermit – a person who does not interact with other people and lives alone, often away from town
* There is a hermit who lives in a cabin in the mountains, whom few people have seen.
loner – a person who has few friends, often choosing to avoid other people
* In high school, Nancy was a loner, who sat by herself at lunchtime and didn’t join any clubs.
introvert – a shy person; a person who likes to spend time alone rather than in groups
* It’s hard to believe that Manuel and Carlos are brothers. Manuel likes to go to parties and be around a lot of people, while Carlos is an introvert.
other than – except for; aside from
* Benoit has never wanted to travel far from his home, and other than a week spent in Texas when his brother was in the hospital, he has never left the state.
rather than – in place of; instead of
* Allie is very angry right now and rather than try to talk to her, why don’t you take a walk and come back later?
Et tu, Brute? – Latin for “You too, Brutus?”, used to accuse someone of being disloyal or doing something to help the enemy, from William Shakespeare’s play Julius Caesar
* Sheila was used to people telling her that she couldn’t become a famous singer, but when her best friend said the same thing, Sheila responded, “Et tu, Brute?”
What Insiders Know
The Cecil B. DeMille Award
If you are a “fan” (enthusiastic follower) of television shows and movies, you may look forward to the Golden Globe Award show each year. Unlike the Emmy Awards, which “honor” (give recognition and respect to) only television shows and the Academy Awards, which honor film, the Golden Globe Awards honor both television and film.
Each year, the Hollywood Foreign Press Association, which “grants” (gives; awards) the Gold Globe Awards selects one person to receive its award for outstanding “contributions” (work that helps or enriches) to the world of entertainment, the Cecil B. DeMille Award. Most of the people who receive this award are those who have had a “lifetime” (throughout one’s life) of excellent work, not just one or two “noteworthy” (worth notice or attention) contributions.
Cecil B. DeMille was an American film director who lived between 1881 and 1959. His films included both “silent” (without sound) films and films with sound. He was known for producing films that were large in “scope” (amount that it covered or addressed). His most well known films were The Ten Commandments (1956), Cleopatra (1934), and The Greatest Show on Earth (1952).
The Cecil B. DeMille award was first “awarded” (given) in 1952. The youngest person to receive the award was Judy Garland in 1962, when she was only 39 years old. This is “remarkable” (worthy of notice; incredible) considering that this award is for a person’s “body of work” (collection of work; total production) over one’s lifetime. Judy Garland was also the first woman to receive the award. Lucille Ball received the Cecil B. DeMille award in 1979 when she was 67 years old.