= 1614
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 309.
This is English as a Second Language Podcast’s English Café episode 309. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Download the Learning Guide for this episode, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about a well-known American movie, West Side Story; it was also a Broadway musical. We’ll also talk about a patriotic character, very famous, Uncle Sam. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of a well-known movie called West Side Story. The area known as West Side is a part of New York City, in particular the borough or part of the city called Manhattan, which is the main downtown business section of the city. You can guess, of course, that the West Side Story takes place in New York City. You may not know that it is a love story that is based on a famous tragedy by Shakespearean, a play – a sad play, Romeo and Juliet. Romeo and Juliet is a play about thwarted lovers. “To thwart” (thwart) someone means to prevent or stop someone from doing something that he or she wants to do. So, thwarted lovers would be two people who fall in love, but are not able to have a romantic relationship, in this case because their families or their culture doesn’t permit them to.
West Side Story is a love story about young, thwarted lovers. But they don’t come from different families as they do in the Shakespearean tragedy; rather, they come from different gangs. A “gang” (gang) is here a group of young people, usually teenagers, in a city, what we would call an urban area. Gang members spend a lot of time together mostly getting into trouble, often using violence to scare people, to steal things, to sell drugs, and so forth. Unfortunately, here in Los Angeles we have a lot of these gangs; they tend to be, as I said, associated with illegal drugs, racial violence, killings, and so forth. But back when this story takes place – it is set in the 1950s – gangs were a little less violent. This story is about two rival gangs. “Rivals” (rivals) are people or organizations that fight against each other, especially when they are both very strong and good at what they do. You could have rival sports teams: the Los Angeles Dodgers and the San Francisco Giants, or the Boston Red Sox and the New York Yankees. They’re rivals; they both want to win; they are opposite or opposing teams.
Well, these are rival gangs. The gangs have names. One of the gangs is called the Jets and the other one is called the Sharks. The Jets – and I’m not sure if this refers to an airplane which is called a jet; it might be short for something, I don’t remember. The Jets are white, working-class young men and their girlfriends. Working-class means that they don’t go to college; they work in jobs that don’t require a college education typically. The Sharks are Puerto Rican immigrants. Puerto Rico, you probably know, is a territory of the United States in the Atlantic Ocean. It became part of the U.S. after the Spanish American War in the late 19th century. In any case, a lot of Puerto Ricans – who are American citizens – have gone to New York City. There’s a large Puerto Rican population there, and has been for many years, including back in the 1950s. Well, the Sharks, then, are Puerto Rican immigrants. The Jets are white, working-class men and women – boys and girls, in many cases. So, there’s a ethnic or cultural difference between these two groups.
One of the Jets, one of the white gang members, a man named Tony, falls in love with a woman from the Sharks, a woman – a girl named Maria. Maria is the sister of the leader of the Jets. Now obviously, this upsets everyone; it makes everyone angry because these are rival gangs and they’re not supposed to be falling in love with each other. The gangs, if that happened, would lose their identity; they wouldn’t be special anymore.
West Side Story shows the consequences of Tony and Maria’s relationship. It’s a very poignant story. When we say something is “poignant” (poignant) it makes you feel sad, it’s something very emotional that affects you deeply. West Side Story makes you feel sad for Tony and Maria, but it also makes you think about things like the relationship between different ethnic groups and racial groups, immigration, how people feel about dating people who are not from your background, who are perhaps from a different cultural background.
West Side Story, as I mentioned, was originally a Broadway musical. A Broadway musical is a musical play that appears in New York City. It’s called Broadway musical because Broadway is the street where many of the theaters are. It was first produced in 1957. Like many American musicals, they have singing and dancing. The script was written by a man named Arthur Laurents, who you probably have not heard about before. You have heard about the person who composed the music, I think; that was Leonard Bernstein. Bernstein was one of the great American conductors and composers of the 20th century; some people say he was a better conductor or leader of the orchestra than he was a composer. In any case, the lyrics to the songs in the musical were written by another famous American in the world of music, Stephen Sondheim. The play was popular on Broadway, and what happens sometimes with popular musicals is that they become movies. This became a movie in 1961; it was directed by Robert Wise and Jerome Robbins.
The songs in West Side Story are very well known, or least they were well known when I was growing up. I remember seeing the movie on television many times. One of my favorites songs is one of the most popular songs from the movie and the musical, a song about Maria, which Tony sings right after he learns the name of the girl he has fallen in love with. It goes something like this: [Jeff sings]
Maria!
I’ve just met a girl named Maria,
And suddenly that name
Will never be the same
To me.
Maria!
I’ve just kissed a girl named Maria,
And suddenly I’ve found
How wonderful a sound
Can be!
Ah! “Maria! / I’ve just met a girl named Maria / And suddenly that name / Will never be the same / To me.” Then he sings, “I’ve just kissed a girl named Maria / And suddenly I’ve found / How wonderful a sound can be!” Of course, the sound of the person you love is a wonderful sound; that’s what love is all about, and Tony is in love with Maria.
Another interesting song sung by the other rival gang – or members of the other rival gang the Sharks, is called “America.” It’s sung by the girls or the women in the Sharks, the Puerto Rican gang. They’re all Puerto Rican, but one of them, Rosalia, is signing about how wonderful the island of Puerto Rico is, while another one, Anita, is singing about how she doesn’t like Puerto Rico and prefers life in the United States. So, the song has both women singing back and forth, talking about the pluses and minuses, the pros and cons, the good and the bad about living on the island of Puerto Rico versus in the mainland United States, in New York City. It’s a funny song. The singers, at least in the musical, sang it with something of a Spanish-influenced accent; it was sung in English, as all the songs were. The chorus, or repeating part of the song is the one that at that most Americans will probably recognize. It goes something like: [Jeff sings]
I like to be in America!
Okay by me in America!
Ev’rything free in America
For a small fee in America!
So, pardon my Spanish accent! “I like to be in America! / Okay by me in America!” The idea is that their English isn’t perfect. The next line is “Ev’rything free in America,” rather than everything is free in America. And then one of the other singers says “For a small fee in America!” A “fee” is the price that you have to pay to do something, meaning it’s not really free, America, you have to pay a price for it.
There are a couple of other famous songs; we don’t have time to talk about them all. Two more are “I Feel Pretty,” which is sung by Maria after she has fallen in love and everyone around her thinks she is acting very strangely, but they don’t know why. The song begins with her singing: [Jeff sings]
I feel pretty,
Oh, so pretty,
I feel pretty and witty and bright!
Another famous one is called “When You’re a Jet.” I really like this song, describing what you need to be in order to be a member of this gang: [Jeff sings]
When you’re a Jet,
You’re a Jet all the way
From your first cigarette
To your last dyin’ day.
“When you’re a Jet / You’re a Jet all the way (your whole life) / From your first cigarette (the first time you smoke a cigarette) / To your last dyin’ day (till the day that you die).”
The chorus parts of these songs are all very catchy. When we say something is “catchy” (catchy) we mean it’s easy to remember; you remember it after hearing it only a couple of times.
West Side Story is a very fun movie to watch, especially if you like musicals. It’s also a musical that talks about some problems, problems that were already becoming apparent, already being noticed in the 50s and 60s, and became even more important in American culture in the 70s and after. So, it’s a great movie to learn about American culture, and a fun movie to enjoy music and dancing.
Since we’re talking about American culture, as we always do, let’s turn to our next topic, which is the figure of Uncle Sam. Uncle Sam isn’t actually a person. He’s a symbol for the United States government, and I’m sure you’ve seen Uncle Sam in pictures.
Some people think Uncle Sam was named after a man named Samuel Wilson, a man who was a meat-packer, someone who prepares meat to be sent to stores. Samuel Wilson worked in New York in the early 19th century, in the early 1800s. He and his men worked with containers used to ship or send meat to the army, and those containers were labeled “U.S.,” which of course meant the United States. Some people joked, however, that U.S. was Uncle Sam, for Samuel Wilson, who was one of those preparing these packages.
When you see a picture of Uncle Sam, he’s usually “depicted” or shown in drawings as an old, thin white man with white hair and a long goatee. A “goatee” (goatee) is a long beard that only comes down from the bottom of your “chin,” the part of your face below your lower lip – your lower part of your mouth. It makes a man look a little like a goat, and that’s why it’s called a goatee. Uncle Sam always wears American colors of red, white, and blue. For example, his hat may have a wide blue band or line around it with white stars; his clothing may be red and white, just like the American flag. He always has red, white, and blue on, because those are the American colors.
We first find the image of Uncle Sam at the very beginning of our history as a country, during the War of 1812, a war against Great Britain. But it really became familiar to Americans beginning more than 100 years later in 1916, just before the Americans entered the first World War. Uncle Sam appeared on recruiting posters for the Army. “To recruit” (recruit) means to ask someone to joining an organization. Uncle Sam appeared on recruiting posters asking American men to join the Army. In fact, the famous saying that was later used was “I want you to join the U.S. Army,” and it shows Uncle Sam pointing out at the person looking at the recruiting poster or picture. It was a recruiting poster used throughout the 20th century; it’s not quite as popular anymore. But you will still see Uncle Sam on some U.S. government publications. You will sometimes see Uncle Sam represented in a newspaper, especially an editorial comic – an editorial drawing. Many people dress up as Uncle Sam to celebrate our Independence Day on the Fourth of July. Every once in a while, my father would dress up as Uncle Sam because, like Uncle Sam, he was born on the Fourth of July.
Uncle Sam has a counterpart in Great Britain that I’ll mention briefly. A “counterpart” is a person who does the same job or has the same purpose in another place or in another organization. The counterpart to Uncle Sam in Great Britain is a character known as John Bull, who represents England. He’s depicted as a “stout,” that is, an overweight, short man wearing a piece of the British flag on himself. John Bull doesn’t usually represent the government; he tends to represent the middle class in British life, people who are not too rich and too poor.
In any case, that’s some of the story behind Uncle Sam. Now let’s answer some of the questions that you have sent to us.
Our first question comes from Pascal (Pascal) in France, of course. Pascal wants to know the meaning of the suffix “ship” (ship), as well as some other common suffixes. Well, let’s begin by defining a suffix.
A “suffix” (suffix) is something that goes on the end of a word, it’s attached to the end of the word of that changes it’s meaning somehow. We have in English “prefixes,” which go before the word, and “suffixes,” which go after the word. We do not have what are called “infixes,” although some languages do, that go in the middle of a word.
Well, what does the suffix “ship” (ship) mean? It can mean a couple of things. First, it can mean the state or the condition that something is in, or simply the period of time. For example: “During their courtship (the time that they were dating) Jose and Tanisha never had an argument.” The “courtship,” which is all one word, is the time they were dating. “The scholarship of this article is excellent.” “Scholarship” here means quality – the academic quality of it. So, one meaning of “ship” can be the condition that you are in or the condition of something, the condition of dating or of academic quality in our examples.
“Ship” can also be used to indicate a job, especially a job that has a certain status or rank – a certain position: “He has a professorship at the local university.” Or, “She has an internship at one of the Hollywood studios.” An “intern” is someone who works in training, someone who isn’t yet a professional but wants to learn more about a certain area of work. So, an “internship” is the job that you would get as an intern. A “professorship” is the job you would get as a professor.
Sometimes, “ship” can be used to refer to skill, your ability to do something. We talk about “penmanship,” which is the ability to write, something that we’re probably losing nowadays with the keyboards. When I say “write,” I mean write with your hand, with a pen or pencil. We can also talk about “workmanship,” the ability to make things.
Finally, “ship” can refer to a group – a group of people. We talk about “the readership of this newspaper.” The “readership” are the people who are reading the newspaper, that group of people.
We could do a whole podcast on suffixes; let me just mention a couple more that also are similar to “ship”: (ness) and (hood); “ness” and “hood,” if we were to pronounce them as separate words, which they’re not – in this case, anyway. For example, “brightness” refers to the amount or the condition or the state of something being bright. We could also talk about “her friendliness.” “Friendliness” refers to the condition or the amount that this person is friendly. “Hood” can also be used to talk about the state or the condition of something; it can also have meanings related to groups of people as well as periods of time. For example: “The boys formed a brotherhood,” a group of male friends. Or, “I remember during my childhood how I used to play with toys.” “Childhood” is the time when I was a child; the state or condition of being a child is another way of looking at it.
Our next question comes from Diogo (Diogo) in Brazil. Diogo’s question relates to an expression: “grab a spoon.” “To grab” (grab) means to get; to obtain, usually by using your hand and taking something into your hand. A “spoon” is, you probably know, something you use to eat with; it’s round.
When someone says “grab a spoon” or “grab a fork,” they mean get ready to eat, or please eat. You come into someone’s house during dinnertime, the mother of the family or father of the family might say, “Grab a spoon,” meaning come down and eat. It isn’t that common, but it’s something that you might hear someone say, and it refers to an invitation to eat, to come and eat with the other group of people who are there.
Finally, Patricia (Patricia), in Brazil also – maybe she knows Diogo – was listening to a song called “Elephant Gun” by Beirut (Beirut). I don’t know the song; I don’t know the group. The expression, however, is “take the big game down.”
“Game” can have a couple of different meanings in English. One meaning is a fun activity, like something you play with each other. It could be a sporting game; it could be a card game. “Game” can also, as a noun, refer to wild animals or wild fish; it can refer to wild birds. “We traveled in Africa to see the game,” to see all of the different wild animals. When I say “wild,” I mean they’re not in a zoo; they’re not what we would call “domesticated.” They are out living on their own, if you will.
“To take down” is a two-word phrasal verb usually meaning to bring someone down to the ground or to kill someone – to kill an animal specifically. It can also be used, more generally, to mean to remove or to move something from a high position to a low position.
In the expression “take the big (or large) game down,” we’re talking about killing a large animal. I don’t know this particular song, but it probably means that the songwriter is expressing a certain feeling of power, the ability to have this huge animal and kill it. “To take the big game down” would be an expression of your power, and perhaps that’s how it is used, I don’t know. But that’s the general meaning of the expression, anyway.
I should also mention that “to take down” as a phrasal verb can also mean to write down on a piece of paper. Um…we might say, “Take down this telephone number.” You’re asking the person to write the number on a piece of paper – especially if they have good penmanship!
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you, our listenership, for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
to thwart – to prevent or stop someone from doing what he or she wanted to do
* How can we thwart that big company’s plans to buy the land that our restaurant is on and to put us out of business?
gang – a group of young people in a city who spend a lot of time together, often getting in trouble and using a lot of violence to scare the people around them and get what they want
* Members of the gang threatened to hurt my brother if he doesn’t help them rob the store where he works.
rival – a person or an organization that fights against each other, especially when they are both very strong and good at what they do
* The political rivals made statements that the other is dishonest and would not do what the voters wanted them to do.
poignant – affecting one very deeply emotionally and making one sad; very touching
* The story of the boy whose parents died and left him homeless was very poignant and made everyone in the room cry.
musical – a play where the characters often sing and dance along with music
* Kara has seen this musical more than 20 times and sings along with each song as she watches it.
catchy – easy to remember, often staying in one’s head, making it difficult to stop thinking about it
* I hate this commercial! The song in it is so catchy that it stays in my head all day.
to depict – to show; to represent
* Everybody has an idea of what aliens look like, but may depict them differently if asked to draw a picture of them.
goatee – facial hair grown at the bottom of a man’s face, below the lower lip; a beard on a man’s chin, resembling the long tuft of hair that a goat has below the front of its mouth
* Manuel has a scar on his chin, so he grew a goatee to cover it up.
chin – the part of one's face directly below the lower lip
* On a hot day, the children try to eat their ice cream before it melts down their chin.
to recruit – to ask someone to join an organization; to find and invite people to join an organization
* How can we recruit more members for our soccer club?
counterpart – a person who does the same job or has the same purpose in another place or a different organization
* Sheila is in charge of personnel issues in our office and works closely with her counterpart in the North Carolina office.
stout – overweight; having a heavy or fat body
* The witnesses to the crime described the thief as a stout middle-aged man wearing dark glasses.
grab a spoon/fork – get ready to eat; please eat
* As soon as we walked in the front door, my mother said, “Grab a fork. Dinner is getting cold.”
to take the big game down – to kill a large animal; to make someone who is in a high position or who is respected feel low or unimportant
* Computer hackers sometimes try to harm or destroy the computer systems of large corporation to try to take the big game down.
What Insiders Know
Shakespeare in the Park
In this episode of the English Cafe, we talked about the movie West Side Story, which is based on William Shakespeare’s play Romeo and Juliet. Whether it is a modern version of the story, or a traditional “production” (the putting on of a play or show), people are familiar with and are “drawn to” (attracted to) the “themes” (subjects) and stories that Shakespeare is known for.
Many of us like Shakespeare’s plays, but how would you like to see them on stage for free, in a popular “setting” (location), and performed by some of the best actors alive today? If that sounds good to you, then you’ll want to try to get tickets to “Shakespeare in the Park.”
“Shakespeare in the Park” is a theater “festival” (celebration with many types of entertainment) held each summer in New York City’s Central Park, an 843-acre (3.41 square kilometer; 1.317 square mile) public park in the middle of the city. Typically each year, there are three of Shakespeare’s plays performed, with each “running” (lasting) two weeks. All of the tickets are free, but you’ll have to have “patience” (ability to wait) if you want to get in. As you can imagine, there are long lines for tickets, especially during the festival’s last week or when a “big name” (celebrity; famous person) is in a production.
Many famous actors have performed in the festival. The idea of performing for large and “appreciative” (grateful) audiences is one “appeal” (attraction). Performing for people who may not have the money to attend Shakespeare performances with major stars is another reason these famous actors participate. Some of the big names who have performed at the festival include Meryl Streep, Patrick Stewart, Natalie Portman, Kevin Kline, Anne Hathaway, and Al Pacino.