= 1613
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 308.
This is English as a Second Language Podcast’s English Café episode 308. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide that we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to continue our series on famous authors, or writers, focusing on Herman Melville. We’re also going to talk about an organization called the Ku Klux Klan. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café with a continuation of our series on famous American authors. Today we’re going to talk about Herman Melville, who was an American author, best known for his novel Moby-Dick.
Herman Melville lived from 1819, in the early part of the 19th century, to 1891, in the latter part of the 19th century. He was born into a large family in New York City, which is on the eastern – what we call the Eastern Seaboard, the coast that is along the Atlantic Ocean in the north central part, I guess you could say, of that part of the country. Melville, as a young man, worked on several ships, including whaling ships. A “whaling (whaling) ship” is a large boat that goes out into the ocean to catch whales, of course. “Whales,” which are very large, technically mammals, but they look like fish, and live in the ocean.
In 1845, when Melville was 26, if I’m doing the math correctly, he published a novel called Typee about a romance – a love affair with a young girl in the Marquesas Islands, which are islands owned by France in the southern part of the Pacific Ocean in what’s sometimes called French Polynesia. Anyway, the novel became popular almost immediately, but the books that he wrote after that first novel, what we could call his “subsequent” books, or later books, were not that well liked, we would say they weren’t that well received by a lot of readers. The critics, people whose job it is to write about what other people do and give their opinion, attacked Melville and his writing, and he eventually became very unpopular. He wasn’t able to use his writing to make a living – to make enough money to live on, so he spent almost 20 years working as a customs inspector. A “customs inspector” is someone who works for the government. When you come into the country, they look and see if you are bringing in anything that you shouldn’t, or anything that you are supposed to pay a tax on.
Melville’s writing did not earn him financial success during his lifetime; he was never a highly successful writer, but things changed after his death, too late for Melville, of course. In the 1920s, there was something of a Melville Revival. A “revival” (revival) is a time when something becomes popular again. When I was a child and a teenager in the 1970s there was a 50s revival, where songs and movies, themes from the 1950s were popular on television, movies like…uh, what was it called? American Graffiti, things like that. Well, this was a revival of interest in Herman Melville’s books, which took place in the U.S. in the 1920s. There were several books published about Melville, and that caused many people to become more interested in his work. In 1945, there was an organization called the Melville Society, which was created to promote his work – to make sure other people knew about it. In the 1960s, one of the universities began to publish several of his books – his novels, and stories, and poems. So, like a lot of authors and artists, he was much more popular after he died than before he died; that is, while he was living.
When Americans think of Herman Melville, however, they’re probably going to think of what is now considered his greatest book – his greatest novel, Moby-Dick, which is also known as The Whale. Moby-Dick is about a sailor, someone who works on a ship, named Ishmael. Ishmael works on a whaling ship. In fact, the first sentence of the novel is one that most Americans know: “Call me Ishmael,” meaning that’s my name, Ishmael. Call me Jeff…hmm, doesn’t quite have the same sound to it! Anyway, Ishmael works on this whaling ship. The captain of the ship is named Ahab, and Ahab is trying to kill one particular whale. In fact, Captain Ahab is seeking revenge on this whale. “To seek (or look for) revenge” means trying to do something bad usually to another person because of something bad he or she did to you in the past. In this case, we have a whale, what’s called a white sperm whale, who once destroyed Ahab’s boat and bit off his leg. So now Captain Ahab is seeking revenge; he wants to find this whale and kill it.
The novel is interesting in that it contains a lot of detailed information about life on a whaling ship, daily life. Remember, Melville himself was a sailor who worked on whaling ships. But it also explores what we might call larger “themes,” bigger ideas, more general concepts. These include concepts about good and evil, whether God or gods exist, how humans who are seemingly intelligent interact with non-humans like whales. So, there are lots of interesting themes and ideas in the book; it’s definitely considered a classic, one of the great American novels.
Moby-Dick was first published in 1851. Today it is part of what we might call the “canon” of American literature. A “canon” (canon) in this context refers to all of the books that might be considered the most important of a certain time period. Back in the 80s, we often talked about the Western canon being taught at the university, the great books of the Western world – of Europe and the Americas – that some people thought were too restrictive. They wanted other kinds of literature to be read in college, so there was this big debate about the Western canon. However, the Western canon is still what we might call the basis of literature study in the United States, beginning with Homer and going right up to modern novelists. Moby-Dick is an important part of the Western canon, or least the American canon; it’s often assigned as reading in American high schools. I myself did not read Moby-Dick in high school; it was not part of our assigned reading, and I confess I’ve never read Moby-Dick. I probably should, um, but I haven’t, and probably won’t. But, they say it’s a very good book – if you like whales!
Melville’s next best-known work – his second best-known work is a short novel, what we would call a “novella” called Billy Budd. Melville began writing Billy Budd towards the end his life in 1888, but it was not finished, and he did not finish it by the time he died in 1891. It wasn’t actually even published until 1924. Billy Budd is also about a sailor, but it’s really about these larger themes of good and evil.
Both of the novels, Moby-Dick and Billy Budd, have many biblical references; that is, they refer to things that happened in the Bible, the Old and New Testament of the religion – the Christian religion. The Old Testament is the holy book of the Jewish religion; Christians claim both books. In any case, his novels and stories have a lot of symbolism in there; they use people or events to stand for or represent larger ideas. These ideas include things related to sexuality, racism, politics, law, and others. As I say, I haven’t actually read the book – or the books, but that’s what I’m told.
Now let’s turn to our next topic, which is an organization known as the Ku Klux Klan, or simply the KKK. Many people think of the Ku Klux Klan as a single organization, but it actually refers to three separate but related organizations that have existed over a period of years. It is a racist organization, an organization that discriminates against and believes in discriminating, or worse, against certain minorities in the United States; it has a very ugly history.
The first of the three organizations that we consider part of the KKK was active in the southern United States in the 1860s and 70s. When I say they were active, they had members and there were meetings going on during this time. Now, the 1860s, you probably know, was the time of the American Civil War, and the Southern states had slaves, from Africa originally. The war was in part about the end of slavery. The KKK, as I said, is a racist organization, and so they, of course, believed in slavery. The second KKK organization was active in the 1920s in the United States, and the third organization appeared after World War II, in the late 1940s and 1950s in the U.S.
Today, we would call the KKK a “terrorist” organization, although that term wasn’t used very often when I was growing up, but it is in fact what the KKK is. It tries to scare people by usually some form of violence. The Ku Klux Klan focuses specifically on terrorizing, or trying to harm and scare non-white people, people who are not white in the United States, what we would call racial minorities, especially blacks or what we now more commonly call African Americans.
The Ku Klux Klan believes in white supremacy. “Supremacy” (supremacy) is the idea that certain people are better than other people. In this case, white people are inherently or naturally better than people of any other skin color. Over time, the organization began to discriminate against other groups. These included being against Catholics; being against Jews, what we would call “anti-Semitic” (Semitic); as well as being anti-communist.
Traditionally, members of the Ku Klux Klan wore long white “robes,” which is like a long dress that hangs from the body. They also wore white hats and white masks over their faces. When they dress like this, of course, no one could identify them – no one could know who they were. The hat that they wore was typically a tall, what we would call a pointed hat, that comes to a single point at the top, kind of like a…uh…a wizard from the imaginary world of magic.
The second organization of the Ku Klux Klan, in addition to being a racist organization, started a certain tactic – a certain strategy to terrorize people, and that was putting burning crosses in front of the houses or places where blacks lived. A “cross” is a large piece of wood that looks like a “t”. It represents to Christians the cross of the founder of the Christian religion, Jesus. The Ku Klux Klan would burn this cross as a way of scaring people, or trying to scare people. The idea was that your life was going to be threatened; maybe you would be killed next, or maybe your house would be burnt down, or church. That’s one of the popular ways in which the Ku Klux Klan tried to terrorized blacks in the South.
The third, more recent Ku Klux Klan started to create “alliances,” that is partnerships, working together with some police departments in the South. This was a way of trying to fight against the Civil Rights laws of the 1950s and 60s.
In the past, the Ku Klux Klan often lynched African Americans. “To lynch” (lynch) means to kill someone by hanging them by the neck from a tree, for example. They also used to bomb churches that were used by African Americans. In 1963, they bombed a church in Birmingham, Alabama, and four young African American girls were killed. So, this is definitely a terrorist group. But that sort of violence backfired. When we say something “backfires,” we mean it has the opposite effect that they intended. Instead of slowing the Civil Rights movement, the violence of the Ku Klux Klan made people want to adopt new laws protecting African Americans even more.
I’d like to be able to say that the Ku Klux Klan doesn’t – does not exist anymore, but unfortunately it does. It’s not as popular as it was 40 or 50 years ago, but some experts think that there may be as many as 5,000 people in this country who are members of this group. It’s a sad commentary, but a necessary thing to talk about in our present day of terrorism and violence.
Now let’s turn to some happier topics by answering a few of your questions.
Our first question comes from Ta-ke (Ta-ke) in Japan. The question has to do with three words: “localize,” “locate,” and “position.” Let’s start with the second word, “locate.”
“To locate” means to put something in a certain place. “I chose to locate my business in Los Angeles.” That’s where I put it, that’s the geographical place that I chose. “To locate” also means simply to find something by looking for it, perhaps on a map. “Look at a map and locate Minnesota.” Where is it? “It’s in the north central part of the United States, just south of Canada.” I have located it.
“Localize” (localize) is a little different. “To localize” means to keep something within a certain area. “We were able to localize the infection to the man’s arm.” It didn’t go farther than that. “To localize” can also mean to find a specific place; it’s similar, in that case, to “locate,” but it usually is what we use when we’re talking about a problem or an illness. “We had a problem with our computer system, we are able to localize it to one of the hard drives.” I’m able to find the exact place. So, “localize” is used in identifying typically problems, when it’s used in the sense of finding something.
Finally, “position” is to put something in a certain place, usually a small thing. “I’m going to position the television next to the window,” or, “I’m going to position my computer on the left side of my desk.” That’s where I’m going to put it. “Locate” has to do with larger things: “we’re going to put our business” or “our headquarters.” “Position” has to do with smaller things.
Denis (Denis) from Russia wants to know the meaning of two words he found in a book about computer gaming. The first is “keep on your toes,” and the second is “roll with the punches.” Well, neither of these expressions are related specifically to the world of computer gaming; they’re both general expressions that we use in English.
“To keep on your toes” means to be ready, to stay alert, to be prepared to act quickly if necessary. “The students kept the teacher on her toes by asking so many questions.” They kept her alert; she had to pay attention.
“To roll with the punches” is to accept bad things that happen, and react in such a way that you are able to survive; you are able to go forward after this bad thing has happened. “I got laid off (that is, I lost my job), but I was able to roll with the punches by studying for a new career.” So something bad happens to you, but then you’re able to do something that allows you to survive and to continue on. That’s to roll with the punches.
It probably comes from boxing, this expression. “To punch (someone)” means to take your fist, which is your closed hand, and hit them in the body or in their head – on their head, I should say. So, to roll with the punches in boxing would be to be punched, but not to fall down – not to stop, to be able to continue fighting. I don’t know; I’ve never really boxed other than in school. We used to box in high school in gym class. Maybe once or twice a year we would learn something about boxing, and then do the boxing. I never really liked boxing, thought it was kind of a silly thing. But, it’s very popular, and of course, millions of people like watching it.
Our next question – our final question comes from Arjun (Arjun) in India. The question has to do with two expressions, or two phrases: “suffering from” and “dying of.” Boy, we’ve got happy questions today, don’t we?
Okay, “suffering” is pain that you feel because you are sick – because you are ill. “To suffer from (something)” is to feel pain because of this certain disease or injury. It could be something physical: “He is suffering from cancer.” He has cancer and it is causing him pain. It could also be psychological: “I am suffering from feelings of embarrassment.”
“To die of” or “to die from” something is to lose your life, to have your life end because of something. “He died of heart disease.” Or, “She is dying of tuberculosis,” whatever the disease is.
A few notes about these expressions: You can say either “die from” or “die of.” However, they’re used typically in a slightly different way. “Die from” is usually used when there is an “ing” word after. “He died from jumping off the bridge.” Or, “He died from doing (or taking) drugs.” “To die of” is usually used when the word after “of” – the object of the preposition “of” to be technical – is a noun that is not an “ing” word, so “He died of cancer.” “He died of heart disease.”
We also use “die of” when we’re using it not literally – not actually, but in a more symbolic or metaphorical sense. For example: “He died of a broken heart.” He was so sad that he died. Or, it could be the opposite: “I’m dying of laughter,” or “I was dying of laughter.” It was so funny I was going to laugh myself to death – which is not a good idea, though there’re probably much worse ways to die!
If you have a happy question or comment, please email eslpod@eslpod.com. We’ll do our best to answer your question. We don’t have time to answer everyone’s question, and sometimes it takes several months before we get to your question, but we do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
whaling ship – a large boat that goes out to sea to catch whales, which are very large, fish-like animals in the ocean
* The storm caused the whaling ship to turn over and the entire crew was killed.
revival – a period of time when something becomes popular again, after a period of not being popular
* In California, you can see many examples of homes built during a revival of Spanish architecture.
to seek revenge – to try to do something bad to another person because of something bad he or she did to you in the past
* Our neighbor ran over our cat by accident, but don’t seek revenge by running over his dog!
canon – all the books, artworks, or other materials that are considered to be most important in a certain area or time period, or to a certain group of people
* It would be impossible to read the entire canon of Western literature in just one year.
terrorist – related to a person, group, or activities aimed at scaring people and making them afraid to be or to do something
* A group of terrorists bombed a church to show their feelings against religion.
white supremacy – the idea that white people are inherently or naturally better than people of any other race
* The university speaker tried to talk about white supremacy to students, but very few people wanted to hear his message.
anti-Semitic – anti-Jewish; strong, negative feelings against Jewish people; hating or prejudice against Jewish people
* The Cohen family found an anti-Semitic message painted on the side of their building, saying that they should leave the neighborhood.
robe – a large piece of fabric that hangs over the body, similar to a loose dress
* For the concert, each of the singers in the choir wore a white robe.
cross – a piece of wood or other material that stands vertically (up and down) with a shorter piece of wood or other material attached to it horizontally (side to side), often a symbol of the Christian religion
* The new church has a large white cross on its doors.
alliance – partnership; an agreement or understanding with another person or group to work together for the benefit of both people or groups
* Cathy is a successful businesswoman because she has been able to build useful business alliances over the past 10 years.
to lynch – to kill someone by putting a rope around the person’s neck and hanging him or her, usually done by a person or group without a legal trial
* The police caught the two men who tried to lynch a teenager who insulted one of the men’s wives.
to backfire – for something to do the opposite of what was intended; to have the opposite result of what one planned on
* Paolo arranged a dinner for his sisters to make up after a big fight, but it backfired and they left even angrier than before.
to locate – to put something, especially a large thing, in a certain place; to find something by looking for it
* The firefighters tried to locate the exact place where the fire started.
to position – to put something, usually a small thing, in a certain place
* Jenisa positioned herself by the door so she would be the first person to greet the important guest when he arrived.
to localize – to keep something inside a certain area; to find a place, usually where something began; to choose a place for something
* If we can localize the effects of the oil spill, we may be able to save more of the area’s animals and wildlife.
to keep on one’s toes – to stay alert; to be ready to act quickly
* The police officers kept on their toes as they searched for the killer in the crowd.
to roll with the punches – to accept that bad things happen and react to them in a way that will allow one to continue or to overcome them
* Sam learned to roll with the punches early in life when his father died and he had to care for his brothers and sisters.
to suffer from – to feel pain, illness, or negative feelings because of something
* Maria has suffered from bad headaches all her life, but they became worse in the past year.
to die from/of – to lose one’s life because of something, usually an illness or disease
* Would you rather die of old age or die from some painless disease?
What Insiders Know
How Starbucks Got Its Name
If you visit or live in the United States, you know that it would be difficult to travel through any medium or large city without seeing a Starbucks. Starbucks is a “chain” (business with many locations) of coffeehouses, where people can buy coffee, tea, snacks, and more. It has also become a gathering or meeting place for people who want a place to sit and “chat” (talk informally) with friends and colleagues. Starbucks is so popular in some American cities that you’ll see one on each side of the same “boulevard” or “avenue” (wide streets with many lanes for cars to travel on).
Starbucks was founded in Seattle, Washington, and its first store opened in 1971. The three “founders” (people who start an organization or business) all have a “literary” (related to books and fiction) or education background. Jerry Baldwin was an English teacher, Zev Siegl was a history teacher, and Gordon Bowker was a writer.
It’s not surprising, then, that when it came to naming their coffeehouse they looked to classic literature for “inspiration” (ideas). One of the founders wanted to name the coffeehouse “Pequod,” the name of the ship in Moby-Dick, but one of the other founders “objected” (did not like or accept the idea). Instead, they decided to name it after the “first mate,” the person on the ship who is in charge of the workers “on board” (on a ship) and the “cargo” (goods traveling on a ship, truck, train, etc.). His name was Starbuck.
In the novel, Starbuck is intelligent and “thoughtful,” a person who gave a lot of thinking to life and daily matters. It’s not surprising, then, that the founders decided to name the business after this literary character.