= 1633
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 328.
This is English as a Second Language Podcast’s English Café episode 328. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Support this podcast by becoming a member, if you do you’ll be able to download our Learning Guide, an 8- to 10-page guide we provide for all of our current episodes. And, you can also take a look at our ESL Podcast Blog on our website, and some of our specialty courses in business and daily English.
On this Café, we’re going to talk about a very famous court case, or legal case, in the United States called the Scopes Trial. We’ll also continue our series on American cities, focusing on two cities, both in the same state: Aspen and Vail, Colorado. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion about a famous court case in the United States known as the Scopes Trial. A “trial” (trial) is a court case or a legal decision made by a judge and a jury, although sometimes it’s just a judge. Usually in legal cases – in trials in the U.S. you have a “jury,” a group of people who are selected to make a decision. This particular trial took place or happened back in 1925, but it was very important in the cultural and educational history of the U.S. The full name of the trial was The State of Tennessee v. John Thomas Scopes. That word “versus” is written in a legal case just as a lowercase “v” with a period after it. That’s how we write down the names of the court cases, showing who was, in this case, the “prosecutor,” or the party or group placing charges and accusing someone of doing something wrong, and who was the “defendant,” or the person who was trying to prove that he or she is innocent – did not break the law. In the Scopes trial, the State of Tennessee was the prosecutor. In a case involving a crime – a criminal case – it’s always a government organization – a government unit – that is the prosecutor. The defendant in the Scopes Trial was John Thomas Scopes.
Now, Scopes was a high school science teacher. What was his crime? His crime was teaching students about Charles Darwin’s theory of evolution in his science classes. Darwin’s theory of evolution, you probably know, is the idea that humans evolved from other animals – they came from other animals through a process known as natural selection. “Natural selection” is when certain members of a plant or an animal group have small genetic changes, and these changes are beneficial to them. They help them survive better than the other members of their group. When these members have babies, well those babies, then, will carry on that gene and they will also survive. So, there is a natural selection of those who are best able to survive, because of whatever genetic makeup they have.
Darwin’s theory of evolution has always been controversial since it was first proposed in the 19th century, and it’s still controversial today, which I’ll talk about in a little bit. But it was especially controversial in the United States during the early 20th century. The State of Tennessee, which is located in the central eastern part of the United States, had passed a law known as the Butler Act. An “act” is just another word for a law. The Butler Act made it illegal for teachers in public schools to teach anything that didn’t agree with their version of the Bible on how humans were created. The Butler Act made it illegal for teachers in public schools to teach that human beings had evolved from lower or less developed animals, such as “primates,” or monkey-like creatures.
An organization called the American Civil Liberties Union, or ACLU, believed that the Butler Law was wrong because it didn’t let teachers use their freedom of speech in the classroom. So the ACLU offered to pay the legal costs for the teacher who was accused of violating the Butler Act. Scopes became that teacher.
Scopes’ “attorney,” or lawyer, in the case was a very famous lawyer at this time, a man named Clarence Darrow. Darrow was a very well respected attorney, someone who had recently defended two murderers in another famous case. Darrow volunteered to defend Scopes at the trial. The ACLU had wanted the case to focus on the teachers’ right to free speech or their right to say what they wanted to say in their classroom. But during the trial, Darrow focused more on the merits of the Bible’s story of creation and Darwin’s theory of evolution. The “merits” (merits) of something refer to the good parts of something, how worthy something is of having or doing it particular action. For example, employees might receive a raise – they might get more money because of their merits, based on how well they work. The Scopes Trial ended up focusing mainly on the merits of creation story in the Bible versus the evolution theory of Darwin.
The trial lasted eight days and received a lot of media attention; the newspapers and radio stations were all talking about it. In the end, however, the jury, the group of people who made the decision, deliberated for only nine minutes. “To deliberate” means to discuss something in order to make a decision. In a court case, the members of the jury, usually 12, deliberate everything that they have heard during the trial in order to make a decision about whether or not the defendant, in this case John Scopes, is guilty or innocent. After just nine minutes of deliberation, which is really almost nothing, the jury determined that Scopes was guilty; he lost the case and was “fined,” or had to pay, 100 dollars to the government.
In the U.S. legal system, if a defendant loses a case they can often appeal the case. When we “appeal” (appeal) a legal decision, we take the case to a higher court, that is, a court that is above the court that made the initial decision. In the United States, we have different levels of courts; the very highest court is the Supreme Court. But this was tried at a lower level court, and so Darrow was able to appeal the decision.
When the case was appealed, the higher court found that the Butler Act – the Butler Law was “constitutional,” it was consistent with the Constitution of the State of Tennessee, meaning there wasn’t anything wrong with the law itself based upon the main laws of the state – the Constitution of the state. However, there was a legal technicality. A “technicality” (technicality) is a small detail in the rules that change the decision; a “technicality” is a very small mistake. But because it is a mistake, it can sometimes change the larger picture, it can change the decision, and that’s what happened in the Scopes Trial. Even though the higher-level court said that there was nothing wrong with the law upon which the decision was based, there was a problem with the Scopes Trial, there was a mistake made. In the Scopes Trial the 100-dollar fine that Scopes was supposed to pay to the state was set by the judge – it was determined by the judge, whereas it should have been set by the jury. So on this small mistake – this technicality the Scopes conviction was overturned. To “overturn” (overturn – one word) means to reverse a decision. In other words, Scopes was no longer guilty. This happens sometimes in the American legal system – in our court system. Someone may have, in fact, been guilty of a crime, but if the rules are not followed then sometimes the person goes free, is found not guilty based on that technicality – that mistake, and that’s what happened in the Scopes Trial.
The importance of the Scopes Trial is not the 100-dollar fine, however. It’s important in the history of education in the United States. It brought attention to the disagreements, sometimes, between science and certain views of religion, especially in this context with Christian “fundamentalists,” Christians who believed in what we might call a literal interpretation of the Bible. “To be literal” means to be actual, to follow exactly what, in this case, the words appear to say. So if the world, according to the Bible, was created in just six days, then certain Christians believe that that means six days – six 24-hour days. The trial brought attention to how those kinds of beliefs contradict the Darwinian theory of evolution. The trial also resulted in changes to many of the books – the science textbooks that were used, which stopped talking about evolution in the 20s and 30s.
The Butler Law – the Butler Act was still on the books, that is, it was still the law of the State of Tennessee up until 1967. After the Scopes Trial itself, many states passed their own anti-evolution laws. In 1927, just a few years after the Scopes Trial, 13 states had laws against teaching evolution. Most of those laws have been changed; it is not against the law to teach about evolution in American schools anymore. However, there’s still a controversy; there are still people who believe that the science classrooms should teach other theories of how human beings got on the Earth, how we got to where we are today, and that controversy will continue, I’m guessing, for many years.
Now let’s turn to our next topic, continuing our series on American cities. We’re going to talk about two cities today; really they’re two large towns. A city and a town are similar; a city is usually bigger than a town, though the definitions aren’t exact. The two towns or cities we’ll talk about today are Aspen (Aspen) and Vail (Vail); both of them are located in the State of Colorado, which is in the western central part of the United States. If you think of Colorado, you should think about the Rocky Mountains, the large mountains that go through the western part of the U.S. They are quite tall and quite prominent in the State of Colorado. Aspen and Vail are just 100 miles from each other, near the White River National Forest, and they’re very high up in the mountains. The towns are relatively small; there are only about 5,000 people who live in each of these towns. But they’re very famous in the United States because of what you can do at these towns, and what you can do is ski. Aspen and Vail have a lot of what are called “ski resorts.”
A “resort” (resort) is a place where you can go on vacation; usually it’s a very nice place, it’s what we would call “luxurious.” It’s usually expensive, too. Many resorts are on the beach, but a ski resort, of course, is in the mountains where people can go skiing. “To ski” means to wear these special boots – these special shoes that are attached to long, straight pieces of…I guess they’re fiberglass – I’m not sure what they’re made of, wood in some cases – and you put them on your feet and you go down the hill. Other people like to ski across flat land – or more or less flat land, this would be called “cross-country skiing.” When you ski down a hill, we call that “downhill (one word) skiing.”
A typical ski resort has nice hotels where you can stay for several days while you are skiing. The resorts will rent you skis and other equipment; they also provide other services. They have a special system to take you from the bottom of the mountain to the top, or the top of where you can start skiing; these are called “chair lifts,” or just “lifts,” where you sit on a chair and it takes you up to the top of the ski hill. Ski resorts typically have nice restaurants; they often have what are called “spa services.” These are places where you can get a massage, because remember, you’ve been falling down the hill all day so your muscles might be a little sore – they might hurt a little. You can go to the spa to get a massage for that. These two towns of Aspen and Vail have many of these expensive resorts that you can go to, so if you like to ski that’s a good place to go if you’re coming to the United States.
The local economy in the towns of Aspen and Vail depend a lot, almost exclusively, on tourism. A lot of celebrities – famous actors, musicians, and athletes go there. The singer Mariah Carey, the late – now dead – singer John Denver used to go there, actor Charlie Sheen, actress Goldie Hawn, the famous cyclist Lance Armstrong; all of these are people who go to Aspen and Vail – or used to go, before they died. Many people own vacation homes there; Aspen has some of the most expensive real estate prices – house prices in the entire United States.
These towns, as you can guess, have many upscale stores. When we say something is “upscale” (upscale – one word) we mean they’re very expensive, they’re design for people with a lot of money. Aspen, especially, has many upscale clothing stores, gourmet restaurants, and so forth.
Aspen and Vail are best known as ski resorts, but you can also visit during the warmer months, during the summer. In the summertime, visitors often go there for other festivals and celebrations, including film and music festivals. You can also hike or walk in the mountains, you can ride on a horse, you can fish, and so forth. It is a beautiful part of the United States that I think is worth visiting; if you like to ski, especially, you will enjoy going during the wintertime to Aspen and Vail.
Now let’s answer some of the questions that you have sent us.
Our first question comes from Alexander (Alexander). He is from Russia, although I don’t think he’s Alexander the Great – might be! Alexander, great or not, asks, “What is the difference between the City of New York and New York City, and what is the official name of Kansas City?” Do we say “the City of Kansas City,” because we don’t say “the City of Kansas?” This is actually a good question, a confusing issue. It depends on the city how you use the word “city” to describe it. Let’s start first with New York.
New York is a state in the northeastern part of the United States. The biggest city in the United States is located in the state of New York. It can be called either “New York City” or “the City of New York.” Either way of describing this place is acceptable. For people who actually live in New York City, they usually just call the place where they live “New York,” they don’t even include the word “city,” because everyone knows that they are talking about the City of New York. So there’s no real difference between these two. You can’t say, however, “the City of New York City,” that wouldn’t sound quite right.
However, people do sometimes use the expression “city of” to talk about the official government of a city. So here in Los Angeles, we might say, “I work for the City of Los Angeles.” That means I work for the government of the City of Los Angeles. We wouldn’t say, however, “Los Angeles City,” although you could describe one of our local legislative bodies – representative bodies as the “Los Angeles City Council.” There is something called the “Los Angeles City College.” But the “city” isn’t part of the official title of the City of Los Angeles. It is rather confusing. Here in Los Angeles we have a place called “Culver City,” but the word “city” is an official part of the name of that particular town. So, you would talk about “Culver City,” you wouldn’t talk about “the City of Culver” in the same way that you would say “the City of New York.” Why? Well, that’s just the tradition; that’s the custom. In most cities that have the word “city” in their name, such as Kansas City, you would just say “Kansas City,” you wouldn’t say “the City of Kansas.” So, New York is kind of an exception to the rule. Is it possible to say “the City of Kansas City” or “the City of Culver City?” The answer is yes if you are talking about the government of that city, if you’re talking about the people who work for the government of that city.
So, the general rule is that you can use the word “city of” when you are talking about the government of any city: the City of Los Angeles, the City of San Francisco, and so forth.
For some cities, the word “city” is actually in their name, cities like Kansas City or, here in Los Angeles, Culver City. For New York, it’s sort of an exception. For New York, you can say, “City of New York” or “New York City,” and they both are correct.
Gabriel (Gabriel) in Spain wants to know the difference between the word “verge” (verge) and “brink” (brink). Both “verge” and “brink” can talk about or describe the point where a new action or a new situation begins. Usually, it is combined with the preposition “on.” We say, “on the verge” or “on the brink.” “I am on the brink of discovering a cure for baldness,” for people who don’t have any hair. I’m on the brink of discovering it; I’m almost there. Something is going to happen very soon, but I’m not yet there. I haven’t yet discovered it, but I’m close. Or, “I’m on the verge of discovering a cure for people talk who on their cell phones in the car.” I haven’t got quite the solution, but I’m on the verge of finding one. That’s how we use “verge” and “brink,” and in that sense they both mean the same thing.
The word “brink” can also mean the edge of something, the dividing line between two things, especially if we’re talking, for example, about a lake or an ocean: “I stood on the brink ready to dive in and swim.” “Verge” also has a couple of other meanings. “Verge” can also mean to be on the edge or the border of something. We usually use the preposition “on” after the word “verge” when it has this meaning. We might say, “My property, where my house is, verges on the water,” meaning it is next to or has a border with the water. That’s not true, by the way, just an example. I wish my house verged the ocean; that would be very nice! The expression “verges on” can also be used not just for physical closeness, but closeness in another sense. For example: “His piano playing verges on brilliance,” or “verges on genius.” It’s almost perfect; it’s almost brilliant.
Notice that in the expressions “on the brink of” or “on the verge of” both “brink” and “verge” are nouns. When we say something “verges on” we’re using “verge” as a verb. “Brink” is not used as a verb in that sense.
Finally, Khaalid (Khaalid) from Somalia wants to know the difference between two words that sound the same but are spelled different: “compliment” (compliment) and “complement” (complement). I think we might have talked about the difference between these two words in another podcast, but we’ll review them here.
A “compliment,” with an “i”, is when you are telling someone something good about themselves; you are praising or congratulating them. It can be either a noun or a verb. If it’s a noun, we would usually use the verb “give.” “I’m going to give you a compliment. You are the most beautiful woman in the world.” I would only say that to my wife, of course! You can use it as a verb: “I complimented my teacher on the lesson today, it was very interesting.” So, “compliment” can be a noun or a verb, with the letter “i”.
“Complement,” with the letter “e”, can also be a noun or a verb. It means to complete something. So, if you think of the word “complete,” which is spelled (complete), that’s how you can remember that “complement” with an “e” has to do with making something whole, something that completes or finishes something else. “The lab assignments that you do in biology class are complements to the lectures,” one goes with the other. They complete each other; together you get the whole picture. “Complement” can also be a verb, meaning the same thing.
Words that sound the same but are spelled different or have different meanings are called “homophones.” “Complement” and “compliment,” with an “e” and an “i”, are homophones – or homophones, depending on how you want to pronounce it.
However you pronounce it, if you have a question you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, this is Jeff McQuillan. Thanking you for listening to us today. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
trial – a formal look at evidence in a court case by a judge and/or jury so that a legal decision can be made
* This trial will decide whether the tech company is guilty of selling its customers’ personal information for money.
– versus; the way a court case is referred to, with the names of the two people or organizations that are working against each other to win a trial
* One of the most influential trials of the past 10 years was McQuillan v. Tse.
prosecutor – the person or organization officially accusing someone of doing something legally wrong
* The prosecutor is accusing Dana of stealing from her clients.
defendant – the person or organization that is trying to prove that it did not break the law
* As the defendant, Dana has to show that she did not commit the crime.
merit – the good parts or qualities of something; how worthy it is to have or to do something
* Gilessa’s plan has its merits, but I think Sandra’s plan is more likely to succeed.
to deliberate – to think about and/or discuss something in order to make a decision
* The judge deliberated for two days before making a decision on the case.
to appeal – to take a court case that has already been decided by a court to a higher, more powerful court to ask for the decision to be made again by a different, more powerful judge
* Our company isn’t satisfied with the judge’s decision and we plan to appeal.
technicality – a small detail in the rules that changes a decision in a big way
* Byung’s painting would have won the art contest, but because of a technicality that artists could not use certain brands of paints, he was not allowed to compete.
to overturn – to reverse a decision; for a higher, more powerful court to decide a court case differently than in the original trial
* Because of political reasons, the university president overturned the professor’s decision to fail the students who were caught cheating.
resort – a place where people go on vacation that is usually very luxurious, with very nice and comfortable rooms and facilities
* For their honeymoon, Katy and Mike are going to a resort in the Bahamas.
to ski – a sport and recreational activity where people wear special boots that are attached to long, straight pieces that let them move smoothly over the snow
* Rick likes to ski and takes a trip to Switzerland each year to ski on some of the best ski slopes in Europe.
upscale – something that is very expensive and luxurious, designed for wealthy people
* For their wedding anniversary, Janelle and Griffin had dinner at an upscale restaurant.
verge – the point where a new action or situation begins
* Ding is angry and on the verge of leaving, so please don’t say anything else to upset him.
brink – the point where a new action or situation begins; the edge of a high point, such as a cliff or a body of water
* No one knows why Manny and Sarah broke up on the brink of their wedding.
to compliment – to give praise or congratulations; to say something nice to someone about their appearance, actions, or something else
* The company president complimented our entire work group for finishing the project ahead of schedule.
to complement – to have parts that work together to make something more complete or whole; for something to be added to something else to complete it
* This wine complements the meat dish well, bringing out its delicious flavor.
What Insiders Know
The Play Inherit the Wind
In 1955, two “playwrights” (authors of plays), Jerome Lawrence and Robert Edwin Lee “debuted” (showed for the first time) a play called Inherit the Wind. This play was a “parable” (a simple story used to give a moral or religious lesson) about the 1925 Scopes Trial.
The play uses “fictionalized” (not real) characters similar to those in the real trial, “portraying” (acting in the role of) the two “attorneys” (lawyers), William Jennings Bryan and Clarence Darrow, and the science teacher John Thomas Scopes. However, in the “opening” (beginning of a performance) of the play, the playwrights “state” (say) clearly that the play is not a historical “account” (accurate telling of true events).
The authors wanted to use the Scopes Trial to “comment on” (give their opinions about) what happens when “intellectual freedom” (the right to think the way one wants to) is “threatened” (in danger). In the 1950s, when the playwrights wrote Inherit the Wind, the United States government was “holding” (having) “anti-communist” (against communism) “hearings” (government trials). (“Communism” is the political idea proposed by Karl Marx that people should belong to the same social and economic class, and property should be owned publicly, not by private individuals). The playwrights believed that it was wrong for the government to try to control what people thought.
The play continues to be well known today. Its past “productions” (the putting on of a show) have included some very well known and respected actors, such as George C. Scott, Christopher Plummer, and Tony Randall.