= 1608
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 303.
This is English as a Second Language Podcast’s English Café episode 303. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, which will help you improve your English faster than you thought possible.
On this Café, we’re going to talk about another famous American movie; this time we’re going to talk about a well-known movie called Jaws. We’re also going to talk about some important awards – prizes, things that are giving to honor people in the United States: the Presidential Medal of Freedom, the Congressional Gold Star, and the Medal of Honor. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of a well-known movie, Jaws (jaws). We have two jawbones, which are the bones that our teeth sit in. We have an upper jaw and a lower jaw, so we refer to them in the plural as “jaws,” referring really to the whole mouth including the teeth, especially when we’re talking about a dangerous animal.
The movie Jaws is a what we could call horror movie, a movie that is supposed to scare you. It was made in 1975; I was 12 years old. It was based on a novel by Peter Benchley. The movie and the novel are about a great white shark. A “shark” is a very large fish that has sharp teeth that can eat people, although in reality sharks don’t usually attack people. In the movie, this great white shark is a man-eating shark, meaning it likes to eat people.
The police officer at a “resort town,” or a place where people like to visit on vacation, tries to protect people from the shark by closing the beaches and not letting people swim in the water. But the government body – the city council doesn’t want to lose money by telling the tourists to go away – to stay away, so the beaches stay open and the shark continues to kill and eat people. The rest of the movie shows how a group of men go out on a boat to try to catch and kill this shark.
Jaws was directed by Steven Spielberg, and it was a very important movie in his early career. The movie was very difficult and expensive to produce – to make, but Spielberg succeeded, although he finished more than 100 days later than scheduled. The movie is often referred to as Spielberg’s breakthrough as a film director. A “breakthrough” is an event or a moment where something becomes very successful or popular or well known. During the 1970s, there was a singer called Bruce Springsteen; you’ve probably heard of him. Well, he had recorded in album in 1972 and 74 – or maybe 73 and 74, anyway, his first two albums were not that popular. His breakthrough album was his third album, Born to Run. This was Spielberg’s breakthrough movie; it’s the one that made him very popular, very successful. Once the movie became a success, people recognized that this was a good director and he began to direct other movies.
Some of the best-known actors in the movie are Roy Scheider, who played the head of the police officers, a person we would call the police chief. There was also Robert Shaw, who played the shark hunter, the person who tried to kill the shark, and Richard Dreyfuss, who played an oceanographer. An “oceanographer” is a scientist who studies oceans and the things that live in the ocean.
Jaws was a very successful movie. It was the first film to open, or to be shown at hundreds of theaters throughout the country at the same time. Before Jaws, in 1975, movies began to be shown in different theaters at different times. That is, they opened at different times. When we use the verb “open” in talking about a movie, we mean when it is first played in the movie theaters. Before Jaws, movies opened in different cities at different days; it wasn’t something that happened all on one day. Well, Jaws changed that; it opened at hundreds of theaters on the same day, something that we now do for almost every movie. Jaws also made use of television advertising to get people interested in the movie. Jaws made 7 million dollars in the first weekend and soon became the first American film to earn more than 100 million dollars in the theaters. It was also a movie that was released or opened in the summertime, and it is sometimes called the first summer blockbuster. A “blockbuster” is a movie that becomes extremely popular very quickly. A summer blockbuster would be one that becomes very popular in the summertime. Summertime, of course, is a time when people are on vacation, they may have more time to go to the movies, so it’s a popular time for the movie studios – the companies that makes the movies – to make a lot of money. Over the years, Jaws has made almost 500 million dollars worldwide – that is, not just in the U.S.
Jaws also won some famous awards; it won the Academy Awards, what we call the Oscar, for Best Film Editing, Best Original Dramatic Score (that is, the music); it was also nominated for Best Picture, but it did not win the Best Picture award. Today the movie is, however, included on many lists of the best movies made in the past 50 years or 100 years. It’s number 56 on the American Film Institute’s list of the best American movies of all time.
I mentioned the “score” (score). In a film, the score is the music that is played during the movie, which is very important. It gives the movie a certain feel – a certain tone. I actually know someone who writes scores for movies, has written dozens of scores including some famous movies. The score for Jaws is particularly famous because when the shark appears in the movie there’s a very famous part of the score: “duh duh, duh duh.” That’s it, just those two notes, but it gives the movie a certain level of suspense. “Suspense” is the feeling of anxiety when you want to know what’s going to happen next, but you’re not sure what it is. The great director Alfred Hitchcock made many suspense movies; he was probably the best director of suspense movies in the 20th century. Jaws is a suspense movie, and that score – that music helps give the movie that feeling of suspense. The simple music was written by a person who became famous for other musical scores; that man’s name is John Williams. It was also a breakthrough moment for John Williams as a composer – as a person who writes music. Even today, people who have never seen the movie will know that two note part of the score, and may even use it when they think something bad might happen. Usually it’s done as a joke; it’s done in a humorous way.
There have been several sequels for Jaws. A “sequel” (sequel) is a movie that comes after the original movie, sort of like a second or third part, where you have the same characters and a continuation of the original story. Spielberg, however, was not involved in the sequels, and they were not very popular. Some movies have very popular sequels. The Harry Potter movies, which were based on books that had several sequels, they were very successful. Many movies – Mission Impossible, Star Trek, X-Men – many movies that are successful and popular have sequels because, of course, the movie studios know that people like that movie – that kind of movie, and they make another one just like it.
I have never seen Jaws myself. I mentioned I was 12 years old when the movie came out. It was considered a scary movie, and I was too young to go see it. As an adult, I’ve never really liked horror movies or certain kinds of suspense movies, so I’ve never seen the movie. But I know the story and of course, the famous music.
Jaws was really part of a larger phenomenon in movie making in the 1970s, what we might call the disaster phenomenon. Jaws wasn’t a disaster movie exactly, but it was a movie about people’s fears, and disaster movies are all about people’s fears. Of course we still have movies, many movies made to exploit – to take advantage of your fears. I’m just one of those people who doesn’t really need more fear in his life!
Now let’s turn to our second topic, which is about special awards that the U.S. government gives Americans for their service, or the things that they do for their country. We’re going to talk about the Presidential Medal of Freedom, the Congressional Gold Medal, and the Medal of Honor.
A “medal” (medal) is usually a flat circle, usually quite heavy, made of a material called metal that’s spelled (metal). So, medals are made of metal, even though those two words are spelled differently. The medal typically has certain images and words on it; we would say they’re “engraved” on it; they’re written and made part of the metal. Medals are usually, though not always, worn around the neck. They’re usually on what we would call a ribbon, a piece of material that goes around your neck, and the medal is on your chest or just below your chest. The Olympics has gold silver and bronze medals that the winners wear. That’s what we’re talking about; that’s what a medal is, what they give you if you win.
The Presidential Medal of Freedom and the Congressional Gold Medal are the highest or most important awards in the United States for civilians. A “civilian” (civilian) award is an award given to ordinary citizens, someone who is not in the military – not in the army, or the navy, or the air force or the marines, and so forth. I’m a civilian; most Americans are civilians, they’re not in the army and never have been. American does not have military service that is required, as is the case in many other countries. We have what’s called a volunteer army and a volunteer military. Anyway, the Presidential Medal of Freedom and the Congressional Gold Medal are the highest civilian awards in the U.S. However, people who receive these awards don’t have to be U.S. citizens, and military personnel, people who are in the military, can also receive these awards. It isn’t a requirement that you be a civilian or that you be a U.S. citizen, and sometimes they have been given to citizens of other countries.
The Presidential Medal of Freedom is awarded by the United States President. It’s given to people who have made some important contribution; they’ve done something important that is important to America’s national security, or it could be to the national interest of the United States. It could also be for world peace, for cultural contributions, or other significant things that you have done.
The Medal of Freedom was created by President John F. Kennedy, back in 1963, although there were other, somewhat similar awards before that. You can receive more than one Presidential Medal of Freedom, and you can even get it after you’re dead. Although if you’re dead, you can’t normally wear it, because, you see, you’re dead and your body is in the ground and therefore I guess they give the medal to your brother. Anyway, some famous people who have received the medal include Mother Teresa, the Prime Ministers of England Margaret Thatcher and Tony Blair, former U.S. President Ronald Regan, the physicist Steven Hawking, the famous singer Frank Sinatra, the famous writer John Steinbeck, former Chairman of the Federal Reserve Alan Greenspan, and many others.
The Congressional Gold Medal is similar to the Presidential Medal of Freedom, but it’s awarded by the U.S. Congress. So the Congress, the elected representatives, decide who gets the medal. The first Congressional Gold Medal was awarded to George Washington and John Paul Jones, another famous Revolutionary War hero, back in 1776. As you can see, the Congressional Gold Medal is much, much older in U.S. history than the Presidential Medal of Freedom. The Congressional Gold Medal is also given less frequently than the Presidential Medal of Freedom. It has to be something that the legislative part of our government, the House of Representatives and the Senate, agree on, and they don’t often agree on a lot of things, so it’s not given as many times as the Presidential Medal of Freedom.
The Congressional Gold Medal is made individually for each person who gets it, so no two of them look the same. There were medals given to the Dalai Lama, Dr. Martin Luther King, Jr., Nelson Mandela, Pope John Paul II, and several others.
The final medal we’ll talk about today is the Medal of Honor. The Medal of Honor is the highest military honor awarded by the U.S. government. This is just for those who are in the Army, the Navy, the Marine Corps, the Air Force, the Coast Guard, and so forth. The Medal of Honor is given to men and women who have risked their own life while fighting an enemy of the United States. More than half of these medals have been awarded “posthumously,” or after the person has died. Often the person dies in a battle in a war, defending the United States, and they receive the medal because of their service.
There are three kinds of Medals of Honor: there’s one for the Army, there’s one for the Air Force, and then there’s one for the Navy, Marine Corps and Coast Guard. This medal was created in the early 1860s. Nineteen people have received the Medal of Honor twice.
Recipients of the Medal of Honor get certain benefits in addition to the medal itself. For example, they can be interred in Arlington National Cemetery. “To be interred” (interred) means to be buried. Arlington National Cemetery is near Washington, D.C. It’s where many of the famous American politicians and presidents and military leaders are buried. Recipients, those who receive the Medal of Honor, can also have their children study at the U.S. military academies if they want to.
So those are some of the most famous awards given by the U.S. government to people who have done great things.
Now let’s answer a few of your questions.
Our first question comes from Matheus (Matheus) from the Republic of Matheus. I’m just kidding, I don’t know where Matheus is from; he’s from a mystery country. Matheus wants to know the difference between a couple of similar expressions: “go in,” “go into,” get in,” “get into.” Let’s start with “go in.”
“Go in” can mean to walk inside into a building, especially a hospital or a doctor’s office. We would say, “I’m going to go in to see the doctor,” “I need to go in to the hospital to get some medical test done.” “To go in” can also mean to fit, to belong to a certain place. “Those pants go in the closet,” meaning that’s where they should be, that’s where they are kept. We especially use that if we are talking about storing things – keeping things.
“Go into” (into – one word) means to talk about something for a long time, to give a long speech about a certain idea. “I don’t want to go into all of the details, but here are some important points.” Or, “The politician is going to go into her reasons for wanting to raise taxes.” “To go into” can also mean to have a certain career, to work in a certain area. “My brother is going to go into law. My sister is going to go into medicine.” They’re going to study law and become a lawyer, or they’re going to study medicine and become a doctor. That’s another way of using “go into.”
So, you go in a building, you go into a profession, or you go into a long explanation of something.
“To get in” has several meanings. First, “to get in” can mean to arrive, especially if we’re talking about a bus or an airplane or some other public transportation. “What time does your plane get in?” meaning what time does it arrive to wherever you’re going. “To get in” can also mean to come home or to arrive at work. “What time did you get in last night?” That means what time did you arrive at your house last night. “Get in” can also be something you tell someone if you want them to come into your car. The taxi driver may say “get in,” meaning open the door and sit down, come into the car. “Get in” can also mean to be accepted by a school, especially a college or a university. “My niece wants to go to Harvard, but she didn’t get in.” She wasn’t accepted.
“To get into” means to become interested, to begin to spend a lot of time or energy on something. “My friend is getting into jazz music,” he’s starting to listen to a lot of it and really enjoy it. You can get into bad things like drugs: “He got into drugs when he was in high school.” It can also be used for someone who starts to have lot of problems or trouble. In fact, we have the expression “don’t get into trouble,” meaning don’t get or do something that will cause you problems. “Get into” can also mean the same as one of the meanings of “get in,” to get accepted by a school or a team: “He didn’t get into Harvard, but he did get into the University of Des Moines, Iowa.” Actually, I don’t think there is a University of Des Moines, Iowa, just a random example.
Our next question comes from Matheus – no, the first Matheus, another Matheus, this one from Brazil. Matheus wants to know the meaning of the word “overwhelming” (overwhelming).
“Overwhelming” can mean very strong or powerful: “I have an overwhelming fear of cats.” I don’t like cats, I hate cats; I have an overwhelming fear or an overwhelming dislike. Very strong, very powerful. Just an example, not actually true. No, actually true!
“Overwhelming” can also mean impossible to fight against: “The other person’s strength was overwhelming.” Or, you could say you were overwhelmed by something: “I was overwhelmed by the amount of work I had to do.” I couldn’t complete it, it was too much. “Overwhelming” is often used in situations where you’re describing something in great number or something that is much bigger or much larger than you expected. Sometimes it can mean very big or a lot of. It could also be used in a good way: “I was overwhelmed by the number of people who thanked me at the party for what I did.” I wasn’t expecting it; it caused a deep emotional reaction. That’s another way of using “overwhelmed.”
Finally, Susanna (Susanna) in Germany wants to know how we use the word “off-kilter.” “Off-kilter” means something is not in a straight line; it’s not balanced. If you put a photograph on the wall and it’s crooked – it’s not straight – we would say it’s “off-kilter.”
“Off-kilter” can also mean simply not traditional or unconventional, not what you would expect, not normal. “There’s something off-kilter about my nephew’s girlfriend.” Something weird about her, something strange.
Susanna had one more question. She wants me to pronounce a couple of words. The first word is (ladder), which is typically pronounced “ladder.” The second word is (letter), and that word is pronounced “letter.” Ladder, letter. Ladder, letter. The difference is just in the first vowel, the “ah” versus the “eh.” Notice that even though there are two “d”s in the middle of “ladder,” and two “t”s in the middle of “letter,” in normal pronunciation they are pronounced exactly the same.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. You won’t get a Congressional Gold Medal for writing us, but as long as your question isn’t too off-kilter we’ll try to answer it here on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, won’t you, on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
jaw – the entire mouth and its teeth; the bones that form the mouth and that teeth are attached to
* After a frightening and tense dream, I woke up with a sore jaw.
shark – a very large fish with sharp teeth that can eat people
* People aren’t allowed to swim on this beach because there are a lot of sharks in these waters.
resort town – a place people like to visit on vacation; a town whose main industry is tourism, often with many hotels and activities for people on vacation
* In the summer, our resort town gets over 50,000 visitors, but nearly none in the wintertime.
breakthrough – the event or moment where something becomes very successful, popular, and well-known
* Lamar has been a clothing designer for years, but only got his breakthrough when a celebrity wore his clothing to an award show.
score – the music played during the movie; the music and/or songs heard during a film
* The score made the love scenes in the movie even more romantic.
suspense – the feeling of anxiety when one wants to know what’s going to happen next, or when one believes something bad is going to happen, but doesn’t know exactly when or how
* The owner of the company left Manika in suspense, not telling her yet whether she got the job.
sequel – a second film that continues with the same characters as the first film and may be a continuation of the original story
* Why are sequels seldom as good as the original film?
medal – a heavy, flat circle of metal that has images and words on it, that hangs around one’s neck on a nice ribbon (long piece of material)
* The person who wins the race will receive a medal.
civilian – a person who is not involved in the military or the police force
* At the military school graduation ceremony, the civilians sat on one side and the officers sat on the other.
to commemorate – to remember and celebrate a person, event, or achievement that one believes should be recognized
* Every year, our boss takes us out to lunch to commemorate the anniversary of the opening of her first store.
posthumously – after death; after someone has died
* She wrote her best book while she was ill, and it was published posthumously a year later.
to inter – to place in a grave (hole in the ground where dead people are placed) or tomb (building or structure with walls where dead people are placed), usually used for an important person and/or in an important place
* The former president was interred this morning after a long church service.
to go in – to enter a building; to go inside an enclosed place; to fit; to belong to a certain place
* I’m so glad you could come! Go in and say ‘hello’ to everyone.
to go into – to talk about something for a long time; to have an in depth discussion about something; to begin a career in a specific field
* We don’t have time to go into the details for the event, so let’s meet again next week to do that.
to get in – to enter a car or a building; to arrive at a bus station, airport, or other public transportation station; to reach home or work; to get accepted by a school, group or organization
* What time does your flight from Seattle get in?
to get into – to become interested in; to begin to spend a lot of time or energy on; to get accepted by a school, group or organization; to make a mess
* How did your sister get into building boats?
overwhelming – very strong or powerful; impossible to fight against
* Sheila felt an overwhelming sense of sadness when she heard that her favorite movie star had died.
off-kilter – not arranged in a straight line; not balanced; unconventional; not done in a traditional, normal, or expected way; not quite right
* That picture is off-kilter and is hung lower on the left side than on the right.
What Insiders Know
Jaws and Moby-Dick by Herman Melville
“Screenwriters” (writers of scripts for television shows and films), like writers of books and stories, often “draw” (get; take) influences from other “literary works” (high quality books and written stories). Many people have “noted” (stated; written about) the similarities between the film Jaws and the book Moby-Dick published in 1851 by American writer Herman Melville (1819-1891).
Moby-Dick is a “novel” (story that is book-length) about a ship “captain” (leader of a boat or ship) named Captain Ahab. Captain Ahab is “obsessed with” (have only this one goal in mind, paying attention to nothing else) killing Moby-Dick, a sperm whale. In a “previous” (before now) meeting between Captain Ahab and Moby-Dick, the whale destroyed his boat and “bit off” (removed by using one’s teeth) one of Captain Ahab’s legs.
Some people have said that the character of Quint in Jaws is very similar to Captain Ahab because he is also obsessed with killing a dangerous sea creature, a white shark. In fact, in the original “screenplay” (script for a movie with the lines the actors are to say and instructions for filming), the character of Quint is first introduced in the movie while watching a film version of Moby-Dick. Unfortunately, because the makers of Jaws could not get permission to use the film’s “footage” (part of a movie), that scene had to be “cut” (removed) from the Jaws screenplay.
Moby-Dick is often called the “Great American Novel” because it is considered one of the “finest” (best) pieces of American literature. Many high school students in the U.S. read Moby-Dick in their English class and the characters of Captain Ahab and Moby-Dick are well known to many Americans.