= 1828
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 523.
This is English as a Second Language Podcast’s English Café episode 523. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store with additional courses in Daily and Business English. You can also like us on Facebook at facebook.com/eslpod. And why not follow us on Twitter at @eslpod, of course.
On this Café, we’re going to talk about a famous American movie from the early 1930s called Frankenstein. We’re also going to talk about a famous American singer and entertainer, James Brown. And as always, we’ll answer a few of your questions. Let’s get started.
Back in 1818, the British author Mary Shelley wrote a novel called Frankenstein. Shelley was only 20 years old, the wife of the famous older English poet Percy Shelley. Frankenstein is considered one of the great examples of what is called a “gothic (gothic) novel.” It has some very dark elements to it. Gothic novels often take place in buildings that are built in “gothic” or “neo-gothic” style. Gothic novels often have horror as the theme. You can think of the American poet Edgar Allan Poe as another example of someone who wrote in this dark, gothic style.
Frankenstein the novel was not considered a great book by the critics in the early part of the nineteenth century, but it was a very popular novel, a novel that was very soon after its publication translated and turned into a play. The book continued to be popular throughout the nineteenth and early twentieth centuries, so it was no surprise that the movie industry got interested in making a film based on the book.
In 1931, the movie Frankenstein begins with one of the actors, a man by the name of Edward Van Sloan, coming onto the screen to give the audience a message from the director. This was a very unusual way to begin a movie. He tells the audience that the story they are about to see is something they never could have imagined. He says it is “horrifying.” “Horrifying” (horrifying) comes from the word “horror” (horror), which means very scary, very frightening.
He says that some people in the audience may become too scared to watch the whole movie. Well, that of course is a great way to begin your movie. It gets everyone interested in the movie. The movie Frankenstein is slightly different than the original book. In the movie, the name of the scientist is Dr. Henry Frankenstein, not Victor Frankenstein, as it is in the book.
In the movie story, Henry Frankenstein becomes obsessed with his experiments, his scientific experiments. “To be obsessed” means to only be able to think about one thing, to spend all of your time thinking about this one thing. An “experiment” is a scientific investigation, usually to learn more about something or to see if your hypothesis – your guess about the way the world works – is true or not.
Frankenstein becomes so obsessed that he leaves medical school. He stops speaking to his fiancée – the woman he’d promised to marry – and to his friends, and he spends all of his time in his laboratory with his assistant, Fritz. Fritz is a small and not very intelligent man who does whatever the doctor tells him to do. The two of them are working in a laboratory, which is basically a room where scientists perform experiments.
When Frankenstein’s friends and family do talk to him, they learn that Frankenstein is trying to create life. He’s trying to create a living creature, something that no one else has done before. In fact, the moment that Frankenstein is able to bring this creature, this thing, to life, he says, “It’s alive,” which means, of course, it is living. He has created life. That phrase, “It’s alive,” is one of the more well-known expressions from the movie.
Anyway, Frankenstein creates life by creating what we would call a “monster” (monster). A monster is usually a creature that is dangerous or that can hurt us. Well, the reason the monster created by Frankenstein is dangerous is that Fritz, his assistant, put a criminal mind into him. He found the brain of someone who was a criminal – dead, of course – and put that into the monster, and now of course Frankenstein is not just alive but he’s also dangerous. In fact, the scientist Henry Frankenstein has no idea what the monster is capable of – that is, what he will have the power to do.
Well, when you create a monster, of course, bad things will happen, and bad things do happen in the movie. Frankenstein and Fritz try to prevent the monster from leaving the place where the experiment is taking place. However, the monster kills Fritz and ends up escaping. Several other bad things happen as the monster is wandering around the village, but eventually the movie does have a happy ending for everyone – except the monster.
It has become common over the years for people to refer to the monster as “Frankenstein,” even though in the book and in the original movie, Frankenstein is the name of the scientist who creates the monster. But you will hear people talk about creating a “Frankenstein,” referring to a monster. In fact, several other films were made after Frankenstein in which the monster himself is called “Frankenstein.”
When they were planning to make the 1931 version of Frankenstein, the producers wanted to have another famous actor in horror movies, Bela Lugosi, play the part of the monster. Bela Lugosi is most famous for playing another horrible character during the movies of this time period: Dracula. Unfortunately, Bela Lugosi was unable to play in the movie. He was doing something else, so they chose another actor by the name of Boris Karloff. In the movie, Karloff is this big, ugly monster who walks with a great deal of stiffness – that is, he’s not able to bend his arms and legs easily.
The monster that Karloff did is certainly one that would likely give moviegoers nightmares – that is, bad dreams. Karloff’s monster is very scary. In fact, there were some parts of the movie that were so shocking that they had to take them out of the final production of the movie. When I say they were “shocking” (shocking), I mean they were very frightening. Some people thought they were too frightening. There’s one scene in the movie in which the monster throws a little girl into the water and the girl dies. That was a scene, a part of the movie, that was removed from the movie before it was shown to the public.
Although it is a horror movie and many people think horror movies aren’t of a very high quality, this movie is considered one of the better movies of the twentieth century, or at least one of the movies that deserves to be remembered. It is considered one of the 100 best films by the American Film Institute, an organization that goes around and, well, makes lists of great movies, I guess.
I mentioned that there have been many other versions of the Frankenstein story told in the movies over the past 80 years or so. In fact, there were sequels to the Frankenstein movie. A “sequel” (sequel) is a movie that continues the story. There was The Bride of Frankenstein (and here, Frankenstein is used as the name of a monster). There were also what we would call “spoofs” of the movie. A “spoof” (spoof) is when someone makes fun of the movie.
An early spoof involved two famous comedic actors, two famous comedians who made a lot of movies during the 1930s and ’40s, Abbott and Costello. There was a movie called Abbott and Costello Meet Frankenstein. There was a comedy made back in the early ’70s called Young Frankenstein. When I was growing up, there was a black-and-white television comedy called The Munsters, in which one of the characters was based on Frankenstein, especially the look of Frankenstein that Boris Karloff had in the movies.
I have to admit, I’ve never seen the original 1931 movie Frankenstein. I’m not sure if I would be scared by it today. To be honest, I’m really not a big fan of horror movies, of movies that are supposed to scare you, but they have been popular since the beginning of movies, and I’m sure someday soon there’ll be another Frankenstein movie in the movie theaters or on your tablet.
Our second topic is the great singer and performer James Brown. James Brown was born in May of 1933 in the state of South Carolina. South Carolina is located in the southeastern part of the United States, on the Atlantic Ocean. Brown ended up becoming one of the most famous entertainers of the twentieth century. We use the word “entertainer” (entertainer) as a broad category to describe someone who might be a singer, might be a dancer, might do other things that entertain or make people laugh and enjoy a performance.
Brown moved at an early age to Georgia when his parents divorced. He grew up a very poor child. He often didn’t have enough food, and at one point was told he had to leave school because he had insufficient clothes. “Insufficient” (insufficient) simply means not enough. The opposite of “insufficient” would be “sufficient.” Brown learned to sing and play instruments such as the guitar and the drums, both from his neighbors and from the church where he and his great-aunt, who was raising him, went to.
The church, like many churches in the South for African Americans, was what we might refer to as a “gospel church.” “Gospel” here refers to the kind of music, the kind of service that was held in these churches. There is often a lot of very energetic music and other forms of prayer. Some of these forms of worship that you can find in churches that have gospel music and are in this particular tradition have forms of worship that have a lot of energy to them, just like the music that is sung during the services at these churches.
James Brown learned a lot from those church services and took a lot of that energy and used it in his own performances later on. When he was just 15 years old, Brown got in trouble with the law – that is, he got arrested by the police. His crime was breaking into cars, and he went to jail for that for three years. When he got out of jail, he started his first musical group, his first band, which he called “The Famous Flames.”
The music that he was performing was soon noticed by another musician, by the name of Little Richard. Little Richard, like Brown, would also go on to become a famous musician in the United States. More importantly, though, James Brown’s music was noticed by someone from a record label – that is, a company that makes records. Brown was signed to the King label and recorded his first song, “Please, Please, Please,” in 1956. This song became incredibly popular. In fact, it sold three million copies and it made Brown an instant celebrity, a very famous person.
Over the next 30 years, James Brown had over 100 popular songs and more than 50 albums. He recorded the very first live albums. Although Brown was popular in the 1950s, his most famous songs came in the middle of the 1960s and the early 1970s. Those songs include “I Got You (I Feel Good).” Most people know it simply as “I Feel Good.” “It’s a Man’s Man’s Man’s World,” and “Get Up Offa That Thing.”
In the 1980s his music was not as popular, although other musicians started to use some of the elements, some of the parts, of his songs. This became especially popular among hip-hop artists. Hip-hop musicians began using parts of Brown’s songs in their own songs, and this brought Brown back into popularity. People started to go back and listen to his music. One of the most famous things about Brown was not only his music and his voice but his way of performing. He became known as the “hardest working man in show business.”
“Hardest working” means the person who was working the most. “Show business” is just a way of describing, in a very general way, the entertainment industry. We call it here in Los Angeles simply “the industry” – movies, music, television, that sort of thing. Brown became very involved in his performances. He selected these amazing costumes – shirts and jackets and pants – and he would perform different dances. He would jump up and down on the stage. He had an amazing amount of energy when he was performing.
He was also very famous for screaming during his songs, during his performances, and falling to his knees – that is, going down on his knees – during a song, during a performance. You might describe James Brown’s performances as being “flashy.” Something that is “flashy” (flashy) is something that gets people’s attention, that often costs a lot of money. You can think of, for example, rock stars or celebrities that like to wear gold chains around their neck. Those are flashy. Those are meant to get your attention.
In addition to being a popular entertainer, Brown was also what we might describe as an “activist.” An “activist” (activist) is a person who works to create some change in society, often a political change. The 1960s and early 1970s were important years during the civil rights movement, when people were trying to create equal rights under the law for African Americans and other racial and ethnic minorities. Brown often participated in different civil rights demonstrations and other activities to try to improve the situation of African Americans in the United States during this time.
While Brown was a very successful professional in his singing and entertaining career, his personal life was not as successful. This, as we’ve mentioned many times, is not unusual for people in the entertainment industry. He married four times and had six children. In the 1980s, Brown began to have serious problems with illegal drugs, which caused him to get in trouble with the police and to go to jail. He was also very violent with at least three of his wives and was accused of beating or hitting them.
My memory of James Brown certainly wasn’t very positive when I was in college during this period of the 1980s, but that doesn’t mean that he wasn’t a great singer and performer. Sometimes great artists are not-so-great people. Brown died of pneumonia, a disease of the lungs, in 2006. His songs and his famous performances can still be heard today. If you’ve never heard or seen James Brown, you should definitely look it up on the Internet and watch one of his videos. You’ll see what I mean by the energetic performances that he was famous for.
Now let’s answer a few of your questions.
Our first question comes from Sergey (Sergey) in Russia. The question has to do with three words, “to boost,” “to foster,” and “to encourage.” I’m going to start with the last of those three, “to encourage” (encourage). “To encourage” a person means to urge them to do something – to make them feel more confident or perhaps more determined. If someone says, “I encourage you to study English,” that person is saying, “I think it’s a good idea for you.” The person is trying to motivate you to get you to do something that he thinks will be good for you.
The opposite of “encourage” is “to discourage.” Normally, “to encourage” is used when the person isn’t forcing you to do something, the person isn’t making you do something or demanding that you do something, but rather trying to motivate you to do something by saying things to you. Maybe you doubt that you are able to do something. Maybe you don’t have the confidence to do something. That would be a case where someone may “encourage” you to do it, to give you that confidence or that hope.
“To boost” (boost) usually means to increase or improve something, to help something increase and improve. You might say, “I’m going to boost his confidence.” I’m going to increase his confidence. We could also use “boost” to talk about, say, sales in a store. “What can we do to increase sales?” – to increase the amount of things we sell. “What can we do to boost sales?”
“To foster” (foster) means to promote the development of something. Normally when we use this verb “foster,” we use it in very specific situations, such as with the word “growth.” “I’m going to foster growth.” That means I’m going to do things that will cause something to grow. It could be the sales of my company or it could be confidence in a certain ability to do something.
A government might change its economic policies to “foster economic growth” in a country, or we might “foster better communications.” We might do things so that we are able to communicate with each other better. When I hear the word “foster,” the verb “to foster,” I think of things that you do that might not have a direct impact on the result that you want. “To foster” often means to do things that will eventually perhaps lead to an increase in something, whether it’s development, whether it’s economic growth, whether it’s an increase in communication.
The verb can also be used to mean to raise a child who is not your own, not your own biological son or daughter, though normally the word “foster” is used as an adjective in that instance. “He’s my foster child.” He’s not my child but he’s a child whom I am raising, whom I am taking care of. Usually “foster children” are children who have not been adopted legally as a son or a daughter but are being raised by someone who is not their mother or father, their biological mother or father.
Our next question comes from Liu (Liu) in an unknown country. Liu wants to know the meaning of the word “funky” (funky). “Funky” is a word you don’t hear very often anymore. It used to be quite popular during the late twentieth century, if you can remember back that far, to describe a kind of music that had a very strong dance rhythm or dance beat. In fact, there’s a kind of music that was called “funk music.”
Funk music was popular especially among certain African Americans during this time period. It had elements of soul music and had a very strong beat. Later, there developed this adjective “funky” to describe more generally something that seemed unique or strange and yet had an attractive quality about it – something that had an odd look, but yet was somehow appealing, something you could like.
A third definition of “funky” would be something that smells bad, something that has a bad odor. I think we use it less commonly in that third sense. If you hear it at all or see it at all today, it probably will have the meaning of being somehow unique or strange. I suppose we might also use it in the negative sense of something not working properly. I could see someone saying, “There’s something wrong with my word processing program. It’s acting all funky.” That means it’s not working properly. It’s working in a strange way, but not in a good strange way.
Finally, Benoit (Benoit) in France wants to know the meaning of the phrase “right (right) as rain (rain).” He heard it in a movie. “Right is rain” means perfectly fine, all right, everything is great. “How are you feeling?” “I’m right as rain.” I’m feeling great. I’m feeling perfectly fine.
“Right as rain,” I would say, is probably more common in British English than American English, although you will certainly hear Americans use this phrase. I tend to associate it more with British English. I wouldn’t be surprised to see it, say, in an old British movie. The singer, the British singer, Adele has a song called “Right as Rain.” I think in American English we would probably use some equivalents such as “great” or “fine” or “no problem.” “Everything’s going well,” perhaps. It would depend, really, on the circumstances.
If you’d like to boost your English knowledge and have a question, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
horrifying – extremely scary; very frightening
* The photos of the city after it had been flooded were horrifying because of the extensive damage it had done to people’s homes.
to be obsessed – to only be able to think about one specific thing nearly all the time in an unhealthy way
* Marcella became obsessed with trying to lose weight and began weighing herself every day and eating only one small meal a day.
experiment – a scientific investigation to learn more about something or to prove something is true or false
* Marcella wanted to find the fastest way to get to work, so she conducted an experiment by leaving the same time each day, but taking different routes.
laboratory – a room or building where scientists perform experiments or tests to learn new things
* The scientists kept their laboratory clean to be sure that dirt or bacteria would not affect any of the experiments.
to be capable of – to be able to do something; to have the power to do something
* Amir didn’t think he was capable of running a marathon, but he trained hard and was able to finish the race in four hours.
nightmare – a very scary dream; a bad dream
* She woke up from a nightmare in which she was drowning and couldn’t breathe.
shocking – frightening or offensive, causing people to have strong negative emotional reactions
* The people of the city found it shocking when the mayor admitted that he had often come to work drunk.
entertainer – a performer; a person who sings, dances, or performs in some way for an audience’s enjoyment
* When the entertainer came on stage, the audience members clapped and cheered.
insufficient – not enough; too little
* Mary tried to withdraw $200 from her bank account but was told that she had insufficient funds. The account only had $50 in it.
label – a record company; a company that pays singers to record music, then takes a certain amount of the money the artist earns from selling that music
* The label had new artists sign a contract promising to pay the company 55% of any money they made on their music.
show business – the business of entertainment, including movies, music, and television
* Many people involved in show business live in Los Angeles or New York where many major entertainment companies are located.
flashy – something that gets people’s attention and may cost a lot of money, used to impress other people
* Enrique loved flashy cars and owned a red Ferrari, a yellow Lamborghini, and a white Aston Martin.
activist – a person who works to create change in society
* She was an activist, dedicating her life to change public policy to help the homeless.
to boost – to help or encourage something to increase or improve
* Do you think the new TV commercials will boost our sales by at least 20%?
to foster – to promote the growth or development of something
* Jane fostered a love of reading in her children by taking them to the library each week.
to encourage – to help make someone more determined, hopeful, or confident
* Kwame’s teacher encouraged him to apply for the prestigious college scholarship.
funky – (music) having or using a strong dance rhythm or beat; having a bad odor; having an odd appearance or feeling
* This club plays funky music that gets everybody onto the dance floor.
right as rain – perfectly fine; all right
* A: Are you upset about what Camile said about your girlfriend?
B: No, I’m right as rain. I don’t care what she thinks.
What Insiders Know
The Munsters
The popular 1960s television “comedy” (entertainment to make people laugh) The Munsters “centered around” (was about) a family of friendly monsters. It first “aired” (was shown on TV) on September 24, 1964 and “ran” (continued to be shown) until May 12, 1966, producing 70 “episodes” (shows).
The show was about the Munsters family, who lived in a “fictional” (not real; imaginary) “suburb” (a neighborhood with homes outside of a big city) in California. While the family was very “odd” (different from what is usual or expected) in appearance, the Munsters consider themselves as a typical “working-class” (with average income) people. The Munster family included the father, Herman Munster, his wife Lily, their teenage daughter Marilyn, their son Eddie, and the children’s grandfather, simply called “Grandpa.” The family showed a mix of personalities in a regular 1960s family. Herman was the only “wage” (salary; money from working) earner. Lily was a “nurturing” (caring and encouraging) mother. Grandpa was an “eccentric” (unusual and slightly strange) “live-in” (living in one’s home) relative.
The Munsters were “cancelled” (no longer shown) due to a drop in “ratings” (a measure of how many people watched the show) after another show began to air: Batman. The Munsters were shown in black and white, but Batman was shown in color, which attracted a lot of viewers.
While the original The Munsters sitcom was cancelled after 70 episodes, several “remakes” (made again with a new cast (group of actors)) and “spin-offs” (show based on one or more characters or some element of an earlier one) were produced. Several Munsters movies were also released, three of which featured the original “cast members” (actors in a show).