= 1831
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 526.
This is English as a Second Language Podcast’s English Café episode 526. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Why don’t you go there? If you do, you can become a member of the ESL Podcast and download the Learning Guide for this episode. The Learning Guide contains a complete transcript of this episode – the vocabulary words, definitions, sample sentences, cultural notes, and a whole lot more. Go to ESLPod.com and become a member.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – that is, at a normal speed. We’ll listen to them and then explain what they’re talking about.
Today we’re going to talk about journalism and technology. And as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is journalism and technology. As usual, we’re going to listen to some people who were interviewed by Voice of America. That’s where we get most of our Ask an American segment audio clips. The people we are listening to today are either journalism professors or students.
A “journalist” (journalist) is a person who works for a newspaper, magazine, television station, or radio station who reports on the news – who investigates news stories and reports them or writes about them or speaks about them to the public. The noun “journalism” describes this activity. We also use the word “reporter” when we are talking about someone who is a journalist.
These three people are all from the University of Southern California’s Annenberg School of Journalism. It’s popular in American universities, when someone gives a lot of money to the university to give a certain school or college within the university that person’s name. So, we have the Annenberg School of Journalism because a man by the name of Walter Annenberg, who had a lot of money, gave a lot of that money to the University of Southern California here in Los Angeles. USC, as we call it here in Southern California, is the school that I got my Ph.D. from.
ell, these three people are going to talk about how journalism has changed because of new technology. First we’re going to listen to Willow Bay, who is the director of this school of journalism. She’s going to talk about what journalists, what students who are studying to be journalists, have to learn nowadays in order to be a good journalist, according to her.
Let’s listen and then I’ll explain what she’s talking about.
[recording]
“Today we expect journalists to be able to use all sorts of technological tools to research stories, to vet that research, to analyze that research. We expect them to be fluid in multimedia storytelling skills. We expect them increasingly to be their own marketing and distribution arms, to get their stories in front of audiences and to spread those stories as far as they can.”
[end of recording]
Professor Bay begins by saying, “Today, we expect journalists to be able to use all sorts of technological tools to research stories, to vet that research, to analyze that research.” “All sorts of” means many different kinds of. So, she’s saying that journalists have to be able to use a lot of different kinds of technological tools. The word “tool” (tool) here just means different kinds of technologies or different kinds of devices, perhaps.
These tools are used to “research stories” – meaning to find out more about the story, to get more facts about the story – as well as “to vet (vet) that research.” The verb “to vet” means to carefully check and investigate something to make sure that it’s accurate, to make sure that it is correct. You may have a lot of different facts that you are looking at as a journalist. You want to make sure that what you say in your story is correct, is accurate.
We also use this verb “to vet” when we are hiring someone for a company. We may get many different applications and we have to vet those people. We have to make sure that they are as qualified as they say they are. The government has to vet new employees, especially if they are hiring them to do things like security or things involved with secret documents. “To vet” someone there would mean to investigate the person to make sure that they, well, weren’t spies for another country. But here, “to vet” just means to research carefully to make sure something is accurate.
Dr. Bay – I assume she has a Ph.D. – continues by saying, “We,” meaning the people at the journalism school, “expect them,” meaning the students, “to be fluid in multimedia storytelling skills.” Well that’s quite an expression. “Fluid” (fluid) normally means to be moving in an elegant and graceful way, if we’re talking about a person. “Fluid” might also mean simply to be moving forward or performing without any difficulties. I think it’s the second meaning that Dr. Bay is trying to convey to us.
She might actually be thinking of a completely different word, which is “fluent” (fluent). I’m not sure. “To be fluent,” for example, in a language means to be able to use it easily. In either case, she’s the journalism professor so what do I know? She wants her students to be fluid in “multimedia storytelling skills.” “Multimedia” refers to many different kinds of or means of communication. It could mean audio. It could mean video. It could mean text. We sometimes use the word “multimedia” to refer to something that uses a lot of different kinds of technology.
“Storytelling” refers to the ability to, well, tell an interesting story. “Skills” are abilities that you have to do something. So, we put it all together: “multimedia storytelling skills” would be the ability to tell a good story using different kinds of technology. She continues, “We expect them increasingly” – more and more ?– “to be their own marketing and distribution arms.” “Marketing” refers to getting people to know about your company, your product,or whatever it is that you are selling or whatever it is that you are doing.
Most companies have a “marketing department” whose job it is to let the world know about what the company is selling and of course to get people to buy what the company is selling. “Distribution” (distribution) refers to getting things from one place to another, moving things from one place to another. But in this case, it really refers to making sure that whatever it is that you’re producing – in this case, new stories – gets to a lot of different people. Now, to do that could mean using the Internet. It could mean using the radio. It could mean using the television.
In the quote, Dr. Bay talks about “marketing and distribution arms” (arms). You probably know that your arms are the two things that extend out of your body, from the top of your body, that have your hands connected to them. Well, here “arms” means different means or different channels – different ways of marketing and distributing something. Dr. Bay is saying that the students themselves, when they become journalists, will have to in some cases be their own marketing and distribution arms, meaning they themselves will have to go out and sell, if you will, what they’re reporting on and distribute it.
She also says the students will have to get their stories “in front of audiences and to spread those stories as far as they can.” The expression “to get a story in front of audiences” mean simply to distribute the story, or to make the stories available for people to read or to listen to or to watch. “To spread a story as far as you can” means to get as many people as possible to see that story or to read that story.
Now let’s listen to Dr. Bay one more time.
[recording]
“Today we expect journalists to be able to use all sorts of technological tools to research stories, to vet that research, to analyze that research. We expect them to be fluid in multimedia storytelling skills. We expect them increasingly to be their own marketing and distribution arms, to get their stories in front of audiences and to spread those stories as far as they can.”
[end of recording]
Next, we listen to a professor of digital journalism, Robert Hernandez, giving a more specific example. I think here he’s actually talking to a group of students, explaining to them one way that they could cover or report on a certain story. Let’s listen and then we’ll talk about what he says.
[recording]
“You can do a 360 panorama through your phone, right? We can talk about what a tornado looks like, how it rips trees out of the ground, and through their phone, there’s an app to kind of stitch that together.”
[end of recording]
Professor Hernandez is talking to his students, we think. He begins by saying, “You can do a 360 panorama through your phone, right? A “panorama” (panorama) is a very large or wide view of an entire area. Usually we use this word to refer to a photograph or perhaps a painting of a large area of land, what we might also describe as a “landscape.”
A “360 panorama” refers to a 360-degree panorama. It would be a view of a complete circle, or everything around you at one point. A “circle,” of course, has 360 degrees. So, a “360 panorama” would require you to stand and then turn in a complete circle so you capture, presumably on film, everything around you in a complete circle. The word “panorama” should not be confused with the female rock group of the 1980s, Bananarama – who has, of course, the famous hit “Venus.”
“I’m your Venus,
I’m your fire,
At your desire . . .”
remember, you know, “Venus” – that one. Yeah. Anyway, that’s Bananarama. This is “panorama” – completely different, so don’t confuse them. Dr. Hernandez is instructing his students about getting a 360-degree panorama using your cell phone. Phones of course nowadays, cell phones, often have cameras in them, including video cameras. He continues, “We can talk about what a tornado looks like.” A “tornado” (tornado) is a very strong windstorm that spins around in a tight circle; it looks like what we call a “funnel” (funnel).
“Tornadoes,” which are quite common in the central part of the United States, can cause a lot of damage. In fact they can, as Dr. Hernandez describes, “rip trees out of the ground.” “To rip (rip) trees out of the ground” means to pull the tree out of the ground – the force of the wind of the tornado is so strong that it can actually remove the tree from the ground and move it to a different place. If you haven’t experienced a tornado as I have, you’ve probably seen them on a video or on television or perhaps in a movie.
Dr. Hernandez is trying to give his students ways that they could talk about a tornado story, a story about a tornado – how they can film the, perhaps, damage that a tornado has done and then how they can take that video and stitch it together. He says, “There’s an app,” meaning an application on your phone, “to kind of stitch that together.” “To stitch” (stitch) here means to put together.
Usually the verb “to stitch” is used in what is called “sewing” (sewing), which involves connecting different pieces of cloth together in order to make, say, clothing. But here, the verb “to stitch” is used to mean to put things together. In this case, it would be to put different video clips or video films together in order to create a story for a television station or perhaps a YouTube video.
Let’s listen to Dr. Hernandez one more time.
[recording]
“You can do a 360 panorama through your phone, right? We can talk about what a tornado looks like, how it rips trees out of the ground, and through their phone, there’s an app to kind of stitch that together.”
[end of recording]
Next we’ll listen to the executive director, or head, of the media center at the Annenberg School of Journalism. The “media (media) center,” we guess, is a place where they have lots of different technological tools that students can learn from. Her name is Serena Cha. Let’s listen.
[recording]
“In the journalism arena, we’ve got to consider carefully. How do we teach students to use the tools responsibly? So, yes, new technology often raises new questions because you’re able to manipulate reality even more than before.”
[end of recording]
Serena Cha begins by saying, “In the journalism arena, we’ve got to consider carefully. How do we teach students to use the tools responsibly?” “Arena” (arena) here just means the field or the general area of study. In this case, it’s the journalism arena. It’s really just another way of saying “journalism.” I’m sort of surprised. Some of the quotes coming from these professors don’t sound like the most concise way of describing the things they want to describe – maybe that’s why they’re journalism professors and not actually journalists. Now, that’s not very nice, is it?
Anyway, Serena says, “In the journalism arena, we’ve got to consider carefully. How do we teach students to use the tools,” the technological tools, “responsibly.” She continues, “So, yes, new technology often raises new questions.” “To raise (raise) new questions” means to present questions for the first time, to deal with or talk about a situation that you’ve never had to deal with or talk about before.
Technology raises new questions about a lot of different things – “privacy,” for example. “Privacy” (privacy) is keeping your information secret. It’s not letting other people know about things you don’t want them to know about. We could say that new technology raises new questions about how we protect our privacy. Professor Cha says new technology often raises new questions “because you’re able to manipulate reality even more than before.”
“To manipulate” (manipulate) something means to change it in some way, especially in a way that meets your own purposes – that perhaps even fools or tricks other people. If you talk about a person being “manipulative,” the adjective, you are describing someone who tries to get people to do what he or she wants them to do in a way that isn’t very honest, perhaps, or isn’t very straightforward.
Professor Cha is talking about journalists “manipulating reality.” “Reality” (reality) is the way things really are. If you manipulate reality, you somehow change something so that it isn’t really true or that it doesn’t really reflect the actual situation. Now, the funny thing about this quote is that Professor Cha is talking about new technology being able to manipulate reality “even more than before,” meaning we could manipulate reality before and possibly did. Now with this new technology, we can manipulate it even more.
Of course, the implication here is that journalists have been manipulating reality all along, which is probably not something that as a journalism professor you want to admit. But we appreciate Professor Cha’s honesty.
Now let’s listen one more time.
[recording]
“In the journalism arena, we’ve got to consider carefully. How do we teach students to use the tools responsibly? So, yes, new technology often raises new questions because you’re able to manipulate reality even more than before.”
[end of recording]
Now let’s answer some of the questions you have sent to us.
Our first question comes from Shu (Shu) in China. The question has to do with the term “liberal arts education.” The word “liberal” (liberal) has several different meanings in English. In Latin, I believe the word “liberal” means relating to a free person, and the “liberal arts” originally referred to the subjects that a free person, a person who was not a slave, would study and would know. If you were an intelligent, free person, you were a person who knew about these different subjects, and so “liberal arts” (arts) refers to the subjects that you would study in order to be an educated person.
During the late classical period in Europe – that is, oh, say, from the fourth to the sixth century A.D. – and in medieval Europe, there were seven subjects that were considered “liberal arts” that every educated person would study. Those seven liberal arts were music; arithmetic, that is adding and subtracting numbers; geometry, the study of points, lines, and circles (that sort of thing which is most often associated with the Greek, Euclid); astronomy, the study of the stars; grammar; logic, the study of reason; and rhetoric, the study of persuasion – of convincing other people that you are right, both in writing and in speaking.
These were the seven liberal arts that were traditionally studied. However, now in the modern era, in modern times, “liberal arts” at a university usually includes a lot more than just those seven categories. In fact, some of those categories would no longer be considered part of the liberal arts, such as arithmetic, geometry, and astronomy. The liberal arts nowadays includes things such as history, the study of languages and literature, anthropology, sociology, psychology – all of these might be found in a school or college of liberal arts at a university.
At my university where I got my undergraduate degree, the University of Minnesota, the College of Liberal Arts contained lots of things, lots of areas of study, that were never part of the traditional seven liberal arts from the classical period and the medieval period. In even more general terms, people use that expression “liberal arts education” to refer to the study of things which are not technical and scientific. So, studying art or philosophy, for example, might not to some people seem very practical. It certainly isn’t technical in the way that studying computer science is.
There’s been a lot of debate and discussion in the United States about the role or place of the liberal arts in the education of those who attend our universities. I graduated from the College of Liberal Arts, so I guess I’m a little bit biased. I tend to be in favor of the study of the liberal arts and a liberal arts education.
Richard (Richard) from Germany wants to know the meaning of the expression “second to last” or “second to the last.” “Second,” of course, comes right after “first” in a ranking or in a placement of importance. “Second” is what we would call an “ordinal (ordinal) number.” “Ordinal numbers” put things in order. There’s first, second, third, fourth, fifth, sixth, seventh, eighth, ninth, tenth – those are ordinal numbers.
You can have something that is first in a group of, say, people or things. If you have a group of students, the best student would be “first.” The worst student would be “last.” So the term “last” is also ordinal in that sense. The expression “second to last” would refer to not the worst or bottom person or thing, but the one just above that.
I think it would be okay to say either “second to last” or “second to the last” when talking about, for example, a student in the class. “He’s the second-to-the-last student in terms of his grades.” You could also refer to someone in a line, for example, waiting to go into a movie theater – someone is “second to last in the line.” He’s not the last person in line; he’s the second-to-last (or second-to-the-last) person.
We actually have another word in English for this concept, and it is “penultimate” (penultimate). “Penultimate” means second to last. In fact, there’s another word that means third to last which is “antepenultimate.” You add an (ante) at the front of the word. That word, however, is quite rare in English. You’ll probably never see that in writing. After “penultimate” people would start using the ordinal numbers – “third to last,” “fourth to last,” and so forth.
Our final question comes from Huang (Huang) from an unknown country, perhaps from the smallest country in the world. Do you know what the smallest country in the world is? Sure you do. It’s, I think, Vatican City, located in Italy in the city of Rome. Maybe Huang is actually the leader of Vatican City, the Pope. We thank the Pope for writing us.
The question has to do with the meaning of the expression “I am hearing you.” This is an interesting question because we have two common verbs in English that sometimes mean the same thing or are used to mean the same thing. Those verbs are “to hear” (hear) and “to listen” (listen). “To hear” means to perceive a sound. Someone may be knocking at your door or you may hear a bird outside. The sound enters into your ear and you are conscious of it. You know it’s there.
“To listen,” usually followed by the proposition “to,” means to pay attention to a sound or a series of sounds. We talk about listening to a television program or listening to the radio or listening to our husband or wife talk about what a good day they had (or more commonly, what a bad day they had). All of these are examples of “listening” to something. When it relates to sound, the verb “to hear” usually just means “to perceive.” You’re conscious of it. It’s not used typically to mean “I’m paying attention to something,” especially over a long period of time.
However, there are some uses of the verb “to hear” that can have a similar meaning as “to listen,” usually when it’s followed by a clause. For example, “My girlfriend doesn’t hear what I am saying.” That would mean my girlfriend doesn’t listen to what I am saying. However, it could have another meaning which is “My girlfriend doesn’t understand what I am saying.”
And in the example that Huang asks about, “I am hearing you,” the verb “to hear” is closest to the meaning of the verb “to understand” – to understand what someone is saying and to really maybe even feel what the person is feeling. If someone is explaining something to you and perhaps is a little frustrated that you don’t understand what he or she is talking about, you may say, “Yeah, I hear you.” I hear you – I understand what you’re saying. Depending on how you say that expression, it could mean that you understand and no longer want the person to continue talking about it.
We might also use this expression “I hear you” when someone is describing some experience that we also have had or that we also understand. So, you’re at a bar and you’re talking to your friend and you’re complaining about how, I don’t know, your wife never does what you want her to do, and your friend says, “Yeah, I hear you, man. I hear you.” That usually means that you’ve had the same experience, and therefore you really understand what the person is saying.
If there’s something that you don’t understand, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
journalist – a reporter; a person whose job is to report the news, especially in writing
* A journalist needs to have good research, interviewing, and writing skills, and the ability to work under tight deadlines.
to vet – to carefully check or investigate, making sure that one’s research and facts are accurate and correct
* Any engineers working on government contracts need to be vetted by security.
fluid – working well, flowing in an elegant or graceful way, without experiencing problems or delays
* The exchange of ideas is fluid among the six team members.
multimedia – using two or more types of communication or media, such as a combination of written, audio, and visual information
* Everyone in the public speaking class has to prepare a multimedia presentation using PowerPoint, video, and handouts.
marketing – the act of promoting one’s work, products, or services to attract consumers who may want to buy it
* Tobacco companies are not allowed to direct their marketing to young children or teenagers.
distribution – the act of sending one’s products to many stores or consumers spread over a large area, making sure that potential buyers have access to it
* Bob is in charge of distribution throughout the Pacific Northwest, and Heather focuses on the southeastern United States.
arm – one branch, department, or part of an organization
* The logistics arm is responsible for making sure that the right resources are available at the right time.
panorama – a very large or wide view of an entire area, like a full landscape
* On this tour, we’ll see breathtaking panoramas of the Grand Canyon.
tornado – a very strong windstorm where the wind spins around and around in a tight circle that looks like a funnel, bigger on the top than on the ground
* The tornado was very destructive, lifting up trees, cars, and even roofs.
to rip (something) out – to pull something apart very strongly or to separate it from something else
* The little boy tried to rip out his tooth by tying a string around it.
to stitch – to sew or otherwise put things together in some way
* The detectives are trying to stitch together the facts to figure out who committed the crime.
to raise new question – to pose or present questions for the first time, asking things that people have never thought about before
* The popularity of educational apps for very young children raises new questions about the effects of technology on brain development in early childhood.
to manipulate – to change something in some way, especially for one’s own purposes, often to trick others in some way
* In the study, researchers manipulate the environment to see how the subjects react.
reality – what is real and true; what actually happens
* It’s fun to imagine time travel, but in reality, it is impossible.
liberal arts – areas of study, including history, language, and literature, that are intended to give one general knowledge, rather than to develop specific skills needed for a profession or job
* It can be difficult to find a high-paying job with a degree in the liberal arts. Have you considered studying science and engineering instead?
second to (the) last – indicating the one immediately before the final or last in a list or line; in order, the item/person before the final item/person
* My performance in that race was so embarrassing! I finished second to last.
I am hearing you – a phrase indicating that one is listening to the other person speaking, but not necessarily understanding or agreeing
* I am hearing you, but I think you’re wrong.
What Insiders Know
Yellow Journalism
“Yellow journalism” is a “disparaging” (derogatory; insulting; expressing disapproval) “term” (word or phrase) for journalism that has little “value” (worth; merit) because it is poorly researched. Yellow journalism “exaggerates” (makes things seem bigger or more important than they actually are) and is “sensational,” meaning that it tries to capture readers’ attention by focusing on “scandals” (shocking behavior that is generally considered to be unacceptable) and “rumors” (statements that are widely shared, but probably not true and certainly unproven).
The term “yellow journalism” was “coined” (first used) in the mid-1890s by the editor of the New York Press, a man named Erwin Wardman. He used the term to describe journalism that was printed in yellow “ink” (the colored liquid used to print marks on paper). But the term “stuck” (continued to be used) even when the ink colors changed. He was “critical” (saying that someone or something is doing something poorly or wrong or) of newspapers that used yellow journalism to “drum up” (increase in number through concentrated efforts) their “circulation” (the number of people who read and subscribe to a particular magazine or newspaper).
Today, people are more likely to use the term “tabloid” than “yellow journalism.” Tabloids are inexpensive newspapers sold at the “checkout stands” (where people pay for their purchases) in grocery stores, with “outlandish” (extreme and difficult to believe) “headlines” (titles of articles) and shocking photographs. The stories have some “basis” (foundation) in reality, but most of them are clear exaggerations “intended” (meant) to generate interest and encourage people to buy the publications.