= 1832
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 527.
This is English as a Second Language Podcast’s English Café episode 527. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode. We got Facebook. Yes, we do. We’ve got Facebook. How about you? Do you have Facebook? If you do, then go to facebook.com/eslpod and like us. That would be so nice. I’m a little weird today, I know. Aren’t I always?
On this Café, we’re going to talk about soccer in the United States. Of course, the rest of the world calls it “football,” but we call it “soccer.” We’re also going to talk about a famous American poet, Robert Frost. And as always, we’ll answer a few of your questions. Let’s get started.
In many countries around the world, the word “football” (or some equivalent of “football”) is used to describe a game where you have two groups or two teams of 11 people trying to kick a little round ball into what is called a “goal” or a “net.” In the U.S., however, the word “football” refers to a very different game – what other people might call “American football” – that has two teams that basically try to hit each other in order to get a ball that is not round but shaped, interestingly enough, like what we would call a “football,” even though you don’t kick it very often in the game of football.
It’s very confusing. I know, I know. But the game that the rest of the world calls “football,” we call “soccer” (soccer). I’m going to talk not about the rules of soccer, because I don’t know the rules of soccer and almost never watch soccer, like most Americans. However, I will talk about the history of soccer because I have heard – it has been told to me – that this is a very popular game in other countries. I’m kidding, of course. It’s also popular here in the U.S., and we’ll find out just how popular right now.
The earliest signs or indications of a game similar to soccer being played in what is now the United States was back during the seventeenth century when the English arrived to North America. It wasn’t exactly the same as modern-day soccer, of course. In the nineteenth century, it was mostly men at American colleges and universities who played a game called “soccer.” At that time, however, schools didn’t play against each other, and so each school sort of developed its own rules for the game.
It was only after the American Civil War in the 1860s that schools began playing each other in this game of soccer. In the 1870s there was an increase in British immigrants arriving to the United States. The immigrants brought their love of this game we call soccer with them, and the sport began to become popular, at least with some Americans. It never became as popular as baseball or American football, but there were college groups in particular who played the game.
In 1884, the American Football Association was created in New Jersey, and this organization began to create what we might describe as a “standard set of rules.” “Standard” (standard) here means agreed upon. “Standard rules” would be rules that everyone follows. The AFA changed its name in 1913 to the United States Football Association, and in 1914 was a member of the international association that governs soccer – FIFA, which many of you will be familiar with.
An “association” (association) is a group or an organization that usually has lots of different members. FIFA is an international organization that “governs” (governs) soccer. “To govern” means to be in charge of something. We call the people who are in charge of a country the “government.” The verb is “to govern.” So, in 1914 the United States became a member of FIFA, or at least the United States Football Association did. Notice, of course, they still called it “football.”
It was also in 1914 that the U.S. had its first “Open Cup.” This was a soccer tournament in which teams from around the United States played each other. A “tournament” is a series of games or competitions to determine who is the best team or the best player. Despite joining FIFA and having tournaments, soccer continued to be unpopular in most places in the United States in comparison to other sports, as I’ve mentioned previously.
The United States Football Association decided to change its name again to the United States Soccer Football Association in order to avoid confusion with the sport most Americans know as football, American football. “Confusion” (confusion) is when you have something that is unclear, and it was perhaps confusing to people to see something called the United States Football Association that had nothing to do with what Americans considered football.
The organization changed its name again in 1974 to simply the U.S. Soccer Federation (federation). There’s really no difference, I don’t think, between a “federation” and an “association” in this case, but you will notice that the word “football” disappeared from the title of the organization. The USSF tried to bring international soccer celebrities to professional teams here in the United States during the 1970s.
In fact, it was during the 1970s that soccer began to become popular as a professional sport here in the U.S. I remember growing up that there was a professional soccer team in my state of Minnesota. In fact, I even remember the name of the team. It was the Minnesota Kicks (kicks) “To kick a ball” is what you do in soccer. You use your foot to move the ball by striking it, by hitting it against the ball.
The Minnesota Kicks was the name of our professional soccer team, and I actually went to several of the Minnesota Kicks games in the old Metropolitan Stadium, which is no longer there in Minnesota. They tore down the stadium. They got rid of the stadium. They removed the stadium that they used to play both baseball and professional soccer in. Instead, they put up a big mall called the Mall of America, which is the largest shopping mall in the world.
So, it was during the 1970s that the United States Soccer Federation tried to get people interested in professional soccer. They even brought in some famous soccer players. In 1975, perhaps the most famous soccer player, the one that Americans will recognize, the Brazilian soccer star Pele agreed to play for a professional soccer team in New York. He actually played two years for that team, the New York Cosmos. In his final game for New York, he played against the Brazilian team he used to play for, apparently called the Santos, and almost 78,000 people went to that game.
In 1982, the United States tried to become the host of the 1986 World Cup games. It “bid” (bid) to host the games. “To bid” means to offer to do something. In this case, it tried to get the international soccer association, FIFA, to have the games hosted here in the U.S. Well, it didn’t work. It did however bid again, and it was successful in hosting the World Cup in 1994.
Some people say that it was the 1994 World Cup that helped make soccer more popular in the U.S. More than three and a half million people went to the different World Cup games in the U.S. And some people say that the U.S. men’s team played the best they had played since 1950 during the World Cup. I don’t really know because I didn’t watch any of the games. However, many millions of people did, and it helped make popular the sport of soccer, at least among some Americans.
Perhaps, the most important event in U.S. soccer history was the 1996 Olympic Games that were held in Atlanta. It was during that time that a U.S. team won a gold medal in soccer – not the men’s team but the women’s team. They won the gold medal, and no doubt that also got people more interested in soccer. Today there is still a professional sports league, or group of teams, in the United States that play soccer. There is something called Major League Soccer, which was created in 1996 for professional soccer teams in the U.S. and Canada.
There are 23 teams in Major League Soccer including teams here in Los Angeles, in New York, in Washington D.C., in Dallas, in Chicago, in Montreal and Toronto, and other cities throughout the United States. Some of these teams have had famous players from other international teams come and play for them, including David Beckham here in Los Angeles.
Now, despite the fact that there is a professional sports league of soccer teams in the U.S. and even though millions of people go to those games, I’ve said repeatedly that soccer is not that popular compared to other professional sports, and that’s still true. However, soccer is very professional among children and teenagers. There are millions of young people who play amateur soccer. Many of my nieces and nephews, for example, played soccer when they were growing up. In fact, I had one nephew who I think got a scholarship or played on a soccer team when he was in college.
Soccer is incredibly popular among younger people. In fact, in 2014 I think there were more than three million American children playing soccer. So, although soccer is not as popular as other professional sports, soccer is a very popular sport among children and teenagers at what we would call the “amateur level” – that is, they don’t get paid, of course, to play soccer.
The population of the United States has changed, and there are many immigrants who have come from countries where soccer is popular, especially places such as Latin America, and that has made professional soccer more popular. It’s impossible here in Los Angeles to drive by a public park and not see a group of usually men, Latino men, playing soccer, although soccer is popular also among those who are not Hispanic or Latino.
No doubt the immigrant population to the United States will help make soccer even more popular in the future. It might become so popular that even I will go and watch a game of soccer. If I do, I’ll let you know.
Now let’s turn to our second topic, the American poet Robert Frost. Robert Frost was born in 1874, right here in California – in San Francisco, California. Remember, in the late nineteenth century, San Francisco was a major city in the United States, while Los Angeles was really just a small town at that time. Robert Frost and his sister grew up, however, not in San Francisco but in Massachusetts, which is a state on the other side of the country, on what we call the East Coast of the United States. Frost’s father died when he was young. He died in 1885 when Frost was only 11 years old.
Frost began writing poetry when he was in high school. He continued to write when he went to college. He went to a private college called Dartmouth, located in the state next to Massachusetts called New Hampshire. Dartmouth is considered one of the better colleges in the United States. Frost published his first poem when he was only 20 years old, in 1894. It was called “My Butterfly: An Elegy.” An “elegy” (elegy) is a long, sad poem. Frost wasn’t very interested in school, however, and he dropped out of, or he left, Dartmouth after only one year.
He got married in 1895 to his girlfriend from high school, Elinor White. The two of them had six children together, but only four of those lived to be adults. Frost needed money and so he taught at a school. He even tried to become a farmer in order to earn money, but he wasn’t really interested in teaching or farming. His only real interest was in being a poet. Unfortunately, he didn’t have a lot of financial success at that, at least at first.
Finally, in 1912, Frost and his family sold everything they had and they moved – not to San Francisco, not to California, but to London, England. Yes, they moved out of the country completely. Why? Well, they had heard that it was easier to get published in England. “To publish” (publish) usually means to put something in a magazine or in a book for other people to buy. You could also publish a newspaper, or we now on the Internet talk about publishing “content,” such as blog posts.
Luckily for Frost, he was right. It was in fact easier for him to publish his poetry in England, and in 1913 he did in fact publish a collection of his poems in Great Britain. A “collection” here refers to a group of things, of similar things. The collection of poems that Frost published was called A Boy’s Will (will). “Will” here I think probably means the desires, the things that a boy wants to do. Frost published his second collection of poems the next year, in 1914.
Frost’s poems weren’t about England, however. They were about his life, especially his early life in the area of the country where he grew up called New England. New England is the northeastern part of the United States – the states of Massachusetts, Rhode Island, Vermont, New Hampshire, and Maine. Most of the areas in these states were at that time farmland. They were very “rural,” we might say. “Rural” (rural) means basically country – outside of the city.
Remember, the reason Frost went to England was because it was easier to get his poems published there. Well, fortunately for Frost, an American woman by the name of Amy Lowell happened to be visiting, travelling in England in 1915 and saw Frost’s book. She bought it. She read the poems. She loved them so much that she decided that she was going to get them published back in the U.S. In 1915 she was successful in getting Frost’s collection North of Boston published. She also got Frost’s other collection, A Boy’s Will, published in the U.S.
Frost’s poems became very popular after they were published here. In 1915, Frost and his family returned to the United States. World War I had, of course, already begun in Europe. Frost decided to come back to the U.S., and it was only then he learned just how popular his poems were. In fact, in just a very short period of time, Frost became one of the most famous poets in the U.S.
Over the next 40 years, Frost continued to write poetry about life in New England. He published many more collections of his poems. In 1923, he published New Hampshire. In 1930, he published a book called Collected Poems. More books followed and many of Frost’s books won what’s called the Pulitzer Prize. The Pulitzer Prize is an award given for the best writing, among other things, in the U.S., including poetry.
Frost’s poetry became so popular that American schoolchildren began to read his poems as part of their school assignments. I remember my father, who grew up in the 1920s and ’30s, remembered some of the poetry that he read of Frost’s that he was taught when he was in school. Even to this day, Robert Frost is probably one of the few American poets that most Americans probably recognize even if they haven’t read any of his poetry.
One of the most famous events in Frost’s life came at the very end of his life, when the newly elected President John Fitzgerald Kennedy asked Frost to read a poem at what is called the “inauguration ceremony.” When the U.S. president begins his four years in office, he has to take what’s called an “oath” (oath). An “oath” is just a promise to do what the president is supposed to do.
During the inauguration, it’s traditional for the president to give a speech. John F. Kennedy’s speech became quite famous. Some presidents, especially more recently, ask a famous poet to come and read a poem at their inauguration. Often the poet writes an original poem for the president. That was the case with Robert Frost. He wrote a poem for President Kennedy.
However, when he got to the inauguration ceremony, which takes place in January in Washington, D.C., it was very cold and he couldn’t read the poem that he had written for Kennedy. So instead he simply recited, or said from memory, another poem that he had written. It didn’t matter, of course. The important thing was that the entire country saw what was then the greatest living poet.
Robert Frost died a few years later in Boston, in January of 1963. He had a blood clot in his lung. A “blood clot” is when you have a certain amount of your blood that sticks together, I guess you could say, and doesn’t allow other blood to flow through the body. Even though he did not become a successful poet until the middle of his life, he did become perhaps the most well-loved poet of the twentieth century in the U.S. His poems continue to be read today.
Now let’s answer a few of your questions.
Our first question comes from Daya (Daya) in India. The question has to do with the difference between two verbs, “to suck” and “to lick.” “To suck” usually means to pull liquid into your mouth, or perhaps air. Usually it is done by forming a small O with your mouth, with your lips. “To lick” means to put your tongue on the surface of something, usually a piece of food. If you are eating ice cream, especially ice cream that is served in what’s called a “cone” (cone), which is a small container, you eat it by licking it – by putting your tongue on the ice cream in order to get it into your mouth.
“Sucking” would be related, for example, to, say, a “straw.” A “straw” (straw) is a long piece of usually plastic that goes into soda or water so that you can get the liquid out of the glass without putting it to your lips. You instead put your lips around the straw and you suck the liquid out of the glass. There’s an idiomatic expression, an informal one, “that sucks.” In that case, “that sucks” means that’s terrible, that’s a horrible thing. It’s an informal expression, but it has become more common in American English in the last 20, 30 years or so. You may hear someone say, “Oh, I got an F on my exam. That sucks.”
For some of us who are a little older, the expression still seems a little bit vulgar, but I guess it’s become common enough nowadays that when people say something “sucks,” you interpret it simply to mean that it is very bad, or that something very bad has happened. The reason I say that some of us who are a little older still are a little uncomfortable with the expression is because we know that it comes from a vulgar sexually related expression that we won’t bother explaining here.
Our next question comes from Juan (Juan) Angel (Angel) in Spain. Juan Angel wants to know the meaning of the expression “left to one’s own devices.” “To be left to your own devices” means to be let to do whatever you want to do without anyone helping you or controlling you. Normally when you say this about someone else – “I’m going to leave him to his own devices” – you mean you’re going to let him do what he wants to do, how he wants to do it, but there’s also the idea that you don’t really care whether this person succeeds or not, whether he is successful in doing whatever it is he’s doing.
It’s sometimes used in situations where you are pointing out that if someone doesn’t have supervision or isn’t helped, he might do something wrong or might waste his time. Children “left to their own devices” will spend all day watching television rather than doing their homework. Instead of doing something good, or at least what people think is good for them, the children will do something else. “Left to their own devices” – if no one is helping them or supervising them or controlling them.
Finally, Sherrie (Sherrie) from an unknown country wants to know the meaning of a couple of different expressions. The first one is “someone to,” as in, “She is not a teacher you want to cross.” Well, “to cross” here would mean to oppose or somehow get in a person’s way, usually in such a way that would make that person angry. If someone says, “She’s not a person to cross,” he means that you don’t want to get in this person’s way. You don’t want to be an enemy of this person, probably because this person might be able to do something bad to you or this might be a mean person.
The second expression Sherrie wants to know about is “to give a talking-to” someone. “To give a talking-to” someone means to yell at someone or discipline someone or criticize someone. It’s usually something a teacher would do with a student or a parent with his child. “I’m going to give him a talking-to.”
There’s also an idea that this might be a long criticism, or a long “lecture,” we might say, from a parent to his child or from a teacher to her student. If you do something wrong and your mother isn’t happy about it, she may “give you a talking-to.” She may take you into the other room and yell at you for ten minutes and explain to you why you were wrong to do what you did.
In my house, it was usually my father who gave me the talking-to. My father worked two jobs when I was growing up in order to pay for the food for our family, so he would get home at night – maybe nine o’clock at night – and as was heard in so many houses (at least back in the time I grew up) a mother, if a child did something wrong, would say, “Wait till your father gets home,” meaning your father will discipline you and yell at you for what you’re doing wrong when he comes home from work, when he gets back.
In fact, I think there was even a television show called Wait Till Your Father Gets Home. I remember that show growing up. I even remember the song. I have this thing – I can like remember songs from TV shows from 30 years ago. I know, it’s crazy. Something like:
Wait till your father gets (wait till your father gets . . .)
Wait till your father gets home.
That was close. Anyway, that would be a “talking-to.” This is usually spelled (talking-to). It’s all one word. It’s a noun, not a verb – “a talking-to” – even though there’s a gerund and a preposition that form this somewhat unusual word.
If you have an unusual question, or even a usual question, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
standard – an agreed upon level, set of requirements, or rules
* All of the singers working as entertainers for our company know a standard set of songs, which customers can request.
association – a group or organization that consists of individuals or groups as members
* One of the common benefits of being a member of automobile associations is getting discounted prices for hotel rooms and rental cars.
to govern – to be in charge of something, having authority over rules and decisions
* The president had governed the country for eight years when he decided to retire from pubic life.
tournament – a series of games where players or teams compete for a prize
* March Madness is a basketball tournament where 64 college basketball teams play each other to win the basketball championship.
confusion – not understanding something well and being unclear about its meaning
* The poor weather conditions caused a lot of confusion among airline passengers who weren’t sure if their flights were going to take off on time.
to bid – to offer to do something for a certain price, usually a specific job or project
* David got three bids from plumbers to repair the broken pipe in his kitchen and gave the job to the plumber who said she could fix it the fastest.
elegy – a long, serious poem, usually to remember or honor the dead
* When his wife died, the poet wrote an elegy about all the things she used to do that he now missed every day.
to publish – to create something, usually in print, for others to read, see, or use, such as a book, newspaper, or printed music
* After her book was published, Anna went on a book tour around the country.
collection – a group of similar items
* Dmitri had a collection of coins from all of the countries that he had visited on his travels.
New England – the area in the northeastern part of the United States that consists of the states of Massachusetts, Rhode Island, Vermont, New Hampshire, and Maine
* Fall is a beautiful time to visit New England because the leaves on the trees turn beautiful colors such as red, orange, and yellow.
rural – the countryside, with fields or farms, not a town or city
* Sandrine loved living in a rural area with lots of trees, fields, and wild animals.
blood clot – a thick amount of blood that sticks together making it impossible for blood to flow around the body properly
* It is important when sitting on an airplane or in a car for many hours to get up and walk around to avoid getting blood clots in your legs.
to suck – to pull liquid, air, or something similar into one’s mouth, especially while one’s lips are forming a small hole
* The little boy sucked soda out of his straw too quickly, spilling it on his shirt.
to lick – to pass one’s tongue over a surface or an object
* Lick the ice cream on the other side of your cone before it drips on your hand.
to leave (someone) to his/her own devices – to let someone do what he or she wants without helping them or trying to control them
* Michael seemed confident that he could figure out how to assemble his new toy, so I left him to his own devices.
to cross (someone) – to betray someone; to cheat someone; to not follow or agree to someone else’s plans and cause trouble for them as a result
* Nobody dares to cross Cassandra because she has a terrible temper.
talking-to – a scolding; the act of expressing criticism and disapproval for something someone else has done
* Grandma gave Paco a talking-to after he threw rocks at the neighbor’s cat.
What Insiders Know
Poetry Slams
In November of 1984, an American poet named Marc Smith started a competition for poets in Chicago. This competition was later called a “poetry slam,” where poets compete with each other by reading or “reciting” (saying something from memory) original poetry. The first “national” (relating to the entire country) poetry slam was held in 1990 in Fort Mason, San Francisco. That competition had only three teams. As of 2014, 72 “certified” (official; recognized) teams competed over five days.
Some poetry slams asks the entire audience to “judge” (evaluate) the performances. In other competitions, before the poetry slam begins, the host chooses from members of the audience three to five people to act as “judges” (evaluators; people making a final decision) for the poetry slam. Each judge “scores” (evaluates using numbers) a poet after each performance.
The most common type of poetry slam is called an “open slam.” Open slams allow anyone to compete to fill the available “slots” (number of positions). “Invitation slams,” where only invited competitors can compete are also quite common. Another type, called a “theme slam,” requires performances based on a specified theme or genre. Finally, a “dead poet slam” requires competitors to use the poetry only of “deceased” (dead) poets.
While poetry slams have become popular all over the world, some are “critical” (have a negative opinion) of them. Some say that poetry slams are similar to television singing competition shows like American Idol. Others think that poetry slams have become more of a sport than an “art form” (product of art).