= 1825
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café episode 520.
This is English as a Second Language Podcast’s English Café episode 520. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also take a look at our ESL Podcast Store, which has additional courses in Business and Daily English. And why not like us on Facebook? Go to facebook.com/eslpod.
On this Café, we’re going to talk about a man whose name is famous here in Los Angeles, even though most people don’t know much about his life. I’m referring to Henry Gaylord Wilshire, for whom Wilshire Boulevard here in Los Angeles is named. We’re also going to talk about a famous building in New York City called the Flatiron Building. And as always, we’ll answer a few of your questions. Let’s get started.
Henry Gaylord Wilshire, better known as Gaylord Wilshire, is remembered today mostly because one of the most important streets here in Los Angeles is named after him. But when he was alive, he was best known as perhaps one of the most unusual businessmen of his generation. He was not only a businessman, he was a political activist. An “activist” (activist) is someone who tries to accomplish some political goal or to get people to recognize certain social problems. A “political activist” typically will try to get people to agree with his political beliefs or ideas.
Wilshire’s interest in politics began very early in his life, long before he arrived here in Los Angeles. So, let’s go back a little. Let’s start with his birth, which was in June of 1861 in the city of Cincinnati, Ohio. Ohio is located in the central eastern part of the United States. The city of Cincinnati is about 480 kilometers southeast of the city of Chicago. Gaylord Wilshire’s father was a very wealthy businessman, a man with a lot of money. So, Wilshire was raised in a home with a lot of money.
He was sent to the finest university in the United States at that time, Harvard University. However, he only stayed for about a year. He left Harvard in 1879 and he read a book by a very popular author at that time by the name of Henry George. The book was called “Progress and Poverty.” “Progress” relates to moving forward – in this case, improving the world. “Poverty” (poverty) relates to not having money. Henry George’s idea in the book that Wilshire read was that there were so many poor people in this country because a very small group of rich people controlled all of the money.
Well, in some ways that’s almost obvious. If you have poor people, they don’t have money. That’s why they are poor. But Henry George’s idea was that the reason the poor were poor was because this small group of people were keeping the money all for themselves. The book offered some solutions to the problem, solutions which nowadays we would call “socialism.” “Socialism” (socialism) is a political and economic idea that is related to making sure that the riches in a society are distributed equally.
Now, it’s much more than that, but I don’t want to give a lecture on political science and economics. The general idea of socialism, at least as Wilshire understood it, was the idea that everyone would be owners in the society, in the economy of the society, in such a way that there wouldn’t be any poor people, that everyone would have a more equal share of the money.
After reading Henry George’s book, Wilshire became very involved in the local socialist organization in Cincinnati. In fact, he later became president of this organization. Now, you have to understand that Wilshire himself was a wealthy man, a man with a lot of money, but it was not unusual – then nor now – for certain rich people to get interested in what we would consider liberal or left-wing political ideas, including socialism.
In the early 1880s, Gaylord Wilshire and his brother William decided, as many did during this period, to move to the West Coast, to go in this case to San Francisco. The two brothers started a “safe” (safe) business. A “safe” is a strong box or place – could be a room, even – where you keep things that are valuable. Well, the safe business wasn’t going very well for the Wilshire brothers. However, one day Wilshire was out riding his horse with the daughter of a very important lawyer and businessman in San Francisco.
At one point, the horse that the daughter of the rich businessman was riding on started to run wild, and Wilshire went and stopped the horse and was able to save the woman from further harm. However, during this act of saving the young woman, the horse kicked Wilshire in the face. Well, it’s not really funny. He had a six-inch scar as a result of this kick. A “scar” (scar) is a mark left on the skin where there was a cut or injury.
However, the family of this young woman was so grateful, so appreciative of what Gaylord Wilshire had done in saving the life of this young woman, that they began to give the brothers all of their business and recommend their company to all of their friends, and eventually this company started to make a profit – that is, they started to make money.
In 1884, the brothers moved to Los Angeles, which at the time was really just a small town. It only had about 11,000 people in it. The Wilshire brothers started buying up land because land was cheap in Los Angeles during the late nineteenth century. When I say it’s “cheap” (cheap), I mean it was inexpensive. It didn’t cost very much.
Wilshire bought land outside of the downtown area of Los Angeles, a place where not very many people, if any, were living at the time. He knew, however, that Los Angeles would grow and that eventually this land would be worth a lot of money. But it wasn’t worth a lot of money when he bought it, so he decided, along with his brother, to travel around California looking for other business opportunities.
In 1889, he met and married a woman named Hannah Owen, who was also a socialist. In the following year, in 1890, Wilshire’s father – who you’ll remember was also a wealthy man – died, and eventually Wilshire inherited about $200,000, which would be in today’s money probably something close to five million dollars. Although Wilshire was a socialist, that didn’t mean, as it usually doesn’t, that he gave his money away to poor people.
Instead, he lived a very expensive lifestyle. A “lifestyle” (lifestyle) is the way a person lives, how he spends his money, what kinds of activities he does. As I say, even though he was a socialist and believed everyone should be equal, he didn’t want to start with his own money. This began to cause some problems between Wilshire and his wife, who was a bit more ardent in her socialism. “Ardent” (ardent) means passionate, having very strong feelings about something.
However, around the same time, Wilshire was asked to run for a political office, for Congress, as a member of the Socialist Labor Party. He lost that election, however, and decided that he would move and leave the city of Los Angeles and go to London, England. Now, interestingly enough, when he was in England, he tried to become a member of the English Parliament. He ran for a seat in the English Parliament. Once again, he was not successful. Although I imagine he’s one of the few people who have run for both Congress and Parliament. That alone is sort of an amazing thing.
At this point, Wilshire and his wife divorced, and in 1895, Wilshire returned here to Los Angeles. By this time, there were 50,000 people living in Los Angeles and after buying an additional piece of property, Wilshire decided he would develop his land, including putting a road through it. He told the city that he would give them the land for the road as long as they named it after him. The road eventually became Wilshire Boulevard, a very wide road for that time.
The area where Wilshire owned land, east of the downtown area, became a very popular one during this period. People were building houses in this area. They wanted to live in this area, and of course Wilshire made a lot of money building huge homes there. Wilshire also started another business, a billboard business. A “billboard” (billboard) is a very large sign that you usually find next to a road or a highway. It’s basically a big advertisement. The people who lived on Wilshire Boulevard hated these billboards, but they made Wilshire a very rich man.
He was also considered one of the most educated and well-read businessmen of his day. He was friends with people like Upton Sinclair, the American writer, and the British author and playwright George Bernard Shaw. In addition to his businesses, Wilshire also took time to start socialist newspapers and magazines. He started a socialist newspaper called The Nationalist and used it as a way of having a public argument with people with whom he disagreed. An “argument” is a strong disagreement between two or more people.
One of the people Wilshire argued with was a famous politician during this period, William Jennings Bryan, who was running for president in 1900. Wilshire decided to change the name of his newspaper to The Challenge, and finally a year later, he renamed it again to – well, what else? – Wilshire’s Magazine. Wilshire wanted the magazine to be popular, especially among those who were poor.
So once again he left Los Angeles and moved to Canada. Why Canada? Well, it turns out it was easier for him to mail out his magazine from Canada, but he didn’t make any money off of this periodical, this publication, and eventually he had to stop publishing the magazine. In 1904 Wilshire married again, to a woman by the name of Mary McReynolds, and they had a son, Lucas, in 1907.
Wilshire tried to start a new business, this time in gold mining. But unfortunately, he wasn’t very successful. “Gold mining” is when you dig in the ground trying to find that valuable yellow metal called “gold.” By 1916, he had almost no money left and he began to have health problems. But because Wilshire was one of the more creative people of his generation, he invented his own treatment for the illnesses that he had. It was a special belt that had electricity in it.
Now, during this period in the late nineteenth and early twentieth centuries, there were a lot of people selling things that they said would make you feel better or cure you of diseases, and that was the case for Wilshire’s electric belt. He did make some money on it, but not enough. He eventually died in 1927 with very little money, even though he had once been one of the richest men in Los Angeles. So, that’s the somewhat odd story of the man who is known today only by the boulevard that bears his name that goes from downtown Los Angeles to the Pacific Ocean – Wilshire Boulevard.
Now let’s turn to our second topic, which is the Flatiron Building. The Flatiron Building is in New York City and is famous mostly for its shape. Unlike most buildings, which are square or rectangular – having four sides – the Flatiron Building is in the shape of a triangle. Why a triangle? Well, here’s why.
There’s an area in New York City where there are three streets, but two of them cross not at a 90-degree angle, which is what you normally have in most city streets, but they cross and form two sides of a triangle. Then there’s a third street that goes in the back, so you have basically a triangular space. So if you want to build a building there, it’s going to have to be in the shape of a triangle – a three-sided building.
An architect by the name of Burnham, from Chicago, designed and built the building, which opened in 1902. When it was being designed, many people called it “Burnham’s Folly.” “Folly” is something, usually a plan or a project, that people consider silly or ridiculous, something that will fail. Earlier in our history, there was something called “Seward’s Folly.” This was referring to the purchase of land from Russia that became later the state of Alaska. Burnham’s Folly was the Flatiron triangular-shaped building.
The building at the time was one of the tallest in New York City, at 21 stories high. Some people even thought the building would fall down, that you couldn’t build a triangular building, which of course is a little silly. Of course you can, and that’s what Burnham did. Although people laughed originally at the idea of this building, it eventually became what we would call a “landmark” building in New York. A “landmark” (landmark) is an object or a building that is well known and recognized.
Anyone who’s been to New York City and has traveled around the city knows about the Flatiron Building. It’s a landmark the way the Statue of Liberty is a landmark in New York City or the Hollywood sign here in Los Angeles is a landmark. It’s a building or a structure that everyone recognizes, and in many ways is identified with a certain place.
You might wonder why this triangular building was called the Flatiron Building. Well, an “iron” (iron) is something you use to make your clothing – your shirts and your pants and your ties and your dresses – flat, so they don’t have what we call “wrinkles.” “Wrinkles” (wrinkles) is what you get when your shirt is not completely flat. It’s also what you get on your face as you grow older. Your skin isn’t smooth and flat anymore. It has wrinkles in it – unless of course you live here in Los Angeles, and then miraculously, magically, your wrinkles disappear. It’s amazing.
Anyway, an iron has to be hot if it’s going to flatten out your clothes and get rid of the wrinkles. A “flatiron” heated, then, is what you use to take the wrinkles out of your clothing. Nowadays, of course, we have electric irons, but the piece of metal that you use to iron is still a flat one, of course. It has to be. Well, some people thought the building looked like a Flatiron, and so that’s the name it was given, and to this day it’s still called the Flatiron Building, and the area around it in New York City is called the Flatiron District.
The building was an office building for many years and continues to be an office building. It wasn’t until the 1990s that the area around the Flatiron Building became what we might call “trendy.” “Trendy” (trendy) means fashionable – something that everyone wants to do or be associated with. In the 1990s, several new expensive restaurants and stores started moving into the Flatiron District. Today you can visit the building and look at it from the outside and go to some of the expensive restaurants in that area.
You might have seen pictures, photographs of the Flatiron Building. That’s because some of the earliest photographers in the twentieth century, such as Edward Steichen and Alfred Stieglitz, took pictures of the building and made it famous. It continues to be popular now, more than a hundred years after it was built, and is still a New York City landmark.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Imran (Imran) from a mystery country that I’ll call the “Alpha Bravo Charlie” country. Imran wants to know the meanings of a couple of different pairs of words. The first two are “regime” and “regimen.” The second pair is “laugh” and “laughter.”
Let’s start with “regime” (regime). “Regime” usually is a word we use to describe a kind of, or form of, government that is very strict and authoritarian – a government that doesn’t allow freedoms for its people. It’s usually a negative way of describing a country’s government. If you say it’s a “regime,” you mean it’s probably not a democratically elected government, a government that doesn’t allow its own people a lot of freedoms.
Although it has a similar spelling, “regimen” (regimen) is a completely different word. “Regimen” refers to a plan, either of making you healthy by eating certain kinds of food, doing certain kinds of exercise and other activities, or a recommended plan or course of medical treatment – things that you do or drugs that you take to make you healthy.
“Laugh” (laugh) can be both a noun and a verb. As a verb, “to laugh” means to make a certain sound and often have a certain expression on your face indicating that you are happy or that you find something funny. “The girl laughed at all of her boyfriends jokes.” That of course is what all men want – women to laugh at their jokes, right?
As a noun, “laugh” can refer to a couple of different things. It could mean the particular sound that someone made. It’s when they’re laughing. “I like his laugh” – “I like the way he laughs,” that’s what you’re saying. A “laugh” could also mean something that is funny, something that is entertaining (although this usage of “laugh” is probably more common in British English than American English).
“Laughter” (laughter) can also refer to the emotion, including the sounds and physical expressions one makes when one is happy or finds something funny. So what’s the difference? Well, I would say generally, in American English, we would use “laughter” for a situation in which there were lots of people laughing. “There was laughter at the party.” That means that several people were laughing at the party. They were happy. You probably wouldn’t say, “Oh, I like his laughter” to describe someone’s individual way of laughing.
“Laughter” usually refers to a situation in which usually more than one person is laughing, is engaged in laughing. If you look at up in the dictionary, “laughter” usually is defined simply as “the sound or action of laughing.” But I think, at least when I hear “laughter,” I usually think of more than one person, or a situation in which people are laughing, though other people might have different ideas about that.
Finally, Andi (Andi) in Russia wants to know the difference between two verbs, “to unveil” and “to reveal.” Let’s start with the second word, “to reveal” (reveal) since it’s the more general of the two words. “To reveal” simply means to take something that was secret or something that you couldn’t see, something that was hidden, and make it public – allow people to know about it or to see it. You could reveal someone’s secret, some secret information that was told to you. You could reveal it to another person.
On television now, there are several popular shows in which people go and fix up a house. They redecorate the house or they put new furniture in the house, and the whole show is about how they go about doing it. At the end of the show, they have what is sometimes called “the reveal,” using “reveal” as a noun. It’s the point during the television show when you get to see the final result, when they show you how things turned out. In general, though, “to reveal” as a verb means to let people see something or know about something that was either secret or hidden.
I should also mention there’s an adjective, “revealing” with an (ing) at the end. If someone is wearing “revealing clothing,” usually that means the person, often a woman, is wearing clothes that show a lot of her skin. “That’s a very revealing dress,” you might say about someone who you can see, well, a little bit more than what you could normally when a woman wears a dress. So “revealing clothing” is clothing that shows more of your body – that, if you will, exposes, or lets people see, things that usually are hidden.
The second word that Andy asks about is “unveil” (unveil). To understand the meaning of “unveil,” let’s talk about the meaning of “to veil” (veil). “To veil” means to cover something, usually a piece of furniture. It could be a painting. It could be a statue. It could be something, anything, any object that you don’t want someone to see. So, the opposite of veiling something, would be to “unveil” it.
Usually we use this verb when, for example, a museum has purchased perhaps a new painting, or an artist has painted something new and everyone goes to a party and the picture is covered. It’s veiled in a sheet or some sort of covering which is then taken off. Well, taking off that covering is “unveiling” the picture, or the sculpture, or whatever it is.
The verb can also be used when, for example, a political candidate – someone running for a governmental office – gives people their new plan, the way they’re going to solve problems. A politician might say, “I’m unveiling my new plan to give everyone a better job,” or whatever it is that the person is promising. And of course politicians promise everything, so they have plans for all sorts of things. They just don’t have ways of actually carrying out their plans.
So, “to unveil” is a kind of revealing – it’s a special case, you could say, of revealing. “To reveal,” however, can be used in a lot more circumstances and is used more generally than the verb “to unveil,” which tends to be used either literally, as in, “The museum is unveiling the painter’s new painting,” or in a more metaphorical way when, for example, a politician “unveils” their new plan for something.
Let’s see, we have time actually for one more question. So let’s take a question from Nermin (Nermin), also in Russia. Nermin wants to know the meaning of the two-word phrasal verb “to light (light) up.” What does it mean “to light up”? There are a couple of different ways to use this phrasal verb. One would refer to someone who is smoking. Someone may say to you, “Don’t light up your cigarette in here. We don’t allow smoking.” “To light up” can mean to light a cigarette, whatever kind of cigarette it is you smoke.
“To light up” can also mean literally that something begins to give off light. For example, if you are having a brain scan – if the doctors are looking at your brain activity – the scan, the equipment for the scan, may indicate that there is certain activity in your brain by having certain parts of the screen you are looking at light up. Or you could have a phone that has several different phone lines that come into it, and as someone calls each number, there’s a little light that, well, lights up – that suddenly turns on and starts emitting light. That could also be a use of the phrasal verb “to light up.”
Finally, “to light up” could also refer to a person who suddenly becomes interested in something or excited about something. “When I tell her about the money that I won, her face lights up.” She suddenly becomes interested in me because she knows I have all this money. Well, I’m not interested in her.
If you have a question, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
political activist – a person who works to raise awareness of a specific political belief or opinion
* Some political activists have tried to raise awareness through peaceful methods, while others have used violence to get people’s attention.
socialism – the political and economic idea that the systems for making things, distributing them, and trading them should be owned by everyone in society
* Because he was a believer of socialism, Yuri made all his employees equal owners in the company and paid each person the same amount of money.
scar – a mark left on the skin where a cut or injury had been
* Mary had a large scar on her leg from knee surgery.
profit – in business, the amount of money that remains after expenses have been paid
* Early sales indicate that the company will make a huge profit this year.
cheap – inexpensive; not costing much money
* Annika regretted wearing cheap running shoes when they fell apart only after a month.
lifestyle – how a person lives, including how they spend money and what kinds of activities they do
* Although he enjoyed visiting the country, Matt missed his city lifestyle of walking everywhere and having lots of shops, restaurants, and museums close by.
ardent – passionate; having very strong feelings about something
* The politician was an ardent supporter of equal pay for women in the workplace and promised to pass laws to make it happen.
billboard – a very large sign next to a large road or highway with advertisements
* As they got close to the city, they saw billboards on the side of the road advertising city attractions, such as the zoo and the museums.
argument – a strong disagreement between two or more people
* Gui and Sabrina had the same argument every time they traveled about who will drive.
folly – a plan or project that is very silly or ridiculous, and likely to fail
* Many of the largest and most important projects in history were thought to be follies at the time they were built.
landmark – an object or building that is well-known and easily noticed from a long distance away
* On their hike, they used different trees and rocks as major landmarks.
trendy – fashionable; in style; popular with many people
* Sandrine owned a clothing store and knew from experience that just because a type of clothing was trendy didn’t mean that it looked good on everyone.
regime – a form of government, especially one that is strict in enforcing the government’s authority at the expense of personal freedom
* The military regime in this country will not allow any public protests to occur.
regimen – a plan or set of rules about food, exercise, and other health related matters, to help someone become or stay healthy; a recommended course of medical treatment
* Our new diet regimen includes a lot of fresh fruits and vegetables.
laugh – the sudden sound and movement of the face that one makes when showing happy emotion, often with sounds similar to “ha ha”
* It is good to hear Melinda laugh after the bad week she’s had.
laughter – the action or sound one makes when one shows happy emotion, often with sounds similar to “ha ha”
* Jaime fell on the floor with laughter when he heard the joke.
to unveil – to show or reveal something to others for the first time; to remove a cover from something so that people can see it
* When will the artist’s new painting be unveiled?
to reveal – to make something that was secret or hidden public or generally known
* The police investigators finally revealed that they had lost critical evidence in the case.
to light up – to become interested and responsive in something; to show activity
* The children’s faces lit up when the clown came into the room.
What Insiders Know
The Phrase “23 Skidoo”
The phrase “23 skiddoo” is an American “slang” (informal language) expression. The expression generally refers to leaving someplace quickly or being forced by someone to leave quickly. It can also refer to taking advantage of an opportunity to leave.
The phrase “23 skiddoo” became popular in the 1920s, and it became a “fad” (popular for a short time) for people to use it in daily conversation. While there are several stories and explanations that suggest where the phrase “originated” (how it started; where came from), the most “credited” (given attention because it is likely correct) explanation of its origin is “tied to” (related to) the Flatiron Building in New York City.
The Flatiron Building has a triangular shape and because of this shape, winds “swirl” (move in a twisting or spiraling pattern) around the building. During the early 1900s, groups of men would gather to watch women walking around the Flatiron Building because the winds would blow their skirts up, showing their legs, which were “seldom” (not often) seen or “exposed” (visible) in clothing at that time. Local policemen would tell these groups of men to leave the area, and this action became known as giving the “23 skiddoo.”
Today, this phrase is not very often used and if an American uses it, it’s usually for comic reasons or to sound old-fashioned. Occasionally, you’ll still hear people say something like, “Hey, kids, skiddoo or I’ll tell your parents you’ve been getting in trouble.” Almost never will you hear “23 skiddoo” anymore in daily conversation.