= 1855
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 550.
This is English as a Second Language Podcast’s English Café episode 550. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode that contains a complete transcript of every word I say, as well as a complete list of vocabulary words, definitions, sample sentences, and much more.
On this Café, we’re going to talk about Casey Jones and his amazing and courageous story. We’re also going to talk about a famous television show from the 1970s, Happy Days. And as always, we’ll answer a few of your questions. Let’s get started.
Casey Jones was born in March of 1864 in the state of Missouri, which is located in the central part of the United States. The name he was given when he was born was John Luther Jones, but he started using the nickname “Casey” when his family moved to a town named Cayce, in the state of Kentucky, when he was just a boy. A “nickname” (nickname) is a short or informal name that people use instead of their real name.
Casey loved trains from the time he was a boy. Many young boys do. When he was 15 years old, he got a job working for the Mobile and Ohio Railroad Company. “Railroad” (railroad) is a term that refers to the entire system of “train tracks,” or metal lines and the trains that travel on them.
In his first job, Casey was what was called a “telegraph officer.” “Telegraphs” (telegraphs) were messages that, until somewhat recently, used to be sent over wires using electrical connections. That’s how people were able to communicate over long distances back in the nineteenth century before there were telephones and emails and texting. Working for the telegraph service of the railroad was one of Casey’s first jobs.
In 1884, he moved to Jackson, Mississippi, located in the southern part of the U.S., and he was promoted. He was given a better job, to the position of “flagman.” A “flagman” (flagman) is a person who sends signals or messages using a flag on a railroad line. The flagmen had very important jobs because of course you need to make sure the train is on the right track, the right set of metal lines, especially when they’re coming in and out of a railroad station.
While living in Jackson, Casey met a woman named Joanne Brady, and the two of them got married in 1886, eventually having three children together. Casey was a hard worker and he got better jobs within the railroad company quite quickly. By 1891, he took a job as an engineer with another railroad company called the Illinois Central. An “engineer” (engineer) is, in this case, the person who actually drives or controls the train.
We use the word “engineer” nowadays, however, to refer to someone who has knowledge of certain scientific areas and is able to use that knowledge to make, design, or create things. You can think, for example, of an electrical engineer – someone who designs electrical systems in a house or a building – or perhaps a mechanical engineer, someone who designs machines.
Well, when we’re talking about “railroads,” the engineer is really the driver of the train. Now, one of the things you want from an engineer of a train is a person who is going to get the train to arrive at the time it is scheduled to arrive. This is still a problem in our trains today, as many of you know.
Casey had a reputation. He had the fame of being a very good engineer – someone who would always make sure that the train would arrive on time. To do this, however, he often had to drive his train very, very fast. As he drove through the towns as trains often do, he would blow the whistle of his train to make sure that anyone who was near the train tracks would move away. A “whistle” (whistle) is an object that makes a clear, high-pitched sound. This is an example of a “whistle” sound. Of course, the whistle on a train is much louder and much easier to hear.
Now, you might be thinking to yourself, “None of this is unusual. Train engineers always use whistles and there are lots of good engineers and have been throughout the history of railroads. So what is so special about Casey Jones?” Well, on April 30th, 1900, Casey offered to work an extra shift as an engineer to help out a train engineer who was sick that day.
A “shift” (shift) is a period of time or a number of hours that you are scheduled to work each day. This is especially true in jobs that are paid by the hour, where you work a definite number of hours each day. Most people work a day shift. They work during the day – from, say, eight in the morning till five in the afternoon.
There are some kinds of jobs where you need someone to work the entire 24-hour period, or at least to have someone working the entire 24-hour period. And so, those jobs are typically split up into three different shifts: the first shift, the second shift, the third shift – the third shift being the one that would have to work overnight during the time that most of us are sleeping. We usually call that the “graveyard shift.” A “graveyard” is the same as a cemetery, where dead bodies are buried.
On April 30th, 1900, Casey Jones offered to work an extra shift for a sick “colleague” – someone he worked with. Unfortunately, the train that he was driving was very late, almost an hour and a half late, and Casey was determined to arrive on time. He had decided he was going to get on time or arrive on time by driving the train very, very fast. Some say that he drove the train over 100 miles an hour (or 160 kilometers per hour for the rest of you).
As Casey was traveling through one of these small towns on the way to where he was supposed to be, one of the people on the train told him that there was another train blocking the track – that is, another train that was on the same railroad track that Casey’s train was on. Unfortunately, because Casey’s train was going so fast, it wasn’t going to be possible for him to stop the train before it hit the one that was parked or was stationary on the railroad track in this small town.
Casey then told the other person who was on the train to jump off the train, and he would try to stop the train, both by blowing the whistle to make sure no one else got hurt as well as pulling on the brake. The “brake” (brake) is what is used to stop a moving vehicle. You have a brake on your car, for example, to slow and stop the car when it is moving. Well, the train had a brake, and Casey put his hand on the brake and tried to stop or at least slow the train down before it hit the other train.
Well, of course the two trains hit each other, and amazingly only one person died in the crash. Everyone else had been saved because of how Casey was able to slow the train and of course blow the whistle to warn everyone else to get away from these two trains that were going to hit each other. People immediately called the now dead Casey Jones a hero for his courage and his achievement of preventing anyone else from dying in this train crash.
One could argue, I suppose, that if Casey had not been travelling so fast in order to arrive on time, there would never have been a problem, but that’s not the way that the story is interpreted by most Americans who know Casey Jones’ story, and most schoolchildren grow up hearing about Casey Jones – or at least, they did when I was a child.
Shortly after Casey’s death, another railroad worker by the name of Walter Saunders wrote a song about him called “The Ballad of Casey Jones,” and it told the story of Casey’s Death. This is how Casey became famous in the U.S. A “ballad” (ballad) is a slow song that tells a story, often a traditional song of a culture that tells the story of some hero, or perhaps some sad tale, some sad story. This indeed was a sad story but also a story of courage.
“The Ballad of Casey Jones” became popular throughout the United States, and it was something that people began to listen to and to sing themselves. It became popular, interestingly enough, back when I was a child in the 1970s when a famous rock group you may have heard of, called the Grateful Dead, released a version of the song – that is, they made a version of the song.
The words of the song have sometimes changed over the years, but the message is always the same – this man Casey Jones was a hero who saved the lives of many people by giving up his own life.
We turn from the story of a hero to the story of a popular television program.
Happy Days was one of the most successful television shows of the 1970s in the United States. Happy Days was about a middle-class family named the Cunninghams, who lived in Milwaukee, Wisconsin, during the 1950s and 1960s. The term “middle class” is a very important one in American culture and politics. To say you are “middle class” means you are not rich, but you’re not poor. Most Americans like to think of themselves as being middle class. They don’t have a lot of money, but they’re not poor either.
This television show, then, was about what we might call a “typical middle-class white family” in the town of Milwaukee, Wisconsin. Wisconsin is located in the north central part of the U.S. next to the greatest state in the U.S., my home state of Minnesota. Milwaukee was, during the 1950s, a town that was famous for making beer. It was a town that manufactured or made beer. That was the most famous product of the town of Wisconsin – the city of Wisconsin, I should call it.
The Cunninghams were a family that lived in this town, and the television show, which was a comedy – a funny show – was about the life of this middle-class family. There were four people in the family: the father, whose name was Howard; the mother, whose name was Marion; and a brother and a sister, Ritchie and Joanie. The show followed the Cunninghams in their everyday life. It was what we would call a “situation comedy,” or a “sitcom” for short.
The Cunninghams were considered an all-American family – a typical family who had qualities and characteristics that other people watching the show in the 1970s would look at and “admire” – consider good things. But of course, they weren’t perfect, and that’s what made the show funny.
The show was mostly about the children of the family – Ritchie in particular and his friends, all of whom were teenagers. They would spend a lot of time at a local drive-in. A “drive (drive) – in (in)” was a kind of movie theater that was popular in the 1950s and ’60s, right up until probably the 1990s. A drive-in theater is where you drive your car into what is a large parking lot, and next to your car there’s a little speaker, and in front of the drive-in there is, of course, a very large screen on which you watch the movie.
Drive-ins were very popular in many American towns. Even when I was growing up you could go to a drive-in and watch a movie. Nowadays there aren’t very many drive-ins left, but during the 1950s and ’60s, drive-ins were popular and especially popular among teenagers who would go in their cars and watch movies. One of the most popular characters on Happy Days was not one of the Cunningham family, but rather one of Ritchie Cunningham’s friends, Arthur Fonzarelli, who was called simply “Fonzie” or “the Fonz.”
Fonzie lived in an apartment above the Cunningham’s garage. He was older than Ritchie and he was considered cool. He wore a leather jacket. He rode a motorcycle, and he seemed to know a lot about life. He would give Ritchie advice, especially about women and how to get a girlfriend, but also how to live a good life. He was in many ways, in 1970s culture, the epitome of what it meant to be cool. “Epitome” (epitome) means the perfect example of something.
Even though the show was very popular in the 1970s, it wasn’t about the 1970s, remember. It was about the 1950s. Now, you might be wondering why a show about the 1950s was so popular in the 1970s – why they didn’t just make the characters, the people in the television show, about the 1970s. Part of the reason is that the show was part of a larger movement in American culture of “nostalgia.”
“Nostalgia” (nostalgia) is looking back at the way things were and remembering them as being much better than the way things are now. The 1970s was a time of social change. It was a time of economic change, and perhaps one reason why a show about the 1950s was popular during this period was that people were feeling a little insecure or unsafe about the changes going on in American life during this period, much the way people are unsure about those things today in 2016.
Not only was the television show Happy Days popular, but also music from the 1950s became popular during the 1970s. I remember, once again when I was in grade school and high school, hearing a lot of 1950s music on the radio. Movies about the 1950s were also very popular during this period. A year before Happy Days first was shown on American television in 1974, a movie by a young George Lucas called American Graffiti was also very popular, taking as its theme teenagers in the 1950s.
In fact, there are a lot of similarities between the movie American Graffiti and Happy Days in terms of the general setting or the general background of the show. Both were about American teenagers in the 1950s; so was another popular musical from two years before the release of American Graffiti, a musical called Grease which first appeared in 1971. That was later made into a popular movie with John Travolta and Olivia Newton John in 1978. So you can see that there were several things in American culture related to the 1950s during this period of the 1970s.
There were several other television shows that came from Happy Days. It was popular in this period in American television to have what were called “spin-offs.” A “spin (spin) hyphen off (off)” is a television show in which one or more of the characters is taken and you basically have a different show about those characters. There were several spin-offs from Happy Days, including the more or less successful Mork and Mindy, which starred a young comedian by the name of Robin Williams, who if you know something about American movies later became quite a famous star himself.
The stars of Happy Days were also famous later on, especially Ron Howard. Ron Howard became a very successful movie director, directing films such as Apollo 13, A Beautiful Mind, and that horrible movie The Da Vinci Code. Happy Days as a show lasted for 11 seasons on television – 11 years, basically – and it continues to be a show that most Americans of my generation remember and think back fondly on. In fact, you might say that we have nostalgia for television shows that were as funny as Happy Days that an entire family could sit down and watch.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Iran, from Roohallah (Roohallah). The question has to do with three verbs: “to try out,” “to examine,” and “to test.” “To try (try) out (out)” is a two-word phrasal verb meaning to see how well something works – to use something to see how it functions.
For example, you might be considering buying a new computer, so you go to the store “to try it out” – to see how it works, to see if you want to buy it. Or perhaps you want to exercise and someone is teaching you a new way of exercising. You decide you’re going “to try it out” for a few weeks. You’re going to see if you like it, see how it works. That’s the phrasal verb “to try out.” There’s one other less common use of this phrasal verb, especially in the world of theatre. “To try out” can also mean to go and try to get a certain part in a play or performance.
When a school, for example, is going to produce a play, it will have the students who want to be part of the play “try out.” They will go and they will sing or they will act. They will do something, and then the director or the teacher will decide who is going to get which part, which character, in the play. That’s another use of this phrasal verb “to try out,” but the more common use is the one I mentioned first, which is to test something to see how well it works, to try something to see how it functions.
The second verb is “to examine” (examine). “To examine” means to look at something very closely, very carefully, in order to learn more about it. If a police officer is trying to find who committed, who did, a certain crime, the officer will examine the evidence carefully, we hope. He will look at it very closely, very carefully.
You could examine a cup that you want to buy at the store to make sure that there aren’t any problems with it, there aren’t any cracks in it. I didn’t do that a few weeks ago when I bought a new cup at the store, and when I got it home, it started to “leak” (leak) – water started to come out of the bottom of the cup, which of course is not really the way a cup is supposed to work, right? I didn’t examine it. I didn’t look at it closely.
The third verb is “to test” (test). “Test” has a couple of different meanings. “To test” can mean to use something in a way to see if it is working properly. So, in that sense, “test” can mean something similar to the phrasal verb “to try out.” “I’m going to test this car to see if I like it.” “I’m going to test this website to see if I want to use it.” That’s one meaning of “test.”
“Test” can also be used to mean to give someone some questions or some problems to solve to see if he knows a certain type of information. A teacher or a professor “tests” his students. He asks his students questions or gives his students “tests” (as a noun) in order to see if they know what they should know. The word “test” as a noun means some questions you answer in order to exhibit or to show that you have knowledge about a certain area, a certain topic.
A third meaning of “test” is to have part of your body examined closely to see if you have some disease or illness. There’s a related verb, “to get tested.” “To get tested” for a certain disease means that you go to a doctor or to a laboratory where they take some of your blood to see if you have a certain illness or disease.
There are some relationships among these three verbs, especially in their noun forms. I mentioned the verb “to examine.” However, we also have a noun “examination” which can mean the same as the noun “test,” meaning a group of questions or problems that you have to answer or solve in school to show that you know something about a topic, or for a company that may want to know if you know how to do something. The company may give you an examination, a “test” – a list of questions or problems that you have to answer or solve.
When you go to the doctor to see if there is anything wrong with you, he may give you an “examination.” He may look at you closely and carefully to make sure there’s nothing wrong with you. That’s another use of the noun “examination.” So you can see that there are some connections here between these three verbs and the nouns that we get from those verbs.
Our next question comes from Zhao (Zhao), originally from China, now living in the great state of Texas. Zhao wants to know the use of the words “dude” and “buddy.” “Dude” (dude) is a term, an informal term, for a man or what we might call a “guy” that is used especially by young people. It usually refers to a man, not a woman.
You could say, “Hey, dude. What’s up?” What’s going on? I’m not sure if it’s as popular as it was, say, 15, 20 years ago, but it’s still popular enough that you will hear it a lot. It is an informal term, so you would definitely not want to use this at your job or with your boss. I myself don’t use it very often unless I’m sort of making a joke, trying to sound younger than I really am, perhaps.
The meaning of the word can change depending on how it is said. For example, some people use it to express surprise at what someone is doing when they don’t understand why someone is doing something or are surprised that someone is doing something. You may say, “Dude, what are you doing?” Notice that “dude” doesn’t mean the person you’re talking to is your friend.
You could certainly call someone you’ve never met before “dude” if you were talking to him at a bar or at a party, especially if you were trying to get that person’s attention, perhaps to say something that you want the person to pay attention to. If you are at a party and you saw a beautiful girl on the other side of the room, you may say to someone, “Dude, did you see the girl over there with the red dress, huh?” I would never say that, of course. I am a happily married man.
The word “buddy” (buddy) can refer to someone who is your close friend. It’s especially a word we would use for young children in talking about their friends, especially young boys. We may say, “Well, who’s your buddy?” Who’s your friend? You would say that to a young child, perhaps. It could, however, also be used for men. I could talk about my “best buddy,” my good friend from high school, and that would not sound unusual or strange.
So, a “buddy” could also be a male friend, especially the friend of another man. Rob and I were buddies in high school. (That’s the name of one of my friends from my high school days.) There’s another very different use of the word “buddy,” when it is used in the context of someone you do not know, someone you’ve never seen before. There it is used to refer to someone who is not only a stranger but someone perhaps whom you are insulting or to whom you are going to say something that may make the other person angry.
Here you have to be very careful about the use of the word “buddy” because it can often be interpreted as either being an insult or a challenge to another person. You’re telling the person something that the person is doing wrong. If you say, “Hey, buddy. Don’t be touching my car,” that means perhaps some man was walking by and putting his hand on your car and you want him to stop.
If you say, “Hey, buddy,” you might even get into a fight about it. It’s a very aggressive, challenging thing for one man to say to another. It’s very strange, of course, since that same word “buddy” is also used for young boys and their friends, but in this particular context – from one adult male to another, who don’t know each other – it could actually be a very threatening thing to say.
Finally, a question from Ali (Ali) from an unknown country. Ali wants to know the meaning of the expression “courtesy of.” “Courtesy (courtesy) of” is an expression meaning that this was produced or given or paid for by another person or organization. For example, on our “Ask an American” segments here on the English Café, we might say that these recordings are “courtesy of Voice of America.” That means we get them from Voice of America, which in fact we do, even though I may not have mentioned that.
You could also, for example, use this in a very different situation. Let’s say your boss gives you some tickets to go to a football game or a baseball game. You may say to your wife, “These tickets are courtesy of my boss,” meaning my boss paid for them. My boss gave them to me.
If you have a question or comment and want to test our knowledge of English, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
railroad – the system of train tracks (long metal bars in the ground) and the trains that travel on them
* The railroad in many European and Asian countries is well taken care of, with tracks in good condition and the trains running on time.
flagman – a person whose job is to signal or send messages using a flag or flags, usually on a railroad line or in a construction zone
* Because of the construction, there was only one lane open on the road so a flagman signal for cars to merge into that lane.
(train) engineer – a person who drives a train; the operator of a train
* The engineer pulled the train slowly into the station and the passengers got off.
whistle – an object that makes a clear and high-pitched sound by forcing air through a small opening
* The boat captain blew the boat’s whistle as he pulled into the dock to let the passengers know that they had reached their destination.
shift – a period of time or number of hours someone is scheduled and paid to work each day
* Yuko works the night shift at the local grocery story, going to work at 6 p.m.
hero – a person who is admired for their courage, achievements, or qualities
* Many say firefighters heroes because they save people from burning buildings.
ballad – a slow song that tells a story
* The ballad is sad and tells the story of two young people who were in love but kept apart by their families.
middle-class – the group of people who are socially and economically between the poor and the wealthy, including professional business workers
* Theodora grew up in a middle-class family. Her parents owned a small clothing store where she and her brother worked on the weekends.
drive-in – a type of movie theater where people park and sit in their cars in a large outdoor area to watch a movie on a very large screen
* Teenagers go to the drive-in on Friday nights to meet their friends, or to sit in their cars with a date to watch a movie.
epitome – the perfect example of a quality, characteristic, or type
* Flying in a private plane is the epitome of luxury and comfort.
cool – describing something or someone that is very attractive, fashionable, and modern
* Yvette always looks very cool with her perfectly styled hair, trendy clothing, and expensive sunglasses.
season – a set or sequence of related episodes in a television show, often shown within a few months or one year
* A typical season for some television shows is 15 episodes, which usually includes a holiday-themed show.
to try out – to test something to see how well it works; to use something so see how it functions
* Jenny wished she could try out each lawn mower before deciding which to buy.
to examine – to look at something closely and carefully in order to learn more about it
* The experts examined the bomb and were able to defuse it before it exploded.
to test – to use something in a planned and controlled way to see if it works properly; to use a set of questions or problems to measure someone's skills, knowledge, or abilities; to examine a part of the body or a substance taken from the body
* Ana tested the exercise machine at a low speed before her doing her workout.
dude – a man or a guy, a term used especially by young people; a term used to address another boy or man, usually used by boys or young men
* Those dudes over there are trying to break into my car!
buddy – a close friend, a term used especially to describe men or boys who are friends; a term used to address a man who one does not know
* This is a picture of my buddies and me on a weekend trip to Brussels.
courtesy of – paid for by, given by, or donated by a person or organization
* These theater tickets are courtesy of the theater owner, who is an admirer of your work.
What Insiders Know
Happy Hour
A “happy hour” is a period of time when a “bar” (pub; a business that primarily serves alcoholic drinks) or another “establishment” (a business that serves customers) offers “discounted” (sold at prices lower than usual) drinks and “appetizers” (food eaten before the main dish). Some restaurants, “bowling alleys” (places where people play a game or sport of throwing a heavy ball down a lane or alley trying to hit 10 “pins,” short sticks shaped like bottles), and other businesses associated with entertainment have happy hours, too, but they might offer discounted services during that time rather than discounted food and drink. For example, a bowling alley might offer a happy hour when shoe rentals are free.
A happy hour is typically in the late afternoon on a weekday, before the “dinner rush” (the period of time when many people go to restaurants to eat in the evening). Sometimes colleagues go to a happy hour together after work, but before they go home.
Nobody knows “for sure” (with complete certainty) where the term “happy hour” “originated” (began; came from), but some people think it is from the U.S. Navy. A group of soldiers had a weekly social event that they called the Happy Hour Social, and this gathering was associated with smoking and drinking. As the idea spread, the name “stuck” (continued to be used).
Some states have “banned” (prohibited; decided to no longer allow) happy hours, while others have restricted the times when happy hours may be offered. Most of the bans are “attributed to” (explained by) safety and health concerns. For example, the U.S. military banned happy hours on “military bases” (property owned by the military for training and housing soldiers) in 1984. The State of Utah banned happy hours beginning in 2012, but in that same year, the State of Kansas made happy hours legal again after a 26-year “ban” (making something illegal).