
= AP Euro 2.1 Contextualizing 16th- and 17th-Century Challenges and Developments
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, it's Emily P. Let's talk all about unit 2: the Age of Reformation 宗教改革时代.
 +
I'm going to start by contextualizing 提供背景信息. Contextualization 背景化；情境化 is a very important skill for you in your AP history class. Contextualizing is telling me what is going on in the world before a specific event. You got to situate 使处于；使位于 it in the broader context 更广泛的背景 of world history, as the College Board says.
 +
So in order to talk about the Protestant Reformation 新教改革, I actually need to contextualize the Protestant Reformation and remind you what was happening in Europe before 1517.
 +
Let's start by recapping 回顾 last unit: the Renaissance 文艺复兴 and the Age of Exploration 探索时代. By the end of last unit, we see that Europe has been experiencing a commercial revolution 商业革命 and a price revolution 价格革命.
 +
The connected hemispheres 半球 -- especially now that joint stock companies 股份公司 are gaining lots of wealth -- means that Europe is moving steadily 稳步地 toward a money-based capitalistic economy 以货币为基础的资本主义经济. Due to 由于 the enclosure acts 圈地法案, small-scale farmers 小农户 find themselves moving to the cities, which leads to 导致 this increase in urbanization 城市化进程加快.
 +
Not only that, but new political theorists 政治理论家 like Machiavelli started to advocate for 提倡；主张 a secular 世俗的 civic 公民的 political system 政治体系. And new monarchs 君主 like Ferdinand and Isabella, or Henry VII, or even some of these new wealthy elites 富有的新精英 living within Italy, start to separate themselves from 使自己与……分离 the Catholic Church 天主教会 and establish their own political order 政治秩序.
 +
Speaking of 说到；谈及 the Catholic Church, let's talk about some foreshadowing 伏笔；预示 for this unit.
 +
So in 1517, Martin Luther decides that he wants to write up 撰写 a list of critiques 批评意见 that he has about the Catholic Church. And then he publishes them widely 广泛出版 and disseminates 传播 them throughout Europe -- thanks to 多亏；由于 the printing press 印刷机 -- and this begins the Protestant Reformation.
 +
Prior to 在……之前 the Protestant Reformation, under the banner of 在……的旗帜下 Christianity 基督教, you had Roman Catholics 罗马天主教徒 and then you have the Eastern Orthodox Church 东正教. And now a new player has entered the game, and they are called Protestants 新教徒.
 +
And this Protestant Reformation challenges 挑战 the idea of a religiously unified 宗教统一的 Europe. What version of Christianity are you going to practice -- Catholicism 天主教 or Protestantism 新教?
 +
In order to consolidate 巩固 and gain their own power, leaders start to turn toward 转向 Protestantism and break away from 脱离 Catholicism because it gives them more power and control. But in strongly dominated 占主导地位的 Catholic lands like France and Spain, those leaders ally themselves with 与……结盟 the church to reassert 重申 or reaffirm 再次确认 their control.
 +
And this struggle 斗争 between religion and politics -- and how they should be connected, and to what extent 到什么程度 they should be connected -- leads to 导致 a lot of conflict 冲突 in Europe.
 +
Make sure you're following along 跟上进度 because unit 2 is one of my favorite units, and let's just get right into it, y'all.
 +

'''


== 中文释义

嘿，同学们，我是艾米丽·P。咱们来全面聊聊第二单元：宗教改革时代。 +

我要先讲一下时代背景。**背景分析**在你们的AP历史课上**是一项非常重要的技能。所谓背景分析，就是告诉我在一个特定事件发生之前，世界上正在发生什么。**就像大学理事会（College Board）说的那样，*你得把它置于更广阔的世界历史背景中。* +

*所以，为了讨论"新教改革"（Protestant Reformation），我实际上需要阐述一下新教改革的背景，并提醒你们在1517年之前欧洲发生了什么。* +

咱们先回顾一下上一单元的内容：文艺复兴（Renaissance）和大航海时代（the Age of Exploration）。在上一单元的结尾，我们看到欧洲经历了商业革命（commercial revolution）和价格革命（price revolution）。 +

各大半球之间相互联系——*尤其是现在股份制公司（joint stock companies）积累了大量财富——这意味着欧洲正稳步迈向以货币为基础的资本主义经济（capitalistic economy）。由于《圈地法案》（enclosure acts），小农户们发现自己得搬到城市里去，这导致了城市化（urbanization）进程的加快。* +

不仅如此，*像马基雅维利（Machiavelli）这样的新政治理论家, 开始倡导世俗的公民政治体系*（secular civic political system）。像费迪南德（Ferdinand）和伊莎贝拉（Isabella），或者亨利七世（Henry VII）这样的**新君主，甚至包括意大利（Italy）的一些新富有的精英们，开始与天主教会（Catholic Church）划清界限，并建立他们自己的政治秩序。** +

说到天主教会，咱们来谈谈本单元的一些伏笔。 +

所以在1517年，马丁·路德（Martin Luther）决定写下他对天主教会的一系列批判。然后他广泛地发表这些批判内容——多亏了印刷机——并在整个欧洲传播开来，由此开启了新教改革。 +

*在新教改革之前，在基督教（Christianity）的旗帜下，有罗马天主教徒（Roman Catholics）和东正教（the Eastern Orthodox Church）。现在一个新的参与者登上了历史舞台，他们被称为"新教徒"（Protestants）。* +

**而这次"新教改革", 对欧洲在宗教上统一的理念提出了挑战。**你要信奉哪种基督教呢——天主教（Catholicism）还是新教（Protestantism）？ +

**为了巩固和获取他们自己的权力，领导者们开始转向新教，并脱离天主教，因为这能给他们更多的权力和控制权。**但在法国（France）和西班牙（Spain）这些天主教占主导地位的国家，那些领导者们更加与教会结盟，以重申或确认他们的控制权。 +

*#宗教与政治之间的这种斗争——以及它们应该如何相互联系，以及联系到何种程度——在欧洲引发了许多冲突。#* +

一定要跟上我的思路，因为第二单元是我最喜欢的单元之一，大家，咱们直接进入正题吧。 +

'''

== pure

Hey students, it's Emily P. Let's talk all about unit 2: the Age of Reformation.

I'm going to start by contextualizing. Contextualization is a very important skill for you in your AP history class. Contextualizing is telling me what is going on in the world before a specific event. You got to situate it in the broader context of world history, as the College Board says.

So in order to talk about the Protestant Reformation, I actually need to contextualize the Protestant Reformation and remind you what was happening in Europe before 1517.

Let's start by recapping last unit: the Renaissance and the Age of Exploration. By the end of last unit, we see that Europe has been experiencing a commercial revolution and a price revolution.

The connected hemispheres -- especially now that joint stock companies are gaining lots of wealth -- means that Europe is moving steadily toward a money-based capitalistic economy. Due to the enclosure acts, small-scale farmers find themselves moving to the cities, which leads to this increase in urbanization.

Not only that, but new political theorists like Machiavelli started to advocate for a secular civic political system. And new monarchs like Ferdinand and Isabella, or Henry VII, or even some of these new wealthy elites living within Italy, start to separate themselves from the Catholic Church and establish their own political order.

Speaking of the Catholic Church, let's talk about some foreshadowing for this unit.

So in 1517, Martin Luther decides that he wants to write up a list of critiques that he has about the Catholic Church. And then he publishes them widely and disseminates them throughout Europe -- thanks to the printing press -- and this begins the Protestant Reformation.

Prior to the Protestant Reformation, under the banner of Christianity, you had Roman Catholics and then you have the Eastern Orthodox Church. And now a new player has entered the game, and they are called Protestants.

And this Protestant Reformation challenges the idea of a religiously unified Europe. What version of Christianity are you going to practice -- Catholicism or Protestantism?

In order to consolidate and gain their own power, leaders start to turn toward Protestantism and break away from Catholicism because it gives them more power and control. But in strongly dominated Catholic lands like France and Spain, those leaders ally themselves even more with the church to reassert or reaffirm their control.

And this struggle between religion and politics -- and how they should be connected, and to what extent they should be connected -- leads to a lot of conflict in Europe.

Make sure you're following along because unit 2 is one of my favorite units, and let's just get right into it, y'all.

'''