
= AP Euro 1.3 The Northern Renaissance
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, it's Emily P. Let's talk about the northern Renaissance 文艺复兴.
 +
Italian Renaissance takes root in 扎根于 -- you guessed it -- Italy and then starts to spread north throughout the continent 大陆 of Europe. The northern Renaissance centers on 以……为中心 the low countries, which is going to be the modern-day Benelux countries 比荷卢经济联盟国家 -- Belgium 比利时, Netherlands 荷兰, and Luxembourg 卢森堡.
 +
Students in AP History, we call this area the low countries, and I just want us to take a second in our brains and think about the fact that the Netherlands -- the Netherlands -- was a low country.
 +
What we need to do here is talk about similarities 相似之处 and differences between the northern Renaissance and the Italian Renaissance.
 +
Now, both of these artistic movements 艺术运动 are focusing on individualism 个人主义 and humanism 人文主义, and both reflect 反映 naturalism 自然主义, which is really just choosing to paint and draw what you see in a natural form 自然形态. This is both in contrast to 与……形成对比 -- again -- what art looked like during the Middle Ages, which was depicting 描绘 these religious heavenly 天国的；神圣的 scenes in heaven. Rather than that 而不是, these artists are choosing to just draw what they see outside of their window in front of them.
 +
A difference between the Italian Renaissance and the northern Renaissance is that the northern Renaissance focused on drawing people more as they are, whereas 然而 the Italian Renaissance focused on creating this beautiful classical 古典的 ideal 理想 with -- like, you know -- the rippling 起伏的 muscles 肌肉.
 +
Specifically 具体地说, in the northern Renaissance, there is a huge focus on detail 细节. Look no further than 看看；不用远看 Albrecht Dürer and his self-portraits 自画像 or Jan van Eyck and the Arnolfini Portrait 阿尔诺芬尼夫妇像. And generally 通常；一般来说, you can assume 假设 that if you see a lot of people in a painting, it's a northern Renaissance painting.
 +
Pieter Bruegel the Elder 老彼得·勃鲁盖尔 -- whom the AP test loves, by the way 顺便说一下 -- depicted 描绘 a lot of people just doing everyday things.
 +
But outside of just visual art 视觉艺术, there's also written art 书面艺术. Desiderius Erasmus writes a book called On the Education of a Christian Prince 论基督君主的教育, which I love to contrast with 与……形成对比 Machiavelli's The Prince 君主论.
 +
Machiavelli postulates 假定；假设 this very pragmatic 务实的 approach to 对……的方法 ruling 统治, while Erasmus says, "You know, we need to actually consider 考虑 the moral 道德的 and ethical 伦理的；道德的 responsibilities of a ruler to his people." Erasmus says it is the prince's duty 职责 to be virtuous 品德高尚的, just 公正的, and pious 虔诚的.
 +
A lot of these northern Renaissance humanists embody 体现；代表 more Christian values 基督教价值观 in their writing. Erasmus, in his book In Praise of Folly 愚人颂, critiques 批评；批判 the Catholic Church 天主教会 and its overabundance 过度；过多 and opulence 富裕；奢华.
 +
Englishman Thomas More, in his book Utopia 乌托邦, says that a just 公正的 society is capable of 能够 existing if we abolish 废除 private property 私有财产 and educate women.
 +
In summary 总之, there are many differences between the Italian Renaissance and the northern Renaissance. The northern Renaissance focuses more on Christian values and focuses more on depicting 描绘 life naturally as it is. The Italian Renaissance depicts people in that classical ideal.
 +
But at the end of the day 归根结底, both visual artists in both of the renaissances employ 采用 naturalism 自然主义 and rely on 依赖 patrons 赞助人 to make sure that they are able to commission 委托制作 art.
 +
I hope that helps. As always, you can do it. I believe in you.
 +

'''

== 中文释义

嘿，同学们，我是艾米丽·P（Emily P）。咱们来聊聊北"方文艺复兴"（northern Renaissance）吧。 +

意大利文艺复兴（Italian Renaissance）起源于——你猜对了——意大利，然后开始向北传播，遍及欧洲大陆。*北方文艺复兴, 以低地国家为中心，也就是现代的"比荷卢"三国——比利时（Belgium）、荷兰（Netherlands）和卢森堡（Luxembourg）。 +*

学"美国大学预修课程"（AP）历史的同学们，我们把这个地区称为低地国家，我就想让大家花点时间在脑海里想一想这个事实：荷兰——荷兰——就是一个低地国家。 +

我们在这里需要做的, 是谈谈**北方文艺复兴, 和意大利文艺复兴之间的异同点。** +

现在，这两个艺术运动, 都专注于"个人主义"（individualism）和"人文主义"（humanism），并且都体现了自然主义（naturalism），而**"自然主义"其实就是选择以自然的形式, 去描绘你所看到的东西。**这与中世纪时期的艺术风格再次形成了对比，*中世纪的艺术描绘的是天堂里那些宗教的神圣场景。与之不同的是，"自然主义"这些艺术家们, 选择去描绘他们眼前窗外所看到的东西。* +

*意大利文艺复兴和北方文艺复兴之间的一个区别是，#北方文艺复兴更注重如实描绘人物，而意大利文艺复兴则注重创造那种美丽的古典理想形象，就比如有着明显起伏的肌肉线条的形象。#* +

具体来说，**"北方文艺复兴"非常注重细节。**看看阿尔布雷希特·丢勒（Albrecht Dürer）和他的自画像，或者扬·凡·艾克（Jan van Eyck）和《阿尔诺芬尼夫妇像》（the Arnolfini Portrait）就知道了。一般来说，如果你看到一幅画里有很多人物，你可以认为这是一幅北方文艺复兴时期的画作。 +

老彼得·勃鲁盖尔（Pieter Bruegel the Elder）——顺便说一下，这是美国大学预修课程（AP）考试很喜欢考的人物——描绘了很多人做日常事情的场景。 +

但除了视觉艺术之外，还有书面艺术。德西德里乌斯·伊拉斯谟（Desiderius Erasmus）写了一本名为《论基督教君主的教育》（On the Education of a Christian Prince）的书，我很喜欢把这本书和马基雅维利（Machiavelli）的《君主论》（The Prince）进行对比。 +

*马基雅维利提出了一种非常务实的统治方法，而伊拉斯谟则说：“你知道吗，我们实际上需要考虑一个统治者对他的人民所应承担的道德和伦理责任。”* 伊拉斯谟说，成为一个有德行、公正且虔诚的君主是君主的职责。 +

**很多这些北方文艺复兴时期的人文主义者, 在他们的作品中更多地体现了基督教价值观（Christian values）。**伊拉斯谟在他的《愚人颂》（In Praise of Folly）一书中，*批判了天主教会（Catholic Church）的过度铺张和奢华。* +

英国人托马斯·莫尔（Thomas More）在他的《乌托邦》（Utopia）一书中说，如果我们废除私有财产, 并对女性进行教育，一个公正的社会是能够存在的。 +

*总之，#"意大利文艺复兴"和"北方文艺复兴"之间有很多不同之处。北方文艺复兴更多地关注基督教价值观，并且更注重如实地描绘生活本来的样子。而意大利文艺复兴, 则按照那种古典理想来描绘人物。#* +

但归根结底，这两个文艺复兴时期的视觉艺术家们, 都运用了自然主义（naturalism），并且都依赖"赞助人"来确保他们能够委托创作艺术品。 +

我希望这能对你有所帮助。一如既往，你能做到的。我相信你。 +

'''

== pure

Hey students, it's Emily P. Let's talk about the northern Renaissance.

Italian Renaissance takes root in -- you guessed it -- Italy and then starts to spread north throughout the continent of Europe. The northern Renaissance centers on the low countries, which is going to be the modern-day Benelux countries -- Belgium, Netherlands, and Luxembourg.

Students in AP History, we call this area the low countries, and I just want us to take a second in our brains and think about the fact that the Netherlands -- the Netherlands -- was a low country.

What we need to do here is talk about similarities and differences between the northern Renaissance and the Italian Renaissance.

Now, both of these artistic movements are focusing on individualism and humanism, and both reflect naturalism, which is really just choosing to paint and draw what you see in a natural form. This is both in contrast to -- again -- what art looked like during the Middle Ages, which was depicting these religious heavenly scenes in heaven. Rather than that, these artists are choosing to just draw what they see outside of their window in front of them.

A difference between the Italian Renaissance and the northern Renaissance is that the northern Renaissance focused on drawing people more as they are, whereas the Italian Renaissance focused on creating this beautiful classical ideal with -- like, you know -- the rippling muscles.

Specifically, in the northern Renaissance, there is a huge focus on detail. Look no further than Albrecht Dürer and his self-portraits or Jan van Eyck and the Arnolfini Portrait. And generally, you can assume that if you see a lot of people in a painting, it's a northern Renaissance painting.

Pieter Bruegel the Elder -- whom the AP test loves, by the way -- depicted a lot of people just doing everyday things.

But outside of just visual art, there's also written art. Desiderius Erasmus writes a book called On the Education of a Christian Prince, which I love to contrast with Machiavelli's The Prince.

Machiavelli postulates this very pragmatic approach to ruling, while Erasmus says, "You know, we need to actually consider the moral and ethical responsibilities of a ruler to his people." Erasmus says it is the prince's duty to be virtuous, just, and pious.

A lot of these northern Renaissance humanists embody more Christian values in their writing. Erasmus, in his book In Praise of Folly, critiques the Catholic Church and its overabundance and opulence.

Englishman Thomas More, in his book Utopia, says that a just society is capable of existing if we abolish private property and educate women.

In summary, there are many differences between the Italian Renaissance and the northern Renaissance. The northern Renaissance focuses more on Christian values and focuses more on depicting life naturally as it is. The Italian Renaissance depicts people in that classical ideal.

But at the end of the day, both visual artists in both of the renaissances employ naturalism and rely on patrons to make sure that they are able to commission art.

I hope that helps. As always, you can do it. I believe in you.

'''