
= AP Euro 6.1 Contextualizing Industrialization and Its Origins and Effects
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, it's Emily P. Let's talk all about unit 6.1: Contextualizing Industrialization and Its Effects 探究工业化及其影响的背景. +

It's been a wild 疯狂的；不可思议的 thing to be a European in the late 1700s and early 1800s because Europe had just experienced the French Revolution 法国大革命, subsequently 随后 Napoleon's conquest of Europe 拿破仑对欧洲的征服, and then the fact that things are now being mass-produced 批量生产 in a new and almost unchecked 未加约束的 way. +

The Industrial Revolution 工业革命 starts in Britain in the mid-18th century because of its environmental advantages 环境优势 and also because of its economic and political prowess 经济和政治实力 -- due to 由于 Britain's ascendency 优势地位 which was covered in unit five -- and due to Parliament's support of 议会支持 Britain making as much money as possible. +

The textile industry 纺织业 booms 蓬勃发展 and then is later transformed into 转变为 the iron and steel industries 钢铁工业. Industrialization 工业化 is able to take place 发生 in Britain because of its iron and coal deposits 铁矿和煤矿储量, but also because it had a tremendous amount of support 大量支持 through Parliament, because Parliament knew that this was going to make them more money. +

Britain's favorable political climate 有利的政治环境 plus 加上 its favorable social climate 有利的社会环境 -- thanks to 由于 the Agricultural Revolution 农业革命 and a large labor working class 庞大的工人阶级 who is now living in cities -- led to 导致 industrialization taking off 迅速发展 in Britain, and it slowly started to spread from the islands to the continent 从岛屿传播到欧洲大陆. +

As you can imagine, the Industrial Revolution 工业革命 changed the world. Like, historians think that this is the biggest thing to ever happen in all of world history, and I might agree with that. I could argue that the Agricultural Revolution 农业革命 -- that original Neolithic Revolution 最初的新石器时代革命 -- might have changed things a little bit more. +

But literally 确实, the fact that you are watching this on a screen -- whether that is a handheld screen 手持屏幕 or on like a projector 投影仪 in a classroom or on your computer that you did not make -- and I like made this just in this little room that I live in in Colorado, and you are now watching it -- it's all thanks to 多亏；由于 the Industrial Revolution 工业革命. +

Yes, industrialization 工业化 did lead to 导致 the mass production of goods 商品的批量生产 and a rise in consumerism 消费主义的兴起 across the world, but it also led to 导致 early unchecked capitalism 早期不受约束的资本主义, which led to 导致 a gigantic wage gap 巨大的工资差距 between the factory owners 工厂主, the factory workers 工厂工人, and then this emerging middle class 新兴中产阶级 -- this new bourgeoisie 新资产阶级. +

And what does that lead to 导致, students? Say it with me: they're going to fight. +

Political effects 政治影响 are still simmering 酝酿 throughout Europe as a result of 由于 the French Revolution 法国大革命, and in the mid-1800s and 1848, we see what I like to call the "springtime of the peoples"  “人民之春”, which is a rise of liberal revolutions 自由主义革命的兴起 across the continent 欧洲大陆. +

Conservatives 保守派 are there trying to maintain power 维持权力, trying to maintain the status quo 维持现状 after the Napoleonic Wars 拿破仑战争, and these liberals 自由主义者 -- now who are maybe more incentivized 更受激励 after the economic disparities 经济不平等 that occurred as a result of 由于 industrialization 工业化, at least early industrialization -- are saying, "Maybe we should fight for more rights 争取更多权利." +

New ideologies 意识形态 -- or "isms" as we like to call them in class -- like nationalism 民族主义, feminism 女权主义, socialism 社会主义, communism 共产主义 -- all emerge 出现 in the wake of 在…之后 industrialization 工业化 because, y'all, when industrialization first started, when it was unchecked 不受约束的, it was so bad if you were a worker 对工人来说情况很糟糕. +

And over time 随着时间推移 -- through labor unions 工会, through protests 抗议活动, through social organizations 社会组织, through religious organizations 宗教组织 -- those ills 弊病 of the Industrial Revolution 工业革命 eventually got fixed 最终得到解决. +

This is actually my favorite unit in all of AP European History, so make sure that you follow along 跟上进度 because it's about to get wild 变得激动人心. +

As always, students, you can do it. I believe in you. +

'''

== 中文释义

嘿，同学们，我是艾米丽·P。我们来全面聊聊第六单元的6.1部分：工业化及其影响的背景梳理。 +

在18世纪末和19世纪初，作为一个欧洲人，那可真是一段不寻常的时期，因为欧洲刚刚经历了"法国大革命"，随后是拿破仑对欧洲的征服，而且当时东西都以一种新的、几乎不受控制的方式, 进行大规模生产。 +

**#工业革命（Industrial Revolution）在18世纪中期始于英国，#**这得益于它的环境优势，也得益于它在经济和政治方面的实力——这是在第五单元中提到的英国的崛起的结果——同时也得益于议会支持英国尽可能多地赚钱。 +
纺织业蓬勃发展，后来又转变为钢铁行业。*工业化能够在英国开展，是因为它有丰富的铁矿和煤矿资源，也因为它得到了议会的大力支持，因为议会知道这会让他们赚更多的钱。* +

*英国有利的政治环境，再加上良好的社会环境——这要归功于农业革命（Agricultural Revolution）, 以及大量生活在城市里的工人阶级*——使得工业化在英国兴起，并且慢慢地从英伦诸岛传播到欧洲大陆。 +

正如你们可以想象的那样，工业革命改变了世界。比如说，历史学家认为,这是世界历史上发生的最重大的事情，我可能也认同这一点。我可以说，新石器时代的农业革命, 可能在一定程度上带来了更大的变化。 +

但事实上，你现在正在屏幕上观看这段内容——无论是在手持屏幕上，还是在教室里的投影仪上，或者是在你并非亲手制造的电脑上——而我就在我位于科罗拉多州的小房间里制作了这个视频，你现在正在观看它——这一切都要归功于工业革命。 +

是的，*工业化确实导致了商品的大规模生产，以及全球消费主义的兴起，但它也导致了早期不受控制的资本主义，这使得工厂主、工厂工人以及新兴的中产阶级——新的资产阶级之间出现了巨大的工资差距。(#技术加剧贫富分化#)* +

同学们，**这会导致什么呢？**和我一起说：*他们会斗争(贫富分化, 导致阶级冲突)。* +
由于法国大革命的影响，政治方面的影响在整个欧洲持续发酵，*在19世纪中期以及1848年，我们看到了我称之为 “人民之春” 的情况，也就是欧洲大陆上自由革命的兴起。* +

保守派试图维持权力，在拿破仑战争（Napoleonic Wars）后维持现状，而这些自由派——至少在早期工业化导致的"经济不平等"之后，他们有更多的动力——他们说：“也许我们应该为更多的权利而斗争。” +

*#新的意识形态#*——或者像我们在课堂上所说的 “主义”——比如**#民族主义（nationalism）、女权主义（feminism）、社会主义（socialism）、共产主义（communism）——都是在工业化之后出现的，#**因为，大家要知道，**当工业化刚刚开始且不受控制的时候，对于工人来说情况非常糟糕。 **+

随着时间的推移——通过工会、抗议活动、社会组织以及宗教组织——工业革命带来的这些弊病, 最终得到了解决。 +

这实际上是AP欧洲历史中我最喜欢的单元，所以一定要跟上进度，因为接下来的内容会很精彩。 +
同学们，一如既往，你们能做到的。我相信你们。 +

'''

== pure

Hey students, it's Emily P. Let's talk all about unit 6.1: Contextualizing Industrialization and Its Effects.

It's been a wild thing to be a European in the late 1700s and early 1800s because Europe had just experienced the French Revolution, subsequently Napoleon's conquest of Europe, and then the fact that things are now being mass-produced in a new and almost unchecked way.

The Industrial Revolution starts in Britain in the mid-18th century because of its environmental advantages and also because of its economic and political prowess -- due to Britain's ascendency which was covered in unit five -- and due to Parliament's support of Britain making as much money as possible.

The textile industry booms and then is later transformed into the iron and steel industries. Industrialization is able to take place in Britain because of its iron and coal deposits, but also because it had a tremendous amount of support through Parliament, because Parliament knew that this was going to make them more money.

Britain's favorable political climate plus its favorable social climate -- thanks to the Agricultural Revolution and a large labor working class who is now living in cities -- led to industrialization taking off in Britain, and it slowly started to spread from the islands to the continent.

As you can imagine, the Industrial Revolution changed the world. Like, historians think that this is the biggest thing to ever happen in all of world history, and I might agree with that. I could argue that the Agricultural Revolution -- that original Neolithic Revolution -- might have changed things a little bit more.

But literally, the fact that you are watching this on a screen -- whether that is a handheld screen or on like a projector in a classroom or on your computer that you did not make -- and I like made this just in this little room that I live in in Colorado, and you are now watching it -- it's all thanks to the Industrial Revolution.

Yes, industrialization did lead to the mass production of goods and a rise in consumerism across the world, but it also led to early unchecked capitalism, which led to a gigantic wage gap between the factory owners, the factory workers, and then this emerging middle class -- this new bourgeoisie.

And what does that lead to, students? Say it with me: they're going to fight.

Political effects are still simmering throughout Europe as a result of the French Revolution, and in the mid-1800s and 1848, we see what I like to call the "springtime of the peoples," which is a rise of liberal revolutions across the continent.

Conservatives are there trying to maintain power, trying to maintain the status quo after the Napoleonic Wars, and these liberals -- now who are maybe more incentivized after the economic disparities that occurred as a result of industrialization, at least early industrialization -- are saying, "Maybe we should fight for more rights."

New ideologies -- or "isms" as we like to call them in class -- like nationalism, feminism, socialism, communism -- all emerge in the wake of industrialization because, y'all, when industrialization first started, when it was unchecked, it was so bad if you were a worker.

And over time -- through labor unions, through protests, through social organizations, through religious organizations -- those ills of the Industrial Revolution eventually got fixed.

This is actually my favorite unit in all of AP European History, so make sure that you follow along because it's about to get wild.

As always, students, you can do it. I believe in you.

'''