
= AP Euro 2.6 16th-Century Society and Politics
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, it's Emily Pool. Let's talk all about 16th century society and politics, especially in the wake of 随着……之后；在……之后, you know, the Protestant Reformation 新教改革.
 +
Family, what's that on your shirt? Oh, thanks for asking, students. This is my favorite painting of all time. This is Artemisia Gentileschi's Judith Beheading Holofernes, and it says "girls will be girls" on top of it, which I love so much because we're going to talk about the shifting role 转变的角色 of women today.
 +
Protestants 新教徒 argued that there is a priesthood of all believers 信徒皆祭司, and then men in Europe were like, "What?" Their reading of the Scripture 圣经 is clear that Jesus valued 重视 and treated women quite well. So now men are like, "Um, do we have to do that too? What does this mean about women's roles? Can women be preachers 传教士? Can women now get educated?"
 +
This debate about women is a theme 主题 that we will come back to 回到；重新讨论 over and over and over again in our study of European history -- and honestly, across the world. It is still an argument or a debate today.
 +
But even despite 尽管 the new Protestant focus on equality 平等 and the Protestant value of a nuclear family 核心家庭 that should be rooted in 植根于 love and complimentary work 互补的工作, established hierarchies 既定的等级制度 of gender 性别 and class 阶级 and religion 宗教 still remained the same across Europe from the 1400s to the 1600s.
 +
Even though early modern Europeans are challenging 挑战 traditionally held sources of power 传统权力来源 in all of the different ways, these established social hierarchies are still pretty much the same. Land ownership 土地所有权 determines 决定 wealth 财富, and if you've had wealth for a long time, you probably still have wealth.
 +
While women and their work at the home actually starts getting viewed with more dignity 尊严, they are still denied access from 被剥夺……机会 education and political systems 政治体系. And for the average European peasants 农民 -- someone on that bottom rung 最底层 of the social ladder 社会阶梯 -- things are still pretty much the same.
 +
You live in a little town with all your friends. Your calendar 日历 is still based on 基于 the agricultural system 农业体系 or on specific holidays 特定节日. You still engage in 参与 very communal leisure activities 公共休闲活动 like Saints' Day activities 圣徒节活动, like Carnival 狂欢节.
 +
But there is something that starts to change politically in these smaller towns now. The Catholic Church 天主教会 doesn't have the supreme authority 最高权威 that it did once have over Europe. Local governments 地方政府 have to figure out 弄清楚 how to regulate morality 规范道德 now that all of the people don't believe the same things or have the same methods of morality or follow the same canon of law 教会法规.
 +
It's up to 取决于 local governments to say, "Um, this is how we should behave. This is what we should do." They don't do a great job of it at first because it leads to 导致 just like a lot of rituals of public humiliation 公开羞辱仪式.
 +
Now, I'm sure your teacher would never do anything to publicly humiliate 公开羞辱 you in class, but you know, if the threat of public humiliation -- or putting you in stocks 颈手枷 or whipping you in public 公开鞭打 -- is what you know would happen if you didn't act a certain way, you're probably going to stay in line 遵守规定.
 +
Could you imagine how much better would you be behaved in class if you knew that your threat would be like to sit outside of the school early in the morning with your hands and your head in stocks so that people could laugh at you as they're walking by?
 +
This enforcement 执行 of communal norms 公共规范 was not only by new governmental leaders in these towns, it was also encouraged by the church.
 +
Anywho, let's end by talking about witchcraft 巫术. Pagan beliefs 异教信仰 or traditional spiritual practices 传统精神习俗 that go against 违背 what the Catholic Church had said existed in Europe for like all of its history.
 +
But due to 由于 the chaos 混乱 caused by the Protestant Reformation in Europe, people start to really strongly believe that only Christian practices -- as a Protestant or as a Catholic -- are appropriate 合适的, and that any remnants 残余 of any old pagan rituals 异教仪式 need to be expelled from 从……驱逐 the faith 信仰.
 +
And it is no coincidence 并非巧合, students, that this is happening during a time when women are fighting for more rights and when women are becoming more literate 有文化的. Because who is often accused of witchcraft?
 +
To students: a single woman who is not married, who could read and write -- she was viewed as a threat to 被视为对……的威胁 the spirituality 精神性 and the morality 道德 of Europe.
 +
Y'all, if we look at this graph 图表 right here, what do we notice about where the trials 审判 mainly happened? In Protestant lands 新教地区 -- in Germany and in Switzerland.
 +
And with more people reading the Bible, more people became aware of 意识到 this paganism 异教 or this witchcraft that existed in the Old Testament 旧约圣经 and wanted to separate themselves from 使自己与……分离 that.
 +
It is no wonder 难怪 that witchcraft accusations 巫术指控 peaked 达到顶峰 in Europe during this time of religious wars -- from the 1580s to the 1650s.
 +
That is all I will say about that, but please talk to your teacher more to have discussions in class because this is so riveting 引人入胜的.
 +
If you're still confused about the upheaval 动荡 that is happening in Europe as a result of these religious changes, check out 查看 my Ultimate Review Packet because it will have so many helpful skill sheets 技能表 and multiple choice questions 选择题 and study guides 学习指南 to help you parse it all out 梳理清楚.
 +
But as always, students, you can do it. I believe in you.
 +

'''

== 中文释义

嘿，同学们，我是艾米丽·普尔（Emily Pool）。咱们来全面聊聊16世纪的社会与政治，尤其是在"新教改革"（Protestant Reformation）之后的情况。 +

家人（这里可能是表述习惯问题，感觉“家人”在这里不太准确，不过按原文翻译），你衬衫上是什么呀？哦，谢谢提问，同学们。这是我一直以来最喜欢的画作。这是阿尔泰米西娅·真蒂莱斯基（Artemisia Gentileschi）的《朱迪斯砍下霍洛芬斯的头颅》（Judith Beheading Holofernes），而且上面写着“女孩就是女孩”，我非常喜欢这句话，因为我们今天要聊聊女性角色的转变。 +

*新教徒主张"所有信徒皆为祭司"（priesthood of all believers），然后欧洲的男人们就想：“什么？” 他们对《圣经》的解读明确显示，耶稣很重视女性，并且对待女性很好。所以现在男人们就在想：“嗯，我们也得这样做吗？这对女性的角色意味着什么呢？女性可以当传教士吗？女性现在可以接受教育吗？”* +

**关于女性的这场辩论, **是我们在研究欧洲历史时会反复提到的一个主题——说实话，在全世界的历史研究中也是如此。而且**直到今天，这仍然是一个有争议的话题。** +

但是，*尽管新教关注平等，并且新教重视以"爱"和"互补性工作"为基础的核心家庭（nuclear family），在15世纪到16世纪的欧洲，既定的性别、阶级和宗教等级制度, 基本上依然如故。* +

**尽管早期现代欧洲人以各种不同的方式, 挑战传统的权力来源，但这些既定的社会等级制度, 依然没什么变化。"土地所有权"决定财富，**而且如果你长期拥有财富，你很可能依然富有。 +

*虽然女性, 以及她们在家中的工作, 开始受到更多尊重，但她们仍然无法参与教育和政治体系。而对于普通的欧洲农民——处于社会底层的那些人——情况基本没有改变。* +

你和你的朋友们住在一个小镇上。你的日程安排仍然以农业体系或特定的节日为基础。你仍然会参与非常具有社群性质的休闲活动，比如圣徒节的活动，像狂欢节（Carnival）。 +

*但在这些小镇上，##政治方面开始有些变化。天主教会（Catholic Church）不再拥有曾经在欧洲的至高权威。既然所有人的信仰不同，道德观念不同，遵循的教会法（canon of law）也不同，地方政府就得想办法规范道德。##* +

得由地方政府来说：“嗯，这就是我们应该有的行为方式。这就是我们应该做的事情。” 一开始他们在这方面做得并不好，因为这导致了很多公开羞辱的仪式。 +

现在，我确定你们的老师绝不会在课堂上做任何公开羞辱你们的事情，但是，你懂的，如果存在公开羞辱的威胁——比如把你关在颈手枷里, 或者当众鞭打你——如果你不按某种方式行事就会这样，那你很可能会循规蹈矩。 +

你能想象吗，如果你知道如果你不遵守规定，就要一大早把手和头放在颈手枷里, 坐在学校外面，人们走过时还会嘲笑你，那你在课堂上的表现会好很多。 +

这种对社群规范的执行, 不仅来自这些小镇的新政府领导人，也得到了教会的鼓励。 +

不管怎样，我们以聊聊巫术（witchcraft）来结束今天的内容。*异教信仰（Pagan beliefs）或者传统的精神实践，这些与天主教会所说的相悖的东西, 在欧洲历史上一直存在。* +

但是由于"新教改革"在欧洲引发的混乱，人们开始强烈认为, 只有新教徒或天主教徒所践行的基督教（Christian）仪式才是合适的，任何旧的异教仪式的残余, 都需要从信仰中清除。 +

同学们，这一情况发生在女性为争取更多权利而斗争, 以及女性识字率提高的时期，这并非巧合。因为**通常被指控施行巫术的, 会是谁呢？** +
同学们，*是那些未婚的单身女性，那些会读书写字的女性——她被视为对欧洲的精神和道德的威胁。* +

大家，如果我们看看这张图表，我们会注意到, *#审判主要发生在哪里呢？在新教地区——德国（Germany）和瑞士（Switzerland）。#* +

*随着越来越多的人阅读《圣经》，越来越多的人意识到《旧约全书》中存在的异教信仰或巫术，并且想要远离它们。* +
毫不奇怪，*在16世纪80年代, 到16世纪50年代的宗教战争期间，欧洲对巫术的指控达到了顶峰。* +

关于这个问题我就说这么多，但是请和你们的老师多交流，在课堂上进行讨论，因为这真的非常引人入胜。 +
如果你们仍然对这些宗教变革在欧洲引发的动荡感到困惑，看看我的终极复习资料包，因为里面有很多有用的技能表、选择题和学习指南，能帮助你们理解这一切。 +
但是，同学们，一如既往，你们能做到的。我相信你们。 +

'''

== pure

Hey students, it's Emily Pool. Let's talk all about 16th century society and politics, especially in the wake of, you know, the Protestant Reformation.

Family, what's that on your shirt? Oh, thanks for asking, students. This is my favorite painting of all time. This is Artemisia Gentileschi's Judith Beheading Holofernes, and it says "girls will be girls" on top of it, which I love so much because we're going to talk about the shifting role of women today.

Protestants argued that there is a priesthood of all believers, and then men in Europe were like, "What?" Their reading of the Scripture is clear that Jesus valued and treated women quite well. So now men are like, "Um, do we have to do that too? What does this mean about women's roles? Can women be preachers? Can women now get educated?"

This debate about women is a theme that we will come back to over and over and over again in our study of European history -- and honestly, across the world. It is still an argument or a debate today.

But even despite the new Protestant focus on equality and the Protestant value of a nuclear family that should be rooted in love and complimentary work, established hierarchies of gender and class and religion still remained the same across Europe from the 1400s to the 1600s.

Even though early modern Europeans are challenging traditionally held sources of power in all of the different ways, these established social hierarchies are still pretty much the same. Land ownership determines wealth, and if you've had wealth for a long time, you probably still have wealth.

While women and their work at the home actually starts getting viewed with more dignity, they are still denied access from education and political systems. And for the average European peasants -- someone on that bottom rung of the social ladder -- things are still pretty much the same.

You live in a little town with all your friends. Your calendar is still based on the agricultural system or on specific holidays. You still engage in very communal leisure activities like Saints' Day activities, like Carnival.

But there is something that starts to change politically in these smaller towns now. The Catholic Church doesn't have the supreme authority that it did once have over Europe. Local governments have to figure out how to regulate morality now that all of the people don't believe the same things or have the same methods of morality or follow the same canon of law.

It's up to local governments to say, "Um, this is how we should behave. This is what we should do." They don't do a great job of it at first because it leads to just like a lot of rituals of public humiliation.

Now, I'm sure your teacher would never do anything to publicly humiliate you in class, but you know, if the threat of public humiliation -- or putting you in stocks or whipping you in public -- is what you know would happen if you didn't act a certain way, you're probably going to stay in line.

Could you imagine how much better would you be behaved in class if you knew that your threat would be like to sit outside of the school early in the morning with your hands and your head in stocks so that people could laugh at you as they're walking by?

This enforcement of communal norms was not only by new governmental leaders in these towns, it was also encouraged by the church.

Anywho, let's end by talking about witchcraft. Pagan beliefs or traditional spiritual practices that go against what the Catholic Church had said existed in Europe for like all of its history.

But due to the chaos caused by the Protestant Reformation in Europe, people start to really strongly believe that only Christian practices -- as a Protestant or as a Catholic -- are appropriate, and that any remnants of any old pagan rituals need to be expelled from the faith.

And it is no coincidence, students, that this is happening during a time when women are fighting for more rights and when women are becoming more literate. Because who is often accused of witchcraft?

To students: a single woman who is not married, who could read and write -- she was viewed as a threat to the spirituality and the morality of Europe.

Y'all, if we look at this graph right here, what do we notice about where the trials mainly happened? In Protestant lands -- in Germany and in Switzerland.

And with more people reading the Bible, more people became aware of this paganism or this witchcraft that existed in the Old Testament and wanted to separate themselves from that.

It is no wonder that witchcraft accusations peaked in Europe during this time of religious wars -- from the 1580s to the 1650s.

That is all I will say about that, but please talk to your teacher more to have discussions in class because this is so riveting.

If you're still confused about the upheaval that is happening in Europe as a result of these religious changes, check out my Ultimate Review Packet because it will have so many helpful skill sheets and multiple choice questions and study guides to help you parse it all out.

But as always, students, you can do it. I believe in you.

'''