
= AP Euro 4.1 Contextualizing the Scientific Revolution and Enlightenment
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, it's Emily P. Welcome to one of my favorite units in this course: unit four -- scientific 科学的, philosophical 哲学的, and political developments 政治发展. +

And as always, we're going to start out with a contextualization 情境化；背景化 video. Just a reminder: the AP test loves asking questions about contextualization 情境化；背景化. +

What is contextualization 情境化；背景化? You are situating 把…置于特定情境 an event in history in the context 背景；环境 in which it happens. Here's how I told my students to try to think about it: back in the day 过去 when I was growing up, I had to watch TV shows once a week. There was no Netflix, there was no binging TV  binge-watching  binge-watching指一次性观看大量剧集；追剧. +

So at the very beginning of every episode 剧集, there was a 30-second clip 片段 that was a recap 回顾；概述 of previous things that happened in this series 系列, so that when I start this new episode of TV and I see a character that I haven't seen in -- I don't know -- if we're looking at Grey's Anatomy （电视剧《实习医生格蕾》）, 17 seasons 季, then I will know immediately what's going on when I see that person because this recap thing reminded me of it. +

That is an easy way to think about contextualization 情境化；背景化. What do I need to know in my brain about the topic so that when you start talking about the topic, I'm like, "Oh yeah, obviously." +

So let us contextualize 情境化；背景化 the Scientific Revolution 科学革命 and the Enlightenment 启蒙运动. Think back way back to our first unit of study. It's 1450, and what are the Europeans very excited about? Oh, those old Greek and Roman texts 文本；文献 from antiquity 古代；古老年代. +

The rediscovery 重新发现 of those works has led to 导致 everything that we've talked about in this course so far -- directly or indirectly 直接或间接地 -- and that's definitely going to continue in unit four. +

So remember that during the Middle Ages 中世纪, the Catholic Church 天主教会 was like, "Hey Europeans, these are the things that you can and can't do regarding 关于 science." Like for example: no dissecting 解剖 or desecrating 亵渎；破坏 of a human body. Also, the Earth is at the center of the solar system 太阳系. +

Which y'all, if you just think about it -- can you feel the Earth moving right now? No, you cannot. So it makes sense 有道理；说得通. It makes sense as to why people in Europe believe that for a very long time. +

But the rediscovery 重新发现 of Greek and Roman texts 文本；文献 plus an increasingly literate 有文化的；识字的 European population 人口 means that early scientists 科学家, early thinkers 思想家, are going to start critically 批判性地 looking at math 数学, empiricism 经验主义, and the way the world works 世界运行方式. +

New ideas in science based on observation 观察 and experimentation 实验 challenged 挑战 the traditionally held view 传统观点 of the cosmos 宇宙. +

Students, it's also important to say that these early scientists 科学家 were not directly trying to challenge 挑战 the Catholic Church 天主教会. Very similar to Martin Luther here, right? He was trying to reform 改革 the Church from within 从内部. +

These early scientists 科学家 were trying to figure out 弄清楚 the intricacies 复杂细节 of how the world works 世界运行方式 because they thought that it would bring more glory to God 为上帝带来更多荣耀. The Catholic Church put Galileo on trial 审判；审讯 and called him a heretic 异教徒 and made him and all of his findings sure, but we'll get there in this unit. +

You have two major themes 主题 happening: the Scientific Revolution 科学革命 and the Enlightenment 启蒙运动, and then the impacts 影响 of those things on society 社会. +

In the Scientific Revolution 科学革命, scientists 科学家 like Galileo 伽利略 or Newton 牛顿 or Kepler 开普勒 or Vesalius 维萨里 or Harvey 哈维 are trying to figure out 弄清楚 the natural laws 自然法则 that dictate 支配；决定 the world around them. +

And in the Enlightenment 启蒙运动, these Enlightenment philosophers 启蒙哲学家 like Locke 洛克, Hobbes 霍布斯, Descartes 笛卡尔, and Rousseau 卢梭 all try to figure out 弄清楚 the natural laws 自然法则 that dictate 支配；决定 humanity 人类. +

The scientists 科学家 are like, "Why does the world act the way it does?" And these Enlightenment philosophers 启蒙哲学家 are like, "Why do people act the way that they do?" +

And both of these together lead to 导致 an increasing emphasis on 越来越重视 reason 理性 in European society 欧洲社会. And the Enlightenment 启蒙运动 specifically 特别；尤其 -- with its focus on 专注于 reason 理性, rationalism 理性主义, empiricism 经验主义 -- really continues to challenge 挑战 the role of faith 信仰的作用 in society 社会 and the role of government 政府的作用 in society 社会. +

To be outdone 不甘示弱, a group of enlightened 开明的；有见识的 economists 经济学家 called physiocrats 重农主义者 then challenge 挑战 mercantilist policies 重商主义政策. +

To summarize 总结, students: scientists 科学家 are going to challenge 挑战 the supreme power 至高权力 of the Catholic Church 天主教会 over affairs of science 科学事务. Enlightenment philosophers 启蒙哲学家 are going to challenge 挑战 the prevailing 盛行的；流行的 governmental systems 政府体制 like absolutism 专制主义 and lead to 导致 more secular 世俗的 methods of government 政府治理方式 -- and honestly, more democratic 民主的 methods of government 政府治理方式. +

We're just really anti-absolutist 反对专制主义的 at this point. And these physiocrats 重农主义者 -- these enlightened 开明的；有见识的 economists 经济学家 -- are like, "Hey uh, capitalism 资本主义? What about this thing?" +

It's a really fun unit. Make sure that you are following along 跟上进度, students. This is also a unit where you just need to memorize 记住 people. That happens very rarely 很少发生 in this course, and you will need to do it now. +

So if you need extra help with that, make sure you check out 查看 my Ultimate Review Packet 终极复习资料包 because I have the most study skills 学习技巧 for you, and you can find a link of that below. +

As always, students, you can do it. I believe in you. +

'''

== 中文释义

嘿，同学们，我是艾米丽·P。欢迎来到这门课程中我最喜欢的单元之一：第四单元——科学、哲学和政治的发展。 +

和往常一样，我们要先来看一个关于时代背景的视频。提醒一下：*AP考试很喜欢考关于时代背景的问题。* +
什么是时代背景呢？就是把一个历史事件置于它发生的背景之中。我是这样告诉我的学生去理解它的：在我小时候，我每周只能看一些电视节目。那时候没有网飞（Netflix），也不能一口气看完一部剧。 +
所以在每一集的开头，都会有一个30秒的片段，回顾这个系列之前发生的事情，这样当我开始看新的一集时，如果我看到一个角色——我不知道，就比如在《实习医生格蕾》（Grey's Anatomy）这部剧的17季里出现的角色，我看到这个角色时就能立刻知道发生了什么，因为这个回顾片段能让我想起来之前的剧情。 +

这是一种理解时代背景的简单方式。关于这个主题，我需要在脑海里知道些什么，这样当你开始谈论这个主题时，我就能反应过来，“哦，对，很明显”。 +

所以让我们来梳理一下"科学革命"（Scientific Revolution）和"启蒙运动"（Enlightenment）的时代背景。回想一下我们的第一单元。那是1450年，欧洲人对什么感到兴奋呢？哦，是古代希腊和罗马的文献。 +
这些著作的重新发现, 直接或间接地引发了我们在这门课程中讨论的所有内容，而且这种影响在第四单元还会继续。 +

所以记住，**在中世纪，天主教会（Catholic Church）会说，“嘿，欧洲人，关于科学，这些事你们能做，那些事你们不能做”。**比如说：不能解剖或亵渎人体。还有，地球是太阳系的中心。 +
大家想一想——你们现在能感觉到地球在动吗？不能，对吧。所以欧洲人在很长一段时间里相信这些是有原因的。 +

但是希腊和罗马文献的重新发现，再加上欧洲识字率的提高，意味着**早期的科学家和思想家, 开始批判性地审视数学、经验主义以及世界的运行方式。** +
*基于观察和实验的科学新思想, 挑战了传统上对宇宙的看法。* +

同学们，还有一点很重要，**这些早期的科学家并不是直接试图挑战天主教会。这和马丁·路德（Martin Luther）的情况很相似，**对吧？*他试图从教会内部进行改革。* +

这些早期的科学家, 试图弄清楚世界运行的复杂原理，因为他们认为这样做能给上帝带来更多荣耀。天主教会审判了伽利略（Galileo），称他为异教徒，并认可了他的所有发现，关于这些我们会在本单元详细讲解。 +

这里有两个主要的主题：科学革命和启蒙运动，以及这些对社会的影响。 +
**在科学革命中，**像伽利略、牛顿（Newton）、开普勒（Kepler）、维萨里（Vesalius）、哈维（Harvey）这样的**科学家试图弄清楚支配他们周围世界的自然法则。** +
**在启蒙运动中，**像洛克（Locke）、霍布斯（Hobbes）、笛卡尔（Descartes）和卢梭（Rousseau）这样的**启蒙哲学家试图弄清楚支配人类的自然法则。** +

*科学家们会思考，“为什么世界是这样运行的？” 而这些启蒙哲学家会思考，“为什么人们会这样行事？”* +

*这两者共同导致了欧洲社会对"理性"的日益重视。而启蒙运动特别强调理性、理性主义和经验主义，它真正地持续挑战着信仰在社会中的角色, 以及政府在社会中的角色。* +

随后，*一群被称为"重农主义者"（physiocrats）的开明经济学家不甘落后，他们挑战了重商主义（mercantilist）政策。* +

同学们，总结一下：科学家们挑战了天主教会在"科学事务"上的至高权力。启蒙哲学家们挑战了像专制主义（absolutism）这样的主流政府体制，并带来了更世俗化的政府治理方式——说实话，也是更民主的政府治理方式。 +
在这一点上，我们真的反对"专制主义"。而这些重农主义者——这些开明的经济学家会想，“嘿，资本主义呢？这又该怎么看呢？” +

这是一个非常有趣的单元。同学们，一定要跟上进度。在这个单元里，*你们需要记住一些人物。这在这门课程里很少见，但现在你们需要这么做。* +
所以如果在这方面需要额外的帮助，一定要查看我的终极复习资料包，因为我为你们准备了很多学习技巧，你们可以在下面找到相关链接。 +
同学们，一如既往，你们能做到的。我相信你们。 +

'''

== pure


Hey students, it's Emily P. Welcome to one of my favorite units in this course: unit four -- scientific, philosophical, and political developments.

And as always, we're going to start out with a contextualization video. Just a reminder: the AP test loves asking questions about contextualization.

What is contextualization? You are situating an event in history in the context in which it happens. Here's how I told my students to try to think about it: back in the day when I was growing up, I had to watch TV shows once a week. There was no Netflix, there was no binging TV.

So at the very beginning of every episode, there was a 30-second clip that was a recap of previous things that happened in this series, so that when I start this new episode of TV and I see a character that I haven't seen in -- I don't know -- if we're looking at Grey's Anatomy, 17 seasons, then I will know immediately what's going on when I see that person because this recap thing reminded me of it.

That is an easy way to think about contextualization. What do I need to know in my brain about the topic so that when you start talking about the topic, I'm like, "Oh yeah, obviously."

So let us contextualize the Scientific Revolution and the Enlightenment. Think back way back to our first unit of study. It's 1450, and what are the Europeans very excited about? Oh, those old Greek and Roman texts from antiquity.

The rediscovery of those works has led to everything that we've talked about in this course so far -- directly or indirectly -- and that's definitely going to continue in unit four.

So remember that during the Middle Ages, the Catholic Church was like, "Hey Europeans, these are the things that you can and can't do regarding science." Like for example: no dissecting or desecrating of a human body. Also, the Earth is at the center of the solar system.

Which y'all, if you just think about it -- can you feel the Earth moving right now? No, you cannot. So it makes sense. It makes sense as to why people in Europe believe that for a very long time.

But the rediscovery of Greek and Roman texts plus an increasingly literate European population means that early scientists, early thinkers, are going to start critically looking at math, empiricism, and the way the world works.

New ideas in science based on observation and experimentation challenged the traditionally held view of the cosmos.

Students, it's also important to say that these early scientists were not directly trying to challenge the Catholic Church. Very similar to Martin Luther here, right? He was trying to reform the Church from within.

These early scientists were trying to figure out the intricacies of how the world works because they thought that it would bring more glory to God. The Catholic Church put Galileo on trial and called him a heretic and made him and all of his findings sure, but we'll get there in this unit.

You have two major themes happening: the Scientific Revolution and the Enlightenment, and then the impacts of those things on society.

In the Scientific Revolution, scientists like Galileo or Newton or Kepler or Vesalius or Harvey are trying to figure out the natural laws that dictate the world around them.

And in the Enlightenment, these Enlightenment philosophers like Locke, Hobbes, Descartes, and Rousseau all try to figure out the natural laws that dictate humanity.

The scientists are like, "Why does the world act the way it does?" And these Enlightenment philosophers are like, "Why do people act the way that they do?"

And both of these together lead to an increasing emphasis on reason in European society. And the Enlightenment specifically -- with its focus on reason, rationalism, empiricism -- really continues to challenge the role of faith in society and the role of government in society.

To be outdone, a group of enlightened economists called physiocrats then challenge mercantilist policies.

To summarize, students: scientists are going to challenge the supreme power of the Catholic Church over affairs of science. Enlightenment philosophers are going to challenge the prevailing governmental systems like absolutism and lead to more secular methods of government -- and honestly, more democratic methods of government.

We're just really anti-absolutist at this point. And these physiocrats -- these enlightened economists -- are like, "Hey uh, capitalism? What about this thing?"

It's a really fun unit. Make sure that you are following along, students. This is also a unit where you just need to memorize people. That happens very rarely in this course, and you will need to do it now.

So if you need extra help with that, make sure you check out my Ultimate Review Packet because I have the most study skills for you, and you can find a link of that below.

As always, students, you can do it. I believe in you.

'''