
= AP Euro 1.7 Rivals on the World Stage
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, this is Emily P. Let's talk about rivals 竞争对手 on the world stage 世界舞台.
 + 
 
Columbus sailed the ocean blue in 1492, and then that set up 引发；造成 -- you know -- colonization 殖民 of the Americas. Europe is establishing overseas empires 海外帝国 not only in the Americas but also on the coast of Africa and in the Indian Ocean, and they're doing this through a lot of coercion 强迫；威压, obviously, and sometimes through negotiation 谈判.
 + 
 
Let's highlight 突出；强调 the key players 关键参与者 and also the key conflicts 冲突. Spain is the dominant 占主导地位的 empire in the Americas. They establish colonies 殖民地 in North America, in the Caribbean, and in South America. And not only that, they established a colony in the Philippines named after -- you guessed it -- Philip II, which means that they have a truly global trade network 全球贸易网络.
 + 
 
And what are they doing with the trillions of dollars in gold and silver bullion 金银条 and also actual resources that they are extracting 提取 from their colonies? Funding wars 资助战争.
 + 
 
If we're looking back at Europe, Spain is a country that is right next to Portugal on the Iberian Peninsula 伊比利亚半岛. In order to prevent conflict 防止冲突 at home, they need to come to an agreement 达成协议 on what lands they can colonize.
 + 
 
In 1494, the two countries get together and go to the pope 教皇 in the name of 以……的名义 Catholicism 天主教 and say, "Hey pope, please help us out. Help us figure out 弄清楚 what lands we can freely conquer 征服." And the pope says, "Cool," marks a line of demarcation 分界线 called the Treaty of Tordesillas 托德西利亚斯条约. Spain can colonize everything west of this line, and Portugal can colonize everything east of this line.
 + 
 
To Spanish domination 统治 in the Americas and Portuguese domination on the coast of Africa and in the Indian Ocean. But not wanting to be outdone 不甘落后, other Atlantic-based nations 大西洋沿岸国家 like France, the Netherlands, and Britain also want to get involved in 参与 trade.
 + 
 
Students, it's important to note 注意 here that power shifts 权力转移 in Europe from the Mediterranean region 地中海地区 to the Atlantic region 大西洋地区. While Italy controlled so much wealth, power, and influence in the 1400s, they're not on the Atlantic coast. So as soon as Columbus sails the ocean blue and the hemispheres 半球 are connected, those Atlantic states are the ones that emerge as 成为 the most powerful.
 + 
 
After colonies in the Americas are established by those countries, there's a lot of conflict that ensues 随之发生 to make sure that certain countries have control over 控制 certain colonies. Both the Wars of Spanish Succession 西班牙王位继承战争 and the Seven Years' War 七年战争 lead to 导致 Britain's ascendancy 优势 and control over more colonies and at the same time weaken 削弱 the power of Spain and France in North America.
 + 
 
Now let's talk about piracy 海盗行为. You imagine -- can you imagine -- the amount of wealth that is being transported via 通过 ships across the Atlantic and across the Indian Ocean and Pacific Ocean? Of course piracy is going to be rampant 猖獗的 during this time.
 + 
 
Like, the 1650s to the early 1700s is the golden age of piracy 海盗黄金时代. The most fun fact about that is that Blackbeard -- Edward Teach, maybe the pirate that you think of when you think of pirates -- owned a ship called the Queen Anne's Revenge, which was in fact 事实上 a former French enslaving ship 法国奴隶船.
 + 
 
While pirates did a lot of damage -- no denying that -- while there was lots of looting 抢劫 and stealing and negative things, I will say pirate ships tended to be more egalitarian 平等主义的. So there is at least that.
 + 
 
Anyway, I hope this helped. And as always, you can do it. I believe in you.
 + 
 

'''

== 中文释义

嘿，同学们，我是艾米丽·P（Emily P）。咱们来聊聊世界舞台上的竞争对手吧。 +

1492年哥伦布在蓝色的海洋上航行，然后，你知道的，这开启了美洲的殖民活动。欧洲不仅在美洲建立了海外帝国，还在非洲海岸和印度洋建立了海外帝国，显然，他们在很大程度上是通过强制手段来实现的，有时也会通过谈判的方式。 +

让我们来重点说说关键的参与者, 以及关键的冲突。**##西班牙（Spain）是在美洲占主导地位的帝国。##他们在北美洲、加勒比海地区和南美洲建立了殖民地。**不仅如此，**他们还在菲律宾（Philippines）建立了一个殖民地，**这个殖民地是以——你猜对了——菲利普二世（Philip II）的名字命名的，*这意味着他们拥有一个真正的全球贸易网络。* +

那么他们用从殖民地开采出的价值数万亿美元的金银条块, 以及实际的资源, 做了什么呢？用于资助战争。 +

如果我们回顾欧洲，**西班牙**是伊比利亚半岛（Iberian Peninsula）上紧邻**葡萄牙**（Portugal）的一个国家。为了避免国内的冲突，*他们需要就可以殖民的土地, 达成协议。* +

*1494年，这两个国家聚在一起，以天主教（Catholicism）的名义去见教皇，说：“嘿，教皇，请帮帮我们。帮我们确定一下我们可以自由征服哪些土地。” 教皇说：“好的。” 于是划定了一条分界线，这就是《托尔德西里亚斯条约》（Treaty of Tordesillas）。西班牙可以殖民这条线以西的所有土地，葡萄牙可以殖民这条线以东的所有土地。* +

**结果就是西班牙在美洲占据统治地位，葡萄牙在非洲海岸和印度洋占据统治地位。但是，其他以大西洋为基地的国家，如法国（France）、荷兰（the Netherlands）和英国（Britain），也不甘落后，同样想要参与到贸易中来。 +**

同学们，**这里需要重点注意的是，##欧洲的权力中心, 从地中海地区转移到了大西洋地区。虽然在15世纪时，意大利（Italy）掌控着大量的财富、权力和影响力，但它并不位于大西洋沿岸。##所以，一旦哥伦布在蓝色的海洋上航行，**两个半球被连接起来，*#那些大西洋沿岸的国家就崛起成为了最强大的国家(地理优势)。#* +

在那些国家在美洲建立殖民地之后，随之而来的是许多冲突，目的是确保某些国家能控制某些殖民地。*西班牙王位继承战争（Wars of Spanish Succession）和七年战争（Seven Years' War）都使英国（Britain）崛起并控制了更多的殖民地，同时也削弱了西班牙和法国在北美的势力。* +

现在我们来谈谈海盗行为。你想象一下——*你能想象吗——通过船只穿越大西洋、印度洋和太平洋运输的财富数量有多少？当然的，在这个时期海盗行为就会十分猖獗。* +

比如，**17世纪50年代到18世纪初是海盗的黄金时代。**关于这一点最有趣的事实是，黑胡子——爱德华·蒂奇（Edward Teach），也许当你想到海盗时就会想到他——拥有一艘名为 “安妮女王复仇号”（Queen Anne's Revenge）的船，而这艘船实际上曾经是一艘法国的奴隶运输船。 +

不可否认，海盗造成了很多破坏，他们进行了大量的掠夺和偷窃等不良行为，但我要说的是，**海盗船往往更加平等主义。**至少有这一点。 +

不管怎样，我希望这能对你有所帮助。一如既往，你能做到的。我相信你。 +

'''

== pure

Hey students, this is Emily P. Let's talk about rivals on the world stage.

Columbus sailed the ocean blue in 1492, and then that set up -- you know -- colonization of the Americas. Europe is establishing overseas empires not only in the Americas but also on the coast of Africa and in the Indian Ocean, and they're doing this through a lot of coercion, obviously, and sometimes through negotiation.

Let's highlight the key players and also the key conflicts. Spain is the dominant empire in the Americas. They establish colonies in North America, in the Caribbean, and in South America. And not only that, they established a colony in the Philippines named after -- you guessed it -- Philip II, which means that they have a truly global trade network.

And what are they doing with the trillions of dollars in gold and silver bullion and also actual resources that they are extracting from their colonies? Funding wars.

If we're looking back at Europe, Spain is a country that is right next to Portugal on the Iberian Peninsula. In order to prevent conflict at home, they need to come to an agreement on what lands they can colonize.

In 1494, the two countries get together and go to the pope in the name of Catholicism and say, "Hey pope, please help us out. Help us figure out what lands we can freely conquer." And the pope says, "Cool," marks a line of demarcation called the Treaty of Tordesillas. Spain can colonize everything west of this line, and Portugal can colonize everything east of this line.

To Spanish domination in the Americas and Portuguese domination on the coast of Africa and in the Indian Ocean. But not wanting to be outdone, other Atlantic-based nations like France, the Netherlands, and Britain also want to get involved in trade.

Students, it's important to note here that power shifts in Europe from the Mediterranean region to the Atlantic region. While Italy controlled so much wealth, power, and influence in the 1400s, they're not on the Atlantic coast. So as soon as Columbus sails the ocean blue and the hemispheres are connected, those Atlantic states are the ones that emerge as the most powerful.

After colonies in the Americas are established by those countries, there's a lot of conflict that ensues to make sure that certain countries have control over certain colonies. Both the Wars of Spanish Succession and the Seven Years' War lead to Britain's ascendancy and control over more colonies and at the same time weaken the power of Spain and France in North America.

Now let's talk about piracy. You imagine -- can you imagine -- the amount of wealth that is being transported via ships across the Atlantic and across the Indian Ocean and Pacific Ocean? Of course piracy is going to be rampant during this time.

Like, the 1650s to the early 1700s is the golden age of piracy. The most fun fact about that is that Blackbeard -- Edward Teach, maybe the pirate that you think of when you think of pirates -- owned a ship called the Queen Anne's Revenge, which was in fact a former French enslaving ship.

While pirates did a lot of damage -- no denying that -- while there was lots of looting and stealing and negative things, I will say pirate ships tended to be more egalitarian. So there is at least that.

Anyway, I hope this helped. And as always, you can do it. I believe in you.

'''