
= Unit 7 19th-Century Perspectives and Political Developments - 1
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

==== AP Euro 7.1 Contextualizing 19th-Century Perspectives and Political Developments 探究19世纪的观点和政治发展背景

Do you remember how after Napoleon tried to conquer 征服 most of Europe, Metternich got a bunch of 一群 European leaders together in 1815 at the Congress of Vienna 维也纳会议? And these conservative leaders 保守派领导人 were like, "Hey, we need to make sure that never happens again. Let's create this Concert of Europe 欧洲协调 so that one state 国家 can't become too powerful." +

Yeah, Europeans in the 1800s were like, "Nah 不, we're just pretty much gonna do whatever we want to." Sorry. +

I will say this is inspired by 受…启发 Napoleon because his conquest of Europe 对欧洲的征服 did lead to 导致 the rise of nationalism 民族主义 in most of these states. +

Italy finally is unified 统一 for the first time, and Germany is unified under Otto von Bismarck 奥托·冯·俾斯麦 and his strong Prussian military 普鲁士军队. +

And then in 1848, we have all of these revolutions 革命 that are sometimes referred to as 被称为 the "springtime of the peoples" “人民之春”. But Emily, why are revolutions happening? Because again -- of nationalism 民族主义. +

Different language groups 语言群体 and ethnic groups 族群 -- especially in Eastern Europe 东欧 -- are like, "Yeah, I don't want to be a part of this whatever empire 帝国 anymore." +

Also, all of these countries are industrialized 实现工业化, and now they're mass-producing 批量生产 weapons 武器. I wonder what's going to happen. +

==== AP Euro Topic 7.2 Nationalism 民族主义

An increase in nationalism 民族主义的增长 plays out 展现 in Europe in three important developments 发展. Let's talk about them. +

Number one: Italy is unified 统一. It starts out with 以…开始 this guy Giuseppe Mazzini 朱塞佩·马志尼 who creates the "Young Italy" “青年意大利党”. They're not super successful, but they pave the way for 为…铺平道路 this guy Camillo Cavour 卡米洛·加富尔 to be successful. Also, this guy Giuseppe Garibaldi 朱塞佩·加里波第 is important in fighting some major battles 重要战役. Or as I like to remember it -- the soul, the sword, and the mind behind Italian unification 意大利统一背后的灵魂、利剑和智慧. +

Number two: Germany is united under Otto von Bismarck 奥托·冯·俾斯麦. Bismarck -- what a guy. "Blood and Iron" 铁血政策, am I right? +

Just a reminder: Prussia industrialized before all of the other Germanic states 日耳曼国家, which means that they were the leaders in German unification 德国统一的主导力量. +

Bismarck and Cavour are great examples of realpolitik 现实政治, which basically just means realistic politics 现实政治 -- not ideological ones 意识形态政治. Let's take this back way back to Machiavelli 马基雅维利: the ends justify the means 为达目的不择手段. +

Number three: Austria-Hungary becomes a dual monarchy 二元君主国. They do this to promote political stability 政治稳定, but just a reminder -- wow, there are lots of different ethnic groups 族群 and languages within this empire 帝国. +

There's one more kind of nationalism 民族主义. Let's learn about Zionism 犹太复国主义. +

==== AP Euro Topic 7.2 Nationalism (the Dreyfus Affair) 民族主义（德雷福斯事件）

Hey, I'm going to talk about the Dreyfus Affair 德雷福斯事件. +

Alfred Dreyfus 阿尔弗雷德·德雷福斯 was a French Jewish man 法国犹太裔男子 accused of 被指控 selling military secrets 军事机密 to the German government. He was charged 起诉, and then convicted 定罪, and then sent to prison 入狱 in French Guiana 法属圭亚那 -- which is right here, by the way. +

Anyway, he didn't do it. +

This is part of the rise of anti-Semitism 反犹主义 that we see in Europe in the 1800s. Influential political leaders 有影响力的政治领导人 like Édouard Drumont 爱德华·德鲁蒙 say that to be French is to be Catholic 天主教徒. +

France, you fought so many wars in the 1500s and 1600s to fight for religious pluralism 宗教多元化. Come on. +

Great CCOT (Continuity and Change Over Time 历史延续与变迁) practice would be to look at religion in France from the 1500s to the 1900s. +

Media 媒体 gets super involved in this injustice 不公正事件, and this is also where Émile Zola 埃米尔·左拉 writes "J'accuse" 《我控诉》. +

This trial 审判 happens in 1894, but by 1906, there's a new French government. They pardoned 赦免 Dreyfus, but man -- he had just spent 10 years in prison in South America for a crime he did not commit based on falsified evidence 伪造的证据. +

The Dreyfus Affair 德雷福斯事件 increases Jewish nationalism 犹太民族主义 -- called Zionism 犹太复国主义 -- across Europe. Also leads to 导致 more liberalization 自由化 in France. +

==== AP Euro Topic 7.3 National Unification and Diplomatic Tensions 国家统一与外交紧张局势

It is the Crimean War 克里米亚战争 that breaks down 打破 this Concert of Europe 欧洲协调 and directly paves the way for 直接为…铺平道路 the unification of Germany and Italy. +

I already talked about their unification 统一, so I'm not going to do that again. Instead, I want to talk more about Bismarck 俾斯麦. +

Oh, Bismarck. You know who he really doesn't like? France. +

Bismarck creates this really interesting group of alliances 联盟 with Eastern European countries specifically in order to isolate 孤立 France. +

Also, by the way, he's like a really good military leader 军事领导人, and Germany's industrialized 工业化, and they have some intense industrial warfare 激烈的工业战争. +

He gets dismissed from power 被免职 in 1890, and that leads to 导致 a lot of tensions 紧张局势 in Europe. +

But everything's gonna be totally fine, right? Right? Right? +

I can't get ahead of myself, but there are also effects of the Crimean War on the Ottoman Empire 奥斯曼帝国. +

Inspired by 受…启发 nationalist movements 民族主义运动, these Balkan states 巴尔干国家 -- man, also want independence 独立. And I wonder if anything is gonna happen soon. +

==== AP Euro Topic 7.3 National Unification and Diplomatic Tensions (The Crimean War) 国家统一与外交紧张局势（克里米亚战争）

Talking about shifting boundaries 边界变化 in Europe in the 1800s, we have to talk about the Crimean War 克里米亚战争. +

Summarize 总结 the war: Russia wants to get involved in 介入 the Ottoman Empire, and these Eastern European countries are like, "Not allowing it." +

And which Western European powers 西欧列强 get involved to stop this? Of course, it's going to be Britain and France. +

That's also because Russia is a threat to 对…构成威胁 Austria, and Britain and France are like, "No, we can't let that happen." +

The war plays out 发生 here on the Crimean Peninsula 克里米亚半岛 -- hence 因此, Crimean War. +

Interestingly enough 有趣的是, Austria doesn't actually get involved in this conflict 冲突. So it's Britain, France, and the Ottoman Empire that take on 对抗 Russia. +

A really terrible siege 围攻 at a place called Sevastopol 塞瓦斯托波尔 that causes the deaths of over a hundred thousand people. +

So within the Crimean War, that Florence Nightingale 弗洛伦斯·南丁格尔 starts to do radical changes 彻底变革 to healthcare 医疗保健 -- like, I don't know, clean linens 干净的床单 -- as a response to Sevastopol. +

Alfred Lord Tennyson 阿尔弗雷德·丁尼生 writes "The Charge of the Light Brigade" 《轻骑兵的冲锋》, which is like a hymn to nationalism 民族主义赞歌 -- no matter what the outcome is. +

So Tsar Alexander II 沙皇亚历山大二世 ends the war with a peace 签订和平协议, and then allows him to push for 推动 reforms 改革 for modernization 现代化 in Russia. +

==== AP Euro Topic 7.4 Darwinism, Social Darwinism 达尔文主义, 社会达尔文主义

So I've talked at length about 详细谈论 how political nationalism 政治民族主义 is on the rise 兴起 in Europe in the 1800s, and now it's time to talk about like social pride nationalism 社会优越感民族主义. +

Charles Darwin 查尔斯·达尔文 publishes his book "On the Origin of Species" 《物种起源》, and wow does that change things. +

It's all about evolution 进化 and the development of human species 人类物种发展, but then this English philosopher 哲学家 Herbert Spencer 赫伯特·斯宾塞 takes it to a whole new level 提升到全新高度. +

Herbert Spencer is the guy who is credited with 因…而受到赞誉 coining the term 创造术语 "survival of the fittest" “适者生存”. +

He looks at the world -- he's English, remember -- and says, "Wow, yeah, England's on the top because we deserve to be here, and we have done everything right. And civilizations that have fallen behind 落后 deserve the fact that they have fallen behind because they are not fit enough to be where we are." +

This becomes social Darwinism 社会达尔文主义, which becomes justification for 为…提供依据 all of the racist ideologies 种族主义意识形态 in the 1800s and 1900s -- which also paves the way for 为…铺平道路 imperialism 帝国主义. +

==== AP Euro Topic 7.5 The Age of Progress and Modernity 进步与现代性时代

A lot of upheavals 动荡 in Europe in the 1800s -- a lot of revolutions 革命, whether that's industrial 工业的 or political 政治的. +

Let's talk about scientific and intellectual changes 科学和知识变革. +

Positivism 实证主义 is the idea that science alone provides objective knowledge 客观知识 about the world. Only objects verifiable by the senses 可通过感官验证的事物 can exist. +

But then, because the world is changing drastically 剧烈地 and in a very short period of time, some scientists and philosophers say, "You can't actually know anything about the world." +

This idea is called new relativism 新相对主义. +

Friedrich Nietzsche 弗里德里希·尼采 -- what a mustache 小胡子 -- writes a book called "God is Dead" 《上帝已死》. He believes that quote, "The belief in the Christian God has become unbelievable." +

Freud 弗洛伊德 is all like, "Id 本我, ego 自我, subconscious 潜意识, conscious 意识." He says that behavior is motivated by 由…驱动 unconscious desires and urges 无意识的欲望和冲动. +

And Einstein 爱因斯坦 is like, "Well, here's my theory of relativity 相对论. Can we really know anything about the universe?" +

Science is now characterized by 以…为特征 irrationality 非理性 and impulse 冲动, and boy does this pave the way for 为…铺平道路 the Age of Anxiety 焦虑时代. +

==== AP Euro Topic 7.6 New Imperialism - Motivations and Methods 新帝国主义 - 动机与方法

In 1884, King Leopold II of Belgium 比利时国王利奥波德二世 hosts a conference 召开会议 in which other European leaders sit down, look at a map of Africa, and then divide it up 瓜分. +

This is called the Berlin Conference 柏林会议, and this is the signal of 标志着 new imperialism 新帝国主义. +

Needing to fuel 推动 their Industrial Revolution 工业革命, these European states just carve up 瓜分 other parts of the world. +

Like colonization 殖民 in the 1500s, this new imperialism is also fueled by 由…推动 gold, glory, and God -- except for this time, it's gold in the form of raw resources 原材料 to fuel their Industrial Revolution, glory in the form of nationalism 民族主义, and God in the form of Protestant missionaries 新教传教士. +

Inspired by 受…启发 racist ideology 种族主义意识形态 -- thanks, Herbert Spencer -- and also poems like "The White Man's Burden" 《白人的负担》 -- thanks, Rudyard Kipling 鲁德亚德·吉卜林 -- these European colonizers 殖民者 seek to 试图 go bring civilization to 带来文明 other parts of the world -- mainly Africa and Asia. +

Also, because a lot of these European countries have industrialized 工业化, they have access to 拥有 things like advanced weaponry 先进武器 and also quinine 奎宁. +

And imperialism has atrocious effects 恶劣影响 on the colonized lands 殖民地. +

==== AP Euro Topic 7.7 Imperialism's Global Effects 帝国主义的全球影响

So Europe has industrialized 工业化 and then imperialized 帝国主义化. By the way, imperialism 帝国主义 means relating to an empire or empire-building 与帝国或建立帝国相关. +

And yes, this leads to 导致 tension 紧张局势 among European states because they're all fighting for 争夺 this balance of power 权力平衡. +

But I mainly want to talk about how imperialized places resist 反抗 European rule 统治. +

Let's start in Africa because -- like, by the way -- when Europeans looked at this map of Africa in order to carve it up 瓜分, they neglected 忽视 -- I don't know -- the thousands of different linguistic and ethnic groups 语言和族群 that existed there. +

The Zulu under Shaka Zulu 沙卡·祖鲁领导下的祖鲁人 valiantly resist 英勇抵抗 British imperialism 英国帝国主义 but are ultimately unsuccessful 最终失败. +

China's also partitioned 被瓜分 -- kind of into spheres of influence 势力范围 -- after the Opium Wars 鸦片战争, which leads to 导致 the Boxer Rebellion 义和团运动, in which the Chinese try to expel 驱逐 the "white devils" “洋鬼子”. +

An event called -- depending on the text you read -- the Sepoy Rebellion 印度土兵起义 or the Sepoy Mutiny 印度土兵兵变 again against British rule, but it is ultimately unsuccessful, and this leads to 导致 the British Raj 英属印度 in India. +

Japan and the Meiji Restoration 明治维新 decides to modernize 现代化 from within 从内部 rather than 而不是 having a Western European country come and do it for them -- to death and sadness. +

==== AP Euro Topic 7.8 19th-Century Culture and Arts 19世纪的文化与艺术

After industrialization 工业化 and imperialism 帝国主义, Europeans are like, "Oh, um, maybe progress like isn't great." +

Religion says that truth comes from God. The Enlightenment 启蒙运动 says that truth comes from reason 理性. And the Romantic Movement 浪漫主义运动 says that truth comes from emotion 情感. +

And romantic art 浪漫主义艺术 reflects 反映 that. +

As a response to 作为对…的回应 the Enlightenment and to industrialization, we see this focus on 关注 nature and landscapes 自然和风景 and this idea of like emotional longing 情感渴望. +

I mean, come on -- we have an industrial tugboat 工业拖船 pulling back in a famous old British ship to go back to shore 靠岸, and the sun is setting 日落. +

This doesn't only happen in visual art 视觉艺术. It also happens in literature 文学. +

"Les Misérables" 《悲惨世界》 is actually about the July Revolution 七月革命 in 1830, which is what this picture is about. But come on -- "Liberty Leading the People" 《自由引导人民》. Liberty -- an idea, a philosophy 哲学 -- leading the people. +

Realism 现实主义 also emerges 出现 -- again, ordinary people doing ordinary things 普通人做普通事. +

And we also see the beginnings of 开始出现 abstract modern art 抽象现代艺术 -- so going from the objective 客观 to the subjective 主观 and the rise of cubism 立体主义 and abstract art 抽象艺术. +

'''

== 中文释义

====  AP欧洲历史 7.1 19世纪视角与政治发展的背景梳理

你还记得**拿破仑试图征服欧洲大部分地区失败后，梅特涅**（Metternich）在1815年把一群欧洲领导人召集到维也纳会议（Congress of Vienna）上吗？这些保守派领导人**说：“嘿，我们得确保那种情况不再发生。我们建立"欧洲协调"（Concert of Europe）吧，这样就不会有一个国家变得过于强大。 (势力均衡政策)”** +
是的，19世纪的欧洲人却说：“不，我们基本上想做什么就做什么。” 不好意思。 +

我得说这受到了**拿破仑**的启发，因为**他对欧洲的征服, 确实导致了大多数这些国家"民族主义"的兴起。** +
意大利终于首次实现了统一，德国在奥托·冯·俾斯麦（Otto von Bismarck）和他强大的普鲁士军队的领导下实现了统一。 +

然后在1848年，发生了一系列革命，这些革命有时被称为 “人民之春”。但是，艾米丽，为什么会发生革命呢？因为同样是民族主义的原因。 +
不同的语言群体和民族群体——尤其是在东欧——说：“是的，我不想再成为这个帝国的一部分。” +

而且，所有这些国家都实现了工业化，现在他们在大规模生产武器。我很好奇会发生什么。 +

====  AP欧洲历史主题 7.2 民族主义

**民族主义的增强, 在欧洲表现为三个重要的发展。**我们来谈谈这些发展。 +

**第一：意大利实现了统一。**这始于朱塞佩·马志尼（Giuseppe Mazzini）创建了 “青年意大利”（Young Italy）。他们没有取得巨大成功，但为卡米洛·加富尔（Camillo Cavour）的成功铺平了道路。此外，朱塞佩·加里波第（Giuseppe Garibaldi）在一些重大战役中发挥了重要作用。或者，就像我记住的那样——意大利统一背后的灵魂、利剑和智慧。 +

**第二：德国在奥托·冯·俾斯麦的领导下实现了统一。**俾斯麦——真是个人物。“铁血政策”，我说得对吧？ +
提醒一下：*普鲁士比其他所有日耳曼国家都率先实现了工业化，这意味着他们是"德国统一"进程的领导者。* +

**俾斯麦和加富尔是"现实政治"（realpolitik）的绝佳例子，"现实政治"基本上意味着"现实主义的政治"——而非"意识形态上的政治"(即"现实主义"是充满灵活性的, 而不会被意识形态所牵绊, 不会为了意识形态打肿脸充胖子让自己利益受损)。让我们追溯到马基雅维利（Machiavelli）：为达目的，不择手段。 **+

**第三：奥匈帝国成为了"二元君主国"。**他们这样做是为了促进政治稳定，但提醒一下——哇，这个帝国内部有很多不同的民族群体和语言。 +

还有一种民族主义。我们来了解一下"犹太复国主义"（Zionism）。 +

====  AP欧洲历史主题 7.2 民族主义（德雷福斯事件）

嘿，我要谈谈"德雷福斯事件"（Dreyfus Affair）。 +
阿尔弗雷德·德雷福斯（Alfred Dreyfus）是一位法国犹太人，他被指控向德国政府出售军事机密。他被起诉、定罪，然后被送往"法属圭亚那"（French Guiana）的监狱——顺便说一下，就在这里。 +
不管怎样，他没有做这件事。 +

这是19世纪欧洲"反犹主义"兴起的一部分。像爱德华·德吕蒙（Édouard Drumont）这样有影响力的政治领导人说，身为法国人就应该是天主教徒。 +
*法国，你在16世纪和17世纪打了那么多仗来争取"宗教多元化"。* 拜托。 +

很好的 “比较、关联和时间跨度分析”（CCOT，Comparison, Contextualization, and Continuity and Change over Time）练习, 是研究19世纪到20世纪法国的宗教情况。 +

媒体深度参与了这一不公正事件，而且埃米尔·左拉（Émile Zola）还为此写下了《我控诉》（"J'accuse"）。 +
这场审判发生在1894年，但到了1906年，法国有了新政府。他们赦免了德雷福斯，但是天哪——他因为莫须有的罪名, 在南美洲的监狱里待了10年，证据都是伪造的。 +

德雷福斯事件增强了欧洲各地的"犹太民族主义"——也就是"犹太复国主义"。这也导致了法国更多的自由化。 +

====  AP欧洲历史主题 7.3 国家统一与外交紧张局势

克里米亚战争（Crimean War）打破了"欧洲协调"，直接为德国和意大利的统一铺平了道路。 +
我已经讲过它们的统一了，所以我不再重复。相反，我想多谈谈俾斯麦。 +

哦，俾斯麦。你知道他非常不喜欢谁吗？法国。 +
**俾斯麦与东欧国家建立了非常有趣的联盟，就是为了孤立法国。 **+
另外，顺便说一下，他是个非常出色的军事领导人，而且德国实现了工业化，他们经历了激烈的工业战争。 +
他在1890年被罢黜，这导致了欧洲的很多紧张局势。 +

但一切都会好起来的，对吧？对吧？ +
我不能说得太超前，但**克里米亚战争, 对奥斯曼帝国（Ottoman Empire）也有影响。** +
*受到民族主义运动的启发，这些巴尔干国家*——天哪，**也想要独立。**我很好奇很快会发生什么事。 +

====  AP欧洲历史主题 7.3 国家统一与外交紧张局势（克里米亚战争）

谈到19世纪欧洲的边界变化，我们必须谈谈**克里米亚战争。** +
*总结一下这场战争：俄罗斯想要插手奥斯曼帝国的事务，而这些东欧国家说：“不允许这样。”* +

*哪些西欧强国参与进来阻止这件事呢？当然是英国和法国。 +
这也是因为俄罗斯对奥地利构成了威胁，英国和法国说：“不，我们不能让这种情况发生。”* +
战争在克里米亚半岛（Crimean Peninsula）上展开——因此叫克里米亚战争。 +

有趣的是，奥地利实际上没有参与这场冲突。所以是英国、法国和奥斯曼帝国, 对抗俄罗斯。 +
在塞瓦斯托波尔（Sevastopol）发生了一场非常惨烈的围攻，导致超过10万人死亡。 +

*在克里米亚战争期间，弗洛伦斯·南丁格尔（Florence Nightingale）对医疗保健进行了彻底的改革*——比如，我不知道，清洁的床单——作为对塞瓦斯托波尔事件的回应。 +

阿尔弗雷德·丁尼生勋爵（Alfred Lord Tennyson）写下了《轻骑兵的冲锋》（"The Charge of the Light Brigade"），这就像是一首民族主义的赞歌——不管结果如何。 +
所以沙皇亚历山大二世（Tsar Alexander II）以和平结束了战争，然后推动了俄罗斯的现代化改革。 +

====  AP欧洲历史主题 7.4 达尔文主义、社会达尔文主义

我已经详细讲述了19世纪欧洲政治民族主义的兴起，现在是时候谈谈社会自豪感民族主义了。 +

查尔斯·达尔文（Charles Darwin）出版了他的《物种起源》（"On the Origin of Species"），哇，这改变了很多事情。 +
这本书讲的是进化和人类物种的发展，但是后来英国哲学家赫伯特·斯宾塞（Herbert Spencer）把它提升到了一个全新的高度。 +

赫伯特·斯宾塞是创造了 “适者生存” 这个词的人。 +
他审视世界——记住他是英国人——然后说：“哇，是的，英国处于领先地位，因为我们理应如此，我们做的一切都是正确的。而那些落后的文明活该落后，因为他们不够强大，无法达到我们的高度。” +

这就产生了**"社会达尔文主义"，这为19世纪和20世纪的所有"种族主义"意识形态,提供了正当理由——这也为"帝国主义"铺平了道路。** +

====  AP欧洲历史主题 7.5 进步与现代性的时代

*19世纪的欧洲发生了很多动荡——很多革命，无论是工业革命还是政治革命。* +

我们来谈谈科学和知识方面的变化。 +
*#"实证主义"（Positivism）认为，只有科学才能提供关于世界的客观知识。只有能被感官验证的事物才存在。#* +
但是，由于世界在很短的时间内发生了巨大的变化，*一些科学家和哲学家说：“实际上，我们对世界一无所知。” 这种观点被称为"新相对主义"（new relativism）。* +

弗里德里希·尼采（Friedrich Nietzsche）——他那胡子太有个性了——写了一本书叫《上帝已死》（"God is Dead"）。他认为，引用他的话来说，“对基督教上帝的信仰, 已经变得不可信了。” +
弗洛伊德（Freud）一直在说：“本我、自我、潜意识、意识。” 他说"行为是由无意识的欲望和冲动驱动的"。 +
而爱因斯坦（Einstein）说：“嗯，这是我的相对论。我们真的能了解宇宙的一切吗？” +

科学现在的特点是不合理性和冲动，而且天哪，这为焦虑时代（Age of Anxiety）的到来铺平了道路。 +

====  AP欧洲历史主题 7.6 新帝国主义——动机与手段

1884年，比利时国王利奥波德二世（King Leopold II）主持了一次会议，其他欧洲领导人坐在一起，看着非洲地图，然后瓜分了非洲。 +
这次会议被称为柏林会议（Berlin Conference），这标志着"新帝国主义"的开始。 +
为了推动工业革命，这些欧洲国家分割了世界其他地区。 +

*就像16世纪的殖民活动一样，"新帝国主义"也是由黄金、荣耀和上帝推动的——只不过这一次，黄金是以"原材料"的形式来推动工业革命，荣耀是以"民族主义"的形式存在，而上帝是以"新教传教士"的形式出现。* +

受到种族主义意识形态的启发——感谢赫伯特·斯宾塞——以及像《白人的负担》（"The White Man's Burden"）这样的诗歌的影响——感谢鲁德亚德·吉卜林（Rudyard Kipling）——这些欧洲殖民者试图将文明带到世界其他地方——主要是非洲和亚洲。 +
而且，因为很多这些欧洲国家实现了工业化，他们拥有先进的武器，也有奎宁。 +

帝国主义对"被殖民的土地(国家)", 产生了极其恶劣的影响。 +

====  AP欧洲历史主题 7.7 帝国主义的全球影响

欧洲实现了工业化，然后进行了帝国主义扩张。顺便说一下，帝国主义意味着与帝国或建立帝国相关的行为。 +
是的，这导致了欧洲各国之间的紧张关系，因为他们都在争夺权力平衡。 +

但我主要想谈谈, 被殖民地区是如何反抗欧洲统治的。 +
我们从非洲开始讲起，因为——顺便说一下——当欧洲人看着非洲地图进行瓜分的时候，他们忽略了——我不知道——那里存在的成千上万不同的语言群体,和民族群体。 +

在沙卡·祖鲁（Shaka Zulu）领导下的祖鲁人勇敢地反抗英国的帝国主义统治，但最终失败了。 +
中国也被分割——在鸦片战争后，中国被划分为势力范围——这导致了义和团运动（Boxer Rebellion），中国人试图驱逐 “洋鬼子”。 +
有一个事件——根据你阅读的文本不同——被称为"印度土兵起义"（Sepoy Rebellion）或"印度土兵兵变"（Sepoy Mutiny），这也是反抗英国统治的起义，但最终失败了，这导致了英国在印度的殖民统治（British Raj）。 +

日本通过明治维新（Meiji Restoration）决定从内部实现"现代化"，而不是让西欧国家来为他们做这件事——这是件好事。 +

====  AP欧洲历史主题 7.8 19世纪的文化与艺术

在工业化和帝国主义之后，欧洲人说：“哦，嗯，也许进步并不总是那么好。” +
宗教认为"真理来自上帝"。启蒙运动认为"真理来自理性"。而浪漫主义运动（Romantic Movement）认为"真理来自情感"。 +
浪漫主义艺术反映了这一点。 +

**作为对**启蒙运动和**工业化的回应，我们看到人们关注自然和风景，以及情感渴望的理念。(回归山水田园的心灵寄托?)** +
我的意思是，拜托——我们看到一艘工业拖船拖着一艘著名的旧英国船只回到岸边，太阳正在落山。 +

这种情况不仅出现在视觉艺术中。在文学作品中也有体现。 +
《悲惨世界》（"Les Misérables"）实际上是关于1830年七月革命（July Revolution）的，这幅画描绘的也是这个。但是拜托——《自由引导人民》（"Liberty Leading the People"）。自由——一种理念，一种哲学——引导着人民。 +
现实主义（Realism）也出现了——同样，描绘普通人做着普通的事情。 +

*我们也看到了抽象现代艺术的开端——所以从"客观"转向"主观"，立体主义（cubism）和抽象艺术兴起了。* +


'''

== pure

==== AP Euro 7.1 Contextualizing 19th-Century Perspectives and Political Developments

Do you remember how after Napoleon tried to conquer most of Europe, Metternich got a bunch of European leaders together in 1815 at the Congress of Vienna? And these conservative leaders were like, "Hey, we need to make sure that never happens again. Let's create this Concert of Europe so that one state can't become too powerful."

Yeah, Europeans in the 1800s were like, "Nah, we're just pretty much gonna do whatever we want to." Sorry.

I will say this is inspired by Napoleon because his conquest of Europe did lead to the rise of nationalism in most of these states.

Italy finally is unified for the first time, and Germany is unified under Otto von Bismarck and his strong Prussian military.

And then in 1848, we have all of these revolutions that are sometimes referred to as the "springtime of the peoples." But Emily, why are revolutions happening? Because again -- of nationalism.

Different language groups and ethnic groups -- especially in Eastern Europe -- are like, "Yeah, I don't want to be a part of this whatever empire anymore."

Also, all of these countries are industrialized, and now they're mass-producing weapons. I wonder what's going to happen.

==== AP Euro Topic 7.2 Nationalism

An increase in nationalism plays out in Europe in three important developments. Let's talk about them.

Number one: Italy is unified. It starts out with this guy Giuseppe Mazzini who creates the "Young Italy." They're not super successful, but they pave the way for this guy Camillo Cavour to be successful. Also, this guy Giuseppe Garibaldi is important in fighting some major battles. Or as I like to remember it -- the soul, the sword, and the mind behind Italian unification.

Number two: Germany is united under Otto von Bismarck. Bismarck -- what a guy. "Blood and Iron," am I right?

Just a reminder: Prussia industrialized before all of the other Germanic states, which means that they were the leaders in German unification.

Bismarck and Cavour are great examples of realpolitik, which basically just means realistic politics -- not ideological ones. Let's take this back way back to Machiavelli: the ends justify the means.

Number three: Austria-Hungary becomes a dual monarchy. They do this to promote political stability, but just a reminder -- wow, there are lots of different ethnic groups and languages within this empire.

There's one more kind of nationalism. Let's learn about Zionism.

==== AP Euro Topic 7.2 Nationalism (the Dreyfus Affair)

Hey, I'm going to talk about the Dreyfus Affair.

Alfred Dreyfus was a French Jewish man accused of selling military secrets to the German government. He was charged, and then convicted, and then sent to prison in French Guiana -- which is right here, by the way.

Anyway, he didn't do it.

This is part of the rise of anti-Semitism that we see in Europe in the 1800s. Influential political leaders like Édouard Drumont say that to be French is to be Catholic.

France, you fought so many wars in the 1500s and 1600s to fight for religious pluralism. Come on.

Great CCOT practice would be to look at religion in France from the 1500s to the 1900s.

Media gets super involved in this injustice, and this is also where Émile Zola writes "J'accuse."

This trial happens in 1894, but by 1906, there's a new French government. They pardoned Dreyfus, but man -- he had just spent 10 years in prison in South America for a crime he did not commit based on falsified evidence.

The Dreyfus Affair increases Jewish nationalism -- called Zionism -- across Europe. Also leads to more liberalization in France.

==== AP Euro Topic 7.3 National Unification and Diplomatic Tensions

It is the Crimean War that breaks down this Concert of Europe and directly paves the way for the unification of Germany and Italy.

I already talked about their unification, so I'm not going to do that again. Instead, I want to talk more about Bismarck.

Oh, Bismarck. You know who he really doesn't like? France.

Bismarck creates this really interesting group of alliances with Eastern European countries specifically in order to isolate France.

Also, by the way, he's like a really good military leader, and Germany's industrialized, and they have some intense industrial warfare.

He gets dismissed from power in 1890, and that leads to a lot of tensions in Europe.

But everything's gonna be totally fine, right? Right? Right?

I can't get ahead of myself, but there are also effects of the Crimean War on the Ottoman Empire.

Inspired by nationalist movements, these Balkan states -- man, also want independence. And I wonder if anything is gonna happen soon.

==== AP Euro Topic 7.3 National Unification and Diplomatic Tensions (The Crimean War)

Talking about shifting boundaries in Europe in the 1800s, we have to talk about the Crimean War.

Summarize the war: Russia wants to get involved in the Ottoman Empire, and these Eastern European countries are like, "Not allowing it."

And which Western European powers get involved to stop this? Of course, it's going to be Britain and France.

That's also because Russia is a threat to Austria, and Britain and France are like, "No, we can't let that happen."

The war plays out here on the Crimean Peninsula -- hence, Crimean War.

Interestingly enough, Austria doesn't actually get involved in this conflict. So it's Britain, France, and the Ottoman Empire that take on Russia.

A really terrible siege at a place called Sevastopol that causes the deaths of over a hundred thousand people.

So within the Crimean War, that Florence Nightingale starts to do radical changes to healthcare -- like, I don't know, clean linens -- as a response to Sevastopol.

Alfred Lord Tennyson writes "The Charge of the Light Brigade," which is like a hymn to nationalism -- no matter what the outcome is.

So Tsar Alexander II ends the war with a peace, and then allows him to push for reforms for modernization in Russia.

==== AP Euro Topic 7.4 Darwinism, Social Darwinism

So I've talked at length about how political nationalism is on the rise in Europe in the 1800s, and now it's time to talk about like social pride nationalism.

Charles Darwin publishes his book "On the Origin of Species," and wow does that change things.

It's all about evolution and the development of human species, but then this English philosopher Herbert Spencer takes it to a whole new level.

Herbert Spencer is the guy who is credited with coining the term "survival of the fittest."

He looks at the world -- he's English, remember -- and says, "Wow, yeah, England's on the top because we deserve to be here, and we have done everything right. And civilizations that have fallen behind deserve the fact that they have fallen behind because they are not fit enough to be where we are."

This becomes social Darwinism, which becomes justification for all of the racist ideologies in the 1800s and 1900s -- which also paves the way for imperialism.

==== AP Euro Topic 7.5 The Age of Progress and Modernity

A lot of upheavals in Europe in the 1800s -- a lot of revolutions, whether that's industrial or political.

Let's talk about scientific and intellectual changes.

Positivism is the idea that science alone provides objective knowledge about the world. Only objects verifiable by the senses can exist.

But then, because the world is changing drastically and in a very short period of time, some scientists and philosophers say, "You can't actually know anything about the world."

This idea is called new relativism.

Friedrich Nietzsche -- what a mustache -- writes a book called "God is Dead." He believes that quote, "The belief in the Christian God has become unbelievable."

Freud is all like, "Id, ego, subconscious, conscious." He says that behavior is motivated by unconscious desires and urges.

And Einstein's like, "Well, here's my theory of relativity. Can we really know anything about the universe?"

Science is now characterized by irrationality and impulse, and boy does this pave the way for the Age of Anxiety.

==== AP Euro Topic 7.6 New Imperialism - Motivations and Methods

In 1884, King Leopold II of Belgium hosts a conference in which other European leaders sit down, look at a map of Africa, and then divide it up.

This is called the Berlin Conference, and this is the signal of new imperialism.

Needing to fuel their Industrial Revolution, these European states just carve up other parts of the world.

Like colonization in the 1500s, this new imperialism is also fueled by gold, glory, and God -- except for this time, it's gold in the form of raw resources to fuel their Industrial Revolution, glory in the form of nationalism, and God in the form of Protestant missionaries.

Inspired by racist ideology -- thanks, Herbert Spencer -- and also poems like "The White Man's Burden" -- thanks, Rudyard Kipling -- these European colonizers seek to go bring civilization to other parts of the world -- mainly Africa and Asia.

Also, because a lot of these European countries have industrialized, they have access to things like advanced weaponry and also quinine.

And imperialism has atrocious effects on the colonized lands.

==== AP Euro Topic 7.7 Imperialism's Global Effects

So Europe has industrialized and then imperialized. By the way, imperialism means relating to an empire or empire-building.

And yes, this leads to tension among European states because they're all fighting for this balance of power.

But I mainly want to talk about how imperialized places resist European rule.

Let's start in Africa because -- like, by the way -- when Europeans looked at this map of Africa in order to carve it up, they neglected -- I don't know -- the thousands of different linguistic and ethnic groups that existed there.

The Zulu under Shaka Zulu valiantly resist British imperialism but are ultimately unsuccessful.

China's also partitioned -- kind of into spheres of influence -- after the Opium Wars, which leads to the Boxer Rebellion, in which the Chinese try to expel the "white devils."

An event called -- depending on the text you read -- the Sepoy Rebellion or the Sepoy Mutiny again against British rule, but it is ultimately unsuccessful, and this leads to the British Raj in India.

Japan and the Meiji Restoration decides to modernize from within rather than having a Western European country come and do it for them -- to death and sadness.

==== AP Euro Topic 7.8 19th-Century Culture and Arts

After industrialization and imperialism, Europeans are like, "Oh, um, maybe progress like isn't great."

Religion says that truth comes from God. The Enlightenment says that truth comes from reason. And the Romantic Movement says that truth comes from emotion.

And romantic art reflects that.

As a response to the Enlightenment and to industrialization, we see this focus on nature and landscapes and this idea of like emotional longing.

I mean, come on -- we have an industrial tugboat pulling back in a famous old British ship to go back to shore, and the sun is setting.

This doesn't only happen in visual art. It also happens in literature.

"Les Misérables" is actually about the July Revolution in 1830, which is what this picture is about. But come on -- "Liberty Leading the People." Liberty -- an idea, a philosophy -- leading the people.

Realism also emerges -- again, ordinary people doing ordinary things.

And we also see the beginnings of abstract modern art -- so going from the objective to the subjective and the rise of cubism and abstract art.

'''