
= AP Euro 2.3 Protestant Reform Continues
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey students, it's Emily P. Let's talk about the continuation 延续 of the Protestant Reformation 新教改革.
 +
So in my last video, I left us on a cliffhanger 悬念, and I said, "Students, I wonder if this new Christian denomination 基督教教派 is going to lead to any conflict 冲突 in Europe." And y'all, yes, of course it does.
 +
Martin Luther published his 95 Theses 九十五条论纲 and then was brought before Pope Leo the 10th at the Diet of Worms 沃尔姆斯议会 -- or the Diet of Worms if you want to be specific about it. Pope Leo the 10th is like, "Martin Luther, what you're saying is terrible. You must recant 撤回；放弃 all of it, and then we can go back to being a normal, religiously unified 宗教统一的 Europe."
 +
Martin Luther said, "I will not recant. Here I stand." And then Pope Leo the 10th was like, "Great, you're excommunicated 逐出教会的." Excommunicated in the Catholic Church means that you are no longer allowed to participate in 参与 any church sacrament 圣礼 at all. But that didn't matter to Martin Luther because he did not recognize the authority 权威 of the Catholic Church over any of those sacraments.
 +
After this, Martin Luther is secluded away 隐居 into a castle in Germany, where he then translates the entire New Testament 新约圣经 into German. Then the German Peasants' War 德国农民战争 breaks out 爆发.
 +
Peasants 农民 were tired of being oppressed 压迫 by the wealthy nobility 贵族 in Germany and also by the clergy 神职人员, who they started to view as corrupt 腐败的. The peasants, as a result, started to fight against 反抗 the clergy and the nobility, and they thought that they had Martin Luther's support. But Luther was like, "No, no. At the end of the day 归根结底, Christians should still submit to 服从 the rulers, even if the rulers are corrupt."
 +
And in a very interesting turn of events 事件转折, Martin Luther then actually encouraged 鼓励 the nobility to crush 镇压 this German peasant revolution 革命, which means the major effect of the German Peasants' War is that the nobility gained a lot of power and influence 影响力 in Germany, and Germany then became solidified 巩固 as a Lutheran Protestant land 路德宗新教地区.
 +
About 100,000 peasants died in the German Peasants' War, and after it ends, Martin Luther then goes back to his work of translating the Bible from Latin 拉丁语 into the German vernacular 德语白话, which he finishes the Old Testament 旧约圣经 in 1534.
 +
It is because of the printing press 印刷机 that the Protestant Reformation was as successful as it was. And since the Renaissance 文艺复兴, the populace 民众 was already more literate 有文化的. The printing presses popped up 出现 everywhere in Europe, and people were pretty eager to 渴望 read the Bible on their own -- especially if it meant maybe weakening 削弱 the power of the Catholic Church.
 +
But let's continue this conflict in Germany. In the middle of the 1500s, these German princes 诸侯 that had been mobilized 动员 after their win of the German Peasants' War got into conflict with 与……发生冲突 Charles I, the Habsburg leader 哈布斯堡王朝领袖, who was very staunchly 坚定地 Catholic 天主教徒.
 +
A religious civil war 宗教内战 breaks out in Germany between the Protestants 新教徒 and the Catholics 天主教徒, and what you need to know about this, students, is that it ends in 1555 with Charles I signing the Peace of Augsburg 奥格斯堡和约.
 +
The Peace of Augsburg was the first example in Western Europe of establishing religious pluralism 宗教多元主义, which means that two religions can coexist 共存 at the same time, and it is up to 取决于 the leader of that specific area to determine if he wants his people to be Lutheran 路德宗信徒 or Roman Catholic 罗马天主教徒.
 +
Because everyone disagreed with Calvin at this point -- don't forget about those Anabaptists 再洗礼派. What radicals 激进分子.
 +
Speaking of 说到 Calvin, here's where some political differences emerge 出现 between Luther and Calvin. Luther believed that the church should be subordinate to 从属于 the state 国家, which means that Luther said, "Hey, we still need to recognize the political authority 政治权威 that people have over the church. The government should still exist and should be separate."
 +
Calvin, on the other hand 另一方面, said that the government should just be the church, and they should be one and the same 完全相同. And actually, the best form of government is a theocracy 神权政治. It is the duty 职责 of the Calvinists 加尔文主义者 to Christianize 使基督教化 the state through laws.
 +
Not even half a century after the Protestant Reformation began with Martin Luther in 1517, religious wars and conflicts are breaking out across Europe.
 +
If we think back to what I told you my overarching thesis 总体论点 was for this entire time period -- that early modern Europeans are challenging 挑战 traditionally held sources of power 传统权力来源 in a bunch of different ways -- if we're looking at the Protestant Reformation, these new Protestants are, yes, challenging the religious power of the Catholic Church, but they are also challenging political power and the power of any kind of authority 权威.
 +
And we see this with Puritans 清教徒 in England and Huguenots -- AKA 又名 French Calvinists 法国加尔文主义者 -- in France. Y'all, it is about to get bloody 血腥的 in this class.
 +
But to end on somewhat of a positive note 以积极的内容结束, I got to talk about the Polish-Lithuanian Commonwealth 波兰立陶宛联邦 because that is weirdly 奇怪地 a thing I think about too much, and I think it stands as a good testament to 证明 what's happening in Eastern Europe.
 +
While religious wars are plaguing 困扰 Western Europe, in 1573, the Polish-Lithuanian Commonwealth passes 通过 the Act of the Warsaw Confederation 华沙联盟协约, which establishes the freedom of religion 宗教自由 for anyone within their lands. And I mean anyone.
 +
I'm not only talking about Catholics and Lutherans and Calvinists and Anabaptists. I'm also talking about Jews 犹太人 and Muslims 穆斯林. Now, you might be thinking, "Yeah, Emily, that makes sense. Of course, people should be able to practice whatever faith they want to." Y'all, not in the 1500s across the world.
 +
So shout out to 为……欢呼 this often neglected 被忽视的 empire that I actually don't think is brought up at all in your AP Euro curriculum 课程, but you're welcome for now knowing about it.
 +
Next time, we're going to talk a ton about religious wars. And as always, students, you can do it. I believe in you.
 +

'''

== 中文释义

嘿，同学们，我是艾米丽·P。咱们来聊聊新教改革的延续吧。 +

在上一个视频里，我给大家留了个悬念，我说：“同学们，我想知道**这个新的基督教教派是否会在欧洲引发冲突呢？” **大家，*没错，它当然引发冲突了。* +

马丁·路德发表了他的《九十五条论纲》，然后在沃尔姆斯帝国议会（Diet of Worms）上被带到了教皇利奥十世（Pope Leo the 10th）面前——要是说得具体点，就是沃尔姆斯帝国议会。教皇利奥十世说：“马丁·路德，你说的话太糟糕了。你必须撤回你说的所有内容，这样我们才能让欧洲恢复到正常的、宗教统一的状态。” +

马丁·路德说：“我不会撤回。我就站在这里。” 然后教皇利奥十世说：“很好，你被逐出教会了。” *在天主教会里，被逐出教会, 意味着你再也不被允许参与任何教会圣礼。但这对马丁·路德来说并不重要，因为他不承认天主教会对任何圣礼的权威。* +

在这之后，马丁·路德隐居到了德国的一座城堡里，在那里他把整部《新约全书》翻译成了德语。接着，德国农民战争（German Peasants' War）爆发了。 +

农民们受够了德国富有的贵族, 以及他们认为腐败的神职人员的压迫。结果，农民们开始反抗神职人员和贵族，他们认为自己得到了马丁·路德的支持。但路德说：“不，不。归根结底，基督徒仍然应该服从统治者，即使统治者是腐败的。” +

接着发生了一个非常有趣的转折，*马丁·路德实际上鼓励贵族镇压这次德国农民起义。这意味着德国农民战争的主要影响, 是贵族在德国获得了大量的权力和影响力，并且德国由此巩固成为了一个信奉"路德宗"的新教国家。* +

大约有十万农民死于德国农民战争。战争结束后，马丁·路德又回去继续他把《圣经》从拉丁语翻译成德语方言的工作，并在1534年完成了《旧约全书》的翻译。 +

**正是因为有了印刷机，"新教改革"才取得了如此的成功。**而且自从文艺复兴以来，民众的识字率已经提高了。*#印刷机在欧洲各地纷纷出现，人们非常渴望自己阅读《圣经》——特别是如果这意味着有可能削弱天主教会的权力的话。#* +

但让我们继续说说德国的这场冲突。在16世纪中期，*那些在德国农民战争中取得胜利后, 被动员起来的德国诸侯，与坚定信奉天主教的哈布斯堡王朝（Habsburg）领袖查理一世（Charles I）发生了冲突。* +

**一场新教徒和天主教徒之间的宗教内战, 在德国爆发了。**同学们，关于这场战争你们需要知道的是，*它在1555年以查理一世签署《奥格斯堡和约》（Peace of Augsburg）而告终。* +

*#《奥格斯堡和约》是西欧建立宗教多元主义的第一个例子，这意味着两种宗教可以同时共存，并且由特定地区的领袖, 来决定他的人民是信奉路德宗, 还是罗马天主教。#* +

因为在这个时候, 每个人都不同意加尔文的观点——别忘了那些再洗礼派。他们可真是激进分子。 +

说到加尔文，**#这里体现出"路德"和"加尔文"之间在政治观点上的一些差异。路德认为"教会应该从属于国家"，#**也就是说路德说：“嘿，我们仍然需要承认人们对教会的政治权威。#*政府应该继续存在，并且应该与教会分离。*#” +

*#另一方面，加尔文说"政府就应该是教会"，它们应该是一体的。实际上，最好的政府形式是神权政治。加尔文主义者的职责, 是通过法律让国家基督教化。#* +

*在1517年马丁·路德开启"新教改革"后还不到半个世纪，宗教战争和冲突就在整个欧洲爆发了。* +

如果回想一下我告诉过你们的关于这个时期的总体论点——*#早期现代欧洲人正在以各种不同的方式, 挑战传统的权力来源——如果看看新教改革，这些新的新教徒确实在挑战天主教会的宗教权力，但他们也在挑战政治权力, 以及任何形式的权威。#* +

我们在英国的清教徒（Puritans）和法国的胡格诺派（Huguenots，也就是法国加尔文主义者）身上, 看到了这一点。大家，这门课接下来的内容会涉及到血腥的历史事件哦。 +

但以一个稍微积极点的内容来结尾吧，我得说说波兰立陶宛联邦（Polish-Lithuanian Commonwealth），因为这是一件我经常过多思考的事情，而且我认为它很好地证明了东欧正在发生的事情。 +

*##当宗教战争困扰着西欧的时候，在1573年，波兰立陶宛联邦通过了《华沙联盟法案》（Act of the Warsaw Confederation），该法案确立了其境内所有人的宗教信仰自由。##我说的是所有人*。 +

我所说的不仅仅是天主教徒、路德宗信徒、加尔文主义者和再洗礼派。我还包括犹太人和穆斯林。*现在，你们可能会想：*“是的，艾米丽，这说得通。*当然，人们应该能够自由信仰他们想信的宗教。” 大家，在16世纪的世界可不是这样。* +

所以我要特别提一下这个经常被忽视的帝国，实际上我觉得在AP欧洲历史课程里根本没提到过它，但现在你们知道了，不用谢哦。 +

下次，我们会大量讨论宗教战争。同学们，一如既往，你们能做到的。我相信你们。 +

'''

== pure


Hey students, it's Emily P. Let's talk about the continuation of the Protestant Reformation.

So in my last video, I left us on a cliffhanger, and I said, "Students, I wonder if this new Christian denomination is going to lead to any conflict in Europe." And y'all, yes, of course it does.

Martin Luther published his 95 Theses and then was brought before Pope Leo the 10th at the Diet of Worms -- or the Diet of Worms if you want to be specific about it. Pope Leo the 10th is like, "Martin Luther, what you're saying is terrible. You must recant all of it, and then we can go back to being a normal, religiously unified Europe."

Martin Luther said, "I will not recant. Here I stand." And then Pope Leo the 10th was like, "Great, you're excommunicated." Excommunicated in the Catholic Church means that you are no longer allowed to participate in any church sacrament at all. But that didn't matter to Martin Luther because he did not recognize the authority of the Catholic Church over any of those sacraments.

After this, Martin Luther is secluded away into a castle in Germany, where he then translates the entire New Testament into German. Then the German Peasants' War breaks out.

Peasants were tired of being oppressed by the wealthy nobility in Germany and also by the clergy, who they started to view as corrupt. The peasants, as a result, started to fight against the clergy and the nobility, and they thought that they had Martin Luther's support. But Luther was like, "No, no. At the end of the day, Christians should still submit to the rulers, even if the rulers are corrupt."

And in a very interesting turn of events, Martin Luther then actually encouraged the nobility to crush this German peasant revolution, which means the major effect of the German Peasants' War is that the nobility gained a lot of power and influence in Germany, and Germany then became solidified as a Lutheran Protestant land.

About 100,000 peasants died in the German Peasants' War, and after it ends, Martin Luther then goes back to his work of translating the Bible from Latin into the German vernacular, which he finishes the Old Testament in 1534.

It is because of the printing press that the Protestant Reformation was as successful as it was. And since the Renaissance, the populace was already more literate. The printing presses popped up everywhere in Europe, and people were pretty eager to read the Bible on their own -- especially if it meant maybe weakening the power of the Catholic Church.

But let's continue this conflict in Germany. In the middle of the 1500s, these German princes that had been mobilized after their win of the German Peasants' War got into conflict with Charles I, the Habsburg leader, who was very staunchly Catholic.

A religious civil war breaks out in Germany between the Protestants and the Catholics, and what you need to know about this, students, is that it ends in 1555 with Charles I signing the Peace of Augsburg.

The Peace of Augsburg was the first example in Western Europe of establishing religious pluralism, which means that two religions can coexist at the same time, and it is up to the leader of that specific area to determine if he wants his people to be Lutheran or Roman Catholic.

Because everyone disagreed with Calvin at this point -- don't forget about those Anabaptists. What radicals.

Speaking of Calvin, here's where some political differences emerge between Luther and Calvin. Luther believed that the church should be subordinate to the state, which means that Luther said, "Hey, we still need to recognize the political authority that people have over the church. The government should still exist and should be separate."

Calvin, on the other hand, said that the government should just be the church, and they should be one and the same. And actually, the best form of government is a theocracy. It is the duty of the Calvinists to Christianize the state through laws.

Not even half a century after the Protestant Reformation began with Martin Luther in 1517, religious wars and conflicts are breaking out across Europe.

If we think back to what I told you my overarching thesis was for this entire time period -- that early modern Europeans are challenging traditionally held sources of power in a bunch of different ways -- if we're looking at the Protestant Reformation, these new Protestants are, yes, challenging the religious power of the Catholic Church, but they are also challenging political power and the power of any kind of authority.

And we see this with Puritans in England and Huguenots -- AKA French Calvinists -- in France. Y'all, it is about to get bloody in this class.

But to end on somewhat of a positive note, I got to talk about the Polish-Lithuanian Commonwealth because that is weirdly a thing I think about too much, and I think it stands as a good testament to what's happening in Eastern Europe.

While religious wars are plaguing Western Europe, in 1573, the Polish-Lithuanian Commonwealth passes the Act of the Warsaw Confederation, which establishes the freedom of religion for anyone within their lands. And I mean anyone.

I'm not only talking about Catholics and Lutherans and Calvinists and Anabaptists. I'm also talking about Jews and Muslims. Now, you might be thinking, "Yeah, Emily, that makes sense. Of course, people should be able to practice whatever faith they want to." Y'all, not in the 1500s across the world.

So shout out to this often neglected empire that I actually don't think is brought up at all in your AP Euro curriculum, but you're welcome for now knowing about it.

Next time, we're going to talk a ton about religious wars. And as always, students, you can do it. I believe in you.



'''