
= AP Euro 3.6 Balance of Power
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey AP Euro students, it's Emily P. Let's talk all about topic 3.6: the balance of power 权力平衡. +

This is a theme 主题 that will come up 出现 over and over again 反复地 in every subsequent 随后的 unit in European history, and it happens for one specific reason. But before I get there, let's define 定义 what it is. +

I need you to think about the United States. You know how we are all neighbors with each other, and all of the states might have some differences but all ultimately 最终地 work together for the common good 共同利益 because we're part of the same country? That does not exist in Europe. +

Like, if Texas -- where I'm from -- were to take over 接管 Oklahoma, it would not be good for people in Oklahoma. So in Europe, in this continent 大陆 where there are different independent nations 独立国家 and states, they need to make sure that not one nation is getting too powerful -- to tip the scales 打破平衡 and then conquer 征服 the rest of everyone else. +

And yeah, you might be thinking, "Uh, Emily, but I know history, and I know that that has happened with Napoleon and also Hitler." You'd be right. But there are many times in which European states 欧洲国家 have worked together to try to stop that from happening. +

That's the description 描述. That's the definition 定义. So why does it happen in topic three? Why is it happening in the 1600s and 1700s? +

The military revolution 军事革命 happened. Remember that Thirty Years' War 三十年战争? And remember this guy named Gustavus Adolphus, the king of Sweden 瑞典国王? He radically 彻底地 transforms 变革 military techniques 军事技术 with things like mobile cannons 移动火炮 and new firearms 新式火器 and strategic military strategies 战略性军事策略. +

Countries that are able to marshal 集结；统领 a sufficient amount of 足够数量的 people or technology to support this new military are going to very quickly dominate 主导 other countries that haven't been able to do that. Sweden under Gustavus Adolphus undergoes 经历；遭受 the military revolution 军事革命, and then that is followed actually relatively quickly by France. +

States 国家 who are run by an absolute monarch 专制君主 develop this military revolution prior to 在…之前 other states. First off 首先, you have the ability to do whatever you want to do, and also you're taxing people 向人民征税 and raising money 筹集资金 which you can now use to fund 为…提供资金 a standing army 常备军. +

And if you have an absolute monarch 专制君主, you kind of have a lot of people at your disposal 在你支配下 in your bureaucracy 官僚机构 and the people who work for you, so you can just tell them, "Hey, do this thing for me," and they'll do it -- or else 否则, you know, they might die. +

Back to the Thirty Years' War 三十年战争. The Peace of Westphalia 威斯特伐利亚和约 -- which ends the Thirty Years' War, which I say over and over again in my videos because it is so important because it will show up on your AP test probably in multiple ways -- it is a marker date 标志性日期 for a reason. +

It signals 标志；预示 the end of religious warfare 宗教战争 in Europe. But now instead of religious conflict 宗教冲突, states 国家 are more concerned about 更关注 the fact that other people maybe have more political or military power 政治或军事权力, and that is going to lead to 导致 conflict 冲突. +

Three examples of the importance of a balance of power 权力平衡 in unit three: +

Number one: Louis XIV 路易十四 -- with his, you know, new military revolution 军事革命 that he has brought to France -- fights in so many wars just around France, a lot of which he loses, that it forces a coalition of powers 权力联盟 to join against him. +

A great example of how the balance of power 权力平衡 works, right? One state 国家 is getting too strong. In order to prevent 阻止 that state from getting as strong as it could be or taking over nearby lands 附近土地, you have a group of people joining together to say, "Hey, whoa whoa whoa, stop that." +

This happens in France. This also happens in Sweden against Gustavus Adolphus. Peter the Great of Russia 俄国彼得大帝 in the Great Northern War 大北方战争 joins a coalition of 联合 nearby countries to stop Sweden's growing power 瑞典日益增长的势力. +

In both of these instances 情况；事例 -- in the west and in the east -- neighboring countries 邻国 are trying to limit 限制 the growing power of a nearby country in order to protect themselves militarily 军事上, sure, but also to protect themselves politically and economically 政治和经济上. +

In this video, I will talk about the two neglected 被忽视的 children of the AP European History course 欧洲历史课程: the Ottoman Empire 奥斯曼帝国 and the Polish-Lithuanian Commonwealth 波兰立陶宛联邦. +

The Ottoman Empire -- is it Europe, is it not Europe? Because boy, do they exist in a lot of southeastern Europe 东南欧. But because of their cultural differences 文化差异 and religious differences 宗教差异, they're kind of like a shoe-in 稳当入选者 in this course. +

The Ottoman Empire in the 1500s and the 1600s is trying to grow its influence 扩大影响力 in western Europe 西欧, and both times are stopped at battles of Vienna 维也纳战役. Now, the various Habsburg kings 哈布斯堡王朝的各位国王 and Poland -- might I say -- joined together to fend off 抵御 this advancing Ottoman Empire 前进中的奥斯曼帝国. +

Y'all, this is just a fun fact: have we seen the Lord of the Rings movies? Aragorn comes back on the third day, and he looks up and he sees the hill, and like everyone's running down the hill like they kill everyone. Tolkien literally got that story from the Battle of Kahlenberg Mountain 卡伦山战役, which was the single moment in which the Ottomans were turned back 击退 just outside of Vienna. +

It is in 1683 that the Ottoman Empire stops their expansion 扩张 into Europe and stays really where they were at that time, which is modern-day Balkan Peninsula 现代巴尔干半岛. +

Now on to the Polish-Lithuanian Commonwealth 波兰立陶宛联邦, which I love so much. Just reminder 提醒, students: the Act of the Warsaw Confederation 华沙联盟法案 in 1573 granted 授予 religious toleration 宗教宽容 not only to Protestants 新教徒 and to Catholics 天主教徒 and to Anabaptists 再洗礼派教徒, but also to Jews 犹太人 and Muslims 穆斯林 within. We love it so much. +

Now, the Polish-Lithuanian Commonwealth 波兰立陶宛联邦 was not a monarchy 君主制国家. Rather 相反, they were elected representatives 民选代表 ruling on behalf of 代表, you know, the 10 million people who lived within their empire. +

So its governance 治理 as a confederation 联邦 of elected nobility 当选贵族 was more similar to 与…更相似 what is going on in the Dutch Republic 荷兰共和国 than anything else in Europe at the time. Because they were religiously tolerant 宗教宽容的, they didn't get involved in 卷入 the Thirty Years' War 三十年战争 -- because why would you need to go to war over religion 如果我们允许人们自由信仰宗教 if we just allow people to practice the religion that they want to practice? +

In European history, they did not have a military revolution 军事革命, and their lack of 缺乏 an absolute monarchy 专制君主制 and that decentralized power 权力分散 -- which didn't work well for them by the 1700s -- led to 导致 their partition 瓜分 by their stronger neighboring states 更强大的邻国: Prussia 普鲁士, Russia 俄国, and Austria 奥地利. +

Three partitions of Poland 波兰的三次瓜分 from 1772 to 1795 essentially 实质上 wipe Poland off of the European map 从欧洲版图上抹去 for a long time. And then honestly, Poland has a real bad go 经历艰难时期 in history after this until 1989. But we'll get to Lech Wałęsa 莱赫·瓦文萨 and the Solidarity movement 团结工会运动 later. +

So to summarize 总结 the key highlights 要点 in this topic in European history: a balance of power 权力平衡 is when countries try to make sure that their neighbors are not getting too strong and powerful 过于强大. +

And these countries are getting strong and powerful because they're undergoing 经历 military revolutions 军事革命. And those countries that don't undergo military revolutions -- like Poland -- get partitioned 瓜分 or divided 分割 by their stronger neighbors. +

I hope that helped, and if you need any extra help, make sure that you check out 查看 all of my YouTube videos, find me on TikTok, and you know, check out my Ultimate Review Packet 终极复习资料包. +

As always, students, you can do it. I believe in you. +

'''

== 中文释义

嘿，AP欧洲历史课程的同学们，我是艾米丽·P。咱们来全面聊聊主题3.6：*权力平衡*（the balance of power）。 +

这是一个会在欧洲历史后续每个单元中反复出现的主题，它的出现是有特定原因的。但在我阐述原因之前，咱们先给它下个定义。 +

我希望你们想想美国。你们知道我们彼此都是邻国，而且各个州可能存在一些差异，但最终都为了共同利益而合作，因为我们同属一个国家吧？但在欧洲情况并非如此。 +

打个比方，如果得克萨斯州——我来自那里——要接管俄克拉荷马州，这对俄克拉荷马州的人来说可不是好事。所以**#在欧洲#，在这个由不同独立国家和州组成的大陆上，#他们需要确保没有一个国家变得过于强大——强大到足以改变力量平衡并征服其他国家。(势力均衡政策, 避免垄断, 一家独大, 变成中国一样的独裁君主制)#** +

没错，你们可能会想，“呃，艾米丽，但我了解历史，我知道**拿破仑和希特勒就曾试图这么做。**” 你们说得对。但在很多时候，*欧洲各国也曾共同努力阻止这种情况发生。* +

以上就是对**"权力平衡"**的描述和定义。那么为什么它会出现在第三单元呢？*为什么它会在17世纪和18世纪出现呢？* +
因为**军事革命（military revolution）发生了 (科技造成了各国实力的不平衡, 科技强国更容易吞并科技弱国, 独裁帝制化)。**还记得三十年战争（Thirty Years' War）吗？还有瑞典国王古斯塔夫·阿道夫（Gustavus Adolphus）？他用移动大炮、新型火器和战略性军事策略, 从根本上改变了军事技术。 +
**那些能够动员足够人力或技术, 来支持这种新军事变革的国家，会迅速地统治那些无法做到这一点的国家。**在古斯塔夫·阿道夫统治下的瑞典, 经历了军事革命，随后法国也相对迅速地跟上了。 +

*由"绝对君主"统治的国家, 比其他国家更早地开展了军事革命 (先不说效率, 但集权国家, 有条件来集中力量办大事)。首先，你有权力做任何你想做的事，而且你可以向人民征税并筹集资金，这些钱可以用来建立常备军。* +
如果你有一个绝对君主，在你的官僚体系中，有很多人可供你差遣，为你工作，所以你可以告诉他们，“嘿，帮我做这件事”，他们就会去做——否则，你懂的，他们可能会被处死。 +

回到三十年战争。**#《威斯特伐利亚和约》（Peace of Westphalia）——它结束了三十年战争，#**我在视频里反复提到它，因为它的后果意义非常重要，它很可能会以多种形式出现在你们的AP考试中——它成为一个标志性日期是有原因的。 +
*##它标志着欧洲"宗教战争"的结束。##但##现在，虽然宗教冲突结束了，但各国更担心的是其他国家可能拥有更多的政治或军事权力，##而这将导致冲突。* +

第三单元中, "权力平衡"重要性的三个例子：

第一：路易十四（Louis XIV）——他将新的军事革命引入法国——在法国周边打了很多战争，而且很多战争他都输了，这迫使一些国家联合起来对抗他。 +
这是"权力平衡"如何起作用的一个很好的例子，对吧？*一个国家变得过于强大。为了阻止这个国家变得更加强大或接管周边土地，一群国家联合起来说，“嘿，等等，停下。”* +

这种情况在法国发生了。在瑞典对抗古斯塔夫·阿道夫时也发生了。在大北方战争（Great Northern War）中，*俄罗斯的彼得大帝（Peter the Great）联合周边国家, 来阻止瑞典日益增长的势力。* +

在这两种情况下——在西方和东方——*#邻国试图限制附近国家不断增长的势力，这既是为了在军事上保护自己，也是为了在政治和经济上保护自己。#* +

在这个视频里，我要讲讲AP欧洲历史课程中被忽视的两个对象：奥斯曼帝国（the Ottoman Empire）和波兰立陶宛联邦（the Polish-Lithuanian Commonwealth）。 +

**奥斯曼帝国——它算欧洲国家吗？**因为，天哪，**他们在欧洲东南部占据了很大一片土地。但由于文化和宗教差异，**在这门课程里，*他们有点像个特殊存在。* +
*在16世纪和17世纪，奥斯曼帝国试图扩大其在西欧的影响力，但两次都在"维也纳之战"中受阻。当时，哈布斯堡王朝（Habsburg）的各位国王和波兰——我得说——联合起来抵御奥斯曼帝国的推进。* +

大家，这里有个有趣的事实：你们看过《指环王》（Lord of the Rings）系列电影吗？阿拉贡（Aragorn）在第三天回来，他抬头看到山丘，然后所有人冲下山去，把敌人都消灭了。托尔金（Tolkien）的这个故事其实源于"卡伦山战役"（Battle of Kahlenberg Mountain），在那场战役中，奥斯曼帝国在维也纳城外被击退。 +

*1683年，奥斯曼帝国停止了对欧洲的扩张，并且停留在了当时的领土上，也就是现代的巴尔干半岛（Balkan Peninsula）。* +

现在来说说我非常喜欢的**"波兰立陶宛联邦"。**同学们，提醒一下：*1573年的《华沙联盟法案》*（Act of the Warsaw Confederation）不仅**给予**新教徒、天主教徒和再洗礼派（Anabaptists）宗教宽容，也给予犹太人和穆斯林**宗教宽容。**我们太喜欢这一点了。 +

**波兰立陶宛联邦不是"君主制国家"。相反，他们是由选举出来的代表,来统治，**代表着帝国内的1000万人民。 +

*所以，##它作为一个由选举出来的贵族组成的联邦，其治理方式与当时欧洲其他国家不同，反而更类似于荷兰共和国（Dutch Republic）的治理方式。##因为他们实行宗教宽容政策，所以没有卷入三十年战争*——如果我们允许人们信仰他们想信的宗教，那为什么要为宗教而战呢？ +

*在欧洲历史上，#(波兰)他们没有经历军事革命，而且由于没有绝对君主，权力分散——到18世纪，这种情况对他们很不利——这导致他们被更强大的邻国普鲁士（Prussia）、俄罗斯和奥地利瓜分。#* +

从1772年到1795年，**波兰被三次瓜分，这使得波兰在很长一段时间内从欧洲地图上消失了。**说实话，在那之后，波兰在历史上一直命运坎坷，直到1989年。但我们之后会讲到莱赫·瓦文萨（Lech Wałęsa）和"团结工联运动"（Solidarity movement）。 +

所以总结一下欧洲历史上这个主题的重点："权力平衡"是指各国试图确保邻国不会变得过于强大。 +
*而这些国家变得强大, 是因为他们经历了军事革命。那些没有经历军事革命的国家——比如波兰——会被更强大的邻国瓜分。* +

希望这对你们有帮助，如果你们需要额外的帮助，一定要看看我在YouTube上的所有视频，在TikTok上找到我，还有，看看我的终极复习资料包。 +
同学们，一如既往，你们能做到的。我相信你们。 +

'''

== pure

Hey AP Euro students, it's Emily P. Let's talk all about topic 3.6: the balance of power.

This is a theme that will come up over and over again in every subsequent unit in European history, and it happens for one specific reason. But before I get there, let's define what it is.

I need you to think about the United States. You know how we are all neighbors with each other, and all of the states might have some differences but all ultimately work together for the common good because we're part of the same country? That does not exist in Europe.

Like, if Texas -- where I'm from -- were to take over Oklahoma, it would not be good for people in Oklahoma. So in Europe, in this continent where there are different independent nations and states, they need to make sure that not one nation is getting too powerful -- to tip the scales and then conquer the rest of everyone else.

And yeah, you might be thinking, "Uh, Emily, but I know history, and I know that that has happened with Napoleon and also Hitler." You'd be right. But there are many times in which European states have worked together to try to stop that from happening.

That's the description. That's the definition. So why does it happen in topic three? Why is it happening in the 1600s and 1700s?

The military revolution happened. Remember that Thirty Years' War? And remember this guy named Gustavus Adolphus, the king of Sweden? He radically transforms military techniques with things like mobile cannons and new firearms and strategic military strategies.

Countries that are able to marshal a sufficient amount of people or technology to support this new military are going to very quickly dominate other countries that haven't been able to do that. Sweden under Gustavus Adolphus undergoes the military revolution, and then that is followed actually relatively quickly by France.

States who are run by an absolute monarch develop this military revolution prior to other states. First off, you have the ability to do whatever you want to do, and also you're taxing people and raising money which you can now use to fund a standing army.

And if you have an absolute monarch, you kind of have a lot of people at your disposal in your bureaucracy and the people who work for you, so you can just tell them, "Hey, do this thing for me," and they'll do it -- or else, you know, they might die.

Back to the Thirty Years' War. The Peace of Westphalia -- which ends the Thirty Years' War, which I say over and over again in my videos because it is so important because it will show up on your AP test probably in multiple ways -- it is a marker date for a reason.

It signals the end of religious warfare in Europe. But now instead of religious conflict, states are more concerned about the fact that other people maybe have more political or military power, and that is going to lead to conflict.

Three examples of the importance of a balance of power in unit three:

Number one: Louis XIV -- with his, you know, new military revolution that he has brought to France -- fights in so many wars just around France, a lot of which he loses, that it forces a coalition of powers to join against him.

A great example of how the balance of power works, right? One state is getting too strong. In order to prevent that state from getting as strong as it could be or taking over nearby lands, you have a group of people joining together to say, "Hey, whoa whoa whoa, stop that."

This happens in France. This also happens in Sweden against Gustavus Adolphus. Peter the Great of Russia in the Great Northern War joins a coalition of nearby countries to stop Sweden's growing power.

In both of these instances -- in the west and in the east -- neighboring countries are trying to limit the growing power of a nearby country in order to protect themselves militarily, sure, but also to protect themselves politically and economically.

In this video, I will talk about the two neglected children of the AP European History course: the Ottoman Empire and the Polish-Lithuanian Commonwealth.

The Ottoman Empire -- is it Europe, is it not Europe? Because boy, do they exist in a lot of southeastern Europe. But because of their cultural differences and religious differences, they're kind of like a shoe-in in this course.

The Ottoman Empire in the 1500s and the 1600s is trying to grow its influence in western Europe, and both times are stopped at battles of Vienna. Now, the various Habsburg kings and Poland -- might I say -- joined together to fend off this advancing Ottoman Empire.

Y'all, this is just a fun fact: have we seen the Lord of the Rings movies? Aragorn comes back on the third day, and he looks up and he sees the hill, and like everyone's running down the hill like they kill everyone. Tolkien literally got that story from the Battle of Kahlenberg Mountain, which was the single moment in which the Ottomans were turned back just outside of Vienna.

It is in 1683 that the Ottoman Empire stops their expansion into Europe and stays really where they were at that time, which is modern-day Balkan Peninsula.

Now on to the Polish-Lithuanian Commonwealth, which I love so much. Just reminder, students: the Act of the Warsaw Confederation in 1573 granted religious toleration not only to Protestants and to Catholics and to Anabaptists, but also to Jews and Muslims within. We love it so much.

Now, the Polish-Lithuanian Commonwealth was not a monarchy. Rather, they were elected representatives ruling on behalf of, you know, the 10 million people who lived within their empire.

So its governance as a confederation of elected nobility was more similar to what is going on in the Dutch Republic than anything else in Europe at the time. Because they were religiously tolerant, they didn't get involved in the Thirty Years' War -- because why would you need to go to war over religion if we just allow people to practice the religion that they want to practice?

In European history, they did not have a military revolution, and their lack of an absolute monarchy and that decentralized power -- which didn't work well for them by the 1700s -- led to their partition by their stronger neighboring states: Prussia, Russia, and Austria.

Three partitions of Poland from 1772 to 1795 essentially wipe Poland off of the European map for a long time. And then honestly, Poland has a real bad go in history after this until 1989. But we'll get to Lech Wałęsa and the Solidarity movement later.

So to summarize the key highlights in this topic in European history: a balance of power is when countries try to make sure that their neighbors are not getting too strong and powerful.

And these countries are getting strong and powerful because they're undergoing military revolutions. And those countries that don't undergo military revolutions -- like Poland -- get partitioned or divided by their stronger neighbors.

I hope that helped, and if you need any extra help, make sure that you check out all of my YouTube videos, find me on TikTok, and you know, check out my Ultimate Review Packet.

As always, students, you can do it. I believe in you.


'''