= 005 How to Write a DBQ： Using the Documents (2020 APUSH exam)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What's up, beautiful people? Today we're gonna take a look at 审视；考察 the DBQ (Document-Based Question) for your AP (Advanced Placement) history class. In particular 特别地；尤其, we are gonna focus on 集中于；专注于 using the documents. Now I know you're wondering 纳闷；想知道 how do I get points, and I'm gonna show you how to use the documents, but I'm gonna try to keep the rubric 评分标准 talk to an absolute minimum 绝对最小值 here. This stuff can make you go crazy (非正式)发疯. If you're worried about how many documents you need to use or how many documents you need to do the HIPPO (Historical Context 历史背景, Intended Audience 预期读者, Purpose 目的, Point of View 观点, Organization 组织) thing with, go into the description 描述 and click the link for the rubric video which will break it all down 分解；解析. This video is just about how in the heck (非正式)究竟；到底 you should approach 处理；对待 the documents and use them in your essay. And in my experience 经验, this is what messes with (非正式)妨碍；干扰 most students and their ability 能力 to do well on the DBQ.

With that being said 说了这么多, quick check of the rubric language: You will get a point if you use the content 内容 of the document to address 处理；应对 the topic of the prompt 提示；题目. And what this really means is in your essay you describe 描述；描写 the document in your writing. You break down 分解；解析 what the document is saying, what the document is about, but you don't really connect it to 与…联系；与…相关 any argument 论点；观点. So this is really basic 基本的；基础的, and you can't get a point for doing this. The next part of the rubric is really using the documents to support 支持；支撑 or advance 推进；促进 your argument. This is where you are using the documents as evidence 证据. You're not just describing 描述；描写 or interpreting 解释；说明 the document -- you're doing something useful 有用的 with the document and showing the reader how it proves your thesis 论文；论点.

Another part of the rubric that's linked to 与…相连 the documents is the HIPPO point or the deeper analysis 分析；研究 point. We're not going to go into extreme detail 极端细节 on the extended analysis 扩展分析, but just know that we're gonna make some references 提及；参考 to this part of the rubric. And then finally 最后；终于, stuff that's not directly 直接地 connected to 与…相连 a document -- using outside information and complex 复杂的 understanding 理解；明白 -- can also be achieved 实现 during your analysis and your use of documents. So we'll touch on 涉及；提及 that in just a moment.

So we're gonna use this prompt 提示；题目 as our sample prompt, and for the purposes of 为了…的目的 keeping this video as short as possible, we're going to imagine 想象 that we only have three documents to look at 审视；考察. Now up until 直到…为止 this point, you haven't actually 实际上；事实上 looked at 审视；考察 the documents. You've done all of the things in the black right there -- it took about 大约 two to three minutes. You don't want to spend too much time on this. But now it's time to go on an adventure 冒险 and find us some evidence 证据 and interpret 解释；说明 some documents.

Now before 在…之前 we actually 实际上；事实上 do this, I want to give you a quick little checklist 清单 of what I think you should do as you approach 处理；对待 each document. So the first thing is to source 标明来源 the document. Does the name of the author 作者, the date, the context 背景 of the document, title 标题 of the document ring any bells 使人想起什么? Jot it down 匆匆记下 in the margins 页边空白 if that will help you out. Then you want to quickly 迅速地 read and annotate 注释；评注 the document. Now focus on 集中于；专注于 the big idea 主要观点 of the document. There will be words -- in fact 事实上；实际上 whole sentences -- that will throw you off 使你困惑；使你不知所措. Let's be real (非正式)说真的 -- you may be confused 困惑的 by the whole dang (非正式)该死的 thing. But remember your focus is to know the main idea of the document in regards to 关于；就…而言 the prompt and how it might be useful 有用的 in advancing 推进；促进 your argument 论点；观点. So if you can't understand 理解；明白 every part of it, don't worry -- you could still do something with it.

Next you want to think about: How could this document help you defend 辩护；维护 your thesis 论文；论点? Now when you are reading the document for the first time, you more than likely 极有可能；很可能 don't have a thesis yet. So how could you answer the question with this document? Does it give you an idea for a potential 潜在的 thesis? The next thing you want to do is: Does the document connect to 与…联系；与…相关 any of the other documents? You want to try to connect 连接；联系 the documents into two different groups or buckets (非正式)类别. Make connections to 与…建立联系 the documents. Remember the people who created this test chose these documents for a reason. How did the documents reinforce 加强；巩固 or perhaps 也许；可能 even contradict 否定；反驳 one another? And if you can group 分组；分类 these documents as you're reading them, you will develop 发展；形成 your line of reasoning 推理思路 which will become your body paragraphs 主体段落.

And then finally 最后；终于, you also want to do the following: Does any outside information come to mind 想起；浮现 that may be relevant 相关的；切题的 to your developing 发展中的 thesis? You only need a couple 几个 pieces of outside information, and if anything is triggered 触发；引起, jot it down 匆匆记下. And then: Would this document be good for HIPPO or HAPPY? You want to start to identify 识别；认出 which ones might be good candidates 候选人 for that process.

So now that we got the checklist 清单 out of the way, let's look at 审视；考察 some documents. So the first one we're gonna look at 审视；考察 is Document One. Once again 再次；又一次, we're imagining 想象 we only have three documents to look at 审视；考察. And Document One is an interesting 有趣的 one because just by sourcing 标明来源 it, we know it's John Winthrop -- which you may remember as the "city upon a hill" (山巅之城，指具有榜样作用的社群) guy. He is the Puritan 清教徒 governor 州长 of the Massachusetts Bay Colony 马萨诸塞湾殖民地, so he's a Puritan leader 领导者. The document is written on board 在船上 the ship prior to 在…之前 them arriving to 到达；来到 the colony 殖民地, so perhaps 也许；可能 this can reveal 揭示；表明 a religious 宗教的 motivation 动机；目的 of colonization 殖民. These are some of the things that may come to mind 想起；浮现 before 在…之前 you even dive into 深入研究 the document.

Now I'm not gonna read the document to you but just highlight 强调；突出 some of the key points 要点；关键. You could pause it and read it if you like. But if you look at 审视；考察 this document, a couple 几个 things stand out 突出；显眼. The main idea 主要观点 here is the Massachusetts Bay Colony must work together to create a "city upon a hill" that will be an example 榜样；典范 to the rest of the world. So that's really what this document is talking about.

So remember -- AP stands for answer the prompt. We're not just gonna describe 描述；描写 the documents, but we're gonna use them to advance 推进；促进 a thesis 论文；论点. And so perhaps 也许；可能 as you're reading this, this could reveal 揭示；表明 that the New England colony 殖民地 was motivated 激励；促使 by religion 宗教 and the importance 重要性 of community 社区 in the New England colonies.

Our next document we're gonna look at 审视；考察 is Document Four. And what we see here is this is written in 1635 -- doesn't really trigger 触发；引起 a whole lot (非正式)不多；没多少 right off the bat (非正式)立刻；马上 -- but this is a list of immigrants 移民 bound for 前往；驶向 Virginia 弗吉尼亚州. So this document is showing who's going to the Chesapeake region 地区. Now one thing that comes to mind 想起；浮现 as I'm reading this is the colony was founded 建立；创立 in 1607 -- that's not in the document, but that helps me put the document into context 背景. So this is, you know, a couple 几个 decades 十年 after 在…之后 the colony has been already in existence 存在. And from looking at 审视；考察 this document, the main idea 主要观点 is there's way more (非正式)多得多 men than women going to the Chesapeake region -- pretty obvious 明显的；显而易见的, you can count them if you want. And perhaps 也许；可能 for the prompt 提示；题目 we're trying to answer, you can contrast 对比 this with Document One. There's less reliance on 依赖 community, and perhaps 也许；可能 this document reveals 揭示；表明 a male-dominated 男性主导的 society 社会 seeking 寻求；试图 profit 利润；收益. It's not necessarily 不一定 in that document, but you might remember things about the colonization 殖民 of Virginia that would lend some credibility 可信度 to that inference 推断；推论.

Now our next document is Document Five, and this one sees us looking at 审视；考察 John Smith -- which you may remember is one of the key figures 关键人物 in early Virginia history 历史. Since it is written in 1624, this is written after 在…之后 the worst of the starving time (指早期殖民地因饥饿而死亡的时期) was over, and it perhaps 也许；可能 -- you know, because it's from John Smith -- perhaps 也许；可能 it's from the perspective 视角；观点 of the upper class 上层阶级 in Virginia. Now if you look at 审视；考察 the document -- once again 再次；又一次, if you want to read it, hit pause -- you'll notice 注意到 there's a lot of stuff in here. But the main idea 主要观点 is this: Life in Virginia was difficult 困难的 as many settlers 定居者 died. As commanders 指挥官 exploited 剥削；利用 fellow 同伴 colonists 殖民者, desire 渴望；期望 for gold 黄金 consumed 吞噬；占据 many, and John Smith provided 提供；供给 provisions 供应；给养 and stopped a plot 阴谋 against 反对；对抗 the colony 殖民地. That's not everything, but that's kind of some of the key points.

Now our job is not just to describe 描述；描写 the documents, so perhaps 也许；可能 if we bring to use this to answer the prompt, we could connect 连接；联系 this document with Document Four. It demonstrates 表明；证明 a lack of 缺乏 community in the Chesapeake. The purpose 目的；意图 of profit 利润；收益 in the colony is discussed with this emphasis 强调；重点 on gold. And this is a sharp contrast to 与…形成鲜明对比 Document One, which is a foundational 基础的；根本的 document for the New England colonies.

Now on the real DBQ, you will have more documents to look at 审视；考察, but let's just assume 假设；假定 those documents are taking your essay in a different direction -- that's going to be a different body paragraph 主体段落. What would you do with these three documents? Well, let's take a look at 审视；考察 what not to do. So let's just say you write this little paragraph here which is from a student: "Document One shows religion 宗教 and community 社区 were important to 重要 to John Winthrop. Document Four we can see a list of people going to Virginia. Document Five reveals 揭示；表明 things were difficult 困难的 and John Smith tried to keep order 秩序 in the Virginia Colony 殖民地." And this is what a lot of essays -- DBQs -- look like. It's students just basically 基本上；主要地 creating a laundry list (非正式)冗长的清单 of documents: Document One says this, Document Two says this. And your essay should not be a list of documents. Your essay is not about documents. So please -- pretty please (非正式)求求你 -- don't write an essay where you're just kind of randomly 随意地 telling us what these different documents are saying.

Now this one is slightly 稍微 better. So let's take a look: "There were many differences 不同点；差异 between the Chesapeake and New England colonies 殖民地. In Document One, John Winthrop talks a lot about religion 宗教 and community 社区. Winthrop wrote this document while on board 在船上 the Arbella 阿贝拉号 in 1630, and in the document he states 陈述；说明 his hope 希望 that the Massachusetts Bay Colony 马萨诸塞湾殖民地 will be a city upon a hill (山巅之城，指具有榜样作用的社群). Document Four is a list of passengers 乘客 headed to 前往；驶向 the Virginia colony. The colony of Virginia was in the Chesapeake, and in the document we could see there are way more (非正式)多得多 men than women going to the colony. In the history 历史 of Virginia, Document Five we can see that Virginia was a society 社会 with a lot of hardships 艰难困苦. John Smith had to impose 实行；强加 discipline 纪律 to get the colony on the right track 使殖民地走上正轨 as many of the settlers 定居者 were only interested in getting rich."

This particular 特定的；特别的 response 回应；回答 from a student would definitely 肯定地；无疑地 get the credit 赞扬；肯定 for the description 描述；描写 point of the documents. They're using the content 内容 of the documents to address 处理；应对 the topic of the prompt 提示；题目 -- they're definitely 肯定地；无疑地 doing that. But what they're not really doing -- explicitly 明确地；清晰地 -- is really showing how the documents are advancing 推进；促进 a particular 特定的；特别的 thesis 论文；论点. There's a lot of description 描述；描写 about what the documents are saying, but you want to link that back to 与…联系起来 your big idea 主要观点. You need to do more analysis 分析；研究.

So what would that look like? So let's just say this is what your thesis 论文；论点 you kind of end up with: "This thesis." And what you want to do is once you start writing, the topic sentences 主题句 of your different body paragraphs 主体段落 should defend 辩护；维护 a part of your thesis. Now there is no set number -- you know it could be two, it could be three -- as long as you answer all parts of the prompt 提示；题目 and use the appropriate 适当的；恰当的 number of documents, you are good to go (非正式)一切顺利.

So for this particular 特定的；特别的 thesis, let's just imagine 想象 that this is going to be one of our body paragraphs 主体段落. This is the topic sentence -- it's a line of reasoning 推理思路. And since you are trying to make connections to 与…建立联系 the documents and link them back to 与…联系起来 an argument 论点；观点, you decide your first body paragraph will focus on 集中于；专注于 this part of the thesis. One of the things you will quickly 迅速地 see is that if you have a well-thought-out 经过深思熟虑的 thesis with a clear line of reasoning, it's gonna make your life tremendously 极其；非常 easier.

So here's how. Remember the red part is your thesis, and the documents we just looked at 审视；考察 will help us make the point of this idea of the motives 动机；目的 for colonization 殖民 in the characteristics 特征；特点 of the colonists 殖民者 causing these two societies 社会 to develop into 发展成 two different directions. So big idea 主要观点 here is documents that prove 证明；证实 the same point can and definitely 肯定地；无疑地 should be used in the same paragraph to advance 推进；促进 a similar 相似的 argument 论点；观点.

So let's see how this particular 特定的；特别的 student did this. So their first body paragraph looked something like this: "The Chesapeake and the New England colonies developed into two distinct 截然不同的；有明显区别的 regions 地区 due to 由于；因为 the different motivations 动机；目的 for colonization 殖民 and the different types of settlers 定居者 who came to North America 北美洲." So there's their topic sentence -- there's their sub-claim 子论点. And here's how they kind of roll into (非正式)开始 document analysis 分析；研究: "Winthrop's 'A Model of Christian Charity' (基督教慈善典范) demonstrates 表明；证明 that the settlers 定居者 to the New England colonies were largely 主要地 motivated 激励；促使 by religious 宗教的 reasons in the colonization of the New England region." So Document One -- there's some evidence 证据 to advance 推进；促进 that part of the claim 主张；断言.

They go on: "Winthrop, the leader 领导者 of the Massachusetts Bay Colony 马萨诸塞湾殖民地, was speaking to 对…讲话 his followers 追随者 about the unique 独特的 mission 使命 they had in the New World 新大陆 and his desire 渴望；期望 to create 创建 a community 社区 that would serve as 充当；担任 a city upon a hill (山巅之城，指具有榜样作用的社群)," and then they cite 引用 the document -- Document One. You know you want to do that to help the reader -- the grader 评分者 -- figure out 弄明白 kind of where you're using the documents. It's not a requirement 要求, but it's just nice to do. What they're doing here is the writer is providing 提供；供给 some additional 额外的；附加的 analysis 分析；研究 of the document and kind of linking it back 如何联系 to the claim 主张；断言 made and how it proves this thesis 论文；论点 you have so proudly 自豪地 come up with 想出；提出.

They go on: "As a result of 由于；因为 this motivation 动机；目的, many Puritans 清教徒 came to the New World 新大陆 as families, beginning with settlers 定居者 on the Mayflower 《五月花号》." A couple 几个 things here: Quoting 引用 -- you don't want to quote. The only reason they got away with (非正式)侥幸逃脱 quoting is this is that famous 著名的 phrase 短语 "a city upon a hill." But the reader knows what the documents say -- you don't want to quote. The other thing that's stuff in the red -- the Mayflower would count as outside information. It's not in the document -- in fact 事实上；实际上 it happens before 在…之前 the document was created -- but it demonstrates 表明；证明 this idea of religious 宗教的 motivations 动机；目的 of the founding 建立；创立 of New England 新英格兰. So the red is outside information that helps advance 推进；促进 this thesis 论文；论点, and it shows you don't need to create 创建 whole new paragraphs 段落 to get the outside information points. Do that a couple 几个 times throughout 贯穿；遍及 the essay, and you're good to go (非正式)一切顺利 there.

And they continue: "In contrast 对比之下, Document Four reveals 揭示；表明 that the majority 大多数 of those going to 前往；驶向 the Chesapeake region 地区 were male 男性的 settlers 定居者 seeking to 寻求；试图 get rich." Document Five -- John Smith reveals 揭示；表明 that the Chesapeake colony 殖民地 was plagued with 受…困扰 tensions 紧张局势 between economic 经济的 classes 阶级 and competition 竞争 for wealth 财富, further 进一步地 fueled by 助长；刺激 the rise 兴起；出现 of tobacco 烟草 plantations 种植园 and indentured servants 契约奴仆 as a labor source 劳动力来源. Now in terms of 关于；就…而言 citing 引用 documents -- you know, this is not the best way where you say "Document Four shows." It's much more sophisticated 老练的；复杂的 writing to actually 实际上；事实上 call it by the source 来源 -- so you see that in Document One -- "A Model of Christian Charity." But there is no rule about this. So you're on a time limit 时间限制 -- do what you need to do to get by (非正式)应付过去 and to get your point across 使你的观点被理解 and so that you can get those points so you can make your family proud.

So this would be an example of a body paragraph 主体段落 that uses three documents, brings in 引入；提及 some outside information in a way that really advances 推进；促进 the thesis 论文；论点. And if we think about where we've come so far 到目前为止 with this prompt 提示；题目, we have a contextualization 背景化；语境化 -- we're setting the scene 设置场景, the bigger picture 大局；全貌, and how it links back to 如何联系到 the thesis 论文；论点 which we have right there in the opening paragraph 开头段落. We get the two points, and then we kill it (非正式)做得极好 with this body paragraph that would make Theodore Roosevelt proud, where we have three documents, we have outside information, we link that stuff back to 与…联系起来 your thesis.

And you're probably 可能；大概 wondering 纳闷；想知道: What about the HIPPO? Or if your teacher's weird (非正式)古怪的 -- HAPPY (Historical Context 历史背景, Audience 读者, Purpose 目的, Point of View 观点, Why now? 为何此时？)? Because there's nothing happy in a DBQ. Or some people use CAP (Context 背景, Audience 读者, Purpose 目的). We're gonna talk about that in another video because that gets really messy (非正式)混乱的 and complicated 复杂的. But the important thing to know is: Use the documents, analyze 分析；研究 the documents, and write a killer (非正式)极好的 essay. And if you need additional 额外的；附加的 help, go to apushexplained.com. If you liked the video, click like, leave a comment. Peace!

'''


== 中文翻译

大家好，漂亮的人们！今天我们要来看看你的 AP 历史课的 DBQ。特别是，我们将重点关注如何使用文献。我知道你们想知道如何得分，我将向你们展示如何使用文献，但我会尽量减少对评分标准的讨论。这东西会让你发疯。如果你担心你需要使用多少文献，或者你需要对多少文献进行 HIPPO 分析，请查看描述并点击评分标准视频的链接，它会详细讲解。这个视频只是关于你到底应该如何处理文献并在你的论文中使用它们。根据我的经验，这才是最让学生困惑并影响他们 DBQ 表现的地方。

话虽如此，快速查看评分标准的措辞：如果你使用文献的内容来回应题目的话题，你将获得一分。这实际上意味着在你的论文中，你用文字描述了文献。你分解了文献在说什么，文献是关于什么的，但你并没有真正把它与任何论点联系起来。这真的很基本，你不能通过这样做获得分数。评分标准的下一部分是真正使用文献来支持或推进你的论点。这是你将文献用作证据的地方。你不仅仅是在描述或解释文献——你正在用文献做一些有用的事情，并向读者展示它如何证明你的论点。

评分标准中与文献相关的另一部分是 HIPPO 分或更深入的分析分。我们不会详细讨论扩展分析，但要知道我们将引用评分标准的这一部分。最后，与文献没有直接联系的东西——使用外部信息和复杂理解——也可以在你的分析和文献使用过程中实现。我们稍后会简单提及这一点。

所以我们将使用这个题目作为我们的示例题目，为了尽可能缩短这个视频，我们将假设我们只有三份文献可以查看。到目前为止，你实际上还没有看过这些文献。你已经完成了右边黑色框里的所有事情——大约花了二到三分钟。你不想在这上面花费太多时间。但现在是时候去冒险，找到一些证据并解释一些文献了。

在我们实际这样做之前，我想给你一个快速的小清单，列出我认为你在处理每份文献时应该做的事情。首先是标注文献来源。作者姓名、日期、文献背景、文献标题是否让你想起什么？如果对你有帮助，就在页边空白处记下来。然后你需要快速阅读并注释文献。现在专注于文献的主要思想。会有一些词——实际上是整个句子——会让你感到困惑。说实话——你可能会对整个东西感到困惑。但记住，你的重点是了解文献关于题目的主要思想以及它如何能帮助你推进你的论点。所以如果你不能理解它的每个部分，别担心——你仍然可以用它做一些事情。

接下来你需要思考：这份文献如何能帮助你捍卫你的论点？现在当你第一次阅读文献时，你很可能还没有一个论点。那么你如何用这份文献回答这个问题？它是否为你提供了一个潜在论点的想法？接下来你需要做的是：这份文献是否与其他任何文献相关联？你想要尝试将这些文献连接成两个不同的组或“桶”。将文献联系起来。记住，创建这个测试的人选择这些文献是有原因的。这些文献是如何加强甚至可能相互矛盾的？如果你在阅读时就能将这些文献分组，你将发展你的论证思路，这将成为你主体段落的内容。

最后，你还需要做以下事情：是否有任何与你正在形成的论点相关的外部信息浮现在脑海中？你只需要几个外部信息，如果有任何信息被触发，就记下来。然后：这份文献是否适合 HIPPO 或 HAPPY 分析？你想要开始确定哪些文献可能是进行这种分析的好选择。

现在我们已经完成了清单，让我们来看一些文献。我们要看的第一个是文献一。再次强调，我们假设只有三份文献可以看。文献一是很有趣的一份，因为仅仅通过标注文献来源，我们就知道它是约翰·温斯罗普——你可能记得他是“山巅之城”的那个人。他是马萨诸塞湾殖民地的清教徒总督，所以他是清教徒的领导人。这份文献是在他们抵达殖民地之前的船上写的，所以也许这可以揭示殖民化的宗教动机。这些可能是在你甚至深入阅读文献之前就会想到的事情。

我现在不会向你朗读这份文献，只是强调一些关键点。如果你愿意，可以暂停并阅读。但如果你看一下这份文献，有几件事很突出。这里的主要思想是马萨诸塞湾殖民地必须共同努力创建一个将成为世界其他地方榜样的“山巅之城”。这才是这份文献真正要说的。

记住——AP 代表回答题目。我们不仅仅要描述文献，还要用它们来推进论点。所以也许你在阅读时，这可以揭示新英格兰殖民地是由宗教和新英格兰殖民地社区的重要性所驱动的。

我们要看的下一份文献是文献四。我们在这里看到的是这份文献写于 1635 年——乍一看并没有引起太多联想——但这是一份前往弗吉尼亚的移民名单。所以这份文献显示了谁要去切萨皮克地区。现在当我阅读这份文献时，我想到的第一件事是这个殖民地成立于 1607 年——这不在文献中，但这有助于我将这份文献置于背景中。所以这是在殖民地已经存在了几十年之后。从这份文献来看，主要思想是前往切萨皮克地区的男性远多于女性——这很明显，如果你愿意可以数一下。也许对于我们试图回答的题目，你可以将此与文献一进行对比。对社区的依赖较少，也许这份文献揭示了一个以男性为主导的、寻求利润的社会。这不一定在文献中，但你可能会记得一些关于弗吉尼亚殖民化的事情，这些会为这种推断提供一些可信度。

现在我们的下一份文献是文献五，这份文献让我们看到了约翰·史密斯——你可能记得他是早期弗吉尼亚历史的关键人物之一。由于它写于 1624 年，这是在最严重的饥饿时期结束后写的，也许——你知道，因为它来自约翰·史密斯——也许它来自弗吉尼亚上层阶级的视角。现在如果你看一下这份文献——再次强调，如果你想阅读，请暂停——你会注意到里面有很多内容。但主要思想是：弗吉尼亚的生活很艰难，许多定居者死亡。指挥官剥削其他殖民者，对黄金的渴望吞噬了许多人，约翰·史密斯提供了物资并阻止了一场反对殖民地的阴谋。这不是全部内容，但这是一些关键点。

现在我们的工作不仅仅是描述文献，所以也许如果我们用它来回答题目，我们可以将这份文献与文献四联系起来。它展示了切萨皮克地区缺乏社区意识。这份文献讨论了殖民地中以黄金为重点的利润目的。这与文献一形成了鲜明的对比，文献一是新英格兰殖民地的基础性文献。

在真正的 DBQ 中，你将有更多的文献可以查看，但让我们假设这些文献正在将你的论文引向不同的方向——那将是不同的主体段落。你会如何处理这三份文献？好吧，让我们看看不该怎么做。所以假设你写了这段小文字，这是一个学生写的：“文献一表明宗教和社区对约翰·温斯罗普很重要。文献四我们可以看到一份前往弗吉尼亚的人员名单。文献五揭示了情况很艰难，约翰·史密斯试图维持弗吉尼亚殖民地的秩序。”很多论文——DBQ——看起来都是这样。学生基本上只是创建了一个文献清单：文献一说了这个，文献二说了那个。你的论文不应该是文献清单。你的论文不是关于文献的。所以请——拜托了——不要写一篇你只是随意告诉我们这些不同文献在说什么的论文。

这个稍微好一点。让我们看看：“切萨皮克和新英格兰殖民地之间有很多不同之处。在文献一中，约翰·温斯罗普谈了很多关于宗教和社区的事情。温斯罗普在 1630 年乘坐阿贝拉号时写了这份文献，他在文献中表达了他希望马萨诸塞湾殖民地将成为一座山巅之城的愿望。文献四是一份前往弗吉尼亚殖民地的乘客名单。弗吉尼亚殖民地位于切萨皮克地区，在文献中我们可以看到前往该殖民地的男性远多于女性。在弗吉尼亚的历史中，文献五我们可以看到弗吉尼亚是一个充满艰辛的社会。约翰·史密斯不得不强制执行纪律，使殖民地走上正轨，因为许多定居者只对发财感兴趣。”

这个学生的回应肯定会获得文献描述分的。他们正在使用文献的内容来回应题目的话题——他们肯定在这样做。但他们并没有真正——明确地——展示这些文献是如何推进一个特定的论点的。有很多关于文献在说什么的描述，但你需要将其与你的主要思想联系起来。你需要做更多的分析。

那会是什么样子呢？所以假设这就是你最终形成的论点：“这个论点。”你想要做的是，一旦你开始写作，你不同主体段落的主题句应该捍卫你论点的一部分。现在没有固定的数量——你知道可能是两个，可能是三个——只要你回答了题目的所有部分并使用了适当数量的文献，你就可以了。

所以对于这个特定的论点，让我们假设这将是我们其中一个主体段落。这是主题句——这是一个论证思路。由于你试图在文献之间建立联系并将它们与一个论点联系起来，你决定你的第一个主体段落将侧重于论点的这一部分。你很快就会看到，如果你有一个经过深思熟虑、论证思路清晰的论点，它会使你的生活变得异常轻松。

就是这样。记住红色部分是你的论点，我们刚才看到的文献将帮助我们阐述殖民动机和殖民者特点导致这两个社会朝着两个不同方向发展的观点。这里的主要思想是，证明相同观点的文献可以而且绝对应该在同一段落中使用，以推进类似的论点。

让我们看看这个学生是如何做的。他们的第一个主体段落看起来像这样：“切萨皮克和新英格兰殖民地发展成为两个截然不同的地区，这是由于殖民化的不同动机以及来到北美的不同类型的定居者。”这是他们的主题句——这是他们的子论点。以下是他们如何引入文献分析的：“温斯罗普的《基督教慈善典范》表明，新英格兰殖民地的定居者主要是出于宗教原因而殖民新英格兰地区的。”文献一——有一些证据可以推进这一论点。

他们继续说：“马萨诸塞湾殖民地的领导人温斯罗普正在向他的追随者讲述他们在北美洲的独特使命以及他创建一个将成为山巅之城的社区的愿望，”然后他们引用了文献——文献一。你知道你需要这样做来帮助读者——评分者——弄清楚你在哪里使用文献。这不是强制性的，但这样做很好。作者在这里所做的是对文献进行了一些额外的分析，并将其与所提出的论点以及你如此自豪地提出的论点联系起来。

他们继续说：“由于这种动机，许多清教徒以家庭为单位来到新世界，从五月花号上的定居者开始。”这里有几点：引用——你不想引用。他们之所以引用，唯一的原因是这是那句名言“山巅之城”。但读者知道文献说了什么——你不想引用。另一件红色部分的内容——五月花号将被视为外部信息。它不在文献中——事实上它发生在文献创建之前——但它证明了新英格兰建立的宗教动机的观点。所以红色是帮助推进这个论点的外部信息，它表明你不需要创建全新的段落来获得外部信息分。在整篇论文中做几次这样的事情，你就没问题了。

他们继续说：“相比之下，文献四显示，前往切萨皮克地区的大部分是寻求致富的男性定居者。文献五——约翰·史密斯揭示，切萨皮克殖民地饱受经济阶级之间的紧张关系和对财富的竞争之苦，而烟草种植园和作为劳动力来源的契约奴的兴起进一步加剧了这种情况。”现在就引用文献而言——你知道，像“文献四显示”这样并不是最好的方式。更成熟的写作方式是实际地称呼其来源——所以你在文献一中看到了——“基督教慈善典范”。但这并没有规定。所以你有时间限制——做你需要做的事情来通过并表达你的观点，这样你就可以获得这些分数，让你的家人感到骄傲。

这将是一个主体段落的例子，它使用了三份文献，引入了一些外部信息，并且真正推进了论点。如果我们回顾一下到目前为止我们在这个题目上所取得的进展，我们有一个背景化——我们正在设置场景，更大的图景，以及它如何与我们在开头段落中提出的论点联系起来。我们获得了两分，然后我们用这个会让西奥多·罗斯福感到骄傲的主体段落把它搞定了，我们有三份文献，我们有外部信息，我们将这些东西与你的论点联系起来。

你可能想知道：HIPPO 呢？或者如果你的老师很奇怪——HAPPY？因为 DBQ 里没有任何快乐的东西。或者有些人用 CAP。我们将在另一个视频中讨论这个问题，因为它变得非常混乱和复杂。但重要的是要知道：使用文献，分析文献，写一篇出色的论文。如果你需要额外的帮助，请访问 apushexplained.com。如果你喜欢这个视频，请点击“喜欢”，留下评论。再见！

'''


== pure


What's up, beautiful people? Today we're gonna take a look at the DBQ for your AP history class. In particular, we are gonna focus on using the documents. Now I know you're wondering how do I get points, and I'm gonna show you how to use the documents, but I'm gonna try to keep the rubric talk to an absolute minimum here. This stuff can make you go crazy. If you're worried about how many documents you need to use or how many documents you need to do the HIPPO thing with, go into the description and click the link for the rubric video which will break it all down. This video is just about how in the heck you should approach the documents and use them in your essay. And in my experience, this is what messes with most students and their ability to do well on the DBQ.

With that being said, quick check of the rubric language: You will get a point if you use the content of the document to address the topic of the prompt. And what this really means is in your essay you describe the document in your writing. You break down what the document is saying, what the document is about, but you don't really connect it to any argument. So this is really basic, and you can't get a point for doing this. The next part of the rubric is really using the documents to support or advance your argument. This is where you are using the documents as evidence. You're not just describing or interpreting the document -- you're doing something useful with the document and showing the reader how it proves your thesis.

Another part of the rubric that's linked to the documents is the HIPPO point or the deeper analysis point. We're not going to go into extreme detail on the extended analysis, but just know that we're gonna make some references to this part of the rubric. And then finally, stuff that's not directly connected to a document -- using outside information and complex understanding -- can also be achieved during your analysis and your use of documents. So we'll touch on that in just a moment.

So we're gonna use this prompt as our sample prompt, and for the purposes of keeping this video as short as possible, we're going to imagine that we only have three documents to look at. Now up until this point, you haven't actually looked at the documents. You've done all of the things in the black right there -- it took about two to three minutes. You don't want to spend too much time on this. But now it's time to go on an adventure and find us some evidence and interpret some documents.

Now before we actually do this, I want to give you a quick little checklist of what I think you should do as you approach each document. So the first thing is to source the document. Does the name of the author, the date, the context of the document, title of the document ring any bells? Jot it down in the margins if that will help you out. Then you want to quickly read and annotate the document. Now focus on the big idea of the document. There will be words -- in fact whole sentences -- that will throw you off. Let's be real -- you may be confused by the whole dang thing. But remember your focus is to know the main idea of the document in regards to the prompt and how it might be useful in advancing your argument. So if you can't understand every part of it, don't worry -- you could still do something with it.

Next you want to think about: How could this document help you defend your thesis? Now when you are reading the document for the first time, you more than likely don't have a thesis yet. So how could you answer the question with this document? Does it give you an idea for a potential thesis? The next thing you want to do is: Does the document connect to any of the other documents? You want to try to connect the documents into two different groups or buckets. Make connections to the documents. Remember the people who created this test chose these documents for a reason. How did the documents reinforce or perhaps even contradict one another? And if you can group these documents as you're reading them, you will develop your line of reasoning which will become your body paragraphs.

And then finally, you also want to do the following: Does any outside information come to mind that may be relevant to your developing thesis? You only need a couple pieces of outside information, and if anything is triggered, jot it down. And then: Would this document be good for HIPPO or HAPPY? You want to start to identify which ones might be good candidates for that process.

So now that we got the checklist out of the way, let's look at some documents. So the first one we're gonna look at is Document One. Once again, we're imagining we only have three documents to look at. And Document One is an interesting one because just by sourcing it, we know it's John Winthrop -- which you may remember as the "city upon a hill" guy. He is the Puritan governor of the Massachusetts Bay Colony, so he's a Puritan leader. The document is written on board the ship prior to them arriving to the colony, so perhaps this can reveal a religious motivation of colonization. These are some of the things that may come to mind before you even dive into the document.

Now I'm not gonna read the document to you but just highlight some of the key points. You could pause it and read it if you like. But if you look at this document, a couple things stand out. The main idea here is the Massachusetts Bay Colony must work together to create a "city upon a hill" that will be an example to the rest of the world. So that's really what this document is talking about.

So remember -- AP stands for answer the prompt. We're not just gonna describe the documents, but we're gonna use them to advance a thesis. And so perhaps as you're reading this, this could reveal that the New England colony was motivated by religion and the importance of community in the New England colonies.

Our next document we're gonna look at is Document Four. And what we see here is this is written in 1635 -- doesn't really trigger a whole lot right off the bat -- but this is a list of immigrants bound for Virginia. So this document is showing who's going to the Chesapeake region. Now one thing that comes to mind as I'm reading this is the colony was founded in 1607 -- that's not in the document, but that helps me put the document into context. So this is, you know, a couple decades after the colony has been already in existence. And from looking at this document, the main idea is there's way more men than women going to the Chesapeake region -- pretty obvious, you can count them if you want. And perhaps for the prompt we're trying to answer, you can contrast this with Document One. There's less reliance on community, and perhaps this document reveals a male-dominated society seeking profit. It's not necessarily in that document, but you might remember things about the colonization of Virginia that would lend some credibility to that inference.

Now our next document is Document Five, and this one sees us looking at John Smith -- which you may remember is one of the key figures in early Virginia history. Since it is written in 1624, this is written after the worst of the starving time was over, and it perhaps -- you know, because it's from John Smith -- perhaps it's from the perspective of the upper class in Virginia. Now if you look at the document -- once again, if you want to read it, hit pause -- you'll notice there's a lot of stuff in here. But the main idea is this: Life in Virginia was difficult as many settlers died. As commanders exploited fellow colonists, desire for gold consumed many, and John Smith provided provisions and stopped a plot against the colony. That's not everything, but that's kind of some of the key points.

Now our job is not just to describe the documents, so perhaps if we bring to use this to answer the prompt, we could connect this document with Document Four. It demonstrates a lack of community in the Chesapeake. The purpose of profit in the colony is discussed with this emphasis on gold. And this is a sharp contrast to Document One, which is a foundational document for the New England colonies.

Now on the real DBQ, you will have more documents to look at, but let's just assume those documents are taking your essay in a different direction -- that's going to be a different body paragraph. What would you do with these three documents? Well, let's take a look at what not to do. So let's just say you write this little paragraph here which is from a student: "Document One shows religion and community were important to John Winthrop. Document Four we can see a list of people going to Virginia. Document Five reveals things were difficult and John Smith tried to keep order in the Virginia Colony." And this is what a lot of essays -- DBQs -- look like. It's students just basically creating a laundry list of documents: Document One says this, Document Two says this. And your essay should not be a list of documents. Your essay is not about documents. So please -- pretty please -- don't write an essay where you're just kind of randomly telling us what these different documents are saying.

Now this one is slightly better. So let's take a look: "There were many differences between the Chesapeake and New England colonies. In Document One, John Winthrop talks a lot about religion and community. Winthrop wrote this document while on board the Arbella in 1630, and in the document he states his hope that the Massachusetts Bay Colony will be a city upon a hill. Document Four is a list of passengers headed to the Virginia colony. The colony of Virginia was in the Chesapeake, and in the document we could see there are way more men than women going to the colony. In the history of Virginia, Document Five we can see that Virginia was a society with a lot of hardships. John Smith had to impose discipline to get the colony on the right track as many of the settlers were only interested in getting rich."

This particular response from a student would definitely get the credit for the description point of the documents. They're using the content of the documents to address the topic of the prompt -- they're definitely doing that. But what they're not really doing -- explicitly -- is really showing how the documents are advancing a particular thesis. There's a lot of description about what the documents are saying, but you want to link that back to your big idea. You need to do more analysis.

So what would that look like? So let's just say this is what your thesis you kind of end up with: "This thesis." And what you want to do is once you start writing, the topic sentences of your different body paragraphs should defend a part of your thesis. Now there is no set number -- you know it could be two, it could be three -- as long as you answer all parts of the prompt and use the appropriate number of documents, you are good to go.

So for this particular thesis, let's just imagine that this is going to be one of our body paragraphs. This is the topic sentence -- it's a line of reasoning. And since you are trying to make connections between the documents and link them back to an argument, you decide your first body paragraph will focus on this part of the thesis. One of the things you will quickly see is that if you have a well-thought-out thesis with a clear line of reasoning, it's gonna make your life tremendously easier.

So here's how. Remember the red part is your thesis, and the documents we just looked at will help us make the point of this idea of the motives for colonization in the characteristics of the colonists causing these two societies to develop into two different directions. So big idea here is documents that prove the same point can and definitely should be used in the same paragraph to advance a similar argument.

So let's see how this particular student did this. So their first body paragraph looked something like this: "The Chesapeake and the New England colonies developed into two distinct regions due to the different motivations for colonization and the different types of settlers who came to North America." So there's their topic sentence -- there's their sub-claim. And here's how they kind of roll into the document analysis: "Winthrop's 'A Model of Christian Charity' demonstrates that the settlers to the New England colonies were largely motivated by religious reasons in the colonization of the New England region." So Document One -- there's some evidence to advance that part of the claim.

They go on: "Winthrop, the leader of the Massachusetts Bay Colony, was speaking to his followers about the unique mission they had in the New World and his desire to create a community that would serve as a city upon a hill," and then they cite the document -- Document One. You know you want to do that to help the reader -- the grader -- figure out kind of where you're using the documents. It's not a requirement, but it's just nice to do. What they're doing here is the writer is providing some additional analysis of the document and kind of linking it back how it connects to the claim made and how it proves this thesis you have so proudly come up with.

They go on: "As a result of this motivation, many Puritans came to the New World as families, beginning with settlers on the Mayflower." A couple things here: Quoting -- you don't want to quote. The only reason they got away with quoting is this is that famous phrase "a city upon a hill." But the reader knows what the documents say -- you don't want to quote. The other thing that's stuff in the red -- the Mayflower would count as outside information. It's not in the document -- in fact it happens before the document was created -- but it demonstrates this idea of religious motivations of the founding of New England. So the red is outside information that helps advance this thesis, and it shows you don't need to create whole new paragraphs to get the outside information points. Do that a couple times throughout the essay, and you're good to go there.

And they continue: "In contrast, Document Four reveals that the majority of those going to the Chesapeake region were male settlers seeking to get rich. Document Five -- John Smith reveals that the Chesapeake colony was plagued with tensions between economic classes and competition for wealth, further fueled by the rise of tobacco plantations and indentured servants as a labor source." Now in terms of citing documents -- you know, this is not the best way where you say "Document Four shows." It's much more sophisticated writing to actually call it by the source -- so you see that in Document One -- "A Model of Christian Charity." But there is no rule about this. So you're on a time limit -- do what you need to do to get by and to get your point across and so that you can get those points so you can make your family proud.

So this would be an example of a body paragraph that uses three documents, brings in some outside information in a way that really advances the thesis. And if we think about where we've come so far with this prompt, we have a contextualization -- we're setting the scene, the bigger picture, and how it links back to the thesis which we have right there in the opening paragraph. We get the two points, and then we kill it with this body paragraph that would make Theodore Roosevelt proud, where we have three documents, we have outside information, we link that stuff back to your thesis.

And you're probably wondering: What about the HIPPO? Or if your teacher's weird -- HAPPY? Because there's nothing happy in a DBQ. Or some people use CAP. We're gonna talk about that in another video because that gets really messy and complicated. But the important thing to know is: Use the documents, analyze the documents, and write a killer essay. And if you need additional help, go to apushexplained.com. If you liked the video, click like, leave a comment. Peace!

'''
