= 0819
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 819: Athletes Behaving Badly.
This is English as a Second Language Podcast episode 819. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. If you really want to improve your English as fast as possible, become a member of ESL Podcast and download a Learning Guide to help you do that.
This episode is a dialogue between Connie and Walt about people who play sports, professional athletes. Let’s get started.
[start of dialogue]
Connie: I just got a call from Ron’s agent. He’s in hot water again.
Walt: Not again! What did he get up to now?
Connie: He got into another fight outside of a bar, and he’s in police custody right now cooling his heels. I don’t know what he was thinking.
Walt: It’s the off-season, so I can understand him wanting to blow off some steam. But doesn’t he realize what he’s doing to his image and reputation?
Connie: They don’t call him the bad boy of basketball for nothing. I guess it’s our job to do some damage control.
Walt: Yeah, and fast. Once the press gets a hold of this, they’ll have a field day.
Connie: It’s going to be a long night.
Walt: Not as long as Ron’s.
Connie: Serves him right!
[end of dialogue]
Our dialogue begins with Connie saying, “I just got a call,” meaning I just received a telephone call, “from Ron’s agent.” An “agent” (agent) is a representative, a person whose job it is to represent usually an athlete (that is, a sports player), a musician, a model, an actor, a writer. Many of these people have agents. They're sort of business people who represent them, who take care of their business negotiations and business contracts for them. Connie says, “He’s in hot water again,” meaning Ron is in hot water. “To be in hot water” means to be in trouble, to have a lot of difficulties, to have done something wrong and now you have problems.
Walt says, “Not again! What did he get up to now?” The expression “to get up to something” is a phrasal verb meaning to become involved in something, usually something bad, something that you should not be doing. “What did he get up to now?” Well, Connie says that he, Ron, got into another fight outside of a bar. A “fight” is when you hit someone else. A bar, of course, is a place where people drink alcohol, so it's not surprising that there are fights outside of bars and that’s what happened to Ron. Now Connie says, “He’s in police custody.” To be in “police custody” (custody) means that the police came and they arrested you. They are holding you. They won't let you go. Usually, they take you to a jail or to what we would call a “police station.” If you get in trouble, that can happen to you. And that’s what happened to Ron.
Connie says, “He’s in police custody right now cooling his heels.” This expression to “cool (cool) your heels” (heels) means to spend time calming down. When you're very angry or very emotional, someone might say to you, “You need to cool your heels.” Your “heel” is the part of your foot, the bottom, back part of your foot, but the expression “to cool your heels” perhaps means that you need to be running around less. In any case, it means that you need to calm down. You need to be less angry, less emotional. Connie says, “I don’t know what he was thinking,” meaning I'm not sure why he did this.
Walt says, “It’s the off-season.” The “off-season” is when a sport is not being played. For example, baseball is played between, say, April and October. That means that November, December, January, February, the first part of March, that’s the off-season. That’s when there isn't any professional baseball games or there aren't any professional baseball games. That’s the off-season. Walt says, “It's the off-season, so I can understand him wanting to blow off some steam.” The expression “to blow off some steam” (steam) means to release negative emotions or extra energy or stress in some way. Let's say you come home from work and you had a bad day, a very stressful day, so you decide to go for a run. You're going to jog around your neighborhood in order to relax, to blow off some steam. That’s the idea.
Walt says, “Doesn’t he, Ron, realize that what he’s doing to his image and reputation?” Walt is asking why Ron is doing these crazy things like getting involved in a fight outside of a bar and then getting arrested or taken by the police. He asked whether Ron realizes what all of this is doing to his image. Your “image” (image) is the way other people look at you. It's the way other people see you. Reputation is very closely related to that. That’s what other people think about you. Your reputation is what other people think. You may have a reputation for being a funny person. That means other people, when they think of you, think, “Oh yeah, he’s funny.” We want to have a good reputation, of course, and not a bad reputation, but Ron is getting a bad reputation by doing all of these stupid things. But sometimes professional athletes do stupid things.
Connie says, “They call him the bad boy of basketball for nothing.” This phrase “they don’t call someone something for nothing” is used to emphasize that someone has earned or deserves the image and reputation that they have. So, for example, someone may be a very good singer and they stand up and they sing a wonderful song, and you say to your friend, “They don’t call him the best singer in the world for nothing,” meaning there's a reason why people think he’s a good singer and he just demonstrated it. So, when somebody does something that shows that whatever their image or reputation is, is true, that is when we would use this expression. So, Ron is known, he has the reputation, for being the bad boy of basketball. Basketball of course is the sport. To be a “bad boy” means to be a boy or a man who’s actions are often breaking the rules, somebody who doesn’t care what other people think of him, somebody who does things that are wrong or that are bad.
Connie says, “I guess it's our job to do some damage control.” “Damage” is when you hurt something. “Damage control” is when there's a problem or a negative situation and somebody tries to make it so that it isn't as bad as it might be, someone who tries to stop the problem from getting any bigger or any worse. So, let's say we have a famous singer or a famous actor and they have a drug problem or they get arrested for doing something bad, something wrong, their agents, their representatives will try to do some damage control. They’ll try to talk to the newspapers and magazines and say, “Well, he was having a bad day” or he’s really sorry about what happened. That’s damage control. That’s trying to protect and save this person’s reputation from getting any worse.
Walt says, “Yeah, and fast,” meaning we need to do some damage control quickly. “Once the press gets a hold of this, they’ll have a field day.” The expression “to get a hold of something” means to get information, to find out about something, to obtain information that might be difficult to get. The “press” refers to the media: newspapers, magazines, television reporters, etc. “To have a field day” is an expression meaning to have a lot of fun doing something without any limits or any restrictions. We're going to have a field day at Starbucks by drinking all the coffee we possibly can. We're going to the café and we're going to have a field day. This expression is often used, as it is in this dialogue, to talk about what will happen if somebody finds out about some secret negative or damaging information. When the television stations find out that Ron had a fight, they’ll have a field day, meaning they’ll really make fun of him. It will be a very damaging time because they found out this information.
Connie says, “It's going to be a long night,” meaning we're going to have to stay up late in order to do this damage control, making phone calls and so forth.
Walt says, “Not as long as Ron’s,” meaning Ron will have an even more difficult night because of course, he is being held by the police.
Connie then says, “Serves him right!” The expression “serves him right” or “serves them right” or “serves her right” is used when you are expressing your opinion that when something bad happened to someone, they deserved it. It was because they did something wrong that they are getting a negative consequence for their behavior or for their actions. So, somebody starts drinking and they start driving and then the police stop them and arrest them. You might say, “Well, serves them right!” meaning, they deserve that because they did something bad. They did something wrong.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Connie: I just got a call from Ron’s agent. He’s in hot water again.
Walt: Not again! What did he get up to now?
Connie: He got into another fight outside of a bar, and he’s in police custody right now cooling his heels. I don’t know what he was thinking.
Walt: It’s the off-season, so I can understand him wanting to blow off some steam. But doesn’t he realize what he’s doing to his image and reputation?
Connie: They don’t call him the bad boy of basketball for nothing. I guess it’s our job to do some damage control.
Walt: Yeah, and fast. Once the press gets a hold of this, they’ll have a field day.
Connie: It’s going to be a long night.
Walt: Not as long as Ron’s.
Connie: Serves him right!
[end of dialogue]
She has the reputation for being the best ESL scriptwriter in the world and she deserves it. That’s our own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
agent – representative; a person whose job is to represent an athlete, musician, model, or actor, helping that person find new jobs and take care of his or her reputation
* Perry’s agent told him about a great audition that’s happening next week.
in hot water – in trouble; in a problematic situation; with a lot of difficulties; having done something bad or wrong
* We’ll be in hot water if the professor finds out we cheated on the exam.
to get up to – to become involved in something, especially something bad that one should not be doing
* Keep these teenagers busy so they don’t have time to get up to anything during summer vacation!
in police custody – being held or detained by police, so that one is not allowed to leave the police station or jail for a period of time; under the care and observation of the police
* The drunken men were kept in police custody overnight until they became sober.
to cool (one’s) heels – to spend time calming down and becoming less angry, especially before making a decision based on one’s emotions
* Meghan has decided to spend the weekend thinking about the situation and cooling her heels before firing Jordan.
off-season – when something is not active or is not happening, especially related to sports; between seasons; between busy or active periods
* Baseball players work hard during the spring, summer, and fall, but winter is their off-season.
to blow off some steam – to release negative emotions and extra energy or stress in some way; to do something that makes one feel less stressed or less angry
* Exercise can be a great way to blow off some steam after a stressful day at the office.
image – the way one is perceived or understood by other people; appearance
* Many corporations are trying to create an environmentally-friendly image to increase sales.
reputation – how one is perceived or understood by other people, especially a judgment about whether one is good, honest, and trustworthy
* If dentists don’t treat their patients well, it can really hurt their professional reputation.
they don’t call (someone) (something) for nothing – a phrase used to emphasize that someone has earned the title he or she has, or that someone deserves the reputation he or she has
* Oscar has broken up with six girls already this year. They don’t call him a heartbreaker for nothing!
the bad boy of (something) – a boy or man whose actions are extreme, who is independent, who doesn’t care what other people think or how they feel, and who often breaks rules or laws
* Lyle has always been the bad boy of our band, but this time he went too far.
damage control – efforts to fix or correct a problem or a negative situation, especially to control how it is perceived by other people and make it seem less serious or less important
* The senator has a team of people responsible for damage control whenever a journalist writes a negative article about his personal life.
press – media; journalists; the people and organizations who distribute the news
* It seems unfair for the press to report such a biased story. Why didn’t they interview the other side?
to get a hold of – to obtain information or some other thing that is very desirable, but difficult to get
* If anyone gets a hold of these emails, we’ll all lose our job.
to have a field day – to have a lot of fun doing something without limitations or restrictions
* If we ever win the lottery, we’ll have a field day at this expensive store!
to serve (one) right – for someone to receive what he or she deserves, especially as a negative consequence that results from bad behavior
* Wynona is complaining about losing her driver’s license, but it serves her right! She should never have driven while she was drunk.
Comprehension Questions
1. What does Connie mean when she says that Ron is “in hot water”?
a) He is taking a hot shower.
b) He is in trouble.
c) He is in debt.
2. Why do they call Ron the bad boy of basketball?
a) Because he isn’t a very good basketball player.
b) Because he’s the youngest player on the team.
c) Because he is known for his bad behavior.
Answers at bottom.
What Else Does It Mean?
to get up to
The phrase “to get up to,” in this podcast, means to become involved in something, especially something bad that one should not be doing: “What did you two get up to while your parents were out of town last weekend?” The phrase “get-up-and-go” refers to one’s energy, enthusiasm, and motivation for doing something: “We’re looking for a candidate with a lot of get-up-and-go who can do the job without a lot of help.” The phrase “to get (someone) up” means to wake someone and make him or her get out of bed: “If I didn’t get Carla up, she would sleep until noon.” Finally, the phrase “to get up” can mean to stand up: “It’s a beautiful day! We should get up and go outside.”
to get a hold of
In this podcast, the phrase “to get a hold of” means to obtain information or some other thing that is very desirable, but difficult to get: “How did you get a hold of those tickets? I thought they sold out the first day.” The phrase “to get a hold of (someone)” means to be able to speak with someone who is difficult to find or who does not have very much free time: “After leaving voicemail messages almost every day for two weeks, I finally got a hold of Rick to talk about the project.” Finally, the phrase “to take hold” means to have some effect or result: “The new education policies are starting to take hold and we’re beginning to see improvements in the students’ attendance at a school.”
Culture Note
Professional Athletes in Retirement
In many sports, “athletes” (people who play a sport) “hit their peak” (reach their maximum level of performance) in their 20s or 30s. Professional athletes may have “earned” (received in exchange for one’s work) enough money to “retire” (stop working) comfortably at that time, but they are too young to sit at home and “twiddle their thumbs” (do nothing for a period of time). So many professional athletes “engage in” (become involved in) other activities after they retire from professional sports.
Some professional athletes choose to “remain” (stay; continue to be) “affiliated” (connected) with professional sports. They may become “coaches” (people who teach others how to play a sport), or managers or owners of sports teams. Other retired professional athletes become “commentators,” speaking about games on television or radio letting viewers or listeners know what is happening and providing their opinions based on their experience playing the sports.
Other professional athletes “channel” (direct) their experience into business “ventures” (risky ways to try to make money). Some athletes become authors, writing books about their experience as professional athletes. Sometimes athletes write “self-help books” (books intended to help readers improve their life) based on the skills and techniques they “acquired” (obtained) and “refined” (improved) while playing sports. Others become professional speakers, giving “motivational” (encouraging; causing others to feel like they want to do something) speeches at special events and conferences.
Still other professional athletes spend their retirement helping others. Some athletes start “nonprofit” (not intended to make money) organizations to encourage children and young adults to succeed through athletics and education. They might “promote” (encourage) healthy living or community involvement through sports.
Comprehension Answers
1 - b
2 - c