= 0824
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 824: Grooming a Successor.
This is English as a Second Language Podcast episode 824. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com. Become a member of ESL Podcast and download the Learning Guide for each of our episodes.
This episode is a dialogue about getting someone ready to become the leader of a company or of an organization. Let’s get started.
[start of dialogue]
Aisha: It’s only a matter of time before I retire and hand over the reins to someone else.
Javier: That won’t happen for years.
Aisha: It’ll happen sooner than you think. I’ve given a lot of thought to the person I want to fill my shoes. After long consideration, I think that person should be you.
Javier: Me? But there are a lot of people who outrank me in this organization and who have more experience.
Aisha: That may be true, but I’ve decided to make you my protégé. I’m taking you under my wing starting now to groom as my successor.
Javier: I don’t know what to say. I’m honored, of course, but aren’t you going to meet with a lot of resistance by choosing me instead of someone more senior?
Aisha: I might, but I have confidence in you. With a little time, you’ll come into your own and you’ll make a fine leader for this organization.
Javier: All I can say is thank you for having faith in me.
Aisha: The opportunity is yours and it’s up to you what you make of it.
Javier: I know that this is a once-in-a-lifetime opportunity. I won’t let you down.
Aisha: I’m counting on that.
[end of dialogue]
Aisha begins our dialogue by saying, “It’s only a matter of time before I retire and hand over the reins to someone else.” The expression “it’s only a matter of time” is used to describe something that will definitely happen in the future but you don’t know exactly when, but it will happen. “It’s only a matter of time before Miss Universe calls me and asks me for some personal English lessons.” It’s only a matter of time; it will happen, I just don’t know when. Aisha says it’s only a matter of time before she retires. “To retire” (retire) means to stop working, basically to stop working for the rest of your life. So when you are 65 or 70 you often – at least in the United States at those ages – will retire; you will quit your job and you will no longer work full-time. At least that’s the way it traditionally has been, we’ll see what happens in the future, depending on our economy.
Aisha is planning on retiring, and when she does she will hand over the reins (reins). “To hand over (something)” is a phrasal verb meaning to give something to someone else. The “reins” – (reins), not (rains) – is what you use to control a horse. They’re the little ropes that you hold onto that you use to control a horse, to turn it from one side to the other. Here, it means the control of something, so Aisha will hand over control of the organization or the company to someone else.
Javier says, “That won’t happen for years.” You won’t be retiring for many years, he says. Aisha, however, has different ideas. She says, “It will happen sooner than you think.” She actually says, “It’ll happen,” “it’ll” being a contraction for “it will.” “It will happen sooner than you think,” sooner than you might imagine. She says, “I’ve given a lot of thought,” meaning I thought about something a lot, “I’ve given a lot of thought to the person I want to fill my shoes.” “To fill (someone’s) shoes” means to perform the same duties and the same activities as another person normally does. So, when someone leaves as president, the next person becomes president fills his or her shoes; he does or she does what that other person used to do. Aisha says, “After long consideration,” meaning after thinking about it very carefully for a long time, “I think that person should be you,” meaning you should be the next leader of this organization.
Javier says, “Me?” He’s surprised. I’m kind of surprised, too. Javier, eh, not that intelligent I don’t think! Anyway, he says, “But there are a lot of people who outrank me in this organization.” “To outrank” (outrank – one word) means to have a higher position or to have greater authority in an organization. So, a company might have a president, it might have a couple of vice-presidents, and then it might have some managing directors. Well, the president outranks the vice-president; he or she is higher in the organization than the vice-president, and the vice-presidents outrank the managers. Javier is saying there are other people in this company who outrank him and who have more experience.
Aisha says, “That may be true,” meaning maybe you’re right, “but I’ve decided to make you my protégé.” “Protégé” (protégé) is a person who receives support, advice, and guidance from an older, more experienced person, especially as preparation for that person to take over the job of the older person. So someday when I get old – I mean really old, not old like I am now – someday when I get really old I will probably find a young version of me – a young Jeff McQuillan – and I will make him my protégé. I will train that person so they can take over as ESL Podcast’s host many years now – many, many years from now, however. Aisha says, “I’m taking you under my wing (Javier).” “To take (someone) under your wing” (wing) means to begin to make someone your protégé, to begin to take that person and give them advice, give them suggestions, give them guidance. It’s something that an older person would do for a younger person in an organization.
Aisha’s going to take Javier under her wing, and she’s going to groom him as her successor. “To groom” (groom) here means to prepare another person to do a certain job, often your job. It’s similar to taking someone under your wing or making someone your protégé. In this case, Aisha is going to groom Javier as her successor (successor). I should mention the word “groom” has a couple of different meanings – very different. Take a look at our Learning Guide for those. I don’t want you to use that word in the wrong way, take a look at the Learning Guide. A “successor” is the person who takes over your job, the person who comes after someone else as the person taking that job.
Javier says, “I don’t know what to say.” He’s surprised. He says, “I’m honored, of course,” meaning here sort of I’m flattered or I feel very good about you telling me this, “but aren’t you going to meet with a lot of resistance by choosing me instead of someone more senior?” Javier is asking Aisha if she’s going to meet a lot of resistance, meaning people are going to oppose her, people are going to be against her decision. The reason they would be against her decision is because Javier is not the most senior person in the company. “Senior” (senior) here means to have more experience in the company. Usually that means you’re older. It doesn’t mean that you are what we call a “senior citizen,” that would be someone over, say, 65 or 70 years old. Here it just means someone with more experience at that organization, or in that organization.
Aisha says, “I might, (I might meet some resistance) but I have confidence in you. With a little time, you’ll come into your own and you’ll make a fine leader for this organization.” The phrase “to come into your own” means to achieve the level of ability or competence in something that you are able to succeed at a job or succeed in a certain position. “To come into your own” means to mature, to get the necessary experience so that now you are ready to do this job.
Javier says, “All I can say is thank you for having faith in me.” “To have faith (faith) in (someone)” means to believe in someone, to believe that someone can do something.
Aisha says, “The opportunity is yours and it’s up to you what you make of it.” When we say something is “up to” someone – “it’s up to you,” “it’s up to John,” “it’s up to Phil” – we mean that’s the person who has the power to make something happen, to make something succeed or fail. It’s the same as saying “it depends upon you” or “it depends on what you do.” “It’s up to you to go and study harder to pass your test.” It’s not something I can do, it’s only something you can do; you’re the one that has that power. Aisha says it’s up to Javier what he makes of it. The expression “what you make of (something)” means what you do with an opportunity, how you take advantage of a chance – an opportunity to do something. “What will you make it?” How will you use this opportunity?
Javier says, “I know that this is a once-in-a-lifetime opportunity.” “Once in a lifetime” means it only happens once in your entire life. Once-in-a-lifetime opportunity would be an opportunity – a chance – that will only happen once in your life. Javier says, “I won’t let you down.” “To let (someone) down” (down) means to disappoint someone, not to meet someone’s expectations. Aisha says, “I’m counting on that.” To count on (something)” means to rely on, to depend on something. “I’m counting on you to finish this job.” I’m relying on you; I’m depending on you.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Aisha: It’s only a matter of time before I retire and hand over the reins to someone else.
Javier: That won’t happen for years.
Aisha: It’ll happen sooner than you think. I’ve given a lot of thought to the person I want to fill my shoes. After long consideration, I think that person should be you.
Javier: Me? But there are a lot of people who outrank me in this organization and who have more experience.
Aisha: That may be true, but I’ve decided to make you my protégé. I’m taking you under my wing starting now to groom as my successor.
Javier: I don’t know what to say. I’m honored, of course, but aren’t you going to meet with a lot of resistance by choosing me instead of someone more senior?
Aisha: I might, but I have confidence in you. With a little time, you’ll come into your own and you’ll make a fine leader for this organization.
Javier: All I can say is thank you for having faith in me.
Aisha: The opportunity is yours and it’s up to you what you make of it.
Javier: I know that this is a once-in-a-lifetime opportunity. I won’t let you down.
Aisha: I’m counting on that.
[end of dialogue]
Our scriptwriter never lets us down; she always has wonderful scripts. That’s the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
happen, but one does not know when
* It’s only a matter of time before Cheryl’s manager realizes that she spends all her time playing games online instead of working.
to retire – to stop working, usually when one is 62 or 65 years old
* If we don’t start saving more money, we won’t be able to retire until we’re 90!
to hand over the reins – to give someone one’s power, control, authority, or leadership position
* Blake almost never hands over the reins, so the fact that he asked you to work on this project while he is traveling is an honor.
to fill (one’s) shoes – to perform the duties and activities of another person; to do what another person normally does
* The previous vice-president was very good at her job, but we believe you can fill her shoes.
consideration – careful thought about something, often over a period of time
* I’m really excited about this job opportunity and I thank you for your consideration of my application.
to outrank – to have a higher position and greater authority in an organization
* The manager outranks me, so I won’t be able to give you permission without her input.
protégé – a person who receives guidance and support from an older, more experienced person, especially as preparation for that person to have the older person’s job in the future; a mentee
* Carl was very upset when his father, who owns a large business, chose someone outside of the family to be his protégé.
to take (someone) under (one’s) wing – to begin to offer someone guidance, advice, and protection, especially a younger and/or less experienced person
* Thanks for taking me under your wing during my first few weeks in the city. It was really helpful.
to groom – to prepare someone to do or be something by providing advice, guidance, and criticism
* Even as very young babies, princes are groomed to become king.
successor – a person who has a job after another person has left that job
* How long did it take the company to find your successor?
resistance – efforts to prevent something from happening or to not let something happen; opposition
* Do you anticipate a lot of resistance to the new policy?
senior – having spent a lot of time in an organization or position and having a lot of experience
* Frannie spent three years working as a junior sales representative before the company made her a senior sales manager.
to come into (one’s) own – to achieve competence (an ability to do something well) and success using one’s abilities
* Charles really came into his own in his late 20s.
to have faith in (someone) – to believe in someone; to believe that someone is able to do something
* Li wouldn’t have put you in charge of this project if she didn’t have faith in you.
up to (one) – within someone’s power to make something succeed or fail; depending on someone’s decisions or actions
* We’ve cleaned the car and fixed the dent, so now it’s up to you to sell it at a good price.
what (one) makes of (something) – what one does with an opportunity; how much benefit one is able to get out of something; how much effort one puts into something to achieve some goal or benefit
* Parents can help their children get the finest education, but then they have to wait and see what their children make of it.
once-in-a-lifetime opportunity – a very good opportunity that does not happen very often or to very many people, so one must take advantage of it
* Jane received a once-in-a-lifetime opportunity to fly in the space shuttle.
to let (someone) down – to disappoint someone; to not meet someone’s expectations or hopes
* Nancy really let down her son when she forgot to go to his baseball game.
to count on (something) – to rely or depend on something
* We’re counting on you to finish that report by Tuesday.
Comprehension Questions
1. Why is Javier surprised by Aisha’s decision?
a) Because he doesn’t think he has enough experience.
b) Because he doesn’t think he is smart enough.
c) Because he doesn’t think it complies with company policies.
2. Why does Javier thank Aisha for having faith in him?
a) Because she’s a very religious person.
b) Because she believes he will succeed.
c) Because she always tells the truth.
Answers at bottom.
What Else Does It Mean?
to groom
The verb “to groom,” in this podcast, means to prepare someone to do or be something by providing advice, guidance, and criticism: “Each summer, the company chooses one intern to groom as a new employee.” When talking about animals and especially horses, “to groom” means to clean an animal and brush its fur (hair): “How much time do you spend grooming your horse before a competition?” The verb “to groom” can also mean to try to improve one’s appearance by making changes to one’s clothing, hair, and makeup: “Is Sheila grooming herself in front of the bathroom mirror again?” Finally, as a noun, a “groom” is a man on his wedding day, or on the day when he will get married: “The groom is getting very nervous.”
to let (someone) down
In this podcast, the phrase “to let (someone) down” means to disappoint someone by not meeting his or her expectations or hopes: “Willie let his team down when he dropped the ball in the last few seconds of the game.” The phrase “to let (one’s) hair down” means to relax, stop worrying, and have a good time: “Meg had a difficult week at work, so this weekend she plans to let her hair down and go dancing.” The phrase “to let (one’s) guard down” means to stop worrying about something and stop trying to protect oneself or hide something: “Adam let his guard down and told Constantine everything, but later he wished he hadn’t.” Finally, the phrase “to let (someone) down gently” means to end a romantic relationship gently to avoid hurting the other person very much: “Ryan let his girlfriend down as gently as he could.”
Culture Note
Corporate Succession: Apple Computers
Many companies “engage in” (are involved in) “succession planning,” trying to identify “new talent” (people who are good in a particular field or in a particular type of job) and groom those individuals to “assume” (take; accept) leadership positions as older leaders retire or “otherwise” (in some other way) leave the organization.
Apple’s “esteemed” (greatly admired and respected) co-founder, Steve Jobs, “resigned” (said that he would no longer work in his job) as “CEO” (chief executive officer) in August 2011, but he and the company had a succession plan. As he resigned, he strongly recommended that Tim Cook be named the next Apple CEO while Jobs would remain Chairman of the Board of Directors.
Cook already had a long history with Apple. Jobs “hired him away from” (gave him a job offer so he would leave his current company) in 1998. Cook made many good business decisions and he was promoted to “COO” (chief operating officer) in 2007.
Apple also gave Cook a “trial run” (a test; an opportunity to prove that something or someone can succeed) in 2004. Jobs took a “leave of absence” (a temporary period of time when one does not work for a company) for health reasons. During that two-month period, Cook served as the “interim” (temporary) CEO of Apple. He did so again in 2009 and 2011 when Jobs took additional leaves of absence for health reasons.
When Jobs resigned in August 2011, the company and “shareholders” (people who own stock in Apple) had already observed his performance as CEO and had “confidence” (a belief that something will succeed) in his abilities. So far, the succession plan has been a success with a “smooth” (without major problems) transition of power.
Comprehension Answers
1 - a
2 - b