= 0845
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 845: Dropping Out of College.
This is English as a Second Language Podcast episode 845. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is to be found at eslpod.com. To be found on our website are the Learning Guides for these episodes. If there’s something you don’t quite understand, you want more explanation, take a look at the Learning Guide.
This episode is a dialog between Aaron and Margo about leaving college before you are finished. Let’s get started.
[start of dialog]
Aaron: Mom, I have something to tell you and you’re not going to like it.
Margo: What is it?
Aaron: I’m dropping out of college. I want to get out into the real world and get a job. I’m wasting time in school.
Margo: You’ll get a better job if you stay in school and graduate with a degree. You’ll have more earning power and better long-term prospects.
Aaron: I’m sick of school. All of my friends are earning money, buying cars, and living life. I feel like life is passing me by.
Margo: Your friends didn’t go to college and got a job right out of high school.
Aaron: That’s right. There’s nothing wrong with that.
Margo: No, there isn’t. And right now, they seem to be living the high life. They don’t have any responsibilities and can blow their paychecks on having fun. Once they have a family, their paychecks won’t stretch very far. With a degree, you’ll out-earn them right out of the gate when you graduate in two years.
Aaron: I don’t want to wait.
Margo: This is all about delayed gratification. A little suffering now will pay off in the long run. Trust me. Two more years and you’ll be done.
Aaron: Yeah, maybe I can stick it out for two more years and then no more school – ever!
Margo: Unless you decide to go to graduate school...
Aaron: Mom, don’t push it.
[end of dialog]
Aaron says to Margo, who we find out is his mother, “Mom, I have something to tell you and you’re not going to like it.” This, of course, is the worst way to begin any conversation. “I have something to tell you and you’re not going to like what I have to tell you.” Margo says – Aaron’s mom – “What is it?”
Aaron says, “I’m dropping out of college.” “To drop out” is a two-word phrasal verb meaning to stop going to school before you have completed your education, before you have received your degree or certificate. You can drop out of high school. We have many young people who stop going to high school after they turn 16 years old. In the United States, in most states, you can leave high school when you turn 16, even though you haven’t completed your high school diploma or certificate. The normal age is 18 to complete high school – 17 or 18. It is possible to stop going to school before that. That’s what we call “dropping out.” You can also drop out of college, leave college before you finish your degree. That’s what Aaron wants to do.
He says, “I want to get out into” – or to go into – “the real world and get a job.” When people say “the real world,” they mean not inside of a school, to be out where people are working, doing things like making money. Aaron says, “I’m wasting time in school.” “To waste time” means you aren’t doing anything very useful or productive. Margo says, “You’ll get a better job if you stay in school and graduate with a degree.” Margo is trying to convince her son that if he wants to get a good job, he should stay in school and graduate. “To graduate” means to complete your program. I graduated from high school in 1981. That’s when I completed my high school degree – my high school “diploma”, we would call it. “Degree” is usually a word we use when you finish some sort of college program. You can have an undergraduate degree, what we call a “Bachelor’s degree,” or you could have a “graduate degree,” such as a Master’s or a doctorate.
Margo says, “You’ll have more earning power and better long term prospects.” Margo was saying to Aaron: If you graduate with a degree, you’ll have more “earning power.” “Earning” (earning) refers to getting money by working. “Earning power” is the ability to make a lot of money from your work. “Long-term” means for a very long time. “Prospects” (prospects) refer to opportunities. So, “long-term prospects” are your opportunities for the future, for many years into the future.
Aaron says, however, “I’m sick of school” I’m tired of school. “All of my friends are earning money, buying cars, and living life” – living a normal life. “I feel like life is passing me by.” The expression, “life is passing me by,” or passing someone by, means that you feel that your life is very boring, that you’re getting older but you’re not getting more out of life. You’re not enjoying life the way other people enjoy life. That’s the meaning of the expression “Life is passing me by.”
Margo says, “Your friends didn’t go to college and got a job right out of high school,” meaning immediately after they finished high school. Aaron says, “That’s right” – that’s correct. “There is nothing wrong with that,” meaning that’s okay. Margo says, “No. There isn’t.” She’s agreeing with Aaron that there isn’t anything wrong with getting a job when you graduate from high school and not going to college.
However, she’s also reminding Aaron that in the future he will be better off than his friends. He will have a better job than his friends because he did wait to get a job and go to college instead. Margo says, “Right now” – at this moment – “your friends seem to be living the high life.” The “high (high) life” is a relaxed, comfortable, exciting life, spending a lot of money on your own comfort, your own entertainment, a good life. And that’s what Margo is saying that Aaron’s friends are doing right now. “They’re living the high life. They don’t have any responsibilities and can blow their paychecks on having fun.” “To blow (blow) your money on something” means to spend it on something that isn’t very important, or to waste your money on something that isn’t very useful. I’m going to go to Vegas and gamble. I’m going to go to Las Vegas and play cards and gamble a million dollars. I’m going to blow a million dollars. Well, I don’t have a million dollars but it’s just an example. “To blow it” means to waste it – to lose it, in this case.
Margo says that Aaron’s friends can blow their paychecks on having fun. Your “paycheck” is the money you receive for working at your job. Margo says, “Once they have a family” – once they get married and have children – “their paychecks won’t stretch very far.” “To not stretch (stretch) very far” means they won’t be able to pay for everything they want and need because they won’t have enough money. So, if you only have to worry about yourself, you may be able to buy whatever you want. But when you get married and have a family and have children, well then, your money will not stretch very far. You will have less money to spend because you have more things to buy.
Margo says, “With a degree” – with a college degree – “you’ll out-earn them” – your friends – “right out of the gate when you graduate in two years.” “To out-earn” means to earn more than, to get more money at a job than the other people. To “out-“ anything means to do more of that. You can out-perform. You can out-sing. You could out-swim, meaning you would perform better. You would sing better. You would swim better than the other people. “Right out of the gate” (gate) means immediately. As soon as you graduate, right out of the gate, you will start to make more money than your friends.
Aaron says, “I don’t want to wait.” This, of course, is the problem of many young people. They do not understand that you need to wait in order to good things in life if you spend time wisely. But they don’t want to wait. Margo says, “This is all about delayed gratification.” “Gratification” is getting good things in your life. “To delay” (delay) means to wait. So, “delayed gratification” is waiting for the good things. Many people can’t delay their gratification. They want gratification right now. And so, instead of going to college and getting a degree, they want to go out and get a job right away, or when they get money, the first thing they do is they spend their money, even though they should, perhaps, wait, save their money and buy something in the future instead. Margo says, “A little suffering” – a little pain – “now, will pay off in the long run.” “To pay off” means to be worthwhile, to have benefits. The “long run” means in the future, in the long term, which is an expression we used earlier.
Aaron’s mom says, “Trust me, two more years and you’ll be done.” Aaron says, “Yeah, maybe I can stick it out for two more years.” “To stick it out” means to wait, to delay. “And then no more school, ever.” Margo says, “Unless you decide to go to graduate school.” “Graduate school” is where you go after you finish your Bachelor’s, if you want a Master’s or a doctorate in something.
Aaron says, “Mom, don’t push it.” The expression “Don’t push it!” means stop right there. Don’t try to get a better deal or don’t try to get even more out of this negotiation or this conversation. We often use the expression jokingly, humorously – “Don’t push it.” So, for example, your daughter asks you if she can use your car to go to a movie. And you say, “Okay, fine.” And then she says, “Oh, and can you also pay for the movie?” You say to her, “Don’t push it,” meaning you’ve already gotten something good, don’t ask for more.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Aaron: Mom, I have something to tell you and you’re not going to like it.
Margo: What is it?
Aaron: I’m dropping out of college. I want to get out into the real world and get a job. I’m wasting time in school.
Margo: You’ll get a better job if you stay in school and graduate with a degree. You’ll have more earning power and better long-term prospects.
Aaron: I’m sick of school. All of my friends are earning money, buying cars, and living life. I feel like life is passing me by.
Margo: Your friends didn’t go to college and got a job right out of high school.
Aaron: That’s right. There’s nothing wrong with that.
Margo: No, there isn’t. And right now, they seem to be living the high life. They don’t have any responsibilities and can blow their paychecks on having fun. Once they have a family, their paychecks won’t stretch very far. With a degree, you’ll out-earn them right out of the gate when you graduate in two years.
Aaron: I don’t want to wait.
Margo: This is all about delayed gratification. A little suffering now will pay off in the long run. Trust me. Two more years and you’ll be done.
Aaron: Yeah, maybe I can stick it out for two more years and then no more school – ever!
Margo: Unless you decide to go to graduate school...
Aaron: Mom, don’t push it.
[end of dialog]
She went to graduate school and is now living the high life, I hear. I speak, of course, of our very own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen again, right here on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
to drop out – to stop attending a school or educational program before one has finished or earned a degree or certificate
* Yolanda dropped out of college during her third year to stay at home and help her father, who was ill.
the real world – actual personal and professional experiences where one has responsibilities, not living with one’s parents or going to school full-time
* Once Francine entered the real world, she realized how hard it was to plan and prepare healthy meals each evening after working all day.
to graduate – to complete an educational program and earn one’s degree
* Lola graduated from high school in 1995.
degree – diploma or certificate; an official piece of paper stating that one has completed an academic program, meeting all the requirements, and now has a certain level of knowledge and/or experience
* Sam has an undergraduate degree in chemical engineering and a graduate degree in biochemistry.
earning power – how much money one is able to make over a certain period of time or after working a certain number of hours, usually related to one’s education and experience
* People with a master’s degree have greater earning power than people with only a high-school education.
long-term prospects – opportunities that will be available to oneself in the future, but are not available right now, especially when talking about jobs
* If the health care system continues to expand, there are very good long-term prospects for doctors and nurses.
for life to pass (one) by – the feeling or perception that one’s life is very boring or routine and one is getting older, but is not developing or enjoying life as much as one should or as much as other people are
* Maggie is complaining that life is passing her by, since she spends every day at work while her friends are traveling around the world.
the high life – a relaxed, comfortable, and exciting way of living, spending a lot of money on one’s comfort and enjoyment
* Many people think that actors are living the high life, but most actors are struggling to find paying jobs.
to blow – to spend a lot of money to buy expensive things that are not necessary
* How could you blow $2,000 on a dress?
paycheck – money received in exchange for one’s work, usually every week or every 15 days
* After deductions for taxes and retirement savings, there isn’t much money left in my paycheck.
to not stretch very far – to not be able to pay for everything one wants or needs with the limited amount of money one has
* Kylie was hoping to work for a nonprofit organization, but the salary offers she’s receiving won’t stretch very far.
out- – to do more of something than other people are doing; to do something to a greater extent than other people are doing something
* Bernard is an excellent student who always wants to out-perform the other students.
right out of the gate – immediately; at the beginning; from the beginning or outset
* There were major problems with their business plan right out the gate.
delayed gratification – one’s ability to work hard now and enjoy the benefits later, rather than choosing to enjoy more limited benefits right away
* The psychologists conducted a study in delayed gratification by giving preschoolers two marshmallows and telling them that if they waited five minutes without eating them, they would receive two more.
suffering – the experience of pain or discomfort
* Dr. Neill specializes in medication management and tries to find ways to minimize his patients’ suffering.
to pay off – to be worthwhile; to have benefits that are greater than the sacrifice needed to obtain something
* Justina practiced piano for hours each day, but it all paid off when she was accepted into music school.
long run – long term; over a long period of time; in the distant future, not right away
* In the long run, these investments will help our company grow stronger and increase sales.
graduate school – education beyond a bachelor’s (undergraduate) degree, usually to earn a master’s degree or a Ph.D. (doctorate)
* Tolola is earning a degree in political science, and then she plans to go to graduate school to become a lawyer.
don’t push it – a phrase used to warn someone to stop trying to get more of something or to get a better deal, often used humorously
* The ad listed the used car for $8,000 and we tried to negotiate a lower price, but the seller said, “Don’t push it.”
Comprehension Questions
1. Why does Aaron want to drop out of college?
a) Because he wants to earn money like his friends.
b) Because he’s doing very poorly in his classes.
c) Because he thinks college is boring.
2. What does Aaron mean when he says, “life is passing me by”?
a) He thinks he is going to die soon.
b) He isn’t having interesting or exciting experiences
c) He is surprised by how quickly time is passing.
Answers at bottom.
What Else Does It Mean?
degree
The word “degree,” in this podcast, means a diploma or certificate stating that one has completed an academic program and has a certain level of knowledge and/or experience: “They want to hire someone with a degree in journalism or communications and at least three years’ experience working for a magazine publisher.” A “degree” is also a measure of temperature: “Wow, it’s going to be more than 100 degrees outside tomorrow!” In mathematics, a “degree” measures an angle: “There are 360 degrees in a circle.” The word “degree” can also mean extent, describing how much there is of something: “To a certain degree, we are all selfish.” Finally, the phrase “by degrees” means very slowly and gradually: “The doctors anticipate that Aunt Sunny will get better by degrees as long as she continues to take her medicine.”
to blow
In this podcast, the verb “to blow” means to spend a lot of money to buy expensive things that are not necessary: “I wouldn’t mind paying taxes if I were certain the government wouldn’t blow the money on bad programs.” The phrase “to blow (one’s) nose” means to clean the inside of one’s nose by pushing out a lot of air while holding a piece of tissue or cloth in front of one’s nose: “Please don’t blow your nose at the dinner table.” Finally, the phrase “to blow a kiss” means to kiss one’s hand and then hold it in front of one’s mouth and push air from one’s mouth in the direction of another person: “The little girl smiled and blew a kiss through the window as she watched her father drive to work.”
Culture Note
Non-Traditional College Options
Many people who drop out of college “regret” (feel bad about; wish one hadn’t done something) their decision later in life. They wish they had more experience and education so that they could get a better-paying job, but they don’t “feel at liberty” (believe they have the freedom or ability) to stop working and return to school as full-time students.
Fortunately, full-time workers have many “non-traditional college options” (ways to attend college without being at school all day). Many programs offer classes in the evenings and on weekends. These classes are designed for older students who are already “in the workforce” (working in jobs).
Other full-time workers choose to “enroll in” (begin participating in a school program) online degree programs. These programs allow students to study on their own and take classes online using video technology to listen to lectures and ask questions of the teachers. Some of these programs require that the students go to the institution “periodically” (sometimes; from time to time) to take exams, but “for the most part” (mostly) students can study from their home or office.
Still other full-time workers can take advantage of workplace training opportunities and continuing education. Some employers organize courses in the workplace, so that employees can take classes before or after their “shift” (the period of time when one works) or during their lunch break. Many of these courses are “subsidized,” meaning that the employer pays part or all of the registration fee “on behalf of” (for the benefit of) the employees, as long as they continue to perform well in the classes.
Comprehension Answers
1 - a
2 - b