= 0846
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 846: Donating Blood.
This is English as a Second Language Podcast episode 846. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. I’m going to speak very low. No, not really.
We have a website. You know where it is. It’s at eslpod.com. Go there, become a member, help keep us going here at ESL Podcast.
This episode is a dialog between Michelle and Gabriel about donating or giving some of your blood to people who need it. Let’s get started!
[start of dialog]
Michelle: Did you hurt yourself?
Gabriel: No, why?
Michelle: You have a Band-Aid on your arm.
Gabriel: Oh, that. I donated blood today.
Michelle: You did? That’s great. I’d like to donate blood, but every time I get close to a needle, I feel light-headed. I’m afraid if I go through with it, and they actually draw blood, I’ll faint.
Gabriel: I’m used to it. I give blood all the time. The needle doesn’t bother me.
Michelle: That’s very admirable. I know how important it is for hospitals to have a good supply of blood for use in transfusions.
Gabriel: I don’t mind doing it. It’s not a big deal.
Michelle: But it is a big deal. If relief organizations didn’t have enough blood when they traveled to disaster areas, they couldn’t help the injured people there. I’m sure that’s why you do it, right?
Gabriel: Well...
Michelle: Well, what?
Gabriel: There is a particularly pretty nurse who works in the bloodmobile...
Michelle: Ah.
[end of dialog]
Michelle begins by saying to Gabriel, “Did you hurt yourself?” Gabriel says, “No, why?” Michelle says, “You have a Band-Aid on your arm.” A “Band-Aid” (band-aid) is actually the name of a product of a company here in the United States. It’s a bandage. It’s a small piece of cotton that has a piece of tape on it that you put over a cut on your skin. So, if you cut your finger and it’s bleeding – blood is coming out – you might put a Band-Aid on it. That is a bandage. We say “Band-Aid” even when it’s not the bandage made by that company. We have another similar term “Kleenex” (Kleenex), which is basically tissue paper you use to blow your nose, to clean out the inside of your nose, if you will. We say “Kleenex” even though that’s technically just one company’s tissue paper.
Michelle is asking if Gabriel hurt himself because he has a Band-Aid on his arm. Gabriel says, “Oh, that. I donated blood today.” “To donate blood” means to give some of your blood to a hospital or to an organization like the Red Cross, to help people who need blood. When you get hurt or sick and go to a hospital, often they need to give you more blood. Where do they get the blood? From people who donated.
Michelle says, “You did? That’s great! I’d like to donate blood but every time I get close to a needle, I feel light-headed.” “Needle” (needle) is that long, sharp thing they put inside of your body. They basically put a hole in your skin in order to get the blood out. You also use a needle for putting something into your body, like a drug. “Light-headed” is the same as dizzy, a feeling that you may fall down. It feels like the world is spinning around you. That’s to feel light-headed.
Michelle says, “I’m afraid if I go through with it and they actually draw blood, I’ll faint.” “To go through with something” means to do something that is, perhaps, difficult or even a little dangerous. But you go ahead and do it anyway. You have the courage, the strength to do this difficult thing. Michelle is afraid that if she goes through with it – if she actually goes to a place to donate her blood – “and they actually draw blood,” meaning they actually take blood out of her, “I’ll faint.” “To faint” (faint) is to, basically, lose consciousness. You fall asleep. If you are standing, fall down and become unconscious, typically, for a short period of time.
I’ve only fainted once in my life. I was…yeah, that was a long time ago. I was sitting at a chair and someone was rubbing my neck. I know it sounds a little weird. But someone was rubbing my neck and it was so relaxing that I fainted. I can remember that very well. It was probably 25 years ago. Well, some people faint when they hear bad news. Some people faint when they see something they don’t like, like blood.
Michelle is afraid that she’ll faint if she actually goes and donates blood. Gabriel says – because he’s a man – “I’m used to it. I give blood all the time. The needle doesn’t bother me,” meaning it doesn’t cause me any problems. Michelle says, “That’s very admirable.” Something that is “admirable” (admirable) is something that is impressive, something that other people respect, other people realize is important. Michelle says, “I know how important it is for hospitals to have a good supply of blood for use in transfusions.” “Transfusions” are when a doctor at a hospital, typically, will be giving you new blood. They are transferring someone else’s blood into your body, for some medical reason.
Gabriel says, “I don’t mind doing it.” “I don’t mind” means it doesn’t bother me. It’s not a problem. He says, “It’s not a big deal,” meaning it’s nothing that’s very important, nothing that causes any trouble. Michelle then says, “It is a big deal.” Here, “big deal” means something important, something makes a difference. She says, “If relief organizations didn’t have enough blood when they travelled to disaster areas, they couldn’t help the injured people there. “Relief organizations” are organizations like the Red Cross or the Red Crescent that go into areas where people are suffering, perhaps because of a war or a hurricane or some other natural disaster, some other terrible event, and they help people in those areas. They give them food, water, and so forth.
Michelle says, “If relief organizations didn’t have enough blood when they travelled to disaster areas, they couldn’t help the injured people there.” A “disaster (disaster) area” is an area where something very bad has happened – a war, a hurricane, an earthquake, that sort of thing. “To help injured people” means to help people who are hurt. “To be injured” (injured) means that you are hurt. You have some part of your body that has been hurt or been damaged, maybe you broke your leg, maybe you’ve been cut – whatever the injury is.
Michelle says, “I’m sure that’s why you do it, right?” She’s saying to Gabriel, I’m sure the reason you donate your blood is to help people who need help, these relief organizations, for example. Gabriel says, “Well…” Michelle says, “Well what?” He doesn’t seem to want to give the real answer and then he does. He says, “There is a particularly pretty nurse who works in the bloodmobile.” Now, we find out why Gabriel goes and donates his blood. It’s not because he wants to be a good person. It’s because there’s an attractive, a physically attractive, good-looking nurse in the bloodmobile.
A “nurse” (nurse) is a professional who helps doctors. Many nurses, most nurses, are female, in most countries. But there’re also, of course, male nurses. But male nurses are the exception. In fact, typically, if you are a nurse who is male, we’ll often use the expression “male nurse” so that people know that you’re not a woman. Of course, if they saw you, they probably know you’re not a woman, but you know what I mean.
Well, Gabriel happens to like a pretty nurse who works in the “bloodmobile.” The “bloodmobile” (bloodmobile) – one word – is a large van or truck that travels around from place to place and inside of it. It has equipment needed so that you can donate blood. “Bloodmobiles” are very popular in the United States. They go to buildings or to big events and allow people to donate blood so they don’t have to go to a hospital or to a doctor’s office. Michelle now understands why Gabriel wants to donate blood so often. He wants to go and talk to the pretty nurse. The question is, does the pretty nurse want to talk to Gabriel?
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Michelle: Did you hurt yourself?
Gabriel: No, why?
Michelle: You have a Band-Aid on your arm.
Gabriel: Oh, that. I donated blood today.
Michelle: You did? That’s great. I’d like to donate blood, but every time I get close to a needle, I feel light-headed. I’m afraid if I go through with it, and they actually draw blood, I’ll faint.
Gabriel: I’m used to it. I give blood all the time. The needle doesn’t bother me.
Michelle: That’s very admirable. I know how important it is for hospitals to have a good supply of blood for use in transfusions.
Gabriel: I don’t mind doing it. It’s not a big deal.
Michelle: But it is a big deal. If relief organizations didn’t have enough blood when they traveled to disaster areas, they couldn’t help the injured people there. I’m sure that’s why you do it, right?
Gabriel: Well...
Michelle: Well, what?
Gabriel: There is a particularly pretty nurse who works in the bloodmobile...
Michelle: Ah.
[end of dialog]
I think the scripts written by our own Dr. Lucy Tse are very admirable. I hope you do, too.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
Band-Aid – a bandage; a brand name for a small piece of cotton placed on a sticky piece of tape, used to cover cuts in one’s skin to keep them clean and help them heal more quickly
* When Nolan was learning how to walk, he fell down a lot, so he always had Band-Aids on his knees.
to donate blood – to give some of one’s blood to a hospital or an organization that will clean it and give it to other people who need it for medical reasons
* When people donate blood, are they able to find out who used it?
needle – a thin, long tube of metal with a pointed end, used to enter one’s blood vessel through the skin to deliver medicine or remove blood
* The nurse had to try three times before he was able to get the needle into Kirk’s vein.
light-headed – dizzy and/or faint; the feeling that one is not balanced and might fall down and/or lose consciousness
* When Alycia started feeling light-headed, she knew she had exercised too hard and she needed to rest and drink some water.
to go through with (something) – to do something that is risky, challenging, or very difficult and requires a lot of courage or commitment
* Justina says she wants to buy a house, but she’s worried about borrowing so much money. I wonder if she’ll actually go through with it.
to draw – to take something away or pull something out; to remove something, especially money from an account or blood from a body
* Do you know how to draw out the poison when someone is bitten by a snake?
to faint – to lose consciousness; to fall down and seem to be asleep, unaware of what is happening around oneself, usually when one is very frightened or very hungry
* If I don’t get something to eat soon, I’ll faint!
admirable – impressive; something that other people respect and realize is important or worthwhile
* Becca thinks it’s admirable that Edgar spends so much time volunteering in the local schools.
transfusion – the transfer of blood from one person’s body to another for medical reasons
* Jim lost a lot of blood in the accident and needed a transfusion at the hospital.
relief organization – a nonprofit organization that provides, food, water, medicine, and shelter (housing) to people who suffer during natural disasters or wars
* The relief organization provided drinking water, rice, and dried beans to hundreds of villagers after the earthquake.
disaster area – an area where many buildings have been destroyed and there is little or no clean water or electricity, usually after an earthquake, tornado, hurricane, or fighting
* The governor has declared the entire county a disaster area as a result of the flooding.
injured – hurt; suffering from damage caused to one’s body
* It’s amazing that nobody was injured in the car accident!
nurse – a professional who has medical training and assists doctors in caring for patients
* The hospital is hiring nurses to work in its operating rooms.
bloodmobile – a large van or truck that has all the equipment needed so that people can go inside and donate blood at a convenient place
* Each year, the company lets the bloodmobile park in its parking lot for one week while it encourages employees to donate blood.
Comprehension Questions
1. What does Gabriel have on his arm?
a) A bandage to stop the blood from flowing.
b) A sticker stating that he donated blood.
c) A badge that shows he plays in a band.
2. Why doesn’t Michelle want to donate blood?
a) Because she has a medical condition that prevents it.
b) Because she doesn’t meet the weight requirements.
c) Because she is afraid of giving blood.
Answers at bottom.
What Else Does It Mean?
needle
The word “needle,” in this podcast, means a thin, long tube of metal with a pointed end, used to enter one’s blood vessel through the skin to deliver medicine or remove blood: “Does the nurse usually put the needle in your right arm or your left arm?” A “needle” is also a thin, long, solid piece of metal with a pointed end and a small hole in the other end, used to push and pull thread through a piece of fabric: “Hold the needle like this to sew on the button.” Finally, when talking about a dial, a “needle” is the long, thin piece of metal or plastic that points to a number or measurement: “The needle on the speedometer is stuck at 30 miles per hour, even when the car is stopped.”
faint
In this podcast, the verb “to faint” means to lose consciousness, or to fall down and seem to be asleep, unaware of what is happening around oneself, usually when one is very frightened or very hungry: “Tania fainted when she heard the bad news.” When used as an adjective, “faint” means barely or just a little bit: “These cookies have a faint taste of cinnamon.” Or, “Even the faintest noise distracts Jenna when she is trying to study.” Finally, the phrase “to not have the faintest idea” means to not have any idea about something or to not know something at all: “We didn’t have the faintest idea what the director was talking about, but we all nodded and smiled anyway.”
Culture Note
Requirements for Donating Blood
To “maintain” (keep up) the quality of the blood in “blood banks” (collections of different types of blood that will be used when needed), organizations that have “blood drives” (efforts to collect a lot of blood) have “strict” (without exceptions) requirements that blood “donors” (people who donate blood) must meet.
The basic requirements are that donors must be healthy, at least 17 years old, and have an “adequate” (sufficient; enough) body weight. But that is just the beginning.
Donors need to “disclose” (share information about) a full list of any medications they are taking, as well as whether they have recently had “immunizations” (injections designed to protect people against disease). They also have to provide basic information about their general health, such as whether they are “ill” (sick) or have medical conditions that are “transmitted” (passed from one person to another) via the blood. In addition, women cannot donate blood if they are pregnant.
Donors also have to respond to a “questionnaire” (a form requesting information) or interview about their “lifestyle” (how one lives and the choices one makes). People who have had a “tattoo” (a permanent ink drawing on one’s skin) or a “non-sterile” (not clean) “piercing” (the placement of a hole in one’s body, as for earrings) in the past year, people who have had many sexual partners, and people who have taken “non-prescription” (not recommended by a doctor) drugs “intravenously” (via injections) may not donate blood.
There are also some restrictions based on foreign travel. For example, blood banks will not accept blood donations from people who have traveled to a country with malaria (a disease of the blood that causes fevers) in the past 12 months.
Comprehension Answers
1 - a
2 - c