= 1598
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 293.
This is English as a Second Language Podcast’s English Café episode 293. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful – and I do mean beautiful – Los Angeles, California.
Visit our website at eslpod.com. Why? Well, because you can download a Learning Guide for this episode, an 8- to 10-page guide that will help you improve your English – and give you long, healthy hair, like mine!
On this Café, we’re going to continue our series on famous Americans, talking about a man named Al Capone. We’re also going to talk about the most famous military college in the United States, the U.S. Military Academy at West Point. And as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on famous Americans. Today we’re going to talk about Al Capone, whose full name was Alphonse Gabriel Capone; he was called “Al” for short. “Al” (Al) can be used for a name like Alphonse or Alphonso; it could be used for a name like Albert, which is probably a little more common, at least historically in the U.S. In any case, Al Capone was born in Brooklyn, which is part of New York City in the State of New York, in 1899 to a family of Italian immigrants. There were millions of Italians who came as immigrants to the United States in the late 19th and early 20th centuries. Many of them began their life here living in the cities in the eastern coast of the U.S., including especially the City of New York, but also Boston, Philadelphia, and other places.
Capone was born in New York to a family of Italian immigrants. He dropped out of school, that is, he left school when he was 14 years old. “To drop out” means to stop attending or stop going to school. He was only 14, although that was not unusual at that time; the average American did not graduate from high school. In fact, it wasn’t until after World War II that the majority of Americans were graduating from high school. In any case, Capone worked several odd jobs. An “odd (odd) job” refers to one of several jobs that are not professional, usually not requiring a lot of skill, a lot of knowledge or talent. In addition, they are not related. I may work as, as I did when I was in college, one day I would be working in an office and the next day I might be working in a factory. I worked for what’s called a “temporary agency,” so you get a different job almost every day. Well, that wasn’t the case for Al Capone, he didn’t work for a temporary agency, but he did have many different kinds of jobs. He worked in a candy store; he worked at a bowling alley, a place where you bowl – you throw a ball down a long section of wood in order to knock down what are called “pins.” That’s one of the jobs Al had. But his true profession, the one that he found I guess you could say the most success at was being a gangster.
A “gang” (gang) is a group of people, usually young men, who are involved in illegal, unlawful activities. Usually they are trying to make money; they are often “intimidating,” or scaring other people into giving them money. Someone who is a member of a gang is called a “gangster.” More recently, at least in the 80s and 90s, members of modern gangs, if you will, here in Los Angeles or New York City were called “gang bangers,” but the older term is “gangster.”
A gangster named Johnny Torrio became Al Capone’s mentor. A “mentor” (mentor) is when one person with lots of experience in something helps someone who is younger than them, teaches them things. It’s many times an informal relationship. They are helping the less experienced person learn things and develop their career. We usually talk about mentors when we’re talking about business or medicine or teaching, but in this case, the mentor was a gangster.
Capone started as a member of several small, relatively unimportant gangs, but soon he became part of a gang known as the Five Points Gang. At that time, he worked in a dance hall and what we now call a bar, an old word for bar is “saloon” (saloon). In that job, Capone got into a lot of fights and ended up receiving many cuts to his body, especially his face. When you cut your skin, and it’s a deep, serious cut, it will often leave a mark on your skin. We call that mark a “scar” (scar). Well, Al Capone had a lot of scars on his face, and some people in fact called him Scarface.
In 1923, Capone moved to the City of Chicago, which is in the central part of the United States. Chicago is sometimes called the “Second City,” the second city in terms of importance after New York City. Capone had a wife and a son by this time, by 1923. His gangster mentor had asked him to come to Chicago to help him with some family problems. Shortly after he arrived, the gang members who were creating these problems were murdered – were killed, and many people suspected or thought that the guilty person, the person who committed the crimes, was Al Capone, but Capone was not arrested. Capone also got involved in Chicago’s politics, which were at that time – some people say still – very corrupt. “Corrupt” (corrupt) means that politicians do things for people who pay them illegally and secretly. Many people believe that the politics of Chicago was corrupt throughout the 20th century; some people might say it’s still corrupt, but it is famous in American history for being a city of political corruption.
This was the time, 1923, of Prohibition, the period of time where it was illegal to make, sell, or buy alcohol in the United States. We’ve talked about the prohibition a couple of different times – on English Café 66, on English Café 134, I think on English Café 153 – so I’m not going to talk about that here. But Prohibition was an excellent opportunity for gangsters like Al Capone to make a lot of money transporting and selling alcohol illegally. In the mid-1920s, Al Capone’s gang-related businesses were bringing in, or were gaining or getting revenue of about 100 million dollars per year. “Revenue” is just another way of saying the money that your company takes in, what it sells – the money it gets for what it sells, whether that’s a thing, a product, or an activity – a service. Capone was making 100 million dollars a year on his activities. He used this “wealth,” this large amount of money, to have more power in Chicago. He would bribe politicians. “Bribing” (bribing) comes from the verb “to bribe.” It means to give politicians or someone in power money so that they will do what you want them to do, and remember Chicago was considered a very corrupt city politically.
Other gangs became jealous of the money that Capone was making and the power that he was attaining – he was getting – and they started to attack Al Capone’s gang. They wanted some of that money and power for themselves. The gangs became more and more violent; more and more killings – murders – were taking place. The violence “culminated,” that is it reached its maximum or highest point on February 14th, 1929 in what became known as the Saint Valentine’s Day Massacre. Saint Valentine’s Day, February 14th, is normally a day for lovers; it is a day for romance between a boy and a girl, a husband and a wife, and so forth. Well, Saint Valentine’s Day in 1929 had a massacre. A “massacre” (massacre) is when many people are killed at the same time. On that day, seven people were killed in a garage, in a place where you normally park cars, but no one was ever taken to court for it, no one was ever found guilty of the murders. But many people thought Al Capone was responsible for the Saint Valentine’s Day Massacre. The word “massacre” is not normally used for seven or eight people; it is here. A massacre is nowadays usually tens or hundreds of people. But it was of course, a terrible crime, and people thought Al Capone was responsible.
Throughout this time, the government tried to catch Capone – they tried to convict Capone, that is, find him guilty and send him to prison, especially for violating the laws of Prohibition, but they were not able to lock him up. “To lock (someone) up” is, in this case, to arrest him, that is, to put them in jail. “To lock up” can just mean to close a door, for example, so no one can get into it. But if you are talking about a person, “I’m going to lock him up,” or “he was locked up,” usually that means that he is in prison – in jail.
Capone was finally locked up in 1931, and it wasn’t for crimes of murder or violating Prohibition; it was for tax evasion. “To evade” (evade) means to avoid, to not do something you’re supposed to do. “Tax evasion” is when you don’t pay the taxes that you are supposed to to the government. Capone was released from prison in 1939, but by then he had lost most of his power. He was very sick at the end of his life and he died in 1947.
Capone is the most famous and most notorious gangster in American history. “Notorious” means that you are famous, but famous in a bad way, famous for something you did wrong. The word is now used often to mean the same as famous, not in a bad way, but the original meaning was in fact that you were famous for doing something wrong. Capone became so powerful and so rich – so wealthy – that he was actually admired by many people, even though he was breaking the law, even though he was killing people. Sometimes Capone would give money to people who were poor, and this was reported in the news, in the newspaper and on radio, and that caused some people to think that Capone was perhaps a good guy rather than a bad guy. Even today many people are fascinated by Al Capone, and many movies and books have been dedicated to or have been about Capone.
Now, after talking about gangsters and crime, let’s turn to our next topic, which is the U.S. Military Academy at West Point, what is known more commonly simply as West Point.
The United States has five academies – they’re colleges really, universities – which are for people who are in the armed forces, in the Army, the Navy, the Marines, and so forth. West Point is the oldest military academy. It was created by President Thomas Jefferson, our third president, in the year 1802. West Point is the military academy for the largest part of the American military historically, the U.S. Army.
If you want to study at West Point you have to apply, you have to submit an application, but it isn’t just any kind of application. You actually have to be nominated by someone in our U.S. Congress, a House of Representatives in our Senate, or by the President himself. You don’t have to know these people, but you do have to give your information to their offices, and they will select people that they will nominate to the Academy. A good friend of mine’s brother was nominated to another military academy, the United States Air Force Academy in Colorado. So, Congressmen and Congresswomen nominate men and women between ages of 17 and 23 for the military academies, in this case, for West Point. You have to pass a physical examination – you have to be able to participate as a member of the armed forces, you cannot be married, and you cannot have children if you are accepted. Of course after you can get married and have children eventually, but not when you are first entering into the academy.
The students who are admitted to West Point are training to be, or studying to be military officers. When they are at the academy they are known as “cadets” (cadets). A “cadet” is an officer-in-training, someone who is preparing to be an officer. About 1,300 cadets enter West Point each year, and about 1,000 of them finish four years later with a Bachelor of Science degree.
Cadets to our military academies, like West Point, do not have to pay for their schooling; they don’t have to pay tuition. The government pays all of the expenses. However, the person in the military academy has to serve in the military a certain number of years after, so it isn’t exactly free. You get a free education, but you have to remain a member of the military for a certain amount of time. All the cadets live on campus, that is, where the school is located for all four years. They are required to participate in athletics. Football, for example, is very popular among the men.
Ethics and morals are considered very important at West Point, and the cadets have to agree not to lie, cheat, or steal, and not tolerate those who do, that is, not allow their friends and others to do so. West Point has very high standards traditionally – high expectations for its students. The graduates tend to be very successful, especially in the U.S. military, which is of course the reason why they are going there.
There have been many very famous Americans who have gone to West Point, who have graduated from West Point. Former U.S. Presidents Ulysses S. Grant and Dwight D. Eisenhower were graduates of West Point. Many governors, Congressional representatives, and of course military generals, the leaders in the Army, almost all of them are graduates of West Point.
It used to be that West Point was only for men, but in 1976 West Point admitted its first female cadets. Today about 15 percent of the cadets are women, so it is still a mostly male institution.
West Point is one of those things that you will hear mentioned in the news or read about in a story, and now you have a little background on it. It is the most famous U.S. military college for the U.S. Army.
Now let’s answer some of your questions.
Our first question comes from Marina (Marina) in Bulgaria. Marina wants to know the meaning and the differences of the words “crash,” “shatter,” and “smash.”
“Crash” (crash), as a verb, means to hit something and to make it break loudly, or to cause things to hit each other and to break loudly. It’s often used when talking about a car hitting another car or hitting something else and making a loud sound. “The two cars crashed into each other yesterday.” In fact, there was a movie called Crash about Los Angeles that involved a car crash. “To crash” can mean simply to make a loud noise even if something doesn’t break. For example, we use this verb in talking about the waves in the ocean. When the water crashes against the rocks it makes a loud sound, and that is another use of the verb.
“To shatter” (shatter) means to break into many pieces, many smaller pieces, while making a loud sound. We usually use this verb in talking about glass, or something that when it breaks, breaks into many small pieces. If you have a mirror on the wall, and it falls to the ground it will shatter; it will break up into small pieces. We sometimes use this verb metaphorically, or somewhat poetically even. You could say, for example, “My girlfriend left me, and it shattered my heart.” My heart was broken up into a thousand little pieces. Then of course, you meet another girl – eh, you don’t have to worry. Right?
“Smash” (smash) is to destroy something or break something; it’s usually with a loud noise but not always. It could mean that, for example, one army defeated another army; they completely defeated them.
When it comes to breaking things, then, “crash,” “shatter,” and “smash” are all very useful words that have some specific meanings typically. “Crash,” more than anything, is a noise word; it…it emphasizes the noise that is made. “Shatter” is all about breaking up into small pieces. “Smash” is all about the destruction, destroying something completely.
There’s another meaning for the word “crash” in informal English, and that would be to sleep. “I was so tired last night, I crashed at about 9:30.” That means I fell asleep about 9:30. Or you might say, “I’m visiting my cousin in Honolulu. He has a couch where I can crash,” a place where I can sleep. I wish I had a cousin in Honolulu, but I don’t! I have one in Minnesota, so there you go.
Idi (Idi), now living in Egypt, wants to know the difference between two expressions: “How about you?” and “What about you?” “How about” or “What about you?” can both be used to ask your thoughts or feelings about something. For example, “How about a cup of coffee?” What you’re saying to the person is do you want to get a cup of coffee. Do you feel like getting a cup of coffee? You could also say, “What about a couple of coffee?” It is a little less common in that context, but you could still say that and mean the same thing. “How about you?” is a little more common than “What about you?” when you’re asking about how someone feels or what someone thinks about a certain topic.
Sometimes these expressions can be used to ask about you, what are your feelings about you – about yourself, we should say. “What about you?” What are you thinking?
Finally, Karimov (Karimov) in Uzbekistan wants to know the meaning of the expression “bite me.” “To bite” (bite) something is to put it in your mouth and use your teeth to go into the object. However, the general meaning of this very informal slang, rude, and someone vulgar expression is I don’t accept what you say. It’s a way of responding to someone who has insulted you. Someone says something bad about you and you want to tell them to go away, you want to insult them back. For example: “Your team lost the baseball game. You guys are terrible,” and you could respond, “Bite me!” Now, it’s a very rude thing to say. Teenagers and young adults might say this. You won’t hear people my age say it – you might, but it’s not very common. It’s become more common. As I say, it’s very rude, and you would probably be best never to use it. It can be used sometimes jokingly among friends. But again, I would caution you about that; I would say you probably are best not using the expression. You may read it or hear it in a movie, and as I said, generally speaking it means go away or shut up or get out of here, something like that.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Develo
Glossary
odd job – one of several jobs that are unskilled and not professional, each usually unrelated to the others that one has
* When Jae was in high school, he did odd jobs around the neighborhood to earn money for college.
gang – a group of people who are involved in illegal activities, usually to make money and/or to scare other people
* Too many of this community’s young men are becoming members of gangs, getting into trouble, and risking their lives.
mentor – a person who has a lot of experience in a particular profession and helps a younger, less experienced person learn more about the profession and develop his or her career
* When I was in college, I had a mentor who was already a successful businesswoman. She gave me career advice and helped me get my first job.
scar – a thin, white or pink line left on one’s skin after one has healed from a cut
* After the accident, Kanisa was self-conscious about the scars on her arms and legs.
to bribe – to pay someone to do something or not do something that would benefit one
* Have you ever bribed a hostess at a restaurant to get a better table?
to culminate – to reach a maximum point; to reach the most important point
* The movie culminated with three car chases and four explosions!
massacre – the violent and deliberate killing of many people at the same time
* The soldiers massacred the people in the village, killing everyone including the children.
to lock (someone) up – to place a person in prison or jail
* The citizens wanted the police to find the killer quickly and to lock him up for good.
tax evasion – the act of not paying taxes to the government; the crime of not paying taxes owed to the government
* Winston won $1 million on a game show, didn’t pay his taxes, and is now in jail for tax evasion.
notorious – famous for doing something wrong; famous in a bad way
* Oh no, I didn’t know that Dana was standing behind me when I told you my secret. She’s notorious for gossiping with anyone who’ll listen!
nominated – for one’s name to be suggested for a particular position or opportunity
* Five actresses have been nominated for the acting award, but we won’t know the winner until next month.
cadet – a student in a military school; a person training to become a member of the military or a police force
* Leslie and Toshi’s son is an air force cadet.
to crash – to hit something and make it break noisily; to cause things to hit each other and break noisily, often used with cars or other vehicles
* The boy lost control of his bicycle and crashed into the tree.
to shatter – to break into many pieces while making a loud noise; to ruin something by breaking it into many pieces, often used with glass and other similar materials
* When Bernice heard the bad news, she dropped her glass and it shattered on the floor.
to smash – to break something completely, usually while making a loud noise; to crush something; to make something flat
* When Len sat down, he accidentally sat on Mai’s hat and smashed it.
how about you? / what about you? – what are your thoughts or feelings about something or someone?; what are your opinions about something or someone?
* - I prefer watching comedies. How about you? / What about you?
* - I like comedies, but I really like horror movies.
bite me – an rude, informal phrase said when one is angry or frustrated, most often used in response to an insult, usually meaning “I don’t accept what you say” or “Go away!”
* - You look stupid wearing Mom’s dress and high-heeled shoes.
* - Bite me.
What Insiders Know
Famous College Dropouts: Bill Gates and Steve Jobs
Many people see graduating college as a way to improve their “job prospects” (the possibility of getting a job and the quality of job offers) or as a first step to a successful career. For many people, this is true, but for a few “notable” (worthy of attention) “dropouts” (people who quit school), graduating college did not stand in their way of success. Two of the most important people in computers science and technology are college dropouts: Bill Gates and Steve Jobs.
Bill Gates started as a student at Harvard University in 1973. He remained a student for two years before he dropped out to “found” (start) Microsoft with his friend Paul Allen. In 2007, Harvard University wanted to “recognize” (acknowledge) their most famous dropout and awarded him an “honorary doctorate,” the highest-level academic degree even though he did not “satisfied” (complete) the courses needed and other requirements. For over a “decade” (period of 10 years), Bill Gates was named the “richest” (with the most money) person in the world.
Steve Jobs attended Reed College in Portland, Oregon for only one “semester” (term, usually three or four months long) before he dropped out. Even after dropping out, however, he continued to “audit” courses at Reed. (To “audit” a course is to take a course informally and not for a grade or for university credit.) In fact, in 2005, Steve Jobs told a group of graduating students at Stanford University that it was a course in “calligraphy” (decorative handwriting) that gave him the ideas for the fonts used on Macintosh computers. Four years later, Steve Jobs and Stephen Wozniak “co-founded” (started together) the company Apple.