= 1595
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 290.
This is English as a Second Language Podcast’s English Café episode 290. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that will give you some additional help in improving your English.
On this Café, we’re going to talk about a criminal named Charles Manson and his involvement in the Tate Murders, one of the more famous murder cases of the 20th century right here in Los Angeles. We’re also going to talk about air marshals and what they do on airplane flights. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion about a man named Charles Manson. Charles Manson was born in Cincinnati, Ohio in 1934. Ohio is in the eastern part of the United States, not on the ocean, next to the State of Pennsylvania and the State of Indiana. Manson had a very troubled childhood. When we talk about someone who is “troubled” we mean that he or she has a lot of problems – a lot of trouble. Charles Manson had a troubled childhood, a very difficult childhood. His mother was only 16 years old when he was born. She was an alcoholic who once sold her son to a waitress for some beer. He never knew his father.
He began committing crimes at a very young age. He stole things from many stores and, as he got older, began committing “armed robbery.” “To be armed” means that you have a weapon, often a gun nowadays. “Robbery” is the same as stealing from someone. So, he was stealing things by using guns. He also committed auto, or car theft. He was kept in several juvenile centers, special facilities the government has for young people who get in trouble. Eventually he went to prison – a regular prison, where he was dangerous and violent toward the other prisoners. By 1967, he was 32 years old and had spent more than half of his life in prison or other institutions. He asked for permission to stay in prison, rather unusual, saying it was the only home he knew, but he was released, or made free anyway.
After he was freed from prison he moved to San Francisco, California, where a couple of people, mostly women, began following him. In this context, “to follow” someone means to believe the things that they say, even if they are strange or crazy. The people following Charles Manson became known as the Manson Family. This is the late 1960s-early 1970s; there is certainly an alternative – a different sort of lifestyle that is becoming popular in places like San Francisco, Los Angeles, New York. You have the so-called “hippy” movement during this period, people who wanted to break free from traditional society and traditional morals and values. Manson became a guru of some of the hippies in the area of San Francisco, especially in Berkeley, California. A “guru” (guru) here means someone who is considered a wise person, a wise leader. Manson had some very strange beliefs, very different beliefs about the world. Part of his beliefs came from the Scientology movement, which we talked about back in Café number 76.
Manson traveled around the country and even became involved briefly with Dennis Wilson, the drummer for the music group The Beach Boys. In fact, Manson ended up moving in with Dennis Wilson, along with more than a dozen of his women followers, and eventually he recorded some songs. Everyone in Los Angeles thinks they’re either a movie star or a singing artist, and so it’s not too surprising that Charles Manson also recorded music.
Charles Manson became increasingly obsessed with the music of the Beatles, and especially with ideas about racism. He believed that there would be violent conflict – violent war between blacks and whites in the United States, and between those who were racist and non-racist, and that many people would die as a result. Manson called this future violence Helter Skelter, which was the name of a song by the Beatles.
In 1969, Manson and his followers decided that they would start Helter Skelter – they would start this violence. They entered a home, here in Los Angeles, of a famous actress, Sharon Tate, who at the time was eight and a half months pregnant with a child. Sharon Tate was an actress in movies and television, as well as a model. She was also married to a man named Roman Polanski, a famous – now famous director, he was also well known back in the late 1960s. Polanski himself would have his own problems, which we’ll talk about perhaps on another Café. So, the Manson Family entered the home of Sharon Tate and Roman Polanski. Polanski himself was not home, and they murdered her along with four other people in the house. The crimes committed that night became known as the Tate Murders.
Manson’s followers committed other murders as well, the very next day – actually the next night. These were known as the LaBianca Murders. At first the police investigating the crime didn’t see the connection between the two murders, they didn’t realize they were related. In fact, it took several months before the police solved the crime and made arrests later that year. The murders, I should say, took place in early August of 1969.
We don’t have time to go into all of the strange things that happened during this famous trial back in 1970. At one point, Manson and his followers had put a black X on their foreheads. Manson had actually tried to attack the judge in the courtroom. The judge later began carrying a gun for protection. The Manson followers who were not arrested began to do violence against those people who were going to give evidence against Manson in the trial. One of the lawyers who was defending the women in the trial was, in fact, killed during the trial. Although there was never any charges brought against the Manson Family, many people suspect that he was killed because he didn’t agree with Charles Manson about how they should conduct, or carry out the trial.
Manson and his followers were all found guilty of the murders. Manson himself was found guilty of conspiracy. “Conspiracy” (conspiracy) is when you have a secret plan to do something illegal and you are working someone else. Charles Manson planned and organized the murders, and therefore he is as guilty as the people who actually killed the victims, the people who died. Manson and his followers were given a death sentence, meaning the court decided that they should be killed by the government for their crimes. However, California’s Supreme Court, the highest legal body in the state, temporarily got rid of the death penalty, and so Manson and his followers’ sentence – their punishment was changed to life in prison.
The prosecutor of the Manson case, the legal officer from the government who is responsible for presenting the evidence against, in this case, Charles Manson and his followers, wrote a book called Helter Skelter; it was later made into a movie, which I remember watching as a child, a few years later. That prosecutor, whose name is Vincent Bugliosi (Bugliosi), originally from Minnesota, was later to write another book about a famous political cultural crime, the assassination of John F. Kennedy back in 1963. That book that Bugliosi wrote is more than 2,500 pages long, and it is a complete review of all of the theories and ideas about who killed John F. Kennedy. He concludes that Kennedy was killed by Lee Harvey Oswald acting alone, just as the government determined in the 1960s. But that’s another story, another unfortunate story.
The Charles Manson case was an important part of early 1970s American culture in a way. During the late 1960s and 1970s there was what some people called “counterculture,” that is a culture that went against the traditional culture. Part of this lead to the creation of what we called then, and probably would still call now, “cults.” A “cult” (cult), in this context, is a group of people who have certain beliefs, often they are very different than the traditional religious beliefs of their society. These cults often try to control their members through various psychological and sometimes physical techniques. These cults were, for whatever reason, very popular here in California in the 1970s. Manson’s cult was just one of those.
You might guess that after these terrible murders the Manson cult sort of went away and disappeared, but in fact it did not. It continued to have influence on people, some small group of followers, after Manson and his other followers were convicted of murder. Manson’s cult was very closely connected with music, and some rock groups actually recorded some of Manson’s music. The rock singer Marilyn Manson took his name – his stage name, it’s not his real name of course – he took the first name from Marilyn Monroe, the famous actress, and his last name from Charles Manson. Why? I’m not really sure.
In any case, there were continuing influences of the Manson cult throughout the 1970s and 80s. In fact, one of Charles Manson’s followers was a woman who was called “Squeaky” Fromme. “Squeaky” Fromme tried to assassinate the President of the United States a few years later, that was Gerald Ford. She did not succeed, she was caught, and she was put in prison. I believe she was just released from prison a year or so ago. That was back in the mid-1970s when she attempted to assassinate the president.
Now let’s turn briefly to our next topic, which is air marshals. An “air marshal”, sometimes called a “sky marshal,” is someone who flies in airplane as a passenger, just like you and I might, but they are undercover police agents. “Undercover” (one word) means in disguise; you don’t know they’re police officers, they look just like normal people. They don’t have a special set of clothing on, a uniform for example. The air marshal program is part of the Transportation Security Administration. This was an organization – a federal or national government organization that was established, or set up after 9/11. The program actually began back in 1969, but it has grown considerably in the 10 years.
The air marshals, then, are sort of like federal police officers. They fly on planes undercover – in disguise – wearing regular clothing. They have guns, but you can’t see them. They’re there to protect the passengers in case there is a terrorist threat – a terrorist attack. The idea is that if a terrorist is on the plane, and wants to blow up the plane or attack the pilots, the air marshals are there to disarm the terrorists. “To disarm” is to take someone’s weapon away. They usually fly in “pairs,” meaning there are at least two of them if they’re on your particular airplane. Now, not every airplane and every air flight has an air marshal. The Transportation Security Administration decides which flights – which airplanes will get air marshals.
In order to become an air marshal, you have to go through many different tests, as well as a background investigation. A “background investigation” is when officials make sure that you haven’t committed crimes, that you are trustworthy. If you pass these tests, then you participate in a 15-week training program, where you learn about the things you need to do. You also have to have very good skills in shooting a gun, that you can shoot very accurately. We don’t want air marshals shooting other passengers!
Most people want to be protected when they fly, but the air marshal program is still somewhat controversial. Nobody knows which flights the air marshals are on, and of course no one knows which flights the terrorists might be on. We don’t know, in fact, how many air marshals there are; many people think it’s somewhere between 1,000 and 4,000. But clearly there aren’t, as I said before, enough air marshals to be on every flight and every plane.
The airlines, the companies that fly the airplanes, are not always happy to have an air marshal on their flight. First, the air marshals always fly in the front of the plane, which means they fly in the first-class section. That’s so they can be close to the pilot. But first-class tickets are very expensive, and the airlines cannot charge the government any money to give them those tickets. Remember, they usually fly in groups of two, at least. This sometimes causes the airline to have to bump one of their first-class passengers. In talking about airplanes, when someone says, “I was bumped (bumped) from my flight,” they mean the airline told them they had sold too many tickets and that they could not take that airplane flight. In the case of the first-class passengers, they will get bumped to the back of the plane, the more inexpensive, cheaper seats, what we call “coach.” This, of course, doesn’t make the first-class passengers very happy. However, the airline cannot tell the first-class passengers who are bumped why they are bumped; they cannot indicate that there are air marshals on the plane. But overall, most Americans would probably support, and do support the air marshal program as a way of protecting those who are flying on airplanes here in the United States.
Now let’s answer some of your questions.
Our first question comes from one of our many listeners in Iran, Bahador (Bahador). The question has to do with the difference between the verb “to reach” and “to arrive.” These verbs can have similar meanings. Let’s start with the second one: “to arrive” (arrive).
“To arrive” means to come to a certain place: “We arrived in Paris yesterday afternoon.” Notice we use the preposition “in.” “I arrived in Minneapolis at five o’clock.” You could also say “I arrived at” if you’re talking about a specific place: “I arrived at the school at five o’clock.” Or simply, “We arrived at five o’clock.” You can use “at,” in fact you must use “at” if it’s a time expression. You also use “at” if you are talking about a specific building or a specific location. If you’re talking about a city, like Paris or Topeka, then you use “in.” The same would be true for a state or a country. That’s one meaning of the verb “to arrive.”
“To arrive” can also sometimes mean to happen, when you are waiting for something. This is especially true for some event or some specific day. For example: “The last day of school finally arrived.” We mean we’ve been waiting for the last day of school and now it is here. Of course, the day doesn’t travel, but we use that idea of traveling in talking about time. You could also say, “My birthday finally arrived.” That is, I’ve been waiting for my birthday to celebrate, of course, my birthday, which is September 24th – you all know that, put it on your calendar – and so you could say that day arrived.
Now, the verb “to reach” (reach) means to get to a place or to achieve a goal usually after a long wait or after a long time, in the case of a place, a long trip. For example: “We finally reached Paris after 16 hours of traveling.” You could say, “We arrived in Paris after 16 hours of traveling,” but when you use the verb “reach” you are emphasizing that it was a long wait or a long trip. We can also use this in talking not about physical locations but about a goal. “Joel thought he’d never reach his goal of losing 20 pounds.” It took a long time. You could also say, for example, “My sister’s letter finally reached me.” It finally got to me after a long time. You could also say, “My sister’s letter finally arrived,” but once again “reach” emphasizes the long trip or the long time, the long wait.
“To reach” has a couple of other meanings, not related to the same idea as “to arrive.” One of them is simply to take your arm or another part of your body in order to touch something far away or lift something up. For example: “I had to stand on my chair so I could reach the top of the bookshelf.” “To reach” here means to be able to take my hand and touch it or take something off of it. Or you could say, “I reached as far as I could to catch the ball.” I was running, and then I put my arm out to the side of my body and tried to catch the ball. Baseball, of course, we’re talking about baseball. Everybody knows the great American sport – the great American pastime, we call it. So, that’s another meaning of the verb “to reach.”
“To reach” can also mean to be in communication with, especially someone who is difficult to communicate with. This verb is used in this way when talking about trying to call someone on a telephone: “I finally reached my sister last night after trying her telephone number for three hours.” I reached her; I was able to communicate, to speak with her.
Finally, “reach” can also be used to talk about how far the borders or the edges of a piece of land or a body of water go. It can even be used to talk about how much power or influence you have; that’s a slightly less common use of that verb.
Andre (Andre) in Mexico wants to know the meaning of a couple of very common phrasal verbs – two words verbs – with the verb “to go.” He asked about “to go off,” but I’ll talk about a couple of different verbs phrases, phrasal verbs we call them, using the verb “to go.”
The first is “to go off” (off). This usually means to make a sudden noise if it’s for, for example, a clock or an alarm: “My clock will go off at six o’clock in the morning tomorrow.” That’s what time it will start ringing; it will start making a noise. “To go off” if you’re talking about a bomb means to explode, to damage the things around it.
“To go on” can mean to keep going, to continue. “Go on with your story” means continue telling us your story, continue talking. “To go on” can also mean to begin functioning or to begin working. “The lights go on at six o’clock in the morning with an automatic timer.” The lights begin working at that time.
And, just to make your life difficult, English also has the expressions “come on” and “come off” in addition to “go on” and “go off.” “To come on” can also mean the same as “to go on,” meaning they start working. “The lights come on at six o’clock.” That’s what time they start functioning – they start working. “Come on” can also mean to begin feeling sick if you have a specific type of sickness or illness in the sentence. “I have a cold coming on.” It’s beginning to affect me. “I have a headache coming on.” It is starting to hurt. “Come on,” as an expression, can also mean hurry up. If you’re leaving somewhere and you say to your husband or wife, “Come on, we need to leave now,” that means hurry up, start exiting, start coming with me. “Come on” can also be used when you are telling someone that they are being unreasonable or they are saying something that isn’t true and that they know it’s not true. A teenager says to his father, “Oh, come on Dad, let me use the car.” “To come on to someone” means to flirt with them, to do something that would indicate that you wanted to have a romantic or sexual relationship or activity with them. Finally, “to come off” can mean that something breaks off; something separates from where it should be. “The button came off on my shirt.” The button was on the shirt and then it, for some reason, came off; it was removed. Usually, that’s something that happens by accident, that’s when we use that expression. “To come off” can also mean to complete or finish something, usually something negative. It’s often used in sports to talk about a team that has been losing game after game: “The Dodgers are coming off a five game loss.” It can also be positive, now that I think of it. You could say, “The Dodgers are coming off a five game win,” though that probably isn’t true.
Finally, Ali (Ali) from Syria wants to know the meaning of the expression “she is out of my league” (league). “To be out of (someone’s) league,” when we’re talking about, say, a woman, means that that person is so attractive, so beautiful, so desirable, successful that you will not possibly have a chance of going on a date with her or being involved in a romantic relationship with her. “She’s out of your league. She’s too beautiful, don’t even bother trying to talk to her.” That’s the idea. Of course, if you’re a single man this is not a very good attitude to have; you should never think that. All the other guys who see her will be thinking that, and that gives you the opportunity to try your luck – to try to ask her out on a date. Of course, you may have to do that 100 times 100 different women, but eventually you may have some success. It helps have lot money, too, just so you know!
We’ve reached the end of this episode. If you have a question or comment email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, won’t you, on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
troubled – feeling as though one has a lot of problems; feeling a lot of distress and anxiety
* David has had a troubled look on his face all week. Do you think he’s having personal problems?
armed robbery – stealing things by threatening people with guns
* The judge gave the bank robbers 15 years in prison for armed robbery.
following – a group of people who admire and believe in what a specific person or leader says; a gathering of people who believes strongly in a specific way of thinking
* Jemina has written several books about how people should simplify their lives to be happier, and she has a very large following.
conspiracy – a secret plan between two or more people to do something illegal or against the rules
* The police arrested three employees of this company for a conspiracy to steal millions of dollars.
death sentence – the punishment of being killed for crimes one has committed
* Instead of the death sentence, the judge gave the criminal a life sentence, so she will spend the rest of her life in prison.
cult – a group of people who share certain unusual beliefs and act in certain ways
* When Abby joined a cult, she gave the cult leaders all of her money and went to live with them in the mountains.
air marshal – a law enforcement officer who flies undercover (without letting others know of his job) on passenger airplanes to protect the other passengers
* When the man on the plane tried to light a bomb, the air marshals stopped him before he could do any damage.
undercover – in disguise; without letting others know of one’s identity, role, or job
* As a spy, Jason travels the world undercover and never tells anyone of his real identity.
to disarm – to take a weapon away from someone or some group
* The police officer disarmed the thief and arrested him for trying to steal the woman’s purse.
in pairs – in groups of two; with a set of two things or people together
* Okay, children, we’re going to the library. Walk in pairs and hold hands.
background investigation – for officials to take fingerprints and other information about a person to try to find out whether that person has committed crimes or done something else that is not acceptable
* The background investigation found that she had spent time in jail for murder.
to bump – to not allow a passenger who has paid for a seat on an airplane to fly, usually because the airline had sold too many tickets for the number of seats available
* I was very angry when I was bumped from my flight and I could not reach Washington D.C. to attend a very important meeting.
to reach – to get to a place or goal, usually after a long wait or a long trip; to stretch the arm or another part of the body, usually in order to touch or lift something
* When we reach the next town, we’ll need to find a gas station to get more gas.
to arrive – to get to a place; to occur, often when someone has been waiting
* When is your grandchildren’s plane supposed to arrive today?
to go off – to make a sudden noise, usually to alert someone to the time or some danger; to explode
* My alarm clock didn’t go off this morning and I was late for work.
to be out of (one’s) league – a phrase used to refer to someone/something that is better in some way than one is and one is not deserving to be with this person or to participate in the same things as this person
* Jessica is out of my league. She’s beautiful, smart, and charming. She’ll never agree to go out on a date with me.
What Insiders Know
Criminal Justice
Would you like to work as an air marshal or a police officer? If you do, you could be working in important parts of the criminal justice system.
The term “criminal justice” refers to all parts of the system that “ensures” (makes sure) laws are followed, and when laws are broken, that people are punished. In the United States, the criminal justice system has three parts.
The first part is called “law enforcement” or the police. There are many different kinds of police officers, some who work for a city, a state, or for the national government. However, there is one thing that all law enforcement officers do. They “enforce” (make sure people follow) laws.
The second part of the criminal justice system is called “adjudication” or the law courts. “To adjudicate” means to make a decision about some problem or “dispute” (disagreement between two or more people or groups). The law courts require the “judge” (most important law official) to adjudicate, or a “jury” to make a legal decision. A “jury” is a group of citizens who listen to the “testimony” (official statements) in a court case and makes a decision about it.
The third part of the criminal justice system is “corrections,” which refers to jails and prisons, and the “probation” and “parole” systems. “Probation” is when someone who is guilty of a crime is not required to go to prison, as long as he or she follows rules and laws for a period of time. “Parole” is when a prisoner is allowed to leave prison early, as long as he or she commits no more crimes within a specified period of time.