= 1587
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 282.
This is English as a Second Language Podcast’s English Café episode 282. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that will give you some additional help in improving your English – and, make your children smarter! You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about the 60s and the 70s, in a way. We’re going to talk about a movie called The Graduate, which was a popular movie in the late 1960s. We’re also going to talk about a woman who became famous in the 1970s by the name of Patty Hearst, someone that most Americans of my generation and older certainly remember. And, as always, we’ll answer a few of your questions. Let’s get started.
The Graduate is a book and a movie. The book was written by a man named Charles Webb and was published in the year I was born, 1963. Four years later, it was made into a movie, and most Americans are probably more familiar with the movie than with the book. I, for example, did not know that it was a book until looking at some of the information in preparing for this episode.
A “graduate” is a person who has what we call earned a degree at a particular school, college, or university. “To earn a degree” means to complete a course of study and to be given some sort of certificate, we call it a “diploma” (diploma), that indicates that you have completed your studies in a particular area. I, for example, am a graduate of the University of Minnesota; that’s where I got my bachelor’s degree. I also graduated from the College of St. Thomas; now it’s called the University of St. Thomas. That’s where I got my master’s degree. And finally, I got my Ph.D. from the University of Southern California. So, I’m a graduate of three different universities. That’s what my father called a “permanent student,” which is sort of true; I’m still a student in many ways.
Anyway, the film The Graduate is about a young man named Benjamin Braddock, who is a recent university graduate, someone who has earned his university degree only a short time ago. In the plot, or the story, Benjamin’s parents host a graduation party for him. “To host” (host) means that they are the ones who plan the party and have the party for, in this case, their son. They invite friends and relatives to come to their home and celebrate their son’s graduation, something that is very typical. One of the guests is a woman by the name of Mrs. Robinson. She is the wife of Benjamin’s father’s business partner, someone his father works with, and Mrs. Robinson gives young Benjamin a ride home. The phrase “to give someone a ride” means to offer to drive someone somewhere when that person doesn’t have a car. So if you don’t have a car, and I do, I could give you a ride to Venice Beach, or I could give you a ride to Disneyland, which is about, oh, 45 minutes south by car from where I am.
Anyway, Mrs. Robinson gives our young Benjamin a ride, but she takes him to her house, not to his apartment, and at her house she tries to seduce him. “To seduce” (seduce) means to try to get the other person to want to have sexual relations with you. In this case, Mrs. Robinson is trying to seduce young Benjamin. She removes, or takes off her clothes, which is probably a pretty powerful way of seducing someone – I don’t know personally! They begin having an affair. “To have an affair” means to become involved in a romantic, sexual relationship. We usually use the term when one or both of the people in the relationship is married to someone else. So, a man has a wife and the man also has a girlfriend, what we used to call a “lover” (lover), and that is a situation where the man is having an affair with this other woman. Benjamin is having an affair with Mrs. Robinson, who is, as I mentioned previously, already married.
At the same time, Benjamin’s parents and Mr. Robinson – Mrs. Robinson’s husband – are trying to set Benjamin up with Elaine, who is Mr. and Mrs. Robinson’s daughter. “To set someone up with (someone)” means to try to get two people to date each other, because you think they will like each other in a romantic way. So you say to your friend, “My girlfriend has a beautiful cousin. Would you like to meet her? Maybe the two of you could go out on a date (on a romantic meeting).” This never happened to me, personally. I assume that all of my friend’s cousins were not very pretty!
So, here we have a strange situation. Benjamin is having an affair with the older Mrs. Robinson, but his parents and Mr. Robinson want him to date the daughter – Mrs. Robinson’s daughter. Well, obviously Mrs. Robinson doesn’t want Benjamin to date her own daughter, but Benjamin does anyway. Benjamin and Elaine actually fall in love with each other. Remember, Elaine is the daughter – the younger daughter, someone more close to Benjamin’s age. Benjamin tells Elaine about the affair he had with her mother and this, for some reason – I don’t know why, makes her very angry. So Elaine begins dating someone else, but Benjamin pursues her, continues to try to speak with her and tell her that he loves her.
I don’t want to tell you the end of the movie. We try not to do that on the English Café in case you, someday, want to see the movie. I can tell you that Mr. Robinson, the husband, finds out about the affair that Benjamin and his wife had, and that, of course, leads to some other very interesting developments – interesting things in the plot.
One of the reasons the movie The Graduate became famous, or at least continues to be well known, is that it had a famous song. The song is called “Mrs. Robinson” by two very popular singers in the 1960s and early 70s, Paul Simon and Art Garfunkel, who were known as Simon & Garfunkel. The success of the movie helped make the song popular, and I think the later success of the song helped keep the movie in the minds of the American people. The film itself was called one of the funniest American comedies of the year; this is back in 1967. One of the actors, the actor who played Benjamin – the main actor, we would call him the lead (lead) actor – was Dustin Hoffman. Hoffman later became famous in several other movies, and is still a famous actor. The movie won the Oscar, the best and highest award you can get for a movie in the United States, for Best Director. And in 1996, the U.S. National Film Registry, an organization that examines and looks at good films – good movies, named The Graduate a “culturally significant film,” meaning it was important in the development of pop culture in the 1960s. Now whether that was a good development or a bad development depends on your opinion of the movie.
In any case, The Graduate is well known, and the song, “Mrs. Robinson,” is well known. You may know the song. The chorus of the song, the part repeats in the song, goes something like this:
And here’s to you, Mrs. Robinson,
Jesus loves you more than you will know.
Whoa, whoa, whoa
God bless you please, Mrs. Robinson.
Heaven holds a place for those who pray.
Hey, hey, hey...hey, hey, hey
And so on. There is, of course, some irony in the fact that the chorus has these religious sentiments – these religious ideas, mentioning God and Jesus, when Mrs. Robinson, of course, is having an affair with this younger man. “Irony” is when you say one thing but you really mean another; you’re trying to convey a different meaning than what the words actually say.
Now let’s turn to our next topic, also a very interesting one, in my opinion one of the more interesting stories of the 1970s in American history, and that is Patty Hearst. Patty Hearst was born in San Francisco, here in the beautiful State of California, in 1954. She grew up in a very wealthy – a very rich family. Her great-grandfather was George Hearst, who worked and invested in the mining industry. “Mining” is when you dig into the ground to get things like gold and coal. Hearst became very rich – a millionaire, and became a senator from the State of California – a United States senator. He represented California in Washington, D.C. George Hearst’s son, Patty Hearst’s grandfather, was the most famous of all the Hearsts, William Randolph Hearst. William Randolph Hearst was what we would call a publishing magnate. A “magnate” (magnate) is someone who is very powerful in a particular area – a particular kind of business, and is also very wealthy. William Randolph Hearst was a publishing magnate, meaning he was very rich and powerful in the publishing industry. He created the biggest newspaper and magazine business in the world during the late 19th century and early 20th century. He was also elected to the United States Congress; he was in the House of Representatives, not the Senate. The Hearst family was a very important of U.S. history, U.S. politics, and U.S. journalism. The Hearst newspapers advocated, or favored certain political positions, especially in international relations, and were very influential in things such as the 1898 war against Spain, the Spanish American War, as it’s called.
Patty Hearst was William Randolph Hearst’s goddaughter. She became famous, but really she became notorious instead of famous. Someone who is “notorious” (notorious) is famous, but in a bad way, famous for the bad things that he or she has done. We might say that, for example, Adolph Hitler is notorious, or Joseph Stalin, or Pol Pot in Cambodia. These are all notorious people because they did some very bad things.
In 1974, in the month of February, Patty Hearst and her boyfriend were in their apartment when they were kidnapped. “To kidnap (kidnap) (someone)” means to take someone against their will – against their wishes, usually because you want to get money from the family of that person. Rich people’s children are sometimes kidnapped because the kidnappers believe the parents will pay a lot of money to have their children returned to them. There were several famous kidnapping cases in American history; this was one of the more famous ones.
Patty and her boyfriend were kidnapped by a group calling itself the Symbionese Liberation Army. Remember, this is the early 70s, when radical political groups were to be found in many Western European and western countries. The group made up the word “Symbionese,” it’s not a real word – or wasn’t a real word in English. They called themselves an urban guerrilla group. “Urban” refers to the city; the urban environment would be the environment in a city – a large city. A “guerrilla” is, in this case, a member of a small group that fights against the military or the government using unusual and often unexpected tactics. Normally we think of guerillas fighting somewhere in a jungle or a forest. An “urban guerrilla” would be a group that would do things in large cities, such as what happened with the Symbionese Liberation Army.
The SLA, as they were called back then, had a lot of radical ideas about how society should be changed, they wanted everyone to be treated equally, but they tried to achieve those things through violence. It was one of many fringe political groups in the 60s and 70s. Those of you a bit older than I remember the radical groups of those days; some of them are still around in some countries. A “fringe” (fringe) group is a small group that is very extreme and generally does not have a lot of people as part of the organization. Other fringe groups at this time included the Black Panther Party and the Weather Underground Organization.
The SLA kidnapped Patty Hearst and tried to demand the release of some of its members who were in jail. In other words, the group said it would set Patty free if the U.S. government let members of the Symbionese Liberation Army out of jail. Well of course, the government said no, so then the group changed its mind and said it would let Patty go if her family would give 70 dollars of food to every needy, or poor family in California. Patty’s father then donated six million dollars, which was worth a lot more than it is today, of food to poor people. However, the group said that the donation wasn’t big enough and that the food wasn’t very good, so it refused to release Patty.
Now things get really strange – really weird. Two months after she was kidnapped, Patty Hearst announced that she had joined the group. About two weeks after that, she participated in one of the group’s bank robberies, where they would steal money from a bank. She was finally arrested in September of 1975, about a year and a half after her kidnapping. After her arrest, Patty defended the members of the SLA. She refused to say bad things about them or provide information about the bad things they had done.
Now the Hearst family, of course, tried to defend Patty herself. They said that what happened to her was an example of what is called the Stockholm syndrome. A “syndrome” (syndrome) is sort of a medical condition, a group of physical or mental problems that affect people in a certain way. The Stockholm syndrome occurs when “hostages,” which is what we call the people who are kidnapped – they’re called hostages – begin to actually like the people who kidnap them. They defend them; they see things from their perspective. Not all psychologists agree on how this works, but there have been several cases. Stockholm, of course, is a city in Sweden, and the name comes from an example of this phenomenon that took place there.
During Patty’s court case, when she was brought before a judge because she had committed a crime – or at least she was accused of committing a crime, her lawyer argued that she was suffering from Stockholm syndrome. He said that she had been abused – she had been hurt – and brainwashed. “Brainwashing,” which was a very popular idea in the 70s – 60s and 70s, is the notion – the idea that your mind or your thoughts were being controlled so that you begin to believe everything you are told by a certain person or group of people. The prosecutor, however, the lawyer working for the government who was arguing against her, didn’t believe that she was brainwashed. The prosecutor said that she was a willing participant, meaning she wanted to do the things she did. She participated in the robbery, the stealing of the money, because she wanted to.
Hearst was, in fact, convicted, or found guilty of the bank robbery and went to jail. She was supposed to stay there for 35 years. However, she was released – she was let out of prison after only 22 months. Many people thought this was unfair. More recently, President Bill Clinton officially “pardoned” her in 2000, right before he ended his term as president, meaning he said that she was forgiven for her participation in the bank robbery. That was also controversial.
After that, other members of the SLA died or were arrested. Patty herself went on to become an actress and she appeared in several movies and TV shows; not very famous ones I don’t think, I can’t remember any of them right now. But I do remember reading about the Patty Hearst case in the 70s when I was in grade school and high school, and it is certainly one of the more famous cases of kidnapping and Stockholm syndrome in recent American history.
Now let’s answer some of the questions you have sent to us.
Yong-Woo (Yong-Woo) in South Korea wants to know the meaning of the words “embarrassed,” “ashamed,” and “awkward.” “Embarrassed” is when you feel what we would say self-conscious. That is, you feel as though you have done something wrong and everyone is looking at you or you are not very happy with what happened. For example, if the teacher in your classroom yells at you, says, “You’re a bad student Jeff McQuillan” – that happened a lot – I might become embarrassed. My face might turn red – redder than it is right now – and I would be embarrassed by that.
“Ashamed” (ashamed) is a little bit more serious than embarrassment. When you feel shame, you feel a great sorrow or sadness about something that you did wrong; you feel a sense of guilt, often. “Marie felt ashamed after she stole her friend’s money.” I would feel ashamed, too; Marie, you should give that money back!
“Awkward” (awkward) is different than “embarrassed” and “ashamed.” It means that you tend to perhaps cause embarrassment for other people; you say things that make other people feel embarrassed or feel a little strange. So for example, you meet someone in a café and you start talking, and the person suddenly asks you how much money you make – what is your salary. That might be a little awkward; people don’t like to give that information, especially to strangers – to people they don’t know. That would be an example of awkward. “Awkward” is sometimes also used to describe a person who does the things such as accidentally falling down or hitting a glass and making it go to the ground and break accidentally, what we would call “clumsy” (clumsy). “Awkward” has those two meanings.
“Embarrassed” and “ashamed” are close in meaning. “Ashamed” however, as I mentioned, that is a much stronger emotion. If you feel ashamed, it’s usually because you’ve done something you think is morally or ethically wrong, such as lying or stealing. “Awkward” is related, but it’s different. It’s related to “embarrassment,” but it usually is something less serious, and is often something that isn’t so much about feeling guilty as it is feeling strange, feeling like things aren’t quite normal here.
Maria (Maria) in Chile wants to know the use of the words “people” and “persons.” Both of these are plural, so when do we use one and when do we use another? Well, both “people” and “persons” refer to a group of humans – of human beings. “People” is the most common term used for more than one person. So between these two, “people” is more common. “The streets are full of people in Las Vegas.” There’s always people on the sidewalk, on the streets in the main part of town. Or, “The president needs the support of the people,” meaning the people who are in his country, or her country. “Persons” is sometimes used in more formal or legal situations to refer to a group of people – a group of humans. “American law protects persons with disabilities.” “Maria has been missing for a week; the police are putting her on their missing persons list.”
Except in a few common phrases, it’s usually okay to use the word “people” to talk about a group of human beings. I would not use “persons” unless you know that you are using it in one of those more common expressions, such as “missing persons.” The police sometimes talk about “persons of interest,” meaning the people that they are looking for who may have committed a crime.
One phrase that you will hear with “person” is the expression “in person,” which means that you are physically somewhere – you are physically there. In that case, you cannot use “people.” You can’t say “in people,” that doesn’t make any sense. You would have to say “in person,” although notice “person” is singular, not plural there.
Finally, Dasha (Dasha) from Ukraine wants to know the meaning of a quote he saw in the popular movie, Terminator 3, where our now former governor, Arnold Schwarzenegger, says the expression “talk to the hand.” “Talk to the hand” was first used in the early 1990s by some comedians – by some comedy groups. When someone is talking to you and you don’t want to hear them anymore, you want to stop, you would put your hand up the air with the palm of your hand – the front of your hand facing toward that person and say, “Talk to the hand.” Normally, when you put your hand up like that it means stop, and that, in fact, is what you are saying: stop talking, I’m not interested in listening to what you said. It’s not a nice thing to say to someone. It’s something of an insult. I would not use it to anyone unless you were doing so jokingly. But it does mean no one is listening to what you are saying, or I’m not listening to you so stop talking. It still can be heard, though it’s not as popular as it was back way, long ago, in the 1990s.
If you have a question or comment, I’m not going to tell you to talk to the hand. Email ESL Podcast at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
to give (someone) a ride – to offer to drive someone somewhere when that person does not have a car or the ability to drive
* My car is being repaired. Could you give me a ride to work tomorrow?
to seduce – to do things to attract or to cause someone to want to have a sexual relationship with one; to attract someone into doing something wrong or foolish
* Do you think the famous movie director should be punished for seducing young girls?
to have an affair – to become involved in a romantic and sexual relationship, especially when one or both of the people in the relationship are married to other people
* Georgina’s husband divorced her when he discovered she was having an affair with his best friend.
to set (someone) up with – to try to get two people to date each other, because one thinks they will like each other in a romantic way
* I want to set you up with my roommate. She’s perfect for you!
magnate – a person who is very powerful in a particular industry or field and is also very wealthy or powerful
* She is the most influential media magnate in this country, owning over 450 television stations, radio stations, and newspapers.
notorious – famous in a bad way; famous for the bad things one has done
* Ophelia is notorious for her mood swings: One day she’s very happy and the next she’s very sad.
to kidnap – to take someone away against their wishes, usually because one wants to get money from someone else
* Every parent fears that their child will be kidnapped, so they teach their children to not talk to strangers and to not follow anyone they don’t know.
urban guerrilla – a person or small group that fights against the military or government in a city using unusual and unexpected tactics
* Last night, a group of urban guerrillas tried to bomb city hall, but the police caught them before they could do any damage.
fringe – a part of a group that has very unusual or extreme beliefs and generally does not have a lot of believers or followers
* Dr. Haulter isn’t accepted by his colleagues at the university because of his fringe beliefs.
hostage – a person who has been kidnapped (taken against their wishes)
* When will George return the lawn mower he borrowed from me six weeks ago? I think I’m going to keep you here as a hostage until he brings it back!
to brainwash – to have one’s mind and thoughts controlled so that one begins to believe what one is told by a certain person or group of people
* Jelisa began socializing with a group of people who brainwashed her into thinking that school wasn’t important and having fun was the only thing that mattered.
to pardon – for a governmental official, usually the U.S. President, to officially forgive someone who has committed a crime
* Do you think the president will pardon the billionaire because his family gave a lot of money to the president’s political campaign?
embarrassed – feeling self-consciousness; feeling a loss of pride
* Jim was so embarrassed when he spilled wine on his pants and had to walk around all evening with dark stains on them.
ashamed – feeling shame or a loss of pride, often because one has done something wrong
* You took candy away from a smaller and younger boy. I’m ashamed of you!
awkward – making clumsy mistakes or to cause such mistakes; causing oneself or others embarrassment
* The baby looks awkward when he walks because he only started learning how to walk a few weeks ago.
people – plural form of “person”; more than one person
* How many people do you expect to come to hear the politician speak?
persons – plural form of “person,” most often used in legal or formal situations
* Our company pays for medical treatment of persons injured while on the job.
talk to the hand – an informal phrase meaning “I’m not listening to you” or “No one is listening or paying attention to what you are saying”
* - I wish someone would buy me a new TV.
* - Talk to the hand!
What Insiders Know
The Graduate: The Sequel
Most Americans know about the film The Graduate, but how many know that it is based on a novel by Charles Webb written in 1963?
Charles Webb wrote The Graduate “shortly” (a short time) after he graduated from college. Although the story is “fictional” (not true), in an interview, he “revealed” (told others about) the “inspiration” (something that gives one an idea) for the role of Mrs. Robinson. The older woman was actually the wife of a business associate of his father’s, but that woman and Webb never had an affair.
Years later, Charles Webb wrote a “sequel” to The Graduate called Home School that included the characters in the original book, but taking place 10 years later. “Initially” (at the beginning), he refused to publish the novel because of a “contract” (legal agreement) he signed in the 1960s. In that contract, he “gave up” (no longer could keep ownership of) the “film rights” for any sequels to The Graduate. This meant that the movie studio could make a film from the sequel without his “permission” (consent; authorization) and without him receiving any “compensation” (money or something else valuable) for it.
After many years, Webb found out that there was a possibility of getting the film rights back from the movie studio under a French “copyright law” (law on who has ownership of materials one creates, such as artwork or a book). Finally, he decided to publish his sequel through a company in Britain in 2007.