= 1557
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 251.
This is English as a Second Language Podcast’s English Café episode 251. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, where you can find additional courses in English. You can also support this podcast by becoming a member and getting our Learning Guides for each of the current episodes, including this one.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed. We’re going to listen to them and then, as always, we will explain what they are talking about. Today we’re going to listen to an author named Anna Jane Grossman. She’s written a book called Obsolete: An Encyclopedia of Once-Common Things Passing Us By. We’ll explain what that means in a second. And, as always, we’ll answer a few of your questions. Let’s get started.
Today we’re going to listen to the author of a book called Obsolete (obsolete): An Encyclopedia of Once-Common Things Passing Us By. The word “obsolete” is used to describe something that is no longer useful, something that doesn’t have any value because, typically, it’s been replaced by something better and newer. For example, records and tapes nowadays are pretty much obsolete, because people listen to their music on CDs or with MP3s. That’s an example of a technology that has become obsolete, although there are some people who still like to listen to the old records, as I did when I was growing up back in the early 19th century.
Now, the expression “once common” means simply something that was common many years ago, something that you would usually see many years ago. “To pass (something) by” is a phrasal verb meaning to be removed from our experience. These are things that we no longer see or use. This book, then, is an “encyclopedia,” it’s a listing and a description of these things.
The book’s author is Anna Jane Grossman. She’s going to talk about some of the things in her life that now become obsolete. She’ll start by talking about large, portable radios that were common in the 1960s and especially the 1970s, when I was a teenager. These are called “ghetto blasters,” and we’ll explain what that term means in a second. First, let’s listen:
[recording]
And in New York, they used to talk about how every block had its own kind of soundtrack based on whoever was toting around their ghetto blaster.
[end of recording]
She says that in New York – New York City, people used to talk about how every block had its own kind of soundtrack. A “block” is also called a city block. It’s an area of land in a city that is surrounded by four streets, usually forming a square or a rectangle. For example, you might have two streets, First Street and Second Street that go north to south. You may have two other streets, let’s say Washington and Lincoln, that go east to west. Well, if you look at a map the square that is surrounded by these streets is a block. We often use this to describe short distances in the city: It’s five blocks from the ocean, or it’s two blocks from my house.
The author here says that each block in New York had its own soundtrack. A “soundtrack” (one word) is the music usually that is recorded for a movie. The soundtrack has a lot of power to change the “mood,” or the feeling of a movie, making it more romantic, or more suspenseful, for example. The author says here that each New York City block had its own kind of soundtrack, meaning it was music that somehow defined or was related to the people who lived on that block. She says that the soundtrack was based on whoever was toting their ghetto blaster. To “tote” (tote) means to carry something as you are walking. Some women carry very large purses that are called “tote bags.”
In New York City, people used to tote around – that is, used to tote a ghetto (ghetto) blaster (blaster). This is a portable stereo radio and cassette tape player that can play very loud music. In the 1980s, young men were often seen in certain neighborhoods carrying a large stereo on one shoulder, playing their favorite music as loud as they could. This was called a “ghetto blaster,” in part because the music was “blasted,” which means here to play very loudly, through a poor section of the city. A poor section of the city is sometimes called the “ghetto,” although we don’t use that expression very often anymore, but it was much more common in the 60s and 70s.
Let’s listen to her talk about this ghetto blaster one more time.
[recording]
And in New York, they used to talk about how every block had its own kind of soundtrack based on whoever was toting around their ghetto blaster.
[end of recording]
The author says that the ghetto blaster is an example of something which is now obsolete, because everyone listens to their music now on iPods or on their phone or on some sort of portable music device.
Another technology that she thinks is becoming obsolete, although certainly isn’t obsolete yet, is the radio. First let’s listen to her quote, and try to understand what she’s saying.
[recording]
The thumb and the forefinger have so much less to do these days. They used to be so important in turning those knobs and now they’re not so much. But I do listen to a lot of podcasts and I do listen to radio online. And there are so many choices of what you can listen to, thanks to the Internet, which is in so many ways a bonus. On the other hand, because we no longer have these one, two, three dozen stations that we all know across the country, I don’t think we have as many cultural references that we can share with the person next door.
[end of recording]
She begins by saying that the thumb and the forefinger have much less to do these days than they did in the past. The “thumb” is your first digit – your first finger, the shortest one. Your “forefinger,” sometimes called your index finger, is the second finger, the finger next to the thumb, that you typically use to point to something. She says, “The thumb and the forefinger have so much less to do these days,” meaning we don’t use them as much. The reason is that we don’t use the radio as much as we used to, especially the older radios that had something called “knobs.” A “knob” (knob) is a round button that controls something or opens something. We have, for example, doorknobs, that we put our hand on to open a door. We also, back in the old days, used to have knobs that you would turn on a radio with. Nowadays, it seems that everything is done more with buttons that you press, though there are some things that you still turn a knob with. So, because we don’t listen to the radio, especially the old kinds of radios, we don’t use our thumb and forefinger as much. We instead use our fingers with MP3 players or our computers. So, she says that the thumb and forefinger used to be so important in turning those knobs and now they’re not so much, meaning they’re not as important.
She continues, “But I do listen to a lot of podcasts and I do listen to radio online.” Notice that she uses the word “do” before the verb: “I do listen.” She wants to emphasize that there is something that she continues to do, even though you might not expect it from the previous sentence. She’s talking about people not listening to radios, but she wants to emphasize that she does still listen – she listens now to a lot of podcasts, like ESL Podcast, and a lot of online radio, radio that goes over the Internet. She says, “And there are so many choices of what we can listen to, thanks to the Internet (because of the Web), which is in so many ways (in a lot of ways) a bonus.” A “bonus” is something that is an advantage, a good thing. However, she says that on the other hand (looking at things from a different perspective), we no longer have just one, two, three dozen stations that we all know across the country.
Back in the old days, a lot of music was on AM radio, and AM radio especially at night tends to be able to travel farther – the radio signal travels farther. You can turn on your AM radio in Los Angeles at night, for example, and hear stations from Mexico, which is more than 200 miles away. That’s something that people used to do in listening to music. And, they were certain AM radio stations that had very powerful signals that you could hear from many miles away. Now, however, people aren’t listening to radio, especially AM radio, for their music and so, she says, we have somehow lost something. We no longer have the same stations – radio stations that we all used to listen to because we have these other choices.
One of the problems, she says, is that we have lost some of the cultural references, that we no longer share these cultural references. A “cultural reference” is something that most people from a single culture are familiar with. Here on ESL Podcast, we try to talk about the cultural references in the United States that the typical, average American would know: movies, songs, books, people, and so forth. Cultural references give us something to talk about; they make it easier for us to communicate with each other. They also give us a sort of identity. When we meet people from other cultures, it’s sometimes difficult because we don’t have the same cultural references.
Anna, the author, believes that with more listening options on the Internet we no longer have as many cultural references that we can share with the person next door. A person who lives “next door” (two words) is someone who lives in the house next to you, or the apartment or condominium next to you. That’s one meaning. Here, she is using the expression more generally to mean people who are in our same neighborhood or in the same city or area where we live.
Let’s listen to the author talk again about this topic.
[recording]
The thumb and the forefinger have so much less to do these days. They used to be so important in turning those knobs and now they’re not so much. But I do listen to a lot of podcasts and I do listen to radio online. And there are so many choices of what you can listen to, thanks to the Internet, which is in so many ways a bonus. On the other hand, because we no longer have these one, two, three dozen stations that we all know across the country, I don’t think we have as many cultural references that we can share with the person next door.
[end of recording]
I know that she is sometimes difficult to understand because she’s very loud at some points, and then it’s as though she were talking very quietly – softly. So, it’s a little hard to understand her, but I hope with our explanation you were able to understand.
Finally, we’ll listen to a quote from Anna about how some of the technology we use today is beginning to become obsolete, technology, in some cases, that have been around less than 20 years such as email. Let’s listen.
[recording]
A lot of people today, especially high school students, college students, only use email when they’re communicating with professors, older relatives, that kind of thing. Otherwise, they’re text messaging, they’re Tweeting, they’re using Facebook. And all of those are forms of communication that have to be quite short. Things are just getting shorter and shorter, terser and terser, until I wonder if we’re just going to be shouting one-syllable words at each other, like monkeys. Yes, it’s progress, but it definitely waters down the kind of relationships that we have.
[end of recording]
Anna says that a lot of people – that is, many people today, especially high school students (students between the ages of, say, 13, and 18), college students (those at the university) only use email when they’re communicating with professors, older relatives, that kind of thing. Older relatives would be parents, aunts, uncles, brothers and sisters who are older than you are. They only use email, then, for people I guess of my generation and older. She says, “Otherwise, they’re text messaging.” “Otherwise” is used to introduce an idea that’s different from what we just said, that is an exception to what we just said. For example, when the weather is nice, I like to go on long walks. Otherwise, I prefer to stay at home, meaning when the weather isn’t nice I stay at home.
Anna is saying here that young people are starting to move away from email, they only use it to communicate with older people – people older than themselves. Now, they’re using other technologies: they’re text messaging. To “text message” means to send a message using your telephone. You don’t actually talk; you type a message and you send it. She says they’re also Tweeting, and using Facebook. The new verb in English “to Tweet” (Tweet) is to send a message using a service provided by Twitter.com (Twitter). Twitter is a way of sending short messages, sort of like text messages, but to other people via the Internet. We have a Twitter account at ESL Podcast. In fact, I’ve had mine for longer than probably 99 percent of the people out there. I got mine very early. It’s eslpod; you can look for us on Twitter.com by searching for eslpod.
So, Tweeting is something that younger people are using now instead of email. Facebook, you may know, is what is called a social networking site that lets people connect to their friends. We talked about social networking on English Café 223, so if you look at that or listen to that Café you can get more information on things like Twitter and Facebook.
Anna goes on to say that text messaging, Twitter, and Facebook are forms of communication that have to be quite short – that is, very short. She says that things are just getting shorter and shorter, terser and terser. “Terse” (terse) means using as few words as possible. If you are mad or upset at someone, you might be very terse with them; you may not speak to them very much, use very few words.
Well, these new technologies require you to be terse, because you can only send a message, typically, that is, say 140 characters or letters long. She says, “I wonder if we’re just going to be shouting one-syllable words at each other, like monkeys. She’s saying that because these communication technologies require short messages we will start communicating in simpler and simpler language, just like an animal using basically one sound – one syllable to try to communicate. She’s joking here, of course, but she’s making the point that complicated, complex communication is becoming more difficult with the new technologies.
She says, “Yes, it’s progress,” meaning it’s something that is moving forward. “But,” she says this change in technology “definitely waters down the kind of relationships that we have.” “To water down” (two words) is a phrasal verb meaning to make something less powerful, to make something weaker, to make something less meaningful. The phrase is actually one we use with alcoholic beverages, where a bar might try to save money by mixing water into the alcohol so that you think you’re getting more alcohol than you are. This is called watering down the drinks. Well here, it’s used to mean more generally to make something weaker, to make our relationships weaker.
Let’s listen to Anna one more time.
[recording]
A lot of people today, especially high school students, college students, only use email when they’re communicating with professors, older relatives, that kind of thing. Otherwise, they’re text messaging, they’re Tweeting, they’re using Facebook. And all of those are forms of communication that have to be quite short. Things are just getting shorter and shorter, terser and terser, until I wonder if we’re just going to be shouting one-syllable words at each other, like monkeys. Yes, it’s progress, but it definitely waters down the kind of relationships that we have.
[end of recording]
So that, at least, is one person’s opinion of the changing technologies, especially those that have become or will soon become obsolete.
Now let’s answer a few of your questions.
Our first question comes from Sakai (Sakai) in Japan. Sakai wants to know the difference between “regarding,” “concerning,” and “as for.” All three of these words are actually quite similar in meaning usually. They mean having to do with something, related to something, with respect to something. For the most part, usually you can use any one of these three. You could say, “Concerning John, he will not be able to come to the party.” Or, “Regarding John, he won’t be able to come to the party.” “As for John, he won’t be becoming to the party.”
“Regarding” and “concerning,” especially, can be used in places other than the beginning of the sentence, or the beginning of what we call an independent clause, a part of the sentence that can be on its own – that can be independent. “As for” is usually at the beginning of a sentence an independent clause. For example: “I don’t know much concerning the topic of today’s meeting.” “I don’t know much regarding the topic of today’s meeting.” You would not say, “I don’t know much as for the topic of today’s meeting,” that would not be possible. You could say, “As for the topic of today’s meeting, I’m not really sure what it’s about.” Or, you could put it in the middle of the sentence, but make it the beginning of the independent clause, the clause or part of the sentence that has a subject and verb and can be independent, or stand by itself. You could say, “I don’t know who planned this meeting, and as for the topic of the meeting I don’t know anything about that either. So there, “as for” is in the middle of the sentence, but it comes at the beginning of an independent clause.
“Concerning,” regarding,” and “as for” are all somewhat formal; they’re certainly acceptable in business and formal speaking and writing. More informally, however, people would just use “about”: “I don’t know much about today’s topic.” Or, “About our dinner plans, I think we should have fish tonight.” So, “about” is probably more common in informal speech than these three expressions or words: “regarding,” “concerning,” and “as for.”
Manuel (Manuel) in Spain wants to know the meaning of the expression “I can’t be bothered.” This expression can have two meanings: one, it can mean that I am too busy or too lazy to do something about a certain situation. It doesn’t concern me, it’s too much trouble, or it will be too difficult. For example: “Dan wants me to meet him for dinner tonight, but I can’t be bothered.” I don’t really like Dan, I don’t want to have dinner with him.
“Can’t be bothered” can also mean that you do not want or are unable to be interrupted: “I can’t be bothered while I’m studying for my English test tonight.” That means don’t interpret me, don’t come and talk to me, don’t bother me.
“Can’t be bothered” in the sense of being too lazy or too unconcerned about something is a little more common in British English, although you will hear it in American English as well. That first meaning is often used to talk about someone who is rude or lazy, and we often put the word “even” to emphasize that: “He can’t even be bothered to call me on the phone, he’s so lazy.” “I can’t believe how lazy Bella is, she couldn’t even be bothered to turn off the lights when she left the room.” You’re complaining about the other person.
Finally, we have a similar question from both Gustavo (Gustavo) from an unknown country, and Byron (Byron) from El Salvador. The question has to do with an informal way of greeting someone: “How you doing?” “How you doing?” is short for “How are you doing?”; it is a very informal expression, and not including the verb makes it, in part, informal. It’s something you can use with your friends and your coworkers. It can also be used as a friendly way of greeting people that you are meeting for the first time in an informal setting, such as “Hi, my name is John,” and the other person says, “Oh, I’m Bill. How you doing?” “How are you doing?” – same thing.
“How you doing?” with the emphasis on the second word is something that was made famous or popular by the character Joey on the TV show Friends many years ago – not too many years ago. It is usually said in a funny way. Joey used it to try to pick up women. That is, try to get women romantically interested in him. So, he would see a beautiful girl and he’d say, “How you doing?” Normally, however, when this is used in that way it’s done as a joke nowadays. I should also point out that “doing” is some time shortened to “doin’” (doin’) and “you” is sometimes changed to “ya” (ya). “How ya doin’?” “How you doing?” Those are the same.
Don’t think we can’t be bothered to answer your questions. We won’t have time to answer everyone’s, but we’ll our best. Email them to eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you, as always, for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
Obsolete Audio and Video Formats
As “audiovisual” (related to things that we watch and/or listen to) technology continues to change, many audio and video “formats” (the way something is packaged and used) are becoming “obsolete” (no longer useful or valuable) because they have been replaced by newer technologies, like CDs, MP3 files, and DVDs.
The “eight-track tape” or “eight-track cartridge” is a good example of an obsolete audio format. It was very popular in the United States from the mid-1960s to the early 1980s, but today, it is almost never seen or used. Each eight-track tape was a plastic box that had a “coiled” (wound or wrapped in a circle) magnetic tape with the recorded music. These were replaced by the smaller and lighter “cassette tapes,” which have a magnetic tape coiled around two small wheels. Of course, now cassette tapes are mostly obsolete, too, as people prefer CDs, which never have to be “rewound” (wound or wrapped in the other direction) and let listeners choose which songs they want to hear without having to wind through the other songs first.
“Betamax” is an example of an obsolete video format. It was replaced by “VHS cassettes,” which were smaller and lighter. Some people do still prefer Betamax over VHS, because they think it offers better picture quality, but most people haven’t seen Betamax in years. Today, even VHS is becoming “rarer” (less common), as most people prefer to watch their videos on DVD or download them electronically from the Internet.
Some people “predict” (make statements about what will happen in the future) that CDs and DVDs will become obsolete within the next few “decades “(groups of 10 years), replaced by electronic audiovisual files. “Only time will tell” (no one can know the future until it actually happens).
What Insiders Know
The Pinkerton National Detective Agency
In books and movies, the private investigator is often “portrayed as” (given the image of) a romantic character, involved in solving mysteries. In real life, private investigators, or P.I.s, are professionals who do a “wide array” (many different kinds) of work.
In the United States, P.I.s often work for attorneys or lawyers in “civil” cases, where people are suing each other, often for money. P.I.s also work for insurance companies to investigate suspicious “claims,” or requests by people who say that they should be paid money because of something bad that happened to them or to their property. P.I.s are also hired by individuals to investigate personal matters, often in “divorce” (ending a marriage) situations, where evidence of “adultery” (having sexual relationships with someone not your husband or wife) or some other “wrongdoing” (illegal or dishonest behavior) would be useful in court.
In the U.S., the first and perhaps most well-known private detective agency was the Pinkerton National Detective Agency, which was “founded” (started) in 1850. Allan Pinkerton, the founder, was famous because he had put a stop to a “plot” (plan) to “assassinate” (kill) Abraham Lincoln, during the period between when Lincoln was elected and when he “took office” (officially began his time as president). Because of this, the Pinkerton Agency was hired to provide “armed” (with weapons) security service for President Lincoln.
The Pinkerton Agency also became a major part of “labor disputes,” or disagreements between company owners and their workers. Large companies hired Pinkerton detectives to “infiltrate” (become secret members of) the unions. “Unions” are organizations created by workers to try to get their bosses to provide better pay and better working conditions. Some of the major companies and big bosses hired the Pinkerton Agency to discover union plans and to try to stop their activities.