= 1318
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 13.
This is English as a Second Language Podcast’s English Café episode 13. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com.
On this Café, we’re going to talk about two very different things, but two things that mean a lot – or at least are very familiar – to a lot of Americans: Spam? and Valentine’s Day. The two have nothing to do with each other, but I think they’re both interesting topics. And, as always, we’ll answer a few of your questions. Let’s get started.
If you’re like me, you use your email all the time. Unfortunately, using email nowadays means that you are vulnerable to something called “spam.” “To be vulnerable” (vulnerable) means that it is possible that someone may attack you or that something bad will happen to you. “To be vulnerable” doesn’t mean that something bad has happened to you already, but that you are at risk of something happening. It’s possible something will happen that you won’t like.
So, whenever you hear someone talk about “being vulnerable to” something, you know that that something is something bad, and that’s the case here. When I say you’re “vulnerable to spam” if you use email, I mean that you may have something bad happen to you, which is to get spam email. “Spam” (spam) is email you don’t want, often email that is trying to sell you something or to do something bad. Sometimes spam email is or contains some sort of scam.
A “scam” (scam) is an attempt to cheat you of your money – to steal your money by cheating you – and of course, scams are very common in emails as they’ve always been common in other media. If someone sends you a spam with a scam to get money from you, then we would call this a type of “fraud.” “Fraud” (fraud) is the crime of cheating someone by telling that person lies, things that aren’t true, or by doing something dishonest to get the money from the person. Don’t confuse “fraud” with “Freud” (Freud) who was a famous psychoanalyst, but not as far as I know, a criminal.
“Spam” is also used to describe something else. In fact, it was originally used to describe a type of food, and is still used that way. There’s a company in my home state of Minnesota called Hormel Foods. It has its main office in the southern part of Minnesota. Hormel Foods makes a kind of food called “Spam.”
Spam? is cooked meat that is then put into a can and sold just as you would buy canned vegetables. The meat in Spam is pork – that’s meat from a pig. It includes pork meat from the shoulder of the pig – the shoulder is the area where the neck meets the limb or the leg, in this case. In a human being, the shoulder is where your arm meets the rest of your body.
“Spam” also has another kind of meat from a pig in it that’s called “ham” (ham). There’s other things in Spam in addition to the shoulder meat of the pig and ham. There are things added to the Spam to give it more flavor – to give it more taste – and also to help keep the cans of Spam, the meat in the cans, from spoiling or going bad. When a food “spoils,” it’s no longer edible. You can’t eat it anymore. It’s bad for you to eat.
Spam was first sold in the United States back in 1937. Because it was cheap and very easy to transport, or move, from one place to another and because it didn’t spoil easily, you could keep it for many days, many weeks, many months without any problems, it was used a lot by the United States military during World War II in the early 1940s. During the war, it was very difficult to get fresh meat to the soldiers who were fighting. Spam provided an answer to this problem. In fact, the soldiers were served Spam sometimes three times a day: breakfast, lunch, and dinner.
Now, as you can imagine, if you eat anything three times a day, you might eventually get sick of it – that is, you might tire of it. You might no longer want it. Spam, then, got a “bad reputation,” we might say. People made jokes about it during the war. In fact, some people said Spam stood for “SPecial Army Meat,” meaning it was meat that you could only find in the army, although that wasn’t true because Spam, of course, was sold even before the army started using it, but that was the joke.
So, Spam as food had a very bad reputation, something that most soldiers, anyway, grew tired of and didn’t really like eating. But not everyone disliked Spam. In fact, after World War II, the company that makes Spam, Hormel Foods, wanted to keep the associations Spam had with the war and with the general concept of patriotism. “Patriotism” (patriotism) is a strong feeling of support and love for your own country.
Hormel wanted to keep this association that people had with America and Spam, and so it went out and it hired, it employed, former servicewomen – women who had served in the military during the war – to help promote and advertise its products. These women were called the “Hormel Girls.” They weren’t girls, they were women, but that’s the name they used.
By 1948, there were 60 Hormel Girls, 16 of them forming an orchestra – a group of musicians. And these Hormel Girls would go out and perform songs together. They would go to small towns, they would go to cities, and all the while they were promoting Spam in addition to, of course, entertaining the people who went to see them. The Hormel Girls were finally disbanded – that is, the group stopped existing in 1953 – but for five years or so they were quite popular.
Today, Spam is still sold in the United States, even though most people don’t think it’s very good or very high quality food. If you live outside of the U.S., you might have seen it at the market since it’s sold now in over 40 different countries. Interestingly, the place where Spam is the most popular is the state of Hawaii. Spam was introduced to Hawaii during the second World War and eventually became part of Hawaiian cooking.
If you go to Hawaii, you can often see Spam used in different popular dishes – not in a good restaurant, but in street food or food that families might make for themselves. Sometimes people call Spam the “Hawaiian Steak,” even though there’s no beef in it. So, if you go to a fast food restaurant or eat some street food in Hawaii, or perhaps eat with a Hawaiian family, you might have some Spam and then you can decide for yourself whether you think it’s good enough.
Now coming back to our original topic, which was email spam, you may wonder: “Why do we call unwanted email “spam” in English?” It undoubtedly had to do with this negative association people had with Spam during World War II and after. And so, it was considered something that no one would want.
Our second topic is quite different – it has nothing to do with Spam – and that is Valentine’s Day, or Saint Valentine’s Day. Valentine’s Day is on the 14th of February, as most of you probably know. In the United States, Valentine’s Day is not a holiday – you still have to go to work and school – but it is celebrated by many Americans as a day of thinking about and perhaps giving a gift to someone that you are romantically interested in: a boyfriend or a girlfriend, a husband or a wife.
People aren’t completely sure where the idea of Valentine’s Day comes from – how it got associated with romance – however the most common story, probably the one closest to the truth, is that Valentine’s Day is related to a Christian martyr named Valentine. A “martyr” (martyr) is a person who is killed because of his or her religious beliefs. So, a Christian martyr is someone who died because they believed in Christianity and someone killed them for believing in that. Many religions have martyrs. Christianity has martyrs, and one of those martyrs was called Saint Valentine.
The story is that in about 270 A.D., about 270 years after the founder of the Christian religion was born, Jesus Christ, there was a priest – a leader, a religious leader – by the name of Valentine who was put in jail or prison for believing in Christianity. Before being put in jail, Valentine as a priest often performed wedding ceremonies – marriages that took place between Christian men and Christian women. He would have that association, and so eventually when he was killed, when he was martyred in prison, people began to associate his name with romance and with love.
There is one particular story (we don’t know if this is true or not) but one story says that Valentine had cured one of the daughters of the jailer, the person who was responsible for keeping him in prison. The daughter had some sort of illness and Valentine cured the daughter of her physical problem. He made her healthy again. Before he was executed – before he was killed – he wrote a letter to the daughter and he signed the letter “From Your Valentine.”
So, that perhaps is one association with the idea of giving someone a Valentine, because in English a “Valentine” is a card or a note or a letter expressing your affection and/or love for another person. Valentine was not, in the story anyway, in love with the daughter by any means, but it was a way of him signing his letter, and because he then had this association with marriages and romance, you can see how all of these things came together and developed a tradition which we now have around St. Valentine’s Day.
There are several traditional gifts that people give on Valentine’s Day, at least in the U.S. One of those gifts is a stuffed animal. A “stuffed (stuffed) animal” is basically a small toy in the shape of an animal. You don’t take an actual animal and then put things inside of it and then give it to someone. That would be interesting, but it’s not what we mean by “stuffed animal.” Stuffed animals aren’t animals, they are toys made to look like animals.
Stuffed animals are typically made with a sort of cloth, or what we might call a kind of “fabric.” “Fabric” (fabric) is usually a soft cloth that something else is made of – a piece of clothing or, in this case, a small toy animal. All the gifts associated with Valentine’s Day could be given any day of the year to someone you love. It doesn’t mean you would only give these gifts on Valentine’s Day. Chocolates, for example, are popular gifts on Valentine’s Day. Another popular gift, especially for girls or women, would be roses. Giving red roses would be a very romantic gesture, a very romantic thing to do.
What many women that I have met like in particular on Valentine’s Day is jewelry. “Jewelry” (jewelry) is something you wear on your body, usually made of metal or some kind of stone that makes you look or is supposed to make you look more beautiful. I’ve worn rings, for example. That’s a kind of jewelry. I don’t look any more beautiful with my ring on than off. You could also wear necklaces, which go around your neck or earrings, which go on the bottom of your years. All of these would be examples of jewelry. Diamond jewelry is particularly popular with many women I know, including my wife.
In American schools, however, Valentine’s Day is not usually celebrated with children giving each other jewelry; rather, it’s more of a day of celebrating friendship among the children. Since they’re young children and most of them are not interested in each other romantically, the children nevertheless still give each other gifts oftentimes on Valentine’s Day. I’m talking about children between the ages of, say, six and twelve.
On Valentine’s Day, it is popular in many schools for children to give each other small cards that have their names on them, and they give these cards to other people in their class that they like who are their friends, just as people give cards on Christmas Day or on a birthday. There’s also very popular kind of candy. It’s very small and it’s made in the shape of a heart, and I remember when I was growing up it was very popular to have these little boxes of candy that you would give to other people or other people would give to you on Valentine’s Day.
So, in American schools, especially what we would call “elementary schools” for younger children, Valentine’s Day has its own particular customs and traditions that are somewhat different than the ones that we use for adults. St. Valentine’s Day is celebrated on the 14th of February, in case you didn’t know, or in case I didn’t mention that already.
Now let’s answer a few of the questions that you have sent to us.
Our first question comes from Pascal (Pascal) in France. Pascal’s question has to do with the use of possessives in English spelling. A “possessive” (possessive) is a word or a form that tells you what belongs to whom, or “who owns what,” we might say. So, for example, in the phrase “Jeff’s cup,” we know that the cup belongs to Jeff. We indicate that in this case by putting an apostrophe mark after the last letter of the word. In this case, the second “f” of Jeff and an “s” immediately after that.
So, instead of “the cup of Jeff,” we can say “Jeff’s cup.” The two things mean the same. The two things both indicate a possessive form. In spelling, we use an apostrophe (‘) before the “s.” Although, obviously, when you’re listening to it you don’t hear the apostrophe because punctuation is only for writing. We don’t use punctuation when we speak. “Jeff’s cup,” then, is an example of a possessive form. Jeff is the owner of the cup. Jeff “possesses” the cup, we might say. One of the uses of the verb “to possess” is to have, to own, to be the owner of something.
Our next question comes from Yu (Yu), originally from China, but now studying in the country of Ireland. Yu wants to know the meaning of the expression “in terms of.” “In terms (terms) of” something is a very common expression in English. Let’s give an example. “In terms of the Olympics, I think the best sport (or the best event) is skiing.” “In terms of” in that sentence means that when we are talking about this subject or this topic. You use “in terms of” to limit the topic or the issue that you are talking about.
“In terms of weather, I think Hawaii is the best state to live in.” It might not be the best state to live in in terms of how much money you have to spend to buy food. Hawaii is a set of islands, and it’s expensive to live in Hawaii because all the food has to be – well, most of the food has to be transported into the islands. So, in terms of the cost of food, it’s not the best place to live, but in terms of weather, it is. “In terms of,” then, is used to specify the particular issue or topic that you are talking about and that you want to give some opinion on.
We move along to our next question. This one is coming from Philip (Philip) in Germany. Philip has a question about three similar words or expressions: “must,” “have to,” and “got to.” What’s the difference between “I must go,” “I have to go,” and “I have got to go”? All three of these basically mean the same thing.
“I must go” (and notice we don’t say, “I must to go” – we say, “I must go”) means that something is necessary. “I have an obligation to do it.” If you say, “I have to go,” you’re saying the same thing. It’s necessary. It’s an obligation. The expression “I got to go” or “I’ve got to go” is much more informal, but it means the same as “have to” – “I have to go.” “He has to be at the dinner tonight.” “He’s got to be at the dinner tonight.” “He must be at the dinner tonight.” All three of those expressions are basically the same.
Now, sometimes people will use “I’ve got to do something” when they want to express a certain urgency about something. Not only is it an obligation, not only is it necessary, but it must be done now. It must be done immediately. “Urgency” (urgency) means you need something to happen right now. If you go to a hospital and you say you need “urgent care,” you mean that you need a doctor to see you right away or a nurse to help you right away because you are really sick. It’s urgent. It needs to be done immediately. Now.
Finally, we have a question from Gero (Gero), also from Germany. This question has to do with the difference between two verbs, “to raise” (raise) and “to rise” (rise). “To raise” something is to lift something up or “to elevate” something, we might say, with our hands or with some machine. You could also use other parts of your body, I guess. You could raise something with your legs, or you could simply raise your legs. It means to bring something up into the air – to make it higher up, if you will.
That’s the use of the verb when we’re talking about physical objects. We also use the verb “to raise” when we are talking about helping children grow up, helping your sons and daughters grow up. My parents, bless them, raised 11 children. They helped 11 children grow up in their household. They paid for their food and their clothing and so forth, just as parents would for any of their children, at least until they’re 18.
“To rise” (rise) is a little different. “To rise” means that you as a person physically stand up. You might be sitting, and then suddenly you rise. Now, used in that context, it’s a little formal. We don’t normally say, “I rise in the morning at six a.m.” We would say, “I get up at six a.m.” or “I get up out of my chair and walk over and get some coffee.” “Rise” is also used for the sun. We talk about the sun “rising” in the sky. It means it goes up higher as, of course, the earth goes around the sun.
Another use of “rise” not referring to a human being is when we talk about a river rising. A river “rising” is a river that is getting higher and higher – that has more and more water. If a river rises too high, it can cause what we call a “flood” (flood). A flood is when you have water going places that you don’t want it to go – water from a river, in particular. In Egypt, for example, you can think of the River Nile. The Nile floods and that helps give water, of course, to the land around the Nile and allows agriculture to take place – the growing of food.
So, “rise” can be applied to a person, a human being, getting up out of his chair or getting up out of bed. That’s a more formal use. “Rise” also applies to the sun, or perhaps even the stars coming out in this night sky. We can talk about the sun “rising” in the morning. The other word that we would use with the sun when it goes down at night, if you will, is “to set.” We talk about the “rising” and the “setting” of the sun. “Rising” is what happens in the east in the morning, and “setting” is what happens in the west in the afternoon.
Again, in case you’re confused, the sun doesn’t actually rise – the earth turns around and goes around, or moves around, the sun. At least, I think that’s right. Or does the the sun go around the moon? No. Anyway, I was never very good at astronomy.
If you have a question or comment not about astronomy, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
to be vulnerable – to be open to an attack from someone or something that could cause harm; to be unable to defend oneself from getting hurt
* Debra has poor health, and as a result, she is vulnerable to viruses and infections.
spam – unwanted email, especially when that email contains something that can harm one's computer or attempts to trick someone into sending money or personal information; a type of food made from ham (pig meat) and packaged in a square metal can
* When Burton received an email asking him to type in this bank account information, he knew it was spam.
fraud – an act to cheat or steal from another person; tricks or dishonest methods to gain something from someone else, especially when it could not be gained using honest methods
* The advertisement offered an expensive vacation for a very low price, but it turned out to be a fraud.
Valentine's Day – a holiday to celebrate love, occurring every year on February 14th; a holiday on which people give gifts to other people who they love, especially to people who they love romantically
* During their first Valentine’s Day as a couple, Michelle and Julius went on a date to an expensive restaurant and watched a romantic movie.
card – a piece of stiff, thick paper or thin cardboard, often folded in half, with a message written or printed on it given to someone on a specific occasion
* Gladys sent her brother a card with a funny poem in it on his birthday.
stuffed animal – plush toy; a small cloth toy made in the shape of an animal and filled with soft material
* When he was a child, Robbie’s favorite stuffed animal was a toy dog made from fuzzy blue cloth.
fabric – cloth material; soft material used to make clothing, blankets, and other similar items
* Britney is allergic to wool, so she needs to wear sweaters and other clothing made from other types of fabric.
rose – a flower with many petals, usually in red, pink, white, or yellow, and with a thorny or prickly stem; a flower that is usually given as a romantic gift and treated as a symbol of romance
* On their anniversary, Manual bought his wife a bouquet of twelve red roses.
jewelry – an item, usually made from metal and gemstones, that is worn on the body as a type of decoration or ornament, such as necklaces and bracelets
* Tambra does not wear much jewelry, but she does have a pair of gold diamond earrings that she wears on special occasions.
possessive – feeling a strong sense of ownership; when a word describing a person, place, or thing is changed by adding an apostrophe-"s" ('s) to indicate that another object being described belongs to that person, place, or thing
* Derrick’s possessive nature caused him to seem very jealous and demanding.
in terms of – concerning or dealing with a specific topic; an expression used to describe information that only applies to a specific topic
* In terms of which pets are the easiest to take care of, Rosina believes that goldfish are best.
urgency – an action that must be taken immediately; a feeling of great importance that must be taken care of immediately
* Ellis rushed his daughter to the hospital with great urgency when he realized that she had a high fever.
to raise – to lift something up; to care and provide for children until those children are old enough to care for themselves
* Every morning, Kandra raises the flag to the top of the flagpole.
to rise – to move upward; to increase in amount or height
* Gas prices rose from $3.40 per gallon to $3.65 per gallon overnight.
to flood – for water to overflow out of the area it is usually located in and onto dry land
* The city experienced heavy rainstorms every day for over a week, filling the nearby river and causing it to flood.
What Insiders Know
Trends in Marriage
Traditionally, the typical life “path” (plan) for middle-class Americans has been to graduate from school, get a job, get married, and have children. While that is still the “trajectory” (direction; moving path) of some Americans, when it comes to marriage, things have changed.
A 2012 article in the Los Angeles Times “cites” (refers to; tells about) a “poll” (survey) that finds that fewer Americans are getting married. Saying “I do,” or getting married, has become less popular in the past few “decades” (periods of 10 years) in the United States, with nearly 20% fewer adult Americans married now than in 1960. In fact, it’s likely that within a few years, less than 50% of Americans will be married compared to 72% in 1960.
Those who are getting married, the report said, are getting married later. In the past 50 years, the age when men and women first marry has “risen” (gone up) six years. For men, the age is now 28.7 and for women, 26.5.
These days, other living arrangements have become more popular. Couples, people who are together romantically, may “cohabit” (live together) instead of getting married, and many children live in “single-parent homes” (with only a father or mother, not both).
The study “points out” (shows) that the U.S. is not alone in this “shift” (change) in rates of marriage. In most “post-industrial countries” (countries where “manufacturing” (making products) becomes less important and developing services, information, and research become more important), marriage has become less popular, “regardless of” (despite) good or bad economic times.