= 1351
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to English as a Second Language Podcast English Café number 46.
This is the English Café episode number 46. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On today's Café we're going to talk about business cards, what you put on a business card in the United States. We're also going to talk about nationalities, where people are from and the words we use to describe people from different countries. And as always, we'll answer a few questions. Now, let's get started.
Our first topic today is business cards. These are the cards that people who work for different companies or different organizations give each other, and it has their personal information on it. I thought I would talk a little bit about what goes on an American business card, what we call certain parts of the card.
The most important information is, of course, your name, who you are. Usually, on a business card below your name, underneath your name, there is your title. Your "title" is your position, what you do, what is your job in the company. If you have a professional degree - if you are, for example, a doctor - a medical doctor or a doctor of philosophy, a Ph.D., then you will put those letters after your name. So, if you are a medical doctor you would say, for example, "Sally Johnson, M.D.," with the M.D. standing for medical doctor. But for most people, you would just have your name and your title underneath.
Of course, other information you would put on a business card would be your telephone number. Usually, people put a telephone number and a fax number. Now it is very common to see a telephone number, a fax number, and a cell number, or cell phone number. The term “cell phone,” you may know, is the same as “mobile phone.” Sometimes on business cards they will abbreviate the telephone number title. So, for example, instead of writing out “fax," it made just say "F" and then the number. So, F 310-555-1212 would be an example of that use of an abbreviation. "C" is cell or cellular phone and "T" would be the telephone that you would talk on.
Another thing that you'll find on an American business card is the logo, the logo of the company or organization that you work for. A "logo" is the little sign or symbol that identifies that company. For ESL Podcast, for example, we have a logo. It says "ESL Pod," it's green, and on a business card, I would put that on my card if I had a business card for ESL Podcast, which I don't.
That leads us to the question of who gets a business card in an American company. Well, definitely the people who are at the top of the company, the executives would get a business card. People who are in sales, who sell things, would get a business card. The original purpose of a business card is to give your information to someone else so they can contact you or call you later, and sales people, of course, need to have that so that people can call them to buy products and services from the company. Other people will also get business cards in organizations. Mostly people who work in offices will get a business card. People who work in more physical jobs, such as manufacturing, making things, the people who are actually in the factory where they make products or they make things that company sells, they may not have business cards. Not everyone who works for an American company gets a business card. It depends on the company. Two other things that go on a business card now would be you or e-mail address and, for most companies, the website of that company.
The size of a business card is usually three and a half inches wide and two inches in terms of the height, or two inches tall. So, three and a half by two inches, that would be about 89 by 51 millimeters, so 89 millimeters across and 51 millimeters from the top to the bottom.
You can give someone a business card at the beginning of the meeting or wait until the end of the meeting. Either way is possible. We often use business cards - some people use business cards - to advertise their product or their service. This is especially common in cafés. Some cafés have a little board where you can put your business card, with a little "pin," the thing that you put into a soft board so it holds the card up. And, you'll often see people such as personal trainers, here in Los Angeles are very common. They will put their card on a local board. A “personal trainer” is the person who helps you at the gym, who helps you, tells you what to do when you are exercising. And in Los Angeles, this is a very common thing that people do. They hire a personal trainer. Other people will also put their cards on these boards to advertise their service.
One thing that you will see in many American restaurants is when you walk into the restaurant, usually at the “host stand,” that is the place where the person who says hello and takes you to your table, that person is called a “host” if it's a man, or a “hostess” if it's a woman - and on the host stand, the place or desk where they are, there's often a bowl. And, it's many times what we would call a “fish bowl,” and it's a small glass bowl that you would normally put little fish in, in water. But, in a restaurant this is usually a place where you can put your business card and every week or every month, the restaurant will have a "drawing," and that means that they pick one of the cards in the bowl and call that person and give them, usually, a free dinner or a free lunch. So, even if you aren't doing business, it's always good to have some business cards with you so you can win a free lunch. That's how I use most of my business cards, since no one really wants my business card to do business!
A second topic we're going to talk about today is nationalities, and nationalities is the word we used to describe where you are from, what country you are from. The word “nation" is the same as country, and “nationalities,” that word, comes from nation. There are a couple things about nationalities in English that are, I think, very confusing and difficult for many people. There is not one rule about how you call someone, how you form the word, or make the word for the nationality. Unfortunately, every country is a little different. It's also important to know the difference between a noun and an adjective when we talk about nationalities.
The noun would be the person from that country and the adjective would be how you would describe someone from that country. So for example, "I'm from the United States," the noun would be American, "I am an American," or "There are three Americans in the restaurant." You can also use the word American as an adjective, "He is an American painter.” “He is an American writer." So, it can be used as an adjective or as a noun. In many countries…for many countries, I should say, in English these are the same words. So, American can be a noun and American can be an adjective.
Another thing to think about when we talk about nationalities is whether it is one person, whether it is singular or plural, if it's a noun. So, for example, "there is one American, there are two Americans," putting an "s" sound at the end.
Well, unfortunately, different countries, as I said before, have different rules - we have different rules, or different ways, that we talk about nationalities. I'm going to talk about some of the most common ways that we form the word for the nationality. Probably the most common way is adding an "an" or an "ian" at the end of a word. So, someone from Canada is called a “Canadian,” we add an "ian." That's both the noun and the adjective. The plural would be Canadians, adding an "s." That pattern, or that format is probably the most common in English, adding an "an" or "ian" and an "s" for plural. Words like this, such as American or Canadian or Columbian, someone from Columbia, usually are the same for the adjective and the noun, that is, it's the same word. So, someone from Peru, for example the country of "Peru," would be called a Peruvian. There it's a little different, there's a "v" that we add, and two people from Peru would be called Peruvians, with an "s."
Now, that's the most common pattern, but it's…there are many other patterns that we also use. For example, someone from Japan is not called a Japanian; we call them Japanese, with an "ese" at the end. And, this is common for several different countries where we add "ese." Now, why "ese?" Well, there isn't necessarily a good reason. Unfortunately, it's just the way that these words have been formed in the past, probably for different reasons. China, for example, the word that we use for China is Chinese. The same would be true for Vietnam. Someone from Vietnam would be Vietnamese. There are also a few other countries, such as the Congo, in Africa, and the Sudan in Africa. Someone from the Congo would be Congolese. Someone from Sudan would be Sudanese. I believe from Nepal, also the country of "Nepal," we also use the "ese."
Now, with the "ese" the adjective and the noun are the same. However, you do not add an "s" at the end. So, you have one Japanese, two Japanese. You don't say Japaneses; you don't put an "s" at the end, that's true for all of the nationalities that end in "ese," Japan, China, Congo, Sudan, and so forth.
Another very common ending for nationalities is "ish." This is an ending that we use for some countries that have the word “land” in them, such as England or Scotland or Finland or Poland. Where you have that "and" at the end, we sometimes use the "ish" for the nationality. So, someone from England is English, someone from Poland is “Polish,” someone from Scotland is "Scottish," someone from Finland it is "Finnish." We also use "ish" for Denmark; someone from Denmark is "Danish." So, those are…that's another way of forming the word.
Now, for these examples, or the "ish" examples, the person, the noun is not always same as the adjective. So, for example, the adjective for someone from England is English, but a person from England, the noun, would be an Englishman or an Englishwoman. From Poland, it's a little different. Someone from Poland, as an adjective we would use Polish, but for the person we would use "Pole," and the plural would be "Poles." So, it's a little different with these endings.
There are many other endings also, for example, some countries we use a "ch" ending. Someone from France is French, for the adjective; for the noun it would be a Frenchman or a Frenchwomen. Someone from the Netherlands would be called "Dutch," and there are other different countries. Unfortunately, there are more than 190 countries, so I can't give you all of the countries. There are some countries where there is no real good way of trying to understand why we call them that particular name. Someone from Spain, for example, as an adjective we would say Spanish, but if it's a person, as a noun, we would say "Spaniard," and the plural would be Spaniards, with an "s."
A few other countries that are very different from these rules would be those from Switzerland, we would say they were "Swiss," that's both the singular and the plural of the noun, and it's also the adjective. Someone from Sweden would be called Swedish with an "ish" as an adjective, but the person is called a "Swede," with an "s" at the end for the plural. And, there are many other examples of this. Someone from Saudi Arabia is normally called a "Saudi." Someone from Thailand would be called a "Thai." Someone from Turkey would be called a "Turk." So, there are many others that we could do, we'd have to spent several hours going through all the countries, but those are some of the most common patterns, the most common ways that we use nationalities in English both as nouns, as adjectives, singular and plural.
Now, let's answer a few questions. Our first question is from "Anna" in Germany. Anna wants to know meaning of the expression, "dry-eyed." “Dry" hyphen "eyed" - what does it mean when we say someone is dry-eyed? Well, "eye," you know is what you look with, what you use to see. When we say someone is dry-eyed this is an expression that means that they are not emotional, that they aren't crying, that they are not affected by something. If you see something that's sad, for example, you might cry, you might have "tears," coming from your eyes. “Tears” is the word we use for the little drops of water that come out of your eye. Well, the opposite of that would be dry-eyed, and it's used to describe someone who is not affected emotionally by something, someone who is not influenced and doesn't have any strong emotional feelings about a certain topic.
"Andrea," from Italy, has a question about the expression "killer app." This is a term that you will see in the computer business, people who are talking about different types of software programs. An "app" is short for “application.” An application is a software program on your computer. Microsoft Word, for example, is an application. Internet Explorer is an application. Well, the short term we used for that is "app." The word “killer,” as an adjective here means great, excellent, wonderful, the best. “It's a killer app” - it's a great application; it's a wonderful program.
Interestingly enough, this word, killer, has another meaning. It can also describe something that is very difficult, something that is very hard to do. For example, "I took a test yesterday with my history professor. It was a killer." Using it as a noun, “it was a killer” means it was very difficult. "It almost killed me," it almost killed me because it was so difficult. So, it can have those two meanings. It can mean great as an adjective, but sometimes, informally, it can also means something that's very difficult. But in the expression killer app, it means it's great or excellent.
If you have a question about something you don't understand in English, email us at eslpod@eslpod.com and we'll try to answer your question here on the Café.
That's all we have time for today. From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. We'll see you next time on the English Café.
ESL Podcast English Café is written and produced by Dr. Jeff McQuillan. This podcast is copyright 2006, by the Center for Educational Development.
Glossary
title – the name that describes a person’s job or work
* His title sounds very important but I wonder what he really does in that company.
fax – a document sent electronically through a fax machine
* I need to get that contract today. Can you send it by fax?
logo – a symbol or picture that an organization uses to represent the organization or its products
* To promote the company, let’s put our logo on some t-shirts and hats.
pin – also called a “push pin”; a small piece of metal that is flat on one end, used to attach something to a surface, such as paper to a board
* Do you have enough pins to put up that big sign on the wall?
drawing – the selection of a winner in a game of chance, such as a lottery or a raffle
* This year, they plan to give away a trip to Hawaii at the drawing.
nation – a large group of people who have the same history, culture, language, or background
* The president said that, as a nation, we need to start caring about the environment.
dry-eyed – not emotional; not crying
* I don’t know how she can stay dry-eyed while watching that sad movie.
tears – small drops of liquid that comes out of your eyes when you cry
* I don’t want to see any tears. I’m going away, but I’ll be back.
killer app – a very good computer software program
* I just heard about this new killer app and I can’t wait to download it.
What Insiders Know
Nationalities in English
Afghanistan
noun: Afghan(s)
adjective: Afghan
Albania
noun: Albanian(s)
adjective: Albanian
Algeria
noun: Algerian(s)
adjective: Algerian
American Samoa
noun: American Samoan(s)
adjective: American Samoan
Andorra
noun: Andorran(s)
adjective: Andorran
Angola
noun: Angolan(s)
adjective: Angolan
Anguilla
noun: Anguillan(s)
adjective: Anguillan
Antigua and Barbuda
noun: Antiguan(s), Barbudan(s)
adjective: Antiguan, Barbudan
Argentina
noun: Argentine(s)
adjective: Argentine
Armenia
noun: Armenian(s)
adjective: Armenian
Aruba
noun: Aruban(s)
adjective: Aruban; Dutch
Australia
noun: Australian(s)
adjective: Australian
Austria
noun: Austrian(s)
adjective: Austrian
Azerbaijan
noun: Azerbaijani(s), Azeri(s)
adjective: Azerbaijani, Azeri
Bahamas, The
noun: Bahamian(s)
adjective: Bahamian
Bahrain
noun: Bahraini(s)
adjective: Bahraini
Bangladesh
noun: Bangladeshi(s)
adjective: Bangladeshi
Barbados
noun: Barbadian(s) or Bajan
adjective: Barbadian or Bajan
Belarus
noun: Belarusian(s)
adjective: Belarusian
Belgium
noun: Belgian(s)
adjective: Belgian
Belize
noun: Belizean(s)
adjective: Belizean
Benin
noun: Beninese (singular and plural)
adjective: Beninese
Bermuda
noun: Bermudian(s)
adjective: Bermudian
Bhutan
noun: Bhutanese (singular and plural)
adjective: Bhutanese
Bolivia
noun: Bolivian(s)
adjective: Bolivian
Bosnia and Herzegovina
noun: Bosnian(s), Herzegovinian(s)
adjective: Bosnian, Herzegovinian
Botswana
noun: Motswana (singular), Batswana (plural)
adjective: Motswana (singular), Batswana (plural)
Brazil
noun: Brazilian(s)
adjective: Brazilian
British Virgin Islands
noun: British Virgin Islander(s)
adjective: British Virgin Islander
Brunei
noun: Bruneian(s)
adjective: Bruneian
Bulgaria
noun: Bulgarian(s)
adjective: Bulgarian
Burkina Faso
noun: Burkinabe (singular and plural)
adjective: Burkinabe
Burma
noun: Burmese (singular and plural)
adjective: Burmese
Burundi
noun: Burundian(s)
adjective: Burundian
Cambodia
noun: Cambodian(s)
adjective: Cambodian
Cameroon
noun: Cameroonian(s)
adjective: Cameroonian
Canada
noun: Canadian(s)
adjective: Canadian
Cape Verde
noun: Cape Verdean(s)
adjective: Cape Verdean
Cayman Islands
noun: Caymanian(s)
adjective: Caymanian
Central African Republic
noun: Central African(s)
adjective: Central African
Chad
noun: Chadian(s)
adjective: Chadian
Chile
noun: Chilean(s)
adjective: Chilean
China
noun: Chinese (singular and plural)
adjective: Chinese
Christmas Island
noun: Christmas Islander(s)
adjective: Christmas Island
Cocos (Keeling) Islands
noun: Cocos Islander(s)
adjective: Cocos Islander
Colombia
noun: Colombian(s)
adjective: Colombian
Comoros
noun: Comoran(s)
adjective: Comoran
Congo, Democratic Republic of the
noun: Congolese (singular and plural)
adjective: Congolese or Congo
Congo, Republic of the
noun: Congolese (singular and plural)
adjective: Congolese or Congo
Cook Islands
noun: Cook Islander(s)
adjective: Cook Islander
Costa Rica
noun: Costa Rican(s)
adjective: Costa Rican
Cote d'Ivoire
noun: Ivoirian(s)
adjective: Ivoirian
Croatia
noun: Croat(s), Croatian(s)
adjective: Croatian
Cuba
noun: Cuban(s)
adjective: Cuban
Cyprus
noun: Cypriot(s)
adjective: Cypriot
Czech Republic
noun: Czech(s)
adjective: Czech
Denmark
noun: Dane(s)
adjective: Danish
Djibouti
noun: Djiboutian(s)
adjective: Djiboutian
Dominica
noun: Dominican(s)
adjective: Dominican
Dominican Republic
noun: Dominican(s)
adjective: Dominican
East Timor
noun: Timorese
adjective: Timorese
Ecuador
noun: Ecuadorian(s)
adjective: Ecuadorian
Egypt
noun: Egyptian(s)
adjective: Egyptian
El Salvador
noun: Salvadoran(s)
adjective: Salvadoran
Equatorial Guinea
noun: Equatorial Guinean(s) or Equatoguinean(s)
adjective: Equatorial Guinean or Equatoguinean
Eritrea
noun: Eritrean(s)
adjective: Eritrean
Estonia
noun: Estonian(s)
adjective: Estonian
Ethiopia
noun: Ethiopian(s)
adjective: Ethiopian
Falkland Islands (Islas Malvinas)
noun: Falkland Islander(s)
adjective: Falkland Island
Faroe Islands
noun: Faroese (singular and plural)
adjective: Faroese
Fiji
noun: Fijian(s)
adjective: Fijian
Finland
noun: Finn(s)
adjective: Finnish
France
noun: Frenchman(men), Frenchwoman(women)
adjective: French
French Guiana
noun: French Guianese (singular and plural)
adjective: French Guianese
French Polynesia
noun: French Polynesian(s)
adjective: French Polynesian
Gabon
noun: Gabonese (singular and plural)
adjective: Gabonese
Gambia, The
noun: Gambian(s)
adjective: Gambian
Gaza Strip
noun: NA
adjective: NA
Georgia
noun: Georgian(s)
adjective: Georgian
Germany
noun: German(s)
adjective: German
Ghana
noun: Ghanaian(s)
adjective: Ghanaian
Gibraltar
noun: Gibraltarian(s)
adjective: Gibraltar
Greece
noun: Greek(s)
adjective: Greek
Greenland
noun: Greenlander(s)
adjective: Greenlandic
Grenada
noun: Grenadian(s)
adjective: Grenadian
Guadeloupe
noun: Guadeloupian(s)
adjective: Guadeloupe
Guam
noun: Guamanian(s) (US citizens)
adjective: Guamanian
Guatemala
noun: Guatemalan(s)
adjective: Guatemalan
Guernsey
noun: Channel Islander(s)
adjective: Channel Islander
Guinea
noun: Guinean(s)
adjective: Guinean
Guinea-Bissau
noun: Guinean(s)
adjective: Guinean
Guyana
noun: Guyanese (singular and plural)
adjective: Guyanese
Haiti
noun: Haitian(s)
adjective: Haitian
Holy See (Vatican City)
noun: none
adjective: none
Honduras
noun: Honduran(s)
adjective: Honduran
Hong Kong
noun: Chinese/Hong Konger
adjective: Chinese/Hong Kong
Hungary
noun: Hungarian(s)
adjective: Hungarian
Iceland
noun: Icelander(s)
adjective: Icelandic
India
noun: Indian(s)
adjective: Indian
Indonesia
noun: Indonesian(s)
adjective: Indonesian
Iran
noun: Iranian(s)
adjective: Iranian
Iraq
noun: Iraqi(s)
adjective: Iraqi
Ireland
noun: Irishman(men), Irishwoman(women), Irish (collective plural)
adjective: Irish
Isle of Man
noun: Manxman (men), Manxwoman (women)
adjective: Manx
Israel
noun: Israeli(s)
adjective: Israeli
Italy
noun: Italian(s)
adjective: Italian
Jamaica
noun: Jamaican(s)
adjective: Jamaican
Japan
noun: Japanese (singular and plural)
adjective: Japanese
Jersey
noun: Channel Islander(s)
adjective: Channel Islander
Jordan
noun: Jordanian(s)
adjective: Jordanian
Kazakhstan
noun: Kazakhstani(s)
adjective: Kazakhstani
Kenya
noun: Kenyan(s)
adjective: Kenyan
Kiribati
noun: I-Kiribati (singular and plural)
adjective: I-Kiribati
Korea, North
noun: Korean(s)
adjective: Korean
Korea, South
noun: Korean(s)
adjective: Korean
Kuwait
noun: Kuwaiti(s)
adjective: Kuwaiti
Kyrgyzstan
noun: Kyrgyzstani(s)
adjective: Kyrgyzstani
Laos
noun: Lao(s) or Laotian(s)
adjective: Lao or Laotian
Latvia
noun: Latvian(s)
adjective: Latvian
Lebanon
noun: Lebanese (singular and plural)
adjective: Lebanese
Lesotho
noun: Mosotho (singular), Basotho (plural)
adjective: Basotho
Liberia
noun: Liberian(s)
adjective: Liberian
Libya
noun: Libyan(s)
adjective: Libyan
Liechtenstein
noun: Liechtensteiner(s)
adjective: Liechtenstein
Lithuania
noun: Lithuanian(s)
adjective: Lithuanian
Luxembourg
noun: Luxembourger(s)
adjective: Luxembourg
Macau
noun: Chinese
adjective: Chinese
Macedonia
noun: Macedonian(s)
adjective: Macedonian
Madagascar
noun: Malagasy (singular and plural)
adjective: Malagasy
Malawi
noun: Malawian(s)
adjective: Malawian
Malaysia
noun: Malaysian(s)
adjective: Malaysian
Maldives
noun: Maldivian(s)
adjective: Maldivian
Mali
noun: Malian(s)
adjective: Malian
Malta
noun: Maltese (singular and plural)
adjective: Maltese
Marshall Islands
noun: Marshallese (singular and plural)
adjective: Marshallese
Martinique
noun: Martiniquais (singular and plural)
adjective: Martiniquais
Mauritania
noun: Mauritanian(s)
adjective: Mauritanian
Mauritius
noun: Mauritian(s)
adjective: Mauritian
Mayotte
noun: Mahorais (singular and plural)
adjective: Mahoran
Mexico
noun: Mexican(s)
adjective: Mexican
Micronesia, Federated States of
noun: Micronesian(s)
adjective: Micronesian; Chuukese, Kosraen(s), Pohnpeian(s), Yapese
Moldova
noun: Moldovan(s)
adjective: Moldovan
Monaco
noun: Monegasque(s) or Monacan(s)
adjective: Monegasque or Monacan
Mongolia
noun: Mongolian(s)
adjective: Mongolian
Montserrat
noun: Montserratian(s)
adjective: Montserratian
Morocco
noun: Moroccan(s)
adjective: Moroccan
Mozambique
noun: Mozambican(s)
adjective: Mozambican
Namibia
noun: Namibian(s)
adjective: Namibian
Nauru
noun: Nauruan(s)
adjective: Nauruan
Nepal
noun: Nepalese (singular and plural)
adjective: Nepalese
Netherlands
noun: Dutchman(men), Dutchwoman(women)
adjective: Dutch
Netherlands Antilles
noun: Dutch Antillean(s)
adjective: Dutch Antillean
New Caledonia
noun: New Caledonian(s)
adjective: New Caledonian
New Zealand
noun: New Zealander(s)
adjective: New Zealand
Nicaragua
noun: Nicaraguan(s)
adjective: Nicaraguan
Niger
noun: Nigerien(s)
adjective: Nigerien
Nigeria
noun: Nigerian(s)
adjective: Nigerian
Niue
noun: Niuean(s)
adjective: Niuean
Norfolk Island
noun: Norfolk Islander(s)
adjective: Norfolk Islander(s)
Northern Mariana Islands
noun: NA (US citizens)
adjective: NA
Norway
noun: Norwegian(s)
adjective: Norwegian
Oman
noun: Omani(s)
adjective: Omani
Pakistan
noun: Pakistani(s)
adjective: Pakistani
Palau
noun: Palauan(s)
adjective: Palauan
Panama
noun: Panamanian(s)
adjective: Panamanian
Papua New Guinea
noun: Papua New Guinean(s)
adjective: Papua New Guinean
Paraguay
noun: Paraguayan(s)
adjective: Paraguayan
Peru
noun: Peruvian(s)
adjective: Peruvian
Philippines
noun: Filipino(s)
adjective: Philippine
Pitcairn Islands
noun: Pitcairn Islander(s)
adjective: Pitcairn Islander
Poland
noun: Pole(s)
adjective: Polish
Portugal
noun: Portuguese (singular and plural)
adjective: Portuguese
Puerto Rico
noun: Puerto Rican(s) (US citizens)
adjective: Puerto Rican
Qatar
noun: Qatari(s)
adjective: Qatari
Reunion
noun: Reunionese (singular and plural)
adjective: Reunionese
Romania
noun: Romanian(s)
adjective: Romanian
Russia
noun: Russian(s)
adjective: Russian
Rwanda
noun: Rwandan(s)
adjective: Rwandan
Saint Helena
noun: Saint Helenian(s)
adjective: Saint Helenian
note: referred to locally as "Saints"
Saint Kitts and Nevis
noun: Kittitian(s), Nevisian(s)
adjective: Kittitian, Nevisian
Saint Lucia
noun: Saint Lucian(s)
adjective: Saint Lucian
Saint Pierre and Miquelon
noun: Frenchman(men), Frenchwoman(women)
adjective: French
Saint Vincent and the Grenadines
noun: Saint Vincentian(s) or Vincentian(s)
adjective: Saint Vincentian or Vincentian
Samoa
noun: Samoan(s)
adjective: Samoan
San Marino
noun: Sammarinese (singular and plural)
adjective: Sammarinese
Sao Tome and Principe
noun: Sao Tomean(s)
adjective: Sao Tomean
Saudi Arabia
noun: Saudi(s)
adjective: Saudi or Saudi Arabian
Senegal
noun: Senegalese (singular and plural)
adjective: Senegalese
Seychelles
noun: Seychellois (singular and plural)
adjective: Seychellois
Sierra Leone
noun: Sierra Leonean(s)
adjective: Sierra Leonean
Singapore
noun: Singaporean(s)
adjective: Singapore
Slovakia
noun: Slovak(s)
adjective: Slovak
Slovenia
noun: Slovene(s)
adjective: Slovenian
Solomon Islands
noun: Solomon Islander(s)
adjective: Solomon Islander
Somalia
noun: Somali(s)
adjective: Somali
South Africa
noun: South African(s)
adjective: South African
Spain
noun: Spaniard(s)
adjective: Spanish
Sri Lanka
noun: Sri Lankan(s)
adjective: Sri Lankan
Sudan
noun: Sudanese (singular and plural)
adjective: Sudanese
Suriname
noun: Surinamer(s)
adjective: Surinamese
Swaziland
noun: Swazi(s)
adjective: Swazi
Sweden
noun: Swede(s)
adjective: Swedish
Switzerland
noun: Swiss (singular and plural)
adjective: Swiss
Syria
noun: Syrian(s)
adjective: Syrian
Taiwan
noun: Taiwan (singular and plural)
note: example - he or she is from Taiwan; they are from Taiwan
adjective: Taiwan
Tajikistan
noun: Tajikistani(s)
adjective: Tajikistani
Tanzania
noun: Tanzanian(s)
adjective: Tanzanian
Thailand
noun: Thai (singular and plural)
adjective: Thai
Togo
noun: Togolese (singular and plural)
adjective: Togolese
Tokelau
noun: Tokelauan(s)
adjective: Tokelauan
Tonga
noun: Tongan(s)
adjective: Tongan
Trinidad and Tobago
noun: Trinidadian(s), Tobagonian(s)
adjective: Trinidadian, Tobagonian
Tunisia
noun: Tunisian(s)
adjective: Tunisian
Turkey
noun: Turk(s)
adjective: Turkish
Turkmenistan
noun: Turkmen(s)
adjective: Turkmen
Turks and Caicos Islands
noun: none
adjective: none
Tuvalu
noun: Tuvaluan(s)
adjective: Tuvaluan
Uganda
noun: Ugandan(s)
adjective: Ugandan
Ukraine
noun: Ukrainian(s)
adjective: Ukrainian
United Arab Emirates
noun: Emirati(s)
adjective: Emirati
United Kingdom
noun: Briton(s), British (collective plural)
adjective: British
United States
noun: American(s)
adjective: American
Uruguay
noun: Uruguayan(s)
adjective: Uruguayan
Uzbekistan
noun: Uzbekistani
adjective: Uzbekistani
Vanuatu
noun: Ni-Vanuatu (singular and plural)
adjective: Ni-Vanuatu
Venezuela
noun: Venezuelan(s)
adjective: Venezuelan
Vietnam
noun: Vietnamese (singular and plural)
adjective: Vietnamese
Virgin Islands
noun: Virgin Islander(s) (US citizens)
adjective: Virgin Islander
Wallis and Futuna
noun: Wallisian(s), Futunan(s), or Wallis and Futuna Islanders
adjective: Wallisian, Futunan, or Wallis and Futuna Islander
West Bank
noun: NA
adjective: NA
Western Sahara
noun: Sahrawi(s), Sahraoui(s)
adjective: Sahrawi, Sahrawian, Sahraouian
Yemen
noun: Yemeni(s)
adjective: Yemeni
Zambia
noun: Zambian(s)
adjective: Zambian
Zimbabwe
noun: Zimbabwean(s)
adjective: Zimbabwean