= 1333
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 28.
This is English as a Second Language Podcast’s English Café episode 28. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On today’s Café, we’re going to talk about the Easter Bunny. We’ll also be discussing the topic of protests in America. And, as always, we’ll answer a few of your questions. Let’s get started!
Our first topic today is the “Easter Bunny.” “Easter” (Easter), always capitalized in English, is an important Christian holiday. Easter comes at the end of a Catholic practice called “Lent” (Lent), and is celebrated by all Christian groups, Catholic or not. Easter is the celebration of the resurrection of Jesus Christ, who Christians believe to be God and who founded the Christian religion. “Resurrection” means to come back from the dead. The majority of Americans are of the Christian tradition, so Easter is an important holiday in the United States, although it is not a legal or government holiday.
One symbol or one part of the celebration of Easter in the United States and some other countries is the “Easter Bunny.” Somewhat strangely, the Easter Bunny is very popular even with some people who are not very religious. The word “bunny” (bunny) is short for “bunny rabbit,” which is a small rabbit. A “rabbit” (rabbit) is a small, furry rodent, an animal with very big ears. If you know the cartoon character “Bugs Bunny,” then you know what a rabbit is. The use of a bunny as an Easter tradition is an old custom that goes back to when German immigrants arrived in what is now the state of Pennsylvania on the East Coast of the United States in the 1700s. These German immigrants brought the tradition of the Easter Bunny with them, and it become so popular that it is now sort of the universal symbol of Easter in the United States.
For children, the Easter Bunny is a little bit like Santa Claus is on Christmas. On Easter morning, children find candy and other sweets that the Easter Bunny has left them for being good. One very common Easter tradition is to have an “Easter egg hunt,” in which the adults hide Easter eggs for the children to find. “Easter eggs” are colored eggs that are another symbol of Easter. Sometimes these are real eggs – but chicken eggs, not rabbit eggs. Rabbits don’t lay eggs. People buy the eggs and then they “hard boil” them so they will not break easily by putting them in boiling or very hot water for several minutes. After the eggs cool, they paint the eggs with bright colors.
For the Easter egg hunt, the adults hide the Easter eggs all around the house and in the yard for the children to go and find. When I was growing up, we didn’t use real eggs for our Easter egg hunt. We used plastic eggs. Yes, that’s right.The plastic eggs would open and there would be candy inside. My parents would hide the eggs all around the house, and when we got up on Easter morning, my brothers and sisters and I – and I am the youngest of eleven children, so there were a lot of us – would all go looking for these eggs.
You might be able to see the Easter Bunny at the mall before Easter. A “mall” (mall) is a place where there are many different stores all in one area. Sometimes there will be a person in a Easter Bunny costume, special clothing that makes him or her look like a bunny, at the mall before Easter so children can have their pictures taken with the Easter Bunny. I never did that myself, but you will see that quite often these days. Another very popular Easter tradition is the chocolate Easter Bunny. Candy companies sell a lot of chocolate bunnies around Easter. Easter began as a religious holiday, but it has become more of a non-religious, or what we would call a “secular” holiday in the past 50 years in the U.S. Many families do celebrate both the original religious holiday of Easter, as well as the tradition of the Easter Bunny.
Our next topic is “protest.” A “protest” (protest) is when people get together in a big group, usually in some public place like near a government building or in a park, to give their opinion about something, usually to speak against something they object to. Another word for a protest is a “demonstration” (demonstration). Often, the protest will be against something that the government is doing. Our founding document in the United States, the “Constitution,” guarantees that people have what’s called the “right to assemble.” This means that people can get together in groups and talk to each other and do things together in public, including holding protests and demonstrations.
The word “protest” can also be a verb: “to protest.” “To protest” something means to be against something or to tell someone that you are against something. Often people will protest some particular action by the government. A few years ago there were some bills in Congress, about immigration that people were protesting. A “bill” (bill) is a proposal, an idea that someone has. A bill is not a law yet, but if enough representatives from different parts of the country – what we call “Congress” – vote for the bill and the president signs the bill, then it becomes a law.
The bills that people were protesting about had to do with illegal immigration. “To immigrate” (immigrate) is to come and live in a country. There’s also a verb “to emigrate,” with an “e” (emigrate), that means to leave a country. “Illegal (illegal) immigration” is when people enter a country without getting the proper permission, like a visa. There are a lot of people living in the United States illegally, meaning without proper documentation, probably at least 12 million people.
Some people say we should just let the people living here illegally become American citizens because they work here. Other people disagree and say that for our security we need to not let so many people into the country, and we should make the people who are already living here illegally leave the country. It’s a very sensitive topic, and people are very divided, meaning there are very strong opinions about it on both sides.
The recent protests were large but “non-violent,” meaning they were peaceful. People weren’t throwing things or causing problems. Sometimes during a protest people may get overly excited, and sometimes there can be violence. When this happens, the police usually come wearing special uniforms called “riot gear.” A “riot” (riot) is a big group of people who are very angry and are being violent. The word “gear” (gear) means specialized clothing – clothing for a very specific purpose. You can have hockey gear or bicycling gear or, in this case, riot gear. Riot gear is special clothing that protects the police officers from getting hurt by the crowd when there is a big demonstration.
But thankfully, there was no violence in the recent protests here in the United States. Immigration will continue to be a very important topic, especially for states like California and Texas and New York, where there are a lot of immigrants from other parts of the world. It is always good for the people to be concerned with the actions of their government and to make their voices be heard – to let the leaders in Washington, D.C. and elsewhere know what they think, about this topic and others.
Now let’s answer some of the questions you have sent to us.
Our first question today comes from Patricia (Patricia) in France. Patricia wants to know about the different uses of a very common word in English: “actually.” “Actually” (actually) is used as an adverb, and it is used in a couple of different and very common ways. One way we use “actually” is to mean the same as “really.” You might say to someone, “They are actually swimming in the river,” meaning they’re really swimming in the river. Usually we use it in this way when describing a situation that someone might not believe, to emphasize that it is true. For example, “I actually got to work on time today.”
Another way we use “actually” is to give an unexpected opinion or to say something that someone doesn’t expect. For example, “Everyone thinks I’m going to the dance. Actually, I’m going to stay home.” You are saying that you’re going to do something different from what everyone thought you were going to do. “People say that Los Angeles is very hot in the summertime. Actually, it depends on where you are in the city.” “Actually” is basically the same as “in fact.” We can use either to express a contradictory idea, an idea that is different or unexpected.
Our next question comes from Mohammed (Mohammed) in Egypt. Mohammed wants to know the difference between the words “zero” and “nil.” That’s a good question. The word “zero” (zero) is used to indicate the number zero, and we sometimes use the word “zero” in expressions like, “You have zero chance of getting a date with that beautiful woman.” “You have zero chance” means you have no chance at all.
There’s also the word “nil” (nil), which also means zero, but this word is not quite as common in American English. It’s used mainly in certain expressions such as, “His chances are nil,” meaning his chances are nonexistent. But we would never say, “I have nil chance of going.” The word “nil” is probably more commonly used in English spoken in other places around the world, but here in the United States, “zero” is a safer word to use, a much more common word to use.
Another question comes from Younes (Younes) in Germany. Younes would like to know what the expression “He is on his last legs” means. “He is on his last (last) legs (legs).” Your legs are the parts of your body that you run and walk with. When we say a person is on his or her last legs, we mean that person is very sick and weak and is probably going to die soon.
You can also say that a machine or a thing is “on its last legs” to mean something similar. “My television is on its last legs” means my television is old and is going to stop working soon. That’s actually a real example, because I have a very old television that I will eventually need to replace – I will need to get a new one.
Finally, we have a question from Diones (Diones) in Brazil. Diones would like to know the difference between the word “despite” (despite) and the phrase “in spite of.” Both “despite” and “in spite of” are prepositions used to express a determination to do something regardless of the difficulties involved. “I am going outside despite the rain” means that even though it is raining and not the best weather for going outside, I am going outside anyway. I’m saying that it doesn’t matter that it’s raining, I’m still going outside. “I’m going outside despite the rain” and “I’m going outside in spite of the rain” mean exactly the same thing.
A similar idea can be expressed with the conjunction “even though.” “Even (even) though (though)” means the same as “despite” and “in spite of,” but it is used differently in a sentence because it is what we call a “conjunction.” A “conjunction” (conjunction) is used to join two parts of a sentence, often two clauses that each have a subject and a verb. So, for example, you could say, “I am going outside even though it is raining.” Notice that each half of the sentence joined by the conjunction has its own subject and verb: “I am going outside” and “it is raining.” I am going outside even though it is raining.
But in the example with the preposition “despite,” there is only one subject and verb: “I am going outside despite the rain.” There is no verb in “despite the rain.” We would never say, “Despite it is raining” or “In spite of it is raining.” And we also would not say, “I am going outside, even though the rain.” Both of those examples are incorrect. “Even though” is always followed by a complete sentence – “I am going outside even though it is raining” – and “despite” and “in spite of” are not: “I am going outside despite the rain.” “I am going outside in spite of the rain.” It’s a bit complicated, but I hope this helps.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. We can’t answer every question, but we will certainly try to answer as many as we can.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
Easter – a Christian holiday that celebrates the resurrection (returning to life after having died) of Jesus Christ, celebrated on the first Sunday after the first full moon of the spring season each year
* When she was a child, Kelsey got a basket filled with chocolate and other sweets every year to celebrate Easter.
Easter Bunny – a rabbit (a small furry animal with a short fluffy tail, whiskers, and long ears) used as a symbol to represent the Easter holiday; a mythical or fictional rabbit that brings eggs to children on Easter
* Li believed that the Easter Bunny visited his house until he was eight years old.
universal symbol – well-known representation; an object that is known by almost everyone as something that represents another object, event, or idea
* Doves are a universal symbol of peace.
Easter egg hunt – a game played by children on Easter where children search for plastic eggs with toys or candy inside, or eggs that are boiled in water until they are cooked, brightly dyed or colored, and hidden around a house or yard
* Every year, the church hid plastic eggs around the garden and held an Easter egg hunt for children under the age of 10.
mall – a large building in which there are many separate stores
* Roseanne didn’t know which store would carry the type of coat she wanted to buy, so she decided to go to the mall and look around.
secular – non-religious; dealing with things that are not holy, sacred, or religious
* Henry is not a Christian, but he still celebrates the secular parts of Christmas.
protest – an action meant to show or express disapproval; the act of publicly stating one's disapproval or dislike of something, often done with a large group of people
* When the school made a rule stating that students must wear uniforms, several students arrived in normal clothes as a protest of the rule.
demonstration – something done to prove or show a fact, feeling, or belief; a sign or action done to show that one or more people do not approve or like something that a government or organization is doing
* An anti-war group held a demonstration outside of the capital building.
Constitution – the founding document of the United States, describing the way that government will be organized and run as well as the rights of people
* Jacqueline is an expert on the Constitution and knows how to interpret it.
right to assemble – the ability or privilege to gather or meet together with a group of people to discuss ideas or take actions
* We have the right to assemble and voice our disagreement with the president.
bill – a proposal or idea for a law that the U.S. Congress votes on to decide whether it will become a law
* Congress will be voting soon on a new bill that, if passed, would cut taxes.
to emigrate – to leave one country, region of a country, or location to move to another
* Our emigrated from France to the United States roughly 75 years ago.
illegal immigration – the act of coming into a country without getting permission or following the rules that country has about entry
* Illegal immigration is a very controversial topic because people disagree about how illegal immigrants should be treated.
riot gear – protective clothing, including helmets worn over the head and thick vests worn over the chest that can stop bullets, usually worn by police when they enter large crowds that may try to cause physical harm
* When an angry mob broke out after the election, the police had to show up in riot gear to calm the violent crowd.
actually – really; used to emphasize or give attention to something that is unexpected or surprising
* Gena thought that Fyodor had no interest in baseball, but actually, he has always been a huge fan.
zero – “0,” a number representing none; no or non-existent
* Maye knew that there was zero chance of her passing the exam.
nil – none; nothing; of no value
* The painting looked like it could be expensive, but it was worth nil.
on (one's) last legs – very sick or very ill and probably going to die; likely to stop working soon
* Sidney had his old toaster for 15 years, but he could tell that it was on its last legs and could stop working at any moment.
in spite of – despite; even though; a phrase used to state that an action is being done even though something else has happened that would make that action unexpected
* Natasha decided to go to class in spite of the fact that she had a terrible headache.
What Insiders Know
Tax Return Fraud
Americans “file” (send in) their tax returns every spring to the “federal” (national) government. Everyone who works has to pay a certain amount of money in income taxes to the government, but if you don’t make a lot of money, the government gives you that money back in a “tax refund” the following year.
To get your tax refund check, you have to file your tax return sometime between January 1st and April 15th. The government then normally sends you a check, but if you are very poor and don’t have a bank account, they will send you a debit card with the money on the card. A “debit card” is like a credit card, except that it has a certain amount of money on it already.
In order to file a tax return, you have to “put down” (write down) your name, your “social security number” (a national identification number), the amount of money you “earned” (were paid at your job), and the amount of taxes you paid. These returns are now filed mostly electronically, either by using your own computer or going to a company that will file them for you. However, it is “possible” and not difficult to use someone else’s identity (including their name, address, social security number, etc.) to file a return, and if you file it before the real person files his or her return, the government may not realize what is happening and send you someone else’s refund!
This problem has become more common as more and more people have their identities stolen on the Internet or other places. In 2010, it is estimated that there were more than two million false returns, costing the U.S. government more than five billion dollars.