= 1321
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 16.
This is English as a Second Language Podcast’s English Café episode 16. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development right here in beautiful Los Angeles, California.
Go to our website at ESLPod.com. On this Café, we’re going to talk about two important things that happen in the month of April. The first is April Fools’ Day, and the second is Tax Day. And, as always, we’ll answer a few of your questions. Let’s get started.
Our first topic today is April Fool’s Day. April Fool’s Day is the first day in April, or April first. Why do we call it “April Fool’s Day,” and what exactly happens? Let’s begin by explaining the meaning of the word “fool” (fool). A fool is a person who isn’t very smart, who isn’t very intelligent. A fool is a stupid person.
It’s certainly an insult to call someone a fool. You don’t want to tell someone he or she is a fool unless you want to insult that person. You certainly do not want to tell your boss that he or she is a fool, even if he or she is a fool. “Don’t be a fool” is an expression that means “Don’t be stupid.”
April Fool’s Day is actually a day that is observed in many different countries. It’s basically a day when people play tricks on each other. “To play a trick” (trick) on someone is to do something to make the person believe something that isn’t true and something that would make other people laugh if the person thought it were true.
Sometimes these are what are called “practical jokes.” A “practical (practical) joke” is when you do something physical, such as put some glue on someone’s pen so that it doesn’t work anymore. That would be a practical joke, and a way of playing a trick on someone.
Even though many countries celebrate April Fool’s Day, it’s not exactly clear where this custom or this tradition started. Some people think it came from France in 1582. What happened in 1582? Well, in France and in the rest of Europe, the Gregorian calendar was adopted, and it changed the New Year from March 25th to January first. A “calendar” (calendar) is a schedule of days, weeks, or months of the year.
When the change was made from the old, what was called the “Julian calendar,” to the new Gregorian calendar, dates changed, and so all of the calendars had to be adjusted. But not everyone wanted to change the calendar. In fact, they continued to celebrate the new year the week of what used to be April first, and these people were made fun of and called “fools.” It’s not clear exactly if this story is true or not, but it’s one guess.
April Fool’s is known for practical jokes and for telling people things that aren’t true. So, on April Fool’s Day, you might go up to someone and say, “Hey, I just won a million dollars.” You tell them something that you think the person will believe, and the person says, “Really? You won a million dollars? That’s fantastic!” And the other person says, “April Fool’s!” meaning you’re indicating that you had just lied to them, that you had told them something that wasn’t true in order to trick them, in order to fool them. The verb “to fool” means to deceive someone, to make someone believe something that isn’t true.
This custom or tradition of making people believe things that are not true is very much related to what we would call a “hoax” (hoax). A hoax is when you make people believe something that isn’t true. For example, you could take a photograph, a picture, and change it on your computer to make it look like there are aliens from another planet visiting your house. “Aliens” (aliens) are beings, living things from other planets.
Some people say cats are actually aliens. They’re not animals that are originally from Earth. I think this is true. Anyway, a hoax is when you get people to believe things that aren’t true, and that’s something that people try to do on April Fool’s Day.
Now, April is famous in the United States for other reasons, especially the middle of April – April 15th. April 15th is what we sometimes call “Tax Day,” and as you might guess, it’s the day that Americans have to send in their tax information to the government – their income tax information, typically. “Income” (income) is the money that you get from working, that someone pays you to work.
The word “taxes” refers to money that you have to give the government because the government needs money to run, to operate. Well, in the United States, you have to send in what are called your “income tax forms,” or papers, to the government by the 15th of April. Now, you can send it in any time between January first and April 15th, but April 15th is the last day that you can send it in.
Many people nowadays don’t send anything paper to the government. Everything is done electronically. Well, not everything, but for many people they file their income tax returns electronically. “To file” (file) means to submit, or to send something in. We call the information that you give the government your “tax returns” (returns). “Returns,” as a noun here, refers to the information that has your financial data or your financial information on it. The government wants to know how much money you paid and whether you still need to pay the government more in taxes.
Now, the United States did not always have a national income tax. In fact, the first income tax in the U.S. wasn’t until the early part of the U.S. Civil War in 1861, and that tax ended about 11, 12 years later in 1872. The reason that the U.S. had an income tax during this time period was to pay for the very expensive Civil War that the United States fought in in the early part of the 1860s. Now, this was a temporary income tax and, as I mentioned, it stopped in 1872.
However, by the early part of the twentieth century, the federal or national government in the United States decided it needed more money, and so it passed a law establishing a permanent income tax. This was in 1913. In fact, it was the 16th change, or “amendment” to the U.S. Constitution.
The Constitution is our most important legal document. The main part of the Constitution was written back at the beginning of the U.S. as a country in 1789. However, there are changes that have needed to be made to the Constitution to keep it up-to-date, if you will. And so, we have added different things to the Constitution – 27 times as of the year of this recording.
This was the 16th change, or amendment, to the Constitution. The word “amendment” comes from the verb “to amend” (amend), which means to make changes, especially to a written document or a legal document. The 16th Amendment gave the federal government the right to collect income taxes.
The amendment did not say how much the government could tax the American people. It didn’t say what percentage the tax was. I believe one person wanted to put in a maximum percentage of 10 percent. People were against this idea because they thought it was ridiculous. It was absurd to think that the U.S. would actually have an income tax rate of 10 percent. They didn’t want to suggest that the government could charge as much as 10 percent in taxes on income in the U.S.
Well, as it turns out – as history has “unfolded,” we would say – 10 percent is now the minimum, or the least amount of federal tax, income tax, that many people have to pay. The maximum amount in income tax can be close nowadays to 40 percent. Everyone who has a job, who makes money in the United States above a certain amount, has to pay taxes.
However, many people are poor and don’t have to pay taxes, or they don’t make enough money to pay taxes. It’s not exactly that they’re poor in all cases, but you have to have a certain minimum amount of money that you make, a minimum amount of income, in order to have to pay the income tax.
It wasn’t just the federal government, however, that decided that it was going to have an income tax in the early part of the twentieth century. Many individual states decided to have their own income tax. There are still some states that don’t have income taxes – states like Texas and Alaska and a few others – but there are very few states now that do not have income tax that needs to be paid.
Here in California we certainly have income tax. In fact, California has one of the highest income tax “rates,” or percentages, that you have to pay. I believe currently it’s around 13 percent in terms of being the top or maximum percentage that you may be asked to pay.
In order to pay your income tax, the usual procedure is to have the money deducted from your paycheck. Your “paycheck” (paycheck) is the money that you get from the company or the organization that you work for. This is the money that they give you for working. So, let’s say that you work at a job that pays you $10 an hour. If you worked 40 hours a week, you would expect to get $400. However, you don’t get $400 because the company gives part of that money to the government as part of your income tax.
However, because people sometimes don’t know exactly how much money they’re going to make each year, sometimes you have to pay more tax than what you paid during the year, and this is the purpose of the income tax return. You file your income taxes on April 15th, but you file it for the previous year. All during the year you are paying the government a little bit of tax with every paycheck. At the end of the year, or really at the beginning of the next year, you write down all the money you paid, and then you determine if you paid enough tax.
If you didn’t pay the government the proper percentage of your income, then you have to send them another check. You have to pay your taxes, and those taxes have to be paid by – that’s right – April 15th. Sometimes you pay too much in taxes, and when that happens you get what’s called a “tax refund” (refund).
A refund is money that you get back from, in this case, the government, because you paid too much. What happened is that you or the company deducted too much money from your paychecks each week. “To deduct” (deduct) means to take out of. Now, because people don’t like giving the government their money, there are many people who wait until the very last day in order to send in their tax return.
Now, technically, you have to put your tax return into the mail, into the U.S. mail system, no later than April 15th, so you need to go to the post office by April 15th and make sure that your letter or your package with your income tax information is postmarked by that day. “To postmark” (postmark) means basically that the post office indicates that this is the day that this person mailed his letter or, in this case, his probably envelope with the income tax return in it.
Many people, as I say, “wait until the last minute,” we would say. They wait until the last possible day to mail in their taxes. In fact, sometimes post offices in some cities stay open until midnight because people are coming in so late to pay their taxes – or more correctly, to send their tax returns in to the government. This has become less common now that we have the Internet and people can just send or submit their tax returns electronically from their computer.
Unfortunately, the tax system in United States is very complicated and many people are not able to do their own tax returns. They have to go to someone to help them prepare the return. One common person that would be asked to do this is an accountant. An “accountant” (accountant) is a person whose job it is to take care of a company’s or a person’s money. One thing that many accountants do is prepare taxes. In fact, there are some accountants that do only that. They are “tax accountants.”
One of the most famous Americans, Benjamin Franklin, one of a group of what we call our “Founding Fathers,” had a very famous quote about taxes. He said, “In this world, nothing is certain but death and taxes.” The phrase “nothing is certain” means nothing is for sure, nothing is definitely going to happen “except” – but – “death and taxes.” So, you can’t avoid dying – everyone is going to die – and in most places, you can’t avoid paying taxes. Everyone has to pay their taxes.
So, just pay your taxes by April 15th if you live in the U.S. By the way, if April 15th is on a weekend, on a Saturday or Sunday, then it’s the next following Monday. So, if April 15th were on Sunday, then you would have until April 16th to file your taxes.
Now let’s answer some of the questions you have sent to us.
Our first question comes up from Younes (Younes) in Morocco. The question has to do with the difference between the verb “to have” and the verb “to be” with a past participle. Now, “to have” and “to be” are two of the most common verbs in English, if not the two most common verbs in English, so we’re not going to explain all the differences between those two verbs. It would take us many hours to do so. We’re just going to focus on the use of these two verbs with what’s called a “past participle.”
For example, in the expressions “was thrown,” “was broken,” “was done” – the words “thrown,” “broken,” and “done” are past participles. You can also say “has broken” or “has thrown” or “has done.” The question is what’s the difference between these two uses of the past participle with the verbs “to have” and “to be”? The most common difference between these is that one is in what we would call the “active voice” and the other is in what we would call the “passive (passive) voice.”
If something is in the active voice, the subject of the sentence is the person or the thing that is doing the action. “I throw the ball” – “I” is the subject, “throw” is the verb, the “ball” is what we call the “object.” “I throw” is active. The verb is active, what we would call the “active voice” (voice). If something has happened in the past, I might say, “I have thrown the ball.” It’s still in the active voice, but now it is something that we’re talking about from the past, not something that is going on right now or in the future.
The “passive voice” is when something is done by someone else to you or to another person, and the subject of the sentence isn’t the thing or person who is doing the action. This is easier to explain with a couple of examples. “The ball was thrown by John.” Now, the ball didn’t throw anything. Even though the ball is the subject of the sentence, the sentence itself is in the passive voice. Who threw the actual ball? Well, that would be John – “The ball was thrown by John.” So in that case, using the verb “to be” with the past participle indicates the passive voice.
If you use the verb “to have” with the past participle, such as “has thrown” or “have thrown,” then the sentence is in the active voice, which means that the subject of the sentence is the thing or person who is doing the action. So, you could never say, “The ball has thrown by John.” You would have to say, “The ball was thrown by John” because it’s a passive sentence and the person doing the action is not the subject.
Our next question comes from Anthony (Anthony) over in Hong Kong. Anthony has a question about the use of a number and the expression “straight time.” For example, “This is the third straight time that I have seen this movie,” or “This is the 15th straight time that the government has raised our taxes.”
The word “straight” (straight) here means in a row, one after another. The word that comes before the word “straight” is what we call an “ordinal number.” An “ordinal (ordinal) number” is a number that tells us where something is – what position something is in or, if you will, what order it is in.
In English, these numbers often end with the letters “th,” although sometimes they end in something different. “First,” “second,” and “third” have different endings than the rest of the numbers – “fourth,” “fifth,” “sixth,” “seventh,” “eighth,” “ninth,” and “tenth.” So, you have “twentieth,” but you have “twenty-first,” “twenty-second,” “twenty-third.” All of these are examples of ordinal numbers. They tell you what order something is coming in.
If you say this is the third straight time that your girlfriend has failed to call you back, you should probably get the message and move onto a new girlfriend. What it means is that this is the third time in a row, one after the other, that your girlfriend hasn’t called you back. Or if you say, “This is the third straight time I’ve seen this movie,” that means “I’ve seen this movie three times in a row,” one after the other.
You might be asking yourself, “Why would you watch a movie three times in a row?” and the answer is, of course, that your girlfriend hasn’t called you back.
I can’t be your girlfriend, but I can answer your questions. You can email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
April Fools' Day – April 1st; a day on which people try to make others look silly or stupid by tricking or causing them to believe that something is true when it is not, all done for fun
* On April Fools’ Day, Eli tricked his sister into thinking that her cell phone had been stolen when it was actually in his room.
fool – someone who is stupid or unintelligent; someone who behaves or acts in a way that seems stupid, dumb, or unwise
* When Aja started dating her ex-boyfriend again after he had cheated on her, her friends thought she was a fool.
to play a trick – to deceive someone or to be dishonest with someone for one's amusement or entertainment
* Marcus played a trick on his best friend by making him think that a cute girl had sent him a note asking for a date.
practical joke – the act of causing someone to do something that makes him or her appear foolish for the purpose of entertaining oneself
* Sophia’s roommate played a practical joke on her by locking her out of the apartment without a coat in the middle of winter.
hoax – something that someone claims to be true when it is actually false
* The news story about the political scandal seemed like it could be true, but it was actually a hoax.
income tax – a portion or amount of money that one earns from working but must pay to the government so that the government can pay for services
* About 25% of Colin’s earning went to pay his income tax.
federal – of the national government; relating to or dealing with a central government that controls the actions of smaller states or regions
* Jennette violated federal law when she stole her neighbor’s mail.
percentage – a portion or part of something that exists for every 100 instances of that something
* Arthur donated a generous percentage of what he earned to various charities.
paycheck – money one earns from working at a job; money that a company or employer gives to someone for doing work for that company or employer
* Dr. Hampton gave her office assistant a paycheck every other week.
to fill out – to complete; to provide or write in information on a document that has empty spaces intended for that information
* When Richard went to the dentist’s office, he fill out several forms.
tax refund – tax rebate; money that the government returns to someone who paid the government too much money throughout the year
* Inez overpaid her taxes during the year and got a tax refund of $184 after she filed her taxes.
to deduct – to take out of; to take away from; to remove from a larger part
* Bradley broke several dishes at work, so the cost of the dishes was deducted from his pay.
to postmark – to have a letter, package, or other piece of mail stamped or marked by the post office, showing the date on which that mail was received by the post office
* The application has to be postmarked by May 15th, or it will be considered late.
to wait until the last minute – to wait until the final day or period of time one can perform an action
* Even though she had three weeks to work on the assignment, Hildred waited until the last minute to finish it.
tax return – an official form sent to the government every year stating how much money one earned and how much one should pay in taxes
* There was a mistake on Wilson’s tax return, so the IRS sent him a letter to inform him that a correction was made.
accountant – someone whose job is to keep and organize financial accounts; a person who keeps track of and organizes money for other people or businesses
* Jutta hired an accountant to review her company’s financial records.
(number) straight time – getting the same result a certain of times in a row
* Sandy tried making pancakes, but for the third straight time, he burned them.
ordinal number – a number that explains the order or pattern something is in; a number that defines a position or place within a series or set
* The teacher asked Kamie to give her the first three ordinal numbers, so Kamie responded, “first, second, and third.”
in a row – consecutively; one after another, without anything else in between
* Nye is exhausted because hasn’t slept for three nights in a row.
What Insiders Know
Summer Reading
Summer is a time when “school is out” (there are no classes) and people take vacations. For many, vacation means more time for relaxing reading, and the term summertime reading usually implies “light” (easy), enjoyable books. Summertime reading is the kind of reading you can take to the “beach” (sandy area next to a lake or ocean), one that perhaps does not need a great deal of “concentration” (focus; mental energy) to understand and enjoy.
Philosopher and author Peter Kreeft once said that there are four kinds of books in the world. The first kind are books that are “clear” (understandable; comprehensible) the first time you read them, and clear each time you read them again. We might call these “easy” books, although that doesn’t mean they are not good books. The second kind of books are books that are clear the first time you read them, but upon “second reading” (the second time you read them), you start to notice problems in the book – errors or poor writing – and the book becomes less clear. The third kind of book is unclear on the first reading, unclear on the second reading, and unclear on the third reading! These are simply bad books, where the author doesn’t do a very good job of explaining his or her ideas or telling the story.
Finally, there are books that are unclear upon first reading, but then become clearer on the second reading, and even clearer on the third. In fact, this fourth kind of book gets clearer and clearer each time you read it, with more and more meaning found on “each pass” (each reading of the book). Some people would say that this is the sort of book we call a “classic” book (great book).
We can probably all think of books in each of these categories. Our summertime reading may be any of these four types, but most probably would choose a book in the first category and not the fourth, unless we are feeling very “ambitious” (feeling of wanting to achieve something)!