= 1263
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,263 – Bragging about Success with Men.
This is English as a Second Language Podcast episode 1,263. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESLPod Special Courses in business, daily, and cultural English.
This episode is a dialogue between Evan and Chantelle about a woman who is successful in getting men to be romantically interested in her. Let’s get started.
[start of dialogue]
Evan: Who are going out with tonight?
Chantelle: I’m not sure. I might go to dinner with Steve or Eduardo or Jim.
Evan: Dinner is in a couple of hours. You mean they’re waiting around for your call?
Chantelle: They’d better be. They’re the ones vying for my attention, so they’d better be at my beck and call.
Evan: How many guys are you juggling?
Chantelle: Not that many, only the ones who are really devoted admirers. I try to throw them a bone now and then.
Evan: By keeping them waiting.
Chantelle: It’s good to keep them on their toes.
Evan: And by making them jealous of each other? I saw how angry Jack got when he saw you flirting with Kwan and later getting cozy with Mike.
Chantelle: Jack can’t stay angry with me. We’ll kiss and make up.
Evan: Don’t you ever get tired of toying with so many men?
Chantelle: I’m not toying with them. It’s not my fault that men find me irresistible.
Evan: Right, just like moths to a flame. No wonder so many get burned!
[end of dialogue]
This episode is all about bragging. “To brag” (brag) means to talk about how good you are at something, to tell other people how great you are. In this episode, Chantelle is bragging about her success with men.
Evan begins our dialogue by asking her, “Who are you going out with tonight?” “To go out with” someone here means to go to some social event such as a dinner or a movie or some party. “I’m going out with my friends” means I’m going to have a good time tonight doing something with my friends. “To go out with” can also mean to be in a romantic relationship with someone. “I’m going out with a girl I met at work last week.” Here, however, it just means to be with someone to have a good time.
Chantelle isn’t sure who she’s going out with tonight. She says, “I might go to dinner with Steve or Eduardo or Jim.” Evan says, “Dinner is in a couple of hours,” meaning we are very close to the time when you would be going to dinner. “You mean they’re waiting around for your call?” “To wait (wait) around” is a two-word phrasal verb meaning to wait for something to happen, usually because you don’t have any other plans. “I’m waiting around for my friend to call.” I’m sitting here doing nothing else, really, because I don’t have anything important to do other than wait for him to call me.
These men that Chantelle is interested in are waiting around for her to call. Chantelle says, “They’d better be,” meaning she expects them to be waiting around for her call. She continues, “They’re the ones vying for my attention, so they’d better be at my beck and call.” “To vie (vie) for someone’s attention” means to try to get someone to pay attention to you, to try to get someone to notice you. Chantelle says that these three men are “vying for her attention.” They want her to notice them.
Therefore, she says, “they’d better be at my beck (beck) and call.” “To be at someone’s beck and call” means to be ready and willing to do whatever someone asks you to do or wants you to do. Rich people often have servants who are at their “beck and call.” The servants work for them and do whatever they tell them to do. Chantelle thinks these men should be at her beck and call, sort of like servants, I guess.
Evan says, “How many guys are you juggling?” “To juggle” (juggle) here means to try to do many different things at the same time. Another meaning of “to juggle” is to take objects such as small balls and throw them up in the air and keep them up in the air at the same time. Some people are able to juggle three, four, or five tennis balls at the same time, keeping them all up in the air. Here the verb is used, however, to mean to be able to do a lot of different things at the same time.
In Chantelle’s case, she’s talking about the number of different men who are interested in her and to whom she is thinking of paying attention. Chantelle says, “Not that many, only the ones who are really devoted admirers.” If someone is “devoted” (devoted) to something or to someone, he is interested in that thing or person and will spend a lot of time on it – or her, in this case. An “admirer” (admirer) is someone who likes another person, in this case in a romantic way. So Chantelle’s devoted admirers are men who are very interested in having a romantic relationship with her.
Chantelle continues, “I try to throw them a bone now and then.” The expression “to throw someone a bone” (bone) means to give someone a small amount of what he or she wants or is asking for, but not what they completely want or not everything that they want. The expression relates to what you would do for a dog for example. You may be eating a nice juicy steak and the dog wants the steak. Well, you don’t give the dog the steak, the meat, but you might throw the dog the bone from the steak. It’s a small amount of what the dog likes.
“To throw someone a bone,” then, means to give him a little of what he wants so that he continues to be interested, but not everything he wants. Chantelle says she likes “to keep” these men “on their toes.” “To keep someone on their toes” (toes) means to make someone pay attention, to keep someone ready for something that might happen, something important that might happen. “To keep someone on his toes” means to keep him focused, to keep him concentrated. Chantelle wants the men to be kept on their toes, meaning they have to be ready to do what she says she wants them to do.
Evan says, “And by making them jealous of each other?” “To be jealous” (jealous) means to want what another person has. In this case, “to be jealous” refers to the men each wanting what he thinks the other has, the attention of Chantelle. Evan says, “I saw how angry Jack got when he saw you flirting with Kwan and later getting cozy with Mike.” Men, as well as women, are sometimes jealous if the person whom they are attracted to or are in love with shows attention to another person.
Chantelle was “flirting” with Kwan. “To flirt” (flirt) means to show some sort of romantic interest in another person by what you say or by what you do in a playful way, without any real seriousness perhaps behind it. Chantelle was “flirting with Kwan” and later “getting cozy with Mike,” another man. “To get cozy (cozy) with” someone means to be very close physically to that person, perhaps touching that person or putting your arm around that person or kissing that person.
Evan describes a situation in which Chantelle was with one man, Jack, but she was also flirting with Kwan and getting cozy with a third man, Mike. This made Jack, understandably, angry. Chantelle says, however, “Jack can’t stay angry with me,” meaning he won’t continue to be angry for a long time. “We’ll kiss and make up,” she says. The expression “to kiss and make up means” to end an argument, especially between a romantic couple.
Then Evan asks her, “Don’t you ever get tired of toying with so many men?” “To toy (toy) with” someone is to treat someone in a way that isn’t serious – in this case, to act as though you are romantically interested in someone when in fact you really aren’t. You’re playing with them. You’re toying with them. That’s what Evan is accusing Chantelle of doing.
Chantelle disagrees. She says, “I’m not toying with them. It’s not my fault,” meaning I am not to blame, “that men find me irresistible.” “To be irresistible” (irresistible) means it is impossible to say no to something or to someone. In this case, it means that she is very, very beautiful, very attractive, such that men cannot resist her. They can’t say no to her. Evan says, “Right, just like moths to a flame.” “Moths” (moths) are small flying insects that have large wings – the things they move up and down to fly – that typically are found at night. They’re sort of like a butterfly but are usually white or gray.
Moths are attracted to sources of light. One source of light is a “flame” (flame). A “flame” is what you get when you have a fire. The “flames” of a fire are what you can see of the fire – that which is burning produces heat and light. A moth is often attracted to light, and so may actually go into a flame, and of course doing that will kill the moth. When a moth flies into a fire or a flame, it gets burned. “To get burned,” means in one sense to have the fire harm the insect.
You can get burned if you put your hand into a fire, but here the expression has two meanings. It means literally the moths flying into the flame and being burned, but “to get burned” is also used as an expression in a romantic relationship – or perhaps in any relationship, really – where one person does something to harm another person or another person gets harmed because of the actions of the other.
In the case of Chantelle, the men are all interested in her and are attracted to her like moths to a flame, but also like moths to a flame, they will get hurt by this attraction. All of us probably have gotten burned at some point or another in our lives, especially if you vie for the attention of someone whom other people are also attracted to. There will be one winner and many losers. That’s the way the world is, isn’t it?
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Evan: Who are going out with tonight?
Chantelle: I’m not sure. I might go to dinner with Steve or Eduardo or Jim.
Evan: Dinner is in a couple of hours. You mean they’re waiting around for your call?
Chantelle: They’d better be. They’re the ones vying for my attention, so they’d better be at my beck and call.
Evan: How many guys are you juggling?
Chantelle: Not that many, only the ones who are really devoted admirers. I try to throw them a bone now and then.
Evan: By keeping them waiting.
Chantelle: It’s good to keep them on their toes.
Evan: And by making them jealous of each other? I saw how angry Jack got when he saw you flirting with Kwan and later getting cozy with Mike.
Chantelle: Jack can’t stay angry with me. We’ll kiss and make up.
Evan: Don’t you ever get tired of toying with so many men?
Chantelle: I’m not toying with them. It’s not my fault that men find me irresistible.
Evan: Right, just like moths to a flame. No wonder so many get burned!
[end of dialogue]
There is no need to wait around to improve your English. You can start right now by listening to the wonderful dialogues written by our scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to wait around – to wait for something to happen, with no other plans or activities prepared if that thing does not happen
* Don’t wait around for him to call. Come out to dinner with us tonight.
to vie for (someone’s) attention – to compete very hard against other people or things to get someone’s attention; to struggle to not be ignored
* Sometimes there are so many projects vying for my attention at the office that it’s hard to figure out where to begin.
at (one’s) beck and call – ready and willing to do whatever another person wants or asks for
* Wouldn’t it be great to have a maid at your beck and call when you’re feeling ill, ready to do whatever you need?
to juggle – to handle many things at the same time without ignoring or dropping any of them
* How do you juggle a full-time job, your family, and volunteer work?
devoted admirer – someone who really likes another person, especially in a romantic way, and would do almost anything for that person
* James has been Heather’s devoted admirer for years, but she has never been romantically interested in him.
to throw (someone) a bone – to give someone a small amount of what he or she wants or has asked for, enough to keep the person interested, but not enough to really satisfy him or her
* Quincy’s boss gave him a small raise, but not as much as he was asking for. I guess she’s just throwing him a bone to prevent him from quitting.
to keep (one) on (one’s) toes – to make someone concentrate and pay attention, remaining ready for what might happen
* The military has frequent practice drills to keep the soldiers on their toes so they are prepared for what might happen during a real war.
jealous – showing envy of what another person has or what another person has done, especially when one wants to have the romantic relationship that another person has
* Chris becomes very jealous whenever he sees his wife talking to another man.
to flirt – to express romantic or sexual attraction to another person in a casual, playful way without any real commitment
* You’re in a serious relationship now. You really shouldn’t be flirting with those women.
to get cozy – to snuggle or cuddle; to be very close physically to another person, touching and possibly kissing each other
* It’s so uncomfortable to watch people getting cozy in public. They should do that when they’re alone at home.
to kiss and make up – for a romantic couple to end an argument and become friendly and romantic toward each other again
* Buy some roses for your girlfriend and apologize for what you said. Then you two can kiss and make up.
to toy with – to play with; to tease or fool someone; to treat someone in a way that is playful and not serious, especially when that person would prefer it to be more serious
* Manuel is serious about Jaime and wants to marry her, but she’s just toying with him.
irresistible – impossible to deny, reject, or say “no” to something or someone; extremely attractive and desirable
* These cookies are irresistible! I’ve eaten almost all of them!
moth – a small flying insect with large wings that flies at night, similar to a butterfly, but usually white or gray
* At night, moths fly around the light outside our front door.
flame – the bright, hot, oval or pointed shape, usually orange, yellow, or blue, produced by a fire
* If you put the steaks on the grill now, they’ll get burnt by those tall flames.
to get burned – to be hurt or damaged by something, especially by another person’s actions in a romantic relationship; to suffer in a romantic relationship that ended in a bad way
* Xavier got burned when his last girlfriend cheated on him. Now he says that he never wants to date again.
Comprehension Questions
1. What does Chantelle mean when she says, “I try to throw them a bone”?
a) She takes the men out for dinner.
b) She is mean to the men.
c) She does nice things for the men sometimes.
2. What does Evan mean when he compares the men to “moths to a flame”?
a) They are unattractive and ugly.
b) They cannot stay away from her.
c) They are blinded by her beauty.
Answers at bottom.
What Else Does It Mean?
to wait around
The phrase “to wait around,” in this podcast, means to wait for something to happen, with no other plans or activities prepared if that thing does not happen: “Are you going to wait around for a promotion, or are you going to start applying for jobs at other companies?” The phrase “to wait on (someone)” means to serve someone: “Which server is waiting on our table tonight?” Or, “I’m not waiting on you boys. If you’re hungry, make your own snack.” Finally, the phrase “to wait up” means to stay awake until someone returns home: “Do you always wait up when your daughter is out on a date?”
to toy with
In this podcast, the phrase “to toy with (someone)” means to treat someone in a way that is playful and not serious, especially when that person would prefer it to be more serious: “Young, beautiful women sometimes enjoy toying with men who will buy them nice things.” Or, “Don’t toy with me. This is serious!” The phrase “to toy with (something)” can also mean to touch and move something around without a clear purpose: “Stop toying with your food. Just eat it!” The phrase “to toy with an idea” means to consider or think about doing something but without clear plans: “I’ve been toying with the idea of buying a boat. What do you think?” Or, “The company is toying with the idea of an international expansion.”
Culture Note
Puffery and Puff Pieces
In “advertising” (promotions; materials that encourage people to buy one’s products), companies often “overstate” (say that something is bigger or more valuable than it actually is) the “benefits” (the good things that come from having or doing something) of their products. “Lying” (not telling the truth) about a product and its benefits is against the law, but some “puffery” is allowed.
“Puffery” refers to the way in which advertisers sometimes “puff up” (inflate; make something seem bigger or more impressive than it actually is) their products by making statements that they do not expect anyone to actually believe. For example, a restaurant might advertise that it has “the best pizza in the word.” A “reasonable person” (a rational, thinking, normal person) would understand that the restaurant is simply stating that it’s pizza is very good—not that they have compared it against all the other types of pizza in the word. In an official statement in 1984, the Federal Trade Commission, a government agency that protects “consumers" (buyers of products or services), “clarified” (made clear) that this type of puffery is allowed.
In “journalism” (reporting; newspapers and magazines), “puff pieces” are articles or stories that “praise” (say good things about) someone or something in an “exaggerated” (made to seem bigger than something really is) way. The authors of puff pieces are “biased” (have an opinion and a desire to have other people think and believe the same way they do) and do not try to present a “balanced” (fair and equal) view of the topic. Many people feel that puff pieces are “unethical” (wrong) for journalists, especially when they receive free products and services in exchange for writing puff pieces.
Comprehension Answers
1 - c
2 - b