= 1274
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,274 – Childish Fighting and Misbehavior.
This is English as a Second Language Podcast episode 1,274. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. When you do, you can download the learning guide for this episode.
This episode is a dialogue between Mitch and Nancy about children fighting and acting badly, as children sometimes do. Let’s get started.
[start of dialogue]
Mitch: How was work today?
Nancy: Terrible. Nobody could get along and the name-calling started early.
Mitch: Did anybody throw a tantrum or act out in some other way?
Nancy: Several did. At one point, a couple of them stomped out and slammed the door, but they eventually came back. I wish they’d given each other the silent treatment instead.
Mitch: So there was yelling?
Nancy: Lots of yelling. They tried to talk over each other and wouldn’t take turns. After a while, I wanted to demand some quiet time, but no one would have paid me any attention.
Mitch: That sounds like a lot of posturing. At least it didn’t devolve into hitting and biting.
Nancy: Not yet, but I wouldn’t be surprised if there is plenty of that next week when the Congressional subcommittee on peacekeeping meets again.
[end of dialogue]
Mitch begins our dialogue by asking Nancy, “How was work today?” He wants to know how Nancy’s day was at work. Nancy responds, “Terrible,” meaning very bad. “Nobody could get along and the name-calling started early.” The phrasal verb “to get along” (along) means to have a friendly relationship with another person, to be nice to each other. If you say, “I get along with my mother-in-law,” that means you have a friendly relationship with her. It also means you’re probably a liar.
Nancy also says that “the name-calling started early.” “Name-calling” is when you try to hurt another person’s feelings by calling or using a bad name for him. I won’t give you examples but you probably can think of lots of names or words that you call other people whom you don’t like or whom you want to anger. Mitch asks, “Did anybody throw a tantrum or act out in some other way?” The expression “to throw (throw) a tantrum (tantrum)” means to lose control of your emotions or your actions – to get very angry or upset and begin to act in ways that you shouldn’t.
Normally, we associate this expression “throwing a tantrum” with a child, a young child who gets mad and starts yelling or perhaps hitting other people. If you say that an adult is “throwing a tantrum,” you are really insulting that person, saying that that person is acting like a child, because we only expect children to throw a tantrum. “To act (act) out” is also another expression that we usually use with children, or to describe the way children act when they are being bad – when they are, we would say, “behaving badly.”
“To behave” (behave) means to act. The title of this episode is “misbehavior,” which refers to people not acting the way they should, or acting badly. “To act out” means to yell or start doing things that show that you are angry. It’s something that children might do when they get upset. They might start yelling or throwing things or hitting other people. That’s what “to act out” means. To be honest, I don’t remember hearing this expression a lot when I was a child. Although in my family, if you misbehaved, my parents would certainly let you know about it and it would not last very long.
Nancy says that several people threw a tantrum and acted out at her work today. She says, “At one point,” meaning at a certain time, “a couple of them stomped out and slammed the door, but they eventually came back.” The expression “to stomp” (stomp) refers to hitting your feet against the floor loudly. The phrasal verb “to stomp out” means to leave a room by loudly hitting your feet against the floor. It’s an indication that you’re angry and you’re leaving because you are angry or upset with someone.
Similarly, “to slam (slam) the door” means to close the door very loudly, with a lot of force. Again, that usually indicates that you are angry, when you slam the door. Nancy says a couple of people at her work “stomped out and slammed the door, but they eventually,” meaning later, “came back.” “I wish they’d given each other the silent treatment instead,” she says. The phrase “the silent treatment” (treatment) refers to a period of time when two people don’t talk to each other because they are angry with each other. If you’re married, you know what I mean.
Mitch says, “So there was yelling?” “Yelling” comes from the verb “to yell” (yell). “To yell” means to shout, to speak in a very loud voice, usually because you’re angry. Nancy says, “Lots of yelling,” meaning yes, there was a lot of yelling. “They tried to talk over each other and wouldn’t take turns,” she explains. “To talk over someone” is a two-word phrasal verb meaning to speak while another person is speaking, especially if you want to say something and don’t want to listen to the other person.
If you are arguing with another person, you may sometimes talk over that other person – talk when he or she is talking. My wife loves it when I talk over her during a discussion. That’s a joke. Nancy says the people at her work “tried to talk over each other and wouldn’t take turns (turns).” “To take turns” means to allow someone else to do something that you are doing. First, I do it, then you do it, then another person does it, then another person does it, then I do it, and so forth. That’s “taking turns.” Everyone gets a chance or an opportunity to do something – in this case, to talk.
“After a while,” Nancy continues, “I wanted to demand some quiet time.” “Quiet time” is a period of silence when no one is allowed to talk. She says, “No one would have paid me any attention,” however. “To pay attention” means to do what the other person says to do, or at least to listen to the other person. Mitch says, “That sounds like a lot of posturing.” The verb “to posture” (posture) means to behave or to act in a certain way in order to impress other people, to make other people think a certain way about you, or perhaps even to make other people afraid of you. “To posture” is to act in a certain way, to make you seem bigger or stronger or more powerful than you really are.
Mitch says, “At least it didn’t devolve into hitting and biting.” The verb “to devolve” (devolve) means to change into something worse. We might also use the verb “to deteriorate” or simply “to worsen” (worsen). Mitch says, “At least it didn’t devolve into hitting (hitting) and biting (biting).” “To hit” someone is to use a part of your body, such as your hand or perhaps an object, a thing, to hurt that person by moving it with force into that person. Normally, if you hit someone, you are angry at that person.
“To bite” (bite) means to use your teeth, which are inside of your mouth, to hurt another person. Normally we bite a piece of food when we are eating. You don’t normally bite another person. Once again, that would be something perhaps that a child would do. Nancy says, “Not yet,” meaning the people at her work had not yet started hitting and biting, but perhaps they will in the future. In fact, she says, “I wouldn’t be surprised,” meaning it would not surprise me – it would not be unusual, “if there is plenty of that” – that is, a lot of hitting and biting – “next week when the Congressional subcommittee on peacekeeping meets again.”
The final line of the dialogue then tells us where Nancy works. She works in Congress. She works in that part of our national or federal government in Washington, D.C., that is composed of representatives of the people. A “congressional subcommittee” is a group of people in Congress that are discussing and are responsible for laws about a certain topic. This topic in the case of our dialogue is “peacekeeping” (peacekeeping). “Peace” is the opposite of “war.” “Peacekeeping” means trying to prevent people from fighting.
So of course, the joke in our dialogue here is that this group of people, this congressional subcommittee on peacekeeping, is in fact a group of people who are always fighting each other and behaving badly.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mitch: How was work today?
Nancy: Terrible. Nobody could get along and the name-calling started early.
Mitch: Did anybody throw a tantrum or act out in some other way?
Nancy: Several did. At one point, a couple of them stomped out and slammed the door, but they eventually came back. I wish they’d given each other the silent treatment instead.
Mitch: So there was yelling?
Nancy: Lots of yelling. They tried to talk over each other and wouldn’t take turns. After a while, I wanted to demand some quiet time, but no one would have paid me any attention.
Mitch: That sounds like a lot of posturing. At least it didn’t devolve into hitting and biting.
Nancy: Not yet, but I wouldn’t be surprised if there is plenty of that next week when the Congressional subcommittee on peacekeeping meets again.
[end of dialogue]
Our wonderful scriptwriter gets along with everyone here at ESL Podcast. I speak of the great Dr. Lucy Tse.
From Los Angeles, California, I’m the not-very-great Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to get along – to be pleasant with another person and not fight or argue; to have a friendly relationship
* Sheraz didn’t get along with his brothers when they were growing up, but they became good friends as adults.
name-calling – the act of hurting another person’s feelings by referring to that person using insulting or offensive names
* It’s completely inappropriate for your boss to engaged in name-calling. The next time he calls you a “stupid idiot,” report it to human resources.
to throw a tantrum – to lose control of one’s emotions, actions, and words, usually when one is very upset and begins to behave in inappropriate ways like a very young child
* The little girl threw a tantrum at the grocery store because her father refused to buy her a candy bar.
to act out – to behave very badly; to behave in inappropriate ways to get attention and get what one wants
* The school counselor is concerned about students who acting out frequently in the classroom.
to stomp out – to leave a room angrily, making loud noises by hitting one’s feet forcefully against the ground while walking
* They got in a huge argument and then Mania stomped out of the room.
to slam – to hit something so that it makes a loud noise, especially when closing a door
* Jorge slammed the car door in anger, but then realized that he had locked his keys inside.
silent treatment – a period of time when one refuses to speak to another person out of anger
* As parents, we are so tired of hearing our kids argue! We wish they would give each other the silent treatment.
to yell – to shout; to speak in a very loud, usually angry voice
* They had to yell to be heard over the sound of the storm.
to talk over – to speak while another person is speaking
* I can’t understand what either one of you is saying. Please stop talking over each other.
to take turns – to alternate; to allow someone to do something for a period of time, then do it oneself, and then allow the other person to do it again
* They’re taking turns driving during the four-day road trip.
quiet time – a period of silence; a period of time when no one is allowed to speak or make other noises, usually to help people become calm and/or concentrate
* Many children need a little bit of quiet time after a long day at school.
posturing – behaving is a way that is supposed to intimidate or impress other people, making one seem bigger and more powerful than one actually is
* Don’t be fooled by Solomon’s posturing. He’s not as influential as he pretends to be.
to devolve – to worsen; to deteriorate; to gradually become worse and worse
* The debates devolved from a discussion of the issues to personal attacks.
to hit – to try to hurt another person with one’s hand or an object
* Why did you hit your brother?
to bite – to try to hurt someone with one’s teeth
* Our dog bit the neighbor last night for no reason.
Congressional subcommittee – a group of U.S. elected representatives who discuss particular issues in order to propose and vote on laws related to them
* The Congressional subcommittee on labor has voted against any increase in the national minimum wage.
peacekeeping – activities and people focused on ending wars and maintaining peaceful relationships between regions and countries
* The peacekeeping efforts are focused on ending the bombings and finding safe housing for people living in areas of fighting.
Comprehension Questions
1. Which of these actions could hurt another person?
a) Throwing a tantrum
b) Posturing
c) Biting
2. What happened when people stomped out?
a) They left the room angrily.
b) They shouted rudely.
c) They demanded a refund.
Answers at bottom.
What Else Does It Mean?
to slam
The verb “to slam,” in this podcast, means to hit something so that it makes a loud noise, especially when closing a door: “The gate is falling apart, so please don’t slam it, or it might break into pieces.” The phrase “to slam the door in (someone’s) face” means to refuse to help or meet with someone: “Our city’s mayor slammed the door in the faces of a group of lawmakers who had supported his opponent in the election.” “The phrase “to slam on the brakes” means to use the brakes of a car forcefully in order to stop suddenly: “A little kid ran into the road and I had to slam on the brakes to avoid hitting her.” Finally, the phrase “to slam (someone)” means to criticize someone harshly: “Blake was slammed for his poor management of the new department.”
to bite
In this podcast, the verb “to bite” means to try to hurt someone with one’s teeth: “What are preschool teachers supposed to do when one child bites another?” The phrase “to bite (one’s) tongue” means to not say what one really thinks even though one has very strong opinions and it is difficult to remain silent: “Over the years, I’ve learned to bite my tongue on holidays when our family begins talking about politics.” The phrase “to bite the dust” means to fail or to perform very badly: “Wow, she really bit the dust in that competition coming in last place.” Finally, the phrase “to bite the bullet” means to become determined to do something even though it is difficult or unpleasant: “We’re going to have to bite the bullet and buy a new car, because it’s getting too expensive to fix our old one.”
Culture Note
Congressional Ethics
Since 2008, the Office of Congressional Ethics has reviewed “allegations” (claims or statements that someone has done something wrong) of “ethical” (related to what is right or wrong) “misconduct” (bad behavior) against “elected” (selected by voting) members of the “House of Representatives” (one of two groups that makes laws in the United States). It might “act upon” (react to) allegations from the public, other Representatives, the “media” (newspaper, radio, magazine, television, or Internet reports), or “unnamed” (not identified) sources. It shares its “findings” (what it learns from its review or investigation) with the United States House Committee on Ethics.
The Committee on Ethics has an equal number of members from each of the two main political parties. Together, the committee members agree on the rules that “govern” (control) ethical behavior, such as whether elected Representatives should be allowed to accept gifts, or how they should “handle” (manage; deal with) “conflicts of interest” (situations where one’s behavior is influenced by other professional or personal relationships). The committee “investigates” (conducts research into) whether Representatives have violated those rules and makes recommendations about whether and how that behavior should be punished.
In the most extreme cases of unethical behavior, punishment may include “reprimand,” “censure,” “fine,” or “expulsion.” “Reprimand” and “censure” are very similar and both involve publicly “criticizing” (saying that someone has done something wrong) the “offending” (doing something that is wrong) Representative. A “fine” requires the offending Representative to pay money as a punishment. The most serious punishment “expulsion,” forces the representative to leave the House of Representatives.
Comprehension Answers
1 - c
2 - a