= 1305
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,305 – Saying a Final Goodbye.
This is English as a Second Language Podcast episode 1,305. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode is a dialogue between Lucy and me about saying goodbye. Let’s get started.
[start of dialogue]
Lucy: I don’t know how to say goodbye.
Jeff: How about so long, I’m outta here, “I’m leaving on a jet plane” and “in 10 minutes I’ll be late for the door”?
Lucy: No, that’s not what I mean. I mean that it’s hard to say goodbye to something after such a long time. I’ve had a very happy time here.
Jeff: What you really mean to say is, “Parting is such sweet sorrow.” But, “It’s better to have loved and lost than never to have loved at all.” “I, I, will always love you.”
Lucy: Stop! Listen, what I want to express is a fond farewell and optimism for the future.
Jeff: Ah, okay! Then you should say: Tomorrow is the first day of the rest of my life! I’m off to bigger and better things! I’m blowing this pop stand!
Lucy: No, no, no. That’s not right at all. I want to end with some meaningful parting words, something sincere, something from my heart.
Jeff: Like, “May the force be with you”?
Lucy: Hmm . . . how about “Live long and prosper”?
Jeff: Now are you ready to leave?
Lucy: I guess so. It’s been a blast.
Jeff: It’s been a hoot.
Lucy: It’s been an honor and a pleasure.
Jeff: Adiós.
Lucy: Au revoir.
Jeff: Sayonara.
Lucy: Zàijiàn. Zoi gin.
Jeff: Ciao.
Lucy: Auf Wiedersehen.
Jeff: Proshchay.
Lucy: Tchau.
Jeff: Wadaeaan.
Lucy: Annyeong.
Jeff: Toodle loo!
Lucy & Jeff: Thank you and goodbye.
[end of dialogue]
Lucy begins our dialogue by saying, “I don’t know how to say goodbye.” I then give her some suggestions, some informal expressions that we might use in English to say goodbye. These are all informal, definitely not things that you would say in normal conversation, in a formal setting. The first one, however, I guess you could say in a formal or informal setting, and that is “so long.” “So long” is one way of saying goodbye.
Another much more informal way of saying goodbye is “I am outta here.” “I am outta (outta) here” is something of an abbreviated way of saying, “I am out of here.” “To be out of here” is a way of saying “I’m leaving quickly,” often because I no longer want to be here, though that isn’t always the case. If someone says, “I’m outta here,” he may be saying, “This is a bad situation and I no longer want to be here.” Said in a different context, perhaps in a different way, it just means goodbye. If you are, for example, talking to a friend and you look at your clock and you realize you have to get home now, you say, “Well, I’m outta here. I gotta get home.” I have to return to my house.
The next two expressions that I use are from songs, really, and they are expressions of saying goodbye or of leaving from a couple of different popular songs. One of them is “I’m leaving on a jet (jet) plane.” This comes from an old song called, appropriately enough, “I’m Leaving on a Jet Plane.” It was a song sung by the folk group back in the 1960s, Peter, Paul, and Mary.
I’m leaving on a jet plane
don’t know when I’ll be back again
It would be a very unusual way of saying goodbye, but it’s possible in a joking way, especially if you are about to leave on a plane. A “jet plane” is really just another word for an airplane here. “In 10 minutes I’ll be late for the door” is another suggestion I give, and once again this comes from a popular song from my youth, a song by the rock group Bob Seger and the Silver Bullet Band, who I actually saw in concert when I was in high school. Yeah. I’m that old.
The song was called “Old Time Rock and Roll” and was made famous in the movie that starred a young Tom Cruise called Risky Business. “In 10 minutes, I’ll be late for the door.” “To be late for the door” means that I will be out of the door – that is, I will be leaving. However, again, it’s not something that you would normally say in order to say goodbye, but to someone of a certain age – my age – you might say it as a joke, knowing the other person would recognize it as a line from the song. The person would understand it means that you are saying goodbye.
Lucy says, however, “No, that’s not what I mean.” I was giving her expressions used in situations when you are leaving temporarily – say, in the morning or after work. Lucy was referring to something more permanent. She says, “I mean that it’s hard to say goodbye to something after such a long time.” She’s referring to perhaps leaving one’s job or saying goodbye to a certain situation such as writing dialogues, for example, for English lessons. “I’ve had a very happy time here,” she says.
I respond by saying, “What you really mean to say is, ‘Parting is such sweet sorrow.’” “Parting is such sweet sorrow” is a well-known or famous line, phrase, spoken by one of the actors – one of the characters, I should say – in the Shakespeare play Romeo and Juliet. It’s used sometimes now, almost as a joke, to say that it is sad to say goodbye.
The original line in the play means that saying goodbye is sad. That’s why it is a “sorrow” (sorrow). “Sorrow” refers to sadness, but it is a “sweet (sweet) sorrow.” It’s sweet because we think about the good times we’ve had together. “Parting” comes from the verb “to part” (part), which here means to separate – when two people have to say goodbye to each other. That’s where we get this expression, then, “Parting is such sweet sorrow.”
Then I use another famous sentence, “It’s better to have loved and lost than never to have loved at all.” This is also, as I mentioned, a famous line, a famous sentence, this time from a poem that was written by the great British poet Alfred Lord Tennyson. It’s an adaptation, really, from his poem “In Memoriam A. H. H.” It means that it’s painful to end a relationship, especially a romantic relationship, but it is better to have loved someone and then lose that person than never to have actually loved the person, or to love anyone, I suppose, in general.
“It’s better to have loved and lost,” meaning lost the person you loved, “than never to have loved at all.” I’m trying to be funny in the dialogue, as I usually do. I’m using these famous expressions, these famous lines from poems and plays, in order to express this feeling of saying goodbye. Then I take a line from a famous song by the singer Dolly Parton. It was recorded most famously by Whitney Houston in 1992 for a really terrible movie called The Bodyguard, but anyway, the line is “I will always love you, will always love you.” (I had to do that.)
Lucy then says, “Stop!” I, of course, am making fun and she’s trying to be a little serious. She says, “Listen,” meaning pay attention to me. “What I want to express is a fond farewell and optimism for the future.” “To express” means to communicate. A “fond (fond) farewell (farewell)” is a sweet, kind, emotional goodbye. Something that people would give to each other when they like each other.
“Farewell” is another way of saying goodbye. A “farewell” is a goodbye. “Fond” is something that is kind, something that you really mean. “Optimism” (optimism) is a positive view of the future, a belief that things will be better in the future, a hopefulness. Lucy wants to express a “fond farewell and optimism for the future.”
I say, “Ah, okay! Then you should say” – and I give another common expression – “Tomorrow is the first day of the rest of my life.” This is an expression sometimes people use when they are trying to be positive about their future. “Tomorrow is the first day of the rest of my life” – unless of course you die today, in which case tomorrow is not anything.
I then say, “I’m off to bigger and better things!” “I’m off to” means I am leaving now to go on to bigger and better things, a better situation. Then I use a third expression which is quite different and is actually an informal way of saying goodbye sometimes, “I’m blowing this pop stand!” “To blow this pop (pop) stand (stand)” means that you are leaving a place. You are saying goodbye to everyone, probably because you think the place you are in is boring or the situation you are in is unpleasant, one that isn’t very exciting, one that makes you want to leave.
A “stand” is a small store, often outside, where you sell things from. You might sell things such as soda pop, and hence the expression “pop stand.” People also nowadays say, “Oh, I’m going to blow this popsicle stand,” or “Let’s blow this popsicle stand.” A “popsicle” is a frozen dessert, basically sugar water that has been frozen. So, “I’m blowing this pop stand,” or if you say to someone else, “Let’s blow this popsicle stand,” are both ways of saying that you are now leaving this place because it’s too boring or too unexciting for you.
Lucy says, “No, no, no. That’s not right at all. I want to end with some meaningful parting words, something sincere, something from my heart.” “Parting words” would be words you say when you are leaving someone. “To be sincere” (sincere) means to express your true emotions, your true feelings, your real thoughts without hiding anything. Lucy wants to express something from her heart, emotionally, meaningfully.
I then say, “Like,” meaning for example, “‘May the force be with you?’” “May the force (force) be with you” is a well-known line from, of course, the Star Wars movies, used in general to mean good luck or I hope you will be successful. Lucy then uses another famous line from another science fiction movie or TV series, “Live long and prosper.” “To prosper” (prosper) means to be successful, often financially or economically successful at what you do. This is a famous line from the character Spock in the Star Trek TV shows and movies.
Then I say to Lucy, “Now are you ready to leave?” Lucy says, “I guess so.” “I guess so” means yes, but it’s said when either you’re not sure or perhaps you’re not very enthusiastic about something. She says, however, “It’s been a blast” (blast). A “blast” is a great time, a lot of fun, a lot of excitement. I then say, “It’s been a hoot” (hoot). A “hoot” is something that is fun, enjoyable, entertaining. It’s an old word, an old expression. We don’t use it much anymore other than to be funny because it is such an old expression. “It’s been a hoot.”
Lucy says, “It’s been an honor and a pleasure.” An “honor” is something that you believe is like a gift to you. You’ve had the ability to do something because someone has given you that ability, someone has given you permission to do something or has given something to you almost as if it were a gift. Lucy says, “It’s been an honor and a pleasure.” I think she means making these lessons, but in general it’s something you could say if you have been happy to do something.
Then Lucy and I give a number of ways of saying goodbye in different languages. I won’t repeat those here. I do say one thing in English using another very old way of saying goodbye, which is “Toodle loo!” “Toodle (toodle) loo (loo)” is a funny, informal way saying goodbye nowadays. It’s actually taken from a French word, but it is a very, we would call, “corrupt” pronunciation. “Toodle loo” is just a funny way of saying goodbye.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lucy: I don’t know how to say goodbye.
Jeff: How about so long, I’m outta here, “I’m leaving on a jet plane” and “in 10 minutes I’ll be late for the door”?
Lucy: No, that’s not what I mean. I mean that it’s hard to say goodbye to something after such a long time. I’ve had a very happy time here.
Jeff: What you really mean to say is, “Parting is such sweet sorrow.” But, “It’s better to have loved and lost than never to have loved at all.” “I, I, will always love you.”
Lucy: Stop! Listen, what I want to express is a fond farewell and optimism for the future.
Jeff: Ah, okay! Then you should say: Tomorrow is the first day of the rest of my life! I’m off to bigger and better things! I’m blowing this pop stand!
Lucy: No, no, no. That’s not right at all. I want to end with some meaningful parting words, something sincere, something from my heart.
Jeff: Like, “May the force be with you”?
Lucy: Hmm . . . how about “Live long and prosper”?
Jeff: Now are you ready to leave?
Lucy: I guess so. It’s been a blast.
Jeff: It’s been a hoot.
Lucy: It’s been an honor and a pleasure.
Jeff: Adiós.
Lucy: Au revoir.
Jeff: Sayonara.
Lucy: Zàijiàn. Zoi gin.
Jeff: Ciao.
Lucy: Auf Wiedersehen.
Jeff: Proshchay.
Lucy: Tchau.
Jeff: Wadaeaan.
Lucy: Annyeong.
Jeff: Toodle loo!
Lucy & Jeff: Thank you and goodbye.
[end of dialogue]
As I tried to do in every episode, I want to thank our wonderful scriptwriter, Dr. Lucy Tse, for all of her 1,305 wonderful scripts, and both Lucy and I thank you for listening.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. So long.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2017 by the Center for Educational Development.
Glossary
so long – an informal phrase used to say goodbye or “see you later”
* So long, I’ll see you next month!
I’m outta here – an informal phrase meaning that one is leaving or departing
* It’s 5:30 on a Friday and it’s the end of a workweek. I’m outta here!
I’m leaving on a jet plane – well-known “lyrics” (words that are sung) from “Leaving on a Jet Plane,” a song written by John Denver in 1966 and recorded by Peter, Paul and Mary; a phrase meaning that one is going away
* Liam smiled when the sounds of “I’m Leaving on a Jet Plane” echoed through the airport because it is one of his favorite songs.
in 10 minutes I’ll be late for the door – well-known “lyrics” (words that are sung) from “Old Time Rock and Roll,” a song by Bob Seger; a phrase used to show that one must leave soon
* Hurry up and finish getting ready! In 10 minutes I’ll be late for the door.
parting is such sweet sorrow – a well-known “line” (phrase spoken by actors) from Romeo and Juliet, a play by William Shakespeare, meaning that it is sad to say goodbye, but also pleasant because it makes one think about the next time when one will see the other person
* Heather started crying when she said goodbye to her boyfriend. Parting is such sweet sorrow.
it’s better to have loved and lost than never to have loved at all – a well-known “line” (one part of a poem) adapted from In Memoriam A.H.H, a poem by Alfred Lord Tennyson; a phrase meaning that although it is painful to end a relationship, one is grateful for having known the other person
* I’m sorry we broke up, but I don’t regret that we dated. It’s better to have loved and lost than never to have loved at all.
I, I, will always love you – well-known “lyrics” (words that are sung) from “I will Always Love You,” a song written and recorded by Dolly Parton in 1973, but better known from Whitney Houston’s 1992 recording
* The neighbor’s boyfriend stood in front of our apartment building and sang “I, I, will always love you” as loud as he could to try to get his girlfriend back.
to express – to present, show, or display one’s feelings or thoughts in a particular way
* Hundreds of people expressed their opinions about the new law at the meeting.
fond farewell – a sweet goodbye in which the people care about each other and speak kindly to each other
* Brent’s colleagues gave him a fond farewell on his last day in the office.
optimism – hopefulness; a belief that good things will happen; positivity; without negative thoughts
* I appreciate your optimism, but I just don’t think this business plan can succeed.
I’m blowing this pop stand – also “let’s blow this popsicle stand,” a phrase meaning that one is leaving a boring, unexciting place
* This movie is so boring. I’m blowing this pop stand!
parting words – the words that one speaks when saying goodbye; the last words one says to another person
* We couldn’t believe Mother’s parting words were, “Don’t forget to take out the garbage.”
sincere – showing one’s true emotions and feelings, without hiding anything and without deceiving or lying
* Please except my sincere apology. It was my fault and I take full responsibility.
may the force be with you – a well-known “line” (words spoken in a movie or play) from the Star Wars movies, used to wish someone good luck so that he or she will succeed
* Good luck on your business trip. May the force be with you.
Live long and prosper – a well-known “line” (words spoken in a movie or play) from the Star Trek TV series used to wish someone peace and success, usually with the hand raised in the air, with the “palm” (flat, open, front part of the hand) facing the other person, forming a V shape using the middle and ring fingers
* Congratulations on your new job offer! Live long and prosper.
a blast – a great time; a lot of fun and excitement
* The new ride at the amusement park is a blast! You have to try it!
a hoot – something that is funny, entertaining, and enjoyable
* Carl is a hoot! He’s always telling jokes that make everyone laugh.
toodle loo – a funny, informal way to say goodbye, taken from the French phrase à tout à l'heure, meaning “see you soon”
* Thanks for a fun day! Toodle loo!
Comprehension Questions
Answers at bottom.
What Else Does It Mean?
to express
The verb “to express,” in this podcast, means to present, show, or display one’s feelings or thoughts in a particular way: “Why do so many people struggle to express their emotions?” In mathematics, the phrase “to express (something) in (units)” means to change the form of a quantity: “Please express your answer in degrees Fahrenheit – not Celsius.” An “express train/bus” is a very fast train or bus with few stops: “If you’re traveling by train from New York to Pennsylvania, make sure you take the express train so you don’t have to stop at every train station along the way.” Finally, the phrase “words cannot express” means that one is not able to describe something fully: “Words cannot express how much I love my children.”
blast
In this podcast, the word “blast” means a great time with a lot of fun and excitement: “The kids have a blast playing in the swimming pool on hot, sunny days.” The word “blast” can also refer to the sudden movement of air or water: “The firemen opened the door, releasing a hot blast of air.” A “blast” can also be a loud noise caused by a horn or an explosion: “New York City is filled with the blast of car horns.” The phrase “at full blast” means for a device or machine to be turned on to the highest setting, especially to full volume, or as loudly as possible: “Never listen to headphones at full blast as it might damage your ears.” Finally, a “blast” can be an explosion: “Two soldiers lost their legs in the bomb blast.”
Culture Note
Famous Rock Band Breakups and Reunions
Many famous “rock banks” (groups of musicians who perform rock-and-roll music” have “devoted” (with strong commitment and enthusiasm) “fans” (people who like something very much) who “mourn” (feel very sad about a loss or death) their “breakups” (when a band breaks apart so that the members no longer perform together) and “celebrate” (are very happy about) their “reunions” (when the former members of a band perform together again after many years).
Many bands break up because the musicians are “overworked” (have worked too hard) and too “stressed out” (with feelings of anxiety and worry). That is what happened to The Eagles, a popular band in the 1970s. After years of “constant” (without stopping; without breaks) “recording” (making new music) and “touring” (traveling to many places to give concerts), the band members had “frayed nerves” (a lot of anxiety) and had trouble “getting along” (maintaining friendly relationships). “Everything fell apart” (problems began) in July 1980 at a concert where one of the band members “insulted” (said something that hurt someone’s feelings) a “Senator” (an elected representative in the government). Another band member became upset, they argued, and the band broke up. However, the performers “reunited” (came back together again) in the 1990s and released new “albums” (collections of recorded music).
Other bands have more “complex” (complicated; not clear, simple, or straightforward) reasons for breaking up. Van Halen was a popular rock band in the late 1970s, but the band is “widely known” (known by many people) for its “dramatic” (with a lot of emotion) breakup. The band “repeatedly” (many times) changed its singers and “bassists” (people who play the bass guitar) in a “series” (a group of events that happen over time) of “ugly” (not friendly or peaceful) breakups in which the members “cited” (referred to) different reasons for leaving.
Comprehension Answers
1 - b
2 - a