= 0217
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 217, “Lost and Found.”
This is English as a Second Language Podcast episode 217. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com to get more information about our podcast and some new things we have on our website. You'll also find a copy of the Learning Guide for this episode, which has all of the vocabulary, definitions, sample sentences, additional definitions that we do not talk about in the podcast, cultural notes and a complete transcript of this episode.
Our episode 217 is called, “Lost and Found.” Let's go!
[Start of story]
Airport employee: Hello, Portland Airport, Lost and Found.
Lucas: Hello. I was a passenger on a SunCal Airlines flight yesterday and I think I left my keys on the plane.
Airport employee: I see. To claim the item, you have to fill out a claim form. What did you lose again? Some luggage? You’ll need your claim receipt to get your luggage.
Lucas: No, I lost some keys on the airplane. Keys. I think I left them on my seat. Is it possible to find out if anyone has turned them in to your office?
Airport employee: I don’t know. Can you describe them?
Lucas: Well, they’re on a key chain and there are eight keys on it, including a car key.
Airport employee: Was there anything distinctive about the key chain? You’ll need to prove ownership if you want to claim them.
Lucas: No, it’s a plain key ring. Maybe I should come down to the office to see if I can identify them. What happens to property that’s unclaimed?
Airport employee: We keep it for 30 days and then we dispose of it. Don’t worry. We don’t have a policy of finders, keepers. If you lost some luggage, it’ll turn up.
Lucas: No, I lost some keys! Keys! Never mind. I’m coming down right now.
Airport employee: That’s a good idea. It’s easier to pick up your lost luggage than for us to send it.
Lucas: Uh!
[End of story]
The title of this podcast is, “Lost and Found.” Lost and found is a place in a store or an airport, or some public place where you can go to if you lose something and someone brings it to the lost and found, someone finds it for you. This is the place where you go to see if anyone has found it and brought it back. So, it's a place in a store, or an airport, or a bus station. Sometimes it's not a separate place. Sometimes it is part of another office or another area in an airport, or in a train station, or in a store. There are also online lost and found places now. If you look at our Cultural Note in the Learning Guide today, you'll get more information about that.
Our dialogue begins with the employee, the person who works at the airport, answering the telephone. So, this is a telephone conversation, and she says “Hello, Portland Airport, Lost and Found.” So, she is identifying, she is saying where she is, who you are calling, which is a common thing that businesses do.
Our gentleman in this dialogue, Lucas, says “Hello. I was a passenger on a flight yesterday and I think I left my keys on the plane.” Lucas says, I was on one of your airplanes yesterday - I was on a flight yesterday and I think I left my keys - your car keys, your house keys, that sort of thing. A key is something you use to open something that is locked.
Well, the airport employee doesn't seem to really listen very well. She says, “I see” - I understand. “To claim the item, you have to fill out a claim form.” To claim, “claim,” means to get something back, or to say that something is yours. It belongs to you. So, the airport employees says, well, if you want to get it back, if you want to claim the item, the thing that you lost, you'll “have to fill out a claim form.” And a claim form is a piece of paper that you put your name and address and information on, and that way the airport or the store has some record of what happened to this lost item.
The airport employee says, “What did you lose again? Some luggage?” Luggage, “luggage,” is the same as baggage, “baggage.” For traveling in an airplane, that's usually your suitcases, the thing you use to put your clothes and other items into to carry them. The airport employee says you’ll need to have a “claim receipt to get your luggage.” A claim receipt is a piece of paper they give you at the airport when you give them your baggage, you give them your luggage. We say when you “check your luggage.” To check your luggage at the airport means to give your suitcase and they put it in the bottom of the plane and then you pick it up again when you arrive at the place where you are going to. So, this is a claim receipt, it's a little piece of paper that has a number on it, usually, and there's also a little piece of paper on your luggage.
Lucas says, “No, I lost some keys on the airplane.” He's trying to explain to the airport employee that he did not lose his luggage. He says, “I think I left” my keys “on my seat” - where I was sitting. “Is it possible to find out if anyone has turned them in to your office?” To turn (something) in means that you find something that isn't yours and you give it to the store, or the airport, or wherever you are. So for example, if you are at the train station and you find a wallet with money and driver’s license and other information, credit cards, you would, I hope, take that to the lost and found and say, “Here, I found this.” You would turn it in. You would give it back so someone could come back and claim it.
The airport employee says, “I don’t know. Can you describe” your keys? He says, “Well,” the keys are “on a key chain and there are eight keys on it.” A key chain, “chain,” is usually a round piece of metal that holds your keys. My key chain is huge because I have keys for everything. Well, Lucas says that he has eight keys on his key chain, and the airport employee asks him is “there anything distinctive about the key chain?” Distinctive, “distinctive,” means is there anything special, is there anything different about your key chain? She says that Lucas will “need to prove ownership if” he wants “to claim them.” To prove, “prove,” means to show or to demonstrate. Ownership is the idea that you own something, you possess something, that it's yours. So, you need to prove that it is yours, she says.
Lucas says, “it’s a plain key ring.” The adjective plain, “plain” - different spelling from the thing that you fly in, which is a plane, “plane” - a plain key chain, or a plain key ring, is a normal...not special. We say something is plain we mean there's nothing special, nothing different, nothing extraordinary about it, nothing unusual about it.
Lucas says he can come “to the office” and “identify them,” or say that, “Yes, those are mine.” That is to identify. He asks what happens to things that are unclaimed, meaning no one comes and gets them. The employee's says that they keep things “for thirty days and then” they “dispose of it.” To dispose, “dispose,” means to get rid of, to either throw out or to give away to someone else. The employee says that they “don’t have a policy of finders, keepers.” The expression finders, “finders,” keepers, “keepers,” means that if you find something, it belongs to you. This is an expression that kids use sometimes, children. Finders, keepers means if I find it, I get to keep it. The full expression is, “Finders, keepers, losers, weepers,” meaning if I find it, I get to keep it, and if it is yours, you lose it and therefore you will cry, you will weep. To weep, “weep,” means to cry. So, “Finders, keepers, losers, weepers.”
The employee says, “If you lost some luggage, it will turn up.” To turn up, “turn up,” two words, means that someone will find it. It will be found. The expression, “turn up” and “turn in” have different meanings, other meanings besides the ones we have described here. If you look at the Learning Guide today, you will see some additional definitions for those two terms.
Lucas is getting somewhat angry. He says, “No, I lost some keys! Never mind,” he says to the employee. The expression never mind, “mind,” means forget about it. Don't worry about it. Sometimes you say that to someone who is not very smart, doesn't understand you. You try to explain, and then you'll say, “Never mind.” This happens with me and my wife all the time. She tries to explain something to me, I'm too stupid and she says, “Never mind.”
Finally, the airport employee, who still does not understand, says oh, I'm sure that it would be easier for you to get your luggage than for them to send it, and Lucas just says, “Uh!” He's completely frustrated. He's tired of talking to this employee.
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
Airport employee: Hello, Portland Airport, Lost and Found.
Lucas: Hello. I was a passenger on a SunCal Airlines flight yesterday and I think I left my keys on the plane.
Airport employee: I see. To claim the item, you have to fill out a claim form. What did you lose again? Some luggage? You’ll need your claim receipt to get your luggage.
Lucas: No, I lost some keys on the airplane. Keys. I think I left them on my seat. Is it possible to find out if anyone has turned them in to your office?
Airport employee: I don’t know. Can you describe them?
Lucas: Well, they’re on a key chain and there are eight keys on it, including a car key.
Airport employee: Was there anything distinctive about the key chain? You’ll need to prove ownership if you want to claim them.
Lucas: No, it’s a plain key ring. Maybe I should come down to the office to see if I can identify them. What happens to property that’s unclaimed?
Airport employee: We keep it for 30 days and then we dispose of it. Don’t worry. We don’t have a policy of finders, keepers. If you lost some luggage, it’ll turn up.
Lucas: No, I lost some keys! Keys! Never mind. I’m coming down right now.
Airport employee: That’s a good idea. It’s easier to pick up your lost luggage than for us to send it.
Lucas: Uh!
[End of story]
The script for today's podcast was by Dr. Lucy Tse. If you have a question or a comment about our podcast, you can email us at eslpod@eslpod.com.
From Los Angeles, California, I am Jeff McQuillan. Thank you for listening. We will see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
Lost and Found – a place that holds lost items for people until they come to find them
* I left my glasses at the theater last night, and I’m hoping someone turned them in to the Lost and Found.
to claim – to say an item belongs to you
* Everyone is waiting to see who will claim the $20 million lottery prize!
claim form – a form that someone completes to say that an item that was found belongs to him or her
* Before we can allow you to take this bicycle, you’ll need to fill out a claim form.
luggage – suitcases or bags that people take on a trip
* My sister always has a lot of luggage when she travels because she can’t make up her mind about what to bring.
claim receipt/ticket – a small ticket that passengers receive when their luggage is stored so they can claim it again at the end of the trip
* The security officers at the airport were checking each person’s luggage and claim receipt before they were allowed to leave the baggage claim area.
to turn (something) in – to give to someone else, usually something that doesn’t belong to you; to submit
* He wasn’t sure if he would get to his professor’s office in time to turn in his final assignment.
key chain – a small metal ring for holding keys; can come in many shapes or with special decorations
* I’d better put my new apartment key on my key chain before I lose it.
distinctive – easy to notice; special; unique
* This artist has a very distinctive style and should get a lot of attention at the show next month.
to prove ownership – to prove or give evidence that you own something
* Erin’s car was stolen but the police found it. At the police station, she had to prove ownership before she was allowed to drive it home.
plain – without decorations or design; simple
* Some people like to t-shirts with different designs but I like mine to be plain.
to identify – to recognize; to see if something fits a certain description or is something or someone you know
* She was sure that she could identify the dog that bit her if she ever saw him again.
unclaimed – not claimed; not taken; without an owner
* In the 10 years that our organization has given out this award, we have never before had a prize go unclaimed.
to dispose of – to throw something away, usually in the garbage; to destroy
* Would you please dispose of that food in the refrigerator? It’s turning green!
finders, keepers – a saying that means that the person who found something gets to keep it, even if it doesn’t belong to them, usually used by children
* The little boy picked up the jump rope off the ground and said to the girl who dropped it, “Finders, keepers!”
to turn up – to be found; to be discovered
* Don't worry about your ring. I'm sure it’ll turn up soon.
never mind – forget what I just said; don’t worry about what I said before
* Are you sleeping? Never mind. That was a stupid question.
Comprehension Questions
1. Why does Lucas call the airport Lost and Found?
a) He wants to apply for a job.
b) He lost his luggage.
c) He lost his keys.
2. Why is Lucas going to the Lost and Found?
a) He is having problems communicating with the person on the telephone.
b) He wants to see if his luggage is there.
c) He wants to invite the airport employee to lunch for being so helpful.
Answers at bottom.
What Else Does It Mean?
to turn up
The phrase “to turn up,” in this podcast, means for something to be found: “I’m sure your cell phone will turn up when they clean up after the party.” This phrase can also be used to mean to arrive: “We weren’t sure if Sarah would make it to the performance but she turned up right before it started.” Or, “I told him that if he didn’t turn up to his own birthday lunch, I would never forgive him.” “To turn up” can also mean to increase something, such as the volume or speed: “Turn up the volume on the radio so we can hear the results of the game.” Or, “You’ll need to turn up the speed on the mixer if you want all of the ingredients to mix well.”
to turn (something) in
In this podcast, the phrase “to turned (something) in” means to give something to someone, usually something that is found but that doesn’t belong to that person: “My sister turned in the money she found under the seat in the bus.” “To turn (someone) in” can also mean to give information, usually about someone who has done something bad: “When I saw the man who robbed the store, I immediately went to the police to turn him in.” Or, “I know that it was Rob who damaged the car but I don’t know if I should turn him in.” The verb “to turn into” can also be used for driving, when someone enters a place or when they turn from going in one direction to suddenly going in another: “The car was driving north when he turned into the parking lot.”
Culture Note
Lost and Founds are usually found in large, public areas with a lot of people, such as airports or museums. But there are also websites that can work as Lost and Founds online. Craigslist.com is an American-based website with pages for different cities and countries in the U.S. and all over the world. Craigslist has an online Lost and Found section for each city or area.
In the Lost and Found section, someone may submit an “advertisement” or announcement that says they have lost an item or a pet. In this “ad,” they will give information describing what they have lost and provide “contact information,” or a way that someone can reach them, such as a phone number or an email address. They may also offer a “reward” (a valuable thing or some money) for the return of this item or pet, to encourage people to look for it or return it. Someone who has found an item may also write an advertisement describing what he or she has found and leave contact information in case the owner finds the ad. It is a very good way to reach many people in a short amount of time.
This is only one feature of the Craigslist website, which serves as online “classified” or small advertisement. There are also sections where people can sell or give away items, look for housing, or different types of jobs. There is even a section to find someone who can do a job or provide a service for you. Similar to many American newspapers with classified sections, there is also a section for the “personals” or personal ads, where people can post announcements looking for a date or a romantic partner.
Comprehension Answers
1 - c
2 - a