= 0244
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 244: Critiquing Someone’s Work.
This is English as a Second Language Podcast episode 244. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com, and download the Learning Guide for this episode. It contains all of the vocabulary, definitions, additional definitions, cultural notes and a complete transcript of this episode.
Our episode is called “Critiquing Someone’s Work.” We'll hear a conversation between two people talking about a third person's work and how it has to be improved. Let's get started.
[start of story]
Noriko: Have you had a chance to look over Russ’s project?
Walt: Yeah, I took a look at it yesterday. If you have a couple of minutes, I can give you my two cents.
Noriko: Sure. Shoot.
Walt: Well, it’s not what I envisioned when we gave him the charge to come up with a new design for the brochure. The cover isn’t bad, but I’m not crazy about the rest of it.
Noriko: Why? What don’t you like?
Walt: Well, I think Russ is off the mark to feature our older products, rather than our new ones. When I saw what he had come up with, I thought he was out in left field. We told him to focus on the latest products, didn’t we?
Noriko: Yes, we did tell him that. I haven’t had a chance to look at the brochure closely myself, but I plan to this afternoon. So you think it needs work, huh? A lot of work?
Walt: Let’s just say that there’s a lot of room for improvement. I’d be happy to meet with him to give him my comments, if you think that would help.
Noriko: Why don’t you hold off until I’ve had a chance to go over the brochure this afternoon. I’ll set up a meeting for tomorrow and we can both give him some feedback on how to proceed.
Walt: That’s okay with me. Thanks for taking the reins on this.
Noriko: It’s no big deal. I’ll let you know later today about that meeting.
[end of story]
The title of this episode is “Critiquing Someone’s Work.” To critique, “critique,” means to criticize - to say what is wrong, sometimes what is right, about someone's work. Usually though, you are telling the person what they did wrong. This is a difficult thing to do, especially with someone that you work with.
Noriko begins by saying to Walt, “Have you had a chance to look over Russ’s project,” Russ is the name of the person about whom they're talking - about his project. To look over means to look at something quickly - to review something quickly - to read it through, usually so you can give an opinion about it. This expression, to look over, has a couple of different meanings; take a look at the Learning Guide today for the additional definitions of this expression.
Walt says, “Yeah” - yes - “I took a look at it yesterday. If you have a couple of minutes,” he says, “I can give you my two cents.” To give someone your two cents, “cents,” means to give someone your opinion - to tell someone what you think. Sometimes we use that expression when we're not sure if the other person wants our opinion; it's also used when we want to say that, well, my opinion may not be the most important or the correct opinion. So, it's a somewhat humble way of saying, “Here is my opinion.” A cent is the same as a penny. In the American dollar, there are 100 cents. So, two cents is not necessarily worth a lot, and that's, again, this idea that, well, I'm not sure if my opinion is worth all that much, but here it is.
Noriko responds to Walt by saying, “Sure. Shoot,” “shoot.” Shoot is an informal way of saying go ahead; continue talking. You're telling someone that you want them to say something - to continue talking about what they want to talk about. You may say to your friend, “I'd like to ask you a question,” and your friend says, “Shoot,” meaning go ahead, ask me your question. Shoot has other meanings in English; again, take a look at the Learning Guide for some additional definitions of this word.
Walt then gives Noriko his opinion. He says, “Well,” Russ's project is “not what I envisioned when we gave him the charge to come up with a new design for the brochure.” To envision, “envision,” means to imagine - to have an idea about how something will be before it is actually done - before it is made. In this case, Walt is envisioning what the project should be, and when he looked at it, it wasn't what he envisioned.
He also uses the expression, “we gave” Russ “the charge to come up with.” When we say, “You give someone the charge,” “charge,” you mean you give them the responsibility - the control over the project. It can also be used as a verb, “I charge you,” but it's sort of an old use of that word. If you say, “I charge you to do this project,” that would be very old-fashioned English. To charge has a couple of other meanings as well. For example, with your credit card to pay for something you charge it. But here, charge as a noun, means responsibility.
Walt says that “The cover” of the brochure - the front of the brochure, “isn’t bad,” meaning it's okay - it's not great - “it isn't bad,” Walt says, “but I’m not crazy about the rest of it” - the rest of the brochure. The expression to be not crazy, “crazy,” about something means that you are not enthusiastic - you don't really like it - you're not happy with something. You can say, for example, “I'm not crazy about that movie” - I don't like it very much. Or, “I'm not crazy about skiing” - I don't like to ski. Actually, I don't know how to ski, so maybe I would like it if I tried it.
Noriko asks Walt why he doesn't like Russ's project. He says, “Well, I think Russ is off the mark to feature our older products.” To be off the mark, “mark,” means to be wrong - to be incorrect. Usually, it means that someone didn't quite understand what was needed or expected - wasn't able to do when he should have done. So, off the mark is wrong - it's incorrect. Walt is saying that Russ's use of the old products from their company in the brochure was “off the mark,” it was a wrong decision.
He says, “When I saw what he had come up with, I thought he was out in left field.” To come up with something means to make something - to create something or to think of something. You may say, “I've come up with some ideas about how to improve ESL Podcast” - I've thought about it - I've created or made in my mind some ideas. You can also, come up with something that is physical, “I came up with a new kind of pencil that always writes, it never runs out of lead,” “lead,” which is what the pencil uses to make its mark on the paper.
Walt thinks that Russ is “out in left field.” To be out in left field means to be crazy - not rational - not logical, in this case, probably not very useful - not very effective. Someone says, “Oh, I want to run my car on water instead of gas.” You may say, “You are out in left field” - you're crazy - you have the wrong idea. I am told this many times!
Noriko says well, “we did tell him” to use the latest products. “I haven’t had a chance to look at the brochure closely,” she says, and then she asks Walt, “So you think it needs work, huh.” To need work means it needs improvement - it needs to get better. “My car really needs work,” that means there's something wrong with it, it needs to be fixed - it need to be made better.
Notice that Noriko uses a very common way of asking a question, “huh,” which we normally spell, “huh.” It's sort of an informal word. You may say to someone, “You don't really want to go the movie, huh?” It's a way of asking a question.
Walt says, “Let’s just say that there’s a lot of room for improvement.” The expression, let's just say that, is one we use when we are introducing an opinion about something that is going to be less strong then what you really think, we would use the word understatement. An understatement is that you say something is not as bad as you really think it is or you are not expressing your opinion as completely as you could. So Walt says, “Let’s just say that there’s a lot of room for improvement.” When we say something has room for improvement we mean that it is not perfect - it can be made much better.
Walt says, “I’d be happy to meet with” Russ and “give him my comments, if you think that would help.” Your comments are your suggestions - something that you tell someone that, in this case, will help them make it better.
Noriko says, “Why don’t you hold off until I’ve had a chance to go over the brochure this afternoon.” When you tell someone to hold, “hold,” off (two words), you're telling them to wait and do what they are planning on doing later. You're asking them to delay it - to wait before they do it. So, Noriko's asking Walt to hold off, to wait until after she has read through the brochure.
She says, “I’ll set up a meeting for tomorrow and we can both give” Russ “some feedback on how to proceed.” Feedback, “feedback,” is giving your opinion about something - telling someone if it is good or if it is bad and, often, how to make it better.
Walt says, “That’s okay with me. Thanks for taking the reins on this.” The expression to take the reins, “reins,” means to be in control of something - to take the leadership - to be in the lead or to lead something. In this case, Noriko is taking over - taking the lead with this project with Russ. The word reins refers to what you use to control a horse. When you are riding on a horse and you want the horse to stop or to go left or go right, you use the reins that are attached to the horse to control it. So, when you take the reins, that means you are taking control - you are taking command of something.
Noriko says to Walt, “It’s no big deal. I’ll let you know later today about the meeting.” A big deal is something that’s very important. So, when someone says, “It's no big deal,” they mean it's not very important.
Now let's listen to the dialogue, this time at a normal speed.
[start of story]
Noriko: Have you had a chance to look over Russ’s project?
Walt: Yeah, I took a look at it yesterday. If you have a couple of minutes, I can give you my two cents.
Noriko: Sure. Shoot.
Walt: Well, it’s not what I envisioned when we gave him the charge to come up with a new design for the brochure. The cover isn’t bad, but I’m not crazy about the rest of it.
Noriko: Why? What don’t you like?
Walt: Well, I think Russ is off the mark to feature our older products, rather than our new ones. When I saw what he had come up with, I thought he was out in left field. We told him to focus on the latest products, didn’t we?
Noriko: Yes, we did tell him that. I haven’t had a chance to look at the brochure closely myself, but I plan to this afternoon. So you think it needs work, huh? A lot of work?
Walt: Let’s just say that there’s a lot of room for improvement. I’d be happy to meet with him to give him my comments, if you think that would help.
Noriko: Why don’t you hold off until I’ve had a chance to go over the brochure this afternoon. I’ll set up a meeting for tomorrow and we can both give him some feedback on how to proceed.
Walt: That’s okay with me. Thanks for taking the reins on this.
Noriko: It’s no big deal. I’ll let you know later today about that meeting.
[end of story]
The script for today's episode was written by Dr. Lucy Tse.
If you have a question, comment or suggestion, send us an email. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to look over – to quickly review something; to quickly read something to give one’s opinion about it
* Do you think you’ll have time this afternoon to look over this report before I give it to the company president tomorrow morning?
to give (someone) (one’s) two cents – to let someone know what one thinks about something
* Nicole gave me her two cents about my ideas, but I just don’t agree with her.
shoot – go ahead; continue; a word used to let someone know that one wants the other person to say or do something
* Anis, I’d like to hear your thoughts about this project. Shoot.
to envision – to imagine; to have an idea about how something will be before it is made or happens
* When she planned their vacation, she had envisioned a week of resting on the beach, but her husband wanted to go to a different museum everyday.
charge – responsibility for some work or project; control over a project
* Why did Zayed give Bill charge of the new account? Everyone thought Clarrisa would lead the project.
to not be crazy about (something) – to not like something; to not be pleased with something
* Rachelle wasn’t crazy about the idea of going to Florida for Christmas, but her husband and children really wanted to go.
off the mark – wrong; incorrect; not matching what is needed or expected
* Your comments to Anita about her behavior at the ceremony were really off the mark. I don’t think she behaved inappropriately at all.
to come up with something – to make something; to create something; to produce something; to think of something
* Yung came up with a great way to increase the company’s sales.
out in left field – not rational or logical; crazy; not useful or effective
* When he was younger, everyone said that his business ideas were out in left field, but today he’s a millionaire!
to need work – to need improvement; to not be finished or completed
* The story is interesting, but the ending still needs some work.
Let’s just say that... – An expression meaning that the words that follow are an understatement (the feelings are stronger than the words)
* Do I want to make more money? Let’s just say that I wouldn’t say “no” if the company offered it to me.
room for improvement – not perfect; can be improved
* Even though everyone said that her paintings were beautiful, the artist still saw room for improvement.
comment – something that is said or written to give one’s opinion about something
* Don’t you know that you should never make a comment about a woman’s weight or age?
to hold off – to wait to do something later; to delay something
* I know we had planned to study for the exam tonight, but can we hold off until tomorrow? I’m really tired.
feedback – one’s opinion about whether something is good or bad and how it can be improved
* Receiving negative feedback is difficult, but it’s usually helpful.
to take the reins – to lead something; to be in control of something
* When Danitsa got sick, her co-worker had to take the reins on all her projects.
big deal – something that is very important
* Graduating from a university with honors is a big deal. You must be so proud of your granddaughter!
Comprehension Questions
1. What does Walt like best about Russ’s new design for the brochure?
a) The left field.
b) The featured old products.
c) The cover.
2. Why does Walt thank Noriko?
a) Because she is going to give Russ all of Walt’s feedback.
b) Because she is going to arrange a meeting with Russ.
c) Because she is giving Walt very good feedback.
Answers at bottom.
What Else Does It Mean?
to look over
The phrase “to look over (something),” in this podcast, means to quickly review a written document to give one’s opinion: “Clementine looked over hundreds of resumes before she decided to interview these three candidates.” The phrase “to look into (something)” means to examine or investigate something: “Is anyone looking into the reasons why students don’t graduate?” The phrase “to look back on (something)” means to think about something that happened in the past: “Looking back on my childhood, I can clearly see how wonderful my parents were.” The phrase “to look ahead to (something)” means to think about something that will happen in the future: “Kristin is only 12 years old, but she’s already looking ahead to college.” The phrase “to look forward to (something)” means to think with pleasure or happiness about something that will happen in the future: “We’re all looking forward to our summer vacation in Hawaii.”
shoot
In this podcast, the word “shoot” is used to let someone know that one wants him or her to say or do something: “Ivan, it’s your turn. Shoot!” The word “shoot” is also used to show disappointment or frustration: “Oh, shoot! I left my jacket at the office.” As a verb, “to shoot” means to use a gun: “The policeman shot the criminal in the leg” (“shot” is the past tense of “shoot”). “To shoot” can also mean to make a movie or a photograph: “Where did you shoot this photo?” “To shoot down” means to disapprove of or say no to someone’s idea: “At the meeting, Erma wanted to change the project deadline, but Irma shot down that idea right away.”
Culture Note
CULTURE NOTE
In the United States, most companies have similar “corporate structures,” which are the titles and positions of the people who work in the company. A company is led by a “board of directors,” a small group of people who have responsibility for the company, but do not work there every day. The “board of directors” manages the company “president,” who has more responsibility than anyone else who works in the company.
The president usually works closely with the CEO (chief executive officer), CFO (chief financial officer), COO (chief operating officer), and CIO (chief information officer). In a very large company with “many locations,” or offices in different places, there are also “regional managers” who are responsible for the company’s work in each “region” or area, such as the West Coast or the South.
Each region has many stores or “branches” (office locations). Each of these locations has a “store manager” or “branch manager” who is responsible for all the business in that location. The branch manager or store manager “hires” or selects people for the jobs in the branch or store.
A large company often has many “management layers,” meaning that the lowest employee and the president are separated by many managers. This can make communication difficult, and many companies are now trying to reduce the number of management layers that they have.
One good thing about working for a large company with a “standard” or normal corporate structure is that if you do your work well, it is relatively easy to “move up” in the company and get a better job with more responsibility and a higher salary.
Comprehension Answers
1 - c
2 - b