= 0245
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 245: Characteristics of an Ideal Mate.
This is English as a Second Language Podcast number 245. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and take a look at our new ESL Podcast Store. There are several good premium courses there we think you may be interested in, both business and personal English. Of course, you also want to download the Learning Guide for this episode that gives you all of the words, definitions, cultural notes and a complete transcript of this episode.
The topic of this episode is “Characteristics of an Ideal” - or perfect - “Mate.” A mate, “mate,” is someone that you are boyfriend or girlfriend or husband or wife with. We're going to listen to a conversation between two people talking about what they would look for in the perfect boyfriend or girlfriend. Let's get started.
[start of story]
I’ve been trying to set up my good friend, Rachid, with one of my single girlfriends, but I still wasn’t too sure what his type would be.
Tamara: So, tell me what you’re looking for in a woman.
Rachid: She has to be rich and hot!
Tamara: Come on! Be serious.
Rachid: Okay, okay, but I don’t know why married people are always trying to get their single friends married off. Is it because misery loves company?
Tamara: Stop being a smart aleck and answer the question.
Rachid: All right. I’m being serious now. What do I look for in a woman? I’d like someone who has a good sense of humor, someone who is kind-hearted and easy to talk to, and is supportive of me.
Tamara: What about vital statistics? Age, physical type?
Rachid: She has to be pretty, but I’m not too picky about whether she’s a blond, brunette, or redhead. She should be my height or shorter, and around my age or a few years younger or older.
Tamara: That helps a little to narrow down who may be a good match for you. Any deal killers?
Rachid: I don’t like women who are too chatty or who are too bossy. Otherwise, I have a pretty open mind when it comes to women.
Tamara: Okay, I can think of at least a couple of friends who may be willing to put up with you.
Rachid: Put up with me? Are you kidding? I’m a catch!
Tamara: Oh, geez. Finding somebody for you is going to be harder than I thought!
[end of story]
We listened to a dialogue between two people talking about their ideal, “ideal,” or perfect mate - person they would want to have as their boyfriend, girlfriend, husband or wife.
The dialogue begins by Tamara saying that she's “been trying to set up” her “good friend, Rachid, with one of” her “single girlfriends.” To set someone up means, in this dialogue, to help two people meet so they can begin, perhaps, dating each other. If you think two people may like each other, you may try to set them up - try to arrange a meeting between them so they can have a chance to talk and to get to know each other. To set up someone, or to set someone up - either way is correct - has a couple of different meanings, and you want to take a look at our Learning Guide today for those additional definitions.
So, Tamara is trying to set up her friend - her male friend - Rachid, but she wasn't sure what Rachid's type was. When we say that “She's my type,” or “He's not my type,” “type,” we mean the ideal characteristics - the personality, the physical appearance that you are looking for in a person with whom you want a romantic relationship. So, some people like tall men or women; some people like short men or women; some people brown hair; some people like blond hair; some people - well, not very many people - like bald men. That's too bad for me!
Well, Rachid is going to describe to Tamara what his type is - what he likes in a woman. So, Tamara begins by saying, “So, tell me what you’re looking for in a woman” - how would you describe the perfect woman for you.
Rachid is a very typical man, he says, “She has to rich and hot!” To be rich, you know, means to have a lot of money. So, he wants a woman - a girl - with a lot of money, and she has to be hot, “hot.” When you use the word hot to describe a person, you mean they are very attractive - they're very sexy - they're very good looking. I have never been described as being hot!
But Rachid is looking for a woman who is hot, and Tamara says, “Come on! Be serious.” Rachid is kind of joking here, since that's the answer that every man would say - he wants his girlfriend to be rich and attractive. Tamara uses the expression “Come on,” meaning stop doing that - stop saying that, “Be serious” - tell me what you really think.
Rachid then says, “Well, that is what I really think” - no! He says, “Okay, okay, but I don’t know why married people are always trying to get their single friends married off.” Tamara is married; Rachid is single. To marry someone off means to get them to be married - to get them married. “Is it because misery loves company?” Is it because people who are unhappy like to be with other people who are unhappy, assuming that married couples are unhappy.
Tamara says, “Stop being a smart aleck and answer the question.” A smart, “smart,” aleck, “aleck,” is someone who does not give serious answers - tries to always be funny - tries to be - give funny answers. I have been described as a smart aleck, for example.
Rachid says, “All right. I’m being serous now. What do I look for in a woman? I’d like someone who has a good sense of humor.” To have a good sense, “sense,” of humor means that you can make other people laugh and enjoy laughing and telling jokes. Recognizing the funny things in life; that's to have a good sense of humor.
Rachid also wants a woman “who is kind-hearted and easy to talk to.” To be kind-hearted, “kind-hearted,” means to be nice - to be kind - to be generous. To have a kind heart means to be a nice person. He also wants a woman who is “easy to talk to,” someone he can have conversations with - someone who will talk to him and interested in talking to him, someone he is comfortable speaking with. He also says that he wants a woman who “is supportive of” him. To be supportive, “supportive,” means to give help - to give advice, or to be willing to help someone, and that's what Rachid wants in his future wife.
Tamara says, “What about vital statistics? Age, physical type?” The expression vital, “vital,” statistics is a word we - or expression we normally use to describe someone's physical appearance - how old they are, their height, their weight, their hair color. The expression means something a little different in a hospital. When the doctors want to know the vitals - or the vital statistics - they're usually looking for things like the heartbeat and the pulse - other indications of how the body is doing. But here it means the physical appearance of the person.
Rachid says that “She has to be pretty, but I’m not too picky about whether she’s a blond, brunette, or redhead.” A blond is a woman, of course, with yellow, light hair; a brunette has dark hair, and a redhead has red hair. My niece is a redhead, for example. She's not married, so if you are between the ages of 18 and 25, email me and I'll - I'll set you up if your type is redheads!
Rachid says he's not picky, “picky.” To be picky means to be very difficult to please - somebody who only wants a very specific type and doesn't like anything else. A person who is picky might, for example, only like certain kinds of food. It's usually a negative adjective to describe someone as picky.
Rachid says that “She should be my height or shorter, and around my age or a few years younger or older.” So, he doesn't want anyone who's 20 years older, and he wants someone who's more or less his height or a little shorter than him.
Tamara says, “That helps a little to narrow down who may be a good match for you.” To narrow, “narrow,” down something (two words) means to go from a large number of choices to a very small number. To narrow down means to eliminate some options - some choices - so that you can focus or concentrate on a smaller number. “We need to narrow down the number of people we are going to interview for this job.” You may have 100 people who want the job - who apply for the job - but you can only interview 10, so you have to narrow down the list of people to 10 people.
Tamara says that Rachid's description helps “narrow down who may be a good match for” him - who would be a good person for him. Then she asks him, “Any deal killers?” A deal, “deal,” killer, “killer,” is something that would make someone decide not to do something - not to accept something. So, Tamara's asking if there's anything that he absolutely would not want in his ideal mate. That would be something that would be something that would make him say no - “a deal killer.” A deal is an arrangement and an agreement, usually. You don't often hear that expression in talking about people, but about business deals, for example. But Tamara, here, is using it to describe the potential negative characteristics that would make Rachid say no.
Rachid says, “I don’t like women who are too chatty or who are too bossy.” To be chatty, “chatty,” means to talk a lot. You may have seen on the Internet chat rooms, “chat,” these are places where you talk. So, chat is just another word for talking. Chatty is somebody who talks a lot. Bossy, “bossy,” is someone who likes to tell other people what to do - likes to give orders. So, Rachid doesn't want a woman who's chatty or bossy. I'm with Rachid!
Rachid also says, “I have a pretty open mind when it comes to women.” To have an open mind, “open,” open - I know I sometimes pronounce that “ompen,” with an “m” in there, that's my Minnesota dialect - to have an open mind means to be willing to consider many different things - to be flexible - to be the opposite of picky.
Tamara says, “Okay, I can think of at least a couple of friends who may be willing to put up with you.” To put up with someone means to tolerate - to be able to be with someone even though they are difficult to be with. Tamara, here, is joking with Rachid.
Rachid says, “Put up with me? Are you kidding” - are you joking? “I’m a catch,” “catch.” To say someone is a catch means that they are a person who is very desirable, that many people would want to marry or, in the case of an employee, that a company would want to hire. Normally it's used in talking about someone who would be good to marry. If you say, “I'm a catch,” you're saying lots of people would want to marry me because I am so good. So, Rachid is not very humble! He thinks very highly of himself; he has a high opinion of himself.
Tamara says, “Oh, geez,” meaning ugh! It's an expression to mean that you dislike what the other person said. “Finding somebody for you is going to be harder than I thought,” she says.
Now let's listen to the dialogue, this time at a native rate of speech
[start of story]
I’ve been trying to set up my good friend, Rachid, with one of my single girlfriends, but I still wasn’t too sure what his type would be.
Tamara: So, tell me what you’re looking for in a woman.
Rachid: She has to be rich and hot!
Tamara: Come on! Be serious.
Rachid: Okay, okay, but I don’t know why married people are always trying to get their single friends married off. Is it because misery loves company?
Tamara: Stop being a smart aleck and answer the question.
Rachid: All right. I’m being serious now. What do I look for in a woman? I’d like someone who has a good sense of humor, someone who is kind-hearted and easy to talk to, and is supportive of me.
Tamara: What about vital statistics? Age, physical type?
Rachid: She has to be pretty, but I’m not too picky about whether she’s a blond, brunette, or redhead. She should be my height or shorter, and around my age or a few years younger or older.
Tamara: That helps a little to narrow down who may be a good match for you. Any deal killers?
Rachid: I don’t like women who are too chatty or who are too bossy. Otherwise, I have a pretty open mind when it comes to women.
Tamara: Okay, I can think of at least a couple of friends who may be willing to put up with you.
Rachid: Put up with me? Are you kidding? I’m a catch!
Tamara: Oh, geez. Finding somebody for you is going to be harder than I thought!
[end of story]
The script for today's podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to set up (someone) – to help two people meet and begin dating each other because one thinks that they will like each other
* Her aunt always sets her up with men who are almost twice her age!
type – the ideal characteristics (personality and physical appearance) that one wants to find in another person for a romantic relationship
* Romulo’s type has always been the same: tall, red-haired, and very intelligent.
rich – wealthy; with a lot of money
* Bill Gates, the founder of Microsoft, is a very rich person.
hot – very attractive and sexy
* Every woman I know thinks that Brad Pitt is hot.
smart aleck – someone who does not give serious answers, but instead gives funny answers, making it difficult to talk with him or her
* Why are you such a smart aleck? I wish you would be serious sometimes.
sense of humor – the ability to make other people laugh or to recognize funny things in life
* Janine has a great sense of humor. She’s always making other people laugh, even in difficult situations.
kind-hearted – kind; nice; generous
* Today I saw Denise do a very kind-hearted thing. She bought breakfast for an old man who was sleeping on the streets and then helped him buy a new jacket.
easy to talk to – comfortable to speak with; not difficult to have a conversation with
* He’s shy with most people, but his is roommate is so easy to talk to that sometimes they stay awake until 4:00 a.m. talking about life.
supportive – giving help, support, and advice; willing to give help, support, and advice
* Cheryl’s parents are very supportive of her decision to study in Africa.
vital statistics – the physical appearance of someone, including age, height, weight, hair color, and other things
* The modeling agency has the vital statistics of each of their models, so that they can find the right person for each modeling job.
picky – difficult to please, because one wants only a certain type of something
* Little children are often picky eaters. For example, they might not want to eat green foods or they might not like to eat meat.
to narrow down – to go from a large number of choices to a small number of choices
* At first, Yoko was considering all the universities in the state, but now she has narrowed down the list to just three schools.
deal killer – something that makes one decide not to do or accept something
* They were going to offer Marshal the job, but the deal killer was his demand for 10 weeks of vacation each year.
chatty – very talkative; talking a lot about things that are not very important
* Eri is very chatty, so there is never a moment of silence when we’re together.
bossy – likes to give orders; likes to tell other people what to do
* Jubel’s older brother is so bossy! He’s always telling him what to do and how to do it!
open mind – willingness to consider many different things; flexible; not close-minded
* Polly has an open mind and is willing to try almost any type of foreign food, from Tanzanian to Mongolian!
to put up with (someone) – to tolerate someone; to deal with someone; to be able to be with someone even though it is difficult to be near him or her
* How can you put up with Ron? He’s the most annoying person I know.
catch – a person who is good for something, such as marrying or working in one’s company
* Kenuke is a great catch. He’s intelligent and good-looking, he has a great job, and he treats other people nicely.
Comprehension Questions
1. What kind of woman is Rachid looking for?
a) Tall and blond.
b) Kind-hearted and supportive.
c) Chatty and bossy.
2. Why doesn’t Tamara date Rachid?
a) Because she is married.
b) Because he is a smart aleck.
c) Because he is a catch.
Answers at bottom.
What Else Does It Mean?
to set up
The phrase “to set up (someone),” in this podcast, means to help two people meet and begin dating each other because they are likely to like each other: “Hugh and April were set up on a date by their friends and a year later they were married!” The phrase “to set (something) up” can mean to schedule something: “She set up the meeting for Tuesday afternoon at 4:30.” It can also mean to build something so that it is ready for an event: “They’re setting up the chairs for the Governor’s speech in the park.” The phrase “to set (something) down” can mean to place something on a flat surface: “Please don’t set your drink down near the computer.” The same phrase can also mean to make a rule: “The teacher sets down the rules for her students on the first day of classes.”
catch
In this podcast, the word “catch” means a person who is good for something, such as marrying or working in one’s company: “I think Janette is a great catch, so I don’t understand why men aren’t very interested in her.” A “catch” can also be a hidden disadvantage of doing something: “This website says that I can earn $2 million a year by working from home, but there must be a catch.” A “catch” is also the act of catching something in your hands while it is moving in the air: “Leonardo made a great catch and his baseball team won the game!” As a verb, “to catch” usually means to stop an object that is moving in the air: “My dog likes to catch balls whenever we go to the park.”
Culture Note
In the United States, most men and women who want to find a “mate” (a person to have a serious romantic relationship with) are looking for a person with specific “characteristics.” A “characteristic” is something that describes a person, such as physical appearance (such as tall or short), personality types (cheerful or serious), or favorite activities.
One characteristic that many men and women look for is “sincerity.” A “sincere” person is someone who is honest and direct about what he or she feels and thinks. Another common characteristic that many people look for is “ambition.” An “ambitious” person is someone who has strong career goals and wants to do very well in his or her work.
Other people are more interested in “financial security,” which means that they don’t want to worry about money. These people look for a mate who has a good job and does not spend money on unnecessary things.
Many American men and women say that they want a mate who has a “sense of adventure” and is willing to take risks and do things that are unusual. Someone with a sense of adventure may enjoy traveling to different places or participating in unusual sports.
Reading the “personal ads” is a good way to learn more about the characteristics that American men and women look for in a mate. Most newspapers have a small section of “personal ads” where people list the characteristics that they are looking for in a mate. Then, if a reader believes that he or she is a good catch, he or she can answer the personal ad to meet that person.
Comprehension Answers
1 - b
2 - a