= 1816
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 511.
This is English as a Second Language Podcast’s English Café episode 511. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide right after you become a member of ESL Podcast. You can also take a look at our ESL Podcast Store. And if you’re on Facebook, well, please go to facebook.com/eslpod and like us, because you know we like you.
On this Café, we’re going to talk about a famous animated or cartoon movie from the 1990s, Toy Story. We’ll also talk about the United States Naval Academy. And as always, we’ll answer a few of your questions. Let’s get started.
In 1995, the company Pixar did something that no one had ever done before. They released, or showed to the public, a full-length film that was completely computer animated. A “full-length film” is a complete movie, usually defined as longer than 40 minutes. When we say something is “animated” (animated), we mean it’s created using a method of showing a series of images or drawings and putting them together to make it appear as though the characters were moving. Something that is “computer animated” is something that is created entirely from a computer.
In the old days before computer animation, people would draw on a piece of paper thousands and thousands of little drawings and put them together in order to produce a cartoon. But with computers, it was now possible to do everything on the computer. And that is why Toy Story is so important, because it changed the way that animated movies, or cartoon movies, were made.
How long does it take Pixar to make one of these movies? Well, a very long time – three to four years, apparently. This is because they have to make sure that the movie is perfect. The process of making an animated movie – really, any movie – begins with a script, begins with the words that the characters in the movie will say.
Most movies also start with a storyboard. A “storyboard” (storyboard) is a collection or set of drawings that give you an idea about what’s going to happen in each part of the movie, in each scene of the movie. They don’t show the entire movie. They don’t illustrate or show you everything that’s going to happen, but it gives you an idea of what’s going to happen. That’s what a storyboard does.
In the case of Toy Story, Pixar hired two very famous actors, by the names of Tom Hanks and Tim Allen, to do the voices of the two main characters: Woody and Buzz Lightyear. The actors were actually filmed reading the script, although you don’t necessarily have to film them. Really all you need are their voices, because the voices are then, of course, combined with the animation.
However, Pixar films the stars reading the lines because they actually take some of their movements and make the animated characters do those same movements. After the recording, then, the characters are animated. They’re added, and then you add music and other sounds, and you have a movie.
Toy Story, if you have not seen it, is the story of a young boy’s toys, told from the toys’ perspective. “Perspective” (perspective) refers to your point of view – the way that you would see something. Of course, toys aren’t alive. They’re not actually little human beings, but of course this is a movie and this is Hollywood, so anything is possible. And in Toy Story, the toys are like little people. They talk. They think. They move of their own “volition” – that is, on their own, without being moved by a human being.
Now, the main characters in Toy Story include a cowboy named Woody and an astronaut named Buzz Lightyear. A “cowboy” (cowboy) is actually not a boy, but a man who takes care of animals, usually riding a horse in the process. Out here in the western part of the United States, there are still a lot of cowboys who take care of animals on large farms. Buzz Lightyear is the other main character in the movie, and he’s an “astronaut” (astronaut). An astronaut is a person who, of course, goes out into space, who leaves the earth and goes out away from the earth into what we would call “outer space.”
Now, the story begins with the birthday of the young boy. The boy is named Andy. Andy is the one who owns these toys. Woody and the rest of the toys are trying to find out what Andy will get as presents for his birthday, and they learn that he’s going to get a new toy. The new toy is this astronaut, Buzz Lightyear. Well, unfortunately, Woody and Buzz don’t like each other, and Andy, the young boy, starts to play with the new toy – as boys will do – Buzz Lightyear more than his old toy Woody. This makes Woody sad and a little jealous of Buzz.
Now, this new toy – the astronaut Buzz Lightyear – thinks he’s really an astronaut and thinks that he has a mission to get back into outer space. A “mission” (mission) is some goal or task that you must complete. Businesses nowadays often talk about their “mission statement.” It’s a statement of what the goals, values, perhaps ideals of the company are. But here when we say “mission,” we’re talking about some specific project that in this case Buzz wants to accomplish. He wants to go back into outer space. We often use the word “mission” in a military context to talk about a particular movement and objective of an army or a navy.
Now, during one part of the movie, Woody accidentally pushes Buzz out of a window so that Buzz falls down onto the ground outside the house. Some of the other toys think that Woody was trying to kill Buzz or murder Buzz, but he wasn’t. I mean, this is a movie for children primarily, so we’re not going to see any murders. Well, Andy, the young boy, comes in to find Buzz, but he doesn’t see Buzz because of course Buzz is not in the little boy’s room anymore. So Andy takes Woody with him to a restaurant, a pizza restaurant.
Now remember, in the movie the toys can move on their own, and Buzz actually manages to get to the restaurant by going in the car of Andy’s mother. So now everyone’s at the restaurant, and inside the restaurant there is a game that looks like a spaceship. A “spaceship” is a special vehicle that takes people off into outer space. Now remember, Buzz thinks that he’s a real astronaut, so he gets into the spaceship thinking that he’s going to go back to where he belongs.
Well, lots of other funny things happen, but eventually Buzz and Woody both get taken by another boy, a mean boy by the name of Sid. Well, Sid doesn’t treat his toys very well – very different from Andy in that respect. Buzz and Woody are scared of the other toys in Sid’s house and so they escape. They get out of Sid’s house. “To escape” (escape) means to break free from the person who is keeping you in a certain place against your wishes. We sometimes – not often, I hope, but sometimes – talk about prisoners escaping from prison. They are able to get out of the prison when they aren’t supposed to.
In the movie, Buzz and Woody escape and Buzz sees a commercial on the television. Now, I don’t want to give you the whole movie, but the commercial makes Buzz depressed. “To be depressed” means to be very sad, to be very unhappy, often for a long time. However, once again, this is a movie for children, and so of course it’s going to have a happy ending, and it does. How does it end? Well, you’ll just have to go and see Toy Story.
Toy Story became a very popular movie. In fact, they made three more Toy Story movies after the original movie. The movie also won an Oscar, an Academy Award, in 1996. It was actually a special award called a “Special Achievement Award” to honor and recognize this accomplishment that Pixar had achieved by making an entire movie with computer animation.
And I said they made three more Toy Story movies – actually, the fourth Toy Story movie has not yet been released at the time of this recording, which is 2015. But my guess is that will be successful and there’ll be many other Toy Story movies in the future. The movie will show Woody, Buzz, and Andy’s other toys 22 years after the first Toy Story movie. I guess all of the children who watched the movie are now adults, and so they’ll want to find out what happened to the toys. I’m not sure why, but there it is.
Toy Story was the first of many successful computer-animated movies including Cars, Monsters, Inc., and Finding Nemo. So if you have young children, you will probably be familiar with these movies. Now, the smart thing about these movies nowadays is that the people who make them make them interesting for adults as well, so that both children and adults can laugh at the movie. Of course, a lot of the jokes that the adults laugh about are not the same ones as the children laugh at.
Let’s turn now to our second topic, which is the United States Naval Academy. The United States Naval Academy is located in the city of Annapolis is in the state of Maryland. Maryland is on the East Coast of the United States, right next to our nation’s capital, Washington, D.C. The U.S. Naval Academy was founded, or began, in 1845 by the then secretary of the Navy, George Bancroft.
Now, we call it an “academy.” An “academy” is used in a couple of different ways when we’re talking about schools. An academy can be a school for high school children, often rich high school children. But in the military, the word “academy” is used to describe a college or university where the very best or smartest people who want to go into the military often attend. We have a U.S. Army Academy called West Point. Well, this is the U.S. Naval Academy.
“Naval” (naval) refers to ships and boats. It is related to the word “navy,” which is the part of the military that is responsible for protecting the seas and the oceans. There’s another part of the U.S. military that is closely associated or connected with the Navy, and that is the Marine Corps. The Marine Corps basically are the fighters that go onto the naval ships in order to do whatever it is the military is going to do.
The Naval Academy, then, is like a college or university. There are traditional academic subjects that are studied, but in addition, a member or student at the Naval Academy also studies military leadership. The military academies are supposed to train the future leaders of the military, and so the Naval Academy, of course, is training future leaders of the Navy.
When the academy first opened back in the nineteenth century, only the first year and the last year were spent at the school. During the other years, the students would go onto actual ships to do military work. However, they changed that way of doing things fairly quickly so that the students were spending four years studying at the Naval Academy and only going on the ships during the summertime.
I mentioned that the naval academy teaches both traditional academic subjects as well as military leadership. The classes are taught by a faculty. A “faculty” (faculty) is the group of teachers. We use that word “faculty” to refer to the teachers at any school, really, even a high school or a grade school. All colleges and universities have faculties. I was a faculty member at a couple of different universities.
The military leadership part of the student’s education at the U.S. Naval Academy is all overseen, or directed, by a person known as the “Commandant of Midshipmen.” A “commandant” is a military officer in charge of a certain position. An “officer” (officer) is a person in charge of a certain group of the members of a military organization, although we use the word “officer” in situations outside of the military as well, to describe the leaders of a certain group.
A company usually has officers: a president, a vice president, a treasurer (who handles the money), a secretary – these are officers of the company. But in the military, an “officer” is a leader in the military. The word “midshipmen” refers to students in the U.S. Naval Academy who are training to become officers.
Students also take classes in naval history, military law, leadership, and navigation. “Navigation” is the process of finding out where you are – what your position is on a map – and planning how you’re going to get to where you need to go. Once again, we use this word in other situations outside of a military context. You can talk about “navigating,” using the verb form, from one place to another using your phone or tablet in your car.
Now, I know some of you are listening to this description of the U.S. Naval Academy and are saying to yourselves, “Hey, how do I become a member of the U.S. Naval Academy?” Well it’s not as easy as it sounds. The first thing you need to do is become a citizen of the United States, since only citizens can attend the Naval Academy.
You have to be between the ages of 17 and 22 when you start studying at the Naval Academy. And you have to be unmarried when you first begin your schooling. Now, I don’t qualify to be a student at the Naval Academy. I’m older than 22 and I’m married, although that could change. I am a U.S. citizen, however, so I have one of those three qualifications.
Until 1976, only men were accepted into the U.S. Naval Academy, but with the change in society during the 1970s, the academy began to accept women. In fact, I knew someone from my high school who was one of the first women to be accepted into the U.S. Naval Academy back in the late 1970s. I think it was 1977. However, it has been or was very difficult for women to study at the Naval Academy since there were so few of them, and in fact I don’t think this woman continued. I don’t think she graduated from the U.S. Naval Academy. She was one of the smartest students in her class at the high school.
Anyway, since 1976, both men and women can study at the Naval Academy. I’ve been referring mostly to members of the Navy, but there are also officers in the Marine Corps (or future officers) that study at the Naval Academy. When you graduate from the Naval Academy, you are given a certain title, and that is “ensign” (ensign). If you are going into the Marine Corps, they call you a second lieutenant. Those are the lowest levels of officers in the Navy and Marine Corps.
Several famous people have graduated from the Naval Academy, including one of our presidents, President Jimmy Carter; one of the people who wanted to become president, Senator John McCain; and someone who also wanted to become president but wasn’t successful, a famous businessman by the name of H. Ross Perot. The astronaut Alan Shepard graduated from the Naval Academy, as did a famous professional American football player by the name of Roger Staubach.
It is very difficult to get into the U.S. Naval Academy. In fact, it’s difficult to get accepted to any of the military academies since there are only so many positions that are available in these universities.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Amir (Amir) in Iran. Amir wants to know the meanings of three words that are all related – “buddy,” “chum,” and “pal.”
All three of these words refer to someone who is a close friend of yours. They’re informal words for the most part. The least common one, at least in American English, would be “chum” (chum). We don’t use this word very much anymore, but most Americans know what it means. It means the same as “buddy” and “pal.” The second least common of these three would be “pal” (pal). A pal is a close friend, but we would probably not use it all that often anymore. But again, it’s a word that most Americans know and recognize.
The most common of the three is probably “buddy.” However, even here, it’s a word that you would use describing your son or daughter’s friend or the friends of your children more than your own personal friend. We might say it almost in a joking way. “Oh, yeah. He’s my buddy.” It’s a word that is normally used when talking about younger children and their friends. There are a couple of uses of “buddy” and “pal,” however, which are somewhat common in the speech of adults when they’re speaking English, but they mean something a little different.
Sometimes we use the word “buddy” or “pal” when we see someone that we don’t know or don’t recognize and are perhaps a little angry with the person. It’s often used right before you get into a fight with someone, which of course I don’t recommend doing. So if you refer to a man – a grown man, an adult – as a “buddy,” usually you’re saying it in some way that indicates that you are angry or irritated at that person. You have to be careful, then, in using these terms.
So for example, if you’re at a baseball game and the person behind you, the man behind you, is getting drunk, drinking too much beer, and he starts yelling and screaming, you might turn around (if you are bigger than the man) and say, “Hey, buddy, could you stop shouting so much?”
You could also say, “Hey, pal, could you stop shouting so much?” “Buddy” is probably even here a little more common than “pal,” but it’s definitely a word that might get you into trouble if you use it with someone. And we would only use it with someone whose name we don’t know but whose actions are making us mad or are irritating us.
Our next question comes from the Vitalik (Vitalik) in Russia. The question has to do with the difference between “fee” (fee) and “pay” (pay). “Fee” is a noun that refers to the amount of money you have to give someone for some service or for something that you are going to get a benefit from.
So, for example, if you are going to visit a national park here in the United States, usually you have to pay a fee. After giving money to the government in order to go into the park, you also have fees for things such as your credit card. The bank charges you what we would call a fee if you don’t pay all of the money on your bill by the end of the month or if you are late paying your bill. In fact, we would call those “late fees” – money you have to pay because you didn’t pay on time.
“Pay” is both a verb and a noun. It’s more commonly used as a verb which means to give money to someone for something – either a product, a physical thing, or a service. “Pay” can be used as a noun, however, in referring to the money you get at your job for working for someone or some company. In fact, we call the check that you might get from the company your “paycheck.” Your paycheck is the money the company gives you for working at that company.
Nowadays, most paychecks are not given physically to employees. The company just puts the money right into your bank account. So that’s the difference between “fee” and “pay.” “Fee” is money you have to pay for some service or to have access to some service, to be able to use something. Or it could be money that a company charges you because you are late paying your bill, or simply as the price of using their services. “Pay” as a noun refers to money you get for working. As a verb, it means to give money to someone for something.
Finally Jiro (Jiro) in Japan wants to know the meaning of an expression his English teacher gave him. A tongue twister is a difficult sentence to pronounce. Here’s the sentence: “Clean clams crammed in clean cans.” What does this tongue twister mean? It’s called a “tongue twister,” I should add, because if you say it very fast, it can be quite difficult to do. “Clean clams crammed in clean cans.” The faster you say, it the more likely you are to make a mistake in the pronunciation.
Well let’s start with the word “clams” (clams). Clams are small animals that live inside of a hard surface called a “shell.” They’re commonly found in the sand or the mud. When you find a clam, you have to open up the shell and clean the clam – get all the dirt or other material that might be on the clam – so you can then eat it. So that’s the meaning of “clean clams.”
The verb in this sentence is “to cram” (cram). “To cram” something means to put something in a place or a space that is already full or almost full. If you have a small car and there are six people that need to go in your car, you’re going to have to cram the people in there because there isn’t enough room. Well, here we’re talking about clams that are crammed into or in clean cans. A “can” (can) is a metal container, what you would put certain kinds of food into. The cans, of course, you would want to be clean. So it makes sense that you would put “clean clams into clean cans.”
Now, whether you would want to cram them in there or not is another story. If you don’t have very much room in the can, I guess you would need to cram them. The importance of the tongue twister is not what it means, but rather the fact that it is difficult to say. I guess some people find tongue twisters fun. I’m not really one of those people who finds them all that interesting.
If you have a question or comment other than a tongue twister, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
animated – created using a method of photographing a series of images or drawings and putting them together to make it appear as though there is motion and movement
* Mickey Mouse was one of the first animated characters on television or in movies.
perspective – point of view; as seen through one’s eyes
* Flying on an airplane must be uncomfortable from a very tall person’s perspective, because there is so little legroom.
cowboy – a man who rides a horse and takes care of cows and other animals, traditionally working in the southwestern part of the United States
* John Wayne was an actor who played cowboys in many movies about the American West.
astronaut – a person who is trained to travel from Earth into space to explore and to do research
* The astronauts were sent into space to find life on other planets.
mission – a goal or task that must be completed; an important assignment
* Johann was on a mission to find the perfect birthday gift for his wife.
spaceship – a vehicle that is used to carry people or items into space
* The spaceship had two very powerful engines that create enough speed to shoot it out of the Earth’s atmosphere and into outer space.
to escape – to break free from being held against one’s wishes
* The prisoner dug a hole in the floor of his cell and was able to escape the jail where he was being held.
commercial – a television or radio advertisement
* During sports games, you’ll see many television commercials for pizza, beer, and cars.
to be depressed – to feel very sad and unhappy for a long period of time
* After losing her job, Imani was depressed and spent all her time crying or worrying about not having enough money to pay her bills.
faculty – the teaching staff at a school; the teachers or professors at a school, college, or university
* Masha is on the faculty at the university and teaches in the Russian literature department.
officer – a person who holds a position of power and authority in the military
* Tom is a high-ranking officer in the Army and is responsible for leading many soldiers.
navigation – the process of correctly finding one’s position on a map and planning a route of travel
* Yoshi is in charge of navigation on the trip and is equipped with a GPS system and a large number of maps.
buddy – a close friend; a term used to address a man whom one does not know
* My friend Pierre and I have been buddies since college.
chum – a close friend
* Yes, of course I know Arin. He’s an old chum of mine.
pal – a close friend; a term used to address a man when one is angry or annoyed
* I’m inviting a few pals over tonight to watch the game and to play cards.
fee – an amount of money that must be paid for advice, a service, permission to do something, or for some other benefit
* How much is the fee to replace a lost or stolen passport?
pay – an amount of money given to someone for regular work
* With Geraldo’s increase in pay, he can afford to buy a new car to replace his current unreliable one.
clam – a small animal that lives in fresh water and that has a shell, commonly found in sand or mud
* I’m making a seafood spaghetti dish with clams, mussels, and shrimp.
to be crammed – to be placed in a container or space so that there is no room for anything else
* At 5:00, the elevators in our office building are crammed with people leaving work.
What Insiders Know
The Origins of Pixar
Pixar Animation Studios is an animation film “studio” (film company) located in Emeryville, California that produces animated films. From 1995 to 2013, the studio produced fourteen films, including the very popular Toy Story, The Incredibles, Monsters, Inc., and Finding Nemo
Pixar began as The Graphics Group. It was one-third of the Computer Division of Lucasfilm “launched” (begun; created) in 1979. In 1986, Steve Jobs, the co-founder of Apple Computers “invested” (gave money with the hope of earning more money in future) money and turned Pixar into a corporation in 1986.
The name “Pixar” was taken from a “high-end” (good quality and expensive) computer “hardware” (equipment) company whose products included the Pixar Image Computer. Unfortunately, the image computer did not sell well and the company was forced to sell its hardware “division” (section; department) in 1990.
In 1991, Pixar made a $26 million deal with Disney to produce three computer-animated feature films, the first of which was Toy Story. Toy Story was very successful, making $361 million worldwide. This was the beginning of Pixar’s success as a film studio.
All of Pixar’s films are among the 50 “highest-grossing” (earning the most money, before expenses are deducted (taken away)) animated films of all time. In 2013, Pixar’s film Frozen earned over $1 billion worldwide, making it the highest-grossing animated film in history. The studio has also earned 27 “Academy Awards” (U.S. film awards) and 11 “Grammy Awards” (U.S. music awards). As of 2014, The Walt Disney Company owned Pixar, after purchasing it for $7.4 billion in 2006.