= 1845
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 540.
This is English as a Second Language Podcast’s English Café episode 540. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide – an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English, including a complete transcript of everything I say. You can also take a look at our ESL Podcast Store with additional courses in English, and our ESL Podcast Blog.
On this Café, we’re going to talk about the 1986 movie Planet of the Apes. We’re also going to talk about one of the shortest presidencies in U.S. history, that of Zachary Taylor. And as always, we’ll answer a few of your questions. Let’s get started.
The 1968 movie Planet of the Apes tells a very unusual story, a story of what we may call an “alternate world.” “Alternate” (alternate) means something that is similar to something else, but different in a noticeable or an important way. We use “alternate” as an adjective to describe another way of doing something or another kind of thing that you could use in place of something else.
So, when you’re driving, we may talk about an “alternate route” (route). A “route” is a way of getting from one place to another. Here in Los Angeles, it’s necessary to know alternate routes – different ways of getting from one place to another – because we have so much traffic, so many cars, and so you need to know other ways of getting to the places you want to go to. Here we’re talking about an “alternate world,” a whole world – a whole reality, if you will – that’s different from our own.
Planet of the Apes, then, is a kind of science fiction movie. An “ape” (ape) is an animal similar to a monkey but it doesn’t have a tail. My neighbor, for example, looks a little like an ape. In the movie Planet of the Apes, the alternate world is one in which apes act like human beings. They speak. They read. They write. They have jobs. They even have pets and slaves. The interesting thing about the movie is that the pets and slaves in the alternate world are human beings.
The movie begins by telling the story of a group of astronauts that leave the planet Earth and go out into outer space. An “astronaut” is someone who travels outside of the earth’s atmosphere, out into what we call “outer space” – all that area outside of our own planet. Remember, the movie was released in 1968, when the U.S. had a very active space program. So, there were lots of stories and movies about outer space and this was one of them.
In the movie, these astronauts go out into outer space, and their captain is George Taylor, played by the famous American actor Charlton Heston. There’s a problem with their spaceship and the astronauts crash onto a planet that they don’t recognize – that isn’t familiar to them. “To crash” (crash) means that you hit something very hard, you hit something with great force, in a violent way. If you crash your car, you hit your car against something else, perhaps another car.
Well, these astronauts are on this strange planet and they, soon after they crash, are captured by these apes. “To capture” (capture) means to take control or possession of someone. The inhabitants of this planet, as I mentioned previously, are apes. An “inhabitant” (inhabitant) is someone who lives in a certain place. The astronauts are prisoners and they decide, after being captured by these apes, that they should escape. “To escape” (escape) means to run away from the place where you are now, a place where you are being held, often as a prisoner – as someone who cannot leave.
Now, immediately Taylor and the other astronauts realize what a weird place this is. I mean, there are apes who are talking and holding them as prisoners. The first thing that Charlton Heston’s character discovers is that the other humans don’t speak. They don’t read. They don’t seem to be able to communicate with him. Well, very soon George Taylor, this astronaut, is basically by himself in terms of trying to escape, and the movie follows his attempts to understand these apes and for the apes to understand George Taylor – to understand this human being who speaks.
The movie was popular because it tells the exciting story of this man who is trying to understand this strange world in which he finds himself. And, of course, trying to get his freedom. Part of the reason the movie was successful also is because of the special effects that were used in the movie. “Special effects” are images that are created for movies and television programs that make it seem as though the actors are in a different place, in a different time.
Another thing that made the movie popular was that the apes were very interesting characters. They were, of course, human beings – not real apes – dressed up as apes, but they used a lot of prosthetics to make the actors look like apes. A “prosthetic” (prosthetic) is a material that covers your body to make you either look like someone different or to replace a body part that you don’t have.
If you lose your arm or lose your leg, you might get a prosthetic. We might also call it an “artificial arm” or an “artificial leg.” The general term would be an “artificial limb” (limb). Notice the “B” is not pronounced. Your arms and your legs are your limbs. Two of the lead actors in the movie who played apes were Rodney McDowell, the British actor, and Kim Hunter. The prosthetics were so good that the man who created them won an Academy Award for his work.
The story of the movie was actually taken from a French novel written in 1963. The original novel tells a similar story, but the theme of the novel was how technology could actually make human beings dumber, and that if we didn’t use it properly, our intelligence could be lost. That’s what seems to have happened to the humans in this world of Planet of the Apes. When the movie was made, however, the theme or the message of the movie changed somewhat.
The person who wrote the script for the movie changed one of the main themes of the movie and made it instead into something related to nuclear war and the ability to have the planet destroyed by nuclear weapons. The person who wrote the script for Planet of the Apes was already famous for writing stories that had some sort of political or social commentary. His name was Rod Serling. Rod Serling had created a television series that you can still see on some American television stations today. It was called The Twilight Zone.
Rod Serling, then, took the message of the movie and changed it somewhat, perhaps reflecting the fears of the American public during this time of the 1960s. The movie became less of a commentary on how technology could make us stupid – a message which is still perhaps one we need to listen to today – but rather on the dangers of nuclear weapons.
Although no one considers Planet of the Apes to be one of the great classics of American cinema, of American film, it was a popular movie. It was shown on television quite a bit when I was growing up in the middle and late 1970s – so popular that they made several more movies. In 1970, just two years later, they made Beneath the Planet of the Apes. Then they made Escape from the Planet of the Apes in 1971. In 1972, they made Conquest of the Planet of the Apes, and in 1973, Battle for the Planet of the Apes.
So it was what we would today call a very successful movie “franchise” (franchise). A “movie franchise” would be something like Star Wars or the Star Trek movies, the Harry Potter movies, the X-Men movies – when you have several movies based on an original movie or idea or even set of characters. Planet of the Apes was a successful movie franchise. It was also briefly a television show in 1974.
In 2001, Tim Burton, the director, made a new Planet of the Apes, although I don’t think it was very good. In fact, none of the other movies after the original movie were very good, although they did make money. My favorite is still the original Planet of the Apes with the great Charlton Heston.
We turn now to President Zachary Taylor, one of the shortest-serving presidents in U.S. history but a man of considerable accomplishments before reaching the White House. Zachary Taylor was born in 1784 in Virginia, on the eastern coast of the United States. Virginia was one of the original 13 states of the U.S. When he was a child, he and his eight brothers and sisters moved to Kentucky.
Now, at this time, Kentucky was considered part of what we call the “frontier.” The “frontier” (frontier) is an area that is farthest away from the cities and towns where most people live. Kentucky was definitely on the frontier and was a difficult place to live because there weren’t very many people there. You had to know how to hunt and fish and survive.
When Taylor was 18 years old, he joined the army and would spend most of his life as a military man. He got married to a woman named Margaret Smith, and together they had six children. Interestingly enough, one of his six children would later marry another man famous in American history, Jefferson Davis. Jefferson Davis was later to become the president of the Confederacy – the group of states that separated themselves from the United States and caused our Civil War.
Taylor was good at what he did in the army and he was promoted several times, eventually becoming one of the highest members of the U.S. military – the “highest-ranking” members, we would call them – a major general. “To be promoted” (promoted) means to be given a more important job, a more powerful job. Taylor served as a leader in several wars during the early part of the nineteenth century, including the War of 1812. He also served as a leader in some of the wars against the Native American peoples, the Native American tribes.
But it was his leadership in the U.S. Army during the Mexican-American War that made him famous throughout the United States. That war with Mexico, which lasted from 1846 to 1848, started in part because of the now state of Texas joining the United States. During the war, the president at that time, President Polk, sent Taylor to the border, the dividing line between Texas and Mexico, and later sent him into the country of Mexico, near the city of Monterrey.
Taylor didn’t particularly like President Polk and didn’t actually obey some of his orders – he didn’t follow what the president told him to do. In fact, he took a small group of soldiers farther south into Mexico and fought the Mexican army at something called the Battle of Buena Vista. Against all odds, he won that battle, despite having fewer soldiers than the Mexican army had. The expression “to win something against all odds” (odds) means to do something even though it doesn’t seem probable that you will in fact succeed or be successful.
The victories of Polk in the Mexican-American War made him famous, made him what we would call a “war hero,” and not surprisingly, as has happened in other periods of American history, war heroes – famous generals – are often then asked to become political leaders, and that’s what happened to Taylor. The Whig Party asked Taylor to be their nominee for president in the election of 1848, and Taylor won that election, becoming president.
The biggest political issue that Taylor had, which was the political issue that all presidents had during the early and mid nineteenth centuries in the U.S., was that of slavery – of the owning of other human beings. This was a practice that was allowed in some states – the Southern states, but not in the Northern states. Taylor was against slavery, and one of the first things he did as president was encourage the then territory of California to become a state, which it did in 1849.
However, it became a free state when it entered the Union – when it became part of the United States – and this didn’t make the slave states, the Southern states, very happy since California would be adding two more senators to the United States Senate. The Southern states wanted some sort of compromise so that any future territories and states that were added to the U.S. would not change the political “balance of power,” we might call it, in the U.S. government. A “balance of power” refers to how much power two or more different, in this case, political parties have. This ended up being called the Compromise of 1850.
Taylor did not live long enough, however, to be able to solve this political issue. On July fourth, 1850, he began to feel very sick. His stomach hurt. He got very ill very quickly. The doctors determined that he had what was not an uncommon disease in the U.S. at that time: cholera. Only five days later, on July ninth, 1850, Taylor died in the White House. He had served as president only 16 months. He was the second president to die as president. The first was William Henry Harrison, who wasn’t even president a year before he died.
There’s not a lot else to say about the presidency of poor Zachary Taylor since he wasn’t president for very long. His vice president, Millard Filmore, became president after he left office and he wasn’t very successful either in solving the problem of slavery in the U.S. – a problem that was ultimately solved by the Civil War. If Americans know anything about Zachary Taylor, it’s probably more because of his service as a general than his service as our 12th president.
One other interesting note – the man that Taylor beat to become president in 1848, the Democrat by the name of Louis Cass, is a name that is probably familiar in some way to those of us who grew up in the Midwestern part of the U.S. Louis Cass, before he became a candidate for president, was the governor of the Michigan territory. He was also secretary of war under Andrew Jackson and a member of the U.S. Senate.
There are several places that are named after Cass, including Cass County in my home state of Minnesota. And there are things named after President Taylor there I’m sure as well. Taylor Swift, for example, was named after President Taylor, maybe. I could be wrong about that. Well, I’d like to think I’m never, never, never wrong about anything.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Renee (Renee) in Mexico. Renee wants to know the meaning of three verbs, “to improve,” “to boost,” and “to enhance.”
“To improve” (improve) is a very common verb in English meaning to make things better or to become better. You can improve your life. You can make it better. You can improve your health by eating better food. You could improve your test scores by studying more instead of playing so many video games. And yes, I’m talking to you, student who isn’t studying out there.
“To boost” (boost) means to increase the force, power, or amount of something. It’s not quite as common of a verb, though it might sometimes be used in the same situations. You could talk about “boosting your test scores,” for example, meaning improving them, making them higher. You could boost the power to your engine by perhaps giving it more gasoline – the engine or motor in your car, for example. Some people take vitamins for their body “to boost their immune system,” their ability to heal from diseases and illnesses.
There’s something related to this verb called a “booster chair,” and that’s a little chair that a young child sits in often in a restaurant. The restaurant of course has chairs for adults, and because the child is too small, the child may not be able to eat at the same table. So, they give the child this little chair that the child sits in called a “booster chair.” You can see the relationship, then, between “to boost” and the “booster chair” as, well, raising up the child so that he can eat.
The third verb is “to enhance” (enhance). This verb can be used in a lot of different situations. It means, again, to improve something and also to increase something. Usually it’s used to mean to improve the value or quality of something. “I’m going to enhance the flavor of this food by adding some salt” – I’m going to improve it; I’m going to make it better.
We also use the verb “enhance” in photography when we take a picture and make it better, or try to make it better, by using certain computer effects on it ?– maybe increasing the light or changing the contrast. These are ways of enhancing a photograph. The noun related to this verb is “enhancement” – or at least, one of the nouns related to this verb. “Enhancement” refers to a general improvement of some situation.
Andre (Andre) from Brazil wants to know the meaning of two phrases that he’s heard or read: “The man grows on you” and “His bark is worse than his bite.”
The expression “to grow on” someone means for you first not to like someone, but later, as you get to know them better, to like them more and more. You could also use this expression when we’re talking about a thing. You could start watching a television show and at first you don’t like it. But later, you watch more and more episodes of the show and it starts “to grow on you.” You start to like it more and more as you get to know it better and better over a period of time.
The second expression, “His bark is worse than his bite,” refers to a dog. The verb “to bark” (bark) means to make a short, loud sound. It’s the specific verb we use to describe the way a dog makes a sound. “To bark” can also mean to shout or say something in a loud and angry way. “Don’t bark at me” means don’t yell at me in a loud and angry way.
When we’re talking about a dog, it’s simply the sound that a dog makes when the dog is angry or, I guess, wants attention. I don’t know. I don’t have a dog, but that’s what I understand. My family had a dog when I was growing up, but he didn’t like me very much, probably because I didn’t like him very much.
Anyway, the other verb in this expression you need to understand is “to bite” (bite). “To bite” (bite) refers to the action using your teeth when you eat, or perhaps simply when you open your mouth and close it on some object. If you make a dog angry, the dog may “bite” you, may open his mouth and put his teeth into your leg or arm.
The expression, then, “His bark,” here using “bark” as a noun, “is worse than his bite” – again same thing, using bite as a noun – means that he may make a lot of noise, but he isn’t going to hurt you. This could refer to a dog, but it’s usually used to refer to a person who may get angry and yell but isn’t really a bad person or won’t actually hurt you.
Our final question comes from Christina (Christina) from countries unknown. Maybe she’s from several countries. You don’t know. Christina wants to know why we would use the expression “Script by Lucy Tse” and not “Scripted (scripted) by Lucy Tse.” You may see this, for example, on our Learning Guides: “Script by Dr. Lucy Tse.” “Script by Dr. Lucy Tse” means this script was written by Dr. Lucy Tse. If you use the form of “scripted,” there’s a slight difference, or could be a slight difference, in meaning.
We usually use the word “scripted,” with the “ed” at the end, to refer to remarks or comments that someone makes that are written out beforehand and then read. For example, if the president of the United States were talking to journalists – members of the media – he might have certain remarks, certain things he wants to say, that are already written down on a piece of paper. We would say that his remarks or his comments are “scripted.” Usually they’re “scripted” by someone who works in the White House.
The opposite of that would be for him to give remarks that are “unscripted” or that are, to use a more technical word, “extemporaneous” (extemporaneous). If your remarks are extemporaneous, you have not prepared them in advance. You haven’t scripted them out first. They haven’t been scripted by anyone. When I record the English Café, most of what I say is not scripted by anyone, although I do have a script that gives me information that I then summarize and comment on.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
ape – a type of animal that is similar to a monkey, but without a tail
* The children were excited to see the apes at the zoo, especially the gorillas and chimpanzees.
alternate – something that is similar to the original, but is different from it in noticeable or important ways
* There was a lot of traffic on the roads yesterday morning so Margaret took an alternate route to work.
to crash – for a vehicle to hit something suddenly with great force or strength and in a violent or forceful way
* The man was driving too fast and was unable to stop before crashing into the car in front of him.
to capture – to take control or possession of something or someone by force
* After chasing the bank robber for three days, police officers were finally able to capture him.
inhabitant – a person or animal that lives in a specific place
* The inhabitants of this neighborhood ranged from older couples to young, single people.
to escape – to run away from a place where one was being held against one’s wishes
* The dog escaped from the yard and had been gone for 20 minutes before his owner found him.
special effects – images created for movies and television using special objects, computer programs, and filming techniques to make audience believe they are seeing something that isn’t real
* Using special effects, the filmmaker created scenes with dogs driving cars.
prosthetic – material that is used to cover a part of the body to change one’s appearance or to replace a missing body part
* The doctors removed his lower leg, but George was able to get a prosthetic, which allowed him to walk again.
to rule – to have complete power and control over something or someone
* Queen Elizabeth II has ruled Great Britain longer than any other king or queen before her.
to promote – to give someone a higher-level and/or more powerful job than the one he or she currently holds
* Yuko worked hard and was respected by her fellow employees, so her boss promoted her to store manager.
border – a line separating two countries or areas of land
* The United States shares a border with Canada to the north and Mexico to the south.
against all odds – doing or accomplishing something even though success seemed unlikely
* There was very bad weather around the airport, but against all odds, Marcy’s flight arrived on time.
to improve – to make something better; to become better
* To improve safety, the city put in more crosswalks on the streets surrounding the college.
to boost – to increase the force, power, or amount of something
* Jermaine often feels the need for a boost of energy in the middle of the afternoon when he begins to feel tired and sleepy.
to enhance – to increase or improve something; to improve the value or quality of something
* How do we enhance the appeal of our products without spending more on packaging?
to grow on (someone) – for someone or something to become familiar, wanted, and/or desired by one after a period of time
* At first, I thought Ben talked too much, but he grew on me and now I find him witty.
(one’s) bark is worse than (one’s) bite – describing a person or animal who behaves in an aggressive and/or threatening way, but is actually harmless
* When you first meet the boss, she seems intimidating, but soon you realize that her bark is worse than her bite.
What Insiders Know
The Boone and Crockett Club
Former U.S. President and “outdoor enthusiast” (someone who enjoys spending time in nature) Theodore “Teddy” Roosevelt “founded” (established; created) The Boone and Crockett Club in 1887. The Club is a nonprofit organization for “hunters” (people who kill animals for food, skins, and/or “sport” (recreation; fun)) and “conservationists” (people who want to take care of the natural environment and protect it for future generations).
The organization is named for Daniel Boone and Davy Crocket, who were well-known hunters who helped the United States expand “westward” (toward the west), but also “warned” (told others that something bad might happen) about the dangers of “overharvesting” (taking too much of a plant or animal, so that it cannot maintain a healthy population).
The Boone and Crockett Club focuses on hunter “ethics” (ideas and rules about what is right or wrong). The Club’s “mission” (purpose) is to “promote” (encourage; help something to happen) the conservation and management of “wildlife” (animals living in the wild, not in homes or farms), especially “big game” (large animals that are killed by hunters) and its “habitat” (where an animal lives), and to maintain the highest ethical standards of “fair chase” and “sportsmanship” (following the rules and respecting others) in North America.
The Club defines “fair chase” as the ethical, sportsmanlike, and “lawful” (following the laws) “pursuit” (chasing something to catch it) and taking of any “free-ranging” (without limitations on where one can go) “wild” (not domesticated; living without human involvement), “native” (originally from the area) North American big game animal in a way that does not give the hunter an “improper” (inappropriate; unfair) advantage over such animals. In other words, the animal should have an opportunity to “escape” (get away from) the hunter.