= 1815
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 510.
This is English as a Second Language Podcast’s English Café number 510. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide, an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English. While you’re there, you can take a look at our ESL Podcast Store with additional courses in English. And why not like us on Facebook? Go to facebook.com/eslpod.
On this Café, we’re going to talk about the 23rd president of the United States of America. Who was the 23rd president? Well, it was, of course, Benjamin Harrison. Mr. Harrison is a more interesting guy than you may think. Find out in this Café. Oh, and always, we’ll answer a few of your questions, too. Let’s get started.
Benjamin Harrison was born in the state of Ohio in 1833. Ohio is in the eastern part of the United States, in between the states on the East Coast and what we call the Midwest. His grandfather (Benjamin’s, that is) was William Henry Harrison. Now, if William Henry Harrison rings a bell – that is, if that name sounds familiar – it’s because he was also a president of the United States: the ninth president. But today we’re going to talk about William Henry’s grandson Benjamin and how he became the 23rd president of the United States.
As you can see, it isn’t just the Bushes that have had more than one person from the family become president. You also had, in the nineteenth century, the Harrisons. They were the Bushes of their century, or something like that. Anyway, Benjamin Harrison attended Miami University in Ohio. It’s a little confusing because Miami is also a city in Florida. Miami University, however, is in Ohio. Weird but true. Harrison was a very bright student. He was one of the most intelligent students in his class when he graduated in 1852.
In 1853, he married the beautiful Caroline Lavina Scott. And in 1854, the Harrisons moved to Indianapolis, Indiana. Indiana is the state next door, just to the west of Ohio. Harrison opened his law office, or law practice, in Indianapolis. The Harrisons also had their first child, a son named Russell. in 1858, a few years later, the Harrisons had their second child, a daughter named Mary.
In Indianapolis, Harrison became involved in a new political party – the Republican Party. Now, in the 1850s, slavery – the practice of owning another person – was still legal in parts of the United States. The Republican Party was started to help end that practice, to stop slavery in the U.S. Of course, political activity was not sufficient, and so in 1861, a war was begun between the Northern states, where slavery was illegal, and the Southern states.
Harrison joined the Army on the side of the North, what we also call the “Union.” The Union was the army that fought for the United States, the Northern part of the United States, in the civil war. The other side in the civil war, you may know, was called the “Confederacy.” The Confederacy was the collection of Southern states that wanted to break away or separate themselves from the main United States, shall we say.
Harrison did well during the war, and by the end, he had been promoted to the rank of Brevet Brigadier General. When I say he was “promoted to a rank” (rank), I mean he was given a higher position of power in the Army. A “brigadier general” is a very high-ranking, high-positioned officer in the Army. The term “brevet” (brevet), which I had never heard of before today, was used during the Civil War as a title. It was given to people who were seen as some of the best soldiers or fighters.
When Harrison returned home, he went back to his law practice, but he continued to be involved, as he was before the war, in local politics. In 1876 he ran for, or tried to get elected to, the office of governor of Indiana, but he lost. The governor is the highest political figure or leader in a state. In 1881, a few years later, he ran for the office of United States senator, and this time, he won. So, he moved with his family to Washington, D.C., since that’s where the U.S. Senate meets.
While in office as senator, Harrison focused on the rights not of African Americans (who were by this time free, following the Civil War) but rather of Native Americans or American Indians. He also worked to protect the rights of a group of very important Americans in our history: that is, homesteaders. What was a “homesteader?” A “homesteader” (homesteader) was a person who decided to move to the western part of the United States to build a home.
You see, when the United States was growing, it had a lot of empty land, and the government wanted to encourage people to go out and live in the Midwest and western parts of the United States. This was an area in many cases that wasn’t even officially part of a state. So in 1862, in the middle of the Civil War, the U.S. Congress passed the “Homestead Act,” and basically what it said was that if you moved out west, where there weren’t very many people, you would be given 160 acres – that’s 65 hectares for the rest of you – of land for free. That’s right. The government would give you that land.
However, as an incentive to stay on the land, you had to do something with the land. An “incentive” (incentive) is something that motivates you, that encourages you to do a certain thing. Well, the incentive for these people was to build a home there and live on the land. And that’s what they had to do. I had relatives who homesteaded in North Dakota – who went to North Dakota, received land, and lived on the land.
One of the things that helped the United States expand into the western territories and states was the growth of the railroad system during the middle and late nineteenth century. “To expand” means to grow or get larger, and that’s what the United States was doing. Well, Harrison argued. He said that the railroad companies shouldn’t be allowed to force people to move in order to build these new railroad lines simply because they lived in the path of the railway.
So you had this conflict – the railroads were being built across the country in order to help people get there, but in order to build the actual railroad track, they had to go through land that some people had homesteaded, who had gotten the land from the government originally. Well, this was something of a political problem, but Harrison tried to fight for the rights of the homesteaders over the railroad.
During this same time, Harrison also argued that soldiers like him, who fought in the Civil War, should receive pensions from the government. A “pension” (pension) is a regular payment that the government gives someone, usually after the person has retired – has stopped working. My father, who fought in North Africa and Europe during World War II in the U.S. Army, received a small pension from the government for his services to the country. Harrison wanted this done to the soldiers who fought in the Civil War.
Both of these policies were popular with a lot of people, and in 1888, the Republican Party nominated, or named, Harrison as their presidential candidate. Harrison won the election of 1888 by a very small number of votes, beating out, or defeating, Grover Cleveland. But don’t worry about Grover Cleveland. You see, Cleveland had already been president. He was president before Harrison was elected and he became president again after Harrison left office. He was the only president to be president twice but not in what we call “consecutive terms” – one after another.
So Harrison was now president of the United States. He didn’t believe in making deals with people to win political office, however. When I say he didn’t believe in “making deals” (deals), I mean he didn’t want to compromise. He didn’t want to give people something in order to get himself elected or in order to get his policies put into practice. Many people in the Republican Party did not feel the same way as Harrison – as indeed is the case for most politicians – and so people made promises to supporters of Harrison just as politicians normally do. They promise you all these things if you will vote for them.
Harrison, as president, focused a lot of his attention not on the United States – at least, on the people living here – but rather on countries overseas. He wanted the United States to become more involved in international issues. And he spent a lot of time focusing on what we would call “foreign policy.” He was interested in spreading American ideas and values and beliefs, as well as working with other countries.
Now, the United States has these two traditions. One tradition is what we might call “isolationist.” This is a tradition that began really with our first president, George Washington, the idea that we wouldn’t get involved in other countries. There is another tradition that is more “interventionist,” or perhaps better “internationalist,” which sees the United States as being active in world politics.
Harrison was definitely of the latter category. Under his presidency, the International Union of American Republics was formed to encourage countries to share knowledge within the North and South American continents. The organization changed its name later to the “Pan American Union” and finally settled on its current name, the “Organization of American States.”
In addition to increasing American “presence,” shall we say, overseas, Harrison also spent a lot of time growing the U.S. military. He believed the military should not consist or be made up of a group of volunteers who didn’t know how to fight. He wanted a professional, well-trained army. Remember that Harrison himself was a general in the Army during the Civil War. He was particularly interested in growing, or increasing, the size of the United States Navy. He added 19 ships to the U.S. Navy, which allowed the U.S. to become more equal to some of the great powers during this period at sea – Great Britain, France, and other countries.
Harrison had a more difficult time, however, with domestic politics. “Domestic” (domestic) refers to the issues at home, in your own country. The opposite would be “foreign policy.” During Harrison’s presidency, many people became concerned about the power of large companies. They were concerned that certain companies such as railroad companies were monopolies and that they were bad for the economy. A “monopoly” (monopoly) is when one organization or company has the majority of a given market. That is, they are one of the few companies you can go to, to buy a certain thing.
The government decided that it needed to restrict monopolies. It needed to prevent these companies from becoming too big and too powerful. And so, Congress passed one of the most important business laws or set of laws of the nineteenth century, the Sherman Antitrust Act of 1890. Under the act, the U.S. government was allowed to take any large company that it thought was a monopoly and was being unfair to consumers, to the average person, to court to sue them.
The government could even ask for these companies to be dissolved. “To dissolve” (dissolve) means to close down or to put an end to a company or an organization. More often, the government sought fines from these companies. A “fine” (fine) is a punishment in the form of money. It wasn’t until the early 1900s that the government really began to get serious about using the Sherman Antitrust Act. In fact, that act is still important today. The government has many times in the past 30 years tried to stop large companies – most famously, Microsoft – from becoming monopolies.
When Harrison began as president, the economy was doing pretty well, and the government had a lot of surplus money. “Surplus” (surplus) refers to an extra amount of something, more than what you need. The government had extra money, more than what it had to spend. This is not the normal way most governments operate. Governments usually have a lot of debt, a lot of money they owe other people, but when Harrison was president, they actually had a surplus. So Harrison did what most politicians did – he spent the surplus.
What did he spend the surplus on? Well, some of the money went to those Civil War pensioners, those soldiers who had fought for the North during the Civil War. Some of the money went to help businesses. Many people complained, however, that the government didn’t really care about the average American citizen, and in the election of 1890, during the middle of Harrison’s presidential term, many Republicans lost their seats in Congress, and for the next two years, Harrison wasn’t really able to accomplish much.
Harrison was once again nominated for the office of president for the 1892 election. However, his wife, sadly, died in October of 1892 of tuberculosis, or what was then called “consumption.” So he didn’t really go out and try very much to become president. In part because of this, Grover Cleveland won the election and became president again. Harrison, of course, was saddened by the loss of his wife, by the death of his wife, and he returned back to Indianapolis. He did, however, eventually remarry, or marry again, in 1896. Harrison was 62 at the time. His young bride, his new wife, was 37. Way to go, Benjamin. They had a daughter, and the daughter was named Elizabeth, in 1897.
Harrison continued to be active in politics even into his old age. He worked as a lawyer. He also continued to work in foreign affairs. He worked for the country of Colombia in an argument that they had over a border with British Vienna. The Venezuelans asked the United States for help in redrawing this border, this dividing line between the two countries. Venezuela did get back some of its land, but most of it stayed under British control. Today Guyana is an independent country.
Harrison spent the remainder of his time giving lectures and speaking in public. He was a very excellent public speaker, a very “charismatic speaker,” we might say. “Charismatic” (charismatic) means that he was very charming. He was very appealing. Many of these lectures took place here in California at Stanford University, up near San Francisco. Harrison died in 1901 of pneumonia, an inflammation of the lungs. His young daughter, Elizabeth, was only five years old when he died.
Harrison is remembered as a president who expanded American influence overseas, sometimes for the good, sometimes not. He also is known for increasing the size of the military and for signing the Sherman Antitrust Act. Although Benjamin benefited from having the last name of Harrison and the connection to his grandfather, he eventually made his own mark on American history by being a famous lawyer, general, senator, and president of the United States.
Now let’s answer a few of your questions.
Our first question comes from the Haris (Haris) in Pakistan. The question has to do with two common expressions, “to call the shots,” and “to wear the pants in the family.” Let’s start with the first one, “to call the shots” (shots). “To call the shots” is an expression that refers to being responsible for making all of the decisions in a given situation.
The person who is in charge, who is the leader, who is the boss, “calls the shots” – decides what is going to be done and what is not going to be done. So, if someone says, “I’m calling the shots around here,” the person means he is the one who’s making the decisions. He’s in charge. He’s the boss. He’s the leader.
“To wear the pants in the family” is an old expression, perhaps not as common now as it used to be, to refer to the person in a marriage who is the most powerful or who makes all the important decisions. Traditionally, you think of “pants” as being associated with men and “dresses” or “skirts” as being associated with women. So the expression “to wear the pants in the family” means to be the person who’s making the decisions.
Traditionally, the man had a certain amount of power in families and was seen as the decision maker. So, if someone says, “Well, the wife wears the pants in that family,” the person is saying that the wife has the power, perhaps the power that traditionally might have belonged to the husband.
Our next question comes from Madard (Madard) in Benin, in Africa. The question has to do with the difference between two similar sounding words, “inquiry” and “enquiry.” These two words mean the same thing. One of them is British English – (enquiry), and one of them is American English – (inquiry). Both of them refer to a request for information, when you ask someone for information about something.
The word “inquiry” in American English can also mean an official, often government-led investigation of something, usually a problem or perhaps even a scandal. When politicians do something wrong or when some government official or worker makes a mistake, sometimes there’s an “inquiry.” There’s an official investigation as to what actually happened, what went wrong. So “inquiry,” “enquiry” – same meaning, different countries or different types of English. With an “e,” it’s British English; with an “i,” it’s American English.
Finally Marco (Marco) in Italy wants to know the meaning of an expression he heard, “There’s more than one way to skin a cat.” This is an odd – but to me, oddly interesting – expression. It goes back to, I guess, the middle part of the nineteenth century, at least according to some of the Internet websites I looked at. The meaning is fairly easy to explain. It means there is more than one way to accomplish a goal or to achieve a certain end or result. There is more than one way to do something.
Now, if you skin an animal, you take a knife and cut the skin off it (of course, you would kill the animal). The expression apparently is a variation of a more general expression about there being more than one way to kill a cat. Now, why would someone want to kill a cat? Well, I can think of a lot of reasons, actually. But the important thing is that this expression doesn’t really have anything to do with killing cats. It is related to the idea that there is more than one way to do something.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
rank – a position within the power structure of an organization, such as the police force or the military
* After being in the army for 20 years, John had reached a very high rank and was in charge of many people.
incentive – something that motivates or encourages a person to do something
* The car dealership offered an incentive of $500 off the price of a used a car to anyone who bought one that day.
to expand – to make something grow; to make something larger
* As Moshi blew air into the balloon, the balloon expanded and we could see the picture printed on it.
pension – regular payments made by a person’s employer to that person after he or she has retired (stopped working after a certain age)
* Dmitri felt as though he had earned his pension after working for the same company for forty years.
to make a deal – to come to an agreement with someone in order to achieve a goal
* Let’s make a deal: I’ll go to the movie with you if you go with me to get ice cream afterwards.
domestic – relating to one’s own country; involving a person’s home
* In most countries, when taking a domestic flight, you don’t need a passport, only a form of identification with your picture on it.
to restrict – to limit; to prevent something from occurring
* Parking in the garage was restricted to residents of the building, which prevented people from parking there to go to the restaurant across the street.
monopoly – when one person or organization controls a product or a major part of the market
* When the two largest airline companies tried to merge into one, the government said that it would become a monopoly and the deal was called off.
to dissolve – to close down or take apart, usually an organization or agreement
* The brothers had a good partnership for many years but when they began arguing all the time, they dissolved the partnership and went their separate ways.
fine – a punishment in the form of money that a person or company must pay when it has done something illegal
* Amir parked in the “no parking” zone at the airport and had to pay a $250 fine.
surplus – an extra amount of something that remains after what is required has been paid or the demand has been met
* Will there be a surplus of t-shirts after every student has been given one?
charismatic – charming or appealing to other people
* Fernando is a very charismatic man who can get himself out of any difficult situation simply by talking to people and making them want to help him.
to call the shots – to be responsible for making all decisions in a given situation
* While the supervisor is out of the office, Gem calls the shots and tells us what to do.
to wear the pants – to be in charge in a marriage or in a family
* You can ask Dan to help you, but his wife wears the pants in the family and she doesn’t like you.
inquiry – a request for information; an official effort to collect and examine information about something
* If we get any inquiries about the job opening, give their information to the Balah.
enquiry – a request for information, used mainly in British English
* We’ve had several enquiries about our used car for sale.
“There’s more than one way to skin a cat.” – a saying meaning that there are several possible ways of achieving a goal or completing a task
* Mom said we’re not allowed to stay out late Saturday night, but there’s more than one way to skin a cat. I’m asking Dad.
What Insiders Know
Wovoka and The Ghost Dance Movement
The Ghost Dance was a religious “movement” (people working together to create or advance an idea) begun in 1890 by Wovoka, a Native American religious leader from the Northern Piute “tribe” (cultural group). Wovoka, also known as Jack Wilson, was said to be a “prophet” (person who can tell others the meaning of messages from God) who could “interpret” (explain the meaning of) “visions” (the seeing of something not there) directly from God.
Wovoka said that he saw visions many times in his life, but it wasn’t until he got older that he learned to interpret them. On January 1, 1889, when he was 33 years old, he said he saw an important vision. He said that God showed him a place where people lived in “peace” (without war or conflict) with whites. God, he said, gave him the Ghost Dance, a religious dance performed in a circle, and told him to take it back to his people. By including the dance in their religious ceremonies, according to Wovoka’s vision, the Dance would “wipe out” (eliminate) “evil” (forces causing bad things to happen) from the world and fill the world with food, love, and “faith” (belief in God).
As news of Wovoka’s vision “spread” (became known to many people), many different tribes sent representatives to find out more about Wovoka and what he “claimed” (said was true but without proof) to have seen. Learning about the Ghost Dance, many tribes incorporated it into their own “practices” (regular behaviors and actions). However, there were other tribes that did not accept and believe in this “concept” (idea) and “dismissed” (did not accept) it “altogether” (completely), never including or performing the Ghost Dance as part of their religious ceremonies.