= 1821
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 516.
This is English as a Second Language Podcast’s English Café number 516. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. (I know. Not so good, right?)
Visit our website at ESLPod.com – that will be much better than my singing – because when you go there, you will see you can become a member of ESL Podcast and download the Learning Guide for this episode. Are you on Facebook? So are we! Go to facebook.com/eslpod, and follow us on Twitter at @eslpod, of course.
On this Café, we’re going to do another one of our Ask an American segments, where we listen to other native speakers speaking – in some cases, very quickly – but we go back then and explain what they’re saying. This Ask an American episode will be about “community policing.” And as always, we’ll answer a few of your questions. Let’s get started.
We’re going to talk about community policing. The word “policing,” of course, comes from the noun “police” (police). The police are the people who are supposed to protect you against criminals, make sure that you are safe in your community. “Community policing” is a technique that has become very popular in many American cities. The idea is that the police officers, the people who are working for the police department, work with local residents – the people in the community – to try to reduce crime, to try to make an area safer for those who live there.
We’re going to listen to some people talking about their experiences with the police and their opinions of community policing. Part of the idea behind community policing is that the police make sure that even small crimes are taken care of – what are sometimes called “quality of life” crimes. The idea here is that you want to keep a neighborhood safe not just from murderers and people who steal things, but also from smaller crimes that might create an “atmosphere of criminality,” we might call it, in a community.
We’re going to first listen to a young man from Long Beach, California. Long Beach is a city about, oh, maybe 15, 20 minutes from where I live by car. Long Beach is a community that has, like a lot of California cities, many poor people. We’re going to listen to a 22-year-old man by the name of Jacob. He speaks very quickly, so he’s difficult to understand, but hey, that’s why I’m here. We’ll listen to Jacob give his experience with the police, and then I’ll explain what he says after we listen to him. Let’s listen.
[recording]
“They always try to mess with me like, uh, I ask, ‘What’s the reason for you pulling me over?’ ‘Oh, because you fit the description.’ Really? Really, yeah, I guess I’m always fitting the description then, because I’m always getting pulled over.”
[end of recording]
Jacob is difficult to understand even for a native speaker, but let’s explain what he said. He begins by saying, “They always try to mess with me.” “They” in this case refers to the police, to police officers. “To mess (mess) with” someone means to create problems for someone or to do something that would bother another person. Jacob believes that the police are always messing with him. They’re always trying to create problems for him.
He then says, “I ask,” meaning I asked the police, “‘What’s the reason for you pulling me over?’” The phrasal verb “to pull someone over” refers to the police stopping your car and asking you some questions, or perhaps even arresting you – taking you to the police station.
Let’s say you’re driving down the street and you suddenly hear a police car behind you. You pull over to the side of the road. You stop and you park your car. The police have pulled you over – they have made you stop your car in order to perhaps ask you a question or perhaps to give you some sort of punishment. They may give you what’s called a “ticket” (ticket). When the police give you a ticket, they are saying that you have to pay money to the government because you broke a law.
Sometimes the police will pull you over, and if they discover perhaps you were doing something illegal, or even that you have something illegal in your car like a gun or drugs, they might arrest you. They might take you back to the police station. Jacob is complaining that he always gets pulled over by the police, and he asks the police why, what’s the reason they are pulling him over. The police answer, “Oh, because you fit the description.”
Jacob doesn’t say that’s what the police says, but we know from the way he says it that he’s quoting a police officer. He’s telling us what the police tell him. They tell him that he “fits the description.” “To fit the description” means to match or be similar to a description that the police have of a criminal.
So, for example, if someone commits a crime, someone hits another person or steals someone’s car, and a person sees the criminal and gives the police a description of what the criminal looks like – the police will then go out and try to find that person. Or perhaps there was a camera that was taking a film, a movie, of the person who committed the crime. The police then try to find someone who “fits” that description – who matches that description, who looks like the person being described.
Jacob says that the police tell him they pull him over because he always fits the description, which logically Jacob thinks is probably not true. He says, “Really? Really, yeah, I guess I’m always fitting the description then, because I’m always getting pulled over.” Jacob is sort of making a joke here – he’s saying that he must fit the description of everyone the police are looking for because he always gets pulled over. The police always stop his car.
Some people complain that the police will stop certain kinds of individuals – young men for example, or African-American, Latino, or other minority men – more than they stop other people. I think that’s what Jacob is saying here. When Jacob says, “Really?” he uses a certain way of speaking, what we would call an “inflection,” to indicate that he doesn’t believe the police.
This has become common, especially in the last 10, 15 years or so, for people to use the word “really” to express their disbelief – the fact that they don’t believe this for a minute, that they can’t believe that someone else believes this. Let’s take two possible situations – one is that your friend tells you that he’s getting married. You say, “Really? That’s wonderful! Congratulations!” The way I say the word “really” in that example expresses surprise, but in a good way.
Compare that to this situation – your friend comes up to you and tells you that he’s quitting his job in order to go and become a singer or an actor here in Hollywood, here in Los Angeles. You say to him, “Really? Are you really going to do that?” There, when you say “really,” you mean you don’t believe him or you think it’s a really bad idea. You can’t believe that your friend would be so stupid as to come to Los Angeles and try to become, say, an actor.
Let’s listen to Jacob now, again.
[recording]
“They always try to mess with me like, uh, I ask, ‘What’s the reason for you pulling me over?’ ‘Oh, because you fit the description.’ Really? Really, yeah, I guess I’m always fitting the description then, because I’m always getting pulled over.”
[end of recording]
Next, we’re going to listen to a person who is what we might call a “community activist,” a person who works for an organization in a community, in a neighborhood, that tries to help the people who live there – in this case, who tries to arrange meetings between police officers and the young people so that the two can understand each other better. This man is called Darick Simpson. Let’s listen.
[recording]
“With any differences comes some misunderstanding, because people bring their culture, they bring that history into the workplace, into schools, into different social scenarios.”
[end of recording]
Darick begins by saying, “With any differences comes some misunderstanding.” The verb “comes” here means when you have one situation, you also have another situation. “With great power comes great responsibility.” If you have a lot of power, you also have a lot of responsibility. Many people think this comes from the movie Spiderman, but of course it does not come originally from Spiderman – at least that idea comes from the Bible.
But back to our story. Mr. Simpson says, “With any differences” – meaning whenever people are different from each other – “With any differences comes some misunderstanding.” “Misunderstanding” is when two different people or groups of people, well, don’t understand each other, don’t know why the other person or the other group does what it does. They don’t understand the reasons for their actions. People have different perspectives, different opinions, when they come from different, what we would call, “backgrounds.”
Darick goes on to say, “People bring their culture. They bring that history into the workplace, into schools, into different social scenarios.” Darick is saying that “people bring their culture,” meaning their customs, their ideas, their traditions, “into the workplace.” “Workplace” (workplace) – one word – is, logically, the place where you work, the place where you have your job.
Darick says, “People bring their culture. They bring that history,” meaning their experiences, what they have gone through in life, “into the workplace, into schools, into different social scenarios.” A “scenario” (scenario) – a “social scenario” might be people together in a café or in a restaurant or at a party. What Darick is trying to say is that no matter where people go – wherever they go, whether it’s to work, to school, or to somewhere else in the community – they always bring their own culture with them, their own history with them, and that can sometimes lead to misunderstanding.
Let’s listen to Darick one more time.
[recording]
“With any differences comes some misunderstanding, because people bring their culture, they bring that history into the workplace, into schools, into different social scenarios.”
[end of recording]
Finally, we’ll listen to Jim McDonnell. Jim McDonnell is the police chief of Long Beach, California. A “police chief” (chief) is the person who manages or runs the police department. He or she is the boss, if you will, of everyone who works in the police department. Chief McDonnell is going to explain how you avoid problems, especially problems that are related to racial issues. Let’s listen.
[recording]
“We build a team. And when you have a team, when a crisis comes up, you’re not dealing with it by yourself. And too often when we see things get volatile across America, and whether it’s a racial issue or another similar type of issue, it’s often because there aren’t those pre-existing relationships in place.”
[end of recording]
McDonnell begins by saying, “We build a team.” The word “team” (team) is usually used when we’re talking about a sports competition. We could talk about baseball teams or soccer teams or football teams, but the word “team” has become popular also in American business – people talk about teams who work on a project together. McDonnell talks about how the police build teams – groups of police officers, we’re guessing – that work together.
But also I think he means a team of people from the community, people who live in a certain area, a certain neighborhood, to whom the police can go and get help from, especially when there is a crisis. A “crisis” (crisis) is a serious situation, a serious problem that you have to take care of right away, usually. The chief says when you have a team, when a crisis comes up, “you’re not dealing with it by yourself.” “To deal (deal) with” something means to take care of something, usually a problem.
He says, “And too often when we see things get volatile across America, and whether it’s a racial issue or another similar type of issue, it’s often because there aren’t those pre-existing relationships in place.” Let’s start with the first part of the sentence, when Jim says, “too often when we see things get volatile across America.” “Volatile” (volatile) refers to a situation that is changing quickly and can become dangerous or violent at any second, or very soon. A “volatile situation” is a dangerous situation, a situation in which people might start killing each other or committing some other sorts of crime.
Jim is talking about situations when “things get volatile across America,” meaning in different parts of the United States. He then talks about whether something’s “a racial issue or another similar type of issue.” The word “issue” here means topic, or more likely, problem. A “racial (racial) issue” is a problem or a situation that relates to people of different races, perhaps African American, white, or Asian American.
We don’t use the word “race” normally to describe those who we refer to as “Hispanic” or “Latino.” The word we would use in those cases would be probably “ethnic” (ethnic). But in any case, Chief McDonnell here is talking about problems that come up or that are caused by racial differences or racial misunderstanding. McDonnell is saying when we have a problem like this, or one caused by some other situation, it’s often because there aren’t those pre-existing relationships in place.
“Pre-existing” means existing before something else happens. If the police know a lot of people in a neighborhood, in a part of the city in a community, they can talk to those people. They can work with those people when there are problems. However, if they don’t have those relationships, if those relationships don’t exist before a problem, then things become volatile, things can become violent. Let’s listen to Chief McDonnell one more time.
[recording]
“We build a team. And when you have a team, when a crisis comes up, you’re not dealing with it by yourself. And too often when we see things get volatile across America, and whether it’s a racial issue or another similar type of issue, it’s often because there aren’t those pre-existing relationships in place.”
[end of recording]
That there is a little information about community policing in the United States.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Ayden (Ayden) in China. The question has to do with three words, “perspective,” “notion,” and “viewpoint.” Let’s start with “perspective” (perspective). Your “perspective” is your way of looking at something – how you examine something, how you think about something, really. Your perspective is formed by, or is influenced by, your experiences – where you grew up, what language you speak, what country you’re from. All of these things can affect or influence your perspective – the way you see the world, we might say.
“Viewpoint” (viewpoint) is similar to “perspective,” although usually “viewpoint” refers to a specific opinion you have about something. I have a viewpoint about people who talk on their cell phones in cafés. I think they should be arrested. I think they should be thrown in prison. I think they should have all of their property taken away from them. (I’m just kidding. Just throwing them in prison would be enough.) That is a “viewpoint.” That is my opinion. That is the way I think about a certain situation.
“Perspective” is a little more general, a little broader – something that would influence or affect your views or opinions on lots of different topics, perhaps. The word “perspective” can be used in lots of different situations, including in business or in your daily life. The word “viewpoint” would probably be used more often when talking about, say, a political situation.
Finally, the word “notion” (notion) means an idea or an opinion. It could be used in a similar way to viewpoint, but “notion” has a much more general use. It describes an idea or an opinion that a person has. Usually when we use “notion,” we use it in cases where we’re not sure of something. We think it’s true, but we’re not 100 percent certain.
“I had this notion that the girl sitting across from me didn’t like me.” I’m not sure. I don’t know why, but when I said hello, she got up and she walked away. I have a notion that she didn’t like me, but I can’t be sure. Actually, I could probably be pretty sure in that situation. Sometimes we use “notion” to mean idea, as in, “You have no notion of what it’s like to work every day of your life.” You have no idea. You don’t have any experience, and therefore you can’t really understand what it’s like.
Our next question comes from Sergei (Sergei) in Russia. This question has to do with three verbs – “to burst out,” “to break out,” and “to explode.” Let’s start with the first verb, a phrasal verb “to burst (burst) out.”
The verb “to burst” means to break open in a sudden and often violent way. If you take a balloon and you fill it with water and throw it at your friend, it will burst. It will suddenly open, and of course all the water will come out and fall on your friend. That’s a very popular game among children, using water balloons – or perhaps more likely, teenagers. We used to do that when we were growing up. We would throw water balloons at each other. That’s the verb “to burst.”
The phrasal verb “to burst out,” however, means to suddenly say or do something in an expression of a very strong emotion. Someone could “burst out laughing” – and in fact, that’s the most common situation when you will use this phrasal verb, with the idea of someone laughing. “He burst out laughing” – or it could be the opposite as well, “He burst out crying.” He suddenly started crying, very loudly perhaps, expressing a very strong emotion.
The second phrasal verb is “to break (break) out.” There are some similarities between “burst out” and “break out,” but “break out” usually is used to describe a situation where people are in a prison or a jail and they escape. They get out of the jail illegally. “To break out of prison” means to escape from prison, to leave prison without the guards, the people who are watching you, knowing.
In a more general way, we can use this phrasal verb “break out” to refer to either someone who has a disease that suddenly develops, such as chicken pox, which is a disease where you get these small little red bumps on your skin. “I broke out in chicken pox” means I suddenly developed the symptoms of chicken pox.
Finally, the verb “to explode” (explode) is usually used when we’re talking about a bomb or some other object that suddenly breaks apart and causes the contents – what’s inside of the bomb or the object – to go all over the place and often to hurt or to injure people. If a bomb explodes, it’s going to kill people, perhaps. It’s going to injure people. It’s going to damage something.
You could also talk about, say, a car exploding. If it hits a wall and a fire is started, the gasoline that is in the car could cause it to explode. It could suddenly go “boom” and you would have a huge ball of fire, and of course a very dangerous situation if you are still in the car. Sometimes, we’ll talk about a person “exploding,” usually when someone is very angry, someone is very upset and starts yelling and screaming. “The person exploded with anger,” we might say.
Finally, a question from Ahmad (Ahmad) from Unknownlandia. Actually, I think he lives in Unknown City in Unknownlandia. The question has to do with something he read on the Internet: “Don’t count every hour in the day, make every hour in the day count.” This expression – which I’ve never heard of before, but I understand what it means – depends on knowing the meaning of the word “count,” because there are two different ways you could use the verb “to count” (count).
“To count” can mean to add up a set of objects. I can “count” from one to ten on my fingers – one, two, three, four, five, six, seven, eight, nine, ten – that is “to count”, or I can count the number of people in this room: one – oh, that’s it. It’s just me. “Count” also has another meaning, which is to matter or to be meaningful – to make an impact, to have an effect, to be significant. “Every day counts” means every day is important, every day matters.
The expression here is “Don’t count every hour in the day,” which probably means something like don’t just be paying attention to how much time you have and how much time you are working, but rather what you are actually doing. “Make every hour in the day count” means do something significant, something that matters all of the time, every hour. Don’t just worry about how much time you spend on something; worry about what impact you are having or what you are actually doing that matters.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
to mess with (someone) – to create problems for someone; to become involved in someone else’s business and do things that that person does not like
* Nobody wants to mess with Li because she can be mean when she gets angry.
to pull (someone) over – for a police officer to make someone stop his or her car at the side of the street to ask him or her questions
* The police officer pulled me over for speeding and asked me to show him my driver’s license and proof of car insurance.
to fit the description – to have the physical characteristics of the person that someone is looking for
* The police are looking for a male in his 20s or 30s between 5’6” and 6’, but that’s too vague. Too many people fit the description.
misunderstanding – an instance when two people do not understand each other, often leading to confusion or disagreement
* Pete thought they were meeting at the corner of Main and 34th Street, but Meghan thought they were meeting at the corner of Main and 43rd Street. It was just a simple misunderstanding, but it took them a long time to find each other.
workplace – the office building, factory, store, or other place where a person works
* They have a relaxed workplace where people can wear casual clothing and bring their pets to the office.
scenario – a situation or a set of circumstances; the setting in which people interact with each other
* Have you ever been in that awkward scenario where you have to introduce your current girlfriend to your ex-girlfriend?
crisis – a very big, serious, significant problem that requires immediate attention
* The hospital is well equipped to respond to natural disasters and other crises.
volatile – changing quickly and likely to become dangerous or violent
* At the mental hospital, patients often become volatile and staff members have to know how to react appropriately.
racial issue – a problem related to negative interactions between groups of people with different skin and hair color or cultural background
* Providing low-income housing in urban areas is almost always tied to racial issues and differences in educational opportunities among racial groups.
pre-existing – existing before something else happens; already in existence
* The Spaniards built their cathedral on top of pre-existing Incan temples.
in place – in existence; established; already there
* If these rules had been in place from the beginning of the school year, the teacher wouldn’t have had to deal with so many student behavior problems.
perspective – the ability to see things in their true importance; a way of looking at or thinking about something
* Even though this is a major problem, let’s keep it in perspective and not overreact.
notion – an idea; an opinion
* Where did you get the notion that rabbits like to eat fish?
viewpoint – a way of looking at or thinking about something; point of view
* People say that your viewpoint about life changes after you have children.
to burst out – to suddenly say and/or do something that shows strong emotion
* Carlos told Sally a joke in the middle of class and she burst out laughing.
to break out – to develop or emerge suddenly using force; when being confined or constrained, to emerge suddenly by using force
* How did the kittens break out of the cardboard box and get into the kitchen cupboard?
to explode – to suddenly break apart in a violent way with parts flying in many directions
* The bomb exploded in the empty building, causing a lot of damage, but no injuries.
to count – to indicate how many of something there is, giving the total number of things involved
* Let’s count the number of guests who have already agreed to attend.
to count – to have significance; to be of importance
* The person who walks around the track first is the winner, but it doesn’t count if you run.
What Insiders Know
The Controversial Practice of Stop and Frisk
In many “jurisdictions” (places controlled by a government or police department and are required to follow the rules of that government or department), police officers use “stop-and-frisk” “practices “(ways of doing something) when they “encounter” (find; run into) a “suspicious” (something whom one believe may have committed a crime) individual. The police officer “stops” (detains; makes someone stop what he or she is doing and stay still for a period of time) the individual and then “frisks” him or her. When frisking someone, a police officer lightly “runs” (moves) his or her hands over the person’s clothing against the body to determine whether there are any hidden “weapons” (arms; items intended to hurt or kill others, such as knives, guns, or bombs) or drugs.
Some people argue that police officers are “abusing” (using in wrong ways) stop-and-frisk practices to “target” (focus one’s attention on) minority communities. Police officers are supposed to have “probable cause” (a reason for believing that a person is suspicious and probably has a weapon), but in many cases, the only probably cause seems to be the individual’s race. Analyses of the programs have shown that most of the targets of stop-and-frisk practices have been African American and “Latino” (Hispanic; from Central and South America) men.
In a large “majority” (more than 50%) of the cases, no weapon or drugs are found, and the individual is allowed to “go on his way” (proceed with what he was doing). However, many members of minority communities report that they have “repeatedly” (many times) been stopped and frisked, which “intrudes on” (violates) their freedoms and makes them feel that the stop-and-frisk program is really a form of “racial intimidation” (a way to make members of a racial minority feel frightened or less powerful or important than others).