= 1842
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 537.
This is English as a Second Language Podcast’s English Café number 537. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development (development, development) in beautiful (beautiful, beautiful, beautiful) Los Angeles (Angeles) – okay, in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download a Learning Guide for this episode right after you become a member of ESL Podcast. And hey, take a look at our ESL Podcast Store which has additional courses you can buy and download immediately on Business and Everyday English. If you’re on Facebook, please, please like us on Facebook, too. We’re at facebook.com/eslpod.
On this Café, we’re going to talk about one of the greatest American writers in our history, the great poet Walt Whitman. We’re also going to talk about a 1960s singing group called the Supremes. And as always, I’ll answer a few of your questions. Let’s get started.
Walt Whitman was born in May of 1819 in the state of New York. New York is on the eastern coast of the United States. When Walt Whitman was a child, he, his parents, and his eight brothers and sisters moved to Brooklyn, New York, which is in New York City. As an adult, Whitman worked as a printer, as a teacher, and as a journalist.
A “printer” (printer) is a person whose job it is to work with a machine that makes books, newspapers, and magazines on, of course, paper. A “journalist” is a writer who works for a newspaper or a magazine, who goes out and investigates stories or reports on stories. We also call a journalist, sometimes, a “reporter” because the journalist is giving you information. He’s “reporting on” a certain topic.
Whitman eventually became the editor of a popular newspaper in New York called the Brooklyn Daily Eagle in 1846. An “editor” (editor) is a person at a newspaper or a magazine or perhaps even a news program on television who decides which stories to talk about or to print, as well as helping determine how those stories are reported. Whitman was a very good writer and editor. However, the person who owned the newspaper didn’t like some of his political opinions. So, in 1948, after only two years, Whitman lost his job as the editor of this newspaper.
One of the reasons Whitman lost his job is that he was the member of a political party called the “Free Soil (soil) Party.” “Soil” is another name for dirt or earth, something that you dig out of the ground. We usually use the word “soil” when we’re referring to how well a particular piece of land is able to grow certain things – plants and other vegetation. However here, “Free Soil” refers to a group of people who believed that slavery was wrong and that slaves should become free men and free women.
We’re referring, of course, to African American slaves during this time in our country’s history. “Slavery” is the owning of another human being. I should point out that many people in the northern states were against slavery, including Whitman. That doesn’t mean that they believed that blacks as free men and women should have the same rights as whites. In fact, many of them didn’t like African Americans even living in their states and territories. But they didn’t think they should be slaves.
Young Walt Whitman – he was only 25 years old at this time – believed in the ideas of the Free Soil party, and because of those beliefs, he was “fired” – he lost his job as editor of this newspaper. Now, as a young man, he had his whole life in front of him, you might say. So, he decided to travel. He went to New Orleans, Louisiana, in the southern part of the U.S. and worked on a boat. Then he came back to New York, and after trying to get a job as a journalist again, decided to build and sell houses.
Whitman was an intelligent young man, but he had not gone to college. He had not gone to university. He didn’t have any formal training other than being a printer. And so he decided that he would make money by being involved in what we would call “real estate” – the buying and selling and building of houses. He did this for about five years until about 1855.
During these years in New York, working in the different jobs in which he worked, Whitman liked to observe people. He liked to analyze and think about and write about people. He did this on his own. He didn’t publish these observations. He expressed himself in the form of poetry. “Poetry” (poetry) is a kind of writing that often uses a certain pattern, although it is difficult to define poetry. Poetry is often written in lines that don’t always match up with sentences as you would find in the other major kind of writing, which is “prose” (prose).
Whitman’s poetry included his observations about people, but it wasn’t until he was 36 years old in 1855 that he actually produced a book. He actually published a book of his poetry. This was a collection or a set of different poems that Whitman had written over the years. He called this first book of his poetry Leaves of Grass.
A “leaf” (leaf) is normally something we would use to describe a part of a tree – the little green things that come out of a tree are called “leaves,” but less commonly, a “leaf” can also refer to a piece of paper, and that’s the meaning that Whitman was using here in his title, Leaves of Grass. Why grass? Well, “grass” was a term that some publishers used for works – things that were published – that weren’t very important, that didn’t have a lot of value, that were sort of not worth a lot.
Some of America’s best writers, when they saw Leaves of Grass, when they read it, recognized it to be an amazing and very important piece of literature – something that was very different from other poetry that had been published before this time in the United States. Ralph Waldo Emerson, the great writer, thought it was an amazing collection of poems. One of the reasons they thought this was such an amazing book is because several of the poems talked about sexuality in a very open way.
“Sexuality” refers, of course, to the sexual thoughts and actions of a man or a woman. This is not something that poetry, at least the poetry that was published in the U.S., had discussed openly or very honestly or “explicitly,” we might say. Before this time, open discussions of sexuality were “taboo.” “Taboo” (taboo) refers to something that is not acceptable – that you don’t do or you don’t talk about in public, at least. And that’s why Leaves of Grass was so different from the other poetry that had been published before it.
Even though many critics and many poets loved Leaves of Grass, the general public didn’t. The first edition, the first time that Whitman published this book, it didn’t sell very many copies. It was eventually revised. It was eventually changed, correcting some of the mistakes and improving some things, and published again. But this second revision, this second publication that included these changes in corrections to the poem, didn’t sell very well either. (I should mention, the second edition also contained a poem that was not in the first edition.)
Whitman tried again in 1860 with a third edition of the book, but once again he was not successful, in part because this was a time in which the United States was about to go to war. The American Civil War began in 1861 and everyone was focused, of course, on this horrible Civil war. Whitman worked for the government during the war, and in 1865, after the war had ended, he got a job in the Department of the Interior, which is the federal or national government office that takes care of the land that is owned by the U.S. government.
He was, however, fired from this job because his boss read his poems and thought that they were indecent. “To be indecent” (indecent) means that they are unacceptable, usually because of the sexual content. Something that is indecent is usually something that is very sexually explicit or that talks about or shows sex in a way that people find offensive, that makes people uncomfortable and is considered unacceptable socially.
And remember that Leaves of Grass has a lot of discussion of sexuality, a lot of use of sexuality in its poems. Whitman, perhaps learning something from his failures in trying to sell Leaves of Grass, published another set of poetry in 1865, this time about the war. This kind of poetry was popular. That collection of poems was called Drum-Taps. But Whitman had not given up on that first collection of poetry, Leaves of Grass. He revised it again, and this time added even more new poems to it.
By this time, writers and poets from England had also begun to notice Whitman’s poetry and talk about it in a favorable light – that is, say that they liked it. In 1872, however, Whitman became ill. He had a “stroke” (stroke). A stroke causes, among other things, sometimes for people to become paralyzed. They’re unable to move an arm or leg or part of their body, and unhappily, that is what happened to Walt Whitman in 1872. He went to live with his brother and eventually got better – well enough, in fact, for him to travel out West in 1879.
In 1881, yet another edition of Leaves of Grass was published. This one, however, was condemned, or was criticized, by some organizations for being immoral. Something that is “immoral” (immoral) is something that is not moral, not right, not ethically correct according to some philosophical or religious belief. Oddly enough, interestingly enough, the newspapers began to write articles about these criticisms of Whitman’s collection of poetry, and he actually began to sell more of his Leaves of Grass collection.
The collection was revised a couple of more times. In fact, there were a total of nine editions of Leaves of Grass that were published in Whitman’s lifetime. The ninth was published the year he died, in 1892, and that’s the edition that you will find now available in bookstores or online. Whitman’s poems were part of what we may term the “Romantic movement” in art and literature during the nineteenth century. He also participated in a more nationalistic kind of literature, a literature that attempted to express the particular characteristics of a given country.
Some people think there’s something uniquely American about some of Whitman’s poetry. Some say that his particular style of writing, what is called “free verse” (verse), creates a mood of openness that matches the large natural resources of the U.S. I don’t know if that’s true, but certainly Whitman is still considered today one of the great American poets of the nineteenth century and is often read in American high schools and colleges.
We turn now to our second topic in this Café, the singing group the Supremes. The word “supreme” (supreme) means the highest level or the greatest. Here in the U.S., we have what is called the “Supreme Court” that is the highest legal court – highest legal body, we might refer to it as – in the U.S. judicial system, in our court system. Each state typically also has a Supreme Court. So, “supreme” means greatest or highest level.
The singing group the Supremes began, as many famous musical groups did during this period, in Michigan, in the city of Detroit, Michigan, which became famous for a certain style of music. Michigan is located in the central-eastern part of the United States. It’s actually on the border of Canada.
The Supremes were a group of three black, or African American, women by the names of Diana Ross, Florence Ballard, and Mary Wilson. These three young women were signed to a record label called “Motown Records” in 1961. A “record label” (label) is basically a company that makes records, that makes audio recordings that it then sells.
The word “Motown” (Motown) is a shortened version of “Motor Town” or “Motor City,” which is what Detroit is often called in the U.S. Why? Well, because the largest makers of automobiles, of cars, are located in Detroit, or at least they used to be. So, we call sometimes the city of Detroit, “Motown.” Motown Records was the most famous record company during this period, promoting a certain style of music, and many of its artists, many of its singers, were African American.
Motown Records began in 1959 and represented some of the best African American musicians of this period, including Marvin Gaye, Smokey Robinson, later Stevie Wonder, and Michael Jackson, who you might have heard of. The Supremes were not immediately successful after they began recording records for the Motown Records label. It took them about three years of trying out different songs before they began to become popular, before they began in a way to develop their own, what we might refer to as, “signature sound.”
The word “signature” (signature) is an interesting one. “Signature” can refer to the way you write your name on a piece of paper. But “signature” can also refer to something that is unique to you, something that is special to you, or in this case, to a musical group. In 1964, the Supremes released, or started to sell, a song that contained that signature sound, that had that signature sound.
That song was called “Where Did Our Love Go,” and it helped make the Supremes one of the most popular music groups in the United States. They were considered not just a popular group, but a group of sophisticated young African American singers. “Sophisticated” (sophisticated) usually refers to someone who has a lot of knowledge about the world or culture, art, and literature. Here perhaps it refers just to musicians who are very good at what they do, and that’s certainly true of the Supremes.
One of the things the Supremes helped do, along with other popular musical groups during the 1960s, is to give people a different image of the African American community, to help them understand the importance of the civil rights movement that was taking place during this same period. From 1964 to 1967, the Supremes were in fact one of the most popular musical groups in the U.S. They also had a famous song in 1964 called “Baby Love.”
Baby love, my baby love,
I need you, oh how I need you . . .
You know that one. In 1965, they had “Stop! In the Name of Love.” In 1966, a song that often appears in movies nowadays, “You Can’t Hurry Love.” All of these songs at some point were later sung by other bands and other musicians because they really are wonderful pop songs, wonderful songs to sing along with.
You can’t hurry love,
No, you just have to wait,
She said love don’t come easy
It’s a game of give and take . . .
See? You just can’t help but sing them when you hear them. In 1967, however, the Supremes began to have some supreme problems. The group members began fighting with each other, and that made it very difficult, of course, to work together. Florence Ballard left the group in 1967 and she was replaced by another singer, Cindy Birdsong.
But even that didn’t end their problems, and finally in 1970, the most famous singer in the group, Diana Ross, left the group to become a solo artist. “Solo” (solo) means by yourself. Diana Ross became a big star in the 1970s by herself and continued to record records right up through the 1980s.
In 1988, the Supremes became members of the Rock and Roll Hall of Fame. This is a group, an organization, that selects the very best members of the rock and roll community, I guess we could say, the very best musicians, and gives them this honor of being included in the organization. Despite the relatively short career that the Supremes had, they managed to record some classic American songs that we still remember from the 1960s.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Daya (Daya) from an unknown country. The question has to do with three words: “abbreviated,” “concise,” and “succinct.” “Abbreviated” (abbreviated) is something, such as a word, that is made shorter than it would normally otherwise be. “Abbreviations” are often used in writing so that you don’t have to write the whole word out.
So, for example, the word “street” is often abbreviated to two letters (St.). Abbreviations typically have a period after them. Sometimes an entire word is abbreviated by just one letter, and that letter has a period mark after it. At least, it does in formal writing. With the increase in text messaging and other forms of short writing, such as Twitter, people have begun to use abbreviations without periods, so you will often see letters that are supposed to be abbreviations that don’t have any periods. It really depends on the abbreviation.
I would say in general that there’s a trend to get rid of the period after the letters in an abbreviated form of a word. In some cases, such as when you are writing a letter, the abbreviation for the state, the two letter abbreviation, no longer has a period after it. In the old days, they used to put a period after it since it was an abbreviation. So, “California” has a two letter abbreviation – CA – but instead of seeing a capital C and a small A with a period after it, you just see two capital letters (CA) and everyone knows that’s an abbreviated form of the word “California.”
“Abbreviated” could also be used to describe anything that is shortened, such as a piece of writing or even a story. Someone says, “I have a great story to tell you.” You may say, “Well, I’m really busy right now. Give me the abbreviated version.” That means don’t give me the whole story; give me a shorter version of the story.
“Concise” (concise) means expressing a lot of information using very few words. It’s not the same as “abbreviated.” In “abbreviated” the idea is that you are actually not including some information in your version of, say, a story. With “concise,” all the information is there but you are using the fewest number of words possible to express the information or the ideas.
Similarly, “succinct” (succinct) means expressing an idea in a short form but still using all the information that you have. You’re just using the fewest number of words you can in order to express it. Other words that mean the same as “concise” and “succinct” are “brief” or “pithy” (pithy). You don’t hear “pithy” used very much anymore, but I rather like it.
Out next question comes from Jose (Jose) in Spain. Jose wants to know the difference between the verb “to withdraw” and the verb “to retreat,” especially when we’re talking about military context – that is, a situation where one country is fighting another in a war. “To withdraw soldiers” (people who are fighting in a war from an area) means to remove them.
Now, there might be a lot of reasons why you, for example, send a group of people, a group of soldiers, into an area and then decide to take them out of that area. There are many reasons why you might withdraw your soldiers. We would also say your “troops” (troops). It means the same thing.
The use of the verb “withdraw” doesn’t tell you why you’re removing these soldiers from an area. In fact, we might use this verb to withdraw even in a situation where there is not a war going on right now, but you have soldiers in a certain country. So, if the United States had soldiers in a certain country and it decided to withdraw its troops, its soldiers, it wouldn’t necessarily have anything to do with a war or whether you are winning or losing a war.
However, “to retreat” (retreat) refers specifically to withdrawing your troops during some sort of battle. Normally you retreat, you take your soldiers out of an area, when you are losing – when the other side is winning and you want to save yourself, basically. Sometimes people who are running the war – the generals – will have what they may call a “strategic retreat.” They’re retreating not because they think they’re losing, but because they think they will have a better chance by moving their soldiers out of a certain area.
Both of these verbs have non-military uses – that is, we use them in other contexts other than talking about a war or about soldiers. “To withdraw” anything is to remove it from a place where you put it originally. So you can, for example, put money into your bank account – we would use the verb “deposit” (deposit) money – or you can “withdraw” your money. That would be to take it out of your bank account. So “withdraw” is also used in cases where you put something in a certain place and then you decide to remove it for whatever reason.
Similarly, retreat can also be used in other circumstances not related to a war. As a noun, a “retreat” could signify a place where you go for quiet and comfort, or a time that you spend away from other people to be alone, perhaps for some religious purpose. You could go on a “religious retreat” where you go and you spend your time praying and reading. The idea of a retreat more generally refers to a place that is quiet and peaceful and calm.
Finally, Norbert (Norbert) in Germany wants to know the meaning of the expression “to stretch (stretch) well.” The verb “to stretch” means to make something wider or longer. Usually you hear this verb when you are talking about some physical object like, say, a cloth or a towel. However, we also use it when we’re talking about money. Someone may say, “I’m trying to stretch my money,” or “I’m trying to stretch my budget” (budget).
“To stretch” there means to get as much as you can for the money that you have – to get as much value, perhaps we could say, from the money that you have. “I’m going to buy cheap vegetables” – vegetables that don’t cost very much money – “because I don’t have a lot of money and I need to stretch my money so that I have enough to eat.” I need to get the best value possible for the money I have. So “to stretch well” would in this case mean to spend your money on things that will give you a lot of value for the dollars that you are spending.
I should mention that we also use this verb “stretch” when you’re talking about the body. You can “stretch” by reaching your hands up in the air. You’re stretching your body. You are flexing or exercising your muscles in such a way that they are being used in a way they were not when you were just sitting.
If you’ve been sitting at your desk for a long time, you may decide to stand up and stretch your legs, to move your legs out back and forth. Maybe take a little walk around your office in order to stretch your legs. It’s a way of giving your muscles some exercise. Not very much exercise, of course, if you’re just walking around your office. On a lot of airplanes nowadays, there isn’t a lot of room to stretch your legs while you are sitting. You can’t move your legs out very far because the seat is so close to the seat in front of you.
If you’re walking around your office wondering what something means in English, send us an email. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
printer – a person whose job is to produce large numbers of books, magazines, or newspapers traditionally using large machines, usually for sale
* The printer produced 50,000 copies of the book and they all sold in a month.
to observe – to watch and listen closely to people and their surroundings
* Jean enjoyed observing people because he believed that you could learn a lot about them from watching their facial expressions and hand movements.
poetry – a kind of writing that has many lines of short text, usually with some type of repeated rhythm
* For Valentine’s Day, George wrote some love poetry for his girlfriend.
taboo – something that is not socially acceptable; something not acceptable to talk about or to do
* It’s generally taboo to ask someone you don’t know well how much money he or she earns or how much he or she weighs.
edition – a particular version of a book or other published text
* Only 10 copies of the first edition of the book still exist and each copy is worth a fortune.
revision – changes to a piece of writing that corrects or improves it
* The students went through four revisions of their final research paper before submitting it to their professor.
indecent – offensive and shocking, usually because of sexual content
* The way that man is touching that woman in a public place is indecent!
immoral – against what is considered good and right
* Many people consider it immoral to sell guns to children.
supreme – the greatest or highest in level or quality; the best
* This restaurant claims its coffee is supreme, but I like their competitor’s better.
signature – something that a person, place, or thing is known for
* Tony Bennett sang his signature song, “I Left My Heart in San Francisco.”
sophisticated – having a lot of knowledge about the world, culture, art, and literature
* People who visit this art gallery come from all over the world and have sophisticated taste.
solo – alone; by oneself
* Charles Lindbergh was the first person to fly solo without stopping from the United States to Paris in 1927.
abbreviated – something, especially a word, that has been made shorter; having made something shorter than it was or was intended to be
* The abbreviations “Ave.,” “St.,” and “Blvd.” you see on envelopes stand for “Avenue,” “Street,” and “Boulevard.”
concise – giving a lot of information in a few words; using few words to express an idea or meaning, not including extra or unnecessary information
* Dorrie’s reports only take a few minutes to read because she is concise.
succinct – in speech or writing, expressing something briefly and clearly; using few words to state or express an idea
* Are there any politicians who answer reporter questions in a simple and succinct way?
to withdraw – for soldiers in battle to leave an area
* The peacekeeping troops will withdraw from this area because there is no longer any fighting or any serious threat.
to retreat – for soldiers to move away from an enemy because the enemy is winning or has won the battle
* The enemy’s soldiers caught us by surprise and we had to retreat.
to stretch – to cause something to be used for a longer time or for more purposes than originally planned or expected; to make something wider or longer
* Li is a single mother who has to stretch her income to feed and clothe three children.
What Insiders Know
Dreamgirls
Dreamgirls is a Broadway “musical” (a theater production that involves acting, singing, and dancing) and a film. Tom Eyen wrote the “lyrics” (the words that are sung) and “book” (script), and Henry Krieger wrote the music. The musical “opened” (was performed for the first time) in 1981.
The musical is about “show business” (the entertainment industry) “aspirations” (hopes and desires to do something). It presents the story of three women in Chicago, Illinois who sing together and call themselves “The Dreams.” “Act 1” (the first part of the musical) shows their early days in Chicago in the 1960s as they begin to “transform” (change) themselves. “Act II” (the second half of the musical) shows the musicians after they have become the most successful group of female musicians in the country.
Many people believe that Dreamgirls is based on the life and careers of The Supremes. The plot or story follows closely with their “rise” (process of becoming popular or successful) to “stardom” (being famous) and their “tumultuous” (confused and difficult) relationship after they becoming famous.
The musical was “adapted as” (made into) a film in 2006. “Directed by” (having control of the filming of the movie) Bill Condon, it “stars” (has as the lead or most important actors) Jamie Foxx, Beyoncé Knowles, Eddie Murphy, and Jennifer Hudson. The movie includes four additional songs that were not part of the original musical. The film’s “production” (the process of making a movie) cost $80 million, which made it the most expensive film to have only African Americans in the “starring cast” (the most important roles in a movie and the actors who play them).
The musical and the film were “well received” (appreciated and admired by critics and audiences). The musical was “nominated for” (named; suggested as a recipient of) 13 Tony awards, the yearly award for theater and musical shows. It won six awards. The film won three Golden Globe Awards and two Academy awards, both honoring or recognizing good films.