= 1682
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Cafe number 377.
This is English as a Second Language Podcast’s English Café episode 377. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and get the Learning Guide for this episode.
On this Café, we’re going to talk about another famous American court case or trial – the Sam Sheppard trial. We’ll also talk about Plymouth Rock, and as always, we’ll answer a few of your questions. Let’s get started.
We begin our Café with a discussion of a famous murder trial, the Sam Sheppard case. Sam Sheppard was a physician or a doctor who was accused of murdering his pregnant wife, Marilyn, on July 4, 1954, in their home in the state of Ohio, which is in the eastern central part of the United States. Sheppard was brought to trial, or brought into a courtroom, in the fall of that year.
The trial or case received a lot of attention from the media and from the general public. People were very interested in this trial as they often are in murder trials. During the trial, it was shown that Sheppard had had an affair with a nurse where he worked. “To have an affair” (affair) is a sexual and/or romantic relationship with someone to whom you are not married, so someone other than your husband or wife.
Prosecutors – the people who were trying to show that Sheppard had committed murder, the government lawyers – argued that this affair was what prompted or caused Sheppard to kill his wife. He fell in love with another woman, and then he decided to kill his wife.
Sheppard said that he had been sleeping downstairs in the home when he heard his wife scream. He said he ran upstairs where he saw an intruder. An “intruder” (intruder) is someone who goes into your house without your permission, usually someone who’s going to steal something, or perhaps, to harm you.
Well, Sheppard saw this intruder, and, according to Sheppard, the intruder beat Sheppard or hit him very hard and he lost consciousness. “To lose consciousness” (consciousness) means, basically, to fall asleep, to become unaware of your surroundings. Losing consciousness could also be more serious than that, but in this case, it was temporary. When Sheppard came to, that is, when he returned to consciousness – when he woke up, he realized that his wife had been murdered. That, anyway, was Sam Sheppard’s story.
The jury – the group of people who listen to the evidence during a trial and determine whether you are guilty or innocent, whether you did the crime or not – did not believe Sheppard’s story, and so, Sheppard was convicted or found guilty of the murder in December, 1954. Sheppard was then, of course, sent to prison or jail, as we call it also, for ten years, and then he was allowed to have another trial. Sometimes, murder cases, or any criminal case, if there is new evidence or if there’s reason to believe there was a problem with the original trial, some of these cases can be tried again, and Sheppard was given a new trial in the mid 1960’s.
His appeal, or his request for a new trial, went all the way to the United States Supreme Court – to the highest and most powerful court in the United States. That court determined that Sheppard’s original conviction, when he was originally found guilty, was a mistake, or at least, it was unfair. There had been several mistakes made in the trial.
One of the problems was there was a large amount of media attention, and there were reports about the trial on television and in the newspaper. The members of the jury had not been sequestered. “To sequester (sequester) a jury” means to, usually, to put them in a hotel room where they don’t have access to TV or radio or newspapers so they don’t get other ideas about whether the person is guilty or innocent. Juries are only sequestered in very rare instances, in rare cases where there’s a very famous person who was killed, and it is thought that the jury might be influenced by reading the newspaper or surfing the Internet, nowadays.
Well, this jury probably should have been sequestered, but they weren’t, and that’s one of the reasons why the Supreme Court decided that Sheppard’s original trial had been unfair. I should mention, it’s quite unusual for the Supreme Court of the United States – the highest court – to act in this way, to decide to change a decision by the jury or, at least, tell the court that they have to have a new trial, but that is what happened in the Sheppard case.
Sheppard’s attorney during the appeal was a man by the name of F. Lee Bailey. F. Lee Bailey later became one of the most famous lawyers in the United States. At the time, he wasn’t very well known, but the trial – the second trial – helped propel his career. “To propel” (propel) means to advance or to move forward. F. Lee Bailey was later involved in another famous murder trial, the O.J. Simpson trial, which we talked about on ESL Podcast number 364.
During the retrial of Sam Sheppard, he was acquitted in 1966. “To be acquitted” (acquitted) means he was found not guilty. The second jury found that he did not commit the murder, or at least, there wasn’t enough evidence to show that he commuted murder. He was, therefore, allowed to leave prison, and wrote a book about his experiences, and actually began working as a doctor again.
But life was never again to be the same for Sam Sheppard, having spent 10 years in prison. He wasn’t able to adapt very well. He, in fact, ended up becoming what is called a “professional wrestler.” These are the guys that dress up in suits often and really pretend like they’re fighting each other. It’s more for entertainment than anything else. Sheppard also became addicted to alcohol. He couldn’t stop drinking, and that was one of the reasons why he died of liver failure in 1970.
Sam Sheppard’s son, Samuel, has spent much of his life trying to clear his father’s name or his father’s reputation. “To clear someone’s name or reputation” means to try to change how people think of that person, usually by trying to tell what you think is the true story of what happened. Was Samuel successful? Well, not completely.
However, today people continue to talk about this murder trial of more than 60 years ago. One of the reasons is, of course, the interesting circumstances – a rich doctor having an affair, murdering his wife, perhaps, or saying that someone else came in and murdered his wife. There were lots of theories and there still are about who really killed Sam Sheppard’s wife. Some people believe the real murderer was somebody who was there fixing the house. Nobody knows for sure. Perhaps, Sam Sheppard himself was the murderer. Again, it’s impossible to give a final answer. We do know that in his second trial, the jury decided there was not enough evidence to show he was a murderer.
Probably one of the most important things that came out of the Sheppard trial was that television and movie writers got interested in the story, and they developed a TV series called “The Fugitive (Fugitive).” However, the creators of the story say that the Sheppard trial was not their inspiration. That’s not where they got their ideas. However, if you’ve ever seen the TV series or the movie with Harrison Ford, you can see pretty clearly that there’s a lot of similarity between what happens to the doctor in The Fugitive and what happened to Sam Sheppard. You have a doctor whose wife was murdered by some mysterious intruder who claims that the intruder hit him, that he became unconscious, and that when he woke up, he found his wife dead. That, in fact, is exactly how the movie begins. If you haven’t seen The Fugitive, it’s really very entertaining. I’ve seen it probably 10, 15 times, mostly because it’s on television a lot here in the United States, but The Fugitive certainly has a lot of similarities to the story of the Sam Sheppard trial.
Now let’s turn to our next topic, which is not murder, but a rock - specifically, Plymouth Rock.
Plymouth Rock is located in Massachusetts, which is a state in the northeast part of the U.S. Plymouth Rock is a physical rock, where, according to tradition, the first colonists, the first settlers from Europe, came in their ships, people we call the “Pilgrims.” They came in the ship called the “Mayflower” and they landed in North America in 1620. These “Pilgrims” (pilgrims) were early settlers. They left Europe mostly to have more religious freedom.
When their boat, the Mayflower, landed or reached land in what is now called Massachusetts, the Pilgrims disembarked or got out of the boat. “To disembark” (disembark) is the opposite of “embark,” which means to leave. “To disembark” means to arrive and then to get off of the, in this case, the boat. We would probably use this verb now more for boats than anything else. For an airplane, we would say “deboard.” But in this case, it was not an airplane – although that probably would’ve been faster than taking a boat – but rather, it was the Mayflower.
The Pilgrims, as they were getting off of the boat, stepped on this large rock, and according to the tradition, Plymouth Rock was the first rock that they stepped on, although some people doubt whether this was really the first rock that they stepped on. Why that was even important, I don’t know. But for some reason, it was considered important, and oh, maybe 120 years after the pilgrims arrived, in 1741, there was a man who said that he knew the Pilgrims had landed on this rock. The man was very old. He was 94 years old, but not old enough to have been alive when the Mayflower landed in 1620.
However, he said that his father and some of the other passengers of the Mayflower, some of the other Pilgrims, had shown it to him when he was younger. Whether we have the right rock or not isn’t really that important. The rock has become a symbol of American history and culture. It’s a story that is told even today in American schools, about how these Pilgrims came to the New World and landed in what became Plymouth, Massachusetts, and they stepped first on this rock.
The rock was preserved. It was taken and it was actually, in 1774, it was broken into two parts in order to move it because it was a very large rock. The bottom part was left on the shore in the water where it was originally, and the top part was taken to a large meeting hall or meeting house – a place where people meet and have discussions. Later, that top piece of the rock was moved again, this time back to sit on top of the lower part of the rock . The rock was also carved, or had written into it: the year of the Mayflower landing, 1620.
Whenever you have something old and famous, people always want to have a piece of it for themselves, and over time, people started removing small pieces of the rock as souvenirs. A “souvenir” (souvenir) are small objects that you take from a place to help you remember those experiences or those trips, those vacations. Some of those pieces of rock, actually, can be seen in museums throughout the United States. There were a lot of these rocks that were taken. a lot of these pieces that were taken from the rock, I should say. In fact, the top part of the rock is probably only one third of its original size. That part of the rock is kept in a state park called the Pilgrim Memorial State Park in Plymouth, Massachusetts.
I said that Plymouth Rock is an important symbol of American history. It represents the first Americans who came to this country; that is, the first settlers or colonists, the Pilgrims. Not everyone has liked the idea or the symbolism of Plymouth Rock. For example, Malcolm X, the famous African American civil rights activist of the 1960’s, once said, “We didn’t land on Plymouth Rock. The Rock landed on us.” That’s an interesting phrase, an interesting saying. “To land on” means that you step on, or that your vehicle that you are in touches the ground at a certain point. We can talk about the plane landing on the ground. It comes down and it touches the ground and it stays there. We talk about people landing on their feet. (For some reason, we have this idea that, if you drop a cat from say a tall building, it will always land on its feet. I’ve always wanted to try that.)
Anyway, the verb “to land on” means to come down on, and what Malcolm X was saying is that African Americans – black people in the U.S. - did not land on Plymouth Rock. Instead, “the Rock landed on us,” meaning we were crushed by the rock. We were hurt by the Rock, that America came down on the backs of African Americans. They were enslaved, they were made slaves, and they were discriminated against.
That, however, is not the main association that Americans have with Plymouth Rock. In fact, my guess is most Americans have never even heard that story about Malcolm X. Most Americans think of Plymouth Rock as a symbol of the founding of the new colonies and the representation of religious freedom, which is what the Pilgrims primarily were seeking, according to traditional American history, when they came to what is now the United States.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Aryan (Aryan) in Iran. The question has to do with the difference between two verbs, “to counsel” and “to consult.” “To counsel (counsel)” means to give advice to someone, to recommend something to someone. It can also be a noun meaning “advice” or “instruction.” Often, we use this word “counsel” when we’re talking about a psychologist or a psychiatrist or a social worker, or what we would call a therapist, working with someone who needs some sort of psychological help. We would call that person a “counselor,” someone who counsels, someone who gives advice, who helps them.
“To consult” (consult) is sort of the opposite meaning. “To consult” means to ask someone for advice or to ask someone for information. That’s one meaning of consult. “Consult” can also mean to go out and look for information, usually, in a specific place, such as an encyclopedia or a dictionary, or nowadays, Wikipedia. “I need to consult the dictionary about the meaning of this word.” That means I need to look at the dictionary to see what this word means.
“Counsel” and “consult,” then, both involve advice, but the difference is “to counsel” means to give advice, and “to consult” means to ask for advice. “Before I buy anything at the store, I have to consult my wife. She has to give me permission to do anything, if I’m buying anything, especially anything expensive.” That’s an example – just an example.
Just to confuse you, I’ll mention that there’s a noun “consultant,” which refers to a person who works with companies, usually a person who has some sort of expertise - that is, some sort of knowledge that the company needs. Consultants usually work for short periods of time with an organization or a company.
Our next question comes from Russia, from Svyatoslv (Svyatoslv). The question has to do with two expressions. One is “hit me head on,” when talking about a car. “The car almost hit me head on.” Let’s talk about that one and then we’ll talk about the next one. “Hit me head on” means that the car almost hit you directly. “Head on” in this case means right in front of you, directly in front of you. If a car hits you head on, the car doesn’t hit the side of your car; it hits you directly in the front of your car. So, the two, you can think of them, “heads” of the car hit each other. That’s to “hit something head on.”
The next expression is “scared the crap out of me.” Well, this is a rather informal phrase and slightly vulgar. “To scare” (scare) means to frighten someone. “Crap” (crap) is another word for excrement, what comes out of the body, the solid waste that comes out of the body. There’s a more vulgar term that begins with an “s” and is four letters long and ends in a “t,” which I will not mention on the podcast.
The original expression was “scare the s-blank-blank-t out of me,” but a more polite, although still not very polite version, is “scared the crap out of me.” Basically, it means it really frightened me. It really scared me. I was very frightened.
As I say, the word “crap” is not a polite word. Sometimes it’s used to mean junk, trash. Sometimes it’s used as an expression of anger or disappointment. “The Dodgers won. Oh, crap!” I don’t like to use the word. It sounds ugly to me. Certainly, my mother would not let me use that kind of language when I was growing up. So, it’s probably not a good word for you to use, either. There are some cleaner, more acceptable ways of expressing this idea. You can say “something scared the daylights out of you.” “It scared the daylights out of me.” That’s perfectly acceptable. “Scared the life out of me” is also acceptable.
Finally, Pinky (Pinky) from a country not identified here in my notes - I’m sorry Pinky - Pinky wants to know the meaning of an idiom “to have a bee (bee) in one’s bonnet (bonnet).” A “bee” is a small insect, usually yellow and black, that has what we call a “stinger” (stinger), which is sort of like a short needle that it uses to defend itself. The verb “to sting” – it means the animal, in this case, the bee, will actually come and go into your skin with that little needle, that little stinger. We call that a “bee sting” as a noun. So, that’s a bee. A bee also makes what we would describe as “buzzing sounds.”
[buzzing]
That’s to buzz (buzz).
A “bonnet” is a hat that a woman or a young girl might wear. It has two little strings or ribbons on the bottom that tie under the chin to keep the bonnet from flying away, I guess. It goes around the face. It’s not, however, something that you will see today, at least in most places in the United States. It used to be more traditional back in the 19th and early 20th centuries, to see women and young girls with bonnets, especially when they went to church. But hardly anyone wears a bonnet anymore. I don’t think I’ve ever seen a woman wearing a bonnet in my lifetime.
This expression, however, “a bee in one’s bonnet,” means that you are thinking a lot about something or only about something. We would probably, nowadays, use the verb “to be obsessed (obsessed). “To be obsessed,” about something means to be constantly thinking about it. You wake up and you’re thinking about it. You go to sleep and you’re thinking about it. The idiom, then, means thinking too much about something, perhaps, I’m not sure.
The idea is that the bee gets inside of your bonnet and it can’t leave and it’s always moving around because it can’t get out of your bonnet. I’m just guessing. The truth is this idiom is not used very much in English, American English, anymore. I would bet a lot of Americans never have heard of it or certainly don’t know what it means, but you will come across it in reading, in literature, especially in books written in the 18th, 19th, perhaps first part of the 20th century. In place of this idiom, we would probably, as I mentioned, use a verb like “obsessed” or we might say someone is “preoccupied.” They’re always thinking about something, so much that they’re not able to think about anything else. “To be preoccupied” is usually a negative way of describing someone, just as to have a bee in your bonnet is considered a negative way of describing someone.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the
Glossary
intruder – a person who enters a home or other location without permission, usually with an intention to commit a crime
* Leo woke up in the middle of the night because he thought he heard an intruder in the house.
to lose consciousness – to not be aware of one’s surroundings, almost as though one is asleep
* During the football game, Jose was hit hard and he lost consciousness for about a minute.
to come to – to regain consciousness; to once again become aware of one’s surroundings
* Belinda fainted after hearing the bad news, but came to almost immediately.
jury – a group of people who listens to the evidence during a court trial and determines whether someone is guilty or innocent
* The jury listened to the witnesses as each one told what he or she saw during the robbery.
to be convicted – to be found guilty of a crime; to be legally responsible for a crime
* If she’s convicted of murder, she’ll spend the rest of her life in prison.
appeal – a request for a second trial because one believes that the first trial was unfair or conducted improperly, or there is new evidence
* Bosun doesn’t think his lawyer did a good job with his first trial and plans to file an appeal for a new trial.
sequestered – for a jury to be kept separate during a trial, usually with the members living in a hotel room, with limited access to other people and the news
* The jury was sequestered for two months during the murderer’s trial.
to be acquitted – to be found not guilty; for a court to decide that one did not commit a crime
* Everyone was surprised that Anwar was acquitted of all charges, because most people thought he was guilty.
to clear (someone’s) reputation – to try to change how people think about someone, usually by trying to tell the true story or by showing evidence or proof of what actually happened or of what someone actually did
* The principal was convinced that Monica spray-painted the side of the school, and to clear her own reputation, Monica found the student who really did it.
Pilgrims – early settlers of the United States; the first Europeans to arrive and to make a home in the United States
* Many of the Pilgrims left Europe to find religious freedom.
to disembark – to leave a ship, airplane, or other vehicle; to get off a ship, airplane, or other vehicle
* Our ship arrived at the port at 9 a.m. and the passengers disembarked.
souvenir – a small item kept to help one remember one's travels or experiences
* When Amar returned from his Hawaiian vacation, he brought souvenirs for all of his co-workers.
to counsel – to give advice; to recommend
* The guest speaker counseled students on how to get a job in her field.
to consult – to ask for advice, guidance, or information; to look to for information
* If your leg doesn’t feel better by next week, consult your doctor.
to hit (one/someone) head on – to strike one or someone directly, usually from the front
* The dumb dog ran toward the cow and hit the cow head on.
to scare the crap out of (one/someone) – to frighten one/someone very much
* My son scared the crap out of me when he walked into the house with blood on his face.
a bee in (one’s) bonnet – thinking a lot or only about something; preoccupied or obsessed with something
* Jermaine has a bee in his bonnet about how much more money the house will cost to build than he was originally told.
What Insiders Know
The Pilgrim’s Progress by John Bunyan
The Pilgrim’s Progress from This World to That Which is to Come (usually just known as The Pilgrim’s Progress) is a story written by John Bunyan in 1678, and is one of the most well-known stories in English Literature.
Bunyan wrote The Pilgrim’s Progress while he was in jail. He had been sent there because of religious crimes, such as “preaching” (teaching God’s word or Bible stories to people) without a “license” (a piece of paper that allows someone to do something) or preaching in places where he wasn’t allowed.
The story is a “Christian allegory,” meaning that it is a story that uses “symbols” (things that are meant to represent something else) to share a message so that Christians can learn from it. The Pilgrim’s Progress is a “tale” (story) about a man named Christian, who represents all Christians. This man goes on a journey from his hometown, called “The City of Destruction” (meaning the Earth) to the “Celestial City,” meant to represent “heaven” (the beautiful place where Christians believe people’s souls or spirits go after they die if they were a good person). Along the way, Christian is “weighed down” (made to feel heavy) with the knowledge of “sins” (actions that go against what Christians believe the Bible says you should or should not do), and sinks down into “Tophet,” a place that represents “hell” (the horrible place where Christians believe people’s spirits go if they were bad during their lifetime). Christian does not like Tophet, and luckily, he meets other people who can help him get out. Eventually, after a lot of trouble, Christian makes it to the Celestial City, and later, his wife and children must try to make the same journey.
This story was meant to get Christians to follow God so that they could get to heaven, and it became very popular all over the world. Since it was first written, the story has been printed in over 200 languages, and has never been “out of print” (not published or not available to people in writing).