= 1679
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast: English Café number 374.
This is English as a Second Language Podcast: English Café episode 374.
I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is at eslpod.com. Become a member of ESL Podcast and get the Learning Guide for this episode, which contains a complete transcript of everything we say, along with vocabulary words, definitions, sample sentences, cultural notes, and a whole lot more.
On this Café, we’re going to continue our series on famous Americans, focusing on the musician, Jimi Hendrix. We’re also going to talk about the idea of the melting pot, and what that means in American society. And as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café talking about a famous musician by the name of Jimi Hendrix. Jimi Hendrix was born in Seattle, Washington, a state on the Pacific coast of the U.S, in the northwest part of the country. Many consider him to have been one of the best electric guitar players in music history. But he was also a singer and a songwriter. As an elementary student, as what we would call a “grade school student,” Hendrix had the habit of carrying a broom everywhere he went. When we say someone had the “habit” (habit), we mean it was something that you did regularly. It was a custom. It was something performed even without thinking about it. You brush your teeth, perhaps, as a habit or you turn on the light when you enter a room. You don’t really even think very much about it. Well, Hendrix had the habit of carrying a broom with him. A “broom” is a long stick that has things on the bottom of it that help clean the floor. We use a broom for sweeping the floor.
Well, Hendrix didn’t sweep floors with his broom. He pretended that the broom was a guitar. He had a ukulele, which is a musical instrument that kind of looks like a very small guitar. A “ukulele” (ukulele) is a musical instrument popular in the state of Hawaii. Hendrix, however, taught himself to play this ukulele not by a book, but by ear. When we say someone taught themselves a musical instrument “by ear,” we mean that he just listened to the music and figured out how to play it by himself. He didn’t have any lessons and he wasn’t looking at musical notes on a piece of paper, either. He didn’t actually get his first guitar, surprisingly, until he was 15 years old. As he became a better player, he began to get what we would call “music gigs.” A “gig” (gig) is basically a job that may be short term, it might be longer term. We use the word “gig” in general to mean a job that isn’t like a regular job working for a company. It’s something specific and often is something associated with music. So, we might say, “He was playing local gigs,” meaning he was performing his music at a bar or at some other place in the place where he was living. Each one of those performances might be called a “gig.”
In 1964, Hendrix moved to New York City. He won first prize in a competition – a music competition at a very famous theater in New York called the “Apollo Theater.” I talked about that in a previous English Café. He ended up accepting a guitarist position – being a guitar player – for a famous group called the Isley Brothers. And that was the first opportunity he had to be officially or formally recorded in a studio. That’s where music is recorded and made into a record or an album.
In 1964, Hendrix also began performing with another famous musician of that time, Little Richard. Little Richard was famous for introducing a rhythm and blues style into rock and roll music. Rock and roll music, of course, was changing a lot in the early 1960’s and artists like Little Richard were influencing the direction of those changes by introducing more traditional rhythm and blues styles – styles that had been popular among African American musicians for a few decades. In 1966, Hendrix was in London, England and he decided to create a new band – a new musical group. He called it the “Jimi Hendrix Experience.” Now, why did he call it the Jimi Hendrix Experience? “Experience” is sort of an odd name for a group. No doubt, Hendrix was trying to show that his group was somehow different. It was unusual. It was like going and not just listening to music, but having this entire different experience, entirely different phenomenon almost.
He soon became popular in England and in France, and he began recording some of his first songs, some of his first singles. A “single” (single) is a song that an artist, a musician records and releases as an individual song. It’s not part of a larger collection of songs. It’s not part of an album. The first Jimi Hendrix Experience album was not until 1967 and it was called “Are You Experienced?”
Now “experienced” here means that you have done something in the past and there’s probably a sexual reference to that in the title. The album was very popular and Hendrix began performing a series of concerts in the United Kingdom, in Great Britain, as well as in Europe. During this time, Hendrix also developed a certain stage presence that was unique. “Stage presence” (presence) refers to how you act up on the stage, how you perform. Hendrix became known for playing his guitar very loudly and most importantly for a very virtuosic style. “Virtuosic” (virtuosic) means very skilled, with a very high level of ability – an expert.
Hendrix would play things that were extremely difficult to play on the electric guitar. Hendrix also had a reputation for being wild, a little bit out of control, unpredictable, for doing unusual things like playing the guitar behind his back or playing the guitar with his teeth. Hendrix was very popular in Europe, but originally, initially, he wasn’t very well known here in the United States; that is, until his band performed at a musical festival called the “Monterey International Pop Festival.”
A music “festival” is when a number of different musical groups come together for two, three, maybe four days, and they all perform music in one usually, large area, a large auditorium, or a large place to listen to the music. One of the most famous music festivals of the late 1960’s was the Monterey International Pop Festival – “pop,” standing for popular music. It was held in Monterey, California, which is a city, sort of in between San Francisco and Los Angeles, closer to San Francisco, in 1967. At least, that’s when Hendrix performed at the festival.
The festival was attended by many people and a lot of reporters who recorded, who reported how Hendrix, as one of his crazy on-stage performances, burned and smashed his guitar at the end of his performance. “To smash” (smash) means to hit something very hard in order to destroy it. Burning and smashing guitars was part of Hendrix’s stage presence. It’s something that another music group called “The Who” also adopted. Hendrix was very well received at this festival. A lot of people realized what a great musician he was and he continued then later, to play other concerts in the United States as well as record new albums. Hendrix was known for being a great guitarist, but he was also known for his drug and alcohol use, as were a lot of musicians, even musicians today. Things don’t change. He often became very angry and violent when he was drinking and using drugs.
He died, sadly, in London, in 1970 when he was just 27 years old. He died in what some people think are “suspicious circumstances.” Something that is “suspicious” (suspicious) is something that you have doubts about, something that appears to be strange, perhaps illegal, something bad that has happened. “Circumstances” just means situation. People believed – some people believed that Hendrix died under suspicious circumstances. There were a lot of questions about how he died. Alcohol and drugs seemed to be the cause of his death. Some people say he might have committed suicide. A few people think he might even have been murdered.
Hendrix died, in any case, as a very young man. But he had a very lasting or on-going, permanent effect on rock music. Many other rock bands tried to imitate or copy his style, both of his music and his stage presence. Hendrix won many awards during his lifetime and was named by Rolling Stone magazine in 2011 as the greatest guitar player of all time. And that may well be true if we’re talking about the electric guitar in particular. I have to say, I’m not really a big fan of Jimi Hendrix. I had friends in the late 70’s who listened to all of his music. I was a little less interested but I recognize that he was, in fact, a great guitar player.
Now let’s turn to our next topic, which is really a metaphor that’s used in American society. A “metaphor” (metaphor) is a way of describing something by calling it something else. For example, we have an expression, “He’s a wet towel,” or “He was a wet towel.” Well, a “wet towel” is a piece of fabric that normally you use to dry yourself after you take a shower. When you do that, of course, it becomes wet and heavy. But when we say someone was a wet towel, we mean that you were having a good time, maybe you were laughing, and this person somehow said something or did something that made you not laugh, that made everything sad or that wasn’t very exciting or interesting. “He was a wet towel.” That’s an example of a metaphor.
The metaphor we’re going to use today is a “melting pot.” “To melt” (melt) usually means to go from a solid form of some substance to a liquid form, often when you apply heat to an object. So, you might have a candle and you light the candle, you make the candle begin to burn and the candle begins to melt. The heat begins to interact with the wax and the wax goes from solid to liquid, it starts melting. A “pot” (pot) here means, a large container, often used for cooking. If we put these two ideas together, melting pot would be a large container where things melt – things go from solid to liquid. But more importantly, they combine together. So, if you put a bunch of different candles in a big pot and you melted them all, they would all mix together, you couldn’t tell which one was which because they would turn into this liquid and mix together.
The metaphor of melting pot is used to describe how immigrants to the United States – people who come from other countries to live here – are assimilated into American culture and American society. “To assimilate” (assimilate) means to become part of a group so that no one can tell that you weren’t a member of that group originally. The idea of the melting pot in the United States is how we have people from all over the world to come to this country and over time, they begin to have similar ideas, similar philosophies. They’re like candles melting together or maybe butter melting together.
The melting pot metaphor became very common in the late 18th century, in the late 1700’s in the United States, and is still used today. It became especially popular in the 1970’s when the United States, having changed its immigration policy in the mid 1960’s, started to receive, again, a very large number of immigrants. The United States always had immigrants up to the early 20th century, but the immigration laws changed and for a period of, oh, about 40 years, there weren’t as many immigrants coming to the United States as there were in the late 19th century, early 20th century.
Now, that situation changed again in the 60’s and by the 1970’s, we were getting more and more immigrants, immigrants not just from Europe where traditionally immigrants had come from, but also from Asia, from Africa, from Latin America. There was a movement in the United States, especially among some of the newer immigrants, to value the differences that people brought with them. This idea became known as “multiculturalism.” “Multi” means many. And the “multiculturalism” idea said people don’t have to change when they come to this country. There doesn’t have to be a melting pot. They can keep some of their original ideas and traditions. So, there are basically these two ideas about what should happen to immigrants, not just in the United States, but, of course, in any country.
Those who advocated or said we should adopt a multicultural approach used a different metaphor, the metaphor of a mosaic. A “mosaic” (mosaic) is a kind of artwork that’s created by putting very small pieces of tile, ceramic or stone, possibly glass of different colors and when you look at it from a distance, it has a certain image. Other people use the metaphor of a salad bowl, where you had different elements together, but they all stayed separate in some way, they didn’t melt together, which is the correct metaphor. Well, that’s a continuing debate in the United States.
Most people, I think, recognize that different cultures bring different gifts in their own traditions to the United States. People also recognize that in order to live as one country, we all have to share some ideas, some common vision. And exactly what the correct mix of those two are, is a constant topic of not only conversation among Americans, but also of policy, of what our government should do to encourage one or the other vision of the U.S.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Enrique (Enrique) in Guatemala. Enrique wants to know why, in something he read, the state of Delaware was referred to as the “first state.” This is an interesting question. What does it mean when people say, “This is the 1st state,” “This is the 20th state,” “This is the 50th state.” Originally, when the United States began with the U.S constitution in the late 1700’s, there were 13 colonies – 13 states. After the U.S passed a constitution, the states had to approve the constitution. They had to say, “Yes. I agree. I want to be part of the United States.” Each individual state had to say yes.
Delaware was the first state to say yes, and therefore, we call it the first state. But really, all 13 states agreed to it fairly close in time. But Delaware was the first. As the United States grew, new states were added and those states, of course, would’ve been the 14th, 15th, 16th and so on. My home state, Minnesota, was the 32nd state. It became a state in 1858. California was the 31st state. It became a state in 1850. Although, generally, the states entered the union, the official federal government, going from east to west, there were some exceptions to that. California is one of those that entered the union a little early, if you will, because a lot of people came here after gold was discovered in California in 1849. But going back to this whole question of numbers, the number refers to when they entered the United States, when they became one of the 50 United States. The last two states to become states where Alaska, that was state number 49 and Hawaii, that was the 50th state. In fact, there’s a popular television program called Hawaii 5-0. The 5-0 refers to the fact that it is the 50th state of the union.
Our next question comes from Ana Laura (Ana Laura) in Argentina. Ana wants to know the meaning of an expression she heard, “by any stretch of the imagination.” “By any stretch (stretch) of the imagination” means as much as anyone could imagine. It’s typically used in a negative way. “He’s not the best football player by any stretch of the imagination,” meaning even if you tried to imagine something crazy, he wouldn’t be considered one of the best athletes. It usually means “at all,” “in any way.” We usually use this phrase to criticize or say something negative about something and hence, we usually say, “not by any stretch of the imagination.” “She’s not ugly, but by no stretch of the imagination would you describe her as beautiful.” Or “This is a nice house, but by no stretch of the imagination could you call this a beautiful house.” Or “By no stretch of the imagination would this red dress be something you would wear to a funeral,” when someone dies.
Norbert (Norbert) originally from Poland, now living in Germany, wants to know the meaning of an expression he heard or read, “to play it fast and loose.” “To play it fast and loose” (loose) means not to do things the way they are supposed to be done, especially when it’s being done to benefit you, personally. More generally, it means to be careless, not to pay attention to the details, not to do things right, to ignore the rules – that’s also another way of using this expression. One common use of this expression is “He’s playing fast and loose with the truth,” meaning he’s lying, he’s not being accurate. Or “You can’t play it fast and loose with your girlfriend’s feelings.” “If you don’t love her anymore, you have to tell her.” So, it can also be used sort of as being dishonest and as I say, it’s often used in connection with the word “truth.” In other contexts however, it means to be careless, not to be careful. And of course, if you’re not careful sometimes, you can damage or hurt something. That’s also a use of this expression.
If you have an expression you’re wondering about and would like us to discuss, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
habit – something ones does regularly without even thinking about it; an activity that one does routinely
* Jolene has a habit of leaving her dirty clothes on the floor, rather than putting them in the laundry basket.
broom – a tool with a long handle used for sweeping floors
* Karol got the broom out of the closet to sweep up the mess that the baby had made on the floor.
ukulele – a musical instrument similar to a small guitar, but with only four strings
* Mel is in a Hawaiian band. He sings while Lailani plays the ukulele.
by ear – learning music by listening to how different musical combinations sound, without lessons and without learning how to read music
* Amin learned to play the guitar by ear and can play nearly any song he hears on the radio.
gig – a live (not recorded) musical performance; the hiring of a musician to play
* As a classical pianist, Boris plays a lot of wedding and formal reception gigs.
stage presence – the ability to get an audience’s attention by how one appears or behaves
* From an early age, Bonnie’s parents knew that their daughter had great stage presence because of the way people stopped to listen to her whenever she sang.
virtuosic – very skilled; with a master-level ability and expert techniques, often said of musicians
* Did you know that Clyde is a virtuosic clarinet player?
to smash – to hit something very hard so that it is crushed; to destroy something by hitting it very hard so that it is flat or in small pieces
* The thief smashed a window to get inside the house to steal the computer.
suspicious circumstances – in a situation with many unanswered questions; with the possibility that something unlawful or strange may have occurred
* My co-worker left the company under suspicious circumstances, but none of us knows what really happened.
metaphor – a way of describing something by calling it something else; a way of speaking or writing in which one uses words to describe something not meant literally
* This simple story about a growing tree is a metaphor for how people should live their lives.
melting pot – the idea of how people who come from other countries to live in the United States are made part of American culture and society
* Our church is like a melting pot, welcoming people from every background.
to assimilate – to become part of a group and to be accepted into that group
* It’s been difficult for female athletes to assimilate into all-male teams and to be truly accepted.
mosaic – a type of artwork that creates a large image by gluing together many smaller pieces of tile, ceramics, stone, or glass with many different colors
* This palace has a beautiful 12th Century mosaic showing the rise of the king.
by any stretch of the imagination – as much as anyone could imagine; at all; in any way
* William is good looking, but he’s not the handsomest man I’ve ever seen by any stretch of the imagination.
to play it fast and loose – to ignore proper behavior or how things are generally done, especially when it suits one's purpose; to be careless about accuracy (being precise or correct); to behave inappropriately, ignoring guidelines and how things are generally done
* Playing it fast and loose with your taxes is a sure way to get investigated by the government’s Internal Revenue Service.
What Insiders Know
Jimi Hendrix’s Gravesite
Many of Jimi Hendrix’s fans were very sad when he died in 1970. Hendrix was first “buried” (for a dead body to be placed in the ground) in a simple “cemetery” (the place where people are buried after they die) in Seattle. However, Jimi Hendrix’s father did not think that this cemetery was good enough for his son, a man who had greatly changed music over the “course” (time period) of his short career. Although Hendrix’s father, James “Al” Hendrix, did not have much money, he began working to make a “memorial” (a place where people could go to to remember someone) for his son in the Greenwood Memorial Park in Renton, Washington.
Al Hendrix’s “original” (first) plan was to have Jimi himself and three other family members buried at the new gravesite, but his family kept growing and he didn’t have enough money to make a memorial for Jimi, in addition to all of his family members.
In 1995, however, Al was finally given the rights to the Jimi’s “estate,” meaning that he would get the money Jimi had made from making music. This gave Jimi’s father enough money to build the memorial at the Greenwood Memorial Park, as well as to buy “burial plots” (small, individual pieces of land where the dead are buried) for fifty-four other members of the Hendrix family.
Unfortunately, Al Hendrix died before the memorial was completed, but the rest of his family worked hard to build it the way he wanted it. Now, the memorial is still “under construction” (not finished), but the plan is to eventually open this place for Hendrix’s fans to go to remember him.