= 1702
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 397.
This is English as a Second Language Podcast’s English Cafe episode 397. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website, won't you, at ESLPod.com. Download this episode's Learning Guide, an eight to ten page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to cover one main topic, continuing our series on American Presidents. Today we're going to talk about the 29th president of the United States, Warren G. Harding. You may not have heard of Mr. Harding – President Harding to you – but I think you'll find his life interesting. And as always, we’ll answer a few of your questions. Let's get started.
This Café begins with a continuation of our series on American Presidents. Today, we’re going to talk about the 29th president of the United States, Warren G. Harding, who was in office, or served as president, from 1921 to 1923. Harding is an interesting president in that some people think he was, perhaps, our worst president. Well, let’s talk about him and you can make that decision.
Harding was born in the state of Ohio in the Midwestern part of the United States – or the eastern central part of the United States perhaps, more accurately – in 1865, right at the end of the U.S Civil War. He was the oldest of eight children. His father eventually became a doctor, a physician.
Harding was not a good student. He went to college for three years, then tried a lot of different kinds of jobs. He wasn't very successful at most of them. Finally, he decided to buy a newspaper – a small newspaper – in 1884. He married seven years later, in 1891, and his wife turned out to be a pretty good businesswoman. She helped him make the newspaper successful. In fact, it became very successful.
Harding began to become famous in his town and in his state. He made a few unsuccessful bids to become the governor of Ohio. The governor is the leader of the state. The expression, “to make a few unsuccessful bids” (bids) means to try to get something, usually in an election, but fail to do so.
I had an unsuccessful bid to be president of my eighth grade class when I was in junior high school – that's true. I tried to become president of our class. Every class in American schools, at least in many schools, have a president they elect, a leader. I tried to become the president and I failed. I had an unsuccessful bid. That was the end of my political career.
Well, it was not the end of Warren G. Harding's political career, when he made some unsuccessful bids to become governor. In 1915, he was successful in becoming a U.S. senator. He represented Ohio in the U.S. Senate, in our nation’s capital, in Washington, D.C., from 1915 to 1921.
The interesting thing about Harding is that most historians don't think he was very smart, don't think he was very intelligent. He was, however, very handsome, very good-looking. He was sort of the George Clooney of politicians. He was a very attractive man and he looked like a leader. So the leaders of the Republican Party in Ohio, and later in the United States, saw Harding as a good person to run for office because he was good-looking and, honestly, that can often help in politics. I consider myself the Warren G. Harding of podcasters. Of course, I'm the only one who thinks that.
When Harding was in the U.S. Senate, he was often considered someone who was a “fence sitter.” A “fence” (fence) is something you put up between two properties usually, to keep people out of your property, out of where you live or out of your area. “To sit on the fence” means to not be able to make a decision or to be unwilling to choose one side or the other, especially in politics. “To be a fence sitter” would be to be someone who doesn't want to make anyone angry, so they don't make a decision or they don't choose one side versus the other. They say, “Well, yeah, maybe that, but maybe that, too.” That was Warren G. Harding.
When Harding ran for president, or tried to be elected president, in 1920, he focused on three main things that he believed would help the country – the United States – after World War I. Remember, the United States got involved in World War I in Europe in 1917, although the war had started before then, of course.
Now that the war was over, Harding felt that the country had to make some changes. He argued for three basic political ideas. The first was isolationism. “To isolate (isolate) someone” is to keep them from talking or interacting with other people. In politics, “isolationism” is the idea that a country should only focus on itself and not become involved in other countries’ businesses, other countries’ affairs – even get involved in international agreements with other countries. “Isolationism,“ believe it or not, is actually a fairly common political theme in American history, during certain parts of our history. Some people, probably in other countries, would hope that it would be more of a theme in our politics; that is, that the United States would not get involved in the affairs of other countries. But isolationism in the case of Warren G. Harding meant no longer getting involved in European problems, European politics, and focusing only on United States.
Harding was also a believer in “nativism.” “Nativism” (nativism) is the practice of giving special treatment to people who have lived in the United States. However, in American politics, nativism was really an anti-immigrant philosophy or set of policies. “To be a nativist” would be to be against immigrants coming in. Remember that in American history, we had a huge number of immigrants, mostly from Europe, come to the United States in the late 19th and early 20th centuries. Then, after World War I, in part because of the political ideas of people like Warren G. Harding, the United States limited or restricted immigration, and that limit or restriction on immigration lasted from the middle of the 1920’s all the way up to the middle of the 1960’s, when the U.S. government changed its policy and it started allowing more immigrants to come to the United States. Harding was responsible in part for the popularity of the nativist or anti-immigrant ideas in American politics.
His third idea was to end government activism. “Activism” is when a certain group, in this case, the government, tries to solve the problems of society. Government, Harding felt, wasn't able to do everything everyone wanted it to do, and so he wanted to end government activism. He called his platform, his set of ideas, “A Return to Normalcy.” “Normalcy” (normalcy) is the situation or condition of being normal, of not being unusual. Harding believed that the United States had to change during World War I in order to help win the war. But now, he wanted to go back to the way things used to be, to go back to being “normal,” and he felt that these changes, especially isolationism, would help the United States do that.
Harding's campaign or his effort to be elected president in 1920 was considered by many people to be one of the first truly modern election campaigns. By that, I mean that he used a lot of advertising techniques in this election, including sound recordings and newspaper ads and billboards and even people who would call on a new device that many Americans owned – a “telephone.” You had people calling on the telephone, what we now call “telemarketers,” to convince people to vote for Mr. Harding.
Harding also was helped, some people say, by the fact that he was in fact, so good looking, so handsome. Nineteen twenty was the first year in which women were allowed to vote for a president in the United States. Some people say that a lot of women voted for Harding because he was so good looking. That's probably why I was not elected president of my eighth grade class. I didn't have that handsome quality that Warren G. Harding had.
Harding won the election in 1920, and he won “big” – that is, he won by a large margin, by a large percentage. He received 60% of the popular vote – the votes of the people. He was inaugurated, or became president, in 1921. The ceremony to make someone a president, or to begin a presidential term, is called an “inauguration” (inauguration). An inauguration is when we celebrate a new president’s beginning of their term of office. We have an inauguration every four years, at least. Harding was inaugurated in 1921, and many people were happy to see this return to normalcy.
However, Harding, remember, was not the brightest person in the United States. He was not the most intelligent politician. He may not have been himself dishonest, but he unfortunately had a lot of people in his administration, people that he had hired to work in the government, who were themselves not very honest. Harding's government, in other words, had a lot of what we would call “corruption.” “Corruption” is when you have dishonest or unethical behavior, especially in a government. In Harding's government, there were many instances of “graft.” “Graft” (graft) is basically bribery – when people give money to a government official so that they will get some sort of favor in return.
For example, one person in Harding's government sold government ships, government boats, to private companies at a very low cost and in return, these companies gave this individual a lot of money secretly. That was an example of the kind of corruption that you found in Harding's government in the early 1920’s.
Harding tried to do a few good things for the American people while he was president. He established or began something known as the “Veterans Bureau.” A “veteran” (veteran) is someone who has served in the military, in a war, and then returned home. The Veterans Bureau or the veterans department helped veterans coming back from, in this case, World War I, get jobs and become members of society again.
In international affairs, Harding “held true to” his promise of isolationism. “To hold true to something” means that you do what you promised to do. Harding promised that his government would have an isolationist policy in international affairs and that is, in fact, exactly what happened. He did not join the League of Nations. He did not try to get involved in politics in other countries, especially in Europe. He was a supporter of “disarmament.” “Disarmament” is the attempt to reduce the number of military weapons.
In 1923, Harding decided to take a trip with his wife, going to Alaska, which at this time was an American territory, now, an American state. On his way back home to Washington, D.C, Harding stopped in San Francisco, here in California. He went to his hotel room. He complained that he wasn't feeling well, and a few days later he died. Americans were shocked. They couldn't believe that this handsome, strong man would suddenly die of illness. Some people even thought that perhaps he was murdered, or he committed suicide. But the truth is he wasn't in very good health, and most people, most historians, now believe he died of a heart attack.
After he died, after he passed away, as what typically happens when a president dies in office, the vice president becomes president. Warren G Harding's vice president was a man by the name of Calvin Coolidge.
Historians today remember Harding as being a very affable president. “Affable” (affable) means friendly, someone who's easy to talk to, someone who is a good person to spend time with, who is entertaining, perhaps, who is charming. Harding was all of those things. However, he wasn't a very good president or at least, historians nowadays don't consider him to be a very good president. In fact, some people think that because of Harding's scandals – the corruption in his government – he was perhaps, maybe one of the worst presidents in American history. Sometimes being good-looking, being handsome, isn't always enough.
Now let's answer some of the questions you have sent to us.
Our first question comes from Reiko (Reiko), living here in the United States, in Indianapolis, Indiana, in the Midwest part of this large country of ours. Reiko wants to know the meaning of the words “wet,” “muggy,” and “humid,” three adjectives we use to describe often, the weather.
Let's start with “wet” (wet). “Wet” means covered with water or some other liquid. That's one meaning of wet. However, when we talk about the weather, “wet” can simply mean “rainy.” We’re getting a lot of water falling down from the sky – that is to say, rain. “It's a very wet out there,” you might say. Or “It's going to be a wet day.” These expressions mean it's going to rain today or it's going to be rainy.
“Muggy” (muggy) means the same as humid. It's really very humid. Typically, “muggy” is when you have a very high temperature and there's a lot of water in the air, a lot of moisture in the air. It's not raining, but there's a lot of water in the air so that it feels very uncomfortable. “Muggy” would be used to describe, for example, the weather in southern Florida in August or along the ocean in the summertime, when it's very hot and there's a lot of water in the air. That would be “muggy.”
“Humid” is also related to the amount of water in the air. “Humid” doesn't always describe a weather condition. It does, however, always mean having a lot of water in the air. “Humid” is a more general, perhaps a more neutral term. To say, “It's humid out,” doesn't always mean you don't like the weather. But “muggy” is always a critical or negative way of describing the weather – weather with a lot of humidity.
“Humid” can also refer to the situation inside of a house or inside of a room that perhaps has too much moisture in it. When I was growing up, during the wintertime, it would be very dry. So, we had a little machine called a “humidifier” which tried to put more water into the air, more humidity. There, humid was not a bad thing. It was considered a good thing. “Muggy” is always considered a bad thing, and describes the weather in general, not the condition of the air inside of your house.
Our next question comes from Norbert (Norbert), originally from Poland, now living in Germany. Norbert wants to know the difference between “intense” and “intensive.” “Intense” (intense) means strong or extreme. “I have intense pain” means I have a lot of pain. Or, “There is an intense heat when you go to the desert.” There is a very strong heat, in this case, a very high heat.
“Intensive” (intensive) also means in a strong way or to an extreme amount, or extreme degree. The difference between “intense” and “intensive” is that “intensive” is usually used when the situation is being forced on someone, or is being made to happen or “imposed,” we might say, on someone. For example, a student could receive “intensive instruction.” The student is receiving this very strong or large amount of instruction from a teacher. That would be intensive instruction. Or the police could be talking to someone and using intensive questioning, very strong questioning, asking them over and over again. It's something that one person is doing to another person.
“Intense” is a little more general. It's something that just happens. It's not something that's caused by someone else. So, when we say, “There is an intense heat in the desert,” we don't mean that someone is going out and causing the heat. We mean that it's a natural, if you will, “phenomenon.”
We could also talk about different senses, such as sight, or touch, or smell, or taste, that could be linked up with this adjective “intense.” “There is an intense smell in the air when my neighbor is cooking.” It's very strong. It's a little too strong. I don't like it very much.
More recently, people have started using the word “intense” to describe an experience where they had to go through some sort of extreme emotion or difficult situation. It can even describe a person. “She's really intense.” That means that she's very focused but also someone who perhaps takes things to an extreme degree, who maybe talks too much or is very concentrated in such a way that she doesn't pay attention to anyone around her. “Intense,” used in that way, is not always a negative thing. It could be considered a positive thing. It's definitely related to a strong emotional effect that something has on you. It could be a movie. It could be a situation. It could be an experience where, for example, you're driving your car and someone almost hits you, and afterwards you might say, “Uh, that was intense,” meaning that was a very strong emotional impact on me.
Finally, Bruno (Bruno) in Brazil has a question that does not begin with a “B.” It begins with an “S.” Bruno wants to know the meaning of the phrase, “Such a.” “He’s such a good friend.” “She is such a complainer.” She's always talking about what's wrong. Or, “He is such a good artist.” In those examples, “such a,” usually means very much. It's a way of emphasizing, you might even say to an extreme. “He's such a good artist” means he's a very good artist.
“Such a” can also mean something that is unusual, something that is full of surprises, either good or bad. “Such a life I have had.” That could mean I had a very good life. It could mean I had a very bad life.
When “such a” is used with an adjective and a noun together, as in the example, “He's such a good artist” – “good” is an adjective, “artist” as a noun – it means this person is very much an artist. “Such a” means very when used with an adjective and a noun. When it's just used with a noun, as in the sentence, “I have never seen such a color before.” It means it's unusual. It's not normal.
If you have a question or comment for us, we’ll be happy to try to answer it here on the Café. Just e-mail us at eslpod@eslpod.com. We get more questions than we can possibly answer here on the Café. So, I apologize if we’re not able to answer all of them that you e-mail us, but do e-mail us and we'll do our best.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2013 by the Center for Educational Development.
Glossary
to make a bid – to try to get something; to try to be successful in doing something
* You can make a bid for the manager’s job, but I think the boss is going to hire her daughter for the job.
fence sitter – someone who cannot or will not make up his or her mind and doesn't know or will not say if he or she is for or against something
* Right now, we have six people who support the proposal and four people against it, with five fence sitters.
isolationism – the idea or policy that a country should focus on itself and not become involved in other country's affairs or even in international agreements
* Our country cannot continue its isolationism while our neighboring country’s leader is killing his own people.
normalcy – the state of being normal, not unusual; being typical or expected
* When the children’s grandparents returned home after a long visit, life returned to normalcy.
campaign – a set of actions to achieve a goal; a series of actions to try to win an election (the selection of someone using voting procedures)
* Laura’s campaign to get her coworker and competitor fired isn’t working.
telemarketer – a person whose job is to call people on the telephone, usually to sell them something or to gain support for someone or something
* We don’t answer our home telephone in the evenings because that’s when telemarketers typically call.
corruption – dishonest actions, usually among people in power and involving bribery (paying money in exchange for something)
* The mayor said that her mission is to eliminate corruption from the tax assessment office.
graft – bribery; the act of someone receiving money illegally or unfairly, usually in exchange for something
* Two of the top officials in McQuilanland were arrested for graft.
veteran – a person who has served in the past in the military and fought in a war
* When will these veterans get the medical services they need?
to hold true to – to do what one has promised or what one said one would do, not changing one’s mind
* We must hold true to our beliefs even when criticized and laughed at.
disarmament – the reduction of military weapons and/or the withdrawal of soldiers
* Why can’t our two countries agree on disarmament if that is what both nations want?
affable – friendly and easy to talk to
* Paul is so affable that he becomes friends with nearly everyone he meets.
wet – covered with water or another liquid; rainy
* Jelissa put a napkin under her glass of cold water to prevent the new table from getting wet.
muggy – containing a lot of moisture in the air; damp
* Nobody wants to play soccer when it’s so hot and muggy outside.
humid – containing moisture in the air
* It feels humid in the kitchen when Dad is cooking and boiling something in every pot.
such a – to an extreme; very; eventful; unusual; full of surprises (good or bad)
* It’s such a treat to have all of my children and grandchildren visiting for the holidays!
What Insiders Know
President Harding’s Radio Conferences
Today, we are able to see American presidents make important statements and “speeches” (talks given to an audience about a specific topic) on television. But before the “advent of” (invention of; arrival of) television, presidents reached the American “public” (people) through the radio.
The first president to reach a large audience through the radio was Warren G. Harding on June 14, 1922. He gave a speech “in honor of” (remembering and giving respect to) Francis Scott Key, the man who wrote the “lyrics” (words to a song) to the American “national anthem” (a country’s official song), the “Star-Spangled Banner.”
During President Harding’s “presidency” (period of time when he was president), he worked toward establishing “regulations” (rules; laws) for “broadcast” (sent through airwaves so that many people can hear or see) radio. “Up to that point” (before this time), professional and “amateur” (not professional) broadcasters could use the airwaves without very many rules.
In 1922, he began a series of Radio Conferences that brought together 30 representatives that included amateur radio broadcasters, government “agencies” (departments), and radio and broadcasting companies. President Harding saw several problems that needed to be solved, including the “lack of” (not having enough of) rules for advertising on the radio and interference of amateur radio operators with government broadcasts.
After a second Radio Conference in 1923, the government successfully got power “to regulate” (make rules for) radio broadcasts, including how many and which hours broadcasts can be made, and who can use the “wave lengths” (broadcast frequencies) for the good of the public.