= 1694
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 389.
This is English as a Second Language Podcast’s English Café episode 389. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store, with additional courses in English you may be interested in.
On this Café, we’re going to continue our series on famous American songs, focusing on a folk song that I learned as a child – “Red River Valley.” We’re also going to talk about how something called recall elections work in the United States. And as always, we’ll answer a few of your questions. Let's get started
This Café begins with a continuation of our series on famous songs. Today we’re going to talk about a folk song, a traditional song called “Red River Valley,” although it’s sometimes known by other names. It has other names that people would recognize it by, including “The Cowboy Love Song” and the “Bright Laurel Valley.” Those are actually songs with different words, but the same melody, the same song. They have different, what we would call, “lyrics” (lyrics), or words that are sung.
There's a lot of disagreements about the origins of this song – where this song came from. Some people “trace the song’s origins” to the Red River Valley in Manitoba, Canada, in the late 1800’s. The phrase “to trace (trace) the origins (origins) of something” means to study something’s history, to determine where it came from. We might trace the origins of a story. We may find out where the story started. The origin is the place where it began.
The origins of this song, some people say, come from an area in Manitoba, Canada, which is north of Minnesota, called the “Red River Valley.” A “valley” is a low part of the land in between two mountains. Some people think the original song came from the eastern United States, from the state of Pennsylvania. Other people say, “No, it came originally from Europe.” We’re not sure exactly where it came from.
We do know that it became very popular in the late 19th century in the United States. It remained popular at least through the 1960’s and 70’s, because that's when I learned it. I’m going to sing part of the version that I'm most familiar with, that I learned as a child in school. The song expresses the sorrow, the sadness, of someone who has to say goodbye to someone they love. I'll sing it first and then we'll talk about what the lyrics mean in a minute.
From this valley they say you are going.
We will miss your bright eyes and sweet smile,
For they say you are taking the sunshine
That has brightened our pathway a while.
The verse, the part of the song, begins “From this valley they say you are going.” They say you are leaving this valley, this area. “We will miss your bright eyes and sweet smile.” “Bright eyes” would be eyes that are full of life, that are happy, that are cheerful. A “sweet smile” would be a nice smile, a pleasant, beautiful smile.
The second part of the verse is, “For they say” – people say – “you are taking the sunshine.” The “sunshine” is the light we get from the sun during the day, but here, it's used really as a metaphor. It's an example to show that by leaving, you are taking away the sun. That's what the effect is, that is what it seems like to us. “You are taking the sunshine that has brightened our pathway a while.” “To brighten” means to make lighter, to shine on. Your “pathway” (pathway) is the place where you walk. It's the area where you are walking on. “A while” means for some time. So, “They say you are taking the sunshine that has brightened our pathway a while.” Your light, your happiness, has made everyone happy around you, and you leaving now is like the sunshine going away.
Let me sing that verse again and then will sing the second and somewhat more famous verse of the song:
From this valley they say you are going.
We will miss your bright eyes and sweet smile,
For they say you are taking the sunshine
That has brightened our pathway a while.
So come sit by my side if you love me.
Do not hasten to bid me adieu.
Just remember the Red River Valley,
And the one that has loved you so true.
The second verse is “So come sit by my side,” meaning come sit next to me – if you love me. If you don't love me, then go sit by someone else aside, but let's assume that the girl loves the boy here in the song. He says “Do not hasten to bid me adieu.” “To hasten” (hasten) means to rush, to hurry. Don't be in such a hurry “to bid me adieu.” “To bid (bid) someone adieu (adieu)” means to say goodbye to them, but it's a very poetic way of saying that meaning. I believe it is taken from the Old French,l “adieu” – probably it means “to God,” like in Spanish, we have “adios” to say goodbye. So the boy in the song says, “Do not hasten to bid me adieu.” Don't say goodbye so quickly.
“Just remember the Red River Valley” – the place where we live – “and the one that has loved you so true.” The phrase “so true” means truthfully, honestly, sincerely. It's a way of saying that I have loved you very deeply. So, it's a sad song, really. It's a boy or man saying goodbye probably to his girlfriend – the person that he loves – but it's also very beautiful melody, a very beautiful song in terms of the music. It is what some people might describe as “catchy” (catchy). A song that is “catchy” is a song that is easy to remember and easy to sing. It's those songs that you hear that you can remember even though you've only heard them a couple of times.
“So here's my number/Call me, maybe.”
That would be very bad example of a catchy song.
“Red River Valley,” or variations on the song, have been popular in the United States at least since the late 19th, early 20th centuries. The song has been recorded by some of the great American folk singers, such as Woody Guthrie and his son, Arlo Guthrie. It's also been recorded by the great Leonard Cohen. There are many, many other versions of this song. It has sort of a “Western” feel to it. Like a lot of country western songs, it has the plot, the story, of a woman leaving a man and a man being sad. That, of course, is true for a lot of music.
I learned the song in grade school from my seventh grade English teacher who taught us a lot of the traditional folk songs from the early part of the 20th and late part of the 19th centuries. This song is certainly familiar to most Americans, at least Americans of a certain age. That expression “of a certain age,” is used by people like me who know that some younger people may not remember, and so, they’re really saying “old people,” like me!
Now let's turn to our next topic, which is about American politics. We’re going to talk about a special kind of election. An “election” is when people go and vote for the person they want to be the mayor, the governor, the president or some other government official. A “recall” election is a special kind of election.
The verb “to recall” (recall) can mean a couple of different things. It can mean, when it's pronounced “re-CALL,” it can mean to remember. It can also mean to get something back that was sold by a company. A company may sell, say, a car, and then they discover there's a problem with the car. They “recall” the cars. They contact all the customers and say, “No, no. Don't drive that car. It's dangerous. Bring it back to us. We’ll give you a new one or we’ll fix it.” That's when a company recalls something it sold.
We can also use this same idea in talking about our elected officials. “To recall an official” is to remove them from office. Normally an election is when you vote for someone to be, for example, the governor or the mayor of your town. But to recall that person would be to take them out of that position. Perhaps they've done something wrong. Perhaps people aren't happy with them and they want to get rid of them before their normal time is over.
So, if you're the governor and you’re elected for four years, after two years, if people don't want you anymore, in some states, you can recall the governor. You can have what's called a “recall election.” Notice the pronunciation as a noun is different. As a verb, it's “re-CALL.” As a noun, it’s “RE-call.” A recall election is when the people vote to get rid of someone who is in office right now, someone who is serving as the governor, the mayor, or whatever. Another way of saying this is “to remove someone from office.” “Office” doesn't mean the room in a building. “Office” here means the position, the government position that this person has.
Recall elections began really in the early part of the 20th century – in the 1900’s. They were part of a political movement in American history called the “Populist Movement.” “To be popular” means to have everyone like you but, “populist” (populist) refers to a certain political movement that claims to represent the average person, the common person, especially compared to the rich and the powerful – the banks, the wealthy, people with a lot of money. A “populist movement” in politics in general refers to someone who tries to appeal to, or to get the votes of people, based on the fact that you represent the “average” man and woman, the poor people, the working people.
There was a populist political party in the early 20th century, and one of the things they did was try to change American government, to make it what they thought was more fair. So they put through a number of important changes in some states, and one of those changes was a recall election.
Now, recall elections don't take place in every state. Each state has its own laws. Here in California, there is a law that says that people can get together and remove someone from office by holding a special recall election. Recall elections usually are because the government official has done some sort of “malfeasance,” or is guilty of, we would say malfeasance. “Malfeasance” (malfeasance) is simply a long word meaning to do something wrong – to do something illegal, for example. But sometimes people can try to recall a political official because they just don't like what that person has been doing, or they don't think the person is been doing a very good job. In most states, you have to go around and get a bunch of people to sign what we would call a “petition” (petition). This is a piece of paper that says “I want this to happen.” I want this change to happen, and you sign it, and you get a bunch of people to sign it, and then you give it to the government and say, “Look all of these people want us to have a recall election.” That's basically how it works.
One of the most famous examples of a recall election was here in California just a few years ago, back in 2003. We had a governor by the name of Gray Davis. Gray Davis was the Democratic governor here. He was the leader of our state, the most powerful person in the state government. When he was first elected, he was popular, but then after the 2001 tech bubble burst – that is, when the economy got worse in 2000, 2001, with all the technology stocks doing so poorly – California of course, is the home of Silicon Valley, where have a lot of technology companies – so the economy here in California was very bad back in 2003.
People were looking for someone to blame, someone to say “You did a bad job! It's your fault!” And so they blamed the governor, Gray Davis. There was a recall election. Gray Davis lost, and the person who instead became governor was a man by the name of Arnold Schwarzenegger. You probably have heard of him. Arnold Schwarzenegger became governor and then was reelected governor a few years later.
There have been lots of recall elections in American history. There were at least 150 recall elections in the year 2011. So, this is still a very popular thing that happens in some areas. Nine people in those recall elections resigned. They said, “Okay, I quit,” and about 75 of them were recalled. So, about half of the time recall elections are successful. Sometimes they are not successful.
Another very well-known recall election was in 2011 in the state of Wisconsin, which is next to Minnesota in the Midwest part of the U.S. There, there was a Republican governor by the name of Scott Walker who got into an argument with the unions, with the public unions – the groups that represent people who work for the government itself. There was a disagreement over what is called “collective bargaining.” “Collective bargaining” is the right of employees, who in this case work for the government, to have a union and to be able to have the power of a union. A lot of people wanted to get rid of the governor and there was a recall election, but the recall election failed. The governor remained as governor, and as of the year 2013, he's still governor. He was the first U.S. governor to, if you will, “win” a recall election, where there was not enough votes to remove him from office.
My guess is we'll continue to have this tradition in American politics of recall elections. A lot of people consider it an important democratic protection against people who get into office, who become elected, and then don't do what they're supposed to do.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Korea, from someone with the initials “DS.” I'm not sure if that's a man or woman. DS wants to know the meaning of four different verbs that have similar meanings: “to reduce,” “to lessen,” “to decrease,” and “to decline.”
Let’s start with the first one, “to reduce.” “To reduce” means to bring something down to a smaller size, or to lower the price on something. It can also mean to use less of something. “We’re going to reduce our use of water.” We’re not going to use as much water anymore. Or, “We’re going to reduce our weight.” We’re going to try to lose weight, to have less of it. You could also reduce the price on something. If you're in a store, and you're selling something for $15, then you decide well I'm going to reduce the price to $10. I'm going to lower the price to ten dollars. All of those are uses of the word “reduce.”
“To lessen” (lessen) means to make less. We use “lessen” less frequently, not as much as “to reduce,” and it's typically used in sort of certain expressions, certain phrases. For example, we're going to try to lessen the impact of this strike, where people stop working. “Impact” is the influence or effect of something. “We’re going to lessen the impact.” We might also talk about lessening the severity of something. “Severity” (severity) is the strength of something. So lessen is used a little less frequently than to reduce.
The next word on our list is “to decrease” (decrease). “To decrease” also, like “to reduce,” means to make something smaller or lessen quantity or strength. We can decrease the prices. We can decrease the amount of money that we spend. We can decrease the size of the people who work for us – the number of people, that is, who work for us. You could also decrease your weight. You can lose weight, not be so heavy, we might say. Decrease and reduce a very similar in meaning and can often be used in the same sentences.
“Decline (decline) can also mean to have less of something, but when it has that meaning, it's usually more of a noun, used more as a noun than as a verb. It can be used as a verb. “The stock market declined today.” That means the stock market went down, the general prices were reduced, they decreased. All of those are similar ways of expressing the same idea. Decline, as a verb, can also mean to say “no” to someone, especially to someone who is inviting you to do something. “I declined the girl's invitation to go with her to a bar and have a drink.” (I'm a married man, after all!)
Marco (Marco) in Costa Rica in Central America, may be a married man. I'm not sure. He does have a question. Of that, I am very sure. He wants to know the meanings of the word “sort” (sort). “Sort” can mean type, kind or variety. That’s the most common meaning. “What sort of ice cream is this?” That means what kind of ice cream. For ice cream, we would might also say, “What flavor of ice cream is it?”
“What sort of person is he?” What kind of person is he? Is he a nice person? Is he a mean person? You could also say, “Well, he’s really not my sort,” meaning he’s not my type. He’s not my kind of person. That’s a little less common of a use. “Sort” is used a lot to mean “kind of” or “type of.”
Sometimes it can be used to mean something that isn’t exactly what you are describing, but it’s close. “He’s sort of sad.” That means he’s not sad but he’s a little bit sad. He’s sort of crazy. He’s not crazy, he’s not completely mentally insane, but he’s a little bit mentally insane – like my neighbor, for example.
“Sort,” as a verb, can also mean to arrange things based on some quality or category. For example, if you use a spreadsheet on your computer like Microsoft Excel, and you have a bunch of numbers in different columns, you can sort them from the highest to the lowest. You put the highest ones on top and the lowest ones on the bottom. That’s also “to sort.” Or you might take your clothes out of a dryer and put them on your bed and “sort” them. You separate them into different categories. That's another way of using sort.
There are a couple of other special uses of “sort.” We have the phrase “of sorts” (sorts). “He's a baseball player, of sorts.” That means that person is not very good at what they do. Or, we watched a movie last night that was “a comedy, of sorts.” That means it wasn't a very good comedy .It wasn't very funny.
“Out of sorts” means something very different. “Out of sorts” means you are not feeling well, or you're in a bad mood, or you’re depressed, or you're sick. You may say to your wife, “I'm a little out of sorts today,” or you may say to your boyfriend, “I'm feeling out of sorts.” You're not quite all together. Maybe you're feeling a little sad. Maybe you're just in a bad mood. Maybe you're just a little confused.
Our final question comes from Lynn (Lynn) in China. Lynn wants to know the difference between the word “intervene” and “interfere.”
“Intervene” (intervene) means to come between people because there is some problem, or to try to solve a problem that is happening among a group of people or groups of people. “I'm going to intervene when I see the children fighting.” I'm going to actually go over there and separate them, get in between them so they don't fight with each other. “Intervene” also can be something that isn't necessarily a physical act. You don't actually go over there and stand in between two people, but you get involved in the situation to try to solve a problem. The United States government has a history of intervening, sometimes, in the political crises of other countries. They come in and they think they're going to solve the problem. It doesn't always happen that way, but that's what they're doing. They're “intervening.”
“Interfering” (interfering) – the verb is “to interfere” – means to stop something from happening. It doesn't mean that there was a problem that you're trying to solve. It could be something going on that's normal and good, but then you go and you “interfere.” You stop it from going forward. You stop it from continuing. “Interfering” is usually a negative thing. “To interfere in something” is to stop something, and it's often done when the people don't want you to interfere. So, you may say to someone, “Stop interfering with my relationship,” or “Stop interfering with my work, you are bothering me.” You are preventing me from doing what I want to do.
If you have the sort of question you think we might be able to answer, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan thank you for listening. Come back and listen to is again right here on the English Café.
ESL Podcast's English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2013 by the Center for Educational Development.
Glossary
to trace (something’s) origins – to study something’s history and determine its past and how it became what it is today
* No one in this town has been able to trace the origins of this very old statue.
to hasten – to rush; to hurry
* We’re not able to offer those services now, but let me hasten to add that as soon as we get more government money, that will change.
to bid (someone) adieu – to say goodbye to someone
* In the story, the soldiers bid their loved ones adieu and went off to war.
so true – so or very truthfully, honestly, and/or sincerely
* No dog has ever been so true to its owner as Fido is to Mark.
catchy – easy to learn and stays with one for a long time, perhaps even remaining in one’s head so one cannot stop hearing it or cannot stop thinking about it
* This new song is really catchy and is easy to dance to.
recall election – a voting procedure that allows people to remove someone from an elected job or position
* The people of this state are tired of the governor’s broken promises and want a recall election.
to remove (someone) from office – to take away a person’s job, so that he or she can no longer serve or work in a government position
* The state treasurer was removed from office when it was revealed that he had lied about his qualifications.
Populist Movement – a political movement to give power to the people to control their government leaders
* People wanted to end government corruption as part of the Populist Movement.
malfeasance – wrongdoing; the act of having done something wrong
* As the new mayor of this city, I will not tolerate any corruption or malfeasance in my administration.
governor – the most powerful elected official in state government
* Governor McQuillan, will you support a tax increase for the middle class?
to resign – to decide to stop working in one’s job; to leave one’s job
* After a year of strong disagreements with the new president, Jelissa resigned her job to take another job with a different company.
collective bargaining – negotiations related to unions (organizations of workers working together to get more power, money, better working conditions, and more), where one person or group negotiates for the entire union
* Through collective bargaining, we hope to raise salaries and reduce work hours.
to reduce – to bring down to a smaller size, amount, or price
* George put up curtains on his bedroom windows to reduce the amount of light coming in in the morning when he’s trying to sleep.
to lessen – to make less, in amount or degree
* Melinda took some medicine to lessen the pain.
to decrease – to make smaller or less, in amount or strength
* Our decrease in sales this year is due to more competition.
to decline – to go down little by little, over time; to refuse in a nice way
* The demand for oil has declined over the years as people eat fewer fried foods.
sort – type, kind, or variety
* I’ve never seen this sort of cake before. What kind is it?
to sort – to arrange according to certain qualities; to put into different categories
* The teacher asked the children to sort the blue-colored items into this basket and the yellow-colored items into this box.
to intervene – to come between people or events, often because there are problems or problems are likely to develop if things continue
* The two men got into a fight, and if Liam hadn’t intervened, they may have hurt each other badly.
to interfere – to hamper; to try to stop the progress of something
* Why does your mother always try to interfere in the way we raise our children?
What Insiders Know
Valley Girls
There are many “valleys” (low areas of land surrounded by mountains) in the United States. However, the San Fernando Valley near Los Angeles, California, has become known as “The Valley.” The “stereotypical” (what everyone thinks is true but is not necessarily true of everyone) person who lives in The Valley is white, “professional” (someone who has a job that requires specific education), and wealthy.
In the 1980’s, the Valley girl stereotype became well known to people all over the country. A Valley girl is the teenage girl who lives in the San Fernando Valley area, and the stereotype of a Valley girl is a girl who pretty but not very smart. “Spacey” (not aware of what is going on around her) and “ditzy” (happy to not be very smart) are words usually used to describe a Valley girl. Valley girls talk with a very specific “dialect” (variety of a language, usually from a specific place). “Oh my God!” is one of the expressions Valley girls like to use most, said with a high-pitched voice that gets even higher at the end, to express surprise, pleasure, or any strong emotion.
Because Valley girls have such specific characteristics, they are easy “targets” (subjects) for humor. The musician Frank Zappa helped the stereotype of the Valley girls to became part of the “pop” (popular) culture in the early 1980’s. He wrote a song called “Valley Girl” and was sung by his daughter, Moon Unit Zappa, who “impersonates” (talks and acts like) a Valley girl. The “lyrics” (words to a song) include references to a Valley girl’s concern with clothes and how she looks, especially her hair and fingernails.
The image of the Valley girl also “inspired” (cause to happen) the 1983 movie Valley Girl. The movie was about a Valley girl who became unhappy with her boyfriend and fell in love with a boy from a different part of California and not in her social group. The girl is forced to choose between what will keep her popular with her friends, “namely” (mainly) dating someone from The Valley, and what she wants, dating this new boy.