= 0672
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 672: Asking for More Time.
This is English as a Second Language Podcast number 672. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download the Learning Guide for this episode that will improve your English – and make your teeth just a little whiter!
This episode is a dialogue between Dan and Marcia. It’s called “Asking for More Time,” more time to do something. Let’s get started.
[start of dialogue]
Dan: Hello.
Marcia: Hi, Dan. What’s the status on the project? We’re still on schedule, right?
Dan: Uh, well, I’ve been meaning to call you about that. We’ve had a slight delay.
Marcia: What do you mean by “slight”? Are you saying that you won’t be able to meet the deadline?
Dan: Not exactly. I’m only asking that you grant us a short extension.
Marcia: How short?
Dan: A week or two, tops. We hit a minor snag, but we should have everything up and running in no time.
Marcia: If the project has come to a grinding halt, then it doesn’t sound like a minor snag. We’re running on a tight schedule and we don’t have a lot of time to spare.
Dan: I know that all too well.
Marcia: Good, then I don’t have to spell it out for you.
Dan: No, you don’t. My head is on the chopping block and the clock is ticking.
[end of dialogue]
Dan begins by saying “Hello” to Marcia. Marcia says, “Hi, Dan. What’s the status on the project?” The “status” (status) is the current condition, the most up-to-date, the newest information we have about this project, this thing that you are working on. Marcia says, “We’re still on schedule, right?” “To be on schedule” means be on time, that you are progressing – you are moving forward just as you had planned. If you’re late in completing the different parts of the project, we would say you were “behind schedule,” and if you are making better progress than you anticipated – than you planned, then we would say you are “ahead of schedule.” So there’s “ahead of schedule,” “behind schedule,” and “on schedule.”
Dan says, “Uh, well, I’ve been meaning to call you about that.” “I’ve been meaning to” means I was planning on, I was thinking about it, I should have called you. He says, “We’ve had a slight delay.” “Slight” (slight) here means very small; “minor,” we might say. “Minor” (minor) is something that is not very important; the opposite would be “major,” something very important. But “slight” means minor, unimportant. There are other meanings for the word “slight,” and those can be found in our Learning Guide.
So Dan says there has been a slight delay. A “delay” is something that causes you to be behind schedule – to be late. Marcia says, “What do you mean by ‘slight’?” She’s asking Dan to say how unimportant or how minor this delay is. “Are you saying that you won’t be able to meet the deadline?” The “deadline” (one word) is the date and sometimes the time that something is supposed to be done, that something needs to be completed by. “The deadline is 5:30 p.m. on Friday.” That means whatever you’re doing has to be done by 5:30 in the afternoon on Friday.
So Marcia is asking not too bright, not too smart, we get the impression, Dan – we’ll call him dumb Dan – Marcia’s asking dumb Dan if he is going to be able to meet the deadline. “To meet the deadline” means to be completed before or by the deadline. Actually, I guess, Marcia says, “Are you saying that you won’t (that you will not) be able to meet the deadline?” Dan says, “Not exactly.” “Not exactly” means “no,” but it implies – it gives you the idea that there is something wrong. Now we find out what is wrong, what Dan is really saying. He says, “I’m only asking that you grant us a short extension.” “To grant (something to someone)” as a verb means to give someone something, usually officially, like a government giving something to one of its citizens or an organization giving something to an individual person. Here, it means really to give permission, to say “yes, okay.” Dan is asking for a short extension. An “extension” here means when you are given more time to do something. If the deadline was Friday at five p.m., and you’re not going to be finished by then, you might ask for an extension until Monday at five p.m.
Marcia says, “How short?” meaning how short of an extension. How much more time do you want dumb Dan? Well, she doesn’t say “dumb Dan,” but that’s what she means – right? So Dan says, “A week or two, tops.” “Tops” is an informal way of saying maximum, at most. In other words, it won’t be more than that. So, Dan says, “A week or two weeks, tops. We hit a minor snag, but we should have everything up and running in no time.” A “snag (or snag)” (snag) is a problem; a small problem, but still a problem that prevents you from completing something, that causes a delay. “Snag” has a few other meanings, and those can be found in the Learning Guide – of course! Where else would you find them?
Dumb Dan says, “we should have everything up and running in no time.” The expression “to have (something) up and running” means something will be working normally, functioning as it should function, doing what it’s supposed to be doing. Marcia says, “If the project has come to a grinding halt, then it doesn’t sound like a minor snag.” The expression “to come to a grinding halt” (halt) means to completely stop. You could have a car traveling down the street and suddenly you see a dog come out into the street and you step on, or press on, your brakes to stop the car, but you stop it very quickly. We would say “it came to a grinding halt,” it stopped quickly. Actually, we don’t use this expression very often in talking about actual movement; usually we use it in talking about some sort of project or process that stops, that suddenly stops, that completely stops. Marcia says if the project has stopped – if you’ve stopped making progress on it – then it’s not a minor snag, it would be a major snag. Marcia says, “We’re running on (meaning we’re operating on) a tight schedule and we don’t have a lot of time to spare.” A “tight schedule” is a situation where a lot of work needs to be done but in a very small amount of time. If you only have two days to finish writing a book, that might be a very tight schedule if you haven’t started writing already. By the way, the opposite of a “tight schedule” would not be a “loose schedule,” we wouldn’t say that. You might say something like, “We have plenty of time,” or even, “We have all the time in the world.” There’s no rush; there’s no hurry. With a tight schedule you have to hurry, you have to rush; you don’t have a lot of time.
Marcia says they don’t have a lot of time, they don’t have a lot of time to spare (spare). “To spare” is to have an extra amount of something. It’s used as an adjective when we are talking about something extra that you have. For example in your car, you should have a spare tire. That’s an extra tire to put on your car in case you have problems with one of them. In fact, we typically call it just “a spare,” using “spare” there as a noun. Here, it means they don’t have any extra time.
Dan says, “I know that all too well,” meaning I know it very well; I understand completely. Marcia says, “Good, then I don’t have to spell it out for you.” “To spell (something) out” can mean to give the letters in the word, like I spell out words like “spare” (spare). But the same expression also means to explain something in great detail, to talk about every little part of this thing you are trying to describe, to be very explicit. Marcia is saying that she does not need to spell it out for Dan – for dumb Dan; that’s another way of saying “I don’t need to explain to you how serious the situation is.” Sometimes, especially when we’re giving someone bad news or telling them something they don’t want to hear, we’ll use the opposite expression; we’ll say, “Let me spell it out for you. If you don’t give me my money I’m going to call the police!”
Dan says, “No, you don’t (you don’t need to spell it out for me; you don’t need to explain what will happen to me if I don’t finish this project on time – on schedule). My head is on the chopping block and the clock is ticking.” The expression “to have your head on the chopping block” means for one to be at risk of losing your job or otherwise having a very negative consequence if they don’t do what they’re supposed to do. It used to be, back in history and perhaps in some places still is, common to kill someone, especially when the government was killing a criminal, to put their head on a piece of wood and take a large “ax,” which is a sharp metal instrument used normally to cut trees, and chop or cut the head of the person off so that, of course, they would die. That’s the idea. Well, we don’t do that anymore, at least not very often. But the expression continues and it means now to be in trouble, to have some serious problems if you don’t finish or do what you’re supposed to do. Dan says, “the clock is ticking.” This means simply that there is very little time left before something happens. He has to hurry because there isn’t a lot of time left. “To tick” (tick) is the verb we use, or used to use clocks or watches because when the little wheel inside the clock moved around it made a little sound – “tick, tick, tick” – and that is why we talk about clocks ticking. Clocks don’t tick anymore – most of them don’t because they’re electronic, but we still have the expression.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dan: Hello.
Marcia: Hi, Dan. What’s the status on the project? We’re still on schedule, right?
Dan: Uh, well, I’ve been meaning to call you about that. We’ve had a slight delay.
Marcia: What do you mean by “slight”? Are you saying that we won’t be able to meet the deadline?
Dan: Not exactly. I’m only asking that you grant us a short extension.
Marcia: How short?
Dan: A week or two, tops. We hit a minor snag, but we should have everything up and running in no time.
Marcia: If the project has come to a grinding halt, then it doesn’t sound like a minor snag. We’re running on a tight schedule and we don’t have a lot of time to spare.
Dan: I know that all too well.
Marcia: Good, then I don’t have to spell it out for you.
Dan: No, you don’t. My head is on the chopping block and the clock is ticking.
[end of dialogue]
Our scriptwriter is always on schedule – usually ahead of schedule. That’s because it’s our own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
status – the current condition; the most up-to-date information about the quality, timing, or progress of something
* All of the employees are supposed to send weekly reports on the status of their work.
on schedule – on time; making enough progress so that something will be completed when it should be; expected to meet one’s deadline
* The buses are usually on schedule, but for some reason, my bus was 20 minutes late this morning.
slight – very small, minor, and unimportant
* We saw a slight increase in sales last month, but not enough to really make a difference.
delay – something that causes one to become behind schedule; something that slows one down and makes it difficult or impossible to finish something when it was planned to be finished
* When there’s a lot of snow and ice, expect a delay when driving across town.
deadline – the date and time when something is due or must be turned in; the time by which something needs to be completed
* The deadline for this grant proposal is Friday at 3:00 p.m. Do you think we can finish everything before then?
to grant – to officially give something to someone, especially giving permission or authority
* If the board of directors grants approval, we’ll be able to hire two new employees next month.
extension – the act of making something bigger or longer in space or time
* We are proposing a bridge extension that would reach to Main Street.
tops – maximum; at most
* We can pay you $11 per hour, tops.
snag – a problem; something that causes a problem or a delay, but that one probably will be able to find a solution for
* When the lead actress lost her voice, it was a snag for the show, but fortunately they were able to find another actress who could play her role.
up and running – operational; functioning normally
* The mechanic promised to have their car up and running again by the end of the day.
to come to a grinding halt – to completely stop; to no longer be able to work or operate at all
* Traffic came to a grinding halt during the snowstorm.
tight schedule – a situation when a lot of work needs to be done in a very short period of time
* The engineers are on a tight schedule to design the new freeway by the end of the month.
to spare – to have an extra amount of something
* Do we have any food to spare? I brought a few friends home for dinner.
all too well – very well; very familiar and very clearly understood
* - Did you know this town is expected to flood after tomorrow’s storm?
* - Yes, I know it all too well.
to spell (something) out – to explain something in great detail; to be explicit
* Let me spell it out for you: if you don’t make your mortgage payments, your bank will take away your home.
for (one’s) head to be on the chopping block – for one to be at risk of losing one’s job or otherwise suffering negative consequences if something does not go well, or if some result is not achieved
* Could you please help me with these preparations? My head is on the chopping block if the conference isn’t a success.
the clock is ticking – a phrase meaning that very little time is left before something else happens, implying that one should hurry up and do something
* Her birthday is tomorrow! I can’t believe you still haven’t bought her a gift. Hurry up and go to the store! The clock is ticking.
Comprehension Questions
1. What does Dan need in order to meet the deadline?
a) More money.
b) More time.
c) More staff.
2. What does Dan mean when he says, “My head is on the chopping block”?
a) He feels sick and has a lot of congestion.
b) He is very stressed out and has a bad headache.
c) He could lose his job if the project isn’t successful.
Answers at bottom.
What Else Does It Mean?
slight
The word “slight,” in this podcast, means very small, minor, and unimportant: “The baby has a slight fever, but the doctor said not to take her to see him until it reaches 104.” Or, “Please let us know if there’s even the slightest possibility you might be able to come to our home for Thanksgiving.” The word “slight” can also describe someone who is very thin and possibly unhealthy: “Janik is a very slight boy, even though his parents are always trying to feed him more.” The phrase “to not have the slightest idea” means to not be aware of something at all: “I’ve known them for quite a while, but I didn’t have the slightest idea they were brothers! They don’t look anything alike.”
snag
In this podcast, the word “snag” means a minor or medium-sized problem, especially something that causes a problem or a delay, but that one probably will be able to find a solution for: “The engineers hit a snag when they couldn’t find a way to keep the processor cool enough for the software to run.” A “snag” is also part of a tree that can be seen above the water when the rest of the tree is hidden under the water: “Watch out for that snag, or it might tear a hole in your raft.” The phrase “to snag” means for a piece of clothing to be caught on something that sticks out, usually stretching or ripping as a result: “Yolanda’s dress snagged on the corner of the countertop and ripped.” The verb “to snag” also informally means to get something: “How did you snag such a great deal?”
Culture Note
Excluding “territories” (areas of land that are parts of the United States, but are not states), the United States has six “time zones” (vertical geographic areas that experience the same time). Their “boundaries” (the dividing lines between two areas) are shown on the “shaded” (with a particular color in the background) map below.
Hawaii Time
Alaska Time
Pacific Time
Mountain Time
Central Time
Eastern Time
Comprehension Answers
1 - b
2 - c