= 0675
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 675: Having Furniture Delivered.
This is English as a Second Language Podcast episode 675. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode – and for life, really. It will help you in many things.
This episode is a dialogue between Zuly and Danny about when you buy “furniture” – a bed, a couch, a chair – and the company or store delivers it to your house. We’ll see what happens when there are some problems in that process. Let’s get started.
[start of dialogue]
I was waiting patiently for the furniture store to deliver my new bed. I was given a window of 1:00 to 4:00. At 4:50, the delivery truck pulled up in front of my house.
……
Zuly: Hello.
Danny: Hi! We’re from Reliable Furniture. We’re here to deliver your new bed.
Zuly: I thought you’d never get here. The new bed should go in the bedroom. Follow me. You’ll haul away the old bed, right?
Danny: We will for an extra charge.
Zuly: I thought that was included in the price of the new bed.
Danny: Let me check the paperwork. Oh, I guess it is. We’ll take away the old bed and bring in the new one.
Zuly: Okay, this way. You can bring the bed right in here.
Danny: Okay, here you are. We’re all done.
Zuly: Aren’t you guys going to remove the bubble wrap, assemble the pieces, and set up the bed?
Danny: We can, but it’ll cost extra.
Zuly: I’m sure that’s included in the price of the new bed.
Danny: Let me check…Okay, I guess we’ll set it up. We’re just running a little late, that’s all. We got a late start from the warehouse this morning and it’s already past quitting time.
……
I wasn’t too happy, to say the least, but I was at their mercy and didn’t say anything. But as soon as they’re finished, I’ll be ready to give them a piece of my mind!
[end of dialogue]
Zuly begins by telling us the background – the setting of our story. She says, “I was waiting patiently for the furniture store (the place where she bought a piece of furniture, such as a bed, a couch, or a chair) to deliver my new bed.” I should say that “furniture” is always singular; we would never say “furnitures,” even though it refers to many different objects – many different we would say “pieces of furniture.” She’s waiting for the store to “deliver” her bed, to take it from their store and bring it to her house. She says, “I was given a window of 1:00 to 4:00.” A “window” in this case means a period of time during which something will happen. It’s very common in the U.S. when you have someone delivering furniture or someone coming to your house to fix your telephone – for lots of different services – that the company will give you not a specific time but a range of time, what we would call a “window.” In this case, they could come any time between 1:00 and 4:00. It’s very inconvenient for the person who is buying the service or thing, but that’s just the way a lot of companies do things here. I always find it rather annoying. In any case, Zuly says, “At 4:50 (meaning 50 minutes after the end of the window – 50 minutes late), the delivery truck pulled up in front of my house.” The “delivery truck” is the large vehicle that will deliver things. “To pull up” is a two-word phrasal verb meaning to drive to a place and stop there, especially in front a building or a house. “To pull up,” it’s used with your car.
So, the truck pulled up in front of her house, and then we get the actual dialogue. Zuly says, “Hello.” Danny, who works for the delivery company or the store, says, “Hi! We’re from Reliable Furniture. We’re here to deliver your new bed.” Something that is “reliable” is something that is dependable, that you can count on. Of course, they’re 50 minutes late, so they’re not actually very reliable! Zuly says, “I thought you’d never get here.” The expression “I thought you’d never get here” is one you would use to let someone know that they are much later than you expected. Normally it communicates a certain annoyance, a certain anger perhaps at that person. Zuly says, “The new bed should go in the bedroom.” That’s where beds go usually, in the bedroom. “Follow me,” she says, walk behind me and go where I am going, “You’ll haul away the old bed, right?” “To haul (haul) away (something)” is to take something away, take something from, say, a house or a building that is very large typically; it may be very heavy to lift. It’s something that you don’t need anymore. So if your refrigerator breaks and you can’t fix it, you can buy a new refrigerator and then have your old refrigerator hauled away. Someone will it take away. It’s a phrasal verb we use especially in this circumstance.
So Zuly wants to make sure the movers will haul away her old bed – will take her old bed away and get rid of it, throw it out or do whatever one does with old beds. Danny says, “We will (we will haul it away) for an extra charge.” An “extra charge” is an additional amount of money. Zuly says, “I thought that (the hauling away) was included in the price of the new bed.” Zuly didn’t think she had to pay extra, or additional money. Danny says, “Let me check the paperwork.” Let me look at the paper or the forms that were given to him with instructions about what to deliver, where, and what services are included. “Paperwork” is a general term that describes forms, pieces of paper you have to put information on, we would say “to fill out.” That’s a general term that would be used in businesses and government offices. Government offices typically have lots of paperwork if you ever want to get anything from them! Danny checks his paperwork and realizes that he should not charge her more money for hauling away the old bed, so he says, “Oh, I guess it is,” it is included in the price that she already paid. “We’ll take away the old bed and bring in the new one,” he says.
Zuly then says, “Okay, this way (meaning follow me; walk after me). You can bring the bed right in here.” So she walks, we guess, from the door of the house – the front door and goes to the bedroom and shows them where to put the bed, so they bring the bed in. Danny then says, “Okay, here you are,” meaning this is what I am giving you; it is right here. This is a very common expression. Someone may ask you for a pen to write with. You take out a pen, and as you’re giving it to the person you may say, “here you are,” or “here you go.” In that case, they mean the same thing. Danny says, “We’re all done,” we are finished; we’ve completed our job. But Zuly doesn’t think they’re finished, she says, “Aren’t you guys (you men – in this case perhaps – aren’t you) going to remove the bubble wrap, assemble the pieces, and set up the bed?” “Bubble wrap” are large pieces of plastic that have been put together and they have lots of little, well, bubbles, which are sort of like little balloons that have air in them, and they’re all attached, and they’re put around something to protect it. They’re often used when you are mailing, for example, something that could break easily. “To assemble” means to put together, to take things that are apart and put them together so that whatever you have is working. “To set up (something)” in this case means to put something into the correct position, put it where it’s supposed to be. “Set up,” as a phrasal verb, can also be used to mean to put something together, to organize something, to get something ready.
Danny says, “We can (we can do that), but it’ll cost extra.” It’ll be an extra charge again. Zuly again doubts this, doesn’t think this is true. She says, “I’m sure that’s included in the price of the new bed,” meaning I already paid for that, you should do it. Danny looks at his paper again; he says, “Let me check,” and realizes that yes, they’re supposed to do the things that Zuly is asking them to do, to set up the bed. He says, “Okay, I guess we’ll set it up. We’re just running a little late, that’s all.” “To run a little late” means to be behind schedule, not to have made very much progress in what you are doing. You planned to be finished by 5:00, it’s 5:30 and you’re still not finished; you’re running a little late. Danny says, “We got a late start from the warehouse this morning,” meaning we left the warehouse later than we were planning to. A “warehouse” (warehouse – one word) is a large building where many objects or items are stored until they are needed. So if you go to the store to buy a bed, they won’t usually have the bed there in the store for you; they will have it in another building, which we would call a “warehouse,” where they put things until they can sell them. Danny says, “it’s already past quitting time.” “Quitting time” is the end of your workday: 5:00 at night, 6:00 at night. When you finish working; when you go home after working, that’s “quitting time.”
Zuly says, “I wasn’t too happy, to say the least.” The phrase “to say the least” is used to show that what you just said is an understatement, that you actually feel much more strongly than you have indicated. So, someone for example wins a million dollars and they say, “Well, I’m very happy, to say the least,” meaning they’re more than just very happy. Zuly says she wasn’t too happy – she wasn’t very happy, to say the least, meaning she was really angry, “but I was at their mercy and didn’t say anything.” “To be at (someone’s) mercy” (mercy) is to be in a situation where someone else has control of what is happening, that you have to depend on another person to get something done. It’s usually used when you’re in a situation you don’t want to be in, that you don’t have the power that you want. She says, “as soon as they’re finished (as soon as Danny and his other workers finish setting up the bed), I’ll be ready to give them a piece of my mind!” “To give (someone) a piece of your mind” is an expression meaning to tell someone what you really think, especially when you’re angry and upset, when you’re mad. “Well, I’m going to give that guy a piece of my mind!” I’m going to tell him what I really think, usually because you’re angry.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
I was waiting patiently for the furniture store to deliver my new bed. I was given a window of 1:00 to 4:00. At 4:50, the delivery truck pulled up in front of my house.
……
Zuly: Hello.
Danny: Hi! We’re from Reliable Furniture. We’re here to deliver your new bed.
Zuly: I thought you’d never get here. The new bed should go in the bedroom. Follow me. You’ll haul away the old bed, right?
Danny: We will for an extra charge.
Zuly: I thought that was included in the price of the new bed.
Danny: Let me check the paperwork. Oh, I guess it is. We’ll take away the old bed and bring in the new one.
Zuly: Okay, this way. You can bring the bed right in here.
Danny: Okay, here you are. We’re all done.
Zuly: Aren’t you guys going to remove the bubble wrap, assemble the pieces, and set up the bed?
Danny: We can, but it’ll cost extra.
Zuly: I’m sure that’s included in the price of the new bed.
Danny: Let me check…Okay, I guess we’ll set it up. We’re just running a little late, that’s all. We got a late start from the warehouse this morning and it’s already past quitting time.
……
I wasn’t too happy, to say the least, but I was at their mercy and didn’t say anything. But as soon as they’re finished, I’ll be ready to give them a piece of my mind!
[end of dialogue]
Our scriptwriter is a very fine writer, to say the least. We think she’s wonderful, and we thank Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
to deliver – to take something to another place and leave it there, especially something that has been purchased
* How long will it take for you to deliver the pizza to my house?
window – a period of time during which something will happen; the range of times when something will happen
* In Jacob’s busy schedule, he only has a 30-minute window each day to eat lunch.
delivery truck – a large vehicle used to carry many things and take them where they need to go
* The worst part about living next to the grocery store is that there are so many noisy delivery trucks in the evening
to pull up – to drive to a place and stop there, especially at a building
* After you place your order, please pull up and pay at the second window.
I thought you’d never get here – a phrase used to let someone know that he or she has arrived later than expected.
* I thought you’d never get here! I’ve been waiting for you for more than 40 minutes.
to haul away – to take something away, especially when it is a very large and heavy object that is no longer useful and needs to be sold or thrown away
* Please call the garbage company and find out how much they would charge to haul away our broken refrigerator
extra charge – an additional amount of money that must be paid for some purpose
* Most movie rentals cost $1, but there’s an extra charge for our most popular films.
paperwork – the forms that must be filled out or completed for a particular process to take place
* I never realized how much paperwork was involved in buying a home!
bubble wrap – large pieces of plastic that have been put together so that there are many small areas filled with air between the two pieces of plastic, put around delicate or fragile objects so that they do not break
* Little kids like to jump on pieces of bubble wrap to hear the popping sound.
to assemble – to put something together so that it can be used; to put many small pieces together in a particular way to produce the final product
* How long did it take you to assemble that swing set for your children?
to set up – to put something in position, or to put many small pieces in position so that something can be used
* Do you need help setting up the stage for the concert?
to run a little late – to be slightly behind schedule; to not have made as much progress in doing something as one had expected
* I called the office to say that I was running a little late and that they should start the meeting without me
warehouse – a large building or storage facility where many objects are kept until they are needed, especially until they are taken to stores where they will be sold
* If we start to run out of digital cameras, please call the warehouse so they can send more cameras to our store.
quitting time – the end of a workday; the time of day when one stops working and goes home
* Jack’s boss pressures him to work past quitting time most days.
to say the least – at a minimum; a phrase used to show that what one has just said is an understatement, and one actually feels much more strongly about it
* Trent’s $1,000,000 donation to the school was generous, to say the least.
to be at (someone’s) mercy – to be in a situation where someone else has control over the outcome; to be dependent on another person’s actions for something to be done
* Wanda filled out the job application and now she’s at the hiring manager’s mercy.
to give (someone) a piece of my mind – to tell someone what one really thinks, especially when one is angry and upset
* When Quentin was fired, he took the opportunity to give his boss a piece of his mind, telling her how much he disliked her management style.
Comprehension Questions
1. What does Zuly mean when she says, “I thought you’d never get here”?
a) She thought they might have gotten lost.
b) She was expecting them to come earlier.
c) She thought they weren’t going to come.
2. Why is Zuly dissatisfied with Danny’s service?
a) Because he didn’t bring the right bed.
b) Because he asked her to pay more money.
c) Because he didn’t want to put the bed together.
Answers at bottom.
What Else Does It Mean?
window
The word “window,” in this podcast, means a period of time during which something will happen: “The post office gave us a three-day window for when the package will be delivered.” The phrase “a window of opportunity” refers to a short period of time when something can be done: “When Cambria’s boss went on vacation, it was her window of opportunity to show the vice-president that she was capable of managing the department.” When talking about computers, the word “window” refers to one rectangular box that appears on the screen where one can do work or view information: “I usually have three windows open on my computer: my email, a word processor, and a spreadsheet.” “Finally, the phrase “a window on the world” is something that lets people learn what is happening in other parts of the world: “These radio news programs are my window on the world.”
to be at (someone’s) mercy
In this podcast, the phrase “to be at (someone’s) mercy” means to be in a situation where someone else has control over the outcome and to be dependent on that person’s actions: “If we go to the park today, we’ll be at the mercy of the weather.” The word “mercy” refers to one’s decision or choice to be kind and forgiving: “Do you think the judge will have mercy on him and give him only a few years in prison?” The phrase “to beg for mercy” means to desperately ask someone to be nice and kind, especially if one does not fully deserve it: “The man begged for mercy, but victim’s family didn’t think the deserved any.” Finally, the phrase “it’s a mercy” means one is fortunate that nothing worse happened: “It’s a mercy we only lost $40,000 when housing prices fell. Other people lost much more.”
Culture Note
Sellers in the United States often “stipulate” (say that something must happen; establish) “conditions of sale” (terms; things that the buyer and seller must agree to). These conditions of sale can be very “lenient” (tolerant) or very strict.
Buyers generally want to buy things that are “fully refundable,” meaning that they can try the product and, if they are “dissatisfied” (not pleased) with it, return it to the store for a “full refund,” receiving the amount of money they originally paid for it. Stores and manufacturers sometimes offer “satisfaction guarantees,” allowing people to bring back the unused “portion” (part) of whatever they have purchased for a full refund, “no questions asked” (without needing to say what was wrong with the product).
Other stores “refuse” (do not do something) to give refunds, but may offer “replacements” (giving the customer a different unit of the same item), “exchanges” (letting the customer pick out something with the same price), or “store credit” (a card or certificate that the customer can use as cash in that store in the future).
Still other stores say that “all sales are final,” meaning that the customer cannot bring the product back to the store even if something is wrong with it. These stores often have a sign over the “cash register” (the machine where money is kept and sales are made) saying “no exchanges/refunds” to “remind” (help someone remember) customers of their policy.
“Secondhand stores” (stores that sell things that have already been used by other people) normally sell things “as-is,” meaning the buyer must accept the purchased good no matter what “condition” (quality) it is in. The buyer needs to test the item “thoroughly” (completely; exhaustively) before paying for it, because the store will not be “sympathetic” (caring about another person’s situation) if it doesn’t work properly or if it breaks soon after purchase.
Comprehension Answers
1 - b
2 - c