= 0683
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 683: Using a Video-Sharing Website.
This is English as a Second Language Podcast episode 683. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website, you know, it’s eslpod.com. Go there, you know what to do.
This episode is called “Using a Video-Sharing Website.” Let’s get started.
[start of dialogue]
Melissa: You’re looking at the next overnight sensation. I’m uploading my video right now, and by this time tomorrow, I wouldn’t be surprised if it’s had over 100,000 views. It’s going to go viral.
Frank: You and your amateur videos. Who is going to watch something with such low production value?
Melissa: You’d be surprised. I have my own channel on YouGube, with over 5,000 subscribers.
Frank: Are you sure that’s not because your username is AngelinaJolie?
Melissa: No, it’s because people enjoy my videos, mark them as their favorites, and share them with their friends. Word of mouth – that’s why I’m so popular.
Frank: But what about the comments on your videos? How many of those are positive and how many are negative?
Melissa: I don’t read the comments. I assume they’re all positive, and my videos have never been flagged.
Frank: All right, so is this another video of you dancing with your cat?
Melissa: No, my cat and I are dancing and singing. That’s why we’re both going to be the next big thing.
Frank: Right, I’ll get in line right now to buy tickets to your upcoming Vegas show.
[end of dialogue]
Our dialogue begins with Melissa saying to Frank, “You’re looking at the next overnight sensation.” “Overnight” (one word) means from today till tomorrow, in 24 hours. If a company says we’ll deliver that to you overnight that means it will be there the next day. “Overnight,” however, can also mean very quickly, suddenly. This is the meaning that Melissa has in mind when she says “the next overnight sensation.” A “sensation” here means something that is very popular; something that has become very popular very quickly is called an “overnight sensation.” Melissa says, “I’m uploading my video right now.” “To upload” (upload – one word) means to move a file from a computer – a computer’s hard drive – up to another computer on the Internet or on a network of computers. Melissa says that by this time tomorrow, in 24 hours, “I wouldn’t be surprised if it’s had over 100,000 views.” She’s saying that she expects that her video will, in 24 hours, have 100,000 views. A “view,” when we’re talking about a video website, means that something has been watched by 100,000 people or 100,000 times. Maybe one person watches it 100,000 times; I’m not sure exactly how that works. But, 100,000 views usually means that 100,000 people have seen the video. “It’s going to go viral,” Melissa says. The expression “to go viral” (viral) means something becomes very popular on the Internet very quickly. Like a virus causes illness – sickness to spread quickly from one person to another, “viral” means something moves very quickly on the Internet; it becomes popular very quickly.
Frank says, “You and your amateur videos.” “Amateur” is the opposite of “professional,” something done by someone who isn’t getting any money for it typically. Also, it means not very good, not very sophisticated. That’s the idea that Frank is saying; he’s saying that you are making another amateur video. “Who’s going to watch something with such low production value?” “Production value” is the quality of the video or the quality of the movie. It could be the sound, it could be the way it looks, the special effects. All of these are part of the production value. “Production” comes from the word “produce,” meaning to make. “Value,” here, is how good or bad it is. It’s a term you hear a lot in Los Angeles when people talk about movies and films: “production value.”
Melissa says, “You’d be surprised.” That expression “you’d be surprised” means you will be surprised at the quality of my video. She says, “I have my own channel on YouGube, with over 5,000 subscribers.” A “channel” here is a group of things that are related to each other; it typically refers to something on the radio or the television that is created and can be found in the same place every time. On video-sharing sites, this one is called “YouGube,” similar I think to YouTube, you can have your own channel. So, you can put all of your videos in one place and people can find them easily. They can also “subscribe” to your channel, meaning every time you put a new video on your channel they get an email telling you hey, there’s a new video on this person’s channel. A “subscriber” is someone who has signed up or paid to receive copies of something such as a newspaper, a magazine, or in this case emails on the Internet. Notice when pronounced quickly, the word “Internet” often loses that “t” in the middle when we say it quickly: “Inernet” instead of “Internet.”
Anyway, Frank says, “Are you sure that’s not because your username is AngelinaJolie?” A “username” (one word) is a name that you select for an email account or when you register or subscribe to something on the Internet. It’s a name that you can pick that doesn’t necessarily have to be your name. One of my usernames is ESLPod; that’s not my name, but I can use it as my username. That’s my username on Twitter; you can follow me on Twitter if you want to. Frank says Melissa has a username of AngelinaJolie, who you may know is a famous, beautiful actress who lives with another actor, some guy by the name of Brad…Brad…what is it? Brad Pitt, yeah, Brad Pitt. Who ever heard of him?
Anyway, AngelinaJolie is the username Melissa uses, and of course people would subscribe to her channel thinking that she was the real Angelina Jolie. Melissa says, however, “No,” that isn’t true. She has 5,000 subscribers she says, “because people enjoy my videos, mark them as their favorites, and share them with their friends.” On many websites you can indicate which things on the site are your favorite things, and that’s what Melissa is referring to. People also share her videos; they send an email perhaps with a “link” (the website address) so the person can then look at that video, or they put on their Facebook page or perhaps they put it on their Twitter feed by tweeting it. Melissa says, “Word of mouth – that’s why I’m so popular.” “Word of mouth” is an expression that means that one person tells another person and then they tell their friend and then that friend tells someone else, and pretty soon you’re very popular because everyone has been telling everyone else. Normally we use this expression to compare it to another way of getting people to come to your website or go to your store, which would be a commercial on the television for example, or in the newspaper. But, “word of mouth” is advertising that takes place when one person tells another. It doesn’t cost you any money; it’s the best kind of advertising. Melissa says, “that’s why I’m so popular (that’s why everyone likes me).”
Frank says, “But what about the comments on your videos?” A “comment” is something that you write to express your opinion, especially on a website. Frank asks, “How many of those (comments) are positive and how many are negative?” Melissa says, “I don’t read the comments. I assume they’re all positive, and my videos have never been flagged.” She thinks everyone loves her videos, but she doesn’t read their comments with their actual opinions. She says her videos have never been flagged. “To be flagged” (flagged) means to indicate that something on the Internet has either broken a rule for the website or is somehow unusual in some way. So if you go to YouTube and you put up a video of a television program that is illegal, someone could flag your video. They could indicate to the owner of the website that you are doing something wrong.
Frank says, “All right, so is this another video of you dancing with your cat?” That’s Melissa’s video, her dancing with her cat. Melissa says, “No, my cat and I are dancing and singing. That’s why we’re both going to be the next big thing.” “The next big thing” is the next thing that will be very popular and well known among many people. It’s the next, we might call it, “trend,” or “fad” (fad), something that’s popular for a while, but only briefly – only for a short time, and then it’s not so popular.
Melissa says she thinks she and her cat will be the next big thing. Frank says, “Right,” but he says it in a way that really means wrong. He says the word “right” meaning I don’t believe you. So sometimes the meaning of the word can be the opposite depending on how the person says it. He says, “I’ll get in line (I’ll start waiting) right now to buy tickets to your upcoming Vegas show.” “Upcoming” (one word) means happening in the near future, something that will be happening soon. “Vegas” refers to the city of Las Vegas in Nevada, about five hours by car east of Los Angeles. It’s where you can go and see a lot of famous singers, they have shows – they have performances that you go and watch. Frank, of course, is making a joke.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Melissa: You’re looking at the next overnight sensation. I’m uploading my video right now, and by this time tomorrow, I wouldn’t be surprised if it’s had over 100,000 views. It’s going to go viral.
Frank: You and your amateur videos. Who is going to watch something with such low production value?
Melissa: You’d be surprised. I have my own channel on YouGube, with over 5,000 subscribers.
Frank: Are you sure that’s not because your username is AngelinaJolie?
Melissa: No, it’s because people enjoy my videos, mark them as their favorites, and share them with their friends. Word of mouth – that’s why I’m so popular.
Frank: But what about the comments on your videos? How many of those are positive and how many are negative?
Melissa: I don’t read the comments. I assume they’re all positive, and my videos have never been flagged.
Frank: All right, so is this another video of you dancing with your cat?
Melissa: No, my cat and I are dancing and singing. That’s why we’re both going to be the next big thing.
Frank: Right, I’ll get in line right now to buy tickets to your upcoming Vegas show.
[end of dialogue]
Why is ESL Podcast so popular? Well, the big reason I think is our scriptwriter, the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast. Angelina, call me!
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
overnight sensation – something that becomes very popular among many people very quickly, without anyone having been aware of it previously
* Every time we introduce a new product, we hope it becomes an overnight sensation.
to upload – to move a file from a single computer to the Internet or a network of computers where it can be accessed by many different users
* To make a photo calendar, first you need to upload your favorite photographs to this website.
view – one instance of someone visiting a particular website, seeing a particular image, or watching a particular video
* This video has been getting about 10,000 views each day.
to go viral – for something to become very popular online and be shared with many people by being sent electronically via email and social networking sites
* Advertising agencies dream of producing ads that can go viral.
amateur – not professional; without polished skills for doing something; doing something as a hobby or just for fun, but not as one’s career
* During the day, Drake is a dentist, but in the evenings he’s an amateur DJ for the local radio station.
production value – the quality of a video or movie, often referring to the sharpness of the image, the clarity of the sound, and the sophistication of the editing and special effects
* If we’re going to improve the production value of these videos, we’ll need to invest in some better video cameras.
channel – station; one group of programs that are created or gathered by a single person or company and shared via television, the radio, or the Internet
* They’re planning to get a satellite dish so they can watch hundreds of TV channels.
subscriber – someone who has signed up and/or paid to receive copies of something, especially of a newspaper or magazine
* How many subscribers does this magazine have?
username – the short word or phrase used to identify a particular user for an online account or discussion forum
* Do you create a different username for each of your online accounts, or do you try to use a single username for everything?
favorite – a website or video that one likes and has put on a special list to make it easier to find again in the future and recommend to other people
* If you save websites in your favorites folder, you can just click on them when you want to visit them again, without needing to retype the URL.
to share – to send or give something to another person so that he or she will become aware of it and enjoy it as one continues to enjoy it oneself
* If you win the lottery, will you share the money with me?
word of mouth – the process of sharing information by telling other people about something orally, not in writing
* The new restaurant is surprisingly popular, considering that it doesn’t pay for any advertising and instead relies only on word of mouth.
popular – being liked and admired by many people
* Which will be the most popular TV shows this spring?
comment – remark; something that is written to express one’s opinion about something, especially online
* How often do you leave comments on blogs?
flagged – marked as something that has broken the rules or is questionable or unusual in some way
* If any of the payment transactions are flagged as being suspicious, make sure the money is received before you mail out the order.
the next big thing – the next trend or fad; the next thing that will become extremely popular and well-known among many people
* They’ve invested all their money in hydrothermal power, hoping it will become the next big thing.
upcoming – happening in the near future; anticipated
* Are you ready for the upcoming conference?
Comprehension Questions
1. What does Melissa think will happen with her video?
a) It will become infected with a virus.
b) It will become extremely popular.
c) It will be flagged.
2. Why doesn’t Frank think Melissa’s video will be successful?
a) Because the production didn’t cost very much.
b) Because the quality of the production isn’t very good.
c) Because she didn’t pick a very good username.
Answers at bottom.
What Else Does It Mean?
view
The word “view,” in this podcast, means one instance of someone visiting a particular website, seeing a particular image, or watching a particular video: “Some of the most popular videos have more than one million views.” A “view” can also be one’s opinion: “What’s your view on the new legislation?” The word “view” can also refer to what one is able to see: “Would we need to pay more for a room with a view of the ocean?” The formal phrase “in view of (something)” means considering something, especially when explaining one’s reasons for doing something: “In view of the problems in the housing market, the government is creating programs to help people pay their mortgage.” Finally, the phrase “with a view to (something)” means with a plan to do something in the future: “He’s studying biochemistry with a view to applying to medical schools next year.”
to be flagged
In this podcast, the phrase “to be flagged” means to be marked as something that has broken the rules or is questionable or unusual in some way: “His travel plans were flagged as suspicious and potentially terrorism-related.” The phrase “to flag (someone) down” means to move one’s hands in the air to make a car stop: “When their car broke down on the freeway, they had to pull over and try to flag down someone who could help them.” The phrase “flag-waving” refers to very strong, extreme feelings of patriotism or a love for one’s country: “Do you think she really believes in all that flag-waving, or is she just doing it to win the election?” Finally, the verb “to flag” can also mean to lose strength and become tired: “After the 12th mile of the marathon, Chenalise really started to flag.”
Culture Note
The Digital Millennium Copyright “Act” (law) became law in 1998. It “amended” (changed) existing laws to “extend” (make something bigger or further-reaching) “copyright protections” (laws that do not allow people to copy other people’s creative work) to “digital media” (electronic files).
At the same time, the Digital Millennium Copyright Act “limited” (put a maximum on) the “liability” (someone’s risk; how much someone can be held responsible for something) of people who provide online services when their users “post” (upload) copyrighted materials but do not have permission to do so. For example, it limits the liability of a site like YouTube when users post videos that they do not “hold” (have; own) the copyright to.
Some people say that the Digital Millennium Copyright Act “goes too far” (takes something to an extreme) in protecting the rights of copyright holders. If a copyright holder believes his or her work is being used without permission on a website, he or she can send a takedown “notice” (official letter) to the website owner, demanding that the material be “taken down” (removed or deleted) from the website. As long as the website owner “complies” (agrees with; does what is asked) with the takedown request, he or she cannot be “held liable” (punished) for the “disallowed” (not allowed) use of the materials. However, many of the takedown requests “have no basis” (are not based on anything) and the materials are actually “fair use” (legally allowed usage) of the copyrighted material. Nevertheless, because the website owner does not want to be punished, the materials are usually taken down anyway.
Comprehension Answers
1 - b
2 - b