= 0684
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 684: Asking for Information About a Coworker.
This is English as a Second Language Podcast episode 684. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Why do we tell you that at the beginning of every episode? Well, because we want you to go and download a Learning Guide for this episode. And why do we want you to download a Learning Guide? Well first, because it will help you improve your English, and second, because this podcast depends on you becoming members and supporting us so we can continue to provide these audio files for free.
This episode is called “Asking for Information About a Coworker,” someone you work with. Let’s get started.
[start of dialogue]
Amina: What’s the lowdown on the new guy?
Earl: Which new guy?
Amina: You know, the cute one. Fill me in. Is he single?
Earl: I don’t know. I have no idea.
Amina: You’re working with him side-by-side and you haven’t gleaned any personal information about him?
Earl: We talk about work. It’s not my job to pry into his personal life.
Amina: I need to get the scoop on Mr. Perfect and you’re my source.
Earl: You don’t know anything about him, so how do you know he’s perfect? Maybe when you get to know him, you’ll find out he’s a selfish, self-centered jerk.
Amina: Wait, catch me up on what’s going on here. Have other people asked you about him?
Earl: Yeah, maybe about a dozen of the women in this office. They’ve been bombarding me with questions.
Amina: Oh, sorry. I didn’t know.
Earl: Yeah, I’m not the guy’s social secretary. You women have to satisfy your own curiosity elsewhere.
Amina: Point taken, but do you know if he’s shown interest in any of the dozen women you’ve talked to?
Earl: Ugh!
[end of dialogue]
Our dialogue begins with Amina saying to Earl, “What’s the lowdown on the new guy?” The word “lowdown” (one word) means what is the interesting information about someone, what is the true information about this person. We often use this we are talking about perhaps secret information, information that you know and no one else knows. Amina is asking for the lowdown on the new guy, the new man who is working at their company.
Earl says, “Which new guy?” Amina says, “You know, the cute one.” “Cute” is someone who is attractive – physically attractive. I’m sort of the opposite of cute; I’m the anti-cute! Anyway, Amina says, “Fill me in.” “To fill (someone) in” is a phrasal verb meaning to give someone accurate information about what she or he wants or needs. “Fill me in” means give me the information I need. She begins by asking, “Is he single?” meaning is he unmarried. Earl says, “I don’t know. I have no idea,” meaning I don’t have any information at all. Amina says, “You’re working with him side-by-side (meaning right next to him physically) and you haven’t gleaned any personal information about him?” “To glean” (glean) means to learn something or to find something out indirectly, without asking the person directly. You get information, but not by asking them. You get it by doing other things, listening to their answers, asking related questions perhaps. Earl says, “We talk about work,” meaning when he and the new guy have a conversation it’s related to their work, not to their personal lives. Earl then says, “It’s not my job to pry into his personal life.” “To pry” (pry) means, in this case, to ask personal questions, usually questions that are very private or that are about information that you would not normally ask someone. Someone might tell you, “Don’t pry,” meaning don’t ask too personal of a question, things that you really don’t have any right to know. “To pry,” also, is the verb we use when, for example, we’re trying to open a door that won’t open, and we take a piece of thin metal – a long stick – and we try to open the door; we try to pry it open. It’s the same idea of trying to get into an area that is closed, much like your personal life might be closed.
Earl says that it’s not his job to pry into the new guy’s personal life. Amina says, “I need to get the scoop on Mr. Perfect and you’re my source.” The “scoop” (scoop) in this case is the most important information about something, especially information that is secret. The word “scoop” can also be used as a verb. In journalism, when talking about newspapers for example, or magazines, “to get a scoop on (something),” or simply “to get a scoop,” means to get information about a story before anyone else does, before anyone else is able to write an article about it. Here, the term is used more generally to mean information – important, possibly secret information. Amina calls him “Mr. Perfect,” meaning she really likes this person. She says to Earl, “you’re my source.” “Source,” in this case, just like we were talking about newspapers and magazines, is a person who provides information on a particular topic. It’s a term often associated with journalism – with news reporting. Your “source” is the person who tells you information, again, often secret information. Earl is Amina’s source for information, the place where she can go to get information.
Earl says, “You don’t know anything about him, so how do you know he’s perfect? Maybe when you get to know him, you’ll find out he’s a selfish, self-centered jerk.” “To be selfish” (selfish) means to care only about yourself and your happiness, you don’t care about anyone else. “Self-centered” means something similar, you only think about yourself and how something will affect you. You don’t think about how something will have an impact on or affect another person; that’s someone who is self-centered. We might also use the word “narcissistic,” from the old Greek story of Narcissus, the person who is so in love with themselves they don’t pay attention to anyone else. This, some people say, is a problem that has gotten worse in the United States. I read a book recently about this topic; I think it was called something like The Epidemic of Narcissism. “Epidemic” is like a disease that spreads quickly, and many people get the disease. Well, that’s what some psychologists say is happening with narcissism, especially among younger Americans. It was an interesting book, but I really wish it would have talked more about my generation. I mean, they’re the most important, right? So, Earl says that this new guy could be a selfish, self-centered jerk. A “jerk” (jerk) is a rude, uncaring, selfish, self-centered, thoughtless person that you don’t like. It’s a very negative way to describe someone, an insulting term, informally used, not something you would ever, for example, want to say about your boss – at least if your boss is listening to you! It can be used to describe a man or a woman, probably a little more common in describing a man.
Amina says, “Wait, catch me up on what’s going on here.” “To catch (someone) up” is a two-word phrasal verb meaning to give someone the information that he or she needs in order to know as much as everyone else knows about a certain topic. The idea is that other people know more than you do about this. Maybe you were on vacation or you were gone, and now you want someone to catch you up, to give you information that everyone else already has. There are some other meanings of this verb that you can find in our Learning Guide for this episode.
Amina says, “Have other people asked you about him?” Earl says, “Yeah, maybe about a dozen of the women in this office.” So, a “dozen,” around 12 other women have also asked Earl for information about this new, apparently cute guy. Earl says, “They’ve been bombarding me with questions.” “To bombard (bombard) (someone)” in this case means to ask them many questions very quickly: “Where is he going? What does he look like? How old is he? Is he married? Does he hate cats?” All important questions, right? That would be to bombard someone with questions. We also use this verb when talking about airplanes that are dropping bombs on a place in order to blow things up – to destroy things. So, that’s the original military meaning of “bombard.”
Earl says that the other women have been bombarding him with questions. Amina says, “Oh, sorry. I didn’t know.” Earl then says, “Yeah, I’m not the guy’s social secretary.” A “social secretary” would be a person who schedules another person’s personal meetings and dates, not a professional secretary that you would have at an office. Some people are so busy and have so much money that they can have a personal and a business or professional secretary. I don’t have either one, but I don’t really need the social secretary. My life is very boring, anyway. Anyway, enough about me. Earl says that you women have to satisfy your own curiosity elsewhere. “To satisfy your own curiosity,” or simply “to satisfy your curiosity,” means to find the answers to the questions you have by yourself. To discover things you want to know without getting help from other people, that would be to satisfy your own curiosity.
Amina says, “Point taken.” This is an informal phrase we use to mean that you understand and agree with the other person on what they just said. “Point taken,” Amina then says, “but do you know if he’s shown interest in any of the dozen women you’ve talked to?” So, she asks another question, even after Earl says he doesn’t want to answer more questions. Her question is has the new guy shown interest in any of the other women who have been asking about him. “To show interest in” is to be interested in someone or something. Often, we use it to describe someone who is interested in a romantic relationship with another person. They may show interest by talking to them, laughing at their jokes, asking them to go to lunch with them, and so forth. Earl replies simply by saying, “Ugh!” This is an expression of frustration, of disappointment, of dislike. He doesn’t want to be asked these questions; he’s tired of it.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Amina: What’s the lowdown on the new guy?
Earl: Which new guy?
Amina: You know, the cute one. Fill me in. Is he single?
Earl: I don’t know. I have no idea.
Amina: You’re working with him side-by-side and you haven’t gleaned any personal information about him?
Earl: We talk about work. It’s not my job to pry into his personal life.
Amina: I need to get the scoop on Mr. Perfect and you’re my source.
Earl: You don’t know anything about him, so how do you know he’s perfect? Maybe when you get to know him, you’ll find out he’s a selfish, self-centered jerk.
Amina: Wait, catch me up on what’s going on here. Have other people asked you about him?
Earl: Yeah, maybe about a dozen of the women in this office. They’ve been bombarding me with questions.
Amina: Oh, sorry. I didn’t know.
Earl: Yeah, I’m not the guy’s social secretary. You women have to satisfy your own curiosity elsewhere.
Amina: Point taken, but do you know if he’s shown interest in any of the dozen women you’ve talked to?
Earl: Ugh!
[end of dialogue]
The lowdown on our scriptwriter is that she’s intelligent, creative, and knows how to write, the one and only Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, won’t you, on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
lowdown – the interesting, possibly secret information about someone or something
* When I asked Eiko for the lowdown on the business deal, she refused to tell me anything.
to fill (someone) in – to give someone the information he or she wants or needs
* Is it true that Hinton asked you out on a date? Fill me in!
to glean – to learn something or find something out indirectly, without asking about it directly
* Have you been able to glean any information about their budget range for the project?
to pry – to ask personal, obtrusive questions about things that should be private, secret, or confidential
* I don’t mean to pry, but how old are you?
the scoop – all the most important information about something, especially when it is a secret
* What’s the scoop on why the politician really resigned from his job?
source – the person who provides information on a particular topic; where information comes from
* The teacher was impressed with Josephina’s report because she used several good and reliable sources, unlike her classmates.
selfish – caring only about one’s own happiness or comfort, and not caring about other people
* Samantha is so selfish! She never shares anything with anyone.
self-centered – thinking only about oneself and how something will affect oneself or what will benefit oneself
* Bryan is so self-centered. He probably thinks the world was created just for him!
jerk – a rude, uncaring, thoughtless person whom one does not like
* What a jerk! I can’t believe he wouldn’t open the door for you.
to catch (someone) up – to give someone the information he or she needs in order to know as much about something as everyone else does
* I had to step out of the room for a minute, but please catch me up. What did you guys talk about while I was gone?
to bombard – to ask someone many questions very quickly
* Ever since they sent out that press release last week, they’ve been bombarded with phone calls from reporters.
social secretary – a person who schedules another person’s personal (not professional) meetings and dates
* How many social secretaries does the U.S. President have?
to satisfy (one’s) own curiosity – to find the answers to one’s questions by oneself; to discover the things one wants to know without help from other people
* Marissa has always been fascinated by Southeast Asia, so she decided to satisfy her own curiosity by taking a trip to Thailand.
point taken – an informal phrase used to mean that one understands and agrees with what another person has just said
* - I really dislike the way you chew with your mouth open.
* - Point taken. I’ll try to stop doing it.
to show interest in – to be interested in someone or something, especially to be interested in starting a romantic relationship
* When Vinny started showing interest in the trombone, his parents signed him up for music lessons.
Comprehension Questions
1. What does Earl mean when he says, “I’m not the guy’s social secretary”?
a) He doesn’t work for the new employee.
b) He doesn’t spend very much time with the new employee.
c) He doesn’t control who gets to spend time with the new employee.
2. What does Amina mean when she says, “Point taken”?
a) She understands what Earl is saying.
b) She is offended by what Earl has said.
c) She thinks Earl is taking everything too seriously.
Answers at bottom.
What Else Does It Mean?
to fill (someone) in
The phrase “to fill (someone) in,” in this podcast, means to give someone the information he or she wants or needs: “What happened here? Please fill me in.” The phrases “to fill (something) out” or “to fill in the blanks” mean to complete a form by providing information where it is requested: “Please fill out this medical questionnaire before you see the doctor.” The phrase “to fill out” means for a young person’s body to change and become more like an adult body: “Rebecca really filled out over the summer, and now she is a young lady.” Finally, the phrase “to fill up” can mean to eat too much of something: “They filled up on bread while waiting for their food, and they were not able to eat much of what they had ordered.”
to catch (someone) up
In this podcast, the phrase “to catch (someone) up” means to give someone the information he or she needs in order to know as much about something as everyone else does: “Could someone please catch us up on what happened last week?” The phrase “to catch up with (someone)” means to go somewhere quickly so that one reaches another person who started earlier: “I have to work late, so I won’t be able to join you for dinner, but I’ll try to catch up with you for a movie afterwards.” The phrase “to catch up” means to become reacquainted with someone, talking about everything that has happened since the last time two people saw each other: “It’s so good to see you again! Let’s catch up over coffee.”
Culture Note
The Employee Information a Company Keeps
Businesses keep electronic and paper “files” (groups of related information stored together) about their employees. Those files include basic “contact information” such as address, telephone number, and email address, but they also include a lot of “confidential” (secret; private information), so normally the files can be seen only by “HR” (human resources) professionals and the employee’s “immediate” (one-level above) supervisor.
Employee files usually “contain” (have; include) the employee’s original application for employment, as well as a full description of each job the employee has had with the organization. The file includes “performance assessments” (reviews of how well an employee is doing his or her job) and “documentation” (written materials saved to remember things in the future) “backing up” (supporting) “promotion” (increase in salary and job responsibilities) or “demotion” (decrease in salary and job responsibilities) decisions.
Employee files also contain information about the types of training the employee has completed, along with any certificates of further education or anything else that documents the employee’s “skill set” (abilities; the things one is able to do).
Employee files also contain tax information, including the employee’s “Social Security number” (a national identifying number) and “W-4” (a tax form used to calculate how much of the salary should be held for taxes). The files also contain proof that the employee is legally allowed to work in the United States, such as a copy of the employee’s driver’s license or passport to demonstrate citizenship, or a copy of a “green card” (documentation of permanent residency in the U.S.).
Comprehension Answers
1 - c
2 - a