= 0699
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 699: Dealing With the Paparazzi.
This is English as a Second Language Podcast episode 699. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Go there to download a Learning Guide for this episode that will help you improve your English even faster.
This episode is called “Dealing With the Paparazzi,” these are photographers who try to take pictures of famous people. Let’s get started.
[start of dialogue]
Fredo: I feel like a prisoner in my own home! I can’t step outside without the paparazzi snapping pictures of me. They stake out my house 24 hours a day.
Amanda: I suppose that’s the price of fame. You do have the most popular podcast in the world.
Fredo: But they’re such a pain in the neck! They don’t just take pictures. They chase me in my car and follow me into restrooms, trying to corner me. It’s an invasion of privacy.
Amanda: You’re right, but look on the bright side. The paparazzi give you plenty of exposure. They keep your name – and your face – in the spotlight.
Fredo: It would be fine if they just took a few candid shots while I’m at dinner or at the store, but they try to take photos when I’m out of town, trying to catch me doing something I shouldn’t.
Amanda: At least, that’s good news for your wife. She can call off that private detective she hired to follow you from city to city!
[end of dialogue]
Our dialogue begins with Fredo saying to Amanda, “I feel like a prisoner in my own home!” A “prisoner” is someone who is in prison, which is the same as jail, when the government – the police arrest you and keep you in a building that’s called the “prison,” and you are a prisoner. Fredo says he feels like a prisoner in his own home. “I can’t step outside (meaning I can’t go outside my house) without the paparazzi snapping pictures of me.” The “paparazzi” (paparazzi) are photographers who try to take pictures of famous people and sell them to newspapers and magazines. The paparazzi are snapping pictures of Fredo. “To snap” (snap) here means to take a photograph, to use a camera to take a picture. You can say “I’m going to take a picture,” or you could say “I’m going to snap a picture,” they mean the same thing. “Snap” also is the sound that you make with your fingers when you put them together quickly, like this [Jeff snaps his fingers], that’s also “to snap.” Fredo said, “They stake out my house 24 hours a day.” “To stake (stake) out” is a two-word phrasal verb meaning to watch some place or some person in a hidden, secret way. You’re trying to observe what this person is doing without the person knowing that you are watching.
Amanda says, “I suppose that’s the price of fame.” “The price of fame” or “being famous” are the disadvantages or negative consequences of being famous. You have a lot of advantages, but you also have disadvantages. The disadvantages constitute or make up the price of fame. Amanda says, “You do have the most popular podcast in the world.” Fredo says, “But they’re,” meaning the paparazzi, “they’re such a pain in the neck!” “To be a pain in the neck” means someone or something is bothering you, is annoying you, is making you very uncomfortable. “My boss is a pain in the neck.” That means he annoys me, he makes me mad, he upsets me, he gives me a lot of trouble. “Pain in the neck” is the nice way of saying it; some people might also say “pain in the butt” (butt). Your “butt,” of course, is what you sit on, and other people use other words for “butt” that we won’t mention here on the podcast. “Pain in the neck,” then, is an informal expression, meaning someone or something that is annoying.
Fredo says, “They don’t just take pictures (these paparazzi). They chase me in my car and follow me into restrooms.” “To chase” (chase) means to follow someone, usually in their car, but it could be riding a bicycle or running after you. The person is usually moving very fast trying to catch you, trying to get you before you leave. Fredo says that the paparazzi chase him in his car and follow him into “restrooms,” or bathrooms, trying to corner him. “To corner (someone)” means to put someone in a position where that person can’t leave because there’s nowhere else to go. You could do that physically, you could corner someone, make sure that they can’t leave. Usually you do that when you want to talk to them or do something they don’t want to do. You can also corner someone in a more general sense of not giving them very many options, limiting their ability to do other things that you don’t want them to do.
Fredo says, “It’s an invasion of privacy.” “Privacy” is related to the word “private,” which means secret, hidden, other people don’t know about what you want to keep secret or keep hidden. Sometimes people say, “I’m a very private person,” meaning they don’t like to talk about their personal life with other people. The word “invasion” (invasion) is usually when some group of soldiers, people in the military – the army, the navy – go into some place and take it over. But here, “invasion of privacy” means someone is going into your private life, is finding out about things that they have no right to know.
Amanda says, “You’re right, but look on the bright side.” “To look on the bright side” is an expression meaning to see the advantages of what may seem like a bad situation, to be positive, to be optimistic. If you lose your girlfriend or your boyfriend, you should always look on the bright side; there are other men and women out there in the world for you. Or, if someone steals your car, you have to look on the bright side; you will now get more exercise by walking! See, there’s always a positive thing that can be said of a negative situation.
Amanda says, “The paparazzi give you plenty of exposure. They keep your name – and your face – in the spotlight.” “To be in the spotlight” means to get a lot of attention from other people, the newspapers and the television programs for example. That’s to be in the spotlight, to get a lot of attention.
Fredo says, “It would be fine (it would be okay) if they just took a few candid shots while I’m at dinner or at the store.” “Candid” (candid) can mean very honest, but when we’re talking about photography it’s a picture of someone who isn’t posing for the picture; they’re not looking a certain way or smiling a certain way. A candid photograph is one where typically you don’t even know that you’re being photographed, or you don’t act any different because you are being photographed. A “shot” is another word for a picture, so “candid shots” would be pictures of someone who doesn’t know they’re being photographed or doesn’t care – doesn’t act any differently.
Fredo says that the paparazzi try to take photographs of him when he’s “out of town,” meaning visiting another city, “trying to catch me doing something I shouldn’t.” “To catch (someone)” means to watch them and find out what they’re doing that might be wrong, usually something they’re trying to hide or keep secret. “The teacher caught one of her students cheating.” “Caught” is the past tense of “catch.” Or you could say, “The father caught his daughter talking on the phone late at night,” she wasn’t supposed to, she was supposed be sleeping. The father caught her. Fredo says that the paparazzi are trying to catch him doing something wrong, doing something he shouldn’t do.
Amanda says, “At least, that’s good news for your wife. She can call off that private detective she hired to follow you from city to city!” “To call off” is a two-word phrasal verb meaning to end something, to cancel, to abandon, to tell someone you don’t need them to continue doing what they were doing. If you have dogs to protect you in your house and they start to chase someone who is coming to your house – they start to go after them – the person may yell, “Call off your dogs,” meaning tell your dogs to stop attacking me. “Call off” is often used for investigations or searches. “The police called off their search for the missing dog,” they stopped looking for the dog. Why were they looking for the dog? I don’t know. Or you could say, “The baseball game was called off last night because of rain,” it was canceled. Or, “The man called off his wedding,” he decided he wasn’t going to marry the woman he said he was going to marry. That’s not very nice!
Amanda says that the wife of Fredo can call off that private detective she hired. A “private detective” is someone whose job it is to find out secret information about you, usually by taking pictures of what you are doing. This is something a wife might do if she thinks her husband is going with another woman; she may hire, or employ, a private detective to follow him. Amanda is making a joke, of course, saying that because the paparazzi are always taking pictures of Fredo, his wife doesn’t have to worry about him going with another woman, we would say “cheating on her,” because they will find out if he does.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Fredo: I feel like a prisoner in my own home! I can’t step outside without the paparazzi snapping pictures of me. They stake out my house 24 hours a day.
Amanda: I suppose that’s the price of fame. You do have the most popular podcast in the world.
Fredo: But they’re such a pain in the neck! They don’t just take pictures. They chase me in my car and follow me into restrooms, trying to corner me. It’s an invasion of privacy.
Amanda: You’re right, but look on the bright side. The paparazzi give you plenty of exposure. They keep your name – and your face – in the spotlight.
Fredo: It would be fine if they just took a few candid shots while I’m at dinner or at the store, but they try to take photos when I’m out of town, trying to catch me doing something I shouldn’t.
Amanda: At least, that’s good news for your wife. She can call off that private detective she hired to follow you from city to city!
[end of dialogue]
At the end of every ESL Podcast episode we try to put our scriptwriter in the spotlight. That’s because it’s our wonderful Dr. Lucy Tse who is bringing you – writing for you – these wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
prisoner – a person who is forced to stay in a jail or another building, held by other people and not allowed to leave
* Gertrude’s uncle was a prisoner for several months during World War II.
paparazzi – a photographer who tries to take photographs of famous people to sell to newspapers and magazines, usually following them wherever they go
* The movie star wanted to have a quiet wedding, but the paparazzi figured out where it was being held.
to snap – to take a photo; to use a camera to take a picture
* I wish I had a camera to snap a photo of the look on your face right now!
to stake out – to watch a place or person in a secret, hidden way, trying to observe something that other people don’t want to be seen
* The police are staking out the bank because they heard there might be a robbery there this week.
the price of fame – the disadvantages or negative consequences of being famous and having access to many advantages
* Yes, movie stars are rich, but the price of fame is losing their privacy.
pain in the neck – something or someone who is very annoying, upsetting, or uncomfortable that one would prefer not to have or deal with
* Filling out all these forms is a pain in the neck!
to chase – to follow someone at a high speed while that other person is trying to get away
* The police chased the criminal who was running down the street.
to corner (someone) – to put someone in a position where he or she cannot leave because there is nowhere else to go; to put someone in a position where he or she must do what one wants because there are no other options
* He has tried to avoid answering our questions for months, so if we want his answer we’ll have to corner him.
invasion of privacy – a violation of one’s right to lead a private life where others do not know one’s personal information; a lack of respect for a person by not letting him or her do things alone, without other people knowing what he or she is doing
* Would you ever read your daughter’s diary? It’s such an invasion of privacy, but sometimes it’s the only way to know what’s really happening in a teenager’s life.
to look on the bright side – to see the advantages or the good side of a bad situation; to be positive or optimistic
* Yeah, your car is broken beyond repair, but look on the bright side – you’ll save a lot of money on gas and insurance while you’re riding the bus!
exposure – being seen by many people; with many people being aware of something or someone
* Winning a Pulitzer Prize is a great way for authors to get a lot of exposure for their work.
in the spotlight – with a lot of attention from many people and/or the media
* As a public relations professional, his job is to keep his clients in the spotlight so everyone knows who they are.
candid shot – a photograph taken of someone who didn’t know he or she was being photographed, showing how someone was actually doing something, without posing for the photo
* We used to spend a lot of time trying to get our kids to smile for the camera, but then we realized that candid shots are easier and they tend to be better photos anyway.
to catch (someone) – to observe someone doing something he or she would like to hide and keep a secret, usually because it is in appropriate or wrong
* Have you ever caught someone stealing something from your store?
to call off – to abandon or cancel; to end something; to tell someone that his or her services are no longer needed; to stop doing something
* Call off your dogs! I’m just trying to deliver a package, and they won’t let me come to the front door!
private detective – a person whose job is to find out secret information about someone, usually by spying and following a person around to take pictures
* Meghan hired a private detective to find out whether her husband was having an affair.
Comprehension Questions
1. According to Amanda, what is the price of fame?
a) Never having privacy.
b) Being treated like a prisoner.
c) Having to pay the paparazzi.
2. According to Amanda, how do the paparazzi benefit Fredo?
a) They keep their cameras’ light bulbs shining on his face.
b) They always speak to him candidly.
c) They help to keep everyone’s attention on him.
Answers at bottom.
What Else Does It Mean?
to stake out
The phrase “to stake out,” in this podcast, means to watch a place or person in a secret, hidden way, trying to observe something that other people don’t want to be seen: “After Melody’s boyfriend broke up with her, she started staking out his apartment to see who else he was dating.” The phrase “to stake (something) up” means to use small pieces of wood or metal to help something stand up: “The tree is too tall and old to support its heavy branches, so we decided to stake them up.” Finally, the phrase “to stake (one’s) life on something” is used to show that one fully supports something and is 100% sure it is true or correct: “When we asked Hans whether he was sure his plan would work, he said, ‘I’d stake my life on it.’”
to call off
In this podcast, the phrase “to call off” means to tell someone that his or her services are no longer needed, or to cancel or stop doing something: “Officials called off the game due to the heavy rain.” Or, “Why did they decide to call off the wedding?” The phrase “to call the shots” means to be able to make decisions because one has authority or power: “Personally, I think it’s a bad idea, but the boss likes it and he’s the one who calls the shots.” Finally, the phrase “to call it a day” is used to announce that one will stop doing something, usually before it is finished, because one is tired or has been doing it for too long: “We’ve been working on this for hours. Let’s call it a day and continue next week.”
Culture Note
Anti-Paparazzi Laws
Paparazzi can make a lot of money by selling photos of “top” (extremely popular) “celebrities” (very famous people, especially musicians or actors), but sometimes these “financial incentives” (money one receives for doing something) make them “go over the top” (do too much of something). Some paparazzi “go to extremes” (do too much) to snap a photo, “intimidating” (scaring or frightening) the celebrities or even creating dangerous situations.
Sometimes celebrities “act out” (have strong physical reactions) against the paparazzi who are “pursuing” (chasing) them, such as when singer Britney Spears attacked a paparazzi’s “SUV” (sports utility vehicle; car) with an umbrella. Other celebrities try to “sue” (take someone to court to demand money) the paparazzi.
In 1997, Princess Diana was killed in a car accident that “occurred” (happened) while she was being chased by paparazzi. Since that event, many people have argued that there should be laws against the paparazzi’s actions, limiting when, where, and how they can take photos of celebrities.
The governor of California, Arnold Schwarzenegger, created a law in late 2009 that allows the “courts” (where legal decisions are made) to “fine” (demand money as a punishment) paparazzi for “invading” (violating) a celebrity’s right to privacy. This is especially important in the state of California, which “is home to” (where people live) so many Hollywood celebrities. The “aim” (goal; purpose) of the law is to make the paparazzi “think twice” (reconsider; carefully consider) whether snapping the perfect photo is worth receiving a “hefty” (large) fine.
Comprehension Answers
1 - a
2 - c