= 1524
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 219.
This is English as a Second Language Podcast’s English Café episode 219. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to talk about the medical marijuana controversy, or disagreements about whether the drug marijuana should be used by doctors to help people who are in pain. Then we’ll continue our series on famous Americans, focusing on film director Woody Allen. And, as always, we’ll answer a few of your questions. Let’s get started.
The United States has been fighting what’s been called a War on Drugs since at least the 1960s. The phrase “The War on Drugs” refers to all of the U.S. government’s attempts to stop the international trade, or the international buying and selling, of what are in the United States illegal drugs. Part of the War on Drugs focuses on not letting illegal drugs cross the borders, meaning come into the country. Another part of this War on Drugs focuses on getting people to not use illegal drugs, mostly by educating their children while they are very young about the dangers of these drugs. That hasn’t necessarily, however, been hugely successful.
The U.S. government has spent a lot of money, however, on the War on Drugs, but unfortunately, as I say, it hasn’t always produced the best results. Many people continue to use illegal drugs today, and some people think there might actually be less drug use if the War on Drugs ended. The evidence and the arguments can get rather complicated.
“Marijuana” is a popular illegal drug for smoking, especially among young people (high school, college age students). It is considered “milder” than cocaine, heroin, and many other types of drugs, meaning that it is not as strong and dangerous as those other drugs. Some people think that marijuana is bad for people; other people think it’s no different than drinking alcohol, which is, of course, legal. Others think that marijuana should be used only for medicinal purposes. “Medicinal” refers to things related to your health, to medicine, to healthcare.
There have been some studies that have shown that marijuana does have some useful medical properties. “Properties” are characteristics that doctors can use, in this case, to treat and care for their patients. Medical marijuana, as it’s sometimes called, can help people who are going especially through painful chemotherapy. “Chemotherapy” is the treatment where dangerous chemicals are put into your body to try to kill the cancer cells and stop the cancer from moving to other parts of your body – from spreading, we would say. People who are going through chemotherapy, or “chemo” as it is often called, often suffer from certain side effects. “Side effects” are things that a drug causes that are not the main purpose of the drug, usually they’re negative effects. One of the side effects of chemo is “nausea” (nausea), the feeling that people may need to vomit or throw up. People also lose weight when they are undergoing chemotherapy because they lose their “appetite,” their desire to eat. Marijuana can help people feel less nauseous and make them want to eat more, which allows them keep their weight up and be more healthy, in general, when they are fighting against cancer. Other studies have shown also that marijuana can be used to treat “migraines” (migraines), or “migraine headaches,” which are very bad, painful headaches. It is also been found helpful in treating multiple sclerosis, arthritis, asthma, depression, and other medical problems.
People who understand the medical properties of marijuana want doctors to be allowed to “prescribe” it, or give their patients permission to use marijuana, to buy it at a pharmacy or some other place that sells legal drugs. Other people, however, have argued that medical prescriptions for marijuana could also lead to (or could result in) more non-medical use of marijuana, meaning people would get the prescriptions but the marijuana would be used for what we would call recreational purposes; that is, just for fun, not for their sickness. This is the key part or key point of the medical marijuana controversy. This is what people don’t agree on, the fact that marijuana, if it is allowed for medical purposes, could be then used more widely for non-medical purposes. At least that’s one of the most important differences between the two groups who are fighting over these laws on medical marijuana.
Right now there are thirteen states, including here in California, that allow the medical use of marijuana, and seven other states are considering it. In those states, doctors are allowed to prescribe marijuana to their patients. In four of these states (California, Colorado, New Mexico, and Rhode Island) medical marijuana can also be sold through or at places called dispensaries. “Dispensaries” are special buildings that give out medicine; it’s sort of like a pharmacy. These are sometimes called, when we’re talking about medical marijuana, cannabis clubs. “Cannabis” (cannabis) is the Latin name of the plant that marijuana comes from. People with a doctor’s prescription for marijuana, here in California for example, legally should be able to go to a cannabis club to get the marijuana they need for their medical treatment.
However, remember here in the U.S., we have state governments, but we also have a national government. Marijuana is still considered illegal for any purpose, medical or non-medical at the federal or national level. Federal or national laws typically or usually supersede state laws. When we say they “supersede” (supersede) we mean that they are more powerful than state laws, that if there’s a conflict – a difference between a state law and a federal law, it’s the federal law that people have to follow. We would say it’s the federal law that “prevails.” In 2005, the Supreme Court of the United States said that the federal government can “prosecute,” or take people to court, who are using marijuana as medicine, even where the state laws allow it. So, here in California, even though the state law says it’s okay to use medical marijuana, you could still be arrested by federal government officials. In fact, this is exactly what happened here in California; a few cannabis clubs were raided, or entered by force, by the federal Drug Enforcement Administration (or DEA). It will be interesting to see what happens as more states legalize medical marijuana even though the federal government continues to say it is illegal. There is no national movement, at least one that is considered to have any likely success in the near future, to legalize medical marijuana at the national level. So my guess is these conflicts – these problems will continue, even as states continue to pass laws that allow medical use of marijuana. Of course, we’re not talking about non-medical use, again, people using marijuana as a drug like they would use any other legal or illegal drug in order to get simply intoxicated. The word we would use is “to get high.”
Speaking of controversial – that is, we were just talking about something controversial, now we’re going to talk about something else somewhat controversial. Let’s continue our series on famous Americans. Today we’re going to talk about Woody Allen, who has done many things in the entertainment industry in the U.S.; he’s best known, however, as a screenwriter and film director. A “screenwriter” (one word) is a person who writes the document they use to make a movie; they write the script. They describe who the characters are, what the setting is (where the story takes place), and the dialogue (the words that the characters say). Sometimes a screenwriter is called a scriptwriter; a scriptwriter is a more general term. Dr. Lucy Tse is our scriptwriter here at the Center for Educational Development. A screenwriter is a scriptwriter who writes for movies or television.
Woody Allen was born In New York City in 1935. His real name is Allen Stewart Konigsberg, but he began calling himself Woody Allen when he was a teenager. To make money, he started writing and selling what are called “one-liners.” “One-liners” are short jokes, that in this case were published in newspapers. A one-liner is typically one sentence, maybe two sentences long. When he was 16, Allen began working as a writer. He went to college to study communication and film, or movies, but he wasn’t a very good student and so he quit school before earning his degree.
When he was just 17 years old, he started writing for several TV shows, including the very popular Ed Sullivan Show and The Tonight Show (this is during the 1950s). In 1961, he started working as a stand-up comedian. A “stand-up comedian” is a person who stands up in front of an audience with a microphone and tells funny stories or jokes to try to make people laugh.
In the 1960s, he also started writing short stories and cartoon captions for The New Yorker magazine. The New Yorker magazine is a weekly magazine published in New York, of course, but it’s actually a national magazine. It has very good writing, considered to be one of the best magazines in terms of writing in English in the United States – articles about politics and literature and reviews of movies and so forth. The New Yorker is also famous for its cartoons. The “caption” of a cartoon is the line of text below the cartoon (the drawing). We also use this word, for example, in the newspaper if there’s a photograph the sentence below the photograph, describing what it is, is called the caption. So, Woody Allen wrote funny captions for the cartoons. In 1966, he wrote a play called Don’t Drink the Water, followed by another play called Play it Again, Sam. “Play it Again, Sam” comes from the movie Casablanca.
Finally, in 1965 he had his first movie called What’s New Pussycat?. Since then, he has written and directed many movies, and has been an actor in most of his own movies. His movies cover a lot of different topics; he often talks about ideas from literature, philosophy, psychology, and sexuality. He has taken some of the themes of his movies from ancient Greek drama, from his own Jewish culture, and especially from his hometown New York City. Woody Allen is very much associated with New York City as a filmmaker. That’s where he lives, that’s where he works.
His films are almost always comedies, they’re supposed be funny, but many of his films are “dark,” meaning they have some unpleasant, uncomfortable, perhaps even somewhat evil themes and ideas. One of Woody Allen’s more recent films is an example of this sort of dark comedy. Match Point was made in 2005 and is a drama that has a very dark ending. It’s a movie that many people have liked and praised, they’ve said good things about it, but it isn’t a movie that makes you feel very happy or comfortable at the end. I actually haven’t seen that movie.
There are other movies, however, that Allen is probably more famous for, two movies he made the 1970s in particular. The first was Annie Hall, a movie that won the Academy Award, or Oscar, for best picture and three other Academy Awards. Annie Hall is probably Allen’s most famous movie, and perhaps one of his best movies. Another popular movie that came out in 1979 is Manhattan. Manhattan, of course, is part of New York City; it’s the downtown, if you will, of New York City. There are too many Woody Allen movies to name here; he makes one almost every year nowadays. In 1996, Allen received a lifetime achievement award from the Directors Guild of America, an organization made up of American movie directors. He’s also won many film awards in Europe, where he is probably even more popular than he is here in the United States.
Allen’s personal life, however, has been very controversial, some people would say even “scandalous,” where a lot of people have been shocked and angered at his behavior. He has been married several times, and is now married to a woman who was basically the adopted daughter – although he never officially adopted her, but she was the adopted daughter of the woman he lived with for 12 years, and many people said that he was basically like a father to this girl at the time. When the girl grew up, he ended up falling in love with her and marrying her. Many people were shocked by this, considered it a very scandalous affair. Nevertheless he has continued, Allen has, to be popular, and his movies have been popular. Sometimes it may be necessary to separate the artist from his or her art.
Now let’s answer some of your questions.
Our first question comes from Bronis (Bronis), originally from Russia, now living in New York City. Maybe he knows Woody Allen! Bronis has a question about the word “sky” (sky) and “skies” (skies), the plural. He’s heard both words used and wants to know what the difference is.
Well, “sky” is the upper part of the space above the Earth, far above the ground. In most places, the sky, if there are no clouds in the sky, is the color blue. “Skies” is the plural of “sky.” It is, however, often used to refer to a even larger area of the world; it refers to the sky, but the sky over a large piece of land, perhaps over the entire country. So you might say, for example, “Did you see the birds in the sky today?” (singular), referring to the sky above your head or in your near vicinity (close to you). You could say, “The sky is very blue today,” or “The sky is very gray today.” If, however, you were talking about the weather in the entire western part of the United States, or on the west coast of the United States, you may say something like “Skies will be clear over most of California.” Now we’re talking about a larger area.
There’s no really good logical reason why we use the plural; we could just say “sky” for both of these things. “Skies,” the plural, tends to be used more often in weather forecasts. The person who’s telling you what the weather is going to be like tomorrow may say “We are expecting cloudy skies,” even though you’re talking about just your area. So for weather, for whatever reason, the plural is a little more common.
Alejandro (Alejandro) in Spain wants to know the meaning of some words he heard watching one of the American news broadcasts. Those two words are “meltdown” (meltdown – one word) and “crack down.”
“Meltdown” can mean a loss of control, because you are perhaps tired or upset; something very bad or tragic may have happened. That’s when the word is used to describe a person. If you’re describing a situation, it just means a disaster, a complete failure. “If things continue the way they’re going now, we will have an economic meltdown,” that is, our economy will be a disaster – even more of a disaster!
A “crack down” is when the government decides to enforce a law or a rule. For example: “The president said he will crack down terrorists,” he’s going to try to find them and arrest them. Or, “The police chief promised to crack down on violent crime this year.” A “crack down” is when the government gets more serious, perhaps has more men and women who are trying to enforce the law – who are trying to make sure that people follow a law.
So these two words, “crack down” and “meltdown,” are actually somewhat different. One additional use of “meltdown” if there is a failure at a nuclear power plant, where the power source melts by accident, we would call that a meltdown. “To melt” is to go from a solid state to a liquid state.
Hemen (Hemen) in Iran wants to know the meaning of the expression “more is less.”
“More is less” sounds like a contradiction; it’s a phrase, however, that means that a large amount of something is sometimes not as good as a small amount of something. The more common expression is “less is more,” meaning the less you have of something, the better it is. But “more is less” means the more you have of something, the worse it is; they actually mean the same thing. “Less is more” is more common,” but you could also say “more is less” to mean the same thing. For example: “Nancy used to much perfume tonight.” “Perfume” is a spray – a liquid you put on your body to make you smell nicer. Nancy should have realized that when it comes to perfume, when we’re talking about perfume, more is less, meaning putting too much on is actually worse. You could also say, “Marine only wants a few flowers at her wedding. To her, less is more,” meaning the fewer flowers the better.
“Less is more” is, as I say, the more common expression. There’s another expression that sounds similar because it uses the words “more” and “less,” but is different. That expression is “more or less.” When someone says “more or less,” they mean approximately, about, not exactly. This is especially used in talking about numbers. “My mother bought a pound of sugar, more or less,” meaning it could have been a little more than a pound; it might have been a little less than a pound – approximately.
Finally, Varunya (Varunya) in Thailand wants to know how we pronounce the word (live). There are two pronunciations for this word,” one is “live.” “To live” means to not be dead. You could say someone is “living,” meaning they’re breathing; they’re the opposite of dead. “Live” can also mean that you are resident, or you occupy a particular place: “I live in a house,” this is where I spend my time, where I sleep. The other pronunciation is “live.” “Live” is usually is usually used to describe something that you are seeing performed, for example on television or on the radio, as it is happening. In other words, it wasn’t recorded and then played back again; it’s actually something going on right now. “The World Cup was broadcast live from Brazil last year,” you could watch the soccer game as the game was going on. Or you could say, “Andrea Bocelli’s CD is really awful, but he’s even worse live,” when you hear him sing in person or live on the television. I’m joking, of course, just a little joke about the famous singer.
So that’s “live” and “live.” There’s a third word, “alive” (alive), which means that a person is living. Consider the following sentence: “I thought that actor was still alive (I thought that he wasn’t dead). I heard, however, that he died two years ago. How long did he live?”, with “live” as the verb here. So “alive” and “live” are related to each other, but they’re used differently. “How long did your grandmother live?”, meaning how many years was she alive. Those two things mean the same. Here, “alive” is an adjective describing the person, and “live” is the verb.
If you have a question or are confused about something in English, don’t have a meltdown! Send us your question to eslpod@eslpod.com, and we’ll try to answer it on a future English Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
medical properties – characteristics of a substance that doctors can use to treat or care for their patients
* Researchers are studying the medical properties of herbs found in these mountains.
chemotherapy – the treatment where dangerous chemicals are put into a person’s body to try to kill cancer cells and stop cancer from taking over a larger part of one’s body
* Diana is undergoing chemotherapy, which makes her feel sick and weak for days afterwards.
nausea – the feeling of uneasiness in one’s stomach, as though one needs to vomit; feeling sick and needing to throw up
* Riding in a boat or a ship always gives me a feeling of nausea.
appetite – desire to eat; wanting to eat
* The children had big appetites after playing in the park all morning.
to prescribe – to give patients permission to get and to use a type of medicine
* The doctor prescribed a new medication for him since the old one didn’t seem to be working anymore.
dispensary – special buildings or places that give out medicine
* When I was in the army, we had to go to the dispensary to get aspirin and other non-prescription medication.
cannabis club – places where people can purchase marijuana for medical purposes
* The police watched the cannabis club on this street to make sure that only people with doctor’s prescriptions were being sold marijuana.
screenwriter – a person who writes the document that is used to make a movie, including the characters, the setting (where and when the story happens), and the dialogue
* The director wasn’t happy with the script and asked the screenwriter to change several scenes.
one-liner – a short joke, usually with one or two lines; a short, witty remark
* I really like Christine, but she likes delivering one-liners to try to get laughs, so it’s hard to get to know her.
stand-up comedian – a person who stands in front of an audience with a microphone and tells funny stories or jokes to make people laugh
* We went to a comedy club last weekend and watched several stand-up comedians perform.
caption – a line of text below a photograph or drawing, usually providing more information about what one is looking at, or where it came from
* The caption under this photograph says that it was taken in 1933!
dark – themes or ideas that are evil or unpleasant, or that make people feel uncomfortable
* We thought this movie was a comedy, but the story was really dark and disturbing.
sky – the air above any point on the Earth; the space above the ground and over one’s head
* We’re sure that a storm is coming from the way the sky looks this morning.
skies – plural of “sky”; the space above the ground and over one’s head, often used when speaking of a large country or large area of land
* The airplanes flew low across the skies above New York City, causing people to wonder if the city was under attack.
meltdown – a loss of control due to being overtired or upset; a loss of control due to strong emotions
* Jo had a meltdown when she heard that her son had died in the plane crash.
crack down – strongly enforcing a law or rule; the increased enforcement of a law or rule
* The police crack down on drunk driving reduced the number of deaths related to traffic accidents this month.
more is less – a phrase meaning that a large amount of something is not as good as a smaller amount
* I think that Susanna is wearing too much jewelry. I always believe that more is less.
less is more – a phrase meaning that a small amount of something is sometimes better than a larger amount
* When putting on perfume, don’t you think less is more?
What Insiders Know
The Comedy Duo of Cheech and Chong
In the entertainment “industry” (business), there are a lot of famous “duos” (couples; two people who work together as a team). There are famous dance duos, such as Fred Astaire and Ginger Rogers in the 1920s and 1930s, and there are many comedy duos, who have made us laugh.
One famous comedy duo from the 1970s and 1980s is Cheech and Chong. The two comedians – Richard “Cheech” Marin and Tommy Chong – started out as stand-up comedians. Their favorite “themes” (subjects) were those of the hippy “era” (period) of the 1970s. “Hippies” were people who didn’t believe in traditional culture, and who believed in “free love” (sexual freedom) and taking “hallucinogenic” (making you see and hear things that are not really there) drugs.
Cheech and Chong made people laugh because they made fun of themselves as hippies. They often pretended to be under the influence of marijuana, and in fact, their first movie was called Up in Smoke. The title has a “double-meaning” (two meanings). First, it is referring to their favorite activity of smoking marijuana. Second, when we say that something “goes up in smoke,” it means that it is completely destroyed. This movie was fairly successful and it developed a “cult following,” which is when a group of fans become very “devoted” (giving a lot of one’s time and energy) to something.
Although Cheech and Chong aren’t together anymore, they have each gone on to “solo careers,” working without their partner. They have also occasionally “reunited” (come back together) in recent years for a few performances.