= 1539
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 234.
This is English as a Second Language Podcast’s English Café episode 234. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, in California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, which has even more courses in English for you.
On this Café, we’re going to talk about classic game shows. Game shows are a type of TV show; we call them “classic,” we mean that they are ones that have been around for a long time, or are of a certain high quality perhaps. We’re also going to talk about something called the sister cities program, the way many American cities have sister cities that they are connected to in another country. This is a program in many different countries. As always, we’ll also answer a few of your questions. Let’s get started.
This Café begins with a discussion about game shows, which are television shows that have people – we would call them “participants” – who play different games. Usually these are silly games, not serious games, and if they win the game they win money or prizes. One very popular show, that is now in many other countries as well, is called Who Wants to Be a Millionaire. It became very popular a few years ago, maybe 10-11 years ago. You may have seen it, or a version in your country.
There are also many older, what we would call classic game shows. Something that is a “classic” is old, but it’s still very popular because it’s considered to have a high quality. In literature, for example, people talk about reading the classics. For English literature that would be, for example, Shakespeare or one of the other great English language writers. We can talk about a classic anything really: a classic movie, a classic car – a classic podcast perhaps someday!
The classic game shows were on the air, meaning they were being shown on television, for many years. They were eventually taken off the air, meaning they were no longer shown. So “on the air” is when something is on television now, “off the air” is when it is no longer being broadcast. When I say “on the air now,” I don’t mean right this minute, at 10:00 on Wednesday morning, I mean it’s currently being broadcast every week or every month or every day. The classic game shows appear to be making a comeback, however. The phrase “to make a comeback” (comeback – one word) means to become popular again. For example, in fashion, in the way that people, mostly women, wear their clothing, long skirts might make a comeback after several years of short skirts being popular. The phrase “to make a comeback” can also be used to describe a sports team or an athlete who is starting to win after losing for many years or many games.
One game show that has made a comeback in the United States is called The Price Is Right. I remember watching this show when I was a child back in the 1970s. It was originally produced – it was originally made between 1956 and 1965, so it goes back many years. Then it went off the air for a few years, but made a comeback in 1972 and it is still on the air today. It has been on the air continuously, I believe, since 1972. In this game, The Price Is Right (or the price is “correct”), the audience waits to see who will be chosen to play the game. So there’s a big group of people and they call, or announce someone’s name, and what they say when they announce their name is that they should “Come on down.” “Come on down” means get off your seat, walk down to the place where the players are playing. Of course, people are very happy when they are chosen. The actual expression they use is, for example, “Lucy Tse, you’re the next contestant on The Price Is Right! Come on down!” Of course the person is happy, and they’re smiling, and they’re laughing, and they think they won the Olympics or something!
They announce the names of four contestants. A “contestant” is a person in a contest – in a game, trying to win something. In this case, it’s someone participating (someone who is a part of, someone we would call a “participant”) in the game show. Now the contestants on The Price Is Right try to guess the price of a product; it could be a car – probably not a car, usually something cheaper like a new stove or a brand new table. They try to guess the price of this particular thing – this product, and whoever guesses the closest – whoever’s guess is the closest to the price without being more than the price, that is, without going over the actual price, wins that particular round or that particular game. Well, they play several games, and the person who has the most money at the end gets to go up on stage, gets to play a game for an even bigger prize. Usually, these are called a “showcase” of prizes, a very nice group of prizes, such as new furniture for your house, or a nice trip to a foreign country. That’s The Price is Right. The person who was the “host,” the person who ran the games for many, many years was a man by the name of Bob Barker, and most Americans of my generation and older know who Bob Barker is.
Another classic game show, again, for people in my generation originally, was called Let’s Make a Deal. A “deal” (deal) is a transaction or an exchange or agreement between two people. For example, I say, “I’ll give you something if you give me something,” or “I’ll do something for you if you do something for me,” that’s a deal. “Deal” can also mean a very good price, a cheap price on something. Here, it means mostly we’re going to come to an agreement: you’re going to give me something, and I’ll give you something back.
Let’s Make a Deal was originally on the air from 1963 – which many of you know is probably the most important year of the 20th century – to 1976, but again, it made a comeback. It appeared again in the late 1970s, again in the 1980s, in the 1990s, and more recently in 2003. That’s sort of like those dance songs, they would have Spanish names like “La Lambada” or “The Macarena.” They become popular like once every five or seven years, I’m not quite sure why – perhaps it’s the weather! But in any case, this is a game show that has become popular many different times over the last 47 years.
As with The Price Is Right, the members of the audience, the people who go to watch the game, don’t know whether they will be chosen to play the game. The “host,” the person who leads the show, chooses people in the audience to be contestants. Sometimes, the host would give an audience member a prize of some medium value, something that wasn’t very expensive but wasn’t cheap either, let’s say a television. Then this contestant would be asked to choose whether he or she wanted to keep that prize or to trade it in for another – to make a deal: I’ll give you this television and you give me a different prize. However, you didn’t know what the other prize was; it was hidden, usually behind a door or a big curtain, sometimes in a box. Often you were given a very nice prize, but sometimes you were given a very bad prize: something that was cheap, something that wasn’t worth anything; but you didn’t know, you see. Typically, they would have three doors, and you could choose one of the three doors. One of the doors would have a very nice prize, the other two doors often had very bad prizes like a cat or a compact disc of disco music from the 70s, you see. That would be bad prize for me, anyway!
Let’s Make a Deal had many similar games; they were all based on the idea of trading prizes, of making a deal, giving up one thing to get something else without knowing what that something else was. The show always ended with the Big Deal of the Day, and this is where they had the Door #1, Door #2, and Door #3. After the contestant selected one of the three doors then the host would say, “Let’s see what’s behind Door #1,” or whatever door that she didn’t pick.
We’ll talk about one more classic game show in the U.S.: The Newlywed Game. “Newlywed” (newlywed – one word) is someone who has recently gotten married. “Wed” is another verb for “to marry.” “Newlywed” is someone newly married – someone recently married, usually within the past year or so. On The Newlywed Game, these newlywed couples would compete against other newlywed couples by answering questions that were supposed to tell you how well the husband – the new husband and wife knew each other. So what would happen is they would take all of the wives, and they would go into another room, and they would have just the husband. Then they would ask the husbands questions about their wives. For example: “What is her favorite color?” or “Where did you go on your first date?” Then they would bring the wives back and they would ask the wives the question and if it was the same answer, well then, they got points or a prize or money.
The Newlywed Game began in 1966 and has had many different versions, and it is still on today – this year, in 2010. Some of the questions on the show were related to sex; it wasn’t a vulgar or dirty show. When the show was new, in the 1960s, TV shows would almost never have phrases like “having sex” or “making love,” so the host of this particular program used the phrase “making whoopee.” “Making whoopee” is an old expression even, which means the same as having sexual relations with someone, preferable your husband or wife. It became very popular, and it is often used kind of as a joke nowadays. The expression actually comes from a very old jazz-blues song from the 1920s, and it has been recorded by many different singers, including one of the great popular singers of the 20th century in the U.S., Mr. Frank Sinatra.
So, those are three classic game shows The Newlywed Game, Let’s Make a Deal, and The Price Is Right. Of course, there are other games on now. I don’t watch game shows, myself, very often. But there are, of course, many others as well.
Our next topic is rather different; we’re going to talk about something called the sister city program. A sister city is when two cities, usually in different countries, make an agreement to have connections, have what we would call “ties” (ties). Usually, these are cultural or commercial connections, or ties.
For example, the first city, in the U.S. anyway, to become a sister city was Toledo, Ohio. It became a sister city with the city of Toledo, Spain. Notice in Spain it’s pronounced “Toledo,” that’s the original city; in the United States we say “Toledo.” Anyway, it was established, this sister city relationship, in 1931. In 1956, the then President of the United States, Dwight Eisenhower, created the American sister cities program, which is now called Sister Cities International. The purpose of the program is to try to build partnerships – improve partnerships and connections between the U.S. and other cities in other countries for both cultural understanding as well as for business relationships.
In a typical sister city relationship, an American city might celebrate important holidays that the other city celebrates, or it might organize a cultural festival related to the culture of the sister city. An American city might send businesspeople from their city to the sister city to learn how business works in that city.
American cities often have many sister cities – lots of sisters. I don’t know why there aren’t any brothers, but there are just sisters! According to Sister Cities International, our own beautiful Los Angeles, California, has 26 sister cities, including Yerevan, Armenia; Makati, Philippines; and Auckland, New Zealand. So, 26 sisters – big family, hope they have more than one bathroom!
It’s difficult to measure the benefits of participating in a sister city program. Some people believe it is a “waste” of money, meaning it’s not a very good way to spend money. Other people think the sister cities program just gives city officials – city leaders a chance, an excuse, to go to another country. But many people think the sister city program leads to greater international understanding. I’m not sure which of those answers is correct!
Now let’s answer some of the questions that you have sent us.
Our first question comes from Keochua (Keochua), currently living in San Jose, California, here in the United States. The question has to do with the expression “beyond a reasonable doubt.”
“Beyond a reasonable doubt” means that you are very sure that something is true. Usually, we use this expression in a courtroom for a legal matter. If someone, for example, commits a crime, that person, if they are arrested, would go to a trial – would go to a courtroom typically, and the group of people who decide if the person is guilty or innocent, what we call the “jury,” usually 12 men and women, have to decide whether this person is guilty beyond a reasonable doubt. It really means you don’t have to be 100 percent sure that the person is guilty; you just have to be mostly sure – beyond a reasonable doubt. In other words, yes, you could come up with an excuse of why the person is innocent, but if it isn’t reasonable – if that isn’t something that most people would say, “yes, that’s logical, that makes sense,” then you have to vote for the person to be guilty.
This idea of having to be beyond a reasonable doubt was originated in medieval England. It made its way into other western countries. Not all countries, however, have this “standard,” this rule that they apply, that they use for deciding if someone is guilty or not – if someone is the person who committed the crime or not.
Shinichi (Shinichi) in Japan would like to know the meaning of the words “infinite,” “permanent,” and “eternal.”
“Infinite” (infinite) means without end, or too many to be counted. Many people see the United States as a land of infinite opportunity. That’s probably not true, but that’s what some people may say! We could talk about a certain kind of number being infinite; usually this is represented in mathematics by what looks like the number eight, but on its side – horizontal, rather than vertical (?). Sometimes in conversation when people use the word “infinite,” they just mean a very large number; they don’t necessarily mean something that is truly infinite – something that never ends, or something that is of a number that could never be counted.
“Permanent” is a little different, “permanent” means that something will not change, something will last or continue for a very long time. “Permanent” is the opposite of “temporary.” The opposite of “infinite” is “finite” (finite), meaning limited in number. “Permanent” is the opposite of “temporary,” meaning that it will last a long time.
“Eternal” (eternal) means continuing forever and never stopping, without end. Something could be permanent and last, say, 500 years. But something that is eternal would last forever; it would never end. For example, in a cemetery outside of Washington, D.C., called Arlington National Cemetery, there is the grave, the place where they put the body of John F. Kennedy, who was, of course, killed in 1963 when he was President. And on top of his grave they have what’s called an eternal flame, a fire that is always on. It probably won’t truly be eternal, but it has been that way for at least a half a century almost.
So, “infinite” is often used to talk about possibilities, opportunities, sometimes about space and time. “Permanent” is used to describe situations or states of something, such as a permanent job. It’s a job that you have that is not just for a month or two months, a permanent arrangement or agreement. “Eternal” is usually used to talk about, for example, feelings. You may talk about eternal love: loving someone forever. “Eternal” is often used in religious situations or contexts as well.
Each of these adjectives can also be made into adverbs simply by putting the “ly” suffix at the end – adding an “ly.” You could talk about the infinitely expanding Internet, or the permanently removed mustache, or someone who is eternally grateful for something.
Finally, Parham (Parham) in Canada would like to know the difference between “forward” and “forwards,” especially when we are talking about going in a certain direction. Both “forward” and “forwards” can mean going in the direction that is in front of you, that you are facing, we would say. It can also mean in the future.
“Forward” is much more common than “forwards.” Really, “forward” is the only acceptable form if you’re going to use this word as an adjective, such as for example in a airplane you have two different sections. You have the first class section, which costs a lot of money, and then you have the section in back, which we call the coach section. You could call the first class section the forward section; it’s the section that’s in front.
“Forwards” was used in the past, but it is not as common anymore. So to be safe, just use “forward,” without the “s.”
If you have a question or comment, we’ll try to answer it as best that we can. We don’t have time, unfortunately, to answer everyone’s questions. You can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
game show – a television show with participants who play games to win money or prizes
* On this game show, people win money for every question they answer correctly.
classic – something old, but still very popular because it is of very high quality
* This car is not a piece of junk! It’s a classic.
on the air – shown on television; broadcasted on television
* I missed this show when it was on the air, but I’m now watching it on DVD.
to make a comeback – to become popular again; to have people interested in it again
* I know that he was a pop star in the 80s, but do you think he can make a comeback?
contestant – a person who is trying to win something; a participant in a game show
* Even though Sally has a good singing voice, she is too nervous to be a contestant in the singing contest.
showcase – something very nice that is on display; a special thing placed somewhere where many people can see it
* This play is a showcase for my favorite actor. He has several long speeches and important scenes in it.
deal – transaction; an exchange that two parties or two people agree to
* Shinobu made a deal with his sister: he would clean her room and she would lend him her videogame.
newlywed – a person who was married recently, usually within in the past year
* Jim and Pam are newlyweds and are still setting up their new home together.
to make whoopee – to have sex; to make love
* Stop making jokes about making whoopee in front of my parents. You’re embarrassing me!
sister city – a formal agreement between two cities in different countries to promote their cultural and business connections
* A group from my school visited Taipei as part of the sister city program.
ties – connections; relations
* I didn’t know you had ties to the restaurant business. How long has your family owned restaurants?
waste – using without purpose; spending or using carelessly
* My mother always told me to turn out the lights when I leave a room so I don’t waste electricity.
beyond a reasonable doubt – being completely certain that something is true; having overwhelming proof that someone did something wrong; a situation that leaves no significant doubt in anyone’s mind
* Sam’s lawyer said that he would prove beyond a reasonable doubt that Sam is innocent of the crime.
infinite – without end; too many to be counted, used to talk about time, space, or quantity
* If you go to college, there are infinite possibilities for what you can do with your life in the future.
permanent – not changing in the future; lasting a long time without change; not temporary
* Will your move to Birmingham be permanent, or will you move back to Seattle next year?
eternal – continuing forever without stopping; without an end
* When Emil asked Pilar to marry him, he told her that his love for her was eternal.
forward / forwards – in the direction that one is facing; toward the front; in the direction ahead; in the future
* Instead of trying to place blame for what has happened in the past, let’s move forward and work to do better in the future.
What Insiders Know
Game Show Network
“Cable television,” extra television stations that one can get by paying extra money, is known for it’s “niche” (specialized; focused on one topic) programming. Early cable television featured stations that showed music videos and sports. Since that time, many new niche stations have appeared to “satisfy” (give people what they want) the taste of its viewers.
Are you “addicted to” (need and want very much) game shows? If you are, you’re “in luck” (very lucky). Most cable television systems in the United States have available a channel called the Game Show Network or GSN.
GSN was “launched” (started) in 1994. The station began by showing “reruns” (shows already shown on television) of popular game shows. You could watch game shows that aired before the 1970s, many of which are considered classics.
Today, GSN continues to show reruns of popular game shows, but a large part of its “programming” (planned programs) consist of original game shows produced for GSN. Many of these shows have “celebrity” (famous person) “hosts” (people who are in charge of a show, who introduce the other people, and who manage the activities on the show).
Another “innovation” (something new) is the introduction of “interactive call-in shows,” that allow viewers at home to play games “live” (not recorded), either by making phone calls, by emailing, or by “texting” (using an electronic device to send messages). GSN has grown a lot in popularity since its beginnings and is the perfect fit for people who love watching and playing games.