= 1526
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 221.
This is ESL Podcast’s English Café episode 221. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English that you will enjoy, I think. You can also download the Learning Guide for this episode, and every current episode. The Learning Guide contains lots of additional information, including a complete transcript of this episode, vocabulary words, definitions, sample sentences, cultural notes – oh, and did I mention a comprehension quiz on what you’re listening to now.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed. We’re going to listen to them and explain what they are talking about. Today we’re going to talk about the way that many people are watching television programs over the Internet in the U.S. And as always, we’ll also answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is the way in which many people are now watching television programs over the Internet instead of on their TV. We’re going to listen to Mark Kellner, who is a technology columnist, that is a person who regularly writes about technology, for a newspaper called the Washington Times, in Washington D.C. This is actually an interview on Voice of America recently. The Voice of America reporter is interviewing another reporter. That, of course, makes it easier for him; you just pick up the phone and call one of your friends who’s also a reporter, and there you have your story. Well, we’ll listen first as he talks about how people are changing the way they watch TV. As always, try to understand as much as you can, then we’ll go back and explain what he said. Let’s listen.
[recording]
“Well, regular TV is still the dominant way people watch programming in the United States. But, more and more, folks are turning to the Internet and alternatives such as Hulu – H-U-L-U.com – to watch programs on their schedule, as opposed to the broadcaster’s schedule.”
[end of recording]
Mark begins by saying that regular or normal TV is still the dominant way people watch programming (or television programming – television shows) in the United States. The word “dominant” (dominant) means strongest, or most powerful. If you’re right-handed, your right hand is your dominant hand, because it’s stronger or more powerful than your left hand, at least when you typically use it. The word dominant can also mean more common, most popular, and in this context when Mark says that TV is the dominant way Americans watch programming, he means that most Americans watch programming on TV. TV is the dominant or most popular way. Programming, as I mentioned, is anything that’s on a television channel: sports, TV shows, movies, the news. All of these are programming – TV programs.
Next, Mark says that more and more “folks” (folks) or people (it’s an informal term for people – folks) are turning to the Internet. The phrase “to turn to (something)” means to begin to use something or begin to do something. Maybe you’ve always liked rock-and-roll music, but now you’re turning to jazz, meaning you’re starting to prefer to listen to jazz. People used to watch programming on their television, but now they’re turning to the Internet, starting to use the Internet as a way to watch programming. Marks says this is happening more and more, meaning it’s becoming more common, more frequent. Now, these people haven’t stopped watching television completely yet, but their preferences are starting to change, that’s what he’s saying here.
Mark then says that people can watch programming on a website called Hulu.com. He explains that this website lets people watch programs on their schedule, as opposed to the broadcaster’s schedule. The phrase “as opposed to” means in contrast to, and we use it when we want to emphasize that two things are different. For example, we used have five podcast episodes a week when we first started back in 2005, as opposed to the three episodes a week we have now. We moved from five to three because it was almost impossible to produce five good episodes every week. And of course, here at ESL Podcast we want to produce the best for you – nothing but the best for you! Marks says that people can watch this programming on Hulu.com, and it allows them to watch programs on their schedule as opposed to the broadcaster’s schedule. The “broadcaster” would be the television station. Even though your favorite program is on at 8:00 at night, if you go onto Hulu.com some of those programs will be on there and you can watch them whenever you want. Of course, you could also tape or record the programs, which people have been doing for many years. So the idea that you would watch programs on your schedule, as opposed to the broadcaster’s schedule is certainly not new.
Let’s listen to Mark one more time.
[recording]
“Well, regular TV is still the dominant way people watch programming in the United States. But, more and more, folks are turning to the Internet and alternatives such as Hulu – H-U-L-U.com – to watch programs on their schedule, as opposed to the broadcaster’s schedule.”
[end of recording]
Our good friend Mark now talks about which kinds of people are watching their programming on the Internet instead of on TV. Let’s listen.
[recording]
“Logic would sort of suggest younger people would be more likely to watch online; they have the experience and so forth. However, this is cutting across generational lines, and if you’re a tech-savvy senior citizen, it’s very likely that you could watch a program online as well.”
[end of recording]
Mark says that logic – that is, rational thinking – would make you think that younger people would be more likely to watch online, since they’re the people who have a lot of experience doing things on the Internet. When he says “younger people,” he, of course, means people who are 46 years of age or younger – just so you understand that. However, he says, watching TV on the Internet is cutting across generational lines. A “generation” is a group of people who are born at about the same time. For example, here in the United States we talk about baby boomers. These were people who were born after World War II, roughly between 1946 and 1964. That’s considered a generation. I am part of the baby boom generation; in fact, my entire family – my siblings (my brothers and sisters) were all born in this period. My oldest brother was born in 1946, I was born in 1963, so we are all baby boomers. A “boom” (boom) is a sudden increase in something; it could also be a loud sound. So, baby boomers were when the American population grew very quickly because everyone was having children again. The phrase here is “cutting across generational lines.” Generational lines would be the differences between generations, or among generations. For example, there are clear generational lines in music. Some younger people, under the age of 46, may like to listen to rock-and-roll music. Older people – older than 46 would perhaps like to listen to jazz or other kinds of music. I’m joking, of course! But, there are differences among generations and what they like to do, and these are called “generational lines,” the dividing line, if you will, that separates two groups and their preferences.
Marks says that watching TV on the Internet is cutting across generational lines. To cut across something means to reach across something. In this case, watching TV on the Internet is something that people in many different generations do, not just the baby boom generation or the younger generations – generation x, generation y. The newest generation, those born more recently, I think they’re going to call them the millennial generation. Of course, in the year 2001 we entered into a new millennium – a new thousand-year period. They may also call those being born nowadays the loud generation – that’s what I call my neighbors children! So, we’re cutting across generational lines here, watching programming on the Internet versus on TV is something popular with younger and older Internet users.
I just should say also that also I’ve been saying the word “Internet” or “Innernet.” Notice the difference: Internet – Innernet. When I’m being careful about my pronunciation, I will probably pronounce that “T” sound. But in common, normal conversation it’s quite common for people to speak quickly and to sometimes eliminate certain sounds, especially in the middle of a word. So, instead of hearing “Internet,” you will often hear Americans say “Innernet,” as if there were no “T” in the word. But both are common, as long as you understand what people are saying there’s no problem.
Mark – remember Mark? He says that if you’re a tech-savvy senior citizen, or older person, it’s very likely that you could watch a program online as well. Someone who is “tech-savvy” (tech-savvy) knows a lot about technology (tech means technology) and is comfortable using computers and other types of modern machines. To be savvy means to be very wise, to know lot about something. My nephew, for example, is very music-savvy; he knows a lot about modern music and bands and rock groups and so forth. Mark is talking about tech or technology-savvy senior citizens, older people.
Let’s listen to Mark’s quote one more time.
[recording]
“Logic would sort of suggest younger people would be more likely to watch online; they have the experience and so forth. However, this is cutting across generational lines, and if you’re a tech-savvy senior citizen, it’s very likely that you could watch a program online as well.”
[end of recording]
Notice when Mark talks he often pauses, or stops speaking. When he’s trying to think of something else to say, he’ll make the sound “uh.” He may say, “Logic would sort of suggest, uh, younger people…” and so forth.
Finally, we’re going to listen to Mark answer the question asked of him about whether someday people will watch programming only on the Internet, and not on television at all. This is a rather long quote, so get as much as you can and then we’ll go back and explain it. Let’s listen.
[recording]
“It’s possible. Whether it’s likely or not, I can’t say, but the probability, or possibility, is there. Ten years ago, twenty years ago, we all thought print newspapers were indestructible and look now. That industry is changing quite rapidly. It could happen in television. When television first came on the scene…then when cable television first came on the scene, the movie theaters were very, very worried that no one would go to the movies anymore. And yet, Hollywood is still, what, a 30 or 40 billion dollar – that’s U.S. dollar – a year business. Hollywood didn’t die and somehow I think television will be with us for quite some time.”
[end of recording]
In answering the question about whether people will someday watch programming only over the Internet, Mark says it’s possible. Well, thank you Mark for telling us that it is possible! Not really an answer to the question, in fact he next says, “Whether it’s likely or not,” meaning whether people will actually do it or not, “I can’t say.” When someone says, “I can’t say” or “he can’t say” or “she can’t say,” they mean I don’t know, I don’t have enough information to talk about that. Now remember, Mark is a reporter for technology, and he can’t say, so I guess he hasn’t gotten enough information. I suggest he use the Internet, or maybe talk to another reporter!
Marks says, “Whether it’s likely or not, I can’t say (I don’t know), but the probability, or possibility, is there.” The “probability” of something refers to, in mathematics, the likelihood something will happen. Let’s say I have a bucket – a bowl with ten balls. Six of them are green and four of them are blue. If I reach into the bucket or reach into the bowl with my eyes closed and I just take one of the balls out, the probability that it will be blue is 4 out of 10, or 40 percent, because there are four (blue) balls, remember, and ten balls total. That’s an example of statistical probability.
Mark says he doesn’t know whether people are going to be watching TV only over the Internet, but that there is a probability, meaning there’s a likelihood. Normally, in non-scientific conversations, probability means likelihood. Someone says, “Well, I think it’s probable that it will rain today,” they mean they’re pretty sure; it’s very likely. If somebody says, “It’s possible it will rain today,” that usually means they’re less sure. It might, it might not; they don’t really have a lot of evidence one way or the other. Mark says, “the probability, or possibility is there,” meaning it exists – obviously!
“Ten years ago, twenty years ago,” he says, “we all thought print newspapers were indestructible and look now.” Print newspapers would be what we normally just call newspapers, but we call them print newspapers now because, of course, you can read a newspaper on the Internet now, as well as have the actual paper newspaper in front of you. I prefer the paper newspaper, even though I am young! Mark says that 10 or 20 years ago everybody thought print newspapers were indestructible. Something that is “indestructible” is not destructible; “destructible” means that it is able to be destroyed. So, something that is indestructible is something that cannot be destroyed because it’s very strong. People thought that the newspaper business was very strong 20 years ago, before the Internet. But now, because everyone is getting their news for free on the Internet, many newspapers are having problems. I think this is mostly because the newspapers decided to give away everything rather than having people pay for it online, but that’s just my opinion.
Marks says that the newspaper industry – the newspaper business is changing quite rapidly, meaning very quickly, very rapidly. He says, “It could happen in television,” with the television industry. “When television first came on the scene,” he says – that is, when television first appeared or became available and people started watching TV and then later, when cable television first appeared, movie theaters were very, very worried that no one would go to the movies anymore. So, when television was first popularized in the 1950s and 60s in the U.S., many of the movie studios thought that they were going to be destroyed because everyone would just watch things on television. However, that is not what happened. Mark says, “And yet (meaning however), Hollywood is still a 30 or 40 billion dollar – that’s U.S. dollar – a year industry.” So, it’s a 30 or 40 billion dollar a year industry (or business). That’s how much the move business – which, of course, is here mostly in Los Angeles, although it’s also in other places – that’s how much money they make each year. Notice Mark says, “Hollywood is still, what, a 30 or 40 billion dollar a year industry.” The use of “what” there is when you are saying something and you don’t know exactly a specific piece of information, usually a number – a statistic, but you are going to give a good guess. So you might go to a party and there might be 20 beautiful women there; you’re not sure exactly, you haven’t counted them yet. So you say, “Oh, they must have been, what, 15-20 beautiful women at the party.” That would be example of “what,” when you are stopping yourself and indicating to the other person that you are sort of guessing. Mark says Hollywood didn’t die after the introduction of television, “and somehow I think television will be with us (will continue) for quite some time,” meaning for a long time.
Let’s listen to once more to good old Mark.
[recording]
“It’s possible. Whether it’s likely or not, I can’t say, but the probability, or possibility, is there. Ten years ago, twenty years ago, we all thought print newspapers were indestructible and look now. That industry is changing quite rapidly. It could happen in television. When television first came on the scene…then when cable television first came on the scene, the movie theaters were very, very worried that no one would go to the movies anymore. And yet, Hollywood is still, what, a 30 or 40 billion dollar – that’s U.S. dollar – a year business. Hollywood didn’t die and somehow I think television will be with us for quite some time.”
[end of recording]
Now let’s answer a few of your questions.
The first question comes from Gabriele (Gabriele) in Italy. Gabriele wants to know the meanings of the verbs “to search,” to look for,” and “to seek.”
“To search” means to look through or in something in order to find a particular thing; you’re trying to find one particular item – one particular thing. “I’m looking for my glasses, I will search in my suitcase.” Of course, if I don’t have my glasses on it will be kind of hard to find my glasses, but you get the idea!
“To look for” means to try to find something, so it can be similar to the meaning of the verb “to search.” It can also mean to stay alert for something or someone, to be expecting someone or something. Someone may tell you, “Look for the television show on tonight about the cats and the screaming children, it’s great.” They mean you should be expecting a television show on tonight and you should try to watch it. So that’s another meaning of “to look for.” “To look for” can also mean the same, as I said, as “to search”: “I’m looking for my glasses in my suitcase.”
“To seek” is a little different than the first two verbs. “To seek” means to try to find something, to hope to find something, to look for something or someone, but usually the idea is that it is something of great importance. In fact, often we use this verb “to seek” when we are talking about, say, the truth. “I am seeking the truth,” I am looking for the truth. It’s a little bit old-fashioned now in American English, however “to search” or “to search for (something)” and “to look” or “to look for (something)” are still popular. “Seek” is a verb that you might find in an older book or older translation. “Seek and ye shall find” is a quote from the Christian Bible. “Seek (look for something) and ye (a very old way of saying “you”) shall find,” you will find it if you look for it.
Link (Link) in China wants to know the meaning of the expression, or idiom, “to be pushing up daisies” (daisies). “To be pushing up daisies” is an idiom (informal expression) meaning to be dead. “That dog won’t bother you again, by now he should be pushing up daisies.” Or, “By this time tomorrow that murderer will be pushing up daisies, because he’s being executed (killed by the government).”
It’s traditional in most parts of the United States to bury the dead – bury the body of the dead in the ground. Once it is in the ground, what we call the “grave,” the hole where you put a body, it’s filled with dirt and grass and sometimes other plants grow on top of the grave. One thing that could grow is a flower – a daisy, and the body underneath, the idea of this expression, is said to be pushing up or helping the daisies grow, because of course the body is below – underground. Of course, the body isn’t actually doing that, it’s just an expression. However, it’s an expression that you would never use for anyone or with anyone who was an actual friend or who knew the person who had died. It’s a very casual expression. You would never say, for example, “Oh, I hear your grandmother is ill (is sick). Is she pushing up daisies yet?” That would not be a good thing to say! It’s an expression you would use jokingly about, perhaps, a fictional character or somebody who’s not necessarily very close to the person you’re talking to. So, you have to be careful with that.
Finally, David (David), from an unknown (unknown) country, wants to know the definition of “do you have any idea…?” It’s an expression you’ll often hear when people are angry. In fact, you use this expression to indicate, or to tell the other person, that you are angry. When used in this way, you’re not actually asking a person a real question; you’re simply using that form to let them know how angry you are. “Do you have any idea what time it is?” you might say to, say, your son or daughter who’s making a lot of noise late at night, and you knock on their door and you go into their room and you say, “Do you have any idea what time it is young lady?” That would be not a real question, of course you already know what time it is; you’re merely expressing your anger at that person.
However, it can be used as a real question, when you’re not angry, to indicate that you don’t know the information but that you want to get a little bit more information from the person you’re asking. So, you may say, “Oh, your necklace is very beautiful. Do you have any idea how much it cost?” Well, you probably wouldn’t ask a woman that, but that’s an example of “do you have any idea…?” when you are actually asking a question, you really want to know the answer.
One more thing, when you are using “do you have any idea…?” and you’re angry, you can sometimes use it to indicate that you think the other person has no idea, the other person is ignorant of something. Somebody says to you, “Oh, did you finish your new book yesterday?” and the book is, let’s say, a thousand pages long. You may say to that person, “Do you have any idea how long this book is?” You’re saying really, “Are you stupid? You don’t even know how long this book is and you’re asking me if I finished it already.” That would be another use of that expression.
If you are looking for – if you are seeking the answer to one of life’s important questions in English, you can email us. Our email address is eslpod@eslpod.com. With luck, we’ll answer it before you’re pushing up daisies!
From Los Angeles, California, this is Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
dominant – strongest or most powerful
* The dogs are fighting to see which male in the group is dominant.
programming – anything that’s on a television channel, like sports, TV shows, movies, and the news
* Do you prefer the programming on ABC or NBC?
to turn to (something) – to begin to do or use something
* To save money, they’re turning to home-cooked meals instead of restaurants.
as opposed to – in contrast to; rather than; a phrase used to emphasize that two things are different
* Theresa, it’s time for you to really start studying, as opposed to asking your friends to do your homework for you.
to cut across generational lines – to appeal to people who were born at different times, even though they often have very different interests
* The president’s message about the importance of volunteerism cut across generational lines, and soon people of all ages began volunteering in their community.
tech-savvy – knowing a lot about technology and comfortable using computers and other technology
* Do you know any tech-savvy people who can help us create a new website?
I can’t say – a phrase used when one doesn’t know the answer, or doesn’t have enough information to comment on something
* - Will Marsha agree to marry Kelvin?
* - I can’t say. She’s never really talked to me about their relationship.
probability – a mathematical term used to describe the likelihood that something will happen
* When you flip a coin, there’s a 50% probability it will land with the tail-side facing upward.
indestructible – so strong that something cannot be destroyed
* Why can’t anyone make an indestructible cell phone? Mine keep breaking every time I drop one.
to come on the scene – to appear; to become available; to become used or common
* When did that band first come on the scene?
to search – to look through or in something in order to find a particular thing; to try to find a particular thing
* A little boy is lost in the mountains, and many people are searching for him.
to look for – to try to find something; to stay alert for something or someone; to expect something or someone
* Could you please help me look for my glasses?
to seek – to try to or hope to find something; to look for something or someone
* The company is seeking new customers.
to push up daisies – an idiom meaning “dead”
* Someday we’ll all be pushing up daisies, so enjoy life while you can!
Do you have any idea…? – an expression used to show anger and displeasure
* Does she have any idea how inappropriate her behavior is?
What Insiders Know
The TV Parental Guideline Ratings and the V-Chip
Many parent worry about what their children see on TV. They don’t want young children to see shows with a lot of “violence” (actions that hurt other people), “foul language” (bad, impolite words), “nudity” (not wearing clothes), and sex. In response to their “concerns” (worries), the television industry created a “rating” (saying how good or bad something is) system to let parents know which programs are “age-appropriate” (okay for a child of a certain age to see) for their children.
The TV Parental Guidelines can be seen on the “screen” (the surface one looks at while watching TV) before a TV show begins, and sometimes after each “commercial break” (a period of time with many advertisements between parts of a show). In all, the system has seven ratings:
tvY – All children
tvY7 – Directed to older children
tvY7FV – Directed to older children – “fantasy” (imaginary) violence
tvG – General audience
tvPG – Parental guidance “suggested” (recommended)
tv14 – Parents strongly “cautioned” (warned)
tvMA – “Mature” (older; adult) audience only
Since 2000, most “television sets” (the piece of electronics that one uses to watch TV) have included a “V-Chip,” which is a “parental control” that lets parents decide which programs they want to “block” (not allow to be seen). The V-Chip allows people to watch programs only if they have the ratings that the parents have chosen to allow. The parents can “set” (create; establish) a password to “override” (ignore the rules of) the V-Chip, so that they can see shows with higher ratings when their children are not present.