= 1506
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 201.
This is English as a Second Language Podcast’s English Café episode 201. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to continue our series of famous Americans, focusing on a famous American author or writer named Flannery O’Connor. We’re also going to talk about a well-known TV show called 60 Minutes. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on famous Americans. Today we’re going to talk about a famous author or writer named Mary Flannery O’Connor. O’Connor was born in 1925 in the state of Georgia, and her writing is about the Southern United States. Georgia is located in the Southeast part of the U.S., on the Atlantic Ocean. In the United States, when we say “the South” (with capital ‘S’), that refers to the southeastern part of the United States. It doesn’t include, for example, Arizona or California even though, if you look at a map, they are in the southern part of the U.S. When we talk about the South, we’re talking about what some people would call the “Confederate South,” those states that broke away, or attempted to break away from the U.S. during the Civil War of the 19th century. We’re talking about the states of Louisiana, Mississippi, Alabama, Georgia, Florida, North Carolina, South Carolina, Kentucky, and Tennessee. Some people would include Virginia in that as well. That is the South, and Flannery O’Connor wrote about this area; this is where she grew up, where she was born.
Flannery wrote two novels, or fiction books, and 32 short stories. They’re all based in (or take place in) the American South. Most of her characters, or the people she writes about in her books and short stories, are what we might call misfits and fanatics. A “misfit” (misfit) is someone who does not fit into society, or who is somehow different from everyone else and has trouble interacting with people, making friends with other people; that’s a misfit. A “fanatic” is someone who believes in something very strongly, maybe too strongly. We sometimes talk about religious fanatics, people who take their religion very seriously, sometimes so seriously that they don’t understand other people’s beliefs and perhaps do some things they shouldn’t do, even according to their own religious beliefs. But you can be a political frantic, you can be a fanatic about all sorts of things.
In Flannery’s books, her stories of misfits and fanatics are often filled with violence and “faith,” or belief in God. Flannery herself was a devout Catholic. Someone who is “devout” (devout) is someone who believes in their religion very strongly and makes it a very important part of his or her life. Flannery O’Connor was a Roman Catholic who lived in an area of the United States where there are relatively few Catholics, so she was somewhat unusual in her religious beliefs for that area. What is more interesting is that very few of her characters are actually Catholic; most of them are not Catholic. And yet, she is considered very much, in American literature, to be a Catholic writer or a writer who was influenced by her view of the world – her philosophy of the world that was very Catholic in outlook – Catholic in perspective.
Flannery’s first novel, called Wise Blood, was published in 1952. Her second novel was called The Violent Bear it Away, and that was published in 1960. The phrase “to bear (something)” means to carry something, especially to carry something very heavy or very difficult. Notice the word “violent” in the title, “the violent” meaning the violent people. The other novel is Wise Blood; again, “blood” giving you this idea of violence somehow related to death. Although O’Connor is known for these two novels, her short stories are actually more famous in the U.S.; she has a well-known collection of stories called A Good Man Is Hard to Find, which is a collection of ten short stories that was published in 1955. That’s sort of an old expression, “a good man is hard to find,” something a woman might say when looking for a husband.
Most book critics, or people whose job it is to read and analyze books, and then say what they do or don’t like about them, say that Flannery O’Connor’s writing is often filled with the grotesque – grotesque things. Normally we use the word “grotesque” to talk about things that are ugly, unpleasant, weird, or strange. A horror film might be grotesque if it shows a lot of people dying with a lot of blood.
An example of the grotesque nature – the violent nature of some of O’Connor’s stories is a story from A Good Man Is Hard to Find. It’s about a family that goes on vacation, but then there is a car accident – their car gets in an accident. The family is found by a man who in the story is called The Misfit. The Misfit is a serial killer, a person who kills many other people, and I won’t tell you how the story ends, but of course, this family is now in danger. Many people call this story grotesque, although there are other themes or main ideas that critics focus on in this short story. There’s a very interesting scene of the grandmother trying to save her own life from this serial killer by talking about her religion, about Jesus Christ, trying to find out if the man is a Christian. This is an example of serial killers and murderers that take place in her books and short stories.
Now even though it sounds, perhaps, unpleasant, in fact the stories are not depressing usually, and they certainly aren’t horror stories; that’s not what Flannery O’Connor is about. O’Connor’s fiction is about some of the very basic questions of life: Who are we? Why are we here? What does it mean to be good? What does it mean to be evil or bad? She looks at these questions in her stories and through her characters.
I first read Flannery O’Connor when I was in college, back in the early 1980s. I read A Good Man Is Hard to Find, Wise Blood, The Violent Bear it Away, and other stories by her. I loved her writing; she is perhaps one of the few writers that is able to understand the American South and be able to capture – be able to describe the atmosphere of the American South in the early 20th century. It’s a fascinating portrait of people and ideas, and also of religion in that part of the country.
Flannery died of “lupus” (lupus), which is a disease where the body actually attacks itself; it can affect many different parts of your body. It’s what is sometimes called an autoimmune disease. This disease is fatal; it can kill you, although more recently they have developed treatments to prevent lupus from killing you. But it can kill you, and that’s what happened to Flannery O’Connor. O’Connor died at the age of 39; she died very young. If she had lived longer, she might have written much, much more, but of course we will never know.
After her death, there was also a collection of her letters that was published, which is quite interesting. I read some of that collection recently. Flannery O’Connor was an amazing writer and very intelligent woman, who had a very independent view on life compared to those around her.
In 1972, a collection of all of her short stories received the National Book Award; it was what we would call a “posthumous” award. The word “posthumous” (posthumous) means after death – after someone dies. O’Connor received this award – or members of her family, one guesses – in 1972, she died in 1964. The University of Georgia Press (a press is a publishing house or some organization that publishes books) gives away an annual award in Flannery O’Connor’s name. It’s an award named after her, or named in her honor: The Flannery O’Connor Award for Short Fiction.
The English in Flannery O’Connor’s stories is not necessarily easy; it is, of course, written for native speakers. But if you have a chance to try to read one of her short stories, I think you would enjoy it. She is, I think, an uniquely American author who gives you perspectives on the United States you can’t find from any other writer of the last hundred years or so.
Now let’s switch to a very different topic, which is a well-known television program called 60 Minutes. 60 Minutes has been “on the air,” which means it has been showing on TV, since 1968, and of all TV shows, 60 Minutes is the one that has run continuously, without stopping, for the greatest number of years in the U.S. during what we would call “prime time.” “Prime (prime) time” refers to the early evening hours when most Americans, who watch TV, are watching TV. Of course, not all Americans are watching television, but those that do will often – usually, we could say – watch during this prime time.
“Prime” means, in this case, first, important, the most important, and these hours between 7:00 in the evening and 10 or 11:00 at night are called prime time. Actually, it depends on what part of the country you are in. If you live on the coast – on the East Coast: Boston, Philadelphia, New York, or the West Coast: San Francisco, Los Angeles – I think there are other cities on the West Coast, less important! Anyway, if you live on one of the coasts, then you have prime time between 8:00 at night and 11:00 at night. However, if you live in the center part of the country such as Minnesota, where I grew up, then prime time is between 7:00 and 10:00. I guess people on the coasts go to bed later than those in the middle of the country.
60 Minutes, then, is a popular prime time television show. Although it’s on Sunday evenings, and here in Los Angeles it’s on at 7:00, which is just before the main prime time, but we call it a prime time program. Television stations usually put their most popular shows on the air (meaning they broadcast them) during prime time so they can have the largest number of viewers (people watching the show).
60 Minutes is a news show where the reporters are involved in what we call “investigative journalism,” finding interesting, perhaps secret or shocking information to tell people about. It’s a serious new show. It’s been so successful that there are other news shows in other countries that use a similar format. The reporters in 60 Minutes often use hidden cameras to see things that normally happen where no one can see them. They also sometimes show up, or go to someone’s house without telling them so they can catch them off guard. The phrase “to catch (someone) off guard” means to surprise them. You might catch your wife off guard if you ask her something that is unexpected. Well, these reporters try to catch people off guard, often politicians or businessmen who’ve done something wrong, and ask them questions trying to find out more about the story.
Each episode of the show has three long news stories. Sometimes these are profiles or biographies of famous people, but usually they’re stories about some corruption, something that has gone wrong, something scandalous that someone has done. Usually, again, it’s a company or the government that is being investigated, or individuals.
The stories are usually interesting, which is why 60 Minutes has remained so popular for so long. Some people think that sometimes, however, the stories go too far. The phrase “to go too far” means to do something too much, to do too much of something so that it becomes a problem. For example, it’s okay to eat chocolate every once in a while, but if that’s the only thing you eat every day, you’ve gone too far, you’ve done too much of that. 60 Minutes, according to some people, sometimes goes too far in its stories, changing the stories to make them more interesting, sometimes so interesting that they’re not actually true. This hasn’t happened very much, but it has happened a few times.
For example, back in 1986, when people were complaining that a particular kind of car, the Audi 5000, was accelerating, or speeding up, going forward even though it was supposed to be in park; that is, it was not supposed be moving. 60 Minutes reported that these accidents were hurting or even killing people, so the reporters for 60 Minutes tried to “replicate” the problem; that is, they tried to create the problem to see if it would happen to their Audi 5000 car. However, they were not able to do that, so they made some changes to the car’s engine so that it would have this problem that other people said was common or had happened with the Audi 5000. This made a lot of people stop buying Audi 5000s, even though it was later determined that the cars were actually safe, and the only reason that they had accelerated – they had gone forward – was because the people driving them had made a mistaken in their driving.
Many people have sued 60 Minutes; that is, they have taken the show’s producers (the people who make the program) into a courtroom for something called “libel” (libel). “Libel” is when you say things about people that are not true and you hurt their reputation. However, here in the United States it’s more difficult to sue someone for libel – to say that they’ve lied about you – than it is in some other countries, especially if you’re a news organization. News organizations are difficult to sue for libel. You usually have to show that the organization knew it was false and was trying to convey false information to hurt you. However, that’s much more difficult than proving that they made a mistake. News organizations can make a mistake, but you can’t necessarily sue them because of that.
60 Minutes is different from almost all other shows because it doesn’t have theme music; it doesn’t have music like we have in the beginning of our ESL Podcast. The only sound you hear at the beginning of the show is the ticking of a watch or a clock: tick-tick-tick-tick-tick-tick-tick-tick. That’s my imitation of a watch.
For many years, the host of the show, the person who introduced the news stories, was a man named Mike Wallace. At least, he was one of the most well-known hosts. He’s now 90 years old, and he’s still working – he’s still working on this program. He retired officially in 2006, though he still works with the show – just not as the host. I’m hoping that ESL Podcast will still be around when I’m 90; that would be, uh, let’s see, in 2043, but I probably will retire before then!
Now let’s answer a few of your questions.
Our first question comes from Mariusz (Mariusz) in Poland. The question has to do with expressions that have hyphens (a small dash) in the middle of the word, especially with the word “well” (well). For example: “well-written,” “well-built,” “well-mixed.” The question is when we should use the hyphen sign, and that’s a good question.
“Well” means good, proper, or in some complete way. You could say, “That house is very well built.” Or, “His kitchen is well stocked,” meaning has a lot of food in it. But, we don’t always put a hyphen in between the word “well” and the word that follows. Here’s the difference: If becomes before the noun, for example: “a well-built house,” then we use the hyphen. If it comes after the noun, for example: “The house is well built,” then we don’t. It’s a little tricky, for example: “This is a well-written book.” “Well written” comes before the noun, “book,” and therefore we use the hyphen. If you said, however, this sentence, which means the same thing, “This book is well written,” you would not use the hyphen. So, if it comes after the noun, it isn’t used; if it comes before the noun, it is used.
This is the rules for the word “well,” you can also use this for “best,” for example: “best-loved,” or “worst,” or “ill.” “It’s an ill-fitting dress.” “Ill-fitting” means badly fitting; it doesn’t fit the person, it’s too big or too small.
We would not use this for adverbs, words that typically end in -ly. For example: “That’s a beautifully written book.” There, there would be no hyphen between “beautifully” and “written.” So, just with the words “well,” best,” “worst,” and “ill,” perhaps a few others, that are common when it comes to having the hyphen in between the word.
Our next question comes from Ryan (Ryan) in China. Ryan was reading the news from the United States, and he heard the expression in a story about American politics: “red states and blue states.” A “red state” is a state in the United States that typically votes for the Republican Party, which is the more conservative political party. A “blue state” is a state that votes for the Democratic Party, which is typically more politically liberal.
This use of colors, blue and red, comes from the television networks – the television stations, when they show on election night – on the presidential election which candidate, which party won that state’s votes. If it was Republican, they would put the state in red; if it was Democrat, they would put the state in blue. No real particular reasons why red is Republican and blue is Democrat; simply, it was the way that the television networks and the newspapers decided to color the map so you could tell easily which states were won by the Democrats and which by the Republicans.
After the 2000 election, which was a very close election where George W. Bush defeated Al Gore (the Republican defeated the Democrat), people said that the U.S. was divided into blue states and red states, and the idea was that there was this political division. Generally speaking, states on the coast tend to be blue states: California, Oregon, Washington, Massachusetts, New York – both the East and the West Coast, especially the northeast, and states in the south and the center part of the country are more likely to be red states, especially in what we call the American West (west of the Mississippi River, between the center part of the country and the West Coast).
These are very general observations, however, and every election is different. So that’s where “blue states and red states” comes from.
No matter what state you come from, you can email us. Our email address is eslpod@eslpod.com. Send us your questions; we won’t have time to answer all of them, but we’ll try to answer as many as we can, giving you well thought out answers.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
misfit – someone who does not fit into society; someone who is different from everyone else and has trouble interacting with people and making friends
* When Dean was growing up, he felt like a misfit because he was much taller than his classmates.
fanatic – someone who believes in something very strongly; someone who believes only in one thing and believes it too strongly
* Julie is a fanatic about this TV show. She watches each episode four times and writes a blog about it.
devout – believing in a religion very strongly and making it a very important part of one’s life
* The Simes family is very devout and do not work on Sundays as part of their religion.
grotesque – ugly, unpleasant, and strange
* The doll that you bought for your sister is grotesque, and it is more likely to scare her than to delight her.
posthumous – after death; after one has died
* She was awarded a posthumous award for her work in helping the poor.
on the air – during the time that a show is seen on television or heard on the radio; broadcasted on television or radio
* My favorite radio deejay is on the air in the mornings between 7:00 and 10:00 a.m.
prime time – the early evening hours when many people are watching television at home after work
* The TV station decided not to show a movie in prime time because it has too much violence and children may be watching.
investigative journalism – finding interesting, shocking, and secret information and sharing it with readers or viewers
* It was because of excellent investigative journalism that the criminals in the city government were exposed and forced to leave their jobs.
to catch (someone) off guard – to approach someone who is unprepared; to talk to someone who did not know you were coming and who is not ready to speak with you
* Jahlil caught me off guard when he asked me for a date. I thought he was married!
to go too far – to do too much of something so that it becomes a problem
* At the office party, Sarah told a lot of jokes, but she went too far when she made a joke about the boss and made everyone feel uncomfortable.
libel – saying things that are not true and that hurt someone’s reputation; saying things that are not true and negatively influencing how other people think of that person
* Writing about rumors is dangerous. One of these days, someone is going to sue you for libel.
theme music – song that plays at the beginning of a television or radio show
* Whenever I hear that theme music, I know it’s time to watch my favorite show.
red state – a state whose citizens usually vote for candidates from the Republican Party; a state that is politically conservative
* Most people were surprised that she was elected in a red state despite her earlier comments about not believing in God.
blue state – a state whose citizens usually vote for candidates of the Democratic Party; a state that is politically liberal
* A law to put a special tax on unmarried mothers will never pass in a blue state like California.
What Insiders Know
Southern Writers and Southern Literature
When talking about American authors, people sometimes talk about “Southern writers” as a group. For the most part, Southern writers and Southern literature include writing about the American South, which is often “defined as” (described as) the states of South Carolina, Georgia, Alabama, North Carolina, Virginia, Tennessee, Mississippi, Louisiana, Texas, Oklahoma, Missouri, Maryland, Delaware, Kentucky, West Virginia and Arkansas.
However, Southern writing is not only defined by location. Southern authors also have “in common” (the same) certain “themes,” or topics, that appear in their writing. Many of these themes are an “outgrowth” (result) of the history that is shared by this region of the country.
One of the major themes relates to the history of “slavery,” when African Americans were owned by other Americans and forced to work without pay and without the right to make their own decisions. The American Civil War was fought “in large part” (mainly) to end slavery. Common among Southern states, then, include the “aftermath” of losing the war and the end of slavery as part of the Southern way of life and the effects on its economy.
Other common themes include the importance of family life and religion. Readers may also find in Southern literature the use of Southern dialects, which “mark” (show; signal) that someone is from that region of the United States. There are many Southern dialects – not just one, as is often “portrayed” (shown) in television shows and movies – and the “subtle” (small; difficult to hear) and not so subtle differences in dialect give readers a true “sense of place,” a feeling and understanding of the setting where the story takes place.