


= Sex.And.The.City s02-12
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../+ 美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

New York City restaurants are always looking +
for the next new angle to grab that elusive +
and somewhat jaded Manhattan palate. +
Last year it was fusion-Cajun. +
Last month it was mussels from Brussels, +
and tonight, it's S&M. +
Samantha's PR firm was hired to do the opening party +
for La Douleur Exquise, +
translation, The Exquisite Pain. +
Of course, we were all invited. +
See, this is what happens when the mayor shuts down the sex shops. +
Pops up in your cuisine. +
Hey, Stanford! +
Well, I know where I'm taking mother for dinner +
the next time she's in town. +
Oh, honey! +
Excuse me. +
Let her through! +
-Honey! -Hi! +
What are you wearing? +
The invitation said kinky. +
I kinked my hair. +
The ladies are inside, go have fun. +
Next! +
Excuse me. +
But when did wild sex come back in style? +
Oh, I think that was the weekend +
you spent at the Barney's warehouse sale. +
Three Cosmopolitans, a Diet Coke, +
and a vodka Martini with a twist. +
-I said olive. +
Bad waiter, bad waiter. +
What do you tip for that? +
Anyone else want a whack? +
How does he wait on tables dressed like that? +
It's humiliating. +
Well, the summer I worked at Howard Johnson's, +
I had to wear an orange hat. +
Don't be so judgmental! +
This is just a sexual expression. +
All these people have jobs and pay their bills. +
They're just having fun with fetishes. +
I wonder what your fetish is? +
Charlotte has a thing for Crabtree and Evelyn Potpourri. +
I don't have a fetish! +
Oh, we all have a fetish. +
The difference between us and them is, +
they're putting it out there where everyone can see. +
I think it's healthy and fabulous. +
Well, it's so lovely to see you all. +
And remember, ladies, +
whipping on the first date is considered forward. +
You sit your ass down, Mistress Carrie. +
-There are drinks present. -No can do. +
Big's flying to Paris tomorrow for business +
and I wanna say goodbye. +
Ooh, why not give him a goodbye he'll never forget? +
Sacre bleu! +
Go get him, girl. +
Woo! +
Well, laugh, it's a joke. +
Oh. +
Whoa, wait, wait. +
Not so fast, let me see. +
Oh, baby. +
I wasn't sure if it was the cap, the crop, or me, +
but it worked. +
Meanwhile, at a fetish across town, +
Stanford Blatch had a secret sex life. +
A very active secret sex life +
on the Internet as "Rick9Plus." +
It all started innocently enough +
as a goof on a lonely Friday night. +
But pretty soon he was logging in hours and hours +
on his favorite website. +
It was a comfort to know that others shared his underwear fetish, +
sometimes as many as 2,000 hits a day. +
No sooner had "Rick9Plus" entered the chat room +
that he got a message from his favorite on-screen pal, +
"Bigtool4U." +
Some fetishes can only flourish behind closed doors +
in the very late-night hours on a laptop. +
While others are right out in the broad daylight +
where everyone can see them. +
Charlotte, like every other normal woman in Manhattan, +
had a thing for shoes. +
Good morning. +
Beautiful shoes. +
Just got those in. +
-Oh... -Would you like to try them on? +
No, no, I'm just looking. +
I have way too many shoes as it is. +
Size seven? +
Uh-huh. +
Size seven. +
Oh, you are bad. +
Okay, I'm just trying them on. +
I can't even afford them. +
I'm saving for a summer share in the Hamptons. +
Beautiful. +
Look at that craftsmanship. +
Oh, I love them. +
How much? +
$400. +
No... +
can't. +
Please take it off before I start to cry. +
-$200. -Why? +
Shoes were meant to be loved. +
And you're gonna need a beautiful sandal like that +
in the Hamptons. +
Oh, thank you so much. +
Buster. +
Thank you, Buster. +
While one woman was uptown +
eyeing her artful new sandal, +
another was downtown eyeing +
The Life and Times of Isabella Stewart Gardner. +
Miranda was obsessed with reading historical biographies. +
In fact, she spent all last weekend in bed +
with Philip of Spain . +
Morning. +
Oh... +
that's very good. +
 +
The Parallel Lives of Two American Warriors. +
Stephen Ambrose, great writer. +
Yeah, I know. +
I just finished his Meriwether Lewis and Thomas Jefferson, +
Undaunted Courage. Yeah. +
-Amazing. -Oh. +
I'll pick that up right after I finish +
the New York Years. +
Jack. +
Miranda. +
And right after Miranda picked up Elizabeth I , +
by Jasper Riley, +
Jack picked up Miranda. +
Big and I stayed in bed all morning, +
which gave us just enough time for coffee +
and some last-minute details. +
I'm gonna miss you. +
Well, in a week I'll be back +
and you can sit there and watch as I unpack. +
There. I helped. +
Woo. +
Hey. +
Oh, before I forget. +
Charlotte wants to do a share in the Hamptons. +
So, are we thinking about doing something +
or should I go in on that? +
Don't think I can. +
Why, not a big fan of the $40 crab salad? +
Actually, there's a possibility +
I'm not gonna be here this summer. +
I may have to move to Paris for work. +
Just for a while. +
For how long a while? +
I don't know. +
Seven months, maybe a year. +
Nothing's definite. +
Wait. +
Wait, wait, wait, wait, wait. +
How long have you known about this? +
It's been in the works for a while. +
I'll know more details after this trip. +
Well, when did you plan on telling me? +
When I knew more, nothing's definite. +
I mean, don't get carried away. +
-There's the car. +
Look, I have to go or I'm gonna miss the plane. +
We'll figure this all out when I get back. +
I wanted to kill him. +
And he's standing there giving me +
the "What's the big problem?" eyes. +
You know, I don't understand you, like it's my problem. +
Okay, just calm down, there are ways to make this work. +
It's just seven months. +
And you can go visit him in Paris, +
-and he can come back here. -No, it's not about that. +
It's about the fact that I wasn't even a factor +
in his decision-making process. +
-Totally. -Men do this all the time. +
Women walk around thinking "we" +
and their version of "we" is "me and my dick." +
Totally. +
I mean, just tell me what's going on! +
Is that too much to ask? +
"Um... Carrie I'm thinking about going to France +
for the rest of my life!" +
-Am I right? -Totally. +
You know, one minute, he's all over me, +
and the next minute he's pushing me away. +
And I just-- I just cannot believe this is happening again! +
Yes, all right, calm down. +
There'll be no breaking of things. +
Why do I keep doing this to myself? +
I must be a masochist or something. +
That's when I first realized it. +
I was in an S&M relationship with Mr. Big. +
Excuse me. +
In love relationships, +
there is a fine line between pleasure and pain. +
In fact, it's a common belief +
that a relationship without pain +
is a relationship not worth having. +
To some, pain implies growth. +
But how do we know when the growing pains stop +
and the pain-pains take over? +
Are we masochists or optimists +
if we continue to walk that fine line? +
When it comes to relationships, +
how do you know when enough is enough? +
When you read The Complete War Memoirs of Charles de Gaulle , +
-get back to me. +
On Tuesday night, Miranda and Jack had dinner. +
In the biography of her life, +
this would go down as the best first date in history. +
This is kind of what I wanted to show you. +
Oh! +
Yeah, um... +
-Mark Twain lived here. -Mmm. +
Right around the time he wrote Huck Finn . +
Really? -Yeah. +
C'mon. +
It's private property. +
-I know, shh. -Shh. +
I'm gonna show you his little house. +
Right there, number 27. +
It's cute. +
Yeah. +
And just when Miranda thought she could read Jack perfectly, +
he opened an entire new chapter. +
No, no. +
Someone might come by, we could get caught. +
I know. +
A chapter entitled, +
I Like to Have Sex in Places I Can Get Caught. +
With my one man out of town in Paris, +
I found time to have drinks with my other man. +
I need your advice. +
But in order to get it, I have to confess something. +
And I'm asking you not to judge me. +
Who am I to judge anyone? +
I had bangs in the '80s. +
Okay. +
I have cybersex on the Internet. +
And this would be the non-judgment part? +
My name is "Rick9Plus." +
No, you didn't! +
"Rick9Plus," how sad is that? +
Actually, I think it shows a great deal of restraint. +
You could have been "Rick11." +
So I've been chatting with this guy, +
and we have a really great time. +
But now he wants to meet and I don't know if I should. +
Okay, let's figure this out. +
What do you know about him? +
His name is "Bigtool4U." +
My god. +
Come on, Carrie. +
This is serious. +
I'm sorry. +
I'm sorry, Rick. +
Okay. +
Where does he want to meet you? +
At an after-hours gay club +
in the Meatpacking District. +
Makes sense. +
Now tell me why you want to go. +
He seems hot, it's exciting. +
And I haven't had good sex +
since before Cats was on Broadway. +
I say go. +
Have a naughty little adventure. +
Be safe, have fun. +
What if he disses me? +
He said he's really great looking +
and has a really ripped body. +
Well Stanford, are you "Rick9Plus"? +
I'm so getting your point. +
After "Rick9Plus" went home, +
I decided I was just drunk enough to call Big. +
-Hello? -Hey, it's me. +
What are you doing? +
I'm in bed. +
I think it's called sleeping. +
Oh, so you're funny in France. +
It's 5:30 in the morning. +
-What is it? -I would like to know +
how you could even think of going to Paris +
and not even think about discussing it with me. +
Huh? +
I think about you all the time. +
What's he doing? What's he thinking? +
But you, no. +
When were you planning to tell me? +
Are you still there? +
Yes. +
Okay, well, because I think about you +
all the time. No, no, correction, correction. +
I think about us all the time. +
Can we get into this another time? +
I was sleeping. +
Oh, look, look, look, it's never a good time for you. +
You're always sleeping, or you're ready, +
or you're going, going, going. You're always going. +
You're fucking... "Taxi!" +
And you're on a plane to France for maybe a year. +
Well, you're a freakin' old man. +
You should be thinking about somebody else. +
This is not fake us. +
This is real. +
Even if you don't know it, it is. +
I am a woman. +
A wo-man! +
Have another cocktail, woman. +
No, no, no, this isn't about cocktails. +
This is about basic human decency. +
This is about taking responsibility. +
It's about being a grown-up. +
It's about being a man. +
I am a man. +
I'm a tired man. +
It's 5:30 in the morning here. +
Well, you know what? You better get used to it. +
Because if you move there, +
this is how our relationship is gonna be. +
You're gonna be sleeping when I'm eating, +
and I'm gonna be sleeping when-- +
shit. +
Shit. +
Hey. +
Are you still there? +
I'm going to bed. +
I have an important meeting at 9:00. +
Yeah, fine, hang up. +
But don't call me when I'm sleeping +
because I have a job here too, you know. +
Shit. +
Even through my cosmopolitan haze, +
I knew I had gone too far. +
Take off your panties. +
What? +
I want to give you head. +
In the cab? +
You're not serious, the driver is right there. +
Oh. +
Yes. +
Oh. +
Yes! +
Take 9th Avenue. +
A few days later, on the way home, +
Charlotte couldn't help but notice +
a gorgeous pair of Italian slingbacks in the window. +
I just came in to look. +
You have a very high arch. +
Are you a dancer? +
No. +
Such well-formed feet. +
Well, I was in Miss Debbie's twirlers when I was a little girl. +
They are so beautiful. +
For anyone else, $500. +
For you... free. +
What? No, Buster. +
Why would you do something like that? +
Because these beautiful feet are tired. +
And they need a little rub. +
When a shoe fetish meets a foot fetish, +
all reason goes out the shop window. +
Thank you. +
I am way overreacting to this whole France situation. +
I think Charlotte's right, there are-- there are ways to work this out. +
Mm-hmm. What made you change your mind? +
Well, I completely lost my shit to Big on the phone +
and I realized how close this whole thing is +
to really blowing up. +
And you know what? +
Yes, it's painful sometimes, +
but it's worth it, you know? +
I mean, the guy has to go there for work. +
And really, what is so awful about spending +
a week here and there with your boyfriend in Paris? +
Nothing, it's so romantic. +
Great, your love life takes you to Paris, +
and I'm fucking in the back of a cab. +
That's lovely. +
And not just there. +
We've done it in the bathroom at Bond Street. +
Ew, I just ate there! +
The elevator at the Marriott Marquis +
and a public restroom in Central Park. +
How very "George Michael" of you. +
We've actually never done it lying down, +
or inside, for that matter. +
Miranda, this is supposed to be a relationship, +
not Outward Bound . +
You've got to get this guy in a bedroom +
and find out what's really there. +
I'm a little afraid to try. +
He likes the threat of getting caught. +
What if being with just me isn't enough? +
Excuse me, Miss Charlotte, +
what is happening south of your ankles? +
Oh, they're new, do you like them? +
Oh, I love them! $500? +
Oh, no, not that much. +
The guy kind of gave me a deal. +
How much? +
Um... free. +
-Why? -And where is he? +
Well, he just, he really wanted me to have them. +
I mean, he just really loves it when people love shoes. +
Sweetie, this is New York City. +
Nobody loves anything that much. +
Well, I let him hold my feet, +
just a little. +
The second she said it out loud, +
she knew what she had to do. +
Hello, again. +
I can't keep these shoes you gave me. +
Why? +
You know why. +
You've already worn them, I can't take them back. +
Keep 'em. +
No, thank you! +
Then I'll throw them in the garbage. +
No, no, no, they're too beautiful. +
I'd buy them, but I can't afford it. +
What about a trade? +
Six new styles just came in. +
I've never seen them on a foot. +
Charlotte looked down at the exquisite shoes. +
The smell of leather was intoxicating. +
And all I have to do is try the shoes on? +
Charlotte felt like Cinderella... +
Cinderella in a dirty, kinky, freaked out, storybook parallel universe. +
Thank you. +
Big arrived on the 9:00 p.m. flight. +
I was at his door by 10:00 to welcome him home in style. +
Bonjour, voilà, le French hat , +
voilà, le french fry . +
And it doesn't stop there. +
I have le Big Mac, +
and le Filet-De-Fish. +
What is all this? +
It's an apology for being le bitch. +
Now, I've been thinking about this. +
We can make this work. +
We can, you know, we'll do le phone sex. +
And if things get really bad +
then I'll move to Paris for a while +
and write Le Sex and Le City . +
That would be great. +
Which one? +
I don't care. +
But you'd be moving to Paris for yourself, right? +
I mean, don't move for me. +
Well, why would I move to Paris if it wasn't for you? +
No, I'm just saying, +
I don't want you to uproot your life and expect anything. +
I am such an idiot! +
What the fuck? +
I'm running around town in a beret, +
buying your greasy food +
and you don't even care if I'm in your life! +
Would you calm down? +
No, you know what? I am so tired of calming down! +
Look, I have to be in a relationship +
where if I have to go to Paris, +
I have to go to Paris. +
Fine, go to Paris +
and then what happens to us next year +
when you decide you just have to go to Brazil? +
This isn't about us. +
This is about work! +
No, this isn't about work. +
This is about us getting closer, +
and you getting so freaked out +
that you have to put an ocean between us. +
I don't want to talk about this anymore. +
Why is it so hard... +
for you to factor me into your life in any real way? +
I guess old habits die hard. +
Well, maybe I can't do this anymore. +
I understand. +
Yeah, I bet you do. +
You said you loved me. +
I do. +
Then why does it hurt so fucking much? +
On the way home, I was furious. +
Not with Big, with myself. +
I was the real sadist. +
He might be the one with the whip, +
but I was the one who tied myself up. +
Tied myself to a man who was terrified of being tied down. +
And downtown in the Meatpacking District, +
another terrified man was preparing to face his fears. +
Take 'em off. +
Excuse me? +
Stanford panicked. +
He hadn't been seen in his underwear +
by a roomful of men since 7th grade gym class. +
What's it gonna be, pal? In or out? +
So, "Rick9Plus" undressed. +
It would have been rude to stand up "Bigtool4U." +
To her surprise, Miranda had no trouble +
getting Jack to agree to make love in his bedroom that night. +
Let's do it in bed. +
Suddenly, her fear of his fetish ended. +
Miranda realized that Jack's excitement +
wasn't about getting caught, it was about her. +
And she really began to let loose, +
something she'd been unable to do outside. +
Oh! Oh! +
Jack? +
Is everything all right? +
Who was that? +
It's my mother. +
My parents are visiting. +
Son? +
They sound like they're coming in here. +
Are they coming in here? +
Yeah. +
♪ The funk soul brother Right about now ♪ +
♪ The funk soul brother Check it out now ♪ +
♪ The funk soul brother Right about now ♪ +
♪ 'Bout now, 'bout now ♪ +
At first, Stanford thought he'd be shunned +
for lack of the popular six-pack abs. +
But then... +
Never seen that kind before. +
They're French! +
I bought them in Paris. +
Turn around. +
Stanford Blatch had never felt more special. +
Nice. +
"Bigtool4U"? +
Excuse me? +
Another beer for you? +
Yeah! +
I'll buy. +
Stanford learned that sometimes a brief encounter +
can be quite fulfilling. +
I went to bed at 1:00. +
I was still wide awake at 2:30. +
There were no words left. +
We'd said them all. +
After we made love, I knew it was over. +
Did I ever really love Big? +
Or was I addicted to the pain? +
The exquisite pain of wanting someone so unattainable. +
Hey. +
What are you doing over there? +
Go to Paris. +
I'm not gonna come. +
Let's not pretend we're something we're not. +
It's okay. +
Come to bed. +
I wanted to go to him. +
But I felt like I was tied to the chair. +
Some part of me was holding me back, +
knowing I had gone too far, reached my limit. +
And just like that, +
I had untied myself from Mr. Big. +
I was free. +
But there was nothing exquisite about it. +
欲望城市 +
（两性专家凯莉布雷萧） +
，强烈痛苦 +
纽约的餐厅总试图寻求新卖点 +
为了吸引善变的曼哈顿民众 +
去年是推出纽奥良肯犹美食 上个月是布鲁塞尔的河蚌 +
今晚则是性虐待秀 +
莎曼珊的公关公司负责 +
为这家餐厅筹划开幕派对 +
这家餐厅叫做：强烈痛苦 +
我们全都被邀请了 +
市长勒令情趣商店停业 +
但它却突然出现在餐厅里 +
史丹佛 +
我知道下次该带我妈 到哪里吃饭了 +
-亲爱的 -借过 +
让她过来 +
你穿的是什么？ 邀请函上写了是变态派对 +
我缠卷了头发 +
姐妹们都在里面 去吧，好好玩，下一个 +
何时狂野性爱又开始流行？ +
巴尼百货清仓拍卖 你去血拼的那个周末 +
三杯四海为家、一杯健怡可乐 跟一杯摇匀的伏特加马丁尼 +
我要的是橄榄 +
差劲服务生… +
-你干嘛这样打他？ -有没有人想玩玩？ +
那个服务生怎么穿成那样？ 真丢脸 +
霍华强森冰淇淋的服务生 也规定要戴橘色帽子 +
别如此评判他人 这只是一种性的表现方式 +
这些人有工作，不偷也不抢 +
他们只是在享受恋物癖的乐趣 +
不知道你的癖好是什么？ +
夏绿蒂对香薰罐有恋物癖 +
-我才没有恋物癖 -每个人都有恋物癖 +
只是他们把癖好展现出来 让大家都看到 +
我认为这样很好又很健康 +
很高兴见到你们 小姐们，要记住 +
别第一次约会就玩性虐待 那太过激烈了 +
坐下来，饮料还没喝完 +
大人物明天要去巴黎 我想去跟他道别 +
何不送他一个难忘的道别？ +
-糟透了 -把他弄到手来 +
快笑，这是个玩笑 +
等等…别急着脱，让我看看 +
宝贝 +
宝贝 +
我不确定是因为那顶帽子 还是马鞭，或是我 +
但却奏效了 +
在恋物癖弥漫全市的同时 史丹佛进行着秘密性生活 +
他化名午夜干柴在网路上 进行非常活跃的秘密性生活 +
起初只是在孤独的周五夜晚 犯下的一个不经意错误 +
但很快地他便时常花时间 上他最爱的网站 +
他很高兴知道有其他人 能分享他的恋内裤癖 +
有时网站参观人数 一天多达两千 +
不久后，午夜干柴 开始进聊天室聊天 +
他收到他最喜欢的网友 大玩意的讯息 +
某些恋物癖 只会在午夜的门后发酵 +
然而有某些则在 人人都看得见的大白天发作 +
夏绿蒂和其他曼哈顿女人 对鞋子有狂热 +
-早安 -早安，好漂亮的鞋子 +
是新款，要不要试试？ +
不了，我只是看看 我的鞋太多了 +
你穿七号？ +
这是七号鞋 +
你真坏 +
我只要试试就好 +
我买不起，我在存钱去汉普顿 +
好漂亮，看看它的手工 +
我好喜欢 +
-多少钱？ -四百元 +
不行，请在我哭之前 把它脱下来 +
两百元 +
-为什么？ -鞋子该被喜爱的人珍惜 +
你去汉普顿 会需要这样一双凉鞋 +
谢谢你 +
-我叫巴斯特 -谢谢你，巴斯特 +
当一个女人在这头 审视她的美丽新凉鞋 +
另一个女人正在城里 注意新恋情的对象 +
“伊莎贝拉史都华贾德纳所著 生命与时代” +
米兰达喜爱读历史传记 +
其实她上个周末 都在读西班牙王菲利浦的传记 +
-早安 -那本书很不错 +
“疯马与卡士达 两名美国战士的人生” +
史蒂芬安伯斯是个很棒的作家 +
我知道，我刚读完他的… +
“路易斯与汤玛士 无畏的胆量” +
真是太棒了 +
等读完“罗斯福的纽约时代” 我打算看那本 +
-我是杰克 -我是米兰达 +
当米兰达读完 琼斯里莱的“伊莉沙白一世” +
杰克也把上了米兰达 +
大人物和我整个早上 都待在床上 +
我们有时间一起喝咖啡 交代一些剩余的琐事 +
我会很想你 +
我一周内就会回来 到时候你可以看我整理行李 +
我帮了你忙 +
对了，夏绿蒂计划去汉普顿 +
-我们怎么样？要一起去吗？ -我想我不行 +
为什么？ 不喜欢吃螃蟹沙拉吗？ +
我今年夏天可能不会在这里 +
我可能得为了工作 搬去巴黎一阵子 +
-一阵子是多久？ -我不知道 +
七个月或是一年，还不确定 +
等一下，等等… +
你知道这件事多久了？ +
已经筹划一阵子 这次出差回来会知道更多细节 +
你打算什么时候告诉我？ +
等我知道更多细节 还不确定，你别激动 +
车子在等 我得走了否则会赶不上飞机 +
这件事等我回来再谈 +
我真想杀了他 +
他的眼神就是一副 “有什么大不了”的样子 +
好像这是我的问题 +
冷静点，总有办法可以解决 +
你可以去巴黎看他 +
不全是这样 他甚至都没考虑到我 +
男人总是这样 女人想的是“我们” +
但他们的“我们” 只是“我和我的小弟弟” +
为什么会这样？ 这样的要求过分吗？ +
“凯莉 我想我之后要定居法国” +
我有说错吗？ +
这一分钟还绕着我打转 下一分钟就急着把我推走 +
我不敢相信又发生这种事 +
别激动，事情不会那么糟 +
我为何要这样折磨自己？ +
我一定有被虐狂 +
那是我第一次体认到 +
我和大人物的关系 就像是性虐待 +
在爱情里 快乐与痛苦只有一线之隔 +
有些人相信没有痛苦的爱情 +
便不值得拥有 +
对某些人而言，痛苦代表成长 +
但何时成长的痛苦 会转变成疼痛的痛苦？ +
若我们继续走在那条线上 我们是被虐狂或只是乐观？ +
谈到爱情 +
如何知道是真的够了？ +
等你读完戴高乐的战争回忆录 +
再回来找我 +
星期二晚上 米兰达和杰克共进晚餐 +
在她生平传记中 这是最美好的一次约会 +
这就是我想让你看的 +
没错 +
马克吐温曾住在这里 大约是他写哈克系列故事时 +
是吗？ +
来吧 +
-这是私人住宅 -我知道 +
我想带你看他的房子 +
就在那里，二十七号 +
很不错 +
正当米兰达以为 她能完全读透杰克 +
他又开展了一个新的章节 +
不要…可能会有人经过 我们会被看到 +
我知道 +
这个章节叫做 +
“我喜欢在 可能被看到的地方做爱” +
我的男人去了巴黎 所以我能和另一个男人喝酒 +
我需要你的意见 +
我要向你坦白一些事 希望你不要评判我 +
我有什么资格评判人？ 我一点影响力也没有 +
我在体验网路性爱 +
这是不要我评判的部分吗？ +
-我的化名是午夜干柴 -不会吧 +
午夜干柴，是不是很可悲？ +
这表现出你的压抑 你甚至可以是午夜烈火 +
我跟某个家伙聊得很愉快 +
但是现在他想要见面 我不知道该不该答应 +
让我问你，你对他了解多少？ +
他叫做大玩意 +
拜托，凯莉，我是认真的 +
对不起…干柴 +
他想约在哪里？ +
密派区的同性恋酒吧 +
蛮吸引人的 告诉我你为什么想去 +
他似乎很辣，让人兴奋 +
“猫”在百老汇上演后 我就没有过很棒的性爱 +
那就去，来个顽皮的小冒险 做好安全措施，好好玩 +
要是他不喜欢我呢？ +
他说他长得很帅，身材又好 +
你不是午夜干柴吗？ +
我了解你的意思了 +
午夜干柴回家后 +
我想我喝醉了 所以打电话给大人物 +
是我，你在做什么？ +
我在床上 +
-简单说就是在睡觉 -在法国玩得愉快吗？ +
现在是清晨五点半 你有什么事？ +
我想知道为何你要去巴黎 +
却没想过要跟我讨论？ +
我无时无刻不在想你 +
“他在做什么？想什么？” 但你却不是 +
你打算什么时候告诉我？ 你有在听吗？ +
有 +
因为我想的都是你 +
更正…我想的都是我们 +
我们能不能改天再谈？ 我在睡觉 +
什么时间对你来说都不适合 你总在睡觉或离开 +
你总是离开 叫部计程车，就搭机去了法国 +
你年纪不小了 该多为别人想想 +
我没有骗你，我总是在想我们 +
就算你不知道，但这是真的 +
我是个女人，一个女…人 +
再喝杯酒吧，女人 +
这跟酒无关 这是关系到基本作为 +
有关责任感，你该当个成人 +
-有关如何当个男人 -我是男人，一个疲倦的男人 +
现在这里是清晨五点半 +
你最好开始习惯 +
因为要是你搬去那里 我们就必须如此 +
你在睡觉时我在吃饭，可恶 +
你有在听吗？ +
我要睡觉了 九点钟有个重要会议 +
你可以挂电话 但别在我睡觉时打来 +
因为我在这里也有工作 +
虽然我是有点醉了 但我知道我做得太过头 +
把你的内裤脱掉 +
什么？ +
-我想让你享受一下 -在计程车上？ +
司机会看到 +
对，走第九大道 +
几天后，在回家的路上 +
夏绿蒂在橱窗发现一双 很漂亮的意大利露跟鞋 +
我只是进来看看 +
你的足背很高 你是个舞者吗？ +
-不是 -真是双漂亮的脚 +
我小时候参加过乐队指挥团 +
这双鞋真漂亮 +
我卖其他人五百 +
你，免费 +
什么？不，巴斯特 你为什么要这样？ +
因为这双美丽的脚累了 它们需要按摩 +
当一个恋鞋狂遇上一个恋脚狂 +
橱窗内从此没有理智存在 +
对于去法国的事 我是反应过度了 +
夏绿蒂说的对 总有解决的办法 +
是什么让你改变想法？ +
我和大人物讲电话时完全失控 +
我发现我们之间可能就快完了 +
没错，有时会痛苦 但这是值得的 +
他必须去那里工作 +
花一个星期与男友在巴黎相聚 没什么可怕的 +
没什么，这很浪漫 +
你的爱情带你去巴黎 我则是在计程车后座做爱 +
-那很棒 -不只是那里 +
还有庞德餐厅的洗手间 +
我才刚去那里吃饭 +
马里欧特玛库斯饭店的电梯里 及中央公园的公共厕所 +
乔治麦可也输给你 +
我们从没躺着或在家里做过 +
你们是在谈恋爱 可不是“外展训练” +
把他弄进房间搞清楚是哪回事 +
我想我没办法 他喜欢害怕被抓到的快感 +
要是他觉得 我无法满足他怎么办？ +
夏绿蒂小姐 你的脚是怎么回事？ +
-这是新鞋，喜欢吗？ -好漂亮，五百元吗？ +
没那么多，店员给了我折扣 +
-那是多少？ -免费 +
-为什么？ -是哪一家店？ +
他希望我能拥有这双鞋 +
他希望鞋子能被好好珍惜 +
这里是纽约，没人会这么想 +
我让他摸了我的脚一会儿 +
在她说出来的那一刻 她便了解该怎么做 +
-又见面了 -我不能收这双鞋 +
-为什么？ -你知道为什么 +
你穿过了不能退，留着吧 +
-不，谢谢你 -那我丢到垃圾桶 +
不，它们太漂亮了 我想买但是付不起 +
来笔交易如何？ +
有六双新鞋刚到 我想找人试穿 +
夏绿蒂看了看那些美丽的鞋子 +
皮革的味道让人兴奋 +
只是要我试穿吗？ +
夏绿蒂感觉自己像是灰姑娘 +
身处在肮脏、变态 及疯狂世界里的灰姑娘 +
谢谢 +
大人物的飞机九点抵达 +
我十点便以法式风情装扮 到他门口欢迎他回家 +
欢迎回来，法国帽和炸薯条 +
不只如此 +
还有麦香堡和麦香鱼 +
-为什么要这样？ -为我脾气差道歉 +
我好好想过，没什么行不通的 +
我们可以享受电话性爱 +
如果还是有问题 +
我就搬到巴黎一阵子 写法国人的“欲望城市” +
-这样最好 -你要哪一个？ +
我都可以 +
你是为了自己才搬到巴黎吧？ +
别为了我搬 +
不为了你，我干嘛搬到巴黎？ +
我只是不希望你 因为如此而有所期待 +
-我真是个笨蛋 -又怎么了？ +
我带着贝雷帽到处跑 还帮你买油腻腻的食物 +
你根本不在乎生活里有没有我 +
-你冷静下来好吗？ -我不想再冷静 +
听着，即使我在谈恋爱 +
若我得去巴黎，我就会去 +
很好，你就去巴黎 +
要是明年你又要去巴西 我们该怎么办？ +
重点不是我们，这是工作 +
重点不是工作 而是我们越来越亲密 +
你就发疯似的，想逃得远远的 +
我不想再谈这个 +
为什么会这么难？ +
为何你不愿认真考虑 将我纳入你的生活？ +
我想我还没做好准备 +
-也许我应该离开你 -我了解 +
我相信你是 +
-你说过你爱我 -我是爱你 +
那为何又伤我这么深？ +
在回家的路上，我气疯了 不是对大人物，是对我自己 +
我是个真正的被虐狂 +
他手上或许握着鞭子 但我却是自缚的人 +
我将自己绑在一个 害怕被绑住的男人身上 +
在密派区 +
另一个害怕的男人 正准备面对他的恐惧 +
-把衣服脱掉 -你说什么？ +
（限着内裤进入） +
史丹佛感到惊慌 +
自从七年级的健身课后 他就没在他人面前裸露过 +
小子，决定如何？ 脱衣服还是出去？ +
所以午夜干柴选择了脱衣服 +
让大玩意白等会很失礼 +
出乎意料之外 +
米兰达说服了杰克 到他房间做爱 +
我们到床上做 +
突然间 她对他恋物癖的恐惧消失了 +
米兰达了解到 杰克真的是因为她而感到兴奋 +
她开始解放自己 做些她不敢在外面有的举动 +
杰克，发生什么事吗？ +
-那是谁？ -是我妈 +
我父母过来看我 +
他们好像要进来了 +
史丹佛起初以为 他会因为没有六块肌受到排挤 +
但是… +
我没见过这种样式的 +
这是法国货，我在巴黎买的 +
转过来看看 +
史丹佛巴勒奇 从未感到如此特别过 +
很不错 +
-大玩意吗？ -你说什么？ +
我说再来一瓶啤酒吗？ +
我请客 +
史丹佛发现 有时一个简单的招呼 +
就能达到目的 +
我在一点钟上床 但两点半时还未入睡 +
我们没有再说些什么 因为都已经说完了 +
做完爱后，我知道我们结束了 +
我真的爱大人物吗？ 或我只是对痛苦上瘾？ +
对捉不住的男人的欲望 所带来的强烈痛苦 +
你坐在那里想什么？ +
去巴黎吧 +
我不会跟着你去 +
我们别再假装下去 +
没关系 +
过来床上 +
我想跟他一起去 但我像是被绑在椅子上 +
有某部分的我将我往回拉 +
我知道我已走得太过头 碰到了我的极限 +
因此我将自己 从大人物身上释放 +
我自由了，但却不感到兴奋 +
