


= Sex.And.The.City s02-05
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../+ 美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

There are only two times when it's appropriate +
to wear the little, black dress in daylight. +
One involves leaving a party way too late. +
The other involves leaving the party way too early. +
The New York funeral. +
Javier was a hot Cuban designer +
and the toast of the New York fashion elite. +
He was also a good friend. +
I had known him since he was Harvey. +
Javier loved clothes. +
Unfortunately, he loved heroin more. +
Shit. +
Okay. +
Wow, look at you. +
You like? +
Well, isn't it a little wrong +
to wear a dead man's design to his own funeral? +
It's wrong not to. +
Besides, at two thousand for the outfit, +
I better get some wear out of it. +
Two thousand? You're kidding! +
Marked up 30 percent since yesterday. +
See, that's the thing about New York. +
You're always more popular when you're not around. +
Carrie, I have to look fabulous. +
Everyone is gonna be there. +
Reminder, honey, +
this is a funeral, +
not Friday night at Bond Street. +
That's your grief talking, honey, get your purse, let's go. +
Hey, sorry I'm late. +
Is everyone in town invited to this? +
Well, Carrie invited me. +
-You got invited with a guest? -Well... +
We were supposed to see the Magritte show together. +
That dress is really inappropriate. +
Apparently, Charlotte and I were the inappropriate ones. +
There it was, +
Javier's entire new spring line. +
It was his best show ever. +
Everyone's wearing a Javier. +
Told you. +
Lend me your hat, please? +
Fine. +
But if anyone asks, it was a gift from the designer. +
Christ, my heels keep getting stuck. +
-So much for death with dignity. -Yeah. +
Oh... +
Hello. +
Buenos dias. +
Look at the number they did on Josephina. +
She is beautiful. +
She wasn't a week ago. +
Josephina was Javier's sister +
and heir apparent to the Javier industry. +
In a day, she had gone from ugly duckling +
to Donatella Versace. +
Death definitely became her. +
You're smoking at a funeral? +
Javier would have wanted it that way. +
We are asking today... +
that in Javier's memory, +
all donations be made to Javier House, +
a home we are building to house those in the fashion industry +
who suffer from... +
substance abuse. +
No, don't. +
-No? -No. +
I'm gonna help them raise money. +
That's unusually nice of you. +
Forget nice, the mailing list will be priceless +
and I'll have every unlisted 212 number in Manhattan. +
You had to give Samantha credit. +
She always saw the positive. +
One man's death was another woman's P. R. opportunity. +
Josephina, I'm Samantha Jones, +
from Samantha Jones Public Relations. +
I was so touched by your speech, that I wanted to... +
Oh! +
Oh... +
I'm sorry. +
It's nothing to lose your hat over. +
She loved hats. +
It's, uh... +
fitting, really. +
Your mother? +
My wife. +
Oh, I'm so sorry. +
It's okay. +
Thanks. +
Kids? +
Nope. +
It's just a drink. +
He works on the same block as my gallery. +
You picked up a man at a cemetery? +
He's really handsome and he went to Princeton. +
The widower thing is a definite no-no. +
-Why? -The dead wife factor. +
It doesn't matter how much of a bitch she was alive. +
Now she's dead, and you're the bitch +
who can't live up to her. +
You shouldn't talk about his wife like that. +
See? Happening already. +
It's not his fault she died! +
And, besides, I think that going through something like that +
makes him more sensitive. +
I mean, he's felt really deeply. +
He's in touch with his emotions. +
It's kind of romantic. +
And, think about it. +
He's been married. +
I mean, it shows he can commit. +
Then date a divorced guy. +
They've committed and everyone's still alive. +
It didn't work for Big. All that marriage did +
was convince him he hated committing. +
Carrie, you broke up with him. +
Oh, so I'm the one with the commitment problem? +
Well, I'm just saying. +
While we were watching them break ground on Javier's last location, +
Miranda was breaking new ground of her own. +
So... It's just you? +
Yep. +
-Just me. +
Such a big apartment to buy for just you. +
I have a lot of shoes. +
Maybe the boyfriend will move in? +
No, no boyfriend. +
Just me. +
I have a son who owns his own business. +
No, thanks. +
I'll take it. +
And with that, Ms. Miranda Hobbes Esquire, +
a.k.a. "just me," +
bought herself her first apartment +
and promptly took herself out for a drink. +
While Miranda was out celebrating her future, +
I was in contemplating my own. +
In a city that moves so fast, +
they give you the Sunday paper on Saturday, +
how did any of us know how much time we had left? +
There was so much I hadn't done. I'd never been to Greece, +
I hadn't finished painting my bathroom... +
My Visa bill still wasn't paid in full. +
Hell, sometimes I felt like I was barely living. +
Hello. +
Hey . +
Hey. +
It's just me. +
So, uh... How are you? +
Just got back from a funeral. +
Oh, and you thought of me, I'm flattered. +
Listen, uh... +
Do you want to have dinner sometime? +
I'd like to have dinner any old time. +
Who am I having dinner with? +
Me. +
Oh, um, you know, in that case, I better check my book. +
-I'm hanging up now. Fine. +
Saturday, eight o'clock, Roberto's. +
Be there or be square. +
God, you're old. +
It was so easy. +
Just like that, I had made a Saturday night date with Big. +
In under 30 seconds, we had resuscitated a relationship +
that had taken six months to die. +
The next day, Samantha set out to break some records of her own. +
You know, I rarely make personal contributions. +
We'd love to have you on the Javier House Board. +
Maybe, in this case, you can make an exception? +
I'll tell you what's exceptional. +
Getting solicited by a woman as beautiful as you. +
Richard Cranwell, senior partner at Bear Stearns. +
Philanthropist, playboy. +
His specialty was hostile takeovers. +
Flattery will get you everywhere, Mr. Cranwell. +
Please. Call me Dick. +
Dick. +
In Samantha's case, +
it was more like a friendly merger. +
Perhaps we could discuss Javier House over dinner sometime. +
I believe that could be arranged. +
Samantha groped Dick Cranwell +
for the good of all strung out designers everywhere. +
Unfortunately, she was not expecting Sandy Cranwell +
back early from groping a sweater set at Bendel's. +
Get out. +
I'll just leave the proposal. +
I... +
Apparently, Sandy was not feeling +
as charitable as her husband. +
Meanwhile, at her mortgage company across town, +
Miranda was having her own troubles closing the deal. +
So it's just you. +
Yeah, just me. +
Check the "single woman" box. +
And initial. +
And the down payment is coming from your father? +
No. +
Just me. +
And check the "single woman" box. +
In the course of one hour, +
Miranda had checked more single woman's boxes +
than her gynecologist. +
I'm telling you, if I was a single man +
none of this would be happening. +
If you were a single man, I'd date you. +
I've got the money, I've got a great job, +
and I still get, "It's just you?" +
No, they're threatened. +
Buying a place alone means you don't need a man. +
-I don't. -Everyone needs a man. +
That's why I rent. +
If you own and he still rents, +
then the power structure is all off. +
It's emasculating. +
Men don't want a woman who's too self-sufficient. +
I'm sorry, did someone just order a Victorian, straight up? +
I'm sorry, Miss Jones, your card's not accepted. +
That's not possible, try it again. +
Maybe I'm not making myself clear. +
Your card, and you, are not accepted here. +
Samantha had messed with the wrong woman. +
Sandy Cranwell practically owned Manhattan +
and she wanted Samantha off it. +
Come on, let's go. +
Sandy Cranwell had done what any well-heeled +
she took out a social hit on Samantha. +
In 12 hours, Sam had gone from A-list to blacklist. +
The next night, Charlotte met Ned, the widower, for drinks. +
This was fun. +
Maybe we can meet for a real meal next time. +
I'd like that. +
They talked about architecture, +
art, the Ivy league. +
The ex-wife wasn't even in the picture... +
Is this her? +
Until the ex-wife's picture showed up. +
Yeah. +
She's so pretty. +
Let's get out of here, okay? +
Oh, I'm sorry. +
That was really thoughtless of me, I... +
I know this must be hard for you. +
It's just a little weird talking about her on a date. +
I understand. +
It's a beautiful night. +
Ned. +
Ned, are you okay? +
I'm sorry. +
It's just-- +
Seeing Liz's picture and... +
thinking about her, just... +
Oh, God! +
I'm sorry. +
Here, here. +
Ordinarily, Charlotte hated when men cried. +
But on Ned, it only made him more romantic. +
Oh... +
Wow. +
It's so embarrassing. +
I'm just... +
feeling so much right now. +
Those were magic words to Charlotte's ears. +
It's okay. +
You just take as much time as you need. +
Okay? +
It's okay. +
Aw... +
Apparently all the time Ned needed was 45 minutes. +
That night, under the watchful eyes of a dead woman, +
Ned came back to life... +
Twice. +
One word... +
Rebound. +
It's not a rebound when the other person's dead. +
She has a point. +
He's moving on, I'm helping him to get over his wife. +
This guy has project written all over him. +
That's not fair. +
So how was the sex? +
Ah! Amazing. +
It was like Liz was just looking over us, +
giving us her blessing. +
A threesome in absentia. +
I mean, my hat blew right into her headstone. +
She was clearly sending a message. +
Yeah, don't fuck my husband, you hat-loving bitch. +
He invited me to a memorial service at her grave next week. +
That is huge. +
Excuse me, but when did cemeteries get so happening? +
It's a sign that he's ready to move on. +
And he's ready to do it with me. +
So you're saying you fucked him back to life? +
In a way, yes. +
Man, you're good. +
That night, I had my date with Big. +
I was feeling everything, +
fear, happiness, dread. +
Was I ready to jump back into a life with Big in it? +
Was seeing him again a huge mistake? +
And if it was, +
why was I so excited? +
I had never felt so confused. +
Was Charlotte right? +
In a world where everyone's dying to make a connection, +
can a relationship bring you back to life? +
I never really thought about it. +
Oh, come on, everybody wonders what happens after you die. +
I'm too busy wondering who's dinging my car in the garage. +
Well, I think we reincarnate. +
Ah! Well, that's the easy way out. +
What are you gonna come back as? +
Someone who knows better. +
You smell nice. +
I'm serious. +
Do you believe in heaven? +
Oh, yeah. +
Really? +
What's your idea of heaven? +
A big bed. +
And they just say, +
"Come on in." +
Your idea of heaven is a bed? +
It depends on who's in it. +
I'm not sleeping with you tonight. +
I thought we were just having dinner. +
We are. +
A half hour later, and I was back at Big's, +
the site of so many past little deaths. +
It felt great and weird and... +
wrong. +
-We can't do this. -Yes, we can. +
Not like this. +
You're right, let's go inside. +
No... +
I have to go, I have to go. +
I didn't know what had happened, +
but suddenly getting back together with Big +
seemed like a very bad idea. +
I was scared to death. +
The first time I got involved with Big, +
I got out just in time. +
Would I be as lucky the second? +
Across town, Samantha was facing her own uncertain future. +
Check it again, Samantha Jones. +
Sorry. +
The first time, she thought it was +
an unfortunate oversight. +
The second time was just unfortunate. +
I'm sorry, we're all full. +
I'll wait for a table. +
Don't bother. +
By the third time Samantha was turned away, +
it had all become clear. +
She was deader in this town than Javier. +
Por favor , Teddy, take her out of here. +
The next day, Miranda met her new neighbor. +
Hello! +
Are you my new neighbor? +
Yeah, hi, I'm Miranda Hobbes. Nice to meet you. +
I haven't actually moved in yet. +
I'm just here taking some measurements. +
Well, I'm so glad to have a young person moving in. +
Brings a little life to the place. +
Ruthie kept pretty much to herself. +
Never married. +
Uh-huh. +
She died in there, you know. +
She did? +
Oh, yes. +
It was a week before anyone realized she'd passed. +
Rumor has it, the cat ate half her face. +
So... Just you? +
That night, Miranda had another disconcerting experience. +
Halfway through her Three Delicacy Delight, +
a delicacy got stuck. +
After Miranda was done saving her own life, +
she called someone who could commiserate. +
Unfortunately, I was deep into screening mode. +
Big had called twice and I didn't know what I wanted to say to him. +
Oh my God, +
I just choked! +
I just almost died and you're not... +
Hey, sweetie, you alright? +
I was watching Hard Copy . +
And I kept thinking, when they found me, +
I would forever be the dead girl who watched bad TV. +
Well, why didn't you call me? +
I couldn't breathe! +
I'm gonna die alone, Carrie. +
No, you are not. Do you want me to come over? +
No, I'm okay. +
I'll call you tomorrow. +
The fact was, Miranda was not okay. +
She went to bed hungry and locked the cat in the kitchen for two days. +
After a week of being a social pariah, +
Samantha realized if she ever wanted to get her life back, +
she would have to beg for it. +
the godfather. +
Samantha Jones. +
The name sounds familiar. +
Shippy Shipman was the queen of the ladies who lunch. +
And was personally responsible for the demise +
of at least 70 social lives. +
You might know me from my work with the Javier House Foundation? +
No, that's not it. +
-No? -I believe you were the whore +
who once groped my husband at a Whitney benefit. +
It was bad. +
Not only was Samantha dying, +
but her entire sex life was flashing before her. +
Maybe... +
I don't really remember. +
I do. +
Eh... You're good friends with Sandy Cranwell? +
Yes, we go back to Chapin. +
Could you maybe talk to her for me? +
I think you've made your own bed and you need to lie in it. +
And you're good at that, aren't you... +
Samantha? +
Look, what do you want me to say, Shippy? +
That I'm a whore? +
That I've slept with every man in New York and some in Brooklyn? +
All right, maybe I have. +
Is that what it's gonna take? +
Okay, I'm a big whore. +
Now... Will you help me? +
I don't think so. +
Fine. +
And I only groped your husband's flat preppy ass at that benefit +
because I was drunk. +
I'll see myself out. +
The next day, Miranda decided to check out her new neighborhood. +
But suddenly she was the one checking out. +
That was the peculiar thing about New York, +
you never knew if a cab was going to save you or kill you. +
Columbia Presbyterian Hospital, please. +
Or both. +
Well, that was freaky. +
I felt like I was drowning and dying at the same time. +
Sweetie, they said you had a panic attack. +
Yeah, and I had to pay 500 dollars +
of my single person's salary to find that out. +
What's wrong? +
Take a good look at my face, because at my funeral... +
there'll only be half of it. +
I'll be dead and my cat will be happy, and... +
Charlotte will be picking up men at the next gravesite over. +
Breathe, sweetie, breathe, breathe. +
I'm all alone, Carrie. +
The first people on my "call in case of emergency" list +
are my parents. +
And I don't like them. +
And they live in Pennsylvania. +
Oh, sweetie, you can put me on there. +
I can't! +
You screen! +
Well, I'll pick up. +
I promise. +
Listen... +
You did the right thing buying that apartment. +
-You love it, right? -Yeah. +
And you won't be alone forever. +
The truth was, I didn't know if any of us would end up alone. +
But I did know Miranda couldn't afford another panic attack. +
Meanwhile, over in Queens, +
Charlotte was about to get a surprise of her own. +
You brought lilies. +
You said they were her favorite. +
Please tell me those are your sisters. +
I don't have any sisters. +
Charlotte realized she wasn't the only woman resuscitating Ned. +
Agh! +
Charlotte's relationship died right where it started. +
She was prepared to live in the shadow of a dead woman. +
She wasn't prepared to live in the shadow of three live ones. +
That Saturday, Samantha hit rock bottom, +
also known as Javier House. +
No one would return her phone calls, +
she hadn't raised any money. +
All she could do for Javier House was construct it. +
But six hours of hard labor later, +
Samantha experienced her own rebirth. +
It was Leonardo DiCaprio, ex machina. +
That day, Leonardo and Samantha became fast friends. +
The nightmare was over. +
Leonardo DiCaprio had brought Sam back to social life. +
To add insult to panic attack, +
Miranda had just gotten some unsettling news. +
The mortgage officer had messed up Miranda's application. +
They had inadvertently labeled her as separated, +
and to clear up the confusion, Miranda had to write a rather humiliating letter. +
Miranda had a choice. +
She could panic, or she could just type. +
Miranda killed her panic attacks right then and there. +
She realized she probably wouldn't die alone. +
But she kept overfeeding her cat... +
just in case. +
Meanwhile, four unreturned calls later, +
my number was up. +
Good, you're alive. +
Hey, wait, where are you going? +
Home. +
I'm old, it's past my bedtime. +
I'm sorry. +
You should be. +
I had box seats to a Yankee doubleheader. +
Oh, damn! +
Who'd you take? +
Someone who returned my calls. +
It was déjà vu all over again. +
Me, Big, a doorway, +
and mixed emotions. +
Wait, not here. +
Don't do this, Carrie. +
Come on. +
We're going out. +
I took him to the most non-sexual place I could think of. +
I'm good! +
-Did you see that? -Wow, I sure did. +
Two pitchers of cheap beer later, +
Big and I were having a great time. +
You know what my version of hell is? +
Wearing rented two-toned shoes. +
Hey, batter, batter, batter... +
No heckling the bowler. +
Woo! +
Did you see that? +
Yeah. +
That was nice. +
Hey, look at that. +
I won. +
Okay, two out of three. +
You want to play a second game, huh? +
Maybe. +
Are you sure you're ready to get killed all over again? +
I didn't know what we were talking about anymore. +
But either way, I knew the answer. +
Yep, let's do it. +
We never made it to the second game. +
I didn't know if it was suicide or not. +
All I knew was, +
Big and I had been reincarnated, +
and I'd never felt more alive. +
欲望城市 +
（性爱专家凯莉布雷萧） +
，四个女人和一场葬礼 +
只有两种情形适合在 白天穿黑色礼服 +
一种是太晚离开派对 +
另一种是太早离开纽约的葬礼 +
哈维是个热情的古巴设计师 +
也是我的好朋友 +
我认识他很久了 哈维热爱服饰 +
不幸地，他更爱海洛因 +
可恶 +
好 +
-看看你 -你喜欢吗？ +
穿一位死去设计师设计的衣服 去参加他的葬礼不妥吧？ +
不穿才不妥，我花了两千块 不利用机会穿怎么行 +
-这么贵？ -从昨天开始加价三成 +
在纽约，死了比活着受欢迎 +
我得精心打扮，很多人会到场 +
这是葬礼 不是周五夜晚的派对 +
你听起来太悲伤，走吧 +
-抱歉，我迟到了 -是不是全曼哈顿都到了？ +
-凯莉邀我来的 -你是客人邀请来的？ +
-我们去看马格里特的展览 -你的服装很不合宜 +
显然地 夏绿蒂和我的服装才不合宜 +
就在那里：哈维的春装全系列 那是他有过最好的服装秀 +
-每个人都穿哈维的设计 -我就说吧 +
-把帽子借我 -好 +
要是有人问起 就说是设计师送的礼物 +
我的脚跟困在鞋子里 我为了这场葬礼也够牺牲了 +
（大家好，欢迎各位） +
看他们怎么作弄乔瑟芬娜 +
-她好漂亮 -一周前她不是长这样 +
乔瑟芬娜是哈维的妹妹 继承他整个服饰企业 +
百分百的丑小鸭变天鹅 +
彻彻底底地改头换面 +
-在葬礼上抽烟？ -哈维会喜欢的 +
我们今天将公开要求 为了纪念哈维 +
所有的捐款将汇到 “哈维之屋”名下 +
这个机构是为了在时尚界 +
患有物质滥用症的朋友设立的 +
-不需要 -不需要？ +
-我会帮忙募款 -你真是异常好心 +
邮寄名单可是无价之宝 有全曼哈顿未登记的电话 +
你不得不赞扬她这一点： 她总是看到光明的那一面 +
一个男人的死亡是另一个女人 公关事业的良机 +
我是莎曼珊琼斯，从事公关 +
你的演讲让我很感动 +
抱歉 +
你不需要脱帽致敬吧 +
她热爱帽子，这很合适 +
-这位是令堂？ -我妻子 +
我很抱歉 +
没关系，谢谢 +
-你们有小孩吗？ -没有 +
只不过是喝杯酒 他工作地点跟我的很近 +
你在公墓钓凯子？ +
他很英俊，普林斯顿大学毕业 +
-绝对不要跟鳏夫约会 -因为亡妻的缘故 +
不管她生前是不是个讨厌鬼 她死了，你永远比不上她 +
-不要这样说他的妻子 -已经开始了 +
老婆死了又不是老公的错 +
经历丧妻之痛会让他 更善解人意 +
他很有感情 +
这不是很浪漫吗？ 而且他结过婚 +
这表示他愿意承诺 +
那就跟离过婚的人约会 只要对方还活着 +
婚姻让大人物领悟他讨厌承诺 +
-是你跟他分手 -所以我有承诺恐惧？ +
当我们看着哈维安息地的 破土仪式 +
米兰达正在开辟她的新天地 +
-你一个人住？ -是的，我一个人 +
这么大的公寓只有你一个人住 +
我有很多鞋子 +
-或许男朋友会搬进去？ -没有男朋友，只有我 +
-我有个自己创业的儿子 -不用了，谢谢 +
我来就好 +
就这样，米兰达“先生” 又叫做“只有我” +
买给自己生平第一层公寓 并带自己出去喝酒 +
在当米兰达庆祝她的未来 我正在苦思我自己的 +
在一个步调飞快的城市 周六就可以拿到周日的报纸 +
我们如何能知道 生命还剩多少时间？ +
我有好多事还没做过 我还没去过希腊 +
我的信用卡帐单还没付清 +
有时候我根本不觉得我活着 +
-你好 -你好 +
-你好 -是我 +
你好吗？ +
-刚从一场葬礼回来 -所以想到我？真荣幸 +
听着…你想吃晚餐吗？ +
我每天都吃晚餐，跟谁？ +
-跟我 -那我得查一下行程 +
-我要挂电话了 -好 +
星期六八点，罗贝多餐厅 一定要到 +
天，你老了 +
就这么简单 我和大人物周六晚上有约 +
三十秒内，我们的关系复苏了 +
那花了我六个月才结束 +
莎曼珊正准备破自己的纪录 +
我很少做什么贡献 +
我们希望你能加入董事会 你能破例一次吗？ +
被你这样的美女恳求 就是史无前例的 +
理查康威尔，贝尔史登 资深合伙人，慈善家 +
他的专长是恶意接手他人企业 +
康威尔先生，奉承能成就大事 +
-叫我小弟弟就行 -小弟弟（与阳具同音） +
对莎曼珊来说 这比较像是友善的合并案 +
或许我们可以在 哈维之屋晚宴上讨论？ +
我可以安排 +
莎曼珊抚摸过小弟弟康威尔 身上所有名牌服饰 +
不幸地，她没料到珊蒂康威尔 +
会提早回家 +
-滚出去 -我把提案留在这里 +
显然地 珊蒂没有她丈夫来得慈善 +
在抵押借款公司 米兰达在交易时遇到困难 +
-只有你一个人？ -对，只有我 +
勾选单身妇女那一栏 并签上你的姓 +
头期款是你父亲支付吗？ +
不，是我 +
勾选单身妇女栏 +
米兰达勾选了无数个 单身妇女栏 +
如果我是单身男子 他们就不会这样了 +
如果你是单身男子 我就跟你约会 +
我有钱，有好工作 人们却老爱问我：只有你吗？ +
靠自己买一栋公寓 意味着你不需要男人 +
每个人都需要男人 所以我只租房子 +
要不然权力结构就垮了 +
男人不需要自给自足的女人 +
你真是来自旧时代的人 +
琼斯小姐，你的卡不被接受 +
-不可能，再试一次 -我可能没说清楚 +
我们这里不欢迎你和你的卡 +
莎曼珊招惹到不该惹的女人 +
珊蒂几乎拥有整个曼哈顿 她要莎曼珊在此消失 +
走吧，我们走 +
珊蒂做了任何富有的名流 都会做的事 +
她让莎曼珊在社交圈混不下去 +
在半天内 莎曼珊从贵宾名单变成黑名单 +
隔一晚 夏绿蒂和鳏夫耐德见面 +
-下一次我们好好吃顿饭 -我很乐意 +
他们谈论建筑，艺术 和长春藤联盟 +
-他的前妻从来不是话题… -这是她吗？ +
直到前妻的照片出现… +
对 +
她好漂亮 +
我们走吧 +
抱歉，我真粗心 你一定很难过 +
在约会时谈到她很奇怪 +
我了解 +
美丽的夜晚 +
耐德，你还好吗？ +
抱歉，我只是… +
看到丽兹的照片，想到她… +
-天，我很抱歉 -这给你 +
夏绿蒂讨厌男人哭 但耐德的眼泪让他显得更浪漫 +
这真是太糗了 +
我现在…感触很多 +
这些话在夏绿蒂耳中具有魔力 +
没关系，你慢慢平复情绪 +
显然地 耐德只需要四十五分钟 +
那晚，就在他亡妻的凝视下 +
耐德“重振雄风”…两次 +
-我劝你再想想 -他老婆去世了 +
-她说得有理 -我在帮他走过丧妻之痛 +
他根本就是事先策划好了 +
-他床上表现如何？ -太棒了 +
感觉就像丽兹看着我们 祝福我们 +
一人缺席的三人行 +
我的帽子被吹到她的墓前 她在传递某种讯息 +
“不要搞上我老公 你这个爱帽子的贱人” +
他邀请我参加下周 她的追悼仪式 +
什么时候这种事变成喜事？ +
这表示他愿意跟我更进一步 +
-所以你用性让他起死回生？ -可以这么说 +
你真棒 +
那一晚，我跟大人物约会 +
我心中五味杂陈： 恐惧，幸福，担心 +
我准备好回到大人物 身边了吗？ +
跟他再次见面是错误吗？ +
如果是，我为什么这么兴奋？ 我没有这么困惑过 +
夏绿蒂是对了吗？ +
在这个人人急于攀关系的世界 +
一段关系能让你起死回生吗？ +
-我想都没想过 -你死了以后会怎样？ +
我忙得没时间想这种问题 +
-我想我们有轮回 -这是一个解脱的方法 +
你来世会变成什么？ +
一个懂得更多的人 +
-你闻起来好香 -我是认真的 +
-你相信天堂吗？ -相信 +
-你心中的天堂是什么样子？ -一张大大的床 +
天堂的人对着我说：请进 +
-你心目中的天堂是张床？ -那要看谁躺在上面 +
-我今天不跟你上床 -我们不是只吃晚餐吗？ +
没错 +
半小时后，我回到大人物家中 我过去记忆埋葬的地方 +
感觉很棒，很怪…很不妥 +
-不可以 -可以 +
-不要这样 -好，我们进去 +
不行，我要走了 +
突然间，我觉得跟大人物复合 不是件好事 +
第一次跟大人物交往 我离开的正是时候 +
我第二次会一样幸运吗？ +
莎曼珊正面对自己不定的未来 +
-再查一次 -抱歉 +
她第一次觉得这是 一个不幸的错误 +
-来的真不是时候 -我们客满了 +
-我再等别桌 -不用麻烦了 +
当莎曼珊第三次被拒 一切就很明显了 +
她在这里死得比哈维还彻底 +
把她请出去 +
隔天，米兰达遇见她的新邻居 +
你们是我的新邻居吗？ +
我是米兰达霍布斯 很高兴见到你们 +
我还没搬进来 我只是来测量尺寸 +
我很高兴有年轻人搬进来 +
为这个地方带来生气 璐西很封闭，从未结婚 +
-她就死在里面 -真的吗？ +
一个礼拜后才被人发现 +
听说她的猫吃掉她半边脸 +
只有你一个人？ +
那一晚，米兰达遇到一个窘境 +
就在她穿越美丽的厨房时 她被食物噎住了 +
自己救回一条命后 她打电话找人诉苦 +
不幸地，我正在过滤电话 +
大人物打来两次 我不知道要说什么 +
我噎到了，快死了你却不接… +
-你还好吗？ -我在看影集 +
我想当我被发现时 我会变成看烂节目的死人 +
-你为什么不打电话给我？ -我没办法呼吸 +
-我将孤老到死 -你要我过去吗？ +
我很好，明天再打给你 +
米兰达一点都不好 她饿着肚子上床睡觉 +
还把猫关在厨房两天 +
当了一星期的社交贱民后 +
莎曼珊领悟到她不得不求人 才能回到以前 +
她去求助最上层的教父级人物 +
莎曼珊琼斯，听起来很熟 +
希琵西普曼是社交皇后 +
她曾让至少七十个 社交人士消失 +
-因为我负责筹募哈维之屋？ -不是的 +
你就是在一场慈善会中 勾引我丈夫的狐狸精 +
不只莎曼珊完蛋了 +
她的性生活也从她眼前闪过 +
-或许吧，我不记得了 -我记得 +
你跟珊蒂康威尔是好朋友？ +
-没错，我跟她是旧识了 -你能帮我跟她讲讲话？ +
自己铺的床，自己睡 +
你很擅长的不是吗？ +
希琵，你希望我说什么？ 我是个荡妇？ +
我跟全纽约的男人睡过 或许还有布鲁克林的？ +
好，或许是真的 但我需要承受这么多吗？ +
好，我是个大荡妇 +
你愿意帮我吗？ +
-不愿意 -好吧 +
我是因为喝醉才会抚摸 你丈夫又平又垮的屁股 +
不用送了 +
隔天，米兰达决定 观察周遭环境 +
突然间，她萌生退意 +
这就是纽约的诡异之处 +
你永远不知道计程车 会救你还是害你 +
真的是很奇怪 +
我觉得自己就快淹死了 +
你这是惊吓过度 +
我得花五百块给医生诊断 +
怎么了？ +
好好看看我的脸 葬礼上我的脸会只剩一半 +
我死了，我的猫会很高兴 +
夏绿蒂又会藉机在墓园钓凯子 +
深呼吸，亲爱的 +
我一个人，凯莉 +
我的紧急联络人是我的父母 +
我不喜欢他们 而且他们住在宾州 +
-你可以写我 -不行，你不接电话 +
我保证我会接的 +
听好，你买公寓是正确的 +
-你很喜欢，不是吗？ -是 +
你不会一辈子孤单的 +
我不知道我们之中 有没有人会孤身到老 +
我只知道米兰达禁不起 再一次的打击 +
在皇后区 夏绿蒂正准备接受惊喜 +
-你带了百合花 -你说这是她最爱的花 +
-他们是你妹妹吧？ -我没有妹妹 +
夏绿蒂不是唯一 让耐德重振雄风的人 +
夏绿蒂的感情才刚开始就结束 +
她可以活在一个 死去女人的阴影下 +
却不能接受三个活着的女人 +
那个星期六，莎曼珊跌到谷底 +
没有人回她的电话 她一毛钱也没有募到 +
她能为哈维之屋做的 就是帮忙盖 +
在辛苦工作六小时后 她获得重生 +
那是李奥纳多狄卡皮欧 解围之神 +
他们很快地变成朋友 噩梦就此结束 +
李奥纳多将莎曼珊带回社交圈 +
在惊吓过度之后 米兰达接到脑人的消息 +
贷款经办人窜改她的申请 +
他们将她贴上分居的标签 +
为了澄清 米兰达写了一封蒙羞的信 +
米兰达有一个选择 她可以惊慌或是打字 +
米兰达当下即克服了她的恐惧 +
她知道她或许不会孤单地死去 +
但她一直过量地喂她的猫 +
在四通未接电话后 我的把戏被揭穿了 +
-很好，你还活着 -等一下，你要去哪里？ +
-回家，我老了，该睡觉了 -我很抱歉 +
应该的，我有洋基队的门票 +
-该死，你带谁去？ -回我电话的人 +
旧事重演 +
我，大人物，在楼梯间 交杂的情绪 +
-等一下，不要在这里 -不要这样，凯莉 +
走吧，我们出去 +
我带他到最不会引起 性欲的地方 +
-我真棒，你有看到吗？ -当然有 +
喝了两壶啤酒 我们玩得很愉快 +
你知道地狱长什么样子吗？ 穿着租来的两色鞋 +
不要刁难打保龄球的人 +
-你有看到吗？ -有，很棒 +
你看 +
-我赢了 -三战两胜 +
-要再玩一局吗？ -或许吧 +
你准备好再一次被痛宰？ +
我不确定我们在谈什么 但我知道答案 +
来吧 +
我们没有再打第二局 +
我不知道这样算不算自杀 +
我只知道大人物跟我再生了 +
我从来没有这么有活力 +
