

=  杨鹏 001-050
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''


== 释义

'''






'''

== pure

- (001.) That sex ratio will be favored which maximizes the number of descendants an individual will have and hence the number of gene copies transmitted.

- (002.) Hardy’s weakness derived from his apparent inability to control the comings and goings of these divergent impulses and from his unwillingness to cultivate and sustain the energetic and risky ones.

- (003.) Virginia Woolf’s provocative statement about her intentions in writing Mrs. Dalloway has regularly been ignored by the critics, since it highlights an aspect of her literary interests very different from the traditional picture of the “poetic” novelist concerned with examining states of reverie and vision and with following the intricate pathways of individual consciousness.

- (004.) As she put it in The Common Reader, “It is safe to say that not a single law has been framed or one stone set upon another because of anything Chaucer said or wrote; and yet, as we read him, we are absorbing morality at every pore.”

- (005.) With the conclusion of a burst of activity, the lactic acid level is high in the body fluids, leaving the large animal vulnerable to attack until the acid is reconverted, via oxidative metabolism, by the liver into glucose, which is then sent (in part) back to the muscles for glycogen resynthesis.

- (006.) Although Gutman admits that forced separation by sale was frequent, he shows that the slaves’ preference, revealed most clearly on plantations where sale was infrequent, was very much for stable monogamy.

- (007.) Gutman argues convincingly that the stability of Black family encouraged the transmission of--and so was crucial in sustaining--the Black heritage of folklore, music, and religious expression from one generation to another, a heritage that slaves were continually fashioning out of their African and American experiences.

- (008.) This preference for exogamy, Gutman suggests, may have derived from West African rules governing marriage, which, though they differed from one tribal group to another, all involved some kind of prohibition against unions with close kin.

- (009.) His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

- (010.) Such variations in size, shape, chemistry, conduction speed, excitation threshold, and the like as had been demonstrated in nerve cells remained negligible in significance for any possible correlation with the manifold dimensions of mental experience.

- (011.) It was possible to demonstrate by other methods refined structural differences among neuron types; however, proof was lacking that the quality of the impulse or its condition was influenced by these differences, which seemed instead to influence the developmental patterning of the neural circuits.

- (012.) Although qualitative variance among nerve energies was never rigidly disproved, the doctrine was generally abandoned in favor of the opposing view, namely, that nerve impulses are essentially homogeneous in quality and are transmitted as “common currency” throughout the nervous system.

- (013.) Other experiments revealed slight variations in the size, number, arrangement, and interconnection of the nerve cells, but as far as psychoneural correlations were concerned, the obvious similarities of these sensory fields to each other seemed much more remarkable than any of the minute differences.

- (014.) Although some experiments show that, as an object becomes familiar, its internal representation becomes more holistic and the recognition process correspondingly more parallel, the weight of evidence seems to support the serial hypothesis, at least for objects that are not notably simple and familiar.

- (015.) In large part as a consequence of the feminist movement, historians have focused a great deal of attention in recent years on determining more accurately the status of women in various periods.

- (016.) If one begins by examining why ancient writers refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact--real Amazonian societies--but rather to offer “moral lessons” on the supposed outcome of women’s rule in their own society.

- (017.) Thus, for instance, it may come as a shock to mathematicians to learn that the Schrodinger equation for the hydrogen atom is not a literally correct description of the atom, but only an approximation to a somewhat more correct equation taking account of spin, magnetic dipole, and relativistic effects; and that this corrected equation is itself only an imperfect approximation to an infinite set of quantum field-theoretical equations.

- (018.) The physicist rightly dreads precise argument, since an argument that is convincing only if it is precise loses all its force if the assumptions on which it is based are slightly changed, whereas an argument that is convincing though imprecise may well be stable under small perturbations of its underlying assumptions.

- (019.) However, as they gained cohesion, the Bluestockings came to regard themselves as a women’s group and to possess a sense of female solidarity lacking in the salonnieres, who remained isolated from one another by the primacy each held in her own salon.

- (020.) As my own studies have advanced, I have been increasingly impressed with the functional similarities between insect and vertebrate societies and less so with the structural differences that seem, at first glance, to constitute such an immense gulf between them.

- (021.) Although fiction assuredly springs from political circumstances, its authors react to those circumstances in ways other than ideological, and talking about novels and stories primarily as instruments of ideology circumvents much of the fictional enterprise.

- (022.) Is this a defect, or are the authors working out of, or trying to forge, a different kind of aesthetic?

- (023.) In addition, the style of some Black novels, like Jean Toomer’s Cane, verges on expressionism or surrealism; does this technique provide a counterpoint to the prevalent theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

- (024.) Black Fiction surveys a wide variety of novels, bringing to our attention in the process some fascinating and little-known works like James Weldon Johnson’s Autobiography of an Ex-colored Man.

- (025.) Although these molecules allow radiation at visible wavelengths, where most of the energy of sunlight is concentrated, to pass through, they absorb some of the longer-wavelength, infrared emissions radiated from the Earth’s surface, radiation that would otherwise be transmitted back into space.

- (026.) The role those anthropologists ascribe to evolution is not of dictating the details of human behavior but one of imposing constraints--ways of feeling, thinking, and acting that “come naturally” in archetypal situations in any culture.

- (027.) Which of the following most probably provides an appropriate analogy from human morphology for the “details” versus “constraints” distinction made in the passage in relation to human behavior?

- (028.) A low number of algal cells in the presence of a high number of grazers suggested, but did not prove, that the grazers had removed most of the algae.

- (029.) Perhaps the fact that many of these first studies considered only algae of a size that could be collected in a net (net phytoplankton), a practice that overlooked the smaller phytoplankton (nannoplankton) that we now know grazers are most likely to feed on, led to a deemphasis of the role of grazers in subsequent research.

- (030.) Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers.

- (031.) In the periods of peak zooplankton abundance, that is, in the late spring and in the summer, Haney recorded maximum daily community grazing rates, for nutrient-poor lakes and bog lakes, respectively, of 6.6 percent and 114 percent of daily phytoplankton production.

- (032.) The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

- (033.) Only when a system possesses natural or artificial boundaries that associate the water within it with the hydrologic cycle may the entire system properly be termed hydrogeologic.

- (034.) The historian Frederick J. Turner wrote in the 1890’s that the agrarian discontent that had been developing steadily in the United States since about 1870 had been precipitated by the closing of the internal frontier--that is, the depletion of available new land needed for further expansion of the American farming system.

- (035.) In the early 1950’s, historians who studied preindustrial Europe (which we may define here as Europe in the period from roughly 1300 to 1800) began, for the first time in large numbers, to investigate more of the preindustrial European population than the 2 or 3 percent who comprised the political and social elite: the kings, generals, judges, nobles, bishops, and local magnates who had hitherto usually filled history books.

- (036.) Historians such as Emmanuel Le Roy Ladurie have used the documents to extract case histories, which have illuminated the attitudes of different social groups (these attitudes include, but are not confined to, attitudes toward crime and the law) and have revealed how the authorities administered justice.

- (037.) It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

- (038.) My point is that its central consciousness--its profound understanding of class and gender as shaping influences on people’s lives--owes much to that earlier literary heritage, a heritage that, in general, has not been sufficiently valued by most contemporary literary critics.

- (039.) Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reaction of tissue cultures to biomaterials or from short-term implants.

- (040.) But achieving necessary matches in physical properties across interfaces between living and non-living matter requires knowledge of which molecules control the bonding of cells to each other--an area that we have not yet explored thoroughly.

- (041.) Islamic law is a phenomenon so different from all other forms of law--notwithstanding, of course, a considerable and inevitable number of coincidences with one or other of them as far as subject matter and positive enactment are concerned--that its study is indispensable in order to appreciate adequately the full range of possible legal phenomena.

- (042.) Both Jewish law and canon law are more uniform than Islamic law. Though historically there is a discernible break between Jewish law of the sovereign state of ancient Israel and of the Diaspora (the dispersion of Jewish people after the conquest of Israel), the spirit of the legal matter in later parts of the Old Testament is very close to that of the Talmud, one of the primary codifications of Jewish law in the Diaspora.

- (043.) Islam, on the other hand, represented a radical breakaway from the Arab paganism that preceded it; Islamic law is the result of an examination, from a religious angle, of legal subject matter that was far from uniform, comprising as it did the various components of the laws of pre-Islamic Arabia and numerous legal elements taken over from the non-Arab peoples of the conquered territories.

- (044.) One such novel idea is that of inserting into the chromosomes of plants discrete genes that are not a part of the plants’ natural constitution: specifically, the idea of inserting into nonleguminous plants the genes, if they can be identified and isolated, that fit the leguminous plants to be hosts for nitrogen-fixing bacteria. Hence, the intensified research on legumes.

- (045.) It is one of nature’s great ironies that the availability of nitrogen in the soil frequently sets an upper limit on plant growth even though the plants’ leaves are bathed in a sea of nitrogen gas.

- (046.) Unless they succeed, the yield gains of the Green Revolution will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis with nitrogen fixers are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

- (047.) Its subject (to use Maynard Mack’s categories) is “life-as-spectacle,” for readers, diverted by its various incidents, observe its hero Odysseus primarily from without; the tragic Iliad, however, presents “life-as-experience”: readers are asked to identify with the mind of Achilles, whose motivations render him not a particularly likable hero.

- (048.) Most striking among the many asymmetries evident in an adult flatfish is eye placement: before maturity one eye migrates, so that in an adult flatfish both eyes are on the same side of the head.

- (049.) A critique of the Handlins’ interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and explanations for the different treatment of Black slaves in North and South America should be expanded.

- (050.) The best evidence for the layered mantle thesis is the well-established fact that volcanic rocks found on oceanic islands, islands believed to result from mantle plumes arising from the lower mantle, are composed of material fundamentally different from that of the midocean ridge system, whose source, most geologists contend, is the upper mantle.

'''



