

=  杨鹏  051-100
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义









- (063.) #*This is not because*# such an interpretation 解释；阐释 necessarily stiffens (v.)（使）变僵硬；变生硬；（使）变强硬 into a thesis 论文；论点；论题 (although `主` rigidity 僵硬；刻板；僵化 in any interpretation of this or of any novel `系` is always a danger), #*but because*# Wuthering Heights has recalcitrant 反抗的；不服从的；顽抗的 elements 要素；成分；组成部分 of undeniable 不可否认的；确凿无疑的 power 影响力；效力 that, ultimately 最终；最后, resist 抵抗；抗拒；反抗 inclusion 包含；包括 in all-encompassing 包罗万象的；全面的 interpretation.


[.my1]
.案例
====
- (063.) This is not because such an interpretation necessarily stiffens into a thesis (although rigidity in any interpretation of this or of any novel is always a danger), but because Wuthering Heights has recalcitrant elements of undeniable power that, ultimately, resist inclusion in all-encompassing interpretation.

这并非因为这种解释必然会僵化为一种论点（尽管对这部或任何小说的任何解释中的僵化始终是一种危险），而是因为《呼啸山庄》拥有不容置疑的力量的顽固元素，这些元素最终抵制被纳入任何包罗万象的解释。
====

- (064.) The isotopic 同位素的 composition 成分；组成 of lead often varies from one source of common copper ore 铜矿石 to another, with variations exceeding the measurement error; and preliminary 初步的；预备的 studies indicate virtually uniform isotopic composition of the lead from a single copper-ore source. +

[.my1]
.案例
====
- (064.) The isotopic composition of lead often varies from one source of common copper ore to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform isotopic composition of the lead from a single copper-ore source.

铅的同位素组成常常因普通铜矿石来源的不同而异，其变异量超出测量误差；初步研究表明，来自单一铜矿石来源的铅具有几乎一致的同位素组成。
====

- (065.) More probable is bird transport, either externally, by accidental attachment 附着；粘连 of the seeds to feathers, or internally, by the swallowing of fruit and subsequent excretion 排泄 of the seeds. +

[.my1]
.案例
====
- (065.) More probable is bird transport, either externally, by accidental attachment of the seeds to feathers, or internally, by the swallowing of fruit and subsequent excretion of the seeds.

更可能的是鸟类传播，无论是外部传播（种子意外附着在羽毛上），还是内部传播（鸟类吞食果实后排泄种子）。
====

- (066.) A long-held view of the history of the English colonies that became the United States has been that England’s policy toward these colonies before 1763 was dictated by 由……决定 commercial interests and that a change to a more imperial 帝国的 policy, dominated by expansionist 扩张主义的 militarist 军国主义的 objectives, generated the tensions that ultimately led to the American Revolution. +

[.my1]
.案例
====
- (066.) A long-held view of the history of the English colonies that became the United States has been that England’s policy toward these colonies before 1763 was dictated by commercial interests and that a change to a more imperial policy, dominated by expansionist militarist objectives, generated the tensions that ultimately led to the American Revolution.

一个长期以来关于构成美国的英国殖民地历史的观点认为，1763年之前英国对这些殖民地的政策是由商业利益决定的，而转向由扩张主义军事目标主导的更具帝国主义色彩的政策，则产生了最终导致美国革命的紧张局势。
====

- (067.) It is not known how rare this resemblance 相似；相似之处 is, or whether it is most often seen in inclusions 包裹体 of silicate 硅酸盐 such as garnet 石榴石, whose crystallography 晶体学 is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling 令人信服的 evidence that the diamonds and inclusions are truly cogenetic 同源的. +

[.my1]
.案例
====
- (067.) It is not known how rare this resemblance is, or whether it is most often seen in inclusions of silicate such as garnet, whose crystallography is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence that the diamonds and inclusions are truly cogenetic.

目前尚不清楚这种相似性有多罕见，也不清楚它是否最常见于石榴石等硅酸盐内含物中（石榴石的晶体结构通常与钻石有些相似）；但如果存在，这种相似性被认为是钻石和内含物确实同源的有力证据。
====

- (068.) Even the “radical” critiques 批评；评论 of the mainstream 主流的 research model, such as the critique developed in *Divided Society*, attach 把……归因于 the issue of ethnic assimilation 民族同化 too mechanically 机械地 to factors of economic and social mobility 流动性 and are thus unable to illuminate 阐明；揭示 the cultural subordination 从属；隶属 of Puerto Ricans as a colonial minority 殖民地少数民族. +

[.my1]
.案例
====
- (068.) Even the “radical” critiques of the mainstream research model, such as the critique developed in Divided Society, attach the issue of ethnic assimilation too mechanically to factors of economic and social mobility and are thus unable to illuminate the cultural subordination of Puerto Ricans as a colonial minority.

即使是对主流研究模式的“激进”批判，例如《分裂社会》中提出的批判，也过于机械地将民族同化问题与经济和社会流动性因素联系起来，因此无法阐明波多黎各人作为殖民地少数民族的文化从属地位。
====

- (069.) They are called virtual particles 虚粒子 in order to distinguish them from real particles, whose lifetimes 寿命 are not constrained 限制；约束 in the same way, and which can be detected 检测；发现. +

[.my1]
.案例
====
- (069.) They are called virtual particles in order to distinguish them from real particles, whose lifetimes are not constrained in the same way, and which can be detected.

它们被称为虚粒子，是为了将它们与实粒子区分开来，实粒子的寿命不受同样的限制，并且可以被探测到。
====

- (070.) Open acknowledgment 承认；确认 of the existence of women’s oppression 压迫 was too radical 激进的 for the United States in the fifties, and Beauvoir’s conclusion, that change in women’s economic condition, though insufficient 不足的；不充分的 by itself, “remains the basic factor” in improving women’s situation, was particularly unacceptable. +

[.my1]
.案例
====
- (070.) Open acknowledgment of the existence of women’s oppression was too radical for the United States in the fifties, and Beauvoir’s conclusion, that change in women’s economic condition, though insufficient by itself, “remains the basic factor” in improving women’s situation, was particularly unacceptable.

在20世纪50年代的美国，公开承认女性受压迫的存在太过激进，而波伏娃的结论，即女性经济状况的改变，尽管本身不足以解决问题，但“仍然是改善女性处境的基本因素”，这一点尤其令人无法接受。
====

- (071.) Other theorists propose that the Moon was ripped out of 从……中撕裂 the Earth’s rocky mantle 岩石地幔 by the Earth’s collision 碰撞 with another large celestial body 天体 after much of the Earth’s iron fell to its core 地核. +

[.my1]
.案例
====
- (071.) Other theorists propose that the Moon was ripped out of the Earth’s rocky mantle by the Earth’s collision with another large celestial body after much of the Earth’s iron fell to its core.

其他理论家提出，在地球大部分铁元素落入地核之后，月球是由地球与另一个大型天体碰撞，从地球的岩石地幔中撕裂出来的。
====

- (072.) However, recent scholarship 学术研究 has strongly suggested that those aspects of early New England culture that seem to have been most distinctly Puritan 清教徒的, such as the strong religious orientation 倾向；方向 and the communal 集体的；公共的 impulse 冲动；推动力, were not even typical of New England as a whole, but were largely confined to 局限于 two colonies of Massachusetts and Connecticut. +

[.my1]
.案例
====
- (072.) However, recent scholarship has strongly suggested that those aspects of early New England culture that seem to have been most distinctly Puritan, such as the strong religious orientation and the communal impulse, were not even typical of New England as a whole, but were largely confined to two colonies of Massachusetts and Connecticut.

然而，最近的学术研究强烈表明，早期新英格兰文化中那些似乎最具清教徒特色的方面，例如强烈的宗教倾向和社群冲动，甚至并非整个新英格兰的典型特征，而主要局限于马萨诸塞州和康涅狄格州这两个殖民地。
====

- (073.) Thus, what in contrast to the Puritan colonies appears to Davis to be peculiarly Southern--acquisitiveness 贪婪；物欲, a strong interest in politics and the law, and a tendency to cultivate metropolitan 大都市的 cultural models--was not only more typically English than the cultural patterns exhibited by Puritan Massachusetts and Connecticut, but also almost certainly characteristic of most other early modern British colonies from Barbados north to Rhode Island and New Hampshire. +

[.my1]
.案例
====
- (073.) Thus, what in contrast to the Puritan colonies appears to Davis to be peculiarly Southern--acquisitiveness, a strong interest in politics and the law, and a tendency to cultivate metropolitan cultural models--was not only more typically English than the cultural patterns exhibited by Puritan Massachusetts and Connecticut, but also almost certainly characteristic of most other early modern British colonies from Barbados north to Rhode Island and New Hampshire.

因此，与清教徒殖民地形成对比，在戴维斯看来具有独特南方特征的——贪婪、对政治和法律的浓厚兴趣，以及培养大都市文化模式的倾向——不仅比清教徒马萨诸塞和康涅狄格展现的文化模式更具典型英格兰特色，而且几乎可以肯定地代表了从巴巴多斯向北至罗德岛和新罕布什尔州的大多数其他早期现代英国殖民地的特点。
====

- (074.) Portrayals 描绘；刻画 of the folk of Mecklenburg County, North Carolina, whom he remembers from early childhood, of the jazz musicians and tenement 廉租公寓 roofs of his Harlem days, of Pittsburgh steelworkers, and his reconstruction 重建；再现 of classical Greek myths in the ancient Black kingdom of Benin, attest to 证明；证实 this. +

[.my1]
.案例
====
- (074.) Portrayals of the folk of Mecklenburg County, North Carolina, whom he remembers from early childhood, of the jazz musicians and tenement roofs of his Harlem days, of Pittsburgh steelworkers, and his reconstruction of classical Greek myths in the ancient Black kingdom of Benin, attest to this.

他童年时代记忆中的北卡罗来纳州梅克伦堡县的居民形象，他哈莱姆时期爵士音乐家和贫民窟屋顶的形象，匹兹堡钢铁工人的形象，以及他在古代贝宁黑人王国对古典希腊神话的重构，都证明了这一点。
====

- (075.) A very specialized 专门的；特殊的 feeding adaptation 适应 in zooplankton is that of the tadpolelike appendicularian 尾海鞘纲动物 who lives in a walnut-sized (or smaller) balloon of mucus 黏液 equipped with filters 过滤器 that capture and concentrate phytoplankton 浮游植物. +

[.my1]
.案例
====
- (075.) A very specialized feeding adaptation in zooplankton is that of the tadpolelike appendicularian who lives in a walnut-sized (or smaller) balloon of mucus equipped with filters that capture and concentrate phytoplankton.

浮游动物中一种非常特殊的摄食适应是蝌蚪状尾海鞘，它生活在一个核桃大小（或更小）的粘液气囊中，气囊配备有过滤器，可以捕获并浓缩浮游植物。
====

- (076.) These historians, however, have analyzed less fully the development of specifically feminist 女权主义的 ideas and activities during the same period. +

[.my1]
.案例
====
- (076.) These historians, however, have analyzed less fully the development of specifically feminist ideas and activities during the same period.

然而，这些历史学家对同期具体女权主义思想和活动的发展分析不足。
====

- (077.) Apparently most massive stars manage to lose sufficient material that their masses drop below the critical 关键的；临界的 value of 1.4M before they exhaust 耗尽；用尽 their nuclear fuel 核燃料. +

[.my1]
.案例
====
- (077.) Apparently most massive stars manage to lose sufficient material that their masses drop below the critical value of 1.4M before they exhaust their nuclear fuel.

显然，大多数大质量恒星在耗尽核燃料之前，都能设法损失足够多的物质，使其质量降至1.4M的临界值以下。
====

- (078.) This is so even though the armed forces operate in an ethos 精神特质；风气 of institutional 机构的；制度的 change oriented toward occupational equality and under the federal sanction 批准；认可 of equal pay for equal work. +

[.my1]
.案例
====
- (078.) This is so even though the armed forces operate in an ethos of institutional change oriented toward occupational equality and under the federal sanction of equal pay for equal work.

尽管军队在一种制度变革的氛围中运作，这种变革旨在实现职业平等，并且在联邦政府对同工同酬的认可下，情况依然如此。
====

- (079.) An impact capable of ejecting 喷射；排出 a fragment 碎片 of the Martian 火星的 surface into an Earth-intersecting orbit 轨道 is even less probable than such an event on the Moon, in view of 考虑到 the Moon’s smaller size and closer proximity 接近；邻近 to Earth. +

[.my1]
.案例
====
- (079.) An impact capable of ejecting a fragment of the Martian surface into an Earth-intersecting orbit is even less probable than such an event on the Moon, in view of the Moon’s smaller size and closer proximity to Earth.

考虑到月球尺寸较小且离地球更近，能够将火星表面碎片 eject 到与地球相交的轨道上的撞击，比月球上发生此类事件的可能性更小。
====

- (080.) Not only are liver transplants 肝脏移植 never rejected 排斥, but they even induce 诱发；引起 a state of donor-specific unresponsiveness 无反应性 in which subsequent 随后的 transplants of other organs, such as skin, from that donor are accepted permanently 永久地. +

[.my1]
.案例
====
- (080.) Not only are liver transplants never rejected, but they even induce a state of donor-specific unresponsiveness in which subsequent transplants of other organs, such as skin, from that donor are accepted permanently.

肝脏移植不仅从未被排斥，它们甚至能诱导一种供体特异性无反应状态，在这种状态下，来自同一供体的其他器官（如皮肤）的后续移植也会被永久接受。
====

- (081.) As rock interfaces 界面 are crossed, the elastic 弹性的 characteristics encountered generally change abruptly 突然地；意外地, which causes part of the energy to be reflected back to the surface, where it is recorded by seismic 地震的 instruments. +

[.my1]
.案例
====
- (081.) As rock interfaces are crossed, the elastic characteristics encountered generally change abruptly, which causes part of the energy to be reflected back to the surface, where it is recorded by seismic instruments.

当穿过岩石界面时，所遇到的弹性特性通常会突然改变，这导致部分能量反射回地表，并在那里被地震仪记录下来。
====

- (082.) While the new doctrine 学说；教义 seems almost certainly correct, the one papyrus 纸莎草纸 fragment raises the specter 恐惧；忧虑 that another may be unearthed 发掘；出土, showing, for instance, that it was a posthumous 死后的 production of the Danaid tetralogy 四联剧 which bested Sophocles, and throwing the date once more into utter confusion 混乱. +

[.my1]
.案例
====
- (082.) While the new doctrine seems almost certainly correct, the one papyrus fragment raises the specter that another may be unearthed, showing, for instance, that it was a posthumous production of the Danaid tetralogy which bested Sophocles, and throwing the date once more into utter confusion.

尽管新学说几乎可以肯定是正确的，但那件纸莎草残片引出了一个幽灵般的可能性：也许会出土另一件残片，例如显示它是《达那伊得斯四部曲》的遗作，这部作品曾胜过索福克勒斯，从而再次将日期完全搅乱。
====

- (083.) The methods that a community devises 设计；想出 to perpetuate 使永久；保持 itself come into being to preserve aspects of the cultural legacy 遗产 that that community perceives as essential. +

[.my1]
.案例
====
- (083.) The methods that a community devises to perpetuate itself come into being to preserve aspects of the cultural legacy that that community perceives as essential.

一个社群为延续自身而设计的方法，其产生是为了保护该社群认为至关重要的文化遗产的各个方面。
====

- (084.) Traditionally, pollination 传粉 by wind has been viewed as a reproductive 繁殖的；生殖的 process marked by random events in which the vagaries 变幻莫测 of the wind are compensated for 弥补；补偿 by the generation of vast quantities of pollen 花粉, so that the ultimate production of new seeds is assured at the expense of 以……为代价 producing much more pollen than is actually used. +

[.my1]
.案例
====
- (084.) Traditionally, pollination by wind has been viewed as a reproductive process marked by random events in which the vagaries of the wind are compensated for by the generation of vast quantities of pollen, so that the ultimate production of new seeds is assured at the expense of producing much more pollen than is actually used.

传统上，风媒授粉被视为一个以随机事件为特征的繁殖过程，其中风的变幻莫测通过产生大量的花粉来弥补，从而确保了新种子的最终产生，但代价是生产了比实际使用量多得多的花粉。
====

- (085.) Because the potential hazards 危险；危害 pollen grains 花粉粒 are subject to 遭受；经历 as they are transported over long distances are enormous, wind-pollinated plants have, in the view above, compensated for the ensuing 随之发生的 loss of pollen through happenstance 偶然事件 by virtue of 凭借；由于 producing an amount of pollen that is one to three orders of magnitude 数量级 greater than the amount produced by species pollinated by insects. +

[.my1]
.案例
====
- (085.) Because the potential hazards pollen grains are subject to as they are transported over long distances are enormous, wind-pollinated plants have, in the view above, compensated for the ensuing loss of pollen through happenstance by virtue of producing an amount of pollen that is one to three orders of magnitude greater than the amount produced by species pollinated by insects.

由于花粉粒在长距离运输过程中可能面临的潜在危险巨大，因此，根据上述观点，风媒植物通过产生比昆虫授粉物种多一到三个数量级的花粉量，来弥补偶然造成的花粉损失。
====

- (086.) For example, the spiral 螺旋形的 arrangement of scale-bract complexes 鳞片苞片复合体 on ovule-bearing 结胚珠的 pine cones 松果, where the female reproductive organs of conifers 针叶树 are located, is important to the production of air flow patterns that spiral over the cone’s surfaces, thereby passing airborne 空气传播的 pollen from one scale to the next. +

[.my1]
.案例
====
- (086.) For example, the spiral arrangement of scale-bract complexes on ovule-bearing pine cones, where the female reproductive organs of conifers are located, is important to the production of air flow patterns that spiral over the cone’s surfaces, thereby passing airborne pollen from one scale to the next.

例如，带胚珠的松果（针叶树的雌性生殖器官所在之处）上鳞苞复合体的螺旋排列，对于产生在松果表面螺旋流动的气流模式至关重要，从而使空气中的花粉从一个鳞片传递到下一个。
====

- (087.) Friedrich Engels, however, predicted that women would be liberated from the “social, legal, and economic subordination 从属；服从” of the family by technological developments that made possible the recruitment 招募；招聘 of “the whole female sex into public industry”. +

[.my1]
.案例
====
- (087.) Friedrich Engels, however, predicted that women would be liberated from the “social, legal, and economic subordination” of the family by technological developments that made possible the recruitment of “the whole female sex into public industry”.

然而，弗里德里希·恩格斯预测，女性将通过技术发展摆脱家庭的“社会、法律和经济从属地位”，这些技术发展使得“全体女性进入公共工业”成为可能。
====

- (088.) It was not the change in office technology, but rather the separation of secretarial work, previously seen as an apprenticeship 学徒期 for beginning managers from administrative 行政的；管理的 work that in the 1880s created a new class of “dead-end 没有前途的” jobs, thenceforth 此后；从那时起 considered “women’s work”. +

[.my1]
.案例
====
- (088.) It was not the change in office technology, but rather the separation of secretarial work, previously seen as an apprenticeship for beginning managers, from administrative work that in the 1880s created a new class of “dead-end” jobs, thenceforth considered “women’s work”.

并非是办公技术的变化，而是在19世纪80年代，秘书工作（此前被视为初级管理人员的学徒期）与行政工作的分离，创造了一类新的“死胡同”式工作，此后这些工作被视为“女性工作”。
====

- (089.) The increase in the numbers of married women employed outside the home in the twentieth century had less to do with 与……关系不大 mechanization 机械化 of housework and an increase in leisure time for these women than it did with their own economic necessity and with high marriage rates that shrank 缩小；减少 the available pool of single women workers, previously, in many cases, the only women employers would hire. +

[.my1]
.案例
====
- (089.) The increase in the numbers of married women employed outside the home in the twentieth century had less to do with mechanization of housework and an increase in leisure time for these women than it did with their own economic necessity and with high marriage rates that shrank the available pool of single women workers, previously, in many cases, the only women employers would hire.

20世纪已婚女性外出就业人数的增加，与其说是由于家务机械化和这些女性闲暇时间的增加，不如说是由于她们自身的经济需求以及高结婚率缩小了单身女性劳动力的可用池（在许多情况下，此前雇主只会雇佣单身女性）。
====

- (090.) For one thing, no population can be driven entirely by density-independent 密度无关的 factors all the time. +

[.my1]
.案例
====
- (090.) For one thing, no population can be driven entirely by density-independent factors all the time.

首先，没有任何种群可以一直完全由密度无关因素驱动。
====

- (091.) In order to understand the nature of the ecologist’s investigation, we may think of the density-dependent 密度依赖的 effects on growth parameters 参数 as the “signal” ecologists are trying to isolate 分离；隔离 and interpret, one that tends to make the population increase from relatively low values or decrease from relatively high ones, while the density-independent effects act to produce “noise” in the population dynamics 动态；变化. +

[.my1]
.案例
====
- (091.) In order to understand the nature of the ecologist’s investigation, we may think of the density-dependent effects on growth parameters as the “signal” ecologists are trying to isolate and interpret, one that tends to make the population increase from relatively low values or decrease from relatively high ones, while the density-independent effects act to produce “noise” in the population dynamics.

为了理解生态学家调查的性质，我们可以将对增长参数的密度依赖性影响视为生态学家试图分离和解释的“信号”，这种信号倾向于使种群从相对较低的值增加或从相对较高的值减少，而密度无关性影响则在种群动态中产生“噪声”。
====

- (092.) But the play’s view of Black self-esteem 自尊 and human solidarity 团结 as compatible 兼容的；能共处的 is no more “contradictory 矛盾的” than Du Bois’ famous, well-considered ideal of ethnic self-awareness coexisting with human unity, or Fanon’s emphasis on an ideal internationalism 国际主义 that also accommodates 包容；容纳 national identities and roles. +

[.my1]
.案例
====
- (092.) But the play’s view of Black self-esteem and human solidarity as compatible is no more “contradictory” than Du Bois’ famous, well-considered ideal of ethnic self-awareness coexisting with human unity, or Fanon’s emphasis on an ideal internationalism that also accommodates national identities and roles.

但是，该剧将黑人自尊与人类团结视为相容的观点，其“矛盾”程度不亚于杜波依斯著名的、经过深思熟虑的民族自我意识与人类统一共存的理想，或者法农强调的、同时也包容民族认同和角色的理想国际主义。
====

- (093.) In which of the following does the author of the passage reinforce 加强；巩固 his criticism of responses such as Isaacs’ to *Raisin in the Sun*? +

[.my1]
.案例
====
- (093.) In which of the following does the author of the passage reinforce his criticism of responses such as Isaacs’ to Raisin in the Sun?

文章作者在下列哪一项中强化了他对诸如艾萨克斯对《烈日下的葡萄干》的回应的批评？
====

- (094.) Inheritors 继承者 of the viewpoints of early twentieth-century Progressive historians such as Beard and Becker, these recent historians have put forward arguments that deserve evaluation 评价；评估. +

[.my1]
.案例
====
- (094.) Inheritors of the viewpoints of early twentieth-century Progressive historians such as Beard and Becker, these recent historians have put forward arguments that deserve evaluation.

这些新近的历史学家继承了20世纪早期进步派历史学家（如比尔德和贝克尔）的观点，提出了值得评估的论点。
====

- (095.) Despite these vague 模糊的；不明确的 categories, one should not claim unequivocally 明确地；毫不含糊地 that hostility 敌意；敌视 between recognizable classes cannot be legitimately 合理地；正当地 observed. +

[.my1]
.案例
====
- (095.) Despite these vague categories, one should not claim unequivocally that hostility between recognizable classes cannot be legitimately observed.

尽管存在这些模糊的类别，但我们不应断然宣称，可识别阶级之间的敌意不能被合法地观察到。
====

- (096.) Yet those who stress the achievement of a general consensus 共识 among the colonists cannot fully understand that consensus without understanding the conflicts 冲突 that had to be overcome or repressed 压制；抑制 in order to reach it. +

[.my1]
.案例
====
- (096.) Yet those who stress the achievement of a general consensus among the colonists cannot fully understand that consensus without understanding the conflicts that had to be overcome or repressed in order to reach it.

然而，那些强调殖民者之间达成普遍共识的人，如果不了解为了达成这一共识而必须克服或压制的分歧，就无法完全理解这个共识。
====

- (097.) It can be inferred from the passage that the author would be most likely to agree with which of the following statements regarding socioeconomic 社会经济的 class and support for the rebel 反叛者 and Loyalist 保皇党 causes during the American Revolutionary War? +

[.my1]
.案例
====
- (097.) It can be inferred from the passage that the author would be most likely to agree with which of the following statements regarding socioeconomic class and support for the rebel and Loyalist causes during the American Revolutionary War?

从文章中可以推断出，关于社会经济阶层以及美国独立战争期间对叛军和保皇派事业的支持，作者最可能同意以下哪项陈述？
====

- (098.) She wished to discard 抛弃；放弃 the traditional methods and established vocabularies 词汇 of such dance forms as ballet 芭蕾舞 and to explore the internal sources of human expressiveness 表现力. +

[.my1]
.案例
====
- (098.) She wished to discard the traditional methods and established vocabularies of such dance forms as ballet and to explore the internal sources of human expressiveness.

她希望摒弃芭蕾等舞蹈形式的传统方法和既定词汇，转而探索人类表现力的内在源泉。
====

- (099.) Although it has been possible to infer from the foods and services actually produced what manufacturers 制造商 and servicing trades 服务行业 thought their customers wanted, only a study of relevant personal documents written by actual consumers will provide a precise 精确的；准确的 picture of who wanted what. +

[.my1]
.案例
====
- (099.) Although it has been possible to infer from the foods and services actually produced what manufacturers and servicing trades thought their customers wanted, only a study of relevant personal documents written by actual consumers will provide a precise picture of who wanted what.

尽管可以从实际生产的商品和服务中推断出制造商和服务行业认为他们的客户想要什么，但只有研究实际消费者撰写的相关个人文件，才能提供一份关于谁想要什么的精确图景。
====

- (100.) With regard to 关于 this last question, we might note in passing 顺便提及 that Thompson, while rightly restoring 恢复；使复位 laboring people to the stage of eighteenth-century English history, has probably exaggerated 夸大；夸张 opposition of these people to the inroads 侵犯；侵蚀 of capitalist consumerism 消费主义 in general; for example, laboring people in eighteenth-century England readily shifted from home-brewed 家酿的 beer to standardized 标准化的 beer produced by huge, heavily capitalized 资本化的 urban breweries 啤酒厂. +

[.my1]
.案例
====
- (100.) With regard to this last question, we might note in passing that Thompson, while rightly restoring laboring people to the stage of eighteenth-century English history, has probably exaggerated opposition of these people to the inroads of capitalist consumerism in general; for example, laboring people in eighteenth-century England readily shifted from home-brewed beer to standardized beer produced by huge, heavily capitalized urban breweries.

关于最后一个问题，我们不妨顺便指出，汤普森虽然正确地将劳动人民重新置于18世纪英国历史的舞台，但他可能夸大了这些人对资本主义消费主义普遍侵蚀的反对；例如，18世纪英国的劳动人民很容易就从家酿啤酒转向由大型、资本雄厚的城市啤酒厂生产的标准化啤酒。
====

'''

== pure

- (051.) Some geologists, however, on the basis of observations concerning mantle xenoliths, argue that the mantle is not layered, but that heterogeneity is created by fluids rich in “incompatible elements” (elements tending toward liquid rather than solid state) percolating upward and transforming portions of the upper mantle irregularly, according to the vagaries of the fluids’ pathways.

- (052.) Fallois proposed that Proust had tried to begin a novel in 1908, abandoned it for what was to be a long demonstration of Saint-Beuve’s blindness to the real nature of great writing, found the essay giving rise to personal memories and fictional development and allowed these to take over in a steadily developing novel.

- (053.) The very richness and complexity of the meaningful relationships that kept presenting and rearranging themselves on all levels, from abstract intelligence to profound dreamy feelings, made it difficult for Proust to set them out coherently.

- (054.) But those of us who hoped, with Kolb, that Kolb’s newly published complete edition of Proust’s correspondence for 1909 would document the process in greater detail are disappointed.

- (055.) Now we must also examine the culture as we Mexican Americans have experienced it, passing from a sovereign people to compatriots with newly arriving settlers to, finally, a conquered people--a charter minority on our own land.

- (056.) It is possible to make specific complementary DNAs that can serve as molecular probes to seek out the messenger RNAs of the peptide hormones. If brain cells are making the hormones, the cells will contain these mRNAs. If the products the brain cells make resemble the hormones but are not identical to them, then the cDNAs should still bind to these mRNAs, but should not bind as tightly as they would to mRNAs for the true hormones.

- (057.) The molecular approach to detecting peptide hormones using cDNA probes should also be much faster than the immunological method because it can take years of tedious purifications to isolate peptide hormones and then develop antiserums to them.

- (058.) Nevertheless, researchers of the Pleistocene epoch have developed all sorts of more or less fanciful model schemes of how they would have arranged the Ice Age had they been in charge of events.

- (059.) This succession was based primarily on a series of deposits and events not directly related to glacial and interglacial periods, rather than on the more usual modern method of studying biological remains found in interglacial beds themselves interstratified within glacial deposits.

- (060.) There have been attempts to explain these taboos in terms of inappropriate social relationships either between those who are involved and those who are not simultaneously involved in the satisfaction of a bodily need, or between those already satiated and those who appear to be shamelessly gorging.

- (061.) Many critics of Emily Brontë’s novel Wuthering Heights see its second part as a counterpoint that comments on, if it does not reverse, the first part, where a “romantic” reading receives more confirmation.

- (062.) Granted that the presence of these elements need not argue an authorial awareness of novelistic construction comparable to that of Henry James, their presence does encourage attempts to unify the novel’s heterogeneous parts.

- (063.) This is not because such an interpretation necessarily stiffens into a thesis (although rigidity in any interpretation of this or of any novel is always a danger), but because Wuthering Heights has recalcitrant elements of undeniable power that, ultimately, resist inclusion in all-encompassing interpretation.

- (064.) The isotopic composition of lead often varies from one source of common copper ore to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform isotopic composition of the lead from a single copper-ore source.

- (065.) More probable is bird transport, either externally, by accidental attachment of the seeds to feathers, or internally, by the swallowing of fruit and subsequent excretion of the seeds.

- (066.) A long-held view of the history of the English colonies that became the United States has been that England’s policy toward these colonies before 1763 was dictated by commercial interests and that a change to a more imperial policy, dominated by expansionist militarist objectives, generated the tensions that ultimately led to the American Revolution.

- (067.) It is not known how rare this resemblance is, or whether it is most often seen in inclusions of silicate such as garnet, whose crystallography is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence that the diamonds and inclusions are truly cogenetic.

- (068.) Even the “radical” critiques of the mainstream research model, such as the critique developed in Divided Society, attach the issue of ethnic assimilation too mechanically to factors of economic and social mobility and are thus unable to illuminate the cultural subordination of Puerto Ricans as a colonial minority.

- (069.) They are called virtual particles in order to distinguish them from real particles, whose lifetimes are not constrained in the same way, and which can be detected.

- (070.) Open acknowledgment of the existence of women’s oppression was too radical for the United States in the fifties, and Beauvoir’s conclusion, that change in women’s economic condition, though insufficient by itself, “remains the basic factor” in improving women’s situation, was particularly unacceptable.

- (071.) Other theorists propose that the Moon was ripped out of the Earth’s rocky mantle by the Earth’s collision with another large celestial body after much of the Earth’s iron fell to its core.

- (072.) However, recent scholarship has strongly suggested that those aspects of early New England culture that seem to have been most distinctly Puritan, such as the strong religious orientation and the communal impulse, were not even typical of New England as a whole, but were largely confined to two colonies of Massachusetts and Connecticut.

- (073.) Thus, what in contrast to the Puritan colonies appears to Davis to be peculiarly Southern--acquisitiveness, a strong interest in politics and the law, and a tendency to cultivate metropolitan cultural models--was not only more typically English than the cultural patterns exhibited by Puritan Massachusetts and Connecticut, but also almost certainly characteristic of most other early modern British colonies from Barbados north to Rhode Island and New Hampshire.

- (074.) Portrayals of the folk of Mecklenburg County, North Carolina, whom he remembers from early childhood, of the jazz musicians and tenement roofs of his Harlem days, of Pittsburgh steelworkers, and his reconstruction of classical Greek myths in the ancient Black kingdom of Benin, attest to this.

- (075.) A very specialized feeding adaptation in zooplankton is that of the tadpolelike appendicularian who lives in a walnut-sized (or smaller) balloon of mucus equipped with filters that capture and concentrate phytoplankton.

- (076.) These historians, however, have analyzed less fully the development of specifically feminist ideas and activities during the same period.

- (077.) Apparently most massive stars manage to lose sufficient material that their masses drop below the critical value of 1.4M before they exhaust their nuclear fuel.

- (078.) This is so even though the armed forces operate in an ethos of institutional change oriented toward occupational equality and under the federal sanction of equal pay for equal work.

- (079.) An impact capable of ejecting a fragment of the Martian surface into an Earth-intersecting orbit is even less probable than such an event on the Moon, in view of the Moon’s smaller size and closer proximity to Earth.

- (080.) Not only are liver transplants never rejected, but they even induce a state of donor-specific unresponsiveness in which subsequent transplants of other organs, such as skin, from that donor are accepted permanently.

- (081.) As rock interfaces are crossed, the elastic characteristics encountered generally change abruptly, which causes part of the energy to be reflected back to the surface, where it is recorded by seismic instruments.

- (082.) While the new doctrine seems almost certainly correct, the one papyrus fragment raises the specter that another may be unearthed, showing, for instance, that it was a posthumous production of the Danaid tetralogy which bested Sophocles, and throwing the date once more into utter confusion.

- (083.) The methods that a community devises to perpetuate itself come into being to preserve aspects of the cultural legacy that that community perceives as essential.

- (084.) Traditionally, pollination by wind has been viewed as a reproductive process marked by random events in which the vagaries of the wind are compensated for by the generation of vast quantities of pollen, so that the ultimate production of new seeds is assured at the expense of producing much more pollen than is actually used.

- (085.) Because the potential hazards pollen grains are subject to as they are transported over long distances are enormous, wind-pollinated plants have, in the view above, compensated for the ensuing loss of pollen through happenstance by virtue of producing an amount of pollen that is one to three orders of magnitude greater than the amount produced by species pollinated by insects.

- (086.) For example, the spiral arrangement of scale-bract complexes on ovule-bearing pine cones, where the female reproductive organs of conifers are located, is important to the production of air flow patterns that spiral over the cone’s surfaces, thereby passing airborne pollen from one scale to the next.

- (087.) Friedrich Engels, however, predicted that women would be liberated from the “social, legal, and economic subordination” of the family by technological developments that made possible the recruitment of “the whole female sex into public industry”.

- (088.) It was not the change in office technology, but rather the separation of secretarial work, previously seen as an apprenticeship for beginning managers from administrative work that in the 1880s created a new class of “dead-end” jobs, thenceforth considered “women’s work”.

- (089.) The increase in the numbers of married women employed outside the home in the twentieth century had less to do with mechanization of housework and an increase in leisure time for these women than it did with their own economic necessity and with high marriage rates that shrank the available pool of single women workers, previously, in many cases, the only women employers would hire.

- (090.) For one thing, no population can be driven entirely by density-independent factors all the time.

- (091.) In order to understand the nature of the ecologist’s investigation, we may think of the density-dependent effects on growth parameters as the “signal” ecologists are trying to isolate and interpret, one that tends to make the population increase from relatively low values or decrease from relatively high ones, while the density-independent effects act to produce “noise” in the population dynamics.

- (092.) But the play’s view of Black self-esteem and human solidarity as compatible is no more “contradictory” than Du Bois’ famous, well-considered ideal of ethnic self-awareness coexisting with human unity, or Fanon’s emphasis on an ideal internationalism that also accommodates national identities and roles.

- (093.) In which of the following does the author of the passage reinforce his criticism of responses such as Isaacs’ to Raisin in the Sun?

- (094.) Inheritors of the viewpoints of early twentieth-century Progressive historians such as Beard and Becker, these recent historians have put forward arguments that deserve evaluation.

- (095.) Despite these vague categories, one should not claim unequivocally that hostility between recognizable classes cannot be legitimately observed.

- (096.) Yet those who stress the achievement of a general consensus among the colonists cannot fully understand that consensus without understanding the conflicts that had to be overcome or repressed in order to reach it.

- (097.) It can be inferred from the passage that the author would be most likely to agree with which of the following statements regarding socioeconomic class and support for the rebel and Loyalist causes during the American Revolutionary War?

- (098.) She wished to discard the traditional methods and established vocabularies of such dance forms as ballet and to explore the internal sources of human expressiveness.

- (099.) Although it has been possible to infer from the foods and services actually produced what manufacturers and servicing trades thought their customers wanted, only a study of relevant personal documents written by actual consumers will provide a precise picture of who wanted what.

- (100.) With regard to this last question, we might note in passing that Thompson, while rightly restoring laboring people to the stage of eighteenth-century English history, has probably exaggerated opposition of these people to the inroads of capitalist consumerism in general; for example, laboring people in eighteenth-century England readily shifted from home-brewed beer to standardized beer produced by huge, heavily capitalized urban breweries.

'''
