= 1573
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 268.
This is English as a Second Language Podcast’s English Café episode 268. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this episode. The learning guide will help you improve your English even faster – and help you lose weight. Yes, it will!
On this Café, we’re going to continue our series on famous American authors (writers), focusing on a very popular modern writer, Stephen King. Then we’re going to talk about we’re going to talk about traffic school, ways for people in the United States to learn how to become better drivers, and more importantly, to help them once they have broken the driving laws. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on famous American authors. Today we are going to talk about Stephen King, who writes horror novels. “Horror” (horror) is one “genre,” one type of writing, just like romance and mystery are genres. We use the French word (genre). Horror novels are designed to scare the reader, and that’s exactly what Stephen King’s novels do; they make you frightened.
Stephen King was born in 1947 in Portland, Maine. Maine is in the very northeast corner of the United States, with the border on its north of Canada. It is on the Atlantic Ocean, a beautiful state. King, as a young boy, enjoyed reading horror “comics” or little books that have drawings as well as words. He began writing horror stories, and the first one he wrote was published when he was just 18 years old. He studied English at college and planned to teach high school English, but he wasn’t able to find a teaching job right away. Maybe he scared the people who were going to hire him! So instead, he wrote short stories and sold them to magazines to make money for himself and his family, and that’s how he started in his career as a writer.
His first full novel – his first writing that wasn’t just a short story but was a complete novel – was accepted for publication in 1973, meaning King was at this time only 26 years old. It was called Carrie, and it’s about a teenage girl named Carrie who has psychic powers. The word “psychic” (psychic), it comes from a Greek word, refers to things that are done with the human mind – I should say supposedly done with the human mind that cannot be explained by science. Psychic powers have been used, or people have said they have been used to read what other people are thinking; that is, to see and know what someone else is thinking. Some people believe that psychic powers can help them see the future – see what will happen in the future, or even make things move, like a cup on the table. Some people believe that psychic powers can help you move objects. I say “some people” in the way that we might say some people believe dogs can talk. Probably there are some people like that! My wife actually says I am the opposite of being psychic (I don’t know what that would be called – anti-psychic, non-psychic perhaps) since I can never tell what she is thinking, so I must be the anti-psychic.
Anyway, Carrie, this novel by Stephen King, is about a girl who is often teased by her classmates, meaning the boys and girls she goes to school with make fun of her. “To tease” is to make fun of someone. They tease her when they find out she has psychic powers. Well, she uses these powers for revenge. “Revenge” (revenge) is a way of fighting back, of getting back at, we would say, her classmates. If someone does something bad to you, you may want to get revenge; you want to do something bad to them. That is unfortunately part of our natural human reaction sometimes. Well, Carrie uses her psychic powers to hurt her classmates, because they have hurt her in many ways.
Stephen King writes novels like this, scary novels, novels that are very frightening. Many of his novels have become movies, including his first novel Carrie. In total, Stephen King has written 49 novels since 1972. I think he has a new one even, it might be 50. That’s in the last 38 years, so he’s written almost 50 novels in 38 years, or more than one novel a year – which is 49 more than I have written! Two other famous novels you may have heard of are The Shining and It. The Shining is about a hotel that is evil – that is very bad. And, the powers in this hotel try to control people who are staying there. It was made, this novel, into a movie – very famous movie with the great actor Jack Nicholson. The other novel, It, is about a person who becomes a monster, who can change appearances to become whatever people and especially children are most afraid of. So if you’re most afraid of…I don’t know…dogs or cats, it will turn into the shape or the appearance of a dog or cat. Most of the time in the novel this person looks like a clown. A “clown” is someone who dresses up in very brightly colored clothes. Normally a clown has big shoes, lots of hair, and a big red nose. Clowns try to make people laugh, especially children at circuses and fairs. But some people, I guess, are afraid of clowns, so in the novel one of the things that this monster looks like often is a clown.
Stephen King also wrote a series of books called The Dark Tower. A “series” is a group of related things that come in a particular order: first, second, third, and so forth. A television series refers to a program that has different episodes that come in a certain order. A series of books would be books that are related to each other, that you start with book one and you continue on to the next and then the next. There are many series of books like this, the Harry Potter series for example.
The Dark Tower combines the horror genre, in other words it tries to scare people, with the western genre. Westerns are books about the American West, especially in the 19th century. The Dark Tower is about a man who is looking for a tower that is supposed to be the center of the universe. A “tower” is a tall, like a building that you climb on top of – climb up either to see a long distance or perhaps to defend yourself, like in a war. Tower can also just be a very tall building. In New York, the World Trade Center that was attacked on 9/11 was called the Twin Towers; there were two large buildings. There are seven books in The Dark Tower series written over 27 years. In other words, from the first one to the seventh one there were 27 years that passed. In 2009 Stephen King announced he was working on an eighth book in that series, so it isn’t finished yet.
As I mentioned, many of Stephen King’s books have been made into movies, including the novels I mentioned earlier. The Dark Tower, however, has not. The movies that have been made generally “follow the books” pretty closely, meaning that the story in the movie is pretty close to the story in the book – but not always. Honestly, it’s hard to say whether it is scarier to read Stephen King’s novels or watch his movies. I, myself, am not a big fan of horror books, horror novels, and horror movies. I don’t really like them very much; I think life is scary enough! But many people love Stephen King; he is a very good storyteller.
Not all of his novels, or at least not all of his stories have been horror stories. He wrote a story called The Body, which was made into a movie called Stand by Me way back in 1986. It was not a horror movie; it was actually a very good movie about boys growing up – maturing, becoming men, or at least trying to.
Stephen King has received many awards for his work. In 2003 he received a lifetime achievement award from the National Book Awards in the United States. A “lifetime achievement award” recognizes someone who has made important contributions – has done great things in a particular area over his or her entire lifetime. It isn’t just for one book or one thing that the person did. This is an award that some organizations give to people who perhaps have not won award for their individual work. Some people were not happy that the National Book Awards gave him a lifetime achievement award. King is a very popular novelist, but he’s not considered a great literary writer – he’s not considered one of the best writers in English for example. Some people think the awards should only go to those who have more literary style versus someone like King, who is very popular and makes a lot of money.
King’s work has been very important in American culture in the last 30-40 years, and if you haven’t read one of his novels you might give it a try.
Now let’s turn to our next topic, which is traffic school. “Traffic” normally refers to the number of cars on the road. Here in Los Angeles, for example, there is always a lot of traffic on the freeway, meaning there are lots of cars on the highway – on the freeway. Traffic is bad especially in the morning, when people are going to work, what we call rush hour, and in the evening when people are coming back home from work, which is also another rush hour.
“Traffic school” is a program that is supposed to help people become better, safer drivers after they have done something wrong – after they have broken a driving law. Don’t confuse traffic school with “driver’s ed,” or driver’s education. Driver’s education is a course you take before you get your driving license to teach you how to drive. In many states you are required to take a class, especially if you are under the age of 18.
Traffic school is different because it’s designed for people who already have a driver’s license, but broke the law. Maybe they were speeding, for example. “Speeding” is when you are going faster than you are supposed to. Or perhaps they ran a red light. “To run a red light” means that you go through an intersection, where two streets cross, even though the light says stop.
Many states in the United States have what’s called a point system for traffic violations, when you break the law. Each time you break the law, and get caught of course, you are given a certain number of points that is based on how serious the violation was. Once you have a certain number of points – if you keep violating the law, keep getting what we call traffic tickets (which are punishments; fines) you can “lose your driver’s license,” meaning the state will take it away your driver’s license completely.
The number of points you have for traffic violations also affects how much you pay for auto insurance, or car insurance. Insurance companies will charge you more money if you have traffic violations, because you are considered an unsafe or dangerous driver.
What happens when you get a ticket for let’s say speeding is that the government will send you a letter telling you that you need to pay a certain amount of money, or the police officer will give you that information. It also gives you the opportunity to have that point removed from your driving record. The way you do that is by agreeing to go to traffic school. When you go to traffic school you have to pay money for the school in addition to the money you pay for the government. However, people do it because it will keep their car insurance lower – the amount they have to pay lower. It also removes that violation point from your “driving record,” the official record or report of how many violations you have.
In most states you need to go to a traffic school for eight hours, or the equivalent. This means that sometimes you go to an actual school, usually on a Saturday or a Sunday, and you have to sit in class for eight hours, and take a test often, and then you’re done. You can also take, in some states, a course by correspondence. A “correspondence course” is when you don’t go anywhere to a class. They send you a book or they send you a DVD, and you have to take a test after reading the book or watching the DVD. Or, you can do it online, over the Internet. Internet courses are now very common.
When I had a traffic violation – and yes, I have broken the law – I got a ticket. That is, I was penalized – I was punished for driving too fast, for speeding. Not that much faster, really. I mean, I think the speed limit was 35 miles an hour and I was driving 40 miles an hour, maybe 45 – okay, no more than 50 miles an hour! Anyway, I did not go to traffic school; I did not go on the Internet. I found the easiest way was to take a correspondence course, where they sent me the book and they sent me the test. I took out the test, I answered all the questions I knew without looking at the book, then I went into the book and I found the sections – the places where the answers for the other questions were, and I completed the test. It took me maybe an hour and a half instead of eight hours. So, if you’re ever in California and you live here and you want to go to traffic school but you don’t want to spend eight hours, you can take a correspondence course.
Traffic schools are private businesses; the government does not run the traffic schools, they just approve the traffic schools. You have to fill out an application – you have to send documents to the government to prove that you have a real school – a real traffic school.
There are many different kinds of traffic schools. They have comedy traffic schools that try to make the presentation as funny as possible. The instructors – the teachers tell jokes while they are teaching about driver safety. A friend of mine went to one of these and said that wasn’t very funny.
Now let’s answer a few of your questions.
Our first question comes from Mehrdad (Mehrdad) in Iran. The question has to do three words: “cost,” “charge,” and “fee.” All three of these words can refer to the price that you pay for something – how much money you pay, but there are differences in how they are used.
“Cost” (cost) is the amount of money you pay, but it could also be other things such as your time or your energy. You can ask, “What is the cost of this coat?” How much money do I need to pay to buy it? “Cost” could refer to time: “This job cost me a lot of time on the weekends.” I have to spend a lot of time on the weekends. Notice we use the verb “to spend” for some things other than money, especially time. So “cost” can be the price, but the price isn’t always in money. “Cost” can be a noun or a verb.
“Charge” is also used to indicate the price that you pay for something. Usually the word “charge” is used for, for example, going to a museum, or going to a school: “How much does the school charge for its tuition?” “How much does the museum charge in order to go inside (to get admission to the museum)?” “Charge” can be a verb as well as a noun: “The charge is five dollars.” We often use this verb when we are talking about using our credit cards: “I’m going to charge this purchase.” I’m going to use my credit card to pay for it.
“Fee” (is only a noun, it cannot be a verb) means the price you pay, just like “charge,” but often for specific kinds of things, education for example. I mentioned how much a school charges, but we could also say, “How much are their fees?” We use the word “fee” to indicate the price of professional services as well. Going to a lawyer or going to an accountant, we talk about their fees. We could talk about doctors’ fees, how much your doctor charges you – how much money you have to pay for his or her services.
To review, “cost” and “charge” are verbs and nouns; “fee” is just a noun. “Cost” refers to the price you pay for something, but it could be something other than money that you are using to pay that price. “Charge” is used, for example, at stores or at museums to indicate the price you are paying for something. “Fee” is specifically used for certain professional services, also many government services have a fee. If you want to go and use one of our national parks, you sometimes have to pay a fee. That’s the amount of money you have to pay to get into the park.
Our next question comes from Isabel (Isabel) in Spain. Isabel wants to know the meaning of an expression she read: “in a New York minute.” The phrase “in a New York minute” means in a very short amount of time, very quickly, the shortest amount of time you can imagine. Why do we say “a New York minute”? Well, many people believe that people who live in New York City are always in a hurry, always running, are very impatient, want things to happen right away. So that is the idea of something happening quickly.
Finally, Bahador (Bahador), also in Iran, wants to know how we use the word or the phrase “a couple.” “A couple” refers to two; it could be more however. “There are a couple of people here for the party.” That could be two, it could be three, it could be five; it depends on the situation. It’s a little confusing because sometimes “couple” means only two. For example: “The couple is getting married this fall.” We’re talking about two people only – at least in the United States! But, we also use it to mean a small number: “Can I have a couple of French fries?” You don’t mean necessarily two; it could be three, it could be 10. Hopefully it doesn’t mean 50! You could say, “My friend lives a couple of miles from here.” Again, we’re not certain exactly the number, but we mean not too far.
Sometimes people use this expression when they don’t want to tell someone the specific number: “How many beers did you drink?” “Oh, a couple.”
In written English “a couple” is normally followed by the preposition “of.” “How long will take to get there?” “A couple of hours.” But in informal spoken English, sometimes the “of” is dropped – is eliminated, or is pronounced more like an “a”. “I need a couple a dollars to go to the movie.” Or, “I need a couple minutes to get dressed.” There, you hear either an “a” or nothing at all between the word “couple” and the unit that you are talking about – hours, minutes, miles, etc. In written English, however, it’s always best – safest, so that people understand you, to put an “of” after the word “couple.”
If you have a couple of questions that you want to ask us, you can email us. There’s no charge! Our email is eslpod@eslpod.com. We can’t promise we’ll answer in a New York minute, but we’ll try to answer as quickly as we can here on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, won’t you, on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
horror – a category of books and entertainment designed to frighten; scary books or movies
* Jeannie likes going to theaters to see horror movies, but her sister is too afraid to go.
psychic – things done with the human mind that cannot be explained by science, such as being able to read other people’s minds or move objects with one’s mind
* If I were psychic, I could read my wife’s mind and find out what she really wants for a birthday present.
clown – a person who entertains children, dressing up in brightly colored clothes and big shoes, with a lot of curly hair and a red nose
* The children had a fun time at the birthday party, eating cake and watching the clown perform.
series – a group of related things that appear in a particular order, such as television shows or books
* All of Seth’s friends have read the Harry Potter series and can’t wait to see all of the movies based on the books.
to follow the book – for the story in a show or movie to be very similar to the story it is based on in a book
* I’m glad the movie didn’t follow the book. The movie had a much better ending!
lifetime achievement – an award recognizing someone who has made important contributions in a particular field over his or her entire lifetime, rather than recognizing the importance of a single contribution by that person
* My favorite actor has been in dozens of great movies and finally received an award for lifetime achievement.
traffic school – a program that helps people become better, safer drivers after they have broken a driving law
* Josopho got a ticket for running a stop sign and had to go to traffic school.
driver’s ed – driver’s education; an optional course that people can choose to take when they are learning how to driver
* Did you take driver’s ed in high school, or did your parents teach you how to drive?
to speed – to drive faster than the law allows; to drive faster than the speed limit
* It’s dangerous to speed on this narrow road. Please slow down!
to lose (one’s) driver’s license – for the state to take away one’s driver’s license as punishment for breaking driving laws
* If you’re caught driving while you’re drunk, you may lose your driver’s license.
driving record – an official report of how many times the driver has violated traffic laws
* Cecil’s driving record shows that he’s a careful driver.
correspondence course – a course that allows students to use workbooks and tests that are mailed between the student and the institution offering the course, instead of requiring the student to attend classes
* People living far from large cities with colleges and universities may chose to take correspondence courses to complete their college education.
cost – a price to pay, usually in money, but sometimes also in other things such as time or energy
* The cost of driving cars and operating factories is poor air quality.
charge – a price to pay
* What will you charge for fixing these shoes?
fee – a price to pay, usually for law, education, or professional services
* Tom wanted to sue his neighbor in court, but was afraid that the lawyer fees would be too high.
in a New York minute – in an extremely short period of time; in an instant; in the shortest amount of time one can imagine
* It won’t take more than a New York minute for me to get ready for the party.
couple – two; a few; several
* Do you have a couple of minutes to look at these proposals before the meeting?
What Insiders Know
The AFI’s Top 10 Most Thrilling Movies (2001)
A “thrill” is a feeling of sudden excitement, and many people look for thrills in their free time. Some people go “skydiving,” jumping out of airplanes with a “parachute” (a large piece of cloth worn on one’s back as one falls from a high place, so the air can push against it and allow a person not to hit the ground too hard and be harmed) for a thrill. Others drive their cars or ride their motorcycles at high speeds down a road for a thrill. But do you like to go to the movies for a thrill?
If you do, you might be interested in the American Film Institute’s 2001 list of the Top 10 Most Thrilling Movies. The American Film Institute, the AFI, is an independent “non-profit” (not intended for making money) organization that was created with money from the government for the “arts” (such as creating paintings, dance, music, and more).
On the top of the list is the movie Psycho directed by Alfred Hitchcock, about a woman who visits a “motel” (inexpensive hotel) and finds a very frightening man “running” (operating) it. The second movie on the list is Jaws, a 1975 movie about a very large “shark” (large fish with sharp teeth) near a popular “beach” (a place next to an ocean with sand).
Below is the full list of the 10 movies. Turn on your television and “hold on to your hats” (get ready for something exciting)!
Psycho (1960)
Jaws (1975)
The Exorcist (1973)
North by Northwest (1959)
The Silence of the Lambs (1991)
Alien (1979)
The Birds (1963)
The French Connection (1971)
Rosemary’s Baby (1968)
Raiders of the Lost Ark (1981)