= 1569
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 264.
This is English as a Second Language Podcast’s English Café episode 264. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California in the United States of America.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for our episodes that contain all the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this entire episode.
This episode is going to be dedicated to – that is, we are going to talk about a well-known American movie called On the Waterfront. Then we’ll continue our series on famous songs in the history of the U.S., focusing on “Swing Low, Sweet Chariot.” And, as always, we’ll answer a few of your questions. Let’s get started.
We begin our Café with a discussion of a famous movie called On the Waterfront. A “waterfront” (waterfront – one word) is simply a piece of land next to some water; it could be a lake, it could be a river, it could even be the ocean although we might more commonly say the oceanfront. So, the waterfront is some land next to water, usually there are a lot of ships or boats that are used for shipping – that is, sending things from one place to another.
On the Waterfront is a 1954 American film, or movie, about mob violence and “corruption,” or dishonest behavior by government officials. A “mob” (mob) could be a large group of people, especially a group of people who are very angry, and perhaps will “resort to,” or will use, violence to get what they want. A mob can also refer to a group of people who are working on some illegal activities together. The mob in the United States has an association with the Italian Mafia (Mafia). The mob and the Mafia are often used to mean the same thing; it’s an organized group of criminals. Nowadays, there are many organized groups of criminals, but we tend to use the word “gang” (gang), but the idea is very similar. They’re group of people who are organized who are committing illegal acts: they’re selling drugs, they’re involved in prostitution, and so forth.
On the Waterfront is a movie about mob or Mafia violence and corruption among government officials and others, especially among a group of dockworkers. A “dock” (dock) is something that you build on a lake or an ocean that goes out into the water so you can walk on it. It also allows you to have boats or ships come in and park alongside the dock so you can take things on and off the ship. Well, a “dockworker” is someone who works on these docks “loading,” or putting things on a ship, and “unloading,” taking things off the ship. The movie was filmed on the actual waterfront of the city of Hoboken in the state of New Jersey, which is on the east coast of the United States next to the state of New York.
New Jersey has a reputation for having mob or Mafia problems. In fact, there was a popular television show just a few years ago called The Sopranos about a Mafia family – a mob family – in New Jersey. So, New Jersey sort of has a bad reputation for that sort of thing. I’m afraid the reputation of New Jersey has not improved even though the show The Sopranos is no longer being shown. There’s a new show called Jersey Shore. The “shore” is similar to the waterfront; it’s what’s next to a lake or an ocean. Jersey Shore is about some young, mostly Italian American teenagers and 20-somethings – people in their 20s who do all sorts of crazy things and…well, it’s not really worth talking about. But, it does show that New Jersey continues to have a bad reputation.
In the movie On the Waterfront the plot of the story is based on a long series of articles written for a New York newspaper, the New York Sun. There were 24 articles written. “Articles” are stories that appear in the newspaper. The series on corruption – on mob corruption in New Jersey won the 1949 Pulitzer Prize, which is a prize given to the best writing in journalism for newspapers – at that time, newspapers and magazines.
The movie follows the story of one person, a union boss by the name of Johnny Friendly, who also works for the mob. Now, a “union” is a group of people – workers – who get together and organize themselves so that they can fight for their rights; they can try to get better pay and better treatment by the people who hire them – by their employers. Johnny Friendly is a “boss” or a leader in the union. He controls the dockworkers’ union. “Unions” are typically, although not always, formed for a particular kind of work. So, there might be a union for automotive, or car workers; in fact, there is. So, this is a union that is “centered on,” or that is concerned with dockworkers. Johnny Friendly, the union boss in the movie, is also suspected of working for the Mafia – for the mob – and having ordered the murder of people who created problems for the mob. None of the people who know of Johnny Friendly’s bad “deeds,” or things he has done, want to talk about it because they’re afraid they might be killed for sharing or giving information to the police. A “deed” (deed) is just something you have done. You could have good deeds or you could have bad deeds. Well, Johnny Friendly definitely had a lot of bad deeds. He is “suspected,” that is we think but we’re not sure he has ordered the murder of several people.
The main character in the moving, however, is Terry Malloy, played by the famous actor Marlon Brando. Malloy is a dockworker, and his brother is Johnny Friendly’s lawyer – his attorney. In the movie, Friendly uses Malloy for his bad deeds and lies to him many times. So, Friendly is using Terry Malloy to do bad things for him. Malloy allows this, or lets it happen for a long time, but then begins to get a conscience, we might say, or his conscience starts to bother him – your “conscience” is that part of you that tells you what is right and wrong – and Malloy considers becoming a whistleblower. A “whistle (whistle) blower” (one word) is a person who tells the police or the government or perhaps a newspaper about something bad or Illegal that is happening, usually with the people that he is working with. A “whistle” is something that makes a very high, loud noise to get people’s attention. And so a whistleblower – we talk about blowing the whistle; that’s how you make the noise, you blow air into it – a whistleblower is someone who is getting people’s attention about something that is illegal or something not according to the rules.
In the movie, which made Brando famous in the United States, Terry Malloy considers testifying before a commission. A “commission” is a group of people, usually government officials, who are trying to figure out what to do about a problem or what the problem is. “To testify” means to go to some official commission or a judge and tell what you know – tell the truth. So, Terry Malloy is thinking about testifying before a commission that is investigating the mob and the Mafia corruption on the waterfront among the dockworkers union.
There’s one particular part of the movie – scene in the movie that is very famous, where Brando is sitting in the back of a car and he’s talking about the mistakes that he’s made and how he really wanted to be successful in life. But instead, he’s committed these crimes – he’s done these bad things – and of course now he wants to try to make things better. Brando’s character, I should also say, was a boxer, and one of the things he does wrong is he goes to a boxing match – a competition – and he purposely allows the other person to win. We would say he “throws the match,” that is he loses on purpose, usually because of the way that someone is betting money on the other person. This is one of the things that he does that he is sorry for. In one of the movie’s most famous scenes, as I was saying, you hear Terry saying, “I could’ve had class. I could’ve been a contender. I could’ve been somebody instead of a bum, which is what I am.” A “contender” is someone who’s very good at a particular thing, usually sports. In this case, for Terry, boxing. He could have been a good boxer, but instead he did what his mob boss Johnny Friendly wanted, and he now calls himself a bum (bum). In American English, a “bum” is someone who doesn’t have a job or someone who is not very ethical – someone who does things wrong, someone who’s not a very nice person. It’s a very negative way to describe someone. The way that Brando, in his very unique way of talking, delivers those lines – says those words – makes that scene in the movie especially powerful.
The movie’s director, Elia Kazan, actually had a similar experience in his own life. In 1952, two years before the movie was “released,” or was made available to see, Kazan “testified,” or spoke about his experiences, in front of an official U.S. government committee that was trying to identify what were called then un-American activities. “Un-American” would be things that people would do to try to hurt the United States. You may remember during the 1950s in the U.S. there was a lot of concern about communism and communist influence in the American government as well as in the American film industry here in Hollywood. Kazan identified, in front of this commission, several people he thought were communists. Like the character Terry Malloy in the movie he felt that he needed to do this. Kazan made a lot of enemies here in Hollywood in the entertainment industry, and many people never forgave him for testifying in front of that committee.
Despite his unpopularity, the movie did win several awards. It received, in fact, eight what we call Oscars, or Academy Awards, which are given to the best movies of the year. It won the award for Best Actor, for Best Director, and for Best Picture, or movie, of the year.
I don’t want to give away the ending. The phrase “to give way the ending” means to let someone know what happens at the end of a movie or a television show that he or she hasn’t seen yet. I’m not going to give away the ending of the movie if you haven’t seen it, but I would recommend, if you can, to see this movie. It’s a classic; it’s one of the great movies of the 1950s. The soundtrack, if you like music, was written by Leonard Bernstein, one of the most famous American conductors and composers of the 20th century. I should also mention that Marlon Brando, as some of you may know, also starred in a movie about the Mafia 20 years later in the early 1970s. The movie was called The Godfather, and I think we talk about that movie in Café number 232.
I’m going to move on now to our section on famous songs. Today we’re going to talk about a spiritual or religious song that is famous here in the U.S. called “Swing Low, Sweet Chariot.” It’s a sad song about the difficulties that people have in life and the promise of life after they die – life in “heaven,” where in many religions you go if you are a good person. If you’re not a good person, then you go to hell – or New Jersey, whichever is closer!
The song was traditionally sung by African Americans, or blacks, who were living in the United States. The African Americans were, of course, slaves during much of the early history of the U.S. – they were property belonging to other people – who had so many difficult experiences, but also created some very powerful, some very beautiful songs about those experiences. “Swing Low, Sweet Chariot” is one of those. Many people find listening to the song can be very uplifting. “Uplifting” is something that gives you hope, something that lifts or raises you up – raises up your spirits, we might say; makes you feel happier.
“Swing Low, Sweet Chariot” was written in the mid-1800s by a man named Wallis Willis – something of an odd name – who was a slave in the state of Oklahoma, which is in the central part of the U.S. A “slave,” as I mentioned earlier, is someone who is owned as property and forced to work without receiving money. A “minister,” a religious leader, at a school in Oklahoma heard Willis singing this song in the 1860s and later wrote the song down. He gave the song to other people, and later it became famous across the United States. I would say even today most Americans know or have heard of this song. It is sometimes sung in church services – religious services.
I’ll try to sing part of the song, but I’m not going to be able to do it justice. The phrase “to do (something) justice” means to do something well enough to match the original beauty or the original high quality of the thing. This is a beautiful song and I would need a much more beautiful singing voice to do it justice. But I’ll try my best. Here’s the main part of the song, what we call the “chorus” (chorus), that’s the main part of the song that repeats many times. The chorus goes:
Swing low, sweet chariot
Coming for to carry me home,
Swing low, sweet chariot,
Coming for to carry me home.
A “chariot” (chariot) is a special kind of vehicle; it’s like a small box that you can stand in. It has two wheels on either side, and it is pulled usually by one or two horses. You can ride in the back of it. Chariots were used in ancient Rome; they were used for races – competitions. You would have races around a circle. The idea here in the song, however, is that there is a chariot that takes you, after you die, from earth to heaven. It’s sort of like a means of transportation. So, the sweet chariot that he’s singing about is the chariot that will take him, what he says, home. He means heaven, since he believes that’s where he belongs – that’s where he really should be.
He says, “Swing low, sweet chariot.” To “swing low” would mean to go down very close to the ground. “Swing low, sweet chariot. Coming for to carry me home.” It sounds ungrammatical; it’s a poetic way of saying the reason the chariot is coming is to carry me back home. The singer is ready to die and wants the heavenly angels – the heavenly beings to come down in their chariots and swing low close to the ground to pick him up and take him to heaven. He believes he is bound for heaven. To be “bound (bound) for (somewhere)” means to be going in a certain direction, and that’s the direction he wants to go.
Some people say that “Swing Low, Sweet Chariot” is really about something other than going to heaven, that’s it’s about something called the “Underground Railroad,” which was a system – a network of people who were trying to help slaves escape to safer places, and they would hide them in their homes. Some people think “Swing Low, Sweet Chariot” was giving a message to the slaves about this possibility of being able to escape. That’s a difficult thing, however, to prove.
The song became very popular again in the 1960s during the civil rights movement when many African Americans, led by the Reverend Martin Luther King, were fighting to be treated as equals in the United States. Many of the demonstrations – the large groups of people who would come together – would sing songs like “Swing Low, Sweet Chariot.” And as I said, it’s still a song sung in many American churches and is familiar with most Americans. I hope you have a chance to listen to a real version of the song. I’m sure you could find one on YouTube that sounds much better than I.
Now let’s answer some of the questions that you have sent us.
Our first question comes from Rodrigo (Rodrigo) in Venezuela. Rodrigo wants to know the differences between the words “bet” (bet), “wager” (wager), and “gamble” (gamble). Both “bet” and “wager” mean to offer something of value, usually money, on what will happen or how something will end, particularly in a contest. So for example, there’s a baseball game between the Cincinnati Reds and the Los Angeles Dodgers, and one of the players, let’s call him Pete, Pete decides to bet on the game. He goes to someone and says, “I think we’re going to lose and I’m going to give you 100 dollars, and if I’m right you give me 300 back,” or whatever the particular what we would call “odds” are. In many sporting events in the U.S. you can bet on who will win, and if you win then you get more money. This is particularly popular in places such as Las Vegas, where it is legal to bet or wager on things like sports. In many states it is not legal, although people do it anyway. You can bet or wager almost anything; you could bet your car for example if someone was willing to accept that. You can bet on horse races; you can wager on basketball games; there are all sorts of things you can bet or wager.
“Bet” and “wager” can also be nouns, and that refers to what it is you are offering. “How much are you going to bet.” “My bet is 1,000 dollars.” That’s the money I am going to risk in hopes of winning even more money.
“To gamble” can also mean a similar thing as “to bet” or “to wager.” “Gamble” is usually referred more often to the habit of somebody over and over again going to bet or wager on some game, or going to somewhere like Las Vegas where they lose a lot of money – because most people who go to Las Vegas, of course, lose a lot of money!
Now, “gamble” can be more generally used in addition to the betting idea; it can be used to take a chance on something. You gamble with your life if you are talking on the cell phone and driving at the same time. You’re gambling on your life, meaning taking a chance; you are taking a big risk; something could go wrong.
Erika (Erika) in Japan she wants to know the difference between “U.S.” and “U.S.A.” Well, this is a simple one. “U.S.” stands for, or means United States; “U.S.A.” means United States of America. So, “U.S.” is a short form of “U.S.A.” and they both mean the same thing. However, we use “U.S.” as an adjective, whereas we never use “U.S.A.” as an adjective. So you can talk about U.S. cities or U.S. cars, but you cannot say you say U.S.A. cars or U.S.A. cities. That’s not acceptable; you cannot use “U.S.A.” as an adjective.
Sometimes you may hear the expression “the U.S. of A.” This means the same thing, but it’s often used perhaps in a funny way to emphasize that you are talking about the United States of America and not the united states of some other country. It’s sometimes also used when referring to traditional culture or customs in the United States, saying how important they are or perhaps how you don’t want them to change. So it’s sort of a matter of pride sometimes when people say “U.S. of A.” More normally, however, people would just say U.S.A.”
Finally, Oleg (Oleg) in Russia wants to know the meaning of the phrase “can’t help (doing something).” He was listening to a song:
Wise men say only fools fall rush in.
But I can’t help falling in love with you.
Well, not you Oleg! “Wise men say (people who are intelligent say that ) only fools (only idiots) rush in.” In other words, do something quickly without thinking about it. “But I can’t help falling in love with you.” When we say you “can’t help (something) we mean it’s not possible to avoid it; it’s impossible to prevent it. You can also use that in the past tense, “I couldn’t help looking at the beautiful girl across the room” (in the past). She was so beautiful I…it was not possible for me not to look at her.
The song, as many of you may know, is actually from Elvis Presley, or simply Elvis. It was later recorded by another group UB40.
The expression is meant to communicate the idea often that you shouldn’t do something, but it was impossible for you not to do it because of the situation.
If you have a question about U.S. English email us ateslpod@eslpod.com and we’ll try to answer it here on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
waterfront – a piece of land next to water, often where there are a lot of ships or boats that are used for shipping, or sending products from one place to another
* Many sailors like to live near the waterfront to be close to their boat or ship.
mob – a large group of people, especially when they are angry or excited
* There is an angry mob outside demanding to speak to the governor.
union – a group of workers who work together legally to fight against their employer or try to get more money or better working conditions
* The maids in this hotel are part of a union and can’t be fired without a good reason.
deed – an action; something one has done on purpose
* My father used to say that doing good deeds for other people makes you feel better about yourself.
whistleblower – a person who tells the government or the public about something bad or Illegal that is happening and that other people want to keep secret
* Georgina was afraid she would lose her job if she became a whistleblower.
to give away the ending – to let someone know what happens in a story, book, movie, or TV show that he or she hasn’t yet read or seen
* Stop! Don’t give away the ending. I haven’t finished reading that book yet.
uplifting – giving one hope and making one feel happier
* The song Leandro sang at their wedding was beautiful and uplifting.
slave – someone who is owned by another person and forced to work without receiving money
* Many southern U.S. states relied on slaves to do farm work until 1865.
to do (something) justice – to do something well enough to match the beauty or importance of the original thing
* You should tell them the funny thing that happened to us. You’re better at telling a story and I wouldn’t be able to do it justice.
chariot – a special kind of cart or a small box with two wheels that is pulled by two horses that people can ride in
* At the parade, we saw a chariot carrying the mayor and her husband.
to swing – to make a graceful movement through the air, usually from side to side
* In the play, Susanne plays a girl who can fly, so she swings from one end of the stage to the other.
bound – going in a certain direction; trying to reach a particular location while one is moving or traveling
* After you leave Chicago, are you bound for Philadelphia or Washington D.C.?
to bet – to offer something valuable, usually money, on what will happen or how something will end, often in a contest
* Shandra and Malcolm made a bet that each could run faster than the other.
to wager – to offer something valuable, usually money, on what will happen or how something will end, often in a contest
* Are you betting on your favorite team to win? I wagered $30.
to gamble – to play a game for money or other valuables; to take a chance on something
* The card players gambled all night, playing game after game.
U.S. / U.S.A. – United States / United States of America
* The box is addressed to the U.S.A., but it was delivered to Canada by the U.S. Postal Service.
can/could not help – can/could not avoid; can/could not prevent
* When Monica wore high heel shoes for the first time, she couldn’t help but fall down a few times before she found her balance.
What Insiders Know
Popular Drinking Games
In the U.S., friends like to get together at bars or at parties to “socialize” (interact with friends or to make friends). If they are college students or young adults, they sometimes like to play “drinking games,” games that involve drinking alcohol in some way. Many drinking games involve seeing how quickly or how much someone can drink in a short period of time. “Chugging” beer, or drinking beer very quickly and in large amounts, is a common event at “rowdy” (wild and disorderly) parties.
Other drinking games require some skill. Two popular drinking games in the U.S., especially among college students, are “Beer Pong” and “Quarters.” In both of these drinking games, the player must throw or “toss” (throw lightly) something small into a container. In Beer Pong, cups of beer or other alcohol are placed on a table in a “triangle formation” (organization that is shaped with three points). The player takes a “ping-pong ball,” a ball used to play ping-pong or table tennis, and standing some distance from the table, throws it so that it “lands” (falls) into one of the cups. The person or team of people with the fewest “hits” (accurate throws) must drink the beer or alcohol on the table.
Similarly, the game of Quarters requires the player to “bounce” (causing an object to move quickly away from a surface after hitting it) a “quarter” (25-cent coin) off the surface of a table so that it lands in a small container, often a “shot glass” (a small glass used for serving strong alcohol). The person who “misses” (does not throw accurately) must drink the cup of beer or alcohol.
There are many “variations” (different versions) of these games, but the “aim” (goal) is usually the same: Win and you do not need to drink large amounts of alcohol. These games require skill, something difficult to have if you have already been drinking.