= 1565
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 260.
This is English as a Second Language Podcast’s English Café episode 260. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with even more courses in English, and read our ESL Podcast Blog.
On this Café, we’re going to continue our series on famous Americans, discussing the life, career, and what we call stunts of a man named Evel Knievel. We’re also going to explore Colonial Williamsburg, a place in the state of Virginia, why it was important in American history and why it is still important today. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a look at the life, career, and stunts of Evel Knievel. Knievel was very famous when I was growing up in the 1960s and 70s. Knievel was an American motorcycle daredevil. A “daredevil” (daredevil – one word) is a person who takes risks, usually physical risks – things that are physically dangerous, and is always looking for new adventures. It’s a word we don’t use as much now as we did 20-30 years ago. There are still people who are like this, who take risks, but we may call them by some other name. The verb “to dare” (dare) means to challenge someone to do something, often something dangerous. A “devil,” as you may know, is an evil spirit; it’s used more informally to describe a very evil person. A daredevil, however, is not an evil person; a daredevil is a person who likes to take risks.
Well, Evel Knievel was the most famous American daredevil of the 20th century. As I said, he was a motorcycle rider. He became famous for some very specific stunts. A “stunt” (stunt) is a very dangerous action – a dangerous trick. For example, in many movies nowadays you will see actors jumping out of airplanes or doing things that look very dangerous. Well, we call those things that they do “stunts,” and typically they are not done by the actor him or herself, they are done by a professional, what we call a “stuntman” or a “stuntwoman. Evel Knievel did stunts himself – dangerous things – to make himself rich; he got paid to do these stunts.
Knievel was born in 1938. His real name was Robert Craig Knievel. He got a job after high school, but he was fired because he was driving one of the machines he was using. He drove it in a way that was very dangerous, he did something we call “popping a wheelie” (wheelie). “Wheelie” comes from the word “wheel,” which are, of course, the rounds things on a car or truck or machine that allow you to move. Well, “to pop a wheelie” means to lift the front wheel of the vehicle, typically something like a motorcycle or a bike, off the ground while you are riding it, so you are riding on only one wheel. This, of course, can be dangerous. When Evel Knievel popped a wheelie the first time at work he caused damage and was actually put in jail.
In jail, he was in the same room – we would call it a “cell” (cell) in a jail – with a man called William Knoefel. So now you have a man named Knoefel in the same room as a man named Knievel. Both names are somewhat unusual, beginning with a “K.” Well, William Knoefel was also known as Awful Knoefel, perhaps because he did awful or bad things. But Robert Knievel liked this idea – liked the way that title sounded, so he chose the name Evel (Evel) so that it rhymed with his last name: Knievel. “Evil” is normally spelled (evil). I’m not sure if Evel Knievel didn’t know how to spell or he wanted to make it slightly different. In any case, he made up – he invented this name: Evel, and that is the name he decided to use in the future: Evel Knievel. I remember when I was in jail once. Well, never mind!
Knievel was always looking for new stunts – new things to do that were dangerous. He participated in rodeos, where you ride animals; he participated in ski jumping events, where you get on a pair of skis and you go down a big hill on the snow and then you jump at the end. Knievel eventually served in the United States Army, the military forces of the U.S. He married and he had odd jobs after leaving the Army to support his family. The expression “odd (odd) jobs” refers to a series of unrelated, unspecialized jobs. Maybe one day or one month he was working at a gas station, the next month he was a salesperson, the next month he was a deliveryman, delivering things in a truck. These are odd jobs, they are not related and typically don’t pay very well.
Finally, in the middle of the 1960s – we would say the mid-60s – Knievel began his daredevil career by designing and promoting his own entertainment show. “To promote” means to advertise, to make popular, to let other people know about it. So, he started his own entertainment business. He did things such as pop wheelies on his motorcycle. He also tried to jump, on his motorcycle, over a 20-foot-long box filled with rattlesnakes, which are very dangerous, poisonous snakes – snakes that could kill you. This box also had two lions in it – again, very dangerous animals. Well, when Knievel tried to jump over this box he actually hit his back wheel in the box, but he got on the ground safely and he survived. This is actually sort of typical of Evel Knievel’s stunts – many of them don’t work! But he still continued to do them, and people continued to come back, pay money, and watch him do these stunts.
Knievel wanted to make more money, so he decided to have other performers – other daredevils performing stunts. He expanded his show, which “debuted” or first began in 1966. Although he had several serious injuries, Knievel continued to perform stunts. He became very famous in the late 1960s for driving his motorcycle and jumping over cars. In 1967, he successfully cleared 16 cars. In this context, “to clear” (clear) means to jump over the top of something without touching it. So, while riding his motorcycle, he jumped over 16 cars – again, a dangerous thing to do.
Now Knievel was starting to become famous. His next big stunt was in Las Vegas. Las Vegas is a city in Nevada in the western United States famous for, among other things, gambling. Knievel went to a famous hotel, which is still there, called Caesar’s Palace. His goal was to jump over the famous fountains of the hotel. A “fountain” is when you have water that goes up into the air. You see these in parks, in front of buildings sometimes. Well, there are some famous fountains in front of Caesar’s Palace. However, when he tried to jump over these fountains his bike suddenly lost power – it stopped going fast, and things quickly, we might say, went south. The phrase “to go south” means to fail, to have a bad experience, to lose. “I invested money in the stock market, and then the market went south.” The market went down, something bad happened. Well, things went south for Evel Knievel in his Caesar’s Palace stunt. He broke many bones in the fall – in his accident, although we don’t really want to call it an accident since he was the one at fault. He also went into a coma; he was asleep, or unconscious for 29 days. So, it was a very serious accident – a very serious event.
The event made Knievel more famous, however, than ever. That is, he was even more famous after the stunt than before. Remember, he failed, but he still became famous! So then he decided to do another stunt. He decided to jump over 19 cars instead of 16 cars. When he did that, there were over 100,000 people who watched him do this. Then he chose his most famous stunt; he chose to jump over a river, the Snake River Canyon, which is located near the town of Twin Falls, Idaho. Idaho is a state in the northwestern part of the U.S., it’s right next to Montana and the state of Washington – and the state of Oregon, I should add.
This was the most dangerous stunt that Knievel planned to perform. Knievel built a special motorcycle in order to jump the Snake River Canyon. Of course, if he failed he could easily kill himself. The bike would go down a very long distance and he would probably not survive. This event was so famous it was on television; I remember watching it as a child. Everyone knew about Evel Knievel when I was growing up, and many people watched him on TV performing this stunt.
Well, like other Evel Knievel stunts, he failed. He jumped across the Canyon and landed on the other side, however he began to fall back into the canyon, and yet he survived – he did not die. He continued doing these stunts in the 1980s, but his real height of fame was in the 1970s, with this Snake River Canyon jump in 1974.
Knievel died in 2007, but anyone who grew up in the late 20th century in the U.S. certainly remembers him and his daredevil stunts.
Now, we’ll move on to our second topic: Colonial Williamsburg. Colonial Williamsburg is part of the town of Williamsburg, Virginia. For most of the 18th century, during the 1700s, Williamsburg was the center of government; it was the center of culture and education in what was then the Colony of Virginia before it became a state – that is, before the American Revolution in 1776. There were many important men in American history, including Thomas Jefferson, James Monroe, James Madison, all of whom were presidents, and another famous American, Patrick Henry, who met in Williamsburg and helped build the American democracy.
Today you can go to Colonial Williamsburg in Virginia, on the east coast of the United States, and you can see how life was like in the 18th century. There are “exhibits,” which are displays or collections of things. In a museum, you often have exhibits. These are the things that you go to see, especially a museum that is dedicated to history.
Colonial Williamsburg includes many original houses – colonial houses. Some of them, I should say, are original; we would probably use the word “authentic” (authentic), which in this case means the same as original, or real. Other houses were recreated to look like a house from the 18th century. There are also exhibits of government buildings, churches, there’s an old what we used to call a “tavern” (tavern), which is a bar.
As you walk around Colonial Williamsburg there are guides – tour guides that are dressed like someone from the 18th century, someone from that “era” (era), or that time period. They use old colonial English vocabulary and pronunciation when speaking to people who are visiting – to tourists. Colonial Williamsburg tries to give you a look at life in the 18th century.
When I was 10 years old, I visited with my family Colonial Williamsburg; I remember it very well. It was like walking into another time period, and as a young boy it was very interesting.
The creation of Colonial Williamsburg as a tourist site began in the 1930s. A very rich family – famous, wealthy family, the Rockefellers, provided a lot of the money to restore or recreate the area, to fix the old buildings, to build new buildings, and so forth. They bought the land around that area and developed it as a tourist site.
Today, Colonial Williamsburg is considered a historical landmark. That is, it’s a real place where important things happened in U.S. history. It’s also an example of what we might call “living history,” where you have people who are dressed up and act like people from another part of the history of your country or area. There are many places in the United States were you can visit, for example old army forts, places where military troops stayed. In my home state of Minnesota we have something called Fort Snelling – Snelling was the name of the fort – and if you go there you can see men and women dressed like the people would have dressed in the 18th and 19th centuries – the 19th century, really, for Fort Snelling. So, this living history gives you the opportunity to experience some of things that happened and the way that people lived in that era.
Some people call this 300-acre Colonial Williamsburg the “Disneyland of the American Revolution.” It’s a place where you can go and experience a part of American history. However, unlike Disneyland – not like Disneyland – Colonial Williamsburg is free. You can go and see things from the revolutionary period – the colonial period. “Colonial” refers to the fact that the areas in the United States on the eastern coast were part of another country; they were part of England. You can see things like “firearms” (firearms – one word), which is another word for weapons – guns, rifles, that sort of thing. You can also see other interesting things in Colonial Williamsburg. They have a lot of performances, what they call “street theater,” where they do performances of various famous events in American history in a park or in the streets instead of going to a formal theater inside a building.
If you have a chance to visit southern Virginia in visiting the United States, you should definitely visit Colonial Williamsburg.
Now let’s answer a few of your questions.
Our first question comes from Patrick (Patrick) in France. Patrick wants to know the difference between the verb “to devote” (devote) and “to dedicate” (dedicate). Both “devote” and “dedicate” can mean to give, or we might say to commit to something, to promise to do something. Or, to take something and decide that it is going to be only used for a certain activity. For example: “He devotes a lot of time to his family.” He gives time to his family. You could say, “He dedicates a lot of time to his family.” Again, it means the same thing. You could say, “I am devoting a lot of money to my new computer,” “I am dedicating a lot of money to my new computer.”
In most cases, either word can be used. Some people use “devote” to talk more about things like your family, your love, your religion, important serious things. “Dedicate” is often used to talk about work or other interests. But there’s no agreement; people use these words both ways.
“Dedicate” can also means something else; “dedicate” can also mean to write something or to produce something, such as a song, that you say is in honor of another person. So if you pick up a book, often on the first two or three pages there is what we call a “dedication,” which is the noun that comes from the verb “to dedicate.” Someone will dedicate this book to his mother or her husband. That’s another use of the verb “to dedicate.”
Petr (Petr) in Russia wants to know why I use the title of “doctor.” Why are some people called doctors, such as Dr. Lucy Tse? I think I might have talked about this in an episode many, many years ago, but in the United States there are two kinds of people that can be called “doctor.” The first, everyone calls “doctor,” and that would be a medical doctor, someone who has the initials, or the letters “M.D.” after their name: Marcus Welby, M.D. – Dr. Marcus Welby. That was a famous television show, Marcus Welby, M.D., when I was a child. So, a medical doctor or a dentist would be called doctor and usually their last name: Dr. Smith, Dr. Jones, and so forth, Dr. Hugh.
Dr. is also used in the academic world, in the world of the university, to refer to anyone who has a degree called a doctorate. The most common is a Ph.D. This is a doctor of philosophy, but here philosophy just means learning. Some newspapers refuse to call university professors with doctorates Dr. They reserve that, that is keep that title only for medical doctors, but it can be used in both cases.
Why do I use it? Well, mostly because I want people to know that I do have some education and experience in language teaching, and that’s not always true when you go to other websites.
I said the term Dr. is used for anyone with a doctorate. That could be an M.D., a medical doctor. It could be a veterinarian doctor, someone who takes care of animals. It could be a dentist. It could also be a lawyer, who has what we call a J.D., or Juris (meaning law) Doctor. You could have a Doctor of Theology, the study of religion, and so forth. I should mention that lawyers who get a J.D., a Juris Doctor, are typically not called Dr., even though they have the highest possible degree in their field – in their area. Instead of being called Dr., they just make a lot of money!
Finally, Yoss (Yoss) in Israel wants to know the meaning of the expression “between now and then.” “Between now and then” (then). “Between now and then” is the amount or the period of time between right now, this moment, and some later time, some time in the future that you’ve mentioned. So for example, I am going on vacation again in the year 2012. You know, I work very hard; I never take a vacation, almost! So, I will take another vacation in the year 2012, two years from the time I am recording this episode. Between now and then, meaning from now until 2012, I will be working hard recording podcasts for you. Or you could say, “Our airplane flight leaves in one hour. Between now and then I’m going to get some food.” Between right now and one hour from now.
There’s a relate expression, “now and then,” without the word “between,” which means sometimes, occasionally; “every once in a while” is another way of saying this. Now and then I like to eat breakfast food for dinner: eggs, bacon – well, an American breakfast.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
daredevil – a person who takes risks, usually physical risks, looking for new adventures
* Bea is a daredevil who likes to skydive off mountains and ski on dangerous mountain slopes.
stunt – dangerous trick, usually requiring physical skill
* The actor in the movie did a dangerous stunt, walking on a thin wire between two buildings.
to pop a wheelie – to lift the front wheel of a vehicle, motorcycle, bicycle, or machine off the ground while one is riding on it
* The children rode their bikes, popping wheelies to impress each other.
odd jobs – a series of unrelated, unspecialized jobs, usually with low pay
* After graduation, Charlie did odd jobs until he found a full-time job in his field.
to clear – to pass over the top of something without touching it
* Micha threw the balloon filled with water thinking it would clear his sister’s head, but it didn’t and it hit her in the face.
to go south – for something to begin to fail; for the condition of something to become worse
* After the heart attack, Jiang seemed to be recovering when her condition went south.
exhibit – display; the making available for the public to see of a collection of related things
* Let’s go see the exhibit with the jewels of past kings and queens.
authentic – real; original; not fake or false
* The man on the street said that this watch is an authentic Rolex, but I don’t believe him.
era – time period; a long and specific period in history
* When the car became a popular way to travel, the era of traveling by horse was over.
living history – an interactive presentation that uses historical tools, activities, and dress to allow visitors to experience what it would be like living in that period in history
* Watching the play about the first man on the moon is like watching living history.
firearm – weapons, such as guns, pistols, and rifles
* Passengers are not allowed to bring firearms onto the airplane.
street theater – a performance or presentation done on the street or in a park, rather than performed on traditional stages in a theater
* Spend the summer in New York City and you’ll see a lot of street theater.
to devote – to give time, effort, or oneself to doing something; to set something apart for a specific use, usually for an important reason or to get something done
* We devoted six years to developing a car that would run on air, but it still isn’t ready.
to dedicate – to give time, effort, or oneself to doing something; to set something apart for a specific use, usually for an important reason or to get something done
* She dedicated her entire life to helping poor children.
Dr. – an abbreviation for “doctor”; a title used for someone with a medical degree or a doctoral degree in an academic area
* My doctor is Dr. Kamil and my dentist is Dr. Johnson. My favorite professors are Dr. Lavadenz and Dr. Saint-John.
between now and then – the time period between this moment and a later time mentioned earlier
* There are five minutes before the movie starts. I should have time to get some drinks and snacks between now and then.
What Insiders Know
Frontier House
In the past 10 years or more, the popularity of reality TV shows has increased “dramatically” (very much; significantly) in the United States. It seems that every channel “broadcasts” (shows) some type of reality television show and PBS is “no exception” (included; the same). PBS “stands for” (is a short version of) Public Broadcasting Service, which is the “non-profit” (not intended to earn money) public broadcasting station seen across the U.S.
In 2002, PBS began “airing” (showing on TV) a show called Frontier House. This reality show followed the lives of three families who agreed to live for five months as “homesteaders” in 1883. “Homesteaders” were people who agreed to move to a part of the country that did not have white people living there, such as the Midwest and Western areas, and to make their home there, in exchange for becoming owners of a piece of land. Homesteaders were given 160 acres (0.65 km) of land and basic supplies, food, and “livestock” (animals). The parts of a country without towns and people living there are often called the “frontier,” and that is why the show was called Frontier House.
In the show, the three families were expected to live as people did in the 1883. They dressed as they did, worked as they did, prepared and ate food as they did, and used the “resources” (materials available for doing something) that were available to them in that time period and in that “setting” (location and situation). The families had to do without “modern conveniences” such as toilets, washing machines, and even simple things like soap.
PBS did not have the original idea for the show. Frontier House “followed in the footsteps” (did the same thing as something else before it) of the successful British TV series “The 1900 House,” which originally aired in 2000 in Britain. In the 1900 House, a modern family tried to live for three months as people did in Victoria England (during the time of Queen Victoria) in the late 1800s.