= 1599
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 294.
This is English as a Second Language Podcast’s English Café episode 294. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Become a member of ESL Podcast and help keep these podcasts free. We need your support, and one way you can do that is becoming a Learning Guide member. Not only do help us, you help yourself! Our Learning Guides are 8- to 10-page guides that include a complete transcript of this episode, along with vocabulary, definitions, sample sentences, additional cultural information, and a short comprehension quiz.
On this Café, we continue our series on American Presidents, focusing on perhaps one of our most famous presidents, our 16th President, Abraham Lincoln. And, as always, we’ll answer a few of your questions. Let’s get started.
On this Café we’re going to talk about the 16th President of the United States, Abraham Lincoln, who was President from 1861 to 1865.
Abraham Lincoln had very humble origins. When we use the word “humble” (humble) to talk about someone we mean that they are not proud, they’re very modest, they don’t like to talk about themselves and how great they are. “Humble” is the opposite of someone who is “boastful”; someone who “boasts” always talks about how great they are. The phrase “humble origins,” however, refers to someone who was born in a poor family, a family without much power in society. Americans traditionally have admired people who have humble origins but then become very successful, wealthy, or powerful. That’s part of the so-called American Dream, that you can go from a poor person to a rich person. That’s one of the reasons why Americans probably admire Abraham Lincoln. He is sometimes referred to as Honest Abe, where “Abe” (Abe) is short for his first name Abraham. That nickname, we would call it, Honest Abe, shows how much people trusted him to tell the truth.
Lincoln was born in a one-room log cabin in Kentucky on February 12, 1809. Kentucky is a state located in the central eastern part of the U.S. A “log cabin” is a small home built out of long pieces of wood called “logs,” which come from, of course, trees that you cut down, and you take the tree and you build a house from it. Lincoln was born in a one-room log cabin, meaning it was a very small, simple home. The Lincoln family wasn’t wealthy or rich, but the father was, in fact, a relatively rich man in his area at that time. He owned a lot of land and “livestock,” which is another word for animals, especially animals on a farm that you can eat or get something from. But in 1816 the family lost almost everything because there was a problem with the title to the land. The word “title,” when we are talking about land or property, refers to the legal documents that show who owns the land. It’s sort of like an official paper that says you own the land or someone else owns the land. Whenever you buy a house in the United States you have to have a lawyer investigate the title to make sure that the person you are buying the house from really owns the house. Well, that was the problem that poor Mr. Lincoln, Abraham’s father, had, and they lost the land that they had. Well, the poor Lincolns moved to the neighboring state to the north, to Indiana to start a new life. However, Lincoln’s mother and older sister died when he was young. His father married again, and the family then moved to Illinois in 1830, when Lincoln was 21 years old or so.
Lincoln didn’t receive a formal education; that is, he didn’t go to school – an official school. He did take some classes for about 18 months from itinerant teachers. “Itinerant” (itinerant) is someone who travels around from place to place. These were teachers that would travel around in the countryside and give classes to families. Lincoln, however, loved to read, and most of what he learned he taught himself by reading books, which, of course, is the best way to get an education.
When Lincoln was 23 years old, he bought a small store, but it failed and he fell into debt. When we say is someone is “in debt” (debt – we don’t pronounce the “b”) we mean that he owed other people money. Notice the verb we use, “to fall into,” almost like you’re falling into a hole by accident in the ground. Many people fall into debt by borrowing more money than they can pay back. It took Honest Abe 17 years to pay his loans back. Maybe he realized he wasn’t a very good businessman, and that, perhaps, was one reason that he decided to enter politics – to become involved in politics.
In 1834 he was elected to the Illinois legislative body, the Illinois General Assembly. He then decided to become a lawyer, so he started, of course, studying books, reading, teaching himself about law. He was “admitted to the bar” meaning he became officially a lawyer in 1837 and he began to practice law in the City of Springfield, Illinois. Once again, notice the verb we use here: “to practice” law. We use the same verb for a doctor: “to practice” medicine. It’s a special verb; it just means to work as a lawyer or to work as a doctor. Springfield, Illinois is in the southern central part of the state. I visited Springfield a couple of times when I was younger. My parents had good friends that lived in Springfield, who later moved to California I think. I wonder what ever happened to them. Well anyway, we’re in Springfield, Illinois, Abraham Lincoln is working as a lawyer, and he is getting a good reputation; people are beginning to learn about him because of his oratorical skills. “Oratorical” (oratorical) is the ability to give good public speeches. He served, or was elected to the Illinois House of Representatives for four terms; that is, four times.
Finally, in 1846, Lincoln decided to enter national politics when he was elected to the United States House of Representatives in Washington, D.C. He was a representative from 1847 to 1849, just two years. He became known in that short time however for his opposition to slavery. “Opposition” means to be against something. “Slavery” is the owning of human beings as property. He was also opposed to President Polk’s Mexican-American war.
When his term, or his time in office ended in 1849, Lincoln returned to Illinois and continued to work as a lawyer. But just a few years later in 1854 he once again returned to politics, giving speeches against the practice of slavery. Many people thought of him as what was called then an “abolitionist.” “To abolish” (abolish) means to get rid of, to eliminate something. An “abolitionist” was someone who wanted to make slavery illegal. But Lincoln didn’t say he wanted to abolish slavery; he said he wanted to stop the spread of slavery, he wanted to prevent more states from allowing slavery. He was also convinced, however, that the United States could not continue as one country if part of the country allowed slavery, the South, and part of it did not. In 1858, he made a very famous speech, quoting from the Bible, “A house divided against itself cannot stand.” That is, if you have one group of people – one organization – if they are divided against each other, one wants one thing, one wants another, it’s not going to last, the group is going to break up or split up. “A house divided against itself cannot stand,” that is, the house will fall down, to use the metaphor here. In that 1858 speech, Lincoln argued that slavery would either have to be allowed everywhere, throughout the entire country, or nowhere in the country. The speech drew people’s attention, or got their attention, to how serious the issue of slavery was and how it might, as it did, divide the country.
In 1858, Lincoln decided to run for, or try to be elected to the United States Senate. Each state in the United States has two senators that represent that state in Washington, D.C. Lincoln was running against a man by the name of Stephen Douglas. The two men participated in seven debates before the election. A “debate” is an opportunity for two or more people to present their opinions in front of a larger group of people. Political debates have a long history in the United States, but this debate was perhaps the most famous one in American history. I should say “these debates,” since there were several of them. The debates were mostly about slavery, Lincoln saying that slavery was wrong, Douglas saying that the states should determine whether they want to allow slavery or not. There is this constant tension in American politics – in American history between the power of the federal or national government and the power of the individual states and their governments.
Stephen Douglas won the election to be U.S. Senator, however most people thought that Lincoln won the debates in terms of the arguments he presented, and the debates gave Lincoln a national visibility. That is, people knew about Lincoln in other states. In fact, after the election, Lincoln continued to give very powerful and popular speeches, and in 1860 he was made the presidential candidate for the Republican Party. Much of the campaign focused on the fact that he came from a family without a lot of money, once again, remembering that Americans love the poor person who becomes successful.
Lincoln won the election in 1860, but only because of the voters in the northern states, where slavery was illegal. Ten of the southern states didn’t even put his name on the “ballot,” the piece of paper used to vote. As the southern states realized Lincoln would win, they began to talk about seceding from the United States. “To secede” (secede) means that you are going to break away, you are no longer going to be part of the U.S. In February of 1861 several states, South Carolina, Florida, Mississippi, Alabama, Georgia, Louisiana, and Texas began calling themselves the Confederate States of America. Lincoln and the then-President Buchanan of course refused to recognize them as a separate country, and thus America entered into its one, we hope only, Civil War.
Lincoln did not have a lot of military experience, but he was determined to save the United States as a union, as one country. He believed that freeing the slaves and ending slavery was the only way to do that. So after the war began, in 1862 he signed one of the more famous documents in U.S. history, the Emancipation Proclamation. “To emancipate” means to give someone their freedom. A “proclamation” is like an announcement. The Emancipation Proclamation said that all slaves were free in the United States as of, or beginning on January 1st, 1863. The problem, of course, was that the southern Confederate, as they were called, states didn’t recognize the legal authority of Lincoln. So, in reality there were no slaves freed at the time of the proclamation, because the southern states didn’t recognize the proclamation as legal.
Lincoln, of course, ended up becoming one of the greatest war presidents; at least he was successful even if he wasn’t the most experienced. He gave a very famous speech called the Gettysburg Address, which we talked about back in Café number 247.
As the war ended, Lincoln focused on “reconstruction,” that is building the country back up again, bringing the country together after the war. He wanted to treat, that is, he wanted to act toward the southern states firmly but fairly. In 1864, he was elected president for a second term. And in 1865, the Civil War ended with the Northern, or Union forces winning, and the United States becoming one country once again. This was the final and definitive, that is, the last and most authoritative answer to the question about whether a state can secede from the Union. The answer is “no.”
Understandably, Lincoln was very unpopular among the southern states. On April 14, 1865, Lincoln went to the theater for the evening, and it was there that he was shot and killed by a man named John Wilkes Booth. It was the first “assassination” or murder of a U.S. president. Unhappily, it was not the last. Lincoln died the following day and his Vice-President Johnson became the President of the United States.
Lincoln is remembered, admired, and honored for his work to end slavery and to save the Union – to save the country as one. There are too many ways to mention about how he is honored – cities and streets and schools. We have his birthday celebrated, along with George Washington, on President’s Day. There’s a large memorial to Lincoln, the Lincoln Memorial in Washington, D.C. And, most people agree he was one of our greatest presidents. As a child while visiting Springfield, Illinois I visited Abraham Lincoln’s tomb, the place where his body was buried, and, like most Americans, see Abraham Lincoln as one the great figures of our history.
Now let’s answer some of the questions that you have sent us.
Our first question comes from Villarie (Villarie) in Taiwan. The question has to do with three similar words: “rise” (rise), “raise” (raise), and “arise” (arise).
“Rise” can mean to move to a higher level, to move to a higher place. We have the expression “heat rises,” that is hot air will go to the top of the room or the top of the building. “Rise” can also mean to get up from your bed. A mother might call out to her children who were still sleeping, “Rise and shine.” “Rise” means get out of your bed; “shine” is something that the sun does, it gives off light. So just like the sun rises and shines each morning, you’re telling the person who’s sleeping they need to rise and shine.
“Rise” can also mean to get more powerful or bigger or stronger; again, the same idea of getting to a higher level. “The price of gasoline is rising,” it’s getting higher. Or, “The river is going to rise in another week,” it’s going to get higher. You could also talk about a company becoming more successful; you might say, “It’s a rising company,” it’s a company that is getting more and more successful every day.
“Raise” (raise) is to move something higher, or the action of moving something to a higher level. “Raise” is what we would call a transitive verb, it takes an object; there is something that is raised by someone. “The soldiers raised the flag.” The soldiers, those in the army, put the flag of their country up on a pole; they raised the flag. “Raise” can also be used for, once again, to make something bigger, louder, stronger, more powerful. “I’m raising the volume on the television,” I’m making it louder. Or, “I’m going to raise your salary,” I’m going to give you more money. “I’m going to give you a raise,” notice it can be also used as a noun in that case, when you are talking about work.
To makes something grow is another meaning of “raise.” “I’m raising kittens,” that is, I am taking the little kittens from when they were – are babies and making them into adults. Ha! If you believe that, you haven’t been listening very carefully. “Raise” can also be used for children. “My poor mother and father raised 11 children.” They were responsible for those children, they paid for them, they take care of them. Many people are born in one place, but raised in another. “My friend was born in Texas, but raised in Minnesota.”
“Arise” means to get up or to move higher. It’s similar to “rise,” it can be used in the same circumstance. “Arise” can also mean to come into existence, to come into being, to result from. “Many problems arise when you try to date two men or two women at the same time,” many problems will result from that situation. In fact, the noun “problem” is often used with the verb “to arise” to talk about situations where there are bad things happening or possibly bad things happening because of the situation.
I mentioned earlier that “raise” is what we call a transitive verb; “rise” is an intransitive verb. That is, it doesn’t take an object. I mention that “rise” and arise” can both mean to get up, as in to get up out of bed. The truth is, however, we don’t use them in that context very often. It’s more common to say simply “to get up.” “What time did you get up?” If you say, “What time did you arise?” that’s considered very formal and not very common. In fact, of the two, “rise” and “arise,” you will only hear “rise” in conversation, if you hear it at all. “Arise” is something you might you read in a book, with more formal English.
Omid (Omid) in Iran wants to know the difference between two very common words in English: “rather” (rather) and “prefer” (prefer). For example, what’s the difference between “I would rather go to the store” and “I prefer to go to the store.”
Both “rather” and “prefer” have similar meanings and can be used in many of the same situations, but they’re grammatically different. “Rather” is almost always used with the verb “would.” “I would rather go swimming.” Sometimes you’ll hear somebody say “I’d rather go swimming.” The “I’d” is a contraction, it’s a short version of “I would.” “Prefer” can be use with “would,” but doesn’t have to be. “I would prefer to go swimming.” Or “I prefer to go swimming,” “would” is not necessary.
Now when you’re talking about two different options – two different choices or possibilities, you can again use “rather” and “prefer.” If you use “rather,” it usually comes with a verb as well as the word “than” (than). “I would rather eat pie than cake.” Pie is the one you are choosing between the two. “Would prefer” is usually used with another expression, “instead of,” or, you can use it with “rather than.” “I’d prefer pie instead of cake.” “I would prefer pie rather than cake.” So notice that you can combine the two. “Prefer”, when you don’t use “would,” is usually used in comparing two things with the word “to.” “I prefer pie to cake.” So, this idea can be expressed in all of the following ways: “I would rather have pie than cake.” “I’d prefer pie instead of cake.” “I would prefer pie rather than cake.” “I prefer pie to cake.” All of those are basically the same.
Finally, Tzu-Ling (Tzu-Ling) in Taiwan wants to know the meaning of the expression “to tender your resignation.” “To tender” (tender) means to offer formally. It’s a verb that you will usually hear only with the word “resignation,” which is when you are quitting your job or leaving your position. When I left the university several years ago, I tended my resignation to the dean, who is the head or leader of the group of departments where I was working – the school where I was working at the university. So, this expression “to tender your resignation” is where you will hear the verb “tender” most often in English, and that’s what it means, to formally say I am quitting, I am leaving.
Sometimes there is an idea that the person – your boss will say “no.” In politics, when something bad happens someone will often tender their resignation to the president or to the governor, and the governor may say, “No, I don’t want you to leave.”
As a verb, “tender” is rather formal, and you will only hear this expression “tender one’s resignation” in a very formal setting.
“Tender” can also be an adjective. As an adjective it can mean showing concern or being gentle, been very nice with something. “The mother touched the child tenderly,” using it there as an adverb. You may remember, those of you who are a bit older, a song by Elvis Presley called “Love Me Tender” from a movie in the 1950s. [Jeff sings] “Love me tender, love me sweet, never let me go. You have made my life complete, and I love you so.”
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
humble origins – having been born into a poor family without very much power or status
* I admire Nisa for coming from humble origins and reaching the top of her field.
log cabin – a small home built out of logs (cut-down trees); a very simple building made for logs, often in the forest or woods
* During a rainstorm, it is difficult to keep the rain and wind out of a log cabin.
itinerant teacher – a teacher who traveled from place to place in rural (not in the cities) America in the old days
* Years ago, many rural children weren’t educated in schools, but only occasionally by itinerant teachers.
to fall into debt – to owe other people money; to have borrowed money from other people and to need to pay them back
* Our company fell into debt when we expanded the business too quickly.
oratorical – the giving of speeches in front of an audience; speaking formally in public
* American presidential candidates must have good oratorical skills.
abolitionist – a person who wants to make slavery (the owning of other people) illegal; a person working to end slavery
* Abolitionists put pressure on politicians to end slavery.
debate – a formal discussion in public of two or more people to present their different opinions about one or more issues
* There was no clear winner in the debate, with each speaker making some good points about the issue.
to secede – to formally withdraw from a larger group; for one part of a group to formally leave a larger organization
* If Los Angeles seceded from the rest of California, it would need to form its own state government.
reconstruction – rebuilding after something has been damaged or destroyed
* Fortunately, there was enough money for reconstruction after the storm damaged the school.
to rise – to move higher; to get up; to get bigger, louder, stronger, or more powerful
* The price of gasoline rises during the summer months and over the holidays.
to raise – to move something higher; to make something bigger, louder, stronger, or more powerful; to make something grow; to care for children while they grow up
* Our state is considering the raising of the drinking age from 19 to 21.
to arise – to get up; to move higher; to come into being; to result from
* A lot of our company’s problems arose from the owners’ poor planning.
rather than – used to indicate one’s preference for one thing instead of another; choosing or wanting to choose something one thinks is better
* Rather than stopping home after work to change my clothes, I’ll bring a change of clothes to work and go directly to the ballgame.
to prefer – to indicate one’s preference for one thing instead of another; to choose or want to choose something one thinks is better
* Do you prefer a relaxing vacation on the beach or an adventurous vacation in a new city?
to tender (one’s) resignation – to formally give someone else verbal (spoken) or written notice that one intends to leave one’s job or position
* The company earnings dropped significantly in the past year and the president tendered her resignation.
What Insiders Know
Commemorating President Lincoln
Abraham Lincoln is one of the most respected past presidents of the United States. For this reason, he is “commemorated” (remembered and shown respect) in many ways.
The most famous “monument” (statue, building, or other structure to honor or remember someone or something) of Lincoln is the Lincoln Memorial in Washington D.C. This impressive monument is located on the National Mall, where other important monuments and museums are found. The monument includes a 19-foot statue of Lincoln.
Lincoln also appears on Mount Rushmore, a very large “sculpture” (figure made from stone or other hard material) on the side of the mountain in the state of South Dakota. Lincoln is one of the four presidents included in the sculpture, and appears with George Washington, Thomas Jefferson, and Theodore Roosevelt. Many Americans would “argue” (say it is true) that these are among the four greatest presidents in U.S. history.
Many towns and cities have also been named for Lincoln. The capital of the state of Nebraska is “Lincoln.” A town in Illinois is also called Lincoln and is the only city that was named for Lincoln before he became president. Lincoln, who was a lawyer before he became president, practiced law there between 1847 and1859.
If you’re not able to visit Washington D.C., South Dakota, or any of the towns or cities named for him, you can still see ways Americans commemorate Lincoln. Nearly every time you “handle” (use or feel with your hands) money, you see Lincoln. That’s because he appears on the $5 bill and on the 1-cent coin, called a “penny.”