= 1564
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 259.
This is English as a Second Language Podcast’s English Café episode 259. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide that contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this episode.
On this Café, we’re going to talk about the Great Smoky Mountains National Park, a beautiful national park in the eastern part of the United States. We’re also going to continue our series on famous American songs. Today we are going to talk about the song Oh! Susanna, which almost every American knows, and after this episode you’ll know it too. As always, we will also answer some of your questions. Let’s get started.
This Café begins with a discussion about the Great Smoky Mountains National Park. “Smoke” (smoke) is that dirty, dark grey or black air that comes from a fire, and the word “smoky” is often used to describe those dark colors. The Great Smoky Mountains are a part of a mountain “range,” a large number of connected mountains, in the eastern U.S. The Great Smoky Mountains are part of the Blue Ridge Mountains and the Appalachian Mountains. These mountains are found in Tennessee and North Carolina. Appalachia refers to this region in the center eastern, I guess we could call it, part of the United States; the Appalachian Mountains are part of that region, and the Great Smoky Mountains have their own national park. They’re called great because they are considered beautiful; they are big. Great is used to mean wonderful, in some ways; it can also mean large, and the Great Smoky Mountains National Park is large. There are 800 square miles. It’s one of the biggest natural areas that is protected by the government in the eastern United States. It is also the most popular national park in America. That is, more people visit the Great Smoky Mountains National Park than any other park in the U.S.
The park is especially beautiful in the fall – that is, in the autumn (September, October, November) when the leaves on the trees change colors; they become red, orange, and yellow a few weeks before they die – they fall off of the tree. That’s true in the eastern U.S., it’s true in the northeastern United States, it’s also true where I grew up in the Midwest. During the fall you will see the trees change colors – the leaves change colors. It’s very beautiful to see.
This park has 16 mountains in it that are taller than 6,000 feet. That would be almost 2 – 1.8 kilometers tall. There are also a lot of what are called old-growth forests in this national park. These are areas of land that have many large trees that are very old. This, combined with a lot of rain, has given this area a very rich environment. There are lots of different types of plants and animals, birds and fish in this area. The park has more than 2,000 black bears and is famous for having at least 30 types, or 30 species of salamanders. “Salamanders” (salamanders) are small amphibians, they’re called. They look like little lizards but they live in and around the water. I don’t particularly like salamanders.
I have been to the Great Smoky Mountains National Park, however. I was there when I was a boy, back at 19 – let’s see – 73 I think. I was there with my family traveling in the eastern part of the U.S. It might have been ‘72, I don’t remember.
In any case, the Great Smoky Mountains National Park has more types of salamanders than anywhere else in the world. It’s sometimes called the Salamander Capital of the World. If you really like salamanders you should go there!
Many people come to the park for its natural beauty – its natural attractions. It’s very popular to go walking; we would call it hiking (hiking). To “hike” (hike) means to walk in the forest or to walk in nature where there aren’t a lot of cars, and houses, and McDonald’s, and all that good stuff. Many people also climb these tall mountains. The park has 850 miles of hiking trails. A “trail” is a path, a place where you can walk. Usually it’s small and narrow, not big enough for a car. Many people take these trails to go to the tops of the mountains where they can have these beautiful views; they can see a long distance. There are also waterfalls in the park. A “waterfall” is when the water goes over a very high surface; we would call it a cliff (cliff). The water goes over the cliff and falls many feet below. The most famous falls in the United States – waterfalls – are Niagara Falls, located on the border of the state of New York and Canada. You can also use your bicycle in the park, and most importantly for me you can use a car to drive around the park, too. That’s my favorite way of experiencing the outdoors – experiencing the natural environment. We would say experiencing nature. The best way to do that is to be in my very comfortable car!
Some people go to this national park to fish – to catch fish. Other people come to see certain historical attractions. There are 78 what are called historic structures or buildings – old buildings in the park. These are mainly the homes of some of the first white people who came to live in these mountains; we would call them settlers. A “settler” (settler) is someone who is the first to go and live in a certain area. The buildings that people visit also include churches and log cabins. A “cabin” (cabin) here means a small house. “Logs” are what you get when you cut a tree down and take the main, big part of the tree. The log is round. You can take these logs and build a small house. In the American imagination we think about our early settlers during the 19th century living in these log cabins. The most famous person that is associated with living in a log cabin would be our 16th president Abraham Lincoln.
So, the Great Smoky Mountains National Park is a beautiful area. If you are in the eastern U.S., in the states of Tennessee and North Carolina, you would probably enjoy seeing them. I know I did, many years ago.
Our next topic is going to be a famous song, a song known by most Americans called, Oh! Susanna. Susanna is a woman’s name. The song was written in 1848 by someone who is called the father of American music, Stephen Collins Foster. Foster wrote many of the songs that Americans are now used to hearing growing up; Oh! Susanna is one of them. I’ll start by singing the first part for you, and then we’ll talk about the meaning of the lyrics or the words to the song. A little later, we’ll talk about the song’s importance in American history and American culture. So, here we go:
I come from Alabama with a banjo on my knee,
I’m going to Louisiana, my true love for to see
It rained all night the day I left, the weather was so dry
The sun so hot I froze to death; Susanna, don’t you cry.
That is the first verse – the first four lines of the song; they’re a little bit silly we would say, they’re a little bit like a joke, not making a lot of sense. It begins by saying, “I came from Alabama with a banjo on my knee.” Alabama is a state in the southern United States, the southeastern part of the U.S. “I came from Alabama with a banjo,” a “banjo” (banjo) is a musical instrument with strings; it’s sort of like a guitar, but it has a round base or body and you will often hear it in country-style music. To have a banjo on your knee means that you are holding or putting the banjo on your knee, sitting down, so you can play it. The singer has come from Alabama, ready to play his banjo, and he’s going to another state in the southern U.S., Louisiana. Louisiana is the state where the city of New Orleans is; it’s where the Mississippi River ends. It’s the one state that still has a significant French influence. Louisiana is not next to Alabama; there’s one state in between them called Mississippi.
So we have this young man who is, we find out, in love, because he’s going to see his “true love,” the woman he wants to spend the rest of his life with, the woman he wants to marry. Then things get sort of strange in the song; the next line is “It rained all night the day I left.” So, the day that I left it was raining throughout the night. But then he says, “the weather was so dry.” This is obviously impossible if it’s raining, that’s the opposite of dry. He also says, “the sun so hot (meaning the sun was so hot) I froze to death.” “Froze” is the past tense of “freeze” (freeze), which is what happens when something is so cold it becomes solid. When water freezes it becomes ice. The expression “to freeze to death” means that it was extremely cold. Once again, it doesn’t really make sense, “the sun so hot I froze to death. Finally he says, “Susanna, don’t you cry,” meaning please don’t cry Susanna, even though I have had these difficult, if weird, times. He misses his true love; he wants to see her even though he has to suffer. He says, “Susanna, don’t you cry.”
The next part of the song is called the chorus (chorus). They’re two parts of a popular song: the verse – or verses, typically more than one – and the chorus. The chorus is the part that you sing over and over again, several times typically. So, here is the chorus for Oh! Susanna:
Oh! Susanna, oh don’t you cry for me
I come from Alabama,
With a banjo on my knee.
Some people say, “With my banjo on my knee.” So, “Oh! Susanna, don’t you cry for me,” don’t cry for me. “I come from Alabama, with my banjo on my knee.”
Here’s the next verse:
I had a dream the other night when everything was still,
I thought I saw Susanna coming up the hill,
A buckwheat cake was in her mouth, a tear was in her eye,
I said I’m coming from the south, Susanna don’t you cry.
And then, of course, we would hear the chorus:
Oh! Susanna, oh don’t you cry for me
I come from Alabama,
With my banjo on my knee.
Now, this verse is also a little unusual – a little strange. He begins by saying, “I had a dream the other night,” meaning recently; not last night, maybe two or three nights ago. And in this dream, everything was still (still). To be “still” means to be very quiet, nothing is happening, nothing exciting is happening. My life has been very still! He says that he thought he saw Susanna coming up, or walking up, the hill. He then says that a buckwheat cake was in her mouth. “Buckwheat” (buckwheat) here is a type of flour, something you would make a cake or bread out of. In this case, it’s a buckwheat cake. Buckwheat is somewhat popular in the American South, what we would call the Old South: Louisiana, Mississippi, Alabama, Georgia, South and North Carolina, and so forth.
So he sees his girlfriend, or the woman he wants to be his wife, with a buckwheat cake in her mouth. I guess she was eating it, and a tear was in her eye. A “tear” (tear) means that she had a little bit of water on her face because she was crying. When you cry, the water that comes out of your eyes is called a tear or tears. So, he says, again, I said I’m coming from the south, Susanna, don’t you cry. So, he is telling her not to cry, that he’s on his way.
Here is one more verse:
I’ll soon be in New Orleans and then I’ll look around
And when I find my Susanna, I’ll fall upon the ground
But if I do not find her, this man will surely die
And when I’m dead and buried, Susanna don’t you cry.
Oh! Susanna, oh don’t you cry for me
I come from Alabama,
With my banjo on my knee.
I sang the chorus there just to finish it off – to complete it.
He says, “I soon will be in New Orleans.” New Orleans is, as you know, in Louisiana. It’s the largest, most famous city in Louisiana, and that’s where apparently, we guess, Susanna is. He says, “I soon will be in New Orleans (I will be in New Orleans soon) and then I’ll look around,” meaning I’ll try to find, in this case, you. “And when I find my Susanna (when I find my girlfriend), I’ll fall upon the ground,” meaning he’ll fall down, perhaps because he is so happy or so excited to see her. Then he says, “But if I do not find her, this man will surely die.” “This man” refers to himself: I will certainly – will surely die. “Surely” here (surely) means certainly, absolutely, without a doubt. He’ll be so sad he will die. And when he’s dead and buried, that is when his body is in the ground, he doesn’t want Susanna to cry. My guess is Susanna will find someone else and she’ll be just fine! But, of course, he’s in love with her and believes that she will be sad if he dies.
This song has an interesting history. It was actually written as a song making fun of African Americans – of blacks in the U.S. Remember, in the first part of the 19th century the United States had, in many states, slavery, especially in the south. And, many people made fun of – made jokes about African Americans, jokes that are definitely considered racist, that is prejudiced, not liking someone because of the color of his or her skin.
The words are “nonsensical,” meaning they don’t make any sense sometimes. But as I said, the origin – the place where this song first started was with singing groups that were making fun of African Americans. In fact, they would put black paint on their face, what was called blackface, and they would dance and sing, talking like the black slaves talked. They were of course, as I said, making fun of them. The song was originally performed in a very strong dialect, which is the version of language spoken by a certain group of people. It was performed for white people and usually was part of a larger show, where there was lots of singing.
I’m guessing the average American, however, doesn’t realize that this song began in this racist tradition of the 19th century. Part of the reason they don’t know is because the racist verses are not sung anymore; you won’t find them very easily. People think it’s just a nice love song, and they sing it without realizing its history. Of course, if you eliminate the racist verses then it is a nice little love song, but it’s important to remember the history of it, where it came from originally.
The words to the song have actually been changed over the years. Most Americans hear the song as children when they’re growing up, and typically can saying can sing a few verses “from memory,” that is, without having to look at the words. If not the verses, then at least they can sing the chorus.
So that’s Oh! Susanna, a popular song still more than 150 years since it was written.
Now let’s answer a few of your questions.
Our first question comes from Nizar (Nizar) in France. The question has to do with the difference between the word “whichever” and the word “whatever.”
“Whichever” means the one or ones out of a group; it can also mean no matter which, it doesn’t matter which group. “You can have turkey or you can have chicken, whichever you want,” meaning either one, it doesn’t matter.
“Whatever,” and like “whichever” it is just one word, means anything or everything that meets some condition, or it means something similar to. For example: “I like coffee, tea, and whatever there is to drink,” meaning anything else.
Notice “whichever” is usually between two or three choices. “Whatever” can mean anything or everything. “A good wife forgives her husband whatever mistakes he made.” It doesn’t matter how many mistakes he made, she forgives him. That’s what we call a fictional sample sentence!
The word “whatever” can also be used to show surprise or confusion: “Whatever are you doing here?” It’s another way of saying what are you doing here, but you are adding this meaning of surprise or confusion. It’s a little old-fashioned; you don’t hear it as much anymore, but you will still read it and hear it from old people like me. “Whatever are you doing?” a mother might say to her son who she finds making a mess in his room.
In everyday conversational English you will often hear people these two interchangeably, one for the other. “Whatever choice you make, I know you will do the right thing.” “Whichever choice you make, I know you will do the right thing.”
There’s one final meaning, however, of the word “whatever” that can only be expressed by that word, and that is an informal way of using it that shows that you don’t care. Usually it’s a negative sense that you don’t care about something, that it isn’t important. So your wife says to you, “It’s six o’clock, you said you would be home at five o’clock,” and you say, “Oh, whatever,” meaning it doesn’t matter, it’s not important. But it’s also sort of a criticism of the person who is criticizing you, a lot depends on the way the word is said, especially by a teenager: “Whatever!” That would definitely mean that he or she doesn’t care.
Kanako (Kanako) in Japan wants to know the meaning of the expression “tarred-and-feathered.” “Tar-and-feather,” (tar) and (feather) is an old verb in English. “Tar” is a thick, dark liquid that is made from either wood or coal, which is a hard, black substance you dig out of the ground. We use tar to make roads; we use tar often on the roofs of our houses to protect them from the rain. “Feathers” are things that come from a bird; birds have many different feathers. They use their feathers to fly and to keep them warm.
The verb, however, “to tar-and-feather” originally comes from Europe. It was a physical punishment. It was also used in the American colonies before they became the United States. It’s literally where a person has their clothes removed, or taken off, and this hot tar is put on their body. Obviously, that would be very painful. And then, feathers are thrown on him or her, or the person is made to put feathers on themselves. The idea was to not only hurt the person but to humiliate, to make the person feel ashamed, to make the person want to leave because they’ve done something so wrong or they feel so foolish.
I should say that this was never an official form of punishment in the United States. However, people know what it means. It’s nowadays used sometimes to mean mob vengeance. A “mob” (mob) is a large group of people. “Vengeance” is when people try to hurt or harm other people because they think they are guilty of something – they’ve done something wrong. They’ve been hurt, and so they want to hurt you. So, mob vengeance is the sense where many people try to – we have another expression – “take the law into your own hands,” meaning you basically become the police, and you are going to punish people. As a group this would happen.
Finally Ann (Ann) in Hong Kong wants to know the meaning of the expression “mutually exclusive.” “Exclusive” (exclusive) comes from the verb “to exclude,” which means the opposite of “include.” Not to include is to exclude. “Mutually” means the same for two different things or persons. “Mutually exclusive” is when two things cannot occur or exist at the same time, two things that cannot be true at the same time. You can be a good father and a successful businessman; those two things are not mutually exclusive. You can be a good mother and a successful businesswoman; those two things are not mutually exclusive. However, if you work for a company that does not want you to work for anyone else part-time on the weekends, you could say that working for your company and having another job are mutually exclusive; you can’t do both.
Enjoying the English Café and writing us a note with your questions and comments are certainly not mutually exclusive things! You can email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational
Glossary
smoke – the dirty, dark grey or black air that rises from a fire
* Look! There’s a lot of smoke on that mountain. I hope it’s not on fire!
old-growth forest – an area of land with many large trees that are very old
* Walking around this old-growth forest makes us feel very young by comparison.
salamander – a small animal with bright spots that lives near the water and that looks similar to a lizard
* Did you see those salamanders jumping into the water?
settler – the first person to move to a place and to make his or home there
* The settlers of the western United States fought with Native Americans for land and food.
log cabin – a small house made with logs (the thick part of trees) that are placed one on top of another to make the walls
* Did President Abraham Lincoln really grow up in a log cabin as many popular stories say he did?
banjo – a musical instrument with strings and a round body that is often used for country-style music
* Sharon is a very good banjo player, and whenever she starts playing, people start to dance.
true love – a person whom one loves very much and wants to spend one’s life with
* When Jasper met Jordan, he knew that he had found his true love.
still – not moving; not making a sound
* In this region, the air is always still before a big storm.
nonsensical – something spoken or written that does not make sense; something that has no meaning
* That politician’s speech is nonsensical. He wants to increase social services and cut taxes at the same time.
dialect – version of a language, especially used to refer to the way people speak
* Even though Californians and New Yorkers speak a different dialect of English, they can communicate without any problems.
from memory – without needing to look at the words because one knows them already
* Kim can tell you the date of each of her 18 nieces’ and nephews’ birthdays from memory.
whichever – the one or ones out of a group; no matter which
* Whichever costume you choose is fine with me. I’ll wear the one you don’t choose.
whatever – anything or everything that; no matter what
* It’s Jeannie’s decision. Whatever she decides, let’s try to be supportive of her.
tar-and-feather – a physical punishment used to hurt or make someone feel ashamed, where hot tar is put on a person’s skin and feathers put on the body, then the person made to walk or ride down the street so others can see him or her
* The horse thief was tarred-and-feathered, and then made to leave town.
mutually exclusive – two things or events that cannot exist or occur at the same time; two things that cannot be true at the same time
* Having a career and having children aren’t mutually exclusive.
What Insiders Know
The Song Parody: Oh! California
A parody is something people create that copies a writer’s or artist’s style, or copies a “genre” or type of something, usually to create something interesting, funny, and/or amusing. The song Oh! Susanna is so well known that there have been many parodies of this song.
One parody version is called Oh! California. It is sung to the same “tune” (music) as the original. The topic, however, is very different. Oh! California is about The California Gold Rush that began in 1848, when “gold” (a precious yellow-colored metal) was “discovered” (found) near San Francisco, California. This discovery of gold brought over 300,000 people from other parts of the United States and thousands of people from other countries to the area to try to “strike it rich” (make their own discovery to become wealthy).
Oh! California describes the experience of some of the people who traveled to this area. These are the words of the last “verse” (paragraph of a song).
Oh! California
I soon shall be in Frisco, and there I’ll look around,
And when I see the gold lumps I’ll pick them off the ground
I’ll scrape the mountains clean, my boys, I’ll drain the rivers dry
A pocket full of rocks bring home, so brothers, don’t you cry.
Frisco – short for San Francisco
lump – a piece of something, like a rock, that does not have a regular shape
to scrape – to use force with something hard on another hard surface to remove dirt or something else from that surface
to drain – to remove water leaving something empty or dry