= 1578
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 273.
This is English as a Second Language Podcast’s English Café episode 273. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English – and your eyesight. You will be able to see better after you read our Learning Guide – amazing! You can also take a look at our ESL Podcast Store, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about a very well-known movie in the United States called It’s a Wonderful Life. We’re also going to talk about Cape Cod, an area in the state of Massachusetts where many wealthy or rich people go for vacation, or at least that’s what we think. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of a well-known movie, It’s a Wonderful Life. This movie is an American drama that was produced and directed by one of the most famous film directors of the mid-20th century, Frank Capra. Capra created many great films in the 30s and the 40s, including It Happened One Night, Mr. Smith Goes to Washington, one of my favorite movies, and many other films that you may have heard of. His films typically focus on the importance of “unselfishness,” the importance of doing things to help other people, not necessarily yourself.
It’s a Wonderful Life is the story of a man named George Bailey, played by one of the most famous American actors of this period – during this time, Jimmy Stewart. Jimmy is another form of James Stewart. George, the character, runs or manages a local bank, and on Christmas Eve, the day before Christmas, he sends one of his bank employees to make an 8,000 dollar “deposit,” or to put 8,000 dollars into his bank account. However, the employee loses the money. George then talks to someone who is his enemy, someone who he thinks may help him, but an “enemy” is someone who dislikes you and wants to make your life difficult, and that’s exactly what this person does. He says that George will get in trouble; George will perhaps be arrested by the police for bank fraud (fraud). “Bank fraud,” or any kind of fraud, is an illegal, dishonest action, usually a form of stealing money.
Well, George didn’t do anything wrong, but he doesn’t have the money and he thinks he doesn’t really have any good options; he’s not sure what to do. So, he becomes very depressed, very sad. When he goes home, he takes his anger out on his wife and his children. “To take your anger out on (someone)” means that you treat someone or you act towards someone very badly, even though there isn’t a good reason for you to be angry at them. We sometimes called this the “kick the cat phenomenon.” Well, I call it that anyway! “Kick the cat” is the notion that someone, say your boss’s boss gets angry, and then your boss gets angry at you; he takes his anger out on you. You didn’t do anything wrong, but because he’s angry because he got yelled at, he takes his anger out on you. And then you go home and take your anger out on your child, and your child decides to take his anger out on the cat, and so he kicks the cat. A bad thing to do, of course. Don’t kick cats, unless they do something wrong. No, don’t kick cats; let’s leave it at that!
After taking his anger out on his family, George leaves his house and thinks about committing suicide. “To commit suicide” (suicide) means to kill yourself, to end your life. And so, I don’t want to tell you the rest of the story, but there is another person who comes to help him, someone who, in the movie, is his guardian angel. A “guardian” (guardian) is someone who protects you. When a child, for example, loses his parents – if his parents die and he’s still a young child – the government will find a guardian for that child, perhaps an aunt or an uncle, even grandparents, who become the legal guardian. They are the people who are responsible for protecting and taking care of the child. An “angel” is a spirit, in this case from heaven. A “guardian angel” is then this spiritual being that takes care of you. Well, that’s what happens with George. He meets his guardian angel and then the movie continues.
Now, unlike many of Frank Capra’s other movies, It’s a Wonderful Life didn’t do very well at the box office; that is, it didn’t make a lot of money. The “box office” refers to the place where you sell tickets for a movie or for a play. So, when someone says, “the movie didn’t do well at the box office,” we mean it didn’t make a lot of money, and that’s what happened to Capra’s movie It’s a Wonderful Life when it was first released, when it was in the movie theaters in December of 1946. It was nominated for five Oscars, the highest award for movies, but it did not win any of those awards.
During the 60s and 70s, and on through the 80s, the movie started to get shown on television. Part of the reason has do with some complicated problems that were involved in the copyright of the film. “Copyright” is the legal protection that someone who produces a work of art or any creative work, they have copyright on that production. The Center for Educational Development has copyright on these podcasts. That means we have the legal right to own them and to prevent other people from using them unless they get our permission.
This is what happened with It’s a Wonderful Life, there was a problem with the copyright; I don’t want to go in and tell you the whole story. But basically television channels were allowed to show the film, even though they were supposed to pay the owner something, they really didn’t, and they showed the film every Christmas. Lots of different television stations would show the movie, and the movie became more and more popular during this time. When I was growing up, It’s a Wonderful Life was always on TV, even some months that were not even close to Christmas, but especially around Christmas. You could see the movie five or six times because they were showing it on television on different channels all the time. In the early 1990s, that copyright problem was somewhat fixed, and after that point the TV stations did not show the movie as much anymore. But you can still see it almost every Christmas on some television station or another.
It is considered one of the 100 best films made, according to a list by The American Film Institute, one the 100 best made of the 20th century. If you have a chance to see it, I’m sure you will enjoy it. It’s a very what we would call “feel good” movie. It makes you feel good at the end. It’s also called an “inspirational” movie. “To inspire” means to make someone want to
do something, usually something good, and that’s what It’s a Wonderful Life is all about.
Now let’s turn to our next topic, which is Cape Cod, Massachusetts. Normally we talk about American cities; sometimes we’ve talked about American states, American national parks, and so forth. Today we’re going to talk about what’s really a section or part of a state. In this case, the state of Massachusetts, which is located on the eastern coast of the United States. The most famous city in Massachusetts would be Boston. A “cape” (cape) is a part of land that goes out into the water, and that’s exactly what Cape Cod is. If you look at a map of the state of Massachusetts – here let me show you one. Okay, see that? Well, if you look at the map you can see that there’s a little curl, like a letter “C,” that comes out of the state of Massachusetts and goes into the Atlantic Ocean; that’s a cape. Cape Cod is a cape; it’s also an island, because in the early 20th century they dug a hole – a long hole from the top part of the Cape where it connected to the land to the bottom. It’s called a “canal” when you do that (canal). You know about the Panama Canal that connects the Atlantic and Pacific oceans. Well, they built a similar canal on Cape Cod, and so after the canal was built it became an island, and technically it is considered an island by the government, but people still just call it Cape Cod or simply the Cape.
About 200,000 people live on Cape Cod; they live there for the entire year, we would say “year-round.” The year-round residents of Cape Cod number to about 200,000. But the population increases dramatically – a lot – during the summertime. That’s because the Cape has more than 500 miles of “coastline,” or land next to the ocean, so many people go there to spend time at the beaches during the summer. Tourists go there for other outdoor activities, such as biking, fishing, golfing, drinking beer – you know, all of the athletic things you can do! Each August there is a music festival called, I think, the Naukabout Music Festival, which also draws, or brings a lot of people to the island.
Cape Cod is famous for having a lot of bed and breakfasts. A “bed and breakfast” is a business; it’s like a small hotel, but it’s in your house – or in someone’s house, not your house probably. Someone has a big house, they have many rooms in the house, and so they allow people to come and sleep overnight, and usually they get some sort of meal in the morning; it’s part of what you pay for. That’s why it’s called bed and breakfast. Bed and breakfasts are a nice alternative to staying in a hotel or a motel. It’s usually a little bit more expensive, but it’s also more interesting if you like to meet other people.
Anyone can go to Cape Cod, but the area has often been associated with very rich, what we would call wealthy, people. When Americans think of Cape Cod, they often think of it as a place where rich Bostonians – that is, people from Boston – go on the weekend to spend some time to relax, to be by the ocean. In New York City, it would be the Hamptons or Long Island. Here in Los Angeles it would be Santa Barbara, perhaps Catalina Island, maybe San Diego, – places where people may go on the weekend to get away from the big city. That’s what Cape Cod is to Boston, or at least that’s what Americans think.
I’ve been to Cape Cod; I was there in 1972, so just few years ago really! I’m sure it hasn’t changed a lot since I was there.
Most Americans also think, when they think of Cape Cod, of Martha’s Vineyard. A “vineyard” (vineyard) is a large piece of land where grapes are grown for making wine, typically. Martha’s Vineyard is actually a large island just south of Cape Cod. It also has a large population in the summertime. The population “swells” in the summer we could say. “To swell” (swell) means to grow larger. “Swell” can also be used to mean good or great; it’s not as common anymore. But here, it’s a verb and it means to increase, and that’s what happens to the population on Martha’s Vineyard in the summertime.
Martha’s Vineyard is interesting and somewhat unusual, because traditionally it has been known to have a very large population of “deaf” people, people who cannot hear. In the late 19th century, about 1 in 155 people were deaf in Martha’s Vineyard, which is about 20 times as many in the United States in general. The people there created their own “sign language,” their own way of communicating with hands and fingers. Many non-deaf – that is, hearing people, people who can hear learned how to communicate in that sign language making the island a place where deaf people could become part of the larger community. The Martha’s Vineyard sign language was used up until about the mid-20th century. (American Sign Language, which is the sign language most popular in the United States for those who are deaf.)
You may wonder why there were so many deaf people on Martha’s Vineyard in the 19th and early 20th centuries. It’s probably something that happened many centuries ago – well, a couple of centuries ago; we’re not that old of a country – where there were some original deaf “settlers,” people who came to live on the island, and that deafness was “hereditary,” that is, if you have it your son or daughter might also get it, and that created initially a larger number of deaf people on Martha’s Vineyard than in other parts of Massachusetts or the United States. Remember it is an island, so it is more isolated, and that always helps produce unique characteristics, whether it be for language or, in this case, genetics.
Cape Cod and Martha’s Vineyard is associated in the minds of many Americans with the Kennedy family. The Kennedys, you probably know, were a large family; they’re still many Kennedys alive. They became most famous when John F. Kennedy became President of the United States in 1961. There were also two brothers of John Kennedy: Robert F. Kennedy and Edward (or Ted) Kennedy. Ted Kennedy died very recently. Robert F. Kennedy was assassinated – was murdered here in Los Angeles in 1968. And John F. Kennedy, you probably know, was assassinated in Dallas on a very sad day of American history, November 22nd, 1963.
Finally, Cape Cod is also well-known for some of its products, some of things, kinds of food you can buy there, especially cranberries. “Cranberries” are very sour red berries, a kind of fruit that are very popular at Thanksgiving. Most Americans have some sort of cranberry sauce or cranberry dish that they serve with the turkey. I love cranberries, by the way. In case anyone is looking to, you know, buy me something, a can of cranberries would be good! The Cape is also known for certain kinds of fish, such as lobster. It’s also famous for its “shellfish,” which are small animals that live in the ocean but have what we call a hard “shell,” like a hard skin around them that protects them. Clams and oysters are examples of shellfish.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Daisho (Daisho) in Japan. Daisho wants to know the difference between “backward” (backward) and “backwards,” with an “s” at the end.
“Both “backward” and “backwards” mean in the direction toward something behind you or, if we are talking about time, toward the past, moving in the direction of the past. For example: “Some kids think it’s fun to walk backwards,” or “to walk backward.” They move with their face to the front, but they’re moving in the opposite direction. You could also say, “We’re going to go backward in time and talk about the 1970s and what it was like then.”
“Backward” or “backwards” can also be when something is positioned – when it is put in a position where the back is toward the front. For example, some mornings when I am not very awake I put on my shirt, but I might put it on backwards. That is, the back of the shirt is actually in the front. Fortunately, my wife looks at me before I ever leave the house, so she knows to tell me when I have something on backwards.
For those definitions either form, “backward” or “backwards,” is acceptable. In the U.S., “backward” might be a little more common, and in British English you might hear “backwards” more. However, there is one case where you must say “backward” without the “s”, at least in American English, and that is when “backward” is used as an adjective to mean old-fashioned – something that is out of date, something that is not modern. “He has a very backward view of women in society.” He has old-fashion views about that topic. Or, “This is a backward little town.” It’s a town that has attitudes that are no longer fashionable.
There’s one additional expression you may hear: “to bend over backward.” “To bend over backward,” or “to bend over backwards,” means to do is much as possible to try to accomplish your work or to finish your task. “My friend bent over backwards trying to help me get a job,” he did everything possible that he could do.
Our next question is also from Japan; it’s from Yas (Yas). The question has to do with three different phrases: “agree to,” “agree with,” and “agree on.” Let’s start with “agree (agree) with.”
“To agree with” means to like the idea, to have the same opinion as someone else. Typically it is followed by the name of a person. “I agree with John, we should have Bill pay for our dinner.” You could also agree with something that expresses ideas, like a book or a philosophy. “I agree with that book about why American needs to become greener (become more environmentally conscious; to do more for the environment).” “Agree with” can also mean the same as, especially when we’re talking about two different things and comparing them. “My story agrees with his story,” we both said the same thing. Finally, “agree with” can also mean to be likable or to be acceptable, especially when we’re talking about food. “That pork chop did not agree with me.” That’s a way of saying I feel a little sick; my stomach doesn’t feel right. Those are three meanings of “to agree with.”
“To agree to” means to accept someone else’s idea, to say “yes” to someone else’s proposal. “He didn’t agree to the contract because he said it cost too much money.” Or, “The young woman agreed to marry her boyfriend as long has he bought her a new house.” Probably not the best reason to get married!
“To agree on” means to come to an agreement after usually a long time of negotiating – of discussing, of arguing even. “The two countries were at war; finally they agreed on a peace treaty (a peace agreement).”
That’s “agree with,” “agree to,” and “agree on.”
Finally, Antonio (Antonio) in Italia – in Italy wants to know the meaning of the word “howdy” (howdy). “Howdy” is an informal way of saying “hi” or “hello.” It is something that you will see perhaps in an old Western movie, although you will still hear people say it. It became popular I think originally in the southern United States, especially with the state of Texas. So if an American hears someone say “howdy,” they think, “Oh, this person is either from the south or perhaps from the western United States. “Howdy” was often used, as I say, in TV shows and movies about cowboys and the west and southwest U.S. in the 19th century. But as I say, you can say it, but it isn’t something you would probably use every day. It’s an informal greeting, in any case, unless, of course, you want to be considered from the state of Texas for example, in which case you can certainly use it all you want!
You can email us to say howdy or to ask a question. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
unselfishness – with a tendency and desire to do things that help others, but not necessarily oneself
* The way he donated all that money to the church is a great example of his unselfishness.
fraud – illegal, dishonest actions, especially involving money
* Have you ever been a victim of fraud when looking for new investments?
to take (one's) anger out on (someone) – to treat someone badly even though he or she isn't the real reason why one is angry
* I know you're mad that your business is failing, but please don't take your anger out on me.
to commit suicide – to kill oneself; to cause one’s own death
* After losing all his money in the stock market, Aden tried to commit suicide.
guardian angel – an angel who looks after a certain person from heaven
* Do you believe we all have a guardian angel helping us make the right decisions?
inspirational – making someone want to do something, or giving someone the energy and enthusiasm needed to do something
* This is such an inspirational book! Reading it makes me believe I can do anything.
cape – a part of land that extends into the water
* Have you ever visited Cape Peninusla in southwest Africa?
year-round – throughout the year; all year long
* The weather here is great, so we can grow corn year-round.
bed and breakfast – a type of lodging or accommodations in a nice home where guests can spend the night in special rooms and eat breakfast with the owners in the morning
* They've chosen to stay at bed and breakfasts instead of hotels during their honeymoon.
vineyard – a large piece of land where grapes are grown, especially for making wine
* They spent the day visiting many different vineyards and tasting the local wines.
to swell – to increase a lot; to become bigger in number or size
* What can we do to make our sales swell, even when the economy isn’t doing well?
sign language – a way of communicating by moving one's hands and fingers, used by people who cannot hear
* If you know the alphabet for sign language, you can communicate with deaf people by spelling out words.
backward / backwards – moving toward the back; moving into the past; positioned with the back in front
* The baby can walk forward, but falls down when he tries to walk backward.
to agree with – to like the idea of; to be of the same opinion; to be the same as
* Do we all agree with Dante that we should use the money for a new roof, instead of buying new furniture?
to agree to – to accept an idea somebody else suggests; to say ‘yes’ with the intention to act on an idea
* Lynette agreed to help Monica move, but she didn’t know it would take all weekend!
to agree on – to come to an agreement, usually after a time of disagreement
* I know that each of you has a favorite color, but can you agree on what color your new bedroom should be painted?
howdy – an informal greeting meaning “hi” or “hello”
* Howdy, Nick. I’m glad you could make it to our little party.
What Insiders Know
How the Grinch Stole Christmas! by Dr. Seuss
Christmas is a time for “traditions” (things done the same way over time). People put up Christmas trees and watch the classic movie It’s a Wonderful Life on television. Another Christmas tradition is for the family to read with their children the book How the Grinch Stole Christmas! by Dr. Seuss.
Dr. Seuss, whose real name was Theodor Seuss Geisel, was an American author and “cartoonist” (artist drawing funny pictures) who died at the age of 87 in 1991. He wrote in a very “distinct” (unique; easy to identify) way. His stories were written in “rhyme,” much like a long poem. He wrote over 60 children’s books and is perhaps the most well known children’s book authors in the United States.
How the Grinch Stole Christmas! tells the story of a character, the Grinch, who is “bitter” (feeling angry and resentful) and unhappy, living in a “cave” (hole in the side of a mountain) near a town called Whoville. The people in Whoville are happy and “warm-hearted” (friendly and kind). The Grinch is “envious” of the happiness in Whoville and is tired of hearing their happy singing and kind words. He decides to “spoil” (ruin; destroy) their Christmas by stealing their Christmas foods, decorations, and “presents” (gifts). He is successful, but finds that the people of Whoville still celebrates Christmas and is still full of “joy” (happiness). The Grinch learns that Christmas is more than just presents and things. It is a time for people to feel and show “good will” (good thoughts and intentions) towards other people.
Today, the term “Grinch” is “associated” (connected in people’s minds) with a person who is bitter and unpleasant. In fact, it is quite common for people to call others who are unkind or disagreeable to others a Grinch, regardless of whether it is Christmas time or not.