= 1579
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 274.
This is English as a Second Language Podcast’s English Café episode 274. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to continue our series on famous authors (writers), focusing on the American writer Emily Dickinson. We’re also going to talk about one of the most famous events in the U.S. in the early 20th century, the Lindbergh Kidnapping. And, as always, we’ll answer a few of your questions. Let’s get started.
Emily Dickinson was a poet. A “poet” is a person who writes “poems,” pieces of writing that describe often emotions, feelings, ideas. Sometimes poems “rhyme” (rhyme), or have the same sounds at the end of each line or sentence. For example, here’s a very simple poem that rhymes:
Roses are red,
Violets are blue.
Sugar is sweet
And so are you.
Aw, isn’t that nice? By the way, the form “roses are red, violets are blue” is often used in English to make a joke about something by writing something funny for the last two lines of that particular poem.
Emily Dickinson did not write any poetry – any poems that were as bad as the one I just read you. Many of Dickinson’s poems in fact were quite sad; they dealt with sickness and death, but she also wrote about other topics including religion, flowers, and gardens.
Dickinson was very talented; she was also a very prolific author. “Prolific” (prolific) means that she wrote a lot. In fact, she wrote more than 1,800 poems in her life! Only a few of those poems were actually published while she was still alive. The rest were published “posthumously,” that is after her death.
Dickinson was born in Massachusetts in 1830, so the early part of the 19th century. Massachusetts is a state on the eastern coast of the United States in the northeast part of the country. Dickinson was well-educated, she got a good education, but she was a recluse. A “recluse” (recluse) is a person who doesn’t like to interact or communicate with other people, someone who wants to be by themselves. Emily Dickinson was one of those kinds of people. She became more reclusive, in fact, as she grew older and she “rarely,” meaning not very often, left her house or even her room where she was living, although she did have a lot of friendships via, or using, correspondence. “Correspondence,” at least in the 19th century, meant writing letters back and forth. Today we have email and Facebook, back then you had the old paper letters.
Toward the end of Dickinson’s life, she became more and more eccentric. An “eccentric” (eccentric) is a person who behaves in strange ways, behaves almost like they’re crazy; other people don’t understand them. Now, we know that they’re not crazy, but they are very odd. For example, Dickinson never left her house after a certain age. When people came to visit her, she would not see them even though they came to her house. In fact, she would talk to them, but she would be behind a closed door. The few times that she was seen, she apparently wore only white clothing.
But as a poet, Dickinson was definitely ahead of her time. “To be ahead of your time” means that you are doing things in ways that are new, innovative, things that people won’t really understand until perhaps much, much later, sometimes after you’re dead. Dickinson’s poetry was ahead of its time. Her poems had very short lines and sometimes didn’t even have a title (a name). She also used unusual punctuation (periods and commas) and capitalization (making the letter large versus small). Her rhymes also were a little, we might say, “inexact,” they weren’t exactly right. For example, she might use the word “soul” and “all” as if they rhymed, even though although similar they’re not quite the same; they wouldn’t normally be considered rhyming words.
For all of these reasons, Dickinson’s poems were edited heavily before they were published. That is, the people who were publishing the books wanted to change them. Editors tried to make them more “conventional,” that is, more standard, following the rules for that particular time that other writers were following. It can be interesting to compare her original poems as she wrote them with the versions that were published in her “lifetime,” while she was still alive.
Dickinson died in 1886 that the age of 55, but her poetry is still read and enjoyed today. She’s considered one of the most important female writers of the early part of our country’s history. In fact, many times you will see lists of the most important writers of the 19th century, and her name will almost always be there when we’re talking about American writers. Her work is especially interesting today because, as I said, she was one of the very few women who were writing, especially writing very powerful poetry. Even today, some people consider her the best female poet to have written in English. Her poems are read in high schools and in college English classes; I’m sure that I’ve read some during my studies.
I’ll read just one short poem form Dickinson – very short, as many of her poems were. It will give you a little idea of her style. This poem that I’m going to read you is a rhyming poem; you will hear the words rhyme. Let’s listen, and then I’ll give you a very brief explanation of it.
Look back on time with kindly eyes,
He doubtless did his best;
How softly sinks his trembling sun
In human nature’s west.
The poem begins “Look back (meaning think about the past) with kindly eyes (eyes that are kind).” In other words when you think about the past, think about the good things that happened. “He doubtless did his best.” We’re not sure who “he” is. “To do your best” means to do your best job, to do the best that you can. “Doubtless,” here, means without a doubt, certainly. “How softly sinks his trembling sun (sun).” The sun, of course, rises in the east, and then at the end of the day we say it “sets” in the west – it goes down in the sky. She’s talking about how softly this sun sinks. “To sink” is to go down into something liquid, such as water. If you take a coin and you throw it in a pool of water, the coin will sink to the bottom. So she says, “How softly sinks his trembling sun.” “Trembling” is when you are very nervous or perhaps very tired and your hands are not still. They’re moving back and forth quickly. It may be because you are scared; it maybe because you are tired. The sun is, you could I guess say, his life, the things that he did. “How softly sinks his trembling sun In human nature’s west.” Remember the sun sets, or sinks down into the west. “Human nature” is a description of who we are as human beings, our way of being.
Look back on time with kindly eyes,
He doubtless did his best;
How softly sinks his trembling sun
In human nature’s west.
That’s a little bit of Emily Dickinson. I’ll leave the interpretation of the poem to you!
Now let’s turn to our next topic, the Lindbergh Kidnapping. To “kidnap” (kidnap) someone means to take someone, often a child, and demand “ransom” (ransom), or a large amount of money. Kidnapping is taking someone or a number of people, and holding them, and then telling their friends or family or government that you want something before you will give them back. “Ransom” is money, and that’s the most common thing that people ask for when they kidnap someone. Kidnapping has been around since the beginning of recorded history; it’s not a new thing. It’s a very scary, and sometimes fatal thing. That is, people often die in these kidnappings.
The most famous, or one of the most famous kidnappings in the United States was the Lindbergh Kidnapping in 1932. Charles Lindbergh, you may know, was a pilot (someone who flies an airplane) who, in 1927, flew his plane across the Atlantic Ocean from New York City to Paris without stopping. It made him easily one of the most famous men in the United States, indeed one of the more famous men in the world during that time. But Lindbergh was also an explorer, an inventor, someone who was a writer – an author. He also had some particularly strong political ideas. He became famous, however, because of his famous flight – his famous plane ride from New York to Paris. And, because he was famous of course people saw the opportunity to get some of his money, and that’s what happened in the Lindbergh Kidnapping.
His oldest child, Charles Augustus Lindbergh, Jr., was just 20 months, less than two years old, when he was kidnapped from Lindbergh’s home in 1932. The story is that they put the young baby into his “crib” (crib), which is the bed where you put a young, small baby. I guess all babies are young, but! The bed is usually one that has sides to it so that the baby doesn’t fall out. On March 1st, 1932, about 8:00 in the evening, the Lindberghs put the baby into his crib, and at 10:00 that same night they realized that he was gone – he wasn’t there. The father found a ransom note next to the window. Ransom being the money, remember, that you have to pay to get someone back. The ransom note demanded 50,000 dollars, which of course was a lot of money back in 1932, especially during the bad economic times of those years, the so-called Great Depression. In today’s dollars it would probably be close to 800,000 dollars, so a lot of money.
The kidnapping was rather “sensational,” meaning it was something that all of the media – the newspapers, the radio stations, everyone became very interested in this kidnapping because, of course, it was very frightening – it was very scary. It was also very sad; it was a very tragic, horrible thing that happened to these poor parents. All the newspapers had stories about the kidnapping and many people tried to help. Unfortunately, so many people came to the Lindbergh house after the kidnapping – police officers, but also reporters, friends, and family members – that a lot of the “evidence,” the things that could have been used to figure out where the kidnapper went or who he or she was, was destroyed.
The police did find a ladder outside of the bedroom window, but there were no fingerprints on the ladder. A “fingerprint” is made with the oil that is naturally found on your hand. When you touch an object, like a glass, we usually leave behind our fingerprint, which can identify you. Unfortunately, many people touched the ladder before the police had a chance to get fingerprints from it. The verb we would use is “lift” fingerprints from it.
Charles Lindbergh and his wife became very frustrated; they were not happy with the police’s efforts, and so they began to work with other people to get their baby back. They trusted a retired teacher named John Condon who helped them communicate with the kidnappers, and they did, in fact, pay the kidnappers 50,000 dollars in ransom. They were told that they would be able to find their baby in a boat, a small ship in the water. However, when they went there, they couldn’t find the boat, and of course they still did not know where their child was. They had already given the kidnapper 50,000 dollars.
Finally on May 12th, 1932, more than two months after the kidnapping, a man found the body of the small child, the “toddler” alongside the road. The police determined the boy had been killed with a “blow,” or a strong hit to the head that broke the bones in his head, what we call the “skull” (skull). So, a very horrible murder, and perhaps one of the saddest things that can happen to a parent: to lose one’s child, especially a young child.
Even after the body was found, people were very interested in the crime and, of course, now people wanted to find the kidnapper and the murderer. Many people suspected John Condon, the retired teacher who the Lindberghs trusted to communicate with the kidnappers. Other people thought that it was a relative, someone who was a family member. Some people thought it was a servant, people who were working in the home – remember, the Lindberghs were famous and had a lot of money. Police questioned one particular servant, someone who worked for the Lindberghs three times. Her name was Violet Sharp. Right before she was supposed to be questioned a fourth time, she committed “suicide,” she killed herself. Some people thought that this meant – this indicated that she had been the kidnapper and the killer. Other people believe she killed herself because she was so scared.
Eventually, the police identified a man by the name of Bruno Richard Hauptmann as the person who probably was the kidnapper. They went into his home; they found some of the ransom money there. Hauptmann said that he had been left the money by a friend who had already died, but police didn’t believe him. They found other evidence that indicated that the ladder that they found outside of the Lindbergh home was connected to Hauptmann. There was, of course, a trial – a sensational trial. Hauptmann was found guilty, they said that he did the crime, and he was “sentenced to death.” That is, he was to be killed by the government for his crime. He was, in fact, on April 3, 1936, he was in fact executed; he was killed. He never “confessed” however. That is, he never said, “Yes, I did it.” For that reason, some people think he did not commit the murder. Even today, 70 years after the event, people are still interested in the Lindbergh Kidnapping, or at least it still is one of the most famous cases of kidnapping in U.S. history.
Now let’s answer quickly a few of your questions.
Our first question comes from Kyoko (Kyoko) in Japan. Kyoko wants to know the difference between “sure,” “of course,” and “certainly.” Well, all of these mean yes, without a doubt, definitely. Differences among them are small.
“Sure” is rather informal to mean yes. Sometimes, but not always, it is used when the person talking is not very excited about what he or she is agreeing to. For example: “I’m buying a new house. Can you come and help me move my things?” And you go, “Oh, sure.” You’re not very excited about it, but you will do it; you say yes. “Sure” is also an adjective meaning certain. “The Dodgers are sure to win the World Series next year.” Hmm!
“Of course” is often used when the person answering is answering a question that the questioner really already knows the answer to; he expects a certain answer. “Can you help me?” you ask your wife or husband, and they say, “Of course.” You know that that is what they’re going to say, naturally.
“Certainly” is a little more formal than “sure” or “of course.” It’s more likely to be found in writing or in formal business situations. “Will you write me this letter?” You say, “Certainly.” You could say “sure” or “of course,” but “certainly” is a little more formal if your boss is talking to you, for example.
Next Christopher (Christopher) in Germany wants to know the meaning of the word “either.” We talked in Café 209 about “also,” too,” and “as well.” “Either” has some similar meanings with those three words that we’ve already discussed. “Either” can mean “also not.” “There was no food in the kitchen, and there were no dishes either.” Or, “If you don’t go to the dance, I’m not going either.”
“Either” can also mean one or the other when you’re choosing between two things. “Which dress do you like the best?” As a husband you would say, “Well, I would wear either of them,” meaning both of them are nice. You probably wouldn’t actually wear them as the husband – but you, of course, say they both look beautiful my love! Or, “There are two books here. I’ll buy either one but not both.” So there, you are saying, well, it will be this one or that one. “Either” is often used with the word “or.” “Either I go to the movie or I stay home.”
Finally, Tiago (Tiago) in Brazil wants to know the meaning of a song title by a group called The Black-eyed Peas; the title is “Imma Be” (Imma Be). What does this title mean? Well, this is not formal, standard English. “Imma be” is a very informal, slang way of saying “I am going to be.” “Imma be the best (I’m going to be the best).” In English, as in most languages, people often speak very quickly and so sometimes you get what is called compressed speech. “To compress” means to put two things together so that they almost seem like one, and that’s what happens in English. The classic example of this is: “Izzy busy (is he busy)?” But we pronounce it almost as if it were two words: izzy busy? That’s what’s happening here. “Imma be” is a very quick way of saying “I am going to be.”
Now, this particular compressed speech is more to be found among African American speakers of English – black speakers of English, but you may also here it in other pop or popular culture types of media: songs, movies, and so forth.
Can you ask a question of us here at ESL Podcast? Sure! Of course! Certainly! Just email us at eslpod@eslpod.com.
From Los Angeles, California, I am Jeff McQuillan. Thank you for listening. Come back and listen to us again, won’t you, on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
poet – a person who writes poems (pieces of writing that describe emotions and feelings, normally with words that rhyme)
* Jemima likes reading poetry and her favorite poet is Robert Frost.
to rhyme – for something that one says or writes to have the same ending sounds
* Lorna is writing a children’s book, but is having trouble finding a word that rhymes with “orange.”
prolific – for an author, artist, or music composer to produce many works
* She is one of the most prolific songwriters working in the business today.
recluse – a person who does not like to interact with other people and chooses to spend a lot of time at home
* The old man who lives in that house is a recluse, and few people have seen him in the past 10 years.
eccentric – a person who behaves in strange ways that other people do not understand
* Do you think people who have more than 10 or 20 pets are eccentric?
ahead of (one’s) time – to be doing things in ways that are very new and innovative and won’t really become understood or accepted until later
* Few people like Jo’s fashion designs, but I think they’re ahead of their time.
to kidnap – to take someone and demand a large amount of money or something else for his or her return
* The soldiers kidnapped one of the doctors who had been helping the local people.
ransom – for kidnappers to ask for a large amount of money for the return of a person or something valuable the kidnappers have taken
* The kidnappers demanded $1 million in ransom for the return of their daughter.
sensational – for the media and the people to became very interested in something that causes a lot of excitement
* Why do you read that terrible newspaper? It only has sensational news stories and nothing about more important matters.
fingerprint – a mark made on a surface with the oil naturally found on one’s fingertips
* The police detective found the thief because she left fingerprints on the wall when she stole the valuable painting.
to be sentenced to death – for a judge to decide that one’s punishment for a crime should be to die, and the government prepares to kill that person
* The murderer may be sentenced to death or life in prison.
to confess – to admit to committing a crime; to tell others that one is guilty of a crime
* Okay, I confess! I left the dirty footprints on the floor when I forgot to wipe my feet on the doormat when I came home.
sure – yes; definitely; without doubt; of course; certainly
* Sure, I’m sure that he’ll be here at 2:00 today. He told me so this morning.
of course – yes; definitely; without doubt; sure; certainly
* Of course you can borrow my car, as long as you fill it up with gas again when you return it.
certainly – yes; definitely; without doubt; sure; of course
* I’ll certainly remember to give your best regards to my mother the next time I speak to her.
either – also not; one or another
* Like you, I don’t like either one of those paintings either.
Imma be – informal way to say “I am going to be”
* Imma be going to the store this afternoon. Do you want me to get you anything while I’m there?
What Insiders Know
Dognapping
Kidnapping is a crime that we are all familiar with, but have you heard of dognapping?
Dognapping is the stealing of dogs from their owners who are then required to pay a ransom to get the dog back. The dog owners who are most “susceptible” (likely to be affected or influenced) to dognapping are those who own “purebread dogs,” which are dogs with parents from the same “breed” or type. Especially susceptible are those owners with “rare” (not common) breeds of dogs. Some dogs that are victims of dognapping are pets, while others are used for “breeding” (causing animals to have children, usually in an organized and controlled way).
How can a dog owner prevent dognapping? Many “devices” (machines) have been developed to “call attention to” (cause others to look at or listen to) a dog so that it is more noticeable. For example, a dog may wear a “dog collar” (a band of leather or other material place around the neck of a dog) that “flashes” (producing light, turning on and off quickly) and is easy to see, so that others will notice if the dog is being taking away.
Other devices are used to identify a dog if it is stolen. A “microchip” (thin, flat piece of electronic equipment) can be “implanted” (put under the skin) that has information allowing people to identify the dog if it is returned to the owner or if the thief tries to sell it elsewhere. Dogs can also have their ears “tattooed” (with pictures or symbols placed permanently on the skin with ink) so that it can be easily identified. Some owners even keep a “DNA sample” (a small amount of genetic material that is unique to each person or animal) of their “beloved” (very much loved) pet or valuable breeding dog.