= 1556
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 250.
This is English as a Second Language Podcast’s English Café episode 250. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with even more courses in English, as well as our ESL Podcast Blog, and you can follow us on Twitter at eslpod.
On this Café, we’re going to talk about Comic-Con. This is an annual event (once a year) that takes place, or is held in San Diego, California, just south of Los Angeles. It is a convention – it is a group of people who come together to talk about comic books. But actually they do a lot more, as we’ll see. We’re also going to continue our series on famous Americas, focusing on perhaps the most famous magician and escape artist in the United States – at least in U.S. history, he’s not alive anymore. His name is Harry Houdini. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion about Comic-Con, which is officially called the San Diego Comic-Con International. The “con” (con) stands for, or is a short form of “convention,” which is a large meeting or conference of many people who have the same interest in something. Comic-Con brings together many people who are interested in, among other things, comic books. “Comic books,” you probably know, are special books, or sometimes they look like magazines that have lots of drawings and tell a story with words and drawings. Often these are characters that are somehow superhuman – can do extraordinary things. You may be familiar with, for example, Spiderman and Superman. These were, before they were movies, comic books, and still are.
The San Diego Comic-Con has been held in San Diego, California every year since 1970. I have never been there myself – to Comic-Con, I’ve been to San Diego. Comic-Con is normally a four-day event, and it has grown a lot over the years. The phrase “over the years” means over time, or as time has passed. Comic-Con began as a convention showcasing, or featuring comic books, but over the years it has begun to include many other types of what we might call pop or popular culture. The convention now covers video games, fantasy novels, which are basically much longer forms of comic books, toys, horror, animation, and more. “Animation,” is the art of making a movie with drawings that seem to move. If you’re familiar with the Disney movies, they are good examples of animation. Originally, they were all done by hand. You had artists, whom we call animators, drawing the movie. Now, much of it is done on a computer, we call it computer animation. In any case, the popularity of Comic-Con has played an important role especially in the increased importance of animation in recent years. The number of movies – popular movies that have some animation in them or are all animated – all drawings – has increased a great deal, especially in the last 10 to 15 years. Well, Comic-Con is one reason for that growth, because it has helped people get together and share ideas, and those ideas are then used, often, in animated movies.
Comic-Con has also grown in size. Its first year, back in 1970, there were only 300 people who came. In 2007, more than 125,000 people came, filling the San Diego Convention Center. A “convention center” is a large building, which you find in many Americans cities. Los Angeles has a convention center, San Francisco has a convention center, St. Paul has a convention center – almost every big city in the U.S. has these buildings called convention centers. Basically they are large buildings that are places where you can have a big meeting – a large gathering for business, for fun, for comic books. It’s a place where lots of people can come together. Often convention centers have smaller rooms, so you can have one big room, and then you can have smaller rooms with smaller presentations in each one of those rooms. I’ve been to many convention centers for education and language related conferences. Comic-Con now attracts so many people that it really doesn’t fit in the San Diego Convention Center, meaning there isn’t enough room for everyone. In fact, there is some talk that they may move the convention to a different city that has a larger convention center.
Comic-Con still brings together many of the comic book professionals, even though there are other things you can find there. During the convention, these professionals participate in workshops and seminars, which are meetings where you learn how to do something often; they learn how to make better comic books. People also have an opportunity to “preview” new films, or see new, especially animated movies before they are made available to the average person – to what we would call the general public. Artists can also have their “portfolio,” their collection of samples of their work, reviewed by and looked at by companies that publish comic books or make video games and who are looking for new talent – new designers. This convention also has award ceremonies – they give prizes, and they have a costume contest as one of those types of awards that they give. People basically dress up as some of the characters in the comic books – Spiderman and Superman. I have a Superman suit myself. It has a big “S” on the front – if you’ve seen Superman you know. And, what I like the best is it has this long piece of fabric that goes off of the back that’s independent of the shirt, which we call a “cape” (cape). Maybe in the next anniversary video I will wear my Superman suit!
Comic-Con, in addition to having these comic book and animation professionals, also has a lot of companies that are selling things to the people who make comic books and animated movies. At a convention, these are called “exhibitors” (exhibitors). These are people who come, usually are all placed in one big room, they put up tables, and there they try to sell what they are selling. Sometimes the exhibitors are famous comic book artists, where you can go and get them to autograph your comic book. To “autograph” means that a famous person signs his or her name, usually on a book, or a photograph, a drawing, nowadays a CD or DVD. There are many people who love to go and collect famous autographs – the signatures of famous people. Here in Los Angeles, you can go into almost any restaurant, and on the wall of the restaurant you will see some famous people with their autograph on their picture – picture of themselves. The restaurants like to put these up to show that famous people eat here. But in Los Angeles famous people eat everywhere, so that’s why you see them everywhere. Not me, of course. I don’t have a photograph that I can put up on the restaurant, but I’m not famous!
In many ways, Comic-Con is similar to other fan conventions. A “fan” here means a person who is a fanatic about something, who likes something very much. In Comic-Con, you have fans of certain comic books and movies. Maybe the best-known fan convention is Star Trek, where the fans of the first TV show and then movie Star Trek dress up – put on costumes, try to look like the characters in Star Trek, some of them even try to speak the invented language. There are also many fan conventions for video games, and I don’t know anything about them because I don’t play video games, but I am told they have them.
There are a lot of people in Los Angeles, San Francisco, and New York who know about Comic-Con, even people like me who are not involved in making movies or comic books. That’s because they are a lot of people in those cities who are involved in what we call here in Los Angeles “the Industry” – the movie industry – the movie business. I, happily, am not.
Now let’s turn to our series on famous Americans. I think you’re going to like today’s famous American, even if you didn’t know who he was before this Café. Today we’re going to talk about Harry Houdini, who, as I said, was a very well-known magician. A “magician” is a performer – an entertainer who appears to do things that are impossible. The most famous trick – and we call them “tricks,” what a magician does – is to pull a live rabbit out of a hat, or to know what card someone is looking at without seeing it, to be able to guess the number of the card, for example. These are things that a magician might do. Of course, they are not actually doing things that are impossible. They’re just doing things in a way that you don’t see how they can do it.
Harry Houdini was born in Hungary, in Europe, in 1874, but his family moved to the United States when he was only four years old, so he grew up in this country. When he was nine years old, he began performing as a trapeze artist. A “trapeze artist” is a person who does impressive tricks with their body while holding onto a bar that hangs high up in the air. It’s a very dangerous thing, the sort of thing you would see at a circus. Well, Harry Houdini soon became a magician, but he was only moderately successful, meaning that he wasn’t very successful as a magician.
He then turned to a slightly different type of performance when he focused on becoming an escape artist. An “escape artist” is a person who’s able to get out of situations that seem to be impossible. For example, if you take the arms and the legs of the escape artist and you put them in “chains,” in basically long ropes of metal, with locks, and then you put the magician in a box, and then you put the box underwater. Well that is, for most people, a situation where you will probably die. It seems impossible, but the escape artist is somehow able to get out of the box and get out alive. Once again, it’s not actually impossible, it’s just that we don’t know how the escape artist does what he or she does.
Houdini became known, in particular, as “The Handcuff King.” “Handcuffs” (handcuffs) are two metal rings – two metal circles that are held together by a short chain. And, these metal rings are used typically by the police to make sure the person doesn’t use their hands in trying to escape. So when they arrest someone, they will often put them in handcuffs when they catch a “criminal,” someone who has broken the law. If it’s a somewhat serious law, the police will put your hands – basically your wrists in handcuffs. One ring goes around one wrist, one ring goes around your other wrist, and then you can’t move them. Houdini became known as “The Handcuff King” because he was very good at getting out the handcuffs. In fact, he would travel around the United States and Europe, and he would ask police officers in his audiences to handcuff him, sometimes to handcuff him and lock him in jail – in a prison. Then he would “amaze,” or surprise people by finding a way to get out of the handcuffs and sometimes escaping from jail. So, if you are listening to this podcast and you’re in prison well, Harry Houdini is someone you might want to study!
Harry Houdini’s escape tricks made his very famous, but he was also famous for something else. He was well known for debunking people who “claimed,” or said that they had supernatural abilities. To “debunk” (debunk) something means to prove that something isn’t true. “Supernatural” refers to things that cannot be explained by nature or science; they seem, perhaps, to be magical. For example, if you know for sure what is going to happen in the future, or you can tell what someone is thinking even if you’re not looking at them, someone might say, “Well, you have supernatural abilities.”
Well, Houdini didn’t believe that people had supernatural abilities, and so he debunked people, especially people who were charging money for their so-called supernatural powers. In particular, Houdini worked very hard to debunk mediums. A “medium” (medium) here means a person who claims that he or she can communicate with people who are dead, or with the spirits of people who are dead. Houdini would go to these mediums, who would have small gatherings – small meetings called “séances,” and in these meetings people would sit in the dark, usually around a table, and the medium would try to communicate with someone, usually a relative of someone, who had died. Sometimes Houdini would go to these séances with reporters and even police officers, using his knowledge of magic – his knowledge of tricks to figure out how the medium was tricking people, and then he would “expose” the lie, that is he would tell people what was actually happening.
Houdini’s death was almost as unusual as his life. Houdini often told people that he could take a “blow,” that is he could be hit above his waist without getting hurt. After one of his performances – one of his shows one day, he was in his dressing room, the place where he got ready for his performance, when a young man asked if he could try hitting him, and Houdini said “yes.” However, before Houdini could actually prepare himself – before he knew the man was going to hit him, the young man hit him in the stomach. Well, at this time, without Houdini himself knowing, he already had a medical condition, an illness called “appendicitis,” which is when your “appendix,” which is an organ, part of your body below the stomach, becomes infected – there’s a problem with it, and it becomes very painful. Unfortunately, Houdini ignored the pain and didn’t see a doctor. Well, if you have appendicitis, and you don’t go to the doctor to have the doctor remove the appendix, it can kill you. And, in fact, Houdini, when he got on stage had a very high “fever,” his body temperature was very high. However, he went on with his show, not knowing he had appendicitis. His appendix broke, it basically poisoned him, and he died a few days later. This was in 1926 and Houdini was only 52 years old.
Strangely enough, although Houdini didn’t believe in séances and spent part of his life debunking these mediums, his wife, Bess, held séances for 10 years after his death, hoping to communicate with his dead spirit. Some magicians continue this tradition, holding a séance on the anniversary of Houdini’s death. Of course, none of them have communicated with the spirit. None of them really understood, apparently, what Houdini was doing, showing that these séances were tricks – they were false, they weren’t what they said they were.
When I was a boy growing up, I heard many stories about Houdini. He seemed to be a very interesting person for young boys to read about, and there was lots of TV shows that would talk about Houdini even though he had been dead for 50 plus years. He’s still well known as a magician. Sometimes people will use his name to refer to someone who can escape from a difficult situation.
We won’t escape from any difficult situations now. Instead, we’ll answer some of the questions you have sent us.
Our first question comes from Marco (Marco) in Italy. Marco wants to know the difference between the expression “I have just done (something)” and “I just did (something).”
Whenever you see the verb “have” plus a form of another verb, what we call the past participle, typically a form of the verb that ends in “ed,” you have what’s called the present perfect tense in English. “I have just talked to my mother.” “I have just eaten a very big meal.” These are examples of the present perfect tense. You’re talking about something that has happened in the past, although you don’t say exactly when usually. Or, you’re talking about things in the past that began, but that are possibly continuing or could continue easily now or in the future. If you say, “I just talked to my mother,” “talked” is what we call the simple past tense, there’s no “have.” Now we’re talking about something that happened in the past and has ended in the past.
In actual conversation, people use both of these things often to mean the same thing. If there’s a difference, one would be that if you are saying “have done (something),” “I have just talked to my mother,” you’re implying – you’re indicating that you could talk to her again. If you say, “I just talked to John,” you’re not indicating whether it’s possible to talk to John again. It’s difficult, because the word “just” in this case means recently, maybe an hour ago, maybe 10 minutes ago, maybe 10 seconds ago. If you’re saying, “I just have done (something),” it’s often connected with some other action that you are going to take or that could be taken. For example: “I have just explained the rules of this game. Does anyone have any questions?” Here, there’s a connection between what you did in the past and what is going on now in the present. If you say, “I explained the rules to you,” the idea is that you are just describing something in the past and not necessarily anything connected to the present or future. Again, these are small differences, and in conversation or in writing you will often see people use one for the other without making a very strong distinction.
Kelvin (Kelvin) in China wants to know the differences in meaning for the words “suit” (suit), “match” (match), and “fit” (fit). We’re going to talk about all three of these as verbs, because they can also, some of them, be nouns.
As verbs, all three mean things that go together, things that are appropriate for each other. For example: “This sad song I’m listening to suits my mood (suits the way I’m feeling).” It’s complementary; it’s something that is appropriate for my mood, because I’m sad. You could also say, “This sad song matches my mood,” or, “This sad song fits my mood.” In that case, all three words really mean the same thing as verbs, but there are other ways of using them that are different and are separate.
“To suit” can also mean to meet the needs or the wants of someone: “This job suits me,” it’s good for me. You couldn’t say – or you wouldn’t normally say, “This job matches me,” or “This job fits me,” possible, but not very likely. The best verb would be “suit you.” So, that’s one special use of that verb.
“Match” also has some special uses: one is to find an equal or compatible part. For example, if you are wearing a black shirt you might want to wear some pants that match the color, that are the same or that go together well. Someone may say, “That shirt doesn’t match your tie. The colors and patterns are different, and they don’t go together very well.”
“Fit” as a verb has a particular use when talking about clothing. When we’re talking about “fit” and clothing, we’re talking about whether the clothing is the right size and shape. Someone could say, “This new sweater I bought doesn’t fit me, it’s too small.” It’s the wrong size. Or you could say, “These jeans fit me very well.” They’re the right size; they make me look good. “To fit” can also mean to have room for, to have enough space for. If you are driving in a small car, say a Volkswagen, and it’s very small and there are already five people in the car, you won’t be able to fit a sixth person, the car is just too small. So, that’s another use of the verb “to fit.”
Finally, Jason (Jason), living in New York City, wants to know the meaning of the word “levity” (levity). “Levity” usually means someone who is trying to be funny, someone who is not taking a situation serious or seriously enough. If you go to someone’s funeral, when someone dies, you don’t typically expect a lot of levity – a lot of humor. But sometimes in a serious situation like that, some people may say, “Well, we want to have a little more levity here,” meaning we want it to be happier. Just depends on who you are, I guess.
Well, you know who we are, and you can find us at eslpod@eslpod.com if you have a question. We won’t be able to answer all your questions, and it does take a while for us to answer questions because we get so many, but we’ll do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
convention – a conference or large meeting of many people who share a particular interest in something
* Nancy is at a four-day convention for people interested in knitting and crocheting.
comic book – a special book that has more drawings than words, and are usually about characters that are very strong, fast, or can do things that ordinary human beings cannot do
* When Danale was young, he would spend his summers reading comic books and wishing he had superpowers.
animation – the art of making a movie with drawings that appear to move
* The movie studio plans to turn this children’s book into animation for a major film.
autograph – the signature of a famous person; for a famous person to sign his or her name, usually in a book or on a photograph
* Fiona is so excited! She got her favorite singer’s autograph at the concert.
fan – a person who likes something very much, especially when talking about a musician, an actor, a movie, or a TV show
* We’re not big fans of classical music, but we went to the concert to support our neighbor who performed.
magician – an entertainer and performer who appears to do things that are impossible
* The magician pulled a rabbit out of his hat and then made it disappear.
escape artist – an entertainer and performer who is able to get out of situations that seem to be impossible
* Randy is a great escape artist. On stage, he can get out of locked boxes and cages without any problems.
handcuffs – two metal rings that are held together by a short chain, often used by the police to keep prisoners from escaping
* The police officer didn’t put handcuffs on the old woman they arrested for stealing.
to debunk – to prove that something isn't true; to show that a claim is false
* Jiang writes magazine articles that debunk claims made in the medical community.
supernatural – something that seems magical and cannot be explained by nature or science
* Do you believe in ghosts and the supernatural?
medium – a person who claims that he or she can communicate with the spirits of dead people
* After Jan’s father died, she missed him so much that she hired a medium to try to talk to him.
séance – a special meeting where people sit in a dark, quiet room with a medium to try to communicate with someone, often a relative, who had died
* During the séance, the table started to move by itself and the medium began speaking in a strange voice.
to suit – to go together; to be appropriate for something or someone; to meet the needs or wants of someone; to look good on someone or something
* I would have never thought Sandy and Portia would suit each other, but they’ve been married for 10 years.
to match – to go together; to be appropriate for something or someone; to find an equal or compatible part; to provide money equal to an amount that already exists
* Do these brown shoes match with these blue pants?
to fit – to go together; to be appropriate for something or someone; to make to the correct size and shape; to make room for something
* Bosuni has good qualifications, but he’s not a good fit for this job.
levity – humor; amusement; for speech or behavior to not be serious enough for a situation
* People on the committee were tired of arguing and failing to come to an agreement, so Phillip try to introduce some levity by making a joke.
What Insiders Know
The Magic Castle
In Los Angeles, there are many “private clubs” that only allow certain people to become members and to participate in its activities. One “unique” (special; unlike others) private club in Los Angeles that many people don’t know about is one for magicians. This club is called The Magic Castle.
A “castle” is a very large home for kings, queens, and other royal people. In this case, The Magic Castle is a building made to look like a castle and it is located in the Hollywood area of Los Angeles. This “nightclub” (social club open mainly in the evenings, often with music and dancing) is for magicians and magic “enthusiasts” (fans; people highly interested in something).
If you are a member or a guest of a member, you will need to know the secret phrase to enter The Magic Castle, since the front area has no “visible” (able to see) doors. Once you say the secret phrase, the entrance will appear and you can go in.
On a typical evening, you may see several magic shows in its three theaters, and you may also see interesting “displays” (exhibits) of items important in the history of magic. You can also have a meal in its dining room, and there are several bars in an atmosphere similar to what you might find in a standard nightclub.
The idea of the club is to give magicians and fans of magic a chance to see magicians with high-levels of skill perform, for magicians to show each other their tricks, and to “mingle” (interact socially) with others with the same interests.
The Magic Castle also has a program for children called the “Junior Program,” (“junior” meaning a young person) for young magicians who are highly skilled. One week each year, these young magicians perform in a “showcase” (a show for purpose of displaying one’s skills) at The Magic Castle.