= 1201
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,201 – Types of Non-Alcoholic Drinks.
This is English as a Second Language Podcast episode 1,201. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and take a look at our Learning Guide memberships. You can become a member of ESL Podcast and download an eight- to ten-page PDF Learning Guide for each of our current episodes.
On this episode, we’re going to have a dialogue between Asa and Elizabeth about drinking things that don’t have alcohol in them. Sounds a little boring, but let’s get started anyway.
[start of dialogue]
Asa: What can I get you to drink?
Elizabeth: I’ll have a glass of water, thanks.
Asa: Are you sure you don’t want something else? I have soft drinks, orange juice, lemonade, and fruit punch.
Elizabeth: No, thanks. I’m trying to cut back on my sugar intake.
Asa: In that case, how about an energy drink, sports drink, or bottled tea?
Elizabeth: No, really, I’m fine with water.
Asa: Ah, I bet you’d like some tea or coffee, right?
Elizabeth: No, all I want is a glass of water.
Asa: Okay, do you want tap water or bottled water, flavored water or carbonated?
Elizabeth: Do you mean to tell me you have all of those drinks in your refrigerator?
Asa: It pays to own a beverage company.
[end of dialogue]
Asa begins our dialogue by saying to Elizabeth, “What can I get you to drink?” Asa is offering to get something for Elizabeth to drink. Elizabeth says, “I’ll have a glass of water, thanks.” Asa says, “Are you sure you don’t want something else?” He then lists, or gives a list of, the other things he can get for Elizabeth.
He says, “I have soft drinks, orange juice, lemonade and fruit punch.” A “soft (soft) drink” is also called a “soda.” In some parts of the country it’s called “soda pop” (pop). Or if you’re from Minnesota, it’s called simply “pop.” Soft drinks are typically “carbonated beverages,” or things you drink. “Carbonated” just means it has little bubbles in it. Things like Coca-Cola and 7 Up are “soft drinks.”
Asa says he has soft drinks. He also has “orange juice,” which is obviously the liquid made by squeezing an orange. The word “juice” (juice) usually refers to the liquid that you get from a fruit. Asa also has “lemonade” (lemonade). “Lemonade” is made with lemon juice, but you put a little bit of lemon juice into a lot of water. Lemon juice itself is a little strong to drink without mixing it in with water, whereas orange juice can be drunk just as it is. In fact, you don’t want to mix orange juice in with water. It’s not strong enough.
Finally, Asa says he has “fruit punch” (punch). Fruit punch is made by mixing in the juices of several different types of fruit, often combined with sugar. Elizabeth says, “No, thanks. I’m trying to cut back on my sugar intake.” “To cut back on” something is to reduce the amount of something, to have less of something. Someone may say, “I’m trying to cut back on coffee” – that means he’s still drinking coffee but he’s trying to drink less coffee than he did before.
Elizabeth is “cutting back on her sugar intake” (intake). “Intake” is the amount of something you eat or drink, usually. So, your “sugar intake” would be the amount of sugar that you eat or drink. Asa says, “In that case,” meaning since you are trying to cut back on your sugar intake, “how about an energy drink, sports drink, or bottled tea?” Interestingly enough, all three of these things can also have sugar in them.
Let’s start with the first one, which is “energy (energy) drink.” An energy drink is a drink that is supposed to, well, give you more energy so that you can get up and do something. These are drinks that often contain a lot of caffeine, but they often also contain a lot of sugar.
“Sports drinks” are drinks designed for people who are exercising or participating in some sort of athletic event. A sports drink often contains things that will help replace sodium, potassium, and other what are called “electrolytes” that you may lose by “sweating” – that is, when water comes out of your skin because you are working so hard at the physical activity.
“Bottled tea” is, well, just what it sounds like – tea that is put into a bottle and sold. It’s not the kind of tea that you make by boiling hot water and mixing with tea leaves. Bottled tea is something you can buy in a store and is usually drunk cold. Again, a lot of bottled tea also has sugar in it.
Elizabeth says, “No, really. I’m fine with water.” To say you’re “fine with” something means you’re okay with this. You don’t need anything else. Asa says, “Ah, I bet you’d like some tea or coffee, right?” “I bet” means I’m guessing. “I bet you’d like some tea or coffee,” Asa says. Tea, of course, is a hot drink made by placing hot water into a cup with tea leaves in it or another container that has tea leaves in it.
Coffee is a hot drink that was invented by God so that we would be able to function properly in the morning – we would be able to get up and do our work properly in the morning. I have coffee every day. Coffee is made from coffee beans which are crushed or ground up before hot water is poured through them.
Elizabeth says, “No, all I want is a glass of water.” Asa says, “Okay, do you want tap water or bottled water, flavored water or carbonated?” Water that comes from your kitchen sink is called “tap (tap) water.” In order to get water out of the sink in your kitchen or in your bathroom, you have to turn the tap so that the water can come out of the pipe. You open the tap and you close the tap. “Tap water,” then, is water that you just get from whatever water system your house or building is connected to.
In most big cities in the United States, the city government controls the water, and there are water pipes that go to every house. That’s “tap water.” Now, the water that is provided by the government sometimes isn’t very good in terms of the taste. So, some people prefer to get “bottled water” – water that you buy at a store that has been specially cleaned or filtered.
“Flavored water” is water that has some sort of added fruit or other vegetable flavor to it. This has become quite popular in the U.S. in the last few years, especially at certain cafes and restaurants. They will put fruit into the water. Like, oh, I don’t know, strawberries, for example, or vegetables such as cucumbers. They put that into the water and it tastes, well, like strawberries or cucumbers.
I really don’t like flavored water, myself. I don’t know why they do that. Perhaps because the tap water tastes so bad, instead of filtering it or getting bottled water they put some sort of fruit or vegetable into it. Personally I think it’s disgusting, but some people like it. Asa is offering Elizabeth some flavored water or carbonated water. “Carbonated water” is water with dissolved “carbon dioxide” in it, which causes it to have little bubbles just like soda.
Elizabeth says, “Do you mean to tell me you have all of those drinks in your refrigerator?” The question form “Do you mean to tell me” is used when you don’t believe what the other person is saying and you want to make sure that you understand him correctly. That’s why Elizabeth uses it here. She is surprised that Asa has all of these different kinds of drinks in his refrigerator.
“Do you mean to tell me you have all of those drinks in your refrigerator?” she asks. He says, “It pays to own a beverage company.” “Beverages” (beverages) are drinks. Any kind of drink can be called a “beverage.” We find out that Asa “owns” – is the owner of – a company that makes these different beverages. That’s why he says, “It pays (pays) to own a beverage company.”
“It pays to” means it is beneficial to or there are advantages to doing or having something. This is actually a quite useful expression. “It pays to study before a test.” That means it will be to your benefit. It will be advantageous for you to study before you go and take a test; or, “It pays to prepare yourself for an interview.” It will be good for you. It will benefit you if you do that.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Asa: What can I get you to drink?
Elizabeth: I’ll have a glass of water, thanks.
Asa: Are you sure you don’t want something else? I have soft drinks, orange juice, lemonade, and fruit punch.
Elizabeth: No, thanks. I’m trying to cut back on my sugar intake.
Asa: In that case, how about an energy drink, sports drink, or bottled tea?
Elizabeth: No, really, I’m fine with water.
Asa: Ah, I bet you’d like some tea or coffee, right?
Elizabeth: No, all I want is a glass of water.
Asa: Okay, do you want tap water or bottled water, flavored water or carbonated?
Elizabeth: Do you mean to tell me you have all of those drinks in your refrigerator?
Asa: It pays to own a beverage company.
[end of dialogue]
It pays to listen to each and every ESL Podcast, especially those that have the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
soft drink – soda; a sweet, carbonated (with bubbles) beverage
* Do you have any orange-flavored soft drinks?
orange juice – the sweet liquid made by squeezing an orange (a orange-colored sweet fruit), sometimes with added sugar
* Many Americans like to have a glass of orange juice with their breakfast.
lemonade – a cold, sweet drink made by mixing the juice of lemons (a yellow-colored sour fruit) with sugar and water
* During the hot summer months, they enjoy sitting on the front porch and drinking cold lemonade.
fruit punch – a sweet beverage made by mixing several types of fruit juices together, often with pieces of cut-up fruit floating in the container
* This fruit punch was made with pineapple juice, orange juice, cranberry juice, and some lime slices.
sugar – a white or brown substance that is used to sweeten foods and dissolves easily in warm water
* Do you drink your coffee with milk and sugar?
intake – consumption; the amount of something that one eats or drinks
* The medication will help increase your intake of air when you have trouble breathing.
energy drink – a drink designed to provide quick energy, usually containing a lot of sugar and caffeine (a chemical substance found in coffee, tea, and chocolate)
* Many college students use energy drinks to help them stay awake all night to study longer before a big test.
sports drink – a drink designed for athletes to use after intense exercise for a long period of time, containing sodium, potassium, other electrolytes, and a lot of sugar to replace the things that are lost through sweat (the water that forms on the skin as a result of physical activity)
* Marathon runners are encouraged to drink sports drinks throughout their run.
bottled tea – a tea that is cooled and then packaged in bottle, often with added sugar and/or other flavors, and drunk cold
* Do you want some plain tea, sweetened bottle tea, or this one with a lemon flavor?
tea – a hot drink made by placing the leaves of tea plants and other herbs in very hot water for a few minutes
* Do you want black tea or a caffeine-free herbal tea?
coffee – a hot drink made by passing very hot water through ground-up, roasted coffee beans
* Most offices provide coffee for their employees to help them feel more alert and awake.
tap water – water that comes out of the faucet on a sink
* Is it safe to drink the tap water here or should we boil it first?
bottled water – water that is sold in bottles, thought to be purer (cleaner) or safer than tap (regular) water
* Why do people waste money on bottled water, when they can just fill up a reusable bottle at home?
flavored water – water that has an added flavor, usually with fruit, sugar, vitamins, or minerals
* This flavored water tastes like raspberries, but it doesn’t have any sugar in it.
carbonated – with dissolved carbon dioxide in a liquid, causing bubbles to form
* Drinking carbonated water makes me burp.
do you mean to tell me – a phrase used when one does not believe what another person is saying and wants to clarify it
* Do you mean to tell me that the grocery store would actually call the police if it saw a customer eating a grape without paying for it?
it pays to – it is beneficial to; there are benefits or advantages to doing or having something
* Computer programmers can earn a lot of money even without going to college. It pays to study coding.
beverage – a drink
* Are beverages included in the buffet, or do we need to pay for them separately?
Comprehension Questions
1. Which of these beverages is carbonated?
a) A soft drink
b) Fruit punch
c) A sports drink
2. What does Asa mean when he says, “it pays to own a beverage company”?
a) Owning a beverage company has benefits.
b) Owning a beverage company is very profitable.
c) Owning a beverage company requires paying a lot of employees.
Answers at bottom.
What Else Does It Mean?
sugar
The word “sugar,” in this podcast, means a white or brown substance that is used to sweeten foods and dissolves easily in warm water: “This recipe calls for two cups of sugar, but we could probably cut that in half and the muffins would still taste good.” The word “sugar” is sometimes used as a name to show affection for someone: “Hey, sugar, give me a hug.” The phrase “sugar-coated” describes something that has been made to seem better than it really is: “That job description was sugar-coated and really didn’t give applicants an understanding of how hard the work will be.” Finally, a “sugar daddy” is an older man who gives a younger woman money and gifts, often in exchange for sex: “She says she’s in love, but he is old enough to be her grandfather and most of us just think she has found a sugar daddy.”
tap
In this podcast, the phrase “tap water” means water that comes out of the faucet on a sink: “The tap water in this city contains a lot of chlorine, but a simple filter can make it taste better.” The phrase “on tap” describes beer that comes out of a barrel, keg, or large container: “What beers do you have on tap?” The phrase “tap dancing” describes a type of dancing in which the shoes have a small piece of metal on the bottom, designed to make noise as people move: “The girls love tap dancing, but the constant noise gives their parents a headache.” Finally, the word “taps” refers to a song played at night in a military or recreational camp, and at funerals: “Hearing ‘taps’ always brings tears to my eyes.”
Culture Note
The Sugary Drinks Portion Cap Rule
“Obesity” (a condition when people are unhealthy and weigh too much) is a major problem in the United States, and many local governments and organizations are testing new policies to try to “encourage” (help something to happen) Americans to lose weight. One of the most “controversial” (with strong opinions on both sides of an issue) efforts was the Sugary Drinks Portion Cap Rule, also known as the Soda “Ban” (prohibition; when something is not allowed). New York City created the rule to “limit” (place a maximum amount on) the size of soft drinks sold in the city.
Under the rule, people in the city would not be able to buy or sell sweetened drinks with a “volume” (the amount of liquid something can hold) of more than 16 ounces (half a liter). They could still buy larger drinks in grocery stores, but not in restaurants, movie theaters, sports “stadiums” (large buildings where games are played), and similar “establishments” (places; businesses).
The rule’s strongest “advocate” (a person who supports something and wants others to support it too) was Mayor Michael Bloomberg. The Board of Health voted “unanimously” (without anyone voting against it; with everyone in agreement) in favor of the rule in 2012, but in 2013 the New York “Supreme Court” (the highest, most powerful court) “invalidated” (said that it was not allowed) it. In 2014, the New York Court of Appeals also “sided” (took a stance on one side of an issue) against the rule, saying that the Board of Health did not have the “authority” (official power) to “enact” (make into law) the rule.
Comprehension Answers
1 - a
2 - a