= 1204
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,204 – Controlling Information to the Media.
This is English as a Second Language Podcast episode 1,204. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful L.A., CA. (That’s Los Angeles, California.)
Go to ESLPod.com and take a look at our website. It has our ESL Podcast Store on it that contains some ESL Podcast Special Courses in Business and Daily English that I think you will enjoy. In fact, I know it. You can also like us on Facebook. Go to facebook.com/eslpod.
In this episode, we’re going to listen to a little story about controlling information – being careful what kind of information you give – to television stations, newspapers, radio shows, and nowadays, news websites. Let’s get started.
[start of dialogue]
Pablo: Okay everybody, have a seat. The purpose of this meeting is to get everybody on the same page.
I’m passing out the fact sheet we’ve prepared. This fact sheet gives a rundown on what has happened to date so that no one is in the dark about our current situation.
We’ve also prepared these talking points. This is for internal use only. I don’t want them leaked to the media. These talking points have been prepared to help everyone stay on message. Anyone talking to the media off-script will have to answer to me.
These talking points preempt many of the possible questions you’ll be asked. We hope to take the wind out of their sails by addressing some of the media’s most likely questions up front. Any questions?
Suzanna: Um, I’ve read through these talking points and I’m still not sure how to answer one key question.
Pablo: What’s that?
Suzanna: Have we solved the huge issue that’s the cause of our current problems?
Pablo: It goes without saying that if the media ever wants a straightforward answer, our response is always “no comment.”
[end of dialogue]
We are at a meeting in this episode. The meeting is being run by, or managed by, Pablo. Pablo begins by saying, “Okay everybody, have a seat,” meaning please sit down. “The purpose of this meeting,” Pablo continues, “is to get everybody on the same page” (page).
The expression “to be on the same page” means to have the same understanding or knowledge about something. Sometimes it can also mean to have the same opinion about something. So, if you say to someone, “I want to make sure we are on the same page,” you are saying to this person “I want to make sure we both understand the same thing,” or we both agree about this issue or have the same knowledge about this issue.
He says, “I’m passing out the fact sheet we’ve prepared.” “To pass out” is a two-word phrasal verb meaning to give something to many different people, usually a piece of paper. “To pass out” means to distribute – we might also say “to hand (hand) out.” A teacher “hands out” papers to her students, or a boss “passes out” agendas to the members of the committee. “To pass out,” “to hand out,” “to distribute” all mean to give something to many different people. You could also pass out water to people at a party. Everyone gets a glass of water or a bottle of water.
Pablo is passing out a “fact (fact) sheet (sheet).” A “fact sheet” is a piece of paper that contains important details or information about something. Often, fact sheets have simple sentences that just give the most important or “key (key) information.” A fact sheet is usually just one piece of paper that contains a summary of the most important information on a topic. Pablo says, “This fact sheet gives a rundown on what has happened to date so that no one is in the dark about our current situation.”
A “rundown” (rundown) – one word – is a summary of the most important points or pieces of information. We might also refer to it as a “brief” or short “overview” (overview). If, for example, you miss a meeting, you might ask one of your “colleagues,” one of the people you work with, for a “rundown” on the meeting – a summary of the most important things that happened. This is a “rundown” on what has happened “to date,” meaning up to the present point or up to this moment. We might also say “so far.”
It’s a “rundown on what has happened to date so that” – in order that – “no one is in the dark.” “To be in the dark” means to be unaware or uninformed, without knowledge or information about something. We often use this with the verb “leave.” “I don’t want to leave you in the dark” or “I don’t want you to be in the dark.” I want to give you the information.
This expression “in the dark” would probably be used more often in a business situation, although it could also be used in your personal life. “I’m in the dark about what my neighbor is doing with his dog.” I don’t know why it barks or makes noise all the time. I’m in the dark. Maybe he’s teaching the dog to sing. I don’t know. Pablo continues, “We’ve also prepared these talking points.” “Talking points” are key ideas that you want someone to express in an interview, a speech, or a presentation. They’re the points or ideas you are going to talk about.
Nowadays, in business and in politics, “talking points” are the key ideas that everyone from an organization or everyone who is supporting a particular political candidate talks about so that the message is the same coming from the organization. If you have an organization, a business that has had problems, you want everyone to talk about the problems in the same way so that the media – newspapers, magazines, television stations, and so forth – give the same message to their listeners or readers.
You want everyone to be on the same page by using the same talking points, the same basic pieces of information, so that everyone is given the same message. If you don’t do that, that could cause problems. Some people may say one thing. Other people may say something that contradicts that or that is different from that. So that’s why having talking points is such an important part of modern business and modern politics. However, Pablo says that these talking points “are for internal use only.” “Internal (internal) use” means just within the company or within your organization.
The opposite of internal would be “external” (external). A business or political organization might create a set of talking points that it gives to all of the members of the “staff” – the people who work there. But the business or organization doesn’t want the media to get these talking points directly because then it will look like the organization is just trying to present certain information and avoid other information being released. Of course, that’s exactly what the organization is doing, but you don’t want people to think that.
That’s why Pablo says, “I don’t want them,” meaning these talking points, “leaked (leaked) to the media.” “To leak” something is to share secret information to someone who should not have it, especially to someone in the media – a newspaper, a magazine, a television channel, and so forth. Pablo says, “These talking points have been prepared to help everyone stay on message.” “To stay” – or “be” – “on message” means to be focused on the main ideas or main topic, to be consistent in what you are telling people so that you don’t have different messages.
Pablo then warns the people at the meeting, “Anyone talking to the media off-script will have to answer to me.” “Off-script” means not following the talking points, not giving the message the company wants to give. If you say someone “will have to answer to” you, you mean that person will have to explain his behavior to you and possibly be punished for not doing the right thing.
Pablo continues, “These talking points preempt many of the possible questions you’ll be asked.” “To preempt” (preempt) means to do something in order to prevent something else from happening or to ensure that something else doesn’t happen. “To preempt a disagreement” is to do something to prevent a disagreement from happening. The talking points Pablo has prepared will “preempt” possible questions. It will prevent the media from asking certain things. It will give the answers first, if you will.
He says, “We hope to take the wind out of their sails by addressing some of the media’s most likely questions up front.” “To take the wind (wind) out of someone’s sails (sails)” is to take away someone’s advantage or perhaps to make someone feel less confident. In this case, Pablo is trying to make sure the press doesn’t ask embarrassing or critical questions by answering their questions “up front.” To do something “up front” is to do it at the beginning, before something else happens.
If you’re going to rent an apartment in the United States, usually you have to give the first month’s rent “up front” before you actually move into the apartment. Not only the first month’s rent, but usually an additional amount of money in case you cause some damage to the apartment. But we’re not talking about apartments here. We’re talking about answering questions before people ask them.
Pablo then asks if any of the members of his meeting have any questions. Suzanna says that she’s read through the talking points, but she’s not sure how to answer one “key,” or important, question. Pablo says, “What’s that?” meaning “What question?” Suzanna says, “Have we solved the huge issue that’s the cause of our current problems?” In other words, has the company actually solved the problem about which the media is going to be asking questions?
Pablo says, “It goes without saying that if the media ever wants a straightforward answer, our response is always ‘no comment.’’’ “It goes without saying” is an expression we use when we are stating something that is obvious, something that everyone should already know. “It goes without saying that if you come to California, you should bring a hat and sunscreen to put on your skin because we have a lot of sun.” That’s something that we assume everyone knows. “It goes without saying,” Pablo says, “that if the media ever wants a straightforward answer, our response is always ‘no comment.’”
A “straightforward (straightforward) answer” is a direct and honest answer, a clear answer. The media will ask questions and want an honest answer, and if that happens, Pablo says, “Our response is always ‘no comment.’” “No comment” is a phrase used when you don’t want to answer a reporter’s question. You don’t want to answer questions from the newspaper or the television station or the magazine that is asking you questions. It’s a phrase that politicians and businesspeople often use when they are asked questions that they don’t want to answer.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Pablo: Okay everybody, have a seat. The purpose of this meeting is to get everybody on the same page.
I’m passing out the fact sheet we’ve prepared. This fact sheet gives a rundown on what has happened to date so that no one is in the dark about our current situation.
We’ve also prepared these talking points. This is for internal use only. I don’t want them leaked to the media. These talking points have been prepared to help everyone stay on message. Anyone talking to the media off-script will have to answer to me.
These talking points preempt many of the possible questions you’ll be asked. We hope to take the wind out of their sails by addressing some of the media’s most likely questions up front. Any questions?
Suzanna: Um, I’ve read through these talking points and I’m still not sure how to answer one key question.
Pablo: What’s that?
Suzanna: Have we solved the huge issue that’s the cause of our current problems?
Pablo: It goes without saying that if the media ever wants a straightforward answer, our response is always “no comment.”
[end of dialogue]
It goes without saying that the most wonderful scriptwriter on the Internet is our own scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
on the same page – with the same understanding or opinion; with the same level of knowledge about something
* We need to have a conference call to get all our international offices on the same page about the changes to company policy.
to pass out – to hand out; to distribute; to give items to many people
* The members of that church often pass out free bibles to people on the street.
fact sheet – a single piece of paper that contains a lot of detailed or technical information about something so that readers can understand it quickly
* The salespeople have fact sheets about each of the company’s software packages.
rundown – a summary of the most important points; a brief overview
* After a quick rundown of the plan, all the teams started working on their parts.
to date – up to the present point; up until this moment; from the past to the present; so far
* To date, we have received donations of more than $40,000.
in the dark – without knowledge or information about something; unaware or uninformed
* Don’t keep us in the dark. Tell us what happened!
talking points – the key ideas that someone wants to express in a conversation, speech, or presentation
* If you write down your talking points, I can make some PowerPoint slides for your presentation.
internal use – for use within a company or organization, but without being shared with other people who are not part of the company or organization
* These reports are for internal use only. We’ll have a simpler, more attractive version to share with the public by the end of next week.
to leak – to secretly share a document or secret information with someone who should not have it, especially to share it with the media
* Whoever leaked these national security secrets will be punished!
on message – focused on the main topic, without covering other, less related or less important topics
* The speaker did a great job of staying on message even when audience members asked unrelated questions.
off-script – without following the plan of what should be said, especially saying whatever one thinks of at the moment, without a plan
* Those off-script comments were completely inaccurate andp inappropriate. Next time just say what you’ve been told to say.
to answer to (someone) – to have to explain one’s bad behavior to a person in authority, especially if one is likely to be punished or disciplined by that person
* Jake would never get a tattoo, because he knows he would have to answer to his mother!
to preempt – to do something in order to prevent something else from happening; to ensure that something else does not happen
* The governor preempted a planned protest by cancelling the meeting.
to take the wind out of (one’s) sails – to take away someone’s advantage; to make someone feel less confident, proud, or determined
* We were really excited about opening a restaurant, but hearing the horror stories of other business owners really took the wind out of our sails.
up front – directly and at the beginning, before something else happens
* You’ll need to pay $50 up front, and then $10 for each additional month.
it goes without saying – a phrase used when stating something that is obvious or that should be obvious; a phrase used for emphasis when stating something that should already be known by everyone
* It goes without saying that you should bring a birthday present when attending a birthday party.
straightforward – direct, clear, and honest, without hiding or minimizing anything
* Politicians almost never give straightforward responses. They give long answers that rarely answer the questions they’ve been asked.
no comment – a phrase used when one does not want to speak to the media and does not want to be quoted in news stories
* The lawyer advised her client to say, “No comment” in response to any inquiries about the lawsuit.
Comprehension Questions
1. What is the purpose of the meeting?
a) To have everyone write their name on a single piece of paper.
b) To take a group photograph.
c) To make sure everyone has the same information.
2. What does Pablo mean when he says, “This is for internal use only”?
a) People should eat and/or drink during the meeting.
b) People should memorize the talking points.
c) People should not share the talking points with others.
Answers at bottom.
What Else Does It Mean?
in the dark
The phrase “in the dark,” in this podcast, means without knowledge or information about something or being unaware or uninformed: “I’ll have to tell her the news soon. I can’t keep her in the dark forever.” The phrase “a shot in the dark” means a guess made without having any real information or facts: “That test was so hard! Most of my answers were a shot in the dark.” The phrase “after/before dark” means before/after the sunrise: “The children are supposed to come home before dark.” When talking about feelings, “dark” refers to feelings of sadness or depression: “Do you trust him enough to share your darkest fears?” Finally, “dark humor” refers to things that are bad in a funny way: “Chris’s dark humor can be upsetting to people who do not know him well.”
up front
In this podcast, the phrase “up front” means directly and at the beginning, before something else happens: “When roommates establish clear expectations and rules up front, they are less likely to experience conflict later.” A “front” can be an organization or business that prevents others from seeing illegal or secret activities: “The jewelry store on Main Street is a front for drug and arms dealing.” The phrase “to put on a brave front” means to act brave and appear brave to other people when one does not feel brave: “Ivan was really upset that he didn’t win the competition, but he put on a brave front and congratulated the winner.” Finally, a “front office” refers to the people and divisions of a business that interact with the public: “The front office needs to be staffed by employees with really good people skills.”
Culture Note
The Woozle Effect
The “Woozle effect” refers to the way in which “urban myths” (things that many or most people believe, but that are not true, especially when talking about popular culture) “come into being” (are created). Sometimes “publications” such as newspapers, magazines, and websites make statements that “lack” (do not have) proper “citation” (a statement of where the information is coming from) or that cite research incorrectly. When these publications are cited repeatedly by many people, the statements become “widely believed” (believed by many people), even thought there is little or no “evidence” (proof) for them.
A “Woozle” is the name of an “imaginary” (not real) creature in Winnie the Pooh, a popular children’s book. In the story, two of the characters begin following “tracks” (footprints) in the snow, believing they were left by a Woozle, but “it turns out” (in the end they find out) that they have been following their own tracks while walking in a circle.
Today, a “Woozle effect” is a “shorthand expression” (a way of referring to a complex idea in just a few words) for evidence that is based on citation when the actual evidence within that cited “work” (publication or article) is “weak” (not convincing; not good) or “nonexistent” (does not exist; is not there).
For example, many people “make reference to” (talk about) Malcolm Gladwell’s book, Outliers, citing his “concept” (idea) that the key to achieving “world-class” (the best in the world) “expertise” (ability or knowledge) is “largely” (mainly) practicing something for 10,000 hours. Many researchers have questioned his evidence for such a concept, but thanks to the Woozle effect, so many people have referred to his “10,000 Hour Rule” that it has become a widely accepted urban myth.
Comprehension Answers
1 - c
2 - c