= 1208
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,208 – Living on Low Wages.
This is English as a Second Language Podcast episode 1,208. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode that contains a complete transcript of everything we say.
This episode is a dialogue between Dylan and Yvonne about living with not very much money. Let’s get started.
[start of dialogue]
Dylan: Here.
Yvonne: What’s this?
Dylan: It’s information about a job-training program. It’ll give you the skills you need to get steady work.
Yvonne: I don’t need that. I get by with the wages I earn from this job.
Dylan: You’re in a dead-end job straining to make ends meet every month.
Yvonne: I’ve always landed on my feet.
Dylan: But you don’t have any job security. You could be out on your ear any minute. Don’t you want a better quality of life?
Yvonne: My life is fine the way it is. I may not be able to hold on to this job for long, but there will always be other ones.
Dylan: I wish I had your optimism. To hear you speak, you’d think you were one of the privileged few.
Yvonne: It’s all in your outlook on life. I don’t have mortgages to pay, cars to maintain, jets to fuel, and employees to support.
Dylan: You’re right. You should be counting your blessings!
[end of dialogue]
Dylan begins our dialogue by giving something to Yvonne. He says, “Here.” This is sometimes a word we would use by itself when we are giving some object to another person. We are “handing” it, we might say, to another person. Yvonne takes what he is giving her and says, “What’s this?
Dylan says, “It’s information about a job-training program” – a program that will teach you skills to get a job. Dylan says, “It’ll give you the skills you need to get steady work.” “Steady (steady) work” is work that you can rely on, that you will be able to count on. For example, if you have a job with a company and the company always gives you 40 hours of work each week, you have “steady work.” You have work that you can rely on.
The opposite of “steady work” would be “seasonal work,” or perhaps “temporary work.” Here in Los Angeles, if you are an actor, you often don’t have steady work. You may work for a month and then not have any work for a couple of months and then work for a few weeks, and so forth. If, however, you work on a television program that you know will be on for many years, then you could say you have steady work. Steady work is something that most of us have if we have a permanent job with a company.
Yvonne says, “I don’t need that. I get by with the wages I earn from this job.” “To get by” is a two-word phrasal verb meaning “I have enough money or resources to pay for what I need to pay for.” “To get by” means you are able to pay for your food, and your rent, and your clothing, and your cell phone bill, and so forth. It doesn’t mean you’re getting rich, however. Yvonne says she gets by with the “wages” (wages) that she “earns” – that she gets – from her job.
“Wages” refer to money that you get for your work, especially when you are paid by the hour – that is, your company gives you 10 dollars for every hour you work, or 50 dollars for every hour you work. Many people have what are called “salaries” (salaries). A “salary” is when you are paid a certain amount of money regardless of how many hours you work. You might work 40 hours. You might work 60 hours. You get the same amount of money. With wages, you are paid by the hour, typically. If you work more hours, you get more money.
Dylan says to Yvonne, “You are in a dead-end job straining to make ends meet each month.” A “dead-end job” is a job that doesn’t have any opportunities for promotion or advancement. In other words, you’re never going to get a better job in that company or doing what you’re doing. You’re always going to be doing the same thing. The verb “to strain” (strain) here means to try very hard to have something or to do something – to work very hard in order to get something.
Dylan says Yvonne is “in a dead-end job straining to make ends meet.” “To make ends (ends) meet (meet)” means to make enough money to pay for your expenses. It’s similar to the phrasal verb “to get by.” So Dylan is saying that Yvonne is in this dead-end job and she is trying really hard, or having to work really hard, just to have enough money to live on. She is “straining to make ends meet.”
Yvonne says, however, “I’ve always landed on my feet.” “To land (land) on your feet” is an expression that means even in a difficult situation, I always have success, or perhaps, I’m always lucky. If someone loses his job but has a lot of skills or perhaps knows a lot of people, we could say that he will land on his feet. He won’t land on his head and kill himself or hurt himself, metaphorically. He will land on his feet. He will be able to stumble or fall but get up again and be successful.
If you jump off a building and land on your feet, you’ll be able to continue living and walking and breathing, but if you land on your head, you might kill yourself. So, you definitely want to land on your feet. Yvonne says she always lands on her feet even when she has difficult circumstances to deal with. Dylan says, “But you don’t have any job security” (security). “Job security” is confidence that you will have your job in the future, that you are not going to lose your job.
Dylan says, “You could be out on your ear any minute.” The expression “to be out on your ear” (ear) means to lose your job, to be fired. You can imagine, I suppose, someone throwing you out of the building and throwing you down to the ground – that would be literally “landing on your ear.” Dylan says basically that Yvonne could be fired any minute. She doesn’t have very good job security. He says, “Don’t you want a better quality of life?” That is, “Don’t you want to be happier in your everyday life, in your everyday existence?”
Yvonne says, “My life is fine the way it is.” That means “My life is okay the way I am living it now.” “I may not be able to hold on to this job for long,” she says, “but there will always be other ones,” meaning other jobs. “To hold on to” something means to be able to keep something, to continue to have something even when it is difficult. “I’m trying to hold on to this job even though the boss doesn’t like me and I’m not very good at the job.” That’s my case here at the Center for Educational Development. My boss is always trying to fire me and I am trying to hold on to my job.
Dylan says, “I wish I had your optimism.” “Optimism” (optimism) is the belief that things will be better in the future or that things will continue to be successful. The opposite of “optimism” is “pessimism” (pessimism). “Pessimism” is when you think everything is going to get worse. “Optimism” is when you think things will be good in the future or will continue to be good in the future.
Dylan says, “To hear you speak, you’d think you were one of the privileged few.” What Dylan means here is if anyone would listen to you, they would think that you were one of the “privileged (privileged) few.” The “privileged few” refers to the small percentage of people who have a lot of money or are very successful. In the United States, more recently, we’ve had the expression “the 1 percent,” meaning the very richest 1 percent in the country. They would be among the “privileged few.”
Yvonne says, “It’s all in your outlook on life.” Your “outlook” (outlook) is the way you look at the world, the way you see things in general – your perspective. It’s also, of course, the name of the email program in Microsoft Office. But that’s different. “I don’t have mortgages to pay, cars to maintain, jets to fuel, and employees to support.” Yvonne is saying that she doesn’t have any burdens. She doesn’t have anything she needs to take care of in her life such as “mortgages” (mortgages). “Mortgages” are loans that you have to either buy a house or to buy a car.
Yvonne says she doesn’t have any mortgages or loans. She doesn’t have any “cars to maintain” – that is, to keep in good running order. She doesn’t have any “jets” (jets) to fuel. A “jet” is a fast airplane. Here it probably refers to a small airplane owned by a rich person. Yvonne says she doesn’t have to worry about fueling, or putting gasoline into, her own jet. Dylan says, “You’re right,” meaning you are correct. “You should be counting your blessings.”
“To count (count) your blessings” is an expression that means to recognize the good things in your life – to appreciate and be thankful for the good things you have in your life. It could be used by someone who has problems and is telling another person that he should be thankful for not having the problems that the person speaking has. It might also be used simply to tell someone who is unhappy or complaining about his life that he should be happier because he has good things. He should count his blessings.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dylan: Here.
Yvonne: What’s this?
Dylan: It’s information about a job-training program. It’ll give you the skills you need to get steady work.
Yvonne: I don’t need that. I get by with the wages I earn from this job.
Dylan: You’re in a dead-end job straining to make ends meet every month.
Yvonne: I’ve always landed on my feet.
Dylan: But you don’t have any job security. You could be out on your ear any minute. Don’t you want a better quality of life?
Yvonne: My life is fine the way it is. I may not be able to hold on to this job for long, but there will always be other ones.
Dylan: I wish I had your optimism. To hear you speak, you’d think you were one of the privileged few.
Yvonne: It’s all in your outlook on life. I don’t have mortgages to pay, cars to maintain, jets to fuel, and employees to support.
Dylan: You’re right. You should be counting your blessings!
[end of dialogue]
We count our blessings that we have the wonderful Dr. Lucy Tse, who helps us improve our English and our quality of life with her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
steady work – reliable employment that allows one to anticipate how much and when one will work, and how much money one will receive, with a reasonable expectation that the work will continue for a long time
* It can be hard for a builder to get steady work, since there are fewer construction projects in the winter.
to get by – to manage; to have enough money and other resources to survive or to pay for one’s expenses, but without anything extra
* Early pioneers had to make sure they had enough food and firewood to get by during the long winter months.
wages – the money that one receives for one’s work, especially when paid by the hour
* The factory workers are demanding higher wages and safer working conditions.
dead-end job – a job with no opportunity for promotion or advancement
* I enjoy the work, but it’s a dead-end job. If I want an opportunity to earn more money in the future, I’ll need to find a different job.
to strain – to try very hard to have or do something; to make a significant effort to fight against obstacles or challenges
* Harvey is straining to find a way to save his marriage.
to make ends meet – to earn enough money to pay for one’s expenses; to be able to pay for the basic things that one needs
* Many people who earn minimum wage do not have enough money to make ends meet, so they have to rely on help from the government and nonprofit organizations.
to land on (one’s) feet – to have success or good luck, especially in difficult or challenging circumstances
* We were lucky that we landed on our feet this time investing in a risky venture, but we might not be so lucky next time.
job security – stable employment; confidence that one’s job will continue into the future
* In general, state workers have better job security than people working in the private sector, because it is difficult for the government to fire people.
out on (one’s) ear – fired; told that one no longer has a job
* If we can’t find ways to improve the company’s profitability, we’ll all be out on our ear by the end of the year.
quality of life – the amount of happiness and satisfaction that one has in daily life, usually a reflection of health, financial success, family, friends, and a balance between work and pleasure
* When Abdullah was working 80-hour weeks, we had a lot of money, but our quality of life was very poor. Now that he is working less, we are much happier.
to hold on to – to keep; to continue to have, especially if it is difficult to do so
* Kyle holds the record for the long jump at this school, but he won’t be able to hold on to it for long.
optimism – the belief and confidence that something will be successful or that good things will happen
* Jenna’s optimism helped to motivate the other members of her team to find a solution to the problem.
privileged few – the small percentage of people who have had a lot of money and/or success and have many advantages and benefits
* Clarke is one of the privileged few, and he unconsciously assumes that everyone else has had the same opportunities that he has had.
outlook – perspective; the way that one views the world and thinks about things
* It must be hard to keep a positive outlook when working with patients who are very ill and dying.
mortgage – a bank loan used to buy a home that is paid back in regular small amounts
* Does your mortgage payment include taxes and insurance?
jet – a small, fast airplane, especially an airplane owned by a company or a very wealthy person
* CEOs sometimes fly in private jets to avoid wasting a lot of time in lines at airports.
to count your blessings – to recognize and be grateful for the good things in one’s life; to be appreciative of the benefits or advantages one has
* We don’t have much money, but we’re healthy and happy, so we should count our blessings.
Comprehension Questions
1. What does Dylan mean when he says, “You could be out on your ear any minute”?
a) Yvonne could get injured at her workplace.
b) Yvonne could run out of money.
c) Yvonne could lose her job.
2. What does Dylan mean when he says, “You should be counting your blessings”?
a) She should be grateful for what she has.
b) She should pay more attention to her spending.
c) She should evaluate her skills and job qualifications.
Answers at bottom.
What Else Does It Mean?
wage
The word “wage,” in this podcast, means the money that one receives for one’s work, especially when paid by the hour: “Shannon asked her boss for a wage increase.” The phrase “minimum wage” refers to the lowest amount per hour that employers are allowed to pay their employees: “The minimum wage in Ohio is $8.10 per hour.” A “living wage” refers to wages that covers the cost of the minimum basic things that a person needs to live comfortably: “The minimum wage might be enough money in this rural area, but it would not be a living wage in a more expensive place like New York City.” Finally, a “wage freeze” is a period when the government or a company refuses to increase the amount paid to workers: “The federal government is establishing a two-year wage freeze to try to reduce its budget.”
jet
In this podcast, the word “jet” means a small, fast airplane, especially an airplane owned by a company or a very wealthy individual: “Wow, did you see how fast that jet moved across the sky?” A “jumbo jet” is a larger passenger plane: “The 747 jumbo jet can accommodate more than 400 passengers.” The phrase “jet lag” describes the feeling of confusion and tiredness that one feels after a long flight that travels across several time zones: “It’s hard to send our employees to Asia for meetings, because they need a day or two to recover from jet lag.” A “jet” can also be a stream of air or liquid that moves very quickly: “The squid shot out a jet of dark liquid to confuse its predator.” Finally, the phrase “jet black” describes a very dark shade of black: “She died her hair a jet-black color.”
Culture Note
Disparaging Terms Related to American Companies
Some of America’s major employers are often referred to “disparagingly” (in a highly critical and offensive way), especially when referring to their “hiring practices” (how a company attracts and manages employees). For example, a “McJob” is a disparaging term for any minimum-wage job that requires few skills and almost no “independent thought” (deciding one’s own actions and making one’s own decisions). The term comes from the fast-food restaurant McDonald’s, where many employees perform “repetitive” (the same thing over and over again) “tasks” (small jobs or actions) and receive little “compensation” (money and other benefits received for one’s work).
Some people refer to very large “cookie-cutter” (with each item appearing identical to others) homes as “McMansions.” The homes are luxurious and comfortable, but they are not unique or interesting – a “commentary” (statement of one’s opinion) on the food that McDonald’s restaurants serve.
The new verb “Walmarting” refers to what happens when a large company moves into an area and “pushes out” (forces to leave; excludes) small businesses, causing them to “go out of business” (no longer be profitable and have to end the business). The verb reflects the “phenomenon” (something that is observed to happen) that often “follows” (happens next) when a Walmart store opens in smaller communities.
The word “Disneyfication” or “Disneyization” describes “efforts” (attempts) to make an area more tightly controlled, safe, and “uniform” (with everything the same). It is “derived” (created and taken) from the way in which Disney amusement parks create a tightly controlled experience for visitors, so that each person has a very similar, positive experience. But the new word is used to show disapproval of this type of environment.
Comprehension Answers
1 - c
2 - a