= 1209
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,209 – Questioning Mental Competency.
This is English as a Second Language Podcast episode 1,209. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast courses in Business and Daily English, and I think you’ll enjoy them.
This episode is about people like me, who sometimes can be a little crazy. We’re talking about whether someone is mentally competent – whether they can think and behave rationally and logically. Let’s get started.
[start of dialogue]
Claire: What are you doing with all those law books? I thought you retired 20 years ago.
Ray: I’m preparing for my mental competency hearing.
Claire: Mental competency hearing? But your mind is as sharp as it has ever been.
Ray: That’s not what my children think. They are going to court to prove my diminished capacity. They are going to argue that I need a conservator for my estate.
Claire: Nobody who knows you would question your sound mind. There must be another reason for this hearing.
Ray: You’re right. My children want to get their hands on my money, and if they can prove mental incapacitation and impaired judgment, they will get power of attorney.
Claire: And if they get power of attorney . . .
Ray: They would get control of my company and my entire estate.
Claire: So what are you going to do?
Ray: I am going to fight fire with fire. I’m suing them.
Claire: What for?
Ray: Fraud, and I can make it stick. They’re both lacking in common sense. Everybody knows you should never sue an attorney, especially a successful one!
[end of dialogue]
Claire begins our dialogue by asking Ray, “What are you doing with all those law books? I thought you retired 20 years ago.” “To retire” means to leave your job, usually when you are older – say, 65 years or more. Ray says, “I’m preparing for my mental competency hearing.” “Mental” (mental) refers to your mind, to your ability to use your brain. “Competency” (competency) refers to the ability to do something. A “hearing” (hearing) is an opportunity, often in front of a judge in a courtroom, to make your case – to give the judge information so that the judge can make a decision.
Put it all together and we have “mental competency hearing,” which is a legal hearing – a legal meeting, if you will – in front of a judge, in which the judge is going to decide if a certain person has lost his ability to think rationally or clearly. If someone is “not mentally competent,” then different rules apply, different laws apply to that person. For example, if you are not mentally competent, you may not be able to control your own money or even your own medical decisions. Ray says he’s preparing for his mental competency hearing.
Claire is surprised at this. She says, “Mental competency hearing? But your mind is as sharp as it has ever been.” If you say someone’s mind is “sharp” (sharp), or describe someone as “being sharp,” you mean the person is able to think clearly and intelligently. The adjective can also mean to be bright or intelligent or smart. Ray says, “That’s not what my children think.” In other words, Ray’s children think that he is no longer mentally competent, that he cannot take care of himself.
“They are going to court” – that is, his children are going to a judge – “to prove my diminished capacity.” “Diminished (diminished) capacity (capacity)” is when you no longer have the ability to think as clearly as you did, so much so that you probably shouldn’t be handling your own affairs – taking care of your business or personal affairs yourself. Ray says that his children “are going to argue” – they’re going to tell the judge – that he needs a “conservator for my estate.”
A “conservator” (conservator) is someone who takes care of another person’s legal and financial matters, especially when that person is no longer able to do it himself. So, if you are judged to be “mentally incompetent” – that is, not able to take care of your own affairs, your own financial and legal matters – the judge, the government in effect, will give someone that power, and that person is called a “conservator.” Your “estate” (estate) here refers to all of the money and things that you own.
Claire says, “Nobody who knows you would question,” would doubt, “your sound mind.” “To have a sound (sound) mind” is to be mentally competent. We have an expression “to be of sound mind” – that is, you are logical, rational. You are able to think clearly. If you are going to sign a contract or enter into a legal agreement, you must be “of sound mind.” If you are not, then the agreement is invalid. That is, you can’t enter into a legal contract if you are not mentally competent. Even though a lot of people enter into legal contracts that are pretty stupid, that isn’t quite the same thing.
Claire says, “There must be another reason for this hearing.” Ray says, “You’re right. My children want to get their hands on my money.” The expression “to get your hands (hands) on” something means you want to get control of something. “To get your hands on someone’s money” means to take someone’s money or get control of someone’s money.
A beautiful young woman who marries a rich old man maybe trying to get her hands on his money, or it could just be love. Yes, that’s it. It’s love. The same would be true, of course, of a young man and a rich old woman. But let’s not talk about people here in Hollywood. Back to our story. Ray says that his children want to get their hands on his money. He says, “If they can prove mental incapacitation and impaired judgment, they will get power of attorney.”
There are a couple of legal phrases or expressions here. The first one is “mental incapacitation.” We’ve already talked about “diminished capacity.” “Mental incapacitation” is when you are judged not to be able to think clearly. “To be incapable of” doing something is to be unable to do something. So if you are “incapacitated,” you are unable to do a certain thing. You could be “physically incapacitated” – that is, unable to move your body of your own volition, of your own will – or you could be “mentally incapacitated.”
If you are mentally incapacitated, it’s basically the same as being “mentally incompetent.” You are unable to do what you need to do. “To have impaired (impaired) judgment” means to be unable to make good, logical decisions. If you drink a lot of alcohol, for example, you may have “impaired judgment.” People who go to a bar on Friday night and drink a lot of alcohol, by the end of the night often have impaired judgment and tend to believe that other people in the bar are more attractive than they really are.
Ray says that his children want to get “power of attorney” (attorney). The word “attorney” normally refers to a lawyer. The expression “power of attorney,” however, refers to the legal authority that one person has to represent another person in some sort of financial or legal decision or contract. If you have “power of attorney” for your parents, for example, you are able to do everything your parents would be able to do financially and legally in most cases. So you could go to a bank and open up a bank account in their name if you have power of attorney.
Sometimes power of attorney gives you the right to make medical decisions for another person if the government decides that that person is mentally incapacitated. However, you can voluntarily give someone power of attorney. My accountant has power of attorney before the government to represent me on tax matters. You may give power of attorney to your husband or wife in case you are unable to do something because you are mentally or physically incapacitated.
Claire says, “If they,” meaning Ray’s children, “get power of attorney . . .” Ray interrupts and says, “They would get control of my company and my entire estate.” Claire asks, “So what are you going to do?” Ray responds, “I am going to fight fire with fire.” The expression “to fight fire (fire) with fire” means to attack someone using the same methods or techniques that person is using to attack you. Ray says, “I’m suing them.” “To sue” (sue) someone means to bring a legal case against someone in front of a judge.
Claire says, “What for?” meaning what are you suing them for? Ray says, “Fraud, and I can make it stick.” “Fraud” (fraud) are lies or actions that are meant to trick another person, to fool another person, in order to get this other person to give you his money. The expression “to make it stick” (stick) means to demonstrate that it is true, to demonstrate that someone else is wrong, especially if they are guilty of some sort of crime or offense against the law.
Ray says, “They’re both lacking in common sense.” Ray is referring to his two children, saying they are “lacking (lacking) in common sense.” “To lack” means not to have something, to be without something. “Common sense” refers to the normal ability of people to understand the world, to make rational decisions about the world around them. Ray says, “Everybody knows you should never sue an attorney, especially a successful one.”
We find out in the last sentence that Ray himself is a lawyer. He is an attorney, and he was a successful one. He’s saying that his children aren’t very smart. They lack common sense because they are trying to sue their own father who himself is an attorney. There is, however, another expression in English that we could use here that Ray may not like, which is: “A person who represents himself in court” – that is, a person who tries to be his own attorney, as Ray’s doing – “has a fool for a lawyer.” That is, it’s never a good idea to try to be your own attorney, your own lawyer.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Claire: What are you doing with all those law books? I thought you retired 20 years ago.
Ray: I’m preparing for my mental competency hearing.
Claire: Mental competency hearing? But your mind is as sharp as it has ever been.
Ray: That’s not what my children think. They are going to court to prove my diminished capacity. They are going to argue that I need a conservator for my estate.
Claire: Nobody who knows you would question your sound mind. There must be another reason for this hearing.
Ray: You’re right. My children want to get their hands on my money, and if they can prove mental incapacitation and impaired judgment, they will get power of attorney.
Claire: And if they get power of attorney . . .
Ray: They would get control of my company and my entire estate.
Claire: So what are you going to do?
Ray: I am going to fight fire with fire. I’m suing them.
Claire: What for?
Ray: Fraud, and I can make it stick. They’re both lacking in common sense. Everybody knows you should never sue an attorney, especially a successful one!
[end of dialogue]
Thanks to the most competent scriptwriter on the Internet, Dr. Lucy Tse, for her wonderful script.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
mental competency – one’s ability to think clearly, behave rationally, and make informed decisions
* The attorney is arguing that his client doesn’t have the mental competency to understand his crime.
hearing – an opportunity to present one’s case, or one’s version of the story, in a court in front of a judge, with the judge making a legal decision
* In this initial hearing, the judge simply wants to understand your basic arguments. We’ll have a full trial with a jury in a few weeks.
sharp – able to think clearly and intelligently, without any confusion
* Ursula is really sharp. She’ll be able to figure out how to create that spreadsheet in just a few minutes.
diminished capacity – a lessened ability to have or do something, especially referring to one’s ability to think clearly
* Is diminished capacity an unavoidable part of aging, or are there things we can do to keep the brain functioning at its best?
conservator – a protector or guardian who manages another person’s legal and financial matters when that person can no longer do so for himself or herself
* If I die, the conservator will handle my assets and make sure my children have enough money until they are old enough to manage their finances themselves.
estate – all of one’s assets; all the money, land, and buildings a person owns
* It’s so sad when children argue over how to divide and share their parents’ estates.
sound mind – mental competence; ability to think clearly
* This contract is valid only if the parties were of sound mind when they signed it.
to get (one’s) hands on (something) – to obtain or get control of something, especially when doing it dishonestly or when one should not actually have it
* Our competitors would do anything to get their hands on these secret formulas.
mental incapacitation – an inability to think clearly; an injury or condition that makes it impossible for something to think clearly and make good decisions as he or she did before
* The accident caused a lot of injuries, but fortunately, the doctors don’t see any signs of mental incapacitation.
impaired judgment – a weakened or lessened ability to make good, logical decisions, evaluations, or assessments
* When managers are involved in romantic relationships with their employees, it can lead to impaired judgment in performance evaluations and promotion decisions.
power of attorney – the legal authority to represent another person and act on his or her behalf in making financial, legal, and healthcare decisions
* When Marco’s father began to suffer from Alzheimer’s disease, he gave his son power of attorney to manage his affairs.
to fight fire with fire – to use the methods and techniques that are being used against oneself to oppose that person
* I can’t believe Greg called my employer and told those lies! It’s time to fight fire with fire. I’m going to call his boss and do the same thing.
fraud – lies and actions intended to deceive or trick another person, especially to gain money or some other advantage
* The auditors discovered fraud, specifically an accountant who was stealing money from the company.
to make (something) stick – to demonstrate that something is true, especially when talking about an accusation or something bad that has been said about another person; to demonstrates someone’s guilt
* The police must be careful to gather enough evidence to make the charges stick.
to lack – to not have something, or to not have enough of something
* These applicants all lack the technical skills that we’re looking for.
common sense – the ability to think sensibly and make good, rational decisions that others would probably make
* If Francine had just a little more common sense, she wouldn’t get into these ridiculous situations.
attorney – lawyer; a person who represents people and businesses in court
* Did you and your ex-husband use a divorce attorney, or did you file the paperwork yourselves?
Comprehension Questions
1. Who would have trouble demonstrating mental competency?
a) Someone who is sharp.
b) Someone who has a sound mind.
c) Someone who has impaired judgment.
2. What will happen if Ray’s children get power of attorney?
a) They will be allowed to serve as his lawyer.
b) They will be allowed to select his attorney.
c) They will be allowed to make legal and financial decisions for him.
Answers at bottom.
What Else Does It Mean?
sharp
The word “sharp,” in this podcast, means able to think clearly, without any confusion: “Helen is 90 years old and her body is starting to fall part, but her mind is still sharp.” Someone who is “sharp-eyed” is very observant and able to see well: “Sharp-eyed viewers have found a lot of inconsistencies in movies, such as when the level of liquid in a character’s cup changes abruptly between shots.” The phrase “sharp-eared” means able to hear very well: “You must be really sharp-eared to be able to hear that conversation from across the room.” The phrase “sharp-tongued” describes someone who says many mean, critical things about others: “Randall’s sharp-tongued mother never has anything nice to say about his girlfriends.” Finally, the phrase “sharp-witted” means able to think very quickly and react accordingly: “We need a sharp-witted presenter who can respond quickly to the audience’s hostile questions.”
estate
In this podcast, the word “estate” means all of one’s assets, or all the money, land, and buildings a person owns: “When my grandparents died, I inherited their estate, which let me pay for college.” An “estate sale” is when the home of someone who recently died is opened to the public so that people can buy the furniture and other items that remain: “Shoppers can find a lot of good deals at an estate sale, but it’s a little strange to buy things that belonged to a person who just died.” When talking about property, an “estate” is a large area of land around one large house owned by a very wealthy person: “They spend their summer vacations on a country estate.” Finally, “real estate” refers to buying and selling land and buildings: “Which real estate agent helped you buy your house?”
Culture Note
Determining Competence to Stand Trial
Often the “outcome” (how something ends) of a court trial depends on the attorney’s ability to determine the mental competence of the “defendant” (the person who is accused of breaking the law and must defend himself or herself in court) to “stand trial” (participate in a legal court hearing and receive a legal decision). A “competency evaluation” usually occurs before the trial and results in a decision of whether the individual can understand and participate in the “proceedings” (what happens during a legal trial).
Many “psychologists” (scientists who specialize in studying human behavior and mental conditions) specialize in conducting evaluations to determine mental competency. Specifically, they determine whether the defendant understands the “purpose” (why something exists) of the legal trial and whether he or she is able to “cooperate” (work together) with the attorney. The defendant must understand the courtroom proceedings, the “charges” (what someone is accused of), and the potential “penalties” (punishments, such as fines that must be paid or time that must be served in prison). The defendant has to be able to “recall” (remember) the event “in question” (being studied or discussed in the case), including his or her “role” (what one did) in it. Finally, the defendant must be mentally able to “testify” (state the truth before the court) on his or her own “behalf” (for oneself, or for one’s own benefit) and interact with the “witnesses” (people who say what happened).
Sometimes defendants “feign” (pretend to have) mental incompetence to avoid facing the consequences of their crime. In those cases, the psychologist’s job is to demonstrate the defendant’s “malingering” (when one pretends to have an illness or mental condition in order to avoid work or the consequences of one’s action).
Comprehension Answers
1 - c
2 - c