= 1225
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,225 – Being a Good Samaritan.
This is English as a Second Language Podcast episode 1,225. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Why don’t you visit our website at ESLPod.com? Take a look at our Special Courses in Business and Daily English. They are awesome. I think you’ll really like them. You can also like us on Facebook. Go to facebook.com/eslpod, of course – and follow us on Twitter at @eslpod.
This episode is a dialogue between Ana Maria and Gio about helping someone who needs help. Let’s get started.
[start of dialogue]
Ana Maria: Did you see this news article about the Good Samaritan who stopped to help a stranger and died?
Gio: That’s his own fault. Who told him to meddle in other people’s business?
Ana Maria: He wasn’t meddling. He saw that a fellow human being was in distress and was selfless enough to try to help.
Gio: Doing a good deed, was he? Going out on a limb to help someone in need, eh?
Ana Maria: Exactly. I call him a hero.
Gio: I call him a fool. You don’t put yourself in danger to help a stranger. That’s just common sense.
Ana Maria: So you would have just walked right by and done nothing to help.
Gio: If it meant putting myself in jeopardy. You should always look out for yourself, no matter what the situation.
Ana Maria: Great, remind me never to get into a lifeboat with you!
[end of dialogue]
Ana Maria asks Gio, “Did you see this news article about the Good Samaritan who stopped to help a stranger and died?” The term “Good Samaritan” nowadays refers to a kind person, specifically someone who will stop and help someone whom they don’t know who needs help. The term comes from a story from the Christian Bible, specifically from the book of St. Luke in the New Testament of the Bible. It’s what is called one of the “parables,” or stories, that Jesus told in the Bible.
A Good Samaritan refers then to someone who helps another person who needs help, even someone the person doesn’t know. That’s what happened in this news story that Ana Maria is talking about. Unfortunately, the person who stopped to help the stranger died. A “stranger” (stranger) is a person you don’t know, a person who you have never met before. Gio, however, doesn’t feel sorry for the Good Samaritan. He says, “That’s his own fault.”
When you say something is someone’s “own (own) fault (fault),” you mean that the person himself is responsible for his problems. The word “fault” here refers to “blame.” If I say, “It’s your fault” or “It’s your own fault,” I mean you are the person responsible for the bad thing that happen to you. If you have a test tomorrow, an examination tomorrow, and you don’t prepare for it and then you do very poorly on that exam, I will say, “Well, it’s your own fault. You didn’t study. You are the person who is responsible for your poor performance.”
Gio says, “Who told him,” meaning the Good Samaritan, “to meddle in other people’s business?” The verb “to meddle” (meddle) means to get involved in something that you should not be involved in or to try to influence other people’s activities or decisions. “To meddle” is usually a verb we use when we are criticizing another person’s actions, saying the other person should not have done this because it was none of his business.
Ana Maria says, “He wasn’t meddling. He saw that a fellow human being was in distress and was selfless enough to try to help.” The word “fellow” (fellow) as an adjective refers to someone who is in the same category or group as you are or as another person about whom you’re speaking. For example, I can talk about my “fellow Californians.” These are other people who are also, like I am, from California or who live in California now. I could talk about “the Queen of England and her fellow Britons” – that is, people who, like the Queen of England, are also British, are also considered part of that group.
All of us are human beings, except you cats out there. Therefore, “to stop and help a fellow human being” is to stop and help someone who is part of the same group as you are. The Good Samaritan in our story stopped to help a fellow human being who “was in distress.” “To be in distress” (distress) is to be in a crisis, to need help, to be perhaps very unhappy or worried because of some situation you are in. The Good Samaritan was “selfless” (selfless). “To be selfless” means not to think about your own needs – to help others even when it may hurt you.
Gio is not convinced. He says, “Doing a good deed, was he?” This is a form of what we call a “tag question.” It’s often used in this form, and pronounced this way, when someone doesn’t really believe what the other person is saying. And that’s the case with Gio. He doesn’t really think this person was doing a good deed. What’s a “good deed” (deed)? It’s an action you do for another person that will help that person even though you don’t get anything for it yourself.
Gio says, “Going out on a limb to help someone in need, eh?” Once again, he’s asking this as a question, but in a way he’s just expressing his doubt. The phrase “to go out on a limb” (limb) – notice the “b” is not pronounced – means to take a risk, to do something that may cause you harm. This person was “going out on a limb,” doing something risky, in order to help a person “in need” – that is, someone who needed help.
Ana Maria says, “Exactly,” meaning yes, that is in fact what he was doing, even though Gio doesn’t believe it. She says, “I call him a hero” (hero). A “hero” is someone who does something brave, something that requires courage, and therefore is someone whom you would admire and respect. Gio says, “I call him a fool” (fool). A “fool” is someone who isn’t very smart or who does something without thinking rationally or clearly.
Gio continues, “You don’t put yourself in danger to help a stranger.” “To put yourself in danger” (danger) is to do something that may cause you harm, that may hurt you. If you are driving down a freeway, a highway, and you are drunk – you’ve had too much to drink – you’re putting yourself in danger. You may hurt yourself. In fact, you’re putting other people in danger, too. Don’t do that.
Gio says that you should not put yourself in danger to help a stranger. “That’s just common sense,” Gio says. “Common sense” refers to the ordinary or regular ability of people to make good decisions. Something that everyone knows is a good idea is “common sense.” Ana Maria then says, “So you would have just walked right by and done nothing to help?”
Gio says, “If it meant putting myself in jeopardy,” meaning yes, he would have just walked right by and done nothing to help if helping the person would have put him in jeopardy. “To be put in jeopardy” (jeopardy) is to put yourself in danger. Gio is saying here that if he thought he was going to be in jeopardy, in danger, he would not have helped the man – the stranger who needed help. We’re not sure if it’s a man or a woman. Gio says, “You should always look out for yourself, no matter what the situation.”
Gio believes you should always look out for yourself. “To look out for yourself” means to protect yourself first and not worry about anyone else around you. Ana Maria says, “Great, remind me never to get into a lifeboat with you.” A “lifeboat” (lifeboat) is a small boat carried on a larger boat, or ship, that is used if the larger boat is having problems and you need to leave it. If you are on a large boat or ship, you will usually have lifeboats that will be used to get off of that boat if the larger boat or ship is sinking or has some sort of serious problem.
Ana Maria is making a joke here. She says, “Remind me never to get into a lifeboat with you,” meaning she doesn’t want to be in a lifeboat with Gio because Gio won’t help anyone else if there is a serious problem. He will look after himself or look out for himself before helping anyone else.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ana Maria: Did you see this news article about the Good Samaritan who stopped to help a stranger and died?
Gio: That’s his own fault. Who told him to meddle in other people’s business?
Ana Maria: He wasn’t meddling. He saw that a fellow human being was in distress and was selfless enough to try to help.
Gio: Doing a good deed, was he? Going out on a limb to help someone in need, eh?
Ana Maria: Exactly. I call him a hero.
Gio: I call him a fool. You don’t put yourself in danger to help a stranger. That’s just common sense.
Ana Maria: So you would have just walked right by and done nothing to help.
Gio: If it meant putting myself in jeopardy. You should always look out for yourself, no matter what the situation.
Ana Maria: Great, remind me never to get into a lifeboat with you!
[end of dialogue]
We think our hero here at ESL Podcast is Dr. Lucy Tse, for helping her fellow human beings by writing such wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
Good Samaritan – a kind, helpful, and charitable person, specifically referring to a man who helped another in the Book of Luke in the Bible
* Look! A Good Samaritan just stopped what he was doing to help that old woman safely cross the street.
stranger – a person whom one does not know; a person who is not a friend, relative, or acquaintance
* The school principal told parents to teach their children to never get in a car with a stranger.
(one’s) own fault – a phrase used to emphasize that one should be blamed and that one is responsible for the problems caused by his or her actions
* It’s her own fault that she doesn’t have any money in her savings account. She always spends more than she should.
to meddle – to interfere in someone else’s life or affairs; to become involved in something that one should not be part of; to try to influence other people’s activities or decisions
* Don’t meddle in your ex-girlfriend’s personal life. You have no right.
fellow – referring to other people, or specifically to people in the same situation
* If you miss class, try to get a copy of the notes from your fellow students.
in distress – feeling extreme unhappiness, worry, and/or fear; in a crisis situation and needing help
* That woman is in distress and needs an ambulance right away!
selfless – not selfish; not thinking about one’s own needs; treating the needs of others as if they are more important than one’s own needs
* Everyone admires Matt’s selfless behavior. He’s always giving money to help other people, even though he has many uses for the money himself.
good deed – something that one does to help other people, without receiving much or any benefit from it; a selfless act
* Rebecca tries to perform one good deed every day, even if it’s just buying coffee for the next person in line or picking up a piece of garbage from the sidewalk.
to go out on a limb – to take a risk; to choose to do something that might be dangerous or harmful
* We went out on a limb to help you catch the thief. Now it’s your turn to help us.
in need – needing help; requiring assistance
* We volunteer for a nonprofit organization that helps children in need by giving them food and warm jackets.
hero – someone who has shown bravery and who is admired and respected by others; someone who has helped or saved another person
* That man is a hero for trying to save a drowning women.
fool – someone who is foolish or silly and does not think clearly or rationally; someone who makes stupid or unwise decisions
* Which fool thought this project would be a good idea? It has cost our company millions of dollars!
to put (oneself) in danger – to do something that puts one at risk; to do something that puts one in a situation that could result in harm, injury, or death
* The doctors and nurses who treated patients with Ebola put themselves in danger in order to help others.
common sense – the ability to think clearly and rationally and to make good decisions and demonstrate good judgment in ordinary circumstances or situations
* He doesn’t have enough common sense to lock the doors at night.
in jeopardy – at risk; in danger; in a situation that could result in harm, injury, or death
* If the stock market continues to perform poorly, all our investments could be in jeopardy.
to look out for (oneself) – to focus on protecting oneself and doing what will benefit oneself, with little or no consideration for other people’s needs
* Benedict was looking out for himself and didn’t realize how his decision would impact his team members.
lifeboat – a small boat carried on a larger boat, so that if the larger boat sinks, people can get into the lifeboat and be safe until they can be rescued
* More than 1,500 people died when the Titanic sank, because the ship didn’t have enough lifeboats.
Comprehension Questions
1. Which of these activities involves putting oneself at risk?
a) Meddling in other people’s business
b) Going out on a limb
c) Looking out for oneself
2. Why wouldn’t Gio have helped the stranger?
a) Because he wouldn’t want to put himself in danger.
b) Because he only helps people as a way to make money
c) Because he thinks the stranger deserved what happened.
Answers at bottom.
What Else Does It Mean?
(one’s) own fault
The phrase “(one’s) own fault,” in this podcast, is used to emphasize that one should be blamed and that one is responsible for the problems caused by his or her actions: “It’s her own fault that she missed her flight. She should have planned to arrive at the airport earlier.” The phrase “at fault” describes someone who is responsible for having caused a problem, especially someone who must accept a punishment or pay a fine as a result: “The judge found that the landlord was at fault and ordered the landlord to pay $3,000 to the tenant.” Finally, the phrase “to find fault with” means to criticize someone or something: “Aunt Gemma is never happy. She is constantly finding fault with other people’s decisions and actions.
deed
In this podcast, the phrase “good deed” means something that one does to help other people without receiving much or any benefit from it: “Xavier became known for performing good deeds without being asked.” Sometimes the phrase “(one’s) good deed for the day” is used sarcastically to describe someone doing something that appears to be generous and helpful, but is actually insignificant or self-serving: “Wow, you gave that beggar two cents. I guess you’ve done your good deed for the day.” Finally, a “deed” is a title, or a piece of paper that shows ownership of a home or piece of property: “Whose name is on the deed to the house?” Or, “Who will inherit the deed to the property when the owner passes away?”
Culture Note
Good Samaritan Laws
Good Samaritan laws are “enacted” (made into law) to protect people who help others “with good intentions” (wanting to do something good, without any bad or evil reason for doing something). When people “observe” (see) someone in distress, their first reaction is often to help, but in some cases, this has led to problems.
For example, a person who is helped might “claim” (state) that his or her “right to refuse treatment” (the ability to say that one does not want to receive medical care) was violated by the Good Samaritan and even “sue” (take to court) that person. Or if the Good Samaritan does something incorrectly and, for example, accidentally breaks the other person’s “ribs” (bones in the chest) while performing “CPR” (cardiopulmonary resuscitation; a way to help someone whose heart has stopped beating), there could be “legal” (related to the law) or financial (related to money) consequences.
Good Samaritan laws are enacted to protect the “bystander” (the person who observes something or happens to be present when something happens) in such situations. The “intent” (purpose; aim; what something is trying to do) of the Good Samaritan laws is to reduce the bystander’s “hesitation” (delay caused by fear or uncertainty) in helping someone who needs “aid” (help; assistance).
Good Samaritan laws “vary” (are different) by “jurisdiction” (the local, regional, or state government that has power and control over an area). In some parts of the United States, Good Samaritan laws protect anyone who tries to help someone in distress. In other jurisdiction, the laws apply only to “trained personnel” (people who have been taught to perform a particular job or service), like firefighters, doctors, and nurses.
Comprehension Answers
1 - b
2 - a