= 1227
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,227 – Altering Clothing.
This is English as a Second Language Podcast episode 1,227. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast courses in Business and Daily English. You can also like us on Facebook. Go to facebook.com/eslpod.
On this episode, we’re going to listen to a dialogue between Mom and Sa’ad about changing the size of your clothing. Let’s get started.
[start of dialogue]
Mom: Put on these pants and this shirt, come over here, and stand still. I need to alter your brother’s clothes to fit you.
Sa’ad: Oh, Mom!
Mom: Hurry up. I need to let down the hems and take up the sleeves. I don’t think I have to take in the pant legs, but I might have to let out the waist a little.
Sa’ad: Ouch!
Mom: Sorry, but you need to stop moving around or your hem will be uneven and your seams will be crooked. You and your brothers are growing so fast I feel like a full-time tailor!
Sa’ad: Are we done?
Mom: No, we’re not. Stay right there. You can help me iron a crease into this shirt before I put it through the sewing machine.
Sa’ad: Oh, Mom!
Mom: Don’t “Oh, Mom” me. This machine doesn’t seem to be working. I hope I don’t have to stitch all these by hand.
Sa’ad: Mom, since I’m growing so fast, I’ll probably grow out of these clothes in a couple of months. Let’s wait until after my growth spurt to alter them.
Mom: And what will you wear in the meantime, high waters?
Sa’ad: No, shorts!
[end of dialogue]
We have in this dialogue a mother and her son. The mother says to her son, “Put on these pants and this shirt, come over here, and stand still.” The mother is telling the son to put on a pair of pants and a shirt and then to walk over to her and stand still. “Stand still” means don’t move. Don’t move your arms or your legs or any part of your body. The mother says, “I need to alter your brother’s clothes to fit you.” The mother is going “to alter” some clothing. “To alter” (alter) means to change or modify something, especially when we are referring to clothing.
You alter clothing so that it “fits” (fits) you better. It is the correct size for you. “To fit” means to be the correct size for you, when referring to clothing. Mom wants to alter the brother’s clothing to fit her son, Sa’ad. The son says, “Oh, Mom!” He says it in a way that indicates he’s complaining. He doesn’t like what his mother is doing. The mother, however, says, “Hurry up. I need to let down the hems and take up the sleeves.” “To let (let) down” in this case means to increase the length of something, such as the length of the pants.
“Pants” are, of course, articles of clothing that you wear over your legs. If a pair of pants are too short, sometimes you can “let down the hem” (hem) of the pants. The “hem” is the bottom of the pants, which often has more material, more of the pant leg underneath. If you take out the “hem,” the sewing that is on the bottom of the pant leg, there is often more material that can be pulled down to make the pants longer. That’s what Mom is doing in our dialogue. She’s going to let down the hems. She also is going “to take up the sleeves.”
The phrasal verb “to take up” is the opposite of the phrasal verb “to let down” when we’re talking about clothing. “To take up” means to shorten something, to decrease the length of something – in this case, Mom wants to “take up the sleeves” (sleeves). The sleeves are the parts of a shirt that go over the arms. If you put on a shirt that is too big for you, the sleeves might be so long they go over your hands. In that case, you would need to take up the sleeves. You would need to shorten them. Mom wants to take up the sleeves in Sa’ad’s brother’s clothes so that they fit him.
She says, “I don’t think I have to take in the pant legs, but I may have to let out the waist a little.” There are two more phrasal verbs that Mom uses here in talking about altering clothing. They are “to take in” and “to let out.” “To take in” means to make something smaller around, especially when we’re talking about the waist of pants or of a skirt. If you, for example, lose weight and you are now skinnier, your pants will be a little loose around the middle of your body, around your waist. You might have to take in your pants – that is, you might have to change them so that the waist is smaller.
Let’s hope that is a problem you have. For many people, however, if you gain weight, if you get fatter, you might have “to let out” the waist of the pants. “To let (let) out” means to make the waist bigger. Sometimes it’s not possible to let out the waist of a pair of pants. Sometimes you just have to buy a new, bigger pair of pants. Mom doesn’t think she’ll need to take in the legs of the pants. She doesn’t think she’ll need to make the pant legs smaller, but she might have “to let out the waist a little” for her younger son.
Sa’ad says, “Ouch!” “Ouch” is the word we use when we are expressing pain, if someone hurts us. We may say, “Ouch!” (ouch). Mom says, “Sorry, but you need to stop moving around or your hem will be uneven and your seams will be crooked.” “To be uneven” (uneven) means to be not straight. “To be uneven” is the opposite of “to be even,” which is straight. You want the bottom of your pants, the hems of your pants, to be even, not uneven.
Another word for “uneven” is “crooked” (crooked). Something that is “crooked” is something that is not in a straight line, something that is not even. There’s another meaning of the word “crooked,” which is to be someone who is dishonest, who takes money illegally. Many politicians around the world are “crooked.” They are dishonest by taking money and doing things because someone gave them money. Here, however, “crooked” just means not straight, not even.
Mom is worried that because her son keeps moving around while she’s trying to measure and make alterations of the clothing, the seams of the clothing will be “crooked.” “Seams” (seams) refers to the line of sewing where two pieces of the material, what we call “fabric” (fabric), come together in a piece of clothing. So, if you look at a pair of pants, if you look at the legs of the pants, there will be a “seam” – a place where the material or the fabric is sewn together, is connected. That’s called a “seam.”
Mom says, “You and your brothers are growing so fast I feel like a full-time tailor.” A “tailor” (tailor) is a person who sews clothing professionally, who gets paid to sew clothing. A tailor is often a person who makes clothing as well. For example, if you want to buy a nice professional suit – a suit coat and pants – you might go to a tailor and have a suit made professionally that will cost you a lot of money. You might go to a tailor just to have your clothes altered – just to have them changed so that they will fit better.
A “tailor,” then, is someone who works and gets paid for doing the kinds of things that Mom is doing for free in our dialogue and many moms have done for free, including my own. The son says, “Are we done?” Mom says, “No, we’re not,” meaning “We are not finished.” “Stay right there. you can help me iron a crease into this shirt before I put it through the sewing machine.” A “crease” (crease) is a line in clothing that is made by using what’s called an “iron” (iron). An iron is a hot piece of metal that you put over clothing so that the clothing is flat.
Sometimes, especially for a pair of formal pants, you want a crease in the pants. You want a line that you can see in the fabric. Mom is going to have Sa’ad do a crease in the shirt. She wants him to do this before she puts the shirt “through the sewing machine.” The “sewing (sewing) machine” is a machine that sews or puts two pieces of fabric together with something called “thread” (thread). “Thread” is like a very thin piece of string that you would use in clothing in order to put two pieces of fabric or material together.
Once again the son goes, “Oh, Mom!” He’s complaining again. Mom says, “Don’t ‘Oh, Mom’ me,” meaning don’t say that to me. Don’t complain to me. “This machine doesn’t seem to be working,” Mom says. “I hope I don’t have to stitch all these by hand.” “To stitch” (stitch) means to connect two pieces of fabric or material by putting the thread into the material in the form of a circle. You typically take a sharp metal object called a “needle” and you put it into the material with a piece of thread tied onto it, and you take the needle and pull it in and out of the material, forming little circles.
That’s “stitching” the material or the fabric together. Mom says she’s going to have “to stitch” all of these “by hand.” “By hand” means using her own hands, not using the sewing machine. Sa’ad says, “Mom, since I’m growing so fast, I’ll probably grow out of these clothes in a couple of months.” “To grow out of clothes” means to get bigger so that you will no longer be able to wear a certain piece of clothing. When children grow up, they “grow out of” the clothing they have and have to get new, bigger clothing.
The son is saying that he’s growing so fast that he’s going to grow out of the clothes that Mom is working on right now in a couple of months. He says, “Let’s wait until after my growth spurt to alter them.” The term “growth spurt” (spurt) refers to a period of time when a child grows very quickly. Even in a few months, the child gets taller or bigger. Sa’ad is saying that Mom should wait and not alter these clothes right now, and instead alter them after he has another growth spurt.
Mom says, “And what will you wear in the meantime?” meaning what will you wear between now and the end of your next growth spurt. She says, “And what will you wear in the meantime, high waters?” “High waters” (high waters) are pants that are too short for you, pants that end several inches above the ankle. They’re called “high waters” because, of course, if you were walking to the street and there was a lot of water in the street, your pants wouldn’t get wet because they are so high up on your legs.
Her son isn’t proposing to wear the pants as high waters. He says, “No, shorts!” meaning he wants his mother to make the pants into a pair of shorts.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mom: Put on these pants and this shirt, come over here, and stand still. I need to alter your brother’s clothes to fit you.
Sa’ad: Oh, Mom!
Mom: Hurry up. I need to let down the hems and take up the sleeves. I don’t think I have to take in the pant legs, but I might have to let out the waist a little.
Sa’ad: Ouch!
Mom: Sorry, but you need to stop moving around or your hem will be uneven and your seams will be crooked. You and your brothers are growing so fast I feel like a full-time tailor!
Sa’ad: Are we done?
Mom: No, we’re not. Stay right there. You can help me iron a crease into this shirt before I put it through the sewing machine.
Sa’ad: Oh, Mom!
Mom: Don’t “Oh, Mom” me. This machine doesn’t seem to be working. I hope I don’t have to stitch all these by hand.
Sa’ad: Mom, since I’m growing so fast, I’ll probably grow out of these clothes in a couple of months. Let’s wait until after my growth spurt to alter them.
Mom: And what will you wear in the meantime, high waters?
Sa’ad: No, shorts!
[end of dialogue]
We wouldn’t alter a word of the wonderful dialogues by our wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to alter – to change or modify something, especially to change clothing so that it fits better
* Could you alter this suit to fit me now that I’ve gained a little weight?
to let down – to increase the length of something so that it hangs lower, by using the extra fabric that was previously folded under and sewn in place
* Felipe grew another few inches over the summer, so we need to let down the pants of his school uniform.
hem – the sewn edge of a piece of fabric that has been folded under
* The school requires that the hem of girls’ skirts must be at or below their knees.
to take up – to decrease the length of something so that it does not hang as low, by folding additional fabric under and sewing it in place
* Please take up these pants so that the ends don’t drag on the ground.
sleeve – the tube of fabric that covers one’s arms as part of a shirt, dress, or jacket
* Mom told Daniel to roll up his sleeves so they don’t fall into his food.
to take in – to make something smaller around, especially when referring to the waist of pants or a skirt
* Yolanda lost 30 pounds and had to take in all her pants and skirts.
to let out – to make something bigger around, especially when referring to the waist of pants or a skirt
* If I eat all these doughnuts and cookies, I’ll have to let out my pants!
uneven – not even or straight; lopsided; crooked
* It was a horrible haircut that was uneven in the back.
seam – the line of sewing where two pieces of fabric meet
* If you keep pulling on that fabric, the seam will rip.
crooked – not straight or event; not in a straight line
* Whenever I write on paper without lines, my writing is crooked.
tailor – a person who sews clothing to fit individual customers
* Wow, your suit fits you so well! Who is your tailor?
crease – a line made in fabric by pressing it down at a high temperature with an iron
* These pants need to be ironed so that they have a crease down the front of each leg.
sewing machine – a machine that sews pieces of fabric together with thread
* May I please borrow your sewing machine to make some simple curtains for the bedroom?
stitch – one loop of string or thread in a line of loops that are being sewn
* These are decorative stitches that are meant to be seen on the outside part of the shirt.
by hand – done manually, with one’s hands, without the use of a machine
* Did you draw these by hand, or did you draw them with a computer?
to grow out of – to no longer be able to wear, have, or do something because one has become too big or old for it
* The children are growing out of their clothing so quickly that we have to go shopping almost every month!
growth spurt – a period of time when a child grows very quickly
* During his last growth spurt, Toshi grew three inches in just a month and a half.
high waters – pants that end several inches above the ankle and not considered fashionable
* If you’re going to wear high waters, at least make sure your socks match!
Comprehension Questions
1. What might you do if your clothes are too big?
a) Let down the hems.
b) Take in the legs.
c) Let out the waist.
2. What are high waters?
a) Clothing that does not fit well.
b) Pants that are too short.
c) Clothes that are wet.
Answers at bottom.
What Else Does It Mean?
to take up
The phrase “to take up,” in this podcast, means to decrease the length of something so that it does not hang as low, by folding additional fabric under and sewing it in place: “Please take up these pants so that I don’t trip over them.” The phrase “to take up” also means to try a new activity or adopt a new hobby: “Have you thought about taking up weight lifting?” The phrase “to take after (someone)” means to resemble or appear similar to an older relative: “Wow, Mariah really takes after her mother. They almost look like sisters!” Finally, the phrase “to take over” means to take control of something: “Nobody expected the new employee to take over the project so quickly.”
to grow out of
In this podcast, the phrase “to grow out of” means to no longer be able to wear, have, or do something because one has become too big or old for it: “Eleanor was really sad when she grew out of that sweater. It was her favorite.” The phrase “to grow apart” means for two people to become more distant so that their relationships is not as close as it used to be: “They were best friends in high school, but they grew apart in college.” The phrase “to grow on (someone)” means for one to begin to like something more and more: “At first, I thought Thai food was too spicy, but it has grown on me and now I love it.” Finally, the phrase “to grow up” means for a child to become an adult: “What do you want to be when you grow up?”
Culture Note
Getting Rid of Baby Clothes
Children grow quickly, but it can be difficult to know what to do with the clothes and toys that they “leave behind” (no longer need because they are too big or old). Some people give them to friends or relatives with younger children or donate them to a “thrift store” (a store that sells used, donated items at low prices). Other people try to sell them in a “garage sale” (an event where people sell things they no longer need in front of their home) or at a “consignment store” (a store where people buy used items and the sellers receive a percentage of the sales amount).
But some people have an “emotional attachment” (strong feelings) to their children’s baby clothes and aren’t able to “part with” (get rid of; be separated from) them. These people might “keep them in storage” (keep something for future use) for their grandchildren, or they might “repurpose” (use something in a different way) the items. For example, some people make “quilts” (warm blankets made by sewing together many different pieces of fabrics) out of baby clothing. They might cut out pieces of many different items of their baby’s clothing and sew them into a quilt. That way, they can continue to use the fabric, and looking at it reminds them of what their baby wore.
Some people like to “bronze” (cover in bronze, a shiny, dark metal) baby shoes. A layer of “copper” (an orange-colored metal) is attached to the shoes, preserving them as a “keepsake” (something that helps someone remember something). Bronzed baby shoes might be kept on a “mantle” (the shelf above a fireplace), on a desk, or hanging from the “rear-view mirror” (the mirror that allows a driver to see behind a car) of a car.
Comprehension Answers
1 - b
2 - b