= 1234
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,234 - Traveling with Pets.
This is English as a Second Language Podcast episode 1,234. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com to download the Learning Guide for this episode that will give you a complete transcript of everything we say. This episode is a dialogue between Eva and Amin about traveling with your pets. Let’s get started.
[start of dialogue]
Amin: I can’t stand to be away from Fifi for two weeks. Can’t we bring her along?
Eva: We’ve talked about this before. Our dog does not like to travel. We’ll board her.
Amin: What if we get a really big crate or carrier that Fifi will feel comfortable in?
Eva: It won’t make a difference if she’s left out on a hot tarmac and has to spend hours in cargo hold.
Amin: It’ll be well ventilated and the crate will be large enough for her to turn around in.
Eva: She’ll still bark and whimper and you know it. Do you want her to suffer?
Amin: Of course not. What if she can travel in the cabin with us?
Eva: She’s too big.
Amin: We could change our travel plans, drive instead of fly.
Eva: We’re not changing our travel plans. She’ll be fine at the kennel.
Amin: She’ll have separation anxiety.
Eva: Are you talking about the dog or about you?
[end of dialogue]
Amin begins our dialogue by saying to Eva, “I can’t stand to be away from Fifi for two weeks. Can’t we bring her along?” The expression “I can’t stand” means “I am not able to deal with” or “I’m not able to tolerate.” We can use this expression in a lot of different ways. If someone is making a lot of noise next to us, you might say, “I can’t stand the noise you’re making.” That means it really bothers me. It makes me upset. It makes me perhaps angry.
In the dialogue, Amin is saying that he isn’t going to like to leave Fifi for two weeks. “Fifi,” we learn, is the name of his dog. “Can’t we bring her along?” he asks. “To bring someone along” (along) means to bring someone with you, to take someone with you on a trip.
Eva says, “We’ve talked about this before. Our dog does not like to travel. We’ll board her,” she says. “To board” (board) means to pay someone to take care of your animal, usually a dog, for a certain amount of time. If you own a dog and you are going to be traveling, you can take it to a place that will take care of it while you are gone. The verb we would use there would be “to board” the dog. These places are usually called “kennels” (kennels).
Amin says, “What if we get a really big crate or carrier that Fifi will feel comfortable in?” Amin is trying to think of a way to take the dog with them, so he suggests getting a big “crate” (crate). A crate is a large wooden box. A “carrier” (carrier) is any sort of box that can be lifted up using what we would call “handles” (handles). Handles are basically straps – pieces of material that are connected to the box that you can use to put your hands around in order to lift the box up.
Eva says, “It won’t make a difference if she’s left out on a hot tarmac and has to spend hours in cargo hold.” We’re talking now about an airplane. When you travel on an airplane, the airplane in the airport is parked on or sits on what’s called a “tarmac” (tarmac). A tarmac is a large area at the airport that the airplanes drive on or go across on before they go up in the air. A “cargo (cargo) hold (hold)” is a large area on the bottom of an airplane, although it could be in a ship as well, that is used to keep or store suitcases, boxes, and other large objects.
Eva is saying it won’t be very practical to try to do what Amin is suggesting, but Amin isn’t giving up. He says, “It’ll be well ventilated and the crate will be large enough for her to turn around in.” “Ventilated” (ventilated) means having a lot of air going through a certain space or a room. If you are inside a room, you want the room to be “well ventilated” – air moving in and out of it so that you’re not breathing in the same air. The opposite of “ventilated” would be “stuffy” (stuffy). Amin says that this crate he’s thinking of will be well ventilated and will be large enough for the dog “to turn around in.”
“To turn around” is a two-word phrasal verb meaning to move 180 degrees in the opposite direction. So, if you are looking north, you will turn your body so that you are looking south. The verb we would use here actually would be “facing south” and “facing north.” “To face” (face) means to turn your body in a certain direction so that the front of your body, your face, is pointed in a certain direction. Interestingly enough, the verb “to face” can also mean “to deal with.” We have “to face our problems.” We have to deal with or take care of our problems.
Eva says the dog will still “bark and whimper.” “To bark” (bark) is the verb we use to describe the way a dog makes sound. There’s also a noun which is “bark.” A dog “barks” – woof, woof. The sound made by a cat is described by using the verb “to meow” (meow) – meow, meow. That, at least in English, is the sound a cat makes. Cats make different sounds in different languages. It’s very strange, but then again, so are cats, which is why you should never own one.
Eva is saying that even in this crate, the dog is still going to bark and “whimper” (whimper). “To whimper” is to make a soft sound that usually indicates you are sad or scared or perhaps in pain. Eva then asks Amin, “Do you want her,” meaning the dog, “to suffer?” “To suffer” (suffer) means to experience some sort of pain or to be in a difficult situation or undergoing a difficult experience. Amin says, “Of course not.” He doesn’t want her to suffer.
Then he says, “What if she can travel in the cabin with us?” The “cabin” (cabin) is the part of an airplane in which the human beings are located. It’s where you sit in an airplane. The cabin is usually on the top part of the airplane and the cargo hold is on the bottom part of the airplane. Eva says, however, that the dog is too big to travel in the cabin with them. Amin says, “We could change our travel plans, drive instead of fly.” Eva says, “We’re not changing our travel plans. She’ll be fine at the kennel.”
Amin says, “She’ll have separation anxiety.” “Separation” (separation) comes from the verb “to separate,” which means to take two things and pull them apart or put them apart so that they are not next to each other. “Anxiety” is a feeling of sadness or fear or perhaps just worry about something. “Separation anxiety,” then, is the feeling of sadness or fear that you feel when you are separated from another person.
In this case, Amin thinks the dog will have separation anxiety being away from her owners. Eva then asks, “Are you talking about the dog or about you?” meaning of course that it is Amin who will feel the separation anxiety because he won’t be near his dog.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Amin: I can’t stand to be away from Fifi for two weeks. Can’t we bring her along?
Eva: We’ve talked about this before. Our dog does not like to travel. We’ll board her.
Amin: What if we get a really big crate or carrier that Fifi will feel comfortable in?
Eva: It won’t make a difference if she’s left out on a hot tarmac and has to spend hours in cargo hold.
Amin: It’ll be well ventilated and the crate will be large enough for her to turn around in.
Eva: She’ll still bark and whimper and you know it. Do you want her to suffer?
Amin: Of course not. What if she can travel in the cabin with us?
Eva: She’s too big.
Amin: We could change our travel plans, drive instead of fly.
Eva: We’re not changing our travel plans. She’ll be fine at the kennel.
Amin: She’ll have separation anxiety.
Eva: Are you talking about the dog or about you?
[end of dialogue]
If you can’t stand bad English lessons, you should listen to our English lessons. They will never disappoint you. That’s because our scripts are written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to not be able to stand – to not be able to tolerate; to not be able to deal with or endure
Dawn can’t stand a dirty kitchen. As soon as she’s done cooking, she washes and cleans up all of the pans, cooking utensils, and worktops.
to board – to pay for an animal, usually a dog, to be kept, fed, and cared for by a small business (a kennel) while one is traveling
None of the neighbors are available to watch Fido while we’re in Hawaii, so I guess we’ll have to board her at a kennel.
crate – a wooden box; a box made from many pieces of wood with small spaces between them
The new employee spent most of the day unpacking crates of apples and oranges.
carrier – a box that is lifted by one or more handles, used to transport live animals, typically dogs and cats
Does your dog willingly go into the carrier, or do you have to force her into it?
tarmac – a runway; the large, paved area at an airport, used for airplanes and support vehicles to drive on
All employees on the tarmac should be wearing devices to protect their hearing – no exceptions!
cargo hold – the large, open area in an airplane or ship, used to store suitcases, boxes, and other large objects
Airline employees are still emptying the cargo hold. That must be why we haven’t seen our suitcases yet.
ventilated – with plenty of fresh air circulating through a space or room; not stuffy
Factory workers are demanding better-ventilated workspaces, especially where they’re working with hazardous chemicals.
to turn around – to move so one is facing the opposite direction
I have a surprise for you. Don’t turn around until I tell you to.
to bark – for a dog to make a loud sound, almost like a cough or shout
The dog barks whenever anyone comes to the front door.
to whimper – to make a soft, high-pitched, whiny sound, especially when one is very sad, scared, or in pain
The child’s whimpering was more alarming than her cries, because we knew she was really in pain.
to suffer – to experience physical or emotional pain or discomfort; to have a difficult, uncomfortable experience
How long have you been suffering from arthritis?
cabin – the large part of an airplane with many seats, where people sit while traveling
Flight attendants are walking through the cabin, asking people to put on their seat belts and put their seats in an upright position.
kennel – a place of business where dogs receive care and food while their owners are traveling
This kennel promises to give our dog at least two hours of outdoor exercise each day.
separation anxiety – intense feelings of worry, sadness, and fear while one is temporarily separated (apart) from someone or something
Very young babies will be happy in almost anyone’s arms, but once separation anxiety begins, they cry when they are with anyone other than their mother or father.
Comprehension Questions
1. When would the dog be loudest?
a) When she barks
b) When she whimpers
c) When she suffers
2. Where could they board the dog?
a) On a tarmac
b) In a cargo hold
c) At a kennel
Answers at bottom.
What Else Does It Mean?
board
The verb “to board,” in this podcast, means to pay for an animal, usually a dog, to be kept, fed, and cared for by a small business (a kennel) while one is traveling: “Do you have recommendations for places where we can board our dog while we’re in Nashville next month?” The phrase “to board (something) up” means to use pieces of wood to cover a window, door, or an open hole: “They’re hurrying to board up the windows before the hurricane hits land.” A “diving board” is the platform above a swimming pool that one jumps from to land in the water: “He jumped off the diving board in a graceful swan dive.” Finally, the phrase “to go back to the drawing board” means to start again with an entirely new idea or plan: “Our proposal was rejected, so we have to go back to the drawing board.”
cabin
In this podcast, the word “cabin” means the large part of an airplane with many seats, where people sit while traveling: “In a few minutes, our flight attendants will walk through the cabin offering drinks and snacks.” The “cabin crew” is the group of airline employees who take care of passengers during a flight: “The cabin crew passed out blankets and pillows.” A “cabin” or a “log cabin” is also a simple home in the woods, often used for vacation: “They like to spend their weekends in a cabin by the lake, fishing and relaxing in nature.” Finally, the phrase “cabin fever” describes feelings of restlessness after one has been indoors for a long period of time: “I hope this snowstorm stops soon, because we’re all experiencing cabin fever.”
Culture Note
Traveling with Pets
Travelers who cannot “leave their pets at home” (travel without their pets) must
“comply with” (follow the rules of) many restrictions if they want to travel with their “furry friends” (pets). Some of these regulations “stem from” (are caused by; result from) health and safety concerns, and others relate to the comfort of other passengers.
The U.S. “Department of Agriculture” (USDA; a government agency) regulates the transportation of pets “by air” (while flying). The agency requires that the pet be placed in an “adequate” (sufficient; good enough) carrier with “handles” (pieces for one’s hands to hold onto) so that it can be lifted easily, enough “room” (space) for the pet to stand, sit, and turn around, and “leak-proof” (not allowing liquids to pass through) floor. The owners must place a food bowl and a water bowl inside the carrier and provide “feeding instructions” (information about what food should be provided, and when) to the airline. USDA also requires that the traveler feed the pet within four hours “prior to” (before) the flight.
The pet must be in good health with a health “certificate” (an official document stating that something is true) from a “veterinarian” (a doctor who takes care of animals). If the travelers I going to a very hot or very cold “destination” (the place where one is going), the veterinarian must “state” (say) that the pet is
“acclimated” (can handle or adjust to the weather). The pet will not be allowed to
travel if it “appears” (seems to be) ill, “violent” (trying to hurt others), or “distressed” (very nervous; extremely worried or uncomfortable).
Comprehension Answers
1 - a
2 - c