= 1494
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 189.
This is English as a Second Language Podcast’s English Café episode 189. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to continue our series on famous Americans, focusing on Helen Keller, who was a very well known deaf and blind person, or a person who couldn’t see or hear. We’re also going to talk about horseracing and something called the Triple Crown, a famous group of three horse races in the United States. These races are very popular and are shown on television every year, we’ll talk a little bit about them. And as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café with a continuation of our series on famous Americans. Today we are going to talk about Helen Keller. Keller was born in the state of Alabama in 1880. When she was just 19 months old, not yet two years old, she got very sick. She “survived,” she continued to live, but the illness left her “deaf” (deaf), or unable to hear anything, and “blind,” or unable to see anything.
Naturally, it was very difficult or almost impossible for Helen to communicate with other people. When she was seven years old, her parents arranged for a special teacher by the name of Anne Sullivan to come help her learn to communicate with the rest of the world – with the outside world, with other people.
When Anne Sullivan came into the Kellers’ home, she immediately began using sign language with Helen. Sign language is the language that deaf people use, often, to communicate with each other. They move their hands and fingers in the air instead of speaking, and each movement of the hand or arms represents a word or an idea.
Obviously Helen couldn’t see other people’s sign language, so Anne used the letters from sign language to spell words into Helen’s hands. For example, when she gave Helen a doll to hold (a little toy that especially young girls like to play with that is like a little human – it looks like a little human), when she would put a doll in her hand she then would spell out the word, D-O-L-L, by moving her fingers as they rested on Helen’s palm. Your “palm,” is the inside part of your hand, the part that people see when you spread out your fingers so that your hand is flat.
Anne must have been a very patient teacher, because it took about a year before Helen understood that the movements Anne was making in the palm of her hand represented words and ideas. Once Helen understood that concept, she became very “eager,” or interested as a student of Anne’s. Helen made Anne teach her signs for many other objects until Anne was almost “exhausted,” or extremely tired. Just imagine how exciting it must have been for Helen Keller to finally be able to communicate with the rest of the world!
Later, Anne Sullivan taught Helen to speak by helping Helen put her fingers over other people’s throats and lips as they spoke. Helen paid attention to the movements that she felt, then put her fingers on her own throat and lips, making different sounds until she felt something similar and knew that she was speaking correctly. Rather an amazing process, if you think about it.
Once she had learned to speak, Helen learned to read something called Braille. Braille is a way for blind people to read. It’s made by printing small, raised dots, little points on the paper or on the surface that you can feel as you move your fingers across the paper, and by feeling where the dots are you know what letters and words are there. Helen, however, was no ordinary student – no ordinary girl. Not only did she learn to read Braille in English, she also learned to read Braille in Latin, Greek, German, and French!
Helen was a very determined student, someone who wanted to learn as much as possible, and she was very committed to education. When she was 24 years old, she became the first deaf and blind person to earn (or to receive) a university degree. She earned her degree magna cum laude. The phrase cum laude is Latin, it means with honor. When someone graduates with the best grades from a university, we say that he or she graduated summa cum laude, with highest honors. You could also say cum summa laude, but that’s not ever done. Cum is with, laude is honor, summa is highest. The highest degree you can receive from a university would be summa cum laude. The next highest is magna cum laude, which means with great honor, and after that comes cum laude. So when someone says they graduated from an American university with honors, that means that their degree says either cum laude, magna cum laude, or summa cum laude. Every university has a different system for determining who gets to graduate with honors. So not only did Helen receive a university degree, something that was quite unusual, first of all, for a woman in the early 20th century, not to mention in addition to being a blind and deaf woman. She graduated with great honor, with the second-highest possible honors from her university.
Anne Sullivan continued to be Helen Keller’s teacher; later, she became her friend – her “companion,” someone who spends a lot of time with another person, until Anne died in 1936. During and after this time, Helen became very famous, not only for her “accomplishments,” or the amazing things she had been able to do as a deaf and blind person, but also because she became a very well known author and speaker.
Helen was also very politically active, or involved in politics, at a time when it was unusual for women and people with what we now call disabilities to “voice,” or to share their opinions in public. A “disability” is something that you are not able to do, such as to see or to hear or to walk or other types of difficulties that you might have that other people do not. Helen, as I say, was politically active. She was an advocate, in fact, for people with disabilities. An “advocate” is a person who fights for something important that he or she thinks needs to be changed in society. Some people are advocates for the environment; some people are advocates for people with certain diseases, such as AIDS or Parkinson’s. Helen was an advocate not only for people with disabilities, like herself, she was also an advocate for other more controversial issues. She advocated for a woman’s right to vote, as well as more radical political ideas.
In 1915, Helen helped create an organization called Helen Keller International. Helen wasn’t particularly modest, I guess! The organization is still active today; it conducts research in vision and health and nutrition in the United States and in several other countries. Much later in life, Helen received the Presidential Medal of Freedom, which is a very high honor in the United States. She died in 1968. Most Americans learn about her life when they are in elementary school; it’s very common to read stories about Helen Keller when you are a young student in the U.S. Almost all Americans recognize her name and are at least somewhat familiar with her story. There was also a famous movie made, The Helen Keller Story. That, then, is our story of Helen Keller.
Now let’s jump (or move) to our next topic, which is the Triple Crown – the Triple Crown of Thoroughbred Horse Racing. Usually, it is called simply the Triple Crown. A “thoroughbred” is a horse that is a pure “breed,” or type. A thoroughbred’s parents are the same kind of horse. In other words, a thoroughbred is not a mix of different kinds of horses.
Horse racing, or thoroughbred racing, is a popular sport for some Americans to watch. There are three main races for the Triple Crown, “triple,” of course, meaning three. These are races for three-year-old thoroughbreds. These races take place in different parts of the United States. There’s the Kentucky Derby, the Preakness Stakes, and the Belmont Stakes. “Stakes,” here, is just another word for race, as is “derby.” When a thoroughbred wins all three of these races in a single year, we say that the horse has “taken the Triple Crown.” A horse that has taken the Triple Crown is recognized as one of the greatest or best thoroughbred horses in the United States, and perhaps even the world.
Winning all three races, however, is very difficult and “rare,” or unusual. The three races have been going on for more than 100 years, but the Triple Crown has only been taken only 11 times, so about 10 percent of the time. The last time someone won a Triple Crown was in 1978, more than 30 years ago. No horse has been able to win all three races since then. When I was growing up, there was a very famous Triple Crown winner in the early 1970s by the name of Secretariat, and everybody in the country knew about Secretariat and the winning of the Triple Crown by that horse. Of course, there is a man on top of the horse, a man we call the “jockey” (jockey), and you need to have a good jockey in order to be a successful thoroughbred horse.
The Triple Crown begins with the Kentucky Derby in early May. As I mentioned earlier, a “derby” (derby) is a kind of competition or race. We often use that word to talk about a horse race. The Kentucky Derby is a mile and one quarter (11/4) long, or just over 2 kilometers. The Kentucky Derby takes place in – you guessed it correctly – the State of Kentucky, which is in the central eastern part of the United States.
The second race is called the Preakness Stakes. That is held in Maryland two weeks later. That is the shortest of the three races, at just 13/16 miles, or 1.91 kilometers for the rest of the world.
The third and final or last race is the Belmont Stakes, which takes place about three weeks later, in early June. The Belmont Stakes is held in the State of New York. It is the longest race at a mile and a half (11/2), or about 2.41 kilometers.
I should mention that Maryland is a state located on the eastern coast, in the central coast of the United States right next to Washington, D.C., our national capital.
The race, nowadays, is sponsored by large companies. VISA, the credit card company, used to sponsor the races. To “sponsor” a race means to give money to help organize the race. VISA stopped sponsoring the Triple Crown in 2005, but it still offers a special bonus or reward if a horse should win the Triple Crown. That reward is about five million dollars, so a pretty good amount of money!
Even people who don’t normally like to watch horse racing will watch the Kentucky Derby, the Preakness, and the Belmont Stakes simply because this series of three races is so famous. And if there is a horse that can win all three races, that horse becomes quite famous also.
Now let’s answer a few of your questions.
Our first question is from Peter, originally from Iran, now living in Canada. Peter wants to know the meaning of the expression “opposable thumb.” An opposable thumb, in humans and other primate animals, is the ability of the thumb to be placed against the other fingers of the hand. It allows the hand to grab, or grasp, small objects, to hold them in your hand. “Opposable,” here, means on the other side of, so the thumb can be placed on the other side of the fingers so that you can use the fingers and the thumb together to grasp or grab something.
The phrase “opposable thumb” distinguishes (makes different) the idea of the human thumb from other animals who don’t have this ability. A cat, for example, has five digits or fingers on its feet, what we call its paws. But none of the cat’s fingers or digits are opposable; that is, a cat can’t take one finger against another in order to grab something, like a pencil.
Sometimes people talk about the opposable thumb as if it is something that only human beings had. In fact, there are other animals such as apes that have opposable digits; they have something that is like our opposable thumb. To say that someone doesn’t have opposable thumbs might be a form of an insult to someone. If someone said, “Well, this isn’t something you can do. It’s only for those with opposable thumbs,” they’re saying that you’re not a human, that you are some sort of lower animal, that you are not very intelligent. Perhaps you are an American football player, I don’t know!
Yuki (Yuki) from Japan wants to know the difference the expressions “due to” and “because of.”
“Due (due) to (to)” can mean by the reason of, or as a result of. “Because of” can mean the same thing: “Due to the heavy rain, school was canceled today.” “Because of the heavy rain, school was canceled today.” “She is very healthy due to her exercise program.” “She is very healthy because of her exercise program.” There, the two expressions mean the same thing. Both “due to” and “because of” are followed by a noun or a noun phrase; they are not followed by a complete sentence.
“Due to” is a little more formal; it might be something that you hear on the news on television or in a business letter. “Because of” is probably a little more conversational, a little more informal.
“Because” can be used to introduce a complete sentence if you don’t use the word “of.” So, “because of” is followed by a noun or a noun phrase: “Because of the rain, school was canceled.” “The rain” is the noun. But if you don’t use “of,” then “because” can introduce a complete sentence: “There is no school today because it is raining.” “It is raining” is a complete clause, and you can use “because” in front of it because there is no “of” there. “Due,” however, cannot be used in the same way. You can’t say, “School is cancelled today due the rain is heavy.” That doesn’t make any sense, so it can’t be used the same as “because.” But it it’s “due to” and “because of,” then you use them in the same way.
Finally, Fatemeh (Fatemeh) in Iran wants to know the meaning of the letters “Mc” in front of a name. For example, one of the famous Beatles is Paul McCartney (McCartney). There’s also a man who lives here in California, Fatemeh says, named Jeff McQuillan. I believe he is the host of ESL Podcast!
The letters “Mc” (we often or usually pronounce it “Mic,” though there’s no “i” in there) is a prefix, it’s something that goes before a last name, and it means simply “son of.” Many names that come from Ireland, where my relatives were from, and Scotland, which is in the northern part of the island where England is located; it is north of England – many of these names have their origins in the Gaelic languages. The Gaelic language is something that was part of different parts in Europe, including Scotland and Ireland. Names like McCartney and McQuillan are what we would call anglicized pronunciations – anglicized versions; that is, they’ve been converted, if you will, from Gaelic to English.
A variation on “Mc” (or “Mc”) is “Mac”; this is a little more common in Scottish names, in names that come from Scotland.
If you have a question or comment you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
deaf – unable to hear anything; not having the ability to hear
* Was Daniel born deaf or did he become deaf later in life?
blind – unable to see anything; not having the ability to see
* If the eye disease Su has is not treated properly, she could go blind.
sign language – the language that deaf people use to communicate with each other by moving their hands and fingers in the air, with each movement representing a word or idea
* In college, I studied sign language so that I could work in the deaf community.
palm – the inside part of your hand; the part that people see when you spread out your fingers so that your hand is flat
* Show me your palm and I will tell you your future.
Braille – a type of printing made to be read by blind people; a type of printing that uses small, raised dots on a piece of paper so that blind people can gently move their fingers over the paper and, by feeling where the dots are, know what letters and words are there
* All of Omar’s books are published in Braille so that they can be read by the blind.
magna cum laude – the second highest academic honor given to students who graduate a university with very good grades
* Gina’s parents were very proud that she graduated magna cum laude.
companion – someone who spent a lot of time with another person; someone who spends time with another person so that that person does not become lonely
* In the last years of her life, her husband was her constant companion and they never left each other’s side.
advocate – a person who fights for something important that he or she thinks needs to be changed in society
* Chung is an advocate for children’s rights and plans to go to Washington to meet with lawmakers.
thoroughbred – a horse that is a pure breed (type); a horse that only has the blood and background of one type of horse
* My horse may not be a thoroughbred, but it can run faster than any horse in the race.
rare – unusual; not common; unique
* Have you ever seen a green rose? I think it must be very rare.
derby – a kind of competition or race; a horse race
* Let’s go to the derby this afternoon and watch your favorite win the race!
to sponsor – to give money to support an event or organization; to give money so that an event can take place
* Without our corporate sponsors, we would not be able to run our programs for children.
opposable thumb – in people, the ability of the thumb to be placed against the other fingers of the hand, giving the ability to hold small objects in one’s hand
* If we didn’t have opposable thumbs, we wouldn’t be able to do simple things, like hold a toothbrush to brush our teeth.
due to – by the reason of; as a result of
* This meeting is starting a little late due to a problem with the microphones.
because of – by reason of; as a result of
* Because of the large number of people who want to attend the concert, we’ve moved it to a larger place.
Mc – a prefix for a last name, meaning “son of”
* You last name is McNally. Are your relatives originally from Ireland?
What Insiders Know
Mister Ed
People aren’t the only ones who “make it big” (become famous) on TV and in movies. Some of the biggest television and movie stars have been animals!
One of the most famous horses that have been on TV is the character of Mister Ed. Mister Ed was the title of a “sitcom,” a situation comedy that had half-hour episodes, and was shown on television from 1961 to 1966.
Mister Ed was a very intelligent horse that could talk. His owner was an “architect” (a person who designs buildings) named Wilbur. Mister Ed talked to Wilbur often. However, there was one big problem. Only Wilbur could hear Mister Ed talk; no one else could. You can imagine all of the problems Wilbur had with a horse that only talked to him!
There were many stories about how the “trainer” (a person who works with animals, teaching them to do special things) got the horse to talk. One story was that the trainer put “peanut butter” (a type of spread made from peanuts) on the horse’s “gums” (the soft, pink part of the mouth that teeth are attached to), and while the horse tried to remove it, it looked like he was talking.
However, many years later, the trainer explained that he himself had started that story and it wasn’t true. In fact, the way he got the horse to “talk” was to put a piece of “nylon” (flexible plastic) under the horse’s lip. When the trainer gave the “cue” (a signal to a performer to do something), the horse would try to get it off his lip. This made it look like he was talking. The horse was so well trained, he would “ignore” (not pay attention to) the piece of nylon until the trainer gave the cue.