= 1479
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 174.
This is English as a Second Language Podcast’s English Café episode 174. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English.
On this Café, we’re going to talk about a very well known American hymn – well known, that is, to Americans. A “hymn” is a type of religious song, and this song is called Amazing Grace. We'll also talk about specialty cable and satellite channels and the types of television programs that you can see on them here in the United States. And as always, we’ll answer a few of your questions. Let’s get started.
For those of you who watched the video podcast for ESL Podcast's third anniversary, you will remember that I promised to keep singing in the future. Well, today is your lucky day. Or unlucky, depending on what you think of my singing voice! Today we're going to talk about a very well known, or popular “hymn,” or religious song. Normally hymns are sung by Christians in a church, but sometimes they become so popular and well known that they are heard outside of church as well. Today's song, Amazing Grace, is one of those types of popular hymns.
First let's look at the name of the song. Something that is “amazing,” is something that is very impressive or perhaps surprising in a good way. It makes you stop and think about something and admire it very much. For Lucy and me, the growth and popularity of ESL Podcast is amazing, because we are much more popular than we thought we would ever be. The word “grace” is usually similar to elegance. We use the word grace to describe someone who can move their body smoothly and elegantly, without falling down or bumping into things. Dancers, especially ballerinas (people who dance in a ballet), are considered to be very graceful; they have a lot of grace. However, in the song Amazing Grace the word means something different. Grace is describing the willingness of God to help people no matter what they have done. Grace, in this case, can mean mercy, or willingness to forgive people for their “sins,” the bad things that they did that are against God's laws. Christians talk about the amazing grace of God, because they are amazed or impressed by their God's willingness to help them and forgive them no matter what they do.
The words for the song were written by an Englishman named John Newton (Newton). He wrote the words in 1772, or thereabouts (approximately that date). John Newton was a slave trader; he worked bringing slaves from Africa back to the U.S. and to other countries in the so-called “New World,” North and South America. He was working as a slave trader for many years, and slowly he became convinced that what he was doing was wrong. He believed that God was giving him this amazing grace to change his life.
The words for the song are based on some things in the Bible. The song itself – the music for the song was not written by John Newton; it was adapted to a popular spiritual hymn.
Amazing Grace has six verses. A “verse” (verse) is the part of the song that is repeated, with different words or “lyrics.” Most people, including myself, only know the words to the first verse – the first section of Amazing Grace. If you want to know the words for the other verses, you can search online to find them easily enough. I'm going to sing the first verse for you now. Don't worry if you don't understand the words. Once I finish singing, I'll go back and explain the meanings of the words. It’s hard to sing this song well – especially for me! It’s such a beautiful song; I hope you have a chance to hear a real singer sing it someday, but we will give it a try.
“Amazing grace, how sweet the sound
That sav’d a wretch like me!
I once was lost, but now am found,
Was blind, but now I see.”
The song starts by saying, “Amazing grace, how sweet the sound that sav'd a wretch like me!” The word “sweet,” here, is normally used to describe the taste of certain foods that have sugar: fruits or other types of food. But the word “sweet” can also be used, as it is here, to talk about something that is enjoyable or pleasant. In this context, we are talking about the sweetness or the wonderfulness of God's amazing grace.
In the song, amazing grace “sav'd a wretch like me.” In the religious, Christian context, to “save” someone means to help someone find and accept God so that he or she begins to believe in Jesus Christ, the founder of the Christian religion, and decides to live according to what the Bible has taught. If someone says, “Have you been saved?” they want to know whether you have become a Christian, if you have accepted the Christian God into your life. A “wretch” (wretch) is a person who has done something wrong or perhaps is very unhappy and unloved. A wretch isn't someone you want to spend a lot of time around, but in this song God, in his amazing grace, saves the wretch anyway. God forgives the person for his or her sins, and the person is very thankful – very grateful for that. So, “Amazing grace, how sweet the sound that sav’d a wretch like me!” Not quite sure why it’s “the sound that sav’d a wretch like me,” perhaps the sound of God.
The song goes on to say, “I once was lost, but now am found.” We usually talk about things that are lost and found, rather than people. For example, if you leave your keys at a store by mistake, they are lost. When someone else finds them and gives them back to you, they are found. In this case, though, a person is lost, meaning he doesn't know God, he’s not a Christian, and hence he is lost. Then something happens and that person becomes a Christian, and that’s why we say that he is now found, meaning he now has a religious belief in God. You can be lost, of course, if you don’t know where you’re going, and that is also part of the meaning here.
The last line of this song is “Was blind but now I see,” meaning I was blind but now I see. A person who is “blind” cannot see. This song isn't really about someone who couldn't see, but about a person who couldn't see or understand the truth – the truth of religion, in this case. But now, thanks to the amazing grace of God, he can see the truth, which in this song means living as a Christian, having a relationship with the Christian God.
Let's listen to the verse one more time:
“Amazing grace, how sweet the sound
That sav’d a wretch like me!
I once was lost, but now am found,
Was blind, but now I see.”
It’s a very powerful and “moving” song – emotional song, especially if you have heard it sung in a church by a professional singer or choir. It is a song that is often sung in churches in the United States, and is probably familiar to most Americans. I hope you enjoyed it and have a chance to hear a good version soon.
Our second topic today is quite different; we’re going to talk about some television programs that you might see on the cable television networks or cable television systems in the United States. There are many different television channels here in the U.S. A “channel” is the number that you turn to on your television to watch a certain program. The channel is usually owned by a single company or station, and they have shows usually 24 hours a day. There are many basic television channels in the U.S; we sometimes talk about “basic cable.” What we mean is that when you sign up for cable or satellite television, so that you have either some sort of wire running into your house or you have a satellite dish on the top of your house to receive the television signals from the sky, you are given certain channels as part of your basic package, the lowest priced package. These channels will be found on all of the televisions that subscribe to the basic package. A cable channel is, as I mentioned, something that is delivered to your home through a wire; satellite is from outer space, from a satellite above the planet.
You have these basic channels – this basic cable, but you also have, on most cable television systems and satellite television systems what are called “specialty” channels. These are channels that have very specific programs for special interests, people who have interest in things that are perhaps not popular with everyone. For example, there is a popular channel called Animal Planet; all of its shows are, you guessed it, about animals. There is also a golf channel that has nothing but golf games and other information related to the sport of golf. That’s a good one to watch when you can’t sleep at night and you want to fall asleep! The Cartoon Network is full of animated drawings – “cartoons.” These are for children mostly, but some of them are for adults as well – or adults who still think like children! The History Channel has special programs about American and world history. That’s also popular with certain people. Another popular cable channel is called HGTV, which means, or stands for Home and Garden TV. It has programs about buying and selling houses, taking care of your house, and improving them. These are just a few of the specialty channels that are available. There are specialty cable and satellite channels for almost everyone and almost every specific interest. There are travel channels, there are religious channels, there are channels for people who are interested in sports, and so forth.
In the U.S. you usually have to pay extra, meaning you have to pay more money to get these specialty channels. You also have to pay more money if you want movie channels, which show nothing but movies. Many cable and satellite companies offer these “packages.” It offers customers a group of channels they can buy for one price every month. The company selects the channels that it offers, and then you can pay for an additional set of channels. Usually, there are very basic ones that probably cost anywhere between, oh, 25 and 35-40 dollars a month. If you want the additional channels, you can pay up to 70-80 dollars a month, even more if you want movie channels, which are more expensive.
If you live in the U.S. and you have a television, you might want to try to look at some of these specialty cable and satellite channels that are available. Of course, many countries have these specialty channels. On my satellite television system, I think we have more than 500 channels, which is about 499 more than what I need!
Now let’s answer a few of your questions.
Our first question comes from Bogdan (Bogdan) in Ukraine. Bogdan wants to know the meanings of the words “slay,” “kill,” “murder,” and “slaughter.” A happy question! These words can all mean to kill someone, to end someone’s life, but they each have a slightly different use or meaning.
“Slay” usually means to kill or destroy violently a large number of people. It’s an older word that you don’t hear as much other than in, for example, stories, especially imaginary stories, when you have someone killing monsters and dragons and other mythical or made up creatures: “The prince in the movie Sleeping Beauty slays the dragon” (kills the dragon). “Slay” can also occur as a noun, a “slayer” is someone who slays. There was a popular television program a few years ago called Buffy, the Vampire Slayer. A “vampire” is, again, an imaginary creature that sucks your blood and kills you – I think it’s imaginary!
The verb “to kill” is the most common word for ending someone’s life, to cause the death of someone else. You can kill anything, however. You could kill an animal; you could kill even someone’s plan to do something. It means to end something suddenly, including to end life. Someone who kills is called a “killer.”
“To murder” means to kill someone on purpose. You could kill someone accidentally, but you cannot murder someone accidentally. If you mean to kill them – if you want to kill them, then we would call that “murder,” you murdered that person. Murder can also be a noun, the act of murdering someone. And a person who murders is called a “murderer,” with an “er” at the end.
Finally, “to slaughter” (slaughter) means to kill something in a brutal or violent way. You can slaughter people, usually many people. Slaughter is also, however, more commonly used to refer to killing animals such as cows. In fact, the place where you kill a cow is called a slaughterhouse. There was a famous novel in the 20th century called Slaughterhouse Five by the writer Kurt Vonnegut. Slaughter is not a common word for humans, however – that is, for the killing of humans. You might refer to some act of war, for example: “The soldiers slaughtered every one in the village (or the town).”
Our next question comes from Essai (Essai), and I don’t know where Essai is from. I don’t even know if I’m pronouncing his or her name correctly, my apologies. The question has to do with an advertising slogan that this person saw, an expression, which is “I’m loving it!”
Well, let’s start with the expression “I love it.” When someone says, “I love it,” they mean they like it very much, they care for it or enjoy it very much. “I’m loving it” means I’m enjoying it; the emphasis is on the present situation – what’s going on right now. I like the current situation as it’s happening right now. “Isn’t this a great television show that we are watching? I’m loving it!” Or, “I have a new book; it’s very interesting. I’m loving it!” It means same as “I love it,” it’s just a little more active, perhaps a little stronger for more emphasis. The fast food restaurant McDonald’s uses this expression: “I’m loving it!”
Finally, Chiayasit (Chiayasit) from Thailand wants to know the uses of the words “dollar” and “buck” (buck).
These words mean the exact same thing. A “dollar” is a U.S. amount, at least what we call our money here in the U.S., there are other countries that use the word dollar. A dollar in the United States is worth 100 cents. “Buck” is simply an informal word or term for dollar. Someone says, “How much is that shoe?” – they just want to buy one for some reason! – and you say, “10 bucks.” That’s 10 dollars; it means the same thing.
We usually use the word “bucks” for smaller amounts of money, but not always. You could say, “He spent 50,000 bucks on a new car.” He’s, of course, someone with a lot of money!
So “buck” and “dollar” are identical, “buck” is just an informal way that we refer to a dollar.
I love it when we get questions and comments about our podcast. You can email those to eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. Copyright 2009, by the Center for Educational Development.
Glossary
amazing – very impressive; very surprising in a good way
* The concert last night was amazing and the best concert I’ve seen in years!
grace – elegance; ability to move smoothly and elegantly, without falling down or bumping into things
* The film actress danced across the screen with grace.
sin – bad thing that one does that is against God's laws; something one does that is morally bad
* Is it true that most cultures believe that killing another person is a sin?
verse – the part of a song that is repeated many times, but with different lyrics (words) each time
* We remember the words for the first verse of the song, but we don’t remember the words to the second verse.
wretch – a person who has done something wrong; a person who is very unhappy and unloved
* After lying to his parents, Jim felt like a wretch.
channel – one number that you turn to with your television set to watch a certain set of programs provided by a television station or company
* Which channel will my favorite show be on tonight?
cable – television channels delivered to a home or business through long cables or wires that are either underground or up in the air
* Sean got cable at his apartment and invited all of us over to go over to watch the game tonight.
satellite – television channel sent to a home from outer space (above the planet) and is received by a large round dish that collects the signals and shows the images on one’s television set
* After the storm, our satellite TV wasn’t working and we had to call someone to repair it.
specialty – something, such as a product, that is special or unique; something that someone is very good at doing
* Steak is the specialty at this restaurant.
cartoon – animated (moving) drawings that are used to create a show; a movie or show made from moving drawings
* When I was young, I would wake up early every Saturday morning to watch cartoons on TV.
package – a group of products that a company puts together and sells at one price, often for a lower price than if one were to buy each product separately
* I bought a vacation package that included hotel, airfare, and meals.
to slay – to violently kill or destroy, usually in large numbers
* Many soldiers were slain on the battlefield.
to kill – to cause the death of someone or something; to take one’s life or someone or something, to destroy
* The violent storm killed three people and destroyed 20 homes.
to murder – to kill a person; the crime of killing someone
* Our neighbor was never arrested for murder, although we think he killed his wife.
to slaughter – to kill animals; to kill someone in a very violent way
* Although Jaime grew up on a farm, he said that he never wanted to watch when a cow was being slaughtered.
I love it – I like something very much; I care for something very much; I enjoy something very much
* I love it when the weather is sunny and warm.
I’m loving it – I’m enjoying it; I’m happy with the current situation; I really like what is happening right now
* Sitting on the beach on vacation and with my girlfriend – I’m loving it!
buck – informal term for “dollar”
* Do you have 10 bucks I can borrow? I’ll pay you back later today.
What Insiders Know
Cable Channels for Different Cultural or Language Groups
The United States is full of people of many backgrounds and cultures. “Recognizing” (realizing) this, cable television companies are “eager” (want to do very much) to include cable channels created especially for people from the major cultural groups in this country and for other people who enjoy programming for those groups.
A major cable channel “targeting” (aimed at) African Americans is Black Entertainment Television (BET). This channel was founded in 1980 and is intended for young “urban” (living in the city) African American viewers. If you watch this channel, you will see music videos and movies involving African Americans or produced for this audience.
For Asian Americans, there is a cable channel called ImaginAsian (pronounced “imagination”) that began in 2004. It had “programming” (programs; shows) for people of East Asian and South East Asian “descent” (ancestry; background). Like BET, it had music videos and movies targeted to Asian Americans. However, the channel was not successful and stopped broadcasting in 2008.
In the U.S. there are many Spanish-speaking people who have connections to South and Latin America, the Carribean, and other places where Spanish is spoken. For this reason, there are many stations that broadcast in that language. The two biggest Spanish-language channels are Univision and Telemundo. Both channels are based in the U.S. and broadcast in many cities with large Latino populations. These channels include many types of programs, including local news and “variety shows,” shows that have a host who welcome many different types of performances that involve humor, singing and dancing, and games. Also popular on these channels are “telenovelas,” which are soap operas – drama shows with stories that continue from one show to another and that are usually broadcasted every day. These telenovelas are very popular and may be produced in other countries or in the U.S.