= 1481
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 176.
This is English as a Second Language Podcast’s English Café episode 176. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, including our new Introduction to the United States course, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about an interesting organization called The Innocence Project. I’ll also share with you some information about a very popular website in the United States, and a few other countries, called Craigslist. And as always, we’ll answer a few of your questions. Let’s get started.
This Café is going to focus first on The Innocence Project. “Innocence” means not being “guilty,” or not having done anything wrong. If you have not broken the law, then you are innocent. When the police think that someone has broken a law, he or she is “arrested,” or taken to prison or jail. Some of these people really have broken the law, so they are what we would call “criminals.” But other people are arrested because of a mistake, and they are actually innocent.
Now, normally, after people are arrested, they go to “court,” or the place where a judge will listen to arguments about what happened and will decide whether the person is guilty or innocent. Usually, the judge doesn’t decide him or herself, there is a group of people called a “jury” (jury) who makes the decision. If the jury decides that a person is guilty, we say that the criminal has been “convicted” (convicted), which means that the jury and the judge make an official announcement that this person is guilty. We often call someone who has been convicted a “convict,” that would be a person who has been convicted of a crime (who is guilty of a crime). As a result, the convicted criminal (or convict) might go to jail for many years. That’s the way the U.S. legal system generally works.
But what happens if the jury and the judge make a mistake? Sometimes people who are actually innocent are convicted and sent to jail even though they have done nothing wrong. We say that these people are “wrongfully” convicted, because the decision to send them to jail was wrong or incorrect. Unfortunately, someone who is wrongfully convicted might stay in jail for years, telling people that he or she is innocent, but other people might not, and often don’t, believe it.
That brings us to the Innocence Project. The Innocence Project was created in the United States to help people in this situation. The Innocence Project was started in 1992 by a couple of lawyers. They started this group – this project to try to exonerate people who had been wrongfully convicted. To “exonerate” (exonerate) someone means to say officially that someone is not guilty after he or she has been convicted, to show that the person is innocent. So if a judge says that you did something wrong, you are convicted of the crime and go to jail. But then if more information is found and the judge decides that you are actually innocent, then you are exonerated and you are allowed to go home – to leave the jail.
The Innocence Project became famous in the United States because it uses DNA testing to investigate whether people actually committed a crime. This is especially important in what we would call capital cases. A “capital case” is a case where the person is sentenced to death, or could be sentenced to death. Obviously, we want to find out if they are innocent before they are put to death; the DNA evidence helps the Innocence Project do just that.
There have been several very famous cases in the US of the Innocence Project discovering that someone who was convicted of murder, and who had been sentenced to death – that is, someone who they were going to put to death because of their crime was found innocent. DNA is something that all living things have; it carries what we would call genetic information. It tells our body whether we will have black hair or blonde hair, blue eyes or brown eyes. Everyone’s DNA is “unique,” it is not like anyone else with the exception of what we call identical twins, two babies that are born at the same time who are identical, meaning they are the same – they look same, they have the same hair color, the same eye color. That kind of twin has the same DNA as the other twin. But everyone else’s DNA is unique; no two people have the same DNA. So DNA is a good way of determining whether you, specifically, were the person who, in this case, committed the crime.
When there is a crime, the criminal often leaves behind this biological “evidence,” or clues or things that the police can use to understand what happened and find the person who “committed,” or did the crime. Some types of biological evidence include hair or a drop of blood. When there is this biological evidence, scientists can do DNA testing to read the DNA and try to match it to a person. So if you leave a piece of hair, for example, the scientists can take the hair and look at the DNA, and then compare it to your DNA to see whether it is your piece of hair. This is what we call a “match,” when the two are the same or almost exactly the same. If the person has a DNA match, then they are probably guilty, or least they were there when the crime was committed. But if they don’t match, then it seems likely the person would be innocent.
So, the Innocence Project makes the results of these DNA testings public information, meaning anyone can see if the DNA matched based upon the evidence that the police have. If the DNA evidence shows the person is innocent, then the person can go back to the court and try to be exonerated. This, in fact, is what the Innocence Project has done many times – hundreds of times in the last 16-17 years. Many people go to the Innocence Project and try to get this DNA testing done, people who think or say that they are innocent and have been wrongfully convicted.
The Innocence Project is an interesting example of a private organization that tries to make sure that the government is doing its job correctly when it comes to criminal convictions.
Now let’s turn to our next topic, which is a very popular website here in the U.S. called Craigslist. Craigslist is actually in many different countries; it is popular in some of these, but it is very popular here in the United States. You can go to craigslist.org (craigslist.org) to find the website. You’ll see that it’s a very simple site that mostly has what we call classified ads. A “classified ad,” or a “classified advertisement,” is a few lines of text (a few sentences), that traditionally are published in a newspaper. Most people use classified ads when they want to buy or sell something, or when they are looking for other people who are interested in something.
I once used a classified ad in the newspaper to buy a car. Someone had put an ad in the paper for a used car, and I saw the ad in the paper and I responded – that is, I answered, or I called the person, and I bought the car. Unfortunately, the car stopped working about a month later, so you have to be careful when you buy a used car from the classified ads. This was more than 20 years ago and back then all of the classified ads were in the newspapers, usually in the back of the newspaper. Now, however, these classified ads are online, or on the Internet. The most popular place to find them in the U.S. is at craigslist.org.
Craigslist used to just list events in the San Francisco area, where it was started. A lot of Internet companies start in San Francisco or in an area next to San Francisco called the Silicon Valley. The website was started by a man named Craig, of course, and that’s why it’s called Craigslist. But it has grown far beyond San Francisco. Today there are Craigslist websites for many cities in the U.S. and internationally, too. You can find out by going to craigslist.org to see if there is one in your city.
All the Craigslist sites are very similar. They have a “for sale” section where people write classified ads for things they want to buy or sell. There’s also a “housing” section where people can advertise apartments that they want to rent or share, or even homes that they want to sell. There is a “jobs” section; these are classified ads from companies that are looking for new employees. So if you are looking for a new job in these difficult times, you can go to craigslist.org and look in the “help wanted” section, which is what we call the section of a newspaper or of a website where there are jobs that are advertised.
Craigslist, like newspaper classified ads, has what is called a “personals” section. Personal ads are classified ads that are written for people who are looking for a friend, or a boyfriend, girlfriend, even a husband or wife. In these ads, they usually say what kind of person they are looking for, this may include the physical appearance, the age, education, job or occupation, perhaps even how much money a person makes. Classified personal ads usually include information about the person themselves, and often a photograph – not necessarily a photograph of the person, but a nice looking photograph so that you think this person is attractive (is good looking). That’s what I do – well, I used to do; I would put in a picture of Brad Pitt or George Clooney and say that that was me. I got lots of calls!
Under the “personals” section, there is an area also called “missed connections.” Who would put an ad in the “missed connections” section? Well, let’s say that you are a young man – like me – and you see a beautiful woman in a restaurant, and you’re interested in this woman, but you don’t have the “courage,” you don’t have the, we would say, “guts,” the bravery to go up to her and ask for her phone number. When you get home that night, you keep thinking about her and you wish you had some way to contact her. Well, in that situation you might put a classified ad under the “missed connections” section of Craigslist, describing where you met the woman, what she looks like, what you look like, hoping that if she sees the ad she will contact you. Of course, the chances that that person will read the Craigslist ad and find you are very small. But it’s sort of like buying a lottery ticket; you might win, you probably won’t, but it doesn’t cost you very much. In fact, most of the Craigslist ads are free.
There’s also a “community” section of Craigslist. This has advertisements from people who have similar interests, or are looking for people who have similar interests. For example, if you are looking for someone to practice your English with, or French, or Japanese, or whatever language you are trying to learn, you can put an ad in this section saying that you are looking for conversation partners. You’ll also see classified ads for people who are looking for tennis players to play with, babysitters (people to come and take care of their children), people who want to “carpool,” that is, ride to work with someone else in their car. All of these can be found on the Craigslist “community” section.
Craigslist is really a great “resource,” or tool that can help you, especially when you move to a new city. It can help you find a place to live, get furniture for your new home or apartment. You can then use the website to find a job, and other people to spend time with when you’re not working. You can find a boyfriend or a girlfriend, a dog, a cat – I recommend a dog, much more reliable than a boyfriend or girlfriend! Well, some people swear by Craigslist. When we say they “swear by it,” we mean they think it is very, very good. To “swear by something” means to say I believe this is excellent, I believe this is wonderful. Some people who swear by Craigslist say that they found their apartment, their furniture, their job, their wife, their dog on Craigslist!
I’ve used Craigslist many times, and it is very useful for many different things. So, take a look at craigslist.org, you may find something that interests you there as well.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Mohammad (Mohammad) in Egypt. Mohammad wants to know the meaning of the word “in” in the expression, “It’s the in place” and “She’s part of the in crowd.” In is normally a preposition meaning, among other things, inside of something. But here it is used as an adjective to mean cool, popular, or trendy. For example, you may read that a certain restaurant is the “in restaurant in Los Angeles” or a dance club is the “in place to be seen.” (That’s where you will find me, of course, dancing at the in place to be!) In can be thought of as a shorted version of the expression “in fashion,” which means popular. The “in crowd” would be the group of people who are most popular and with whom people want to be seen. I was never in the “in crowd” in school (sad, I know).
Finally, Tzu-Ling (Tzu-Ling), originally from Taiwan, now living in the United States, wants to know the meaning of the expression “to be sworn in.” The verb to swear in means to take an oath, an official promise, to do something. To be sworn in (the part participle of the verb to swear is sworn) is simply the passive form of this expression. Often this expression is used when there is an official government ceremony for some elected or appointed person who is starting a new job. For example, when the president of the United States begins his first day as president, he or she is sworn by the leading judge in the United States, the Chief Justice. The Chief Justice swears in the president; the president is sworn in by the Chief Justice. If you are part of a trial where you go before a judge in a legal case, you may be sworn in, meaning you promise to tell the truth in answering the questions the lawyers or the judge asks you.
Of course, we just learned that to swear by something means to say that something is true, that you are guaranteeing that it is true.
If you have a question, you can email us. We don’t have time to answer all of your questions but we’ll do our best. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Cafe.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. Copyright 2009, by the Center for Educational
Development.
Glossary
innocence – not being guilty; not having done something wrong
* This book is about that man’s innocence, even though a judge found him guilty.
criminal – someone who has broken the law; someone who has done a crime
* What will happen to these criminals when they are released from prison?
convicted – an official announcement by a judge or court that the person is guilty of breaking the law or doing something wrong.
* People who have been convicted of a serious crime cannot work for the government.
to exonerate – to officially say that someone is not guilty after he or she has been convicted (officially found guilty of a crime)
* My brother was exonerated after another man said he had stolen the money.
DNA testing – using the very small thing in all living things that carries genetic information (deoxyribonucleic acid) to see if two things come from the same person
* The Lima family used DNA testing to show that they were related to another family with the same last name.
evidence – things that police and researchers use to understand what happened during a crime and find the person who did it
* Do you have any evidence that your sister damaged your bicycle or are you just guessing that she caused it?
classified ad – a short advertisement published in a newspaper
* We placed a classified ad in the newspaper to sell our car.
personals – a short advertisement written by people who are looking for a boyfriend, girlfriend, husband, wife, or other social relationships
* Did you know that Clea met her husband through the personals?
carpool – a group of people who drive to work or another place together, to save money or to protect the environment
* I’m joining a carpool to work so I can save money on gas.
resource – a tool that can help you; useful things that can help you do something
* Getting information about universities is easy because there are so many resources on the Internet.
to swear by (something) – to think that something is very, very good
* I swear by this recipe for cooking chicken. It will make the best chicken you have ever tasted!
“in” – trendy; fashionable; popular with many people
* The “in” place for vacation this year is Miami, so we’d better make our reservations early.
to swear in – to have an official meeting for someone to accept an important public job
* This ceremony is to officially swear in the new president of our organization.
What Insiders Know
Tips on Avoiding Scams on Craigslist
Craigslist has become a very popular and useful website for people looking for jobs, advertising a service, looking for social relationships, and for buying and selling. Anyone can use Craigslist and for most people, it’s free to use.
However, like other popular Internet websites, Craigslist is a place where dishonest people may try to pull “scams” (fraud; dishonest plan) to cheat people out of their money. Some of these scams can be very simple or very “elaborate” (with many parts or details), so it’s important that users “beware” (be careful).
“Common sense” (normal thinking and intelligence) will help users avoid most scams. However, here are a few “tips” (pieces of advice; suggestions) from people who have used or are frequent users of Craigslist.
First, if you are buying, only buy from people you can meet “face-to-face” (in person). Some scams ask people to send money first and then the item will be mailed or delivered to them. In these cases, the thief gets the money but the buyer never sees their “merchandise” (item they bought).
Look for “posts” (advertisements; messages) with pictures and detailed descriptions. “Fraudulent” (criminal) posts “lure” (attract) customers with “vague” (not detailed) ads for items that are sold at very good prices.
If you are selling on Craigslist, “insist” (require) that the buyer pay in cash. Thieves will try to pay in “fake” (false; not real) checks or “money orders” (a piece of paper a buyer purchases that can be traded for cash. The bank will hold you responsible, not the seller.