= 0012
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''

== 中文释义



M: Hello everyone! And welcome back to EnglishPod! My name is Marco. +
E: I'm Erica. +
M: And today we have a great intermediate 中级的；中等水平的 lesson for you. +
E: That's right, we've got some excellent 优秀的；极好的 real English 实用英语 for you all about cleaning the house. +
M: Cleaning the house, that's a real life situation 现实生活场景, so, we're gonna give you real English. +
E: Exactly 确实如此, so, on today's lesson /we're gonna look at language 用语；表达方式 about cleaning the house. We're also going to learn a few phrases 短语 that you can use if you wanna ask someone for help 寻求某人帮助 /and maybe if you're a little bit lazy 懒惰的 like me… +
M: Hehe. +
E: A phrase or two _to avoid doing work_ 逃避做事. Okay, well, let's get started 开始吧 then with our “vocabulary preview 词汇预习”. +

[.my2]
还能学一两个用来逃避干活的短语。

Voice: Vocabulary preview. +
M: Alright 好的, great, we have two great words for you today. Erica, why don't tell us the first one? +
E: The first word is _such a mess_ 一团糟；乱七八糟. +
M: Such a mess. +
E: Such a mess. +
M: So, when something is a mess… +
E: It's dirty 脏的. +
M: Yeah, or things are everywhere 到处都是. +
E: Disorganized 杂乱无章的；无条理的. +
M: Yeah, so, you know, you have your clothes 衣服 on the floor 地板 and your shoes 鞋子 on… +
E: Okay, so, that sounds a lot like 很像 _my desk 书桌 at work_ 上班的地方；办公室. +
M: Hehe. Your shoes on your desk, yeah, I've seen that; I've been wanting to ask you about that. +

[.my2]
鞋子在书桌上，是啊，我见过；我一直想问你这事儿呢。

E: Hehe. Okay, such a mess – really, really dirty. +

M: Okay, now let's take a look at 看一看 our second word – chores 杂务；零工；困难的工作;家务；日常杂务. +

[.my1]
.案例
====
.chore
-> ##来自##PIE*sker, #转，打转#，词源同charlady, ring. #即在外围打杂的人。#
====

E: Chores. +
M: Chores. +
E: Chores. +
M: Chores is a really common 常见的 word for… +
E: Things /you have to do around the house 家里. +
M: Like, for example 比如, laundry 待洗（或正在洗涤、洗完）的衣物； laundry… +
E: Or making the bed 铺床. +
M: Or when you have to *take out the garbage* 倒垃圾. +
E: Those are all examples 例子 of chores. +
M: Chores, yeah. I guess /everyone can remember when they were kids, they had chores to do. +
E: Yeah, when I was a kid, it was my chore (n.) *to chop (v.)剁，砍，劈 wood* 砍柴. +

[.my2]
我小时候的家务是砍柴。

M: Chop (v.) wood? +
E: Yeah! +
M: That's a great chore. Playing with an axe 斧头. +
E: Hehe. Maybe if you're a boy, but for a girl /it was not so great. +

[.my2]
要是男孩可能觉得好玩，但对女孩来说就没那么有趣了。

M: Uh, that's why you're so strong and fit 健康的. +

[.my2]
难怪你现在又强壮又健康。

E: Yeah. Hehe. +
M: Alright, so, let's listen to our dialogue for the first time. It's gonna be kind of fast 有点快. +
E: But don't worry if you miss something, because we'll explain all of the important language afterwards. +

[.small]
[options="autowidth" cols="1a"]
|===
|Header 1

|A: Honey 亲爱的, the house is such a mess! I need you to help me tidy up 整理；收拾 a bit 一点. My boss and her husband are coming over 过来；来访 for dinner 晚餐 /and the house needs to be spotless (a.)无可挑剔的；无瑕疵的；纯洁的;一尘不染的；极干净的! +
B: I’m in the middle of something 正忙着做某事 right now. I’ll be there in a second 马上；立刻. +
A: This can’t wait! I need your help now! +
B: Alright, alright. I’m coming. +
A: Ok, here’s a list of chores /we need to get done 完成. I’ll do the dishes (餐具)洗碗 and get all the groceries 食品杂货 for tonight. You can sweep 扫地 and mop (v.)用拖把拖 the floors. Oh, and the furniture 家具 needs to be dusted 掸去灰尘. +
B: You know what, I have to pick something up 取某物 at the mall 购物中心, so why don’t you clean the floors /and I’ll go to the supermarket and get all the groceries. +
A: Sure 当然 that’s fine 可以；没问题. Here is the list of all the things you need to get. Don’t forget anything! And can you pick up a bottle of wine on your way home? +

B: Hey, honey I’m back. Wow, the house looks really good! +
A: Great! Can you set the table 摆餐具? +
B: Just a sec 等一下 /I’m just gonna vacuum (v.)用吸尘器打扫 this rug 小地毯 real fast 非常快 +

[.my2]
我先快速用吸尘器吸一下这块小地毯。

A: Wait! Don’t turn it on... +
|===




E: Oh my God, Marco, what happened there? +
M: An explosion 爆炸. +
E: We love a good explosion here at EnglishPod. +

[.my2]
咱们《EnglishPod》就爱搞点这种 “爆炸” 小插曲。

M: We're gonna give you *as many* explosions *as possible*. Hehe. +

[.my2]
我们会尽量多安排点这种有趣的小意外。

E: Okay. +
M: Alright, so, let's take a look at our “language takeaway 语言要点”. +
Voice: Language takeaway. +
E: So, 'language takeaway' is the part of our lesson /where we teach you `主` what we think `系` are some really important words that are found in the dialogue. +
M: Exactly, and we have three really important words in our dialogue today, so, let's start with 从……开始 the first one. +

E: Tidy up 整理、收拾. +
M: Tidy up. +
E: Tidy up. +
M: So, *to tidy up* means (v.) to… +
E: Put things in their correct spot 正确的位置. +
M: Right, so, put the shoes on the floor. +
E: Yeah. +
M: Take them off… +
E: Get the shoes off my desk. +
M: Exactly, so, tidy up – organize (v.) things 整理东西 a little bit 稍微. +
E: Yeah, *put things away* 收拾东西, 把东西收起来. +

M: Okay, let's take a look at our second word now – spotless 无可挑剔的；无瑕疵的；纯洁的. +
E: Spotless. +
M: Spotless. +
E: Spotless. +
M: So, when you want something to be spotless… +
E: You want it to be really clean. +
M: Really clean, not a spot of dirt 一点灰尘 on it. +
E: Like your desk. +
M: Exactly, my desk is spotless. +
E: My desk is not spotless. +

M: Hehe. Alright, great word. Now let's take a look at our last word for language takeaway – mall. +
E: Mall. +
M: Mall. +
E: M-A-L-L, mall. +
M: Mall, yeah. It's a strange sounding word 发音的单词. +
E: It is a little bit funny 滑稽的；有趣的 sounding, but it basically  means a large building with many shops inside, many different stores inside. +
M: Right. Now, in British English  /you would say shopping center. +
E: Yeah, I think that's a little bit more common, but in American English  we say mall. +

M: Mall. Great, so, now it's time _in our show_ to look at “putting it together 学以致用”. +
Voice: Putting it together. +
E: Okay, so, in 'putting it together' /we take a word from the dialogue /and we show you how to use this word in real English, so, we give you a couple of examples of how this particular word can be used. +
M: Exactly, so, `主` the word that we have for today `系` is groceries 杂货；食品；生活用品. +
E: Groceries. +
M: Groceries. +
E: Groceries. +
M: Erica, why don't you tell us _what groceries are all about_ (关于……的情况)杂货都是关于什么的? +
E: So, groceries are all of the food items 食品；食物 that you need to buy at the supermarket, so, like your bread and milk and meat and… +
M: Vegetables 蔬菜. +
E: Exactly. +
M: All that stuff. +
E: Those are all groceries. +
M: Okay, so, let's listen to some examples on how we use this phrase. +

Voice: Example one. +
A: There’s no milk. Can you go to the grocery store 杂货店? +

Voice: Example two. +
B: Here’s the grocery list 购物清单. I need all of these things, so that I can cook dinner 做晚饭 tonight. Don’t forget anything. +

Voice: Example three 第三个例子. +
C: I hate _grocery shopping_ 买食品杂货. I can never find what I’m looking for. +

M: Okay, great examples. We heard some really interesting combinations 搭配, right? +
E: Yeah, we heard grocery store. +
M: Which is _where you buy your groceries_. +
E: Exactly, grocery shopping. +
M: Buying all your groceries. Hehe. +
E: Hehe. And grocery list. +
M: Um, where you have all the items 物品 that you need to buy. +
E: A list of everything you need to buy. +
M: Exactly. +
E: You know, grocery store, I think this is quite a common word in Canada. +
M: Probably in North America. +
E: Yeah, do you say grocery store in America ? +
M: Well, if it's a small one 小的杂货店. +
E: Really, so… +
M: Like a small store 小商店. +
E: In Canada /I say grocery store for even 甚至 like a supermarket. +

[.my2]
在加拿大，就算是大型超市，我也会说 “grocery store”。

M: Really? +
E: Yeah. +
M: I guess, mm, I would say supermarket for a large one 大型超市 /and grocery store for a little corner shop 街角小店. +
E: All of these little differences /in American and Canadian English. +
M: Hehe. +
E: Okay, I think it's time for us to listen to our dialogue another time, this time it'll be a little bit slower. +

\... +
\... +
\... +

M: Okay, great stuff 很棒的内容. Love hearing that explosion, that vacuum just is a bomb. +

[.my2]
真喜欢听那个 “爆炸” 声，那吸尘器简直像个炸弹。

E: Yeah. +
M: Hehe. +
E: In this dialogue /there was some really interesting language that you can use /if you don't wanna do any chores 杂务；零工；困难的工作 in a house. +
M: Exactly, so, it's time now for “fluency builder 流利表达训练”. +

Voice: Fluency builder. +
E: You know, 'fluency builder' is a part of our show /that we use to take a common phrase or a word /后定说明 that you already know /and show (v.) you how to express (v.) that idea more fluently 流利地 and more naturally. +
M: Exactly, so, let's take a look at our first idea /that we want to explain. +
E: Let’s say 假设 you're watching TV like the woman in this dialogue /and your husband wants you to help him do the chores /and you say “No, I'm busy”. +
M: Right, or “I'm doing something”. +
E: Those are two great expressions 表达方式, but we heard something a little bit different in the dialogue.  +
Phrase 1: I’m in the middle of something right now. I’m in the middle of something right now. +
M: Yeah, that phrase is great. It means she's busy, she's doing something. +
E: Yeah, I’m in the middle of something. +
M: Yeah. +

E: And so, Marco, you can tell us about our next phrase. +
M: Okay, well, now suppose that 假设 you want to say, you'll be there soon 很快到那里. +
E: You might say “I'll be there soon” or… +
M: “I'm coming”. +
E: Exactly. +
M: But in our dialogue /we heard something a little bit different, let's listen.

Phrase 2: I’ll be there in a second. I’ll be there in a second. +
M: So, this is a more natural way of saying “I'll be there very soon”. +
E: Yeah, you know what, I think /I use this phrase almost every day, I’ll be there in a second. +
M: Yeah, yeah, it's really common. +
E: Yeah, it means I'll be there really fast. +
M: Yes. +
E: Okay, so, our final item today in fluency builder, um, is a great phrase that helps you say the idea “Could you” or “Would you”. +
M: Right or “Can you”. +
E: Yeah, so, “Can you sweep the floor”, “Could you sweep the floor”. +
M: But in the dialogue /we heard something that's a little bit different.

Phrase 3: Why don’t you clean the floors /and I’ll go to the supermarket? Why don’t you clean the floors /and I’ll go to the supermarket? +
M: Great, so, this is more natural /and it's giving a suggestion 提出建议. +
E: Yeah, it's sort of 有点像 a polite way  of asking someone to clean the floors. +
M: Right, it's a really good and polite way of saying it, yeah, I would agree on that 同意这一点. This was fluency builder, now we are ready to listen to our dialogue again at its normal speed 正常速度. +
E: And this time /you'll understand a lot better 好得多. +

\... +
\... +
\... +

E: Um, has… has this ever happened to you 发生在你身上过吗 as your vacuum cleaner 吸尘器 exploded in your house? +
M: Well, not a big explosion like this one. +
E: Not so dramatically 戏剧性地；夸张地. +
M: Yeah, not so dramatically, but, ah, I've had this happen to me before, yeah. And dust everywhere /and it's just… it's a mess. You don't wanna have… +
E: You know, this word vacuum, um, is really… a very American word. +
M: Yeah, vacuum. Vacuum (v.)用真空吸尘器打扫 the rug, vacuum the carpet 地毯. +
E: Yeah, vacuum cleaner. In the UK /what do they say? +
M: Hoover 胡佛吸尘器（代指吸尘器）. +
E: Hoover. +
M: Yeah, hoover. +
E: Hoover (v.) the rug. +
M: Hoover the rug. Which is interesting, because it's actually a brand 品牌. +
E: Yeah? +
M: So, I guess it's kind of like 有点像 American English /you say “Pass me a kleenex （商标名,代指纸巾）”. +
E: Oh, that's true. +
M: That would be like a tissue 纸巾. +
E: Yeah. +
M: So, I guess they say “Hoover (v.) the rug” or “Hoover the house”, yeah. +
E: Wow. +
M: Hehe. +
E: You know, I really love these small differences in meaning 含义上的小差异 that we have between American English and British English. +

M: Yeah, it's… it's fun, okay. Well, another interesting thing about this is that /the man was doing the house work 家务. +
E: I know. +
M: He's a househusband 家庭主夫. +
E: Yeah, so, he's the one /doing all the chores in the house. +
M: Yeah, that's… well, that's the new trend 新趋势 now. Now it's more popular for men to stay home  /and *take care of* the babies /and clean the house. +
E: Yeah, like when I was growing up 成长过程中, my dad would *take out 取出，提取;消除，清除 the garbage* 倒垃圾 and that was it 就这样. +
M: Hehe. +
E: Hehe. My mom had to do everything else, but now I think /it's becoming a lot more common in… especially in North America /for _the household chores_ 家务事 to be divided between the man and the wife equally 平等地. +
M: Yeah, I think it's fair 公平的, it's fair. +
E: Me too, yeah. +
M: Yeah. +
E: You'd make a good husband 你会是个好丈夫, Marco. +
M: Hehe. That's what they say, but they haven't married me yet. +

[.my2]
大家都这么说，但还没人嫁给我呢。

E: Hehe. Okay. +

M: Alright, well, we're out of time 没时间了 folks 朋友们, be sure to log on to our community website 社区网站 /and you can leave all your comments  /and maybe `主` all the househusbands out there 那里的（所有）家庭主夫 `谓` can give us their feedback 反馈意见 on what they think about this. +
E: Yeah, so, check us out 关注我们 at englishpod.com /and thanks for listening today, everyone, until next time 下次见，this Marco and Erica saying… +
M: Bye! +
E: Good bye! +

'''

== pure

M: Hello everyone! And welcome back to EnglishPod! My name is Marco. +
E: I'm Erica. +
M: And today we have a great intermediate lesson for you. +
E: That's right, we've got some excellent real English for you all about cleaning the house. +
M: Cleaning the house, that's a real life situation, so, we're gonna give you real English. +
E: Exactly, so, on today's lesson we're gonna look at language about cleaning the house. We're 
also going to learn a few phrases that you can use if you wanna ask someone for help and maybe
if you're a little bit lazy like me… +
M: Hehe. +
E: A phrase or two to avoid doing work. Okay, well, let's get started then with our “vocabulary 
preview”. +
Voice: Vocabulary preview. +
M: Alright, great, we have two great words for you today. Erica, why don't tell us the first one? +
E: The first word is such a mess. +
M: Such a mess. +
E: Such a mess. +
M: So, when something is a mess… +
E: It's dirty. +
M: Yeah, or things are everywhere. +
E: Disorganized. +
M: Yeah, so, you know, you have your clothes on the floor and your shoes on… +
E: Okay, so, that sounds a lot like my desk at work. +
M: Hehe. Your shoes on your desk, yeah, I've seen that; I've been wanting to ask you about that. +
E: Hehe. Okay, such a mess – really, really dirty. +
M: Okay, now let's take a look at our second word – chores. +
E: Chores. +
M: Chores. +
E: Chores. +
M: Chores is a really common word for… +
E: Things you have to do around the house. +
M: Like, for example, laundry… +
E: Or making the bed. +
M: Or when you have to take out the garbage. +
E: Those are all examples of chores. +
M: Chores, yeah. I guess everyone can remember when they were kids, they had chores to do. +
E: Yeah, when I was a kid, it was my chore to chop wood. +
M: Chop wood? +
E: Yeah! +
M: That's a great chore. Playing with an axe. +
E: Hehe. Maybe if you're a boy, but for a girl it was not so great. +
M: Uh, that's why you're so strong and fit. +
E: Yeah. Hehe. +
M: Alright, so, let's listen to our dialogue for the first time. It's gonna be kind of fast. +
E: But don't worry if you miss something, because we'll explain all of the important language 
afterwards. +

A: Honey, the house is such a mess! I need you to 
help me tidy up a bit. My boss and her husband
are coming over for dinner and the house needs
to be spotless! +
B: I’m in the middle of something right now. I’ll be 
there in a second. +
A: This can’t wait! I need your help now! +
B: Alright, alright. I’m coming. +
A: Ok, here’s a list of chores we need to get done. I’ll 
do the dishes and get all the groceries for tonight.
You can sweep and mop the floors. Oh, and the
furniture needs to be dusted. +
B: You know what, I have to pick something up at the 
mall, so why don’t you clean the floors and I’ll
go to the supermarket and get all the groceries. +
A: Sure that’s fine. Here is the list of all the things 
you need to get. Don’t forget anything! And can
you pick up a bottle of wine on your way home? +
B: Hey, honey I’m back. Wow, the house looks really 
good! +
A: Great! Can you set the table? +
B: Just a sec I’m just gonna vacuum this rug real fast +
A: Wait! Don’t turn it on... +
E: Oh my God, Marco, what happened there? +
M: An explosion. +
E: We love a good explosion here at EnglishPod. +
M: We're gonna give you as many explosions as possible. Hehe. +
E: Okay. +
M: Alright, so, let's take a look at our “language takeaway”. +
Voice: Language takeaway. +
E: So, 'language takeaway' is the part of our lesson where we teach you what we think are some 
really important words that are found in the dialogue. +
M: Exactly, and we have three really important words in our dialogue today, so, let's start with 
the first one. +
E: Tidy up. +
M: Tidy up. +
E: Tidy up. +
M: So, to tidy up means to… +
E: Put things in their correct spot. +
M: Right, so, put the shoes on the floor. +
E: Yeah. +
M: Take them off… +
E: Get the shoes off my desk. +
M: Exactly, so, tidy up – organize things a little bit. +
E: Yeah, put things away. +
M: Okay, let's take a look at our second word now – spotless. +
E: Spotless. +
M: Spotless. +
E: Spotless. +
M: So, when you want something to be spotless… +
E: You want it to be really clean. +
M: Really clean, not a spot of dirt on it. +
E: Like your desk. +
M: Exactly, my desk is spotless. +
E: My desk is not spotless. +
M: Hehe. Alright, great word. Now let's take a look at our last word for language takeaway – 
mall. +
E: Mall. +
M: Mall. +
E: M-A-L-L, mall. +
M: Mall, yeah. It's a strange sounding word. +
E: It is a little bit funny sounding, but it basically means a large building with many shops inside, 
many different stores inside. +
M: Right. Now, in British English you would say shopping center. +
E: Yeah, I think that's a little bit more common, but in American English we say mall. +
M: Mall. Great, so, now it's time in our show to look at “putting it together”. +
Voice: Putting it together. +
E: Okay, so, in 'putting it together' we take a word from the dialogue and we show you how to 
use this word in real English, so, we give you a couple of examples of how this particular word
can be used. +
M: Exactly, so, the word that we have for today is groceries. +
E: Groceries. +
M: Groceries. +
E: Groceries. +
M: Erica, why don't you tell us what groceries are all about? +
E: So, groceries are all of the food items that you need to buy at the supermarket, so, like your 
bread and milk and meat and… +
M: Vegetables. +
E: Exactly. +
M: All that stuff. +
E: Those are all groceries. +
M: Okay, so, let's listen to some examples on how we use this phrase. +
Voice: Example one. +
A: There’s no milk. Can you go to the grocery store? +
Voice: Example two. +
B: Here’s the grocery list. I need all of these things, so that I can cook dinner tonight. Don’t 
forget anything. +
Voice: Example three. +
C: I hate grocery shopping. I can never find what I’m looking for. +
M: Okay, great examples. We heard some really interesting combinations, right? +
E: Yeah, we hard grocery store. +
M: Which is where you buy your groceries. +
E: Exactly, grocery shopping. +
M: Buying all your groceries. Hehe. +
E: Hehe. And grocery list. +
M: Um, where you have all the items that you need to buy. +
E: A list of everything you need to buy. +
M: Exactly. +
E: You know, grocery store, I think this is quite a common word in Canada. +
M: Probably in North America. +
E: Yeah, do you say grocery store in America? +
M: Well, if it's a small one. +
E: Really, so… +
M: Like a small store. +
E: In Canada I say grocery store for even like a supermarket. +
M: Really? +
E: Yeah. +
M: I guess, mm, I would say supermarket for a large one and grocery store for a little corner 
shop. +
E: All of these little differences in American and Canadian English. +
M: Hehe. +
E: Okay, I think it's time for us to listen to our dialogue another time, this time it'll be a little bit 
slower. +

\... +
\... +
\... +

M: Okay, great stuff. Love hearing that explosion, that vacuum just is a bomb. +
E: Yeah. +
M: Hehe. +
E: In this dialogue there was some really interesting language that you can use if you don't 
wanna do any chores in a house. +
M: Exactly, so, it's time now for “fluency builder”. +
Voice: Fluency builder. +
E: You know, 'fluency builder' is a part of our show that we use to take a common phrase or a 
word that you already know and show you how to express that idea more fluently and more
naturally. +
M: Exactly, so, let's take a look at our first idea that we want to explain. +
E: Let’s say you're watching TV like the woman in this dialogue and your husband wants you to 
help him do the chores and you say “No, I'm busy”. +
M: Right, or “I'm doing something”. +
E: Those are two great expressions, but we heard something a little bit different in the dialogue. 
Phrase 1: I’m in the middle of something right now. I’m in the middle of something right now. +
M: Yeah, that phrase is great. It means she's busy, she's doing something. +
E: Yeah, I’m in the middle of something. +
M: Yeah. +
E: And so, Marco, you can tell us about our next phrase. +
M: Okay, well, now suppose that you want to say, you'll be there soon. +
E: You might say “I'll be there soon” or… +
M: “I'm coming”. +
E: Exactly. +
M: But in our dialogue we heard something a little bit different, let's listen. 
Phrase 2: I’ll be there in a second. I’ll be there in a second. +
M: So, this is a more natural way of saying “I'll be there very soon”. +
E: Yeah, you know what, I think I use this phrase almost every day, I’ll be there in a second. +
M: Yeah, yeah, it's really common. +
E: Yeah, it means I'll be there really fast. +
M: Yes. +
E: Okay, so, our final item today in fluency builder, um, is a great phrase that helps you say the 
idea “Could you” or “Would you”. +
M: Right or “Can you”. +
E: Yeah, so, “Can you sweep the floor”, “Could you sweep the floor”. +
M: But in the dialogue we heard something that's a little bit different. 
Phrase 3: Why don’t you clean the floors and I’ll go to the supermarket? Why don’t you clean
the floors and I’ll go to the supermarket? +
M: Great, so, this is more natural and it's giving a suggestion. +
E: Yeah, it's sort of a polite way of asking someone to clean the floors. +
M: Right, it's a really good and polite way of saying it, yeah, I would agree on that. This was 
fluency builder, now we are ready to listen to our dialogue again at its normal speed. +
E: And this time you'll understand a lot better. +

\... +
\... +
\... +

E: Um, has… has this ever happened to you as your vacuum cleaner exploded in your house? +
M: Well, not a big explosion like this one. +
E: Not so dramatically. +
M: Yeah, not so dramatically, but, ah, I've had this happen to me before, yeah. And dust 
everywhere and it's just… it's a mess. You don't wanna have… +
E: You know, this word vacuum, um, is really… a very American word. +
M: Yeah, vacuum. Vacuum the rug, vacuum the carpet. +
E: Yeah, vacuum cleaner. In the UK what do they say? +
M: Hoover. +
E: Hoover. +
M: Yeah, hoover. +
E: Hoover the rug. +
M: Hoover the rug. Which is interesting, because it's actually a brand. +
E: Yeah? +
M: So, I guess it's kind of like American English you say “Pass me a kleenex”. +
E: Oh, that's true. +
M: That would be like a tissue. +
E: Yeah. +
M: So, I guess they say “Hoover the rug” or “Hoover the house”, yeah. +
E: Wow. +
M: Hehe. +
E: You know, I really love these small differences in meaning that we have between American 
English and British English. +
M: Yeah, it's… it's fun, okay. Well, another interesting thing about this is that the man was 
doing the house work. +
E: I know. +
M: He's a househusband. +
E: Yeah, so, he's the one doing all the chores in the house. +
M: Yeah, that's… well, that's the new trend now. Now it's more popular for men to stay home 
and take care of the babies and clean the house. +
E: Yeah, like when I was growing up, my dad would take out the garbage and that was it. +
M: Hehe. +
E: Hehe. My mom had to do everything else, but now I think it's becoming a lot more common 
in… especially in North America for the household chores to be divided between the man and
the wife equally. +
M: Yeah, I think it's fair, it's fair. +
E: Me too, yeah. +
M: Yeah. +
E: You'd make a good husband, Marco. +
M: Hehe. That's what they say, but they haven't married me yet. +
E: Hehe. Okay. +
M: Alright, well, we're out of time folks, be sure to log on to our community website and you 
can leave all your comments and maybe all the househusbands out there can give us their
feedback on what they think about this. +
E: Yeah, so, check us out at englishpod.com and thanks for listening today, everyone, until next 
time, this Marco and Erica saying… +
M: Bye! +
E: Good bye! 
 
