= 0014
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


== 中文释义

M: Hello English learners! And welcome to another great podcast  with EnglishPod! My name is Marco. +
E: And I'm Erica. +
M: And today we have another really great lesson for you – elementary 初级的；基础的 lesson. +
E: That's right and that's another lesson about money. +
M: We have no money here at EnglishPod, we are in debt 负债；欠债 here. +

[.my2]
咱们《EnglishPod》这儿可是没什么钱，还欠着债呢。

E: In debt! +
M: Yes. +
E: Okay. +
M: In dept. +
E: In debt. +
M: So, what does that mean? Why don't you tell us? +
E: If I owe 欠；负债 you money, I'm in debt. +
M: In debt, yes. +
E: In fact, I think I am in debt to you. +
M: Hehe. You owe me two fifty (2,50) for a coke zero 零度可乐 today. +
E: That's true. +
M: Hehe. Alright. Okay, so, let's get started 开始吧；着手进行； let's take a look at our “vocabulary preview”. +

Voice: Vocabulary preview. +
E: We have two words today in our vocabulary preview /and the first one is recession 经济衰退；不景气. +
M: Recession. +
E: Recession. +
M: Recession. +
E: So, recession. Everyone's talking about it right now /and what does it mean? +
M: I don't know. +
E: Hehe. +
M: Hehe. That's your topic 话题；主题. I don't know. I really don't know, why don't you tell me, Erica, cause this isn't my topic for today? +

[.my2]
这可是你要讲的内容，我可不知道。我是真不知道，埃里卡，你给我讲讲呗，因为今天这个词不是我负责的呀？

E: Okay. +
M: Hehe. +
E: Recession is a period of time /when the economy of a country is doing badly. +
M: In a recession /the country is making less money. +
E: That's true, so, maybe we can give a few examples of things that happen in a recession /to show the meaning of this a little bit better. +
M: Right, so, for example, in a recession /many people lose their jobs. +
E: Because, uh, companies might close 关闭 or go bankrupt 破产. +
M: Exactly 确实如此, and also people start spending less money. +
E: That's true, and the stock prices 股价 of companies, um, fall pretty dra… +
M: ??? fall. +
E: Yeah, they… they fall a lot, hey? +
M: Yeah, yeah, and that's what's going on 发生；进行 now /in the United States. +
E: Very true. +

M: Okay, so, let's take a look at our second word /and it has to do with 与……有关 recession, it's broke 没钱的；破产的. +
E: Broke. +
M: Broke. +
E: I'm broke. +
M: Broke, it means that /you have no money, you're broke. +
E: I'm broke. +
M: Right, so, these are our two words for vocabulary preview today /and you're going to hear them in the dialogue. +
E: This dialogue is about a man who is in debt, he's broke. Let's find out 弄清楚；查明 what happens. +


[.small]
[options="autowidth" cols="1a"]
|===
|Header 1

|A: Hello, I’m here to see Mr. Corleone. +
B: Right this way 这边请, sir. +
C: Charlie! What can I do for you? +
B: Mr. Corlone, I’m really sorry to trouble you, but I need your help. +
C: Anything for you, Charlie! Your father was like a brother to me. +
B: Well, sir, you see, this recession has hit me pretty hard; I lost my job /and I’m in a lot of debt. +
C: I see. . . . . . +
B: Yeah, you know, I’ve got _credit card bills_ 信用卡账单, car payments 汽车贷款还款, I’ve got to pay (v.) my mortgage 按揭，抵押贷款; and on top of all that, I have to pay my son’s college tuition. +

[.my1]
.案例
====
.mortgage
-> 来自古法语mort gage,死亡承诺，##来自mort,死亡，词源同 mortal, gage,承诺，##词源同engage,wage.比喻用法，##即直到死亡也会履行的承诺。##用于指古代的抵押资产以换取借款的经济行为，即现代意义上的按揭。
====


C: So you’re asking for a loan 贷款，借款.  +
B: Well, I just thought 我只是想 /maybe you could help me out 帮我一把；帮我解决困难. +
C: What? At a time like this? I’m broke too, you know! You’re not the only one who has been hit by 受到……的影响 the recession! I lost half my money in the stock market crash 股市崩盘! Go on! Get outa (prep.<非正式>离开) here 离开这里!
|===



M: Okay, so, that was a bit unexpected 想不到的，出乎意料的；意外的. +
E: Yeah, that was certainly  strange. He didn't go to the bank  *to ask for*  money, did he? +
M: No, he went to the mob 黑帮；犯罪集团. +
E: O… +
M: And the mob is broke +
E: Oh, no! You know it's a bad recession when even the mob runs out of 用完；耗尽 money. +
M: Hehe. Alright, so, why don't we start by looking at our “language takeaway”? +

Voice: Language takeaway. +
E: Alright, so, for today's language takeaway /we have four words from the dialogue, which we think are really important. +
M: Yes, so, why don't we start with the first one? Loan 贷款；借款. +
E: Loan. +
M: Loan. +
E: Loan. +
M: So, Erica, tell us about a loan? What is a loan? +
E: Okay, when you borrow money, you get a loan. +
M: A loan, yes. Not to be confused with 与……混淆 alone 独自；单独, like by myself. Hehe. +
E: No, so, this is L-O-A-N. +
M: Loan. +
E: Right. +

M: Okay, great. Let's take a look at our second word – mortgage 抵押贷款（尤指购房贷款）. +
E: Mortgage. +
M: Mortgage. +
E: Mortgage. +
M: Now, this is very common. I'm sure many of you have mortgages. What is a mortgage? +
E: A mortgage is a type of a loan. Basically, it's a loan that helps you to buy a house. +
M: A house or property 房产；财产. +
E: Yeah, so, this is a funny word. I mean there's the strange mortgage with a T. +

[.my2]
这个词的拼写还挺特别的，你看它里面有个字母 “T”。

M: Yeah, it has a T in it, but you don't pronounce 发音 it, you say mor[t]gage, mor[t]gage. +
E: So, not mort… morTgage. +
M: Not, morTgage. +
E: Mor[t]gage. +
M: Mor[t]gage, yeah. I had trouble  spelling (v.)拼写 that one /for this lesson, so, I learned it well now. +

[.my2]
为了准备这节课，我之前拼写这个词还遇到点困难呢，不过现在我已经记牢了。

E: Okay. Let's move to our third word today. +
M: Hit me pretty hard 对我打击很大；让我深受影响. +
E: Hit me pretty hard. +
M: Hit me pretty hard. +
E: Hit me pretty hard. I think we have some examples that will help us understand this phrase. +

Voice: Example one. +
A: My divorce 离婚 hit me pretty hard. I’m so depressed 沮丧的；抑郁的. +

Voice: Example two. +
B: This cold 感冒 has hit me pretty hard. I’ve been in bed  for a week. +

Voice: Example three. +
C: The news of Fluffy’s death `谓` hit me pretty hard. I’ve been crying for days. +

M: Okay, so, that's a lot clear. +
E: Yeah. +

M: Great. Why don't we take a look at our last word for language takeaway? +
E: Tuition 学费. +
M: Tuition. +
E: Tuition. +
M: Tuition. +
E: So, this is the money you have to pay (v.) to your school, so, that you can study there. +
M: Right, um, usually it's in college 学院, right, or university 大学? +
E: Yeah, but sometimes in some countries /you have to pay tuition for public school 公立学校. +

M: Okay, great, so, it's time to listen to the dialogue again /and it's gonna be slower, so we can listen to all the words that we just talked about. +

\... +
\... +
\... +

E: Okay, so, I think a lot of the key language we just talked about /is a lot more clear now, but you know, I also noticed some really interesting phrases in this dialogue. +
M: Yes, I did too, so, let's start with “fluency builder”. +

Voice: Fluency builder. +
E: 'Fluency builder' is a tool /that we use to help you sound 听起来 more native 母语者般的；地道的. +
M: Right, so, you can sound more natural 自然的 when you're speaking. +
E: So, we take a really common phrase /and we show you some great natural ways of expressing that same idea. +
M: Exactly, and today we have three of these examples. Let's start with the first one. +

E: So, this phrase /we use when we want to ask somebody /“Can I help you?” +
Phrase 1: What can I do for you? What can I do for you? +
E: Yeah, that sounds really, really polite and really natural. +
M: Right, so, instead of 代替，而不是 saying “Can I help you” or… I don't know, “What do you need”, we can just say _what can I do for you_. +

[.my2]
比起说 “Can I help you” 或者…… 比如 “ What do you need（你需要什么）”，我们直接说 “what can I do for you” 就可以了。

E: Exactly. +
M: Great. +

E: So, let's move to our second phrase. This phrase we use when we need something, when we wanna say “I'm sorry to bother you 很抱歉打扰你”. +
M: Or “I'm sorry to interrupt 打扰；打断”. +
E: Okay, let's listen.

Phrase 2: I’m really sorry to trouble (v.) you. I’m really sorry to trouble you. +
E: I’m sorry to trouble you. This phrase might be a little bit more difficult to understand how it's used, um, but we've got some examples. +
M: Yes, so, let's listen. +

Voice: Example one. +
A: Can I trouble you for a moment 麻烦你一下? I just need you *to sign 签名 this form* for me. +

Voice: Example two. +
B: I’m sorry to trouble you, but _may I go home early today_? +

Voice: Example three. +
C: Can I trouble you for a pen? Mine is not working (v.) anymore. +

M: Okay, so, now let's take a look at our last phrase for fluency builder – on top of all that 除此之外；更糟糕的是（或更棒的是）. +
E: On top of all that. +
M: On top of all that. +
E: This is a really useful phrase. Marco, how would you use it? +
M: Well, for example, today I lost my job… +
E: Oh, no. +
M: My car got stolen 被偷了. +
E: Oh, my God. +
M: And _on top of all that_ /my girlfriend *broke up with* 与……分手 me. +
E: That was a terrible day. +
M: It was, but don't worry, you can use this phrase also in a positive 积极的；正面的 way. +
E: That's true, you could say “So, today was a really great day! It was my birthday  /and all my friends came to visit  me /and _on top of all that_ I got _a million_ 一百万;许多的，无数的 presents 礼物”. +

[.my2]
除此之外，我还收到了好多礼物。

[.my1]
.案例
====
.million
*a millionmillions (of...)*: ( informal ) a very large amount 大量 +
•I still have a million things to do. 我还有很多很多的事情要做。 +
•There were millions of people there. 那里人山人海。 +
•He made his millions (= all his money) on currency deals. 他的万贯家财, 都是通过外汇交易得到的。 +
====

M: Hehe. That is a great day, so, you can use _on top of all that_ in this way. +
E: It's like “_and also_ 也；并且;而且；还有”. +
M: And also, yeah. +
E: Yeah, so, _on top of all that_. +

M: So, we are ready to listen to our dialogue a third time. We can hear all the words that we just talked about and all the phrases /and you'll definitely 肯定；一定 be able to understand a lot better now. +


\... +
\... +
\... +


E: Today's dialogue was all about _being in debt_ 陷入债务之中, right? +
M: Yes. +
E: And… and different people have different attitudes 态度 or different viewpoints 观点 on _being in debt_. +
M: Yes, that's true, for example, in North America and in Canada /it's a really common thing. +
E: Yeah, *it's actually 实际上 almost good* to be in debt. +
M: It's more than 不仅仅是 good, it's necessary to be in debt. +
E: That's right, unless 除非 you have… a history of _being in debt_ and regularly 定期地 paying off 还清 your debts, you can't actually borrow money, you can't get a mortgage, you can't get a… a car loan 汽车贷款, so you can buy a new car. +

[.my2]
除非你有欠债记录，而且能定期还清债务，否则你根本借不到钱，没法申请房贷，也没法申请汽车贷款来买新车。

M: Right, that's called 被称为 a credit history 信用记录, so, you must have a good credit history /in order to 为了 be able to, like you say, buy a car or buy a house. +
E: Yeah, and you know the funny thing 有趣的事情 is, um, when I was in university, maybe I was eighteen years old, the first thing that happened at university was, you know, banks came to our university /and started offering 提供 you credit cards 信用卡, so, you can get a credit card when you're eighteen /no problem 没问题. +
M: And not only 不仅 do they offer you credit cards, they give you like free gifts 免费礼物 if you sign up for 注册；申请 a credit card. +
E: I know /they really want you to have a credit card. +
M: Of course they want you to spend more money, that’s the trick 把戏；圈套. +

E: Yeah, but you know what, it's totally different /in Europe, for example, I used to live (v.)曾经住 in Switzerland /and there they're really careful 谨慎的 with debts /like it's a bad thing to be in debt. +
M: Oh, yeah, I mean it's bad _to be in debt_, definitely. +
= E: For example, if I wanna have a credit card in Switzerland /and let’s say /I want to have _a limit of_, um, _five hundred (500) francs_ 法郎 that I can spend every month, I need to put in 存入 my bank account 银行账户 seven hundred (700) francs /before I can even 甚至 spend that credit card money, so, it's totally opposite 相反的 from North America. +

[.my2]
比如在瑞士，如果我想办一张信用卡，假设我想每月有 500 法郎的消费额度，那我得先在银行账户里存 700 法郎，才能用信用卡消费，这和北美洲完全相反。

M: Hehe. Well, yeah, I mean in North America /it's crazy /the way that people are in debt /and it's showing now 现在已经显示出来了 with the recession  （经济的）衰退（期）, right? +
E: Yeah, that's true. +

[.my2]
是啊，北美洲人欠债的情况确实很夸张，现在经济衰退，这种情况就更明显了，是吧？

M: So, everyone, be sure to handle (v.) your money carefully, don't _be in debt_ unless you really, really have to. +
E: Good _financial 财务的；金融的 advice_ 建议 from EnglishPod. +
M: EnglishPod – financial advising service 咨询服务. Hehe. +
E: Okay, everyone, thanks for listening, now remember /if you have any questions or comments, please, visit (v.) our website  at englishpod.com. +
M: Right, Erica and I are always there to answer all the questions /and we really like to receive comments and suggestions from all our users, so, be sure to go /and leave us your comments. +
E: Okay, Marco, it's been fun 很开心. +
M: Yes, it has, but sadly we have to go now, so, until next time 下次见 it's… +
E: Good bye! +
M: Bye!




'''

== pure

M: Hello English learners! And welcome to another great podcast with EnglishPod! My 
name is Marco. +
E: And I'm Erica. +
M: And today we have another really great lesson for you – elementary lesson. +
E: That's right and that's another lesson about money. +
M: We have no money here at EnglishPod, we are in debt here. +
E: In debt! +
M: Yes. +
E: Okay. +
M: In dept. +
E: In debt. +
M: So, what does that mean? Why don't you tell us? +
E: If I owe you money, I'm in debt. +
M: In debt, yes. +
E: In fact, I think I am in debt to you. +
M: Hehe. You owe me two fifty (2,50) for a coke zero today. +
E: That's true. +
M: Hehe. Alright. Okay, so, let's get started; let's take a look at our “vocabulary preview”. +
Voice: Vocabulary preview. +
E: We have two words today in our vocabulary preview and the first one is recession. +
M: Recession. +
E: Recession. +
M: Recession. +
E: So, recession. Everyone's talking about it right now and what does it mean? +
M: I don't know. +
E: Hehe. +
M: Hehe. That's your topic. I don't know. I really don't know, why don't you tell me, Erica, 
cause this isn't my topic for today? +
E: Okay. +
M: Hehe. +
E: Recession is a period of time when the economy of a country is doing badly. +
M: In a recession the country is making less money. +
E: That's true, so, maybe we can give a few examples of things that happen in a recession 
to show the meaning of this a little bit better. +
M: Right, so, for example, in a recession many people lose their jobs. +
E: Because, uh, companies might close or go bankrupt. +
M: Exactly, and also people start spending less money. +
E: That's true, and the stock prices of companies, um, fall pretty dra… +
M: ??? fall. +
E: Yeah, they… they fall a lot, hey? +
M: Yeah, yeah, and that's what's going on now in the United States. +
E: Very true. +
M: Okay, so, let's take a look at our second word and it has to do with recession, it's broke. +
E: Broke. +
M: Broke. +
E: I'm broke. +
M: Broke, it means that you have no money, you're broke. +
E: I'm broke. +
M: Right, so, these are our two words for vocabulary preview today and you're going to 
hear them in the dialogue. +
E: This dialogue is about a man who is in debt, he's broke. Let's find out what happens. +


\... +
\... +
\... +

M: Okay, so, that was a bit unexpected. +
E: Yeah, that was certainly strange. He didn't go to the bank to ask for money, did he? +
M: No, he went to the mob. +
E: O… +
M: And the mob is broke +
E: Oh, no! You know it's a bad recession when even the mob runs out of money. +
M: Hehe. Alright, so, why don't we start by looking at our “language takeaway”? +
Voice: Language takeaway. +
E: Alright, so, for today's language takeaway we have four words from the dialogue, which 
we think are really important. +
M: Yes, so, why don't we start with the first one? Loan. +
E: Loan. +
M: Loan. +
E: Loan. +
M: So, Erica, tell us about a loan? What is a loan? +
E: Okay, when you borrow money, you get a loan. +
M: A loan, yes. Not to be confused with alone, like by myself. Hehe. +
E: No, so, this is L-O-A-N. +
M: Loan. +
E: Right. +
M: Okay, great. Let's take a look at our second word – mortgage. +
E: Mortgage. +
M: Mortgage. +
E: Mortgage. +
M: Now, this is very common. I'm sure many of you have mortgages. What is a mortgage? +
E: A mortgage is a type of a loan. Basically, it's a loan that helps you to buy a house. +
M: A house or property. +
E: Yeah, so, this is a funny word. I mean there's the strange mortgage with a T. +
M: Yeah, it has a T in it, but you don't pronounce it, you say mor[t]gage, mor[t]gage. +
E: So, not mort… morTgage. +
M: Not, morTgage. +
E: Mor[t]gage. +
M: Mor[t]gage, yeah. I had trouble spelling that one for this lesson, so, I learned it well 
now. +
E: Okay. Let's move to our third word today. +
M: Hit me pretty hard. +
E: Hit me pretty hard. +
M: Hit me pretty hard. +
E: Hit me pretty hard. I think we have some examples that will help us understand this 
phrase. +
Voice: Example one. +
A: My divorce hit me pretty hard. I’m so depressed. +
Voice: Example two. +
B: This cold has hit me pretty hard. I’ve been in bed for a week. +
Voice: Example three. +
C: The news of Fluffy’s death hit me pretty hard. I’ve been crying for days. +
M: Okay, so, that's a lot clear. +
E: Yeah. +
M: Great. Why don't we take a look at our last word for language takeaway? +
E: Tuition. +
M: Tuition. +
E: Tuition. +
M: Tuition. +
E: So, this is the money you have to pay to your school, so, that you can study there. +
M: Right, um, usually it's in college, right, or university? +
E: Yeah, but sometimes in some countries you have to pay tuition for public school. +
M: Okay, great, so, it's time to listen to our dialogue again and it's gonna be slower, so we 
can listen to all the words that we just talked about. +

\... +
\... +
\... +

E: Okay, so, I think a lot of the key language we just talked about is a lot more clear now, 
but you know, I also noticed some really interesting phrases in this dialogue. +
M: Yes, I did too, so, let's start with “fluency builder”. +
Voice: Fluency builder. +
E: 'Fluency builder' is a tool that we use to help you sound more native. +
M: Right, so, you can sound more natural when you're speaking. +
E: So, we take a really common phrase and we show you some great natural ways of 
expressing that same idea. +
M: Exactly, and today we have three of these examples. Let's start with the first one. +
E: So, this phrase we use when we want to ask somebody “Can I help you?” 
Phrase 1: What can I do for you? What can I do for you? +
E: Yeah, that sounds really, really polite and really natural. +
M: Right, so, instead of saying “Can I help you” or… I don't know, “What do you need”, we 
can just say what can I do for you. +
E: Exactly. +
M: Great. +
E: So, let's move to our second phrase. This phrase we use when we need something, when 
we wanna say “I'm sorry to bother you”. +
M: Or “I'm sorry to interrupt”. +
E: Okay, let's listen. 
Phrase 2: I’m really sorry to trouble you. I’m really sorry to trouble you. +
E: I’m sorry to trouble you. This phrase might be a little bit more difficult to understand 
how it's used, um, but we've got some examples. +
M: Yes, so, let's listen. +
Voice: Example one. +
A: Can I trouble you for a moment? I just need you to sign this form for me. +
Voice: Example two. +
B: I’m sorry to trouble you, but may I go home early today? +
Voice: Example three. +
C: Can I trouble you for a pen? Mine is not working anymore. +
M: Okay, so, now let's take a look at our last phrase for fluency builder – on top of all 
that. +
E: On top of all that. +
M: On top of all that. +
E: This is a really useful phrase. Marco, how would you use it? +
M: Well, for example, today I lost my job… +
E: Oh, no. +
M: My car got stolen. +
E: Oh, my God. +
M: And on top of all that my girlfriend broke up with me. +
E: That was a terrible day. +
M: It was, but don't worry, you can use this phrase also in a positive way. +
E: That's true, you could say “So, today was a really great day! It was my birthday and all 
my friends came to visit me and on top of all that I got a million presents”. +
M: Hehe. That is a great day, so, you can use on top of all that in this way. +
E: It's like “and also”. +
M: And also, yeah. +
E: Yeah, so, on top of all that. +
M: So, we are ready to listen to our dialogue a third time. We can hear all the words that we 
just talked about and all the phrases and you'll definitely be able to understand a lot better
now. +

A: Hello, I’m here to see Mr. Corleone. +
B: Right this way, sir. +
C: Charlie! What can I do for you? +
B: Mr. Corlone, I’m really sorry to trouble you, but I 
need your help. +
C: Anything for you, Charlie! Your father was like a 
brother to me. +
B: Well, sir, you see, this recession has hit me pretty 
hard; I lost my job and I’m in a lot of debt. +
C: I see. . . . . . +
B: Yeah, you know, I’ve got credit card bills, car pay- 
ments, I’ve got to pay my mortgage; and on top of
all that, I have to pay my son’s college tuition. +
C: So you’re asking for a loan. +
B: Well, I just thought maybe you could help me out. +
C: What? At a time like this? I’m broke too, you 
know! You’re not the only one who has been hit
by the recession! I lost half my money in the stock
market crash! Go on! Get outa here!
 
E: Today's dialogue was all about being in debt, right? +
M: Yes. +
E: And… and different people have different attitudes or different viewpoints on being in 
debt. +
M: Yes, that's true, for example, in North America and in Canada it's a really common thing. +
E: Yeah, it's actually almost good to be in debt. +
M: It's more than good, it's necessary to be in debt. +
E: That's right, unless you have… a history of being in debt and regularly paying off your 
debts, you can't actually borrow money, you can't get a mortgage, you can't get a… a car
loan, so you can buy a new car. +
M: Right, that's called a credit history, so, you must have a good credit history in order 
to be able to, like you say, buy a car or buy a house. +
E: Yeah, and you know the funny thing is, um, when I was in university, maybe I was 
eighteen years old, the first thing that happened at university was, you know, banks came
to our university and started offering you credit cards, so, you can get a credit card when
you're eighteen no problem. +
M: And not only do they offer you credit cards, they give you like free gifts if you sign up 
for a credit card. +
E: I know they really want you to have a credit card. +
M: Of course they want you to spend more money, that’s the trick. +
E: Yeah, but you know what, it's totally different in Europe, for example, I used to live in 
Switzerland and there they're really careful with debts like it's a bad thing to be in debt. +
M: Oh, yeah, I mean it's bad to be in debt, definitely. +
E: For example, if I wanna have a credit card in Switzerland and let’s say I want to have a 
limit of, um, five hundred (500) francs that I can spend every month, I need to put in my
bank account seven hundred (700) francs before I can even spend that credit card money,
so, it's totally opposite from North America. +
M: Hehe. Well, yeah, I mean in North America it's crazy the way that people are in debt and 
it's showing now with the recession, right? +
E: Yeah, that's true. +
M: So, everyone, be sure to handle your money carefully, don't be in debt unless you 
really, really have to. +
E: Good financial advice from EnglishPod. +
M: EnglishPod – financial advising service. Hehe. +
E: Okay, everyone, thanks for listening, now remember if you have any questions or 
comments, please, visit our website at englishpod.com. +
M: Right, Erica and I are always there to answer all the questions and we really like to 
receive comments and suggestions from all our users, so, be sure to go and leave us your
comments. +
E: Okay, Marco, it's been fun. +
M: Yes, it has, but sadly we have to go now, so, until next time it's… +
E: Good bye! +
M: Bye! 
 
