= 0015
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! And welcome back to another great lesson with EnglishPod! My name 
is Marco. +
E: And I’m Erica. +
M: Erica, today we have a great intermediate lesson. +
E: That’s right, we’ve got a lesson about love… +
M: About love? +
E: And about apologizing. +
M: Uh, okay, love and apologizing. +
E: They go together 相配，相称. +

[.my2]
这两者是相辅相成的。

M: Yes, they do, if… especially if you have a girlfriend or boyfriend, right? +
E: That’s true. +
M: Hehe. Okay, so, why don’t we start by looking at our “vocabulary preview”? +

Voice: Vocabulary preview. +
E: In today’s vocabulary preview /we will learn two important words from our dialogue.
What’s the first word? +
M: Knock over 碰倒；撞倒. +
E: Knock over. +
M: Knock over. +
E: Knock over. +
M: So, that’s a really simple one, when you knock something over… +
E: You make it fall down 摔倒. +
M: Make it fall down. +
E: Yep, speaking of 说起，提到 knocking things over, this morning *I knocked over my coffee cup* all over my desk. +

[.my2]
说到碰倒东西，今天早上我就把咖啡杯碰倒了，咖啡洒得满书桌都是。

M: Yeah, I saw that. +
E: Yeah. +
M: You almost ruined our lesson plan for today. +

[.my2]
你差点把我们今天的课程计划都毁了。

E: Yes, I did. It was all over the place. 到处都是,当时一片狼藉 +

M: Hehe. Okay, let’s look at our second word – explode. +
E: Explode. +
M: Explode. +
E: Explode. +
M: So, when something explodes (v.), this is what happens. +
Sound of an explosion. （爆炸声效） +
E: Alright, that’s pretty clear. +
M: Hehe. That’s more than clear I think. So, now we’ve looked at our two vocabulary _preview words_ for this dialogue /and we are ready to listen to it /for the first time. +

[.my2]
我觉得不止是清楚，简直太直观了。现在我们已经学完了词汇预习的两个单词，接下来可以第一次听对话了。

[.small]
[options="autowidth" cols="1a"]
|===
|Header 1

|A: Whoa, whoa, what’s going on? Watch out 小心! +
B: Hey, watch where you’re going! +
A: Oh, no! I’m so sorry! Are you all right? +
B: Oh...I don’t know. +
A: I feel terrible, I really didn’t mean *to knock you
over*. My tire, just exploded, and I lost control
of my bike. Really, it was an accident. Please
accept my apologies. +

[.my2]
我的自行车轮胎突然爆了，我就控制不住车了。真的，这是个意外。

B: Just let me try to stand up. +
SONG: Why do birds suddenly appear, every time you
are near? +

[.my2]
（歌曲：为何每当你靠近，鸟儿便会突然出现？）


A: Are you okay? +
B: Oh, wait a second, you seem really familiar, I
think I know you from somewhere. +
A: Yeah, I think we have met somewhere before.
That’s right! We met at Aaron’s place last
weekend! What a coincidence! But anyway,
I’m glad to see that /you’re not too badly hurt,
and I should probably get going 离开,出发. I have a nine
o’clock meeting. +

[.my2]
对了！我们上周末在亚伦家见过！太巧了吧！不过不管怎样，看到你没受重伤我就放心了，我可能得走了，我九点有个会。

B: Ouch! My ankle 脚踝，踝关节! I think it’s broken! You can’t
just leave me like this! Are you calling an am-
bulance? +
A: Nope 不是，没有；不, I’m canceling my appointment /so that I
can stay here with you. +
SONG: Do you remember when we met? That’s the
day /I knew _you were my pet_. I wanna tell you
how much I love you.
|===


 
E: I love _happy endings_ 幸福结局. +
M: Hehe. Such a romantic dialogue. +
E: Yeah, this guy, oh my God, he is amazing! I would love to meet a guy like that. +
M: Like that? Like crashing 碰撞 into you? +
E: Maybe not LIKE that. +
M: Hehe. +
E: Okay, well, I think it’s time to, uh, look at some of the language in this dialogue. Let’s 
start with our “language takeaway”. +

Voice: Language takeaway. +
E: Today we have three important words from our dialogue /that we will learn for our
language takeaway. The first word is _familiar_. +
M: Familiar. +
E: Familiar. +
M: Familiar. +
E: This one I think is a little bit hard to explain. +
M: Yeah, so, let’s listen to some examples on _how we use familiar_. +

Voice: Example one. +
A: Norman Clark, that name sounds familiar. Where have I heard it before? +

Voice: Example two. +
B: Do you know _where we are_? +
C: I have no idea. Nothing looks familiar, I think we’re lost. +

Voice: Example three. +
D: You look really familiar. Did we go to high school together? +

E: So, when something’s familiar, you think you know it, but you’re not exactly sure. +
M: Exactly, familiar. +

E: Okay, our next word is… +
M: Place. +
E: Place. +
M: Place. +
E: Aaron’s place. +
M: Exactly, so, when we *refer to* place, we refer to house. +
E: Right, so, I can say “Hey, Marco, come over to my place for dinner tonight”. +
M: Exactly, or I could say, um, “We’re having a party at my place tonight at eight”. +
E: You might ask someone “How’s your new place?” +
M: Right. +
E: How’s your new apartment? +
M: Exactly, that’s a good one. 这个例子很贴切  +
E: Yeah. +
M: So, place. It’s a house. +

E: Right. Our final word today is… +
M: Coincidence. 巧合，同时发生 +
E: Coincidence. +
M: Coincidence. +
E: Coincidence. +
M: So, again we have some great examples for you /to understand how we use coincidence. +

Voice: Example one. +
A: I’m going to Ney York this weekend. +
B: What a coincidence? I am too. +

Voice: Example two. +
C: By coincidence, everyone in the room was named Alex. +

Voice: Example three. +
D: We met by pure coincidence. One day *we ran into 撞到,偶遇 each other* on our bikes /and we’ve been together ever since. +

[.my2]
我们是纯属偶然遇见的。那天我们骑自行车时碰巧撞见了，从那以后就一直在一起了。


E: A coincidence is something /that happens by chance, right? +
M: Right, you didn’t plan (v.) it, it just happened. +
E: Yeah, these funny little things happen all the time, I love it when these coincidences 
happen. +
M: Hehe. Yeah, they’re great. So, Erica, why don’t you tell us about a coincidence that’s 
happened to you? +
E: Well, uh, the other night I was having dinner, uh, in a restaurant and I looked up and I 
saw my old professor… +
M: Wow! +
E: From university. +
M: Hehe. +
E: I was such a coincidence, because here we are in Shanghai and I see my professor from 
Canada… +
M: Hehe. +
E: Having dinner at the table next to me. It was such a coincidence. +
M: That is a coincidence. +
E: Yeah. +
M: Or has it ever happened to you that you’re thinking of someone and that person calls 
you? +
E: That happens all the time. +
M: Hehe. That’s a coincidence. +
E: Yeah, yeah. +
M: Okay, so, now that we have learned these three language takeaway words, we can listen 
to our dialogue a second time, but this time it’s gonna be slower. +

\... +
\... +
\... +
 
E: Well, that was much clearer, wasn’t it? +
M: Yes, that was clearer and this brings us to “fluency builder”. +
Voice: Fluency builder. +
E: In today’s fluency builder we’re going to show you different ways of apologizing. It’s so 
important to be able to apologize well, um, and fluently. +
M: Exactly, and you also wanna say something different from “I’m sorry”. +
E: Right. +
M: So, that’s what we’re gonna show you today. +
E: We heard some great expressions for “I’m sorry” in the dialogue. Let’s listen now. 
Phrase 1: I’m so sorry; I feel terrible; please accept my apologies. I’m so sorry; I feel
terrible; please accept my apologies. +
E: Yeah, I feel terrible, I say this one all the time. +
M: Yeah, it’s a great way of saying “I’m sorry”. Now, also if you wanna say “I’m sorry”, you 
also wanna tell the person that you made a mistake, right? +
E: That’s true, and we did hear some wonderful expressions for “I made a mistake” in this 
dialogue.
Phrase 2: I didn’t mean to knock you over; it was an accident. I didn’t mean to knock you
over; it was an accident. +
E: Well, I didn’t mean to knock my coffee cup over this morning. +
M: Exactly, it was an accident. +
E: It was. +
M: Hehe. Not on purpose, right? +
E: Or so you think. +
M: Hehe. Okay, so, all of these phrases are really useful and great for apologizing and 
telling someone you made a mistake. +
E: Well, it’s time for us to listen to our dialogue a third time. This time it’ll be at its normal 
speed and I think you’ll be able to understand a little bit better. +

\... +
\... +
\... +

M: Great dialogue and great music, right? +
E: Wonderful music, who picked that, Marco? +
M: Of course, me. I’m a romantic type, I love romantic music. +
E: Really? +
M: Yes. +
E: Well, speaking of a romantic type, do you believe in love at first sight? +
M: I… I kind of do. +
E: Really? +
M: I… I’d like to believe it. Yeah, well… If… +
E: That surprises me. +
M: Hehe. Well, I think the first time that you see someone it impresses you someway and 
you feel attracted to that person. +
E: Really? +
M: Yeah, at least it’s the first feeling that you get that makes you want to talk to that 
person or get to know that person. +
E: I’m the exact opposite. +
M: Really? +
E: When I see somebody for the first time, my first impression is always wrong. +
M: Uh, okay. +
E: So, if I see someone and I like them at the beginning, in three weeks I’ll hate them. +
M: Hehe. +
E: And if I see someone and I hate… I don’t like them when I first meet them, I will… I’ll be 
their best friend. +
M: Uh, yeah, yeah. +
E: So, love at first sight doesn’t work for me. +
M: Hehe. I’m sure that our listeners have some stories at love at first sight. Maybe they met 
their wives or their boyfriends in this way. +
E: I’d like to hear about it. +
M: Me too, and if anybody knows the name of the songs we used, also be sure to post it 
on the discussion board. +
E: That’s right, our challenge for this week. +
M: Our challenge for this lesson. +
E: Yeah. +
M: So, that’s all for today everyone, but be sure to go to our website at englishpod.com, 
and as we said leave all your comments, your stories and see if you know the name of the
songs. +
E: Okay, well, thanks for listening everyone, and until next time… Good bye! +
M: Bye! 
 
