= 0017
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! And welcome back to another episode of EnglishPod! My name is 
Marco. +
E: And I'm Erica. +
M: And today with Erica we are getting married. +
E: Well, we're not getting married. +
M: Hehe. We're not, but our actors in the podcast are. +
E: That's right, so, we've got a lesson today about weddings. And you know what, a lot of 
the language in this lesson is about weddings and marriages and maybe you don't need to
use this language everyday, but… +
M: Learning this vocabulary will definitely help you understand or learn a lot more about 
Anglo culture. +
E: Okay, great point, Marco, I think now we can look at our “vocabulary preview”. +
Voice: Vocabulary preview. +
E: So, two simple words in this vocabulary preview; the first one is groom. +
M: Groom. +
E: Groom. +
M: Groom. +
E: So, who is the groom? +
M: He's the man, the man that's getting married. +
E: Okay, and our second word is… +
M: Bride. +
E: Bride. +
M: Bride. +
E: And obviously the bride is… +
M: The woman getting married. +
E: Perfect. +
M: Hehe. +
E: Now we have our bride and our groom, so, it's time to listen to our dialogue the first 
time. +
A: I can’t believe that Anthony is finally getting mar- 
ried! +
B: Yeah well it’s about time! He’s been living with his 
parents for 40 years! +
A: Don’t be mean. Look here come the bridesmaids! 
Their dresses look beautiful! +
B: Who are those kids walking down the aisle? +
A: That’s the flower girl and the ring bearer. I’m 
pretty sure they’re the groom’s niece and nephew.
Oh, they look so cute! +
B: I just hope the priest makes it quick. I’m starving. 
I hope the food’s good at the reception. +
A: That’s all you ever think about, food! Oh, I think 
the bride’s coming now! She looks gorgeous.
Wait, what’s she doing? Where’s she going? +
B: Oh great! Does this mean that the reception is 
canceled?
 
E: Oh, Marco, that sounds sad. +
M: Yeah, I know the reception is cancelled now. +
E: Marco! +
M: Well… +
E: They're not getting married! +
M: Uh, well, I mean… the best part is when you go and eat and drink at a reception. +
E: Okay. Well, there's some great language in this dialogue and now let's look at our 
“language takeaway”. +
Voice: Language takeaway. +
M: Great, our first word on the language takeaway today is it’s about time. +
E: It's about time. +
M: It's about time. +
E: It's about time. +
M: So, now we are going to listen to some examples on how we use this great phrase. +
Voice: Example one. +
A: Dinners’ ready. +
B: It’s about time! I’m starving! +
Voice: Example two. +
C: Guess what? I finally got a job. +
D: It’s about time! You’ve been unemployed for two years! +
Voice: Example three. +
E: We’re almost there. Just a couple more minutes. +
F: It’s about time. We’ve been driving for twelve hours. +
E: So, this phrase means 'finally'. +
M: Finally! At last. +
E: We've been waiting a long time for this. +
M: Exactly. +
E: Okay, so, it's about time. +
M: Great, let's take a look at our second word now – aisle. +
E: Aisle. +
M: A-I-S-L-E. +
E: Aisle. +
M: Aisle. It's a tricky word, it sounds like the contraction of 'I will'. +
E: Yeah, but it's spelled so strangely. +
M: Right, we don't pronounce the S, the S is silent, it's… +
E: That's true. +
M: Ai-le. +
E: So, what is an aisle? +
M: In a big room where you have a lot chairs that space in the middle that allows people to 
walk through, that's the aisle. +
E: So, the aisle is the part where you walk. +
M: Yes. +
E: In a big room. +
M: In a big room, wh… +
E: With many chairs. +
M: With many chairs. Hehe. +
E: Okay. +
M: So, in the church… +
E: The bride and groom… +
M: Walk down the aisle. +
E: Exactly. +
M: Great. +
E: Let's move to our third word… +
M: Bridesmaid. +
E: Bridesmaid. +
M: Bridesmaid. +
E: So, who are the bridesmaids? Or wait, maybe you ask me that. +
M: Yeah, cause I… I… we don't get bridesmaids. +
E: Okay, so, the bridesmaids are the women who are friends of the bride who stand next to 
her when she's getting married. Usually, they're her best friends. +
M: Right, okay. Okay, so, we have our bridesmaids, now we have our flower girl. +
E: Flower girl. +
M: Flower girl. +
E: Again, I'll explain this one. +
M: Please, please. +
E: The flower girl is the cute little girl who walks down the aisle and who throws flowers. +
M: That's the flower girl. And with the flower girl we have our ring bearer. +
E: Ring bearer. +
M: Ring bearer. +
E: So, the ring bearer is the cute little boy who walks down the aisle carrying the… +
M: Rings. +
E: Yep. +
M: Okay, so, a lot of useful vocabulary for a wedding ceremony. +
E: That's true. +
M: Now, let's look at our last word – gorgeous. +
E: Gorgeous. +
M: Gorgeous. +
E: Gorgeous means beautiful. +
M: Very beautiful. +
E: Yeah, i… you know, beautiful you can only use with a woman. +
M: Uhu. +
E: Can you use gorgeous with a woman or with a man? +
M: Yes, gorgeous is unisex. +
E: So, both men and women are gorgeous. +
M: Right, you can say “Oh, that girl is gorgeous”. +
E: That guy is gorgeous. +
M: Right, or you can say even “This house is gorgeous”. +
E: Okay, so, men, women, objects. +
M: Yes, yes. +
E: Alright, well, we've learned some really interesting vocabulary that will help us to 
understand an Anglo wedding, so, why don't we listen to the dialogue slow down? +
A: I can’t believe that Anthony is finally getting mar- 
ried! +
B: Yeah well it’s about time! He’s been living with his 
parents for 40 years! +
A: Don’t be mean. Look here come the bridesmaids! 
Their dresses look beautiful! +
B: Who are those kids walking down the aisle? +
A: That’s the flower girl and the ring bearer. I’m 
pretty sure they’re the groom’s niece and nephew.
Oh, they look so cute! +
B: I just hope the priest makes it quick. I’m starving. 
I hope the food’s good at the reception. +
A: That’s all you ever think about, food! Oh, I think 
the bride’s coming now! She looks gorgeous.
Wait, what’s she doing? Where’s she going? +
B: Oh great! Does this mean that the reception is 
canceled?
 
M: Now, in this dialogue we have a word that many students often make mistakes on. +
E: So, this is a word that causes a lot of problems. +
M: Yes, the word marry. +
E: Marry. +
M: Marry, right? So, we are going to listen now to some common mistakes on how English 
learners use this word. +
E: Right, so, these are wrong examples. +
Voice: Example one. +
A: Honey, let’s marry. +
Voice: Example two. +
B: We married four years ago. +
Voice: Example three. +
C: When I marry I wanna huge wedding. +
E: These are great examples of mistakes students make with the word marry. They're 
missing a word. Let's listen to these right examples to see what word is missing. +
Voice: Example one. +
A: Honey, let’s get married. +
Voice: Example two. +
B: We got married four years ago. +
Voice: Example three. +
C: When I get married I wanna huge wedding. +
M: Great, so, we can see that when we use the word marry, we say to get married. +
E: Exactly right! Get married. +
M: To get married, right? +
E: Okay, don't forget that. +
M: Yes, get married. I will get married. +
E: We got married. +
M: Right, so, now you know exactly how to use this word, we are ready to listen to our 
dialogue again for a third time and this time it's gonna be at a normal speed. +
A: I can’t believe that Anthony is finally getting mar- 
ried! +
B: Yeah well it’s about time! He’s been living with his 
parents for 40 years! +
A: Don’t be mean. Look here come the bridesmaids! 
Their dresses look beautiful! +
B: Who are those kids walking down the aisle? +
A: That’s the flower girl and the ring bearer. I’m 
pretty sure they’re the groom’s niece and nephew.
Oh, they look so cute! +
B: I just hope the priest makes it quick. I’m starving. 
I hope the food’s good at the reception. +
A: That’s all you ever think about, food! Oh, I think 
the bride’s coming now! She looks gorgeous.
Wait, what’s she doing? Where’s she going? +
B: Oh great! Does this mean that the reception is 
canceled?
 
M: Okay, well, I'm gonna be honest with you, I don't know too much about marriages, 
because, first of all, I'm not married and I've never really been too many marriages, so,
Erica, some questions for you. +
E: Okay. +
M: What are these bridesmaids do… I mean… What are they… what are they about? +
E: What do the bridesmaids do? +
M: Yeah, what are they… what are they doing there? +
E: Well, like I said earlier, the bridesmaids are the friends of the bride, but the most 
important people besides the bride and groom are the best man and the maid of honor. +
M: Okay, and what do they do there, in the ceremony? +
E: Well, what they do is they sign the marriage license. +
M: Okay, so, they're like witnesses. +
E: Exactly. +
M: Okay, so, but wait a minute, they sign the marriage license there in the church? +
E: Yeah, of course, right inside the church you sign the marriage license. +
M: Wow, that's strange, because from what I know, in other countries usually you will 
sign the marriage license before the ceremony. +
E: So, you get married twice. +
M: Yeah, you have like the civil marriage and then you have like the church wedding or 
whatever. +
E: That's so complicated. +
M: Hehe. Well, yeah, I mean the church wedding is just a ceremony; it's not really anything 
official. +
E: Oh, in Canada it's the official part as well. +
M: I guess maybe it's just more efficient. +
E: Maybe. +
M: Hehe. +
E: Well, this is a really fascinating, a really interesting subject, isn't it? +
M: Yeah, because there're so many countries that have different marriage ceremonies. I 
know that marriages in India last around seven days. +
E: Yeah, yeah. I wanna know more about how our users get married in their country[s]. +
M: Yeah, so, please go to our website at englishpod.com and tell us how you get married 
in your countries. +
E: Yeah, I can’t wait to hear your stories. +
M: Yeah, it should be interesting, right? +
E: Okay, well, everyone thanks for listening and until next time… Good bye! +
M: Bye! 
 
