= 0038
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And today we’re bringing you another great lesson for all of you, who are interested in 
shopping. +
E: Especially those of you, who are interested in shopping for a car. +
M: A car. +
E: Uhu. +
M: Exactly. So, we’re gonna give you some great language about describing a car or 
characteristics of a car. +
E: Yeah. +
M: And also some really interesting language for shopping. +
E: Yes, especially buying something really big and expensive. +
M: Yeah, like a car. +
E: Yeah. +
M: So, before we listen to our dialogue let’s take a look at “vocabulary preview”. +
Voice: Vocabulary preview. +
M: On vocabulary preview today we’re brining two words. The first one is vehicle. +
E: Vehicle. +
M: Vehicle. +
E: Vehicle. +
M: So, again a vehicle is a machine, right? +
E: Right, a machine that carries people from one place to another. +
M: So, it’s important to say that a vehicle could be an airplane… +
E: A car. +
M: A car. +
E: A boat. +
M: Boat. +
E: Even a bicycle. +
M: Right. +
E: Yeah. +
M: That’s a vehicle. Our second word is sedan. +
E: Sedan. +
M: Sedan. +
E: Sedan. +
M: So, a sedan is a type of car. +
E: Exactly. It… it’s a type of car with four doors that can fit five people inside. +
M: So, to make it more clear, most taxies are sedans. +
E: Exactly. +
M: Right? +
E: Yeah. +
M: They have four doors. +
E: Yeah. +
M: Five people can fit in there… +
E: Yeah. +
M: Including the driver. Except taxies in Mexico. +
E: They’re not sedans? +
M: They’re little Beetles. +
E: Oh. +
M: The Volkswagen Beetles. +
E: Okay. +
M: So, those are not sedans. But, yeah, most, uh, countries have sedans as taxies. +
E: Yeah. +
M: To give you some examples, like a Toyota Corolla or a Toyota Camry is a sedan. +
E: Yeah, yeah. Maybe like, uh, a Volkswagen Getta is that a…. +
M: A Jetta, yeah… +
E: Yeah. +
M: A Jetta is the sedan. +
E: Yeah. +
M: Now, we could listen to our dialogue and it’s gonna be at a normal speed, the first time, 
but you don’t have to worry about it. +
E: We’ll come back and teach you some of the important words from the dialogue. +
A: Hi there, can I help you folks? +
B: I’m just browsing; seeing what’s on the lot. My 
daughter wants a car for her birthday, you know
how it is. +
C: Dad! I’m sixteen already and I’m, like, the only 
one at school who doesn’t have a car! +
A: She is right, you know. Kids these days all have 
cars. Let me show you something we just got in:
a 1996 sedan. Excellent gas mileage, it has dual
airbags and anti lock brakes; a perfect vehicle for
a young driver. +
C: Dad, I love it! It’s awesome! Can we get this one 
please? +
B: I see... What can you tell me about this one? +
A: Oh, that’s just an old World War Two tank that we 
use for TV commercials. Now about this sedan... +
B: Whoa, whoa wait a minute. Tell me more about 
this tank. +
A: Well, Sir, if you are looking for quality and safety 
then look no further! Three inches of reinforced
steel protect your daughter from short range mis-
sile attacks. +
B: Does the sedan protect her from missile attacks? +
A: It does not. +
B: Well, I don’t know. Let me sleep on it. +
A: Did I mention the tank is a tank? +
B: I’ll take it! +
C: Dad! 
 
M: I think she’s really lucky. She’s… +
E: Really? +
M: She’s getting a tank to go to school. How awesome is that? +
E: Uh, I would be so embarrassed if I had to drive to school on a tank. +
M: That’s like the coolest car. +
E: Oh, you’re such a boy. +
M: Hehe. Alright, a surprising ending to, uh, relatively easy shopping day. +
E: Yeah. +
M: Uh, let’s take a look at some… language that we saw in our dialogue on “language 
takeaway”. +
Voice: Language takeaway. +
E: We have four words for you today. The first one is gas mileage. +
M: Gas mileage. +
E: Gas mileage. +
M: Gas mileage. So, gas mileage is how many miles you can travel on a gallon or liter of 
gasoline. +
E: Well, you know, it’s interesting in some English speaking countries like Australia, New 
Zeeland, Canada, we use kilometers… +
M: Right. +
E: To measure distance. But we still talk about gas mileage. +
M: Uh. +
E: Yeah. +
M: I guess you can’t say gas kilomiliage. +
E: No. +
M: Or… or some like that. But, yeah, it’s… yeah, basically, how many kilometers or how 
many miles you can travel on a tank or on a liter or gallon of gas. +
E: Exactly. +
M: Okay. +
E: The next word is airbags. +
M: Airbags. +
E: Airbags. +
M: Airbags. +
E: These are like big bags of air that fill up and come out of the car when there’s a crash. +
M: Right, so, that way you don’t hit your head against… +
E: Yeah. +
M: The steering wheel or… +
E: Yeah. +
M: Something like that. +
E: So, they protect you. +
M: Right, I’ve heard that Volvo has like eighteen airbags now in their cars. +
E: They are very safe cars, you know. +
M: Hehe. Like a big balloon. +
E: Aha. +
M: Okay, our third word today is brakes. +
E: Brakes. +
M: Brakes. +
E: Brakes. So, what are brakes? +
M: Brakes are little… What are breaks? Breaks are what make your car stop. +
E: Okay, so, that the little machines maybe that stop your car. +
M: Yeah, they’re on the wheels. +
E: Yeah. +
M: They make your car stop. +
E: Aha. +
M: You have brakes on your bike. +
E: Yes. +
M: On your car, etcetera. +
E: Uhu. +
M: Our last word today on language takeaway – reinforced. +
E: Reinforced. +
M: Reinforced. +
E: Reinforced. +
M: So, we have some examples of how we use reinforced, because it’s a little bit weird. +
E: Yeah, these will help you understand the meaning. +
Voice: Example one. +
A: So, I reinforced all the walls; there’s no way they’re gonna fall down. +
Voice: Example two. +
B: This plastic is reinforced with the glass, so it’s both light and strong. +
M: So, basically, anything that’s reinforced is made stronger. +
E: Perfect. +
M: Reinforced steel… +
E: Yep. +
M: Reinforced table. +
E: Aha. +
M: Anything. Okay. Great, so now we could listen to our dialogue again. You can practice all 
these words that we just talked about and we’ll come back shortly. +
A: Hi there, can I help you folks? +
B: I’m just browsing; seeing what’s on the lot. My 
daughter wants a car for her birthday, you know
how it is. +
C: Dad! I’m sixteen already and I’m, like, the only 
one at school who doesn’t have a car! +
A: She is right, you know. Kids these days all have 
cars. Let me show you something we just got in:
a 1996 sedan. Excellent gas mileage, it has dual
airbags and anti lock brakes; a perfect vehicle for
a young driver. +
C: Dad, I love it! It’s awesome! Can we get this one 
please? +
B: I see... What can you tell me about this one? +
A: Oh, that’s just an old World War Two tank that we 
use for TV commercials. Now about this sedan... +
B: Whoa, whoa wait a minute. Tell me more about 
this tank. +
A: Well, Sir, if you are looking for quality and safety 
then look no further! Three inches of reinforced
steel protect your daughter from short range mis-
sile attacks. +
B: Does the sedan protect her from missile attacks? +
A: It does not. +
B: Well, I don’t know. Let me sleep on it. +
A: Did I mention the tank is a tank? +
B: I’ll take it! +
C: Dad! 
 
E: So, we have a couple of interesting phrases to talk about shopping. +
M: Right. +
E: Let’s look at these in “fluency builder”. +
Voice: Fluency builder. +
M: The first one is I’m just browsing. +
E: I’m just browsing. +
M: I’m just browsing. +
E: I’m just browsing. +
M: This is a really useful phrase, because usually salespeople will come up to you and ask 
you “can I help you?” or… +
E: Yeah. +
M: “Are you interested in something?” +
E: Yeah. +
M: And you’re just looking, so… +
E: Yeah, you maybe… you don’t really wanna buy today. +
M: Right. +
E: Yeah. +
M: So, you’re just “uh, I’m just browsing”. +
E: Uhu. +
M: So, then they’ll just leave you alone and… +
E: Yeah, they won’t bother you as much. +
M: Yeah, it’s a good, good phrase. +
E: Another good phrase. +
M: Sleep on it. +
E: Sleep on it. +
M: Sleep on it. +
E: Sleep on it. +
M: So, we have some examples of how we use sleep on it. +
Voice: Example one. +
A: I don’t know if we should buy that house. It’s perfect for us, but it’s so expensive. +
B: Let’s sleep on it. +
Voice: Example two. +
C: Why don’t you sleep on it and tell me tomorrow? +
Voice: Example three. +
D: This is a bit more than what I can afford; let me sleep on it. +
M: To sleep on it means to… +
E: Like to think about it overnight. +
M: To think about it, right? +
E: Yeah. +
M: So, maybe you wanna buy this really expensive car. +
E: But you need to think about it. +
M: Right. +
E: So, you’ll sleep on it. +
M: So… yeah. You go home, sleep on it, think about it twice and then make a decision. +
E: Exactly. +
M: Okay, great words and great dialogue, so… +
E: Yeah, I love this dialogue. +
M: Yeah, it was… it’s kind of funny. So, we could listen to it again and then we’ll come back 
and talk a little bit about it. +
A: Hi there, can I help you folks? +
B: I’m just browsing; seeing what’s on the lot. My 
daughter wants a car for her birthday, you know
how it is. +
C: Dad! I’m sixteen already and I’m, like, the only 
one at school who doesn’t have a car! +
A: She is right, you know. Kids these days all have 
cars. Let me show you something we just got in:
a 1996 sedan. Excellent gas mileage, it has dual
airbags and anti lock brakes; a perfect vehicle for
a young driver. +
C: Dad, I love it! It’s awesome! Can we get this one 
please? +
B: I see... What can you tell me about this one? +
A: Oh, that’s just an old World War Two tank that we 
use for TV commercials. Now about this sedan... +
B: Whoa, whoa wait a minute. Tell me more about 
this tank. +
A: Well, Sir, if you are looking for quality and safety 
then look no further! Three inches of reinforced
steel protect your daughter from short range mis-
sile attacks. +
B: Does the sedan protect her from missile attacks? +
A: It does not. +
B: Well, I don’t know. Let me sleep on it. +
A: Did I mention the tank is a tank? +
B: I’ll take it! +
C: Dad! 
 
E: So, Marco, have you ever driven a tank? +
M: Hehe. Well… +
E: I… I mean know you were in the army, so… +
M: Yeah, yeah. Um, yeah, actually I did… I did drive, uh, a tank before. +
E: Really? +
M: A really… yeah, a really old one… +
E: Really? +
M: Kind of like a World War Two type tank. But, yeah, they’re really fun and interesting. You 
have… it’s not like driving a normal car. You have pedals and you have… +
E: So, there’s no steering wheel? +
M: No, no, no. You have, um, levers… +
E: Yeah. +
M: And, uh… what many people don’t know is that actually tanks are… manual transmission, 
so you have to change gears. +
E: Oh, really? +
M: And it’s really hard to change gears on those things. +
E: And what’s the gas mileage like on a tank? +
M: Hehe. I don’t know, maybe like five miles per gallon, well… +
E: Okay. +
M: They run on diesel… +
E: Aha. +
M: Witch is a different type of fuel, right? +
E: Yep. Okay, well, very cool. I never knew that my podcast partner had driven a tank. 
That’s pretty awesome. +
M: Yeah, well, it was… it was fun, definitely and… I hope I get to do it again some day. +
E: Alright. Well, uh, guys, have you ever driven a tank? +
M: Or a submarine or any type of, uh, armor vehicle. +
E: Yeah, tell us about it at our website englishpod.com. +
M: Right, we’ll be there to answer all your questions. I’ll also be there to maybe post some 
more crazy stories. +
E: Or some pictures of the tank or something. +
M: Yeah, maybe. +
E: Yeah. +
M: Alright guys, we’ll see you there… until then it’s… +
E: Good bye! +
M: Bye! 
 
