= 0155
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! And welcome back to another lesson here atEnglishPod! My name 
is Marco. +
C: And my name is Catherine. So, Marco, what are we talking about today? +
M: Today we’re talking about a very interesting topic. You’ve probably seen it on every TV 
show or American movie and it’s a bachelor party. +
C: Oh-oh. +
M: Yeah. +
C: Hehe. I’ve heard bad things. +
M: Oh, bad things about a bachelors party. Well, they can be, uh, fun, but at times they can 
be a little bit too excessive, too much. But before we get started on the dialogue, why don’t
we take a look at “vocabulary preview”? +
Voice: Vocabulary preview. +
C: Well, the first word we’ve got here is the topic of today, this is thebachelor party, so 
what is a bachelor exactly? +
M: Right, well, a bachelor is a person who is not married, single person, a single guy 
specifically, right? +
C: Alright, so it’s a man. +
M: Man… +
C: Before he’s married. +
M: Right. So for women you would say a bachelorette. +
C: Okay, [a] bachelor is a guy and a bachelorette is a girl. And so, we don’t really say 
“bachelorette”, except when we’re talking about this party. +
M: Right. So a bachelor party is a party that a guy has the day before he’s married or 
maybe two or three days before he actually gets married. So it’s a night where all his
friends get together, they go out, they have some drinks, they have some fun and, uh, it’s
just like the last extreme fun they will have… he will have before he gets married. +
C: Alright, and so, it’s all his guy friends. +
M: All his guy friends, only guys, no girls. +
C: And a bachelorette party is only girls and it’s when a girl’s friends take her out before she 
gets married to celebrate her last night or two of being unmarried. +
M: Right, exactly. So, um, not only guy’s parties can get a little bit crazy, but girl’s, uh, ba… 
bachelorette parties can also get kind of crazy, right? +
C: That’s true, so before we start talking about what exactly goes on at some of these 
parties, let’s take a listen to today’s dialogue and hear what happens to our main
characters. +
A: Hi honey! You’ll never guess what! My friends 
Julie and Alex are getting married! +
B: Wow that’s great news! They’re a great couple! +
A: I know! Anyways I just talked to Alex’s best man 
and he is organizing the bachelor party It’s gonna
be gonna be so much fun! All the groomsmen are
thinking up all the wacky and crazythings we are
going to do that night. +
B: You aren’t going to a strip club are you? I don’t 
want you getting a lap dance from some stripper
with the excuse that it’s your friends party. +
A: Aw come on! It’s just some innocent fun! You 
know how these things are! We are gonna play
drinking games, get him some gag gifts and just
have a good time.Nothing too over the top . +
B: Well, I don’t know. +
A: Come on! If one of your friends was getting mar- 
ried I wouldn’t mind you going to her bachelorette
party! +
B: Good,because my friend Wendy is getting mar- 
ried and I’m organizing her party! +
A: What! +
M: Alright, great, so apparently both of them have parties to go to, but I don’t think the guy 
was too happy about it. +
C: I don’t think so either and that’s the funny thing. I think a lot of girls are like: oh, well, 
my husband to be… he wants to have a party, it’s okay. But the minute the girl wants to
have the party the guy is like: uh-uh, no way. +
M: Yeah. Hehe. That’s true. I guess, uh… but, uh, we can talk a little bit more about this 
towards the end. Before we start on… on this really interesting topic, why don’t we take a
look at some of the language on language takeaway. +
Voice: Language takeaway. +
C: Well, Marco, the first few words are actually more wedding terms, than… than bachelor 
party terms. The first one is best man. +
M: Right, the best man. So the best man is… who is he exactly? +
C: He’s usually the groom’s best friend. So the groom is the man getting married. +
M: Uhu. +
C: And his best friend has the position of best men, so he has some special things to do 
with the wedding. He has to make a speech, for example. +
M: Aha. +
C: And he has to stand next to his friend when the friend gets married. +
M: Right. +
C: And, uh, it’s just a very special position of honor that the best friend has in his friend’s 
wedding. +
M: Okay, and, uh, among those responsibilities the best man is usually the one that has to 
organize the bachelor party, right? +
C: Exactly. +
M: Okay, so best man. And, well, the rest of the groom’s friends are also present at the 
wedding and they are called the groomsmen. +
C: Alright, so groom… +
M: Uhu. +
C: Groomsmen. And so, usually these are maybe three to five guys… +
M: Uhu. +
C: Three to five men, who are friends of the groom or brother of the bride, it depends on 
the wedding, and they stand with the man, um, when he gets married and so, they kind of
have a lot of responsibilities as well. +
M: Okay, and the groomsmen usually are also present at the bachelor party. +
C: Exactly. +
M: Alright. Now moving on to a bit more colorful, uh, language, um, we have a place here, 
a strip club. +
C: Okay, so sometimes… you see this in movies oftentimes… +
M: Uhu. +
C: Or, for example, the TV show, The Sopranos, this is often a place where Tony Soprano 
goes. +
M: Hehe. +
C: A strip club is a club, it’s like a bar, it’s open most of the day and night, um, where 
there’re women who take their clothes off for money. +
M: Alright, so you have the verb – to strip, right? +
C: Uhu. +
M: A strip club. So the verb “to strip” means to… to take off or… or leave without 
something. +
C: Right, so… so you can strip off your clothes. +
M: So it’s usually used with clothes, right? To take off clothes, to strip. So you have a strip 
club and in the strip club you have the, as you mentioned, the girls that are dancing and
taking off their clothes. Um, they are called strippers. +
C: Okay, so stripper is a person who takes off their clothes as their job. +
M: Uhu. +
C: And you can have male strippers or female strippers. +
M: True. +
C: So, usually, just saying “stripper” is a woman. And a male stripperis actually a guy. +
M: Okay, so you have this club that’s very common in many countries and, well, the 
strippers are dancing. And now they also talked about getting a lap dance. +
C: Okay, now, this is getting a little bit, uh… a little dirty. Lap is a… well, it’s not really a 
part of your body, but when you sit down in a chair, your lap is the tops of your legs, so you
can, uh… you know, you can hold something in your lap, like your backpack… +
M: Or maybe, for example, if you have a child that’s three or four years old, you would seat 
him on your lap, right? On your legs while you’re sitting down maybe in subway. +
C: Right, or a laptop computer is a kind of computer you can hold on… +
M: On your lap. +
C: On your lap. +
M: So a lap dance is when, ah, one of the female strippers comes and kind of dances on 
your lap. +
C: Exactly, and so, it’s a sexy dance. You pay for it extra and it’s something that is very 
popular with, uh, young men and people who… you know, these grooms and groomsmen
before the groom gets married. +
M: Right, alright. And moving on, we have the last word for today –gag gifts. +
C: Alright, gag gifts are joke gifts, they’re jo… they’re… they’re meant to be funny, they’re 
not meant to be serious. +
M: Right. +
C: And they’re very popular at these kinds of bachelor parties and bachelorette parties. Um, 
one kind of gag gift is just very silly, it’s like a whoopee cushion. +
M: Alright. +
C: You know, it’s like a… it’s like a balloon you put on someone’s seat and when they sit 
down, phrrrr… +
M: Alright. +
C: It makes a farting sound. +
M: Right. So those are gag gifts. Anything that’s kind of for… to joke around. It’s not really 
useful, it’s not like giving somebody a t-shirt, right? +
C: Right, or a gi… a bis… a gift card is a nice gift, it’s not… it’s not a gag gift. +
M: Right, so there’re really… there’re a lot of different types of gag gifts and actually some 
of them are… are pretty good and funny like, uh… you know, like spicy chewing gum or… or
the electric shocker. +
C: Oh, yeah. +
M: When you shake somebody’s hand. +
C: That’s really funny, zzzz… +
M: Hehe. Alright, so we’ve taken a look at a lot of words on language takeaway, so let’s 
listen to this dialogue again and we’ll be right back with “fluency builder”. +
A: Hi honey! You’ll never guess what! My friends 
Julie and Alex are getting married! +
B: Wow that’s great news! They’re a great couple! +
A: I know! Anyways I just talked to Alex’s best man 
and he is organizing the bachelor party It’s gonna
be gonna be so much fun! All the groomsmen are
thinking up all the wacky and crazythings we are
going to do that night. +
B: You aren’t going to a strip club are you? I don’t 
want you getting a lap dance from some stripper
with the excuse that it’s your friends party. +
A: Aw come on! It’s just some innocent fun! You 
know how these things are! We are gonna play
drinking games, get him some gag gifts and just
have a good time.Nothing too over the top . +
B: Well, I don’t know. +
A: Come on! If one of your friends was getting mar- 
ried I wouldn’t mind you going to her bachelorette
party! +
B: Good,because my friend Wendy is getting mar- 
ried and I’m organizing her party! +
A: What! +
M: Alright, we’re back, so now let’s look at some of the phrases that were used in this 
dialogue on “fluency builder”. +
Voice: Fluency builder. +
C: Alright, so at the beginning of this dialogue we meet this couple, these… +
M: Aha. +
C: These man… man and women. And… and the guy says: hey, honey,you’ll never guess 
what. +
M: Alright. +
C: Okay, my friends are getting married. So what does this mean, my…you’ll never guess 
what? +
M: It’s just a phrase that you would use to give really, really important or exciting news, it’s +
like: guess what! +
C: Okay, so you’ll never guess what happened to me. +
M: Right. +
C: I won the lottery. +
M: Right, it’s so amazing or it’s so uncommon or unusual that you would probably never 
guess that person won the lottery. +
C: Okay, so you’ll never guess what. +
M: Right. “You’ll never guess what” or you can say: guess what! I won the lottery. +
C: Uhu, okay. +
M: Alright, and our second phrase: you know how these things are. +
C: Okay, so this is a phrase that people often use when they want to remind someone that, 
uh, this is [a] tradition or this is a habit. +
M: Common. +
C: It’s a common thing. Um, and so, oftentimes when like people are having problems at 
work and they say: ugh, gosh, this person’s just not listening to me; someone to… to help
them out will say, you know: you know how these things are. +
M: Yeah. +
C: You know, it takes some time to resolve a problem. +
M: Uhu. +
C: Um, or you could say, you know: ugh, gosh, this is gonna be a horrible party, I don’t 
want you guys to go to a strip club, it’s so dirty. +
M: Right. +
C: And you’d say: well, you know how these things are… +
M: Right. +
C: It’s [a] tradition. +
M: You have to do it. Hehe. +
C: You have to do it. +
M: Right, so this is what he meant, right? You know how these things are. It’s like: I don’t 
really have a choice, it’s a tradition, this is what guys do when they’re gonna get married,
so we have to do it. +
C: It’s almost like saying: don’t worry about it, there’s really… +
M: Nothing to worry about. +
C: There’s nothing to worry about. +
M: Alright. And our last phrase… and our last phrase is something that we never want to 
happen, something to be over the top. +
C: Well, it’s not necessarily a bad thing, okay, so… +
M: Right. +
C: We could say that, um, it was really ridiculous party, it was really over the top. They had 
a clown and they had people dressed up like Star Trek characters. You know, something
that is more than normal, it’s almost silly. +
M: Uhu. +
C: The way that it’s all just kind of crazy and… yeah, it’s too much in every way. +
M: Right, so it can be something bad, like for example, someone’s behavior was over the 
top. It was too much, it was too intense. +
C: Or like: oh, my gosh, did you see her coat? It’s really over the top, it’s like purple 
with sprinkles on it. +
M: Hehe. Right, so it can be used in different ways, but it usually means it’s excessive, it’s 
too much. +
C: Exactly. +
M: Alright, so some interesting phrases on this occasion as well. Let’s listen to our dialogue 
for the last time and we’ll be back. +
A: Hi honey! You’ll never guess what! My friends 
Julie and Alex are getting married! +
B: Wow that’s great news! They’re a great couple! +
A: I know! Anyways I just talked to Alex’s best man 
and he is organizing the bachelor party It’s gonna
be gonna be so much fun! All the groomsmen are
thinking up all the wacky and crazythings we are
going to do that night. +
B: You aren’t going to a strip club are you? I don’t 
want you getting a lap dance from some stripper
with the excuse that it’s your friends party. +
A: Aw come on! It’s just some innocent fun! You 
know how these things are! We are gonna play
drinking games, get him some gag gifts and just
have a good time.Nothing too over the top . +
B: Well, I don’t know. +
A: Come on! If one of your friends was getting mar- 
ried I wouldn’t mind you going to her bachelorette
party! +
B: Good,because my friend Wendy is getting mar- 
ried and I’m organizing her party! +
A: What! +
M: Alright, we’re back, so bachelor and bachelorette parties. Have you even been to a 
bachelorette party? +
C: I have not yet, but, uh, one of my closest friends is getting married in a couple of weeks. 
And so, I will be attending and helping organize a bachelorette party. +
M: Wow! So do you have anything in mind? +
C: Mm, nothing I can talk about, it’s a surp… +
M: Hehe. +
C: These things are meant to be surprises oftentimes… +
M: Sure, yeah. +
C: So I don’t wanna spoil it, but I will tell you that, um, my boyfriend just organized a 
bachelor party for his best friend. He was the best man in the… in the wedding. +
M: Uh, okay. +
C: And it was very crazy. +
M: Oh, really? +
C: Uhu. +
M: Did they also go to Vegas and do some of these things that we saw in the dialogue? +
C: They didn’t go to Vegas, but they did some of the things we heard about in today’s 
dialogue. They went to a strip club, they got lap dances, they drank a lot, it was very over
the top. +
M: It… Hehe. And I think this is something that, um, most of our listeners probably have 
seen in TV shows or in movies or in different type of exposure of American culture, which
is… it’s actually very, very common in Canada, um, the… the United Sates. I’m not really
sure about Europe or… +
C: England it is too, my… +
M: Really? +
C: My friend said that he… his friend was getting married and they all went to Portugal for a 
week… +
M: Wow. +
C: Uh, to have a bachelor party and I heard something about mud wrestling. +
M: Hehe. Wow, well, I guess it’s different in every country and this is the interesting part. 
We wanna know how these things are in your country. Do you have any traditions or any
fun stuff that you do before the wedding? Maybe after… I don’t know… +
C: What about Ecuador? +
M: Um, we usually… we don’t really have strip clubs actually. +
C: Hehe. +
M: So, uh, it’s com… +
C: It makes it easy. +
M: Yeah, so, um, we usually just do what we do every night, just go out with friends… +
C: Drink and dance. +
M: Drink and dance, play the guitar or, um… yeah, maybe some gag gifts or 
some prank that we pull on… on the groom, but nothing too over the top. So, yeah, we’re
really interested in… in knowing how it is in your country, so come to englishpod.com,
leave your questions, comments. And, uh, we’ll see you guys next time. +
C: Until then… bye everyone! +
M: Bye-bye! 

  
