= 0166
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello English learners, welcome back to EnglishPod.
My name is Marco.
My name is Catherine and today we have an intermediate level lesson talking about appearances.
That's right.
We are going to change or somebody wants to change their appearance and they're going to have surgery.
Well before we get started, let's look at what kind of surgery they're having in today's vocabulary preview.
Alright, so today we're going to be talking about plastic surgery specifically.
Plastic surgery.
So why plastic?
I have no idea.
I don't either, no.
Well basically plastic surgery is surgery for your appearance, right?
It's not really for health reasons.
That's right and sometimes they add things to you, sometimes they take things away but they're not for your health.
They're not for your heart or your lungs.
It's for your appearance.
And also called cosmetic surgery, right?
That's right and we'll be hearing that later but cosmetic means having to do with your appearance like cosmetics.
Right, exactly.
Alright, so we're going to be talking about this.
Let's listen to our dialogue for the first time and we'll be back.
What are you doing?
Look at me, I look so old.
I look as if I were 30.
Come on, 30.
Come on, stop being so vain.
You look great.
You are beautiful.
Yes I am but I think it's time for some plastic surgery.
I'm tired of these wrinkles and sagging skin, see?
I don't see any wrinkles or sagging skin.
You're 25, stop being ridiculous.
Besides I think that people who get Botox, have facelifts or tummy tucks look weird.
It doesn't look natural.
Whatever, I think I'm going to get liposuction and a nose job and some breast implants for you.
I think you need to get brain surgery.
I honestly don't think you need cosmetic surgery.
You look amazing.
I thought you were my friend and would support me on this.
I just want to feel better about myself and feel more attractive.
You don't need plastic surgery to do that.
You're fine the way you are and you have guys drooling all over you.
Plus plastic surgery hurts.
Really?
Yeah.
When I got my nose job I was black and blue for a week.
I'm not a fan of language takeaway.
Language takeaway.
Okay, well this first one might be the reason for surgery, not necessarily a kind of surgery.
If someone is vain.
Okay, so if a person is vain, this is an adjective.
That means that they are very, they care too much about their appearance, right?
Right, and they care so much that they only care about themselves.
So, do I look good?
I love my face, my eyes, I look so good.
So, a person who is vain thinks very highly of themselves.
Okay, very good.
And well, this person I think wanted to get surgery as well because she said she had wrinkles.
Okay, wrinkles are little lines on your face.
So, maybe on your forehead or next to your mouth.
And generally when we get older people get more and more of these.
Well, you would say you have, even you have wrinkly skin when you're in the bathtub for too long and you look in your hands.
They look like raisins, you have wrinkly skin.
That's right, wrinkles are little lines in your skin.
Alright, and well you have wrinkles as you sit around your mouth and eyes.
And sometimes under your eyes you also have some sagging skin.
Or under your chin.
Under your chin as well, yeah.
That's right, so sagging means coming down, means it's heavy.
It's like hanging, right?
So sagging, something sags, it's heavy, it pulls down.
But if you have sagging skin that means your skin is no longer tight, it's kind of loose and it hangs.
Falling off your face.
Okay, and well a new popular treatment that is not really surgery is this Botox.
That's right, so Botox is something that women and some men do every couple of months I think and they have to get shots.
Right, they're like injections.
That's right, and they tighten your skin.
And so you can get Botox in your face, your forehead, or your eyes and it makes you look younger for a couple of months.
I've heard that they also put them in their lips to make them like fuller, right?
That's right, and sometimes you can say that someone's had too much Botox because they can no longer smile.
Or they can't stop smiling.
Exactly, and well very related to this is also when people get a facelift.
Okay, a facelift.
So that means that a doctor, a plastic surgeon will tighten the skin on your face so he'll pull your eyes and the skin next to your ears to make your face look younger.
Right, so that's called a facelift.
So it's to kind of take away those wrinkles, right?
Or the sagging skin.
Right, lift means to pull up.
It's the opposite of sag.
Very good.
Alright, so this dialogue has a lot of rich vocabulary related to surgery so why don't we listen to our dialogue again and we'll be back with a second part of language takeaway to explain a little bit more.
You look great!
You are beautiful!
Yes I am, but I think it's time for some plastic surgery.
I'm tired of these wrinkles and sagging skin.
See?
I don't see any wrinkles or sagging skin.
You're 25!
Stop being ridiculous!
Besides, I think that people who get Botox, have facelifts or tummy tucks look weird.
It doesn't look natural.
Whatever, I think I'm going to get liposuction and a nose job and some breast implants as well.
I think you need to get brain surgery.
I honestly don't think you need cosmetic surgery.
You look amazing!
I thought you were my friend and would support me on this.
I just want to feel better about myself and feel more attractive.
You don't need plastic surgery to do that.
You're fine the way you are and you have guys drooling all over you.
Plastic surgery hurts.
Really?
Yeah, when I got my nose job I was black and blue for a week.
Alright, we're back.
So what other surgical procedure is in store for us?
Well now the big ones.
So we've left the face and we're talking about the rest of the body.
The first one is a tummy tuck.
Okay, so a tummy tuck.
What is that exactly?
Well let's look at these two words by themselves because maybe tummy people have heard before.
This is another way to say stomach.
Usually children say tummy.
Right, my tummy hurts.
My tummy hurts and doctors they'll say stomach.
But the name of the surgery is tummy tuck because tuck means to put in or to fold.
And so my mom used to say tuck in your shirt.
You know when your shirt comes out of your pants and that means you put it back in.
Well a tuck means to fold your stomach under.
It means to make your stomach look smaller and they put staples or I think they sew you up.
Yeah, they sew you up.
It's pretty painful, right?
I've heard that.
Usually this is because somebody got a liposuction for example and that's our next word.
Liposuction.
Okay, lipo.
That's kind of fat, right?
Yeah.
And suction means to pull like a vacuum.
Right.
So that's basically what they do.
They open the person up and kind of use a sort of vacuum type device and suck all the fat out of the stomach or the balcony areas.
You know the love handles that are also called.
And this way they remove all this excess fat.
And because they do this sometimes the skin since it's been stretched out because you were a little bit fat they need to do to they need to have a tummy tuck.
That means to hide the extra skin.
The extra skin to kind of hide it.
That's right.
So these two words, these two procedures actually go hand in hand because maybe if you're very fat you get a liposuction but that doesn't solve your problem because now you have all this sagging skin off your stomach.
That's right.
So you have to have a tummy tuck as well.
Right.
Eww.
Alright.
So yeah, very, very dangerous procedure I've heard as well, right?
Yeah.
And they usually only do it with people who are very, very fat.
Right.
That means dangerously fat because if you do it on a skinny person you could really hurt them.
Yeah, of course fat is also necessary for our bodies.
Alright.
So now moving back up to the face again, a very common procedure, I think one of the most common ones is a nose job.
A nose job.
And so nose job is very colloquial.
You'll hear this on the TV.
Nose job means to fix someone's nose, to change the shape or appearance of their nose.
And so often times people with really big noses want smaller noses.
Right.
So a doctor will take some bone away and will put the skin back.
Yes, that's right.
So this is called a nose job or formally known as like a nose surgery, right?
That's right.
Rhinoplasty is the official name.
Rhinoplasty, that's right.
And actually I've heard it's very painful because they have to break your nose before they fix it.
Yeah, exactly.
Wow.
I can't believe people do this.
Alright, and well, one of the very common ones among women most likely is...
I hope so.
...are breast implants.
That's right.
So breast implants.
Am I allowed to say boob job?
Yeah, you can.
Well, the very common phrase for this is boob job.
Right.
Boob is a very colloquial term for breasts.
And breast implants are...well, an implant is something that you put inside something.
Okay, and so a breast implant is a piece of silicone.
So it's like plastic, but it's more like a liquid plastic.
Yeah, just imagine like this big plastic bag with like gel right inside of it.
And they put that inside a woman's chest to make her breasts bigger.
Right.
And so these are very, very popular surgeries, breast implants.
Right, exactly.
I guess many models and many different types of women get breast implants.
That's right.
And the verb there is to get.
So she got breast implants.
Right.
Okay, because they're things.
Very good.
Alright, so why don't we listen to our dialogue for the last time, and we'll be back to talk a little bit more.
What are you doing?
Look at me, I look so old.
I look as if I were 30.
Come on, stop being so vain.
You look great.
You are beautiful.
Yes, I am, but I think it's time for some plastic surgery.
I'm tired of these wrinkles and sagging skin.
See?
I don't see any wrinkles or sagging skin.
You're 25.
Stop being ridiculous.
Besides, I think that people who get Botox, have facelifts or tummy tucks look weird.
It doesn't look natural.
Whatever, I think I'm going to get liposuction and a nose job, and some breast implants as well.
I think you need to get brain surgery.
I honestly don't think you need cosmetic surgery.
You look amazing.
I thought you were my friend and would support me on this.
I just want to feel better about myself and feel more attractive.
You don't need plastic surgery to do that.
You're fine the way you are, and you have guys drooling all over you.
Plus, plastic surgery hurts.
Really?
Yeah, when I got my nose job, I was black and blue for a week.
All right, we're back.
As you mentioned, all of these surgeries are very painful and very expensive, right?
They are.
The plastic surgery industry is huge.
I was just reading an article that said that redos are becoming very popular.
There are doctors who perform redos.
Redo a surgery?
Redo a surgery.
That's right.
They're fixing other surgeries.
Because oftentimes, people go in, they say, I want a nose job, they get a nose job, and then it's not the nose they wanted.
And so they have doctors now who specialize in fixing former surgeries.
Wow.
Yeah, I've heard also a lot about the plastic surgery tourism industry, where people get offered a package, for example, to go to countries like Argentina, where they have good doctors, and it's very inexpensive compared to the States to get plastic surgery.
And it's also popular now in Asia, I believe, they're traveling to Hong Kong to get plastic surgery done.
Interesting.
Yeah, I know.
But it's one of those things that if you have the money and you really feel that you want to improve your appearance, then you know.
But is it an improvement?
I don't know.
It's a little fake.
Yeah, it is a little bit fake.
Like for example, but it does help people with their self-confidence, right?
Sometimes, for example, with the case of breast implants, some women feel very self-conscious about them having smaller breasts.
So they want to get bigger breasts and they feel more confident, happier, and you know, stuff like this.
So I guess if it helps and if you really want it, you know, everyone's to their own.
Well, I'm curious what our users think about this.
Have you had plastic surgery?
Would you like to have plastic surgery?
Let us know on our website, EnglishPod.com.
Right.
We'll see you guys there.
Until next time.
Bye. +
