= 0170
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
And my name is Katherine and today we're talking about a very important day in a couple's life.
That's right, we're going to a wedding and, but this time it's not going to be so romantic because actually the groom is having second thoughts about the wedding.
Okay, that means he's nervous and he's not positive he wants to get married today.
So remember the groom is the man, the bride is the woman.
Let's jump right into this dialogue, listen to what's going on and when we come back we'll be talking about some of the words and phrases you've heard.
Man, I'm freaking out.
You gotta help me.
Whoa, whoa, take it easy, relax.
Jeez, you're sweating like a pig.
What's going on?
I can't go through with this.
I just can't.
I'm not ready for marriage.
What was I thinking?
I'm only 35 years old.
I've got my entire life ahead of me.
Adventure's waiting.
I can't settle down yet.
What are you talking about?
It wasn't more than a month ago that you were rambling on about how you are tired of living the life of a bachelor and how you envy your friends that have a family.
I know, I know.
Let's think this through.
First of all, you cannot leave Amy at the altar.
Not only will she be humiliated and kill you, but she is the woman that you love and the woman of your dreams.
Why would you want to end that or jeopardize it like this?
Second of all, you're just getting cold feet.
You know deep down inside that you want to marry her.
So cut the crap and do it.
You're right.
I'm being crazy.
Okay, I'm ready.
Let's do this.
Great.
Whew, that was a close one.
You had me going there for a minute.
I thought I was gonna have to slap some sense into you.
Alright, we're back.
So almost, he almost didn't get married, but luckily you have a good friend to help you out.
Exactly.
So this friend really saved the day, made sure that the groom didn't get too nervous, and had some really positive words.
So let's take a listen to some of these marriage words in today's language takeaway.
Language takeaway.
Alright, so as you mentioned, we have this word marriage.
Now marriage is the noun form, right, of actually getting married or to be married.
Right, marriage is the noun, the word that describes the relationship between two married people.
Okay, and so you have a relationship, maybe you're dating, but once you get married, the thing between you as a man and a woman, that's your marriage.
Your marriage, okay.
So you could say, our marriage is in danger.
We need to work on our marriage.
Exactly, or we have a happy marriage.
Alright.
Okay, so that's marriage.
Now if you get married, and this guy, he mentioned a phrase, which was to settle down.
To settle down, this is a very important phrase.
To settle down means to get serious, mature, and to stop living like a child.
It means really to have a house or to start having kids.
It's a time in life.
So to settle down is to become more stable, right?
As you say, to buy a house, to have a family, to stay in one place and not be so adventurous or stuff like that.
Exactly, so it's to calm down and to be more fixed in life.
Alright, now the opposite of this would be to be a bachelor.
Right, so bachelor is a single man, someone who's not married.
And you often hear this term when we talk about apartments, so bachelor pad is an apartment that's specific to a single man.
Usually there's lots of video games and a fancy table.
A pool table, exactly.
Alright, so bachelor.
We had a lesson about this called bachelor party.
Right, which is a party for a man right before he gets married.
And bachelor is a special word for a man who's not yet married.
Okay, very good.
And now as they were talking about not getting married, he said that you can't leave Amy at the altar.
So you often hear this in movies, she got left at the altar, or you can't leave her at the altar.
This word altar is actually religious.
Altar is the table in a church where the priest does all of his work.
Right.
Alright, so an altar is a special religious table.
So usually two people will stand in front of an altar and get married, right, with the priest who is doing his thing there.
Exactly, he says, do you Joe, take Samantha to be your bride, blah blah blah.
So that happens at a special place called the altar.
Okay, very good.
It's also common in the normal mass, like on Sundays.
Right, okay.
And for the last word or phrase today, it's to get cold feet.
You're just getting cold feet.
Okay, so this is a very funny phrase in English because it doesn't actually mean that your feet are cold, right?
So cold feet means you're nervous about something, you might change your mind.
Okay.
Okay, so people often talk about men and women getting cold feet before a wedding.
But you can also relate it to any other situation, not only getting married, right?
Yeah, for example, I'm going to go jump out of an airplane tomorrow.
Okay, fast forward, tomorrow.
Oh no, I have cold feet.
I don't think I want to jump out of an airplane.
Okay, so that's to get cold feet, to have second thoughts or doubts about actually doing something.
Exactly, cold feet.
Alright, so why don't we listen to our dialogue again.
Let's keep a lookout for all of these words and we'll be back in a little bit.
Hey, man, I'm freaking out.
You gotta help me.
Whoa, whoa, take it easy, relax.
Geez, you're sweating like a pig.
What's going on?
I can't go through with this.
I just can't.
I'm not ready for marriage.
What was I thinking?
I'm only 35 years old.
I've got my entire life ahead of me.
Adventure's waiting.
I can't settle down yet.
What are you talking about?
It wasn't more than a month ago that you were rambling on about how you are tired of living the life of a bachelor and how you envy your friends that have a family.
I know, I know.
Let's think this through.
First of all, you cannot leave Amy at the altar.
Not only will she be humiliated and kill you, but she is the woman that you love and the woman of your dreams.
Why would you want to end that or jeopardize it like this?
Second of all, you are just getting cold feet.
You know deep down inside that you'd want to marry her.
So cut the crap and do it.
You're right.
I'm being crazy.
Okay, I'm ready.
Let's do this.
Great.
That was a close one.
You had me going there for a minute.
I thought I was going to have to slap some sense into you.
Alright, we're back.
So now why don't we take a look at four key phrases that we found in this dialogue on Fluency Builder.
Fluency Builder.
This first one is a really great phrase because it's very, well it's easy to picture this, what we're describing.
Sweating like a pig.
To sweat like a pig.
Okay, you're sweating like a pig.
Alright, this is a way to say that someone is sweating a lot.
A lot.
Okay, and it's really gross or disgusting.
Now do pigs actually sweat?
I don't know if pigs actually sweat, but you imagine someone smells bad and they have sweat on their face and their back and their arms.
Alright, well sometimes don't you say you're sweating like a dog?
You could also say that.
I guess we like animals in English, but this is just a really great way to say that someone is really sweaty.
Alright, and well he was sweating and he was really nervous because he said, I can't go through with this.
What does he mean go through with this?
With what?
To go through with means to actually do something, okay?
So maybe I say, I don't want to jump out of an airplane.
I can't go through with this.
Okay, I can't jump.
So it depends on what we're actually talking about.
If we're talking about a wedding, you say I can't go through with this.
I can't get married.
So if you're planning a robbery, you say well in the last minute I couldn't go through with it.
I backed out.
Right, I can't complete what I talked about doing.
Okay, and now the friend, he finally gets kind of angry and he says cut the crap.
Oh man, this is a very common phrase.
Someone says this if they don't want to listen to you complain anymore, okay?
Marco, cut the crap, okay?
I don't want to hear your excuses.
I don't want to hear your complaints.
I want to just hear...
Solutions.
Solutions, ideas, positive things.
So to cut the crap is no more complaints, no more excuses, or no more talking nonsense.
Exactly, and this is common among teachers and, well, parents.
Alright, so cut the crap.
Now it's not very polite, right?
So you wouldn't really say it to your boss or like a friend.
Cut the crap is kind of rude and it's a very spoken language, so I wouldn't write it down.
And I would not use this with someone who is like a teacher, well...
Yeah, like an authority.
You don't use it with them.
They might use it with you.
Okay, and for our last phrase, he said, you had me going there for a while, or you had me going there for a minute.
Okay, so this is a really interesting phrase.
We use this a lot in English, but it's not clear from listening to it what it might mean.
So, you had me going there, in this sense means, oh, I was really nervous for a minute.
I really believed what you were saying.
Exactly, so maybe we could give an example, Marco.
Alright.
Did you know that yesterday I won the lottery?
I mean, I won like a million dollars and I had the perfect numbers.
Oh my God, really?
Can I have a million dollars?
I would love to help you out, man, but yeah, no, I didn't actually win a million dollars.
You had me going there for a minute.
You believed me.
I did for a little while.
You believed me.
Okay, maybe not.
He's not that gullible.
That gullible.
Alright, but that's what it means, right?
To believe someone's story or to think that something's going to happen even though it doesn't.
You had me going there.
That means what you thought was going to happen didn't happen.
So, you can use it in the third person as like, yeah, I was telling him this awesome story and I really had him going for a while.
He really believed me and then I told him it wasn't true.
The truth.
Okay.
Great phrases.
Now, let's listen to our dialogue for the last time and we'll be back to talk a little bit more about getting cold feet.
Man, I'm freaking out.
You gotta help me.
Whoa, whoa, take it easy.
Relax.
Jeez, you're sweating like a pig.
What's going on?
I can't go through with this.
I just can't.
I'm not ready for marriage.
What was I thinking?
I'm only 35 years old.
I've got my entire life ahead of me.
Adventure's waiting.
I can't settle down yet.
What are you talking about?
It wasn't more than a month ago that you were rambling on about how you are tired of living the life of a bachelor and how you envy your friends that have a family.
I know, I know.
Let's think this through.
First of all, you cannot leave Amy at the altar.
Not only will she be humiliated and kill you, but she is the woman that you love and the woman of your dreams.
Why would you want to end that or jeopardize it like this?
Second of all, you were just getting cold feet.
You know deep down inside that you'd want to marry her.
So cut the crap and do it.
You're right.
I'm being crazy.
Okay, I'm ready.
Let's do this.
Great.
Phew.
That was a close one.
You had me going there for a minute.
I thought I was gonna have to slap some sense into you.
Alright, so this is a popular scenario, right?
Somebody on their wedding day, they get cold feet and they back out.
TV, movies, books, everyone loves this situation.
Have you ever actually heard of or experienced or maybe known of somebody who actually left the bride at the altar or the groom at the altar?
I don't know anyone who did that.
Luckily, I think it's really sad.
Yeah, me neither.
I don't think it's really that common.
No, but there was a movie just about this.
So there's a woman, Julia Roberts, who tries and tries and tries to get married but never can.
So it's called Runaway Bride.
Because every time she goes to the altar, she gets nervous.
She gets cold feet and she runs away.
So they call her the runaway bride.
I can't imagine this actually happening to someone.
I mean you have all your family there, your friends.
I know, it'd be so embarrassing.
It's amazing.
And expensive.
Exactly, because you've already paid for everything.
So do you get to eat the cake if you're the one who's left behind?
I think so.
Everything's paid for, right?
Exactly.
And drink all the liquor.
Alright, so that's all the time we have for today.
If you have any questions, any comments, you can come to our website at EnglishPod.com and we'll see you guys there.
Bye everyone.
Bye. +
