= 0173
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome back to EnglishPod.
My name is Marco.
And my name is Catherine and today we have an upper intermediate level lesson all about money.
That's right.
We are going to be talking about money but most importantly we need to start saving money.
We need to spend less.
Exactly.
So in order to control spending today we're talking about budgeting.
So let's take a look at this very important word in today's vocabulary preview.
Alright, so as you mentioned budgeting is a...
what is to budget?
To budget, that's the verb.
So budgeting is deciding how to spend your money.
Okay?
So that means that we prepare a plan for how to spend money.
Alright so that can be a noun and a verb.
A budget is the plan on how you're going to spend money and to budget is to execute this plan.
Exactly.
Today we're budgeting a family's spending.
We're trying to control how much this family will spend in the future.
Alright very good.
So why don't we listen to this dialogue for the first time.
Welcome Mr.
and Mrs.
Carnwell.
Please take a seat.
Thank you.
So I understand that your family spending has skyrocketed and you want to start budgeting.
Yes that's correct.
Frankly speaking our household income is relatively high and we have never had any money problems.
But I think this is the main reason as to why our spending has gone out of control.
We have two kids and with allowances, paying their credit cards, hours and not to mention our mortgage and car payments, with the recent economic downturn my husband's business has suffered and now we need some advice as to how we can prepare a family budget.
I see.
Well, you have come to the right place.
First what we need to do is determine your cash flow.
Knowing how much money is coming in will help us allocate spending to different categories such as mortgage, education, groceries, etc.
Yes that makes sense.
Secondly, I need you to bring all of your receipts for the last two to three months.
That way we can determine what your average expenditures are and see which category you're spending money on the most.
Usually your fixed costs are higher and we can't do much about that.
But we can usually trim your variable costs such as entertainment or clothing.
Great!
We will do that then.
Now how about we treat you to a nice dinner?
That's another thing.
If you really want to stop spending so much money, throw away at least half of your credit cards.
Alright we're back.
So there were some interesting words and phrases in this dialogue related to budgeting in a lot of financial terms here.
Let's get started now on language takeaway.
This first term is very important because it tells us what kind of a budget we're talking about.
We're not talking about a company here, we're talking about a family.
In this case we use the phrase household.
What are we talking about?
Household income.
Income we know is the amount of money that comes into maybe your wallet.
My income, my personal income.
That's how much money you earn.
So a household income is how much money the house earns.
So all the people that are living in this house.
That's right.
So it could be a family, it could be two married people who are married to each other.
So the idea is that it's not one person's income, it's the household income.
Think of a house.
So it's the combined income of everyone that's living there or that's making money that lives in this house.
So if Marco and I have a household, I earn $10,000 and he earns $10,000, our household income is $20,000.
Very good.
Alright, so then now we know what our household income is and in this case we have children and we give our kids an allowance.
Okay so I had an allowance when I was a kid.
This is the amount of money I got from my parents every week.
So I get I think $10 a week and I could spend it on anything I wanted and I didn't have to work because my parents gave the money to me.
And so an allowance is this money.
It's the money that mom and dad give to their children maybe every month or maybe every week.
Now it's not only related to children, right?
Because maybe if you have a brother or maybe you're married and your wife is a housewife, maybe you give her an allowance, right?
Or the opposite.
Maybe you're a house husband and you get an allowance from your wife.
That's right.
You can have an allowance if you're anyone.
You can also have an allowance from your company if you go traveling.
If you have a business trip, your company gives you a food allowance.
That's the amount of money you can spend on food and you don't have to work for it.
That's the best part.
Awesome.
All right.
So after these allowances, they were talking about well how the economic downturn has affected their income and their spending.
Okay so down, you think this is a negative thing.
You're right.
Downturn means when something, when a situation gets worse, okay, or slows down.
And in this case, the economy is what got worse and you remember this from last year.
Things started to get very difficult for people who are in business and this has affected families.
And so we call the situation an economic downturn.
Now the opposite would be an economic boom.
That's right.
A boom is when things are going well.
That means people are earning more money.
There are more jobs.
All right.
Very good.
And now moving on, as they were talking about budgeting, they mentioned this very important word, very technical, is to allocate money into different areas.
That's right or allocate spending.
This is a verb, to allocate.
That means to decide where the money will go.
Okay, so as the mother in a family, I will allocate 10% of the money to the children's allowances.
That's a lot.
50% to the mortgage, 20% to the car.
Okay.
Car repairs.
So you're allocating your spending.
That's right.
And you're allocating where to spend the money.
Okay.
And well, talking about spending, we have this word expenditures.
Expenditures.
And so this is a really important word if you're in business as well, because we consider expenditures when we're talking about how much a company earns.
Expenditures are things that we spend money on.
So remember that word expenditures, spend.
Okay.
So an expenditure.
And this is a noun and usually it's in the plural, expenditures.
Exactly.
Expenditures.
So we have many expenditures at my house.
Among them, we have the car, the rent, healthcare, things like that.
Okay, perfect.
So really good phrases there.
Really good vocabulary items.
Why don't we move on now to Fluency Builder?
Fluency Builder.
We've got some very fun phrases today, Marco, in Fluency Builder.
This first one is a very common phrase that we hear in songs and movies.
To skyrocket.
What is skyrocket?
Well, you think about a rocket, that's a ship that goes to space.
To skyrocket means to go up really high, really fast.
The price of gas has skyrocketed.
So I remember when I was a kid, gas used to be 98 cents a gallon.
And in the 2000s, the price skyrocketed and it ended up being like $4 a gallon.
Yeah, it was really expensive.
This is also, you can talk about sales have skyrocketed or the price of petroleum has skyrocketed.
So it could be a good thing or a bad thing depending on what you're talking about.
Alright.
And now moving on, they said that their spending was out of control.
Yeah, so this family doesn't seem to understand how to budget.
They spend on everything.
And so the accountant says that your spending is out of control.
That means that you're spending too much.
There's no order to the way that you're spending.
And we actually have a lesson, a previous lesson called out of control spending that we also touched this topic of what we talk about out of control.
Something is out of control.
A person can be out of control.
Like a child.
This child is out of control.
He never stops screaming and hitting people.
Alright.
And our last phrase for today, the accountant says, well, you've come to the right place.
Okay, this is him.
This is the accountant bragging.
He's saying, well, I can fix your problems.
I can help you.
You've come to the right place.
You can use this in many different ways.
For example, I have a problem maybe with my TV and I say, Marco, oh my gosh, my TV doesn't work.
I don't know what to do.
Can you help?
Right.
And I can say, well, you've come to the right place.
I can fix your TV.
Marco's an expert in electronics.
Alright, so you've come to the right place.
It's a very common phrase, especially as you say, when somebody's trying to brag and say, well, I know how to fix your problems or I know what you need.
I'm good at this.
You've come to the right place.
If you want to learn English, you've come to the right place.
EnglishPod.com.
Exactly.
Alright, so let's listen to our dialogue for the last time.
Welcome, Mr.
and Mrs.
Carnwell.
Please take a seat.
Thank you.
So I understand that your family spending has skyrocketed and you want to start budgeting.
Yes, that's correct.
Frankly speaking, our household income is relatively high and we have never had any money problems.
But I think this is the main reason as to why our spending has gone out of control.
We have two kids and with allowances, paying their credit cards, hours, and not to mention our mortgage and car payments, with the recent economic downturn, my husband's business has suffered and now we need some advice as how we can prepare a family budget.
I see.
Well, you have come to the right place.
First, what we need to do is determine your cash flow.
Knowing how much money is coming in will help us allocate spending to different categories such as mortgage, education, groceries, etc.
Yes, that makes sense.
Secondly, I need you to bring all of your receipts for the last two to three months.
That way we can determine what your average expenditures are and see which category you're spending money on the most.
Usually, your fixed costs are higher and we can't do much about that.
But we can usually trim your variable costs such as entertainment or clothing.
Great!
We will do that then.
Now how about we treat you to a nice dinner?
That's another thing.
If you really want to stop spending so much money, throw away at least half of your credit cards.
Alright, we're back.
So now talking about allowances, you said you had an allowance when you were a kid.
Did you really have a $10 a week allowance?
No, I think it was like $8.
It started out at $6 or $5 a week and I think the most I got was like $10 or $11.
So it was like almost about $1 a day.
About that, but usually the point was that, well, I started working when I was 15 because my parents thought it was important for children to learn how money works.
But I was given that money because at the time it was enough money to go out one night.
So on Friday nights if I wanted to go out with my friends, I could go out to watch a movie and get a slice of pizza and $10 was enough.
Now $10 doesn't even buy you a ticket to the movie, but at the time it was more than enough.
So this is important I guess because different families have different ways of upbringing their children and in many cases this doesn't happen, right?
If I want to go out to the movies on a Saturday then my parents will give me $30 and if I want to go out next weekend they'll also give me money.
So it's interesting to see the contrast because obviously when I was a kid also I didn't really get this opportunity of going out all the time and actually I had to work for it.
So if I wanted to go out on the weekend I would get an allowance, but also I would have to wash the car.
That was typical with my dad.
I had to wash the car.
Well I think it's interesting because it shows that the parents want to teach their children about budgeting because if you only have $10 you really have to budget.
You have to decide how you will allocate that money even though it's not very much.
So in some ways it's good practice.
Yeah it is.
I think it's done as well.
We're not in debt.
Not yet.
All right so let us know how allowances work in your country or maybe did you have an allowance when you were a kid?
A lot of people didn't have an allowance.
I know a lot of friends didn't get allowances.
So come to our website EnglishPod.com and if you have any other questions or doubts please leave them there as well.
We hope to hear from you.
Until next time.
Bye everyone.
Bye. +
