= 0190
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome back to EnglishPod.
My name is Marco.
My name is Catherine and today we have an elementary level lesson about food, one of my favorite things to talk about.
That's right.
We are going to talk about food, but specifically we're going to talk about a family barbecue.
Okay, what is a family barbecue?
Well, I'll just say a few words first.
A barbecue is usually something that we do outside.
We bring food, we play games, maybe have some drinks, and a lot of the food is grilled.
So that's what we're talking about today.
We're going to hear this dialogue first and then we'll come back to talk about it.
Is everything ready for the big family barbecue tomorrow?
Yep.
The steaks and chicken are marinated and I also bought hamburger buns.
We should also cook a couple dozen hot dogs and kebabs.
Yeah, good idea.
We could put some lawn furniture outside next to the grill.
I also set up the tent outside so we can hide from the sun if it gets too hot.
Great!
I asked Grace to bring cups and serve yetz as she is also bringing two big coolers for the beers.
This is going to be a great barbecue.
Oh no, it's raining.
Alright, we're back.
So probably a couple of words you didn't really understand.
So let's take a look at those now in Language Takeaway.
Language Takeaway.
Lots of food words, Marco.
The first one is barbecue.
We were talking about that a minute ago.
A barbecue is something we do usually for something on a special occasion or for dinner.
It's a summertime thing.
You know, you go outside when it's warm and the entire family comes and we have food.
Sometimes people even bring food.
Right.
And actually, as you mentioned, it's something that you do a barbecue.
You have a family barbecue, but it's also a verb.
To barbecue something.
So to cook meat on a barbecue.
So that's cooking meat, not in a stove, not with gas.
Usually it's under a fire or very warm intense heat coming from coals.
Exactly.
And so before we cook food, usually before we cook meat on the grill, before we barbecue it, we have to marinate it.
Okay.
So in this situation, the steaks and the chicken are already marinated.
Okay.
So to marinate something or which is so to marinate something, which is a verb or the steaks and chickens are marinated, which is an adjective.
So basically means that you have added spices and maybe some lemon juice, different herbs or salts to the meats in order to give it flavor before you cook them.
Exactly.
Sometimes in Indian cooking, for example, you marinate with a yogurt sauce and you leave the meats in the refrigerator for a whole night.
Exactly.
So marinating or to marinate is a process to give flavor to food.
Very good.
All right.
So we've marinated our food, our chicken, our steaks, but also we have hamburgers.
So we need hamburger buns.
What are buns?
Okay.
Buns are pieces of bread that are for special kinds of food.
So you have a hamburger bun.
It's a round piece of bread and the hamburger goes on one piece and under another piece.
A hot dog bun is different.
It's like a piece of bread that's folded and the hot dog goes in the middle.
So bun is a special kind of bread for these kinds of foods.
All right.
So remember, if you want to have a hot dog, you need to buy hot dog buns.
So people know already that you're talking about bread.
And if you want to buy a hamburger bread, you say a hamburger bun.
That's right.
So hamburger buns and hot dog buns.
But after we talk about having the hamburger buns, we discuss how many hot dogs are going to cook.
So the person says we should cook a couple dozen hot dogs.
All right.
So a dozen is 12 units of something.
Right.
So eggs are sold in dozens.
We buy a dozen eggs.
We buy 12 eggs.
Okay.
Or you can say half a dozen.
That means six.
Half of 12.
And a couple dozen is usually around 24, 25.
Okay.
Very good.
So a dozen hot dogs and they are also getting kebabs.
What are kebabs?
One of my favorite foods.
Kebabs are sticks or skewers of meat.
So you have a very thin stick and you put the meat on it and you put that on the grill and you cook the meat on the grill.
So yeah, those are very common.
For example, in the Middle East, right, you have kebabs, sticks of meat and also maybe some vegetables put on it and you grill them.
Exactly.
Very flavorful, very tasty meat.
All right.
So why don't we listen to our dialogue again and we'll come back shortly to look at some more words.
Is everything ready for the big family barbecue tomorrow?
Yep.
The steaks and chicken are marinated and I also bought hamburger buns.
We should also cook a couple dozen hot dogs and kebabs.
Yeah.
Good idea.
We could put some lawn furniture outside next to the grill.
I also set up the tent outside so we can hide from the sun if it gets too hot.
Great.
I asked Grace to bring cups and serve yetz as she is also bringing two big coolers for the beers.
This is going to be a great barbecue.
All right.
We're back.
So now why don't we go to a second part of language takeaway and take a look at five more words.
Language takeaway.
All right.
The first word that we're going to look at is lawn furniture.
So we're going to have lawn furniture outside.
OK.
So before we even start thinking about food, we have to decide where people will sit at this barbecue.
And so we have to find out how much lawn furniture we have.
Furniture can be a sofa, a table, a chair.
We have furniture in the house.
But lawn furniture is furniture for the outside.
A lawn is the green grass outside your house.
So it's usually not going to be made out of wood, for example, because if it rains, it might get ruined.
Right.
So usually it's either plastic or maybe even rock or stone or metal So that's what lawn furniture is.
Furniture that is made to be outside in your backyard, for example, or that sits on your lawn.
Exactly.
And so we're going to be on the lawn furniture.
We have the special thing for cooking meat outside the grill.
OK.
So we mentioned that you grill chicken or you grill steaks, but it's also a noun, a grill.
So a grill.
What is that?
A grill is like a stove for the outside.
But instead of having electricity to make the fire, we have gas or propane.
And this is something that we light on fire.
And we use coals to keep the insides very warm.
And so this is just a way to cook meats or even vegetables outside.
OK, perfect.
So that is a grill.
And if you're going to cook foods or vegetables in this way, so you're going to grill them.
All right.
And well, just in case it gets hot and you want to hide from the sun, we are going to set up a tent.
OK, a tent.
You can sleep in a tent, but in this case, a tent is just a covering outside.
So maybe some cloth or some fabric that will stand over us when we sit down or want to be outside.
It's also a way to protect us from the rain.
Right.
So as you mentioned, a tent is something that you set up temporarily made out of cloth or plastic to protect you from the sun or rain.
Or if you're going camping, you sleep in one.
All right.
And now that they have all the food, they need cups.
And then they mentioned the strange word.
It kind of sounds French.
Serviette.
Serviette.
So I do think it comes from the French word.
This is a British way of saying napkins.
So it's like paper for cleaning your hands and cleaning your mouth that you throw away.
OK, so you can say napkins or if you want to sound a little bit more fancier, you can say serviettes.
And speaking of fancy, let's talk about beer.
Where do we where do we keep beer?
It has to stay cold, right?
Right.
So usually you would place it in a refrigerator.
But if you're outside or you're going camping, you want to keep them cold or you want to keep something hot.
You place it in a cooler.
OK, so a cooler is a plastic bin or a plastic box that we put all of the ice in and the drinks.
So it's not just for beer.
It's also for Coke and Sprite and all these different drinks.
Right.
So it's usually made to keep something cool.
But as I said, if you want to keep something warm, you can also keep it in the cooler.
It keeps the temperature of the foods.
And the nice thing is that it's not electric, so you can use it anywhere.
Right.
All right.
So that's all the words for today.
Why don't we listen to our dialogue for the last time?
Is everything ready for the big family barbecue tomorrow?
Yep, the steaks and chicken are marinated and I also bought hamburger buns.
We should also cook a couple dozen hot dogs and kebabs.
Yeah, good idea.
We could put some lawn furniture outside next to the grill.
I also set up the tent outside so we can hide from the sun if it gets too hot.
Great.
I asked Grace to bring cups and serve yet, as she is also bringing two big coolers for the beers.
This is going to be a great barbecue.
Oh, no, it's raining.
All right, we're back.
So family barbecues and doing these things, did you do these when you were young at home?
Do you still like to do it all the time?
I love barbecues.
That's one of my favorite ways to eat food.
The nice thing about a barbecue is you get to sit outside and relax and there's nothing better than nice, fresh grilled meat.
Right.
And well, you have all your friends over, so you're having a couple of beers and you're having some meat.
And it's actually a really nice way of just having something at home with good friends and family, right?
Exactly.
And some of the most important barbecues we have are in the summer near July 4th.
So people like to have July 4th barbecues where you celebrate Independence Day and sit outside and drink and have hot dogs and hamburgers and macaroni and cheese.
Actually, while I was in Chile, I noticed that as well near their their festivities for their independence, which is September 18th, a lot of people get together and have barbecues.
And it's so, so popular that pretty much every house in the neighborhood, you can smell somebody barbecuing on the weekend.
You're making me so hungry.
All right, guys.
So if you have any questions, any doubts, or if it's common for you guys to barbecue back home, then why don't you send us a couple of comments at EnglishPod.com and we'll see everyone there.
Bye. +
