= 0452
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 452: Dealing with Unhappy Employees.
This is English as a Second Language Podcast number 452. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, an 8- to 10-page guide that will help you improve your English even faster.
This episode is called “Dealing with Unhappy Employees.” It’s a dialogue between Asa and Samantha, and it talks about some common problems that you might have at work. Let’s get started.
[start of dialogue]
Asa: I don’t know how we got stuck with reviewing employee complaints. This has got to be the worst job ever!
Samantha: This is important work and somebody has to do it. Come on, let’s get started.
Asa: I think it’s bad for morale to allow employees to file complaints. We’re all overworked and underpaid, and most of us are burned out.
Samantha: How else are disgruntled employees going to voice their grievances?
Asa: Personally, I think it’s stupid for employees to put their complaints on paper. Aren’t they worried about retaliation from the management?
Samantha: I don’t think that’s going to happen. The whole point of having this system is to resolve any problems before they get blown out of proportion. It’s to everybody’s benefit to try to make this work.
Asa: On the contrary, I think it makes for a dysfunctional workplace: Employees thinking of things to complain about and the management with their backs up against the wall. I just don’t get it.
Samantha: No, I guess you don’t. If you don’t like how things are done around here, I’ve got a suggestion for you.
Asa: What?
Samantha: File a complaint.
[end of dialogue]
The title of this episode is “Dealing with Unhappy Employees.” To “deal with” means to take care of a problem, to solve or resolve some sort of problem.
Asa says, “I don’t know how we got stuck with reviewing employee complaints.” To “get stuck with (something)” is a phrasal verb meaning to be forced to do something that is boring or unpleasant, to have to do something you don’t want to do: “I cooked dinner and my wife got stuck with washing the dishes.” Asa is saying that he doesn’t know how they got stuck with “reviewing,” or looking at, employee complaints. A “complaint” is something negative that is said or written, and usually comes with an explanation about why someone doesn’t like something.
Asa says, “This has got to be the worst job ever.” Samantha says, “This is important work, and somebody has to do it. Come on, let’s get started,” she says. Asa says, “I think it’s bad for morale to allow employees to file complaints.” “Morale” (morale) is the way that a group of people, especially employees, feel about their jobs (their opinions, what they think about their jobs). It’s the general feeling that they have. Morale can either be high or low. If you say, “My employees have low morale,” you mean they’re not very interested, they’re not very happy, they’re not very excited. The opposite would be high morale.
Asa is saying that it’s bad for morale to have the employees “file,” or submit (give to the company) their complaints. He says, “We’re all overworked and underpaid, and most of us are burned out.” To be “overworked” means to have too much work and to work too hard, making you tired. We all think that we are overworked, I’m sure! To be “underpaid” means that you don’t get enough money for the work that you do. Once again, most people think that they are overworked and underpaid. This can cause some people to burn out. To “burn out” is a two-word phrasal verb meaning to become tired from having done too much of something for too long. So, if you continue to do the same thing year after year and it’s very difficult, you could eventually burn out; you could get to the point where you’re too tired to want to continue, that you’re no longer effective at what you do.
Samantha says, “How else are disgruntled employees going to voice their grievances?” “Disgruntled” means unhappy, disappointed, perhaps even angry. “To voice” means to express something in words, to say something. “Voice,” like “burn out,” has different meanings in English; take a look at our Learning Guide for some additional explanations of both of those terms. Samantha is saying that she doesn’t know how these upset, angry, disgruntled employees are going to “voice their grievances,” are going to tell the company what they don’t like. A “grievance” is like a complaint that is said or written with an explanation. Often, it is related to people thinking that there is something unfair or that they haven’t been treated right by their company.
Asa says, “Personally (in my opinion), I think it’s stupid for employees to put their complaints on paper.” “On paper” just means in writing, written down. “Aren’t they worried about retaliation from the management?” “Retaliation” means revenge, something that you do to hurt another person who has hurt you. So, if I punch you, you could retaliate and punch me back. Asa is saying that if the employees complain, the company could retaliate against them – could do something negative, something bad to them.
Samantha says, “I don’t think that’s going to happen. The whole point (the main reason) of having this system is to resolve any problems before they get blown out of proportion.” To “resolve” means to solve, to fix or end a problem. So, they’re trying to fix any problems with the employees before they get blown out of proportion. To “blow (something) out of proportion” means to make it more important or more serious than it really is or than it has to be. So, you’re trying to stop the problems when they’re small, before they get too big.
Samantha says, “It’s to everybody’s benefit to try to make this work.” Asa says, “On the contrary,” meaning I think it’s the exact opposite; I disagree with you. He says, “On the contrary, I think it makes for a dysfunctional workplace.” Asa is saying that he thinks it “makes for,” meaning it causes, a dysfunctional workplace. “Dysfunctional” means not functional; not working properly, especially when people have bad relationships with each other. There’s a popular expression you’ll read or hear about called “the dysfunctional family.” It would be a family that doesn’t communicate very well with each other, doesn’t have good relationships with each other. Asa says, “employees thinking of things to complain about and the management with their backs up against the wall.” Asa is saying this is why it causes a dysfunctional workplace, because the employees are thinking of things to complain about and the managers – the management has their backs up against the wall. “To have one’s back up against the wall” means to be in a position where you don’t have a lot of options or choices, that you’re forced to do something without necessarily having a lot of flexibility.
Asa says, “I just don’t get it” – I don’t understand. Samantha says, “No, I guess you don’t (meaning no, you don’t understand). If you don’t like how things are done around here, I’ve got a suggestion for you.” Asa says, “What?” Samantha says, “File a complaint.” Of course, that’s what Asa was complaining about: employee complaints.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Asa: I don’t know how we got stuck with reviewing employee complaints. This has got to be the worst job ever!
Samantha: This is important work and somebody has to do it. Come on, let’s get started.
Asa: I think it’s bad for morale to allow employees to file complaints. We’re all overworked and underpaid, and most of us are burned out.
Samantha: How else are disgruntled employees going to voice their grievances?
Asa: Personally, I think it’s stupid for employees to put their complaints on paper. Aren’t they worried about retaliation from the management?
Samantha: I don’t think that’s going to happen. The whole point of having this system is to resolve any problems before they get blown out of proportion. It’s to everybody’s benefit to try to make this work.
Asa: On the contrary, I think it makes for a dysfunctional workplace: Employees thinking of things to complain about and the management with their backs up against the wall. I just don’t get it.
Samantha: No, I guess you don’t. If you don’t like how things are done around here, I’ve got a suggestion for you.
Asa: What?
Samantha: File a complaint.
[end of dialogue]
The script for this episode was written by the overworked Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
to get stuck with (something) – to be forced to do something that is unpleasant or boring; to have to do something that one doesn’t want to do
* Why do I get stuck washing dishes every night?
complaint – something negative that is said or written, explaining what one is unhappy about and why
* Clarke asked to speak to the store manager so that he could make a complaint about the new higher prices.
morale – the way that a group of people, especially employees, feel in general, especially about whether they like their job
* The manager improved employees’ morale when she started giving them free pizza each Friday.
overworked – having worked too much and too hard; being tired from having worked too much or for too long
* Last week, three of the five secretaries were on vacation and the other two felt very overworked because they had to do everything.
underpaid – not receiving enough money for the work that one is doing; feeling that one should be paid more for one’s work
* Keenan feels really underpaid, so he’s going to ask his boss for more money.
to burn out – to become tired from having done too much of something for too long, and not wanting to do that thing anymore
* Alicia used to love working as a lawyer, but after six years of 12-hour workdays, she’s burned out and wants to become a teacher instead.
disgruntled – unhappy, disappointed, and angry because something didn’t happen the way that one wanted it to
* The employees became very disgruntled when the company president announced that they would have to pay for parking.
to voice – to express something in words; to speak; to say something
* Some parents called the teacher to voice their concerns about the books that their children were reading in the classroom.
grievance – complaint; something negative that is said or written, explaining what one is unhappy about and why, especially if one thinks that something is unfair or that one has been treated unfairly
* The female employees have a grievance because they aren’t being paid as much as male employees who do the same jobs.
on paper – in writing; written
* The young man has agreed to sell us the car for just $1,800, but we won’t believe it until we see it on paper.
retaliation – revenge; something that one does to hurt another person after one has been hurt by that person; something that one does to get even with the person who is responsible for something bad that happened to oneself
* When Verna accidentally lost her brother’s watch, he hid her necklace as retaliation.
to resolve – to solve; to address; to fix and end a problem
* The company said that it would resolve my problem in two days, but I still haven’t heard back from them.
blown out of proportion – treated as being much more important or serious than something actually is
* When the airline employee heard a passenger joking that he had a bomb, it was blown out of proportion and the police came to arrest him.
on the contrary – a phrase used to show that something is completely the opposite of what came before it; a phrase used to show that one completely disagrees with what was just said
* Bryce thinks the movie was too loud, but on the contrary, I could hardly hear what the actors were saying!
dysfunctional – not working properly, especially when people have bad relationships with each other
* Carlita comes from a dysfunctional family where her father left when she was just a baby and her mother is hardly ever at home.
(one’s) back up against the wall – in a position where one doesn’t have any options or choices and is forced to do something
* When the landlord raised our rent, we had our backs up against the wall, because we had to pay more if we wanted to continue living there.
Comprehension Questions
1. What are the employees complaining about?
a) Being overworked and underpaid.
b) Retaliation from management.
c) Things that are blown out of proportion.
2. What would you expect in a dysfunctional workplace?
a) High employee morale.
b) Many disgruntled employees.
c) Problems that have been resolved.
Answers at bottom.
What Else Does It Mean?
to burn out
The phrase “to burn out,” in this podcast, means to become tired from having done too much of something for too long, and not wanting to do that thing anymore: “She practiced playing the piano for three hours each day when she was a child, so now she’s burned out and doesn’t even want to look at a piano.” The phrase “to get burned” means to be hurt either financially or emotionally: “He got burned in the stock market, and now he doesn’t like to invest money.” Or, “Have you ever been burned by someone you loved?” Finally, the phrase “to be burning up” means to have a hot forehead or body because one has a fever: “He’s burning up! I think we should take him to see a doctor.”
to voice
In this podcast, the verb “to voice” means to express something in words or to say something: “How many people have voiced their objections to the company’s new policy?” The phrase “to lower (one’s) voice” means to speak more quietly: “Please lower your voice while you’re in the library.” The phrase “to raise (one’s) voice” means to speak more loudly, usually shouting in anger: “I hope I never raise my voice at my son.” The phrase “at the top of (one’s) voice” means to shout or yell as loudly as one can: “The concert was so loud that I couldn’t hear anything Jenny said, even though she was standing right next to me and shouting at the top of her voice.”
Culture Note
Employees in the United States often complain about work and things that make them unhappy in the “workplace” (the place where one works). One of the most common complaints in “favoritism,” or the idea that employees are not being treated fairly, with the boss treating one person better or more nicely than other employees.
Many employees also complain that they are overworked and underpaid. They think that their “workload” (the amount of work that one has to do) is too heavy, especially if the company is trying to save money by having fewer employees. Many employees also complain that they should be paid more for the work that they do. They think that they “deserve” (should have) a “raise” (an increase in the amount of money that one is paid), but their employers either don’t agree or don’t have enough money to give them raises. Often complaints about “salary” (the amount of money that one is paid in a year) and “benefits” (things other than money that employees receive from their employers, like health insurance or free parking) “stem from” (are based on) differences in the salaries of new and old employees, or the difference in salaries between management and workers.
Other people complain about the workplace itself. Employees might complain that a workplace is “unhygienic” (unclean; unsanitary) or unsafe, or they might complain that they don’t have the tools and equipment that they need to do their job well.
Finally, many employees complain about their boss’s “managerial style” (the way that a person works with the people who report to him or her). They might complain that their boss “micro-manages” them, trying to control small, unimportant details. Or they might complain that their boss doesn’t communicate well or never has time to meet with them.
Comprehension Answers
1 - a
2 - b