= 0459
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 459: Watching Political Commentary Shows.
This is English as a Second Language Podcast number 459. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide, an 8- to 10-page guide we provide for this episode and all of our current episodes that will help you improve your English even faster.
This episode is called “Watching Political Commentary Shows.” These are news programs where there are people giving their opinions about politics – about things going on in the country, in the government. They’re very popular in the United States, especially in last 20 years they have become popular. We’re going to listen to a dialogue between Laura and Joon that uses some common vocabulary you might hear or see used on one of these television shows. Let’s get started.
[start of dialogue]
Laura: I really don’t like these political commentary shows. They purportedly present both sides of an issue, but the commentator is always biased.
Joon: Oh, I don’t think so. Each show invites pundits on each side of the political spectrum. In this show, for instance, the pundits each take turns presenting their arguments.
Laura: You mean they each present the party line, right? I find it so predictable what each side will say, since they always invite people who have opinions that are poles apart.
Joon: That’s not always true. This other show has a roundtable format. Each person listens to the others and they debate the issues.
Laura: On that show, it’s not what they say, but how they say it. They treat the others’ opinions with such contempt. You can hear the loathing in their voices and they constantly talk over each other. I’m surprised you can bear to watch it.
Joon: I find it stimulating. I like a good fight.
Laura: I guess it’s better for them to do it on screen than on the streets!
[end of dialogue]
Our dialogue begins with Laura saying, “I don’t really like these political commentary shows.” “Political” means relating to politics, what the government does – their policies, their actions. “Commentary” means giving your opinion, or your view about something. Laura says that these political commentary shows purportedly present both sides of an issue, but the commentator is always biased. “Purportedly” means supposedly; it’s what someone says they are doing, but it usually isn’t true. You could say, “She went into his room purportedly to put away some clothes, but he thinks that she was looking for something.” She said she was going in there to put away some clothes, but she was really doing something else.
These shows purportedly present, or give you both sides of an issue – give you different viewpoints about an issue, but the commentator is always biased. A “commentator” is a person who gives his or her opinion, usually someone who is paid to give their opinion. They can be either politically liberal (on the left), or politically conservative (on the right), or somewhere in between. When we say someone is “biased,” we mean that they have a strong opinion for or against something, so that you can’t really see anything but your opinion. Someone who is biased is usually someone who is not objective, someone who can’t look at the facts and determine something because they have their own strong opinions that already influence their views.
Joon says, “Oh, I don’t think so (I don’t think the commentators are always biased). Each show invites pundits on each side of the political spectrum.” A “pundit” (pundit) is a person who gives his or her opinions about something, usually on a radio program or on a television show. There are several cable news networks that have political pundits, people giving their opinions on shows, and you can find lots and lots of these shows about American politics on American television. The “political spectrum” is the range of opinions, from liberal on the left, to conservative that is on the right. That’s the spectrum; it’s the range of different opinions. Joon says, “In this show, the pundits each take turns presenting their arguments.” To “take turns” means that each person has an opportunity, they go from one to the other, then back to the first, and then back to the second, and so forth. “Arguments,” here, means reasons why you believe something. The word “argument,” however, has a couple of different meanings in English; go to the Learning Guide for some additional explanations.
Laura says, “You mean they each present the party line, right?” The “party line” here means the official opinion or the generally accepted ideas of a certain group. Usually when we are talking about a political party people will use this term, the party line. It also has the implication of being someone who doesn’t think for themselves, just repeats the opinions of the group that they belong to. But in any case, party line has to do with the accepted positions about certain things, opinions that a certain group has about, often, political issues. Laura says, “I find it so predictable what each side will say.” When you say something is “predictable,” you mean you know what is going to happen, you already know their opinion before they tell you – you can predict it. She says, “they always invite people who have opinions that are poles apart.” The expression “poles apart” here means very different from one another. Someone very conservative and someone very liberal would be poles apart.
Joon says, “That’s not always true. This other show has a roundtable format.” A “roundtable” (one word) is a type of meeting or discussion where people sit around a table and each person talks for a short amount time. It’s more like a conversation. Joon says in this roundtable, each person listens to the others and they debate the issues. To “debate” means to talk about what you think and the reasons why you think that.
Laura says, “On that show, it’s not what they say, it’s how they say it. They treat the others’ opinions with such contempt.” “Contempt” is a feeling that someone or something isn’t important and you do not need to respect it. It’s a feeling of disgust, we would say. If someone says, “She was treated with contempt,” they mean that the other persons didn’t respect her and they treated her badly. Laura says that you can hear the loathing in their voices and they constantly talk over each other. To “loathe” (loathe) means to hate, to really dislike something, not to like something. “Loathing” means hatred of something, not liking something. She says, “You can hear the loathing (the dislike, their hatred) in their voices and they constantly talk over each other.” To “talk over (someone)” means to speak loudly before the other person is finished talking. You’re trying to basically stop the other person from talking by speaking loudly so that they will listen to you, or someone else will listen to you. This is very common on these political commentary shows; people are almost shouting or yelling at each other about some political topic.
Laura says, “I’m surprised you can bear to watch it.” To “bear to watch it” means that you are able to watch it because it is so difficult; it is so painful, perhaps. Joon says, “I find it stimulating.” Something that is “stimulating” is something that is exciting, something that is interesting, something that makes you think about a topic in a new or different way. Joon says, “I like a good fight,” when two people are arguing or disagreeing with each other. Laura says, “I guess it’s better for them to do it on screen than on the streets!” So she’s saying I guess it’s better for them to fight each other on the television. The expression “on screen” means either on your television or on a movie screen – a place where you watch movies. It’s better for them to do it on TV then to fight in the streets. The idea here is that if you fight in the streets it’s often a physical fight, where you’re punching and hitting the other person.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Laura: I really don’t like these political commentary shows. They purportedly present both sides of an issue, but the commentator is always biased.
Joon: Oh, I don’t think so. Each show invites pundits on each side of the political spectrum. In this show, for instance, the pundits each take turns presenting their arguments.
Laura: You mean they each present the party line, right? I find it so predictable what each side will say, since they always invite people who have opinions that are poles apart.
Joon: That’s not always true. This other show has a roundtable format. Each person listens to the others and they debate the issues.
Laura: On that show, it’s not what they say, but how they say it. They treat the others’ opinions with such contempt. You can hear the loathing in their voices and they constantly talk over each other. I’m surprised you can bear to watch it.
Joon: I find it stimulating. I like a good fight.
Laura: I guess it’s better for them to do it on screen than on the streets!
[end of dialogue]
The script for this episode was written by the always stimulating Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
political commentary – offering one’s opinion about political issues, the people who work in the government, and their decisions
* During the fall of 2008, all the political commentary shows were talking about the U.S. presidential elections.
purportedly – supposedly; claiming to do something, although it probably isn’t true or correct
* She went into his room purportedly to put away the clean clothes, but he thinks she was really looking through his papers.
commentator – a person whose job is to offer his or her opinion about something, especially politics
* On this show, the commentator speaks with two guests each week.
biased – with a strong opinion for or against something, so that one is no longer able to see the issue as it really is
* Mothers can be biased and think that their children are beautiful, intelligent, and well behaved, even when they aren’t.
pundit – a person who gives his or her opinion about something, usually on a radio program or a TV show
* I couldn’t believe the things we heard from that pundit!
political spectrum – the range of opinions about a political issue, from very conservative to very liberal and everything in between
* Even within the Democratic Party, there is a wide political spectrum and there are many things that people don’t agree on.
argument – the reasons why one believes something and why one thinks other people should believe the same thing
* Her main argument for spending more money on education is that children who get a better education will get better jobs in the future.
party line – the official opinion of an organization, group or political party; the ideas that people should agree with if they are going to be members of an organization, group, or political party
* The other politicians don’t like him because he rarely votes along the party line.
predictable – easy to know what will be said or done; easy to know what will happen
* The movie was really boring because the ending was too predictable.
poles apart – extremely different from each other; opposites
* Jane and Jacques are poles apart in many ways: she works hard while he prefers to watch TV, and she likes to spend a lot of money while he saves all of his money.
roundtable – a type of meeting or discussion where people sit around a table and each person speaks for a short period of time
* I think our office meetings would be better if we had a roundtable discussion, instead of making everyone listen while the manager speaks.
to debate – to talk about an issue where one person explains his or her position and another person explains his or her opposite position, trying to show which position is better or more correct
* Have you been listening to the economists who are debating whether the federal government should lower interest rates again?
contempt – a feeling of disgust; a feeling that someone or something is not important and cannot be admired or respected
* Many people feel contempt for criminals, but Becca feels sorry for them because she thinks they just made a bad decision.
loathing – strong hatred and dislike mixed with anger
* It frightened us to hear her talk about her loathing for people who drive too slowly on the freeways.
to talk over (someone) – to speak loudly while another person is speaking, trying to be heard while the other person is still talking
* Instead of talking over our colleagues, try saying, “Excuse me, but I’d like to say a few words.”
stimulating – exciting and interesting, making one think about something in a new way
* This toy store sells a lot of things that are stimulating for young babies.
on screen – on television or in the movies
* How old was this actress when she first appeared on screen?
Comprehension Questions
1. What doesn’t Laura like about commentators?
a) They talk too much.
b) They aren’t open-minded.
c) They don’t understand politics.
2. What do people need in order to debate the issues?
a) They need to have contempt for each other.
b) They need to talk over each other.
c) They need to have different opinions.
Answers at bottom.
What Else Does It Mean?
argument
The word “argument,” in this podcast, means the reasons why one believes something and why one thinks other people should believe the same thing: “The doctor made a powerful argument for exercising for 30 minutes each day.” Or, “Their argument is that we should close the national park to protect it from visitors.” An “argument” is also a loud, angry discussion between two people who disagree about something: “Do you remember your parents having arguments about money when you were a child?” The phrase “for the sake of argument” is used when one wants to talk about something that might happen: “You’ll probably be accepted at Princeton, but for the sake of argument, let’s say that you’re not. Then what will you do?”
on screen
In this podcast, the phrase “on screen” means on television or in the movies: “I wish real life were as exciting as life on screen.” The phrase “the silver screen” or “the big screen” refers only to the movies: “She acted in several commercials before she finally made it to the big screen.” The phrase “off screen” refers to the time when an actor is not in front of a TV or movie camera: “She always seems nice in the movies, but I wonder what she’s like when she’s off screen.” If something is “a screen for (something),” it is hiding something: “They use their dry-cleaning business as a screen for illegal activities.” Finally, the phrase “to screen (someone) for (something)” means to do a test to see if someone has a disease or another medical problem: “Have you ever been screened for tuberculosis?”
Culture Note
In the United States, there are many different political commentary shows that use different types of “formats” (styles and ways of doing things) and “segments” (sections or parts).
Most political commentary shows have a commentator who “hosts” or “moderates” the show, introducing guests, asking them questions, and helping to guide the discussion. The guests might participate in a “one-on-one” (between only two people) interview with the host, or they might participate in a roundtable discussion. The guests often have very different opinions, so one of the host’s responsibilities is to make sure that the discussions and debates don’t become too “hostile” (angry).
Sometimes the people who are watching the show are invited to “call in” (use their phone to call the show) and ask questions “on air” (while the TV show is being recorded). The host and guests usually answer the question while the caller is still “on the line” (hasn’t yet hung up the phone) so that he or she can ask a “follow-up question” (a second question about the first answer), if needed. Other viewers use e-mails to ask their questions and the host reads those questions to the guests.
Many shows have a “point/counterpoint” segment. One person is given a certain amount of time, perhaps 2-3 minutes, to present his or her “point” (opinion or argument). Then a person with an opposite position is given the same amount of time to present his or her “counterpoint” (opposite opinion or argument).
Often political commentary shows have long segments where the host or commentator simply provides his or her commentary on what is happening in the news, without interacting with any guests at all.
Most political commentary shows use a mixture of a few or all of these formats and segments.
Comprehension Answers
1 - b
2 - c