= 0475
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 475: Hiring a Hitman.
This is English as a Second Language Podcast episode 475. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
Visit our website at eslpod.com. You can find some additional courses in business and daily English there, along with a Learning Guide for this episode that will help you improve your English even faster.
This episode is called “Hiring a Hitman.” It’s sort of a funny dialogue about a woman who wants to get rid of someone. Let’s get started.
[start of dialogue]
Gus: Are you Shirley?
Shirley: Yeah, thanks for agreeing to meet me here. I’m told you’re the best sniper in the business and you can be discreet. I need a hitman who can do a job, then make himself scarce.
Gus: I’m your man. Tell me about it.
Shirley: There’s someone who’s been a thorn in my side, keeping me up at night, and it’s time to take him out.
Gus: Taking care of problems is my specialty. I’ll need a down payment now and the balance when I finish him off. We shouldn’t meet again, so I’ll tell you later where to make a drop.
Shirley: All right.
Gus: Good. How will I be able to spot the target?
Shirley: Here’s a picture. He’s usually in the yard in the afternoons.
Gus: You want me to kill a dog?!
Shirley: Right, he’s my neighbor’s dog and he keeps me up every night. Is that a problem?
Gus: You bet it is. Who do you think I am? People are disposable, but dogs? They’re a man’s best friend.
Shirley: Are you kidding me? You won’t take the job?
Gus: Nope, I won’t. If you want to pay good money to take out a dog, then that’s your prerogative, but I have my standards!
[end of dialogue]
Our dialogue begins with Gus saying to Shirley, “Are you Shirley?” They haven’t met before; they’re meeting for the first time. Shirley says, “Yeah, thanks for agreeing to meet me here. I’m told you’re the best sniper in the business and you can be discreet.” A “sniper” (sniper) is someone who is very good at using a gun and can shoot people from a far away distance very accurately. So it’s a gunman (someone with a gun), or a gunwoman, who is very accurate. The army and the police might have a sniper. Shirley says to Gus I heard that, or I’m told that you can be discreet. “Discreet” means to be able to keep a secret very quietly, not tell anyone this information, not make yourself noticeable. Someone who is discreet keeps things to themselves – keeps things secret.
Shirley says, “I need a hitman who can do a job, and then make himself scarce.” A “hitman” is a person who is paid for killing other people – illegally, of course. They are hired by people to kill other people; that is a hitman. Shirley says, “I need a hitman who can do a job,” meaning who can get this particular killing done, and “then make himself scarce.” “To make yourself scarce” is a phrasal verb meaning to disappear quickly, to be difficult to find, to leave a place; that is making yourself scarce. If somebody says, “Make yourself scarce,” they mean get out of here, leave.
Gus says, “I’m your man,” a phrase we use to show that you can do what the other person wants you to do (someone who is going to hire you). For example, if someone says, “I’m looking for someone who is good with cars,” and you’re a mechanic (you’re a person who fixes cars), you might say, “I’m your man. You should hire me.”
Shirley says, “There’s someone who’s been a thorn in my side, keeping me up at night, and it’s time to take him out.” “A thorn in your side” is something that is very annoying, very unpleasant, something that is painful and won’t go away. Usually we use this expression to talk about a person who bothers you or a situation that causes you pain or annoys you somehow. A “thorn” (thorn) is something that you would find in a plant, or a flower like a rose. It’s like a needle, a small stick, that when you touch it, it hurts. So, a thorn in your side is something that hurts you. Shirley says that this person – this someone has been keeping her up at night, meaning not allowing her to sleep, “and,” she says, “it’s time to take him out.” “To take someone out” is an informal expression meaning to kill someone, to murder someone.
Well, this all sounds very serious! Gus says, “Taking care of problems is my specialty.” Your “specialty” is something that you do very well, something you’re very good at, something that you have made your profession – your job, your expertise. Well, Gus says that taking care of problems is his specialty; in this case, getting rid of people. He says, “I’ll need a down payment now and the balance when I finish him off.” A “down payment” (two words) is money that you pay before some service is finished; usually it’s a certain percentage of the total cost. So if you’re going to get your house painted and it’s going to cost you $4,000, the painter might tell you, “I need a down payment of 25%. You need to pay me $1,000 before I start.” This is a down payment. Gus wants a down payment and the balance when he finishes him off. The “balance” is, here, the rest of the money that you have to pay someone. So in the case of the painter, it would be the other $3,000. The expression “to finish someone off” also means to kill someone; it’s the same as “taking someone out.” “To finish off” means, here, just to kill someone.
Gus says, “We shouldn’t meet again, so I’ll tell you later where to make a drop.” “To make a drop means to put money or something else very valuable in a secret location so that someone else can come and get it later. This is something you will see in the movies. For example, if there’s a spy (someone who is collecting information about another country), the person might have someone in that country that is helping them, that is giving them information. That person inside the country may put the documents or the other information in a place, say in a park, and then leave, and then the spy comes and picks up that information. It can be used to talk about money; it can be used to talk about information or something else.
Shirley says, “All right,” meaning okay. Gus says, “Good. How will I be able to spot the target?” “To spot (something)” means to see and identify, to find something. If there’s a big crowd of people – lots of people, and you’re looking for one person you might say to your friend, “I can’t spot her,” and then when you see her you say, “Oh, I’ve spotted her now.” So it means to look, to see, and identify: say, “Oh, yeah. That’s the one.” The “target” is someone or something that you are looking for. We often use that word when we are going to attack that thing – we’re going to shoot that thing, that can also be a target. “Target” has a couple of different meanings in English, so take a look at the Learning Guide for some more explanation on that.
Gus says, “How will I be able to spot the target?” Shirley says, “Here’s a picture. He’s usually in the yard in the afternoons.” The “yard” here refers to the back or the front of the house where there is grass. We talk about the “front yard” and the “back yard.” The front yard is the space in front of your house that is part of your property, and the back yard is the space behind it.
Gus says, “You want me to kill a dog?!” Shirley has given him a picture of the target, and the target is a dog that she wants to have killed. Shirley says, “Right, he’s my neighbor’s dog and he keeps me up every night. Is that a problem?” meaning are you okay with that, does that mean you don’t want to kill him for me. Gus says, “You bet it is,” meaning yes, it is a problem. “Who do you think I am?” meaning what kind of person do you think I am. “People are disposable, but dogs? They’re a man’s best friend.” Something that is “disposable” is something that you can throw it away. Usually we use this word to talk about a thing, something you use once and then you throw it away, or something that is very inexpensive and cheap. He says that people are disposable, meaning well, it’s okay to get rid of people but not dogs. He says they’re man’s best friend, which is an old expression: “A dog is a man’s best friend.”
Shirley says, “Are you kidding me (are you joking)? You won’t take the job (you won’t do it)?” Gus says, “Nope (which is an informal of saying no), I won’t.” He says, “If you want to pay good money to take out a dog, then that’s your prerogative, but I have my standards!” “To pay good money” here means to spend a lot of money for a specific thing, especially when someone doesn’t think it’s a good idea. You may say, “I don’t know why he pays good money to buy that old car.” You’re saying he’s paying too much money or a lot of money for something that he shouldn’t be paying for. Gus says, “If you want to pay good money to take out (to kill) a dog, then that’s your prerogative.” “Your prerogative” is your choice, your decision. It’s often used when someone is not in agreement with you; they say, “Well, that’s your prerogative.” That usually means I don’t agree with your choice, but that’s your choice, you can do that if you want.
Gus says that he has his standards. Here, “standards” means rules that you follow that tell you what is right and wrong, what is good and bad. They are principles or rules that you believe in and you try to follow in your life. “Standard” has a couple of meanings in English however, so once again, take a look at that Learning Guide for some more explanations.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Gus: Are you Shirley?
Shirley: Yeah, thanks for agreeing to meet me here. I’m told you’re the best sniper in the business and you can be discreet. I need a hitman who can do a job, then make himself scarce.
Gus: I’m your man. Tell me about it.
Shirley: There’s someone who’s been a thorn in my side, keeping me up at night, and it’s time to take him out.
Gus: Taking care of problems is my specialty. I’ll need a down payment now and the balance when I finish him off. We shouldn’t meet again, so I’ll tell you later where to make a drop.
Shirley: All right.
Gus: Good. How will I be able to spot the target?
Shirley: Here’s a picture. He’s usually in the yard in the afternoons.
Gus: You want me to kill a dog?!
Shirley: Right, he’s my neighbor’s dog and he keeps me up every night. Is that a problem?
Gus: You bet it is. Who do you think I am? People are disposable, but dogs? They’re a man’s best friend.
Shirley: Are you kidding me? You won’t take the job?
Gus: Nope, I won’t. If you want to pay good money to take out a dog, then that’s your prerogative, but I have my standards!
[end of dialogue]
The script for this episode was written by someone whose specialty it is to write good scripts, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
sniper – someone who is very good at using a gun and shoots people from a hidden place where he or she cannot be seen
* How does the U.S. government protect the president from snipers?
discreet – very quietly, not drawing attention to oneself, keeping a secret
* She agreed to date him only if he would be discreet, not telling his friends about it.
hitman – a person who is paid for killing other people illegally
* The movie is about a hitman who makes $1 million each time he kills someone.
to make (oneself) scarce – to disappear; to make oneself unseen or very difficult to find; to leave a place
* When his parents are mad at him, he makes himself scarce until they have calmed down.
I’m your man – a phrase used to show that one can do what another person needs to have done
* If you ever need your house painted, Alexei is your man! He has all the tools and more than 10 years of experience painting houses.
a thorn in (one’s) side – something that is very annoying, unpleasant, or painful and will not go away
* That student has been a thorn in his teacher’s side all year, and she’ll be very glad when he graduates.
to take (someone) out – to kill someone; to murder someone
* What are the police doing to learn who took him out?
specialty – expertise; something that one is very good at and has made his or her profession or job
* He’s a good farmer and his specialty is growing tomatoes.
down payment – money that is paid initially, before a service is provided, usually as a percentage of the total cost
* She had to make a $4,000 down payment on the new car.
balance – remainder; the difference between the total cost and the down payment; money that still needs to be paid
* Jill asked her client to pay 40% at the beginning of the project, with the balance due when the work was finished.
to finish (someone) off – to kill someone after having hurt or injured them already; to finish killing someone
* In the movie, the bad guy told his friends to hurt the mafia leader, but not to finish him off until later.
to make a drop – to put money in a secret location so that someone can come and get it later
* The kidnapper told the child’s parents to make a drop on the corner of 7th Avenue and Swanson Street.
to spot – to find; to see and identify
* You’ll be able to spot her in the crowd because she’s wearing a big orange hat.
target – something or someone that one is looking for or aiming at, especially to attack
* How often do you practice shooting at targets?
disposable – something that can be thrown away after it is used only once; something that is inexpensive and can be replaced easily
* We forgot to pack our camera, so we bought an inexpensive disposable camera for our vacation.
to pay good money – to use one’s money for a particular purpose, especially when the speaker thinks it is not a good use of one’s money
* I can’t believe that anyone would pay good money to buy that desk. It’s so ugly!
prerogative – one’s choice or decision, especially when other people may not agree with it
* Dropping out of school in your prerogative, but I think it’s a bad decision.
standards – the principles or rules that one follows about what is right or wrong, good or bad
* I’m not prepared to take a job at half the salary of my last job. I have my standards.
Comprehension Questions
1. How does Gus want Shirley to pay him?
a) She should pay him all the money right away.
b) She should pay him part of the money now, and part of it later.
c) She should pay him all the money after he’s done.
2. Why doesn’t Gus want to kill the dog?
a) Because dogs make too much noise when they are shot.
b) Because the dog in the photo is his best friend.
c) Because he thinks dogs are more valuable than people.
Answers at bottom.
What Else Does It Mean?
target
The word “target,” in this podcast, means something or someone that one is looking for or aiming at, especially to attack: “If you can throw the ball and hit the target, you get a prize.” A “target” can also be a goal, or something that one wants to reach or achieve: “They have a sales target of $40,000 per month.” A “target audience” or “target market” is the group of people that a company wants to reach through marketing so that the people buy its products or services: “The toy company’s target market is young girls, ages 4-6.” Finally, when one is translating, the “target language” is the language that one is translating a text into: “We need to find someone to translate this brochure into our target languages of German and Italian.”
standards
In this podcast, the word “standards” means the principles or rules that one follows about what is right or wrong, good or bad: “It’s going to be very difficult for her to find a man who meets all her standards.” A “standard” is also a level of acceptable quality: “The university has very high standards for admission, so only the best students are invited to study there.” In music, a “standard” is a song that is sung or performed by many people: “The Autumn Leaves is a well-known jazz standard.” Finally, the phrase “standard of living” is used to talk about people’s lifestyles, especially how comfortable they are and what they can buy with the money they have: “Which countries have the highest standard of living?”
Culture Note
Hiring a hitman is an “extreme measure” (something that is too strong) for dealing with a neighbor’s noisy “pet” (an animal that lives with people for fun and enjoyment, not for meat, milk, or clothing). Fortunately, Americans have many other options that don’t involve hiring a hitman.
First, you can talk to your neighbor. Tell him or her that the noisy pet is an “unwelcome” (not wanted) “distraction” (something that takes one’s attention away from other, more important things). Hopefully the neighbor will do something about it.
If the neighbor doesn’t do anything and the pet continues to be too noisy, you can call the police and “report” (officially tell the authorities about something) the “noise violation” (something that is so loud that it “disrupts” (makes unpleasant) the residential neighborhood). If the police agree that the pet is a noise violation, they may “fine” the neighbor, making him or her pay money and fix the problem.
Another option is to call “animal control,” which is the local government agency that deals with animals in the city. When someone “files a complaint” (officially says that there is a problem), animal control will “investigate” (learn more about) the situation and may take the pet away from the owner. The pet might be taken to the “pound” (a large building where there are many animals that do not have owners). If the animal is “adopted” (taken into a family) by another person, it will go to their home. If the animal is not adopted, it might be “put down” (killed) to make room for more animals.
Comprehension Answers
1 - b
2 - c