= 0485
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 485: Being Clumsy.
This is English as a Second Language Podcast episode 485. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
Our website is eslpod.com. Go there and download a Learning Guide for this episode, an 8- to 10-page PDF file we provide for all of our current episodes that will help you improve your English even faster.
This episode is called “Being Clumsy.” “To be clumsy” means to be unable to control your body very well; you are always falling down or having accidents. That’s being clumsy. It’s a dialogue between Edward and Bella about being clumsy, about being someone who isn’t able to dance very well. Let’s get started.
[start of dialogue]
Edward: Would you dance with me?
Bella: Me? I’d like to, but I don’t dance.
Edward: Why?
Bella: I have two left feet. I’m so clumsy, first I’d step all over your feet, and then I’d stumble all over the dance floor.
Edward: I don’t believe that. I bet you’re very graceful on the dance floor. You wouldn’t stumble; you’d glide across that floor.
Bella: I’m the most uncoordinated person alive. When I was little, I was even more awkward. My mother hated taking me shopping because I was so accident-prone. Everywhere we’d go, I was like a bull in a china shop. I’m not like Rosalie. Look at her. She’s so elegant.
Edward: Rosalie has nothing on you. Dance with me and I promise to catch you if you trip.
Bella: What if I step all over your feet?
Edward: You won’t get the chance. My feet will be moving so quickly, I will dazzle you with my agility and finesse.
Bella: Okay, you asked for it!
[end of dialogue]
The dialogue begins with Edward asking Bella, “Would you dance with me?” Bella says, “Me (you’re asking me)? I’d like to (I would like to dance), but I don’t dance,” she says. Edward asks, “Why?” Bella makes a joke and says, “I have two left feet.” The expression “to have two left feet” in this case means to be a bad dancer, to not know how to move your feet when you are dancing. Of course, most of us have one left foot and one right foot, so having two left feet is a funny way of saying that you can’t move very easily – you can’t dance very well. Bella says, “I’m so clumsy.” “To be clumsy” means to not be able to move your body the way you want it to, this also results in you falling down, or hitting something accidentally, and so forth. Bella says, “I’m so clumsy, first I’d step all over your feet,” meaning my foot would go on top of your foot accidentally, “then I’d stumble all over the dance floor.” “To stumble” means to move awkwardly, to hit your foot against the ground or something else that makes you almost fall down. That’s to stumble; to stumble can also be to almost fall. Bella says that she would stumble all over the dance floor if she tried to dance.
Edward says, “I don’t believe that. I bet you’re very graceful on the dance floor.” “To be graceful” means to move very smoothly, very elegantly, we would say. Someone who’s a good dancer is very graceful, or a good ballerina (someone who dances ballet) can be graceful. Edward says, “You wouldn’t stumble; you’d glide across that floor.” “To glide” (glide) means to move smoothly and beautifully with very little effort, making it look very easy. “Glide” is also a verb we could use if you were on ice and you were skating, you had special shoes that had blades on the bottom of them that allowed you to move across the ice quickly. That’s gliding across the ice. Here, Edward means that Bella would move across the floor as if she were gliding on ice.
Bella says, “I’m the most uncoordinated person alive.” “Uncoordinated” is another word for clumsy, someone who can’t control the way their body moves very well. Bella says, “When I was little, I was even more awkward.” “Awkward” is uncomfortable, difficult, something that doesn’t seem quite right. She says, “My mother hated taking me shopping because I was so accident-prone.” “To be prone (prone) to do (something)” means that you are likely to do something. So to be “accident-prone” means that you are likely to have an accident, you are the kind of person that has accidents frequently. She says, “Everywhere we’d go, I was like a bull in a china shop.” China is a country, but “china,” in English, also refers to a type of dish or cup that is made of a very fine and delicate material. My mother used to have a good set of china; these were the plates and cups that we would use for formal occasions. For Christmas or for some family party, she would bring out the china; the rest of the year, we would just eat on the floor – no, we would eat on regular plates! But china is the very nicest, the very finest kind of plate and cup that you would use for eating. A “bull” is a male cow, and a bull can be considered rather wild. So you can imagine if you had a store – a shop that had china in it and a bull came in, well the bull would probably break a lot of the china. So “to be a bull in the china shop” is an old expression used to describe somebody who breaks things accidentally, in this case. More generally, it can mean someone who isn’t very careful.
Bella says, “I’m not like Rosalie. Look at her. She’s so elegant.” “Elegant” is similar to graceful; it’s moving beautifully, in control of your own body movements. Edward, however, says, “Rosalie has nothing on you.” “To have nothing on (someone)” means not to be better than someone else, not to be able to compete with someone else, or someone who is not as good as you. So Edward is saying Rosalie is not as good of a dancer as you are. Edward says, “Dance with me and I promise to catch you if you trip.” “To trip” (trip) means to fall down, usually because you hit your foot on something that you didn’t see or expect. Both “trip” and “to have nothing” have several different meanings in English; take a look at our Learning Guide for some additional explanations of both of those expressions.
Bella says, “What if I step all over your feet (what if I step on your feet)?” Edward says, “You won’t get the chance (you won’t get the opportunity). My feet will be moving so quickly, I will dazzle you with my agility and finesse.” “To dazzle” (dazzle) means to impress someone, to make a good impression, often to surprise someone at how good you are. So, Edward is saying I will dazzle you – I will surprise amaze you with my agility and finesse. “Agility” (agility) is the ability to move quickly and easily, to have a lot of flexibility. Girls who participate in gymnastics, for example, need a lot of agility – a lot of flexibility. “Finesse” is to have a certain style and skill, to be able to do something in a very special way, to have a certain class about what you are doing; to be very refined, for example. Edward is saying that he is going to dance so well that Bella won’t have the opportunity to step on his feet accidentally.
Bella says, “Okay, you asked for it!” That expression, “you asked for it,” means I’m going to do what you want me to do but you may not be happy about what happens. But you are insisting on it – you are demanding that I do it, so I will go ahead and do it, but you’ll probably be sorry that you asked me to do it.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Edward: Would you dance with me?
Bella: Me? I’d like to, but I don’t dance.
Edward: Why?
Bella: I have two left feet. I’m so clumsy, first I’d step all over your feet, and then I’d stumble all over the dance floor.
Edward: I don’t believe that. I bet you’re very graceful on the dance floor. You wouldn’t stumble; you’d glide across that floor.
Bella: I’m the most uncoordinated person alive. When I was little, I was even more awkward. My mother hated taking me shopping because I was so accident-prone. Everywhere we’d go, I was like a bull in a china shop. I’m not like Rosalie. Look at her. She’s so elegant.
Edward: Rosalie has nothing on you. Dance with me and I promise to catch you if you trip.
Bella: What if I step all over your feet?
Edward: You won’t get the chance. My feet will be moving so quickly, I will dazzle you with my agility and finesse.
Bella: Okay, you asked for it!
[end of dialogue]
Our dazzling script was written by our graceful and elegant writer, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to have two left feet – to be a bad dancer, not knowing how to move one’s feet
* He likes to watch people dance, but he never joins them because he has two left feet.
clumsy – moving awkwardly; not being able to control the movements of one’s body, or not being able to make smooth movements, often accidentally hitting things or falling down
* Ian is so clumsy that he regularly drops and breaks dishes when he tries to wash them.
to stumble – to move awkwardly, hitting one’s foot against the ground or another object so that one almost falls down
* Watch where you’re going, or you might stumble over these rocks.
graceful – elegant; moving very smoothly and in control of one’s body
* Most ballerinas are very graceful, even when they aren’t dancing.
to glide – to move smoothly and beautifully with very little effort, making it look easy
* The artist glided through the art gallery, making small adjustments to his work and making sure that everyone was having a good time.
uncoordinated – clumsy; not in control of the way one’s body moves; not able to do physical things well
* Young always wanted to do gymnastics, but he is too uncoordinated.
awkward – uncomfortable and difficult; out of place; not able to do something as other people do it
* Helena always feels awkward leaving voicemail messages for people when they don’t answer their phone.
accident-prone – likely to have an accident; with a high probability of having an accident
* Trevor is a very accident-prone kid. By the time he was 10 years old, he had already broken seven bones and been in the hospital several times.
like a bull in a china shop – a phrase used to describe a person who accidentally hits things, making them break
* Lucille, I’m sorry I broke the vase in your living room. It was an accident. Sometimes I’m like a bull in a china shop.
elegant – graceful; moving beautifully and in control of one’s movements
* Pilar is always so elegant that when she walks into a room, all the men turn to look at her.
to have nothing on (someone) – to not be better than someone else; to not be able to compete with someone else; to look bad when compared to someone else
* Yes, Seung got the job offer, but he has nothing on you. You’re very well qualified with a good education and years of professional experience.
to trip – to fall down, usually because one accidentally hit something with one’s foot
* Be careful or you might trip on the icy streets.
to dazzle – to amaze; to impress someone favorably; to make a good impression on someone; to surprise someone in a good way
* The professor dazzled the class with a fun and exciting lecture on what is normally a boring subject.
agility – ability to move easily and quickly; flexibility; ability to control the movements of one’s body very well
* Athletes have more agility than other people do.
finesse – style and skill; one’s special way of doing something well
* The politician answered the questions with such finesse that many people stood up and clapped even if they didn’t agree with his answers.
Comprehension Questions
1. Which of these words could be used to describe someone who has two left feet?
a) Graceful.
b) Awkward.
c) Elegant.
2. What does Edward mean when he says, “Rosalie has nothing on you”?
a) Rosalie hasn’t told Edward anything about Bella’s dancing.
b) Rosalie is a much better dancer than Bella.
c) Rosalie isn’t as good a dancer as Bella is.
Answers at bottom.
What Else Does It Mean?
to have nothing on (someone)
The phrase “to have nothing on (someone),” in this podcast, means to not be able to compete with someone else, or to look bad when compared to someone else: “Jewel is a great runner who won all the races last year. The other runners on the team have nothing on her.” The phrase “to have nothing to do with (something)” means to not want to become involved in something, or to want to distance oneself from something: “You can have a big party while our parents are gone, but I’ll have nothing to do with it. I don’t want to get in trouble.” Finally, the phrase “there’s nothing like (something)” means that something is very good or enjoyable: “There’s nothing like swimming in the lake on a hot summer day.”
trip
In this podcast, the verb “to trip” means to fall down, usually because one accidentally hit something with one’s foot: “Camille is worried that she might trip when she walks onto the stage.” The phrase “to trip an alarm” means to turn on an alarm (a loud noise made by a machine to get attention) by accident: “The thief tripped the car alarm and ran away before the police arrived.” The phrase “to trip up” means to make a mistake: “Nicolas tripped up when he was asked to explain the government’s new energy policy.” Finally, when used informally, the verb “to trip” can mean to see strange things and feel oddly because one is taking illegal drugs: “The teenagers were tripping when the police arrived at their house.”
Culture Note
One of the most famous dancing “pairs” (a group of two people) in American culture is Fred Astaire and Ginger Rogers. They were both actors, singers, and dancers in many American “musical films” (movies with a lot of songs and dancing). They made 10 films together between 1933 and 1940. Some of the most popular films include Top Hat (1935), Swing Time (1936), and Shall We Dance (1937). These films were very “profitable” (made a lot of money) for the “studios” (the companies that make movies).
Most film “critics” (people whose job is to say what they do and don’t like about movies) say that Fred was the better dancer. He had studied dance for many years and performed even as a young child. Ginger was a “so-so” (average; not really good, but not really bad) dancer, but a very good actress who knew how to make it look as if dancing with Fred were a “thrilling” (very exciting) experience. Although Ginger wasn’t a good “technical” (knowing all the steps) dancer, most people believe that she was Fred’s best dancing partner throughout his “career” (the years he spent making movies).
Fred had “solo performances” (dancing on his own, without another person) in many of the movies, but Ginger did that only once. Usually they danced together.
The dancing pair was so popular that many people simply refer to them as “Fred and Ginger.” They “passed away” (died) in 1987 and 1995, but even today, great dancing pairs are still compared to Fred and Ginger.
Comprehension Answers
1 - b
2 - c