= 0498
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 498: Joking and Making Fun of People.
This is English as a Second Language Podcast episode 498. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of everything we say on this episode. All that is available on our website.
This episode is called “Joking and Making Fun of People.” It’s a dialogue between Dmitry and Charlene. Let’s get started.
[start of dialogue]
Dmitry: Stan is really miffed at you. All of that teasing at lunch really upset him.
Charlene: What? I was just poking fun at him for trying to hit on the new, young receptionist.
Dmitry: You called him an old goat.
Charlene: I said that tongue in cheek. If he didn’t find that funny, then he can’t take a joke.
Dmitry: What about last week when you told that joke about fat people trying to dance and you made him the butt of the joke?
Charlene: Everybody knows I’m the class clown around here, and I make wisecracks about everybody. Nobody else is as thin-skinned as Stan.
Dmitry: I wouldn’t be so sure about that. I suggest you watch your back. The next joke may be on you.
Charlene: Why? What have you heard?
Dmitry: Oh, nothing. I just think it may be time for some payback – big time!
[end of dialogue]
Dmitry says to Charlene, “Stan is really miffed at you.” Stan is a man’s name. “To be miffed (miffed) at (someone)” means to be mad at someone, to be upset or angry with someone. “Miffed” usually is a little less severe than mad; it’s a little less serious, perhaps. Dmitry says, “All of that teasing at lunch really upset him.” “To tease” (tease) as a verb means to make jokes about someone, but in a friendly way; to laugh at something someone has done, but you’re not trying to be mean. It’s not something that you are doing to hurt the other person. “Tease” actually has a couple of different meanings; take a look at our Learning Guide for some additional explanations of that term.
Charlene says, “What?” She’s surprised. “I was just poking fun at him.” “To poke (poke) fun at (someone)” is an expression that means to make jokes about someone. However, it could be in a friendly way like teasing, but it might also be in an unfriendly way in order to hurt that person. The expression can be used for both cases, it just depends on the context. Charlene, however, believes that she was just teasing him, and she uses the expression “to poke fun at him” in a friendly way.
Why is she poking fun at him? Well, because Stan was trying to hit on the new, young receptionist. “To hit on (someone)” is a two-word phrasal verb to say something to another person that you are romantically interested in. When a man comes up to a woman and says, “Come here often?” meaning do you come to this place often, he might be hitting on her. He might be trying to get her romantically interested in him. Of course, that’s not a very good way to start. In fact, that expression “Come here often?” is used now as a joke; it’s a terrible way to try to hit on a girl or a woman. I know, I’ve tried it; it hasn’t worked very well! “To hit” is a verb that has many different meanings in English, depending on the other words used – the other prepositions (the other phrasal verbs). Take a look at our Learning Guide for an explanation of a few of those.
Poor Stan was trying to hit on the young, new receptionist. A “receptionist” is a person in an office whose job it is to answer the phone and to welcome people as they walk into the office, if they are people who are visiting. So, Dmitry says, “You called him an old goat.” That’s what Charlene said about Stan. A “goat” is an animal, not a particularly attractive animal, so most people would consider that an insult, to call someone “an old goat.” Charlene says, “I said that tongue in cheek.” The expression “tongue in cheek” (cheek) means as a joke, not seriously, in a joking way. “She made a tongue in cheek comment about wanting to go swimming” – she wasn’t serious, she was joking. In this case, Stan did not think it was a joke. Charlene goes on to say that if he didn’t find that funny, then he can’t take a joke. “To take a joke” or “to be able to take a joke” means that you can laugh at yourself, you can laugh at the world. “To not be able to take a joke” means that you are too serious, that you don’t find something funny; you can’t find the humor in things.
Dmitry says, “What about last week when you told that joke about fat people trying to dance and you made him the butt of the joke?” Dmitry is “bringing up,” or bringing to Charlene’s attention another example of something that she said that was mean, that wasn’t just teasing. She made a joke about people who are overweight trying to dance, and she made Stan the butt (butt) of the joke. The “butt of a joke” or “the butt of the joke” is the person about whom a joke makes fun; it is the person who is being laughed at, and here, it usually isn’t in a friendly way.
Charlene says, “Everybody knows I’m the class clown around here.” The “class clown” is an expression that comes from school, where there is someone in your class that always makes jokes, that is always trying to be funny. When you have a group of students, there’s usually a couple of people who always want to be the funny one, the ones making jokes; this is the “class clown.” A “clown” is someone who tries to make other people laugh, especially young children, usually by putting on a strange costume (strange clothes) and painting their face. Here, it’s more used as a general expression to be the person who tries to be funny in the group, in this case at the company where Charlene and Dmitry work.
Charlene says, “I make wisecracks about everybody.” A “wisecrack” (wisecrack – one word) is a joke; it’s a funny comment, something that is supposed to be clever and funny. She says that nobody else is as thin-skinned as Stan. To have “thin skin” is an expression that means to be easily offended or upset, someone who can’t laugh at themselves. Or, it could also mean someone who cannot take criticism without being personally hurt. The opposite is “thick skin.” If someone says, “He has a thick skin,” they mean that he’s not bothered by criticism or by jokes; he doesn’t take it personally.
Charlene is saying that, in this case, Stan is “thin-skinned.” Well, Dmitry says, “I wouldn’t be so sure about that,” or I wouldn’t be so sure about that. He says, “I suggest you watch your back.” The expression “to watch your back” means to be cautious or to be careful, to try to protect yourself from something that might happen to you. The idea is that other people may try to hurt you or attack you. He says, “The next joke may be on you.” When a joke is “on someone,” that means it’s about someone or that person is going to be the butt of the joke, the person that everyone else will be joking about.
Dmitry is saying to Charlene, “The joke may be on you” – you may be the person that we laugh at. Charlene says, “Why? What have you heard?” Dmitry says, “Oh, nothing. It just may be time for some payback.” “Payback” (one word) means revenge, something that you do to another person to get even, something bad you do to another person because they did something bad to you. That’s called “payback.” Dmitry then uses the expression “big time.” He says, “I just think it may be time for some payback – big time!” “Big time” is an informal expression (not something that you would want to use at work necessarily, but among friends) that means something important, something significant, in a big way. For example, you go to Las Vegas and you gamble, because Las Vegas is famous for people going to gamble their money on cards or other games, and you lose a thousand dollars. Someone asks you, “Did you lose any money in Las Vegas?” and you say, “Oh yeah, big time!” meaning a lot, in that case.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dmitry: Stan is really miffed at you. All of that teasing at lunch really upset him.
Charlene: What? I was just poking fun at him for trying to hit on the new, young receptionist.
Dmitry: You called him an old goat.
Charlene: I said that tongue in cheek. If he didn’t find that funny, then he can’t take a joke.
Dmitry: What about last week when you told that joke about fat people trying to dance and you made him the butt of the joke?
Charlene: Everybody knows I’m the class clown around here, and I make wisecracks about everybody. Nobody else is as thin-skinned as Stan.
Dmitry: I wouldn’t be so sure about that. I suggest you watch your back. The next joke may be on you.
Charlene: Why? What have you heard?
Dmitry: Oh, nothing. I just think it may be time for some payback – big time!
[end of dialogue]
The script was written for this episode by our wisecracking writer, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
miffed – angry, annoyed, and offended; upset
* Leanne was really miffed when her husband didn’t notice her new haircut.
to tease – to make jokes about someone else, but in a friendly way; to laugh at another person or at what another person has done
* Uncle Logan is always teasing his young nieces, asking them if they’re dating anyone in their elementary school.
to poke fun at (someone) – to laugh at another person or at what another person has done, especially when it isn’t very nice and hurts that person’s feelings
* Please don’t poke fun at Grace’s writing. She’s trying as hard as she can.
to hit on (someone) – to say something to another person that shows that one is interested in having a romantic or sexual relationship, especially when one doesn’t know that other person
* How many men hit on you at the bar last night?
receptionist – a person whose job is to answer the phone and welcome people as they walk into an office
* When you get to the office, please tell the receptionist that you have a 10:00 meeting with Ms. Lazonski.
tongue in cheek – in a joking way; as a joke; not seriously
* She made a tongue-in-cheek comment about wanting to go skydiving, but I don’t think she really meant it.
to not be able to take a joke – to not see the humor in something; to not think that something is funny, especially when talking about a joke that hurts a person’s feelings; to be mad or offended by something that one said while trying to be funny
* Ricky put a frog in his teacher’s desk, but she can’t take a joke, so she got really mad at him.
the butt of the joke – the person whom a joke makes fun of; the person who is being laughed at
* Walton is always making jokes about other people, but he hates being the butt of the joke himself.
class clown – a person who is always making jokes and is doing silly or funny things; the funniest person in a group of people
* Howard was the fifth child in a very large family, and he became the class clown as a way to get attention.
wisecrack – a joke; a funny comment; something that is clever and funny
* If you make a wisecrack about bombs at the airport, you might be arrested.
thin-skinned – very easily offended or upset; without the ability to laugh at oneself
* Please don’t make jokes about Marlo’s cooking. She’s very thin-skinned about it.
to watch (one’s) back – to be cautious or careful; to try to protect oneself from something that might happen unexpectedly
* If you walk alone in the streets at night, watch your back and try to be aware of the people around you.
a joke may be on (someone) – a phrase used to show that one was trying to make a joke about someone else, but something changed and suddenly the joke was about oneself instead
* Sandra is always making jokes and tricking us, but yesterday we were finally able to trick her. We said, “Ha ha, this time the joke’s on you!”
payback – revenge; something that one does to get even with another person; something bad or mean that one does to another person because that person did something bad or mean to oneself earlier
* When Sallie shared Rebecca’s secret with the other students, Rebecca told everyone about Sallie’s own secret as payback.
big time – in a big, important, or significant way
* He got into a lot of trouble – big time – and had to go to jail for eight years.
Comprehension Questions
1. Who was the butt of Charlene’s joke?
a) Stan.
b) The receptionist.
c) Dmitry.
2. What does Charlene mean when she says that Stan is “thin-skinned”?
a) He has pale skin and gets sunburned very easily.
b) His skin has stretched because he’s very fat.
c) He doesn’t like it when people make jokes about him.
Answers at bottom.
What Else Does It Mean?
to tease
The verb “to tease,” in this podcast, means to make jokes about someone else, but in a friendly way: “Stop teasing your sister or you’ll make her cry.” When talking about animals, the verb “to tease” means to bother or annoy an animal: “If you keep teasing that dog, it might bite you.” The phrase “to tease (one’s) hair” means to brush or comb it in the direction that is opposite to the way it normally grows, to make it seem bigger or as if one has more hair: “Many women teased their hair in the 1980s, but it isn’t as popular now.” The phrase “to tease (something) out of (someone)” means to get someone to share a secret or some information that shouldn’t be shared: “How did you tease all the details out of Jackie about your surprise birthday party?”
to hit on
In this podcast, the phrase “to hit on (someone)” means to say something to another person that shows that one is interested in having a romantic or sexual relationship, especially when one doesn’t know that other person: “Some men try to hit on women by asking, ‘Do you come here often?’” The phrase “to hit (someone) up for (something)” means to ask someone for something, especially for money: “How much money did he hit you up for this time?” The phrases “to hit the sack” and “to hit the hay” mean to go to bed to sleep: “I’m really tired. All I want to do is go home and hit the sack.” Finally, the phrase “to hit the nail on the head” means to say something that is completely correct: “You really hit the nail on the head in your presentation this morning. Congratulations!”
Culture Note
Many Americans like to watch TV shows that make them laugh. One very well known TV show with “practical jokes” (something that one does to surprise another person or make him or her look silly) is called Candid Camera.
The word “candid” means truthful and honest, even when it is about something unpleasant or uncomfortable. Candid Camera “captures” (records) people’s candid behavior in unusual situations. The show uses “hidden cameras” (a camera that cannot be seen, so people don’t know they’re being filmed) to see what “ordinary” (normal) people do when unexpected things happen.
For example, in one episode, the show used a “security guard” (a person whose job is to make sure other people are safe) at an airport. He asked the passengers to go through the “x-ray machine” (a machine that can see through bags and skin), even though normally only bags go through those machines. It was funny to see people’s “reactions” (how people responded).
In another episode, people sat behind a desk that has been “modified” (changed) so that the drawers opened automatically as soon as they were closed. The camera captured people’s reactions, which “ranged” (varied) from laughter about the situation to frustration with the desk.
Many other practical joke shows have copied the show’s “format” (the style of the show). Girls Behaving Badly is a similar show, but only women are “playing tricks” (doing funny things). One show, Punk’d, plays practical jokes on “celebrities” (famous people, especially musicians and actors), and now the phrase “to punk (someone)” is used informally to mean to play a trick on someone.
Comprehension Answers
1 - a
2 - c