= 1776
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 471.
This is English as a Second Language Podcast’s English Café episode 471. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide – an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English, including a complete transcript of everything that we say on the Café. And why not like us on Facebook at facebook.com/eslpod.
On this Café, we’re going to talk about another famous American, by the name of John Brown. We’re also going to talk about high school reunions. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café talking about a man by the name of John Brown. John Brown was an “abolitionist.” An “abolitionist” (abolitionist) is a person who believes in ending, or stopping, the practice of “slavery.”
“Abolitionist” comes from the verb “to abolish,” which means to get rid of something, to end something. John Brown was not your typical abolitionist. When we think of the abolitionist movement – the group of people who tried to end slavery in the United States during the nineteenth century – normally we think of people who use the political process. But John Brown believed in using violence to end slavery, and that’s why he is famous in American history, in part.
Brown has an interesting personal history. He was born in 1800 in the state of Connecticut, which is located in the northeast part of the United States. His family, and his father in particular, were very much against the practice of slavery. They were also very vocal about it. When someone is “vocal” (vocal) about something, they complain loudly. They talk about it, they tell other people, they write letters, and so forth. Someone who’s very vocal about something is someone who is always or often giving his opinion about this topic. Well, the Brown family was very vocal against slavery.
John Brown had some personal experience with slavery. He once saw a young African-American slave being very badly treated by the owner of the slave. It is believed by some historians that this experience of seeing a slave being punished influenced Brown’s own ideas about slavery and his opposition to it.
Brown moved around quite a lot during his lifetime. He lived in Ohio, Pennsylvania, Massachusetts, and New York. He had a lot of different jobs, including being a farmer, but he wasn’t very successful at any of them. (Sounds like my life story.) This meant that he and his very large family often had very little money. In addition to farming, Brown also worked as a tanner. A “tanner” is a person who works with animal skins to make them soft in order to turn them into, or use them for, clothing and furniture.
Brown got married at the age of 20 to a woman by the last name of Lusk, and together they had seven children. Unfortunately, Brown’s wife died in 1832, while giving birth to one of their children. This, of course, was not uncommon during this time period. Brown married again the very next year to a woman by the name of Day, and together they had 13 children. So, in total, Brown was the father of 20 children. Of the twenty, 11 lived to become adults. Once again, it was not uncommon for children to die before reaching adulthood during this period.
Even though Brown was not a very good businessman, he was very successful in supporting and promoting the cause of abolition throughout his life. He was actively involved in several different organizations that worked to end slavery in the United States. Just to be clear, “slavery” (slavery) is when one person owns another person – when one person is the property of another person. Slavery was abolished in the United States completely after the Civil War during the 1860s. But before that time, slavery was legal, and John Brown was one of those working to abolish it.
One of the things that Brown did was get involved in something known as the “Underground Railroad.” A “railroad” is a means of transportation using trains. “Underground” usually means below the ground, underneath the ground. However, the term “underground” is sometimes also used for something that is not noticed by other people or something that is perhaps even illegal. The “underground economy,” for example, could refer to people who work without the government knowing about it and without paying taxes.
The “Underground Railroad” wasn’t a railroad at all. It was an organization of white people, mostly from the North, as well as African Americans who had escaped slavery or who were freed from slavery, who worked together to try to get slaves out of the American South. Specifically, the underground railroad smuggled slaves from the South to the North.
Now you have to understand, in the South – the southern part of the United States – slavery was legal. In most states in the northern part of the U.S. during this time period before the Civil War, slavery was illegal. So these members of the Underground Railroad were trying to get blacks out of the South, out of the southern states, and into the North – into the northern states, states like Massachusetts and New York and Ohio.
“To smuggle” (smuggle) means to transport an object or a person illegally. You could smuggle drugs into the United States; you could bring in illegal drugs into the United States. Millions of people have done that. Well, we’re not talking about drugs, we’re talking about people. Of course, people are also smuggled into countries – brought into countries illegally without the government knowing about it.
In the case of the Underground Railroad, since the slaves were technically property of their owners, it was illegal for them to leave without the permission of their owners. However, the people in the Underground Railroad helped the slaves escape – to leave their owners and to travel to the northern states. Once they were in the North, they could live as free men and women.
The Underground Railroad was incredibly successful according to many people, many historians. It’s believed that over a hundred thousand slaves were helped to escape to the North between 1810 and 1850. What happened in 1850, however, changed the operations of the Underground Railroad.
In 1850, the U.S. Congress – the national government – passed a law called the “Fugitive Slave Act.” A “fugitive” (fugitive) is a person who is being held as a prisoner but who then escapes and is now hiding from people who are trying to find him. There was a famous movie with Harrison Ford called The Fugitive, based on a television series by the same name. (It’s one of my favorite movies, by the way, The Fugitive. I’ve seen it, oh, probably about 47 times – something like that.)
Anyway, the fugitives in this case were not prisoners like Harrison Ford in the movie; rather, they were slaves who were owned by their owners in the South and had escaped. The Fugitive Slave Act said that any escaped slave that was found in any state in the United States – including the northern states, where slavery was illegal – could be brought back to the owner of the slave in the South. This meant that slaves who escaped on the Underground Railroad were no longer safe in northern states.
Escaped slaves in fact tried to go to Canada in order to be safe after the passage of the 1850 Fugitive Slave Act. Most, however, were forced to stay where they were and tried not to get caught by people who were trying to find them and bring them back to their owners. These people who went out to find escaped slaves were called “slave hunters.”
Normally the verb “to hunt” means to go and find something or someone, usually an animal, but here, the slave hunters were looking for humans – escaped slaves that they could bring back to their owners. The slave owners paid the slave hunters rewards for bringing back escaped slaves. A “reward” (reward) is something, usually money, that is given as thanks to someone for helping another person.
On January 15th, 1851, the year following the passage of the Fugitive Slave Act, John Brown “founded,” or started, an abolitionist organization called the League of Gileadites. Now, the word “Gileadites” refers to people from Gilead. Where was Gilead? Well, Gilead was the name of a place that is mentioned in the Bible, in the Old Testament of the Bible, in the Jewish Scriptures – specifically, in the book of Jeremiah.
Gilead was a place that was famous for a “balm” (balm). A balm is some sort liquid that you put on your skin, either to take away the pain or to heal some problem on your skin. The balm of Gilead was considered to be medicinal. It was supposed to cure your illness, to take away your pain. The liquid balm came from a tree, from what we would call the “sap” (sap) of a tree. It was quite expensive and quite valuable during this time period.
In the Hebrew holy books, the balm of Gilead was a symbol of something that would cure you, that would make you better. During the middle part of the nineteenth century, this notion of a balm of Gilead was used as a symbol for getting rid of the pain and suffering that the African-American community was experiencing. In fact, there was a religious song, a hymn, called “There Is a Balm in Gilead” which talks about this same concept. So, it’s significant that John Brown used this biblical reference, this name of “Gilead,” in the name of his organization.
The abolitionists were for the most part motivated by religious reasons, and it was religious organizations that were most active in trying to get rid of slavery in the United States, as was true in other countries as well. I should mention that there was a specific association with Gilead also with freedom. In the Bible, there is a man named Gideon who is told by God to go to a place called Mount Gilead, and there he would lead the people of Israel to freedom. The purpose of the League of Gileadites was to lead the slaves to freedom.
Beginning in 1855, Brown began using violence to help slaves escape. He became very involved in a fight in the state of Kansas, in the central part of the U.S., about whether or not the new territories, the new areas of Kansas and Nebraska, would allow slavery. It was decided that these new territories would allow slavery, and this caused John Brown and the abolitionists to be very angry. In 1856, they actually attacked a group of people in Kansas where five people who supported slavery, who were in favor of slavery, were killed.
A few years later, in October of 1859, Brown took 21 of the members of his group and attacked a government arsenal. They raided a government arsenal located in Harpers Ferry, Virginia. An “arsenal” (arsenal) is a place where weapons are stored. The U.S. government had a place where it was keeping guns and other weapons. John Brown and his followers raided the arsenal. “To raid” (raid) means to suddenly attack and enter a place.
Brown’s attack on the Harpers Ferry Arsenal was not successful. Within about two days, the local farmers and the military – led, interestingly enough, by a general who later became famous in the Civil War, Robert E. Lee – killed or captured most of Brown’s men. John Brown himself was captured – that is, he was taken alive. He was then given a trial and sentenced to death. In December of 1859, he was executed in Virginia. “To be executed” (executed) means to be killed by the military or the government because you have committed some crime.
Brown’s attack on Harpers Ferry was not successful in the way that Brown had hoped, but it was successful in another way. Brown became a martyr for the cause of abolitionism. “To be a martyr” (martyr) means to die for some belief or some principle. Many historians believe that in many ways, Brown’s actions at Harpers Ferry inspired other abolitionists all across the country to get actively involved in fighting against slavery. In fact, someone wrote a song called “John Brown’s Body” that was sung by the northern troops during the Civil War.
The name of John Brown then became associated with the abolitionist movement, and even into the twentieth century, people were still talking about John Brown. One of the great American poets of the early part of the twentieth century, Stephen Vincent Benet, wrote a poem called “John Brown’s Body” in 1928. In fact, my parents had a book of old poetry, and I remember growing up, taking that book off of the bookshelf and looking through it and seeing this poem about John Brown’s Body and wondering who John Brown was. Well, I later learned, of course, and now you know as well.
Our final topic here on the Café is high school reunions. A “reunion” is a gathering, a meeting, of people who have not seen each other for a long time. In the United States, there is a tradition of high school reunions, where people who all graduated from the same high school in the same year get together for a party, usually 5, 10, 15, 20, sometimes 30 years after they have left high school. In fact, the tradition is to have a reunion every five to ten years. Everyone gets together again for a party where they meet up with their old friends and talk about what their life has been like.
On television and in the movies, the American high school reunion is often considered something that you should, or many people do, dread. “To dread” (dread) means to not look forward to it. Some people don’t want to go back to their high school reunion. They don’t want to see the people that they went to high school with. Of course, everyone matures as they get older. They develop and grow up, and often you don’t have a lot in common, a lot to talk about, with the people you went to high school with.
However, some people really love going to these high school reunions. They like to catch up with their old friends. “To catch up” is a phrasal verb which here means to talk to a person about what he or she has been doing, a person that you haven’t seen for a long time. High school reunions are different in every school, but usually they take place at a hotel or some large meeting room. There’s often music that is played, music from the time that you were in high school.
Apparently, some high school reunions nowadays have themes. A “theme” (theme) is a certain idea or mood that you want to establish for your event. So, for example you might have an 80s theme, where everyone dresses up as they did in the 1980s. Of course, some of us graduated from high school in the 1980s, and so that wouldn’t seem so unusual to us, I guess.
Typically, members of the high school class themselves organize the reunion. Usually they’re a group of classmates – people who went to school together – who organize the party and contact everyone. Most people who go to high school reunions enjoy the experience. But of course, if you go to the high school reunion, you want to be there. Many people don’t go to their high school reunions. I have never gone to a high school reunion. We had our 30th high school reunion a few years ago, and I did not go and do not plan to go to any of my future high school reunions. Well, maybe I’ll go to my 100th high school reunion if I’m still alive at 118.
Why don’t I go to my high school reunions? I guess the people that I was friends with in high school, I keep in touch with – that is, I’m in contact with them. I already know what they’re doing. And the people that I was not friends in high school with, I guess I don’t have any strong interest in finding out how they are doing. And they’re probably not interested in how I’m doing, either.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Zahra (Zahra). The question has to do with the difference between two words, “phantom” and “soul.” Let’s start with “phantom” (phantom). A “phantom” is the ghost of a dead person, someone who has died and continues living in some sort of immaterial or nonmaterial way. Usually the word “phantom” refers to some spiritual being that is going around and causing problems in the world or perhaps is unable to rest in the afterlife (after the person dies).
There was a famous musical, The Phantom of the Opera, that related to this old notion that there is a ghost that is somehow bothering people. Sometimes people talk about phantoms and ghosts “haunting” a place. “To haunt” (haunt) means to be present in a certain area and to cause problems for people who go into, say, a house that is haunted. I’m not saying any of this is true, but that’s how the word is used.
Sometimes the word “phantom” is used to mean “nonexistent” – something that isn’t real. You could talk about a “phantom financial transaction,” where someone says that they gave someone money but they didn’t really do it. So, “phantom” can be used as an adjective also to describe something that isn’t real or perhaps is done for some illegal or illegitimate purpose.
A “soul” (soul) is similar to a phantom, except it has a much broader use and meaning. The “soul” of something would be the nonphysical part of something, specifically the spiritual aspect or part of a human being. Now, the word “soul” has been used in many different ways over the centuries. What Plato and Aristotle, for example, thought of as the soul isn’t necessarily the exact same thing that a modern Christian might think of as a soul. In modern twentieth-century American English, your “soul” usually refers to the part of you that will continue living even after you’re dead.
It’s different from “phantom” in that “phantom” is usually used in a negative sense to refer to some spiritual being that people can actually see or that somehow effects the way we live in a negative way. The word “soul” doesn’t have that negative connotation and is used in theology as well as philosophy to talk about a nonphysical, if you will, part of a human being – or, for that matter, an animal.
Our next question comes from Farsad (Farsad). The question has to do with two words, “coast” (coast) and “shore” (shore). “Coast” and “shore” both refer to the part of the land that is near water. The difference is that we normally use the word “coast” when we’re talking about the land near an ocean, near a sea. However, “shore” can be used in those instances as well.
You can talk about the “seashore,” which would be the land next to an ocean or a sea. “Shore” can also refer to the land next to the water on a lake. We could talk about the “lakeshore” or owning “lakeshore” property. So, they mean the same thing, but “shore” is used both to refer to the land next to an ocean or a sea, as well as the land next to a lake. You may ask, “Well what about the land next to a river?” And that would typically be called the “riverbank” (bank).
I should also mention that in the U.S., when people say “the coast,” usually they’re referring to either the west coast of the United States, which would be California, Oregon and Washington – those three states are on the West Coast – or the East Coast (those would be all of the states from Maine to Florida that are on the Atlantic Ocean). Now, of course, technically the states that are on the Gulf of Mexico are also connected by water to the Atlantic Ocean, but we don’t usually refer to those states as being part of the East Coast.
Finally, a question from Brazil from Thiago (Thiago). This is a question about an old expression that you don’t hear much anymore, but you might see it in print – that is, you might see it in writing. The expression is “plug nickel.” The first part of this term, “plug” (plug), refers to a piece of solid material that is put into a hole, preventing usually water from going down into what we would call a “drain” – a pipe that is connected to, say, a sink.
“Plug” can also be a verb. There is a common two-word phrasal verb “to plug up,” which means to put a plug, put something, into a hole to prevent water from escaping. Now, it could also be air. It could be something else, some other material that would escape or leave a container that you want to keep it in. You might also use the word “plug” for that. “Plug” as a verb can also mean something completely different. It can mean to try to sell or to try to give publicity to. Authors will often go to bookstores and “plug” their books – that is, try to get people to buy them.
“Nickel” (nickel) here refers to the American coin worth five cents. A nickel is five cents, a dime is ten cents, a quarter is twenty-five cents, and a dollar is one hundred cents. The term “plug nickel,” however, describes something that is “worthless” – that’s not worth very much money.
It’s a strange term. It comes from the nineteenth century in the U.S., where the government sometimes made coins with a hole in the middle, and in the hole they would put a little piece of silver of whatever value that coin was. Sometimes, however, those pieces of silver fell out of the coin, and you had basically a coin that looked like a doughnut – it didn’t have the original metal in it.
That’s the origin of “plug nickel,” meaning something that was worthless, something that didn’t have the metal that it was supposed to have. Since we’re talking about the word “plug,” there’s one other common idiom that you should know, and that is “to pull (pull) the plug.” “To pull the plug” means to withdraw support, especially financial support, for some activity or operation, or simply to end something. “The play was not very successful at the local theater, so the theater decided to pull the plug on the project,” on the play.
The original meaning of that expression comes from the idea of a plug being a small object that prevents water or some other material from escaping a container so it has the same origin, but nowadays it means to stop supporting something. A lot of people will tell you that this expression comes from the electrical cords that are devices, are machines, computers and televisions use to get electrical power. The cord at the very end has what’s called a “plug.” Same word. The “plug” goes into the wall in order for you to get electricity to the machine.
Many people associate “pulling the plug” with that plug – the plug that is part of an electrical cord. However, the original meaning was actually the one that I gave, which is the plug that would prevent, say, water from escaping.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
abolitionist – a person who believes in ending the practice of slavery (the owning of another person and forcing them to work for no pay)
* Abolitionists tried to get laws passed that would limit slave owners’ rights.
to smuggle – to illegally transport an object or person
* Illegal drugs are sometimes smuggled into a country inside toys and other innocent-looking items.
fugitive – a prisoner but who has escaped and is running or hiding from those who want to find him/her
* After he escaped from prison, Henri was a fugitive in India for over 16 years before he was caught.
reward – something, usually money, that is given as thanks to someone for their help or assistance
* The Van der Maartins offered a $5,000 reward to the person who found their lost dog and returned it to them.
to raid – to suddenly attack or enter a place using force
* The police raided the building where they believed illegal goods were being stored.
arsenal – a place where many weapons are kept in storage to be used, usually by a large group of people or the military
* Members of the military closely guarded the arsenal to be sure that no weapons were stolen.
to be executed – to be killed by a military or government as punishment for a crime
* The murderer was executed after being convicted of killing 14 people.
reunion – a gathering of people who have not seen each other for a long period of time
* There were so many college friends at Siddharth and Radha’s wedding that it felt like a college reunion.
to dread – to be worried or fearful of some future event or possibility; to not look forward to something
* Yvette had been dreading the trip to the dentist, but was pleasantly surprised when it didn’t hurt at all.
to mature – to fully develop and grow; to have the emotional development and mental ability of a responsible adult
* Yuko was glad when her brother finally matured and stopped playing silly jokes on other people
to catch up with (someone) – to talk with another person about events in one’s life since the last time one had been in contact
* Liam hadn’t seen his father for two years, so they spent all weekend catching up.
theme – an idea that sets a certain atmosphere or mood for an event
* The theme of the fundraiser was “a day at the beach” so there were beach balls and sandcastles all around the room.
phantom – a ghost; the soul of a dead person who appears to people or who lives in another world
* Do you believe stories about phantoms that live in the attic of this old house?
soul – the spiritual or non-physical part of a human being or animal that is believed to live or remain after someone dies
* Christians believe that a person’s soul never dies.
coast – the part of the land near the sea; the edge of the land next to an ocean or sea
* The storm affected three states along the eastern coast of the country.
shore – the land along the edge of an ocean, sea, or lake
* You can walk on this part of the shore when the tide is out.
plug nickel – worthless; having little or no value
* I don’t think he’s very knowledgeable. His advice is worth a plug nickel.
What Insiders Know
The Oberlin-Wellington Rescue
The Fugitive Law of 1850 was a law passed by the United States Congress that required citizens to help locate escaped slaves, captured them, and returned them to their “masters” (bosses; owners). The abolitionist movement wanted to end any form of slavery in the United States, and this law was one of the many things that the abolitionist movement wanted to “get rid of” (remove).
One event that became very important to the abolitionist movement was the Oberlin-Wellington Rescue. On the morning of September 13, 1858, a “runaway” (person leaving and getting away from one’s parents or master) slave named John Price from the State of Kentucky was “arrested by” (taken away by) a U.S. “marshal” (police officer who works for the federal government) in Oberlin, Ohio. To avoid “conflict” or problems with local residents who “largely” (mainly) supported the abolitionist movement, the marshal took him to a nearby town called Wellington.
When people found out that Price had been taken to Wellington, a large group of abolition supporters went there to bring him back to Oberlin. The marshal tried to hide Price, but “failed” (did not succeed). The people from Oberlin “stormed inside” (rush inside using force) the hotel where Price was being kept and took Price back to Oberlin. When then reached Oberlin, the group “hid” (placed him in a place where he would not be found) Price and then later took him across the “border” (line between two lands) to Canada.
Thirty-seven people were arrested for their participation in the event. Two men, Charles Langston and Simeon Bushnell, were “convicted” (legally found guilty of the crime) and “sentenced” (given time in jail as punishment) for their actions. Bushnell was sentenced to 60 days, while Langston received 20 days.