= 1763
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 458.
This is English as a Second Language Podcast’s English Café episode 458. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide, an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to talk about a court or legal case that changed how police in the United States interview people who they think may have committed or done a crime. We’re also going to talk about a famous American cartoonist named Rube Goldberg and something called a “Rube Goldberg Machine.” And, as always, we’ll answer a few of your questions. Let’s get started.
If you watch any American television show or movie nowadays that involves the police arresting someone, or taking that person to jail or prison, you’ll usually hear the police say the same thing to each person as the police officer arrests the person. Here’s what you’ll hear them say:
“You have the right to remain silent. Anything you say can and will be used against you in a court of law. You have the right to an attorney. If you cannot afford an attorney, one will be provided for you.”
This statement, which every police officer has memorized and which anyone who watches American television shows and movies also knows, is called the “Miranda warning,” and it isn’t just the police in movies and on television who say it. Police and what we call “law enforcement officers” in real life are required to say it in the United States, or something very similar. So, why do we have this Miranda warning and what, really, does it mean?
In 1966, the case of Miranda v. Arizona arrived at the Supreme Court. The U.S. Supreme (supreme) Court is the highest and most powerful court in the United States. The court listens to cases that have already typically gone through other courts. The court decides if the rulings or decisions the other courts have made are correct or not, and more importantly, if they follow the laws of the United States Constitution, which is our highest law, if you will.
The word “supreme” means highest, and that’s what our Supreme Court is – the highest court in the country. Nine men and women sit on the Supreme Court, and they are appointed, or named to the court, for life. That is, they can stay there until they die, and many of them do die as “sitting justices,” we would say, or until they resign.
The case of Miranda v. Arizona began in Arizona, logically enough, in 1963. I call the case “Miranda V Arizona” because, as we may have explained on previous Cafés, legal cases in United States involve one person or one group versus another. The “V” in “Miranda V Arizona” stands for “versus,” meaning “against.” In this case, we have a person named Miranda who is filing a case against the state of Arizona.
There was a man named Ernesto Miranda who was accused of, or thought to have been involved in, kidnapping, rape, and robbery. “Kidnapping” (kidnapping) is when one person takes another person by force against the other person’s wishes and holds that person against his or her wishes. “Rape” (rape) is when a person forces another person to have sex with him (and it’s usually a “him”). “Robbery” (robbery) is when one person takes another person’s belongings, another person’s things, without the other person saying it’s okay.
Ernesto Miranda was found by the police and taken into custody. The expression “to be taken into custody” (custody) means basically to be arrested by the police and brought to a police station, to a jail. When Miranda was taken to the police station, the place where the police work, the police interrogated him. “To interrogate” (interrogate) someone means to ask someone a lot of questions, usually because you’re trying to get information from the person, often information related to a crime or some issue of security.
Now, the police talked to Miranda for two hours about the crime they thought he had committed, or he had done, and Miranda, in fact, confessed. “To confess” (confess) means to say yes, I am guilty – I am the person who did the crime. Well, the case went to trial, which means two lawyers went before a judge and talked about what happened.
In a criminal case, there are usually two lawyers involved. One lawyer is for what we call the “defense” (defense). The lawyer for the defense is trying to help the person who has been accused of the crime. His or her job is to defend the person and try to get the person free. The other lawyer is called the lawyer for the “prosecution” (prosecution). In criminal cases in the United States, the prosecution is the government, and so the lawyer for the prosecution works for the government.
In Miranda’s case he was, in fact, found guilty and sentenced to 20 to 30 years in jail, in prison. The way that the prosecution proved that Miranda was guilty was by showing the court Miranda’s confession – his admission or statement that he committed the crime, which is what he told the police. But after the court case, after Miranda was sent to prison, he filed a lawsuit or legal case against the government of Arizona saying that his constitutional rights had been violated.
That means that he said that the laws that were supposed to protect him as a citizen of the United States were not followed properly in this case – that the police had done something wrong and therefore violated, or had broken or gone against, his rights under the U.S. Constitution. Specifically, he said that Arizona had violated, or failed to respect, his Fifth and Sixth Amendment rights.
What are the Fifth and Sixth Amendment rights? Well, the U.S. Constitution has a number of what we call “amendments.” These are basically additions to the Constitution that have been added since the original Constitution was approved back in 1789. There have been 27 changes, or additions, or amendments, to the Constitution of the United States, at least at the time of this recording of this episode.
The Fifth Amendment to the Constitution says that no person shall be compelled in any criminal case to be a witness against himself. This means that no one can be forced or compelled to say anything that will make him sound guilty of committing a crime. You can’t be forced to say that you did something wrong.
Remember, in the U.S. court system, in the U.S. criminal legal system, you are innocent until proven guilty, meaning that the people deciding the case must assume that the person arrested is innocent – that the person did not commit the crime – unless the government can prove or show that he is, in fact, guilty. The Fifth Amendment says that if you are arrested and accused of a crime – if the police say you did it – you do not have to say anything that might make you appear or actually prove that you are guilty.
The Sixth Amendment says that each person has the right to have the assistance of counsel for his defense. This means that each person has the right to have a lawyer – that’s what “counsel” means – with him or her when he or she is answering questions from the police and the courts in order to find out if the person is guilty. If you have a right to counsel, you have a right to a lawyer who (we hope) will help you in defending yourself against the accusation.
When Miranda was taken into custody, when he was arrested, no one told him that he was allowed to remain silent, or not to talk to the police. In addition, no one told him that he was allowed to have a lawyer or attorney with him when the police asked him questions. Now, many people in the 1960s may not have known that they had these legal rights.
Miranda was not what we would call an “educated man.” He had only gone to school through the ninth grade, and in addition, he had a history of mental illness. This means that throughout his life, he had suffered from some sickness of the mind. It is therefore very possible that Miranda did not know his rights, especially if the police did not tell him of those rights. The “justices” of the Supreme Court, which is the special name we call the judges on a Supreme Court, also believed that Miranda’s rights had been violated.
They said that his confession could not be used in court by the prosecution because the police had obtained it, or had gotten it, illegally. It was illegal, or against the law, because the police had not told Miranda of his rights. The justices also said that they believed it was necessary to make sure that all people understood that they had certain rights to protect them if they were accused of a crime, and for this reason, the court created what we now call the “Miranda warning.”
Let’s take a look at what the Miranda warning says, since it appears so often in films and television shows. The first part of the Miranda warning says, “You have the right to remain silent.” This means that the person being accused of a crime does not have to say anything at all. He doesn’t have to talk about the crime, and if he chooses, he doesn’t have to answer any questions about the topic from the police.
The second part of the warning says, “Anything you say can and will be used against you in a court of law.” This means that the police and lawyers are allowed to repeat anything that the person has said while talking to the police to prove that he is guilty. That’s what we mean when we say, “Anything you say can and will be used against you.” “To use something against” someone is to hurt the person or to try to prove the person is guilty of something.
Both of these statements refer to the Fifth Amendment, which we discussed earlier. The next two parts of the Miranda warning refer to the Sixth Amendment. The third statement says, “You have the right to an attorney.” This means that every person is allowed to ask to have a lawyer or attorney with him when the police are asking him questions – all they need to do is ask for one.
The final part of the warning says, “If you cannot afford a lawyer, one will be provided for you.” This means that if the person is unable to pay for – “cannot afford” (afford) – a private lawyer to come and help him or her, the state must find a lawyer who will help that person. A lawyer who works for the state gets paid by the state and is free for the person the lawyer is helping. Of course, that doesn’t mean you’re going to get the best lawyer in the state or city where you were arrested. In fact, it may mean you get one of the worst lawyers, so if you have the money, it’s best to get your own attorney.
At the time that the Supreme Court created the Miranda warning, some people said that they were taking power away from the police. They argued that by making the police say the Miranda warning, the police would not be able to put as many guilty people in jail. The court disagreed. They said that was not true. The court thought that it would help make sure that people accused of a crime were treated fairly by the police.
Today, mostly because of television and movies, most Americans are familiar with the Miranda warning and know their legal rights. However, the police are still required to remind a person of his or her rights by reading or saying the Miranda warning when arresting a person.
Ernesto Miranda, the person responsible for the creation of the Miranda warning, had his first jail sentence overturned, or removed. He was tried again for the crime he had been accused of. The prosecution was not allowed to use his confession in the trial; nevertheless, the prosecution won again, and Miranda was found guilty of the crime. So, he did not go free in the end.
Let’s turn briefly now to our second topic on this Café – a famous American by the name of Rube Goldberg. Rube Goldberg was born on July fourth, 1883, right here in California. July fourth is, as you know, Independence Day in the United States. My father was also born on July fourth.
Goldberg went to college at the University of California, Berkeley, which is now one of the best universities in the U.S., and studied engineering. He graduated in 1904. After he graduated, he worked for the San Francisco Sewer Company. A “sewer” (sewer) is part of an underground system that carries water and waste away from houses and buildings.
Shortly after Goldberg had started working for the San Francisco Sewer Company, he got a job in a completely different area – as a sportswriter for the San Francisco Chronicle, a newspaper in San Francisco. He wrote articles about sports and sports teams for the newspaper. He moved newspapers a couple of times, and by 1907 he was in New York working for another newspaper, called the New York Evening Mail.
There, instead of writing sports articles, he created comic strips. “Comic strips” are groups of drawings that tell a funny story that typically appear in newspapers and some magazines. There are comics for children, and there are comics for adults. One of the funny characters Goldberg created for these comics was a man named Professor Lucifer Gorgonzola Butts. This character was an inventor of items that would solve simple problems in a very complicated and complex way.
Of course, that isn’t very useful. I mean, simple problems don’t require complicated solutions – that’s why we call them “simple problems.” But Goldberg’s character Professor Butts did the opposite. He created complicated solutions, typically machines to solve simple problems. The character has a very strange name, which combines a name for the devil, Lucifer, with the name of a cheese – Gorgonzola – and ends with a slang word for someone’s rear end: “Butt.”
Goldberg’s training as an engineer helped him create these silly inventions that Professor Butt used in the cartoons. One of the inventions seen in the comic strip, for example, was a way to get rid of mice. This will give you an idea of the funny, complicated machines that Rube Goldberg was known for creating in his comics.
In this particular comic, the mouse would see a painting of a piece of cheese and jump for it. Not an actual piece of cheese – a painting of a piece of cheese. The mouse would fall through the painting and land on, or end up on, a hot stove – a place where you cook in the kitchen. The mouse would then jump off the hot stove because it’s hot and land on a piece of ice. The piece of ice is going up an escalator. An “escalator” (escalator) is a moving set of stairs.
The mouse would next fall off the escalator into a giant boxing glove. A “boxing glove” (glove) is soft covering for the hand of a boxer, or a person who punches or hits other people for a living in a sport called “boxing.” The mouse would bounce off the boxing glove into a basket. The basket was attached to, or connected to, a rocket ship – the sort of thing you use to go up into outer space, away from Earth. The rocket ship would take off and fly the mouse to the moon, and in that way get rid of the mouse.
Well, you can see this is an extremely complicated system for a very simple problem. It’s supposed to be funny, and if you look at the comic strips, it is. The term “Rube Goldberg machine” – or, more generally, a “Rube Goldberg solution” – came to mean a very complicated, too-complicated solution to a simple problem.
Goldberg went on to work as a cartoonist for several other newspapers. He worked as what we would call an “editorial cartoonist.” An editorial cartoonist is a person who draws cartoons that are usually about some current situation or some political situation. Goldberg was so good at his job that he won a Pulitzer Prize for one of these cartoons. A “Pulitzer Prize” is an award for journalists and people who work at newspapers in the United States. Pulitzer Prizes are also given to other kinds of writing, but that’s the main association people have with the Pulitzer.
While Goldberg eventually became a respected editorial cartoonist, it was his earlier work as a cartoonist trying to make people laugh with his crazy machines that made him famous and that made that expression famous – a “Rube Goldberg machine,” or a “Rube Goldberg contraption.” If you look up “Rube Goldberg” in a dictionary, you will see a definition of that term, usually related to doing something simple in a complicated way that is not necessary.
Let’s answer a few of your questions.
We have time for a couple of quick questions. The first one is from Jane (Jane) living in Pittsburgh, originally from China. Jane wants to know the difference between two verbs, “to heal” and “to cure.” Both terms are similar in meaning. Let’s start with “to heal” (heal).
“To heal” means that you are sick and then you become healthy. Your body goes back to its normal, healthy condition, typically after an injury. We use the verb “to heal” when you hurt some part of your body, such as your arm or your leg. Maybe you were playing American football and someone knocked you down and hurt your shoulder, or maybe you were skiing and you fell off of your skis and you broke your leg. In those situations, where your body is somehow damaged, we use the verb “to heal” to describe the process of your body getting better.
“To cure” (cure) usually refers to someone who gets healthy after having some disease. It could be, for example, that you have a flu, or you have a cold, or you have some sort of cancer, even. “To cure” means that you get healthy; your body goes back to normal after having this illness or disease. “Heal” refers to an injury – when you hurt your body, often by accident. “Cure” means that your body has some sort of illness, some sort of disease, and then gets better.
More generally, we use the word “cure” to refer to someone who has completely recovered from their disease – is completely back to normal. “Cure” can also be used as a noun to refer to some medical process or some drug that makes someone who is ill healthy. The Cure was a rock band popular in the 1980s. I don’t think Jane is asking about The Cure.
Our second question comes from Marat (Marat) in Russia. The question is about two phrasal verbs, “to give up” and “to give in.” “To give up” means to stop trying to do something – to decide that you’re not going to be able to do it, and therefore to stop trying to do it. Someone may say to you, “Guess the name of the movie I went to see last night,” and you guess a few things. You say, “Well, maybe it was this movie. Maybe it was that movie.” Finally, you say, “Okay, I give up,” meaning I’m not going to try anymore.
“To give in” is to do what other people want you to do after first not wanting or refusing to do it. My brother wants me to go to a Minnesota Twins baseball game. He keeps asking me. I keep saying no. Finally, after the 25th time of him asking me, I say, “Okay, I give in. I will go.” “To give in” means to stop resisting the pressure from someone else to do something. You decide, “Okay, I’m just going to do it.”
“To give in” in some ways is the opposite of “to give up.” “To give up” is to stop doing something that you perhaps want to accomplish. “To give in” is to do something that you really didn’t want to do in the first place.
Finally, Bobur (Bobur) in Uzbekistan wants to know the meaning of a very common expression in English: “No way” (way). “No way” means under no circumstances – not at all. “Our boss told us that there is no way we will be able to leave early on Friday.” There is no possibility. There’s no chance whatsoever. It’s not going to happen. “There’s no way I’m going to go out and buy a cat and bring it into my house.” That is not going to happen. It will never happen even if I live a million years. It will never happen. That is the meaning of “No way.”
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
to take into custody – to be arrest by the police and brought to the police station as a person who may have committed a crime
* The newspaper article reported that the police had taken into custody a man who was suspected of robbing three banks in the area.
to interrogate – to ask a person who may have committed a crime questions about that crime
* The detective interrogated the teenager for three hours but could not get him to admit to stealing the clothing from the store.
to confess – to admit to committing a crime; for a person to admit to doing something wrong or that is against the rules
* Deepka’s husband confessed to drinking the last of the orange juice and forgetting to buy more.
defense – the lawyer or legal team that argues on behalf of a person or organization being accused of a crime
* The defense team worked day and night to try to prove that Emmanuel was innocent of breaking into the mayor’s house.
prosecution – the lawyer or legal team that argues on behalf of the person or organization that has accused another person or organization of committing a crime
* The prosecution attempted to prove that the company had been hiding money it had earned and not paying taxes on it.
justice – a judge, especially of the Supreme Court of the United States
* The justices of the Supreme Court work together to determine if the cases before them follow the laws of the Constitution.
to overturn – to determine that a judge’s decision in a trial is wrong and say that it is no longer valid
* The appeals court listens to cases that have already been decided and will occasionally overturn a ruling if they believe the first court was wrong.
sewer – an underground system that carries water and waste away from houses and buildings
* The sewer system in many cities is hundreds of years old because they were built when cities first began to grow.
comic strip – groups of drawings that tell a funny story that appear in newspapers or magazines
* The Peanuts comic strip was published in newspapers for over 50 years.
escalator – a moving set of stairs; a staircase that is set into motion by a motor that goes up or down
* The escalator at the airport was broken, so Manny had to carry his suitcase up the stairs to the check-in desk.
boxing glove – a soft covering for the hand of a boxer or person who punches and hits other people as part of a sport
* The boxer put his boxing gloves on so that his hands would be protected during the fight.
editorial cartoonist – a person who draws an image or series of images that make fun of a current situation
* During an election season, many editorial cartoonists focus their work on the different candidates running for office.
to heal – to return to good health or to restore one’s body to its normal condition, usually after an injury
* For the cut on your finger to heal property, keep it as clean and dry as possible.
to cure – to cause someone to be healthy again after an illness or disease; to do something to cause someone to recover from disease
* Do you believe there will be a cure for breast cancer within the next 50 years?
to give up – to stop trying to complete or succeed in doing something; to accept failure
* Jordan gave up trying to beat his sister in this computer game after failing for weeks.
to give in – to stop trying to resist; to do what others want one to do after a period of not wanting to or refusing to do it
* If we keep asking Dad to take us out for ice cream after dinner, I know he’ll finally give in.
no way – under no circumstances; not at all
* There is no way we’ll finish this project by Monday unless we all work this weekend.
What Insiders Know
The Garrity and Kalkines Warnings
Although you may have heard of the Miranda warning in television shows and movies, you may not be aware of two other warnings: The Garrity warning and the Kalkines warning. Both are used for government employees during an “investigation” (attempt at finding out the truth) and reminds people of the same “rights” (legal permission).
The Garrity warning is given by state and local investigators to their employees. Similar to the Miranda warning, it tells the employee that they have certain rights before they are questioned.
The Garrity warning is the result of a United States Supreme Court” case called Garrity v. New Jersey, in which a police officer was forced to speak or be “fired” (lose his/her job), and to be “prosecuted criminally” (charged with a crime). The Supreme Court said that the police officer was not told of his right to remain silent, or of the other rights he has to protect himself.
The Kalkines warning is similar to the Garrity warning, but “applies to” (is intended for) federal or national employees. It was established after another Supreme Court case, this one called Kalkines v. United States.
In this case, a federal employee was fired for not cooperating with an investigation. It was later “ruled” (decided by a court of law) that the employee was not properly “advised of” (told about) his rights.