

= 0017 What a museum of disgusting food reveals about human nature
:toc: left
:toclevels: 3
:sectnums:

'''


==   What a museum of disgusting food reveals about human nature



When people recognise that disgust *depends [in part] on* upbringing (a.) 抚育；养育；培养, they can learn to overcome it, at least some of the time.

Not only 主 do “immoral” things 谓 disgust people; sometimes, disgust can affect their moral judgments.

In one experiment, Thalia Wheatley of the National *Institutes of Health* 国立卫生研究院 and Jonathan Haidt of the University of Virginia took a group of people *who were susceptible (a.)易受影响（或伤害等）；敏感；过敏) to* hypnosis 催眠状态.

*They were hypnotised (v.)对（某人）施催眠术 to feel* a brief pang (n.)突然的疼痛（或痛苦）；一阵剧痛) of disgust [when they read an everyday 每天的；每日发生的；日常的 word, either “take” or “often”].

Then they read accounts (n.)描述；叙述；报告 of theft, bribery (n.)行贿；受贿 or incest (n.)乱伦；血亲相奸, and were asked how morally outrageous (a.)骇人的；无法容忍的 they thought each incident was.

When *an account 描述；叙述；报告 of* an offence(n.)违法行为；犯罪；罪行 included one of the words that triggered disgust, the participants *condemned (v.) it more severely*.

Other experiments have shown that 主 people who are easily disgusted 谓 *make harsher moral judgments* [when subjected (v.)使经受；使遭受 to *disgusting 极糟的；令人不快的 stimuli* 刺激物, such as *a sticky 黏（性）的 desk* or *foul 肮脏恶臭的；难闻的 smells*].


[.my1]
.标题
====
.hypnosis
/hɪp-ˈnoʊ-sɪs/
⇒ hypno-,睡觉，催眠，-osis,情况，疾病征兆。引申词义催眠，催眠状态。许普诺斯（Hypnos）是希腊神话中的睡神.

.outrageous
⇒ 来自outrage,愤怒，愤慨。
当人们意识到, "厌恶感"在某种程度上取决于你从小受过什么教育时，他们可以尝试学会克服它，至少在某些时候是这样。

.incest
-> in-,不，非，-cest,纯的，词源同caste,castrate.即不纯洁的，引申词义乱伦。

不但做“不道德”的事, 会令人厌恶;有时，厌恶的感观感觉, 也会影响他们的道德判断。

在一项实验中，美国国立卫生研究院的Thalia Wheatley和弗吉尼亚大学的Jonathan Haidt, 对一组容易受到催眠影响的人, 进行了研究。他们在被催眠后，就让他们阅读每一个日常的普通单词, 比如“take” 或 “often”, 同时, 给他们施加一阵令人会产生厌恶感的短暂刺激. 之后, 就给他们阅读关于盗窃、贿赂或乱伦的报道，并询问他们, 这每一个有罪的行为, 令他们有多无法容忍? 结果证明, 当报道中含有会令人引起厌恶的用词时, 被试者就会更加严厉地谴责它。

其他的实验表明，容易感到厌恶感的人, 在受到令人作呕的刺激时，比如黏糊糊的桌子, 或难闻的气味时，会做出更严厉的道德判断。
====



Another finding is that 主 people who are more easily disgusted 系 *are more likely(a.) to be* socially conservative (a.)保守的.

A study by Xiaowen Xu of the College of William and Mary 威廉与玛丽学院 in Virginia and others *found evidence that* “disgust-sensitive people [underline]#extend# (v.) their preference (n.) for order 秩序;条理 (in the physical environment (eg, tidying up 使整洁；使整齐 ；使有条理；整理 one’s room)) [underline]#to# *the sociopolitical 社会政治的 environment* (eg, strengthening (v.) *traditional norms*).”

Woo-Young Ahn of Virginia Tech 弗吉尼亚理工大学 and others found that by scanning (v.) *brain responses* to a single disgusting image (such as *a mutilated 使残废；使残缺不全；毁伤) body*, they could *make accurate predictions about* a subject’s  接受试验者；实验对象 *political ideology*  意识形态；观念形态.

主 People *who are highly sensitive to disgust* 系 are especially likely to oppose (v.)反对（计划、政策等）；抵制；阻挠 immigration 外来移民. This is true *even after* controlling for education, income and political ideology.


[.my1]
.标题
====
.the College of William and Mary :
威廉与玛丽学院. 是美国历史第二悠久的高等院校(1693年)，建校时间仅次于1636年建立的哈佛大学。

.mutilate
⇒ 来自拉丁语mutilus,使残的，可能来自PIE*mai,砍，切，词源同 maim, mangle. 引申词义使残废。

另一项发现是，更容易会产生恶心感的人, 也更有可能是社会保守主义者。弗吉尼亚的威廉与玛丽学院的 Xiaowen Xu 等人研究发现，有证据表明，“对厌恶感敏感的人, 会将他们对物理环境中的秩序(如整理房间)的偏好, 延伸到社会的政治环境上(如强化传统规范)。” 弗吉尼亚理工大学的 Woo-Young Ahn 等人发现，通过扫描大脑对单独的恶心图像(比如残损的身体)所作出的反应，他们可以准确预测一个被试的政治意识形态。

那些最容易产生(具有敏感性)厌恶感的人, 尤其可能反对移民。即使将他们的教育、收入, 和政治意识形态考虑在内，也是如此。
====


'''

== <pure> What a museum of disgusting food reveals about human nature


When people recognise that {disgust depends in part on upbringing}, they can learn to overcome it, at least some of the time.

Not only do “immoral” things disgust people; sometimes, disgust can affect their moral judgments. In one experiment, Thalia Wheatley of the National Institutes of Health and Jonathan Haidt of the University of Virginia took a group of people who were susceptible to hypnosis. They were hypnotised to feel a brief pang of disgust when they read an everyday word, either “take” or “often”. Then they read accounts of theft, bribery or incest, and were asked how morally outrageous they thought each incident was. When an account of an offence included one of the words that triggered disgust, the participants condemned it more severely. Other experiments have shown that  people who are easily disgusted make harsher moral judgments [when subjected to disgusting stimuli, such as a sticky desk or foul smells].


Another finding is that people who are more easily disgusted are more likely to be socially conservative. A study by Xiaowen Xu of the College of William and Mary in Virginia and others found evidence that “disgust-sensitive people [underline]#extend# their preference for order in the physical environment (eg, tidying up one’s room) [underline]#to# the sociopolitical environment (eg, strengthening traditional norms).” Woo-Young Ahn of Virginia Tech and others found that by scanning brain responses to a single disgusting image (such as a mutilated body), they could make accurate predictions about a subject’s political ideology.

People who are highly sensitive to disgust are especially likely to oppose immigration. This is true even after controlling for education, income and political ideology.


'''
