= 1407
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 102.
This is English Café episode 102. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. You can also take a look at our ESL Podcast Store, which has some additional business and daily English courses you may be interested in.
On this Café, we’re going to talk about something that is known to every American child, and that is the Pledge of Allegiance. We’ll talk about what that is. We’re also about tomatoes, whether they are a fruit or a vegetable and why that is related to the U.S. Supreme Court, the highest legal authority in the United States. And as always, we’ll answer a few of your questions. Let’s get started.
Our first topic today is something called the “Pledge of Allegiance.” One of the things we try to do on the English Café is tell you about American ideas, customs, traditions – things that most Americans know but you may not know if you live in another country, and the Pledge of Allegiance is a good example of that.
The Pledge of Allegiance is something that every American knows, especially every American who went to school in the United States – elementary and secondary school. Everyone here could tell you what the Pledge of Allegiance is. Let’s begin by talking about these words, “Pledge of Allegiance.” A “pledge” (pledge) is a promise. Usually it’s a formal promise, a promise to do something. In this case it is a promise of allegiance (allegiance). “Allegiance” means loyalty, means defending something, being a supporter of something. The “Pledge of Allegiance” is a promise, or an oath, of loyalty or of support to the United States.
When children go to school – elementary and secondary school – the first thing they do every morning in almost every school in the United States is they say this Pledge of Allegiance. They stand up in their classroom, they look at the flag of the United States, they put their hand – their right hand – over their heart on the top of their chest, and they say this one sentence pledge. The words of the pledge are – and this is all said together, everyone says it together. We would say it is said “in unison” (unison), which means all together. The words are:
I pledge allegiance to the flag of the United States of America and to the Republic for which it stands, one Nation under God, indivisible, with liberty and justice for all.
Let me explain that sentence to you. It begins by using the word “pledge” as a verb: “I pledge allegiance to the flag of the United States of America.” The “flag” is, for most countries, a symbol of the country. In this case, you are looking at the flag, you are pledging allegiance to the flag, but not to the flag itself. You’re pledging allegiance, or support, for the country, and that’s why the next part of the sentence it is “and to the Republic for which it stands.” The “Republic” is another name for the country – the United States. The United States is a republic. The flag stands for the Republic – the country. When we say it “stands for,” we mean it represents, so the flag represents the country.
The pledge continues “one Nation (one country) under God (under the guidance or protection, perhaps, of God), indivisible.” Something that is “indivisible” means you cannot divide it, and this is an important word because during the middle of the 19th century, about 40 or 50 years before this Pledge of Allegiance was written, America had, as you may know, a civil war where the North and the South fought each other. The southern states tried to separate from the United States, and the northern states prevented them from doing that. That’s one of the reasons why there is this word “indivisible” – cannot be divided.
The final phrase of the pledge is “with liberty (or freedom) and justice for all.” “Justice” is being fair, being right. So once again:
I pledge allegiance to the flag of the United States of America and to the Republic for which it stands, one Nation under God, indivisible, with liberty and justice for all.
This is what is said by almost every child in school every morning, usually at the beginning of the school day – the beginning of the first class.
A couple of interesting things about the Pledge of Allegiance, first, it was originally written – and I think this is very American, in some way – as an advertising slogan, or part of an advertising campaign. There was a company that made flags and sold flags, and they asked someone to write them this Pledge of Allegiance. However, soon after this happened, back in 1892, the president at the time decided to make the pledge something that all schools used.
Some people have wondered about the expression “under God.” The original Pledge of Allegiance did not have this phrase, “under God.” It was put in the Pledge of Allegiance back in the 1950s by President Eisenhower. This has been somewhat controversial in the last few years. Some people think there should be no mention of God in the Pledge of Allegiance. The Supreme Court has not ruled on this issue – we say it “rules” on an issue, we mean it decides the issue. Our Supreme Court is the highest legal authority in interpreting the Constitution in the United States. Some people have tried to stop the government from forcing, or obligating, students to say the Pledge of Allegiance with this word, “under God.” They have not yet been successful, though it might happen in the future.
There aren’t many times when adults say the Pledge of Allegiance, it’s something that you say mostly as a child in school. We don’t say it at public gatherings usually; we don’t say it before a sporting event – a baseball game. We do sing the National Anthem, and in a later Café, I will talk about the National Anthem and what the words are and what they mean. But the Pledge of Allegiance is a good place to start because it is known by most Americans, especially those who went to school here in the United States.
I mentioned the Supreme Court as being the most important – the highest legal authority in the United States. The Supreme Court decides important – usually important – legal questions. I saw an article recently, which I thought was interesting, about a Supreme Court decision back in the late 19th century, just a few years after the Pledge of Allegiance was written.
In 1887, the U.S. Congress passed a law that the president approved – the president signed, we would say – that put a tax on certain things that were brought into the country. A tax on things that you bring from other countries back to the United States to sell in the United States is called a “tariff” (tariff). Another word for “tariff” is “duty” (duty). You can also pay a duty if you come into the United States as a visitor, or if you are a citizen of the United States returning to the United States with a lot of gifts, for example, you may have to pay a tax. We call that a “duty.” You will have to, when you come to the United States, fill out a form – put information on a piece of paper. If you have bought a lot of materials, gifts, or are bringing things into the United States that are very valuable, you may have to pay a tax on them, and that tax is called a “duty,” or a “custom duty.”
Tariff laws, then, have duties that are put on things that are imported into the United States, and in the late 19th century Congress passed a law that put a duty – a tax – on vegetables, but not on fruits. So vegetables were taxed, but fruits were not. This is important – or, I think at least a little interesting – because somebody said, “Well, what about the tomato?” What about tomatoes? Are tomatoes a fruit or a vegetable?
Well, the word “fruit” is actually a scientific term, and a tomato, technically, is a fruit, just like an apple is a fruit, or an orange is a fruit. A tomato is a fruit, if you look at the scientific side of things. However, the Supreme Court got a case – had people complaining to it – that the tomato was not a fruit, but a vegetable. Because it was a vegetable, you had to pay taxes on it, a duty if you imported it into the United States. If they are a vegetable, you do; if they are a fruit, you do not.
Well, the Supreme Court ruled unanimously – meaning everyone agreed on the court, there are nine members on the Supreme Court – everyone agreed that even though scientifically a tomato is a fruit, it is used more as a vegetable. “Vegetable” usually would refer to things such as lettuce, onions, things that you eat with your main entrée – your main dish, your main meal. “Fruit” is usually something you would eat at the end of your meal as a dessert. So the Supreme Court said that tomatoes are a vegetable for the purpose of this tax, so that you had to pay a tax on tomatoes, even though scientifically they are a fruit, they are used more like a vegetable.
Well, I thought this was an interesting case when the U.S. Supreme Court decided that tomato is a vegetable. Although nobody talks about this anymore, it is something that is still recognized by the U.S. government; it is officially classified as a vegetable. So when you come to the United States, remember that even though a tomato is technically a fruit, here it’s a vegetable.
Now let’s answer a few of your questions.
Our first question comes from Uwe (Uwe) in Germany. The question has to do with the expression “raised in” versus “grew up in.” For example, what does it mean when someone says, “I was born and raised in Minnesota,” or, “I grew up in Minnesota.”
Let’s start with the first part, “I was born.” To be “born” means to come out of your mother as a baby. To be “raised” means where you spent your time as a child and/or as a teenager. I was raised in Minnesota. I went to school there, I went to elementary school, secondary school, I even went to college there. I was born in Minnesota and I was raised in Minnesota. I could also say I “grew up” in Minnesota.
For some reason, it’s more common for people, if they’re going to say that they were born in a place to add they “were raised” rather than they “grew up.” So you hear people say “I was born and raised in California” – that’s where I was born in the hospital and that’s where I went to school as a child. You will also hear people say “I grew up in Minnesota,” or “I grew up in New York.” They don’t often use it with the expression “I was born.” It’s possible – it means the same thing. Of course, you can be born in one place and grow up in another. You could be born – as a baby – in Chicago, and then your family moves to Detroit – another city – and you were raised, or grew up, in that city.
Another thing about the verb to be “raised,” you can be raised by someone: “I was raised by my grandmother.” My parents, for example, may have not been alive and my grandmother is the person who raised me. Or, if your father dies when you are young, you may be raised by your mother. That’s not something you can say with “grow up,” you can’t say “I was grown up by my mother” – cannot say that. You can say “I was raised by” someone. So, to be “raised” can be used to mean the same as “grow up,” but it also can be used to indicate who was your parent or who was the person who took care of you.
Our next question comes from Liu (Liu) in China. The question has to do with the difference between two verbs, “to buy” and “to purchase” (purchase).
“To buy” and “to purchase” mean the same thing; it means giving money to someone and getting something back in return. You can buy a new computer – you give someone money and they give you your computer. You can buy things; you can buy services.
“Purchase” is the same, however we use purchase in a little more, perhaps, formal situation. For example, when you are working in a company you probably would say, “We are going to purchase some new office equipment.” You can also say “We are going to buy new office equipment,” but it’s a little more formal.
In a business, there is often a system that businesses use when they are going to buy new equipment. They fill out a form – a piece of paper – called a purchase order. A “purchase order” is a promise to pay for something that you are going to buy, but we don’t call it a “buy order,” we call it a “purchase order.” So, it’s a little more formal, used in a little more formal situations, but they mean the same thing – “to buy” and “to purchase.”
Our next question comes from Gerhard in Germany (Gerhard). He wants to know the meaning of the expression “to take the bull (bull) by the horns (horns).”
A “bull” is a male cow, you could think of it. “Horns” are things that come out of the head of an animal. Bulls have horns that are short and sharp. They can injure you, or hurt you, if you touch them, or if the bull touches you with them.
The expression “to take the bull by the horns,” however, means to take control of a situation – to deal with a difficult situation, not to avoid it. You may have a difficult situation at work, you don’t get along with someone you work with and so you just don’t talk to them – you don’t go near them. Someone may say to you, “You need to take the bull by the horns” – you need to actually control the situation – deal with or handle this difficult situation, stop avoiding it.
Finally, Ricardo (Ricardo) in Argentina has a question about the difference between the words “can,” “may,” and “could.” This is tough question; we use these words frequently in English and they can mean some slightly different things.
I’ll give you a short explanation, especially when we use these words for asking for permission to do something – you want to do something but you have to ask another person. “Can,” “may,” and “could” could all be used to ask a question. Technically, or strictly speaking, “may” is the most correct form for asking for permission: “May I leave the room now?” “May I have another sandwich?” You’re asking for permission. But it’s considered somewhat formal, so many people in a more informal situation will say “can”: “Can I have another sandwich?” “Can I leave the room now?” You could also say “could”: “Could I have another sandwich?” “Could I leave the room?”
So, if you are talking to your friend or a member of your family, you would say, “Can I ask you a question?” or “Could I ask you a question?” But if you were talking, perhaps, to your boss or in a more formal situation, you would probably say, “May I ask you may question?”
There are other uses of “can,” “may,” and “could,” but when we are talking about asking for permission, that’s how we would use those three words.
That’s all we have time for today. From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
pledge – a vow; a promise; a commitment; a serious statement that one will do something
* The president made a pledge to increase money for education.
allegiance – loyalty; one’s continued support for an organization or person
* The soldier swore his allegiance to the king.
unison – together; with many people acting as one; in harmony
* At the school performance, the students sung the closing song in unison.
to stand for – to represent; to symbolize; to mean the same thing as something else
* A red rose stands for love, and a yellow rose stands for friendship.
indivisible – strongly united; strongly held together; cannot be divided or separated
* The laws were made so that the state is indivisible, and even if cities wants to separate and join another state, it cannot do so under this law.
tariff – money that must be paid when products move into or out of a country
* How much is the tariff when you import Japanese cars into the United States?
duty – a tax; an amount of money that must be paid to the government when one buys something
* Many countries have high duties on alcohol and tobacco.
to rule on – to make a legal decision about something; to decide a case in a court of law
* The U.S. Supreme Court rules on many important issues every session.
unanimously – with everyone in agreement; with everyone sharing the same opinion; all together; without any exceptions or disagreement
* The team unanimously decided to choose Jill as their leader.
to be raised in (a place) – to be a child in a particular place; to spend one’s childhood in a particular place with the love and protection of someone
* Yolanda was raised in Texas, but now she lives in Maine.
to grow up in – to be a child in a particular place; to spend one’s childhood in a particular place as one grows older
* Did you grow up in Boston, or did you move here recently?
to buy – to get something by paying money for it; to give money to get something
* The Winfreys bought a new home in Atlanta.
purchase – to get something by paying money for it; to give money to get something
* We need to purchase a new refrigerator because the old one stopped working.
to take the bull by the horns – to do something without delay; to do something right away and without complaining, even though it is difficult and/or unpleasant
* Quincy didn’t want to paint the house, but last weekend he decided to take the bull by the horns and do it.
What Insiders Know
God Bless America Versus This Land is Your Land
God Bless America is a “patriotic” (proud of one’s country) song that was written in 1918. Many people think of it as the United States’ unofficial national “anthem” (a song that is very important for a country), because it is more popular and easier to sing than the real national anthem, The Star-Spangled Banner.
However, Woodie Guthrie, a famous American “folk singer” (a musician with a traditional, country style) didn’t like God Bless America. He thought it was “unrealistic” (not related to real life), and so he wrote a song “in response” (in answer to something) called This Land is Your Land in 1940.
Let’s look at the “lyrics” (the words to a song) for both of these songs. Here are the words to the “chorus” (the lines that are repeated many times during a song) for God Bless America:
God bless America, land that I love
Stand beside her and guide her
Through the night with the light from above
From the mountains, to the prairies,
To the ocean white with foam
God bless America, My home sweet home.
The lyrics to the chorus of This Land is Your Land are:
This land is your land, this land is my land
From California to the New York Island
From the Redwood Forest to the Gulf Stream waters
This land is made for you and me.
Both of these songs are patriotic and show that Americans love their country. God Bless America is more religious and asks God to “bless” (to ask God to protect something) the country. This Land is Your Land is more about how the country should be shared by all Americans.