= 1421
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast English Café number 116.
This is the English Café episode 116. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. If you go there, you can download a Learning Guide for this episode, an 8 to 10 page guide to help you improve your English even faster. You can also take a look at our ESL Podcast Store, which has some additional courses in business and daily English.
On this Café, we’re going to talk about two fictional characters that are very popular in the United States among children. They are the “Tooth Fairy” and the “Easter Bunny”; we’re going to talk about what those characters are and why they’re famous in the U.S. We’re also going to talk about four common hand gestures. Every culture, every country has its own way of using body language and gestures – movements of your hands and arms – to express certain ideas. We’re going to talk about some of the common hand gestures in American culture. And as always, we’ll answer a few of your questions. Let’s get started.
The first thing we’ll talk about on this episode is the Tooth Fairy and the Easter Bunny; let’s begin with the Tooth Fairy. The Tooth Fairy is a traditional fictional – imaginary – children’s character that parents tell their children about. The Tooth Fairy gives children a small amount of money, or sometimes a small gift, in exchange for a baby tooth when it falls out of the child’s mouth. In other words, when a child loses one of his teeth – and of course, all children lose their first set of teeth when the second, larger set comes in; these are sometimes called “baby teeth.” When a child loses a baby tooth, the Tooth Fairy takes it and gives them money in exchange for, or in return for the tooth.
Now, when a child loses his or her tooth, they put it underneath their pillow – the thing they put their head on in the bed – before they go to sleep. So, let’s say a child loses his tooth in the afternoon, that night he would clean it and put it underneath his pillow. When the child wakes up the next morning, the tooth is gone and there is a quarter (25￠) or a small amount of money where the tooth had been.
Now, in some families the custom is a little different. The child puts the tooth in a glass of water next to his or her bed, and then the parent – well, the Tooth Fairy takes the tooth out and puts a coin in. Of course, it’s the parent who is doing that, but you probably guessed that since there is no such thing as a Tooth Fairy. When we say “there’s no such thing,” we mean it doesn’t exist. But, the Tooth Fairy is very popular, very common; almost every American family will have parents that tell their children about the Tooth Fairy, and give their child a quarter or a small coin when they lose a tooth.
The reason for this custom – this tradition – is probably to give children a small reward when they lose something, like their tooth. It may also be a little painful for them. It, in other words, gives them a little something to look forward to; even though they lost their tooth, now they have a quarter. I have always thought that there should be, for adults, a “Hair Fairy,” so that if you lose your hair, you can put it under your pillow and get some money for it. If we did that, I would be a rich man! But that idea has not become very popular.
The other fictional character for children that we’ll talk about today is the Easter Bunny. A “bunny” (bunny) is another word for a “rabbit,” a small animal that jumps up and down.
The Easter Bunny brings children gifts and candy on Easter Sunday. Easter Sunday is a celebration in Christian churches of the resurrection of the Christian savior, Jesus. Easter Sunday is not an official holiday, but it is celebrated in the United States on a Sunday during the springtime. The “Easter Bunny” is the imaginary character that brings children small gifts on the morning of Easter. So, a child goes to sleep, wakes up, and just like Santa Claus at Christmas, there are small gifts for the child. Usually, the gifts are in what we call a “basket,” which is a small, round container. In some families, the children leave carrots out where the Easter Bunny will be coming, because the idea is that rabbits like to eat carrots.
The Easter Bunny also usually hides eggs that children will try to find on Easter morning. These could be real eggs that are “hard-boiled,” meaning you cook the egg so that it is solid. More popularly, however, parents buy plastic, colored eggs, and they put candy or some sort of sweet inside of the egg. The most popular candy for Easter eggs is jellybeans. When I was growing up, every Easter morning we would wake up and we would have an “Easter egg hunt.” “To hunt” here means simply to look for. So, we would have this Easter egg hunt, and we would go around the house looking for these little plastic eggs that had candy in them. Of course, my older brothers or my parents were the ones that hid the Easter eggs – I think! In any case, Easter egg hunts are actually very popular; sometimes you will even see them at a park.
There’s also a tradition of taking real eggs and cooking them, and painting the outside of the egg. The outside of the egg is what we called the “eggshell” (shell), that’s the hard part of the egg that you take off before you eat the egg. There are many families that color Easter eggs, and that’s something that you do either on Easter or in the week before Easter. Once again, it’s part of the celebration.
Our second topic today is “hand gestures,” things that Americans do with their hands or their arms to communicate some sort of message. We’re going to look at four of these. These may be the same in your country; they may be different.
The first one is “thumbs up.” To make the “thumbs up” gesture, you make a fist with your hand – you put your four fingers against the flat part of your hand, the “palm,” and you put your thumb up in the air. The “thumbs up” gesture indicates approval. It’s a very old hand gesture; the Romans, for example, used it during the time of the gladiator fights. The tradition was the emperor would put his thumb up if he wanted the gladiator to live, and a thumbs down if the gladiator wasn’t going to be able to retire, shall we say.
Well, “thumbs up,” in U.S. culture, means approval, something that is good. You can even use it to say that someone gave you approval: “My boss gave me the thumbs up on my proposal.” Notice we use “the” – “gave me the thumbs up.” You can also just say simply, “thumbs up,” meeting yes, good.
In the last 25 years or so there is a slightly different meaning of the expression “thumbs up.” It comes from a popular television program that every week has two movie critics – movie reviewers, two people who talk about movies and whether they like them or not. The original show was called Siskel and Ebert; those were the names of the two critics, Gene Siskel and Roger Ebert. Gene Siskel died a few years ago, and now it is called Ebert and Roeper; they have a different critic.
On the show, each critic gives either a thumbs up or a thumbs down to a movie, if they like it, it’s a thumbs up. The phrase “two thumbs up” means both critics liked it. That expression has now become famous; if you look at a advertisement for an American movie in the newspaper, you will sometimes see just the expression “two thumbs up.” That means that those two critics – those two famous reviewers on the television show liked the movie. In fact, I believe they’ve even copyrighted that expression: “two thumbs up.”
Another gesture is the “high five.” “High five” you will sometimes see in athletic games – in basketball games, for example – when one person will put their hand up in the air and spread out their fingers, and another person will put their hand up in the air, and they will hit each other’s hands – they will slap each other’s hands. (Jeff slaps his hands together) That’s a “high five” – five, of course, for your five fingers. “High five” means that you are either congratulating someone on doing something well, or that you are both happy about something. If your team wins the game, you may give each other a high five. It’s a “high five” because your hand is high up in the air.
Now, sometimes people put their hand up in the air expecting the other person to give them a high five, and the other person doesn’t, and so the person just has their hand in the air, looking a little ridiculous. That’s usually considered sort of embarrassing; we say that the person was “left hanging,” meaning they were left there without anyone giving them a high five.
“Air quotes” is the third gesture we’ll talk about. “Air quotes” is when you take your two fingers – your first and second finger, your “index” and your “middle” finger we call them. You put them up in the air, with both hands, and you make a gesture that looks that you are making two quotes, or a quote and an unquote.
This gesture is used to mean that what you are saying isn’t necessarily true; it is often used to make a joke. For example, you may be talking to your husband or wife about your young child and you may say, “The ‘boss’ tells us that we need to go home and put him to bed.” The “boss” refers to the child. But of course, the child isn’t the boss, so you use these “air quotes”; as you’re saying the words “the boss” you do the gesture with the quotes. So, the “boss” says we need to go home, that’s a way of using the air quotes to make a sarcastic or an ironic remark. Sometimes people will also just say the words “quote unquote.” For example: “The quote unquote boss says we need to go home.” That’s the same idea.
The final hand gesture we’ll talk about is very famous; you’ve seen it in movies and TV shows perhaps. We call it, in the U.S., simply “the finger.” “To give someone the finger” is to make a vulgar – an obscene gesture. You make a fist and stick your middle finger up in the air, and you move your hand towards that person or you show it to a person. It is a very negative, insulting gesture. You can get in trouble by making someone very angry when you give them the finger. The meaning is probably already known to you; you’re telling the person that you don’t like them very much – let’s just say that!
Sometimes people will put three fingers up: the index finger, the middle finger, and the third finger, what we would call the “ring” finger, and say “read between the lines,” meaning look at the finger in between the two other lines – the two other fingers. The expression “to read between the lines” we use in talking about newspapers or books. If you say “read between the lines,” you mean interpret the message, it’s not directly stated, but if you can understand the general context you will understand this “implicit,” or unstated, message. Here, it’s just a funny way of giving someone the finger.
We also use the expressions “to give someone the bird”; “the bird” is the same as “the finger.” You can also say “I flipped him off.” “To flip (flip) someone off” means the same as to give them the finger. You have to be careful then, in the U.S., if you’re scratching your face, or doing anything where you have the middle finger extended by itself. Someone may interpret that as giving the finger, which, of course, you don’t want to do. So that’s not a nice gesture, never to be done publicly – really probably should never be done, but people get angry and they use it.
I won’t give you the finger; instead I’ll answer a few of your questions.
Our first question comes from Abdulkadir (Abdulkadir) in Germany. The question is: “What is the difference between progress and process?”
“Progress” means moving toward a certain goal or a certain place, or getting close to completing something. It can also mean improving over time. Your boss may ask you how much progress you have made this week. Notice that we use the verb “to make” with progress. You “make progress,” that means you have done better – you are advancing, you are going forward. You may ask your child’s teacher, “Is my son (or daughter) making progress?” – are they doing better? They’ll tell you, of course, that they are – even if they’re not! That’s what some teachers do anyway; I would never do that!
I’m using “progress” in these examples as a noun; you can also use it as a verb. It’s pronounced slightly differently; we say “progress,” with the stress on the second syllable. “Progress” is the noun; “progress” is the verb. “To progress” is the same as “to make progress.”
“Process” is a series of steps – a series of actions that need to be completed in order to achieve a specific goal. For example: “Learning to play the guitar well is a long process that can take many years,” you have to go through several different steps – several different phases. Or, someone may ask you, “What is the process for becoming a U.S. citizen?” – what are the things that you have to do to obtain or achieve that goal?
Giovanni from Italy has a question about the use of the expression “I would go.” In English Café number 90, I said when I was a child and a teenager, “I would always go to the State Fair.” Tobi (Tobi) in Germany has a very similar question. He noticed that in English Café number 91 I said when I was a teacher, “I would have parent-teacher conferences four times a year.” Once again, what is the meaning of this use of the word “would”?
Well, “would” can be used to express what we would call a “conditional” idea: “I would go to the story if I had money.” It’s a hypothetical – it’s an imaginary situation. That’s one place where we use “would.”
In talking about things in the past, we can also use “would” to mean something that was repeated over and over again, something that happened or was ongoing for a long time. “When I was young, I would go to the baseball park and play” – I didn’t go just one time, I went many times. You could also say “When I was young, I went to the baseball park,” but there you don’t know if it was one time or many times. If you want to say you went frequently, you would use “would.”
Some languages have two different forms of the verb to express an idea that is finished – over and done – versus an idea that is continuously going on in the past. In English, we call it the “preterit” and the “imperfect”; other languages have a similar distinction. In English, we use this word “would” to express the imperfect idea, that is, something that is going on in the past repeatedly – many times.
We often use this expression when we are telling a story. For example: “When I was in college, I would look at the pretty girls and I would ask them for their telephone number, and they would always say no.” That’s something that happened very frequently in my past!
Finally, Angelica (Angelica) in Italia – in Italy, wants to know the meaning of the expression “to be on the chunky (chunky) side.”
“To be on the chunky side” is an informal expression that means to be a little fat, a little overweight; but not very fat, not very overweight. Sometimes we use this as a slightly more polite way of describing a person who is a little fat, who has a little too much weight. Even so, it’s not a very nice thing to talk about when you are referring to someone’s weight. It’s certainly not a compliment, but it is meant to be a little more polite.
On ESL Podcast number 305, I talked about people’s body types, so if you haven’t listened to that, that would give you some additional vocabulary in describing people’s bodies. If I described myself, I would say that I was very thin when I was a young man, and now I’m a little on the chunky side. I have to stop eating all of those cookies!
If you have a question that you’d like us to answer on the English Café, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
fairy – an imaginary, small person in many stories who can fly and has other magical powers
* Tinkerbelle is a famous fairy in the story of Peter Pan.
baby tooth – a tooth in a child’s mouth that falls out and is replaced by a larger, adult tooth
* How old were you when you lost your first baby tooth?
there’s no such thing as (something) – a phrase used to mean that something doesn’t exist, or that something isn’t real
* My professor said that there’s no such thing as an energy source that’s completely good for the environment. They all hurt the planet in some way.
bunny – a rabbit; a small or young rabbit
* The bunnies in this field have white bodies with brown ears and tails.
basket – a container made from small pieces of grass, plastic, or wire that are woven (folded on top of one another) together to hold things
* The waiter brought her a basket filled with teabags to choose from.
hunt – a search for something that is hidden and difficult to find
* When I was growing up, our birthdays always began with a hunt for our presents.
eggshell – the hard, thin, white or brown skin around an egg that must be broken and thrown away before eating the egg
* The cook was careless when breaking open the egg and there were little pieces of eggshell in the food.
palm – the inside part of one’s hand, between the wrist and the fingers, that is covered with lines
* Shane held the small bird in the palm of his hand to show his sister his new pet.
thumbs up – a gesture in which one folds one’s fingers into one’s hands and holds one’s thumb up in the air to show one’s approval of something
* If you answer correctly, the teacher will give you a thumbs up.
air quotes – a gesture in which one holds up the index and middle fingers of each hand in a “V” shape near one’s shoulders at each side of one’s head and moves the fingers up and down two or three times, used to show that what one is saying at that time is the words of another person, or to show that one doesn’t really mean what one is saying
* Iris was telling a funny story about her co-worker, but she didn’t want to use his name, so instead she used air quotes every time she referred to him, saying “Mr. Stupid.”
to give (someone) the finger – to flip someone off; to make a rude and offensive gesture in which one holds up the middle finger of one’s right hand with the back of one’s hand toward another person to say, “fuck off” or “fuck you” (an extremely rude phrase used to show that one is angry with another person)
* The men were making rude comments about the women walking by, so one of the women gave them the finger.
to flip (someone) off – to give someone the finger; to make a rude and offensive gesture in which one holds up the middle finger of one’s right hand with the back of one’s hand toward another person to say, “fuck off” or “fuck you” (an extremely rude phrase used to show that one is angry with another person)
* When another driver almost hit her car, Rachel yelled and flipped him off.
progress – advancement toward a goal; the process of improving or changing over time
* Have you made any progress on your college applications yet?
process – the things that must be done to make something happen
* Buying a metro ticket is a four-step process: (1) choose which ticket you want to buy, (2) put your money in the machine, (3) push the “okay” button, and (4) take your ticket.
to be on the chunky side – to be a little bit overweight; to be a little bit fat
* I hadn’t seen Harold in a year, so I was surprised to see that he is now on the chunky side.
What Insiders Know
Gang Signs
A “street gang” is a group of young people who spend a lot of time together and often “get into trouble” (behave badly and create problems) and fight with other gangs. In larger cities, gangs can be very dangerous, with members killing members of other gangs. Many gangs have “gang signs” (things that they do or use to show which gang they belong to). These gang signs can include clothing, “tattoos,” “graffiti,” and hand signs.
Typical gang clothing includes “leather jackets” (coats made from cow skin), “chains” (metal rings that are connected together), and colored “bandanas” (a square piece of colored fabric that is usually worn on one’s neck or head).
Another common gang sign is a “tattoo” (a permanent drawing on one’s skin, made by using a needle to put colored ink under the skin). Normally all the members of one gang will have the same tattoo design.
Other gangs like to use “graffiti” (text or drawings painted onto public walls, where they shouldn’t be) to “mark their territory” (show which areas belong to a particular gang). Sometimes the graffiti is very “elaborate” (detailed), but other times it is just a “tag” (a simple symbol for the gang that can be painted quickly). Gangs often paint their graffiti over other gangs’ graffiti, and this is known as “mark out” graffiti.
Finally, hand signs are a common gang sign. Many gang members put their fingers in the shape of a letter that identifies their gang. Other gangs use special gang “handshakes” (ways to touch another person’s hand, usually to say hello, goodbye, or to show agreement). Some gangs prefer hand signs over other types of gang signs because they aren’t always “visible” (able to be seen), like tattoos are.