= 1448
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 143.
This is English as a Second Language Podcast’s English Café episode 143. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, which has additional courses in business and daily English I think you may enjoy.
On this Café, we’re going to talk about Harley Davidson motorcycles. What they are, and why they are important to the culture of the United States – at least, to part of our culture. We’ll also continue our series on famous Americans. Today we’ll be learning about the life and accomplishments of Jesse Jackson. And as always, we’ll answer a few of your questions. Let’s get started.
Our first topic today is Harley Davidson motorcycles. A somewhat unusual topic, I will admit, for our Café, but I hope that you will see that it is, in fact, an interesting part of American culture.
The Harley Davidson Company is based in the state of Wisconsin, which is in the mid-western – the upper mid-western part of the United States, next to the State of Minnesota, north of the State of Illinois, and just east of the State of Michigan.
Harley Davidson Motor Company manufactures (or makes) very popular motorcycles in the U.S. The motorcycles are called “Harley Davidsons,” or sometimes simply “Harleys.” Many people who own these motorcycles are very loyal to the Harley Davidson brand – to the type of product that they produce. To be “loyal,” in this case, means to always use a particular product or always try to promote a particular product – to think good things about them. A “brand,” as I said, is really a name that a company puts on its products – in this case, “Harley Davidson.” When I say that people are loyal to the Harley Davidson brand, I mean that they will buy only Harleys when they want a motorcycle.
Many of these people buy other Harley Davidson products as well, such as t-shirts, stickers, and other and just about any other item that show the Harley Davidson logo. A “logo” (logo) is a small image, sometimes with some writing on it that identifies a company or organization. If you go onto the ESL Podcast website, in the top left corner you will see the ESL Pod logo, designed by our wonderful webmaster, Adriano Galeno. The Harley Davidson logo is black, orange, and white. You can see these on jackets, you can see these on t-shirts; they’re very popular among people who ride Harley Davidson motorcycles.
The Harley Davidson Company was founded more than 100 years ago, in 1903. The company’s motorcycles became very popular almost immediately. In 1917, the U.S. government bought more than 20,000 Harleys to use in World War I. Many of the soldiers and the other men who used the motorcycles during the war liked them so much that they bought their own Harleys when they came back to the United States. Very soon after, Harley Davidson became the biggest manufacturer of motorcycles in the world.
Then, unfortunately, came the Great Depression, that period of time from the late 20s and through the 1930s, when the United States and, really, the world economy was very bad and there was very little extra money for people to buy things like motorcycles. For this reason, the company actually stopped making motorcycles, or at least, stopped focusing on motorcycles – I believe they continued to make them – and instead made engines for factories. An “engine” is the part of a machine that provides the power or the energy. In your car – in an American car, your engine is usually in the front of the car.
Well, the plan, or strategy, worked for Harley Davidson. They were only one of only two motorcycle manufacturers to stay in business during the Great Depression, and when World War II started, at least for the United States involvement in World War II in 1941, the company made many more motorcycles for the U.S. government. Then it began selling motorcycles again to civilians, people who are not in the military, and it continues to do so today. So, after the war, Harley Davidson was successful again at selling motorcycles to the average person, not just to the government.
Harley Davidson Company’s “reputation,” what people think of it, suffered, or got worse, when the company changed ownership. We sometimes say your reputation “suffers.” Normally, “suffer” is a verb we use to talk about human pain, but here it refers to a decline, or decrease, or worsening of your reputation. The Harley Davidson Motor Company’s reputation suffered when it was bought by another company that changed the way motorcycles were made. The quality of the motorcycle got worse; it “deteriorated.” People began to use pejorative names for the motorcycle. Something that is “pejorative” (pejorative) is very negative. The pejorative names for the Harleys included: “Hardly Drivable,” meaning you could almost not drive them, they were so bad, and “Hogly Ferguson.” I’m not sure why “Hogly Ferguson,” but these were negative names – pejoratives that people used about the motorcycle because they thought the quality of the motorcycle declined. Some people continue to refer, even today, to Harley Davidson motorcycles as “Hogs.” “Hog” is another name for a large pig. It’s not considered a pejorative term anymore, however, but people who like Harley Davidsons.
Another reason why Harleys began to have a negative reputation in the U.S. was because the motorcycles became associated with, or thought to be connected with, a particular motorcycle club called “Hells Angels.” Hells Angels is a motorcycle organization – a club for people with similar interests. The members say that they enjoy riding motorcycles together. They typically organize long trips, parties, and other events. But many people, especially police officers – members of what we would call “law-enforcement agencies,” basically the police – began to think that Hells Angels was a violent gang; they were selling drugs and had done other bad things. So, the motorcycle got a bad reputation because it was associated with this one particular group, who were, at times, very violent in the late 60s and in the early 70s. Many people today still consider Harleys to be associated with this negative group; if you rode a Harley, you were considered almost a criminal.
But the situation is actually quite different nowadays. Back in the 60s and 70s, the average age of someone who rode a motorcycle in the United States was probably in their 20s. Today, things have changed. Most motorcycle owners – most Harley owners tend to be well educated, usually wealthy men in their mid-40s, not their mid-20s. So basically, the people who used to ride them 20-30 years ago continue to ride them, or those who are now in their 40s and 50s decided that they wanted to ride them. This is kind of interesting because my neighbor, the one with all the screaming children, he has a new motorcycle – a Harley motorcycle – and he’s probably about 48-47, something like that.
Many time, the owners of Harley motorcycles are doctors, dentists, and lawyers. They get together often on the weekends and take very long rides together. The funny thing is they often dress as if they were 20 years old again! They dress in black leather; they often wear “chains,” which are small circles of metal that are connected to each other. Many people say these men are in a mid-life crisis. The “mid-life crisis” is supposed to be that period of time when you start worrying about getting older. “Mid-life” means in the middle of your life; a “crisis” is an emergency situation. So, this is a time when particularly men are supposed to start worrying about how old they are, and so they start doing things that make them feel younger. They buy a nice, new sports car, or they buy a motorcycle, or they start a podcast to teach English – something like that!
There’s a Harley Davidson store not too far from where I live, and it is interesting to see that most of the customers – most of the people who go there and buy them – are not young kids, they’re not criminals; they’re wealthy men who want to feel younger, in many ways. But others say that these men drive these motorcycles just because they enjoy it, and of course, that’s part of the reason as well.
The second part of our Café is going to be about famous Americans. Today we’re going to talk about the Reverend Jesse Jackson. “Reverend” is a title of respect we use when referring to a minister, a preacher, a pastor – anyone who leads a church and who speaks to other people about faith and religion, we call that person a “reverend.” Could be a Catholic priest, could be a Baptist minister – any of those folks would be called “reverend.” The Reverend Jesse Jackson is a Baptist minister, but he’s really much more famous for being a civil rights leader, or a civil rights activist.
In the United States, when someone says “civil rights,” usually they’re talking about the ability for everyone to be able to practice their own religion or to vote, to have the same rights as other people in the society no matter what color their skin is or what group they belong to. An “activist” is a person who really tries to change the world – to change society, to work hard for that change. The Reverend Jesse Jackson is a civil rights activist, just as the Reverend Martin Luther King, Jr. was a civil rights activist. Both Reverend Jackson and Reverend King fought for the rights of African Americans – for blacks. Another famous civil rights activist would be Susan B. Anthony, who fought for a women’s right to vote more than 100 years ago.
Jesse Jackson’s life is actually somewhat interesting. He was born in 1941 in the state of South Carolina, which is in the southeastern part of the United States, just south of North Carolina – of course! Back in the 1940s in the United States, especially in the southern part of the U.S., there was a lot of discrimination. Jesse Jackson attended, or went to, a segregated high school. When we say something is “segregated,” we mean it is separated by race, or skin color. Busses in the United States, in many places, used to be segregated, with whites sitting in the front and blacks sitting in the back. Still today, we have this expression “to sit in the back of the bus,” or “to be in the back of the bus,” it means to be discriminated against, to be to segregated, to be considered less than a full citizen.
Well, Jesse Jackson went to a segregated high school that was only for black students. Later he entered the University of Illinois, which is in a northern state; Illinois is south of Wisconsin. The University of Illinois was racially integrated at that time. “Integration” is putting things together; “segregation” is pulling them apart. So, a “racially integrated” university would be one where both white students and black students studied together. Jesse Jackson still had problems. He was on the football team, and he had problems in some of his classes at the university. In fact, he had so many problems he left the University of Illinois and went to another college.
Jesse Jackson “came of age” (began to enter his adulthood) during the time of the civil rights movement in the 1950s. The civil rights movement was a period when many people began fighting for blacks’ civil rights in the 50s and 60s. Many of these people began to work with the Reverend Martin Luther King, Jr., who is, as you probably know, one of the most famous civil rights leaders in U.S. history. Jesse Jackson joined Reverend King on civil rights marches. A “march” is an event where many people walk together in order to demonstrate their support for a certain thing, in this case, civil rights.
Jesse Jackson became the national director of an effort to change people’s habits – people’s practices – in order to force white-owned businesses to hire more black employees. He created an organization also, called Rainbow/PUSH, and in fact, he became famous for a particular phrase, the “Rainbow Coalition.” The Rainbow Coalition was the idea that people of different races – of different colors – would come together and join together to cause political change – to make things change in society.
Jesse Jackson was very active in politics, especially in the 1980s and 90s. He actually ran for president in 1984, and won some states. During the 1990s he served as a “shadow senator” for Washington, D.C. Washington, D.C. does not have its own senator – its own elected representative in the U.S. Senate because it is not a state. So, he basically acted as if he were a senator, even though he didn’t have any right to vote.
Today you will still see the Reverend Jesse Jackson on television talking about civil rights – talking about “racism,” discrimination against people because of the color of their skin. Jesse Jackson is also famous for his speaking style. He would often make rhymes of things, words that would sound alike. For example, he used to say in the 1980s, “Down with dope, up with hope.” “Dope” is an informal word for illegal drugs. To say “down with” means we are against that particular thing, so we are against drugs. “Up with” means to be for something, we are for hope. So, “Down with dope, up with hope.” Jesse Jackson would often use expressions and phrases like that that had a rhyme in them, where two words sounded similar.
I’m very poor at rhymes, but now it’s time to answer your questions.
Our first question comes from Kei (Kei) in Japan. Kei wants to know the difference between “because” and “since.” For example, in the sentence: “I can’t go to the store because I don’t have any money” – “I can’t go to the store since I don’t have any money.”
“Because” usually answers the question why: “Why can’t I go to the store? Because, I don’t have any money.” “Since” can also sometimes be used in the same way as “because.” “I went shopping since I had no school this morning” – I didn’t have to go to school. “She doesn’t want to marry him since he’s a jerk” – he’s an idiot!
“Since” has other uses; “since” can also be used to describe a period of time after a certain point. Here, it’s different than “because,” it’s used differently. It really answers the question when an action began to take place, when something started. If someone asks you how long have you listened to ESL Podcast, you could say, “Since July, 2005, when it first started.” Most of you probably didn’t start listening in July of 2005, but that’s an example of using “since” to talk about when something started. “Gas prices have gone up since the beginning of the year” – since the year began, that’s when they started to go up.
Pavel (Pavel) in the Czech Republic wants to know the definition of the expression “yikes” (yikes).
“Yikes” is usually followed by an exclamation point (!); it’s what we call an “interjection.” It’s something you say during a moment of great excitement – of great emotion. Usually it’s used to express surprise, sometimes fear, sometimes dislike of something. You could say, “Yikes! This pan is hot!” The pan on the stove that you use to cook with, if you touch it accidentally you might say “Yikes!” You could also say, “Yikes! What are you eating? It looks terrible.”
“Yikes” is a little old fashioned; you will still hear older people use it, but it’s not quite as common with the younger generation – at least, I don’t think.
Ladan (Ladan), from an unknown country, wants to know the meaning of the expression “speaking of which.”
“Speaking of which” is an expression we use when you are talking about a certain topic – a certain idea – and suddenly you think of something else that you want to talk about related to that idea. So, you may be talking about the beach, and then you say, “Speaking of which, did you know that it’s going to be sunny today, and it would be a good day for us to take a walk on the beach.” You were talking about the beach in general, or one aspect – one idea related to the beach, and then you thought of something else. Another example would be: “Mr. Gopal talked about elephants in class today. Speaking of which, he told me to tell you to see him before class tomorrow.” So, we’re talking about Mr. Gopal and what he said in class, and then I think of something that he told me, and I tell you a related idea – related, in this case, to Mr. Gopal.
It might be possible to say “talking of which” instead of “speaking of which,” but I don’t think I have ever heard anyone say that; the common expression is “speaking of which.”
If you have a comment or question, you can email us. Our email address is eslpod@eslpod.com.
That’s all we have time for on this episode. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
loyal – being faithful to something; always using or being a customer to a product or business
* When she became president of the company, she gave management jobs to the employees who had been loyal to her for years.
logo – a small image, sometimes with text, that identifies a company or organization
* Some people like to wear clothes with the logo of famous or high-status clothing companies.
engine – the part of a machine that provides power or energy; the part of a car or vehicle that makes it run
* Do you know why your car’s engine is making those funny noises?
reputation – the way that other people think about a person, organization, or something else
* Zia has a reputation for being generous with her friends and family.
pejorative – something very negative; expressing disapproval
* When his daughter’s boyfriend yelled at his daughter, he called the boyfriend a pejorative name.
mid-life crisis – a period of time in one’s life when one is worried about getting older and does and buys things to feel younger
* Lee had a mid-life crisis at the age of 45 and bought a brand new sports car.
reverend – a title of respect for a minister, preacher, pastor, or another person who leads a church and speaks to other people about faith and religion
* We spoke to the reverend at our church and he agreed to marry us next month.
civil rights – the things that everyone should be able to have and do, such as the freedom to practice religion or to vote, no matter what color a person’s skin is or whether they are a man or a woman
* They filed a lawsuit against the government for violating their civil rights.
activist – a person who strongly believes that something should be changed in society and works hard to change that thing
* Xander used to be lawyer, but now he’s an environmental activist.
segregated – separated by race, or skin color; separated for a specific purpose
* Let’s keep the two groups of people participating in this research study segregated until after we get the test results.
march – an event when many people walk outside together for some purpose, such as to show support for a cause or to show dislike of something
* Last year, we marched from downtown to city hall to protest the new state taxes.
shadow senator – an elected representative in the U.S. government from Washington, D.C., who cannot vote for or against laws and policies
* Even though she’s the shadow senator, she has a lot of influence on which policies are voted on.
because – for the reason that; since
* I don’t want to sing in front of my friends because I have a bad singing voice.
since – for that reason that; because; from a specific time in the past to the present
* Since I started exercising, I’ve had more energy and feel more relaxed.
yikes – an exclamation to show shock or alarm, often to be funny; something said to express surprise, fear, or disgust
* You have eight of your aunts, uncles, and cousins staying at your house this summer? Yikes!
speaking of which – an expression used when someone is talking about a topic and he or she wants to mention, ask about, or suddenly recall something related to that topic
* My favorite TV show is 60 Minutes. Speaking of which, did you see last week’s show?
What Insiders Know
The Classic Movie Easy Rider
If you were to ask Americans to name a classic “biker” (motorcycle riding) movie, there is a good chance the answer would be Easy Rider. Easy Rider was a 1969 film about two bikers who travel around the southwestern part of the United States to experience life and to meet people. Three of the main actors, writers, and directors of the film – Jack Nicholson, Peter Fonda, and Dennis Hopper – are well known and well respected actors today.
In the movie, two young bikers, Wyatt and Billy, get money by selling drugs in Southern California and begin their trip to find a lifestyle that is right for them. On the journey, they encounter hatred from small-town communities who “despise” (hate) and fear their “non-conformist” (not following the rules) views on life. However, Wyatt and Billy also discover people attempting “alternative lifestyles,” or a different way to live, who are resisting this “narrow-mindedness” (not willing to listen to or tolerate others’ views).
Easy Rider was one of the films that began a new way of making films in Hollywood during the late 1960s and early 1970s. The major film making “studios” (companies) realized that they could make money by making “low-budget” (low cost) films with “avant-garde” or new and experimental directors.
This way of making films reflected the social atmosphere and attitudes of the U.S. during this time. This was a period in American history of people’s, especially young people’s, increasing “disillusionment” (feeling disappointment after finding out that something is not good) with the government and the world. The film was nominated for many awards, including several Academy Awards for acting and writing.