= 1455
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 150.
This is English as a Second Language Podcast’s English Café episode 150. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. There, you can download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses, as well as our ESL Podcast Blog, where several times a week we provide even more help in helping you increase your language proficiency.
On this Café, we’re going to continue our series on famous Americans, talking about two great jazz music artists: Josephine Baker and Ella Fitzgerald. Then we’re going to talk about a special group of Americans called the Amish. And as always, we’ll answer a few of your questions. Let’s get started.
Our first topic is going to be famous Americans. Today we’re going to talk about two female jazz artists. “Jazz” (jazz) is, you may know, a type of music that has a very strong “beat,” or rhythm. Jazz is an American style of music that was created, or made, in the early 1900s – beginning in the early 1900s in the southern part of the United States. African Americans, or blacks, were the first jazz musicians, but today there are jazz artists of many different races. You have probably heard of some famous jazz artists, such as Duke Ellington, Louis Armstrong, and more recently, Wynton Marsalis. Today we’re going to focus on two famous female jazz artists: Josephine Baker and Ella Fitzgerald.
Josephine Baker was born in the U.S. in 1906, but spent most of her life in France. She was African American and was often called the “Black Pearl.” A “pearl” (pearl) is a small, round jewel that is found in oysters, a type of animal that has two shells and lives in the sea. Pearls are usually white, but some are pink, grey, and even black. Many women wear necklaces and earrings made out of pearls. When we call someone or something a pearl, it means that we like it very much; it is very valuable to us, and this is why Josephine was called the Black Pearl, because she was so well liked, such a great jazz musician.
Josephine was one of the first African American women to become a world-famous entertainer. “World-famous” means someone who is very well known and is famous all over the world. Every time you tell your friends and co-workers about ESL Podcast, you’re helping us in making our efforts to make me world-famous – even if it’s a very small world!
Josephine dropped out of school when she was 12 years old. To “drop out” means here to stop going to school before one has graduated. Normally this is a bad idea, since people who drop out often do not have good jobs; they don’t have a lot of qualifications. However, it was quite common for students to drop out of school in the early parts of the 20th century. However, it worked well for Josephine. At first she worked as a dancer, moving to Paris, where black dancers were more accepted than they were in the United States at that time. Josephine had a very interesting and popular dancing style, which included dancing, believe it or not, with a cheetah. A “cheetah” (cheetah) is a large cat-like animal that lives in Africa, normally; it has dark spots on its fur or hair, and can run very quickly. Her dancing was often very sexual in nature; she would often dance almost nude in her Paris shows in the 1920s.
In the late 1920s and early 1930s, Josephine began to act in movies and her “popularity,” or how much people knew and liked her, began to grow. She began singing jazz music and her popularity grew even more. However, she was not always well accepted or well liked here in the United States, so she eventually became a French citizen. A “citizen” is a person who belongs to a country and, usually, can vote in that country. Even though she didn’t live in the United States, however, Josephine was actively involved in the American civil rights movement, or the organized efforts to have equal rights for blacks and whites, and Asian Americans, and others.
While in Paris, Josephine Baker met many famous what we would call “expats” – expatriates, people who go to another country to live. Paris was very popular for American writers: people such as Ernest Hemingway, F. Scott Fitzgerald, the African American poet Langston Hughes, the Spanish artist Pablo Picasso, and others. Baker was a friend of these famous artists and writers, and was very well known in Paris and in Europe, as well as here in the U.S., of course.
Josephine remained in Paris even during World War II, where she worked with the French Underground, those French citizens who were trying to oppose the German occupation of France in World War II. She was given some of France’s highest honors for her work during World War II for the French Underground.
She continued to perform – to sing – in France and in other countries. She died in 1975 and was buried in Paris, where thousands and thousands of people came to her funeral.
Another famous American female jazz singer was Ella Fitzgerald. Like Josephine, Ella was African American. She is, however, much better known here in the United States as a jazz singer than Josephine Baker was. Many people called her the “First Lady of Song.” The expression “first lady” usually refers to the wife of the president of the United States, but when we say the “first lady of song,” we mean the woman who is best at singing.
Like Josephine Baker, Ella wanted originally to be a dancer but became a singer instead. She also acted in several movies and television shows. As a singer, Ella was famous at “improvisation,” which is a style of jazz music where the singer “improvises,” or invents – makes up – what he or she is singing at the moment. The notes and the words aren’t written down, but they fit within the sound of the music. This is a very common phenomenon in jazz music. Improv singers usually sing something that is not real words, things like (sings) “bee-ba-da-ba-do-ba-do-ba-da-ba-do-ba-do-ba-dee-ba-da.” I’m not a very good jazz singer! But, those aren’t real words I’m saying, and neither did Ella Fitzgerald when she sang.
Ella Fitzgerald became famous, also, in the U.S. during – oh, I guess it was the 1970s, maybe the early 1980s when I was growing up, because she had made a television commercial for an audio cassette company called Memorex. Memorex made audio cassettes that you would record on; those of you old enough to remember that will know what I’m talking about. And, in the commercial, she would sing her improv – her improvisation – and she would go up and sing a very high note: (sings) “do-ba-do-ba-do-ba-do-ba-do-ba-aaaah.” Sorry! A very high note, and it was so high that it would break a glass. Then, they would say at the end of the commercial, “Is it live, or is it Memorex?” Is it the tape you’re listening to, or the live person? The idea is that the cassette tape was so good that it would be just like listening to someone live. My guess is that many Americans, like me, found out about Ella Fitzgerald in part from that television commercial.
Ella won many awards for her jazz singing, including national awards given by the U.S. president. She was always resident here in the U.S. – she was a citizen of the United States. She is even shown on a special postage stamp, the small piece of paper you put on your envelope to mail something. She died in 1996 after having recorded many albums with other famous musicians.
You may want to go and find some recordings by Josephine Baker and Ella Fitzgerald. They are certainly two of the most famous jazz singers in the 20th century.
Our next topic is the Amish. If you were a member of the Amish group here in the U.S., you would not be able to listen to a jazz CD by Ella Fitzgerald or Josephine Baker. That’s because the “Amish,” who are a group of Christians that have very traditional values, don’t have a lot of modern technology in the places where they live. We say the Amish have very “traditional,” we mean not modern. Among the Amish people, the most traditional order – the most traditional group – called “Old Order Amish” do not use electricity, phones, or cars. They work on farms using horses and buggies for their transportation. A “buggy” (buggy) is basically a large black box with a seat for people to sit on. Buggies have wheels and they’re pulled by a horse. Buggies were used a lot before cars became common, and they are still used by the Amish today.
There was a movie, oh, must have been in the late 1980s called The Witness, with Harrison Ford. It was about a police officer who goes and hides in an Amish community. You may have seen it.
The Amish wear very traditional clothing that is sewn, or made, in the home. The women wear long dresses and a special type of hat called a “bonnet” (bonnet). The men wear pants and shirts; the pants have typically suspenders. Suspenders used to be a lot more common; they’re not used all that often anymore. Most men, now, use a belt around their pants – the top of their pants to keep their pants from falling down. “Suspenders” do the same thing; they’re long, thin pieces of fabric – material – that connect the front of the pants, going over your shoulder, to the back of the pants. There were some famous Americans in the 1970s and 80s that used to wear suspenders, but I haven’t seen them very frequently in the last 20 years or so.
Not all of the Amish are as strict as the Old Order Amish. To be “strict” (strict) means that you always follow the rules all the time. Sometimes teenagers complain that their parents are too strict because, for example, they make them come home by 10:00 every evening. To be strict means to follow the rules, and usually these are very tough or difficult rules. There are some Amish, then, that use cars and telephones; it depends on the specific group where the Amish are living and are members of.
There are about 200,000 Amish living in the U.S. Most of them live in the state of Pennsylvania, which is a state in the eastern part of the U.S., near New York. The Amish live in an area called Pennsylvania Dutch Country. They speak a language called Pennsylvania Dutch. Dutch is a language originally from the Netherlands; they speak a variation of Dutch, but they also learn English in school.
The Amish are famous for their religious “faith,” or belief in God, but they don’t go to church. Instead, they “pray” in their homes – they speak to God in their homes. Part of the reason is that historically the Amish were, at times, “persecuted,” or treated unfairly for their religious beliefs.
The Amish try to separate themselves from the rest of American society. They, in fact, usually refer to people who are not Amish as “English.” To stay away from the English – these are Americans who are not Amish – they often work at home or on the family farm. However, to have enough money, many of them have to work with or for the English. The women, for example, the women will sometimes make “quilts” (quilts) which are beautiful large blankets that are made by hand, typically. More often, the Amish work in tourism, because many people like to come and see this very different culture in Pennsylvania Dutch Country. Of course, many of the Amish would prefer to be left alone; they want to separate themselves from the rest of the country, but there are still people who go and visit.
If you ask most Americans about the Amish, they’ll think of this very traditional group of people in Pennsylvania – no electricity, no cars, no phones. That’s the general image that people have of the Amish here in the United States.
Now let’s answer a few of your questions.
Our first question comes from Nicolas (Nicolas) in France. Nicolas wants to know the difference between the expressions “to be honest” and “as a matter of fact.”
“To be honest” means in reality, in truth – if I am telling you the truth. For example, someone asks us our opinion on their new shirt that they bought and you don’t really like it, so you might say, “Well, to be honest, it’s not my favorite shirt for you.” You are giving them the truth. Usually we use this when what we are going to tell them is perhaps not something they want to hear.
“As a matter of fact” is an expression to emphasize that what you are saying is true. For example, someone is telling you that Minneapolis the capital city in the state of Minnesota and you know that that is wrong – and of course, you do know that that is wrong! So, you say, “Well, as a matter of fact, St. Paul is the capital of Minnesota.” You can also simply say “in fact” instead of “as a matter of fact”: “In fact, St. Paul is the capital of Minnesota.”
So, “to be honest” means in truth, sometimes we also say simply “the reality is,” or “to tell you the truth.” All of these mean the same thing; we use this to express an idea that we are telling someone something that they may not want to hear. “As a matter of fact” is used to emphasize that what you are saying is true.
Mitsuhiro (Mitsuhiro) in Japan wants to know difference between the expressions “why don’t you” and “let’s.”
Both “why don’t you” and “let’s” can be used to suggest something to someone else. When you use “let’s,” which is short for “let us,” you are including yourself in the suggestion. “Let’s go to the movies” means I want you and me to go to the movies together, or as a group.
If you say “why don’t you go to the movies,” you are suggesting that the other person go to the movies but not you; you will not be going with them. If you say “why don’t we go to the movies,” then you are saying the same thing as “let’s go to the movies.”
So, “let’s go,” or “why don’t we do something,” that’s including you in the action. If you say “why don’t you,” then you are just telling that person, or suggesting to that person that they do something.
Why don’t you visit our website at eslpod.com? We certainly want to thank you for your questions, and for listening today. Why don’t you come back and listen to us next time on the English Café?
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
jazz – an American style of music that was created in the early 1900s in the Southern United States that has a very strong beat or rhythm
* If you like jazz, we can go this club on Friday night to hear one of the best jazz groups in town.
pearl – a small, round jewel that is found in oysters, a type of animal that has two shells and lives in the sea
* Emil gave his daughter a necklace of pearls that belonged to her grandmother.
world-famous – someone or something that is very well known and famous all over the world
* The hotdogs at this restaurant are world-famous and people come from all over the world to taste them.
to drop out – to stop going to school before one has graduated
* Eddie was going to cooking school, but dropped out because he thought he was a better cook than the teacher!
civil rights movement – organized efforts to get equal rights for blacks and whites, such as the right to vote and go to the same schools
* Many improvements were made for minority Americans through the actions of people involved in the civil rights movement.
first lady of (something) – a woman who is best at doing something; a woman who is the best in her field
* This house has never been cleaner. You’re the first lady of cleaning!
improv – improvisation; a style of jazz music where the singer makes up what he or she is singing at that moment when they are singing; a type of comedy where comedians makes up jokes during a performance
* The other musicians stopped playing while the singer did some improv in the middle of the song.
postage stamp – a small piece of paper that we stick to an envelope to show that we have paid enough money for it to be sent through the mail
* How much does it cost to buy a postage stamp to send a letter to Norway?
buggy – a type of transportation that has a large black box with a seat for people to sit on and wheels, and is pulled by a horse
* In the old days, people used buggies to carry things from one farm to another.
suspenders – long, thin pieces of fabric that connects to the front of one’s pants, come up one’s chest, over one’s shoulder, down one’s back, and connect to the back of one’s pants to keep the pants from falling down
* Do you plan to wear a belt or suspenders to keep your pants up?
strict – following the rules all the time, without making exceptions
* His parents are so strict, they get angry if he gets home just a few minutes late from school.
to pray – to speak to a god; to make a request or to give thanks to a god or gods
* The passengers thought the ship was going to sink and many began to pray.
to be honest – in truth; in reality
* Kali came over to help me fix my broken refrigerator, but to be honest, he did more harm than good.
as a matter of fact – actually; a phrase used to emphasize that what you are saying is true
* Shaniqua knows all about starting a small business. As a matter of fact, she owned three successful small businesses before she retired.
let’s – let us; a phrase used to give a suggestion; a phrase used to suggest an action or way of thinking
* We’ve talked about this issue for two hours and we still haven’t made a decision. Let’s stop for today and start again tomorrow.
What Insiders Know
Jazz Festivals
Summertime is a good time for music and music festivals. A “festival” is an event usually over a few days where a lot of people gather to celebrate something, in this case, music. Some of the most famous and “well-attended” (visited by many people) festivals are the jazz festivals.
The Newport Jazz Festival is held every August. It began in 1954 and was held in Newport, Rhode Island. It is now held in two locations, both in Newport and in New York City. Some of most famous jazz artists in history have performed “live” (in person; not recorded) at this festival. Jazz “legends” (very famous and well respected people in a field) Miles Davis, John Coltrane, and the Duke Ellington Orchestra have all performed at this festival.
Another festival that many people “flock to” (gather in a large group at) is the New Orleans Jazz & Heritage Festival around May each year in Louisiana. The festival takes place over two weekends and includes a wide range of music that has been part of the history of New Orleans. In addition to “contemporary” (modern) and traditional jazz, the festival includes “gospel music,” which is often associated with African American churches; “Cajun music,” which is influenced by the “descendents” (children, grandchildren, great-grandchildren, and so on) of the French Canadians who came to live in New Orleans; and “zydeco,” which is a kind of African American dance music.
If you want to hear interesting jazz and other forms of music, be sure to look for the music festivals all over the United States during the summer months.