= 1444
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 139.
This is ESL Podcast’s English Café episode 139. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Blog, where several times a week we provide additional help in helping you improve your English.
On this Café, we’re going to talk about Native American reservations and something called the Trail of Tears, a very sad, unfortunate part of American history. Then we’ll change topics and focus on retirement communities. As always, we’ll answer a few of your questions as well. Let’s get started.
As I said, this Café begins with a discussion of Native American reservations and something known as the Trail of Tears. A Native American, what is also known as an Indian or an American Indian, is a person whose ancestors lived in North and South America before Europeans came to what they called the “New World.” “Ancestors” are people who come before you: your grandparents, your great-grandparents, and so forth; these are your ancestors. So, the American Indians, or Native Americans, were here long before the first Europeans came to North and South America. My ancestors came from Ireland to the United States, about 170 years ago. When Americans talk about Native Americans, then, they’re referring to Native Americans in North America, specifically the United States. In other countries there are different names given. “Indigenous populations,” for example, is a word used in some countries but not in the U.S.; we say Native Americans or Indians.
When Europeans started coming to North America, they, of course, had many “conflicts,” or disagreements with North Americans. You can understand why; the North Americans lived here first so they weren’t always so happy to give away their land to these European settlers. The Europeans wanted to have the same land, and as the U.S. began to form and grow, so did the “population,” or number of people who live in a specific area. With more people, the country needed more land, and so it started taking more land away from the Native Americans. There were many “battles,” or formal fights, between the Native Americans and the settlers. “To settle” means to go and stay and remain in a place – to live in a place. A “settler” is the noun; it’s the person who goes to live in a new area. After the first Europeans arrived on the – what is now the East Coast of the United States, people started to move west. These people were called settlers.
The battles between the Native Americans and the European settlers were very violent and many people died. Over time, though, the United States – what became the United States – won these battles against the Native Americans. Instead of killing all the Native Americans – although the government did kill many Native Americans – they decided to make an agreement with different groups of Native Americans, and give them small pieces of land where they were allowed to live and to follow their own laws. These places became known as “reservations,” because they reserved, or set aside, for Native Americans, a certain portion of land. “To reserve” something means to say “I’m going to use that.” So, reservations were pieces of land that were going to be used by Native Americans.
In general, however, these reservations were on the worst possible land that could be found. Often they were far from water or they could not be used to grow crops – that is, to grow food. Obviously, the Native Americans did not want to live on reservations, but they had no other option, or choice, because the United States government was stronger. Today many Native Americans continue to live on reservations, especially in the western part of the United States.
As the United States continued to grow, people wanted more land, so they began to take the land that they gave the Native Americans – the reservation land – back, even though they had promised to give it to them. In other words, the United States broke its promise. When you don’t do what you say are going to do, that’s called “breaking your promise.” These Native Americans were pushed further and further westward towards the Pacific Ocean to reservations in smaller, usually less desirable areas of land. These movements were called “forced relocations.” “To force someone to do something” means not to give them a choice, to make them do something. Native Americans were forced to “relocate,” or move to another place.
One of these forced relocations became known as the Trail of Tears. A trail, “trail,” is a small road or path that you normally would use to walk through some part of the country, outside of the city. Many people, for example, walk along trails in the mountains or the forests on the weekends as a way of relaxing. But this relocation is known as the Trail of Tears. “Tears,” are the little drops of liquid that fall from your eye when you are crying. In other words, the Trail of Tears was a very sad, unfortunate trip. In this case, it involved the Cherokee tribe that was forced to relocate in 1838. A “tribe” (tribe) is a group of Native Americans who live together, speak the same language, and share a common culture. The Cherokee tribe originally lived in an area that we now call Georgia – the State of Georgia. They were forced to relocate in 1838 to the State of Oklahoma, which is very different. It is in the middle of the country; Georgia is on the east coast of the United States. Oklahoma is not a very good place to live for farming and for other activities – hunting and fishing – that the Native Americans were used to.
The Trail of Tears began when President Andrew Jackson signed a law that was approved by the United States Congress. This law was passed in 1830. It forced many Native Americans to move from the eastern part of the United States into the western part of the United States, even though they were promised that they could stay, originally, in the areas in the east. Approximately 17,000 Cherokee tribe members were forced to live in camps, and many of them died. Those who didn’t die were forced to follow this Trail of Tears to their new reservation.
It is a very sad part of American history. Unfortunately, it was something that was repeated many times as Native American tribes were forced to relocate to other parts of the country. Although it is an unfortunate part of U.S. history, it’s an important one for Americans and others to understand in trying to understand the history and the experience of the United States, especially in the 19th and 20th centuries.
Now let’s change our topic and talk about retirement communities. We’ve spoken about retirement communities before, back on English Café number 47, which was a long time ago. Today we’re going to talk a little bit more about retirement communities in general. The last time I talked about this, we talked about one particular retirement community called Sun City. Today I’m going to talk a little more generally about this phenomenon.
“To retire” means to leave your job, or to leave your position and stop working. So, you retire when you are no longer going to work, usually for the rest of your life. “Retirement,” then, as a noun, is that period of time when you are no longer working. In the U.S., most people retire when they are 62 or 65 years old, because that’s the age when Americans can begin to get Social Security benefits. “Social Security benefits” are money that you receive from the federal government to help you live – to help pay your bills.
When people retire it’s common in the United States, or at least for some people, to move to a different part of the country. Many times, they simply move to another part of the city. People buy houses, they have children, and then as the children grow older and they move out, they don’t need a big house anymore. Sometimes, because of their health, they have to stay in another place that isn’t as big, perhaps doesn’t have steps. My parents, for example, owned a house that was three stories tall – there were three levels. Remember, there were 13 people in my family, so we needed a very big house. But after everyone grew up and moved away, they didn’t need a big house anymore. My mother also began to have problems in terms of walking, and it was difficult for her to walk up the steps to the second and third floors. So they decided to sell their house and they moved to an apartment building, where they could live on the first floor so there were no steps that had to be climbed.
Sometimes as someone get older, and they don’t have the ability to take care of themselves anymore, or they need medical care, they will move to what we call a “retirement home,” sometimes called a “nursing home” because there are usually nurses who work there to help take care of the people who live there. “Retirement communities” are a little different. Retirement communities are whole areas of a city or of a town that are built just for people who are retiring.
Typically, retirement communities have lots of activities for the people who live there. They may often have a “clubhouse,” which is a place for people to spend time together, sort of like a meeting room. Retirement communities often have what we would call “on-site medical facilities.” To say something is “on-site” means it is at that location; they don’t have to go somewhere else such as to a hospital. They have medical services, doctors and nurses, who live right in that area. Unlike in previous generations, people live longer now in most countries. Many times as people get older their health will “deteriorate,” or get worse. There are still some retirement communities where they can live where they have nursing assistance. However, sometimes it’s necessary for them to move into a more traditional nursing home, where they can receive better medical care.
It’s difficult as people grow older in any country. People, in general, tend to cherish their independence. “To cherish” (cherish) means to like something very much, to value something very much, to say this is very important to me. The “elderly,” those who are of an older age, cherish their independence, so if they have to move to nursing home they lose some of that independence, and that is difficult, I know from my own family’s experience.
As the American population gets older, these problems are becoming more and more prevalent. That is, they’re becoming more and more common; they’re becoming more noticeable, and you will hear a lot in the U.S. news media in the coming years about the problems of growing old because we have a large part of our population that is getting older – people like Dr. Jeff McQuillan!
Now let’s answer a few of your questions.
Our first question comes from Gustavo (Gustavo) in Uruguay. Gustavo has a question about a sentence he read: “The loss of one hour’s sleep is associated with an increased risk of accidents.” This sentence means that if you lose one hour of sleep – if you don’t get one hour of sleep – you are more likely to have an accident. The question Gustavo has is: Why do we say “one hour’s sleep”; why don’t we say “one hour of sleep?”
In English, the possessive “s” can be used to indicate ownership of something or that you possess certain qualities, so it is possible to say both “one hour of sleep” and “one hour’s sleep.” They both mean the same thing. You could say, “This book’s author is very popular; you could also say, “The author of this book is very popular.” Both are correct.
Taehoon (Taehoon) in Korea wants to know the difference between the expression “subjected to” and “subject to.” Let’s start with “subject to.”
“Subject to” is used basically as an adjective. It means that something depends on something else. For example, your salary is subject to your productivity – how hard you work, how much you produce. It depends on how hard you work – it is subject to. “Subject to” is also used in situations where someone is likely to receive some sort of punishment or have a negative consequence for their activities or actions: “Someone who robs a bank is subject to spending the rest of their life in prison.” That is something that could happen them, a negative consequence.
“Subjected to,” with an “ed” at the end, is used as a verb. It can sometimes mean to submit to the control of someone else – to allow someone else to control you. For example: “I am subjected to constant headaches due to the dogs that are always barking in my neighbors yard.” I am subjected to – I suffer from these headaches. “Subjected to” can also mean to be exposed to: “I am subjected to the screaming daughter of one of my neighbors.” She’s about four years old; she screams at the top of her voice, meaning as loud as she can, and the parents, apparently, don’t care. So everyone who lives near them is subjected to the noise of their screaming child.
Finally, Bakhtyr (Bakhtyr) in Iraq wants to know the meaning of the term “hedge trimming.”
A “hedge” (hedge) is a row of bushes or small trees, usually found in front of a house or between houses. So they are trees or bushes that you find in front of or on the side of a house that are sort of like a fence or a divider.
“To trim” means to cut something a little bit. You might say, “I need to trim my hair” – I need not to cut it all off, but to cut a little bit off. I don’t have this problem; I don’t need to trim my hair since I don’t have any! But, “to trim” means to cut a little. So, “hedge trimming” means to cut the branches and leaves of the hedges, the small trees or bushes. Hedge trimming is something that, for example, a gardener might do, someone who works to make your yard and area around your house look neat and clean.
If you have any questions that are neat and clean, you can send them to us. Our email address is eslpod@eslpod.com. We can’t answer everyone’s questions, but we’ll try to answer as many as we can.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
ancestor – a person who came before one in life; one’s relatives who lived before one was born
* Our ancestors sacrificed a lot to come to a new country and to start a new life.
settler – a person who is among the first to move to a new place and to start a community; a person who begins to live in a new area
* Many early American settlers were farmers who had to learn to grow new crops in a new land.
reservation – piece of land the American government gave to Native Americans where they would be allowed to live and follow their own laws
* Today, there are still many Native Americans who live on reservations across the United States.
forced relocation – moved to a new location without choice; made to move to a new place even though one does not want to move there
* When the government decided to build a freeway through our neighborhood, we were told that there would be a forced relocation of all of the families on our street.
trail – a path for walking; a small road for walking on in the countryside
* A group of hikers got lost in the mountains when they got off the trail and couldn’t find it again.
tribe – a group of Native Americans who live together, speak the same language, and share a single culture; a group of people who share a background and live together and help each other
* The oldest member in this tribe is the leader of her people.
retirement – the period of time in one’s life when one is elderly and no longer works; the time when older adults quit their jobs and no longer work
* After retirement, we plan to sell our house and move to a warmer city.
Social Security benefits – the money that one receives from the federal government in one’s old age
* Even with their Social Security benefits, her parents didn’t have enough money to pay the rent, and so her father continued to work.
retirement community – an area where retirees can buy homes in a neighborhood where only other retirees live; a place designed for older adults who no longer work
* Many retirement communities will not allow children to live there.
clubhouse – a place for people to spend time together in planned activities; a large room or group of rooms where people who live in the same building or community can meet for social events
* The party will be in the clubhouse and we hope that all of the residents will attend.
to deteriorate – to get worse; to become worse; to decline in quality
* The house needs a lot of repairs, and without them, its condition will continue to deteriorate.
to cherish – to like and value something very much; to value highly
* Which childhood memories do you cherish the most?
to be subject to – to be likely affected by; to be dependent on something or someone
* Whether I’ll get the job is subject to approval by the board of directors.
to be subjected to – to be caused to undergo; to be caused to experience something, usually negative or unpleasant
* Living next to the playground means I’m subjected to the loud noise of children playing every afternoon.
hedge trimming – cutting a row of bushes or small trees to make them look straight and neat
* Every month, the gardeners do hedge trimming around the house and yard.
What Insiders Know
Native American Stereotypes in Film
In the U.S., as in other countries, there are stereotypes of every social, cultural, and religious group. “Stereotypes” are beliefs that most people have about a group that are too simple and often wrong.
Native Americans in films have been stereotyped in many ways. Films tend to present Native Americans as one group of people. In fact, there are more than 600 different Native American societies, each with its own culture, and many with its own language. These films also “portray” or show Native Americans as “ruthless” killers, who show no “mercy” (compassion or forgiveness) to the people they kill.
Even though Native Americans live in and out of reservations today, most Native American characters in movies are “restricted to” (limited to) the Western. The Western is a type of American movie “set” (located) in North American in the 1800s and 1900s with “cowboys,” or people whose job is to take care of and to move “cattle” or cows. The Native Americans in these films are almost always the “villains,” or the bad guys, and the job of the cowboy is to fight and to defeat them. The Native Americans are shown as “savages,” who don’t have the same beliefs of right and wrong, and who live in the wild.
Based, in part, on these film “portrayals” (representations), the modern-day Native American continues to suffer from “inaccurate” (not true) stereotypes. In 1969, a U.S. government survey found that Caucasian (White) Americans believed Native Americans to be lazy, “drunken” (drinking too much alcohol), and dirty. This government report “concluded” (ended by saying) that this view, based on a history created by the majority culture in the United States, allowed and “justified” (shown to be reasonable) the “exploitation” or poor treatment of Native Americans in this country throughout American history.