= 1417
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast English Café number 112.
This is the English Café episode 112. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com, and download a Learning Guide for this episode. You can also take a look at our ESL Podcast Store, which has some interesting business and daily English courses to help you.
This episode is going to be one of our “Ask an American” episodes, where we listen to other native speakers talk at a normal speed, and then we stop and explain what they say. Today the topic is going to be Roswell, New Mexico. We’re going to find out why that’s famous in the U.S., and why people are interested in this topic. It has something to do with aliens visiting from other planets. As always, we’ll a few of your questions, here on Earth. Let’s get started.
Our first topic today is Roswell, New Mexico. Roswell is a small town of about, now, 50,000 people or so in New Mexico, which is a state in the southwest part of the U.S. New Mexico is just north of the country of Mexico, in between the states of Texas and Arizona.
The reason Roswell is famous in the U.S. is because of something that happened back in 1947 – something that people believed happened in 1947, and that is that near the town of Roswell there were people from other planets – from what we would call “outer space,” places other than Earth – who had a ship that crashed in New Mexico. The story is that the U.S. Army went and took the aliens’ bodies and their spaceship – the vehicle that they rode in, in outer space – and brought it to the Army base near Roswell. An “Army base” is a place where the Army has equipment and people living and working; that area is called a “base.” We have many different kinds of military bases: Army bases, Air Force bases, and so forth.
Some people believe that the government tried to cover up this alien crash. To “cover up” is a phrasal verb that means to hide, to keep secret. “Alien” is another word we use for someone who is not from this place. Usually, we use the word “alien” to describe people from other planets, if they exist. We also use the word “alien” in talking about people who are not U.S. citizens. Some people talk about “illegal aliens,” that is people who are here illegally, or “legal aliens,” people here who have permission to be here. But in this context, “alien” means people or creatures, that is to say, some sort of animal or some sort of living being from another planet.
Many people think – or some people think that the U.S. government was trying to hide the secrets of this strange crash back in 1947 near Roswell. We’re going to listen now to one man who believes the U.S. government is hiding something. He’s going to talk out why he thinks the U.S. government is keeping secrets. We’ll listen to him talking at normal speed, then go back and explain what he is saying.
[recording]
The United States government has had a lot of practice in keeping secrets. Good examples are the atomic bomb, which was developed up here in Los Alamos just north of Roswell. 50,000 people were involved with that project for about 10 years, and it was kept secret.
[recording ends]
This man, who lives in Roswell, begins by saying, “The United States government has had a lot of practice keeping secrets. Good examples are the atomic bomb project.” The atomic bomb project was a project to develop a nuclear bomb, back in the late 1930s and 1940s. He says this atomic bomb project was carried out right here in Los Alamos, north of Mexico. Los Alamos is near Roswell. It’s where the U.S. atomic bomb project was headquartered, where most of the people worked on the project lived. It was “carried out,” meaning it was developed – it took place in this area.
“50,000 people,” the gentleman says, “were involved in that project for about 10 years, and it was kept secret.” His logic here, of course, is that because the U.S. government has kept secrets, maybe it’s keeping secrets now. Let’s listen again to his quote:
[recording]
The United States government has had a lot of practice in keeping secrets. Good examples are the atomic bomb, which was developed up here in Los Alamos just north of Roswell. 50,000 people were involved with that project for about 10 years, and it was kept secret.
[recording ends]
The general term for seeing spaceships supposedly from other planets up in the sky is “UFO,” unidentified flying object. We sometimes talk about “flying saucers” (saucers). A “saucer” is like a round, small plate that you put a cup on. Some people believe that these aliens are in flying saucers and they visit Earth from other planets.
The United States government actually investigated this incident – this event – in the mid-1990s, and said that what people think were UFOs – were space aliens – was, in fact, a secret U.S. government project that was testing different kinds of planes and flying vehicles, and that it had nothing to do with UFOs. Of course, the government would say that if it were lying! That’s the logic of those who believe in this Roswell incident.
Roswell has become famous. People have T-shirts; there are television programs about Roswell. It is something I don’t think most Americans believe, but certainly it has become a popular, we might say, “folk legend.” When we say something is a “folk (folk) legend,” we mean that most people know it isn’t true, but the story gets told over and over again and it becomes part of the popular culture.
Many people go and visit Roswell, New Mexico, which now has a museum about UFOs. I’m not sure exactly what is in the museum, but this is a very popular, for some people, tourist destination. A “tourist destination” is where people go. It has also been very good for the economy in Roswell; people come, they stay in hotels, they spend money. Let’s listen to one local person talk about the effects of the UFO incident on the Roswell economy:
[recording]
It seems like 11 or 12% of the employment base in Roswell is now tourism and hospitality-oriented, such as hotels, restaurants, museums, and things like that. A decade ago, that number was a zero-point-something percent.
[recording ends]
This man says, “It seems 11 or 12% of the employment base in Roswell is now tourism.” Notice the use of the word “base.” We talked about an Army base as a place where the military has men and equipment; here, the gentleman says “employment base.” Here, he’s using the word “base” to mean “foundation,” what something else is built on or depends on. So, the “economic base” would be the important part of the economy, where the jobs are.
The employment base in Roswell now depends, in part, on tourism and hospitality-oriented businesses. “Hospitality” means being nice to people who are visiting, who are your guests. When we talk about “hospitality-oriented businesses,” we mean businesses that serve tourists: hotels, restaurants, museums. Places where tourists go – people who are visiting – are part of the hospitality business, or hospitality-oriented businesses. “Oriented” just means directed toward or concerning.
He says at the end that a decade ago –10 years ago – that figure, meaning the percentage of people working in the tourist and tourism industry, was zero-point-something percent, meaning it was a very small percentage. Zero-decimal point-something – some number is what that means. So, it has grown, or increased dramatically in the last 10 years. Let’s listen again:
[recording]
It seems like 11 or 12% of the employment base in Roswell is now tourism and hospitality oriented, such as hotels, restaurants, museums, and things like that. A decade ago, that number was a zero-point-something percent.
[recording ends]
If you go to Roswell, New Mexico, what sort of things would you buy as a “souvenir,” or as something to remember your visit? Not surprisingly, the most popular things that people buy are the same kinds of things you can find in almost any tourist area in the world. Here’s one woman telling us what are the most popular things that people buy:
[recording]
Top items that we – people buy would be T-shirts is first, coffee mugs are second, shot glasses and keychains.
[recording ends]
She says that the top items, meaning the most popular items – we talk about someone who’s “on the top,” we mean that they’re number one – so top items that people would buy – do buy – are “T-shirts,” a kind of simple shirt usually with something printed on it, “coffee mugs are second.” A cup that you drink your coffee from is a “coffee mug,” again, very popular in tourist places – a mug or a cup that has the name of the place on it. Then she says “shot glasses and keychains.” A “shot (shot) glass” is a glass used to serve small amounts of alcohol. A “keychain” is, you probably know, a small ring, usually, where you can have all your keys together. Let’s listen again:
[recording]
Top items that we – people buy would be T-shirts is first, coffee mugs are second, shot glasses and keychains.
[recording ends]
Notice that the woman hesitates at the beginning. She starts to say, “Top items that we sell,” then she changes her mind and says that “people buy.”
Finally, we listen to another one of the gentleman that we heard earlier talk about whether there will ever be a resolution to the Roswell mystery, meaning will we ever really know what happened in 1947 in the desert. Here’s his opinion:
[recording]
I think the mystery will always endure; the mystery will always be there. Nobody is going to ever have conclusive proof of what it was or wasn’t.
[recording ends]
He starts by saying, “I think the mystery will always endure” (endure). Something that “endures” lasts a long time, something that continues for a very long time. He says, “the mystery will always be there,” there will always be a mystery about what happened. “Nobody is ever going to have conclusive proof of what it was or wasn’t.” When we say something is “conclusive,” we mean you can make a determination, you can make a conclusion about something – you can say, “Okay yes, it’s true,” or “it isn’t true.” He’s saying that we will not have conclusive proof, or evidence, of what really happened. Let’s listen one more time:
[recording]
I think the mystery will always endure; the mystery will always be there. Nobody is going to ever have conclusive proof of what it was or wasn’t.
[recording ends]
You can hear and read about Roswell in many different TV shows and movies; there are several books about Roswell that you can also find. If you are an alien listening to this episode and are learning English, you can email me and I can tell everyone whether it was true or not!
Now let’s answer a few of your questions.
Our first question comes from Toni (Toni), on the island of Majorca. Toni wants to know the difference between a “holiday” and a “vacation.”
In the United States, we use the word “holiday” usually to talk about a national celebration, such as the Christmas holiday or the Fourth of July holiday – Independence Day holiday. The word “vacation” is usually used to mean time where you don’t work for a week or perhaps two weeks. “I like to play baseball during my summer vacation,” if I am a student at school, I don’t have school; I get a vacation in the summertime.
The word “holiday” in Great Britain – in British English – means the same as “vacation” here in the U.S. People will say, “I am going on holiday,” that is the same as, in the U.S., “I’m going on a vacation.” Although that’s the normal way we use these words, they can sometimes be used to mean the same thing. People take vacations, for example, when there is a big holiday. Since you don’t have to work on the holiday, it’s an extra day that you don’t need to use from your vacation days.
Janine (Janine) in Switzerland wants to know when we use the words “arbitrator,” “referee,” and “umpire.”
An “arbitrator” is someone who helps two people or two groups come to an agreement usually in a legal situation. So, an “arbitrator” is someone who works in a formal setting – a formal situation – usually around some sort of contract or agreement, sometimes perhaps even a legal, what we would call a “court case,” that is a legal – official, legal proceedings. You use this word, “arbitrator,” when, for example, someone may be getting a divorce and you need help on deciding who is going to get what in the house, and the two people can’t agree – that’s why they’re getting a divorce! So, you bring in an “arbitrator,” someone who helps makes those decisions.
The word “referee” and the word “umpire” are usually used more in sports; it depends on which sport you’re talking about. The word “umpire” (umpire) is used in baseball. You talk about the “umpires,” or sometimes we’ll say simply the “ump” (ump) for short. The word “referee” is used more in soccer, basketball, American football – those are sports where we use the word “referee.” They do the same thing; they’re the people responsible for making sure that everyone follows the rules of the game.
Finally, Tadatoshi (Tadatoshi) in Japan wants to know the meaning of the expression, “Ay, caramba!” and when would you use it.
“Ay, caramba!” is actually a Spanish expression, not an English one. But it has become, like other expressions from other languages, popular in English. It became very popular with the television show The Simpsons, because one of the characters on the cartoon show The Simpsons, Bart Simpson, would sometimes say, “Ay, caramba!” It basically means, in English, “Oh, my goodness!” or “Oh, jeez!” It could be positive; it could be negative. You might say, for example, “Ay, caramba! It’s very hot today.” Or, you might say, “I knew that you were going to buy a new car, but ay, caramba! That’s a beautiful car.” Or, if your wife is wearing a new dress, you should say to her, “Ay, caramba! You look great!” That’s what I say to my wife!
Whatever you say to your wife, or husband, or boyfriend, or girlfriend, or father, or mother, or whoever it is that you are with, you can email us with your questions to answer on the Café. We don’t have a chance to answer everyone’s questions, but if there’s something you’d like us to talk about on the Café, you can email us. Our email is eslpod@eslpod.com.
The audio portions of our “Ask an American” segment this show were from The Voice of America.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. We’ll see you next time on the English Café.
ESL Podcast English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
alien – a living, non-human being from another planet
* Do you believe that aliens live on Mars?
army base – a place owned by the government where the army has many people living and working
* How many army bases does the U.S. government have in that country?
to cover up – to keep a secret; to not let other people learn about something; to hide information about something
* When the toy company found out that its toys had dangerous chemicals, it tried to cover it up and not tell anyone.
to carry out – to execute; to implement; to make something happen
* The scientist is carrying out a study about the causes of AIDS.
UFO – unidentified flying object; something in the sky that one cannot identify, and therefore thinks might be a type of transportation from another planet
* He said that a UFO landed behind his house and took him to another planet.
flying saucer – spaceship; a type of transportation from another planet, usually round and somewhat flat
* In the movies, flying saucers often have many colored lights and are flown by green aliens from other planets.
hospitality – friendly, kind behavior shown to guests, often offering them food and drink
* Daniel said that people from his country are known for their hospitality because they often give their guests very good food and drink when they visit.
top (something) – the most popular of a certain type of thing; the biggest or best of something
* This doll is our top toy for children aged 7-10.
to endure – to last a long time; to bear; to deal with something for a long time, especially if it is difficult or painful
* Jemina’s commitment to helping sick children has endured despite her own illness.
conclusive – decisive; proving or showing that something is true; without leaving any doubt
* Their research provided conclusive evidence that bad air quality can cause asthma in children.
holiday – a special day that is celebrated by a country or culture, often with most stores and other businesses closed so that most people don’t work; a specific type of vacation
* Some popular U.S. holidays are Memorial Day, Labor Day, Independence Day, Halloween, Thanksgiving, Christmas, and New Year’s Day.
vacation – a period of time when one does not have to go to work or school, and often uses the time to travel to another place
* The college students went to Chicago during their summer vacation.
arbitrator – a person who can help people reach agreement; a person who tries to end a disagreement between two people or organizations
* When Sandy and her landlord couldn’t agree on how much money she owed him, they asked an arbitrator to help.
referee – umpire; a person who watches a game closely, decides whether people are breaking the rules, and decides when teams have scored points in most sports
* The referee wasn’t paying attention, so he didn’t see which team had touched the ball before it went off the field.
umpire – referee; a person who watches a game closely, decides whether people are breaking the rules, and decides when teams have scored points, usually in baseball
* The player became very angry when the umpire said that he was out.
Ay, caramba! – a Spanish phrase used by speakers of American English to show frustration and/or surprise
* Ay, caramba! I left my keys at the office.
What Insiders Know
Aliens in TV Programs
Many American TV programs are about aliens, and especially those that live with normal American families.
The Coneheads was a popular “sketch” (a short comedy act) in the 1980s on the comedy show Saturday Night Live. It was about a family of aliens who were “stranded” (unable to leave a place) on Earth. They had cone-shaped heads, where a “cone” is a three-dimensional shape that is round on the bottom and comes to a point on the top. They were very “strange” (unusual), ate a lot of food, and used very formal phrases when speaking. Whenever humans “noticed” (saw something) the Coneheads’ strange “behavior” (way of acting), the aliens said “We are from France,” as if that could explain their differences.
Another popular TV comedy program about aliens was named Third Rock from the Sun, since Earth is the third planet from the sun. This show “ran” (was shown) in the late 1990s. The aliens were a group of scientists from another planet who thought that Earth was the least interesting planet. On Earth, they “pretended” (acted in a way that isn’t true) to be a human family. The show is funny because it showed how difficult it was for the family to understand “customs” (culturally acceptable behavior) on Earth.
Finally, another popular TV comedy was Alf, which ran in the late 1980s. It was about an alien named A.L.F. (for Alien Life Form) that lived with a regular human family. Unlike the aliens in the other two shows, Alf didn’t look like a human – he was short and covered with orange hair – so he had to “hide” (not be seen) from other humans. The family agreed to hide him until he could fix his spaceship, but he soon became part of the family.