= 0554
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 554: An Emergency Airplane Landing.
This is English as a Second Language Podcast episode 554. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Please go to our website and support this podcast by becoming a member or making a small donation. You can do so at eslpod.com.
This episode is called “An Emergency Airplane Landing.” A “landing” is when the plane comes down to the ground; an “emergency landing” would be when there’s some problem with the airplane. Let’s get started.
[start of story]
I was nearly asleep in my seat when I heard this announcement:
“Folks, this is the captain speaking from the cockpit. We are experiencing a lot of turbulence and I’m turning on the fasten seatbelt sign. Please remain in your seats.”
I didn’t think anything of it until a few minutes later when I heard this announcement:
“This is your captain speaking again. Due to extreme weather conditions, we may need to make an emergency landing. The cabin crew will review the emergency procedures, and give you instructions on how to use the floatation devices and the oxygen masks. Please stay calm.”
This is when I started to freak out. What if we crash-land? What if we dive into the ocean? Who would rescue us here in the middle of nowhere?
Then, I heard this announcement:
“Ladies and gentlemen, this is the captain again. It seems that we had an instrument malfunction, and no emergency landing will be necessary. Sorry to alarm you, and please go back to sleep.”
Go back to sleep?! Is he kidding? How can anyone sleep after that?! I’m still watching my life flash before my eyes!
[end of story]
Our story begins when I say “I was nearly (meaning I was almost) asleep in my seat when I heard this announcement.” Of course, we’re on an airplane in the middle of an airplane flight. “Folks, this is the captain speaking from the cockpit.” “Folks” is an informal way of saying “ladies and gentlemen”; even more informal would be “guys” or “hey guys,” but a captain wouldn’t say that. “Folks” is a little old-fashioned. The word “folks” is also used to describe your parents. Somebody says, “My folks are traveling,” they mean my parents are traveling, but here it just means ladies and gentlemen.
“This is the captain speaking from the cockpit,” he says. The “cockpit” (cockpit) is the part of the plane where the pilot and the assistant pilot (we call him or her the “co-pilot”) sit, separated from the rest of the plane. It’s in the very front of the plane, the cockpit. The captain says that we are experiencing (meaning we are having) a lot of turbulence. “Turbulence” is when you have unpredictable movement in the airplane, usually because of wind or storms. The airplane starts to move up and down or side to side. It’s usually an uncomfortable situation.
The captain turns on the fasten seatbelt sign. A “seatbelt” is a belt that keeps you in your seat. Most cars have seatbelts; you put the seatbelt on before you start driving. In fact, that’s the law in most places in the United States. On an airplane, you also have a seatbelt that will, we hope, prevent you from getting hurt if there is some sort of emergency situation or a lot of turbulence, so you don’t fall out of your seat. “To fasten a seatbelt” means to put it on. “To fasten (something)” means to connect one thing with another. A seatbelt has a metal end on it, and that fastens, or connects into the other part of the seatbelt that is on the other side of the seat. The “fasten seatbelt sign” is a sign in the airplane that you can see usually above every seat that tells you whether you can get up and walk around, or whether you should remain in your seat with your seatbelts fastened.
The captain tells people to remain in their seats. I say that I didn’t think anything of it (meaning I wasn’t thinking about it, it didn’t seem important) until a few minutes later when I heard another announcement. The captain comes on again: “This is your captain speaking again. Due to extreme weather conditions, we may need to make an emergency landing.” “Extreme weather conditions” would be a lot of rain, snow, or wind that might affect the way the plane flies. An “emergency landing” is when the plane has to come down to the ground, or perhaps the water, because there’s some problem with the airplane and it can’t continue flying. “Landing” is when the plane comes back down to the ground. The opposite is called the “takeoff,” that’s when the plane goes up in the air.
Well, an emergency landing, of course, is a very serious thing. The captain says that the cabin crew will review emergency procedures. A “crew” is a group of people, in this case who are working together. These are people who work for the airline; they are called, typically, “flight attendants,” and they work on the plane. They give you your food, they provide information and directions, and so forth. The “cabin” is the part of the plane where the people are. Usually in American airplanes, there is a big cabin, which is called the “coach” cabin, that’s where the cheap seats are. And then there’s the business or first-class cabin in the front of the plane, where they have nice seats and good food. The “cabin” refers, in general, to everything, all of the passengers in the airplane. So the “cabin crew” really means the flight attendants; in this case, everyone but the pilots, who are in the front flying the plane. “Procedures” are steps; things that you have to do to. “Emergency procedures” would be the things you have to do; in this case, if they had to make an emergency landing.
The captains says the cabin crew will give instructions on how to use the floatation devices and the oxygen masks. “To float” (float) means to go into the water but not to go down below the water, you stay on top of the water. A “floatation device” is something that you either wear or hold onto that prevents your body from going underneath the water. So if you can’t swim, for example, but you have a floatation device, you can hang onto the floatation device so that you don’t go down into the water and die. The “oxygen mask” is a small device you put over your mouth and your nose so that you can breathe oxygen in. Of course, you need oxygen to survive, and when the plane is up at a very high altitude, when it is high above the earth, you need that oxygen given to you. In an emergency situation you have oxygen masks, usually they are above where you are sitting.
The captain tells everyone to please stay calm, which, of course, means don’t get excited, don’t panic, but that’s very difficult for people to do in this situation. I say that this is when I started to freak out. “To freak (freak) out” is a two-word phrasal verb meaning to become very worried or anxious or scared. It’s somewhat of an informal term. Then I say, “What if we crash-land?” “To crash-land” means that the airplane has to go down either on the ground or somewhere else, but not at the airport. Of course, you don’t want the plane to land somewhere else because many times the plane will blow up – it will explode, and once again, you would die. You see this is a happy, happy story; I hope you’re not listening to this while you’re on the airplane!
I say also, because I’m so worried, “What if we dive into the ocean?” “To dive” (dive) means to jump or to fall into the water from above, usually so that you are then completely underneath the water, at least for a period of time. “Dive” has a couple of other in English, very different meanings; take a look at the Learning Guide for some additional explanations.
So I am afraid that the plane is going to go down into the ocean. I then say, “Who would rescue us here in the middle of nowhere?” “The middle of nowhere,” or “in the middle of nowhere,” means it’s a very remote place, which means it isn’t near anything else. There aren’t any cities, there aren’t any towns, there aren’t a lot of people around; that would be in the middle of nowhere. “To rescue” means to find and save someone who’s in a difficult situation. So, there’ll be no one to rescue us if they crash-land or go into to the ocean because there is no one near them, they’re in the middle of nowhere.
Then, I hear the final announcement: “Ladies and gentlemen, this is the captain again. It seems that we had an instrument malfunction.” An “instrument” is a tool, in this case a tool that provides you information: how high the plane is flying, how fast the plane is going. These are pieces of information that the instruments in the cockpit will indicate. A “malfunction” is when something breaks, when it doesn’t work, when it stops working properly. So the captain is saying that there isn’t an emergency, it was just a problem with their instruments. The information was wrong; the machine was not working properly, it malfunctioned.
He says, “Sorry to alarm you, and please go back to sleep.” “To alarm (someone)” means to scare them or make them very worried, usually by telling them some very bad news. I, of course, am surprised at what the captain is saying. He tells us to go back to sleep. I then say, “Is he kidding (is he joking)? How can anyone sleep after that?!” You thought you were going to die one minute, the next minute everything is fine, but you’re still not able to just go back to sleep. I say, “I’m still watching my life flash before my eyes!” “To watch your life flash before your eyes” is an expression that means that you remember everything that happened in your life, but it goes by very quickly. Usually, this is an expression that indicates that you are about to die. For example, you’re in a car, and the car begins to go over the other side of the road, and another car is about to hit you. One second, two seconds before you die, your life may flash before your eyes; you may suddenly think of all these things that happened in your life. In general, the expression is to indicate that you were in a very dangerous situation.
Now let’s listen to the story, this time at a normal speed.
[start of story]
I was nearly asleep in my seat when I heard this announcement:
“Folks, this is your captain speaking from the cockpit. We’re experiencing a lot of turbulence and I’m turning on the fasten seatbelt sign. Please remain in your seats.”
I didn’t think anything of it until a few minutes later when I heard this announcement:
“This is your captain speaking again. Due to extreme weather conditions, we may need to make an emergency landing. The cabin crew will review the emergency procedures, and give you instructions on how to use the floatation devices and the oxygen masks. Please stay calm.”
This is when I started to freak out. What if we crash-land? What if we dive into the ocean? Who would rescue us here in the middle of nowhere?
Then, I heard this announcement:
“Ladies and gentlemen, this is your captain again. It seems we had an instrument malfunction, and no emergency landing will be necessary. Sorry to alarm you, and please go back to sleep.”
Go back to sleep?! Is he kidding? How can anyone sleep after that?! I’m still watching my life flash before my eyes!
[end of story]
The script for this episode was written by someone who never freaks out in an emergency, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
cockpit – the part of the plane where the pilot and co-pilot sit, separated from the rest of the airplane
* The cockpit is filled with instruments used to operate the plane.
turbulence – a period when there is a lot of unpredictable movement while a plane is flying, usually caused by wind or storms
* During turbulence, her glass of orange juice spilled all over her jacket.
fasten seatbelt sign – a small, lighted sign above each seat on an airplane that, when turned on, lets passengers know they should wear their seatbelt, which holds them in their seats when the plane moves
* The pilot has turned off the fasten seatbelt sign, so you are free to walk around the plane, but we recommend that you leave your seatbelt on whenever you are seated.
extreme weather conditions – weather with a lot of rain, snow, or wind, or with a very high or low temperature
* People who live in Colorado are used to extreme weather conditions, since sometimes it snows one day and then is 70 degrees and sunny the next day.
emergency landing – when a plane is forced to land earlier than planned, and in a different place, usually because it is having mechanical problems
* When the plane’s engine failed, the pilot had to make an emergency landing at the nearest airport.
cabin crew – airplane personnel; the people who work on an airplane during a particular flight, including the pilots and flight attendants
* Welcome to Global Airways! If there’s anything we can do to make your flight more enjoyable, please ask a member of our cabin crew for assistance.
emergency procedure – something that people have learned to do if and when there is an emergency (a serious, unexpected, and dangerous problem)
* Does the library have a written emergency procedure describing what people should if there is a fire?
floatation device – something that is worn, held, or attached to one’s body so that one’s head does not fall below the surface of water, used to save lives
* If you don’t have a life jacket, you can use your seat cushion as a floatation device.
oxygen mask – a small device that is placed over one’s nose and mouth so that one can receive oxygen when something is wrong with the normal air
* Ever since his surgery, Gerard has had difficulty breathing, so he has to wear an oxygen mask whenever he leaves the house.
to freak out – to become very worried, anxious, and scared
* June is going to freak out if her pregnancy test is positive.
to crash-land – to have to land a plane, even though there is no airport nearby, usually landing it in a field or on a road
* The pilot had to crash-land in a field, but fortunately no one was hurt.
to dive – to jump or fall into the water from above, so that one is completely below the surface of the water
* The lifeguard dove into the water to rescue the little boy who had fallen into the pool.
to rescue – to find and save someone who is in a difficult or dangerous situation
* The boat is sinking! Use our radio to call the Coast Guard to rescue us.
in the middle of nowhere – in a remote place; very far from cities and towns; in a place that is difficult to reach
* After living in the city for 10 years, Oscar wanted to buy some land in the middle of nowhere and live in peace and quiet.
instrument – a tool that measures something and provides information
* Which instrument did the doctor use to measure your blood pressure?
malfunction – when a device or a piece of electronic equipment does not work properly
* When the bank had a computer malfunction, customers’ private information was visible on its website for about 20 minutes.
to alarm – to scare someone or make someone become worried, usually by sharing bad news or unexpected information
* The doctor said, “I don’t want to alarm you, but your mother has a very serious heart condition.”
to watch (one’s) life flash before (one’s) eyes – to quickly remember all the things that one has done in one’s life, usually immediately before one expects to die
* Right before the car accident, I saw my life flash before my eyes.
Comprehension Questions
1. What would you want to use on an airplane during turbulence?
a) A seatbelt.
b) A floatation device.
c) An oxygen mask.
2. What does he mean by saying, “Who would rescue us here in the middle of nowhere?”
a) He doesn’t think anyone will come to look for them.
b) He doesn’t think there’s anywhere for the plane to land.
c) He doesn’t think anyone will be able to find them.
Answers at bottom.
What Else Does It Mean?
to dive
The verb “to dive,” in this podcast, means to jump or fall into the water from above, so that one is completely below the surface of the water: “The bird dove into the water to catch a fish.” Or, “All the judges agreed that the diver dove beautifully.” The verb “to dive” can also mean to spend time moving underwater while using special equipment so that one can breathe: “They went diving in the Caribbean and were amazed by all the beautiful, colorful fish they saw there.” The phrase “to dive (right) in” means to begin doing a task right away, without hesitating (waiting) and with a lot of enthusiasm: “Let’s dive right in and get started.” The verb “to dive” can also mean to move quickly: “The children’s hands dived into the bowl of candy.”
to alarm
In this podcast, the verb “to alarm” means to scare someone or make someone become worried, usually by sharing bad news or unexpected information: “We were alarmed to hear that there had been a large earthquake near our friends’ home.” An “alarm” is any type of electronic equipment that makes a loud noise to let people know there is a problem: “Whenever we burn toast in the kitchen, the smoke alarm goes off.” Or, “All the apartment building residents had to go outside when the fire alarm went off.” Finally, an “alarm clock” is a small electronic clock that makes a loud noise at a specific time of day to wake someone up: “Oh no! I turned off my alarm clock in my sleep, and now I’m going to be late for work!”
Culture Note
On January 15, 2009, Chesley “Sully” Sullenberger was the “pilot” (the person whose job is to fly a plane) of U.S. Airways Flight 1549 from New York City to Charlotte, North Carolina. Soon after “taking off” (leaving the ground and beginning to fly), the plane hit a large “flock of birds” (a large group of birds flying together). The “impact” (hit; collision), made the engines stop working.
Chesley knew that he wouldn’t be able to get the plane to land at the nearest airport in New York, so he decided to make an emergency landing. He landed the plane in the Hudson River, even thought there wasn’t any “thrust” (power to move forward) in the engines. How did he do that? Well, he had many years of experience “gliding” (flying without power, only with the wind), having earned his glider pilot’s license when he was only 14 years old. He knew how to control a plane without engines, although obviously the plane he was flying that day was not supposed to be a glider.
Chesley’s actions that day saved the lives of all 155 passengers. As the plane “floated” (stayed above the surface of the water) on the river, he made sure that everyone else had been “evacuated” (left the plane) before he became the last person to get off.
The story received a lot of “media coverage” (with many stories on TV and in the newspapers) and Chesley was congratulated by then-President George W. Bush and “President-elect” (the person who had been chosen to be the next president) Barack Obama. He has also received many “honors” (awards and recognition) for his “heroism” (bravery to help others). Many people have called him the “Hero of the Hudson.”
Comprehension Answers
1 - a
2 - c