= 0567
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 567: Visiting a Patient in the Hospital.
This is English as a Second Language Podcast episode 567. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
If you like this podcast and would like to support us you can become a member of ESL Podcast by going to our website, eslpod.com (com). You can also make a donation to or podcast to keep this audio portion free for everyone.
This episode is about someone visiting a hospital. It uses vocabulary that you would need in a hospital. I hope you don’t need it, but if you do, here it is. Let’s get started.
[start of dialogue]
George: You’re just in time. There’s only another 20 minutes until the end of visiting hours.
Inez: I got here as soon as I could. How is Uncle Peter?
George: They moved him from the emergency ward to the intensive care unit. He’s on life support.
Inez: How could this have happened? How could somebody in the prime of his life collapse suddenly like that?
George: They’ve been running tests all day, and the doctor is supposed to come by after her rounds to talk to us. Hopefully, we’ll get some answers then, and she’ll give us an update on Uncle Peter’s condition. Come on, I’ll take you to the ICU.
Inez: Okay, but I really dread seeing him on a respirator and hooked up to monitors.
George: This is it, room 323.
Inez: Oh, look at him. What are all of these IV drips for? He looks so lifeless in that hospital bed. Is he under sedation?
George: Yeah, I think so. We’ll know more when the doctor gets here. Oh, here she is.
Inez: Let’s hope she has some answers for us.
[end of dialogue]
George begins by saying to Inez, “You’re just in time.” “In time” means before something is ending, before something is no longer possible. To tell someone that they are “just in time” means that a few minutes later, or maybe an hour later they would not be able to do what they can do now. George says, “There’s only another 20 minutes until the end of visiting hours.” “Visiting hours” are times when family and friends can see and visit patients in a hospital. A “patient” is someone who is sick. So, it’s the time you can go to the hospital and talk to somebody who’s there. Every hospital has different visiting hours.
Inez says, “I got here as soon as I could (as fast as I could). How is Uncle Peter?” George says, “They moved him from the emergency ward to the intensive care unit.” In a hospital, the different parts or sections of the hospital are called “wards” (wards). For babies that are going to be born, you go to the “maternity ward.” That’s where they deliver babies. There was a famous novel by late Russian writer Aleksandr Solzhenitsyn called The Cancer Ward. That would be the place in the hospital where they take care of people who have cancer. This is the “emergency ward,” it’s for people who have very serious problems and need immediate attention. The “intensive care unit” is a special part of the hospital for people who are so sick they might die soon, so that they are given extra attention (extra care; help) to make sure they don’t. George says that Uncle Peter is on life support. “Life support” in a hospital are machines that keep a person alive. Often, they allow the person to breathe; they prevent the person from dying, if they did not have the life support they would die. To be on life support is to be in a very serious situation.
Inez says, “How could this have happened? How could somebody in the prime of his life collapse suddenly like that?” Inez doesn’t understand why Uncle Peter is sick. She says he’s in the prime of his life. The expression “the prime (prime) of (one’s) life” are the best years, the years where you are almost always going to be healthy. Maybe it’s between 20 and 70, depends on the person. I’m 46, so I’m in the prime of my life. Uncle Peter suddenly collapsed. “To collapse” means to fall down suddenly because you feel sick; you feel weak; perhaps you become unconscious, like you were sleeping. That’s to collapse.
George says that the doctors have been “running tests” (doing tests) all day, trying to find out what is wrong. “The doctor,” he says, “is supposed to come by (is supposed to visit) after her rounds to talk to us.” “Rounds” (rounds) are when a doctor goes and sees all of his or her patients, usually in a certain order: first they go to this ward, then they go to that ward; first they see this person, then they see that person. It’s sort of like the plan that doctors follow to visit all of the patients that they have. George says, “Hopefully, we’ll get some answers then (when the doctor comes), and she’ll give us an update (the most recent information) on Uncle Peter’s condition (how Peter is doing).” I should mention that the word “round” that we just talked about has several different meanings in English. If you’re member of ESL Podcast, you can find out what those are by going to the Learning Guide for this episode. You can also find other meanings of the word “condition” in that same Learning Guide.
George says, “Come on, I’ll take you to the ICU.” The “ICU” is the intensive care unit, often called, simply, “ICU.” Inez says, “Okay, but I really dread seeing him on a respirator and hooked up to monitors.” “To dread” (dread) means not to want to do something because you are very worried or you’re anxious about what will happen. Uncle Peter is on a respirator. A “respirator” is a machine that helps you breathe by pushing oxygen into your lungs. It allows you to breathe even if you can’t breathe on your own. It’s very common when someone is ill that they are so weak that they cannot breathe properly, and so respirators are used to keep them alive. Inez says Uncle Peter is hooked up to monitors. “To be hooked up to (something)” means to be connected to something. A “monitor” is a machine, especially in a hospital, that tells you how the person – the patient is doing: their heart rate, their blood pressure, and so forth.
George says, “This is it,” they’ve been walking to the ICU. “This is it,” he says, “room 323.” Inez says, “Oh, look at him (meaning Uncle Peter). What are all of these IV drips for?” “IV” stands for intravenous. “IV drip” is a clear, usually, plastic bag that is full of liquid, often with medicine in it, and it hangs next to the patient. It is hooked up to the patient; there’s actually something that goes in, usually, to the patient’s arm. This allows, for example, for the doctors to make sure the person keeps “hydrated,” make sure they have enough water. It is also a way of giving medicine to a person who is sick. You’ll often see IVs next to patients in hospitals.
Inez then says, “He looks so lifeless in that hospital bed.” “To be lifeless” is to be without life, basically like you’re dead. Inez says, “Is he under sedation?” “Sedation” is medicine that makes you very sleepy; it calms you down. Often, if someone is under sedation, you can’t talk to them because they’re sleeping or they don’t respond normally to you. George says, “Yeah, I think so. We’ll know more when the doctor gets here. Oh, here she is.” Inez then says, “Let’s hope she has some answers for us.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
George: You’re just in time. There’s only another 20 minutes until the end of visiting hours.
Inez: I got here as soon as I could. How is Uncle Peter?
George: They moved him from the emergency ward to the intensive care unit. He’s on life support.
Inez: How could this have happened? How could somebody in the prime of his life collapse suddenly like that?
George: They’ve been running tests all day, and the doctor is supposed to come by after her rounds to talk to us. Hopefully, we’ll get some answers then, and she’ll give us an update on Uncle Peter’s condition. Come on, I’ll take you to the ICU.
Inez: Okay, but I really dread seeing him on a respirator and hooked up to monitors.
George: This is it, room 323.
Inez: Oh, look at him. What are all of these IV drips for? He looks so lifeless in that hospital bed. Is he under sedation?
George: Yeah, I think so. We’ll know more when the doctor gets here. Oh, here she is.
Inez: Let’s hope she has some answers for us.
[end of dialogue]
The script for this episode was written by someone in the prime of her writing life, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
in time – before something ends or before something is no longer a possibility; with time to spare
* Fredy accidentally slept in, but he hurried and got to work just in time, arriving a few seconds before 8:00.
visiting hours – the periods of time when people are allowed to see and speak with patients at a hospital, because during the other periods of time the patients must be left alone with the doctors and nurses
* I’m sorry, but visiting hours have ended for the day. You can come back tomorrow at 1:00.
emergency ward – the part of a hospital that deals with patients who have very serious problems that need immediate attention
* Doctors don’t like it when people go to the emergency room when they have just a mild cold.
intensive care unit (ICU) – the part of a hospital that deals with patients who have very serious problems and could die, and are in a condition that requires constant monitoring and care
* Aunt Marge is in the ICU and the doctors don’t know whether she’ll live or die.
life support – machines that keep a person alive by making oxygen flow through one’s lungs and by making one’s heart beat
* Grandma is working with a lawyer to make sure that doctors never put her on life support. She would prefer a natural death.
the prime of (one’s) life – in the best years of one’s life, when one has good health and things are going well
* Hedwig is 34 years old and should be in the prime of her life, but her depression is making her miserable.
to collapse – to suddenly fall down because one feels very weak or loses consciousness (the ability to think and be aware of where one is)
* Teri went running when it was 104o outside, and she collapsed due to the extreme heat and dehydration.
rounds – a doctor’s practice of visiting each of his or her patients in a particular order
* Next time the doctor comes in here on his rounds, remember to ask him for more pain medication.
condition – the medical or health status of an individual
* Julius is in poor condition, but the doctor says he can improve his health through exercise and by eating better.
to dread – to not want to do something; to be very worried or anxious about something that will happen
* Sequita dreads doing her taxes each spring.
respirator – a machine that helps a person breath, pushing oxygen through his or her lungs
* If Dad keeps smoking, he might end up on a respirator within a few years.
hooked up to monitors – attached to machines, especially to medical machines that observe one’s heart rate, blood pressure, breathing rate, and more
* Please don’t come visit me at the hospital. I don’t want anyone to see me hooked up to monitors.
IV drip – a clear plastic bag that is filled with liquid and hangs next to a patient with a long, thin plastic tube that connects it to a needle placed inside the patient’s vein, used to put liquid, nutrients, and medication in the patient’s bloodstream
* The doctors used an IV drip to rehydrate the runner.
lifeless – without life; not living; dead
* The child held the lifeless bird in her hands and cried.
under sedation – affected by medicine that makes one fall asleep or become very calm, unable to respond normally to other people
* The patient became very angry and violent toward the nurses, so the doctors put him under sedation.
Comprehension Questions
1. Which of these is a type of life support?
a) Respirator.
b) Monitor.
c) Rounds.
2. Why does George think Peter looks so lifeless?
a) Because he is dying.
b) Because he has died.
c) Because he is being medicated.
Answers at bottom.
What Else Does It Mean?
rounds
The word “rounds,” in this podcast, means a doctor’s practice of visiting each of his or her patients in a particular order: “The doctor is on his rounds right now, but I’ll have him give you a call once he’s finished.” A “round” can be a group of related events that is part of a larger series of events: “The second round of the debate will begin at 7:00 tomorrow evening.” A “round of applause” is the period of time when a group of people are clapping to show their appreciation for something: “It took the President a long time to finish his speech, because he had to stop talking for each round of applause.” Finally, the phrase “to make the rounds” means for something to be shared among many people: “An interesting magazine article is making the rounds through the office as co-workers share it with each other.”
condition
In this podcast, the word “condition” means the medical or health status of an individual: “You shouldn’t be outside of the house in your condition! The doctor said you should stay in bed and rest.” The word “conditions” means the situation in which people live: “They live in horrible conditions, without running water or electricity.” The phrase “the condition of (something)” refers to the quality of something: “What is the government doing to improve the condition of the local schools?” Finally, a “condition” is a term in an agreement, or a requirement for something else to happen: “Her continued employment is a condition for the loan.” Or, “Make sure you read all the detailed terms and conditions before signing the contract.”
Culture Note
When Americans are sick or injured and have to stay at the hospital for a period of time, their friends and family members often visit them to try to “cheer them up” (make someone feel better and happier).
Many visitors bring the patient a “bouquet” (floral arrangement; a pretty group of flowers) of flowers or a small plant to “brighten” (have lighter, sunnier colors) the room and freshen the air. Visitors might also bring music for the patient to listen to, or videos to watch. Other visitors might bring the patient his or her favorite foods, since the food served in hospital “cafeterias” (places that serve food to many people) is “notoriously” (famous in a bad way) bad. Of course, the doctors often want to control what the patients eat, so the visitors might have to “sneak it in” (bring the food secretly, without being seen).
Mostly, the visitors simply spend time with the patient, trying to “distract” (help someone stop thinking about something) him or her from the pain, discomfort, and worry. They might tell stories, look at photographs, or watch a movie together. People who share religious beliefs might “pray” (speak with God) together for a “speedy” (quick) “recovery” (return to good health).
People who cannot visit the hospital might send a card with a small gift, like flowers or a “stuffed animal” (a small, soft toy in the shape of an animal, normally for young children). Sometimes when a student is in the hospital, his or her classmates create a large “get-well” (designed to help someone feel better) card or “banner” (a large piece of paper to hang on the wall) and have everyone sign it.
Comprehension Answers
1 - a
2 - c