= 0574
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 574: Shopping for Produce.
This is English as a Second Language Podcast episode 574. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there to learn the secret of life! You can also download a Learning Guide for this episode that contains information, including a complete transcript to help you improve your English even faster.
This episode is called “Shopping for Produce.” “Produce” includes fruits and vegetables. Let’s get started.
[start of story]
On my way home from work, I stopped at the supermarket. My doctor has been telling me to eat more fresh fruits and vegetables, so I finally decided to follow her advice. I resolved to eat better, so I could feel better. I made a beeline for the produce department.
First, I looked at some bananas. Since they ripen off the vine, I picked out some that were already ripe and others that were still green. Next, I looked for some tomatoes. They looked picked over, but then I saw some organic tomatoes and decided to give those a try. Then, I went to look for the spinach. I found it, but it didn’t look fresh at all. The leaves were brown and wilted. I decided to pass on the spinach and checked out the mushrooms. The mushrooms didn’t look any better. In fact, some were beginning to rot. I picked up some lettuce instead and headed for the checkout stand.
I was feeling pretty good about my new decision to eat better. But then, I passed the cookie aisle. My resolve weakened. I spotted my favorite type of cookies. Before I knew what I was doing, I’d put a bag of those cookies in my cart.
I know I should be able to resist impulse buys, especially of things I’m likely to eat all in one sitting, but don’t forget, I’m eating more fruits and vegetables. With my new healthy diet, aren’t I allowed to fall off the wagon now and then?
[end of story]
Our story begins with me coming home from work. I decide to stop at the “supermarket,” which is a large store that sells many types of food. A “market” is a general word for a store, especially a story that sells food. A supermarket is just a big market. “My doctor,” I say, “has been telling me to eat more fresh fruits and vegetables.” “Fresh” is, in this case, an adjective that means recently picked – recently taken from the trees or the fields where they were grown. These are fruits and vegetables that are ready to be eaten or to be cooked; in other words, they’re not in a can, they’re the actual vegetable right from the farm.
I say that I was going to eat more fruits and vegetables because my doctor recommended that to me. I resolved to eat better, so I could feel better. “To resolve” here means to make a firm decision to change something in your behavior, usually to change something in your life. The noun is “resolution.” It’s very common for people to make New Year’s resolutions. When the first of January comes up every year they say, “Okay, I’m going to stop smoking,” or “This year I’m going to stop eating a pound of chocolate every day,” something like that. That’s a resolution; the verb is “to resolve.” “To resolve” can also mean to solve a problem or a conflict, an argument, something like that.
I say next that I made a beeline for the produce department. The expression “to make a beeline (beeline – one word) for (something)” means to go directly to a particular place or to a particular person without stopping to look at or to talk to anyone else; you go directly to that person. When children go to the library, some of them make a beeline for the comic books. They walk in the door, and they run over to the comic books; they don’t stop and look at anything else. Some men, when they walk into a bar, make a beeline for the beautiful women. Of course, I did not make a beeline for any women; I made a beeline for the produce department. “Produce” means fresh fruits and vegetables; it’s a general term.
First, I looked at some “bananas,” those are yellow pieces of fruit that are long and they grow on trees – I think. I say that since bananas, or because bananas ripen off the vine, I picked some that were already ripe. “To ripen (ripen) off the vine (vine)” means that they continue to mature and become “ripe,” or ready to eat, after they are removed from the plant. So there some fruits, for example, that you can take it off of the tree, like a banana, and you wait a couple of days, and it will turn from green to yellow indicating it is now ready to eat. There are some fruits that do not ripen off the vine, meaning you have to wait until they are ready – until they are ripe before you remove it from the tree or the plant. A “vine” technically is a plant that grows certain kinds of fruit. Grapes, for example, and tomatoes, grow on what we call vines. “To ripen off the vine,” however, is a general term referring to fruit that matures after it has been picked, or removed from the plant or tree where it was growing. So because bananas ripen off the vine, you can pick those bananas that are still green. A green banana indicates it is not yet ripe.
Next, I looked for some tomatoes. They looked picked over. When we say something is “picked over,” we mean that other customers have come and taken the best ones, so the ones that are left are not very good. That’s what it means to be picked over. Before I forget, the word “green” has other meanings in English, and those are in the Learning Guide.
I say that the tomatoes were picked over, but then I saw some organic tomatoes. “Organic” is a very popular adjective describing food nowadays. Usually it means that it is grown naturally, without any chemicals, anything that might damage your health. Organic food is supposed to be more healthy because it doesn’t have these different chemicals that are normally used when we are farming – and by “we” I mean other people, not me!
Then I look for some spinach, after I get my organic tomatoes. I found the spinach, but unfortunately it didn’t look fresh at all. It was old; it was not recently arrived from the farm. The leaves on the spinach, the part of the spinach that is flat and large, were brown and wilted. When we say something is “wilted” (wilted), we mean that the leaves of the fruit or vegetable are not fresh, they’re weak, they are bent. For example, lettuce if put in the oven will very quickly wilt with the heat. Things often wilt in the heat, and that means that they are no longer hard, crisp; they are weak instead, and they start to look bad, and that’s what happened to leaves of the spinach.
I decided to pass on the spinach. “To pass on (something)” here means to decide not to buy or not to use something. If you’re at a dinner and someone offers you some hot dogs, and you don’t really like hot dogs – although I can’t understand why, I love hot dogs! But you decide, well, hot dogs, they’re not very healthy, so you say to the person, “I think I will pass on the hot dogs,” meaning I’m not going to have any. “To pass on” has other very different meanings, and those are in – everyone together – the Learning Guide.
So, I pass on the spinach, and I decide to “check out,” or go look at (investigate) the mushrooms. The mushrooms didn’t look any better. In fact, some of the mushrooms were beginning to rot (rot). “To rot” is when something that is living, like a plant or a vegetable or a body begins to decay and decompose. When something dies it begins to fall apart, whether it’s a body or a banana. Usually it begins to have a bad smell and it begins to come apart physically. So that is the meaning of to rot; it’s when something that was once living dies and begins to smell and look ugly.
The mushrooms, I say, didn’t look any better because they were beginning to rot, so I picked up some lettuce – I took some lettuce and I put into my cart. My “cart” is another word for a shopping cart, which is a large metal basket on wheels that you use in a store; you push it. I picked up some lettuce and put it in my cart, and I then headed for the checkout stand. “To head for” means to go in the direction of. The “checkout stand” is the part of the grocery store where you pay for your food.
I was feeling pretty good about my new decision to eat better. But then, I passed (I walked by) the cookie aisle. In a store, you have usually several “aisles.” These are basically rows where you have food on both sides, usually on shelves. So I pass by the cookie aisle, the aisle that had the cookies in it, and my resolve weakened. Remember we mentioned “resolve” as being your decision to do something – to change something. Here it’s used as a noun: my resolve weakened. “To weaken” means to become less strong, to become weaker. I spotted (I saw) my favorite type of cookies. Before I knew what I was doing, I’d put a bag of those cookies in my cart. So, I saw the cookies, I could not resist them. I needed the cookies I thought, so I got them and I put them in my cart.
Finally I say, “I know I should be able to resist impulse buys.” An “impulse (impulse) buy (buy)” is something that you buy that you were not planning on buying. You did not have the idea before you got to the store, but you saw it and you decided to buy it. I say, “I know I should be able to resist impulse buys (meaning not buy those things), especially of things I’m likely to eat all in one sitting.” “All in one sitting” means all at once, at one time. If you give me a bag of potato chips I will eat them all in one sitting. “But,” I say, “don’t forget, I’m eating more fruits and vegetables. With my new healthy diet, aren’t I allowed to fall off the wagon now and then?” The expression “to fall off the wagon” means to resume a bad habit, to start doing something that you stopped doing such as, for example, smoking. If you say, “I’m going to stop smoking,” and then two months later you have a cigarette, you’ve fallen off the wagon. This is often used for people who are alcoholic, stop drinking, but then a few weeks, or months, or even years later they start drinking again. They fall off the wagon.
Now let’s listen to the story, this time at a normal speed.
[start of story]
On my way home from work, I stopped at the supermarket. My doctor has been telling me to eat more fresh fruits and vegetables, so I finally decided to follow her advice. I resolved to eat better, so I could feel better. I made a beeline for the produce department.
First, I looked for some bananas. Since they ripen off the vine, I picked out some that were already ripe and others that were still green. Next, I looked for some tomatoes. They looked picked over, but then I saw some organic tomatoes and decided to give those a try. Then, I went to look for the spinach. I found it, but it didn’t look fresh at all. The leaves were brown and wilted. I decided to pass on the spinach and checked out the mushrooms. The mushrooms didn’t look any better. In fact, some were beginning to rot. I picked up some lettuce instead and headed for the checkout stand.
I was feeling pretty good about my new decision to eat better. But then, I passed the cookie aisle. My resolve weakened. I spotted my favorite type of cookies. Before I knew what I was doing, I’d put a bag of those cookies in my cart.
I know I should be able to resist impulse buys, especially of things I’m likely to eat all in one sitting, but don’t forget, I’m eating more fruits and vegetables. With my new healthy diet, aren’t I allowed to fall off the wagon now and then?
[end of story]
You should never pass on a script written by our scriptwriter, the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
supermarket – a large store that sells many types of food to be cooked or prepared at home
* Please go by the supermarket on your way home from work to pick up bread, milk, and eggs.
fresh – recently picked; recently made or cooked; not old, stale, or rotten
* Wouldn’t it be great to have our own orange tree, so that we could have fresh oranges each morning?
to resolve – to make a firm decision to change something, usually to improve one’s quality of life
* Each New Year’s Eve, Miles resolves to stop smoking, but he always starts again within a few weeks.
to make a beeline for – to go directly to a particular person or place, without stopping to look at anything or anyone else
* At the library, the kids made a beeline for the comic books.
produce – fresh fruits and vegetables; fruits and vegetables that are not cooked, canned, or prepared in any other way
* My doctor said that one of the best ways to prevent cancer is to eat more fresh produce.
to ripen off the vine – to continue to mature and become ripe (ready to eat) after something is picked from the plant
* Does cantaloupe ripen off the vine, or is it important to buy cantaloupe that’s already ready to be eaten?
green – unripe; not yet fully mature or ready to be eaten
* These plums are still green, but I think they’ll be ready to eat within a few days.
picked over – with many items already selected for purchase, so that the remaining items aren’t very desirable
* The store had a great sale, but by the time we got there most things had already been picked over and we couldn’t find anything we liked.
organic – grown naturally, without the use of chemical pesticides or fertilizers
* If we had a garden in our backyard, we could make sure all our fruits and vegetables were organic.
wilted – with leaves that are weak and bent, not crisp, usually because they are too dry or old
* These houseplants are really wilted. We need to water them more often.
to pass on – to decide not to buy, use, or have something
* Alexey decided to pass on the movie and instead stay at home to study all evening.
to rot – to decay and decompose when something has been dead or separated from a plant for a long time
* All the vegetables in our refrigerator are rotting. We should really clean it out more often.
checkout stand – the part of a grocery store where one pays for everything one wants to buy
* This checkout stand is “express,” so you can use it only if you are buying 12 or fewer items.
aisle – row; one of the long parts of a store that one can walk through, looking at the products for sale on both sides
* Peanut butter and jam are in aisle eight.
to weaken – to become less strong
* Julia’s eyesight has gradually weakened over the years, and now she can hardly see anything.
cart – shopping cart; a large metal basket on wheels that one uses inside a store to carry all the things one wants to buy
* Victor’s cart was filled with ice cream, cookies, and chocolate candies. I guess he really likes sweets!
impulse buy – something that one buys without having planned to buy it, just because it looks good when one sees it in the store
* Lucas bought that sweater as an impulse buy, but he’s really glad he did!
all in one sitting – all at once; all at one time
* Have you ever eaten an entire half-gallon of ice cream all in one sitting?
to fall off the wagon – to resume a bad habit when one has been trying to stop it, usually used when talking about drinking alcohol
* Hal had stopped smoking for almost two weeks when he fell off the wagon and started again.
Comprehension Questions
1. What does “to make a beeline for the produce department” mean?
a) To buy honey in the produce department.
b) To be scared by a bee in the product department.
c) To go directly to the produce department.
2. Which of these things is most likely an impulse buy?
a) Bananas.
b) Lettuce.
c) Candy.
Answers at bottom.
What Else Does It Mean?
green
The word “green,” in this podcast, means unripe, or not yet fully mature or ready to be eaten: “My sister likes to eat green peaches, but I think they’re too crunchy.” The word “green” is also related to environmental protection and conservation: “Do you think the green movement is as important as reducing poverty?” If a person is “green,” it means that he or she is very young and/or doesn’t have very much experience doing something: “Nick is pretty green right now, but if we hire him, I think he’ll learn quickly.” Finally, the phrase “to have a green thumb” means to be very good at making plants grow and stay healthy: “If your plants are dying, ask Tomas for advice. He has a green thumb.”
to pass on
In this podcast, the phrase “to pass on” means to decide not to buy, use or have something: “Why did you pass on such a great offer?” The phase “to pass (something) on” means to make someone else pay the cost of something: “If the price of fuel increases, airlines just pass the cost on to the passengers through higher airfare.” The phrase “to pass (something) on” also means to share information with another person: “Could you please pass my telephone number on to your roommate?” The phrase “to pass (something) on” can also mean to give one’s child a physical characteristic or a disease through one’s genes: “I hope I don’t pass my big nose on to my children.” Finally, the phrase “to pass (something) down” means to give something to a member of a future generation: “This ring was passed down to Greta from her great-grandmother.”
Culture Note
The National Organic Program was created in 2002 to develop “standards” (regulations and rules) for organic products. Previously, farmers and food manufacturers followed many different “guidelines” (recommendations for how to do things) in labeling their food as organic. Some products were sold as organic if they were grown without chemical pesticides. Others were sold as organic if they didn’t use any chemical pesticides or fertilizers. And “still” (additionally) others were sold as organic only if the land hadn’t been “exposed to” (been in contact with) chemicals for a certain number of years. There were also different rules about organic meat, which generally must come from animals that have been fed only organic “grain” (cereals) without any antibiotics or hormones.
Under the National Organic Program, a farmer or food manufacturer must be “certified organic” (officially having documents proving it is organic) before it can “label” (put a name or description on something) its products as organic. Right now there are 56 agencies in the United States that have the authority to provide organic certification for the National Organic Program.
Today, the official “seal” (a small logo or design) of the National Organic Program has a white-and-green design saying “USDA (United States Department of Agriculture) Organic” inside a reddish-brown circle. A product can have that seal only if at least 95% of its “ingredients” (the things used to make a food or medicine) are organic.
Farmers and food manufacturers who label a product as organic when it actually isn’t may have to pay a “fine” (money paid as a punishment) of up to $11,000 for each “offense” (each time someone does something wrong). However, this is very difficult to enforce, because the National Organic Program has a very small “staff” (the number of people working for an organization).
Comprehension Answers
1 - c
2 - c