= 0583
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 583: Going to a Spa.
This is English as a Second Language Podcast episode 583. I’m your host, Dr. Jeff McQuillan, coming to you from Los Angeles, California.
Visit our website at eslpod.com. Become a member of ESL Podcast and you can download a Learning Guide, an 8- to 10-page guide we prepare for all of our current episodes that will help you improve your English even faster.
This episode is called “Going to a Spa.” It’s a dialogue between Tim and Jan using vocabulary that you would find at a spa. Let’s get started.
[start of dialogue]
Jan: This is the life! Spending the day at a spa is my idea of paradise.
Tim: Yeah, it’s great.
Jan: Aren’t you enjoying yourself?
Tim: The massage was okay, but why do I have to get a facial and a body wrap? I’m a guy!
Jan: Men need rejuvenating, too. These are all holistic treatments and you’ll feel like a new man when you’re done. Just enjoy the pampering.
Tim: I feel like an idiot. How am I supposed to relax?
Jan: Why don’t you get a body scrub or a scalp massage instead? Maybe that’ll calm your nerves.
Tim: I don’t need a body scrub or another massage. I just want to get out of here. When will we be done?
Jan: After this, all we have left are manicures and pedicures.
Tim: What?! I’m not getting a manicure or a pedicure.
Jan: You did promise to go with me to the spa if I agreed to have your four college friends stay in our house for two weeks, remember?
Tim: Yes, I remember. All right, let’s get this over with.
Jan: Just be glad I didn’t sign you up for waxing!
[end of dialogue]
Jan begins by saying to Tim, “This is the life!” That expression, “this is the life,” is used to show when you are very happy; you’re enjoying yourself very much, especially doing whatever it is you are doing right now. Jan says, “Spending the day at a spa is my idea of paradise.” A “spa” (spa) is a business where people go to usually receive some sort of treatment or service that makes them healthier, makes them relax, makes them more beautiful. That would be a spa. I definitely need a spa! Well, this spa is Jan’s idea of paradise. “Paradise” is a place that is very enjoyable, a very pleasant place; we might say “heaven.” This place is my idea of heaven – my idea of paradise.
Tim says, “Yeah, it’s great.” Jan says, “Aren’t you enjoying yourself?” She thinks maybe Tim really doesn’t like the spa that much. Tim says, “The massage was okay, but why do I have to get a facial and a body wrap? I’m a guy!” A “massage” (massage) is when someone touches you with their hands, usually, to try to relax your muscles, to relax your body; to relieve tension, we might say. Tim says, “The massage was okay,” but he wants to know why he needs to get a facial and a body wrap. A “facial” (facial) is a special treatment for your face, you can guess, that cleans it. It is usually something that involves using different creams, or things that they put on your face. I don’t know; I’ve never had one! A “body wrap” is where your whole body is covered in some sort of liquid, cream, lotion, or something else; it’s supposed to make the skin of your body softer. Facials and body wraps are things that traditionally a woman would get at a spa, not a man. I should also mention that “wrap” (wrap), as in body wrap, has other meanings in English that can be found in the Learning Guide.
So Tim says, “I’m a guy,” meaning I’m a man – I’m a male, I should not have to get these things. Jan says, “Men need rejuvenating, too.” “To rejuvenate” means to make younger, to make you feel better, make you feel new. Some people work all day, they come home, they have a glass of wine, and they feel rejuvenated; they feel like they now have more energy. Jan says, “These are all holistic treatments and you’ll feel like a new man when you’re done.” “Holistic” means here relating to your entire body; relating to all of your health, not just one particular part. The word “holistic” is used in many different ways, but usually it refers to the whole – the (whole) of something, although it’s spelled (holistic), no “w”.
Jan says that these holistic treatments will make Tim feel like a new man. She says, “Just enjoy the pampering.” “Pampering” comes from the verb “to pamper” (pamper). “To pamper (someone)” is to do some things for them to make them feel good, to relax them, to make them feel comfortable. Often these are things that we might consider luxurious, expensive, something that makes you feel good.
Tim says, “I feel like an idiot. How am I supposed to relax?” Jan says, “Why don’t you get a body scrub or a scalp massage instead?” A “body scrub” (scrub) is when they put certain things on your body, perhaps something that is rough – something that is what we would call “abrasive.” They rub it on your body in order to remove the dead skin cells so that your skin seems brighter and younger. A “scalp massage” refers to your “scalp” (scalp), which is the skin on top of your head, underneath your hair – if you have hair! So, a scalp massage would be someone massaging the top of your head basically. Jan says, “Maybe that’ll calm your nerves.” “To calm your nerves” means to make you feel more relaxed and comfortable. The person who comes home and has a glass of wine or a cup of tea may do so to calm their nerves, to make them less tense, make them more relaxed. The word “calm” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Tim says, “I don’t need a body scrub or another massage. I just want to get out of here. When will we be done?” When will we be finished here? Jan says, “After this, all we have left (meaning the only thing that remains for us to do) are manicures and pedicures.” A “manicure” (manicure) is when you go somewhere and they make your fingernails look good. They cut them; they perhaps paint them if you’re a woman, typically. It’s supposed to make your fingernails look better. A “pedicure” (pedicure) is the same thing but for your toenails, the nails on your feet. When I’m talking about “nails,” I’m talking about something that is at the end of each finger or toe, on the top of them, that protects the very top of the finger. Again, manicures and pedicures are typically things that a woman would get, not a man.
Tim says, “What?! I’m not getting a manicure or a pedicure.” Jan says, “You did promise to go with me to the spa if I agreed to have your four college friends stay in our house for two weeks, remember?” You see, the reason Tim is there is it’s something he is doing for his wife. What his wife is doing for him is allowing him to invite his friends from college – from his college years, many years ago – to stay in their house. Tim says, “Yes, I remember. All right, let’s get this over with.” “Let’s get this over with” means let’s complete this, let’s finish this as soon as possible; usually you say it about something that is painful or not pleasant.
Jan says, “Just be glad I didn’t sign you up for waxing!” “Waxing” (waxing) is another beauty treatment where hair is removed from a particular part of your body by taking hot wax – “wax” is what you make a candle out of – you take hot wax and you put it on the skin, and then you allow it to cool a little so that it isn’t as hot, and then you pull it off, and with it will come your hair in that part of your body. It can, needless to say, be somewhat painful, especially for a man who has a lot of hair. So Jan is saying just be glad I didn’t sign you up for – meaning making appointment for you – for waxing, something that would, again, normally be done to a woman.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jan: This is the life! Spending the day at a spa is my idea of paradise.
Tim: Yeah, it’s great.
Jan: Aren’t you enjoying yourself?
Tim: The massage was okay, but why do I have to get a facial and a body wrap? I’m a guy!
Jan: Men need rejuvenating, too. These are all holistic treatments and you’ll feel like a new man when you’re done. Just enjoy the pampering.
Tim: I feel like an idiot. How am I supposed to relax?
Jan: Why don’t you get a body scrub or a scalp massage instead? Maybe that’ll calm your nerves.
Tim: I don’t need a body scrub or another massage. I just want to get out of here. When will we be done?
Jan: After this, all we have left are manicures and pedicures.
Tim: What?! I’m not getting a manicure or a pedicure.
Jan: You did promise to go with me to the spa if I agreed to have your four college friends stay in our house for two weeks, remember?
Tim: Yes, I remember. All right, let’s get this over with.
Jan: Just be glad I didn’t sign you up for waxing!
[end of dialogue]
Your English, we hope, was rejuvenated today by the wonderful script by Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
this is the life – a phrase used when one is very happy and relaxed, enjoying oneself very much, and wishing one could do that particular activity all the time, every day
* Ah, this is the life! I wish we could eat like this every day, but we’d each weigh at least 300 pounds!
spa – a business where people go to receive treatments and services that improve their beauty and health and help them relax
* Let’s go to the spa and relax in the sauna for a few hours.
paradise – heaven; a place that is very enjoyable and pleasant
* The view here is so beautiful. It’s like being in paradise.
massage – a treatment where one person uses his or her hands to push into the muscles of another person’s back and other body parts, either to relieve tension (help the person relax) or to treat an injury
* After a long, stressful week at work, Helene was really looking forward to a professional massage.
facial – a treatment that cleans and moisturizes one’s face through the use of several different scrubs, creams, and lotions
* The day before the wedding, the bride and all her best friends got facials at the local beauty salon.
body wrap – a treatment in which one’s body is covered in a cream, lotion, or another substance and then covered with warm towels, usually to soften the skin and relax the body
* Did you hear about the new body wrap at the spa? They cover your body in chocolate, mud, and warm rocks to relax the muscles!
rejuvenating – refreshing; making one feel better, younger, or like new
* If you drink this rejuvenating juice each morning, you’ll feel like you’re 20 years younger.
holistic – relating to the entire body or one’s entire health, and not just a particular part
* Orion’s doctor believes in holistic medicine that treats the entire body, and not just the body part that has a problem.
pampering – treatments and services that are luxurious and designed to make someone feel very comfortable and relaxed
* As a college student, I always enjoyed going back to my parents’ home for some pampering: home-cooked meals, laundry service, and more.
body scrub – a treatment where slightly abrasive products (like sand, nut shells, etc.) are rubbed all over the skin to remove dead skin cells and make skin appear brighter and younger
* This body scrub uses small pieces of apricot pits to remove dead skin.
scalp – the skin on one’s head, under one’s hair
* Dandruff is a condition where one’s scalp is covered with many small pieces of dead skin.
to calm (one’s) nerves – to make someone feel more relaxed and comfortable
* Maybe a nice cup of hot tea will calm your nerves before you have to give your speech.
manicure – a beauty treatment in which one’s fingernails are cut, shaped, moisturized, and painted
* Mia chose to get a French manicure where only the tips of the fingernails are painted white.
pedicure – a beauty treatment in which one’s toenails are cut, shaped, and painted, and one’s feet are moisturized, with the dead skin being removed
* As the weather gets warmer, many women want to get pedicures before they start wearing sandals.
waxing – a beauty treatment in which hair is removed from a particular part of one’s body by placing hot wax over the skin and letting it cool slightly before pulling it off, tearing the hairs out
* Our salon offers waxing services for the eyebrows, chin, and legs.
Comprehension Questions
1. Which of these services are primarily for the skin?
a) A massage.
b) A body scrub.
c) A pedicure.
2. Which of these treatments does not happen on the head?
a) A facial.
b) A scalp massage.
c) A manicure.
Answers at bottom.
What Else Does It Mean?
wrap
The phrase “body wrap,” in this podcast, means a treatment in which one’s body is covered in a cream, lotion, or another substance, and then covered with warm towels, usually to soften the skin and relax the body: “Was the body wrap as relaxing as you had hoped?” When talking about food, a “wrap” is a type of sandwich with food rolled into a tortilla (flat bread) instead of being placed between two slices of bread: “I’d like the turkey-bacon wrap, please.” When talking about clothing, a “wrap” is a large piece of clothing worn around a woman’s shoulders: “If it’s too cold to wear a sleeveless dress, you can always use this wrap.” Finally, “plastic wrap” is a very thin, clear piece of plastic used to cover the food in a bowl or dish: “If you cover those strawberries with plastic wrap, they won’t dry out in the fridge.”
to calm (one’s) nerves
In this podcast, the phrase “to calm (one’s) nerves” means to make someone feel more relaxed and comfortable: “The doctor says she’ll be okay, but I’m afraid he said that just to calm my nerves.” The phrase “to be a bundle of nerves” describes the feeling of being very nervous: “He was a bundle of nerves before his interview.” The phrase “to lose (one’s) nerve” means to lose the courage to do something: “Hank was going to ask for a raise, but he lost his nerve.” The phrase “nerves of steel” means the ability to be very brave and controlled even in a difficult or dangerous situation: “That firefighter must have nerves of steel!” Finally, the phrase “to get on (someone’s) nerves” means to annoy or bother someone: “The way you chew with your mouth open really gets on my nerves.”
Culture Note
A “typical” (common; normal) spa has many different types of employees who work together to create a “luxurious” (beautiful, comfortable, relaxing) pampering experience for their “clients” (customers). Some clients might work with only one of these employees, but other clients who come in for a “total” (complete) “makeover” (a transformation to change one’s physical appearance) might work with almost all of them.
A “hairstylist” helps the client get his or her hair to “look its best” (be as beautiful as possible). The hairstylist “shampoos” (washes), cuts, dries, and “styles” (gives shape to) the hair. A hairstylist might also color the hair or add “highlights” (color added to small sections of hair), although this might also “fall to” (be the responsibility of) a “hair colorist,” depending on the size of the spa.
A “manicurist” specializes in providing manicures and pedicures. A “hair removal specialist” or “hair removal technician” is an expert in waxing, helping people remove unwanted body hair. Some larger spas might have a hair removal specialist who provides “permanent” (forever; not temporary) hair removal services through the use of a “laser” (strong light) or another technology.
A “masseuse” is someone who specializes in giving different kinds of massages. A masseuse might work closely with an “aroma therapist” who uses different “aromas” (odors; smells) to help the client reach different goals, such as relaxing or thinking more clearly.
Finally, a “makeup artist” applies “makeup” (colors painted on the face) for the clients. Makeup artists also offer lessons in makeup “application” (techniques for putting on makeup) so that clients can learn to create the same “look” (physical appearance) at home.
Comprehension Answers
1 - b
2 - c