= 0587
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 587: Feeling Disillusioned.
This is English as a Second Language Podcast episode 587. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can to download a Learning Guide for this episode, an 8- to 10-page guide that contains all of the vocabulary, definitions, sample sentences, additional definitions – come on, say it with me – cultural notes, comprehension questions, and a complete transcript of everything we say.
This episode is called “Feeling Disillusioned,” about someone who is sad and disappointed in something. Let’s get started.
[start of dialogue]
Daniela: I did it. I finally met Mandy Timpkin.
Tony: Mandy Timpkin, your idol?
Daniela: Yeah, I stood in line for two days at her book signing and finally met her. It was a big disappointment.
Tony: Really? I thought she could do no wrong, as far as you’re concerned.
Daniela: Well, that was before I met her. I have always wanted to be just like her. She had everything going for her: a great life and a great career. I emulated her in so many ways. I thought she must be a paragon of virtue and a great person to be around. I walked into that bookstore with all of these preconceived notions.
Tony: What happened to shatter your image of her?
Daniela: While I waited in line, I saw what kind of person she really was. She was rude to everybody and made ridiculous demands of her assistants. It wasn’t how I pictured her at all. She was a real diva.
Tony: So meeting her really burst your bubble.
Daniela: Yeah, it really did. I guess it was my own fault for putting her on a pedestal.
Tony: Well, you’re not the only one. Celebrities wouldn’t be celebrities if we didn’t idolize them.
Daniela: True enough, and I’ve learned my lesson. Nobody’s perfect, least of all celebrities!
[end of dialogue]
Daniela says to Tony, “I did it. I finally met Mandy Timpkin.” Tony says, “Mandy Timpkin, your idol?” An “idol” (idol) is someone you love, someone you admire; you want to be like that person. It’s often a famous person, it doesn’t have to be. An idol is literally something that you worship, that you believe has almost special powers. Some people have idols who are famous politicians, famous actors, podcasters perhaps – probably not! That will be an idol. We especially in the U.S. have the term “teen idol,” this would be usually a very attractive boy – they usually are boys, less than 18 years old, but they could be older – and all of the young girls fall in love with this famous singer. That would be a teen idol.
Well this is just your idol, meaning someone that you admire. Daniela says, “Yeah, I stood in line (I waited) for two days at her book signing and finally met her.” A “book signing” is an event where the author of a book “autographs,” or writes his or her name on copies of the book for people who bought it. Bookstores sometimes have a book signings by famous authors; they come and they sign the book. I’ve gone to some of these; they often give a little talk, which can be interesting. Daniela says, however, that meeting her idol Mandy Timpkin, who is obviously a writer, was a big disappointment. “Disappointment” means feeling sad because something that you thought was going to be good or great was not; it was less than what you thought it would be. That’s disappointment.
Tony says, “Really? I thought she could do no wrong, as far as you’re concerned.” When we say someone “can do no wrong” we mean they are perfect; they cannot make a mistake. My wife believes I can do no wrong. Right, honey? She’s not answering me! Daniela thought that Mandy Timpkin could do no wrong – was perfect. Tony says, “as far as you’re concerned.” “As far as you’re concerned” or “(someone) is concerned” means in someone’s opinion, according to this person’s belief. As far as I’m concerned – as far as what is important to me, in my opinion, we have the best listeners in the world right here at ESL Podcast. That’s you!
Daniela says, “Well, that was before I met her (I thought she was perfect before I actually had a chance to meet her).” Daniela says, “I have always wanted to be just like her. She had everything going for her: a great life and a great career.” “To have everything going for (someone)” means to be very fortunate, to have a lot of advantages, to be very lucky in life. Well, Daniela says that Mandy had a great life and a great career. She says she emulated her in so many ways. “To emulate” (emulate) means to copy the things that another person does or says, to try to behave just like this other person. Daniela emulated, in the past, Mandy. She thought that Mandy must be a paragon of virtue and a great person to be around. A “paragon (paragon) of virtue” is someone who is perfect in every way, someone who has no flaws, usually someone who has very high what we might call moral standards. Someone who never does anything wrong: never cheats, never lies, never steals. That would be a paragon of virtue.
Well, that’s what Daniela thought Mandy Timpkin was. She says, “I walked into that bookstore with all of these preconceived notions.” A “notion” (notion) is an idea. A “preconceived notion” is an idea you have about something without having all of the facts, without being able to actually experience or observe what it is you have this idea about. For example, some people when they come to Los Angeles have a lot of preconceived notions. They have things that they have heard about or read about or seen on TV or in the movies that makes them think they know what Los Angeles is like, and then they come here and it’s very different. Hollywood Boulevard, for example, which is a very famous tourist site here in Los Angeles, people have a lot of preconceived notions about what that’s like. Well, if you come, you will see! A preconceived notion is usually wrong, that’s the implication.
Tony said, “What happened to shatter your image of her?” “To shatter” (shatter) means to break something into very small pieces. It can also be used to talk about how your dreams or your hopes were destroyed, how something happened that made them go way, you no longer had this dream or this hope. That’s what “shatter” means here. “Shatter” actually has more definitions, and those are in the Learning Guide. Well, Tony wants to know what happened to shatter Daniela’s image of Mandy Timpkin. “Image,” here, means the ways someone appears – someone looks.
Daniela says, “While I waited in line, I saw what kind of person she really was. She was rude (not very nice) to everybody and made ridiculous demands of her assistants.” “Ridiculous” means crazy, not normal, way beyond what you would expect. A “demand” is something you say you must have. So, this woman made ridiculous demands on the people who were helping her, her assistants. Daniela says, “It wasn’t how I pictured her at all. She was a real diva.” “To picture” means to imagine how something will be. It has other meanings as well, this word “picture.” The Learning Guide will tell you more. Well, Daniela found out that Mandy was a real diva (diva). A “diva” is a woman who has a lot of success, usually in singing or acting, but doesn’t treat other people very nicely. A diva is someone who is great at what they do but is not a very nice person, and usually diva is applied to a woman. I guess a man would be a “divo,” but we never say that, if that’s the correct word. We usually would call a man a real – well, I can’t say it on the podcast!
Tony says, “So meeting her really burst your bubble.” This expression, “to burst (burst) someone’s bubble,” means to destroy your belief, your hope, the way that you saw something or someone, and now you see it is not as good or as interesting as you thought it was. So, it’s another way of saying a great disappointment. Something burst your bubble; it made you see that you were wrong about what you were hoping for.
Daniela says, “Yeah, it really did. I guess it was my own fault for putting her on a pedestal.” “To put (someone) on a pedestal” means to believe that someone is perfect, to admire them too much. A “pedestal” is what you put a statue of a famous person on. So to put a person that you know on a pedestal means to think that they are great.
Tony says, “Well, you’re not the only one. Celebrities wouldn’t be celebrities (that is, famous people would not be famous) if we didn’t idolize them.” “To idolize” (idolize) is a verb that comes from the first word we talked about, “idol.” It means to admire someone too much, to think that someone is perfect. Daniela says, “True enough (meaning I agree, you’re right), and I’ve learned my lesson (meaning now I have learned that I was wrong). Nobody’s perfect, least of all celebrities!” “Least of all” means especially; it’s a phrase used to give emphasis to the words that follow it. So, “Nobody’s perfect, least of all celebrities” means celebrities are probably the least perfect or the most flawed of anyone.
The title of the dialogue was “Feeling Disillusioned.” “To be disillusioned” means that you have dreams about how great something is and then you are disappointed. Usually, to be disillusioned means that you had a vision – you had a picture of the way a situation was going to be or going to turn out, and then you were very bitterly, we might say, disappointed – greatly disappointed.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Daniela: I did it. I finally met Mandy Timpkin.
Tony: Mandy Timpkin, your idol?
Daniela: Yeah, I stood in line for two days at her book signing and finally met her. It was a big disappointment.
Tony: Really? I thought she could do no wrong, as far as you’re concerned.
Daniela: Well, that was before I met her. I have always wanted to be just like her. She had everything going for her: a great life and a great career. I emulated her in so many ways. I thought she must be a paragon of virtue and a great person to be around. I walked into that bookstore with all of these preconceived notions.
Tony: What happened to shatter your image of her?
Daniela: While I waited in line, I saw what kind of person she really was. She was rude to everybody and made ridiculous demands of her assistants. It wasn’t how I pictured her at all. She was a real diva.
Tony: So meeting her really burst your bubble.
Daniela: Yeah, it really did. I guess it was my own fault for putting her on a pedestal.
Tony: Well, you’re not the only one. Celebrities wouldn’t be celebrities if we didn’t idolize them.
Daniela: True enough, and I’ve learned my lesson. Nobody’s perfect, least of all celebrities!
[end of dialogue]
She’s no diva, and I put her on a pedestal because she deserves it: our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
idol – someone whom one loves, worships, or admires very much, possibly wanting to be that person
* When you were a teenager, did you have any posters of your idols hanging on your bedroom walls?
book signing – an event where an author autographs (writes his or her name on) copies of his or her book for people who have bought the book
* How many hours did you have to stand in line at the book signing to get the author’s autograph?
disappointment – a feeling of sadness that one has when something is not as good, useful, or interesting as one had expected
* It was a major disappointment for Margie when she found out she hadn’t been accepted to study at the university.
can do no wrong – unable to make a mistake; perfect
* Most kids grow up thinking their parents can do no wrong, at least until they become teenagers.
as far as (someone) is concerned – in someone’s opinion; according to someone’s beliefs
* As far as the government is concerned, water quality isn’t a high priority.
to have everything going for (someone) – to be in a very fortunate, strong position with many advantages
* Michel was a great athlete who had everything going for him until he got in a car accident and became paralyzed.
to emulate – to copy the things another person says or does, trying to be like that person; to behave like someone else does
* In our speech class, we’re trying to emulate the style of Martin Luther King, Jr.
paragon of virtue – someone who is perfect in every way and has no flaws or faults; someone who has very high moral (beliefs about right and wrong) standards
* Jung tries to pretend he’s a paragon of virtue, but he lies all the time.
preconceived notion – an idea of how something is or should be, especially when that idea is not based on facts and one has not had an opportunity to observe that thing in detail
* When Brenda traveled to Asia for the first time, she had a lot of preconceived notions about how people would act around her, but she soon learned that many of those ideas were wrong.
to shatter – to break something into many small pieces, often used when talking about glass; to destroy someone’s dreams, beliefs, or hopes
* The earthquake shattered all the glass vases that had been standing on the shelf.
image – vision; picture; the way something looks or appears
* My image of the main character in the book is very different from what I saw in the movie adaptation.
to picture – to imagine how something is or appears
* When you were a child, did you picture your adult life as it is now?
diva – a woman who has had a lot of success in a performance career, especially if she isn’t very nice personally and treats others poorly
* The actress is very popular and people love to see her movies, but she’s such a diva that nobody wants to spend time with her in person.
to burst (one’s) bubble – to destroy a person’s beliefs, vision, or hope, showing him or her that something isn’t as good, useful, or interesting as he or she thought it was
* They had dreamed of becoming millionaires by investing in real estate, but the fall in the housing market burst their bubble.
to put (someone) on a pedestal – to believe that someone is perfect; to admire someone too much
* He’s so in love with his girlfriend that he always puts her on a pedestal, but someday he’s going to realize that she’s just human and that she makes mistakes just like all the rest of us
to idolize – to admire someone too much; to think that someone is perfect
* The more I read about Gandhi, the more I idolize him and his work.
least of all – especially; a phrase used to give emphasis to the word(s) following the phrase
* I would never hurt anyone on purpose, least of all my own mother.
Comprehension Questions
1. What did Daniela do before she met Mandy?
a) She tried to be like her.
b) She thought she was a diva.
c) She wrote a book about her.
2. Why was Daniela disappointed when she met Mandy?
a) Because Mandy didn’t look the way Daniela had expected.
b) Because Mandy didn’t sign her copy of the book.
c) Because Mandy didn’t treat other people very nicely.
Answers at bottom.
What Else Does It Mean?
to shatter
The verb “to shatter,” in this podcast, means to destroy something by breaking it into many small pieces, often used when talking about glass: “When the baseball hit the window, the glass shattered and the children ran away.” Or, “if you pour hot water into a cold glass, you might make it shatter.” The verb “to shatter” can also mean to destroy someone’s dreams, beliefs, or hopes: “Being fired shattered his hopes of retiring within the next five years.” The word “shattering” means upsetting: “Hearing such shattering news put her in a bad mood for weeks.” Something that is “earth-shattering” is very important and surprising: “After 47 years of living as a bachelor, Blake called with the earth-shattering news that he’s getting married!”
to picture
In this podcast, the verb “to picture” means to imagine how something is or appears: “She pictured a career as a fashion model to be very glamorous, but she soon found out that it’s a lot of work.” Or, “That paint color isn’t quite how I pictured it. Let’s try a different color instead.” Something that is “picture-perfect” is exactly right, correct, or appropriate: “Melissa wants everything to be picture-perfect on her wedding day.” Or, “Having a dinner with all of my family around me is the picture-perfect gift.” Finally, a “picture window” is a very large window made of just one piece of glass: “They’re replacing all the small, old windows in their home with beautiful picture windows.”
Culture Note
“Fans” (people who like, love, and admire someone or something very much) can “show” (demonstrate) their admiration in many ways. In the past, fans “were limited to” (had no options other than) sending “fan mail,” or letters written to their idols, expressing how much they admire those people and their work. Today, however, with the “advent” (when something begins to be used by many people) of the Internet and “social networking” (related to connecting people) sites, fans have many other options.
Fans often create “fan sites,” or websites that are all about their idol. These fan sites typically try to attract other fans of the same celebrities. Some fan sites are organized by the celebrities themselves, but many others are organized by the fans. Other fans follow the “tweets” (messages sent via Twitter) of their favorite celebrities. For example, actor Ashton Kutcher is the most-followed user on Twitter, thanks to all his fans.
Fans of musicians and bands sometimes show their admiration by “forming” (creating) “tribute bands,” or musical groups that perform the music of the idolized musician. This usually happens after the idol has “retired” (is no longer performing) or “passed away” (died).
Other fans try to show their admiration by “adopting” (using as one’s own) the clothing style, hairstyle, or “manner” (way) of speaking of their idolized celebrities. For example, many American women “wear their hair” (have a certain hairstyle) like the actress Jennifer Aniston, at least in part because they admire her work and think she is very beautiful.
Comprehension Answers
1 - a
2 - c