= 0902
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 902: Being Chivalrous and Protective.
This is English as a Second Language Podcast episode 902. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. If you go there and become a member, you can download a Learning Guide for this episode.
This episode is about a man and a woman. The man is going to be chivalrous, or at least that's what we hope. Let’s get started.
[start of story]
When I first met Lance, I thought he was the perfect guy. He was a real gentleman. He opened doors for me and pulled out my chair in restaurants. He was as chivalrous as they come. But after a while, I realized that he took chivalry a little too far.
...
Lance: Let me carry that box for you.
Guinevere: No, that’s okay. It’s not heavy.
Lance: It doesn’t matter. I’m your boyfriend and I can’t have you carrying a box when my hands are free.
Guinevere: Is that some kind of code of conduct I don’t know about?
Lance: It’s how a knight would treat his lady.
Guinevere: That’s nice, but I’m perfectly capable of carrying my own box, thank you.
Lance: Don’t argue. It’s my duty to show every courtesy to my girlfriend, so give me that box.
Guinevere: Are you saying that your code of conduct takes precedence over my preferences?
Lance: No, I’m just telling you that my job is to help and protect you, even if it’s against your will.
...
How can you argue with that logic?
[end of story]
Our story begins with Guinevere telling us about how she met this man by the name of Lance. She says, “When I first met Lance” – when I met him the first time – “I thought he was the perfect guy” – the perfect man, the perfect person. “Guy” here would probably refer to a man, however. Sometimes, people will use “guys” in the plural to mean both men and women, but when it's singular, it's usually a man, I think.
Anyway, Guinevere says that this Lance was a real gentleman. A “gentleman” (gentleman) is a man who behaves well, who acts nice, especially with women. A man who has good manners could be called a gentleman. “Lance opened doors for me and pulled out my chair in restaurants.” These are two things that traditionally gentlemen – men with good manners – are supposed to do. If you are walking into a building and there is a woman with you, as the man, you are supposed to open the door and let her walk in first. Similarly, if you are sitting down at a restaurant somewhere, or sitting down to eat, the man will go over and pulled the chair out to make it easier for the woman to sit down so the woman doesn't have to pull her own chair out. That's what Lance did with Guinevere when they first were dating, when they first were going out as a romantic couple.
“Lance,” Guinevere tells us, “was as chivalrous as they come.” “Chivalrous” (chivalrous) is similar to being a gentleman. It means to be courteous. It means to be well mannered. It means to pay special attention to being nice to women. “Chivalrous” is an adjective. “Gentleman” is a noun. The two are related, however. We describe a man who acts like a gentleman as being chivalrous, especially when we're talking about how that man treats or acts toward women. Guinevere says, “He was as chivalrous as they come.” The expression “as they come” means more than other people, or simply very much. “He's as rich as they come” would mean he is one of the richest people you will ever know. He's very rich.
“Lance was as chivalrous as they come. But after a while,” Guinevere says, “I realized that he took his chivalry a little too far.” “To take something too far” means to do too much of something or to go to such an extreme that now it's almost a bad thing. You're doing it too much. “Chivalry” is the noun related to the adjective “chivalrous.” Well, Lance apparently is taking his chivalry too far.
We begin then with the dialogue. Lance says to Guinevere, “Let me carry that box for you.” That might be another thing the gentleman might do for a woman – carry her bags or carry her things that are heavy.
Guinevere says, “No, that's okay. It's not heavy.” Lance says, “It doesn't matter.” That's not important. “I'm your boyfriend and I can't have you carrying a box when my hands are free.” The expression “to have your hands free” means that you're not holding anything, that you can use your hands to do something, in this case, to help carry the box. Guinevere says, “Is that some kind of code of conduct I don't know about?” A “code” (code) is a set of rules or laws. “Conduct” (conduct) is how you act. A “code of conduct” would be rules for how you act, especially formal rules that some organization, perhaps, creates. Guinevere is asking if what Lance wants to do is part of some kind of, or some variety of code of conduct.
Lance says, “It's how a knight would treat his lady.” A “knight” (knight) is a title of honor that is given to a man by the king or the queen. In the United States, we don't have a king or queen so we don't have knights. But, for example, in Great Britain, in the United Kingdom, there is a queen who makes some men, anyway, knights – people with a lot of power, a lot of influence. Important people are often knighted. We can even use that word as a verb, “to knight.” The term “lady” (lady) here means a woman with good manners, a woman with grace, a woman who is considered to be well behaved, well mannered.
Guinevere says, “That's nice, but I'm perfectly capable of carrying my own box. Thank you.” “To be capable,” (capable) means to have the ability, to have the skills, or the knowledge to do something. “To be perfectly capable,” means you are completely capable. “Perfectly” is just a word to emphasize. It's sort of like “very” capable.
Lance says, “Don't argue. It's my duty to show every courtesy to my girlfriend so give me that box.” Lance is telling Guinevere not to disagree with him. “Don't argue.” Lance hasn’t been a boyfriend very long. You got a lot to learn, Lance, let me tell you. Anyway, Guinevere says she's perfectly capable of carrying her own box but Lance says that it's his “duty” (duty) to show every “courtesy” (courtesy) to his girlfriend. Your “duty” is your obligation, your responsibility, the thing you are supposed to do. “Courtesy” is something that is nice, something that is polite that you do to show your respect to someone, to show that you are well behaved, that you have good manners. “Courtesy” is a noun that describes those activities or those actions.
Guinevere says, “Are you saying that your code of conduct takes precedence over my preferences?” “To take precedence (precedence) over something” means to be more important than something, to come before something. You should never let your job, your work, take precedence over your family. It should never be more important than your family.
Guinevere is asking if Lance’s code of conduct, his rules for chivalry, take precedence over her preferences. Lance says, “No, I'm just telling you that my job is to help and protect you even if it's against your will.” “To protect someone” means to keep them safe, to make sure that nothing bad happens to them. “To do something against your will” means the opposite of what you want. “He did it against his will.” That means he didn't really want to do it but he did it anyway. Lance is saying that it is his duty to protect Guinevere even if Guinevere doesn't want him to.
Guinevere ends our story by saying, “How can you argue with that logic?” “Logic (logic) is thinking, usually thinking in a rational, intelligent way. In some cases, it means following certain formal rules of reasoning, of thinking, of logic. We think about Aristotle and his writings about logic. In this case, Guinevere is saying that it's difficult to try to convince Lance that he's wrong because he has this set of reasons that don't seem to allow for anyone to differ with him. That's why she says, “How can you argue with that logic?” Sometimes we might say that when we think the person is correct and they are saying something we agree with – sometimes we might say this expression or use this expression when we think the person’s ideas are a little crazy and there is no way we could agree with them. It can have opposite meanings. I'm not sure which meaning it has for Guinevere.
Now let's listen to the dialogue, this time at a normal speed.
[start of story]
When I first met Lance, I thought he was the perfect guy. He was a real gentleman. He opened doors for me and pulled out my chair in restaurants. He was as chivalrous as they come. But after a while, I realized that he took chivalry a little too far.
...
Lance: Let me carry that box for you.
Guinevere: No, that’s okay. It’s not heavy.
Lance: It doesn’t matter. I’m your boyfriend and I can’t have you carrying a box when my hands are free.
Guinevere: Is that some kind of code of conduct I don’t know about?
Lance: It’s how a knight would treat his lady.
Guinevere: That’s nice, but I’m perfectly capable of carrying my own box, thank you.
Lance: Don’t argue. It’s my duty to show every courtesy to my girlfriend, so give me that box.
Guinevere: Are you saying that your code of conduct takes precedence over my preferences?
Lance: No, I’m just telling you that my job is to help and protect you, even if it’s against your will.
...
How can you argue with that logic?
[end of story]
Our script was written by a very capable lady indeed, Dr. Lucy Tse – “Lady Lucy,” we might call her.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
gentleman – a man who behaves very well and has very good manners
* A real gentleman doesn’t lie, cheat, or steal.
to pull out (someone’s) chair – to slide a chair back from a table to prepare it for someone (usually a woman) to sit down; to help someone sit
* During a lunch interview, am I supposed to pull out the interviewee’s chair, or would that be too strange?
as (something) as they come – very much; more than other people
* Lauralee is as talented as they come. She’ll be a famous actress someday.
chivalrous – courteous and well mannered, paying special attention to and taking care of women
* Albert is very chivalrous, always holding the door open for women.
to take (something) a little too far – to do too much of something or to go to an extreme so that what would normally be a good thing becomes a bad thing
* Shane has a great sense of humor, but this time he’s taking the joke a little too far.
(one’s) hands are free – to not be holding anything or doing anything with one’s hands; to have empty hands
* When Naomi goes to the zoo, she puts everything in a backpack so that her hands are free.
code of conduct – the rules that govern one’s behavior; a set of rules that tell people how to behave
* The students code of conduct prohibits plagiarism, or presenting other people’s work as one’s own.
knight – a title of great honor given to a man or soldier by a king or queen
* Candee loves to read stories about knights who ride horses and save princesses from dragons.
lady – a woman of good birth, good manners, and grace and elegance
* A lady always crosses her legs when she sits down.
capable – having the knowledge, skills, and ability to do something
* Do you think Rodger is capable of facilitating the meeting with our new client?
duty – something that one must do; a responsibility or obligation
* As the administrative assistant, his duties include answering the phones, sorting the mail, and greeting customers.
courtesy – something nice and polite that one does to show respect and good manners
* As a courtesy to others, make sure you always say “please” and “thank you.”
to take precedence over – to be more important than something else
* Dylan loves his job, but he never lets his work take precedence over his family.
to protect – to keep someone or something safe and out of danger
* What can we do to protect our investments from the effects of the recession?
against (one’s) will – the opposite of what someone wants
* You can’t keep me here against my will!
logic – one’s way of thinking, especially rationally and following a set of rules for clarity and organization
* I don’t understand that hiring committee’s logic. Why did they choose him over me?
Comprehension Questions
1. What did Lance do when he pulled out Guinevere’s chair?
a) He helped her sit down in her chair.
b) He found a place for her to sit.
c) He brushed off the seat of the chair.
2. What does Lance mean when he says, “My hands are free”?
a) His hands are very strong.
b) He won’t charge her for his help.
c) He isn’t holding anything.
Answers at bottom.
What Else Does It Mean?
to take (something) a little too far
The phrase “to take (something) a little too far,” in this podcast, means to do too much of something or to go to an extreme so that what would normally be a good thing becomes a bad thing: “It’s good to eat healthy foods, but Sheila is taking the dieting a little too far.” If something is “far-fetched,” it is very unlikely and difficult or impossible to believe: “Hank thinks we’ll get five new clients this month, but I think his plans are far-fetched.” The phrase “far-reaching” means having a lot of impact or influence: “The governor has proposed a far-reaching policy that would affect almost everyone in the state.” Finally, someone who is “far-sighted” is able to come up with good ideas because he or she understands what will happen in the future: “If we had been more far-sighted, we would have invested in computer technology 20 years ago.”
lady
In this podcast, the word “lady” means a woman of good birth, good manners, and grace and elegance: “My mother always said that a lady never swears.” A “bag lady” is a homeless woman who carries all her things with her: “There’s that poor bag lady again. Should we give her some money and food?” The “first lady” is the wife of the President of the United States: “The first lady doesn’t have an official position in the government, but she is expected to support her husband and have programs of her own.” Finally, the phrase “old lady” is an informal, slightly rude way to talk about someone’s wife or girlfriend: “So, your old lady let you go out with the guys last night, huh?”
Culture Note
Traditionally Chivalrous Acts
Men have to “walk a fine line” (be very careful in achieving a balance) when performing “chivalrous acts” (things one does to be chivalrous), because some modern women “interpret” (perceive and understand in a particular way) their actions as a sign of “sexism” (being biased against women (or men)). For example, if a man holds open a door, many women will be “flattered” (honored and pleased), but some women will be “insulted” (upset and angry) because they interpret it as a sign of a man showing that he is stronger than she is.
“Nevertheless” (even though that is true), men can perform many chivalrous acts to show their respect and admiration for women. In addition to holding open doors and car doors, they can hold an umbrella over a woman’s head when it is raining. If it is cold outside, they can offer the woman their jacket. If it is too cold or rainy, the man can go to get the car and bring it closer to the door so that the woman does not have to walk in the “inclement weather” (bad weather).
Traditionally, to be chivalrous, when walking down the street, the man walks on the side of the sidewalk that is closest to the street, so that if a car drives through a “puddle” (water that has collected in a low part on a street), it will not splash onto her.
Similarly, in a restaurant, a man stands up as a woman arrives at the table and when she stands up to leave the table. Men can also pull out the woman’s chair to make it easier for her to sit down.
Comprehension Answers
1 - a
2 - c