= 0907
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 907 – Buying Tools at a Hardware Store.
This is English as a Second Language Podcast episode 907. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the city of, the beautiful city of, Los Angeles, California.
Our website is of course, ESLPod.com. Become a member of ESL Podcast and download a Learning Guide to this episode.
This episode is a dialog about buying tools, things you use in order to fix other things or make other things, at a hardware store, a place where you buy tools. Let’s get started.
[start of dialog]
Chuck: Just remember that we have a lot to accomplish today, so let’s just get what we need and go, okay?
Ayaka: Sure, we just need a few tools for our DIY project. The power tools are over there.
Chuck: Whoa, we’re not getting power tools. We just need a few simple hand tools: a hammer, a wrench, a chisel, some pliers – and maybe an extra screwdriver or two.
Ayaka: We would get the job done so much more quickly if we had power tools. Instead of a hammer, we should get a nail gun. We also need a power drill, and hey, a sander and a table saw.
Chuck: A table saw?! We’re doing some simple repairs, not remodeling our house.
Ayaka: You never know when you need a good saw and I’ve always wanted a table saw.
Chuck: Other women want clothes and jewelry, and you want power tools?
Ayaka: That’s right. You should be counting your lucky stars!
[end of dialog]
Our dialog begins with Chuck saying to Ayaka, “Just remember that we have a lot to accomplish today, so let's just get what we need and go, okay?” Chuck is telling Ayaka that they have a lot to “accomplish” today, meaning they have a lot of things they need to do today, to get done today. He just wants to go into the store, get what they need, and leave.
Ayaka says, “Sure. We just” – or only – “need a few tools for our DIY project.” “DIY” is an abbreviation for the phrase, “Do It Yourself.” “To do it yourself” means to build something or construct something on your own. If you want to table, you could buy a table or you could do a “DIY project.” a do-it-yourself project where you build the table.
Ayaka says, “The power tools are over there.” “Power tools” are tools that are electric, that you plug into a wall. For example, you could have a power drill. That’s a kind of tool that is used to make holes in something. “Power tools” are any tools that run on electricity. Chuck says, “Whoa, we’re not getting any power tools.” That first word “whoa” is used to express surprise. Chuck is surprised that Ayaka wants to buy some power tools.
He says, “We just need a few simple hand tools.” A “hand tool” is something that is not electric. It's a tool that you just use your own physical force, with your own bodily force, or power. A hammer, for example, is a hand tool. It’s used to hit things that you need to put into, say, a piece of wood, like a nail.
Chuck says, “We just need a few simple hand tools: a hammer, a wrench, a chisel, some pliers – and maybe an extra screwdriver or two. “Hammer,” we just mentioned, is a tool usually that has a wooden handle that is you grab it by, a long piece of wood, and at the end of the wood, there is a heavy metal part that is used to hit (usually) nails. “Nails” are small pieces of metal that you use to attach something or to put something into a piece of wood. That's a hammer.
A “wrench” (wrench) is a tool made of metal. The handle, the part that you grab onto with your hand, is long and narrow. On the top of the tool, there is what looks like the letter “U” turned on its side, and you are able to make the “U” smaller or larger in order to fit over, say, a pipe – a long round metal tube – that you want to turn. That's a wrench.
A “chisel” (chisel) is a tool that has a wooden handle and a long flat piece of metal at the other end that is sharp. It's a way of cutting into wood, for example. There are other uses for a chisel. When we think about the great sculptors like Michelangelo, we think of someone with a hammer and a chisel, using the chisel to remove pieces of rock from the marble so that he can make the statue. That's another use of a chisel.
“Pliers” (pliers) is a tool that looks a little like a pair of scissors. It's made of (usually) metal, and is used to grab things – not to cut things, typically, but to grab them and turn them, or pull them.
A “screwdriver” (screwdriver) is a tool, again usually made of metal, that looks like a long stick, and at one end of the stick is a narrow piece of metal that is part of the stick. that's used to turn something called the “screw.” A “screw” is a small piece of metal that goes into a piece of wood or other material by turning it. A “nail” is a small piece of metal that goes into wood or other material by hitting it. So, that's what a screwdriver does. It screws or puts than screw into a piece of wood or metal or other material.
Ayaka says, “We would get the job done so much more quickly if we had power tools.” Ayaka is saying, “Yes, we can buy hand tools, but power tools would be quicker. Instead of a hammer, we should get a nail gun.” The other way of putting a nail into a piece of wood or other material is to buy an electric tool, a power tool, called a “nail gun.” It's not a real gun. A “nail gun” is a power tool that pushes nails into wood in a way that doesn't require you to pound or hit anything. It's all done by the machine. A “power drill” (drill) is a tool used to create a narrow, deep hole in a piece of wood or metal or other material.
So, Ayaka says that instead of a hammer, we should get a nail gun. “We also need a power drill, and hey, a sander and a table saw.” Ayaka is walking around the hardware store, and she's seeing things that she wants to get. That's why we have this somewhat unusual expression in the middle of the sentence, “and hey.” Here it indicates that she has just seen something and she's stopping herself in order to describe what she sees. In this case, it's something she wants. It's a “sander.”
A “sander” (sander) is a machine that is used to make wooden surfaces, a piece of wood, smooth by rubbing or moving back and forth something called “sandpaper.” “Sandpaper” is a piece of paper that has small, hard objects on it, and if you rub it back and forth over a piece of wood, the wood will become smooth. That's what a “sander” does. A “sander” is an electric power tool.
A “table saw” is a large machine that is used to cut long pieces of wood. A “saw” (saw) could also be a hand tool. You can have a handsaw that you move back and forth. It's like a big knife that you’re moving back and forth to cut something, such as a piece of wood. A “table saw” is a saw that runs on electricity that you would have in your garage or wherever you’re working that is used to cut long pieces of wood – or short pieces of wood, I guess.
Chuck says, A “table saw? We’re doing some simple repairs, not remodeling our house.” Chuck doesn't like Ayaka’s idea of buying all of these power tools. He says, “We’re doing some simple, some easy repairs.” “Repairs” (repairs) are corrections or modifications to fix something, to get something working again. If you have a refrigerator, and it stops working, you need to get it repaired. You need to fix whatever the problem is – or you can just buy a new refrigerator. Chuck says that they're not “remodeling” their house. “To remodel” (remodel) means to make major or large changes in your house. If you are remodeling your kitchen, you might be removing all of the things in your kitchen and basically building a new kitchen or changing things significantly. That's “to remodel.”
Ayaka says, “You never know when you need a good saw, and I've always wanted a table saw.” “You never know” means you can't possibly anticipate when you will, in this case, need a good saw. Chuck says, “Other women want clothes and jewelry, and you want power tools?” Chuck is surprised that Ayaka wants to buy these tools, which we might associate more traditionally with men. Ayaka says “That's right.” That's correct. “You should be counting your lucky stars.” “To count (count) your lucky stars” means to be very grateful for something that has happened, something that you don't have any control over. What Ayaka is saying here, somewhat jokingly, is that Chuck is a very lucky husband because his wife doesn't want to go out and spend money and buy clothes and jewelry, like perhaps some other wives do. No, his wife just wants to buy power tools.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Chuck: Just remember that we have a lot to accomplish today, so let’s just get what we need and go, okay?
Ayaka: Sure, we just need a few tools for our DIY project. The power tools are over there.
Chuck: Whoa, we’re not getting power tools. We just need a few simple hand tools: a hammer, a wrench, a chisel, some pliers – and maybe an extra screwdriver or two.
Ayaka: We would get the job done so much more quickly if we had power tools. Instead of a hammer, we should get a nail gun. We also need a power drill, and hey, a sander and a table saw.
Chuck: A table saw?! We’re doing some simple repairs, not remodeling our house.
Ayaka: You never know when you need a good saw and I’ve always wanted a table saw.
Chuck: Other women want clothes and jewelry, and you want power tools?
Ayaka: That’s right. You should be counting your lucky stars!
[end of dialog]
We count our lucky stars for having the wonderful scriptwriter, Dr. Lucy Tse, writing for us.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
DIY – do it yourself; a project done by an individual without any special experience or training, and without hiring specialists or professionals
* If you have to cut a hole in the roof to install the skylight, it probably isn’t a DIY project.
power tool – a tool that plugs into the wall and is operated with electricity
* You have to complete the training and earn certification before the company will allow you to use any of the power tools.
hand tool – a tool that is held in one’s hand and operated by one’s physical movements, without the use of electricity.
* There isn’t much space to work in here, so I’ll need to use my smallest hand tools.
hammer – a tool with a wooden handle and a heavy metal end, used to hit nails so that they are pushed into a piece of wood or a wall
* Don’t use a stapler to try to pound those nails! Use a hammer instead.
wrench – a metal tool with a metal handle and an open u-shaped piece of metal at the top, used to hold onto nuts or a pipe and make them turn
* This is too tight for me to unscrew with my hand, but I bet I could do it with a wrench.
chisel – a tool with a wooden handle and a long, flat piece of metal at the other end, used to shape a piece of wood, separate tile from a wall, and to perform other tasks that need a fine edge
* We used a chisel and a hammer to chip away the rock wall.
pliers – a tool shaped like scissors, with metal or plastic handles and a metal tip that can open and close, used to grab small items, possibly to turn or cut them
* Use these pliers to hold the wires in place while I pull at them from the other side.
screwdriver – a tool with a metal or wooden handle and a pointed piece of metal at the other end that fits into a screw and can be used to turn it as it pushes into a piece of wood or metal
* The directions say to use a screwdriver to attach the shelf to the back of this bookcase.
nail gun – a tool that pushes nails into wood with a lot of force and a loud, popping sound, eliminating the need for a hammer
* Professional roofers use nail guns instead of hammers, because they can install the roofing material much more quickly that way.
power drill – a machine that uses electricity to create a narrow, deep hole in or through a piece of wood
* Use a power drill to make a small hole first, and then it will be easier to put the screw in.
sander – a machine that uses electricity to make a rough wooden surface smoother by rubbing it with “sandpaper”
* Yesterday they finished installing the boards on the back deck. Today they’re sanding it with a sander, and tomorrow they’ll paint it.
table saw – a large machine that uses electricity to cut boards of wood, with a person guiding them over a table that has a large cutting blade that spins very quickly in the middle of the table
* For safety, always wear eye protection and gloves when using a table saw, and be careful not to touch the blade while it is spinning.
repair – a fix; a correction or modification to make something work again after it has broken
* The bike store charged me $50 for the seat repair.
to remodel – to change the structure or layout of something, especially a home, often removing or adding walls or rooms
* We’d love to remodel our home so that it has two bathrooms.
to count (one’s) lucky stars – to be very grateful for something that has happened, but that one has little or no control over
* Every day we thank out lucky stars for our good health.
Comprehension Questions
1. Which of these tools would you use to make wood smoother?
a) A chisel.
b) Pliers.
c) A sander.
2. Why does Ryo say that Chuck should count his lucky stars?
a) Because he should be grateful that his wife is interested in tools.
b) Because he should be grateful that his wife lets him spend money on tools.
c) Because he should be grateful that they have enough money to buy so many tools.
Answers at bottom.
What Else Does It Mean?
wrench
The word “wrench,” in this podcast, means a metal tool with a metal handle and an open u-shaped piece of metal at the top, used to hold onto nuts or a pipe and make them turn: “Plumbers use many wrenches of different sizes to hold onto pipes and turn nuts.” As a verb, “to wrench” means to pull something with a forceful, twisting movement: “Sheila screamed when her baby was wrenched out of her arms.” The phrase “to wrench (oneself) away” means to pull away from another person or thing: “If you can wrench yourself away from the TV for a while, I’d like to talk to you.” Finally, the phrase “to throw a monkey wrench in the works” means to do something that causes problems for other people and slows down or prevents progress: “That storm is going to throw a monkey wrench in the works for our vacation.”
repair
In this podcast, the word “repair” means a fix or modification to make something work again after it has broken: “Who does most of the home repairs in your house?” If something is “in need of repair,” it needs to be fixed: “Please make a list of everything that is in need of repair.” If something is “beyond repair,” it is ruined and cannot be fixed: “After the flooding, the carpet in their basement was beyond repair.” The phrase “under repair” means being fixed: “How long has the tunnel been under repair, and when do they expect to finish?” The phrase “in good/bad repair” means to be in good or poor condition: “Why would you consider buying a home in such bad repair?”
Culture Note
"This Old House"
“This Old House” is a popular American “home improvement” (related to fixing homes and making them more comfortable and valuable) TV show that began in 1979 and is still being “aired” (shown on TV) today, with at least 800 episodes. The show “follows” (monitors and shares information about) home “remodeling projects” for several weeks, showing the different stages of the construction process and explaining steps in detail so that viewers can try to complete similar remodeling projects “on their own” (independently; alone).
The show has had several “hosts” (the people who organize and present a show), but the person who is most often “associated with” (thought about in connection with) the show was Bob Vila, who had “gained recognition” (become well-known) for his work “renovating” (improving an old building) older homes. Bob Vila was the show’s host from 1979 to 1989. He “left the show” (stopped participating in production of the show) under “controversial circumstances” (a situation where people strongly disagree about something) and “went on to” (continued with something else) be a “spokesman” (a representative to makes statements to the public on behalf of an organization) for Sears, a large department store that sells many tools. Then he hosted a new show, “Bob Vila’s Home Again.” He has also written several books about home remodeling projects and “historic homes” (older homes that have significant historical and cultural value)
“This Old House” continues to air on “PBS” (Public Broadcasting Service). Since Bob Vila’s departure, it has “spun off” into two other shows: “Ask This Old House” where viewers’ questions are answered by experts, and “Inside This Old House,” which focuses on specific themes. There is also a magazine called This Old House.
Comprehension Answers
1 - c
2 - a