= 0913
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 913 – Experiencing Motion Sickness.
This is English as a Second Language Podcast episode 913. I'm your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website.
This episode is a dialog between Ashley and Terrell about something called “motion sickness,” when you get sick inside of a moving vehicle. Let’s get started.
[start of dialog]Welcome to English as a Second Language Podcast number 913 – Experiencing Motion Sickness.
This is English as a Second Language Podcast episode 913. I'm your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website.
This episode is a dialog between Ashley and Terrell about something called “motion sickness,” when you get sick inside of a moving vehicle. Let’s get started.
[start of dialog]
Ashley: You don’t look so good. What’s wrong?
Terrell: I felt motion sickness watching that movie. The camera jerked around and it made me dizzy.
Ashley: It didn’t bother me. The hand-held camera used to film the movie had that effect on you?
Terrell: I’m susceptible to motion sickness. You should see me on a boat. The rocking motion makes me seasick and nauseous. When I was a kid, I used to get carsick every time my family took a road trip. My parents always had a barf bag ready.
Ashley: Wow, that sucks.
Terrell: Yeah, and don’t even try to get me on an airplane. Just the starting of the engines makes me feel airsick and looking down gives me vertigo.
Ashley: So how do you travel?
Terrell: Very rarely and usually with one foot on the ground!
[end of dialog]
Ashley says to Terrell, “You don't look so good,” meaning you don't look very healthy. You look sick. “What's wrong?” Terrell says, “I felt motion sickness watching that movie.” “Motion sickness” is a feeling of what we would call “nausea,” feeling sick in your stomach or sick to your stomach, caused usually by being in a car, or a boat, or an airplane, or some other vehicle, some other means of transportation.
Terrell, however, was not in a vehicle. He was watching a movie, and he says the movie gave him motion sickness. Terrell said, “The camera jerked around and it made me dizzy.” Terrell is saying that the camera moved back and forth suddenly and quickly from one place to another. That's what he means by the phrasal verb “to jerk (jerk) around” – to move quickly back and forth. This term can also be used informally when you have a situation where you are, perhaps, not treating someone very well. You tell them one thing and then five minutes later you tell them another thing. This is especially true if you’re a boss, or if you're in charge of another person. “To jerk someone around” is a very negative way of describing someone's behavior and how they are treating another person. They're treating them by making decisions that change very quickly.
Terrell is talking about a camera that is moving back and forth. He says the cameras jerking around made him “dizzy” (dizzy). “Dizzy” is a feeling in your head that everything is moving or spinning around you. When you're dizzy, you feel like you may fall down. If you spin around in a circle ten times, you'll feel dizzy. You'll feel like you might fall down.
Ashley said the movie didn't bother her, didn't affect her. She then asks Terrell, “The hand-held camera used to film the movie had that affect on you?” “Hand-held” is something you hold in one of your hands. A “camera,” of course, is used to film or to record the movie. So, a “hand-held camera” would be a camera used, usually, to make a movie, although it could just be a camera used to take pictures. In some movies nowadays, the makers of the movie will use a hand-held camera because they think perhaps it provides a more “realistic” image for the people watching the movie, although, I’m not a filmmaker, so I can’t give you any exact explanations.
Ashley is asking Terrell if the hand-held camera that was jerking around had that “effect on you.” “That effect” refers to motion sickness. An “effect” (effect) is a result or an outcome or a consequence. Terrell says, “I’m susceptible to motion sickness.” When you’re “susceptible (susceptible) to something,” you are very easily affected by it or can easily have a problem with it. “Susceptible” is usually used when talking about, for example, an illness or a sickness, or something negative in your behavior. Young children may be susceptible to colds. They may be more likely to get a cold, or a sick person with an infection is more susceptible to serious health problems, because they are sick. Terrell says he’s susceptible to motion sickness.
He says, “You should see me on a boat.” That expression, “you should see me,” means you have to imagine this situation because I would really show you or you would really understand it if you were to see me in this other situation. For example, you should see me on a bicycle. I am a wonderful bicyclist. That’s not true, but the example here is that you can imagine that person, and if you did see the person in that situation, you would realize exactly what they're talking about.
Terrell says, “The rocking motion” – on a boat – “makes me seasick and nauseous.” A “rocking (rocking) motion” is a motion that goes back and forth many times, usually somewhat slowly. “To be seasick” (seasick) – one word – means to have motion sickness caused by being on water, by being in a boat or ship. That's “seasick.” It's just the same as motion sickness. “Motion sickness” is the general term. If you're on a boat, we might call it “seasickness.” If you’re in car, it would be to be “carsick,” and so forth.
“Nauseous” as I mentioned earlier, means feeling sick to your stomach, like you're going to vomit, like you're going to throw up. Terrell says, “When I was a kid, I used to get carsick every time my family took a road trip.” So, now we see that word “carsick” that I just mentioned. That means getting motion sickness by being in a car. A “road trip” is when you take a long driving trip somewhere. The United States is a very big country, and it's popular for people to take road trips, to travel to, say, a different state to see a national park, or to visit a different city. These are driving trips that can often take several days. When I was young boy, my father, who was a schoolteacher, would take us on road trips in the summer time when he didn't have to work. One road trip was almost six weeks long. That was a really, really long trip.
Anyway, Terrell says that his parents always had a “barf bag” ready. A “barf (barf) bag” is a somewhat informal term to describe a small paper bag that you usually find on an airplane for people who get motion sickness and are going to be physically sick, who are going to throw up. These bags are used so that you can not make a mess, basically. “Barf” (barf) as a verb means to vomit, but it's a word that is only used informally.
Ashley says, “Wow, that sucks.” This is, again, a very informal use of a verb. “To suck” as a verb here means to be terrible, to be awful. It's very informal, and probably not one you'd want to use in a business setting. Some people still think it's a little vulgar, even. So, I would be careful about using this. It is, however, used commonly in conversation, and you'll certainly hear it in movies and television shows. When someone says something “sucks,” they mean it's bad. It's very bad.
Terrell agrees. He says, “Yeah, and don't even try to get me on an airplane.” “Don't even try” means, “Do not attempt to (in this case) get me on an airplane.” Of course, you can imagine that Terrell would get sick on an airplane as well. He says, “Just the starting of the engines makes me feel airsick.” The “engines” (engines) are the motors, the machines that give the airplane energy so it can fly. Terrell is saying as soon as the engines start, as soon as they start working, they start running on an airplane, he starts to get airsick. “Airsickness” is when you have motion sickness on an airplane.
So, now we have “seasick,” “carsick,” and “airsick” for motion sickness on a boat, in a car, and on an airplane. Terrell says that looking down gives him “vertigo.” “Vertigo” (vertigo) is a feeling of dizziness caused by being up at a very high location. If you are in a very tall building, and you look out the window down to the street, you might get vertigo. It might cause you to be dizzy. There was a famous Alfred Hitchcock movie called Vertigo.
Ashley says, “So, how do you travel?” How do you get from one place to another if you always have motion sickness? Terrell says, “Very rarely,” not very often, “and usually with one foot on the ground,” meaning he walks. He doesn't take any sort of vehicle to get from one place to another.
Now let's listen to the dialog, this time at a normal speed.
[start of dialog]
Ashley: You don’t look so good. What’s wrong?
Terrell: I felt motion sickness watching that movie. The camera jerked around and it made me dizzy.
Ashley: It didn’t bother me. The hand-held camera used to film the movie had that effect on you?
Terrell: I’m susceptible to motion sickness. You should see me on a boat. The rocking motion makes me seasick and nauseous. When I was a kid, I used to get carsick every time my family took a road trip. My parents always had a barf bag ready.
Ashley: Wow, that sucks.
Terrell: Yeah, and don’t even try to get me on an airplane. Just the starting of the engines makes me feel airsick and looking down gives me vertigo.
Ashley: So how do you travel?
Terrell: Very rarely and usually with one foot on the ground!
[end of dialog]
Our dialogues never suck because they're written by the wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
motion sickness – the feeling of nausea (feeling sick to one’s stomach) caused by being in a moving vehicle
* Yolanda suffers from motion sickness, but rolling down the windows for fresh air seems to help.
to jerk around – to make many sudden, short movements so that something is not steady or smooth
* The man said he was showing off a new style of dance, but to us it just looked like his body was jerking around.
dizzy – feeling as if one’s head is spinning around or the world is moving in circles
* The children played on the merry-go-round for so long that they became dizzy and couldn’t walk in a straight line.
hand-held camera – a still camera or video camera that is small enough to be held in one’s hand while being used, not resting on a tripod (a stand that supports a camera)
* This smart phone has such a great camera that it’s almost as good as the hand-held camera I bought three years ago!”
effect – result, influence, or outcome
* How can we measure the effects of our medical program to help the poor if we don’t have enough volunteers?
susceptible – likely to be affected by something, especially in a negative way
* The elderly and young babies are most susceptible to the common cold.
rocking – moving back and forth many times, usually gently
* Sit in this rocking chair to help the baby fall asleep.
seasick – with motion sickness caused by the movement of a boat, ship, or a floating platform over the water
* The cruise ship is so big that nobody gets seasick, because passengers can’t really feel the boat’s movements.
nauseous – feeling sick to one’s stomach, as if one is going to throw up (vomit)
* Many pregnant women are nauseous in the morning, especially during the first part of their pregnancy.
carsick – with motion sickness caused by the movement of a car as it travels over roads
* Jaime is more likely to become carsick on winding mountain roads than on a flat, straight highway.
road trip – a long journey traveling by car, especially when the experience of traveling by car is almost as important as the destination (where one is going)
* The day after their college graduation, they started on a cross-country road trip.
barf bag – an informal term for a small paper bag that people can vomit (throw up) into, especially on an airplane
* The flight had a lot of turbulence and many people reached for the barf bag in their seat pocket.
to suck – an informal word used to mean to be very unpleasant, disappointing, gross, offensive, or unwanted
* That sucks that your fight was delayed and you had to spend the night at the airport.
engine – a machine that converts (transforms; changes) energy into motion and is used in most vehicles, such as cars, boats, and airplanes
* Do you know much about repairing car engines?
airsick – with motion sickness caused by the movement of an airplane or helicopter as it travels through the air
* I don’t mind traveling on big jets, but I always get airsick on smaller planes.
vertigo – dizziness and the feeling of losing one’s balance, often from looking at the ground from a very high place, caused by a disease affecting the ear
* Sheila was suddenly overcome with vertigo and she had to sit down for a few minutes.
Comprehension Questions
1. Which of these might you experience on a train?
a) Seasick.
b) Carsick.
c) Airsick.
2. Which of these feelings might make someone reach for a barf bag?
a) Being dizzy.
b) Having vertigo.
c) Being nauseous.
Answers at bottom.
What Else Does It Mean?
dizzy
The word “dizzy,” in this podcast, means feeling as if one’s head is spinning around or the world is moving in circles: “Holly loved playing on the swings as a child, but once she became older, they made her dizzy.” The phrase “dizzy with” means overwhelmed by a feeling: “Greg felt dizzy with pride as he accepted the award.” The phrase “a dizzy blonde” describes a woman with blonde (light-colored) hair who is very stupid, silly, and forgetful: “Telling jokes about dizzy blondes is inappropriate in the office.” Finally, the word “dizzying” can mean causing someone to feel exciting, with a lot of movement: “Chuck grew up in the country and found it difficult to adapt to dizzying city life when he moved away for college.”
rocking
In this podcast, the phrase “rocking” means moving back and forth many times, usually gently: “Please stir the contents of the bottle with a gentle rocking motion.” The phrase “to rock the boat” means to create problems by doing something that is unexpected and not what other people are doing: “If you want to keep your job, just stay quiet and don’t rock the boat.” The phrase “to rock (someone’s) world” means to change someone’s life by making him or her think about something in a new way: “That book rocked my world. You have to read it!” The phrase “to rock out” means to enjoy loud music, either by making music or by dancing to it: “They rocked out until the early hours of the morning.” Finally, the informal phrase “(something/someone) rocks” means that one admires someone or something and thinks it is very good: “Wow, this new job rocks!”
Culture Note
Shaky Camera Techniques
Over time, the film industry has developed many “techniques” (ways of doing something) to produce a “stable” (not moving) image, especially while recording action. Traditionally, film producers wanted to “eliminate” (get rid of) the small movements caused by a human hand holding a camera. However, in recent years, some “videographers” (people who make films) are “purposely” (on purpose; intentionally) using “shaky” (with many small movements) camera techniques.
The shaky camera technique can be produced with a hand-held camera, or with equipment that “replicates” (copies) the movements of a hand-held camera. These techniques are often used to make the film appear to be “unrehearsed” (not practiced), especially to show people “capturing” (recording) images quickly, as they are happening, like a reporter running after a “subject” (the person or thing being recorded).
For example, the TV series ER was about medical professionals working in an “emergency room” (the part of a hospital that treats patients with life-threatening problems) and used shaky camera techniques to make the show seem more exciting, as if the viewer were running with the medical professionals “alongside” (next to) the “gurney” (a bed on wheels, used to move patients). The 1996 film, Twister used shaky film techniques to make viewers feel as if they were following a “tornado” (a very strong, dangerous windstorm). And the 1999 film The Blair Witch Project used shaky film techniques to make it appear that students were recording their experience when they were lost in the “woods” (forest).
The shaky camera techniques can make films more exciting, but some people experience “severe” (very strong) motion sickness. In fact, some movie theaters “post” (put up on the wall) announcements warning viewers about shaky camera techniques so that they can be “forewarned” (know about something bad ahead of time) of possible nausea and dizziness.
Comprehension Answers
1 - b
2 - c