= 0922
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 922 – Getting a Second Opinion.
This is English as a Second Language Podcast episode 922. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode has a Learning Guide on our website at ESLPod.com. Become a member and download a Learning Guide.
This dialogue between Greg and Anne is about someone who doesn’t believe their doctor – who at least wants to get someone else’s opinion, an additional opinion, about a medical condition. Let’s get started.
[start of dialogue]
Greg: Where are you going?
Anne: I’m going to see another doctor to get a second opinion. My doctor diagnosed me with a serious medical condition, and I don’t want to take it at face value.
Greg: You’re second-guessing your doctor?
Anne: No, I just want to make sure he’s right. He’s also recommending a conservative treatment for this condition, and if I really have it, I want to be more aggressive.
Greg: Doesn’t your doctor mind that you’re getting a second opinion?
Anne: No, he even gave me a recommendation for another specialist.
Greg: What’s all of that?
Anne: This is a complete set of my records along with my test results. I’m hoping he’ll have a fresh perspective when he looks at all of it and my patient history.
Greg: What are you hoping he’ll find?
Anne: The best-case scenario is that he’ll find that my doctor was wrong and that I don’t really have this condition.
Greg: If he tells you that, wouldn’t you be dubious? You’ll have one doctor telling you that you have it, and one telling you that you don’t.
Anne: Then it would be time for a third opinion.
[end of dialogue]
Greg begins our dialogue by asking Anne, “Where are you going?” Anne says, “I’m going to see another doctor to get a second opinion.” The expression “second opinion” means you’ve gotten the recommendation or opinion of one person, but you want to get someone else’s opinion, someone else’s recommendation. The expression is often used in talking about healthcare – about medicine – when you talk to one doctor who says you should do this, and then maybe you don’t like that idea, or you don’t think the doctor knows what he’s talking about, so you go to see another doctor and get his or her opinion.
Anne wants to go see another doctor to get a second opinion. She says, “My doctor diagnosed me with a serious medical condition, and I don’t want to take it at face value.” “To diagnose” (diagnose) means to identify a problem, especially a medical problem – why someone is sick or what illness a person has. “Medical condition” refers to a disease or an illness that you have, some problem in your body. The expression “to take something at face (face) value” means to accept something as being true, but without investigating it very much – to believe that it’s true without getting more information, without researching it.
“Face value” is a term that we often use in talking about money. We talk about the face value of a coin, or the face value of a certain bill, a certain piece of money. Sometimes, money that’s very old might be worth more than what it says on the piece of money. That would be where you have something that is worth more than the face value of the coin, or the face value of the bill.
So, if you have a five cent coin from, I don’t know, 1893, it might be worth more than five cents even though the face value is still five cents. When I was growing up, we used to collect pennies, and you try to collect pennies from different years but also from different mints. A “mint” (mint) here means the places where they manufactured or made the coins, and that would be indicated on the coin itself.
Anyway, getting back to our dialogue, Anne doesn’t believe her idiot doctor and wants to get another opinion. Greg says, “You’re second-guessing your doctor?” “To second guess” means to question someone’s opinion or to question someone’s actions. Anne says, “No. I just want to make sure he’s right.” I want to be certain he’s correct.
“He’s also recommending a conservative treatment for this condition, and if I really have it, I want to be more aggressive.” “Treatment” refers to how you try get someone better, how you try to heal someone, how you try to get someone to recover from their sickness or illness. A “conservative treatment” would be a treatment where you do the minimum. You do a small amount but not as much as you could. The opposite of conservative here would be “aggressive” (aggressive). “Aggressive treatment” would be to do the maximum, to do as much as possible to try to get the person over their sickness or to get the person healthy.
Greg says, “Doesn’t your doctor mind that you’re getting a second opinion?” Here, the verb “to mind” means to be bothered by. “Doesn’t your doctor mind that you’re getting a second opinion?” Anne says, “No. He even gave me a recommendation for another specialist.” A “specialist” (specialist) is a doctor in this case, who knows a lot about one particular illness, one particular kind of medical condition. You might have a specialist in ears and throats and noses. In fact, there is something called an “ear, nose, throat specialist.” In American hospitals, these are doctors who know a lot about those three things. So, if you have a problem with your ears – my wife thinks I have a problem with my ears – you would go to an “ear, nose, and throat specialist.”
Greg says, “What’s all of that?” He sees something else that Anne is holding in her hand. Anne says, “This is a complete set of my records along with my test results.” The word “records” (records) has a couple of different meanings. Here, it refers to documents or pieces of paper or, nowadays, electronic files that have information about you. “Medical records” is a reference to documents about your health – how old you are, how much you weigh, results from medical tests you might have taken in the past, and so forth.
Anne, in fact, talks about “test results.” “Test results” are outcomes of exams or analyses, especially when we are referring to things like a blood test. The doctor takes some of your blood, and then they analyze the blood for certain things. That would be – once you get the results, once you get what the analysis says – your test results. Anne has all this information that she’s going to give the other doctor, the other specialist.
She says, “I’m hoping he’ll” – the doctor – “have a fresh perspective when he looks at all of it” – all of my records – “and my patient history.” A “fresh perspective” means a new opinion about something, especially from someone who has not been involved in the case or involved in the situation. If you work on something for a very long time, sometimes you can’t see certain issues or certain problems because you’re too close to it. You’ve been involved with it for too long. You need to get a new or a fresh perspective – a new view on things, usually from someone else who hasn’t been working on the same thing you have.
Anne wants to get a fresh perspective on her medical records and her patient history. Your “patient (patient) history” is a detailed record of everything that the doctor has done for you – all of the tests he has performed on you, all of the drugs that he has given you, and so forth. That would be your “patient history.”
Greg then asks, “What are you hoping he’ll find?” Anne says, “The best-case scenario is that he’ll find that my doctor was wrong and that I don’t really have this condition.” A “scenario” (scenario) is a situation or an outcome, a result. “Best-case (case)” refers to the best possible situation. So, a “best-case scenario” is the best possible thing that could happen. If you apply for a job, the best-case scenario is that they give you the job, and they give you a new house and a new car. Well, that probably won’t happen, but that would probably be the best-case scenario – the best possible thing that could happen. The opposite of a best-case scenario is a worst-case scenario – a “worst- (worst) case scenario.”
Anne hopes that the second specialist will tell her that she doesn’t have this disease or this problem at all. Greg says, “If he tells you that, wouldn’t you be dubious?” “To be dubious” (dubious) means to be doubtful – not to believe or not to trust someone or something. Greg says, “You’ll have one doctor telling you that you have it, and one telling you that you don’t.” Anne says, quite logically, “Then it would be time for a third opinion.” It would be time for her to see a third doctor, a third specialist, which I think is actually a good idea.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Greg: Where are you going?
Anne: I’m going to see another doctor to get a second opinion. My doctor diagnosed me with a serious medical condition, and I don’t want to take it at face value.
Greg: You’re second-guessing your doctor?
Anne: No, I just want to make sure he’s right. He’s also recommending a conservative treatment for this condition, and if I really have it, I want to be more aggressive.
Greg: Doesn’t your doctor mind that you’re getting a second opinion?
Anne: No, he even gave me a recommendation for another specialist.
Greg: What’s all of that?
Anne: This is a complete set of my records along with my test results. I’m hoping he’ll have a fresh perspective when he looks at all of it and my patient history.
Greg: What are you hoping he’ll find?
Anne: The best-case scenario is that he’ll find that my doctor was wrong and that I don’t really have this condition.
Greg: If he tells you that, wouldn’t you be dubious? You’ll have one doctor telling you that you have it, and one telling you that you don’t.
Anne: Then it would be time for a third opinion.
[end of dialogue]
She brings a fresh perspective to learning English on the Internet. I refer to our wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
second opinion – a conclusion or recommendation reached by another person after one has already received a conclusion or recommendation from someone else, when everyone is reviewing the same information
* Whenever a doctor recommends a risky surgery, it’s a good idea to get a second opinion to find out whether you really need it.
to diagnose – to identify a problem; to identify someone’s medical condition
* How old was your mother when she was diagnosed with breast cancer?
medical condition – a disease or illness that affects one’s health, abilities, and/or lifestyle
* What would you do if you found out your unborn child had a serious medical condition?
to take (something) – to accept something passively, without questioning it or fighting against it, especially talking about something that is negative or unpleasant
* The manager started yelling at employees a few months ago, and over time it has worsened until finally we just couldn’t take it anymore.
at face value – as something appears on the surface, without digging deeper or trying to find more information or make a more detailed assessment
* At face value, the merger appears to be very profitable, but the company still needs to perform more financial analyses.
to second-guess – to question someone’s opinion or belief, especially in a disrespectful way
* I don’t mean to second-guess you, but have you considered the impact of your decision to quit your job and to move to Hawaii to surf?
conservative – trying only those things that have been tested in the past and are proven to work well, not trying anything new or risky
* It’s fine for the COO to have a conservative approach to the business’s day-to-day operations, but the CEO needs to be more visionary and willing to take risks.
treatment – the medications and therapy that are intended to help a patient improve
* What treatment options are available for severe headache sufferers?
aggressive – doing things forcefully to get what one wants, not waiting or things to happen on their own
* We never realized how aggressive blackberry plants could be until they started taking over our garden!
specialist – a professional who focuses in a particular area of a larger field, usually having obtained a lot of education and special skills in that area
* Jenna was advised to find a specialist in high-risk pregnancies.
records – written information about one person or organization, especially documenting changes over time
* For tax purposes, please keep your records for seven years.
test result – the outcome of an exam or analysis, especially when talking about a blood test or a urine analysis for medical purposes
* Doctor, when do you expect to have my test results back from the laboratory?
fresh perspective – a new opinion on something from someone who has not been involved in the issue previously and is not being influenced by others
* As our managers and executives get older, we need to keep hiring young people to get fresh perspectives on our products.
patient history – a detailed written record of all interactions between a person and his or her doctor, including descriptions of the individual’s health
* According to the patient history, you haven’t come to see Dr. Vanderbush for the past three years. Is that correct?
best-case scenario – the most optimistic outcome; the most positive thing that could happen of all the things one is imagining or anticipating
* The business is failing. Even in the best-case scenario, it’s going to be a struggle to pay all the employees next month.
dubious – doubtful; not believing or trusting someone or something
* Krzysztof told the police that he had been at his grandmother’s house that evening, but the police officers were dubious.
Comprehension Questions
1. Why doesn’t Anne want to take the doctor’s diagnosis at face value?
a) Because she doesn’t like to have face-to-face interactions with her doctor.
b) Because she thinks she should learn more and do more research.
c) Because she thinks her doctor charged her too much for the office visit.
2. What would be included in Anne’s test results?
a) Grades from her college exams.
b) A psychological profile of her personality type.
c) The results of blood and urine analyses.
Answers at bottom.
What Else Does It Mean?
conservative
The word “conservative,” in this podcast, means trying only those things that have been tested in the past and are proven to work well, not trying anything new or risky: “When conservative treatments failed, Meghan signed up for some experimental drug trials to see if new medicines might stop the cancer from spreading.” The word “conservative” also means disliking change and new ways of doing things: “This school uses a conservative approach to education.” The word “conservative” can also mean traditional or old-fashioned: “Bank employees are expected to wear conservative clothing.” Or, “Would you say you grew up in a family with conservative values?” Finally, the phrase “a conservative guess” means an estimate of the value of something where one purposely states a smaller-than-actual amount: “Even conservative projections indicate that the sea level will rise by a few inches.”
records
In this podcast, the word “records” means written information about one person or organization, especially documenting changes over time: “Are students allowed to view the records that the school is keeping about them?” The word “record” also means the best or worst, the longest or shortest, or some other extreme of the level that has been achieved: “Hannah ran the marathon in 3:48, a personal record.” Or, “Who holds the world record for the long jump?” When talking about music, a “record” is a flat, round piece of plastic that has raised circular lines that can produce sound in a record player: “Do you prefer to listen to records or CDs?” Finally, the phrase “for the record” provides emphasis and means that another person should remember what one was saying: “Yes, I was arrested, but for the police never charged me with a crime.”
Culture Note
Remote Second Opinions
As the costs of healthcare “rise” (increase), many people who have received a diagnosis of a serious medical condition are “seeking” (looking for; trying to get) a second opinion without visiting another doctor. “Remote” (from a distance; not face-to-face) second opinions allow people to “submit” (send in) their medical records and test results online, so that a medical specialist can review them and provide a second opinion.
The major advantages of a second opinion are that it is inexpensive and usually much faster than scheduling a face-to-face appointment with a busy specialist. However, health insurance usually “covers” (pays for) a face-to-face appointment, but usually does not cover a remote second opinion.
Another advantage of a remote second opinion is that it could allow the patient to receive the opinion of an international expert on any particular condition, even when that specialist lives and works far from the patient.
The biggest “drawback” (disadvantage) of a remote second opinion is that the patient does not meet with the specialist. This makes it difficult or impossible to know exactly who is reviewing the medical records.
There are also concerns about the “confidentiality” (privacy; a guarantee that secret information is not shared) of health records. If they are sent to an unreliable provider of remote second opinions, personal information could be “made public” (shared with other people).
Comprehension Answers
1 - b
2 - c