= 0934
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 934 – Watching Special Effects.
This is English as a Second Language Podcast episode 934. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member of ESL Podcast and download the very useful Learning Guide that comes with this episode.
This episode is a dialogue between Jack and Chrissy about watching a movie with special effects. Let’s get started.
[start of dialogue]
Chrissy: Wow, that movie was amazing, but I can’t believe that they blew up the Eiffel Tower. I bet the French are really pissed.
Jack: You’re kidding, right? They didn’t really blow up the Eiffel Tower. They used special effects to make it look that way.
Chrissy: Are you sure? It really looked like the real thing.
Jack: They used a scale model or a computer-generated image of the Eiffel Tower and added some pyrotechnics or other visual effects to create what you saw on the screen. It’s like a big optical illusion. I can’t believe you really thought they blew up the Eiffel Tower.
Chrissy: Oh no, I didn’t. I was just kidding. But you have to admit that it was pretty cool that they got the real president of the United States to kill that monster, right?
Jack: You must be messing with my mind again. That wasn’t the president. That was an actor wearing prosthetics and makeup standing in front of a green screen. They added the monster later in post-production.
Chrissy: Oh, right, sure. But you have to hand it to them for moving a section of the Great Wall of China to New York City, right?
Jack: Oh, boy . . .
[end of dialogue]
Our dialogue begins with Chrissy saying, “Wow, that movie was amazing, but I can't believe that they blew up the Eiffel Tower. I bet the French are really pissed.” “To blow up” something is to destroy it, to make it explode. “Blow up” is a two-word phrasal verb, of course. It's used here to indicate that something was destroyed, usually with a bomb or some sort of explosive. Chrissy is saying that in the movie, they blew up the Eiffel Tower.
The Eiffel Tower is the most famous monument of Paris – the most famous site in Paris. That's why Chrissy says, “I bet the French are really pissed.” “To be pissed” (pissed) is something of a vulgar term, which we don't normally talk about on the episodes here. But it's here in our dialogue, so I'll explain that it means to be angry – to be very, very angry or upset. However, it's not a word you should use normally, especially in front of your boss or in front of your family. A much better expression here would be “angry” or “upset,” which is what this word means.
Jack says, “You're kidding, right?” meaning “You're joking, right?” He says, “They didn't really blow up the Eiffel Tower. They used special effects to make it look that way.” “Special effects” are techniques that are used in television and movie production. You think something is happening, even though in reality it isn't. In this case, it looks like the Eiffel Tower is being destroyed in the movie, but Jack says no, that did not actually happen; they used special effects.
He says they use special effects to "make it look that way.” He means they use special effects so that it appears as though the Eiffel Tower were destroyed. Chrissy says, “Are you sure? It really looked like the real thing.” Immediately, we get the sense that Chrissy might not be the most intelligent person in this conversation. Jack says, “They used a scale model or a computer-generated image of the Eiffel Tower and added some pyrotechnics or other visual effects to create what you saw on the screen.”
There are several somewhat difficult terms in that sentence. Let's go back to the beginning where Jack says, “They used a scale (scale) model (model).” A “scale model” would be a small representation of an object, but it's not the real object. If you go to Paris, you can probably buy a little Eiffel Tower that's maybe three inches tall. It's not the actual Eiffel Tower. It's what you might call a scale model. It looks exactly the same, but it is made to be a very small size. That's what Jack is saying they used in this movie.
“Or,” he says, “they used a computer-generated image.” A “computer-generated image” would be something that you would create using software on your computer. Jack says also that they added “some pyrotechnics or other visual effects.” “Pyrotechnics” (pyrotechnics) means fireworks – explosions that produce bright lights and colors and, typically, fire. That's “pyrotechnics.”
Jack says, “They may have used pyrotechnics or visual effects.” “Visual effects” are just special effects that are not sound, but something that you see. “Visual” (visual) refers to that which you can see, or something that can be seen. Jack continues, “It's like a big optical illusion.” An “illusion” (illusion) is something that looks real but it isn’t. An “optical (optical) illusion” is something that makes your eyes think something is going on when it isn't really going on. It looks like it's one thing, but it in fact is another thing. That would be an “optical illusion.”
Jack says, “I can't believe you really thought they blew up the Eiffel Tower.” Jack can't believe that Chrissy could be that stupid. But Chrissy says, “Oh no, I didn't. I was just kidding.” Now Chrissy says that she wasn't serious, that she knew that they didn't really blow up the Eiffel Tower – right. When we use that word “right” with the intonation that I just used, you’re really saying “I don't believe you. I don't think that's true.”
Chrissy says, “You have to admit that it was pretty cool that they got the real president of the United States to kill that monster, right?” So now Chrissy says something else incredibly stupid. She says that the real president of the United States killed the monster in the movie. A “monster” (monster) is a large, ugly, imaginary creature, an animal that doesn't really exist but that you are very scared of. If you remember the movie Frankenstein, Frankenstein was what we would call a monster – kind of like my neighbor.
Jack says, “You must be messing with my mind again.” Jack is saying to Chrissy that she is “messing” with his mind. “To mess” (mess) with someone's mind means to try to trick another person, try to fool another person, try to get someone to believe something is true that really isn't true. It's somewhat of an informal expression. “To mess with” in general means to interfere with or to cause problems with. It could be used in a physical sense. “To mess with” someone would be perhaps to fight them, to hit them.
There's an old expression: “Don't mess with Texas.” “Don't mess with Texas” means don't get into a fight or criticize or anger anyone from the state of Texas. The state of Texas, which is located in the south-central part of the United States on the border with Mexico, has a reputation of being a state that has a lot of pride, where everything is bigger – at least, that's what they think in Texas. But we’re not dealing with Texas here. We’re dealing with Chrissy.
Jack says, “That wasn't the president. That was an actor wearing prosthetics and makeup standing in front of a green screen.” “Prosthetics” (prosthetics) are artificial body parts used sometimes for people who lose their arms or lose one of their legs. Here, it's something that an actor would put on to make him look different. “Makeup” is something you would put typically on your face to make you look different. Women put makeup on to make them look more beautiful.
A “green screen” is a wall that is green. A “green screen” is used in movie and television production in order to put a different background behind the person – but that is done after you actually make the film, after you actually film the video. You then can go back, if the background is green, and change what is behind the person so that it looks like something different.
Jack says, “They added the monster later in post-production.” “Post-production” is the final stages, the final steps in making a movie or a television show or a record or a podcast. “Post-production” is what happens after you do the recording. It's all of the things that happen to get the recording – whether it's audio or visual – ready to release, ready to publish.
Chrissy says, “Oh, right, sure, but you have to hand it to them for moving a section of the Great Wall of China to New York City, right?” The expression “to hand (hand) it to” someone means to compliment them, to say that they did something very well. Chrissy is saying that in the movie, they took a section of the Great Wall of China and moved it to New York City. That's what Chrissy thinks. That's why she says, “You have to hand it to them.” You have to congratulate the people who made the movie for doing such an amazing thing.
Of course, that's not actually what happened, but that's what Chrissy thinks. That's why Jack ends our dialogue by saying, “Oh, boy.” That expression, “Oh, boy” is when you are frustrated, or you can't believe how stupid the other person is, or you can't believe the crazy ideas that the other person has. Chrissy certainly has some crazy ideas.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Chrissy: Wow, that movie was amazing, but I can’t believe that they blew up the Eiffel Tower. I bet the French are really pissed.
Jack: You’re kidding, right? They didn’t really blow up the Eiffel Tower. They used special effects to make it look that way.
Chrissy: Are you sure? It really looked like the real thing.
Jack: They used a scale model or a computer-generated image of the Eiffel Tower and added some pyrotechnics or other visual effects to create what you saw on the screen. It’s like a big optical illusion. I can’t believe you really thought they blew up the Eiffel Tower.
Chrissy: Oh no, I didn’t. I was just kidding. But you have to admit that it was pretty cool that they got the real president of the United States to kill that monster, right?
Jack: You must be messing with my mind again. That wasn’t the president. That was an actor wearing prosthetics and makeup standing in front of a green screen. They added the monster later in post-production.
Chrissy: Oh, right, sure. But you have to hand it to them for moving a section of the Great Wall of China to New York City, right?
Jack: Oh, boy . . .
[end of dialogue]
We hope that our scriptwriter never messes with our minds. I don't think she would. I speak, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to blow up – to make something explode; to use an explosion to destroy something
* Smokers aren’t allowed near the tent where fireworks explode, because they might accidentally blow up everything.
pissed – very angry, mad, or upset
* Karla’s Dad was pissed when he found out that she had taken his car without his permission.
special effect – a technique used to make something appear to have happened when it actually did not, especially in movies and on stage
* Those aliens looked so real! What great special effects!
scale model – a three-dimensional copy or representation of an object, but smaller than the actual object; a much smaller version of what something will look like when completed, especially a building
* The architectural firms each brought a scale model of their proposed design for the city council to review and evaluate.
computer-generated – created by a computer, not drawn or made by hand
* Can a computer-generated drawing be considered artwork?
image – picture; a drawing, graphic, or representation of something on paper or in one’s mind
* Let’s design a new logo that incorporates an image of a tree.
pyrotechnics – fireworks; explosions that produce bright lights and colors and/or fire
* Action films use a lot of pyrotechnics to make car chase scenes more exciting.
visual effects – images created with the help of computers and other devices, without actually filming the event that is being portrayed (shown)
* The film used impressive visual effects to make it look like the astronauts were floating in outer space.
optical illusion – something that tricks one’s eyes and makes one believe something that is not true; something that appears differently than it actually is
* In this optical illusion, one line appears to be longer than the other, but if you measure them you can see that they are actually the same length.
monster – a large, scary, and ugly imaginary creature
* When Kazuo was a little boy, he slept with the lights on because he believed there were monsters under the bed.
to mess with (one’s) mind – to try to trick another person; to try to make another person believe something that is not true
* Pedrito believed everything we told him, but we were just messing with his mind. None of it was true.
prosthetic – an artificial body part, used to change an actor’s appearance or to help someone function normally
* Beatriz lost her hand in a factory accident, and now she’s learning how to use a prosthetic.
makeup – colored substances placed on the face to change one’s appearance, especially to make a woman appear more beautiful
* Lililana prefers to wear simple makeup: some foundation, mascara, and lipstick.
green screen – a colored wall that actors stand in front of so that their movements can be recorded and then shown over a different background
* The weather reporter on the news appear to be standing in front of a map of the country, but they’re really standing in front of a green screen.
post-production – the final stages in making a TV show or a movie, after the actors have been filmed
* Post-production involves a lot of video editing and adding music to the film.
to hand it to (someone) – to compliment someone; to say that someone has done something well; to admire how well someone has done something
* Many of the students at this school have gone to very good colleges over the past five years. You have to hand it to the principal and the teachers.
Comprehension Questions
1. Which of these might be used for an explosion?
a) Pyrotechnics.
b) Prosthetics.
c) Makeup.
2. What does Chrissy mean when she says, “you have to hand it to them”?
a) She thinks they deserve to win an award.
b) She is very impressed by what they’ve done.
c) She thinks they should be paid a lot of money.
Answers at bottom.
What Else Does It Mean?
to blow up
The phrase “to blow up,” in this podcast, means to make something explode, or to use an explosion to destroy something: “Why did the military blow up the hospital?” The phrase “to blow up” also means to fill something with air: “Can you please help me blow up these balloons for the birthday party?” The phrase “to blow” is used informally to mean that something is disappointing, uninteresting, and not good: “This party blows. Let’s go somewhere else instead.” Finally, the phrase “to blow over” means for an argument or a heated discussion to be forgotten and become less important: “Right now everyone’s upset about what happened, but in a few weeks this will all blow over and nobody will even remember it.”
to mess with (one’s) mind
In this podcast, the phrase “to mess with (one’s) mind” means to try to trick another person, or to try to make another person believe something that is not true: “Those job interviewers will try to mess with your mind, but be confident and don’t let them confuse you.” The phrase “to mess with (one’s) mind” can also mean to damage one’s brain: “Randall took illegal drugs as a teenager and they really messed with his mind.” The phrase “to mess up” means to make a mistake: “I’m sorry, I messed up, but would you give me another chance?” Finally, the phrase “to mess around” means to goof around or to do silly things: “Are you busy, or are you just messing around?”
Culture Note
Landmarks in Special Effects
The history of American filmmaking is “marked” (characterized) by many “landmarks” (very impressive things that others refer to as major achievements) in special effects. For example, the 1956 film The Ten Commandments used “impressive” (getting admiration from many people) special effects to “multiply” (make bigger in number) “crowds” (large groups of people), making it seem like there were more actors than there actually were. The film was also noted for the special effects used when Moses “parted” (separated; put into two pieces) the Red Sea.
Special effects are especially “prominent” (noticeable) in science fiction films. For example, Stanley Kubrick’s 1968 film, 2001: A Space Odyssey “established” (created) a new “benchmark” (a standard for measuring things; an expectation of quality) for special effects in films. The filmmakers used very detailed model “spaceships” (vehicles for going into space) for filming. And they made careful use of “wires” (thin cables) and mirrors to “portray” (show) a “zero-gravity environment” (where there is no gravity, so people and things float in the air). George Lucas’s Star Wars “trilogy” (a group of three movies in a series) also used many impressive special effects.
In recent years, “computer-generated imagery,” or “CGI,” has helped to advance special effects. With CGI, filmmakers no longer need to create “physical” (real; able to be touched) models for filming. Instead, they can create “digital” (electronic) images and combine them with live actors in unusual ways, as “illustrated” (shown) in movies like Jurassic Park, where human actors interacted with digital “dinosaurs” (large animals that lived on Earth many, many years ago) “on screen” (in a movie). Movies like Toy Story have continued to “blur the line” (make unclear the distinction) between live action films and CGI films.
Comprehension Answers
1 - a
2 - b