= 1884
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 579.
This is English as a Second Language Podcast’s English Café number 579. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Take a look at our website. Go to ESLPod.com. We have an ESL Podcast Store with additional courses in business, daily, and cultural English.
On this Café, we’re going to talk about one of the most interesting science fiction writers of the twentieth century, an author by the name of Philip K. Dick. And as always, we’ll answer a few of your questions. Let’s get started.
Philip Kindred Dick and his twin sister were born in December of 1928 in Chicago, Illinois. Philip Dick’s middle name of “Kindred” is rather unusual, but then again, so were the career and works of Philip K. Dick. “Kindred” as an adjective means “similar to,” and as a noun is a word meaning your family, although it’s not used very much in that sense anymore. In any case, although you may have never heard of Philip K. Dick as a writer, you almost certainly have heard of some of the movies that were based on his writing.
Dick and his twin sister, as I mentioned, were born in 1928. However, the sister died when she was very young, surviving only a few weeks. This loss of his sister affected Dick’s work later in his life. He would often talk about the missing twin that he had. Philip K. Dick moved around quite a bit in his early life. His parents moved first to San Francisco and then divorced, or ended their marriage.
The mother and Philip moved to Washington, D.C., and then back to California when Philip was 10 years old. He grew up near Berkeley, California. Berkeley is the home of the University of California, Berkeley, one of the best universities in the United States. Berkeley was then, and is still, a community known for its more alternative lifestyles. It has always been a place of intellectual, and in some ways artistic, creativity, especially for those who are interested in literature and writing.
Young Philip got interested in writing science fiction at a young age. “Science fiction” refers to stories about how people and society will be affected in the future by technological or scientific developments. Philip went to Berkeley High School and later, for one year, went to the University of California, Berkeley. He didn’t last very long in college and decided to become a full-time writer. He continued writing science fiction and in 1952 published his first story, called “Beyond Lies the Wub” (Wub) – a made-up word.
The story involves an alien – a creature, a living being, from another planet – called a “Wub,” who looks like a big pig. Of course, this is science fiction, so there are all sorts of strange things that happen. It was the first of many science fiction stories that Philip wrote. In 1955, he published his first novel. It was called Solar Lottery, and it told a story of a world where the positions of power, such as president or prime minister, were given to people based on a “lottery.”
A “lottery” (lottery) is a system where someone is chosen at random. Often it is done by putting a bunch of little balls with numbers on them into a bowl and then picking one of those numbers out of the bowl. Lotteries are used in many countries, including in the United States, to give away money. You buy a ticket with a certain set of numbers on it, and if your numbers are chosen, you win a lot of money.
The story in my family is that my first name was chosen at random from a bunch of names written on a piece of paper and put into a hat. Because I was the 11th child, my parents, well, they ran out of names. They didn’t have any names they wanted to use since I had already 10 older siblings, and so “Jeffrey” was selected as my name, sort of by lottery – but I’m not sure if that story is true. You know how parents sometimes tell their children stories that aren’t always 100 percent accurate.
Anyway, Philip K. Dick’s story was about a lottery, a “solar (solar) lottery.” “Solar” refers to something involving the sun. I haven’t read the story so I’m not sure why it was called a “solar lottery.” In any case, Dick was what we would describe as a “prolific writer.” “Prolific” (prolific) describes a writer, artist, or someone who creates things, who produces a lot of artistic works – in this case, a lot of stories and novels. Some people say he wrote a story or a book almost every two weeks. Imagine.
His most successful stories, however, were written in the early to mid-1960s. Many of these stories were later turned into movies or television shows that you probably recognize. Let’s start with his 1962 book, The Man in the High Castle. This was made into a television show very recently, in 2015. It was a story of what we might call an “alternate universe.” An “alternate (alternate) universe (universe)” is an imaginary world where something changes in history and the world develops in a different way than it actually did.
An “alternate universe” could simply be a world like ours, but with certain things that have been changed. There are many science fiction stories that are based on this idea of an alternate universe. In The Man in the High Castle, the alternate universe was what the world would look like if Nazi Germany under Adolf Hitler had won World War II, and Japan had won as well. It, of course, is a very different world than the one we know.
Perhaps his most famous story that became a movie is Do Androids Dream of Electric Sheep? This was made into a famous movie in 1982, starring Harrison Ford, called Blade Runner. An “android” (android) nowadays refers to a kind of phone or operating system for a phone, but the original meaning was a robot or machine that acted like a human being. One of my favorite science fiction television series, Star Trek: The Next Generation, has an android called “Data.”
Well, in Philip K. Dick’s novel, androids were created to basically be slaves of human beings, and in the movie, Harrison Ford is sent to kill a particular android. The entire movie takes place here in Los Angeles. I think my neighbor might be an android. I’m not sure. He looks a little strange, “and he talks like this.” I’m not sure if he is an android.
I should explain the title of the story that Blade Runner was based on, Do Androids Dream of Electric Sheep?” (sheep). One of the things that people say you should do to help you fall asleep, if you have difficulty, is to count sheep – one sheep, two, three, four five – in your head, and eventually I guess you’ll get so bored of counting sheep that you will fall asleep. That’s the meaning of that title “Do Androids Dream of Electric Sheep?”
Other books by Philip K. Dick that were turned into films include “We Can Remember It for You Wholesale.” This became a very popular movie, released in 1990, called Total Recall, which was a big hit around the world. It starred the now former governor of California, Arnold Schwarzenegger. Another story by Philip K. Dick was The Minority Report, which became a movie of the same name in 2002, starring Tom Cruise.
I should explain also that “wholesale” in the title We Can Remember It for You Wholesale, is an unusual word. “Wholesale” (wholesale) normally describes something that is sold in large amounts to someone else who is going to sell that same product. So if you are a store that sells clothing, you would go to another place that sells clothing “wholesale,” and you would buy a whole bunch of pants and shirts and bring them to your store where you would sell them individually to people. We would call that “retail” (retail). So, “wholesale” is when you buy a lot of things to sell typically to other people, and when you sell them to other people individually, that would be called “retail sales.”
Philip K. Dick was interested very early on in his career – and as a young student, in fact – in certain aspects of philosophy, especially in the question of whether the world really exists and how do we know that the world exists. Many of his stories focus on what is real and how we know what is real. This theme becomes even more prominent, more noticeable, in his later books – those written after, say, 1974.
It was that year that he says that he was visited by some kind of supernatural being, some sort of god. He wasn’t sure if he had been visited or if he was simply suffering from some kind of mental illness, some serious condition of his mind. Many people think that he suffered from mental illness during much of his life and this caused him to question what was real and what was not real.
Among other problems he had, he became addicted to drugs. “To be addicted” (addicted) means that you are dependent on, or you require, some kind of other stimulus – in this case, drugs – to keep you going. You need it. You can’t do without it, and the rest of your life is affected by it. People can be addicted to all sorts of behaviors as well as chemical substances. In this case, he was addicted to drugs and spent a lot of the money he made from his stories buying drugs.
It also no doubt caused problems in his personal relationships. He was married no less than five times. Most of the marriages fairly short-lived. I think his longest marriage was nine years during the 1950s. You might say he was prolific as a husband as well as a writer. As a writer, he eventually wrote 44 novels and 121 short stories. Imagine. That’s a lot of writing.
Of course, not all of his novels and stories were of the best quality, but some of them have been judged to be quite good indeed by later writers and readers. His story The Man in the High Castle won a Hugo Award, given to the best science fiction story, back in 1963. Many of his stories continue to be used, and will be used in the future, for ideas for movies and TV shows, especially. There are already new adaptations, new versions, of Philip K. Dick stories that are being produced now that you will probably see in the near future.
Philip K. Dick died at a young age. He was only 53 years old. He died apparently of a “stroke” (stroke), which is a brain injury. He died relatively poor. He had lived long enough to sell the rights for his book that became Blade Runner. “Rights” (rights) refer to permissions to use something. There’s no question that Philip K. Dick is more famous now than he ever was when he was writing. His personal papers, his personal documents, were all donated to a university here in Southern California, California State University, Fullerton.
When I say “donated,” I mean they were given to the university to keep. That sometimes happens with famous people who have a collection of their own writings and papers. They are given to a library so that people who want to do research on that person can go and look at them. Interestingly enough, I worked at that university – California State University, Fullerton – for a number of years and was in the library where his papers are kept, although I never went to look at them. Maybe I should have. I might have gotten some good ideas.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Alex (Alex) in Ukraine. Alex wants to know the meaning of three phrases or words: “on purpose,” “deliberately,” and “intentionally.” All three of these are closely related. Let’s start with the first one, “on purpose” (purpose). To do something “on purpose” means to do it because you planned on doing it. You wanted to do it. It was the way that you intended to do it.
Usually we use this phrase when we are talking about something bad that a person does. If someone hits you and then says, “Oh, I’m sorry. That was an accident. I didn’t mean to do that. That wasn’t my intention,” you might think otherwise. You might think, “No, you did that on purpose. You wanted to do that.” So, “on purpose” is used normally to describe an action that someone does that has some negative consequence – that is, bad in its effect.
“Deliberately” (deliberately) can also mean the same as “on purpose.” It can mean something done in a planned or intended way. It could be a good thing or a bad thing. It’s used in either sense. However, “deliberately” has another meaning which means slowly and carefully, something that is done not just on purpose, but in a way that is very careful, very planned – very slowly, often, so that it is done correctly.
“Intentionally” (intentionally) means the same as “on purpose” and “deliberately” in the sense of in a planned and intended way. I did something “intentionally.” “Intentionally,” like “deliberately,” can mean something done that had a positive or negative impact. I would say, however, that it is probably used more in cases of a negative consequence. “He intentionally hit me.” The opposite, as I mentioned previously, of “intentionally” or “on purpose” is “accidentally” – that is, it wasn’t the person’s intention. They didn’t want to do it. It just happened by mistake.
Our next question comes from Jnanesh (Jnanesh), living in the United Kingdom. The question has to do with two words, “moderate,” or “moderately,” and “sparingly.”
“Moderately” (moderately) can mean a couple of different things. One is something that is done not in an extreme way – to a medium of degree, we might say. The word “moderate” is related to being in the middle. In politics, we talk about people who are on the left or the right, liberal or conservative, and in the middle, between those two groups, you have “moderates” – people who don’t take the position of either side or are somewhere in the middle in terms of their political positions.
Well, the adverb “moderately” refers to something that is not done in any extreme: not high, not low, not a lot, not a little – somewhere in the middle. If you say you are “moderately satisfied” or “moderately happy” with something, you’re not really happy – you’re not very happy – but you’re not very disappointed either. It’s somewhere in between. As an adjective, “moderate” can describe something that isn’t very expensive. It’s not cheap. It isn’t a low price. It’s somewhere in between.
“Sparingly” (sparingly) means “not very much” – something that is not used very often or is not used very frequently. “My boss gives me praise” – says nice things about me – “but he does it very sparingly.” He doesn’t do it very often. It is not very frequent that it happens. You could be cooking something and the “recipe,” the set of instructions of what you should do, may say something like “Use salt sparingly.” That means use only a little bit, not very much. If we wanted to compare these two words, “moderately” would be more than “sparingly.”
Now, you might ask, “Well what about the opposite of ‘sparingly?’ What if you want to use something a lot?” Then we would probably use the adjective “liberally” (liberally). “Liberally” would be the opposite of “sparingly.” Notice that the word “liberally” here is not a political term. We’re not talking about “liberally” versus “conservatively,” although you could actually say “conservatively” instead of “sparingly” in certain circumstances, but it’s not related to who you are going to vote for for president.
Finally, Pavithra (Pavithra) from India wants to know the meaning of the phrase “understatement of the century.” Well, to understand this phrase, we need to understand the word “understatement” and “overstatement.” An “understatement” (understatement) is when you say something that makes the reality or the situation seem less important than it really is, or makes the impact seem smaller than it really is.
For example, if you go to what we would call here in America a “soccer game” – what the rest of the world calls a “football game” – and the score at the end of the game is 10 to nothing, 10-0, it would be an understatement to say, “Well the team that lost, lost by only a little bit.” Well, of course they didn’t lose by just a small amount. They lost by 10 goals, which is a lot in soccer, in football. That’s an example of an understatement – where you say something that minimizes or makes it seem less important or smaller than it really is.
The opposite of an “understatement” is, of course, an “overstatement” – where someone makes something more important than it really seems. If I say, “Harrison Ford was the greatest actor of the twentieth century,” that’s probably an overstatement. He was good. He’s a very good actor, maybe a great actor, but probably not the greatest actor of the twentieth century.
The second part of this statement is “of the century” (century). I just used the word “century” in my example. It means, of course, 100 years. So between the years 1900 and 1999 would be the twentieth century. So, if you say something is “the best of the century,” you mean it’s the best of a hundred years.
We put these things together, then, and we get “the understatement of the century,” which would be someone saying something that was really, really an understatement. If I say, “Bill Gates has enough money to buy a new house here in Los Angeles,” that would be an understatement – perhaps “the understatement of the century,” since he has enough money to buy hundreds if not thousands of houses. That’s an example of that expression.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
alien – an imaginary (not real) creature from another planet; a being from outer space
* Jacob believes that aliens have already arrived on Earth and are watching us.
science fiction – stories about how people and societies are affected by imaginary scientific developments in the future
* Star Wars is a science fiction story about people and beings from other planets fighting a war in outer space against an evil power.
lottery – a process or game in which the outcome is random and controlled by chance or luck, not skill
* He played the lottery every Friday with the hopes that he will win enough to quit his job.
solar – relating to or determined by the sun
* Our swimming pool is heated using solar energy.
prolific – a writer, artist, or composer (writer of music) who produces a large number of works or creations
* Beethoven was a prolific composer completing five symphonies and 32 piano sonatas.
alternate universe – an imaginary (not real) world that exists at the same time as the current one, but which has developed differently
* In an alternate universe, animals could be the masters and people their pets.
android – a robot or machine that looks and acts like a human being
* Do you think we will ever be able to replace workers doing basic jobs with androids?
wholesale – sold in large amounts, often with the intention of the items then being sold to individual customers
* Where can we buy soil and plants wholesale to landscape the school grounds?
mental illness – a serious condition of the mind that affects how a person thinks, feels, and behaves
* Vincent Van Gogh suffered from a mental illness and expressed what he saw and how he felt in his paintings.
to be addicted – for one’s body to need more and more of a substance in order to feel good or normal and not being able to function normally without it
* People addicted to pain medications often need professional help to reduce their dependency.
rights – official permission to use someone’s ideas for another purpose or project
* That singer didn’t get the rights to use the band’s music in her own songs, and is now being sued.
on purpose – in a planned or intended way; in a deliberate way
* Ouch! You stepped on my foot on purpose.
deliberately – in a planned or intended way; on purpose; slowly and carefully; in a way that is not hurried
* Jon deliberately allowed Sara to think that he wasn’t going to attend her party so he could surprise her.
intentionally – in a planned way; on purpose
* Even though the player intentionally hit another player, the referee ignored it.
moderately – not completely or in an extreme way; to a medium degree or extent; in a way that is not too expensive
* Our fundraising has been moderately successful, but if we want to reach our goal, we’ll have to find more donors.
sparingly – not using or giving a lot of something; using something only a little and/or not often
* Maki likes whole milk in her coffee, but since she’s trying to lose weight, she only adds it sparingly.
understatement of the century – a phrase used when one thinks that something said was not strong, big, important, etc., enough and does not fully express the truth
* You said you had a small piece of good news, but that was the understatement of the century! Being admitted to the best university in the country is big news.
What Insiders Know
Popular Sub-genres of Science Fiction
“Science fiction” is a “wide-ranging” (including many types) “genre” (a category of literature or other artistic work) about “imagined” (not real; created in one’s mind) futures involving new technology and scientific discoveries. One of the most popular “sub-genres” (a smaller category under the bigger category of “science fiction”) is “apocalyptic fiction,” which considers what would happen at the “end of civilization” (when society stops functioning as it does now), usually as a result of war or a “pandemic” (a disease that affects many people).
“Space opera” is a different sub-genre in which there are very strong characters fighting against each other in outer space, with a clear “hero” (the good person in a story whom everyone wants to see win) and a “villain” (the bad person in a story whom everyone wants to see lose). For example, the Star Wars “trilogy” (a group of three related movies or books) is a space opera.
A “space Western” combines science fiction with the ideas found in the “American West,” or the cowboys and other settlers who had “adventures” (exciting experiences) in the western part of North America as the United States was “expanding” (getting bigger). Space Westerns consider what would happen if humans began to “colonize” (start living in a new place and taking the land or planet as one’s own) other planets.
Finally, the “climate fiction” sub-genre imagines what would happen if the Earth’s “climate” (weather patterns) changed “dramatically” (significantly; in a big way), usually becoming much colder or much hotter very quickly. Some of these books are only for entertainment, while others are trying to “raise awareness” (make people think about the importance of something) of “global warming” (the ways in which human activity is changing the climate).