= 1877
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 572.
This is English as a Second Language Podcast’s English Café episode 572. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful – and I do mean beautiful – Los Angeles, California.
Visit ESLPod.com to become a member of this podcast. When you do, you can download our eight- to ten-page Learning Guide that contains a complete transcript of everything we say. Take a look also on our website at our ESL Podcast Store, with special courses in Business English, Daily English, and more.
On this Café, we’re going to talk about a man who changed the history of the United States in many ways by a single invention, Eli Whitney. We’ll also talk about something called the Ziegfeld Follies and why it was important in early twentieth-century entertainment. And as always, we’ll answer a few of your questions. Let’s get started.
One of the most important men in the early history of the United States was not a politician or a general – it was a businessman by the name of Eli Whitney. Whitney was born in December of 1765 in the state of Massachusetts, which is in the northeast part of the United States, an area still known today as New England. His father was a farmer, and Whitney grew up helping on a farm.
He went to one of the best universities at that time – and still today – Yale University, in the state of Connecticut, which is just south of Massachusetts. He studied science and applied arts. The word “applied” (applied) means taking some idea, some theory, and using it for something practical. I, for example, when I was at the university, studied “applied linguistics” – the study of language that is then used to do something practical like teaching English.
After Eli Whitney graduated, or finished his studies at the university, in 1792, he was offered a few teaching positions, but things didn’t go well for Whitney. He moved to the southern United States, to Georgia, but found himself without a job. He decided that he wasn’t going to continue teaching. Fortunately for him, he made friends with a woman named Catherine Greene, who owned a plantation in the state of Georgia.
A “plantation” (plantation) is a large farm that is used to grow things such as coffee, sugar, and tobacco, and typically has a large number of people working there. Plantations usually have crops, or plants that are grown to be eaten or used, that require a lot of “labor” (labor) – that is, a lot of people working. One of the people that Whitney met after he started his acquaintance – his friendship – with Catherine Greene, the owner of this plantation, was the manager, the director of the plantation, Phineas Miller.
During this period in the early part of the nineteenth century, the manufacturing centers in England – the factories that made clothing – had a need for more and more cotton. “Cotton” is a plant that grows in climates such as the American South, in places such as Georgia, which is located in the southeastern part of the United States. However, the southern states, although they did grow cotton and sent some of that cotton to England, didn’t have enough to meet the demand. The English clothing manufacturers wanted more.
So they had to think of a way, the farmers in the South, to produce more of this cotton – which is, as you may know, a soft white material. During this period the American South did have slaves that it had brought in from Africa to use to take the plant, the cotton plant, and remove the parts that weren’t needed in order to produce a usable form of cotton from the plant, but it was very slow work and it didn’t produce a lot of cotton.
Whitney understood that if these plantations could remove the parts of the cotton plant that weren’t needed more efficiently, more quickly, they could produce more cotton and therefore make more money. So, after thinking about it for a long time and experimenting with different methods, eventually Whitney and his friend Phineas Miller developed something called a “cotton gin.” The word “gin” (gin) here is short for “engine” (engine). An “engine” is sometimes called a “motor” in certain applications, such as in a car. Your car’s “engine” is the motor. It is what gives the car power to move.
Well, here the engine, if you will, was the part of the machine that was able to remove the unwanted parts of the cotton plant in order to produce the cotton that was needed. Now, when you have a good idea, the common practice is to go to the government and get what’s called a “patent.” A “patent” (patent) is government recognition and protection of your idea so that no one else steals it. Whitney got a patent for his cotton gin in 1794.
Whitney and Miller started their own business making these cotton gins. They immediately discovered what a lot of people discover when they have a good idea and they try to sell the results of that idea, which was that other people will steal your idea. They’ll take your work and they’ll use it for themselves and not give you any money for it. This is exactly, unhappily, what happened to Eli Whitney and Phineas Miller. Other people took their design. They used it. They made their own machines and they didn’t give them any money.
Whitney and Miller had to close their cotton gin business after only three years because they weren’t making any money. What do you do if someone steals your ideas and tries to sell them as his own? In America, you sue them. “To sue” (sue) means to go to the government – to the court system, to the justice system – and try to get those people to give you money for having stolen your idea.
Whitney wasn’t very successful in these lawsuits, although eventually there were four states in the South – South Carolina, Tennessee, North Carolina, and Georgia – which paid him and Miller money for using their ideas. They essentially paid them for what we would call a “license” (license). A “license” is legal permission to use your idea, usually in exchange for some money. Whitney and Miller did get money for this idea, but they knew it was never going to be the same amount as what they had lost because others had taken their ideas without permission.
In 1799, Whitney decided to turn his attention to another concept, which in many ways was perhaps even more important for the future of the American economy. Remember, he had already in a sense revolutionized the economy of the American South by providing a way of getting cotton more efficiently from cotton plants. This changed the economy in the South for a good hundred years or more.
The next thing that Whitney did was change the economy of the northern states by popularizing a concept that would affect the manufacturing or making of products of goods. In the United States – in the nineteenth century, at least – the southern states, the southeastern states, were mostly agricultural. They were growing things such as cotton. In the northern states, however, especially beginning in the middle part of the nineteenth century, the economy was very much what we would call “industrial.”
Like the Industrial Revolution had affected the economy in England and in Europe, it also affected the economy in the United States, and many of the northern states had large manufacturing centers – places that made things such as steel and other products. Whitney’s contribution to the northern economy was to understand the importance of something called “interchangeable parts.” What do I mean by “interchangeable” (interchangeable)? The concept is so familiar to us today that in some ways we forget about how important it is.
Let’s say you have a computer and you have a problem with one of the keys on the keyboard of your computer. It’s broken. It doesn’t work. Well, you can take that key off, often, and put another key in its place. So, if your “J” key doesn’t work on your keyboard, you can replace it with another “J” – another “part” (part). The parts of your keyboard are “interchangeable.” You don’t need to make a new “J” just for your keyboard, because all of the keyboards of your kind of computer use the same kinds of keys.
The concept of “interchangeable parts” is important because if you want to produce or make a lot of one thing, you’re going to need to make that one thing out of interchangeable parts. The concept, which we call “mass (mass) production,” which is making a lot of one thing, depends on the concept of interchangeable parts. Many Americans associate the idea of mass production with another inventor, Henry Ford, who helped develop the car business, the car industry in the United States.
Ford was famous for his factories – his manufacturing centers that made cars using this process of mass production and interchangeable parts – but it was in fact, at least in the United States, Eli Whitney who was the first to make this concept popular. And he did it in making what some people think is that most American of product: a gun. Yes. During the early part of the nineteenth century, the United States government thought that it was going to go to war with France, and in order to have a war, you need a lot of guns.
Whitney proposed that he could make as many as 10,000 guns by using this process of interchangeable parts. In fact, he even went to the then-president of the United States, Thomas Jefferson, and he demonstrated how you could make a kind of gun called a “musket” very quickly if you made them out of interchangeable parts. Before this time, each gun was made individually, and so if you had a problem with the gun, you had to make a special part just for that gun.
Whitney’s idea allowed the mass production of these guns, and although it took him longer to do it than he at first said it would, he was in fact able to produce guns very quickly when the government needed them, especially before the war with Great Britain in 1812. Whitney married in 1817 and had four children with his wife, Henrietta. His son, Eli Whitney Jr., followed his father into the business of mass production and took over his gun factory after Whitney died in 1825.
If you ask Americans who Eli Whitney was, most of those who remember their history lessons will tell you that he was the inventor of, of course, the cotton gin, but he spent most of his life not working on the making of cotton gins, but rather on mass production and application of the idea of interchangeable parts – especially, in his case, in the manufacture of guns. Although of course that general principle, that general idea, would be applied to all sorts of businesses later in the nineteenth century.
We turn from the economy to entertainment. One of the most popular forms of entertainment before the invention of radio, television, and cinema was something called the “musical revue.” A “revue” (revue) is a performance in a theatre that usually includes several kinds of entertainment, including comedy, songs, acting, and dancing. A “musical revue,” of course, primarily involves singing and dancing. The Ziegfeld Follies was the most famous of these musical revues.
A “folly” (folly) is something you do that is foolish or ridiculous. You may know of a famous work of literature called In Praise of Folly by the sixteenth-century writer Erasmus. It’s actually a very funny piece of literature. The plural of “folly” is “follies,” and in the early twentieth century, the word “follies” was used to describe this particular kind of musical revue, especially one that had mostly or all women in it.
The Ziegfeld Follies was a musical revue that was on Broadway in New York City. Broadway, you may know, is one of the most famous streets in New York, where all the large theaters are located. In 1907, a man by the name of Florenz Ziegfeld created a musical revue for that summer. It was supposed to only last for one summer, and it included, as musical revues typically did, singing, dancing, comedy, and most importantly, beautiful women dancing.
The Ziegfeld Follies were so popular in New York that Ziegfeld decided he would do it again the following year and the year after that. For 30 years, you could go to New York and see the Ziegfeld Follies during the summertime. One of the things that made the Ziegfeld Follies so famous was that it was a very what we might describe as a “lavish production” (lavish). Something that is “lavish” is very expensive looking. It’s something that you can tell cost a lot of money.
Another word for this is “opulent” (opulent). Something that is opulent is rich and expensive and perhaps elegant. You might describe the famous buildings at Versailles, in France, as being opulent. Well, the Ziegfeld Follies were opulent. People went to them and they wanted to see a big show. This is still the same today when people go to a musical on Broadway in New York City. They’re expecting a big production – lots of lights, lots of perhaps dancing and singing, and very expensive clothing worn by the actors and singers.
It was, in other words, what we might call a “spectacle” (spectacle). A spectacle is that kind of show that you remember with lots of expensive costumes and opulent sets. In addition to the actors telling the jokes and performing different parts of the follies, you also had most famously the dancers – and in fact, it was the Ziegfeld dancers that were most famous in terms of what people remembered about these shows. They were considered the most beautiful women in the world.
They were young, they were pretty, and they wore what we would describe as “very revealing” clothing. “Revealing” (revealing) is clothing that reveals or shows a lot of the human body so that when you wear it, you can see a lot that is not covered by the clothing. In this sense, the follies were a bit like music videos today, or perhaps the cheerleaders that you will find at professional American football games. There were lots of pretty girls, not wearing very much, dancing.
Some of the beautiful women that first started with the Ziegfeld Follies went on and became quite famous performers, people such as Barbara Stanwyck, Gypsy Lee Rose, and the great singer Josephine Baker. All of them got their start in the Ziegfeld Follies. The show stopped being performed on Broadway in 1931, although it was produced again for a few years in the mid-1930s. You may wonder why people even today, still know about the Ziegfeld Follies, and the reason is Hollywood. There are at least three famous movies about the Ziegfeld Follies.
The first one was a movie about Florenz Ziegfeld called The Great Ziegfeld. It starred William Powell and the beautiful Myrna Loy. Hollywood made another movie called Ziegfeld Girl, starring again beautiful actresses such as Lana Turner and Judy Garland. Jimmy Stewart was also in that movie. A third movie was made in 1946, called simply Ziegfeld Follies. This one had Judy Garland, the great dancer Fred Astaire, Lena Horne, William Powell, Gene Kelly, Red Skeleton, a famous comedienne, Lucille Ball - these are some of the best-known actors, singers, and comedians of that generation. So, people growing up as I did in the 1960s and ’70s still knew about the Ziegfeld Follies from the movies that were made about these amazing shows. In fact, another famous movie that made Barbara Streisand famous in 1964, a musical called Funny Girl, is about in part an actress from the Ziegfeld Follies.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Kavian (Kavian) in Iran. The question has to do with three expressions or words that Kavian has seen, especially in video games or on the internet. The first one is “ROFL.” “ROFL” is one of the many abbreviations that are used in text messaging and instant messaging nowadays. It stands for “rolling on the floor laughing.” “To be rolling on the floor” means that you are physically on the floor and your body is going around and around over the floor.
Now, you might do that if you were in a lot of pain, but you might also do it if you are laughing so hard that you couldn’t stand up. So, “ROFL” means that it is extremely funny. You are responding to something or saying that a comment was very funny. There are lots of these text abbreviations that are used I’m guessing in many different languages, especially English. The second expression is “straight outta” (outta). The informal word “outta” stands for “out of.” So the complete expression would be, in standard English, “straight out of.”
“Straight out of” means it comes directly from or is directly influenced by a certain thing or place or person. The most well-known use of this phrase is “Straight Outta Compton,” a song by the hip-hop group NWA from the late 1980s. More recently, there was a movie about NWA called Straight Outta Compton. Compton, in case you’re curious, is actually a small city located in the southern part of the Los Angeles metropolitan area, known mostly for being a poor and dangerous part of town.
Our next question comes from Piotr (Piotr) from Poland. The question has to do with two words, “shack” (shack) and “shed” (shed). A “shack” is a small house or building that is not put together very well. It might be made out a very cheap or inexpensive materials and constructed somewhat poorly. A shack is definitely a small, often poor house where someone lives that may not have a lot of money.
A “shed” is a place where you keep tools and other small objects, usually in the backyard of a house or on a farm. When I was growing up, we had a shed in the back of our house. It’s a separate small little building where we kept our bikes during the wintertime, and the lawn mower, and other larger tools. A shed is a place “to store” (store) or to keep things.
There are other meanings of the words “shack” and “shed.” “Shed” can also be a verb that is used to describe what happens when the hair of an animal falls off. Cats often shed hair. They lose their hair. “To shed” can also mean to get rid of extra weight, to lose weight, in the expression “I’m going to shed some pounds.” I’m going to get rid of these pounds, this extra weight I have.
There’s a phrasal verb we used to use, it’s not as common anymore, “to shack up.” “To shack up” means to live with someone with whom you are not married but with whom you’re having sexual relations. We don’t say that anymore because that’s become so common, no one thinks it’s an insulting thing to say. The more polite way of saying that is “living together.” When I was growing up, we called it “shacking up.”
Our final question comes from Victor (Victor) in Spain. Victor wants to know the meaning of two expressions. The first one is “to take advantage of something” or “to take advantage of someone.” Those are actually two different expressions and two different meanings.
“To take advantage of something” such as an opportunity means to get the most out of something, to take the fullest advantage or fullest benefit from something. “I’m going to take advantage of my trip back to Minnesota to have some good steak and corn because there are a lot of farms in Minnesota.” “I’m going to take advantage of my trip to New York to see a show on Broadway” – to go and see a play.
“To take advantage of someone,” however, is a bad thing. “To take advantage of a person” is to use that person in a way that benefits you but not the person. It may mean even stealing something from that person or using that person’s innocence or lack of knowledge to get some benefit for yourself. It could even mean to have some sort of sexual relations with another person who might not be able to resist you – perhaps the person is drunk.
The second question is about the verb “to seize” (seize). “To seize” means to take something or use something quickly and enthusiastically. It can also be used with the word “opportunity” to mean something similar to “to take advantage of an opportunity.” “To seize an opportunity” means to take an opportunity and start using it right away. The idea behind “seize” is that it is a matter of speed, of quickness. You do it right away, immediately, without hesitation.
There’s an old Latin expression “carpe diem” which is often translated into English as “seize the day.” It means take advantage of today and the opportunities and chances you have today because tomorrow, well, you might be dead. I hope not, but if you are, you’ll be happy you’d taken advantage – “seized the day” – today. “To seize” also has some other less pleasant meanings. The government can “seize” your car, or your house, or other things that you own if you, for example, don’t pay your taxes. The government can “seize your property,” the things that you own.
“To seize” can also mean for one person to use his or her hand to grab another person, often against that person’s will or desire. If I seized your arm, I grabbed it with my hand, usually by using some force. I might even hurt you as I do it. “To seize a person” means to take a person against his will and put them somewhere that person doesn’t want to be.
It could also be used to describe what police do when they take someone who they think is a criminal. They “seize the criminal.” They grab the criminal and they bring that criminal to the police station. An army, or even a group of criminals, can “seize” someone. They take the person against that person’s will – that is to say, the person doesn’t want to go with them but they have no choice.
You have a choice if you don’t understand something about English – you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
applied – putting something, such as an idea or theory, to use
* In applied linguistics, researchers don’t just study the language itself, they study how language is taught, learned, understood, and used.
plantation – a large farm growing crops such as coffee, sugar, and tobacco and worked by people who live on the property
* When it was time to pick the tobacco, everyone on the plantation went out into the fields and worked from sunrise to sunset.
cotton – white material that grows on tall plants used to make cloth
* Many types of clothing are made from cotton, which is soft, easy to clean, and relatively inexpensive to produce.
patent – government permission giving a person or company the right to be the only ones to make or sell a specific item for a certain amount of time
* Thomas Edison had over 2,000 patents, including over 400 for inventions involving electricity, power, and light.
to sue – to bring a legal action in court, asking a judge or jury to make a decision based on evidence and the law
* After the car accident, Marie had terrible neck pains and had to see a lot of doctors, so she sued the other driver to pay for her medical bills.
license – official permission to do something or to use something
* In many countries, people who are at least 18 years old may get a driver’s license.
mass production – the process of making goods in large numbers using machines or by making individual parts in large quantities and then fitting them together
* Mass production allows this factory to make hundreds of air conditioning units each day.
follies – a theater show with different types of entertainment, such as singing, dancing, and funny acts, usually with all women
* The women in the follies are beautiful and talented performers.
revue – performance in a theater that includes a set of short scenes or acts, songs, and dances
* The student revue took place at the end of the school year and the students from each grade level performed acts they had written about their teachers.
opulent – very rich, expensive, and elegant
* The mansion was incredibly opulent with gold paint on the ceilings and white marble floors.
spectacle – a very impressive or memorable show or display
* The arrival of the king and queen at the airport was quite a spectacle, with several dozen police officers and hundreds of reporters and cameras there.
revealing – clothing that shows more of a person’s body than is typical
* That dress is too revealing and shows too much of your back.
ROFL – “Rolling on the Floor Laughing,” an abbreviation commonly used to show one’s amusement in electronic communication, such as texting and social media
* Myung texted Rafe a joke and Rafe responded, “ROFL!”
straight outta – informal way to say “straight out of”; coming originally or directly from some position, event, or place
* Patrick has lived in Michigan most of his life, but from the way he talks, you’d think he came straight outta Georgia.
meme – a humorous image, video, or piece of text that is copied, often with slight changes, and spread rapidly on the Internet
* Did you see that meme of Jeff kissing a cat? It was so funny!
shack – a small house or building that was built with rough materials and is not put together well
* My brother said he bought a cottage by the sea, but when I saw it, it looked more like a shack.
shed – a small, simple building that is typically used for storing things, such as tools and machinery
* Could you go into the shed and bring me some of my gardening tools?
to take advantage of – to use an opportunity, in a way that helps one; to make good use of something
* A lot of customers take advantage of discounts offered only on Mondays.
to seize – to take or use something, such as a chance or opportunity, in a quick and eager way
* Nico was finally alone with Shannon so he seized the moment to ask her for a date.
What Insiders Know
Whitney Museum of American Art
Gertrude Vanderbilt Whitney, a member of the “wealthy” (rich; with a lot of money) Vanderbilt and Whitney families, was a “sculptor” (someone who makes three-dimensional art) and an “art collector” (a person who buys many pieces of art made by other artists). In 1929, she offered to “donate” (give at no cost) about 700 pieces of art to the Metropolitan Museum of Art, but the museum refused her offer, so she decided to open her own museum.
In 1931, she “founded” (established; created and opened) the Whitney Museum of American Art, now commonly referred to as The Whitney. It is a large art museum in Manhattan in New York City, filled with American art from the 1900s and 2000s. It focuses on “exhibiting” (showing to the public) the artistic work of “living artists” (artists who are still alive and producing new art). This focus presents valuable opportunities to artists whose work has not yet been “discovered” (found and appreciated by a large number of people).
The Whitney has many paintings, sculptures, drawings, photographs, and other objects of art. It was the first museum to present the work of a video artist, and it even had a show of “live” (in-person) “bodybuilders” (people who lift weights to get very large, defined muscles and show their bodies to others in competitions) that included actor and former California governor Arnold Schwarzenegger.
The museum has been moved several times to find enough room for the large and growing art collection. Most recently, the Whitney moved to a new building in Manhattan in May of 2015.