
= 2025.03.04 Keeping the peace on NATO’s longest border with Russia 维护北约与俄罗斯最长边界的和平
:toc: .toc
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss0.css

'''

== 释义

==== 主持人开场

Very warm welcome to _Chatham House_ 查塔姆研究所（英国皇家国际事务研究所）. I'm Bronwen Maddox, the director （某一活动的）负责人, and I'm delighted 高兴的 to have here this morning Elina Valtonen, Foreign Minister of Finland.

Start getting your questions ready! Just a few housekeeping 家务（尤指采购和管理开支） things —this is on the record 记录在案的, it is being recorded 录制的, and it is being live-streamed 直播的. We have television cameras here as well, taking a feed （婴儿的）一次喂奶，一餐；（动物的）一次喂给的饲料;（电视中心台）网络供给节目（系统）;信号.

[.my2]
准备好你们的问题吧！先说几句注意事项——这次会议会被记录下来，正在录音，也在进行直播。这里还有电视摄像机在拍摄画面。

Let me say just a few things before the minister makes her__ opening remarks__ 开场白. We are obviously in extraordinary 非凡的 times, and she has a biography 传记 that could not be better placed to talk about all these issues.

She is a fourth-term 第四届,第四任 member of parliament 议会, Deputy Chair 副主席 of _the National Coalition 联合政府；联合体，联盟；联合，结合 Party_ in Parliament. She has served as _Vice Chair_ 副主席 of _the Foreign Affairs Committee_ 外交事务委员会 and has been a member of _the Defense Committee_ 国防委员会, _the Finance Committee_ 财政委员会, and _the Grand Committee_ 大委员会. Additionally, she has chaired (v.)担任主席 the Finnish delegation 代表团 to _the NATO Parliamentary Assembly_ 北约议会大会.

Before that 在此之前 , she worked in the private sector 私营部门 in various 各种 countries, including ten years in the financial sector 金融部门 in Copenhagen 哥本哈根（丹麦首都） and London. She is also a former 以前的 computer programmer 计算机程序员, which I found interesting to read. Furthermore, she has been involved in *setting up* various _growth companies_ 成长型公司 and is an author 作者 of a best-selling book 畅销书 about some of the issues we are likely to be discussing today.

So, she has the perfect background to talk about all of this! Please, get your questions coming 提出你的问题. We are given, by the hour —by the minute —more things to talk about.

[.my2]
所以，她具备谈论这一切的绝佳背景！请各位踊跃提问。我们每时每刻都有更多的话题可聊。

But for the moment, Minister 部长，大臣, welcome. Thank you very much indeed  确实，的确；实际上；真正地! We look forward to 期待 your _opening remarks_ before we start deluging 淹没 you with questions.

==== 芬兰外长开场演讲

Thank you so much, Bronwen. It’s great to be here.

I must say, I don’t think anybody has the perfect background for the times 时代 we live in. But certainly, I will give it a try 试一试!

Ladies and gentlemen, it is a true privilege 荣幸 to see you all here today and to address (v.)演说，演讲 _Chatham House_ in this historic 历史性的 setting 环境, where `主` great ideas and solid 坚实的 principles 原则 shaping 塑造 global affairs 全球事务 `谓` have long been debated 辩论. I am honored (a.)荣幸 to contribute 贡献 to this essential 必要的 conversation 对话.

And if not today, when great ideas and solid principles are needed—then when?

Today, I would like to speak to you about security 安全, the future of Europe, and Ukraine. I will focus on _European support_ for Ukraine, the pathway 途径 to _sustainable 可持续的 peace_ 和平, and how to strengthen 加强 the role of Europe in writing the next chapter of the Free World.

One thing we can say for sure is that we in Europe have a unique 独特的 opportunity 机会 to take ownership 拥有所有权 of our own future. This is not to say that we would do it *at the cost of* 以……为代价 our transatlantic (a.)大西洋两岸国家的；横渡大西洋的；在大西洋彼岸的 ties 跨大西洋关系. On the contrary, by starting *to better pull (v.) our own weight* 自力更生, we strengthen 加强 the partnership 伙伴关系 后定 so crucial 至关重要的 to both sides of the Atlantic.

[.my1]
.案例
====
.pull your weight
to work *as hard as* other people in a group 做好自己的份內事，做好本職工作 +
- The others had complained that Sarah *wasn't pulling her weight*.
其他人抱怨說莎拉工作不盡職。
====

We Finns 芬兰人 don’t usually like *to make a big deal of* 對某事小題大作 ourselves, but on this matter, I must depart (v.)背离，违背；离职 from tradition 偏离传统 and say that defense 防御 and security 安全 are topics we truly know something about. Our history has taught us *not just* how to survive 生存, *but* how to defend 捍卫 what we hold dear 珍视的东西.

==== 乌克兰战争与欧洲的责任

`主` Russia’s war of aggression 侵略 against Ukraine `谓` shattered (v.)粉碎 the post-Cold War ideals 冷战后的理想 of stability 稳定 in Europe. That aggression started more than ten years ago with the illegal 非法的 annexation (n.)吞并 of Crimea 克里米亚. Now, Ukrainians 乌克兰人 have fought a full-scale war 全面战争 for three long years and continue to fight for their right to live (v.) as an independent 独立的 nation 国家, *free from* 免于,摆脱 oppression 压迫.

Let us be clear: Ukraine is not only fighting for its own survival 生存—it is fighting for all people’s right to choose 选择 and to be free.

Finland** stands (v.) with** Ukraine now. Finland will continue to stand with Ukraine in the future. *Compared to* 与（某事物）相比 the size of our GDP 国内生产总值, Finland is Ukraine’s fifth-biggest supporter 支持者. We are *in constant (a.)持续的 contact 联系 with* _the Ukrainian government 政府 and armed (a.)forces_ 武装部队 to ensure 确保 that our support continues (v.) to meet their immediate (a.)立即的;目前的，紧迫的 needs 需求 and is made available without delay 毫不拖延.

On top of that 除此之外, we are actively 积极地 enhancing (v.)增强 Ukraine’s long-term strategic 战略的 resilience 韧性;恢复力，复原力. We explore (v.)探索 new means 手段 and mechanisms 机制, including support (v.) for Ukraine’s own defense industry. `主` Ukraine’s rapid 迅速的 innovation 创新 in _drone 无人机 warfare_ 战争 `系` is a testament 证明，证据 to their defense forces’ resolve 决心, and we must ensure (v.)确保 that they have the industrial capacity 工业能力 to maintain 维持 this edge 优势.

The pledge 承诺 of long-term security assistance 安全援助 for Ukraine, announced at the Washington NATO Summit 华盛顿北约峰会 last summer, is one of the key elements 关键因素 in our commitment 承诺. We must make sure that the alliance 联盟 *delivers (v.)履行诺言；不负所望；兑现 on* this pledge 履行承诺.

[.my1]
.案例
====
.deliver
(v.)*~ (on sth)*  to do what you promised to do or what you are expected to do; to produce or provide what people expect you to履行诺言；不负所望；兑现 +
• She always *delivers (v.) on* her promises.她总是信守诺言。
====

==== 欧洲的领导角色

Ladies and gentlemen, now is the time for European leadership 领导权.

[.my2]
现在是欧洲发挥领导作用的时候了

The day before yesterday, your _Prime Minister_ 首相，总理 brought together an important and timely (a.)及时的 leaders' meeting 领导人会议 here in London, accelerating (v.)加速 our efforts 努力 to support (v.) Ukraine and to seek 寻求 a just 公正的 and lasting 持久的 peace 和平. Europe has momentum 势头;冲力，推力；动力, and we will use it.

The day after tomorrow 后天, the European Council 欧洲理事会 will convene (v.)召开 on the initiative 倡议 of Finland’s Prime Minister Petteri Orpo. I expect that the meeting in Brussels this week will deliver concrete 具体的 and sizable 大量的 commitments 承诺 for additional 额外的 EU support to Ukraine, *as well as* 和，以及，还有 take (v.) decisive 决定性的 steps toward strengthening (v.)加强 European defense 防御 —or "*rearming (v.)重新武装；重新装备 Europe*," as _the President of the European Commission_ 欧盟委员会 has phrased (v.)（以某种方式）表达，措辞，推敲 it.

We have reached a point where decisions must not be symbolic 象征性的. They must be consequential (a.)重要的；将产生重大结果的;随之而来的；相应发生的；作为结果的.

[.my1]
.案例
====
.consequential
(a.) important; that will have important results 重要的；将产生重大结果的 +
• The report discusses _a number of consequential (a.) matters_ that are yet to be decided. 这份报告讨论了许多有待决定的重大问题。

====

Let me be absolutely 绝对地，完全地 clear: if we do not act (v.) now, we will pay a far greater price 付出更大的代价 later. There can be no sustainable 可持续的 peace 和平 in Ukraine *without* a strong 强大的 and sovereign (a.)（国家）有主权的，完全独立的 Ukraine. This is not just a _political reality_ 政治现实 —it is a _moral imperative_ (n.重要紧急的事；必要的事) 道德义务.


==== 如何应对俄罗斯的威胁

`主` *Rushing (v.) to* a deal *at the cost of* its content 内容 and without due (a.)适当的;预期的；应有的，应得的 consideration 考虑 of the consequences 后果 `谓` would endanger (v.)危及 *not only* Ukraine *but also* Europe —and, *by extension* 引申开来,相关地,结果是,  the United States —for generations to come 为子孙后代，为未来几代人.

[.my2]
不充分考虑后果，为了达成协议而仓促行事，不仅会危及乌克兰，还会危及欧洲，进而危及美国，影响到未来几代人。

[.my1]
.案例
====
.by extension
used to show that someone or something is connected with and affected by something else; therefore +
- His report contained serious criticisms of the finance director, and, *by extension*, of the entire board of management. 他的报告严厉批评了财务总监，进而批评了整个管理委员会。
====

We Finns 芬兰人 know Russia. Russia shares a land border 陆地边界 with fourteen countries, but _only one of them_ has remained _a continuously 持续的 independent 独立的 democracy_ 民主 through the Second World War 第二次世界大战 and the Cold War 冷战—and that’s Finland.

[.my2]
我们芬兰人了解俄罗斯。俄罗斯与十四个国家接壤，但只有一个国家在第二次世界大战和冷战期间始终保持独立民主——那就是芬兰。

History has taught (v.) us that Russia respects (v.) only strength 力量 and resolve 决心. Russia’s current war is based on imperialistic 帝国主义的 ambitions 野心 that *go beyond* 超过（或超出）某事 Ukraine. The Kremlin’s 克里姆林宫 appetite 胃口 does not diminish (v.)减少 when fed (v.)喂养—it only grows.

[.my2]
历史告诉我们，俄罗斯只尊重力量和决心。俄罗斯当前的战争是基于超越"仅获得乌克兰领土"的帝国主义的野心。克里姆林宫的胃口不会因为喂养而减少，只会增长。

Take it from us 相信我们: whatever happens in this war, Russia will remain a long-term strategic 战略的 threat 威胁 to Euro-Atlantic security 欧洲-大西洋安全. Rather than encourage 鼓励 it, we need *to keep it at bay* 不让（敌人）接近；防止（问题恶化）;阻止.

[.my1]
.案例
====
- bay: （海或湖的）湾; 分隔间（户外或室内的，用以停放车辆、存放货物等）
- *at ˈbay* : when an animal that is being hunted is at bay , it must turn and face the dogs and hunters because it is impossible to escape from them（猎物）被围困，被迫作困兽之斗
- *hold/keep sb/sth at ˈbay*: to prevent an enemy from coming close or a problem from having a bad effect不让（敌人）接近；防止（问题恶化）
====



Of course, we need to be open (a.) to re-engagement (v.)重新接触 in the future —if Russia starts (v.) to adhere 遵守 to international law 国际法 again. But going forward, it would be a mistake *to let go of* 松开，放开;放下，放弃 our deterrence (n.)威慑 or to rebuild (v.) strategic dependency 战略依赖 on Russia. This *applies to* 适用于 all of Europe.

So far, we have not seen any sign that President Putin has any genuine (a.)真正的 will 意愿 to negotiate (v.)谈判 a lasting agreement 持久协议. On the contrary, just a week ago —on the third anniversary 周年纪念日 of Russia’s invasion 入侵 —Russia launched 发动 its largest drone (n.)无人机 attack 袭击 on Ukraine. That is not what you would expect (v.) from someone who is truly interested in peace.


There is no reason whatsoever (a.任何，无论什么;adv.丝毫) 根本没有理由 to believe that Putin has moderated (v.)缓和 his demands 要求 from those he laid out 提出 in December 2021— `主` *demands (v.) that*, if accepted, `谓` would roll back 回滚, 撤销 decades 几十年 of progress 进步 in European security.

[.my2]
如果这些要求被接受，将使"欧洲安全"倒退几十年的进步。

Caving (v.)屈服;让步；屈从;山洞；洞穴 to these demands would expose (v.)使暴露 Europe to further 进一步的 aggression 侵略. Instead, our objective 目标 must be a just (a.)公正的 and lasting 持久的 peace 和平 that respects 尊重 international law 国际法, including the prohibition 禁止 of annexation 吞并 of territory 领土 through the use of force 武力.

==== 结语

Let me emphasize (v.)强调: peace 和平 *does not —and must not —mean*  (v.) submission 屈服. True peace 真正的和平 is built on justice 正义, accountability (n.)问责;责任，责任心，可说明性, and deterrence 威慑.

We must not mistake (v.)误解 a temporary 暂时的 pause 暂停 for a sustainable 可持续的 peace 和平. If in doubt, ask the Baltic states 波罗的海国家 *what kind of "peace" it was* to live (v.) under Russian —or, back then, Soviet —occupation 占领.

[.my2]
我们绝不能将"暂时的停火", 误解为"可持续的和平"。如果有疑问，请询问波罗的海国家在俄罗斯——或当时的苏联——占领下生活是怎样的一种“和平”。


To secure (v.)确保 a peace 和平 that can last (v.)持久的, Ukraine needs a strong deterrent 威慑 against any future aggression 未来的侵略. Without such guarantees (n.)保证, any truce 休战 or ceasefire 停火 is only an invitation 邀请 for Russia to regroup (v.)重组 and return.

We must not repeat 重复 the mistakes made with the Minsk agreements 明斯克协议. The most credible 可信的 security guarantee 安全保证 would be NATO membership 北约成员国资格 for Ukraine.

Until then, and even thereafter 其后，此后, the required (a.)必要的 deterrence 威慑 must *be based primarily 主要地 on* Ukraine’s own defense forces 防御力量, firmly 坚定地 supported (v.)支持 by _external (a.)外部的，外面的；外来的 assistance_ 外部援助 and _credible 可信的 security arrangements_ 安全安排 provided 提供 by Europe and the U.S.

In parallel 同时, Russia’s position must be further weakened (v.)削弱. Sanctions 制裁 must be strengthened (v.)加强, and their implementation 实施 made more effective 有效的.

Russia's war economy 战争经济 is already showing serious cracks 裂缝.

[.my2]
俄罗斯的战争经济, 已经出现严重裂缝。

We must also find a way to use (v.) the frozen Russian assets 冻结的俄罗斯资产, around 200 billion euros 欧元 in Europe, to support Ukraine and compensate 补偿 for the damage 损害 Russia's aggression 侵略 has caused.

We Finns 芬兰人 know from experience 经验 that Russia is a skillful 熟练的 but unreliable 不可靠的 negotiator 谈判者.

One of our foremost 最重要的 diplomats 外交官 and later president 总统, J. K. Paasikivi, was _on several occasions_ 几次 on the other side of the table from Stalin and Molotov /when `主` our existence (n.)存在 as an independent 独立的 country 国家 `系` was *on the line* 处于危险中 in the 1930s and 1940s.

[.my2]
我们最杰出的外交官和后来的总统J.K.帕锡基维, 曾在1930年代和1940年代的几次会议上，与斯大林和莫洛托夫在谈判桌对面，当时我们作为一个独立国家的存在危在旦夕。

He *summed it up* 总结 like this: "_The constant 持续的 policy_ 政策 of the Russians is `表` to get what they can with *as little as possible* /and then come back *asking for* more. They never *sacrifice* (v.)牺牲；献出 their immediate 立即的 interests 利益 *for* future objectives 未来目标. They are immune (a.)免于 any ethical 道德的, human 人类的, or abstract 抽象的 legal 法律的 factors 因素."

[.my2]
他总结如下：“俄罗斯人的一贯政策是, 以尽可能少的代价得到他们能得到的东西，然后回来要求更多。
他们从不为了未来的目标, 而牺牲眼前的利益。他们不受任何道德、人道或抽象法律因素的影响。”

This is the Finnish experience 芬兰经验.

The Ukrainians 乌克兰人 know (v.) from their own experience 经验 that Russia has broken (v.)违反 every single commitment 承诺 they have ever made on Ukraine's sovereignty 主权.

_No agreement 协议 with Moscow_ can stand (v.)没有…就不能成立 without _the will 意愿 and the means_ 手段 to enforce 实施 it.

`主` The merits 优点 of any agreement 协议 that may *result (v.)（因…）发生；（随…）产生 from* the talks 会谈 that have been initiated 发起 between the US and Russia, or any group of countries *for that matter* 就此而言；至于那个；说到那一点, `谓` will not be judged (v.)判断 on the day of the signing 签署. +
They will be judged 判断 every day thereafter 之后每天 to make sure that `主` the deal is a good one.

[.my2]
任何可能由美国和俄罗斯之间，或者任何国家集团之间已启动的会谈所达成协议的价值，都不会在签署协议的当天就得以评判。此后每天都会对他们进行评估，以确保这笔交易是划算的。

The US will need Europeans 欧洲人.


Dear friends, history has shown that when Europe and the United States stand (v.) together, we are an unbreakable 不可打破的 force  for peace, security 安全, and freedom.

Transatlantic 跨大西洋的 partnership 伙伴关系 has historically (ad.)历史上 been strong, and it must remain (v.)保持不变，一直是；仍需去做（或处理） so.

President Trump is certainly right that we in Europe must do more for our own security 安全.

But for both the US and Europe to succeed 成功 in bringing (v.) peace 和平 to Ukraine and strengthening (v.)加强 transatlantic 跨大西洋的 security 安全, we must build peace through the strength of alliances 联盟.

This *applies #to#* security 安全 and defense 防御, but also *#to#* the global 全球的 economic and technological competition.

On the British Isles 不列颠群岛 *as well as* on the European continent 欧洲大陆, we share the same concerns 担忧 about the future.

We are determined (a.v.)决心 to act 行动 *so that* we can shape (v.)塑造 that future 未来 *rather than* being shaped by it.

The UK's contribution 贡献 to European security 欧洲安全 is *not just* historic 历史性的, it is essential 必要的，非常重要的.

[.my2]
英国对欧洲安全的贡献不仅是历史性的，而且是至关重要的。

*From* both World Wars 世界大战 *to* the present day 至今, Britain has stood (v.) firm (ad.)坚定地 when freedom has been *at stake* (火刑柱) 处于危险中.

_Prime Minister_ Sunak's recent 最近的 commitment 承诺 to increasing (v.)增加 _defense spending_ 开支 is a powerful  and timely 及时的 message 信息. It *coincides (v.)相同；相符；极为类似 with* 与…一致 similar 相似的 decisions 决定 across Europe.

[.my2]
这与欧洲各地的类似决定, 相吻合。

We are stepping up 采取行动 together.

The EU 欧盟 and the UK 英国 have a GDP 国内生产总值 almost 几乎 10 times （用于比较）倍 the size of Russia.

We have the means 手段，方法；金钱.

`主` Whether we have the political will 政治意愿 `系` is _a question of priority_ 优先事项, and `主` *no priority 优先事项 `系` is higher than* keeping our citizens 公民 safe  and free.

[.my2]
我们是否有"政治意愿", 是一个优先事项的问题，没有比保障我们公民的安全和自由更重要的优先事项。

By *doing more* as Europe, we also *show* [_with actions_ 行动] `宾` *our value* 价值 as _a trusted 受信任的, indispensable 不可或缺的 transatlantic 跨大西洋的 partner_ 伙伴.

[.my2]
通过作为欧洲做更多的事情，我们也用行动展示了我们作为值得信赖的、不可或缺的跨大西洋伙伴的价值。

So, Winston Churchill 温斯顿·丘吉尔 once said, "To each /there comes a moment when *they are figuratively 比喻地 tapped (v.)轻拍 on the shoulder* 肩膀 and *offered the chance 机会 to do a special thing*, unique (a.)独特的 to them and their talents 天赋." This is Europe's moment 时刻.

[.my2]
因此，温斯顿·丘吉尔曾经说过：“每个人都会有一个时刻，他们会被比喻地轻拍肩膀，并有机会做一件特别的事情，这件事情是他们和他们的天赋所独有的。” 这是欧洲的时刻。


We must *rise to* 能够处理，有能力处理（突发情况、问题等）;上当；上钩；进圈套 it.

I thank you so much for your attention 注意力.

[.my2]
非常感谢大家的关注。

[Applause]

Min, thank you very much indeed, um, for those remarks 评论；言论.

Very wide-ranging 范围广泛的.

Let me ask you a few things, and then I will come to the wider questions 更广泛的问题.

Not yet, um, but, but well done, you, and well done, online, Raphael Morto, for firing (v.)开火；发射 a whole list 一系列.

[.my2]
还没有，但做得好，你，还有在线的Raphael Morto，列出了一系列问题。

So, Finland joined (v.) NATO 北约 two years ago, a bit less.

What is the alliance 联盟 you think Finland has joined? Is it one that is going to stick by 坚持 its Article 5 commitment 承诺? I'm sure that, um, NATO will stick to 坚持 its Article 5, uh, commitment, and also the US. Um, we have heard nothing which would be contrary (a.) to 与…相反 that.

[.my2]
那么，芬兰在两年前加入了北约。你认为芬兰加入的是什么样的联盟？它会坚持其第五条承诺吗？我相信北约和美国都会坚持其第五条承诺。我们没有听到任何与此相反的消息。

Uh, indeed, um, President Trump and his administration have, um, have also ensured 确保 that they, they stick, uh, to NATO and its commitments.

And in any case 无论如何、无论如何的情况下、或者无论怎样, I, I guess Finland and its own history show that we never, um, relied on 依赖 _outside help_ anyway 不管怎样，无论如何. Um, we have always, um, *put* our own defense 防御 *first*.

[.my2]
我们总是把防御放在首位。

And, um, again, we joined NATO only, only two years ago, um, together with Sweden. And, uh, we know that, uh, well, we are net contributors 净贡献者 to the alliance, and we would very much like *to be that* also, also in the future. But *having said this* 但说到这里, it's very important that, uh, all of our European partners also step up 加强;增加，提高，推进 in this.

[.my2]
我们知道，我们是联盟的净贡献者，我们也希望在未来继续保持这一点。但话虽如此，我们的欧洲伙伴们也必须加强这方面的努力。


What would you like to see from them? Finland is obviously making a, a much greater contribution 贡献 to defense. You've got now _firm plans_ 明确的计划 for 3.3% of GDP by 2032. But that isn't where the whole of the EU 欧盟 is. What would you like to see from them?

[.my2]
你希望从他们那里看到什么？芬兰显然在国防方面做出了更大的贡献。你们现在有明确的计划，到2032年将国防支出提高到GDP的3.3%。但这并不是整个欧盟的情况。你希望从他们那里看到什么？

I think the EU is already doing a tremendous 巨大的，极大的；极好的，精彩的；令人望而生畏的，可怕的, uh, job. And, um, on their line （尤指公开表明的）态度，看法;（行进的）方向，路线；方位, um, the _commissioner （政府部门的）首长，长官；（委员会的）委员，专员  president_ 委员会主席, um, she, um, published, uh, today, um, the ideas on, on how we as the European Union will be *stepping up* 加强 in terms of 在…方面 defense and deterrence 威慑. Um, the commitment 承诺，保证 is there, and it will happen. Um, *everybody just has to understand that* it takes some time. Um, um, you can't build an army 军队 overnight 一夜之间, right?

[.my2]
我认为欧盟已经在做一项巨大的工作。今天，欧盟委员会主席发表了关于欧盟如何在国防和威慑方面加强的设想。承诺已经在那里，它将会发生。每个人都必须明白，这需要一些时间。你不能在一夜之间建立一支军队，对吧？

[.my1]
.案例
====
在这句话的口语表达中，"on their line" 可能是说话人暂时停顿、思考或口误的一部分，而不是一个固定的短语。不过，从语境来看，它可能意味着以下几种情况之一：

"In line with their position"（与他们的立场一致）

说话者可能是想表达 “按照他们的立场”，即“欧盟按照自己的立场或承诺，在国防和威慑方面采取行动”。
如果是这个意思，"on their line" 可能是"along their line of thinking" 或 "in line with their stance" 的简略说法。
"Regarding their statement/announcement"（关于他们的声明）

说话者可能想提到某个官方声明或立场，比如欧盟委员会的声明。
例如："On their line of communication"（关于他们的沟通方式）或 "On their official position"（关于他们的官方立场）。
"Following their strategy"（遵循他们的战略）

这里可能是指欧盟在防御和威慑方面的政策，与之前的战略方向一致。

不过，由于这段话充满了口头填充词（um, uh），它可能只是一个无意的停顿，并不具有实际的语法意义。如果要理解更准确的意思，最好结合上下文。
====


Uh, and, uh, we are, of course, um, happy to, to share the burden 分担负担. And, and I think `主` the course of action 行动方针 which has been there in the past 3 years already `系` is exactly 确切地；（用于强调）恰好，完全 the right one. We just have to continue.

And I'm saying this /because there's been so much Europe bashing (n.v.)抨击 in the, in the past, uh, weeks. Uh, but I think what Europe has done is exactly the right thing.

We have aided (v.)援助 Ukraine, we have put economic pressure 经济压力 on Russia, and we have, perhaps too slowly, but still, started (v.) as individual countries *to ramp (v.)为……提供（或建造）斜面（或斜坡） up* 增加;使…的数量增加 our defense industries 国防工业 and our defense.

[.my2]
并且虽然可能有些慢，但作为个体国家，我们已经开始加强国防工业和国防。

Do you think Europe can defend (v.) Ukraine on its own 独立地，单独地? We have now, uh, the US pausing 暂停, it's the Trump administration's word, pausing its aid 援助, uh, to Ukraine, obviously an attempt 尝试 to bring Ukraine to the negotiating table 谈判桌. Can Europe fill that gap 填补空白?

[.my2]
你认为欧洲能独自保卫乌克兰吗？现在，美国暂停了对乌克兰的援助，这是特朗普政府的说法.

Um, I think we need the Americans. Uh, we need the Americans militarily (ad.)军事上, but especially also to keep up 维持 the sanctions pressure 制裁压力.

[.my2]
我们需要美国在军事上的支持，但尤其是维持制裁压力。

Because the worst thing that could happen now is that, um, the, the US, uh, *lets go of* 放弃;松开，放开 the sanctions and starts engaging with 与…交往 Russia economically. Because that would be exactly _the wrong course 进程，进展；方针，总方向；行动方式，处理方法 of action_ 错误的行动方针 now where we see that Russia's economy clearly is not sustainable 可持续的 as it is now 现在这样. They are allocating (v.) 分配 8% or even more of their GDP, uh, into the war economy 战时经济. The inflation 通货膨胀 is well above 30%. The domestic banking sector 国内银行业 is in serious trouble, uh, with _interest rates_ 利率 of, uh, also *north of* 超过、高于, uh, 20%, uh, even much, much higher for, for smaller businesses. It's not sustainable. So, if we just, you know, waited for at least some months, we would be in such a much better place.

[.my2]
(俄罗斯)国内银行业陷入严重困境，利率也超过20%，对小企业来说甚至更高。所以，如果我们再等几个月，情况会好得多。

[.my1]
.案例
====
- "north of" 是一个地道的英语表达，意思是 "超过"、"高于"，类似于 "above" 或 "more than"。
====


And also, what has to be noted is that /also on the battlefield 战场, um, Russia has not really been advancing 推进 in the late, in, in the recent months.

Um, they have been advancing only very, or taking very small steps and, and at very heavy losses 重大损失.

Um, so this definitely 肯定地，当然；明确地，确定地 shouldn't be a moment where we give, give in 屈服, or especially not that we surrender 放弃 Ukraine. Because, well, um, that's certainly not something, um, what the Ukrainian people wanted to have for their future.

[.my2]
所以，这绝对不应该是我们屈服或放弃乌克兰的时刻。因为，这当然不是乌克兰人民希望看到的未来。

That is undeniably 不可否认地 correct, and there are a lot of people, I suspect a lot of people here, who would agree with you. But we don't have that time *in that* 因为；由于；就在于 the US is, is very much, uh, changing the timetable 时间表 of all this, separate from what is happening on the, on the battlefield.

这是不可否认的正确，我怀疑这里有很多人会同意你的观点。但我们没有时间，因为美国正在改变这一切的时间表，与战场上发生的事情无关。

President Trump says, um, President Putin *wants peace* 想要和平. Is he making a mistake? You've got, you've had some pretty tough words 严厉的言辞 about _what Russia wants_ over the years.

[.my2]
特朗普总统说，普京总统想要和平。他是否犯了错误？多年来，你对俄罗斯的意图发表了一些相当严厉的言论。


Well, look, um, I think President Trump is exactly right in demanding 要求 peace. Who wouldn't want peace? But I guess _the only one_ not wanting peace is Putin, who invaded 入侵 _in the first place_ 首先，最初.

So, um, you know, the analysis, um, just has to start at the realization 认识 of the fact. And, the thing is, I mean, if Russia started their peace now, they could do that by *withdrawing 撤军 their troops* or _at least_ 至少 *stopping (v.) those heinous 恶劣的;极恶毒的；道德败坏的 attacks (n.) on* civilian infrastructure 民用基础设施 and on Ukrainian military. Um, but if Ukraine did that, then probably you wouldn't have Ukraine any longer 不再.

[.my2]
所以，分析必须从认识事实开始。如果俄罗斯现在开始和平，他们可以通过撤军或至少停止对民用基础设施和乌克兰军队的恶劣攻击来实现。但如果乌克兰这样做，那么你可能就不会再有乌克兰了。

You, you *put a lot of weight* 重视 [in your remarks] *on* the notion 概念 of sustainable peace 可持续的和平, uh, which Europe wants. Do you think the US has the same notion 概念，想法 of peace?

[.my2]
你在评论中非常重视欧洲想要的可持续和平的概念。


Well,  our message to _our friends in America_ is that history will judge (v.)裁判，评判 us, by the developments 发展 after the signing of the agreement 协议, not just that moment when _any possible agreement  is being signed_.

[.my2]
我们对美国朋友的信息是，历史将根据协议签署后的发展, 来评判我们，而不仅仅是任何可能协议签署的那一刻。

And unfortunately, the experience we have as Europe from the Russians is that,  especially now 尤其是现在 during Putin's rule 统治, they are not willing to make any compromises (n.)妥协；和解；折中方案. They have only been advancing.

[.my2]
不幸的是，我们作为欧洲, 从俄罗斯人那里得到的经验是，特别是在普京统治期间，他们不愿意做出任何妥协。他们一直在推进。

If you look at what, you know, in Georgia 2008,  illegally annexing 非法吞并 Crimea 克里米亚半岛 2 14,  then, you know, the fighting in the Eastern parts of Ukraine, the Minsk agreements which *agreed on* ceasefire 停火, but Russia violated 违反 the ceasefire almost immediately and just *kept on advancing* slowly but surely. This is,  in my view, absolutely right.

Yet, that was one of the points 观点，论点；要点，核心问题 that President Zelensky *put to* President Trump in the Oval Office 椭圆形办公室, and *it didn't go so well* after that point.

[.my2]
然而，这是泽连斯基总统向特朗普总统在白宫提出的观点之一，之后事情并不顺利。

Um, do you think *it's fair to say that* we're dealing with 处理 an American administration 美国政府 后定 that just sees it very differently? Um, I guess President Trump,  well, *it's difficult to know exactly* how he sees the situation.

[.my2]
你认为公平地说，我们正在与一个看待问题非常不同的美国政府打交道吗？我想特朗普总统，嗯，很难确切知道他如何看待局势。

and, as said, it's easy *to agree with* the objective 目标 of finding peace.  but I think *what is important to realize is that this*, you know, um, `主` attempting to have a normal political and business  with the Russians `系` is exactly _the course of action_ 行动方针 everybody was engaged in 参与 *up until* 直到 effectively 有效地；实际上 22, right, four years ago.

[.my2]
正如所说，很容易同意寻找和平的目标。但我认为重要的是要意识到，试图与俄罗斯进行正常的政治和商业交往，正是每个人在四年前一直在采取的行动方针。

Europe was building a gas pipeline 天然气管道 with Putin still. I mean, less than 少于；不到；不足 four years ago. So, this, you know, *hoping (v.) for the best* 希望得到最好的结果 and engaging with the Russians, this was the mainstream (a.)主流的 course of action 行动方案. And only in the past three years /*have* we *individually*, European countries, and this is also important,  *to note (v.)指出；特别提到 to* our friends in Washington. I mean, Europe is not one country, right? So, we are making decisions individually.

[.my2]
欧洲还在与普京建设天然气管道。我是说，不到四年前。所以，希望最好的结果并与俄罗斯交往，这是主流的行动方针。只有在过去三年里，我们作为欧洲国家，才各自决定，我们必须遏制俄罗斯。

Even as the European Union 欧盟, it's a union of 27 sovereign nations 主权国家. But *even so* 尽管如此, in the past three years, democratically elected  (a.) leaders 民主选举的领导人 have decided more or less on the same thing, that we must keep Russia *at bay* (陷入困境) 遏制俄罗斯. So, why not continue with this? It's only been three years.

And I was thinking /as you were talking, *I just want to explore your sense of* what the European Union can do. Because as you say, it is a group of many very different countries, some of them quite close to Russia, others,  very different view. What do you think *it can do* as an organization,  the EU itself, or are we really talking about _coalitions 联合；结盟 of the willing_ 自愿的联盟 to use (v.) K's phrase?

[.my2]
我在你说话的时候想，我只是想探讨你对欧盟能做些什么的看法。因为正如你所说，它是由许多非常不同的国家组成的，其中一些国家与俄罗斯关系密切，另一些国家则非常不同。你认为它作为一个组织，欧盟本身能做什么，还是我们真的在谈论自愿联盟，用K的话说？

I think, `主` this _coalition of the willing_ thinking (n.) `系` is exactly what we need. And this is *what it will end up with* 以…告终 anyway 无论如何最终都会是这样的. And this is exactly *what it's been* the past three years 而这正是过去三年来的情况. Because of course, it's not just been the European Union. It's been the UK. It's been say Norway, Iceland, uh, also Turkey *doing its bit* (小片，小块) 尽一份力,  and of course, the US and Canada.

So, uh, and, and of course, many, many of our, uh, partners in the, in the Indo-Pacific 印太地区 as well, who have, who have been on the right side of history 站在历史正确的一边 in this.

So,  I'm sure this will continue. Or I hope it will continue. But also, as the European Union, we can do so much. And I think `主` #these# new arrangements 安排 for how to credibly 可信地 and strategically 战略性地  *ramp (v.) up* 逐步增加 our defense and our defense industries at the same time `系` #is# exactly what we should be doing.

但作为欧盟，我们也可以做很多事情。我认为这些新的安排，关于如何可信地和战略性地加强我们的国防和国防工业，正是我们应该做的。

And now *we're talking numbers* which are also credible. So, in total, say 800 billion.

现在我们谈论的数字也是可信的。所以，总共大约8000亿。

Because let's face (v.) it, the European Union *has also* 此外，而且；也，同样 in the past *been* *very powerful* if faced with 面对 outside crisis. In _the Euro crisis_ 欧元危机, well, we can all have our own ideas, the making of it, yeah, whether it was the right thing to do. Um, as a former banker, I have my own feelings about it. But anyway, so we put a lot of money on the table, and the ECB 欧洲央行 *did its bit* 尽一份力. And also during the COVID crisis, it was a package of 750 billion.

[.my2]
因为让我们面对现实，欧盟在面对外部危机时也非常强大。在欧元危机中，我们都可以有自己的想法，无论是这是否是正确的做法。作为一名前银行家，我对此有自己的感受。但无论如何，我们投入了大量资金，欧洲央行也尽了一份力。在COVID危机期间，它也是一个7500亿的援助计划。

So surely, if we wanted to, we can do it. And I guess this is an existential (a.)关于人类存在的；与人类存在有关的 issue 生存问题.

I just like to get your sense of how big _the coalition of the willing_ is likely to be. Because at the end of _the Lancaster House talks_ 会谈, uh, there were only two clear members. It *seemed like* 好像,看起来像是 the UK and France.

[.my2]
我只是想了解一下你对"自愿联盟"的规模有多大。因为在兰开斯特宫会谈结束时，只有两个明确的成员。似乎是英国和法国。


The UK had not invited the some of the Baltic countries 波罗的海国家 to that, which I think is mystifying (v.)令人困惑的;迷惑；使迷惑不解；使糊涂. But anyway, `主` the countries coming out and saying _we will contribute_, um, perhaps *to fighting in Ukraine* `谓` seems small. How big do you think that group might get?

[.my2]
但无论如何，那些站出来说我们将为乌克兰战斗的国家似乎很少。你认为这个群体可能会变得多大？

Well, I think *we are making a mistake* if we only concentrate (v.)集中注意力，聚精会神；使集中 on the capabilities 能力 *as defined 按照…的定义,以……的方式来界定 in* _boots on the ground_ 地面部队. Because, arranging (v.) security guarantees 安全保证 or, uh, certainly 无疑，确定；当然，行 in the using _the wider term 广义的术语 security arrangements_ 安全安排 for Ukraine, it's a combination 结合体，联合体 of so many things.

[.my2]
我认为如果我们只关注地面部队的能力，那我们就犯了一个错误。因为, 为乌克兰安排安全保证，或者更广泛地说，安全安排，是许多事情的结合。

[.my1]
.案例
====
这里的 "as defined in boots on the ground" 的 "as defined" 意思是 “按照……的定义” 或 “以……的方式来界定”。 +
整句话的意思可以理解为： “我认为如果我们仅仅把重点放在‘作战能力’，并且仅仅按照‘地面部队’的定义来理解它，那就是一个错误。”

"*as defined in* boots on the ground" 说明了能力的定义方式，意思是 “如果我们只把‘能力’定义为地面部队（即士兵实际部署在战场上）”。 +
"boots on the ground" 是一个军事术语，指的是实际部署在战区的士兵，而不是远程作战或其他类型的军事能力（比如空军、网络战等）。
====

and of course, while it is in our common interest 共同利益 to have _the best security guarantees and arrangements_ possible for Ukraine, we must at the same time *take care of* the entire NATO territory 北约领土 and NATO defense plans 防御计划.

[.my2]
当然，虽然我们有共同利益, 为乌克兰提供最好的安全保证和安排，但与此同时，我们也必须照顾到整个北约领土和北约防御计划。

And certainly, uh, without *going too much into* detail, the defense plans rely on 依赖于, uh, the capabilities of the allied countries 盟国. Um, and for instance, Finland having 1,340 kilometers of border with Russia, *even though* 尽管，虽然 we are the fifth biggest contributor to Ukraine's military assistance 军事援助, it's very unlikely that we will be the ones 后定 sending all of our troops over, and that's not even required (a.)必需的，规定的；理想的. Yeah, well, I guess that's understood by everybody.

[.my2]
当然，在不深入细节的情况下，防御计划依赖于盟国的能力。例如，芬兰与俄罗斯有1340公里的边界，尽管我们是乌克兰军事援助的第五大贡献者，但我们不太可能派遣所有部队过去，这甚至不是必要的。是的，我想这是每个人都理解的。

主题：乌克兰的军事需求与欧洲的应对 +
But there's a lot. It's not even so much _the boots on the ground_ 地面部队. Let's face it, Ukraine has probably the most capable army 最有能力的军队 in Europe *as we speak* 就在我们说话的这时候, and its size is tremendous 巨大的. `主` The capabilities 能力 that Ukraine needs for their aid 援助 now and in the future `系` is not just that.

[.my2]
但问题远不止地面部队。说实话，乌克兰目前拥有欧洲最有能力的军队，规模也非常庞大。乌克兰现在和未来所需的援助不仅仅是这些。

While I say this, I have no disregard (v.)忽视 whatsoever  任何，无论什么 for the UK and France's plans to do that. As _the coalition of the willing_ 自愿联盟, we will figure out 找到答案，解决 the best package 方案 of different capabilities 能力；功能；性能 and then work based on that.

[.my2]
虽然我这么说，但我对英国和法国的计划没有任何轻视。但作为志愿联盟，我们当然会找出不同能力的最佳组合，然后在此基础上开展工作。”

主题：美国立场与跨大西洋关系 +
If the US says no, its current position is "Europe, go do it yourself." I would say _that's very unfortunate_ 不幸的 if that happens. But still, I think it's unlikely 不太可能 because it's very much in the US interest to have a stable 稳定的 Europe. Certainly, if *viewed (v.) from* a business angle 商业角度, 40% of the trade 贸易 in the world is transatlantic 跨大西洋的. So, why sacrifice (v.)牺牲 that? There's a lot to gain (v.) from the stability 稳定 and prosperity 繁荣 of the free world, which all of us *have gained massively 大量地 from*. I know America traditionally, and *at the end of the day* 归根结底，最终, it's the American people who decide. If somebody 使动 has freedom written (v.) on their hearts, it's the American people. So, I'm sure they will stick with 坚持 Europe.

[.my2]
我知道美国历来如此，归根结底，是由美国人民来决定的。如果有人真的把自由写在他们的心上，那就是美国人民。所以我确信，归根结底，他们会支持欧洲。


段落：冻结俄罗斯资产的讨论 +
*You put yourself firmly on the side of* those 后定  saying take the frozen 冻结的 Russian assets 资产 and use them for the benefit of Ukraine. Do you think _there's a lot of support_ behind that? Europe has been very divided 分裂的 on that in the past. The damage that Russia has caused, if counted (v.)计算（或清点）总数 in euros or pounds or dollars, is roughly 大约 500 billion 十亿 euros.

We're talking about _frozen (a.) assets_ of the magnitude 规模;震级；大小；数量，数值;星等；星的亮度 of 200 billion. Typically 通常, you would consider _war reparations_ (赔款)战争赔偿 for the aggressor 侵略者 *to have to pay* 必须付钱 at some point 在某个时间点. Surely, there would be a legal way 合法途径 of using those assets. You wouldn't even have to 你甚至不需要 confiscate (v.)没收，查抄（某人的财产）；充公，罚没 those if that's a political obstacle 政治障碍. I wouldn't see an economic downside 经济负面影响 to this. Property rights 财产权 are extremely important in any market economy 市场经济, and certainly here in the Free World. But surely, if you are *engaged in* a war of aggression 侵略战争 against us, then there's also interpretation 解释 in international law 国际法 that your property rights probably aren't the same.

[.my2]
你坚定地支持那些主张冻结俄罗斯资产并将其用于乌克兰利益的人。你认为这背后有很多支持吗？欧洲过去在这个问题上一直存在很大分歧。俄罗斯造成的损失，如果以欧元、英镑或美元计算，大约为5000亿欧元。我们谈论的是规模约为2000亿的冻结资产。通常情况下，你会考虑让侵略者在某个时候支付战争赔偿。当然，使用这些资产会有合法途径。如果这在政治上是一个障碍，你甚至不需要没收这些资产。我认为这不会带来经济上的负面影响。财产权在任何市场经济中都极为重要，特别是在自由世界。但如果你对我们发动侵略战争，那么根据国际法的解释，你的财产权可能就不一样了。

[.my1]
.案例
====
- confiscate -> con-, 强调。-fisc, 篮子，钱篓，词源同 basket,fiscal.
====


==== 段落：美国的制裁与武器供应问题 +

Let's come to wider questions now. I've got many more, but let's start here in the front. The microphone will *come around* 来临. If you could say who you are, please.

I'm Edward Lucas, and I'm one of the authors of _the proposed 被提议的，建议的 real bank_. But my question is actually 实际上，事实上；（用于开始新话题）其实 on something different. You said _the worst thing that can happen_ is that the Americans relax (v.)放松 their sanctions 制裁. I think it could get worse than that. There are people in Washington who say Russia should have a _free hand_ 自由行动;自由支配的权力,或自由行动的机会 in Europe, that they want to win Russia as a friend against China, and they even say that they don't want American-made weapons 美国制造的武器 used in what they call a border skirmish (小冲突，小规模战斗；小争论)边境冲突 with Russia. So, where does that leave _countries like you_ when *you've placed a huge bet 巨大赌注 on* buying the JASMs, the vital  至关重要的，必不可少的 deterrent missile 重要威慑导弹 that you have, and ordering the F-35? If you try and use these American weapons /and a sign 符号；记号 *comes up* saying "_software update_ needed" and they don't work?



[.my2]
现在让我们转向更广泛的问题。我还有很多问题，但让我们从前面开始。麦克风会传过来。请介绍一下你自己。 +
我是Edward Lucas，我是拟议的“真实银行”的作者之一。但我的问题实际上是关于另一件事。你说最糟糕的事情是美国人放松制裁。我认为情况可能比这更糟。华盛顿有些人说俄罗斯应该在欧洲自由行动，他们希望赢得俄罗斯作为对抗中国的朋友，甚至说他们不希望美国制造的武器用于他们所谓的与俄罗斯的边境冲突。那么，当你已经购买了JASM这种重要的威慑导弹，并订购了F-35时，这对你这样的国家意味着什么？如果你试图使用这些美国武器，却出现“需要软件更新”的提示，导致武器无法使用？



==== 段落：欧洲作为贸易伙伴的优势 +
I'm more than convinced 深信 that America is *not only* #interested in# _the future of the Free World_ *but also* #in# the future of the arms industry 军火工业. And again, the business ties 商业联系 with Europe as well.
Europe certainly, as a trading partner 贸易伙伴 and as a market 市场, if only looking at from the economic perspective 经济角度, is not only much bigger, but also so much more reliable 可靠的 than anything that Russia can offer, whose size is _a tenth_ 十分之一 of our GDP 国内生产总值. Also, `主` the experience  经历，往事；经验 of companies 后定 trying to operate 运营 in Russia in the past 20 years `谓` has been quite a _roller 滚筒 coaster_ (航行于沿海港口间的轮船;玻璃杯垫) 过山车般起伏.

[.my2]
我深信美国不仅关心自由世界的未来，也关心军火工业的未来。当然，还有与欧洲的商业联系。欧洲作为一个贸易伙伴和市场，如果仅从经济角度来看，不仅规模更大，而且比俄罗斯能提供的任何东西都可靠得多，俄罗斯的规模只有我们GDP的十分之一。此外，过去20年试图在俄罗斯运营的公司的经历, 也相当起伏不定。



==== 段落：芬兰的冬季战争经验与安全思维 +
Thanks, James. Thank you, Bran. Good morning, Minister. My name is James Nixie. I run the Russia and Eurasia program 俄罗斯与欧亚项目 here at Chatham House. Minister, you've talked a lot this morning about the Finnish experience. The Finns know Russia. Could you elaborate 详细说明 a little bit more on the specific experiences of the 1939 to 1940 Winter War and how that has affected your present-day security thinking 安全思维? Thank you.
It indeed still has a massive influence 巨大影响 on how we see the world. In the Winter War, where we were illegally invaded 非法入侵 by Russia, but fended the aggression off 击退侵略, we had to give up some territory 领土 for our independence 独立. It certainly taught us the lesson that we simply have to invest into our own defense 防御 and deterrence 威慑. During the Winter War, nobody came to Finland's help. The Finnish mindset 思维方式 has always been that we can do this alone, which is not the best scenario 最佳情景, but also probably not the most realistic one in this world. That was very much in the mindset of people who thought that we would need NATO. It wasn't that Finland would have been against NATO, whilst we had not for a very long time not joined NATO or applied for membership 成员资格. That certainly changed with the full-scale invasion 全面入侵 of Ukraine. Finns take pride 自豪 in saying that we can pull our own weight 尽自己的一份力 and we have. Even though the country is fairly small, we have one of the strongest reservist-based armies 基于预备役的军队 in Europe. We also like to think that we are net contributors 净贡献者 to NATO, which we are. The reason, together with Sweden, we wanted to join was not only to improve our own security 安全, but also to contribute to the prevalence 盛行 of our values 价值观. Because essentially, the European way of life 欧洲生活方式 is what is at stake 处于危险中 now.

==== 段落：美国网络防御的撤出与担忧 +
Thank you. May I come here in the front, right in the front? Yes, thanks. Thank you very much. Isabelle Hilton, journalist 新闻记者. Over the weekend, Mr. Heus, the US defense secretary 国防部长, ordered (v.) the Pentagon 五角大楼 to cease (v.)停止 aggressive (a.)好斗的，挑衅的 cyber operations 网络行动 against Russia. This _at a time_ when Europe and all of us are experiencing 经历；感受到 all manner 方式；方法 of gray zone warfare 灰色地带战争 and cyber attacks 网络攻击 from Russia. How do you explain this, and *how concerned (a.v.)关心的，挂念的,使忧虑，使担心 are you* about this withdrawal 撤出 of an effective defense 有效防御 of us allies against a constant (a.)持续不断的，经常发生的；恒定的，不变的 gray zone warfare?

Well, of course, I'm a little bit concerned (a.), but I would imagine this is probably _part (n.) of this grand strategy_ 大战略 that the White House 白宫 has chosen, which is to see if this _course of action_ 行动方针 can lead to peace. Effectively appeasing (v.)安抚,平息 Russia and putting some pressure on Ukraine. In my personal view, it should be exactly *the other way around* (倒过来；从相反方向)情况应该恰恰相反. But I'm sure that President Trump and his team will notice *in due (a.)适当的；恰当的；合适的 course* 在适当的时候 that this probably doesn't work.


[.my2]
====
谢谢，James。谢谢，Bran。早上好，部长。我是James Nixie，我在查塔姆研究所负责俄罗斯与欧亚项目。部长，您今天早上谈了很多关于芬兰的经验。芬兰人了解俄罗斯。您能否详细说明1939年至1940年冬季战争的具体经历，以及它如何影响了你们当前的安全思维？谢谢。

冬季战争确实对我们如何看待世界产生了巨大影响。在那场战争中，我们被俄罗斯非法入侵，但成功击退了侵略，我们不得不放弃一些领土以换取独立。这无疑教会了我们一个教训，即我们必须投资于自己的防御和威慑。在冬季战争期间，没有人来帮助芬兰。芬兰人的思维方式一直是我们可以独自应对，这当然不是最佳情景，但在当今世界也可能不是最现实的。这种思维方式在那些认为我们需要北约的人中非常普遍。芬兰长期以来没有加入北约或申请成员资格，并不是因为我们反对北约。但随着乌克兰的全面入侵，这种情况当然发生了变化。芬兰人自豪地说我们可以尽自己的一份力，我们也确实做到了。尽管国家较小，但我们拥有欧洲最强大的基于预备役的军队之一。我们也认为我们是北约的净贡献者，事实也是如此。与瑞典一起加入北约的原因不仅是为了提高我们自身的安全，也是为了为我们的价值观的盛行做出贡献。因为本质上，欧洲的生活方式现在正处于危险之中。
====

==== 段落：美国对俄罗斯的态度与和平策略 +
I just want *to take that point a little bit further* 就这一点话题再深入一点. Because I've been listening to many of the things you're saying, and many supporters of Ukraine would think, look, *that would be great* if this were the case 如果是这样的话. But it isn't. It isn't the view  观点，看法 that the US is taking. It isn't the approach 方法，态度. Do you have a view on 你对...有什么看法 why the US is trying *to bring Russia in from the cold* 从孤立中拉回(让俄罗斯摆脱寒冷)? I'm not guessing any motives 动机 behind that.

I think President Trump is truly following two objectives 目标, which I can fully agree with. The first one is finding peace for Europe and in Ukraine. The second thing is *having Europe pull its weight 尽自己的一份力量，承担应有的责任 better* what(因是 when it ) *comes to* 涉及到 security and defense.

[.my1]
.案例
====
pull its weight 是一个固定短语，意思是“尽自己的一份力量，承担应有的责任”。

having Europe pull its weight better (表语 - 动名词短语) +
what comes to security and defense. (定语从句，修饰 "what" ，但结构上有错误，应为 "when it comes to security and defense." 意为“在涉及安全和防御时”。错误原因：“what comes to” 结构不符合标准英语表达，“come to” 通常需要有一个明确的主语，而 what 在这里不能充当合适的主语。)
====

Our message is that appeasing (v.)平息，安抚；缓解 Russia has not helped in the past, and it probably doesn't help now either. So, let's work together on a strategy 策略 how we can *put an end to* this killing on the battlefield 战场 and especially targeting (v.) civilians 平民.

The last time I was in Ukraine, I was in Kiev in January, and I visited the Children's Hospital, the largest in Ukraine in Kiev, the Okhmatdyt one, which was hit by a Russian missile 导弹 last summer. I remember that situation vividly 清晰地 because I was on my way to the NATO Summit 北约峰会 in Washington, and then the news came that this missile had hit the Children's Hospital. So, I went to see it. It was devastating 毁灭性的 enough to see the building which had been destroyed partly. But the most devastating 毁灭性的，极具破坏力的；令人极为震惊的；令人印象深刻的 experience was to meet those children patients 病人，患者 who had perhaps lost (v.) limbs 肢体, who had lost family. Really to see the sorrow 悲伤 in their eyes. Those children, if somebody wants peace, it's those children who deserve peace.

[.my2]
看到部分被摧毁的建筑已经足够令人心碎，但最令人心碎的经历是见到那些儿童患者，他们可能失去了肢体，失去了家人。真正看到他们眼中的悲伤。

So, our message is that let's work together on a strategy which really brings peace to the people and especially to the civilians. Our suggestion to President Trump is also *as part of this process* 作为这个过程的一部分 to have Russia show (v.) good will 善意, for instance by bringing back those deported children 被驱逐的儿童. Russia has deported 20,000 children from Ukraine, taken them from their parents 把他们从父母身边夺走. A horrendous (a.)可怕的；惊人的 war crime 可怕的战争罪行. One of the worst things you can do in a war. So, let's start with that. I'm sure President Trump would agree that let's start with the children.


The second thing that Europe needs to do more, fully agreed. This has been the Finnish position *all along* 自始至终，一直. Our message to Americans is just that please, let's do this together. It takes some time, and things will work out 成功，顺利进行 well.

Thanks very much.

[.my2]
====
我想进一步探讨这一点。因为我一直在听您说的许多事情，许多乌克兰的支持者会认为，如果情况是这样，那就太好了。但事实并非如此。这不是美国所持的观点，也不是其采取的方法。您对美国试图将俄罗斯从孤立中拉回有何看法？我不是在猜测这背后的动机。

我认为特朗普总统真正在追求两个目标，我完全同意。第一个目标是为欧洲和乌克兰找到和平。第二个目标是让欧洲在安全和防御方面更好地尽自己的一份力。我们的信息是，安抚俄罗斯在过去没有帮助，现在可能也没有帮助。因此，让我们共同努力制定一个策略，如何结束战场上的杀戮，特别是针对平民的行为。

我上次在乌克兰是1月份在基辅，我参观了乌克兰最大的儿童医院Okhmatdyt，去年夏天它被俄罗斯导弹击中。我清晰地记得当时的情况，因为我正在前往华盛顿参加北约峰会的路上，然后传来消息说导弹击中了儿童医院。所以我去看了。看到部分被摧毁的建筑已经足够令人心碎，但最令人心碎的经历是见到那些儿童患者，他们可能失去了肢体，失去了家人。真正看到他们眼中的悲伤。如果有人想要和平，那就是这些孩子，他们值得拥有和平。所以，我们的信息是让我们共同努力制定一个真正为人们带来和平的策略，特别是为平民。我们对特朗普总统的建议也是这一过程的一部分，即让俄罗斯表现出善意，例如带回那些被驱逐的儿童。俄罗斯从乌克兰驱逐了2万名儿童，将他们从父母身边带走。这是一项可怕的战争罪行，是战争中最恶劣的行为之一。所以，让我们从这一点开始。我相信特朗普总统会同意让我们从孩子们开始。欧洲需要做更多的事情，这一点完全同意。这一直是芬兰的立场。我们对美国人的信息是，请让我们共同努力。这需要一些时间，但事情会顺利解决的。
====


==== 段落：联合国决议后的全球局势与美国的合作 +

Here in the third row 一排，一行, you'll need it. It's online.

My name is J, and I'm a member of Chatham House. *In the wake of* 在…之后；随着……发生 the UN resolution 联合国决议 where the US and Russia voted together, the global picture 全局图景 of NATO 北约 is under a cloud 蒙上阴影 now. Focusing on a smaller subject which is that of the Ukraine situation, I ask _what can the willing *expect (V.)期待；预计；要求，指望； from* the United States_ *in terms of* 就…而言；从…角度来看 cooperation 合作 [to their cause 原因；事业；理由] in that _particular part of the world_? *Does anything remain (v.) in place* in the light of 鉴于 the recent decisions by the US government? Thank you.

[.my2]
在第三排这里，你需要它。是在线的。 +
我是J，查塔姆研究所的成员。在联合国决议之后，美国和俄罗斯一起投票，北约的全球形象现在蒙上了阴影。聚焦于乌克兰局势这一较小的话题，我想问，美国在这个特定地区的合作中，自愿者能期待什么？鉴于美国政府最近的决策，还有什么仍然存在吗？谢谢。

Well, again, I think this incident 事件，事故；（两国间的）冲突，严重摩擦 at the UN the other week `系` was an extraordinary (a.)意想不到的；令人惊奇的；奇怪的;不平常的；不一般的 moment. Twice *voting (v.) against* Europe on a matter of European security for the first time since 1945. I guess it's also linked to this strategy which President Trump probably has *in terms of* 就……而言；从……角度来看 simply *putting* his entire weight 全部力量 and certainly all his cards 所有筹码 *on* getting a peace deal. Certainly, it could sound logical that in order to achieve that, you would try to get the entire world *on board* 支持;加入团队;在船上（或飞机上、火车上）, also those countries 后定 who typically aren't your allies 盟友. This is the only way I can explain this to myself.

Certainly, I think it was also a powerful message that _the general assembly 议会，代表大会；集会 vote_ was so strongly *in favor of* _Ukraine_ and _European security_ and especially _the UN Charter_ 联合国宪章 which this *at the end of the day* 归根结底，最终 is about. Because *we haven't spoken so much about* how this space *is actually being watched* everywhere in the world. If we allow for *moving borders* with the use of force 武力 or *subjugating (v.)征服 another country* or *taking away its sovereignty* 主权 by the use of force or by threatening (a.)威胁（性）的，恐吓（性）的 force, then certainly we can forget (v.) about the entire _UN Charter_.

[.my2]
我认为，上周在联合国发生的事件是一个非同寻常的时刻。自1945年以来，美国首次在欧洲安全问题上两次投票反对欧洲。我想这与特朗普总统的策略有关，他可能把所有力量都押在达成和平协议上。当然，为了达成这一目标，试图让整个世界参与进来，包括那些通常不是盟友的国家，这听起来是合乎逻辑的。这是我唯一能解释这一点的方式。 +
当然，我认为联合国大会投票如此强烈地支持乌克兰和欧洲安全，特别是联合国宪章，这也是一个强有力的信息。因为我们没有太多谈论世界各地如何关注这一空间 (因为我们还没有讲太多关于这个空间实际上是如何在世界各地被监视的。)。如果我们允许通过武力移动边界或征服另一个国家，或者通过武力或威胁武力剥夺其主权，那么我们当然可以忘记整个联合国宪章。


==== 段落：对乌克兰的军事援助与美国的暂停 +

We know that military exports (n.)军事出口 to Ukraine have been suspended 暂停. Does stalling 拖延 still available, or has that been cancelled too? We are due (a.)预定；预期；预计 to find out all those details. Certainly, what is also important is that the US has the possibility to continue providing that aid 援助 also very soon. So, we're talking about the suspension 暂停，中止, I guess. I'm convinced (a.)确信的，信服的；坚信不疑的 that *this is linked to* President Trump trying (n.) to have the minerals deal 矿产协议 with Ukraine /and some sign 迹象，征兆 that he expects (v.) Ukraine would be willing (a.) to approach (v.) some sort of a peace deal.

[.my2]
我们知道对乌克兰的军事出口已被暂停。拖延是否仍然可行，还是也被取消了？我们即将查明所有这些细节。当然，同样重要的是，美国有可能很快继续提供援助。所以，我想我们谈论的是暂停。我相信这与特朗普总统试图与乌克兰达成矿产协议, 以及他希望乌克兰愿意接近某种和平协议的迹象有关。


==== 段落：英国在欧盟防御中的角色 +

You're here, John Pete, from The Economist. You mentioned the UK a number of times, and you also said quite a lot about the EU building a bigger role in defense 防御, including in defense procurement 国防采购 and possibly defense spending 国防开支. Not all members of the EU, one in particular, share the idea that the UK should be more closely involved if it's an EU matter. Do you think there will be a way found of including the UK even though it's not a member of the EU and not a member of the single market 单一市场? And do you think it would be sensible 明智的 to build a bigger EU defense role without the UK?
I don't think it makes any sense to do anything in relation to security and defense without the UK. If you ask me, Finland would be more than happy to have the UK back in the single market and in political decision-making 政治决策 in the European Union. To get some sense back, a little bit exaggerating, but we have always been very like-minded countries 志同道合的国家 and think very similarly, for instance, what comes to the freedom of trade 贸易自由, the need to really base everything we have on the as free as possible market economy 市场经济, and at the same time also make sure that we have militarily and politically the weight 分量 that we deserve as Europe in the world. Certainly, this time really calls for not really innovations 创新 as such, but resolve 决心 and strong alliances 强大联盟. The UK and also the leadership that Prime Minister Starmer has shown is more than welcome. Also, I should add, those countries like Norway, Iceland, Turkey, it's not just the European Union. Everybody who wants to join in this effort, it's effectively about protecting the Free World. So, everybody who wants to do that should be invited.


[.my2]
====
你是《经济学人》的John Pete。你多次提到英国，也谈了很多关于欧盟在防御方面建立更大角色的事，包括国防采购和可能的国防开支。并非所有欧盟成员国，特别是其中一个，都认为如果这是欧盟事务，英国应该更紧密地参与。你认为即使英国不是欧盟成员，也不是单一市场成员，是否会找到一种方式将其包括在内？你认为在没有英国的情况下建立更大的欧盟防御角色是否明智？

我认为在没有英国的情况下做任何与安全和防御有关的事情都没有意义。如果你问我，芬兰会非常高兴让英国回到单一市场和欧盟的政治决策中。稍微夸张一点，但我们一直是志同道合的国家，思考方式非常相似，例如在贸易自由、需要将我们所拥有的一切建立在尽可能自由的市场经济基础上，同时确保我们在军事和政治上拥有作为欧洲在世界上的分量。当然，这个时代真正需要的不是创新，而是决心和强大的联盟。英国以及首相斯塔默所展现的领导力是非常受欢迎的。我还应该补充说，像挪威、冰岛、土耳其这样的国家，不仅仅是欧盟。任何想加入这一努力的人，实际上都是为了保护自由世界。所以，任何想这样做的人都应该被邀请。
====

==== 段落：加拿大与欧盟的合作可能性 +
Yeah, I'm just going to take one from online, from Christina Dorsi, who's a Canadian living in Kazakhstan, Chatham House member, glad to have you. And she says, what are the realistic chances of Canada joining with the EU in some kind of way, in this kind of support of either European values 欧洲价值观 or of Ukraine?
Absolutely, and why not the European Union too? I mean, again, I think in this effort, we need the coalition of the willing. This is not really anything new. This is how the aid to Ukraine and also our sanctions have functioned thus far. For instance, the sanctions that we have imposed on Russia have not only been the G7 or the EU sanctions, but well, the G7, that says it all. It's not just the EU, of course. The UK has been extremely active in fighting Russia's shadow fleet 影子舰队, which is a massive problem in our neighborhood here. Effectively, a massive threat to the environment 环境 to start off with, but also like we've experienced also a threat to critical infrastructure 关键基础设施, undersea cables 海底电缆, and so on here on the Isles.

[.my2]
====
是的，我要从网上选一个问题，来自Christina Dorsi，她是一名住在哈萨克斯坦的加拿大人，查塔姆研究所的成员，很高兴有你。她说，加拿大与欧盟以某种方式合作，支持欧洲价值观或乌克兰的现实可能性有多大？

当然，为什么不呢？我的意思是，再次，我认为在这一努力中，我们需要自愿联盟。这并不是什么新鲜事。因为这是迄今为止对乌克兰的援助和我们的制裁的运作方式。例如，我们对俄罗斯实施的制裁不仅仅是G7或欧盟的制裁，而是G7，这就说明了一切。当然，不仅仅是欧盟。例如，英国在打击俄罗斯的影子舰队方面非常积极，这是在我们这里的一个巨大问题。实际上，首先是对环境的巨大威胁，但我们也经历了对关键基础设施、海底电缆等的威胁。
====

==== 段落：冻结俄罗斯资产与和平前景 +
Gon member of Chatham House, Minister, the question I, there are so many questions to ask, but I choose one in relation to what you stated earlier that $750 million Russian asset which have been frozen for some time. You claim to pay for the reparation 赔偿 of the war to seize them and pay as reparation for the damage caused by Russia. Now, are you seriously considering there will ever be peace between Russia and Ukraine with the current situation taken effect now by the European nations?
I'm not sure if I understood the question, but if there's a, I, there really briefly, the question is, are you seriously considering that Russia will allow you to seize the funds they have and then subsequently to have a peace with them or and will they return the lands they seized?
Well, that's a very important question indeed. So far the damage that Russia has caused in Ukraine, in monetary terms 货币价值, if we just forget about all the lives lost, which is of course the most horrendous bit of this war, but the economic damage is around 500 billion euros so far. The frozen assets which Europe holds or which are more or less in the European Union is 200 billion. I guess, based on international law 国际法 and its interpretation, and in what is also being used for the sanctions legislation 制裁立法 which we have in place, so effectively as a countermeasure 反制措施 against Russia's illegal war of aggression 非法侵略战争, then certainly there's also a legal way to seize those assets now and especially in the future, or conditional to further aggression by Russia. This all can be figured out. But what is important is that the killing stops, that we get to peace, that's what certainly Ukraine and Europe want, but also that there's accountability 问责 to the war of aggression and towards the aggressor.

[.my2]
====
查塔姆研究所的成员，部长，我有很多问题要问，但我选择了一个与你之前提到的7.5亿美元俄罗斯资产有关的问题，这些资产已被冻结一段时间。你声称将其扣押并作为对俄罗斯造成的损害的赔偿。现在，你是否认真考虑过，在当前欧洲国家采取的措施下，俄罗斯和乌克兰之间是否会有和平？

我不确定我是否理解了这个问题，但如果有一个，我简要地说，问题是，你是否认真考虑过俄罗斯会允许你扣押他们的资金，然后与他们达成和平，或者他们会归还他们占领的土地？

这是一个非常重要的问题。到目前为止，俄罗斯在乌克兰造成的损害，以货币计算，如果我们忽略所有失去的生命，这当然是这场战争中最可怕的部分，但经济损失大约是5000亿欧元。欧洲持有的或基本上在欧盟内的冻结资产是2000亿。我想，根据国际法及其解释，以及我们现有的制裁立法，作为对俄罗斯非法侵略战争的反制措施，那么当然也有法律途径可以扣押这些资产，特别是在未来，或者以俄罗斯进一步侵略为条件。这一切都可以解决。但重要的是，杀戮停止，我们实现和平，这当然是乌克兰和欧洲想要的，但也要对侵略战争和侵略者进行问责。
====

============


Let's get in one, one or two more.

Yes, here the third, yes, you, yes, you go microphone.

Uh, Phil Goff, New Zealand High Commissioner.

Um, I was rereading Churchill's speech to the House of Commons in 1938 after the Munich Agreement, and he turned to Chamberlain, he said, um  "You had the choice between war and dishonor.

You chose dishonor, yet you will have war."

President Trump has restored the bust of Churchill to the Oval Office, but do you think he really understands history? I will limit myself to saying that in this time, uh, and I did it myself, I, I quoted Sir Winston Churchill, and I think, uh, he has made very, um, timeless remarks.

Thank you.

Thank you both on that.

Am in the front here.

Thank you, thank you very much, Minister.

Arma van Rij, I head up the Europe program here at Chatham House.

Thank you for making the time for us.

Um, you described the challenge for Europe as essentially being twofold.

One, maintaining support for Ukraine and enabling, enabling them as much as they can to deter Russia.

And the second is to restock and rearm Europe themselves for their defense.

Um, even if the European Commission is successful in all its initiatives that it's planning, even if on a national level country's plan for rearmament, we still face a situation where stocks are depleted, and it takes time for those initiatives to bear fruits, five, seven, 10 years, if not longer.

So, what do we do in the short term? What's the kind of beyond pressure on Russia through sanctions, etc.?

What do we do in the short term right now? Um, well, during the Second World War, um, and certainly in, in history, there have been times when, um, if there's a massive need to ramp up the defense industry, then it can happen also pretty quick.

Um, but, um, we are not at the phase where we need to be panicking or anything.

That's, that's not the thing.

But we certainly have to, to make room for also private investment into the defense industry.

Because this is not only something which the taxpayers have to be funding.

On the very contrary, uh, I guess, and this very much applies to the European Union, um, we should recognize that funding, um, a strategic defense industry, uh, is within the sustainability goals of our societies.

Um, unlike, uh, in some of the regulation we had imposed prior where defense defense industry was considered contrary to ESG.

So, letting go of that.

At the same time, also through the EIB, making room for, uh, investments into the defense sector is important.

Because that will also, um, send a message to, uh, private both equity and, and debt investors to, to participate in the effort.

And I'm sure there's a lot of private interest around.

Because of course, investors see that the demand is there now, and it's going to be there in the future.

So, we just need, um, a better strategy for that.

And what the European Union is doing now, there will be, um, in two weeks' time, the white paper and defense coming out, which will focus on exactly this.

But of course, we need public funds for that too.

But, but this will be an effort which certainly, uh, we will be able to do to.

But it's a very important, uh, remark that you're making.

Because, uh, it's not sufficient if we only raise our defense spending.

Because if we end up just, you know, paying for massive inflation on goods which are not there on military goods, then it doesn't help so much.

So, instead of focusing only on the share of GDP, uh, that defense spending, um, is, is, um, or how high that is, uh, we should certainly focus on the GDP and its growth as well.

So, competitiveness of Europe and, and including the UK, if you ask me.

Uh, and the second thing is, is that we truly are able to produce those capabilities, uh, along with NATO's capability targets and not just, uh, you know, a share of spending.

I'm going to squeeze in two questions on NATO that are online with apologies to the many hands that have been going up in, in, in the hall.

Uh, and the two questions are, one, can you just tell us a bit about how integrated Finland now is, uh, in NATO, um, in this short time you've had? And the second one of whether Turkey has a useful role to play in this.

This is Shamana Salah, um.

Turkey, obviously member of NATO.

Uh, on the other hand, as its finance minister has said in public at Chatham House, not observing the sanctions because it can't afford to and doesn't suit it.

So, what do you, what do you think of one more descriptive one and and then your view on Turkey? Well, Finland, um, had been 30 years, um, a peacetime partner of NATO, and our military was almost 100% interoperable with NATO on the day we joined.

So, in, in that respect, um, we were partly already in there.

And now that we have been, been using these two years together with Sweden to really integrate into, uh, NATO command structure and also ramping up our capabilities, which were, I must say, good in to start off with, but, but still to, um, really integrate also in, in NATO's defense planning, I think we've come a very long way in these few years.

And of course, Finland has also been, uh, participating in, in NATO's presence, um, in places where, where there's need for it, for instance, in Romania and Bulgaria last, last year and Iceland this year.

And, and, um, and yeah, so I think, uh, we are proud proud member of NATO.

What comes to Turkey, uh, they certainly have an interest in, um, peace and stability in Europe too.

And I'm more than convinced that they are willing and able to do their bit.

And I think they are u a fantastic, uh, partner and ally to the coalition of the willing.

And I'm so glad that also Prime Minister Sunak invited Turkey here on Sunday to this gathering.

With that, we are going to have to stop.

It's not as if the questions are stopping, and this is going to be, um, so much part of what Chatham House is talking about in the coming days and weeks.

But for now, you join me in thanking the minister for…








'''


== pure

==== 主持人开场

Very warm welcome to Chatham House. I'm Bronwen Maddox, the director, and I'm delighted to have here this morning Elina Valtonen, Foreign Minister of Finland.

Start getting your questions ready! Just a few housekeeping things—this is on the record, it is being recorded, and it is being live-streamed. We have television cameras here as well, taking a feed.

Let me say just a few things before the minister makes her opening remarks. We are obviously in extraordinary times, and she has a biography that could not be better placed to talk about all these issues.

She is a fourth-term member of parliament, Deputy Chair of the National Coalition Party in Parliament. She has served as Vice Chair of the Foreign Affairs Committee and has been a member of the Defense Committee, the Finance Committee, and the Grand Committee. Additionally, she has chaired the Finnish delegation to the NATO Parliamentary Assembly.

Before that, she worked in the private sector in various countries, including ten years in the financial sector in Copenhagen and London. She is also a former computer programmer, which I found interesting to read. Furthermore, she has been involved in setting up various growth companies and is an author of a best-selling book about some of the issues we are likely to be discussing today.

So, she has the perfect background to talk about all of this! Please, get your questions coming. We are given, by the hour—by the minute—more things to talk about.

But for the moment, Minister, welcome. Thank you very much indeed! We look forward to your opening remarks before we start deluging you with questions.

==== 芬兰外长开场演讲

Thank you so much, Bronwen. It’s great to be here.

I must say, I don’t think anybody has the perfect background for the times we live in. But certainly, I will give it a try!

Ladies and gentlemen, it is a true privilege to see you all here today and to address Chatham House in this historic setting, where great ideas and solid principles shaping global affairs have long been debated. I am honored to contribute to this essential conversation.

And if not today, when great ideas and solid principles are needed—then when?

Today, I would like to speak to you about security, the future of Europe, and Ukraine. I will focus on European support for Ukraine, the pathway to sustainable peace, and how to strengthen the role of Europe in writing the next chapter of the Free World.

One thing we can say for sure is that we in Europe have a unique opportunity to take ownership of our own future. This is not to say that we would do it at the cost of our transatlantic ties. On the contrary, by starting to better pull our own weight, we strengthen the partnership so crucial to both sides of the Atlantic.

We Finns don’t usually like to make a big deal of ourselves, but on this matter, I must depart from tradition and say that defense and security are topics we truly know something about. Our history has taught us not just how to survive, but how to defend what we hold dear.

==== 乌克兰战争与欧洲的责任

Russia’s war of aggression against Ukraine shattered the post-Cold War ideals of stability in Europe. That aggression started more than ten years ago with the illegal annexation of Crimea. Now, Ukrainians have fought a full-scale war for three long years and continue to fight for their right to live as an independent nation, free from oppression.

Let us be clear: Ukraine is not only fighting for its own survival—it is fighting for all people’s right to choose and to be free.

Finland stands with Ukraine now. Finland will continue to stand with Ukraine in the future. Compared to the size of our GDP, Finland is Ukraine’s fifth-biggest supporter. We are in constant contact with the Ukrainian government and armed forces to ensure that our support continues to meet their immediate needs and is made available without delay.

On top of that, we are actively enhancing Ukraine’s long-term strategic resilience. We explore new means and mechanisms, including support for Ukraine’s own defense industry. Ukraine’s rapid innovation in drone warfare is a testament to their defense forces’ resolve, and we must ensure that they have the industrial capacity to maintain this edge.

The pledge of long-term security assistance for Ukraine, announced at the Washington NATO Summit last summer, is one of the key elements in our commitment. We must make sure that the alliance delivers on this pledge.

====欧洲的领导角色

Ladies and gentlemen, now is the time for European leadership.

The day before yesterday, your Prime Minister brought together an important and timely leaders' meeting here in London, accelerating our efforts to support Ukraine and to seek a just and lasting peace. Europe has momentum, and we will use it.

The day after tomorrow, the European Council will convene on the initiative of Finland’s Prime Minister Petteri Orpo. I expect that the meeting in Brussels this week will deliver concrete and sizable commitments for additional EU support to Ukraine, as well as take decisive steps toward strengthening European defense—or "rearming Europe," as the President of the European Commission has phrased it.

We have reached a point where decisions must not be symbolic. They must be consequential.

Let me be absolutely clear: if we do not act now, we will pay a far greater price later. There can be no sustainable peace in Ukraine without a strong and sovereign Ukraine. This is not just a political reality—it is a moral imperative.

==== 如何应对俄罗斯的威胁

Rushing to a deal at the cost of its content and without due consideration of the consequences would endanger not only Ukraine but also Europe—and, by extension, the United States—for generations to come.

We Finns know Russia. Russia shares a land border with fourteen countries, but only one of them has remained a continuously independent democracy through the Second World War and the Cold War—and that’s Finland.

History has taught us that Russia respects only strength and resolve. Russia’s current war is based on imperialistic ambitions that go beyond Ukraine. The Kremlin’s appetite does not diminish when fed—it only grows.

Take it from us: whatever happens in this war, Russia will remain a long-term strategic threat to Euro-Atlantic security. Rather than encourage it, we need to keep it at bay.

Of course, we need to be open to re-engagement in the future—if Russia starts to adhere to international law again. But going forward, it would be a mistake to let go of our deterrence or to rebuild strategic dependency on Russia. This applies to all of Europe.

So far, we have not seen any sign that President Putin has any genuine will to negotiate a lasting agreement. On the contrary, just a week ago—on the third anniversary of Russia’s invasion—Russia launched its largest drone attack on Ukraine. That is not what you would expect from someone who is truly interested in peace.

There is no reason whatsoever to believe that Putin has moderated his demands from those he laid out in December 2021—demands that, if accepted, would roll back decades of progress in European security.

Caving to these demands would expose Europe to further aggression. Instead, our objective must be a just and lasting peace that respects international law, including the prohibition of annexation of territory through the use of force.

==== 结语

Let me emphasize: peace does not—and must not—mean submission. True peace is built on justice, accountability, and deterrence.

We must not mistake a temporary pause for a sustainable peace. If in doubt, ask the Baltic states what kind of "peace" it was to live under Russian—or, back then, Soviet—occupation.

To secure a peace that can last, Ukraine needs a strong deterrent against any future aggression. Without such guarantees, any truce or ceasefire is only an invitation for Russia to regroup and return.

We must not repeat the mistakes made with the Minsk agreements. The most credible security guarantee would be NATO membership for Ukraine.

Until then, and even thereafter, the required deterrence must be based primarily on Ukraine’s own defense forces, firmly supported by external assistance and credible security arrangements provided by Europe and the U.S.

In parallel, Russia’s position must be further weakened. Sanctions must be strengthened, and their implementation made more effective.


Russia's war economy is already showing serious cracks.

We must also find a way to use the frozen Russian assets, around 200 billion euros in Europe, to support Ukraine and compensate for the damage Russia's aggression has caused.

We Finns know from experience that Russia is a skillful but unreliable negotiator.

One of our foremost diplomats and later president, J.

K.

Paasikivi, was on several occasions on the other side of the table from Stalin and Molotov when our existence as an independent country was on the line in the 1930s and 1940s.

He summed it up like this: "The constant policy of the Russians is to get what they can with as little as possible and then come back asking for more.

They never sacrifice their immediate interests for future objectives.

They are immune to any ethical, human, or abstract legal factors.

" This is the Finnish experience.

The Ukrainians know from their own experience that Russia has broken every single commitment they have ever made on Ukraine's sovereignty.

No agreement with Moscow can stand without the will and the means to enforce it.

The merits of any agreement that may result from the talks that have been initiated between the US and Russia, or any group of countries for that matter, will not be judged on the day of the signing.

They will be judged every day thereafter to make sure that the deal is a good one.

The US will need Europeans.



Dear friends, history has shown that when Europe and the United States stand together, we are an unbreakable force for peace, security, and freedom.

Transatlantic partnership has historically been strong, and it must remain so.

President Trump is certainly right that we in Europe must do more for our own security.

But for both the US and Europe to succeed in bringing peace to Ukraine and strengthening transatlantic security, we must build peace through the strength of alliances.

This applies to security and defense, but also to the global economic and technological competition.

On the British Isles as well as on the European continent, we share the same concerns about the future.

We are determined to act so that we can shape that future rather than being shaped by it.



The UK's contribution to European security is not just historic, it is essential.

From both World Wars to the present day, Britain has stood firm when freedom has been at stake.

Prime Minister Sunak's recent commitment to increasing defense spending is a powerful and timely message.

It coincides with similar decisions across Europe.

We are stepping up together.

The EU and the UK have a GDP almost 10 times the size of Russia.

We have the means.

Whether we have the political will is a question of priority, and no priority is higher than keeping our citizens safe and free.

By doing more as Europe, we also show with actions our value as a trusted, indispensable transatlantic partner.



So, Winston Churchill once said, "To each there comes a moment when they are figuratively tapped on the shoulder and offered the chance to do a special thing, unique to them and their talents.

" This is Europe's moment.

We must rise to it.

I thank you so much for your attention.



[Applause]

Min, thank you very much indeed, um, for those remarks.

Very wide-ranging.

Let me ask you a few things, and then I will come to the wider questions.

Not yet, um, but, but well done, you, and well done, online, Raphael Morto, for firing a whole list.



So, Finland joined NATO two years ago, a bit less.

What is the alliance you think Finland has joined? Is it one that is going to stick by its Article 5 commitment? I'm sure that, um, NATO will stick to its Article 5, uh, commitment, and also the US.

Um, we have heard nothing which would be contrary to that.

Uh, indeed, um, President Trump and his administration have, um, have also ensured that they, they stick, uh, to NATO and its commitments.

And in any case, I, I guess Finland and its own history show that we never, um, relied on outside help anyway.

Um, we have always, um, put our own defense first.

And, um, again, we joined NATO only, only two years ago, um, together with Sweden.

And, uh, we know that, uh, well, we are net contributors to the alliance, and we would very much like to, uh, be that also, also in the future.

But having said this, it's very important that, uh, all of our European partners also step up in this.



What would you like to see from them? Finland is obviously making a, a much greater contribution to defense.

You've got now firm plans for 3.3% of GDP by 2032.

But that isn't where the whole of the EU is.

What would you like to see from them? I think the EU is already doing a tremendous, uh, job.

And, um, on their line, um, the commissioner president, um, she, um, published, uh, today, um, the ideas on, on how we as the European Union will be stepping up in terms of defense and deterrence.

Um, the commitment is there, and it will happen.

Um, everybody just has to understand that it takes some time.

Um, um, you can't build an army overnight, right? Uh, and, uh, we are, of course, um, happy to, to share the burden.

And, and I think the course of action which has been there in the past 3 years already is exactly the right one.

We just have to continue.

And I'm saying this because there's been so much Europe bashing in the, in the past, uh, weeks.

Uh, but I think what Europe has done is exactly the right thing.

We have aided Ukraine, we have put economic pressure on Russia, and we have, perhaps too slowly, but still, started as individual countries to ramp up our defense industries and our defense.



Do you think Europe can defend Ukraine on its own? We have now, uh, the US pausing, it's the Trump administration's word, pausing its aid, uh, to Ukraine, obviously an attempt to bring Ukraine to the negotiating table.

Can Europe fill that gap? Um, I think we need the Americans.

Uh, we need the Americans militarily, but especially also to keep up the sanctions pressure.

Because the worst thing that could happen now is that, um, the, the US, uh, lets go of the sanctions and starts engaging with Russia economically.

Because that would be exactly the wrong course of action now where we see that Russia's economy clearly is not sustainable as it is now.

They are allocating 8% or even more of their GDP, uh, into the war economy.

The inflation is well above 30%.

The domestic banking sector is in serious trouble, uh, with interest rates of, uh, also north of, uh, 20%, uh, even much, much higher for, for smaller businesses.

It's not sustainable.

So, if we just, you know, waited for at least some months, we would be in such a much better place.

And also, what has to be noted is that also on the battlefield, um, Russia has not really been advancing in the late, in, in the recent months.

Um, they have been advancing only very, or taking very small steps and, and at very heavy losses.

Um, so this definitely shouldn't be a moment where we give, give in, or especially not that we surrender Ukraine.

Because, well, um, that's certainly not something, um, what the Ukrainian people wanted to have for their future.

That is undeniably correct, and there are a lot of people, I suspect a lot of people here, who would agree with you.

But we don't have that time in that the US is, is very much, uh, changing the timetable of all this, separate from what is happening on the, on the battlefield.

President Trump says, um, President Putin wants peace.

Is he making a mistake? You've got, you've had some pretty tough words about what Russia wants over the years.

Well, look, um, I think President Trump is exactly right in demanding peace.

Who wouldn't want peace? But I guess the only one not wanting peace is Putin, who invaded in the first place.

So, um, you know, the, the analysis, um, just has to start at the, you know, uh, realization of, of the fact.

And, uh, and the thing is, I mean, if, if Russia started, started, uh, their peace now, they could do that by withdrawing, withdrawing their troops or at least stopping, uh, those heinous attacks on, on civilian infrastructure and on Ukrainian military.

Um, but if Ukraine did that, then probably you wouldn't have Ukraine any longer.



You, you put a lot of weight in the, in your remarks on the notion of sustainable peace, uh, which Europe wants.

Do you think the US has the same notion of peace? Well, our, our message to, to our friends in America is that, um, history will judge us, uh, by the developments after the signing of the agreement, not just that moment when any possible agreement is, is being signed.

And unfortunately, the experience we have as Europe from the Russians is that, um, especially now during Putin's rule, they, they are not willing to make any compromises.

They have only been advancing.

If you look at what, you know, in Georgia 2008, um, illegally annexing Crimea 2 14, um, then, uh, you know, the, the fighting in, in, in the Eastern parts of, of Ukraine, the Minsk agreements, agreements which agreed on ceasefire, but Russia violated the ceasefire almost immediately and just kept on advancing slowly but surely.

This is, in, in my view, absolutely right.

Yet, that was one of the points that President Zelensky put to, uh, President Trump in the Oval Office, and it didn't go so well after that point.

Um, do you think it's fair to say that we're dealing with an American administration that just sees it very, very differently? Um, I guess President Trump, um, well, it's difficult to, to know exactly how, how he sees the situation.

Um, and, uh, as said, it's easy to agree with the objective of, of finding, of finding peace.

Um, but I think what is important to realize is that this, you know, um, attempting to have a normal political and business with, with the Russians is exactly the course of action everybody was engaged in up until effectively 22, right, four years ago.

Europe was building a gas pipeline with Putin still.

I mean, less than four years ago.

So, this, you know, hoping for the best and engaging with the Russians, this was the mainstream course of action.

And only in the past three years have we individually, European countries, and this is also important, uh, to note, uh, to, to our friends in, in Washington.

I mean, Europe is not one country, right? So, we are making decisions individually.

Even as the European Union, it's a union of 27 sovereign nations.

But even so, in the past three years, democratically elected leaders have decided more or less on the same thing, that we must keep Russia at bay.

So, why not continue with this? It's only been three years.

And I was thinking as you were talking, I, I, I just want to explore your sense of what the European Union can do.

Because as you say, it is a group of many very different countries, some of them quite close to Russia, others, uh, very, very different view.

What do you think it can do as an organization, the, the EU itself, or are we, we really talking about coalitions of the willing to use K's phrase? I think, uh, this coalition of the willing thinking is exactly what we need.

And this is, uh, what it will, uh, end up with anyway.

And this is exactly what it's been the past three years.

Because of course, it's not just been the European Union.

It's been the UK.

It's been say Norway, Iceland, uh, also Turkey doing its bit, uh, and of course, the US and Canada.

So, uh, and, and of course, many, many of our, uh, partners in the, in the Indo-Pacific as well, who have, who have been on the right side of history in this.

So, I'm, I'm sure this, this will continue.

Um, uh, or I hope it will continue.

But also, as the European Union, we can do so much.

And I think these, uh, new arrangements for, for how to credibly and strategically, uh, ramp up our defense and our defense industries at the same time, uh, is exactly what we should be doing.

And now we're talking numbers which are also credible.

So, in total, say 800 billion.

Because let's face it, the European Union has also in the past been very powerful if faced with outside crisis.

In the Euro crisis, well, we can all have our own, uh, ideas, the making of it, yeah, whether it was the right thing to do.

Um, as a former banker, I have my own feelings about it.

But anyway, so we put a lot of money on the table, and the ECB did its bit.

And also during the COVID crisis, it was a package of 750 billion.

So surely, if, if we wanted to, we can do it.

And I, I guess this is an existential issue.

I just, I just like to just get your sense of how big the coalition of the willing, uh, is likely to be.

Because at the end of the Lancaster House talks, uh, there were only two clear members.

It seemed like the UK and, um, uh, and France.

The UK had not invited the, uh, some of the Baltic countries to that, which I think, I think is mystifying.

But anyway, the countries coming out and saying we will contribute, um, perhaps to fighting in, in Ukraine seems small.

How big do you think that group might get? Well, I think we are making a mistake if we only concentrate on, on, um, uh, the capabilities as defined in boots on the ground.

Because, uh, arranging, um, security guarantees or, uh, certainly in, in the using the wider term security arrangements for Ukraine, it's a combination of so many things.

Um, and of course, while it is in our common interest to, um, have the best security guarantees and arrangements possible for Ukraine, we must at the same time take care, uh, of the entire NATO territory and, and NATO defense plans.

And certainly, uh, without going too much into detail, the defense plans rely on, uh, the capabilities of the allied countries.

Um, and for instance, Finland having 1,340 kilometers of border with Russia, even though we are the fifth biggest contributor to Ukraine's, uh, military assistance, it's very unlikely that we will be the ones sending all of our troops over, and that's not even required.

Yeah, well, I, I guess that's understood by everybody.

But there's a lot, I mean, it's not even so much the boots on the ground.

I mean, let's face it, Ukraine has, has, uh, probably the C most capable army in Europe as we speak, uh, and, and its size is tremendous.

So, um, the, the capabilities that Ukraine needs for their aid now and in the future, uh, is not just that.

And while I say this, I, I have no disregard whatsoever for the UK and, and France's plans to do that.

Um, but as the coalition of the willing, we will of course figure out the best package of different capabilities and then, you know, um, work based on that.

And if the US says no, it's current position, Europe, go do it yourself.

Um, I would say that's, uh, very unfortunate if that happens.

But still, I think it's unlikely that it happens.

Because it's in very much in the US interest to, um, have a stable Europe.

Because certainly, if, if only viewed from a business, business angle, uh, 40% of the trade is, uh, basically in the world is transatlantic.

So, why sacrifice that? Um, and, uh, certainly there's, uh, uh, there's a lot to, to gain from, from overall, um, the stability and the prosperity of the free, free world, um, which, uh, all of us have, have gained massively from.

So also in that plus, um, I know, uh, from a well, um, America traditionally and, you know, at the end of the day, it's the American people who decide.

And, and if somebody, uh, wants to have, uh, or really has freedom written, uh, on, on their hearts, it's, it's the American people.

So, I'm sure at the end of the day, um, they will stick with Europe.

You put yourself in your remarks very firmly on the side of those saying take the frozen Russian assets, uh, and use them for the benefit of the Ukraine.

Um, do you think there's a lot of support behind that? As Europe has been very divided on that in the past.

Well, um, see, um, there's already been some, um…


I guess, uh, the damage that Russia has caused, if only counted in euros or pounds or dollars, whatever, roughly 500 billion euros.

Um, and we're talking, um, frozen assets of the magnitude order of 200 billion.

So, already, typically, uh, you would consider war reparations for the aggressor to have to pay at some point.

So, surely, uh, there would be also legal way of, uh, you know, uh, using those assets.

You wouldn't even have to confiscate those if, if that's an obstacle politically to somebody.

But I wouldn't even see an economic, uh, downside to this so much.

Because of course, property rights, which are extremely important in any market economy, and certainly here in the Free World, uh, are, are extremely crucial to, to, um, to us in, in the sense that, uh, we want to be a credible, you know, place to make investments also in the future.

But surely, if you are engaged in an, in a war of aggression against us, then there's also interpretation in the international law that your property rights probably aren't the same.



Let's come to wider questions now.

I've got many, many more, but, um, let's see, let's start here in the front.

The microphone will come around.

If you could say who you are, please.

I'm Edward Lucas, and I'm one of the, um, authors of the proposed real bank.

But my question is actually on something different, which is that you said the worst thing that can happen is that the Americans relax their sanctions.

I think it could get worse than that.

There are people in Washington who say Russia should have a free hand in Europe, um, that they want to win Russia as a friend against China, and they even say that they don't want American weapons, American-made weapons, used in what they call a border skirmish, some border skirmish with Russia.

So, where does that leave countries like you when you've placed a huge bet on buying the JASMs, the vital deterrent missile that you have, and ordering the F-35? If you try and use these American weapons and a sign comes up saying "software update needed" and they don't work? Well, I'm more than convinced that, uh, America is not only interested in the future of the Free World, but also in the, in the future of the arms industry.

And again, the business ties with, with Europe, uh, as well.

Europe certainly, as a trading partner and as a market, if only looking at from the economic, uh, perspective, is not only much bigger, but also so much more reliable than anything that Russia can offer, uh, whose size is, is a tenth, uh, of our, our GDP.

And also, um, I guess the experience of, uh, companies trying to operate in Russia in the past 20 years has been, um, it's been quite a roller coaster, right?

Thanks, James.

Thank you, Bran.

Good morning, Minister.

My name is James Nixie.

I run the Russia and Eurasia program here at Chatham House.

Um, Minister, you've talked a lot this morning about the Finnish experience.

Um, and, uh, the Finns know Russia.

Could you elaborate a little bit more on the specific experiences of the 1939 to 1940 Winter War and how that has affected your present-day security thinking? Thank you.

It indeed, um, still has a massive influence on, on how we see the world.

And in the Winter War, where we were, uh, illegally invaded by, by Russia, but fended the aggression off, we had to, um, give up some territory, uh, for our independence.

Um, but it certainly taught us the lesson, uh, and of course, this wasn't the first time that Russia has been trying to invade Finland or, or its neighboring countries, that we simply have to invest into our own defense and deterrence.

And during the Winter War, nobody came to Finland's help.

Um, so perhaps, uh, the Finnish mindset has always been that we can do this alone, which is of course, uh, well, not just the, well, it's not the best, uh, best scenario anyway, but, but also probably, um, not the most realistic one also in, in this world.

But it, that was certainly very much in the mindset of people who thought that we would need NATO.

I mean, it, it wasn't that Finland would have been against NATO, uh, whilst we had not for a very long time not joined NATO or applied for membership.

Um, but that certainly changed, uh, with the full-scale, uh, invasion, um, of, of Ukraine.

But yes, Finns take pride in, in saying that we, you know, can pull our own weight and we have.

And indeed, uh, even though the country is, is fairly small, we have one of the strongest reservist-based armies in the, uh, well, not in the world, but in, in Europe.

Um, and, um, we, we also like to think that we are net contributors to NATO, which we are.

Uh, and the reason, uh, together with Sweden, we wanted to join was not only, uh, in order to improve our own security, but also to contribute to the prevalence of our values.

Because essentially, the European way of life, that is what is at stake now.



Thank you.

May I come here in the, the front, right in the front? Yes, thanks.

Thank you very much.

Um, Isabelle Hilton, journalist.

Over the weekend, uh, Mr.

Heus, the US defense secretary, ordered the Pentagon to cease, uh, aggressive, um, cyber, uh, operations against Russia.

This at a time when Europe and all of us are, are experiencing all manner of gray zone warfare and cyber attacks from Russia.

How do you explain this, and how concerned are you about this withdrawal of an effective defense of, of, of us allies against, uh, against a constant gray zone warfare? Uh, well, of course, I'm, I'm a little bit concerned, but I, I would, um, imagine this is, uh, probably part of this grand strategy that, um, the White House has chosen, which is to, uh, um, see if this course of action can lead to peace.

Um, that, um, effectively appeasing Russia, uh, and, um, and, um, putting some pressure on Ukraine.

In my personal view, it should be exactly the other way around.

Um, but I'm sure that, uh, and I trust President Trump and his team are will notice, uh, in due course that this, this probably doesn't work.

I, I just want to just take that point a little bit further.

Because I've been listening to many of the things you're saying, and, um, many supporters of Ukraine would think, look, that would be great if, if, if, if, uh, if this were the case.

But it isn't.

It isn't the view that the US is taking.

It isn't the approach.

Do you have a view on why the US is trying to bring Russia in from the cold? I'm not guessing any, any motives behind that.

Um, you see, um, I think the objective, I think President Trump is, is truly following two objectives, which I can fully agree with.

And the first one is finding peace for Europe and in Ukraine.

And the second thing is, uh, having Europe, uh, pull its weight better what comes to security and defense.

Um, our message is that what comes to peace, um, appeasing Russia has not helped in the past, and it probably doesn't help now either.

So, let's work together on a strategy how we can put an end to this killing on the battlefield and especially targeting civilians.

I, I was, uh, the last time I was in, uh, Ukraine, I was in Kiev in, in January, and I visited, um, the, the Children's Hospital, the largest in Ukraine in, in Kiev, the Okhmatdyt one, which, um, was hit by a Russian missile last summer.

I, I remember that situation vividly because I was on my way to, um, NATO Summit in, in Washington, and then the news came that, uh, they had, or this missile had had hit the Children's Hospital.

So, yeah, uh, I went went to see it.

And of course, it was, um, devastating enough to, to see the building which had been destroyed partly.

But you know, the most devastating, um, experience was to meet those children, those children patients who had perhaps, you know, lost limbs, who had lost family.

Um, and, uh, really to see the sorrow in their eyes.

And those children, if somebody wants peace, it's those children and who deserve peace.

So, I guess our message is that, you know, let's work together on a strategy which, which really brings peace to the people and especially to the civilians.

And, um, our suggestion, uh, to President Trump is, is also as part of this, uh, process, is to have Russia show good will, for instance by bringing back those deported children.

Um, Russia has deported   20,000 children from Ukraine, taken them from their parents.

Um, and of course, a horrendous war crime.

Um, one of the worst things you can do, uh, in, in a war.

So, let's start with that.

And I'm sure President Trump would agree that let's start, start with the children, right? And the second thing that Europe, uh, needs to do more, um, fully agreed.

This has been the Finnish position all along.

Um, and I guess our message to, um, Americans is, is just that, uh, please, let's do this together.

It takes some time, and, uh, things will work out well.



Thanks very much.

Here in the third row, you'll need it.

It's online.

My name is J, and I'm a member of Chatham House.

In the wake of the UN resolution, you could use that so that people can hear you online.

You can hear me, can't you? You can hear you, but online they can't.

In the wake of the UN resolution where the US and Russia voted together, the global picture of NATO is under a cloud now.

Focusing on a smaller subject which is that of the Ukraine situation, I ask what can the willing expect from the United States in terms of cooperation to their cause in that particular part of the world? Does anything remain in place in the light of the recent decisions by the US government? Thank you.

Well, um, again, I think, uh, this incident what we saw at the UN the other week, this was an extraordinary moment.

Twice, uh, voting against Europe on a matter of European security for the first time since 1945.

I guess it's, uh, it's also linked to this strategy, um, which, um, President Trump probably has, um, in terms of simply putting, um, his entire weight and certainly all his cards, uh, on, on, on, um, getting a peace deal.

And, um, certainly, um, it could sound logical that in order to achieve that, you would try to get the entire world on board, also those countries who typically aren't your allies.

Um, this is the only way I can explain this to myself.

Um, and, uh, certainly I think it was, um, also a powerful message that the general assembly vote was so strongly in favor of Ukraine and European security and especially the UN Charter which this at the end of the day is about.

Because we haven't spoken so much about how this space is actually being watched everywhere in the world.

Because if we allow for, um, for moving borders with the use of force or subjugating another country, um, or taking away its sovereignty again by, by the use of force or, or by threatening, uh, force, then certainly we can forget about the entire UN Charter.



We know that military exports to Ukraine have been suspended.

Does stalling, is, is stalling still available, or has that been cancelled too? We are due to find out all, all those details.

And certainly, what is also important is that, um, the US has the possibility to continue, uh, providing that aid, um, also very soon.

So, we're talking about the suspension, I guess.

Um, and, um, I'm convinced that this is linked to, uh, President Trump trying to have the minerals deal with, with Ukraine and some, some sign, uh, that he expects that Ukraine, Ukraine would be willing to approach some sort of a peace deal.

You here on the John Pete from The Economist.

Um, you mentioned the UK a number of times, and you also said quite a lot about the EU building a bigger role in defense, including in defense procurement and possibly defense spending.

Um, not all members of the EU, one in particular, uh, share the idea that the UK should be more closely involved if it's an EU matter.

Do, do you think there will be a way found of including the UK even though it's not a member of the EU and not a member of the single market? And do you think it would be sensible to build a bigger EU defense role without the UK? I don't think it makes any sense to, to, um, do, uh, anything in relation to security and defense without the UK.

And if you ask me, we, well, of course, Finland would be more than happy to have the UK back in the single market and, uh, in political decision-making in, in the European Union.

Uh, to get some sense back, well, a little bit exaggerating, but, uh, we of course have always been very, um, like-minded countries, uh, and think very similarly, for instance, what comes to, um, the freedom of trade, the need to really base everything we have on the as free as possible market economy, and at the same time also, uh, make sure that we have militarily and politically the weight that we deserve as, as Europe in the world.

And certainly, um, I think this, this time really calls for, um, not really innovations as such, but, but resolve, uh, and strong alliances.

And the UK and also the leadership that, uh, Prime Minister Starmer has, has shown is, is more than welcome.

And also, I should add, I mean, those countries say Norway, Iceland, Turkey, it's not just the European Union, right? Everybody who wants to join in this effort, it's effectively about again, you know, protecting the Free World.

So, everybody who wants to do that should be invited.



Yeah, I'm just going to take one from online, um, from Christina, Christina Dorsi, who's a Canadian living in Kazakhstan, Chatham House member, glad to have you.

And she says, um, what are the realistic chances of Canada joining, joining with the EU in some kind of, uh, way, um, in, in this kind of, I think she means, um, support of either European values or, um, or of Ukraine? Absolutely, um, and, um, why not the European Union too? I mean, well, again, I think in this effort, we need the coalition of the willing.

And this is not really, um, anything new.

Because this is how the aid to Ukraine and also our sanctions have functioned thus far.

For instance, uh, the sanctions that we have imposed on, on Russia, um, has not only been the G7 or the EU sanctions, but well, the G7, that says it all.

I mean, it's not just the EU, of course.

And, uh, for instance, the, the UK has been extremely active in, for instance, um, fighting the Russia's shadow fleet, which is a massive problem, uh, in, in our neighborhood here.

Um, so effectively, a massive threat to the environment to start off with, but also like we've experienced also a threat to critical infrastructure, undersea cables, and so on here on the Isles.

Gon member of Chatham House, Minister, the question I, there are so many question to ask, but I choose one in relation to what you stated earlier that $750 million Russian asset which have been frozen for some time.

You claim to pay for the reparation of the war to seize them and pay as reparation for, uh, the damage caused by Russia.

Now, are you seriously considering there will be ever peace between Russia and Ukraine with the current situation taken effect now by the European nations? I'm not sure if I understood the question, but if there's a, I, there really briefly, the question is, are you seriously considering that Russia will allow you to seize the funds they have and then subsequently to have a peace with them or and will they return the lands they seized? Well, that's a, that's a very, very, um, important question, uh, indeed.

Well, um, so far the damage that Russia has caused in Ukraine, uh, in monetary terms, um, if we just forget about all the all the lives lost, which is of course, uh, the most horrendous bit of this war, but, uh, the economic damage is, is around 500 billion euros so far.

And the frozen assets which Europe holds or which are more or less in the European Union is 200 billion.

So, I guess, um, based on international law and its interpretation, uh, and in, or what is also being used for for, um, the sanctions legislation which we have in place, so effectively as a countermeasure, uh, against Russia's illegal war of aggression, then certainly there's also a legal way to seize those assets, um, now and especially in the future, or conditional to further aggression by Russia.

This, this all can be, uh, figured out.

But what is, um, important is that of course that the killing stops, the, I mean, that we get to peace, that's what, uh, certainly Ukraine and Europe want, but also, um, that there's accountability, uh, to the war of aggression and, and towards the aggressor.

Okay, thank you for that.

Let's get in one, one or two more.

Yes, here the third, yes, you, yes, you go microphone.

Uh, Phil Goff, New Zealand High Commissioner.

Um, I was rereading Churchill's speech to the House of Commons in 1938 after the Munich Agreement, and he turned to Chamberlain, he said, um  "You had the choice between war and dishonor.

You chose dishonor, yet you will have war."

President Trump has restored the bust of Churchill to the Oval Office, but do you think he really understands history? I will limit myself to saying that in this time, uh, and I did it myself, I, I quoted Sir Winston Churchill, and I think, uh, he has made very, um, timeless remarks.

Thank you.

Thank you both on that.

Am in the front here.

Thank you, thank you very much, Minister.

Arma van Rij, I head up the Europe program here at Chatham House.

Thank you for making the time for us.

Um, you described the challenge for Europe as essentially being twofold.

One, maintaining support for Ukraine and enabling, enabling them as much as they can to deter Russia.

And the second is to restock and rearm Europe themselves for their defense.

Um, even if the European Commission is successful in all its initiatives that it's planning, even if on a national level country's plan for rearmament, we still face a situation where stocks are depleted, and it takes time for those initiatives to bear fruits, five, seven, 10 years, if not longer.

So, what do we do in the short term? What's the kind of beyond pressure on Russia through sanctions, etc.?

What do we do in the short term right now? Um, well, during the Second World War, um, and certainly in, in history, there have been times when, um, if there's a massive need to ramp up the defense industry, then it can happen also pretty quick.

Um, but, um, we are not at the phase where we need to be panicking or anything.

That's, that's not the thing.

But we certainly have to, to make room for also private investment into the defense industry.

Because this is not only something which the taxpayers have to be funding.

On the very contrary, uh, I guess, and this very much applies to the European Union, um, we should recognize that funding, um, a strategic defense industry, uh, is within the sustainability goals of our societies.

Um, unlike, uh, in some of the regulation we had imposed prior where defense defense industry was considered contrary to ESG.

So, letting go of that.

At the same time, also through the EIB, making room for, uh, investments into the defense sector is important.

Because that will also, um, send a message to, uh, private both equity and, and debt investors to, to participate in the effort.

And I'm sure there's a lot of private interest around.

Because of course, investors see that the demand is there now, and it's going to be there in the future.

So, we just need, um, a better strategy for that.

And what the European Union is doing now, there will be, um, in two weeks' time, the white paper and defense coming out, which will focus on exactly this.

But of course, we need public funds for that too.

But, but this will be an effort which certainly, uh, we will be able to do to.

But it's a very important, uh, remark that you're making.

Because, uh, it's not sufficient if we only raise our defense spending.

Because if we end up just, you know, paying for massive inflation on goods which are not there on military goods, then it doesn't help so much.

So, instead of focusing only on the share of GDP, uh, that defense spending, um, is, is, um, or how high that is, uh, we should certainly focus on the GDP and its growth as well.

So, competitiveness of Europe and, and including the UK, if you ask me.

Uh, and the second thing is, is that we truly are able to produce those capabilities, uh, along with NATO's capability targets and not just, uh, you know, a share of spending.

I'm going to squeeze in two questions on NATO that are online with apologies to the many hands that have been going up in, in, in the hall.

Uh, and the two questions are, one, can you just tell us a bit about how integrated Finland now is, uh, in NATO, um, in this short time you've had? And the second one of whether Turkey has a useful role to play in this.

This is Shamana Salah, um.

Turkey, obviously member of NATO.

Uh, on the other hand, as its finance minister has said in public at Chatham House, not observing the sanctions because it can't afford to and doesn't suit it.

So, what do you, what do you think of one more descriptive one and and then your view on Turkey? Well, Finland, um, had been 30 years, um, a peacetime partner of NATO, and our military was almost 100% interoperable with NATO on the day we joined.

So, in, in that respect, um, we were partly already in there.

And now that we have been, been using these two years together with Sweden to really integrate into, uh, NATO command structure and also ramping up our capabilities, which were, I must say, good in to start off with, but, but still to, um, really integrate also in, in NATO's defense planning, I think we've come a very long way in these few years.

And of course, Finland has also been, uh, participating in, in NATO's presence, um, in places where, where there's need for it, for instance, in Romania and Bulgaria last, last year and Iceland this year.

And, and, um, and yeah, so I think, uh, we are proud proud member of NATO.

What comes to Turkey, uh, they certainly have an interest in, um, peace and stability in Europe too.

And I'm more than convinced that they are willing and able to do their bit.

And I think they are u a fantastic, uh, partner and ally to the coalition of the willing.

And I'm so glad that also Prime Minister Sunak invited Turkey here on Sunday to this gathering.

With that, we are going to have to stop.

It's not as if the questions are stopping, and this is going to be, um, so much part of what Chatham House is talking about in the coming days and weeks.

But for now, you join me in thanking the minister for…








'''

