= 1362
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 57.
This is English as a Second Language Podcast’s English Café episode 57. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about one of the most famous musical festivals, musical events, in the twentieth century in the United States, an event that was important culturally. That event was the Woodstock Music Festival. We’re also going to talk about a controversial political policy – political idea – called “affirmative action.” And, as always, we’ll answer a few of your questions. Let's get started.
Our first topic today is going to be what was probably the most famous music festival in twentieth-century America – that was the Woodstock Festival, or the Woodstock Music Festival. A “music festival” (festival) is another word for a large concert. However, a music festival is where you have many different concerts by different performers, usually all held in one place over a period of two or three days. There are lots of different music festivals for different kinds of music.
Today, we’re going to talk about a rock music festival that took place back in 1969, in a town in New York State called Woodstock. One of the reasons that Woodstock is considered one of the more important music festivals, even though it happened several decades ago, is that it was the largest gathering of the hippie community, the hippie culture, of the late 1960s. A “gathering” is when several people get together. This was a gathering of many young people, teenagers and people in their 20s, many of whom were part of what has been called the “Hippie Movement.”
The hippies were, in the late 1960s and early 1970s, young people who wanted to go against traditional culture – wanted to go against traditional morality, against traditional politics, and against traditional music. The music and actions of people in the hippie movement were very much what we could describe as “countercultural.” This was also a period of time when American politics was going through some difficult periods – indeed, Western politics in Europe, as well. There were lots of protests – people who were angry about certain ways that the political system was operating.
This was also a time when the United States was involved in a war in Southeast Asia, particularly in Vietnam, and many people were not very happy – especially young American men were unhappy, because they had to go and fight in this war. So, the hippie movement tried to protest against many different things. There were a lot of people who were in this movement who got involved in using illegal drugs as well, and at music festivals like Woodstock, it was very common to see people smoking marijuana or using other sorts of illegal drugs.
The Woodstock festival itself had many of the most famous rock bands perform there. The rock band The Who from England was there. The guitar player Jimmy Hendrix from the United States was there. In fact, his performance is still famous because he played the U.S. national anthem on his electric guitar. The “national anthem” (anthem) is the national song of a country. In the United States, we have our national anthem, which is called “The Star-Spangled Banner.” The word “banner” here refers to the flag of the United States. When we say something is “spangled” (spangled), we mean that it's shiny, that it reflects light. You can see it easily.
“The Star-Spangled Banner” refers to the stars of the states – now the 50 stars, one for each state – on the American flag. “Spangle” is a word you won't hear anywhere else other than in the name of our national anthem. Well, Jimi Hendrix played the national anthem on his electric guitar, and it became quite famous. Some people didn't like what he did on his guitar, but it is definitely something that most people of my generation remember seeing.
Woodstock took place in 1969. It was only an event that lasted a couple of days, but it had a great deal of importance culturally in the United States. It was the high point of the countercultural movement in the United States. Not everything was fun and happy at the Woodstock festival, unfortunately. I mentioned that there was a lot of drug use at Woodstock, and two people actually died at Woodstock because of what is called a “drug overdose.” An “overdose” (overdose) is when you take too much of a drug, so much that it kills you. A “dose” (dose) is the amount of drug you're supposed to take. So, an “overdose” is too much of that drug.
People still remember Woodstock, and if you say Woodstock, even people who were born many years after will know what you are talking about, or at least understand generally that you're referring to this music festival that was such an important part of the counterculture hippie movement in the U.S. I don't know anyone who actually went to Woodstock, and I was just a young child when it happened, but like most Americans, I'm aware of it and have seen pictures as well as video clips from the festival.
My guess is you could go on the Internet and try to find some clips on Woodstock. They later had another music festival at Woodstock several years later, but it was never as successful or as important as the original festival.
Our next topic is about political policy. We don't normally talk about politics on the English Café, but I thought I would talk about one controversial policy – one policy that people have certainly disagreed about in the United States in the last 40 years – and that is affirmative action. The word “affirmative” (affirmative) means the opposite of negative. It means, if you will, saying yes to something. “Affirmative” is something that is positive. “Affirmative action,” however, refers to helping someone who may have been hurt or injured because of discrimination in the past.
“Affirmative action” usually involves steps that a company or that the government takes to try to make up for the negative effects of discrimination on certain groups of people in the past, sometimes many years ago. Usually, this is not referring to someone who specifically was discriminated against. Generally speaking, we're not talking about, for example, an African American who didn't get a job because the person who is hiring didn't like black people. That person can certainly sue and go to the courts to get a remedy, or a solution to that problem.
Instead, we’re talking about actions that the government takes to help a whole group of people, even those who perhaps have never experienced discrimination personally. The idea behind affirmative action is that it provides a remedy. A “remedy” (remedy) is normally something that cures you when you're sick. Here, we’re talking about something that helps you because there has been discrimination against your group in the past.
The United States, of course, is a country of many different groups, many different races – blacks, whites, Asians – many different ethnicities. An “ethnicity” (ethnicity) refers to the country where you come from: Mexican, Irish, French, Japanese, and so forth. Many of these groups in the past had been discriminated against, and even though the laws changed so that people could no longer legally discriminate against other people because of their race or ethnicity or “gender” (which would be your sex – whether you're male or female) – even though we had laws like that, there were still people who felt like the government needed to do more to help these groups.
Primarily, affirmative action was an attempt to do something about the effects of discrimination on African Americans, on Latino Americans, on Native Americans or American Indians, and to a lesser extent, on Asian Americans. Affirmative action tried to correct the mistakes of the past, and it did that by giving people from certain groups advantages when they were involved in certain government programs.
The most important area where affirmative action has had an effect is the university. In order to get into a college – in order to be “admitted to,” we would say, a university – you have to fill out an application. You have to have certain academic qualifications and so forth. One of the things that affirmative action policies did, beginning in the 1970s and 1980s, is to try to help people from certain groups get into the university more easily. Many people supported this policy.
There were also many people who didn't like it, who felt that the government was trying to correct discrimination by discriminating against people who were not in these groups. The word that was used to describe this idea was “reverse discrimination.” “Reverse” (reverse) is when you go backwards. That's one meaning. For example, if you're driving in your car and you need to not go forward but go backwards, you would put it in – the gear in – reverse. You would reverse the car so that it went back. “Reverse” can also mean in a way opposite, and that's really the meaning here.
“Reverse discrimination” would be discriminating against the people who are in the majority, in favor of people who are in a minority. That was the primary, most important criticism of this political policy. What has happened with affirmative action? It depends on the state where you live. The federal government has made changes to some of the early affirmative action laws, and the U.S. court system has also made changes, saying that certain kinds of affirmative action were legal and other kinds were not. There are still many states where there are affirmative action laws to try to help minorities. There are other states that have passed laws to say that schools and other institutions cannot use affirmative action (speaking now of public institutions).
It's hard to know what the future of affirmative action will be. Even people who support the policy of affirmative action recognize that America is changing, that the profile of America is changing. Whites will no longer be a majority in a few years in the United States, and so that may change some of these policies that were originally intended to help those who have been discriminated against.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Fabio (Fabio). I love that name, Fabio. Fabio is in Brazil. Fabio wants to know the difference between two expressions, or two terms: “hands-on” and “hands-off.” When we say something is “hands (hands) – on (on),” we mean that it is something that you are working with with your hands or something that you are doing personally. The opposite of “hands-on” would be “hands-off.” “To be hands-off” means that you are not actively participating in the activity.
This is often a term that is used when talking about someone who is supervising or helping another person do their job. A “hands-on person” would be a boss or a supervisor who perhaps goes in and tries to help the person directly, maybe even do some of it himself. “Hands-off” would describe someone who just lets the person work – doesn't give them a lot of instruction or a lot of recommendations. “Hands-off,” then, is when you're not involved in something, and “hands-on” is when you are involved in something.
A second question from Fabio has to do with the verb “to struggle.” “To struggle” (struggle) means, usually, that you are trying to get free from something. Something is holding you back or holding you down. It could be a situation that is causing difficulties for you. “To struggle” means to try to escape that situation – to try to make your situation better. “Struggle” as a verb usually refers to someone who has to put in a lot of energy or a lot of effort in order to get free of this situation.
Sometimes the verb “struggle” can be used in describing a physical struggle, a fight between two people. If someone comes up to you with a gun and says, “Give me your wallet.” You decide that you don't want to give them your wallet, which is a really stupid thing to do. I don't recommend that. But let's say you're not very smart, and you just say, “I'm not going to give you my wallet.” And you grab the hand of the person with the gun and the two of you “struggle” – the two of you fight. You’re trying to get free, if you will, of this situation.
A more general use of the word “struggle” is, however, to put in a lot of effort in order to meet a certain goal or a certain objective. “I'm struggling with this class.” I'm having a difficult time with this class. I want to pass this class. That would be one possible use of the word struggle.
Our next question comes from Keiko (Keiko) in Japan. The question has to do with what you do when you are, for example, staying in a hotel and you want the people who work at the hotel to get you a taxi, a taxicab – a car that will take you to somewhere where you want to go.
The expression we would probably use in this situation is, “Can you call me a taxi, please?” “Can you call me a taxi, please,” or simply, “Can you call a taxi?” “To call” here usually refers to picking up the telephone and calling the taxi company so they will send the car over to the hotel. “Can you call me a taxi?” is one way of asking for this. Another way would be, “Would you call me a taxi,” or “Could you call me a taxi?” They mean the same thing, but they are perhaps a little more polite.
Our next question comes from Rui Li (Rui Li) – two words – from China originally, but now living here in California. The question has to do with the difference between two expressions that are also very common in English, “May I” and “Can I.” If you're asking permission to do something, should you say, “May I” or “Can I”?
Let's say that you're in a restaurant, and you want the waiter or the waitress to bring you more water. In that situation, you would probably say something like, “Can I get some more water, please?” or “Could you get me some more water?” A more polite way of saying that, a little more formal way of saying that, would be, “May I have some water, please?” “May I” is a little more polite in that situation. “Can I” is a little less formal, a little less polite, but still perfectly acceptable.
When you're talking to your friends or family, you would probably not use “May I” to ask for permission. You would probably just say, “Can I?” “Dad, can I use the car?” You would never say, “Dad, may I use the car?” You might, but it would be a little strange.
Some people want you to use “May I” because they think that's more grammatically correct, that “Can I” implies “Are you able to do something?” In fact, this was a joke when we were growing up. Someone would say, “Can I do something?” and you would say, “Are you able?” “Can,” as a helper verb, means “able to do something.” However, almost no one separates the meaning of “May I” and “Can I” anymore, especially in normal conversation, so it's not something you should worry about.
Our next question, our final question, comes from Susana (Susana). We’re not sure where Susana is from. Let’s say she's from the moon. Susana, writing from the moon, wants to know the meaning of the word “carpooling” or, simply, “to carpool.”
“To carpool” (carpool) – one word – means to share a car ride with someone who is going to the same place as you are. This is very common in companies who try to help their employees save money. They may set up a car pool, where you can say, “I live here . . . I live here, this person lives here, and we all need to get to our job.” If you live in the same area, you'll drive over to someone else's house, or someone will come by your house and pick you up, and you will drive together.
Some companies actually will pay you to operate a car pool to go with someone else. I actually did this once when I was a high school teacher. I lived somewhat far from where I was teaching, and there was another teacher who lived in my neighborhood. So, on two days of the week, we would both drive to the same parking lot near our houses, and then we would carpool. One of us would drive one day, and the other one would drive the next day. That way, we both didn't have to drive, and we saved money on gasoline.
The verb “to pool” (pool) means to put things together, for people to share their resources – to put their resources, or the things that they have, together so that they can use them together. That's where we get this verb “to carpool.” In the United States, there are now many freeways and highways that have what's called a “carpool lane.” When you have a place like Los Angeles where there are too many cars, it can take a very long time for you to get to work in the morning.
The government now has special lanes, special places on the freeway, where you can only drive if there are either two or more people in your car or three or more people in your car. It depends on where you are. These are called “carpool lanes,” and really they reward people. They give people a benefit who are not driving by themselves. If everyone drives by themselves, then you have the problem of too many cars, of more pollution, and so forth.
That's all we have time for today. If you have a question, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
gathering – a meeting, usually for a social purpose or celebration
* Every year, St. Louis has a gathering of the best jazz musicians in the country.
overdose – too much of a dangerous drug that causes someone to be sick or to die
* The police don’t know yet how the man died, but they think it was an overdose of sleeping pills.
national anthem – a country’s official national song
* You’ll hear the U.S. national anthem played before every professional baseball game.
shiny – something that reflects light, usually a smooth surface
* Is that Dr. Jeff McQuillan over there? I think I see the top of his shiny head!
affirmative – agreeing to or approving of something; positive; yes
* If we get an affirmative response from the local government, we can move ahead with this building project.
remedy – something that corrects or fixes something that is wrong or that causes a problem
* The only remedy we can see for fixing this mistake is to start all over again.
to be admitted – to allow someone to enter, enroll, or join a group or an organization
* When will you find out if you have been admitted to the University of Arkansas?
race – a group of people with common physical features
* On most government forms, you are asked to check a box indicating your race.
gender – being male (a man/boy) or female (a woman/girl)
* I want to make it clear that there will be no gender preferences when hiring for these jobs.
ethnicity – a group with the same social, cultural, and/or language background
* Our next presentation will be about how race and ethnicity are portrayed in American movies.
to reverse – to go backwards; to change to the opposite
* The vice-president of our club reversed his decision and we will now allow players under 18 to join.
hands-on / hands-off – being involved or participating (hands-on); not being involved or not participating (hands-off)
* The old manager liked to be hands-on in the office, meeting with people every week, but the new manager prefers being hands-off unless there’s a serious problem.
to struggle – to try to do something that is difficult to achieve; to physically fight with someone
* He struggled with the tax forms for an hour but still couldn’t figure them out.
to call (someone) a taxi – to get a taxicab for someone
* Dan, would you please call Ms. Sanchez a taxi as soon as possible?
May I… / Can I... – a phrase to use when asking someone for permission to do something; “May I” is more formal than “Can I”
* May I take your coat for you, and can I help you find your seat?
to carpool – to ride in a car with one or more other people to a specific place, rather than to drive alone
* I started carpooling to work three times a week and it’s saving me a lot of money on gas.
What Insiders Know
Politically Correctness
“Politically correctness” is a term used for language that we use that is least likely to cause “offense,” or cause other people to be angry with you. We talk about being politically correct or “PC” most often when we are talking about racial or cultural groups in the U.S., but it can be used with any group. Most people see being PC as a way to give groups respect so that groups can get along with each other. Others believe that Americans try to be too PC and that they are too careful about giving offense. There has been some “backlash,” or strong negative reaction in the opposite direction. There is even a political talk show on American television called, “Politically Incorrect.”
Below are the politically correct or generally accepted terms for some of the major racial and cultural groups in the U.S. What is acceptable has changed over time. Terms acceptable 20 or 50 years ago are now no longer considered appropriate, and some of those are listed in the right-hand column below. We do not include “racial slurs,” or bad names used to insult a specific racial or cultural group. We also do not have the space to include smaller ethnic groups, such as Mexican American, Korean American, or Nigerian American.
Generally Acceptable		Less Acceptable or Not Acceptable
§ Native American			§ Indian
§ American Indian			§ Afro-American
§ African American			§ Negro
§ Black				§ Colored
§ Latino (men) / Latina (women)	§ Spanish (unless from Spain)
§ Hispanic
§ Asian American			§ Oriental
§ White (American)
§ Caucasian (American)
§ European American