= 1380
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Café number 75.
This is the English Café episode number 75. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, in the State of California, here in the United States of America. I hope you are well - doing well.
On this Café, we're going to talk about American songs, one song in particular, a very popular song from the 1960s called “Sound of Silence” by the singer, Paul Simon. It was made famous by the group Simon and Garfunkel, two male singers back in the 1960s and 70s, and we'll talk about a little bit about that song because it's a very popular song and many people know it, and it gives us a chance to talk about some different kinds of vocabulary. As always, we will answer some of your questions as well. Let's get started.
Take a look at our website at eslpod.com. You'll want to download the Learning Guide for this podcast as well as look at our new ESL Podcast Store and other new things that we now have on our website. So, if you haven't visited in awhile, take a look.
We're going to start by talking about a famous American song called “The Sound of Silence.” Now, I can't play the music on the podcast because that would be against the law in the United States. I don't have permission to play the music on the podcast. If I did that, then they would probably come and - the police would come and arrest me - take me to jail - take me to prison, and then we could do a podcast on prison English. But, I would really rather not do that! So instead, I'm just going to talk about the lyrics. The lyrics of a song, “lyrics,” are the words for the song, or the words to the song we would probably say.
I'll talk a little bit about what the lyrics mean and some of the vocabulary in them, and then you can go and listen to “The Sound of Silence.” Again, a very popular song all throughout the world; I think many people know this song.
“The Sound of Silence” was written in 1964, and that's an important date because 1964 is the year after the president of the United States, John F. Kennedy, was killed. We would say he was assassinated. To assassinate, “assassinate,” means to kill usually a famous person - a famous political person or political leader.
Well, Kennedy was assassinated on November 22nd, 1963, and Paul Simon, in the early part of 1964, wrote this song about the loneliness that Americans felt, about the fear, about the sadness that they felt. At least according to some people, that was the reason for the song. So, the song is very much about sadness; it's very much about being alone and being in the dark, and that's how he felt Americans felt after the death of John F. Kennedy. I'm a little too young to remember that; I was alive, but just barely! I was only about two months old when that happened. I was born on September 24th, 1963, so it was just about two months after I was born.
In the song, Paul Simon writes about this loneliness. He begins the song, what we would say the first part of the song, or the first to stanza, “stanza.” A stanza is like a paragraph or part of a song. Most songs are usually written as though they were poetry, so they're written like poetry, and like poetry, it's not always easy to understand what the song means. I'm going to give you my interpretation, but another person could listen and read this lyrics and come up with a different interpretation. So, this is my view of the song, and I’ll explain some of the words in the song that you may not understand easily.
The song begins:
“Hello darkness, my old friend,
I've come to talk with you again.”
I read somewhere that Paul Simon liked to play the guitar in the dark when he was composing songs or just to relax. Here, he's talking to darkness, and again, that gives you this idea of being lonely - being by yourself. Darkness is his friend.
He says:
“I've come to talk with you again,
Because a vision softly creeping,
Left its seeds while I was sleeping.”
A vision, here, is like a dream - it's like an inspiration that you get, and this vision was “softly creeping.” To creep, “creep,” means to move very slowly - very carefully - usually so that you won't be noticed. It's something that someone who was going to steal money from a house - was going to rob a house - he would, or she, would creep - would move very slowly and carefully so no one heard them. To creep softly means to move without making a lot of noise.
So, this vision came into his head and “Left its seeds while he was sleeping.” Seeds, “seeds,” are things that we put into the ground in order to grow flowers and grow plants. So, if you are a farmer, you put seeds in the ground, and the seeds develop into a plant or into a flower. In this expression, the verb is to plant, “plant.” So, you plant seeds, and the seeds produce plants - plants as a noun, so it can be a noun or a verb.
You plant seeds; in this case, the vision was planted in his head. The seeds are the beginning of this idea. We sometimes use this expression, to plant a seed in someone, to mean to give them an idea that they can then think about by themselves and develop. Well, this seed - this vision “Still remains within the sound of silence.”
The title of the song, “Sound of Silence,” is, of course, something of a contradiction - something of a paradox, “paradox.” A paradox is when you have two things that seem to be opposite, that don't seem to make sense. Silence is when there is no sound, so how can you have the “Sound of Silence?” I think he's trying communicate the idea of loneliness here, of being by ourselves now that we've lost our president, President Kennedy.
The second stanza continues by him saying, “In restless dreams,” meaning I couldn't sleep very well - the dreams bothered me. In his dreams, he “walked alone on narrow streets of cobblestone.” Cobblestone, “cobblestone,” (one word) are rocks that they used to use to cover roads. They don't use them any more, at least in American cities, but some of the older cities would have cobblestones - cities in the eastern part of the United States and cities in Europe as well, and in parts of Latin America.
So, he's walking through these streets, “neath the halo of a street lamp.” Neath is short for beneath; it's a poetic expression here. A halo, “halo,” is a ring of light, and we normally associate halos with, in the Christian artistic tradition, with the holy people - with the saints. They had a halo over their head. Here, it just means a ring or a circle of light around the street lamp - the lamp for the street. And of course, because there's a street lamp that is on, we know that it's night time so, once again, this idea of darkness.
He turns his “collar to the cold and damp.” Damp, “damp,” means wet. So, he's trying to keep warm because it's cold outside. Then suddenly, he says:
“When my eyes were stabbed by the flash of
A neon light
That split the night.”
His “eyes were stabbed.” To stab, “stab,” usually means to take a knife and try to kill someone with it. If you read in the news, “The man was stabbed,” that means that someone took a knife and tried to kill him, or at least to hurt him. In the song, he says his “eyes were stabbed by a flash of neon light.” So, the light was so strong that it was like he was being stabbed. It was so strong it entered his eyes. A flash is just a bright light that comes and goes very quickly. Neon, “neon,” is a type of gas; it's a chemical element that we use for advertising signs that are made of lights. The idea of neon here is, I think also, that it represents commercial America, and also sort of an emptiness - a certain shallowness. To be shallow, “shallow,” is the opposite of deep, so not very important.
This neon light stabs him, and it splits “the night,” which I think means here it divides the night - it interrupts the night - it was dark, and suddenly there was this flash of light, Now, what is the flash of light? Well, we can guess it's the assassination of the president, that was what changed the environment - the atmosphere here.
The rest of the song then continues with this idea of loneliness - this idea of many people not knowing what to do and being lost. I don't want to go through the whole song - we don't have time to go through the whole song, but I think you get a good idea from those first two stanzas about what the song is - what the song is about. Just so that you know which song I'm talking about, I will sing for you the first couple of lines. I know that you want me to sing, so I will:
“Hello darkness, my old friend,
I've come to talk with you again,
Because a vision softly creeping,
Left its seeds while I was sleeping...”
And so on and so forth. [recording of applause] Thank you; thank you. I appreciate that.
Now let's answer a few questions.
Our first question comes from Vladimir, “Vladimir,” in Toronto, Canada. Vladimir wants to know the meaning of the expression, and when you use the expression, “good for you.” Good for you.
Good for you normally means that's great - that's a very good accomplishment - something that you did. So, someone is congratulating you, saying you did a good job on something, or they're happy for you. They think it's wonderful that you have done something that would be to your benefit. Usually used, as I say, when someone has done something or achieved something good, and it is often used to give them a little encouragement. Encouragement meaning here giving them hope - giving them more confidence.
Often, but not always, but many times it's used by someone who has more authority or who is older talking to someone who is younger or someone who has less power - less authority. For example, if your daughter wasn't good enough to join the swim team - she couldn't swim well enough to be on the team at her high school - and she decides to work very hard so that she can be on the team next year, you might say, “Good for you” - I'm glad you're going to work hard - you're encouraging her. Another example: if you have a friend who is applying for many jobs, and finally they get a very good job, and someone tells you and you say, “Good for him,” meaning that's great, I'm happy for him.
Oliver, “Oliver,” in Germany, wants to know the difference among the words realize, recognize and notice.
Realize, “realize,” means to understand something clearly or to become aware of something - to suddenly know something. “I realized I did not put gas in my car yesterday.” I understood it - I became aware of it.
To recognize, “recognize,” means to identify someone or something because you've seen them before. “I recognized my old college professor when I was at the grocery store yesterday.” I saw him and I knew him - I recognized him. When you recognize something, it's always something that you have seen before, or someone whom you have seen before.
Notice, “notice,” means to become aware of something, usually something that you see that you didn't see before. So, it has some connection with realize - notice. We would usually use notice for situations where you are looking at something or that you saw something. For example, “Did you notice that the woman over there looks just like Angelina Jolie? That's Dr. Lucy Tse!” Did you notice, meaning did you see that - did you become aware of it when you saw it.
So, realize is to understand something clearly. Sometimes we say, “I realized my mistake.” I understood it - I became aware of it. Recognize is usually when you see someone or something again, and you remember it. Sometimes we use recognize to be more formal in saying that something is true. For example, “My boss recognized my good work in the company.” He recognized it; he maybe gave me an award or told other people what a good job I was doing. The noun would be recognition. “I received recognition,” means that people have come up to me or given me something so that I know that they appreciate my good work.
To notice, as I say, means to - usually to see something, and so is a little more specific than the verb realize or to realize.
Our final question comes from Carole, “Carole,” in France. Carole has a question, a common question that we get, which is: What is the difference between farther and further?
Farther, “farther,” is what we would call the comparative form, when you are comparing one thing with another thing. Usually it's used for a greater distance. It could also be used to mean a bigger or larger or greater amount of space or time.
Further, “further,” is often used now the same way as farther. Traditionally, there was a difference that some people still recognize when they read it or hear it. Traditionally, we use we use the word farther when we were talking about physical distance. For example, “Las Vegas is farther from Los Angeles than San Bernardino,” which is another city. San Bernardino is closer to Los Angeles than Las Vegas, so Las Vegas is farther way, or farther.
Further, traditionally, was used when we were talking, for example, about an idea. “I want to investigate this idea further,” meaning more - at a greater amount. Nowadays, as I say, most people use them to mean something very similar. But, if you want to be very careful in your language, according to traditional rules, you would probably say, for example, “I can throw this ball farther than you,” because you're talking about physical distance. Or, “I've traveled farther from my home than anyone else has,” again, talking about physical distance.
You can also talk about physical distance using further, at least that's become popular in American English. There are some cases where you would probably only say further and not say farther, however. For example, if you are at a meeting and you want to know if anyone has more questions, you may say, “Are there any further questions,” meaning additional. So here, it means something a little different - additional. Or, you might say to someone, “I will try to explain this idea further tomorrow,” meaning I will go more into it - I will go deeper.
So, thank you for that question Carole, as well as Oliver and Vladimir for their questions. If you have a question for the English Café, just email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on the English Café.
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
to creep – to move slowly and carefully
* Your father is asleep on the couch so let’s creep quietly upstairs so we don’t wake him.
softly – quietly; in a slow and gentle way
* Ryan speaks so softly sometimes that it’s hard to understand him.
to plant a seed – to give someone an idea; to suggest or inspire someone to do something
* During the meeting, Ginger planted a seed to give the employees a bonus this year, instead of having a holiday party.
vision – dream; inspiration; a view of what the future will or should be like
* We need a leader who has a clear vision about how this organization can expand.
cobblestone – a small round stone used in the past to cover roads
* On our vacation, we visited some cities that still have cobblestone roads that horses and carriages once traveled on.
halo – a circle of light above a person’s head, usually seen in pictures with saints or other holy people
* In the portrait you’re painting of Dr. Jeff McQuillan, make sure you add a halo around his head.
to stab – to try to hit someone with a knife or a sharp object
* Be careful with that knife! If you’re not more careful, you’re going to stab someone in the back.
flash – a bright shining light that is seen only briefly or suddenly
* We were outside looking at the stars when suddenly, we saw a flash of light that we couldn’t explain.
neon – a very bright type of light used in lamps and in business or store signs
* The restaurant has a big pink neon sign that says, “Dinner and Dancing.” You can’t miss it.
Good for you! – a phrase that means “That’s great!”, “I’m very happy for you!”, “I’m proud of you”
* You won a full scholarship to go to Lansing University? Good for you!
to realize – to understand clearly; to become aware of something as a fact or is true
* I knew that I had forgotten something when I left the house this morning, but it wasn’t until lunchtime that I realized I’d left my lunch at home.
to recognize – identify someone or something because you have seen or heard them before; to formally say that something is true
* At the reunion party, I was able to recognize a lot of people I hadn’t seen in over 10 years.
to notice – become aware of something, often used for things you see
* Did you notice that the man over there has been staring at you the entire evening?
farther – at a greater distance
* The hotel clerk said that the store was only two blocks away, but we’ve been walking a lot farther than that and I still don’t see it.
further – at a greater amount of space, time, or degree
* I don’t see why we have to discuss this issue any further. I thought we had already made a decision last week.
What Insiders Know
Rock and Roll Hall of Fame
The Rock and Roll Hall of Fame is an organization located in Cleveland, Ohio, that recognizes and honors people who have been important in the rock music industry. It also has a “museum,” a building with important “artifacts” (things from history) where people can go to visit and learn about rock music. The museum opened in 1995 and the building was designed by the famous architect I.M. Pei.
A “hall of fame” is any organization that recognizes the achievements or accomplishments of any group of people. In sports, for example, there is a “Baseball Hall of Fame,” which honors the most important players in baseball history.
Each year, a Rock and Roll Hall of Fame committee “nominates” or proposes people to be include in this organization. A person is “eligible” (meets the requirements) to be nominated 25 years after they release their first record. About 1000 people who are considered “experts” (people who have a lot of knowledge in an area) in music vote on the people who are nominated. These people include university researchers, “journalists” (news writers), producers, and other people with a lot of experience in the music industry.
And, each year, this organization “inducts” (accepts) performers, producers, and other people who have influenced the music industry in a major way. Simon and Garfunkel who wrote and recorded Sound of Silence and many other well known hit songs were inducted in 1990.