
= What Is Narcissism? Science Confronts a Widely Misunderstood Phenomenon 什么是自恋？科学面临一个被广泛误解的现象
:toc: left
:toclevels: 3
:stylesheet: ../myAdocCss.css



'''


== What Is Narcissism  (n.)自我陶醉，自赏，自恋（尤指对自己的容貌） ? Science Confronts (v.) a Widely Misunderstood 遭误解的；不为人理解的 Phenomenon 什么是自恋？科学面临一个被广泛误解的现象


[.my1]
.案例
====
.narcissism +
[ U] ( formal disapproving) the habit of admiring yourself too much, especially your appearance 自我陶醉，自赏，自恋（尤指对自己的容貌） +
--> 来自古希腊神话，英俊青年Narcissus拒绝了神界第一美女Echo的爱，却爱上了自己在水中的倒影，不幸溺水而死，后用于心理学名词，自恋，孤芳自赏。
====


...But chances 可能性 are you've encountered a narcissist 自恋者,自我陶醉者, and they looked nothing like Trump, Musk or Modi.

*Up to* 6 percent of the U.S. population, mostly men, is estimated to have had _narcissistic 自我陶醉的; 自恋的 personality disorder_ during some period of their lives.

And the condition manifests (v.)表明，清楚显示（尤指情感、态度或品质）; 显现；使人注意到 *in confoundingly 令人困惑地 different ways*.

People with narcissism (n.)自我陶醉，自赏，自恋（尤指对自己的容貌） “may be _grandiose_ (a.)华而不实的；浮夸的；不切实际的 or _self-loathing_ (a.)自我讨厌的,自我憎恨的, _extraverted_ (a.)外向的 or _socially isolated_ 社交孤立, _captains of industry_ or _unable to maintain steady 稳的；平稳的；稳固的 employment_ 工作；职业；受雇, 就业, _model citizens_ or _prone (a.) 易于遭受；有做（坏事）的倾向 to antisocial activities_,” according to a review paper 回顾性论文,综述论文 on _diagnosing (v.) the disorder_.

[.my2]
...但你很可能遇到过一个自恋者，他们看起来一点也不像特朗普、马斯克或莫迪。据估计，高达 6% 的美国人口（主要是男性）在一生中的某个时期, 患有自恋型人格障碍。而且这种情况以令人困惑的不同方式表现出来。根据一篇诊断自恋症的评论论文，自恋者“可能是'浮夸的'或'自我厌恶的'，'外向的'或'社会孤立的'，'工业领袖'或'无法维持稳定的就业'，'模范公民'或'容易进行反社会活动'”。

[.my1]
.案例
====

.The chances are + that...
表示推测。意思是：“有可能......”。 +
- The chances are you won't have to pay.  你可能不用付钱。

.manifest
(v.)  +
1.[ VN] ~ sth (in sth) : to show sth clearly, especially a feeling, an attitude or a quality 表明，清楚显示（尤指情感、态度或品质） +
SYN demonstrate +
• Social tensions were manifested in the recent political crisis. 最近的政治危机显示了社会关系的紧张。 +

2.[ VN] ~ itself (in sth) : to appear or become noticeable 显现；使人注意到 +
SYN appear +
• The symptoms of the disease manifested themselves ten days later. 十天后，这种病的症状显现出来。

-->  来自拉丁语manifestus,清晰的，明显的，抓个正着的，来自manus,手，词源同manual,-fest,击，打，抓住，词源同infest,offend.引申词义显现，展现。




====


Clinicians  临床医师 note (v.) several dimensions 维（构成空间的因素）；尺寸; 方面；侧面 *on* which narcissists *vary* (v.)（根据情况）变化，变更，改变.

They may function (v.) extremely well, with _successful careers_ and _vibrant  (a.)充满生机的；生气勃勃的；精力充沛的 social lives_, or _very poorly_ (a.)有病；不适；不舒服.

They may (or may not) have other disorders, *ranging from* depression *to* sociopathy 反社会人格.

And although most people are familiar with _the “grandiose” 华而不实的；浮夸的；不切实际的 version_ of narcissism — as displayed by _an arrogant 傲慢的；自大的 and pompous 虚华的；言辞浮夸的 person_ who craves (v.)渴望；热望 attention — the disorder also comes _in a “vulnerable” （身体上或感情上）脆弱的，易受…伤害的 or “covert” 秘密的；隐蔽的；暗中的 form_, where individuals suffer (v.) from _internal distress_ and _fluctuations 波动，起伏 in self-esteem_ 自尊（心）.

`主(主从)` What these seeming opposites 对立；对立面 have in common 共有；公有 `系`  is _an extreme preoccupation_ 盘算；思虑；长久思考的事情 with themselves.

[.my2]
临床医生指出，关于自恋者存在多个维度的差异。他们可能表现得非常好，拥有成功的职业生涯和活跃的社交生活，或者表现得非常差。他们可能（或不可能）患有其他疾病，从抑郁症到反社会人格障碍。尽管大多数人熟悉“夸大型”自恋——表现为一个傲慢、自大、渴望关注的人——但这种障碍也有一种“脆弱”或“隐秘”形式，在这种形式中，个体会经历内心的痛苦和自尊心的波动。这些看似相反的形式的共同点在于，对自身的极度关注。

[.my1]
.案例
====
.主从 What these seeming opposites have in common  `系`  is ...
主 What these 后定 seeming opposites `谓` have in common


.pompous
(a.) ( disapproving) showing that you think you are more important than other people, especially by using long and formal words 虚华的；言辞浮夸的

.covert
(a.) ( formal ) secret or hidden, making it difficult to notice 秘密的；隐蔽的；暗中的 +
• covert (a.) operations/surveillance 暗中活动╱监视

.self-esteem
[ U] a feeling of being happy with your own character and abilities 自尊（心）


.preoccupation
[ UC] ~ (with sth) : a state of thinking about sth continuously; sth that you think about frequently or for a long time 盘算；思虑；长久思考的事情 +
. She found his preoccupation with money irritating. 她对他一心只想着钱感到很厌烦。 +


.have sth in common (with sth)
( of things, places, etc. 东西、地方等 ) to have the same features, characteristics, etc. 有相同的特征（或特点等）


====

`主` Most psychologists who treat (v.)医疗；医治；治疗 patients `谓` say that grandiosity 宏伟；夸张 and vulnerability 脆弱性,易损性 coexist (v.)同时存在，共存 in the same individual, showing up （使）看得见，变得明显，显现出来 in different situations.

Among academic psychologists, however, many contend (v.)（尤指在争论中）声称，主张，认为 that these two traits （人的个性的）特征，特性，特点 do not always overlap （物体）部分重叠，交叠. +
 This debate has raged (v.)猛烈地继续；激烈进行 for decades without resolution （问题、分歧等的）解决，消除, most likely because of a conundrum 令人迷惑的难题；复杂难解的问题: vulnerability is almost always present (v.) in a therapist's 治疗专家；心理治疗师 office, but `主` individuals high in grandiosity 宏伟；夸张 `谓` are unlikely to show up for treatment.


Psychologist Mary Trump deduces (v.)推论；推断；演绎, from family history and close observation, that her uncle, Donald Trump, meets the criteria  (判断的) 标准 for narcissistic as well as, probably, antisocial personality disorder, at the extreme end of which is sociopathy 反社会人格.

But “`主` coming up with 找到（答案）；拿出（一笔钱等） an accurate and comprehensive 全部的；所有的；（几乎）无所不包的；详尽的 diagnosis `谓` would require a full battery 一系列；一批；一群 of psychological and neuropsychological tests that he'll never sit for,” she notes 指出；特别提到 in her book on the former president.


[.my2]
====

大多数治疗患者的心理学家表示，"夸大"和"脆弱"同时存在于同一个人身上，在不同的情况下表现出来。然而，在学术心理学家中，许多人认为这两种特征并不总是重叠。这场争论已经持续了数十年而没有解决，很可能是因为一个难题：治疗师的办公室里几乎总是存在"脆弱性"，但自大的人不太可能出现接受治疗。心理学家玛丽·特朗普, 根据家族史和密切观察推断，她的叔叔唐纳德·特朗普符合自恋的标准，也可能符合"反社会人格障碍"的标准，其中最极端的是"反社会人格障碍"。但她在关于这位前总统的书中指出，“做出准确而全面的诊断, 需要进行全套的心理和神经心理学测试，而他永远不会接受这些测试”。
====

Now brain science is contributing to a better understanding of narcissism. It's unlikely to resolve the debate, but preliminary (a.)预备性的；初步的；开始的 studies are coming down on the side of the clinicians: vulnerability indeed seems to be the hidden underside of grandiosity.


[.my1]
.案例
====

现在，脑科学正在有助于更好地理解自恋。这不太可能解决争论，但初步研究显示临床医生站在一边："脆弱"似乎确实是"浮夸"背后隐藏的一面。
====

Tessa has sometimes felt on top of the world.  “I thought I could just keep perfecting 使完善；使完美；使完备 myself and that someday I would end up as this amazing person surrounded by this amazing life.”

But she also hit severe emotional lows （一生或事业中的）艰难时期，低谷. One came when she realized that `主` the fabulous 极好的；绝妙的 life she imagined `谓` might never come to be. “It was one of the longest periods of depression I've ever gone through.”

“Sometimes I simultaneously 同时地 feel (v.) above everything, above life itself, and also like a piece of trash on the side of the road.” Tessa was diagnosed (v.)诊断（疾病）；判断（问题的原因） with narcissistic personality disorder (NPD) in 2023.


[.my1]
.案例
====

泰莎 (Tessa) 有时感觉自己站在世界之巅。“我以为我可以不断完善自己，有一天我会成为一个被美好生活包围的了不起的人。” 但她的情绪也陷入了严重的低谷。当她意识到她想象中的美好生活可能永远不会实现时，其中一件事发生了。 “这是我经历过的最长的抑郁期之一.” +
“有时我同时感觉自己凌驾于一切之上，凌驾于生活本身之上，同时也感觉自己像路边的一块垃圾. ” 泰莎于 2023 年被诊断出患有自恋型人格障碍 (NPD)。
====


What makes narcissism particularly complex is that it may not always be dysfunctional 机能失调的；功能障碍的. +


[.my1]
.案例
====
.dysfunctional
(a.)( technical 术语) not working normally or properly 机能失调的；功能障碍的

自恋之所以特别复杂，是因为它可能并不总是功能失调的。
====


The relatively functional variety  （同一事物的）不同种类，多种式样 of narcissism includes having, when things are going well, a positive view of oneself and a drive to preserve 保护；维护 one's own well-being 健康；安乐；康乐, while still being able to maintain close relationships with others and tolerate divergences (n.)差异，不同 from an idealized version of oneself. +
"自恋"这种特性, 有不同的版本, 其"相对功能性的变体"包括，当事情进展顺利时，对自己有积极的看法，并有动力维护自己的福祉，同时仍然能够与他人保持密切的关系, 并容忍"与理想化的自己, 其不同版本的"差异。 +


Then there is “pathological” 不理智的；无道理的；无法控制的;病态的；与疾病有关的 narcissism, characterized 以…为特征 by an inability 无能；无力；不能 to maintain a steady sense of self-esteem. +
还有“病态版本的”自恋，其特征是无法保持稳定的自尊感。 +

`主` Those with this condition `谓` protect (v.) an inflated 夸张的；言过其实的; 过高的；高得不合理的 view of themselves at the expense of others and — when that view is threatened — experience (v.) anger, shame, envy 羡慕；忌妒 and other negative emotions. +
患有这种疾病的人, 会以牺牲他人为代价, 来保护自己的"自大感"，当这种观念受到威胁时，就会体验到愤怒、羞耻、嫉妒和其他负面情绪。 +

They can go about （常处于某种状态或以某种方式行动）习惯于 living (v.) relatively normal lives and act out only in certain situations. +
他们可以过着相对正常的生活，只在某些情况下才会表现出来。 +


[.my1]
.案例
====
.go about
( BrE also also ˌgo aˈbout ) to often be in a particular state or behave in a particular way （常处于某种状态或以某种方式行动）习惯于 +
• She often goes around barefoot. 她常常光着脚到处跑。  +

[+ -ing] +
• It's unprofessional 未达专业水平的；违反职业道德的 to go round criticizing your colleagues. 总是指责同事，这不符合职业道德。
====

Narcissistic personality (n.)性格；个性；人格 disorder is a subtype 子类型 of pathological narcissism in which someone has persistent, long-term issues. +
自恋型人格障碍, 是病理性自恋的一种亚型，其中某人有持续的、长期的问题。 +

It often occurs along with other conditions, such as depression, bipolar (a.)双相型障碍的；躁狂抑郁性精神病的 disorder, borderline (a.)所属不清的；两可之间的；临界的 personality 边缘型人格障碍 or antisocial personality disorder. +
它经常与其他疾病一起发生，例如抑郁症、双相情感障碍、边缘性人格, 或反社会人格障碍。 +
 +
In the 1960s and 1970s psychoanalysts 精神分析学家（或医生） Heinz Kohut and Otto Kernberg sketched (v.)概述；简述 what’s now known as the “mask model” of narcissism. +
在 20 世纪 60 年代和 1970 年代，精神分析学家 Heinz Kohut 和 Otto Kernberg 勾画出了现在所谓的自恋“面具模型”。 +

It postulated (v.)假定；假设 that grandiose 华而不实的；浮夸的；不切实际的 traits （人的个性的）特征，特性，特点 such as arrogance (n.)傲慢；自大 and assertiveness (n.)坚定自信，果断 conceal (v.) feelings of insecurity and low self-esteem. +
它假设傲慢和自信等浮夸特征, 掩盖了不安全感和自卑感。 +


[.my1]
.案例
====
.postulate
(v.) /ˈpɒstjuleɪt/  ( formal ) to suggest or accept that sth is true so that it can be used as the basis for a theory, etc. 假定；假设

.as‧ser‧tive
(a.) expressing opinions or desires strongly and with confidence, so that people take notice 坚定自信的；坚决主张的 +
- assertive behaviour 坚定自信的行为
====

The 1980 edition of the Diagnostic and Statistical Manual of Mental Disorders (DSM), the main reference used (v.) by clinicians in the U.S., reflected this insight by including vulnerable features in its definition of NPD, although it emphasized the grandiose  华而不实的；浮夸的；不切实际的 ones. +
1980 年版的《精神疾病诊断与统计手册》(DSM) 是美国临床医生使用的主要参考资料，它通过在 NPD 定义中纳入"脆弱特征", 来反映这一见解，尽管它强调了"浮夸"的性格特征。 +

But some psychiatrists contended （尤指在争论中）声称，主张，认为 that the vulnerability criteria (判断的) 标准 overlapped (v.)（范围方面）部分重叠 too much with those of other personality disorders. +
但一些精神病学家认为，"脆弱性"标准, 与其他人格障碍的标准, 有太多重叠。 +

Borderline personality disorder (BPD), in particular 尤其；特别；格外, shares (v.) with 有同样的感情（或想法、经历等） NPD characteristics 特征 of vulnerability such as difficulty managing (v.) emotions, sensitivity to criticism, and unstable relationships. +
尤其是"边缘性人格障碍"（BPD），与 NPD 一样具有脆弱性，例如难以管理情绪、对批评敏感以, 及不稳定的关系。 +

Subsequent versions of the DSM therefore placed even more weight on grandiose features — such as an exaggerated 夸张的；夸大的；言过其实的 sense of self-importance, a preoccupation 盘算；思虑；长久思考的事情 with fantasies 幻想 of unlimited success and power, an excessive 过分的；过度的 need for admiration  钦佩；赞赏；羡慕 and a lack of empathy 同感；共鸣；同情. +
因此，DSM 的后续版本更加重视"浮夸"的特征，例如"夸大的自我重要感"、老是保持着幻想能有"无限的成功和权力"、对"获得钦佩"的过度需求, 以及缺乏同理心。 +


`主` this focus (n.) on grandiosity `谓` did not accurately represent what he was seeing in narcissistic patients. +
这种对浮夸的关注, 并不能准确地代表他在自恋患者身上看到的情况。 +

It was completely ignoring what typically drives (v.) patients to come to therapy (n.)治疗；疗法, which is vulnerability and distress 忧虑；悲伤；痛苦. +
它完全忽视了通常促使患者接受治疗的因素，即"脆弱性"和"痛苦"。 +
 +
enormous variability in how mental health practitioners （尤指医学或法律界的）从业人员 were conceptualizing (v.)构思；使形成观念；将…概念化（为…） NPD, with dozens of labels for the ways in which narcissism expressed itself. +
心理健康从业者对 NPD 的概念存在巨大差异，自恋的表达方式有数十种标签。 +



[.my1]
.案例
====
.conceptualize
[ VN] ~ sth (as sth) : ( formal ) to form an idea of sth in your mind 构思；使形成观念；将…概念化（为…）
====

But there was also a common thread 线索；脉络；思绪；思路；贯穿的主线: descriptions of both grandiose and vulnerable ways in which the disorder showed up （使）看得见，变得明显，显现出来. +
但也有一个共同点：对这种疾病表现出的"夸张性"和"脆弱性"的方式的描述。 +


researchers have found that both dimensions of narcissism are linked to what psychologists call “antagonism  (n.)对立情绪；对抗情绪；敌对；敌意,” which includes selfishness, deceitfulness 不诚实；欺诈 and callousness 麻木不仁. +
研究人员发现，自恋的两个维度, 都与心理学家所说的“对抗”有关，其中包括自私、欺骗和冷酷。 +


[.my1]
.案例
====
.callous
/ˈkæləs/ +
(a.) not caring about other people's feelings or suffering 冷酷无情的；无同情心的；冷漠的 +
--> 词源同callus, 老茧，硬的。比喻无感情的，冷漠的。原始印欧语词根 kal（硬）
====

But grandiosity 自大 is associated with being assertive (a.)坚定自信的；坚决主张的 and attention  注意；专心；留心；注意力 seeking 寻求关注, whereas vulnerability tends to involve neuroticism 神经质; 具有不稳定、焦虑及有侵略性等的特征 and suffering from anxiety, depression and self-consciousness. +
但自大与自信, 和"寻求关注"有关; 而脆弱, 则往往涉及神经质以及焦虑、抑郁和自我意识的困扰。 +

Vulnerable narcissism also more often goes along with self-harm (which can include hairpulling, cutting, burning and related behaviors that are also found in people with BPD) and risk of suicide than the grandiose form. +
与"夸张性的自恋"相比，"脆弱的自恋"也更常伴随着自残（包括拔头发、剪头发、烧头发和相关行为，这些行为也出现在边缘性人格障碍患者身上）和自杀风险。 +
 +
The two manifestations 显示；表明；表示;（幽灵的）显现，显灵 of narcissism are also linked to different kinds of problems in relationships. +
自恋的两种表现, 也与"人际关系障碍问题"中的不同类型, 有关。 +

In grandiose states, people with NPD may be more vindictive (a.)想复仇的；报复性的；怀恨的 and domineering (a.)专横的；盛气凌人的 toward others, whereas in vulnerable phases they may be more withdrawn (a.)沉默寡言的；怕羞的；内向的 and exploitable 可开发的；可利用的. +
在自大性的类型中,，患有自恋型人格障碍的人, 可能会对他人更加报复和专横，而在脆弱的阶段，他们可能会更加孤僻和容易被利用。 +


Jacob Skidmore, a 23-year-old with NPD, says he often flips (v.)（使）快速翻转，迅速翻动 from feeling grandiose to vulnerable, sometimes multiple times a day. +
雅各布·斯基德莫尔 (Jacob Skidmore) 是一位 23 岁的 NPD 患者，他表示自己常常会从自大到脆弱，有时一天会发生好几次。 +

If he’s getting positive attention from others or achieves his goals, he experiences (v.) grandiose “highs” when he feels confident and secure. +
如果他得到了别人的积极关注或实现了自己的目标，当他感到自信和安全时，他就会体验到巨大的“高潮”。 +
 +

But when these sources of ego boosts — something he refers to as “self-esteem  自尊（心） juice” — dry up, he finds himself slipping (v.)滑倒；滑跤 into lows when an overwhelming feeling of shame might stop him from even leaving his home. +
但当这些自我提升的源泉——他称之为“自尊果汁”——枯竭时，他发现自己陷入了低谷，压倒性的羞耻感可能会令他甚至不想踏出家门。 +


`主` The desire to fill up 填补；装满 on self-esteem `谓` has driven many of Skidmore’s more grandiose behaviors — ① whether it was making himself the de facto 实际上存在的（不一定合法） leader of multiple social groups where he referred to himself as “the Emperor” and punished those who angered him /② or forging (v.)形成，缔造 relationships purely for the sake of boosting his self-esteem. +
对自尊的渴望, 驱使斯基德莫尔做出许多更宏伟的行为 —— 无论是让自己成为多个社会群体事实上的领导者，他称自己为“皇帝”并惩罚那些激怒他的人，还是建立关系纯粹是为了提升他的自尊心。 +

Skidmore hasn’t always presented himself in grandiose ways: when he was younger, he was much more outwardly (ad.)表面上；外表上 sensitive and insecure. +
斯基德莫尔并不总是以浮夸的方式展现自己：当他年轻时，他外表上更加敏感和缺乏安全感。 +

“I remember looking in the mirror and thinking about how disgusting 令人反感的，令人恶心的；令人气愤的 I was and how much I hated myself.” +
“我记得看着镜子，想着我是多么恶心，我多么讨厌自己。” +


Clinicians' evaluations 评价，评估, as well as studies in the wider population, support the idea that narcissists oscillate (v.)（情感或行为）摇摆，波动，变化; 波动；振荡 between these two states. +
临床医生的评估, 以及对更广泛人群的研究, 都支持自恋者在这两种状态之间摇摆的观点。 +


[.my1]
.案例
====
.oscillate
/ˈɑːsɪleɪt/ +
(v.) ( physics 物) to keep moving from one position to another and back again 摆动；振动
====


They found that whereas （用以比较或对比两个事实）然而，但是，尽管 vulnerability and grandiosity do not generally coexist (v.) in the same moment 片刻；瞬间, people who are overall 一般来说；大致上；总体上 more grandiose also undergo (v.) periods of vulnerability — whereas those who are generally more vulnerable don’t experience much grandiosity. +
他们发现，虽然脆弱和自大通常不会同时存在，但整体上比较自大的人, 也会经历脆弱时期，而那些通常比较脆弱的人, 则不会经历太多自大。 +
 +
Some studies suggest that the overlap may depend on the severity of the narcissism: vulnerability may be more likely (a.) to appear in highly grandiose individuals. +
一些研究表明，重叠可能取决于自恋的严重程度："脆弱性"可能更可能出现在"高度自大"的人身上。 +
 +

To Diana Diamond, a clinical psychologist at the City University of New York, such findings suggest that the mask model is too simple. +
对于纽约城市大学的临床心理学家戴安娜戴蒙德来说，这些发现表明"面具模型"过于简单。 +
“ +


The picture is much more complex — vulnerability and grandiosity exist (v.) in dynamic relation to each other, and they fluctuate (v.)（大小、数量、质量等）波动；（在…之间）起伏不定 according to what the individual is encountering (v.) in life, the stage of their own development.” +
情况要复杂得多——脆弱性和自大性, 彼此存在着动态关系，并且根据个人在生活中遇到的情况, 以及自身发展的阶段而波动。” +


[.my1]
.案例
====
.fluctuate
-->  fluctu(-flu-)流 + -ate动词词尾
====


Although grandiose people may sometimes feel (v.) vulnerable, that vulnerability isn’t necessarily linked to insecurities, Miller argues. +
米勒认为，虽然自大的人有时可能会感到脆弱，但这种脆弱并不一定与不安全感有关。 +

“I think they feel really angry because `主` what they cherish (v.)珍爱；钟爱；爱护 more than anything `系` is a sense of superiority 优越（性）；优势 and status — and when that’s called into question 怀疑；引起怀疑, they’re going to lash 鞭打；抽打 back,” +
“我认为他们感到非常愤怒，因为他们最珍惜的是优越感和地位感——当这种感觉受到质疑时，他们会反击，” +
 +


[.my1]
.案例
====
.call sth into ˈquestion
to doubt sth or make others doubt sth 怀疑；引起怀疑 +
SYN question +
• His honesty has never been called into question. 他的诚实从未受到过怀疑。
====


These differences (n.) in perspective  态度；观点；思考方法 may arise because different types of psychologists are studying different populations. +
这些观点上的差异, 可能是因为不同类型的心理学家正在研究不同的人群。 +

In a 2017 study, researchers surveyed (v.) 23 clinical psychologists and 22 social and/or personality psychologists (who do not work with patients) and found that although both groups viewed grandiosity as an essential 完全必要的；必不可少的；极其重要的;本质的；基本的；根本的 aspect of narcissism, clinical psychologists were slightly more likely to view vulnerability as being at its core. +
在 2017 年的一项研究中，研究人员调查了 23 名临床心理学家和 22 名社会和/或人格心理学家（他们不与患者一起工作），发现虽然两组人都认为"自大"是自恋的一个重要方面，但临床心理学家更有可能认为"脆弱"作为其核心。 +


Most narcissists who seek help are generally more vulnerable, Miller notes: “These are wounded people who come in to seek treatment for their wounds.” To him, that means clinics might not be the best place to study narcissism —at least not its grandiose aspect. +
米勒指出，大多数寻求帮助的自恋者通常更容易受到伤害：“这些人是来寻求治疗的受伤者。”对他来说，这意味着诊所可能不是研究自恋的最佳场所——至少不是研究自恋的浮夸方面。 +

It’s “a little bit like trying to learn about a lion’s behavior in a zoo,” he says. +
他说，这“有点像试图了解动物园里狮子的行为”。 +


The unwillingness to seek therapy is especially true of “malignant narcissists,” who, in addition to the usual characteristics, exhibit antisocial and psychopathic features such as lying chronically or enjoying inflicting pain or suffering on others. +
不愿意寻求治疗的“恶性自恋者”尤其如此，除了通常的特征外，他们还表现出反社会和精神病态的特征，例如长期撒谎或享受给他人造成痛苦或折磨。 +
 +
Marianne (whose name has been changed for privacy) recalls her father, a brilliant scientist whom her own therapist deemed a malignant narcissist . +
玛丽安（出于隐私原因，化名）回忆起她的父亲，一位才华横溢的科学家，她自己的治疗师认为他是一个恶性自恋者。 +

(He never sought therapy.) +
（他从未寻求治疗。） +
 +
He implemented stringent rules. +
他执行了严格的规则。 +
“There was [hardly] a day without that kind of drama—one person being isolated, punished, humiliated, being called out.” +
“几乎没有一天没有这样的戏剧性事件——一个人被孤立、惩罚、羞辱、被点名。” +
 +
Her father also pitted her siblings and their mother against one another to prevent them from forging close connections—and he constantly looked for flaws in those around him. +
她的父亲还让她的兄弟姐妹和他们的母亲互相对抗，以阻止他们建立密切的联系——他不断地寻找周围人的缺点。 +
Marianne recalls dinner parties at home where her father spent hours trying to pinpoint weaknesses among the other husbands and to hurt couples' opinions of each other. +
玛丽安回忆起在家里举行的晚宴上，她的父亲花了几个小时试图找出其他丈夫的弱点，并破坏夫妻之间对彼此的看法。 +
When Marianne brought home boyfriends, her father challenged them and tried to prove that he was superior. +
当玛丽安带男朋友回家时，她的父亲向他们提出挑战，并试图证明自己更优秀。 +
And despite being a dazzling academic who easily charmed people when they first met, he got fired time and time again because of conflicts at the universities where he worked. +
尽管他是一位耀眼的学者，一见面就很容易被人迷住，但他却一次又一次因为所在大学的冲突而被解雇。 +
“It was all about one-upmanship,” she says. +
“一切都是为了比人更胜一筹，”她说。 +
“His impulse to destroy anything that was shiny, that was popular, that was loved—it overwhelmed everything else.” +
“他想要摧毁任何闪亮的、流行的、受人喜爱的东西的冲动——它压倒了其他一切。” +
 +
Malignant narcissists often pose the greatest challenge for therapists—and they may be particularly dangerous in leadership positions, Diamond notes. +
戴蒙德指出，恶性自恋者常常给治疗师带来最大的挑战，他们在领导职位上可能尤其危险。 +
They can have deficient moral functioning while exerting an enormous amount of influence on followers. +
他们的道德功能可能存在缺陷，同时对追随者施加巨大影响。 +
“I think this is something that’s going on right now, with the rise of authoritarianism worldwide,” she adds. +
“我认为随着威权主义在全球范围内的兴起，这就是现在正在发生的事情，”她补充道。 +
 +
AN ADVERSE CHILDHOOD?  不幸的童年？ +
 +
Research with identical and nonidentical twins suggests that narcissism may be at least partially genetically heritable, but other studies indicate that dysfunctional parenting might also play a significant role. +
对同卵和异卵双胞胎的研究表明，自恋可能至少部分是遗传性的，但其他研究表明，功能失调的养育方式也可能发挥重要作用。 +
Grandiosity may derive from caregivers holding inflated views about their child’s superiority, whereas vulnerability may originate in having a caregiver who was cold, neglectful, abusive or invalidating. +
夸大可能源于照顾者对孩子的优越性抱有夸大的看法，而脆弱性可能源于照顾者冷漠、疏忽、虐待或虚弱。 +
Complicating matters, some studies find overvaluation also plays a role in vulnerable narcissism, whereas others fail to find a link between parenting and grandiosity. +
让事情变得更加复杂的是，一些研究发现，高估也在脆弱的自恋中发挥着作用，而另一些研究则未能找到养育子女与浮夸之间的联系。 +
“Children who develop NPD may have felt seen and appreciated when they achieved or behaved in a certain way that satisfied a caregiver’s expectations but ignored, dismissed or scolded when they failed to do so,” Ronningstam summarizes in her guide to the disorder. +
Ronningstam 在她的自闭症指南中总结道：“患有 NPD 的孩子，当他们达到或以某种方式满足照顾者的期望时，可能会感到受到关注和赞赏，但当他们未能做到这一点时，他们可能会被忽视、解雇或责骂。” +
 +
Skidmore attributes his own NPD to both genes and painful childhood experiences. +
斯基德莫尔将自己的 NPD 归因于基因和痛苦的童年经历。 +
“I’ve never met a narcissist who has not had trauma,” he says. +
“我从未见过没有受过创伤的自恋者，”他说。 +
“People just use love as this carrot on a stick [that] they hang above your head, and they tell you to behave or they’ll take it away. +
“人们只是把爱当作一根棍子上的胡萝卜，挂在你的头顶上，他们告诉你要守规矩，否则他们会把它拿走。 +
And so I have this mindset of, ‘Well then, screw it! I don’t need love. +
所以我的心态是，‘那么，管它呢！我不需要爱。 +
I can take admiration, achievements, my intelligence—you can’t take those things away from me.’ +
我可以夺走钦佩、成就和智慧——你不能把这些东西从我身上夺走。 +
 +
Many researchers nonetheless say a lot more work is needed to determine what role, if any, parenting plays. +
尽管如此，许多研究人员表示，还需要做更多的工作来确定养育子女所扮演的角色（如果有的话）。 +
Miller points out that most research to date of grandiosity, in particular, has found small effects. +
米勒指出，迄今为止，大多数关于浮夸的研究都发现了一些微小的影响。 +
Further, the work was done retrospectively—asking people to recall their past experiences—rather than prospectively to see how early life experiences affect outcomes. +
此外，这项工作是回顾性进行的——要求人们回忆过去的经历——而不是前瞻性地观察早期生活经历如何影响结果。 +
 +
There is another way to study what is going on with a narcissist, however: look inside. +
然而，还有另一种方法可以研究自恋者的情况：向内看。 +
In a study published in 2015, researchers at the University of Michigan recruited 43 boys aged 16 or 17 and asked them to fill out the Narcissism Personality Inventory, a questionnaire that primarily measures grandiose traits. +
在 2015 年发表的一项研究中，密歇根大学的研究人员招募了 43 名 16 岁或 17 岁的男孩，要求他们填写自恋人格调查表，这是一份主要衡量浮夸特质的调查问卷。 +
The teenagers then played Cyberball, a virtual ball-tossing game, while their brain activity was measured using functional magnetic resonance imaging (fMRI), a noninvasive neuroimaging method that enables researchers to observe the brain at work. +
然后，这些青少年玩了 Cyber​​ball，一种虚拟的抛球游戏，同时使用功能性磁共振成像 (fMRI) 来测量他们的大脑活动，这是一种非侵入性神经成像方法，使研究人员能够观察工作中的大脑。 +
 +
Cyberball tests how well people deal with social exclusion. +
网络球测试人们应对社会排斥的能力。 +
Participants are told that they’re playing with two other people, although they are actually playing with a computer. +
参与者被告知他们正在和另外两个人一起玩，尽管他们实际上是在玩电脑。 +
In some rounds, the virtual players include the human participant; in others, the virtual players begin by tossing the ball to everyone but later pass it just between themselves—cutting the participant out of the game. +
在某些回合中，虚拟玩家包括人类参与者；在其他游戏中，虚拟玩家一开始将球扔给每个人，但随后只在他们之间传递——将参与者从游戏中剔除。 +
 +
The teenagers with higher levels of grandiose narcissism turned out to have greater activity in the so-called social pain network than those with lower scores. +
事实证明，自恋程度较高的青少年比得分较低的青少年在所谓的社会痛苦网络中更加活跃。 +
This network is a collection of brain regions—including parts of the insula and the anterior cingulate cortex—that prior studies had found were associated with distress in the face of social exclusion. +
该网络是大脑区域的集合，包括部分岛叶和前扣带皮层，之前的研究发现这些区域与面对社会排斥时的痛苦有关。 +
Interestingly, the researchers did not find differences in the boys' self-reports of distress. +
有趣的是，研究人员没有发现男孩们对痛苦的自我报告存在差异。 +
In another revealing fMRI study, Jauk and his Graz colleagues found that men (but not women) with higher levels of grandiose narcissism showed more activity in parts of the anterior cingulate cortex associated with negative emotions and social pain when viewing images of themselves compared with images of close friends or strangers. +
在另一项揭示性功能磁共振成像研究中，Jauk 和他的格拉茨同事发现，与观看自己的图像相比，自恋水平较高的男性（但不是女性）在观看自己的图像时，与负面情绪和社会痛苦相关的前扣带皮层部分表现出更多的活动。亲密的朋友或陌生人。 +
 +
The bodies of narcissists bear evidence of elevated stress. +
自恋者的身体上有压力升高的证据。 +
Studies indicate that men with more narcissism have higher levels of the stress hormone cortisol than those with less narcissism. +
研究表明，自恋程度较高的男性比自恋程度较低的男性压力荷尔蒙皮质醇水平更高。 +
 +
Such findings suggest that “vulnerability is always there but maybe not always expressed,” Jauk says. +
这些发现表明“脆弱性始终存在，但可能并不总是表现出来，”乔克说。 +
“And under particular circumstances, such as in the lab, you can observe signs of vulnerability at a physiological level, even if people say, ‘I don’t have vulnerability.’” He adds, however, that these studies are far from the last word on the matter: many of them have a small number of subjects, and some have reported contradicting findings. +
“在特定情况下，比如在实验室里，你可以在生理层面上观察到脆弱的迹象，即使人们说，‘我没有脆弱’。”不过，他补充说，这些研究与实际情况相去甚远。关于此事的最后一句话：其中许多研究对象的数量很少，有些报告的研究结果相互矛盾。 +
Follow-up studies, ideally with a larger number of individuals, are needed to validate their results. +
需要进行后续研究，最好是对更多的人进行研究，以验证他们的结果。 +
The neuroscience of narcissism “is incredibly interesting, but at the same time, I’m very hesitant to interpret any of these results,” says Mitja Back, a psychologist at the University of Münster in Germany. +
德国明斯特大学心理学家米贾·巴克 (Mitja Back) 表示，自恋的神经科学“非常有趣，但与此同时，我对解释这些结果非常犹豫”。 +
 +
TOWARD TREATMENTS 寻求治疗 +
 +
To date, there have been no randomized clinical trials for treatments specific for narcissistic personality disorder. +
迄今为止，还没有针对自恋型人格障碍的特异性治疗的随机临床试验。 +
Clinicians have, however, begun to adapt psychotherapies that have proved to be effective in other related conditions, such as borderline personality disorder. +
然而，临床医生已经开始采用心理疗法，这些疗法已被证明对其他相关疾病（例如边缘性人格障碍）有效。 +
Treatments currently used include “mentalization,” which aims to help individuals make sense of both their own and others' mental states, and “transference,” which focuses on enhancing a person’s ability to self-reflect, take the perspective of others and regulate their emotions. +
目前使用的治疗方法包括“心智化”和“移情”，前者旨在帮助个人理解自己和他人的心理状态，后者侧重于增强一个人自我反思、站在他人角度并调节自己情绪的能力。情绪。 +
But there is still a dire need for effective treatments. +
但仍然迫切需要有效的治疗方法。 +
 +
“People with pathological narcissism and narcissistic personality disorder have a reputation of not changing or dropping off from treatment,” +
“患有病态自恋和自恋型人格障碍的人以不改变或放弃治疗而闻名。”



'''


== What Is Narcissism? Science Confronts a Widely Misunderstood Phenomenon

But chances are you've encountered a narcissist, and they looked nothing like Trump, Musk or Modi. Up to 6 percent of the U.S. population, mostly men, is estimated to have had narcissistic personality disorder during some period of their lives. And the condition manifests in confoundingly different ways. People with narcissism “may be grandiose or self-loathing, extraverted or socially isolated, captains of industry or unable to maintain steady employment, model citizens or prone to antisocial activities,” according to a review paper on diagnosing the disorder.



Clinicians note several dimensions on which narcissists vary. They may function extremely well, with successful careers and vibrant social lives, or very poorly. They may (or may not) have other disorders, ranging from depression to sociopathy. And although most people are familiar with the “grandiose” version of narcissism—as displayed by an arrogant and pompous person who craves attention—the disorder also comes in a “vulnerable” or “covert” form, where individuals suffer from internal distress and fluctuations in self-esteem. What these seeming opposites have in common is an extreme preoccupation with themselves.


Most psychologists who treat patients say that grandiosity and vulnerability coexist in the same individual, showing up in different situations. Among academic psychologists, however, many contend that these two traits do not always overlap. This debate has raged for decades without resolution, most likely because of a conundrum: vulnerability is almost always present in a therapist's office, but individuals high in grandiosity are unlikely to show up for treatment. Psychologist Mary Trump deduces, from family history and close observation, that her uncle, Donald Trump, meets the criteria for narcissistic as well as, probably, antisocial personality disorder, at the extreme end of which is sociopathy. But “coming up with an accurate and comprehensive diagnosis would require a full battery of psychological and neuropsychological tests that he'll never sit for,” she notes in her book on the former president.


Now brain science is contributing to a better understanding of narcissism. It's unlikely to resolve the debate, but preliminary studies are coming down on the side of the clinicians: vulnerability indeed seems to be the hidden underside of grandiosity.


Tessa has sometimes felt on top of the world.  “I thought I could just keep perfecting myself and that someday I would end up as this amazing person surrounded by this amazing life.” But she also hit severe emotional lows. One came when she realized that the fabulous life she imagined might never come to be. “It was one of the longest periods of depression I've ever gone through.”

“Sometimes I simultaneously feel above everything, above life itself, and also like a piece of trash on the side of the road.” Tessa was diagnosed with narcissistic personality disorder (NPD) in 2023.



What makes narcissism particularly complex is that it may not always be dysfunctional. +


The relatively functional variety of narcissism includes having, when things are going well, a positive view of oneself and a drive to preserve one's own well-being, while still being able to maintain close relationships with others and tolerate divergences from an idealized version of oneself. Then there is “pathological” narcissism, characterized by an inability to maintain a steady sense of self-esteem. Those with this condition protect an inflated view of themselves at the expense of others and—when that view is threatened—experience anger, shame, envy and other negative emotions. They can go about living relatively normal lives and act out only in certain situations. Narcissistic personality disorder is a subtype of pathological narcissism in which someone has persistent, long-term issues. It often occurs along with other conditions, such as depression, bipolar disorder, borderline personality or antisocial personality disorder.




In the 1960s and 1970s psychoanalysts Heinz Kohut and Otto Kernberg sketched what's now known as the “mask model” of narcissism. It postulated that grandiose traits such as arrogance and assertiveness conceal feelings of insecurity and low self-esteem. The 1980 edition of the Diagnostic and Statistical Manual of Mental Disorders (DSM), the main reference used by clinicians in the U.S., reflected this insight by including vulnerable features in its definition of NPD, although it emphasized the grandiose ones. But some psychiatrists contended that the vulnerability criteria overlapped too much with those of other personality disorders. Borderline personality disorder (BPD), in particular, shares with NPD characteristics of vulnerability such as difficulty managing emotions, sensitivity to criticism, and unstable relationships. Subsequent versions of the DSM therefore placed even more weight on grandiose features—such as an exaggerated sense of self-importance, a preoccupation with fantasies of unlimited success and power, an excessive need for admiration and a lack of empathy.


this focus on grandiosity did not accurately represent what he was seeing in narcissistic patients. It was completely ignoring what typically drives patients to come to therapy, which is vulnerability and distress.


enormous variability in how mental health practitioners were conceptualizing NPD, with dozens of labels for the ways in which narcissism expressed itself. But there was also a common thread: descriptions of both grandiose and vulnerable ways in which the disorder showed up.


researchers have found that both dimensions of narcissism are linked to what psychologists call “antagonism,” which includes selfishness, deceitfulness and callousness. But grandiosity is associated with being assertive and attention seeking, whereas vulnerability tends to involve neuroticism and suffering from anxiety, depression and self-consciousness. Vulnerable narcissism also more often goes along with self-harm (which can include hairpulling, cutting, burning and related behaviors that are also found in people with BPD) and risk of suicide than the grandiose form.


The two manifestations of narcissism are also linked to different kinds of problems in relationships. In grandiose states, people with NPD may be more vindictive and domineering toward others, whereas in vulnerable phases they may be more withdrawn and exploitable.



Jacob Skidmore, a 23-year-old with NPD, says he often flips from feeling grandiose to vulnerable, sometimes multiple times a day. If he's getting positive attention from others or achieves his goals, he experiences grandiose “highs” when he feels confident and secure.

But when these sources of ego boosts—something he refers to as “self-esteem juice” — dry up, he finds himself slipping into lows when an overwhelming feeling of shame might stop him from even leaving his home.



The desire to fill up on self-esteem has driven many of Skidmore's more grandiose behaviors—whether it was making himself the de facto leader of multiple social groups where he referred to himself as “the Emperor” and punished those who angered him or forging relationships purely for the sake of boosting his self-esteem. Skidmore hasn't always presented himself in grandiose ways: when he was younger, he was much more outwardly sensitive and insecure. “I remember looking in the mirror and thinking about how disgusting I was and how much I hated myself.”



Clinicians' evaluations, as well as studies in the wider population, support the idea that narcissists oscillate between these two states.


They found that whereas vulnerability and grandiosity do not generally coexist in the same moment, people who are overall more grandiose also undergo periods of vulnerability—whereas those who are generally more vulnerable don't experience much grandiosity.

Some studies suggest that the overlap may depend on the severity of the narcissism:  vulnerability may be more likely to appear in highly grandiose individuals.


To Diana Diamond, a clinical psychologist at the City University of New York, such findings suggest that the mask model is too simple. “

The picture is much more complex—vulnerability and grandiosity exist in dynamic relation to each other, and they fluctuate according to what the individual is encountering in life, the stage of their own development.”



Although grandiose people may sometimes feel vulnerable, that vulnerability isn't necessarily linked to insecurities, Miller argues. “I think they feel really angry because what they cherish more than anything is a sense of superiority and status—and when that's called into question, they're going to lash back,”



These differences in perspective may arise because different types of psychologists are studying different populations. In a 2017 study, researchers surveyed 23 clinical psychologists and 22 social and/or personality psychologists (who do not work with patients) and found that although both groups viewed grandiosity as an essential aspect of narcissism, clinical psychologists were slightly more likely to view vulnerability as being at its core.


Most narcissists who seek help are generally more vulnerable, Miller notes: “These are wounded people who come in to seek treatment for their wounds.” To him, that means clinics might not be the best place to study narcissism—at least not its grandiose aspect. It's “a little bit like trying to learn about a lion's behavior in a zoo,” he says.


The unwillingness to seek therapy is especially true of “malignant narcissists,” who, in addition to the usual characteristics, exhibit antisocial and psychopathic features such as lying chronically or enjoying inflicting pain or suffering on others.


Marianne (whose name has been changed for privacy) recalls her father, a brilliant scientist whom her own therapist deemed a malignant narcissist . (He never sought therapy.)

He implemented stringent rules.  “There was [hardly] a day without that kind of drama—one person being isolated, punished, humiliated, being called out.”


Her father also pitted her siblings and their mother against one another to prevent them from forging close connections—and he constantly looked for flaws in those around him. Marianne recalls dinner parties at home where her father spent hours trying to pinpoint weaknesses among the other husbands and to hurt couples' opinions of each other. When Marianne brought home boyfriends, her father challenged them and tried to prove that he was superior. And despite being a dazzling academic who easily charmed people when they first met, he got fired time and time again because of conflicts at the universities where he worked. “It was all about one-upmanship,” she says. “His impulse to destroy anything that was shiny, that was popular, that was loved—it overwhelmed everything else.”


Malignant narcissists often pose the greatest challenge for therapists—and they may be particularly dangerous in leadership positions, Diamond notes. They can have deficient moral functioning while exerting an enormous amount of influence on followers. “I think this is something that's going on right now, with the rise of authoritarianism worldwide,” she adds.




AN ADVERSE CHILDHOOD?  +


Research with identical and nonidentical twins suggests that narcissism may be at least partially genetically heritable, but other studies indicate that dysfunctional parenting might also play a significant role. Grandiosity may derive from caregivers holding inflated views about their child's superiority, whereas vulnerability may originate in having a caregiver who was cold, neglectful, abusive or invalidating. Complicating matters, some studies find overvaluation also plays a role in vulnerable narcissism, whereas others fail to find a link between parenting and grandiosity. “Children who develop NPD may have felt seen and appreciated when they achieved or behaved in a certain way that satisfied a caregiver's expectations but ignored, dismissed or scolded when they failed to do so,” Ronningstam summarizes in her guide to the disorder.


Skidmore attributes his own NPD to both genes and painful childhood experiences. “I've never met a narcissist who has not had trauma,” he says. “People just use love as this carrot on a stick [that] they hang above your head, and they tell you to behave or they'll take it away. And so I have this mindset of, ‘Well then, screw it! I don't need love. I can take admiration, achievements, my intelligence—you can't take those things away from me.’


Many researchers nonetheless say a lot more work is needed to determine what role, if any, parenting plays. Miller points out that most research to date of grandiosity, in particular, has found small effects. Further, the work was done retrospectively—asking people to recall their past experiences—rather than prospectively to see how early life experiences affect outcomes.


There is another way to study what is going on with a narcissist, however: look inside. In a study published in 2015, researchers at the University of Michigan recruited 43 boys aged 16 or 17 and asked them to fill out the Narcissism Personality Inventory, a questionnaire that primarily measures grandiose traits. The teenagers then played Cyberball, a virtual ball-tossing game, while their brain activity was measured using functional magnetic resonance imaging (fMRI), a noninvasive neuroimaging method that enables researchers to observe the brain at work.


Cyberball tests how well people deal with social exclusion. Participants are told that they're playing with two other people, although they are actually playing with a computer. In some rounds, the virtual players include the human participant; in others, the virtual players begin by tossing the ball to everyone but later pass it just between themselves—cutting the participant out of the game.


The teenagers with higher levels of grandiose narcissism turned out to have greater activity in the so-called social pain network than those with lower scores. This network is a collection of brain regions—including parts of the insula and the anterior cingulate cortex—that prior studies had found were associated with distress in the face of social exclusion. Interestingly, the researchers did not find differences in the boys' self-reports of distress. In another revealing fMRI study, Jauk and his Graz colleagues found that men (but not women) with higher levels of grandiose narcissism showed more activity in parts of the anterior cingulate cortex associated with negative emotions and social pain when viewing images of themselves compared with images of close friends or strangers.


The bodies of narcissists bear evidence of elevated stress. Studies indicate that men with more narcissism have higher levels of the stress hormone cortisol than those with less narcissism.


Such findings suggest that “vulnerability is always there but maybe not always expressed,” Jauk says. “And under particular circumstances, such as in the lab, you can observe signs of vulnerability at a physiological level, even if people say, ‘I don't have vulnerability.’” He adds, however, that these studies are far from the last word on the matter: many of them have a small number of subjects, and some have reported contradicting findings. Follow-up studies, ideally with a larger number of individuals, are needed to validate their results. The neuroscience of narcissism “is incredibly interesting, but at the same time, I'm very hesitant to interpret any of these results,” says Mitja Back, a psychologist at the University of Münster in Germany.



TOWARD TREATMENTS

To date, there have been no randomized clinical trials for treatments specific for narcissistic personality disorder. Clinicians have, however, begun to adapt psychotherapies that have proved to be effective in other related conditions, such as borderline personality disorder. Treatments currently used include “mentalization,” which aims to help individuals make sense of both their own and others' mental states, and “transference,” which focuses on enhancing a person's ability to self-reflect, take the perspective of others and regulate their emotions. But there is still a dire need for effective treatments.


“People with pathological narcissism and narcissistic personality disorder have a reputation of not changing or dropping off from treatment,”


'''

