

= Academic sexism 学术界里的性别歧视
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css

'''


== Academic sexism （尤指对女性的）性别歧视，性别偏见

In any case 无论如何;不管怎样, the survey yielded (v.)出产（作物）；产生（收益、效益等）；提供 more than enough reports of sexual harassment 骚扰.

Nearly 2,000 respondents said /they had been embarrassed or offended by inappropriate (a.)不适当的；不合适的 gestures （表明感情或意图的）姿态，表示; 手势, 示意动作, remarks 言论；评述 or materials /from other economists.
Hundreds reported(v.) experiences of _attempted (a.)犯罪等未遂的 or actual sexual assault_ (n.)侵犯他人身体（罪） by a colleague or student in the past ten years.

And 267 reported(v.) that /they would ① have been rewarded (v.) /条件状 had they co-operated with unwanted sexual attention 兴趣；关注;特别照料（或行动、处理）, or ② threatened (v.) with retaliation (n.) 报复 /had they not.

`主` _A meta-analysis 荟萃分析；元分析 of studies_ of the prevalence (n.)流行, 普遍盛行 of sexual harassment in 2003 /`谓` ranked 把…分等级；属于某等级 academia 学术界  *second only to* the armed forces.




[.my1]
.标题
====
.harassment
Harassment is behaviour which is intended to trouble or annoy someone, for example repeated attacks on them /or attempts to cause them problems. 骚扰

.assault
(n.)(=~ (on/upon sb) the crime of attacking sb physically 侵犯他人身体（罪）；侵犯人身罪

.Sexual attention
指的是不受欢迎的"性关注"或性骚扰。


.attention
interest that people show in sb/sth 兴趣；关注; /special care, action or treatment 特别照料（或行动、处理） +
- the report's attention to detail 报告对细节的关注 +
- Please pay attention (= listen carefully) to what I am saying. 请注意听我讲的话。

.retaliation
/rɪˈtælieɪt/ (n.) ~ (against sb/sth) (for sth) : action that a person takes against sb who has harmed them in some way 报复 +
-> 来自拉丁语 retaliare,偿还，返还，来自 re-,向后，往回，talis,同样，同类，来自 PIEtod,指 示代词，词源同 this,that.即原样返还的，后用于指报仇，以眼还眼，以牙还牙。

[.my2]
无论如何，调查得出的性骚扰报告已经足够多了。近2000名受访者表示，他们曾因其他经济学家不当示意姿势、言论或材料而感到尴尬或被冒犯。 +
报告说，在过去的十年里，有数百人遭遇过同事或学生的试图或实实在在的性侵犯经历。267人报告说，如果他们在不想要的性关注下合作，他们会得到奖励。或者, 如果他们不合作，就会受到报复的威胁. +
2003年时,一项对性骚扰流行情况的荟萃分析显示，学术界仅次于军队。
====



Our interviewees found (v.) /it much easier to name (v.) prominent bullies 著名的恶霸 than notorious 臭名昭著的 harassers 骚扰者. +
A senior professor said that /she had seen a special nastiness 不洁,污秽;肮脏,龌龊 /后定 reserved 保留；贮备 for people regarded as 看待为, 视为 vulnerable （身体上或感情上）脆弱的，易受…伤害的, including women.
Others claimed 宣称；声称；断言 /only to have seen “assholes” 屁眼;混蛋,很讨厌的人 who were indiscriminate(a.) 随意的；恣意的；不加选择的 in their aggression 侵犯；挑衅；侵略.



[.my1]
.标题
====

.reserve
(v.) ~ sth (for sb/sth): to keep sth for sb/sth, so that it cannot be used by any other person or for any other reason 保留；贮备 +
- I'd prefer to reserve (my) judgement (= not make a decision) until I know all the facts. 在了解全部事实之前我不想发表意见。


.vulnerable
⇒ 来自拉丁语 vulnus,伤口，来自 PIE wele,拔，击打，词源同 wool,vulture.引申词义有伤口的， 脆弱的。

.indiscriminate
⇒ dis-, 分开，散开。-crim, 区分，词源同crime, crisis. 即区分开，区别对待，歧视。

[.my2]
我们的受访者发现，比起臭名昭著的骚扰者，说出有名的恶霸要容易得多。一位资深教授说，她发现了一种特别的肮脏，专门保留给并施加在那些被视为脆弱的人身上，包括女性。另一些人则声称, 他们只看到了那些不论对方身份为何人, 都无差别进行骚扰的“混蛋”。
====


Unfair treatment can be unwitting (a.)不知情的；糊里糊涂的；无意的. Senior professors may be unconsciously 无意地；不知不觉地 drawn (v.)吸引；招引；使感兴趣 to favour (v.) students /who look like their younger selves 自己.
They may like chatting about work /over a drink, which young women may find uncomfortable. One PhD student said /she felt that female students found it harder to connect with male professors. She suspected /that *was partly due (a.) to* unspoken worries about harassment.



[.my1]
.标题
====
.unwitting
(a.) not aware of what you are doing or of the situation you are involved in 不知情的；糊里糊涂的；无意的

.selves
self的复数. 自己

[.my2]
不公平的待遇, 可能是无意识中造成的。资深教授可能会无意识地偏爱那些看起来像他们年轻时的自己的学生。他们可能喜欢边喝酒边谈工作，这可能会让年轻女性感到不舒服。一位博士生说，她觉得女学生很难与男教授沟通。她怀疑这在一定程度上是由于对骚扰的潜在担忧。
====



Then there is the style of seminars （大学教师带领学生作专题讨论的）研讨课, for which /economics is notorious.
Interruptions and intense  有强烈感情（或意见、想法）的；尖锐的；热切的 questioning /are supposed 据说的,误以为的 to weed (v.) out 剔除，淘汰（不需要的或较差的人或物） errors /and uncover (v.)发现；揭露；揭发 sloppy 马虎的；凌乱的；草率的 thinking.

[.my2]
还有一种问题, 是研讨会的风格，经济学在这方面臭名昭著。打断他人发言, 和激烈的提问, 被看做是能排除错误，并发现马虎想法。
打断和强烈的提问本应消除错误，揭露草率的思维。

And several interviewees *told of* 谈到，说到;公布；说明 supportive 给予帮助的；支持的；鼓励的；同情的 sub-fields and departments, where the primary purpose was not to tear down the speaker.  +
But one said /she felt like quitting 放弃，退出 /after seeing how a female presenter was treated.
Another economist reported /*being asked* during a presentation 展示会；介绍会；发布会 *whether* 是否（表选择或可能性） she knew any economics, and being interrupted incessantly 不停地，不间断地.

[.my2]
几位受访者谈到了支持性的子领域和部门，那里的主要目的不是诋毁演讲者。但其中一位表示，在看到一位女发言人遭受的待遇后，她想要退出。
另一位经济学家报告说，她在一次演讲中被问及是否懂经济学，她的发言也不时被打断。

Among macroeconomists 宏观经济学, whose field is both particularly short of women /and infamous 臭名远扬的；声名狼藉的 for bare-knuckled 裸关节的,不用拳击手套的,不手软地 seminars 研讨课, `主` 40% of those 后定 responding 回答，回应 to the AEA’s survey /`谓` felt “disrespected” 不尊敬；无礼；轻蔑; among female macroeconomists, 70% did.

[.my2]
宏观经济学家的研究领域尤其缺乏女性，而且以不戴拳击手套的(不留情面的)研讨会而臭名昭著。在接受美国经济学会调查的人中，40%的人感到“不受尊重”；在女性宏观经济学家中，70%的人感到“不受尊重”。

[.my1]
.标题
====
.weed
(v.) 除（地面的）杂草.

.weed out :
to remove or get rid of people or things from a group because they are not wanted or are less good than the rest 清除，剔除，淘汰（不需要的或较差的人或物）

.sloppy
that shows a lack of care, thought or effort 马虎的；凌乱的；草率的 +
⇒ slop,泥浆，-y,形容词后缀。引申比喻义马虎的，草率的。

.knuckle
/ˈnʌkl/ 指关节,膝关节

.supportive sub-fields and departments
ChatGPT的解释是: 指的是支持性的领域和部门，它们提供了一个更为温和和鼓励性的环境，使得演讲者不会被批评或被质疑的方式打击士气。换句话说，这些领域和部门的主要目的不是批评或挑剔演讲者，而是为他们提供支持和鼓励，帮助他们更好地发挥自己的才能和创造力。
====



'''


== <prue> Academic sexism


In any case, the survey yielded more than enough reports of sexual harassment. Nearly 2,000 respondents said they had been embarrassed or offended by inappropriate gestures, remarks or materials from other economists. Hundreds reported experiences of attempted or actual sexual assault by a colleague or student in the past ten years. And 267 reported that they would have been rewarded [had they co-operated with unwanted sexual attention], or threatened with retaliation [had they not].

A meta-analysis of studies of the prevalence of sexual harassment in 2003 ranked academia second only to the armed forces.

Our interviewees found it much easier to name prominent bullies than notorious harassers. A senior professor said that she had seen a special nastiness (reserved for people regarded as vulnerable, including women). Others claimed only to have seen “assholes” who were indiscriminate in their aggression.


Unfair treatment can be unwitting. Senior professors may be unconsciously drawn to favour students who look like their younger selves. They may like chatting about work over a drink, which young women may find uncomfortable. One PhD student said she felt that female students found {it harder to connect with male professors}. She suspected {that was partly due to unspoken worries about harassment}.


Then there is the style of seminars, for which economics is notorious. Interruptions and intense questioning are supposed to weed out errors and uncover sloppy thinking. And several interviewees told of supportive sub-fields and departments, where the primary purpose was not to tear down the speaker. But one said she felt like quitting after seeing how a female presenter was treated. Another economist reported being asked during a presentation whether she knew any economics, and being interrupted incessantly.

Among macroeconomists, whose field is both particularly short of women and infamous for bare-knuckled seminars, 40% of those (responding to the AEA’s survey) felt “disrespected”; among female macroeconomists, 70% did.


'''

