

= Dunbar number : 150. 邓巴数

:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css




'''


== The number of the best

Whereas （用以比较或对比两个事实）然而，但是，尽管 150 is sometimes referred to as 被称为 the “Dunbar number”, the academic himself in fact *refers to* 描述；涉及；与…相关 a range of figures.

He observes that /humans tend (v.) to have five intimate  亲密的；密切的 friends, 15 or so 大约，左右 good friends, around 50 social friends and 150-odd 大约；略多 acquaintances.

[.my2]
150有时被称为“邓巴数”，而学者自己实际上指的是一系列数字。他发现，人类往往有5个亲密的朋友，15个左右的好朋友，大约50个社会朋友和, 150多个熟人。

[.my1]
.标题
====
.odd :
( no comparative or superlative; usually placed immediately after a number 无比较级或最高级；通常紧接在数字后面 ) approximately or a little more than the number mentioned 大约；略多 +
- How old is she — seventy odd? 她多大年纪？七十出头？ +
- He’s worked there for twenty-odd years. 他在那里工作了二十多年。



====


'''

== <pure> The number of the best



Whereas 150 is sometimes referred to as the “Dunbar number”, the academic himself in fact refers to a range of figures. He observes that humans tend to have five intimate friends, 15 [or so] good friends, around 50 social friends and 150-odd acquaintances.


'''
