
= 合作中的欺骗行为, 具有"传染性"和"步步升级性"
:toc: left
:toclevels: 3
:stylesheet: ../myAdocCss.css



'''

== The Dark Side of Collaboration 合作的阴暗面


`主` People 后定 working together `谓` often scheme (v.)密谋；秘密策划；图谋 to *put* profits 利润 *ahead of* telling the truth. New research points to ways to stop this behavior.


Often /discussion of collaboration emphasizes (v.) its advantages: it helps people solve complex problems they could not address (v.)设法解决；处理；对付 alone, for instance. But there are also situations in which `主` group work 团体工作 `谓` can be _fertile (a.)能生育的；可繁殖的；能结果的  ground_ for dishonest behavior.


[.my2]
====

在一起工作的人往往会把"利益"放在比"说真话"更高的位置上。新的研究指出了阻止这种行为的方法.

对协作的讨论, 常常强调它的优势：例如，它可以帮助人们解决他们无法单独解决的复杂问题。但在某些情况下，团队合作可能成为滋生不诚实行为的温床。
====


My colleagues and I pooled (v.)集中资源（或材料等） data from many _past studies_ to understand (v.) the forces 强大效力；巨大影响 that shape (v.) and underlie (v.)构成…的基础；作为…的原因 group dishonesty.  +
We analyzed 34 _research projects_ that involved more than 10,000 participants altogether. In these experiments, scientists asked people to play (v.) economic games /or carry out 执行，实施 decision-making 决策的 tasks while part of a team. The specific instructions varied (v.) *from* one study *to* the next, but across 在…各处；遍及 experiments, participants could gain (v.) money *through* honesty and teamwork.

[.my2]
我和我的同事汇集了过去许多研究的数据，以了解形成和构成群体不诚实行为的力量。我们分析了 34 个研究项目，共涉及 10,000 多名参与者。在这些实验中，科学家要求人们作为团队的一员, 玩经济游戏或执行决策任务。每个研究的具体指示各不相同，但在所有实验中，参与者都可以通过诚实和团队合作来获得金钱。

[.my1]
.标题
====
.while part of a team
"while" 意思是“当……的时候”或“在……期间”。"while part of a team" 表示参与者在作为团队一员的情况下, 进行经济游戏或决策任务。 +
所以，“while part of a team” 可以理解为“作为团队的一员时”或“在团队中”。
====


They also had opportunities, however, to earn additional money as a group by lying. For example, in some tasks, teams received a payout 付出的巨款 based on the number of puzzles they solved together; participants could lie (v.) and inflate (v.)使充气；膨胀;鼓吹；吹捧 the quantity they had deciphered  (v.)破译，辨认（难认、难解的东西）.  +
Across all studies and tasks, we found that groups tended to lie. On average, they earned 35.6 percent of _the extra profits_ 后定 available 可获得的；可购得的；可找到的 to them *above* what they could make from simply telling the truth.


[.my2]
====
然而，作为一个群体，他们也有机会通过撒谎来赚取额外的钱。例如，在某些任务中，团队根据他们一起解决的谜题数量获得奖励;参与者可以撒谎, 并夸大他们破译的数量。在所有的研究和任务中，我们发现群体倾向于撒谎。平均而言，他们获得的额外利润, 比他们简单地说实话所能获得的利润, 高出35.6%。
====


We also showed that _collaborative (a.)合作的，协作的 dishonesty_ is contagious (a.)（疾病）接触传染的 and escalates (v.)（使）逐步扩大，不断恶化，加剧.  +

`主` Several studies we analyzed `谓` involved asking pairs of people to roll (v.) dice 掷骰子 over multiple rounds.  +
One person *rolled a die* in private and then reported the outcome. Their partner learned about 了解,获取关于某个主题或事物的信息 that report /and then *rolled an independent die* before reporting their own outcome. If both teammates claimed to have rolled the same number, they received a payout (尤指大笔) 钱款: for example, a one-one double 双的；成双的；成对的 might mean each person got $1, a two-two double could mean $2 each, and so on.  +

Pairs 一对，一双 could choose to be honest and receive payment （将付或应付的）款额，款项 only when they truly rolled (v.) doubles. But over 遍及; 在…期间 the course 进展；进程 of many rounds, some pairs would be tempted to falsely declare (v.) a higher or matching roll *for* greater or more frequent payouts.




[.my2]
====
我们还表明，##合谋的"不诚实行为", 是具有传染性, 并且会逐渐升级。##我们分析了几项研究，其中涉及要求一对人在多轮中掷骰子。一人在私下中掷骰子，然后报告结果。他们的伴侣会了解这个报告，然后掷一枚独立的骰子，并报告自己的结果。如果两个队友声称他们掷得相同的数字，他们将得到奖金：例如，两个一意味着每个人得到1美元，两个二意味着每个人得到2美元，以此类推。#一对人可以选择诚实#，只有在他们真正掷得相同数字时才能获得报酬。#但是在许多轮次中，有些人可能会被诱使报告更高的数字或相同的数字，以获取更高或更频繁的奖金。#
====

For these studies, we first identified whether any participants were obviously deceitful 不诚实的；骗人的. When the data suggested that certain people reported only sixes —_the highest roll_ possible —or _only doubles_ in all rounds of the task, we *labeled* these improbably lucky rollers *as* brazen (a.)厚颜无耻的 liars 说谎者；撒谎者. (Because `主` the chance of getting _sixes_ or _doubles_ in 20 rounds, _the most common number of rounds_ in the task, `系` is very small —less than 0.001 percent — we felt confident (a.) about this classification 分类；归类；分级.)


[.my2]
====
对于这些研究，我们首先确定是否有参与者明显撒谎。当数据显示某些人在任务的所有轮次中, 只报告六点（最高点数）或只报告双数时，我们将这些不太可能的幸运掷骰者, 标记为厚颜无耻的撒谎者。（因为在任务中最常见的20轮次中, 获得六点或双数的机会非常小，小于0.001％，所以我们对这个分类感到有信心。）
====

[.my1]
.案例
====
.brazen
-> 同brass, 黄铜。原指黄铜色，看不出脸红的人。
====

`主` The brazen liar’s behavior `谓`  influenced  (v.)影响；对…起作用 their partner. People were more likely to lie when their partner did. This dishonesty also grew over time. In later rounds, compared with earlier ones, the first person to roll a die `系` was more likely to report a higher roll, and their partner was more likely to report a double.


[.my2]
====
##厚颜无耻的撒谎者的行为, 影响了他们的伴侣。当他们的伴侣撒谎时，人们更有可能撒谎。这种不诚实也随着时间的推移而增加。##与早期轮次相比，在后期轮次中，首先掷骰子的人更有可能报告更高的点数，而他们的伴侣更有可能报告双数。
====


The good news is that there was a limit to the deceit 欺骗，欺诈（行为）；诡计. In puzzle tasks, for instance, most teams did not pretend to solve every puzzle presented. And when studies added ethical （有关）道德的；伦理的 costs for dishonesty, such as by informing (v.) people that lies would harm (v.) other participants /or have negative 坏的；有害的 consequences for a charity 慈善；赈济；施舍 donation, groups lied (v.) less.  +
On top of that 除此之外, we discovered that `主` the gender and age of the group members `谓` mattered (v.) 事关紧要；要紧；有重大影响. *The more* women a group had /and *the older* its members were, *the less* the group lied. We are still investigating (v.)研究 reasons for this pattern.


[.my2]
====
好消息是, 欺骗是有限度的。例如，在拼图任务中，大多数团队并没有假装解决所有呈现的拼图。##当研究增加不诚实的道德成本时，##例如通过告知人们 说谎会伤害其他参与者, 或对慈善捐赠产生负面影响，##团体说谎的次数就会减少。## +
最重要的是，我们发现, ##小组成员的性别和年龄很重要。一个团体中的女性越多，成员年龄越大，该团体撒谎的次数就越少。##我们仍在调查这种模式的原因。
====

Our findings point to specific ways people could encourage (v.) honesty when groups work together.  +
For instance, `主` our discovery (n.) 后定 that _collaborative dishonesty is contagious_ （疾病）接触传染的 `谓` suggests that people should try to detect 发现；查明；侦察出 and act (v.) [on early signs 迹象；征兆；预兆].  +
Managers could *implement* (v.) 使生效；贯彻；执行；实施 _zero-tolerance 零容忍 policies_ *toward* even _small acts of deceit_ to deter (v.) 制止；阻止；威慑；使不敢 its spread.

To increase (v.) early disclosure 揭露；透露；公开 of dishonesty, they could *put* policies 政策，方针 *in place* that forgive (v.) whistleblowers
告发者，检举者，吹哨者 for their part in wrongdoing (n.)不法行为；坏事；作恶；欺骗行径 when they *come forward* 自愿站出来，主动提供帮助或信息 about dishonest deeds  行为；行动.

And because groups are more honest when they believe others are harmed by their lies, `主` *highlighting* (v.) the negative consequences of dishonesty *more prominently* 显著地 `谓` may help curb (v.)控制，抑制，限定，约束（不好的事物） it.

[.my2]
我们的研究结果, 指出了人们在团队合作时, 可以鼓励诚实的具体方式。例如，我们发现, ##协作中的不诚实, 具有传染性，这表明人们应该尝试发现早期迹象, 并采取行动。##管理人员##可以对哪怕是很小的欺骗行为实施"零容忍"政策，以阻止其蔓延。## +
为了增加对不诚实行为的早期披露，他们##可以制定政策，在举报人举报不诚实行为时，原谅他们在不当行为中所扮演的角色。##而且，因为当一个群体相信"别人会被自己的谎言伤害"时，他们会更诚实，所以更突出地强调不诚实的负面后果, 可能有助于遏制这种情况。

[.my1]
====
.deter
de-, 向下，强调。-ter, 恐惧，词源同terrible,terrorist. 即使恐惧，威慑，震慑。

.curb
它和curve（曲线）都来自拉丁语curvare（使弯曲）。“勒马绳”和“弯曲”有何关系呢？在马前进时，马脖子向前挺直，你要左转，得用绳子将马脖子拽向左边，即向左弯曲；让马停下得往后拽绳，使脖子向后弯曲。


====

'''

== (pure) The Dark Side of Collaboration



People working together often scheme to put profits ahead of telling the truth. New research points to ways to stop this behavior.


Often discussion of collaboration emphasizes its advantages: it helps people solve complex problems they could not address alone, for instance. But there are also situations in which group work can be fertile ground for dishonest behavior.


My colleagues and I pooled data from many past studies to understand the forces that shape and underlie group dishonesty. We analyzed 34 research projects that involved more than 10,000 participants altogether. In these experiments, scientists asked people to play economic games or carry out decision-making tasks while part of a team. The specific instructions varied from one study to the next, but across experiments, participants could gain money through honesty and teamwork.

They also had opportunities, however, to earn additional money as a group by lying. For example, in some tasks, teams received a payout based on the number of puzzles they solved together; participants could lie and inflate the quantity they had deciphered. Across all studies and tasks, we found that groups tended to lie. On average, they earned 35.6 percent of the extra profits available to them above what they could make from simply telling the truth.

We also showed that collaborative dishonesty is contagious and escalates. Several studies we analyzed involved asking pairs of people to roll dice over multiple rounds. One person rolled a die in private and then reported the outcome. Their partner learned about that report and then rolled an independent die before reporting their own outcome. If both teammates claimed to have rolled the same number, they received a payout: for example, a one-one double might mean each person got $1, a two-two double could mean $2 each, and so on. Pairs could choose to be honest and receive payment only when they truly rolled doubles. But over the course of many rounds, some pairs would be tempted to falsely declare a higher or matching roll for greater or more frequent payouts.


For these studies, we first identified whether any participants were obviously deceitful. When the data suggested that certain people reported only sixes—the highest roll possible—or only doubles in all rounds of the task, we labeled these improbably lucky rollers as brazen liars. (Because the chance of getting sixes or doubles in 20 rounds, the most common number of rounds in the task, is very small—less than 0.001 percent—we felt confident about this classification.)

The brazen liar’s behavior influenced their partner. People were more likely to lie when their partner did. This dishonesty also grew over time. In later rounds, compared with earlier ones, the first person to roll a die was more likely to report a higher roll, and their partner was more likely to report a double.


The good news is that there was a limit to the deceit. In puzzle tasks, for instance, most teams did not pretend to solve every puzzle presented. And when studies added ethical costs for dishonesty, such as by informing people that lies would harm other participants or have negative consequences for a charity donation, groups lied less. On top of that, we discovered that the gender and age of the group members mattered. The more women a group had and the older its members were, the less the group lied. We are still investigating reasons for this pattern.


Our findings point to specific ways people could encourage honesty when groups work together. For instance, our discovery that collaborative dishonesty is contagious suggests that people should try to detect and act on early signs. Managers could implement zero-tolerance policies toward even small acts of deceit to deter its spread. To increase early disclosure of dishonesty, they could put policies in place that forgive whistleblowers for their part in wrongdoing when they come forward about dishonest deeds. And because groups are more honest when they believe others are harmed by their lies, highlighting the negative consequences of dishonesty more prominently may help curb it.
