= 1008
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1008 – Money Laundering.
This is English as a Second Language Podcast episode 1008. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our special courses in Business and Daily English that I think you’ll enjoy. Take a look at our ESL Podcast Blog. While you’re there, you could also like us on Facebook at facebook.com/eslpod, and follow us on Twitter at @eslpod.
This episode is a dialogue between Susanna and Clark about someone who’s trying to do something illegal with money. Let’s get started.
[start of dialogue]
Susanna: What’s going on in the office next door? I heard that the police shut down their business.
Clark: You heard right. The cops had long suspected that the business operating out of that office wasn’t legit.
Susanna: Not legit?
Clark: Yeah, it was a front for money laundering. The so-called services it offered were a sham. It was a way for people to send them dirty money and for the business to legitimize those funds.
Susanna: But who was involved?
Clark: I’m not sure, but I imagine they’re people who want to evade taxes or to circumvent certain laws or regulations. I wouldn’t be surprised if their clients were people with underworld connections.
Susanna: You mean organized crime?
Clark: Yeah, they’re probably drug lords, smugglers, and racketeers.
Susanna: Wow, and the people who helped them were working next door to us all that time.
Clark: And we didn’t know a thing about it. How awful.
Susanna: How exciting!
[end of dialogue]
Our dialogue begins with Susanna saying to Clark, “What’s going on in the office next door?” The “office next door” would be the office that is right next to your office. We could also talk about the “house next door” – literally, the next door that you would open if you went over a little bit from where you are now. We talk about our “next door neighbor” as the person or the house that is immediately next to ours. Here, we’re talking about an “office next door.”
Susanna says, “I heard that the police shut down their business.” Clark says, “You’re right. The cops had long suspected that the business operating out of that office wasn’t legit.” Clark says the police “suspected.” “To suspect” (suspect) is to think that something is true, especially when we’re talking about someone doing something wrong or committing a crime, although it could be a situation that is not criminal.
You could say, “I suspect that my brother is not very happy living in Minnesota.” I’m not sure. I don’t have proof of that. I don’t have a lot of “evidence,” we would say, of that, but I think it’s true. When the police suspect someone of something, usually they think that person has done something wrong, has done something against the law.
The “cops,” which is an informal term for the police, had “long suspected,” meaning they had suspected for a long time, “that the business operating out of that office was not legit.” “Legit” (legit) is short for “legitimate” (legitimate). Something that is legitimate is something that is real, something that is valid – in this case, something that is legal. The business was doing things that weren’t legal.
Susanna says, “Not legit?” Clark says, “Yeah, it was a front for money laundering.” A “front” (front) is a business or organization that doesn’t do what it says it does. It is established or created or started in order to hide some sort of illegal activity. So, you might have someone who opens up a store, but the store isn’t really for selling food or selling clothing – whatever the store sells. The store is really there in order to do something else, something illegal. One thing that is illegal is “money laundering.”
“To launder” (launder) means to clean your clothes. We talk about taking your clothes to a “laundromat,” which is a place that has washing machines and drying machines – or, simply, “dryers.” “Money laundering” is when you take money that you got from doing something illegal and use it in a business that is legal so that the police won’t know where the money really came from. It looks like it came from this business, even though it was gotten from some sort of illegal activity.
For example, you may be selling drugs illegally and making a lot of money selling these drugs. You don’t want the police to find out about where you got all this money, and you want to put the money in a bank or do something with the money. So, you start a business that sells clothing. You invest the money that you got selling drugs into the clothing store, and then the clothing store makes money, and now suddenly the money has been laundered.
You can say, “Well, the money came from my clothing store,” and it looks “clean” – it looks like it came from a legal operation, when in fact it came from you selling drugs. That would be an example of money laundering. Clark says, “The so-called services it offered were a sham.” The expressions “so-called” (called) means presumably. It’s a phrase we use to refer to something that isn’t really true, or where you have a name for something that isn’t really accurate. So, in this case, the business was selling services, but they weren’t really services, and so Clark uses the term “so-called.”
For example, you could talk about giving money to a government official in order to get the government official to do something for you. This is illegal. You could call it a gift, however. Someone would then refer to that gift as your “so-called gift,” because it isn’t really a gift. It is, in fact, what we would call a “bribe” (bribe) – when you give money to a government official to do something for you. In most countries, bribes are illegal, which does not mean they’re not common.
The business here offered certain services that weren’t really services at all. These services are what Clark calls a “sham” (sham). Something that is a sham is something that is fake, something that is false, something that is not what it appears to be. Clark says, “It was a way for people to send them dirty money and for the business to legitimize those funds.” “Dirty money” would be money that you obtained or got from doing something illegal. “To legitimize (legitimize) is to make legitimate – to make it seem as though in this case it were legal.
Susanna asks, “But who was involved?” Clark says, “I’m not sure, but I imagine” – I’m guessing – “they’re people who want to evade taxes or to circumvent certain laws or regulations.” “To evade” (evade) is to avoid something. “To evade taxes” is to avoid paying money to the government that you have to pay them.
If you work in the United States, for example, you have to pay taxes to the U.S. government, a certain percentage of your money to the government, so the government has money to waste on other things, No, I’m just joking. The government needs money. It just doesn’t always spend the money very wisely, but back to our story . . .
Clark says that this front was used by people who wanted to evade taxes or to “circumvent certain laws or regulations.” “To circumvent” (circumvent) means to go around something, but here it really means the same as “to evade.” It means to avoid doing something. Clark says, “I wouldn’t be surprised if their clients were people with underworld connections.” The term “underworld” (underworld) refers to the world of criminals, the world of the illegal activities by criminals.
Susanna says, “You mean organized crime?” “Organized crime” refers to groups of criminals who organize, who have an organization that is used to commit crimes. You may have organized crime involved in selling drugs. There isn’t just one person who goes and finds drugs and sells them to another person. It’s usually part of an organization, and these organizations, as you probably know, can be very dangerous and very powerful.
Clark says, “Yeah, they’re probably drug lords, smugglers and racketeers.” The term “drug lord” refers to a very powerful person who is involved in this organization, in organized crime, selling drugs. A “smuggler” (smuggler) is a person who brings things into a country illegally, against the law. If you are smuggling in drugs to the United States, you are bringing these illegal drugs in here without permission.
A “racketeer” (racketeer) is a person who is involved in illegal business activities, often involving some sort of violent crime. The term “racketeer” is used in a very broad way to refer to people who are doing things illegal in terms of running a business. Susanna says, “Wow, and the people who helped them were working next door to us all that time.” She is amazed that the people that were working in the office next door were part of this illegal activity.
Clark says, “And we didn’t know a thing about it. How awful.” When we say something is “awful” (awful) nowadays, we mean it’s terrible. It’s horrible. It’s very unpleasant. Clark thinks this entire situation is awful. Susanna says, however, “How exciting!” She thinks that it’s exciting rather than awful.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Susanna: What’s going on in the office next door? I heard that the police shut down their business.
Clark: You heard right. The cops had long suspected that the business operating out of that office wasn’t legit.
Susanna: Not legit?
Clark: Yeah, it was a front for money laundering. The so-called services it offered were a sham. It was a way for people to send them dirty money and for the business to legitimize those funds.
Susanna: But who was involved?
Clark: I’m not sure, but I imagine they’re people who want to evade taxes or to circumvent certain laws or regulations. I wouldn’t be surprised if their clients were people with underworld connections.
Susanna: You mean organized crime?
Clark: Yeah, they’re probably drug lords, smugglers, and racketeers.
Susanna: Wow, and the people who helped them were working next door to us all that time.
Clark: And we didn’t know a thing about it. How awful.
Susanna: How exciting!
[end of dialogue]
I don’t suspect our scriptwriter is the best scriptwriter on the web – I know. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
to shut down – to put a company out of business so that it can no longer operate or make money
* The local health department shut down the restaurant due to food safety violations.
to suspect – to think that something is true, especially that someone has committed a crime or done something bad, but be unable to prove it due to a lack of evidence
* When Lucas was six, he began to suspect that Santa Claus isn’t a real person.
legit – legitimate; real, valid, and justified
* If the offer sounds too good to be true, it probably isn’t legit.
front – something used to mask, hide, or obscure the true identify or purpose of someone or something
* Heather has been acting nicer than usual lately, but it’s just a front to get a job, because she heard we might be hiring.
money laundering – the process of taking dirty money (funds that have been obtained from illegal activities) and making them seem clean (obtained through legal activities), often by passing the money through a business or by breaking a large amount of money into many small deposits
* The bank thought the new client might be involved in money laundering, so it called the FBI.
so-called – presumably; a phrase used to refer to something by its chosen name when one doesn’t believe that name is appropriate or accurate; a phrase used to show one’s disagreement with how something is referred to
* Those so-called gifts are actually bribes so that the government inspectors will ignore the many problems here.
sham – something that is false or fake; something that is not what it appears to be
* His declarations of love were a sham. He was actually just interested in her money.
dirty money – funds obtained from dishonest, secret, and illegal activities
* How much dirty money is generated through illegal drug sales each year?
to legitimize – to make something legal, valid, official, and accepted
* They’ve been living together for years. Their parents want to know when they’re going to legitimize their relationship by getting married.
to evade – to avoid having or doing something, especially to escape having to do something
* Students are always looking for ways to evade the rules on a university campus.
taxes – money paid to the government, often as a percentage of one’s earnings or assets (valuable things one owns)
* Don’t forget to file both your federal and state taxes by April 15!
to circumvent – to find a way around something, especially a way to avoid having to do something or to avoid being covered by some rule or regulation
* Is there any way to circumvent the company’s rule that coworkers shouldn’t date?
underworld – the hidden and disguised economy and society of criminals
* As soon as Harold began selling drugs, he became part of the underworld.
organized crime – groups of criminals who work together in a disciplined, ordered way, like the mafia
* The city is struggling to find ways to fight against organized crime.
drug lord – a very powerful person who sells illegal drugs and/or controls many people who sell illegal drugs
* In the past few years, we’ve seen property values decline as drug lords have moved into the neighborhood, making the streets unsafe.
smuggler – a person who carries illegal goods or people across borders in a highly secretive way
* The airport police use dogs to smell luggage as a way to help them catch drug smugglers.
racketeer – a person involved in illegal and dishonest business transactions, often when violent crime is involved
* The police arrested a racketeer involved in bribery cases.
awful – terrible; horrible; very unpleasant
* I will never go to that restaurant again. The food was awful!
Comprehension Questions
1. What does Clark mean when he says, “The so-called services it offered were a sham”?
a) The company’s services were overpriced.
b) The company didn’t really offer the services it said it did.
c) The company offered very poor customer service.
2. What does Clark mean when he says, “How awful”?
a) He feels bad for the people who were involved in the business.
b) He thinks the business was involved in some terrible activities.
c) He wishes he had known about the business’s activities earlier.
Answers at bottom.
What Else Does It Mean?
to shut down
The phrase “to shut down,” in this podcast, means to put a company out of business so that it can no longer operate or make a profit: “Large companies are shutting down local factories, because they can make their products less expensively in developing countries.” The phrase “to shut down” also means to turn off a computer or a similar device: “Please shut down your computer before you leave the office at night.” The phrase “to shut off” also means to make something stop operating: “If you smell natural gas inside the home, shut off the gas lines right away.” Finally, the phrase “to shut up” means to be quiet and stop talking: “Shut up! You’re giving me a headache.”
lord
In this podcast, the phrase “drug lord” means a very powerful person who sells illegal drugs and/or controls many people who sell illegal drugs: “Drug lords tend to be a bigger problem in large cities than in small, rural towns.” When talking about Christianity, “Lord” with an uppercase L refers to God or Jesus, “Thank you, Lord, for this food that we are about to eat.” Someone’s “lord and master” is a person who has complete control and authority over another person: “You’re my husband, not my lord and master.” Finally, as a verb, “to lord (something) over (someone)” means to use one’s power or benefit in a way that shows one is better than others, or superior in some way: “When Loretta became engaged to a billionaire, she seemed to lord it over her girlfriends.”
Culture Note
U.S. Laws to Prevent Money Laundering
Money laundering “presents” (represents; is) a major problem for the government, so the United States has “enacted,” or created, many laws to “prevent’ (not allow something to happen) money laundering.
Beginning in 1970, the U.S. Congress passed several laws known as the Bank Secrecy Act, which requires “financial institutions” (banks and related companies) to “report” (officially provide information about) certain types of financial transaction that may be involved in money laundering. For example, banks have to report cash transactions “in excess of” (that are larger than) $10,000. Financial institutions are regularly “audited” (examined in detail) to make sure they are following the Bank Secrecy Act.
Reports of “potential” (possible) money laundering activities are entered into a large “database” (an organized way of storing electronic information) operated by the Financial Crimes Enforcement Network. The database is made available to “investigators” (people who are researching something) around the world.
The Bank Secrecy Act also requires that financial institutions “conduct due diligence” (engage in appropriate and sufficient research) to know their customers, understanding their “business model” (how they do business and make money) and the types of transactions they are involved in. Any “suspicious” (making people question whether something in honest or good) transactions must be reported in a Suspicious Activity Report.
U.S. laws also “restrict” (control or limit) the movement of large amounts of “currency” (cash) across borders. People crossing international borders with more than $10,000 in cash must “complete” (fill out and submit) a Report of International Transportation of Currency or Monetary Instruments. In 1986, the Money Laundering Control Act was enacted to “prohibit” (not allow) people to participate in financial transactions dealing with funds obtained through illegal activities.
Comprehension Answers
1 - b
2 - b