= 1042
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,042 – Being Diagnosed with and Treated for Cancer.
This is English as a Second Language Podcast episode 1,042. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this episode. You can also look at our special courses in English by going to our ESL Podcast Store. While you’re on our website, take a look at our ESL Podcast Blog as well.
This episode is a dialogue between Vivian and Guy (notice Guy can be a man’s name as well as a general term for a man) about the all-too-common problem of cancer. Let’s get started.
[start of dialogue]
Vivian: Do you see this lump? I’m sure I have cancer.
Guy: Don’t jump to conclusions. It could be something completely benign.
Vivian: I know it’s not benign. It’s got to be a malignant tumor. The cancer is probably at stage two or three already. The oncologist will probably want to start me on radiation and chemotherapy right away.
Guy: You haven’t seen a single doctor yet and you’re already planning for the worst.
Vivian: Of course I am. I want to be mentally prepared for the bad news. The doctor will do a biopsy, but I already know what the results will be. I’m just hoping the prognosis will be good.
Guy: I think you’re getting way ahead of yourself. It could be something completely harmless.
Vivian: I can’t afford to believe that. I have a family history of cancer. My father was diagnosed when he was 56 years old. It’s true he’s been in remission and hasn’t had a relapse yet, but you never know with cancer.
Guy: That’s right, you never know. You could live to the age of 90.
Vivian: You can fool yourself as much as you like, but I have to face facts – especially as sick as I am.
[end of dialogue]
Vivian begins our dialogue by asking Guy, “Do you see this lump? I’m sure I have cancer.” A “lump” (lump) is a small bump or piece of something that, when we’re talking about the body, is right below your skin. There’s something like a little ball underneath your skin that you can feel – that’s a “lump.” “Cancer” (cancer) is a disease caused when cells in some part of your body begin to grow and make you sick. “Cancer” can, of course, kill you, and unhappily does in some cases.
Guy says to Vivian, “Don’t jump to conclusions.” Vivian thinks that she has cancer just because she found a lump on her body. “To jump to conclusions” means to think that you know the answer to a question before you have all the information necessary to know the answer. “To jump to conclusions” is to try to make a decision or reach a conclusion before having all of the necessary information.
Guy says, “It,” meaning the lump, “could be something completely benign.” A “benign” (benign) lump would be a lump that would not be harmful or deadly. The word “benign” means that it doesn’t cause any harm, that it won’t hurt you. Vivian, however, says, “I know it’s not benign. It’s got to be a malignant tumor.” The word “malignant” (malignant) here means the opposite of benign – something that will hurt you. A “tumor” (tumor) is a kind of cancer growth that can spread throughout your body and ultimately kill you.
Vivian says, “The cancer is probably at stage two or stage three already.” Cancers are often classified by how serious they are, or how advanced they are – how much the cancer has spread throughout your body. The classification system is based on stages. A “stage” (stage) here means one step in a process, one level of progress or advancement of a certain thing – in this case, the growth of the cancer.
The higher the number of the stage, the more advanced and serious the cancer has become. Stage one is not as serious as stage four, which I believe is the highest stage used when talking about the spread of cancer, the growth of the cancerous cells in your body. Vivian thinks she’s already at stage two or three, which would be somewhat unusual, but possible. “The oncologist,” she says, “will probably want to start me on radiation and chemotherapy right away.”
Vivian doesn’t even know if she has cancer and she’s already assuming all sorts of things such as that her cancer is already at stage two or three. She also thinks the oncologist will start her on radiation and chemotherapy. An “oncologist” (oncologist) is a doctor who specializes in diagnosing and treating cancer. “To diagnose” (diagnose) means to identify a problem, usually a medical problem that you have. An oncologist can determine if you have cancer and treat the cancer. “To treat” cancer means to try to stop the cancer to cure you.
Vivian mentions “radiation” and “chemotherapy.” “Radiation” (radiation) is the use of high energy that kills cancer cells and makes the tumors smaller. It’s a medical treatment. “Chemotherapy” (chemotherapy) is the use of injections of chemicals, chemicals that are put into your body to kill the cancer cells.
Guy says, “You haven’t seen a single doctor yet and you’re already planning for the worst.” Guy is saying you haven’t even talked to one doctor and you already are “planning for the worst” – the worst possible case. Vivian says, “Of course I am. I want to be mentally prepared for the bad news.” “To be mentally prepared” means that you think about a problem and are ready for the worst possible case of that problem or worst possible resolution of that problem, perhaps.
Vivian says, “The doctor will do a biopsy, but I already know what the results will be.” A “biopsy” (biopsy) is a medical procedure where a small amount of your body is removed and tested – in this case, it would be tested to see if you had cancer. Vivian says, “I’m just hoping the prognosis will be good.” “Prognosis” (prognosis) is what a doctor thinks will happen to you with a certain disease. “Diagnosis” means the doctor identifies the problem. A “prognosis” is what the doctor thinks will happen to you. Will you continue to live for the next 10 years? Will you die in six months? Those would be examples of prognoses. It’s a prediction about what will happen to you in terms of your health.
Guy says, “I think you’re getting way ahead of yourself.” “To get ahead of yourself” or “way ahead of yourself” means to say or do something sooner than you should, especially if you have jumped to conclusions – if you have made up your mind before you have all the information that you need to make a decision. You can also get way ahead of yourself by making preparations for something that hasn’t even happened yet.
So for example, you meet a beautiful girl at a bar and you get her phone number. You go home and you start planning your wedding with this woman. You start thinking about how many children you want to have with this woman. That would be a very good example of getting way ahead of yourself. Notice the use of the word “way” (way) here. It just means “very much” – really ahead of yourself, perhaps.
Guy says, “It” – meaning again the lump – “could be something completely harmless.” Vivian responds, “I can’t afford to believe that.” If someone says they “can’t afford (afford) to” do something, the person means it’s not possible for them, because if they did, it would cause them more harm. The risk of something bad happening is too great.
Vivian says, “I have a family history of cancer.” A “family history” of some disease or illness means that other members of your family have had that disease. In my case, I have a family history of heart disease. My father had heart disease, as did some of my uncles. Vivian says, “My father was diagnosed when he was 56 years old.” “My father was diagnosed” – meaning the doctors said that he had cancer – when he was only 56.
“It’s true,” Vivian continues, “he’s been in remission and hasn’t had a relapse yet, but you never know with cancer.”
If your cancer is “in remission” (remission), your cancer seems to have stopped or gotten better or possibly even disappeared. If your cancer is in remission, you’re healthy, at least for now. Vivian says her father has been in remission from his cancer and hasn’t had a “relapse” yet. A “relapse” (relapse) is a return to a previous state or condition of bad health. So, you get better and then you get worse again. Getting worse again would be the relapse, going back to the condition you started with.
Guy says, “That’s right, you never know.” Vivian has said that, quote, “You never know with cancer.” When someone says “you never know,” he means it is not possible for you to predict. Guy says, “That’s right, you could live to the age of 90.” Vivian says, “You can fool yourself as much as you like, but I have to face facts.” “To fool (fool) yourself” means to make you believe something that isn’t true – to hide the truth from yourself.
Vivian says she has to face facts. The expression “to face (face) facts (facts)” means to accept reality, to accept the truth, especially when it’s a difficult or painful truth that you have to accept. Vivian is convinced that she has cancer, and that’s why she ends by saying that she has to face facts, “especially as sick as I am.” Vivian believes she’s sick even though she hasn’t gone to a doctor yet.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Vivian: Do you see this lump? I’m sure I have cancer.
Guy: Don’t jump to conclusions. It could be something completely benign.
Vivian: I know it’s not benign. It’s got to be a malignant tumor. The cancer is probably at stage two or three already. The oncologist will probably want to start me on radiation and chemotherapy right away.
Guy: You haven’t seen a single doctor yet and you’re already planning for the worst.
Vivian: Of course I am. I want to be mentally prepared for the bad news. The doctor will do a biopsy, but I already know what the results will be. I’m just hoping the prognosis will be good.
Guy: I think you’re getting way ahead of yourself. It could be something completely harmless.
Vivian: I can’t afford to believe that. I have a family history of cancer. My father was diagnosed when he was 56 years old. It’s true he’s been in remission and hasn’t had a relapse yet, but you never know with cancer.
Guy: That’s right, you never know. You could live to the age of 90.
Vivian: You can fool yourself as much as you like, but I have to face facts – especially as sick as I am.
[end of dialogue]
Our scriptwriter never jumps to conclusions. She’s always looking at the facts and then making the right decision, as she does in every script that she writes. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2014 by the Center for Educational Development.
Glossary
lump – a small bump, piece, or mass of something, especially on part of the body, that doesn’t have a clear shape or form and probably shouldn’t be there
* While petting the dog, we noticed a lump on the side of her neck and decided to take her to the veterinarian.
cancer – a disease caused when cells in part of the body divide and grow uncontrollably
* What’s deadlier: breast cancer or lung cancer?
to jump to conclusions – to assume that one knows the answer to a question before all the information is available; to try to make a decision or reach a conclusion too quickly
* Investigators and judges have to carefully evaluate all the evidence and not jumping to conclusions.
benign – not harmful or deadly, especially when talking about cancer
* The infection looks terrible, but it’s mostly benign.
malignant tumor – a type of cancer growth that can spread throughout the body and does not stay in one small area
* The doctors found a malignant tumor, so they’re going to start Kelsey on chemotherapy right away.
stage – one step in a process
* When building a home, the first stage is selecting the land and the type of home one wants. Choosing paint colors and floor coverings is the last stage of the process.
oncologist – a doctor who specializes in the diagnosis and treatment of cancer
* Is the oncologist recommending surgery, chemotherapy, radiation, or a combination of all three?
radiation – the use of invisible, high-energy radiation to kill cancer cells and make tumors smaller
* How can the doctors be sure that the radiation is targeting the right part of the body?
chemotherapy – the use of injections of chemicals to kill cancer cells
* James has chemotherapy every Tuesday morning, so he knows that he’ll feel sick and be unable to eat anything each Wednesday.
biopsy – the removal of a small amount of tissue from one’s body so that it can be examined and diagnosed, especially if cancer is suspected
* I think you should ask a dermatologist to do a biopsy of some of these strange spots on your shoulders.
prognosis – a doctor’s opinion about how quickly a disease will progress or be cured, or how quickly one will recover from an injury or illness; a forecast of the progression of a medical condition
* Your son is in a lot of pain right now, but the prognosis is good and we think he’ll be able to start walking again within a few months.
to get way ahead of (oneself) – to say or do something sooner than one should, especially because one has reached a conclusion or made a decision before all the information was available
* Krystal’s baby hasn’t even been born yet, but she’s already researching ballet and art classes. She’s really getting way ahead of herself.
family history – information about the older members of one’s family, especially related to their health
* Do you have a family history of heart disease or high blood pressure?
to be diagnosed – to be told that one has a particular disease or medical condition
* The doctor wants to do more tests before diagnosing the problem.
remission – disappearance of the symptoms or signs of a disease, especially cancer, although the disease may still be present in the body
* We were all so relieved when the doctors reported that Anna was in remission, but now we’re scared that the cancer will come back.
relapse – a return to an earlier state of bad health after one has improved temporarily
* After the cancer treatment, Grandpa started eating right and exercising, but he still had a relapse a few years later.
to fool (oneself) – to trick oneself; to make one believe something that isn’t true; to hide from the truth
* Sheila is fooling herself if she thinks she has any chance of winning the race.
to face facts – to accept reality; to confront and accept an unpleasant truth
* I know you’re disappointed, but it’s time to face facts: your son doesn’t want to follow in your footsteps and become an attorney like you.
Comprehension Questions
1. Which of these is most dangerous?
a) A lump.
b) A benign tumor.
c) A malignant tumor.
2. What does Vivian mean when she says, “You never know with cancer”?
a) Her father might get sick again.
b) Cancer may or may not be hereditary.
c) Doctors haven’t done enough research about cancer.
Answers at bottom.
What Else Does It Mean?
lump
The word “lump,” in this podcast, means a small bump, piece, or mass of something, especially part of a body, that doesn’t have a clear shape or form and probably shouldn’t be there: “Doctors recommend that women check their breasts for lumps every month.” The word “lump” also refers to small bumps in other things: “What are all these lumps in the mashed potatoes?” When talking about money a “lump sum” is a large amount of money paid all at once: “Lottery winners have to choose whether they’d like to receive small payments for 20 years, or a smaller total amount as a single lump sum.” Finally, a “lump” of sugar is a small cube or square of sugar: “How many lumps of sugar would you like in your tea?”
to face facts
In this podcast, the phrase “to face facts” means to accept reality or to confront and accept an unpleasant truth: “Let’s face facts: this relationship isn’t working and we should probably end it soon.” The phrase “to face the music” means to accept the punishment for what one has done: “Justin finally decided it was time to face the music, so he confessed to the crime at the police station.” The phrase “to face off” means to have an argument, discussion, or fight with another person: “The best professional wrestlers are going to face off tomorrow night.” Finally, the phrase “can’t face (something)” means unable to do something because it seems too difficult or unpleasant: “I just can’t face the thought of telling Susan such bad news.”
Culture Note
The Great American Smokeout
The “Great American Smokeout” is an “annual” (once a year) event organized by the American Cancer Society, a nonprofit organization that provides education and support regarding cancer. During the “smokeout,” people are “challenged” (asked to do something that is difficult) to “give up smoking” (stop smoking cigarettes) for 24 hours.
The first Great American Smokeout event was held in 1970, when a man in Randolph, Massachusetts asked people to stop smoking for one day and “donate” (give away) to the local high school the money that they normally would have spent on cigarettes. The idea became popular, and now the Smokeout is held on the third Thursday of November. In the days “leading up to” (immediately before) the Great American Smokeout, people are encouraged to use that day to make a plan to “quit smoking” (no longer smoke cigarettes) and/or to make that day the first day when they do not smoke.
The American Cancer Society “touts” (talks about in a favorable way) the benefits of quitting smoking. The organization states that the smoker’s heart rate and blood pressure drop almost immediately, followed by improved “circulation” (the travel of blood throughout the body). They state that, over time, the risk of serious disease and death “diminishes” (becomes smaller) significantly, and that 15 years after “smoking cessation” (the end of smoking cigarettes), the “ex-smoker” (a person who used to smoke) has the same risk of heart disease as a “non-smoker” (a person who has never smoked).
The event clearly helps individuals, but it also helps “motivate” (make someone want to do something) organizations and governments to “enact laws” (create new laws) against smoking in public, in restaurants, and in private workplaces.
Comprehension Answers
1 - c
2 - a