= 1046
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,046 – Types of Luggage.
This is English as a Second Language Podcast episode 1,046. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. You can also take a look at our special courses on our website, as well as our ESL Podcast Blog.
This episode is a dialogue about types, or kinds, of luggage – what you use to transport your clothing when you travel. Let’s get started.
[start of dialogue]
Driver: Ma’am, where would you like these suitcases?
Leona: The three wheeled suitcases should go next to the bed, and the garment bag should be hung up in the closet. Where is my expandable bag?
Driver: Do you mean this duffel bag?
Leona: Yes. You can leave that right there. Hmm, where is my carry-on? All I see is my checked baggage. I thought I gave you my carry-on, too.
Driver: You did, ma’am, and it’s right here.
Leona: Oh, good. When can I expect my trunk to arrive?
Driver: Your trunk? You had a trunk?
Leona: Yes, I had a trunk. Didn’t you see it at the airport?
Driver: Uh no, I must have overlooked it.
Leona: You mean you left behind my trunk?! Who knows what has become of it by now!
Driver: I’m sure I’ll be able to find it and deliver it here to you.
Leona: I knew I should have used a luggage forwarding service.
Driver: You might consider traveling light next time, ma’am.
Leona: What did you say?!
Driver: Nothing! I’m going to fetch your trunk as we speak.
Leona: I should hope so!
[end of dialogue]
Our dialogue is between a woman named Leona and her driver. A “driver” is a person who usually drives you around in a car. You could have a driver if you’re a rich person, for example. You don’t want to drive, so you have a driver – someone who drives you from place to place.
The driver says to Leona, “Ma’am,” which is a polite way of addressing a woman – somewhat formal, however, “where would you like these suitcases?” A “suitcase” is the same as a piece of luggage. It’s a container in which you put your clothing and other things that you are using, and that is used to transport those items to wherever you’re going when you travel.
Leona says, “The three wheeled suitcases should go next to the bed.” A “wheeled (wheeled) suitcase” is a suitcase that has – are you ready? – wheels. Yes. A wheeled suitcase has wheels on it so that you can roll it along the ground. Back when I was growing up, most suitcases did not have wheels on them. Instead, you bought this separate little device called a “luggage carrier” and you put your pieces of luggage on that. Now luggage companies have gotten smart, and they put the wheels right on the suitcases, right on the pieces of luggage.
Leona says that the wheeled suitcases should go next to the bed. She continues, “The garment bag should be hung up in the closet.” A “garment” (garment) is a piece of clothing. So, a “garment bag” is a special piece of luggage that is only used typically for transporting clothing. Usually a garment bag is long. You are able to put a suit in it or a dress in it, and then you fold it over so that it doesn’t get all wrinkled. “Wrinkled” (wrinkled) is when you put your clothes in a certain way that causes them to not be flat, to have a bunch of lines in them.
A garment bag is a large bag then that is used for transporting usually a suit or a dress – some sort of formal clothing, although it doesn’t have to be. The verb “to hang up” is used to describe the action where you are putting something, say a piece of clothing, into a closet. You want a piece of clothing to hang down vertically. Usually you put it on something called a “hanger” (hanger). A hanger is a triangular piece of metal or plastic that has a little round hook on the top.
You put the clothing on the hanger and then you put that hook over a bar or a, what we would call, “rod” (rod) in your closet. This keeps your clothes, once again, from getting wrinkled. A garment bag typically has hangers inside of it and/or it has a hook on the top that you can use to hang it in a closet. That’s what Leona means when she tells the driver that the garment bag should be hung up in the closet. “Hung” is the past participle of “hang.”
Leona then asks, “Where is my expandable bag?” “Expandable” (expandable) comes from the verb “to expand,” which means to make bigger, to make something larger. An “expandable bag,” then, would be a piece of luggage that you could make bigger if you had more things to put in it. It will get bigger for you, if you will, usually because the material is soft and will expand or because there is some additional space in the piece of luggage that you can use if you need more room.
The driver says, “Do you mean this duffel bag?” A “duffel (duffel) bag” is an example of an expandable bag, typically. It is a soft cloth bag, usually in the shape of a round tube. We often associate duffel bags with people transporting their clothing back and forth – say, to a gym to exercise – but it could also be used just to transport a large amount of clothing or other items when you travel. Duffel bags have a zipper on the top that opens and allows you to put things in and take things out of the bag.
Leona says, “Yes. You can leave that right here. Hmm, where is my carry-on?” A “carry-on” is a small suitcase that you can bring with you on the plane to either put in front of you in the seat in front of you – underneath it – or above you in what are called the “overhead bins” (bins). That’s a piece of carry-on luggage. Most airlines in the United States allow you to bring one piece of carry-on luggage when you get on the plane. Your big suitcases have to be typically checked, which is another way of saying they’re put in the plane, but below where the passengers are, in the bottom part of the plane.
Leona in fact refers to the checked baggage in the very next sentence. She says, “All I see is my checked baggage.” Once again, your “checked baggage” is baggage that you give to the airline, and the airline puts it underneath the plane and then gives it back to you (you hope) when you arrive to wherever you’re going. Leona is looking for her checked baggage. She says, “I thought I gave you my carry-on too.” The driver says, “You did, ma’am, and it’s right here.”
Leona says, “Oh, good. When can I expect my trunk to arrive?” A “trunk” (trunk) here refers to a large box that has hard sides on it and a top that is used for transporting a large amount of books, clothing, or other items for travel. Trunks, or “travel trunks,” aren’t very popular anymore. You usually will see them in movies – old movies – about people who are traveling either by ship or by plane. They’re not very easy or convenient to move around.
People have trunks in their homes, however, to store things, especially clothing that they’re not wearing currently. My mother used to keep all of the winter clothing in trunks in our attic, in the very top part of our house, so that it wouldn’t take up space in the rooms. She would then, of course, take it down and bring the clothing to us when the weather got cold – which unfortunately in Minnesota was often.
The driver says, “Your trunk? You had a trunk?” He’s surprised that Leona is asking about it. Leona says, “Yes, I had a trunk. Didn’t you see it at the airport?” The driver says, “Uh, no. I must have overlooked it.” “To overlook” (overlook) something here means to ignore or to miss something. You didn’t see it. You didn’t notice it.
Leona says, “You mean you left behind my trunk?” The phrasal verb “to leave behind” something or “to leave something behind” means not to take something with you when you take all of the other items. It’s something usually that you’ve forgotten. “I left my wallet behind in the hotel room” – I forgot to bring it with me.
Leona is a little angry with her driver. She says, “Who knows what has become of it by now?” The expression “what will become of” something is used when you’re worried about something and you’re not sure what will happen. You may worry about your son or daughter: “What will become of my son if he doesn’t get a job? What will become of my daughter if she doesn’t study in school?” You’re worried about their future.
The driver says, “I’m sure I’ll be able to find it” – that is, the trunk – “and deliver it or bring it here to you.” Leona says, “I knew I should have used a luggage forwarding service.” “To forward” (forward) something means to send it to another person. We use that term in email, for example. When we forward a message to someone, we are taking a message someone sent to us and sending it to somebody else.
A “luggage forwarding service” would be a special service that takes your luggage and transports it to the place where you’re going. So, instead of you bringing your luggage to the airport and having to worry about it, you give it to someone else at your house. They take it to the airport and it’s transported to the place where you’re traveling. Most people don’t do this. It’s probably much more expensive, but you could do it.
The driver says to Leona, “You might consider traveling light next time, ma’am.” The driver is being somewhat rude here. He’s telling Leona that she should travel light next time. “To travel light” means to bring fewer items, to not bring as many suitcases. Leona says, “What did you say?” She’s obviously upset with the driver, angry with the driver.
The driver says, “Nothing. I’m going to fetch your trunk as we speak.” The driver realizes his mistake and he doesn’t repeat what he said to Leona. Instead, he just says, “Nothing,” meaning I didn’t say anything, or what I said wasn’t meant for you, or I didn’t really mean what I said. The driver says, “I’m going to fetch (fetch) your trunk as we speak.” “To fetch” something means to get something and bring it back.
We often use that verb with a dog, when we throw a ball and the dog runs after the ball and brings it back to us. We sometimes will use that verb to describe that action. We’ll even yell at the dog, “Fetch!” meaning “Run after the ball – get it, and bring it back.” More generally, however, it means to go and get something and bring it back, typically to another person. “I will fetch your purse, dear.” I will go and get your purse for you and bring it back to you, my loveliness. That’s what I say to my wife every day.
The driver is going to fetch Leona’s trunk “as we speak,” he says. The expression “as we speak” means right now, right away, immediately. Leona responds, “I should hope so.” That expression “I should hope so” is one you say when you are annoyed, upset, or angry, and you are expressing your desire that something happen, especially something done by someone else.
So, for example, if you’re at a restaurant and the waiter charges you too much for your meal – the waiter brings you your bill, your check, and you look at it and you say, “Oh, this is wrong.” The waiter says, “Oh, I’m sorry, sir. I’ll change that right away.” You might respond, “I should hope so” if you’re very upset or very angry.
However, I don’t recommend using this phrase normally because there is an idea of not just being angry, but being somehow superior to the other person – that you are above the other person and that the other person has done something very wrong, something that has hurt you, even. So, it’s not an expression you would normally use in daily conversation.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Driver: Ma’am, where would you like these suitcases?
Leona: The three wheeled suitcases should go next to the bed, and the garment bag should be hung up in the closet. Where is my expandable bag?
Driver: Do you mean this duffel bag?
Leona: Yes. You can leave that right there. Hmm, where is my carry-on? All I see is my checked baggage. I thought I gave you my carry-on, too.
Driver: You did, ma’am, and it’s right here.
Leona: Oh, good. When can I expect my trunk to arrive?
Driver: Your trunk? You had a trunk?
Leona: Yes, I had a trunk. Didn’t you see it at the airport?
Driver: Uh no, I must have overlooked it.
Leona: You mean you left behind my trunk?! Who knows what has become of it by now!
Driver: I’m sure I’ll be able to find it and deliver it here to you.
Leona: I knew I should have used a luggage forwarding service.
Driver: You might consider traveling light next time, ma’am.
Leona: What did you say?!
Driver: Nothing! I’m going to fetch your trunk as we speak.
Leona: I should hope so!
[end of dialogue]
We don’t want to overlook the wonderful work of our scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
wheeled suitcase – a suitcase with wheels on the bottom and an expandable handle so that it can be pushed and pulled easily instead of being lifted
* It’s much easier to move through the airport with a wheeled suitcase than with a heavy suitcase that has to be carried.
garment bag – a large, zippered bag with an opening at the top for a hanger, so that clothes can be hung and transported in a way that prevents wrinkles
* If you put your dress shirts in a garment bag instead of folding them flat in your suitcase, they’ll have fewer wrinkles when you arrive at your destination.
to hang up – to put something in a vertical (up and down) condition with the top placed over a hook or rod so that it is suspended above the ground
* Could you help me hang up these pictures? I need someone to stand over there and tell me if they’re straight.
expandable – with the ability to change sizes, becoming larger if needed to make room for more items
* The backpack is expandable, so if you loosen those straps on the side you’ll have more room inside the pockets for large books and folders.
duffel bag – a soft cloth bag in the shape of a round tube, with a zipper down the long end and a fabric strap placed over one’s shoulder, often used for sport clothing or equipment
* Bryan often goes to the gym after work, so he keeps a duffel bag with his gym clothes and tennis shoes in the trunk of his car.
carry-on – a bag or small suitcase kept with a passenger flying on an airplane, not place with larger pieces of luggage in the bottom of the airplane
* Sheila always travels with medicines and an extra set of clothing in her carry-on, just in case the airline loses her suitcase.
checked baggage – suitcases that travel in the same plane as their owners, but in a different compartment, not with the individual
* The airline has a 50-pound limit on checked baggage. If you bring a heavier suitcase, you’ll have to pay extra.
trunk – a large, box with hard sides used to pack clothing, books, and other items for travel, especially a long time ago when people traveled by ship
* In the attic, they found an old trunk filled with photographs and letters.
to overlook – to not see, notice, or pay attention to something, even though one was looking in that direction
* Teachers have to be careful not to overlook the quietest students.
to leave behind – to not take something with oneself when one takes all the other items
* During a fire, employees should leave behind all personal items and exit the building as quickly as possible.
what will become of (someone or something) – a phrase used when one is worried about someone or something and does not know what will happen
* Who knows what will become of the children of illegal immigrants whose parents are sent back to their home country.
luggage forwarding – a company or service that specializes in sending suitcases and other objects to one’s destination so they are already there and waiting when the person arrives
* The company uses a luggage forwarding service to send product samples and promotional materials to trade conferences a day or two before the salesperson arrives.
to travel light – to bring very few items when traveling, ideally in only one bag or suitcase
* You’ll enjoy your trip a lot more if you travel light and don’t have to lug around heavy suitcases.
to fetch – to go to get something and bring it back, especially to give to another person
* Please run inside and fetch my purse, which I left on the kitchen table.
as we speak – right now; right away; immediately
* This is an emergency situation and the technical support specialist is looking for a solution as we speak.
I should hope so – when one is annoyed, upset, or angry, a phrase used to emphasize that one certainly hopes and expects something will happen, especially when referring to someone else’s behavior
* A: I’m so sorry for the inconvenience. We’ll do everything possible to correct the problem.
B: I should hope so!
Comprehension Questions
1. Which of these would be best for traveling with suits and dresses?
a) A wheeled suitcase
b) A garment bag
c) A duffel bag
2. What does the driver mean when he says, “I’m going to fetch your trunk”?
a) He’s going to call the airport to find out where the trunk is.
b) He’s going to buy a new trunk for Leona.
c) He’s going to return to the airport to find and bring back her trunk.
Answers at bottom.
What Else Does It Mean?
trunk
The word “trunk,” in this podcast, means a large, hard-sided box used to pack clothing, books, and other items for travel, especially a long time ago when people traveled by ship: “They keep an old trunk at the foot of their bed, filled with heavy winter sweaters.” When talking about a car, the “trunk” is the open area in the back used for transporting large items: “Could you please help me put these bags of groceries into the trunk?” When talking about an elephant, the “trunk” is the long nose: “The children squealed when the elephant sprayed water over them with its trunk.” Finally, when talking about a tree, the “trunk” is the thick main part of the tree: “The squirrel ran up the trunk of the maple tree.”
as we speak
In this podcast, the phrase “as we speak” means right now, right away, or immediately: “The tornado is coming as we speak. Hurry up and get into the basement!” The phrase “to speak (one’s) mind” means to state one’s opinion, especially if one knows that other people will disagree with it: “Uncle Charlie has never been shy about speaking his mind.” The phrase “speak for yourself” is used to let someone know that one does not share his or her opinions: “Laura spoke as if everyone shared her thoughts, but Richard said, ‘Speak for yourself!’” Finally, the phrase “to speak up for (someone)” means to use one’s words to support or defend someone: “Why didn’t anyone speak up for Samantha when she wasn’t there to do it herself?”
Culture Note
Traveler's Cheques
Beore the1990s, “traveler’s cheques” were a “convenient” (easy-to-use) and safe way for people to make payments while traveling far from home. Traveler’s cheques are typically “purchased’ (bought) at a bank in a variety of “denominations” (amounts shown on a piece of paper money, such as $20 or $50). The buyer is supposed to sign them right away. Then, when traveling, the buyer can present the traveler’s cheque to a “vendor” (a person who is selling something) and sign it again in that person’s “presence” (while the other person is standing there). As long as the two signatures “match” (are the same), the new holder of the traveler’s cheque could “cash it” (present it in exchange for a cash payment) at any bank.
Traveler’s cheques present a safe “alternative” (another way of doing something) to carrying cash, which can be stolen and spent by the “thief” (the person who steals something). In contrast, if a traveler’s cheque is stolen, the thief cannot “convert” (change; transform) them into cash, because his or her signature would not be an exact match. And the “victim” (the person whose traveler’s cheques were stolen) can request replacement traveler’s cheques if he or she still has the “serial numbers” (the unique number assigned to each traveler’s cheque).
Traveler’s cheques were very popular until the 1990s, but then their use began to “decline” (reduce; become smaller) as other options like credit cards, debit cards and “ATMs” (automated teller machines; bank machines that provide cash) became more “prevalent” (more common; more easily found).
Today, traveler’s cheques can still be purchased, but it has become more difficult to find stores and other businesses that will accept them as a form of payment. Most “establishments” (businesses) prefer to accept credit or debit card payments.
Comprehension Answers
1 - b
2 - c