= 1047
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,047 – Having Breathing Problems.
This is English as a Second Language Podcast episode 1,047. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode – a 10-page or so guide that we provide for every episode that includes a complete transcript of everything that we say.
This episode is called “Having Breathing Problems,” a dialogue between Russ and Cheryl with a vocabulary related to “breathing” – putting air into your lungs and breathing out again. Let’s get started.
[start of dialogue]
Russ: Why are you wheezing like that?
Cheryl: I’m not wheezing. I’m just a little short of breath. My lungs feel like they’ve closed up.
Russ: Maybe you should get that checked out. You could have asthma.
Cheryl: Do you really think so? My nasal passages have been stopped up, so I just thought I had a bad cold. My sinuses hurt, too.
Russ: I’m not a doctor, but you may have something more serious, maybe bronchitis or pneumonia. You need a chest x-ray or something.
Cheryl: Wow, so this could be something really serious?
Russ: Why do you sound hopeful that you have a serious condition?
Cheryl: I’m not. That would be stupid.
Russ: And yet, you sounded positively giddy that you might be laid up for a couple of weeks. Does this have anything to do with your upcoming business trip to Abrahamville?
Cheryl: If you had to go to Abrahamville, wouldn’t you wish for an out, too – any out?
[end of dialogue]
Our dialogue begins with Russ saying to Cheryl, “Why are you wheezing like that?” “To wheeze” (wheeze) means to make a loud sound while breathing, usually because you’re having problems breathing – perhaps you’re not getting enough oxygen into your lungs. “To wheeze” is to [wheezing]. That could be an example of wheezing.
Cheryl says, “I’m not wheezing. I’m just a little short of breath.” “To be short of breath” (breath) means that you have to breathe quickly in order to get enough oxygen into your lungs. Usually we are short of breath when we are doing a lot of physical activity or we’re running up a set of stairs. You might become short of breath. You might have a little bit of difficulty breathing, especially if you’re not used to doing a lot of physical activity.
Cheryl says, “My lungs feel like they’ve closed up.” Your “lungs” (lungs) are the organs in your body, the parts of your body, that bring in air and “expel” air, we would say, when you “inhale” (inhale) – when you put air into your lungs – and then you “exhale” (exhale) – when the air goes out of your lungs, when it is pushed out of your lungs. Cheryl says her lungs “feel like they’ve closed up.” “To close up” normally means to no longer be open, but here it probably means something more like not having enough room to move or to expand.
Russ says, “Maybe you should get that checked out.” “To get something checked (checked) out” means to have something looked at, investigated. The phrasal verb “to check out” means to look at, to investigate. We use the phrase “to get something checked out” typically when we’re talking about some sort of medical issue – say, you have a hand that is been bothering you, it hurts. Someone may say to you, “You should get that checked out,” meaning you should go to a doctor or a nurse and have them look at it and make sure there’s nothing wrong with you.
Russ says, “You could have asthma.” “Asthma” (asthma) is a medical condition that makes it very difficult for people to breathe properly and easily. My older brothers had asthma and my father had asthma, quite a serious case of asthma, actually. Cheryl says, “Do you really think so? My nasal passages have been stopped up, so I just thought I had a bad cold.” The word “nasal” (nasal) refers to your nose. A “passage” is an area where something moves in and out of, or goes through.
So, your “nasal passages” are the parts of your nose where the air goes in and out, where you breathe in – you inhale – and you breathe out – you exhale. Of course, you can also breathe in and breathe out with your mouth, but the nasal passages refer specifically to your nose.
Cheryl says her nasal passages have been “stopped up.” “To be stopped up” means that there is something blocking the passage so that things cannot move through easily or at all. You could also talk about, say, the pipes that are connected to your sink as being “stopped up.” If you put a bunch of food down into the pipes that drain the water from your sink, the pipe might become stopped up.
When we’re talking about pipes and sinks and toilets, we actually use another verb more typically, which is “clogged” (clogged). “To be clogged up” means the same as to be stopped up. What’s supposed to move through this area, this passage, is not able to because something is stopping it. That’s the problem that Cheryl has with her nasal passages. She’s not able to breathe easily or at all through her nose because her nasal passages have been stopped up.
She continues, “My sinuses hurt, too.” Your “sinuses” (sinuses) are open areas inside the bones of your face that are connected to your nasal passages. So, it’s part of your “breathing system,” you might call it. People often have problems with their sinuses. Sometimes your sinuses can get an infection so that they hurt, sometimes quite a lot. I’ve had a sinus infection myself. It’s very painful. But enough about me, back to Cheryl and Russ.
Russ says, “I’m not a doctor but you may have something more serious, maybe bronchitis or pneumonia. You need a chest x-ray or something.” Russ says he’s not a doctor, but he thinks that Cheryl might have a more serious illness or problem with her body. He says that she may have “bronchitis” (bronchitis). Bronchitis is a condition where you have typically an infection of the tubes, the passages, that lead into the lungs. Usually it causes coughing and difficulty breathing and can be quite serious. You need to go to a doctor to get medicine if you have bronchitis, usually.
Russ says that Cheryl might also have pneumonia. “Pneumonia” (pneumonia) – notice the “p” is silent; we don’t pronounce it – is also an infection related to your lungs. When you have pneumonia, your lungs often fill with a fluid, a liquid, which makes it difficult to breathe. A pneumonia can also be quite serious. In fact, you can die from pneumonia.
Russ tells Cheryl that she needs a “chest x-ray.” Your “chest” (chest) is the upper part of your body where your lungs are located, as well as your heart and a few other things. An “x-ray” is a special photograph that they take of the inside of your body. So, a “chest x-ray” would be one of these special photographs. Usually you get a chest x-ray when the doctor thinks there might be something more seriously wrong with your lungs or your breathing.
Cheryl is surprised. She says, “Wow! So this could be something really serious?” Russ says, “Why do you sound hopeful that you have a serious condition?” Russ is a little confused by Cheryl’s reaction. It almost seems as if Cheryl wanted to be sick. Cheryl says, “I’m not. That would be stupid.”
Russ says, “And yet, you sounded positively giddy that you might be laid up for a couple of weeks.” “Giddy” (giddy) means very happy, very excited, almost out of control with excitement. “Positively” here means completely, thoroughly, entirely. “Positively giddy,” then, means you are very excited. You are completely excited, very happy about something. Russ thinks that Cheryl is happy about being “laid up.” “To be laid (laid) up” means to be forced to stay in bed, usually because you are sick or have some illness.
Russ says, “Does this have anything to do with your upcoming business trip to Abrahamville?” “Upcoming” means happening soon in the future. We might also use the word “approaching.” It’s something that’s going to be happening soon – maybe in a day, maybe in a week, maybe in a month.
Cheryl says, “If you had to go to Abrahamville, wouldn’t you wish for an out, too – any out?” “Abrahamville” is, of course, not a real place, but it’s obviously a place where Cheryl does not want to go. That’s why she asks Russ, “If you had to go to Abrahamville, wouldn’t you wish for an out, too?” An “out” (out) here means a reason or an excuse for not doing something. Cheryl is looking for a reason not to go to Abrahamville. She’s looking for an “out.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Russ: Why are you wheezing like that?
Cheryl: I’m not wheezing. I’m just a little short of breath. My lungs feel like they’ve closed up.
Russ: Maybe you should get that checked out. You could have asthma.
Cheryl: Do you really think so? My nasal passages have been stopped up, so I just thought I had a bad cold. My sinuses hurt, too.
Russ: I’m not a doctor, but you may have something more serious, maybe bronchitis or pneumonia. You need a chest x-ray or something.
Cheryl: Wow, so this could be something really serious?
Russ: Why do you sound hopeful that you have a serious condition?
Cheryl: I’m not. That would be stupid.
Russ: And yet, you sounded positively giddy that you might be laid up for a couple of weeks. Does this have anything to do with your upcoming business trip to Abrahamville?
Cheryl: If you had to go to Abrahamville, wouldn’t you wish for an out, too – any out?
[end of dialogue]
We hope you feel positively giddy when you hear the wonderful scripts by our excellent scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
to wheeze – to make a loud, windy sound while breathing, usually because one is not receiving enough oxygen
* My overweight brother was wheezing as he reach the top of the stairs.
short of breath – needing to breathe quickly in order to get enough oxygen, especially while performing physically demanding activities
* By the end of the aerobics class, we were all short of breath
lung – one of the two body organs in the chest that bring in air and transfer oxygen into the blood
* A smoker’s lungs are usually gray or black, not pink like a non-smoker’s lungs.
closed up – having become very small and constricted, without enough room to expand or move
* After her son died, it seemed like her heart closed up and she was no longer interested in friends or family.
to get (something) checked out – to have a body part or a medical condition examined and evaluated by a healthcare professional
* How long have you had that rash? I think you should get it checked out by a doctor.
asthma – a medical condition that makes it very difficult for someone to breathe from time to time, often caused by an allergy or by intense physical activity
* My sister had asthma as a child and she could not play the same sports that I played.
nasal passages – airways in the nose; the tubes in the nose that air moves through while traveling in and out of the body
* He has a cold and his nasal passages are stuffy, so he sounds funny when he talks.
stopped up – clogged; with something blocking the way or passage, so that things cannot move through an object
* The kitchen sink is stopped up and we can’t wash the dishes.
sinuses – the open areas inside the bones of the human face, connected to the nasal passages
* It started as a simple cold, but now it looks like he has an infection in his sinuses.
bronchitis – an infection and inflammation of the tubes leading into the lungs and the parts inside the lungs, causing coughing and phlegm (a thick green or yellow substance produced by the body)
* The doctor prescribed an antibiotic to treat Grandma’s bronchitis.
pneumonia – an infection and inflammation of the tubes leading into the lungs and the parts inside the lungs, so that the lungs fill with a fluid, making it difficult to breathe
* The hospital keeps the pneumonia patients far away from newborns and the elderly, who can get pneumonia very easily.
chest x-ray – a black-and-white photographic image of the inside of the body, taken through the skin, while the camera is pointed at a part of the body
* The chest x-ray revealed that the metal post had passed close to the heart, but fortunately, not through it.
positively – completely; entirely; thoroughly
* Getting that job would be positively wonderful!
giddy – so happy and excited that one is almost dizzy and out of control
* Falling in love made Jones feel giddy, and soon he was smiling and laughing like a little boy.
to be laid up – to be forced to stay in bed, usually due to a medical condition
* Melissa was laid up in a hospital bed for the last few weeks of her pregnancy.
upcoming – happening soon in the future; approaching
* Is everything ready for the upcoming conference?
out – a reason, justification, or excuse for not doing something or for not participating in something
* Having to wait at home for the furniture to be delivered was a perfect out from going to visit the in-laws.
Comprehension Questions
1. Which of these conditions could be a sign of an infection?
a) Asthma
b) Pneumonia
c) A chest x-ray
2. What does Russ mean when he says that Cheryl “sounded positively giddy”?
a) She sounded really sick.
b) She sounded very happy.
c) She sounded confused and disoriented.
Answers at bottom.
What Else Does It Mean?
positively
The word “positively,” in this podcast, means completely, entirely, and thoroughly: “Hank was positively thrilled when his wife told him that they are expecting a baby.” The word “positively” can also mean optimistically, or assuming that the best will happen: “Remember to think positively and never give up.” Sometimes the word “positively” means without a doubt: “I can positively say that that was the last time our company will ever make a mistake like that.” Finally, the word “positively” can mean favorably or in a good way: “Do you think the patient will respond positively to this experimental treatment?” Or, “The constituents have responded positively to Senator Markey’s voting record.”
out
In this podcast, the word “out” means a reason, justification, or excuse for not doing something or for not participating in something: “Are you using this business trip as an out to not attend your niece’s birthday party?” The word “out” also means not at home or not at the office: “Sherry is out for a few hours, but I’ll tell her you dropped by.” When talking about objects in the sky, if something is “out” it can be seen: “Look at how many stars are out tonight!” The phrase “out of order” means broken or not working properly: “Why are so many of these ATMs out of order?” Finally, when talking about time, the phrase “before the (something) is out” means by the end of something: “Please file those reports before the day is out.”
Culture Note
The Clean Air Act
The Clean Air Act of 1963 is a U.S. federal law that was designed to control “air pollution” (dirt and dangerous chemicals in the air) throughout the country. Under the law, the “Environmental Protection Agency” (EPA) must create and “enforce” (make sure people follow) “regulations” (rules) about “airborne” (carried by the air) “contaminants” (things that make something dirty or impure). The law has been “amended” (changed and/or added to) several times to make it more “comprehensive” (broader; covering more things).
The EPA website states that its enforcement of the Clean Air Act has reduced air pollution and “prevented” (not allowed to happen) many serious health effects that would “otherwise” (in other cases; if they had not enforced the law) have resulted from air pollution. The Act covers many air pollutants, as well as “acid rain” (rain that mixes with chemicals in the air to become acidic before it falls to the ground), “ozone depletion” (a reduction in the thickness of an atmospheric layer that provides protection against the sun’s UV rays), “factory” (where things are manufactured) and “aircraft” (airplanes) “emissions” (gases that are released into the air), and “evaporation” (the conversion of a liquid into a gas) of gasoline from automobiles.
One important “aspect” (component; part) of the Clean Air Act is that it “addresses” (deals with; handles) “interstate” (involving more than one state) air pollution. This helps states work together to address air pollution problems in a large area, such as when a large “metropolitan area” (city and the surrounding area) goes across state borders.
Comprehension Answers
1 - b
2 - b