

= 继承之战 S02 - 06
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



== 释义



'''

== pure


For a number of years, there was an unofficial company policy

on Cruise Lines that if there was a serious criminal incident,

we could minimize the incident to avoid negative PR.

- Incidents like... - Theft. Sexual assault. Murder.

Okay. The bad ones.

Yeah. There's hundreds in there.

All you have to do is sign out some boxes.

Do a little bit of shredding. Meet some lovely guys.

It's not a big deal, Greg!

We need this.

Bagging Pierce is the key to our proxy defense.

Any thought given to whom you might hand over the keys?

I really don't like to deal in hypotheticals.

For fuck's sake, Dad. Just tell them its gonna be me.

Here we are.

We want to announce the sale and Shiv

at the same time, or there's no deal.

That's not quite how I do things.

I could go to 25, but it would have to be fast.

Then in that case... Yes.

That's goddamn fucking right!

Here's to us.

Money wins.

So, pilot apparently says another half hour.

It's just slots, it's, 400 jets fighting over 100 spaces.

If I find some tech fuck gets landed before us,

I'm gonna kill 'em. Okay?

We okay?

On the Pierce deal they're entrenching on the break fee.

Very, very aggressive.

Well, fuck 'em, right?

I mean, they're empty suits, they're not gonna walk away now.

Maybe...

Maybe we just give them what they want.

We just give 'em what they want?

Excuse me, Dad, I think you just had another stroke.

I wanna sign here. Today.

Well, I think the one thing is just,

there could just be a burnout issue

- in terms of the teams... - No!

Ken, go. I'm tired.

Impress upon them that I need this done yesterday.

Okay.

We've been circling for a fucking hour.

When can we expect something in my hand?

- Imminently. - Like when?

Soon. For confidentiality, leak protection,

we kept the circle small.

- Everyone's spread pretty thin. - It's not fucking good enough.

You're fucking me here.

I'm making good faith fucking assessments

to my father, and you're making me look like a hack,

and I will not have it.

Stop sucking each other off back here,

and get fucking on it.

You pour the shit I'm pouring on you

on your fucking minions, and you ride them.

I don't care. 24 hours, rolling shifts,

crack the fuckin' whip.

Everything you're doing is fucking bullshit,

and I'm very disappointed in you.

I swear to God, I will fucking fire you

if you keep monkeying around... Put the fucking snacks away.

I don't wanna fucking hear it!

We've been circling for a fucking hour.

Tell them we're running out of gas!

Okay, you.

It's time for that most magical time of the quarter.

- Audit committee. 10-Q. - Sounds amazing.

Shiv. Come on. Shadow me, Shadow.

Frank, my dad's a prick. Come on.

Nothing... I got nothing.

You know what he promised me.

- And they're all up there. - I can't get into that.

What, you like this? You like being left behind?

There's limited attendance at Argestes.

They only have a certain amount of platinum passes,

- and that's all there is to it. - Yeah, right.

Because it would be impossible for them to get any more?

It'd mean finding printers and ink, and...

Inconceivable, right?

This is humiliating for you, too.

Come on, soldier. Let's go.

Now, I like to recite Prufrock internally

while we check we're GAAP compliant,

but feel free to use whatever method you prefer

- to numb the pain. - No. Fuck this. I'm going home.

- What... - I am going home.

- Come on. - I have shit to do. No.

I'm making a call on this.

Your dad asked me to take you through this stuff.

Well, you can tell my dad I made a decision. Okay?

It's Cruises.

Hi.

No, I can't talk, sorry.

Time is what I'm indicating here.

Mr. Roy.

- Welcome back to Argestes. - Thank you.

- Mr. Roy... - Yes.

- Welcome back to Argestes. - Thank you.

Programs, and suggested itinerary.

Itinerary, great.

'Cause I'm really hoping to get into some...

"Airbus culture hike", that sounds heart-breaking.

- Thank you. - Enjoy your stay.

Look at you scanning for influence like a yuppie Robocop.

So, what are you rocking for the panel?

Jacket or no jacket?

Right, like I'm gonna fuckin' tell you, dude.

- Fuck off. - Okay.

- Strategic advantage. - Fine. But fair warning,

I'm thinking of no socking it.

Rockin' some horny ankle cleavage.

Scary.

- I'm scared. - Yeah, you should be.

Or am I just saying that to psych you out?

There.

- Sir. - Excuse me.

- My sherpa, what's cookin'? - Yeah, just... just...

Might've just touched Bill Gates.

Did you check out the acoustics

on my room for my talk?

- I... - And did you get me on the culture hike?

And what did I... what did I get in my chalet?

Did I get the nut and fruit box

or the champagne and paperweight?

Nuts.

But... But the talk venue's great.

It's the same one as Roman and Ken.

- Okay. - Yeah. And...

And don't worry about the nuts. The...

The cashews are the size of boomerangs.

Okay.

Thanks.

Nice vest, Wambsgans. It's so puffy.

Thank you, Roman.

What's it stuffed with, your hopes and dreams?

Hiking boots. They're pristine.

Here we go.

All right. All rise for Pope Big Dick.

Hello, Rhea.

Mr. Roy.

You know what I need.

There.

Yeah, just to say, I don't know how

up to speed you are, with all of the details,

but, just to say that we're all lined up

for the ATN strategy announcement.

Yeah, same shit.

Different wrapper.

Well, I hope we're not gonna... We're not gonna go with that, banner, but we...

You know, we settled on, "We're listening."

- It tested great. - It tested fine.

Do me a favor.

Is that Sandy Furness?

Yes.

- Yeah, yeah. - Well, keep talking.

Keep talking.

- Yeah. - I don't want a bump in.

- Not here, not now. - Okay.

Vipers would love it.

Gladly... We'd be honored to be your talking partners...

So, basically, the talk is a celebration of

putting audience input front and center.

And hopefully be really inclusive

and quite changey after recent events,

because ATN Citizen is essentially

very similar but with the option of...

How's he... How's he looking?

Is he healthy?

He looks...

- Not really. - He looks a little enfeebled.

- Yeah. - I'd say.

I heard... I heard, maybe...

maybe syphilis?

What? Really?

- Interesting. - And that's definitely...

You don't really hear much about syphilis these days.

Very much the... The MySpace of STDs.

Excuse me, Logan.

I, just spoke to Karolina.

It came through.

They're asking for a response.

Get a room. But slow. No ripples.

A room?

Sorry. The magazine contacted Cruises directly.

- Who at Cruises? - Hello?

Just Florida PR.

Obviously, they thought they could get someone

who might spew if they went low on the food chain,

but I had 'em all briefed.

What have they got? How much have they got?

We don't know.

All they're requesting is a response on one element.

- Karolina said we had two weeks. - Yeah.

Well, I don't know where Karolina got that from,

so, I... I cannot speak to that.

So I have Shiv on the line, if that's...

Shiv, you're on speaker.

So, what the fuck is going on?

I hear there's a big muck-rake piece coming in on Cruises?

- Yeah, that's right. - So, what's in it?

We don't know exactly.

I'm sorry, who is this?

Hugo Baker, Senior Vice President Comms

for Parks and Cruises.

- Hi. - Wait. Is Dad there?

Does he know I'm on this call?

- I'm here. - Okay, so,

tell me again, how... How did this happen?

Well, we had a tip off some time ago.

New York Magazine working on a substantial piece.

They're, only giving us limited allegations

and asking for a response.

Okay, so there's a bomb about to go off,

and do we know what the fuck is in it?

Why do you do this, Dad? Why do you hoard information?

What you don't know can't hurt you.

Obviously, we are confident on our position,

regardless of the allegations.

And, this'll drop when?

Well, online first, thirty-six to forty-eight hours.

So, yeah. Not two weeks.

Again, I've no idea where that came from.

So, this sinks Pierce, right?

If you don't get that done and signed off before this drops, then...

Can we kill it?

No, you can't kill it. Key.

I've killed bigger.

No, not in the last five years.

Respectfully, Shiv, take a beat. You're new to this, yeah?

Yeah, and thank fuck for you I am.

This stinks of stale, pale male,

and you need an outsider to advise.

- Cease and desist, right? - Yes, Hugo. We're on that.

No, we go, how deep are their pockets,

fuckin' scare the shit out of them.

Yeah, get word around,

our lawyers will go balls to the wall,

say he's super pissed.

Subtext is this is personal, we're feeling vindictive,

get the senior management asking where they'll go

- if we bankrupt them. - Dad, cease and desist

and a full-on shit-flinging freak-out is very high risk,

but we could get them to delay.

Tell them we'll get into it all with them,

we'll cooperate, play it all out, - and then stiff them. -

We could offer up morsels in exchange for postponement?

We might be able to find something,

- maybe out of the studios? - No.

Bigger. Juicier.

People who are... Sorry.

Fuck, I'm sorry.

People who are writing about cruise abuse scandals

are not gonna be getting all kissy for a plot twist

- on frat baby two. - No. Delay is too soft.

Dad, ignore him. Accelerate the deal.

What the fuck do you think we've been doing, Siobhan?

Well, I have no fuckin' idea, Dad,

because you never tell me anything.

Cave on everything,

get them to at least sign a letter of intent

before the story breaks, it should hold.

No, Dad, we go for the piece, we scare them into thinking

what they have isn't solid,

just fuckin' kill, kill, kill.

Ken, you're on that.

Start sprinkling how fucking unreasonable I am,

Gerri, foot down on the deal. LOI if we need,

they're half-pregnant. Let's finish the fucking job

- before this breaks. - Sure, but I have to say

- just legally... - Now.

I need it now.

What money's floating this year?

You mean for a white knight?

I could see what Roman could scratch up.

- Tom? - Roman's hungry.

All right. Shiv, let's get you out here.

- I need your help on the optics. - Excuse me?

No. I... I am not flying out to Argestes

to be the face of this.

Then what the fuck are you doing on the phone, Siobhan?

So, welcome everyone,

to the Airbus Cultural and Leadership Walk.

We're gathered here today with a commitment

to sustainability and stewardship.

So, this place-based learning today will focus on

creating opportunities for you to gain the...

- Sh... Tom! - Perspective for...

Sorry, Tom?

Tom!

- Buddy. - Problem.

You're not picking up?

- Dude, this is a great group. - Sorry.

You did good.

It's like I've fallen into a barrel of deal tits.

Yeah. So... So, there's a thing about your talk.

My talk?

Yes.... When it got circulated,

legal and comms wanted you to be aware that

maybe we shouldn't go with "ATN: We're listening."

Okay. I mean, I really do like, "We're listening."

It sounds like... I mean, it sounds like we're listening.

- No. Sure, it's just... - Yeah.

It's just, there's apparently, in the EPG

on the set top boxes,

the voice activation mode, it does...

Like, there's a gray area in terms of our data collection,

so that we are kind of like,

We actually are listening.

We're listening?

It's complicated, but... but, yeah.

It seems that we are sometimes,

listening quite aggressively.

- We're listening? - Yeah.

But it's just to, like, maximize the user experience.

But if that was to break,

- maybe... - Fuck!

So, yeah.

So, the question is, is it a smart thing for you to be saying,

"We're listening",

when we are indeed listening?

Why was I not aware of this?

Well, it's basically legal, the guy said.

But he didn't wanna put that in an email,

- so... - What am I gonna call it now?

I don't know. Maybe...

They suggested "we hear you." Is that any better?

We tested this, Greg! God damn!

- Yeah, I'd love to. Yeah, yeah. - Great.

Everything is okay?

Marcia.

It's possible that some things will come out.

Nasty things.

People will say things about me, about the company.

I might need to know you're with me.

Logan...

when I am with someone, I am with them.

Look at me.

I know who you are.

Rome.

You see that guy?

Asgarov.

Eduard. Him?

Your dad is intrigued by sounding out big money,

in the event that the Pierce deal goes under.

Well, it's a done deal though, right?

Yeah, I don't know.

Could you start a conversation

in case we need an emergency exit?

White knight, go private?

With Eduard?

In his loafers made from the skin of... I don't know,

what is that? Human rights activists?

His dad has a hose attached to the central bank.

He's apparently conceptualising a 300-year investing horizon.

So, this is what, make-up sex?

This is you grinding yourself against me

and saying sorry for not telling me about Shiv and Dad?

Roman, your dad wanted Tom on this. I said you.

Come on, please.

I don't know what the world is gonna look like in 36 hours.

Just... Just do what you can.

I don't know if it's wise for us to be seen talking.

I can take a bit of tittle tattle.

Well, you're an old rhino.

I'm just a flighty, little sparrow.

We'd like to ink it here tomorrow.

Sure... I mean,

we appreciate the need for expediency from your end.

From what I understand, we're still some distance apart.

The break fee?

Tell your crowd if they push, we'll cave.

Undermining your own position?

Could you sue yourself?

Listen, Rhea.

Can you persuade her that if she doesn't sign here tomorrow,

we might walk?

Later....

I hear the culture hike's the hot ticket.

But I'm not sure you're crazy about either one of those things.

- For tomorrow? - So, 11:00 AM,

we've got Thomas Fisher doing "Qualities of Inequality".

- What difference... - Right.

Look who it is.

Daddy's boy.

I hear your staff are all killing themselves now.

Yeah, at the thought that you could be their boss.

Which you never will be.

No, sure, because of all the acquisitions

you guys are making, like, really bloating yourselves up?

There's a 75-dollar Cobb salad here.

Dude, you should buy that, use that as a defense.

Yeah. Yeah, maybe.

Either the Cobb salad or something else tasty.

That's... scary. What could that be?

Is it a hamburger? Is it calamari?

Is it fuckin'... Dude, is it Napster?

Look, I'm just gonna say, honestly,

we have something coming in,

and it's gonna make your deal untenable. So...

I thought, as a friend, I should mention it.

That's kind.

That's like BFF shit right there.

Look, I'm not fuckin' with you, Stew.

I swear on my children's lives

that right now, we have a deal in the bag

so big that it's gonna kill your approach. Okay?

And I feel a certain level of regret

about how things have panned out between us.

The thing is, Ken, and due respect...

I really don't trust you.

So... So, wait a second. So...

So, we're gonna go with, we...

We're gonna go with, "we hear you"?

"We hear you". Yeah.

Are you still worried?

"We're listening", "We hear you"?

It's the same problem, isn't it?

Well, it's maybe less active.

You know, it's... it's more... Couldn't...

"Couldn't help glimpse you changing unless,

we put a spy cam in your shower."

"We hear you".

I think it's a problem. I think it's a problem.

We're... we're listening, we're hearing you.

I think it needs to be like, "We're hearing," but...

but nothing that's gonna bite me in the ass.

Yeah, okay.

- You know? - So maybe it's like, ATN

We're here for you", and "here" spelled H-E-A-R.

"We're hear for you"? That's just jibberish.

"We hear for you"!

Okay. "We hear for you." Yeah.

So that might be like, "We... We... We hear for you,

man, 'cause you don't need to hear. We hear."

- Yeah, we... - And also... also,

"we're here for you." Right? Is that...?

- Yeah. "We're your guys." - Am I making sense?

It's good, because it's like, it's not clear exactly what the hell it means,

- so, lots of wiggle-room. - Yes.

- "We hear for you." - "We hear for you."

- Yeah. - Okay.

- Okay. Wamsgans. - "We hear for you."

Excuse me, Eduard. Sorry, don't mean to be rude.

I'm, Roman Roy.

- Man. - How you doin'?

Do you think we can talk for a minute?

Sorry. Thanks.

So, how you doin' with...

You know, just walking around, getting pitched to fuck.

Yeah.

I hear you're in trouble.

The proxy?

No. I mean, we're under pressure,

but, yeah, nothing we're worried about.

- Thanks. - Right. So...

you wanna hit me up for my big bag of swag?

Borat the fucking pipeline piece of shit?

No. Come on, man. You're a discerning fellow

that everyone, like... You know... Are you kidding me?

You're like fucking Warhol of, you know...

- of... - Of?

- Of? You know where I'm from? - Stanford?

I mean, Originally... No, I don't.

I do not know where you come from,

and you know what?

I'm embarrassed about it. I would like to know.

Man, the shit happening in Baku...

I'm serious.

You're laughing at us? We're laughing at you.

What is it you're, bringing to me?

Other than a begging bowl?

No begging bowl here. Just, you know,

offering you some, maybe, investment, opportunities.

You're a fucking news guy, right?

- Yeah. - Why is the news so...

- You know? - Yes.

- No, I know... I know. - Yeah.

It's very... Yeah. I don't know why the news is like that.

- I hate that. - We can talk about that.

Sure. Absolutely.

Yeah, the news with a positive agenda.

A positive agenda for my region.

Okay.

But independent. Real stories we'd fund, but hands off.

- Right. - Objective.

A hundred percent independent?

But from our point of view.

All right. Yeah. That's a really, really enticing project, yeah.

I'd like to keep the conversation going.

- Great. Good talking to you. - Yeah.

Sorry. Big fan...

of... of all your money.

Thank you.

What's going on?

You... You doin' the old cocaine?

Could I get... Maybe get a little bump?

Bump? Greg, what happened?

It's like a power party out there.

Like, tech titans and, like, supermodels, and...

I just need a little boost.

Okay. Well, good luck with that.

- Dude, come on. Come on. Stop. - No.

They don't have paper towels. They've gone all green and shit.

Dude, seriously?

So, all of a sudden, I find myself in charge of like a billion-dollar budget,

and it's really exciting. And it's... And it's...

I thought I would... I thought I would...

You know, I would suffer from the pressure,

but I fucking love it. I really love it.

My God. Shiv! What the fuck?

- Nice to see you too, Tom. - Nice to see you.

How are... Why didn't you tell me you were coming?

It was a last-minute thing.

- Hi. Shiv Roy. - Pleasure. Nia.

Of course. Yeah, congratulations on the IPO.

- Thank you. - Would you just...

- Could you give us a moment? - Yeah.

- See you later? - See ya.

But you're here.

- Hope that's not inconvenient. - No! No.

No, I'm not being... No. It... It's nice.

This. It's just... You know, you're often...

It's unsettling. I mean, the texts.

Yeah, sorry. It's... I've just been busy.

Whatever.

There's a potential crisis coming....

There's a journalist looking into cruises,

and there's a big piece coming.

Okay.

- What? - We don't know exactly.

- Come here. - Shit.

Are... Are they scapegoating me? Is the piece about me?

No, the piece hasn't come out yet.

- No one's read the piece. - Is this about... No. Okay.

Nothing has happened. No, we're jamming it up.

I'm just telling you what I know, okay?

Okay. Have I gone red? I feel like I'm going red.

Suddenly everyone wants me here.

- Gerri called. And Rhea called. - Right. Rhea?

Yeah. Suddenly I'm everyone's favorite piece of blast protection.

- Right. - Yeah.

- Bullet-proof tits or something. - So... So what...

What do they want a quote on? Did they ask for me?

Tom, the piece is not about you.

But there's a trail from... There's a trail from Mo

to Bill to me. You're safe.

- Which is good, but... - Yeah.

I'm on the outside. I don't know anything.

- That's why I'm useful. - Yeah.

Okay.

Were you trying to bang Nia Bayton?

Excuse me?

Nothing.

Well, no. God! No.

- Shiv. - Right. Fine.

Shiv.

I mean, I wasn't. But if I was...

that would actually be, under the arrangement, okay.

You know?

- Tom. I know her. - Well, you know of her, but...

It would be a bit fucking awkward.

Just use your common sense, okay?

Right, 'cause I might say that, you know,

spending the night with an actor

in a play financed by your brother

and not telling me for ten days was a little bit... awkward.

Come on. Nia's a real person.

With a face.

Fine.

No.

Okay.

So, anyway. It's nice that you're here.

Yeah, I missed you.

How'd it go?

He might be good for infinite billions,

but he wants a front news channel to spew propaganda.

- We into that? - I guess.

- Depends on the numbers. - Right.

Plus, the whole... I mean...

Obviously, it's an ethical minefield.

Sure. Of course.

But if we took a position of "fuck it"?

Well, that's an interesting ethical position.

Silo it off?

Well, what is it? Why's he got me chasing this?

He still hasn't told you?

Pathetic, isn't it?

- I don't know. I can't say. - Right. Course.

Course not.

You know, right now, if, you know...

If anything happens to him, you're on the piece of paper

as the next ruler of the kingdom.

I think I've been made well aware of how unlikely it is that will transpire.

Sure. Right. But you know how you're...

so efficient and good at your job?

- Well, thank you. - But also sort of, like,

invisible? Like wallpaper, like a...

boring old sort of nothing.

Like a competent kind of clever filing cabinet

that everyone seems content to have around?

- And I'm like a fucking - rockstar moron. - Right.

I mean, obviously, these are our public profiles,

not our true essences.

I have thoughts, but continue.

Well, just floating, like, is there an angle here,

for a team up?

Like, me, kind of a Jagger-Tarzan,

fronting things up and swinging through trees

with my little dick, singing and killing shit,

and you, back home, cooking us soup,

and making sure the numbers are right.

Rockstar and the mole woman?

You're really selling me.

But it would be chair and CEO.

Or CEO and chair.

And you will get properly "fuck you,

fuck you, I don't even care about climate change,

I'm in New Zealand with my own private army" rich.

Not like some pathetic asshole beach house

on the Vineyard rich.

It's late.

Off you go.

Thanks, mole woman.

Thanks, rockstar.

Night night.

God. Here I am.

Is he gonna make me take off my shoes?

- You slept okay? - Couple of hours. The usual.

What am I supposed to do with this?

- You wear it, Nancy. - Absolutely not.

Come on. Join the fun.

A show of false humility. Everyone wears one.

Zuckerberg wears one.

Hand me a pen and I'll write my name across my face.

You okay for this?

I think I made my position perfectly clear,

but for whatever reason you felt it urgently necessary

to put me in transit for grapefruit juice

- and a plate of eggs. - You should go at your own pace,

absolutely, that's imperative.

I just think this is such a good deal for you.

For... For us.

That it's worth a little haste.

So, we have a little room for signing right in there.

Just in and out, and boom. You okay?

Is it the altitude?

I don't know. Maybe. What... what's...

- What's with the...? - Yeah, let's...

- Let's move you around. - No, no. No.

I'm not in a fucking wheelchair. You don't...

I'm good. I'm good.

- Sunglasses. - Yeah.

I just had a call from Karolina.

The magazine is not cooperating.

They feel bullied, and the piece might go up

this morning. Print, Monday.

Fuck, fuck, fuck.

Well... When? How long do we have?

Hours. Maybe minutes. I...

What do we do? Do we bail?

Dad?

I'm thinking.

We should leave. We need to get out of here.

Let's leave. We go..

Apologies.

Well, I feel like the belle of the ball out here.

Very discreet.

You're happy with this table? Visible enough from all sides?

It's all quite adolescent, isn't it?

So, we're there. Correct?

Happy about the break fee, the rest?

Sorry, did I miss the preamble? I heard that you were

going to apologise for your outburst at Ternhaven.

I... I... Sorry. I'm tired.

Well, that's appreciated.

My dad is just reflecting our desire

to get this concluded as swiftly

- and amicably as possible. - Yes.

Every day a letter, a meeting, a call.

I'm afraid my metabolism tends a little slower.

We're due a check-in with the cousins later on this afternoon.

Yeah, but we can sign.

We are ready to sign.

- Ken? - Yeah. Right in there.

We thought we could sign and then have a nice breakfast - out here.

But before we do, I...

I think there's perhaps a wider conversation to be had here.

We would be interested in exploring the option... I'm sorry. I...

I can't concentrate until I order.

Good God, the prices.

I'll. I'll just have tap water, thank you.

No, no, thank you.

We would be interested in exploring the option

of a bonus based on PGM performance.

Of course. We could cover the legal fees.

Your side, outside counsel.

The whole thing.

Well, this... this isn't really for us to discuss here, surely.

Well, I think I've explained, there's a limit to our patience.

Logan, I think perhaps we're not going to agree

to anything over watermelon.

Well, what's it gonna take?

Why are we still fuckin' around?

I think perhaps we all need

a little less sunshine and vinegar.

It always gets a little testy at the end. We're all good.

Nan, is there not a way we could sign the LOI at least?

Dad, I'm wondering if

maybe we should get to our next appointment?

Yeah, sure. Sure.

Why don't you do that? Let us chew a while.

- Soon. - See you later.

So, what do we think?

It's bad, but not... I don't know.

We should have gone at them harder.

Paper copy. Now.

Coming up from reception in two.

So everyone in the fuckin' world has read it except me?

Okay, so where's the link? Why did no one send me the link?

Just fucking Google it.

Google what? I don't know what we did.

"Brightstar roller coaster rape."

- Give me something. - Sending link now.

Thank you.

Well, fuck me.

Do you think they could make this text any fucking smaller?

This is pretty gray.

Yeah, but also vivid.

Great work on frightening them off.

Good work on stalling.

I'm reading.

- Thanks for coming. - Yeah, sure.

Is everyone here remedial at reading? Come on.

Is it me or is this bullshit? Maybe this, maybe that.

- Rome, careful. - Is this one of those things

that I need a woman to explain to me why it's bad?

- Shiv? Is it bad? - Don't fuckin' ask me.

I'm not your grope Geiger counter.

What do you think, Rome?

I do think it's bad, but it's not that fuckin' bad.

Fuck.

What's the protein?

They found a woman, Keerson.

She was working the cruises back in the mid '90s,

name-checks Lester McClintock.

She says Uncle Mo asked for sex with her and the other dancers

to get their contracts renewed.

Were all of you in on this?

Did you all know this was coming?

- It's not ultra-detailed. - Amazing.

- So they fucked. - It says sexual exploitation.

Yeah, she's saying that she was one of the only ones

who refused to sign an NDA

and that we derailed her career as a result.

- Is that it? - No, look.

The old Hewson story, the woman that jumped and drowned...

what if something happened to her?

It's... It's just innuendo.

The dancer says that she heard stories of

dozens of other women who actually signed the NDAs.

Okay, but in terms of actual stuff?

There's not a lot of specifics. It's spooky words,

you know, data wipes, NDAs, shadow logs,

hiding cruise malpractice.

But cold hard facts, it's one woman in the 1990s,

not like 20 women four years ago.

Great. I'm glad we're able to do such good victim math.

Gerri's just saying it doesn't necessarily - punch through.

Sure. But you know...

- this is not okay. - We know it's not okay, Kendall.

We're preparing a corporate response.

Do we have outside PR?

Pinks passed. We've got J Preston.

No, seriously?

They're three disgusting, old, white dudes.

They'll probably just say they're money-grubbing sluts.

- It's bad PR to hire them. - I mean, call me sociopathic,

but doesn't this all seem a tiny bit...

quaint in comparison to the past few years?

He's right.

It's cultural splash back.

We're being punished for the sins of others.

No one real gives a fuck.

No, no. We... We can't be seen to minimize.

I think we need to loudly and quickly say

that this is not okay.

I think the question is what closes this down fastest?

Do we say it's something and we'll fix it,

or it's nothing and fuck off?

Something. There have to be consequences.

Nope. Condemn and move on. It's just good advice.

If we get into it all, they'll never be satisfied.

It's bullshit. It's all about me.

It's not real, it's not honest.

They don't give a flying fuck for these poor bitches.

They hate me.

So, no! Condemn and move on.

New circus in town tomorrow.

What about the, panel? Kendall?

Roman? Do we cancel?

No! Fuck no!

No. Obviously not, no.

- I meant... - Obviously, it'd be great

if we do go ahead with it, to, have a person

who could speak to it in terms of...

A woman.

- Gerri? - Well, not legal counsel.

That gives the wrong sign.

No, I mean... It's something of a no-brainer.

I... I don't know, I...

- Come on. I just got here. - Shiv.

Would you? Please?

Come on. I'm not good enough for an invitation,

and suddenly this blows up and you wanna jam it up my...

fucking uterus and smother it in estrogen? Please.

No, I... I'm not fully briefed.

We don't need Shiv. I can do it.

We can do it.

Fine. We could do with your help,

but fine.

Okay. Let's get out there.

- Walk of shame? - Yeah.

Everybody out. Business as usual.

So, you want me to touch base with Rhea,

- take the temperature? - No, no, no, no, no.

No one speaks to Rhea.

- Me, Laird, no one else. - Right.

Shiv, you're with me.

Little miss fucking credible?

Logan, your 6:00 PM canceled.

- Also, your 7:30. - Qatari money?

He said he'd meet for coffee.

Wary about dinner.

And Jack canceled dinner.

Playground bullshit.

Everyone's waiting to see how it plays out.

Hang back a second.

What's up, dude?

I guess if you did have something going on,

you know, like, deal-wise, it's kinda, like,

dead in the water now, right?

Like some of the women that went on those cruises.

Ken, I'm so sorry, bro. I feel for you.

- Hi. - How are you?

Okay.

- You? - Yeah.

Good.

Jamie...

- You've seen? - Yeah. It's not good.

- No. - It's not good for the Pierces,

it's not good for the proxy fight.

- I need to speak to Rhea. - I've tried calling.

Several times.

I'm wondering, in any event,

if I'm the right flavor of person to be reaching out.

Now my reputation seems to be a fluctuating currency.

But, young Siobhan, she's as close to T-Bills

as we're likely to get.

Dad?

- Christ. - My God. Dad.

- Jesus. - Dad?

- Are you okay? - Yeah, yeah, yeah. We're fine.

We're fine.

- I'm fine. I'm fine. - Okay. We're fine. Thank you.

Hi.

Sorry I couldn't meet you for coffee.

I've had wall-to-wall meetings.

No, it's... it's fine.

You're hiding from us. I'd do the same.

How's your dad?

The rumor mill is saying practically dead.

Yes. Fine. It's... It's the altitude.

So...

The piece. I'm sorry for all the fuss.

You know how these things are.

No, I... I don't, actually.

Okay. Well, for a few days...

you know, people step away from you

like you farted on the dance floor

but you ride it out. It's no big deal.

But you're here. Checking in.

Yeah. Well, I was surprised that you called.

The acceptable face.

Right.

So, you heard the piece was coming,

and you're still pushing this?

You must really want this to happen.

Well, I'm easy come, easy go.

And, where is everybody else's head at?

Well, some of the cousins are still reading,

which is surprising, because...

they have views on the new Jonathan Franzen

three days before it fucking hits the shelf.

Comfy on the fence?

Yeah.

What about Nan?

She's quite unhappy.

She doesn't like a muddle.

Well, I'm around if she has any questions,

or to allay any fears.

- Sure. - Thank you.

I guess our first question might be

did anyone kill any girls on your boat?

No.

And, you know, statistically speaking,

liners have a high death rate simply because of the alcohol,

and the profile of the people who tend to...

Yeah, but the fact that I'm even having to ask...

Dead girls, boats?

It's unpleasant on the tongue.

Well, perhaps the family would be more comfortable

seeking another source of investment.

I like your dad.

But...

what sort of a problem are we looking at here?

Are we in the middle of the storm,

- or is this the first raindrops? - No, my dad has assured me

that this is not a major issue.

Truth is it's in the balance.

I think we... they feel that

if it was just a few bad apples from a long time ago,

then maybe they can grit their teeth.

Well, that's going to be the line,

- so... - Good.

Well, Nan is coming to your panel,

so I'm sure your flacks are getting you all

jumping through hoops,

but if you could apply a nice tourniquet,

then maybe we could patch this up.

Yeah, it's just gonna be Roman and Kendall.

Right. Roman. Okay. Lovely guys.

- I thought perhaps you might... - No.

No, I'm not, fully briefed. So...

Yeah.

Could you get briefed?

I guess.

-This isn't really my mess - to clean up. - No. Sure.

But... And I mean, I don't wanna overdramatize,

but Nan gets cold feet and you can't buy us.

Your dad could lose control. He could.

That's real.

There are many different angles to me appearing on that panel.

Sure. I get it, honey. But listen.

All I would say is there is a time

to accumulate capital, and there is a time to spend it.

But whatever. My dad worked in an asbestos plant.

So...

It's all gravy, right?

And Roman, the safe place is the three Rs, okay?

- Yeah. - Regret.

It happened a long time ago.

Responsibility.

Belongs to individuals and not corporations.

Remedy. Super tough, super vague.

The move is condemn and move on. Got it?

- Yeah, got it. - Okay.

Right, and if you need to smash glass

in case of emergency,

it's enough of that and back to the session.

Family ownership and corporate continuity in the digital age.

Whatever the fuck that means.

So, listen.

I think maybe I should help out and do it.

- The panel? - What?

- Yeah. - Right,

but it's like nine minutes till show time.

Shiv, no. We already decided.

Yeah. We're all prepped.

Okay, fine. So, send out the two cover stars

for Toxic Male Monthly, and,

why don't we get Ted Bundy up there,

- make it a three-way? - Shiv, don't fuckin' pull this.

- Okay? We... We asked you. - Yeah, and I thought about it,

and I changed my mind.

- What do you think? - Me?

Well...

- It's difficult. - It's difficult.

I'm sorry, buddy.

Would you like a handjob and an Advil?

Fuck off then.

It's smart.

Shiv works.

It's smart? A sudden, last-minute line-up change?

Come on, man. It's panicky as fuck.

She's not even in the company.

It looks... kind of fucking cheesy...

- Yeah. - To be honest.

Like, throw our token woman at it?

Well, it can't be two men up there right now. It just...

It can't. Right?

I mean, if disruption is an issue,

the audience is expecting just Roys,

so, maybe... maybe we stick at two, and...

someone relaxes.

- Romulus. - What, pull me?

That looks like a humiliation.

Well, we could just say you got sick.

No. No, you don't bump me. That's bullshit.

Fuck that. Respectfully, Dad, why is she even here?

Because I was fucking invited.

No. I need to be out there, okay?

We need to hang tough, you know? Together. Family.

Okay, so let's just get Connor down here, then?

- Yeah, get Connor... - We'll all pile on

so no one's nose gets put out of joint. Is that...

- That's the important thing. - I will put your nose

- out of joint - You should say that on the panel.

That's a funny joke, Siobhan.

If you wanna know what I really think, I think

you should drop both these two, and I'll do it solo.

Someone thinks they're Beyonce.

Pretty desperate, Shiv. You know,

exploiting the situation for personal gain.

I'm just thinking about what's best for the firm. Okay?

Sure. Sure. No, that's...

That's coming through loud and clear.

She's a loose cannon. She is out of control.

Look, Dad. I don't care.

I can make this go away. I know this in my bones.

I don't need fuckin' flash cards.

I'm not officially in, so I have freedom of movement.

But if you don't want me, then I don't give a fuck.

I will go eat lobster and watch the fuckin' roast,

because it's all... it's all gravy, baby.

It's important to remember two fundamental things

about the news.

One: it's new.

All the things that are new.

The many news. The news.

Your boyfriend's really suckin' ass out there. - Two...

I'm sitting on the right when we're out there.

You know, I can see your bra through your sweater.

- Your dick's hanging out. - Guys.

- There's no way... - Guys, come on.

- Focus. - Ro, Ro, Ro.

Do you want me to get a booster seat for you,

when you're out there?

That's hilarious. Your period just came on.

We aim to evolve our coverage into something that is...

not only dynamic, but democratic.

And something that truly serves

our audience's ever-changing needs.

And that is why we like to say,

ATN, We hear... for you.

Thank you.

Thank you very much. Thank you.

- Well done, baby. - Good luck. Good luck.

Well?

Afternoon.

Where's Nan?

Thank you for joining us.

Next up, please give a warm Argestes welcome

to Roman and Kendall Roy,

joint chief operating officers

at Waystar Royco,

and political and corporate strategist, Siobhan Roy.

Welcome. You don't do many of these, Siobhan.

No. I'm... I'm hard to get.

I'm exceedingly easy to get.

So, I love this idea of corporate continuity

being a positive in the digital age.

But first, I wanted to give you the opportunity

to respond to the magazine piece, which came out today.

- Well... - Yes, well... Go ahead.

No, no. Go ahead.

I mean, I think the thing for us is...

we don't want to simply condemn and move on.

You know, we'll... We'll want to look into this,

investigate it thoroughly,

and then absolutely do the right thing.

I think we all have the same view on that.

And give us an insight.

Tough day for the company, Siobhan?

Well, obviously I've been, given the privilege of growing up

around the business, whilst also being able

to plow my own furrow on the outside.

She's been working in politics for ten years,

so don't hold out for a straight answer.

I wanna give you a straight answer.

Look, obviously, as you say, yes, it's been a tough day

for the company.

Sometimes there are... not errors, not misjudgements

in corporate governance,

- but... - Catastrophes?

Well, no, because it's not really about

corporate procedures here, is it?

It's about human decency

that transcends management structures.

I mean, you know, that's what's so abhorrent

about these stories when they come to light,

in whatever sector.

And sometimes it feels like,

"my God, it's... It's everywhere."

Yeah, that... that's absolutely right. - I mean,

the language... I just would say...

Yeah, we don't know.

Right now, we just don't know.

We haven't started the necessary investigation,

so that language is...

But absolutely, on the sentiment.

I think he's telling me to calm down.

No, no, no. Hell, no. No, I'm not....

I... You know, if this stuff is true,

doesn't matter to the victim

if these were isolated incidents that happened, you know,

many decades ago, right?

Right, and just because it did happen 25 years ago,

is not a reason to simply condemn and just move on.

No. No. Absolutely not.

You know, we've been accruing and maintaining brand loyalty

for decades, and that trust is a result of

knowing and respecting

- our customers... - Stop looking around.

You will hurt your neck.

To compromise that trust,

we'll take the necessary steps to make amends.

We'll do whatever it takes, you know.

We'll do whatever anyone wants.

You know, it's... it's about being completely unimpeachable.

And sometimes companies develop bad habits,

and you need fresh eyes, clean hands,

and new ideas to address those.

Yeah, I mean, that... That's, the great thing

about a company that's structured like ours.

We can do that while retaining core values,

you know, manage change.

He's good, right? He's great.

I think I'm a little more aggressive.

Sometimes I think you just need a good old fashioned dinosaur cull.

And who's the big T-rex in your sights?

No. I mean dinosaur attitudes.

Dinosaur values.

No, I would never go after my dad.

That's a sport others enjoy.

Tom. You did good.

Sorry I wasn't there for you before,

but, you know, "we hear for you" now.

No worries. You fucking shimmered.

- Thank you. - Was that all okayed?

Nice. Bring your daughter to the slaughter.

Tell the old dinosaur what you were gonna do?

I'm sorry.

"We will do whatever anyone wants"?

- Yeah. - Fuck it! Right? It played.

It's just words. There was no press anyway,

so who gives a shit?

What?

- What was that? - I was just dancing.

I'm sorry about Nia last night.

- You can do whatever you like. - Thank you.

It's not like I really want to.

- Really? - No.

Because, truthfully, when I saw you talking to her,

I wanted to smack her in the face and say,

"Back up, bitch. He's mine."

You should've.

I would've really liked to have seen that.

Yeah?

It was too much, Siobhan.

Dinosaurs?

Yeah. It was over the line. Shiv went over the line.

I... I think it was pretty clear

- that I was talking about... - No, it was clear. Yeah.

You tortured the old dinosaur. You barbecued him live?

Don't fuck with me!

No! Don't fucking touch him!

It's okay. Jesus, Dad.

It played well, okay? Word is it played well.

- It's okay. - Ro, are you okay?

Here.

- You all right? - You all right?

Yeah, I'm fuckin' fine.

Fucking leave me alone. I'm fine.

It's just a tooth. I'll get another one.

Ladies and gentlemen, as it's traditional

to roast us home from Argestes,

it's the Argie awards.

And please welcome your host for this evening,

Zell Simmons!

All right. How you doin'?

All right. Look at all you guys with your blazers on,

coming from Burlington Coat Factory?

That where y'all shop at?

I'm glad you guys are out here,

solving the world's problems.

I don't see you solving anything, jerk-off.

Yeah, that's like a guy sitting on a grain silo

in the middle of a famine, going,

"Why is everybody so down?

They don't have WiFi here?"

Did you talk to Roman? Is he okay?

Yeah. He said he wasn't gonna come.

But... But he was fine.

All right, who do we got here? Who we got here?

We got... The Roys are here! What's up, guys!

Shit, I hope he doesn't do me.

Ahoy there! Permission to never fuckin' board?

I think this is going to be a long bit.

I don't understand this tradition.

Why do we come to be insulted?

How is this entertainment?

I shouldn't even be joking about them like that,

because they're in the midst of a...

"hands on investigation".

Yeah, I hear there's a lot of deals going down here, too.

Man, someone's gonna make a sale.

To Waystar. I think that's great.

That's like the Hindenburg going down,

and they're like, "Yeah, hydrogen blimps.

Sign me up!

That's the future, baby!"

No, that's a horrible idea. It's worse than that,

at least nobody was forced to give a blowjob

on the Hindenburg!

Where are you going?

- You okay? - Yeah.

Look at Logan Roy, man. I love that guy, man.

- I mean, he's a very nice guy... - It's funny 'cause it's true.

Fuck off.

Nan.

- Nancy! - Let's talk later.

Here comes Rhea. Of course.

Let's talk.

I... I hope you're not swayed by...

I mean, you get these hothouse atmospheres,

- but we're good. - We'll talk.

- We're good though? - No.

But we can explain.

Look, it's... It's a tempest in a tea kettle.

Relax. I drink them by the pint.

Thank you. I am perfectly relaxed.

But if you want to talk about it,

- it's over. - Nan.

- Come on. Calm down. - A few bad jokes,

what, and you bend?

I think you're made of stronger stuff

- than these Palo Alto pricks. - It's intolerable.

I had a call with the family tonight,

on a number of matters,

and they've left it in my hands.

Which call? After... After our call?

Rhea, may I ask you something? Have you ever had

any communication or meetings with Logan Roy

- that I'm not aware of? - What?

Not...

- Not in terms of... - Are you trying to figure out

what your attorney would let you say?

- No! I have always acted with... - I have been rolled.

I have been sand-bagged.

This is a good deal!

You spoke to Logan on the 13th.

What was the nature of that discussion?

I do not recall. It could have been any number of...

I would like your resignation.

I don't appreciate being hustled.

This is a good fucking deal!

You won't get a deal like this again.

It is a good deal,

and I have never had anything in mind

other than what's best for Pierce.

Horse potatoes.

You work for Rhea Jarell.

And as long as our interests were aligned, it was fine.

You'll be hearing from the lawyers.

I haven't finished.

Good night to you both. Good riddance to bad rubbish.

You turn this down

and you're fucking your whole family.

I think my family will be fine,

but thank you for your concern.

- Let's go. - Wait!

We haven't finished! We haven't fucking finished!

Do you hear me?

We haven't... Stop! Stop! Stop!

Do... Fucking... Stop! Stop!

