


= Sex.And.The.City s01-11
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

New York City is all about sex. +
People getting it. +
People trying to get it. +
And people who can't get it. +
No wonder the city never sleeps, +
it's too busy trying to get laid. +
But if you ever actually do manage to get someone in bed, +
the real fun begins. +
That's the kind with nuts in it. +
Mm-hmm. +
We love our nuts. +
Mm-hmm. +
Mmm. +
After sleeping together for many weeks, +
Mr. Big and I had gotten comfortable enough +
to really sleep together. +
It was nice. +
It was the way I'd always dreamed it could be. +
Good morning. +
Morning. +
Was that you? +
Oh, my God. Oh, my God. +
I think it might be worse under there. +
Shut up. Shut up! +
-Shut up! +
I hadn't dressed so quickly since the time I was caught +
in the boy's dorm sophomore year. +
Wait. Don't you want some coffee? +
Oh, gosh. I'm late for a thing. +
Oh, my God. +
I was mortified. Oh. +
I didn't call him the rest of the day. +
I tried to lose myself in work, +
but every time I stopped for a second to think, +
-Oh, God. +
I'd relive my hell all over again. +
The next day, I realized how childish I was behaving. +
I decided to stop avoiding the situation +
and take the grown-up approach, +
complete and utter denial. +
Oh, so I saw The Met is opening a new Goya exhibit. +
Do you want to go this Saturday? +
Sure. +
Could you get me some more duck sauce, please? +
I most certainly can. +
Oh, and then we have to stop and see the Renoirs. +
I love the Renoirs. +
Okay. +
There's a moment in every relationship +
where romance gives way to reality. +
You know, you know what? +
I'm exhausted. +
You mind if we just call it a night? +
-Okay? -Sure. +
Sorry. +
Goodnight. +
That was the first night we slept together +
and didn't make love. +
By the middle of the next week, it was three times in a row, +
and I was beginning to worry. +
Three times? +
Try three months. +
-No. -Yes. +
Now would be a good time +
to wipe that horrified look off your face. +
Sorry, sweetie. I'm sorry. +
I just-- wow, I didn't know. Where have I been? +
You've been having sex. +
I've been at Blockbuster renting videos. +
It's tragic. +
I'm like two rentals away from a free pound of gummy bears. +
Oh, relax. You're just in a dry spell. +
I can't believe you said that. +
You're all freaked out about three times. +
-I'm talking three months. -Yeah, but that's different. +
Not doing it when you're with someone means much more +
than not doing it when you're not with someone. +
What are you worried about? +
I thought you said everything felt +
really comfortable and great. +
Yeah, well, maybe too comfortable. +
What do you mean? +
I farted. +
I farted in front of my boyfriend. +
And? +
And we're no longer having sex +
and he thinks of me as one of the boys. +
And I'm gonna have to move to another city +
where the shame of this won't follow me. +
You farted! You're human. +
I don't want him to know that. +
I mean, he's this perfect guy. +
You know, he walks around his perfect apartment with his perfect suit. +
And he's just perfect, perfect, perfect, perfect. +
And I'm the girl who farts. +
-No wonder we're not having sex. -You're insane. +
It's been three times. +
It's perfectly normal. +
Says who? +
I mean, say it's not the-- +
then what else is going on? +
I mean is it normal to be in the same bed and not do it? +
I guess it depends on what's normal for you. +
Oh, God, I hate that. +
Who am I to know what's normal? +
I've been dating a hundred years, I don't have a clue. +
Well, three months is not normal for me. +
One month was interesting. +
Two months was numbing. +
Three months, I am going out of my mind. +
There are 1.3 million single men in New York. +
1.8 million single women. +
And of these more than 3 million people, +
about 12 think they're having enough sex. +
How often is normal? +
I have to masturbate three times a day just to make it through. +
Some people take coffee breaks. I take jerk off breaks. +
They say the average 33-year old woman +
has sex 3.5 times a week. +
I'd like to know who that woman Is. +
You know, my wife and I haven't had sex since the baby was born. +
The baby's applying to Yale next fall. +
Oh, once, one time a day, but two time on very special day. +
Normal is the halfway point +
between what you want and what you can get. +
Even in the plow position, +
I could count on Samantha for amazing sexual clarity. +
Very good. Let's move on to downward facing dog. +
Whoof. +
With him, I could do it every hour on the hour. +
Do you think it means something +
if Big and I are sleeping together +
but we're not sleeping together? +
The truth? +
When have I ever wanted that? +
Yeah, okay, tell me. +
I think there's trouble. +
I mean, sex is a barometer +
for what's going on in the relationship. +
Well, I wasn't going to tell you this, but, um... +
I farted. +
Then move your mat away. +
Not now. +
I did it in front of Big. +
Huge mistake. +
You think? +
It wasn't a choice. +
I'm human. It happened. +
No, honey, you're a woman, +
and men don't like women to be human. +
We aren't supposed to fart, +
douche, use tampons, or have hair in places we shouldn't. +
I mean, hell, a guy once broke up with me +
because I missed a bikini wax. +
I knew it. +
This is a watershed relationship moment +
I'm never gonna be able to erase. +
Oh, sure you will. +
Just go over there and fuck his brains out, +
and he'll forget all about it. +
Men aren't that complicated. +
They're kind of like plants. +
Concentrate. Quiet your insides. +
Now he tells me. +
Roll over on your backs. +
Take Goddess pose. +
Let your breathing work with you. +
In and out. +
Ahh. +
In, out. +
Ahh. +
Would you like to go for a coffee some time? +
Forty-five minutes and three animal positions later, +
Samantha and Siddhartha were sipping green tea at a nearby health food restaurant, +
Tofu or Not Tofu. +
I always feel so amazing after yoga. +
My body feels so open. +
So alive. So ready for anything. +
Samantha. +
Yes. +
I'm celibate. +
I practice Brahmacarya, tantric celibacy. +
I gave up sex three years ago. +
My God, why? +
Or more importantly, why? +
Didn't you like it? +
Oh, I loved it. +
I'd have sex morning, noon, and night, +
sometimes three women a day and I was always ready for more. +
Well, now you're just being cruel. +
No. +
It was all ego. +
And where I am now is so much better than sex. +
Oh, come on, honey, nothing's better than sex. +
Think about really good foreplay. +
Your sexual energy's just starting to awaken. +
Now, imagine a three-year foreplay +
where all that sexual energy is coursing through your body, +
but it never gets released. +
It just recycles, +
builds, +
rises. +
Until your entire being +
is humming with that electric sexual energy. +
My apartment's just around the corner. +
The only thing hotter than sex is not having sex. +
Amazingly, +
talking dirty about not having sex +
was the most sexually deviant act +
Samantha had participated in for months. +
The next night, when I met Charlotte for dinner. +
I had reached my own transcendental state, +
pure Mr. Big obsession. +
Okay, um, the first time he was tired. +
And the next two times, I... +
I don't know. +
-It's bad, isn't it? -Carrie, relax. +
There's nothing wrong with your relationship. +
Well, that's not all, Charlotte. I, um... +
What? +
I couldn't bring myself to tell her. +
I was afraid she'd go spontaneously deaf. +
I'm sorry. +
Um, what, what were you saying? +
People put too much emphasis on the importance of sex. +
It's not the most important thing in a relationship. +
Right. +
Take Kevin and I, for example. +
We've been going out for weeks and we still haven't done it. +
I mean, +
we touch and cuddle, +
but he's sweet, and he respects my boundaries, and I like it. +
It makes it special. Oh, there he is. +
Meeting a friend's new boyfriend for the first time +
is always a little tense. +
What if you don't like him? What if he doesn't like you? +
Kevin, this is my good friend, Carrie. +
-Hey, Carrie. -Hi. +
What if you've already slept with him? +
You two know each other. +
Well, kind of. +
We used to go out. +
Well, kind of used to go out. +
-You two used to go out. +
That's so funny. +
Isn't that funny? +
That's my office. I gotta take this. +
I'll be right back. +
Okay, when? +
Um, three years ago. +
Three years, I can live with that. +
Serious? +
-No. -Good. +
Why'd you break up? +
You know, we were in different places and I just-- +
Carrie, we don't have time for diplomacy, just tell me. +
He's a sex maniac. +
When Charlotte discovered that Kevin had tucked his libido away +
for her comfort level, +
she was even more moved by his restraint. +
I want you to know how much I appreciate your patience. +
Hmm? +
Well, you've been so patient with me. +
It shows how much you really care. +
And all that waiting +
is gonna make it all the more special for us now. +
Oh. +
There's only gonna be one stop. Thanks. +
I don't think this is gonna work. +
Why? Is it me? +
No, you're great. +
I'm just not that sexual a guy. +
It's me. I know it's me. +
Look, Carrie told me that you were quite sexual. +
In fact, I believe she used the word "maniac." +
That was before. +
Before what? +
Prozac. +
Prozac? +
Yeah. I used to be such a mess. +
Mr. Mood Swing. +
It's a total lifesaver. +
The only downside is is it takes the air out of my tires. +
After a while, it's kind of like a taffy pull. +
That's okay. +
Don't worry about it. +
I don't. +
I mean, I wish I could say I felt worse. +
But to tell you the truth, +
these days, nothing gets me down. +
Do you want to watch a movie? +
Terrified of going to Mr. Big's +
for what could become another platonic sleepover, +
I paced my apartment and tried not to think about our lack of sex when... +
there they were, my new neighbors, +
Mr. and Mrs. Get It On. +
A couple so obviously into each other +
there was only one thing to do, +
watch. +
Then something wonderful happened. +
My desire overcame my fear. +
Hi, it's me. Um... +
is it okay if I come over? +
Okay. +
Meanwhile, across town at the corner of "Nirvana and West Third," +
Siddhartha was helping Samantha along her newfound path. +
Blocks are a connection to our inner life +
and true identities. +
You're hard. +
I know. +
Our addictions and attachments +
are a way to block our spiritual hunger +
through unhealthy and dependent ways. +
You're still hard. +
It will go down. +
So can I. +
I showed up at his apartment feeling sexy and confident, +
wearing my secret weapon skirt that really hugged my hips. +
I was ret to go. +
He didn't have a prayer. +
Very nice. +
Come on in. I'm watching the fight. +
Baby. You... +
Carrie. Come on, come on. +
Let me watch this. +
Oh, man! +
Jesus, Carrie, come on! +
Would you knock it the fuck off. +
I'm trying to watch this fight. +
-Just-- -Fine, I'll leave. +
What-- What is wrong with you? +
-Why are you acting so nuts? -Well, maybe I'm not perfect. +
Maybe I don't fit into your perfect, you know, life, +
with your perfect apartment, and your perfect pay-per-view fight. +
Maybe I should leave. +
I stood there and waited for the obligatory, +
he's coming to stop me ten seconds. +
He didn't. +
By the time I got home +
I was sure he'd left an apology on my voicemail. +
[beeping, recording] You have no new messages in your mailbox. +
I didn't sleep very well that night. +
But I wasn't the only one. +
After a night of spiritual reading with her hunky guru, +
Samantha began to feel things +
she hadn't felt in a very long time, +
frustrated and horny. +
She decided it was time to put an end to her suffering. +
But just as she reached the place +
Krishna once called "the gateway to life," +
she turned back and decided not to enter. +
After all, she'd come this far. +
She could continue not to cum at all. +
In an effort to get her mind off sex, +
Miranda had rented a five-hour Danish documentary +
on the Nuremberg trial. +
It actually worked until... +
Hey, gorgeous. +
Why don't you quick drop this, huh? +
Hey, she's thinking about it. +
Where you going so fast? +
I got what you want. +
I got what you need! +
Like every woman +
consumed with a relationship problem, +
I needed a project to keep my mind from obsessing +
and my hands from dialing his number. +
Three months and one week. +
Miranda needed to keep her hands busy as well. +
Did he call? +
Nope. +
And it's been two days. +
Nice color. +
Ecru? +
Egg Shell . +
Well, I think it's over. +
I should never have farted. +
Jesus, Carrie. That's it. +
I've heard enough about the fart. +
It's not the fucking fart! +
I know it's not the fucking fart. +
I just, I think I'm in love with him +
and I'm terrified that he's gonna leave me +
because I'm not perfect. +
All right. +
Let's just put the roller down +
and go in the other room and talk, huh? +
The sex has stopped. He hasn't called. +
What if he never calls, and three weeks from now I pick up The New York Times, +
and I read that he's married some perfect little woman +
who never passes gas under his $500 sheets. +
When did you get so obsessed with being perfect? +
I don't know. It's something about him. +
I mean, you should see me around him. +
I'm not like me. +
I'm like "together Carrie." +
You know, I wear little outfits. +
You know, "sexy Carrie" and "casual Carrie." +
Sometimes I catch myself actually posing. +
It's just, it's exhausting. +
Well, then stop! +
Why don't you show him more of this Carrie? She's pretty great. +
Yeah? What if he doesn't like her? +
Miranda? +
Oh, my God! +
Look at them. +
Oh, wow. +
I had no idea they did an afternoon show. +
When a show is good, +
word gets around. +
There we were, +
the '90s' version of Matinee Ladies. +
Who said the theater was dead? +
Samantha, I cannot believe +
that you would give this up on purpose. +
Actually, I hardly miss it. +
How long has it been? +
A hundred years. +
It never goes down, does it? +
Look, it's still... +
-Hard. -Yeah. +
Gummy bear, please. +
Give me the fucking candy. +
Hey, snapping over gummy bears +
might be a sign that celibacy's not for you. +
All I can say is that my big pay off better be worth it. +
Samantha, I don't understand you. +
There are people starving out there and you're fasting. +
Stop complaining. At least you can take care of yourself. +
I'm way beyond that point. +
Besides, I think I've given myself carpal tunnel. +
Oh, sure. It's all fun until you get to know each other. +
Yeah, that move right there? That's what they're famous for. +
It's been an hour. +
How can that guy still be... +
Hard. +
I have got to try this again with Kevin. +
I mean, we really like each other. +
That's got to be stronger than a drug, right? +
I'm warning you ladies, +
if I make it to four months, I'm humping one of you. +
Oh, my God. +
I hate them. +
After the second show, +
each of us went on with our Saturdays. +
Miranda went to get a movie and another pound of gummy bears. +
Hey, hey! It's my sweetheart. +
You're looking good, baby. +
Good enough to eat. +
Hey, where you going, doll? +
I got what you want. +
I got what you need. +
You talking to me? +
Oh, we got a live one boys. +
You got what I want? +
-You got what I need? -Uh-huh. +
Well, what I want is to get laid. +
What I need is to get laid. +
I need to get laid. +
Take it easy, lady. I'm married. +
All talk and no action, huh? +
What a gavone! +
Yeah, she's something else when she's teed off. +
Samantha decided to channel her frustration at yoga. +
Good, now release and breathe. +
Unless you're planning to move those hands down, +
get them off me. +
Exhale, chaturanga dandasana... +
She had reached the end of her path and her patience. +
Psst. +
Want to fuck? +
What? +
Want to fuck? +
Yeah. +
Samantha spent the rest of the afternoon +
having multiple yogasms. +
Later that night, Charlotte was determined to prove +
she was stronger than selective serotonin re-uptake inhibitors. +
Isn't your arm getting tired? +
No, I think it's starting to work. +
Charlotte... it's not. +
and I'm beginning to chafe. +
Oh. +
-You okay? -Yeah. +
I've just never been in this situation before. +
Do you think you'll ever... +
Never mind. +
What, think I'll ever go off it? +
Yeah. +
Nope. +
Not even for me? +
Nope. +
Oh, come on. Wouldn't you rather be with a guy who's kind and giving +
and not that interested in sex, +
than an unstable, oversexed, prick, +
who only wants to get laid? +
Nope. +
Once Charlotte realized she couldn't get +
what she thought she didn't want, +
she couldn't imagine going on without it. +
Saturday night's dinner came and went with no call from Big. +
My life was suddenly shit, +
but my cabinets were looking fabulous. +
Who is it? +
Me. +
Surprise. +
Yeah. +
Wow. +
What's all this? +
I'm painting. +
I can see that. +
Why didn't you call? +
So this is where you live. +
About time you invited me up. +
I didn't invite you. +
I know. +
It's nice. +
Very nice. +
No, it's not. It's a mess. +
The floors need to be stripped and the curtains are... +
It's... +
I want to change a lot of it. +
I don't know. +
I like it. +
I like it the way it is. +
What was that all about the other night? +
That was me. +
Having a meltdown. +
Okay. +
Nice paint. +
Egg Shell? +
Yes. +
Mm-hmm. +
Did you know that there's a couple +
humping outside of your window? +
Really? +
Oh, I never noticed. +
All I could think was... +
"Why aren't we having sex?" +
"Is this normal?" +
"What's wrong?" +
"Where are we going?" +
Oh, hell... +
we can do better than that. +
And then he kissed me. +
Odd how normal can sometimes feel so uncomfortable. +
\N“回归现实” +
\N纽约人满脑子想的都和性有关 +
\N有人正在享受性爱 有人想得到﹐有些人却得不到 +
\N难怪纽约是个不夜城 人们根本忙得没时间睡 +
\N但如果你想和某人上床 +
\N有趣的事就来了 +
\N里面好像有坚果 +
\N我们爱坚果 +
\N我和大人物同床共枕几星期后 +
\N我们好像越来越习惯睡在一起 +
\N这种感觉很棒 这是我梦寐以求的相处方式 +
\N-早 -早 +
\N-是你？ -天啊 +
\N-有可能更糟 -闭嘴… +
\N我飞快穿好衣服 +
\N好像是在男生宿舍被抓到一样 +
\N-等一下﹐你要喝杯咖啡？ -不﹐我迟到了 +
\N天啊﹐真是糗死了 +
\N接着一整天我都没打给他 +
\N想让自己忙于工作 但每次一停下来 +
\N那声音就是挥之不去 +
\N隔天我发觉到 自己的行为实在太幼稚了 +
\N所以决定化解僵局 用成熟的方式来解决 +
\N全盘否认 +
\N我看到麦特画廊 要举行哥雅的画作展 +
\N-这星期六你要去吗？ -好 +
\N麻烦帮我再拿点酱？ +
\N没问题 +
\N我们可顺便去看雷诺瓦的画 我好喜欢雷诺瓦 +
\N好 +
\N这就是每段恋情 从浪漫转为现实的时刻 +
\N你知道吗？我累惨了 +
\N-我们今晚休息﹐好吗？ -好 +
\N-对不起﹐晚安 -晚安 +
\N这是我们第一次睡在一起 却没做爱 +
\N到下星期﹐已经连续发生三次 我开始担心起来 +
\N三次？试试三个月吧 +
\N-不会吧？ -没错 +
\N到了三个月时 你脸上就不会有这种恐惧表情 +
\N抱歉﹐我只是… 不知道﹐到底怎么回事？ +
\N你只是没有做爱 而我却可怜到只能去租录影带 +
\N累积的金额已可以得到 很多免费的ＱＱ糖 +
\N-放轻松﹐这只是一阵子 -真不敢相信你会这么讲 +
\N三次你就大惊小怪 而我说的是三个月 +
\N那不一样 +
\N有男朋友却没做爱 比没有男朋友做爱还更严重 +
\N你到底担心什么？ +
\N你不是说一切都很顺利 感觉很棒？ +
\N-对﹐可能是太顺利了 -什么意思？ +
\N我放屁了 +
\N-在我男朋友面前放屁 -然后呢？ +
\N接着我们就不做爱了 他可能把我当成哥儿们 +
\N接着我要搬到另一个城市去 确定这个耻辱不会永远跟着我 +
\N-你是人﹐当然会放屁 -但不想被他知道 +
\N我是说﹐他是个完美的人 有间完美的房子 +
\N穿着完美入时的服装 一切就是太完美… +
\N而我却是个会放屁的女人 难怪我们不能做爱 +
\N你哪根筋不对了？三次而已 这相当正常 +
\N谁说的？ +
\N谁说不做爱… 那么以后怎么办？ +
\N睡在一起却不做爱 这很正常吗？ +
\N-那得看你对正常的定义 -天啊﹐真是讨厌 +
\N我又不是情场老手 我怎会知道什么才算正常？ +
\N我又没有身经百战的恋爱史 根本无从得知 +
\N对我来说﹐三个月算不正常 +
\N一个月时还蛮有趣的 两个月就开始麻木 +
\N三个月﹐我可能快疯了 +
\N纽约有130万单身男性 180万单身女性 +
\N总共超过300万的单身人口 +
\N却有12%的人 觉得没得到足够的性爱 +
\N究竟多久做一次才算是正常？ +
\N我一天得手淫三次 才能解决需求 +
\N有些人是咖啡休息时间 我则是手淫休息时间 +
\N有人说33岁的女性 平均一星期要做3.5次 +
\N我很想知道她是谁 +
\N从孩子出生后 我和老婆就没再做过爱 +
\N明年秋天时 小孩就要申请进入耶鲁大学 +
\N平均一天一次 但特殊的日子﹐则一天两次 +
\N所谓“正常”就是 理想与现实的中间点 +
\N就算在这混沌状况下 莎曼珊的性爱解析仍值得信赖 +
\N-好﹐换成狗吠式 -呜 +
\N如果是他 我可以不眠不休大战一场 +
\N如果大人物和我一起睡 却不做爱 +
\N你觉得这代表什么？ +
\N-说实话？ -我不是一向都听实话？ +
\N-好﹐说吧 -我觉得麻烦大了 +
\N做爱是检验彼此关系的气压计 +
\N我本来不打算说﹐但… +
\N-我放屁 -把那垫子拿走 +
\N我不是说现在 我在大人物面前放屁 +
\N-天大的错误 -真的？ +
\N-又不是我能控制﹐我是个人 -不﹐你是个女人 +
\N男人不喜欢女人像个人类 +
\N不能放屁﹐灌洗﹐或用棉条 甚至不能有毛的地方就不该有 +
\N有个家伙因为我没抹防晒蜡 和我分手 +
\N我知道 这是我们两人关系的转捩点 +
\N-我一定挽救不了了 -可以 +
\N只要和他大战个几回合后 他就什么都忘了 +
\N男人没那么复杂 他们就像机器一样 +
\N集中注意力﹐内心平静 +
\N-他在说我 -背部卷缩 +
\N朝天姿势 让呼吸在身体内流窜 +
\N吸气与吐气 +
\N吸气 +
\N吐气 +
\N你想去喝杯咖啡？ +
\N45分钟做了三种动物姿势后 +
\N莎曼珊和西达沙 坐在健康食物餐厅内 +
\N一起啜饮绿茶﹐吃着豆制品 +
\N我每次做完瑜珈后 就觉得精神奕奕 +
\N通体舒畅﹐充满活力 准备蓄势待发 +
\N-莎曼珊 -什么？ +
\N我是独身主义者 必须遵守宗教禁欲 +
\N-我三年前就放弃性爱 -天啊﹐为什么？ +
\N再说一次﹐为什么？ 你不喜欢？ +
\N我爱死了 以前无时无刻都可以做爱 +
\N有时一天和三个女人做 但仍是欲求不满 +
\N-那么你现在对自己太残忍了 -这才是纯粹的自我 +
\N我现在的感觉比做爱还棒 +
\N拜托﹐任何事都比不上做爱 +
\N想想看﹐很棒的前戏 +
\N开始激发体内的性能量… +
\N现在想像 储存了三年的前戏能量 +
\N充沛的性能量在体内运行 +
\N但没有加以释放 +
\N只是循环﹐累积﹐提升… +
\N直到体内的性能量充满全身… +
\N我家就在街角 +
\N但比做爱更棒的就是… 不做爱 +
\N真不可思议 +
\N西达沙满口性事却不行动 +
\N这是几个月来最让莎曼珊 感到兴奋的性变态行为 +
\N隔天我和夏绿蒂晚餐时 +
\N我已经濒临疯狂边缘 满脑子想的都是大人物 +
\N第一次﹐他太累 接着两次则是… +
\N我不知道…很惨吧？ +
\N别紧张﹐你们两人的关系很好 +
\N-但事情并非这样 -怎么了？ +
\N我根本没办法告诉她真相 我怕她听了后﹐会突然变聋 +
\N抱歉﹐你说什么？ +
\N人们老是把性爱看得太重了 +
\N这并不是感情中最重要的事 +
\N-对 -就拿我和凯文来说 +
\N我们已经交往一个月了 却还没发生关系 +
\N但我们会抚摸拥抱 他真是太棒了 +
\N他喜欢他充分尊重我 这段关系与众不同﹐他来了 +
\N和好友的男朋友第一次见面 总会有点不自在 +
\N如果你不喜欢他？ 或者他不喜欢你呢？ +
\N凯文﹐这是好友﹐凯莉 +
\N-你好﹐凯莉 -你好 +
\N如果你已经和他上过床了？ +
\N-你们认识？ -算是吧 +
\N-我们约过会 -对﹐算是约会 +
\N你们两个约会过？真是巧 +
\N是办公室打来的﹐我得接电话 我马上回来 +
\N-说吧﹐什么时候？ -三年前 +
\N三年前﹐这我能接受 +
\N-是认真的？ -不是 +
\N很好﹐为何分手？ +
\N我们分隔两地﹐但我… +
\N凯莉﹐没时间客套了 直接说吧 +
\N他“做爱成性” +
\N而当夏绿蒂发现到 +
\N凯文为了她 而强压住自己的性欲时 +
\N她决定采取主动攻势 +
\N我希望你知道 我对你的耐心很感动 +
\N你对我这么有耐心 足以证明你很在乎我 +
\N长期的耐心等待 使得我们的关系更具意义 +
\N停一个地方就好﹐谢谢 +
\N-这样不行 -是我的原因？ +
\N不﹐你很棒 只是我没那么有性趣 +
\N是我的原因﹐我知道 +
\N凯莉说你性欲很强 她甚至说你“做爱成性” +
\N那是以前 +
\N-什么以前？ -服药以前 +
\N我以前的生活一团糟 情绪不稳﹐药物是我的救星 +
\N但唯一的副作用 是让我变成泄气的轮胎 +
\N经过一阵子后 就成了变形的太妃糖 +
\N-没关系﹐别担心 -我不会 +
\N我或许该说这种感觉很糟 但老实说… +
\N我不会觉得沮丧 +
\N你想看影片吗？ +
\N不敢打电话给大人物的情况 +
\N已转变成精神性失眠症 +
\N我在房里来回踱步 试着不去想我们不做爱… +
\N但当我看到新搬来的芳邻 却肆无忌惮地疯狂做爱时… +
\N这对情侣显然已到忘我的境界 而我唯一能做的就是… +
\N欣赏 +
\N突然间美好的事发生了 欲望克服了恐惧 +
\N是我﹐我现在可以过去吗？ +
\N好 +
\N同时在西三街的极乐世界里 +
\N西达沙正在帮助莎曼珊 发现体内的新大陆 +
\N把所有的气集中在体内 与身体合而为一 +
\N-你有反应 -我知道 +
\N世人对事物的执着与迷恋 是依赖且不健康的 +
\N将会阻碍内在心灵的追求 +
\N还是有反应 +
\N-会消退的 -我也可以 +
\N我以性感迷人的姿态出现 +
\N穿着我的秘密武器 那件紧贴着臀部的裙子 +
\N我已蓄势待发﹐准备上阵 +
\N很漂亮﹐进来吧 我正在看拳击 +
\N亲爱的 +
\N凯莉﹐拜托﹐我想看电视 +
\N加油 +
\N拜托﹐停下来﹐我想看拳击 +
\N好﹐我走 +
\N怎么了？你为何这么奇怪？ +
\N我可能不够完美 可能配不上你完美无缺的生活 +
\N完美的房子 和事先预录的拳击赛 +
\N我还是走好了 +
\N我站在门外﹐给他个机会 +
\N希望他十秒内会出来拉住我 +
\N但他没有 +
\N回到家时 觉得他应该会打电话来道歉 +
\N你的语音信箱没有新留言 +
\N那晚我没睡好 但我不是唯一失眠的人 +
\N莎曼珊彻夜阅读 精神导师建议的书籍后 +
\N她开始重获 长久以来失去的感觉 +
\N情欲难耐 +
\N于是她决定要终止这种折磨 +
\N但当她快到达 西达沙所称的生命之门时 +
\N她突然决定收手 +
\N毕竟她已忍了这么久 她可决定要不要继续？ +
\N为了消除脑中做爱的念头 +
\N米兰达租了五小时的影片 在纽伦堡审讯的丹麦记录片 +
\N-效果还不错﹐直到… -美女 +
\N一起玩玩吧﹐她在考虑了 +
\N这么急要去哪？ 我有你想要的﹐有你需要的 +
\N就像每个女人 遇到棘手的感情问题时一样 +
\N我需要找点事 让自己别再胡思乱想 +
\N控制双手别去拨电话号码 +
\N三个月又一星期了 +
\N米兰达也需要让自己的手忙着 +
\N-他打来没？ -没有 +
\N-已经两天了 -颜色很不错 +
\N-米色？ -淡黄褐色 +
\N我想我们完了 我不应该放屁的 +
\N天啊﹐够了 别再怪到放屁这件事上了 +
\N我知道不是放屁的原因 +
\N我觉得自己深爱着他 +
\N却又害怕 他会因我不够完美而离开我 +
\N好吧﹐把滚筒放下 到其他房间好好谈 +
\N没有做爱﹐他也没打来 +
\N如果他一直不打来 而几星期后我在纽约时报上 +
\N却看到他娶个 从来不会放屁的完美女人呢？ +
\N-你何时起这么在意完美？ -不知道﹐是他的原因 +
\N你该看看我在他面前的样子 根本不像我﹐只像他的附属品 +
\N穿着轻薄紧身的服装 性感的凯莉﹐随性的凯莉 +
\N我常得伪装自己 搞得自己很累 +
\N那就别再装了 让他看看真实凯莉﹐很迷人的 +
\N如果他不喜欢呢？米兰达 +
\N天啊 +
\N看 +
\N天啊 我不知道他们也有下午场 +
\N如果有精彩好戏 就得通告亲朋好友 +
\N大家全员到齐 九十年代的剧院仕女 +
\N谁说剧场已死？ +
\N莎曼珊 真不敢相信你会放弃这种事 +
\N-我根本不会怀念 -多久了？ +
\N-不记得了 -一直坚挺？ +
\N-看﹐还是… -坚挺 +
\N麻烦给我ＱＱ糖 +
\N快给我 +
\N看你大吃ＱＱ糖的样子 禁欲应该不适合你 +
\N-一切等待会有所回报的 -莎曼珊﹐真搞不懂你 +
\N对面的人好像永远欲求不满时 而你却在禁欲 +
\N别抱怨了 至少你可以自己解决 +
\N我那地方已使用过度了 +
\N当然﹐得须相互配合才有乐趣 +
\N那姿势是他们的招牌动作 +
\N已经一小时了 他怎么还能保持… +
\N坚挺 +
\N我一定要和凯文试试 +
\N我们都喜欢对方 爱的力量应该比药物强吧？ +
\N我可警告你们 若我四个月没做爱﹐得小心了 +
\N-天啊 -我讨厌他们 +
\N欣赏过性爱秀之后 我们决定好好利用周末假期 +
\N米兰达又去租片子 还拿到免费的ＱＱ糖 +
\N宝贝﹐你看来秀色可餐 +
\N你要去哪儿？美女 我有你想要的﹐有你需要的 +
\N-你和我说话？ -我们对上话了﹐各位 +
\N你有我想要的？ 你有我需要的？ +
\N我想做爱﹐我需要做爱… +
\N-别激动﹐我结婚了 -只说不做﹐没用的家伙 +
\N对﹐她有种 +
\N莎曼珊决定练瑜珈来解决问题 +
\N放松﹐呼吸 +
\N除非你的手要向下移 否则现在就拿开 +
\N吐气… +
\N当她到达生命之门时 耐心也用尽了 +
\N想做吗？ +
\N想做爱吗？ +
\N好 +
\N接下来的几个下午 莎曼珊都在修练性爱术 +
\N那一晚夏绿蒂下定决心 +
\N要证明自己 比血清促进素抑制剂更有效 +
\N-你的手不酸吗？ -不会﹐应该快有反应了 +
\N夏绿蒂﹐我开始觉得有点痛 +
\N-你还好吧？ -还好 +
\N我只是以前没遇过这种情况 +
\N你觉得你会… +
\N-算了 -什么？会不会重振雄风？ +
\N-对 -不会 +
\N-也不会为我而兴奋？ -不会 +
\N一个亲切体贴 +
\N但对性不感兴趣的男人 +
\N应该比满脑子只想做爱 而欲求不满的男人好吧？ +
\N不对 +
\N当夏绿蒂知道 她无法获得满足时 +
\N她觉得这段关系 已无继续下去的理由 +
\N整个周末夜 大人物都没打电话来 +
\N我生活陷入灰暗期 但我的柜子却是亮丽无比 +
\N-谁？ -是我 +
\N-给你个惊喜 -是啊 +
\N-这是做什么？ -在粉刷 +
\N-我看得出来 -你怎么不打电话？ +
\N你怎么不打？ +
\N所以这就是你住的地方 +
\N-也该是请我来的时候了 -我没请你来 +
\N我知道 +
\N不错﹐很漂亮 +
\N不﹐一团糟 +
\N地板要重换﹐窗帘… +
\N可能要来个大整修 +
\N不知道 +
\N我喜欢 +
\N我喜欢房子的装潢陈设 那一晚是怎么了？ +
\N是我的原因﹐心情不好 +
\N好吧 +
\N-粉刷得不错﹐淡黄褐色？ -对 +
\N你知道窗户外 有对情侣疯狂做爱？ +
\N是吗？我没注意到 +
\N现在我脑海中想的全是 为何我们不做爱？ +
\N这样正常吗？出了什么问题？ 我们怎么了？ +
\N我们可以赢过他们 +
\N接下来﹐他吻了我 +
\N真是奇怪 正常有时候反而令人不自在 +
