
= 001  American Government and Civic Engagement 美国政府与公民参与
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




In the United States, the right to vote is an important feature 特征；特点 of the nation’s system 体系；系统 of government, and over the years /many people have fought and sacrificed 牺牲；献出 to obtain 获得；得到 it. Today, many people ignore 忽视；忽略 this important means 方式；方法 of _civic 公民的；市民的 engagement_ (n.) 参与；介入, while others are prevented 阻止；阻碍 from taking part 参与；参加. For example, in the November, 2024 U.S. election 选举；推选, only 64 percent of the voting-eligible 有投票资格的 population 人口；居民 registered (v.) 登记；注册 to vote, and 84 percent of those _registered (a.) voters_ 选民 participated (v.) 参加；参与.

[.my2]
在美国，投票权是国家政体的重要组成部分，多年来，许多人为之奋斗和牺牲。如今，许多人忽视了这一重要的"公民参与"途径，而另一些人则被剥夺了投票权。例如，在 2024 年 11 月的美国大选中，只有 64% 的符合投票资格的人口进行了选民登记，而登记选民中只有 84% 参与了投票。



Since its founding （组织、公司、学校等的）创建，创办, the United States has relied on citizen participation 参与；参加 to govern 统治；管理；治理 /at the local, state, and national levels 水平；级别. This civic (a.) 公民的；市民的 engagement 参与；介入 ensures (v.) 确保；保证 that _representative (a.) 由代表组成的，代议制的 democracy_ 民主制度；民主政体 will continue to flourish (v.) 繁荣；兴旺；蓬勃发展 and that people will continue to influence (v.) 影响；对…起作用 government. `主` The right 权利；权益 of citizens to participate (v.) in government `系` is an important feature 特征；特点；特色 of democracy, and over the centuries 世纪；百年 many have fought (v.) 斗争；奋斗 to acquire 获得；取得 and defend 保卫；捍卫 this right.

During the American Revolution 革命 (1775–1783), British colonists 殖民地居民；殖民者 fought for the right to govern themselves. In the early nineteenth century, agitated 焦虑不安的；激动的 citizens *called for* 要求，需要 the removal 废除；取消 of property 财产；资产 requirements 规定；要求 for voting 投票；选举 /so poor White men could participate (v.) in government /just as wealthy 富有的；有钱的 men could. Throughout 自始至终，贯穿整个时期 the late nineteenth and twentieth centuries, women, African Americans, Native Americans, and many other groups 群体；团体 fought (v.)  for the right to vote  and hold office 职位；公职.

[.my2]
**自建国以来，美国一直依靠"公民参与"来治理地方、州和国家各级政府(即"公民社会")。这种公民参与确保了"代议制民主"的持续繁荣，也确保了人民能够继续影响政府。##公民参与政府的权利,是民主的重要特征，##几个世纪以来，许多人为争取和捍卫这项权利而奋斗。**在美国独立战争（1775-1783）期间，英国殖民者为争取"自治权"而战。19世纪初，激进的公民, 呼吁取消投票的财产限制，以便贫困的白人男性也能像富裕的男性一样参与政府事务。在19世纪末和20世纪，妇女、非裔美国人、美洲原住民, 以及##**许多其他群体, 为争取"投票权"和"担任公职"的权利而斗争(即这才是真正的"人民当家做主")。**##


The purpose of voting 投票 and other forms of political 政治的 engagement 参与；介入 `系` is to ensure 确保 that /government 政府 serves (v.) 服务 the people, and *not the other way around* (反过来；相反地)而不是反过来. But what does government do /to serve the people? What _different forms of government_ exist 存在? How do they differ (v.) 不同；有区别? How can citizens 公民 best *engage (v.) with* （使）衔接，啮合;与…建立密切关系；尽力理解 and *participate in* 参与；参加 the crucial 至关重要的；关键性的 process 过程 of governing (v.) 统治；管理 the nation 国家? This chapter 章节 seeks (v.) to 试图；设法 answer 回答 these questions.

[.my2]
##**"投票"和"其他政治参与形式"的目的, 是确保"政府为人民服务"，而不是"人民为政府服务"。**##但是，政府究竟如何为人民服务？存在哪些不同的政府形式？它们之间有何区别？公民如何才能更好地参与到"国家治理"这一关键进程中？本章旨在解答这些问题。



'''

== pure

Figure 1.1 In the United States, the right to vote is an important feature of the nation’s system of government, and over the years many people have fought and sacrificed to obtain it. Today, many people ignore this important means of civic engagement, while others are prevented from taking part. For example, in the November, 2024 U.S. election, only 64 percent of the voting-eligible population registered to vote, and 84 percent of those registered voters participated. (credit: modification of work by the National Archives and Records Administration)

Chapter Outline

Since its founding, the United States has relied on citizen participation to govern at the local, state, and national levels. This civic engagement ensures that representative democracy will continue to flourish and that people will continue to influence government. The right of citizens to participate in government is an important feature of democracy, and over the centuries many have fought to acquire and defend this right. During the American Revolution (1775–1783), British colonists fought for the right to govern themselves. In the early nineteenth century, agitated citizens called for the removal of property requirements for voting so poor White men could participate in government just as wealthy men could. Throughout the late nineteenth and twentieth centuries, women, African Americans, Native Americans, and many other groups fought for the right to vote and hold office.

The poster shown above (Figure 1.1), created during World War II, depicts voting as an important part of the fight to keep the United States free. The purpose of voting and other forms of political engagement is to ensure that government serves the people, and not the other way around. But what does government do to serve the people? What different forms of government exist? How do they differ? How can citizens best engage with and participate in the crucial process of governing the nation? This chapter seeks to answer these questions.


'''
