
= 002 The Constitution and Its Origins  宪法及其起源
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


The U.S. Constitution, see Figure 2.1, is one of the world’s most enduring symbols of democracy. It is also the oldest, and shortest, written constitutions of the modern era still in existence. Its writing was by no means inevitable, however. In many ways, the Constitution was both the culmination of American (and British) political thought about government power and a blueprint for the future.

[.my2]
美国宪法 （见图 2.1 ）是世界上最经久不衰的民主象征之一。它也是现存最古老、篇幅最短的现代成文宪法。然而，它的制定并非必然。在许多方面，宪法既是美国（以及英国）关于"政府权力"的政治思想的集大成者，也是未来的蓝图。

It is tempting to think of the framers of the Constitution as a group of like-minded men aligned in their lofty thinking regarding rights and freedoms. This assumption makes it hard to oppose constitutional principles in modern-day politics because people admire the longevity of the Constitution and like to consider its ideals above petty partisan politics. However, the Constitution was designed largely out of necessity following the failure of the first revolutionary government, and it featured a series of pragmatic compromises among its disparate stakeholders. It is therefore quite appropriate that more than 225 years later the U.S. government still requires compromise to function properly.

[.my2]
**人们很容易将宪法的制定者, 视为一群志同道合、在权利和自由方面拥有崇高理想的人。**这种假设使得在现代政治中很难反对宪法原则，因为人们钦佩宪法的持久性，并乐于将其理想, 置于琐碎的党派政治之上。#*然而，宪法的制定很大程度上是在第一届革命政府失败后出于无奈之举，它包含了各方利益相关者之间一系列务实的妥协。因此，225 多年后的今天，美国政府仍然需要妥协才能正常运作，这完全合情合理。*#

How did the Constitution come to be written? What compromises were needed to ensure the ratification that made it into law? This chapter addresses these questions and also describes why the Constitution remains a living, changing document.

[.my2]
**宪法是如何制定出来的？#为了确保其获得批准, 并最终成为法律，需要做出哪些妥协？#**本章将探讨这些问题，并阐述宪法为何至今仍是一部鲜活的、不断变化的法律文件。





'''

== pure

Figure 2.1 Written in 1787 and amended twenty-seven times, the U.S. Constitution is a living document that has served as the basis for U.S. government for more than two hundred years. (credit: modification of work by National Archives and Records Administration)

Chapter Outline

- 2.1 The Pre-Revolutionary Period and the Roots of the American Political Tradition
- 2.2 The Articles of Confederation
- 2.3 The Development of the Constitution
- 2.4 The Ratification of the Constitution
- 2.5 Constitutional Change

The U.S. Constitution, see Figure 2.1, is one of the world’s most enduring symbols of democracy. It is also the oldest, and shortest, written constitutions of the modern era still in existence. Its writing was by no means inevitable, however. In many ways, the Constitution was both the culmination of American (and British) political thought about government power and a blueprint for the future.

It is tempting to think of the framers of the Constitution as a group of like-minded men aligned in their lofty thinking regarding rights and freedoms. This assumption makes it hard to oppose constitutional principles in modern-day politics because people admire the longevity of the Constitution and like to consider its ideals above petty partisan politics. However, the Constitution was designed largely out of necessity following the failure of the first revolutionary government, and it featured a series of pragmatic compromises among its disparate stakeholders. It is therefore quite appropriate that more than 225 years later the U.S. government still requires compromise to function properly.

How did the Constitution come to be written? What compromises were needed to ensure the ratification that made it into law? This chapter addresses these questions and also describes why the Constitution remains a living, changing document.

'''