
= 002-2 The Articles of Confederation 邦联条例本
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义



Waging a successful war against Great Britain required that the individual colonies, now sovereign states that often distrusted one another, form a unified nation with a central government capable of directing the country’s defense. Gaining recognition and aid from foreign nations would also be easier if the new United States had a national government able to borrow money and negotiate treaties. Accordingly, the Second Continental Congress called upon its delegates to create a new government strong enough to win the country’s independence but not so powerful that it would deprive people of the very liberties for which they were fighting.


[.my2]
要成功对抗英国，各个殖民地——如今已是主权国家，彼此之间往往互不信任——必须组成一个统一的国家，拥有一个能够指挥国家防御的中央政府。**如果新生的美国拥有一个能够"借贷"和"谈判条约"的中央政府，那么获得外国的承认和援助, 也会更加容易。**因此，"第二届大陆会议"呼吁其代表建立一个足以赢得国家独立，但又不会强大到剥夺人民为之奋斗的自由的新政府。

=== PUTTING A NEW GOVERNMENT IN PLACE

[.my2]
组建新政府

The final draft of the Articles of Confederation, which formed the basis of the new nation’s government, was accepted by Congress in November 1777 and submitted to the states for ratification. It would not become the law of the land until all thirteen states had approved it. Within two years, all except Maryland had done so. Maryland argued that all territory west of the Appalachians, to which some states had laid claim, should instead be held by the national government as public land for the benefit of all the states. When the last of these states, Virginia, relinquished its land claims in early 1781, Maryland approved the Articles.4 A few months later, the British surrendered.

[.my2]
**构成新国家政府基础的 《邦联条例》 最终草案, 于 1777 年 11 月获得国会通过，并提交各州批准。该条例必须得到全部十三个州的批准, 才能成为国家法律。**两年内，除马里兰州外，其余各州均已批准。马里兰州主张，阿巴拉契亚山脉以西的所有领土（一些州曾声称拥有这些领土的主权）, 应由联邦政府作为"公共土地"持有，造福所有州。1781 年初，最后一个提出领土主张的州——弗吉尼亚州——放弃了其领土主张，马里兰州随后批准了《邦联条例》。 几个月后，英国投降。

Americans wished their new government to be a republic, a regime in which the people, not a monarch, held power and elected representatives to govern according to the rule of law. Many, however, feared that a nation as large as the United States could not be ruled effectively as a republic. Many also worried that even a government of representatives elected by the people might become too powerful and overbearing. Thus, a confederation was created—an entity in which independent, self-governing states form a union for the purpose of acting together in areas such as defense. Fearful of replacing one oppressive national government with another, however, the framers of the Articles of Confederation created an alliance of sovereign states held together by a weak central government.

[.my2]
美国人希望他们的新政府是一个共和国 ，一个由人民而非君主掌握权力，并"选举代表,依法治理国家"的政体。然而，许多人担心像美国这样幅员辽阔的国家, 无法有效地实行共和制。**#许多人也担心，即使是人民选举产生的代表政府，也可能变得权力过大、专横跋扈。因此， "邦联"应运而生——一个由独立自治的州,组成的联盟#，**旨在共同应对国防等领域的挑战。然而，*由于担心用一个专制的中央政府取代另一个专制的中央政府，《邦联条例》的制定者们创建了一个由"主权州"组成的联盟，#而维系这些州的, 是一个权力较弱的中央政府。#*

Link to Learning  学习链接
View the Articles of Confederation at the National Archives. The timeline for drafting and ratifying the Articles of Confederation is available at the Library of Congress.


the Articles of Confederation +
https://www.archives.gov/historical-docs?doc=2&title_raw=Articles%20of%20Confederation

[.my2]
您可以在美国国家档案馆查阅 《邦联条例》 。 《邦联条例》的起草和批准时间表, 可在美国国会图书馆查阅。

Following the Declaration of Independence, each of the thirteen states had drafted and ratified a constitution providing for a republican form of government in which political power rested in the hands of the people, although the right to vote was limited to free (White) men, and the property requirements for voting differed among the states. Each state had a governor and an elected legislature. In the new nation, the states remained free to govern their residents as they wished. The central government had authority to act in only a few areas, such as national defense, in which the states were assumed to have a common interest (and would, indeed, have to supply militias). This arrangement was meant to prevent the national government from becoming too powerful or abusing the rights of individual citizens. In the careful balance between power for the national government and liberty for the states, the Articles of Confederation favored the states.

[.my2]
在 《独立宣言》 发表后，十三个州各自起草并批准了一部宪法，规定实行共和政体，政治权力归人民所有。然而，选举权仅限于自由（白人）男性，且各州对"选举权的财产要求"不尽相同。**每个州都设有"州长"和"民选立法机构"。**在这个新生的国家里，**各州可以自由地按照自己的意愿,治理居民。**中央政府的权力仅限于少数领域，例如国防，在这些领域，各州被认为拥有共同利益（而且实际上，**各州必须提供民兵）。这种安排旨在防止联邦政府权力过大, 或滥用公民的个人权利。**在"联邦政府权力"与"各州自由"之间寻求微妙的平衡，《邦联条例》最终倾向于各州。

Thus, powers given to the central government were severely limited. The Confederation Congress, formerly the Continental Congress, had the authority to exchange ambassadors and make treaties with foreign governments and Indian tribes, declare war, coin currency and borrow money, and settle disputes between states. Each state legislature appointed delegates to the Congress; these men could be recalled at any time. Regardless of its size or the number of delegates it chose to send, each state would have only one vote. Delegates could serve for no more than three consecutive years, lest a class of elite professional politicians develop. The nation would have no independent chief executive or judiciary. Nine votes were required before the central government could act, and the Articles of Confederation could be changed only by unanimous approval of all thirteen states.

[.my2]
因此，中央政府的权力受到严格限制。 邦联大会 （前身为大陆会议 ）有权与外国政府和印第安部落互派大使、缔结条约、宣战、铸造货币和借贷，以及解决各州之间的争端。各州议会任命代表,参加邦联大会；这些代表随时可能被召回。无论各州规模大小, 或派出的代表人数多少，每个州都只有一票。##**代表的任期不得超过三年，以免形成精英职业政客阶层。**##国家没有独立的行政首脑,或司法机构。中央政府的行动需要九票才能通过，而《邦联条例》的修改, 也必须获得所有十三个州的一致同意。

=== WHAT WENT WRONG WITH THE ARTICLES?

[.my2]
这些文章到底出了什么问题？


The Articles of Confederation satisfied the desire of those in the new nation who wanted a weak central government with limited power. Ironically, however, their very success led to their undoing. It soon became apparent that, while they protected the sovereignty of the states, the Articles had created a central government too weak to function effectively.

[.my2]
《邦联条例》满足了新生国家中那些渴望建立一个"权力有限的弱势中央政府"的人们的愿望。然而，具有讽刺意味的是，正是它的成功, 最终导致了自身的覆灭。*人们很快意识到，尽管《邦联条例》保护了各州的主权，但它所建立的中央政府却过于软弱，无法有效运作。*

One of the biggest problems was that the national government had no power to impose taxes. To avoid any perception of “taxation without representation,” the Articles of Confederation allowed only state governments to levy taxes. To pay for its expenses, the national government had to request money from the states, which were required to provide funds in proportion to the value of the land within their borders. The states, however, were often negligent in this duty, and the national government was underfunded. Without money, it could not pay debts owed from the Revolution and had trouble conducting foreign affairs. For example, the inability of the U.S. government to raise sufficient funds to compensate colonists who had remained loyal to Great Britain for their property losses during and after the American Revolution was one of the reasons the British refused to evacuate the land west of the Appalachians. The new nation was also unable to protect American ships from attacks by the Barbary pirates.5 Foreign governments were also, understandably, reluctant to loan money to a nation that might never repay it because it lacked the ability to tax its citizens.

[.my2]
**最大的问题之一是联邦政府没有征税权。为了避免“无代表权不纳税”的印象，《邦联条例》规定只有州政府才有权征税。为了支付开支，联邦政府必须向各州请求拨款，**各州则需按其境内土地价值的比例, 提供资金。然而，各州常常疏于履行这项义务，导致联邦政府资金不足。**没有资金，联邦政府就无法偿还"独立战争"期间的债务，也难以处理外交事务。**例如，美国政府无力筹集足够的资金, 来补偿那些在独立战争期间及之后, 仍效忠英国的殖民地居民的财产损失，这正是英国拒绝撤出阿巴拉契亚山脉以西地区的原因之一。这个新生的国家也无法保护美国船只免受巴巴里海盗的袭击。 此外， **外国政府也不愿向一个可能永远无法偿还贷款的国家提供贷款，因为该国缺乏向其公民征税的能力，**这也不难理解。

The fiscal problems of the central government meant that the currency it issued, called the Continental, was largely worthless and people were reluctant to use it. Furthermore, while the Articles of Confederation had given the national government the power to coin money, they had not prohibited the states from doing so as well. As a result, numerous state banks issued their own banknotes, which had the same problems as the Continental. People who were unfamiliar with the reputation of the banks that had issued the banknotes often refused to accept them as currency. This reluctance, together with the overwhelming debts of the states, crippled the young nation’s economy.

[.my2]
##**中央政府的财政困境, 导致其发行的货币——大陆币——几乎一文不值，**##人们不愿使用。此外，**尽管《邦联条例》赋予联邦政府"铸币权"，但并未禁止各州也这样做。结果，许多州立银行发行了自己的纸币，这些纸币也面临着与大陆币同样的问题。**由于不了解发行纸币的银行信誉，人们往往拒绝接受这些纸币。这种拒收行为，加上各州巨额债务，严重拖垮了这个年轻国家的经济。

The country’s economic woes were made worse by the fact that the central government also lacked the power to impose tariffs on foreign imports or regulate interstate commerce. Thus, it was unable to prevent British merchants from flooding the U.S. market with low-priced goods after the Revolution, and American producers suffered from the competition. Compounding the problem, states often imposed tariffs on items produced by other states and otherwise interfered with their neighbors’ trade.

[.my2]
**#由于中央政府无权对外国进口商品征收关税,# **或监管州际贸易，美国的经济困境雪上加霜。因此，##**美国独立战争后，英国商人向美国市场大量倾销低价商品，美国生产商因此遭受重创。**##更糟糕的是，*各州还经常对其他州生产的商品征收关税，并以其他方式干涉邻州的贸易。*

The national government also lacked the power to raise an army or navy. Fears of a standing army in the employ of a tyrannical government had led the writers of the Articles of Confederation to leave defense largely to the states. Although the central government could declare war and agree to peace, it had to depend upon the states to provide soldiers. If state governors chose not to honor the national government’s request, the country would lack an adequate defense. This was quite dangerous at a time when England and Spain still controlled large portions of North America (Table 2.1).

[.my2]
**中央政府也无力组建陆军或海军。由于担心"常备军"落入"暴政政府"之手，《邦联条例》的制定者们, 将国防事务主要交由各州负责。**尽管中央政府可以宣战和媾和，但它必须依赖各州提供士兵。如果各州州长拒绝中央政府的要求，国家将缺乏足够的防御力量。在当时英国和西班牙仍控制着北美大片领土的情况下，这种情况相当危险（ 见表 2.1 ）。

Problems with the Articles of Confederation

[.my2]
《邦联条例》的问题

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|Weakness of the Articles of Confederation +
[.my2]
邦联条例的弱点
|Why Was This a Problem? +
[.my2]
为什么这会是个问题 (这导致了什么结果)？

|The national government could not impose taxes on citizens. It could only request money from the states.

[.my2]
中央政府无权向公民征税，只能向各州请求拨款。
|Requests for money were usually not honored. As a result, the national government did not have money to pay for national defense or fulfill its other responsibilities.


[.my2]
拨款请求通常得不到批准。结果，国家政府没有足够的资金, 来支付国防开支或履行其他职责。

|The national government could not regulate foreign trade or interstate commerce.

[.my2]
国家政府无权监管对外贸易, 或州际贸易。
|The government could not prevent foreign countries from hurting American competitors by shipping inexpensive products to the United States. It could not prevent states from passing laws that interfered with domestic trade.


[.my2]
政府无法阻止"外国通过向美国出口廉价产品, 来损害他们的美国竞争对手的利益"。它也无法阻止"各州通过干预国内贸易的法律"。

|The national government could not raise an army. It had to request the states to send men.

[.my2]
中央政府无力组建军队，只能请求各州派遣兵员。
|State governments could choose not to honor Congress’s request for troops. This would make it hard to defend the nation.


[.my2]
各州政府可以选择不响应国会的增兵请求。这将使保卫国家变得困难。

|Each state had only one vote in Congress regardless of its size.

[.my2]
无论州面积大小，每个州在国会中都只有一票。
|Populous states were less well represented.

[.my2]
人口大州的代表性不足。

|The Articles could not be changed without a unanimous vote to do so.

[.my2]
未经全体一致同意，不得修改宪法条款。

|Problems with the Articles could not be easily fixed.
[.my2]
文章中的问题难以轻易解决。


|There was no national judicial system.
[.my2]
当时没有全国性的司法体系。
|Judiciaries are important enforcers of national government power.

[.my2]
司法机构是国家政府权力的重要执行者。
|===


Table 2.1 The Articles of Confederation suffered from many problems that could not be easily repaired. The biggest problem was the lack of power given to the national government.

[.my2]
表 2.1 《邦联条例》存在许多难以轻易解决的问题。其中最大的问题是中央政府权力不足。



The weaknesses of the Articles of Confederation, already recognized by many, became apparent to all as a result of an uprising of Massachusetts farmers, led by Daniel Shays. Known as Shays’ Rebellion, the incident panicked the governor of Massachusetts, who called upon the national government for assistance. However, with no power to raise an army, the government had no troops at its disposal. After several months, Massachusetts crushed the uprising with the help of local militias and privately funded armies, but wealthy people were frightened by this display of unrest on the part of poor men and by similar incidents taking place in other states.6 To find a solution and resolve problems related to commerce, members of Congress called for a revision of the Articles of Confederation.

[.my2]
邦联条例的缺陷, 早已被许多人所认识，而丹尼尔 ·谢伊斯领导的马萨诸塞州农民起义, 更是让所有人彻底明白了这一点。**这场被称为 “谢伊斯叛乱” 的事件, 令马萨诸塞州州长惊慌失措，他请求联邦政府援助。然而，由于联邦政府无权征兵，因此无法调动军队。**几个月后，马萨诸塞州在"地方民兵"和"私人资助军队"的帮助下, 镇压了叛乱 ，但**富人们却对穷人的这种不安情绪, 以及其他州发生的类似事件感到恐惧。为了找到解决办法, **并解决与商业相关的问题，*国会议员呼吁修订"邦联条例"。*

Milestone


[.my2]
里程碑

Shays’ Rebellion: Symbol of Disorder and Impetus to Act
[.my2]
谢斯起义：混乱的象征和行动的动力

In the summer of 1786, farmers in western Massachusetts were heavily in debt, facing imprisonment and the loss of their lands. They owed taxes that had gone unpaid while they were away fighting the British during the Revolution. The Continental Congress had promised to pay them for their service, but the national government did not have sufficient money. Moreover, the farmers were unable to meet the onerous new tax burden Massachusetts imposed in order to pay its own debts from the Revolution.

[.my2]
1786年夏天，*马萨诸塞州西部的农民负债累累，面临牢狱之灾和失去土地的危险。他们在独立战争期间远赴战场与英军作战，拖欠了税款。大陆会议曾承诺支付他们的服役报酬，但联邦政府资金不足。此外，马萨诸塞州为了偿还自身在独立战争中欠下的债务，又加重了农民的负担，他们也无力承担。*

Led by Daniel Shays (Figure 2.6), the heavily indebted farmers marched to a local courthouse demanding relief. Faced with the refusal of many Massachusetts militiamen to arrest the rebels, with whom they sympathized, Governor James Bowdoin called upon the national government for aid, but none was available. The uprising was finally brought to an end the following year by a privately funded militia after the protestors’ unsuccessful attempt to raid the Springfield Armory.

[.my2]
**在丹尼尔·谢伊斯（ 图 2.6 ）的带领下，负债累累的农民们游行至当地法院，要求救济。由于许多马萨诸塞州民兵拒绝逮捕他们同情的叛乱者，州长詹姆斯·鲍登向联邦政府求助，但未能获得援助。**次年，在抗议者试图袭击斯普林菲尔德"兵工厂"未果后，一支私人资助的民兵, 最终平息了这场起义。

This 1787 almanac cover shows a drawing of Daniel Shays and Job Shattuck.
Figure 2.6 This contemporary depiction of Continental Army veteran Daniel Shays (left) and Job Shattuck (right), who led an uprising of Massachusetts farmers in 1786–1787 that prompted calls for a stronger national government, appeared on the cover of Bickerstaff’s Genuine Boston Almanack for 1787.

[.my2]
图 2.6 这幅当代画作描绘了大陆军老兵丹尼尔·谢伊斯（左）和乔布·沙塔克（右），他们在 1786-1787 年领导了马萨诸塞州农民的起义，引发了人们对建立更强大的国家政府的呼吁。 这幅画作出现在 1787 年比克斯塔夫的《波士顿正宗年鉴》 的封面上。


Were Shays and his followers justified in their attacks on the government of Massachusetts? What rights might they have sought to protect?

[.my2]
谢斯及其追随者攻击马萨诸塞州政府的行为, 是否正当？他们试图保护哪些权利？




'''