
= 003 American Federalism  美国联邦主义
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义

Federalism figures prominently in the U.S. political system. Specifically, the federal design spelled out in the Constitution divides powers between two levels of government—the states and the federal government—and creates a mechanism for them to check and balance one another. As an institutional design, federalism both safeguards state interests and creates a strong union led by a capable central government. American federalism also seeks to balance the forces of decentralization and centralization. We see decentralization when we cross state lines and encounter different taxation levels, welfare eligibility requirements, and voting regulations. Centralization is apparent in the fact that the federal government is the only entity permitted to print money, to challenge the legality of state laws, or to employ money grants and mandates to shape state actions. Colorful billboards with simple messages may greet us at state borders (Figure 3.1), but behind them lies a complex and evolving federal design that has structured relationships between states and the federal government since the late 1700s.



[.my2]
联邦制在美国政治体系中占据重要地位。具体而言，**宪法中规定的联邦制, 将权力划分在"州政府"和"联邦政府"两个层级之间，并建立了相互制衡的机制。**作为一种制度设计， 联邦制既保障了各州的利益，又建立了一个由高效中央政府领导的强大联盟。**美国联邦制, 还力求平衡"权力分散"和"权力集中"两种力量。**当我们跨越州界时，会发现不同的税收水平、福利资格要求, 和投票规定，这体现了"权力分散"。而"权力集中"则体现在联邦政府是唯一有权印钞、质疑"州法律"合法性, 或"利用财政拨款和指令, 来影响州政府行为"的实体。在州界，我们或许会看到色彩鲜艳、信息简洁的广告牌（ 图 3.1 ），但在这背后，是一个复杂且不断演变的联邦制体系，自 18 世纪末以来，它一直塑造着"各州"与联邦政府之间的关系。

What specific powers and responsibilities are granted to the federal and state governments? How does our process of government keep these separate governing entities in balance? To answer these questions and more, this chapter traces the origins, evolution, and functioning of the American system of federalism, as well as its advantages and disadvantages for citizens.



[.my2]
联邦政府和州政府, 分别拥有哪些具体的权力和责任？我们的政府运作机制, 如何维持这些"独立政府实体"之间的平衡？为了解答这些问题, 以及更多其他问题，本章将追溯美国联邦制体系的起源、演变和运作方式，并探讨其对公民的利弊。


'''

== pure

Figure 3.1 Your first encounter with differences across states may have come from visiting relatives or going on a cross-country trip with your parents during vacation. The distinct postcard images of different states that come to your mind are symbolic of American federalism. (credit: modification of work by Boston Public Library)

Chapter Outline

- 3.1 The Division of Powers
- 3.2 The Evolution of American Federalism
- 3.3 Intergovernmental Relationships
- 3.4 Competitive Federalism Today
- 3.5 Advantages and Disadvantages of Federalism

Federalism figures prominently in the U.S. political system. Specifically, the federal design spelled out in the Constitution divides powers between two levels of government—the states and the federal government—and creates a mechanism for them to check and balance one another. As an institutional design, federalism both safeguards state interests and creates a strong union led by a capable central government. American federalism also seeks to balance the forces of decentralization and centralization. We see decentralization when we cross state lines and encounter different taxation levels, welfare eligibility requirements, and voting regulations. Centralization is apparent in the fact that the federal government is the only entity permitted to print money, to challenge the legality of state laws, or to employ money grants and mandates to shape state actions. Colorful billboards with simple messages may greet us at state borders (Figure 3.1), but behind them lies a complex and evolving federal design that has structured relationships between states and the federal government since the late 1700s.

What specific powers and responsibilities are granted to the federal and state governments? How does our process of government keep these separate governing entities in balance? To answer these questions and more, this chapter traces the origins, evolution, and functioning of the American system of federalism, as well as its advantages and disadvantages for citizens.

'''