
= 002-5 Constitutional Change 宪法变更
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义



The federal design of our Constitution has had a profound effect on U.S. politics. Several positive and negative attributes of federalism have manifested themselves in the U.S. political system.

[.my2]
美国宪法的联邦制设计, 对美国政治产生了深远的影响。联邦制的诸多积极和消极特征, 都在美国政治体系中有所体现。

'''

=== THE BENEFITS OF FEDERALISM

[.my2]
联邦制的益处

Among the merits of federalism are that it promotes policy innovation and political participation and accommodates diversity of opinion. On the subject of policy innovation, Supreme Court Justice Louis Brandeis observed in 1932 that “a single courageous state may, if its citizens choose, serve as a laboratory; and try novel social and economic experiments without risk to the rest of the country.” What Brandeis meant was that states could harness their constitutional authority to engage in policy innovations that might eventually be diffused to other states and at the national level. For example, a number of New Deal breakthroughs, such as child labor laws, were inspired by state policies. Prior to the passage of the Nineteenth Amendment, women already had the right to vote in several states. California has led the way in establishing standards for fuel emissions and other environmental policies (Figure 3.18). Recently, the health insurance exchanges run by Connecticut, Kentucky, Rhode Island, and Washington have served as models for other states seeking to improve the performance of their exchanges.

[.my2]
**联邦制的优点之一, 是它促进政策创新和政治参与，**并包容不同的意见。关于政策创新，最高法院大法官路易斯· 布兰代斯在 1932 年指出，“*一个勇敢的州，如果其公民愿意，可以成为一个实验室；尝试新的社会和经济实验，而不会给国家其他地区带来风险。(即风险不会外溢到其他州. 反之中国这样的大一统国家, 领导人一犯浑, 全国人民就遭殃, 无省市可以例外.)*”  布兰代斯的意思是，各州可以利用其宪法赋予的权力, 进行政策创新，这些创新最终可能会推广到其他州乃至全国。例如，罗斯福新政的一些突破性成果，如童工法，都受到了州政策的启发。在第十九修正案通过之前，一些州已经赋予了妇女投票权。加利福尼亚州在制定燃料排放标准, 和其他环境政策方面, 一直处于领先地位（ 图 3.18 ）。近年来，康涅狄格州、肯塔基州、罗德岛州, 和华盛顿州运营的医疗保险交易平台, 已成为其他州改进其交易平台运作的典范。

Image A shows the Golden Gate bridge with a moderate amount of traffic. Image B shows a sticker on a car that states “Access OK California clean air vehicle”. The sticker has the California state seal.


[.my2]
图 A 展示了车流量适中的金门大桥。图 B 展示了汽车上的一张贴纸，上面写着 “Access OK 加州清洁空气车辆”。这张贴纸上有加州州徽。




Figure   数字 3.18 The California Air Resources Board was established in 1967, before passage of the federal Clean Air Act. The federal Environmental Protection Agency has adopted California emissions standards nationally, starting with the 2016 model year, and is working with California regulators to establish stricter national emissions standards going forward. The Trump Administration revoked California's authority to set higher standards than their lower federal standards; however California challenged this ruling in court. The Biden Administration is expected to reverse the Trump ruling and, in anticipation of this change, fifteen states and the District of Columbia have upped their standards. (credit a: modification of work by Antti T. Nissinen; credit b: modification of work by Marcin Wichary)


[.my2]
加州空气资源委员会, 成立于 1967 年，早于联邦《清洁空气法》的颁布。联邦环境保护署, 已将加州的排放标准, 推广至全国，自 2016 款车型开始实施，并正与加州监管机构合作，制定更严格的全国排放标准。特朗普政府撤销了"加州制定高于联邦标准的排放标准"的权力；然而，加州已就此裁决提起诉讼。预计拜登政府将推翻特朗普的裁决，为应对这一变化，已有 15 个州和哥伦比亚特区, 提高了各自的排放标准 。 （图片 a：改编自 Antti T. Nissinen 的作品；图片 b：改编自 Marcin Wichary 的作品）


Another advantage of federalism is that because our federal system creates two levels of government with the capacity to take action, failure to attain a desired policy goal at one level can be offset by successfully securing the support of elected representatives at another level. Thus, individuals, groups, and social movements are encouraged to actively participate and help shape public policy.

[.my2]
**联邦制的另一个优势在于，由于我们的联邦体制设立了两个层级的政府，都具备采取行动的能力，因此，即使某一层级未能实现预期的政策目标，也可以通过成功争取另一层级"民选代表"的支持, 来弥补。**由此，个人、团体和社会运动都受到鼓励，积极参与并帮助塑造公共政策。

Get Connected!

[.my2]
立即连接！

Federalism and Political Office

[.my2]
联邦制和政治职位

Thinking of running for elected office? Well, you have several options. As Table 3.1 shows, there are a total of 510,682 elected offices at the federal, state, and local levels. Elected representatives in municipal and township governments account for a little more than half the total number of elected officials in the United States. Political careers rarely start at the national level. In fact, a very small share of politicians at the subnational level transition to the national stage as representatives, senators, vice presidents, or presidents.

[.my2]
想竞选公职吗？您有多种选择。如表 3.1 所示，**联邦、州和地方各级共有 510,682 个民选职位。市级和乡镇级政府的民选代表, 约占美国民选官员总数的一半多一点。**政治生涯很少从国家层面开始。事实上，只有极少数地方政治家能够晋升到国家层面，成为众议员、参议员、副总统或总统。

Elected Officials at the Federal, State, and Local Levels

[.my2]
联邦、州和地方各级民选官员



Number of Elective Bodies
选举机构的数量	Number of Elected Officials
当选官员人数
Federal Government  联邦政府	1
Executive branch  行政部门		2
U.S. Senate  美国参议院		100
U.S. House of Representatives
美国众议院		435
State Government  州政府	50
State legislatures  州立法机构		7,382
Statewide offices  全州办事处		1,036
State boards  州委员会		1,331
Local Government  地方政府
County governments  县政府	3,034	58,818
Municipal governments  市政当局	19,429	135,531
Town governments  镇政府	16,504	126,958
School districts  学区	13,506	95,000
Special districts  特殊区域	35,052	84,089
Total  全部的	87,576	510,682
Table 3.1 This table lists the number of elected bodies and elected officials at the federal, state, and local levels.73
表 3.1 本表列出了联邦、州和地方各级民选机构和民选官员的数量 。




If you are interested in serving the public as an elected official, there are more opportunities to do so at the local and state levels than at the national level. As an added incentive for setting your sights at the subnational stage, consider the following. Whereas only 32 percent of U.S. adults trusted Congress in 2023, according to Gallup, about 59 percent trusted their state governments and 57 percent had confidence in their local governments.


[.my2]
如果您有兴趣以"民选官员"的身份为公众服务，那么在地方和州一级, 比在国家一级有更多机会。为了进一步激励您将目光投向地方层面，请考虑以下几点。**根据盖洛普的调查，2023 年只有 32%的美国成年人信任"国会"，而约 59%的人信任"州政府"，57%的人对"地方政府"有信心。 **

If you ran for public office, what problems would you most want to solve? What level of government would best enable you to solve them, and why?

[.my2]
#*如果你竞选公职，你最想解决哪些问题？哪个层级的政府最能帮助你解决这些问题，为什么？*#

The system of checks and balances in our political system often prevents the federal government from imposing uniform policies across the country. As a result, states and local communities have the latitude to address policy issues based on the specific needs and interests of their citizens. The diversity of public viewpoints across states is manifested by differences in the way states handle access to abortion, distribution of alcohol, gun control, and social welfare benefits, for example.

[.my2]
**我们政治体系中的"权力制衡机制", 往往限制了联邦政府在全国范围内推行统一政策。因此，各州和地方社区拥有一定的自主权，**可以根据本州居民的具体需求和利益, 来处理政策问题。*例如，各州在堕胎、酒精销售、枪支管制, 和社会福利等方面的处理方式, 就存在差异，这体现了各州公众观点的多样性。*

'''

=== THE DRAWBACKS OF FEDERALISM


[.my2]
联邦制的弊端


Federalism also comes with drawbacks. Chief among them are economic disparities across states, race-to-the-bottom dynamics (i.e., states compete to attract business by lowering taxes and regulations), and the difficulty of taking action on issues of national importance.

[.my2]
联邦制也存在一些弊端。其中最主要的是各州之间的经济差距、 "竞相降低税收和监管, 以吸引企业"的恶性竞争，以及在国家重要问题上, 难以采取行动。

Stark economic differences across states have a profound effect on the well-being of citizens. For example, in 2023, Massachusetts had the highest median household income ($99,858), while West Virginia had the lowest ($55,948). There are also huge disparities in school funding across states. In 2016, New York spent $33,400 per student for elementary and secondary education, while Idaho spent $9,390. Furthermore, health-care access, costs, and quality vary greatly across states. Proponents of social justice contend that federalism has tended to obstruct national efforts to effectively even out these disparities. When national policy-making is stymied, and policy advocates move to the state level, it takes fifty-one different advocacy efforts to bring about change, compared to one effort were the national government to take the lead.

[.my2]
各州之间巨大的经济差异, 对公民福祉有着深远的影响。例如，2023 年，马萨诸塞州的家庭收入"中位数"最高（99,858 美元），而西弗吉尼亚州最低（55,948 美元）。  各州在学校经费方面也存在巨大差异。2016 年，纽约州"中小学生人均教育支出"为 33,400 美元，而爱达荷州仅为 9,390 美元。  此外，各州的医疗保健服务获取、费用和质量, 也存在显著差异。  社会正义的支持者认为，联邦制往往阻碍了国家层面有效消除这些差距的努力。当国家政策制定受阻，政策倡导者转向州一级时，需要 51 项不同的倡导活动, 才能促成改变，而如果由联邦政府牵头，只需一项活动即可。

Link to Learning

[.my2]
学习链接

The National Education Association discusses the problem of inequality in the educational system of the United States. Visit the Racial & Social Justice page of the NEA website to see how NEA EdJustice is advocating for change in this area.


https://www.openstax.org/l/29equalityedu

[.my2]
美国国家教育协会（NEA）探讨了美国教育体系中的不平等问题。请访问 NEA 网站的“种族与社会正义”页面 ，了解 NEA EdJustice 如何倡导该领域的变革。

The economic strategy of using race-to-the-bottom tactics in order to compete with other states in attracting new business growth also carries a social cost. For example, workers’ safety and pay can suffer as workplace regulations are lifted, and the reduction in payroll taxes for employers has led a number of states to end up with underfunded unemployment insurance programs. As of March 2021, twelve states have also opted not to expand Medicaid, as encouraged by the Patient Protection and Affordable Care Act in 2010, for fear it will raise state public spending and increase employers’ cost of employee benefits, despite provisions that the federal government will pick up nearly all cost of the expansion. More than half of these states are in the South.

[.my2]
为了吸引新企业发展, 而与其他州展开竞争，竞相降低标准的经济策略, 也带来了社会成本。例如，随着工作场所监管的放松，工人的安全和薪酬可能会受到影响；而雇主"工资税"的减少, 导致许多州的"失业保险项目资金"不足。截至 2021 年 3 月，已有 12 个州选择不扩大"医疗补助计划"（Medicaid），尽管 2010 年《患者保护与平价医疗法案》（ Patient Protection and Affordable Care Act）鼓励扩大该计划，但这些州担心, 此举会增加州公共支出，并增加雇主的员工福利成本 ， 尽管该法案规定联邦政府将承担几乎所有扩大计划的成本。其中超过一半的州位于南部。

The federal design of our Constitution and the system of checks and balances has jeopardized or outright blocked federal responses to important national issues. President Roosevelt’s efforts to combat the scourge of the Great Depression were initially struck down by the Supreme Court. More recently, President Obama’s effort to make health insurance accessible to more Americans under the Affordable Care Act immediately ran into legal challenges from some states, but it has been supported by the Supreme Court so far. However, the federal government’s ability to defend the voting rights of citizens suffered a major setback when the Supreme Court in 2013 struck down a key provision of the Voting Rights Act of 1965. No longer are the nine states with histories of racial discrimination in their voting processes required to submit plans for changes to the federal government for approval. After a tumultuous 2020 election, many states in 2021 advanced legislation to make voting rules and processes more rigorous, a move many said was an effort to limit voting access. For example, elected leaders in Georgia passed a law making voter ID requirements much stricter and also significantly limited options to vote outside of Election Day itself. In 2023's Moore v. Harper, the Supreme Court affirmed that state legislatures were not able to pass these laws with complete autonomy. Rejecting the theory of "independent state legislature," which asserted that states had the sole power to pass election laws, the Court ruled that voting laws passed by state governments were subject to judicial review. In 2023, the Court also ruled in favor of a challenge—already upheld by district courts—to new voting maps drawn up in Alabama; the plaintiffs had asserted that the new maps violated the Voting Rights Act by diluting the votes of Black voters. The Court agreed, and in the process held that the Voting Rights Act remained constitutional with regard to redistricting.


[.my2]
我们宪法的"联邦制设计"和"权力制衡体系"，已经危及甚至彻底阻碍了联邦政府对重要国家问题的应对。罗斯福总统为应对大萧条所做的努力, 最初被最高法院驳回。最近，奥巴马总统旨在通过《平价医疗法案》让更多美国人获得医疗保险的努力，立即遭到一些州的法律挑战，但迄今为止，最高法院一直支持该法案。然而，*2013 年最高法院推翻了 1965 年《投票权法案》 的一项关键条款，联邦政府捍卫公民投票权的能力遭受了重大挫折。* 如今， 九个在投票程序中存在种族歧视历史的州, 不再需要向联邦政府提交改革方案以获得批准。**在动荡的 2020 年大选之后，许多州在 2021 年推进立法，使投票规则和程序更加严格，许多人认为此举旨在限制投票权。**例如，*佐治亚州的民选官员通过了一项法律，大幅提高了选民身份验证的要求，并显著限制了"选举日"以外的投票方式。*  在 2023 年的 “摩尔诉哈珀案”（Moore v. Harper） 中，#*最高法院确认, "州立法机构"无权完全自主地通过此类法律。法院驳斥了“独立州立法机构”理论（该理论声称, 各州拥有制定"选举法"的唯一权力），并裁定"州政府"通过的"投票法", 须接受"司法审查"。*# 2023年，最高法院还裁定支持一项针对"阿拉巴马州新选区划分方案"的挑战——该挑战此前已得到地方法院的支持；原告声称，新方案违反了《投票权法》，削弱了黑人选民的投票权。最高法院同意了原告的观点，并在此过程中裁定，《投票权法》在选区重划方面,仍然符合宪法。

'''