
= 004 Civil Liberties  公民自由；公民权力
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


Black Lives Matter demonstrations across the nation provided an example of the freedom of assembly protected by the Bill of Rights. This right may now be in jeopardy as bills in several state legislatures threaten peaceful gatherings and even shield citizens who attack such protesters. Fights like this—in the streets, courts, legislatures, and public opinion—are hardly unique in U.S. history. In fact, they are the main driver of political change. 2025 protests against President Trump's policies and especially those targeting Tesla, the company of key Trump advisor Elon Musk, were met with threats of severe punishment for vandalism or destruction of Tesla property or vehicles.

[.my2]
“黑人的命也是命”运动席卷全国，展现了《权利法案》所保护的集会自由。然而，随着多个州议会通过的法案, 威胁和平集会，甚至保护"攻击抗议者的公民"，这项权利如今可能岌岌可危。此类斗争——发生在街头、法庭、议会和舆论场——在美国历史上并非个例。事实上，它们正是政治变革的主要驱动力。2025年，针对特朗普总统政策，尤其是针对其重要顾问埃隆·马斯克旗下特斯拉公司的抗议活动，遭到了严厉惩罚的威胁，任何破坏特斯拉财产或车辆的行为, 都将受到惩罚。

The framers of the Constitution wanted a government that would not repeat the abuses of individual liberties and rights that caused them to declare independence from Britain. However, laws and other “parchment barriers” (or written documents) alone have not protected freedoms over the years; instead, citizens have learned the truth of the old saying (often attributed to Thomas Jefferson but actually said by Irish politician John Philpot Curran), “Eternal vigilance is the price of liberty.” The actions of ordinary citizens, lawyers, and politicians have been at the core of a vigilant effort to protect constitutional liberties.

[.my2]
宪法的制定者们希望建立一个不会重蹈覆辙、不再侵犯"个人自由和权利"的政府，正是这些侵犯行为, 导致他们宣布脱离英国独立。然而，多年来，*#仅仅依靠法律和其他“纸质屏障”（或书面文件）并不能保护自由；相反，公民们逐渐领悟到那句古老格言的真谛#*（这句格言常被认为是托马斯·杰斐逊所说，但实际上是爱尔兰政治家约翰·菲尔波特·柯伦说的）：*#“自由的代价是永不懈怠(即要行动 just do it !, 要脚踏实地去做, 去维护, 去实现的)。”普通公民、律师和政治家的行动，一直是捍卫宪法赋予的自由这一重要举措的核心。#*

But what are those freedoms? And how should we balance them against the interests of society and other individuals? These are the key questions we will tackle in this chapter.

[.my2]
但这些自由究竟是什么？我们又该如何平衡自由与社会, 及其他个人的利益？这些正是本章要探讨的关键问题。

'''

== pure

Figure 4.1 Residents of many towns and cities have become accustomed to seeing protests near popular gathering places, businesses, or major intersections. Some government entities and office holders have considered or pursued more restrictive policies on protests, which may conflict with constitutional protections known as civil liberties. (credit: modification of "aaIMG_9353" by Paul/Flickr, CC BY 2.0)

Chapter Outline

- 4.1 What Are Civil Liberties?
- 4.2 Securing Basic Freedoms
- 4.3 The Rights of Suspects
- 4.4 Interpreting the Bill of Rights

Black Lives Matter demonstrations across the nation provided an example of the freedom of assembly protected by the Bill of Rights. This right may now be in jeopardy as bills in several state legislatures threaten peaceful gatherings and even shield citizens who attack such protesters. Fights like this—in the streets, courts, legislatures, and public opinion—are hardly unique in U.S. history. In fact, they are the main driver of political change. 2025 protests against President Trump's policies and especially those targeting Tesla, the company of key Trump advisor Elon Musk, were met with threats of severe punishment for vandalism or destruction of Tesla property or vehicles.

The framers of the Constitution wanted a government that would not repeat the abuses of individual liberties and rights that caused them to declare independence from Britain. However, laws and other “parchment barriers” (or written documents) alone have not protected freedoms over the years; instead, citizens have learned the truth of the old saying (often attributed to Thomas Jefferson but actually said by Irish politician John Philpot Curran), “Eternal vigilance is the price of liberty.” The actions of ordinary citizens, lawyers, and politicians have been at the core of a vigilant effort to protect constitutional liberties.

But what are those freedoms? And how should we balance them against the interests of society and other individuals? These are the key questions we will tackle in this chapter.


'''