
= 005-5 Equal Protection for Other Groups 对其他群体的平等保护
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




Many groups in American society have faced and continue to face challenges in achieving equality, fairness, and equal protection under the laws and policies of the federal government and/or the states. Some of these groups are often overlooked because they are not as large of a percentage of the U.S. population as women or African Americans, and because organized movements to achieve equality for them are relatively young. This does not mean, however, that the discrimination they face has not been as longstanding or as severe.

[.my2]
美国社会中许多群体在争取平等、公平和联邦政府及州政府法律与政策下的平等保护方面，过去和现在都面临着挑战。其中一些群体常常被忽视，因为他们在美国人口中所占比例不如女性或非裔美国人那么高，而且为他们争取平等的有组织运动也相对较新。但这并不意味着他们所面临的歧视持续时间不长或程度不严重。

HISPANIC/LATINO CIVIL RIGHTS
西班牙裔/拉丁裔民权
Hispanic and Latino people in the United States have faced many of the same problems as African Americans and Native Americans. Although the terms Hispanic and Latino are often used interchangeably in discussions and sometimes in research, they are not the same. Hispanic usually refers to native speakers of Spanish or those descended from Spanish-speaking countries. Latino refers to people who come from, or whose ancestors came from, Mexico, Central America, South America, and some of the Caribbean islands, collectively known as Latin America. Not all Hispanics are Latinos and vice versa. People from Spain are Hispanic but are not Latino, while people from Brazil are Latino but not Hispanic. Both Hispanics and Latinos may be of any race or ethnicity; they may be of European, African, Native American descent, or they may be of mixed racial or ethnic background. We will use the term "Latino" here, also noting that many people use the terms Latinx or Latine to be more inclusive.127
在美国，西班牙裔和拉丁裔群体面临着与非裔美国人和美洲原住民类似的诸多问题。尽管在讨论中，有时甚至在研究中， “西班牙裔 ”和 “拉丁裔” 这两个词经常被互换使用，但它们并非同一概念。 “西班牙裔” 通常指以西班牙语为母语的人，或来自西班牙语国家的人。 “拉丁裔” 则指来自墨西哥、中美洲、南美洲以及部分加勒比海岛屿（统称为拉丁美洲）的人，或祖先来自这些地区的人。并非所有西班牙裔都是拉丁裔，反之亦然。来自西班牙的人是西班牙裔，但不是拉丁裔；来自巴西的人是拉丁裔，但不是西班牙裔。西班牙裔和拉丁裔可以是任何种族或族裔；他们可能是欧洲裔、非洲裔、美洲原住民，也可能是多种族或族裔背景。本文将使用“拉丁裔”一词，同时也指出，许多人为了更具包容性，会使用“拉丁裔群体”（Latinx）或“拉丁裔”（Latine）等词语 。127

Many Latinos became part of the U.S. population following the annexation of Texas by the United States in 1845 and of California, Arizona, New Mexico, Nevada, Utah, and Colorado following the War with Mexico in 1848. Most were subject to discrimination and could find employment only as poorly paid migrant farm workers, railroad workers, and unskilled laborers.128 The Spanish-speaking population of the United States increased following the Spanish-American War in 1898 with the incorporation of Puerto Rico as a U.S. territory. In 1917, during World War I, the Jones Act granted U.S. citizenship to Puerto Ricans.

[.my2]
1845 年美国吞并德克萨斯后，许多拉丁裔人口成为美国的一部分；1848 年美墨战争后，又吞并了加利福尼亚州、亚利桑那州、新墨西哥州、内华达州、犹他州和科罗拉多州。他们中的大多数人遭受歧视，只能从事收入微薄的流动农场工人、铁路工人和非技术工人等工作。128 1898 年美西战争后，波多黎各并入美国，美国的西班牙语人口进一步增加。1917 年，第一次世界大战期间， 《琼斯法案》 赋予波多黎各人美国公民身份。

In the early twentieth century, waves of violence aimed at Mexicans and Mexican Americans swept the Southwest. Mexican Americans in Arizona and in parts of Texas were denied the right to vote, which they had previously possessed, and Mexican American children were barred from attending Anglo-American schools. During the Great Depression of the 1930s, Mexican immigrants and many Mexican Americans, both U.S.-born and naturalized citizens, living in the Southwest and Midwest were deported by the government so that Anglo-Americans could take the jobs that they had once held.129 When the United States entered World War II, however, Mexicans were invited to immigrate to the United States as farmworkers under the Bracero (bracero meaning “manual laborer” in Spanish) Program to make it possible for these American men to enlist in the armed services.130
二十世纪初，针对墨西哥人和墨西哥裔美国人的暴力浪潮席卷了美国西南部。亚利桑那州和德克萨斯州部分地区的墨西哥裔美国人被剥夺了他们原本拥有的投票权，墨西哥裔美国儿童也被禁止就读盎格鲁-撒克逊裔美国人学校。在 20 世纪 30 年代的大萧条时期，居住在西南部和中西部的墨西哥移民和许多墨西哥裔美国人（包括美国出生的和已入籍的公民）被政府驱逐出境，以便盎格鲁-撒克逊裔美国人能够抢走他们曾经从事的工作。 129 然而，当美国加入第二次世界大战时，为了使这些美国男性能够应征入伍，政府通过“布雷塞罗计划”（ Bracero ，西班牙语意为“体力劳动者”）邀请墨西哥人作为农场工人移民到美国。 130

Mexican Americans and Puerto Ricans did not passively accept discriminatory treatment, however. In 1903, Mexican farmworkers joined with Japanese farmworkers, who were also poorly paid, to form the first union to represent agricultural laborers. In 1929, Latino civil rights activists formed the League of United Latin American Citizens (LULAC) to protest against discrimination and to fight for greater rights for Latinos.131
然而，墨西哥裔美国人和波多黎各人并没有被动地接受歧视性待遇。1903 年，墨西哥裔农场工人与同样收入微薄的日本裔农场工人联合起来，成立了第一个代表农业工人的工会。1929 年，拉丁裔民权活动家成立了美国拉丁裔公民联盟 （LULAC），以抗议歧视并为拉丁裔争取更多权利。 131

Just as in the case of African Americans, however, true civil rights advances for Hispanic and Latino people did not take place until the end of World War II. Hispanic and Latino activists targeted the same racist practices as did African Americans and used many of the same tactics to end them. In 1946, Mexican American parents in California, with the assistance of the NAACP, sued several California school districts that forced Mexican and Mexican American children to attend segregated schools. In the case of Mendez v. Westminster (1947), the Court of Appeals for the Ninth Circuit Court held that the segregation of Mexican and Mexican American students into separate schools was unconstitutional.132
然而，正如非裔美国人的情况一样，西班牙裔和拉丁裔人民的真正民权进步直到二战结束才出现。西班牙裔和拉丁裔活动家们与非裔美国人一样，针对同样的种族主义做法，并运用了许多相同的策略来终结这些做法。1946 年，加利福尼亚州的墨西哥裔美国父母在全国有色人种协进会（NAACP）的协助下，起诉了几个强迫墨西哥裔和墨西哥裔美国儿童就读种族隔离学校的加州学区。在门德斯诉威斯敏斯特案（1947 年）中，第九巡回上诉法院裁定，将墨西哥裔和墨西哥裔美国学生隔离到不同的学校是违宪的。 132

Although Latinos made some civil rights advances in the decades following World War II, discrimination continued. Alarmed by the large number of undocumented Mexicans crossing the border into the United States in the 1950s, the United States government began Operation Wetback (wetback is a derogatory term for Mexicans living unofficially in the United States). From 1953 to 1958, more than three million Mexican immigrants, and some Mexican Americans as well, were deported from California, Texas, and Arizona.133 To limit the entry of Hispanic and Latino immigrants to the United States, in 1965 Congress imposed an immigration quota of 120,000 newcomers from the Western Hemisphere.

[.my2]
尽管拉丁裔在二战后的几十年里取得了一些民权方面的进展，但歧视依然存在。20 世纪 50 年代，大量墨西哥非法移民涌入美国，这引起了美国政府的警觉，于是启动了“湿背行动”（ “湿背” 是对非法居住在美国的墨西哥人的贬义称呼）。从 1953 年到 1958 年，超过 300 万墨西哥移民以及一些墨西哥裔美国人被从加利福尼亚州、德克萨斯州和亚利桑那州驱逐出境。为了限制西班牙裔和拉丁裔移民进入美国，国会于 1965 年规定，来自西半球的新移民配额为 12 万人。

At the same time that the federal government sought to restrict Hispanic and Latino immigration to the United States, the Mexican American civil rights movement grew stronger and more radical, just as the African American civil rights movement had done. While African Americans demanded Black Power and called for Black Pride, young Mexican American civil rights activists called for Brown Power and began to refer to themselves as Chicanos, a term disliked by many older, conservative Mexican Americans, in order to stress their pride in their hybrid Spanish-Native American cultural identity.134 Demands by Mexican American activists often focused on improving education for their children, and they called upon school districts to hire teachers and principals who were bilingual in English and Spanish, to teach Mexican and Mexican American history, and to offer instruction in both English and Spanish for children with limited ability to communicate in English.135
在联邦政府试图限制西班牙裔和拉丁裔移民进入美国的同时，墨西哥裔美国人民权运动也像非裔美国人民权运动一样，日益壮大并变得更加激进。当非裔美国人要求“黑人权力”并呼吁“黑人自豪”时，年轻的墨西哥裔美国人民权活动家则呼吁“棕色权力”，并开始自称为“奇卡诺人 ”（Chicanos ），这个词虽然不被许多年长的保守派墨西哥裔美国人所接受，但他们这样做是为了强调他们对自身西班牙裔和美洲原住民混合文化身份的自豪感。 134 墨西哥裔美国活动家的诉求通常集中在改善子女的教育上，他们呼吁学区聘用精通英语和西班牙语的双语教师和校长，教授墨西哥和墨西哥裔美国人的历史，并为英语沟通能力有限的儿童提供英语和西班牙语双语教学。 135

Milestone  里程碑
East L.A. Student Walkouts
东洛杉矶学生罢课
In March 1968, Chicano students at five high schools in East Los Angeles went on strike to demand better education for students of Mexican ancestry. Los Angeles schools did not allow Latino students to speak Spanish in class and gave no place to study Mexican history in the curriculum. Guidance counselors also encouraged students, regardless of their interests or ability, to pursue vocational careers instead of setting their sights on college. Some students were placed in specialized classes for people with disabilities. As a result, the dropout rate among Mexican American students was very high.

[.my2]
1968年3月，洛杉矶东部五所高中的奇卡诺学生举行罢课，要求改善墨西哥裔学生的教育条件。洛杉矶的学校不允许拉丁裔学生在课堂上说西班牙语，课程设置中也没有墨西哥历史的学习内容。升学指导老师还鼓励学生，无论他们的兴趣或能力如何，都应该选择职业道路，而不是追求大学教育。一些学生甚至被安排到专门为残疾学生开设的班级。结果，墨西哥裔美国学生的辍学率非常高。

School administrators refused to meet with the student protestors to discuss their grievances. After a week, police were sent in to end the strike. Thirteen of the organizers of the walkout were arrested and charged with conspiracy to disturb the peace. After Sal Castro, a teacher who had led the striking students, was dismissed from his job, activists held a sit-in at school district headquarters until Castro was reinstated. Student protests spread across the Southwest, and in response many schools did change. That same year, Congress passed the Bilingual Education Act, which required school districts with large numbers of Hispanic or Latino students to provide instruction in Spanish.136
学校管理人员拒绝与学生抗议者会面讨论他们的诉求。一周后，警方介入结束了罢课。13 名罢课组织者被捕，并被控以扰乱治安罪。领导罢课学生的教师萨尔·卡斯特罗被解雇后，活动人士在学区总部举行静坐示威，直到卡斯特罗复职。学生抗议活动蔓延至整个西南部，许多学校也因此做出了改变。同年，国会通过了 《双语教育法》 ，该法案要求拥有大量西班牙裔或拉丁裔学生的学区提供西班牙语教学。

Bilingual education remains controversial, even among Hispanic and Latino people. What are some arguments they might raise both for and against it? Are these different from arguments coming from non-Latinos?
即使在西班牙裔和拉丁裔人群中，双语教育仍然存在争议。他们可能会提出哪些支持和反对双语教育的论点？这些论点与非拉丁裔人群的论点有何不同？

Mexican American civil rights leaders were active in other areas as well. Throughout the 1960s, Cesar Chavez and Dolores Huerta fought for the rights of Mexican American agricultural laborers through their organization, the United Farm Workers (UFW), a union for migrant workers they founded in 1962. Chavez, Huerta, and the UFW proclaimed their solidarity with Filipino farm workers by joining them in a strike against grape growers in Delano, California, in 1965. Chavez consciously adopted the tactics of the African American civil rights movement. In 1965, he called upon all U.S. consumers to boycott California grapes (Figure 5.18), and in 1966, he led the UFW on a 300-mile march to Sacramento, the state capital, to bring the state farm workers’ problems to the attention of the entire country. The strike finally ended in 1970 when the grape growers agreed to give the pickers better pay and benefits.137
墨西哥裔美国人民权运动领袖在其他领域也十分活跃。整个 20 世纪 60 年代，塞萨尔 ·查韦斯和多洛雷斯 ·韦尔塔通过他们于 1962 年创立的联合农场工人协会（UFW）为墨西哥裔美国农业工人争取权益。UFW 是一个为流动工人服务的工会。1965 年，查韦斯、韦尔塔和 UFW 加入菲律宾裔农场工人的行列，参与了加州德拉诺的葡萄种植者罢工，以此声援菲律宾裔农场工人。查韦斯有意识地借鉴了非裔美国人民权运动的策略。1965 年，他呼吁所有美国消费者抵制加州葡萄（ 图 5.18 ）；1966 年，他带领 UFW 进行了长达 300 英里的游行，前往加州首府萨克拉门托，以使全国关注加州农场工人的困境。最终，在 1970 年，葡萄种植者同意提高采摘工人的工资和福利后，罢工结束。 137

Image A is of a group of people carrying signs. The signs read “United Farm Workers AFL-CIO boycott of Jewel Lettuce & Grapes Union Picket Line Don’t Cross” and “Boycott, Farm Workers on Strike”. Image B is of a poster that shows people picking crops in a field. The sun rises in the background. In the center of the sun is an eagle, and text along the sun reads “Si se puede ~ It can be done”. Text at the bottom of the poster reads “Boycott Lettuce & Grapes”.

[.my2]
Figure 5.18 Protestors picket a grocery store in 1973, urging consumers not to buy grapes or lettuce picked by underpaid farm workers (a). The boycott, organized by Cesar Chavez and the United Farm Workers using the slogan “Sí se puede” or “Yes, it can be done!” (b), ultimately forced California growers to improve conditions for migrant laborers.

[.my2]
图 5.18 1973 年，抗议者在一家杂货店外举行纠察示威，呼吁消费者不要购买由低薪农场工人采摘的葡萄或生菜 (a)。这场由塞萨尔·查韦斯和联合农场工人组织发起的抵制活动，以“Sí se puede”（是的，可以做到！）为口号 (b)，最终迫使加州种植者改善了外来务工人员的工作条件。
As Latino immigration to the United States increased in the late twentieth and early twenty-first centuries, discrimination also increased in many places. In 1994, California voters passed Proposition 187. The proposition sought to deny non-emergency health services, food stamps, welfare, and Medicaid to undocumented immigrants. It also banned children from attending public school unless they could present proof that they and their parents were legal residents of the United States. A federal court found it unconstitutional in 1997 on the grounds that the law’s intention was to regulate immigration, a power held only by the federal government.138
随着 20 世纪末 21 世纪初拉丁裔移民涌入美国，许多地方的歧视现象也随之加剧。1994 年，加州选民通过了第 187 号提案 。该提案试图剥夺无证移民获得非紧急医疗服务、食品券、福利和医疗补助的权利。它还禁止儿童就读公立学校，除非他们能够出示自己及其父母是美国合法居民的证明。1997 年，联邦法院裁定该提案违宪，理由是该法案的目的是监管移民，而这项权力只有联邦政府才拥有。 138

In 2005, discussion began in Congress on proposed legislation that would make it a felony to enter the United States illegally or to give assistance to anyone who had done so. Although the bill quickly died, on May 1, 2006, hundreds of thousands of people, primarily Latinos, staged public demonstrations in major U.S. cities, refusing to work or attend school for one day.139 The protestors claimed that people seeking a better life should not be treated as criminals and that undocumented immigrants already living in the United States should have the opportunity to become citizens.

[.my2]
2005 年，国会开始讨论一项法案提案，该提案拟将非法入境美国或协助非法入境者定为重罪。尽管该法案很快夭折，但在 2006 年 5 月 1 日，数十万人，其中大部分是拉丁裔，在美国各大城市举行了公开示威活动，拒绝工作或上学一天。 139 抗议者声称，寻求更好生活的人不应被视为罪犯，并且已经居住在美国的无证移民应该有机会成为公民。

Following the failure to make undocumented immigration a felony under federal law, several states attempted to impose their own sanctions on unauthorized entry. In April 2010, Arizona passed a law that made illegal immigration a state crime. The law also forbade undocumented immigrants from seeking work and allowed law enforcement officers to arrest people suspected of being in the U.S. illegally. Thousands protested the law, claiming that it encouraged racial profiling. In 2012, in Arizona v. United States, the U.S. Supreme Court struck down those provisions of the law that made it a state crime to reside in the United States illegally, forbade undocumented immigrants to take jobs, and allowed the police to arrest those suspected of being illegal immigrants.140 The court, however, upheld the authority of the police to ascertain the immigration status of someone suspected of being an undocumented entrant if the person had been stopped or arrested by the police for other reasons.141
由于联邦法律未能将非法移民定为重罪，一些州试图自行采取措施制裁非法入境者。2010 年 4 月，亚利桑那州通过一项法律，将非法移民定为州级犯罪。该法律还禁止非法移民寻求工作，并允许执法人员逮捕涉嫌非法滞留美国的人员。数千人抗议该法律，声称其助长了种族歧视。2012 年，在 “亚利桑那州诉美国案” 中，美国最高法院推翻了该法律中将非法居留定为州级犯罪、禁止非法移民就业以及允许警方逮捕涉嫌非法移民人员的条款。 140 然而，法院维持了警方在因其他原因被警方拦截或逮捕的情况下，有权核实涉嫌非法入境者的移民身份。 141

Today, Latinos constitute the largest minority group in the United States. They also have one of the highest birth rates of any ethnic group.142 Although Hispanic people lag behind non-Hispanic White people in terms of income and high school graduation rates, they are enrolling in college at higher rates than non-Hispanic White people.143 Topics at the forefront of public debate during the Biden administration included immigration reform, the DREAM Act (a proposal for granting undocumented immigrants permanent residency in stages), and court action on executive orders on immigration. The first Trump administration was very active on issues of immigration and border security. Aside from the proposal to build a border wall, other areas of action have included various travel bans and the policy of separating families at the border as they attempt to enter the country. 144
如今，拉丁裔是美国最大的少数族裔群体，也是生育率最高的族裔群体之一。 142 虽然拉丁裔在收入和高中毕业率方面落后于非拉丁裔白人，但他们的大学入学率却高于非拉丁裔白人。 143 拜登政府时期，公众辩论的焦点议题包括移民改革、 《梦想法案》 （一项分阶段给予无证移民永久居留权的提案）以及针对移民行政命令的法庭诉讼。特朗普第一任期政府在移民和边境安全问题上非常活跃。除了修建边境墙的提议外，其他举措还包括实施各种旅行禁令以及在边境强行拆散试图入境的家庭。 144

The 2024 presidential campaign between former President Donald Trump and Vice President Kamala Harris brought matters related to Latino immigration to the fore once again. Trump, who was elected to a second term and took office in January 2025, dramatized issues of safety and the border and in American communities, including Aurora, Colorado. After swearing in as president for a second four-year term of office, President Trump quickly authorized a widespread campaign by the U.S. Immigration and Customs Enforcement Service (ICE) to round up illegal immigrants across the country of Latino or Hispanic descent. ICE has been omnipresent in American communities, including state and local courts, public spaces and even schools. Some say that the sheer number of people questioned to date is well beyond lists of suspects that ICE might be reasonably expected to investigate who potentially pose a threat to public safety. While supporters of the approach say that the broad net cast by the Trump administration through ICE has led to an increase in legitimate detainments of suspects who pose such a threat, opponents argue that the sheer numbers of law-abiding persons questioned, who must prove their status or face arrest, has been overwhelming for the Latino and Hispanic communities and produced a great deal of fear.145, 146, 147
2024 年总统大选，前总统唐纳德·特朗普和副总统卡马拉·哈里斯之间的角逐，再次将拉丁裔移民问题推到了风口浪尖。特朗普成功连任，于 2025 年 1 月就职。他大肆渲染安全问题、边境问题以及美国社区（包括科罗拉多州奥罗拉市）的困境。在宣誓就任第二个四年任期后，特朗普总统迅速授权美国移民和海关执法局（ICE）在全国范围内开展大规模行动，抓捕拉丁裔或西班牙裔非法移民。ICE 的身影遍布美国各地，包括州和地方法院、公共场所甚至学校。有人指出，迄今为止，ICE 接受讯问的人数远远超过了其理应调查的、可能对公共安全构成威胁的嫌疑人名单。支持者认为，特朗普政府通过美国移民及海关执法局（ICE）撒下的大网，使得对构成威胁的嫌疑人进行合法拘留的案例有所增加；而反对者则认为，大量守法公民被盘问，他们必须证明自己的身份，否则将面临逮捕，这对拉丁裔和西班牙裔社区来说压力巨大，并造成了极大的恐慌。 145 146 , 147

ASIAN AMERICAN CIVIL RIGHTS
亚裔美国人民权运动
As the rash of recent violence against them has shown, Asian Americans have also often been discriminated against and denied their civil rights. Often stereotyped as the "the model minority" (because it is assumed they are generally financially successful and do well academically), the underlying reality is complex. The truth is that Asian Americans have long faced discrimination. Indeed, in the nineteenth century, Asian people were among the most despised of all immigrant groups and were often subjected to the same laws enforcing segregation and forbidding interracial marriage as were African Americans and American Indians.

[.my2]
正如近期针对亚裔美国人的暴力事件频发所表明的那样， 亚裔美国人也经常遭受歧视，其公民权利也常常被剥夺。他们常被刻板印象地视为“模范少数族裔”（因为人们普遍认为他们经济成功、学业优异），但其背后的现实却十分复杂。事实上，亚裔美国人长期以来一直面临歧视。早在 19 世纪，亚裔就曾是所有移民群体中最受歧视的群体之一，他们常常像非裔美国人和美洲原住民一样，受到同样的种族隔离法律和禁止跨种族婚姻的法律的约束。

The Chinese were the first large group of Asian people to immigrate to the United States. They arrived in large numbers in the mid-nineteenth century to work in the mining industry and on the Central Pacific Railroad. Others worked as servants or cooks or operated laundries. Their willingness to work for less money than White workers led White workers in California to call for a ban on Chinese immigration. In 1882, Congress passed the Chinese Exclusion Act, which prevented Chinese from immigrating to the United States for ten years and prevented Chinese already in the country from becoming citizens (Figure 5.19). In 1892, the Geary Act extended the ban on Chinese immigration for another ten years. In 1913, California passed a law preventing all Asian people, not just the Chinese, from owning land. With the passage of the Immigration Act of 1924, all Asian people, with the exception of Filipinos, were prevented from immigrating to the United States or becoming naturalized citizens. Laws in several states barred marriage between Chinese and White Americans, and some cities with large Asian populations required Asian children to attend segregated schools.148
华人是第一批大规模移民美国的亚洲人。他们在十九世纪中叶大量涌入美国，从事采矿业和中央太平洋铁路的建设。其他人则从事佣人、厨师或洗衣店等工作。由于他们愿意接受比白人更低的工资，加利福尼亚州的白人呼吁禁止华人移民。1882 年，国会通过了《 排华法案》 ，禁止华人移民美国十年，并禁止已在美国的华人入籍（ 图 5.19 ）。1892 年， 《吉里法案》 将华人移民禁令延长了十年。1913 年，加利福尼亚州通过一项法律，禁止所有亚洲人（而不仅仅是华人）拥有土地。随着 1924 年 《移民法》 的通过，除菲律宾人外，所有亚洲人都被禁止移民美国或入籍成为美国公民。一些州的法律禁止华裔和白人通婚，一些亚裔人口较多的城市要求亚裔儿童就读种族隔离学校 。148

An image of a cartoon in which a person with a long ponytail is seated in front of a gate labeled “Golden Gate of Liberty”. The crate the person sits on is labeled “Order” and behind it is are crates labeled “Peace” and “Sobriety”. A bag of money next to the person’s feet is labeled “Industry”. A sign on the wall reads “Notice – Communist Nihilist Socialist Fenian & Hoodlum Welcome but no admittance to Chinamen”. The bottom of the cartoon reads “The only one barred out. Enlightened American Statesmen—“We must draw the line somewhere, you know”.”.

[.my2]
Figure 5.19 The cartoon shows a Chinese laborer, the personification of industry and sobriety, outside the “Golden Gate of Liberty.” The Chinese Exclusion Act of 1882 has barred him from entering the country, while communists and “hoodlums” are allowed in.

[.my2]
图 5.19 这幅漫画描绘了一位中国劳工，他是勤劳和节俭的化身，站在“自由之门”外。1882 年的《排华法案》禁止他进入美国，而共产党人和“暴徒”却被允许入境。
During World War II, citizens of Japanese descent living on the West Coast, whether naturalized immigrants or Japanese Americans born in the United States, were subjected to the indignity of being removed from their communities and interned under Executive Order 9066 (Figure 5.20). The reason was fear that they might prove disloyal to the United States and give assistance to Japan. Although Italians and Germans suspected of disloyalty were also interned by the U.S. government, only the Japanese were imprisoned solely on the basis of their ethnicity. None of the more than 110,000 Japanese and Japanese Americans internees was ever found to have committed a disloyal act against the United States, and many young Japanese American men served in the U.S. army during the war.149 Although Japanese American Fred Korematsu challenged the right of the government to imprison law-abiding citizens, the Supreme Court decision in the 1944 case of Korematsu v. United States upheld the actions of the government as a necessary precaution in a time of war.150 When internees returned from the camps after the war was over, many of them discovered that the houses, cars, and businesses they had left behind, often in the care of White neighbors, had been sold or destroyed.151
二战期间，居住在美国西海岸的日裔公民，无论是归化移民还是在美国出生的日裔美国人，都遭受了被强行驱逐出家园并根据第 9066 号行政命令 （ 图 5.20 ）被拘禁的屈辱。其原因是担心他们可能对美国不忠，并向日本提供援助。尽管美国政府也拘禁了被怀疑不忠的意大利人和德国人，但只有日裔美国人仅仅因为其种族而被监禁。超过 11 万名被拘禁的日裔和日裔美国人中，没有一人被发现犯有对美国的不忠行为，许多年轻的日裔美国男子在战争期间加入了美国军队。 149 尽管日裔美国人弗雷德 ·科雷松质疑政府监禁守法公民的合法性，但最高法院在 1944 年的 “科雷松诉美国案”中裁定， 政府的行为是战时必要的预防措施。 150 战后，许多被拘留者从集中营返回家园，发现他们留下的房屋、汽车和生意场所，往往由白人邻居照管，已被出售或摧毁 。151

An image of a long line of people that snakes back and forth.

[.my2]
Figure 5.20 Japanese Americans displaced from their homes by the U.S. government during World War II stand in line outside the mess hall at a relocation center in San Bruno, California, on April 29, 1942.

[.my2]
图 5.20 二战期间被美国政府驱逐出家园的日裔美国人于 1942 年 4 月 29 日在加利福尼亚州圣布鲁诺的一个安置中心的食堂外排队。
Link to Learning  学习链接
Explore the resources at Japanese American Internment and Digital History to learn more about experiences of Japanese Americans during World War II.

[.my2]
浏览日裔美国人拘留营和数字历史网站，了解更多关于二战期间日裔美国人的经历。

The growth of the African American, Chicano, and Native American civil rights movements in the 1960s inspired many Asian Americans to demand their own rights. Discrimination against Asian Americans, regardless of national origin, increased during the Vietnam War. Ironically, violence directed indiscriminately against Chinese, Japanese, Koreans, and Vietnamese caused members of these groups to unite around a shared pan-Asian identity, much as Native Americans had in the Pan-Indian movement. In 1968, students of Asian ancestry at the University of California at Berkeley formed the Asian American Political Alliance. Asian American students also joined Chicano, Native American, and African American students to demand that colleges offer ethnic studies courses.152 In 1974, in the case of Lau v. Nichols, Chinese American students in San Francisco sued the school district, claiming its failure to provide them with assistance in learning English denied them equal educational opportunities.153 The Supreme Court found in favor of the students.

[.my2]
20 世纪 60 年代非裔美国人、奇卡诺人和美洲原住民民权运动的兴起激励了许多亚裔美国人争取自身权益。越战期间，针对亚裔美国人的歧视，无论其国籍如何，都愈演愈烈。具有讽刺意味的是，针对华裔、日裔、韩裔和越南裔的无差别暴力，反而促使这些群体成员团结起来，形成共同的泛亚裔身份认同，正如美洲原住民在泛印第安运动中所做的那样。1968 年，加州大学伯克利分校的亚裔学生成立了亚裔美国人政治联盟 。亚裔美国学生还与奇卡诺人、美洲原住民和非裔美国学生一起，要求高校开设族裔研究课程。 1974 年，在刘诉尼科尔斯案中，旧金山的华裔美国学生起诉学区，声称学区未能为他们提供英语学习方面的帮助，剥夺了他们平等的教育机会。最高法院最终判决学生胜诉。

Until recent attacks against Asian Americans during the COVID-19 pandemic, the Asian American movement was not as active as other civil rights movements. While not keeping them free from discrimination, their educational achievement and economic success placed Asian Americans in a much better position to defend their rights. Unfortunately, racist vitriol related to the origin of COVID-19 highlighted discrimination against Asian Americans and the formerly quiet movement has become highly salient. Hate crimes against Asian Americans increased 150 percent in 2020 and rose over 800 percent in New York City.154
在新冠疫情期间针对亚裔美国人的袭击事件发生之前，亚裔美国人运动的活跃程度远不及其他民权运动。尽管亚裔美国人的教育成就和经济实力并未完全消除歧视，但他们在捍卫自身权利方面却拥有更强大的实力。不幸的是，与新冠疫情起源相关的种族主义言论凸显了针对亚裔美国人的歧视，原本较为低调的运动也因此变得异常活跃。2020 年，针对亚裔美国人的仇恨犯罪增加了 150%，在纽约市更是激增超过 800 %。

THE FIGHT FOR CIVIL RIGHTS IN THE LGBTQ COMMUNITY
LGBTQ 群体争取公民权利的斗争
Laws against same-sex relations and relationships existed in most states throughout the nineteenth and twentieth centuries. By the late nineteenth century, homosexuality had come to be regarded as a form of mental illness as well as a sin, and gay men were often erroneously believed to be pedophiles.155 As a result, lesbian women, gay men, bisexual people, and transgender people, currently known as the LGBTQ community, had to keep their sexual orientation hidden or “closeted.” Secrecy became even more important in the 1950s, when fear of gay men increased and the federal government believed they could be led into disloyal acts through blackmail by Soviet agents. As a result, many men lost or were denied government jobs.156 Fears of lesbians also increased after World War II as U.S. society stressed conformity to traditional gender roles and the importance of marriage and childrearing.157
在 19 世纪和 20 世纪，大多数州都存在禁止同性关系的法律。到 19 世纪末，同性恋被视为一种精神疾病和罪恶，男同性恋者常常被错误地认为是恋童癖。 155 因此，女同性恋者、男同性恋者、双性恋者和跨性别者（即现在的 LGBTQ 群体）不得不隐藏自己的性取向，也就是所谓的“出柜”。到了 20 世纪 50 年代，随着对男同性恋者的恐惧加剧，以及联邦政府认为他们可能受到苏联特工的勒索而做出不忠行为，保密变得更加重要。结果，许多男性失去了政府工作或被拒绝录用。 156 二战后，随着美国社会强调遵守传统性别角色以及婚姻和生育的重要性，对女同性恋者的恐惧也随之加剧。 157

The very secrecy in which lesbian, gay, bisexual, and transgender people had to live made it difficult for them to organize to fight for their rights as other, more visible groups had done. Some organizations did exist, however. The Mattachine Society, established in 1950, was one of the first groups to champion the rights of gay men. Its goal was to unite gay men who otherwise lived in secrecy and to fight against abuse. The Mattachine Society often worked with the Daughters of Bilitis, a lesbian rights organization. Among the early issues targeted by the Mattachine Society was police entrapment of gay men in which plain-clothes police officers would enter neighborhoods or establishments known to be frequented by gay people, and act as if they were interested in a sexual encounter; then the police would arrest those they said propositioned them. Entrapment often posed serious risks, because men who were associated with homosexuality—even if never prosecuted—were at risk of losing their jobs, families, or other positions.158
女同性恋、男同性恋、双性恋和跨性别者不得不生活在隐秘之中，这使得他们难以像其他更公开的群体那样组织起来争取自身权益。然而，一些组织确实存在。成立于 1950 年的马塔辛协会是最早倡导男同性恋权益的组织之一。其目标是团结那些原本生活在隐秘中的男同性恋者，并共同对抗虐待。马塔辛协会经常与女同性恋权益组织“ 比莉蒂斯之女”（Daughters of Bilitis） 合作。马塔辛协会早期关注的问题之一是警方对男同性恋者的诱捕。便衣警察会进入男同性恋者经常出入的社区或场所，假装对性交易感兴趣；然后，警方会逮捕那些被他们指控向其提出性要求的人。这种诱捕往往会带来严重的风险，因为与同性恋有关联的男性——即使从未被起诉——也面临着失去工作、家庭或其他地位的风险。 158

Law enforcement abuses against LGBTQ people took many forms. Some of the activities were encoded in laws, while others were interpretations of older laws or simply policies of individual cities or departments. In many places, any act related to same-sex relationships, such as holding hands, kissing, or dancing, was forbidden in public. As a result, police frequently raided what were known as gay bars, often committing sexually humiliating acts against patrons. Transgender people faced some of the worst treatment. Dressing in drag would result in arrest and prosecution. Transgender people were subjected to public strip searches and were groped beneath their undergarments to determine their sex. Such treatment of LGBTQ people by law enforcement also left them unprotected from others who assaulted them.

[.my2]
执法部门对 LGBTQ 人群的滥用职权形式多种多样。有些行为被写入法律，有些则是对旧法律的解读，还有一些仅仅是个别城市或部门的政策。在许多地方，任何与同性关系相关的行为，例如牵手、接吻或跳舞，在公共场合都是被禁止的。因此，警方经常突袭所谓的“同性恋酒吧”，并常常对顾客实施性羞辱行为。跨性别者遭受的待遇最为恶劣。穿着异性服装会导致被捕和起诉。跨性别者会被公开搜身，并被触摸内衣以确定其性别。执法部门对 LGBTQ 人群的这种对待方式也使他们无法保护自己免受他人的侵害。

In the 1960s, the gay and lesbian rights movements began to grow more radical, in a manner similar to other civil rights movements. In 1962, gay Philadelphians demonstrated in front of Independence Hall. In 1966, transgender sex workers who were tired of police harassment rioted in San Francisco. In June 1969, gay men, lesbians, and transgender people erupted in violence when New York City police attempted to arrest customers at a gay bar in Greenwich Village called the Stonewall Inn. The patrons’ ability to resist arrest and fend off the police inspired many members of New York’s LGBTQ community, and the riots persisted over several nights. New organizations promoting LGBTQ rights that emerged after Stonewall were more radical and confrontational than the Mattachine Society and the Daughters of Bilitis had been. These groups, like the Gay Activists Alliance and the Gay Liberation Front, called not just for equality before the law and protection against abuse but also for “liberation,” Gay Power, and Gay Pride.159
20 世纪 60 年代，同性恋权利运动开始变得更加激进，其方式与其他民权运动类似。1962 年，费城的同性恋者在独立厅前举行示威游行。1966 年，不堪忍受警察骚扰的跨性别性工作者在旧金山发动骚乱。1969 年 6 月，纽约市警察试图逮捕格林威治村一家名为石墙酒吧的同性恋酒吧的顾客，引发了男同性恋、女同性恋和跨性别者的暴力冲突。顾客们反抗逮捕、击退警察的行为鼓舞了纽约 LGBTQ 群体中的许多人，骚乱持续了数个夜晚。石墙事件后涌现的 LGBTQ 权利倡导组织比马塔辛协会和比莉蒂斯之女组织更加激进、更具对抗性。这些团体，例如同性恋维权联盟和同性恋解放阵线 ，不仅呼吁法律面前人人平等和免受虐待，还呼吁“解放”、同性恋力量和同性恋骄傲 。159

Although LGBTQ people gained their civil rights later than many other groups, changes did occur beginning in the 1970s, remarkably quickly when we consider how long other minority groups had fought for their rights. The decade saw 18 states decriminalize same-sex relations, following Illinois and Connecticut, which had done so in the 1960s. In 1973, the American Psychological Association ended its classification of homosexuality as a mental disorder. In 1994, the U.S. military adopted the policy of “Don’t ask, don’t tell.” This act, Department of Defense Directive 1304.26, officially prohibited discrimination against gay, lesbian, and bisexual people by the U.S. military. It also prohibited superior officers from asking about or investigating the sexual orientation of those below them in rank.160 However, those gay, lesbian, and bisexual people who spoke openly about their sexual orientation were still subject to dismissal because it remained illegal for anyone except straight people to serve in the armed forces. The policy ended in 2011, and now gay, lesbian, and bisexual people may serve openly in the military.161 Transgender people were banned from serving in the military in 1960. The ban lasted until 2016, when the government began a gradual process of expanding and altering the limitations on their service. In early 2021, the Biden administration announced that there would no longer be restrictions on military service by transgender individuals, that medical support for gender transition would be provided, and that procedures would be developed to change a service member's official gender marker. Upon taking office in 2025, Donald Trump signed an executive order banning transgender people from serving in the military; a judge blocked enforcement of the ban because it violated transgender people's constitutional rights. The ruling will likely undergo numerous appeals.

[.my2]
尽管 LGBTQ 群体获得公民权利的时间晚于许多其他群体，但自 20 世纪 70 年代起，情况确实发生了变化，考虑到其他少数群体为争取自身权利所付出的漫长斗争，这一速度可谓惊人。在 70 年代，继伊利诺伊州和康涅狄格州（这两个州早在 20 世纪 60 年代就已将同性关系合法化）之后，又有 18 个州将同性关系合法化。1973 年，美国心理学会终止了将同性恋归类为精神障碍的做法。1994 年，美国军方采纳了“不问不说”政策。这项政策，即国防部第 1304.26 号指令 ， 正式禁止美国军方歧视同性恋、女同性恋和双性恋者。该指令还禁止上级军官询问或调查下级军官的性取向。然而，那些公开谈论自己性取向的同性恋、女同性恋和双性恋者仍然可能被开除，因为当时除异性恋者外，任何人在军队服役仍然是非法的。该政策于 2011 年终止，如今同性恋、女同性恋和双性恋者可以公开在军队服役。1960 年， 161 名跨性别者被禁止在军队服役。这项禁令一直持续到 2016 年，之后政府开始逐步放宽和修改对他们服役的限制。2021 年初，拜登政府宣布将不再限制跨性别者在军队服役，并将提供性别转换的医疗支持，同时还将制定相关程序来更改现役军人的官方性别标记。 唐纳德·特朗普于2025年就职后，签署了一项行政命令，禁止跨性别者在军队服役；一位法官阻止了该禁令的执行，理由是它侵犯了跨性别者的宪法权利。这项裁决很可能会经历多次上诉。

In 2003, in the case of Lawrence v. Texas, the Supreme Court ruled unconstitutional fourteen remaining states' laws that criminalized sexual intercourse between consenting adults of the same sex.162 Beginning in 2000, several states made it possible for same-sex couples to enter into legal relationships known as civil unions or domestic partnerships. These arrangements extended many of the same protections enjoyed by heterosexual married couples to same-sex couples. LGBTQ activists, however, continued to fight for the right to marry. Same-sex marriages would allow partners to enjoy exactly the same rights as married heterosexual couples and accord their relationships the same dignity and importance. In 2004, Massachusetts became the first state to grant legal status to same-sex marriage. Other states quickly followed. This development prompted a backlash among many religious conservatives, who considered homosexuality a sin and argued that allowing same-sex couples to marry would lessen the value and sanctity of heterosexual marriage. Many states passed laws banning same-sex marriage, and many gay and lesbian couples challenged these laws, successfully, in the courts. Finally, in Obergefell v. Hodges, the Supreme Court overturned state bans and made same-sex marriage legal throughout the United States on June 26, 2015 (Figure 5.21).163
2003 年，在 “劳伦斯诉德克萨斯州案”中，最高法院裁定其余 14 个州将成年人之间自愿的同性性行为定为犯罪的法律违宪。 162 自 2000 年起，一些州允许同性伴侣缔结被称为民事结合或家庭伴侣关系的合法关系。这些安排将许多与异性已婚夫妇相同的保护措施扩展到了同性伴侣。然而，LGBTQ 权益人士继续为婚姻权而奋斗。他们认为，同性婚姻将使伴侣享有与异性已婚夫妇完全相同的权利，并赋予他们的关系同样的尊严和重要性。2004 年，马萨诸塞州成为第一个承认同性婚姻合法地位的州。其他州也迅速效仿。这一进展引发了许多宗教保守派人士的强烈反对，他们认为同性恋是一种罪过，并辩称允许同性伴侣结婚会降低异性婚姻的价值和神圣性。许多州通过了禁止同性婚姻的法律，许多同性恋伴侣在法庭上挑战这些法律，并最终胜诉。最终，在奥贝格费尔诉霍奇斯案中，最高法院推翻了各州的禁令，并于 2015 年 6 月 26 日宣布同性婚姻在美国全境合法化（ 图 5.21 ）。 163

An image of a group of people at the steps of the Supreme Court building. Many people are holding flags marked with the symbol of an equals sign.

[.my2]
Figure 5.21 Supporters of marriage equality celebrate outside the Supreme Court on June 26, 2015, following the announcement of the Court’s decision in Obergefell v. Hodges declaring same-sex marriage a constitutional right under the Fourteenth Amendment. (credit: Matt Popovich)
图 5.21 2015 年 6 月 26 日，在最高法院宣布奥贝格费尔诉霍奇斯案的裁决，认定同性婚姻是受美国宪法第十四修正案保护的宪法权利后，婚姻平等的支持者在最高法院外庆祝。 （图片来源：马特·波波维奇）
The legalization of same-sex marriage throughout the United States led some people to feel their religious beliefs were under attack, and many religiously conservative business owners have refused to acknowledge LBGT rights or the legitimacy of same-sex marriages. Following swiftly upon the heels of the Obergefell ruling, the Indiana legislature passed a Religious Freedom Restoration Act (RFRA). Congress had already passed such a law in 1993; it was intended to extend protection to minority religions, such as by allowing rituals of the Native American Church. However, the Supreme Court in City of Boerne v. Flores (1997) ruled that the 1993 law applied only to the federal government and not to state governments.164 Thus several state legislatures later passed their own Religious Freedom Restoration Acts. These laws state that the government cannot “substantially burden an individual’s exercise of religion” unless it would serve a “compelling governmental interest” to do so. They allow individuals, which also include businesses and other organizations, to discriminate against others, primarily same-sex couples and LGBTQ people, if the individual’s religious beliefs are opposed to homosexuality.

[.my2]
美国同性婚姻合法化后，一些人感到他们的宗教信仰受到了攻击，许多宗教保守派企业主拒绝承认 LGBT 群体的权利或同性婚姻的合法性。 奥贝格费尔案判决后不久，印第安纳州议会通过了 《宗教自由恢复法案》 （RFRA）。国会早在 1993 年就通过了类似的法案，旨在保护少数宗教，例如允许举行美洲原住民教会的仪式。然而，最高法院在博尔内市诉弗洛雷斯案（1997 年）中裁定，1993 年的法案仅适用于联邦政府， 不适用于州政府。因此，一些州议会随后也通过了各自的《宗教自由恢复法案》。这些法案规定，除非有“令人信服的政府利益”，否则政府不得“实质性地限制个人行使宗教信仰自由”。这些法律允许个人（也包括企业和其他组织）歧视他人，主要是同性伴侣和 LGBTQ 人群，如果该个人的宗教信仰反对同性恋。

LGBTQ Americans still encounter difficulties in other areas as well. While the Supreme Court ruled in 2020 that employers cannot discriminate based on sexual orientation and transgender status, LGBTQ people are not protected from housing discrimination. The federal Department of Housing and Urban Development has indicated that refusing to rent or sell homes to transgender people may be considered sex discrimination, but there is no nationwide clarity on the law.165 Violence and law enforcement targeting members of the LGBTQ community remains a serious problem; this violence occurs on the streets and in their homes.166 The enactment of the Matthew Shepard and James Byrd Jr. Hate Crimes Prevention Act, also known as the Matthew Shepard Act, in 2009 made it a federal hate crime to attack someone based on gender, gender identity, sexual orientation, or disability and made it easier for federal, state, and local authorities to investigate hate crimes, but it has not necessarily made the world safer for LGBTQ Americans. Transgender rights have also been increasingly under scrutiny as 2021 brought a record number of pieces of anti-transgender legislation in state legislatures.167 The U.S. Supreme Court, however, gave the transgender community a win when they chose not to hear a school's appeal of a lower court decision on a transgender student bathroom case.168 Soon after, the federal government indicated that it would follow the approach of many states in including a non-binary gender marker option on official documents, such as passports.

[.my2]
LGBTQ 美国人在其他领域也面临诸多困难。尽管最高法院在 2020 年裁定雇主不得基于性取向和跨性别身份进行歧视，但 LGBTQ 人群并未受到住房歧视的保护。联邦住房和城市发展部曾表示，拒绝向跨性别者出租或出售房屋可能构成性别歧视，但目前全国范围内对此法律尚无明确规定。 165 针对 LGBTQ 群体的暴力和执法行为仍然是一个严峻的问题；这种暴力行为既发生在街头，也发生在他们的家中。 166 2009 年颁布的《马修·谢泼德和詹姆斯·伯德仇恨犯罪预防法案》（简称《 马修·谢泼德法案》 ）将基于性别、性别认同、性取向或残疾的攻击行为定为联邦仇恨犯罪 ，并简化了联邦、州和地方当局调查仇恨犯罪的程序，但这并不一定能让 LGBTQ 美国人的生活更加安全。随着 2021 年各州立法机构通过的反跨性别法案数量创下历史新高，跨性别者的权利也日益受到关注。 167 然而，美国最高法院驳回了一所学校就下级法院关于跨性别学生使用卫生间一案的判决提出的上诉，这无疑是对跨性别群体的一次胜利。 168 此后不久，联邦政府表示将效仿许多州的做法，在护照等官方文件中增加非二元性别选项。

The Supreme Court provided another win in 2020 in Bostock v. Clayton County. This case involved reconciling Federal law regarding employment discrimination in governmental (Bostock v. Clayton County) and private organizations (Altitude Express, Inc. v. Zarda, R.G. & G.R. Harris Funeral Homes, Inc. v. Equal Employment Opportunity Commission). The plaintiff, Gerald Bostock, was fired from his position with the county for raising interest in a gay softball team while at work. In a 6-3 decision, the court found that an employer that terminates an employee for being gay or transgender is in violation of Title VII of the Civil Rights Act of 1964. Importantly, the Court (with Justice Neil Gorsuch writing for the majority) specifically indicated that discrimination due to sexual orientation or gender identity is equivalent to discrimination on the basis of sex, long prohibited by Title VII.

[.my2]
2020 年，最高法院在博斯托克诉克莱顿县一案中再次取得胜利。该案涉及协调联邦法律中关于政府机构（ 博斯托克诉克莱顿县 ）和私营机构（ Altitude Express, Inc.诉 Zarda, RG & GR Harris Funeral Homes, Inc.诉平等就业机会委员会 ）就业歧视的规定。原告杰拉尔德·博斯托克因在工作期间公开支持一支同性恋垒球队而被县政府解雇。法院以 6 比 3 的投票结果裁定，雇主因雇员是同性恋或跨性别者而将其解雇，违反了 1964 年《民权法案》第七章的规定。值得注意的是，法院（尼尔·戈萨奇大法官代表多数意见撰写判决书）明确指出，基于性取向或性别认同的歧视等同于基于性别的歧视，而后者早已被《民权法案》第七章明文禁止。

CIVIL RIGHTS AND THE AMERICANS WITH DISABILITIES ACT
《民权法案》和《美国残疾人法案》
People with disabilities make up one of the last groups whose civil rights have been recognized. For a long time, they were denied employment and access to public education. Many were institutionalized. A eugenics movement in the United States in the late nineteenth and early to mid-twentieth centuries sought to encourage childbearing among White people without disabilities and discourage it among those with physical or intellectual disabilities. Many states passed laws prohibiting marriage among people who had what were believed to be hereditary “defects.” Among those affected were people who were blind or deaf, those with epilepsy, people with intellectual or developmental disabilities, and those with mental illnesses. In some states, programs existed to sterilize people considered “feeble minded” by the standards of the time, without their will or consent.169 When this practice was challenged by a woman in a state institution in Virginia, the Supreme Court, in the 1927 case of Buck v. Bell, upheld the right of state governments to sterilize those people believed likely to have children who would become dependent upon public welfare.170 Some of these programs persisted into the 1970s, as Figure 5.22 shows.171
残疾人是公民权利得到承认的最后几个群体之一。长期以来，他们被剥夺了就业和接受公共教育的权利。许多人被送进机构。19 世纪末 20 世纪初至中期，美国的优生学运动试图鼓励非残疾人士生育，并阻止身心障碍者生育。许多州通过法律，禁止被认为具有遗传“缺陷”的人结婚。受影响的人包括盲人、聋人、癫痫患者、智力或发育障碍者以及精神疾病患者。在一些州，存在着对当时被认为是“弱智”的人进行绝育的计划，而这些人并未同意或自愿接受绝育手术 。169 当弗吉尼亚州一家州立机构中的一名妇女对这种做法提出质疑时，最高法院在 1927 年的 “巴克诉贝尔案”（Buck v. Bell） 中，维护了州政府对那些被认为可能生育依赖公共福利子女的人进行绝育的权利。 170 其中一些项目一直延续到 20 世纪 70 年代，如图 5.22 所示 。171

A map of North Carolina titled “Peak of Eugenic Program in North Carolina, July 1946-June 1968”. A legend reads “Sterilizations performed by county” and marks the counties into six categories. Seven counties are marked “10 or less”. Twenty-six counties are marked “11-29”. Twenty-five counties are marked “30-49”. Twenty-seven counties are marked “50-99”. Eleven counties are marked “100-399”. One county is marked “Over 400”.

[.my2]
Figure 5.22 The map shows the number of sterilizations performed by the state in each of the counties of North Carolina between July 1946 and June 1968. Nearly five hundred sterilizations took place during this time period in the purple county.

[.my2]
图 5.22 该地图显示了 1946 年 7 月至 1968 年 6 月期间，北卡罗来纳州各县进行的绝育手术数量。在此期间，紫色县进行了近 500 例绝育手术。
By the 1970s, however, concern for extending equal opportunities to all led to the passage of two important acts by Congress. In 1973, the Rehabilitation Act made it illegal to discriminate against people with disabilities in federal employment or in programs run by federal agencies or receiving federal funding. This was followed by the Education for all Handicapped Children Act of 1975, which required public schools to educate children with disabilities. The act specified that schools consult with parents to create a plan tailored for each child’s needs that would provide an educational experience as close as possible to that received by other children.

[.my2]
然而，到了 20 世纪 70 年代，人们对​​人人享有平等机会的关注促使国会通过了两项重要法案。1973 年，《 康复法案》 规定，联邦政府雇员或联邦机构运营或接受联邦资助的项目中歧视残疾人属于违法行为。随后，1975 年通过了 《所有残疾儿童教育法案》 ，该法案要求公立学校为残疾儿童提供教育。该法案明确规定，学校应与家长协商，为每个孩子量身定制教育计划，力求使他们获得与普通儿童尽可能接近的教育体验。

In 1990, the Americans with Disabilities Act (ADA) greatly expanded opportunities and protections for people of all ages with disabilities. It also significantly expanded the categories and definition of disability. The ADA prohibits discrimination in employment based on disability. It also requires employers to make reasonable accommodations available to workers who need them. Finally, the ADA mandates that public transportation and public accommodations be made accessible to those with disabilities. The Act was passed despite the objections of some who argued that the cost of providing accommodations would be prohibitive for small businesses. While the ADA has inarguably improved opportunities for Americans with disabilities to receive public services equally and to pursue educational opportunities, challenges continue in this space. On college campuses, disability resource centers are often slow and understaffed, causing stress for students and professors alike.172 And, in schools and colleges, full access to certain buildings and spaces remains elusive.173
1990 年，《 美国残疾人法案 》（ADA）极大地扩展了各年龄段残疾人的机会和保护范围，并显著扩大了残疾的类别和定义。ADA 禁止基于残疾的就业歧视，并要求雇主为有需要的员工提供合理的便利措施。此外，ADA 还强制要求公共交通和公共场所必须方便残疾人使用。尽管有人反对，认为提供便利措施的成本对小型企业来说过于高昂，但该法案最终还是获得通过。虽然 ADA 无疑改善了美国残疾人平等获得公共服务和接受教育的机会，但这一领域仍然面临挑战。在大学校园里，残疾人资源中心往往效率低下、人手不足，给学生和教授都带来了压力。 172 而且，在中小学和大学里，某些建筑物和场所的完全无障碍通行仍然难以实现。 173

Link to Learning  学习链接
The community of people with disabilities is well organized in the twenty-first century, as evidenced by the considerable network of disability rights organizations in the United States.

[.my2]
在二十一世纪，残疾人群体组织良好，美国庞大的残疾人权利组织网络就是最好的证明。

THE RIGHTS OF RELIGIOUS MINORITIES
宗教少数群体的权利
The right to worship as a person chooses was one of the reasons for the initial settlement of the United States. Thus, it is ironic that many people throughout U.S. history have been denied their civil rights because of their status as members of a religious minority. Beginning in the early nineteenth century with the immigration of large numbers of Irish Catholics to the United States, anti-Catholicism became a common feature of American life and remained so until the mid-twentieth century. Catholic immigrants were denied jobs, and in the 1830s and 1840s anti-Catholic literature accused Catholic priests and nuns of committing horrific acts. Anti-Mormon sentiment was also quite common, and members of the Church of Jesus Christ of Latter-day Saints were accused of kidnapping women and building armies for the purpose of dominating their neighbors. At times, these fears led to acts of violence against these religious groups. For example, a convent in Charlestown, Massachusetts, was burned to the ground in 1834.174 In 1844, Joseph Smith, the founder of the LDS Church, and his brother were murdered by a mob in Illinois.175
个人信仰自由是​​美国早期定居的原因之一。因此，具有讽刺意味的是，美国历史上许多人仅仅因为宗教少数群体身份而被剥夺了公民权利。自 19 世纪初大量爱尔兰天主教徒移民美国以来，反天主教情绪在美国社会普遍存在，并一直持续到 20 世纪中期。天主教移民被拒绝录用，在 19 世纪 30 年代和 40 年代，反天主教文献指控天主教神父和修女犯下骇人听闻的罪行。反摩门教情绪也十分普遍，耶稣基督后期圣徒教会的成员被指控绑架妇女，并组建军队以统治邻国。有时，这些恐惧甚至导致了针对这些宗教团体的暴力行为。例如，1834 年，马萨诸塞州查尔斯顿的一座修道院被烧毁。 174 1844 年，耶稣基督后期圣徒教会的创始人约瑟·史密斯和他的兄弟在伊利诺伊州被暴徒杀害。 175

For many years, Jewish Americans faced discrimination in employment, education, and housing based on their religion. Many of the restrictive real estate covenants that prohibited people from selling their homes to Black people also prohibited them from selling to Jewish people, and a “gentlemen’s agreement” among the most prestigious universities in the United States limited the number of Jewish students accepted. Indeed, a tradition of confronting discrimination led many American Jews to become actively involved in the civil rights movements for women and African Americans.176
多年来，美国犹太人因其宗教信仰在就业、教育和住房方面遭受歧视。许多限制性房地产契约不仅禁止人们将房屋出售给黑人，也禁止出售给犹太人；美国最负盛名的大学之间还存在一项“君子协定”，限制了犹太学生的录取人数。事实上，反抗歧视的传统促使许多美国犹太人积极参与到争取妇女和非裔美国人民权的运动中。 176

Anti-semitism remains a significant issue in the United States and worldwide. According to the FBI, Jewish people or property are the most frequent targets of hate crimes motivated by religious bias. Jewish cemeteries and places of worship are frequently attacked or defaced, and insensitive jokes and frequent references to the Holocaust are widely used. Muslims have also experienced a rise in discrimination and hate crimes, and most Americans, including non-Muslims, report a belief that significant anti-Muslim sentiment exists in the United States. Although Title VII of the Civil Rights Act of 1964 prevents employment discrimination on the basis of religion and requires employers to make reasonable accommodations so that employees can engage in religious rituals and practices, Muslim employees are often discriminated against. Often the source of controversy is the wearing of head coverings by observant Muslims, which some employers claim violates uniform policies or dress codes, even when non-Muslim coworkers are allowed to wear head coverings that are not part of work uniforms.177 Hate crimes against Muslims have also increased, and many Muslims believe they are subject to racial profiling by law enforcement officers who suspect them of being terrorists.178
反犹主义在美国乃至全世界仍然是一个重大问题。据联邦调查局（FBI）称，犹太人或犹太人的财产是出于宗教偏见的仇恨犯罪最常针对的目标。犹太人的墓地和宗教场所经常遭到袭击或破坏，不恰当的玩笑和对大屠杀的频繁提及也屡见不鲜。穆斯林也面临着日益严重的歧视和仇恨犯罪，大多数美国人，包括非穆斯林，都认为美国存在着严重的反穆斯林情绪。尽管 1964 年《民权法案》 第七章禁止基于宗教的就业歧视，并要求雇主做出合理安排，以便雇员能够参与宗教仪式和活动，但穆斯林雇员仍然经常受到歧视。争议的焦点往往在于虔诚的穆斯林佩戴头巾，一些雇主声称这违反了制服政策或着装规定，即使非穆斯林同事被允许佩戴非工作制服的头巾。 177 针对穆斯林的仇恨犯罪也有所增加，许多穆斯林认为他们受到执法人员的种族歧视，被怀疑是恐怖分子 。178

Many Christians have recently argued that they are being deprived of their rights because of their religious beliefs and have used this claim to justify their refusal to acknowledge the rights of others. The owner of Hobby Lobby Stores, for example, a conservative Christian, argued that his company’s health-care plan should not have to pay for contraception because his religious beliefs are opposed to the practice. In 2014, in the case of Burwell v. Hobby Lobby Stores, Inc., the Supreme Court ruled in his favor.179 As discussed earlier, many conservative Christians have also argued that they should not have to recognize same-sex marriages because they consider homosexuality to be a sin.

[.my2]
近来，许多基督徒声称，由于他们的宗教信仰，他们的权利被剥夺，并以此为由拒绝承认他人的权利。例如，Hobby Lobby Stores 的老板是一位保守的基督徒，他辩称，由于他的宗教信仰反对避孕，因此他公司的医保计划不应支付避孕费用。2014 年，在 Burwell 诉 Hobby Lobby Stores, Inc. 一案中，最高法院裁定他胜诉。 179 如前所述，许多保守的基督徒还辩称，他们不应承认同性婚姻，因为他们认为同性恋是一种罪。

'''