
= 002-5 Constitutional Change 宪法变更
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义



Along with African Americans, women of all races and ethnicities have long been discriminated against in the United States, and the women’s rights movement began at the same time as the movement to abolish slavery in the United States. Indeed, the women’s movement came about largely as a result of the difficulties women encountered while trying to abolish slavery. The trailblazing Seneca Falls Convention for women’s rights was held in 1848, a few years before the Civil War. But the abolition and African American civil rights movements largely eclipsed the women’s movement throughout most of the nineteenth century. Women began to campaign actively again in the late nineteenth and early twentieth centuries, and another movement for women’s rights began in the 1960s.

[.my2]
与非裔美国人一样，美国各族裔的女性长期以来都遭受歧视。妇女权利运动与美国废奴运动几乎同时兴起。事实上，妇女运动的出现很大程度上源于女性在废奴运动中遇到的重重困难。具有里程碑意义的妇女权利会议于 1848 年召开，即南北战争爆发前几年。然而，在 19 世纪的大部分时间里，废奴运动和非裔美国人民权运动的光芒掩盖了妇女运动。直到 19 世纪末 20 世纪初，女性才再次积极投身于争取权益的运动，而另一场妇女权利运动则始于 20 世纪 60 年代。

THE EARLY WOMEN’S RIGHTS MOVEMENT AND WOMEN’S SUFFRAGE
早期妇女权利运动和妇女选举权
At the time of the American Revolution, women had few rights. Although single women were allowed to own property, married women were not. When women married, their separate legal identities were erased under the legal principle of coverture. Not only did women adopt their husbands’ names, but all personal property they owned legally became their husbands’ property. Husbands could not sell their wives’ real property—such as land or in some states enslaved people—without their permission, but they were allowed to manage it and retain the profits. If women worked outside the home, their husbands were entitled to their wages.62 So long as a man provided food, clothing, and shelter for his wife, she was not legally allowed to leave him. Divorce was difficult and in some places impossible to obtain.63 Higher education for women was not available, and women were barred from professional positions in medicine, law, and ministry.

[.my2]
美国革命时期，女性的权利寥寥无几。虽然单身女性可以拥有财产，但已婚女性却没有。女性结婚后，根据“夫妻共同财产制”（coverture） 的法律原则，她们的独立法律身份被抹去。女性不仅要随夫姓，而且她们拥有的所有个人财产也都归丈夫所有 。丈夫未经妻子许可不得出售妻子的不动产——例如土地，在某些州甚至包括奴隶——但可以管理这些财产并保留收益。如果女性外出工作，她们的工资归丈夫所有 。只要丈夫为妻子提供食物、衣物和住所，妻子就无权离开他。离婚十分困难，在某些地方甚至根本无法实现。女性无法接受高等教育，也被禁止从事医学、法律和宗教等专业工作。

Following the Revolution, women’s conditions did not improve. Women were not granted the right to vote by any of the states except New Jersey, which at first allowed all taxpaying property owners to vote. However, in 1807, the law changed to limit the vote to men.64 Changes in property laws actually hurt women by making it easier for their husbands to sell their real property without their consent.

[.my2]
美国独立战争后，女性的境况并未改善。除新泽西州外，其他各州均未赋予女性投票权。新泽西州最初允许所有纳税的财产所有者投票，但 1807 年，法律修改，将投票权限制在男性。64 财产法的修改实际上损害了女性的利益 ， 因为这使得她们的丈夫更容易在未经她们同意的情况下出售她们的房产。

Although women had few rights, they nevertheless played an important role in transforming American society. This was especially true in the 1830s and 1840s, a time when numerous social reform movements swept across the United States. In 1832, for example, African American writer and activist Maria W. Stewart became the first American-born woman to give a speech to a mixed audience. While there was racism within the suffrage movement, including calls for segregated marches and a lack of scrutiny on the topic of lynchings, many women were active in the abolition movement and the temperance movement, which tried to end the excessive consumption of liquor.65 They often found they were hindered in their efforts, however, either by the law or by widely held beliefs that they were weak, silly creatures who should leave important issues to men.66 One of the leaders of the early women’s movement, Elizabeth Cady Stanton (Figure 5.11), was shocked and angered when she sought to attend an 1840 antislavery meeting in London, only to learn that women would not be allowed to participate and had to sit apart from the men. At this convention, she made the acquaintance of another American woman abolitionist, Lucretia Mott (Figure 5.11), who was also appalled by the male reformers’ treatment of women.67
尽管女性的权利寥寥无几，但她们在美国社会转型中仍然发挥了重要作用。尤其是在 19 世纪 30 年代和 40 年代，当时众多社会改革运动席卷美国。例如，1832 年，非裔美国作家和活动家玛丽亚·W·斯图尔特成为第一位向男女混合听众发表演讲的美国本土女性。尽管妇女参政权运动内部存在种族主义，例如呼吁举行种族隔离的游行以及对私刑问题缺乏审查，但许多女性积极参与废奴运动和禁酒运动，试图遏制过度饮酒的风气。 然而， 她们常常发现自己的努力受到阻碍，要么是受到法律的限制，要么是受到普遍存在的观念的束缚，认为她们软弱无能，应该把重要的事情留给男人。 66 早期妇女运动的领袖之一伊丽莎白·凯迪· 斯坦顿 （ 图 5.11 ）在试图参加 1840 年在伦敦举行的一次废奴会议时，却得知女性不被允许参加，必须与男性分开就座，这令她感到震惊和愤怒。在这次大会上，她结识了另一位美国废奴主义女性卢克丽霞· 莫特 （ 图 5.11 ），莫特也对男性改革者对待女性的方式感到愤慨 。67

Image A is of Elizabeth Cady Stanton with her arms around two children who are seated on her lap. Image B is of Lucretia Mott standing with arms crossed.

[.my2]
Figure 5.11 Elizabeth Cady Stanton (a) and Lucretia Mott (b) both emerged from the abolitionist movement as strong advocates of women’s rights.

[.my2]
图 5.11 伊丽莎白·凯迪·斯坦顿 (a) 和卢克丽霞·莫特 (b) 都从废奴运动中脱颖而出，成为妇女权利的坚定倡导者。
In 1848, Stanton and Mott called for a women’s rights convention, the first ever held specifically to address the subject, at Seneca Falls, New York. At the Seneca Falls Convention, Stanton wrote the Declaration of Sentiments, which was modeled after the Declaration of Independence and proclaimed women were equal to men and deserved the same rights. Among the rights Stanton wished to see granted to women was suffrage, the right to vote. When called upon to sign the Declaration, many of the delegates feared that if women demanded the right to vote, the movement would be considered too radical and its members would become a laughingstock. The Declaration passed, but the resolution demanding suffrage was the only one that did not pass unanimously.68
1848 年，斯坦顿和莫特在纽约州塞内卡福尔斯召开了第一次专门讨论妇女权利问题的大会。在塞内卡福尔斯大会上，斯坦顿撰写了《情感宣言》，该宣言以《独立宣言》为蓝本，宣称女性与男性平等，理应享有同等权利。斯坦顿希望赋予女性的权利之一是选举权， 即投票权。当被要求签署宣言时，许多代表担心，如果女性要求获得选举权，这场运动将被视为过于激进，其成员将沦为笑柄。宣言最终获得通过，但要求选举权的决议是唯一一项未能获得全票通过的决议。 68

Along with other feminists (advocates of women’s equality), such as her friend and colleague Susan B. Anthony, Stanton fought for rights for women besides suffrage, including the right to seek higher education. As a result of their efforts, several states passed laws that allowed married women to retain control of their property and let divorced women keep custody of their children.69 Amelia Bloomer, another activist, also campaigned for dress reform, believing women could lead better lives and be more useful to society if they were not restricted by voluminous heavy skirts and tight corsets.

[.my2]
与她的朋友和同事苏珊·B· 安东尼等其他女权主义者（女性平等的倡导者）一样，斯坦顿除了争取选举权外，还为女性争取其他权利，包括接受高等教育的权利。在她们的努力下，一些州通过了法律，允许已婚妇女保留对其财产的控制权，并允许离婚妇女获得子女的监护权。 另一位活动家阿米莉亚· 布卢默也积极推动服装改革，她认为，如果女性不再受臃肿厚重的裙子和紧身胸衣的束缚，她们就能拥有更好的生活，也能为社会做出更大的贡献。

The women’s rights movement attracted many women who, like Stanton and Anthony, were active in either the temperance movement, the abolition movement, or both movements. Sarah and Angelina Grimke, the daughters of a wealthy slaveholding family in South Carolina, became first abolitionists and then women’s rights activists.70 Prominent Black and formerly enslaved women such as Sojourner Truth, Frances Ellen Watkins Harper, and Mary Anne Shadd Cary joined the women's movement after establishing themselves as key figures in the abolition movement. These women were known for direct, unorthodox, and effective arguments for the suffragist cause. Truth's "Ain't I A Woman" speech is among the most well known of the movement, and Cary, a lawyer, delivered a critical equality argument before the Senate Judiciary Committee..

[.my2]
妇女权利运动吸引了许多女性，她们像斯坦顿和安东尼一样，积极参与禁酒运动、废奴运动或两者兼而有之。萨拉和安吉丽娜· 格里姆克是南卡罗来纳州一个富裕的奴隶主家庭的女儿，她们先是成为废奴主义者，后来又成为妇女权利活动家。索杰纳·特鲁斯、弗朗西丝·艾伦·沃特金斯·哈珀和玛丽·安妮·沙德·凯里等 70 位杰出的黑人女性和前奴隶，在废奴运动中确立了自己关键人物的地位后，加入了妇女运动。这些女性以直率、非正统且有效的论证而闻名，她们为妇女参政权事业奔走呼吁。特鲁斯的《我可不是爱荷华州的女人》演讲是该运动中最著名的演讲之一，而身为律师的凯里则在参议院司法委员会发表了重要的平等论证。

Following the Civil War and the abolition of slavery, the women’s rights movement fragmented. Stanton and Anthony denounced the Fifteenth Amendment because it granted voting rights only to Black men and not to women of any race.71 The fight for women’s rights did not die, however. In 1869, Stanton and Anthony formed the National Woman Suffrage Association (NWSA), which demanded that the Constitution be amended to grant the right to vote to all women. It also called for more lenient divorce laws and an end to sex discrimination in employment. The less radical Lucy Stone formed the American Woman Suffrage Association (AWSA) in the same year; AWSA hoped to win the suffrage for women by working on a state-by-state basis instead of seeking to amend the Constitution.72 Four western states—Utah, Colorado, Wyoming, and Idaho—did extend the right to vote to women in the late nineteenth century, but no other states did.

[.my2]
内战结束后，随着奴隶制的废除，妇女权利运动出现了分裂。斯坦顿和安东尼谴责第十五修正案，因为该修正案只赋予黑人男性投票权，而没有赋予任何种族的女性投票权。 71 然而，争取妇女权利的斗争并未就此结束。1869 年，斯坦顿和安东尼成立了全国妇女选举权协会 （NWSA），该协会要求修改宪法，赋予所有女性投票权。该协会还呼吁放宽离婚法，并结束就业中的性别歧视。同年，立场较为温和的露西 ·斯通成立了美国妇女选举权协会 （AWSA）；AWSA 希望通过逐州推进的方式，而不是寻求修改宪法，来赢得妇女的选举权。 72 19 世纪后期，犹他州、科罗拉多州、怀俄明州和爱达荷州这四个西部州赋予了女性投票权，但其他州并未效仿。

Women were also granted the right to vote on matters involving liquor licenses, in school board elections, and in municipal elections in several states. However, this was often done because of stereotyped beliefs that associated women with moral reform and concern for children, not as a result of a belief in women’s equality. Furthermore, voting in municipal elections was restricted to women who owned property.73 In 1890, the two suffragist groups united to form the National American Woman Suffrage Association (NAWSA). To call attention to their cause, members circulated petitions, lobbied politicians, and held parades in which hundreds of women and girls marched through the streets (Figure 5.12).

[.my2]
在一些州，女性也被赋予了在酒类许可证、学校董事会选举和市政选举中投票的权利。然而，这往往是出于对女性平等的信念，而非出于对女性平等的认同，而是源于将女性与道德改革和关爱儿童联系起来的刻板印象。此外，市政选举的投票权仅限于拥有财产的女性。 73 1890 年，两个妇女参政权运动团体联合成立了全国美国妇女参政权协会 （NAWSA）。为了引起公众对她们事业的关注，协会成员们散发请愿书，游说政客，并举行游行，数百名妇女和女孩走上街头（ 图 5.12 ）。

An image of a group of people marching down a street. Several pairs of people are carrying large signs between them. On both sides of the street is a crowd of observers.

[.my2]
Figure 5.12 In October 1917, suffragists marched down Fifth Avenue in New York demanding the right to vote. They carried a petition that had been signed by one million women.

[.my2]
图 5.12 1917 年 10 月，妇女参政论者在纽约第五大道游行，要求获得投票权。她们携带了一份由一百万名妇女签名的请愿书。
The more radical National Woman’s Party (NWP), led by Alice Paul, advocated the use of stronger tactics. The NWP held public protests and picketed outside the White House (Figure 5.13).74 Demonstrators were often beaten and arrested, and suffragists were subjected to cruel treatment in jail. When some, like Paul, began hunger strikes to call attention to their cause, their jailers force-fed them, an incredibly painful and invasive experience for the women.75 Finally, in 1920, the triumphant passage of the Nineteenth Amendment granted all women the right to vote.

[.my2]
由爱丽丝· 保罗领导的更为激进的全国妇女党 （NWP）主张采取更强硬的策略。NWP 举行公开抗议活动，并在白宫外进行纠察（ 图 5.13 ）。 74 示威者经常遭到殴打和逮捕，妇女参政论者在狱中遭受残酷对待。当一些人，例如保罗，开始绝食以引起人们对她们事业的关注时，狱卒强迫她们进食，这对这些女性来说是极其痛苦和侵犯性的经历。 75 最终，在 1920 年， 第十九修正案的胜利通过赋予了所有女性投票权。

An image of several people standing in front of a fence. Some people are holding banners. The banners read “Mr. President how long must women wait for liberty” and “Mr. President what will you do for woman sufferage”.

[.my2]
Figure 5.13 Members of the National Woman’s Party picketed outside the White House six days a week from January 10, 1917, when President Woodrow Wilson took office, until June 4, 1919, when the Nineteenth Amendment was passed by Congress. The protesters wore banners proclaiming the name of the institution of higher learning they attended.

[.my2]
图 5.13 从 1917 年 1 月 10 日伍德罗·威尔逊总统就职开始，到 1919 年 6 月 4 日国会通过第十九修正案为止，全国妇女党的成员每周六天在白宫外进行纠察示威。抗议者们佩戴着横幅，上面写着她们就读的高等学府的名称。
CIVIL RIGHTS AND THE EQUAL RIGHTS AMENDMENT
公民权利与平等权利修正案
Just as the passage of the Thirteenth, Fourteenth, and Fifteenth Amendments did not result in equality for African Americans, the Nineteenth Amendment did not end discrimination against women in education, employment, or other areas of life, which continued to be legal. Although women could vote, they very rarely ran for or held public office. Women continued to be underrepresented in the professions, and relatively few sought advanced degrees. Until the mid-twentieth century, the ideal in U.S. society was typically for women to marry, have children, and become housewives. Those who sought work for pay outside the home were routinely denied jobs because of their sex and, when they did find employment, were paid less than men. Women who wished to remain childless or limit the number of children they had in order to work or attend college found it difficult to do so. In some states it was illegal to sell contraceptive devices, and abortions were largely illegal and difficult for women to obtain.

[.my2]
正如第十三、十四和十五修正案的通过并未给非裔美国人带来平等权利一样，第十九修正案也未能终结女性在教育、就业或其他生活领域遭受的歧视，这些歧视依然合法。尽管女性拥有投票权，但她们极少竞选或担任公职。女性在各行各业的代表性仍然不足，攻读高等学位的女性也相对较少。直到二十世纪中期，美国社会普遍认为女性的理想是结婚、生育并成为家庭主妇。那些寻求外出工作的女性常常因为性别而被拒之门外，即使找到工作，她们的收入也低于男性。那些希望不生育或为了工作或上大学而限制生育的女性发现，这非常困难。在一些州，出售避孕用品是非法的，堕胎在很大程度上也是非法的，女性很难获得堕胎服务。

A second women’s rights movement emerged in the 1960s to address these problems. Title VII of the Civil Rights Act of 1964 prohibited discrimination in employment on the basis of sex as well as race, color, national origin, and religion. Nevertheless, women continued to be denied jobs because of their sex and were often sexually harassed at the workplace. In 1966, feminists who were angered by the lack of progress made by women and by the government’s lackluster enforcement of Title VII organized the National Organization for Women (NOW). NOW promoted workplace equality, including equal pay for women, and also called for the greater presence of women in public office, the professions, and graduate and professional degree programs.

[.my2]
20 世纪 60 年代，第二次妇女权利运动兴起，旨在解决这些问题。1964 年 《民权法案》 第七章禁止在就业方面基于性别、种族、肤色、国籍和宗教进行歧视。然而，女性仍然因为性别而被剥夺工作机会，并且经常在工作场所遭受性骚扰。1966 年，一些女权主义者对女性权利的缺乏进展以及政府对第七章执行不力感到愤怒，她们组织成立了全国妇女组织 （NOW）。NOW 倡导职场平等，包括男女同工同酬，并呼吁提高女性在公职、专业领域以及研究生和专业学位课程中的参与度。

NOW also declared its support for the Equal Rights Amendment (ERA), which mandated equal treatment for all regardless of sex. The ERA, written by Alice Paul and Crystal Eastman, was first proposed to Congress, unsuccessfully, in 1923. It was introduced in every Congress thereafter but did not pass both the House and the Senate until 1972. The amendment was then sent to the states for ratification with a deadline of March 22, 1979. Although many states ratified the amendment in 1972 and 1973, the ERA still lacked sufficient support as the deadline drew near. Opponents, including both women and men, argued that passage would subject women to military conscription and deny them alimony and custody of their children should they divorce.76 In 1978, Congress voted to extend the deadline for ratification to June 30, 1982. Even with the extension, however, the amendment failed to receive the support of the required thirty-eight states; by the time the deadline arrived, it had been ratified by only thirty-five, some of those had rescinded their ratifications, and no new state had ratified the ERA during the extension period (Figure 5.14). In 2020, Virginia became the thirty-eighth state to ratify, though well after the deadline. That led the U.S. House of Representatives to consider and pass legislation to remove the original deadlines. However, the Senate did not take up the legislation. In 2021, Senator Lisa Murkowski (R-AK) and Senator Ben Cardin (D-MD) introduced a new joint resolution to remove the deadline. That resolution has yet to be taken up by the Senate.77
全国妇女组织（NOW）也宣布支持《 平等权利修正案 》（ERA） ，该修正案规定所有人无论性别都应受到平等对待。ERA 由爱丽丝 ·保罗和克里斯特尔· 伊斯特曼起草，最初于 1923 年提交国会，但未获通过。此后，每届国会都提出了该修正案，但直到 1972 年才在众议院和参议院获得通过。该修正案随后被送交各州批准，截止日期为 1979 年 3 月 22 日。尽管许多州在 1972 年和 1973 年批准了该修正案，但随着截止日期的临近，ERA 仍然缺乏足够的支持。反对者，包括男性和女性，认为该修正案的通过将使女性被迫服兵役，并在离婚时剥夺她们的赡养费和子女监护权。76 1978 年，国会投票将批准截止日期延长至 1982 年 6 月 30 日。然而，即使延期，该修正案仍然未能获得所需的 38 个州的支持。到最后期限时，只有 35 个州批准了《平等权利修正案》，其中一些州撤回了批准，而且在延期期间没有新的州批准该修正案（ 图 5.14 ）。2020 年，弗吉尼亚州成为第 38 个批准该修正案的州，尽管此时已远远超过最后期限。这促使美国众议院考虑并通过了一项法案，取消原有的最后期限。然而，参议院并未审议该法案。2021 年，阿拉斯加州共和党参议员丽莎·穆尔科斯基和马里兰州民主党参议员本·卡丁提出了一项新的联合决议，旨在取消最后期限。该决议至今尚未提交参议院审议 。77

A map of the United States titled “State Support of the Equal Rights Amendment”. States marked as “Ratified” are Washington, Oregon, California, Alaska, Hawaii, Montana, Wyoming, Colorado, New Mexico, North Dakota, Kansas, Texas, Minnesota, Iowa, Wisconsin, Michigan, Indiana, Ohio, West Virginia, Virginia, Maryland, Pennsylvania, Delaware, New Jersey, New York, Connecticut, Rhode Island, Massachusetts, New Hampshire, Maine, and Vermont. States marked as “Ratified, then rescinded” are Idaho, South Dakota, Nebraska, Kentucky, and Tennessee. States marked as “Ratified in one house of legislature” are Nevada, Oklahoma, Missouri, Illinois, Louisiana, Florida, South Carolina, and North Carolina. States marked as “Not ratified” are Utah, Arizona, Arkansas, Mississippi, Alabama, and Georgia.

[.my2]
Figure 5.14 The map shows which states supported the ERA and which did not. The dark blue states ratified the amendment. The amendment was ratified but later rescinded in the light blue states and was ratified in only one branch of the legislature in the yellow states. The ERA was never ratified by the purple states. In 2020, Virginia voted to ratify the amendment, becoming the thirty-eighth state to do so. However, it was well past the deadline.

[.my2]
图 5.14 地图显示了哪些州支持《平等权利修正案》（ERA），哪些州不支持。深蓝色州批准了该修正案。浅蓝色州批准了该修正案，但后来又撤销了；黄色州仅在立法机构的一个分支中批准了该修正案。紫色州从未批准过该修正案。2020 年，弗吉尼亚州投票批准了该修正案，成为第 38 个批准该修正案的州。然而，此时已远远超过了截止日期。
Although the ERA failed to be ratified, Title IX of the United States Education Amendments of 1972 passed into law as a federal statute (not as an amendment, as the ERA was meant to be). Title IX applies to all educational institutions that receive federal aid and prohibits discrimination on the basis of sex in academic programs, dormitory space, health-care access, and school activities including sports. Thus, if a school receives federal aid, it cannot spend more funds on programs for men than on programs for women.

[.my2]
尽管《平等权利修正案》（ERA）未能获得批准，但 1972 年美国教育修正案第九条（Title IX） 作为联邦法规正式生效（而非像 ERA 原本设想的那样作为修正案）。第九条适用于所有接受联邦资助的教育机构，禁止在学术项目、宿舍、医疗保健以及包括体育运动在内的学校活动方面存在基于性别的歧视。因此，如果一所学校接受联邦资助，则其用于男生项目的资金不得多于用于女生项目的资金。

CONTINUING CHALLENGES FOR WOMEN
女性面临的持续挑战
There is no doubt that women have made great progress since the Seneca Falls Convention. Today, more women than men attend college, and they are more likely than men to graduate.78 Women are represented in all the professions, and approximately half of all law and medical school students are women.79 Women have held Cabinet positions and have been elected to Congress. They have run for president and vice president, and four female justices currently serve on the Supreme Court. Women are also represented in all branches of the military and can serve in combat.

[.my2]
毫无疑问，自塞内卡福尔斯会议以来，女性取得了巨大的进步。如今，女性上大学的人数超过男性，而且她们的毕业率也高于男性。78 女性在各行各业都有代表，大约一半的法学院和医学院学生是女性。79 女性曾担任内阁职务，也曾当选国会议员。她们竞选过总统和副总统，目前最高法院有四位女性大法官。女性在军队的各个分支都有代表，并且可以参加战斗。

While women's rights have progressed well beyond where they were in the 1800s, questions of equity continue. In 2021, the massive disparities between the facilities and housing for men and women in their respective NCAA national tournaments became front page news.80 Also in the news recently were the disparities in pay and resources for the U.S. Men's and Women's National Soccer teams. Again, women received much less in terms of resources than men, despite (in this case) being the more successful international team and World Cup champions.81 In the business world, women are still underrepresented in some jobs and are less likely to hold executive positions than are men.

[.my2]
尽管女性权利已远超 19 世纪的水平，但公平问题依然存在。2021 年，NCAA 全国锦标赛中男女运动员在设施和住宿方面的巨大差异成为头条新闻。 80 近期，美国男女国家足球队在薪酬和资源方面的差距也引起了广泛关注。尽管女足（在本例中）是更成功的国际球队，并赢得了世界杯冠军，但她们获得的资源却远少于男足。 81 在商界，女性在某些职位上的比例仍然偏低，担任高管职位的可能性也低于男性。

Many believe the glass ceiling, an invisible barrier caused by discrimination, prevents women from rising to the highest levels of American organizations, including corporations, governments, academic institutions, and religious groups. Women earn less money than men for the same work. As of 2014, fully employed women earned seventy-nine cents for every dollar earned by a fully employed man.82 This problem may be compounded by other factors, as women from under-represented groups are even more discriminated against than other women.83 Women are also more likely to be single parents than are men.84 As a result, more women live below the poverty line than do men, and, as of 2012, households headed by single women are twice as likely to live below the poverty line than those headed by single men.85 Women remain underrepresented in elective offices. As of June 2021, women held only about 27 percent of seats in Congress and only about 31 percent of seats in state legislatures.86
许多人认为， 玻璃天花板 ——一种由歧视造成的无形障碍——阻碍了女性晋升到美国各组织（包括企业、政府、学术机构和宗教团体）的最高层。女性从事同样的工作，收入却低于男性。截至 2014 年，全职女性的收入仅为全职男性收入的 79%。 82 其他因素可能会加剧这个问题，因为来自弱势群体的女性比其他女性遭受的歧视更为严重。 83 女性成为单亲父母的可能性也高于男性。 84 因此，生活在贫困线以下的女性人数多于男性，而且，截至 2012 年，单身女性户主家庭生活在贫困线以下的可能性是单身男性户主家庭的两倍。 85 女性在民选职位中的代表性仍然不足。截至 2021 年 6 月，女性在国会中仅占约 27%的席位，在州议会中仅占约 31%的席位。 86

Women remain subject to sexual harassment in the workplace and are more likely than men to be the victims of domestic violence. Approximately one-third of all women have experienced domestic violence; one in five women is assaulted during her college years.87
女性在职场中仍然容易遭受性骚扰，而且比男性更容易成为家庭暴力的受害者。大约三分之一的女性曾遭受过家庭暴力；五分之一的女性在大学期间遭受过性侵犯 。87

Many in the United States continue to call for a ban on abortion, and states have attempted to restrict women’s access to the procedure. For example, many states have required abortion clinics to meet the same standards set for hospitals, such as corridor size and parking lot capacity, despite lack of evidence regarding the benefits of such standards. Abortion clinics, which are smaller than hospitals, often cannot meet such standards. Other restrictions include mandated counseling before the procedure and the need for minors to secure parental permission before obtaining abortion services.88 Whole Woman’s Health v. Hellerstedt (2016) cited the lack of evidence for the benefit of larger clinics and further disallowed two Texas laws that imposed special requirements on doctors in order to perform abortions.89 Furthermore, the federal government will not pay for abortions for low-income women except in cases of rape or incest or in situations in which carrying the fetus to term would endanger the life of the mother.90
在美国，许多人继续呼吁禁止堕胎 ，各州也试图限制女性获得堕胎手术的途径。例如，许多州要求堕胎诊所达到与医院相同的标准，例如走廊大小和停车场容量，尽管缺乏证据表明这些标准有益。堕胎诊所的规模通常小于医院，因此往往无法达到这些标准。其他限制还包括强制要求在手术前进行咨询，以及未成年人在接受堕胎服务前必须获得父母许可 。88 “全女性健康诉赫勒斯泰特案” （2016 年）指出，缺乏证据表明大型诊所的益处 ，并进一步驳回了德克萨斯州的两项法律，这两项法律对医生实施堕胎手术施加了特殊要求。89 此外，联邦政府不会为低收入女性支付堕胎费用，除非是强奸或乱伦导致的怀孕，或者妊娠至足月会危及母亲生命的情况 。90

To address these issues, many have called for additional protections for women. These include laws mandating equal pay for equal work. According to the doctrine of comparable worth, people should be compensated equally for work requiring comparable skills, responsibilities, and effort. Thus, even though women are underrepresented in certain fields, they should receive the same wages as men if performing jobs requiring the same level of accountability, knowledge, skills, and/or working conditions, even though the specific job may be different.

[.my2]
为了解决这些问题，许多人呼吁加强对女性的保护，包括制定同工同酬的法律。根据 “同等价值原则”，人们应该因从事技能、责任和付出相当的工作而获得同等报酬。因此，即使女性在某些领域人数较少，但如果她们从事的工作需要同等的责任、知识、技能和/或工作条件，即使具体工作内容有所不同，她们也应该获得与男性相同的工资。

For example, garbage collectors are predominantly male. The chief job requirements are the ability to drive a sanitation truck and to lift heavy bins and toss their contents into the back of truck. The average wage for a garbage collector is $15.34 an hour.91 Most people employed as daycare workers are female, and the average pay is $9.12 an hour.92 However, the work arguably requires more skills and is a more responsible position. Daycare workers must be able to feed, clean, and dress small children; prepare meals for them; entertain them; give them medicine if required; and teach them basic skills. They must be educated in first aid and assume responsibility for the children’s safety. In terms of the skills and physical activity required and the associated level of responsibility of the job, daycare workers should be paid at least as much as garbage collectors and perhaps more. Women’s rights advocates also call for stricter enforcement of laws prohibiting sexual harassment, and for harsher punishment, such as mandatory arrest, for perpetrators of domestic violence.

[.my2]
例如，垃圾收集员大多是男性。这项工作的主要要求是能够驾驶垃圾车，并能搬运沉重的垃圾桶，将里面的垃圾倒入车厢。垃圾收集员的平均时薪为 15.34 美元。 91 大多数托儿所工作人员是女性，平均时薪为 9.12 美元。 92 然而，这项工作无疑需要更高的技能，责任也更大。托儿所工作人员必须能够喂养、清洁和穿衣幼儿；为他们准备饭菜；陪伴他们玩耍；必要时给他们喂药；并教他们一些基本技能。他们必须接受过急救培训，并承担起保障儿童安全的责任。考虑到所需的技能、体力活动以及相关的责任程度，托儿所工作人员的工资至少应该与垃圾收集员持平，甚至更高。妇女权益倡导者还呼吁更严格地执行禁止性骚扰的法律，并对家庭暴力施暴者处以更严厉的惩罚，例如强制逮捕。

Insider Perspective  内部视角
Harry Burn and the Tennessee General Assembly
哈里·伯恩与田纳西州议会
In 1918, the proposed Nineteenth Amendment to the Constitution, extending the right to vote to all adult female citizens of the United States, was passed by both houses of Congress and sent to the states for ratification. Thirty-six votes were needed. Throughout 1918 and 1919, the Amendment dragged through legislature after legislature as pro- and anti-suffrage advocates made their arguments. By the summer of 1920, only one more state had to ratify it before it became law. The Amendment passed through Tennessee’s state Senate and went to its House of Representatives. Arguments were bitter and intense. Pro-suffrage advocates argued that the amendment would reward women for their service to the nation during World War I and that women’s supposedly greater morality would help to clean up politics. Those opposed claimed women would be degraded by entrance into the political arena and that their interests were already represented by their male relatives. On August 18, the amendment was brought for a vote before the House. The vote was closely divided, and it seemed unlikely it would pass. But as a young anti-suffrage representative waited for his vote to be counted, he remembered a note he had received from his mother that day. In it, she urged him, “Hurrah and vote for suffrage!” At the last minute, Harry Burn abruptly changed his ballot. The amendment passed the House by one vote, and eight days later, the Nineteenth Amendment was added to the Constitution.

[.my2]
1918 年，旨在赋予所有美国成年女性公民投票权的宪法第十九修正案提案获得国会两院通过，并提交各州批准。该修正案需要 36 票才能生效。在 1918 年和 1919 年，支持和反对女性参政权的双方各执一词，修正案在各州议会中艰难推进。到 1920 年夏天，只需再获得一个州的批准，该修正案即可正式成为法律。该修正案在田纳西州参议院获得通过，随后提交众议院审议。双方的争论异常激烈。支持女性参政权的人士认为，该修正案是对女性在第一次世界大战期间为国家做出贡献的奖励，而且女性更高的道德标准有助于净化政治。反对者则声称，女性进入政治舞台会降低其地位，而且她们的利益已经由男性亲属代表。 8 月 18 日，该修正案提交众议院表决。投票结果势均力敌，似乎难以通过。然而，一位年轻的反对妇女参政权的众议员在等待计票时，突然想起当天收到母亲的一张纸条。纸条上，母亲鼓励他：“加油，投赞成票！”在最后一刻，哈里· 伯恩突然改变了主意。最终，该修正案以一票之差在众议院获得通过。八天后，第十九修正案正式写入宪法。

How are women perceived in politics today compared to the 1910s? What were the competing arguments for Harry Burn’s vote?
与 1910 年代相比，当今女性在政治中的地位有何不同？当时支持哈里·伯恩斯投票的理由有哪些？

Link to Learning  学习链接
The website for the Women’s National History Project contains a variety of resources for learning more about the women’s rights movement and women’s history. It features a history of the women’s movement, a “This Day in Women’s History” page, and quizzes to test your knowledge.

[.my2]
妇女国家历史项目网站包含各种资源，可帮助人们了解更多关于妇女权利运动和妇女历史的信息。网站内容包括妇女运动史、“妇女历史上的今天”页面以及测试知识的测验。


'''