
= 006 The Politics of Public Opinion 公共舆论政治
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


On November 7, 2012, the day after the presidential election, journalists found Mitt Romney’s transition website, detailing the Republican candidate’s plans for the upcoming inauguration celebration and criteria for Cabinet and White House appointees and leaving space for video of his acceptance speech.1 Yet, Romney had lost his bid for the White House. In fact, Romney’s campaign staff had been so sure he would win that he had not written a concession speech. How could they have been wrong? Romney’s staff blamed the campaign’s own polls. Believing Republican voters to be highly motivated, Romney pollsters had overestimated how many would turn out (Figure 6.1).2 The campaign’s polls showed Romney close to President Barack Obama, although non-campaign polls showed Obama ahead.3 On election night, Romney gave his hastily drafted concession speech, still unsure how he had lost.

[.my2]
2012 年 11 月 7 日，总统大选后的第二天，记者们发现了米特·罗姆尼的过渡网站，网站上详细列出了这位共和党候选人即将举行的就职典礼的计划、内阁和白宫任命的标准，并预留了播放他接受提名演讲视频的空间。 然而 ， 罗姆尼却落选了。事实上，罗姆尼的竞选团队对他胜选信心十足，甚至没有准备败选演讲稿。他们怎么会出错呢？罗姆尼的团队将失败归咎于竞选团队自身的民调。民调人员认为共和党选民的投票积极性很高，因此高估了投票人数（ 图 6.1 ）。竞选团队的民调显示罗姆尼的支持率与奥巴马总统接近，但非竞选机构的民调却显示奥巴马领先。在选举之夜， 罗姆尼发表了仓促起草的败选演讲稿，仍然不明白自己为何会落败。

In the 2016 election, most polls showed Democratic nominee Hillary Clinton with an advantage nationwide and in the battleground states in the days leading up to the election. However, Republican nominee Donald Trump was elected president as many new voters joined the process, voters who were not studied in the polls as likely voters. Again in 2024, as Trump again sought the presidency, polls showed a very close race ahead of election day, yet Trump won every swing state, some narrowly, to again take the White House. As many a disappointed candidate knows, public opinion matters. The way opinions are formed and the way we measure public opinion also matter. But how much, and why? These are some of the questions we’ll explore in this chapter.

[.my2]
2016年大选前，大多数民调显示民主党候选人希拉里·克林顿在全国范围内以及关键摇摆州都占据优势。然而，由于大量新选民的加入——这些选民并未在民调中被视为潜在选民——共和党候选人唐纳德·特朗普最终当选总统。2024年，特朗普再次竞选总统，民调显示选情胶着，但特朗普最终赢得了所有摇摆州，其中一些州的胜利也十分微弱，他再次入主白宫。正如许多竞选失败的候选人所体会到的，民意至关重要。民意的形成方式以及我们衡量民意的方式同样重要。但究竟有多重要？为什么？这些正是我们将在本章探讨的问题。

'''

== pure

Figure 6.1 Governor and presidential candidate Mitt Romney takes the stage in Boston, Massachusetts, to give his “Super Tuesday” victory speech. On the eve of the 2012 election, he hoped to repeat the performance, since campaign polls showed he was ahead, but non-campaign polls told a different story. (credit: modification of work by BU Interactive News/Flickr)

Chapter Outline

- 6.1 The Nature of Public Opinion
- 6.2 How Is Public Opinion Measured?
- 6.3 What Does the Public Think?
- 6.4 The Effects of Public Opinion

On November 7, 2012, the day after the presidential election, journalists found Mitt Romney’s transition website, detailing the Republican candidate’s plans for the upcoming inauguration celebration and criteria for Cabinet and White House appointees and leaving space for video of his acceptance speech.1 Yet, Romney had lost his bid for the White House. In fact, Romney’s campaign staff had been so sure he would win that he had not written a concession speech. How could they have been wrong? Romney’s staff blamed the campaign’s own polls. Believing Republican voters to be highly motivated, Romney pollsters had overestimated how many would turn out (Figure 6.1).2 The campaign’s polls showed Romney close to President Barack Obama, although non-campaign polls showed Obama ahead.3 On election night, Romney gave his hastily drafted concession speech, still unsure how he had lost.

In the 2016 election, most polls showed Democratic nominee Hillary Clinton with an advantage nationwide and in the battleground states in the days leading up to the election. However, Republican nominee Donald Trump was elected president as many new voters joined the process, voters who were not studied in the polls as likely voters. Again in 2024, as Trump again sought the presidency, polls showed a very close race ahead of election day, yet Trump won every swing state, some narrowly, to again take the White House. As many a disappointed candidate knows, public opinion matters. The way opinions are formed and the way we measure public opinion also matter. But how much, and why? These are some of the questions we’ll explore in this chapter.

'''