
= 007-4 Campaigns and Voting 竞选活动和投票
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





Campaign managers know that to win an election, they must do two things: reach voters with their candidate’s information and get voters to show up at the polls. To accomplish these goals, candidates and their campaigns will often try to target those most likely to vote. Unfortunately, these voters change from election to election and sometimes from year to year. Primary and caucus voters are different from voters who vote only during presidential general elections. Some years see an increase in younger voters turning out to vote. Elections are unpredictable, and campaigns must adapt to be effective.

[.my2]
竞选经理深知，赢得选举的关键在于两点：一是让选民了解候选人的信息，二是促使选民积极投票。为了实现这些目标，候选人及其竞选团队通常会努力锁定那些最有可能投票的选民。然而，这些选民群体会随着选举的进行而变化，有时甚至会逐年变化。初选和党团会议的选民与只在总统大选中投票的选民有所不同。有些年份，年轻选民的投票率会显著提高。选举充满变数，竞选活动必须灵活应对才能取得成效。

FUNDRAISING  筹款
Even with a carefully planned and orchestrated presidential run, early fundraising is vital for candidates. Money helps them win, and the ability to raise money identifies those who are viable. In fact, the more money a candidate raises, the more they will continue to raise. EMILY’s List, a political action group, was founded on this principle; its name is an acronym for “Early Money Is Like Yeast” (it makes the dough rise). This group helps progressive women candidates gain early campaign contributions, which in turn helps them get further donations (Figure 7.17).

[.my2]
即使是精心策划、周密部署的总统竞选，早期筹款对候选人来说也至关重要。资金有助于赢得选举，而筹款能力则能体现候选人的竞争力。事实上，候选人筹集的资金越多，后续筹款也会越多。政治行动组织 “艾米丽名单”（EMILY's List ）正是基于这一原则而成立的；其名称是“早期资金就像酵母”（Early Money Is Like Yeast）的缩写（它能使面团发酵）。该组织帮助进步派女性候选人获得早期竞选捐款，进而帮助她们获得更多后续捐款（ 图 7.17 ）。

Image A is of Tammy Duckworth. Image B is of Maggie Hassan.

[.my2]
Figure 7.17 EMILY’s List candidates include members of Congress, such as Tammy Duckworth (D-IL) (a), and governors, such as Maggie Hassan (b) of New Hampshire, who both ran for U.S. Senate, and won, in 2016. (credit b: modification of work by Roger H. Goun)
图 7.17 EMILY's List 的候选人包括国会议员，例如伊利诺伊州民主党众议员塔米·达克沃斯 (a)，以及州长，例如新罕布什尔州州长玛吉·哈桑 (b)，她们都曾竞选美国参议员，并在 2016 年获胜。（图片来源 b：Roger H. Goun 作品的修改版）
Early in the 2016 election season, several Republican candidates had fundraised well ahead of their opponents. Jeb Bush, and Ted Cruz were the top fundraisers by July 2015, with Cruz reporting $14 million and Bush with $11 million in contributions. In comparison, Bobby Jindal and George Pataki (who both dropped out relatively early) each reported less than $1 million in contributions during the same period. Bush later reported over $100 million in contributions, while the other Republican candidates continued to report lower contributions. Media stories about Bush’s fundraising discussed his powerful financial networking, while coverage of the other candidates focused on their lack of money. Donald Trump, the eventual Republican nominee and president, showed a comparatively low fundraising amount in the primary phase as he enjoyed much free press coverage because of his notoriety. He also flirted with the idea of being an entirely self-funded candidate.

[.my2]
2016 年总统大选初期，几位共和党候选人的筹款额就远远领先于对手。截至 2015 年 7 月，杰布·布什和特德· 克鲁兹是筹款最多的两位候选人，克鲁兹筹集了 1400 万美元，布什筹集了 1100 万美元。相比之下，鲍比·金达尔和乔治·帕塔基（两人都较早退出了竞选）同期筹集的资金均不足 100 万美元。布什后来筹集的资金超过 1 亿美元，而其他共和党候选人的筹款额则持续较低。媒体对布什筹款的报道着重强调了他强大的金融人脉，而对其他候选人的报道则集中在他们资金短缺的问题上。最终的共和党总统候选人唐纳德·特朗普在初选阶段的筹款额相对较低，因为他凭借其知名度获得了大量的免费媒体曝光。他还曾考虑过完全自筹资金参选。

The Democratic field in 2020 was crowded, before winnowing down to a handful of contenders early in March, when most dropped out, leaving only Senator Bernie Sanders and former Vice President Joseph Biden. Those who dropped out were former New York City mayor Michael Bloomberg, Pete Buttigieg, former congresswoman Tulsi Gabbard, Senator Amy Klobuchar, and Senator Elizabeth Warren. The March cash-on-hand amounts of these candidates were respectively $11,179,565; $6,011,814; $640,210; $2,281,636; and $4,534,180. Sanders later dropped out of the race on April 8 with $16,176,082 left in his campaign coffers, leaving Biden to sail to the nomination.106
2020 年民主党总统候选人提名竞争异常激烈，3 月初开始缩减至少数几位候选人，随后大部分人退出，最终只剩下参议员伯尼·桑德斯和前副总统乔·拜登。退出竞选的候选人包括前纽约市市长迈克尔·布隆伯格、皮特·布蒂吉格、前国会议员图尔西·加巴德、参议员艾米·克洛布查尔和参议员伊丽莎白·沃伦。截至 3 月份，这些候​​选人的竞选资金分别为 11,179,565 美元、6,011,814 美元、640,210 美元、2,281,636 美元和 4,534,180 美元。桑德斯最终于 4 月 8 日退出竞选，当时他的竞选资金还剩 16,176,082 美元，拜登最终轻松获得提名。

COMPARING PRIMARY AND GENERAL CAMPAIGNS
初选与普选的比较
Although candidates have the same goal for primary and general elections, which is to win, these elections are very different from each other and require a very different set of strategies. Primary elections are more difficult for the voter. There are more candidates vying to become their party’s nominee, and party identification is not a useful cue because each party has many candidates rather than just one. In the 2016 presidential election, Republican voters in the early primaries were presented with a number of options, including Mike Huckabee, Donald Trump, Jeb Bush, Ted Cruz, Marco Rubio, John Kasich, Chris Christie, Carly Fiorina, Ben Carson, and more. (Huckabee, Christie, and Fiorina dropped out relatively early.) In 2020, Democrats had to decide between Joe Biden, Bernie Sanders, Kamala Harris, Pete Buttegieg, Michael Bloomberg, Cory Booker, Amy Klobuchar, and Elizabeth Warren. Voters must find more information about each candidate to decide which is closest to their preferred issue positions. Due to time limitations, voters may not research all the candidates. Nor will all the candidates get enough media or debate time to reach the voters. These issues make campaigning in a primary election difficult, so campaign managers tailor their strategy.

[.my2]
尽管候选人在初选和普选中的目标都是赢得选举，但这两种选举截然不同，需要采取完全不同的策略。初选对选民来说更加困难。因为有更多候选人争夺党内提名，而且党派认同不再是有效的判断依据，因为每个党派都有多名候选人，而不是只有一位。在 2016 年总统大选中，共和党选民在早期初选中面临众多选择，包括迈克·赫卡比、唐纳德· 特朗普 、杰布·布什、特德·克鲁兹、马可·卢比奥、约翰·卡西奇、克里斯·克里斯蒂、卡莉·菲奥莉娜、本·卡森等等。（赫卡比、克里斯蒂和菲奥莉娜较早退出了竞选。）而在 2020 年，民主党选民则需要在乔·拜登、伯尼·桑德斯、卡马拉· 哈里斯 、皮特·布蒂吉格、迈克尔·布隆伯格、科里·布克、艾米·克洛布查尔和伊丽莎白·沃伦之间做出选择。选民必须了解每位候选人的更多信息，才能决定哪位候选人的立场最符合他们的偏好。由于时间有限，选民可能无法研究所有候选人。此外，并非所有候选人都能获得足够的媒体曝光或辩论时间来接触选民。这些问题使得初选竞选活动充满挑战，因此竞选经理需要根据实际情况调整策略。

First, name recognition is extremely important. Voters are unlikely to cast a vote for an unknown. Some candidates, like Hillary Clinton and Jeb Bush in 2016 or Joe Biden and Bernie Sanders in 2020, have held or are related to someone who held national office, but most candidates will be governors, senators, or local politicians who are less well-known nationally. Barack Obama was a junior senator from Illinois and Bill Clinton was a governor from Arkansas prior to running for president. Voters across the country had little information about them, and both candidates needed media time to become known. While well-known candidates have longer records that can be attacked by the opposition, they also have an easier time raising campaign funds because their odds of winning are better. Newer candidates face the challenge of proving themselves during the short primary season and are more likely to lose. In 2016, both eventual party nominees had massive name recognition. Hillary Clinton enjoyed notoriety from having been First Lady, a U.S. senator from New York, and secretary of state. Donald Trump had name recognition from being an iconic real estate tycoon with Trump buildings all over the world plus a reality TV star via shows like The Apprentice. In 2020, Democratic nominee Joe Biden had name recognition for having served in the U.S. Senate for many years and for serving two terms as vice president to President Barack Obama.

[.my2]
首先，知名度至关重要。选民不太可能投票给一个名不见经传的候选人。有些候选人，例如 2016 年的希拉里·克林顿和杰布·布什，以及 2020 年的乔·拜登和伯尼·桑德斯，曾担任过国家级公职或与担任过国家级公职的人有亲属关系，但大多数候选人都是州长、参议员或地方政客，在全国范围内知名度较低。巴拉克·奥巴马在竞选总统之前是伊利诺伊州的一名初级参议员，比尔·克林顿是阿肯色州的一名州长。全国各地的选民对他们知之甚少，两位候选人都需要媒体曝光才能为人所知。虽然知名度高的候选人履历更长，更容易受到对手的攻击，但他们也更容易筹集竞选资金，因为他们的胜算更大。而新晋候选人则面临着在短暂的初选期内证明自己的挑战，败选的可能性也更大。2016 年，最终获得党内提名的两位候选人都拥有极高的知名度。希拉里·克林顿曾担任第一夫人、纽约州参议员和国务卿，因此享有很高的声望。唐纳德·特朗普凭借其在全球各地拥有众多特朗普大厦的标志性房地产大亨身份以及通过 《学徒》 等真人秀节目走红的形象而广为人知。2020 年，民主党候选人乔·拜登则因其多年担任美国参议员以及曾两度担任巴拉克·奥巴马总统的副总统而获得知名度。

Second, visibility is crucial when a candidate is one in a long parade of faces. Given that voters will want to find quick, useful information about each, candidates will try to get the media’s attention and pick up momentum. Media attention is especially important for newer candidates. Most voters assume a candidate’s website and other campaign material will be skewed, showing only the most positive information. The media, on the other hand, are generally considered more reliable and unbiased than a candidate’s campaign materials, so voters turn to news networks and journalists to pick up information about the candidates’ histories and issue positions. Candidates are aware of voters’ preference for quick information and news and try to get interviews or news coverage for themselves. Candidates also benefit from news coverage that is longer and cheaper than campaign ads.

[.my2]
其次，当候选人只是众多面孔中的一个时，曝光度至关重要。鉴于选民希望快速找到每位候选人的有用信息，候选人会努力吸引媒体的关注，并积蓄力量。媒体关注对新候选人尤为重要。大多数选民认为候选人的网站和其他竞选材料会带有偏见，只展示最正面的信息。另一方面，媒体通常被认为比候选人的竞选材料更可靠、更客观，因此选民会转向新闻网络和记者，以获取有关候选人背景和政策立场的信息。候选人深知选民偏好快速获取信息和新闻，因此会努力争取采访或新闻报道。此外，与竞选广告相比，新闻报道篇幅更长、成本更低，对候选人也更有利。

For all these reasons, campaign ads in primary elections rarely mention political parties and instead focus on issue positions or name recognition. Many of the best primary ads help the voters identify issue positions they have in common with the candidate. In 2008, for example, Hillary Clinton ran a holiday ad in which she was seen wrapping presents. Each present had a card with an issue position listed, such as “bring back the troops” or “universal pre-kindergarten.” In a similar, more humorous vein, Mike Huckabee gained name recognition and issue placement with his 2008 primary ad. The “HuckChuck” spot had Chuck Norris repeat Huckabee’s name several times while listing the candidate’s issue positions. Norris’s line, “Mike Huckabee wants to put the IRS out of business,” was one of many statements that repeatedly used Huckabee’s name, increasing voters’ recognition of it. While neither of these candidates won the nomination, the ads were viewed by millions and were successful as primary ads.

[.my2]
鉴于以上种种原因，初选竞选广告很少提及政党，而是侧重于议题立场或提升候选人知名度。许多优秀的初选广告都能帮助选民找到与候选人共同的议题立场。例如，2008 年，希拉里·克林顿投放了一则节日广告，广告中她正在包装礼物。每个礼物盒里都有一张卡片，上面列出了一项议题立场，例如“让军队重返美国”或“普及学前教育”。迈克·赫卡比也以类似的方式，通过更幽默的方式提升了知名度，并强化了其在 2008 年初选中的议题影响力。这则名为“HuckChuck”的广告中，查克·诺里斯反复提及赫卡比的名字，并列举了这位候选人的议题立场。诺里斯的一句台词“迈克·赫卡比想让国税局倒闭”只是众多反复提及赫卡比名字的语句之一，进一步提升了选民对他的认知度。虽然这两位候选人最终都没能获得提名，但这些广告的观看量高达数百万，作为初选广告而言，它们无疑是成功的。

By the general election, each party has only one candidate, and campaign ads must accomplish a different goal with different voters. Because most party-affiliated voters will cast a ballot for their party’s candidate, the campaigns must try to reach the independent and undecided, as well as try to convince their party members to get out and vote. Some ads will focus on issue and policy positions, comparing the two main party candidates. Other ads will remind party loyalists why it is important to vote. President Lyndon B. Johnson used the infamous “Daisy Girl” ad, which cut from a little girl counting daisy petals to an atomic bomb being dropped, to explain why voters needed to turn out and vote for him. If the voters stayed home, Johnson implied, his opponent, Republican Barry Goldwater, might start an atomic war. The ad aired once as a paid ad on NBC before it was pulled, but the footage appeared on other news stations as newscasters discussed the controversy over it.107 More recently, in the 2020 campaign, Joe Biden used the "What Happens Now" ad to extol Biden's background in managing crises in contrast to President Trump's mismanagement of the COVID-19 pandemic.108
到了大选时，每个政党都只有一位候选人，竞选广告必须针对不同的选民群体达成不同的目标。由于大多数党派选民都会投票给本党候选人，竞选团队必须努力争取独立选民和尚未决定投票意向的选民，同时也要努力说服本党党员积极投票。一些广告会着重阐述议题和政策立场，对比两大政党候选人。另一些广告则会提醒党内忠实拥护者投票的重要性。林登· 约翰逊总统曾使用臭名昭著的“雏菊女孩”广告来解释选民为何需要出来投票支持他。该广告的画面从小女孩数雏菊花瓣切换到原子弹爆炸的场景。约翰逊暗示，如果选民待在家中，他的对手、共和党人巴里·戈德华特可能会发动原子战争。这则广告曾在 NBC 电视台作为付费广告播出过一次，之后被撤下，但其他新闻频道也播放了这段视频，新闻主播们也讨论了围绕这则广告的争议。 107 最近，在 2020 年的竞选活动中，乔·拜登利用“接下来会发生什么”这则广告，大力宣传拜登在危机管理方面的经验，以此对比特朗普总统对新冠疫情的应对不力 。108

Part of the reason Johnson’s campaign ad worked is that more voters turn out for a general election than for other elections. These additional voters are often less ideological and more independent, making them harder to target but possible to win over. They are also less likely to complete a lot of research on the candidates, so campaigns often try to create emotion-based negative ads. While negative ads may decrease voter turnout by making voters more cynical about politics and the election, voters watch and remember them.109
约翰逊的竞选广告之所以奏效，部分原因是普选的投票率通常高于其他选举。这些新增选民往往意识形态倾向较弱，也更加独立，因此更难精准定位，但也并非完全没有可能争取到他们的支持。他们也不太可能对候选人进行深入研究，所以竞选团队常常会尝试制作煽动情绪的负面广告。虽然负面广告可能会让选民对政治和选举更加愤世嫉俗，从而降低投票率，但选民仍然会观看并记住这些广告 。109

Another source of negative ads is from groups outside the campaigns. Sometimes, shadow campaigns, run by political action committees and other organizations without the coordination or guidance of candidates, also use negative ads to reach voters. Even before the Citizens United decision allowed corporations and interest groups to run ads supporting candidates, shadow campaigns existed. In 2004, the Swift Boat Veterans for Truth organization ran ads attacking John Kerry’s military service record, and MoveOn attacked George W. Bush’s decision to commit to the wars in Afghanistan and Iraq. In 2020, super PACs poured more than $2.3 billion into supporting candidates.110
负面广告的另一个来源是竞选活动之外的团体。有时，由政治行动委员会和其他组织在没有候选人协调或指导的情况下开展的 “影子竞选” 也会使用负面广告来接触选民。早在 “公民联合会诉联邦选举委员会案”（Citizens United） 判决允许企业和利益集团投放广告支持候选人之前，“影子竞选”就已经存在。2004 年， “真相快艇老兵”（Swift Boat Veterans for Truth） 组织投放广告攻击约翰· 克里的服役记录，而 “MoveOn”组织则抨击乔治·W·布什决定发动阿富汗和伊拉克战争。2020 年，超级政治行动委员会（Super PACs）投入超过 23 亿美元支持候选人。

Link to Learning  学习链接
Want to know how much money federal candidates and PACs are raising? Visit the Campaign Finance Disclosure Portal at the Federal Election Commission website.

[.my2]
想知道联邦候选人和政治行动委员会筹集了多少资金？请访问联邦选举委员会网站上的竞选财务披露门户网站。

General campaigns also try to get voters to the polls in closely contested states. In 2004, realizing that it would be difficult to convince Ohio Democrats to vote Republican, George W. Bush’s campaign focused on getting the state’s Republican voters to the polls. The volunteers walked through precincts and knocked on Republican doors to raise interest in Bush and the election. Volunteers also called Republican and former Republican households to remind them when and where to vote.111 The strategy worked, and it reminded future campaigns that an organized effort to get out the vote is still a viable way to win an election.

[.my2]
在竞争激烈的州，大选竞选活动也会努力动员选民投票。2004 年，乔治·W·布什的竞选团队意识到很难说服俄亥俄州的民主党人转而支持共和党，于是将重点放在动员该州的共和党选民投票上。志愿者们挨家挨户敲共和党选民的家门，以提高他们对布什和此次选举的关注度。志愿者们还打电话给共和党选民和前共和党选民的家庭，提醒他们何时何地投票。这一策略奏效了，也让后来的竞选活动意识到，有组织的动员选民投票仍然是赢得选举的有效途径。

TECHNOLOGY  技术
Campaigns have always been expensive. Also, they have sometimes been negative and nasty. The 1828 “Coffin Handbill” that John Quincy Adams ran, for instance, listed the names and circumstances of the executions his opponent Andrew Jackson had ordered (Figure 7.18). This was in addition to gossip and verbal attacks against Jackson’s wife, who had accidentally committed bigamy when she married him without a proper divorce. Campaigns and candidates have not become more amicable in the years since then.

[.my2]
竞选活动历来耗资巨大，而且有时还会充满负面情绪和恶意攻击。例如，约翰·昆西·亚当斯在 1828 年推出的“ 棺材传单 ”就列出了他的对手安德鲁·杰克逊下令处决的人员姓名和具体情况（ 图 7.18 ）。此外，还有针对杰克逊妻子的流言蜚语和人身攻击，因为她在没有正式离婚的情况下嫁给了杰克逊，无意中犯了重婚罪。此后多年，竞选活动和候选人之间的关系并没有变得更加友好。

An image of a handbill from the 1828 presidential election. The top reads “General Jackson” underneath which are several coffins.

[.my2]
Figure 7.18 The infamous “Coffin Handbill” used by John Quincy Adams against Andrew Jackson in the 1828 presidential election.

[.my2]
图 7.18 约翰·昆西·亚当斯在 1828 年总统选举中用来反对安德鲁·杰克逊的臭名昭著的“棺材传单”。
Once television became a fixture in homes, campaign advertising moved to the airwaves. Television allowed candidates to connect with the voters through video, allowing them to appeal directly to and connect emotionally with voters. While Adlai Stevenson and Dwight D. Eisenhower were the first to use television in their 1952 and 1956 campaigns, the ads were more like jingles with images. Stevenson’s “Let’s Not Forget the Farmer” ad had a catchy tune, but its animated images were not serious and contributed little to the message. The “Eisenhower Answers America” spots allowed Eisenhower to answer policy questions, but his answers were glib rather than helpful.

[.my2]
电视普及家庭后，竞选广告也随之转移到了电视上。电视让候选人能够通过视频与选民直接沟通，从而更直接地吸引选民的注意力，并与他们建立情感联系。虽然阿德莱·史蒂文森和德怀特·D·艾森豪威尔分别在 1952 年和 1956 年的竞选活动中率先使用电视，但当时的广告更像是配有图像的广告歌。史蒂文森的“不要忘记农民”广告旋律朗朗上口，但其动画画面不够严肃，对传递信息几乎没有帮助。“艾森豪威尔回答美国”系列广告让艾森豪威尔有机会回答政策问题，但他的回答却显得轻率肤浅，缺乏实质性内容。

John Kennedy’s campaign was the first to use images to show voters that the candidate was the choice for everyone. His ad, “Kennedy,” combined the jingle “Kennedy for me” and photographs of a diverse population dealing with life in the United States.

[.my2]
约翰·肯尼迪的竞选活动首次运用图像向选民表明，他是所有人的选择。他的竞选广告“肯尼迪”将“肯尼迪，我选肯尼迪”的竞选口号与展现美国不同人群生活状态的照片相结合。

Link to Learning  学习链接
The Museum of the Moving Image has collected presidential campaign ads from 1952 through today, including the “Kennedy for Me” spot mentioned above. Take a look and see how candidates have created ads to get the voters’ attention and votes over time.

[.my2]
动态影像博物馆收藏了从 1952 年至今的总统竞选广告，包括上文提到的“肯尼迪为我竞选”广告。不妨看看，候选人是如何随着时间的推移，通过制作广告来吸引选民的注意力并赢得选票的。

Over time, however, ads became more negative and manipulative. In reaction, the Bipartisan Campaign Reform Act of 2002, or McCain–Feingold, included a requirement that candidates stand by their ad and include a recorded statement within the ad stating that they approved the message. Although ads, especially those run by super PACs, continue to be negative, candidates can no longer dodge responsibility for them.

[.my2]
然而，随着时间的推移，广告变得越来越负面和具有操控性。为了应对这种情况，2002 年的 《两党竞选改革法案 》（又称《麦凯恩-费恩戈尔德法案》）规定，候选人必须对其广告内容负责，并在广告中附上录音声明，表明他们认可该广告的信息。尽管广告，尤其是超级政治行动委员会投放的广告，仍然带有负面色彩，但候选人再也不能逃避责任了。

Candidates are also frequently using interviews on late night television to get messages out. Soft news, or infotainment, is a new type of news that combines entertainment and information. Shows like The Daily Show and Last Week Tonight make the news humorous or satirical while helping viewers become more educated about the events around the nation and the world.112 In 2008, Huckabee, Obama, and McCain visited popular programs like The Daily Show, The Colbert Report, and Late Night with Conan O’Brien to target informed voters in the under-45 age bracket. The candidates were able to show their funny sides and appear like average Americans, while talking a bit about their policy preferences. By fall of 2015, The Late Show with Stephen Colbert had already interviewed most of the potential presidential candidates, including Hillary Clinton, Bernie Sanders, Jeb Bush, Ted Cruz, and Donald Trump.

[.my2]
候选人也经常利用深夜电视节目的访谈来传递信息。软新闻，或称娱乐资讯，是一种结合娱乐和信息的新型新闻形式。像 《每日秀》 和 《上周今夜秀》 这样的节目，以幽默或讽刺的方式报道新闻，同时帮助观众更好地了解国内外发生的事件。2008 年，哈克比、奥巴马和麦凯恩做客 《每日秀》 、 《科尔伯特报告》 和 《柯南·奥布莱恩深夜秀》 等热门节目，旨在吸引 45 岁以下的知情选民。候选人们得以展现他们幽默的一面，看起来像普通的美国民众，同时也简要地谈到了他们的政策倾向。到 2015 年秋季， 《斯蒂芬·科尔伯特深夜秀》 已经采访了大多数潜在的总统候选人，包括希拉里·克林顿、伯尼·桑德斯、杰布·布什、特德·克鲁兹和唐纳德·特朗普。

The Internet has given candidates a new platform and a new way to target voters. In the 2000 election, campaigns moved online and created websites to distribute information. They also began using search engine results to target voters with ads. In 2004, Democratic candidate Howard Dean used the Internet to reach out to potential donors. Rather than host expensive dinners to raise funds, his campaign posted footage on his website of the candidate eating a turkey sandwich. The gimmick brought over $200,000 in campaign donations and reiterated Dean’s commitment to be a down-to-earth candidate.

[.my2]
互联网为候选人提供了一个全新的平台和接触选民的新途径。在2000年的总统选举中，各竞选团队纷纷转向线上，创建网站发布信息。他们还开始利用搜索引擎结果投放广告，精准触达选民。2004年，民主党候选人霍华德·迪恩利用互联网联系潜在捐助者。他的竞选团队没有举办昂贵的晚宴来筹款，而是在网站上发布了一段他吃火鸡三明治的视频。这一小噱头为他筹集了超过20万美元的竞选捐款，也再次展现了迪恩平易近人的竞选形象。

Candidates also use social media, such as Facebook, Twitter, and YouTube, to interact with supporters and get the attention of younger voters. While internet websites continue to proliferate in political campaigns, the advent of social media has taken the influence of internet information and communications to a new level. Candidates use social media, such as Facebook, Twitter, and YouTube, to interact with supporters and get the attention of young voters. More importantly, social media has become an incredibly important avenue through which citizens talk to each other about politics, sharing positions, memes and jabs to their chosen networks of contacts and friends. The possibility of misinformation and bias in that setting led Facebook and Twitter to begin to monitor for untruths, in some cases deleting the social media accounts of violators, including President Trump. However, those platforms eventually reduced such monitoring and restriction.

[.my2]
候选人也利用 Facebook、Twitter 和 YouTube 等社交媒体与支持者互动，并吸引年轻选民的关注。虽然互联网网站在政治竞选中持续涌现，但社交媒体的出现将互联网信息和通信的影响力提升到了一个新的高度。候选人利用 Facebook、Twitter 和 YouTube 等社交媒体与支持者互动，并吸引年轻选民的关注。更重要的是，社交媒体已成为公民就政治问题进行交流、分享立场、表情包和讽刺言论的重要渠道，这些交流内容会传播到他们选择的联系人和朋友圈。这种环境下可能出现虚假信息和偏见，促使 Facebook 和 Twitter 开始监控虚假信息，在某些情况下甚至删除违规者的社交媒体账户，包括特朗普总统的账户。然而，这些平台最终减少了此类监控和限制。

VOTER DECISION MAKING  选民决策
When citizens do vote, how do they make their decisions? The election environment is complex and most voters don’t have time to research everything about the candidates and issues. Yet they will need to make a fully rational assessment of the choices for an elected office. To meet this goal, they tend to take shortcuts.

[.my2]
公民投票时，他们如何做出决定？选举环境复杂，大多数选民没有时间去研究所有候选人和议题。然而，他们需要对当选职位做出完全理性的评估。为了达到这个目的，他们往往会走捷径。

One popular shortcut is simply to vote using party affiliation. Many political scientists consider party-line voting to be rational behavior because citizens register for parties based upon either position preference or socialization. Similarly, candidates align with parties based upon their issue positions. A Democrat who votes for a Democrat is very likely selecting the candidate closest to the voter's personal ideology. While party identification is a voting cue, it also makes for a logical decision.

[.my2]
一种常见的简便方法是直接根据党派归属投票。许多政治学家认为，按党派投票是一种理性行为，因为公民登记加入某个政党要么基于政治立场偏好，要么基于社会化因素。同样，候选人也会根据其政治立场选择所属政党。一位民主党人如果投票给民主党候选人，很可能是在选择最符合其个人意识形态的候选人。虽然党派认同是投票的一个线索，但它也符合逻辑。

Citizens also use party identification to make decisions via straight-ticket voting—choosing every Republican or Democratic Party member on the ballot. In some states, such as Texas or Michigan, selecting one box at the top of the ballot gives a single party all the votes on the ballot (Figure 7.19). Straight-ticket voting does cause problems in states that include non-partisan positions on the ballot. In Michigan, for example, the top of the ballot (presidential, gubernatorial, senatorial and representative seats) will be partisan, and a straight-ticket vote will give a vote to all the candidates in the selected party. But the middle or bottom of the ballot includes seats for local offices or judicial seats, which are non-partisan. These offices would receive no vote, because the straight-ticket votes go only to partisan seats. In 2010, actors from the former political drama The West Wing came together to create an advertisement for Mary McCormack’s sister Bridget, who was running for a non-partisan seat on the Michigan Supreme Court. The ad reminded straight-ticket voters to cast a ballot for the court seats as well; otherwise, they would miss an important election. McCormack won the seat.

[.my2]
公民也会通过一键全选的方式进行投票，即选择选票上所有共和党或民主党的候选人。在一些州，例如德克萨斯州或密歇根州，选择选票顶部的一个方框即可将所有选票投给一个政党（ 图 7.19 ）。一键全选在选票上包含非党派职位的州会造成问题。例如，在密歇根州，选票顶部（总统、州长、参议员和众议员席位）是党派职位，一键全选会将选票投给所选政党的所有候选人。但选票中间或底部包含地方官员或法官席位，这些职位是非党派的。由于一键全选的选票只投给党派职位，这些职位将不会获得选票。 2010 年，曾出演政治剧 《白宫风云》 的演员们齐聚一堂，为玛丽·麦考马克（Mary McCormack）的妹妹布里奇特（Bridget）制作了一则竞选广告。当时，布里奇特正在竞选密歇根州最高法院的无党派席位。这则广告提醒那些只投民主党和共和党的选民，也应该为最高法院的席位投票，否则他们将错过这场重要的选举。最终，布里奇特赢得了这个席位。

An image of an official ballot for the 2012 general election. A callout box highlights the section titled “Straight Party Ticket” which reads “vote for not more than 1: Republican Party, Democratic Party, Libertarian Party, U.S. Taxpayers Party, Green Party, Natural Law Party”.

[.my2]
Figure 7.19 Voters in Michigan can use straight-ticket voting. To fill out their ballot, they select one box at the top to give a single party all the votes on the ballot.

[.my2]
图 7.19 密歇根州的选民可以使用一键投票。填写选票时，他们只需在顶部选择一个方框，即可将选票上的所有选票都投给一个政党。
Straight-ticket voting does have the advantage of reducing ballot fatigue. Ballot fatigue occurs when someone votes only for the top or important ballot positions, such as president or governor, and stops voting rather than continue to the bottom of a long ballot. In 2012, for example, 70 percent of registered voters in Colorado cast a ballot for the presidential seat, yet only 54 percent voted yes or no on retaining Nathan B. Coats for the state supreme court.113
一键投票确实有减少投票疲劳的优势。投票疲劳指的是选民只投票给选票上最重要的职位，例如总统或州长，然后就停止投票，而不是继续填写冗长的选票。例如，2012 年，科罗拉多州 70%的注册选民投票选举总统，但只有 54%的选民投票赞成或反对内森·B·科茨继续担任州最高法院法官。 113

Voters make decisions based upon candidates’ physical characteristics, such as attractiveness or facial features.114 They may also vote based on gender or race, because they assume the elected official will make policy decisions based on a demographic shared with the voters. Candidates are very aware of voters’ focus on these non-political traits. In 2008, a sizable portion of the electorate wanted to vote for either Hillary Clinton or Barack Obama because they offered new demographics—either the first woman or the first Black president. Demographics hurt John McCain that year, because many people believed that at 71 he was too old to be president.115 Hillary Clinton faced this situation again in 2016 as she became the first woman nominee from a major party. In essence, attractiveness can make a candidate appear more competent, which in turn can help him or her ultimately win.116 The 2020 election had a bit of everything. While the two major party nominees were older White men, as was the last-standing Democrat other than Biden, Bernie Sanders, (older even than McCain was in 2008), there were many diverse candidates of different ages who ran for the Democratic nomination. Three women, all U.S. senators, ran serious and competitive campaigns: Elizabeth Warren, Amy Klobuchar, and Kamala Harris (who was tapped for vice president). Representative Tulsi Gabbard (D-HI) ran as well. In terms of race and ethnicity, Harris is of Black and South Asian descent, Senator Cory Booker is Black, former HUD Secretary Julián Castro is Latino, and Tulsi Gabbard and entrepreneur Andrew Yang are of Asian-American/Pacific Islander descent.

[.my2]
选民会根据候选人的外貌特征，例如外貌或五官来做决定。 114 他们也可能根据性别或种族投票，因为他们认为当选官员会根据与选民相同的群体特征来制定政策。候选人非常清楚选民对这些非政治特征的关注。2008 年，相当一部分选民希望投票给希拉里·克林顿或巴拉克·奥巴马，因为他们代表着新的人口结构——分别是第一位女总统和第一位黑人总统。人口结构因素在那一年对约翰·麦凯恩不利，因为许多人认为 71 岁的他年纪太大，不适合担任总统。 115 2016 年，希拉里·克林顿再次面临这种情况，因为她成为主要政党的首位女性总统候选人。本质上，外貌吸引力可以使候选人看起来更有能力，这反过来又有助于他或她最终赢得选举。 116 2020 年的选举可谓包罗万象。虽然两大党提名人都是年长的白人男性，除了拜登之外最后一位在位的民主党候选人伯尼·桑德斯也是如此（他的年龄甚至比 2008 年的麦凯恩还要大），但民主党内还有许多不同年龄、背景各异的候选人参与了总统候选人提名。三位女性，均为美国参议员，都进行了认真且竞争激烈的竞选：伊丽莎白·沃伦、艾米·克洛布查尔和卡玛拉·哈里斯（她被提名为副总统候选人）。夏威夷州民主党众议员图尔西·加巴德也参与了竞选。就种族和族裔而言，哈里斯是黑人和南亚裔混血，参议员科里·布克是黑人，前住房和城市发展部部长朱利安·卡斯特罗是拉丁裔，而图尔西·加巴德和企业家杨安泽则是亚裔/太平洋岛民。

Aside from party identification and demographics, voters will also look at issues or the economy when making a decision. For some single-issue voters, a candidate’s stance on abortion rights will be a major factor, while other voters may look at the candidates’ beliefs on the Second Amendment and gun control. Single-issue voting may not require much more effort by the voter than simply using party identification; however, many voters are likely to seek out a candidate’s position on a multitude of issues before making a decision. They will use the information they find in several ways.

[.my2]
除了党派认同和人口统计数据外，选民在做决定时还会考虑各种议题或经济状况。对于一些只关注单一议题的选民来说，候选人在堕胎权问题上的立场至关重要；而另一些选民则可能关注候选人对宪法第二修正案和枪支管制的看法。单一议题投票可能并不比仅仅根据党派认同花费更多精力；然而，许多选民在做出决定前，很可能会了解候选人在众多议题上的立场。他们会以多种方式利用这些信息。

Retrospective voting occurs when the voter looks at the candidate’s past actions and the past economic climate and makes a decision only using these factors. This behavior may occur during economic downturns or after political scandals, when voters hold politicians accountable and do not wish to give the representative a second chance. Pocketbook voting occurs when voters look at their personal finances and circumstances to decide how to vote. Someone having a harder time finding employment or seeing investments suffer during a particular candidate or party’s control of government will vote for a different candidate or party than the incumbent. Prospective voting occurs when the voter applies information about a candidate’s past behavior to decide how the candidate will act in the future. For example, will the candidate’s voting record or actions help the economy and better prepare the candidate to be president during an economic downturn? The challenge of this voting method is that the voters must use a lot of information, which might be conflicting or unrelated, to make an educated guess about how the candidate will perform in the future. Voters do appear to rely on prospective and retrospective voting more often than on pocketbook voting.

[.my2]
回顾性投票是指选民仅根据候选人过去的政绩和经济状况做出决定。这种行为可能发生在经济衰退或政治丑闻之后，此时选民会追究政治人物的责任，不愿给其第二次机会。 经济利益投票是指选民根据自身财务状况来决定投票意向。例如，如果选民在某个候选人或政党执政期间难以找到工作或投资受损，他们就会投票给其他候选人或政党。 前瞻性投票是指选民根据候选人过去的政绩来判断其未来的行为。例如，候选人的投票记录或行为是否有利于经济发展，以及是否能帮助其更好地应对经济衰退时期的总统​​任期？这种投票方式的挑战在于，选民必须运用大量信息（这些信息可能相互矛盾或毫不相关）才能对候选人未来的表现做出合理的预测。选民似乎更倾向于使用前瞻性投票和回顾性投票，而不是经济利益投票。

In some cases, a voter may cast a ballot strategically. In these cases, a person may vote for a second- or third-choice candidate, either because the preferred candidate cannot win or in the hope of preventing another candidate from winning. This type of voting is likely to happen when there are multiple candidates for one position or multiple parties running for one seat.117 In Florida and Oregon, for example, Green Party voters (who tend to be liberal) may choose to vote for a Democrat if the Democrat might otherwise lose to a Republican. Similarly, in Georgia, while a Libertarian may be the preferred candidate, the voter would rather have the Republican candidate win over the Democrat and will vote accordingly.118
在某些情况下，选民可能会进行策略性投票。在这种情况下，选民可能会投票给第二或第三选择的候选人，可能是因为他们心仪的候选人无法获胜，也可能是希望阻止其他候选人获胜。当一个职位有多名候选人或多个政党竞选一个席位时，这种投票方式更容易发生。 例如 ，在佛罗里达州和俄勒冈州，绿党选民（他们往往倾向于自由派）可能会选择投票给民主党候选人，因为民主党候选人可能会输给共和党候选人。 同样 ，在佐治亚州，虽然自由党候选人可能是选民的首选，但选民更希望共和党候选人战胜民主党候选人，并会据此投票。

One other way voters make decisions is through incumbency. In essence, this is retrospective voting, but it requires little of the voter. In congressional and local elections, incumbents win reelection up to 90 percent of the time, a result called the incumbency advantage. What contributes to this advantage and often persuades competent challengers not to run? First, incumbents have name recognition and voting records. The media is more likely to interview them because they have advertised their name over several elections and have voted on legislation affecting the state or district. Incumbents also have won election before, which increases the odds that political action committees and interest groups will give them money; most interest groups will not give money to a candidate destined to lose.

[.my2]
选民做出决定的另一种方式是通过现任优势。本质上，这是一种回顾性投票，但对选民的要求并不高。在国会和地方选举中，现任者连任的概率高达 90%，这种现象被称为“ 现任优势” 。是什么造就了这种优势，并常常导致一些有能力的挑战者放弃参选呢？首先，现任者拥有知名度和投票记录。媒体更倾向于采访他们，因为他们在多次选举中都宣传过自己的名字，并且参与过影响州或选区的立法投票。此外，现任者之前也赢得过选举，这增加了政治行动委员会和利益集团向他们捐款的可能性；大多数利益集团不会把钱捐给注定要落败的候选人。

Incumbents also have franking privileges, which allows them a limited amount of free mail to communicate with the voters in their district. While these mailings may not be sent in the days leading up to an election—sixty days for a senator and ninety days for a House member—congressional representatives are able to build a free relationship with voters through them.119 Moreover, incumbents have existing campaign organizations, while challengers must build new organizations from the ground up. Lastly, incumbents have more money in their war chests than most challengers.

[.my2]
现任议员还享有免费邮寄特权，允许他们使用有限数量的免费邮件与选区选民沟通。虽然这些邮件可能不会在选举前几天寄出——参议员为 60 天，众议员为 90 天——但国会议员仍然可以通过这些邮件与选民建立联系。 此外 ，现任议员拥有现成的竞选团队，而挑战者则必须从零开始组建新的团队。最后，现任议员的竞选资金通常比大多数挑战者更为雄厚。

Another incumbent advantage is gerrymandering, the drawing of district lines to guarantee a desired electoral outcome. Every ten years, following the U.S. Census, the number of House of Representatives members allotted to each state is determined based on a state’s population. If a state gains or loses seats in the House, the state must redraw districts to ensure each district has an equal number of citizens. States may also choose to redraw these districts at other times and for other reasons.120 If the district is drawn to ensure that it includes a majority of Democratic or Republican Party members within its boundaries, for instance, then candidates from those parties will have an advantage.

[.my2]
另一个既得利益者的优势在于选区划分，即通过人为划定选区边界来确保预期的选举结果。每十年一次的美国人口普查之后，分配给各州的众议院议员人数将根据该州的人口数量确定。如果一个州在众议院的席位增加或减少，该州必须重新划分选区，以确保每个选区的人口数量相等。各州也可以在其他时间出于其他原因选择重新划分选区。 例如 ，如果选区的划分是为了确保其边界内包含多数民主党或共和党成员，那么来自这两个政党的候选人将拥有优势。

Gerrymandering helps local legislative candidates and members of the House of Representatives, who win reelection over 90 percent of the time. Senators and presidents do not benefit from gerrymandering because they are not running in a district. Presidents and senators win states, so they benefit only from war chests and name recognition. This is one reason why senators running in 2020, for example, won reelection only 84 percent of the time, while the U.S. House rate was 95 percent.121
选区划分不公有利于地方立法候选人和众议院议员，他们的连任成功率超过 90%。参议员和总统则无法从选区划分中获益，因为他们并非在特定选区参选。总统和参议员赢得的是州，因此他们只能依靠竞选资金和知名度。这便是其中一个原因，例如，2020 年参议员的连任成功率仅为 84%，而众议院议员的连任成功率却高达 95 %。

Link to Learning  学习链接
Since 1960, the American National Election Studies has been asking a random sample of voters a battery of questions about how they voted. The data are available at the Inter-university Consortium for Political and Social Research at the University of Michigan.

[.my2]
自 1960 年以来， 美国国家选举研究项目一直在向随机抽取的选民询问一系列关于他们投票情况的问题。这些数据可在密歇根大学的跨大学政治与社会研究联盟获取。



'''