
= 007-3 Elections 选举
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





Elections offer American voters the opportunity to participate in their government with little investment of time or personal effort. Yet voters should make decisions carefully. The electoral system allows them the chance to pick party nominees as well as office-holders, although not every citizen will participate in every step. The presidential election is often criticized as a choice between two evils, yet citizens can play a prominent part in every stage of the race and influence who the final candidates actually are.

[.my2]
选举为美国选民提供了参与政府事务的机会，而且无需投入太多时间和精力。然而，选民应该谨慎做出决定。选举制度允许他们选择政党候选人和公职人员，尽管并非每位公民都会参与到每个环节。总统选举常被批评为“两害相权取其轻”，但公民可以在竞选的每个阶段都发挥重要作用，并影响最终候选人的归属。

DECIDING TO RUN  决定参选
Running for office can be as easy as collecting one hundred signatures on a city election form or paying a registration fee of several thousand dollars to run for governor of a state. However, a potential candidate still needs to meet state-specific requirements covering length of residency, voting status, and age. Potential candidates must also consider competitors, family obligations, and the likelihood of drawing financial backing. His or her spouse, children, work history, health, financial history, and business dealings also become part of the media’s focus, along with many other personal details about the past. Candidates for office are slightly more diverse than the representatives serving in legislative and executive bodies, but the realities of elections drive many eligible and desirable candidates away from running.67
竞选公职可以很简单，比如在市选举表格上收集一百个签名，或者缴纳数千美元的注册费竞选州长。然而，潜在候选人仍然需要满足各州的具体要求，包括居住年限、投票资格和年龄。潜在候选人还必须考虑竞争对手、家庭责任以及获得资金支持的可能性。他们的配偶、子女、工作经历、健康状况、财务状况和商业往来，以及许多其他个人过往细节，都会成为媒体关注的焦点。公职候选人的构成比立法和行政机构的代表更为多元化，但选举的现实情况仍然迫使许多符合资格且优秀的候选人放弃参选 。67

Despite these problems, most elections will have at least one candidate per party on the ballot. In states or districts where one party holds a supermajority, such as Oklahoma, candidates from the other party may be discouraged from running because they don’t think they have a chance to win.68 Candidates are likely to be moving up from prior elected office or are professionals, like lawyers, who can take time away from work to campaign and serve in office.69
尽管存在这些问题，大多数选举中每个政党至少会有一名候选人出现在选票上。在一些州或选区，例如俄克拉荷马州，如果一个政党拥有绝对多数席位，其他政党的候选人可能会因为认为自己没有获胜机会而放弃参选。68 候选人很可能是从之前的当选职位晋升而来，或者是像律师这样的专业人士，他们可以抽出时间参加竞选和履行公职 。69

When candidates run for office, they are most likely to choose local or state office first. For women, studies have shown that family obligations rather than desire or ambition account for this choice. Further, women are more likely than men to wait until their children are older before entering politics, and women say that they struggle to balance campaigning and their workload with parenthood.70 Because higher office is often attained only after service in lower office, there are repercussions to women waiting so long. If they do decide to run for the U.S. House of Representatives or Senate, they are often older, and fewer in number, than their male colleagues (Figure 7.11). In 2015, only 24.4 percent of state legislators and 20 percent of U.S. Congress members were women.71 However, in the 2018 midterm elections, a record number of women and younger members were elected to national office. Today, while still lagging men's representation, women make up almost 27 percent of the 117th Congress, and 31 percent of state legislative seats are held by women.72
候选人竞选公职时，通常会优先选择地方或州级职位。研究表明，对女性而言，家庭责任而非个人意愿或抱负才是她们做出这一选择的主要原因。此外，女性比男性更有可能等到子女长大后才步入政坛，而且她们也表示，在竞选、工作和育儿之间寻求平衡并非易事。 70 由于更高职位往往需要先担任较低职位才能晋升，女性等待时间过长会带来一些不利影响。如果她们最终决定竞选美国众议院或参议院议员，她们的年龄通常比男性同僚更大，人数也更少（ 图 7.11 ）。2015 年，只有 24.4% 的州议员和 20% 的美国国会议员是女性。 71 然而，在 2018 年中期选举中，当选国家级公职的女性和年轻议员人数创下历史新高。如今，尽管女性的代表人数仍然低于男性，但她们在第 117 届国会中占比已接近 27%，州议会席位中女性占比也达到了 31%。 72

A series of bar graphs titled “Seekers of Elected Office by Demographic”. The first bar graph is titled “Gender”. Under the label “General public”, approximately 49% are men and approximately 51% are women. Under the label “Sough Elected Office”, approximately 75% are men and approximately 25% are women. The second bar graph is titled “Race”. Under the label “General public”, approximately 66% are White, 15% are Hispanic, and 12% are Black. Under the label “Sough Elected Office”, approximately 82% are White, 6% are Hispanic, and 5% are Black. The third bar graph is titled “Education”. Under the label “General public”, approximately 42% have high school or less, 31% have some college, 17% are college graduates, and 10% have some post-graduate education. Under the label “Sought Elected Office”, approximately 19% have high school or less, 36% have some college, 29% are college graduates, and 16% have some post-graduate education. At the bottom of the graphs, a source is listed: “2014 Political Polarization in the American Public; general public demographic data from 2012 American Community Survey (1% IPUMS)”.

[.my2]
Figure 7.11 Those who seek elected office do not generally reflect the demographics of the general public: They are often disproportionately White men who are more educated than the overall U.S. population.

[.my2]
图 7.11 竞选公职的人通常不能反映公众的人口结构：他们往往是不成比例的白人男性，而且受教育程度高于美国总人口。
Another factor for potential candidates is whether the seat they are considering is competitive or open. A competitive seat describes a race where a challenger runs against the incumbent—the current office holder. An open seat is one whose incumbent is not running for reelection. Incumbents who run for reelection are very likely to win for a number of reasons, which are discussed later in this chapter. In fact, in the U.S. Congress, 95 percent of representatives and 82 percent of senators were reelected in 2014.73 But when an incumbent retires, the seat is open and more candidates will run for that seat.

[.my2]
潜在候选人考虑的另一个因素是他们所考虑的席位是竞争激烈的还是空缺的。 竞争激烈的席位指的是挑战者与现任官员 （即现任职位持有者）竞争的席位。 空缺席位指的是现任官员不寻求连任的席位。寻求连任的现任官员很可能获胜，原因有很多，本章稍后将对此进行讨论。事实上，在美国国会，2014 年有 95%的众议员和 82%的参议员成功连任。 73 但当现任官员退休时，席位就会空缺，会有更多候选人竞选该席位。

Many potential candidates will also decline to run if their opponent has a lot of money in a campaign war chest. War chests are campaign accounts registered with the Federal Election Commission, and candidates are allowed to keep earlier donations if they intend to run for office again. Incumbents and candidates trying to move from one office to another very often have money in their war chests. Those with early money are hard to beat because they have an easier time showing they are a viable candidate (one likely to win). They can woo potential donors, which brings in more donations and strengthens the campaign. A challenger who does not have money, name recognition, or another way to appear viable will have fewer campaign donations and will be less competitive against the incumbent.

[.my2]
如果对手拥有大量竞选资金，许多潜在候选人也会选择退出竞选。 竞选资金是指在联邦选举委员会注册的竞选账户，如果候选人打算再次竞选，则可以保留之前的捐款。现任官员和试图从一个职位连任的候选人通常都会有竞选资金。那些早期就拥有资金的候选人很难被击败，因为他们更容易证明自己是合格的候选人（更有可能获胜）。他们可以争取潜在捐助者，从而获得更多捐款，增强竞选实力。而缺乏资金、知名度或其他证明自身实力的挑战者，获得的竞选捐款较少，与现任官员的竞争也更为激烈。

CAMPAIGN FINANCE LAWS  竞选财务法
In the 2024 presidential election cycle, candidates for all parties raised a total of 5.5 billion dollars for campaigns. Congressional candidates raised $10.3 billion.74 The amount raised by political action committees (PACs), which are organizations created to raise and spend money to influence politics and contribute to candidates’ campaigns, was approximately $2.7 billion.75 How does the government monitor the vast amounts of money that are now a part of the election process?
在 2024 年总统选举周期中，各党派候选人共筹集了 55 亿美元的竞选资金。国会候选人筹集了 103 亿美元。 74 政治行动委员会（PAC） 筹集的资金约为 27 亿美元。政治行动委员会是为影响政治和资助候选人竞选而设立的组织。 75 政府如何监管如今选举过程中涉及的巨额资金？

The history of campaign finance monitoring has its roots in a federal law written in 1867, which prohibited government employees from asking Naval Yard employees for donations.76 In 1896, the Republican Party spent about $16 million overall, which includes William McKinley’s $6–7 million campaign expenses.77 This raised enough eyebrows that several key politicians, including Theodore Roosevelt, took note. After becoming president in 1901, Roosevelt pushed Congress to look for political corruption and influence in government and elections.78 Shortly after, the Tillman Act (1907) was passed by Congress, which prohibited corporations from contributing money to candidates running in federal elections. Other congressional acts followed, limiting how much money individuals could contribute to candidates, how candidates could spend contributions, and what information would be disclosed to the public.79
竞选资金监管的历史可以追溯到 1867 年的一项联邦法律，该法律禁止政府雇员向海军造船厂的雇员索要捐款。 76 1896 年，共和党总共花费了约 1600 万美元，其中包括威廉·麦金莱 600 万至 700 万美元的竞选开支。 77 这引起了包括西奥多·罗斯福在内的几位重要政治家的关注。1901 年就任总统后，罗斯福敦促国会调查政府和选举中的政治腐败和政治干预。 78 不久之后，国会通过了 《蒂尔曼法案》 （1907 年），该法案禁止公司向参加联邦选举的候选人捐款。随后，国会又通过了其他法案，限制个人可以向候选人捐款的金额、候选人如何使用捐款以及哪些信息需要向公众披露。 79

While these laws intended to create transparency in campaign funding, government did not have the power to stop the high levels of money entering elections, and little was done to enforce the laws. In 1971, Congress again tried to fix the situation by passing the Federal Election Campaign Act (FECA), which outlined how candidates would report all contributions and expenditures related to their campaigns. The FECA also created rules governing the way organizations and companies could contribute to federal campaigns, which allowed for the creation of political action committees.80 Finally, a 1974 amendment to the act created the Federal Election Commission (FEC), which operates independently of government and enforces the elections laws.

[.my2]
尽管这些法律旨在提高竞选资金的透明度，但政府无力阻止大量资金流入选举，而且这些法律也鲜有执行。1971 年，国会再次尝试通过《 联邦竞选法》 （FECA）来解决这个问题，该法规定了候选人如何报告与其竞选相关的所有捐款和支出。FECA 还制定了组织和公司向联邦竞选捐款的规则，从而允许成立政治行动委员会。80 最终， 1974 年对该法案的一项修正案设立了联邦选举委员会（FEC），该委员会独立于政府运作，负责执行选举法。

While some portions of the FECA were ruled unconstitutional by the courts in Buckley v. Valeo (1976), such as limits on personal spending on campaigns by candidates not using federal money, the FEC began enforcing campaign finance laws in 1976. 81 Even with the new laws and the FEC, money continued to flow into elections. By using loopholes in the laws, political parties and political action committees donated large sums of money to candidates, and new reforms were soon needed. Senators John McCain (R-AZ) and Russ Feingold (former D-WI) cosponsored the Bipartisan Campaign Reform Act of 2002 (BCRA), also referred to as the McCain–Feingold Act. McCain–Feingold restricts the amount of money given to political parties, which had become a way for companies and PACs to exert influence. It placed limits on total contributions to political parties, prohibited coordination between candidates and PAC campaigns, and required candidates to include personal endorsements on their political ads. It also limited advertisements run by unions and corporations thirty days before a primary election and sixty days before a general election.82
尽管《联邦选举竞选法》（FECA）的部分条款，例如对不使用联邦资金的候选人竞选活动个人支出的限制，在 1976 年的巴克利诉瓦莱奥案中被法院裁定违宪，但联邦选举委员会（FEC）仍于 1976 年开始执行竞选财务法。 81 即使有了新法律和 FEC，资金仍然源源不断地流入选举。政党和政治行动委员会利用法律漏洞向候选人捐赠巨款，新的改革势在必行。参议员约翰·麦凯恩（共和党，亚利桑那州）和拉斯·芬戈尔德（前民主党，威斯康星州）共同发起了 2002 年两党竞选改革法案 （BCRA），也称为《麦凯恩-芬戈尔德法案》。《麦凯恩-芬戈尔德法案》限制了捐赠给政党的资金数额，因为这些资金已成为公司和政治行动委员会施加影响的一种手段。该法案限制了对政党的捐款总额，禁止候选人与政治行动委员会的竞选活动进行协调，并要求候选人在其政治广告中包含个人背书。它还限制了工会和企业在初选前 30 天和普选前 60 天刊登的广告 。82

Soon after the passage of the McCain–Feingold Act, the FEC’s enforcement of the law spurred court cases challenging it. The first, McConnell v. Federal Election Commission (2003), resulted in the Supreme Court’s upholding the act’s restrictions on how candidates and parties could spend campaign contributions. But later court challenges led to the removal of limits on personal spending and ended the ban on ads run by interest groups in the days leading up to an election.83 In 2010, the Supreme Court’s ruling on Citizens United v. Federal Election Commission led to the removal of spending limits on corporations. Justices in the majority argued that the BCRA violated a corporation’s free speech rights.84
《麦凯恩-费恩戈尔德法案》通过后不久，联邦选举委员会对该法案的执行便引发了一系列挑战该法案的诉讼。首例诉讼是 2003 年的 “麦康奈尔诉联邦选举委员会案 ”，最高法院最终维持了该法案对候选人和政党如何使用竞选捐款的限制。但后来的诉讼挑战导致个人支出限制被取消，并终止了对利益集团在选举前几天投放广告的禁令。 83 2010 年，最高法院在 “公民联合诉联邦选举委员会案” 中的裁决导致对公司支出限制的取消。多数派大法官认为，《两党竞选改革法案》（BCRA）侵犯了公司的言论自由权。 84

The court ruling also allowed corporations to place unlimited money into super PACs, or Independent Expenditure-Only Committees. These organizations cannot contribute directly to a candidate, nor can they strategize with a candidate’s campaign. They can, however, raise and spend as much money as they please to support or attack a candidate, including running advertisements and hosting events.85 In 2020, the Senate Leadership Fund, a conservative super PAC, spent $293.7 million supporting conservative candidates while the Senate Majority PAC spent $230.4 million supporting liberal candidates. The total expenditure by super PACs alone was $2.13 billion in the 2020 election.86 In 2012, the super PAC “Restore Our Future” raised $153 million and spent $142 million supporting conservative candidates, including Mitt Romney. “Priorities USA Action” raised $79 million and spent $65 million supporting liberal candidates, including Barack Obama. The total expenditure by super PACs alone was $609 million in the 2012 election and $345 million in the 2014 congressional elections.87
法院的裁决还允许企业向超级政治行动委员会 （Super PAC ，即独立支出委员会）投入无限额的资金。这些组织不能直接向候选人捐款，也不能参与候选人的竞选策略制定。但是，它们可以随意筹集和花费资金来支持或攻击候选人，包括投放广告和举办活动。 85 2020 年，保守派超级政治行动委员会“参议院领导基金”（Senate Leadership Fund）花费了 2.937 亿美元支持保守派候选人，而“参议院多数党政治行动委员会”（Senate Majority PAC）则花费了 2.304 亿美元支持自由派候选人。仅超级政治行动委员会在 2020 年大选中的总支出就达到了 21.3 亿美元。 86 2012 年，超级政治行动委员会“重塑我们的未来”（Restore Our Future）筹集了 1.53 亿美元，并花费了 1.42 亿美元支持包括米特·罗姆尼在内的保守派候选人。“美国优先行动”（Priorities USA Action）筹集了 7900 万美元，并花费了 6500 万美元支持包括巴拉克·奥巴马在内的自由派候选人。仅超级政治行动委员会在 2012 年大选中的总支出就达到了 6.09 亿美元，在 2014 年国会选举中则达到了 3.45 亿美元 。87

Several limits on campaign contributions have been upheld by the courts and remain in place. Individuals may contribute up to $3,300 per candidate per election. This means a teacher living in Nebraska may contribute $3,300 to a candidate for their campaign to become to the Democratic presidential nominee, and if that candidate becomes the nominee, the teacher may contribute another $3,300 to their general election campaign. Individuals may also give $5,000 to political action committees and $41,300 to a national party committee. PACs that contribute to more than one candidate are permitted to contribute $5,000 per candidate per election, and up to $15,000 to a national party. PACs created to give money to only one candidate are limited to only $3,300 per candidate, however (Figure 7.12).88 The amounts are adjusted every two years, based on inflation. These limits are intended to create a more equal playing field for the candidates, so that candidates must raise their campaign funds from a broad pool of contributors.

[.my2]
法院已确认并维持了多项竞选捐款限额。个人每次选举最多可向每位候选人捐款 3,300 美元。这意味着，一位居住在内布拉斯加州的教师可以向一位候选人捐款 3,300 美元，支持其竞选民主党总统候选人提名；如果该候选人最终获得提名，这位教师还可以再向其大选竞选捐款 3,300 美元。个人还可以向政治行动委员会 (PAC) 捐款 5,000 美元，向全国性政党委员会捐款 41,300 美元。向多位候选人捐款的 PAC 每次选举最多可向每位候选人捐款 5,000 美元，向全国性政党委员会捐款最多可捐款 15,000 美元。然而，专门为一位候选人捐款的 PAC，每次选举最多只能向每位候选人捐款 3,300 美元（ 图 7.12 ）。 88 这些限额每两年根据通货膨胀率进行调整。这些限制旨在为候选人创造一个更加公平的竞争环境，使候选人必须从广泛的捐助者群体中筹集竞选资金。

A table titled “Contribution Limits for 2023-2024 Federal Elections”. The rows are labeled “Donors” and the columns are labeled “Recipients”. Under the column “Candidate Committee” are the values “Individual: $3,300* per election”, “Candidate Committee: $3,300 per election”, “PAC-multicandidate: $5,000 per election”, “PAC-Nonmulticandidate: $3,300 per election, “State/District/Local Party Committee: $5,000 per election (combined)”, and “National Party Committee: $5,000 per election (3)”. Under the column “PAC (1) (SSF and Nonconnected)” are the values “Individual: $5,000 per year”, “Candidate Committee: $5,000 per year”, “PAC-multicandidate: $5,000 per year”, “PAC-Nonmulticandidate: $5,000 per year”, “State/District/Local Party Committee: $5,000 per election (combined)”, and “National Party Committee: $5,000 per year”. Under the column “State/District/Local Party Committee” are the values “Individual: $10,000 per year (combined)”, “Candidate Committee: Unlimited Transfers”, “PAC-multicandidate: $5,000 per year (combined)”, “PAC-Nonmulticandidate: $10,000 per year (combined)”, “State/District/Local Party Committee: Unlimited Transfers”, and “National Party Committee: Unlimited Transfers”. Under the column “National Party Committee” are the values “Individual: $41,300* per year”, “Candidate Committee: Unlimited Transfers”, “PAC-multicandidate: $15,000 per year”, “PAC-Nonmulticandidate: $41,300* per year”, “State/District/Local Party Committee: Unlimited Transfers”, and “National Party Committee: Unlimited Transfers”. Under the column “Additional National party Committee Accounts (2)” are the values “Individual: $123,900* per account, per year”, “PAC-Multicandidate: $45,000 per account, per year”, and “PAC-Nonmulticandidate: $123,900* per account per year”. At the bottom of the table the following footnotes are listed: *Indexed for inflation in odd-numbered years. (1) “PAC” here refers to a committee that makes contributions to other federal political committees. Independent-expenditure-only political committees (sometimes called “super PACs”) may accept unlimited contributions, including from corporations and labor organizations. (2) The limits in this column apply to a national party committee’s accounts for: (i) the presidential nominating convention; (ii) election recounts and contests and other legal proceedings; and (iii) national party headquarters buildings. A party’s national committee, Senate campaign committee and House campaign committee are each considered separate national party committees with separate limits. Only a national party committee, not the parties’ national congressional campaign committees, may have an account for the presidential nominating convention. (3) Additionally, a national party committee and its Senatorial campaign committee may contribute up to $57,800 combined per campaign to each Senate candidate.

[.my2]
Figure 7.12 The Federal Election Commission has strict federal election guidelines on who can contribute, to whom, and how much. Source: "Contribution Limits for 2023-24," Federal Election Commission.

[.my2]
图 7.12 联邦选举委员会制定了严格的联邦选举捐款指导方针，规定了谁可以捐款、向谁捐款以及捐款金额。资料来源：“2023-24 年捐款限额”，联邦选举委员会。
NOMINATION STAGE  提名阶段
Although the Constitution explains how candidates for national office are elected, it is silent on how those candidates are nominated. Political parties have taken on the role of promoting nominees for offices, such as the presidency and seats in the Senate and the House of Representatives. Because there are no national guidelines, there is much variation in the nomination process. States pass election laws and regulations, choose the selection method for party nominees, and schedule the election, but the process also greatly depends on the candidates and the political parties.

[.my2]
尽管宪法规定了国家公职候选人的选举方式，但并未明确规定候选人的提名方式。政党承担了推举候选人竞选总统、参议院和众议院席位等公职的角色。由于缺乏全国统一的指导方针，各州的提名程序差异很大。各州制定选举法律法规，选择政党候选人的遴选方式，并安排选举，但具体过程也很大程度上取决于候选人和政党。

States, through their legislatures, often influence the nomination method by paying for an election to help parties identify the nominee the voters prefer. Many states fund elections because they can hold several nomination races at once. In 2020, many voters had to choose a presidential nominee, U.S. Senate nominee, House of Representatives nominee, and state-level legislature nominee for their parties.

[.my2]
各州通常通过立法机构影响提名方式，他们会出资举办选举，帮助政党确定选民属意的候选人。许多州之所以资助选举，是因为它们可以同时举行多场提名竞选。2020年，许多选民需要为各自政党选出总统候选人、参议院候选人、众议院候选人以及州级立法机构候选人。

The most common method of picking a party nominee for state, local, and presidential contests is the primary. Party members use a ballot to indicate which candidate they desire for the party nominee. Despite the ease of voting using a ballot, primary elections have a number of rules and variations that can still cause confusion for citizens. In a closed primary, only members of the political party selecting nominees may vote. A registered Green Party member, for example, is not allowed to vote in the Republican or Democratic primary. Parties prefer this method, because it ensures the nominee is picked by voters who legitimately support the party. An open primary allows all voters to vote. In this system, a Green Party member is allowed to pick either a Democratic or Republican ballot when voting.

[.my2]
在州、地方和总统选举中，最常见的政党提名人选产生方式是党内初选。党员们通过选票表明他们支持的候选人。尽管投票方式简单便捷，但初选的规则和形式仍然繁多，容易让选民感到困惑。在封闭式初选中，只有参与提名的政党成员才能投票。例如，注册的绿党成员不能参加共和党或民主党的初选。政党倾向于这种方式，因为它能确保提名人由真正支持该党的选民选出。 开放式初选则允许所有选民投票。在这种制度下，绿党成员在投票时可以选择民主党或共和党的选票。

For state-level office nominations, or the nomination of a U.S. Senator or House member, some states use the top-two primary method. A top-two primary, sometimes called a jungle primary, pits all candidates against each other, regardless of party affiliation. The two candidates with the most votes become the final candidates for the general election. Thus, two candidates from the same party could run against each other in the general election. In one California congressional district, for example, four Democrats and two Republicans all ran against one another in the June 2012 primary. The two Republicans received the most votes, so they ran against one another in the general election in November.89 In 2016, thirty-four candidates filed to run to replace Senator Barbara Boxer (D-CA). In the end, two Democratic women of color emerged to compete head-to-head in the general election. California attorney general Kamala Harris eventually won the seat on Election Day, helping to quadruple the number of women of color in the U.S. Senate overnight. She subsequently ran for vice president in 2020 on the Democratic ticket and now serves in that capacity. More often than not, however, the top-two system is used in state-level elections for non-partisan elections, in which none of the candidates are allowed to declare a political party.

[.my2]
对于州级公职提名，或美国参议员或众议员的提名，一些州采用“前两名初选”制度。这种初选制度有时也被称为“丛林初选”，它让所有候选人相互竞争，不分党派。得票最多的两名候选人将成为最终进入大选的候选人。因此，同一党派的两名候选人也可能在大选中对决。例如，在加利福尼亚州的一个国会选区，2012 年 6 月的初选中，四名民主党人和两名共和党人相互竞争。两名共和党人得票最多，因此他们在 11 月的大选中展开角逐 。2016 年，共有 34 名候选人报名竞选接替芭芭拉·博克瑟（加州民主党参议员）的席位。最终，两名有色人种女性民主党人脱颖而出，在大选中展开直接竞争。加州总检察长卡马拉·哈里斯最终在选举日赢得了该席位，一夜之间使美国参议院的有色人种女性人数翻了两番。她随后于 2020 年代表民主党竞选副总统，目前担任该职务。然而，在州级选举中，通常采用的是两轮投票制，即非党派选举，候选人不得表明所属政党。

In general, parties do not like nominating methods that allow non-party members to participate in the selection of party nominees. In 2000, the Supreme Court heard a case brought by the California Democratic Party, the California Republican Party, and the California Libertarian Party.90 The parties argued that they had a right to determine who associated with the party and who participated in choosing the party nominee. The Supreme Court agreed, limiting the states’ choices for nomination methods to closed and open primaries.

[.my2]
一般来说，各政党都不喜欢允许非党员参与党内候选人提名的提名方式。2000 年，最高法院审理了加州民主党、加州共和党和加州自由党提起的一起诉讼。90 各政党辩称，他们有权决定谁可以与本党联系，以及谁可以参与党内候选人的选举。最高法院同意了这一观点，将各州的提名方式限制在封闭式初选和开放式初选之间。

Despite the common use of the primary system, at least six states (Alaska, Colorado, Hawaii, Idaho, Iowa, and Nevada) regularly use caucuses for presidential, state, and local-level nominations. A caucus is a meeting of party members in which nominees are selected informally. Caucuses are less expensive than primaries because they rely on voting methods such as dropping marbles in a jar, placing names in a hat, standing under a sign bearing the candidate’s name, or taking a voice vote. Volunteers record the votes and no poll workers need to be trained or compensated. The party members at the caucus also help select delegates, who represent their choice at the party’s state- or national-level nominating convention.

[.my2]
尽管初选制度普遍采用，但至少有六个州（阿拉斯加州、科罗拉多州、夏威夷州、爱达荷州、爱荷华州和内华达州）仍然定期举行党团会议，以进行总统、州和地方层面的提名。 党团会议是党员之间的非正式会议，旨在选出候选人。党团会议比初选成本更低，因为它采用的投票方式包括：往罐子里投弹珠、把名字放进帽子里、站在写有候选人名字的牌子下投票，或者进行口头表决。志愿者负责记录投票结果，无需培训或支付工作人员报酬。参加党团会议的党员还会协助选出代表 ，这些代表将在党的州级或全国级提名大会上代表他们所支持的候选人。

The Iowa Democratic Caucus is well-known for its spirited nature. The party’s voters are asked to align themselves into preference groups, which often means standing in a room or part of a room that has been designated for the candidate of choice. The voters then get to argue and discuss the candidates, sometimes in a very animated and forceful manner. After a set time, party members are allowed to realign before the final count is taken. The caucus leader then determines how many members support each candidate, which determines how many delegates each candidate will receive.

[.my2]
爱荷华州民主党党团会议以其热烈的气氛而闻名。党内选民需要根据自己的支持倾向加入不同的支持小组，这通常意味着他们要站在一个或房间的某个特定区域，该区域是为各自支持的候选人指定的。之后，选民们可以就候选人展开辩论和讨论，有时辩论会非常激烈且充满力量。经过一段规定的时间后，党员们可以重新调整支持顺序，之后进行最终计票。党团会议领导人随后会确定每位候选人的支持人数，从而决定每位候选人将获得的代表人数。

The caucus has its proponents and opponents. Many argue that it is more interesting than the primary and brings out more sophisticated voters, who then benefit from the chance to debate the strengths and weaknesses of the candidates. The caucus system is also more transparent than ballots. The local party members get to see the election outcome and pick the delegates who will represent them at the national convention. There is less of a possibility for deception or dishonesty. Opponents point out that caucuses take two to three hours and are intimidating to less experienced voters. These factors, they argue, lead to lower voter turnout. And they have a point—voter turnout for a caucus is generally 20 percent lower than for a primary.91
党团会议既有支持者也有反对者。许多人认为，党团会议比初选更有意思，能吸引更多成熟的选民参与，让他们有机会辩论候选人的优缺点。党团会议制度也比投票更透明。地方党员可以看到选举结果，并选出代表他们参加全国代表大会的代表。这样一来，欺骗或舞弊的可能性就更小了。反对者指出，党团会议需要两到三个小时，会让经验不足的选民感到畏惧。他们认为，这些因素会导致投票率下降。他们的观点不无道理——党团会议的投票率通常比初选低 20 %。

Regardless of which nominating system the states and parties choose, states must also determine which day they wish to hold their nomination. When the nominations are for state-level office, such as governor, the state legislatures receive little to no input from the national political parties. In presidential election years, however, the national political parties pressure most states to hold their primaries or caucuses in March or later. Only Iowa, New Hampshire, and South Carolina are given express permission by the national parties to hold presidential primaries or caucuses in January or February (Figure 7.13). Both political parties protect the three states’ status as the first states to host caucuses and primaries, due to tradition and the relative ease of campaigning in these smaller states.

[.my2]
无论各州和政党选择何种提名制度 ，各州还必须决定在哪一天举行提名。如果提名的是州级职位，例如州长，州议会几乎不受全国性政党的影响。然而，在总统选举年，全国性政党会向大多数州施压，要求它们在三月或之后举行初选或党团会议。只有爱荷华州、新罕布什尔州和南卡罗来纳州获得了全国性政党的明确许可，可以在一月或二月举行总统初选或党团会议（ 图 7.13 ）。由于传统以及在这些小州开展竞选活动相对容易，两党都维护这三个州作为首批举行党团会议和初选州的地位。

Image A is of Bernie Sanders speaking to a group of seated people. Image B is of John Ellis “Jeb” Bush shaking hands with another person.

[.my2]
Figure 7.13 Presidential candidates often spend a significant amount of time campaigning in states with early caucuses or primaries. In September 2015, Senator Bernie Sanders (a), a candidate for the Democratic nomination, speaks at the Amherst Democrats BBQ in Amherst, New Hampshire. In July 2015, John Ellis “Jeb” Bush (b), former Republican governor of Florida, greets the public at the Fourth of July parade in Merrimack, New Hampshire. (credit a, b: modification of work by Marc Nozell)
图 7.13 总统候选人通常会花费大量时间在举行早期党团会议或初选的州进行竞选活动。2015 年 9 月，民主党总统候选人伯尼·桑德斯参议员（a）在新罕布什尔州阿默斯特市举行的阿默斯特民主党烧烤活动上发表讲话。2015 年 7 月，佛罗里达州前共和党州长约翰·埃利斯·“杰布”·布什（b）在新罕布什尔州梅里马克市的 7 月 4 日独立日游行中向公众致意。（图片 a、b：改编自 Marc Nozell 的作品）
Other states, especially large states like California, Florida, Michigan, and Wisconsin, often are frustrated that they must wait to hold their presidential primary elections later in the season. Their frustration is reasonable: candidates who do poorly in the first few primaries often drop out entirely, leaving fewer candidates to run in caucuses and primaries held in February and later. In 2008, California, New York, and several other states disregarded the national party’s guidelines and scheduled their primaries the first week of February. In response, Florida and Michigan moved their primaries to January and many other states moved forward to March. This was not the first time states participated in frontloading and scheduled the majority of the primaries and caucuses at the beginning of the primary season. It was, however, one of the worst occurrences. States have been frontloading since the 1976 presidential election, with the problem becoming more severe in the 1992 election and later.92
其他州，尤其是像加利福尼亚州、佛罗里达州、密歇根州和威斯康星州这样的大州，常常因为必须等到选举季后期才能举行总统初选而感到沮丧。他们的沮丧不无道理：在最初几场初选中表现不佳的候选人往往会彻底退出，导致参加 2 月及之后举行的党团会议和初选的候选人数量减少。2008 年，加利福尼亚州、纽约州和其他几个州无视全国党的指导方针，将初选安排在 2 月的第一周。作为回应，佛罗里达州和密歇根州将初选提前到 1 月，许多其他州则提前到 3 月。这并非各州首次提前举行初选 ，将大部分初选和党团会议安排在初选季初期。然而，这是最严重的事件之一。自 1976 年总统大选以来，各州就一直在提前举行初选 ，而这一问题在 1992 年及之后的选举中变得更加严重。

Political parties allot delegates to their national nominating conventions based on the number of registered party voters in each state. California, the state with the most Democrats, sent 494 delegates to the 2020 Democratic National Convention, while Wyoming, with far fewer Democrats, sent only 14 delegates.93 When the national political parties want to prevent states from frontloading, or doing anything else they deem detrimental, they can change the state’s delegate count, which in essence increases or reduces the state’s say in who becomes the presidential nominee. In 1996, the Republicans offered bonus delegates to states that held their primaries and caucuses later in the nominating season.94 In 2008, the national parties ruled that only Iowa, South Carolina, and New Hampshire could hold primaries or caucuses in January. Both parties also reduced the number of delegates from Michigan and Florida as punishment for those states’ holding early primaries.95 Despite these efforts, candidates in 2008 had a very difficult time campaigning during the tight window caused by frontloading.

[.my2]
各政党根据各州注册党员人数分配参加全国提名大会的代表名额。加利福尼亚州是民主党选民最多的州，向 2020 年民主党全国代表大会派出了 494 名代表，而民主党选民人数少得多的怀俄明州只派出了 14 名代表。 93 当全国性政党想要阻止各州提前举行初选或采取其他他们认为不利于党内选举的行动时，他们可以改变该州的代表人数，这实际上会增加或减少该州在总统候选人提名中的话语权。1996 年，共和党向那些在提名季后期举行初选和党团会议的州提供了额外的代表名额。 94 2008 年，全国性政党规定，只有爱荷华州、南卡罗来纳州和新罕布什尔州可以在 1 月份举行初选或党团会议。两党还减少了密歇根州和佛罗里达州的代表人数，以惩罚这两个州提前举行初选。 95 尽管做出了这些努力，但 2008 年的候选人在竞选活动时间窗口很短的情况下，由于提前投票造成的困难，竞选活动开展得非常困难。

One of the criticisms of the modern nominating system is that parties today have less influence over who becomes their nominee. In the era of party “bosses,” candidates who hoped to run for president needed the blessing and support of party leadership and a strong connection with the party’s values. Now, anyone can run for a party’s nomination. The candidates with enough money to campaign the longest, gaining media attention, momentum, and voter support are more likely to become the nominee than candidates without these attributes, regardless of what the party leadership wants.

[.my2]
现代提名制度的一大弊端在于，如今政党对最终提名人的影响力有所下降。在政党“大佬”盛行的时代，任何希望竞选总统的候选人都需要得到党内领导层的认可和支持，并且与党的价值观紧密相连。而现在，任何人都可以竞选党内提名。那些拥有足够资金进行长期竞选、获得媒体关注、积累势头和赢得选民支持的候选人，比那些不具备这些条件的候选人更有可能最终获得提名，而这与党内领导层的意愿无关。

This new reality has dramatically increased the number of politically inexperienced candidates running for national office. In 2012, for example, eleven candidates ran multistate campaigns for the Republican nomination. Dozens more had their names on one or two state ballots. With a long list of challengers, candidates must find more ways to stand out, leading them to espouse extreme positions or display high levels of charisma. Add to this that primary and caucus voters are often more extreme in their political beliefs, and it is easy to see why fewer moderates become party nominees. The 2016 primary campaign by President Donald Trump shows that grabbing the media’s attention with fiery partisan rhetoric can get a campaign started strong. This does not guarantee a candidate will make it through the primaries, however. In 2020, the most moderate of the front-runners (Joe Biden) won the Democratic nomination.

[.my2]
这种新现实极大地增加了竞选全国性公职的政治经验不足的候选人数量。例如，2012 年，有 11 位候选人在多个州开展竞选活动，力图获得共和党提名。另有数十位候选人的名字出现在一到两个州的选票上。面对众多挑战者，候选人必须找到更多脱颖而出的方法，这导致他们要么拥护极端立场，要么展现出极高的个人魅力。此外，初选和党团会议的选民往往政治立场更为极端，因此不难理解为什么温和派候选人最终获得党内提名的人数较少。唐纳德· 特朗普总统在 2016 年总统初选中的竞选活动表明，用激烈的党派言论吸引媒体的注意力可以使竞选活动迅速启动。但这并不能保证候选人能够赢得初选。2020 年，领先的候选人中最温和的乔·拜登最终赢得了民主党提名。

Link to Learning  学习链接
Take a look at Campaigns & Elections to see what hopeful candidates are reading.

[.my2]
浏览 “竞选与选举” 栏目，看看有抱负的候选人都在读些什么。

CONVENTION SEASON  会议季
Once it is clear who the parties’ nominees will be, presidential and gubernatorial campaigns enter a quiet period. Candidates run fewer ads and concentrate on raising funds for the fall. This is a crucial time because lack of money can harm their chances. The media spends much of the summer keeping track of the fundraising totals while the political parties plan their conventions. State parties host state-level conventions during gubernatorial elections, while national parties host national conventions during presidential election years.

[.my2]
一旦各党派的候选人确定，总统和州长竞选活动便进入一段平静期。候选人减少广告投放，集中精力为秋季的竞选活动筹款。这段时期至关重要，因为资金短缺会严重影响他们的胜算。媒体会在夏季的大部分时间里追踪筹款总额，而各政党则忙于筹备党代会。州长选举年，各州政党会召开州级党代会；总统选举年，全国性政党则会召开全国党代会。

Party conventions are typically held between June and September, with state-level conventions earlier in the summer and national conventions later. Conventions normally last four to five days, with days devoted to platform discussion and planning and nights reserved for speeches (Figure 7.14). Local media covers the speeches given at state-level conventions, showing speeches given by the party nominees for governor and lieutenant governor, and perhaps important guests or the state’s U.S. senators. The national media covers the Democratic and Republican conventions during presidential election years, mainly showing the speeches. Some cable networks broadcast delegate voting and voting on party platforms. Members of the candidate’s family and important party members generally speak during the first few days of a national convention, with the vice presidential nominee speaking on the next-to-last night and the presidential candidate on the final night. The two chosen candidates then hit the campaign trail for the general election. The party with the incumbent president holds the later convention, so in 2016, the Democrats held their convention after the Republicans. In 2020, with the COVID-19 pandemic raging, both major parties modified their conventions to involve fewer people. The Republicans had some in-person gatherings, but mostly met virtually, while the Democrats were almost entirely virtual.96
党代会通常在六月至九月间举行，州级党代会在夏季早些时候举行，全国党代会则在之后举行。党代会一般持续四到五天，白天用于讨论和规划党纲，晚上则用于发表演讲（ 图 7.14 ）。地方媒体会报道州级党代会上的演讲，播出州长和副州长候选人的演讲，以及一些重要嘉宾或该州联邦参议员的演讲。在总统选举年，全国媒体会报道民主党和共和党的党代会，主要播出演讲内容。一些有线电视网会直播代表投票和党纲投票。候选人的家人和重要的党内成员通常会在全国党代会的前几天发言，副总统候选人在倒数第二个晚上发言，总统候选人在最后一个晚上发言。两​​位候选人随后便会开始竞选活动。现任总统所在的政党会举行较晚的党代会，因此在 2016 年，民主党的党代会是在共和党之后举行的。 2020 年，新冠疫情肆虐，两大政党都调整了党代会形式，以减少参与人数。共和党举行了一些线下集会，但大部分时间都在线上进行；而民主党则几乎完全采用线上方式 。96

Image A is of Reince Priebus standing at a podium in front of a crowd of people. Behind Priebus is an elephant symbol, colored red and blue with three white stars along its back. Image B is of a hat with an American flag, red and blue stars, and a political pin attached to it.

[.my2]
Figure 7.14 Reince Priebus, chairman of the Republican National Committee, opens the Republican National Convention in Tampa, Florida, on August 28, 2012 (a). Pageantry and symbolism, such as the flag motifs and political buttons shown on this Wisconsin attendee’s hat (b), reign supreme during national conventions. (credit a, b: modification of work by Mallory Benedict/PBS NewsHour)
图 7.14 2012 年 8 月 28 日，共和党全国委员会主席赖因斯·普里巴斯在佛罗里达州坦帕市宣布共和党全国代表大会开幕 (a)。在全国代表大会期间，盛大的场面和象征意义，例如这位威斯康星州与会者帽子上的旗帜图案和政治徽章 (b)，都占据着主导地位。（图片来源：a、b，改编自 Mallory Benedict/PBS NewsHour 的作品）
There are rarely surprises at the modern convention. Thanks to party rules, the nominee for each party is generally already clear. In 2008, John McCain had locked up the Republican nomination in March by having enough delegates, while in 2012, President Obama was an unchallenged incumbent and hence people knew he would be the nominee. In 2016, both apparent nominees (Democrat Hillary Clinton and Republican Donald Trump) faced primary opponents who stayed in the race even when the nominations were effectively sewn up—Democrat Bernie Sanders and Republican Ted Cruz—though no “convention surprise” took place. The naming of the vice president is generally not a surprise either. Even if a presidential nominee tries to keep it a secret, the news often leaks out before the party convention or official announcement. In 2004, the media announced John Edwards was John Kerry’s running mate. The Kerry campaign had not made a formal announcement, but an amateur photographer had taken a picture of Edwards’ name being added to the candidate’s plane and posted it to an aviation message board. In 2020, strong rumors circulated about Senator Kamala Harris (D-CA) being tapped for the ticket, with confirmation of that choice coming days later.97
现代党代会鲜有意外发生。由于党章规定，各党的候选人通常早已确定。2008 年，约翰·麦凯恩在 3 月份就凭借足够的代表票锁定了共和党的提名；2012 年，奥巴马总统作为现任总统，无人挑战，因此人们都知道他会是最终的候选人。2016 年，两位显而易见的候选人（民主党的希拉里·克林顿和共和党的唐纳德·特朗普）在党内初选中都面临着挑战，尽管提名实际上已经尘埃落定，但他们仍然坚持参选——民主党的伯尼·桑德斯和共和党的特德·克鲁兹——尽管如此，党代会上并没有出现任何“意外”。副总统人选的确定通常也并不令人意外。即使总统候选人试图保密，消息也往往会在党代会或正式宣布之前泄露出去。2004 年，媒体就曾报道约翰·爱德华兹是约翰·克里的竞选搭档。克里竞选团队尚未正式宣布，但一位业余摄影师拍下了爱德华兹的名字被添加到候选人飞机上的照片，并将其发布到了一个航空论坛上。2020 年，关于加州民主党参议员卡马拉·哈里斯被选为竞选搭档的传闻甚嚣尘上，几天后这一选择得到了证实 。97

Despite the lack of surprises, there are several reasons to host traditional conventions. First, the parties require that the delegates officially cast their ballots. Delegates from each state come to the national party convention to publicly state who their state’s voters selected as the nominee.

[.my2]
尽管缺乏惊喜，但举办传统党代会仍有几个理由。首先，各党要求代表们正式投票。各州代表齐聚全国党代会，公开宣布本州选民选出的候选人。

Second, delegates will bring state-level concerns and issues to the national convention for discussion, while local-level delegates bring concerns and issues to state-level conventions. This list of issues that concern local party members, like limiting abortions in a state or removing restrictions on gun ownership, are called planks, and they will be discussed and voted upon by the delegates and party leadership at the convention. Just as wood planks make a platform, issues important to the party and party delegates make up the party platform. The parties take the cohesive list of issues and concerns and frame the election around the platform. Candidates will try to keep to the platform when campaigning, and outside groups that support them, such as super PACs, may also try to keep to these issues.

[.my2]
其次，各州代表会将州级层面的关切和议题带到全国代表大会进行讨论，而地方代表则会将关切和议题带到州级代表大会。这些关乎地方党员的议题清单，例如限制堕胎或取消枪支拥有限制等，被称为 “纲领” ，将在全国代表大会上由代表和党领导层进行讨论和投票表决。正如木板构成平台一样，对党和党代表而言重要的议题构成了党纲 。各党会根据这些连贯的议题和关切清单来构建选举框架。候选人在竞选活动中会努力遵循党纲，支持他们的外部团体，例如超级政治行动委员会（Super PACs），也会努力围绕这些议题展开活动。

Third, conventions are covered by most news networks and cable programs. This helps the party nominee get positive attention while surrounded by loyal delegates, family members, friends, and colleagues. For presidential candidates, this positivity often leads to a bump in popularity, so the candidate gets a small increase in favorability. If a candidate does not get the bump, however, the campaign manager has to evaluate whether the candidate is connecting well with the voters or is out of step with the party faithful. In 2004, John Kerry spent the Democratic convention talking about getting U.S. troops out of the war in Iraq and increasing spending at home. Yet after his patriotic and positive convention, Gallup recorded no convention bump and the voters did not appear more likely to vote for him.

[.my2]
第三，大多数新闻网络和有线电视节目都会报道党代会。这有助于党内候选人在忠实代表、家人、朋友和同事的簇拥下获得正面关注。对于总统候选人而言，这种正面影响通常会带来支持率的提升，使候选人的支持率略有上升。然而，如果候选人的支持率没有上升，竞选经理就必须评估候选人是否与选民建立了良好的联系，或者是否与党内忠实支持者的立场相悖。2004年，约翰·克里在民主党全国代表大会上大谈特谈从伊拉克撤军和增加国内开支。然而，在他发表了爱国主义和积极向上的演讲之后，盖洛普民调显示他的支持率并未出现党代会上升，选民似乎也没有更倾向于投票给他。

GENERAL ELECTIONS AND ELECTION DAY
大选和选举日
The general election campaign period occurs between mid-August and early November. These elections are simpler than primaries and conventions, because there are only two major party candidates and a few minor party candidates. About 50 percent of voters will make their decisions based on party membership, so the candidates will focus on winning over independent voters and visiting states where the election is close.98 In 2016, both candidates sensed shifts in the electorate that led them to visit states that were not recently battleground states. Clinton visited Republican stronghold Arizona as Latino voter interest surged. Defying conventional campaign movements, Trump spent many hours over the last days of the campaign in the Democratic Rust Belt states, namely Michigan and Wisconsin. President Trump ended up winning both states and industrial Pennsylvania by narrow margins, allowing him to achieve a comfortable majority in the Electoral College. In 2020, during the COVID-19 pandemic, the two major-party nominees adopted very different approaches. In seeking re-election, President Trump eschewed CDC recommendations for social distancing and held large in-person rallies, while Joe Biden made fewer public appearances, which were largely carried to audiences virtually.99
大选竞选期通常在 8 月中旬至 11 月初之间。与初选和党代表大会相比，大选流程较为简单，因为只有两大党候选人和少数小党候选人。约 50%的选民会根据党派归属做出选择，因此候选人会着重争取独立选民的支持，并走访选情胶着的州。 2016 年，两位候选人都敏锐地察觉到选民结构的变化，因此他们走访了一些并非近期摇摆州的州。希拉里·克林顿访问了共和党的大本营亚利桑那州，因为当时拉丁裔选民的投票热情高涨。而特朗普则打破常规，在竞选的最后几天，花费大量时间在民主党的传统票仓——密歇根州和威斯康星州——进行竞选活动。最终，特朗普以微弱优势赢得了这两个州以及宾夕法尼亚州，从而在选举人团中获得了稳固的多数席位。2020 年，在新冠疫情期间，两大党候选人采取了截然不同的竞选策略。为了寻求连任，特朗普总统无视疾控中心关于保持社交距离的建议，举行了大型线下竞选集会，而乔·拜登则减少了公开露面，其活动大多以线上形式进行。

Debates are an important element of the general election season, allowing voters to see candidates answer questions on policy and prior decisions. While most voters think only of presidential debates, the general election season sees many debates. In a number of states, candidates for governor are expected to participate in televised debates, as are candidates running for the U.S. Senate. Debates not only give voters a chance to hear answers, but also to see how candidates hold up under stress. Because television and the Internet make it possible to stream footage to a wide audience, modern campaign managers understand the importance of a debate (Figure 7.15).

[.my2]
辩论是普选季的重要组成部分，让选民有机会看到候选人回答有关政策和过往决定的问题。虽然大多数选民只关注总统辩论 ， 但普选季期间的辩论种类繁多。在一些州，州长候选人和参议员候选人都需要参加电视辩论。辩论不仅让选民有机会听到候选人的回答，还能让他们了解候选人在压力下的表现。由于电视和互联网使得向广大观众直播辩论视频成为可能，现代竞选经理们深知辩论的重要性（ 图 7.15 ）。

An image of three people watching a television. On the television screen are Mitt Romney and Barack Obama.

[.my2]
Figure 7.15 Sailors on the USS McCampbell, based out of Yokosuka, Japan, watch the first presidential debate between President Barack Obama and former Massachusetts governor Mitt Romney on October 4, 2012.

[.my2]
图 7.15 2012 年 10 月 4 日，驻扎在日本横须贺的美国海军 “麦坎贝尔” 号驱逐舰上的水兵们正在观看巴拉克·奥巴马总统和前马萨诸塞州州长米特·罗姆尼之间的第一场总统辩论。
In 1960, the first televised presidential debate showed that answering questions well is not the only way to impress voters. Senator John F. Kennedy, the Democratic nominee, and Vice President Richard Nixon, the Republican nominee, prepared in slightly different ways for their first of four debates. Although both studied answers to possible questions, Kennedy also worked on the delivery of his answers, including accent, tone, facial displays, and body movements, as well as overall appearance. Nixon, however, was ill in the days before the debate and appeared sweaty and gaunt. He also chose not to wear makeup, a decision that left his pale, unshaven face vulnerable.100 Interestingly, while people who watched the debate thought Kennedy won, those listening on radio saw the debate as more of a draw.

[.my2]
1960 年，首场电视总统辩论表明，回答问题并非赢得选民青睐的唯一途径。民主党候选人约翰·F·肯尼迪参议员和共和党候选人、副总统理查德·尼克松为四场辩论中的首场辩论做了略有不同的准备。虽然两人都研究了可能被问到的问题的答案，但肯尼迪还着重练习了回答的方式，包括口音、语调、面部表情、肢体动作以及整体形象。而尼克松在辩论前几天生病了，显得满头大汗、面容憔悴。他还选择不化妆，这使得他苍白、未刮胡子的脸显得格外脆弱。有趣的是，虽然现场观众普遍认为肯尼迪获胜，但收听广播的听众却觉得这场辩论势均力敌。

Insider Perspective  内部视角
Inside the Debate  辩论内幕
Debating an opponent in front of sixty million television voters is intimidating. Most presidential candidates spend days, if not weeks, preparing. Newspapers and cable news programs proclaim winners and losers, and debates can change the tide of a campaign. Yet, Paul Begala, a strategist with Bill Clinton’s 1992 campaign, saw debates differently.

[.my2]
在六千万电视观众面前与对手辩论令人胆寒。大多数总统候选人都会花费数天甚至数周的时间进行准备。报纸和有线电视新闻节目会宣布胜负，辩论结果也可能左右选情。然而，曾担任比尔·克林顿 1992 年竞选策略师的保罗· 贝加拉却对辩论有着不同的看法。

In one of his columns for CNN, Begala recommends that candidates relax and have a little fun. Debates are relatively easy, he says, more like a scripted program than an interview that puts candidates on the spot. They can memorize answers and deliver them convincingly, making sure they hit their mark. Second, a candidate needs a clear message explaining why the voters should pick them. Is the candidate a needed change? Or the only experienced candidate? If the candidate’s debate answers reinforce this message, the voters will remember. Third, candidates should be humorous, witty, and comfortable with their knowledge. Trying to be too formal or cramming information at the last minute will cause the candidate to be awkward or get overwhelmed. Finally, a candidate is always on camera. Making faces, sighing at an opponent, or simply making a mistake gives the media something to discuss and can cause a loss. In essence, Begala argues that if candidates wish to do well, preparation and confidence are key factors.101
贝加拉在为 CNN 撰写的一篇专栏文章中建议候选人放松心情，享受辩论的乐趣。他指出，辩论相对轻松，更像是事先准备好的节目，而不是让候选人措手不及的面试。他们可以事先准备好答案，并能令人信服地表达出来，确保达到预期效果。其次，候选人需要传递一个清晰的信息，解释选民为何应该选择他们。这位候选人是否能带来必要的改变？或者是唯一一位经验丰富的候选人？如果候选人在辩论中的回答强化了这一信息，选民就会记住他们。第三，候选人应该幽默风趣，并且对自己的知识储备充满自信。过于正式或临时抱佛脚会让候选人显得尴尬或不知所措。最后，候选人始终处于镜头前 。做鬼脸、对对手叹气，或者仅仅是犯错，都会给媒体提供谈资，甚至可能导致败选。总之，贝加拉认为，如果候选人想要取得好成绩，充分的准备和十足的自信是关键因素。

Is Begala’s advice good? Why or why not? What positives or negatives would make a candidate’s debate performance stand out for you as a voter?
贝加拉的建议好吗？为什么？作为选民，你认为候选人在辩论中表现的哪些优点或缺点会脱颖而出？

While debates are not just about a candidate’s looks, most debate rules contain language that prevents candidates from artificially enhancing their physical qualities. For example, prior rules have prohibited shoes that increase a candidate’s height, banned prosthetic devices that change a candidate’s physical appearance, and limited camera angles to prevent unflattering side and back shots. Candidates and their campaign managers are aware that visuals matter.

[.my2]
虽然辩论并非仅仅关乎候选人的外貌，但大多数辩论规则都包含禁止候选人人为美化自身外貌的条款。例如，此前的规则禁止穿增高鞋，禁止使用改变候选人外貌的假肢，并限制摄像机角度以避免拍摄到不雅的侧面和背面镜头。候选人及其竞选团队都深知视觉形象的重要性。

Debates are generally over by the end of October, just in time for Election Day. Beginning with the election of 1792, presidential elections were to be held in the thirty-four days prior to the “first Wednesday in December.”102 In 1845, Congress passed legislation that moved the presidential Election Day to the first Tuesday after the first Monday in November, and in 1872, elections for the House of Representatives were also moved to that same Tuesday.103 The United States was then an agricultural country, and because a number of states restricted voting to property-owning males over twenty-one, farmers made up nearly 74 percent of voters.104 The tradition of Election Day to fall in November allowed time for the lucrative fall harvest to be brought in and the farming season to end. And, while not all members of government were of the same religion, many wanted to ensure that voters were not kept from the polls by a weekend religious observance. Finally, business and mercantile concerns often closed their books on the first of the month. Rather than let accounting get in the way of voting, the bill’s language forces Election Day to fall between the second and eighth of the month.

[.my2]
辩论通常在十月底结束，正好赶上选举日。从 1792 年大选开始，总统选举定于“十二月的第一个星期三”之前的 34 天内举行。 102 1845 年，国会通过立法，将总统选举日改为十一月第一个星期一之后的第一个星期二；1872 年，众议院选举也改为同一星期二。 103 当时的美国是一个农业国家，由于许多州将投票权限制在 21 岁以上拥有财产的男性，农民占选民总数的近 74%。 104 选举日定在十一月的传统使得农民有时间收割利润丰厚的秋收作物，结束农忙季节。而且，虽然并非所有政府成员都信奉同一宗教，但许多人希望确保选民不会因为周末的宗教活动而错过投票。最后，商业机构通常在月初结束营业。该法案的措辞规定，选举日必须在每月 2 日至 8 日之间，而不是让会计工作妨碍投票。

THE ELECTORAL COLLEGE  选举团
Once the voters have cast ballots in November and all the election season madness comes to a close, races for governors and local representatives may be over, but the constitutional process of electing a president has only begun. The electors of the Electoral College travel to their respective state capitols and cast their votes in mid-December, often by signing a certificate recording their vote. In most states, electors cast their ballots for the candidate who won the plurality of votes in their state, a winner-take-all system. Nebraska and Maine employ a district system, which allows them to allocate two votes to the plurality winner and one additional vote to candidates who win pluralities in individual state districts. Regardless of the method, once the electoral votes are allocated the states then forward the certificates to the U.S. Senate.

[.my2]
11 月选民投票完毕，选举季的喧嚣落下帷幕后，州长和地方代表的竞选或许已经结束，但总统选举的宪法程序才刚刚开始。 选举团的选举人会在 12 月中旬前往各自州的首府投票，通常会签署一份记录投票结果的证书。在大多数州，选举人会投票给在本州获得最多选票的候选人，即“赢者通吃”制度。内布拉斯加州和缅因州则采用选区制，允许将两张选举人票分配给在本州获得最多选票的候选人，并将额外的一张选举人票分配给在各自选区获得最多选票的候选人。无论采用何种方式，一旦选举人票分配完毕，各州都会将证书送交美国参议院。

The number of Electoral College votes granted to each state equals the total number of representatives and senators that state has in the U.S. Congress or, in the case of Washington, DC, as many electors as it would have if it were a state. The number of representatives may fluctuate based on state population, which is determined every ten years by the U.S. Census, mandated by Article I, Section 2, of the Constitution. However, since the Permanent Apportionment Act of 1929, the total number of representatives in Congress has been fixed at 435. Accordingly, for the 2024 presidential election, there will be a total of 538 electors in the Electoral College, and a majority of 270 electoral votes is required to win the presidency.

[.my2]
每个州在选举人团中的票数等于该州在美国国会的众议员和参议员总数；如果是华盛顿特区，则等于其作为一个州所拥有的选举人票数。众议员人数可能根据各州人口数量而有所波动，人口数量由美国人口普查局每十年确定一次，这是美国宪法第一条第二款规定的。然而，自 1929 年《永久选区划分法》生效以来，国会众议员总数固定为 435 人。因此，在 2024 年总统选举中，选举人团共有 538 名选举人，赢得总统职位需要获得 270 张选举人票的多数票。

Once the electoral votes have been read by the president of the Senate (i.e., the vice president of the United States) during a special joint session of Congress in January, the presidential candidate who received the majority of electoral votes is officially named president. Should a tie occur, the sitting House of Representatives elects the president, with each state receiving one vote. While this rarely occurs, both the 1800 and the 1824 elections were decided by the House of Representatives. As election night 2016 played out after the polls closed, one such scenario was in play for a tie. However, the states that Hillary Clinton needed to make that tie were lost narrowly to Trump. Had the tie occurred, the Republican House would have likely selected Trump as president anyway. As Election Day 2020 neared, the context favored Biden, yet it was still possible that Trump might narrowly win key battleground states and find a way to win the Electoral College. This did not occur, as Biden won the popular vote and the Electoral College decisively. Still, based on the erroneous assumption that the election had been stolen, thousands of Trump supporters stormed the U.S. Capitol building to prevent the House and Senate from completing a final tabulation of Biden's victory. While many of the "Stop The Steal" protesters remained outside the building and undertook no violent actions, some organized groups donned paramilitary gear, including helmets and combat vests; individuals were filmed breaking open windows to gain entry. The attempt did not succeed, however, and the votes were finalized in the early overnight hours of January 7th with Vice President Mike Pence presiding.

[.my2]
在1月份国会特别联席会议上，参议院议长（即美国副总统）宣读选举人票后，获得多数选举人票的总统候选人将被正式任命为总统。如果出现平局，则由众议院选举总统，每个州拥有一票。虽然这种情况很少发生，但1800年和1824年的总统选举都是由众议院决定的。2016年大选之夜，投票结束后，就出现了平局的可能性。然而，希拉里·克林顿赢得的几个关键州最终都以微弱劣势输给了特朗普。即使出现平局，共和党控制的众议院也很有可能最终选择特朗普为总统。2020年大选临近时，形势对拜登有利，但特朗普仍有可能险胜关键摇摆州，从而赢得选举人团的胜利。然而，这种情况并未发生，拜登最终赢得了普选和选举人团的胜利。尽管如此，基于选举被窃取的错误假设，数千名特朗普支持者冲进美国国会大厦，试图阻止众议院和参议院完成对拜登胜选结果的最终计票。虽然许多“停止窃选”的抗议者留在国会大厦外，没有采取任何暴力行动，但一些有组织的团体身着准军事装备，包括头盔和作战背心；有人被拍到砸碎窗户试图闯入。然而，他们的企图并未得逞，最终在1月7日凌晨，由副总统迈克·彭斯主持完成了计票。

As political parties became stronger and the Progressive Era’s influence shaped politics from the 1890s to the 1920s, states began to allow state parties rather than legislators to nominate a slate of electors. Electors cannot be elected officials nor can they work for the federal government. Since the Republican and Democratic parties choose faithful party members who have worked hard for their candidates, the modern system decreases the chance they will vote differently from the state’s voters.

[.my2]
从19世纪90年代到20世纪20年代，随着政党势力的壮大和进步时代的影响力不断增强，各州开始允许州政党而非立法者提名选举人名单。选举人不能是民选官员，也不能为联邦政府工作。由于共和党和民主党都选择忠诚的党员，这些党员曾为各自的候选人辛勤工作，因此现代选举制度降低了选举人投票与本州选民投票结果相悖的可能性。

There is no guarantee of this, however. Occasionally there are examples of faithless electors. In 2000, the majority of the District of Columbia’s voters cast ballots for Al Gore, and all three electoral votes should have been cast for him. Yet one of the electors cast a blank ballot, denying Gore a precious electoral vote, reportedly to contest the unequal representation of the District in the Electoral College. In 2004, one of the Minnesota electors voted for John Edwards, the vice presidential nominee, to be president (Figure 7.16) and misspelled the candidate’s last name in the process. Some believe this was a result of confusion rather than a political statement. In the 2016 election, after a campaign to encourage faithless electors in the wake of what some viewed as controversial results, there were seven faithless electors: four in the state of Washington, two in Texas, and one in Hawaii. The electors’ names and votes are publicly available on the electoral certificates, which are scanned and documented by the National Archives and easily available for viewing online.

[.my2]
然而，这并不能保证。偶尔会出现失信选举人的例子。2000 年，哥伦比亚特区的大多数选民投票支持阿尔·戈尔，该特区的三张选举人票本应全部投给他。然而，其中一位选举人投了一张空白票，剥夺了戈尔宝贵的一张选举人票，据报道，此举是为了抗议特区在选举团中代表人数不足。2004 年，明尼苏达州的一位选举人投票支持副总统候选人约翰·爱德华兹担任总统（ 图 7.16 ），并在投票过程中拼错了候选人的姓氏。一些人认为这是由于混淆造成的，而非出于政治目的。在 2016 年大选中，在一些人认为选举结果存在争议之后，有人发起了一场鼓励失信选举人的运动，结果出现了七位失信选举人：华盛顿州四位，德克萨斯州两位，夏威夷州一位。选民的姓名和投票情况均公开记录在选举证书上，这些证书由国家档案馆扫描和存档，并可在网上轻松查看。

Image A is of a presidential elector certificate of vote form, showing a vote for John Kerry for president. Image B is of John Kerry and John Edwards.

[.my2]
Figure 7.16 In 2004, Minnesota had an error or faithless voter when one elector cast a vote for John Edwards for president (a). On July 8, 2004, presidential candidate John Kerry and his running mate John Edwards arrive for a campaign rally in Fort Lauderdale, Florida (b). (credit b: modification of work by Richard Block)
图 7.16 2004 年，明尼苏达州出现选举人失信或“失信投票”现象，一名选举人将选票投给了约翰·爱德华兹 (a)。2004 年 7 月 8 日，总统候选人约翰·克里和他的竞选搭档约翰·爱德华兹抵达佛罗里达州劳德代尔堡参加竞选集会 (b)。（图片 b 为理查德·布洛克作品的修改版）
In forty-eight states and the District of Columbia, the candidate who wins the most votes in November receives all the state’s electoral votes, and only the electors from that party will vote. This is often called the winner-take-all system. In two states, Nebraska and Maine, the electoral votes are divided. The candidate who wins the state gets two electoral votes, but the winner of each congressional district also receives an electoral vote. In 2008, for example, Republican John McCain won two congressional districts and the majority of the voters across the state of Nebraska, earning him four electoral votes from Nebraska. Obama won in one congressional district and earned one electoral vote from Nebraska.105 In 2020, Republican Donald Trump won one congressional district in Maine, and therefore one electoral vote, even though Joe Biden won the state overall, receiving a total of three electoral votes from Maine. This Electoral College voting method is referred to as the district system.

[.my2]
在 48 个州和哥伦比亚特区，11 月大选中获得最多选票的候选人将获得该州的所有选举人票，且只有该党派的选举人才能投票。这通常被称为“ 赢者通吃”制度 。在内布拉斯加州和缅因州这两个州，选举人票是分配的。赢得该州的候选人获得两张选举人票，但每个国会选区的获胜者也获得一张选举人票。例如，2008 年，共和党候选人约翰·麦凯恩赢得了两个国会选区以及内布拉斯加州的大多数选民，从而获得了内布拉斯加州的四张选举人票。奥巴马赢得了一个国会选区，获得了内布拉斯加州的一张选举人票。 2020 年，共和党候选人唐纳德·特朗普赢得了缅因州的一个国会选区，因此获得了一张选举人票，尽管乔·拜登赢得了缅因州全州的选票，总共获得了三张选举人票。这种选举团投票方式被称为选区制 。

MIDTERM ELECTIONS  中期选举
Presidential elections garner the most attention from the media and political elites. Yet they are not the only important elections. The even-numbered years between presidential years, like 2014 and 2018, are reserved for congressional elections—sometimes referred to as midterm elections because they are in the middle of the president’s term. Midterm elections are held because all members of the House of Representatives and one-third of the senators come up for reelection every two years.

[.my2]
总统选举最受媒体和政治精英的关注。然而，总统选举并非唯一重要的选举。总统任期之间的偶数年，例如 2014 年和 2018 年，是国会选举的年份——有时被称为中期选举 ，因为它们正值总统任期中期。举行中期选举的原因是，众议院所有议员和三分之一的参议员每两年都要进行改选。

During a presidential election year, members of Congress often experience the coattail effect, which gives members of a popular presidential candidate’s party an increase in popularity and raises their odds of retaining office. During a midterm election year, however, the president’s party often is blamed for the president’s actions or inaction. Representatives and senators from the sitting president’s party are more likely to lose their seats during a midterm election year. Many recent congressional realignments, in which the House or Senate changed from Democratic to Republican control, occurred because of this reverse-coattail effect during midterm elections. The most recent example is the 2018 election, in which control of the House returned to the Democratic Party after eight years of Republican control.

[.my2]
在总统选举年，国会议员往往会受到 “裙带效应”的影响 ，即当总统候选人人气高涨时，其所在政党的成员支持率也会上升，从而提高他们连任的几率。然而，在中期选举年，总统的政党往往会因为总统的作为或不作为而受到指责。在中期选举年，来自现任总统所在政党的众议员和参议员更有可能失去席位。近年来，许多国会席位的重新分配，例如众议院或参议院的控制权从民主党转移到共和党，都是由于中期选举期间的这种反向“裙带效应”造成的。最近的例子是 2018 年的选举，在共和党控制众议院八年后，民主党重新掌控了众议院。

'''