
= 008-1 What Is the Media 什么是媒体？
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




Ours is an exploding media system. What started as print journalism was subsequently supplemented by radio coverage, then network television, followed by cable television. Now, with the addition of the Internet, blogs and social media—a set of applications or web platforms that allow users to immediately communicate with one another—give citizens a wide variety of sources for instant news of all kinds. The Internet also allows citizens to initiate public discussion by uploading images and video for viewing, such as videos documenting interactions between citizens and the police, for example. Provided we are connected digitally, we have a bewildering amount of choices for finding information about the world. In fact, some might say that compared to the tranquil days of the 1970s, when we might read the morning newspaper over breakfast and take in the network news at night, there are now too many choices in today’s increasingly complex world of information. This reality may make the news media all the more important to structuring and shaping narratives about U.S. politics. Or the proliferation of competing information sources like blogs and social media may actually weaken the power of the news media relative to the days when news media monopolized our attention.

[.my2]
我们的媒体体系正经历着爆炸式增长。最初以纸媒为主，随后广播、电视和有线电视相辅相成。如今，随着互联网、博客和社交媒体 ——一系列允许用户即时交流的应用程序或网络平台——的出现，公民拥有了获取各类即时新闻的丰富渠道。互联网还允许公民上传图片和视频，例如记录公民与警察互动的视频，从而发起公共讨论。只要我们能够连接网络，就能找到海量的信息。事实上，有人可能会说，与上世纪 70 年代的平静生活相比——那时我们可能在早餐时阅读晨报，晚上收看电视新闻——如今这个信息日益复杂的世界里，选择实在太多了。这种现实或许会让新闻媒体在构建和塑造美国政治叙事方面显得更加重要。或者，博客和社交媒体等竞争性信息来源的激增，实际上可能会削弱新闻媒体的权力，使其不如新闻媒体垄断我们注意力的时代那样强大。

MEDIA BASICS  媒体基础知识
The term media defines a number of different communication formats from television media, which share information through broadcast airwaves, to print media, which rely on printed documents. The collection of all forms of media that communicate information to the general public is called mass media, including television, print, radio, and Internet. One of the primary reasons citizens turn to the media is for news. We expect the media to cover important political and social events and information in a concise and neutral manner.

[.my2]
“媒体” 一词涵盖多种不同的传播形式，从通过广播传播信息的电视媒体到依赖印刷文件的印刷媒体。所有向公众传播信息的媒体形式统称为大众媒体 ，包括电视、印刷品、广播和互联网。公民获取新闻是他们关注媒体的主要原因之一。我们期望媒体以简洁、中立的方式报道重要的政治和社会事件及信息。

To accomplish its work, the media employs a number of people in varied positions. Journalists and reporters are responsible for uncovering news stories by keeping an eye on areas of public interest, like politics, business, and sports. Once a journalist has a lead or a possible idea for a story, they research background information and interview people to create a complete and balanced account. Editors work in the background of the newsroom, assigning stories, approving articles or packages, and editing content for accuracy and clarity. Publishers are people or companies that own and produce print or digital media. They oversee both the content and finances of the publication, ensuring the organization turns a profit and creates a high-quality product to distribute to consumers. Producers oversee the production and finances of visual media, like television, radio, and film.

[.my2]
为了完成工作，媒体雇佣了众多不同岗位的人员。记者和报道员负责挖掘新闻，密切关注政治、商业和体育等公众关注的领域。一旦记者获得线索或新闻选题，他们就会调查背景信息并采访相关人士，以撰写完整、平衡的报道。编辑在新闻编辑室幕后工作，负责分配选题、审核文章或专题报道，并对内容进行编辑，确保其准确性和清晰度。出版商是指拥有并制作纸质或数字媒体的个人或公司。他们负责监督出版物的内容和财务，确保机构盈利并制作出高质量的产品分发给消费者。制片人负责监督电视、广播和电影等视觉媒体的制作和财务。

The work of the news media differs from public relations, which is communication carried out to improve the image of companies, organizations, or candidates for office. Public relations is not a neutral information form. While journalists write stories to inform the public, a public relations spokesperson is paid to help an individual or organization get positive press. Public relations materials normally appear as press releases or paid advertisements in newspapers and other media outlets. Some less reputable publications, however, publish paid articles under the news banner, blurring the line between journalism and public relations.

[.my2]
新闻媒体的工作与公共关系有所不同，后者是指为了提升公司、组织或候选人的形象而进行的沟通活动。公共关系并非中立的信息形式。记者撰写新闻报道是为了告知公众，而公共关系发言人则受雇帮助个人或组织获得正面媒体报道。公共关系材料通常以新闻稿或付费广告的形式出现在报纸和其他媒体上。然而，一些信誉度较低的出版物会以新闻的名义发表付费文章，模糊了新闻和公共关系之间的界限。

MEDIA TYPES  媒体类型
Each form of media has its own complexities and is used by different demographics. Millennials (those born between 1981 and 1996) and Generation Z (those born between 1997 and 2012) are more likely to get news and information from digital sources and social media, such as Instagram, TikTok, Twitter, and YouTube, while Baby Boomers (born between 1946 and 1964) are most likely to get their news from television, either national broadcasts or local news (Figure 8.2). Generation X (born between 1965 and 1980) is a mix, taking in more television than Millennials or Generation Z but more digital sources than Baby Boomers.

[.my2]
每种媒体形式都有其自身的复杂性，并且被不同的人群使用。千禧一代（1981 年至 1996 年出生）和 Z 世代（1997 年至 2012 年出生）更倾向于从数字渠道和社交媒体（例如 Instagram、TikTok、Twitter 和 YouTube）获取新闻和信息，而婴儿潮一代（1946 年至 1964 年出生）则更倾向于通过电视获取新闻，包括全国性广播和地方新闻（ 图 8.2 ）。X 世代（1965 年至 1980 年出生）的情况则较为复杂，他们比千禧一代和 Z 世代更多地观看电视，但比婴儿潮一代更多地使用数字渠道。

A graph titled “where do you get your news?”. The legend indicates four categories: Television, Radio, Print, and Digital. The x-axis of the graph is labeled “Percentage of media type used by age group” and goes from 0% at the origin to 90%. The y-axis of the graph is labeled “Demographic Group” and lists four groups: Baby Boomers, Gen X, Millennials, and Gen Z. Baby boomers get sixty percent of their news from television, five percent from radio, eight percent from print publications, and twenty-seven percent from digital. Gen X gets forty-two percent of news from television, eight percent from radio, three percent from print, and forty-six from digital. Millennials get eighteen percent of their news from television, six percent from radio, three percent from print, and seventy-two percent from digital. Gen Z gets eight percent of their news from television, two percent from radio, three percent from print, and eighty-six percent from digital.

[.my2]
Figure 8.2 Age greatly influences the choice of news sources. Baby Boomers are more likely to get news and information from television, while members of Generation X and Millennials are more likely to use social media.

[.my2]
图 8.2 年龄对新闻来源的选择有很大影响。婴儿潮一代更倾向于从电视获取新闻和信息，而 X 世代和千禧一代则更倾向于使用社交媒体。
Television alone offers viewers a variety of formats. Programming may be scripted, like dramas or comedies. It may be unscripted, like game shows or reality programs, or informative, such as news programming. Although most programs are created by a television production company, national networks—like CBS or NBC—purchase the rights to programs they distribute to local stations across the United States. Most local stations are affiliated with a national network corporation, and they broadcast national network programming to their local viewers.

[.my2]
仅电视就为观众提供了多种多样的节目形式。节目可以是剧本式的，例如剧情片或喜剧；也可以是即兴的，例如游戏节目或真人秀；还可以是信息类节目，例如新闻节目。虽然大多数节目都是由电视制作公司制作的，但像 CBS 或 NBC 这样的全国性电视网会购买节目的版权，然后分发给全美各地的本地电视台。大多数本地电视台都隶属于某个全国性电视网，并向本地观众播出全国性电视网的节目。

Before the existence of cable and fiber optics, networks needed to own local affiliates to have access to the local station’s transmission towers. Towers have a limited radius, so each network needed an affiliate in each major city to reach viewers. While cable technology has lessened networks’ dependence on aerial signals, some viewers still use antennas and receivers to view programming broadcast from local towers.

[.my2]
在有线电视和光纤出现之前，电视网需要拥有本地附属电视台才能使用本地电视台的发射塔。由于发射塔的覆盖范围有限，每个电视网都需要在每个主要城市设立附属电视台才能覆盖观众。虽然有线电视技术降低了电视网对空中信号的依赖，但仍有一些观众使用天线和接收器来收看从本地发射塔发射的节目。

Affiliates, by agreement with the networks, give priority to network news and other programming chosen by the affiliate’s national media corporation. Local affiliate stations are told when to air programs or commercials, and they diverge only to inform the public about a local or national emergency. For example, ABC affiliates broadcast the popular television show Black-ish at a specific time on a specific day. Should a fire threaten homes and businesses in a local area, the affiliate might preempt it to update citizens on the fire’s dangers and return to regularly scheduled programming after the danger has ended.

[.my2]
根据与电视网的协议，各加盟电视台优先播出电视网新闻和其他由其所属全国性媒体公司选择的节目。地方加盟电视台会被告知何时播出节目或广告，只有在发生地方或国家紧急情况时才会例外。例如，ABC 的加盟电视台会在特定日期和特定时间播出热门电视剧《喜新不厌旧》 （Black-ish） 。如果当地发生火灾，威胁到居民住宅和商铺，加盟电视台可能会暂停播出该剧，向民众通报火灾危险情况，并在危险解除后恢复正常节目播出。

Most affiliate stations will show local news before and after network programming to inform local viewers of events and issues. Network news has a national focus on politics, international events, the economy, and more. Local news, on the other hand, is likely to focus on matters close to home, such as regional business, crime, sports, and weather.4 The NBC Nightly News, for example, covers presidential campaigns and the White House or skirmishes between North Korea and South Korea, while the NBC affiliate in Los Angeles (KNBC-TV) and the NBC affiliate in Dallas (KXAS-TV) report on the governor’s activities or weekend festivals in the region.

[.my2]
大多数附属电视台会在全国性节目播出前后播放本地新闻，以便让当地观众了解时事和热点问题。全国性新闻侧重于政治、国际事件、经济等全国性议题。而本地新闻则更关注与当地息息相关的内容，例如区域商业、犯罪、体育和天气。 例如 ， NBC 晚间新闻会报道总统竞选、白宫动态或朝韩冲突，而 NBC 在洛杉矶的附属电视台（KNBC-TV）和在达拉斯的附属电视台（KXAS-TV）则会报道州长的活动或当地的周末节庆活动。

Cable programming offers national networks a second method to directly reach local viewers. As the name implies, cable stations transmit programming directly to a local cable company hub, which then sends the signals to homes through coaxial or fiber optic cables. Because cable does not broadcast programming through the airwaves, cable networks can operate across the nation directly without local affiliates. Instead they purchase broadcasting rights for the cable stations they believe their viewers want. For this reason, cable networks often specialize in different types of programming.

[.my2]
有线电视节目为全国性电视网提供了另一种直接触达本地观众的方式。顾名思义，有线电视台直接将节目信号传输到本地有线电视公司的中心机房，然后由中心机房通过同轴电缆或光纤电缆将信号发送到用户家中。由于有线电视不通过无线电波广播节目，因此有线电视网络无需设立本地分支机构即可在全国范围内直接运营。它们购买的是其认为观众感兴趣的有线电视台的播出权。正因如此，有线电视网络通常会专注于不同类型的节目。

The Cable News Network (CNN) was the first news station to take advantage of this specialized format, creating a 24-hour news station with live coverage and interview programs. Other news stations quickly followed, such as MSNBC and FOX News. A viewer might tune in to Nickelodeon and catch family programs and movies or watch ESPN to catch up with the latest baseball or basketball scores. The Cable-Satellite Public Affairs Network, known better as C-SPAN, now has three channels covering Congress, the president, the courts, and matters of public interest.

[.my2]
有线电视新闻网（CNN）是首个采用这种专业形式的新闻机构，它创建了一个 24 小时新闻频道，提供直播报道和访谈节目。其他新闻机构也迅速效仿，例如 MSNBC 和福克斯新闻。观众可能会收看尼克儿童频道（Nickelodeon）的家庭节目和电影，或者收看 ESPN 了解最新的棒球或篮球比赛比分。有线卫星公共事务网（C-SPAN）目前拥有三个频道，分别报道国会、总统、法院和公共事务。

Cable and satellite providers also offer on-demand programming for most stations. Citizens can purchase cable, satellite, and Internet subscription services (like Netflix) to find programs to watch instantly, without being tied to a schedule. Initially, on-demand programming was limited to rebroadcasting old content and was commercial-free. Yet many networks and programs now allow their new programming to be aired within a day or two of its initial broadcast. In return they often add commercials the user cannot fast-forward or avoid. Thus networks expect advertising revenues to increase.5
有线电视和卫星电视供应商也为大多数电视台提供点播节目。市民可以购买有线电视、卫星电视和互联网订阅服务（例如 Netflix），以便即时观看节目，而无需受限于固定的播出时间。最初，点播节目仅限于重播旧内容，且不含广告。然而，现在许多电视台和节目允许其新节目在首播后一两天内播出。作为回报，他们通常会添加用户无法快进或跳过的广告。 因此 ，电视台期望广告收入能够增加。

The on-demand nature of the Internet has created many opportunities for news outlets. While early media providers were those who could pay the high cost of printing or broadcasting, modern media require just a URL and ample server space. The ease of online publication has made it possible for more niche media outlets to form. The websites of the New York Times and other newspapers often focus on matters affecting the United States, while channels like BBC America present world news. FOX News presents political commentary and news in a conservative vein, while the Internet site Daily Kos offers a liberal perspective on the news. Politico.com is perhaps the leader in niche journalism.

[.my2]
互联网的按需特性为新闻媒体创造了诸多机遇。早期的媒体提供商需要承担高昂的印刷或广播成本，而现代媒体只需一个网址和充足的服务器空间即可。在线出版的便捷性使得更多垂直领域的媒体得以涌现。《 纽约时报》 和其他报纸的网站通常关注影响美国的新闻，而像 BBC 美国频道这样的频道则提供世界新闻。福克斯新闻以保守的视角提供政治评论和新闻，而互联网网站 Daily Kos 则提供自由主义的新闻观点。Politico.com 或许是垂直领域新闻的领军者。

Unfortunately, the proliferation of online news has also increased the amount of poorly written material with little editorial oversight, and readers must be cautious when reading Internet news sources. Sites like Buzzfeed allow members to post articles without review by an editorial board, leading to articles of varied quality and accuracy. The Internet has also made publication speed a consideration for professional journalists. No news outlet wants to be the last to break a story, and the rush to publication often leads to typographical and factual errors. Even large news outlets, like the Associated Press, have published articles with errors in their haste to get a story out.

[.my2]
不幸的是，网络新闻的激增也导致了大量缺乏编辑监管的低质量文章涌现，读者在阅读网络新闻时必须格外谨慎。像 Buzzfeed 这样的网站允许用户未经编辑审核就发布文章，导致文章质量和准确性参差不齐。互联网也使得新闻发布速度成为专业记者必须考虑的因素。没有哪家新闻机构愿意成为最后一个发布新闻的媒体，而这种急于发布的做法往往会导致拼写错误和事实错误。即使是像美联社这样的大型新闻机构，也曾因为急于发布新闻而发表过错误的文章。

The Internet also facilitates the flow of information through social media, which allows users to instantly communicate with one another and share with audiences that can grow exponentially. Facebook and Twitter have millions of daily users. Social media changes more rapidly than the other media formats. While people in many different age groups use sites like Facebook, Twitter, and YouTube, other sites like Snapchat and TikTok appeal mostly to younger users. The platforms also serve different functions. Tumblr and Reddit facilitate discussion that is topic-based and controversial, while Instagram is mostly social. A growing number of these sites also allow users to comment anonymously, leading to increases in threats and abuse. The 2020 QAnon conspiracy, which absurdly alleged a connection between liberal elites and child sex trafficking, was promulgated in part through social media posts on many platforms, including Facebook and Twitter. Both companies attempted to kick QAnon off their platforms.6
互联网也促进了信息通过社交媒体的流动，使用户能够即时相互交流，并与呈指数级增长的受众群体分享信息。Facebook 和 Twitter 拥有数百万日活跃用户。社交媒体的变化速度比其他媒体形式更快。虽然许多不同年龄段的人都在使用 Facebook、Twitter 和 YouTube 等网站，但 Snapchat 和 TikTok 等网站则主要吸引年轻用户。这些平台的功能也各不相同。Tumblr 和 Reddit 促进了基于主题且具有争议性的讨论，而 Instagram 则主要是一个社交平台。越来越多的网站允许用户匿名评论，导致威胁和辱骂事件的增加。2020 年的 QAnon 阴谋论荒谬地声称自由派精英与儿童性交易有关，其传播部分是通过包括 Facebook 和 Twitter 在内的多个社交媒体平台上的帖子实现的。 这两家公司都曾试图将 QAnon 内容从其平台上清除出去。

Regardless of where we get our information, the various media avenues available today, versus years ago, make it much easier for everyone to be engaged. The question is: Who controls the media we rely on? Most media are controlled by a limited number of conglomerates. A conglomerate is a corporation made up of a number of companies, organizations, and media networks. In the 1980s, more than fifty companies owned the majority of television and radio stations and networks. By 2011, six conglomerates controlled most of the broadcast media in the United States: CBS Corporation, Comcast, Time Warner, 21st Century Fox (formerly News Corporation), Viacom, and The Walt Disney Company (Figure 8.3).7 With the Disney-Fox merger in March 2019 and the CBS-Viacom merger in December 2019, this number was reduced to four. Moreover, these conglomerates own much of the airways for television news. The Walt Disney Company also owns the ABC Television Network, ESPN, A&E, and Lifetime, in addition to the Disney Channel and Disney+, a popular streaming service. Viacom also owns BET, Comedy Central, MTV, Nickelodeon, and VH1. Warner Bros. Discovery owns Cartoon Network, CNN, HBO, Food Network, and HGTV among others. While each of these networks has its own programming, in the end, the conglomerate can make a policy that affects all stations and programming under its control.

[.my2]
无论我们从何处获取信息，如今各种媒体渠道的丰富程度，与几年前相比，让每个人都能更轻松地参与其中。问题是：谁控制着我们所依赖的媒体？大多数媒体都由少数几家企业集团控制。企业集团是由多家公司、组织和媒体网络组成的集团。20 世纪 80 年代，超过 50 家公司拥有大部分电视台、广播电台和网络。到 2011 年，六家企业集团控制了美国大部分广播媒体：哥伦比亚广播公司（CBS）、康卡斯特（Comcast）、时代华纳（Time Warner）、21 世纪福克斯（前身为新闻集团）、维亚康姆（Viacom）和华特迪士尼公司（ 图 8.3 ）。 7 随着 2019 年 3 月迪士尼与福克斯的合并以及 2019 年 12 月哥伦比亚广播公司与维亚康姆的合并，这一数字减少到四家。此外，这些企业集团还拥有大部分电视新闻频道。华特迪士尼公司除了拥有迪士尼频道和热门流媒体服务 Disney+之外，还拥有 ABC 电视网、ESPN、A&E 和 Lifetime 频道。维亚康姆则拥有 BET、喜剧中心、MTV、尼克儿童频道和 VH1。华纳兄弟探索频道旗下拥有卡通频道、CNN、HBO、美食频道和 HGTV 等频道。虽然这些频道各自拥有不同的节目内容，但最终，集团可以制定一项影响其控制下所有频道和节目的政策。

A diagram demonstrates the decline in number of media companies within the U.S. On the left, there are 50 small TVs in a 10 by 5 table, labeled “1983: 90% of media, 50 companies”. On the right are four large screen TVs labeled “Comcast”, “Disney”, “ViacomCBS”, and “Warner Bros. Discovery”.

[.my2]
Figure 8.3 In 1983, fifty companies owned 90 percent of U.S. media. By 2021, just four conglomerates controlled the same percentage of U.S. media outlets.

[.my2]
图 8.3 1983 年，50 家公司拥有美国 90% 的媒体。到 2021 年，仅四家企业集团就控制了相同比例的美国媒体。
Conglomerates can create a monopoly on information by controlling a sector of a market. When a media conglomerate has policies or restrictions, they will apply to all stations or outlets under its ownership, potentially limiting the information citizens receive. Conglomerate ownership also creates circumstances in which censorship may occur. iHeartMedia (formerly Clear Channel Media) owns music, radio, and billboards throughout the United States, and in 2010, the company refused to run several billboard ads for the St. Pete Pride Festival and Promenade in St. Petersburg, Florida. The festival organizers said the content of two ads, a picture of same-sex couples in close contact with one another, was the reason the ads were not run. Because iHeartMedia owns most of the billboards in the area, this limitation was problematic for the festival and decreased awareness of the event. Those in charge of the festival viewed the refusal as censorship.8
集团可以通过控制市场的一部分来垄断信息。当一家媒体集团制定政策或限制时，这些政策或限制将适用于其旗下所有电台或媒体机构，从而可能限制公民获取的信息。集团所有权也可能导致审查制度的出现。iHeartMedia（前身为 Clear Channel Media）在美国各地拥有音乐、广播和广告牌。2010 年，该公司拒绝在佛罗里达州圣彼得堡市的圣彼得骄傲节暨游行活动中投放几则广告牌广告。节日组织者表示，其中两则广告的内容——一张同性伴侣亲密接触的照片 —— 是广告被拒的原因。由于 iHeartMedia 拥有该地区的大部分广告牌，这一限制对节日造成了不利影响，并降低了人们对该活动的认知度。节日负责人认为这种拒绝是一种审查行为。

Newspapers too have experienced the pattern of concentrated ownership. Gannett Company, while also owning television media, holds a large number of newspapers and news magazines in its control. Many of these were acquired quietly, without public notice or discussion. Gannett’s 2013 acquisition of publishing giant A.H. Belo Corporation caused some concern and news coverage, however. The sale would have allowed Gannett to own both an NBC and a CBS affiliate in St. Louis, Missouri, giving it control over programming and advertising rates for two competing stations. The U.S. Department of Justice required Gannett to sell the station owned by Belo to ensure market competition and multi-ownership in St. Louis.9
报业也出现了所有权集中化的趋势。甘尼特公司（Gannett Company）在拥有电视媒体的同时，还控制着大量报纸和新闻杂志。其中许多收购都是悄悄进行的，没有公开通知或讨论。然而，甘尼特在 2013 年收购出版巨头 AH Belo 公司一事却引发了一些担忧和媒体报道。此次收购将使甘尼特同时拥有位于密苏里州圣路易斯的一家 NBC 和一家 CBS 附属电视台，从而控制两家竞争电视台的节目安排和广告价格。美国司法部要求甘尼特出售 Belo 公司拥有的电视台，以确保圣路易斯的市场竞争和多元化所有权。

Link to Learning  学习链接
If you are concerned about the lack of variety in the media and the market dominance of media conglomerates, the non-profit organization, Free Press, tracks and promotes open communication.

[.my2]
如果您担心媒体缺乏多样性以及媒体集团的市场主导地位，非营利组织“ 自由媒体”（Free Press ）会追踪并促进公开交流。

These changes in the format and ownership of media raise the question whether the media still operate as an independent source of information. Is it possible that corporations and CEOs now control the information flow, making profit more important than the impartial delivery of information? The reality is that media outlets, whether newspaper, television, radio, or Internet, are businesses. They have expenses and must raise revenues. Yet at the same time, we expect the media to entertain, inform, and alert us without bias. They must provide some public services, while following laws and regulations. Reconciling these goals may not always be possible.

[.my2]
媒体形式和所有权的这些变化引发了一个问题：媒体是否仍然作为独立的信息来源运作？企业和首席执行官是否已经掌控了信息流，使得利润凌驾于公正的信息传递之上？事实上，无论是报纸、电视、广播还是互联网，媒体都是商业机构。它们需要支付各种费用，也必须创造收入。然而与此同时，我们期望媒体能够客观公正地娱乐、告知和警示我们。它们必须提供一定的公共服务，同时遵守法律法规。要兼顾这些目标，有时并非易事。

FUNCTIONS OF THE MEDIA
媒体的功能
The media exist to fill a number of functions. Whether the medium is a newspaper, a radio, or a television newscast, a corporation behind the scenes must bring in revenue and pay for the cost of the product. Revenue comes from advertising and sponsors, like McDonald’s, Ford Motor Company, and other large corporations. But corporations will not pay for advertising if there are no viewers or readers. So all programs and publications need to entertain, inform, or interest the public and maintain a steady stream of consumers. In the end, what attracts viewers and advertisers is what survives.

[.my2]
媒体的存在是为了履行多种功能。无论是报纸、广播还是电视新闻，其背后的公司都必须盈利并支付产品成本。收入来自广告和赞助商，例如麦当劳、福特汽车公司和其他大型企业。但如果没有观众或读者，公司就不会投放广告。因此，所有节目和出版物都需要娱乐、告知或吸引公众，并维持稳定的受众群体。最终，能够吸引观众和广告商的才能得以生存。

The media are also watchdogs of society and of public officials. Some refer to the media as the fourth estate, with the branches of government being the first three estates and the media equally participating as the fourth. This role helps maintain democracy and keeps the government accountable for its actions, even if a branch of the government is reluctant to open itself to public scrutiny. As much as social scientists would like citizens to be informed and involved in politics and events, the reality is that we are not. So the media, especially journalists, keep an eye on what is happening and sounds an alarm when the public needs to pay attention.10
媒体也是社会和公职人员的监督者。有人将媒体称为“ 第四权力” ，政府的三个部门构成前三个权力，而媒体作为第四权力同样参与其中。这一角色有助于维护民主，并监督政府的行为，即使政府的某个部门不愿接受公众监督 。 尽管社会科学家希望公民能够了解并参与政治和时事，但现实并非如此。因此，媒体，尤其是记者，密切关注事态发展，并在公众需要关注时发出警报。

The media also engages in agenda setting, which is the act of choosing which issues or topics deserve public discussion. For example, in the early 1980s, famine in Ethiopia drew worldwide attention, which resulted in increased charitable giving to the country. Yet the famine had been going on for a long time before it was discovered by western media. Even after the discovery, it took video footage to gain the attention of the British and U.S. populations and start the aid flowing.11 Today, numerous examples of agenda setting show how important the media are when trying to prevent further emergencies or humanitarian crises. In the spring of 2015, when the Dominican Republic was preparing to exile Haitians and undocumented (or under documented) residents, major U.S. news outlets remained silent. However, once the story had been covered several times by Al Jazeera, a state-funded broadcast company based in Qatar, ABC, the New York Times, and other network outlets followed.12 With major network coverage came public pressure for the U.S. government to act on behalf of the Haitians.13
媒体也参与议程设置 ，即选择哪些议题或话题值得公众讨论。例如，20 世纪 80 年代初，埃塞俄比亚的饥荒引起了全世界的关注，导致该国获得了更多慈善捐款。然而，在西方媒体发现这场饥荒之前，它已经持续了很长时间。即使在被发现之后，也需要视频资料才能引起英国和美国民众的关注，并开始提供援助。如今，议程设置的例子不胜枚举 ，这表明媒体在试图预防进一步的紧急情况或人道主义危机时发挥着多么重要的作用。2015 年春季，当多米尼加共和国准备驱逐海地人和无证（或证件不全）居民时，美国主流媒体保持沉默。然而，在卡塔尔一家国有广播公司半岛电视台多次报道此事后，美国广播公司（ABC）、《 纽约时报》 和其他一些电视媒体也纷纷跟进报道。 12 随着各大媒体的广泛报道，公众对美国政府采取行动援助海地人民的压力也随之增大 。13

Insider Perspective  内部视角
Christiane Amanpour on “What Should Be News?”
克里斯蒂安·阿曼普尔谈“什么才算是新闻？”
The media are our connection to the world. Some events are too big to ignore, yet other events, such as the destruction of Middle Eastern monuments or the plight of foreign refugees, are far enough from our shores that they often go unnoticed. What we see is carefully selected, but who decides what should be news?
媒体是我们了解世界的桥梁。有些事件影响巨大，不容忽视；而另一些事件，例如中东古迹的损毁或外国难民的困境，由于距离遥远，往往被我们忽略。我们看到的内容都是经过精心挑选的，但究竟是谁决定了什么才是新闻呢？

As the chief international correspondent for CNN, Christiane Amanpour is one media decision maker (Figure 8.4). Over the years, Amanpour has covered events around the world from war to genocide. In an interview with Oprah Winfrey, Amanpour explains that her duty, and that of other journalists, is to make a difference in the world. To do that, “we have to educate people and use the media responsibly.”14 Journalists cannot passively sit by and wait for stories to find them. “Words have consequences: the stories we decide to do, the stories we decide not to do . . . it all matters.”15
作为 CNN 首席国际记者，克里斯蒂安· 阿曼普尔是一位媒体决策者（ 图 8.4 ）。多年来，阿曼普尔报道了世界各地的事件，从战争到种族灭绝。在接受奥普拉·温弗瑞的采访时，阿曼普尔解释说，她和其他记者的职责是改变世界。为了做到这一点，“我们必须教育民众，并负责任地使用媒体。” 14 记者不能被动地坐等新闻事件上门。“言辞会产生后果：我们决定报道的新闻，我们决定不报道的新闻……这一切都至关重要。” 15

An image of Christiane Amanpour.

[.my2]
Figure 8.4 Christiane Amanpour accepts the award for the Association for International Broadcasting’s Personality of the Year on November 4, 2015. (credit: AIB (Association for International Broadcasting))
图 8.4 克里斯蒂安·阿曼普尔于 2015 年 11 月 4 日接受国际广播协会年度人物奖。（图片来源：AIB（国际广播协会））
As Amanpour points out, journalists are often “on the cutting edge of reform,” so if they fail to shed light on events, the results can be tragic. One of her biggest regrets was not covering the genocide in Rwanda in 1994, which cost nearly a million lives. She said the media ignored the event in favor of covering democratic elections in South Africa and a war in Bosnia, and ultimately she believes the media failed the people. “If we don’t respect our profession and we see it frittering away into the realm of triviality and sensationalism, we’ll lose our standing,” she said. “That won’t be good for democracy. A thriving society must have a thriving press.”
正如阿曼普尔所指出的，记者往往“站在改革的最前沿”，因此，如果他们未能揭露真相，后果可能不堪设想。她最大的遗憾之一就是没有报道1994年卢旺达种族灭绝事件，那场灾难夺去了近百万人的生命。她说，媒体当时选择报道南非的民主选举和波斯尼亚战争，而忽略了这场灾难，最终她认为媒体辜负了人民。“如果我们不尊重自己的职业，眼睁睁地看着它沦为琐碎和耸人听闻的炒作，我们就会失去声誉，”她说。“这对民主不利。一个繁荣的社会必须拥有一个繁荣的新闻媒体。”

This feeling of responsibility extends to covering moral topics, like genocide. Amanpour feels there shouldn’t be equal time given to all sides. “I’m not just a stenographer or someone with a megaphone; when I report, I have to do it in context, to be aware of the moral conundrum. . . . I have to be able to draw a line between victim and aggressor.”
这种责任感也延伸到了对道德议题的报道，例如种族灭绝。阿曼普尔认为不应该给予各方同等的发言时间。“我不是速记员，也不是拿着扩音器的人；我报道时，必须结合具体情况，意识到其中的道德困境……我必须能够区分受害者和施害者。”

Amanpour also believes the media should cover more. When given the full background and details of events, society pays attention to the news. “Individual Americans had an incredible reaction to the [2004 Indian Ocean] tsunami—much faster than their government’s reaction,” she said. “Americans are a very moral and compassionate people who believe in extending a helping hand, especially when they get the full facts instead of one-minute clips.” If the news fulfills its responsibility, as she sees it, the world can show its compassion and help promote freedom.

[.my2]
阿曼普尔也认为媒体应该报道更多。当人们了解事件的完整背景和细节时，社会才会关注新闻。“美国民众对（2004年印度洋）海啸的反应令人难以置信——比政府的反应快得多，”她说。“美国人是一个非常有道德、富有同情心的民族，他们乐于助人，尤其是在他们了解全部事实而非一分钟的片段之后。”在她看来，如果新闻媒体能够履行其职责，世界就能展现出同情心，并有助于促进自由。

Why does Amanpour believe the press has a responsibility to report all that they see? Are there situations in which it is acceptable to display partiality in reporting the news? Why or why not?
阿曼普尔为什么认为媒体有责任报道他们所看到的一切？在哪些情况下，新闻报道中表现出偏袒是可以接受的？为什么？

Before the Internet, traditional media determined whether citizen photographs or video footage would become “news.” In 1991, a private citizen’s camcorder footage showed four police officers beating an African American motorist named Rodney King in Los Angeles. After appearing on local independent television station, KTLA-TV, and then the national news, the event began a national discussion on police brutality and ignited riots in Los Angeles.16 The agenda-setting power of traditional media has begun to be appropriated by social media and smartphones, however. Twitter, Facebook, YouTube, and other Internet sites allow witnesses to instantly upload images and accounts of events and forward the link to friends. Some uploads go viral and attract the attention of the mainstream media, but large network newscasts and major newspapers are still more powerful at initiating or changing a discussion.

[.my2]
在互联网出现之前，传统媒体决定公民拍摄的照片或视频片段是否能成为“新闻”。1991 年，一位市民用摄像机拍摄的画面显示，四名警察在洛杉矶殴打一名名叫罗德尼·金的非裔美国司机。这段视频先是在当地独立电视台 KTLA-TV 播出，随后又出现在全国新闻中，引发了全国范围内关于警察暴行的讨论 ，并在洛杉矶引发了骚乱。然而，传统媒体的议程设置能力已经开始被社交媒体和智能手机所取代。Twitter、Facebook、YouTube 和其他互联网平台允许目击者即时上传事件的图片和描述，并将链接转发给朋友。一些上传的内容迅速走红，吸引了主流媒体的关注，但大型电视新闻节目和主流报纸在发起或改变讨论方面仍然拥有更大的影响力。

In summary, the traditional agenda-setting role provided by the media has become conflated with social media platforms. This trend is good from the standpoint of more exposure by the public to news topics and events than was the case before the rise of social media. However, there is reason to worry about whether fact-checking, which traditional media carry out, will be done on social media. Meta, the corporate owner of prominent social media platforms Facebook and Instagram, recently made the decision, in the name of free speech, to no longer fact-check the social media posts on their platforms.17
总而言之，传统媒体的议程设置作用已与社交媒体平台融合。从公众接触新闻话题和事件的程度来看，这种趋势是好事，因为与社交媒体兴起之前相比，公众接触到的新闻话题和事件更多。然而，人们有理由担心，传统媒体进行的事实核查是否会在社交媒体上继续进行。拥有知名社交媒体平台 Facebook 和 Instagram 的 Meta 公司最近以言论自由为由，决定不再对其平台上的社交媒体帖子进行事实核查。

The media also promote the public good by offering a platform for public debate and improving citizen awareness. Network news informs the electorate about national issues, elections, and international news. The New York Times, Los Angeles Times, NBC Nightly News, and other outlets make sure voters can easily find out what issues affect the nation. Is terrorism on the rise? Is the dollar weakening? The network news hosts national debates during presidential elections, broadcasts major presidential addresses, and interviews political leaders during times of crisis. Cable news networks now provide coverage of all these topics as well.

[.my2]
媒体通过提供公共辩论平台和提高公民意识来促进公共利益。电视新闻向选民通报国家大事、选举和国际新闻。 《纽约时报》 、 《洛杉矶时报》 、 NBC 晚间新闻和其他媒体确保选民能够轻松了解影响国家的各种问题。恐怖主义是否正在抬头？美元是否正在贬值？电视新闻在总统选举期间主持全国辩论，播出总统重要讲话，并在危机时期采访政治领导人。如今，有线电视新闻网也提供所有这些话题的报道。

Local news has a larger job, despite small budgets and fewer resources (Figure 8.5). Local government and local economic policy have a strong and immediate effect on citizens. Is the city government planning on changing property tax rates? Will the school district change the way Common Core tests are administered? When and where is the next town hall meeting or public forum to be held? Local and social media provide a forum for protest and discussion of issues that matter to the community.

[.my2]
尽管预算有限、资源匮乏，地方新闻媒体却肩负着更重要的使命（ 图 8.5 ）。地方政府和地方经济政策对市民有着直接而深远的影响。市政府是否计划调整房产税率？学区是否会改变“共同核心”考试的实施方式？下一次市政厅会议或公共论坛何时何地举行？地方媒体和社交媒体为抗议和讨论社区关注的问题提供了平台。

An image of a room with several wooden benches in the foreground and a long desk in the background. People are seated in both locations.

[.my2]
Figure 8.5 Meetings of local governance, such as this meeting of the Independence City Council in Missouri, are rarely attended by more than gadflies and journalists. (credit: "MoBikeFed"/Flickr)
图 8.5 地方政府会议，例如密苏里州独立市议会的会议，通常只有一些爱管闲事的人和记者参加。（图片来源：“MoBikeFed”/Flickr）
Link to Learning  学习链接
Want a snapshot of local and state political and policy news? The magazine Governing keeps an eye on what is happening in each state, offering articles and analysis on events that occur across the country.

[.my2]
想了解地方和州级政治及政策新闻概况吗？《 治理》 杂志密切关注各州动态，提供关于全国各地事件的文章和分析。

While journalists reporting the news try to present information in an unbiased fashion, sometimes the public seeks opinion and analysis of complicated issues that affect various populations differently, like healthcare reform and the Affordable Care Act. This type of coverage may come in the form of editorials, commentaries, Op-Ed columns, and blogs. These forums allow the editorial staff and informed columnists to express a personal belief and attempt to persuade. If opinion writers are trusted by the public, they have influence.

[.my2]
尽管新闻记者力求客观公正地呈现信息，但公众有时也希望了解一些复杂议题的观点和分析，例如医疗改革和《平价医疗法案》等，这些议题对不同人群的影响各不相同。这类报道的形式多种多样，包括社论、评论、专栏文章和博客。这些平台为编辑人员和资深专栏作家提供了表达个人观点和试图说服公众的渠道。如果公众信任评论员，他们就能产生影响力。

Walter Cronkite, reporting from Vietnam, had a loyal following. In a broadcast following the Tet Offensive in 1968, Cronkite expressed concern that the United States was mired in a conflict that would end in a stalemate.18 His coverage was based on opinion after viewing the war from the ground.19 Although the number of people supporting the war had dwindled by this time, Cronkite’s commentary bolstered opposition. Like editorials, commentaries contain opinion and are often written by specialists in a field. Larry Sabato, a prominent political science professor at the University of Virginia, occasionally writes his thoughts for the New York Times. These pieces are based on his expertise in politics and elections.20 Blogs offer more personalized coverage, addressing specific concerns and perspectives for a limited group of readers. As of 2021, the most popular blog on U.S. politics was The Daily Kos, a liberal blog with 25 million followers each month.21
沃尔特 ·克朗凯特在越南的报道拥有众多忠实听众。1968 年春节攻势后，克朗凯特在一次广播中表达了担忧，认为美国深陷一场最终会以僵局告终的冲突之中。 18 他的报道基于他从前线观察战争后的个人观点。 19 尽管此时支持战争的人数已经减少，但克朗凯特的评论却增强了反对战争的力量。与社论一样，评论文章也包含观点，并且通常由某一领域的专家撰写。弗吉尼亚大学著名政治学教授拉里·萨巴托偶尔会为 《纽约时报》 撰写评论文章。这些文章基于他在政治和选举方面的专业知识。 20 博客则提供更加个性化的报道，针对特定读者群体关注的问题和观点。截至 2021 年，美国政治领域最受欢迎的博客是 《每日科斯》（The Daily Kos） ，这是一个自由派博客，每月拥有 2500 万粉丝。 21





'''