
= 008-3 Regulating the Media 媒体监管
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





The Constitution gives Congress responsibility for promoting the general welfare. While it is difficult to define what this broad dictate means, Congress has used it to protect citizens from media content it deems inappropriate. Although the media are independent participants in the U.S. political system, their liberties are not absolute and there are rules they must follow.

[.my2]
宪法赋予国会促进公共福祉的责任。虽然很难界定这项宽泛的指令的具体含义，但国会一直利用它来保护公民免受其认为不当的媒体内容的影响。尽管媒体是美国政治体系中的独立参与者，但它们的自由并非绝对，它们必须遵守一定的规则。

MEDIA AND THE FIRST AMENDMENT
媒体与第一修正案
The U.S. Constitution was written in secrecy. Journalists were neither invited to watch the drafting, nor did the framers talk to the press about their disagreements and decisions. Once it was finished, however, the Constitution was released to the public and almost all newspapers printed it. Newspaper editors also published commentary and opinion about the new document and the form of government it proposed. Early support for the Constitution was strong, and Anti-Federalists (who opposed it) argued that their concerns were not properly covered by the press. The eventual printing of The Federalist Papers, and the lesser-known Anti-Federalist Papers, fueled the argument that the press was vital to American democracy. It was also clear the press had the ability to affect public opinion and therefore public policy.69
美国宪法是在秘密状态下起草的。记者既没有被邀请旁听起草过程，制宪者们也没有向媒体透露他们的分歧和决定。然而，宪法完成后，便向公众发布，几乎所有报纸都刊登了它。报纸编辑们也发表了关于这部新文件及其所提议的政府形式的评论和观点。宪法早期获得了强烈的支持，而反对宪法的反联邦主义者则认为，他们的诉求没有得到媒体的充分报道。最终， 《联邦党人文集》 和鲜为人知的《反联邦党人文集》的出版，进一步强化了媒体对美国民主至关重要的论点。媒体影响公众舆论乃至公共政策的能力也显而易见。 69

The approval of the First Amendment, as a part of the Bill of Rights, demonstrated the framers’ belief that a free and vital press was important enough to protect. It said:
作为权利法案的一部分， 第一修正案的通过表明了制宪者们的信念，即自由且至关重要的新闻媒体具有不可估量的重要性，必须加以保护。它指出：

“Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the government for a redress of grievances.”
“国会不得制定任何法律来确立国教，或禁止宗教自由；不得剥夺言论自由或出版自由；不得剥夺人民和平集会和向政府请愿伸冤的权利。”

This amendment serves as the basis for the political freedoms of the United States, and freedom of the press plays a strong role in keeping democracy healthy. Without it, the press would not be free to alert citizens to government abuses and corruption. In fact, one of New York’s first newspapers, the New York Weekly Journal, began under John Peter Zenger in 1733 with the goal of routing corruption in the colonial government. After the colonial governor, William Cosby, had Zenger arrested and charged with seditious libel in 1735, his lawyers successfully defended his case and Zenger was found not guilty, affirming the importance of a free press in the colonies (Figure 8.12).

[.my2]
这项修正案是美国政治自由的基石，而新闻自由在维护民主健康方面发挥着重要作用。没有它，新闻界就无法自由地向公民揭露政府的滥用职权和腐败行为。事实上，纽约最早的报纸之一 《纽约周刊》（New York Weekly Journal ）于 1733 年由约翰·彼得· 曾格（ John Peter Zenger）创办，其宗旨是揭露殖民地政府的腐败。1735 年，殖民地总督威廉·科斯比（William Cosby）逮捕了曾格，并以煽动性诽谤罪对其提起诉讼。然而，曾格的律师成功地为他辩护，最终他被判无罪，这充分证明了新闻自由在殖民地的重要性（ 图 8.12 ）。

An illustration of several men in a courtroom. One man is standing with his hand outstretched, facing the judge.

[.my2]
Figure 8.12 In defending John Peter Zenger against charges of libel against colonial governor William Cosby, Andrew Hamilton argued that a statement is not libelous if it can be proved. (credit: modification of work by the Library of Congress)
图 8.12 在为约翰·彼得·曾格辩护，使其免于诽谤殖民地总督威廉·科斯比的指控时，安德鲁·汉密尔顿辩称，如果一项陈述能够被证实，那么它就不构成诽谤。（图片来源：美国国会图书馆作品的修改版）
The media act as informants and messengers, providing the means for citizens to become informed and serving as a venue for citizens to announce plans to assemble and protest actions by their government. Yet the government must ensure the media are acting in good faith and not abusing their power. Like the other First Amendment liberties, freedom of the press is not absolute. The media have limitations on their freedom to publish and broadcast.

[.my2]
媒体扮演着信息提供者和信使的角色，为公民提供获取信息的途径，并为公民发布集会计划和抗议政府行为提供平台。然而，政府必须确保媒体秉持诚信行事，不滥用权力。与其他受宪法第一修正案保护的自由一样，新闻自由并非绝对。媒体的出版和广播自由受到限制。

Slander and Libel  诽谤和诋毁
First, the media do not have the right to commit slander, speak false information with an intent to harm a person or entity, or libel, print false information with an intent to harm a person or entity. These acts constitute defamation of character that can cause a loss of reputation and income. The media do not have the right to free speech in cases of libel and slander because the information is known to be false. Yet on a weekly basis, newspapers and magazines print stories that are negative and harmful. How can they do this and not be sued?
首先，媒体无权诽谤他人，即故意散布虚假信息以损害个人或实体利益；也无权诋毁他人，即故意刊登虚假信息以损害个人或实体利益。这些行为构成名誉损害，可能导致声誉和收入损失。在诽谤和诋毁案件中，媒体不享有言论自由，因为这些信息是已知的虚假信息。然而，报纸和杂志每周都会刊登负面且有害的报道。他们为何可以这样做而不被起诉？

First, libel and slander occur only in cases where false information is presented as fact. When editors or columnists write opinions, they are protected from many of the libel and slander provisions because they are not claiming their statements are facts. Second, it is up to the defamed individual or company to bring a lawsuit against the media outlet, and the courts have different standards depending on whether the claimant is a private or public figure. A public figure must show that the publisher or broadcaster acted in “reckless disregard” when submitting information as truth or that the author’s intent was malicious. This test goes back to the New York Times v. Sullivan (1964) case, in which a police commissioner in Alabama sued over inaccurate statements in a newspaper advertisement.70 Because the commissioner was a public figure, the U.S. Supreme Court applied a stringent test of malice to determine whether the advertisement was libel; the court deemed it was not.

[.my2]
首先，诽谤和诋毁仅指将虚假信息当作事实呈现的情况。当编辑或专栏作家撰写评论文章时，由于他们并未声称自己的陈述是事实，因此受到许多诽谤和诋毁条款的保护。其次，是否对媒体提起诉讼取决于被诽谤的个人或公司，而法院会根据原告是公众人物还是私人人士采用不同的标准。公众人物必须证明出版商或广播公司在发布信息时存在“鲁莽漠视”的行为，或者作者的意图是恶意的。这一标准可以追溯到 1964 年的 “纽约时报诉沙利文案”（New York Times v. Sullivan ） ，该案中，阿拉巴马州的一位警察局长就报纸广告中的不实陈述提起诉讼。由于该局长是公众人物，美国最高法院采用了严格的恶意检验标准来判定该广告是否构成诽谤；法院最终裁定该广告不构成诽谤。

A private individual must make one of the above arguments or argue that the author was negligent in not making sure the information was accurate before publishing it. For this reason, newspapers and magazines are less likely to stray from hard facts when covering private individuals, yet they can be willing to stretch the facts when writing about politicians, celebrities, or public figures. But even stretching the truth can be costly for a publisher. In 2010, Star magazine published a headline, “Addiction Nightmare: Katie Drug Shocker,” leading readers to believe actress Katie Holmes was taking drugs. While the article in the magazine focuses on the addictive quality of Scientology sessions rather than drugs, the implication and the headline were different. Because drugs cause people to act erratically, directors might be less inclined to hire Holmes if she were addicted to drugs. Thus Holmes could argue that she had lost opportunity and income from the headline. While the publisher initially declined to correct the story, Holmes filed a $50 million lawsuit, and Star’s parent company American Media, Inc. eventually settled. Star printed an apology and made a donation to a charity on Holmes’ behalf.71
个人必须提出上述论点之一，或者辩称作者在发布信息前疏忽大意，未能核实信息的准确性。因此，报纸和杂志在报道个人时更倾向于遵循事实，但在报道政治人物、名人或公众人物时，则可能愿意夸大其词。然而，即使是夸大其词，对出版商来说也可能代价高昂。2010 年， 《明星》 杂志刊登了一篇题为“成瘾噩梦：凯蒂吸毒丑闻”的报道，误导读者认为女演员凯蒂 ·霍尔姆斯吸毒。虽然杂志文章的重点是山达基教的成瘾性而非毒品，但标题和文章的含义却截然不同。由于毒品会导致人的行为异常，如果霍尔姆斯真的吸毒成瘾，导演们可能就不愿意聘用她了。因此，霍尔姆斯可以辩称，这篇报道让她失去了机会和收入。尽管出版商最初拒绝更正报道，霍尔姆斯还是提起了一项 5000 万美元的诉讼，最终 《明星》杂志的母公司美国媒体公司（American Media, Inc.）与霍尔姆斯达成了和解。 《明星》杂志刊登了道歉声明，并以霍姆斯的名义向慈善机构捐款 。71

Classified Material  机密材料
The media have only a limited right to publish material the government says is classified. If a newspaper or media outlet obtains classified material, or if a journalist is witness to information that is classified, the government may request certain material be redacted or removed from the article. In many instances, government officials and former employees give journalists classified paperwork in an effort to bring public awareness to a problem. If the journalist calls the White House or Pentagon for quotations on a classified topic, the president may order the newspaper to stop publication in the interest of national security. The courts are then asked to rule on what is censored and what can be printed.

[.my2]
媒体对政府认定为机密的材料的发布权十分有限。如果报纸或媒体机构获得了机密材料，或者记者目睹了机密信息，政府可以要求对文章中的某些内容进行编辑或删除。在许多情况下，政府官员和前雇员会向记者提供机密文件，以期引起公众对某个问题的关注。如果记者就机密话题致电白宫或五角大楼寻求引述，总统可以出于国家安全考虑，命令报纸停止刊登。之后，法院将对哪些内容需要审查、哪些内容可以刊登做出裁决。

The line between the people’s right to know and national security is not always clear. In 1971, the Supreme Court heard the Pentagon Papers case, in which the U.S. government sued the New York Times and the Washington Post to stop the release of information from a classified study of the Vietnam War. The Supreme Court ruled that while the government can impose prior restraint on the media, meaning the government can prevent the publication of information, that right is very limited. The court gave the newspapers the right to publish much of the study, but revelation of troop movements and the names of undercover operatives are some of the few approved reasons for which the government can stop publication or reporting.

[.my2]
民众的知情权与国家安全之间的界限并非总是清晰的。1971 年，最高法院审理了“ 五角大楼文件案”。在该案中，美国政府起诉《 纽约时报》 和 《华盛顿邮报》 ，试图阻止其发布一份关于越南战争的机密研究报告。最高法院裁定，虽然政府可以对媒体实施事先限制 ，即阻止信息的发布，但这项权利受到诸多限制。法院允许报纸刊登该研究报告的大部分内容，但只有少数情况下，政府才能以披露部队调动和秘密特工姓名等少数正当理由阻止信息的发布或报道。

During the second Persian Gulf War, FOX News reporter Geraldo Rivera convinced the military to embed him with a U.S. Army unit in Iraq to provide live coverage of its day-to-day activities. During one of the reports he filed while traveling with the 101st Airborne Division, Rivera had his camera operator record him drawing a map in the sand, showing where his unit was and using Baghdad as a reference point. Rivera then discussed where the unit would go next. Rivera was immediately removed from the unit and escorted from Iraq.72 The military exercised its right to maintain secrecy over troop movements, stating that Rivera’s reporting had given away troop locations and compromised the safety of the unit. Rivera’s future transmissions and reporting were censored until he was away from the unit.

[.my2]
在第二次海湾战争期间，福克斯新闻记者杰拉尔多 ·里维拉说服军方让他随美军驻伊拉克部队进行现场报道，报道其日常行动。在随第 101 空降师行进期间的一次报道中，里维拉让摄影师拍摄他在沙地上绘制地图的画面，地图上标明了部队的位置，并以巴格达为参照点。随后，里维拉讨论了部队的下一步行动计划。里维拉随即被调离部队，并被护送离开伊拉克 。军方行使了对部队行动保密的权利，声称里维拉的报道泄露了部队位置，危及了部队安全。在里维拉离开部队之前，他之后的所有报道和通讯都受到了审查。

MEDIA AND FCC REGULATIONS
媒体与联邦通信委员会法规
The liberties enjoyed by newspapers are overseen by the U.S. court system, while television and radio broadcasters are monitored by both the courts and a government regulatory commission.

[.my2]
报纸享有的自由受到美国法院系统的监督，而电视和广播公司则受到法院和政府监管委员会的双重监督。

The Radio Act of 1927 was the first attempt by Congress to regulate broadcast materials. The act was written to organize the rapidly expanding number of radio stations and the overuse of frequencies. But politicians feared that broadcast material would be obscene or biased. The Radio Act thus contained language that gave the government control over the quality of programming sent over public airwaves, and the power to ensure that stations maintained the public’s best interest.73
1927 年的《 无线电法》 是国会首次尝试规范广播内容。该法案旨在规范迅速增长的广播电台数量和频率的过度使用。但政界人士担心广播内容会包含淫秽或带有偏见的内容。因此，《无线电法》包含赋予政府控制公共无线电波节目质量的条款，并赋予政府确保电台维护公众利益的权力 。73

The Communications Act of 1934 replaced the Radio Act and created a more powerful entity to monitor the airwaves—a seven-member Federal Communications Commission (FCC) to oversee both radio and telephone communication. The FCC, which now has only five members (Figure 8.13), requires radio stations to apply for licenses, granted only if stations follow rules about limiting advertising, providing a public forum for discussion, and serving local and minority communities. With the advent of television, the FCC was given the same authority to license and monitor television stations. The FCC now also enforces ownership limits to avoid monopolies and censors materials deemed inappropriate. It has no jurisdiction over print media, mainly because print media are purchased and not broadcast.

[.my2]
1934 年的《 通信法》 取代了《无线电法》，并设立了一个权力更大的机构来监管无线电波——由七名成员组成的联邦通信委员会 (FCC)，负责监管无线电和电话通信。如今，FCC 仅剩五名成员（ 图 8.13 ），它要求广播电台申请许可证，只有遵守限制广告、提供公共讨论论坛以及服务于当地社区和少数族裔社区等规定的电台才能获得许可证。随着电视的出现，FCC 也被赋予了同样的权力，可以对电视台进行许可和监管。FCC 现在还强制执行所有权限制，以避免垄断，并审查被认为不合适的内容。它对印刷媒体没有管辖权，主要是因为印刷媒体是购买的，而不是广播的。

A photograph shows the five commissioners of the F C C, Nathan Simington, Brendan Carr, Jessica Rosenworcel, Geoffrey Starks, and Anna Gomez.

[.my2]
Figure 8.13 In March 2024, the leadership of the FCC included (from left to right) Nathan Simington, Brendan Carr, Jessica Rosenworcel (chair), Geoffrey Starks, and Anna Gomez. Rosenworcel resigned from the FCC in January 2025. Carr is now the chair, and Simington, Starks and Gomez remain as commissioners. (credit: Federal Communications Commission)
图 8.13 2024 年 3 月，美国联邦通信委员会 (FCC) 的领导层成员包括（从左至右）：内森·西明顿 (Nathan Simington)、布伦丹·卡尔 (Brendan Carr)、杰西卡·罗森沃塞尔 (Jessica Rosenworcel)（主席）、杰弗里·斯塔克斯 (Geoffrey Starks) 和安娜·戈麦斯 (Anna Gomez)。罗森沃塞尔于 2025 年 1 月辞去 FCC 职务。卡尔现任主席，西明顿、斯塔克斯和戈麦斯继续担任委员。（图片来源：美国联邦通信委员会）
Link to Learning  学习链接
Concerned about something you heard or viewed? Would you like to file a complaint about an obscene radio program or place your phone number on the Do Not Call list? The FCC oversees each of these.

[.my2]
对您听到或看到的内容感到担忧？您想投诉淫秽广播节目或将您的电话号码添加到“请勿来电”名单中吗？ 联邦通信委员会 (FCC) 负责监管这些事项。

To maintain a license, stations are required to meet a number of criteria. The equal-time rule, for instance, states that registered candidates running for office must be given equal opportunities for airtime and advertisements at non-cable television and radio stations beginning forty-five days before a primary election and sixty days before a general election. Should WBNS in Columbus, Ohio, agree to sell Senator Marco Rubio thirty seconds of airtime for a presidential campaign commercial, the station must also sell all other candidates in that race thirty seconds of airtime at the same price. This rate cannot be more than the station charges favored commercial advertisers that run ads of the same class and during the same time period.74 More importantly, should Fox5 in Atlanta give Bernie Sanders five minutes of free airtime for an infomercial, the station must honor requests from all other candidates in the race for five minutes of free equal air time or a complaint may be filed with the FCC.75 In 2015, Donald Trump, when he was running for the Republican presidential nomination, appeared on Saturday Night Live. Other Republican candidates made equal time requests, and NBC agreed to give each candidate twelve minutes and five seconds of air time on a Friday and Saturday night, as well as during a later episode of Saturday Night Live.76
为了维持执照，电视台必须满足多项标准。例如， 平等播出时间规则规定，所有已登记的候选人在初选前 45 天和普选前 60 天，必须在非有线电视和广播电台获得平等的播出时间和广告机会。如果俄亥俄州哥伦布市的 WBNS 电视台同意向参议员马可·卢比奥出售 30 秒的播出时间用于总统竞选广告，那么该电视台也必须以同样的价格向该竞选中的所有其他候选人出售 30 秒的播出时间。该价格不得高于该电视台向在其服务范围内投放同类广告且播出时间相同的商业广告商收取的费用。更重要的是，如果亚特兰大的 Fox5 电视台向伯尼·桑德斯提供 5 分钟的免费播出时间用于电视购物广告，那么该电视台必须满足该竞选中所有其他候选人提出的 5 分钟免费平等播出时间的要求，否则可能会向联邦通信委员会（FCC）提出投诉。 2015 年，唐纳德·特朗普在竞选共和党总统候选人提名期间，曾亮相 《周六夜现场》 。其他共和党候选人也提出了同等的播出时间要求，NBC 同意在周五和周六晚上，以及之后播出的 《周六夜现场》 节目中，给予每位候选人 12 分 05 秒的播出时间 。76

The FCC does waive the equal-time rule if the coverage is purely news. If a newscaster is covering a political rally and is able to secure a short interview with a candidate, equal time does not apply. Likewise, if a news programs creates a short documentary on the problem of immigration reform and chooses to include clips from only one or two candidates, the rule does not apply.77 But the rule may include shows that are not news. For this reason, some stations will not show a movie or television program if a candidate appears in it. In 2003, Arnold Schwarzenegger and Gary Coleman, both actors, became candidates in California’s gubernatorial recall election. Television stations did not run Coleman’s sitcom Diff’rent Strokes or Schwarzenegger’s movies, because they would have been subject to the equal time provision. With 135 candidates on the official ballot, stations would have been hard-pressed to offer thirty-minute and two-hour time slots to all.78 Even the broadcasting of the president’s State of the Union speech can trigger the equal-time provisions. Opposing parties in Congress now use their time immediately following the State of the Union to offer an official rebuttal to the president’s proposals.79
如果报道内容纯粹是新闻，联邦通信委员会（FCC）会豁免“平等时间规则”。例如，如果新闻主播报道一场政治集会，并成功采访到一位候选人，则“平等时间规则”不适用。同样，如果新闻节目制作了一部关于移民改革问题的短纪录片，并选择只播放一两位候选人的片段，则该规则也不适用。 77 但该规则可能适用于非新闻类节目。因此，如果候选人出现在电影或电视节目中，一些电视台就不会播出。2003 年，演员阿诺德·施瓦辛格和加里·科尔曼都参加了加州州长罢免选举。电视台没有播出科尔曼的情景喜剧 《迪弗伦特 ·斯托克斯》或施瓦辛格的电影，因为这些节目会受到“平等时间规则”的约束。由于正式选票上有 135 位候选人，电视台很难为所有候选人提供 30 分钟和 2 小时的播出时段。 78 甚至总统发表国情咨文的电视直播也可能触发平等时间条款。国会反对党现在会利用国情咨文结束后立即发表正式反驳总统提案的时间 。79

While the idea behind the equal-time rule is fairness, it may not apply beyond candidates to supporters of that candidate or of a cause. Hence, there potentially may be a loophole in which broadcasters can give free time to just one candidate’s supporters. In the 2012 Wisconsin gubernatorial recall election, Scott Walker’s supporters were allegedly given free air time to raise funds and ask for volunteers while opponent Tom Barrett’s supporters were not.80 According to someone involved in the case, the FCC declined to intervene after a complaint was filed on the matter, saying the equal-time rule applied only to the actual candidates, and that the case was an instance of the now-dead fairness doctrine.81 The fairness doctrine was instituted in 1949 and required licensed stations to cover controversial issues in a balanced manner by providing listeners with information about all perspectives on any controversial issue. If one candidate, cause, or supporter was given an opportunity to reach the viewers or listeners, the other side was to be given a chance to present its side as well. The fairness doctrine ended in the 1980s, after a succession of court cases led to its repeal by the FCC in 1987, with stations and critics arguing the doctrine limited debate of controversial topics and placed the government in the role of editor.82
虽然平等时间规则背后的理念是公平，但它可能并不适用于候选人以外的其他群体，例如候选人的支持者或某个事业的支持者。因此，广播公司可能存在漏洞，允许他们只向一位候选人的支持者提供免费播出时间。在 2012 年威斯康星州州长罢免选举中，据称斯科特·沃克的支持者获得了免费的播出时间来筹款和招募志愿者，而他的对手汤姆·巴雷特的支持者却没有。 80 据一位参与此案的人士透露，联邦通信委员会（FCC）在收到相关投诉后拒绝介入，称平等时间规则仅适用于候选人本人，而此案属于现已失效的公平原则的范畴。 81 公平原则于 1949 年确立，要求持证电台以平衡的方式报道争议性议题，向听众提供关于任何争议性议题所有观点的信息。如果一位候选人、事业或支持者有机会接触观众或听众，那么另一方也应该有机会陈述自己的观点。公平原则在 20 世纪 80 年代终结。一系列诉讼最终导致联邦通信委员会（FCC）于 1987 年废除了该原则。电台和批评人士认为，该原则限制了对争议性话题的辩论，并将政府置于编辑的角色 。82

The FCC also maintains indecency regulations over television, radio, and other broadcasters, which limit indecent material and keep the public airwaves free of obscene material.83 While the Supreme Court has declined to define obscenity, it is identified using a test outlined in Miller v. California (1973).84 Under the Miller test, obscenity is something that appeals to deviants, breaks local or state laws, and lacks value.85 The Supreme Court determined that the presence of children in the audience trumped the right of broadcasters to air obscene and profane programming. However, broadcasters can show indecent programming or air profane language between the hours of 10 p.m. and 6 a.m.86
美国联邦通信委员会（FCC）还对电视、广播和其他广播机构制定了不雅内容法规 ，限制不雅内容的播出，确保公共广播免受淫秽内容的侵害。 83 虽然最高法院拒绝为淫秽内容下定义，但通常采用米勒诉加利福尼亚州案 （1973 年）中概述的标准来界定。 84 根据米勒标准，淫秽内容是指那些迎合变态者、违反地方或州法律且缺乏价值的内容。 85 最高法院裁定，儿童在场这一因素优先于广播机构播出淫秽和亵渎性节目的权利。然而，广播机构可以在晚上 10 点至早上 6 点之间播出不雅节目或使用亵渎性语言。 86

The Supreme Court has also affirmed that the FCC has the authority to regulate content. When a George Carlin skit was aired on the radio with a warning that material might be offensive, the FCC still censored it. The station appealed the decision and lost.87 Fines can range from tens of thousands to millions of dollars, and many are levied for sexual jokes on radio talk shows and nudity on television. In 2004, Janet Jackson’s wardrobe malfunction during the Super Bowl’s half-time show cost the CBS network $550,000.

[.my2]
最高法院也确认了联邦通信委员会（FCC）有权监管内容。乔治·卡林的一段小品在电台播出时，尽管有警告称内容可能令人反感，但 FCC 仍然对其进行了审查。电台对此决定提出上诉，但败诉。 罚款金额从数万美元到数百万美元不等，许多罚款都是针对电台脱口秀中的性笑话和电视节目中的裸露镜头。2004 年，珍妮·杰克逊在超级碗中场秀上的服装事故导致哥伦比亚广播公司（CBS）被罚款 55 万美元。

While some FCC violations are witnessed directly by commission members, like Jackson’s exposure at the Super Bowl, the FCC mainly relies on citizens and consumers to file complaints about violations of equal time and indecency rules. Approximately 2 percent of complaints to the FCC are about radio programming and 10 percent about television programming, compared to 71 percent about telephone complaints and 15 percent about Internet complaints.88 Yet what constitutes a violation is not always clear for citizens wishing to complain, nor is it clear what will lead to a fine or license revocation. In October 2014, parent advocacy groups and consumers filed complaints and called for the FCC to fine ABC for running a sexually charged opening scene in the drama Scandal immediately after It’s the Great Pumpkin, Charlie Brown—without an ad or the cartoon’s credits to act as a buffer between the very different types of programming.89 The FCC did not fine ABC.

[.my2]
虽然有些联邦通信委员会（FCC）的违规行为是由委员会成员直接目睹的，例如杰克逊在超级碗上的裸露事件，但 FCC 主要依靠公民和消费者对违反平等播出时间和不雅内容规定的行为进行投诉。向 FCC 提交的投诉中，约 2%涉及广播节目，10%涉及电视节目，相比之下，71%的投诉来自电话，15%涉及网络。 88 然而，对于想要投​​诉的公民来说，究竟什么构成违规并不总是很明确，也不清楚哪些行为会导致罚款或吊销执照。2014 年 10 月，家长权益组织和消费者提交了投诉，呼吁 FCC 对 ABC 电视台处以罚款，原因是该电视台在播出 《查理·布朗的万圣节》（It's the Great Pumpkin, Charlie Brown） 之后，紧接着播出了电视剧《丑闻》 （Scandal） 中一段带有性暗示的开场——而且没有在两种截然不同的节目类型之间插入广告或动画片的片尾字幕作为缓冲。 89 但 FCC 最终没有对 ABC 电视台处以罚款。

The Telecommunications Act of 1996 brought significant changes to the radio and television industries. It dropped the limit on the number of radio stations (forty) and television stations (twelve) a single company could own. It also allowed networks to purchase large numbers of cable stations. In essence, it reduced competition and increased the number of conglomerates. Some critics, such as Common Cause, argue that the act also raised cable prices and made it easier for companies to neglect their public interest obligations.90 The act also changed the role of the FCC from regulator to monitor. The Commission oversees the purchase of stations to avoid media monopolies and adjudicates consumer complaints against radio, television, and telephone companies.

[.my2]
1996 年的《 电信法》 给广播电视行业带来了重大变革。它取消了单一公司可拥有的广播电台（40 家）和电视台（12 家）数量的上限，并允许电视网收购大量有线电视台。从本质上讲，该法案削弱了竞争，增加了企业集团的数量。一些批评人士，例如“共同事业”（Common Cause）组织，认为该法案还推高了有线电视价格，并使公司更容易忽视其公共利益义务。 90 该法案还将联邦通信委员会（FCC）的角色从监管机构转变为监督机构。委员会负责监督电视台的收购，以避免媒体垄断，并裁决消费者针对广播、电视和电话公司的投诉。

An important change in government regulation of the press in the name of the fairness of coverage relates to net neutrality. Net neutrality rules were promulgated in 2015 by the Obama administration. These regulations required internet service providers to give everyone equal access to their services and disallowed biased charging of internet access fees. Early in the Trump Administration, the Federal Communications Commission (FCC) reversed that course by throwing out the policy of net neutrality.91 Later, the Trump administration challenged California's state law providing for net neutrality in court. The Biden administration dropped the lawsuit less than two weeks after taking office in 2021.92 In March 2020, a group of tech companies petitioned the FCC to go a step further and formally reinstate net neutrality.93 In April 2024, the FCC reinstated net neutrality by order of a vote of 3-2. In response, USTelecom, a trade group that represents prominent internet provides, including AT&T and Verizon, brought suit against the FCC. The U.S. Court of Appeals for the Sixth Circuit in early January 2025 ruled that the FCC did not have legal authority to reinstate the net neutrality rules.94
政府以保障新闻报道公平为名对新闻界进行监管的一项重要变革与网络中立性有关。网络中立性规则由奥巴马政府于 2015 年颁布。这些规则要求互联网服务提供商向所有人提供平等的服务访问权限，并禁止收取带有偏见的互联网接入费用。特朗普政府上任初期，联邦通信委员会（FCC）推翻了这一政策，废除了网络中立性。 91 随后，特朗普政府在法庭上挑战了加利福尼亚州关于网络中立性的州法律。拜登政府在 2021 年上任不到两周后便撤销了诉讼。 92 2020 年 3 月，一群科技公司向 FCC 请愿，要求更进一步，正式恢复网络中立性。 93 2024 年 4 月，FCC 以 3 比 2 的投票结果恢复了网络中立性。作为回应，代表包括 AT&T 和 Verizon 在内的主要互联网服务提供商的行业协会 USTelecom 对 FCC 提起了诉讼。 2025 年 1 月初，美国第六巡回上诉法院裁定，联邦通信委员会（FCC）无权恢复网络中立规则 。94

Finding a Middle Ground
寻找折衷方案
Watch Dog or Paparazzi?
看门狗还是狗仔队？
We expect the media to keep a close eye on the government. But at what point does the media coverage cross from informational to sensational?
我们希望媒体密切关注政府。但媒体报道何时会从提供信息转变为耸人听闻呢？

In 2012, former secretary of state Hillary Clinton was questioned about her department’s decisions regarding the U.S. consulate in Benghazi, Libya. The consulate had been bombed by militants, leading to the death of an ambassador and a senior service officer. It was clear the United States had some knowledge that there was a threat to the consulate, and officials wondered whether requests to increase security at the consulate had been ignored. Clinton was asked to appear before a House Select Committee to answer questions, and the media began its coverage. While some journalists limited their reporting to Benghazi, others did not. Clinton was hounded about everything from her illness (dubbed the “Benghazi-flu”) to her clothing to her facial expressions to her choice of eyeglasses.95 Even her hospital stay was questioned.96 Some argued the expanded coverage was due to political attacks on Clinton, who at that time was widely perceived to be the top contender for the Democratic presidential nomination in 2016.97 Republican majority leader Kevin McCarthy later implied that the hearings were an attempt to make Clinton look untrustworthy.98 Yet Clinton was again brought before the House Select Committee on Benghazi as late as October 2015 (Figure 8.14).

[.my2]
2012 年，前国务卿希拉里· 克林顿因其部门对美国驻利比亚班加西领事馆的决策而受到质询。该领事馆遭到武装分子炸弹袭击，导致一名大使和一名高级官员丧生。显然，美国方面对领事馆面临的威胁有所了解，官员们质疑是否忽视了加强领事馆安保的请求。克林顿被要求出席众议院特别委员会的听证会并回答问题，媒体也开始对此事进行报道。虽然一些记者将报道范围限定在班加西事件上，但也有一些记者没有。从克林顿的病情（被称为“班加西流感”）到她的穿着、面部表情，再到她选择的眼镜，媒体对她的方方面面都穷追猛打。甚至连她的住院经历也受到了质疑。 96 有人认为，扩大调查范围是由于对克林顿的政治攻击，当时她被普遍认为是 2016 年民主党总统候选人提名的热门人选 。97 共和党多数党领袖凯文·麦卡锡后来暗示，这些听证会是为了抹黑克林顿，让她看起来不可信 。98 然而，直到 2015 年 10 月，克林顿再次被传唤到众议院班加西事件特别委员会作证（ 图 8.14 ）。

An image of several people seated behind a long wooden bench.

[.my2]
Figure 8.14 On October 22, 2015, the House Select Committee on Benghazi listened to testimony from former Secretary of State Hillary Clinton for close to eleven hours.

[.my2]
图 8.14 2015 年 10 月 22 日，众议院班加西事件特别委员会听取了前国务卿希拉里·克林顿近 11 个小时的证词。
This coverage should lead us to question whether the media gives us the information we need, or the information we want. Were people concerned about an attack on U.S. state officials working abroad, or did they just want to read rumors and attacks on Clinton? Did Republicans use the media’s tendency to pursue a target as a way to hurt Clinton in the polls? If the media gives us what we want, the answer seems to be that we wanted the media to act as both watchdog and paparazzi.

[.my2]
这些报道应该让我们质疑，媒体究竟是提供我们需要的信息，还是提供我们想要的信息。人们究竟是关心在海外工作的美国政府官员是否遭到攻击，还是仅仅想看关于希拉里·克林顿的谣言和攻击？共和党人是否利用媒体热衷于攻击特定目标的倾​​向，来损害克林顿的民调支持率？如果媒体提供的是我们想要的，那么答案似乎是：我们希望媒体既扮演监督者的角色，又扮演狗仔队的角色。

How should the press have acted in this case if it were behaving only as the watchdog of democracy?
如果媒体仅仅扮演民主监督者的角色，那么它在这种情况下应该如何行事？

MEDIA AND TRANSPARENCY  媒体与透明度
The press has had some assistance in performing its muckraking duty. Laws that mandate federal and many state government proceedings and meeting documents be made available to the public are called sunshine laws. Proponents believe that open disagreements allow democracy to flourish and darkness allows corruption to occur. Opponents argue that some documents and policies are sensitive, and that the sunshine laws can inhibit policymaking.

[.my2]
新闻媒体在履行其揭露丑闻的职责时得到了一些帮助。一些法律规定联邦政府和许多州政府的程序和会议文件必须向公众公开，这些法律被称为 “阳光法” 。支持者认为，公开的分歧能够促进民主发展，而黑暗则容易滋生腐败。反对者则认为，有些文件和政策涉及敏感信息，“阳光法”可能会阻碍政策制定。

While some documents may be classified due to national or state security, governments are encouraged to limit the over-classification of documents. The primary legal example for sunshine laws is the Freedom of Information Act (FOIA), passed in 1966 and signed by President Lyndon B. Johnson. The act requires the executive branch of the U.S. government to provide information requested by citizens and was intended to increase openness in the executive branch, which had been criticized for hiding information. Citizens wishing to obtain information may request documents from the appropriate agencies, and agencies may charge fees if the collection and copying of the requested documentation requires time and labor.99 FOIA also identifies data that does not need to be disclosed, such as human resource and medical records, national defense records, and material provided by confidential sources, to name a few.100 Not all presidents have embraced this openness, however. President Ronald Reagan, in 1981, exempted the CIA and FBI from FOIA requests.101 Information requests have increased significantly in recent years, with U.S. agencies receiving over 700,000 requests in 2014, many directed to the Departments of State and Defense, thus creating a backlog.102 As FOIA requests have become institutionalized across the levels of the U.S. government, one challenge is the work created in responding to those requests.103 For example, at the University of Oklahoma, two staff in the university counsel's office spend most of their time responding to FOIA requests about the university.

[.my2]
虽然某些文件可能因涉及国家或州安全而被列为机密，但政府应尽量避免过度保密。阳光法案的主要法律范例是 1966 年通过并由林登·约翰逊总统签署的《 信息自由法》（FOIA） 。该法案要求美国政府行政部门提供公民要求的信息，旨在提高行政部门的透明度，此前该部门因隐瞒信息而备受诟病。希望获取信息的公民可以向相关机构申请文件，如果收集和复制所需文件需要耗费时间和人力，机构可以收取费用。99 《信息自由法》还列出了无需公开的数据，例如人力资源和医疗记录、国防记录以及来自秘密来源的材料等等。100 然而 ，并非所有总统都支持这种公开透明的做法。1981 年，罗纳德·里根总统将中央情报局和联邦调查局排除在《信息自由法 》 的适用范围之外。 101 近年来，信息请求数量显著增加，美国各机构在 2014 年收到了超过 70 万份请求，其中许多请求指向国务院和国防部，从而造成了积压。102 随着《信息自由法 》 请求在美国各级政府中制度化，应对这些请求所带来的工作量成为一项挑战。103 例如，在俄克拉荷马大学，大学法律顾问办公室的两名工作人员的大部分时间都花在了回复有关该大学的 《信息自由法》请求上。

Link to Learning  学习链接
Want to request a government document but unsure where to start? If the agency is a part of the U.S. government, the Freedom of Information Act portal will help you out.

[.my2]
想申请政府文件但不知道从何入手？如果该机构是美国政府的一部分， 《信息自由法》 门户网站可以帮到您。

Few people file requests for information because most assume the media will find and report on important problems. And many people, including the press, assume the government, including the White House, sufficiently answers questions and provides information about government actions and policies. This expectation is not new. During the Civil War, journalists expected to have access to those representing the government, including the military. But William Tecumseh Sherman, a Union general, maintained distance between the press and his military. Following the publication of material Sherman believed to be protected by government censorship, a journalist was arrested and nearly put to death. The event spurred the creation of accreditation for journalists, which meant a journalist must be approved to cover the White House and the military before entering a controlled area. All accredited journalists also need approval by military field commanders before coming near a military zone.104
很少有人提出信息请求，因为大多数人认为媒体会主动发现并报道重要问题。许多人，包括媒体，都认为政府，包括白宫，会充分回答问题并提供有关政府行动和政策的信息。这种期望并非新鲜事。内战期间，记者们期望能够接触到政府代表，包括军方。但联邦将军威廉·特库姆塞· 谢尔曼却将媒体与军队隔离开来。在谢尔曼认为受政府审查制度保护的材料发表后，一名记者被捕，险些被处死。这一事件促使记者认证制度的建立，这意味着记者必须获得批准才能报道白宫和军队，然后才能进入管制区域。所有获得认证的记者在靠近军事区域之前，还需要获得军事指挥官的批准 。104

To cover war up close, more journalists are asking to travel with troops during armed conflict. In 2003, George W. Bush’s administration decided to allow more journalists in the field, hoping the concession would reduce friction between the military and the press. The U.S. Department of Defense placed fifty-eight journalists in a media boot camp to prepare them to be embedded with military regiments in Iraq. Although the increase in embedded journalists resulted in substantial in-depth coverage, many journalists felt their colleagues performed poorly, acting as celebrities rather than reporters.105
为了近距离报道战争，越来越多的记者要求在武装冲突期间随军出征。2003 年，乔治·W· 布什政府决定允许更多记者进入战区，希望此举能够减少军方与媒体之间的摩擦。美国国防部将 58 名记者送入媒体训练营，为他们随军前往伊拉克作战做准备。尽管随军记者人数的增加带来了大量的深度报道， 但许多记者认为他们的同事表现不佳，更像是明星而非记者。

The line between journalists’ expectation of openness and the government’s willingness to be open has continued to be a point of contention. Some administrations use the media to increase public support during times of war, as Woodrow Wilson did in World War I. Other presidents limit the media in order to limit dissent. In 1990, during the first Persian Gulf War, journalists received all publication material from the military in a prepackaged and staged manner. Access to Dover, the air force base that receives coffins of U.S. soldiers who die overseas, was closed. Journalists accused George H. W. Bush’s administration of limiting access and forcing them to produce bad pieces. The White House believed it controlled the message.106 The ban was later lifted.

[.my2]
新闻记者对信息公开的期望与政府公开意愿之间的界限一直存在争议。一些政府在战争时期利用媒体来提升公众支持率，例如伍德罗·威尔逊在一战期间的做法。另一些总统则限制媒体，以压制异议。1990 年，在第一次海湾战争期间，记者们从军方获得的所有出版材料都是预先包装好的。接收阵亡美军士兵棺材的多佛空军基地也被关闭。记者们指责老布什政府限制他们的采访权限，并强迫他们发表负面报道。白宫则认为他们掌控着舆论。 106 这项禁令后来被解除。

In his 2008 presidential run, Barack Obama promised to run a transparent White House.107 Yet once in office, he found that transparency makes it difficult to get work done, and so he limited access and questions. In his first year in office, George W. Bush, who was criticized by Obama as having a closed government, gave 147 question-and-answer sessions with journalists, while Obama gave only 46. Even Helen Thomas, a long-time liberal White House press correspondent, said the Obama administration tried to control both information and journalists (Figure 8.15).108
在 2008 年竞选总统时，巴拉克· 奥巴马承诺要建立一个透明的白宫。 107 然而，上任后他发现，透明度反而阻碍了工作的开展，因此他限制了信息获取和提问。在奥巴马执政的第一年，曾被奥巴马批评为政府封闭的乔治·W·布什与记者进行了 147 次问答，而奥巴马只进行了 46 次。就连长期担任白宫新闻记者的自由派人士海伦·托马斯也表示，奥巴马政府试图控制信息和记者（ 图 8.15 ）。 108

The Trump administration had an especially bumpy relationship with the news media. In part, this had to do with Trump's penchant for using Twitter, instead of news briefings, to get his thoughts out to the public. The repeated line from the former president that news media could not be trusted, which he called "fake news," added insult to injury. The prickly relationship also resulted from reduced use of traditional press gaggles and excluding some media outlets, such as CNN, when tempers flared.

[.my2]
特朗普政府与新闻媒体的关系尤其紧张。部分原因是特朗普喜欢用推特而非新闻发布会来表达自己的想法。这位前总统反复声称新闻媒体不可信，称之为“假新闻”，这无疑是雪上加霜。此外，特朗普政府减少了与传统媒体的接触，并在双方情绪激动时将一些媒体机构（例如 CNN）排除在外，也导致了这种棘手的关系。

While some may have expected the Biden administration to undertake a complete reversal from the Trump White House, the first few months demonstrated that presidents' overall relationships with the press may have evolved. A number of news outlets and media commentators noted the lack of a formal press conference for months after Biden took office. However, he did frequently provide comments and answer questions during other occasions.109
尽管有些人可能预期拜登政府会彻底推翻特朗普白宫的做法，但上任后的头几个月表明，总统与媒体的整体关系可能已经发生了变化。许多新闻媒体和评论员注意到，拜登就职后的几个月里都没有举行正式的新闻发布会。然而，他经常在其他场合发表评论并回答问题 。109

An image of Barack Obama and Helen Thomas seated. Obama holds a plate of cake.

[.my2]
Figure 8.15 President Barack Obama and White House correspondent Helen Thomas set aside their differences over transparency to enjoy cupcakes in honor of their shared birthday on August 4, 2009.

[.my2]
图 8.15 2009 年 8 月 4 日，美国总统巴拉克·奥巴马和白宫记者海伦·托马斯搁置了他们在透明度问题上的分歧，一起享用纸杯蛋糕，庆祝他们共同的生日。
Because White House limitations on the press are not unusual, many journalists rely on confidential sources. In 1972, under the cloak of anonymity, the associate director of the Federal Bureau of Investigation, Mark Felt, became a news source for Bob Woodward and Carl Bernstein, political reporters at the Washington Post. Felt provided information about a number of potential stories and was Woodward’s main source for information about President Richard Nixon’s involvement in a series of illegal activities, including the break-in at Democratic Party headquarters in Washington’s Watergate office complex. The information eventually led to Nixon’s resignation and the indictment of sixty-nine people in his administration. Felt was nicknamed “Deep Throat,” and the journalists kept his identity secret until 2005.110
由于白宫对新闻自由的限制并不罕见，许多记者依赖于秘密消息来源。1972 年，联邦调查局副局长马克· 费尔特 （Mark Felt）以匿名身份成为 《华盛顿邮报》 政治记者鲍勃 ·伍德沃德 （Bob Woodward）和卡尔 ·伯恩斯坦（Carl Bernstein） 的新闻来源。费尔特提供了许多潜在新闻线索，并且是伍德沃德获取有关理查德·尼克松总统参与一系列非法活动（包括闯入位于华盛顿水门大厦的民主党总部）信息的主要来源。这些信息最终导致尼克松辞职，其政府中的 69 人被起诉。费尔特被昵称为“ 深喉 ”，两位记者一直保守着他的真实身份，直到 2005 年。

The practice of granting anonymity to sources is sometimes referred to as reporter’s privilege. Fueled by the First Amendment’s protection of the press, journalists have long offered to keep sources confidential to protect them from government prosecution. To illustrate, as part of the investigation into the outing of Valerie Plame as a CIA officer, New York Times reporter Judith Miller was jailed for refusing to reveal “Scooter” Libby, Vice President Dick Cheney’s chief of staff, as her confidential government source.111 Reporter’s privilege has increased the number of instances in which whistleblowers and government employees have given journalists tips or documents to prompt investigation into questionable government practices. Edward Snowden’s 2013 leak to the press regarding the U.S. government’s massive internal surveillance and tapping program was one such case.

[.my2]
给予消息来源匿名保护的做法有时被称为记者特权 。受美国宪法第一修正案对新闻自由的保护，记者长期以来一直主动为消息来源保密，以保护他们免受政府起诉。例如，在对瓦莱丽·普莱姆（Valerie Plame）被揭露为中央情报局官员一事进行调查的过程中， 《纽约时报》 记者朱迪思· 米勒 （Judith Miller）因拒绝透露副总统迪克·切尼（Dick Cheney）的幕僚长“斯库特”·利比（Scooter Libby）是她的秘密政府消息来源而被捕入狱 。记者特权使得举报人和政府雇员向记者提供线索或文件以促使调查可疑政府行为的案例数量有所增加。爱德华·斯诺登（Edward Snowden）2013 年向媒体泄露美国政府大规模内部监控和窃听计划就是其中一例。

In 1972, however, the Supreme Court determined that journalists are not exempt from subpoenas and that courts could force testimony to name a confidential source. Journalists who conceal a source and thereby protect that source from being properly tried for a crime may spend time in jail for contempt of court. In the case of Branzburg v. Hayes (1972), three journalists were placed in contempt of court for refusing to divulge sources.112 The journalists appealed to the Supreme Court. In a 5–4 decision, the justices determined that freedom of the press did not extend to the confidentiality of sources. A concurring opinion did state that the case should be seen as a limited ruling, however. If the government needed to know a source due to a criminal trial, it could pursue the name of that source.113
然而，1972 年，最高法院裁定记者并非不受传票约束，法院可以强制证人提供秘密消息来源的姓名。记者如果隐瞒消息来源，从而保护该消息来源免于因犯罪受到公正审判，可能会因藐视法庭罪而被判入狱。在布兰兹堡诉海耶斯案（1972 年）中，三名记者因拒绝透露消息来源而被判藐视法庭罪。 112 这些记者向最高法院提起上诉。最高法院以 5 比 4 的投票结果裁定，新闻自由并不包括消息来源的保密权。不过，一份协同意见指出，该案的裁决应被视为一项有限的裁决。如果政府因刑事审判需要了解消息来源，则可以追查该消息来源的姓名。 113

More recently, the Supreme Court refused to hear an appeal from New York Times journalist James Risen, who was subpoenaed and ordered to name a confidential source who had provided details about a U.S. government mission designed to harm Iran’s nuclear arms program. Risen was finally released from the subpoena, but the battle took seven years and the government eventually collected enough other evidence to make his testimony less crucial to the case.114 Overall, the transparency of the government is affected more by the executive currently holding office than by the First Amendment.

[.my2]
最近，最高法院拒绝受理 《纽约时报》 记者詹姆斯·里森的上诉。里森曾被传唤，并被要求指认一名曾提供美国政府旨在损害伊朗核武器计划的秘密消息来源。里森最终被解除传唤，但这场斗争持续了七年，政府最终收集到足够的其他证据，使得他的证词对案件的重要性降低 。114 总的来说，政府透明度更多地受到现任行政官员的影响，而非第一修正案的影响。

'''