
= 008-4 The Impact of the Media 媒体的影响
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义






In what ways can the media affect society and government? The media’s primary duty is to present us with information and alert us when important events occur. This information may affect what we think and the actions we take. The media can also place pressure on government to act by signaling a need for intervention or showing that citizens want change. For these reasons, the quality of the media’s coverage matters.

[.my2]
媒体可以通过哪些方式影响社会和政府？媒体的首要职责是向我们提供信息，并在发生重大事件时发出警报。这些信息可能会影响我们的想法和行动。媒体还可以通过发出需要干预的信号或表明公民渴望变革的呼声，向政府施加压力，促使其采取行动。正因如此，媒体报道的质量至关重要。

MEDIA EFFECTS AND BIAS
媒体效应与偏见
Concerns about the effects of media on consumers and the existence and extent of media bias go back to the 1920s. Reporter and commentator Walter Lippmann noted that citizens have limited personal experience with government and the world and posited that the media, through their stories, place ideas in citizens’ minds. These ideas become part of the citizens’ frame of reference and affect their decisions. Lippmann’s statements led to the hypodermic theory, which argues that information is “shot” into the receiver’s mind and readily accepted.115
早在 20 世纪 20 年代，人们就开始关注媒体对消费者的影响以及媒体偏见的存在和程度。记者兼评论员沃尔特 ·李普曼指出，公民对政府和世界的个人经验有限，并提出媒体通过报道将观念植入公民的头脑中。这些观念成为公民认知框架的一部分，并影响他们的决策。李普曼的观点催生了 “皮下注射理论” ，该理论认为信息被“注射”到接收者的头脑中，并被迅速接受。 115

Yet studies in the 1930s and 1940s found that information was transmitted in two steps, with one person reading the news and then sharing the information with friends. People listened to their friends, but not to those with whom they disagreed. The newspaper’s effect was thus diminished through conversation. This discovery led to the minimal effects theory, which argues the media have little effect on citizens and voters.116 By the 1970s, a new idea, the cultivation theory, hypothesized that media develop a person’s view of the world by presenting a perceived reality.117 What we see on a regular basis is our reality. Media can then set norms for readers and viewers by choosing what is covered or discussed.

[.my2]
然而，20 世纪 30 年代和 40 年代的研究发现，信息的传播是分两步进行的：一个人阅读新闻，然后将信息分享给朋友。人们会听取朋友的意见，但不会听取与自己意见相左的人的意见。因此，报纸的影响力在口口相传中被削弱了。这一发现催生了最小效应理论 ，该理论认为媒体对公民和选民的影响微乎其微。 116 到了 20 世纪 70 年代，一种新的理论—— 培养理论 ——提出，媒体通过呈现一种感知到的现实来塑造人们的世界观。 117 我们日常所见即为我们的现实。媒体可以通过选择报道或讨论的内容来为读者和观众设定规范。

In the end, the consensus among observers is that media have some effect, even if the effect is subtle. This raises the question of how the media, even general newscasts, can affect citizens. One of the ways is through framing: the creation of a narrative, or context, for a news story. The news often uses frames to place a story in a context so the reader understands its importance or relevance. Yet, at the same time, framing affects the way the reader or viewer processes the story.

[.my2]
最终，观察人士普遍认为媒体确实会产生一定影响，即便这种影响可能较为微妙。这就引出了一个问题：媒体，甚至包括一般新闻节目，究竟是如何影响公民的？其中一种方式是通过框架构建 ：即为新闻报道创造叙事或背景。新闻报道常常运用框架将新闻置于特定的语境中，以便读者理解其重要性或相关性。然而，与此同时，框架构建也会影响读者或观众处理新闻的方式。

Episodic framing occurs when a story focuses on isolated details or specifics rather than looking broadly at a whole issue. Thematic framing takes a broad look at an issue and skips numbers or details. It looks at how the issue has changed over a long period of time and what has led to it. For example, a large, urban city is dealing with the problem of an increasing homeless population, and the city has suggested ways to improve the situation. If journalists focus on the immediate statistics, report the current percentage of homeless people, interview a few, and look at the city’s current investment in a homeless shelter, the coverage is episodic. If they look at homelessness as a problem increasing everywhere, examine the reasons people become homeless, and discuss the trends in cities’ attempts to solve the problem, the coverage is thematic. Episodic frames may create more sympathy, while a thematic frame may leave the reader or viewer emotionally disconnected and less sympathetic (Figure 8.16).

[.my2]
事件式报道是指故事聚焦于孤立的细节或具体事件，而非着眼于整体问题。 主题式报道则着眼于问题的宏观层面，省略具体数字或细节，而是关注问题在长期发展过程中的变化及其成因。例如，一个大型城市正面临日益严重的无家可归人口问题，并提出了改善现状的方案。如果记者只关注眼前的统计数据，例如报道当前无家可归者的比例、采访几位无家可归者，以及考察该市目前对无家可归者收容所的投资，那么这种报道就是事件式的。但如果他们将无家可归问题视为一个日益普遍的全球性问题，探究人们流落街头的原因，并探讨城市为解决这一问题所做的努力，那么这种报道就是主题式的。事件式报道可能更容易引起读者或观众的共鸣，而主题式报道则可能使读者或观众感到疏离，难以产生同情心（ 图 8.16 ）。

An image of an old person. In the background are an adult and a child in a tent.

[.my2]
Figure 8.16 Civil war in Syria has led many to flee the country, including this woman living in a Syrian refugee camp in Jordan in September 2015. Episodic framing of the stories of Syrian refugees, and their deaths, turned government inaction into action. (credit: Enes Reyhan)
图 8.16 叙利亚内战导致许多人逃离家园，其中包括这位 2015 年 9 月居住在约旦叙利亚难民营的妇女。对叙利亚难民及其死亡事件的片段式叙述，促使政府的不作为转变为采取行动。（图片来源：Enes Reyhan）
Link to Learning  学习链接
For a closer look at framing and how it influences voters, read “How the Media Frames Political Issues”, a review essay by Scott London.

[.my2]
要更深入地了解框架及其对选民的影响，请阅读斯科特·伦敦撰写的评论文章 《媒体如何构建政治议题》 。

Framing can also affect the way we see race, socioeconomics, or other generalizations. For this reason, it is linked to priming: when media coverage predisposes the viewer or reader to a particular perspective on a subject or issue. If a newspaper article focuses on unemployment, struggling industries, and jobs moving overseas, the reader will have a negative opinion about the economy. If then asked whether they approve of the president’s job performance, the reader is primed to say no. Readers and viewers are able to fight priming effects if they are aware of them or have prior information about the subject.

[.my2]
框架效应也会影响我们看待种族、社会经济状况或其他概括性问题的方式。因此，它与启动效应密切相关：媒体报道会使观众或读者对某个主题或问题产生特定的视角。如果一篇报纸文章聚焦于失业、行业困境和工作岗位外流，读者就会对经济产生负面看法。如果随后被问及是否认可总统的工作表现，读者很可能会被引导着回答“不”。如果读者和观众意识到启动效应的存在，或者事先了解相关主题，他们就能抵御这种效应的影响。

COVERAGE EFFECTS ON GOVERNANCE AND CAMPAIGNS
报道对治理和竞选的影响
When it is spotty, the media’s coverage of campaigns and government can sometimes affect the way government operates and the success of candidates. In 1972, for instance, the McGovern-Fraser reforms created a voter-controlled primary system, so party leaders no longer pick the presidential candidates. Now the media are seen as kingmakers and play a strong role in influencing who will become the Democratic and Republican nominees in presidential elections. They can discuss the candidates’ messages, vet their credentials, carry sound bites of their speeches, and conduct interviews. The candidates with the most media coverage build momentum and do well in the first few primaries and caucuses. This, in turn, leads to more media coverage, more momentum, and eventually a winning candidate. Thus, candidates need the media.

[.my2]
当媒体报道时断时续时，其对竞选和政府的报道有时会影响政府的运作方式和候选人的成败。例如，1972年，麦戈文-弗雷泽改革建立了选民控制的初选制度，使得政党领袖不再挑选总统候选人。如今，媒体被视为“造王者”，在影响民主党和共和党总统候选人提名方面发挥着重要作用。他们可以讨论候选人的竞选信息，审查他们的资历，传播他们的演讲片段，并进行采访。获得最多媒体曝光的候选人能够积累势头，并在最初几场初选和党团会议中表现出色。反过来，这又会带来更多的媒体报道，更大的势头，并最终促成候选人胜出。因此，候选人需要媒体的支持。

In the 1980s, campaigns learned that tight control on candidate information created more favorable media coverage. In the presidential election of 1984, candidates Ronald Reagan and George H. W. Bush began using an issue-of-the-day strategy, providing quotes and material on only one topic each day. This strategy limited what journalists could cover because they had only limited quotes and sound bites to use in their reports. In 1992, both Bush’s and Bill Clinton’s campaigns maintained their carefully drawn candidate images by also limiting photographers and television journalists to photo opportunities at rallies and campaign venues. The constant control of the media became known as the “bubble,” and journalists were less effective when they were in the campaign’s bubble. Reporters complained this coverage was campaign advertising rather than journalism, and a new model emerged with the 1996 election.118
20 世纪 80 年代，竞选活动发现，严格控制候选人信息能带来更有利的媒体报道。在 1984 年的总统选举中，候选人罗纳德·里根和乔治·H·W·布什开始采用“每日议题”策略，每天只提供关于一个主题的引语和资料。这种策略限制了记者的报道范围，因为他们只能使用有限的引语和片段。1992 年，布什和比尔·克林顿的竞选团队为了维护精心塑造的候选人形象，也限制了摄影师和电视记者只能在集会和竞选场所进行拍摄。这种对媒体的持续控制被称为“信息茧房”，记者身处竞选活动的“信息茧房”中，工作效率降低。记者们抱怨这种报道更像是竞选广告而非新闻报道，一种新的模式在 1996 年大选中出现 。118

Campaign coverage now focuses on the spectacle of the season, rather than providing information about the candidates. Colorful personalities, strange comments, lapse of memories, and embarrassing revelations are more likely to get air time than the candidates’ issue positions. Donald Trump may be the best example of shallower press coverage of a presidential election. Some argue that newspapers and news programs are limiting the space they allot to discussion of the campaigns.119 Others argue that citizens want to see updates on the race and electoral drama, not boring issue positions or substantive reporting.120 It may also be that journalists have tired of the information games played by politicians and have taken back control of the news cycles.121 All these factors have likely led to the shallow press coverage we see today, sometimes dubbed pack journalism because journalists follow one another rather than digging for their own stories. Television news discusses the strategies and blunders of the election, with colorful examples. Newspapers focus on polls. In an analysis of the 2012 election, Pew Research found that 64 percent of stories and coverage focused on campaign strategy. Only 9 percent covered domestic issue positions; 6 percent covered the candidates’ public records; and, 1 percent covered their foreign policy positions.122
如今的竞选报道侧重于营造节日氛围，而非提供候选人的相关信息。个性鲜明的候选人、奇特的言论、记忆力衰退以及令人尴尬的爆料，比候选人的政纲更能吸引眼球。唐纳德· 特朗普或许是总统选举新闻报道肤浅的最佳例证。有人认为，报纸和新闻节目正在缩减用于讨论竞选活动的篇幅。 119 另一些人则认为，民众想了解的是选情和选举戏剧的最新进展，而不是枯燥乏味的政纲或实质性报道。 120 也可能是因为记者们厌倦了政客们玩弄的信息游戏，重新掌控了新闻周期。 121 所有这些因素都可能导致了我们今天看到的肤浅的新闻报道，这种报道有时被称为 “集群新闻”， 因为记者们互相追随，而不是挖掘自己的新闻故事。电视新闻会讨论选举策略和失误，并列举各种生动的例子。报纸则专注于民调。皮尤研究中心对 2012 年大选的分析发现，64%的报道都集中在竞选策略上。只有 9%报道了国内议题立场；6%报道了候选人的公开记录；而只有 1%报道了他们的外交政策立场 。122

For better or worse, coverage of the candidates’ statements get less air time on radio and television, and sound bites, or clips, of their speeches have become even shorter. In 1968, the average sound bite from Richard Nixon was 42.3 seconds, while a recent study of television coverage found that sound bites had decreased to only eight seconds in the 2004 election.123 The clips chosen to air were attacks on opponents 40 percent of the time. Only 30 percent contained information about the candidate’s issues or events. The study also found the news showed images of the candidates, but for an average of only twenty-five seconds while the newscaster discussed the stories.124
无论好坏，广播和电视对候选人声明的报道时长都在减少，而他们演讲的片段也变得更短。1968 年，理查德·尼克松的平均演讲片段时长为 42.3 秒，而最近一项针对电视报道的研究发现，2004 年大选期间，演讲片段的平均时长已缩短至仅 8 秒。 123 播出的片段中，40%是对对手的攻击，只有 30%包含有关候选人政见或活动的信息。该研究还发现，新闻节目虽然会播放候选人的画面，但平均只有 25 秒，其余时间都是新闻主播在播报新闻。 124

This study supports the argument that shrinking sound bites are a way for journalists to control the story and add their own analysis rather than just report on it.125 Candidates are given a few minutes to try to argue their side of an issue, but some say television focuses on the argument rather than on information. In 2004, Jon Stewart of Comedy Central’s The Daily Show began attacking the CNN program Crossfire for being theater, saying the hosts engaged in reactionary and partisan arguing rather than true debating.126 Some of Stewart’s criticisms resonated, even with host Paul Begala, and Crossfire was later pulled from the air.127
这项研究支持这样一种观点：缩短新闻片段是记者控制新闻报道、添加自身分析而非仅仅进行客观报道的一种手段。125 候选人有几分钟时间来阐述自己对某个问题的观点，但有人认为电视节目更关注的是辩论本身，而非信息。2004 年，喜剧中心频道 《每日秀》 的主持人乔恩· 斯图尔特开始抨击 CNN 的 《交叉火力》 节目，称其为作秀，并表示主持人之间的争论带有反动和党派色彩，而非真正的辩论 。126 斯图尔特的一些批评引起了共鸣，甚至连主持人保罗·贝加拉也认同， 《交叉火力》节目最终停播 。127

The media’s discussion of campaigns has also grown negative. Although biased campaign coverage dates back to the period of the partisan press, the increase in the number of cable news stations has made the problem more visible. Stations like FOX News and MSNBC are overt in their use of bias in framing stories. During the 2012 campaign, seventy-one of seventy-four MSNBC stories about Mitt Romney were highly negative, while FOX News’ coverage of Obama had forty-six out of fifty-two stories with negative information (Figure 8.17). The major networks—ABC, CBS, and NBC—were somewhat more balanced, yet the overall coverage of both candidates tended to be negative.128 Coverage of the COVID-19 pandemic also featured differences, which had an effect on the public. In the spring of 2020, a study of public opinion on the origins of the virus and likelihood of a vaccine being developed, revealed that respondents who watched FOX News were much more likely to believe the virus was created in a lab and much less likely to have confidence that a vaccine would be developed to stop the disease, whereas respondents who relied on MSNBC believed the virus originated in nature and were quite confident a vaccine would be developed.129
媒体对竞选活动的报道也趋于负面。虽然带有偏见的竞选报道可以追溯到党派媒体时代，但有线新闻频道的增加使这个问题更加显而易见。像福克斯新闻和 MSNBC 这样的电视台在报道中公然使用偏见。在 2012 年总统竞选期间，MSNBC 关于米特·罗姆尼的 74 篇报道中有 71 篇带有强烈的负面色彩，而福克斯新闻关于奥巴马的 52 篇报道中有 46 篇包含负面信息（ 图 8.17 ）。主要电视网——ABC、CBS 和 NBC——的报道相对平衡一些，但对两位候选人的整体报道也倾向于负面。 128 对新冠疫情的报道也存在差异，这对公众产生了影响。 2020 年春季，一项关于公众对病毒起源和疫苗研发可能性的看法调查显示，观看福克斯新闻的受访者更倾向于相信病毒是实验室制造的，并且对研发出疫苗以阻止疫情的信心也更低；而依赖 MSNBC 的受访者则认为病毒起源于自然界，并且对研发出疫苗相当有信心 。129

A bar graph titled “Bias in cable News coverage of Presidential Candidates, 2012”. The legend lists two categories, “stories with negative tone” and “stories with positive tone”. Under “CNN”, stories about Obama were 18% positive and 21% negative, and stories about Romney were 11% positive and 36% negative.  Under “MSNBC”, stories about Obama were 39% positive and 15% negative, and stories about Romney were 3% positive and 71% negative. Under “FOX”, stories about Obama were 6% positive and 46% negative, and stories about Romney were 28% positive and 12% negative. At the bottom of the graph, a source is cited: “Pew Research Center. “Tone of Coverage on Cable News.” August 27-October 21, 2012.”.

[.my2]
Figure 8.17 Media coverage of campaigns is increasingly negative, with cable news stations demonstrating more bias in their framing of stories during the 2012 campaign.

[.my2]
图 8.17 媒体对竞选活动的报道越来越负面，有线新闻频道在 2012 年竞选期间的报道框架中表现出更多的偏见。
Due in part to the lack of substantive media coverage, campaigns increasingly use social media to relay their message. Candidates can create their own sites and pages and try to spread news through supporters to the undecided. In 2012, both Romney and Obama maintained Facebook, Twitter, and YouTube accounts to provide information to voters. Yet, on social media, candidates still need to combat negativity, from both the opposition and supporters. Stories about Romney that appeared in the mainstream media were negative 38 percent of the time, while his coverage in Facebook news was negative 62 percent of the time and 58 percent of the time on Twitter.130 In the 2016 election cycle, both party nominees heavily used social media. Donald Trump’s scores of tweets became very prominent as he tweeted during Clinton’s convention acceptance speech and sometimes at all hours of the night. Clinton also used Twitter, but less so than Trump, though arguably staying better on message. Trump tended to rail on about topics and at one point was even drawn into a Twitter battle with Senator Elizabeth Warren (D-MA). Hillary Clinton also used Facebook for longer messages and imaging. Trump took social media posts to a new level, both in terms of the number of posts and the intensity. In January 2021, he was permanently suspended from the Twitter platform due to "the risk of further incitement of violence" in the wake of the January 6th attack on the U.S. capitol building. In contrast, Biden has used social media quite sparingly, both during his campaign and after becoming president.

[.my2]
部分原因是缺乏实质性的媒体报道，竞选活动越来越多地利用社交媒体来传递信息。候选人可以创建自己的网站和页面，并尝试通过支持者向尚未决定投票意向的选民传播消息。2012 年，罗姆尼和奥巴马都开设了 Facebook、Twitter 和 YouTube 账号，以便向选民提供信息。然而，在社交媒体上，候选人仍然需要应对来自反对派和支持者的负面信息。主流媒体上关于罗姆尼的报道有 38%是负面的，而他在 Facebook 新闻上的负面报道比例为 62%，在 Twitter 上的负面报道比例为 58%。在 2016 年大选周期中，两党候选人都大量使用了社交媒体。唐纳德·特朗普的大量推文尤其引人注目，他在希拉里·克林顿发表接受提名演讲期间以及有时在深夜发布推文。克林顿也使用 Twitter，但不如特朗普频繁，不过可以说她在信息传递方面做得更好。特朗普经常就各种话题发表长篇大论，甚至一度与马萨诸塞州民主党参议员伊丽莎白·沃伦在推特上展开骂战。希拉里·克林顿也经常在脸书上发布较长的信息和图片。特朗普将社交媒体的使用推向了一个新的高度，无论是在发帖数量还是强度方面。2021 年 1 月，在 1 月 6 日美国国会大厦遭受袭击后，由于“存在进一步煽动暴力的风险”，他的推特账号被永久封禁。相比之下，拜登在竞选期间和就任总统后都很少使用社交媒体。

Once candidates are in office, the chore of governing begins, with the added weight of media attention. Historically, if presidents were unhappy with their press coverage, they used personal and professional means to change its tone. Franklin D. Roosevelt, for example, was able to keep journalists from printing stories through gentleman’s agreements, loyalty, and the provision of additional information, sometimes off the record. The journalists then wrote positive stories, hoping to keep the president as a source. John F. Kennedy hosted press conferences twice a month and opened the floor for questions from journalists, in an effort to keep press coverage positive.131
一旦候选人就职，治理国家的重任便随之而来，同时还要承受媒体关注的压力。历史上，如果总统对媒体报道不满，他们会运用个人和职业手段来改变报道的基调。例如，富兰克林·罗斯福就曾通过君子协定、忠诚以及提供额外信息（有时甚至是非正式信息）来阻止记者刊登不利于他的报道。记者们随后便撰写正面报道，希望继续将总统视为消息来源。约翰·肯尼迪每月召开两次新闻发布会，并开放提问环节，以期保持媒体报道的正面性。

When presidents and other members of the White House are not forthcoming with information, journalists must press for answers. Dan Rather, a journalist for CBS, regularly sparred with presidents in an effort to get information. When Rather interviewed Richard Nixon about Vietnam and Watergate, Nixon was hostile and uncomfortable.132 In a 1988 interview with then-vice president George H. W. Bush, Bush accused Rather of being argumentative about the possible cover-up of a secret arms sale with Iran:
当总统和白宫其他成员不愿提供信息时，记者必须追问答案。哥伦比亚广播公司（CBS）记者丹·拉瑟经常与总统们争论，试图获取信息。拉瑟就越南战争和水门事件采访理查德·尼克松时，尼克松态度敌对，感到不自在。 132 在 1988 年对时任副总统乔治·H·W·布什的采访中，布什指责拉瑟就可能掩盖与伊朗的秘密军售一事与他争论不休：

Rather: I don’t want to be argumentative, Mr. Vice President.

[.my2]
相反：副总统先生，我不想争论。
Bush: You do, Dan.

[.my2]
布什：你确实有，丹。
Rather: No—no, sir, I don’t.

[.my2]
而是：不——不，先生，我没有。
Bush: This is not a great night, because I want to talk about why I want to be president, why those 41 percent of the people are supporting me. And I don’t think it’s fair to judge my whole career by a rehash of Iran. How would you like it if I judged your career by those seven minutes when you walked off the set in New York? 133
布什：今晚不太妙，因为我想谈谈我为什么想当总统，为什么有 41%的人支持我。我觉得用伊朗问题来评判我的整个政治生涯是不公平的。如果我只凭你在纽约离开片场的那七分钟就评判你的政治生涯，你觉得怎么样？ 133

One of the more profound changes with President Trump compared to prior presidents revolved around his relationship with the press. Trump rarely held press conferences, choosing instead to tweet what he was thinking to the world. Whereas previous presidents spent much effort to cultivate relationships with the media in order to court public opinion, Trump instead criticized the media as untrustworthy and producing "fake news." This approach led to critical coverage of the president across all but a few press outlets. Moreover, President Trump's attack on the media led key outlets, like CNN and the Washington Post, to take action. CNN sued in federal court to get one of their news reporters (Jim Acosta) reinstated on the White House beat after he was thrown out of the West Wing. The Washington Post has run the tagline "Democracy Dies in Darkness" on its website regularly since 2017. Compared to Trump, President Biden's relationship with the press is more conventional, with regular interaction and briefings by Press Secretary Jennifer Psaki.134
与前几任总统相比，特朗普总统最深刻的变化之一体现在他与媒体的关系上。特朗普很少召开新闻发布会，而是选择通过推特向全世界表达自己的想法。以往的总统为了赢得公众舆论，会花费大量精力与媒体建立良好关系，而特朗普却批评媒体不可信，制造“假新闻”。这种做法导致除少数几家媒体外，几乎所有媒体都对总统进行了批评报道。此外，特朗普对媒体的攻击促使 CNN 和《华盛顿邮报》等重要媒体采取了行动。CNN 向联邦法院提起诉讼，要求恢复其新闻记者吉姆·阿科斯塔（Jim Acosta）在白宫西翼被解雇后的白宫报道工作。《华盛顿邮报》自 2017 年以来，一直在其网站上定期刊登“民主死于黑暗”的标语。与特朗普相比，拜登总统与媒体的关系更为传统，新闻秘书詹妮弗·普萨基（Jennifer Psaki）会定期与媒体互动并举行简报会。

Cabinet secretaries and other appointees also talk with the press, sometimes making for conflicting messages. The creation of the position of press secretary and the White House Office of Communications both stemmed from the need to send a cohesive message from the executive branch. Currently, the White House controls the information coming from the executive branch through the Office of Communications and decides who will meet with the press and what information will be given.

[.my2]
内阁部长和其他官员也会与媒体接触，有时会导致信息传递出现矛盾。设立新闻秘书一职和白宫通讯办公室的初衷，正是为了确保行政部门传递的信息保持一致。目前，白宫通过通讯办公室控制着来自行政部门的信息，并决定谁可以与媒体见面以及发布哪些信息。

But stories about the president often examine personality, or the president’s ability to lead the country, deal with Congress, or respond to national and international events. They are less likely to cover the president’s policies or agendas without a lot of effort on the president’s behalf.135 When Obama first entered office in 2009, journalists focused on his battles with Congress, critiquing his leadership style and inability to work with Representative Nancy Pelosi, then Speaker of the House. To gain attention for his policies, specifically the American Recovery and Reinvestment Act (ARRA), Obama began traveling the United States to draw the media away from Congress and encourage discussion of his economic stimulus package. Once the ARRA had been passed, Obama began travelling again, speaking locally about why the country needed the Affordable Care Act and guiding media coverage to promote support for the act.136
但关于总统的报道往往侧重于总统的个人魅力，或是总统领导国家、与国会打交道以及应对国内外事件的能力。除非总统方面投入大量精力，否则报道总统的政策或议程并不常见。 135 奥巴马 2009 年首次就任总统时，记者们关注的焦点是他与国会的斗争，批评他的领导风格以及他与时任众议院议长南希·佩洛西合作不力。为了宣传他的政策，特别是 《美国复苏与再投资法案》 （ARRA），奥巴马开始在美国各地奔走，将媒体的注意力从国会转移开来，鼓励人们讨论他的经济刺激方案。ARRA 通过后，奥巴马再次开始奔走各地，在各地发表演讲，阐述国家为何需要《 平价医疗法案》 ，并引导媒体报道，以促进对该法案的支持。 136

Congressional representatives have a harder time attracting media attention for their policies. House and Senate members who use the media well, either to help their party or to show expertise in an area, may increase their power within Congress, which helps them bargain for fellow legislators’ votes. Senators and high-ranking House members may also be invited to appear on cable news programs as guests, where they may gain some media support for their policies. Yet, overall, because there are so many members of Congress, and therefore so many agendas, it is harder for individual representatives to draw media coverage.137
国会议员的政策更难获得媒体关注。善于利用媒体的众议院和参议院议员，无论是为了帮助本党还是为了展现自身在某个领域的专业知识，都能提升其在国会的影响力，从而有助于他们争取其他议员的投票支持。参议员和众议院的高级议员也可能受邀作为嘉宾出现在有线电视新闻节目中，从而获得一些媒体对其政策的支持。然而，总体而言，由于国会议员人数众多，议程也各不相同，因此单个议员想要获得媒体关注就更加困难 。137

It is less clear, however, whether media coverage of an issue leads Congress to make policy, or whether congressional policymaking leads the media to cover policy. In the 1970s, Congress investigated ways to stem the number of drug-induced deaths and crimes. As congressional meetings dramatically increased, the press was slow to cover the topic. The number of hearings was at its highest from 1970 to 1982, yet media coverage did not rise to the same level until 1984.138 Subsequent hearings and coverage led to national policies like DARE and First Lady Nancy Reagan’s “Just Say No” campaign (Figure 8.18).

[.my2]
然而，媒体对某一问题的报道究竟是促使国会制定政策，还是国会的政策制定促使媒体报道政策，这一点尚不明确。20 世纪 70 年代，国会曾调查如何遏制毒品致死和致罪案件的数量。随着国会会议次数的急剧增加，媒体对这一议题的报道却进展缓慢。1970 年至 1982 年间，听证会的数量达到顶峰，但媒体报道直到 1984 年才达到同样的水平。随后的听证会和媒体报道促成了诸如“拒绝毒品滥用教育”（DARE）项目和第一夫人南希·里根发起的“对毒品说不”（Just Say No）运动等国家政策的出台（ 图 8.18 ）。

Image A is of Nancy Reagan standing behind a podium. A sign on the podium reads “Just say no”. Image B is of a poster that reads “D.A.R.E. to resist drugs and violence. Drug Abuse Resistance Education”.

[.my2]
Figure 8.18 First Lady Nancy Reagan speaks at a “Just Say No” rally in Los Angeles on May 13, 1987 (a). The Drug Abuse Resistance Education (D.A.R.E.) is an anti-drug, anti-gang program founded in 1983 by a joint initiative of the Los Angeles Police Department and the Los Angeles Unified School District.

[.my2]
图 8.18 1987 年 5 月 13 日，第一夫人南希·里根在洛杉矶举行的“拒绝毒品”集会上发表讲话 (a)。“药物滥用抵抗教育”（DARE）是一项反毒品、反帮派计划，由洛杉矶警察局和洛杉矶联合学区于 1983 年联合发起。
Later studies of the media’s effect on both the president and Congress report that the media has a stronger agenda-setting effect on the president than on Congress. What the media choose to cover affects what the president thinks is important to voters, and these issues were often of national importance. The media’s effect on Congress was limited, however, and mostly extended to local issues like education or child and elder abuse.139 If the media are discussing a topic, chances are a member of Congress has already submitted a relevant bill, and it is waiting in committee.

[.my2]
后来对媒体对总统和国会影响的研究表明，媒体对总统的议程设置影响比对国会的影响更大。媒体选择报道的内容会影响总统认为选民关注的重点，而这些重点往往是国家层面的重要议题。然而，媒体对国会的影响有限，主要局限于教育或虐待儿童和老人等地方性议题。 139 如果媒体正在讨论某个话题，很可能国会议员已经提交了相关的法案，目前正在委员会等待审议。

COVERAGE EFFECTS ON SOCIETY
报道对社会的影响
The media choose what they want to discuss. This agenda setting creates a reality for voters and politicians that affects the way people think, act, and vote. Even if the crime rate is going down, for instance, citizens accustomed to reading stories about assault and other offenses still perceive crime to be an issue.140 Studies have also found that the media’s portrayal of race is flawed, especially in coverage of crime and poverty. One study revealed that local news shows were more likely to show pictures of criminals when they were African American, so they overrepresented Black people as perpetrators and White people as victims.141 A second study found a similar pattern in which Latino people were underrepresented as victims of crime and as police officers, while White people were overrepresented as both.142 Voters were thus more likely to assume that most criminals are African American and most victims and police officers are White, even though the numbers do not support those assumptions.

[.my2]
媒体会选择他们想要讨论的内容。这种议程设置为选民和政治家营造了一种现实，影响着人们的思考方式、行为方式和投票方式。例如，即使犯罪率正在下降，习惯于阅读有关袭击和其他犯罪报道的公民仍然认为犯罪是一个问题。 140 研究还发现，媒体对种族的描述存在缺陷，尤其是在报道犯罪和贫困问题时。一项研究表明，地方新闻节目更有可能展示非裔美国人罪犯的照片，因此他们过度渲染了黑人作为犯罪者、白人作为受害者的形象。 141 另一项研究发现了类似的模式，即拉丁裔作为犯罪受害者和警察的比例偏低，而白人作为受害者和警察的比例偏高。 142 因此，选民更有可能假设大多数罪犯是非裔美国人，大多数受害者和警察是白人，即使数据并不支持这些假设。

Network news similarly misrepresents the victims of poverty by using more images of African Americans than White people in its segments. Viewers in a study were left believing African Americans were the majority of the unemployed and poor, rather than seeing the problem as one faced by many races.143 The misrepresentation of race is not limited to news coverage, however. A study of images printed in national magazines, like Time and Newsweek, found they also misrepresented race and poverty. The magazines were more likely to show images of young African Americans when discussing poverty and excluded the elderly and the young, as well as White and Latino people, which is the true picture of poverty.144
同样，电视新闻也存在类似的问题，即在新闻报道中使用非裔美国人的形象远多于白人，从而歪曲了贫困受害者的形象。一项研究表明，观众因此误以为非裔美国人是失业和贫困人口的主体，而不是意识到这个问题是许多种族共同面临的。 143 然而，这种对种族的歪曲并非仅限于新闻报道。一项针对 《时代》周刊和 《新闻周刊》 等全国性杂志刊登的图片的研究发现，这些杂志也歪曲了种族和贫困的形象。这些杂志在讨论贫困问题时，更倾向于展示年轻的非裔美国人的形象，而忽略了老年人、年轻人以及白人和拉丁裔，这才是贫困的真实写照。 144

Racial framing, even if unintentional, affects perceptions and policies. If viewers are continually presented with images of African Americans as criminals, there is an increased chance they will perceive members of this group as violent or aggressive.145 The perception that most recipients of welfare are working-age African Americans may have led some citizens to vote for candidates who promised to reduce welfare benefits.146 When survey respondents were shown a story of a White unemployed individual, 71 percent listed unemployment as one of the top three problems facing the United States, while only 53 percent did so if the story was about an unemployed African American.147
种族框架 ，即使是无意的，也会影响人们的认知和政策。如果观众不断看到非裔美国人被描绘成罪犯的形象，他们就更有可能将该群体成员视为暴力或好斗的群体。 145 人们普遍认为大多数福利领取者是处于工作年龄的非裔美国人，这可能导致一些公民投票支持那些承诺削减福利的候选人。 146 当调查对象看到一个白人失业者的故事时，71%的人将失业列为美国面临的三大问题之一；而如果故事的主角是失业的非裔美国人，则只有 53%的人这样认为。 147

Word choice may also have a priming effect. News organizations like the Los Angeles Times and the Associated Press no longer use the phrase “illegal immigrant” to describe undocumented residents. This may be due to the desire to create a “sympathetic” frame for the immigration situation rather than a “threat” frame.148
用词选择也可能产生启动效应。 《洛杉矶时报》 和美联社等新闻机构不再使用“非法移民”一词来描述无证居民。这可能是因为他们希望营造一种“同情”而非“威胁”的移民氛围 。148

Media coverage of women has been similarly biased. Most journalists in the early 1900s were men, and women’s issues were not part of the newsroom discussion. As journalist Kay Mills put it, the women’s movement of the 1960s and 1970s was about raising awareness of the problems of equality, but writing about rallies “was like trying to nail Jell-O to the wall.”149 Most politicians, business leaders, and other authority figures were men, and editors’ reactions to the stories were lukewarm. The lack of women in the newsroom, politics, and corporate leadership encouraged silence.150
媒体对女性的报道也同样存在偏见。20 世纪初，大多数记者都是男性，女性议题并非新闻编辑室讨论的话题。正如记者凯 ·米尔斯所说，20 世纪六七十年代的妇女运动旨在提高人们对平等问题的认识，但报道集会“就像试图把果冻钉在墙上一样难”。 149 大多数政客、商界领袖和其他权威人士都是男性，编辑们对相关报道的反应也十分冷淡。新闻编辑室、政界和企业领导层中女性的匮乏助长了这种沉默。 150

In 1976, journalist Barbara Walters became the first woman coanchor on a network news show, The ABC Evening News. She was met with great hostility from her coanchor Harry Reasoner and received critical coverage from the press.151 On newspaper staffs, women reported having to fight for assignments to well-published beats, or to be assigned areas or topics, such as the economy or politics, that were normally reserved for male journalists. Once women journalists held these assignments, they feared writing about women’s issues. Would it make them appear weak? Would they be taken from their coveted beats?152 This apprehension allowed poor coverage of women and the women’s movement to continue until women were better represented as journalists and as editors. Strength of numbers allowed them to be confident when covering issues like health care, childcare, and education.153
1976 年，记者芭芭拉· 沃尔特斯成为美国广播公司 （ABC）晚间新闻节目的首位女性联合主播。她遭到了搭档哈里·雷森纳的强烈敌意，并受到媒体的批评报道。 151 在报社，女性记者反映，她们不得不争取报道热门领域 ，或者争取被分配到通常由男性记者负责的领域或话题，例如经济或政治。一旦女性记者获得了这些任务，她们又害怕撰写有关女性议题的文章。这会不会显得她们软弱？她们会不会被调离自己梦寐以求的报道领域？ 152 这种担忧导致对女性和女权运动的报道持续匮乏，直到女性在记者和编辑岗位上拥有了更多代表。人数上的优势使她们在报道医疗保健、儿童保育和教育等议题时充满信心。 153

Link to Learning  学习链接
The Center for American Women in Politics researches the treatment women receive from both government and the media, and they share the data with the public.

[.my2]
美国女性政治中心研究女性在政府和媒体中受到的待遇，并将数据与公众分享。

The media’s historically uneven coverage of women continues in its treatment of women candidates. Early coverage was sparse. The stories that did appear often discussed the candidate’s viability, or ability to win, rather than her stand on the issues.154 Women were seen as a novelty rather than as serious contenders who needed to be vetted and discussed. Modern media coverage has changed slightly. One study found that women candidates receive more favorable coverage than in prior generations, especially if they are incumbents.155 Yet a different study found that while there was increased coverage for woman candidates, it was often negative.156 And it did not include Latina candidates.157 Without coverage, they are less likely to win.

[.my2]
媒体对女性报道历来不均衡，在对待女性候选人方面依然如此。早期的报道寥寥无几。仅有的报道往往讨论的是候选人的胜算或获胜能力，而非其在各项议题上的立场。 154 女性被视为新鲜事物，而非需要认真审查和讨论的严肃竞争者。现代媒体报道略有变化。一项研究发现，女性候选人获得的报道比以往几代人更积极，尤其是现任候选人。 155 然而，另一项研究发现，尽管对女性候选人的报道有所增加，但往往是负面的。 156 而且，该研究并未涵盖拉丁裔候选人。 157 缺乏报道，她们的胜选几率就更低。

The historically negative media coverage of woman candidates has had another concrete effect: Women are less likely than men to run for office. One common reason is the effect negative media coverage has on families.158 Many women do not wish to expose their children or spouses to criticism.159 In 2008, the nomination of Sarah Palin as Republican candidate John McCain’s running mate validated this concern (Figure 8.19). Some articles focused on her qualifications to be a potential future president or her record on the issues. But others questioned whether she had the right to run for office, given she had young children, one of whom has developmental disabilities.160 Even when candidates ask that children and families be off-limits, the press rarely honors the requests. So women with young children may wait until their children are grown before running for office, if they choose to run at all.

[.my2]
历史上媒体对女性候选人的负面报道产生了另一个切实的影响：女性参选的可能性低于男性。一个常见的原因是负面媒体报道对家庭的影响。 158 许多女性不希望自己的孩子或配偶受到批评。 159 2008 年，共和党候选人约翰·麦凯恩提名萨拉· 佩林作为竞选搭档，印证了这种担忧（ 图 8.19 ）。一些文章关注她作为未来总统候选人的资格或她在各项议题上的记录。但另一些文章则质疑她是否有资格参选，因为她有年幼的孩子，其中一个孩子患有发育障碍。 160 即使候选人要求媒体不要报道孩子和家庭，媒体也很少会遵守这一要求。因此，有年幼子女的女性可能会等到孩子长大后再参选，甚至可能根本不会参选。

In 2020, woman candidates, though still facing negative media coverage, nevertheless ran in record numbers at all levels. Several women were competitive for the Democratic presidential nomination, including Senator Elizabeth Warren (D-MA), Senator Kamala Harris (D-CA), and Senator Amy Klobuchar (D-MN). Harris was later selected by Joe Biden as his running mate and now serves as the first woman vice president.

[.my2]
2020年，尽管女性候选人仍然面临负面媒体报道，但她们在各级选举中的参选人数都创下了纪录。多位女性角逐民主党总统候选人提名，其中包括马萨诸塞州参议员伊丽莎白·沃伦、加利福尼亚州参议员卡马拉·哈里斯和明尼苏达州参议员艾米·克洛布查尔。哈里斯后来被乔·拜登选为竞选搭档，如今已成为美国历史上首位女性副总统。

An image of Sarah Palin on a stage with John McCain and several other people.

[.my2]
Figure 8.19 When Sarah Palin found herself on the national stage at the Republican Convention in September 2008, media coverage about her selection as John McCain’s running mate included numerous questions about her ability to serve based on personal family history. Attacks on candidates’ families lead many women to postpone or avoid running for office. (credit: Carol Highsmith)
图 8.19 2008 年 9 月，莎拉·佩林在共和党全国代表大会上亮相，媒体对她被选为约翰·麦凯恩的竞选搭档的报道中，充斥着许多关于她能否胜任公职的质疑，这些质疑往往基于她的个人家庭背景。对候选人家庭的攻击导致许多女性推迟或放弃参选。（图片来源：卡罗尔·海史密斯）

'''