
= 009 Political Parties 政党
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


In 2012, Barack Obama accepted his second nomination to lead the Democratic Party into the presidential election (Figure 9.1). During his first term, he had been attacked by pundits for his failure to convince congressional Republicans to work with him. Despite that, he was wildly popular in his own party, and voters reelected him by a comfortable margin. His second term seemed to go no better, however, with disagreements between the parties resulting in government shutdowns and the threat of credit defaults. Yet just a few decades ago, then-president Dwight D. Eisenhower was criticized for failing to create a clear vision for his Republican Party, and Congress was lampooned for what was deemed a lack of real conflict over important issues. Political parties, it seems, can never get it right—they are either too polarizing or too noncommittal.

[.my2]
2012 年，巴拉克·奥巴马接受了第二次民主党总统候选人提名（ 图 9.1 ）。在他的第一个任期内，他因未能说服国会共和党人与他合作而受到评论员的抨击。尽管如此，他在党内仍然拥有极高的支持率，并以较大优势连任。然而，他的第二个任期似乎也好不到哪里去，两党之间的分歧导致政府停摆和信贷违约的威胁。然而，就在几十年前，时任总统德怀特·D·艾森豪威尔也因未能为共和党制定清晰的愿景而受到批评，国会也因被认为在重要问题上缺乏真正的冲突而遭到嘲讽。看来，政党似乎永远无法做到尽善尽美——要么过于两极分化，要么过于模棱两可。

While people love to criticize political parties, the reality is that the modern political system could not exist without them. This chapter will explore why the party system may be the most important component of any true democracy. What are political parties? Why do they form, and why has the United States typically had only two? Why have political parties become so highly structured? Finally, why does it seem that parties today are more polarized than they have been in the past?
人们虽然喜欢批评政党，但现实是，没有政党，现代政治体系根本无法存在。本章将探讨政党制度为何可能是任何真正民主制度最重要的组成部分。什么是政党？它们为何形成？为什么美国通常只有两个政党？为什么政党的结构如此高度复杂？最后，为什么如今的政党似乎比以往更加两极分化？




Figure 9.1 The families of the 2012 presidential candidates joined in the festivities at the Democratic National Convention in Charlotte, North Carolina, (left) and the Republican National Convention in Tampa, Florida (right). In 2020, the COVID-19 pandemic prevented both the Democrats and the Republicans from staging traditional nominating conventions. In 2024, both parties again held traditional large conventions. (credit right: modification of work by “PBS NewsHour”/Flickr)

Chapter Outline

- 9.1 What Are Parties and How Did They Form?
- 9.2 The Two-Party System
- 9.3 The Shape of Modern Political Parties
- 9.4 Divided Government and Partisan Polarization

In 2012, Barack Obama accepted his second nomination to lead the Democratic Party into the presidential election (Figure 9.1). During his first term, he had been attacked by pundits for his failure to convince congressional Republicans to work with him. Despite that, he was wildly popular in his own party, and voters reelected him by a comfortable margin. His second term seemed to go no better, however, with disagreements between the parties resulting in government shutdowns and the threat of credit defaults. Yet just a few decades ago, then-president Dwight D. Eisenhower was criticized for failing to create a clear vision for his Republican Party, and Congress was lampooned for what was deemed a lack of real conflict over important issues. Political parties, it seems, can never get it right—they are either too polarizing or too noncommittal.

While people love to criticize political parties, the reality is that the modern political system could not exist without them. This chapter will explore why the party system may be the most important component of any true democracy. What are political parties? Why do they form, and why has the United States typically had only two? Why have political parties become so highly structured? Finally, why does it seem that parties today are more polarized than they have been in the past?

'''