
= 009-4 Divided Government and Partisan Polarization 分裂的政府和党派极化
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




In 1950, the American Political Science Association’s Committee on Political Parties (APSA) published an article offering a criticism of the current party system. The parties, it argued, were too similar. Distinct, cohesive political parties were critical for any well-functioning democracy. First, distinct parties offer voters clear policy choices at election time. Second, cohesive parties could deliver on their agenda, even under conditions of lower bipartisanship. The party that lost the election was also important to democracy because it served as the “loyal opposition” that could keep a check on the excesses of the party in power. Finally, the paper suggested that voters could signal whether they preferred the vision of the current leadership or of the opposition. This signaling would keep both parties accountable to the people and lead to a more effective government, better capable of meeting the country’s needs.

[.my2]
1950 年，美国政治学会政党委员会（APSA）发表了一篇文章，对当时的政党制度提出了批评。文章认为，各政党过于相似。对于任何运转良好的民主制度而言，鲜明且团结的政党都至关重要。首先，鲜明的政党能够在选举时为选民提供清晰的政策选择。其次，团结的政党即使在两党合作程度较低的情况下也能有效落实其施政纲领。此外，败选的政党对民主制度也至关重要，因为它可以作为“ 忠诚的反对党 ”，对执政党的过度行为进行制衡。最后，文章建议选民可以通过投票来表明他们更倾向于现任领导层还是反对党的理念。这种信号传递能够确保两党对人民负责，从而建立一个更高效的政府，更好地满足国家的需求。

But, the APSA article continued, U.S. political parties of the day were lacking in this regard. Rarely did they offer clear and distinct visions of the country’s future, and, on the rare occasions they did, they were typically unable to enact major reforms once elected. Indeed, there was so much overlap between the parties when in office that it was difficult for voters to know whom they should hold accountable for bad results. The article concluded by advocating a set of reforms that, if implemented, would lead to more distinct parties and better government. While this description of the major parties as being too similar may have been accurate in the 1950s; that is no longer the case.53
但 APSA 的文章继续指出，当时的美国政党在这方面有所欠缺。它们很少能提出清晰明确的国家未来愿景，即便偶尔提出，一旦当选，也往往无力推行重大改革。事实上，各政党执政期间的重叠之处如此之多，以至于选民很难知道应该追究谁的责任。文章最后提出了一系列改革措施，认为如果这些措施得以实施，将有助于形成更加鲜明的政党，并建立更好的政府。虽然这种将主要政党描述得过于相似的论断在 20 世纪 50 年代或许是准确的，但如今情况已大不相同 。53

THE PROBLEM OF DIVIDED GOVERNMENT
分裂政府的问题
The problem of majority versus minority politics is particularly acute under conditions of divided government. Divided government occurs when one or more houses of the legislature are controlled by the party in opposition to the executive. Unified government occurs when the same party controls the executive and the legislature entirely. Divided government can pose considerable difficulties for both the operations of the party and the government as a whole. It makes fulfilling campaign promises extremely difficult, for instance, since the cooperation (or at least the agreement) of both Congress and the president is typically needed to pass legislation. Furthermore, one party can hardly claim credit for success when the other side has been a credible partner, or when nothing can be accomplished. Party loyalty may be challenged too, because individual politicians might be forced to oppose their own party agenda if it will help their personal reelection bids.

[.my2]
在两党分治的情况下，多数派政治与少数派政治的冲突尤为突出。当立法机构的一个或多个议院分别由与行政部门对立的政党控制时，就会出现两党分治。而当同一政党完全控制行政部门和立法机构时，则形成统一政府。两党分治会给政党运作和整个政府带来相当大的困难。例如，由于立法通常需要国会和总统的合作（或至少是双方的同意），因此兑现竞选承诺变得极其困难。此外，如果另一方是可靠的合作伙伴，或者根本无法取得任何成果，那么一方就很难将功劳揽在自己身上。政党忠诚度也可能受到挑战，因为如果反对本党的议程有助于个人连任，个别政治人物可能会被迫这样做。

Divided government can also be a threat to government operations, although its full impact remains unclear.54 For example, when the divide between the parties is too great, government may shut down. A 1976 dispute between Republican president Gerald Ford and a Democrat-controlled Congress over the issue of funding for certain cabinet departments led to a ten-day shutdown of the government (although the federal government did not cease to function entirely). But beginning in the 1980s, the interpretation that Republican president Ronald Reagan’s attorney general gave to a nineteenth-century law required a complete shutdown of federal government operations until a funding issue was resolved (Figure 9.13).55
分裂的政府也可能对政府运作构成威胁，尽管其全部影响尚不明确。 54 例如，当两党之间的分歧过大时，政府可能会停摆。1976 年，共和党总统杰拉尔德·福特与民主党控制的国会就某些内阁部门的拨款问题发生争执，导致政府停摆十天（尽管联邦政府并未完全停止运作）。但从 20 世纪 80 年代开始，共和党总统罗纳德·里根的司法部长对一项 19 世纪法律的解读要求联邦政府完全停止运作，直到拨款问题得到解决（ 图 9.13 ）。 55

Clearly, the parties’ willingness to work together and compromise can be a very good thing. However, the past several decades have brought an increased prevalence of divided government. Since 1969, the U.S. electorate has sent the president a Congress of his own party in only seven of twenty-three congressional elections, and during George W. Bush’s first administration, the Republican majority was so narrow that a combination of resignations and defections gave the Democrats control before the next election could be held.

[.my2]
显然，各党派愿意合作和妥协是一件好事。然而，过去几十年间，分裂政府的现象日益普遍。自 1969 年以来，美国选民在 23 次国会选举中仅有 7 次让总统拥有了由本党控制的国会。在乔治·W·布什的第一任期内，共和党的多数席位微弱，以至于在下次选举举行之前，由于一些议员辞职或倒戈，民主党就获得了控制权。

Over the short term, however, divided government can make for very contentious politics. A well-functioning government usually requires a certain level of responsiveness on the part of both the executive and the legislative branches. This responsiveness is hard enough if government is unified under one party. During the presidency of Democrat Jimmy Carter (1977–1980), despite the fact that both houses of Congress were controlled by Democratic majorities, the government was shut down on five occasions because of conflict between the executive and legislative branches.56 Shutdowns are even more likely when the president and at least one house of Congress are of opposite parties. During the presidency of Ronald Reagan, for example, the federal government shut down eight times; on seven of those occasions, the shutdown was caused by disagreements between Reagan and the Republican-controlled Senate on the one hand and the Democrats in the House on the other, over such issues as spending cuts, abortion rights, and civil rights.57 More such disputes and government shutdowns took place during the administrations of George H. W. Bush, Bill Clinton, and Barack Obama, when different parties controlled Congress and the presidency. The most recent government shutdown, the longest in U.S. history, began in December 2018 under the 115th Congress, when the presidency and both houses were controlled by Republican majorities, but continued into the 116th, which features a Democratically controlled House and a Republican Senate.

[.my2]
然而，短期内，分裂的政府会导致政治纷争不断。一个运转良好的政府通常需要行政和立法部门都具备一定的响应能力。如果政府由同一政党统一执政，这种响应能力就很难保证。在民主党总统吉米·卡特（1977-1980）执政期间，尽管国会两院均由民主党控制，但由于行政和立法部门之间的冲突，政府仍然停摆了五次 。当总统与国会至少一院分属不同党派时，政府停摆的可能性更大。例如，在罗纳德·里根总统执政期间，联邦政府停摆了八次；其中七次是由于里根与共和党控制的参议院和民主党控制的众议院在诸如削减开支、堕胎权和民权等问题上存在分歧造成的。在老布什、克林顿和奥巴马执政期间，还发生了 57 起类似的争端和政府停摆事件，当时国会和总统职位分别由不同的政党掌控。最近一次政府停摆是美国历史上持续时间最长的一次，始于 2018 年 12 月，当时正值第 115 届国会，总统职位和参众两院均由共和党控制，但停摆一直持续到第 116 届国会，该届国会由民主党控制众议院，共和党控制参议院。

For the first few decades of the current pattern of divided government, the threat it posed to the government appears to have been muted by a high degree of bipartisanship, or cooperation through compromise. Many pieces of legislation were passed in the 1960s and 1970s with reasonably high levels of support from both parties. Most members of Congress had relatively moderate voting records, with regional differences within parties that made bipartisanship on many issues more likely.

[.my2]
在当前这种两党分治的政府格局形成后的最初几十年里， 两党高度合作（或通过妥协进行合作）似乎削弱了这种格局对政府构成的威胁。20 世纪 60 年代和 70 年代，许多法案都得到了两党相当高的支持率。大多数国会议员的投票记录相对温和，而党内存在的地域差异也使得两党在许多问题上达成共识的可能性更大。

An image of Ronald Reagan shaking hands with Tip O’Neil.

[.my2]
Figure 9.13 In the early 1980s, Republican president Ronald Reagan (left) and Democratic Speaker of the House Tip O’Neil (right) worked together to pass key pieces of legislation, even though they opposed each other on several issues. (credit: Ronald Reagan Presidential Library & Museum)
图 9.13 20 世纪 80 年代初，共和党总统罗纳德·里根（左）和民主党众议院议长蒂普·奥尼尔（右）携手合作，通过了多项关键法案，尽管他们在一些问题上立场相左。（图片来源：罗纳德·里根总统图书馆暨博物馆）
For example, until the 1980s, northern and midwestern Republicans were often fairly progressive, supporting racial equality, workers’ rights, and farm subsidies. Southern Democrats were frequently quite socially and racially conservative and were strong supporters of states’ rights. Cross-party cooperation on these issues was fairly frequent. But in the past few decades, the number of moderates in both houses of Congress has declined. This has made it more difficult for party leadership to work together on a range of important issues, and for members of the minority party in Congress to find policy agreement with an opposing party president.

[.my2]
例如，直到20世纪80年代，北方和中西部地区的共和党人通常都比较进步，支持种族平等、工人权益和农业补贴。南方民主党人在社会和种族问题上往往相当保守，并且是州权的坚定支持者。两党在这些问题上的合作相当普遍。但在过去几十年里，国会两院的温和派人数有所减少。这使得两党领导层在诸多重要问题上更难合作，也使得国会少数党成员更难与反对党总统达成政策共识。

However, beginning in the 1990s, the parties began to diverge and moderates began to disappear in Congress. The era of bipartisanship seems to have ended as the parties now compete bitterly with one another and cross-party socialization or international trips across party lines no longer happen. While this trend tends to be evaluated negatively, there are benefits. Firstly, there are now very distinct choices for the voters. Secondly, the existence of competitive parties and competitive elections is a good sign that democracy is thriving. We may not really want to have one party with a monopoly on political discourse and policymaking, as exists in some U.S. states.

[.my2]
然而，从20世纪90年代开始，各党派开始分化，温和派在国会逐渐消失。两党合作的时代似乎已经结束，如今各党派之间竞争激烈，跨党派的社交活动或跨党派的国际访问也已不复存在。尽管这种趋势往往被负面评价，但它也有其益处。首先，选民现在有了非常明确的选择。其次，竞争性政党和竞争性选举的存在，是民主蓬勃发展的良好标志。我们或许并不希望出现像美国某些州那样，由一个政党垄断政治话语权和政策制定权的情况。

THE IMPLICATIONS OF POLARIZATION
极化的影响
The past thirty years have brought a dramatic change in the relationship between the two parties as fewer conservative Democrats and liberal Republicans have been elected to office. As political moderates, or individuals with ideologies in the middle of the ideological spectrum, leave the political parties at all levels, the parties have grown farther apart ideologically, a result called party polarization. In other words, at least organizationally and in government, Republicans and Democrats have become increasingly dissimilar from one another (Figure 9.14). In the party-in-government, this means fewer members of Congress have mixed voting records; instead they vote far more consistently on issues and are far more likely to side with their party leadership.58 It also means a growing number of moderate voters aren’t participating in party politics. Either they are becoming independents, or they are participating only in the general election and are therefore not helping select party candidates in primaries.

[.my2]
过去三十年间，两党关系发生了巨大变化，保守派民主党人和自由派共和党人当选的人数均有所减少。随着政治温和派 ，即意识形态处于中间位置的人士，在各级政党中纷纷退出，两党在意识形态上的分歧日益加深，这种现象被称为政党极化 。换言之，至少在组织和执政层面，共和党和民主党之间的差异越来越大（ 图 9.14 ）。在执政党层面，这意味着国会议员的投票记录更加多元化；相反，他们在各项议题上的投票立场更加一致，也更倾向于支持本党领导层。 58 这也意味着越来越多的温和派选民不再参与党派政治。他们要么成为独立选民，要么只参加大选，因此无法在党内初选中帮助选出候选人。

A series of six graphs titled “Polarization of the U.S. Congress”. The x-axis of each graph is labeled “most liberal -1” on the left and “most conservative +1” on the right, and divided vertically by a line in the center labeled “0”. The y-axis of each graph starts at 0 and ends at 85. The first three graphs are labeled “Senate” and arranged horizontally. The left-most graph is titled “93rd Congress, 1973-74” and shows a majority of democratic senators around “.4” and a majority of republican senators around “.3” on the x-axis. A few democrats are shown at “0”, “.1”, and “.2”, and a few republicans are shown at “0”, “-.1”, “-.2”, and “-.3”. The middle graph is titled “103rd Congress, 1992-94” and shows a majority of democrats around “-.2”, and a majority of republicans around “.3”. A few democrats are shown at “0” and “.1”, and a few republicans are shown at “0”, and “-.1”. The right-most graph is titled “112th Congress, 2011-12” and shows a majority of democrats around “-.3”, and a majority of republicans around “.4”. There is no overlap across the line labeled “0”. The second three graphs are labeled “House” and arranged horizontally. The left-most graph is titled “93rd Congress, 1973-74” and shows a majority of democratic senators around “.4” and a majority of republican senators around “.3” on the x-axis. A few democrats are shown at “0”, “.1”, and “.2”, and a few republicans are shown at “0”, “-.1”, and “-.2”. The middle graph is titled “103rd Congress, 1992-94” and shows a majority of democrats around “-.35”, and a majority of republicans around “.4”. A few democrats are shown at “0” and “.1”, and a few republicans are shown at “0”, and “-.1”. The right-most graph is titled “112th Congress, 2011-12” and shows a majority of democrats around “-.4”, and a majority of republicans around “.7”. There is no overlap across the line labeled “0”. A source at the bottom of the graphs reads: “Pew Research Center. Chart sources: Royce Carroll, Jeff Lewis, James Lo, Nolan McCarty, Keith Poole and Howard Rosenthal, voteview.com. June 12, 2014.”.

[.my2]
Figure 9.14 The number of moderates has plummeted since 1973 as the median of both parties has moved further away from the political center. These data points suggest that the Republicans have moved more clearly from the center than have Democrats. This trend has continued since 2014, with Democrats following the Republican trend with fewer centrists but with Republicans turning sharper right than Democrats turning left.59
图 9.14 显示，自 1973 年以来，温和派人数急剧下降，两党的中间立场都进一步偏离了政治中心。这些数据表明，共和党比民主党更明显地偏离了中心。自 2014 年以来，这一趋势仍在继续，民主党也步共和党后尘，中间派人数减少，但共和党向右倾斜的幅度比民主党向左倾斜的幅度更大。 59
What is most interesting about this shift to increasingly polarized parties is that it does not appear to have happened as a result of the structural reforms recommended by APSA. Rather, it has happened because moderate politicians have simply found it harder and harder to win elections. There are many conflicting theories about the causes of polarization, some of which we discuss below. But whatever its origin, party polarization in the United States does not appear to have had the net positive effects that the APSA committee was hoping for. With the exception of providing voters with more distinct choices, positives of polarization are hard to find. The negative impacts are many. For one thing, rather than reducing intraparty conflict, polarization appears to have only amplified it. For example, the Republican Party (or the GOP, standing for Grand Old Party) has historically been a coalition of two key and overlapping factions: pro-business rightists and social conservatives. The GOP has held the coalition of these two groups together by opposing programs designed to redistribute wealth (and advocating small government) while at the same time arguing for laws preferred by conservative Christians. But it was also willing to compromise with pro-business Democrats, often at the expense of social issues, if it meant protecting long-term business interests.

[.my2]
最引人注目的是，这种政党日益两极分化的趋势似乎并非美国政治学会（APSA）建议的结构性改革所致，而是因为温和派政治家越来越难以赢得选举。关于两极分化的原因，存在许多相互矛盾的理论，我们将在下文讨论其中一些。但无论其根源如何，美国的政党两极分化似乎并未产生 APSA 委员会所期望的净积极影响。除了为选民提供更多不同的选择之外，两极分化的积极作用几乎难以寻觅，而负面影响却不胜枚举。首先，两极分化非但没有减少党内冲突，反而加剧了冲突。例如，共和党（或简称 GOP，即“老牌政党”）历来是由两个关键且相互重叠的派系组成的联盟：亲商的右翼分子和社会保守派。共和党通过反对旨在重新分配财富的方案（并倡导小政府），同时支持保守基督教徒所青睐的法律，从而维系了这两个群体的联盟。但如果能够保护企业的长期利益，共和党也愿意与亲商的民主党人妥协，即便这意味着牺牲社会议题。

Recently, however, a new voice emerged that allied itself with the Republican Party. Born in part from an older third-party movement known as the Libertarian Party, the Tea Party was more hostile to government and viewed government intervention in all forms, especially taxation and the regulation of business, as a threat to capitalism and democracy. It was less willing to tolerate interventions in the market place, even when they were designed to protect the markets themselves. Although an anti-tax faction within the Republican Party has existed for some time, some factions of the Tea Party movement were also active at the intersection of religious liberty and social issues, especially in opposing such initiatives as same-sex marriage and abortion rights.60 The Tea Party argued that government, both directly and by neglect, was threatening the ability of evangelicals to observe their moral obligations, including practices some perceive as endorsing social exclusion.

[.my2]
然而，最近出现了一种与共和党结盟的新声音。 茶党部分源于一个名为自由党的更早的第三党运动，它对政府更为敌视，认为政府的一切干预，尤其是税收和商业监管，都是对资本主义和民主的威胁。它更不愿意容忍对市场的干预，即便这些干预旨在保护市场本身。尽管共和党内部的反税派系由来已久，但茶党运动中的一些派别也活跃于宗教自由和社会议题的交汇点，尤其是在反对同性婚姻和堕胎权等倡议方面。 茶党认为，政府无论是直接干预还是疏忽，都在威胁福音派信徒履行其道德义务的能力，包括一些人认为支持社会排斥的做法。

Although the Tea Party was a movement and not a political party, 86 percent of Tea Party members who voted in 2012 cast their votes for Republicans.61 Some members of the Republican Party were closely affiliated with the movement, and before the 2012 elections, Tea Party activist Grover Norquist exacted promises from many Republicans in Congress that they would oppose any bill that sought to raise taxes.62 The inflexibility of Tea Party members led to tense floor debates and was ultimately responsible for the 2014 primary defeat of Republican majority leader Eric Cantor and the 2015 resignation of the sitting Speaker of the House John Boehner. In 2015, Chris Christie, John Kasich, Ben Carson, Marco Rubio, and Ted Cruz, all of whom were Republican presidential candidates, signed Norquist’s pledge as well (Figure 9.15).

[.my2]
尽管茶党是一场运动而非政党，但在 2012 年的选举中，86%的茶党成员投票支持共和党。 61 一些共和党成员与茶党运动关系密切，在 2012 年大选前，茶党积极分子格罗弗·诺奎斯特(Grover Norquist)迫使国会中的许多共和党人承诺反对任何旨在增税的法案。 62 茶党成员的强硬立场导致了激烈的议会辩论，并最终导致共和党多数党领袖埃里克·坎托(Eric Cantor)在 2014 年党内初选中落败，以及时任众议院议长约翰·博纳(John Boehner)在 2015 年辞职。2015 年，克里斯·克里斯蒂(Chris Christie)、约翰·卡西奇(John Kasich)、本·卡森(Ben Carson)、马可·卢比奥(Marco Rubio)和特德·克鲁兹(Ted Cruz)——他们都是共和党总统候选人——也签署了诺奎斯特的承诺书（ 图 9.15 ）。

Image A is of Ted Cruz. Image B is of John Kasich.

[.my2]
Figure 9.15 Vying for the Republican nomination, 2016 presidential candidates Ted Cruz (a) and John Kasich (b), like many other Republicans, signed a pledge not to raise taxes if elected.

[.my2]
图 9.15 争夺共和党提名的 2016 年总统候选人特德·克鲁兹 (a) 和约翰·卡西奇 (b) 像许多其他共和党人一样签署了承诺，如果当选，不会提高税收。
Movements on the left have also arisen. The Occupy Wall Street movement was born of the government’s response to the Great Recession of 2008 and its assistance to endangered financial institutions, provided through the Troubled Asset Relief Program, TARP (Figure 9.16). The Occupy Movement believed the recession was caused by a failure of the government to properly regulate the banking industry. The Occupiers further maintained that the government moved swiftly to protect the banking industry from the worst of the recession but largely failed to protect the average person, thereby worsening the growing economic inequality in the United States.

[.my2]
左翼运动也随之兴起。 “占领华尔街” 运动源于政府对 2008 年大衰退的应对措施，以及政府通过问题资产救助计划（TARP）（ 图 9.16 ）向陷入困境的金融机构提供的援助。占领运动认为，经济衰退是由于政府未能有效监管银行业造成的。占领者们还指出，政府迅速采取行动保护银行业免受衰退最严重冲击，但却未能有效保护普通民众，从而加剧了美国日益严重的经济不平等。

While the Occupy Movement itself has largely fizzled, the anti-business sentiment to which it gave voice continues within the Democratic Party, and many Democrats have proclaimed their support for the movement and its ideals, if not for its tactics.63 Champions of the left wing of the Democratic Party, however, such as former presidential candidate Senator Bernie Sanders and Massachusetts senator Elizabeth Warren, have ensured that the Occupy Movement’s calls for more social spending and higher taxes on the wealthy remain a prominent part of the national debate. Their popularity, and the growing visibility of race issues in the United States, have helped sustain the left wing of the Democratic Party. Bernie Sanders’ 2016 presidential run made these topics and causes even more salient, especially among younger voters. Several incidents since that time, most notably the murder of George Floyd on May 25, 2020, have caused the Black Lives Matter movement, which began in 2013 after the acquittal of George Zimmerman in the shooting death of Trayvon Martin in April 2012, to expand. Black Lives Matter protests took place in record numbers in 2020.64
尽管“占领运动”本身已基本消退，但它所表达的反商业情绪在民主党内部依然存在，许多民主党人公开表示支持该运动及其理念，即便他们并不认同其策略。然而，像前总统候选人、参议员伯尼·桑德斯和马萨诸塞州参议员伊丽莎白·沃伦这样的民主党左翼领袖，确保了“占领运动”提出的增加社会支出和提高富人税收的诉求仍然是全国辩论的重要组成部分。他们的支持，以及美国种族问题日益凸显，都有助于民主党左翼的持续发展。伯尼·桑德斯 2016 年的总统竞选使这些议题和诉求更加引人注目，尤其是在年轻选民中。此后发生的几起事件，尤其是 2020 年 5 月 25 日乔治·弗洛伊德被杀事件，促使“黑人的命也是命”（Black Lives Matter）运动不断发展壮大。该运动始于 2013 年，起因是乔治·齐默曼因 2012 年 4 月枪杀特雷冯·马丁而被判无罪。 2020 年，“黑人的命也是命”抗议活动规模创下历史新高。

Photo A shows a street from ground level with large yellow letters painted; a “B” is visible. Photo B shows an aerial view of a street painted with the phrase “Black Lives Matter.”
Figure   数字 9.16 In the wake of the George Floyd murder in Minneapolis, Black Lives Matter (BLM) protests occurred all across the country. While there was widespread support initially for the movement from both major parties, Republican opinion of BLM subsequently became more critical, while Democrats continued to embrace the movement. The partisan divide came to a head outside the White House in Washington, DC, where massive BLM protests occurred, which were aggressively criticized by the Trump administration, and cleared with tear gas and other riot control tactics. Democratic mayor Muriel Bowser subsequently authorized the DC Public Works department to paint these massive block letters (a) on 16th Street across Lafayette Park from the White House (b). (credit a: modification of ""Black Lives Matter Plaza" by John Brighenti/Flickr, CC BY; credit b: modification of "In Space, We Can Hear Your Screams" by Steve Jurvetson/Wikimedia Commons, CC BY)
在明尼阿波利斯市乔治·弗洛伊德遇害后，“黑人的命也是命”（Black Lives Matter，简称 BLM）抗议活动席卷全美。尽管最初两大党都对该运动给予了广泛支持，但共和党人随后对 BLM 的态度变得更加批判，而民主党人则继续支持该运动。党派分歧在华盛顿特区的白宫外达到了顶峰，大规模的 BLM 抗议活动爆发，遭到特朗普政府的强烈批评，并被催泪瓦斯和其他防暴手段驱散。随后，民主党籍市长穆里尔·鲍泽授权华盛顿特区公共工程部门在白宫（b）对面的拉斐特公园旁的第 16 街上喷涂了这些巨大的字母（a）。（图片 a：改编自 John Brighenti/Flickr 的“Black Lives Matter Plaza”，CC BY；图片 b：改编自 Steve Jurvetson/Wikimedia Commons 的“In Space, We Can Hear Your Screams”，CC BY）
Unfortunately, party factions haven’t been the only result of party polarization. By most measures, the U.S. government in general and Congress in particular have become less effective in recent years. Congress has passed fewer pieces of legislation, confirmed fewer appointees, and been less effective at handling the national purse than in recent memory. If we define effectiveness as legislative productivity, the 106th Congress (1999–2000) passed 463 pieces of substantive legislation (not including commemorative legislation, such as bills proclaiming an official doughnut of the United States). The 107th Congress (2000–2001) passed 294 such pieces of legislation. By 2013–2014, the total had fallen to 212.65
不幸的是，党派分裂并非党派极化的唯一后果。从大多数指标来看，近年来美国政府整体效率，尤其是国会效率，有所下降。国会通过的法案数量减少，任命官员人数减少，在管理国家财政方面也比以往更加低效。如果我们以立法效率来衡量效率，那么第 106 届国会（1999-2000 年）通过了 463 项实质性法案（不包括纪念性法案，例如宣布美国官方甜甜圈的法案）。第 107 届国会（2000-2001 年）通过了 294 项此类法案。到 2013-2014 年，总数已降至 212 项。

Perhaps the clearest sign of Congress’ ineffectiveness is that the threat of government shutdown has become a constant. Shutdowns occur when Congress and the president are unable to authorize and appropriate funds before the current budget runs out. This is now an annual problem. Relations between the two parties became so bad that financial markets were sent into turmoil in 2014 when Congress failed to increase the government’s line of credit before a key deadline, thus threatening a U.S. government default on its loans. While any particular trend can be the result of multiple factors, the decline of key measures of institutional confidence and trust suggest the negative impact of polarization. Public approval ratings for Congress have been low for decades, typically lower than presidential approval. Congressional approval dipped to single digits in November 2013. Levels early in 2021 were in the mid-30s. However, even then, disapproval was at greater than 60 percent.66 In the wake of the Great Recession, President Obama’s average approval rating remained low for several years, despite an overall trend in economic growth since the end of 2008, before he enjoyed an uptick in support during his final year in office.67 Typically, economic conditions are a significant driver of presidential approval, suggesting the negative effect of partisanship on presidential approval.

[.my2]
国会效率低下的最明显标志或许就是政府停摆的威胁已成为常态。当国会和总统无法在当前预算耗尽前授权和拨款时，就会发生政府停摆。这如今已成为一个年年都会出现的问题。两党关系恶化到如此地步，以至于 2014 年，由于国会未能按时增加政府信贷额度，美国政府面临违约风险，金融市场陷入动荡。虽然任何特定趋势都可能是多种因素共同作用的结果，但衡量机构信心和信任度的关键指标的下降表明了政治极化带来的负面影响。几十年来，国会的公众支持率一直很低，通常低于总统的支持率。2013 年 11 月，国会的支持率跌至个位数。2021 年初，支持率徘徊在 30%左右。然而，即便如此，反对率仍然超过 60%。 66 在大衰退之后，尽管自 2008 年底以来经济总体呈增长趋势，奥巴马总统的平均支持率仍连续数年处于低位，直到他任期最后一年支持率才有所回升。67 通常情况下，经济状况是影响总统支持率的重要因素，这表明党派之争对总统支持率有负面影响。

THE CAUSES OF POLARIZATION
极化的原因
Scholars agree that some degree of polarization is occurring in the United States, even if some contend it is only at the elite level. But they are less certain about exactly why, or how, polarization has become such a mainstay of American politics. Several conflicting theories have been offered. The first and perhaps best argument is that polarization is a party-in-government phenomenon driven by a decades-long sorting of the voting public, or a change in party allegiance in response to shifts in party position.68 According to the sorting thesis, before the 1950s, voters were mostly concerned with state-level party positions rather than national party concerns. Since parties are bottom-up institutions, this meant local issues dominated elections; it also meant national-level politicians typically paid more attention to local problems than to national party politics.

[.my2]
学者们一致认为，美国存在一定程度的政治极化 ，尽管有人认为这种极化仅限于精英阶层。但他们对于极化为何以及如何成为美国政治的常态却不太确定。目前已提出几种相互矛盾的理论。第一个或许也是最有力的论点是，极化是一种执政党现象，其驱动力是选民群体数十年来不断分化 ，或是选民因政党立场变化而改变党派忠诚度。 68 根据这种分化理论，在 20 世纪 50 年代之前，选民主要关注的是州级政党立场，而非国家级政党事务。由于政党是自下而上的机构，这意味着地方议题主导了选举；这也意味着国家级政治人物通常更关注地方问题，而非国家级政党政治。

But over the past several decades, voters have started identifying more with national-level party politics, and they began to demand their elected representatives become more attentive to national party positions. As a result, they have become more likely to pick parties that consistently represent national ideals, are more consistent in their candidate selection, and are more willing to elect office-holders likely to follow their party’s national agenda. One example of the way social change led to party sorting revolves around race.

[.my2]
但过去几十年里，选民开始更加认同国家层面的政党政治，并要求他们选出的代表更加关注国家政党的立场。因此，他们更倾向于选择那些始终如一地代表国家理念、候选人选择更加一致的政党，也更愿意选举那些可能遵循本党国家议程的官员。社会变革导致政党分化的一个例子就与种族有关。

The Democratic Party returned to national power in the 1930s largely as the result of a coalition among low socio-economic status voters in northern and midwestern cities. These new Democratic voters were religiously and ethnically more diverse than the mostly White, mostly Protestant voters who supported Republicans. But the southern United States (often called the “Solid South”) had been largely dominated by Democratic politicians since the Civil War. These politicians agreed with other Democrats on most issues, but they were more evangelical in their religious beliefs and less tolerant on racial matters. The federal nature of the United States meant that Democrats in other parts of the country were free to seek alliances with minorities in their states. But in the South, African Americans were still largely disenfranchised well after Franklin Roosevelt had brought other groups into the Democratic tent.

[.my2]
20世纪30年代，民主党重掌全国政权，很大程度上归功于北部和中西部城市低收入选民的联盟。这些新加入民主党的选民在宗教和种族上比支持共和党的以白人为主、以新教徒为主的选民更加多元化。但自内战以来，美国南部（通常被称为“铁杆南方”）一直由民主党政客主导。这些政客在大多数问题上与其他民主党人意见一致，但他们的宗教信仰更为虔诚，在种族问题上也更加保守。美国的联邦制意味着其他地区的民主党人可以自由地与本州的少数族裔结盟。但在南方，尽管富兰克林·罗斯福已经将其他群体纳入民主党阵营，非裔美国人仍然在很大程度上被剥夺了选举权。

The Democratic alliance worked relatively well through the 1930s and 1940s when post-Depression politics revolved around supporting farmers and helping the unemployed. But in the late 1950s and early 1960s, social issues became increasingly prominent in national politics. Southern Democrats, who had supported giving the federal government authority for economic redistribution, began to resist calls for those powers to be used to restructure society. Many of these Democrats broke away from the party only to find a home among Republicans, who were willing to help promote smaller national government and greater states’ rights.69 This shift was largely completed with the rise of the evangelical movement in politics, when it shepherded its supporters away from Jimmy Carter, an evangelical Christian, to Ronald Reagan in the 1980 presidential election.

[.my2]
在 20 世纪 30 年代和 40 年代，民主党联盟运作相对良好，当时大萧条后的政治重心是支持农民和帮助失业者。但在 20 世纪 50 年代末和 60 年代初，社会问题在国家政治中日益凸显。南方民主党人原本支持赋予联邦政府经济再分配的权力，但后来开始抵制利用这些权力重组社会的呼声。许多这样的民主党人脱离了民主党，转而加入共和党，因为共和党愿意帮助他们推动缩小联邦政府规模和扩大州权 。69 随着福音派运动在政治领域的崛起，这一转变基本完成。在 1980 年的总统大选中，福音派运动引导其支持者从福音派基督徒吉米·卡特转向罗纳德·里根。

At the same time social issues were turning the Solid South towards the Republican Party, they were having the opposite effect in the North and West. Moderate Republicans, who had been champions of racial equality since the time of Lincoln, worked with Democrats to achieve social reform. These Republicans found it increasing difficult to remain in their party as it began to adjust to the growing power of the small government–states’ rights movement. A good example was Senator Arlen Specter, a moderate Republican who represented Pennsylvania and ultimately switched to become a Democrat before the end of his political career.

[.my2]
与此同时，当社会议题促使南方各州（铁杆共和党州）倒向共和党时，北方和西部却出现了截然相反的趋势。自林肯时代以来就倡导种族平等的温和派共和党人，开始与民主党合作推进社会改革。然而，随着共和党开始调整策略以适应小政府和州权运动日益增长的影响力，这些共和党人发现继续留在党内变得越来越困难。宾夕法尼亚州参议员阿伦·斯佩克特就是一个很好的例子。这位温和派共和党人最终在政治生涯结束前转投民主党。

A second possible culprit in increased polarization is the impact of technology on the public square. Before the 1950s, most people got their news from regional newspapers and local radio stations. While some national programming did exist, most editorial control was in the hands of local publishers and editorial boards. These groups served as a filter of sorts as they tried to meet the demands of local markets.

[.my2]
加剧两极分化的第二个可能原因在于科技对公共领域的影响。20世纪50年代以前，大多数人获取新闻的渠道是地区性报纸和地方广播电台。虽然当时也有一些全国性节目，但大部分编辑控制权都掌握在地方出版商和编辑委员会手中。这些机构在某种程度上起到了过滤作用，因为它们需要满足当地市场的需求。

As described in detail in the media chapter, the advent of television changed that. Television was a powerful tool, with national news and editorial content that provided the same message across the country. All viewers saw the same images of the women’s rights movement and the war in Vietnam. The expansion of news coverage to cable, and the consolidation of local news providers into big corporate conglomerates, amplified this nationalization. Average citizens were just as likely to learn what it meant to be a Republican from a politician in another state as from one in their own, and national news coverage made it much more difficult for politicians to run away from their votes Figure 9.17. The information explosion that followed the heyday of network TV by way of cable, the Internet, and blogs has furthered this nationalization trend.

[.my2]
正如媒体章节中详述的那样，电视的出现改变了这一切。电视是一种强大的工具，其全国性的新闻和社论内容传递着相同的信息。所有观众看到的都是关于妇女权利运动和越南战争的相同画面。新闻报道扩展到有线电视，以及地方新闻机构被大型企业集团收购，进一步强化了这种全国化趋势。普通民众从其他州的政客那里了解共和党人的意义，与从本州政客那里了解共和党人的意义一样容易，而全国性的新闻报道使得政客们更难逃避选民的信任 （图 9.17） 。在电视网鼎盛时期之后，有线电视、互联网和博客带来的信息爆炸进一步推动了这种全国化趋势。

Photo A shows Liz Cheney. Photo B shows Alexandria Ocasio-Cortez.

[.my2]
Figure 9.17 Two examples of congressional representatives who have become polarizing national figures are former Congresswoman and House Majority Leader Liz Cheney (R-WY) (a) and Congresswoman Alexandria Ocasio-Cortez (D-NY) (b). Seemingly cut from a very different mold, with Ocasio-Cortez trying to pull the Democratic Party in Congress to the left, and Cheney the staunch conservative who climbed the party leadership ladder somewhat quietly, both women found themselves on the enemy list of President Donald Trump. AOC took on Trump and his policy positions from the get-go, while Cheney became much more visible with her vote to impeach Trump in the wake of the January 6th insurrection. (credit a: modification of "Liz Cheney official 116th Congress portrait" by US House Office of Photography/Wikimedia Commons, Public Domain; credit b: modification of "Alexandria Ocasio-Cortez Official Portrait" by Franmarie Metzler, U.S. House Office of Photography/Wikimedia Commons, Public Domain)
图 9.17 展示了两位已成为极具争议的全国性人物的国会议员：前众议员、众议院多数党领袖利兹·切尼（共和党，怀俄明州）（a）和众议员亚历山大·奥卡西奥-科尔特斯（民主党，纽约州）（b）。两人看似截然不同，奥卡西奥-科尔特斯试图将国会民主党拉向左翼，而切尼则是一位立场坚定的保守派，她相对低调地攀升至党内领导层。然而，这两位女性都上了唐纳德·特朗普总统的黑名单。奥卡西奥-科尔特斯从一开始就与特朗普及其政策立场针锋相对，而切尼则因在 1 月 6 日国会山骚乱后投票弹劾特朗普而更加引人注目。 （图片 a：修改自美国众议院摄影办公室/维基共享资源发布的“Liz Cheney 第 116 届国会官方肖像”，公共领域；图片 b：修改自 Franmarie Metzler 拍摄的“Alexandria Ocasio-Cortez 官方肖像”，美国众议院摄影办公室/维基共享资源，公共领域）
A final possible cause for polarization is the increasing sophistication of gerrymandering, or the manipulation of legislative districts in an attempt to favor a particular candidate (Figure 9.18). According to the gerrymandering thesis, the more moderate or heterogeneous a voting district, the more moderate the politician’s behavior once in office. Taking extreme or one-sided positions on a large number of issues would be hazardous for a member who needs to build a diverse electoral coalition. But if the district has been drawn to favor a particular group, it now is necessary for the elected official to serve only the portion of the constituency that dominates.

[.my2]
导致政治极化的最后一个可能原因是选区划分（gerrymandering） 手段的日益复杂化，即通过操纵选区划分来偏袒特定候选人（ 图 9.18 ）。根据选区划分理论，选区越是温和或多元化，政治人物上任后​​的行为就越温和。对于需要建立多元化选民联盟的议员而言，在众多议题上采取极端或片面的立场是危险的。但如果选区划分有利于某个特定群体，那么当选官员就只能服务于该群体中占主导地位的那部分选民。

A cartoon that depicts gerrymandering. The outline of several voting districts is shown. The border of the districts is used as the backbone for a large fantastical creature.

[.my2]
Figure 9.18 This cartoon, which inspired the term gerrymander, was printed in the Boston Gazette on March 26, 1812, after the Massachusetts legislature redistricted the state to favor the party of the sitting governor, Elbridge Gerry.

[.my2]
图 9.18 这幅漫画启发了“杰利蝾螈”（gerrymander）一词，它于 1812 年 3 月 26 日刊登在《 波士顿公报》 上，此前马萨诸塞州立法机构重新划分了该州的选区，以利于当时的州长埃尔布里奇·杰利的政党。
Gerrymandering is a centuries-old practice. There has always been an incentive for legislative bodies to draw districts in such a way that sitting legislators have the best chance of keeping their jobs. But changes in law and technology have transformed gerrymandering from a crude art into a science. The first advance came with the introduction of the “one-person-one-vote” principle by the U.S. Supreme Court in 1962. Before then, it was common for many states to practice redistricting, or redrawing of their electoral maps, only if they gained or lost seats in the U.S. House of Representatives. This can happen once every ten years as a result of a constitutionally mandated reapportionment process, in which the number of House seats given to each state is adjusted to account for population changes.

[.my2]
选区划分不公由来已久。立法机构一直以来都有动机去划分选区，以确保现任议员能够最大程度地保住职位。但法律和技术的变革已将选区划分不公从一种粗糙的艺术转变为一门科学。第一个进步是 1962 年美国最高法院引入“一人一票”原则。在此之前，许多州通常只有在众议院席位增减的情况下才会进行选区重划 ，即重新绘制选区地图。根据宪法规定的重新分配程序，每十年会发生一次这种情况，该程序会根据人口变化调整各州在众议院的席位数量。

But if there was no change in the number of seats, there was little incentive to shift district boundaries. After all, if a legislator had won election based on the current map, any change to the map could make losing seats more likely. Even when reapportionment led to new maps, most legislators were more concerned with protecting their own seats than with increasing the number of seats held by their party. As a result, some districts had gone decades without significant adjustment, even as the U.S. population changed from largely rural to largely urban. By the early 1960s, some electoral districts had populations several times greater than those of their more rural neighbors.

[.my2]
但如果席位数量不变，议员们就没有动力去调整选区边界。毕竟，如果一位议员是根据现有选区划分赢得选举的，那么任何选区划分的改变都可能导致他失去席位。即使重新划分选区导致了新的选区划分，大多数议员也更关心保住自己的席位，而不是增加本党的席位数量。结果，一些选区几十年都没有进行过重大调整，即便美国的人口结构已经从以农村为主转变为以城市为主。到了20世纪60年代初，一些选区的人口数量已经是邻近农村选区的数倍。

However, in its one-person-one-vote decision in Reynolds v. Simms (1964), the Supreme Court argued that everyone’s vote should count roughly the same regardless of where they lived.70 Districts had to be adjusted so they would have roughly equal populations. Several states therefore had to make dramatic changes to their electoral maps during the next two redistricting cycles (1970–1972 and 1980–1982). Map designers, no longer certain how to protect individual party members, changed tactics to try to create safe seats so members of their party could be assured of winning by a comfortable margin. Designers sought to draw districts in which their preferred party had a 55 percent or better chance of winning a given district, regardless of which candidate the party nominated.

[.my2]
然而，在 1964 年的雷诺兹诉西姆斯案中，最高法院裁定“一人一票”原则，认为无论居住地在哪里，每个人的选票都应大致相同。因此， 70 个选区必须进行调整，以确保各选区人口大致相等。在接下来的两次选区重划周期（1970-1972 年和 1980-1982 年）中，一些州不得不对其选区地图进行大幅修改。由于不再确定如何保障各党派成员的利益，地图设计者改变了策略，试图划分出 “安全选区 ” ，以确保本党成员能够以较大优势获胜。设计者力求划分出本党获胜概率达到 55%或更高的选区，而不管该党提名哪位候选人。

Of course, many early efforts at post-Reynolds gerrymandering were crude since map designers had no good way of knowing exactly where partisans lived. At best, designers might have a rough idea of voting patterns between precincts, but they lacked the ability to know voting patterns in individual blocks or neighborhoods. They also had to contend with the inherent mobility of the U.S. population, which meant the most carefully drawn maps could be obsolete just a few years later. Designers were often forced to use crude proxies for party, such as race or the socio-economic status of a neighborhood (Figure 9.19). Some maps were so crude they were ruled unconstitutionally discriminatory by the courts.

[.my2]
当然， 雷诺兹之后早期的许多选区划分尝试都比较粗糙，因为地图设计者无法准确掌握党派支持者的居住地。他们最多只能大致了解各选区之间的投票模式，却无法掌握具体街区或社区的投票情况。此外，他们还必须应对美国人口固有的流动性，这意味着即使是最精心绘制的地图，几年后也可能过时。设计者常常被迫使用粗略的党派替代指标，例如种族或社区的社会经济地位（ 图 9.19 ）。有些地图过于粗糙，甚至被法院裁定为违宪歧视。

A series of three maps titled “Gerrymandering in Austin, TX, 2003-2015”. The map on the left is labeled “2003-2005” and shows four districts outlined around a city labeled “Austin”. The map in the center is labeled “2005-2007” and shows five districts outlined around a city labeled “Austin”. The map on the right is labeled “2013-2015” and shows six districts outlined around a city labeled “Austin”.

[.my2]
Figure 9.19 Examples of gerrymandering in Texas, where the Republican-controlled legislature redrew House districts to reduce the number of Democratic seats by combining voters in Austin with those near the border, several hundred miles away. Today, Austin is represented by six different congressional representatives.

[.my2]
图 9.19 展示了德克萨斯州选区划分不公的案例。共和党控制的州议会重新划分众议院选区，将奥斯汀的选民与数百英里外边境附近的选民合并，从而减少民主党的席位。如今，奥斯汀由六位不同的国会众议员代表。
Proponents of the gerrymandering thesis point out that the decline in the number of moderate voters began during this period of increased redistricting. But it wasn’t until later, they argue, that the real effects could be seen. A second advance in redistricting, via computer-aided map making, truly transformed gerrymandering into a science. Refined computing technology, the ability to collect data about potential voters, and the use of advanced algorithms have given map makers a good deal of certainty about where to place district boundaries to best predetermine the outcomes. These factors also provided better predictions about future population shifts, making the effects of gerrymandering more stable over time. Proponents argue that this increased efficiency in map drawing has led to the disappearance of moderates in Congress.

[.my2]
支持选区划分不公理论的人指出，温和派选民数量的下降始于选区重划日益频繁的时期。但他们认为，真正的后果直到后来才显现出来。计算机辅助地图绘制技术的第二次进步，真正将选区划分不公变成了一门科学。先进的计算机技术、收集潜在选民数据的能力以及先进算法的应用，使得地图绘制者能够更准确地确定选区边界的位置，从而更好地预先决定选举结果。这些因素也使得对未来人口变化的预测更加准确，使得选区划分不公的影响随着时间的推移而更加稳定。支持者认为，地图绘制效率的提高导致了国会中温和派的消失。

According to political scientist Nolan McCarty, there is little evidence to support the redistricting hypothesis alone. First, he argues, the Senate has become polarized just as the House of Representatives has, but people vote for Senators on a statewide basis. There are no gerrymandered voting districts in elections for senators. Research showing that more partisan candidates first win election to the House before then running successfully for the Senate, however, helps us understand how the Senate can also become partisan.71 Furthermore, states like Wyoming and Vermont, which have only one Representative and thus elect House members on a statewide basis as well, have consistently elected people at the far ends of the ideological spectrum.72 Redistricting did contribute to polarization in the House of Representatives, but it took place largely in districts that had undergone significant change.73
政治学家诺兰· 麦卡蒂认为，仅凭选区重划这一假设缺乏足够的证据支持。首先，他指出，参议院和众议院一样都出现了政治极化，但参议员是全州范围选举产生的。参议员选举中不存在人为操纵选区的现象。然而，研究表明，党派倾向较强的候选人往往先赢得众议院选举，然后再成功竞选参议员，这有助于我们理解参议院为何也会出现党派之争。 71 此外，像怀俄明州和佛蒙特州这样只有一名众议员的州，同样是全州范围选举众议院议员，这些州历来都选出了意识形态光谱两端的人物。 72 选区重划确实加剧了众议院的政治极化，但这主要发生在那些已经发生重大变化的选区。 73

Furthermore, polarization has been occurring throughout the country, but the use of increasingly polarized district design has not. While some states have seen an increase in these practices, many states were already largely dominated by a single party (such as in the Solid South) but still elected moderate representatives. Some parts of the country have remained closely divided between the two parties, making overt attempts at gerrymandering difficult. But when coupled with the sorting phenomenon discussed above, redistricting probably is contributing to polarization, if only at the margins.

[.my2]
此外，尽管全国范围内都出现了政治极化现象，但选区划分中日益极化的趋势却并未如此。虽然一些州的这种做法有所增加，但许多州原本就主要由单一政党主导（例如“铁杆南方”地区），却仍然选出了温和派代表。一些地区两党之间的分歧依然十分明显，使得公开操纵选区划分的企图难以得逞。但如果将上述的选民分化现象结合起来，选区重划或许会在边缘地区加剧政治极化。

Finding a Middle Ground
寻找折衷方案
The Politics of Redistricting
选区重划的政治意义
Voters in a number of states have become so worried about the problem of gerrymandering that they have tried to deny their legislatures the ability to draw district boundaries. The hope is that by taking this power away from whichever party controls the state legislature, voters can ensure more competitive districts and fairer electoral outcomes.

[.my2]
一些州的选民对选区划分不公的问题深感担忧，以至于他们试图剥夺州议会划分选区的权力。他们希望通过剥夺控制州议会的政党的这项权力，能够确保选区更具竞争性，选举结果更加公平。

In 2000, voters in Arizona approved a referendum that created an independent state commission responsible for drafting legislative districts. But the Arizona legislature fought back against the creation of the commission, filing a lawsuit that claimed only the legislature had the constitutional right to draw districts. Legislators asked the courts to overturn the popular referendum and end the operation of the redistricting commission. However, the U.S. Supreme Court upheld the authority of the independent commission in a 5–4 decision titled Arizona State Legislature v. Arizona Independent Redistricting Commission (2015).74
2000 年，亚利桑那州选民通过了一项公投，设立了一个独立的州委员会，负责划分立法选区。但亚利桑那州议会反对设立该委员会，并提起诉讼，声称只有议会才拥有划分选区的宪法权力。议员们请求法院推翻这项全民公投，并终止该选区重划委员会的运作。然而，美国最高法院在 2015 年以 5 比 4 的投票结果，在 “亚利桑那州议会诉亚利桑那州独立选区重划委员会案”（Arizona State Legislature v. Arizona Independent Redistricting Commission ）中，维持了该独立委员会的权力 。74

Currently, only five states use fully independent commissions—ones that do not include legislators or other elected officials—to draw the lines for both state legislative and congressional districts. These states are Arizona, California, Idaho, Montana, and Washington. In Florida, the League of Women Voters and Common Cause challenged a new voting districts map supported by state Republicans, because they did not believe it fulfilled the requirements of amendments made to the state constitution in 2010 requiring that voting districts not favor any political party or incumbent.75
目前，只有五个州使用完全独立的委员会（不包括立法者或其他民选官员）来划分州议会和国会选区。这五个州分别是亚利桑那州、加利福尼亚州、爱达荷州、蒙大拿州和华盛顿州。在佛罗里达州，妇女选民联盟和公共事业组织对州共和党支持的一份新的选区划分图提出质疑，因为他们认为该图不符合 2010 年州宪法修正案的要求，该修正案规定选区划分不得偏袒任何政党或现任官员 。75

Do you think redistricting is a partisan issue? Should commissions draw districts instead of legislators? If commissions are given this task, who should serve on them?
你认为选区重划是党派问题吗？应该由委员会而不是立法者来划分选区吗？如果由委员会来承担这项任务，那么应该由哪些人组成委员会？

Link to Learning  学习链接
Think you have what it takes to gerrymander a district? Play the redistricting game and see whether you can find new ways to help out old politicians.

[.my2]
你觉得自己有能力操纵选区划分吗？来玩玩选区重划游戏 ，看看你能不能找到帮助老政客的新方法。


'''