
= 010-5 Free Speech and the Regulation of Interest Groups 言论自由与利益集团的监管
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




How are lobbying and interest group activity regulated? As we noted earlier in the chapter, James Madison viewed factions as a necessary evil and thought preventing people from joining together would be worse than any ills groups might cause. The First Amendment guarantees, among other things, freedom of speech, petition, and assembly. However, people have different views on how far this freedom extends. For example, should freedom of speech as afforded to individuals in the U.S. Constitution also apply to corporations and unions? To what extent can and should government restrict the activities of lobbyists and lawmakers, limiting who may lobby and how they may do it?
游说和利益集团的活动是如何监管的？正如我们在本章前面提到的，詹姆斯·麦迪逊认为派系斗争是一种必要的恶，他认为阻止人们联合起来比任何团体可能造成的弊端都更糟糕。美国宪法第一修正案保障了言论自由、请愿自由和集会自由等权利。然而，人们对这种自由的延伸范围持有不同的看法。例如，美国宪法赋予个人的言论自由是否也应适用于公司和工会？政府在多大程度上可以且应该限制游说者和立法者的活动，限制谁可以进行游说以及他们如何进行游说？

INTEREST GROUPS AND FREE SPEECH
利益集团与言论自由
Most people would agree that interest groups have a right under the Constitution to promote a particular point of view. What people do not necessarily agree upon, however, is the extent to which certain interest group and lobbying activities are protected under the First Amendment.

[.my2]
大多数人都会认同，利益集团有权根据宪法宣传特定观点。然而，人们对于某些利益集团和游说活动在多大程度上受到第一修正案保护，则未必能达成共识。

In addition to free speech rights, the First Amendment grants people the right to assemble. We saw above that pluralists even argued that assembling in groups is natural and that people will gravitate toward others with similar views. Most people acknowledge the right of others to assemble to voice unpopular positions, but this was not always the case. At various times, groups representing racial and religious minorities, communists, and members of the LGBTQ community have had their First Amendment rights to speech and assembly curtailed. And as noted above, organizations like the ACLU support free speech rights regardless of whether the speech is popular.

[.my2]
除了言论自由权， 第一修正案还赋予人们集会自由权。我们前面已经看到，多元主义者甚至认为，群体集会是自然而然的，人们会倾向于与观点相似的人聚集在一起。大多数人承认他人有权集会表达不受欢迎的观点，但情况并非总是如此。在不同时期，代表种族和宗教少数群体、共产主义者以及 LGBTQ 群体的团体都曾遭受过第一修正案赋予的言论和集会自由权的限制。正如上文所述，像美国公民自由联盟（ACLU）这样的组织支持言论自由权，无论这种言论是否受欢迎。

Today, the debate about interest groups often revolves around whether the First Amendment protects the rights of individuals and groups to give money, and whether government can regulate the use of this money. In 1971, the Federal Election Campaign Act was passed, setting limits on how much presidential and vice-presidential candidates and their families could donate to their own campaigns.75 The law also allowed corporations and unions to form PACs and required public disclosure of campaign contributions and their sources. In 1974, the act was amended in an attempt to limit the amount of money spent on congressional campaigns. The amended law banned the transfer of union, corporate, and trade association money to parties for distribution to campaigns.

[.my2]
如今，关于利益集团的争论往往围绕着第一修正案是否保护个人和团体捐款的权利，以及政府是否有权监管这些资金的使用。1971 年，《 联邦竞选法》 获得通过，对总统和副总统候选人及其家人可以向自身竞选活动捐款的金额设定了限制。 75 该法还允许公司和工会成立政治行动委员会（PAC），并要求公开披露竞选捐款及其来源。1974 年，该法进行了修订，试图限制国会竞选的资金支出。修订后的法律禁止将工会、公司和行业协会的资金转移给政党，再由政党分配给竞选活动。

In Buckley v. Valeo (1976), the Supreme Court upheld Congress’s right to regulate elections by restricting contributions to campaigns and candidates. However, at the same time, it overturned restrictions on expenditures by candidates and their families, as well as total expenditures by campaigns.76 In 1979, an exemption was granted to get-out-the vote and grassroots voter registration drives, creating what has become known as the soft-money loophole; soft money was a way in which interests could spend money on behalf of candidates without being restricted by federal law. To close this loophole, Senators John McCain and Russell Feingold sponsored the Bipartisan Campaign Reform Act in 2002 to ban parties from collecting and distributing unregulated money.

[.my2]
在 1976 年的 “巴克利诉瓦莱奥案”（Buckley v. Valeo ）中，最高法院维护了国会通过限制竞选活动和候选人捐款来监管选举的权力。然而，与此同时，最高法院推翻了对候选人及其家人支出以及竞选活动总支出的限制。 76 1979 年，一项针对选民动员和基层选民登记活动的豁免条款被授予，由此产生了所谓的“软钱漏洞”； 软钱是指利益集团可以代表候选人支出资金而不受联邦法律限制的一种方式。为了堵住这个漏洞，参议员约翰·麦凯恩和拉塞尔·费恩戈尔德于 2002 年共同发起了《 两党竞选改革法案》， 旨在禁止政党收集和分配不受监管的资金。

Some continued to argue that campaign expenditures are a form of speech, a position with which two recent Supreme Court decisions are consistent. The Citizens United v. Federal Election Commission77 and the McCutcheon v. Federal Election Commission78 cases opened the door for a substantially greater flow of money into elections. Citizens United overturned the soft money ban of the Bipartisan Campaign Reform Act and allowed corporations and unions to spend unlimited amounts of money on elections. Essentially, the Supreme Court argued in a 5–4 decision that these entities had free speech rights, much like individuals, and that free speech included campaign spending. The McCutcheon decision further extended spending allowances based on the First Amendment by striking down aggregate contribution limits. These limits put caps on the total contributions allowed and some say have contributed to a subsequent increase in groups and lobbying activities (Figure 10.15).

[.my2]
一些人继续辩称竞选支出是一种言论形式，这一观点与最高法院最近的两项裁决相符。“ 公民联合诉联邦选举委员会案”（Citizens United v. Federal Election Commission 77） 和 “麦卡琴诉联邦选举委员会案”（McCutcheon v. Federal Election Commission 78 ）为大量资金流入选举打开了大门。 “公民联合案” 推翻了《两党竞选改革法案》中关于“软钱”的禁令，允许公司和工会在选举中投入无限额的资金。最高法院以 5 比 4 的投票结果裁定，这些实体享有与个人类似的言论自由权，而言论自由也包括竞选支出。 “麦卡琴案”的裁决进一步扩大了基于第一修正案的支出限额，推翻了捐款总额的限制。这些限制对允许的捐款总额设定了上限，一些人认为这导致了随后团体和游说活动的增加（ 图 10.15 ）。

An image of a corpulent cartoon figure wearing a suit, hands in pockets, with a bag of money instead of a head. Text under the figure reads “The “Brains” ”.

[.my2]
Figure 10.15 With his Harper’s Weekly cartoon of William “Boss” Tweed with a moneybag for a head, Thomas Nast provided an enduring image of the corrupting power of money on politics. Some denounce “fat cat” lobbyists and the effects of large sums of money in lobbying, while others suggest that interests have every right to spend money to achieve their objectives.

[.my2]
图 10.15 托马斯·纳斯特为 《哈珀周刊》 创作的漫画中，威廉·“老板”·特威德的头被一个钱袋取代，这幅漫画深刻地揭示了金钱对政治的腐蚀作用。有人谴责“肥猫”游说者及其巨额资金在游说活动中的影响，也有人认为，利益集团完全有权花钱来实现其目标。
Link to Learning  学习链接
Read about the rights that corporations share with people.

[.my2]
了解一下公司与个人共同享有的权利 。

Should corporations have the same rights as people?
公司是否应该享有与个人相同的权利？

Insider Perspective  内部视角
The Koch Brothers  科赫兄弟
Beginning in the 1980s, conservative billionaires Charles and David Koch became increasingly active in U.S. elections . Until David's death in August 2019, the brothers together ran Koch Industries, a multinational corporation that manufactures and produces a number of products including paper, plastics, petroleum-based products, and chemicals. In the 2012 election, the Koch brothers and their affiliates spent nearly $400 million supporting Republican candidates. Many people have suggested that this spending helped put many Republicans in office. The Kochs and their related organizations planned to raise and spend nearly $900 million on the 2016 elections; however Koch Industries spending in that cycle amounted to only $11.4 million. The amounts for the 2018 midterms and 2020 general election were $12.1 million and $14.6 million, respectively.79 , 80 Critics have accused them and other wealthy donors of attempting to buy elections. However, others point out that their activities are legal according to current campaign finance laws and recent Supreme Court decisions, and that these individuals, their companies, and their affiliates should be able to spend what they want politically. As you might expect, there are wealthy donors on both the political left and the right who will continue to spend money on U.S. elections. Some critics have called for a constitutional amendment restricting spending that would overturn recent Supreme Court decisions.81
自 20 世纪 80 年代起，保守派亿万富翁查尔斯·科赫和戴维· 科赫兄弟开始日益活跃于美国大选中。在戴维于 2019 年 8 月去世之前，兄弟二人共同掌管着科赫工业集团，这是一家跨国公司，生产包括纸张、塑料、石油产品和化学品在内的多种产品。在 2012 年的总统选举中，科赫兄弟及其关联机构花费了近 4 亿美元支持共和党候选人。许多人认为，这笔支出帮助许多共和党人当选。科赫兄弟及其相关组织计划在 2016 年大选中筹集并花费近 9 亿美元；然而，科赫工业集团在该轮选举中的支出仅为 1140 万美元。2018 年中期选举和 2020 年大选的支出分别为 1210 万美元和 1460 万美元。 79 , 80 批评人士指责他们和其他富有的捐助者试图收买选举。然而，也有人指出，根据现行的竞选财务法和最高法院近期的裁决，他们的活动是合法的，这些人、他们的公司及其关联机构应该有权在政治上自由支配资金。正如你所预料的，无论左翼还是右翼，都有富有的捐助者会继续在美国大选中投入资金。一些批评人士呼吁修改宪法，限制政治支出，以推翻最高法院近期的裁决 。81

Do you agree, as some have argued, that the Constitution protects the ability to donate unlimited amounts of money to political candidates as a First Amendment right? Is spending money a form of exercising free speech? If so, does a PAC have this right? Why or why not?
你是否同意某些人的观点，即宪法保护向政治候选人捐赠无限额资金的权利，将其视为一项第一修正案赋予的权利？花钱是否属于行使言论自由的一种形式？如果是，政治行动委员会（PAC）是否拥有这项权利？为什么？

REGULATING LOBBYING AND INTEREST GROUP ACTIVITY
监管游说和利益集团活动
While the Supreme Court has paved the way for increased spending in politics, lobbying is still regulated in many ways.82 The 1995 Lobbying Disclosure Act defined who can and cannot lobby, and requires lobbyists and interest groups to register with the federal government.83 The Honest Leadership and Open Government Act of 2007 further increased restrictions on lobbying. For example, the act prohibited contact between members of Congress and lobbyists who were the spouses of other Congress members. The laws broadened the definition of lobbyist and require detailed disclosure of spending on lobbying activity, including who is lobbied and what bills are of interest. In addition, President Biden's Executive Order 13989 broadened regulations on federal employees by prohibiting appointees in the executive branch from accepting gifts from lobbyists, by requiring them to sign an ethics pledge, and lessens the revolving door by disallowing lobbying for two years after the leave the administration.84 The states also have their own registration requirements, with some defining lobbying broadly and others more narrowly.

[.my2]
尽管最高法院为增加政治支出铺平了道路，但游说活动在许多方面仍然受到监管。 82 1995 年的 《游说披露法》 界定了哪些人可以进行游说，哪些人不可以，并要求游说者和利益集团在联邦政府注册。 83 2007 年的《 诚实领导和开放政府法》 进一步加强了对游说的限制。例如，该法案禁止国会议员与身为其他国会议员配偶的游说者进行接触。这些法律扩大了游说者的定义，并要求详细披露游说活动的支出，包括游说对象和关注的法案。此外，拜登总统的第 13989 号行政命令扩大了对联邦雇员的监管，禁止行政部门的任命官员接受游说者的礼物，要求他们签署道德承诺书，并通过禁止离职后两年内从事游说活动来减少“旋转门”现象。 84 各州也有自己的注册要求，有些州对游说的定义较为宽泛，有些州的定义则较为狭窄。

Second, the federal and state governments prohibit certain activities like providing gifts to lawmakers and compensating lobbyists with commissions for successful lobbying. Many activities are prohibited to prevent accusations of vote buying or currying favor with lawmakers. Some states, for example, have strict limits on how much money lobbyists can spend on lobbying lawmakers, or on the value of gifts lawmakers can accept from lobbyists. According to the Honest Leadership and Open Government Act, lobbyists must certify that they have not violated the law regarding gift giving, and the penalty for knowingly violating the law increased from a fine of $50,000 to one of $200,000. Also, revolving door laws also prevent lawmakers from lobbying government immediately after leaving public office. Members of the House of Representatives cannot register to lobby for a year after they leave office, while senators have a two-year “cooling off” period before they can officially lobby. Former cabinet secretaries must wait the same period of time after leaving their positions before lobbying the department of which they had been the head. These laws are designed to restrict former lawmakers from using their connections in government to give them an advantage when lobbying. Still, many former lawmakers do become lobbyists, including former Senate majority leader Trent Lott and former House minority leader Richard Gephardt.

[.my2]
其次，联邦和州政府禁止某些活动，例如向立法者赠送礼物以及向游说者支付佣金以换取其游说成功。许多活动被禁止是为了防止被指控贿选或讨好立法者。例如，一些州对游说者用于游说立法者的资金数额，以及立法者可以接受的礼物价值都有严格的限制。根据《诚实领导和公开政府法案》，游说者必须证明他们没有违反有关赠送礼物的法律，而故意违反该法律的处罚也从 5 万美元的罚款提高到了 20 万美元。此外， “旋转门”法也禁止立法者在卸任后立即游说政府。众议院议员在卸任后一年内不得注册游说，而参议员则有两年的“冷静期”才能正式进行游说。前内阁部长在卸任后也必须等待同样的时间才能游说他们曾经担任领导的部门。这些法律旨在限制前议员利用其在政府中的人脉关系在游说活动中获取优势。然而，许多前议员仍然成为游说者，其中包括前参议院多数党领袖特伦特·洛特和前众议院少数党领袖理查德·格普哈特。

Third, governments require varying levels of disclosure about the amount of money spent on lobbying efforts. The logic here is that lawmakers will think twice about accepting money from controversial donors. The other advantage to disclosure requirements is that they promote transparency. Many have argued that the public has a right to know where candidates get their money. Candidates may be reluctant to accept contributions from donors affiliated with unpopular interests such as hate groups. This was one of the key purposes of the Lobbying Disclosure Act and comparable laws at the state level.

[.my2]
第三，各国政府对游说活动资金数额的披露要求各不相同。其逻辑在于，立法者在接受来自争议捐赠者的捐款时会更加谨慎。披露要求的另一个优势在于其能够提升透明度。许多人认为，公众有权了解候选人的资金来源。候选人可能不愿接受来自与仇恨团体等不受欢迎利益相关的捐赠者的捐款。这正是《游说披露法》及各州类似法律的主要目的之一。

Finally, there are penalties for violating the law. Lobbyists and, in some cases, government officials can be fined, banned from lobbying, or even sentenced to prison. While state and federal laws spell out what activities are legal and illegal, the attorneys general and prosecutors responsible for enforcing lobbying regulations may be understaffed, have limited budgets, or face backlogs of work, making it difficult for them to investigate or prosecute alleged transgressions. While most lobbyists do comply with the law, exactly how the laws alter behavior is not completely understood. We know the laws prevent lobbyists from engaging in certain behaviors, such as by limiting campaign contributions or preventing the provision of certain gifts to lawmakers, but how they alter lobbyists’ strategies and tactics remains unclear.

[.my2]
最后，违法行为会受到处罚。游说者，以及在某些情况下，政府官员，可能会被处以罚款、禁止游说，甚至被判入狱。虽然州和联邦法律明确规定了哪些活动合法，哪些活动非法，但负责执行游说法规的司法部长和检察官可能人手不足、预算有限或面临积压工作，这使得他们难以调查或起诉涉嫌违法行为。虽然大多数游说者都遵守法律，但法律究竟如何改变游说者的行为尚不完全清楚。我们知道法律禁止游说者从事某些行为，例如限制竞选捐款或禁止向立法者提供某些礼物，但法律如何改变游说者的策略和战术仍然不明朗。

The need to strictly regulate the actions of lobbyists became especially relevant after the activities of lobbyist Jack Abramoff were brought to light (Figure 10.16). A prominent lobbyist with ties to many of the Republican members of Congress, Abramoff used funds provided by his clients to fund reelection campaigns, pay for trips, and hire the spouses of members of Congress. Between 1994 and 2001, Abramoff, who then worked as a lobbyist for a prominent law firm, paid for eighty-five members of Congress to travel to the Northern Mariana Islands, a U.S. territory in the Pacific. The territory’s government was a client of the firm for which he worked. At the time, Abramoff was lobbying Congress to exempt the Northern Mariana Islands from paying the federal minimum wage and to allow the territory to continue to operate sweatshops in which people worked in deplorable conditions. In 2000, while representing Native American casino interests who sought to defeat anti-gambling legislation, Abramoff paid for a trip to Scotland for Tom DeLay, the majority whip in the House of Representatives, and an aide. Shortly thereafter, DeLay helped to defeat anti-gambling legislation in the House. He also hired DeLay’s wife Christine to research the favorite charity of each member of Congress and paid her $115,000 for her efforts.85 In 2008, Jack Abramoff was sentenced to four years in prison for tax evasion, fraud, and corruption of public officials.86 He was released early, in December 2010.

[.my2]
在游说者杰克 ·阿布拉莫夫 （Jack Abramoff）的活动被曝光后（ 图 10.16 ），严格监管游说者的行为变得尤为重要。阿布拉莫夫是一位与众多共和党国会议员关系密切的知名游说者，他利用客户提供的资金资助议员的连任竞选、支付旅行费用，并雇佣国会议员的配偶。1994 年至 2001 年间，当时就职于一家知名律师事务所的阿布拉莫夫，支付了 85 名国会议员前往北马里亚纳群岛（位于太平洋的美国属地）的旅行费用。该属地政府是阿布拉莫夫所在律师事务所的客户。当时，阿布拉莫夫正在游说国会，要求豁免北马里亚纳群岛支付联邦最低工资，并允许该属地继续经营血汗工厂，使工人在极其恶劣的条件下工作。 2000 年，杰克·阿布拉莫夫代表试图阻止反赌博法案通过的美洲原住民赌场利益集团时，曾出资让众议院多数党党鞭汤姆·迪莱及其一名助手前往苏格兰旅行。不久之后，迪莱便帮助众议院否决了反赌博法案。他还雇佣了迪莱的妻子克里斯汀调查每位国会议员最青睐的慈善机构，并为此支付了她 11.5 万美元。 85 2008 年，杰克·阿布拉莫夫因逃税、欺诈和腐败公职人员罪被判处四年监禁。 86 他于 2010 年 12 月提前获释。

An image of Jack Abramoff standing between Ronald Reagan and Grover Norquist.

[.my2]
Figure   数字 10.16 Jack Abramoff (center) began his lifetime engagement in politics with his involvement in the 1980 presidential campaign of Ronald Reagan (left) while an undergraduate at Brandeis University and continued it with his election to chair of the College Republican National Committee in a campaign managed by Grover Norquist (right). Abramoff thus gained unique access to influential politicians, upon which he capitalized in his later work as a DC lobbyist. Since his release from federal prison in 2010 after being convicted for illegal lobbying activity, Abramoff has become an outspoken critic of the lobbying industry.87
杰克·阿布拉莫夫（中）的政治生涯始于 1980 年，当时他还在布兰迪斯大学读本科，参与了罗纳德·里根（左）的总统竞选活动。之后，他当选为大学共和党全国委员会主席，该竞选活动由格罗弗·诺奎斯特（右）负责。阿布拉莫夫由此获得了接触有影响力的政客的独特机会，并在后来的华盛顿特区游说工作中充分利用了这一优势。 2010 年，阿布拉莫夫因非法游说活动被判入狱，出狱后，他成为了游说行业的直言不讳的批评者。
Lobbying of U.S. governmental institutions by interest groups takes place across a variety of branches and at many levels of government. Furthermore, attempts at influence through lobbying take place on topics of domestic policy as well as foreign policy. In the latter area, as U.S. institutions take up U.S. policies that may affect people in other countries, it is not surprising that we see lobbying of the U.S. government by representatives of these foreign interests. These individuals face the same requirements as domestic lobbyists under the Lobby Disclosure Act. Moreover, they are required to register as foreign agents under the Foreign Agents Registration Act. Despite these requirements, some have raised concerns about the dangers of foreign influence, as enforcement of these disclosure requirements can be tough. Others argue that freedom of speech and assembly applies to all, not just to U.S. citizens.88 , 89 , 90
利益集团对美国政府机构的游说活动遍及各个部门和各级政府。此外，游说活动不仅涉及国内政策，也涉及外交政策。在外交政策领域，由于美国机构制定的政策可能会影响其他国家的人民，因此我们看到这些外国利益集团的代表游说美国政府也就不足为奇了。根据《游说披露法》，这些人与国内游说者一样，必须遵守相关规定。此外，他们还必须根据《外国代理人登记法》进行登记。尽管有这些规定，但一些人仍然对外国影响的风险表示担忧，因为这些披露要求的执行可能很困难。另一些人则认为，言论自由和集会自由适用于所有人，而不仅仅是美国公民。 88 , 89 , 90


'''