
= 010-1 Interest Groups Defined 利益集团的定义
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





While the term interest group is not mentioned in the U.S. Constitution, the framers were aware that individuals would band together in an attempt to use government in their favor. In Federalist No. 10, James Madison warned of the dangers of “factions,” minorities who would organize around issues they felt strongly about, possibly to the detriment of the majority. But Madison believed limiting these factions was worse than facing the evils they might produce, because such limitations would violate individual freedoms. Instead, the natural way to control factions was to let them flourish and compete against each other. The sheer number of interests in the United States suggests that many have, indeed, flourished. They compete with similar groups for membership, and with opponents for access to decision-makers. Some people suggest there may be too many interests in the United States. Others argue that some have gained a disproportionate amount of influence over public policy, whereas many others are underrepresented.

[.my2]
虽然美国宪法中没有提及 “利益集团” 一词，但制宪者们意识到，人们会联合起来，试图利用政府为自身谋利。在 《联邦党人文集 》第十篇中，詹姆斯 ·麦迪逊警告说，“派系”——即少数群体围绕他们强烈关注的议题组织起来，可能损害多数群体利益——的危险性。但麦迪逊认为，限制这些派系比直面它们可能造成的弊端更糟糕，因为限制会侵犯个人自由。相反，控制派系的自然方法是让它们蓬勃发展，彼此竞争。美国庞大的利益集团数量表明，许多利益集团确实蓬勃发展。它们与类似的团体争夺成员，并与对手争夺接触决策者的机会。有人认为，美国的利益集团可能太多了。另一些人则认为，某些利益集团对公共政策的影响力过大，而许多其他利益集团的代表性不足。

Madison’s definition of factions can apply to both interest groups and political parties. But unlike political parties, interest groups do not function primarily to elect candidates under a certain party label or to directly control the operation of the government. Political parties in the United States are generally much broader coalitions that represent a significant proportion of citizens. In the American two-party system, the Democratic and Republican Parties spread relatively wide nets to try to encompass large segments of the population. In contrast, while interest groups may support or oppose political candidates, their goals are usually more issue-specific and narrowly focused on areas like taxes, the environment, and gun rights or gun control, or their membership is limited to specific professions. They may represent interests ranging from well-known organizations, such as the Sierra Club, IBM, or the American Lung Association, to obscure ones, such as the North Carolina Gamefowl Breeders Association. Thus, with some notable exceptions, specific interest groups have much more limited membership than do political parties.

[.my2]
麦迪逊对派系的定义既适用于利益集团，也适用于政党 。但与政党不同，利益集团的主要功能并非选举特定党派的候选人或直接控制政府运作。美国的政党通常是范围更广的联盟，代表着相当一部分公民。在美国的两党制中，民主党和共和党都采取相对广泛的策略，力求覆盖大部分民众。相比之下，利益集团虽然可能支持或反对政治候选人，但它们的目标通常更具体，聚焦于税收、环境、枪支权利或枪支管制等领域，或者其成员仅限于特定职业。它们所代表的利益可能涵盖范围很广，从像塞拉俱乐部、IBM 或美国肺脏协会这样知名的组织，到像北卡罗来纳州斗鸡饲养者协会这样鲜为人知的组织。因此，除了一些显著的例外情况外，特定利益集团的成员规模远小于政党。

Political parties and interest groups both work together and compete for influence, although in different ways. While interest group activity often transcends party lines, many interests are perceived as being more supportive of one party than the other. The American Conservative Union, Citizens United, the National Rifle Association, and National Right to Life are more likely to have relationships with Republican lawmakers than with Democratic ones. Americans for Democratic Action, Campaign for America's Future, and People for the American Way all have stronger relationships with the Democratic Party. Parties and interest groups do compete with each other, however, often for influence. At the state level, we typically observe an inverse relationship between them in terms of power. Interest groups tend to have greater influence in states where political parties are comparatively weaker.

[.my2]
政党和利益集团既合作又竞争影响力，尽管方式不同。虽然利益集团的活动通常超越党派界限，但许多利益集团被认为更倾向于支持某一党派。例如，美国保守联盟（American Conservative Union）、公民联合会（Citizens United）、全国步枪协会（NRA）和全国生命权组织（National Right to Life）与共和党议员的关系比与民主党议员的关系更为密切。美国民主行动组织（Americans for Democratic Action）、美国未来运动（Campaign for America's Future）和美国之路人民组织（People for the American Way）则与民主党关系更为密切。然而，政党和利益集团之间确实存在竞争，通常是为了争夺影响力。在州一级，我们通常观察到二者在权力方面呈反比关系。在政党相对弱势的州，利益集团往往拥有更大的影响力。

WHAT ARE INTEREST GROUPS AND WHAT DO THEY WANT?
什么是利益集团？他们的诉求是什么？
Definitions abound when it comes to interest groups, which are sometimes referred to as special interests, interest organizations, pressure groups, or just interests. Most definitions specify that interest group indicates any formal association of individuals or organizations that attempt to influence government decision-making and/or the making of public policy. Often, this influence is exercised by a lobbyist or a lobbying firm.

[.my2]
关于利益集团的定义五花八门，它们有时也被称为特殊利益集团、利益组织、压力集团或简称利益集团。大多数定义都指出， 利益集团指的是任何试图影响政府决策和/或公共政策制定的个人或组织组成的正式联盟。通常，这种影响力是由游说者或游说公司行使的。

Formally, a lobbyist is someone who represents the interest organization before government, is usually compensated for doing so, and is required to register with the government in which they lobby, whether state or federal. The lobbyist’s primary goal is usually to influence policy. Most interest organizations engage in lobbying activity to achieve their objectives. As you might expect, the interest hires a lobbyist, employs one internally, or has a member volunteer to lobby on its behalf. For present purposes, we might restrict our definition to the relatively broad one in the Lobbying Disclosure Act.2 This act requires the registration of lobbyists representing any interest group and devoting more than 20 percent of their time to it.3 Clients and lobbying firms must also register with the federal government based on similar requirements. Moreover, campaign finance laws require disclosure of campaign contributions given to political candidates by organizations.

[.my2]
从形式上讲， 游说者是指代表利益组织在政府层面进行游说的人，通常会因此获得报酬，并且必须在其游说的政府部门（无论是州政府还是联邦政府）进行注册。游说者的主要目标通常是影响政策。大多数利益组织都会开展游说活动来实现其目标。正如您所料，利益组织会聘请游说者、在内部雇用游说者，或者让其成员自愿代表其进行游说。就目前而言，我们可以将定义限定在 《游说披露法》 中相对宽泛的定义范围内。 2 该法案要求代表任何利益集团且将其超过 20%的时间投入其中的游说者进行注册。 3 客户和游说公司也必须根据类似的要求在联邦政府进行注册。此外，竞选财务法要求披露组织向政治候选人提供的竞选捐款。

Link to Learning  学习链接
Visit this site to research donations and campaign contributions given to political candidates by organizations.

[.my2]
访问此网站 ，了解各组织向政治候选人提供的捐款和竞选资金。

Lobbying is not limited to Washington, DC, however, and many interests lobby there as well as in one or more states. Each state has its own laws describing which individuals and entities must register, so the definitions of lobbyists and interests, and of what lobbying is and who must register to do it, also vary from state to state. Therefore, while a citizen contacting a lawmaker to discuss an issue is generally not viewed as lobbying, an organization that devotes a certain amount of time and resources to contacting lawmakers may be classified as lobbying, depending on local, state, or federal law.

[.my2]
游说活动并非仅限于华盛顿特区，许多利益集团不仅在华盛顿特区开展游说活动，还在一个或多个州进行游说。每个州都有自己的法律规定哪些个人和实体必须注册，因此，游说者和利益集团的定义，以及游说活动的定义和注册要求，也因州而异。因此，虽然公民联系立法者讨论某个问题通常不被视为游说，但根据地方、州或联邦法律，投入一定时间和资源联系立法者的组织可能被认定为游说活动。

Largely for this reason, there is no comprehensive list of all interest groups to tell us how many there are in the United States. Estimates of the number vary widely, suggesting that if we use a broad definition and include all interests at all levels of government, there may be more than 200,000.4 Following the passage of the Lobbying Disclosure Act in 1995, we had a much better understanding of the number of interests registered in Washington, DC; however, it was not until several years later that we had a complete count and categorization of the interests registered in each of the fifty states.5
正是由于这个原因，目前还没有一份涵盖所有利益集团的完整名单，因此我们无法得知美国究竟有多少利益集团。对利益集团数量的估计差异很大，这表明，如果我们采用广义的定义，将各级政府的所有利益集团都包括在内，那么利益集团的数量可能超过 20 万个。 4 1995 年 《游说披露法》 通过后，我们对在华盛顿特区注册的利益集团数量有了更清晰的了解；然而，直到几年后，我们才对美国五十个州注册的利益集团进行了完整的统计和分类。 5

Political scientists have categorized interest groups in a number of ways.6 First, interest groups may take the form of membership organizations, which individuals join voluntarily and to which they usually pay dues. Membership groups often consist of people who have common issues or concerns, or who want to be with others who share their views. The National Rifle Association (NRA) is a membership group consisting of members who promote gun rights (Figure 10.2). For those who advocate greater regulation of access to firearms, such as background checks prior to gun purchases, the Brady: United Against Gun Violence is a membership organization that weighs in on the other side of the issue.7
政治学家对利益集团进行了多种分类。 首先 ，利益集团可以采取会员制组织的形式，个人自愿加入并通常缴纳会费。会员制组织通常由具有共同问题或关注点的人组成，或者由希望与持有相同观点的人组成。全国步枪协会（NRA）就是一个会员制组织，其成员倡导拥枪权 （ 图 10.2 ）。对于那些主张加强枪支管制（例如购枪前进行背景调查） 的人来说，“布雷迪：联合反对枪支暴力”则是一个持相反立场的会员制组织。

Image A is of the back window of a vehicle. A sign visible through the back window reads “I’ll keep my freedom, my guns, and my money, you keep the change!” Image B is an aerial view of a street filled with a large and dense crowd of people carrying signs. Image C is if a group of young people marching with signs related to “March for Our Lives.”
Figure 10.2 A Florida member of the NRA proudly displays his support of gun rights (a). After the mass shooting at Marjory Stoneman Douglas High School in Parkland, Florida, on February 14, 2018, which resulted in seventeen deaths, massive demonstrations were quickly organized. On March 24, 2018, in Washington DC (b), San Francisco (c), and 880 sister sites, young Americans gathered and marched to highlight the need for gun control reform. (credit a: modification of work by Daniel Oines/Flickr, CC BY; credit b: modification of "March for Our Lives" by Phil Roeder/Wikimedia Commons, CC BY; credit c: modification of "March for Our Lives SF" by Roger Jones/Flickr, Public Domain)
图 10.2 一位佛罗里达州的美国步枪协会 (NRA) 会员自豪地展示他对拥枪权的支持 (a)。2018 年 2 月 14 日，佛罗里达州帕克兰市玛乔丽·斯通曼·道格拉斯高中发生大规模枪击事件，造成 17 人死亡，此后迅速组织了大规模示威活动。2018 年 3 月 24 日，在华盛顿特区 (b)、旧金山 (c) 以及其他 880 个城市，美国青年聚集游行，强调枪支管制改革的必要性。（图片来源：a：Daniel Oines/Flickr 作品的修改版，CC BY；b：Phil Roeder/Wikimedia Commons 的“March for Our Lives”作品的修改版，CC BY；c：Roger Jones/Flickr 的“March for Our Lives SF”作品的修改版，公共领域）
Interest groups may also form to represent companies, corporate organizations, and governments. These groups do not have individual members but rather are offshoots of corporate or governmental entities with a compelling interest to be represented in front of one or more branches of government. Verizon and Coca-Cola will register to lobby in order to influence policy in a way that benefits them. These corporations will either have one or more in-house lobbyists, who work for one interest group or firm and represent their organization in a lobbying capacity, and/or will hire a contract lobbyist, individuals who work for firms that represent a multitude of clients and are often hired because of their resources and their ability to contact and lobby lawmakers, to represent them before the legislature.

[.my2]
利益集团也可能成立，代表公司、企业组织和政府的利益。这些集团没有个人成员，而是企业或政府实体的分支机构，这些实体有强烈的利益诉求，需要在政府的一个或多个部门面前获得代表。例如，Verizon 和可口可乐会注册游说，以影响政策，从而使自身受益。这些公司要么拥有一名或多名内部游说人员 ，他们为某个利益集团或公司工作，代表其组织进行游说；要么会聘请合同游说人员 ，这些人员受雇于代表众多客户的公司，通常因其资源和与立法者沟通游说的能力而被聘用，代表公司在立法机构面前进行游说。

Governments such as municipalities and executive departments such as the Department of Education register to lobby in an effort to maximize their share of budgets or increase their level of autonomy. These government institutions are represented by a legislative liaison, whose job is to present issues to decision-makers. For example, a state university usually employs a lobbyist, legislative liaison, or government affairs person to represent its interests before the legislature. This includes lobbying for a given university’s share of the budget or for its continued autonomy from lawmakers and other state-level officials who may attempt to play a greater oversight role.

[.my2]
包括市政当局和教育部等行政部门在内的各级政府机构都会进行游说登记，以期最大限度地提高其预算份额或扩大其自主权。这些政府机构通常会聘请立法联络员 ，其职责是向决策者陈述问题。例如，州立大学通常会聘请游说人员、立法联络员或政府事务人员，代表其在立法机构面前维护自身利益。这包括游说争取大学在预算中的份额，或争取其继续享有自主权，免受立法者和其他州级官员的过度干预，以避免他们试图发挥更大的监督作用。

In 2015, thirteen states had their higher education budgets cut from the previous year, and nearly all states have seen some cuts to higher education funding since the recession began in 2008.8 In 2015, as in many states, universities and community colleges in Mississippi lobbied the legislature over pending budget cuts.9 These examples highlight the need for universities and state university systems to have representation before the legislature. On the federal level, universities may lobby for research funds from government departments. For example, the Departments of Defense and Homeland Security may be willing to fund scientific research that might better enable them to defend the nation.

[.my2]
2015 年，有 13 个州的高等教育预算较上一年有所削减，自 2008 年经济衰退开始以来，几乎所有州的高等教育经费都出现了一定程度的削减。 8 2015 年，与许多州一样，密西西比州的大学和社区学院也就即将面临的预算削减问题游说州议会。 9 这些例子凸显了大学和州立大学系统在州议会拥有代表权的重要性。在联邦层面，大学可以游说政府部门提供研究经费。例如，国防部和国土安全部可能愿意资助有助于更好地保卫国家的科学研究。

Interest groups also include associations, which are typically groups of institutions that join with others, often within the same trade or industry (trade associations), and have similar concerns. The American Beverage Association10 includes Coca-Cola, Red Bull North America, ROCKSTAR, and Kraft Foods. Despite the fact that these companies are competitors, they have common interests related to the manufacturing, bottling, and distribution of beverages, as well as the regulation of their business activities. The logic is that there is strength in numbers, and if members can lobby for tax breaks or eased regulations for an entire industry, they may all benefit. These common goals do not, however, prevent individual association members from employing in-house lobbyists or contract lobbying firms to represent their own business or organization as well. Indeed, many members of associations are competitors who also seek representation individually before the legislature.

[.my2]
利益集团也包括协会 ，协会通常由一些机构组成，这些机构往往来自同一行业或领域（ 例如行业协会 ） ，并拥有相似的利益诉求。例如，美国饮料协会 10 的成员包括可口可乐、红牛北美公司、ROCKSTAR 和卡夫食品。尽管这些公司是竞争对手，但它们在饮料的生产、装瓶和分销以及业务监管方面拥有共同的利益。其逻辑在于，人多力量大，如果成员能够游说为整个行业争取税收减免或放宽监管，那么所有成员都将受益。然而，这些共同目标并不妨碍各个协会成员聘用内部游说人员或聘请游说公司来代表自己的企业或组织。事实上，许多协会成员本身就是竞争对手，他们也会在立法机构寻求各自的代表。

Link to Learning  学习链接
Visit the website of an association like the American Beverage Association or the American Bankers Association and look over the key issues it addresses. Do any of the issues it cares about surprise you? What areas do you think members can agree about? Are there issues on which the membership might disagree? Why would competitors join together when they normally compete for business?
访问美国饮料协会或美国银行家协会等协会的网站，浏览它们关注的关键议题。它们关注的议题中，有哪些让你感到意外？你认为会员们在哪些方面能够达成共识？是否存在会员们可能存在分歧的议题？为什么竞争对手会在通常情况下争夺业务的情况下联合起来？

Finally, sometimes individuals volunteer to represent an organization. They are called amateur or volunteer lobbyists, and are typically not compensated for their lobbying efforts. In some cases, citizens may lobby for pet projects because they care about some issue or cause. They may or may not be members of an interest group, but if they register to lobby, they are sometimes nicknamed “hobbyists.”
最后，有时个人会自愿代表某个组织进行游说。他们被称为业余或志愿游说者，通常不会因其游说活动获得报酬。在某些情况下，公民可能会因为关心某些问题或事业而为自己感兴趣的项目进行游说。他们可能是利益集团的成员，也可能不是，但如果他们注册成为游说者，有时会被戏称为“业余人士”。

Lobbyists representing a variety of organizations employ different techniques to achieve their objectives. One method is inside lobbying or direct lobbying, which takes the interest group’s message directly to a government official such as a lawmaker.11 Inside lobbying tactics include testifying in legislative hearings and helping to draft legislation. Numerous surveys of lobbyists have confirmed that the vast majority rely on these inside strategies. For example, nearly all report that they contact lawmakers, testify before the legislature, help draft legislation, and contact executive agencies. Trying to influence government appointments or providing favors to members of government are somewhat less common insider tactics.

[.my2]
代表不同组织的游说者采用各种不同的技巧来实现其目标。其中一种方法是内部游说或直接游说，即将利益集团的信息直接传递给政府官员，例如立法者。 11 内部游说策略包括在立法听证会上作证和协助起草法案。大量针对游说者的调查证实，绝大多数人都依赖这些内部策略。例如，几乎所有人都表示他们会联系立法者、在立法机构作证、协助起草法案以及联系行政机构。试图影响政府任命或向政府官员提供好处则相对少见。

Many lobbyists also use outside lobbying or indirect lobbying tactics, whereby the interest attempts to get its message out to the public.12 These tactics include issuing press releases, placing stories and articles in the media, entering coalitions with other groups, and contacting interest group members, hoping that they will individually pressure lawmakers to support or oppose legislation. An environmental interest group like the Sierra Club, for example, might issue a press release or encourage its members to contact their representatives in Congress about legislation of concern to the group. It might also use outside tactics if there is a potential threat to the environment and the group wants to raise awareness among its members and the public (Figure 10.3). Members of Congress are likely to pay attention when many constituents contact them about an issue or proposed bill. Many interest groups, including the Sierra Club, will use a combination of inside and outside tactics in their lobbying efforts, choosing whatever strategy is most likely to help them achieve their goals.

[.my2]
许多游说者还会采用外部游说或间接游说策略，试图将自身利益诉求传递给公众。 12 这些策略包括发布新闻稿、在媒体上发表报道和文章、与其他团体结盟，以及联系利益集团成员，希望他们能够分别向立法者施压，促使其支持或反对某项立法。例如，像塞拉俱乐部这样的环保利益集团可能会发布新闻稿，或鼓励其成员就该集团关注的立法问题联系各自的国会代表。如果环境面临潜在威胁，且该集团希望提高其成员和公众的环保意识，它也可能采用外部游说策略（ 图 10.3 ）。当许多选民就某个议题或提案联系国会议员时，议员们更有可能予以关注。包括塞拉俱乐部在内的许多利益集团都会在其游说活动中结合使用内部和外部策略，选择最有可能帮助他们实现目标的策略。

An image of a person speaking through a bullhorn on the left, and a crowd of people marching down a street on the right. Several marchers are holding a large banner that reads “Sierra Club”.

[.my2]
Figure 10.3 In February 2013, members of the Sierra Club joined a march on Los Angeles City Hall to demand action on climate change and protest the development of the Keystone pipeline. This was the Sierra Club's first act of civil disobedience across its 120-year history. (credit: Charlie Kaijo)
图 10.3 2013 年 2 月，塞拉俱乐部成员参加了在洛杉矶市政厅举行的游行，要求采取行动应对气候变化，并抗议基斯通输油管道的建设。这是塞拉俱乐部在其 120 年历史上首次采取公民不服从行动。（图片来源：查理·凯乔）
The primary goal of most interests, no matter their lobbying approach, is to influence decision-makers and public policies. For example, National Right to Life, an anti-abortion interest group, lobbies to encourage government to enact laws that restrict abortion access, while NARAL Pro-Choice America lobbies to promote the right of women to have safe choices about abortion. Environmental interests like the Sierra Club lobby for laws designed to protect natural resources and minimize the use of pollutants. On the other hand, some interests lobby to reduce regulations that an organization might view as burdensome. Air and water quality regulations designed to improve or protect the environment may be viewed as onerous by industries that pollute as a byproduct of their production or manufacturing process. Other interests lobby for budgetary allocations; the farm lobby, for example, pressures Congress to secure new farm subsidies or maintain existing ones. Farm subsidies are given to some farmers because they grow certain crops and to other farmers so they will not grow certain crops.13 As expected, any bill that might attempt to alter these subsidies raises the antennae of many agricultural interests.

[.my2]
大多数利益集团的首要目标，无论其游说方式如何，都是影响决策者和公共政策。例如，反堕胎利益集团“全国生命权组织”（National Right to Life）游说政府制定限制堕胎的法律，而“美国支持堕胎权联盟”（NARAL Pro-Choice America）则游说促进女性拥有安全堕胎选择的权利。像塞拉俱乐部（Sierra Club）这样的环保组织则游说制定旨在保护自然资源和最大限度减少污染物使用的法律。另一方面，一些利益集团则游说减少某些组织认为繁琐的监管规定。旨在改善或保护环境的空气和水质法规，可能会被那些在生产或制造过程中产生污染的行业视为负担。其他利益集团则游说争取预算拨款；例如，农业游说团体向国会施压，以确保新的农业补贴或维持现有的补贴。农业补贴发放给一些种植特定作物的农民，也发放给另一些不种植特定作物的农民。正如预期的那样 ，任何试图改变这些补贴的法案都会引起许多农业利益集团的关注。

INTEREST GROUP FUNCTIONS
利益集团职能
While influencing policy is the primary goal, interest groups also monitor government activity, serve as a means of political participation for members, and provide information to the public and to lawmakers. According to the National Conference of State Legislatures, thirty-six states have laws requiring that voters provide identification at the polls.14 A civil rights group like the National Association for the Advancement of Colored People (NAACP) will keep track of proposed voter-identification bills in state legislatures that might have an effect on voting rights. This organization will contact lawmakers to voice approval or disapproval of proposed legislation (inside lobbying) and encourage group members to take action by either donating money to it or contacting lawmakers about the proposed bill (outside lobbying). Thus, a member of the organization or a citizen concerned about voting rights need not be an expert on the legislative process or the technical or legal details of a proposed bill to be informed about potential threats to voting rights. Other interest groups function in similar ways. For example, the NRA monitors attempts by state legislatures to tighten gun control laws.

[.my2]
虽然影响政策是主要目标，但利益集团也会监督政府活动，为成员提供政治参与的途径，并向公众和立法者提供信息。据全国州议会联合会统计 ，已有 36 个州立法要求选民在投票时出示身份证明。 14 像全国有色人种协进会（NAACP）这样的民权组织会密切关注各州议会提出的可能影响投票权的选民身份识别法案。该组织会联系立法者，表达对拟议法案的支持或反对（内部游说），并鼓励成员通过捐款或就拟议法案联系立法者（外部游说）来采取行动。因此，该组织的成员或​​关心投票权的公民无需精通立法程序或拟议法案的技术或法律细节，就能了解投票权可能面临的威胁。其他利益集团也以类似的方式运作。例如，美国步枪协会会密切关注各州立法机构加强枪支管制法律的举措。

Interest groups facilitate political participation in a number of ways. Some members become active within a group, working on behalf of the organization to promote its agenda. Some interests work to increase membership, inform the public about issues the group deems important, or organize rallies and promote get-out-the-vote efforts. Sometimes groups will utilize events to mobilize existing members or encourage new members to join. For example, following Barack Obama’s presidential victory in 2008, the NRA used the election as a rallying cry for its supporters, and it continues to attack the president on the issue of guns, despite the fact that gun rights have in some ways expanded over the course of the Obama presidency. Interest groups also organize letter-writing campaigns, stage protests, and sometimes hold fundraisers for their cause or even for political campaigns.

[.my2]
利益集团以多种方式促进政治参与。一些成员积极参与集团活动，代表组织推进其议程。一些利益集团致力于发展成员、向公众宣传其认为重要的议题，或组织集会、开展选民动员活动。有时，集团会利用各种活动来动员现有成员或鼓励新成员加入。例如，在巴拉克·奥巴马 2008 年赢得总统大选后，美国步枪协会（NRA）利用此次选举作为其支持者的动员号召，并持续就枪支问题攻击奥巴马总统，尽管在奥巴马执政期间，枪支权利在某些方面有所扩大。利益集团还会组织写信活动、举行抗议活动，有时还会为其事业甚至政治竞选筹款。

Some interests are more broadly focused than others. AARP (formerly the American Association of Retired Persons) has approximately thirty-eight million members and advocates for individuals fifty and over on a variety of issues including health care, insurance, employment, financial security, and consumer protection (Figure 10.4).15 This organization represents both liberals and conservatives, Democrats and Republicans, and many who do not identify with these categorizations. On the other hand, the Association of Black Cardiologists is a much smaller and far-narrower organization. Over the last several decades, some interest groups have sought greater specialization and have even fragmented. As you may imagine, the Association of Black Cardiologists is more specialized than the American Medical Association, which tries to represent all physicians regardless of race or specialty.

[.my2]
有些利益集团的关注范围比其他集团更广。美国退休人员协会（ AARP ，前身为美国退休人员协会）拥有约 3800 万会员，代表 50 岁及以上人士在医疗保健、保险、就业、财务保障和消费者保护等诸多议题上发声（ 图 10.4 ）。 15 该组织既代表自由派人士，也代表保守派人士；既代表民主党人，也代表共和党人；此外，还有许多不认同这些政治立场的人。另一方面，黑人心脏病专家协会的规模要小得多，关注范围也窄得多。过去几十年里，一些利益集团追求更加专业化，甚至出现了分裂。正如您所想，黑人心脏病专家协会比美国医学会更加专业化，后者力求代表所有医生，无论其种族或专业领域如何。

Four people stand behind a desk: (Left to Right) Attorney General Becerra, AARP Advocacy Manager Blanca Castro, Governor Newsom, and Assemblymember Jim Wood. Newsom holds a document.

[.my2]
Figure 10.4 Health care is an important concern for AARP and its members, so the organization makes sure to maintain connections with key policymakers in this area, such as Xavier Becerra, then-California attorney general and current, secretary of Health and Human Services, shown here (on left) with (left to right) Blanca Castro, AARP advocacy manager, California governor Gavin Newsom, and California Assembly member Jim Wood. (credit: modification of work by AARP California)
图 10.4 医疗保健是 AARP 及其会员关注的重要议题，因此该组织致力于与该领域的关键政策制定者保持联系，例如时任加州总检察长、现任卫生与公众服务部部长泽维尔·贝塞拉（图中左侧），以及（从左至右）AARP 倡导经理布兰卡·卡斯特罗、加州州长加文·纽森和加州众议员吉姆·伍德。（图片来源：AARP 加州分会作品的修改版）
PUBLIC VS. PRIVATE INTEREST GROUPS
公共利益集团与私人利益集团
Interest groups and organizations represent both private and public interests in the United States. Private interests usually seek particularized benefits from government that favor either a single interest or a narrow set of interests. For example, corporations and political institutions may lobby government for tax exemptions, fewer regulations, or favorable laws that benefit individual companies or an industry more generally. Their goal is to promote private goods. Private goods are items individuals can own, including corporate profits. An automobile is a private good; when you purchase it, you receive ownership. Wealthy individuals are more likely to accumulate private goods, and they can sometimes obtain private goods from governments, such as tax benefits, government subsidies, or government contracts.

[.my2]
在美国，利益集团和组织既代表私人利益，也代表公共利益。 私人利益通常寻求政府提供的特定利益 ， 这些利益往往偏向于单一利益或少数利益群体。例如，企业和政治机构可能会游说政府，争取税收减免、减少监管或制定有利于个别公司或整个行业的优惠法律。他们的目标是促进私人利益。私人利益是指个人可以拥有的物品，包括公司利润。汽车就是一种私人利益；购买汽车后，所有权即归你所有。富裕人士更有可能积累私人利益，他们有时还能从政府获得私人利益，例如税收优惠、政府补贴或政府合同。

On the other hand, public interest groups attempt to promote public, or collective, goods. Such collective goods are benefits—tangible or intangible—that help most or all citizens. These goods are often produced collectively, and because they may not be profitable and everyone may not agree on what public goods are best for society, they are often underfunded and thus will be underproduced unless there is government involvement. The Tennessee Valley Authority, a government corporation, provides electricity in some places where it is not profitable for private firms to do so. Other examples of collective goods are public safety, highway safety, public education, and environmental protection. With some exceptions, if an environmental interest promotes clean air or water, most or all citizens are able to enjoy the result. So if the Sierra Club encourages Congress to pass legislation that improves national air quality, citizens receive the benefit regardless of whether they are members of the organization or even support the legislation. Many environmental groups are public interest groups that lobby for and raise awareness of issues that affect large segments of the population.16
另一方面， 公共利益团体致力于推广公共利益或集体利益。这些集体利益是指能够惠及大多数或所有公民的有形或无形利益。这些利益通常是集体生产的，而且由于它们可能无利可图，并且每个人对哪些公共利益最有利于社会也可能存在分歧，因此，除非政府介入，否则它们往往资金不足，生产不足。田纳西河谷管理局（TVA）是一家政府公司，在一些私营企业无利可图的地区提供电力。其他集体利益的例子包括公共安全、公路安全、公共教育和环境保护。除少数例外情况外，如果某个环保组织致力于改善空气或水质，大多数或所有公民都能从中受益。因此，如果塞拉俱乐部（Sierra Club）鼓励国会通过改善国家空气质量的立法，那么无论公民是否是该组织的成员，甚至是否支持该立法，他们都能从中受益。许多环保组织都是公共利益团体，它们游说并提高公众对影响广大民众的各项议题的认识。 16

As the clean air example above suggests, collective goods are generally nonexcludable, meaning all or most people are entitled to the public good and cannot be prevented from enjoying it. Furthermore, collective goods are generally not subject to crowding, so that even as the population increases, people still have access to the entire public good. Thus, the military does not protect citizens only in Texas and Maryland while neglecting those in New York and Idaho, but instead it provides the collective good of national defense equally to citizens in all states. As another example, even as more cars use a public roadway, under most circumstances, additional drivers still have the option of using the same road. (High-occupancy vehicle lanes may restrict some lanes of a highway for drivers who do not car pool.)
正如上文清洁空气的例子所示，公共物品通常具有非排他性，这意味着所有或大多数人都有权享受公共物品，且不应被阻止享受。此外，公共物品通常不受拥挤效应的影响，因此即使人口增加，人们仍然可以获得全部的公共物品。因此，军队不会只保护德克萨斯州和马里兰州的公民而忽视纽约州和爱达荷州的公民，而是平等地向所有州的公民提供国防这一公共物品。再举一个例子，即使公共道路上的车辆增多，在大多数情况下，新增驾驶员仍然可以选择使用同一条道路。（高乘载车辆专用车道可能会限制部分高速公路车道，使不拼车的驾驶员无法通行。）

'''