
= 010-3 Interest Groups as Political Participation 利益集团作为政治参与
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




Interest groups offer individuals an important avenue for political participation. Tea Party protests, for instance, gave individuals all over the country the opportunity to voice their opposition to government actions and control. Likewise, the Black Lives Matter movement also gave a voice to individuals and communities frustrated with unequal treatment from police officers. Individually, the protestors would likely have received little notice, but by joining with others, they drew substantial attention in the media and from lawmakers (Figure 10.8). While the Tea Party movement might not meet the definition of interest groups presented earlier, its aims have been promoted by established interest groups. Other opportunities for participation that interest groups offer or encourage include voting, campaigning, contacting lawmakers, and informing the public about causes.

[.my2]
利益集团为个人提供了一条重要的政治参与途径。例如，茶党运动让全国各地的人们有机会表达他们对政府行为和控制的反对。同样，“黑人的命也是命”运动也让那些对警察不公平对待感到不满的个人和社区发出了声音。单独行动时，这些抗议者可能不会引起太多关注，但通过联合起来，他们吸引了媒体和立法者的广泛关注（ 图 10.8 ）。虽然茶党运动可能并不符合前文所述的利益集团定义，但其目标确实得到了既有利益集团的支持。利益集团提供或鼓励的其他参与机会还包括投票、竞选活动、联系立法者以及向公众宣传各种议题。

An image of the back a person wearing a jacket. A patch on the jacket reads “I can’t afford a lobbyist”.

[.my2]
Figure 10.8 In 2011, an Occupy Wall Street protestor highlights that the concerns of individual citizens are not always heard by those in the seats of power. (credit: Timothy Krause)
图 10.8 2011 年，一位“占领华尔街”运动的抗议者指出，普通民众的诉求并非总能被掌权者听到。（图片来源：Timothy Krause）
GROUP PARTICIPATION AS CIVIC ENGAGEMENT
群体参与即公民参与
Joining interest groups can help facilitate civic engagement, which allows people to feel more connected to the political and social community. Some interest groups develop as grassroots movements, which often begin from the bottom up among a small number of people at the local level. Interest groups can amplify the voices of such individuals through proper organization and allow them to participate in ways that would be less effective or even impossible alone or in small numbers. The Tea Party is an example of a so-called astroturf movement, because it is not, strictly speaking, a grassroots movement. Many trace the party’s origins to groups that champion the interests of the wealthy such as Americans for Prosperity and Citizens for a Sound Economy. Although many ordinary citizens support the Tea Party because of its opposition to tax increases, it attracts a great deal of support from elite and wealthy sponsors, some of whom are active in lobbying. The FreedomWorks political action committee (PAC), for example, is a conservative advocacy group that has supported the Tea Party movement. FreedomWorks is an offshoot of the interest group Citizens for a Sound Economy, which was founded by billionaire industrialists David H. and Charles G. Koch in 1984.

[.my2]
加入利益集团有助于促进公民参与，使人们感到与政治和社会群体联系更加紧密。一些利益集团发展成为草根运动 ， 通常由地方层面的少数人自下而上地发起。利益集团可以通过适当的组织来放大这些人的声音，使他们能够以个人或少数人难以做到甚至根本无法做到的方式参与其中。茶党就是一个所谓的 “人造草根运动” 的例子，因为严格来说，它并非草根运动。许多人认为茶党的起源可以追溯到一些维护富人利益的团体，例如“美国繁荣联盟”（Americans for Prosperity）和“公民促进健全经济联盟”（Citizens for a Sound Economy）。尽管许多普通民众支持茶党是因为它反对增税，但它也吸引了大量精英和富裕赞助者的支持，其中一些人积极参与游说活动。例如，自由行动政治行动委员会（FreedomWorks PAC）就是一个支持茶党运动的保守派倡导团体。 FreedomWorks 是公民促进健全经济利益集团的一个分支机构，该集团由亿万富翁实业家大卫·H·科赫和查尔斯·G·科赫于 1984 年创立。

According to political scientists Jeffrey Berry and Clyde Wilcox, interest groups provide a means of representing people and serve as a link between them and government.33 Interest groups also allow people to actively work on an issue in an effort to influence public policy. Another function of interest groups is to help educate the public. Someone concerned about the environment may not need to know what an acceptable level of sulfur dioxide is in the air, but by joining an environmental interest group, they can remain informed when air quality is poor or threatened by legislative action. A number of education-related interests have been very active following cuts to education spending in many states, including North Carolina, Mississippi, and Wisconsin, to name a few.

[.my2]
政治学家杰弗里 ·贝瑞和克莱德· 威尔科克斯认为，利益集团为民众提供了一种代表自身利益的途径，并充当民众与政府之间的桥梁。 33 利益集团也使民众能够积极参与某个议题，从而影响公共政策。利益集团的另一项功能是帮助公众接受教育。例如，关心环境的人可能并不需要了解空气中二氧化硫的可接受浓度是多少，但通过加入环保利益集团，他们可以在空气质量恶化或受到立法威胁时及时了解情况。在包括北卡罗来纳州、密西西比州和威斯康星州在内的许多州削减教育经费之后，一些与教育相关的利益集团变得异常活跃。

Interest groups also help frame issues, usually in a way that best benefits their cause. Abortion rights advocates often use the term “pro-choice” to frame abortion as an individual’s private choice to be made free of government interference, while an anti-abortion group might use the term “pro-life” to frame its position as protecting the life of the unborn. “Pro-life” groups often label their opponents as “pro-abortion,” rather than “pro-choice,” a distinction that can affect the way the public perceives the issue. Similarly, scientists and others who believe that human activity has had a negative effect on the earth’s temperature and weather patterns attribute such phenomena as the increasing frequency and severity of storms to “climate change.” Industrialists and their supporters refer to alterations in the earth’s climate as “global warming.” Those who dispute that such a change is taking place can thus point to blizzards and low temperatures as evidence that the earth is not becoming warmer.

[.my2]
利益集团也参与构建议题框架，通常以最有利于自身利益的方式进行构建。支持堕胎权的团体经常使用“支持选择权”（pro-choice）一词，将堕胎定义为个人不受政府干预的私人选择；而反对堕胎的团体则可能使用“支持生命权”（pro-life）一词，将其立场定义为保护未出生胎儿的生命。“支持生命权”团体通常将反对者称为“支持堕胎”（pro-abortion），而非“支持选择权”（pro-choice），这种区别会影响公众对该议题的认知。同样，认为人类活动对地球温度和气候模式产生负面影响的科学家和其他人士，会将风暴频率和强度的增加等现象归因于“气候变化”。工业家及其支持者则将地球气候的变化称为“全球变暖”。因此，那些否认全球变暖的人可以指出暴风雪和低温等现象，以此作为地球并未变暖的证据。

Interest groups also try to get issues on the government agenda and to monitor a variety of government programs. Following the passage of the ACA, numerous interest groups have been monitoring the implementation of the law, hoping to use successes and failures to justify their positions for and against the legislation. Those opposed have utilized the court system to try to alter or eliminate the law, or have lobbied executive agencies or departments that have a role in the law’s implementation. Similarly, teachers’ unions, parent-teacher organizations, and other education-related interests monitored initial implementation and on-going operations of the No Child Left Behind Act (NCLB) promoted and signed into law by President George W. Bush in 2002. That law was replaced in 2015 with the Every Student Succeeds Act, due in part to continual lobbying by teacher unions who tired of the stronger federal role that NCLB necessitated.34 Interest groups have increasingly utilized digital means to have attention paid to their causes. Perhaps most piercing in effect over recent years is the use of so-called hashtag activism. The hashtag is a visible part of life on Twitter and key hashtags have induced press coverage and press taglines. The most visible such use was likely the #MeToo movement, which snowballed quickly as famous woman after famous woman confirmed that they, too, had faced harrassment.35
利益集团也试图将各种议题纳入政府议程，并监督各项政府项目的实施。在《平价医疗法案》（ACA）通过后，众多利益集团一直在密切关注该法案的实施情况，希望利用其成败来论证自身对该法案的支持或反对立场。反对者利用司法系统试图修改或废除该法案，或游说负责法案实施的行政机构或部门。同样，教师工会、家长教师组织和其他教育相关利益团体也密切关注了《不让一个孩子掉队法案》（NCLB）的初期实施和后续运作。该法案由乔治·W·布什总统于 2002 年推动并签署成为法律。由于教师工会持续游说，他们对 NCLB 所要求的联邦政府权力过大感到厌倦，该法案最终于 2015 年被《每个学生都成功法案》（Every Student Succeeds Act）取代。 利益集团越来越多地利用数字手段来吸引人们对其事业的关注。近年来，或许最具影响力的手段是所谓的“话题标签行动主义”。话题标签是推特生活中不可或缺的一部分，一些关键话题标签甚至引发了媒体报道和新闻标题。其中最引人注目的例子或许是#MeToo 运动，随着一位又一位知名女性公开承认自己也曾遭受性骚扰，这场运动迅速发展壮大 。35

Milestone  里程碑
Interest Groups as a Response to Riots
利益集团作为应对骚乱的手段
The LGBTQ (lesbian, gay, bisexual, transgender, and queer [or questioning].) movement owes a great deal to the gay rights movement of the 1960s and 1970s, and in particular to the 1969 riots at the Stonewall Inn in New York’s Greenwich Village. These were a series of confrontational responses to a police raid on the bar and regular police harassment, humiliation, and abuse of LGBTQ people. The riots culminated in a number of arrests but also raised awareness of the struggles faced by members of the LGBTQ community.36 The events are also recognized as a turning point in LGTBQ identity, when many people began moving from a life of secrecy to a more public one, leading to increased cultural acceptance and securing of rights. The Stonewall Inn has recently been granted landmark status by New York City’s Landmarks Preservation Commission (Figure 10.9).

[.my2]
LGBTQ（女同性恋、男同性恋、双性恋、跨性别者和酷儿[或性取向待定者]）运动很大程度上得益于 20 世纪 60 年代和 70 年代的同性恋权利运动，尤其是 1969 年发生在纽约格林威治村石墙酒吧的骚乱。当时，警方突袭了酒吧，LGBTQ 群体长期遭受警方骚扰、羞辱和虐待，引发了一系列对抗性反抗。骚乱最终导致多人被捕，但也提高了公众对 LGBTQ 群体所面临困境的认识。 36 这些事件也被认为是 LGBTQ 身份认同的转折点，许多人开始从隐秘的生活走向公开的生活，从而获得了更广泛的文化认可，并最终获得了应有的权利。石墙酒吧最近被纽约市地标保护委员会列为地标建筑（ 图 10.9 ）。

An image of a group of people standing in front of a brick building. A sign in the window of the building reads “The Stonewall”. A multicolored flag is held by a person to the right.

[.my2]
Figure 10.9 The Stonewall Inn in New York City’s Greenwich Village was the site of arrests and riots in 1969 that, like the building itself, became an important landmark in the LGBTQ movement. (credit: Steven Damron)
图 10.9 位于纽约市格林威治村的石墙酒吧是 1969 年逮捕和骚乱的发生地，与酒吧建筑本身一样，它成为了 LGBTQ 运动的重要地标。（图片来源：Steven Damron）
The Castro district in San Francisco, California, was also home to a significant LGBTQ community during the same time period. In 1978, the community was shocked when Harvey Milk, a gay local activist and sitting member of San Francisco’s Board of Supervisors, was assassinated by a former city supervisor due to political differences.37 This resulted in protests in San Francisco and other cities across the country and the mobilization of interests concerned about gay and lesbian rights.

[.my2]
在同一时期，加利福尼亚州旧金山的卡斯特罗区也是 LGBTQ 群体的重要聚集地。1978 年，哈维·米尔克（Harvey Milk）——一位同性恋维权人士，同时也是旧金山市议会的现任议员——因政治分歧被一位前市议员刺杀，这一事件震惊了整个社区。 37 这引发了旧金山以及全美其他城市的抗议活动，并促使关注同性恋权益的各方力量积极行动起来。

Today, advocacy interest organizations like the Human Rights Campaign are at the forefront in supporting members of the LGBTQ community and popularizing a number of relevant issues. They played an active role in the effort to legalize same-sex marriage in individual states and later nationwide. Now that same-sex marriage is legal, these organizations and others are dealing with issues related to continuing discrimination against members of this community. One current debate centers around whether an individual’s religious freedom allows that individual to deny services to members of the LGBTQ community. This question reached a fever pitch over discussions about restroom facilities for transgender individuals. The Department of Labor's Occupational Safety and Health Administration (OSHA) recommends best practices for restroom access for transgender workers indicating that all employees should have access to bathroom facilities that correspond to their gender identity.38
如今，像人权运动组织这样的倡导组织在支持 LGBTQ 群体成员和普及相关议题方面发挥着先锋作用。它们在推动各州乃至全国同性婚姻合法化方面都做出了积极贡献。如今同性婚姻合法化，这些组织和其他机构正在处理与该群体成员持续遭受歧视相关的问题。目前的一个争论焦点是，个人的宗教自由是否允许其拒绝向 LGBTQ 群体成员提供服务。关于跨性别者使用卫生间设施的讨论使这个问题达到了白热化的程度。美国劳工部职业安全与健康管理局（OSHA）建议，所有员工都应享有与其性别认同相符的卫生间设施，并就跨性别员工使用卫生间的最佳实践提出建议。 38

What do you feel are lingering issues for the LGBTQ community? What approaches could you take to help increase attention and support for gay, lesbian, bisexual, and transgender rights? Do you think someone’s religious beliefs should allow them the freedom to discriminate against members of the LGBTQ community? Why or why not?
您认为 LGBTQ 群体目前还面临哪些长期存在的问题？您可以采取哪些措施来提高公众对同性恋、女同性恋、双性恋和跨性别者权利的关注和支持？您认为一个人的宗教信仰是否应该允许他们歧视 LGBTQ 群体成员？为什么？

TRENDS IN PUBLIC INTEREST GROUP FORMATION AND ACTIVITY
公共利益团体组建和活动趋势
A number of changes in interest groups have taken place over the last three or four decades in the United States. The most significant change is the tremendous increase in both the number and type of groups.39 Political scientists often examine the diversity of registered groups, in part to determine how well they reflect the variety of interests in society. Some areas may be dominated by certain industries, while others may reflect a multitude of interests. Some interests appear to have increased at greater rates than others. For example, the number of institutions and corporate interests has increased both in Washington and in the states. Telecommunication companies like Verizon and AT&T will lobby Congress for laws beneficial to their businesses, but they also target the states because state legislatures make laws that can benefit or harm their activities. There has also been an increase in the number of public interest groups that represent the public as opposed to economic interests. U.S. PIRG is a public interest group that represents the public on issues including public health, the environment, and consumer protection.40
过去三四十年间，美国的利益集团发生了诸多变化。其中最显著的变化是利益集团的数量和类型都大幅增长。 政治学家经常研究已注册利益集团的多样性，部分原因是为了确定它们在多大程度上反映了社会中各种不同的利益。某些领域可能由特定行业主导，而其他领域则可能反映出多种利益。某些利益的增长速度似乎比其他利益更快。例如，无论是在华盛顿还是在各州，机构和企业利益集团的数量都有所增加。像 Verizon 和 AT&T 这样的电信公司会游说国会制定有利于其业务的法律，但它们也会游说各州，因为州立法机构制定的法律可能会对其业务有利或有害 。代表公众而非经济利益的公共利益集团的数量也有所增加。美国公共利益研究集团（US PIRG）就是一个公共利益集团，它在公共卫生、环境和消费者保护等问题上代表公众发声。

Get Connected!  立即连接！
Public Interest Research Groups
公共利益研究团体
Public interest research groups (PIRGs) have increased in recent years, and many now exist nationally and at the state level. PIRGs represent the public in a multitude of issue areas, ranging from consumer protection to the environment, and like other interests, they provide opportunities for people to make a difference in the political process. PIRGs try to promote the common or public good, and most issues they favor affect many or even all citizens. Student PIRGs focus on issues that are important to students, including tuition costs, textbook costs, new voter registration, sustainable universities, and homelessness. Consider the cost of a college education. You may want to research how education costs have increased over time. Are cost increases similar across universities and colleges? Are they similar across states? What might explain similarities and differences in tuition costs? What solutions might help address the rising costs of higher education?
近年来， 公共利益研究团体（PIRG） 数量激增，如今已遍布全国乃至各州。PIRG 代表公众在众多议题领域发声，涵盖消费者权益保护、环境保护等，与其他利益团体一样，它们为人们参与政治进程提供了机会。PIRG 致力于促进公共利益，其关注的大多数议题都影响着众多甚至所有公民。学生 PIRG 则专注于对学生至关重要的议题，例如学费、教材费、新选民登记、可持续发展的大学以及无家可归问题。不妨思考一下大学教育的成本。您或许可以研究一下教育成本随时间推移的增长情况。不同大学和学院的成本增长幅度是否相似？各州之间的成本增长幅度是否相似？学费的异同可能由哪些因素造成？哪些解决方案有助于应对高等教育成本的不断上涨？

How can you get involved in the drive for affordable college education? Consider why students might become engaged in it and why they might not do so. A number of countries have made tuition free or nearly free.41 Is this feasible or desirable in the United States? Why or why not?
如何参与到争取负担得起的大学教育的行动中来？思考一下学生可能参与其中的原因，以及他们可能不参与的原因。许多国家已经实行了免学费或近乎免学费的教育。41 在美国 ， 这样做是否可行或可取？为什么？

Link to Learning  学习链接
Take a look at the website for Student PIRGs. What issues does this interest group address? Are these issues important to you? How can you get involved? Visit this section of their site to learn more about their position on financing higher education.

[.my2]
请访问学生公共利益研究团体（Student PIRGs）的网站 。这个利益团体关注哪些议题？这些议题对你来说重要吗？你如何参与其中？访问他们网站的这个版块 ，了解更多关于他们对高等教育融资的立场。

What are the reasons for the increase in the number of interest groups? In some cases, it simply reflects new interests in society. Forty years ago, stem cell research was not an issue on the government agenda, but as science and technology advanced, its techniques and possibilities became known to the media and the public, and a number of interests began lobbying for and against this type of research. Medical research firms and medical associations will lobby in favor of greater spending and increased research on stem cell research, while some religious organizations and anti-abortion groups will oppose it. As societal attitudes change and new issues develop, and as the public becomes aware of them, we can expect to see the rise of interests addressing them.

[.my2]
利益集团数量增加的原因是什么？在某些情况下，这仅仅反映了社会中新出现的兴趣点。四十年前， 干细胞研究并非政府议程上的议题，但随着科技的进步，其技术和可能性逐渐被媒体和公众所了解，许多利益集团开始游说支持或反对这类研究。医疗研究公司和医学协会会游说政府增加对干细胞研究的投入和研究规模，而一些宗教组织和反堕胎团体则会反对。随着社会态度的转变和新问题的出现，以及公众对这些问题的认识不断加深，我们可以预见，针对这些问题的利益集团将会不断涌现。

The devolution of power also explains some of the increase in the number and type of interests, at least at the state level. As power and responsibility shifted to state governments in the 1980s, the states began to handle responsibilities that had been under the jurisdiction of the federal government. A number of federal welfare programs, for example, are generally administered at the state level. This means interests might be better served targeting their lobbying efforts in Albany, Raleigh, Austin, or Sacramento, rather than only in Washington, DC. As the states have become more active in more policy areas, they have become prime targets for interests wanting to influence policy in their favor.42
权力下放也解释了利益集团数量和类型的增加，至少在州一级是如此。20 世纪 80 年代，随着权力和责任转移到州政府，各州开始承担原本属于联邦政府管辖的职责。例如，许多联邦福利项目通常由州政府管理。这意味着，利益集团与其仅仅在华盛顿特区游说，不如将游说目标放在奥尔巴尼、罗利、奥斯汀或萨克拉门托等地，这样可能更有利于自身利益。随着各州在更多政策领域变得更加活跃，它们也成为了那些希望影响政策以利于自身的利益集团的主要目标。 42

We have also seen increased specialization by some interests and even fragmentation of existing interests. While the American Medical Association may take a stand on stem cell research, the issue is not critical to the everyday activities of many of its members. On the other hand, stem cell research is highly salient to members of the American Neurological Association, an interest organization that represents academic neurologists and neuroscientists. Accordingly, different interests represent the more specialized needs of different specialties within the medical community, but fragmentation can occur when a large interest like this has diverging needs. Such was also the case when several unions split from the AFL-CIO (American Federation of Labor-Congress of Industrial Organizations), the nation’s largest federation of unions, in 2005.43 Improved technology and the development of social media have made it easier for smaller groups to form and to attract and communicate with members. The use of the Internet to raise money has also made it possible for even small groups to receive funding.

[.my2]
我们也看到一些领域的专业化程度不断提高，甚至现有领域的部分领域出现了碎片化。虽然美国医学会可能对干细胞研究持立场，但这个问题对许多会员的日常活动并非至关重要。另一方面，干细胞研究对美国神经病学协会的成员来说却意义重大，该协会是一个代表学术神经科医生和神经科学家的利益相关组织。因此，不同的利益相关领域代表了医学界不同专科更为专业化的需求，但当像这样的大型利益相关领域出现分歧时，就可能出现碎片化 。2005 年，几个工会脱离了美国劳工联合会-产业工会联合会（AFL-CIO，美国最大的工会联合会），情况也是如此。 43 技术的进步和社交媒体的发展使得小型团体更容易成立，也更容易吸引成员并与之沟通。利用互联网筹款也使得即使是小型团体也能获得资助。

None of this suggests that an unlimited number of interests can exist in society. The size of the economy has a bearing on the number of interests, but only up to a certain point, after which the number increases at a declining rate. As we will see below, the limit on the number of interests depends on the available resources and levels of competition.

[.my2]
这并不意味着社会中可以存在无限数量的利益集团。经济规模确实会影响利益集团的数量，但这种影响仅限于一定程度，超过这个程度后，利益集团的数量增长速度会逐渐减缓。正如我们将在下文看到的，利益集团数量的上限取决于可用资源和竞争程度。

Over the last few decades, we have also witnessed an increase in professionalization in lobbying and in the sophistication of lobbying techniques. This was not always the case, because lobbying was not considered a serious profession in the mid-twentieth century. Over the past three decades, there has been an increase in the number of contract lobbying firms. These firms are often effective because they bring significant resources to the table, their lobbyists are knowledgeable about the issues on which they lobby, and they may have existing relationships with lawmakers. In fact, relationships between lobbyists and legislators are often ongoing, and these are critical if lobbyists want access to lawmakers. However, not every interest can afford to hire high-priced contract lobbyists to represent it. As Table 10.1 suggests, a great deal of money is spent on lobbying activities.

[.my2]
过去几十年，我们见证了游说活动的专业化程度不断提高，游说技巧也日趋复杂。这种情况并非一直如此，因为在 20 世纪中期，游说并不被视为一项严肃的职业。过去三十年间，合同游说公司的数量显著增加。这些公司往往卓有成效，因为它们拥有雄厚的资源，其游说人员对所游说的议题了如指掌，并且可能与立法者建立了联系。事实上，游说人员与立法者之间的关系往往是持续性的，而这种关系对于游说人员能否接触到立法者至关重要。然而，并非所有利益相关方都能负担得起聘请高价合同游说人员来代表自己。正如表 10.1 所示，游说活动耗资巨大。

Top Lobbying Firms in 2020
2020年顶级游说公司
Lobbying Firm  游说公司	Total Lobbying Annual Income
游说活动年度总收入
Akin, Gump et al.

[.my2]
Akin、Gump 等人	$49,870,000
Brownstein, Hyatt et al.

[.my2]
Brownstein、Hyatt 等人	$48,365,000
BGR Group  BGR 集团	$31,630,000
Cornerstone Government Affairs
基石政府事务	$28,020,000
Holland & Knight  霍兰德和奈特	$27,990,000
Ballard Partners  巴拉德合伙公司	$24,420,000
Squire Patton Boggs  帕顿·博格斯乡绅	$24,215,000
Invariant LLC	$21,140,000
Forbes Tate Partners  福布斯泰特合伙公司	$19,400,000
Capitol Counsel  国会律师	$19,110,000
K&L Gates	$18,330,000
Mehlman, Castagnetti et al
Mehlman、Castagnetti 等人	$17,836,000
Peck Madigan Jones  佩克·马迪根·琼斯	$17,150,000
Van Scoyoc Assoc  范斯科约克协会	$17,130,000
Crossroads Strategies  十字路口战略	$16,550,000
Cassidy & Assoc  卡西迪及合伙人	$16,430,000
Covington & Burling  科文顿和柏灵	$16,340,000
American Continental Group
美国大陆集团	$15,000,000
Alpine Group  阿尔卑斯集团	$14,600,000
Subject Matter  主题	$14,550,000
Table 10.1 This table lists the top twenty U.S. lobbying firms in 2020 as determined by total lobbying income.44
表 10.1 本表列出了 2020 年美国游说收入排名前二十的游说公司，排名依据为游说总收入 。44
We have also seen greater limits on inside lobbying activities. In the past, many lobbyists were described as “good ol’ boys” who often provided gifts or other favors in exchange for political access or other considerations. Today, restrictions limit the types of gifts and benefits lobbyists can bestow on lawmakers. There are certainly fewer “good ol’ boy” lobbyists, and many lobbyists are now full-time professionals. The regulation of lobbying is addressed in greater detail below.

[.my2]
我们也看到对内部游说活动的限制更加严格。过去，许多游说者被形容为“老好人”，他们经常赠送礼物或其他好处，以换取政治关系或其他利益。如今，各种限制措施约束了游​​说者可以向立法者赠送的礼物和利益类型。当然，“老好人”游说者的数量也减少了，许多游说者现在都是全职的专业人士。下文将更详细地探讨游说监管问题。

HOW REPRESENTATIVE IS THE INTEREST GROUP SYSTEM?
利益集团体系的代表性如何？
Participation in the United States has never been equal; wealth and education, components of socioeconomic status, are strong predictors of political engagement.45 We already discussed how wealth can help overcome collective action problems, but lack of wealth also serves as a barrier to participation more generally. These types of barriers pose challenges, making it less likely for some groups than others to participate.46 Some institutions, including large corporations, are more likely to participate in the political process than others, simply because they have tremendous resources. And with these resources, they can write a check to a political campaign or hire a lobbyist to represent their organization. Writing a check and hiring a lobbyist are unlikely options for a disadvantaged group (Figure 10.10).

[.my2]
在美国，政治参与从来都不是平等的；财富和教育作为社会经济地位的组成部分，是政治参与的重要预测指标。 45 我们已经讨论过财富如何帮助克服集体行动困境，但缺乏财富本身也是普遍存在的政治参与障碍。这类障碍构成挑战，使得某些群体比其他群体更难参与政治。 46 一些机构，包括大型企业，比其他机构更有可能参与政治进程，仅仅是因为它们拥有雄厚的资源。凭借这些资源，它们可以向政治竞选捐款或聘请游说者代表其组织。而对于弱势群体来说，捐款和聘请游说者几乎是不可能的（ 图 10.10 ）。

An image of a crowd of people, one of whom holds a sign that reads “Why am I here? Ask my lobbyist”.

[.my2]
Figure 10.10 A protestor at an Occupy Times Square rally in October 2011. (credit: Geoff Stearns)
图 10.10 2011 年 10 月，一名抗议者在占领时代广场的集会上。（图片来源：Geoff Stearns）
Individually, people living in poverty may not have the same opportunities to join groups.47 They may work two jobs to make ends meet and lack the free time necessary to participate in politics. Further, there are often financial barriers to participation. For someone who punches a time-clock, spending time with political groups may be costly and paying dues may be a hardship. Certainly, the poor are unable to hire expensive lobbying firms to represent them. Structural barriers like voter identification laws may also disproportionately affect people with low socioeconomic status, although the effects of these laws may not be fully understood for some time.

[.my2]
就个人而言，生活在贫困中的人可能没有同等的机会加入各种团体。 47 他们可能为了维持生计而身兼两职，缺乏参与政治所需的空闲时间。此外，参与政治往往面临经济障碍。对于朝九晚五的上班族来说，参与政治团体活动可能成本高昂，缴纳会费也可能成为一种负担。当然，穷人也无力聘请昂贵的游说公司来代表他们。诸如选民身份识别法之类的结构性障碍也可能对社会经济地位较低的人群造成不成比例的影响，尽管这些法律的影响可能还需要一段时间才能完全显现。

The poor may also have low levels of efficacy, which refers to the conviction that you can make a difference or that government cares about you and your views. People with low levels of efficacy are less likely to participate in politics, including voting and joining interest groups. Therefore, they are often underrepresented in the political arena.

[.my2]
贫困人群的效能感也可能较低，这指的是他们缺乏对自身能力的信心，不相信自己能够有所作为，或者不相信政府会关心自己和自己的观点。效能感低的人参与政治的可能性较小，包括投票和加入利益集团。因此，他们在政治领域往往缺乏代表性。

People in certain racial and ethnic populations may also participate less often than the majority population, although when we control for wealth and education levels, we see fewer differences in participation rates. Still, there is a bias in participation and representation, and this bias extends to interest groups as well. For example, when fast food workers across the United States went on strike to demand an increase in their wages, they could do little more than take to the streets bearing signs, like the protestors shown in Figure 10.11. Their opponents, the owners of restaurant chains and others who pay their employees minimum wage, could hire groups such as the Employment Policies Institute, which paid for billboard ads in Times Square in New York City. The billboards implied that raising the minimum wage was an insult to people who worked hard and discouraged people from getting an education to better their lives.48
某些种族和族裔群体参与政治的频率可能低于多数群体，但当我们控制财富和教育水平等因素后，参与率的差异就会缩小。尽管如此，参与和代表性方面仍然存在偏见，这种偏见也延伸到了利益集团。例如，当美国各地的快餐店员工举行罢工要求提高工资时，他们能做的只是像图 10.11 中所示的抗议者那样，走上街头举着标语。而他们的对手，那些支付员工最低工资的连锁餐厅老板和其他企业主，则可以雇佣像就业政策研究所这样的组织，在纽约时代广场投放广告牌。这些广告牌暗示，提高最低工资是对辛勤工作的人的侮辱，并且会阻碍人们接受教育以改善生活。 48

An image of a group of people marching down a street, one of whom holds a sign that reads “I’m not loving’ poverty wages”.

[.my2]
Figure 10.11 Unlike their opponents, these minimum-wage workers in Minnesota have limited ways to make their interests known to government. However, they were able to increase their political efficacy by joining fast food workers in a nationwide strike on April 15, 2015, to call for a $15 per hour minimum wage and improved working conditions. (credit: “Fibonacci Blue”/Flickr)
图 10.11 与他们的反对者不同，明尼苏达州的这些最低工资劳动者向政府表达诉求的途径有限。然而，他们通过加入 2015 年 4 月 15 日举行的全国性快餐店工人罢工，呼吁将最低工资提高到每小时 15 美元并改善工作条件，从而增强了自身的政治影响力。（图片来源：“Fibonacci Blue”/Flickr）
Finally, people do not often participate because they lack the political skill to do so or believe that it is impossible to influence government actions.49 They might also lack interest or could be apathetic. Participation usually requires some knowledge of the political system, the candidates, or the issues. Younger people in particular are often cynical about government’s response to the needs of non-elites.

[.my2]
最后，人们不参与政治往往是因为他们缺乏相关的政治技巧，或者认为无法影响政府行为。 49 他们也可能缺乏兴趣或漠不关心。参与政治通常需要对政治体制、候选人或相关议题有一定的了解。尤其年轻人往往对政府如何回应非精英阶层的需求持怀疑态度。

How do these observations translate into the way different interests are represented in the political system? Some pluralist scholars like David Truman suggest that people naturally join groups and that there will be a great deal of competition for access to decision-makers.50 Scholars who subscribe to this pluralist view assume this competition among diverse interests is good for democracy. Political theorist Robert Dahl argued that “all active and legitimate groups had the potential to make themselves heard.”51 In many ways, this is an optimistic assessment of representation in the United States.

[.my2]
这些观察结果如何转化为不同利益在政治体系中的体现？一些多元主义学者，例如戴维·特鲁曼，认为人们自然而然地会加入各种群体，并且会存在激烈的竞争，以争取与决策者接触的机会。 50 持这种多元主义观点的学者认为，不同利益群体之间的这种竞争有利于民主。政治理论家罗伯特·达尔认为，“所有活跃且合法的群体都有可能发出自己的声音。” 51 在许多方面，这都是对美国代表性的一种乐观评估。

However, not all scholars accept the premise that mobilization is natural and that all groups have the potential for access to decision-makers. The elite critique suggests that certain interests, typically businesses and the wealthy, are advantaged and that policies more often reflect their wishes than anyone else’s. Political scientist E. E. Schattschneider noted that “the flaw in the pluralist heaven is that the heavenly chorus sings with a strong upperclass accent.”52 A number of scholars have suggested that businesses and other wealthy interests are often overrepresented before government, and that poorer interests are at a comparative disadvantage.53 For example, as we’ve seen, wealthy corporate interests have the means to hire in-house lobbyists or high-priced contract lobbyists to represent them. They can also afford to make financial contributions to politicians, which at least may grant them access. The ability to overcome collective action problems is not equally distributed across groups; as Mancur Olson noted, small groups and those with economic advantages were better off in this regard.54 Disadvantaged interests face many challenges including shortages of resources, time, and skills.

[.my2]
然而，并非所有学者都认同动员是自然而然的，以及所有群体都有可能接触到决策者的前提。 精英批判指出，某些利益集团，通常是企业和富人，享有优势，政策往往更多地反映他们的意愿而非其他任何人的意愿。政治学家 E.E. Schattschneider 指出，“多元主义理想中的缺陷在于，天籁之音带有浓重的上层阶级口音。” 52 许多学者认为，企业和其他富裕利益集团在政府面前往往拥有过多的代表权，而贫困利益集团则处于相对劣势。 53 例如，正如我们所见，富有的企业利益集团有能力聘请内部游说人员或高价合同游说人员来代表他们。他们也能够向政客捐款，这至少可以让他们获得一些接触机会。克服集体行动困境的能力并非在所有群体中均等分配；正如 Mancur Olson 所指出的，小群体和拥有经济优势的群体在这方面更有优势。 54 弱势群体面临诸多挑战，包括资源、时间和技能的短缺。

A study of almost eighteen hundred policy decisions made over a twenty-year period revealed that the interests of the wealthy have much greater influence on the government than those of average citizens. The approval or disapproval of proposed policy changes by average voters had relatively little effect on whether the changes took place. When wealthy voters disapproved of a particular policy, it almost never was enacted. When wealthy voters favored a particular policy, the odds of the policy proposal’s passing increased to more than 50 percent.55 Indeed, the preferences of those in the top 10 percent of the population in terms of income had an impact fifteen times greater than those of average income. In terms of the effect of interest groups on policy, Gilens and Page found that business interest groups had twice the influence of public interest groups.56
一项对近 1800 项政策决策（历时 20 年）的研究表明，富人的利益对政府的影响力远大于普通民众。普通选民对政策变更提案的赞成或反对，对政策变更的最终实施影响甚微。而当富裕选民反对某项政策时，该政策几乎从未获得通过。当富裕选民支持某项政策时，该政策提案获得通过的概率则超过 50%。 55 事实上，收入排名前 10%的人群的偏好对政策的影响是平均收入人群的 15 倍。关于利益集团对政策的影响，吉伦斯和佩奇的研究发现，商业利益集团的影响力是公共利益集团的两倍。 56

Figure 10.12 shows contributions by interests from a variety of different sectors. We can draw a few notable observations from the table. First, large sums of money are spent by different interests. Second, many of these interests are business sectors, including the real estate sector, the insurance industry, businesses, and law firms.

[.my2]
图 10.12 显示了来自不同领域的各种利益相关方的贡献。我们可以从表中得出几个值得注意的结论。首先，不同利益相关方都投入了大量资金。其次，这些利益相关方中有很多是商业领域，包括房地产行业、保险业、企业和律师事务所。

An image of a table titled “Business sector total donation to Parties and Candidates, 2019-2020”. The table has three columns and 13 rows. From left to right, the rows read “Defense: $46,077,036, 46.1% Democrat, 48.7% Republican”, “Transportation: $147,406,861, 33.7% Democrat, 60.9% Republican”, “Agribusiness: $193,001,307, 24.1% Democrat, 49.0% Republican”, “Construction: $202,086,321, 29.4% Democrat, 60.4% Republican”, “Energy and Natural Resources: $220,122,039, 19.8% Democrat, 45.8% Republican”, “Labor: $259,296,967, 27.5% Democrat, 3.6% Republican”, “Lawyers and Lobbyists: $377,299,670, 73.4% Democrat, 20.7% Republican”, “Communications and Electronics: $619,808,386, 56.4% Democrat, 13.2% Republican”, “Health: $639,636,897, 44.8% Democrat, 25.8% Republican”, “Misc. Business: $837,233,334, 43.6% Democrat, 42.7% Republican”, “Ideology/Single-Issue: $1,680,399,488, 38.2% Democrat, 16.9% Republican”, “Finance, Insurance, and Real Estate: $1,946,712,833, 26.5% Democrat, 23.9% Republican”. “Other: $2,471,996,960, 43.6% Democrat, 42.7% Republican”, At the bottom of the table, a source is listed: “Center for Responsive Politics. “Sector totals, 2019-2020”. March 22, 2021.”.

[.my2]
Figure 10.12 The chart above shows the dollar amounts contributed from the business sector to Democratic (blue) and Republican (red) federal candidates and political parties during the 2019-2020 election cycle, as reported to the Federal Election Commission.

[.my2]
图 10.12 上图显示了在 2019-2020 年选举周期中，商业部门向民主党（蓝色）和共和党（红色）联邦候选人和政党捐赠的美元金额，数据来自联邦选举委员会的报告。
Interest group politics are often characterized by whether the groups have access to decision-makers and can participate in the policy-making process. The iron triangle is a hypothetical arrangement among three elements (the corners of the triangle): an interest group, a congressional committee member or chair, and an agency within the bureaucracy.57 Each element has a symbiotic relationship with the other two, and it is difficult for those outside the triangle to break into it. The congressional committee members, including the chair, rely on the interest group for campaign contributions and policy information, while the interest group needs the committee to consider laws favorable to its view. The interest group and the committee need the agency to implement the law, while the agency needs the interest group for information and the committee for funding and autonomy in implementing the law.58
利益集团政治的特征往往在于这些集团能否接触到决策者并参与政策制定过程。“ 铁三角” 是三个要素（三角形的三个顶点）之间的一种假想关系：利益集团、国会委员会成员或主席以及官僚机构中的一个部门。 57 每个要素都与其他两个要素存在共生关系，三角之外的势力很难融入其中。国会委员会成员（包括主席）依赖利益集团提供竞选捐款和政策信息，而利益集团则需要委员会审议有利于其利益的法律。利益集团和委员会需要该部门来执行法律，而该部门则需要利益集团提供信息，并需要委员会提供资金和执行法律的自主权。 58

An alternate explanation of the arrangement of duties carried out in a given policy area by interest groups, legislators, and agency bureaucrats is that these actors are the experts in that given policy area. Hence, perhaps they are the ones most qualified to process policy in the given area. Some view the iron triangle idea as outdated. Hugh Heclo of George Mason University has sketched a more open pattern he calls an issue network that includes a number of different interests and political actors that work together in support of a single issue or policy.59
另一种解释是，利益集团、立法者和政府机构官员在特定政策领域内职责分工的原因是，这些参与者都是该领域的专家。因此，他们或许是最有资格处理该领域政策的人。有些人认为“铁三角”理论已经过时。乔治·梅森大学的休·赫克洛（Hugh Heclo）提出了一种更为开放的模式，他称之为“ 议题网络” ，其中包含许多不同的利益集团和政治参与者，他们为了支持某个单一议题或政策而共同合作。 59

Some interest group scholars have studied the relationship among a multitude of interest groups and political actors, including former elected officials, the way some interests form coalitions with other interests, and the way they compete for access to decision-makers.60 Some coalitions are long-standing, while others are temporary. Joining coalitions does come with a cost, because it can dilute preferences and split potential benefits that the groups attempt to accrue. Some interest groups will even align themselves with opposing interests if the alliance will achieve their goals. For example, left-leaning groups might oppose a state lottery system because it disproportionately hurts the poor (who participate in this form of gambling at higher rates), while right-leaning groups might oppose it because they view gambling as a sinful activity. These opposing groups might actually join forces in an attempt to defeat the lottery.

[.my2]
一些利益集团研究学者研究了众多利益集团与政治行为者（包括前任民选官员）之间的关系，以及某些利益集团如何与其他利益集团结盟，以及它们如何竞争接触决策者。 60 有些联盟长期存在，而有些则是暂时的。加入联盟并非没有代价，因为它会稀释各方的偏好，并瓜分各集团试图获取的潜在利益。如果结盟能够实现自身目标，一些利益集团甚至会与对立的利益集团结盟。例如，左倾团体可能反对州彩票系统，因为它对穷人（他们参与这种赌博形式的比例更高）的伤害尤为严重；而右倾团体可能反对它，因为他们认为赌博是一种罪恶的行为。这些对立的团体实际上可能会联手阻止彩票的实施。

While most scholars agree that some interests do have advantages, others have questioned the overwhelming dominance of certain interests. Additionally, neopluralist scholars argue that certainly some interests are in a privileged position, but these interests do not always get what they want.61 Instead, their influence depends on a number of factors in the political environment such as public opinion, political culture, competition for access, and the relevance of the issue. Even wealthy interests do not always win if their position is at odds with the wish of an attentive public. And if the public cares about the issue, politicians may be reluctant to defy their constituents. If a prominent manufacturing firm wants fewer regulations on environmental pollutants, and environmental protection is a salient issue to the public, the manufacturing firm may not win in every exchange, despite its resource advantage. We also know that when interests mobilize, opposing interests often counter-mobilize, which can reduce advantages of some interests. Thus, the conclusion that businesses, the wealthy, and elites win in every situation is overstated.62
尽管大多数学者认同某些利益集团确实拥有优势，但也有人质疑某些利益集团的绝对主导地位。此外， 新多元主义学者认为，诚然，某些利益集团处于特权地位，但这些利益集团并非总能如愿以偿。 61 相反，它们的影响力取决于政治环境中的诸多因素，例如公众舆论、政治文化、资源竞争以及议题的相关性。即使是财力雄厚的利益集团，如果其立场与关注此事的公众的意愿相悖，也并非总能获胜。如果公众关心某个议题，政治家可能不愿违背选民的意愿。例如，如果一家知名制造企业希望减少对环境污染物的监管，而环境保护又是公众关注的焦点，那么即使这家制造企业拥有资源优势，也未必每次都能胜出。我们还知道，当利益集团动员起来时，对立的利益集团往往会进行反动员，这会削弱某些利益集团的优势。因此，认为企业、富人和精英在任何情况下都能获胜的结论是言过其实的。 62

A good example is the recent dispute between fast food chains and their employees. During the spring of 2015, workers at McDonald’s restaurants across the country went on strike and marched in protest of the low wages the fast food giant paid its employees. Despite the opposition of restaurant chains and claims by the National Restaurant Association that increasing the minimum wage would result in the loss of jobs, in September 2015, the state of New York raised the minimum wage for fast food employees to $15 per hour, an amount to be phased in over time. Buoyed by this success, fast food workers in other cities continued to campaign for a pay increase, and many low-paid workers have promised to vote for politicians who plan to boost the federal minimum wage.63 While the goal of a nationwide $15 minimum wage has not yet been realized, two developments demonstrate significant progress in that direction. First, since 2014, twenty-eight states and the District of Columbia have raised their state-level minimum wage above the federal level, as have forty-five cities. Second, in April 2021, President Biden issued an executive order to raise the minimum wage of federal contractors to $15 per hour.64
近期快餐连锁店与其员工之间的纠纷就是一个很好的例子。2015 年春季，麦当劳在全国各地的员工举行罢工和游行，抗议这家快餐巨头支付给员工的低工资。尽管连锁餐厅反对，全国餐饮协会也声称提高最低工资会导致失业，但纽约州在 2015 年 9 月将快餐员工的最低工资提高到每小时 15 美元，并计划分阶段实施。受此鼓舞，其他城市的快餐员工继续争取加薪，许多低收入工人承诺会投票支持那些计划提高联邦最低工资的政客。 63 虽然全国 15 美元最低工资的目标尚未实现，但两项进展表明，朝着这个方向已经取得了显著进展。首先，自 2014 年以来，已有 28 个州和哥伦比亚特区以及 45 个城市将州级最低工资提高到高于联邦水平。其次，2021 年 4 月，拜登总统发布行政命令，将联邦承包商的最低工资提高到每小时 15 美元 。64

Link to Learning  学习链接
Visit the websites for the California or Michigan secretary of state, state boards of elections, or relevant governmental entity and ethics websites where lobbyists and interest groups must register. Several examples are provided but feel free to examine the comparable web page in your own state. Spend some time looking over the lists of interest groups registered in these states. Do the registered interests appear to reflect the important interests within the states? Are there patterns in the types of interests registered? Are certain interests over- or underrepresented?
访问加利福尼亚州或密歇根州州务卿办公室、州选举委员会或相关政府机构和道德规范网站，游说者和利益集团必须在这些网站上注册。文中提供了一些示例，但您也可以查看您所在州的类似网页。花些时间浏览这些州注册的利益集团名单。这些注册的利益集团是否反映了各州的重要利益？注册的利益集团类型是否存在某种模式？是否存在某些利益集团过度代表或代表不足的情况？


'''