
= 002-5 Constitutional Change 宪法变更
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




Not all the business of Congress involves bickering, political infighting, government shutdowns, and Machiavellian maneuvering. Congress does actually get work done. Traditionally, it does this work in a very methodical way. In this section, we will explore how Congress functions at the leadership and committee levels. We will learn how the party leadership controls their conferences and how the many committees within Congress create legislation that can then be moved forward or die on the floor.

[.my2]
国会的运作并非全是争吵、政治内斗、政府停摆和尔虞我诈。国会实际上确实在做事。传统上，国会以非常严谨的方式开展工作。在本节中，我们将探讨国会在领导层和委员会层面的运作方式。我们将了解各党派领导层如何掌控党代会，以及国会下属的众多委员会如何制定法案，这些法案最终能否获得通过或胎死腹中。

PARTY LEADERSHIP  党领导层
The party leadership in Congress controls the actions of Congress. Leaders are elected by the two-party conferences in each chamber. In the House of Representatives, these are the House Democratic Conference and the House Republican Conference. These conferences meet regularly and separately not only to elect their leaders but also to discuss important issues and strategies for moving policy forward. Based on the number of members in each conference, one conference becomes the majority conference and the other becomes the minority conference. Independents like Senator Bernie Sanders will typically join one or the other major party conference, as a matter of practicality and often based on ideological affinity. Without the membership to elect their own leadership, independents would have a very difficult time getting things done in Congress unless they had a relationship with the leaders.

[.my2]
国会的政党领导层掌控着国会的运作。两院的党派代表大会分别选举产生领导人。在众议院，这两个代表大会分别是众议院民主党代表大会和众议院共和党代表大会。这两个代表大会定期单独召开会议，不仅选举各自的领导人，还讨论推进政策的重要议题和策略。根据各自代表大会的成员人数，一个代表大会成为多数党代表大会，另一个则成为少数党代表大会。像参议员伯尼·桑德斯这样的独立人士通常会出于实际考虑，并且往往基于意识形态上的契合，加入其中一个主要政党代表大会。如果没有足够的成员来选举自己的领导人，除非与领导人建立良好的关系，否则独立人士在国会很难有所作为。

Despite the power of the conferences, however, the most important leadership position in the House is actually elected by the entire body of representatives. This position is called the Speaker of the House and is the only House officer mentioned in the Constitution. The Constitution does not require the Speaker to be a member of the House, although to date, all fifty-four Speakers have been. The Speaker is the presiding officer, the administrative head of the House, the partisan leader of the majority party in the House, and an elected representative of a single congressional district (Figure 11.16). As a testament to the importance of the Speaker, since 1947, the holder of this position has been second in line to succeed the president in an emergency, after the vice president.

[.my2]
尽管各届联席会议权力巨大，但众议院最重要的领导职位实际上是由全体众议员选举产生的。这个职位被称为众议院议长 ，也是宪法中唯一提及的众议院官员。宪法并未规定议长必须是众议院议员，但迄今为止，所有 54 位议长都是众议院议员。议长主持会议，是众议院的行政首脑，是众议院多数党的党派领袖，也是单一国会选区的民选代表（ 图 11.16 ）。为了体现议长的重要性，自 1947 年以来，在紧急情况下，议长是继副总统之后，总统的第二顺位继任者。

Photo A shows John Thune. Photo B shows Mike Johnson.

[.my2]
Figure 11.16 Republican John Thune of South Dakota (a), the majority leader in the Senate, and Republican Mike Johnson of Louisiana (b), the Speaker of the House, are the most powerful congressional leaders in their respective chambers. (credit a: "John Thune official photo" Press Kit, John Thune, US Senator for South Dakota, by United States Senate; credit b: "Mike Johnson official photo” Meet Mike Johnson, Speaker of the House of Representatives, by United States House of Representatives)
图 11.16 南达科他州共和党参议员约翰·图恩（John Thune）（a）是参议院多数党领袖，路易斯安那州共和党参议员迈克·约翰逊（Mike Johnson）（b）是众议院议长，他们分别是各自议院中最有权势的国会领袖。（图片来源：a：“约翰·图恩官方照片”，美国参议院新闻资料包，约翰·图恩，南达科他州参议员；图片来源：b：“迈克·约翰逊官方照片”，认识迈克·约翰逊，众议院议长，美国众议院）
The Speaker serves until their party loses, or until the Speaker is voted out of the position or chooses to step down. Republican Speaker John Boehner became the latest Speaker to walk away from the position when it appeared his position was in jeopardy. This event shows how the party conference (or caucus) oversees the leadership as much as, if not more than, the leadership oversees the party membership in the chamber. The Speaker is invested with quite a bit of power, such as the ability to assign bills to committees and decide when a bill will be presented to the floor for a vote. The Speaker also rules on House procedures, often delegating authority for certain duties to other members. He or she appoints members and chairs to committees, creates select committees to fulfill a specific purpose and then disband, and can even select a member to be speaker pro tempore, who acts as Speaker in the Speaker’s absence. Finally, when the Senate joins the House in a joint session, the Speaker presides over these sessions, because they are usually held in the House of Representatives.

[.my2]
议长任期至其所在党派败选、议长被选举下台或选择辞职为止。共和党籍议长约翰·博纳是最新一位在地位岌岌可危时主动辞职的议长。这一事件表明，党团会议（或党团会议）对领导层的监督作用，即便不比领导层对议会成员的监督作用更大，也至少与领导层对议会成员的监督作用相当。议长拥有相当大的权力，例如可以将法案分配给各个委员会，并决定何时将法案提交全体会议进行表决。议长还负责制定众议院的议事规则，并经常将某些职责的权力委托给其他议员。议长任命委员会成员和主席，设立专门委员会以完成特定任务，并在任务结束后解散这些委员会，甚至可以指定一名议员担任临时议长，在议长缺席时代理议长职务。最后，当参议院与众议院举行联席会议时，由于联席会议通常在众议院举行，因此由议长主持会议。

Below the Speaker, the majority and minority conferences each elect two leadership positions arranged in hierarchical order. At the top of the hierarchy are the floor leaders of each party. These are generally referred to as the majority and minority leaders. The minority leader has a visible if not always a powerful position. As the official leader of the opposition, they technically hold the rank closest to that of the Speaker, makes strategy decisions, and attempts to keep order within the minority. However, the majority rules the day in the House, like a cartel. On the majority side, because it holds the speakership, the majority leader also has considerable power. Historically, moreover, the majority leader tends to be in the best position to assume the speakership when the current Speaker steps down.

[.my2]
在议长之下，多数党和少数党会议分别选举两个领导职位，并按层级排列。层级顶端是各党的议会领袖，通常被称为多数党领袖和少数党领袖。 少数党领袖的地位虽然并非总是举足轻重，但却十分显眼。作为反对党的正式领袖，其级别在名义上最接近议长，负责制定战略决策，并努力维持少数党内部的秩序。然而，多数党在议会中拥有绝对的主导权，如同一个垄断集团。由于多数党掌握着议长职位， 其领袖也拥有相当大的权力。此外，从历史经验来看，多数党领袖往往是现任议长卸任时最有可能接任议长一职的人选。

Below these leaders are the two party’s respective whips. A whip’s job, as the name suggests, is to whip up votes and otherwise enforce party discipline. Whips make the rounds in Congress, telling members the position of the leadership and the collective voting strategy, and sometimes they wave various carrots and sticks in front of recalcitrant members to bring them in line. The remainder of the leadership positions in the House include a handful of chairs and assistantships.

[.my2]
在这些领导人之下是两党的党鞭 。顾名思义，党鞭的职责是动员议员投票，并以其他方式维护党纪。党鞭在国会中奔走，向议员们传达领导层的立场和集体投票策略，有时还会对不服从的议员使用各种软硬兼施的手段，以迫使他们服从。众议院的其他领导职位包括一些主席和助理职位。

Like the House, the Senate also has majority and minority leaders and whips, each with duties very similar to those of their counterparts in the House. Unlike the House, however, the Senate doesn’t have a Speaker. The duties and powers held by the Speaker in the House fall to the majority leader in the Senate. Another difference is that, according to the U.S. Constitution, the Senate’s president is actually the elected vice president of the United States, but may vote only in case of a tie. Apart from this and very few other exceptions, the president of the Senate does not actually operate in the Senate. Instead, the Constitution allows for the Senate to choose a president pro tempore—usually the most senior senator of the majority party—who presides over the Senate. Despite the title, the job is largely a formal and powerless role. The real power in the Senate is in the hands of the majority leader (Figure 11.16) and the minority leader. Like the Speaker of the House, the majority leader is the chief spokesperson for the majority party, but, unlike in the House, does not run the floor alone. Because of the traditions of unlimited debate and the filibuster, the majority and minority leaders often occupy the floor together in an attempt to keep things moving along. At times, their interactions are intense and partisan, but for the Senate to get things done, they must cooperate to get the sixty votes needed to run this super-majority legislative institution.

[.my2]
与众议院一样，参议院也设有多数党领袖、少数党领袖和党鞭，他们的职责与众议院的相应职位非常相似。然而，与众议院不同的是，参议院没有议长。众议院议长的职责和权力在参议院由多数党领袖行使。另一个区别是，根据美国宪法，参议院议长实际上是美国当选的副总统，但只有在出现平局时才能投票。除了这一点以及极少数其他例外情况外，参议院议长实际上并不在参议院行使职权。宪法允许参议院选举一位临时议长 ——通常是多数党中最资深的参议员——来主持参议院的会议。尽管有这个头衔，但这个职位在很大程度上只是一个形式上的、没有实权的角色。参议院的真正权力掌握在多数党领袖（ 图 11.16 ）和少数党领袖手中。与众议院议长一样，多数党领袖是多数党的首席发言人，但与众议院不同的是，他不能独自主持参议院的会议。由于参议院保留了无限辩论和阻挠议事的传统，多数党领袖和少数党领袖经常共同占据议事厅，以推动议事进程。有时，他们的互动激烈且带有党派色彩，但为了使参议院能够顺利完成各项工作，他们必须合作，以获得维持这一超级多数立法机构运转所需的六十票。

THE COMMITTEE SYSTEM  委员会制度
With 535 members in Congress and a seemingly infinite number of domestic, international, economic, agricultural, regulatory, criminal, and military issues to deal with at any given moment, the two chambers must divide their work based on specialization. Congress does this through the committee system. Specialized committees (or subcommittees) in both the House and the Senate are where bills originate and most of the work that sets the congressional agenda takes place. Committees are roughly approximate to a bureaucratic department in the executive branch. There are well over two hundred committees, subcommittees, select committees, and joint committees in the Congress. The core committees are called standing committees. There are twenty standing committees in the House and sixteen in the Senate (Table 11.2).

[.my2]
国会共有 535 名议员，需要处理的国内、国际、经济、农业、监管、刑事和军事问题似乎无穷无尽，因此参众两院必须根据专业领域划分工作。国会通过委员会制度来实现这一点。众议院和参议院的专门委员会（或小组委员会）是法案的发起地，也是制定国会议程的主要场所。委员会大致相当于行政部门的官僚机构。国会共有两百多个委员会、小组委员会、特别委员会和联合委员会。核心委员会被称为常设委员会 。 众议院有 20 个常设委员会，参议院有 16 个（ 表 11.2 ）。

Congressional Standing and Permanent Select Committees
国会常设委员会和常设特别委员会
House of Representatives
众议院	Senate  参议院
Agriculture  农业	Agriculture, Nutrition, and Forestry
农业、营养和林业
Appropriations  拨款	Appropriations  拨款
Armed Services  武装部队	Armed Services  武装部队
Budget  预算	Banking, Housing, and Urban Affairs
银行、住房和城市事务
Education and Labor  教育和劳动	Budget  预算
Energy and Commerce  能源与商业	Commerce, Science, and Transportation
商业、科学和交通运输
Ethics  伦理	Energy and Natural Resources
能源和自然资源
Financial Services  金融服务	Environment and Public Works
环境与公共工程
Foreign Affairs  外交	Ethics (select)  伦理（选择）
Homeland Security  国土安全部	Finance  金融
House Administration  众议院行政部门	Foreign Relations  外交关系
Intelligence (select)  智力（选择）	Health, Education, Labor and Pensions
卫生、教育、劳工和养老金
Judiciary  司法	Homeland Security and Governmental Affairs
国土安全和政府事务
Natural Resources  自然资源	Indian Affairs  印度事务
Oversight and Reform  监督与改革	Intelligence (select)  智力（选择）
Rules  规则	Judiciary  司法
Science, Space, and Technology
科学、空间和技术	Rules and Administration
规则与管理
Small Business  小型企业	Small Business and Entrepreneurship
小型企业和创业
Transportation and Infrastructure
交通运输和基础设施	Veterans’ Affairs  退伍军人事务部
Veterans’ Affairs  退伍军人事务部
Ways and Means  途径和方法
Table 11.2
表 11.2
Members of both parties compete for positions on various committees. These positions are typically filled by majority and minority members to roughly approximate the ratio of majority to minority members in the respective chambers, although committees are chaired by members of the majority party. Committees and their chairs have a lot of power in the legislative process, including the ability to stop a bill from going to the floor (the full chamber) for a vote. Indeed, most bills die in committee. But when a committee is eager to develop legislation, it takes a number of methodical steps. It will reach out to relevant agencies for comment on resolutions to the problem at hand, such as by holding hearings with experts to collect information. In the Senate, committee hearings are also held to confirm presidential appointments (Figure 11.17). After the information has been collected, the committee meets to discuss amendments and legislative language. Finally, the committee will send the bill to the full chamber along with a committee report. The report provides the majority opinion about why the bill should be passed, a minority view to the contrary, and estimates of the proposed law’s cost and impact.

[.my2]
两党成员竞相争取各委员会的席位。这些席位通常由多数党和少数党成员分别担任，以大致反映各议院多数党和少数党成员的比例，但委员会主席由多数党成员担任。委员会及其主席在立法程序中拥有很大的权力，包括阻止法案提交全体会议（即全体议院）进行表决。事实上，大多数法案最终都止步于委员会阶段。但当委员会积极推进立法时，它会采取一系列有条不紊的步骤。例如，它会联系相关机构，就当前问题的解决方案征求意见，比如举行专家听证会收集信息。在参议院，委员会还会举行听证会来确认总统的任命（ 图 11.17 ）。收集完信息后，委员会会召开会议讨论修正案和立法措辞。最后，委员会会将法案连同委员会报告一起提交全体议院。该报告会阐述多数党关于法案应予通过的意见、少数党反对的意见，以及对拟议法律的成本和影响的评估。

A photo of Amy Coney Barrett.

[.my2]
Figure 11.17 In 2017, Supreme Court justice Amy Coney Barrett had her confirmation hearings before the U.S. Senate Committee on the Judiciary. The Senate Judiciary Committee is one of the oldest of the sixteen standing committees in the Senate. (credit: modification of work from C-SPAN, Public Domain)
图 11.17 2017 年，美国最高法院大法官艾米·科尼·巴雷特在美国参议院司法委员会举行了确认听证会。参议院司法委员会是参议院十六个常设委员会中最古老的委员会之一。（图片来源：改编自 C-SPAN 的作品，公共领域）
Four types of committees exist in the House and the Senate. The first is the standing, or permanent, committee. This committee is the first call for proposed bills, fewer than 10 percent of which are reported out of committee to the floor. The second type is the joint committee. Joint committee members are appointed from both the House and the Senate, and are charged with exploring a few key issues, such as the economy and taxation. However, joint committees have no bill-referral authority whatsoever—they are informational only. A conference committee is used to reconcile different bills passed in both the House and the Senate. The conference committees are appointed on an ad hoc basis as necessary when a bill passes the House and Senate in different forms. Conference committees are sometimes skipped in the interest of expedience, in which one of the chambers relents to the other chamber. For example, the House demurred to the Senate over the Affordable Care Act instead of going to battle in a conference committee. Still, conference committees are the norm on most major pieces of legislation. A recent example is the Tax Cuts and Jobs Act of 2017, passed in December. Finally, ad hoc, special, or select committees are temporary committees set up to address specific topics. These types of committees often conduct special investigations, such as on aging or ethics.

[.my2]
众议院和参议院共有四种类型的委员会。第一种是常设委员会，也称为永久委员会。该委员会负责对提案进行初步审议，但最终只有不到 10%的提案能够提交全体会议审议。第二种是联合委员会 。联合委员会成员由众议院和参议院共同任命，负责探讨一些关键议题，例如经济和税收。然而，联合委员会没有任何提案权——它们仅提供信息。 协商委员会用于协调众议院和参议院通过的不同提案。当一项提案在众议院和参议院以不同形式通过时，协商委员会会根据需要临时成立。有时，为了方便起见，会省略协商委员会，即一方向另一方让步。例如，众议院在《平价医疗法案》的审议过程中，选择向参议院让步，而不是召开协商委员会。尽管如此，协商委员会仍然是大多数重要立法程序的惯例。最近的一个例子是 2017 年 12 月通过的《减税与就业法案》。最后，特设委员会、特别委员会或专门委员会是为处理特定议题而设立的临时委员会。这类委员会通常会开展专项调查，例如老龄化问题或伦理道德问题。

Committee hearings can become politically driven public spectacles. Consider the House Select Committee on Benghazi, the committee assembled by Republicans to further investigate the 2011 attacks on the U.S. Consulate in Benghazi, Libya. This prolonged investigation became particularly partisan as Republicans focused on then-secretary of state Hillary Clinton, who was running for the presidency at the time. In two multi-hour hearings in which Secretary Clinton was the only witness, Republicans tended to grandstand in the hopes of gaining political advantage or tripping her up, while Democrats tended to use their time to ridicule Republicans (Figure 11.18).36 In the end, the long hearings uncovered little more than the elevated state of partisanship in the House, which had scarcely been a secret before.

[.my2]
委员会听证会可能沦为政治作秀。以众议院班加西事件特别委员会为例，该委员会由共和党人组建，旨在进一步调查 2011 年美国驻利比亚班加西领事馆遇袭事件。这场旷日持久的调查变得尤为党派化，因为共和党人将矛头指向了当时正在竞选总统的国务卿希拉里·克林顿。在两场长达数小时的听证会上，克林顿国务卿是唯一的证人，共和党人倾向于作秀，希望从中获取政治利益或让她难堪，而民主党人则倾向于利用时间嘲讽共和党人（ 图 11.18 ）。 36 最终，漫长的听证会除了揭示众议院日益加剧的党派之争之外，几乎没有其他新发现，而这在之前几乎已是公开的秘密。

An image of several people seated behind a long wooden bench.

[.my2]
Figure 11.18 On October 22, 2015, former Secretary of State Hillary Clinton testified for the second time before the House Select Committee on Benghazi, answering questions from members for more than eight hours.

[.my2]
图 11.18 2015 年 10 月 22 日，前国务卿希拉里·克林顿第二次在众议院班加西事件特别委员会作证，回答了议员们的问题超过八个小时。
Members of Congress bring to their roles a variety of specific experiences, interests, and levels of expertise, and try to match these to committee positions. For example, House members from states with large agricultural interests will typically seek positions on the Agriculture Committee. Senate members with a background in banking or finance may seek positions on the Senate Finance Committee. Members can request these positions from their chambers’ respective leadership, and the leadership also selects the committee chairs.

[.my2]
国会议员们将各自不同的经验、兴趣和专业水平带入到各自的岗位中，并努力使这些优势与所担任的委员会职位相匹配。例如，来自农业利益攸关州的众议院议员通常会争取在农业委员会任职。拥有银行或金融背景的参议员可能会争取在参议院财政委员会任职。议员们可以向各自议院的领导层提出这些职位的申请，而委员会主席也由领导层选定。

Committee chairs are very powerful. They control the committee’s budget and choose when the committee will meet, when it will hold hearings, and even whether it will consider a bill (Figure 11.19). A chair can convene a meeting when members of the minority are absent or adjourn a meeting when things are not progressing as the majority leadership wishes. Chairs can hear a bill even when the rest of the committee objects. They do not remain in these powerful positions indefinitely, however. In the House, rules prevent committee chairs from serving more than six consecutive years and from serving as the chair of a subcommittee at the same time. A senator may serve only six years as chair of a committee but may, in some instances, also serve as a chair or ranking member of another committee.

[.my2]
委员会主席权力极大。他们掌控着委员会的预算，决定委员会何时开会、何时举行听证会，甚至决定是否审议某项法案（ 图 11.19 ）。主席可以在少数党成员缺席时召集会议，也可以在会议进展不如多数党领导层预期时宣布休会。即使委员会其他成员反对，主席也可以审议某项法案。然而，他们并非可以无限期地担任如此重要的职位。在众议院，规则规定委员会主席的任期不得超过六年，且不得同时担任小组委员会主席。参议员担任委员会主席的任期也仅限六年，但在某些情况下，他们也可以同时担任其他委员会的主席或资深成员。

Image A is of Chuck Grassley. Image B is of Merrick Garland and Susan Collins.

[.my2]
Figure   数字 11.19 In 2016, Republican Chuck Grassley of Iowa (a), the chair of the Senate Judiciary Committee, refused to hold hearings on the nomination of Merrick Garland to the Supreme Court, despite the urging of his committee colleagues. In the meantime, Garland met with numerous senators, such as Republican Susan Collins of Maine (b). As of Election Day, no hearings had been held, and Garland's nomination expired on January 3, 2017. Just ten days after his inauguration, Republican president Donald Trump announced his nomination of Neil Gorsuch to the Court. Gorsuch was confirmed in April 2017, despite a filibuster by the Democrats.

[.my2]
2016 年，爱荷华州共和党参议员查克 ·格拉斯利 （Chuck Grassley）（a）是参议院司法委员会主席，尽管委员会同僚敦促，他仍拒绝就梅里克 ·加兰（ Merrick Garland）的最高法院大法官提名举行听证会。与此同时，加兰会见了多位参议员，例如缅因州共和党参议员苏珊·柯林斯（Susan Collins）（b）。截至选举日，听证会仍未举行，加兰的提名于 2017 年 1 月 3 日失效。就职仅十天后，共和党总统唐纳德·特朗普宣布提名尼尔·戈萨奇（Neil Gorsuch）出任最高法院大法官。尽管遭到民主党人的阻挠，戈萨奇的提名最终于 2017 年 4 月获得确认。
Because the Senate is much smaller than the House, senators hold more committee assignments than House members. There are sixteen standing committees in the Senate, and each position must be filled. In contrast, in the House, with 435 members and only twenty standing committees, committee members have time to pursue a more in-depth review of a policy. House members historically defer to the decisions of committees, while senators tend to view committee decisions as recommendations, often seeking additional discussion that could lead to changes.

[.my2]
由于参议院的规模远小于众议院，参议员所担任的委员会职务也比众议员多。参议院设有十六个常设委员会，每个委员会都必须有人担任委员。相比之下，众议院拥有435名议员，却只有二十个常设委员会，这使得委员会成员有时间对政策进行更深入的审查。众议院议员历来尊重委员会的决定，而参议员则倾向于将委员会的决定视为建议，并经常寻求进一步的讨论，以期最终做出改变。

Link to Learning  学习链接
Take a look at the scores of committees in the House and Senate. The late House Speaker Tip O’Neill once quipped that if you didn’t know a new House member’s name, you could just call him Mr. Chairperson.

[.my2]
看看众议院和参议院里数不胜数的委员会吧。已故的众议院议长蒂普·奥尼尔曾打趣说，如果你不知道一位新上任的众议员的名字，你可以直接称呼他为“主席先生”。


'''