
= 012 The Presidency 总统职位
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


The presidency is the most visible position in the U.S. government (Figure 12.1). During the Constitutional Convention of 1787, delegates accepted the need to empower a relatively strong and vigorous chief executive. But they also wanted this chief executive to be bound by checks from the other branches of the federal government as well as by the Constitution itself. Over time, the power of the presidency has grown in response to circumstances and challenges. However, to this day, a president must still work with the other branches to be most effective. Unilateral actions, in which the president acts alone on important and consequential matters, such as President Barack Obama’s strategy on the Iran nuclear deal, are bound to be controversial and suggest potentially serious problems within the federal government. Effective presidents, especially in peacetime, are those who work with the other branches through persuasion and compromise to achieve policy objectives.

[.my2]
总统是美国政府中最引人注目的职位（ 图 12.1 ）。在 1787 年的制宪会议上，与会代表们一致认为有必要赋予一位相对强大且富有魄力的行政首脑权力。但他们也希望这位行政首脑受到联邦政府其他部门以及宪法本身的制约。随着时间的推移，总统的权力因形势和挑战而不断增长。然而，时至今日，总统仍然必须与其他部门合作才能发挥最大效力。总统单方面采取行动，即在重要且影响深远的事项上单独行事，例如奥巴马总统在伊朗核协议问题上的策略，必然会引发争议，并可能预示着联邦政府内部存在严重问题。高效的总统，尤其是在和平时期，会通过说服和妥协与其他部门合作，以实现政策目标。

What are the powers, opportunities, and limitations of the presidency? How does the chief executive lead in our contemporary political system? What guides the chief executive's actions, including unilateral actions? If it is most effective to work with others to get things done, how does the president do so? What can get in the way of this goal? This chapter answers these and other questions about the nation’s most visible leader.

[.my2]
总统的权力、机遇和局限性是什么？在当今的政治体制下，国家元首如何领导？国家元首的行动（包括单方面行动）受哪些因素指导？如果与他人合作是完成任务最有效的方式，总统又该如何做到这一点？哪些因素会阻碍这一目标的实现？本章将解答这些以及其他关于国家最受瞩目的领导人的问题。




Figure 12.1 Ichiro Suzuki meeting President Barack Obama in the clubhouse before the MLB All-Star Game at Busch Stadium on July 14, 2009 (left). President-elect Donald Trump takes the oath of office on January 20, 2025 (right). (credit left: Obama with Ichiro Suzuki Official White House Photo by Pete Souza - P071409PS-0792, Wikimedia Commons; credit right: "President-elect Donald Trump takes the oath of office. 20 January 2025.” by Joint Congressional Committee on Inaugural Ceremonies" by The White House/Wikimedia Commons, Public Domain)

Chapter Outline

- 12.1 The Design and Evolution of the Presidency
- 12.2 The Presidential Election Process
- 12.3 Organizing to Govern
- 12.4 The Public Presidency
- 12.5 Presidential Governance: Direct Presidential Action

The presidency is the most visible position in the U.S. government (Figure 12.1). During the Constitutional Convention of 1787, delegates accepted the need to empower a relatively strong and vigorous chief executive. But they also wanted this chief executive to be bound by checks from the other branches of the federal government as well as by the Constitution itself. Over time, the power of the presidency has grown in response to circumstances and challenges. However, to this day, a president must still work with the other branches to be most effective. Unilateral actions, in which the president acts alone on important and consequential matters, such as President Barack Obama’s strategy on the Iran nuclear deal, are bound to be controversial and suggest potentially serious problems within the federal government. Effective presidents, especially in peacetime, are those who work with the other branches through persuasion and compromise to achieve policy objectives.

What are the powers, opportunities, and limitations of the presidency? How does the chief executive lead in our contemporary political system? What guides the chief executive's actions, including unilateral actions? If it is most effective to work with others to get things done, how does the president do so? What can get in the way of this goal? This chapter answers these and other questions about the nation’s most visible leader.

'''