
= 012-5 Presidential Governance Direct Presidential Action 总统治理：总统直接行动
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





A president’s powers can be divided into two categories: direct actions the chief executive can take by employing the formal institutional powers of the office and informal powers of persuasion and negotiation essential to working with the legislative branch. When a president governs alone through direct action, it may break a policy deadlock or establish new grounds for action, but it may also spark opposition that might have been handled differently through negotiation and discussion. Moreover, such decisions are subject to court challenge, legislative reversal, or revocation by a successor. What may seem to be a sign of strength is often more properly understood as independent action undertaken in the wake of a failure to achieve a solution through the legislative process, or an admission that such an effort would prove futile. When it comes to national security, international negotiations, or war, the president has many more opportunities to act directly and in some cases must do so when circumstances require quick and decisive action.

[.my2]
总统的权力可分为两类：一是行政首脑可运用其正式的制度权力采取的直接行动，二是与立法部门合作所必需的非正式说服和谈判权力。当总统通过直接行动单独执政时，或许能够打破政策僵局或为新的行动奠定基础，但也可能引发反对，而这些反对本可通过谈判和讨论以不同的方式处理。此外，此类决定还可能受到法院挑战、立法机构推翻或被继任者撤销。看似强硬的举动，通常更恰当的理解是，它是在立法程序未能解决问题或承认此类努力徒劳无功之后采取的独立行动。在国家安全、国际谈判或战争等问题上，总统拥有更多直接行动的机会，在某些情况下，当形势需要迅速果断地采取行动时，总统必须这样做。

DOMESTIC POLICY  国内政策
Presidents may not be able to appoint key members of their administration without Senate confirmation, but they can demand the resignation or removal of cabinet officers, high-ranking appointees (such as ambassadors), and members of the presidential staff. During Reconstruction, Congress tried to curtail the president’s removal power with the Tenure of Office Act (1867), which required Senate concurrence to remove presidential nominees who took office upon Senate confirmation. Andrew Johnson’s violation of that legislation provided the grounds for his impeachment in 1868. Subsequent presidents secured modifications of the legislation before the Supreme Court ruled in 1926 that the Senate had no right to impair the president’s removal power.41 In the case of Senate failure to approve presidential nominations, the president is empowered to issue recess appointments (made while the Senate is in recess) that continue in force until the end of the next session of the Senate (unless the Senate confirms the nominee).

[.my2]
总统或许无法在未经参议院确认的情况下任命其政府的关键成员，但他们可以要求内阁官员、高级官员（例如大使）以及总统幕僚辞职或被免职。在重建时期，国会曾试图通过 《任期法案》 （1867 年）来限制总统的罢免权，该法案规定，总统提名的官员经参议院确认后上任，但必须经参议院同意才能被免职。安德鲁·约翰逊违反了该法案，这成为他在 1868 年被弹劾的理由。此后的总统们对该法案进行了修改，直到 1926 年最高法院裁定参议院无权限制总统的罢免权。 41 如果参议院未能批准总统的提名，总统有权发布休会任命（在参议院休会期间作出），这些任命将持续有效至参议院下一届会议结束（除非参议院确认该提名人）。

The president also exercises the power of pardon without conditions. Once used fairly sparingly—apart from Andrew Johnson’s wholesale pardons of former Confederates during the Reconstruction period—the pardon power has become more visible in recent decades. President Harry S. Truman issued over two thousand pardons and commutations, more than any other post–World War II president.42 President Gerald Ford has the unenviable reputation of being the only president to pardon another president (his predecessor Richard Nixon, who resigned after the Watergate scandal) (Figure 12.17). While not as generous as Truman, President Jimmy Carter also issued a great number of pardons, including several for draft dodging during the Vietnam War. President Reagan was reluctant to use the pardon as much, as was President George H. W. Bush. President Clinton pardoned few people for much of his presidency, but did make several last-minute pardons, which led to some controversy. By the end of his presidency, Barack Obama had granted 212 pardons, or 6 percent of petitions received, numbers similar to that of his predecessor, George W. Bush.43 Early on in his presidency, Donald Trump used the pardon in a few visible cases. He set aside sentences for controversial former Sherriff Joe Arpaio of Maricopa County, Arizona, and for former Vice President Dick Cheney’s confidante, Scooter Libby.44 Like other presidents, with his presidency's end in sight after losing the November 2020 election to Joe Biden, his use of pardons escalated. In the end, he granted 237 pardons.

[.my2]
总统还拥有无条件赦免权。赦免权曾经使用得相当谨慎——除了安德鲁·约翰逊在重建时期对前南方邦联成员的大规模赦免——但在近几十年来，赦免权的使用变得越来越普遍。哈里·S·杜鲁门总统颁布了超过两千份赦免令和减刑令，比二战后任何一位总统都多。 42 杰拉尔德·福特总统的“光荣”之处在于，他是唯一一位赦免过另一位总统（他的前任理查德·尼克松，后者在水门事件后辞职）的总统（ 图 12.17 ）。吉米·卡特总统虽然不如杜鲁门慷慨，但也颁布了大量赦免令，其中包括几起越南战争期间逃避兵役的案件。里根总统和老布什总统都不愿频繁使用赦免权。克林顿总统在其任期的大部分时间里赦免的人很少，但他也曾做出过几项临时赦免，这引发了一些争议。在奥巴马总统任期结束时，他共赦免了 212 人，占收到的赦免申请总数的 6%，这一数字与他的前任乔治·W·布什相近。 43 唐纳德·特朗普总统在其任期初期，曾在一些引人注目的案件中使用过赦免权。他撤销了备受争议的亚利桑那州马里科帕县前警长乔·阿尔帕约和前副总统迪克·切尼的亲信斯库特·利比的刑期。 44 与其他总统一样，在 2020 年 11 月败给乔·拜登后，随着任期即将结束，特朗普的赦免力度也随之加大。最终，他共赦免了 237 人。

A photo of Gerald Ford speaking in the House of Representatives.

[.my2]
Figure 12.17 In 1974, President Ford became the first and still the only president to pardon a previous president (Richard Nixon). Here he is speaking before the House Judiciary Subcommittee on Criminal Justice meeting explaining his reasons. While the pardon was unpopular with many and may have cost Ford the election two years later, his constitutional power to issue it is indisputable. (credit: modification of work by the Library of Congress)
图 12.17 1974 年，福特总统成为美国历史上第一位，也是迄今为止唯一一位赦免前总统（理查德·尼克松）的总统。图中是他出席众议院司法委员会刑事司法小组委员会会议，解释赦免尼克松的理由。尽管这项赦免令在许多人中不受欢迎，甚至可能导致福特在两年后的选举中落败，但他行使宪法赋予的赦免权是毋庸置疑的。（图片来源：美国国会图书馆作品的修改版）
Presidents may choose to issue executive orders or proclamations to achieve policy goals. Usually, executive orders direct government agencies to pursue a certain course in the absence of congressional action. A more subtle version pioneered by recent presidents is the executive memorandum, which tends to attract less attention. Many of the most famous executive orders have come in times of war or invoke the president’s authority as commander-in-chief, including Franklin Roosevelt’s order permitting the internment of Japanese Americans in 1942 and Harry Truman’s directive desegregating the armed forces (1948). The most famous presidential proclamation was Abraham Lincoln’s Emancipation Proclamation (1863), which declared enslaved people in areas under Confederate control to be free (with a few exceptions).

[.my2]
总统可以选择发布行政命令或公告来实现政策目标。通常情况下，行政命令会在国会未采取行动时指示政府机构采取特定行动。近年来，总统们开创了一种更为隐晦的行政命令形式——行政备忘录，这种形式往往较少引起关注。许多最著名的行政命令都发布于战争时期，或援引了总统作为三军统帅的权力，例如富兰克林·罗斯福总统于 1942 年发布的允许拘禁日裔美国人的行政命令，以及哈里·杜鲁门总统于 1948 年发布的取消军队种族隔离的指令。最著名的总统公告是亚伯拉罕·林肯总统于 1863 年发布的 《解放奴隶宣言 》，该宣言宣布南方邦联控制区内的奴隶获得自由（少数例外情况除外）。

Executive orders are subject to court rulings or changes in policy enacted by Congress. During the Korean War, the Supreme Court revoked Truman’s order seizing the steel industry.45 These orders are also subject to reversal by presidents who come after, and recent presidents have wasted little time reversing the orders of their predecessors in cases of disagreement. Sustained executive orders, which are those not overturned in courts, typically have some prior authority from Congress that legitimizes them. When there is no prior authority, it is much more likely that an executive order will be overturned by a later president. For this reason, while there has been significant use of executive orders in recent years, including an increase in use with President Trump, the last several presidents have used them sparingly compared to presidents in the early twentieth century. (Figure 12.18).

[.my2]
行政命令会受到法院裁决或国会政策变更的影响。朝鲜战争期间，最高法院撤销了杜鲁门总统没收钢铁行业的行政命令。 45 这些命令也可能被后任总统推翻，而近几任总统在意见不一致的情况下，往往会迅速推翻前任的命令。未被法院推翻的行政命令通常具有国会事先授权的合法性。如果没有事先授权，行政命令被后任总统推翻的可能性就大得多。因此，尽管近年来行政命令的使用有所增加，包括特朗普总统时期，但与 20 世纪初的总统相比，最近几任总统使用行政命令的频率仍然很低。（ 图 12.18 ）

A graph showing the average number of executive actions each U.S. President took per year in office. In reverse chronological order, Donald Trump took 55 actions per year, Barack Obama took 35 actions per year, George W. Bush took 36, William J. Clinton took 46, George Bush took 42, Ronald Reagan took 48, Jimmy Carter took 80, Gerald R. Ford took 69, Richard Nixon took 62, Lyndon B. Johnson took 63, John F. Kennedy took 75, Dwight D. Eisenhower took 61, Harry S. Truman took 117, Franklin D. Roosevelt took 307, Herbert Hoover took 242, Calvin Coolidge took 215, Warren G. Harding took 217, Woodrow Wilson took 225, William Howard Taft took 181, Theodore Roosevelt took 145, William McKinley took 41, Benjamin Harrison took 36, Grover Cleveland took 31.5, Chester Arthur took 28, James Garfield took 11, Rutherford B. Hayes took 23, Ulysses S. Grant took 27, Andrew Johnson took 20, Abraham Lincoln took 12, James Buchanan took 4, Franklin Pierce took 9, Millard Fillmore took 4.5, Zachary Taylor took 3.7, James J. Polk took 4.5, John Tyler took 4.3, William Henry Harrison took 0, Martin Van Buren took 2.5, Andrew Jackson took 1.5, John Quincy Adams took 0.75, James Monroe took 0.13, James Madison took 0.13, Thomas Jefferson took 0.5, John Adams took 0.25, and George Washington took 1. At the bottom of the graph, a source is listed: “Gerhard Peters and John T. Woolley, “Executive Orders.” The American Presidency Project. Ed. John T. Wooley and Gerhard Peters. Santa Barbara, CA. 1999-2021.

[.my2]
Figure 12.18 Executive actions were unusual until the late nineteenth century. They became common in the first half of the twentieth century but have been growing less popular for the last few decades because they often get overturned in court if the Congress has not given the president prior delegated authority.

[.my2]
图 12.18 行政命令在 19 世纪末之前并不常见。它们在 20 世纪上半叶变得普遍，但在过去几十年里越来越不受欢迎，因为如果国会没有事先授予总统授权，行政命令往往会被法院推翻。
Milestone  里程碑
Executive Order 9066  第9066号行政命令
Following the devastating Japanese attacks on the U.S. Pacific fleet at Pearl Harbor in 1941, many in the United States feared that Japanese Americans on the West Coast had the potential and inclination to form a fifth column (a hostile group working from the inside) for the purpose of aiding a Japanese invasion. These fears mingled with existing anti-Japanese sentiment across the country and created a paranoia that washed over the West Coast like a large wave. In an attempt to calm fears and prevent any real fifth-column actions, President Franklin D. Roosevelt signed Executive Order 9066, which authorized the removal of people from military areas as necessary. When the military dubbed the entire West Coast a military area, it effectively allowed for the removal of more than 110,000 Japanese Americans from their homes. These people, many of them U.S. citizens, were moved to relocation centers in the interior of the country. They lived in the camps there for two and a half years (Figure 12.19).46
1941 年，日本偷袭珍珠港，重创美国太平洋舰队。此后，许多美国人担心西海岸的日裔美国人有可能且有意愿组建第五纵队（一支潜伏在内部的敌对组织），以协助日本入侵。这种担忧与全国范围内普遍存在的反日情绪交织在一起，形成了一种恐慌情绪，如同巨浪般席卷了西海岸。为了平息恐慌，防止第五纵队真正采取行动，富兰克林·罗斯福总统签署了第 9066 号行政命令 ，授权在必要时将人员从军事区域迁出。军方将整个西海岸划为军事区域，实际上允许将超过 11 万名日裔美国人从家园驱逐。这些人中许多是美国公民，他们被转移到内陆的安置中心，并在营地中生活了两年半（ 图 12.19 ）。 46

A photo of sign in a store front that says “I am an American.”
Figure 12.19 This sign appeared outside a store in Oakland, California, owned by a Japanese American after the bombing of Pearl Harbor in 1941. After the president’s executive order, the store was closed and the owner evacuated to an internment camp for the duration of the war. (credit: the Library of Congress)
图 12.19 1941 年珍珠港事件后，加利福尼亚州奥克兰市一家日裔美国人商店外出现了这块告示。总统下达行政命令后，商店关闭，店主被疏散到集中营，直至战争结束。（图片来源：美国国会图书馆）
The overwhelming majority of Japanese Americans felt shamed by the actions of the Japanese empire and willingly went along with the policy in an attempt to demonstrate their loyalty to the United States. But at least one Japanese American refused to go along. His name was Fred Korematsu, and he decided to go into hiding in California rather than be taken to the internment camps with his family. He was soon discovered, turned over to the military, and sent to the internment camp in Utah that held his family. But his challenge to the internment system and the president’s executive order continued.

[.my2]
绝大多数日裔美国人对日本帝国的行径感到羞耻，为了表明对美国的忠诚，他们心甘情愿地接受了这项政策。但至少有一位日裔美国人拒绝妥协。他名叫弗雷德 ·科雷松 ，他选择躲藏在加利福尼亚州，而不是和家人一起被送往集中营。不久后，他被发现，被移交给军方，并被送往关押他家人的犹他州集中营。但他对集中营制度和总统行政命令的挑战并未停止。

In 1944, Korematsu’s case was heard by the Supreme Court. In a 6–3 decision, the Court ruled against him, arguing that the administration had the constitutional power to sign the order because of the need to protect U.S. interests against the threat of espionage.47 Forty-four years after this decision, President Reagan issued an official apology for the internment and provided some compensation to the survivors. In 2011, the Justice Department went a step further by filing a notice officially recognizing that the solicitor general of the United States acted in error by arguing to uphold the executive order. (The solicitor general is the official who argues cases for the U.S. government before the Supreme Court.) However, despite these actions, in 2014, the late Supreme Court justice Antonin Scalia was documented as saying that while he believed the decision was wrong, it could occur again.48
1944 年，科雷松的案件提交至最高法院审理。最高法院以 6 比 3 的投票结果驳回了他的上诉，认为政府有权签署该行政命令，因为需要保护美国利益免受间谍活动的威胁。 47 44 年后，里根总统就拘禁事件正式道歉，并向幸存者提供了一些赔偿。2011 年，司法部更进一步，提交了一份正式通知，承认美国副检察长在支持该行政命令的辩护中犯了错误。（副检察长是代表美国政府在最高法院进行辩护的官员。）然而，尽管采取了这些行动，已故最高法院大法官安东宁·斯卡利亚在 2014 年曾表示，虽然他认为该决定是错误的，但类似的事情仍有可能再次发生。 48

What do the Korematsu case and the internment of over 100,000 Japanese Americans suggest about the extent of the president’s war powers? What does this episode in U.S. history suggest about the weaknesses of constitutional checks on executive power during times of war?
科雷松案以及对超过10万日裔美国人的拘禁，对总统的战时权力范围有何启示？美国历史上的这一事件又揭示了战时宪法对行政权力制衡的哪些缺陷？

Link to Learning  学习链接
To learn more about the relocation and confinement of Japanese Americans during World War II, visit Heart Mountain online.

[.my2]
要了解更多关于二战期间日裔美国人的迁移和监禁的信息，请访问 Heart Mountain 网站。

Finally, presidents have also used the line-item veto and signing statements to alter or influence the application of the laws they sign. A line-item veto is a type of veto that keeps the majority of a spending bill unaltered but nullifies certain lines of spending within it. While a number of states allow their governors the line-item veto (discussed in the chapter on state and local government), the president acquired this power only in 1996 after Congress passed a law permitting it. President Clinton used the tool sparingly. However, those entities that stood to receive the federal funding he lined out brought suit. Two such groups were the City of New York and the Snake River Potato Growers in Idaho.49 The Supreme Court heard their claims together and just sixteen months later declared unconstitutional the act that permitted the line-item veto.50 Since then, presidents have asked Congress to draft a line-item veto law that would be constitutional, although none have made it to the president’s desk.

[.my2]
最后，总统们还利用逐项否决权和签署声明来修改或影响他们签署的法律的实施。 逐项否决权是一种否决权，它维持支出法案的大部分内容不变，但否决其中的某些支出项目。虽然一些州允许州长行使逐项否决权（在州和地方政府章节中讨论过），但总统直到 1996 年国会通过一项允许总统行使这项权力的法律后才获得这项权力。克林顿总统谨慎地使用这项权力。然而，那些原本将获得他否决的联邦拨款的实体提起了诉讼。其中两个实体是纽约市和爱达荷州的蛇河马铃薯种植者协会。 49 最高法院合并审理了他们的诉讼，并在仅仅 16 个月后宣布允许逐项否决的法案违宪​​。 50 此后，历任总统都要求国会起草一部符合宪法的逐项否决法案，但至今没有一部最终提交到总统的办公桌上。

On the other hand, signing statements are statements issued by a president when agreeing to legislation that indicate how the chief executive will interpret and enforce the legislation in question. Signing statements are less powerful than vetoes, though congressional opponents have complained that they derail legislative intent. Signing statements have been used by presidents since at least James Monroe, but they became far more common in this century.

[.my2]
另一方面， 签署声明是总统在同意立法时发表的声明，表明总统将如何解释和执行相关立法。签署声明的效力不如否决权，但国会反对者抱怨说，签署声明会阻碍立法意图的实现。总统至少从詹姆斯·门罗时代起就开始使用签署声明，但在本世纪才变得更加普遍。

NATIONAL SECURITY, FOREIGN POLICY, AND WAR
国家安全、外交政策和战争
Presidents are more likely to justify the use of executive orders in cases of national security or as part of their war powers. In addition to mandating emancipation and the internment of Japanese Americans, presidents have issued orders to protect the homeland from internal threats. Most notably, Lincoln ordered the suspension of the privilege of the writ of habeas corpus in 1861 and 1862 before seeking congressional legislation to undertake such an act. Presidents hire and fire military commanders; they also use their power as commander-in-chief to aggressively deploy U.S. military force. Congress rarely has taken the lead over the course of history, with the War of 1812 being the lone exception. Pearl Harbor was a salient case where Congress did make a clear and formal declaration when asked by FDR. However, since World War II, it has been the president and not Congress who has taken the lead in engaging the United States in military action outside the nation’s boundaries, most notably in Korea, Vietnam, and the Persian Gulf (Figure 12.20).

[.my2]
总统更有可能在涉及国家安全或行使战争权力的情况下，为使用行政命令辩护。除了强制解放奴隶和拘禁日裔美国人之外，总统还发布命令保护国土免受内部威胁。最值得注意的是，林肯在 1861 年和 1862 年下令暂停人身保护令的特权，之后才寻求国会立法实施该项措施。总统可以任免军事指挥官；他们还可以利用三军统帅的权力积极部署美国军事力量。纵观历史，国会很少主导军事行动，1812 年战争是唯一的例外。珍珠港事件是一个显著的例子，当时国会在罗斯福总统的要求下发表了明确而正式的声明。然而，自二战以来，领导美国在境外进行军事行动的一直是总统，而不是国会，最显著的例子是朝鲜战争、越南战争和波斯湾战争（ 图 12.20 ）。

A photo of George W. Bush in a flight suit stepping out of a plane onto an aircraft carrier. Personnel stand on either side and salute him.

[.my2]
Figure 12.20 By landing on an aircraft carrier and wearing a flight suit to announce the end of major combat operations in Iraq in 2003, President George W. Bush was carefully emphasizing his presidential power as commander-in-chief. (credit: Tyler J. Clements)
图 12.20 2003 年，乔治·W·布什总统身着飞行服，降落在航空母舰上，宣布伊拉克主要作战行动结束，此举意在巧妙地强调他作为三军统帅的总统权力。（图片来源：泰勒·J·克莱门茨）
Presidents also issue executive agreements with foreign powers. Executive agreements are formal agreements negotiated between two countries but not ratified by a legislature as a treaty must be. As such, they are not treaties under U.S. law, which require two-thirds of the Senate for ratification. Treaties, presidents have found, are particularly difficult to get ratified. And with the fast pace and complex demands of modern foreign policy, concluding treaties with countries can be a tiresome and burdensome chore. That said, some executive agreements do require some legislative approval, such as those that commit the United States to make payments and thus are restrained by the congressional power of the purse. But for the most part, executive agreements signed by the president require no congressional action and are considered enforceable as long as the provisions of the executive agreement do not conflict with current domestic law.

[.my2]
总统还会与外国签署行政协议 。行政协议是两国之间谈判达成的正式协议，但无需像条约那样经立法机构批准。因此，根据美国法律，行政协议不属于条约范畴，条约需要参议院三分之二的多数票才能批准。总统们发现，条约的批准尤其困难。鉴于现代外交政策节奏快、要求复杂，与他国缔结条约可能是一项繁琐而沉重的任务。尽管如此，某些行政协议确实需要立法机构的批准，例如那些承诺美国支付款项的协议，因此受到国会拨款权的约束。但大多数情况下，总统签署的行政协议无需国会批准，只要其条款不与现行国内法相抵触，即可被视为具有法律效力。

Link to Learning  学习链接
The American Presidency Project has gathered data outlining presidential activity, including measures for executive orders and signing statements.

[.my2]
美国总统项目收集了概述总统活动的各种数据，包括行政命令和签署声明的措施。

THE POWER OF PERSUASION
说服的力量
The framers of the Constitution, concerned about the excesses of British monarchial power, made sure to design the presidency within a network of checks and balances controlled by the other branches of the federal government. Such checks and balances encourage consultation, cooperation, and compromise in policymaking. This is most evident at home, where the Constitution makes it difficult for either Congress or the chief executive to prevail unilaterally, at least when it comes to constructing policy. Although much is made of political stalemate and obstructionism in national political deliberations today, the framers did not want to make it too easy to get things done without a great deal of support for such initiatives.

[.my2]
宪法的制定者们担忧英国君主权力的过度扩张，因此确保将总统权力置于联邦政府其他部门制衡的体系之中。这种制衡机制鼓励政策制定过程中的协商、合作与妥协。这一点在国内尤为明显，宪法使得国会或行政首脑难以单方面独断专行，至少在政策制定方面是如此。尽管如今国家政治讨论中经常出现政治僵局和阻挠主义，但宪法的制定者们并不希望在没有足够支持的情况下轻易地完成某些事情。

It is left to the president to employ a strategy of negotiation, persuasion, and compromise in order to secure policy achievements in cooperation with Congress. In 1960, political scientist Richard Neustadt put forward the thesis that presidential power is the power to persuade, a process that takes many forms and is expressed in various ways.51 Yet the successful employment of this technique can lead to significant and durable successes. For example, legislative achievements tend to be of greater duration because they are more difficult to overturn or replace, as the case of health care reform under President Barack Obama suggests. Obamacare has faced court cases and repeated (if largely symbolic) attempts to gut it in Congress. Overturning it will take a new president who opposes it, together with a Congress that can pass the dissolving legislation.

[.my2]
总统需要运用谈判、说服和妥协的策略，与国会合作，以确保政策目标的实现。1960 年，政治学家理查德·纽斯塔特提出，总统权力就是说服的权力，这一过程形式多样，表达方式也多种多样。 51 然而，成功运用这一策略可以带来意义深远且持久的成果。例如，立法成果往往持续时间更长，因为它们更难被推翻或取代，正如奥巴马总统时期的医改所表明的那样。奥巴马医改曾面临诉讼，并在国会遭遇多次（尽管大多是象征性的）试图废除它的努力。要推翻它，需要一位反对它的新总统，以及一个能够通过废除该医改法案的国会。

In some cases, cooperation is essential, as when the president nominates and the Senate confirms persons to fill vacancies on the Supreme Court, an increasingly contentious area of friction between branches. While Congress cannot populate the Court on its own, it can frustrate the president’s efforts to do so. Presidents who seek to prevail through persuasion, according to Neustadt, target Congress, members of their own party, the public, the bureaucracy, and, when appropriate, the international community and foreign leaders. Of these audiences, perhaps the most obvious and challenging is Congress.

[.my2]
在某些情况下，合作至关重要，例如总统提名最高法院大法官人选，参议院确认人选填补空缺时，这往往是两院之间摩擦日益加剧的领域。虽然国会无法独自决定最高法院的组成，但它可以阻挠总统的这一努力。纽斯塔特指出，那些试图通过说服来取得胜利的总统，其目标群体包括国会、本党成员、公众、官僚机构，以及在适当情况下，国际社会和外国领导人。在这些目标群体中，或许最显而易见也最具挑战性的当属国会。

Link to Learning  学习链接
Read “Power Lessons for Obama” at this website to learn more about applying Richard Neustadt’s framework to the leaders of today.

[.my2]
请访问此网站阅读“给奥巴马的权力课程”，了解更多关于如何将理查德·纽斯塔特的框架应用于当今领导人的信息。

Much depends on the balance of power within Congress: Should the opposition party hold control of both houses, it will be difficult indeed for the president to realize their own objectives, especially if the opposition is intent on frustrating all initiatives. However, even control of both houses by the president’s own party is no guarantee of success or even of productive policymaking. For example, neither Barack Obama nor Donald Trump achieved all they desired despite having favorable conditions for the first two years of their presidencies. In times of divided government (when one party controls the presidency and the other controls one or both chambers of Congress), it is up to the president to cut deals and make compromises that will attract support from at least some members of the opposition party without excessively alienating members of their own party. Both Ronald Reagan and Bill Clinton proved effective in dealing with divided government—indeed, Clinton scored more successes with Republicans in control of Congress than he did with Democrats in charge.

[.my2]
国会内部的权力平衡至关重要：如果反对党掌控参众两院，总统实现自身目标将难上加难，尤其是在反对党蓄意阻挠所有举措的情况下。然而，即便总统所属政党掌控参众两院，也并非成功或有效政策制定的保证。例如，巴拉克·奥巴马和唐纳德·特朗普在执政头两年都拥有有利条件，但最终都未能实现所有目标。在两党分治时期（即一个政党控制总统职位，而另一个政党控制国会一院或两院），总统必须达成协议和做出妥协，以争取至少部分反对党成员的支持，同时避免过度疏远本党成员。罗纳德·里根和比尔·克林顿都证明了自己在应对两党分治方面卓有成效——事实上，克林顿在共和党掌控国会时取得的成功甚至超过了民主党掌控国会时。

It is more difficult to persuade members of the president’s own party or the public to support a president’s policy without risking the dangers inherent in going public. There is precious little opportunity for private persuasion while also going public in such instances, at least directly. The way the president and their staff handle media coverage of the administration may afford some opportunities for indirect persuasion of these groups. It is not easy to persuade the federal bureaucracy to do the president’s bidding unless the chief executive has made careful appointments. When it comes to diplomacy, the president must relay some messages privately while offering incentives, both positive and negative, in order to elicit desired responses, although at times, people heed only the threat of force and coercion.

[.my2]
要想说服总统所在政党的成员或公众支持总统的政策，而不冒公开表态的风险，难度更大。在这种情况下，至少直接进行私下劝说的机会非常有限。总统及其幕僚处理媒体对政府报道的方式，或许能为间接劝说这些群体提供一些机会。除非总统经过精心任命，否则很难说服联邦官僚机构听命于总统。在外交方面，总统必须私下传递一些信息，同时提供正反两方面的激励措施，以期获得预期的回应。然而，有时人们只会听从武力威胁和胁迫。

While presidents may choose to go public in an attempt to put pressure on other groups to cooperate, most of the time they “stay private” as they attempt to make deals and reach agreements out of the public eye. The tools of negotiation have changed over time. Once chief executives played patronage politics, rewarding friends while attacking and punishing critics as they built coalitions of support. But the advent of civil service reform in the 1880s systematically deprived presidents of that option and reduced its scope and effectiveness. Although the president may call upon various agencies for assistance in lobbying for proposals, such as the Office of Legislative Liaison with Congress, it is often left to the chief executive to offer incentives and rewards. Some of these are symbolic, like private meetings in the White House or an appearance on the campaign trail. The president must also find common ground and make compromises acceptable to all parties, thus enabling everyone to claim they secured something they wanted.

[.my2]
尽管总统有时会选择公开表态 ，试图向其他团体施压以促成合作，但大多数时候，他们会选择“保持低调”，在公众视线之外达成交易和协议。谈判的手段也随着时间推移而不断变化。过去，行政长官们常常玩弄恩惠政治，在建立支持联盟的同时，奖赏亲信，打击打压批评者。但 19 世纪 80 年代的公务员制度改革系统性地剥夺了总统的这种选择权，并削弱了其作用范围和效力。虽然总统可能会寻求各种机构的协助来游说提案，例如国会立法联络办公室 ，但提供激励和奖励往往还是由行政长官本人负责。其中一些是象征性的，例如在白宫举行私人会晤或在竞选活动中露面。总统还必须找到共同点，做出各方都能接受的妥协，从而使每个人都能声称自己获得了想要的东西。

Complicating Neustadt’s model, however, is that many of the ways he claimed presidents could shape favorable outcomes require going public, which as we have seen can produce mixed results. Political scientist Fred Greenstein, on the other hand, touted the advantages of a “hidden hand presidency,” in which the chief executive did most of the work behind the scenes, wielding both the carrot and the stick.52 Greenstein singled out President Dwight Eisenhower as particularly skillful in such endeavors.

[.my2]
然而，纽斯塔特的模型存在一个复杂之处：他所声称的总统影响选举结果的许多方式都需要公开表态，而正如我们所见，公开表态往往会产生喜忧参半的结果。另一方面，政治学家弗雷德·格林斯坦则推崇“幕后操纵型总统制”，即总统在幕后开展大部分工作，同时运用胡萝卜加大棒。 格林斯坦特别指出，德怀特·艾森豪威尔总统在这方面尤为擅长。

OPPORTUNITY AND LEGACY  机遇与传承
What often shapes a president’s performance, reputation, and ultimately legacy depends on circumstances that are largely out of their control. Did the president prevail in a landslide or was it a closely contested election? Did they come to office as the result of death, assassination, or resignation? How much support does the president’s party enjoy, and is that support reflected in the composition of both houses of Congress, just one, or neither? Will the president face a Congress ready to embrace proposals or poised to oppose them? Whatever a president’s ambitions, it will be hard to realize them in the face of a hostile or divided Congress, and the options to exercise independent leadership are greater in times of crisis and war than when looking at domestic concerns alone.

[.my2]
总统的政绩、声誉乃至最终的政治遗产，往往取决于许多他们无法掌控的因素。总统的胜选是压倒性优势还是势均力敌？他们是因前任去世、遇刺身亡还是辞职而继任？总统所在政党的支持率如何？这种支持是否体现在国会两院、其中一院或两院的组成中？总统面对的国会是准备接受提案还是准备反对？无论总统抱负如何，面对一个敌对或分裂的国会，都难以实现。在危机和战争时期，总统行使独立领导权的机会比仅仅关注国内事务时更多。

Then there is what political scientist Stephen Skowronek calls “political time.”53 Some presidents take office at times of great stability with few concerns. Unless there are radical or unexpected changes, a president’s options are limited, especially if voters hoped for a simple continuation of what had come before. Other presidents take office at a time of crisis or when the electorate is looking for significant changes. Then there is both pressure and opportunity for responding to those challenges. Some presidents, notably Theodore Roosevelt, openly bemoaned the lack of any such crisis, which Roosevelt deemed essential for him to achieve greatness as a president.

[.my2]
此外，还有政治学家斯蒂芬·斯科沃罗内克所说的“政治时机”。 53 有些总统在政局高度稳定、鲜有忧虑的时期就职。除非出现剧烈或意想不到的变化，否则总统的选择有限，尤其是在选民希望一切照旧的情况下。另一些总统则在危机时期或选民寻求重大变革之时就职。此时，他们既面临压力，也拥有应对挑战的机遇。一些总统，尤其是西奥多·罗斯福，曾公开抱怨缺乏此类危机，而罗斯福认为危机对于他作为总统的伟大成就至关重要。

People in the United States claim they want a strong president. What does that mean? At times, scholars point to presidential independence, even defiance, as evidence of strong leadership. Thus, vigorous use of the veto power in key situations can cause observers to judge a president as strong and independent, although far from effective in shaping constructive policies. Nor is such defiance and confrontation always evidence of presidential leadership skill or greatness, as the case of Andrew Johnson should remind us. When is effectiveness a sign of strength, and when are we confusing being headstrong with being strong? Sometimes, historians and political scientists see cooperation with Congress as evidence of weakness, as in the case of Ulysses S. Grant, who was far more effective in garnering support for administration initiatives than scholars have given him credit for.

[.my2]
美国民众声称他们想要一位强有力的总统。这究竟意味着什么？有时，学者们会将总统的独立性，甚至是反抗精神，视为强有力领导力的体现。因此，在关键时刻积极运用否决权，可能会让观察家们认为总统强势且独立，尽管他在制定建设性政策方面可能远非高效。然而，这种反抗和对抗也并非总是总统领导能力或伟大之处的体现，安德鲁·约翰逊的例子就足以提醒我们这一点。究竟何时高效才是力量的象征？我们又何时将固执己见与强势混淆了？有时，历史学家和政治学家会将与国会的合作视为软弱的表现，例如尤利西斯·S·格兰特的例子。格兰特在争取政府各项举措的支持方面，远比学者们所认为的要有效得多。

These questions overlap with those concerning political time and circumstance. While domestic policymaking requires far more give-and-take and a fair share of cajoling and collaboration, national emergencies and war offer presidents far more opportunity to act vigorously and at times independently. This phenomenon often produces the rally around the flag effect, in which presidential popularity spikes during international crises. A president must always be aware that politics, according to Otto von Bismarck, is the art of the possible, even as it is a president's duty to increase what might be possible by persuading both members of Congress and the general public of what needs to be done.

[.my2]
这些问题与政治时机和形势相关的问题有所重叠。虽然国内政策制定需要更多的妥协和协商，以及相当程度的劝说与合作，但国家紧急状态和战争却为总统提供了更多采取强硬行动、有时甚至是独立行动的机会。这种现象常常会产生“ 团结在国旗周围”效应 ，即总统在国际危机期间的支持率飙升。总统必须始终牢记，正如奥托·冯·俾斯麦所言，政治是可能性的艺术，但总统的职责是说服国会议员和公众，让他们相信应该采取的行动，从而扩大可能性。

Finally, presidents often leave a legacy that lasts far beyond their time in office (Figure 12.21). Sometimes, this is due to the long-term implications of policy decisions. Critical to the notion of legacy is the shaping of the Supreme Court as well as other federal judges. Long after John Adams left the White House in 1801, his appointment of John Marshall as chief justice shaped American jurisprudence for over three decades. No wonder confirmation hearings have grown more contentious in the cases of highly visible nominees. Other legacies are more difficult to define, although they suggest that, at times, presidents cast a long shadow over their successors. It was a tough act to follow George Washington, and in death, Abraham Lincoln’s presidential stature grew to extreme heights. Theodore and Franklin D. Roosevelt offered models of vigorous executive leadership, while the image and style of John F. Kennedy and Ronald Reagan influenced and at times haunted or frustrated successors. Nor is this impact limited to chief executives deemed successful: Lyndon Johnson’s Vietnam and Richard Nixon’s Watergate offered cautionary tales of presidential power gone wrong, leaving behind legacies that include terms like Vietnam syndrome and the tendency to add the suffix “-gate” to scandals and controversies.

[.my2]
最后，总统往往会留下远超其任期影响的政治遗产（ 图 12.21 ）。有时，这是由于政策决策的长期影响。塑造最高法院以及其他联邦法官是政治遗产概念的关键所在。约翰·亚当斯于 1801 年离开白宫后，他任命约翰·马歇尔为首席大法官的举措，在之后的三十多年里深刻影响了美国的法理学。难怪在备受瞩目的提名人选的确认听证会上，争议会愈演愈烈。其他一些政治遗产则更难界定，但它们表明，总统有时会对继任者产生深远的影响。接替乔治·华盛顿并非易事，而亚伯拉罕·林肯去世后，其总统地位更是达到了顶峰。西奥多·罗斯福和富兰克林·罗斯福树立了强有力的行政领导典范，而约翰·肯尼迪和罗纳德·里根的形象和风格也影响了继任者，有时甚至令他们感到困扰或沮丧。这种影响不仅限于被认为成功的首席执行官：林登·约翰逊的越南战争和理查德·尼克松的水门事件都提供了总统权力失控的警示故事，留下了诸如“ 越南综合症 ”之类的术语，以及在丑闻和争议中添加后缀“-gate”的倾向。

Image A is a photo of John F. Kennedy and Jacqueline Kennedy. Image B is a photo of Richard Nixon standing in front of a helicopter making “V for Victory” signs with his hands.

[.my2]
Figure 12.21 The youth and glamour that John F. Kennedy and first lady Jacqueline brought to the White House in the early 1960s (a) helped give rise to the legend of “one brief shining moment that was Camelot” after Kennedy’s presidency was cut short by his assassination on November 22, 1963. Despite a tainted legacy, President Richard Nixon gives his trademark “V for Victory” sign as he leaves the White House on August 9, 1974 (b), after resigning in the wake of the Watergate scandal.

[.my2]
图 12.21 约翰·F· 肯尼迪和第一夫人杰奎琳在 20 世纪 60 年代初为白宫带来的青春活力和迷人魅力 (a)，在肯尼迪总统于 1963 年 11 月 22 日遇刺身亡后，促成了“卡米洛特短暂而辉煌的时光”的传奇。尽管留下了污点，理查德· 尼克松总统在水门事件后辞职后，于 1974 年 8 月 9 日离开白宫时，仍然做出了他标志性的“V 字胜利”手势 (b)。

'''