
= 013 The Courts  法院
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


If democratic institutions struggle to balance individual freedoms and collective well-being, the judiciary is arguably the branch where the individual has the best chance to be heard. For those seeking protection on the basis of sexual orientation, for example, in recent years, the courts have expanded rights, such as the 2015 decision in which the Supreme Court ruled that same-sex couples have the right to marry in all fifty states (Figure 13.1).1
如果民主制度难以平衡个人自由与集体福祉，那么司法部门可以说是个人最有机会发声的机构。例如，近年来，法院扩大了那些因性取向而寻求保护的人的权利，例如 2015 年最高法院裁定，同性伴侣在所有五十个州都享有结婚权（ 图 13.1 ） 。

The U.S. courts pride themselves on two achievements: (1) as part of the system of checks and balances, they protect the sanctity of the U.S. Constitution from breaches by the other branches of government, and (2) they protect individual rights against societal and governmental oppression. At the federal level, nine Supreme Court judges are nominated by the president and confirmed by the Senate for lifetime appointments. This provides them the independence they need to carry out their duties. However, court power is confined to rulings on those cases the courts decide to hear.2
美国法院引以为豪的两项成就是：(1) 作为权力制衡体系的一部分，它们保护美国宪法的神圣性，使其免受其他政府部门的侵犯；(2) 它们保护个人权利免受社会和政府的压迫。在联邦层面，九名最高法院法官由总统提名，经参议院确认， 终身任职。这赋予了他们履行职责所需的独立性。然而，法院的权力仅限于对法院决定审理的案件作出裁决。

How do the courts make decisions, and how do they exercise their power to protect individual rights? How are the courts structured, and what distinguishes the Supreme Court from all others? This chapter answers these and other questions in delineating the power of the judiciary in the United States.

[.my2]
法院如何做出判决？如何行使权力保护个人权利？法院的结构是怎样的？最高法院与其他法院有何区别？本章将解答这些问题，并阐述美国司法机构的权力。



Figure 13.1 The Marriage Equality Act vote in Albany, New York, on July 24, 2011 (left), was just one of a number of cases testing the constitutionality of both federal and state law that ultimately led the Supreme Court to take on the controversial issue of same-sex marriage. In the years leading up to the 2015 ruling that same-sex couples have a right to marry in all fifty states, marriage equality had become a key civil rights issue for the LGBTQ community, as demonstrated at Seattle’s 2012 Pride parade (right). (credit left: modification of work by “Celebration chapel”/Wikimedia; credit right: modification of work by Brett Curtiss)

Chapter Outline

- 13.1 Guardians of the Constitution and Individual Rights
- 13.2 The Dual Court System
- 13.3 The Federal Court System
- 13.4 The Supreme Court
- 13.5 Judicial Decision-Making and Implementation by the Supreme Court

If democratic institutions struggle to balance individual freedoms and collective well-being, the judiciary is arguably the branch where the individual has the best chance to be heard. For those seeking protection on the basis of sexual orientation, for example, in recent years, the courts have expanded rights, such as the 2015 decision in which the Supreme Court ruled that same-sex couples have the right to marry in all fifty states (Figure 13.1).1

The U.S. courts pride themselves on two achievements: (1) as part of the system of checks and balances, they protect the sanctity of the U.S. Constitution from breaches by the other branches of government, and (2) they protect individual rights against societal and governmental oppression. At the federal level, nine Supreme Court judges are nominated by the president and confirmed by the Senate for lifetime appointments. This provides them the independence they need to carry out their duties. However, court power is confined to rulings on those cases the courts decide to hear.2

How do the courts make decisions, and how do they exercise their power to protect individual rights? How are the courts structured, and what distinguishes the Supreme Court from all others? This chapter answers these and other questions in delineating the power of the judiciary in the United States.

'''