
= 013-1 Guardians of the Constitution and Individual Rights 宪法和个人权利的守护者
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





Under the Articles of Confederation, there was no national judiciary. The U.S. Constitution changed that, but its Article III, which addresses “the judicial power of the United States,” is the shortest and least detailed of the three articles that created the branches of government. It calls for the creation of “one supreme Court” and establishes the Court’s jurisdiction, or its authority to hear cases and make decisions about them, and the types of cases the Court may hear. It distinguishes which are matters of original jurisdiction and which are for appellate jurisdiction. Under original jurisdiction, a case is heard for the first time, whereas under appellate jurisdiction, a court hears a case on appeal from a lower court and may change the lower court’s decision. The Constitution also limits the Supreme Court’s original jurisdiction to those rare cases of disputes between states, or between the United States and foreign ambassadors or ministers. So, for the most part, the Supreme Court is an appeals court, operating under appellate jurisdiction and hearing appeals from the lower courts. The rest of the development of the judicial system and the creation of the lower courts were left in the hands of Congress.

[.my2]
在《邦联条例》下，美国没有国家司法机构。《美国宪法》改变了这一现状，但其第三条 ——即“合众国的司法权”——是设立政府各部门的三条条款中最短、最不详细的一条。该条款要求设立“一个最高法院”，并确立了最高法院的管辖权，即其审理案件并作出裁决的权力，以及最高法院可以审理的案件类型。它区分了哪些案件属于初审管辖权，哪些属于上诉管辖权。 初审管辖权是指对案件进行首次审理；而上诉管辖权是指法院审理下级法院判决的上诉案件，并可以推翻下级法院的判决。宪法还将最高法院的初审管辖权限制在极少数情况下，即各州之间或美国与外国大使或公使之间的纠纷。因此，在大多数情况下， 最高法院是一个上诉法院，行使上诉管辖权，审理下级法院的上诉案件。司法体系的其余发展和下级法院的设立则交由国会负责。

To add further explanation to Article III, Alexander Hamilton wrote details about the federal judiciary in Federalist No. 78. In explaining the importance of an independent judiciary separated from the other branches of government, he said “interpretation” was a key role of the courts as they seek to protect people from unjust laws. But he also believed “the Judiciary Department” would “always be the least dangerous” because “with no influence over either the sword or the purse,” it had “neither force nor will, but merely judgment.” The courts would only make decisions, not take action. With no control over how those decisions would be implemented and no power to enforce their choices, they could exercise only judgment, and their power would begin and end there. Hamilton would no doubt be surprised by what the judiciary has become: a key component of the nation’s constitutional democracy, finding its place as the chief interpreter of the Constitution and the equal of the other two branches, though still checked and balanced by them.

[.my2]
为了进一步阐释宪法第三条，亚历山大 ·汉密尔顿在 《联邦党人文集 》第 78 篇中详细论述了联邦司法机构。在解释独立于其他政府部门的司法机构的重要性时，他指出，“解释”是法院的关键职责，因为法院致力于保护人民免受不公正法律的侵害。但他同时也认为，“司法部门”将“始终是最不危险的”，因为“它既无武力也无财政权力”，因此“既无武力也无意志，只有判断”。法院只会做出裁决，而不会采取行动。由于无法控制这些裁决的执行方式，也无权强制执行其裁决，法院只能行使判断权，其权力也仅限于此。汉密尔顿无疑会对司法机构如今的成就感到惊讶：它已成为国家宪政民主的关键组成部分，确立了其作为宪法主要解释者的地位，并与另外两个部门平起平坐，尽管仍然受到它们的制约和制衡。

The first session of the first U.S. Congress laid the framework for today’s federal judicial system, established in the Judiciary Act of 1789. Although legislative changes over the years have altered it, the basic structure of the judicial branch remains as it was set early on: At the lowest level are the district courts, where federal cases are tried, witnesses testify, and evidence and arguments are presented. A losing party who is unhappy with a district court decision may appeal to the circuit courts, or U.S. courts of appeals, where the decision of the lower court is reviewed. Still further, appeal to the U.S. Supreme Court is possible, but of the thousands of petitions for appeal, the Supreme Court will typically hear fewer than one hundred a year.3
美国第一届国会第一会期奠定了当今联邦司法体系的框架，该体系于 1789 年通过了《司法法案》 。尽管多年来的立法改革对其进行了调整，但司法部门的基本结构仍然保持不变：最底层是地区法院，联邦案件在此审理，证人在此作证，证据和论点在此呈现。败诉方若对地区法院的判决不服，可以向巡回法院（即美国联邦上诉法院）提起上诉，由巡回法院对下级法院的判决进行复审。最终，还可以向美国最高法院提起上诉，但最高法院每年通常只受理不到一百起上诉案件，而上诉申请数以千计。

Link to Learning  学习链接
This public site maintained by the Administrative Office of the U.S. Courts provides detailed information from and about the judicial branch.

[.my2]
这个由美国法院行政办公室维护的公共网站提供了来自司法部门的详细信息。

HUMBLE BEGINNINGS  卑微的开端
Starting in New York in 1790, the early Supreme Court focused on establishing its rules and procedures and perhaps trying to carve its place as the new government’s third branch. However, given the difficulty of getting all the justices even to show up, and with no permanent home or building of its own for decades, finding its footing in the early days proved to be a monumental task. Even when the federal government moved to the nation’s capital in 1800, the Court had to share space with Congress in the Capitol building. This ultimately meant that “the high bench crept into an undignified committee room in the Capitol beneath the House Chamber.”4
最高法院于 1790 年在纽约成立，早期阶段的重点是确立其规则和程序，或许也试图确立其作为新政府第三分支的地位。然而，由于连让所有大法官都到场都困难重重，而且在之后的几十年里都没有自己的永久办公场所，因此，在早期阶段站稳脚跟是一项艰巨的任务。即使联邦政府于 1800 年迁至首都华盛顿，最高法院也不得不与国会共用国会大厦的空间。这最终意味着“最高法院只能挤进国会大厦众议院议事厅下方一个不太体面的委员会会议室”。 4

It was not until the Court’s 146th year of operation that Congress, at the urging of Chief Justice—and former president—William Howard Taft, provided the designation and funding for the Supreme Court’s own building, “on a scale in keeping with the importance and dignity of the Court and the Judiciary as a coequal, independent branch of the federal government.”5 It was a symbolic move that recognized the Court’s growing role as a significant part of the national government (Figure 13.2).

[.my2]
直到最高法院成立 146 年后，在首席大法官兼前总统威廉·霍华德· 塔夫脱的敦促下，国会才为最高法院的专属大楼指定了名称并提供资金，“其规模与最高法院和司法部门作为联邦政府平等、独立部门的重要性和尊严相符。” ⁵ 这是一项具有象征意义的举措，承认了最高法院作为国家政府重要组成部分的日益增长的作用（ 图 13.2 ）。

An image of the Supreme Court building. In the foreground, a set of stairs is bracketed by statues on either side, leading up to a portico. The portico has a roof supported by several tall columns.

[.my2]
Figure 13.2 The Supreme Court building in Washington, DC, was not completed until 1935. Engraved on its marble front is the motto “Equal Justice Under Law,” while its east side says, “Justice, the Guardian of Liberty.”
图 13.2 位于华盛顿特区的最高法院大楼直到 1935 年才竣工。其大理石正面刻有格言“法律面前人人平等”，而其东侧则写着“正义，自由的守护者”。
But it took years for the Court to get to that point, and it faced a number of setbacks on the way to such recognition. In their first case of significance, Chisholm v. Georgia (1793), the justices ruled that the federal courts could hear cases brought by a citizen of one state against a citizen of another state, and that Article III, Section 2, of the Constitution did not protect the states from facing such an interstate lawsuit.6 However, their decision was almost immediately overturned by the Eleventh Amendment, passed by Congress in 1794 and ratified by the states in 1795. In protecting the states, the Eleventh Amendment put a prohibition on the courts by stating, “The Judicial power of the United States shall not be construed to extend to any suit in law or equity, commenced or prosecuted against one of the United States by Citizens of another State, or by Citizens or Subjects of any Foreign State.” It was an early hint that Congress had the power to change the jurisdiction of the courts as it saw fit and stood ready to use it.

[.my2]
但最高法院花了数年时间才走到这一步，在此过程中也遭遇了诸多挫折。在其首个具有重要意义的案件—— 奇泽姆诉佐治亚州案（1793 年）中，大法官们裁定，联邦法院可以审理一州公民对另一州公民提起的诉讼，并且宪法第三条第二款并不保护各州免受此类跨州诉讼的侵害。然而，他们的裁决几乎立即被 1794 年国会通过、1795 年各州批准的第十一修正案推翻。为了保护各州，第十一修正案对法院施加了限制，规定：“合众国的司法权不得解释为延伸至由另一州的公民或任何外国的公民或臣民对合众国任何一州提起或进行的普通法或衡平法诉讼。”这早先就暗示了国会有权根据自身判断改变法院的管辖权，并且随时准备行使这项权力。

In an atmosphere of perceived weakness, the first chief justice, John Jay, an author of The Federalist Papers and appointed by President George Washington, resigned his post to become governor of New York and later declined President John Adams’s offer of a subsequent term.7 In fact, the Court might have remained in a state of what Hamilton called its “natural feebleness” if not for the man who filled the vacancy Jay had refused—the fourth chief justice, John Marshall. Often credited with defining the modern court, clarifying its power, and strengthening its role, Marshall served in the chief’s position for thirty-four years. One landmark case during his tenure changed the course of the judicial branch’s history (Figure 13.3).8
在当时普遍认为最高法院软弱无力的氛围下，首任首席大法官约翰· 杰伊 （John Jay）—— 《 联邦党人文集》 的作者之一，由乔治·华盛顿总统任命——辞去了职务，出任纽约州州长，后来又拒绝了约翰·亚当斯总统的连任邀请。 7 事实上，如果不是填补了杰伊拒绝的空缺的第四任首席大法官约翰· 马歇尔 （John Marshall），最高法院或许仍会处于汉密尔顿所说的“天然的虚弱”状态。马歇尔常被认为是现代最高法院的奠基人，他明确了最高法院的权力，并强化了最高法院的作用。他担任首席大法官长达 34 年。在他任职期间，一个具有里程碑意义的案件改变了司法部门的历史进程（ 图 13.3 ）。 8

Image A is of Justice John Jay. John is seated with his left hand on a book. Image B is of Justice John Marshall. John is standing, and holds a book is his right hand.

[.my2]
Figure 13.3 John Jay (a) was the first chief justice of the Supreme Court but resigned his post to become governor of New York. John Marshall (b), who served as chief justice for thirty-four years, is often credited as the major force in defining the modern court’s role in the U.S. governmental system.

[.my2]
图 13.3 约翰·杰伊 (a) 是美国最高法院的首任首席大法官，但他辞去职务，出任纽约州州长。约翰·马歇尔 (b) 担任首席大法官长达三十四年，他通常被认为是确立现代法院在美国政府体系中作用的主要力量。
In 1803, the Supreme Court declared for itself the power of judicial review, a power to which Hamilton had referred but that is not expressly mentioned in the Constitution. Judicial review is the power of the courts, as part of the system of checks and balances, to look at actions taken by the other branches of government and the states and determine whether they are constitutional. If the courts find an action to be unconstitutional, it becomes null and void. Judicial review was established in the Supreme Court case Marbury v. Madison, when, for the first time, the Court declared an act of Congress to be unconstitutional.9 Wielding this power is a role Marshall defined as the “very essence of judicial duty,” and it continues today as one of the most significant aspects of judicial power. Judicial review lies at the core of the court’s ability to check the other branches of government—and the states.

[.my2]
1803 年，最高法院确立了司法审查权，这项权力汉密尔顿曾提及，但宪法中并未明确规定。司法审查是法院作为权力制衡体系的一部分，审查其他政府部门和各州行为并判定其是否合宪的权力。如果法院认定某项行为违宪，则该行为无效。司法审查制度确立于最高法院的 “马伯里诉麦迪逊案”中，在该案中，最高法院首次宣布国会法案违宪。9 马歇尔将行使这项权力定义为“司法职责的精髓”，时至今日 ， 它仍然是司法权力最重要的方面之一。司法审查是法院制衡其他政府部门和各州的核心所在。

Since Marbury, the power of judicial review has continually expanded, and the Court has not only ruled actions of Congress and the president to be unconstitutional, but it has also extended its power to include the review of state and local actions. The power of judicial review is not confined to the Supreme Court but is also exercised by the lower federal courts and even the state courts. Any legislative or executive action at the federal or state level inconsistent with the U.S. Constitution or a state constitution can be subject to judicial review.10
自马伯里诉华盛顿案以来，司法审查权不断扩大，最高法院不仅裁定国会和总统的行为违宪，而且还将其权力扩展至审查州和地方政府的行为。司法审查权并非最高法院独有，下级联邦法院甚至州法院也行使该权力。任何与美国宪法或州宪法相抵触的联邦或州立法或行政行为都可能受到司法审查 。

Milestone  里程碑
Marbury v. Madison (1803)
马伯里诉麦迪逊案 （1803 年）
The Supreme Court found itself in the middle of a dispute between the outgoing presidential administration of John Adams and that of incoming president (and opposition party member) Thomas Jefferson. It was an interesting circumstance at the time, particularly because Jefferson and the man who would decide the case—John Marshall—were themselves political rivals.

[.my2]
最高法院发现自己卷入了即将卸任的总统约翰 ·亚当斯和即将上任的总统（也是反对党成员）托马斯 ·杰斐逊之间的争端。这在当时是一个有趣的局面，尤其因为杰斐逊和将要审理此案的约翰· 马歇尔本身就是政治对手。

President Adams had appointed William Marbury to a position in Washington, DC, but his commission was not delivered before Adams left office. So Marbury petitioned the Supreme Court to use its power under the Judiciary Act of 1789 and issue a writ of mandamus to force the new president’s secretary of state, James Madison, to deliver the commission documents. It was a task Madison refused to do. A unanimous Court under the leadership of Chief Justice John Marshall ruled that although Marbury was entitled to the job, the Court did not have the power to issue the writ and order Madison to deliver the documents, because the provision in the Judiciary Act that had given the Court that power was unconstitutional.11
亚当斯总统任命威廉·马伯里到华盛顿特区任职，但亚当斯卸任前，马伯里并未收到委任状。于是，马伯里向最高法院请愿，要求其依据 1789 年《司法法案》 行使权力，签发强制令，迫使新任总统的国务卿詹姆斯 ·麦迪逊交付委任状文件。麦迪逊拒绝执行。在首席大法官约翰·马歇尔的领导下，最高法院一致裁定，尽管马伯里有权获得该职位，但法院无权签发强制令，命令麦迪逊交付文件，因为《司法法案》中赋予法院该项权力的条款违宪。 11

Perhaps Marshall feared a confrontation with the Jefferson administration and thought Madison would refuse his directive anyway. In any case, his ruling shows an interesting contrast in the early Court. On one hand, it humbly declined a power—issuing a writ of mandamus—given to it by Congress, but on the other, it laid the foundation for legitimizing a much more important one—judicial review. Marbury never got his commission, but the Court’s ruling in the case has become more significant for the precedent it established: As the first time the Court declared an act of Congress unconstitutional, it established the power of judicial review, a key power that enables the judicial branch to remain a powerful check on the other branches of government.

[.my2]
或许马歇尔担心与杰斐逊政府发生冲突，并且认为麦迪逊无论如何都会拒绝他的指令。无论如何，他的裁决展现了早期最高法院一个有趣的对比。一方面，它谦逊地拒绝了国会赋予它的权力——签发强制令；另一方面，它却为一项更为重要的权力——司法审查——的合法化奠定了基础。马伯里最终未能获得委任状，但最高法院在该案中的裁决因其确立的先例而更具意义：作为最高法院首次宣布国会法案违宪，它确立了司法审查权，这项关键权力使司法部门能够继续对政府其他部门发挥强有力的制衡作用。

Consider the dual nature of John Marshall’s opinion in Marbury v. Madison: On one hand, it limits the power of the courts, yet on the other it also expanded their power. Explain the different aspects of the decision in terms of these contrasting results.

[.my2]
请思考约翰·马歇尔在“马伯里诉麦迪逊案”中的意见的双重性质 ： 一方面，它限制了法院的权力；另一方面，它又扩大了法院的权力。请根据这些相互矛盾的结果，解释该判决的不同方面。

THE COURTS AND PUBLIC POLICY
法院与公共政策
Even with judicial review in place, the courts do not always stand ready just to throw out actions of the other branches of government. More broadly, as Marshall put it, “it is emphatically the province and duty of the judicial department to say what the law is.”12 The United States has a common law system in which law is largely developed through binding judicial decisions. With roots in medieval England, the system was inherited by the American colonies along with many other British traditions.13 It stands in contrast to code law systems, which provide very detailed and comprehensive laws that do not leave room for much interpretation and judicial decision-making. With code law in place, as it is in many nations of the world, it is the job of judges to simply apply the law. But under common law, as in the United States, they interpret it. Often referred to as a system of judge-made law, common law provides the opportunity for the judicial branch to have stronger involvement in the process of law-making itself, largely through its ruling and interpretation on a case-by-case basis.

[.my2]
即使有了司法审查制度，法院也并非总是随时准备推翻其他政府部门的行为。更广泛地说，正如马歇尔所言，“解释法律是司法部门的职责所在。” 12 美国实行普通法体系，法律主要通过具有约束力的司法判决而形成。该体系起源于中世纪的英国，并连同许多其他英国传统一起被美洲殖民地继承。 13 这与成文法体系形成鲜明对比，成文法体系提供非常详细和全面的法律，几乎没有解释和司法决策的空间。在成文法体系下（如世界上许多国家），法官的职责仅仅是适用法律。但在普通法体系下（如美国），法官则负责解释法律。普通法通常被称为法官造法体系，它使司法部门有机会更深入地参与立法过程，主要是通过个案裁决和解释来实现的。

In their role as policymakers, Congress and the president tend to consider broad questions of public policy and their costs and benefits. But the courts consider specific cases with narrower questions, thus enabling them to focus more closely than other government institutions on the exact context of the individuals, groups, or issues affected by the decision. This means that while the legislature can make policy through statute, and the executive can form policy through regulations and administration, the judicial branch can also influence policy through its rulings and interpretations. As cases are brought to the courts, court decisions can help shape policy.

[.my2]
作为政策制定者，国会和总统倾向于考虑公共政策的宏观问题及其成本和收益。但法院审理的是具体案件，涉及更为具体的议题，因此能够比其他政府机构更深入地关注受判决影响的个人、群体或问题的具体情况。这意味着，立法机关可以通过立法制定政策，行政机关可以通过规章和行政措施制定政策，而司法机关也可以通过其判决和解释来影响政策。当案件提交法院时，法院的判决可以帮助塑造政策。

Consider health care, for example. In 2010, President Barack Obama signed into law the Patient Protection and Affordable Care Act (ACA), a statute that brought significant changes to the nation’s healthcare system. With its goal of providing more widely attainable and affordable health insurance and health care, “Obamacare” was hailed by some but soundly denounced by others as bad policy. People who opposed the law and understood that a congressional repeal would not happen any time soon looked to the courts for help. They challenged the constitutionality of the law in National Federation of Independent Business v. Sebelius, hoping the Supreme Court would overturn it.14 The practice of judicial review enabled the law’s critics to exercise this opportunity, even though their hopes were ultimately dashed when, by a narrow 5–4 margin, the Supreme Court upheld the health care law as a constitutional extension of Congress’s power to tax.

[.my2]
以医疗保健为例。2010 年，巴拉克· 奥巴马总统签署了《患者保护与平价医疗法案》 （ACA），该法案给美国的医疗保健体系带来了重大变革。奥巴马医改旨在提供更广泛、更经济实惠的医疗保险和医疗保健服务，因此受到一些人的赞扬，但也遭到另一些人的强烈谴责，认为这是一项糟糕的政策。反对该法案且明白国会短期内无法废除该法案的人们，转而寻求法院的帮助。他们在 “全国独立企业联合会诉塞贝柳斯案”（National Federation of Independent Business v. Sebelius） 中对该法案的合宪性提出质疑，希望最高法院能够推翻它。 14 司法审查制度使该法案的批评者得以行使这一权利，尽管他们的希望最终落空——最高法院以 5 比 4 的微弱优势裁定该医疗保健法案是国会征税权的合宪延伸。

Since this 2012 decision, the ACA has continued to face challenges, the most notable of which have also been decided by court rulings. It faced a setback in 2014, for instance, when the Supreme Court ruled in Burwell v. Hobby Lobby that, for religious reasons, some for-profit corporations could be exempt from the requirement that employers provide insurance coverage of contraceptives for their female employees.15 But the ACA also attained a victory in King v. Burwell, when the Court upheld the ability of the federal government to provide tax credits for people who bought their health insurance through an exchange created by the law.16
自 2012 年该决定以来，《平价医疗法案》（ACA）持续面临挑战，其中最引人注目的挑战也由法院裁决解决。例如，2014 年，最高法院在 “伯韦尔诉霍比罗比案”（Burwell v. Hobby Lobby） 中裁定，出于宗教原因，一些营利性公司可以免于承担雇主必须为女性员工提供避孕保险的义务，这给 ACA 带来了一次挫折。 15 但 ACA 也在“金诉伯韦尔案”（King v. Burwell） 中取得了一次胜利，最高法院在该案中维护了联邦政府向通过该法案设立的医保交易平台购买医疗保险的人提供税收抵免的权力。 16

With each ACA case it has decided, the Supreme Court has served as the umpire, upholding the law and some of its provisions on one hand, but ruling some aspects of it unconstitutional on the other. Both supporters and opponents of the law have claimed victory and faced defeat. In each case, the Supreme Court has further defined and fine-tuned the law passed by Congress and the president, determining which parts stay and which parts go, thus having its say in the way the act has manifested itself, the way it operates, and the way it serves its public purpose.

[.my2]
在每一起《平价医疗法案》（ACA）案件中， 最高法院都扮演着仲裁者的角色，一方面维护该法案及其部分条款的合法性，另一方面又裁定其某些方面违宪。该法案的支持者和反对者都曾宣称胜利，也曾遭遇失败。在每一起案件中，最高法院都对国会和总统通过的法案进行了进一步的阐释和完善，决定哪些部分保留，哪些部分删除，从而对该法案的实施方式、运作方式以及其服务于公共目的的方式施加影响。

Another recent massive impact in public policy was brought when the Supreme Court reversed the famous 1973 Roe v. Wade decision, which had clarified a woman’s right to reproductive freedom, including abortion. On June 24, 2022, the court vote 5-4 that the Constitution provided no protection for abortion. This decision pushed decisions about abortion rights to the states, which has resulted in a fragmentation of rights for women across the states.17
近期另一项对公共政策产生重大影响的事件是最高法院推翻了著名的 1973 年 “罗诉韦德案”判决。 该判决曾明确女性享有包括堕胎在内的生育自由权。2022 年 6 月 24 日，最高法院以 5 比 4 的投票结果裁定，宪法并未对堕胎提供任何保护。这一决定将堕胎权的决策权下放至各州，导致各州女性的权利出现碎片化。 17

In this same vein, the courts have become the key interpreters of the U.S. Constitution, continuously interpreting it and applying it to modern times and circumstances. For example, it was in 2015 that we learned a man’s threat to kill his ex-wife, written in rap lyrics and posted to her Facebook wall, was not a real threat and thus could not be prosecuted as a felony under federal law.18 Certainly, when the Bill of Rights first declared that government could not abridge freedom of speech, its framers could never have envisioned Facebook—or any other modern technology for that matter.

[.my2]
同样，法院已成为美国宪法的关键解释者，不断地对其进行诠释并将其应用于现代社会和各种情况。例如，2015 年，我们了解到一名男子用说唱歌词威胁要杀死他的前妻，并将威胁发布在她 Facebook 主页上，但这并非真正的威胁，因此不能根据联邦法律以重罪起诉。 18 当然，当《权利法案》最初宣布政府不得限制言论自由时，其制定者们绝对不可能预见到 Facebook——或者任何其他现代科技的出现。

But freedom of speech, just like many constitutional concepts, has come to mean different things to different generations, and it is the courts that have designed the lens through which we understand the Constitution in modern times. It is often said that the Constitution changes less by amendment and more by the way it is interpreted. Rather than collecting dust on a shelf, the nearly 230-year-old document has come with us into the modern age, and the accepted practice of judicial review has helped carry it along the way.

[.my2]
但言论自由，如同许多宪法概念一样，对不同世代而言意义各异，而正是法院塑造了我们现代理解宪法的视角。人们常说，宪法的改变与其说是源于修正，不如说是源于对其的解释。这部近230年历史的文件并没有被束之高阁，而是与我们一同步入现代，而司法审查这一公认的实践也为其发展提供了助力。

COURTS AS A LAST RESORT
法院作为最后的手段
While the U.S. Supreme Court and state supreme courts exert power over many when reviewing laws or declaring acts of other branches unconstitutional, they become particularly important when an individual or group comes before them believing there has been a wrong. A citizen or group that feels mistreated can approach a variety of institutional venues in the U.S. system for assistance in changing policy or seeking support. Organizing protests, garnering special interest group support, and changing laws through the legislative and executive branches are all possible, but an individual is most likely to find the courts especially well-suited to analyzing the particulars of a case.

[.my2]
美国最高法院和各州最高法院在审查法律或宣布其他部门的行为违宪时，对许多人拥有举足轻重的权力。但当个人或团体认为自己受到了不公正对待并向其提起诉讼时，它们的作用就显得尤为重要。感到自身权益受到侵害的公民或团体可以向美国体制内的各种机构寻求帮助，以改变政策或获得支持。组织抗议活动、争取特殊利益集团的支持以及通过立法和行政部门修改法律都是可行的途径，但个人最有可能发现，法院尤其适合分析案件的具体细节。

The adversarial judicial system comes from the common law tradition: In a court case, it is one party versus the other, and it is up to an impartial person or group, such as the judge or jury, to determine which party prevails. The federal court system is most often called upon when a case touches on constitutional rights. For example, when Samantha Elauf, a Muslim woman, was denied a job working for the clothing retailer Abercrombie & Fitch because a headscarf she wears as religious practice violated the company’s dress code, the Supreme Court ruled that her First Amendment rights had been violated, making it possible for her to sue the store for monetary damages.

[.my2]
对抗式司法制度源于普通法传统：在法庭案件中，一方当事人与另一方当事人对立，由公正的个人或团体（例如法官或陪审团）来决定哪一方胜诉。联邦法院系统通常在案件涉及宪法权利时才会介入。例如，穆斯林妇女萨曼莎· 埃劳夫 (Samantha Elauf) 因佩戴头巾违反服装零售商 Abercrombie & Fitch 的着装规定而被拒绝录用。最高法院裁定她的第一修正案权利受到侵犯，因此她可以起诉该商店并要求赔偿损失。

Elauf had applied for an Abercrombie sales job in Oklahoma in 2008. Her interviewer recommended her based on her qualifications, but she was never given the job because the clothing retailer wanted to avoid having to accommodate her religious practice of wearing a headscarf, or hijab. In so doing, the Court ruled, Abercrombie violated Title VII of the Civil Rights Act of 1964, which prohibits employers from discriminating on the basis of race, color, religion, sex, or national origin, and requires them to accommodate religious practices.19
2008 年，埃劳夫申请了俄克拉荷马州一家名为 Abercrombie 的服装店的销售职位。面试官根据她的资历推荐了她，但她最终未能获得这份工作，因为这家服装零售商为了避免为她佩戴头巾（或称希贾布）的宗教习俗提供便利，而选择不录用她。法院裁定，Abercrombie 的做法违反了 1964 年《民权法案》 第七章的规定。该法案禁止雇主基于种族、肤色、宗教、性别或国籍进行歧视，并要求雇主为员工的宗教习俗提供便利。 19

Rulings like this have become particularly important for members of religious minority groups, including Muslims, Sikhs, and Jews, who now feel more protected from employment discrimination based on their religious attire, head coverings, or beards.20 Such decisions illustrate how the expansion of individual rights and liberties for particular persons or groups over the years has come about largely as a result of court rulings made for individuals on a case-by-case basis.

[.my2]
此类裁决对包括穆斯林、锡克教徒和犹太教徒在内的宗教少数群体成员尤为重要，他们现在感到自身权益得到了更多保障，免受因宗教服饰、头巾或胡须而遭受的就业歧视 。 20 此类判决表明，多年来，特定个人或群体权利和自由的扩展，很大程度上得益于法院针对个案作出的裁决。

Although the United States prides itself on the Declaration of Independence’s statement that “all men are created equal,” and “equal protection of the laws” is a written constitutional principle of the Fourteenth Amendment, the reality is less than perfect. But it is evolving. Changing times and technology have and will continue to alter the way fundamental constitutional rights are defined and applied, and the courts have proven themselves to be crucial in that definition and application.

[.my2]
尽管美国以《独立宣言》中“人人生而平等”的宣言为傲，且“法律面前人人平等”也是第十四修正案中一项明确的宪法原则，但现实远非完美。不过，情况正在不断变化。时代和科技的变迁已经并将继续改变基本宪法权利的定义和适用方式，而法院在这些定义和适用过程中也发挥了至关重要的作用。

Societal traditions, public opinion, and politics have often stood in the way of the full expansion of rights and liberties to different groups, and not everyone has agreed that these rights should be expanded as they have been by the courts. Schools were long segregated by race until the Court ordered desegregation in Brown v. Board of Education (1954), and even then, many stood in opposition and tried to block students at the entrances to all-White schools.21 Factions have formed on opposite sides of the abortion and handgun debates, because many do not agree that women should have abortion rights or that individuals should have the right to a handgun. People disagree about whether members of the LGBTQ community should be allowed to marry or whether arrested persons should be read their rights, guaranteed an attorney, and/or have their cell phones protected from police search.

[.my2]
社会传统、公众舆论和政治因素常常阻碍不同群体权利和自由的全面扩展，而且并非所有人都认同法院所扩展的这些权利。学校长期以来实行种族隔离，直到最高法院在布朗诉教育委员会案 （1954 年）中下令取消种族隔离，即便如此，仍有许多人反对，试图阻止学生进入全白人学校。在堕胎和手枪辩论中，由于许多人不认同女性应该拥有堕胎权或个人应该拥有持枪权，因此形成了对立的派别。人们对于 LGBTQ 群体成员是否应该被允许结婚，以及被捕者是否应该被告知其权利、是否应该获得律师协助和/或是否应该保护其手机免受警方搜查等问题也存在分歧。

But the Supreme Court has ruled in favor of all these issues and others. Even without unanimous agreement among citizens, Supreme Court decisions have made all these possibilities a reality, a particularly important one for the individuals who become the beneficiaries (Table 13.1). The judicial branch has often made decisions the other branches were either unwilling or unable to make, and Hamilton was right in Federalist No. 78 when he said that without the courts exercising their duty to defend the Constitution, “all the reservations of particular rights or privileges would amount to nothing.”
但最高法院已就所有这些问题以及其他问题作出了有利于己方的裁决。即使公民之间未能达成一致，最高法院的判决也使所有这些可能性成为现实，这对最终受益的个人而言尤为重要（ 表 13.1 ）。司法部门常常做出其他部门不愿或不能做出的决定， 汉密尔顿在 《联邦党人文集》 第 78 篇中指出，如果法院不履行捍卫宪法的职责，“所有对特定权利或特权的保留都将毫无意义”，他的观点是正确的。

Examples of Supreme Court Cases Involving Individuals
涉及个人的最高法院案例示例
Case Name  案例名称	Year  年	Court’s Decision  法院裁决
Brown v. Board of Education
布朗诉教育委员会案	1954	Public schools must be desegregated.

[.my2]
公立学校必须取消种族隔离。
Gideon v. Wainwright  吉迪恩诉温赖特	1963	Poor criminal defendants must be provided an attorney.

[.my2]
贫困的刑事被告人必须获得律师帮助。
Miranda v. Arizona  米兰达诉亚利桑那州案	1966	Criminal suspects must be read their rights.

[.my2]
必须告知犯罪嫌疑人其享有的权利。
Roe v. Wade  罗诉韦德案
(reversed in Dobbs v. Jackson Women's Health Organization)
（在 Dobbs 诉 Jackson 妇女健康组织一案中被推翻）	1973
(2022)	Women have a constitutional right to abortion.

[.my2]
女性享有堕胎的宪法权利。
(right removed in 2022)  （右侧于2022年移除）
McDonald v. Chicago  麦克唐纳诉芝加哥	2010	An individual has the right to a handgun in his or her home.

[.my2]
个人有权在自己家中拥有手枪。
Riley v. California  莱利诉加利福尼亚州	2014	Police may not search a cell phone without a warrant.

[.my2]
没有搜查令，警方不得搜查手机。
Obergefell v. Hodges  奥贝格费尔诉霍奇斯案	2015	Same-sex couples have the right to marry in all states.

[.my2]
同性伴侣在所有州都享有结婚的权利。
Table 13.1 Over time, the courts have made many decisions that have broadened the rights of individuals. This table is a sampling of some of these Supreme Court cases.

[.my2]
表 13.1 随着时间的推移，法院做出了许多扩大个人权利的判决。本表列举了部分最高法院的案例。
The courts seldom if ever grant rights to a person instantly and upon request. In a number of cases, they have expressed reluctance to expand rights without limit, and they still balance that expansion with the government’s need to govern, provide for the common good, and serve a broader societal purpose. For example, the Supreme Court has upheld the constitutionality of the death penalty, ruling that the Eighth Amendment does not prevent a person from being put to death for committing a capital crime and that the government may consider “retribution and the possibility of deterrence” when it seeks capital punishment for a crime that so warrants it.22 In other words, there is a greater good—more safety and security—that may be more important than sparing the life of an individual who has committed a heinous crime.

[.my2]
法院几乎从不立即应个人请求授予其权利。在许多案例中，法院都表示不愿无限制地扩大权利，并且仍然需要在权利扩张与政府治理、维护公共利益以及服务于更广泛的社会目标之间取得平衡。例如，最高法院维护了死刑的合宪性，裁定第八修正案并未阻止对犯有死罪的人处以死刑，并且政府在寻求对犯有死罪的人判处死刑时，可以考虑“报复和威慑的可能性”。 22 换句话说，存在一种更大的利益——更多的安全保障——可能比饶恕犯下滔天罪行的人的生命更为重要。

Yet the Court has also put limits on the ability to impose the death penalty, ruling, for example, that the government may not execute a person with cognitive disabilities, a person who was under eighteen at the time of the crime, or a child rapist who did not kill his victim.23 So the job of the courts on any given issue is never quite done, as justices continuously keep their eye on government laws, actions, and policy changes as cases are brought to them and then decide whether those laws, actions, and policies can stand or must go. Even with an issue such as the death penalty, about which the Court has made several rulings, there is always the possibility that further judicial interpretation of what does (or does not) violate the Constitution will be needed.

[.my2]
然而，最高法院也对死刑的适用范围做出了限制，例如裁定政府不得处决认知障碍者、犯罪时未满十八岁的人，或未杀害受害者的儿童强奸犯。 23 因此，法院在任何特定问题上的职责都永无止境，因为大法官们会持续关注政府的法律、行为和政策变化，并在案件提交到他们面前时，决定这些法律、行为和政策是否有效或必须废除。即使是像死刑这样最高法院已做出多项裁决的问题，也始终存在需要进一步司法解释哪些行为（或不行为）违反宪法的可能性。

This happened, for example, as recently as 2015 in a case involving the use of lethal injection as capital punishment in the state of Oklahoma, where death-row inmates are put to death through the use of three drugs—a sedative to bring about unconsciousness (midazolam), followed by two others that cause paralysis and stop the heart. A group of these inmates challenged the use of midazolam as unconstitutional. They argued that since it could not reliably cause unconsciousness, its use constituted an Eighth Amendment violation against cruel and unusual punishment and should be stopped by the courts. The Supreme Court rejected the inmates’ claims, ruling that Oklahoma could continue to use midazolam as part of its three-drug protocol.24 But with four of the nine justices dissenting from that decision, a sharply divided Court leaves open a greater possibility of more death-penalty cases to come. The 2015–2016 session alone includes four such cases, challenging death-sentencing procedures in such states as Florida, Georgia, and Kansas.25 In another recent case, Bucklew v. Precythe (2019), the court again rejected an Eighth Amendment claim of the death penalty as torture.26 Yet, while case outcomes would suggest that it is easier, not harder, to carry out the death penalty, the number of executions across the U.S. has plummeted in recent years.27
例如，就在 2015 年，俄克拉荷马州就曾发生过一起涉及注射死刑的案件。在该州，死刑犯被执行死刑时会注射三种药物：一种是镇静剂（咪达唑仑），使犯人失去意识；另外两种药物则会导致麻痹并停止心脏跳动。部分死刑犯质疑使用咪达唑仑违宪。他们认为，由于咪达唑仑无法可靠地使犯人失去意识，因此其使用违反了美国宪法第八修正案中关于禁止残酷和非常规惩罚的规定，应由法院予以制止。最高法院驳回了这些死刑犯的诉求，裁定俄克拉荷马州可以继续在其三药注射方案中使用咪达唑仑。 24 但由于九名大法官中有四名反对该裁决，最高法院内部的严重分歧使得未来出现更多死刑案件的可能性大大增加。仅 2015-2016 年度，此类案件就包括四起，挑战了佛罗里达州、佐治亚州和堪萨斯州等州的死刑判决程序。 25 在另一起近期案件“ 巴克卢诉普雷西斯案” （2019 年）中，法院再次驳回了原告提出的死刑构成酷刑的第八修正案主张。 26 然而，尽管案件结果似乎表明执行死刑更容易而非更难，但近年来美国各地的死刑执行数量却大幅下降。 27

Therefore, we should not underestimate the power and significance of the judicial branch in the United States. Today, the courts have become a relevant player, gaining enough clout and trust over the years to take their place as a separate yet coequal branch.

[.my2]
因此，我们不应低估美国司法部门的权力和重要性。如今，法院已成为举足轻重的角色，经过多年的发展，其影响力和公信力已足以使其成为一个独立但平等的机构。

'''