
= 014-5 County and City Government 县市政府
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




County and city governments make up an important component of the overall structure of the government. Not only do they affect citizens directly; it is also easier for citizens to interact with local government officials because their offices and the community’s school board or city council meetings are often close by. Despite this fact, voter turnout in local elections tends to be lower than in state and national elections. Municipal and county governments differ in structure and purpose in several ways.

[.my2]
县市政府是政府整体结构的重要组成部分。它们不仅直接影响公民，而且由于政府办公室和社区教育委员会或市议会会议通常就在附近，公民也更容易与地方政府官员互动。尽管如此，地方选举的投票率往往低于州和全国选举。市县政府在结构和职能方面存在诸多差异。

COUNTY GOVERNMENT  县政府
County governments serve a larger geographical area than cities and towns, but a smaller area than states. They are created by the state government and typically operate under provisions set out in the state constitution. As such, they are essentially administrative units of the state. Census estimates from 2012 indicate that there are just over three thousand counties in the United States.82 County systems usually take one of three basic forms: the commission system, the council-administrator system, and the council-elected executive system.

[.my2]
县政府的管辖范围比城市和城镇大，但比州小。它们由州政府设立，通常依据州宪法的规定运作。因此，它们本质上是州的行政单位。2012 年的人口普查估计数据显示，美国有三千多个县。 县级行政系统通常采用三种基本形式：委员会制、议会-行政官制和议会选举产生的行政长官制。

The most common form of county government is the commission system. Under this structure, an elected commission, which generally consists of a small number of commissioners, serves as the governing body within the county, performing all legislative and executive functions. These include adopting a budget, passing county resolutions, and hiring and firing county officials.83
县级政府最常见的形式是委员会制 。在这种体制下，一个由少数委员组成的民选委员会作为县级政府机构，履行所有立法和行政职能，包括通过预算、颁布县级决议以及任免县级官员 。83

Under the council-administrator system, the voters elect council members to serve for a specified period of time, and the council in turn appoints an administrator to oversee the operation of the government. The administrator serves at the directive of the council and can be terminated by the council. The goal of this arrangement is to divide administrative and policymaking responsibilities between the elected council and the appointed administrator.84
在议会-行政官体制下，选民选举议员，任期固定；议会再任命一名行政官来监督政府运作。行政官听命于议会，并可由议会解职。这种安排旨在将行政和政策制定职责在民选议会和任命的行政官之间进行划分 。84

Under a council-elected executive system, the voters elect both the members of the council and the executive. The executive performs functions similar to those of the state governor. For instance, the executive can veto the actions of the council, draft a budget, and provide suggestions regarding public policy.85
在议会选举产生的行政体制下，选民既选举议会成员，也选举行政长官。行政长官的职能与州长类似。例如，行政长官可以否决议会的决议、制定预算，并就公共政策提出建议 。85

Although the tasks they perform can vary from state to state, most counties have a courthouse that houses county officials, such as the sheriff, the county clerk, the assessor, the treasurer, the coroner, and the engineer. These officials carry out a variety of important functions and oversee the responsibilities of running a county government. For instance, the county coroner investigates the cause of death when suspicious circumstances are present. The county clerk oversees the registration of voters and also certifies election results for the county. In addition, this officeholder typically keeps the official birth, death, and marriage records. The county treasurer oversees the collection and distribution of funds within the county, while the county assessor conducts property tax evaluations and informs individual citizens or business owners of their right to contest the appraised value of their property. Finally, a county engineer will oversee the maintenance and construction of county infrastructure.86 In short, counties help to maintain roads and bridges, courthouses and jails, parks and pools, and public libraries, hospitals, and clinics.87 To provide these services, county governments typically rely on property tax revenue, a portion of sales tax receipts, and funds from intergovernmental transfers by way of federal or state grants.

[.my2]
尽管各州的职责可能有所不同，但大多数县都设有法院，县级官员，例如警长、县书记员、评估员、财务主管、验尸官和工程师，都在此办公。这些官员履行着各种重要职能，并负责监督县政府的日常运作。例如，县验尸官负责调查可疑死亡原因。县书记员负责选民登记，并认证县选举结果。此外，该官员通常还负责保管官方的出生、死亡和婚姻记录。县财务主管负责监督县内资金的征收和分配，而县评估员则负责进行房产税评估，并告知个人或企业主其有权对房产评估价值提出异议。最后，县工程师负责监督县级基础设施的维护和建设。 简而言之 ，县级政府负责维护道路和桥梁、法院和监狱、公园和游泳池，以及公共图书馆、医院和诊所等公共设施。 87 为了提供这些服务，县政府通常依靠财产税收入、一部分销售税收入以及通过联邦或州拨款进行的政府间转移资金。

CITY GOVERNMENT  市政府
Municipal governments oversee the operation and functions of cities and towns. Census estimates for 2012 show just over 19,500 municipal governments and nearly 16,500 township governments in the United States.88 The vast majority of municipal governments operate on one of two governing models: a mayor-council system or a council-manager system.

[.my2]
市政当局负责监督城镇的运作和职能。2012 年的人口普查估计数据显示，美国有超过 19,500 个市政当局和近 16,500 个乡镇政府 。88 绝大多数市政当局采用两种治理模式之一：市长-议会制或议会-经理制。

Under the mayor-council system voters elect both a mayor and members of the city council. The city council performs legislative functions and the mayor the executive functions. Under this system, the mayor may be given a great deal of authority or only limited powers.89 Under a strong mayor system, the mayor will be able to veto the actions of the council, appoint and fire the heads of city departments, and produce a budget. Under a weak mayor system, the mayor has little authority compared to the council and acts in a ceremonial capacity as a spokesperson for the city.90
在市长-议会制下，选民选举市长和市议会成员。市议会行使立法职能，市长行使行政职能。在这种制度下，市长可能被赋予很大的权力，也可能只有有限的权力。 89 在强市长制下，市长可以否决市议会的决议，任命和解雇各部门负责人，并制定预算。在弱市长制下，市长的权力远小于市议会，主要作为市政府的发言人履行礼仪性职责。 90

In a council-manager system of government, either the members of the city council are elected by voters along with a mayor who presides over the council, or the voters elect members of the city council and the mayor is chosen from among them. In either case, the city council will then appoint a city manager to carry out the administrative functions of the municipal government. This frees the city council to address political functions such as setting policy and formulating the budget.91
在议会-经理制政府体系中，要么市议会成员和市长均由选民选举产生，市长主持议会；要么选民选举市议会成员，市长从议员中选出。无论哪种情况，市议会都会任命一名城市经理来履行市政管理职能。这使得市议会能够腾出精力处理诸如制定政策和编制预算等政治职能 。91

Municipal governments are responsible for providing clean water as well as sewage and garbage disposal. They must maintain city facilities, such as parks, streetlights, and stadiums (Figure 14.19). In addition, they address zoning and building regulations, promote the city’s economic development, and provide law enforcement, public transportation, and fire protection. Municipal governments typically rely on property tax revenue, user fees from trash collection and the provision of water and sewer services, a portion of sales tax receipts, and taxes on business.

[.my2]
市政府负责提供清洁用水以及污水和垃圾处理服务。它们必须维护城市设施，例如公园、路灯和体育场馆（ 图 14.19 ）。此外，它们还负责制定分区和建筑法规，促进城市经济发展，并提供执法、公共交通和消防服务。市政府通常依靠房产税收入、垃圾收集和供水/污水处理服务的用户费用、部分销售税收入以及商业税。

An image of the inside of a stadium. The stands are filled with people.

[.my2]
Figure 14.19 The Sporting Park in Kansas City, Kansas, is home to various sporting events. The stadium first opened for business in 2011, and taxpayers financed $146 million of the total cost to build the stadium, an office park, and a youth soccer complex.92 (credit: Wesley Fryer)
图 14.19 位于堪萨斯州堪萨斯城的体育公园是举办各种体育赛事的场所。该体育场于 2011 年首次投入使用，纳税人出资 1.46 亿美元，用于建造体育场、办公园区和青少年足球中心 。92 （图片来源：Wesley Fryer）
Link to Learning  学习链接
The International City/County Management Association (ICMA) provides networking opportunities, professional development, and statistical data in order to support local government leaders and other individuals throughout the world. Visit the ICMA Leadership page to learn what makes a better leader and how you might improve your local community.

[.my2]
国际城市/县级管理协会 (ICMA) 为世界各地的当地政府领导人和其他人士提供交流机会、专业发展机会和统计数据。访问 ICMA 领导力页面，了解如何成为一名优秀的领导者，以及如何改善您所在的社区。


'''