
= 014-1 State Power and Delegation 国家权力和授权
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义





When the framers met at the Constitutional Convention in 1787, they had many competing tensions to resolve. For instance, they had to consider how citizens would be represented in the national government, given population differences between the states. In addition, they had to iron out differences of opinion about where to concentrate political power. Would the legislative branch have more authority than the executive branch, and would state governments retain as many rights as they had enjoyed under the Articles of Confederation?
1787年制宪会议召开时，制宪者们面临着诸多相互冲突的难题。例如，鉴于各州人口差异，他们必须考虑如何确保公民在联邦政府中的代表性。此外，他们还必须就政治权力的集中方向达成共识。立法部门的权力是否应大于行政部门？各州政府是否应保留《邦联条例》下享有的所有权利？

Here we look at the manner in which power was divided between the national and state governments, first under the Articles of Confederation and then under the U.S. Constitution. As you read, observe the shifting power dynamic between the national government and subnational governments at the state and local level.

[.my2]
本文将探讨在《邦联条例》和《美国宪法》框架下，国家政府和州政府之间的权力划分方式。阅读时，请注意国家政府与州和地方政府之间权力动态的演变。

STATE POWER AT THE FOUNDING
建国之初的国家权力
Before the ratification of the Constitution, the state governments’ power far exceeded that held by the national government. This distribution of authority was the result of a conscious decision and was reflected in the structure and framework of the Articles of Confederation. The national government was limited, lacking both a president to oversee domestic and foreign policy and a system of federal courts to settle disputes between the states.

[.my2]
在宪法批准之前，各州政府的权力远远超过联邦政府。这种权力分配是经过深思熟虑的决定，并体现在 《邦联条例》 的结构和框架中。联邦政府权力有限，既没有总统来统筹内政外交，也没有联邦法院系统来解决各州之间的争端。

Restricting power at the national level gave the states a great deal of authority over and independence from the federal government. Each state legislature appointed its own Congressional representatives, subject to recall by the states, and each state was given the authority to collect taxes from its citizens. But limiting national government power was not the delegates’ only priority. They also wanted to prevent any given state from exceeding the authority and independence of the others. The delegates ultimately worked to create a level playing field between the individual states that formed the confederation. For instance, the Articles of Confederation could not be amended without the approval of each state, and each state received one vote in Congress, regardless of population.1
限制国家层面的权力赋予各州极大的自主权，使其能够独立于联邦政府之外。每个州的立法机构都任命自己的国会代表，这些代表可由各州罢免；每个州也被赋予向其公民征税的权力。但限制联邦政府的权力并非代表们的唯一目标。他们还希望防止任何一个州凌驾于其他州的权力和独立性之上。最终，代表们致力于在组成邦联的各个州之间创造一个公平的竞争环境。例如，《邦联条例》未经各州批准不得修改，而且无论人口多少，每个州在国会中都只有一票。

It wasn’t long after the Articles of Confederation were established that cracks began to appear in their foundation. Congress struggled to conduct business and to ensure the financial credibility of the new country’s government. One difficulty was its inability to compel the individual states to cover their portion of Revolutionary War debt. Attempts to recoup these funds through the imposition of tariffs were vetoed by states with a vested financial interest in their failure.2
《邦联条例》颁布后不久，其根基便开始出现裂痕。国会努力维持运转，并确保新国家政府的财政信誉。其中一个难题是，国会无力强制各州偿还其应承担的独立战争债务。试图通过征收关税来收回这些资金的尝试，遭到了那些在债务偿还中拥有既得利益的州的否决。

Given the inherent weaknesses in the system set up by the Articles, in 1787 the delegates came together once again to consider amendments to the Articles, but they ended up instead considering a new design for the government (Figure 14.2). To produce more long-term stability, they needed to establish a more effective division of power between the federal and state governments. Ultimately, the framers settled on a system in which power would be shared: The national government had its core duties, the state governments had their duties, and other duties were shared equally between them. Today this structure of power sharing is referred to as federalism.

[.my2]
鉴于《邦联条例》所建立的体系存在固有缺陷，1787 年，代表们再次齐聚一堂，商讨对《邦联条例》的修正，但最终却转而考虑一种新的政府架构（ 图 14.2 ）。为了实现更长期的稳定，他们需要在联邦政府和州政府之间建立更有效的权力划分。最终，制宪者们确定了一种权力共享的体系：联邦政府承担其核心职责，州政府承担其职责，其他职责则由两者平均分担。如今，这种权力共享的结构被称为联邦制 。

An image of an original handwritten version of the Articles of Confederation.

[.my2]
Figure 14.2 The Articles of Confederation, written in 1777 and adopted in 1781, established the first government of the United States. The Articles were replaced by the Constitution in 1787.

[.my2]
图 14.2 《邦联条例》于 1777 年制定，1781 年通过，建立了美国第一届政府。该条例于 1787 年被《宪法》取代。
The Constitution allocated more power to the federal government by effectively adding two new branches: a president to head the executive branch and the Supreme Court to head the judicial branch. The specific delegated or expressed powers granted to Congress and to the president were clearly spelled out in the body of the Constitution under Article I, Section 8, and Article II, Sections 2 and 3.

[.my2]
宪法赋予联邦政府更多权力，实际上增加了两个新的分支：总统领导行政部门，最高法院领导司法部门。宪法第一条第八款和第二条第二款 、第三款明确规定了授予国会和总统的具体权力 。

In addition to these expressed powers, the national government was given implied powers that, while not clearly stated, are inferred. These powers stem from the elastic clause in Article I, Section 8, of the Constitution, which provides Congress the authority “to make all Laws which shall be necessary and proper for carrying into Execution the Foregoing powers.” This statement has been used to support the federal government’s playing a role in controversial policy matters, such as the provision of healthcare, the expansion of power to levy and collect taxes, and regulation of interstate commerce. Finally, Article VI declared that the U.S. Constitution and any laws or treaties made in connection with that document were to supersede constitutions and laws made at the state level. This clause, better known as the supremacy clause, makes clear that any conflict in law between the central (or federal) government and the regional (or state) governments is typically resolved in favor of the central government.

[.my2]
除了这些明示的权力之外，联邦政府还被赋予了一些隐含的权力 ，这些权力虽然没有明确规定，但却是可以推断出来的。这些权力源于宪法第一条第八款中的弹性条款 ，该条款赋予国会“制定一切为执行前述权力所必需和适当的法律”的权力。这一表述被用来支持联邦政府在一些有争议的政策问题上发挥作用，例如提供医疗保健、扩大征税权以及监管州际贸易。最后， 第六条规定，美国宪法以及与该宪法相关的任何法律或条约都优先于各州制定的宪法和法律。这一条款，即更为人熟知的 “最高条款” ，明确规定，中央（或联邦政府）政府与地方（或州）政府之间的任何法律冲突，通常都以中央政府的利益为先。

Although the U.S. Constitution clearly allocated more power to the federal government than had been the case under the Articles of Confederation, the framers still respected the important role of the states in the new government. The states were given a host of powers independent of those enjoyed by the national government. As one example, they now had the power to establish local governments and to account for the structure, function, and responsibilities of these governments within their state constitutions. This gave states sovereignty, or supreme and independent authority, over county, municipal, school and other special districts.

[.my2]
尽管美国宪法赋予联邦政府的权力明显大于邦联条例时期，但制宪者仍然尊重各州在新政府中的重要作用。各州被赋予了许多独立于联邦政府的权力。例如，各州现在有权设立地方政府，并在州宪法中规定这些政府的结构、职能和职责。这赋予了各州对县、市、学区和其他特殊区域的主权，即至高无上的独立权力。

States were also given the power to ratify amendments to the U.S. Constitution. Throughout U.S. history, all amendments to the Constitution except one have been proposed by Congress and then ratified by either three-fourths of the state legislatures or three-fourths of the state conventions called for ratification purposes. This process ensures that the states have a voice in any changes to the Constitution. The Twenty-First Amendment (repealing the Eighteenth Amendment’s prohibition on alcohol) was the only amendment ratified using the state ratifying convention method. Although this path has never been taken, the U.S. Constitution even allows for state legislatures to take a direct and very active role in the amendment proposal process. If at least two-thirds of the state legislatures apply for a national convention, constitutional amendments can be proposed at the convention.

[.my2]
各州也被赋予了批准美国宪法修正案的权力。纵观美国历史，除一项修正案外，所有宪法修正案均由国会提出，然后由四分之三的州议会或四分之三的州代表大会批准。这一程序确保各州在任何宪法修改中都拥有发言权。第二十一条修正案（废除第十八条修正案中关于禁酒的禁令）是唯一一条通过州代表大会批准的修正案。尽管从未有人采用过这种方式，但美国宪法甚至允许州议会在修正案提案过程中发挥直接且积极的作用。如果至少三分之二的州议会申请召开全国代表大会，则可以在大会上提出宪法修正案。

Finding a Middle Ground
寻找折衷方案
Debating the Need for a National Convention
辩论是否需要召开全国代表大会
As of 2020, fifteen states had passed applications to hold a national convention. These states are pushing for the opportunity to propose a constitutional amendment requiring the national government to balance its budget in the same way most states are mandated to do. For a national convention to be held, at least thirty-four states must submit applications. Thus, nineteen more states would be needed to hold the first national convention in U.S. history.3
截至 2020 年，已有 15 个州通过了召开全国制宪会议的申请。这些州正积极争取机会，提出一项宪法修正案，要求联邦政府像大多数州一样，必须平衡预算。要召开全国制宪会议，至少需要 34 个州提交申请。 因此 ，还需要 19 个州才能召开美国历史上第一次全国制宪会议。

Proponents see the convention as an opportunity to propose an amendment they argue is necessary to reduce federal spending and promote fiscal responsibility. The exploding Federal budget deficit adds to these concerns and may create more support for such a process. If not, proponents nevertheless believe the growing roster of states favoring a convention may encourage Congress to take action on its own.

[.my2]
支持者认为，此次制宪会议是提出一项修正案的良机，他们认为这项修正案对于削减联邦开支、促进财政责任至关重要。联邦预算赤字的急剧膨胀加剧了这些担忧，并可能促使更多人支持召开制宪会议。即便如此，支持者仍然相信，越来越多的州支持召开制宪会议，这或许会促使国会主动采取行动。

Opponents feel a balanced budget amendment is not realistic given the need for emergency spending in the event of an economic recession. They also worry about the spending cuts and/or tax increases the federal government would have to impose to consistently balance the budget. Some states fear a balanced-budget requirement would limit the federal government’s ability to provide them with continued fiscal support. Finally, other opponents argue that states balance only their operating budgets, while themselves assuming massive amounts of debt for capital projects.

[.my2]
反对者认为，考虑到经济衰退时需要紧急支出，平衡预算修正案并不现实。他们还担心联邦政府为了持续平衡预算，不得不削减开支和/或增加税收。一些州担心，平衡预算的要求会限制联邦政府继续向它们提供财政支持的能力。最后，还有一些反对者认为，各州只平衡其运营预算，而自身却承担了巨额债务用于资本项目。

But perhaps the greatest fear is of the unknown. A national convention is unprecedented, and there is no limit to the number of amendments delegates to such a convention might propose. However, such changes would still need to be ratified by three-fourths of the state legislatures or state conventions before they could take effect.

[.my2]
但或许最大的恐惧在于未知。召开全国制宪会议史无前例，与会代表提出的修正案数量没有上限。然而，这些修正案仍需经四分之三的州议会或州制宪会议批准才能生效。

What are the potential benefits of a national constitutional convention? What are the risks? Are the benefits worth the risks? Why or why not?
召开全国制宪会议有哪些潜在好处？有哪些风险？这些好处是否值得承担这些风险？为什么？

Despite the Constitution’s broad grants of state authority, one of the central goals of the Anti-Federalists, a group opposed to several components of the Constitution, was to preserve state government authority, protect the small states, and keep government power concentrated in the hands of the people. For this reason, the Tenth Amendment was included in the Bill of Rights to create a class of powers, known as reserved powers, exclusive to state governments. The amendment specifically reads, “The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people.” In essence, if the Constitution does not decree that an activity should be performed by the national government and does not restrict the state government from engaging in it, then the state is seen as having the power to perform the function. In other words, the power is reserved to the states.

[.my2]
尽管宪法赋予各州广泛的权力，但反对宪法若干条款的反联邦主义者的核心目标之一，便是维护州政府的权力，保护小州，并将政府权力集中在人民手中。因此，权利法案中加入了第十修正案 ，设立了一类专属于州政府的权力，即保留权力 。该修正案明确规定：“宪法未授予合众国，也未禁止各州行使的权力，均由各州或人民保留。” 简而言之，如果宪法既未规定某项活动应由联邦政府行使，也未限制州政府行使，那么州政府就被视为拥有行使该项职能的权力。换言之，这项权力保留给各州。

Besides reserved powers, the states also retained concurrent powers, or responsibilities shared with the national government. As part of this package of powers, the state and federal governments each have the right to collect income tax from their citizens and corporate tax from businesses. They also share responsibility for building and maintaining the network of interstates and highways and for making and enforcing laws (Figure 14.3). For instance, many state governments have laws regulating motorcycle and bicycle helmet use, banning texting and driving, and prohibiting driving under the influence of drugs or alcohol.

[.my2]
除了保留权力外，各州还保留了与联邦政府共同拥有的权力，即共同承担的责任。作为这一系列权力的一部分，州政府和联邦政府都有权向其公民征收个人所得税，并向企业征收公司税。它们还共同负责建设和维护州际公路和高速公路网络，以及制定和执行法律（ 图 14.3 ）。例如，许多州政府都制定了法律，规范摩托车和自行车头盔的使用，禁止开车时发短信，并禁止酒后或吸毒后驾驶。

On the left is an image of a sign that reads “No texting while driving”. On the right is an image of a person in the driver’s seat of a vehicle. The person is holding a phone in their hand and looking at it.

[.my2]
Figure 14.3 State (and sometimes local) governments regulate items having to do with highway safety, such as laws against cellphone use while driving. (credit right: modification of work by “Lord Jim”/Flickr)
图 14.3 州（有时是地方）政府对与公路安全相关的事项进行监管，例如禁止驾驶时使用手机的法律。（图片来源：改编自“Lord Jim”/Flickr 的作品）
THE EVOLUTION OF STATE POWER
国家权力的演变
Throughout U.S. history, the national and state governments have battled for dominance over the implementation of public policy and the funding of important political programs. Upon taking office in 1933 during the Great Depression (1929–1939), President Franklin D. Roosevelt initiated a series of legislative proposals to boost the economy and put people back to work. The enacted programs allowed the federal government to play a broader role in revitalizing the economy while greatly expanding its power. However, this result was not without its critics. Initially, the Supreme Court overturned several key legislative proposals passed under Roosevelt, reasoning that they represented an overreach of presidential authority and were unconstitutional, such as Schechter Poultry Corp. v. United States.4 Eventually, however, the Supreme Court shifted direction to reflect public opinion, which was decisively behind the president and the need for government intervention in a time of economic turmoil.5
纵观美国历史，联邦政府和州政府一直在争夺公共政策实施和重要政治项目资金的控制权。1933 年，正值大萧条时期（1929-1939 年），富兰克林· 罗斯福总统上任后，推出了一系列旨在提振经济、创造就业机会的立法提案。这些提案的通过使联邦政府在重振经济方面发挥了更广泛的作用，同时也极大地扩展了其权力。然而，这一结果并非没有争议。最初，最高法院推翻了罗斯福总统时期通过的几项关键立法提案，理由是这些提案代表了总统权力的过度扩张，并且违宪，例如“谢克特家禽公司诉美国案” （Schechter Poultry Corp. v. United States） 。 4 然而，最终最高法院的立场发生了转变，反映了公众舆论，公众舆论坚定地支持总统以及在经济动荡时期政府干预的必要性。 5

Just three decades later, during the 1964 presidential election campaign, incumbent President Lyndon B. Johnson declared a “War on Poverty,” instituting a package of Great Society programs designed to improve circumstances for lower-income Americans across the nation. The new programs included Medicare and Medicaid, which are health insurance programs for seniors and low-income citizens respectively, and the food stamp program, which provides food assistance to low-income families. These initiatives greatly expanded the role of the federal government in providing a social safety net.6 State and local governments became partners in their implementation and also came to rely on the financial support they received from the federal government in the form of program grants.7
仅仅三十年后，在 1964 年总统竞选期间，时任总统林登· 约翰逊宣布发起“ 向贫困宣战 ”，并推行了一系列旨在改善全美低收入美国人生活状况的 “伟大社会 ”计划。这些新计划包括为老年人和低收入公民分别提供的医疗保险计划—— 联邦医疗保险（Medicare ）和医疗补助（Medicaid） ，以及为低收入家庭提供食品援助的食品券计划。这些举措极大地扩展了联邦政府在提供社会保障方面的作用 。 州和地方政府也参与了这些计划的实施，并开始依赖联邦政府以项目拨款形式提供的财政支持。

As the federal government’s role in policy creation expanded, so did its level of spending. Spending by the federal government began to surpass that of state and local governments shortly after 1940 (Figure 14.4). It spiked temporarily during the Great Depression and again during World War II, resuming a slow climb with the implementation of Johnson’s Great Society programs noted above.

[.my2]
随着联邦政府在政策制定中的作用不断扩大，其支出水平也随之增长。1940 年后不久，联邦政府的支出就开始超过州和地方政府的支出（ 图 14.4 ）。在大萧条时期和二战期间，联邦政府的支出曾出现短暂的激增，之后随着上文提到的约翰逊“伟大社会”计划的实施，支出又恢复了缓慢增长的趋势。

A graph titled “Federal Spending vs. State and Local Spending”. The x-axis of the graph is labeled “Year” and reads from left to right “1930”, “1940”, “1950”, “1960”, “1970”, “1980”, “1990”, “2000”, “2010”, and “2020”. The y-axis is labeled “Expenditure as percent of GDP” and reads from bottom to top “5%”, “10%”, “15%”, “20%”, “25%”, “30%”, “35%”, “40%”, and “45%”. A line labeled “Federal” starts around 4% in 1930, rises to around 10% in 1940, rises sharply to around 40% around 1945, drops sharply to around 15% in 1960, increases to around 20% in 1970, increases to around 23% in 1980, decreases to around 19% in 200, increases to around 25% in 2010, and ends at 32.5% in 2020. A line labeled “State” starts around 10% in 1930, rises to around 11% then drops back to around 10% in 1940, drops to around 5% then rises to around 8% in 1950, rises to around 10% in 1960, rises to around 13% in 1970, rises to around 14% then drops back around 13% in 1980, maintains around 13% in 1990, rises to around 14% in 2000, rises to around 16% in 2010, and ends at 14.3% in 2020. At the bottom of the graph a source is cited: “U.S. Bureau of Economic Analysis. NIPA table 1.1.5: “Gross Domestic Product.” April 29, 2021. NIPA Table 3.2: “Federal Government Current Receipts and Expenditures.” April 29, 2021. NIPA Table 3.3: “State and Local Government Current Receipts and Expenditures.” April 29, 2021.

[.my2]
Figure 14.4 After spiking during World War II, spending by the federal government has consistently exceeded that of state and local governments. Since 2000, the gap between federal and state spending has widened considerably. An upswing is evident with the Great Recession (2008–10) and federal spending escalated as COVID-19 became the dominant policy issue in 2020.

[.my2]
图 14.4 二战期间联邦政府支出激增后，其支出一直高于州和地方政府。自 2000 年以来，联邦和州政府支出之间的差距显著扩大。在 2008-2010 年的经济大衰退期间，这一差距明显上升；而随着新冠疫情在 2020 年成为主要政策议题，联邦支出进一步攀升。
Growing financial resources gave the federal government increased power over subnational governments. This increased power was because it could use categorical grants to dictate the terms and conditions state governments had to meet to qualify for financial assistance in a specific policy area. Over time, the federal government even began to require state and local governments to comply with legislative and executive authorizations when funding was not attached. These requests from the federal government are referred to as unfunded mandates and are a source of dissatisfaction to political actors at the state and local level. To provide more transparency to state and local governments and reduce the federal government’s use of mandates, the Unfunded Mandates Reform Act was passed in 1995. This act requires the Congressional Budget Office to provide information about the cost of any proposed government mandate that exceeds a specified threshold before the bill can be considered in Congress.8
不断增长的财政资源赋予联邦政府对地方政府更大的权力。这种权力的增强源于联邦政府可以利用专项拨款来规定州政府在特定政策领域获得财政援助的条件。随着时间的推移，联邦政府甚至开始要求州和地方政府在没有资金支持的情况下遵守立法和行政授权。联邦政府的这些要求被称为“无资金授权”，引起了州和地方政治人士的不满。为了提高州和地方政府的透明度，并减少联邦政府使用授权，1995 年通过了《 无资金授权改革法案》 。 该法案要求国会预算办公室在国会审议任何拟议的政府授权法案之前，提供超过特定门槛的成本信息。

Link to Learning  学习链接
Explore the latest news on federal mandates at the Congressional Budget Office and the Catalog of Cost Shifts to States at the National Conference of State Legislatures website.

[.my2]
请访问国会预算办公室网站，了解联邦指令的最新消息；访问全国州议会联合会网站， 了解各州成本转移目录 。

Despite the national government’s power to pass and fund policy that affects lower-level governments, states still have gained considerable headway since the late twentieth century. For instance, with the passage of the Personal Responsibility and Work Opportunity Reconciliation Act in 1996, known as the welfare reform bill, states were given great discretion over the provision of welfare. The federal government reduced its level of monetary support for the program and, in exchange, the states gained more authority over its implementation. States were able to set more restrictive work requirements, to place caps on the number of family members who could receive aid, and to limit the length of time someone could qualify for government assistance.9
尽管联邦政府有权制定和资助影响下级政府的政策，但自 20 世纪末以来，各州仍然取得了相当大的进展。例如，1996 年通过的《 个人责任和工作机会协调法案》（Personal Responsibility and Work Opportunity Reconciliation Act ，简称 PRRC，即福利改革法案）赋予了各州在福利提供方面的更大自主权。联邦政府减少了对该计划的资金支持，作为交换，各州获得了更大的实施权 。 各州可以设定更严格的工作要求，限制可获得援助的家庭成员人数，并限制个人领取政府援助的时间。

Since then, states have been granted the flexibility to set policy across a number of controversial policy areas. For instance, a wide array of states require parental consent for abortions performed on minors, ban abortions completely or after a certain number of weeks of pregnancy, or require patients to undergo an ultrasound before the procedure. As another example, currently, almost half the states allow for the use of medical marijuana and sixteen more states have fully legalized it, despite the fact that this practice stands in contradiction to federal law that prohibits the use and distribution of marijuana.

[.my2]
此后，各州被赋予了在诸多争议性政策领域制定政策的灵活性。例如，许多州要求对未成年人进行堕胎手术必须获得父母同意，完全禁止堕胎或在怀孕一定周数后禁止堕胎，或要求患者在手术前接受超声检查。再举一例，目前近一半的州允许使用医用大麻，另有16个州已将其完全合法化，尽管这种做法与禁止使用和分销大麻的联邦法律相抵触。

Link to Learning  学习链接
For more on these two controversial policy areas, explore ”An Overview of State Abortion Laws” and ”State Medical Marijuana Laws.”
有关这两个有争议的政策领域的更多信息，请参阅 “各州堕胎法概述” 和 “各州医用大麻法”。

Today, it is not uncommon to see a patchwork of legal decisions granting states more discretion in some policy areas, such as marijuana use, while providing the federal government more authority in others, such as same-sex marriage. Decisions about which level controls policy can reflect the attitudes of government officials and the public, political ideology and the strategic advantage of setting policy on a state-by-state basis, and the necessity of setting uniform policy in the face of an economic downturn or unanticipated national security threat. What has not changed over time is the central role of the U.S. Supreme Court’s views in determining how power should be distributed in a federalist system.

[.my2]
如今，法律判决呈现出一种碎片化的局面：某些政策领域（例如大麻使用）赋予各州更大的自主权，而另一些领域（例如同性婚姻）则赋予联邦政府更大的权力。政策由哪个层级控制的决定，反映了政府官员和公众的态度、政治意识形态、逐州制定政策的战略优势，以及在经济衰退或面临突发国家安全威胁时制定统一政策的必要性。然而，始终未变的是美国最高法院的观点在决定联邦制体系中权力分配方面的核心作用。

POWER AT THE SUBSTATE LEVEL
次级权力
The U.S. Constitution is silent on the dispersion of power between states and localities within each state. The fact that states are mentioned specifically and local jurisdictions are not has traditionally meant that power independent of the federal government resides first with the state. Through their own constitutions and statutes, states decide what to require of local jurisdictions and what to delegate. This structure represents the legal principle of Dillon’s Rule, named for Iowa Supreme Court justice John F. Dillon. Dillon argued that state actions trump those of the local government and have supremacy.10 In this view, cities and towns exist at the pleasure of the state, which means the state can step in and dissolve them or even take them over. Indeed, most states have supremacy clauses over local governments in their constitutions.

[.my2]
美国宪法并未明确规定各州及其下辖地方政府之间的权力分配。宪法中明确提及各州而未提及地方管辖权，这传统上意味着，独立于联邦政府的权力首先归于各州。各州通过自身的宪法和法规，决定对地方管辖权的要求以及下放的权力。这种结构体现了狄龙规则的法律原则，该规则以爱荷华州最高法院大法官约翰·F· 狄龙的名字命名。狄龙认为，州政府的行为凌驾于地方政府之上，并拥有最高权力。 10 在这种观点下，城镇的存在取决于州政府的意愿，这意味着州政府可以介入并解散它们，甚至接管它们。事实上，大多数州的宪法中都包含凌驾于地方政府之上的条款。

However, for practical purposes, state and local governments must work together to ensure that citizens receive adequate services. Given the necessity of cooperation, many states have granted local governments some degree of autonomy and given them discretion to make policy or tax decisions.11 This added independence is called home rule, and the transfer of power is typically spelled out within a charter. Charters are similar to state constitutions: they provide a framework and a detailed accounting of local government responsibilities and areas of authority. Potential conflicts can come up over home rule. For example, in 2015, the State of Texas overruled a fracking ban imposed by the City of Denton.12
然而，出于实际需要，州政府和地方政府必须携手合作，以确保公民获得充足的服务。鉴于合作的必要性，许多州赋予地方政府一定程度的自治权，并允许其自行制定政策或税收决策。 11 这种额外的独立性被称为地方自治 ，权力的转移通常会在宪章中明确规定。宪章类似于州宪法：它们提供了一个框架，并详细规定了地方政府的职责和权限范围。地方自治可能会引发潜在的冲突。例如，2015 年，德克萨斯州推翻了丹顿市实施的水力压裂禁令。 12

Like state governments, local governments prioritize spending on building and maintaining the transportation infrastructure, supporting educational institutions, promoting community protection, and funding healthcare.13 As shown in Figure 14.5, local governments, just like state governments, receive a sizeable chunk of their revenue from grants and transfers from other levels of the government. The next biggest source of revenue for local governments is property tax collections.

[.my2]
与州政府一样，地方政府优先考虑将资金用于建设和维护交通基础设施、支持教育机构、促进社区安全和资助医疗保健。 13 如图 14.5 所示，地方政府与州政府一样，其收入的很大一部分来自其他级别政府的拨款和转移支付。地方政府的第二大收入来源是房产税。

A pie chart titled “Local Revenue Funding Source, 2017”. There are six regions on the pie chart. Starting at the top and moving clockwise, the regions are labeled “Charges and miscellaneous 23%”, “Sales tax 7%”, “Other tax 2%”, “Income tax 2%”, “Intergovernmental transfer 36%”, and “Property tax 30%”. At the bottom of the chart a source is cited: “Tax Policy Center/Brookings Institution. “Local Government Revenue, Percentage Distribution, 1977 to 2017.” May 27, 2020.

[.my2]
Figure 14.5 The largest source of revenue for local governments is grants and transfers from other levels of the government. The next biggest source is property tax collections.

[.my2]
图 14.5 地方政府最大的收入来源是来自其他级别政府的拨款和转移支付。其次是房产税收入。
Property taxes can be assessed on homes, land, and businesses. The local government’s reliance on property tax revenue can be problematic for a number of reasons. First, unlike sales tax, the collection of which is spaced out in small increments across multiple transactions, property tax is collected in one or two lump sums and is therefore highly visible and unpopular.14 In fact, in response to tax rate increases, many states have placed legal or constitutional limits on regional governments’ ability to raise property taxes. The trend began in California with the 1978 passage of Proposition 13. This citizen-driven initiative capped the real estate tax at 1 percent of the cash value of property and stopped the practice of reassessing properties for tax purposes whenever a home in the neighborhood was sold.15 After its passage, a number of other states followed suit, making it more difficult for states to reap the rewards of sharp increases in the market value of property. And, of course, not reassessing properties for tax purposes unless a home is sold leads to massive disparities in amounts paid by neighbors living in similar houses in the same neighborhood.16
房产税可以针对房屋、土地和企业征收。地方政府对房产税收入的依赖可能存在诸多问题。首先，与销售税不同，销售税的征收是分多次交易小额收取的，而房产税则是一次性或分两次征收，因此非常显眼，也更容易引起民众不满。 14 事实上，为了应对税率上涨，许多州都对地方政府提高房产税的能力设置了法律或宪法限制。这一趋势始于加利福尼亚州，1978 年通过了第 13 号提案 。这项由公民推动的提案将房产税上限设定为房产现金价值的 1%，并停止了在社区内房屋出售时重新评估房产价值以征税的做法。 15 该提案通过后，许多其他州也纷纷效仿，使得各州更难从房产市场价值的急剧上涨中获利。当然，除非房屋出售，否则不重新评估房产价值以用于征税，这会导致同一社区内居住条件相似的房屋，其邻居缴纳的税款金额存在巨大差异 。16

Another drawback to local governments’ reliance on property tax is that property values vary with the economic health of a given area, the quality of school districts, and the overall desirability of a state, municipality, or county. Significant parcels of land in many cities are also tax-exempt, including property occupied by colleges, churches, and other nonprofit organizations. Boston is a good example as almost 50 percent of the assessed value of property is tax-exempt.17 College towns face the same challenge.

[.my2]
地方政府依赖房产税的另一个弊端是，房产价值会随着特定地区的经济状况、学区质量以及州、市或县的整体吸引力而波动。许多城市的大片土地也免税，包括大学、教堂和其他非营利组织占用的房产。波士顿就是一个很好的例子，该市近 50%的房产评估价值都免税。17 个大学城也面临着同样的挑战。

When the mortgage crisis began in 2007, property values decreased in many areas of the country, and many homeowners defaulted on their mortgages because their homes were now worth less than they had borrowed to buy them. With the decline in property values, local governments faced a loss in tax revenue at the same time states were cutting back on aid; tax collections were also down because of economic conditions and the inability to derive income tax from internet sales. A number of municipalities filed for bankruptcy in the face of fiscal distress during the economic recession. Perhaps the best known municipality was Detroit, Michigan, which filed for Chapter 9 bankruptcy in 2013 (Figure 14.6).

[.my2]
2007 年次贷危机爆发时，全国许多地区的房产价值下跌，许多房主因房屋价值低于购房贷款额而拖欠抵押贷款。随着房产价值的下降，地方政府面临税收收入减少，与此同时，各州也在削减援助；此外，经济形势不佳以及无法从互联网销售中征收所得税也导致税收收入下降。在经济衰退期间，许多市政当局因财政困境而申请破产。其中最著名的或许是密歇根州底特律市，该市于 2013 年申请了破产保护（ 图 14.6 ）。

An image of the inside of a dilapidated building.

[.my2]
Figure 14.6 This photo shows the wreckage of the ballroom at the Lee Plaza Hotel in Detroit, Michigan. Once a landmark, this building is an example of the city’s crumbling infrastructure. (credit: modification of work by Mike Boening)
图 14.6 这张照片展示了密歇根州底特律李广场酒店宴会厅的残骸。这座建筑曾是地标性建筑，如今却成了这座城市基础设施破败的缩影。（图片来源：Mike Boening 作品的修改版）
Detroit filed for bankruptcy due to massive debt obligations and demands for repayment that it could not meet due to a perfect storm of economic and demographic factors. The city owed money to investors who had loaned it money, and it had liabilities resulting from its failure to fulfill its pension and healthcare obligations to city workers. The bankruptcy allowed the city time to develop an exit strategy and negotiate with creditors and union representatives in an effort to restructure its debt load.18 Indeed, Detroit recently emerged from bankruptcy and has started to rebuild economically.

[.my2]
由于经济和人口因素的多重影响，底特律背负了巨额债务，无力偿还，最终申请破产。该市不仅拖欠投资者的贷款，还因未能履行对市政员工的养老金和医疗保健义务而背负了债务。破产程序使该市得以制定退出策略，并与债权人和工会代表进行谈判，以期重组债务。事实上， 底特律近期已摆脱破产困境，并开始重建经济。

Detroit’s fiscal condition only highlights the unique challenges municipalities face. Local governments have to provide many of the same services as state and national governments, but they are often constrained by the boundaries the state prescribes. They may not have the authority to raise revenue above a certain threshold, and they do not have the ability to pass expenses on to another level of government because they lack sovereignty.

[.my2]
底特律的财政状况凸显了市政当局面临的独特挑战。地方政府必须提供与州政府和联邦政府类似的诸多服务，但它们往往受到州政府划定的界限的限制。它们可能没有权力增加超过一定限额的收入，而且由于缺乏主权，它们也无法将支出转嫁给其他级别的政府。

'''