
= 002-5 Constitutional Change 宪法变更
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




A country spends, raises, and regulates money in accordance with its values. In all, the federal government’s budget for 2020 was $6.55 trillion, and for 2024 was $6.8 trillion. This chapter has provided a brief overview of some of the budget’s key areas of expenditure, and thus some insight into modern American values. But these values are only part of the budgeting story. Policymakers make considerable effort to ensure that long-term priorities are protected from the heat of the election cycle and short-term changes in public opinion. The decision to put some policymaking functions out of the reach of Congress also reflects economic philosophies about the best ways to grow, stimulate, and maintain the economy. The role of politics in drafting the annual budget is indeed large, but we should not underestimate the challenges elected officials face as a result of decisions made in the past.

[.my2]
一个国家根据其价值观来支出、筹集和管理资金。2020年联邦政府预算总额为6.55万亿美元，2024年为6.8万亿美元。本章简要概述了预算的一些关键支出领域，从而对现代美国的价值观有所了解。但这些价值观只是预算故事的一部分。政策制定者竭尽全力确保长期优先事项不受选举周期和短期民意变化的影响。将某些政策制定职能置于国会之外的决定也反映了关于如何最好地发展、刺激和维持经济的经济理念。政治在年度预算编制中的作用固然巨大，但我们不应低估民选官员因过去的决策而面临的挑战。

APPROACHES TO THE ECONOMY
经济方法
Until the 1930s, most policy advocates argued that the best way for the government to interact with the economy was through a hands-off approach formally known as laissez-faire economics. These policymakers believed the key to economic growth and development was the government’s allowing private markets to operate efficiently. Proponents of this school of thought believed private investors were better equipped than governments to figure out which sectors of the economy were most likely to grow and which new products were most likely to be successful. They also tended to oppose government efforts to establish quality controls or health and safety standards, believing consumers themselves would punish bad behavior by not trading with poor corporate citizens. Finally, laissez-faire proponents felt that keeping government out of the business of business would create an automatic cycle of economic growth and contraction. Contraction phases in which there is no economic growth for two consecutive quarters, called recessions, would bring business failures and higher unemployment. But this condition, they believed, would correct itself on its own if the government simply allowed the system to operate.

[.my2]
直到 20 世纪 30 年代，大多数政策倡导者都认为，政府干预经济的最佳方式是采取一种不干预的态度，即所谓的自由放任经济学。这些政策制定者相信，经济增长和发展的关键在于政府允许私人市场高效运作。这一学派的支持者认为，私人投资者比政府更有能力判断哪些经济部门最有可能增长，哪些新产品最有可能成功。他们也倾向于反对政府制定质量控制或健康安全标准，认为消费者会通过不与不合格的企业进行交易来惩罚不良行为。最后，自由放任的支持者认为，政府不干预商业活动会形成经济增长和衰退的自动循环。连续两个季度经济增长停滞的衰退阶段，会导致企业倒闭和失业率上升。但他们认为，如果政府允许系统自行运行，这种情况就会自行纠正。

The Great Depression challenged the laissez-faire view, however. When President Franklin Roosevelt came to office in 1933, the United States had already been in the depths of the Great Depression for several years, since the stock market crash of 1929. Roosevelt sought to implement a new approach to economic regulation known as Keynesianism. Named for its developer, the economist John Maynard Keynes, Keynesian economics argues that it is possible for a recession to become so deep, and last for so long, that the typical models of economic collapse and recovery may not work. Keynes suggested that economic growth was closely tied to the ability of individuals to consume goods. It didn’t matter how or where investors wanted to invest their money if no one could afford to buy the products they wanted to make. And in periods of extremely high unemployment, wages for newly hired labor would be so low that new workers would be unable to afford the products they produced.

[.my2]
然而，大萧条挑战了自由放任的观点。1933 年富兰克林·罗斯福总统就职时，美国已经深陷大萧条的泥潭数年之久，其根源可追溯到 1929 年的股市崩盘。罗斯福试图推行一种被称为凯恩斯主义的新经济调控方法。 凯恩斯主义经济学以其创始人、经济学家约翰·梅纳德· 凯恩斯的名字命名，它认为经济衰退可能会变得非常严重，持续时间也可能非常长，以至于传统的经济崩溃和复苏模式可能不再适用。凯恩斯指出，经济增长与个人消费能力密切相关。如果人们买不起投资者想要生产的产品，那么无论投资者想把钱投资到哪里都无关紧要。在失业率极高的时期，新雇佣的工人的工资会非常低，以至于他们根本买不起自己生产的产品。

Keynesianism counters this problem by increasing government spending in ways that improve consumption. Some of the proposals Keynes suggested were payments or pension for the unemployed and retired, as well as tax incentives to encourage consumption in the middle class. His reasoning was that these individuals would be most likely to spend the money they received by purchasing more goods, which in turn would encourage production and investment. Keynes argued that the wealthy class of producers and employers had sufficient capital to meet the increased demand of consumers that government incentives would stimulate. Once consumption had increased and capital was flowing again, the government would reduce or eliminate its economic stimulus, and any money it had borrowed to create it could be repaid from higher tax revenues.

[.my2]
凯恩斯主义通过增加政府支出以刺激消费来应对这一问题。凯恩斯提出的一些方案包括向失业者和退休人员发放补贴或养老金，以及通过税收优惠来鼓励中产阶级的消费。他的理由是，这些人最有可能将获得的资金用于购买更多商品，从而刺激生产和投资。凯恩斯认为，富裕的生产者和雇主阶层拥有足够的资本来满足政府激励措施所刺激的消费者需求增长。一旦消费增加，资本再次流动，政府就会减少或取消经济刺激措施，而用于实施这些措施的借款可以通过更高的税收收入来偿还。

Keynesianism dominated U.S. fiscal or spending policy from the 1930s to the 1970s. By the 1970s, however, high inflation began to slow economic growth. There were a number of reasons, including higher oil prices and the costs of fighting the Vietnam War. However, some economists, such as Arthur Laffer, began to argue that the social welfare and high tax policies created in the name of Keynesianism were overstimulating the economy, creating a situation in which demand for products had outstripped investors’ willingness to increase production.26 They called for an approach known as supply-side economics, which argues that economic growth is largely a function of the productive capacity of a country. Supply-siders have argued that increased regulation and higher taxes reduce the incentive to invest new money into the economy, to the point where little growth can occur. They have advocated reducing taxes and regulations to spur economic growth.

[.my2]
从 20 世纪 30 年代到 70 年代，凯恩斯主义主导了美国的财政或支出政策。然而，到了 70 年代，高通胀开始拖累经济增长。造成这种情况的原因有很多，包括油价上涨和越南战争的成本。 但是 ，一些经济学家，例如阿瑟·拉弗，开始认为，以凯恩斯主义名义制定的社会福利和高税收政策过度刺激了经济，导致产品需求超过了投资者增加生产的意愿。他们呼吁采用一种被称为供给侧经济学的方法，该方法认为经济增长在很大程度上取决于一个国家的生产能力。供给侧经济学家认为，加强监管和提高税收会降低人们向经济投入新资金的积极性，以至于经济增长几乎停滞。他们主张减少税收和监管以刺激经济增长。

MANDATORY SPENDING VS. DISCRETIONARY SPENDING
强制性支出与可自由支配支出
The desire of Keynesians to create a minimal level of aggregate demand, coupled with a Depression-era preference to promote social welfare policy, led the president and Congress to develop a federal budget with spending divided into two broad categories: mandatory and discretionary (see Figure 16.15). Of these, mandatory spending is the larger, consisting of about $4.1 trillion of the 2024 budget, or roughly 60 percent of all federal expenditures.27
凯恩斯主义者希望创造最低限度的总需求，加上大萧条时期推行社会福利政策的倾向，促使总统和国会制定了一项联邦预算，将支出分为两大类：强制性支出和可自由支配支出（见图 16.15 ）。其中， 强制性支出规模更大，约占 2024 年预算的 4.1 万亿美元，约占联邦总支出的 60%。 27

The overwhelming portion of mandatory spending is earmarked for entitlement programs guaranteed to those who meet certain qualifications, usually based on age, income, or disability. These programs, discussed above, include Medicare and Medicaid, Social Security, and major income security programs such as unemployment insurance and SNAP. The costs of programs tied to age are relatively easy to estimate and grow largely as a function of the aging of the population. Income and disability payments are a bit more difficult to estimate. They tend to go down during periods of economic recovery and rise when the economy begins to slow down, in precisely the way Keynes suggested. A comparatively small piece of the mandatory spending pie, about 18 percent, is devoted to benefits designated for former federal employees, including military retirement and many Veterans Administration programs.

[.my2]
绝大部分强制性支出都用于保障符合特定条件（通常基于年龄、收入或残疾）人群的福利项目。上文已讨论过这些项目，包括医疗保险（Medicare）、医疗补助（Medicaid）、社会保障以及主要的收入保障项目，例如失业保险和补充营养援助计划（SNAP）。与年龄相关的项目成本相对容易估算，并且主要随着人口老龄化而增长。收入和残疾补助金的估算则较为困难。正如凯恩斯所预言的那样，这些补助金在经济复苏时期往往会下降，而在经济开始放缓时则会上升。强制性支出中只有相对较小的一部分（约占 18%）用于为前联邦雇员提供的福利，包括军人退休金和许多退伍军人事务部的项目。

A graph titled “U.S. Federal Spending in the Fiscal Year 2024.” Three pie charts are presented. The first chart is broken down into these categories: Social Security $1.5 trillion or 37%; Medicare & Medicaid $1.48 trillion or 36%; Income security: $370 billion or 9%; Other  $752 billion or 18%. The second chart i broken down into these categories: Defense $850 billion or 47%; and Non Defense 960 billion or 53 percent. The third chart covers all other spending, and is made up of net interest at $881 billion.

[.my2]
Figure 16.15 This chart of U.S. federal spending for 2024 shows the proportions of mandatory and discretionary spending, about 60 percent and 26 percent, respectively. Source: Congressional Budget Office. The Federal Budget in Fiscal Year 2024: An Infographic. March 20, 2025. Accessed May 26, 2025. https://www.cbo.gov/publication/61181
图 16.15 这张图表显示了 2024 年美国联邦支出中强制性支出和可自由支配支出的比例，分别约为 60% 和 26%。资料来源：国会预算办公室。《2024 财年联邦预算：信息图》。2025 年 3 月 20 日发布。访问日期：2025 年 5 月 26 日。https://www.cbo.gov/publication/61181
Congress is ultimately responsible for setting the formulas for mandatory payouts, but as we saw in the earlier discussion regarding Social Security, major reforms to entitlement formulas are difficult to enact. As a result, the size and growth of mandatory spending in future budgets are largely a function of previous legislation that set the formulas up in the first place. So long as supporters of particular programs can block changes to the formulas, funding will continue almost on autopilot. Keynesians support this mandatory spending, along with other elements of social welfare policy, because they help maintain a minimal level of consumption that should, in theory, prevent recessions from turning into depressions, which are more severe downturns.

[.my2]
国会最终负责制定强制性支出的计算公式，但正如我们在之前关于社会保障的讨论中所看到的，对福利公式进行重大改革难以实施。因此，未来预算中强制性支出的规模和增长在很大程度上取决于最初制定这些公式的立法。只要特定项目的支持者能够阻止对公式的修改，资金就会几乎自动地继续拨付。凯恩斯主义者支持这种强制性支出以及其他社会福利政策，因为它们有助于维持最低消费水平，理论上可以防止经济衰退演变为更严重的经济萧条。

Portions of the budget not devoted to mandatory spending are categorized as discretionary spending because Congress must pass legislation to authorize money to be spent each year. About 53 percent of the approximately $1.8 trillion set aside for discretionary spending each year pays for most of the operations of government, including employee salaries and the maintenance of federal buildings. It also covers science and technology spending, foreign affairs initiatives, education spending, federally provided transportation costs, and many of the redistributive benefits most people in the United States have come to take for granted.28 The other forty-seven percent of discretionary spending—and the second-largest component of the total budget—is devoted to the military. (Only Social Security is larger.) Defense spending is used to maintain the U.S. military presence at home and abroad, procure and develop new weapons, and cover the cost of any wars or other military engagements in which the United States is currently engaged (Figure 16.16).

[.my2]
预算中除强制性支出外的部分被归类为可自由支配支出 ，因为国会必须通过立法授权每年支出资金。每年拨出的约 1.8 万亿美元可自由支配支出中，约有 53%用于支付政府的大部分运作，包括雇员薪资和联邦建筑的维护。它还涵盖科学技术支出、外交事务、教育支出、联邦政府提供的交通运输费用，以及美国大多数民众习以为常的许多再分配福利。 28 其余 47%的可自由支配支出——也是总预算中第二大组成部分——用于军事开支（仅次于社会保障支出）。国防开支用于维持美国在国内外的军事存在，采购和研发新型武器，以及支付美国目前参与的任何战争或其他军事行动的费用（ 图 16.16 ）。

A series of six images that show combat troops in various locations Afghanistan.

[.my2]
Figure 16.16 The war in Afghanistan, which had been ongoing since 2001, cost the United States billions of dollars in discretionary military spending authorized by Congress every year. In 2021, then-President Joe Biden announced plans to withdraw U.S. troops from Afghanistan by September 11, 2021, the twentieth anniversary of the 9/11 attacks.

[.my2]
图 16.16 自 2001 年以来持续不断的阿富汗战争，每年耗费美国数十亿美元国会授权的可自由支配军费。2021 年，时任总统乔·拜登宣布计划在 2021 年 9 月 11 日（9·11 恐怖袭击事件二十周年纪念日）之前从阿富汗撤军。
In theory, the amount of revenue raised by the national government should be equal to these expenses, but with the exception of a brief period from 1998 to 2000, that has not been the case. The economic recovery from the 2007–2009 recession, and budget control efforts implemented in the early 2010s, managed to cut the annual deficit—the amount by which expenditures are greater than revenues—by more than half by 2015. However, the amount of money the U.S. government needed to borrow to pay its bills in 2016 was still in excess of $400 billion29. This was in addition to the country’s almost $19 trillion of total debt—the amount of money the government owes its creditors—at the end of 2015, according to the Department of the Treasury.30 The total debt as of March 2021 is $28 trillion.

[.my2]
理论上，国家政府的收入应该等于支出，但除了 1998 年至 2000 年的短暂时期外，实际情况并非如此。2007 年至 2009 年经济衰退后的复苏，以及 2010 年代初实施的预算控制措施，使得年度赤字 （即支出超过收入的部分）在 2015 年减少了一半以上。然而，2016 年美国政府为支付账单所需的借款仍然超过 4000 亿美元 29 。根据美国财政部的数据，截至 2015 年底，美国政府的总债务接近 19 万亿美元 30 。截至 2021 年 3 月，美国总债务已达 28 万亿美元。

Balancing the budget has been a major goal of both the Republican and Democratic parties for the past several decades, although the parties tend to disagree on the best way to accomplish the task. One frequently offered solution, particularly among supply-side advocates, is to simply cut spending. This has proven to be much easier said than done. If Congress were to try to balance the budget only through discretionary spending, it would need to cut about one-third of spending on programs like defense, higher education, agriculture, police enforcement, transportation, and general government operations. Given the number and popularity of many of these programs, it is difficult to imagine this would be possible. To use spending cuts alone as a way to control the deficit, Congress will almost certainly be required to cut or control the costs of mandatory spending programs like Social Security and Medicare—a radically unpopular step.

[.my2]
在过去几十年里，平衡预算一直是共和党和民主党的共同目标，尽管两党在实现这一目标的最佳途径上存在分歧。一种经常被提出的解决方案，尤其是在供给侧经济学的支持者中，就是简单地削减开支。然而，事实证明，这说起来容易做起来难。如果国会试图仅通过削减可自由支配的支出来平衡预算，就需要削减国防、高等教育、农业、警务执法、交通运输和一般政府运作等项目约三分之一的开支。考虑到这些项目的数量和受欢迎程度，很难想象这能够实现。如果仅仅依靠削减开支来控制赤字，国会几乎肯定需要削减或控制社会保障和医疗保险等强制性支出项目的成本——而这无疑是一个极不受欢迎的举措。

TAX POLICY  税收政策
The other option available for balancing the budget is to increase revenue. All governments must raise revenue in order to operate. The most common way is by applying some sort of tax on residents (or on their behaviors) in exchange for the benefits the government provides (Figure 16.17). As necessary as taxes are, however, they are not without potential downfalls. First, the more money the government collects to cover its costs, the less residents are left with to spend and invest. Second, attempts to raise revenues through taxation may alter the behavior of residents in ways that are counterproductive to the state and the broader economy. Excessively taxing necessary and desirable behaviors like consumption (with a sales tax) or investment (with a capital gains tax) will discourage citizens from engaging in them, potentially slowing economic growth. The goal of tax policy, then, is to determine the most effective way of meeting the nation’s revenue obligations without harming other public policy goals.

[.my2]
平衡预算的另一种方法是增加财政收入。所有政府都必须筹集资金才能正常运转。最常见的方法是对居民（或其行为）征收某种税款，以换取政府提供的各项福利（ 图 16.17 ）。然而，税收虽然必不可少，但也并非没有潜在的弊端。首先，政府征收的税款越多，用于支付各项开支的资金就越多，居民可用于消费和投资的资金就越少。其次，试图通过税收来增加财政收入可能会改变居民的行为，从而对国家和整体经济产生不利影响。对消费（例如征收销售税）或投资（例如征收资本利得税）等必要且有益的行为征收过高的税款，会抑制公民参与这些行为，从而可能减缓经济增长。因此， 税收政策的目标是在不损害其他公共政策目标的前提下，找到履行国家财政收入义务的最有效途径。

An image of a person’s hand, holding a pen over a form.

[.my2]
Figure 16.17 A U.S. marine fills out an income tax form. Income taxes in the United States are progressive taxes.

[.my2]
图 16.17 一名美国海军陆战队员正在填写所得税申报表。美国的所得税是累进税制。
As you would expect, Keynesians and supply-siders disagree about which forms of tax policy are best. Keynesians, with their concern about whether consumers can really stimulate demand, prefer progressive taxes systems that increase the effective tax rate as the taxpayer’s income increases. This policy leaves those most likely to spend their money with more money to spend. For example, in 2015, U.S. taxpayers who were married and filing jointly paid a 10 percent tax rate on the first $18,450 of income, but 15 percent on the next $56,450 (some income is excluded).31 The rate continued to rise, to up to 39.6 percent on any taxable income over $464,850. Following the passage of the Tax Cuts and Jobs Act of 2017, these tax brackets were shifted. While the lowest bracket remained at a rate of 10 percent, the highest tax rate was reduced from 39.6 to 37 percent. These brackets are somewhat distorted by the range of tax credits, deductions, and incentives the government offers, but the net effect is that the top income earners pay a greater portion of the overall income tax burden than do those at the lowest tax brackets. According to the Pew Research Center, based on tax returns in 2014, 2.7 percent of filers made more than $250,000. Those 2.7 percent of filers paid 52 percent of the income tax paid.32
正如预期的那样，凯恩斯主义者和供给学派在最佳税收政策形式上存在分歧。凯恩斯主义者担心消费者是否真的能够刺激需求，因此他们倾向于累进税制 ， 即随着纳税人收入的增加而提高实际税率。这种政策使得那些最有可能消费的人拥有更多可支配收入。例如，2015 年，美国已婚联合报税的纳税人，其收入的前 18,450 美元适用 10%的税率，而接下来的 56,450 美元适用 15%的税率（部分收入免税）。 31 税率继续上升，超过 464,850 美元的应税收入适用 39.6%的税率。2017 年《减税与就业法案》通过后，这些税率档次进行了调整。最低税率档次仍为 10%，而最高税率档次则从 39.6%降至 37%。政府提供的各种税收抵免、扣除和激励措施在一定程度上扭曲了这些税级划分，但最终结果是，高收入者承担的所得税负担占总所得税负担的比例高于低收入者。根据皮尤研究中心基于 2014 年纳税申报表的数据，2.7%的纳税人收入超过 25 万美元。这 2.7%的纳税人缴纳了 52%的所得税。 32

Supply-siders, on the other hand, prefer regressive tax systems, which lower the overall rate as individuals make more money. This does not automatically mean the wealthy pay less than the poor, simply that the percentage of their income they pay in taxes will be lower. Consider, for example, the use of excise taxes on specific goods or services as a source of revenue.33 Sometimes called “sin taxes” because they tend to be applied to goods like alcohol, tobacco, and gasoline, excise taxes have a regressive quality, since the amount of the good purchased by the consumer, and thus the tax paid, does not increase at the same rate as income. A person who makes $250,000 per year is likely to purchase more gasoline than a person who makes $50,000 per year (Figure 16.18). But the higher earner is not likely to purchase five times more gasoline, which means the proportion of income paid out in gasoline taxes is less than the proportion for a lower-earning individual.

[.my2]
另一方面，供给学派倾向于累退税制，即随着个人收入的增加，总体税率会降低。这并不意味着富人缴纳的税款一定少于穷人，而仅仅意味着富人缴纳的税款占其收入的比例会更低。例如，可以考虑对特定商品或服务征收消费税作为财政收入来源。消费税有时被称为“罪恶税”，因为它们通常针对酒精、烟草和汽油等商品征收。消费税具有累退性，因为消费者购买的商品数量（以及缴纳的税款）的增长速度并不与收入的增长速度相同。年收入 25 万美元的人购买的汽油量可能比年收入 5 万美元的人多（ 图 16.18 ）。但高收入者不太可能购买五倍于低收入者的汽油量，这意味着高收入者缴纳的汽油税占其收入的比例低于低收入者。

An image of a gas pump that reads “$12.00 Sale, 3.752 Gallons”.

[.my2]
Figure 16.18 A gas station shows fuel prices over $3.00 a gallon in 2005, shortly after Hurricane Katrina disrupted gas production in the Gulf of Mexico. Taxes on gasoline that are based on the quantity purchased are regressive taxes.

[.my2]
图 16.18 显示，2005 年卡特里娜飓风扰乱墨西哥湾天然气生产后不久，一家加油站的汽油价格超过每加仑 3 美元。按购买量征收的汽油税属于累退税。
Another example of a regressive tax paid by most U.S. workers is the payroll tax that funds Social Security. While workers contribute 7.65 percent of their income to pay for Social Security and their employers pay a matching amount, in 2015, the payroll tax was applied to only the first $118,500 of income. Individuals who earned more than that, or who made money from other sources like investments, saw their overall tax rate fall as their income increased.

[.my2]
美国大多数劳动者缴纳的累退税的另一个例子是用于社会保障的工资税。虽然劳动者需缴纳收入的7.65%用于社会保障，雇主也需缴纳相同比例的金额，但在2015年，工资税仅适用于收入的前118,500美元。收入超过这个数额或有其他收入来源（例如投资）的个人，其整体税率会随着收入的增加而降低。

In 2020, the United States raised about $3.4 trillion in revenue. Income taxes ($1.61 trillion), payroll taxes on Social Security and Medicare ($1.31 trillion), and excise taxes ($87 billion) make up three of the largest sources of revenue for the federal government. When combined with corporate income taxes ($212 billion), these four tax streams make up about 95 percent of total government revenue. The balance of revenue is split nearly evenly between revenues from the Federal Reserve and a mix of revenues from import tariffs, estate and gift taxes, and various fees or fines paid to the government (Figure 16.19). The Tax Cuts and Jobs Act, which was passed in December 2017 by the Republican-controlled Congress and significantly reduced the income tax rate paid by corporations, has led to a widening budget deficit. November 2018 featured the largest single-month deficit in the history of the country, with $411 billion in spending and only $206 billion in receipts, and the annual budget shortfall is approaching $1 trillion.34
2020 年，美国财政收入约为 3.4 万亿美元。个人所得税（1.61 万亿美元）、社会保障和医疗保险工资税（1.31 万亿美元）以及消费税（870 亿美元）是联邦政府三大主要收入来源。加上企业所得税（2120 亿美元），这四项税收约占政府总收入的 95%。剩余收入几乎平均分配在美联储收入和进口关税、遗产税、赠与税以及各种政府收费或罚款等收入之间（ 图 16.19 ）。2017 年 12 月，由共和党控制的国会通过了《减税与就业法案》，该法案大幅降低了企业所得税税率，导致预算赤字不断扩大。 2018 年 11 月，美国出现了历史上最大的单月财政赤字，支出高达 4110 亿美元，而收入仅为 2060 亿美元，年度预算缺口已接近 1 万亿美元。 34

A chart titled “Funding for the U.S. Government as % of Total Revenue, 2020”. From left to right, “Other, 5.2%”, “Corporate income taxes, 10.8%”, “Payroll taxes, 34.7%”, and “Individual income taxes, 49.0%”.

[.my2]
Figure 16.19 The taxes tied to individuals, not businesses, overwhelmingly fund the government. Source: Congressional Budget Office. The Federal Budget in Fiscal Year 2024: An Infographic. March 20, 2025. Accessed May 26, 2025. https://www.cbo.gov/publication/61181
图 16.19 政府资金主要来源于个人而非企业缴纳的税款。资料来源：国会预算办公室。《2024 财年联邦预算：信息图》。2025 年 3 月 20 日发布。访问日期：2025 年 5 月 26 日。https://www.cbo.gov/publication/61181
THE FEDERAL RESERVE BOARD AND INTEREST RATES
美联储与利率
Financial panics arise when too many people, worried about the solvency of their investments, try to withdraw their money at the same time. Such panics plagued U.S. banks until 1913 (Figure 16.20), when Congress enacted the Federal Reserve Act. The act established the Federal Reserve System, also known as the Fed, as the central bank of the United States. The Fed’s three original goals to promote were maximum employment, stable prices, and moderate long-term interest rates.35 All of these goals bring stability. The Fed’s role is now broader and includes influencing monetary policy (the means by which the nation controls the size and growth of the money supply), supervising and regulating banks, and providing them with financial services like loans.

[.my2]
当太多人担心投资的偿付能力，试图同时提取资金时，就会出现金融恐慌。这种恐慌一直困扰着美国银行业，直到 1913 年（ 图 16.20 ），国会颁布了《 联邦储备法》 。该法案设立了联邦储备系统，也称美联储，作为美国的中央银行。美联储最初的三大目标是促进充分就业、物价稳定和维持适度的长期利率。 35 所有这些目标都有助于经济稳定。如今，美联储的职能更加广泛，包括影响货币政策（国家控制货币供应量规模和增长的手段）、监管银行以及向银行提供贷款等金融服务。

An image of a large crowd of people filling Wall Street.

[.my2]
Figure 16.20 Investors crowd Wall Street during the Bankers Panic of 1907.

[.my2]
图 16.20 1907 年银行家恐慌期间，投资者涌入华尔街。
The Federal Reserve System is overseen by a board of governors, known as the Federal Reserve Board. The president of the United States appoints the seven governors, each of whom serves a fourteen-year term (the terms are staggered). A chair and vice chair lead the board for terms of four years each. The most important work of the board is participating in the Federal Open Market Committee to set monetary policy, like interest rate levels and macroeconomic policy. The board also oversees a network of twelve regional Federal Reserve Banks, each of which serves as a “banker’s bank” for the country’s financial institutions.

[.my2]
美国联邦储备系统由一个理事会监管，该理事会被称为联邦储备委员会。美国总统任命七位理事，每位理事任期十四年（任期交错）。理事会由一位主席和一位副主席领导，任期均为四年。理事会最重要的工作是参与联邦公开市场委员会，制定货币政策，例如利率水平和宏观经济政策。理事会还监管由十二家地区联邦储备银行组成的网络，每家联邦储备银行都作为美国金融机构的“银行家银行”。

Insider Perspective  内部视角
The Role of the Federal Reserve Chair
美联储主席的角色
If you have read or watched the news for the past several years, perhaps you have heard the names Janet Yellen, Ben Bernanke, or Alan Greenspan. Bernanke, Greenspan, and Yellen (Figure 16.21) are all recent past chairs of the board of governors of the Federal Reserve System; Jerome Powell is the current chair. The role of the Fed chair is one of the most important in the country. By raising or lowering banks’ interest rates, the chair has the ability reduce inflation or stimulate growth. The Fed’s dual mandate is to keep inflation low (under 2 percent) and unemployment low (below 5 percent), but efforts to meet these goals can often lead to contradictory monetary policies.

[.my2]
如果您过去几年关注新闻，或许听说过珍妮特·耶伦 、本 ·伯南克或艾伦 ·格林斯潘的名字。伯南克、格林斯潘和耶伦（ 图 16.21 ）都曾担任过美联储理事会主席；现任主席是杰罗姆·鲍威尔。美联储主席是美国最重要的职位之一。通过提高或降低银行利率，主席可以降低通货膨胀或刺激经济增长。美联储的双重使命是保持低通胀（低于 2%）和低失业率（低于 5%），但为实现这些目标所做的努力往往会导致相互矛盾的货币政策。

Image A is of Alan Greenspan. Image B is of Janet Yellen.

[.my2]
Figure   数字 16.21 Economist Alan Greenspan (a) was chair of the board of governors of the Federal Reserve System from 1987 to 2006, the second-longest tenure of any chair. Janet Yellen (b) succeeded Ben Bernanke as chair in 2014, after serving as vice chair for four years. Prior to serving on the Federal Reserve Board, Yellen was president and CEO of the Federal Reserve Bank of San Francisco. She was succeeded by Jerome Powell in February 2018 and has been serving as secretary of the Treasury since January 2021.

[.my2]
经济学家艾伦·格林斯潘（a）于 1987 年至 2006 年担任美国联邦储备系统理事会主席，任期位列历任主席第二位。珍妮特·耶伦（b）于 2014 年接替本·伯南克出任主席，此前她曾担任四年副主席。在加入美联储理事会之前，耶伦曾任旧金山联邦储备银行行长兼首席执行官。她于 2018 年 2 月卸任，由杰罗姆·鲍威尔接任，并自 2021 年 1 月起担任美国财政部长。
The Fed, and by extension its chair, have a tremendous responsibility. Many of the economic events of the past five decades, both good and bad, are the results of Fed policies. In the 1970s, double-digit inflation brought the economy almost to a halt, but when Paul Volcker became chair in 1979, he raised interest rates and jump-started the economy. After the stock market crash of 1987, then-chair Alan Greenspan declared, “The Federal Reserve, consistent with its responsibilities as the nation’s central bank, affirmed today its readiness to…support the economic and financial system.”36 His lowering of interest rates led to an unprecedented decade of economic growth through the 1990s. In the 2000s, consistently low interest rates and readily available credit contributed to the sub-prime mortgage boom and subsequent bust, which led to a global economic recession beginning in 2008.

[.my2]
美联储及其主席肩负着巨大的责任。过去五十年间的许多经济事件，无论好坏，都是美联储政策的结果。20 世纪 70 年代，两位数的通货膨胀几乎使经济陷入停滞，但保罗·沃尔克于 1979 年就任主席后，他提高了利率，刺激了经济增长。1987 年股市崩盘后，时任主席艾伦·格林斯潘宣布：“美联储作为国家中央银行，今天重申其随时准备……支持经济和金融体系。” 36 他降低利率的举措促成了 20 世纪 90 年代前所未有的经济增长。进入 21 世纪，持续的低利率和信贷的宽松政策助长了次贷危机及其后的崩溃，最终导致始于 2008 年的全球经济衰退。

Should the important tasks of the Fed continue to be pursued by unelected appointees like those profiled in this box, or should elected leaders be given the job? Why?
美联储的重要任务是否应该继续由像本文提到的那些未经选举产生的任命人员来承担，还是应该由民选领导人来担任？为什么？

Link to Learning  学习链接
The Federal Reserve has a number of roles and responsibilities. Watch some of the videos about the roles and responsibilities of the Federal Reserve Board to learn more.

[.my2]
美联储承担着多项职责。观看一些关于美联储理事会职责的视频， 了解更多信息。


'''