
= 017 Foreign Policy 对外政策
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义


The U.S. government interacts with a large number of international actors, from other governments to private organizations, to fight global problems like terrorism and human trafficking, and to meet many other national foreign policy goals such as encouraging trade, responding to natural disasters, and protecting the environment. As discussed earlier, the United States invests very heavily -- far more than every other nation -- in its military. The President, as the Commander-in-Chief, has significant impact on military missions. The President can manifest policy priorities related to national security, political influence, and overall attitudes toward nations or even regions through choices on how and where to deploy. An aircraft carrier, which is usually accompanied by dozens of other warships, can be an intimidating and effective reminder of the United States' capability to control the seas and skies around the globe. But the U.S. Navy frequently conducts humanitarian missions, bringing food aid, medical treatment, and other services to areas in need. (Figure 17.1).

[.my2]
美国政府与众多国际行为体互动，包括其他国家政府和私营组织，共同打击恐怖主义和人口贩运等全球性问题，并实现促进贸易、应对自然灾害和保护环境等诸多其他国家外交政策目标。如前所述，美国在军事上的投入巨大，远超其他任何国家。作为三军统帅，总统对军事行动拥有重大影响力。总统可以通过选择部署方式和地点，体现其在国家安全、政治影响力以及对各国乃至各地区的整体态度方面的政策优先事项。一艘通常由数十艘其他军舰护航的航空母舰，能够有效地震慑并提醒世人，美国拥有控制全球海空的能力。此外，美国海军也经常执行人道主义任务，向有需要的地区提供食品援助、医疗救治和其他服务（ 图 17.1 ）。

While the president is the country’s foreign policy leader, Congress also has many foreign policy responsibilities, including approving treaties and agreements, allocating funding, making war, and confirming ambassadors. The two branches of government are not always aligned, because Representatives and Senators often have local considerations to consider, such as their state's major industries, exports, geography, and political leanings. These and various other activities constitute the patchwork quilt that is U.S. foreign policy.

[.my2]
虽然总统是国家外交政策的领导人，但国会也承担着许多外交政策职责，包括批准条约和协定、分配资金、发动战争以及确认大使任命。政府的这两个部门并非总是步调一致，因为众议员和参议员往往需要考虑地方因素，例如本州的主要产业、出口、地理位置和政治倾向。这些以及其他各种活动共同构成了美国外交政策这幅错综复杂的图景。

How are foreign and domestic policymaking different, and how are they linked? What are the main foreign policy goals of the United States? How do the president and Congress interact in the foreign policy realm? In what different ways might foreign policy be pursued? This chapter will delve into these and other issues to present an overview U.S. foreign policy.

[.my2]
外交政策和内政政策的制定有何不同？二者之间又存在哪些联系？美国的主要外交政策目标是什么？总统和国会在外交政策领域如何互动？外交政策可以采取哪些不同的实施方式？本章将深入探讨这些问题，并对美国外交政策进行概述。




Figure 17.1 In this image, the U.S. Navy hospital ship Mercy sails in formation with rapid troop and equipment transport Brunswick and Canadian warship Vancouver. The United States can project power and influence far beyond its borders through a complex web of diplomatic efforts, trade and monetary policy, sanctions, foreign aid, alliances, and military strength. (credit: U.S. Navy photo by Mass Communication Specialist 2nd Class Kelsey L. Adams/Flickr. Public Domain.)

Chapter Outline

- 17.1 Defining Foreign Policy
- 17.2 Foreign Policy Instruments
- 17.3 Institutional Relations in Foreign Policy
- 17.4 Approaches to Foreign Policy

The U.S. government interacts with a large number of international actors, from other governments to private organizations, to fight global problems like terrorism and human trafficking, and to meet many other national foreign policy goals such as encouraging trade, responding to natural disasters, and protecting the environment. As discussed earlier, the United States invests very heavily -- far more than every other nation -- in its military. The President, as the Commander-in-Chief, has significant impact on military missions. The President can manifest policy priorities related to national security, political influence, and overall attitudes toward nations or even regions through choices on how and where to deploy. An aircraft carrier, which is usually accompanied by dozens of other warships, can be an intimidating and effective reminder of the United States' capability to control the seas and skies around the globe. But the U.S. Navy frequently conducts humanitarian missions, bringing food aid, medical treatment, and other services to areas in need. (Figure 17.1).

While the president is the country’s foreign policy leader, Congress also has many foreign policy responsibilities, including approving treaties and agreements, allocating funding, making war, and confirming ambassadors. The two branches of government are not always aligned, because Representatives and Senators often have local considerations to consider, such as their state's major industries, exports, geography, and political leanings. These and various other activities constitute the patchwork quilt that is U.S. foreign policy.

How are foreign and domestic policymaking different, and how are they linked? What are the main foreign policy goals of the United States? How do the president and Congress interact in the foreign policy realm? In what different ways might foreign policy be pursued? This chapter will delve into these and other issues to present an overview U.S. foreign policy.

'''