
= 102 The Constitution of the United States 美国宪法
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


== 释义




We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.

[.my2]
我们美利坚合众国人民，为了建立更完善的联邦，树立正义，保障国内安宁，提供共同防御，增进公共福利，并使我们自己和我们的后代永享自由的幸福，特为美利坚合众国制定并颁布本宪法。

Article. I.  第一条

Section. 1.  第一部分

All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives.

[.my2]
本法所授予的一切立法权，均属于由参议院和众议院组成的美国国会。

Section. 2.  第二部分

The House of Representatives shall be composed of Members chosen every second Year by the People of the several States, and the Electors in each State shall have the Qualifications requisite for Electors of the most numerous Branch of the State Legislature.

[.my2]
众议院由各州人民每两年选举产生的议员组成，各州的选举人应具备该州立法机关人数最多的一院选举人所需的资格。

No Person shall be a Representative who shall not have attained to the Age of twenty five Years, and been seven Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State in which he shall be chosen.

[.my2]
凡未满二十五岁，未成为美国公民七年，且当选时未成为其当选所在州的居民者，不得担任众议员。

Representatives and direct Taxes shall be apportioned among the several States which may be included within this Union, according to their respective Numbers, which shall be determined by adding to the whole Number of free Persons, including those bound to Service for a Term of Years, and excluding Indians not taxed, three fifths of all other Persons. The actual Enumeration shall be made within three Years after the first Meeting of the Congress of the United States, and within every subsequent Term of ten Years, in such Manner as they shall by Law direct. The Number of Representatives shall not exceed one for every thirty Thousand, but each State shall have at Least one Representative; and until such enumeration shall be made, the State of New Hampshire shall be entitled to chuse three, Massachusetts eight, Rhode-Island and Providence Plantations one, Connecticut five, New-York six, New Jersey four, Pennsylvania eight, Delaware one, Maryland six, Virginia ten, North Carolina five, South Carolina five, and Georgia three.

[.my2]
各州代表名额和直接税应按各州人口比例分配，各州人口数的计算方法为：将所有自由人（包括服役一定年限的自由人，但不包括未被征税的印第安人）的总数加上其他所有人口的五分之三。实际人口普查应在美利坚合众国国会首次会议后的三年内进行，此后每十年进行一次，具体方式由国会依法规定。各州代表人数不得超过每三万人一名，但每个州至少应有一名代表；在人口普查完成之前，新罕布什尔州有权选出三名代表，马萨诸塞州八名，罗德岛州和普罗维登斯种植园各一名，康涅狄格州五名，纽约州六名，新泽西州四名，宾夕法尼亚州八名，特拉华州一名，马里兰州六名，弗吉尼亚州十名，北卡罗来纳州五名，南卡罗来纳州五名，佐治亚州三名。

When vacancies happen in the Representation from any State, the Executive Authority thereof shall issue Writs of Election to fill such Vacancies.

[.my2]
当任何邦的代表出现空缺时，该邦的行政机关应当发布选举令，以填补这些空缺。

The House of Representatives shall chuse their Speaker and other Officers; and shall have the sole Power of Impeachment.

[.my2]
众议院选举议长及其他官员；并拥有唯一的弹劾权。

Section. 3.  第三节

The Senate of the United States shall be composed of two Senators from each State, chosen by the Legislature thereof, for six Years; and each Senator shall have one Vote.

[.my2]
美国参议院由各州选出的两名参议员组成，任期六年；每位参议员有一票表决权。

Immediately after they shall be assembled in Consequence of the first Election, they shall be divided as equally as may be into three Classes. The Seats of the Senators of the first Class shall be vacated at the Expiration of the second Year, of the second Class at the Expiration of the fourth Year, and of the third Class at the Expiration of the sixth Year, so that one third may be chosen every second Year; and if Vacancies happen by Resignation, or otherwise, during the Recess of the Legislature of any State, the Executive thereof may make temporary Appointments until the next Meeting of the Legislature, which shall then fill such Vacancies.

[.my2]
首次选举结束后，议员们应立即集会，并尽可能平均地分为三类。第一类参议员的席位在第二年届满时空缺，第二类参议员的席位在第四年届满时空缺，第三类参议员的席位在第六年届满时空缺，以便每两年选出三分之一的议员；如果任何州的立法机关休会期间出现因辞职或其他原因造成的空缺，该州的行政长官可以进行临时任命，直至立法机关下次开会填补这些空缺。

No Person shall be a Senator who shall not have attained to the Age of thirty Years, and been nine Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State for which he shall be chosen.

[.my2]
凡未满三十岁，未成为美国公民九年，且当选时未成为其所代表州的居民者，不得担任参议员。

The Vice President of the United States shall be President of the Senate, but shall have no Vote, unless they be equally divided.

[.my2]
美国副总统将担任参议院议长，但除非票数相等，否则无投票权。

The Senate shall chuse their other Officers, and also a President pro tempore, in the Absence of the Vice President, or when he shall exercise the Office of President of the United States.

[.my2]
参议院应选举其其他官员，并在副总统缺席或行使美国总统职权时，选举临时议长。

The Senate shall have the sole Power to try all Impeachments. When sitting for that Purpose, they shall be on Oath or Affirmation. When the President of the United States is tried, the Chief Justice shall preside: And no Person shall be convicted without the Concurrence of two thirds of the Members present.

[.my2]
参议院拥有审理所有弹劾案的专属权力。参议院在为此目的召开会议时，应当宣誓或作证。当美国总统受审时，首席大法官应当主持审判；未经出席议员三分之二的同意，任何人不得被定罪。

Judgment in Cases of Impeachment shall not extend further than to removal from Office, and disqualification to hold and enjoy any Office of honor, Trust or Profit under the United States: but the Party convicted shall nevertheless be liable and subject to Indictment, Trial, Judgment and Punishment, according to Law.

[.my2]
弹劾案的判决不应超出免职和取消担任和享有美国任何荣誉、信任或有酬职务的资格；但被定罪的一方仍应依法承担责任，并接受起诉、审判、判决和处罚。

Section. 4.  第四节

The Times, Places and Manner of holding Elections for Senators and Representatives, shall be prescribed in each State by the Legislature thereof; but the Congress may at any time by Law make or alter such Regulations, except as to the Places of chusing Senators.

[.my2]
参议员和众议员选举的时间、地点和方式，应由各州立法机关规定；但国会可随时通过法律制定或修改此类规定，但参议员选举地点除外。

The Congress shall assemble at least once in every Year, and such Meeting shall be on the first Monday in December, unless they shall by Law appoint a different Day.

[.my2]
大会每年至少召开一次，会议应在十二月的第一个星期一举行，除非大会依法另行指定日期。

Section. 5.  第五节

Each House shall be the Judge of the Elections, Returns and Qualifications of its own Members, and a Majority of each shall constitute a Quorum to do Business; but a smaller Number may adjourn from day to day, and may be authorized to compel the Attendance of absent Members, in such Manner, and under such Penalties as each House may provide.

[.my2]
各院应自行裁定其议员的选举、选举结果和资格，各院过半数议员构成法定人数，方可进行议事；但人数不足者可逐日休会，并可授权以各院规定的方式和处罚，强制缺席议员出席。

Each House may determine the Rules of its Proceedings, punish its Members for disorderly Behaviour, and, with the Concurrence of two thirds, expel a Member.

[.my2]
各院均可制定议事规则，惩处议员的不守规矩行为，并经三分之二同意，开除议员。

Each House shall keep a Journal of its Proceedings, and from time to time publish the same, excepting such Parts as may in their Judgment require Secrecy; and the Yeas and Nays of the Members of either House on any question shall, at the Desire of one fifth of those Present, be entered on the Journal.

[.my2]
各院应保存议事录，并应不时公布，但其认为需要保密的部分除外；任何一院议员对任何问题的赞成票和反对票，经出席议员五分之一的要求，应记入议事录。

Neither House, during the Session of Congress, shall, without the Consent of the other, adjourn for more than three days, nor to any other Place than that in which the two Houses shall be sitting.

[.my2]
在国会会期期间，未经另一院同意，任何一院不得休会超过三天，也不得迁往两院开会地点以外的任何其他地点。

Section. 6.  第六节

The Senators and Representatives shall receive a Compensation for their Services, to be ascertained by Law, and paid out of the Treasury of the United States. They shall in all Cases, except Treason, Felony and Breach of the Peace, be privileged from Arrest during their Attendance at the Session of their respective Houses, and in going to and returning from the same; and for any Speech or Debate in either House, they shall not be questioned in any other Place.

[.my2]
参议员和众议员应因其服务获得报酬，具体数额由法律确定，并由美国国库支付。除叛国罪、重罪和扰乱治安罪外，他们在各自议院开会期间以及往返途中均享有免遭逮捕的特权；他们在两院的任何发言或辩论，均不得在其他任何地方受到质询。

No Senator or Representative shall, during the Time for which he was elected, be appointed to any civil Office under the Authority of the United States, which shall have been created, or the Emoluments whereof shall have been encreased during such time; and no Person holding any Office under the United States, shall be a Member of either House during his Continuance in Office.

[.my2]
任何参议员或众议员在其当选任期内，不得被任命担任美国政府下属的任何文职职务，该职务须在其任期内设立或增加；任何担任美国政府职务的人，在其任期内不得同时担任众议院或参议院议员。

Section. 7.  第七节

All Bills for raising Revenue shall originate in the House of Representatives; but the Senate may propose or concur with Amendments as on other Bills.

[.my2]
所有增加财政收入的法案均应由众议院提出；但参议院可以像对其他法案一样提出或同意修正案。

Every Bill which shall have passed the House of Representatives and the Senate, shall, before it become a Law, be presented to the President of the United States; If he approve he shall sign it, but if not he shall return it, with his Objections to that House in which it shall have originated, who shall enter the Objections at large on their Journal, and proceed to reconsider it. If after such Reconsideration two thirds of that House shall agree to pass the Bill, it shall be sent, together with the Objections, to the other House, by which it shall likewise be reconsidered, and if approved by two thirds of that House, it shall become a Law. But in all such Cases the Votes of both Houses shall be determined by yeas and Nays, and the Names of the Persons voting for and against the Bill shall be entered on the Journal of each House respectively. If any Bill shall not be returned by the President within ten Days (Sundays excepted) after it shall have been presented to him, the Same shall be a Law, in like Manner as if he had signed it, unless the Congress by their Adjournment prevent its Return, in which Case it shall not be a Law.

[.my2]
凡经众议院和参议院通过的法案，在成为法律之前，均应呈递美国总统；如总统批准，则应签署；如总统不批准，则应将法案连同其反对意见退回提出该法案的议院，该议院应将反对意见完整地记录在议事录中，并重新审议该法案。如经重新审议后，该议院三分之二的议员同意通过该法案，则应将法案连同反对意见一并送交另一议院，由该议院同样进行重新审议；如该议院三分之二的议员批准，则该法案即成为法律。但所有此类情况下，两院的表决均应以赞成票和反对票的方式进行，赞成票和反对票的投票人姓名应分别记录在两院的议事录中。如果任何法案在提交总统后十日内（星期日除外）未被总统退回，则该法案即成为法律，如同总统已签署该法案一样，除非国会通过休会阻止该法案退回，在这种情况下，该法案不成为法律。

Every Order, Resolution, or Vote to which the Concurrence of the Senate and House of Representatives may be necessary (except on a question of Adjournment) shall be presented to the President of the United States; and before the Same shall take Effect, shall be approved by him, or being disapproved by him, shall be repassed by two thirds of the Senate and House of Representatives, according to the Rules and Limitations prescribed in the Case of a Bill.

[.my2]
凡须经参议院和众议院同意的命令、决议或表决（除休会问题外），均须呈报美国总统；且须经总统批准方可生效；若遭总统否决，则须经参议院和众议院三分之二的议员重新通过，并须遵守法案所规定的规则和限制。

Section. 8.  第 8 节

The Congress shall have Power To lay and collect Taxes, Duties, Imposts and Excises, to pay the Debts and provide for the common Defence and general Welfare of the United States; but all Duties, Imposts and Excises shall be uniform throughout the United States;
国会有权征收税款、关税、进口税和消费税，以偿还债务，并为美国的共同防御和公共福利提供资金；但所有关税、进口税和消费税在全美范围内应统一；

To borrow Money on the credit of the United States;
以美国信用为担保借款；

To regulate Commerce with foreign Nations, and among the several States, and with the Indian Tribes;
规范与外国、各州之间以及与印第安部落之间的商业往来；

To establish an uniform Rule of Naturalization, and uniform Laws on the subject of Bankruptcies throughout the United States;
为在美国各地建立统一的入籍规则和统一的破产法；

To coin Money, regulate the Value thereof, and of foreign Coin, and fix the Standard of Weights and Measures;
铸造货币，规范其价值和外国货币的价值，并制定度量衡标准；

To provide for the Punishment of counterfeiting the Securities and current Coin of the United States;
规定对伪造美国证券和流通硬币的行为进行处罚；

To establish Post Offices and post Roads;
设立邮局和邮路；

To promote the Progress of Science and useful Arts, by securing for limited Times to Authors and Inventors the exclusive Right to their respective Writings and Discoveries;
为了促进科学和实用技艺的进步，在一定期限内保障作者和发明家对其各自作品和发现的专有权；

To constitute Tribunals inferior to the supreme Court;
设立最高法院下级法庭；

To define and punish Piracies and Felonies committed on the high Seas, and Offences against the Law of Nations;
界定和惩处在公海上犯下的海盗行为和重罪，以及违反国际法的行为；

To declare War, grant Letters of Marque and Reprisal, and make Rules concerning Captures on Land and Water;
宣战、颁发私掠许可证和报复许可证，以及制定有关陆地和水上俘获的规则；

To raise and support Armies, but no Appropriation of Money to that Use shall be for a longer Term than two Years;
征召和供养军队，但为此目的拨付的款项期限不得超过两年；

To provide and maintain a Navy;
提供和维持一支海军；

To make Rules for the Government and Regulation of the land and naval Forces;
制定陆海军管理条例；

To provide for calling forth the Militia to execute the Laws of the Union, suppress Insurrections and repel Invasions;
规定召集民兵执行联邦法律、镇压叛乱和抵御入侵；

To provide for organizing, arming, and disciplining, the Militia, and for governing such Part of them as may be employed in the Service of the United States, reserving to the States respectively, the Appointment of the Officers, and the Authority of training the Militia according to the discipline prescribed by Congress;
为组织、武装和训练民兵，并管理其中一部分在美国服役的民兵，保留各州任命军官和按照国会规定的纪律训练民兵的权力；

To exercise exclusive Legislation in all Cases whatsoever, over such District (not exceeding ten Miles square) as may, by Cession of particular States, and the Acceptance of Congress, become the Seat of the Government of the United States, and to exercise like Authority over all Places purchased by the Consent of the Legislature of the State in which the Same shall be, for the Erection of Forts, Magazines, Arsenals, dock-Yards, and other needful Buildings;—And
对于经特定州割让并经国会接受而成为美国政府所在地（面积不超过十平方英里）的地区，在任何情况下均享有专属立法权；对于经所在州立法机关同意购买的用于建造堡垒、弹药库、兵工厂、船坞和其他必要建筑物的所有地点，亦享有同样的权力；——以及

To make all Laws which shall be necessary and proper for carrying into Execution the foregoing Powers, and all other Powers vested by this Constitution in the Government of the United States, or in any Department or Officer thereof.

[.my2]
制定为执行上述权力以及本宪法赋予美国政府或其任何部门或官员的所有其他权力所必需和适当的一切法律。

Section. 9.  第9节

The Migration or Importation of such Persons as any of the States now existing shall think proper to admit, shall not be prohibited by the Congress prior to the Year one thousand eight hundred and eight, but a Tax or duty may be imposed on such Importation, not exceeding ten dollars for each Person.

[.my2]
在1808年之前，国会不得禁止任何州认为合适的移民或进口人员，但可以对此类进口征收税款或关税，每人不超过十美元。

The Privilege of the Writ of Habeas Corpus shall not be suspended, unless when in Cases of Rebellion or Invasion the public Safety may require it.

[.my2]
人身保护令特权不得中止，除非在叛乱或入侵的情况下，公共安全需要中止该特权。

No Bill of Attainder or ex post facto Law shall be passed.

[.my2]
不得通过任何剥夺公民权利法案或追溯既往的法律。

No Capitation, or other direct, Tax shall be laid, unless in Proportion to the Census or enumeration herein before directed to be taken.

[.my2]
除非按照先前指示进行的普查或统计结果，否则不得征收人头税或其他直接税。

No Tax or Duty shall be laid on Articles exported from any State.

[.my2]
任何国家出口的物品均不得征收任何税费或关税。

No Preference shall be given by any Regulation of Commerce or Revenue to the Ports of one State over those of another: nor shall Vessels bound to, or from, one State, be obliged to enter, clear, or pay Duties in another.

[.my2]
商业或税收法规不得给予一国港口相对于另一国港口的任何优惠待遇；往返于一国的船舶也不得被强制要求在另一国入境、清关或缴纳关税。

No Money shall be drawn from the Treasury, but in Consequence of Appropriations made by Law; and a regular Statement and Account of the Receipts and Expenditures of all public Money shall be published from time to time.

[.my2]
除依法拨款外，不得从国库提取任何款项；所有公共资金的收支情况应定期公布。

No Title of Nobility shall be granted by the United States: And no Person holding any Office of Profit or Trust under them, shall, without the Consent of the Congress, accept of any present, Emolument, Office, or Title, of any kind whatever, from any King, Prince, or foreign State.

[.my2]
美国不得授予任何贵族头衔；任何在美国担任有酬或受托职务的人，未经国会同意，不得接受任何国王、王子或外国的任何礼物、报酬、官职或头衔。

Section. 10.  第 10 节

No State shall enter into any Treaty, Alliance, or Confederation; grant Letters of Marque and Reprisal; coin Money; emit Bills of Credit; make any Thing but gold and silver Coin a Tender in Payment of Debts; pass any Bill of Attainder, ex post facto Law, or Law impairing the Obligation of Contracts, or grant any Title of Nobility.

[.my2]
任何国家不得缔结任何条约、联盟或邦联；不得颁发私掠许可证和报复许可证；不得铸造货币；不得发行信用票据；不得以金银币以外的任何物品作为偿还债务的法定货币；不得通过任何剥夺公民权法案、追溯既往的法律或损害合同义务的法律，也不得授予任何贵族头衔。

No State shall, without the Consent of the Congress, lay any Imposts or Duties on Imports or Exports, except what may be absolutely necessary for executing it’s inspection Laws: and the net Produce of all Duties and Imposts, laid by any State on Imports or Exports, shall be for the Use of the Treasury of the United States; and all such Laws shall be subject to the Revision and Controul of the Congress.

[.my2]
未经国会同意，任何州不得对进出口商品征收任何关税或税款，但为执行其检验法律所绝对必要的除外；任何州对进出口商品征收的所有关税和税款的净收益，均应归美国国库所有；所有此类法律均应受国会的修订和控制。

No State shall, without the Consent of Congress, lay any Duty of Tonnage, keep Troops, or Ships of War in time of Peace, enter into any Agreement or Compact with another State, or with a foreign Power, or engage in War, unless actually invaded, or in such imminent Danger as will not admit of delay.

[.my2]
未经国会同意，任何州不得征收吨位税，不得在和平时期保留军队或军舰，不得与另一州或外国缔结任何协议或条约，也不得发动战争，除非实际遭到入侵，或面临迫在眉睫的危险，不容拖延。

Article. II.  第二条

Section. 1.  第一部分

The executive Power shall be vested in a President of the United States of America. He shall hold his Office during the Term of four Years, and, together with the Vice President, chosen for the same Term, be elected, as follows
行政权应归于美利坚合众国总统。总统任期四年，与任期相同的副总统一同选举产生，选举方式如下：

Each State shall appoint, in such Manner as the Legislature thereof may direct, a Number of Electors, equal to the whole Number of Senators and Representatives to which the State may be entitled in the Congress: but no Senator or Representative, or Person holding an Office of Trust or Profit under the United States, shall be appointed an Elector.

[.my2]
各州应按照其立法机关所规定的方式，任命与该州在国会中应有的参议员和众议员总数相等的选举人；但任何参议员或众议员，或在美国担任有信托或有酬职务的人，均不得被任命为选举人。

The Electors shall meet in their respective States, and vote by Ballot for two Persons, of whom one at least shall not be an Inhabitant of the same State with themselves. And they shall make a List of all the Persons voted for, and of the Number of Votes for each; which List they shall sign and certify, and transmit sealed to the Seat of the Government of the United States, directed to the President of the Senate. The President of the Senate shall, in the Presence of the Senate and House of Representatives, open all the Certificates, and the Votes shall then be counted. The Person having the greatest Number of Votes shall be the President, if such Number be a Majority of the whole Number of Electors appointed; and if there be more than one who have such Majority, and have an equal Number of Votes, then the House of Representatives shall immediately chuse by Ballot one of them for President; and if no Person have a Majority, then from the five highest on the List the said House shall in like Manner chuse the President. But in chusing the President, the Votes shall be taken by States, the Representation from each State having one Vote; A quorum for this Purpose shall consist of a Member or Members from two thirds of the States, and a Majority of all the States shall be necessary to a Choice. In every Case, after the Choice of the President, the Person having the greatest Number of Votes of the Electors shall be the Vice President. But if there should remain two or more who have equal Votes, the Senate shall chuse from them by Ballot the Vice President.

[.my2]
选举人应在其各自所在州集会，以无记名投票方式选出两名候选人，其中至少一人不得与选举人同住一个州。选举人应列出所有当选人及其得票数，并签署认证，加盖公章送交美国政府所在地，由参议院议长签发。参议院议长应在参议院和众议院议员在场的情况下，开启所有证书，并清点选票。得票最多者当选总统，前提是其得票数超过所有选举人总数的多数；如果有多名候选人得票数相同且超过多数，则众议院应立即以无记名投票方式选出其中一人担任总统；如果没有候选人得票超过多数，则众议院应从得票最高的五名候选人中，以同样的方式选出总统。但在选举总统时，应按州投票，每个州的代表拥有一票；为此目的，法定人数应为三分之二州的一名或多名议员，且须获得所有州的多数票方可当选。在任何情况下，总统选举结束后，获得选举人票最多的人当选为副总统。但如果出现两名或两名以上得票相同的候选人，则由参议院以投票方式从中选出副总统。

The Congress may determine the Time of chusing the Electors, and the Day on which they shall give their Votes; which Day shall be the same throughout the United States.

[.my2]
国会可以决定选举人的时间以及选举人投票的日期；该日期在美国各地应为同一日期。

No Person except a natural born Citizen, or a Citizen of the United States, at the time of the Adoption of this Constitution, shall be eligible to the Office of President; neither shall any Person be eligible to that Office who shall not have attained to the Age of thirty five Years, and been fourteen Years a Resident within the United States.

[.my2]
除出生即为美国公民或在宪法通过时为美国公民的人外，任何人不得担任总统职务；任何未满三十五岁且未在美国居住满十四年的人也不得担任总统职务。

In Case of the Removal of the President from Office, or of his Death, Resignation, or Inability to discharge the Powers and Duties of the said Office, the Same shall devolve on the Vice President, and the Congress may by Law provide for the Case of Removal, Death, Resignation or Inability, both of the President and Vice President, declaring what Officer shall then act as President, and such Officer shall act accordingly, until the Disability be removed, or a President shall be elected.

[.my2]
如总统被免职、死亡、辞职或丧失履行总统职务的权力和职责的能力，则总统职务应由副总统行使。国会可以通过法律规定，在总统和副总统均被免职、死亡、辞职或丧失履行总统职务能力的情况下，由哪位官员代理总统职务，该官员应履行总统职务，直至总统丧失履行总统职务的能力得到恢复，或选出新的总统为止。

The President shall, at stated Times, receive for his Services, a Compensation, which shall neither be encreased nor diminished during the Period for which he shall have been elected, and he shall not receive within that Period any other Emolument from the United States, or any of them.

[.my2]
总统应按规定时间领取酬金，该酬金在其当选任期内不得增加或减少，且在其任期内不得从美国或其任何成员处领取任何其他报酬。

Before he enter on the Execution of his Office, he shall take the following Oath or Affirmation:—"I do solemnly swear (or affirm) that I will faithfully execute the Office of President of the United States, and will to the best of my Ability, preserve, protect and defend the Constitution of the United States."
在就职之前，他应宣誓或声明如下：“我郑重宣誓（或声明），我将忠实履行美国总统的职责，并将尽我所能，维护、保护和捍卫美国宪法。”

Section. 2.  第二部分

The President shall be Commander in Chief of the Army and Navy of the United States, and of the Militia of the several States, when called into the actual Service of the United States; he may require the Opinion, in writing, of the principal Officer in each of the executive Departments, upon any Subject relating to the Duties of their respective Offices, and he shall have Power to grant Reprieves and Pardons for Offences against the United States, except in Cases of Impeachment.

[.my2]
总统应为美国陆军和海军的总司令，以及各州民兵在被征召入伍时的总司令；他可以要求各行政部门的主要官员就与其各自职务相关的任何事项提供书面意见；他有权对违反美国的罪行给予缓刑和赦免，但弹劾案除外。

He shall have Power, by and with the Advice and Consent of the Senate, to make Treaties, provided two thirds of the Senators present concur; and he shall nominate, and by and with the Advice and Consent of the Senate, shall appoint Ambassadors, other public Ministers and Consuls, Judges of the supreme Court, and all other Officers of the United States, whose Appointments are not herein otherwise provided for, and which shall be established by Law: but the Congress may by Law vest the Appointment of such inferior Officers, as they think proper, in the President alone, in the Courts of Law, or in the Heads of Departments.

[.my2]
总统有权经参议院的建议和同意缔结条约，但须有出席参议员三分之二的同意；总统应提名，并经参议院的建议和同意任命大使、其他公使和领事、最高法院法官以及所有其他美国官员，但本法未另行规定任命的官员，须依法设立：但国会可依法将此类下级官员的任命权授予总统、法院或各部门负责人。

The President shall have Power to fill up all Vacancies that may happen during the Recess of the Senate, by granting Commissions which shall expire at the End of their next Session.

[.my2]
总统有权在参议院休会期间填补所有空缺，通过授予委任状的方式，委任人选的任期将于参议院下一届会议结束时到期。

Section. 3.  第三节

He shall from time to time give to the Congress Information of the State of the Union, and recommend to their Consideration such Measures as he shall judge necessary and expedient; he may, on extraordinary Occasions, convene both Houses, or either of them, and in Case of Disagreement between them, with Respect to the Time of Adjournment, he may adjourn them to such Time as he shall think proper; he shall receive Ambassadors and other public Ministers; he shall take Care that the Laws be faithfully executed, and shall Commission all the Officers of the United States.

[.my2]
他应不时向国会报告联邦状况，并建议国会考虑他认为必要和适宜的措施；在特殊情况下，他可以召集两院或其中一院，如果两院之间对休会时间有分歧，他可以将其休会至他认为适当的时间；他应接见大使和其他公使；他应确保法律得到忠实执行，并任命美国所有官员。

Section. 4.  第四节

The President, Vice President and all civil Officers of the United States, shall be removed from Office on Impeachment for, and Conviction of, Treason, Bribery, or other high Crimes and Misdemeanors.

[.my2]
美国总统、副总统和所有文职官员，如因叛国罪、受贿罪或其他重罪和轻罪而被弹劾并定罪，应被免职。

Article III.  第三条

Section. 1.  第一部分

The judicial Power of the United States, shall be vested in one supreme Court, and in such inferior Courts as the Congress may from time to time ordain and establish. The Judges, both of the supreme and inferior Courts, shall hold their Offices during good Behaviour, and shall, at stated Times, receive for their Services, a Compensation, which shall not be diminished during their Continuance in Office.

[.my2]
合众国的司法权，应归属于最高法院，以及国会不时设立的下级法院。最高法院和下级法院的法官，只要行为良好，即可继续任职，并应按规定时间领取报酬，该报酬在其任职期间不得减少。

Section. 2.  第二部分

The judicial Power shall extend to all Cases, in Law and Equity, arising under this Constitution, the Laws of the United States, and Treaties made, or which shall be made, under their Authority;—to all Cases affecting Ambassadors, other public Ministers and Consuls;—to all Cases of admiralty and maritime Jurisdiction;—to Controversies to which the United States shall be a Party;—to Controversies between two or more States;—between a State and Citizens of another State,—between Citizens of different States,—between Citizens of the same State claiming Lands under Grants of different States, and between a State, or the Citizens thereof, and foreign States, Citizens or Subjects.

[.my2]
司法权应延伸至所有根据本宪法、美国法律以及根据其授权缔结或将要缔结的条约而产生的法律和衡平法案件；——所有涉及大使、其他公使和领事的案件；——所有海事和海商管辖案件；——美国作为一方当事人的争议；——两个或两个以上州之间的争议；——一个州与另一个州的公民之间的争议；——不同州的公民之间的争议；——同一州的公民之间因不同州授予的土地而提出的争议；以及一个州或其公民与外国、外国公民或外国臣民之间的争议。

In all Cases affecting Ambassadors, other public Ministers and Consuls, and those in which a State shall be Party, the supreme Court shall have original Jurisdiction. In all the other Cases before mentioned, the supreme Court shall have appellate Jurisdiction, both as to Law and Fact, with such Exceptions, and under such Regulations as the Congress shall make.

[.my2]
凡涉及大使、其他公使和领事的案件，以及以国家为一方当事人的案件，最高法院均具有初审管辖权。凡前述其他案件，最高法院均具有上诉管辖权，包括法律和事实方面的管辖权，但须遵守国会制定的例外情况和规章。

The Trial of all Crimes, except in Cases of Impeachment, shall be by Jury; and such Trial shall be held in the State where the said Crimes shall have been committed; but when not committed within any State, the Trial shall be at such Place or Places as the Congress may by Law have directed.

[.my2]
除弹劾案外，所有犯罪案件的审判均应由陪审团进行；此类审判应在犯罪发生地所在州进行；但若犯罪并非发生于任何州内，则审判应在国会依法指定的地点进行。

Section. 3.  第三节

Treason against the United States, shall consist only in levying War against them, or in adhering to their Enemies, giving them Aid and Comfort. No Person shall be convicted of Treason unless on the Testimony of two Witnesses to the same overt Act, or on Confession in open Court.

[.my2]
对美国犯叛国罪，仅指对美国发动战争，或与美国的敌人勾结，向其提供援助和支持。任何人不得被判犯有叛国罪，除非有两名证人就同一公开行为作证，或在公开法庭上认罪。

The Congress shall have Power to declare the Punishment of Treason, but no Attainder of Treason shall work Corruption of Blood, or Forfeiture except during the Life of the Person attainted.

[.my2]
国会有权宣布叛国罪的惩罚，但叛国罪的剥夺公民权不得导致血统败坏或财产没收，除非是在被剥夺公民权的人有生之年。

Article. IV.  第四条

Section. 1.  第一部分

Full Faith and Credit shall be given in each State to the public Acts, Records, and judicial Proceedings of every other State. And the Congress may by general Laws prescribe the Manner in which such Acts, Records and Proceedings shall be proved, and the Effect thereof.

[.my2]
各州应充分尊重并承认其他各州的公共法令、记录和司法程序。国会可以通过一般性法律规定此类法令、记录和程序的证明方式及其效力。

Section. 2.  第二部分

The Citizens of each State shall be entitled to all Privileges and Immunities of Citizens in the several States.

[.my2]
各州公民享有各州公民的一切特权和豁免权。

A Person charged in any State with Treason, Felony, or other Crime, who shall flee from Justice, and be found in another State, shall on Demand of the executive Authority of the State from which he fled, be delivered up, to be removed to the State having Jurisdiction of the Crime.

[.my2]
任何人在任何州被控犯有叛国罪、重罪或其他罪行，逃避司法制裁，并在另一州被发现，应根据其逃离州的行政当局的要求，将其移送至对该罪行有管辖权的州。

No Person held to Service or Labour in one State, under the Laws thereof, escaping into another, shall, in Consequence of any Law or Regulation therein, be discharged from such Service or Labour, but shall be delivered up on Claim of the Party to whom such Service or Labour may be due.

[.my2]
任何人在一国依法被强制劳动或受雇于另一国，逃往另一国，不得因该国任何法律或规章而被解除劳动或受雇，而应在有权获得该劳动或受雇于该国的一方提出请求时被交还。

Section. 3.  第三节

New States may be admitted by the Congress into this Union; but no new State shall be formed or erected within the Jurisdiction of any other State; nor any State be formed by the Junction of two or more States, or Parts of States, without the Consent of the Legislatures of the States concerned as well as of the Congress.

[.my2]
国会可以接纳新的州加入本联邦；但是，任何新的州都不得在任何其他州的管辖范围内成立或建立；任何州也不得由两个或两个以上的州或州的一部分合并而成，除非得到有关各州立法机关和国会的同意。

The Congress shall have Power to dispose of and make all needful Rules and Regulations respecting the Territory or other Property belonging to the United States; and nothing in this Constitution shall be so construed as to Prejudice any Claims of the United States, or of any particular State.

[.my2]
国会有权处置和制定有关美国领土或其他财产的一切必要规则和条例；本宪法中的任何内容均不得解释为损害美国或任何特定州的任何权利主张。

Section. 4.  第四节

The United States shall guarantee to every State in this Union a Republican Form of Government, and shall protect each of them against Invasion; and on Application of the Legislature, or of the Executive (when the Legislature cannot be convened), against domestic Violence.

[.my2]
美国应保证本联盟内各州实行共和政体，并保护各州免受入侵；经立法机关或行政机关（在立法机关无法召开会议时）申请，美国应保护各州免受国内暴力侵害。

Article. V.  第五条

The Congress, whenever two thirds of both Houses shall deem it necessary, shall propose Amendments to this Constitution, or, on the Application of the Legislatures of two thirds of the several States, shall call a Convention for proposing Amendments, which, in either Case, shall be valid to all Intents and Purposes, as Part of this Constitution, when ratified by the Legislatures of three fourths of the several States, or by Conventions in three fourths thereof, as the one or the other Mode of Ratification may be proposed by the Congress; Provided that no Amendment which may be made prior to the Year One thousand eight hundred and eight shall in any Manner affect the first and fourth Clauses in the Ninth Section of the first Article; and that no State, without its Consent, shall be deprived of its equal Suffrage in the Senate.

[.my2]
国会两院三分之二的议员认为必要时，应提出对本宪法的修正案；或者，应各州三分之二的立法机关的申请，召开制宪会议提出修正案。无论采用哪种方式，经各州四分之三的立法机关批准，或经四分之三的制宪会议批准后，该修正案即成为本宪法的一部分，具有完全的效力。具体批准方式由国会决定。但凡在1808年之前提出的任何修正案，均不得以任何方式影响第一条第九款第一项和第四项的规定；任何州未经其同意，不得被剥夺其在参议院的平等选举权。

Article. VI.  第六条

All Debts contracted and Engagements entered into, before the Adoption of this Constitution, shall be as valid against the United States under this Constitution, as under the Confederation.

[.my2]
在本宪法通过之前所订立的一切债务和订立的一切契约，在本宪法下对美利坚合众国的效力，与在邦联制度下效力相同。

This Constitution, and the Laws of the United States which shall be made in Pursuance thereof; and all Treaties made, or which shall be made, under the Authority of the United States, shall be the supreme Law of the Land; and the Judges in every State shall be bound thereby, any Thing in the Constitution or Laws of any State to the Contrary notwithstanding.

[.my2]
本宪法及依本宪法所制定的美国法律；以及依美国之名义缔结或将要缔结的一切条约，均为国家最高法律；各州法官均应受其约束，任何州宪法或法律中与之相抵触的规定均无效。

The Senators and Representatives before mentioned, and the Members of the several State Legislatures, and all executive and judicial Officers, both of the United States and of the several States, shall be bound by Oath or Affirmation, to support this Constitution; but no religious Test shall ever be required as a Qualification to any Office or public Trust under the United States.

[.my2]
上述参议员和众议员，以及各州立法机构的成员，以及美国和各州的所有行政和司法官员，均应宣誓或作证拥护本宪法；但任何宗教信仰都不得作为担任美国任何公职或公共职务的资格条件。

Article. VII.  第七条

The Ratification of the Conventions of nine States, shall be sufficient for the Establishment of this Constitution between the States so ratifying the Same.

[.my2]
九个州的制宪会议予以批准，足以使本宪法在批准该宪法的各州之间生效。

Done in Convention by the Unanimous Consent of the States present the Seventeenth Day of September in the Year of our Lord one thousand seven hundred and Eighty seven and of the Independance of the United States of America the Twelfth In witness whereof We have hereunto subscribed our Names,
经出席各州一致同意，于公元1787年9月17日，即美利坚合众国独立十二周年之际，在制宪会议上制定。为证，我们在此签名。

G. Washington  乔治·华盛顿

Presidt and deputy from Virginia
弗吉尼亚州的总统和副总统

Delaware  特拉华州

Geo: Read  地理：阅读

Gunning Bedford jun  冈宁·贝德福德二世

John Dickinson  约翰·迪金森

Richard Bassett  理查德·巴塞特

Jaco: Broom  雅各：扫帚

Maryland  马里兰州

James McHenry  詹姆斯·麦克亨利

Dan of St Thos. Jenifer
圣托马斯·詹妮弗的丹

Danl. Carroll  丹尼尔·卡罗尔

Virginia  弗吉尼亚州

John Blair  约翰·布莱尔

James Madison Jr.  小詹姆斯·麦迪逊

North Carolina  北卡罗来纳州

Wm. Blount  威廉·布朗特

Richd. Dobbs Spaight  理查德·多布斯·斯佩特

Hu Williamson  胡·威廉姆森

South Carolina  南卡罗来纳州

J. Rutledge  J. 拉特利奇

Charles Cotesworth Pinckney
查尔斯·科茨沃思·平克尼

Charles Pinckney  查尔斯·平克尼

Pierce Butler  皮尔斯·巴特勒

Georgia  乔治亚州

William Few  威廉·菲尤

Abr Baldwin  阿布尔·鲍德温

New Hampshire  新罕布什尔

John Langdon  约翰·兰登

Nicholas Gilman  尼古拉斯·吉尔曼

Massachusetts  马萨诸塞州

Nathaniel Gorham  纳撒尼尔·戈勒姆

Rufus King  鲁弗斯·金

Connecticut  康涅狄格州

Wm. Saml. Johnson  威廉·塞缪尔·约翰逊

Roger Sherman  罗杰·谢尔曼

New York  纽约

Alexander Hamilton  亚历山大·汉密尔顿

New Jersey  新泽西州

Wil: Livingston  威尔：利文斯顿

David Brearley  大卫·布雷尔利

Wm. Paterson  威廉·帕特森

Jona: Dayton  乔纳：代顿

Pensylvania  宾夕法尼亚州

B Franklin  本·富兰克林

Thomas Mifflin  托马斯·米夫林

Robt. Morris  罗伯特·莫里斯

Geo. Clymer  乔治·克莱默

Thos. FitzSimons  托马斯·菲茨西蒙斯

Jared Ingersoll  贾里德·英格索尔

James Wilson  詹姆斯·威尔逊

Gouv Morris  古夫·莫里斯

Constitutional Amendments
宪法修正案
The U.S. Bill of Rights (Amendments 1–10)
美国权利法案（修正案 1-10）

The Preamble to The Bill of Rights
《权利法案》序言

Congress of the United States begun and held at the City of New-York, on Wednesday the fourth of March, one thousand seven hundred and eighty nine.

[.my2]
美国国会于1789年3月4日星期三在纽约市召开。

The Conventions of a number of the States, having at the time of their adopting the Constitution, expressed a desire, in order to prevent misconstruction or abuse of its powers, that further declaratory and restrictive clauses should be added: And as extending the ground of public confidence in the Government, will best ensure the beneficent ends of its institution.

[.my2]
许多州的制宪会议在通过宪法时，为了防止对宪法的误解或滥用权力，表达了希望增加进一步的声明性和限制性条款的愿望：并且，扩大公众对政府的信任基础，将最有效地确保政府机构的有益目标。

Resolved by the Senate and House of Representatives of the United States of America, in Congress assembled, two thirds of both Houses concurring, that the following Articles be proposed to the Legislatures of the several States, as amendments to the Constitution of the United States, all, or any of which Articles, when ratified by three fourths of the said Legislatures, to be valid to all intents and purposes, as part of the said Constitution; viz.

[.my2]
美国参议院和众议院在国会集会上决议，经两院三分之二议员同意，将下列条款提交各州立法机关，作为对美国宪法的修正案。经上述各州立法机关四分之三批准，全部或任何条款均应在所有方面和目的上有效，成为美国宪法的一部分；即：

Articles in addition to, and Amendment of the Constitution of the United States of America, proposed by Congress, and ratified by the Legislatures of the several States, pursuant to the fifth Article of the original Constitution.

[.my2]
美国宪法的补充条款和修正案，由国会提出，并由各州立法机关根据原宪法第五条批准。

Note: The following text is a transcription of the first ten amendments to the Constitution in their original form. These amendments were ratified December 15, 1791, and form what is known as the “Bill of Rights.”
注：以下文字为宪法前十条修正案的原文。这些修正案于1791年12月15日获得批准，构成了所谓的“权利法案”。

Amendment I  修正案一

Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.

[.my2]
国会不得制定任何法律来确立国教，或禁止宗教自由；不得制定任何法律来剥夺言论自由或出版自由；不得制定任何法律来剥夺人民和平集会和向政府请愿伸冤的权利。

Amendment II  第二修正案

A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.

[.my2]
一支训练有素的民兵队伍对于一个自由州的安全是必要的，人民持有和携带武器的权利不得侵犯。

Amendment III  第三修正案

No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law.

[.my2]
和平时期，未经房主​​同意，任何士兵不得被安置在任何房屋内；战争时期，未经法律规定，任何士兵也不得被安置在任何房屋内。

Amendment IV  第四修正案

The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.

[.my2]
人民的人身、住宅、文件和财产不受无理搜查和扣押的权利不得侵犯；除有合理理由，并经宣誓或代誓词支持，且特别说明要搜查的地点和要扣押的人或物外，不得签发搜查令。

Amendment V  第五修正案

No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury, except in cases arising in the land or naval forces, or in the Militia, when in actual service in time of War or public danger; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation.

[.my2]
任何人不得因死罪或其他重罪被追究责任，除非经大陪审团提出控告或起诉，但陆军、海军或民兵在战时或公共危险时期实际服役时发生的案件除外；任何人不得因同一罪行两次遭受生命或肢体危险；任何人不得在任何刑事案件中被迫自证其罪；任何人不得未经正当法律程序而被剥夺生命、自由或财产；任何人不得未经公平补偿而被征用私人财产用于公共用途。

Amendment VI  第六修正案

In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial, by an impartial jury of the State and district wherein the crime shall have been committed, which district shall have been previously ascertained by law, and to be informed of the nature and cause of the accusation; to be confronted with the witnesses against him; to have compulsory process for obtaining witnesses in his favor, and to have the Assistance of Counsel for his defence.

[.my2]
在所有刑事诉讼中，被告人享有以下权利：由犯罪发生地所在州和地区的公正陪审团进行迅速公开的审判，该地区应事先由法律确定；被告知指控的性质和原因；与指控他的证人对质；强制证人出庭作证；以及获得律师协助进行辩护。

Amendment VII  第七修正案

In Suits at common law, where the value in controversy shall exceed twenty dollars, the right of trial by jury shall be preserved, and no fact tried by a jury, shall be otherwise re-examined in any Court of the United States, than according to the rules of the common law.

[.my2]
在普通法诉讼中，争议金额超过二十美元的，应当保留陪审团审判的权利，并且任何经陪审团审判的事实，除按照普通法规则外，不得在美国任何法院重新审查。

Amendment VIII  第八修正案

Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted.

[.my2]
不得要求过高的保释金，不得处以过高的罚款，不得施加残酷和不寻常的惩罚。

Amendment IX  第九修正案

The enumeration in the Constitution, of certain rights, shall not be construed to deny or disparage others retained by the people.

[.my2]
宪法中列举的某些权利，不得解释为否定或贬低人民保留的其他权利。

Amendment X  第十修正案

The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people.

[.my2]
宪法未授予合众国的权力，以及宪法未禁止各州行使的权力，均由各州或人民保留。

Amendment XI  第十一修正案

The Judicial power of the United States shall not be construed to extend to any suit in law or equity, commenced or prosecuted against one of the United States by Citizens of another State, or by Citizens or Subjects of any Foreign State.

[.my2]
美国的司法权不得解释为延伸至由另一州的公民或任何外国的公民或臣民对美国某一州提起或进行的普通法或衡平法诉讼。

Amendment XII  第十二修正案

The Electors shall meet in their respective states and vote by ballot for President and Vice-President, one of whom, at least, shall not be an inhabitant of the same state with themselves; they shall name in their ballots the person voted for as President, and in distinct ballots the person voted for as Vice-President, and they shall make distinct lists of all persons voted for as President, and of all persons voted for as Vice-President, and of the number of votes for each, which lists they shall sign and certify, and transmit sealed to the seat of the government of the United States, directed to the President of the Senate; — the President of the Senate shall, in the presence of the Senate and House of Representatives, open all the certificates and the votes shall then be counted; — The person having the greatest number of votes for President, shall be the President, if such number be a majority of the whole number of Electors appointed; and if no person have such majority, then from the persons having the highest numbers not exceeding three on the list of those voted for as President, the House of Representatives shall choose immediately, by ballot, the President. But in choosing the President, the votes shall be taken by states, the representation from each state having one vote; a quorum for this purpose shall consist of a member or members from two-thirds of the states, and a majority of all the states shall be necessary to a choice. [And if the House of Representatives shall not choose a President whenever the right of choice shall devolve upon them, before the fourth day of March next following, then the Vice-President shall act as President, as in case of the death or other constitutional disability of the President. —]* The person having the greatest number of votes as Vice-President, shall be the Vice-President, if such number be a majority of the whole number of Electors appointed, and if no person have a majority, then from the two highest numbers on the list, the Senate shall choose the Vice-President; a quorum for the purpose shall consist of two-thirds of the whole number of Senators, and a majority of the whole number shall be necessary to a choice. But no person constitutionally ineligible to the office of President shall be eligible to that of Vice-President of the United States.

[.my2]
选举人应在其各自所在州集会，以投票方式选举总统和副总统，其中至少一人不得与选举人居住在同一州；选举人应在选票上注明当选总统的人选，并在单独的选票上注明当选副总统的人选，并分别列出所有当选总统的人选和所有当选副总统的人选及其得票数，选举人应在名单上签名并认证，然后密封送交美国政府所在地，送交参议院议长；——参议院议长应在参议院和众议院在场的情况下，开启所有证书并清点选票；——如果总统选举中得票数最多的人选的得票数超过所有选举人总数的多数，则该人选当选总统。如果无人获得过半数选票，则众议院应从得票最高的候选人中选出得票不超过三票的候选人，立即以投票方式选出总统。但选举总统时，应按州投票，每个州的代表拥有一票；法定人数为三分之二州的一名或多名议员，且必须获得所有州的过半数支持方可当选。[如果众议院在次年3月4日之前未能选出总统，则副总统应代理总统职务，如同总统去世或因其他宪法原因丧失行为能力时一样。] —]* 获得副总统选举票最多的人，如其票数超过所有选举人票数的多数，则应当选为副总统；如无人获得多数票，则由参议院从得票最高的两人中选出副总统；参议院选举的法定人数为参议员总数的三分之二，且须获得全体参议员的多数票方可当选。但任何不符合总统资格的人，均不得担任美国副总统。

*Superseded by Section 3 of the 20th amendment.

[.my2]
* 已被第二十修正案第三条取代。

Amendment XIII  第十三号修正案

Section 1.  第一部分

Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction.

[.my2]
除因犯罪而被依法判处刑罚外，奴隶制或强迫劳动不得存在于美国境内或受其管辖的任何地方。

Section 2.  第二部分。

Congress shall have power to enforce this article by appropriate legislation.

[.my2]
国会有权通过适当的立法来执行本条款。

Amendment XIV  第十四修正案

Section 1.  第一部分

All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside. No State shall make or enforce any law which shall abridge the privileges or immunities of citizens of the United States; nor shall any State deprive any person of life, liberty, or property, without due process of law; nor deny to any person within its jurisdiction the equal protection of the laws.

[.my2]
凡在美国出生或归化，并受其管辖的人，均为美国公民，也是其居住州的公民。任何州均不得制定或执行任何剥夺美国公民特权或豁免权的法律；任何州均不得未经正当法律程序剥夺任何人的生命、自由或财产；任何州均不得拒绝在其管辖范围内的人享有法律的平等保护。

Section 2.  第二部分。

Representatives shall be apportioned among the several States according to their respective numbers, counting the whole number of persons in each State, excluding Indians not taxed. But when the right to vote at any election for the choice of electors for President and Vice-President of the United States, Representatives in Congress, the Executive and Judicial officers of a State, or the members of the Legislature thereof, is denied to any of the male inhabitants of such State, being twenty-one years of age,* and citizens of the United States, or in any way abridged, except for participation in rebellion, or other crime, the basis of representation therein shall be reduced in the proportion which the number of such male citizens shall bear to the whole number of male citizens twenty-one years of age in such State.

[.my2]
各州代表名额应按各州人口比例分配，计算时应计算各州全部人口，但不包括未纳税的印第安人。但是，如果任何年满二十一岁*且为美国公民的男性居民，在任何选举中被剥夺了选举美国总统和副总统、国会众议员、州行政和司法官员或州立法机关成员的权利，或以任何方式受到限制（参与叛乱或其他犯罪的情况除外），则该州的代表名额应按该州年满二十一岁的男性公民人数占该州所有年满二十一岁男性公民总人数的比例相应减少。

Section 3.  第三节

No person shall be a Senator or Representative in Congress, or elector of President and Vice-President, or hold any office, civil or military, under the United States, or under any State, who, having previously taken an oath, as a member of Congress, or as an officer of the United States, or as a member of any State legislature, or as an executive or judicial officer of any State, to support the Constitution of the United States, shall have engaged in insurrection or rebellion against the same, or given aid or comfort to the enemies thereof. But Congress may by a vote of two-thirds of each House, remove such disability.

[.my2]
任何人如曾宣誓拥护美国宪法，无论是作为国会议员、美国官员、州议员，还是任何州的行政或司法官员，之后又参与叛乱或反抗美国宪法，或向美国宪法的敌人提供援助或支持，则不得担任国会参议员或众议员、总统或副总统选举人，或在美国或任何州担任任何文职或军事职务。但国会可以以两院各三分之二的多数票解除此项限制。

Section 4.  第四节

The validity of the public debt of the United States, authorized by law, including debts incurred for payment of pensions and bounties for services in suppressing insurrection or rebellion, shall not be questioned. But neither the United States nor any State shall assume or pay any debt or obligation incurred in aid of insurrection or rebellion against the United States, or any claim for the loss or emancipation of any slave; but all such debts, obligations and claims shall be held illegal and void.

[.my2]
美国依法授权的公共债务，包括为支付镇压叛乱或暴动所作贡献的养老金和奖金而产生的债务，其有效性不得受到质疑。但是，美国及其任何州均不得承担或支付任何因援助反对美国的叛乱或暴动而产生的债务或义务，也不得承担或支付任何因奴隶的损失或解放而产生的索赔；所有此类债务、义务和索赔均应视为非法无效。

Section 5.  第五节

The Congress shall have the power to enforce, by appropriate legislation, the provisions of this article.

[.my2]
国会有权通过适当的立法来执行本条的规定。

*Changed by Section 1 of the 26th amendment.

[.my2]
* 经第 26 修正案第 1 条修改。

Amendment XV  第十五修正案

Section 1.  第一部分

The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of race, color, or previous condition of servitude—
美国公民的投票权不得因种族、肤色或以前的奴役状况而被美国或任何州剥夺或限制——

Section 2.  第二部分。

The Congress shall have the power to enforce this article by appropriate legislation.

[.my2]
国会有权通过适当的立法来执行本条款。

Amendment XVI  第十六号修正案

The Congress shall have power to lay and collect taxes on incomes, from whatever source derived, without apportionment among the several States, and without regard to any census or enumeration.

[.my2]
国会有权对任何来源的收入征税，无需在各州之间按比例分配，也无需考虑任何人口普查或统计。

Amendment XVII  第十七号修正案

The Senate of the United States shall be composed of two Senators from each State, elected by the people thereof, for six years; and each Senator shall have one vote. The electors in each State shall have the qualifications requisite for electors of the most numerous branch of the State legislatures.

[.my2]
美国参议院由各州选举产生的两名参议员组成，任期六年；每位参议员享有一票表决权。各州的选举人应具备该州议会人数最多的一院选举人所需的资格。

When vacancies happen in the representation of any State in the Senate, the executive authority of such State shall issue writs of election to fill such vacancies: Provided, That the legislature of any State may empower the executive thereof to make temporary appointments until the people fill the vacancies by election as the legislature may direct.

[.my2]
当任何州在参议院的代表出现空缺时，该州的行政机关应发布选举令以填补这些空缺： 但任何州的立法机关可以授权该州的行政机关进行临时任命，直到人民按照立法机关的指示通过选举填补这些空缺为止。

This amendment shall not be so construed as to affect the election or term of any Senator chosen before it becomes valid as part of the Constitution.

[.my2]
本修正案不得解释为影响在本修正案作为宪法的一部分生效之前选出的任何参议员的选举或任期。

Amendment XVIII  第十八号修正案

Section 1.  第一部分

After one year from the ratification of this article the manufacture, sale, or transportation of intoxicating liquors within, the importation thereof into, or the exportation thereof from the United States and all territory subject to the jurisdiction thereof for beverage purposes is hereby prohibited.

[.my2]
自本条款批准之日起一年后，禁止在美国及其管辖的所有领土内制造、销售或运输用于饮用目的的含酒精饮料，禁止将含酒精饮料进口到美国或从美国出口。

Section 2.  第二部分。

The Congress and the several States shall have concurrent power to enforce this article by appropriate legislation.

[.my2]
国会和各州有权通过适当的立法来执行本条规定。

Section 3.  第三节

This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by the legislatures of the several States, as provided in the Constitution, within seven years from the date of the submission hereof to the States by the Congress.

[.my2]
本条规定，除非在国会提交各州之日起七年内，经各州立法机关按照宪法规定批准，作为宪法修正案予以生效，否则本条将不生效。

Amendment XIX  第十九号修正案

The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex.

[.my2]
美国公民的投票权不得因性别而被美国或任何州剥夺或限制。

Congress shall have power to enforce this article by appropriate legislation.

[.my2]
国会有权通过适当的立法来执行本条款。

Amendment XX  第二十条修正案

Section 1.  第一部分

The terms of the President and the Vice President shall end at noon on the 20th day of January, and the terms of Senators and Representatives at noon on the 3d day of January, of the years in which such terms would have ended if this article had not been ratified; and the terms of their successors shall then begin.

[.my2]
总统和副总统的任期应于1月20日中午结束，参议员和众议员的任期应于1月3日中午结束，如果本条款未获批准，他们的任期本应于该年结束；他们的继任者的任期应于那时开始。

Section 2.  第二部分。

The Congress shall assemble at least once in every year, and such meeting shall begin at noon on the 3d day of January, unless they shall by law appoint a different day.

[.my2]
国会每年至少召开一次会议，会议应于每年1月3日中午开始，除非国会依法另行指定日期。

Section 3.  第三节

If, at the time fixed for the beginning of the term of the President, the President elect shall have died, the Vice President elect shall become President. If a President shall not have been chosen before the time fixed for the beginning of his term, or if the President elect shall have failed to qualify, then the Vice President elect shall act as President until a President shall have qualified; and the Congress may by law provide for the case wherein neither a President elect nor a Vice President elect shall have qualified, declaring who shall then act as President, or the manner in which one who is to act shall be selected, and such person shall act accordingly until a President or Vice President shall have qualified.

[.my2]
如果在总统任期开始的预定时间，当选总统已经去世，则当选副总统应继任总统。如果在总统任期开始的预定时间之前尚未选出总统，或者当选总统未能就职，则当选副总统应代理总统职务，直至选出总统为止；国会可以通过法律规定，在当选总统和当选副总统均未能就职的情况下，指定代理总统人选或指定代理总统的方式，该人应代理总统职务，直至选出总统或副总统为止。

Section 4.  第四节

The Congress may by law provide for the case of the death of any of the persons from whom the House of Representatives may choose a President whenever the right of choice shall have devolved upon them, and for the case of the death of any of the persons from whom the Senate may choose a Vice President whenever the right of choice shall have devolved upon them.

[.my2]
国会可以通过法律规定，在众议院选举总统时，如果任何候选人死亡，以及在参议院选举副总统时，如果任何候选人死亡，如何处理。

Section 5.  第五节

Sections 1 and 2 shall take effect on the 15th day of October following the ratification of this article.

[.my2]
本条第1款和第2款自本条批准后10月15日起生效。

Section 6.  第六节

This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by the legislatures of three-fourths of the several States within seven years from the date of its submission.

[.my2]
本条规定，除非自提交之日起七年内，经四分之三的州立法机关批准，作为宪法修正案予以生效，否则将不生效。

Amendment XXI  第二十一条修正案

Section 1.  第一部分

The eighteenth article of amendment to the Constitution of the United States is hereby repealed.

[.my2]
美国宪法第十八修正案现予以废除。

Section 2.  第二部分。

The transportation or importation into any State, Territory, or possession of the United States for delivery or use therein of intoxicating liquors, in violation of the laws thereof, is hereby prohibited.

[.my2]
禁止违反美国任何州、领地或属地的法律，将含酒精饮料运输或进口到美国任何州、领地或属地，以供在那里交付或使用。

Section 3.  第三节

This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by conventions in the several States, as provided in the Constitution, within seven years from the date of the submission hereof to the States by the Congress.

[.my2]
本条规定，除非在国会提交各州之日起七年内，经各州制宪会议批准，作为宪法修正案予以生效，否则本条将不生效。

Amendment XXII  第二十二条修正案

Section 1.  第一部分

No person shall be elected to the office of the President more than twice, and no person who has held the office of President, or acted as President, for more than two years of a term to which some other person was elected President shall be elected to the office of the President more than once. But this Article shall not apply to any person holding the office of President when this Article was proposed by the Congress, and shall not prevent any person who may be holding the office of President, or acting as President, during the term within which this Article becomes operative from holding the office of President or acting as President during the remainder of such term.

[.my2]
任何人不得当选总统超过两届；任何人在另一人当选总统的任期内担任总统或代理总统超过两年，不得再次当选总统。但本条不适用于国会提出本条时已担任总统职务的人，也不妨碍在本条生效期间担任总统或代理总统职务的人在该任期剩余时间内继续担任总统职务或代理总统职务。

Section 2.  第二部分。

This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by the legislatures of three-fourths of the several States within seven years from the date of its submission to the States by the Congress.

[.my2]
本条规定，除非在国会提交各州之日起七年内，经四分之三的州立法机关批准，作为宪法修正案予以生效，否则将不生效。

Amendment XXIII  第二十三号修正案

Section 1.  第一部分

The District constituting the seat of Government of the United States shall appoint in such manner as the Congress may direct:
作为美国政府所在地的哥伦比亚特区应按照国会指示的方式任命：

A number of electors of President and Vice President equal to the whole number of Senators and Representatives in Congress to which the District would be entitled if it were a State, but in no event more than the least populous State; they shall be in addition to those appointed by the States, but they shall be considered, for the purposes of the election of President and Vice President, to be electors appointed by a State; and they shall meet in the District and perform such duties as provided by the twelfth article of amendment.

[.my2]
总统和副总统选举人的人数应等于该特区如果是一个州在国会中应有的参议员和众议员的总数，但无论如何不得超过人口最少的州；这些选举人应在各州任命的选举人之外另行任命，但在选举总统和副总统时，应视为由各州任命的选举人；他们应在该特区集会，并履行第十二条修正案规定的职责。

Section 2.  第二部分。

The Congress shall have power to enforce this article by appropriate legislation.

[.my2]
国会有权通过适当的立法来执行本条款。

Amendment XXIV  第二十四号修正案

Section 1.  第一部分

The right of citizens of the United States to vote in any primary or other election for President or Vice President, for electors for President or Vice President, or for Senator or Representative in Congress, shall not be denied or abridged by the United States or any State by reason of failure to pay any poll tax or other tax.

[.my2]
美国公民在任何总统或副总统初选或其他选举中投票的权利，总统或副总统选举人的权利，或国会参议员或众议员的权利，不得因未缴纳任何人头税或其他税款而被美国或任何州剥夺或限制。

Section 2.  第二部分。

The Congress shall have power to enforce this article by appropriate legislation.

[.my2]
国会有权通过适当的立法来执行本条款。

Amendment XXV  第二十五条修正案

Section 1.  第一部分

In case of the removal of the President from office or of his death or resignation, the Vice President shall become President.

[.my2]
如果总统被免职、去世或辞职，副总统将继任总统。

Section 2.  第二部分。

Whenever there is a vacancy in the office of the Vice President, the President shall nominate a Vice President who shall take office upon confirmation by a majority vote of both Houses of Congress.

[.my2]
当副总统职位出现空缺时，总统应提名一位副总统，该副总统应经国会两院多数票确认后就职。

Section 3.  第三节

Whenever the President transmits to the President pro tempore of the Senate and the Speaker of the House of Representatives his written declaration that he is unable to discharge the powers and duties of his office, and until he transmits to them a written declaration to the contrary, such powers and duties shall be discharged by the Vice President as Acting President.

[.my2]
每当总统向参议院临时议长和众议院议长递交书面声明，表明他无法履行其职务的权力和职责时，在他向他们递交相反的书面声明之前，这些权力和职责应由副总统作为代理总统履行。

Section 4.  第四节

Whenever the Vice President and a majority of either the principal officers of the executive departments or of such other body as Congress may by law provide, transmit to the President pro tempore of the Senate and the Speaker of the House of Representatives their written declaration that the President is unable to discharge the powers and duties of his office, the Vice President shall immediately assume the powers and duties of the office as Acting President.

[.my2]
当副总统和行政部门的主要官员或国会依法规定的其他机构的大多数成员向参议院临时议长和众议院议长递交书面声明，表明总统无法履行其职务的权力和职责时，副总统应立即作为代理总统行使总统的权力和职责。

Thereafter, when the President transmits to the President pro tempore of the Senate and the Speaker of the House of Representatives his written declaration that no inability exists, he shall resume the powers and duties of his office unless the Vice President and a majority of either the principal officers of the executive department or of such other body as Congress may by law provide, transmit within four days to the President pro tempore of the Senate and the Speaker of the House of Representatives their written declaration that the President is unable to discharge the powers and duties of his office. Thereupon Congress shall decide the issue, assembling within forty-eight hours for that purpose if not in session. If the Congress, within twenty-one days after receipt of the latter written declaration, or, if Congress is not in session, within twenty-one days after Congress is required to assemble, determines by two-thirds vote of both Houses that the President is unable to discharge the powers and duties of his office, the Vice President shall continue to discharge the same as Acting President; otherwise, the President shall resume the powers and duties of his office.

[.my2]
此后，当总统向参议院临时议长和众议院议长递交书面声明，表明其并无履行职责的能力时，总统应恢复其职务的权力和职责，除非副总统和行政部门主要官员或国会依法设立的其他机构的多数成员在四日内向参议院临时议长和众议院议长递交书面声明，表明总统无法履行其职务的权力和职责。国会应就此问题作出决定，如国会休会，则应在四十八小时内为此目的召开会议。如果国会在收到上述书面声明后二十一日内，或在国会休会期间，在国会被要求召开会议后二十一日内，经参众两院三分之二多数票通过，认定总统无法履行其职务的权力和职责，则副总统应继续以代理总统的身份履行其职务；否则，总统应恢复其职务的权力和职责。

Amendment XXVI  第二十六号修正案

Section 1.  第一部分

The right of citizens of the United States, who are eighteen years of age or older, to vote shall not be denied or abridged by the United States or by any State on account of age.

[.my2]
年满十八周岁的美国公民的投票权，不得因年龄而被美国或任何州剥夺或限制。

Section 2.  第二部分。

The Congress shall have power to enforce this article by appropriate legislation.

[.my2]
国会有权通过适当的立法来执行本条款。

Amendment XXVII  第二十七号修正案

No law, varying the compensation for the services of the Senators and Representatives, shall take effect, until an election of Representatives shall have intervened.

[.my2]
任何改变参议员和众议员服务报酬的法律，在举行众议员选举之前不得生效。

'''