
:toc:

== 逆矩阵 inverse matrix

有方阵 stem:[ A_{n \times n}], 若存在一个stem:[ A_{n \times n}^{-1}], 使得 stem:[ A * A^{-1} = A^{-1} * A = E] (类似于 stem:[ 2* \frac{1}{2} =  \frac{1}{2} * 2 ]), 则称 A可逆, 且 stem:[A^{-1} ] 就是A的逆矩阵.

但注意: **矩阵永远不能出现在分母上!**

那么问: +
一个方阵, 满足什么条件时, 它才可逆? +
若有逆的话, 它的逆阵是什么?


---


==== 可逆的条件 -> stem:[|A| \ne 0 ]

**若方阵stem:[|A| \ne 0 ], 它就是可逆的.** +
这种行列式的值不为0 的方阵, 也叫"非奇异 /非退化 /满秩"的.

因为行列式的值, 就是它们向量所组成的"平行四边形"的面积. 若 面积=0 了, 说明原坐标系空间被"变换"成零维了, 被降维压缩了. 高维信息全部丢失. 而"逆矩阵"是实现 ctrl + z 作用的, 显然零维物体就无法还原成高维物体了. 所以 ctrl + z 就不可做了. 即不存在你操作, 不存在 stem:[ A^{-1}].

---

==== 当有 stem:[ AB=E 或 BA=E] 时, B 就是A的逆阵.

A若可逆, 其逆阵是什么? **假设它的逆阵是B, 则B必满足这个性质**: stem:[ AB=E 或 BA=E]. 即 stem:[ B=A^{-1} ]. 我们只要算出这个B 就行了.


== 逆矩阵 性质

==== 逆阵是唯一的

**如果A可逆，那么A的逆矩阵是唯一的**. 因此: +
-> 如果有 B、C都是A的逆矩阵，则一定 B=C. +
-> 同样: 若 AB=BA=E, 则 B 就是A的逆阵.

---

====  stem:[  (A^{-1})^{-1} = A]

若A可逆, 则 stem:[ A^{-1}] 亦可逆. 且 stem:[  (A^{-1})^{-1} = A]

---

====  stem:[ (A^T)^{-1} = (A^{-1})^T ]  <- 转置的逆 = 逆的转置

若A可逆, 则 stem:[ A^T] 亦可逆. 且 stem:[ (A^T)^{-1} = (A^{-1})^T ]  <- 转置的逆 = 逆的转置

---

==== stem:[ (AB)^{-1} = B^{-1} A^{-1} ]

若A、B 为同阶方阵, 且均可逆，则AB亦可逆, 且 stem:[ (AB)^{-1} = B^{-1} A^{-1} ] <- 注意AB的顺序要颠倒.

证明过程: +
\begin{align}
& 既然(AB)可逆, 就有: \\
& (AB)(AB)^{-1} = E \\
& (AB)(B^{-1} A^{-1}) = E <- 这一步, 就已经证明了 AB 的逆阵是  B^{-1} A^{-1}
\end{align}


同样: stem:[ (ABCD)^{-1} = D^{-1} C^{-1} B^{-1} A^{-1} ]


---

====  stem:[ (kA)^{-1} = \frac{1}{k} A^{-1} ]

若A可逆, 且stem:[ k \ne 0], 则 kA 也可逆. 且 stem:[ (kA)^{-1} = \frac{1}{k} A^{-1} ] +
<- 你发现, stem:[\frac{1}{k} ] 这个数, 其实就是对k的变换, 能做 ctrl + z 的操作.

---

==== stem:[ |A^{-1}| = |A|^{-1}]

若A可逆, 则 stem:[ |A^{-1}| = |A|^{-1}], 即: 逆的行列式 = 行列式的逆.

---

====  stem:[ (A^{\ast})^{-1} = \frac{1}{|A|} A ]

若A可逆, 则 stem:[ A^{\ast}] 也可逆.  且 stem:[ (A^{\ast})^{-1} = \frac{1}{|A|} A ]

证明过程:

image:../img/0013.svg[]

---

- 单位阵E是可逆的. stem:[E^{-1} = E ]
- 零矩阵不可逆


---

== 求逆的方法

==== 用初等变换法, 求逆 (常用)

比如, 要求A的逆阵, 可以先写这样一个矩阵: [A|E],  把它左边的A, 先变换成E, 则它右边原先的E, 就会变成A的逆阵了. 我们就能得到stem:[A^{-1}] 了.

即: +
\begin{align}
\left[ \begin{array}{c|c}
	A&		E\\
\end{array} \right] \xrightarrow{行变换}\left[ \begin{array}{c|c}
	E&		A^{-1}\\
\end{array} \right]
\end{align}

.标题
====
例: 求 stem:[A^{-1}]

\begin{align}
& 已知 A=\left[ \begin{matrix}
	1&		0&		1\\
	2&		1&		0\\
	-3&		2&		-5\\
\end{matrix} \right]  \\
& 把A和E拼在一起, 构成一个矩阵 \\
& [A|E]=\left[ \begin{array}{ccc|ccc}
	1&		0&		1&		1&		&		\\
	2&		1&		0&		&		1&		\\
	-3&		2&		-5&		&		&		1\\
\end{array} \right] \\
& 做初等行变换, 把竖线左边原先的A, 化成单位阵E: \\
& AE=\left[ \begin{array}{ccc|ccc}
	1&		&		&		-\frac{5}{2}&		1&		-\frac{1}{2}\\
	&		1&		&		5&		-1&		1\\
	&		&		1&		\frac{7}{2}&		-1&		\frac{1}{2}\\
\end{array} \right]
\end{align}

现在, 竖线右边的部分, 就是stem:[A^{-1}]了.

====

做法总结:

1. 先搞第1列, 再第2列, 第3列...
2. **"第1列"处理完后, "第1行"(注意是行!) 就不再主动参与后面的运算. 即不再用 line1 去消下面的行.** 但能用下面的行, 去消 line1上的元素到0.
3. 变换时, 矩阵与矩阵之间, 不能写等号, 要写箭头(→), 即: [] -> [] -> [].
4. 只做"行变换", 而绝不做能"列变换".
5. **如果最后发现 [A|E]的左边, 化不成单位阵E时, 就说明A不可逆.**

关于上面第5点, 比如, 对于这个矩阵: +
\begin{align}
& A=\left[ \begin{matrix}
	1&		2&		3\\
	2&		4&		9\\
	4&		8&		18\\
\end{matrix} \right] \\
& 经过行变换, 你发现 [A|E]只能变成: \\
& [A|E]=\left[ \begin{array}{ccc|ccc}
	1&		2&		3&		1&		&		\\
	0&		0&		3&		-2&		1&		\\
	0&		0&		0&		&		-2&		1\\
\end{array} \right]
\end{align}

你发现竖线左边, 化不成E, 就说明这个A不可逆. +
其实, 你发现, 左边这个行列式的值 = 0. 即 |A|=0, 也说明了A不可逆.





---

==== 用伴随矩阵法, 求逆 (实际中基本不用此法)

\begin{align}
A^{-1} = \frac{1}{|A|}A^{\ast}
\end{align}


---



