= 1154
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,154 – Visiting Historical Sites.
This is English as a Second Language Podcast episode 1,154. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com, and become a member of this wonderful podcast. Well, I think it’s wonderful, anyway. When you become a member, you can download our Learning Guide which includes a complete transcript of everything I say. It also includes a map of where you can find gold here in California. Yes, it does. Go to our website for more information.
In this episode, we’re going to listen to a dialogue between Mary and Will about going to historical sites. Let’s get started.
[start of dialogue]
Mary: I think we should call it a day.
Will: I think we still have time to visit one more historic site and this one is amazing. They’ve done a great job with preservation and restoration.
Mary: It’s not another old castle, is it?
Will: It’s not any old castle. This one dates back to the 1300s. If we’re lucky, we’ll be in time for the last guided tour with a docent who’s knowledgeable. And I hope we have time to visit the archives, too.
Mary: Oh no, not the archives.
Will: I wonder if they’re doing reenactments to commemorate any major historical events during our time here?
Mary: If we visit this castle today, we’re not coming back. There is a lot to see in this city other than old castles and monuments.
Will: Like what?
Mary: Like art museums and stores. It would also be nice to relax a little while on vacation.
Will: But what’s art and shopping when you’re in one of the most ancient cities in the world? And there’s no time to relax. We only have four days here. We have to make the most of it. Hey, where are you going?
Mary: I think it’s time to split up. You go see your castle and I’ll explore on my own.
Will: But you won’t get the full benefits of being in one of the most ancient cities in the world.
Mary: I think I’ll survive.
[end of dialogue]
Mary begins by saying to Will, “I think we should call it a day.” The expression “to call it a day” means to stop doing something for that day, possibly to start again tomorrow. If you’re working late at your office, someone may say, “Well, it’s time to go home. Let’s call it a day,” meaning let’s say this is the end. We’re not going to continue working today.
Mary and Will aren’t working, however. They’re out visiting important historic sites. A “site” (site) is a place of interest. A “historic (historic) site” is a site that is of importance, of historical importance.
There is a difference between “historic” and “historical” (historical). “Historical” is anything from the past. “Historic” is an adjective that describes something that’s very important, that is important in history. Something could be both historic and historical. In fact, most sites, most places that you visit that are considered historic are almost by definition historical as well. They’re old places.
So, for example, if you go to a famous building that was built many years ago, you could call that a “historic site.” You could also call it a “historical site.” However, many cities have “historical places” – places that are old but aren’t important, that aren’t significant in history, and so they’re not historic sites. It’s a little confusing even to native speakers.
Back to our story, Will says, “I think we still have time to visit one more historic site and this one is amazing. They’ve done a great job with preservation and restoration.” “Preservation” (preservation) is when you try to keep something in good condition, something that is old and valuable. “Restoration” (restoration) is when you take something that has been damaged, that needs to be fixed, and make it better.
“Preservation” means to keep something in its current condition. “Restoration” means to fix something and make it better. Many old buildings first need to be “restored” and then “preserved.” Mary says, “It’s not another old castle, is it?” A “castle” (castle) is a large building, usually made of stone, where kings and queens live, or used to live. Many countries, especially in Europe, have castles where kings and queens live or used to live many years ago.
It doesn’t sound like Mary wants to go to another castle. Will says, “It’s not any old castle,” meaning it is a castle but it’s a special one. “This one,” he says, “dates back to the 1300s.” “To date back to” means to have its origins or beginnings in a certain year or period – to be of a certain age. This castle was built, then, in the 1300s, presumably the 1300s A.D., or roughly 700, 800 years ago.
Will says, “If we’re lucky, we’ll be in time for the last guided tour with a docent who’s knowledgeable.” A “guided tour” is a tour that you take of a place or a building led by what we would call a “tour guide,” a person who knows about that place. A “docent” (docent) is a person who works usually in a museum who knows a lot about the things in that museum. Sometimes there are docents who lead tours, who guide people through a museum on a guided tour, explaining what everything means.
Will says, “I hope we have time to visit the archives, too.” “Archives” (archives) usually are large collections of important documents and sometimes small objects. Here in the United States, we have something called the “National Archives.” It’s a place in Washington D.C., a building that has many old important documents and papers. Mary, however, clearly doesn’t want to go to see the archives. She says, “Oh no, not the archives.” She’s saying she doesn’t want to go there.
Will says, “I wonder if they’re doing reenactments to commemorate any major historical events during our time here.” A “reenactment” (reenactment) is a presentation in which people act out something that happened long ago. Usually this is some historical event that you want to teach other people about or you want to understand more yourself. You’ll dress up perhaps in the clothing that people might have worn many years ago and reenact certain famous events. This is quite popular in certain areas.
I’m not really someone who loves the whole idea of reenactments, but people do like them. They can certainly teach us about the way things were perhaps many years ago. People like to reenact old battles. People like to reenact other famous historical events. It’s sort of like putting on a play, but you are acting out or trying to recreate the actions of people many years ago.
“To commemorate” (commemorate) means to remember and honor someone or something in a special way. Reenactments can commemorate some important events, some historical events. Once again we see that word “historical,” meaning old. The word “major” here means very important. Will, then, is wondering if the people at this particular castle will be doing any reenactments to commemorate some major historical event while Mary and Will are visiting.
Mary says, “If we visit this castle today, we’re not coming back. There’s a lot to see in this city other than old castles and monuments.” Mary is saying that if they go to this castle today, they are not going to return later in their trip because she wants to see other things. She thinks there is more to see than “castles and monuments” (monuments).
A “monument” is some object that was built to remember and honor important people or events. If you go to the capital of the United States – Washington, D.C. – you will see many monuments to important people and to important events. Monuments are sometimes built to honor people who have died in a war, for example, or to remember certain important events in a country’s history.
Will says, “Like what?” He’s asking Mary, “What other important things are there to see in this city other than castles and monuments?” Mary says, “Like” – or “such as” – “art museums and stores.” “Art museums” (museums) are places where you of course can see famous pieces of art ?– paintings and sculptures and that sort of thing. Mary says, “It would also be nice to relax a little while on vacation.” Many people go on vacation to see things, but they perhaps don’t relax very much. They don’t just sit and read or talk.
Will says, “But what’s art and shopping when you’re in one of the most ancient cities in the world?” “Ancient” (ancient) means very old. Will is saying that museums and shopping are not very important compared to the other historical things that you can see in this city. He continues, “And there’s no time to relax. We only have four days here. We have to make the most of it.” “To make the most of” something means to take full advantage of it, to use something the most you can.
Will says, “Hey, where are you going?” Mary says, “I think it’s time to split up.” “To split (split) up” is a two-word phrasal verb meaning to separate – for two people to stop doing something together. Normally when we use the verb “to split up” talking about a married couple, we’re talking about two people who are no longer going to be together in their marriage – or you could talk about a boyfriend and a girlfriend splitting up.
However, we can also use this when we are traveling, or we are going to a place and each person wants to go to a different part of that place. We could split up. One of us could go shopping and another could go to monuments, and then we could meet back again later at our hotel. That’s the kind of “splitting up” Mary is talking about, I think. Mary says, “You go see your castle and I’ll explore on my own.” “To explore” (explore) means to move around a place without any clear plan, just to see what you will discover, what you will find new.
Will says, “But you won’t be getting the full benefits of being in one of the most ancient cities in the world.” Mary says, “I think I’ll survive.” She’s not really concerned about it. She says, “I think I’ll survive,” meaning it’s okay, it’s not that important to me – I’m going to be okay even if I don’t visit all of the things that you want to visit. Now see, I am a lot like Will. I like to go and see everything when I go on a vacation, and my wife is a little bit more like Mary. She’d rather relax more.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mary: I think we should call it a day.
Will: I think we still have time to visit one more historic site and this one is amazing. They’ve done a great job with preservation and restoration.
Mary: It’s not another old castle, is it?
Will: It’s not any old castle. This one dates back to the 1300s. If we’re lucky, we’ll be in time for the last guided tour with a docent who’s knowledgeable. And I hope we have time to visit the archives, too.
Mary: Oh no, not the archives.
Will: I wonder if they’re doing reenactments to commemorate any major historical events during our time here?
Mary: If we visit this castle today, we’re not coming back. There is a lot to see in this city other than old castles and monuments.
Will: Like what?
Mary: Like art museums and stores. It would also be nice to relax a little while on vacation.
Will: But what’s art and shopping when you’re in one of the most ancient cities in the world? And there’s no time to relax. We only have four days here. We have to make the most of it. Hey, where are you going?
Mary: I think it’s time to split up. You go see your castle and I’ll explore on my own.
Will: But you won’t get the full benefits of being in one of the most ancient cities in the world.
Mary: I think I’ll survive.
[end of dialogue]
Before I call it a day, I want to thank our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to call it a day – to end something or to stop doing something for the rest of the day, possibly to start again tomorrow
* We’ve done as much as we can without that data. Let’s call it a day and hope that they send us the rest of the information tomorrow.
historic site – a place that has historical importance and is interesting to people
* The city is producing a map of nearby historic sites, and will distribute it to tourists for free.
preservation – the act of maintaining the condition of something; efforts to keep an old or valuable thing in good condition
* The preservation of old documents requires putting them behind special glass and exposing them to very little light.
restoration – the act of fixing and improving something so that it is in better condition; undoing damage and wear
* How long will the restoration of these old statues take?
castle – a large building, typically made of stone, where kings and queens live and rule
* Young princesses rarely left the castle when they were growing up.
to date back to – to have origins in a particular year or period; to be a certain age
* These documents date back to 1835, the year the college was founded.
guided tour – an exploration of an area while being led by someone who is knowledgeable about it and shares a lot of information, usually as part of a large group
* You can explore the ruins on your own, or you can pay a little more for a guided tour.
docent – a knowledgeable guide in a museum or zoo
* The docent explained that we were looking at one of the world’s oldest fossils.
archives – an extensive collection of old, important documents and possibly small objects
* The university’s archives include all the lab documents of scientist Linus Pauling.
reenactment – a presentation in which people act out something that happened long ago, especially to teach others about it
* In Williamsburg, Virginia, visitors can see reenactments of daily life when the United States were still British colonies.
to commemorate – to remember and honor someone or something in a special, ceremonial way
* These statues commemorate the soldiers who died in the war.
historical – relating to things that happened in the past and have been recorded so that they can be remembered and taught to future generations
* Don’t throw out those letters! They’re historical documents!
monument – a statue or other constructed object built to remember and honor important people and events in history
* Washington, DC is filled with memorials and monuments to former U.S. presidents and other important figures in American history.
museum – a large building filled with objects and documents related to a particular topic and/or period of time, designed to educate people about it and preserve the items for the future
* The Smithsonian Air and Space Museum has a fascinating collection of early airplanes.
ancient – very old, from a period a long time ago
* Timothy is fascinated by ancient Greece and the earliest forms of democracy.
to make the most of (something) – to take full advantage of something; to use an opportunity to its fullest potential; to not waste something
* This speaker in the world’s expert on the subject, so let’s make the most of this opportunity to ask her questions.
to split up – to separate; for two people to stop doing something together, and instead do things separately and/or go in separate directions
* We can get all the things on this grocery list if we split up. You buy the vegetables and meat, and I’ll get the canned goods and bakery items.
to explore – to move through a building or area to discover what it includes, without a clear plan, but with interest in learning more about something
* They spent the day exploring the valley in Yosemite National Park.
Comprehension Questions
1. What would you expect to see in the archives?
a) Historic documents
b) Reenactments
c) Monuments
2. Why does Mary say, “I think it’s time to split up”?
a) Because she wants a divorce.
b) Because she thinks they should each do different things.
c) Because she is angry and frustrated with Will.
Answers at bottom.
What Else Does It Mean?
to call it a day
The phrase “to call it a day,” in this podcast, means to end something or to stop doing something for the rest of the day: “We’ve been cleaning out the attic since 8:30 this morning. Let’s call it a day and start again tomorrow.” The phrase “to call it a night” means to end one’s activities and go home or go to bed: “This has been fun, but it’s already 3:00 a.m.! It’s time to call it a night and go home.” Finally, the phrase “to call it like (one) sees it” means to be very direct and straightforward, and say exactly what one thinks: “That is a terrible idea! I’m sorry if that hurts your feelings, but I call it like I see it.”
to make the most of
In this podcast, the phrase “to make the most of (something)” means to take full advantage of something, to use an opportunity to its fullest potential, and to not waste something: “Make the most of your campus tour. Ask questions, learn from current students, and try to find out if this university is a good fit for you.” The phrase “to make too much of (something)” means to treat something with more significance than it deserves, or to pretend something is more important than it really is: “Don’t make too much of this presentation and worry about it too much. It’s just a class assignment.” Finally, the phrase “To make the best of a bad situation” means to find something positive in a bad or challenging situation: “They had to leave their home for a week while the professionals got rid of the rats, but they made the best of a bad situation by treating it like a vacation.”
Culture Note
The Cahokia Mounds
The Cahokia Mounds are a “Native American” (related to the people who lived in North America before the arrival of Europeans, and their descendants) “site” (place; location) in modern-day Illinois that dates back to the 1200s. The “mounds” (hills; piled-up areas) are what “remains” (what is left) of an ancient civilization and a “bustling” (very busy, with a lot of people and activity and movement) city.
The Native Americans who lived there built more than 120 mounds, 80 of which can be seen today. Researchers believe that workers made the mounds by using “woven baskets” (containers made by threading plant material together) to move “earth” (dirt) over many years. “Archaeologists” (scientists who study old objects to learn about ancient cultures) have found many objects in and around the mounds, including “pottery” (ceramics), metals, sea shells, shark teeth, and more. There are many “remnants” (small pieces remaining from what was once there) of buildings on top of some of the mounds. Some of the mounds also have “skeletons” (bones of the human body) and “burial” (related to putting a dead body underground) “artifacts” (old objects that teach us about how people used to live).
Cahokia was an important religious, political, economic, and cultural center. It was also bigger than London in 1250, when it had between 10,000 and 20,000 “inhabitants” (residents; people who lived in a particular place), although some researcher think there may have been as many as 40,000 residents.
The Cahokia Mounds have been a UNESCO World Heritage Site since 1982. The area is currently managed as a State Historical Site.
Comprehension Answers
1 - a
2 - b