= 1164
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,164 – Making Office Renovations.
This is English as a Second Language Podcast episode 1,164. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
You don’t have to come to Los Angeles to visit us, however. You can just go to our website at ESLPod.com. It’s a lot cheaper. When you go to eslpod.com, be sure to become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode. You can also go shopping on our website. Take a look at our ESL Podcast Store for additional courses in Business and Daily English.
This episode is a dialogue between Alice and Dilbert about making changes, physical changes, to an office. Let’s get started.
[start of dialogue]
Alice: I can’t hear you over that hammering. When are these renovations going to be done?
Dilbert: They’re already two weeks past the scheduled completion date and I can only guess at the cost overruns.
Alice: It feels like they’re never going to finish.
Dilbert: I know. When the renovations were announced, I was glad to hear that the office would be reconfigured for better use.
Alice: Me, too.
Dilbert: The upgrades sounded good – new lighting fixtures, flooring, and sound-deadening walls and ceilings.
Alice: I was looking forward to an updated look with new built-ins. This old furniture shows lots of wear and tear.
Dilbert: Yeah, now all I want is to be rid of all this dust. Who can work with this racket?
Alice: Heh? What did you say? Did you say you can’t hack it? Me, neither!
[end of dialogue]
Alice says to Dilbert, “I can’t hear you over that hammering.” “To be able to hear someone over” (over) something means to be able to hear someone despite noise that is in the background that you are also hearing. “Hammering” (hammering) comes from the verb “to hammer.” “To hammer” means to take an object – called, interestingly enough, a “hammer” – and hit another object, usually a small piece of metal called a “nail” (nail).
We use a hammer to put nails into wood or other surfaces, other materials. “Hammering” is the sound that you get when you use a hammer. We often use hammers when we’re putting something together or building something. When Alice says she can’t hear Dilbert “over that hammering,” she means the hammering is so loud she cannot hear Dilbert talking.
She says, “When are these renovations going to be done?” When are they going to be finished? “Renovations” (renovations) are changes to the appearance of a room or a building, usually changes that require taking a wall down, or perhaps putting a new wall up, changing the floors – these are examples of renovations that might take place inside of a building or a room.
Dilbert says, “They’re already two weeks past the scheduled completion date.” “They” in this case are the people who are making the renovations. These people are “already two weeks past the scheduled completion date.” The “completion date” would be the date when something is supposed to be finished, when something is supposed to be completed.
Dilbert says, “I can only guess at the cost overruns.” “To guess at” something is a two-word phrasal verb meaning to estimate the amount or size of something based upon the information that you have. When Dilbert says he can “only guess at the cost overruns,” he means he estimates or expects that the price of this delay in completing the project is going to be high. It’s going to be great.
“Cost overruns” (overruns) refer to the amount of money you have to spend, the expenses of a project, that are more than what you anticipated, more than what was planned. If you have ever done any renovations on your house or apartment, you know that usually they end up costing more than what you expected or what the person doing the renovations told you they would cost.
Alice says, “It feels like they’re never going to finish.” Dilbert responds, “I know. When the renovations were announced” – that is, when they were told that they were going to have these renovations – “I was glad to hear that the office would be reconfigured for better use.” “To reconfigure” (reconfigure) something means to design it in a way that is new – to, we may say, “redesign” it or “reorganize” something.
The offices were Dilbert works are being “reconfigured for better use,” meaning they’re changing things around so that the office is more efficient, perhaps. Alice says she was happy to hear the offices were going to be reconfigured also. That’s why she says, “Me, too.” “Me, too” is an informal way of saying “I agree” or “I also believe that.” Dilbert says, “The upgrades sounded good.” “Upgrades” (upgrades) are improvements in something – in this case, improvements in the office and the way that the office is configured.
Dilbert says that some of these upgrades include “new lighting fixtures and sound-deadening walls and ceilings.” “Lighting fixtures” (fixtures) simply refers to the lamps and bulbs that are attached to the walls and the ceilings that are part of the room. A “fixture” is something usually that is permanently attached to a wall or a ceiling. A “ceiling” (ceiling) is the top of a room. A room has a “floor” (floor) on the bottom, “walls” on the side, and a “ceiling” on top.
Dilbert says the lighting fixtures were going to be changed or upgraded, as was the flooring. The “flooring” refers of course to the kind of surface that is on the floor. Some rooms, such as the room I’m standing in now, have wooden flooring. Some rooms have carpet as flooring. Dilbert says the upgrades also include “sound-deadening walls and ceilings.” Something that is “sound-deadening” (deadening) is something that reduces the amount of noise in a room, usually by making the room quieter.
Alice says, “I was looking forward to the updated look with new built-ins.” “Updated” means more modern – something that is improved, something that is better. “Built -ins” are shelves, cabinets, and other pieces of furniture that are permanently attached to the walls – that is, they aren’t things you can move around.
For example, in some rooms there are “built-in cabinets” – things that you use for storage, things that you use to put things into. A built-in cabinet would be an example of a “built-in” – something that is put in to a room that is usually permanently attached to the ceiling or the floor or the wall or all three.
Alice says, “This old furniture shows lots of wear and tear.” “To show” here means that you can see it. It is easily noticed. “Wear (wear) and tear (tear)” is an expression referring to the damage that occurs slowly over time as things get used. So, if you have, for example, a chair in your room, an old chair that has been there many years, it probably shows a little “wear and tear” – that is, you can see that it’s old; perhaps it’s changed its color or there are parts of the chair that need repairing.
Dilbert says, “Yeah, now all I want is to be rid of all this dust.” To be rid (rid) of” something means to no longer have something, to be free of something that is bothering you or that you don’t like. In this case, Dilbert doesn’t like all of the “dust” (dust). “Dust” usually refers to very small pieces of dirt or other particles, I guess we would call them, that collect on the floor or on a piece of furniture.
If you go away from your house for a couple of months and you return, there will probably be dust on the tables. You can put your hand on the table and move your fingers across the table, and when you lift your hand up, it will have dust on it – those little small pieces of dirt that collect on, say, a piece of furniture. When you build something, or when you renovate something, there is also a lot of dust when they take down the walls or remove the ceilings. Dust will also be present in those situations.
Dilbert then says, “Who can work with this racket?” “Racket” (racket) here refers to a lot of noise, especially constant noise – noise caused, for example, by construction or renovation. A mother might say to her son, “Turn down your radio. I don’t want to hear all of that racket.” The mother is referring to probably her son’s music, which to her sounds just like noise or racket.
As a noun, “racket” can also be used to describe what you use to play certain sporting games such as tennis and badminton. Those sports also use “rackets” – things that you hold in your hand to hit the ball or the object that is used in the game. I think in badminton, in English we call it a “birdie” (birdie). Well, that’s what we called it when we were kids. I think the technical name is something like “shuttlecock.” You don’t need to know that, unless you play badminton, of course.
It’s so loud, however, that Alice can’t hear Dilbert. She says, “Heh? What did you say? Did you say you can’t hack it? Me, neither!” “To not be able to hack” (hack) something means you’re unable to do something. Dilbert actually says the word “racket,” but Alice thinks he’s saying something else. Because of all the noise, she can’t hear him properly. She thinks he said that he “can’t hack it,” meaning he can’t work. He can’t do anything because of all of this noise. He’s unable to perform his job.
She agrees with him, even though that’s not what he said. She says, “Me, neither!” meaning “I can’t either.” Once again, notice that this is an informal way of saying “I don’t either” in English. We’ll often say, in normal conversation, “Me, neither,” even though your grammar book may say that that’s not correct.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Alice: I can’t hear you over that hammering. When are these renovations going to be done?
Dilbert: They’re already two weeks past the scheduled completion date and I can only guess at the cost overruns.
Alice: It feels like they’re never going to finish.
Dilbert: I know. When the renovations were announced, I was glad to hear that the office would be reconfigured for better use.
Alice: Me, too.
Dilbert: The upgrades sounded good – new lighting fixtures, flooring, and sound-deadening walls and ceilings.
Alice: I was looking forward to an updated look with new built-ins. This old furniture shows lots of wear and tear.
Dilbert: Yeah, now all I want is to be rid of all this dust. Who can work with this racket?
Alice: Heh? What did you say? Did you say you can’t hack it? Me, neither!
[end of dialogue]
If your English needs upgrading, you should listen to the wonderful scripts by our amazing scriptwriter, Dr. Lucy Tse. Thank you, Lucy, by the way, for your wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
hammering – the sound of a heavy object hitting a surface, especially of a hammer being used to hit nails into a wall or other object
* Stop that hammering! Wait until after the baby’s nap to hang the pictures.
renovations – changes to the shape, appearance, layout of a room or building that involve construction
* They bought an old house and then made a lot of renovations to update it, including tearing down the wall between the living room and the dining room.
completion date – the date when something should be finished; the anticipated end date of a project
* The new bridge has an official completion date of July 2027, but most people think construction will take an additional five years.
to guess at – to estimate the amount or size of something; to estimate based on available information
* Technology is changing so quickly, we can’t even guess at what cell phones and computers might look like in 20 years.
cost overrun – when expenses are greater than anticipated; when actual expenses are greater than planned or budgeted expenses
* A private company would never tolerate cost overruns of millions of dollars, but such overruns seem common in government projects.
reconfigured – redesigned or laid out and organized in a new way
* When they retired, they reconfigured their home office into a guest room.
upgrade – a new replacement for an older, outdated piece of furniture, equipment, or facility
* You don’t need a new computer. With a few upgrades, like expanded memory and a new video card, it will be great.
lighting fixtures – lamps and bulbs that are attached to walls and ceilings and are part of the room or building
* We should put some lighting fixtures in the ceiling above the couch to make it easier to read at night.
flooring – the type of surface that people walk on, especially tile, carpet, or wood floors
* They installed wood flooring, because it will be easier to clean than carpet.
sound-deadening – reducing the amount of noise in a room by absorbing sound waves
* Eating at the restaurant would be much more enjoyable if they installed some sound-deadening carpet and curtains.
ceiling – the top surface of a room, not the walls or floors; the interior side of a roof
* These raised ceilings are beautiful, but we’ll need to use a ladder to change the light bulbs.
updated – more modern and improved; not old-fashioned or outdated
* Have these sales figures been updated to include this month’s numbers?
build-ins – shelves, cabinets, and other units that are attached to the walls, ceilings, and/or floors, so that they are permanent and cannot be moved easily
* They installed some build-ins in their family room, so now they have a place to store their books, games, and children’s toys.
wear and tear – damage and fading (lightening of color) that occurs gradually over time as objects are used repeatedly
* The used book shows some wear and tear, but it doesn’t have any markings or missing pages.
to be rid of – to no longer have or do something; to be free of something
* It’s going to feel great to be rid of the noisy neighbors next door.
dust – a light powder that covers surfaces that have not been cleaned in a while, typically made of very small pieces of dirt or other particles
* I can tell you don’t cook very often, because your stovetop is covered with dust!
racket – a loud, constant noise
* The neighbors’ children are in a band that practices every night. They call it music, but I just hear a racket.
can’t hack it – unable to do something; unable to function as needed or expected
* Heath has been working in his new job for only a week, but he can’t hack it and he plans to quit tomorrow.
Comprehension Questions
1. What does Dilbert mean when he says, “I can only guess at the cost overruns”?
a) Nobody wants to tell Dilbert how much more the project will cost.
b) The project is costing more than expected, but nobody knows how much more.
c) The budget for the renovations was a secret and was not shared with employees.
2. Why can’t employees work with this racket?
a) Because their offices are too disorganized.
b) Because the workplace is too noisy.
c) Because the air in the building is too dusty.
Answers at bottom.
What Else Does It Mean?
to guess at
The phrase “to guess at,” in this podcast, means to estimate the amount or size of something, or to make an educated guess: “Jenna left her dictionary at home, so she had to guess at the meaning of many of the street signs.” The phrase “I guess so” is used to weakly agree with someone or something, and “I guess not” is used to weakly disagree with someone or something: “Do we need to finish this report by 5:00?” “I guess so, but the boss didn’t give us a definite answer when we asked her earlier.” The phrase “to keep (someone) guessing” means to keep someone feeling excitement and anticipation, not letting them know what will happen: “The movie was great! It kept us guessing until the very end.” Finally, the phrase “you’ll never guess…” is used to introduce some surprising information: “You’ll never guess what I saw downtown today – a bear!”
flooring
In this podcast, the word “flooring” means the type of surface that people walk on, especially tile, carpet, or wood floors: “Make sure you pick a paint color for the walls that coordinates with the tile flooring.” A “floor plan” is a drawing showing the shape of a room and the position of furniture within it, as viewed from above: “The interior designer studied floor plans and then made suggestions about better ways to arrange the furniture.” As a verb, “to floor (someone)” means to or say something that strongly shocks another person: “We were all floored by his surprising announcement.” Finally, the phrase “to floor it” means to make a car go very quickly by pressing the accelerator pedal to the floor of the car: “When the car thief saw that police car, he floored it.”
Culture Note
Office Configurations
American businesses are experimenting with many different “office configurations” (arrangements of workplaces). In the past, many people worked in “cubicle farms” where “the bulk” (most) of each floor was filled with small “cubicles,” or desks with partial moveable walls placed between them. These cubicle farms were surrounded by offices with doors that closed, primarily for managers, but also for “conference rooms” (larger rooms where many people can meet). Cubicles offer little privacy for workers, as their conversations can easily be heard by the people working around them.
In recent years, “open floor plans” have become popular. In an open plan, workers may not have “assigned” (intended for only one person) desks. The workspace is filled with large tables and chairs, and few or no walls. In theory, this office configuration should “facilitate” (make easier) open communication and encourage workers to “collaborate” (work together). But in reality, many workers find that they become distracted too easily, and they “long for” (strongly want to have) a place with some “privacy” (an opportunity to do things without being observed or interrupted by others).
Finally, some businesses are experimenting with “office pods,” or small groups of desks or cubicles placed together. A typical pod might have six triangular cubicles facing each other, somewhat like the slices of a pizza or pie.
Why are there so many different office configurations? Because businesses are trying to identify the most “efficient” (producing the best results with the least amount of resources) and cost-effective use of limited space that “maximizes” (allows for the most) worker “productivity” (how much work someone can do in a period of time) without “diminishing” (reducing) employee satisfaction.
Comprehension Answers
1 - b
2 - b