= 1168
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,168 – Reading Contracts Carefully.
This is English as a Second Language Podcast episode 1,168. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store with several Business and Daily English courses I think you will enjoy. In fact, I know you will enjoy it. If you’re not already subscribing to our Learn English Magazine – our FREE magazine – go to eslpod.com/apple or eslpod.com/android to download our free app.
This episode is a dialogue between Barbara and Sean about reading a contract – a legal document, a legal agreement – very carefully. Let’s get started.
[start of dialogue]
Barbara: Just sign on the dotted line and be done with it.
Sean: Didn’t your parents ever teach you to read every document carefully before you sign it?
Barbara: Not when the contract is boilerplate. All of the terms are standard.
Sean: No, they’re not. Did you notice in the fine print that if the agreement is cancelled, we’re on the hook for additional charges?
Barbara: Really? No, I guess I missed that.
Sean: If you had gone through this document with a fine-tooth comb as I have, you would have noticed that there are loopholes for the other side to end the contract at any time.
Barbara: I guess I overlooked those.
Sean: And there are contingencies for problems on their end, but not on ours.
Barbara: Wow, I didn’t realize they were trying to screw us. Maybe we shouldn’t do business with them.
Sean: Relax. This is par for the course with this kind of contract. They try to sneak in all kinds of things, and it’s our job to find them. We just have to be vigilant, that’s all.
Barbara: Do you think this is going to take much longer? They’re waiting in the other room to finalize the agreement.
Sean: It’ll take as long as it takes. What do you think that cot is for?
[end of dialogue]
Barbara says to Sean, “Just sign on the dotted line and be done with it.” Barbara is telling Sean to sign his name – to put his signature on some sort of contract, some sort of an agreement. A “contract” (contract) is an agreement between two or more people or two or more groups. It usually is used to refer to something that is, what we would say, “legally binding” (binding), meaning that you are required by law to do what you say you’re going to do in the contract, and if you don’t, you could be punished.
Barbra is telling Sean to “sign on the dotted (dotted) line.” It used to be, in many written contracts, that there was a line on which you put your signature. Now, there’s still a line on most contracts, but it was more common I guess, in the old days, to make it a “dotted line,” meaning it wasn’t an uninterrupted line that you would draw with a pencil – rather, it was basically a series of short lines or small points which we would call “dots.” And these little dots were on the paper in the form of a line, and you would put your name on that line. “To sign on the dotted line,” then, means to sign the contract.
Sean says, “Didn’t your parents ever teach you to read every document carefully before you sign it?” Sean is surprised that Barbara wants him to sign this contract without reading it carefully. Barbara says, “Not when the contract is boilerplate.” “Boilerplate” (boilerplate) – one word – is language that is used in some document that is very common, that is used in many different documents of this sort.
Nowadays we would say you basically “copy and paste” the text – that is, it is text that is used in all the contracts or in all the documents of this sort, and therefore the idea is that you don’t really have to read it every time. Once you read it, you don’t need to read it again because it’s going to be the same in the next contract or the next document.
Barbara continues, “All of the terms are standard.” The “terms” (terms) of a contract are the things that the contract says you have to do or the other person has to do. They are requirements of the agreement. “To be standard” means that they are usual – there’s nothing different about them that you wouldn’t normally expect in a contract of this type. Of course, we’re not exactly sure yet what the contract is. Sean says, “No, they’re not,” meaning the terms are not standard. They’re not the usual ones you would expect.
He then asks, “Did you notice” – did you see – “in the fine print that if the agreement is cancelled, we’re on the hook for additional charges?” The “fine (fine) print (print)” of a document or an agreement is the specifics of an agreement that often, in certain legal contracts, actually appear in a smaller font size – in a smaller size. The word “fine” here refers to the size of the letters, the “print,” in the contract.
In some contracts, there are some words that are written larger than others. The words that are written in the smaller print, or the fine print, often contain very important details about the contract that many people don’t read. The “fine print” can also refer in general to the specifics or the details of any agreement, even if they are not actually written in smaller font sizes. Sean says that if the agreement is “canceled” – that is, if it is ended before it is supposed to end – “we’re on the hook for additional charges.”
The expression “to be on the hook” (hook) means you are responsible, usually financially responsible, for something. If there is something in the agreement that says that if you cancel the agreement, you have to pay a “fine” – that is you have to pay the other person some money – that’s an example of being on the hook for something. It’s usually some term in the agreement that requires you to pay something if certain things happen, such as the agreement being “cancelled.”
Barbara is surprised. She says, “Really? I guess I missed that,” meaning I didn’t see that. Sean continues, “If you had gone through this document” – that is, if you had read this document – “with a fine-tooth comb as I have, you would have noticed that there are loopholes for the other side to end the contract at any time.” The expression “to go through something with a fine (fine) – tooth (tooth) comb” means to look at something very carefully, to make sure you don’t miss anything. Notice once again the use of the word “fine” here to mean “small.”
A “comb” is something you would normally use on your hair to keep it straight. A man would use a comb to make sure that his hair is flat against his head. I don’t use a comb anymore since I don’t have any hair. If I did, however, I might use a “fine-tooth comb.” The “teeth” of a comb, like the teeth in your mouth, are things that extend down from the top. A comb has a number of different little pieces of plastic – or whatever the comb is made of – that are used in order to make the comb work to go through your hair.
So, a “fine-tooth comb” would be a comb that has many small, close together, usually, “teeth” that are used to put the hair back into place. Anyway, here the expression just means to look at something very carefully. A “loophole” (loophole) is something in a law or in an agreement such as a contract that is not very clear and that could be used to benefit one side or the other.
In this case, Sean is saying that there are “loopholes” in the contract so that the other party or the other group of people who are signing the contract can end it at any time. The word “party” (party), when we’re talking about a contract, can refer to a single person or to a group of people.
Barbara again says, “I guess I overlooked those.” “To overlook” (overlook) here means not to understand the importance of something or simply not to have seen something because you didn’t look carefully. Sean then says, “And there are contingencies for problems on their end, but not on ours.” A “contingency” (contingency) in a contract is something that says what will happen in the future under certain conditions.
So, for example, a contract might have a “contingency” that says that if you are unable to pay the money that you owe in this contract, you may have to pay an additional fine, an additional amount of money, to the other party in the contract. There are “contingencies” in this contract that Sean and Barbara are talking about that will help the other side, the other party in the contract. That’s what Sean means by “problems on their end, but not on ours.”
Barbara says, “Wow, I didn’t realize they,” meaning the other people in the contract, “were trying to screw (screw) us.” “To screw” someone is a vulgar term that I wouldn’t normally recommend you use, but it means to be very unfair to someone, to try to “cheat” (cheat) another person, to do something that wouldn’t be very nice. A better way of saying this, a more polite way, would be “to take advantage of us,” or “to try” perhaps even “to cheat us.”
Barbara says, “Maybe we shouldn’t do business with them.” Sean says, however, “Relax,” meaning don’t worry. “This is par for the course with this kind of contract.” For something “to be par (par) for the course (course)” means for something to be normal, something to be common or standard, something to be expected. It’s actually a term from the game of golf.
“Par” is the normal score, the standard score, that you would expect on a given hole in golf. Golf is normally a game that is divided up into basically 18 parts. Each part of the game requires you to hit a ball into a hole. What is “par for the course” is what is the normal score that people would get for this particular golf course. Every golf course is a little different. Some are easier, some are harder.
Anyway, back to the story. We use the term “par for the course” simply to mean standard, normal, usual. Sean continues, “They try to sneak in all kinds of things, and it’s our job to find them. We just have to be vigilant, that’s all.” “To sneak (sneak) in” something means to try to get something in a, in this case, contract without the other person noticing – to try to do it in secret.
Sean says that he and Barbara have to be “vigilant” (vigilant). “To be vigilant” means to be very careful about something, to be aware of what is happening, to be looking out for problems or even danger. It means in a sense to stay awake, to be aware of what is going on – in this case, to be very careful in looking at the contract.
Barbara says, “Do you think this is going to take much longer? They’re waiting in the other room to finalize the agreement.” So now we understand that Barbara and Sean are in the same building as the other person or people who are part of this contract, and that they are waiting in the other room “to finalize” (finalize) the agreement. “To finalize” means to finish or complete something.
Sean says, however, “It’ll take as long as it takes.” That expression, “It will take as long as it takes,” means that you, in a way, don’t have any control over the time, or I’m going to take as long as I need to do this right. It’s that second meaning that Sean I think is trying to convey here. He’s saying he’s going to take his time. He’s going to look at this closely even if it takes a long time. “It’ll take as long as it takes.”
Sean says, “What do you think that cot is for?” A “cot” (cot) is a portable folding bed. It’s what you might use, for example, if you go camping. It’s what might be used, for example, in the military, when you have lots of different people in a single place and you don’t have beds for everyone. You may have these portable beds called “cots.”
I once slept on a cot for about six months when I didn’t have a place to stay when I was a younger man, in my twenties. That’s a long story – I’ll tell you that some other time. Sean is sort of making a joke, or maybe not. He’s saying that they’re going to be there so long they may have to sleep in that room, and that’s what the cot is for, because it’s going to take a long time for Sean to finish looking at this contract.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Barbara: Just sign on the dotted line and be done with it.
Sean: Didn’t your parents ever teach you to read every document carefully before you sign it?
Barbara: Not when the contract is boilerplate. All of the terms are standard.
Sean: No, they’re not. Did you notice in the fine print that if the agreement is cancelled, we’re on the hook for additional charges?
Barbara: Really? No, I guess I missed that.
Sean: If you had gone through this document with a fine-tooth comb as I have, you would have noticed that there are loopholes for the other side to end the contract at any time.
Barbara: I guess I overlooked those.
Sean: And there are contingencies for problems on their end, but not on ours.
Barbara: Wow, I didn’t realize they were trying to screw us. Maybe we shouldn’t do business with them.
Sean: Relax. This is par for the course with this kind of contract. They try to sneak in all kinds of things, and it’s our job to find them. We just have to be vigilant, that’s all.
Barbara: Do you think this is going to take much longer? They’re waiting in the other room to finalize the agreement.
Sean: It’ll take as long as it takes. What do you think that cot is for?
[end of dialogue]
There’s nothing boilerplate about our dialogues here on ESL Podcast. They’re all new, all original, every time, thanks to the wonderful work of our scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to sign on the dotted line – to write one’s signature on a line to show one’s agreement with the terms of a contract or agreement
* If you agree to the terms, please sign on the dotted line and then we’ll give you your new cell phone.
contract – a legal agreement between two or more people, parties, or organizations
* We need to make sure the contract has a two-year, not a three-year term.
boilerplate – text that is copied, pasted, and used many times, without being customized
* Each of the company’s press releases ends with the same boilerplate text with the company’s contact information.
term – one part of a contract; one requirement in an agreement
* The contract contains terms that our company won’t agree to.
fine print – the small, specific details in a contract, typically printed in very small letters that can be difficult to read
* When you create an account on a website, do you read the fine print, or just click “Yes, I accept the terms and conditions”?
to cancel – to end something before it has finished, or to stop making regular payments
* Do we have to pay a penalty if we cancel our cell phone contract within the first year?
on the hook – liable and responsible for something; having to do or pay something as part of an agreement
* Clarke signed the rental car agreement, so he is on the hook for any damage.
fine-tooth comb – with attention to all the details of something, not overlooking or missing anything
* When we moved out of the apartment, the landlord inspected everything with a fine-tooth comb, even charging us for dusty blinds and a dirty stove.
loophole – an ambiguity (something that is unclear and can be interpreted more than one way) in the law or the rules, and is beneficial to someone or something
* The company’s accountant found a loophole that allows the company to pay significantly less in taxes.
to overlook – to not see or recognize the importance of something; to miss something in one’s review or inspection
* When we toured the home, we overlooked the broken heating system, but fortunately the inspector found it before we bought the home.
contingency – something that might happen in the future; a potential risk
* Does your insurance policy have contingencies for fire and flood damage?
to screw (someone) – to be very unfair to someone and put that person in a difficult situation for one’s own advantage; to benefit by creating serious problems for another person
* Her boss screwed him by presenting his research as her own.
par for the course – something that is normal, standard, and common, and should be expected
* About one-third of the students failed the exam, but that’s par for the course in Dr. Samuel’s class.
to sneak in – to insert something in a hidden and secretive, because one knows that it is not desirable for the other person
* Mariah has some great recipes for sneaking in vegetables when she cooks for her children.
vigilant – aware of what is happening, looking out for danger, and anticipating potential problems
* The soldiers were vigilant, looking for any signs of the enemy.
to finalize – to finish or complete something, especially to make small changes to reach the final version
* We need to make a few more changes, and then we can finalize the new product for production.
to take as long as it takes – for something to last a certain amount of time, when people have little or no control over the duration, used to indicate one’s acceptance of the length of time
* We’re all waiting for Dad to make a decision, but it will take as long as it takes because he can’t be rushed.
cot – a portable, folding bed
* The hotel room had only two beds, so we asked for a cot for our daughter.
Comprehension Questions
1. What is a boilerplate contract?
a) A standard contract with common language.
b) A contract that is aggressive and harmful to one party.
c) An annual contract that renews automatically each year.
2. What did Sean do when he went through the contract with a fine-tooth comb?
a) He read it very carefully, paying attention to all the details.
b) He paid a lawyer to review and modify it.
c) He wrote his own contract.
Answers at bottom.
What Else Does It Mean?
on the hook
The phrase “on the hook,” in this podcast, means liable and responsible for something, or having to do or pay something: “At the end of the workday, each cashier is on the hook for any shortages in his or her cash register.” The phrase “hook, line, and sinker” is used to emphasize that someone was tricked or fooled completely: “Grandma fell for that e-mail request hook, line, and sinker, and ended up sharing her social security number and bank account information with some thieves.” The informal phrase “to hook (someone) up with (something)” means to get something desirable for someone: “Wow, I can’t believe you hooked us up with tickets for the big game. Thank you so much!”
to sneak in
In this podcast, the phrase “to sneak in” means to insert something in a hidden and secretive, because one knows that it is not desirable for the other person: “How did the kids sneak in these cookies in the grocery basket?” The phrase “to sneak in” also means to secretly enter a building without others noticing or without permission: “The teenagers tried to sneak into the movie theater, but they were caught.” The word “sneaker” is another term for tennis shoes or athletic shoes worn for sports or outdoor activities: “We’re going to go on a long hike, so please put on some comfortable sneakers.”
Culture Note
Do-it-yourself Legal Services
When average Americans need “basic” (simple; uncomplicated) “legal services” (the advice and guidance of an attorney), they may not want to pay a lot of money to “consult” (ask the advice of) a professional “attorney” (lawyer; legal professional). For simple “matters” (issues), they might decide to use “do-it-yourself” (done by oneself, without the help of an expert) legal services. Many companies offer free legal “templates” (basic documents that can be modified). Some sell print versions with “blanks” (lines showing where people need to write in information) for people to “fill in” (insert information). Online versions allow people to type in their information and then print out a professional-looking document.
Popular online legal forms cover everything from starting a business to writing one’s “last will and testament” (a document stating what should be done with one’s possessions and “assets” (thing of value) when one dies). People can also use the forms to “file” (submit official paperwork) for “bankruptcy” (a statement that one has no money and needs to ask for forgiveness from the people and organizations to whom one owes money). People who are immigrating to the United States can use do-it-yourself legal services to complete paperwork, such as an application for a green card.
There are do-it-yourself legal services for creating a “prenuptial agreement” (a contract signed before marriage that states who will receive what if the marriage ends due to divorce), changing one’s name, such as when a woman gets married and “takes her husband’s last name” (begins to use her husband’s last name instead of the one she used to have), and filing for “divorce” (the legal end of a marriage).
These forms are “suitable” (appropriate) for many situations, but anyone with an unusual or “complex” (complicated; with many parts) situation would do better to “seek” (look for and get) the services of a professional attorney.
Comprehension Answers
1 - a
2 - a