= 1220
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,220 – Ramping Up Production.
This is English as a Second Language Podcast episode 1,220. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com to become a member of ESL Podcast and download the PDF Learning Guide for this episode. The Learning Guide contains a complete transcript of everything we say, in addition to a complete list of all the vocabulary words, definitions, and additional sample sentences.
This episode is a dialogue between Valerie and Kareem about increasing production – that is, beginning to make more of something in your business. Let’s get started.
[start of dialogue]
Kareem: Have you seen the latest sales figures? We need to ramp up production right now.
Valerie: We don’t know if that increase is simply a blip or a trend.
Kareem: Those sales figures are significantly above projected levels. Our product is in demand and we need to meet that demand with a larger production run.
Valerie: But that would mean a big increase in capital outlay.
Kareem: We have to spend money to make money. We don’t want to be caught short if sales continue like this.
Valerie: But if they don’t, we’d be saddled with a huge surplus in inventory.
Kareem: When we rolled out this new product, we hoped it would catch on and it has. Are we going to sit on our hands and do nothing?
Valerie: I guess you’re right. Should we increase production by 10 percent?
Kareem: Ten percent? We’re doubling production.
Valerie: Doubling production?! Are you crazy?
Kareem: Crazy like a fox.
[end of dialogue]
Kareem begins by asking Valerie, “Have you seen the latest sales figures?” The word “latest” here means most recent – the newest ones. “Sales” (sales) refers to the things that you sell. “Figures” (figures) refers to numbers. So, “sales figures” would be numbers that reflect how much you’ve sold. Have you sold a million dollars? Have you sold a thousand dollars? Those would be examples of sales figures.
Kareem says, “We need to ramp up production right now.” “To ramp (ramp) up” means to increase. “Production” is making things. So, “to ramp up production” means to increase the number of things you are making. Normally the word “production” is used when we’re talking about physical things. Cars and chairs and cups – those are things that you could ramp up production on. Kareem is talking about ramping up production on whatever it is that the company Kareem and Valerie work for makes. We’re not sure what product, what thing the company makes at this point.
Valerie says, “We don’t know if that increase is simply a blip or a trend.” Kareem is looking at how much the company has sold of the product and believes they need to make more, probably because they have started to sell more. Valerie, however, says, “We don’t know if that increase” – the increase in sales – “is simply,” or just, “a blip” (blip).
A “blip” is an increase in something, but it doesn’t last very long. We might say it’s a “short-lived change” from the expected level of something. If you have a “blip” in your sales figures, your sales went up for a short time, but it went back down again later. A “trend” (trend) is the direction that something is moving. It could either be getting better or getting worse over time. It’s the direction of change in something. Valerie is saying that it isn’t clear if the increase in sales is really a trend, if it is actually going to continue increasing.
Kareem says, “Those sales figures are significantly above projected levels.” “Significantly” here means a lot – a lot above projected levels. Something that is “projected” (projected) is something that is predicted – what you think will happen in the future. The “level” (level) of something is the amount of something, in this case. So the “projected level” is what you think something is going to be in the future – how much you will have of a certain thing – in this case, sales – in the future.
Kareem says, “Our product is in demand.” If something is “in demand,” it is desired. It is wanted. It is something people want to get. You might read in the newspaper that housing is “in demand.” That means that lots of people are looking for places to live, perhaps because more people have moved into an area. Kareem is talking about the product that their company makes being “in demand,” meaning lots of people want to buy it. He says, “We need to meet that demand” – that is, we need to satisfy that demand, we need to give people what they want – “with a larger production run.”
A “production run” is when you make a certain amount of things all at once or during a short amount of time. Valerie says, “That would mean a big increase in capital outlay.” “Outlay” (outlay) is the money you spend to make something or do something. “Capital” (capital) refers to money that is used to buy new equipment or buildings or whatever it is you need in your business to make your business successful. “Capital” in business English usually refers to the things you have in order to make money. You use them to make other things.
So a computer, for example, is an example of a capital expense or a “capital outlay.” You don’t sell the computer to your customers or clients; you use the computer to make something. Well, “capital outlay” in this case would be anything the company would have to spend money on in order to ramp up production. That might include new machines, for example. Kareem says, “We have to spend money to make money.” This is an old expression. If you want to make a lot of money, you may have to spend some money first in order to get money later.
“We don’t want to be caught short if sales continue like this,” Kareem says. “To be caught short” means not to have enough of something, especially when you’re talking about money. If you go to a restaurant and you order a big meal, and then you look in your wallet and see you don’t have any money or credit cards, you are “caught short.” This is a good time to get up and go to the bathroom and slip out, or escape through the back door of the restaurant. I’m just kidding. You should never do that.
Valerie disagrees. She says that if the company doesn’t continue selling its product the way they are now, that the company would be “saddled with a huge surplus in inventory.” A couple of important expressions here. Let’s start with “to be saddled (saddled) with” something. “To be saddled with” something is the same as “to be stuck (stuck) with” something. Both expressions refer to having to do something or having to keep something that you don’t really want to do or to keep.
For example, if you go to school and you take out a lot of loans to pay for going to school for your classes, and then after leaving school you can’t get a job, you are going to be saddled with a lot of debt – money that you have to pay other people. You can’t avoid it because you took out these loans. You borrowed money from other people to pay your tuition, to pay for your classes. Valerie is worried that if the company makes a lot of new products and sales don’t continue, they will have all of these extra products. They will be “saddled with,” or stuck with, “a huge surplus in inventory.”
“Inventory” (inventory) refers to things that your company makes that you have in your offices or somewhere waiting to be sold. “Inventory” refers to products that are being stored, that are being kept somewhere until they are sold. A “surplus” (surplus) is more than what you need. It’s extra. A “huge surplus in inventory,” then, refers to lots of products that your company has made that you don’t need or that you can’t sell.
Kareem says, “When we were rolled out this new product, we hoped it would catch on and it has.” The phrasal verb “to roll (roll) out” means to start selling something or start offering something for people to buy. The phrasal verb “to catch (catch) on” means to become popular. Kareem says that they rolled out their new product and it, in fact, “caught on.” Notice “caught” is the past tense of “catch.” So the product “caught on.”
“Are we going to sit on our hands and do nothing?” Kareem asks. The expression “to sit on your hands” means to take no action, to do nothing. It’s somewhat repetitive for Kareem to say “sit on our hands and do nothing.” “To sit on your hands” is an expression that means to do nothing, to take no action. Valerie says, “I guess you’re right.” Now she agrees with Kareem. “Should we increase production by 10 percent?”
Kareem says, “Ten percent? We’re doubling production.” “To double” (double) is to do twice as much of something, to increase the amount by 100 percent. Valerie thought they should increase production by 10 percent. Kareem says, “No, we should double it.” Valerie can’t believe what Kareem is saying. She says, “Are you crazy?” Kareem responds with an old expression, “Crazy like a fox” (fox).
The expression “crazy like a fox” refers to someone who seems to be crazy, who seems to be not acting logically or rationally, but actually is very smart, very intelligent, who knows what he’s doing, who is doing something (even if you can’t realize it) that is very intelligent. Is Kareem crazy like a fox or is he just crazy? I guess Kareem and Valerie will find out soon.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Kareem: Have you seen the latest sales figures? We need to ramp up production right now.
Valerie: We don’t know if that increase is simply a blip or a trend.
Kareem: Those sales figures are significantly above projected levels. Our product is in demand and we need to meet that demand with a larger production run.
Valerie: But that would mean a big increase in capital outlay.
Kareem: We have to spend money to make money. We don’t want to be caught short if sales continue like this.
Valerie: But if they don’t, we’d be saddled with a huge surplus in inventory.
Kareem: When we rolled out this new product, we hoped it would catch on and it has. Are we going to sit on our hands and do nothing?
Valerie: I guess you’re right. Should we increase production by 10 percent?
Kareem: Ten percent? We’re doubling production.
Valerie: Doubling production?! Are you crazy?
Kareem: Crazy like a fox.
[end of dialogue]
You can’t just sit on your hands and expect to improve your English. You have to do something. I suggest you listen to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
Glossary
sales figures – information about how many items a company or salesperson has sold and how much money those sales have earned
* These sales figures are unacceptable if we plan to stay in business. How can we get more people to buy our products?
to ramp up production – to increase the number of items that one is manufacturing or creating, possibly including an increase in speed
* We’re going to need a bigger factory if we want to ramp up production.
blip – a deviation; a short-lived change or departure from the expected level or amount of something
* The scientists are monitoring the radio waves for any unexpected blips.
trend – a direction of change or movement over time, especially an increase or decrease in something
* If current trends continue, more than half of the students at our school will be from low-income families by the end of 2020.
projected level – the amount that one anticipates; the expected amount of something, calculated by extending current numbers or values into the future
* The projected level of inventory should last through the end of the quarter.
in demand – wanted and desired; with people wanting to buy or have something
* Ice cream is in demand in summertime, but not as popular in wintertime
production run – the number of items that are produced or manufactured at a single time or with a particular group of resources
* Let’s start with a small production run to test the market. We can always use larger production runs if we sell everything.
capital outlay – a significant amount of money spent to buy or maintain land, buildings, equipment or other assets that will be used for several or many years
* We’re going to need to ask the bank for a loan to cover the capital outlay associated with opening a new office location.
to be caught short – to not have enough of something, especially when talking about money
* Wyatt was really embarrassed to be caught short of money on his date. He had to ask his date to pay for their dinner.
saddled with – burdened with; forced to have or do something that one does not want, with no way to avoid or get rid of it
* Don’t be in such a hurry to get married and have kids. You don’t want to be saddled with all those responsibilities at such a young age.
surplus – extra; more than one needs
* Where can we store all these surplus office supplies?
inventory – products that one is storing until they can be sold
* We’re going to need a warehouse to store all this inventory. There just isn’t room for it in the garage anymore.
to roll out – to launch; to enter full production; to begin offering or selling something
* We’re rolling out some exciting new services for our customers at the end of the year.
to catch on – to become popular and well known
* Three-dimensional printers are catching on among scientists, engineers, teachers, and even young children.
to sit on (one’s) hands – to do nothing; to take no action
* How can you sit on your hand and refuse to help when a member of your own family is in trouble?
to double – to increase the amount of something by 100%; to multiply something by two
* We doubled our earnings from $400,000 to $800,000 in just six months.
crazy like a fox – appearing to be crazy or irrational, but actually being very sly, clever, and intelligent
* Ulysses has some strange ideas, but that man is crazy like a fox. We should definitely consider accepting his proposals.
Comprehension Questions
1. What is a blip?
a) A period when no one is allowed to speak.
b) A significant decrease in the amount of something
c) A change from the standard or normal level
2. What will they do if they sit on their hands?
a) They will try very hard to not applaud their success.
b) They will not do anything at all.
c) They will make a decision immediately.
Answers at bottom.
What Else Does It Mean?
production run
The phrase “production run,” in this podcast, means the number of items that are produced or manufactured at a single time or with a particular group of resources: “The entire production run was damaged because one of our fans stopped working.” A “print run” refers to the number of books, magazines, or newspapers that are printed at the same time: “The author was thrilled to learn that the first print run of her books sold out in just a few weeks.” The phrase “dry run” refers to a rehearsal or an opportunity to practice something before the main event: “Try to give your speech in an empty auditorium as a dry run.” Finally, a “fun run” is an event in which many people run a certain distance in order to raise money for a charitable organization or cause: “The fun run raises money for cancer research.”
saddled with
In this podcast, the phrase “saddled with” means burdened with something, or forced to have or do something that one does not want: “How did you get saddled with writing the other team’s report?” The phrase “saddle up” means to put a saddle (seat) on a horse’s back: “Let’s saddle up and have the horses ready to go by sunrise.” The phrase “saddle sore” describes the pain that someone feels after riding a horse or a bicycle: “If you haven’t ridden a bike in a while, you might be saddle sore after our ride.” The phrase “in the saddle” means riding a horse: “My body was really sore after spending most of the day in the saddle.” Finally, the phrase “in the saddle” can mean in a position of authority or control: “Which political party do you think will be in the saddle after the next election?”
Culture Note
Federal Property Disposal
When the “federal” (national) government has “surplus” (extra and unnecessary) “property” (things that one owns), it “goes through” (participates in) a property “disposal” (getting rid of something) “process” (a series of steps that are followed in a particular way). The General Services Administration (GSA) requires that federal “agencies” (departments) report their surplus property. It also requires that agencies “acquire” (buy) surplus items before they buy new items. This “minimizes” (reduces) expenses.
If federal agencies do not need the surplus items, they may be offered to state and local organizations, and then to “nonprofits” (organizations not intended to make money). If there is still no interest in the items, they may be offered to “the public” (ordinary citizens not affiliated with any particular agency or organization).
Many unwanted items end up at “surplus stores” or “army/navy stores.” Some of the items are new, and others are “used” (have been used by someone else), but still have a “usable life” (can still be used by others). Surplus stores are similar to thrift stores and other “secondhand stores” (stores where used items are sold), but they often sell items “in bulk” (in very large quantities).
“Real property” (real estate; buildings and land) that the federal government no longer needs is often sold though “property auctions.” These are events at which goods are sold “to the highest bidder” (to the person who is willing to pay more than anyone else for a particular item). The items that are “up for sale” (being sold) are described to “potential” (possible) bidders before the auction so that they can “place” (make) “informed bids” (offers that are reasonable and reflect the value of the item).
Comprehension Answers
1 - c
2 - b