= 1247
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,247 – Doing Meal Planning.
This is English as a Second Language Podcast episode 1,247. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode.
This episode is a dialogue between Donny and Helene about planning what you’re going to eat this week. I’m hungry already. Let’s get started.
[start of dialogue]
Donny: Have you ever heard of something called a “meal plan”?
Helene: Sure, I make one each week before I go grocery shopping. It saves time and money.
Donny: My mother suggested I make one now that I’m staying home with the kids and Sydney is going back to work.
Helene: See this? This is my meal plan. I map out the dinners I’ll be making each day. It helps me a lot.
Donny: How? It seems like a lot of work.
Helene: Well, for one thing, I only have to go grocery shopping once a week. I buy a week’s worth of groceries in one fell swoop.
Donny: I guess that’s helpful, but it still seems like too much work.
Helene: Here’s what I do. I look at each week’s store circular to see what’s seasonal and on sale. I pull out my recipes that include those items and I see if I have any coupons I can use.
Donny: I still don’t see how I can save much money.
Helene: I also use the sale items for more than one meal and make enough to have leftovers for lunch the next day. It works like a charm.
Donny: I think I’ll stick to my original plan.
Helene: Which is?
Donny: To plead ignorance and ask my mother over to our house to give me cooking lessons. By the time I cook well enough on my own, the children will be nearly full-grown!
[end of dialogue]
Our dialogue begins with Donny asking Helene, “Have you ever heard of something called a ‘meal plan’?” A “meal” (meal) is what you eat at a certain time during the day. Breakfast, lunch, and dinner are three meals that most people eat each day. A “meal plan” is something you write down describing what you’re going to eat in the next, say, week or even month. Helene says, “Sure, I make one,” meaning I write a meal plan, “each week before I go grocery shopping.”
“Grocery (grocery) shopping” refers going to a store to buy food. “Groceries” is another word for food that you buy in a store to eat and or prepare at home. Helene says, “It’s saves time and money” – that is, having a meal plan saves time and money. Donny says that his mother suggested that he make a meal plan since he is now staying home with his kids, his children, and Sidney, his wife, is going back to work. Helene says, “See this?” She’s obviously showing something to Donny we can’t see. Well, you can’t see it. I can see it because I’m right here.
Helene says, “See this? This is my meal plan. I map out the dinners I’ll be making each day.” “To map (map) out” is a two-word phrasal verb that can mean simply to plan and describe something in detail by writing it down. People will sometimes use this expression in business. “Let’s map out our future.” Let’s plan what we’re going to do in the next month or two months or year. Literally, “to map out” would be to draw on a piece of paper or to take a map and indicate where you are going to travel. Donny says, “How?” How does this help you? “It seems like a lot of work.”
Helene says, “Well, for one thing, I only have to go grocery shopping once a week. I buy a week’s worth of groceries in one fell swoop.” Helene says she only goes to the grocery store once of week. She buys “a week’s worth” (worth). A “week’s worth” of something would be enough of something that would last you, that would be enough for you to use, for an entire seven days. “A month’s worth” would be enough for a month, and so forth. She buys “a week’s worth of groceries in one fell (fell) swoop (swoop).” The expression “in one fell swoop” means all at once, at a single time.
Donny says, “I guess that’s helpful, but it still seems like too much work.” Helene then explains what she does. She says, “I look at each week’s store circular to see what’s seasonal and on sale.” Here in the United States, grocery stores will often include in a local newspaper or mail to you something called a “circular” (circular). The word “circular” is just a special term for an advertisement that shows all of the discounts, all of the sales, at a particular store. Helene looks for “seasonal food.” Food that is “seasonal” (seasonal) is food that is fresh. We’re talking here about fruits and vegetables.
Helene says she also looks for anything else that’s “on sale.” “To be on sale” (sale) means it is being sold at a lower price than usual, than normal. She says, “I pull out my recipes that include these items and I see if I have any coupons I can use.” A “recipe” (recipe) is a set of written instructions or steps on how to prepare a certain kind of food. A “coupon” (coupon) is usually a small piece of paper that gives you a certain discount, a lower price, when you bring it to the store. Nowadays people have coupons that are electronic that you can have on your phone or in an email.
Donny says, “I still don’t see how I can save much money,” meaning a lot of money. Helene says, “I also use the sale items for more than one meal and to make enough to have leftovers for lunch the next day.” “Leftovers” (leftovers) refers to food that you prepared for one meal but didn’t finish, and therefore are able to eat at a later time. So, if you make something for dinner and you have some food that is “leftover,” that is extra, you can eat that food tomorrow for lunch.
Helene says, “It works like a charm” – that is, her plan “works like a charm” (charm). The expression “to work like a charm” means it works very well. It’s an excellent solution to a problem. Donny, however, doesn’t seem convinced. He’s not persuaded. He says, “I think I’ll stick to my original plan.” “To stick (stick) to” something is a two-word phrasal verb meaning to continue doing what you have been doing, to continue doing something without changing it. Donny is going to stick to his first or original plan. Helene says, “Which is?” meaning “What is that plan?”
Donny then explains: “To plead ignorance and ask my mother over to our house to give me cooking lessons.” “To plead (plead) ignorance (ignorance)” means to say that you don’t know something or understand something, even though you may in fact know it or understand it. If someone “pleads ignorance,” they say “I didn’t know” or “I don’t know” something. Maybe that person is telling the truth and maybe he isn’t. Donny wants to plead ignorance about cooking and ask his mother over to his house – that is to say, “invite” her to his house – to give him “cooking lessons,” to teach him how to cook.
He says, “By the time I cook well enough on my own,” meaning by the time or by that point in the future when I am able to cook without my mother’s help, “the children will be nearly full-grown.” “To be “full (full) – grown (grown)” means to be an adult, to no longer be a child. If we say someone is “full-grown,” we mean that person is now no longer a child. They’re 18 years old or 21 years old, or it could also refer to a adolescent who has stopped growing, who will no longer get any taller, for example. “Full-grown” could also describe a plant or a tree that will no longer grow any more or get any bigger than it is now.
Here it refers to Donny’s children becoming old enough so that they are adults. Donny is saying that because he will learn to cook so slowly from his mother, his mother will in fact do most of the cooking for his children until they are practically adults. It sounds to me like Donny’s plan is better than any meal plan.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Donny: Have you ever heard of something called a “meal plan”?
Helene: Sure, I make one each week before I go grocery shopping. It saves time and money.
Donny: My mother suggested I make one now that I’m staying home with the kids and Sydney is going back to work.
Helene: See this? This is my meal plan. I map out the dinners I’ll be making each day. It helps me a lot.
Donny: How? It seems like a lot of work.
Helene: Well, for one thing, I only have to go grocery shopping once a week. I buy a week’s worth of groceries in one fell swoop.
Donny: I guess that’s helpful, but it still seems like too much work.
Helene: Here’s what I do. I look at each week’s store circular to see what’s seasonal and on sale. I pull out my recipes that include those items and I see if I have any coupons I can use.
Donny: I still don’t see how I can save much money.
Helene: I also use the sale items for more than one meal and make enough to have leftovers for lunch the next day. It works like a charm.
Donny: I think I’ll stick to my original plan.
Helene: Which is?
Donny: To plead ignorance and ask my mother over to our house to give me cooking lessons. By the time I cook well enough on my own, the children will be nearly full-grown!
[end of dialogue]
Listening to ESL Podcast to improve your English works like a charm. You should try it more often, especially when you listen to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
meal plan – a written document describing what one intends to cook and eat over the next several days, or a week or month
* By following this meal plan, you can use up to 10 pounds in one month.
grocery shopping – the process of going to a store and buying the food items one needs
* I went grocery shopping yesterday, but I forgot to buy eggs and carrots, so I’ll need to go again soon.
to map out – to plan and describe something in detail, especially writing it down
* Let’s map out our strategy for finishing this project on time.
a week’s worth – with enough to last for an entire week
* We’ll be in the Caribbean for a week, so we’ll need to pack at least a week’s worth of clothes.
in one fell swoop – all at once; in a single attempt or effort
* They painted the entire home in one fell swoop, rather than doing just one room at a time.
store circular – an advertisement that shows discounted (lower than usual) prices at a particular store, typically valid for a single week
* I took a quick look at the store circular, and it looks like peaches and asparagus are on sale this week.
seasonal – fresh, inexpensive, and readily available (with a lot of something) only at certain times of year, typically referring to foods that are grown locally or regionally
* This restaurant makes delicious milkshakes and smoothies with different kinds of seasonal fruit.
on sale – with a discount; at a lower-than-usual price; with a temporary price reduction
* Chicken breasts and ground beef are on sale this week, but the pork chops are really expensive.
recipe – written instructions for how to prepare a particular type of food
* This is my grandmother’s recipe for cornbread and chili.
coupon – a small printed piece of paper that provides a discount (lower-than-usual price) on a particular item sold in a store
* This coupon is good for 40￠ off of canned green beans.
leftovers – food that was not eaten when it was originally prepared, but can be saved for a future meal
* We could save a lot of money by taking leftovers to work for lunch rather than eating at restaurants.
to work like a charm – to work very well; to be an excellent solution with no problems or flaws
* If your girlfriend is mad at you, just apologize and give her some flowers. It works like a charm.
to stick to – to continue to have or do something without changing it
* It’s really hard to stick to a workout schedule and go to the gym every single morning.
to plead ignorance – to say that one does not know or understand something, usually when one actually does
* The judge often hears people plead ignorance, saying that they weren’t aware of the law.
full-grown – fully grown; an adult, not a child
* Wow, I never thought I would hear a full-grown man cry for his mother like that when getting a simple injection in his arm.
Comprehension Questions
1. What does Helene mean when she says, “I map out the dinners”?
a) She decides where she is going to eat.
b) She decides where she will buy food.
c) She decides what foods she will prepare.
2. What does Donny mean when he says, “the children will be nearly full-grown”?
a) The children will be adults.
b) The children won’t want to eat.
c) The children will have enough money to go to restaurants.
Answers at bottom.
What Else Does It Mean?
to map out
The phrase “to map out,” in this podcast, means to plan and describe something in detail, especially writing it down: “They’re spending two weeks in Africa and have mapped out how much time to spend in each country.” The verb “to map” also means to make a map, or a drawing that represents the position or location of things: “Researchers are mapping out the bottom of the ocean in greater detail.” The phrase “to put (something) on the map” means to make a place famous: “This new museum should help to put our small town on the map.” Finally, the phrase “to wipe (something) off the map” means to completely destroy something: “We’re hoping to wipe malaria and other diseases off the map within the next 10 years.”
full-grown
In this podcast, the phrase “full-grown” means fully grown and refers to an adult, not a child: “This sofa can accommodate three full-grow people, or about five children.” Or, “How big will that dog be once it’s full-grown?” The phrase “to grow up” means to become older and mature: “Keith grew up in a rural area, but moved to a large city for college.” The phrase “to grow apart” means for two people to develop different interests and become less close: “The two sisters were close as children, but they grew apart as they got older.” Finally, the phrase “to grow out of (something)” means to lose interest in something and stop wanting to do it as one gets older: “He used to love playing with trains, but he grew out of it by the time he entered high school.”
Culture Note
Meals on Wheels
“Meals on Wheels” is a “charitable organization” (a nonprofit organization that tries to improve society and serve others in some way) that delivers “meals” (breakfast, lunch, and dinner) to the homes of people who cannot buy or prepare meals “on their own” (independently; without help from other people). Many of these people are “the elderly” (old people) who have poor health or “mobility” (the ability to move around) problems, or can no longer see or drive. Others are people with “severe” (very difficult) “physical impairments” (handicaps; things that one’s body cannot do) that prevent them from going to the store or “maneuvering” (moving) around a kitchen.
Meals on Wheels began in the United Kingdom in the early 1940s, and “Meals on Wheels America” was officially established in the United States in 1954. Today the organization supports more than 5,000 “senior” (for older people) “nutrition” (related to the healthfulness of food) organizations across the country. It has also “inspired” (led to the creation of) many other food delivery charities, some of which are also referred to as Meals on Wheels, even though they are not officially part of the national organization.
Most of the drivers are “volunteers” (people who work without receiving payment), and many of them are also elderly. They not only deliver food, but also serve as an important connection to the community for people who are “homebound” (must stay at home; cannot leave their home) and would “otherwise” (under other circumstances, if the volunteers did not visit them) not have opportunities for “conversation” (discussions) and “interactions” (opportunities to spend time with other people).
Comprehension Answers
1 - c
2 - a