= 1250
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,250 – Dealing with Bossy People.
This is English as a Second Language Podcast episode 1,250. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. You can download our Learning Guides when you do that. They contain a complete transcript of everything we say as well as a complete glossary with definitions and sample sentences, as well as culture notes and a whole lot more.
This episode is a dialogue between Rachel and Logan about having to work with or live with people who like to tell you what to do. Let’s get started.
[start of dialogue]
Rachel: What you need to do is . . .
Logan: Stop bossing me around! I know what I’m doing so back off.
Rachel: What’s gotten into you? I’m not bossing you around. I’m trying to help you. Some people are so ungrateful.
Logan: It’s true that I’ve made my share of mistakes, but I don’t need you here to push me around calling all the shots.
Rachel: Here’s a reality check: Without me keeping an eye on you and steering you away from bad decisions, you’d be back in trouble again.
Logan: When I asked for your help, I’d forgotten how pushy and controlling you are. I’m not going to let you walk all over me like you did when we were kids.
Rachel: Who is trying to walk all over you? If you think I’m being high-handed then I’m out of here.
Logan: Good. I don’t know what possessed me to ask you for help in the first place.
Rachel: Well, things never change, do they?
Logan: Apparently not!
[end of dialogue]
Our dialogue begins with Rachel saying to Logan, “What you need to do is . . .” Logan interrupts her. He stops her and says, “Stop” – meaning quit – “bossing me around.” “To boss (boss) someone around” is a phrasal verb meaning to tell another person what to do, even when you do not have any authority over that person. So for example, if you are at work and someone you work with starts telling you what to do, even though that person is not your boss -– that is not the person in charge of you – you might consider that person as trying “to boss you around.” That person isn’t the one that is supposed to tell you what to do, but he is telling you what to do anyway.
“To be bossy” (bossy) means to always be telling other people what they should do even though you don’t have the authority to do that. Now, when a parent tells a child what to do, we don’t call that being “bossy” because we expect the parent to tell the child what to do. “Bossy” as an adjective refers to people who are telling other people to do things even though they shouldn’t be or don’t have the authority to do so.
Logan says, “I know what I’m doing so back off.” Logan is telling Rachel “to back off.” “To back off” is a two-word phrasal verb meaning to stop telling another person what to do, or simply to tell another person to stop being so aggressive – to stop trying to control you. If someone is always attacking you or always criticizing you, you might say, “You know what? Back off. Don’t continue to criticize me.” You might also use this phrasal verb in a physical confrontation – that is, when another person comes close to you and perhaps wants to fight you. You might tell that person “to back off” – to move away from you physically.
Rachel says, “What’s gotten into you? I’m not bossing you around.” The expression “What’s gotten (gotten) into you” is an informal expression in English meaning “Why are you so different?” It’s a question used to express your surprise at how another person seems to have changed. You don’t understand why. Perhaps the other person is saying things that you think are strange or unusual, or at least not typical of that person’s normal behavior.
Rachel says she’s not bossing Logan around; she’s trying to help him. Then she says, “Some people are so ungrateful.” “To be grateful” (grateful) means to be thankful, to appreciate what another person has done. So, “to be ungrateful” means to be not thankful, not to appreciate what another person has done. Logan says, “It’s true that I’ve made my share of mistakes, but I don’t need you here to push me around calling all the shots.”
The expression “my share (share) of” something refers to your experience with something or of something. “I’ve had my share of good times and bad times,” meaning I’ve had a certain amount of good times and bad times – I’ve had a lot of those experiences, perhaps. Logan also says that he doesn’t need Rachel “to push him around.” “To push someone around” is another two-word phrasal verb that means the same as to boss someone around, to control another person.
He says he doesn’t need Rachel to push him around by “calling all the shots.” The expression “to call all the shots” (shots) means to make all of the important decisions without letting other people have a say or influence the decisions. Rachel responds by saying, “Here’s a reality check.” A “reality (reality) check (check)” is an opportunity to think about what you are saying or what you believe compared to what is really happening. People use this expression when they are trying to say to another person, “You are not realistic” or “You don’t really understand what’s going on here, so I’m going to tell you.”
Rachel says, “Without me keeping an eye on you and steering you away from bad decisions, you’d be back in trouble again.” Rachel is telling Logan that he needs her “to keep an eye on” him. “To keep an eye on” someone is to watch someone, especially to make sure that person doesn’t do anything wrong, or if we’re talking about a young child, to make sure the child doesn’t hurt himself.
Sometimes we use this expression just to mean “Watch my things so no one steals them.” If you’re at a cafe and you need to go to the restroom and want to leave your computer on your table, you may ask another person, whom often you don’t even know, “to keep an eye on your stuff,” on your things, while you go to the bathroom. People do this all the time, trusting that just because the other person is sitting there at a table next to you, he won’t steal your things.
Rachel also says that she needs “to steer” Logan “away from bad decisions.” “To steer” (steer) here means simply to guide, to make sure someone is moving in the right direction. We also use this verb when talking about a car. We “steer” the car when we move the wheel, the round thing called a “steering wheel,” in one direction or another. You are making sure the car is moving in the right direction or the direction you want to go. Rachel says she needs to steer Logan away from bad decisions. That means she is there to prevent him from making a bad decision.
Logan, however, says, “When I asked for your help, I’d forgotten how pushy and controlling you are.” “To be pushy” (pushy) is the same as to be bossy. It can also simply refer to someone who is very insistent, who doesn’t give up, who is constantly trying to get his way by asking perhaps again and again and again. “To be controlling” means to not let other people make decisions or to try to make decisions for other people. Logan says, “I’m not going to let you walk all over me.” “To walk all over” someone is an expression meaning to control another person completely, perhaps by making all of the decisions for that person.
Rachel says, “Who is trying to walk all over you? If you think I’m being high-handed then I’m out of here.” “To be high (high) – handed (handed)” means to use your power and control over another person without considering that person’s feelings or reactions. The expression “I’m out of here” is an informal one meaning “I’m leaving” or “I’m no longer going to be involved in this situation.” Sometimes it just means “I’m leaving immediately,” but often it is used in the sense of “I’m unhappy with this situation, and therefore I am leaving right now.”
Rachel says, “I’m out of here,” and Logan says, “Good. I don’t know what possessed me to ask you for help in the first place.” The expression “I don’t know what possessed me” is used when a person regrets his decision to do something – when a person decides that what they decided to do before was wrong. We use it in a situation when we’ve changed our minds and are saying that we don’t even understand why we thought differently before. The expression “in the first place” can mean simply originally or in the first instance – at the beginning of a situation.
Rachel says, “Well, things never change, do they?” Rachel and Logan are siblings – brother and sister – and Logan thinks that Rachel is acting just like she did when they were younger, when they were children. That’s why Rachel says, “Things never change, do they?” and Logan responds, “Apparently not!” “Apparently” means seemingly, or it appears to be true.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Rachel: What you need to do is . . .
Logan: Stop bossing me around! I know what I’m doing so back off.
Rachel: What’s gotten into you? I’m not bossing you around. I’m trying to help you. Some people are so ungrateful.
Logan: It’s true that I’ve made my share of mistakes, but I don’t need you here to push me around calling all the shots.
Rachel: Here’s a reality check: Without me keeping an eye on you and steering you away from bad decisions, you’d be back in trouble again.
Logan: When I asked for your help, I’d forgotten how pushy and controlling you are. I’m not going to let you walk all over me like you did when we were kids.
Rachel: Who is trying to walk all over you? If you think I’m being high-handed then I’m out of here.
Logan: Good. I don’t know what possessed me to ask you for help in the first place.
Rachel: Well, things never change, do they?
Logan: Apparently not!
[end of dialogue]
We are very grateful to our scriptwriter, Dr. Lucy Tse, for her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to boss (someone) around – to be bossy; to tell another person what to do and try to control that person, especially when one does not really have the authority to do so
* Why do you let your girlfriend boss you around and tell you how to dress?
to back off – to become less aggressive or assertive; to weaken one’s position or influence; to not try to have so much control
* I wish the manager would back off and let us make some of the decisions.
What’s gotten into you? – a phrase used when one is surprised by another person’s words, actions, or behavior, and wants to understand why the other person is speaking or acting in those ways
* What’s gotten into you? Why are you acting so strangely?
ungrateful – not feeling thankful; not appreciating what one has or what another person has done for oneself
* Please write thank-you notes for all the gifts you received. If you don’t, people might think you’re ungrateful.
(one’s) share of – a phrase used to show that one has experience with something; the amount of something that one is entitled to, or the amount that it is fair for one to have
* I’ve experienced my share of heartbreak, but I’ve always recovered and been able to start a new relationship when the time is right.
to push (someone) around – to be very bossy and controlling, trying to make another person do a certain thing or act a certain way
* The new vice-president is trying to push everyone around, and the employees are really upset about it.
to call all the shots – to make all the important decisions without letting other people have influence or share their opinions
* You just graduated last year. Did you really think you’d be able to call all the shots during your first few months in the job?
reality check – an opportunity to consider how one’s thoughts, opinions, and beliefs match with what is really happening
* Jake thought his employer was underpaying him, but interviewing for other jobs was a good reality check and he finally realized that his salary was fair.
to keep an eye on (someone) – to watch or observe someone closely, especially trying to see when that person does something wrong
* I think Randall might be stealing from the store. We need to keep an eye on him for the next few weeks.
to steer – to guide; to try to change the direction of something or to try to change someone’s behavior or perspective
* They’re trying to steer their daughter toward a career in engineering.
pushy – bossy and insistent, not giving up, and trying to control other people
* The bride’s mother became very pushy, wanting to select the music, the flowers, and even the wedding dress!
controlling – not letting other people have any power or make any decisions; wanting to have all the power and control for oneself
* Oleg is a very controlling father who demands to know where his children are and what they are doing at all times.
to walk all over (someone) – to have too much power, control, and influence over another person; to make decisions for another person
* Howard is letting the new investors walk all over him.
high-handed – using power and control over another person without asking about that person’s feelings or reactions
* Don’t be too high-handed with the employees or they’ll resent it.
out of here – leaving, especially leaving an organization as one quits one’s job; no longer involved or interested in something
* Start acting in a way that is more respectful toward me, or I’m out of here!
to not know what possessed (one) to do (something) – to not understand why one made a particular decision or why one acted in a particular way
* We don’t know what possessed Jeremiah to shout at his co-workers.
in the first place – a phrase used when talking about what one wishes one had done differently at the beginning of a situation
* If you aren’t going to take my advice, what ask for my opinion in the first place?
apparently – seemingly; appearing to be true, but without proof or evidence
* I thought I was ready for the test, but apparently I wasn’t. I wasn’t able to answer very many of the questions.
Comprehension Questions
1. What does Logan mean when he tells Rachel to “back off”?
a) He wants her to step backward and not be so close.
b) He wants her to be less demanding and controlling.
c) He wants her to lower her volume and speak more gently.
2. What does Logan mean when he says, “I’ve made my share of mistakes”?
a) The mistakes he has made have not affected other people.
b) The mistakes he has made are often made by many people.
c) He has made a lot of mistakes.
Answers at bottom.
What Else Does It Mean?
back off
The phrase “to back off,” in this podcast, means to become less aggressive or assertive, to weaken one’s position or influence, or to not try to have so much control: “We’ve been trying really hard to make the sale, but now it’s time to back off and let the client decide what to do.” The phrase “to back away” means to slowly move backward away from something because one is afraid of it: “If you see a bear in the forest, slowly back away.” Finally, the phrase “to back out” means to change one’s mind and no longer want to do or participate in something: “They made an offer to buy a house, but the very next day, they backed out.”
in the first place
In this podcast, the phrase “in the first place” is used when talking about what one wishes one had done differently at the beginning of a situation: “If you aren’t attracted to Faith, why did you ask her out in the first place?” The phrase “all over the place” means very disorganized or disordered: “Look at this kitchen! There is sugar and flour all over the place.” Or, “It was a terrible presentation. The speaker was all over the place.” The phrase “to fall into place” means for things to fit together or for plans to work out: “We weren’t sure we could get all sides to agree to a meeting, but plans are finally falling into place.” “Falling into place” can also mean for something to suddenly make sense: “Biochemistry was really hard at first, but as I continued to study, the concepts began to fall into place.”
Culture Note
U.S. Federal Observances
Most Americans celebrate a “standard” (not changing) set of holidays, such as New Year’s Day, Memorial Day, Labor Day, Independence Day, Thanksgiving, and Christmas. But there are many unusual or “lesser-known” (not known by many people) “federal observances,” or special days that have been declared by Congress or the U.S. President as days to remember or honor someone or something. “Federal employees” (people who work for the U.S. government) don’t receive a “day off of work” (a day when they do not have to work) for observances, and many people are unaware that the federal observances exist, but it’s interesting to consider the “range” (variety) of events and ideas they “cover” (are about).
Some of the federal observances are “patriotic” (showing love and respect for one’s country). These include Constitution Day and Citizenship Day on September 17, Flag Day on June 14, National Freedom Day on February 1, and Patriot Day on September 11. “Collectively” (taken or considered together), the 21 days between Flag Day (June 14) and Independence Day (July 4) are known as “Honor America Days.”
Other federal observances are “declared” (stated and made) for weeks or months rather than individual days. Many months are designated for honoring “cultural heritage” (the traditions of the places where one’s ancestors came from: February is Black History Month, October is Filipino American History Month, and November is Native American Heritage Month. Other months “draw attention to” (help people focus on) health-related issues: February is American Heart Month, April is Cancer Control Month, and October is Breast Cancer Awareness Month.
Comprehension Answers
1 - b
2 - c