
=  0074. Why China’s economy won’t be fixed
:toc: left
:toclevels: 3
:sectnums:

'''


== Why China’s economy won’t be fixed 为什么中国经济无法修复 (2023.8.26)


==== 困境状况

Having produced just a tenth as much as America in 1980, China’s economy is now about three-quarters the size.


[.my1]
.案例
====

1980年，中国的经济总量仅为美国的十分之一，而现在的经济规模约为美国的四分之三。
====


Slowing growth has also been accompanied 与…相伴 by *declining 下降，衰退 prices* and a weaker currency.

Many worry that China faces “Japanification 日本化”—a combination of debt, deflation 通货紧缩 and *demographic 人口的，人口统计的 decline* —in the long term and a “Lehman moment” in the more immediate future, as *defaults  违约 cascade* 小瀑布,倾泻；流注 through the shadow-banking system.


And, unlike Japan, China is also suffering from something more profound 巨大的；深切的；深远的 than *weak demand* and *heavy debt*. Many of its challenges stem from broader failures of its economic policymaking—which are getting worse as President Xi Jinping centralises power.




[.my1]
.案例
====

增长放缓, 还伴随着价格下降, 和货币贬值。

许多人担心，从长远来看，中国将面临“日本化”——债务、通货紧缩和人口下降的结合——以及在不久的将来随着影子银行体系的违约蔓延, 而面临“雷曼时刻”。

与日本不同的是，中国还面临着比需求疲软和债务沉重更严重的问题。它的许多挑战源于其经济政策制定的更广泛的失败——随着习近平主席的集权，这种失败变得更加严重。
====



`主` Consumer spending, business investment and exports `谓` have all *fallen short* 未达到预期目标或期望.


[.my1]
.案例
====

消费者支出、商业投资和出口均低于预期。
====



==== 商业投资

In the 2010s, every time the economy wobbled (v.)（使）摇摆，摇晃, officials defied (v.)违抗；反抗,经受住；顶住；抗住 predictions of calamity (n.)灾难；灾祸 by cheapening  使贬值；贬低 credit, building (v.) infrastructure or stimulating the property market. During each episode, however, public and private debts mounted (v.)逐步增加,登上；爬上. So did doubts (n.)疑惑；疑问 about *the sustainability 可持续性 of the housing boom* and *whether new infrastructure was really needed*. Wisely, they do not want more *white elephants*  昂贵而无用之物 or to reflate (v.)使（通货）再膨胀 the property bubble.


[.my1]
.案例
====
.calamity
(n.) an event that causes great damage to people's lives, property, etc. 灾难；灾祸 +
->  助记窍门：calamity→克拉玛依city→1994年新疆克拉玛依市大火灾→灾祸


2010年代，每当经济出现波动时，官员们都会通过降低信贷价格、建设基础设施, 或刺激房地产市场, 来无视灾难的预测。然而，在每一次事件中，公共和私人债务都在增加。人们对房地产繁荣的可持续性, 以及是否真的需要新基础设施的怀疑, 也随之增加。明智的是，他们不希望出现更多白象, 或加剧房地产泡沫。
====




Given the drop in inflation 通货膨胀 in recent months, real interest rates are rising.

鉴于近几个月通胀下降，实际利率正在上升。

Policymakers are not even willing to cut interest rates much. On August 21st they disappointed investors with an underwhelming 未给人留下深刻印象的 cut of 0.1 percentage points in the one-year *lending rate* 贷款利率.

政策制定者甚至不愿意大幅降息。8 月 21 日，他们将一年期贷款利率下调了 0.1 个百分点，令投资者感到失望。


Foreign direct investment 直接投资 *all but* 几乎, 差不多, 几近 vanished in the second quarter, falling by 87% year-on-year 与上年同期数字相比的 to $4.9bn, as multinationals 跨国公司 repatriated (v.)遣送回国；遣返;寄（钱）回国；将（利润）调回本国 their earnings *rather than* reinvesting (v.) them.


[.my1]
.案例
====

.repatriate
-> re-,向后，往回，-pater,父亲，词源同 father,compatriot.比喻用法。

由于跨国公司将收益汇回国内, 而不是进行再投资，第二季度外国直接投资几乎消失，同比下降 87%，至 49 亿美元。
====



==== 出口


==== 消费者支出




Households may be despondent (a.)沮丧的；泄气的；失望的 because employment 工作；职业；受雇 is insecure 不安全的；无保障的；不牢靠的, wages are stagnant (a.)停滞的；不发展的；无变化的;（水或空气）不流动而污浊的 and assets, especially houses, are losing (v.) value.


[.my1]
.案例
====

家庭可能会因为就业不稳定、工资停滞不前, 以及资产（尤其是房屋）贬值, 而感到沮丧。
====


Weak spending on *consumer durables* 耐用品；非消耗性用品 may also reflect property-market woes (n.)痛苦；苦恼,麻烦；问题, which have depressed furniture 家具 and white-goods sales. The renewed (a.)再次发生的 weakness in China’s property market has certainly contributed to fears of deflation 通货紧缩 and default  违约（尤指未偿付债务）.

The price of *building materials* 建筑材料 fell by 5.6% in July *compared with* a year earlier, and the price of *household appliances* （家用）电器，器具 fell by 1.8%.


[.my1]
.案例
====

耐用消费品支出疲软, 也可能反映出房地产市场的困境，房地产市场的困境, 导致家具和白色家电的销售下降。 +
中国房地产市场再度疲软, 无疑加剧了人们对通货紧缩和违约的担忧。7月份建筑材料价格同比下降5.6%，家用电器价格下降1.8%。
====






Nor can they do enough of the more desirable 可取的；值得拥有的；值得做的 kinds of stimulus (n.)促进因素；激励因素；刺激物, such as *pension 养老金；退休金 spending* and handouts 捐赠品；救济品 to poor households to boost (v.) consumption, because Mr Xi has disavowed 不承认；否认；拒绝对…承担责任 “welfarism 福利主义” and the government seeks (v.) an official deficit 赤字；逆差；亏损 of only 3% of GDP.


[.my1]
.案例
====

他们(指政府)也无法采取足够的更理想的刺激措施，例如养老金支出, 和向贫困家庭发放补贴以刺激消费，因为习近平否认“福利主义”，而且政府寻求将官方赤字, 仅占GDP的3% 。
====

Should China *fall into* persistent 执著的；不屈不挠的 deflation 通货紧缩 because the authorities *refuse to* boost consumption, *debts will rise* in real value and *weigh 有…重；重 more heavily* on the economy.


[.my1]
.案例
====

如果中国因当局拒绝刺激消费, 而陷入持续通货紧缩，债务的实际价值将会上升，并对经济造成更大压力。
====



==== 集权带来僵化


Why does the government keep making mistakes? One reason is that short-term growth is no longer the priority 优先事项；最重要的事 of the Chinese Communist Party (CCP). The signs are that Mr Xi believes China must prepare for sustained 持续的，持久 economic and, potentially, *military conflict* with America. He is willing *to make material sacrifices(n.)* to achieve (v.) those goals, and *to the extent* he wants growth, it must be “high quality”.


[.my1]
.案例
====

为什么政府总是犯错误？原因之一是短期增长不再是中国共产党的首要任务。有迹象表明，习认为中国必须为与美国持续的经济冲突以及潜在的军事冲突做好准备。他愿意为实现这些目标做出物质牺牲，而且他想要的增长程度必须是“高质量”。
====

Decisions are increasingly governed 控制；影响；支配 by an ideology 思想（体系）；思想意识,意识形态 that *fuses* (v.)（使）融合，熔接，结合 a left-wing suspicion 猜疑；怀疑 of rich entrepreneurs *with* a right-wing reluctance (n.)不情愿，勉强 *to hand (v.)交；递；给 money to* the idle 懈怠的；懒惰的,没有工作的；闲散的 poor.


[.my1]
.案例
====

决策越来越受到一种意识形态的支配，这种意识形态融合了左翼对富有企业家的怀疑, 和右翼不愿将钱交给无所事事的穷人的观点。
====


In the 2000s Western leaders mistakenly believed that trade, markets and growth would boost democracy and individual liberty. But China is now testing the reverse relationship: whether more autocracy 独裁政体；专制制度 damages (v.) the economy. The evidence is mounting that it does.


[.my1]
.案例
====

2000 年代，西方领导人错误地认为贸易、市场和增长将促进民主和个人自由。但中国现在正在测试相反的关系：更多的独裁是否会损害经济。越来越多的证据表明事实确实如此.
====


The population is ageing (v.) rapidly. America is increasingly hostile (a.) 敌意的；敌对的, and is trying to choke (v.)（使）窒息，哽噎;（掐住喉咙）使停止呼吸，使窒息 the parts of China’s economy, like chipmaking, that it sees as strategically significant 有重大意义的；显著的. The more China *catches up with* America, the harder the gap will be to close further, because centralised 集中的；中央集权的 economies are better at emulation 模仿 than at innovation.


[.my1]
.案例
====

人口正在迅速老龄化。美国的敌意日益浓厚，并试图扼杀中国经济中具有战略意义的部分，例如芯片制造。中国越是追赶美国，进一步缩小差距就越困难，因为中央集权经济体更擅长模仿, 而不是创新。
====


==== What China’s economic troubles mean for the world 中国的经济困境对世界意味着什么


Commodity 商品 exporters are especially exposed to China’s slowdown (n.)减速；减缓. The country guzzles (v.)暴饮；狼吞虎咽 almost a fifth of the world’s oil, half of its refined 精炼的；提纯的 copper, nickel and zinc, and more than three-fifths of its iron 铁 ore  矿石；矿砂. China’s property woes (n.)麻烦；问题；困难 will mean it requires less of such supplies. That will be a knock 敲；击 for countries such as Zambia, where exports of copper and other metals to China *amount (v.)总计；共计 to* 20% of GDP, and Australia, a big supplier of coal and iron.


[.my1]
.案例
====
大宗商品出口商尤其容易受到中国经济放缓的影响。该国消耗了世界近五分之一的石油，一半的精炼铜、镍和锌，以及五分之三以上的铁矿石。中国的房地产困境将意味着其对此类供应的需求减少。这将对赞比亚和澳大利亚等国家造成打击，赞比亚向中国出口的铜和其他金属, 占国内生产总值的20% ，而澳大利亚则是煤炭和铁的主要供应国。
====

And some Western companies are exposed through 凭借；因为；由于 their reliance on China for revenues 财政收入；税收收入；收益. In 2021 the 200 biggest multinationals in America, Europe and Japan made 13% of their sales in the country, earning $700bn. Tesla is more exposed still （加强比较级）还要，更, making around a fifth of its sales in China; Qualcomm, a chipmaker, makes a staggering (a.)令人难以相信的 two-thirds.


Sales to China *account (v.) for*  (数量、比例上) 占 only 4-8% of business for all *listed 上市的 companies* in America, Europe and Japan. Exports 出口 from America, Britain, France and Spain come to 1-2% of their respective outputs. Even in Germany, with an export share of nearly 4%, China would have to collapse *in order to* generate a sizeable 相当大的 hit (n.) to its economy.


[.my1]
.案例
====

一些西方公司因收入依赖中国而面临风险。2021年，美国、欧洲和日本最大的200家跨国公司13%的销售额来自中国，收入达7000亿美元。特斯拉面临的风险更大，其销量的约五分之一来自中国；芯片制造商高通的收入达到惊人的三分之二。

在美国、欧洲和日本的所有上市公司中，对中国的销售仅占其业务的4-8%。美国、英国、法国和西班牙的出口占各自产量的1-2%。即使在出口份额接近 4% 的德国，中国也必须崩溃才能对其经济造成相当大的打击。
====





'''

== Why China’s economy won’t be fixed


==== 困境状况

Having produced just a tenth as much as America in 1980, China’s economy is now about three-quarters the size.


Slowing growth has also been accompanied by declining prices and a weaker currency.




Many worry that China faces “Japanification”—a combination of debt, deflation and demographic decline—in the long term and a “Lehman moment” in the more immediate future, as defaults cascade through the shadow-banking system.

And, unlike Japan, China is also suffering from something more profound than weak demand and heavy debt. Many of its challenges stem from broader failures of its economic policymaking—which are getting worse as President Xi Jinping centralises power.




Consumer spending, business investment and exports have all fallen short.





==== 商业投资

In the 2010s, every time the economy wobbled, officials defied predictions of calamity by cheapening credit, building infrastructure or stimulating the property market. During each episode, however, public and private debts mounted. So did doubts about the sustainability of the housing boom and whether new infrastructure was really needed. Wisely, they do not want more white elephants or to reflate the property bubble.



Given the drop in inflation in recent months, real interest rates are rising.


Policymakers are not even willing to cut interest rates much. On August 21st they disappointed investors with an underwhelming cut of 0.1 percentage points in the one-year lending rate.

Foreign direct investment all but vanished in the second quarter, falling by 87% year-on-year to $4.9bn, as multinationals repatriated their earnings rather than reinvesting them.



==== 出口


==== 消费者支出




Households may be despondent because employment is insecure, wages are stagnant and assets, especially houses, are losing value.


Weak spending on consumer durables may also reflect property-market woes, which have depressed furniture and white-goods sales. The renewed weakness in China’s property market has certainly contributed to fears of deflation and default.

The price of building materials fell by 5.6% in July compared with a year earlier, and the price of household appliances fell by 1.8%.







Nor can they do enough of the more desirable kinds of stimulus, such as pension spending and handouts to poor households to boost consumption, because Mr Xi has disavowed “welfarism” and the government seeks an official deficit of only 3% of GDP.


Should China fall into persistent deflation because the authorities refuse to boost consumption, debts will rise in real value and weigh more heavily on the economy.



==== 集权带来僵化


Why does the government keep making mistakes? One reason is that short-term growth is no longer the priority of the Chinese Communist Party (CCP). The signs are that Mr Xi believes China must prepare for sustained economic and, potentially, military conflict with America. He is willing to make material sacrifices to achieve those goals, and to the extent he wants growth, it must be “high quality”.


Decisions are increasingly governed by an ideology that fuses a left-wing suspicion of rich entrepreneurs with a right-wing reluctance to hand money to the idle poor.


In the 2000s Western leaders mistakenly believed that trade, markets and growth would boost democracy and individual liberty. But China is now testing the reverse relationship: whether more autocracy damages the economy. The evidence is mounting that it does.


The population is ageing rapidly. America is increasingly hostile, and is trying to choke the parts of China’s economy, like chipmaking, that it sees as strategically significant. The more China catches up with America, the harder the gap will be to close further, because centralised economies are better at emulation than at innovation.



==== What China’s economic troubles mean for the world


Commodity exporters are especially exposed to China’s slowdown. The country guzzles almost a fifth of the world’s oil, half of its refined copper, nickel and zinc, and more than three-fifths of its iron ore. China’s property woes will mean it requires less of such supplies. That will be a knock for countries such as Zambia, where exports of copper and other metals to China amount to 20% of GDP, and Australia, a big supplier of coal and iron.

And some Western companies are exposed through their reliance on China for revenues. In 2021 the 200 biggest multinationals in America, Europe and Japan made 13% of their sales in the country, earning $700bn. Tesla is more exposed still, making around a fifth of its sales in China; Qualcomm, a chipmaker, makes a staggering two-thirds.

Sales to China account for only 4-8% of business for all listed companies in America, Europe and Japan. Exports from America, Britain, France and Spain come to 1-2% of their respective outputs. Even in Germany, with an export share of nearly 4%, China would have to collapse in order to generate a sizeable hit to its economy.





'''

