
=  0075. Scientists Raise Questions about Future Vaccine Strategy
科学家对未来疫苗策略提出疑问
:toc: left
:toclevels: 3
:sectnums:

'''

==  Scientists Raise Questions about Future Vaccine Strategy 科学家对未来疫苗策略提出疑问


Mutations change (v.) the appearance of the spike 尖状物；尖头；尖刺 protein 蛋白质 that covers the coronavirus. That is why Omicron was able to break through that first defense.

Thankfully, a part of the immune system called T cells helps *prevent* an infection *from* turning into severe illness. `主` The protection T cells offer `谓` lasts (v.) longer because T cells recognize other parts of the virus that do not mutate as easily.


[.my1]
.案例
====

突变改变了覆盖冠状病毒的刺突蛋白的外观。这就是 Omicron 能够突破第一道防线的原因。

值得庆幸的是，免疫系统的一部分称为 T 细胞，有助于防止感染演变成严重疾病。 T 细胞提供的保护持续时间更长，因为 T 细胞可以识别病毒中不易突变的其他部分。
====


'''


== Scientists Raise Questions about Future Vaccine Strategy

Mutations change the appearance of the spike protein that covers the coronavirus. That is why Omicron was able to break through that first defense.

Thankfully, a part of the immune system called T cells helps prevent an infection from turning into severe illness. The protection T cells offer lasts longer because T cells recognize other parts of the virus that do not mutate as easily.

'''
