
=  0076.  Long Periods in Space Can Shrink the Heart
研究：长时间在太空中会使心脏收缩
:toc: left
:toclevels: 3
:sectnums:

'''

== Long Periods in Space Can Shrink the Heart 研究：长时间在太空中会使心脏收缩

during Kelly’s stay in space, the left ventricle 心室,（体内的）室，腔 of his heart shrank (v.) about 0.74 grams per week.

Reductions 减少；缩小；降低 in heart size are also seen in patients who spend long periods in bed because they are lying flat and the heart does not have to work as hard to pump.


凯利在太空停留期间，他的左心室每周收缩约0.74克。 +
长时间卧床的患者, 也会出现心脏体积缩小的情况，因为他们平躺着，心脏不需要那么努力地跳动。



even extremely long periods of low-intensity exercise did not keep the heart muscle from shrinking.

A second part of the study examined data from a long-distance swimmer who spent nearly a year trying to cross the Pacific Ocean.

long-distance swimming has similar effects to weightlessness 失重；无重状态 because water pressure works (v.) against the force of gravity. The study showed that during Lecomte’s swim, his left heart ventricle shrank about 0.72 grams per week.

both Kelly and Lecomte had nearly the same heart shrinkage level even though Lecomte exercised much more, swimming an average of six hours a day. Kelly spent one to two hours a day exercising in space.

即使是极长时间的低强度运动, 也无法阻止心肌收缩.

该研究的第二部分检查了一名长距离游泳运动员(勒孔特)的数据，该运动员花了近一年的时间试图穿越太平洋。 +
长距离游泳与失重有类似的效果，因为水压与重力相反。研究表明，勒孔特游泳期间，他的左心室每周收缩约0.72克。

尽管勒孔特锻炼得更多，平均每天游泳六个小时，但凯利和勒孔特的心脏收缩水平几乎相同。凯利每天花一到两个小时在太空锻炼。


endurance  忍耐力；耐久力 swimming is not considered a “high-intensity” exercise. So the health benefits from swimming were likely outweighed
(在重要性或意义上) 超过；比 (某人) 重 by the heart not having to work as hard to pump blood uphill (ad.)向山上；朝上坡方向.

耐力游泳不被视为“高强度”运动。因此，游泳对健康的好处, 可能会被心脏不必费力地将血液泵上山所带来的好处所抵消。

'''

== Long Periods in Space Can Shrink the Heart

during Kelly’s stay in space, the left ventricle of his heart shrank about 0.74 grams per week.

Reductions in heart size are also seen in patients who spend long periods in bed because they are lying flat and the heart does not have to work as hard to pump.





even extremely long periods of low-intensity exercise did not keep the heart muscle from shrinking.

A second part of the study examined data from a long-distance swimmer who spent nearly a year trying to cross the Pacific Ocean.

long-distance swimming has similar effects to weightlessness because water pressure works against the force of gravity. The study showed that during Lecomte’s swim, his left heart ventricle shrank about 0.72 grams per week.

both Kelly and Lecomte had nearly the same heart shrinkage level even though Lecomte exercised much more, swimming an average of six hours a day. Kelly spent one to two hours a day exercising in space.



endurance swimming is not considered a “high-intensity” exercise. So the health benefits from swimming were likely outweighed by the heart not having to work as hard to pump blood uphill.


'''
