
= Stuffy Noses Are Miserable. These Nasal Congestion Treatments Actually Work 鼻塞是痛苦的。这些鼻塞治疗实际上有效
:toc: left
:toclevels: 3
:sectnums:

'''

== Stuffy Noses Are Miserable. These Nasal Congestion Treatments Actually Work 鼻塞是痛苦的。这些鼻塞治疗实际上有效

*Stuffy (a.) 闷热的；闷人的；通风不畅的 Noses* Are Miserable 痛苦的；非常难受的；可怜的,使难受的. These *Nasal 鼻的；与鼻子相关的 Congestion  （交通）拥塞；塞车; 充血；淤血 Treatments* Actually Work (v.)  鼻塞很痛苦。这些鼻塞治疗实际上有效

*Respiratory (a.) 呼吸的 illness* season is here, and *with it* typically comes (v.)  *snotty (a.)流鼻涕的；满是鼻涕的, stuffy (a.)  noses*. +
呼吸系统疾病季节来了，随之而来的通常是流鼻涕、鼻塞。 +

.title
====
.snotty
--> snot,鼻涕，-y,形容词后缀。来自辅音丛 sn-,鼻子，闻，嗅，发鼻音，比较 sneer,snore,snicker,sniff,snuff.引申词义鼻涕。
====

Earlier this fall a Food and Drug Administration panel concluded that oral phenylephrine—a common active ingredient in cold and allergy medicines—is useless at clearing up congestion. +
今年秋天早些时候，美国食品和药物管理局的一个小组得出结论，口服去氧肾上腺素 - 感冒和过敏药物中的常见活性成分 - 对清除充血毫无用处。 +


Lane treats nose and sinus problems and studies how the specialized cells lining the nasal cavity and sinuses participate in the body’s immune response—and can contribute to chronic inflammation. +
Lane治疗鼻子和鼻窦问题，并研究鼻腔和鼻窦内的特殊细胞如何参与人体的免疫反应，并可能导致慢性炎症。 +

He talked with Scientific American about what causes nasal congestion, as well as what treatments work and why. +
他与《科学美国人》讨论了导致鼻塞的原因，以及哪些治疗方法有效以及为什么有效。 +
 +

What is nasal congestion? +
什么是鼻塞？ +


Basically, congestion is the swelling of the mucous membranes that line the nose. +
基本上，充血是鼻子内衬粘膜的肿胀。 +


These mucous membranes help to warm and humidify the air we inhale. +
这些粘膜有助于加热和加湿我们吸入的空气。 +

The nose is constantly sensing the environment and changing how much air is let through and how much moisture should be added. +
鼻子不断感知环境，改变让多少空气通过以及应该添加多少水分。 +

It does that primarily by dilating or expanding the blood vessels beneath the mucous membranes, which makes the tissue swell. +
它主要通过扩张或扩张粘膜下方的血管来做到这一点，从而使组织肿胀。 +


There’s also swelling that occurs from inflammation as the immune system responds to triggers in the environment. +
当免疫系统对环境中的触发因素做出反应时，炎症也会引起肿胀。 +

For example, when you have an infection, your body needs to bring inflammatory cells to that tissue to fight it off. +
例如，当您感染时，您的身体需要将炎症细胞带到该组织以抵抗它。 +

The blood vessels swell and become sort of leaky, leading to fluid buildup in the tissue. +
血管肿胀并变得有点渗漏，导致组织中积液。 +

You might also notice your nose looks red when you are congested—the redness comes in part from these swollen and inflamed blood vessels. +
您可能还会注意到，当您充血时，您的鼻子看起来会发红——发红部分来自这些肿胀和发炎的血管。 +


So nasal congestion is not caused by the buildup of mucus but is more about swelling and inflammation? +
所以鼻塞不是由粘液堆积引起的，而更多的是由肿胀和炎症引起的？ +


They do go a little bit hand in hand because mucus helps to moisten the air [before it reaches the lungs], and you typically have more mucus production when there’s inflammation. +
它们确实有点齐头并进，因为粘液有助于滋润空气[在空气到达肺部之前]，而且当有炎症时，您通常会产生更多的粘液。 +

But I think of the congestion being more from the stuffiness caused by the swelling of the mucous membranes than from the mucus itself. +
但我认为充血更多的是来自粘膜肿胀引起的闷热，而不是粘液本身。 +


What triggers nasal congestion? +
什么会引发鼻塞？ +

The most common causes of nasal congestion are allergies and viral infections, such as those that cause the cold or flu. +
鼻塞的最常见原因是过敏和病毒感染，例如引起感冒或流感的病毒感染。 +

There’s also a form of congestion that has to do with position, where people might complain of being stuffy in one nostril after lying on their side. +
还有一种与体位有关的充血形式，人们可能会抱怨侧卧后一个鼻孔闷闷不乐。 +

And then there’s congestion that comes from irritants in the environment [such as perfume or smoke]. +
然后是来自环境中刺激物（如香水或烟雾）的拥堵。 +
 +
Pseudoephedrine is an excellent decongestant that has been around for a long time. +
伪麻黄碱是一种极好的减充血剂，已经存在了很长时间。 +

It works by constricting the blood vessels, so it counteracts the stuffiness caused by the dilation of vessels that I talked about earlier. +
它通过收缩血管起作用，因此可以抵消我之前谈到的血管扩张引起的闷热。 +

[Because pseudoephedrine is chemically related to the stimulant amphetamine], people started making crystal meth out of it, and it was taken off the shelves and put behind the pharmacy counter. +
[因为伪麻黄碱在化学上与兴奋剂苯丙胺有关]，人们开始用它制造冰毒，它被从货架上取下来，放在药房柜台后面。 +

That made the medication harder to access, so some people turned to another oral decongestant, phenylephrine. +
这使得药物更难获得，因此有些人转向另一种口服减充血剂去氧肾上腺素。 +

Unlike pseudoephedrine, which can raise blood pressure and make people feel a little hyped up, phenylephrine has fewer side effects—which makes sense because it basically has no effects at all, as the FDA panel recently concluded. +
与伪麻黄碱不同，伪麻黄碱会升高血压并让人感到有点兴奋，去氧肾上腺素的副作用较少——这是有道理的，因为它基本上没有任何影响，正如 FDA 小组最近得出的结论。 +

[The panel’s] decision hasn’t changed how we treat nasal congestion because those of us who prescribe these medications know oral phenylephrine never really worked. +
[小组的]决定并没有改变我们治疗鼻塞的方式，因为我们这些开这些药物的人知道口服去氧肾上腺素从未真正起作用。 +
 +

Phenylephrine does work when it is delivered directly to the nose as a spray, however, as does another decongestant called oxymetazoline. +
然而，去氧肾上腺素作为喷雾剂直接输送到鼻子时确实有效，另一种称为羟甲唑啉的减充血剂也是如此。 +

[The latter is] very strong and fast-acting. +
[后者]非常强大和快速。 +

You should only use these sprays for three days, though—any longer and you risk making things worse. +
但是，您应该只使用这些喷雾剂三天——再长一点，你就有可能让事情变得更糟。 +

These medications act on adrenergic receptors on the blood vessels that line the nose’s mucous membranes. +
这些药物作用于鼻粘膜血管上的肾上腺素能受体。 +

If you take the spray around the clock for many days in a row, those receptors get overstimulated and become resistant to the medication. +
如果您连续多天昼夜不停地服用喷雾剂，这些受体会受到过度刺激并对药物产生抗药性。 +

The effects last less and less, and people keep using it more and more frequently, until they feel like they can’t breathe without it. +
效果持续时间越来越短，人们越来越频繁地使用它，直到他们觉得没有它就无法呼吸。 +

We call that rhinitis medicamentosa, or rebound congestion. +
我们称之为药物性鼻炎，或反弹性充血。 +
 +
What about nasal steroid sprays? +
鼻腔类固醇喷雾剂怎么样？ +
 +
That’s the long game. +
这是一场漫长的比赛。 +

If you have allergies, then nasal steroid sprays such as fluticasone can help if you use them consistently over a longer period. +
如果您有过敏症，那么如果您长期坚持使用氟替卡松等鼻腔类固醇喷雾剂会有所帮助。 +

Steroid sprays work to reduce inflammation, so they’re not working directly on blood vessel constriction. +
类固醇喷雾剂可以减少炎症，因此它们不会直接作用于血管收缩。 +

In that same vein, if your congestion is caused by an allergy, there are other options, such as antihistamine pills and sprays, that aren’t necessarily going to work if your symptoms are instead caused by a cold. +
同样，如果您的鼻塞是由过敏引起的，还有其他选择，例如抗组胺药和喷雾剂，如果您的症状是由感冒引起的，则不一定有效。 +


Are there other types of remedies that are effective—such as saline solutions, hot showers, chest rubs or even a comforting bowl of chicken noodle soup? +
有没有其他类型的补救措施是有效的，例如生理盐水、热水淋浴、胸部按摩，甚至是一碗令人欣慰的鸡肉面条汤？ +


Saline rinses, which involve moving saltwater through your nasal passages, can be helpful because they can hydrate the nose and eliminate irritants that might be driving inflammation. +
盐水漱口水涉及将盐水通过鼻腔，可能会有所帮助，因为它们可以滋润鼻子并消除可能引发炎症的刺激物。 +

There are good data to show that symptoms are improved with nasal saline. +
有很好的数据表明，鼻腔盐水可以改善症状。 +

You can deliver saline using a nasal spray, squeeze bottle or neti pot. +
您可以使用鼻腔喷雾剂、挤压瓶或洗鼻壶输送生理盐水。 +
 +
Another popular remedy involves steam. +
另一种流行的补救措施涉及蒸汽。 +

I was taught that steam is perfect for your nose because it’s already warm and moist, so your nose can relax. +
我被告知蒸汽非常适合您的鼻子，因为它已经温暖潮湿，因此您的鼻子可以放松。 +

But I’ve also seen studies showing that cool air helps open the nose. +
但我也看到研究表明，冷空气有助于打开鼻子。 +

There seem to be mixed data, and it depends on the circumstances. +
似乎有好坏参半的数据，这取决于具体情况。 +

Temperature and ambient humidity seem to impact how congested some people are or at least how congested they feel. +
温度和环境湿度似乎会影响一些人的拥挤程度，或者至少会影响他们感到的拥挤程度。 +

A hot shower or a bowl of hot soup can create steam, and I think that could act like a decongestant. +
洗个热水澡或一碗热汤可以产生蒸汽，我认为这可以起到减充血剂的作用。 +


Menthol [an ingredient in Vicks VapoRub, Tiger Balm and other chest rubs] is an interesting one. +
薄荷醇 [Vicks VapoRub、Tiger Balm 和其他胸部摩擦剂中的一种成分] 是一个有趣的。 +

It does absolutely nothing to any of the objective measures of nasal airflow, but it does improve subjective ones. +
它对鼻腔气流的任何客观测量都没有任何作用，但它确实改善了主观测量。 +

That’s because the nose has temperature-sensitive sensors inside that can detect air movement: menthol tricks the nose into thinking there’s a lot of airflow because it creates a cooling sensation, even when there’s absolutely no difference in airflow. +
这是因为鼻子内部有温度敏感传感器，可以检测空气流动：薄荷醇会欺骗鼻子认为有很多气流，因为它会产生凉爽的感觉，即使气流完全没有差异。 +

A bunch of aromatic compounds such as eucalyptus and spearmint have a similar effect. +
一堆芳香化合物，如桉树和留兰香，也有类似的效果。 +
 +
Another factor that can affect nasal congestion is posture. +
另一个可能影响鼻塞的因素是姿势。 +

Your nose will be more congested when you lie down because blood pools in those vessels in the nasal structures and the mucosae [mucous membranes]. +
当您躺下时，您的鼻子会更加充血，因为血液会积聚在鼻结构和粘膜 [粘膜] 的这些血管中。 +

If you sleep with your head elevated on a pillow, you’ll probably have less congestion. +
如果你把头抬高在枕头上睡觉，你的拥堵可能会减少。 +

It’s just gravity, right? If you twisted your ankle, you would want to prop it up to decrease swelling. +
这只是重力，对吧？如果你扭伤了脚踝，你会想把它支撑起来以减少肿胀。 +

Keeping your head up above the level of your heart is going to make your nose less inflamed and less swollen. +
将头抬高到心脏水平以上会让你的鼻子不那么发炎和肿胀。 +


Do you have any parting advice for people suffering from nasal congestion? +
对于鼻塞患者，您有什么临别建议吗？ +


You’re just trying to relieve your symptoms while you wait for the congestion to run its course. +
你只是想在等待拥堵结束的同时缓解你的症状。 +

Start with things that are least likely to cause side effects, such as saline or chicken soup. +
从最不可能引起副作用的东西开始，例如生理盐水或鸡汤。 +

There are over-the-counter medications that are effective and generally safe, but some people do experience side effects. +
有些非处方药是有效的，而且通常是安全的，但有些人确实会出现副作用。 +

If you take a medication once, and it makes you feel sleepy or jittery, just don’t take it again. +
如果您服用过一次药物，并且它使您感到困倦或紧张，请不要再服用。 +


Nasal congestion only gets concerning if it becomes a persistent problem. +
鼻塞只有在成为一个持续存在的问题时才会引起关注。 +

In that case, you want to rule out other causes such as nasal polyps or tumors, and you might need a surgical procedure to open the nasal passages. +
在这种情况下，您需要排除其他原因，例如鼻息肉或肿瘤，您可能需要外科手术来打开鼻腔通道。 +

Not everything is just allergies or a cold, so if it doesn’t really fit that picture, see a doctor. +
并非一切都只是过敏或感冒，所以如果它真的不符合那张照片，请去看医生。















'''

== Stuffy Noses Are Miserable. These Nasal Congestion Treatments Actually Work

Respiratory illness season is here, and with it typically comes snotty, stuffy noses. Earlier this fall a Food and Drug Administration panel concluded that oral phenylephrine—a common active ingredient in cold and allergy medicines—is useless at clearing up congestion.

Lane treats nose and sinus problems and studies how the specialized cells lining the nasal cavity and sinuses participate in the body’s immune response—and can contribute to chronic inflammation. He talked with Scientific American about what causes nasal congestion, as well as what treatments work and why.

What is nasal congestion?

Basically, congestion is the swelling of the mucous membranes that line the nose.

These mucous membranes help to warm and humidify the air we inhale. The nose is constantly sensing the environment and changing how much air is let through and how much moisture should be added. It does that primarily by dilating or expanding the blood vessels beneath the mucous membranes, which makes the tissue swell.


There’s also swelling that occurs from inflammation as the immune system responds to triggers in the environment. For example, when you have an infection, your body needs to bring inflammatory cells to that tissue to fight it off. The blood vessels swell and become sort of leaky, leading to fluid buildup in the tissue. You might also notice your nose looks red when you are congested—the redness comes in part from these swollen and inflamed blood vessels.


So nasal congestion is not caused by the buildup of mucus but is more about swelling and inflammation?


They do go a little bit hand in hand because mucus helps to moisten the air [before it reaches the lungs], and you typically have more mucus production when there’s inflammation. But I think of the congestion being more from the stuffiness caused by the swelling of the mucous membranes than from the mucus itself.

What triggers nasal congestion?

The most common causes of nasal congestion are allergies and viral infections, such as those that cause the cold or flu. There’s also a form of congestion that has to do with position, where people might complain of being stuffy in one nostril after lying on their side. And then there’s congestion that comes from irritants in the environment [such as perfume or smoke].



Pseudoephedrine is an excellent decongestant that has been around for a long time. It works by constricting the blood vessels, so it counteracts the stuffiness caused by the dilation of vessels that I talked about earlier. [Because pseudoephedrine is chemically related to the stimulant amphetamine], people started making crystal meth out of it, and it was taken off the shelves and put behind the pharmacy counter. That made the medication harder to access, so some people turned to another oral decongestant, phenylephrine. Unlike pseudoephedrine, which can raise blood pressure and make people feel a little hyped up, phenylephrine has fewer side effects—which makes sense because it basically has no effects at all, as the FDA panel recently concluded. [The panel’s] decision hasn’t changed how we treat nasal congestion because those of us who prescribe these medications know oral phenylephrine never really worked.


Phenylephrine does work when it is delivered directly to the nose as a spray, however, as does another decongestant called oxymetazoline. [The latter is] very strong and fast-acting. You should only use these sprays for three days, though—any longer and you risk making things worse. These medications act on adrenergic receptors on the blood vessels that line the nose’s mucous membranes. If you take the spray around the clock for many days in a row, those receptors get overstimulated and become resistant to the medication. The effects last less and less, and people keep using it more and more frequently, until they feel like they can’t breathe without it. We call that rhinitis medicamentosa, or rebound congestion.

What about nasal steroid sprays?

That’s the long game. If you have allergies, then nasal steroid sprays such as fluticasone can help if you use them consistently over a longer period. Steroid sprays work to reduce inflammation, so they’re not working directly on blood vessel constriction. In that same vein, if your congestion is caused by an allergy, there are other options, such as antihistamine pills and sprays, that aren’t necessarily going to work if your symptoms are instead caused by a cold.

Are there other types of remedies that are effective—such as saline solutions, hot showers, chest rubs or even a comforting bowl of chicken noodle soup?

Saline rinses, which involve moving saltwater through your nasal passages, can be helpful because they can hydrate the nose and eliminate irritants that might be driving inflammation. There are good data to show that symptoms are improved with nasal saline. You can deliver saline using a nasal spray, squeeze bottle or neti pot.

Another popular remedy involves steam. I was taught that steam is perfect for your nose because it’s already warm and moist, so your nose can relax. But I’ve also seen studies showing that cool air helps open the nose. There seem to be mixed data, and it depends on the circumstances. Temperature and ambient humidity seem to impact how congested some people are or at least how congested they feel. A hot shower or a bowl of hot soup can create steam, and I think that could act like a decongestant.

Menthol [an ingredient in Vicks VapoRub, Tiger Balm and other chest rubs] is an interesting one. It does absolutely nothing to any of the objective measures of nasal airflow, but it does improve subjective ones. That’s because the nose has temperature-sensitive sensors inside that can detect air movement: menthol tricks the nose into thinking there’s a lot of airflow because it creates a cooling sensation, even when there’s absolutely no difference in airflow. A bunch of aromatic compounds such as eucalyptus and spearmint have a similar effect.

Another factor that can affect nasal congestion is posture. Your nose will be more congested when you lie down because blood pools in those vessels in the nasal structures and the mucosae [mucous membranes]. If you sleep with your head elevated on a pillow, you’ll probably have less congestion. It’s just gravity, right? If you twisted your ankle, you would want to prop it up to decrease swelling. Keeping your head up above the level of your heart is going to make your nose less inflamed and less swollen.

Do you have any parting advice for people suffering from nasal congestion?

You’re just trying to relieve your symptoms while you wait for the congestion to run its course. Start with things that are least likely to cause side effects, such as saline or chicken soup. There are over-the-counter medications that are effective and generally safe, but some people do experience side effects. If you take a medication once, and it makes you feel sleepy or jittery, just don’t take it again.


Nasal congestion only gets concerning if it becomes a persistent problem. In that case, you want to rule out other causes such as nasal polyps or tumors, and you might need a surgical procedure to open the nasal passages. Not everything is just allergies or a cold, so if it doesn’t really fit that picture, see a doctor.




'''



