
= The Flu Vaccine Works--In a Way Most People Don't Appreciate 流感疫苗的作用——但大多数人不理解
:toc: left
:toclevels: 3
:sectnums:

'''

== The Flu Vaccine Works—​In a Way Most People Don’t Appreciate 流感疫苗的作用——以大多数人不理解的方式 +

We tend to take kind of a black-and-white approach to vaccines of ‘if you get vaccinated, it will keep you from getting that particular disease. +
我们倾向于对疫苗采取一种非黑即白的方法，“如果你接种了疫苗，它就会阻止你患上那种特定的疾病”。 +

The pro is that it’s a very simple message; the con is that it doesn’t necessarily communicate the reality of vaccines, which is that sometimes you do get that disease even though you’re vaccinated. +
优点是这是一条非常简单的消息；缺点是它不一定传达疫苗的真实情况，即有时即使您接种了疫苗，您也会患上这种疾病。 +

The amount of protection a vaccine offers depends on the disease it targets. +
疫苗提供的保护程度取决于其针对的疾病。 +

For some shots, such as those for measles and polio, the black-and-white approach is essentially true. +
对于某些镜头，例如麻疹和脊髓灰质炎的镜头，黑白方法本质上是正确的。 +

If you received the standard vaccine regimen as a child, your odds of ever catching those particular diseases are tiny: around 1 percent for each. +
如果您小时候接受了标准疫苗接种，那么您感染这些特定疾病的几率很小：每种疾病的几率约为 1%。 +

But flu doesn’t work the same way. +
但流感的作用却不同。 +

Measles and polio are static viruses, whereas influenza mutates regularly, allowing it to evade our immune system even if it’s been trained to identify the pathogen via prior infection or vaccination. +
麻疹和脊髓灰质炎是静态病毒，而流感会定期变异，使其能够逃避我们的免疫系统，即使它已经通过先前的感染或疫苗接种接受过识别病原体的训练。 +

In addition, influenza is a family of viruses, and typically the flu vaccine administered in the U.S. targets only four strains. +
此外，流感是一个病毒家族，通常在美国接种的流感疫苗, 只针对四种病毒。 +

These strains are selected based on the ones that are circulating in the Southern Hemisphere more than six months before flu season begins in the North. +
这些毒株是根据北半球流感季节开始前六个月在南半球流行的毒株选择的。 +

Selecting which strains to target is a guessing game—one that scientists can’t always win. +
选择目标菌株是一场猜谜游戏，科学家们并不总是能赢。 +

These factors give the influenza vaccine a spotty record in preventing disease. +
这些因素导致流感疫苗在预防疾病方面的记录参差不齐。 +

During well-matched seasons, we see [risk reduction] numbers pretty consistently within the range of 40 to 60 percent among the vaccinated. +
在匹配良好的季节中，我们看到接种疫苗的人的[风险降低]数字始终保持在 40% 至 60% 的范围内。 +

The perceived “low” protection can cause people to hesitate about receiving the vaccine. +
被认为“低”的保护作用可能会导致人们对接种疫苗犹豫不决。 +

People think that if they get vaccinated, and then they get sick, the vaccine has failed. +
人们认为，如果他们接种了疫苗，然后生病了，那么疫苗就失效了。 +

But that’s not an accurate view of what public health experts expect the flu vaccine to accomplish. +
但这并不是公共卫生专家对流感疫苗预期效果的准确看法。 +

Mild influenza occurs mostly in the respiratory tract, where vaccine-induced defenses aren’t as effective because they can’t reach the surface of the mucus membranes in, for example, your nose. +
轻度流感主要发生在呼吸道，疫苗诱导的防御作用并不那么有效，因为它们无法到达鼻子等粘膜表面。 +

That’s where the virus might first enter your body and cause flu’s mild symptoms, such as a runny nose—so vaccination doesn’t do much against these infections. +
这是病毒可能首先进入您的身体并引起流感轻微症状的地方，例如流鼻涕，因此疫苗接种对这些感染没有多大作用。 +

Instead the vaccine produces defenses that are active deeper in the body—in the heart, liver and kidney, for example—and can stop the virus from sneaking into organs, where it can cause a severe to possibly life-threatening infection. +
相反，疫苗产生的防御作用在身体更深处（例如心脏、肝脏和肾脏）活跃，并且可以阻止病毒潜入器官，从而导致严重甚至可能危及生命的感染。 +

For the flu, vaccination isn’t about reducing infections overall but instead about reducing the hundreds of thousands of hospitalizations and tens of thousands of deaths the disease causes in the U.S. each year. +
对于流感来说，疫苗接种并不是为了减少总体感染，而是为了减少该疾病每年在美国造成的数十万人住院和数万人死亡。



'''


== The Flu Vaccine Works--In a Way Most People Don't Appreciate


We tend to take kind of a black-and-white approach to vaccines of ‘if you get vaccinated, it will keep you from getting that particular disease. The pro is that it’s a very simple message; the con is that it doesn’t necessarily communicate the reality of vaccines, which is that sometimes you do get that disease even though you’re vaccinated.

The amount of protection a vaccine offers depends on the disease it targets. For some shots, such as those for measles and polio, the black-and-white approach is essentially true. If you received the standard vaccine regimen as a child, your odds of ever catching those particular diseases are tiny: around 1 percent for each.

But flu doesn’t work the same way. Measles and polio are static viruses, whereas influenza mutates regularly, allowing it to evade our immune system even if it’s been trained to identify the pathogen via prior infection or vaccination. In addition, influenza is a family of viruses, and typically the flu vaccine administered in the U.S. targets only four strains. These strains are selected based on the ones that are circulating in the Southern Hemisphere more than six months before flu season begins in the North. Selecting which strains to target is a guessing game—one that scientists can’t always win.

These factors give the influenza vaccine a spotty record in preventing disease. During well-matched seasons, we see [risk reduction] numbers pretty consistently within the range of 40 to 60 percent among the vaccinated.

The perceived “low” protection can cause people to hesitate about receiving the vaccine. People think that if they get vaccinated, and then they get sick, the vaccine has failed.

But that’s not an accurate view of what public health experts expect the flu vaccine to accomplish. Mild influenza occurs mostly in the respiratory tract, where vaccine-induced defenses aren’t as effective because they can’t reach the surface of the mucus membranes in, for example, your nose. That’s where the virus might first enter your body and cause flu’s mild symptoms, such as a runny nose—so vaccination doesn’t do much against these infections.


Instead the vaccine produces defenses that are active deeper in the body—in the heart, liver and kidney, for example—and can stop the virus from sneaking into organs, where it can cause a severe to possibly life-threatening infection. For the flu, vaccination isn’t about reducing infections overall but instead about reducing the hundreds of thousands of hospitalizations and tens of thousands of deaths the disease causes in the U.S. each year.

'''







