
= Artificial Womb Trials in Humans Could Start Soon 人类人工子宫试验即将开始
:toc: left
:toclevels: 3
:sectnums:

'''


== Artificial Womb Trials in Humans Could Start Soon 人类人工子宫试验即将开始 +

The team has emphasized that the technology is not intended — or able — to support development from conception to birth. +
该团队强调，该技术无意或无法支持从受孕到出生的发育。 +

Instead, the scientists hope that simulating some elements of a natural womb will increase survival and improve outcomes for extremely premature babies. +
相反，科学家们希望模拟自然子宫的某些元素能够提高极早产儿的存活率并改善其结局。 +

In humans, that’s anything earlier than 28 weeks of gestation — less than 70% of the way to full term, which is typically between 37 and 40 weeks. +
对于人类来说，这是指妊娠 28 周之前的任何时间，不到足月的 70%，足月通常在 37 至 40 周之间。 +
 +

Preterm birth, defined by the World Health Organization as birth before 37 weeks of gestation, can happen spontaneously or because some conditions — such as an infection, hormone imbalance, high blood pressure or diabetes — can turn the womb into an inhospitable environment for the fetus. +
世界卫生组织将早产定义为妊娠 37 周之前的出生，可能是自发发生，也可能是因为某些情况（例如感染、激素失衡、高血压或糖尿病）可能使子宫变成不适合胎儿生存的环境。 。 +

It poses an enormous global health problem. +
它造成了巨大的全球健康问题。 +

Preterm birth is the largest cause of death and disability in children under five. +
早产是五岁以下儿童死亡和残疾的最大原因。 +

Mortality is strongly linked with the baby’s gestational age at birth. +
死亡率与婴儿出生时的胎龄密切相关。 +

At or before 22 weeks — considered the cusp of fetal viability — few fetuses survive outside the womb. +
在 22 周或之前（被认为是胎儿生存能力的关键时期），很少有胎儿能在子宫外存活。 +

By 28 weeks, most can survive, but often require significant life support. +
到 28 周时，大多数人都可以存活，但通常需要大量的生命支持。 +

Artificial-womb technology aims to improve outcomes for preterm babies who are born in the period between 22 and 28 weeks, for whom survival has improved, but long-term health issues are frequent. +
人工子宫技术旨在改善 22 至 28 周内出生的早产儿的结局，这些早产儿的生存率有所提高，但长期健康问题也很常见。 +

In a study of 2.5 million people in Sweden, for example, 78% of people born before 28 weeks of gestation had some sort of medical condition — ranging from asthma and hypertension to cerebral palsy and epilepsy — by the time they were adults. +
例如，一项针对瑞典 250 万人的研究显示，78% 妊娠 28 周之前出生的人在成年时患有某种疾病，包括哮喘、高血压、脑瘫和癫痫等。 +

For full-term births, that rate was 37%. +
对于足月出生，这一比例为 37%。 +

Death and disability, especially in babies born at younger gestational ages, often occur because the lungs and brain are among the last organs to fully mature in humans. +
死亡和残疾，特别是在胎龄较小的婴儿中，经常发生，因为肺和大脑是人类最后完全成熟的器官之一。 +

That’s why obstetricians try to prevent preterm birth whenever possible — the longer fetuses can safely stay in the womb, the higher their odds are of long-term survival and good health. +
这就是为什么产科医生尽可能地预防早产——胎儿在子宫内安全停留的时间越长，长期存活和健康的几率就越高。 +
 +

In a natural womb, a fetus receives oxygen, nutrients, antibodies and hormonal signals and gets rid of waste through the placenta, a transient organ in which fetal blood interacts with maternal blood. +
在自然子宫中，胎儿接收氧气、营养物质、抗体和激素信号，并通过胎盘排出废物，胎盘是胎儿血液与母体血液相互作用的短暂器官。 +

Of these various roles, artificial-womb technology is most focused on providing oxygen and removing carbon dioxide, replacing the mechanical ventilators that are often used for neonates. +
在这些不同的作用中，人工子宫技术最关注的是提供氧气和去除二氧化碳，取代通常用于新生儿的机械呼吸机。 +

These can damage fragile developing lungs that would otherwise still be filled with amniotic fluid. +
这些会损害脆弱的发育中的肺部，否则肺部仍会充满羊水。

'''


== Artificial Womb Trials in Humans Could Start Soon


The team has emphasized that the technology is not intended — or able — to support development from conception to birth. Instead, the scientists hope that simulating some elements of a natural womb will increase survival and improve outcomes for extremely premature babies. In humans, that’s anything earlier than 28 weeks of gestation — less than 70% of the way to full term, which is typically between 37 and 40 weeks.

Preterm birth, defined by the World Health Organization as birth before 37 weeks of gestation, can happen spontaneously or because some conditions — such as an infection, hormone imbalance, high blood pressure or diabetes — can turn the womb into an inhospitable environment for the fetus.

It poses an enormous global health problem. Preterm birth is the largest cause of death and disability in children under five.

Mortality is strongly linked with the baby’s gestational age at birth. At or before 22 weeks — considered the cusp of fetal viability — few fetuses survive outside the womb. By 28 weeks, most can survive, but often require significant life support. Artificial-womb technology aims to improve outcomes for preterm babies who are born in the period between 22 and 28 weeks, for whom survival has improved, but long-term health issues are frequent.

In a study of 2.5 million people in Sweden, for example, 78% of people born before 28 weeks of gestation had some sort of medical condition — ranging from asthma and hypertension to cerebral palsy and epilepsy — by the time they were adults. For full-term births, that rate was 37%.

Death and disability, especially in babies born at younger gestational ages, often occur because the lungs and brain are among the last organs to fully mature in humans. That’s why obstetricians try to prevent preterm birth whenever possible — the longer fetuses can safely stay in the womb, the higher their odds are of long-term survival and good health.

In a natural womb, a fetus receives oxygen, nutrients, antibodies and hormonal signals and gets rid of waste through the placenta, a transient organ in which fetal blood interacts with maternal blood. Of these various roles, artificial-womb technology is most focused on providing oxygen and removing carbon dioxide, replacing the mechanical ventilators that are often used for neonates. These can damage fragile developing lungs that would otherwise still be filled with amniotic fluid.


'''

