= 0855
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 855: Learning Fire Safety.
This is English as a Second Language Podcast episode 855. I’m your host, Dr. Jeff McQuillan, coming to you from beautiful Los Angeles, California and the Center for Educational Development.
ESLPod.com is our website. When you go there, you can become a member and download a Learning Guide for this episode. Do it today before you forget.
This episode is a story about learning fire safety – learning to make sure that you don’t accidentally cause a fire that will damage your house or building. Sounds like a good idea. Let’s get started!
[start of story]
The apartment manager asked all of the tenants to come to a short meeting to learn about fire safety. I didn’t want to go, but the manager said that there would be free food, and who am I to turn down free pizza?
...
Apartment manager: Thank you all for coming to this meeting about fire safety. With the rash of fires in this neighborhood recently, it seemed like a good idea to talk about fire safety with all of you.
I want to make sure we comply with the fire code, so I’ve installed new smoke alarms or replaced the batteries in the older ones in each apartment and in the hallways. The fire escapes are in good condition and there are fire extinguishers in each hallway.
Your job is to keep the inside of your apartments safe. Keep flammable items away from the fireplace and don’t overload your electrical outlets. Any questions? If not, we’re ready for a fire drill.
...
Nobody told me there would be fire drill. I’m guess I’m ready to stop, drop, and roll – as long as I can take the pizza with me.
[end of story]
Our story begins with me – the person telling the story – saying that “the apartment manager” – the person who takes care of the apartment where I live, in the story – “asked all of the tenants” – the people who rent apartments – “to come to a short meeting to learn about fire safety.” “Fire safety” are things you should do in order to prevent fires and to keep people safe if there is a fire. I say that “I didn’t want to go, but that the manager said that there would be free food, and who am I to turn down free pizza?” “To turn down” is a phrasal verb which, here, means to decide not to do something or not to have something, to say no to someone. “I asked a beautiful woman out on a date and she turned me down.” She said, “No, thank you, Jeff.” Well, this was many years ago, of course. I actually put this in the form of a question – “Who am I to turn down free pizza?” When we say, “Who am I to do something,” we’re kind of making a joke about it, saying, “Well, I’m not an important enough person to say no,” or “I have to do this,” or “I don’t have any right or any permission to do something differently.”
The apartment manager begins, then – and he sounds a lot like me – by saying, “Thank you all for coming to this meeting about fire safety. With the rash of fires in this neighborhood recently, it seemed like a good idea to talk about fire safety with all of you.” A “rash” (rash) is when something is very common – a short period of time, usually, when something bad is happening. If there were four people murdered in the last week, we could talk about a “rash of murders” here in Los Angeles. I’m not saying there were, maybe there were, but that would be an example. Or, “There have been a rash of cases involving people who are stealing cars.” Usually, the word “rash” is used when something bad happens. Well, this is a case where something bad is happening. There have been a rash of fires in the neighborhood.
The manager says that he wants to make sure we “comply” with the “fire code.” “To comply” (comply) means to follow the rules or to follow the laws, to do what you are supposed to do. The “fire code” are a series or a set of rules and regulations, or laws, established to protect people from fires. So, when you build a new building, or you build a house, you have to follow the rules to make sure that you’re not building something that could be dangerous. Those rules are called the “fire code (code).” The word “code” is often used to describe government regulations that you have to follow. And if you don’t follow them, you could be in trouble.
The manager says he’s “installed new smoke alarms.” “To install” (install) means to put something into place, often to attach it to something so that it can be used. “I’m going to install a new sink in my bathroom.” I’m going to put it in. I’m going to put it in place. We talk about, on our computers, “installing software.” We download it from the Internet or we buy it, and we put it on to our hard drive, our computer. That is also another use of the verb “install.” The manager has installed, or put in, new “smoke alarms.”
“Smoke” (smoke) is when something burns and it gives off a certain substance that floats in the air. If you breathe it, you will probably cough and it could kill you. “Smoke” happens when there is a fire. In fact, there’s an old expression “Where there’s smoke, there’s fire,” meaning if you see an indication of a problem, there probably is a real problem, maybe even more serious than you know. However, a “smoke alarm” is a device, a small instrument, that makes a noise when there is smoke in the room. Most houses have smoke alarms, at least a couple of them. “Smoke alarms” are required in public buildings.
Well, the apartment manager installed new smoke alarms or he replaced, or put in, batteries in the older ones. A “battery” (battery) is a small object that provides electricity to a machine. It can often be removed, unless you have certain kinds of phones where the battery can’t be removed, at least not by you. But most batteries are things you can take out and put new ones in or you can what we would call “recharge” them. You can give them more power, new power so that they will work again. The manager continues by saying that the “fire escapes” are in good condition. A “fire escape” (escape) is a way of leaving a building in the case of a fire. We often think about fire escapes as being stairs, metal stairs on the outside of a building, so that if you’re in a building, you can climb out the window, you can exit the building through the window, onto these stairs that area outside. We would call them “fire escapes.” A “fire escape” might also be a ladder that is put up on the side of a building or more typically, dropped down from the window. Those are examples of fire escapes.
The manager says, “The fire escapes in the apartment building are in good condition” – they’re working fine, no problems – “and there are fire extinguishers in each hallway.” An “extinguisher” is something that extinguishes. The verb “to extinguish” (extinguish) means to stop something, in this case, from burning, usually. A fire extinguisher is a metal container, a cylinder, often painted red or yellow, that has special chemicals in it that when you spray it on a fire, it will put the fire out. It will stop the fire. That’s a “fire extinguisher.”
The manager says the fire extinguishers are in each “hallway.” A “hallway” is a space that connects different rooms in a building or in a house, in this case, in the apartment building. The manager concludes by saying, “Your job” – meaning what the tenants, the renters are supposed to do – “is keep the inside of your apartments safe. Keep flammable objects away from the fireplace.” “Flammable” (flammable) is something that will burn easily. And if something burns easily, if it can “catch fire,” we might say, easily, you don’t want to put it near your fireplace where you might be burning wood to bring heat into your house.
Also, “Don’t overload your electrical outlets,” the manager says. “To overload” (overload) means to put too much pressure or to demand too much of something, or someone. In this case, it would be trying to plug in all of your electrical devices into one electrical circuit or even one plug, one outlet. This, in some cases, can be dangerous and can even start a fire. “Electrical outlets” (outlets) are the things that you plug your power cords into, what gives you electricity – we call those “outlets,” “electrical outlets.”
“Any questions?” the manager says. “If not, we’re ready for a fire drill.” A “fire drill” (drill) is an event where people in a building are asked to pretend – to imagine – that there is a fire, and practice leaving the building quickly and in an orderly way, usually going outside and all meeting in the same spot. “Fire drills” are things that typically happen in schools, especially the elementary and high schools. We would have a fire drill at least once, sometimes twice a year, where the fire bell would ring and everyone would have to stand up and walk out of the school in a calm and orderly way. That’s a “fire drill.” It’s something you don’t usually see in a building, an office building or a commercial building nowadays. But it is still quite common in schools, because we want to train students on what to do if there is a fire.
I end the story by saying, “Nobody told me that there would be a fire drill. I guess I’m ready to stop, drop, and roll as long as I can take the pizza with me.” “To stop, drop, and roll” is a common phrase used to remind people what they should do if they are in a building during a fire. You stop whatever you’re doing. You drop or fall down to the ground, and then you roll along the ground to move toward the exit while preventing or stopping your clothes from catching on fire – “Stop, drop, and roll.” That’s the recommended procedure. Most people, of course, use another procedure when a fire breaks out in their building, and that’s “Run like hell!” – which is a somewhat vulgar way of saying “Run really fast!”
Now let’s listen to the story this time, at a normal speed.
[start of story]
The apartment manager asked all of the tenants to come to a short meeting to learn about fire safety. I didn’t want to go, but the manager said that there would be free food, and who am I to turn down free pizza?
...
Apartment manager: Thank you all for coming to this meeting about fire safety. With the rash of fires in this neighborhood recently, it seemed like a good idea to talk about fire safety with all of you.
I want to make sure we comply with the fire code, so I’ve installed new smoke alarms or replaced the batteries in the older ones in each apartment and in the hallways. The fire escapes are in good condition and there are fire extinguishers in each hallway.
Your job is to keep the inside of your apartments safe. Keep flammable items away from the fireplace and don’t overload your electrical outlets. Any questions? If not, we’re ready for a fire drill.
...
Nobody told me there would be fire drill. I’m guess I’m ready to stop, drop, and roll – as long as I can take the pizza with me.
[end of story]
She never turns down a good idea for a script. I speak, of course, of our wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
fire safety – behaviors taught and learned to prevent fires and keep people safe during a fire
* The school promotes fire safety by teaching children that they should never play with matches.
to turn down – to reject; to decide not to have or do something; to say no to someone or something
* Why did you turn down the job offer?
rash – a period of time when something is very common; a period of time when something bad happens many times
* The police officer explained that there has been a rash of robberies in the neighborhood, and that we should make sure all doors and windows are locked.
to comply – to be in compliance; to follow the rules or laws; to do what one is supposed to do
* Employees who do not comply with our code of ethics may lose their job.
fire code – the set of rules, regulations, or laws established to protect people and property from fire, especially describing how buildings should be built
* The fire code clearly states that chimneys must have a minimum height above the roof.
to install – to put something into place or attach it to something else so that it can be used properly, especially when talking about an electronic device or machine
* Could you please help me install the new printer so it will work with my computer?
smoke alarm – a small device that makes a very loud noise when smoke is in the air, used to make people aware of fires in buildings
* The smoke alarm goes off almost every time Jacques cooks, because he always burns the food.
battery – a small object that provides electricity to a machine and can be removed to be recharged or replaced
* Is your watch broken, or does it just need a new battery?
fire escape – a route created to let people leave the building through an emergency exit when there is a fire
* All the apartment buildings are required to have fire escapes through at least one window on each floor.
fire extinguisher – a metal container, usually red or yellow, that can be used to spray special chemicals on a fire to make it stop burning
* If it’s just a small fire, try to use a fire extinguisher. But if it’s a bigger fire, leave the building and call the fire department.
flammable – able to burn easily; able to catch on fire easily
* Never put a child to sleep in flammable clothing.
to overload – to put too much pressure or demand on someone or something; to demand too much of someone or something
* Sheila has been feeling really overloaded at work lately. I think she needs to hire an assistant.
electrical outlet – a small hole in the wall used to connect electrical devices to the source of electricity
* Can little kids really get hurt if they put their fingers in an electrical outlet?
fire drill – an event where the people in a building are asked to pretend that there is a fire so that they can practice leaving the building quickly and gathering in a same spot nearby
* The school has a fire drill at least once each semester.
to stop, drop, and roll – a common phrase describing what one should do if one is in a building during a fire: stop whatever one was doing, drop or fall down to the ground, and roll along the ground to move toward the exit while preventing or stopping one’s clothes from burning
* A firefighter went to the local preschool to teach little kids how to stop, drop and roll.
Comprehension Questions
1. Why did he go to the meeting about fire safety?
a) Because he wanted to learn the latest fire code regulations.
b) Because he wanted to eat food for free.
c) Because he wanted to tell the apartment manager about his smoke alarm.
2. Which of these items would be good to have during a fire?
a) A fire extinguisher.
b) Flammable items.
c) Electrical outlets.
Answers at bottom.
What Else Does It Mean?
rash
The word “rash,” in this podcast, means a period of time when something is very common, or a period of time when something bad happens many times: “The TV reporter is talking about a rash of bank robberies in the southern part of town.” The word “rash” also describes a red, irritated, and often itchy spot on one’s skin, often caused by exposure to a substance: “That’s poison oak! If you touch it, you might get a painful rash.” Or, “I know this looks like a rash, but it’s really just a sunburn.” Finally, the phrase “diaper rash” describes the red spots or marks that appear on a baby’s bottom when he or she is left in a wet or dirty diaper for too long: “As soon as Dave started changing his son’s diaper more often, the diaper rash went away.”
overload
In this podcast, the verb “to overload” means to put too much pressure or demand on someone or something: “This house has really bad electrical wiring. If we turn on the lights and run the dishwasher, the washing machine, and a hair dryer at the same time, it overloads the circuits.” Or, “The poor horse was so overloaded with bags, boxes, and riders that it could hardly walk, much less run.” Finally, the phrase “information overload” describes the modern phenomenon in which people have access to too much information, especially due to the Internet, and feel very tired and become unable to make a decision: “The more time we spend researching potential solutions, the more likely we are to have information overload.”
Culture Note
Smokey the Bear
Smokey the Bear, sometimes called just Smokey Bear, is a symbol of fire prevention and a “mascot” (an animal or character representing a school or institution) of the U.S. Forest Service. Smokey first appeared in 1944 and appeared on many posters and promotional materials designed to prevent “forest fires” (uncontrolled fires burning through wild areas with many trees). His “slogan” (a phrase associated with a company or concept) is “Only you can prevent forest fires.”
The U.S. Forest Service used images of Smokey in many campaigns, but especially to teach children about how to keep forests safe and prevent forest fires. For example, “rangers” (people who work in forests and state or national parks, interacting with visitors) would use Smokey to teach “campers” (people who spend the night outdoors, usually in a tent) how to “put out” (extinguish; stop from burning) a campfire by “dousing it” (pouring water over it) or by using a “shovel” (a tool used for digging) to “smother it” (prevent air from reaching something) with dirt.
In recent years, the U.S. Forest Service has “de-emphasized” (reduced the focus on) Smokey, because our understanding of the “role” (what something does) of fires in forest ecosystems has changed. In the past, people thought that forest fires were always bad, but now forest scientists understand that fires help to minimize the “spread” (expansion) of disease and maintain “biodiversity” (a measure of the number of species and the number of individuals within each species). So Smokey is still used to talk about the importance of preventing “unintended” (accidental) fires, but Smokey no longer wants to prevent forest fires with “natural causes” (such as lightening) unless they “endanger” (put in danger) lives or property.
Comprehension Answers
1 - b
2 - a