= 0859
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 859: Attending an Ex’s Wedding.
This is English as a Second Language Podcast epsiode 859. I’m your host, Dr. Jeff McQuillan, coming to your from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. You know that, but did you also know that you can become a Learning Guide member and download? That’s right, a Learning Guide for this episode.
This episode is a dialog between Andy and Yuka about going to the wedding – the marriage ceremony – of someone who used to be your boyfriend or girlfriend. Sounds pretty interesting. Let’s get started.
[start of dialog]
Andy: What did you do last weekend?
Yuka: I went to Jamal’s wedding.
Andy: Jamal?! Your ex Jamal?
Yuka: Yes, that Jamal.
Andy: He had the nerve to invite you to his wedding?
Yuka: I actually thought it was nice of him to invite me. Whatever happened between us years ago is water under the bridge. There are no hard feelings on either side.
Andy: You told me that the breakup was mutual, but I always thought you still had a soft place in your heart for him.
Yuka: The truth is, when we first broke up, I did harbor some hopes of the two of us getting back together, but that never came to pass. We both moved on and I wish him well.
Andy: Well, how was the wedding?
Yuka: It was very nice and Jamal’s new wife seems to be a good match for him.
Andy: And you didn’t mind seeing them together?
Yuka: Not at all, especially after I met Lorenzo.
Andy: Lorenzo, huh? You’ve been holding out on me. Do tell!
[end of dialog]
Our dialog begins with Andy asking Yuka, “What did you do last weekend?” Yuka says, “I went to Jamal’s wedding.” A “wedding” is an official ceremony where two people promise to, well it depends on the people, but typically, they promise to be married to each other until they die. That doesn’t always happen. I understand. Yuka says that she went to Jamal’s wedding. Andy says, “Jamal?! Your ex Jamal?” “Ex” (ex) means my ex-boyfriend or my ex-girlfriend. It could also mean my ex-husband or my ex-wife. We just use the letters “ex” sometimes in informal conversation when we mean ex-boyfriend or ex-girlfriend. Here, it’s Yuka’s ex-boyfriend.
Yuka says, “Yes, that Jamal,” meaning that’s the Jamal I’m talking about. Andy is obviously surprised. Andy says, “He had the nerve to invite you to his wedding?” The expression “to have the nerve (nerve)” means to do something very surprising, very shocking, but also very rude, very unkind, and to do it without being sorry about it. We might also use the adjectives “bold” and “arrogant” when trying to define this expression. “You have the nerve to tell me that my hair looks bad, when you’re bald yourself” – when you don’t have any hair yourself? That’s what I said to somebody the other day. Well, Andy is surprised that Jamal had the nerve to invite Yuka to his wedding. “To invite” means to ask someone to participate or to come to some sort of event.
Yuka says, “I actually thought it was nice of him to invite me.” So, Yuka was happy that her ex invited her. “Whatever happened between us years ago is water under the bridge.” Yuka is saying that no matter what happened, even if bad things happened many years ago, that is now all “water under the bridge (bridge).” The expression “something is water under the bridge” means something happened a long time ago but it’s no longer important and I’ve sort of forgotten about it, really. It’s not something that bothers me anymore.
Maybe you and your brother had an argument and you’re mad at each other for many months or even years. And then, you decide to forgive your brother or he forgives you or you forgive each other, and you forget about that thing that happened. You say, “Oh, that’s water under the bridge.” You can think about a river, of course, full of water and the water is always moving past. So, when you look down it’s not the same water that you would’ve seen five seconds ago or five minutes or five days ago.
Yuka says “There are no hard feelings on either side.” “To have hard feelings” means to have anger or resentment about a situation or a person. “No hard feelings” means that you’re not thinking about how this other person acted, or whether they may have insulted or hurt you. “No hard feelings” means I’m not mad at you. “Please don’t be mad at me” could also be a way of interpreting that expression. Yuka says “There are no hard feelings on either side,” meaning neither she nor Jamal is angry at the other.
Andy says, “You told me that the breakup was mutual.” A “breakup” is when you end a romantic relationship, usually a boyfriend/girlfriend relationship. You could also use the term, however, for a marriage. “They broke up their marriage.” They ended their marriage. They got a divorce. So, breakup could be used in that case, too.
Andy says that Yuka told him that their breakup was mutual. Something that is “mutual” (mutual) is something done by two people. You both agree. “The feeling is mutual” is another expression we have. That means “I feel the same about that person as that person feels about me.” It could be a positive thing. It could be a negative thing. “Mutual” just means something done by two people or done at the same time. Andy is saying that although Yuka told him that their breakup was mutual, he always thought that Yuka still had a soft place in her heart for him.
“To have a soft place in your heart for someone” means, really, that you still have kind feelings toward someone, possibly even romantic feelings. It’s not always romantic. You could have a soft place in your heart for your nephew or for your grandmother, but it might be also romantic in some instances, when you’re talking, of course, about situations where that’s likely.
Andy then thought that Yuka may have still liked Jamal. Yuka says, “The truth is, when we first broke up, I did harbor some hopes of the two of us getting back together again.”
“To harbor” (harbor) means to continue to have hopes about something or fears about something. It could be a positive or a negative, but to keep those feelings a secret from other people. Yuka had these hopes right after Jamal and she first broke up, “But that never came to pass,” she says. For something to “come to pass” means for something to happen. “Never come to pass” means something did not happen, did not occur.
Yuka says that she and Jamal both moved on. “To move on” means to continue with your life, not to worry about some past event or not to let it affect your decisions about what you’re doing right now. When two people breakup in a romantic relationship, it’s usually better for both of them to move on, to find another boyfriend or another girlfriend, or a dog. Dogs sometimes can be much better companions, much better friends than a boyfriend or a girlfriend.
Well, Yuka says that she and Jamal moved on and that she wishes him well. “To wish someone well” means to hope that that person has a good life, to have good feelings towards that person, to want that person to be happy.
Andy says, “Well, how was the wedding?” Yuka said, “It was very nice and Jamal’s new wife seems to be a good match for him.” “To be a match” (match) here means to have some of the same characteristics, some of the same interests that the other person has or simply to be a good fit, to be two people that are good together, they’re good for each other. They’re a good match. Andy says, “And you didn’t mind seeing them together?” meaning “It didn’t bother you to see your ex-boyfriend with his new wife?” Yuka says, “Not at all, especially after I met Lorenzo.”
Now we find out why Yuka is not angry about going to Jamal’s wedding, because she has a new boyfriend named Lorenzo. In English, Lorenzo is “Lawrence,” which some of you may know is my middle name, but I am not dating Yuka. I want everyone to know that - especially my wife!
Andy says, “Lorenzo, huh? You’ve been holding out on me.” “To hold out on someone” is not to give that person all the information that you have, to keep some things secret, not to tell the person everything you know. Andy says, “Do tell.” This is a somewhat old-fashioned phrase, meaning that you want the other person to give you the information, the (usually) exciting or interesting news that they have to tell you. “Do tell” – “Please tell me” is what that expression means.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Andy: What did you do last weekend?
Yuka: I went to Jamal’s wedding.
Andy: Jamal?! Your ex Jamal?
Yuka: Yes, that Jamal.
Andy: He had the nerve to invite you to his wedding?
Yuka: I actually thought it was nice of him to invite me. Whatever happened between us years ago is water under the bridge. There are no hard feelings on either side.
Andy: You told me that the breakup was mutual, but I always thought you still had a soft place in your heart for him.
Yuka: The truth is, when we first broke up, I did harbor some hopes of the two of us getting back together, but that never came to pass. We both moved on and I wish him well.
Andy: Well, how was the wedding?
Yuka: It was very nice and Jamal’s new wife seems to be a good match for him.
Andy: And you didn’t mind seeing them together?
Yuka: Not at all, especially after I met Lorenzo.
Andy: Lorenzo, huh? You’ve been holding out on me. Do tell!
[end of dialog]
Our scriptwriter always wishes us well and the feeling is mutual.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, here on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
wedding – the ceremony that brings two people together in marriage
* Derek wants a small wedding, but his fiancée wants to invite hundreds of people.
ex – a former romantic partner; a person with whom one used to have a romantic relationship
* Frank never dates colleagues, because he doesn’t want to be in the position of working with an ex.
to have the nerve – to be very bold and arrogant; to do something that is shocking and rude, without being sorry about it
* I can’t believe Sheila had the nerve to ask me to pay for the meal after she was the one who suggested we go to such an expensive restaurant.
to invite – to ask someone to come to an event or to participate in something
* How many people are you inviting to the party?
water under the bridge – something that happened in the past and has been forgotten and no longer has any importance or influence
* When Bryan and Kai were younger, they fought a lot, but now those arguments are water under the bridge and they are best friends.
no hard feelings – without any anger or resentment; not holding a grudge; not spending a lot of time thinking about how another person hurt oneself or did something bad in the past
* I’m sorry I dated your sister without asking for your permission first. No hard feelings, okay?
breakup – the end of a romantic relationship; the moment when two people decide to stop dating each other
* A lot of people have horrible stories about breakups that happened via text messaging or email.
mutual – done by two people, usually at the same time; in the interest of two people; experienced by two people
* They shook hands as a sign of their mutual agreement and said they would put everything in a written contract on Monday.
to have a soft place in (one’s) heart for (someone) – to have sweet, kind, and possibly romantic feelings for another person; to like someone
* Peter has always had a soft spot in his heart for Mikayla. I wonder why he has never asked her out on a date.
to harbor – to continue to have hopes or fears, but keep them secret and hidden from other people
* How can he still be harboring anger over what happened four years ago?
to never come to pass – to not happen; to not occur
* Some economists are predicting an unemployment rate of 20%, but I hope that never comes to pass.
to move on – to continue with one’s life, no longer worrying about some past event or letting it affect one’s decisions and actions
* Janelle’s husband died 10 years ago, and she has finally decided that it’s time to move on and start dating again.
to wish (someone) well – to hope that one has a good life and finds peace and happiness; to have only good feelings toward another person
* We’re sad to see Kaitlynn leave the company, but we wish her well in her next job.
match – one half of a pair, sharing many characteristics or interests with the other person or thing; part of a set
* Do you think this skirt would be a good match for this sweater?
to hold out on (someone) – to not fully share all the available information with another person; to keep a secret, at least partially, and not tell everything to another person
* Did something happen at work today? It seems like you’re holding out on me.
do tell – a phrase used to ask someone to share information or to invite someone to speak, especially about very exciting or interesting news
* How was your date with Sarah? Do tell!
Comprehension Questions
1. What does Andy mean when he asks, “He had the nerve to invite you to his wedding?”
a) He thinks Jamal would be very nervous to invite Yuka.
b) He thinks Jamal’s invitation was inappropriate.
c) He thinks Jamal’s should have invited him, too.
2. What does Yuka say about Jamal’s new wife?
a) She seems to have a lot in common with Jamal.
b) She is very beautiful.
c) She is very kind and thoughtful.
Answers at bottom.
What Else Does It Mean?
to have the nerve
The phrase “to have the nerve,” in this podcast, means to be very bold and arrogant, or to do something that is shocking and rude, without being apologetic: “How could Lola have the nerve to tell me I don’t dress well enough, when she was wearing shorts in the office?” The phrase “to be a bundle of nerves” means to be very nervous and anxious about something: “Damian is always a bundle of nerves before his presentations.” The phrase “to steady (one’s) nerves” means to calm down and stop being so nervous: “Maybe taking a five minute break would help her steady her nerves.” Finally, the phrase “to lose (one’s) nerve” means to become very nervous or worried and lose confidence so that one is no longer able to do what one had planned to do: “Mike was going to ask Mariah to marry him, but then he lost his nerve.”
to harbor
In this podcast, the verb “to harbor” means to continue to have hopes or fears, but keep them secret and hidden from other people: “Are you still harboring hopes that someone will find your dog?” The verb “to harbor” can also mean to protect a criminal or someone else, giving him or her a safe place to stay: “This home harbored many slaves as they left the southern United States in search of freedom.” Sometimes “to harbor” means to have or contain something, especially if it cannot be seen and is dangerous: “Kitchen sponges often harbor germs, so it’s a good idea to replace them frequently.” Finally, as a noun, a “harbor” is an area of calm water in an ocean or sea, where ships are safe and able to avoid large waves: “As soon as they left the harbor, Jacques became seasick.”
Culture Note
Traditional Weddings
Wedding “receptions” (parties after the wedding ceremony) can be “elaborate” (with many parts or details) events, especially when they include all of the traditional “components” (parts).
Normally, there is a lot of music and dancing. Traditionally, the “bride” (the woman who has just been married) has the “first dance” (dancing to the first song played) with her father, and then with her “groom” (the man who has just been married).
The “newlyweds” (the two people who have just been married) usually hold a special knife together to cut the first “slice” (piece) of the cake. They feed the first bite to each other with their fingers, but many couples actually “smear” (put something down and move it to make a mark) over the bride’s or groom’s face as they feed it to each other, having fun by making a mess on each other’s faces. They also might drink their “champagne” (special white wine with bubbles) so that their arms wrap around each other as they each drink from a “champagne flute” (a long, narrow glass used for drinking champagne).
Later in the reception, the bride sometimes puts her right foot up on a chair and “raises” (moves higher) the “hem” (bottom sewn part) of her dress to “expose” (allow to be seen) much of her leg. The groom then removes a “garter” (a small piece of elastic worn around the “thigh” (upper part of the leg), traditionally used to hold up stockings). The groom throws the garter toward the “single” (not married) men and the bride throws her “bouquet” (a collection of flowers held in one’s hands) toward the single women. The man who catches the garter and the woman who catches the bouquet “are said to be” (are talked about as if they are) the next ones to marry.
Comprehension Answers
1 - b
2 - a