= 0861
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 861: Planning a Children’s Party.
This is English as a Second Language Podcast episode 861. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com Become a member of ESL Podcast, and download the Learning Guide for this episode.
This episode is a dialog between Sara and Paul, who are planning, who are getting ready for a party, for some children. Let’s get started.
[start of dialog]
Sara: Come on! We need to buy all of the things we need for Gabriel’s party before the store closes.
Paul: Are you sure we need a party? Maybe we can just have a cake and some party hats.
Sara: Are you kidding?! We are going to pull out all the stops. We’ll have streamers, balloons, noisemakers, and party favors. This is going to be really fun.
Paul: I don’t even know if he’d like all that. What are you doing?
Sara: I’m getting lots of confetti to throw when we sing “Happy Birthday.”
Paul: The confetti is going to get all over the ice cream and the icing on the cake. And it’ll be a nightmare to clean up.
Sara: Don’t worry about the clean up. I’ll take care of that. Now, where are the goodie bags...
Paul: Are you sure all of this is necessary?
Sara: Of course, it is. Ooo...What do you think of hiring a clown and renting an inflatable castle for the party?
Paul: You do remember that Gabriel is turning one, don’t you?
Sara: So?
...
It’s just as I suspected. Some birthday parties aren’t for the children. They’re for the adults who never grew up!
[end of dialog]
Sara says to Paul, “Come on.” “Come on” is an expression we use when you want someone to leave with you or you want them to perhaps work a little faster. Sara says, “Come on. We need to buy all of the things we need for Gabriel’s party before the store closes.” In this case, Sara wants Paul to leave with her, to go to a store so they can buy things for Gabriel’s party, whoever Gabriel is.
Paul says, “Are you sure we need a party? Maybe we can just have a cake and some party hats.” A “cake” (cake) is a type of dessert, a sweet bread-like dessert that you have at parties – birthday parties, graduation parties, parties for someone’s wedding – all of these would probably have some sort of cake involved. Paul says, “Maybe we can just have a cake and some party hats.” “Party hats” are colorful paper hats that you wear on your head, usually associated with parties for young children. Sara says, “Are you kidding?” meaning “Are you joking?” She’s surprised at what Paul is saying, and maybe a little angry.
She says, “We are going to pull out all the stops.” This expression, “to pull out all the stops” or “all of the stops,” means you’re going to do everything you possibly can. You’re not going to limit yourself in anyway. You’re going to do the most you can. The expression actually comes from playing the organ. “To pull out all the stops” is to make the organ play at its loudest possible volume, although I’m not a musician so don’t take my word for that. You may not want to believe what I say.
Sara says, “We’ll have streamers, balloons, noisemakers and party favors.” These are all things you might find at a children’s party or some other kind of party in some cases. “Streamers” (streamers) are long pieces of brightly colored paper that you hang on the wall or hang on doors or put on the windows. “Balloons” are small pieces of rubber that are filled with air and you can fill them with water if you want to have a water balloon fight, but I don’t think that’s what we’re talking about here. We’re talking about filling them with air in order to decorate or make a room look more festive, more like you’re having a party. “Noisemakers” are little devices that are used to make a lot of noise that you would find again at a children’s party because young children like to make a lot of noise. If you don’t believe me, just ask my neighbors. “Party favors” are little gifts that you give people for coming to your party. That’s a party “favor” (favor).
Sara says, “This is going to be really fun.” Paul says, “I don’t even know if he’d like all that.” He’s not even sure if Gabriel will like all of this planning – all of these things that Sara wants to do for the party. Paul then asks, “What are you doing?” Sara says, “I’m getting lots of confetti to throw when we sing happy birthday. “Confetti” (confetti) are small pieces of paper. They could be white, they could be colored, that are used often to throw at people in celebration. You will sometimes see confetti at someone’s wedding, as they’re coming out of the church. You can throw either rice or confetti. So, it’s an item that you would associate with a party. Paul says, “The confetti is going to get all over the ice cream and the icing on the cake.” Paul is complaining these little pieces of paper, if you throw them up into the air, will “get all over,” meaning they’ll get into, the ice cream. “Ice cream” is a sweet frozen dessert, usually made from milk and sugar, maybe fruit and other sweet things that you would like to eat. I remember when I was growing up, those one or two times that I had a birthday party, we would have chocolate ice cream and vanilla ice cream, which is a white-colored ice cream. Those were always the most popular flavors for ice cream at a party. Nowadays, they have ice cream in all different kinds of flavors, all different kinds of taste, but back in the old days, it was basically chocolate and vanilla ice cream.
Paul thinks the confetti will get all over the ice cream and the icing on the cake. When you have a cake, you usually put a thick colored substance made of butter or some other substance as decoration on top of the cake. So, the cake itself is baked in an oven and after you take it out of the oven and let it cool, you’ll put some sugary, buttery substance on the top of it that will make it even sweeter and that will give it some particular color. You can often write someone’s name in icing that goes on the cake for the birthday party. Paul says, “It’ll be a nightmare to cleanup.” A “nightmare” (nightmare) normally means a bad or scary, or frightening dream that you have, but in this case, it just means a very bad situation, a very bad experience. Sara says, “Don’t worry about the cleanup.” Don’t worry about cleaning up after the party.
Sara says, “Now where are the goodie bags.” “Goodie (goodie) bags (bags)” are little bags, kind of like party favors, that have little gifts for the people who come to the party. Once again, it’s something you would probably find more at a children’s party. When you have a birthday party for your son or daughter, and you invite other children to come, the children – even if it’s not their birthday – will also get a little gift from you, who is hosting or who is having the party.
Paul says, “Are you sure all of this is necessary?” Do we really need to do this? Sara says, “Of course it is. Ooo… What do you think of hiring a clown and renting an inflatable castle for the party?” A “clown” (clown) is a person who dresses in very brightly colored clothing, usually with big shoes and a red nose and tries to make people laugh. We associate clowns with children’s birthday parties. Some parents who have way too much money to spend will hire a clown to come to their child’s party in order to entertain the children, to get them to laugh, to have a good time.
An “inflatable castle” is something you used to only find at a big carnival or a big fair, a big celebration in your community or in your town. Nowadays, however, parents sometimes get inflatable castles for their child’s birthday. An “inflatable castle” is a large plastic structure in the shape of a castle. A “castle” is where a king or a queen would live, of a country, that’s filled with air so that children could go inside of this plastic thing and bounce up and down inside of it. I have no idea how much these cost. As I said, it used to be you would only see them at a big celebration in your neighborhood or in your town and now, parents, with again way too much money to spend on their children, get these for their children’s parties. So, some company comes over and they put one of these inflatable castles in the front of your house and all the neighborhood children will come to the party and play inside of this castle.
Paul says, “You do remember that Gabriel is turning one, don’t you?” “Turning” here means having a birthday and becoming one year older. So, I could say, for example, “I’m turning 30 this year.” That means this year I will have my 30th birthday – just an example, of course. Paul thinks that Sara is having a big party that is really unnecessary since Gabriel, their son, is only one year old. He won’t even be able to understand what’s going on. Paul ends the story by saying, “It’s just as I suspected.” It’s just as I thought. “Some birthday parties aren’t for the children. They’re for the adults who never grew up.” “Grew (grew) up” is the past tense of “grow (grow) up,” which means to become an adult, to no longer be a child. Paul is saying that the birthday party isn’t for Gabriel. He’s only one year old. He doesn’t know what’s going on. It’s for Sara – an adult who has never quite grown up herself.
Now let’s listen to the dialog this time, at a normal speed.
[start of dialog]
Sara: Come on! We need to buy all of the things we need for Gabriel’s party before the store closes.
Paul: Are you sure we need a party? Maybe we can just have a cake and some party hats.
Sara: Are you kidding?! We are going to pull out all the stops. We’ll have streamers, balloons, noisemakers, and party favors. This is going to be really fun.
Paul: I don’t even know if he’d like all that. What are you doing?
Sara: I’m getting lots of confetti to throw when we sing “Happy Birthday.”
Paul: The confetti is going to get all over the ice cream and the icing on the cake. And it’ll be a nightmare to clean up.
Sara: Don’t worry about the clean up. I’ll take care of that. Now, where are the goodie bags...
Paul: Are you sure all of this is necessary?
Sara: Of course, it is. Ooo...What do you think of hiring a clown and renting an inflatable castle for the party?
Paul: You do remember that Gabriel is turning one, don’t you?
Sara: So?
...
It’s just as I suspected. Some birthday parties aren’t for the children. They’re for the adults who never grew up!
[end of dialog]
Our scriptwriter pulls out all the stops when she writes her wonderful scripts for us. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again, here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
cake – a sweet, bread-like dessert that is cut into pieces and shared with many people on special occasions, especially on birthdays
* Janus is turning 30, so we’re trying to fit 30 candles on top of his birthday cake.
party hat – a colorful paper hat in the shape of a cone, given to all the people who come to a party
* Everyone wore bright yellow party hats that said, “Happy New Year!”
to pull out all the stops – to do everything or all parts of something, without any limitations or hesitations; to do something wholeheartedly
* This conference has to be perfect, so we’re going to pull out all the stops, no matter how much it costs.
streamer – a long, curling piece of brightly colored paper, hung on walls, doors, and/or windows to decorate for a party
* On Halloween night, they decorated their front porch with orange and black streamers.
balloon – a small piece of rubber that is filled with air, usually in a round or oval shape, used for decoration and/or as a toy for children
* The clown made animal shapes out of balloons and gave them to the children.
noisemaker – a small, usually inexpensive device that makes a lot of noise, either by hitting two parts together or by blowing into it like a horn
* There were so many noisemakers at the street fair that we couldn’t hear any of the bands.
party favor – a small gift given to the people who attend a party
* The party had a princess theme, so all the girls received crowns, wands, and other party favors.
confetti – very small, colored pieces of paper or plastic that are used to decorate tabletops and/or thrown into the air to celebrate something
* Did people throw rice or confetti at their wedding?
ice cream – a sweet, frozen dessert made from milk, sugar, eggs, and fruit or other flavorings
* This apple pie would be even better with a scoop of ice cream.
icing – a thick, sweet, colored substance put on the top and sides of a cake as decoration, often creating flowers or words
* He bought a small chocolate cake with red icing in the shape of a heart for his girlfriend.
nightmare – a bad, scary, or frightening dream; a very bad experience
* Cleaning up after the storm was a nightmare!
goodie bag – a small bag of inexpensive gifts given to the people who come to a party, especially a child’s birthday party
* When I was a kid, the other children just brought presents for the birthday boy, but now, the birthday boy is expected to give everyone a goodie bag!
clown – a person who dresses in very large, brightly colored clothing, often with huge shoes and a red nose, and does and says funny things to try to make people laugh
* The clown tried to make the little girl smile, but she was too scared of him.
inflatable castle – a large, plastic or cloth structure in the shape of a castle (the home of kings and queens) that is filled with air so that children can play on and in it, and that folds into a small object when the air is let out
* The kids aren’t allowed to play in the inflatable castle unless they take off their shoes.
to turn – to have a birthday and become one year older
* Leyla is really looking forward to turning 16 and getting her driver’s license.
to suspect – to think and believe that something is true, but not have any proof or evidence
* I suspect that everyone is thinking the same thing, but nobody wants to say it out loud.
to grow up – to become mature; to become an adult, no longer be a child
* What do you want to be when you grow up?
Comprehension Questions
1. What does Sara mean when she says, “We are going to pull out all the stops”?
a) She is going to drive very fast.
b) She is going to invite only a few people.
c) She is going to have a big party.
2. What are goodie bags?
a) Gifts for the guests.
b) Gifts for the birthday boy or girl.
c) Garbage bags for cleaning up after a party.
Answers at bottom.
What Else Does It Mean?
icing
The word “icing,” in this podcast, means a thick, sweet, colored substance put on the top and sides of a cake as decoration, often creating flowers or words: “Can you use writing to draw a flower on top of each cupcake?” As a verb, “to ice” means to cover a cake in the icing: “Sometimes it’s really hard to ice the sides of a cake.” The phrase “to be just the icing on the cake” describes something that makes a good experience even better: “Wendy was thrilled to find out she was pregnant, and finding out she was going to have twins was just the icing on the cake.” Finally, when talking about an injury, “to ice (something)” means to put ice over part of one’s body so that it does not swell (get bigger): “Richard iced his knee as he was driven to the hospital.”
to turn
In this podcast, the verb “to turn” means to have a birthday and become one year older: “Most Americans turn 18 before they graduate from high school.” The phrase “to turn the corner” means for something to change in an important way and begin to work better: “Their finances turned the corner once Ingrid found a steady job.” The phrase “to turn (something) on its head” means to make a big and surprising change in how something is done or organized: “The new director turned our organization on its head.” Finally, the phrase “to turn (people’s) heads” means to do something that surprises other people and catches their attention: “The film director’s latest film is really turning people’s heads in the movie industry.”
Culture Note
Inflatable Castles
Inflatable castles, also known as “bounce houses” are becoming “increasingly” (more and more) popular in the United States. Today, it is common to see them at children’s birthday parties, school “fairs” (festivals), “company picnics” (events where a company’s employees and their families eat outdoors together) and similar events.
The first inflatable structure was designed in 1959. The “inventor” (a person who creates something) was trying to design an inflatable cover for “tennis courts” (the flat areas where tennis games are played). He saw that his employees were enjoying jumping on the covers, so he began to develop other types of inflatable structures. Since then, many other people and companies have created new designs, many with “enclosures” (something that goes around something else) that prevent children from jumping out of the structure and becoming injured.
Inflatable castles are usually “inflated” (filled up with air) with a “blower” (a powerful fan) that blows air into the structure “continuously” (without stopping), because some air is always escaping through the “seams” (where two pieces are sewn together) and small “punctures” (holes).
Now there are many “rental companies” that allow organizations and individuals to “rent” an inflatable castle for a short period of time, paying much less than the cost of buying a new inflatable castle. The inflatable castles have many different shapes. Some are designed to look like traditional castles. Others look like “ships” (large boats) or “haunted houses” (homes where there are scary ghosts). Still others have an educational purpose, such as an inflatable castle that looks like “internal organs” (body parts on the inside) and teaches about “anatomy” (the study of body structures).
Comprehension Answers
1 - c
2 - a