= 0878
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast 878: Recovering from an Illness or Injury.
This is English as a Second Language Podcast episode 878. I'm your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and become a member of ESL Podcast today.
This episode is a dialogue between Julio and Paula about getting injured – having something bad happen to your body. Let’s get started.
[start of dialog]
Julio: Hi, Aunt Louisa, it’s Julio.
Paula: ...And Paula. I’m on the extension in the kitchen.
Julio: Anyway, we just wanted to call and wish you a speedy recovery. Get plenty of bed rest and take it easy. Avoid greasy or spicy foods and drink lots of liquids. You don’t want to become dehydrated.
Paula: Don’t listen to him. You need to stay active and not get in the habit of sitting around. You’ll recover faster if you get up and move around a lot.
Julio: That’s terrible advice. She needs rest and to eat right. You know what they say: “Feed a cold, starve a fever.”
Paula: What does that old adage have to do with anything? What you need, Aunt Louisa, is to alternate between a heating pad and an ice pack.
Julio: What are you talking about? Aunt Louisa has a bad cold.
Paula: What?! I thought she had a sore back!
[end of dialog]
Our dialogue begins with Julio talking on the phone to his Aunt Luisa. Your “aunt” is the sister of either your mother or your father. Julio says “Hi, Aunt Luisa, it's Julio.” Also, however, talking on the telephone is Paula. So after Julio says hello to his aunt, Paula, whose on the extension in the kitchen, says hello. The “extension” is an additional telephone that is connected to the same phone number, to the same line, so that two people in one office or one house can both talk to someone. Of course, this is impossible on a cell phone, but it is possible when you have the physical phone lines coming into your house or your building. We sometimes call that a “landline” (landline). A “landline” is, you might call it, an old-fashioned phone. It's not a cellular phone. It's not a mobile phone. It's a phone that is connected to your house with physical wires.
Well, Paula and Julio are both talking to their Aunt Luisa. Paula is on the extension in the kitchen. Once again, extension is just another phone in the house or in the building. Julio says, “Anyway, we just wanted to call and wish you a speedy recovery.” That use of “anyway” at the beginning of the sentence is very common in modern conversational English. It can be used in a number of different ways. Here it's used to change the subject or to return the conversation to the topic you were on before someone else changed it. Julio was talking to his Aunt Luisa and then Paula came in, shifting the attention of the conversation to her. So, Julio wants to get back control, if you will, of the conversation. So, he says “Anyway,” meaning paying attention to me now, “we just wanted to call and wish you a speedy recovery.” “Speedy” (speedy) means quick or fast. “Rapid” would be another term. “Recovery” (recovery) is when you get better after feeling sick or after being hurt. “Recovery” is getting better from an illness. A “speedy recovery” would be doing that quickly. Paula and Julio are calling to wish their Aunt Luisa a speedy recovery. They're hoping she gets better soon.
Julio says, “Get plenty of bed rest and take it easy.” “Bed rest” is simply lying in your bed, not getting up, not moving. “Take it easy” is it general expression we use to mean relax. Try not to do anything that's difficult. Take it easy. Sometimes, we use that expression as a way of saying goodbye to someone. “Okay, well, it was nice to see you. Take it easy.” You’re really sort of saying goodbye in that instance.
Here, Julio means exactly what he says. He wants his aunt to relax, to not do anything difficult. Then he says, “Avoid greasy or spicy foods.” “Greasy” (greasy) is food with a lot of oil and fat in it, like, I don't know, duck or certain kinds of pork might be greasy. “Spicy” (spicy) is a very burning hot sensation produced in the mouth, usually by hot peppers. Certain kinds of food from certain countries can be spicy. Food from Mexico, for example, can be spicy. Food from Thailand can be spicy. Lots of different countries have spicy foods as part of their traditional food. Julio is telling his aunt to avoid greasy, or spicy foods. Don't eat them. Avoid them.
He says “Drink lots of liquids.” “Liquids” would be things like water or milk or soda or tea. Those are all liquids. It's not unusual, for people who are recovering from certain kinds of sicknesses – to give this sort of advice. Julio says, “You don't want to become dehydrated.” “To be dehydrated” (dehydrated) means to not drink enough water or not drink enough liquid so that your body feels ill. It feels weak. If you go all day and you don't drink anything, any sort of liquid, your body might start to feel weak. It's becoming dehydrated. “Hydration” has to do with water or liquid. “Dehydration” is when you don't have enough water or liquid.
Paula says, “Don't listen to him.” Don't listen to Julio. “You need to stay active and not get in the habit of sitting around.” So, Paula comes on the phone and gives completely opposite advice to her Aunt Luisa. I think Paula is Julio's sister. Sisters do this sometimes. They think that their brothers don't know anything. I think my sister Kathy feels that way about me.
Anyway, Paula gives Aunt Luisa completely different advice. She tells her to stay active. “To stay active” means to use your body for physical activities, often to help maintain your health. So go to the gym or exercise or jog around the block, run around the block. All these are ways of staying active. “To get into the habit of something” means to get used to something so that you do it regularly. You continue to do it without having to think about it. That's what a “habit” (habit) is. It's something you do all the time, regularly, without really even thinking about it. I get up in the morning. I brush my teeth. I clean my teeth. That's a habit. I don't have to write it down to remember. I just know that that's what I do every morning. That is what Paula is talking about when she is telling her aunt not to get in the habit of doing something, meaning don't make that a regular part of your day.
What doesn't Paula want her want to do? She doesn't want her on getting in the habit of “sitting around.” “To sit around” means just to sit in a chair and not do anything, have no physical activity.
Paula says, “You'll recover faster” – you'll get better faster – “if you get up and move around a lot.” Julio says, “That's terrible advice.” That's bad advice, a very bad suggestion. “She needs rest and to eat right.” Julio is saying that is aunt needs to rest in bed and to eat the right foods. “You know what they say, ‘Feed a cold, starve a fever.’”
This is an old expression. “To feed” means to give someone food. “Feed a cold” means when someone has a cold, they should continue to eat. If someone has a “fever” (fever), where their body’s temperature is higher than it should be, then you don't give them food. “To starve” (starve) means not to have enough food. In this case, it simply means don't give someone food who has a fever, but if they have a cold, you should give them food. You should feed them. I don't know if that is correct, however. I'm not a medical doctor ,so please don't take this as advice for your own illnesses and sickness!
Paula says, “What does that old adage have to do with anything?” An “adage” (adage) is a saying or a traditional expression. We might also call it a “proverb” (proverb). Paula says, “What you need, Aunt Luisa, is to alternate between a heating pad and an ice pack.” “To alternate between something and something else” means to go back and forth. First do one thing, and then do another thing. In this case, first use a heating pad and then an ice pack. A “heating pad” (pad) is something that you put on your body to make it warm. It's usually a piece of cloth or fabric that has electrical wires inside of it that produce heat, so that if you hurt, for example, your leg, you can put this pad on, this cloth on, that will get hot and help it relax.
An “ice pack” (pack) is a small container of (usually) water that is frozen – that is to say, it's “ice” that is put into a small plastic container or other small container and put on your body to keep yourself or part of your body cold. For example, if you hurt yourself, you may put an ice pack on it so that the injury doesn't get any worse or to help it recover. Both heating pads and ice packs are used for (typically) injuries to your muscles, when you hurt some part of your body related to your muscles.
Julio says, “What are you talking about, Paula? Aunt Lisa has a bad cold.” Aunt Lisa did not hurt her muscles, did not have any sort of physical injury. Instead, she has a cold, which usually involves having a sore throat. You might be coughing, have a headache – all of these things are part of having a cold. A cold is usually not a serious disease or serious illness, I should say.
Paula says, “What? I thought she had a sore back?” “Sore” (sore) is a part of your body that hurts. Paula thought that Aunt Luisa's problem was a sore back, that she hurt the muscles in her back or some other part of her back, and that's why she was telling her to stay active and to use a heating pad or an ice pack. But of course, Julio knows what's going on here. (Brothers usually know more than sisters.) And he says “No, no, she just has a cold.”
Now let's listen to the dialogue this time at a normal speed
[start of dialog]
Julio: Hi, Aunt Louisa, it’s Julio.
Paula: ...And Paula. I’m on the extension in the kitchen.
Julio: Anyway, we just wanted to call and wish you a speedy recovery. Get plenty of bed rest and take it easy. Avoid greasy or spicy foods and drink lots of liquids. You don’t want to become dehydrated.
Paula: Don’t listen to him. You need to stay active and not get in the habit of sitting around. You’ll recover faster if you get up and move around a lot.
Julio: That’s terrible advice. She needs rest and to eat right. You know what they say: “Feed a cold, starve a fever.”
Paula: What does that old adage have to do with anything? What you need, Aunt Louisa, is to alternate between a heating pad and an ice pack.
Julio: What are you talking about? Aunt Louisa has a bad cold.
Paula: What?! I thought she had a sore back!
[end of dialog]
Our scriptwriter alternates between writing wonderful scripts and great scripts.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Comeback and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
extension – an additional telephone connected to the same line (phone number) as another phone in the same home or building
* Why am I hearing so much noise from the kitchen? Did somebody pick up the extension in there?
speedy – rapid; quick; not taking very long; happening soon
* Thanks for sending such a speedy reply to our note.
recovery – the moment at which one feels better after one has been sick or injured; the moment when one has full use of one’s body again
* The doctors anticipate a partial recovery within the next few days, but it could be years before Nakasuro has a full recovery.
bed rest – time spent lying down in a bed, usually because one’s body is very weak and needs to rest
* The doctor ordered bed rest for Lia in the last two months of her pregnancy.
to take it easy – to relax and not try to do anything that is difficult or challenging
* Hal has been really busy at the office these past few weeks, so he’s looking forward to taking it easy on the beach next weekend.
greasy – with a lot of oil and fat, especially when talking about food or skin
* When Brent finished eating the fried chicken, his hands were really greasy.
spicy – with a burning hot flavor, usually produced by hot peppers
* Candee doesn’t like spicy foods, so please don’t use pepper in the soup.
dehydrated – with the liquid taken out of something; without enough liquid in one’s body, so one feels ill and weak
* People who run long distances on hot summer days need to drink a lot of water so that they don’t become dehydrated.
to stay active – to use one’s body for physical activities, especially to maintain or improve one’s health
* What can we do to encourage people to stay active after they’ve broken a hip?
to get in the habit of – to become accustomed to doing something; to begin doing something regularly, so that one continues to do it without thinking about it
* How can we get our kids in the habit of turning off the lights when they leave a room?
to sit around – to spend time in a place without any particular purpose, maybe bored and not interested in anything
* I’m tired of sitting around and watching TV. Let’s go hiking instead!
starve a fever, feed a cold – a phrase reflecting a traditional belief that someone who has a fever (a high temperature caused by illness) should not eat, and someone who has a cold (a stuffy or runny nose and/or a cough) should eat a lot of food to get better
* When Hank started to sneeze, he ordered two large pizzas, saying, “Starve a fever, feed a cold!”
adage – proverb; a common phrase repeated many times by many people, usually with wisdom or advice
* When Juan and his girlfriend broke up, people tried to comfort him with an old adage: “There are other fish in the sea.”
to alternate between – to switch back and forth between two things; to first do A, then do B, then do A, etc.
* For major holidays like Thanksgiving and Christmas, they alternate between his parents’ home in Colorado and her parents’ home in Nebraska.
heating pad – a thick, flexible piece of fabric that has electrical wires inside that produce heat, used for relaxation and/or pain relief when applied to the skin
* Wynona’s feet are always cold, so she often puts a heating pad at the bottom of her bed.
ice pack – a small container filled with water or a similar liquid that is put in a freezer to freeze and then held against one’s skin, used for pain relief and/or to reduce swelling from an injury
* The doctor advised putting an ice pack on Becca’s knee for 10 minutes every half-hour.
cold – a minor illness, usually with a stuffy and/or runny nose, headache, sore throat, and cough
* Pierre caught a bad cold, so he won’t be coming to work today.
sore – describing a body part that hurts and is producing pain
* Olivia ran for the first time in months, and her legs were sore the next day
Comprehension Questions
1. According to Julio’s advice, which kind of food could Aunt Louisa eat?
a) Fried chicken.
b) Jalapeno salsa.
c) Fruit salad.
2. What should Aunt Louisa do to avoid becoming dehydrated?
a) She should drink a lot.
b) She should take her medicine on time.
c) She should do extra exercises.
Answers at bottom.
What Else Does It Mean?
extension
The word “extension,” in this podcast, means an additional telephone connected to the same line (phone number) as another phone in the same home or building: “Jane is on the phone! Pick up the extension in the bedroom so all three of us can talk at the same time!” An “extension” can also be one of many telephone lines that are in the same system, usually within an office building: “You can call me directly at extension 271, or just call the main number and ask for me by name.” Finally, when talking about hair, “extensions” are long pieces of artificial hair that women can attach to their natural hair to make it appear longer: “Glenda doesn’t have enough patience to grow out her own hair, so she decided to get extensions.”
sore
In this podcast, the word “sore” is used to describe a body part that hurts and is producing pain: “We went camping and slept outside in a tent, but the next day my back and neck were really sore.” The phrase “a sore point” or “a sore spot” refers to something that makes someone angry or upset: “Don’t ask Keith about his marriage. It has become a sore point for him.” If someone is “sore,” that person is angry or upset about something: “How can you still be sore about not being invited to the party? That was more than a year ago!” Finally, the phrase “to stick out like a sore thumb” means to be noticeable because something or someone is different than everything or everyone else: “If you wear a dress to go hiking, you’ll stick out like a sore thumb!”
Culture Note
Childproofing a Home
Babies and young children are “naturally” (something that is common among all people, not taught) “inquisitive” (curious; wanting to know more), but once they “become mobile” (learn how to crawl or walk), their efforts to explore their environment can “lead to” (result in) accidents and injuries. Experts on “child-rearing” (how to raise children) have many suggestions for how parents and other “caregivers” (people who take care of children) should “childproof their home” (make a home safer for children).
All “hazardous” (capable of causing injury or death) materials, such as cleaning supplies, should be stored “out of reach” (where someone cannot reach it) of children and/or in a cabinet with a “safety latch” (a device that makes it difficult or impossible for a child to open). Bookcases and other pieces of large, heavy furniture should be “secured” (fastened; attached) to a wall so that they cannot “topple over” (fall over) if the child tries to climb up the front to reach something on a higher shelf or in a top drawer.
“Outlets” (small holes in the wall that provide electricity to appliances) should be covered so that children cannot put their fingers or other small objects into the holes. The “cords” (strings or ropes) of “blinds” (a window covering made of many pieces of long, flat wood or plastic) present a “choking hazard” (something that could get wrapped around one’s neck and cause death), so they should be hung up high, out of reach of children. Plastic bags should also be stored out of reach, because they are a “suffocation hazard” (something that could cover one’s face and not allow the person to breathe).
Many products are sold for these and other types of childproofing, and some people “turn to” (ask for help from) consultants to childproof their home.
Comprehension Answers
1 - c
2 - a