= 0882
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 882: Playing a Practical Joke
This is English as a Second Language Podcast episode 882. I'm your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website.
This episode is a dialogue between Patricia and Luis about someone playing a practical joke on someone else. Let's get started.
[start of dialog]
Patricia: What are you doing?
Luis: I’m setting up a practical joke for Bobby. I can’t wait to see the look on his face when he walks outside and finds his bike in pieces. It’ll be the best prank ever!
Patricia: You’re not really going to take apart his bike, are you?
Luis: I’ll let you in on the joke. He’ll just be looking at spare parts. I’ve hidden his bike in the garage.
Patricia: He’s really going to freak out when he thinks that you’ve run over his bike with the car, though. I think this is more cruel than mischievous.
Luis: Lighten up! When he realizes he’s the butt of the joke, he’ll think it’s hilarious, trust me.
Patricia: Couldn’t you just play some other kind of practical joke, maybe with a whoopee cushion?
Luis: A whoopee cushion? That’s child’s play. This practical joke is worthy of a master prankster!
[end of dialog]
Patricia begins our dialogue by saying to Luis, “What are you doing?” Luis says, “I'm setting up a practical joke for Bobby.” “To set (set) up” is a phrasal verb meaning I'm getting ready, I'm getting organized, I'm putting together. Luis is putting together a practical joke. A “joke” is when someone says something funny. It could be a story. It could be something else that makes us laugh. A “practical joke” is some sort of physical action, some sort of trick, that’s supposed to be funny. The trick is always on another person. So, you do something so that the other person looks silly or foolish, not very intelligent. That's what a practical joke tries to do. It tries to make another person look silly, look ridiculous.
Well, Luis is setting up a practical joke for Bobby. We often use the verb “to play a practical joke,” which is in the title of this episode. Luis is going to play a practical joke for Bobby or “on” Bobby. “I can't wait to see the look on his face,” Luis says, when he walks outside and finds his bike in pieces. The expression “I can't wait to something” means I'm really looking forward to something. In this case, Luis is looking forward to “the look on Bobby's face” when he sees what has happened. He's looking forward to the reaction that Bobby will have when he walks outside – outside of their building, where they’re working probably – and finds, or discovers, his bicycle “in pieces.”
When we say something is “in pieces” (pieces), we mean it has been taken apart. It has been disassembled with all the individual pieces laying on the ground, or on the floor. So Luis has taken Bobby's bike and he has taken it apart. He has just assembled that and now the bike is in pieces.
Luis says, “It will be the best prank ever.” A “prank” (prank) is another word for a practical joke. More recently on a popular television program, instead of using the term practical joke or prank, they use the verb “to punk” (punk). “To punk” here means the same as to play a practical joke on someone. In the television show “Punk’d,” they play practical jokes on famous people, typically on celebrities.
Patricia says, “You're not really going to take apart his bike, are you?” Luis says, “I'll let you in on the joke.” “To let someone in on a joke” means to let someone know how you are going to do your practical joke, how you're going to play your practical joke, giving them the details of what is going to happen. Of course, Bobby doesn't know what’s going to happen.
Luis is going to tell Patricia. Luis says, “Bobby will just be looking at spare parts.” “Spare (spare) parts” are things that you use, typically, when you have a machine and it breaks down, you need to fix just part of the machine. We would call the thing you use to fix it with, that you replace the old thing that doesn't work with, “spare parts.” Luis is saying that when Bobby sees his bicycle, it will look like it's just a bunch of parts, just a bunch of pieces. “I've hidden his bike in the garage,” Luis says.
So now we understand what Luis is doing. He's not actually going to take Bobby's bike and take it all apart and leave it on the ground. He's going to take some spare parts, some other parts of another bicycle, and put that on the ground, or I should say put those on the ground, those parts on the ground. Bobby's real bike will not be the one on the ground. It will be in the garage. That's the joke.
Patricia says, “He's really going to freak out when he thinks that you've run over his bike with the car, though.” So, that's the trick. Luis is going to pretend like he ran over the bike. “To run over” means to hit and actually have the, in this case, car drive over the bicycle, which of course, I don't recommend, if you have a bicycle – or least you should get off the bicycle before someone runs it over.
Anyway, Patricia is talking about how Bobby is going to “freak out.” “To freak (freak) out” is a two-word phrasal verb meaning to become very upset, very angry, to lose control of yourself. It's an informal way of saying to go wild or to go crazy, to be so angry you start yelling and screaming.
Patricia says, “I think this is more cruel than mischievous.” “Cruel” (cruel) means very mean – when you are trying to hurt another person. “Cruel” is something that is not kind. “Mischievous” (mischievous) is used to describe a thing or person who is causing problems or causing trouble, but usually in a fun way, or at least in order to be funny. It's an adjective we would most typically use with children who are getting into trouble. They’re not bad children (except my neighbors children). But they’re children that are causing problems.
Luis says to Patricia, “Lighten up.” This expression “lighten (lighten) up” is a phrasal verb meaning relax. Don't take things so seriously. Don't get so excited. Try to have more fun.
Luis says, “When Bobby realizes he's the butt of the joke, he'll think it's hilarious, trust me.” “To be the butt (butt) of the joke” means you are the person that people are laughing at. You are the person who has had this practical joke played on, or more grammatically, on whom the practical joke has been played. Luis says, “Bobby will think it's hilarious.” “Hilarious” (hilarious) means very funny.
So, Bobby will think this is very funny. That's what Luis says. He says, “Trust me,” meaning believe me. I know what I'm talking about here, Patricia. Lighten up, Patricia, seriously.
Patricia says, “Couldn’t you just play some other kind of practical joke, maybe with a whoopee cushion?” A “whoopee (whoopee) cushion (cushion)” is basically a small rubber bag that has one opening in the bag so that when you sit on it, it makes a noise. It makes a funny noise. The ideas that you would put this cushion underneath someone, and they wouldn't realize they were going to sit on it, and then when they sit down it makes a funny noise. It's the sort of thing you would see in an old 1930’s or 1940’s movie, perhaps.
Luis says, “A whoopee cushion? That's child's play.” The expression “child's play” means something is very easy to do, something doesn't require any planning. It's too easy. That's the idea. Luis says, “This practical joke is worthy of a master prankster.” “To be worthy of something” means it's good enough for, or it's appropriate for. Luis is saying this joke is so good, that it is something that you would only expect normally from a master prankster. A “master” here means an expert, someone who knows a lot about something. A “prankster” is a person who plays practical jokes on other people. A “prankster” is a person who is always creating these pranks to make other people look foolish.
Now let’s listen to the dialogue this time at a normal speed.
[start of dialog]
Patricia: What are you doing?
Luis: I’m setting up a practical joke for Bobby. I can’t wait to see the look on his face when he walks outside and finds his bike in pieces. It’ll be the best prank ever!
Patricia: You’re not really going to take apart his bike, are you?
Luis: I’ll let you in on the joke. He’ll just be looking at spare parts. I’ve hidden his bike in the garage.
Patricia: He’s really going to freak out when he thinks that you’ve run over his bike with the car, though. I think this is more cruel than mischievous.
Luis: Lighten up! When he realizes he’s the butt of the joke, he’ll think it’s hilarious, trust me.
Patricia: Couldn’t you just play some other kind of practical joke, maybe with a whoopee cushion?
Luis: A whoopee cushion? That’s child’s play. This practical joke is worthy of a master prankster!
[end of dialog]
I can't wait to see the next wonderful script by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
practical joke – a trick; something done to be funny (and maybe mean) by making another person seem silly or foolish
* Harry’s coworkers filled his office with balloons as a practical joke.
can’t wait to see the look on (one’s) face – to look forward to seeing someone’s reaction to something, especially when one expects that person to be very surprised
* I can’t wait to see the look on Sheila’s face when her boyfriend proposes!
in pieces – taken part; with all the pieces of an object separated so that they are not attached or connected and the device no longer works
* It was easy to get the computer in pieces, but now we have to try to put it back together.
prank – a practical joke; a trick; something done to be funny (and maybe mean) by making another person seems silly or foolish
* Kidnapping Carla’s dog so that she would think it was missing was a terrible prank! Don’t do anything like that again!
to let (someone) in on a joke – to let someone know about how someone is tricking another person, when that other person remains unaware of what is happening
* Why are you all laughing? Let me in on the joke!
spare part – a replacement part used to fix one small piece of a larger device or machine
* Bryan called five different auto repair shops before he found the spare part he needed for his motorcycle.
to freak out – to become very upset or agitated and lose control over one’s words and actions, usually because one is very shocked, surprised, or worried
* Theo’s parents are going to freak out when they hear that he’s dating a woman who is 20 years older than he is!
cruel – very mean; intending to hurt another person; not kind
* Why did you promise to take your niece to the park on her birthday and then change your mind? That was cruel.
mischievous – creating trouble or causing problems, but in a fun or playful way, especially when talking about children
* Jacques was a mischievous boy, always putting frogs in his sister’s bed and throwing paper airplanes in class.
to lighten up – to relax and not take things so seriously; to be more playful and humorous
* It was just a joke and I’m sure she didn’t mean to hurt your feelings. Lighten up!
butt of the joke – the person who is being laughed at; the victim or target of a joke
* Kolya always likes making jokes about other people, but he gets really mad if he’s the butt of someone else’s joke.
hilarious – very funny, making one laugh uncontrollably
* That movie was hilarious! We were laughing so much that we started crying!
whoopee cushion – a small rubber bag with a small opening at one end, so that when one sits on it, it makes a loud noise like someone who is passing gas
* Did you ever put a whoopee cushion on your teacher’s chair when you were a student?
child’s play – something that is very easy to do and does not require planning and preparation; something that is so easy to do that even a child could do it
* Selling $5,000 per month is child’s play! If you really want a challenge, try to bring in sales of $10,000 per month!
worthy of – good enough for; equal in value to; appropriate for
* This huge, beautiful house is worthy of a king!
master – an expert; someone who is very good at doing something; with the greatest skill or ability
* Liana is a master chef. I can’t wait to eat in her home next weekend!
prankster – a person who plays a lot of tricks on other people
* Gregory is known as a prankster in the office.
Comprehension Questions
1. How does Patricia think Bobby will react when he sees the bike in pieces?
a) He’ll be frightened.
b) He’ll laugh.
c) He’ll panic.
2. Why doesn’t Luis want to use a whoopee cushion?
a) Because they’re too simple.
b) Because only kids can buy them.
c) Because they aren’t safe for children.
Answers at bottom.
What Else Does It Mean?
in pieces
The phrase “in pieces,” in this podcast, means taken part, or with all the pieces of an object separated so that they are not attached or connected and the device no longer works: “Grandma began crying when she saw her favorite vase in pieces.” The phrase “to cut something into pieces” means to cut something so that it has smaller slices that can be given to many people: “Please cut the cake into 12 pieces.” The phrase “to fall to pieces” means to stop working well or to become unsuccessful: “All of their plans are falling to pieces.” Finally, the phrase “to fall to pieces” can also describe something that is becoming older and beginning to fall apart: “An older empty home can fall to pieces in just a few years if nobody is taking care of it.”
master
In this podcast, the word “master” means an expert, or someone who is very good at doing something and has the greatest skill or ability: “Charlie is a master scuba diver who has visited most of the world’s best diving locations.” When talking about a document, a “master” is an original copy from which other copies are made: “Please don’t give the master to clients. Instead, make copies from it.” The phrase “to be (one’s) own master” means to be in control of one’s job or life, especially without a boss: “Bubba dreams of starting a business and being his own master.” Finally, in times of slavery, a “master” was a person who owned slaves: “How often does the master beat his slaves?”
Culture Note
Famous Practical Jokes
Friends often play small practical jokes on each other, and some of them are so common that they could be called “classic” practical jokes. For example, in an office environment, people might “block” (not allow any entry or passage) a coworker’s doorway by “stacking” (putting on top of each other) many phone books from the floor to the top of the doorway. Or they might fill an office with balloons, or “wrap” (cover) a desk with newspaper and tape.
Many pranksters use inexpensive objects in their jokes. Some stores sell “fake” (not real) “vomit” (the liquid that comes from one’s stomach and out of one’s mouth when one is sick) and fake “poo” (excrement; feces). People can put these objects on the floor where other people will be “grossed out” (disgusted) when they walk by. Pranksters can also buy fake “melted” (turning from a solid into a liquid) ice cream treats or fake “spilled” (dropped so that liquid comes out) wine. A prankster might put these objects on a white carpet or expensive “linens” (fabrics such as tablecloths, towels, and sheets) just to see the hostess’s reaction.
Students “have a reputation for” (are known for) playing practical jokes on their teachers. They might put a whoopee cushion on the teacher’s seat, put glue on the teachers’ phone or chair, or write a funny message on the board where the teacher cannot see it. They might even put a “bug” (insect) or a frog in the desk drawer to see the teacher’s reaction.
Comprehension Answers
1 - c
2 - a