= 1716
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 411.
This is English as a Second Language Podcast’s English Café episode 411. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this episode.
On this Café, we’re going to do another one of our “Ask an American” segments, where we listen to other native speakers – someone other than me – talking at a normal rate of speech, a normal speed. We’re going to listen to them and explain, as always, what they're talking about. Today we’re going to listen to a very interesting set of quotes about an area in New York City called Harlem, specifically about businesses in this area of New York. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s “Ask an American” segment is Harlem businesses. “Harlem” (Harlem) is a large neighborhood in the northern part of Manhattan. Manhattan is a “borough” (borough), or area in New York City. New York City has five boroughs – five districts, five areas. Manhattan is an island that is considered the downtown, basically, of New York City.
Harlem is one section of that island, that borough, that has traditionally been home to a large African American or black community. The neighborhood is, we are going to learn, undergoing or experiencing a lot of changes. Many businesses are moving into the area, and this is causing the amount that building owners can charge to increase. It is causing the rents to increase. Many small businesses that have been in that area for many years, especially many African American–owned businesses – businesses that are run by African Americans – are having a difficult time, precisely because it is getting more expensive to do business in Harlem.
We’re going to listen to some people talking about these changes. First, we'll listen to a woman named Nikoa Evans Hendrix. Nikoa spent the last 14 years trying to organize small-business owners and trying to make Harlem more attractive to new businesses. First, listen to what she says, and then we’ll go back and explain. Let’s listen.
[recording]
"I’ve watched it evolve from essentially the forgotten land above 96th Street, where no one really saw any value, to the gold mine and the gold coast that it has become in Manhattan.”
[end of recording]
Nikoa speaks very quickly. That's not unusual for people from New York City. They have a reputation of speaking very fast. Nikoa says, “I’ve watched it” – meaning I've watched Harlem, this neighborhood – “evolve from essentially the forgotten land above 96th Street.” “To evolve” (evolve) means to change, to change from one thing to another. We have the word in English “evolution,” talking about the gradual changes of life forms over many thousands and even millions of years. Here, we’re not talking about life forms changing. We’re talking about a neighborhood changing.
Nikoa says she's watched Harlem “evolve from essentially the forgotten land.” “Essentially” means “basically,” in terms of the most important thing for us to think about. When someone says, “essentially,” they are trying to give the most important characteristic or the most important fact about a situation. Here, Nikoa is describing how people used to look at or think about Harlem. Harlem is located at least in part above 96th Street in New York City. I should say 96th Street in Manhattan, since that's the part of the city we’re talking about here.
So, when Nikoa says, “above 96th Street,” she's referring to the area where Harlem is located in Manhattan. She says she's watched Harlem evolve from “essentially” – or basically – “the forgotten land above 96th Street.” The phrase “forgotten land” is referring to a place that people didn't really pay very much attention to, a place where people didn't have a lot of interest in. So, nobody thought about it. Nobody went there, certainly not to open up new businesses.
Nikoa says people used to not see any “value” in Harlem. “Value” means worth. If something has value, you believe it is worth something. Maybe you want to pay money for it, or you at least respect it and want to take care of it. When Harlem was a forgotten land, people didn't think it had any value, and so they didn't think about it very much, at least people who didn't live in that neighborhood. But Nikoa says that Harlem has evolved, has changed from this forgotten land into something else.
It's changed into a “gold mine” and a “gold coast.” What does she mean, a “gold mine” and a “gold coast”? “Gold” is a very valuable metal. You are probably already aware of that. A “mine” (mine) is a place where you dig into the ground in order to find, in this case, gold. You could also have a mine for coal or a mine for other substances that you are taking out of the earth. A “gold mine” refers to a place where you find gold inside of the earth. The term, however, is used here not literally to mean a gold mine but to refer to a place where you can get a lot of money, a place where there is a lot of money that can be made. Harlem is a good opportunity, Nikoa is saying, for people to make money.
The phrase “gold coast” (coast) can refer to many different places. Normally, it's an area near an ocean where you will find a lot of very expensive homes, where very rich people live. “Gold Coast” can also refer to a place in Australia, a place in West Africa . . . There are other places that people have referred to as the “Gold Coast.” Here, however, Nikoa isn't referring to anything specific like that. She's just referring to a place where there is a lot of money, where people can make a lot of money. She says that Harlem has evolved from a forgotten land to a gold mine and a gold coast. At the end of the quote, she says, “that it has become in Manhattan.” She means here that Harlem has “become” this gold mine and this gold coast. It has evolved or changed into that. Let’s listen to her one more time.
[recording]
"I’ve watched it evolve from essentially the forgotten land above 96th Street, where no one really saw any value, to the gold mine and the gold coast that it has become in Manhattan.”
[end of recording]
Next, we’re going to listen to a woman by the name of Seven Brown who owns a skin care spa – a place where people can go to get special treatments, we might call them, for their skin so their skin looks very beautiful. I usually do this once a week or so. I go to a skin care spa so that my skin is always looking beautiful. I'm kidding, of course. Let's listen to Seven Brown talk about what has happened in Harlem with this change that Nikoa told us about. Let’s listen.
[recording]
“You know, it’s been a great experience to be able to live and work in the same community that you’ve lived in for a long time. So there’s a good benefit there. The bad part of it is, you know, watching a lot of the mom-and-pop organizations, mostly black-owned businesses, close on a daily basis. I think I counted 60, 67 of them.”
[end of recording]
Brown begins by saying, “You know, it's been a great experience to be able to live and work in the same community that you've lived in for a long time.” A “community” here really means a neighborhood, a place, an area where you live. She's saying that it has been wonderful to be able to both live and work in this same community, this same area, for a very long time. She says, “So there’s a good benefit there.” A “benefit” is a positive thing, a good thing. Brown then says, “The bad part of it is, you know” – the “bad part” would be the negative aspect of this situation that she's describing.
Notice also, she uses – as she does at the beginning of the quote – “you know.” “You know” is one of those, we might call them “filler phrases,” that we use in English when we're trying to think of what we want to say. Some people just use them as part of their regular conversation. You'll hear people say, “You know” maybe 10, 15 times within a 10-minute period as they are talking. It depends on the person. Generally speaking, we try to avoid saying that unless we, you know, can't think of what to say.
Brown says the bad part of this change is “watching a lot of [the] mom-and-pop organizations, mostly black-owned businesses, close on a daily basis.” So, the difficult thing for her is watching a lot of “mom-and-pop” organizations close. A “mom-and-pop organization” would normally refer to a business that is run by a married couple, a mother and a father. Basically, it's a term for a family business. It doesn't mean there's actually a “mom,” a mother, and a “pop,” a father. It means it's run by a family. It's not owned by a big corporation.
Brown is saying that a lot of the mom-and-pop businesses in Harlem are closing. She calls them “black-owned businesses.” That means the owners – the people who have the organization, who run the organization – are African American, are black. As we've mentioned before in the Café, we use both “black” and “African American” as descriptors, as descriptions. These black-owned businesses, according to Brown, “are closing on a daily basis.” “To close” means here to go out of business, to no longer exist. “Daily (daily) basis” just means, in this case, every day or very frequently.
At the end, Brown says, “I think I counted 60, 67 of them.” She’s saying that she has counted the number of these mom-and-pop organizations that have closed, and that she came up with a number of either 60 or 67. Somewhere in between those is the number of organizations that have closed. Let’s listen to Brown one more time.
[recording]
“You know, it’s been a great experience to be able to live and work in the same community that you’ve lived in for a long time. So there’s a good benefit there. The bad part of it is, you know, watching a lot of the mom-and-pop organizations, mostly black-owned businesses, close on a daily basis. I think I counted 60, 67 of them.”
[end of recording]
Finally, we’re going to listen to one more small-business owner in Harlem, a man by the name of Hans Hageman. He and his wife have opened a gym in Harlem – some might call it a fitness center. Basically, it's a place where you go and exercise, where you try to keep in shape, you try to keep your body healthy – at least, that's what I'm told happens at a gym. I don't know. I don't go to one. I do exercise, don't worry.
Hageman says that he and his wife have opened this fitness center and talks about the good things and the bad things that happen in that business. Let’s listen.
[recording]
"One of the things about having a business here, and particularly where we live, is that our kids get to see both, um, whatever successes we have – and we hope to accelerate those – but they also get to see the struggles that small-business people have.”
[end of recording]
Once again, he speaks very quickly, but we’ll go back and explain everything he said. He starts by saying, “One of the things about having a business here.” “One of the things” means one of the things that he wants to talk about, one of the important aspects of having a business in Harlem. He says, “One of the things about having a business here, and particularly where we live, is that our kids get to see both, um, whatever successes we have.” The quote continues, but let's go back and talk about the first part. “One of the things about having a business here, and particularly where we live” – in other words, “especially where we live,” because they live in the same neighborhood where they have their business.
One of the things about this, he says, “is that our kids,” our children, “get to see both whatever successes we have . . .” Hans is saying that there are two things that his children get to see. One is the successes that they have, the good things that they have. Notice also that in the middle of his sentence, he uses the word “um.” “Um” is like “you know” – one of those words or sounds that we make when we're trying to think, perhaps, of what to say. Here, Hageman is saying that his children get to see the successes of the business, “and,” he says, “we hope to accelerate those.” “To accelerate” (accelerate) means to make something go faster. When you're driving a car, you can put your foot or step on the gas pedal to make the car go faster, but you could also try to accelerate change or accelerate the production of something. Here, Hageman is talking about accelerating the success of his business, making it more successful.
That's one thing that his children get to see, but they also get to see the bad things. They get to see the struggles that small-business people have. A “struggle” (struggle) is a difficulty, a challenge, an obstacle. A “struggle” is a problem that you have to find a solution for, and it may be a lot of work in order to solve the problem. Businesses face struggles in trying to find new customers. Students face struggles in trying to learn a new topic, a new subject. Here, Hageman is talking about the struggles that small-business people have.
A “small business” is a business that is not one of the most important companies in an area. It is typically owned by a small group of people, maybe only one person. It typically has very few employees. It doesn't have a lot of people working for it. All of these would be characteristics of a “small business.” “Small-business people” would be people who own small businesses. Small businesses are very important, however, because there are lots of them and they have a lot of people who work for them, if you count them all together. Small businesses are important in most economies, including the American economy. Now let's listen to Hageman one more time talk about the good and the bad about having a business in Harlem.
[recording]
"One of the things about having a business here, and particularly where we live, is that our kids get to see both, um, whatever successes we have – and we hope to accelerate those – but they also get to see the struggles that small business people have.”
[end of recording]
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Mantinder (Mantinder). I hope that's right. I'm not sure where Mantinder is from, probably from the lost city of Atlantis. Mantinder wants to know the difference between “imply” (imply) and “infer” (infer). This is a good question, because native speakers sometimes confuse these two words.
“To imply” means to say something to someone in a way that isn't direct. You are communicating a message to them, but you're not saying it to them directly. For example, someone wants to come and stay at your house to visit you for a week. You don't really want that person to come, but you can't say no to that person, especially if that person is, I don't know, your brother. So, you say, “Well, yes. You can come and stay at my house. That would be great. I just want to tell you that my children make a lot of noise, and my neighbor’s dogs are always barking, and the bed is really small, and well, of course, my wife is a terrible cook. She doesn't know how to cook, but you can definitely stay at my house.” You're not telling the person “No,” but you're implying it. You're giving him the message indirectly.
“To infer” is sort of the opposite. “To infer” is – you reach a conclusion based on what the other person says. So, I’m implying that you should not come to my house. You, listening to what I say, “infer” that you should not come to my house. “To infer” means to reach a conclusion based on something, based on evidence – in this case, based on what I am saying to you. So, “imply” is when I do something or say something, typically, that leads you to a conclusion, and “infer” is when you take what someone says and you reach a conclusion.
Our next question comes from Kageyu (Kageyu) in Japan. The question has to do with two phrasal verbs: “to put aside” and “to set aside.” Both “to put aside” and “to set aside” can sometimes be used in the same situation. Both of them can mean to take something, some physical object like a chair or a book or a pen, and put it out of the way, either put it in a place where you store it or to move it away from where it is now so that it is not blocking or getting in the way of any of the house. That's “to put aside.” “To put aside” or “to set aside” means to take something and move it to a different location so that it is no longer in the way.
For example, I may say to you, “Put aside your homework and let's go have a drink.” Well, I wouldn't really say that to you, because if you're doing homework, you may not be old enough to drink. Remember, you have to be 21 to drink in the United States. Anyway, let’s say I’m not in the United States, and you’re a college student, and I say, “Hey, put aside your books. Let's go have a drink.” “Put aside” means to put them down, to maybe put them back into your desk, and that way they won't get in the way. “Set aside” can also be used for something physical. “He set aside his newspaper in order to talk to his wife,” or “They set aside their phones” – their cell phones – “during the meeting.” Those are both cases where you could say “put aside” or “set aside.”
“To put aside” has another meaning, which means to save for later. I'm going to put aside some money for my vacation. I'm going to save some money. “To set aside” is also used in a situation where you don't have something physical, but you have a situation that you're going to ignore, that you're not going to pay attention to, at least for a short time. There is a common expression: “to set aside our differences.” “To set aside our differences” means to not worry about them right now, to ignore them, to not think about them. Maybe we'll come back and think about them later. So, “to put aside” and “to set aside” can be used for physical objects. “To put aside” can mean also to save, especially to save money. “To set aside,” especially in the phrase “to set aside our differences,” means to ignore, not to worry about them right now.
Finally, we have a question from Norbert (Norbert), now living in Germany but originally from Poland. Norbert wants to know the meaning of something that he read: “Something's got to give.” “Something's got to give” – what does that expression mean? “Something’s got to give” means that the situation cannot continue like this. Usually, it's a situation where you have two different – we could call them “sides” – two different groups, two different people who have differing ideas about something. I want to do this and you want to do that. I want to go left and you want to go right. What do we do? In a situation like that, one side has to change their mind if things are going to continue, if you are going to make progress.
That's a situation where we might say, “Something's got to give.” You want to go left. I want to go right. One of us has to change their mind. “Got to,” sometimes you'll see informally spelled (gotta) instead of (got), and then (to). “Something's gotta give,” again, means the same as “Something's got to give.” When we speak quickly, in American English, sometimes we combine words together. We used to call that, back when I was teaching several years ago, “compressed speech” – when all the words go together so that you can’t hear the differences between them. That's what's happening here when somebody says, “Something’s gotta give.” They mean something has to change, something has to be different. The situation cannot continue. Someone has to change their mind, hopefully the other person.
There was a movie in 2003 with a couple of the most famous actors in Los Angeles, in Hollywood, in the world – Jack Nicholson and Diane Keaton. The movie was called “Something's Gotta Give,” and it was about an older man, played by Jack Nicholson, who likes to have romantic relationships with younger women, but towards the end of the movie he falls in love with an older woman, and that would be Diane Keaton. This is a movie that only Hollywood could make, something that is completely imaginary, something that would never actually happen here in Los Angeles, where an older man who likes younger women would suddenly start liking older women. That, as I say, is an imaginary situation here.
If you have a real question for us, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
Glossary
to evolve – to change, especially when talking about very gradual changes over long periods of time
* The public’s opinions about the environment has evolved over time.
essentially – basically; in essence
* The movie was entertaining, but it was essentially just a standard romantic-comedy.
forgotten land – a place that people once knew about, but no longer have any interest in, so nobody thinks about it or goes there
* Once the automobile manufacturers closed their factories, this town became a forgotten land.
value – worth, so that someone is willing to pay money for something or at least respects it and wants to take care of it
* There’s a lot of value in farmer’s markets that let shoppers meet the people who grow their food.
gold mine – a place where people have the opportunity to make a lot of money
* Oil far below the earth’s surface is a potential gold mine for this country.
gold coast – an area near the ocean where there are many expensive homes; a place where many people perceive opportunities to make a lot of money
* The state’s gold coast is filled with actors, musicians, and other celebrities who own multi-million-dollar mansions overlooking the ocean.
mom-and-pop – referring to a small, family business that is owned and operated by a married couple or by a family
* Shopping at national chains can be convenient, but it’s important to support the local mom-and-pop businesses.
on a daily basis – daily; every day
* When you provide childcare for the Greens, do you they pay you on a daily basis, or once a week?
to count – to keep track of the number of something that is happening
* Each year, scientists count how many birds leave and return to this area.
to accelerate – to make something go faster
* These special light bulbs can accelerate plant growth in the greenhouses.
struggle – a challenge, an obstacle, or something difficult that one has to overcome or find a solution for
* Paying for college is a huge struggle for most middle-class families.
small business – a business that is not a leader in its field, is owned privately, has few employees, and has relatively low sales
* What percentage of small businesses fail in the first three years of operation?
to imply – to suggest without saying directly or clearly
* I didn’t mean to imply that I wanted you to make me lunch when I said that I was very hungry.
to infer – to reach a conclusion based on evidence; to guess; to hint or suggest
* We inferred from her comments that she’s no longer dating Bruce.
to put aside – to save for later; to place out of the way
* Let’s put aside the question of money and decide which plan is best based only on the designs.
to set aside – to place out of the way; to ignore
* Cut these carrots, but set them aside for now. Put them into the pot after the other vegetables have cooked for 30 minutes.
something’s got to (gotta) give – things cannot continue like this; a situation where both sides will not give up or a compromise cannot continue
* Neither Sam nor Bettina are willing to admit they’re wrong, but something’s got to give if they expect to continuing working with each other on this project.
What Insiders Know
The Boston Massacre
March 5, 1770 was not just a “typical” (normal) day in Boston, Massachusetts. On this day, British soldiers killed five “civilian” (not military) men in an “incident” (event) known as the Boston “Massacre” (event where many people are killed). It was one of the most important events that led to American independence from Great Britain.
In the late 1700’s, Boston was a “colony” of (area controlled and governed by) of Britain and the people of Boston disliked British “rule” (government control). The “citizens” (people who live and belongs to a place) of Boston were not “shy” (timid; quiet) about their unhappiness, and they made the British aware of this hatred. This resulted in the British “Parliament” (government) sending more “troops” (soldiers) to Boston to maintain control.
On February 22, 1770, less than two weeks before the massacre, a member of the British government killed a boy named Christopher Seider. The killer was “convicted” (found guilty in a court of law) of the murder, but to the surprise of many, he was given a “royal pardon” (official forgiveness by a king or queen) and was given a new job in the government. This angered the citizens of Boston even more.
On the night of March 5th, a group of people “taunted” (said and behaved in a hostile way to get someone to react) several British soldiers. They threw snowballs, sticks, and stones at them. Captain Thomas Preston of the British Army “ordered” (told) his men to fight back and started shooting the people. Three were immediately killed and several people also died from their “wounds” (injuries).
Citizens of Boston asked the government to removed Captain Thomas Preston and his soldiers from “duty” (work; job) and charge them with murder. John Adams, a future American president, was a lawyer then and defended Captain Preston in court. Six men were “acquitted” (found not guilty) and two were convicted of “manslaughter” (the crime of killing without intending to).
Although some historians say that it should not have been called a massacre, the events of March 5, 1770 were very important. It was one of the most important events that led to the American Revolutionary War, the war that gained American independence from Great Britain.