= 1749
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 444.
This is English as a Second Language Podcast’s English Café episode 444. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also like us on Facebook at facebook.com/eslpod.
Today we’re going to talk about another famous American author, a novelist by the name of J. D. Salinger. We’re also going to talk about Mad Magazine and The Onion, examples of comedy magazines and newspapers in the U.S. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café with a look at an interesting, if odd, twentieth-century American writer named J. D. Salinger. Jerome David Salinger, better known as J. D. Salinger, was an American author who wrote short stories and books. His most famous book, The Catcher in the Rye, is thought of as one of the most important American books or novels written in the mid-twentieth century, and is very well-known by many high school students.
J. D. Salinger was born in New York City on January 1, 1919. Salinger was apparently not a great student, attending both public schools and a military academy, a special school for boys that emphasizes the discipline of the military. Military academies, usually high schools, were more common in the twentieth century than they are now. They are typically expensive private schools, often used by parents who want their sons to have more discipline. My father had enough discipline so that we didn’t really need to go to a special school to experience that.
After Salinger graduated from high school, he went to New York University in New York City for one year before leaving to travel around Europe. While in Europe, Salinger spent most of his time in Vienna, Austria, learning German and the Austrian culture. When he returned to the United States, Salinger began taking classes at night at Columbia University – in New York City, also.
One of his professors, Whit Burnett, was the editor of a magazine called Story, which published, of course, short stories. Burnett could tell – he realized – that Salinger was an excellent writer, and encouraged him to write short stories for his magazine. Salinger did and began to get his short stories published in important magazines of that time such as Collier’s and The Saturday Evening Post.
In 1942, after the attack on Pearl Harbor in Hawaii on the United States military, America entered World War II, and Salinger, like many men of his age at that time, was drafted. “To be drafted” (drafted) is to basically be forced to enter into the military. In Salinger’s case, it was the army. He went to Europe and fought there, like millions of other Americans – like my father, in fact. During the war, Salinger continued writing. He started work on what would become his most famous book, The Catcher in the Rye.
After World War II ended, Salinger was put in the hospital in Nuremburg, Germany, for “stress” (stress) or being emotionally tired because of difficult events of the war. Not much is known about his time in the hospital. We do know that in 1945, Salinger met and married a woman named Sylvia Weiter. There is not a lot of information about Sylvia except that she was German. Their marriage only lasted for eight months, and they divorced in 1946, shortly after moving back to New York City.
While in New York, Salinger started his writing career again and began being published in magazines such as The New Yorker, one of the very best magazines, with a reputation for publishing some of the best fiction and nonfiction in the U.S., both in the 1940s and today. He continued working on that book he started during the war, what became known as The Catcher in the Rye. The book was published in 1951 and quickly became an important part of contemporary, or modern, American literature.
The Catcher in the Rye is the story of a teenager named Holden Caulfield, who is 16 years old. The book is set in, or takes place in, the 1950s and is written in the first person, as though the main character is talking directly to the reader. Books are usually written either in the first person or the third person. Third person novels and stories are told as though the person telling the story is “outside” the story, whereas first person stories are told from the point of view of a single person.
The Cather in the Rye is the story of a young man who doesn’t, what we would call, “fit in.” He doesn’t feel comfortable in the world around him. Holden Caulfield is a sensitive, smart, funny, and somewhat rebellious teenager – he doesn’t want to follow the rules of his school or his parents. In other words, he’s a very typical teenager. What made this book so popular, in part, was that Salinger wrote it in the language of teenagers, using a lot of “slang” – informal expressions that might be popular among young people at that time.
The character in the book, Holden Caulfield, uses words like “phony” (phony) which means fake and not truthful. He uses “phony” to describe the people he meets. A phony is someone who tries to appear to others in a different way than he or she really is, usually so that others will like or admire that person more. This, of course, is very common among young people who are searching for their own “true” identity. In the story, Caulfield visits different places in New York City, meeting up with friends of his. He tries to understand the world by talking to different people, but he isn’t happy with any of their stories or answers to his questions about how he should live his life.
The Catcher in the Rye became a popular book with young people in the 1950s, especially teenagers and people in their early 20s. The book was written, some say, in the tradition of Mark Twain’s stories of another young man, Huckleberry Finn. The book provides a similar insight or look into the world of a young American boy – not one of the nineteenth century, but one of the twentieth century. It is still a popular book today, and definitely was when I was growing up in the 1970s and ‘80s.
Now, there is some profanity in the book. “Profanity” (profanity) is when you use bad or what we might also call “vulgar” (vulgar) words, words that we don’t use typically here on the Café. The book, however, is nothing like what you might hear today on popular American television shows or in movies. So, I don’t think you would be too surprised by anything you saw now in the book compared to what you see now on your television screen.
But for that time, for the 1950s, the book was considered by some people to be a little vulgar. Because of that, many parents did not want the book used in high schools. But it is, in fact, often used in high school English classes today, which I actually think is somewhat unfortunate, perhaps not a good idea. When I was in high school, the book was almost considered “underground reading” – the kind of book you didn’t want your parents to know you were reading, or at least your teachers. It was a book other students passed on to you, if you were the kind of kid who was a reader in school.
Teenagers, especially teenage boys, who discover the book on their own, I think will have a very different experience with it compared to students who are assigned or required to read it in school. I read it when I was 16 and thought it was amazing because, of course, it was about someone my age, with at least some of my experiences and emotions. It’s the sort of book that you can read again later in life and get a very different message from.
I actually re-read the book when I was in my early 20s, and again in my early 30s, and each time I found it to contain something different. It gave me a different message. That in a way is a sign or an indication of a great piece of literature – you can re-read and get more and more out of it each time.
When Salinger was a young man, he wanted nothing more than to be famous – that is, he really wanted to be famous. However, once he became famous, he wanted nothing more than to be left alone. In 1953, just two years after publishing The Catcher in the Rye, Salinger left New York and moved to the countryside, away from the big city, to a town called Cornish in the state of New Hampshire. Cornish is about 140 miles (that would be 225 kilometers to the rest of the world) northeast of Boston, Massachusetts, in the northeastern part of the U.S.
When he lived in New Hampshire, Salinger basically stopped talking to his friends back in New York City and spent most of his time alone. He did spend some time with local teenagers, however. One of the teenagers he met was 19-year-old Claire Douglas. The two of them eventually married in 1955 and had two children, Margaret and Matthew. Salinger continued to write in New Hampshire. In 1961, he published the book Franny and Zooey, and in 1963 he published Carpenters and Seymour: An Introduction. In 1965, Salinger published his final short story in The New Yorker.
Salinger’s marriage slowly fell apart. It slowly “stopped working,” we could say. He spent most of the time alone. Finally, in 1967, his wife divorced him. As the years passed, Salinger became more and more of what we could call a “recluse.” A “recluse” (recluse) is a person who lives alone and doesn’t have any contact with other people. Salinger had some contact however, with other people – at least with one person, a local nurse called Colleen O’Neill. He married O’Neill in 1991. Salinger himself died in 2010 at the age of 91.
Even though Salinger spent over 50 years in seclusion, he remained a very popular author. When I say he was in “seclusion” (seclusion), I mean he was away from other people, as we described him – we would call him a “recluse.” So, if you’re interested in finding out a little bit more about American teenagers, especially in the twentieth century, I can definitely recommend The Catcher in the Rye.
Now let’s briefly turn to two popular comedy magazines and newspapers, Mad Magazine and The Onion. The first one we’ll talk about is the older of the two, one that people of my generation know very well: Mad Magazine.
Mad Magazine was started back in 1952 by a man named William Gaines. Gaines had published “comics” – stories with pictures that are supposed to be funny – before publishing Mad Magazine. Like most comedy publications, Mad Magazine makes fun of people. It makes fun of real events and things that are in the news. The most famous thing about Mad Magazine is the cover of the magazine, which usually shows the same made up or fictional character, Alfred E. Newman, who looks like a teenager and always has these funny expressions on his face.
Mad Magazine quickly became popular with young boys and teenagers in the 1950s and ‘60s, people who, like young people in every country, had to deal with or get used to “authority,” people who were telling them what to do, such as parents and teachers. Through the magazine, boys and teenagers could, in some ways “rebel,” or go against the authority, by reading these stories that make fun of parents and teachers and other what we might call “authority figures.”
The magazine remained very popular throughout the ‘60s and ‘70s. In fact, in 1972, it had a circulation of over 2 million. When we talk about magazines and newspapers having a “circulation of” something, we mean that’s how many copies of the magazine or newspaper are being sold. I remember being able to buy the magazine back at “newsstands” – places where you could buy newspapers and magazines – and still can, when you can find a newsstand. There aren’t very many of them left in the United States anymore.
After the 1970s, Mad Magazine became a little less popular, perhaps because the times had changed in the 1970s and it no longer had the same appeal. It didn’t seem quite as outrageous and new as it did back in the 1950s and ‘60s. However, the magazine continues to be published. In fact, you can download an app for it now and read the magazine. It still has very much of the same flavor – the same ideas about humor and comedy – as it did when it started more than 50 years ago.
A much more popular comedy publication nowadays is called The Onion. The Onion is another satirical magazine. “Satirical” (satirical) means making fun of people – in this case, making fun of real life events and criticizing these events and real people. The magazine was started by two college students who sold it to two other people in 1989.
Eventually, The Onion started its own website in addition to printing out a weekly magazine. The Onion became famous for making up funny, fake headlines, or titles of news stories, and then of course inventing a fictional story to go with the funny headline. The stories make fun of almost everything you can think of in American news, in American culture.
Unlike other print publications, other magazines and newspapers in the U.S., The Onion has been increasing the number of readers it has over the years. In fact, in 2007 it started The Onion News Network, which is basically an “imitation,” or copy, of CNN, a popular 24-hour news network. Of course, the news on The Onion News Network is mostly made up, but it is quite funny.
I guess one of the differences between Mad Magazine and The Onion is that The Onion is probably a little bit more sophisticated in its humor, a little more adult in the sense of being a little more clever – even a little intellectual sometimes – in the jokes that it makes versus Mad Magazine. But both of them make fun of the news, and if you’re interested in finding out what Americans think is funny, you can try looking at those two publications.
Now let's answer a few of your questions.
Our first question comes from Hulya (Hulya) in Turkey. The question has to do with three words: “scanty,” “inadequate,” and “deficient.” “Scanty” (scanty) is a very small amount of something – not very much, not enough for what you want. You could have a “scanty supply of water,” for example – not enough water, insufficient water. “Inadequate” (inadequate) is related to scanty. It means not being enough or not good enough for what you need or require.
“Inadequate” means not adequate. If something is “adequate,” it's enough. If it's “inadequate,” it isn't enough. “Deficient” (deficient), like “scanty” and “inadequate,” also means not having enough of something, usually of some ingredient or some quality that you would like. We might talk about someone's diet – the food they eat – as being “deficient in vitamins.” It doesn't have enough of the vitamins. All three words, then, are related to not having enough of something. They're used in different contexts.
Typically, if you use “scanty,” you're talking about a small amount of something. “Inadequate” doesn't necessarily mean you have a small amount of something; it means you don't have enough of something for whatever it is you wanted to do. So, you could have a million gallons of gasoline, but if you need ten million gallons of gasoline, then a million is “inadequate” – it's not enough. “Scanty” usually refers also to something physical – not always, but it often refers to something physical. You could talk about, for example, someone walking around in “scanty clothing,” meaning they don't have very much clothing on.
“Inadequate” is a little more general term and refers again to not having enough of something in order to do what you want to do. “Deficient” is similar to “inadequate,” but it's not quite as common. You’ll more often hear “deficient” when people are talking about medical issues, for example. When people don't have enough of a certain vitamin or mineral, doctors may talk about “deficiency,” or a person being “deficient” in certain vitamins.
Our next question comes from Akira (Akira) in Japan. Akira wants to know the definitions of the words “inquiry,” “investigation,” and “research.”
“Inquiry” (inquiry), which could also be pronounced “inquiry,” means a request, typically for information – when you are trying to find the truth about something. It can be used in a very specific way when you are just basically asking a question. You can talk about, “I have to make an inquiry about the flight schedule for my plane” – I'm going to ask someone a question about that. It can also be used more generally by, for example, the government, which may be investigating a certain person or a certain situation. That could also be called an “inquiry,” or “inquiry” – however you want to pronounce it.
An “investigation” (investigation) is typically a formal examination or a formal look at some particular problem. An investigation would be something that the police, for example, would carry out, or would do when someone commits a crime. They would investigate it. They would look into it. The things that they are doing collectively could be called an “investigation.” You'll see this word especially when it relates to the police or to some government organization which is investigating, or looking into, something.
“Research” (research) is an investigation usually related to some sort of scientific or academic purpose. We talk about scientists doing research to try to find the cure for cancer, or we could talk about a high school student doing research in order to write his paper. He would go to the library – or nowadays, he would just Google and find somebody who wrote a paper already and then download it and give it to his teacher and say, “Here – here's my paper.” No. You shouldn't do that. But that's what “research” refers to. It refers to a scientific or an academic investigation, specifically.
You can use the word more generally. I could talk about “researching” the best price for my new television. That is also possible. “Research” in that example is a verb. It can also be used as a noun. “Investigation” is a noun. The verb is “investigate.” “Inquiry” is a noun. The verb is “to inquire” (inquire).
“Inquiry” is a somewhat formal word that is often used in place of “question.” “I need to make an inquiry into the reasons why I did not get my refund from the credit card company.” “Investigation” is often something that is done by the police or some government organization in order to find the answer to some problem or some question. And “research” is associated with academic or scientific investigations. Those are the most common uses of those three terms.
Finally, Gogao (Gogao) – my apologies for mispronouncing your name – from Brazil would like me to explain an expression which I often use on the Café: “so-called.” Well, “so-called” is used to indicate the name of something that people commonly or usually use, even if it's not the correct or official name. “So-called” is also used to refer to the incorrect or the false name for something.
Let me give you an example. In the first meaning, when we are using “so-called” to indicate the common name for something, you are telling people what is the most typical term or word that is used for this idea or concept or thing. I could refer, for example, to the Academy Awards – the awards given to the best movies every year here in Hollywood – as being the “so-called Oscars.”
However, the more common use of this expression “so-called” is when you are telling the person that you don't really think this is the correct name, or you don't even think that this is true. So, I might refer to Lady Gaga as a “so-called artist.” That means I don't really think she is an artist. (It’s just an example. Don't get angry if you like Lady Gaga.) “So-called” could be used to describe anything that you don't think deserves, perhaps, that name.
If two people are fighting each other, and one person wins but he's also very badly hurt, we could talk about the “so-called winner.” We’re not really calling this person a winner or indicating that he's a winner, not in the full sense of the word. I use that expression, as the questioner points out, many times on the Café. I’ll try to be a little bit more careful about that and indicate which of those two meanings I am trying to communicate to you when I'm explaining things.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. Email us and we'll do our best to try to answer it on a future Café.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
to be drafted – to be required by one’s own government to join and fight with the military forces during a war
* In the 1970s, many young men were drafted to fight in the Vietnam War.
stress – feeling pressure and anxiety; a reaction to difficult events that makes a person emotionally unstable and tired
* Yumin had a lot of stress at work because she had three big projects due at the same time.
first person – when a book is written as though the main character is speaking directly to the reader
* The book, written in first person, began: “Let me tell you about my life.”
slang – conversational and informal language or words that are used mainly in speaking and less in writing
* Many Americans say “bucks” as slang for “dollars.”
phony – not real or truthful; appearing other than one or something really is
* Li gave him a phony phone number because she didn’t want him to call her.
recluse – a person who lives alone and doesn’t have contact with other people
* When he got tired of people following him around, the famous actor became a recluse and spent the rest of his life living on top of a mountain in Peru.
seclusion – the act of staying away from other people
* Theo went into seclusion in his room every time he had a big test to study for so that he could concentrate.
comics – drawings with writing that tell a story and are intended to be funny or entertaining
* Batman and Superman are characters in comics who also appear in movies.
authority – a person or group of people who tells one what to do and expects one to do it
* Usually the authority in the household is the mother or father in the family.
circulation – public availability of a magazine or newspaper
* The New York Times has an international circulation.
satirical – describing humor is used to make fun of real life events, often showing one’s disagreement or negative opinion of someone or something
* The satirical television show made fun of the way that the president was handling a difficult situation.
imitation – a copy or replica of something; a fake
* Johann thought that the $800 diamond he bought was real but he later found out that it was an imitation worth only $5.
scanty – a small or insufficient in amount; not much and less than what is needed
* The employees all complain about the scanty benefits of working for this company.
inadequate – not being enough or good enough for what is needed or required; not adequate to meet a need or a requirement
* Her simple apology seems inadequate after all of the trouble she caused everyone.
deficient – not having enough of a specific quality or ingredient
* His doctor told him that he was Vitamin D deficient and should start taking a supplement each day.
inquiry – a request for information; a request for truth, information, or knowledge
* Who will be in charge of the inquiry into the security problems at the airport?
investigation – the process of trying to find out all of the details or facts about something to learn who or what caused something to happen
* The police investigation finally resulted in the arrest of the woman they believe stole the paintings.
research – a systematic investigation to establish facts or principles, usually in science; to collect information on a subject
* Scientists are researching ways to fight childhood cancers.
so-called – used to indicate a name that is commonly or usually used for something, though not its correct, official, or formal name; used to refer to an incorrect or false name for something
* Jaime is the so-called king of the sport, but he hasn’t won a match in over two years.
What Insiders Know
Famous Authors Publishing Only One Book
Authors who experience a great amount of success with one book often “follow it up” (do afterwards) by writing another book. It can be a sequel to their first book, meaning that a book continues the story, or develops a theme from the first book.
However, there are many authors who, despite achieving an incredible amount of success with their first books, chose not to write a second novel. For example, Margaret Mitchell, who wrote the novel Gone With the Wind is one of these authors. Gone With the Wind is one of the most “beloved” (liked by many people) books of all time and won the Pulitzer Prize for Fiction in 1937. Most people know it because it was “adapted into” (for a book or other piece of writing to be made into a performance or film) the classic film of the same name in 1939. Mitchell had “reportedly” (appeared to; was said to) disliked the attention that came with writing her novel, choosing not to write a sequel. Mitchell died in 1949 after being hit by a car.
Ralph Ellison, author of the classic novel The Invisible Man also wrote only one book. His book, which talks about racial “alienation” (feeling separated from others and not fitting in), won the National Book Award for Fiction in 1953, and is considered one of the greatest novels if the 20th Century. Ellison was working on a second novel when, in 1967, a fire in his home destroyed the “manuscript” (piece of writing before it is published).
Finally, Harper Lee, the author of the classic novel that deals with issues of racial “injustices” (unfairness) in the southern part of the United States called To Kill a Mockingbird also wrote only one novel. Lee’s book was awarded the Pulitzer Prize for Fiction in 1961. To Kill a Mockingbird continues to be one of the most popular books in modern American literature. In fact, in 2007, Harper Lee received the Presidential Medal of Freedom for her contributions in literature. Lee never revealed why she never wrote another novel.