= 1251
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,251 – Getting a Confession.
This is English as a Second Language Podcast episode 1,251. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. You can also take a look at our ESL Podcast Store on our website, and like us on Facebook at facebook.com/eslpod.
This episode is a dialogue between Andy and Diane about getting someone to admit he did something wrong – a confession. Let’s get started.
[start of dialogue]
Andy: I got it! I got a confession.
Diane: You got a confession out of that suspect? How did you do it? We’ve been after that guy for days.
Andy: I put the pressure on and he buckled.
Diane: Did you make threats?
Andy: Of course I made threats. It’s an interrogation, not a tea party.
Diane: The confession is no good if it’s coerced.
Andy: I may have gone over the line a little, but who’s to know?
Diane: He knows and any half-decent lawyer will make mincemeat out of that confession. He’ll get it thrown out of court in a heartbeat.
Andy: I leaned on him a little hard, but it’s not like I put the screws on him.
Diane: You have a lot to learn.
Andy: Do you think I should go back in there and talk to him?
Diane: Stay out of there. You’ve done enough damage. Rookies!
[end of dialogue]
Andy begins our dialogue by saying to Diane, “I got it! I got a confession.” Here, “to get a confession” means to get someone else to make or give you a confession. A “confession” (confession) is when you say that you did something wrong – when you state that you have broken the law, for example, or done something that you should not have done – in a legal context, in a legal situation. A “confession” is when someone who broke the law tells the police that he is guilty, that he broke the law.
The word “confession” is also used in some Christian churches to refer to a formal act of asking for forgiveness and what’s called “absolution” of having done something wrong. But here we’re just talking about a confession to the police. Diane says, “You got a confession out of that suspect?” A “suspect” (suspect) is a person who is believed to have committed a crime or broken a law, but we don’t have any proof or evidence yet, or at least not very much. A suspect is someone the police believe is guilty of a crime.
Diane says, “How did you do it?” How did you get a confession out of or from that suspect? “We’ve been after that guy for days.” “To be after” someone means to be trying to get information from someone or trying to catch or find someone. “To be after” can also be used to mean simply to be trying to reach a certain goal or a certain objective. “I am after a victory.” I am trying to get, I am pursuing, a victory. Here, Diane refers to being “after that guy” in the sense of trying to get him to make a confession.
Andy says that he “put pressure on” the suspect and “he buckled.” “To put pressure on” someone is to try to influence someone by doing something that would persuade him to take the action you want him to take. Andy says he “put pressure on” the suspect and “he buckled.” “To buckle” (buckle) here refers to doing something that you don’t really want to do because another person is forcing you or pressuring you to do it.
If your daughter keeps asking for ice cream, and she does it over and over and over and over again, eventually you might buckle. You might say, “Oh, okay. I’ll buy you an ice cream.” This is a case where a suspect buckled under the pressure that Andy put on him. Diane says, “Did you make any threats?” A “threat” (threat) is when you tell someone that if he doesn’t do what you want him to do, you will do something bad to him. You will cause him injury or pain or something else that will make him change his mind.
Andy says, “Of course I made threats.” He says, “It’s an interrogation, not a tea party.” An “interrogation” (interrogation) is usually something that the police do with a suspect. They bring the suspect to the police station and they “interrogate” him. They ask him questions to see if he did anything wrong, or to get information from the person. In other countries, military services might also interrogate someone who is from another country, an enemy country.
A “tea (tea) party” is, literally, a social gathering, a small party you have with friends at which you would drink tea and have perhaps little pieces of cake. “Tea parties” are much more common in countries outside of the United States. We might think of Great Britain, for example, where they have afternoon tea. A tea party would be a little more formal of an event. The idea in this expression, however, is that a tea party is a nice, friendly get-together, whereas an interrogation is not. That’s why Andy says, “It’s an interrogation, not a tea party.” We were not there to have fun.
Diane, however, says, “The confession is no good if it’s coerced.” The verb “to coerce” (coerce) means to force someone to do something or say something often because you are threatening that person with some sort of pain or harm. Andy says, “I may have gone over the line a little, but who’s to know?” Diane says the confession is no good, meaning the police can’t use it, if it was “coerced” from the suspect – if Andy did something to force the suspect to confess.
Andy says he may have “gone over the line” (line). The expression “to go over the line” means to do more than what you should do, or to do more than what is acceptable. In this case, he may have coerced the suspect, making the confession no good. Andy says, “I may have gone over the line” – it was possible, that is – “but who’s to know,” meaning no one will know if we don’t tell anyone. Diane says, “He knows” – the suspect knows – “and any half-decent lawyer will make mincemeat out of that confession.” “Half-decent” means pretty good – someone who is not the best but good enough.
Diane is saying that even a lawyer who isn’t very good “will make mincemeat out of that confession.” “To make mincemeat (mincemeat) out of” something is to destroy it, to defeat it. We often use this expression in talking about defeating someone’s argument or making someone’s argument look to be incorrect. It might also be used in the sense of physically attacking another person. “That six-foot-five man will make mincemeat out of anyone who tries to fight him.”
The verb “to mince” (mince) in this case means to chop up or to break up into smaller pieces. “Minced meat,” then, is chopped-up beef. I think in American English we would probably call it something like “ground beef.” In British English, it’s more likely to be called “minced meat” or “mincemeat.” Although, just to make things even more confusing, there is actually a dish – it’s a kind of pie – called “mincemeat pie” which doesn’t have any beef in it. It’s sweet. It’s made with things like raisins. That’s a British food that is eaten often during Christmastime. But back to our story . . .
Diane says the suspect will get the confession “thrown out in court in a heartbeat” – or I guess, technically, the lawyer will get it “thrown out of court.” To have something “thrown out of court” (court) means to have a judge say that it can’t be used against the person in a criminal or any other kind of legal trial. So, if evidence is “thrown out of court,” the judge says no, you cannot use that particular piece of evidence against this person – perhaps because, as in this case, it was gathered illegally.
There are rules about how you can get information that will be used against a person in a trial, and using “coercion” to get a confession breaks one of those rules, so the judge will “throw it out of court.” Diane says the confession will get “thrown out of court in a heartbeat” (heartbeat). “In a heartbeat” means very quickly. The verb “to beat” is used to describe the motion that your heart goes through when it pumps, and of course, your heart pumps many times a minute, so it’s a very short amount of time. “In a heartbeat,” then, means quickly.
Andy says, “I leaned on him a little hard, but it’s not like I put the screws on him.” “To lean (lean) on” someone can mean a couple of different things. Here it means to try to influence or coerce someone. “To lean on” can also mean to get support from another person, so it has, in many ways, two opposite meanings. “To lean on” means in this case to pressure someone, but you could also say, “I lean on my friend.” He helps me. He supports me. “To put the screws (screws) on” someone means the same thing as “to coerce” someone – to force someone to do something by threatening that person.
Diane just says, “You have a lot to learn,” meaning Andy is still not very good at what he does. Andy says, “Do you think I should go back in there and talk to him?” Diane says, “Stay out of there. You’ve done enough damage,” meaning you’ve already made the situation bad enough. I don’t want you going in there and making it worse. Then she ends our dialogue by saying, “Rookies!”
A “rookie” (rookie) is a person who is just starting to work in a certain area or field. We talk about “rookie players” on a team, on a professional baseball team. These are players that are just starting. It’s their first year. New police officers who don’t have a lot of experience are sometimes called “rookies” or “rookie cops,” and that’s the case with Andy. He obviously doesn’t have very much experience being a police officer yet.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Andy: I got it! I got a confession.
Diane: You got a confession out of that suspect? How did you do it? We’ve been after that guy for days.
Andy: I put the pressure on and he buckled.
Diane: Did you make threats?
Andy: Of course I made threats. It’s an interrogation, not a tea party.
Diane: The confession is no good if it’s coerced.
Andy: I may have gone over the line a little, but who’s to know?
Diane: He knows and any half-decent lawyer will make mincemeat out of that confession. He’ll get it thrown out of court in a heartbeat.
Andy: I leaned on him a little hard, but it’s not like I put the screws on him.
Diane: You have a lot to learn.
Andy: Do you think I should go back in there and talk to him?
Diane: Stay out of there. You’ve done enough damage. Rookies!
[end of dialogue]
Our scriptwriter is no rookie. She has a lot of experience writing wonderful scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
confession – an admission of guilt; a statement that one has committed a crime, broken a law, or done something wrong
* The little girl made a confession that she had told the teacher a lie.
suspect – a person who is believed to have committed a crime or broken a law, but without any clear proof or evidence
* The police have identified a few suspects and are conducting interviews with each of them.
after – pursuing; trying to get information from someone; trying to influence someone’s actions or behavior
* I was after a perfect score, but I guess I should be happy with a 96 out of 100.
to put the pressure on – to influence someone in a very strong, controlling way; to use a lot of persuasion and influence to try to get what one wants
* Professor Ringold’s weekly quizzes really put the pressure on students to do all of the reading before coming to class.
to buckle – to do something one does not want to do in a difficult situation because one has been under too much pressure
* As soon as we saw the tears in his eyes, we knew he would buckle and tell us everything we wanted to know.
threat – a statement that one will cause pain, injury, damage, or death to another person, used to change or control his or her behavior
* A: I’m going to get you for what you did to me.
B: Is that a threat?
interrogation – a session in which one asks a lot of forceful, uncomfortable questions, trying to get the truth from someone who does not want to give the information
* The soldiers know to keep quiet during an interrogation by the enemy.
tea party – an enjoyable afternoon spent drinking tea and eating baked goods with friends or family, often used to refer to any enjoyable experience
* Getting the children to bed after all that candy was no tea party.
to coerce – to force someone to do or say something, especially by making threats or causing pain
* The land developers harassed Rick to try to coerce him into selling his home.
to go over the line – to take something to an extreme; to do more than the acceptable amount of something; to ignore the limits of something
* Thomas really went over the line by telling those racist jokes at work.
half-decent – pretty good at one’s job or at doing something; competent; capable
* These pastries are delicious! I guess Paul is a half-decent baker.
to make mincemeat – to destroy something; to defeat someone easily in an argument or contest
* This proposal lacks facts and figures. The management team is going to make mincemeat out of it.
to throw (something) out of court – for a judge to refuse to allow something to be heard or discussed during a court case, usually because it is not relevant or was obtained in an illegal way
* The police officers found the murder weapon in the apartment, but because they didn’t have legal permission to enter that apartment, the evidence was thrown out of court.
in a heartbeat – very quickly; almost immediately
* We saw the smoke and knew in a heartbeat that there was a fire in the kitchen.
to lean on (someone) – to influence, persuade, or coerce someone; to put a lot of pressure on someone as a way to change or control his or her words or actions
* Myung’s parents are leaning on him to become a doctor, but his passion is music.
to put the screws on (someone) – to force someone to do something through the use of threats; to coerce
* The reporter used secret photos of the politician’s personal life to put the screws on him to get insider information.
rookie – an amateur; a person who has little or no experience; someone who is just starting to work in a particular job or field
* Every rookie makes mistakes. You’ve got to forget about it and move on.
Comprehension Questions
1. Why does Andy say, “I got it”?
a) Because he figured out who committed the crime.
b) Because he made the suspect cry.
c) Because he heard the suspect say that he broke the law.
2. What is a rookie?
a) Someone who leads a successful interrogation.
b) Someone whose evidence is thrown out of court.
c) Someone who has very little experience doing something.
Answers at bottom.
What Else Does It Mean?
after
The word “after,” in this podcast, means pursuing, or trying to influence someone’s actions or behavior: “All the athletes are after gold medals.” The word “after” also means to want what another person has: “I think she’s after my job!” The phrases “day after day” or “year after year” mean repeatedly over a long period of time: “Day after day, Blake’s health continues to worsen.” The polite phrase “after you” is used to allow someone else to have or do something first: “He held open the door and said, ‘After you,’ while gesturing for us to walk in before he did.” Finally, the phrase “to take after” means to resemble another person in some way, especially when talking about a child and parent: “Wow, Chloe is really taking after her parents. She looks like them and even talks like them.”
half-decent
In this podcast, the phrase “half-decent” means pretty good at one’s job or at doing something: “Kristin is a half-decent downhill skier, but she isn’t an Olympic athlete.” The word “decent” also means with sufficient or enough quality: “The home has a decent kitchen, but the bathrooms need to be updated.” Or, “Where can we eat some decent Korean food in this city?” When talking about people, “decent” describes someone who is moral and ethical and meets society’s expectations: “He’s a good, decent man, but I just don’t love him.” Finally, the word “decent” is sometimes used humorously to mean that someone is wearing enough clothing to cover the private parts of his or her body: “It’s okay to come in. We’re all decent.”
Culture Note
Brown v. Mississippi and Due Process
In 1936, a U.S. “Supreme Court” (the highest, most powerful court in the country) “ruled” (made a legal decision) in Brown v. Mississippi that any confession obtained through “violent” (causing pain or injury) police action cannot be “entered as evidence“ (presented to the court to help the jury and judge reach a legal decision). This decision supports the Fifth and Fourteenth “Amendments” (additions to a legal document) of the U.S. “Constitution” (the nation’s most important legal document, which established the U.S. government), which require “due process,” or the idea that the government must respect the “legal rights” (what people are entitled to under the law) of all individuals.
This particular case was about the 1934 “murder” (when someone kills another person) of a white “planter” (a farmer who owns a lot of land). Three black men were “accused” (said to have done something wrong) of the murder and were arrested for it. During the court “trial” (when arguments are heard in order to make a legal decision), the “prosecution” (the people who are trying to prove that someone did something wrong in court) presented the three men’s confessions, but it was clear that those confessions were obtained only after the men were “whipped” (beaten badly with long ropes or pieces of leather) by the police officers.
In the original trial, the confessions “stood” (were considered valid) and the men were “sentenced to death” (were ordered to be punished by death). “On appeal” (when the case was heard again at a different, higher court) at the U.S. Supreme Court, the decision was “reversed” (changed), but the three men still had to “serve time” (spend time) in prison.
Comprehension Answers
1 - c
2 - c