= 1252
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,252 – Reneging on a Promise.
This is English as a Second Language Podcast episode 1,252. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store with some additional courses in business, daily, and cultural English we think you’ll enjoy.
This episode is a dialogue between Jean-Paul and Charlene about someone who says he’s going to do something, who promises to do something, and then doesn’t. Let’s get started.
[start of dialogue]
Jean-Paul: What’s going on? I thought it was a done deal.
Charlene: I think you misunderstood. The last time we talked, I said I would think about partnering up, but now that I have, I’m going to beg off.
Jean-Paul: What you said was that you were agreeable to the idea and that we would work out the details later. Now you’re backtracking?
Charlene: I would never renege on a promise. If I gave my word, I would follow through. In this case, I didn’t.
Jean-Paul: I’m really surprised by your denial. I didn’t have you pegged as someone who backs out of deals.
Charlene: All I can say is that we don’t see eye to eye. Let’s agree to disagree and leave it at that.
Jean-Paul: That’s easy for you to say. Your failure to honor your promise is going to put me in a very awkward position.
Charlene: How’s that? We only spoke yesterday.
Jean-Paul: I may have made some promises of my own and now I’ll have to get out of them somehow.
Charlene: May I make a suggestion?
Jean-Paul: What? Deny, deny, deny?
Charlene: Well, it’s worked for me.
Jean-Paul: Oh, the nerve of some people!
[end of dialogue]
Jean-Paul begins our dialogue by asking Charlene, “What’s going on?” This is a question that could mean a couple of different things, depending on how you ask it.
“What’s going on?” means “What is happening?” If you say it to a friend of yours, it may just mean “How are you?” “How are things?” “What’s new in your life?” But if you say it to someone with a certain intonation, such as “What’s going on?” then you are asking about a problem. You are asking for the reason why something is not going well, perhaps.
Jean-Paul uses this second meaning of the expression. He is clearly confused about what is happening. He says, “I thought it was a done deal.” We don’t know what “it” was. Obviously some sort of agreement. A “done deal” (deal) is something that you have agreed to, something that has been decided upon and about which you don’t expect there to be any changes. A “done deal” is something that has been “finalized,” we might say – some agreement that everyone has already approved.
Charlene says, however, “I think you misunderstood.” Charlene is telling Jean-Paul that it wasn’t a done deal – that they had not finished their discussions about whatever this agreement was. Charlene continues, “The last time we talked,” meaning the previous time we talked, “I said I would think about partnering up, but now that I have, I’m going to beg off.” “To partner (partner) up” is a two-word phrasal verb meaning to agree to work with another person – to make that person your partner, the person you work with.
Charlene says she was thinking about becoming Jean-Paul’s partner, presumably his business partner, but now that she has thought about it more, she says she’s going “to beg (beg) off (off).” “To beg off” means to decide not to do what you were going to do. You’re asking, in a sense, to be excused from some promise or commitment you made, or perhaps you are simply changing your mind about what you want to do. Normally “to beg” someone means to ask something from that person. Here the idea is that you are asking the permission, perhaps, of that person to not do what you said you were going to do.
Jean-Paul is not very happy. He says, “What you said was” – meaning the last time we spoke, you told me – “that you were agreeable to the idea and that we would work out the details later.” “To be agreeable (agreeable) to” something means that you like the idea, that you are okay with supporting it. You think it is a good thing. Jean-Paul says that Charlene was “agreeable to the idea” of being his partner, and that he and Charlene “would work out the details later,” meaning they would figure out the specifics of their agreement later on.
“Now,” Jean-Paul says, Charlene is “backtracking.” “To backtrack” (backtrack) means to change your mind about what you had already agreed to, to try to undo or reverse what has already been done. If you say you are going to buy something for 10 dollars, and then 10 minutes later you say, “No, I don’t think I will. I’ll only pay five dollars,” you are backtracking. You are trying to go back on, or to change your mind about, something you have already promised to do. Charlene, however, disagrees. She says, “I would never renege on a promise.”
“To renege (renege) on” something is to not do what you have promised to do. It’s to break a deal or to break a commitment. Charlene says, “If I gave my word, I would follow through. In this case, I didn’t.” “To give your word” to someone means to make a promise to someone. The idea, however, when you say “I give you my word” is that it is something personal – that even though you are not signing a piece of paper, you are making this promise to the person even without a contract, just “on your word,” just based on your words that are spoken.
However, Charlene says that she didn’t give her word. If she had, however, she would have followed through. “To follow through” (through) means to do what you say you were going to do, to keep your promise. Jean-Paul says, “I’m really surprised by your denial.” A “denial” (denial) is when you say no to someone or when you say that something didn’t happen. If someone says, “I saw you last night with someone other than your girlfriend,” and you say, “No, that wasn’t me,” that’s a denial. You’re saying no, it wasn’t true. Charlene is saying that she did not give her word to Jean-Paul. That’s a denial.
Jean-Paul says, “I didn’t have you pegged as someone who backs out of deals.” “To have someone pegged” (pegged) as a certain thing is to believe that someone has certain characteristics. If someone says, “I didn’t have you pegged as a beer drinker,” that person means that he didn’t think you were the kind of person who drank beer. Jean-Paul says he didn’t think that Charlene was the kind of person who “backs out of” deals. “To back out of” something is to break a promise, to renege on a promise or commitment.
Charlene says, “All I can say is that we don’t see eye to eye.” “All I can say” means “The only thing I can tell you at this point” is that we don’t see eye to eye. “To see eye (eye) to eye” means simply to agree with another person, to think the same as another person, or to come to an agreement with another person. That’s why she says, “Let’s just agree to disagree and leave it at that.” The expression “to agree to disagree” means you are not going to come to an agreement, but you’re not going to fight about it anymore either. You’re going to stop arguing about it or trying to come to an agreement.
So, if two people have different political opinions and they discuss those opinions, at the end of their discussion they may say, “Well, let’s agree to disagree.” In other words, we don’t agree on anything about politics, so we’ll just stop arguing now. That’s also what Charlene means by the expression “to leave it at that.” “To leave it at that” means to stop your conversation even though you have not yet come to an agreement.
Jean-Paul says, “That’s easy for you to say,” meaning that’s easy for you but not easy for me. “Your failure to honor your promise is going to put me in a very awkward position,” he says. “Failure (failure) to honor (honor) a promise” means the same as to renege on your promise – not to do what you said you were going to do. Jean-Paul thinks that Charlene has failed to honor her promise, and this is going to put him or place him in a “very awkward (awkward) position.” An “awkward position” would be a situation that would be difficult for you, that would make things hard for you.
Charlene doesn’t understand. She says, “How’s that?” meaning please explain what you mean. “We only spoke yesterday,” she says. Jean-Paul responds, “I may have made some promises of my own and now I’ll have to get out of them somehow.” “To get out of” something means to find a way not to have to do what you said you were going to do – in other words, to renege on a commitment. So what happened here was that Jean-Paul went and made some promises to other people based on what Charlene had promised to him.
Charlene says, “May I make a suggestion?” Jean-Paul says, “What? Deny, deny, deny?” In other words, Charlene is suggesting that he do to others what Charlene did to him – simply lie and say that he never made those promises. Charlene is saying “Yes, that’s what I just did. I basically lied. I denied that I had made a promise to you.”
Jean-Paul obviously is not very happy at this point, after Charlene now admits – she now says that basically she lied to him. He says, “The nerve of some people!” The expression “the nerve (nerve) of some people” is used to express your frustration at someone else’s behavior – your shock and disapproval of the way someone else is acting, especially towards you. Jean-Paul is saying that he can’t believe how much of a liar Charlene is.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jean-Paul: What’s going on? I thought it was a done deal.
Charlene: I think you misunderstood. The last time we talked, I said I would think about partnering up, but now that I have, I’m going to beg off.
Jean-Paul: What you said was that you were agreeable to the idea and that we would work out the details later. Now you’re backtracking?
Charlene: I would never renege on a promise. If I gave my word, I would follow through. In this case, I didn’t.
Jean-Paul: I’m really surprised by your denial. I didn’t have you pegged as someone who backs out of deals.
Charlene: All I can say is that we don’t see eye to eye. Let’s agree to disagree and leave it at that.
Jean-Paul: That’s easy for you to say. Your failure to honor your promise is going to put me in a very awkward position.
Charlene: How’s that? We only spoke yesterday.
Jean-Paul: I may have made some promises of my own and now I’ll have to get out of them somehow.
Charlene: May I make a suggestion?
Jean-Paul: What? Deny, deny, deny?
Charlene: Well, it’s worked for me.
Jean-Paul: Oh, the nerve of some people!
[end of dialogue]
Our scriptwriter – Dr. Lucy Tse – and I have partnered up to give you what we hope is some useful information, some useful help in improving your English.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
done deal – something that has already been agreed to and decided upon, with no changes expected
* The buyers have agreed to pay $8,500 for the used car. It’s a done deal, and we’ll give them the keys this afternoon.
to partner up – to agree to do something with another person as a team of two
* The teacher told the students to partner up for the book project.
to beg off – to ask to be excused from a commitment so that one no longer has to do what one had promised to do; to ask for permission to not do something
* At the last meeting, Shawn agreed to serve as the organization’s president, but then he spoke with his wife, who disliked the idea, and he had to beg off.
agreeable – open-minded and willing to support and accept something; not opposing something
* Are you agreeable to the idea of relocating overseas?
to backtrack – to undo what had already been done or agreed to; to reverse or change one’s opinion or work
* Dad backtracked on his promise to attend our school performance when he couldn’t get permission to leave work early.
to renege on (something) – to not do something that one has promised to do; to break a commitment, contract, deal, or promise
* What financial penalties will they face if they renege on the agreement?
a promise – a commitment to do something or to act a certain way
* When we got married, we made a promise to love each other for better or for worse, for richer or poorer, and in sickness and in health.
to give (one’s) word – to make a promise; to state that one will do something and make a commitment to doing it
* I give you my word that I will take care of your child while you’re in the hospital.
to follow through – to do what one has said one would do; to keep a promise or commitment; to continue or extend one’s work until it is complete
* The committee members all agreed to complete their work within two weeks, but unfortunately none of them followed through.
denial – a “no” statement; a rejection of what another person has said; a refusal to believe what has happened
* Most people don’t believe the city official’s denial of corrupt activities.
to have (someone) pegged as – to believe that someone has certain characteristics and will act or think in a certain way
* Abraham is a highly technical researcher, so we never had him pegged as an artist, but we were surprised to learn that he’s an award-winning painter.
to back out – to break a promise or not fulfill a commitment; to change one’s mind and not continue doing something; to break a contract
* We’ve already paid the race fee, so you can’t back out now!
to see eye to eye – to agree with another person; to reach the same conclusion as another person
* Dad and I never see eye to eye, so it’s best for us to avoid talking about politics.
to agree to disagree – to accept that two people will never reach an agreement, and to stop trying to persuade or convince the other person
* Sometimes the secret to a happy marriage is to agree to disagree.
to leave it at that – to stop a conversation or argument even though it has not reached a satisfying conclusion; to not continue to do something
* We don’t agree, but I’m tired. Let’s talk no more about it and leave it at that.
failure to honor – when one does not keep a promise; when one has not met a commitment, often relating to a policy or service
* By selling you a broken air conditioner, the company failed to honor its commitment to quality and customer service.
awkward – uncomfortable, unusual, and making it difficult for people to know how to proceed
* The bride changed her mind, leaving her fiancé in a very awkward position.
to get out of (something) – to find a way to not have to do what one said one would do
* I know you’re supposed to help your friend move this weekend, but can’t you get out of it so that we can go to the beach instead?
the nerve of some people – a phrase used to express frustration, shock, and disapproval over someone’s behavior or actions
* That guy just pushed his way to the front of the line? The nerve of some people!
Comprehension Questions
1. Who is best at keeping a promise?
a) Someone who reneges on a promise
b) Someone who backs out of deals
c) Someone who gives his word and follows through
2. What does Charlene mean when she says, “We don’t see eye to eye”?
a) They are different heights.
b) They have different opinions.
c) They aren’t making eye contact.
Answers at bottom.
What Else Does It Mean?
to beg off
The phrase “to beg off,” in this podcast, means to ask to be excused from a commitment so that one no longer has to do what one had promised to do: “I know I agreed to take care of your dog while you’re on vacation, but my landlord won’t let me have pets, so I have to beg off.” The verb “to beg” means to plead or to ask for something from another person, especially money or food: “The streets are filled with homeless people who are begging the tourists for money.” Finally, the very formal and polite phrase “I beg your pardon” means “excuse me” or “sorry”: “I beg your pardon, but could you please tell me how to get to the art museum?”
to leave it at that
In this podcast, the phrase “to leave it at that” means to stop a conversation or argument even though it has not reached a satisfying conclusion: “We’re never going to reach an agreement, so let’s leave it at that and change the subject.” The phrase “to leave (someone) in peace” means to leave someone alone, without other people: “The doctors say that too many visitors will make Hassan tired. Let’s leave him in peace for a few hours.” The phrase “to leave (someone) with no choice” means to force someone to do something: “Your actions have left me with no choice but to tell your boss what you did.” Finally, the phrase “to leave (something) until the last minute” means to procrastinate, or to do something at the last possible moment: “Why did you leave all your studying until the last minute?”
Culture Note
The Legality of Oral Contracts
In the United States, most “contracts” (legal agreements) are written. But “contrary to popular belief” (what most people believe is not actually true), some “oral contracts,” or verbal agreements that are spoken but not written down, can also be “legally binding” (with the power of the law making sure that the agreement is followed). People sometimes say, “An oral contract is as good as the paper it’s written on,” meaning that a verbal agreement has no value, but in many “jurisdictions” (areas with legal power to make laws and legal decisions), they are “enforceable” (people can be held accountable and forced to comply with the agreement).
To be legally binding, an oral agreement must have “witnesses” (people who observe and see something happen, but do not participate in it). Having a witness is the only way to make an oral contract “provable” (demonstrating the existence of the agreement), since nothing has been put in writing.
Oral contracts aren’t allowed in all situations. In most states, certain types of contracts must be put in writing. For example, any contracts regarding the buying and selling of “real estate” (land and buildings) requires a written agreement. Goods that “change hands” (are passed from one person to another) upon death must also be “governed” (controlled) by a written contract.
Some states “establish” (create) restrictions, such as requiring that agreements involving more than a certain dollar amount, or more than a certain “term” (the amount of time covered by an agreement) must be put in writing.
Comprehension Answers
1 - c
2 - b