= 1257
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,257 – Repairing Damage to an Auto Body.
This is English as a Second Language Podcast number 1,257. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store which has additional courses in business English, cultural English, and everyday English.
This episode is a dialogue between Miles and Yuki about getting your car fixed when someone has hit it. Let’s get started.
[start of dialogue]
Miles: It’s something, isn’t it?
Yuki: Yeah, it’s something all right. Where did you get this heap?
Miles: My uncle sold it to me. This car has been sitting in his garage for years and he finally said I could have it for a good price. I need some auto body work done on it. There’s a little damage and I want to make it look good again.
Yuki: A little damage?! The bumpers are falling off and the frame is bent. Was this car in an accident? I’m worried about its structural integrity.
Miles: It was in a small accident, but none of these cosmetic things affects how it runs.
Yuki: I mean there are dents and dings everywhere, and paint scratches so deep you might need to get a whole new paint job.
Miles: I’m sure you can work your magic on it and make it look new again.
Yuki: Wait a second. There’s rust all over the undercarriage.
Miles: When do you think you can have it ready for me to pick up?
Yuki: It’s ready now.
Miles: Now?
Yuki: Yes, this car is ready for you to pick up and take to a salvage yard!
[end of dialogue]
Miles begins with saying, “It’s something, isn’t it?” The meaning of this expression depends on how it is said and the context or situation in which it is said. It could mean it’s something really good. It’s something fantastic. It could also mean that it isn’t very good. I think Miles says it in a way that suggests that it is something good. He’s talking about a car that his uncle sold to him. Yuki, however, doesn’t agree. She says, “Yeah, it’s something all right.” The addition of that expression “all right” is used here to indicate that perhaps what the other person said isn’t correct or perhaps isn’t complete.
Yuki says, “Where did you get this heap (heap)?” “Heap” is usually a large number of objects that are on top of each other, that aren’t organized in any way. You could have a “heap of papers” – a bunch of or collection of papers on your desk that aren’t organized in any way. It looks rather messy. In this case, however, she’s referring to the car as being a collection of pieces that aren’t organized very well. It’s just another way of saying “this piece of junk” (junk), which is something you would normally throw away. If we use the word “heap” to describe a car, we mean it’s not a very good car.
Miles says, “My uncle sold it to me.” This car has been sitting in his garage for years and he finally said I could have it for a good price.” Miles says, “I need some auto body work done on it. There’s a little damage and I want to make it look good again.” “Auto body” refers to the outside of the car, or more specifically, work done to repair the way a car looks. So, if you say you need “auto body work,” you mean you need the outside of your car fixed. We’re not talking about the motor or the engine part of the car.
Yuki says, “A little damage?!” She is surprise that Miles is describing his car as having a “little,” or not very much, damage. She says, “The bumpers are falling off and the frame is bent.” The “bumpers” (bumpers) of a car are the parts that are in the front and the back that are supposed to protect the car if you get into an accident, if you hit some thing or some other car. “The bumpers are falling off,” she says, meaning they are about to come off of the car because they’re not attached properly or because they’re so old.
“The frame is bent” (bent), Yuki says. Something that is “bent” is something that is not straight the way it should be. The “frame” of a car is the basic structure of the car. If you can think of the car without any of the doors or engine or other parts that make the car run, that would be the “frame” of the car, sort of like your skeleton in your body consists of the bones in your body, and then you have everything around and on top of your bones. Well, the frame of the car is like the skeleton of the car.
“Was this car in an accident?” Yuki asks. “I’m worried about its structural integrity.” The “structure” (structure) of something is similar to the frame or skeleton of an object. It gives it its basic shape. “Structural integrity” (integrity) refers to how strong that structure is, how well that structure will survive, say, other damage. The “structural integrity” of a bridge refers to how strong the bridge is – whether the bridge is going to stay up or not. Yuki is talking about the structural integrity of the car.
Miles says, “It was in a small accident, but none of these cosmetic things affects how it runs.” “Cosmetic” (cosmetic) is an adjective that describes the way something looks. In this case, we might think of it as the outside part of the car – not how it functions, not how it works. Miles uses the verb “run” (run) to describe how the car functions. He says, “None of these cosmetic things,” or cosmetic damage, “affects” or has any influence on how the car operates, “how it runs.”
Yuki says, “I mean there are dents and dings everywhere, and paint scratches so deep you might need a whole new paint job.” A “dent” (dent) is created when you take something that is flat and you hit it, say with a hammer or another hard object. If you do that to a piece of metal, it will create a dent in the metal. It’s not a hole – it doesn’t go through the metal – but it bends the metal, causing a dent in the metal.
A “ding” (ding) is a very small dent in a car. If you park your car next to another car and the person in the car next to you opens his door and it hits the side of your door in a very strong or forceful way, it might cause a “ding” in the side of your door, a small dent. Yuki also mentions “paint scratches” (scratches). A “scratch” is a small line in a painted object. So, if you have red paint on the side of your car and there’s a scratch in it, you may see white – that would be the metal underneath the paint.
The scratches are so deep, Yuki says, that Miles “might need a whole new paint job.” A “paint job” is when you have to repaint, or put new paint on the entire car. A “deep scratch” is one that goes far into the metal so that it can’t be easily fixed by just putting a little paint on top of that area. Miles says, “I’m sure you can work your magic on it and make it look new again.” Apparently Miles is asking Yuki to do the auto body work. “To work your magic” means to use your skills in such a way as to make something better again or perfect again.
Yuki says, “Wait a second. There’s rust all over the undercarriage.” “Rust” (rust) is another word for what we could also refer to as “oxidation,” in a technical sense. It’s a reddish-orange powder that appears on metal when it has been damaged by having water on it. Rust is not a good thing for the metal, of course, because it can make the metal weaker. It can actually cause the metal to disintegrate or to break up into small pieces. The “undercarriage” (undercarriage) of a car is the bottom of the car, usually including the bottom of the frame and the wheels.
Miles says, “When do you think you can have it ready for me to pick up?” So we learn now that Yuki works at the auto body shop, the place where he is bringing the car to be fixed. He wants to know when Yuki can finish fixing it. Yuki says, “It’s ready now.” Miles says, “Now?” He’s confused because he just, of course, brought the car to Yuki. Yuki is making something of a joke. She says, “Yes, this car is ready for you to pick up,” meaning to take away, “and to take to a salvage yard.”
A “salvage (salvage) yard (yard)” is a place where there are a lot of old cars and other machines that no longer work and that are used only for their “parts” (parts), meaning people take the cars apart, or the other machines, and they reuse the different parts from those cars or machines for other things, or for other cars and machines. What Yuki is saying is that it is not possible to fix this old car, that it would be better for Miles simply to take it and perhaps sell it to the salvage yard since no one would want to drive the car anymore as it is.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Miles: It’s something, isn’t it?
Yuki: Yeah, it’s something all right. Where did you get this heap?
Miles: My uncle sold it to me. This car has been sitting in his garage for years and he finally said I could have it for a good price. I need some auto body work done on it. There’s a little damage and I want to make it look good again.
Yuki: A little damage?! The bumpers are falling off and the frame is bent. Was this car in an accident? I’m worried about its structural integrity.
Miles: It was in a small accident, but none of these cosmetic things affects how it runs.
Yuki: I mean there are dents and dings everywhere, and paint scratches so deep you might need to get a whole new paint job.
Miles: I’m sure you can work your magic on it and make it look new again.
Yuki: Wait a second. There’s rust all over the undercarriage.
Miles: When do you think you can have it ready for me to pick up?
Yuki: It’s ready now.
Miles: Now?
Yuki: Yes, this car is ready for you to pick up and take to a salvage yard!
[end of dialogue]
Our scriptwriter works her magic every week by writing us these wonderful scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
it’s something – a phrase used when one is shocked or surprised and does not know what to say about something, or does not know how to categorize or describe it
* A: Did you like the song Jacob wrote?
B: Well, it’s something! I’ve never heard anything like it before.
all right – a phrase used for emphasis, especially to indicate that another person’s description of something didn’t go far enough
* Meghan warned us that her new apartment was tiny, but I assumed there would be room for at least a mattress. It’s tiny all right!
heap – a disorganized pile; a large number of objects resting on each other without being neat, tidy, or organized
* If he folded his clothes instead of keeping them in a heap on the floor, they wouldn’t be so wrinkled.
auto body – work done to repair or improve the shape and exterior appearance of a car
* The accident wasn’t too bad. The car still works, but I need to take it to the auto body shop.
bumper – the horizontal part on the front and back of a car, used to provide protection during a collision
* While driving in reverse, I accidentally hit a post and the back bumper fell off.
frame – the strong, basic structure of a car, without the walls, windows, doors, seats, motor, and other parts
* When car manufacturers introduce new car models, do they always change the frames?
bent – referring to something that used to be straight, but is no longer straight because pressure was applied to it
* The cookie sheet is a little bent, but we can still use it for baking.
structural integrity – a measure of how strong a building, bridge, or another object is, including whether it can continue to support weight
* If we remove the wall between the dining room and the living room, will it damage the home’s structural integrity?
cosmetic – related to something’s appearance, not function
* They made a few cosmetic changes to the house when they moved in, like changing the paint color and removing some wallpaper.
to run – for a machine or car to function normally; for something to work as it should
* This laptop runs for about three hours if the batteries are fully charged.
dent – indentation; a part of a flat surface that is lower than the rest, caused by a collision or accident
* Rubio kicked the soccer ball so hard that it left a dent on the side of the house!
ding – a minor mark or dent on a car, boat, or other vehicle
* This old bicycle has a few dings, but it’s still in good condition and fun to ride.
scratch – a small line marked on the surface of something, usually caused by a sharp or pointed object scraping it
* If you clean your eyeglasses with normal fabric, you might create some scratches on the glass. Try using this special towel instead.
paint job – the colored surface of an object and work required to put that surface on the object; the decorative coating painted onto something
* Boats need a new paint job every few years to protect them from the damaging effects of salt water.
to work (one’s) magic – to use one’s skills to perform very well to do something that transforms an object or makes it more valuable or beautiful
* Once our editors work their magic on your manuscript, it will be ready for publication.
rust – oxidation; the reddish-orange powder that appears on steel or iron when it has been left out in the rain
* There is so much rust on this chair that it’s not clear what color it used to be.
undercarriage – the bottom of a vehicle; the wheels and the bottom parts of the frame of a car, train, or airplane
* Some branches got caught in the undercarriage while we were driving.
salvage yard – a large place where many old vehicles and appliances are stored so that they can be taken apart when parts are needed, or recycled
* Buying a new car door is too expensive, so we’ll go to the salvage yard to see if we can find a used one that is still in good condition.
Comprehension Questions
1. Which of these things is a cosmetic matter?
a) The structural integrity
b) The paint job
c) The undercarriage
2. Which of these problems can be prevented with paint?
a) Dents
b) Dings
c) Rust
Answers at bottom.
What Else Does It Mean?
body
The phrase “auto body,” in this podcast, means work done to repair or improve the shape and exterior appearance of a car, not related to the motor or other internal workings: “The insurance will cover the cost of repairing engine problems, but not auto body work.” The phrase “over (one’s) dead body” means that something is unacceptable and one will not allow it to happen: “My daughter wants to get a tattoo? Over my dead body!” The phrase “body language” refers to how we communicate meaning without words, through the movement and position of our body: “Theodore crossed his legs and turned away from his wife. His body language made it clear that he was angry with her.” Finally, the phrase “body count” refers to the number of people who have died: “They think the body count from the earthquake could be more than 1,200.”
to run
In this podcast, the verb “to run” means for a machine or car to function normally, or for something to work as it should: “The factory equipment has been running really loudly lately. Maybe we should have a mechanic check it.” The phrase “to run a bath” means to fill a bathtub with hot water: “She put on some classical music and ran a bath, looking forward to a relaxing evening at home.” The phrase “to run high” means for there to be a lot of emotion, tension, or anxiety: “Fear was running high as the company began to announce budget cuts and layoffs.” Finally, the phrase “to run for cover” means to quickly move to a place where someone will be safe: “We all ran for cover when the ice storm began.”
Culture Note
The National Institute for Auto Service Excellence (ASE)
The National Institute for Auto Service Excellence (“ASE”) is a national organization that provides “certification” (official documentation stating that one has met certain standards) for “shops” (stores) and individuals in the “auto service industry” (all the businesses that maintain and repair automobiles). It has existed since 1972 to help consumers identify which “mechanics” (people who repair cars) will do the best job repairing their cars.
In order to become a certified “automotive professional,” a mechanic must have two years of “relevant” (related to the field) work experience and pass several “exams” (tests), which cover everything from engine repair and “brakes” (used by a rider or driver to stop a vehicle) to heating and “air conditioning” (device in cars and homes used to cool the air) for cars, trucks, busses, and “specialty vehicles” (automobiles that don’t fit into any other category).
Today, there are a large number of ASE-certified professionals. When they earn their certification, they receive a shoulder “patch” (a piece of fabric or badge that can be sewn onto the shoulder of a shirt), a wallet card, and a printed certificate that can be “mounted” (placed in a frame and hung) and displayed on the wall at their workplace. People who have been certified for 25 years are “eligible for” (meet the requirements in order to have) the 25-Year Recognition “Medallion” (a heavy, flat, circular piece of metal, usually worn around the neck as an award).
In addition to training and certifying automotive service professionals, ASE educates consumers about how to maintain their cars and how to select the best auto repair shops. The ASE website also has a “searchable” (allowing people to find specific information) “database” (a large collection of digital or electronic information) of local repair shops where consumers can find ASE-certified professionals.
Comprehension Answers
1 - b
2 - c