= 1258
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,258 – Causes of Plane Crashes.
This is English as a Second Language Podcast episode 1,258. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website now (well, please) at ESLPod.com. Become a member of ESL Podcast and get access to all of our wonderful Learning Guides.
This episode is a dialogue between Angelica and Corey about what is always bad news, a plane crash – when a plane falls down out of the sky. Let’s get started.
[start of dialogue]
Angelica: So the book I’m writing starts with a plane crash.
Corey: What caused it?
Angelica: It doesn’t matter. That’s not part of the story.
Corey: But characters have backstories, so you should have a backstory for the plane crash.
Angelica: Okay, the plane crashed because of mechanical failure, or better yet, pilot error.
Corey: What happened? Was it because the pilot misread the instruments or had a problem navigating?
Angelica: I don’t know.
Corey: Maybe he or she was incapacitated due to an illness. What kind of illness?
Angelica: Forget it. Let’s say instead that it happened because of an act of God.
Corey: Like a lightning strike? That’s not very likely.
Angelica: Okay, how about some problem with the flight crew that caused the cabin to depressurize and the plane to go into a tailspin.
Corey: What was the problem with the fight crew?
Angelica: It doesn’t matter!
Corey: Maybe a member of the flight crew was a hijacker and it was an act of terrorism.
Angelica: Okay, let’s say that’s what happened. Happy?
Corey: But wait! Who was the terrorist? What were his aims and what was his cause?
Angelica: You know what? I think you should put that in your book!
[end of dialogue]
Angelica says to Corey, “So the book I’m writing starts with a plane crash.” Notice Angelica begins the sentence with the word “so.” “So” has become in English, in many cases nowadays, the same as “um” or “well” or other, what we call, “filler words” – words people use to begin a sentence that don’t really have any specific meaning. Angelica could have just said, “The book I’m writing starts with a plane crash.” “Plane” (plane) refers to a machine that flies in the air. A “plane” usually has two, what we call, “wings” (wings) which are like arms that extend or go out from the side of the plane.
Now, what you don’t want to happen if you are in a plane is a “crash” (crash). A “crash” is when a plane falls out of the sky or hits something, and usually bad things follow – bad things happen when that happens to a plane, when it crashes. The verb “to crash” (crash) is used when any kind of vehicle like a plane or a car hits something that it’s not supposed to. In this case, a “plane crash” refers to when a plane usually hits the ground at a very fast speed and explodes or is damaged in some way. Angelica is writing a book about a plane crash.
Corey asks, “What caused it?” meaning “Why did the plane crash?” The “cause” (cause) of something is the reason something happened. Angelica says, “It doesn’t matter,” meaning it’s not important. “That’s not part of the story,” she says. Corey says, however, that the “characters have back stories, so you should have a backstory for the plane crash.” The word “backstory” (backstory) refers to the information about a character or someone in a book, play, movie, or TV show before they appear in the story.
So it’s, if you will, the history of that character, of that person in the story, before the story begins. Now why is backstory important? Well, because in order to understand a story, every character, every person in the story, needs to have some sort of history, some sort of reason why they do what they do or why they are in the story, and so the backstory is the story of the characters, of the people in a story, before the story begins. I hope that makes sense.
“Backstory” is one of those words that gets used a lot here in Los Angeles, where of course many of the movies and television shows are written – often at some of the cafés I go to. Every time I go to a café here in Los Angeles, there’s usually someone working on a “script” (script). A script is the dialogue, or what the people say, in a movie or a TV show.
Corey is saying that the plane crash needs to have a backstory. There needs to be a reason for it that is somehow part of the story or the book that Angelica is writing. Angelica says, “Okay, the plane crashed because of mechanical failure, or better yet, pilot error.” “Mechanical” (mechanical) refers to something in a machine or something related to a machine. “Failure” (failure) is when something goes wrong, when there’s a problem with something. “Mechanical failure” would be when something goes wrong with some part of the plane.
Angelica says, “The plane crashed because of mechanical failure.” But then she comes up with another reason: “Or better yet,” she says, “pilot error.” The phrase “better yet” (yet) is used when you have a better idea than the one you just mentioned. In this case, Angelica first says the plane crashed because of mechanical failure, and then she thinks of a better reason. So she says, “better yet, pilot (pilot) error (error).”
The “pilot” is the person who is in charge of or who is guiding the plane, usually in the front of the plane. There are often two people in front of the plane, the “pilot” and what we call the “copilot” (copilot). The copilot is the person who helps the pilot fly the plane, or who flies the plane if the pilot is not able to. “Error” (error) is when something goes wrong, or in this case when a person makes a mistake – when a person “errs” (errs). So, “pilot error” would be when a pilot makes a mistake, which of course we don’t want to happen.
Corey says, “What happened? Was it because the pilot misread the instruments or had a problem navigating?” Corey is trying to find out more about why Angelica’s pilot made a mistake in her book. One reason could be that the pilot “misread” (misread). “To misread” (the past tense is spelled the same but pronounced differently – “misread”) means to read or look at something but not do it carefully, do it in such a way that you make a mistake.
“Instruments” refer to things on the airplane, in this case, that indicate or show how the plane is doing – how high the plane is flying, what direction the plane is flying in, and so forth. So, if a pilot “misreads” the instruments on the plane, the pilot is not looking carefully enough and getting the wrong information, if you will, from the instruments, or not the correct information. Corey also suggests that perhaps the pilot had a problem “navigating.” “To navigate” (navigate) means to determine which direction you are going in a car, boat, or a plane.
Angelica doesn’t have an answer to Corey. She says, “I don’t know.” She doesn’t know, of course, because she’s just inventing these things as she’s talking. She’s just making them up, which of course is what all authors, all writers do, but Angelica hasn’t thought about it very carefully. Corey then says, “Maybe he or she,” referring to the pilot, “was incapacitated due to illness.” “To be incapacitated” (incapacitated) means to be unable to use your body or perhaps your brain because you are either sick or injured.
If you are “incapacitated due to an accident,” because of an accident, you may be unable to walk, for example. You may have broken your legs. That would be a case of being “incapacitated” – unable to do what you normally do. “Capacitated” comes from the word “capability,” which is “able to do something.” So, “incapacitated” is “not able to do something.”
Angelica isn’t interested in this discussion. She says, “Let’s say instead,” in place of the reason she’s already given, “that it happened” – that is, the plane crashed – “because of an act of God.” The phrase “act of God” usually refers to an event that people have no control over, that wasn’t caused by anything human beings can do or have done, such as a flood or an earthquake or a hurricane. These are also sometimes called “natural disasters” – things that happen that are not caused by human beings.
Corey says, “Like a lightning strike?” He’s giving an example of an “act of God,” and one of those examples is a “lightning (lightning) strike (strike).” “Lightning” refers to an exchange of electricity either within clouds above in the sky, or between the earth and a cloud. Usually there’s a loud sound which we call “thunder” (thunder) that you hear after lightning. “Lightning” is usually indicated by a bright flash of light. Corey says a lightning strike is not a very likely or probable thing that would cause a plane crash.
Angelica then changes her mind again. She says, “Okay, how about some problem with the flight crew that caused the cabin to depressurize and the plane to go into a tailspin.” The “flight crew” (crew) refers to the people who work on the airplane – not just the pilots but also the people in the back part of the plane who are giving you drinks and making sure everyone stays in his or her seat. The “cabin” (cabin) refers to the main part of the plane where everyone sits. The cabin is where most people in the plane sit.
The very front of the plane where the pilots are is usually called the “cockpit” (cockpit).
So, you have the “cabin,” which is where everyone sits other than the pilots, who are in the “cockpit” in the front of the plane. If the cabin “depressurizes,” it loses the pressure that is normally inside of a plane that allows you to be able to breathe in the plane. When a plane goes up very high in the sky, it has to be pressurized in order to allow people inside of the cabin to breathe normally, but if it “depressurizes,” that can cause the plane to crash.
One way a plane can crash is to go into a “tailspin” (tailspin). A tailspin is when a plane falls from the sky down to the ground, often by spinning around in a circle. Angelica suggests that the plane crashed because the flight crew did something to cause the cabin to depressurize and the plane went into a tailspin. Corey says, “What was the problem with the flight crew?” Angelica is getting impatient. She says, “It doesn’t matter!” meaning it’s not important. She said that already, of course, earlier in the dialogue.
Corey then comes up with another possible reason for the plane to crash. He says, “Maybe a member of the flight crew was a hijacker and it was an act of terrorism.” A “hijacker” (hijacker) is a person who uses violence or some other threat to take control, usually of an airplane, in order to do something bad – sometimes to get money, other times to escape from the authorities (people who may want to arrest that person), or sometimes to cause damage with the plane itself. An “act of terrorism” refers to any violence that is done in order to make people afraid or to try to achieve some sort of political or military goal. We are all sadly aware of acts of terrorism nowadays.
Angelica says, “Okay, let’s say that’s what happened. Happy?” meaning “Are you happy now that I have taken your reason as the backstory for the plane crash?” Corey apparently is not happy. He says, “But wait! Who is the terrorist? What were his aims” – that is, what was he trying to accomplish, what was he trying to do – “and what was his cause?” meaning what was his political motivation for doing what he was doing.
Angelica says, “You know what? I think you should put that in your book!” Angelica is telling Corey that he should write his own book and he can put all of that information, all of these reasons, into his own book, and he should stop trying to make Angelica think of reasons for the plane crash for her book.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Angelica: So the book I’m writing starts with a plane crash.
Corey: What caused it?
Angelica: It doesn’t matter. That’s not part of the story.
Corey: But characters have backstories, so you should have a backstory for the plane crash.
Angelica: Okay, the plane crashed because of mechanical failure, or better yet, pilot error.
Corey: What happened? Was it because the pilot misread the instruments or had a problem navigating?
Angelica: I don’t know.
Corey: Maybe he or she was incapacitated due to an illness. What kind of illness?
Angelica: Forget it. Let’s say instead that it happened because of an act of God.
Corey: Like a lightning strike? That’s not very likely.
Angelica: Okay, how about some problem with the flight crew that caused the cabin to depressurize and the plane to go into a tailspin.
Corey: What was the problem with the fight crew?
Angelica: It doesn’t matter!
Corey: Maybe a member of the flight crew was a hijacker and it was an act of terrorism.
Angelica: Okay, let’s say that’s what happened. Happy?
Corey: But wait! Who was the terrorist? What were his aims and what was his cause?
Angelica: You know what? I think you should put that in your book!
[end of dialogue]
There’s no scriptwriter error here on ESL Podcast, thanks to the wonderful work of our scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
plane crash – an accident in which a plane falls out of the sky and lands in an uncontrolled way on the ground or in the water, usually resulting in death and/or injuries
* Many people are scared of being in a plane crash, but flying is actually much safer than driving.
backstory – background information about someone or something, especially when it is not an important part of the current story, but it tells what happened before the story began and provides details that help the reader or listener understand the story more deeply
* It’s hard to understand Hannah’s relationship problems unless you’re familiar with her backstory of how she was treated badly by her parents as a child.
mechanical failure – a problem with a motor or other equipment, not a problem caused by the person operating the machine
* Changing your car’s oil regularly can help to prevent mechanical failure.
better yet – a phrase used when one just had a better idea and wants to suggest it instead of what one just said a moment ago
* Let’s rent a boat this weekend, or better yet, let’s borrow the neighbor’s boat.
pilot error – a mistake made by the person who flies an airplane, often resulting in an accident
* When Spencer turned left instead of right, he made a pilot error that put the lives of all the passengers in danger.
to misread – to see and interpret something incorrectly; to read something incorrectly; to make a mistake while reading or while checking the value of something
* Why is our electric bill so high? The technician must have misread our meter.
instrument – one of many tools, buttons, levers, and gauges used to operate an airplane, car, or another machine
* This instrument shows how much gas is left, and this instrument shows how fast we’re moving.
to navigate – to determine which way one should go and then move in that direction, making changes or adjustments as needed
* I can’t read this map and drive at the same time. Please help me navigate our way to the conference.
incapacitated – unable to use one’s body or brain fully; disabled in some way; not able to do something that one would normally be able to do
* Jerome drank so much beer that he was incapacitated and had to be taken to the hospital.
act of God – an event that people have no control over, such as a hurricane, earthquake, or flood
* Make sure your homeowners insurance covers damage caused by acts of God.
lightning strike – when electricity from the sky hits something during a storm, usually causing damage, injury, or death
* With so much dead grass in the fields, a lightning strike could easily start a forest fire.
flight crew – the team of people who are on an airplane to provide service to passengers during a fight, including the pilot, co-pilot, and flight attendants
* Members of the flight crew are asking all the passengers to put on their seat belts and prepare for landing.
cabin – the large, open part of an airplane where passengers sit, not where the engine is and not where the suitcases are stored
* Did you have to pay extra to have your dog fly with you in the cabin?
to depressurize – to lose pressure; for the air pressure inside of an enclosed area to be released, especially when an airplane is flying
* If the airplane depressurizes, oxygen masks will be released from the ceiling.
tailspin – when an airplane falls from the sky very quickly while also turning in circles
* Can an electrical storm cause an airplane to go into a tailspin?
hijacker – a person who uses violence or threats to take control of an airplane or another vehicle, especially forcing a plane to change its direction and destination
* The hijacker said that no one would be hurt if the pilot agreed to land the plane in Miami.
act of terrorism – an act of violence performed to cause fear among a large group of people, usually to achieve or promote political or religious goals
* That bombing was an act of terrorism that killed hundreds of men, women, and children.
Comprehension Questions
1. Which of these is an example of mechanical failure?
a) The pilot misreads the instruments.
b) There is a lightning strike.
c) The airplane engine stops unexpectedly.
2. What happens if a plane goes into a tailspin?
a) The plane falls out of the sky while turning in circles.
b) The plane’s speed increases very quickly.
c) The plane begins to fly backward.
Answers at bottom.
What Else Does It Mean?
instrument
The word “instrument,” in this podcast, means one of many tools, buttons, levers, and gauges used to operate an airplane, car, or another machine: “Which of these instruments tells us the depth of the water below the boat?” An “instrument” is also a tool that makes music: “Pierre knows how to play the piano, trombone, guitar, and a few other instruments.” In medicine, an “instrument” is a tool used by a doctor or surgeon: “The nurse’s job is to prepare all the instruments for the doctors before the surgery begins.” Finally, if someone is “an “instrument of (someone/something)” he or she is being used or exploited for someone else’s purposes: “All these officials are just instruments of our corrupt government.”
cabin
In this podcast, the word “cabin” means the large, open part of an airplane where passengers sit: “Please enter the airplane and find your seat in the cabin as quickly as possible.” A “cabin” is also a wooden house in the woods or another area far from the city, usually used for relaxation and vacations: “They spent last weekend fishing at a cabin near Lake Detroit.” On a large ship, a “cabin” is a room used for sleeping by the crew or by passengers: “The passengers’ cabins are at the front of the cruise ship, and the crew stays in smaller cabins on the lower levels.” Finally, “cabin fever” refers to feelings of anxiety when one has been forced to stay inside for a long time: “After weeks of heavy snowfall, we were all suffering from cabin fever.”
Culture Note
The National Transportation Safety Board
The National Transportation Safety Board (NTSB) is a U.S. government “agency” (department or organization) responsible for “investigating” (researching; determining what happened) accidents on “highways” (wide roads for fast-moving cars), railroads, ships, and airlines. It also investigates “pipeline incidents” (problems related to the long tubes that carry oil, natural gas, and other substances for long distances) and accidents in which “hazardous materials” (substances that can cause injury, illness, or death) are “released” (allowed to escape), such as when a “tanker truck” (a large vehicle that carries liquids) “leaks” (allowing a liquid to escape) dangerous chemicals.
The NTSB is based in Washington, DC and has four “regional” (related to or located in a particular location) offices in Alaska, Colorado, Virginia, and Washington. It was created in 1967 as part of the Department of Transportation, but “Congress” (the part of the U.S. government that makes laws) soon “established” (created) it as an “independent agency,” meaning that it is not directly connected to other parts of the “federal” (national) government. This was done to be sure that it could be “unbiased” (without already having certain opinions or a need to find certain results) in its investigations.
The “mission” (purpose; reason for being) of the NTSB is to “determine” (identify) the “probable” (most likely) cause of transportation accidents and “incidents” (events that have negative consequences) and to “formulate” (develop; create) safety “recommendations” (suggestions for ways to make something better) to improve transportation safety." The NTSB has “issued” (made; released) more than 14,000 recommendations, and about 73% of them have been “implemented” (adopted and followed).
Comprehension Answers
1 - c
2 - a