= 1260
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,260 – Transport and Shipping Mishaps.
This is English as a Second Language Podcast episode 1,260. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. How are you today? Me, pretty good. Thanks for asking.
This episode, like all of our episodes, has a Learning Guide. You can get it by going to our website at ESLPod.com.
This episode is a dialogue between Una and Jackson about problems that can happen when you are moving things from one place to another. Let’s get started.
[start of dialogue]
Una: Get on the horn and find out where our cargo is.
Jackson: I’ve been trying. Last week, I finally reached someone at the transport company and all they would tell me was that due to unforeseen circumstances, there will be a delay in delivery.
Una: Didn’t they give you any details?
Jackson: None at all. When I called again two days later, I spoke with someone else who said there may have been a mishap in transit, such as a truck breakdown or accident.
Una: But our cargo is being shipped by sea.
Jackson: That’s what I told her. She said the delay could be due to something as simple as bad weather and that our cargo probably hasn’t been captured for ransom or lost at sea.
Una: Captured for ransom?! Lost at sea?!
Jackson: She said that probably hasn’t happened. When I called again yesterday, I was told the cargo had arrived at the port, but that there’s a problem.
Una: What kind of problem?
Jackson: The person I spoke to didn’t know, but thought that it could be a delay in customs clearance or even a loss of refrigeration.
Una: A loss of refrigeration?! That would be disastrous.
Jackson: I know, but then again, who thought transporting Alaska snow to California was a good idea?
Una: Our wonderful director, remember?
[end of dialogue]
Our dialogue begins with Una saying to Jackson, “Get on the horn and find out where our cargo is.” The expression “get on the horn” (horn) is a somewhat old expression, but you will still hear people using it. That means to make a phone call or to call someone by telephone. Una tells Jackson to “get on the horn and find out,” or determine, where their “cargo” (cargo) is. “Cargo” refers to things that are moved or transported by truck, train, or ship, that are usually large and heavy.
We think about “cargo” as being large boxes or large containers that have things in them. On an airplane, for example, the cargo usually goes on the bottom of the plane. Your “luggage” – that is, your suitcases – are cargo, at least they are when they are put together with a bunch of other suitcases and placed on the bottom of the plane. You can move cargo by train or ship or truck. Cargo is usually, but not always, things that are being sold that are being moved from one company to another.
Jackson says, “I’ve been trying” – that is, I’ve been trying to find out where our cargo is. “Last week,” he says, “I finally reached someone,” meaning I finally was able to talk to someone, “at the transport company.” A “transport (transport) company” is a business that moves things from one place to another. The verb “to transport” means to move something. So, a “transport company” would be a company that moves things, usually for other companies, in a truck, a plane, or perhaps a ship or train.
Jackson says the transport company said “that due to unforeseen circumstances,” there was going to be a delay in delivery. “Unforeseen” (unforeseen) is something that you don’t anticipate, that you don’t predict. Something that is unexpected is “unforeseen.” “Unforeseen circumstances” would be a situation usually when something goes wrong that you didn’t expect. And of course, we never expect anything to go wrong, do we?
“There will be a delay in delivery,” Jackson says, because of these unforeseen circumstances, these unforeseen situations. A “delay” (delay) is a period of time longer than expected. When you go to the airport and your plane doesn’t leave at the time it’s supposed to, we would say the plane has been “delayed,” using it as a verb, or simply that there has been “a delay,” using it as a noun. A “delay” is when things are taking longer than expected or are not happening at the time they should.
“Delivery” is moving something from one place to another, usually from the company that sells the product to the company or person that is buying the product. You can get “food delivery.” You can get a restaurant to bring food to your house, or some other company will pick up your food at the restaurant and bring it to your house. If you call a restaurant to order some food, they may ask you, “Is that for pickup or delivery?” “Pickup” means you will go and pick up, or get, the food. “Delivery” means they will bring the food to you.
Una says, “Didn’t they give you any details?” She’s asking Jackson if the company explained why there was a delay. Jackson says, “None at all,” meaning no, they didn’t give me any specific information. They didn’t give me any details. He says, “When I called again two days later, I spoke with someone else who said there may have been a mishap in transit, such as a truck breakdown or accident.” A “mishap” (mishap) is when something bad happens that creates a problem.
Another word for a “mishap” would be simply an “accident” – something bad that happens that you, of course, didn’t expect. “In transit” (transit) means while you are transporting or moving something. A “mishap in transit” means something bad happened during the process of moving things from one place to another. One possible thing that might have caused this delay is a “truck breakdown” (breakdown). A “breakdown” is when a machine stops working – in this case, a truck.
Una says, “But our cargo is being shipped by sea.” “To ship” (ship) something is usually to send something either using the official government mail service or a private delivery system or service, such as UPS or Federal Express or DHL. Una says that their cargo “is being shipped,” or transported, “by sea,” meaning in a boat or ship. So, a truck accident couldn’t be the reason why there is a delay.
Jackson says, “That’s what I told her,” meaning that’s also the same thing I told the woman I spoke with. “She said the delay could be due to something as simple as bad weather and that our cargo probably hasn’t been captured for ransom or lost at sea.” The woman Jackson spoke with said the delay “could be due to something as simple as bad weather,” meaning maybe the reason there is a delay is there was bad weather that prevented or slowed down the transport.
Then the woman at the transport company told Jackson that the cargo “probably,” meaning most likely, “has not been captured for ransom or lost at sea.” Well, of course, these are two very bad things that you would not expect to happen. One thing is that your cargo would be “captured for ransom.” “To capture” (capture) something is to take something, to steal something. “Ransom” (ransom) is when you ask someone for money to get something or someone returned to that person.
Usually we think about ransom with what is called a “kidnapping” – when someone is taken against his will and held until someone pays you money. Here, Jackson is talking about the possibility of their cargo being “captured for ransom,” or even worse, “lost at sea.” If something is “lost at sea,” basically a boat or ship has sunk, has gone down into the water, and so has your cargo. So you’ll never get it back. Una is shocked. She’s surprised that Jackson is talking about these terrible things that might have happened, such as “captured for ransom” and “lost at sea.”
Jackson says, “She said that probably hasn’t happened. When I called again yesterday, I was told the cargo had arrived at the port, but that there’s a problem.” A “port” (port) is a place where many ships, large ships, come and bring cargo which is then delivered to trucks or other means of transportation. Here in Los Angeles, we have the Port of Los Angeles, where ships from all over the Pacific, largely from Asia, come and bring things to the United States – cargo which is then put on either trucks or trains and then delivered to different parts of the U.S.
Jackson says that their cargo has arrived at the port – so it was not lost at sea – but still there is a problem. Una says, “What kind of problem?” Jackson says, “The person I spoke to didn’t know, but thought that it could be a delay in customs clearance or even a loss of refrigeration.” “Customs” (customs) here refers to the process of the government approving entry of certain things into a country. When you go to another country, you usually have to go through customs. They make sure you’re not bringing anything into the country you’re not supposed to or that you’re not paying for properly.
“Clearance” (clearance) is the process of the government officials approving your cargo, in this case – saying yes, it’s okay, there’s no problem, you can bring this into the country. Jackson says that maybe the delay in getting their cargo was due to “customs clearance issues” or, he says, “a loss of refrigeration.” “Refrigeration” (refrigeration) is the process of keeping something cold. So, if your cargo is food and you are sending it in a ship over many, many miles, you will want it to keep cold so that the food doesn’t go bad.
A “loss of refrigeration” would mean that for some reason the ship was unable to keep the food cold. That’s why Una says, “A loss of refrigeration?! That would be disastrous” (disastrous). “Disastrous” comes from the word “disaster,” which is a terrible event, a terrible thing that happens. An earthquake that kills many people is a “disaster.” Una says that a loss of refrigeration would be “disastrous” for her and her company.
Jackson says, “I know” – meaning yes, I understand that that would be disastrous – “but,” he says, “then again, who thought transporting Alaska snow to California was a good idea?” The phrase “then again” is used when we are going to present a new idea after thinking about it some more. Usually we use this when we’re going to present a different idea from the one we just talked about, or perhaps to provide a different perspective on things compared to what we just said.
I could say, for example, “I want to go to the movies, but then again, there aren’t any good movies I really want to see.” “But then again” introduces a different idea that contrasts or is somehow providing a different perspective than the first idea. Jackson says, “Who thought transporting Alaska snow to California was a good idea?” Now we find out what the cargo that is being sent to their company is. It’s snow from Alaska.
Jackson, of course, doesn’t think this was a good idea. Una says, “Our wonderful director, remember?” We learn that this company doesn’t belong to Una because she’s not the boss. The person who is the boss is the “director” (director). A “director” is a person who leads an organization or part of an organization. Una says, “Our wonderful director,” but she of course is making a joke. She doesn’t think the director is wonderful because he or she had this very dumb idea.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Una: Get on the horn and find out where our cargo is.
Jackson: I’ve been trying. Last week, I finally reached someone at the transport company and all they would tell me was that due to unforeseen circumstances, there will be a delay in delivery.
Una: Didn’t they give you any details?
Jackson: None at all. When I called again two days later, I spoke with someone else who said there may have been a mishap in transit, such as a truck breakdown or accident.
Una: But our cargo is being shipped by sea.
Jackson: That’s what I told her. She said the delay could be due to something as simple as bad weather and that our cargo probably hasn’t been captured for ransom or lost at sea.
Una: Captured for ransom?! Lost at sea?!
Jackson: She said that probably hasn’t happened. When I called again yesterday, I was told the cargo had arrived at the port, but that there’s a problem.
Una: What kind of problem?
Jackson: The person I spoke to didn’t know, but thought that it could be a delay in customs clearance or even a loss of refrigeration.
Una: A loss of refrigeration?! That would be disastrous.
Jackson: I know, but then again, who thought transporting Alaska snow to California was a good idea?
Una: Our wonderful director, remember?
[end of dialogue]
Don’t delay in improving your English. Start listening to all of our wonderful episodes with the wonderful scripts written by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to get on the horn – to make a phone call; to contact someone by phone
* Now that you’ve finished the sales training, it’s time to get on the horn and start selling our products.
cargo – items that are transported by truck, train, or ship, usually large and heavy items
* Hundreds of tons of coal, oil, and other cargo are transported along this railroad each week.
transport company – a business that helps other companies send and receive products over long distances; a company that delivers items from sellers to buyers
* They use one transport company for deliveries within the country, and another transport company for international deliveries.
unforeseen circumstances – something that was not anticipated; unexpected, unwanted, and undesirable occurrences; something that causes one’s plans to change in a negative way
* Due to unforeseen circumstances, the concert tonight is cancelled.
delay – a lengthening of the time needed to do something; a period of time that makes something take longer than expected
* Road construction is causing delays on the freeway.
delivery – the process of transporting something and bringing it to the buyer or recipient
* We offer free shipping, but if you want to have faster delivery, you’ll need to pay an extra fee.
mishap – an accident; something that happened unexpectedly and created a problem
* The dancer had a mishap yesterday. She slipped on the ice and hurt her leg.
in transit – while being transported; while moving between two points; while in motion, not yet at the destination
* The website shows that your package is in transit and should arrive tomorrow.
breakdown – when something stops working, especially when an automobile stops operating and can no longer move
* We had a breakdown and waited on the side of the rode for the tow truck.
to ship – to send something over a long distance; to use a mail or delivery service
* How many packages does your office ship in a typical week?
captured for ransom – kidnapped; with someone being held or kept until money has been paid for his or her return; held hostage for money
* Their son was captured for ransom, and the criminals demanded one million dollars for his return.
to be lost at sea – for a person or thing to fall into the ocean and never be found again
* How many sailors were lost at sea during the hurricane?
port – a place where many ships bring cargo as a delivery and take cargo to send to other places; a city or town on the ocean shore where ships are loaded and unloaded
* The railroads send wheat and corn from farms to the port, where it is loaded onto ships and sent to Asia.
customs clearance – the process of giving permission for products to cross borders and collecting payments if needed
* It’s fine to travel with one laptop computer, but if you try to travel with 20 new laptops, you’ll probably have some problems with customs clearance.
loss of refrigeration – when a refrigerator (a machine that is supposed to keep the air in a small area cold) has mechanical problems and stops working, usually resulting in spoiled (damaged) products
* Our electricity stopped working during the storm, so we had a loss of refrigeration, but fortunately, we didn’t have very much food in the freezer.
disastrous – creating many big problems; causing a lot of damage, harm, or death
* Losing all that data would be disastrous for the company.
then again – a phrase used to present a new or additional idea; after thinking about it
* That’s an interesting proposal, but then again, it’s very risky.
director – a person who leads an organization, department, or company; a person who leads and produces a movie
* The director plans to hire at least four more computer programmers by the end of the year.
Comprehension Questions
1. What does Una mean when she says “Get on the horn”?
a) She wants Jackson to make some phone calls.
b) She wants Jackson to tell her the truth.
c) She wants Jackson to stop giving her excuses.
2. Which of these is an unforeseen circumstance?
a) A weekly business meeting
b) Rain on the day of an outdoor wedding
c) Guests arriving for a dinner party
Answers at bottom.
What Else Does It Mean?
delivery
The word “delivery,” in this podcast, means the process of transporting something and bringing it to the buyer or recipient: “Do you want our standard delivery, or overnight service?” The phrase “cash on delivery” describes a policy where someone pays for goods when they are received: “All our products are sold as cash on delivery. Just pay the delivery driver.” The word “delivery” also means childbirth, or the process of giving birth to a child: “Did you go to the hospital for your baby’s delivery, or did you give birth at home?” Finally, when talking about acting or giving a presentation, “delivery” refers to how well someone speaks in front of an audience: “The actress’s delivery was so emotional that almost everyone in the audience began crying.” Or, “The presenter was well prepared and had a lot of interesting visuals, but the delivery was a little boring.”
port
In this podcast, the word “port” means a place where many ships bring cargo as a delivery and take cargo to transport to other places: “They went to the port to watch cranes and other big machines lift heavy cargo onto ships.” When talking about a large boat or ship, “port” is the left side when one is looking at the front of the ship: “Our cabin is toward the front of the ship, on the port side.” When talking about computers, a “port” is one of the small holes on the side or back, used to connect cables: “Please connect the printer to this USB port.” Finally, “port” is a dark, sweet wine often drunk for dessert after a meal: “This cheese would be delicious with a small glass of port.”
Culture Note
Nautical Terms used in Daily Conversation
Many “nautical” (related to boats, sailing, and the ocean) “terms” (words) have “worked their way into” (become a part of) daily conversation, even though the speakers themselves might not really be thinking about their “original” (first; earliest) meaning.
For example, people sometimes talk about “getting to know the ropes” or becoming familiar with something: “I needed a few days to get to know the ropes, but now I know how to do the job well.” This phrase originally referred to the need to become familiar with all the “ropes” (long fibers that are wrapped around each other to make a long, thick string, used for tying objects together) on a sailboat.
The phrase “all hands on deck” is used to say that everyone needs to work together and be involved in a project or effort. In sailing, it means that everyone on the ship needs to come onto the “deck” (the open, flat area of a ship) to help with something, especially before or during a storm. But now the phrase is common in business: “We need all hands on deck if we’re going to fill this order by Thursday.”
When ships returned “victoriously” (winning; having won something) from “battle” (one fight in a war), they “flew” (allowed to be seen in the air) colorful “flags” (pieces of rectangular material with images on them, often representing a country) to let everyone know that they had won. “Nowadays” (in modern times), the phrase “to pass with flying colors” means to do something very well and succeed without any problems: “She passed the test with flying colors.” But few people know that the original phrase was a nautical term for the colorful flags hanging from a ship.
Comprehension Answers
1 - a
2 - b