= 1269
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,269 – Problems with the Heating System.
This is English as a Second Language Podcast episode 1,269. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com and become a member of ESL Podcast. When you do, you can download the Learning Guides for our episodes.
This episode is a dialogue between Dan and Janice about problems with a heating system – the thing that keeps your house warm. Let’s get started.
[start of dialogue]
[Doorbell rings]
Dan: Hello, I’m Dan. I’m here to fix your heating system.
Janice: Oh, when I put in the service call, I didn’t expect a repairperson to come out the same day.
Dan: I just finished another repair in the neighborhood and the company told me to come by. How long has it been on the fritz?
Janice: Well, the boiler hasn’t worked for two months. We used it to heat the basement.
Dan: But you just called for repairs today.
Janice: I didn’t call about the boiler. I called about our radiators. The radiators heat the original part of the house. But we’re also having problems with the furnace for our central heating system, which heats the extension.
Dan: You mean you have two different heating systems in one house?
Janice: It’s an old house. Each system was installed at a different time.
Dan: So you could have problems with more than one thermostat, heating element, fan, or set of ductwork.
Janice: I know that we should install one system for the whole house, but that would be expensive.
Dan: More expensive than fixing two separate systems?
Janice: Is this going to cost a lot?
Dan: I’m afraid so.
Janice: Well, we can’t afford expensive repairs. I guess we’ll have to use these.
Dan: What are those?
Janice: Space heaters.
[end of dialogue]
Dan rings the doorbell, which we hear at the beginning of the dialogue. A “doorbell” is something that makes noise to indicate that someone is at your door and wants you to open it. Dan says, “Hello, I’m Dan. I’m here to fix your heating system.” Dan is talking to Janice, who has, of course, opened the door. A “heating system” refers to all of the equipment and technology used to control the temperature in your house or in a building.
We sometimes talk about a “heating and cooling system.” In some places, it gets very hot, and so you want what is called “air conditioning,” which puts cool air into your house. If it’s cold, you want heating so that your house is warm. My house just has a heating system. I don’t have a cooling system. My cooling system is opening the windows.
In our dialogue, Dan is there to fix the heating system. Janice says, “Oh, when I put in the service call, I didn’t expect a repairperson to come out the same day.” A “service call” is when someone comes to your house to fix something that is wrong. It could be your plumbing, it could be your electricity, or in this case, your heating system.
Janice “didn’t expect a repairperson.” A “repairperson” (or a “repairman” or “repairwoman”) is a person who fixes something broken in your house or perhaps in another building. Usually if you have an electrical or mechanical device in your house that doesn’t work, such as a washer or a refrigerator, you can call a repairperson to come and fix it. That person will “come out,” meaning they will go to your house.
Dan says, “I just finished another repair” – that is, I just fixed someone else’s machine in the same neighborhood, “and the company told me to come by.” “To come by” means to go to someone’s, in this case, house. Dan says, “How long has it been on the fritz?” The expression “on the fritz” (fritz) means not working correctly, or working in a way that you don’t like or that is not acceptable to you. If your television is “on the fritz,” it isn’t working, or at least it isn’t working the way you want it to work.
Janice says, “Well, the boiler hasn’t worked for two months.” A “boiler” (boiler) is something that some homes and buildings have in order to provide heat. A “boiler” actually heats up water. The water turns into vapor or steam, and that vapor or steam is sent through certain pipes or tubes that go into the house or the building that warm the surrounding air. These pipes or tubes usually are in each room. They are put together and called a “radiator” (radiator). My house back in Minnesota, where I grew up, had a boiler and radiators. It’s an older system of heating houses and buildings. The school I went to also had a very large boiler and radiators in each classroom.
Janice says the boiler in her house “hasn’t worked for two months.” She says, “We used it to heat the basement.” A “basement” (basement) is a level or floor of a building that is below the ground. In many parts of the United States, such as in the Midwest and in the east, the houses often have basements a level below the ground. Here in California, most houses do not have basements.
Dan is a little confused because Janice says the boiler hasn’t worked for two months. He says, “But you just called for repairs today.” Janice clarifies. She says, “I didn’t call about the boiler. I called about our radiators.” I explained what radiators are, of course.
“Radiators heat the original part of the house.” So it looks like, or sounds like, Janice has an old part of a house and a new part of her house.
She says, “We’re also having problems with the furnace for our central heating system, which heats the extension.” Another way of heating your house, more common nowadays, is through what is called a “furnace” (furnace). A furnace is a large piece of equipment that burns wood, natural gas, or oil to heat up the air that is used to heat the home.
A boiler heats water, which then becomes steam that is sent through these pipes into the radiators which heat the air around it. A “furnace” heats the air itself and then takes that air and moves it throughout the house so that the air is warm in different parts of the house. Technically, then, they are different ways of heating a house, although when I was growing up, we often referred to the boiler as the furnace without distinguishing between the two, but there is a difference.
Janice says that the new part of her house – the extension – is heated with a furnace. An “extension” (extension) is a part of a house that is added after the original house is built. Here in Los Angeles, it’s very common for houses to have extensions in the back because people want more room. Janice mentions that they have a central heating system in the new part of their house.
A “central heating system” refers to a set of equipment that sends heat throughout the entire house. Most houses have a central heating system, at least most large houses where a furnace is used to heat up the air which is then sent throughout the house to heat it up. There are some older houses that don’t have a central heating system. They have a little heating system in every room.
I used to live in a small house that had one heater in the middle of the house, and that was supposed to heat all of the rooms of the house. So you had to keep the doors open in order to have the heat go into the different rooms. That wasn’t really a central heating system. Central heating systems usually move the air through the house using fans that blow the air from one part of the house to the other.
In any case, Janice is having problems with the furnace in their central heating system. She says they’re having problems not only with the radiators that are part of the boiler system, but also with the furnace for the extension. Dan says, “You mean you have two different heating systems in one house?”
Janice explains, “It’s an old house. Each system was installed at a different time.” “To install” (install) means to connect a new piece of equipment or to put in a new piece of equipment. We often use this verb “to install” when we’re talking about a piece of equipment, mechanical or electrical, that is connected to something else and becomes a more or less permanent part of a house or a building. So we might talk about “installing” a security camera or a set of cameras in different parts of your house. Here we’re talking about installing heating systems.
Dan says, “So you could have problems with more than one thermostat, heating element, fan, or set of ductwork.” Dan is listing, conveniently, different parts of a heating system. A “thermostat” (thermostat) is a small device that you use to set the temperature that you want in your house. It’s how you turn the heater on and off, or turn the air conditioner on and off. A thermostat has a thermometer which tells you what the temperature is inside of a room, and you can change it, turning the heater on or off depending on whether you want more or less heat.
A “heating element” is something that becomes hot through the use of electricity, and that electricity creates heat. Heating elements are actually not used typically in either a boiler or a furnace system. A heating element would be used in an electric heater. Some people have, in addition to a heating system in their houses, electric heaters that they put in individual rooms when they want just one room to be warmer than another. Those electrical heaters have heating elements that get hot because the electricity is going through them, and that creates hot air around the heating element.
A “fan” (fan) is something that moves air. A furnace system has hot air which is then moved by fans to different parts of the house from the furnace to the rooms where you need the heat. An electric heater also uses typically a fan, although not all do. Finally, we have the word “ductwork” (ductwork). “Ductwork” refers to the tubes or passages that go from the furnace to the individual rooms of the house through which the hot air goes.
So, if you walk into a house and you see, usually on the ceiling, an opening that has metal bars over it, that’s probably connected to a duct. Those “ducts” are basically big tubes that are connected to the furnace. The furnace sends the hot air through those ducts into the individual rooms. If you see, on the other hand, metal radiators, either by the floor or against the wall, that house has a boiler system.
Janice says, “I know that we should install one system for the whole house, but that would be expensive.” Dan says, “More expensive than fixing two separate systems?” Janice doesn’t really answer the question. Instead, she asks another question, “Is this going to cost a lot?” meaning is what Dan is going to do today to fix these two systems going to cost a lot of money?
Dan says, “I’m afraid so.” “I’m afraid so” is another way of saying, believe it or not, yes. “I’m afraid so” means “Yes, I am sorry to say that this is true.” Janice says, “Well, we can’t afford expensive repairs.” “Expensive” means costing a lot of money. “I guess we’ll have to use these.” Dan says, “What are those?”
Janice says, “Space heaters.” Space heaters are what I was describing previously. These are little machines that have heating elements in them, that you plug into the wall so that the electricity heats up the heating elements and you can heat up a small area or a small room. If you have lots of space heaters, I suppose you could heat up a big room. We used to use space heaters all the time in my old house where we didn’t have a central heating system.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
[Doorbell rings]
Dan: Hello, I’m Dan. I’m here to fix your heating system.
Janice: Oh, when I put in the service call, I didn’t expect a repairperson to come out the same day.
Dan: I just finished another repair in the neighborhood and the company told me to come by. How long has it been on the fritz?
Janice: Well, the boiler hasn’t worked for two months. We used it to heat the basement.
Dan: But you just called for repairs today.
Janice: I didn’t call about the boiler. I called about our radiators. The radiators heat the original part of the house. But we’re also having problems with the furnace for our central heating system, which heats the extension.
Dan: You mean you have two different heating systems in one house?
Janice: It’s an old house. Each system was installed at a different time.
Dan: So you could have problems with more than one thermostat, heating element, fan, or set of ductwork.
Janice: I know that we should install one system for the whole house, but that would be expensive.
Dan: More expensive than fixing two separate systems?
Janice: Is this going to cost a lot?
Dan: I’m afraid so.
Janice: Well, we can’t afford expensive repairs. I guess we’ll have to use these.
Dan: What are those?
Janice: Space heaters.
[end of dialogue]
Our scriptwriter is like a repairperson for your English. She’ll fix all of the problems if you listen to her dialogues. I speak, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
heating system – all the equipment and technology used to control the temperature of a home or other building
* The heating system used a lot of electricity last January when temperatures fell below zero.
service call – when a mechanic or technician comes to a home or building where something is broken to fix it
* Jacque got permission to work from home today so that he can wait for a plumbing service call.
repairperson – a person whose job is to fix broken equipment or machinery, especially a household appliance
* The repairperson said it might cost $400 to fix our old washing machine, so he recommended that we just buy a new one instead.
on the fritz – not working properly or correctly; likely to break soon; working in an unpredictable and unsatisfactory way
* Lola’s car has been on the fritz lately, so she’s been taking the bus to work.
boiler – a piece of equipment that heats water to turn it into steam (vapor), which is sent through pipes (tubes) to heat a home or other building
* Don’t touch the sides of the boiler! It’s hot.
to heat – to increase the temperature of something
* How should we heat this soup? In the microwave or on the stove?
basement – the bottom floor of a building, completely underground, sometimes used for storage, but sometimes used as a living space
* Their home has an old basement that’s filled with boxes and unused furniture, but they’re going to convert it into a family room and a guest bedroom.
radiator – a piece of equipment that produces heat as hot water, oil, or steam passes through it
* Each of the school’s classrooms has a radiator that makes a clicking or hissing sound while heating up.
furnace – a large piece of equipment that burns wood, natural gas, or oil to heat up the air that is used to heat a home
* They bought a high-efficiency gas furnace to try to reduce their heating expenses in the winter.
central heating system – a collection of related equipment, technology, and ducts (tubes) that produces heat in one place and sends it throughout the home or building
* The central heating system uses a large furnace in the hallway and pushes hot air through ducts under the floors throughout the home.
extension – a part of a home that is added to the original construction years later in order to make the home bigger
* This used to be a very small home, but a few years ago, we created this extension to add two bedrooms and one bathroom.
to install – to buy, connect, and operate a new piece of equipment or software
* Could you please help me install this printer?
thermostat – a small electronic device, hung on a wall, that allows one to control the temperature of a home or another building
* We set the thermostat to 72 degrees during the day and 62 degrees at night.
heating element – a metal device that converts electricity into heat
* Never place a heating element next to curtains or carpets where it might start a fire.
fan – an electronic device that turns metal or plastic blades very quickly to move air forward, creating wind
* Our air conditioner is broken, so we set up some fans in the office to try to keep everyone cool.
ductwork – the system of tubes in the ceiling or under the floors through which hot or cold air move through a home or another building to control the temperature
* A lot of hot air is escaping through the old ductwork. We could save a lot of money by fixing it.
space heater – an electric device, often on wheels, that heats a small space, typically a single room in a larger house or building
* When Clark works from home, he heats his office with a space heater since that’s the only room he uses, and he doesn’t want to waste money heating the whole house.
Comprehension Questions
1. Which of these things generates heat?
a) A furnace
b) A fan
c) Ductwork
2. What does a space heater do?
a) It uses solar energy to heat a home.
b) It heats large, open spaces in a home.
c) It heats a very small part of a home.
Answers at bottom.
What Else Does It Mean?
to heat
The verb “to heat,” in this podcast, means to increase the temperature of something: “They built a small fire to heat their hands and feet.” A “dead heat” describes a race or competition in which two competitors have tied and have the exact same number of points or have traveled the exact same distance: “The spectators stood and cheered as they watched the runners in a dead heat.” A “heat wave” is a period of time with unusual, extremely hot weather: “During the heat wave last August, we spent a lot of time in air-conditioned movie theaters.” Finally, a “heat rash” is a red, irritated area on one’s skin cause by exposure to high temperatures and humid air: “The baby is developing a heat rash on her arms and legs. We need to keep her inside where it’s cooler tomorrow.”
fan
In this podcast, the word “fan” means an electronic device that turns metal or plastic blades very quickly to move air forward, creating wind: “When Karissa turned on the fan, it blew my work papers off the desk and onto the floor.” A “fan” can also be an object that is held in the and moved back and forth quickly to create a cooling wind: “The children folded their papers into fans and tried to cool themselves off.” Finally, a “fan” is often a person who enthusiastically supports a team or admires a celebrity: “The fans cheered when their team stepped onto the field.” Or, “What does it feel like to have hundreds of fans cheering for you when you’re singing on stage?”
Culture Note
Energy-saving Tips for Heating the Home
Heating expenses “account for” (makes up; totals) a “significant” (worth noting; not small) percentage of a typical household’s “budget” (a plan for how one will spend money, or the amount of money spent). Fortunately, there are many “energy-saving tips” (ideas for how to reduce one’s energy consumption) for heating the home.
The U.S. Department of Energy offers many energy-saving tips. Some of them are very simple, such as leaving the curtains open on southern-facing windows that receive sunshine, and hanging heavy, “insulating” (helping to maintain an unchanging temperature) curtains on northern-facing windows that do not receive sunshine. People can also hang “plastic film” (a very thin piece of clear plastic) over their windows to “seal” (prevent something from coming in or going out) them and prevent “drafts” (cold air that comes into a heated home through very small openings).
Another energy-saving tip is to “put on a sweater” (wear warmer clothing) and set the thermostat to a lower temperature. People are “advised” (recommended) to set the thermostat lower at night or when they are out of the house for several hours. A “programmable thermostat” (a thermostat that allows one to control the temperature at specific times without being there) makes it easy for people to cool the home when they are gone and “reheat it” (heat it again) before they return.
Other energy-saving tips include “maintaining” (taking care of) the heating system by cleaning the ducts and changing the “filter” (a device that cleans the air being sent through a heating system). Homeowners can also install “weather-stripping” (a long piece of material put at the bottom or top of a door to cover the opening) on doors and windows.
Comprehension Answers
1 - a
2 - c