= 0201
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 201, “Making a Bet.”
This is English as a Second Language Podcast episode 201. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Visit our website at eslpod.com for the complete Learning Guide to this podcast.
Today's podcast is called, “Making a Bet.” Let's get started.
[Start of story]
Suzanna: Hey, the back of the line is over there.
Ivan: I was here. I just stepped out of line for a minute to get some cash.
Suzanna: Yeah, right. I don’t remember you being in line ahead of me.
Ivan: Come on. Let’s do this. We’ll flip for it. If it’s heads, I win and I get to get back into line. If it’s tails, you win and I’ll go to the back of the line.
Suzanna: All right. I’ll take those odds. You’re on.
Ivan: Here goes…Oh, it’s heads! I win.
Suzanna: I guess it’s your lucky day.
Ivan: I guess so. How about going double or nothing?
Suzanna: What are the stakes?
Ivan: If it’s tails and you win, I go to the back of the line and I have to buy you a drink when we get inside. If it’s heads and I win, I get back in line in front of you and you buy me a drink.
Suzanna: So, no matter what happens I have to have a drink with you?
Ivan: That’s the idea. What do you say?
Suzanna: Okay, you talked me into it. Let’s see if your luck will hold up.
Ivan: I’ve got a good feeling it will.
[End of story]
The podcast today is entitled, “Making a Bet.” To make a bet, “bet,” means that you are saying to someone that you have a certain prediction about what will happen in the future and if what you think - your prediction - happens, then you win the bet. And, if what you predict doesn't happen, you lose the bet. Usually, a bet is with money. You say to someone, “I'll bet you ten dollars that it rains tomorrow.” You are saying that if it rains tomorrow the other person has to give you ten dollars, and if it doesn't rain you have to give him ten dollars.
In dialogue, we have two people, Suzanna and Ivan, who are waiting outside of what is probably a popular bar or pub or dance club, and Suzanna says to Ivan, “Hey, the back of the line is over there.” What happened is that Ivan was coming into the line where they were waiting to get in to the club or bar. To go to the back of the line means to go to the end of the line. So, if someone says, “The back of the line is over there,” they're saying you have to go to the end of the line. You cannot come here, close to the front of the line, where Suzanna is standing.
Ivan says, “I was here. I just stepped out of line for a minute to get some cash.” Ivan is saying that he was standing in line - and to stand, “stand,” in line means to wait in line - he was standing in line and then he stepped out of line. To step, “step,” out of line means to leave the line, to go somewhere away from the line. The line, of course, are the people, the line of people who are waiting to get in.
Suzanna says that, “Yeah, right,” when Ivan tells her that he had “just stepped out of line.” The expression, yeah right, with that intonation, with that pronunciation, means that she does not believe him. It's an informal way of saying I don't believe you. I don't think that's true. “Yeah, right,” Suzanna says, “I don’t remember you being in line ahead of me.” To be ahead of someone, “ahead,” one word, means to be in front of them. So, to be ahead of a person in a line means you are closer to the front of the line than they are.
Ivan says, “Come on. Let’s do this.” Come on means be reasonable, try to agree with me, try to see things my way. He suggests to Suzanna that they make a bet. He says, “We’ll flip for it.” To flip, “flip,” for something means to flip a coin. And, you take a coin, such as a quarter or a dime or a nickel, which are American coins made out of metal, and you put it on your hand and with your thumb, you throw the coin up in the air and it goes around and around and around and then it comes down. Well, when he says to “flip for it,” means let's flip a coin to decide. “If it’s heads,” he says, “I win and I get back into line. If it’s tails, you win and I’ll go to the back of the line.” A coin has two sides. One side, which has the picture, usually, of a president or a famous person. In England, it would be a picture of the Queen. That's the heads because it shows the head of a person. The other side is called the tail of the coin, or we usually use the plural, tails. So, when someone says, “If it's heads,” meaning if the side that has the head on it is the side that lands up, then you win. If it's tails, if the back of the coin is the one that you can see when it stops and you catch it with your hand, then that means, in this story, that Suzanna wins. So, heads I win, tails you win.
Well, Suzanna says, “All right,” she agrees to this. She says, “I’ll take those odds. You’re on.” To take those odds, “odds,” means that I accept what you are saying. The odds are the chances that you can win something. For example, if you are flipping a coin, the odds are 50-50, 50 percent chance that you will get heads or 50 percent chance that you will get tails. So, she's saying, “I will take those odds,” means I will accept your bet. Another way of saying I accept is to say you're on . You're, “you're,” which is short for you are, you are on, you're on means I agree.
Well, Ivan flips the coin and it's heads, which means that he wins. Notice that the expression is it's heads, that means that the heads side of the coin was the one that was on top. Suzanna says, “I guess it’s your lucky day.” - your lucky day. To be lucky, “lucky,” means to have good fortune, to have things that go your way, we might say, that are good things that are happening to you. So, it's his lucky day.
Ivan says, “I guess so. How about going double or nothing?” Double or nothing is an expression we use in betting when someone loses a bet, or wins a bet, and the person says, “let's now bet twice the amount” - two times the amount of the first bet. So, let's say you are betting someone five dollars and you win the bet, if he says, “I'll bet you double or nothing,” or “let's go double or nothing,” that means that you flip the coin again, in this case, and if you win he owes you ten dollars, and if he wins you owe him nothing.
Suzanna says, “What are the stakes?” The stakes, “stakes,” plural, are the things that you will win, the money or the whatever it is that you will win if you win or if...what you have to give the other person if you lose. Usually the stakes are money. We have an expression, high stakes. When we say the stakes are high we mean that they are very expensive or there is a lot that you have to give if you lose. The opposite would be low stakes.
Ivan tells Suzanna that the stakes are that if it's tails and Suzanna wins he has to go to the back of the line, and he has to buy her a drink when they get inside. Notice there are two things he has to do. In the original bet he was just going to go to the back of the line, but since it's double or nothing, he has to do something more. What he'll have to do is go to the back of the line and buy her a drink. If it's heads and Ivan wins, he gets to go back into line in front of Suzanna, and Suzanna has to buy him a drink.
Suzanna says, “So, no matter what happens I have to have a drink with you?” The expression, no matter, “matter,” what happens, means in both circumstances, in both situations, or in any situation - it doesn't matter if she wins or loses, there's no difference, she still has to have a drink with Ivan. Of course, Ivan is hitting on Suzanna. To hit, “hit,” on someone means that you are romantically interested in them and you try to get to know them, and you try to perhaps get their telephone number, or get them to go and have a drink or have coffee with you. This is something that you would do, of course, only if you were single. If you're married, you shouldn't be hitting on anyone, I don't think!
Ivan then says, “That’s the idea.” So, he answers Suzanna's question about having to have a drink with her by saying, yes, that's my intention. That is what I want to happen. That's the idea. That's what I was planning. He then says to Suzanna, “What do you say,” meaning, do you agree to this bet? Do you agree to having a drink with me? And here, of course, is the most important part of the dialogue when Suzanna says, “No! You're a loser! Get away from me!” No, actually Suzanna doesn't say that! A loser, “loser,” is a slang term meaning someone who is not very attractive or someone who does things wrong all the time. Someone who is not a person that you would want to date or be in a romantic relationship.
But, our story has a happy ending because Suzanna says, “you talked me into it.” To talk someone into something means that you convince them, you get them to agree with you. And, Suzanna says that, “you,” Ivan, have “talked me into it” - you have convinced me. Then she says, “Let’s see if your luck will hold up.” The expression, to have your luck hold, “hold,” up, two words, means that it will continue. To hold up, here, means to continue, so she's saying let's see if you continue to be lucky since you bet the first time and you won. And, Ivan says, very confidently as you would expect, “I’ve got a good feeling it will” - means I think that my luck will continue.
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
Suzanna: Hey, the back of the line is over there.
Ivan: I was here. I just stepped out of line for a minute to get some cash.
Suzanna: Yeah, right. I don’t remember you being in line ahead of me.
Ivan: Come on. Let’s do this. We’ll flip for it. If it’s heads, I win and I get to get back into line. If it’s tails, you win and I’ll go to the back of the line.
Suzanna: All right. I’ll take those odds. You’re on.
Ivan: Here goes…Oh, it’s heads! I win.
Suzanna: I guess it’s your lucky day.
Ivan: I guess so. How about going double or nothing?
Suzanna: What are the stakes?
Ivan: If it’s tails and you win, I go to the back of the line and I have to buy you a drink when we get inside. If it’s heads and I win, I get in back in line in front of you and you buy me a drink.
Suzanna: So, no matter what happens I have to have a drink with you?
Ivan: That’s the idea. What do you say?
Suzanna: Okay, you talked me into it. Let’s see if your luck will hold up.
Ivan: I’ve got a good feeling it will.
[End of story]
The script for today's podcast was written by Dr. Lucy Tse, our lucky scriptwriter.
Remember, you can email us at eslpod@eslpod.com if you have questions or comments about this podcast. From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
back of the line – end of a line of people waiting for something, some event
* We’ll never get in. I can’t even see the back of the line from here!
to step out of line – to leave your place in a line of people
* If you’ll hold my place, I’ll step out of line to get us some water and snacks from the store across the street.
ahead of – in front of; before
* If we don’t hurry, the other team will get ahead of us and reach the finish line before we do.
to flip for it – to decide a winner by using a coin; using a coin, each person selects a side, then one person throws it in the air to see which side is up when it lands
* There are three of us and only one ticket left for the show. Why don’t we flip for it?
heads/tails – the front side (heads) or the back side (tails) of a coin
* If it’s heads, he has to wash my car, and if it’s tails, I have to cook him dinner.
to take the odds – to decide to take the risk or the chance
* He took the odds on that basketball game and he won for the first time in weeks.
you’re on – said when someone accepts a bet or a gamble; to agree to a contest or competition
* You think you can beat me in a bike race around the park? You’re on!
your lucky day – you are fortunate; you have good luck
* It’s your lucky day. You can buy this MP3 player for only $20.
double or nothing – a bet in gambling where a player bets again to double or cancel the debt depending on the result
* I can’t believe I lost that last game. How about double or nothing?
stakes – money or something valuable that people gamble to win or play for
* She’s playing a dangerous game at work, but the stakes are a better job and a higher salary.
no matter what happens – an expression used to assure someone that something will occur even if there are difficulties or problems
* They told us that the electricity will be back on tomorrow morning no matter what happens.
that’s the idea – an expression used to tell someone that they are correct or that they are doing something correctly; that’s right
* - Am I doing this math problem correctly?
- Yes, that’s the idea. Now all you need to do is finish solving it.
what do you say? – will you agree?
* I promise never to forget your birthday again if you’ll just give me another chance. What do you say?
to talk (someone) into (something) – to convince someone about something; to get someone to do something that they don’t want to
* She tried talking Curtis into coming with us this weekend, but he said he had too much work to do.
your luck will hold up – your good luck will continue
* Don’t bet that your luck will hold up. If I were you, I’d take my winnings and quit now.
Comprehension Questions
1. Ivan just won the first bet and he is now
a) standing in front of Suzanna in line.
b) at the back of the line.
c) standing behind Suzanna in line.
2. What are the stakes for the double or nothing bet?
a) Suzanna has to get in the back of the line.
b) Suzanna or Ivan has to buy a drink for the other person.
c) Ivan buys two drinks for Suzanna.
Answers at bottom.
What Else Does It Mean?
to flip for it
The phrase “to flip for it,” in this podcast, means to decide a winner using a coin: “They decided to flip for it to decide who will ride in the front seat of the car on the long road trip.” The verb “to flip” has several meanings. “To flip through” means to look or search through something quickly, usually something with pages: “I flipped through all of the books on this shelf but I still didn’t find the letter she was hiding.” Or, “He didn’t really read those papers. He just flipped through them.” “To flip over” means to turn over very quickly: “In the accident, the car flipped over and caught on fire.” Or, “When we all jumped on the bed, he flipped over and fell off!”
that’s the idea
In this podcast, the phrase “that’s the idea” is used when you’re confirming to someone that they’re doing something correctly: “You’ve got it now. That’s the idea. Soon you’ll be doing it better than I can.” We can also use this phrase to mean that this is the general meaning or method of doing something: “Making good bread isn’t easy, but that’s the idea.” A similar phrase, “to get the idea,” means to understand: “I’m starting to get the idea that you don’t want me here.” Or, “He’s been studying those books for days but he doesn’t seem to be getting the idea.” Another phrase, “to have no idea,” means to not know at all: “I could tell that she was gaining weight, but I had no idea that she was going to have a baby!” Or, “We’re all going to the performance tonight but I have no idea what time it starts.”
Culture Note
In the U.S., one of the most popular ways to gamble is to go to a “casino,” or a public place where gambling games are played. Each state in the U.S. can make its own laws about allowing gambling casinos. For almost 50 years, the state of Nevada, where the city of Las Vegas is located, was the only state where casino gambling was legal. At first, the casinos were owned by “organized crime,” or criminal organizations. Later, big hotel companies like Hilton and Ramada were allowed to own casinos, and gambling grew from Las Vegas to other Nevada cities, such as Reno. Today, Las Vegas is still one of the most popular places to gamble in the country.
In the late 1980’s and early 1990’s, several other states also decided to make gambling casinos legal, including South Dakota and Colorado. During this time, the first “riverboat casinos” were also created. Riverboat casinos are casinos that are located on boats. Some lawmakers thought that by putting casinos on riverboats, they could limit where casinos were located and they could also limit the time that gambling could occur by saying, for example, that gambling could only happen while the ship is “sailing,” or moving on the water. Riverboat casinos have become very popular in states located on rivers, such as Illinois, Mississippi, and Missouri. Right now, there are about six states that have riverboat gambling on about 65 boats. The games allowed on these riverboats are normally the same as in any other casino.
Comprehension Answers
1 - a
2 - b