= 0221
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 221, “Long Distance Relationships.”
This is English as a Second Language Podcast episode 221. I am your host, Dr. Jeff McQuillan. I am coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com and look at the Learning Guide for this episode. It's a 10-page guide to the podcast that gives you the complete transcript, all the vocabulary, additional vocabulary, cultural notes and a free trip to Hawaii. Okay, well, everything except the free trip to Hawaii, I promise!
Today's podcast is called “Long Distance Relationships.” Sounds like fun, let's go!
[Start of story]
I met Diana last year when we were both working in New York City for the summer. I’m finishing college in California and Diana started her first job in Florida. Talk about a bicoastal relationship! We spent three great months together and we’ve been trying to maintain a long distance relationship ever since. It’s been really hard and I had a talk about it with my friend, Emily, who just got out of a relationship like this.
Enrique: I’m always worried that for her, it’s out of sight, out of mind.
Emily: I know what you mean, but is it that way with you?
Enrique: No, not at all. I think about her all the time. It’s not that there aren’t temptations, but I’m committed to Diana.
Emily: Don’t you get the same vibe from her?
Enrique: Sometimes I do, but a lot of times I don’t. It’s so easy to get into a fight on the phone. We have misunderstandings all the time or I hurt her feelings without realizing it. And plus, I’m still in school and she’s already out working, and it seems like we’re growing apart.
Emily: That’s what happened with Theo and me. We grew apart and we had less and less in common. After a year, we called it quits.
Enrique: I hope that’s not what Diana wants. I’ve got to have it out with her. If she wants to end this, then I’ll just have to deal with it.
Emily: It’s always better to know where you stand. Let me know how it goes.
Enrique: Sure. See you later.
[End of story]
The topic for this podcast is long distance relationships.
A relationship is normally when a man and a woman are romantically interested in each other. It could be that they are dating, they are not married or it could be that they are married.
This relationship in our story today is a long distance one, meaning that the two people do not live close to each other. Sometimes we use this expression if we are talking about people who live in different cities or even different countries.
Long distance is a term we also use when we are making telephone calls. If you are calling somewhere outside of the city where you live, we say that is a long distance call, and it costs more money.
Well, this is a long distance relationship between Enrique and Emily. Enrique and Emily met in New York City. They were working there during this summer, probably working as interns, “interns.” An intern is someone who works for a company for a short time to get experience.
It turns out that Enrique is going back to California to finish his college and Diana is starting her first job in different state, in Florida, which is on the other side of the country. It is what we would call a bicoastal relationship, “bicoastal.” Bicoastal comes from the word “coast,” which is the part of a country or the part of the land that is next to the ocean. United States, we have two coasts; we have the West Coast, where the Pacific Ocean is, and the East Coast, where the Atlantic Ocean is. A bicoastal relationship means two coasts. “Bi,” bi, as a prefix in English, usually means two. So, you have a bicycle; that is a machine with two wheels.
This is a bicoastal relationship - a long distance relationship, and Enrique is having some problems. Ah, don't we all? He talks to his friend, Emily. Emily just got out of a relationship like this. In other words, Emily was in a long distance relationship and now she is out of the relationship. To get out of a relationship means to end a relationship - to stop it. So, Emily has got out of this long distance relationship with her boyfriend and she is now going to give advice to Enrique.
Enrique starts by saying, “I'm worried about my girlfriend Diana, in Florida. I’m worried that for her, it’s out of sight, out of mind.” That is an expression we use, out of sight, “sight,” out of mind, “mind,” to mean that you don't think about things that are not to close to you - that you cannot see. “Sight” means the same here as to be able to see, or something that you see. So, if you can't see it, you don't think about it - you forget about it. Out of sight, out of mind.
Emily says that she understands what Enrique is talking about, and asks if he feels the same way, that is if it's out of sight, out of mind for him, too. Does he forget about Diana because she is not near him? And, Enrique says, “not at all. I think about her all the time.” You think? I kind of wonder about Enrique, I don't think he's thinking about her. But, well, we'll go with the story here - continue with the story.
Enrique says, “It’s not that there aren’t temptations, but I’m committed to Diana.” The expression, “it's not that,” is one we use to introduce something that isn't true, but we want to compare it to something that is true. So, Enrique says, “it's not true that I don't have temptations.” Temptations, “temptations,” are things that cause you to do something that you may not want to do, that your brain says is a bad idea, but perhaps your heart, or some other part of your body thinks is a good idea. These would be temptations.
The verb is to tempt, “temp,” to try to get someone to do something that they should not do. The world is, of course, full of temptations, that's why I never get another woman, only my wife!
Enrique says he's “committed to Diana.” To be committed, “committed,” means that he is going to stay with Diana. He wants to be in this relationship; he's dedicated to her. Committed can have other meanings as well, and in the Learning Guide we talk about some additional uses of that verb, committed or to commit. We also talk about that expression we used earlier, “get out of,” there are some additional meanings, which you can find in our Learning Guide.
Well, continuing with the story, Emily says do “you get the same vibe from her?” In other words, does she communicate the same idea, that she is committed to you? The word vibe, “vibe,” means the same feeling - the same impression - the same idea. It's the way someone acts towards you, not necessarily what they say.
Enrique says, “Sometimes I do, but sometimes I don’t,” meaning “Sometimes I think Diana is committed and sometimes I don't.” He says, “It's easy to get into a fight” when you're talking “on the phone. We have misunderstandings all the time.” A misunderstanding is when people do not understand each other. Here, mis, “mis,” at the beginning of the word means not.
Enrique says sometimes he hurts his girlfriend's “feelings without realizing,” or without knowing. To hurt, “hurt,” someone's feelings means to make them feel bad - to make them sad, for example. If you say something that is not very nice about someone, you could hurt their feelings.
Enrique is afraid that he and Diana are “growing apart.” To “grow apart” means that as you get older, you aren't as close to another person as you were when you were younger. Enrique is afraid that because Diana is in another state far away, as time goes by, as each month goes by that they are growing apart. Emily says that this is situation that happened to her and her boyfriend, Theo. She says that “We grew apart and had less in common,” meaning they had fewer things that they could talk about or share with each other. “After a year,” Emily says, “we called it quits.” To call something quits, “quits,” means to end something - to end something, to stop something.
Enrique says he hopes that doesn't happen to him and Diana. Of course, it will, but you know, Enrique's trying to see the positive side of things. He says that he is going “to have it out with” his girlfriend. “To have it out” means that you are going to have an argument, perhaps, but you speak very honestly with the other person.
Enrique says that if Diana wants to end, or stop the relationship, he'll “have to deal with it.” This is a very common expression. To deal, “deal,” with something means that you have to adjust to it - you have to make the best situation possible. “To deal with,” means to have to live with and to understand or figure out how to survive - how to continue. Emily says, “It’s always better to know where you stand.” “To know where you stand,” in this case, means to know what your situation is, to understand the other person's opinion and to know the situation or condition of your relationship.
If you are in a long distance relationship, make sure you see the Learning Guide today. It has some advice for those of you who are in a long distance relationship.
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
I met Diana last year when we were both working in New York City for the summer. I’m finishing college in California and Diana started her first job in Florida. Talk about a bicoastal relationship! We spent three great months together and we’ve been trying to maintain a long distance relationship ever since. It’s been really hard and I had a talk about it with my friend, Emily, who just got out of a relationship like this.
Enrique: I’m always worried that for her, it’s out of sight, out of mind.
Emily: I know what you mean, but is it that way with you?
Enrique: No, not at all. I think about her all the time. It’s not that there aren’t temptations, but I’m committed to Diana.
Emily: Don’t you get the same vibe from her?
Enrique: Sometimes I do, but a lot of times I don’t. It’s so easy to get into a fight on the phone. We have misunderstandings all the time or I hurt her feelings without realizing it. And plus, I’m still in school and she’s already out working, and it seems like we’re growing apart.
Emily: That’s what happened with Theo and me. We grew apart and we had less and less in common. After a year, we called it quits.
Enrique: I hope that’s not what Diana wants. I’ve got to have it out with her. If she wants to end this, then I’ll just have to deal with it.
Emily: It’s always better to know where you stand. Let me know how it goes.
Enrique: Sure. See you later.
[End of story]
The script for today's podcast was by Dr. Lucy Tse. Remember to email us if you have a comment or question about our podcast. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We will see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
bicoastal – in two different places near the ocean, usually very far from each other on the opposite sides of a large area of land
* Major magazines like Time and Newsweek have bicoastal offices, usually in New York and California.
long-distance relationship – two people in a romantic relationship or dating while living far away from each other
* One of the downsides to a long-distance relationship is the expensive phone bill.
to get out of – to leave; to no longer be a part of something; to end
* I’ve been a member of this club for five years, but I need to get out of it because it’s taking too much of my time.
out of sight, out of mind – a phrase that means if someone doesn’t see you, then they aren’t thinking about you
* I write down everything I have to do in my calendar. If I don’t, I’ll never get anything done since it’s always out of sight, out of mind with me.
it’s not that – this is not the reason; it’s not because of this
* I know that he didn’t eat anything at dinner, but it’s not that he didn’t like the restaurant. He just wasn’t hungry.
temptation – something that makes you want to do something, usually something wrong or harmful
* People who are on diets try to avoid temptations like chocolate and potato chips.
to be committed – to be devoted; to feel loyal to someone or something
* Rachel shows how committed she is to her work by staying late to finish her projects on time.
vibe – (slang) good or bad feelings given off by a person or thing; the atmosphere of a place
* Leshon didn’t think he did a bad job painting the wall but he got a strong vibe that his girlfriend wasn’t too happy with it.
misunderstanding – not understanding something correctly; when two or more people have different feelings or beliefs about something
* To avoid any misunderstandings, the teacher told his students that he would write all assignments on the board.
to hurt (someone’s) feelings – to make someone feel bad or sad; to insult someone; to cause someone else to have negative emotions
* Not wanting to hurt her feelings, he said he liked the cake she had baked even though it tasted like sand.
to grow apart – for two or more people to become not as close as they used to be; to stop being as friendly or as familiar
* Only two months after Kendra left for her new job in Europe, she started to notice that she and Hassan were growing apart.
in common – having interest in the same things; being similar in beliefs, interests, or behavior
* The only thing they had in common was that neither of them liked the movie Titanic.
to call it quits – to give up; to quit; to end something
* After 20 minutes of trying to program the new DVD player, Hide called it quits.
to have it out with (someone) – to let a person know of the things that’s bothering you; to argue with someone
* Earlier that day, Catherine decided to have it out with her secretary by telling him she’s not happy with the work he’s been doing.
to deal with it – to be okay with something; to handle a difficult situation
* It’s been a year since her husband died but she was still having problems dealing with his death.
to know where (one) stands – to know what someone else is feeling or thinking about a topic or issue; to know someone else’s opinion or belief
* My professor said to me, “Your paper is very good. It clearly shows where you stand on the issue.”
Comprehension Questions
1. Where did Enrique meet Diana?
a) Florida
b) New York City
c) California
2. In this story, Enrique tells Emily that:
a) He wants to break up with Diana
b) He thinks that Diana is working too much
c) He and Diana are not as close as they used to be.
Answers at bottom.
What Else Does It Mean?
got out of
The phrase “to get out of,” in this podcast, means to no longer be a part of something: “I got out of the project because I didn’t agree with the team leader’s decisions.” This phrase also means to avoid doing something: “He got out of doing the dishes by volunteering to cook dinner that night.” Or, “How can I get out of going shopping all day with my wife?” This can also mean to leave or to exit a place, such as a room: “She got out of the crowded room right after she greeted the party’s hosts.” Or, “The audience was sure that the box was empty but the magician’s assistant got out of it as though she had been there the entire time.”
to be committed
In this podcast, the verb “to be committed” means to be devoted or dedicated to something or someone: “She was committed to helping out her sister in any way she can.” This can also be used to mean that someone is obligated to do something: “Since Leslie invited him to the party, Leonard felt committed to go and to bring a gift.” Or, “The governor said that he was committed to spending more money on the poor and the sick in the state.” The verb to commit is also used for doing wrong or bad things, such as a crime: “She told the police that she had committed no crime but no one believed her.” Or, “It’s not clear whether someone killed him or he killed himself by committing suicide.”
Culture Note
Relationships are hard enough and long-distance ones are even more difficult.
Not seeing the person you love can be difficult and there are a lot of people who feel that these types of relationships are “doomed” (certain to fail) from the start. Many people believe that the biggest problem is “jealousy” or being suspicious that the other person is not being faithful or is dating other people. But there are others who believe that if you put some extra work into it, long-distance relationships can be successful.
Relationship “experts” (people who know a lot about a subject) have this advice about long-distance relationships:
1. Be clear about the “ground rules.” Ground rules are basic guidelines about how to behave. Talking about what is expected is a good idea, such as how often to call and when you will visit one another.
2. Do something together. Try to do some things together, even though you are far apart, such as watching the same television program. This gives you a similar experience so that you will have more in common to talk about.
3. Don’t fight about small things. It’s easy for small problems to get “magnified” or seem more important they really are. Make a decision that you won’t fight about small problems and that it’s okay to “agree to disagree,” where each of you has your opinion but you can still get along.
4. Accept uncertainty about how you feel.? It’s not uncommon that when a couple sees each other again after a long time apart, they feel strange or nervous. You may ask yourself, “Do I still love her?” or “Is this relationship still worthwhile?” These feelings are normal and they will most likely “pass” (go away after a short time).
Comprehension Answers
1 - b
2 - c
Dialogue/Story
Slow Speed begins at: 1:27
Explanation begins at: 3:36
Normal Speed begins at: 15:42
Complete Transcript
Welcome to English as a Second Language Podcast number 221, “Long Distance Relationships.”
This is English as a Second Language Podcast episode 221. I am your host, Dr. Jeff McQuillan. I am coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com and look at the Learning Guide for this episode. It's a 10-page guide to the podcast that gives you the complete transcript, all the vocabulary, additional vocabulary, cultural notes and a free trip to Hawaii. Okay, well, everything except the free trip to Hawaii, I promise!
Today's podcast is called “Long Distance Relationships.” Sounds like fun, let's go!
[Start of story]
I met Diana last year when we were both working in New York City for the summer. I’m finishing college in California and Diana started her first job in Florida. Talk about a bicoastal relationship! We spent three great months together and we’ve been trying to maintain a long distance relationship ever since. It’s been really hard and I had a talk about it with my friend, Emily, who just got out of a relationship like this.
Enrique: I’m always worried that for her, it’s out of sight, out of mind.
Emily: I know what you mean, but is it that way with you?
Enrique: No, not at all. I think about her all the time. It’s not that there aren’t temptations, but I’m committed to Diana.
Emily: Don’t you get the same vibe from her?
Enrique: Sometimes I do, but a lot of times I don’t. It’s so easy to get into a fight on the phone. We have misunderstandings all the time or I hurt her feelings without realizing it. And plus, I’m still in school and she’s already out working, and it seems like we’re growing apart.
Emily: That’s what happened with Theo and me. We grew apart and we had less and less in common. After a year, we called it quits.
Enrique: I hope that’s not what Diana wants. I’ve got to have it out with her. If she wants to end this, then I’ll just have to deal with it.
Emily: It’s always better to know where you stand. Let me know how it goes.
Enrique: Sure. See you later.
[End of story]
The topic for this podcast is long distance relationships.
A relationship is normally when a man and a woman are romantically interested in each other. It could be that they are dating, they are not married or it could be that they are married.
This relationship in our story today is a long distance one, meaning that the two people do not live close to each other. Sometimes we use this expression if we are talking about people who live in different cities or even different countries.
Long distance is a term we also use when we are making telephone calls. If you are calling somewhere outside of the city where you live, we say that is a long distance call, and it costs more money.
Well, this is a long distance relationship between Enrique and Emily. Enrique and Emily met in New York City. They were working there during this summer, probably working as interns, “interns.” An intern is someone who works for a company for a short time to get experience.
It turns out that Enrique is going back to California to finish his college and Diana is starting her first job in different state, in Florida, which is on the other side of the country. It is what we would call a bicoastal relationship, “bicoastal.” Bicoastal comes from the word “coast,” which is the part of a country or the part of the land that is next to the ocean. United States, we have two coasts; we have the West Coast, where the Pacific Ocean is, and the East Coast, where the Atlantic Ocean is. A bicoastal relationship means two coasts. “Bi,” bi, as a prefix in English, usually means two. So, you have a bicycle; that is a machine with two wheels.
This is a bicoastal relationship - a long distance relationship, and Enrique is having some problems. Ah, don't we all? He talks to his friend, Emily. Emily just got out of a relationship like this. In other words, Emily was in a long distance relationship and now she is out of the relationship. To get out of a relationship means to end a relationship - to stop it. So, Emily has got out of this long distance relationship with her boyfriend and she is now going to give advice to Enrique.
Enrique starts by saying, “I'm worried about my girlfriend Diana, in Florida. I’m worried that for her, it’s out of sight, out of mind.” That is an expression we use, out of sight, “sight,” out of mind, “mind,” to mean that you don't think about things that are not to close to you - that you cannot see. “Sight” means the same here as to be able to see, or something that you see. So, if you can't see it, you don't think about it - you forget about it. Out of sight, out of mind.
Emily says that she understands what Enrique is talking about, and asks if he feels the same way, that is if it's out of sight, out of mind for him, too. Does he forget about Diana because she is not near him? And, Enrique says, “not at all. I think about her all the time.” You think? I kind of wonder about Enrique, I don't think he's thinking about her. But, well, we'll go with the story here - continue with the story.
Enrique says, “It’s not that there aren’t temptations, but I’m committed to Diana.” The expression, “it's not that,” is one we use to introduce something that isn't true, but we want to compare it to something that is true. So, Enrique says, “it's not true that I don't have temptations.” Temptations, “temptations,” are things that cause you to do something that you may not want to do, that your brain says is a bad idea, but perhaps your heart, or some other part of your body thinks is a good idea. These would be temptations.
The verb is to tempt, “temp,” to try to get someone to do something that they should not do. The world is, of course, full of temptations, that's why I never get another woman, only my wife!
Enrique says he's “committed to Diana.” To be committed, “committed,” means that he is going to stay with Diana. He wants to be in this relationship; he's dedicated to her. Committed can have other meanings as well, and in the Learning Guide we talk about some additional uses of that verb, committed or to commit. We also talk about that expression we used earlier, “get out of,” there are some additional meanings, which you can find in our Learning Guide.
Well, continuing with the story, Emily says do “you get the same vibe from her?” In other words, does she communicate the same idea, that she is committed to you? The word vibe, “vibe,” means the same feeling - the same impression - the same idea. It's the way someone acts towards you, not necessarily what they say.
Enrique says, “Sometimes I do, but sometimes I don’t,” meaning “Sometimes I think Diana is committed and sometimes I don't.” He says, “It's easy to get into a fight” when you're talking “on the phone. We have misunderstandings all the time.” A misunderstanding is when people do not understand each other. Here, mis, “mis,” at the beginning of the word means not.
Enrique says sometimes he hurts his girlfriend's “feelings without realizing,” or without knowing. To hurt, “hurt,” someone's feelings means to make them feel bad - to make them sad, for example. If you say something that is not very nice about someone, you could hurt their feelings.
Enrique is afraid that he and Diana are “growing apart.” To “grow apart” means that as you get older, you aren't as close to another person as you were when you were younger. Enrique is afraid that because Diana is in another state far away, as time goes by, as each month goes by that they are growing apart. Emily says that this is situation that happened to her and her boyfriend, Theo. She says that “We grew apart and had less in common,” meaning they had fewer things that they could talk about or share with each other. “After a year,” Emily says, “we called it quits.” To call something quits, “quits,” means to end something - to end something, to stop something.
Enrique says he hopes that doesn't happen to him and Diana. Of course, it will, but you know, Enrique's trying to see the positive side of things. He says that he is going “to have it out with” his girlfriend. “To have it out” means that you are going to have an argument, perhaps, but you speak very honestly with the other person.
Enrique says that if Diana wants to end, or stop the relationship, he'll “have to deal with it.” This is a very common expression. To deal, “deal,” with something means that you have to adjust to it - you have to make the best situation possible. “To deal with,” means to have to live with and to understand or figure out how to survive - how to continue. Emily says, “It’s always better to know where you stand.” “To know where you stand,” in this case, means to know what your situation is, to understand the other person's opinion and to know the situation or condition of your relationship.
If you are in a long distance relationship, make sure you see the Learning Guide today. It has some advice for those of you who are in a long distance relationship.
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
I met Diana last year when we were both working in New York City for the summer. I’m finishing college in California and Diana started her first job in Florida. Talk about a bicoastal relationship! We spent three great months together and we’ve been trying to maintain a long distance relationship ever since. It’s been really hard and I had a talk about it with my friend, Emily, who just got out of a relationship like this.
Enrique: I’m always worried that for her, it’s out of sight, out of mind.
Emily: I know what you mean, but is it that way with you?
Enrique: No, not at all. I think about her all the time. It’s not that there aren’t temptations, but I’m committed to Diana.
Emily: Don’t you get the same vibe from her?
Enrique: Sometimes I do, but a lot of times I don’t. It’s so easy to get into a fight on the phone. We have misunderstandings all the time or I hurt her feelings without realizing it. And plus, I’m still in school and she’s already out working, and it seems like we’re growing apart.
Emily: That’s what happened with Theo and me. We grew apart and we had less and less in common. After a year, we called it quits.
Enrique: I hope that’s not what Diana wants. I’ve got to have it out with her. If she wants to end this, then I’ll just have to deal with it.
Emily: It’s always better to know where you stand. Let me know how it goes.
Enrique: Sure. See you later.
[End of story]
The script for today's podcast was by Dr. Lucy Tse. Remember to email us if you have a comment or question about our podcast. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We will see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
bicoastal – in two different places near the ocean, usually very far from each other on the opposite sides of a large area of land
* Major magazines like Time and Newsweek have bicoastal offices, usually in New York and California.
long-distance relationship – two people in a romantic relationship or dating while living far away from each other
* One of the downsides to a long-distance relationship is the expensive phone bill.
to get out of – to leave; to no longer be a part of something; to end
* I’ve been a member of this club for five years, but I need to get out of it because it’s taking too much of my time.
out of sight, out of mind – a phrase that means if someone doesn’t see you, then they aren’t thinking about you
* I write down everything I have to do in my calendar. If I don’t, I’ll never get anything done since it’s always out of sight, out of mind with me.
it’s not that – this is not the reason; it’s not because of this
* I know that he didn’t eat anything at dinner, but it’s not that he didn’t like the restaurant. He just wasn’t hungry.
temptation – something that makes you want to do something, usually something wrong or harmful
* People who are on diets try to avoid temptations like chocolate and potato chips.
to be committed – to be devoted; to feel loyal to someone or something
* Rachel shows how committed she is to her work by staying late to finish her projects on time.
vibe – (slang) good or bad feelings given off by a person or thing; the atmosphere of a place
* Leshon didn’t think he did a bad job painting the wall but he got a strong vibe that his girlfriend wasn’t too happy with it.
misunderstanding – not understanding something correctly; when two or more people have different feelings or beliefs about something
* To avoid any misunderstandings, the teacher told his students that he would write all assignments on the board.
to hurt (someone’s) feelings – to make someone feel bad or sad; to insult someone; to cause someone else to have negative emotions
* Not wanting to hurt her feelings, he said he liked the cake she had baked even though it tasted like sand.
to grow apart – for two or more people to become not as close as they used to be; to stop being as friendly or as familiar
* Only two months after Kendra left for her new job in Europe, she started to notice that she and Hassan were growing apart.
in common – having interest in the same things; being similar in beliefs, interests, or behavior
* The only thing they had in common was that neither of them liked the movie Titanic.
to call it quits – to give up; to quit; to end something
* After 20 minutes of trying to program the new DVD player, Hide called it quits.
to have it out with (someone) – to let a person know of the things that’s bothering you; to argue with someone
* Earlier that day, Catherine decided to have it out with her secretary by telling him she’s not happy with the work he’s been doing.
to deal with it – to be okay with something; to handle a difficult situation
* It’s been a year since her husband died but she was still having problems dealing with his death.
to know where (one) stands – to know what someone else is feeling or thinking about a topic or issue; to know someone else’s opinion or belief
* My professor said to me, “Your paper is very good. It clearly shows where you stand on the issue.”
Comprehension Questions
1. Where did Enrique meet Diana?
a) Florida
b) New York City
c) California
2. In this story, Enrique tells Emily that:
a) He wants to break up with Diana
b) He thinks that Diana is working too much
c) He and Diana are not as close as they used to be.
Answers at bottom.
What Else Does It Mean?
got out of
The phrase “to get out of,” in this podcast, means to no longer be a part of something: “I got out of the project because I didn’t agree with the team leader’s decisions.” This phrase also means to avoid doing something: “He got out of doing the dishes by volunteering to cook dinner that night.” Or, “How can I get out of going shopping all day with my wife?” This can also mean to leave or to exit a place, such as a room: “She got out of the crowded room right after she greeted the party’s hosts.” Or, “The audience was sure that the box was empty but the magician’s assistant got out of it as though she had been there the entire time.”
to be committed
In this podcast, the verb “to be committed” means to be devoted or dedicated to something or someone: “She was committed to helping out her sister in any way she can.” This can also be used to mean that someone is obligated to do something: “Since Leslie invited him to the party, Leonard felt committed to go and to bring a gift.” Or, “The governor said that he was committed to spending more money on the poor and the sick in the state.” The verb to commit is also used for doing wrong or bad things, such as a crime: “She told the police that she had committed no crime but no one believed her.” Or, “It’s not clear whether someone killed him or he killed himself by committing suicide.”
Culture Note
Relationships are hard enough and long-distance ones are even more difficult.
Not seeing the person you love can be difficult and there are a lot of people who feel that these types of relationships are “doomed” (certain to fail) from the start. Many people believe that the biggest problem is “jealousy” or being suspicious that the other person is not being faithful or is dating other people. But there are others who believe that if you put some extra work into it, long-distance relationships can be successful.
Relationship “experts” (people who know a lot about a subject) have this advice about long-distance relationships:
1. Be clear about the “ground rules.” Ground rules are basic guidelines about how to behave. Talking about what is expected is a good idea, such as how often to call and when you will visit one another.
2. Do something together. Try to do some things together, even though you are far apart, such as watching the same television program. This gives you a similar experience so that you will have more in common to talk about.
3. Don’t fight about small things. It’s easy for small problems to get “magnified” or seem more important they really are. Make a decision that you won’t fight about small problems and that it’s okay to “agree to disagree,” where each of you has your opinion but you can still get along.
4. Accept uncertainty about how you feel.? It’s not uncommon that when a couple sees each other again after a long time apart, they feel strange or nervous. You may ask yourself, “Do I still love her?” or “Is this relationship still worthwhile?” These feelings are normal and they will most likely “pass” (go away after a short time).
Comprehension Answers
1 - b
2 - c