= 0228
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 228: A Christmas Feast.
Ho, ho, ho! Merry Christmas!
This is English as a Second Language Podcast number 228. I'm your host, Dr. Jeff McQuillan, coming to you from beautiful Los Angeles, California. I want to thank Santa Claus for coming on our program today and wishing us all a Merry Christmas and Happy Holidays to everyone on this Christmas holiday edition of ESL Podcast.
Remember to visit our website and give yourself a Christmas/Chanukah holiday gift by becoming a member of ESL Podcast. If you do that, your present will be a Learning Guide for each episode of this podcast that includes all of the vocabulary, definitions, cultural notes, additional definitions that we don't talk about on the podcast, as well as a complete transcript of each episode.
Our topic today is called “A Christmas Feast.” Let's get started.
[Start of story]
This year, our family decided that the more the merrier and invited Adriano and his family to have Christmas dinner with us. We were thrilled when they accepted our invitation.
Lucy: I’m so glad you guys could all make it.
Adriano: We wouldn’t have missed it for anything. We brought a fruitcake.
Lucy: Oh, thanks. Make yourselves comfortable. We’re just about to sit down to dinner.
Adriano: Wow, it looks like you’ve prepared a feast.
Lucy: Yeah, we did go a little overboard this year. We’ve got a turkey, a roast and a ham, and all the trimmings: stuffing, yams, mashed potatoes, and cranberry sauce. Help yourself to some eggnog.
Adriano: Thanks. Did you do all of the cooking yourself?
Lucy: I had some help and everybody brought different desserts. Save room for the pumpkin pie, the gingerbread house, and the Christmas cookies. Okay everybody, dinner’s ready. Adriano, would you carve the bird?
Adriano: I’d be happy to do the honors.
[End of story]
Our dialogue today begins by Lucy saying that “This year” her “family decided that the more the merrier and invited Adriano and his family to have Christmas dinner with us.” The expression the more the merrier, “merrier,” means the more people you have, the more fun or the more happy something will be. To be merry, “merry,” means to be happy, which is why we say, “Merry Christmas.” We don't normally say, “Happy Christmas” in English, we say, “Merry Christmas.” We do say, “Happy New Year.” Merry is just another word for happy. The expression the more the merrier means more people will be more fun.
Lucy says her family was “thrilled when” Adriano and his family “accepted our invitation.” To be thrilled, “thrilled,” means to be very happy - to be delighted. “I am thrilled that my wife is going to give me a new fifth generation iPod for Christmas.” She doesn't know that yet, but she will!
Lucy begins the dialogue by saying, “I’m so glad you guys could all make it.” Notice the use of the word guys, “guys,” here; it's an informal way of referring to you all. We don't have in English, as in many languages, a plural you, so “you guys” is an informal way of communicating that idea.
Lucy says that she is glad that Adriano and his family could make it, meaning could come to the party. Adriano says, “We wouldn’t have missed it for anything,” it was very important for us, in other words. He says, “We brought a fruitcake.” A fruitcake, “fruitcake,” (one word) is a traditional Christmas cake that usually contains little pieces of dried fruit. My mother used to make fruitcake every year, and we would give the fruitcake to our teachers for Christmas. Maybe that's why I didn't get very good grades when I was in school, I don't know. I'm kidding, of course. My mother made wonderful fruitcake!
The expression fruitcake is also sometimes used to mean someone who's crazy - someone who's not very intelligent. “He's a fruitcake” means he's kind of weird - he's odd - he's unusual.
Lucy says to Adriano, “ Oh, thanks. Make yourselves comfortable. We’re just about to sit down to dinner.” The expression to sit down to dinner is one that we usually use when we are at home and we are going to eat, in this case, dinner. We probably wouldn't say that in a restaurant. But if someone calls you on the phone and you don't want to talk or you don't have time to talk, you could say, if it's five, six, seven o'clock, “We're just about to sit down to dinner” - we're just about to eat. This is a good excuse. There is an expression, a sit down dinner, and that just means a dinner where it is more formal - where everyone is sitting down versus going to McDonald's, for example.
Adriano says, “Wow, it looks like you’ve prepared a feast.” A feast, “feast,” is a large meal, usually for many different people with lots of different types of food. Lucy says, “Yeah, we did go a little overboard this year.” To go overboard means to do beyond what you would normally do - to do a lot, usually to do too much. To be too enthusiastic about something, that would be to go overboard. So, if you have a fight your friend - a disagreement with your friend - and you decide to go and buy him a new car because you want him to be happy, that would be going overboard. That would be doing too much, unless of course, you had ruined or destroyed his car, in which case it would not be going overboard.
Well, Lucy says she's gone overboard, and then she says all of the things that they're going to eat. She says, “We’ve got a turkey,” which is traditional for both Thanksgiving and Christmas in the United States. She also says that they have “a roast and a ham.” These are other two popular foods for Christmas. A roast, “roast,” is a large piece of beef or pork that you cook in an oven. A ham, “ham,” is a kind of pork - meat that comes from a pig. Beef comes from a cow; pork comes from a pig. But we don't say, “I'm going to eat some cow,” or “I'm going to eat some pig,” we say, “I'm going to eat some beef,” or if it's from a pig, “we're going to eat pork.” One type of pork is ham, “ham,” which is, I believe, from the top part of a pig's leg. I don't normally kill my own pigs, but I think that's where it comes from.
Lucy also says that they're going to have all of “the trimmings.” The trimmings, when we talk about food, are the things other than the main meat dish, and she lists what those are. She says they're going to have stuffing, “stuffing,” which is a mix of bread and vegetables, sometimes even fruit, and it's often put inside the turkey or a chicken, maybe duck, and it's cooked inside. It's like little pieces of cooked bread.
Yams, “yams,” is a vegetable - it's an orange vegetable. It's like a sweet potato; sometimes people use the same term but they are a little different. Don't ask me what the difference it is because I don't like yams or sweet potatoes, but Lucy didn't invite me to dinner, did she? She invited Adriano, so it doesn't matter if I like yams or not, I'm not going to eat them!
Mashed potatoes are a type of potato, which again is a vegetable that grows in the ground. Mashed potatoes is when you take the vegetable - the potato - you take the skin off of it - the outside - and you mash it. To mash, “mash,” means to crush - to make into small, little pieces. Normally with mashed potatoes you put some milk in, usually some butter, you mix it altogether and it's - it's very good!
Cranberry sauce, “cranberry” sauce is very popular with turkey, especially at Thanksgiving. Cranberry is a fruit. It is usually combined with some sugar; it's almost like a desert, and it often served with turkey.
Finally, at Lucy's feast they're going to have eggnog, “eggnog.” Eggnog is a special holiday drink that is made from milk and eggs and usually a little alcohol. You can have eggnog with alcohol or without alcohol. Although eggnog and fruitcake are both traditionally popular at Christmas, a lot of people don't like them.
Adriano says, “Thanks. Did you do all of the cooking yourself?” Lucy says that she “had some help and everybody brought different desserts.” She then says to Adriano, “Save room for the pumpkin pie, the gingerbread house, and the Christmas cookies.” The expression to save room for something means don't eat too much now so that you can eat something different later, in this case the dessert, what you eat after the main meal.
A couple of popular desserts for the holidays are pumpkin pie, “pumpkin” pie. A pumpkin is a vegetable that is usually associated with Halloween. The inside of the pumpkin is mixed together with other ingredients, and you make it into a pie that you bake in the oven. You can eat it hot or cold. A gingerbread house is a traditional Christmas dessert that is made of cookies. The cookies are ginger cookies, a type of cookie. You put them into the shape of or you make a little house from the cookies. I, myself, have never eaten a, or part of a gingerbread house, but it is a traditional kind of desert.
Lucy says, “Okay everybody, dinner’s ready. Adriano, would you carve the bird?” To carve, “carve,” the bird usually means to cut the turkey that has been in the oven. You take it out of the oven and you have to cut the pieces of meat off of it. You can also carve a chicken or a duck as well. You put them in a plate - the pieces of meat on a plate and then people can take what they want.
Adriano says, “I’d be happy to do the honors.” The expression to do the honors means usually to do something important, often something official, but here it just means that he will do the carving of the turkey. The expression to do the honors has some different meanings, if you look at today's Learning Guide, you can find out what the other uses of that expression are, as well as the expression to go a little overboard.
Now let's listen to the dialogue, this time at a normal speed.
[Start of story]
This year, our family decided that the more the merrier and invited Adriano and his family to have Christmas dinner with us. We were thrilled when they accepted our invitation.
Lucy: I’m so glad you guys could all make it.
Adriano: We wouldn’t have missed it for anything. We brought a fruitcake.
Lucy: Oh, thanks. Make yourselves comfortable. We’re just about to sit down to dinner.
Adriano: Wow, it looks like you’ve prepared a feast.
Lucy: Yeah, we did go a little overboard this year. We’ve got a turkey, a roast and a ham, and all the trimmings: stuffing, yams, mashed potatoes, and cranberry sauce. Help yourself to some eggnog.
Adriano: Thanks. Did you do all of the cooking yourself?
Lucy: I had some help and everybody brought different desserts. Save room for the pumpkin pie, the gingerbread house, and the Christmas cookies. Okay everybody, dinner’s ready. Adriano, would you carve the bird?
Adriano: I’d be happy to do the honors.
[End of story]
Everyone here at ESL Podcast wishes you and your family a very happy holiday season.
The script for today was written, as always, by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
the more, the merrier – the more people there are, the more fun something will be
* Lydia asked if she could bring her cousins to the party, and I said, “Of course! The more, the merrier!”
thrilled – delighted; very happy
* Magdalene was thrilled to learn that she had been accepted at Boondocks University.
fruitcake – a traditional Christmas cake that contains small pieces of dried fruit
* Ashley doesn’t like raisins, so he always picks them out of the fruitcake.
to sit down to (a meal) – to take a seat at the table and begin to eat a meal
* We had just sat down to dinner when the telephone rang, but we didn’t answer it because we didn’t want the food to get cold.
feast – a very large meal, usually for many people
* The wedding feast was delicious, with enough meat, breads, desserts, and drinks for 300 people.
to go overboard – to be too enthusiastic about something; to do something beyond what one should; to do too much
* Alberto just started a new exercise program, but he’s going overboard and exercising at least two hours a day.
roast – a large piece of uncut beef or pork cooked in an oven
* Grandma Chin has a delicious recipe for a pork roast with an apple-butter sauce.
ham – pork; the meat from the top part of a pig’s leg
* He always has a ham-and-cheese sandwich for lunch.
stuffing – a mixture of chopped bread, herbs, vegetables, and fruits put inside of a turkey, duck, or chicken, and cooked in an oven
* Their family makes a stuffing with apples and carrots. It sounds strange, but it’s very tasty.
yam – a vegetable that is orange-colored that is a root of a plant, similar to a sweet potato
* Do you think we should make some baked yams for dinner?
mashed potatoes – potatoes that have been cooked and then pressed until they are smooth, usually mixed with butter and milk, and served with gravy (a dark brown sauce)
* If you eat too much of the mashed potatoes, you won’t have room for turkey.
cranberry sauce – a dessert that looks like jelly made from cranberries (a type of sour, red berry) and sugar, usually served with turkey for holiday meals
* Could you please pass the cranberry sauce to this end of the table?
eggnog – a holiday drink made from alcohol, eggs, milk, and spices
* Would you like a glass of eggnog or do you prefer soda?
to save room for (something) – to stop eating before one is full, so that one will be able to eat something else later
* I’m glad you like the salad, but please don’t eat too much of it. Save room for the pasta!
pumpkin pie – a dessert baked in an oven, made with soft, sweet pumpkin in the middle and crust (harder edge) on the bottom and sides
* Nancy served us huge slices of pumpkin pie with whipped cream on top.
gingerbread house – a dessert made of cookies flavored with ginger, put together in the shape of a house and decorated with candies
* The girls tried to make a gingerbread house, but it kept falling down, so they decided to just eat the gingerbread by itself.
to carve the bird – to cut an oven-cooked turkey, chicken, or duck into small pieces for each person to eat
* Their grandfather always lets the children help him carve the bird for the Thanksgiving dinner.
to do the honors – to perform a ceremony or ritual; to do an important thing
* We need a close friend to give a speech at our wedding reception. Would you do the honors?
Comprehension Questions
1. Why did the family invite Adriano and his family over for Christmas?
a) The family thought that dinner would be more fun with more people.
b) The family made too much food and needs help eating it all.
c) The family needed someone to bring a dessert.
2. Lucy asks Adriano to:
a) Pour the drinks.
b) Cut the turkey.
c) Bring a fruitcake.
Answers at bottom.
What Else Does It Mean?
to go overboard
The phrase “to go overboard,” in this podcast, means to be too enthusiastic about something or to do too much of something: “We know the food at school isn’t very good, but don’t go overboard while you’re home for the holidays.” Or, “Cynthia went completely overboard when her granddaughter was born, buying far too many presents for the baby.” The phrase “to fall overboard” or “to jump overboard” can mean to fall or jump over the side of a boat or a ship into the water, usually accidentally. For example, “The child was playing too close to the edge of the boat, and he accidentally fell overboard into the cold water.” On a boat or ship, one should shout, “Man overboard!” to make other people aware that someone has fallen into the water.
to do the honors
In this podcast, the phrase “to do the honors” means to perform a ceremony or ritual. or to take on an important responsibility: “Maria couldn’t cut her birthday cake because her arm was broken, so her mother did the honors.” To graduate “with honors” means to graduate with very good grades, as one of the best students: “Adam received a lot of job offers because he graduated with honors from a very good university.” The word “honor” means something that one is very proud of: “It was an honor to be asked to speak at the conference.” “Honor” can mean great admiration or respect when it is used in phrases such as “the guest of honor” or “the seat of honor”: “When will the guest of honor, Dr. Gopal, be arriving for dinner?” Judges are sometimes called “Your Honor.”
Culture Note
Christmas “carols” are traditional Christmas songs. Some songs are religious, but others are about Santa Claus and presents, and others are about the joyful or happy feeling around Christmas. In some cities and towns, small groups of people go “Christmas caroling,” singing carols at hospitals, at nursing homes for the elderly (or older people), or on neighborhood streets. Often people invite the carolers inside their homes to eat Christmas cookies and drink hot chocolate or hot “apple cider” (hot apple juice mixed with sugar, cinnamon, and other spices).
At Christmastime, it is common to see a large, decorated tree in the middle of many American towns. These trees are often decorated with lights, colored balls, dolls, or images of animals. A man dressed as Santa Claus often sits in front of the tree. Young children sit on his “lap” (the space on the upper part of one’s legs when one sits down) and tell him what they would like to receive for Christmas. Then Santa Claus tells them to be good and gives them a “candy cane” (a red-and-white, hard candy in the shape of a “cane” or walking stick).
Other, smaller trees are often placed inside office buildings and shopping malls. These “giving trees” have special paper decorations. One side of the decoration has a holiday drawing and the other side has the name and age of a poor child, with that child’s “wish” or something that the child wants. People take an “ornament” (decoration), buy the gift that the child wants, and then “wrap” it (cover it in colored paper). They place the present under the tree and the presents are given to poor children on Christmas day. Other people choose to “adopt” an entire family, providing gifts and holiday food for a poor family that doesn’t have enough money to celebrate the holiday.
Comprehension Answers
1 - a
2 - b