= 0231
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 231: The Supermarket Checkout.
This is English as a Second Language Podcast episode 231. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com and download the Learning Guide for this episode. This is an eight to ten page document that contains all of the vocabulary, definitions, cultural notes, additional vocabulary we don't talk about on the podcast, as well as a complete transcript of this episode.
Our episode is called “The Supermarket Checkout.” Let's go!
[Start of story]
I went to the supermarket to do my weekly shopping. The cashiers at this market are usually pretty friendly, but this one must have been having a hard day.
Cashier: Excuse me, sir, this lane is for 15 items or less. It looks like you have more than that.
Yong: No, actually I have exactly 15. I have some coupons, too.
Cashier: Just put those down on the belt and push the cart through, please.
Yong: Okay. Can you tell me how much these potatoes are per pound?
Cashier: I’ll have to do a price check. Do you have a club card?
Yong: Yes, here it is.
Cashier: Swipe it through the machine, sir. Your total is $47.52. Debit or credit?
Yong: Debit. Could I get cash back?
Cashier: [sigh] How much do you want?
Yong: I’d like $40.
Cashier: Paper or plastic?
Yong: Paper, please.
Cashier: Are these tabloids yours, too?
Yong: Uh, yes, those magazines are mine.
Cashier: Do you need any help out?
Yong: No, I’m fine. Thanks.
[End of story]
We take a trip to the grocery store - the store where you buy food, sometimes called a supermarket, and we are at the checkout stand - the place where you pay. To check out, at a grocery store, means to pay for the food that you are buying.
Our dialogue begins with Yong saying, “I went to the supermarket to do my weekly shopping. The cashiers at this market are usually pretty friendly.” A cashier, “cashier,” is the employee - the person who works for the store who takes your money. You can recognize the word cash, “cash” - which means money - in this word.
The cashier apparently was “having a hard day,” or a difficult day. She begins by saying to Yong - the customer - “Excuse me, sir, this lane is for 15 items or less. It looks like you have more than that.” At American grocery stores, there's usually one or two checkout stands - places for you to pay - for those that have ten things or less, or perhaps 15 things or less. So, if you're just buying a bottle of Coca-Cola and a pizza, you can go to the, what is sometimes called the express, “express,” the express lane. A lane, “lane,” in this case, is just the line - the place where you are standing waiting for the cashier to take your money.
This cashier is telling the person in the dialogue that they have more than 15 items and they can't be in the express lane. Yong says, “No, actually I have exactly 15,” actually meaning in fact I have exactly 15, not 16, not 14. He also says, “I have some coupons, too.” A coupon, “coupon,” is a small piece of paper, usually from a newspaper or advertisement, that gives you a lower price. Sometimes it will be a dollar less or five percent less on one particular food item. This, of course, encourages you to buy that type of food.
The cashier says, “Just put those down on the belt and push the cart through, please.” She's not very happy. She's telling Yong to put those down, meaning put his items - items is just another word for thing - put those things down on the belt, “belt.” The belt here is a wide piece of rubber or soft plastic that moves in a circle to take the groceries from one end of a checkout stand to the other. So, it's like an automatic method of moving the food closer to the cashier so he or she can get the price from it.
This word, belt, has other meanings in English as well. If you look at today's Learning Guide, we talk about so additional meanings of the words belt as well as the word lane, which we just finished explaining.
The cashier tells Yong to “push the cart,” “cart,” “through.” A cart is like a large basket on wheels. It's what you put your food in, in a grocery store - in a supermarket - and you push it towards the front - towards the checkout stands, and you take the food out of it and you put it on this belt that takes the food to the cashier.
Yong says, “Okay. Can you tell me how much these potatoes are per pound?” Per pound just means for each pound. We, in the United States, use pounds as the way of measuring weight. The cashier then tells Yong, “I’ll have to do a price check.” A price check, “check,” is when the employee has to ask someone else to get the actual price of something for a customer. This happens sometimes in supermarkets, and that's what the cashier is doing here.
She then asks if Yong has “a club card,” “club,” card, “card.” This is like a membership card that some grocery stores have. In order to shop at the store, you have to have a membership - you have to pay a membership, and usually that gives you lower prices. There are other stores that give you a card, and if you use the card, you get a discount. You don't have to pay for the card, but you do get a lower price on some of your food.
After the cashier asks Yong for his club card, Yong says, “here it is,” something you might say when you are giving something to someone else. He could also say, “here you go.” The cashier tells him to “Swipe it through the machine.” The verb to swipe, “swipe,” in this case means to take your credit card and put it through, very quickly, through a little machine that reads your information so that the store can charge your credit card for the amount. The verb swipe can also mean to steal, especially if you're talking about something small, like “I'm going to swipe a pencil from my wife's desk” - I'm going to steal it. I'm sure she's okay with that, though!
The cashier then asks Yong, “Debit or credit?” These are two different ways of paying for something. A credit card is when the bank lends you money for 30 days or for a longer period of time until you pay them back; that's a credit card. A debit card, “debit,” is one where you have the money taken out of your bank account right away, so there's no loan involved. That is also a popular way of paying for things at stores.
Yong says that he has a debit card, and asked if he could “get cash back?” One of the advantages of using a debit card, which takes money directly from your bank, is you can actually ask the cashier in most grocery stores to give you some additional money from your account, just like they were a bank or an automatic teller machine - the machine you get money for automatically when you put in the card.
Of course, this is more work for the cashier, so she says, “How much do you want,” not very nice. And he says, “I’d like 40 dollars.” The cashier then asks him, “Paper or plastic?” What the cashier is asking here is whether Yong wants paper bags to put the food in or plastic bags. Most grocery stores give you the choice of which kind you want. Unlike in some countries, most Americans don't bring a bag with them to put the food in; they have the store give them the bag.
Yong asks for paper, and the cashier says, “Are these tabloids yours, too?” A tabloid, “tabloid,” is a kind of newspaper or magazine, usually one that has very shocking or unusual stories. Many of these are about famous people - celebrities - and they like to print or have lots of stories in them about Britney Spears and her baby or Angelina Jolie. Other famous Hollywood stars are often in these tabloids because people will buy the paper. They're very low quality type of newspaper. The most famous one in the United States would be “The National Inquirer.” To inquire means to ask about. So, “The National Inquirer” is a tabloid that you would find, and they usually have these by the checkout stands in the grocery stores.
Yong says yes, these “magazines are mine,” and the cashier finally says, “Do you need any help out,” meaning do you need someone to help you take your food - your groceries - to your car. Notice that the cashier doesn't say, “Do you need any help,” she says, “Do you need any help out,” and that's a particular type of verb that we would use in this situation when you're at a store - a grocery store - and the cashier is asking if you need help to take the food to your car. Yong says, “No, I’m fine. Thanks.”
Now let's listen to the dialogue, this time at a native rate of speech.
[Start of story]
I went to the supermarket to do my weekly shopping. The cashiers at this market are usually pretty friendly, but this one must have been having a hard day.
Cashier: Excuse me, sir, this lane is for 15 items or less. It looks like you have more than that.
Yong: No, actually I have exactly 15. I have some coupons, too.
Cashier: Just put those down on the belt and push the cart through, please.
Yong: Okay. Can you tell me how much these potatoes are per pound?
Cashier: I’ll have to do a price check. Do you have a club card?
Yong: Yes, here it is.
Cashier: Swipe it through the machine, sir. Your total is $47.52. Debit or credit?
Yong: Debit. Could I get cash back?
Cashier: [sigh] How much do you want?
Yong: I’d like $40.
Cashier: Paper or plastic?
Yong: Paper, please.
Cashier: Are these tabloids yours, too?
Yong: Uh, yes, those magazines are mine.
Cashier: Do you need any help out?
Yong: No, I’m fine. Thanks.
[End of story]
The script for today's podcast was written by Dr. Lucy Tse.
That's all we have time for. From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
cashier – a store employee who takes the money for things that a customer buys and provides a receipt
* The cashier said he couldn’t help me with the clothes I wanted to buy because he works only in the shoe department.
lane – a narrow (small and long) area in a grocery store where shoppers stand in a line to wait for a cashier to help them make their purchases
* I wanted to use the express lane at the grocery store, but in that lane, people can pay only with cash and I needed to use a credit card.
15 items or less – a restriction at express (fast) checkout lanes at a grocery store, meaning that only people buying 15 or fewer items may use that lane
* Mindy became very angry when she saw that the woman in front of her had at least 20 items in her basket, even though the sign clearly said, “15 items or less.”
coupon – a small piece of paper usually cut from an advertisement or a newspaper that gives a shopper a lower price on a particular item
* Brice found a coupon for $0.35 off his favorite brand of shampoo in the magazine.
belt – a wide band of rubber (soft plastic) that moves along the counter at a checkout lane to move groceries from the end where the shopper is taking items from their cart to the other end where the cashier is checking prices
* Please don’t let your child play with the belt! His fingers might get caught underneath it and I don’t want him to get hurt.
cart – a large basket with wheels and a handle that is pushed through a store by a shopper, who fills it with the items that he or she wants to purchase
* Every time I go to the grocery store, I get a cart that has broken wheels!
per pound – for each pound (one pound is approximately 2.2 kilograms)
* In the early summer, strawberries are very inexpensive, but in the winter, they can cost up to $5 per pound!
price check – an employee in a store asking or finding out the price of something for a customer
* I thought the TV was on sale, but the cashier’s computer showed that it cost more than $500, so I asked her to do a price check to make sure.
club card – a membership card that gives shoppers lower prices on many items
* With a club card, my favorite ice cream is only $1.50 this week.
to swipe – to quickly move one’s card through an electronic machine that gets information from the card about the cards’ owners and their accounts
* I swiped my credit card four times, but the machine couldn’t read it, so the cashier had to type in the account number by hand.
debit – a type of card that deducts money directly from a person’s checking account; to take money out of an account
* He tried paying for his purchase with his debit card, but the computer told the cashier that he didn’t have enough money in his account.
credit – a type of card that connects to a credit card account and allows a person to buy something now and pay for it later
* When I got my first credit card, my father warned me that if I don’t pay the entire credit card bill every month, I’d have to pay a lot of interest.
cash back – money in cash (dollars and coins) that one receives at the end of a debit-card transaction by adding that amount to the total amount of the purchase
* Going to the bank to get cash is inconvenient, so we usually ask for cash back at the grocery store instead.
Paper or plastic? – a phrase used by grocery store cashiers or baggers to ask shoppers if they would prefer to have their purchases placed in paper or plastic bags
* When the cashier asked, “Paper or plastic?” Sharon pointed to the cloth bags that she had brought from home and asked them to put her items in those instead.
tabloid – a newspaper with scandalous (shocking) stories about unusual events or famous people, usually which cannot or should not be believed
* Reading the tabloids is a waste of time. Why don’t you read about world news instead?
Do you need any help out? – a phrase used by grocery store cashiers to ask shoppers if they want someone to help them carry their purchases to their car
* The cashier asked me if I needed any help out, but I said “no” because I only had one small bag of groceries.
Comprehension Questions
1. Why does the cashier ask Yong “Paper or plastic?”
a) He wants to know whether Yong wants a paper bag or a plastic bag.
b) He wants to know whether Yong will pay with cash or with a credit card.
c) He wants to know whether Yong wants a paper receipt or a plastic receipt.
2. How much money is deducted from Yong’s account?
a) $47.52 (the total price of the groceries).
b) $7.52 (the total price of the groceries minus a $40 gift).
c) $87.52 (the total price of the groceries plus $40 in cash).
Answers at bottom.
What Else Does It Mean?
lane
The word “lane,” in this podcast, means a narrow (small and long) section in a grocery store where shoppers form a line to wait for a cashier to help them make their purchases: “The grocery store was busy yesterday evening and there were at least five people waiting in each lane.” A “lane” can also be a small road, usually in the countryside: “He lives is the lane behind that big farm.” On a larger road, a “lane” is marked by white or yellow lines and is used to keep cars in a straight line: “In the U.S., the slow lane is on the right and the passing lane is on the left.” A “lane” is also a marked section in a swimming pool or on a racetrack used to keep competitors out of each other’s way: “Which lane is your brother running in?”
belt
In this podcast, the word “belt” means a wide band of rubber (soft plastic) that moves in a circle over a table to carry items from one end of a table to another: “The luggage belts at the airport were broken, so the poor employees had to carry all the suitcases by hand.” A “belt” is also a narrow strip of leather, cloth, or metal worn around one’s waist to keep your pants on: “If you’re going to wear a black suit, you should wear a black belt, not a brown one.” As a verb, “to belt” is used informally to mean to hit something or someone very hard. For example, “The baseball player belted the ball and it flew over the fence.” “To belt” can also be used informally to mean to sing very loudly: “At the college football game, the fans from our school belted out our school song when one of the players scored a touchdown to win the game.”
Culture Note
In the United States, large grocery stores sell many thousands of products and it can sometimes be difficult to find what you’re looking for. For this reason, large stores are divided into several departments so that shoppers can know where to find certain items.
For example, a “meat department” sells chicken, pork, and beef, and the employees will usually cut meats to whatever size or shape the customer requests. A “seafood department” sells fresh fish and the employees give shoppers advice about how best to cook different types of fish. A “frozen foods department” is usually a store “aisle” (row) of refrigerators to keep foods cold. It offers frozen meats, frozen microwaveable meals, frozen fruits and vegetables, frozen juices, ice cream, and more.
A “produce department” is full of fresh fruits and vegetables. A “bakery department” sells breads, cookies, and cakes. Many bakery departments will create specially decorated cakes for customers’ birthdays, weddings, or holiday celebrations.
Some stores have an “ethnic foods department” where shoppers can find unusual food items that are associated with a particular culture, such as Mexican, Thai, or Chinese foods. Other stores have an “organic foods department” where shoppers can find “organic” foods that are grown without chemicals.
Some larger stores even have “flower departments” where shoppers can purchase “bouquets” (arrangements) of fresh flowers. Many expensive stores have a “wine department” that is filled with many types of wines, and expensive grocery stores often pay a wine expert to help customers choose their wines.
Comprehension Answers
1 - a
2 - c