= 0407
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 407: Waiting for a Man or Woman to Call.
This is English as a Second Language Podcast episode 407. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, an 8 to 10 page guide we provide that will help you improve your English even faster. You can also take a look at our ESL Podcast Store, which has additional courses in English.
This episode is a dialogue between Lyla and George about waiting for someone you are romantically interested in to call you back on the telephone. Certainly an experience most of us have had! Let’s get started.
[start of dialogue]
Lyla: Okay, here’s a hypothetical. You ask a girl for her number, but wait two weeks to call her. What gives?
George: Well, that depends. Why?
Lyla: Well, I met this guy two weeks ago at a party. We spent the entire evening talking and I thought we really hit it off. We had a lot of chemistry and we had a ton of things in common. He asked for my number and he said he’d call me the next day. And then, I didn’t hear hide nor hair of him until yesterday, 10 days after we met. How come?
George: What did he say when he called? What was his pathetic excuse?
Lyla: I didn’t talk to him. I wasn’t home and he left a voicemail message. I haven’t called him back yet.
George: Why don’t you just call him and find out?
Lyla: He just called yesterday and I don’t want to seem desperate.
George: Oh, come on. He probably just lost your number and found it yesterday.
Lyla: That’s possible.
George: Or he had to go out of town and just got back.
Lyla: I suppose.
George: Or maybe he was nervous about calling you and just got up the nerve.
Lyla: Do you really think so?
George: Maybe. Or maybe he’s playing hard to get or he’s just not that into you.
Lyla: Oh.
George: But you won’t know if you don’t call him back.
Lyla: I guess that’s true.
[end of dialogue]
We begin with Lyla saying to George, “Okay, here’s a hypothetical.” A “hypothetical” or “hypothetical situation” is a situation that could happen or might happen but has not actually happened, so it’s imaginary. This is the hypothetical, or hypothetical situation Lyla gives to George: “You ask a girl for her number (her telephone number), but wait two weeks to call her.” “Number” has a couple of different meanings; take a look at our Learning Guide for some additional explanations.
So, Lyla is saying what would happen if you asked a girl for her telephone number, and then waited two weeks to call her. She says, “What gives?” which is an informal expression when you want an explanation of something that you don’t understand. Often we use that expression when we’re a little frustrated perhaps. So Lyla wants to know, basically, why someone would wait two weeks to call a woman whose number he’s asked for.
George says, “Well, that depends,” meaning it can be determined by something else; it’s affected or decided by someone else. When someone says “that depends,” they mean it depends on, or is affected by some other information – something else in the situation. Then he says, “Why?”
Then Lyla gives the real story, not a hypothetical situation. She says, “Well, I met this guy two weeks ago at a party. We spent the entire evening talking (we talked the whole evening) and I thought we really hit it off.” To “hit it off” with someone means to get along very well with that person, usually the first time you meet them; to quickly become friends with another person. Many people who get married say that the first time they met their future husband or wife they really hit it off.
Lyla says she hit it off with this gentleman – this man. She says, “We had a lot of chemistry and we had a ton of things in common.” “Chemistry,” when we are talking about a man and a woman or romance, has to do with the attraction between two people – the romantic feelings you have for that other person. She felt they “had a lot of chemistry and a ton of things in common.” A “ton,” here, just means a lot, many, or much. Technically, a ton refers to something that weighs 2,000 pounds, but we use it informally to mean a lot of something. So, “we had a ton of things,” she says, “in common,” meaning that we shared similar interests. “Common” has many definitions in English; take a look at our Learning Guide for some additional explanations.
Lyla continues, “He asked for my number and he said he’d call me the next day (the following day, the day after). And then, I didn’t hear hide nor hair of him until yesterday, 10 days after we met. How come?” The expression not to hear or see “hide (hide) nor hair (hair)” of someone means that you haven’t heard from or seen someone for a certain amount of time, usually a long time. Literally, “hair” is, of course, what grows on the top of your head – well, not my head, but most people’s heads! “Hide” is usually the word we use to describe the skin of an animal, such as a cow. But the expression, “I haven’t seen hide nor hair,” means I haven’t seen anything or heard anything from this person in a long time.
At the end she asks George, “How come?” “How come?” is a way of saying why, it’s the same thing as “what gives?” – somewhat informal expression. For what reason, you’re asking. It can usually be used the same as “why.” For example: “How come you are going to the movies with him and not with me (why are you going to the movies with him and not me)?” and she says, “Oh, well, you’re ugly!” So, that’s how come!
George says, “What did he say when he called? What was his pathetic excuse?” When we say something is “pathetic” (pathetic), we mean it’s irritating, it’s annoying, it’s not adequate, it’s not enough. It’s a very negative way of describing a situation or a person.
Lyla says, “I didn’t talk to him. I wasn’t home and he left a voicemail message. I haven’t called him back yet” – I haven’t returned his call. George says, “Why don’t you just call him and find out?” – why don’t you call him and ask him why he didn’t call you for so long? Lyla says, “He just called yesterday and I don’t want to seem (or appear) desperate.” Someone who is “desperate” is willing to do anything to make something happen; someone who is very eager for something to happen, perhaps because you don’t have any other choices or options. Lyla says she doesn’t want to seem desperate; she doesn’t want to seem as though she is the one who really wants to go out with this guy. This is a little game that men and women play, of course. When they first are interested in each other, neither one wants to seem as though they need the other person. That’s just part of the strange human romantic reactions that we have.
George says, “Oh, come on (meaning oh, be reasonable – be sensible). He probably just lost your number and found it yesterday.” Lyla says, “That’s possible.” George says, “Or he had to go out of town (he had to leave the city) and just got back (just returned).” Lyla says, “I suppose,” meaning okay, maybe. George then gives another possible reason, “Or maybe he was nervous about calling you and just got up the nerve.” To “get up the nerve” (nerve) means to become brave enough to do something, to get enough courage to do something. You may have to get up the nerve to ask your boss for a raise – for more money.
Lyla says, “Do you really think so?” George says, “Maybe. Or maybe he’s playing hard to get or he’s just not that into you.” To “play hard to get” means to act like you are not interested in, even though you are interested. This, again, is a game that men and women play with each other – boys and girls as well. You give the impression to the other person that you are not that interested, hoping that they’ll be more interested in you. Some people are attracted to others who are difficult to get – who are difficult to get a relationship with. You play hard to get – you act as though you don’t want to be with that person. The other possibility George gives is that this man is “just not that into you.” When we say someone is “not into” someone, we mean they aren’t interested in them romantically – they’re not interested in dating that person. You could say, “Oh, he’s just not that into you,” or “She’s just not that into you,” meaning he or she doesn’t really like you.
Lyla say, “Oh.” George then says, “But you won’t know if you don’t call him back.” That is, you can’t find out the truth unless you call him. Lyla says, “I guess that’s true.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lyla: Okay, here’s a hypothetical. You ask a girl for her number, but wait two weeks to call her. What gives?
George: Well, that depends. Why?
Lyla: Well, I met this guy two weeks ago at a party. We spent the entire evening talking and I thought we really hit it off. We had a lot of chemistry and we had a ton of things in common. He asked for my number and he said he’d call me the next day. And then, I didn’t hear hide nor hair of him until yesterday, 10 days after we met. How come?
George: What did he say when he called? What was his pathetic excuse?
Lyla: I didn’t talk to him. I wasn’t home and he left a voicemail message. I haven’t called him back yet.
George: Why don’t you just call him and find out?
Lyla: He just called yesterday and I don’t want to seem desperate.
George: Oh, come on. He probably just lost your number and found it yesterday.
Lyla: That’s possible.
George: Or he had to go out of town and just got back.
Lyla: I suppose.
George: Or maybe he was nervous about calling you and just got up the nerve.
Lyla: Do you really think so?
George: Maybe. Or maybe he’s playing hard to get or he’s just not that into you.
Lyla: Oh.
George: But you won’t know if you don’t call him back.
Lyla: I guess that’s true.
[end of dialogue]
The script for this episode was written by a woman with a ton of talent, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
hypothetical [situation] – a situation that could happen or might happen, but
has not actually happened
* During the interview, they described a hypothetical and asked how he would act if it actually happened.
number – phone number; telephone number
* The company’s phone number is easy to remember. It’s 686-8686.
What gives? – an informal expression used when one wants an explanation because one does not understand how or why something happened
* You said you wanted to buy the car, but then when it was actually time you changed your mind. What gives?
to depend – to be affected, decided, or determined by something else
* I’d like to go to Alaska this summer, but it depends on my being able to save enough money for the trip.
to hit it off – to get along well with another person at the first meeting; to quickly become friends with another person
* Billy and Joey hit it off on the first day of elementary school and have been best friends ever since.
chemistry – an attraction between two people, especially in a romantic way
* I want to introduce Samantha to Gyon because I think they’d have great chemistry together.
a ton – a lot; many; much
* That little boy has a ton of toys in his room.
in common – shared; with the same interests; relating to two or more people
* Jane and I have two things in common: we both like to ride bicycles and we both hate eating peas.
to not see/hear hide nor hair of (someone) – to not have seen or heard from someone for a period of time
* They haven’t seen hide nor hair of their father in more than 10 years.
How come? – why?; for what reason?
* - I don’t want to see that movie.
* - How come?
* - Because I think it will be too scary for me.
pathetic – annoying, weak, and irritating; inadequate
* The student wrote such a pathetic report that I don’t even think he read the book.
desperate – willing to do anything to make something happen; very eager for something to happen because one does not have any other options
* Dr. Kosek is really tired of working and is desperate to take a vacation, but he can’t do it because there is too much work to do.
to get up the nerve – to become brave enough to do something; to get enough courage to do something
* Jesse is trying to get up the nerve to ask his employer for more money.
to play hard to get – to act like one is not interested, even though one is really very interested; to pretend that something is not important, especially a romantic relationship
* Becky likes Zachariah, but she’s playing hard to get, saying “maybe” every time he asks her to go on a date.
not that into (someone) – not very interested in someone romantically; not very interested in dating someone
* We’ve had dinner together a few times, but I’m really not that into her.
Comprehension Questions
1. What happened at the party that Lyla describes?
a) She met a guy who hit her.
b) She met a guy who studied chemistry.
c) She met a guy whom she liked.
2. What might make Lyla seem desperate?
a) If she called the guy back too soon.
b) If she had a pathetic excuse.
c) If she couldn’t get up the nerve.
Answers at bottom.
What Else Does It Mean?
number
The word “number,” in this podcast, means a phone number: “Is this number for your cell phone or your home phone?” A “number cruncher” is an informal way to talk about an accountant or a bookkeeper, or someone who records financial information for a company: “She’s studying accounting because she wants to be a number cruncher.” The phrase “(someone’s/something’s) days are numbered” means that someone or something cannot continue to live or exist for very much longer: “He keeps making major mistakes and his days at this company are numbered.” Finally, the phrase “to be numbered among (something)” means to be included in a group of something: “His novels are numbered among the greatest books in the English language.”
in common
In this podcast, the phrase “in common” means shared or relating to two or more people, or with the same interests: “The two sisters have nothing in common and they fight with each other all the time.” The “common cold” is a cold that isn’t very serious but many people have it: “My throat hurts and I’m coughing a lot, but the doctor says it’s just the common cold so there’s no need to worry.” The phrase “common sense” refers to how much a person knows about how the world works and whether he or she is able to act in a logical, practical way that makes sense: “Anyone with common sense would know that you can’t buy a good car for just $400.”
Culture Note
In the United States, when men and women meet and are interested in each other romantically, they often try to “exchange” phone numbers, meaning that each person gives the other person his or her number. Both men and women can ask for a phone number, although it is probably more “common” (usual) for a man to ask a woman for her number first.
Usually the number is written down on a small piece of paper or “programmed” (entered electronically) into a cell phone. Then the “expectation” (what people think will happen) is that the person will call that number within a few days. Asking for someone’s number but then not calling is often considered “rude” (not polite).
Sometimes people don’t want to give out their phone number, but it can be difficult to say that without “hurting someone’s feelings” (making someone feel bad). So some people, especially women, will give out a “fake” (false; not true or real) phone number. When the man calls that number, he will be angry and “embarrassed” (ashamed) that he was given a fake, but at least he wasn’t embarrassed in front of his friends by having a woman “refuse” (say “no”) to give him her phone number.
When Americans talk about men who collect many women’s phone numbers, they say that they have a “little black book” of phone numbers. This would be a small book that one keeps in one’s pocket to write down phone numbers and addresses. A man who has a little black book can choose among many women to call when he is bored or lonely and wants to go out on a date.
Comprehension Answers
1 - c
2 - a