= 0412
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 412: Corporate Spying.
This is English as a Second Language Podcast episode 412. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there and download a Learning Guide for this episode, an 8 to 10 page guide that gives you all of the vocabulary, definitions, new sample sentences, additional definitions not found in this audio podcast, cultural notes, comprehension checks, and a complete transcript of everything that you hear.
This episode is a dialogue between Joachim and Dawn. They’re going to be talking about spying, trying to get secret information from another company, and in the process they’ll use a lot of different vocabulary to talk about spying and corporate secrets. Let’s get started.
[start of dialogue]
Joachim: I’m really having second thoughts about hiring a firm to do corporate spying for us. I don’t want to do anything that’s ethically questionable.
Dawn: We have no choice but to do it. All of our competitors conduct corporate espionage.
Joachim: I can understand spying on our competitors, but I draw the line at having us snoop on our own employees.
Dawn: We wouldn’t unless our backs were against the wall. I know you’re thinking about Hewer Placket hiring investigators to find a leak in their company. I’m sure it was a hard decision for them, but they couldn’t allow anyone in their own company to leak trade secrets.
Joachim: True, it was necessary, but I don’t like being deceptive with our own employees. I won’t allow wiretaps or any invasion of privacy.
Dawn: Our first priority would be damage control, not privacy. In any case, we’re not making a decision to spy within the company right now. We’re only after our rival’s information. The investigators we’re hiring know the difference between legal and illegal spying. They’ll schmooze at trade shows, scour legal records, and do other things like that. They’ll know where to draw the line.
Joachim: I hope you’re right. I don’t want to end up on the front page of the Times!
[end of dialogue]
Our dialogue begins with Joachim saying, “I’m really having second thoughts about hiring a firm to do corporate spying for us.” When someone says they have “second thoughts” about something, they mean that they feel like, perhaps, they made the wrong decision, that they need to change their mind about something. You are reconsidering an issue. Joachim is having second thoughts about hiring (paying) a company (a firm) to do corporate spying for them. “Corporate spying” is trying to find out as much as you can about another company, including information that may not be publicly available. Joachim says, “I don’t want to do anything that’s ethically questionable.” When we talk about something being “ethical,” or the adverb “ethically,” we mean right or wrong, good or bad, moral or immoral. Lying, according to most people, is ethically wrong. Or we might just say it’s “unethical.” When someone says its “unethical,” they mean it’s not ethical – it’s not right. Joachim says it’s “ethically questionable.” Something that is “questionable” is problematic; it is something that may be right but may not be right, it may not be very clear.
Dawn says, “We have no choice but to do it (we have to do it). All of our competitors (the people who have similar companies) conduct corporate espionage.” “Espionage” (espionage) is just another word for spying, to send somebody to find out secret information about another organization, another person, and, of course, another country.
Joachim says, “I can understand spying on our competitors, but I draw the line at having us snoop on our own employees.” The expression “to draw the line at something” means that this is the last thing you are willing to do; the most extreme thing you are willing to do. So you may do a lot of different things, each one moving more and more towards a point where you don’t want to do any more. For example, someone may cheat on an exam in a teacher’s class, and the teacher says, “Okay, I’m going to forgive you.” Then the student cheats again and the teacher says, “I’ll forgive you this time, but I’m going to draw the line at two times that you cheat. After that, I won’t forgive you.” So, that’s to draw the line at something.
Joachim draws the line at snooping on his own employees. To “snoop” (snoop) means to spy; it means the same thing as spying on someone, getting secret information from them. Sometimes we use the word “snoop” to refer to something that isn’t quite as serious as spying; trying to find out information about another person, but it’s not exactly trying to get secret information about them. So, “snoop” is often used as a more informal, perhaps less serious kind of spying.
Dawn says, “We wouldn’t (meaning we would not snoop on our own employees) unless our backs were against the wall.” The expression “to have your back against the wall” means that you do not have any other options; you have only one thing that you can do; you are desperate. “Our backs are against the wall” – we have to do this, we have no other choice. Dawn says, “I know you’re thinking about Hewer Placket hiring investigators to find a leak in their company.” Dawn is talking about another company called Hewer Placket, which of course is not a real company – although it does sound a lot like a famous computer company that was spying on its own employees and finding information about them. But, that’s just a coincidence!
This other company, then, had hired investigators to find a leak (leak). A “leak” is someone who is giving secret information to people outside of your organization or company; it’s allowing secret information to somehow end up in the hands of another person outside of your organization. This is a problem in government, when the government tries to keep secret information and then somebody takes that from inside the government and gives it, for example, to a newspaper. That would be called a “leak.” The word “leak” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
So, Dawn is saying yes, I know you’re thinking about that other company, “I’m sure it was a hard decision for them, but they couldn’t allow anyone in their company to leak trade secrets.” “Trade secrets” refers to secret information about how you do your business – how you conduct your business. Trade secrets would be anything that a company doesn’t want other people to know. For example, Coca-Cola doesn’t want anyone to know its recipe, how it makes its soda; that would be a trade secret.
Joachim says, “True, it was necessary (for this other company to snoop on their own employees), but I don’t like being deceptive with our own employees.” To be “deceptive” means to lie, to not tell the truth. So, Joachim doesn’t want to lie to his own employees. He says, “I won’t allow wiretaps or any invasion of privacy.” “Wiretaps” (wiretaps) is when someone listens secretly to your conversation, either on the telephone or in a building somewhere; they’re listening and usually recording your conversation without your knowledge. This is something that the government in many countries, including this country, has done with its own citizens to get information about them. This is a very controversial issue in the United States, wiretapping American citizens or others to get to get information usually for reasons of national security – or at least that’s the official reason! An “invasion of privacy” is when someone violates your right to keep your personal information secret. “Privacy” refers to a situation where no one can see you or observe you, or know about what you are doing. An “invasion” is normally when one country goes into another country using military force, an army or a navy for example. Here, “invasion of privacy,” however, means that your privacy has not been kept; someone has been observing you without your permission.
Dawn says, “Our first priority (our first thing that we need to do – the most important thing) would be damage control, not privacy.” “Damage control” is when you try to make a bad situation look better than it is, to make it as good as you can. So something goes wrong and your company, for example, makes a product that doesn’t work. Well, you want to do damage control; you want to make sure the problem is not any worse or gets any worse, perhaps by refunding the money to all of your customers.
Dawn says, “In any case, we’re not making a decision to spy within the company right now (inside the company). We’re only after our rival’s information.” “Rival” is another word for a competitor, a person or a company that you are competing against that, perhaps, sells the same kind of thing as you do. Dawn says, “The investigators we’re hiring know the difference between legal and illegal spying. They’ll schmooze at trade shows, scour legal records, and do other things like that.” To “schmooze” (schmooze) means to have a casual, informal conversation with other people, usually so that you can get to know more important people so that you can make contacts. Another verb we use here would be to “network,” to meet other people in your particular industry, your particular field, in order to find more information or perhaps to get a better job; there are a lot of reasons why someone might schmooze. To “scour” (scour) means to look through many things trying to find a very specific piece of information. “Scour” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Dawn says these investigators “know where to draw the line.” Joachim says, “I hope you’re right. I don’t want to end up on the front page of the Times!” – I don’t want, at the end of this situation, for my name or picture to be on the front page of the newspaper, The New York Times. Usually in the U.S., when someone refers to the Times, they’re usually talking about the largest, or one of the largest national newspapers, The New York Times. There are, however, many newspapers call the Times, including here in Los Angeles, The Los Angeles Times.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Joachim: I’m really having second thoughts about hiring a firm to do corporate spying for us. I don’t want to do anything that’s ethically questionable.
Dawn: We have no choice but to do it. All of our competitors conduct corporate espionage.
Joachim: I can understand spying on our competitors, but I draw the line at having us snoop on our own employees.
Dawn: We wouldn’t unless our backs were against the wall. I know you’re thinking about Hewer Placket hiring investigators to find a leak in their company. I’m sure it was a hard decision for them, but they couldn’t allow anyone in their own company to leak trade secrets.
Joachim: True, it was necessary, but I don’t like being deceptive with our own employees. I won’t allow wiretaps or any invasion of privacy.
Dawn: Our first priority would be damage control, not privacy. In any case, we’re not making a decision to spy within the company right now. We’re only after our rival’s information. The investigators we’re hiring know the difference between legal and illegal spying. They’ll schmooze at trade shows, scour legal records, and do other things like that. They’ll know where to draw the line.
Joachim: I hope you’re right. I don’t want to end up on the front page of the Times!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse. How does she write such good scripts? Well, that’s a trade secret!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
second thoughts – reconsideration; the feeling that one should change one’s mind about something; the feeling that one should not do something as planned
* They wanted to go to Hawaii for vacation, but then they found out how much money it would cost and they started to have second thoughts.
corporate spying – the practice of one company learning all that it can about another company (a competitor) without letting that other company know
* Do you think Microsoft and Apple pay for corporate spying on each other?
ethically – related to what is right and wrong, or moral and immoral
* Ethically speaking, lying is wrong, but sometimes it is necessary.
questionable – subject to question or interpretation; not 100% right or wrong; problematic
* The student said that the dog ate her homework, but her teacher thought it was a questionable excuse.
espionage – spying; the practice of sending someone to learn something secretly about another person, organization, or plan
* The man had been selling national secrets to his home country for more than 15 years before he was arrested for espionage.
to draw the line at (something) – to say that something is the last thing that one will do; to identify the most extreme thing that is acceptable, showing that one will not do anything worse than that
* I’ll drive less, eat at home, and stop buying clothes to save money, but I draw the line at looking for things I need in other people’s garbage!
to snoop – to spy; to secretly look for information that other people might want to hide, without letting them know that one is looking
* Were you snooping in your sister’s room, reading her private journal?
to have (one’s) back against the wall – to not have any other options; to be left with only one thing that one can do; to be desperate
* She didn’t want to steal the money, but she had her back against the wall and didn’t know how else to get enough money to buy food for her family.
leak – a person or thing that allows secret information to be shared with people who shouldn’t know it
* There’s a leak in the government who is giving information to journalists.
trade secret – secret information about how a business does or makes something, which competitors would like to know
* The company’s recipe for tomato sauce is a trade secret.
deceptive – deceitful; lying; not telling the whole truth; misleading
* That’s an example of deceptive advertising. The business is telling people they’re getting something for free, but they really have to pay for it.
wiretap – the practice of listening to conversations secretly by using a small, hidden machine that records what is said in a room or on the phone
* The embassy is worried that there might be wiretaps in the building.
invasion of privacy – a violation of one’s right to keep personal information secret; something that does not respect one’s privacy
* Rufat thought it was an invasion of privacy when his mother went into his room when he wasn’t there.
priority – a level of importance; the order in which something should be done or addressed
* Sam’s uncle said to him, “As a student, your top priority should be studying. Going to parties should be your lowest priority.”
damage control – the practice of minimizing damages or losses, making a bad situation as good as it can be
* They lost more than 60% of their money in bad investments before they decided to sell the rest for damage control.
rival – competitor; a person or company whom one is fighting or competing against
* Adidas, Reebok, and Nike are rivals in the shoe industry.
to schmooze – to network; to have casual conversations, usually to make a good social contact or to get connected with important people
* The party was so boring! There were just a lot of lawyers schmoozing and trying to get new clients.
to scour – to look through many things, trying to find a specific one or a certain detail or piece of information
* The police scoured the room, looking for information that would help them learn who had stolen the television.
Comprehension Questions
1. Which of these things would be ethically questionable?
a) Having second thoughts.
b) Drawing the line.
c) Leaking trade secrets.
2. Which of these verbs has a similar meaning as “to spy”?
a) To snoop.
b) To leak.
c) To scour.
Answers at bottom.
What Else Does It Mean?
leak
The word “leak,” in this podcast, means a person or thing that allows secret information to be shared with people who shouldn’t know it: “The university had an information leak and all of its students’ contact information was shared with the public.” The word “leak” also means a crack or small hole in a wall, ceiling, or something else that lets air or water through it: “When it started raining, we discovered that there was a leak in the ceiling.” The word can also be used as a verb, “to leak”: “The car is leaking oil.” Finally, the phrase “to take a leak” is an informal, rude (unpleasant and not polite) expression meaning that one needs to go to the bathroom to urinate: “I drank too much water and now I have to take a leak.”
to scour
In this podcast, the verb “to scour” means to look through many things, trying to find a specific one, or a certain detail or piece of information: “She scoured her phone bill, trying to understand why she had been charged so much money that month.” Or, “He scoured the book, looking for the paragraph he had remembered reading earlier.” The verb “to scour” also means to scrub, or to rub something very hard to clean it: “He spent almost an hour scouring the dirty pot.” Or, “What cleaner should I use to scour the bathtub?” “Scouring powder” is a white powder that is sold as a cleaner for washing very dirty dishes or ovens: “How much scouring powder should I use to clean the oven?”
Culture Note
Corporate spying, which is sometimes called “industrial espionage,” happens when companies spy on each other to get information that can help their business make more money and/or make their competitors “go out of business” (have to close a business because it isn’t making enough money). Some “basic” (very simple) corporate spying is “common” (not unusual). But there are some dishonest uses of corporate spying, too, that hopefully don’t happen very often.
“Blackmail” is an example of a dishonest use of corporate spying. Blackmail happens when Company A learns something bad about Company B. Then Company A “threatens” (says that it will do something bad) Company B, saying that it will share that information with the government or customers unless Company B agrees to do something that will “benefit” (do something good for) Company A. For example, if Company A finds out that Company B is “damaging” (hurting) the environment, it might threaten to tell Company B’s customers about it unless Company B agrees to pay Company A one million dollars.
Another dishonest use of corporate spying is “sabotage,” where someone “purposefully” (intentionally, or meaning to do something) destroys something that belongs to another company. Sabotage could happen if a person destroys a company’s “equipment” (the machines and tools used to make things) or products. Sabotage could be as simple as cutting electrical “wires” (long, thin pieces of cable covered with plastic that carry energy and information between machines) in a factory.
“Spyware” is a newer type of corporate spying. Spyware is “software” (a computer program) that “runs” (operates) secretly on a person’s computer without that person knowing it. The spyware might find secret information and copy it, sending it back to the person or company that created the spyware.
Comprehension Answers
1 - c
2 - a