= 0415
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 415: Being Clean and Dirty.
This is English as a Second Language Podcast episode 415. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
You can visit our website at eslpod.com. There, you can find our Learning Guide, an 8 to 10 page guide to this episode to help you improve your English even faster.
This episode is called “Being Clean and Dirty.” It’s a dialogue between Ray and Debra where they’re talking about how each one of them is either clean or dirty, using a lot of vocabulary we would use to describe someone who is either clean or not so clean – dirty. Let’s get started.
[start of dialogue]
Ray: My mother is coming for a visit, which means we need to do some spring cleaning this weekend.
Debra: I’ll get the duster, if you’ll get the broom.
Ray: I’m serious. You know how nit-picky my mother is and I want our house to be neat and tidy.
Debra: Fine, fine, I understand. You don’t want her to know we live in a pigsty.
Ray: I’m not saying we live in a pigsty, but the house is a little messy and dusty. It wouldn’t hurt to straighten up a little bit, that’s all.
Debra: I’m willing to pitch in, but I’m not going to spend the entire weekend slaving away to get this house spotless. Your mother won’t love you any less if you’re not a neat freak.
Ray: You don’t know my mother very well.
Debra: I know her well enough. I don’t want to spoil her fun. If she can’t complain about our dirty house, what will she complain about?
[end of dialogue]
Ray and Debra are having a conversation about cleaning the house because Ray’s mother is coming to visit. Ray says, “My mother is coming for a visit, which means we need to do some spring cleaning this weekend.” The expression “spring cleaning” is used to describe a period of time where you clean your house very well. Usually it happens about once a year, often in the spring, in the early part of the year. “Spring cleaning,” however, is a general term that means that you’re going to clean everything in your house; you’re going to “throw out” or get rid of things you don’t need anymore. That’s another meaning of the expression.
Debra says, “I’ll get the duster, if you get the broom.” A “duster” (duster) is a small tool; it’s a piece of wood or plastic that you hold on to and it has, usually, either a lot of feathers, like from a bird, or a very light cloth – material – at one end. It’s used to clean tables and shelves and other things in your house that may have a lot of dirt on them – a lot of dust. A “broom” is typically a long pole that has at one end either straw or plastic, and it’s used to clean a floor – to sweep a floor. The verb “to sweep” means to take, in this case, a broom and move it across the floor in order to clean it. Sweeping with a broom does not involve water or soap; it’s simply removing the things that are on the floor.
Ray says, “I’m serious,” meaning he thinks Debra is joking. “You know how nit-picky my mother is and I want our house to be neat and tidy,” he says. “Nit-picky” comes from the verb to “nit pick” (nit pick). To “nit pick” means to pay a lot of attention to small things and not be happy – not be satisfied – until everything is perfect. It’s generally considered a negative description of someone who tries to be too perfect and tries to criticize someone else for every small problem. Ray says he wants the house to be “neat and tidy.” To be “neat and tidy” means to be well organized and clean. The word “neat” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Debra says, “Fine, fine, I understand (she’s saying “okay, okay”). You don’t want her to know we live in a pigsty.” A “pigsty” (pigsty – one word) is, literally, a place where pigs live. But people consider pigs to be very dirty, so when they talk about a pigsty they’re talking about a very dirty and unorganized place. Ray says, “I’m not saying we live in a pigsty, but the house is a little messy and dusty.” To be “messy” (messy) means to be unorganized, where things are not where they should be. “Dusty” means that there are small pieces of dirt on top of the furniture or other parts of the house.
He then says, “It wouldn’t hurt to straighten up a little bit, that’s all.” When someone says “it wouldn’t hurt to...” do something, such as “it wouldn’t hurt to go home a little early so we can get more sleep tonight,” they mean that it would be a good idea, that it would be a helpful thing. Ray says, “It wouldn’t hurt to straighten up a little bit.” To “straighten up” is a two-word phrasal verb meaning to organize things while you are cleaning them, to put things away where they belong.
Debra says, “I’m willing to pitch in.” To “pitch in” is, again, a two-word verb meaning to help with a project, to give some assistance to complete something. Someone who is going to “pitch in” is going to help. They’re not going to do the whole thing themselves, but they will assist or help someone else with it. The word “pitch” has a couple of different – very different meanings in English; take a look at our Learning Guide for some additional explanations.
Debra says, “I’m not going to spend the entire weekend slaving away to get this house spotless.” The expression – the verb to “slave away” is a two-word phrasal verb meaning to work very hard, to do something difficult for a long time. “Spotless” is perfectly clean. If something is dirty, we may say it has a “spot” on it. For example, if you are at a baseball game and you’re eating a hot dog and you have some mustard on your hot dog, and some of the mustard falls onto your shirt, that would create a spot – a spot of dirt – a small place where it is dirty. “Spotless” is the opposite of that; it’s perfectly clean, something with no spots.
Debra says, “Your mother won’t love you any less if you’re not a neat freak.” The expression “your mother won’t love you any less” means she won’t care that much, she’ll still love you even though you are not something. In this case, you are not a neat freak. “Neat,” we already know, means clean and organized. The word “freak” (freak) describe someone who does things in the extreme or someone who does things very strangely, someone who is very weird. Again, it’s not usually considered a positive quality in someone. A “neat freak” would be someone who wants everything to be clean all the time everywhere, particularly in their own house or home.
Ray says, “You don’t know my mother very well,” meaning maybe my mother won’t love me if I’m not a neat freak. Poor Ray! Debra says, “I know her well enough.” Of course, Debra is Ray’s mother’s daughter-in-law; she is her mother-in-law, and traditionally there’s always a little friction – some difficulties often between the son-in-law and the mother-in-law, or the daughter-in-law and the mother-in-law, and so forth.
Well, Debra says, “I know her well enough,” meaning I know her sufficiently to be able to say something. You don’t know them perfectly, but you know them enough – you know them sufficiently. Debra says, “I don’t want to spoil her fun.” To “spoil (spoil) someone’s fun” means to make something less fun for somebody, to make something less enjoyable. A parent may say to their child, “I don’t mean to spoil your fun, but now you must go to bed, it is late. No more television for you!”
Debra says, “I don’t want to spoil (Ray’s mother’s) fun.” She says, “If she can’t complain about our dirty house, what will she complain about?” To “complain” means to say that you are unhappy about something, to say that you don’t like something. If you check into a hotel and your room is dirty, you may call down and complain to the front desk, the people who are responsible for the hotel. Debra is saying that Ray’s mother likes to have fun by complaining about things. There are, of course, people like this in the world – not my mother-in-law! Debra says, “If she can’t complain about our dirty house, what will she complain about?” meaning if we clean up the house she won’t have any fun because she can’t complain. She, of course, is making a joke here – Debra is.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ray: My mother is coming for a visit, which means we need to do some spring cleaning this weekend.
Debra: I’ll get the duster, if you’ll get the broom.
Ray: I’m serious. You know how nit-picky my mother is and I want our house to be neat and tidy.
Debra: Fine, fine, I understand. You don’t want her to know we live in a pigsty.
Ray: I’m not saying we live in a pigsty, but the house is a little messy and dusty. It wouldn’t hurt to straighten up a little bit, that’s all.
Debra: I’m willing to pitch in, but I’m not going to spend the entire weekend slaving away to get this house spotless. Your mother won’t love you any less if you’re not a neat freak.
Ray: You don’t know my mother very well.
Debra: I know her well enough. I don’t want to spoil her fun. If she can’t complain about our dirty house, what will she complain about?
[end of dialogue]
The script for this episode was written by someone who is never messy, but always neat and tidy, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
spring cleaning – a period of time spent cleaning a home very well, usually once a year, getting rid of the things that one no longer wants or needs and cleaning the things that one wants to keep
* The whole family got involved in spring cleaning: Mom cleaned the kitchen, Dad worked floors and windows, and the kids cleaned out the closets.
duster – a small tool with a piece of wood or plastic to hold onto and many feathers or a light cloth at one end, used on tables, shelves, and other surfaces to move small pieces of dirt off of them
* He used a duster to get rid of the small dead bugs that were lying at the bottom of the window.
broom – a long tool with a long piece of wood or plastic to hold onto and many small pieces of straw or plastic at one end, used to move small pieces of dirt on a floor into one place so that they can be picked up and thrown away
* Arka spilled flour on the kitchen floor and used a broom to clean it up.
nit-picky – one who pays a lot of attention to detail and is happy only if things are a certain way; demanding
* Our teacher is so nit-picky that if we spell even one word wrong she makes us do the whole assignment all over again.
neat and tidy – very organized and clean, with everything where it should be
* Rose’s house is never neat and tidy because her children leave their toys everywhere.
pigsty – a place where pigs live, also used to talk about a very dirty and unorganized place
* Their whole house is very clean, except for their son’s room, which is a pigsty with dirty clothes and pizza boxes all over the floor.
messy – unorganized; with many things where they should not be
* The garage is so messy! We have to get some boxes and start to put everything away.
dusty – covered with very small pieces of dirt
* The library has many old books that are dusty because they haven’t been opened in years.
to straighten up – to organize objects while cleaning; to put things away
* Miranda quickly straightened up the bathroom, hanging towels and putting away her toothbrush.
to pitch in – to help with a project; to give assistance to help complete something
* Sheila said, “I wish you would pitch in around the house more, helping me cook and clean.”
to slave away – to work very hard; to do difficult work for a long period of time
* After slaving away at work all day, Rolf wanted to come home, eat dinner, and sleep.
spotless – perfectly clean, without any dirt or other problems
* Their home is so spotless that you could eat off the floor and not get sick!
neat freak – a person who always wants everything to be extremely clean and organized
* Genevieve is such a neat freak that all her books and CDs are in alphabetical order.
well enough – a phrase used to show that one can do something or knows something sufficiently, even if he or she doesn’t know it perfectly
* I might not be great at algebra, but I can do math well enough to figure out how much to pay at the store.
to spoil (one’s) fun – to make something less fun for someone; to make something less enjoyable
* Wendy wanted to spend her birthday on the beach, but cold weather spoiled her fun.
to complain – to say that one is unhappy about something; to say that one does not like something
* Vana always complains about how salty the food is here.
Comprehension Questions
1. Which of these words could be used to describe a neat freak’s home?
a) Pigsty.
b) Messy.
c) Spotless.
2. What does the phrase “to straighten up a bit” mean?
a) To do some cleaning.
b) To improve one’s posture.
c) To make a mess.
Answers at bottom.
What Else Does It Mean?
neat
The phrase “neat and tidy,” in this podcast, means very organized and clean, with everything where it should be: “At the end of the day, do you leave your desk neat and tidy, or do you leave papers all over it?” The word “neat” also means good and/or interesting: “Google has a neat program for translating text from one language to another.” The word “neat” can be used with the same meaning as an adverb: “I need to learn to write more neatly or else nobody will be able to read my handwriting.” When talking about drinks with alcohol in them, “neat” means a drink that is just alcohol, with no ice or other liquid: “Do you want a vodka neat or with orange juice?”
to pitch in
In this podcast, the phrase “to pitch in” means to help with a project: “Thanks for pitching in and helping us clean up after the party yesterday.” The phrase “to pitch in” can also mean to pay for part of something when many people contribute a little bit of money: “Are you going to pitch in with your co-workers to buy a going-away present for Bryce?” The phrase “to pitch (something)” can mean to suggest an idea or make a suggestion: “The magazine editors meet every Tuesday to pitch ideas for stories for the next week.” Finally, the phrase “to pitch camp” means to get everything ready very quickly for sleeping outside: “The boys pitched camp in about 20 minutes and then went to explore the forest.”
Culture Note
Most Americans “accumulate” (get a lot of something over time) many things in their home. Spring cleaning once a year is a good way for them to “sort through” (order and organize) their “belongings” (the things that a person owns), “getting rid of” (throwing away or giving away) things they don’t want and organizing the things that they want to keep.
Many people begin their spring cleaning in the closets, sorting through their clothing. They might decide to get rid of clothes that are old, ugly, or too big or small. Some children’s clothes are given to younger children as “hand-me-downs,” or clothes that one person has “outgrown” (gotten too big for) but can still be worn by a smaller person. Other clothes are “donated” (given to a person or organization for free) to organizations and people who need them.
Spring cleaning also means cleaning out the “garage” (the room next to a house where one parks a car), getting rid of things that are too big or unwanted and “packing up” (putting in boxes) things that people don’t use every day.
Often people want to get rid of so many things that they have a “garage sale” or a “yard sale” where they put the things in front of their home with prices written on them. Other people come to their home on the day of the sale to buy those things and take them to their own homes.
Finally, once all the unwanted things have been donated, sold, or thrown away, people “thoroughly” (completely or very well) clean everything that’s left. This means “sweeping” (using a broom) and “vacuuming” (pushing an electronic machine to clean the carpets) the floors, washing windows, dusting furniture, and “scrubbing” (cleaning very thoroughly) the kitchen and bathrooms.
Comprehension Answers
1 - c
2 - a