= 0419
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 419: Planting a Garden.
This is English as a Second Language Podcast number 419. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there and download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Planting a Garden.” It’s going to be conversation between Joni and Giuseppe talking about planting things in your back yard in back of your house in the ground so that they will grow. Let’s get started.
[start of dialogue]
Joni: Smell that!
Giuseppe: Smell what?
Joni: Smell that fresh air. Aren’t you glad I got you to help me plant this garden? We’re going to have so much fun today.
Giuseppe: Uh huh. I’m glad to help, but I don’t exactly have a green thumb.
Joni: That’s okay. As long as you can tell a shovel from a lawn mower, you’ll be fine. Let’s start by moving these pots next to the bushes.
Giuseppe: Okay, your wish is my command.
Joni: Oh, this bag of fertilizer is so heavy.
Giuseppe: Let me get that.
Joni: Thanks. I didn’t know we had so many large bags of seeds, too.
Giuseppe: Do you want me to help you with those?
Joni: Thanks a lot. I’ll also need someone to help me hoe this soil.
Giuseppe: I guess I could do that.
Joni: And how am I going to pull all of these weeds?
Giuseppe: Honestly, I think we need reinforcements.
Joni: Good idea. You start working and I’ll go see if I can round up more help. [She leaves.]
Giuseppe: I start working while she leaves? Hmm…I think she just pulled a fast one on me.
[end of dialogue]
Our dialogue begins with Joni saying to Giuseppe, “Smell that!” “Smell” meaning take your nose and try to smell it. Giuseppe says, “Smell what?” Joni says, “Smell that fresh air.” The “fresh air” is air outside that smells good; it smells clean. Joni says, “Aren’t you glad I got you to help me plant this garden? We’re going to have so much fun today.” To “plant,” here, means to put seeds in the ground so that the plants will grow. A “garden” is usually a small piece of land that is used to grow plants, usually flowers or vegetables, perhaps fruit.
Joni says that she thinks they’re going to have so much (or a lot of) fun today. Giuseppe says, “Uh huh.” That expression, “uh huh,” means you don’t really agree with the person; you’re saying yes but you don’t mean yes, or you mean yes but you aren’t very enthusiastic about it. Giuseppe says, “I’m glad to help, but I don’t exactly have a green thumb.” The expression “to have a green thumb” means that you can make things grow well, you can make plants and flowers – things in the ground – you can make them grow; you are good at that sort of thing.
Joni says, “That’s okay. As long as you can tell a shovel from a lawn mower, you’ll be fine.” To “tell something from something else” means to distinguish or to differentiate something from something else. It means to see or understand the difference between two things. If you’re looking at a bird you may say, “I can’t tell a male bird from a female bird.” Hopefully you won’t have that problem with humans! “I can’t distinguish one from the other.”
So Joni says, “As long as you can tell a shovel from a lawn mower, you’ll be fine.” A “shovel” (shovel) is a tool for working in a garden, for example. You have one long wooden piece that you hold onto, and then usually a flat piece of metal that you push into the ground in order, for example, to make a hole. A “lawn mower” is a machine, usually that has an engine powered by gasoline, that’s used to cut the lawn (to cut the grass). So, Joni is saying as long as you know the difference between a shovel and a lawn mower, you’ll be fine.
She says, “Let’s start by moving these pots next to the bushes.” A “pot” is a round container that holds dirt and usually has one or more plants that are planted in this dirt. So it’s a container for growing plants. “Pot” has a couple of different meanings that are not explained in our Learning Guide – so don’t look there for any further explanations!
Joni wants to put the pots next to the bushes. These are not the people who may have lived in the White House! The “bushes” are large, short plants that have many branches and leaves. Giuseppe says, “Okay, your wish is my command.” This is an old expression: “your wish (what you want) is my command.” I will do whatever you want me to do, that’s the meaning of this expression: “Your wish is my command.” It might be something a servant would say to a king or a queen, so there’s a little bit of comedy – a little bit of a joke when someone says this.
Joni then says, “Oh, this bag of fertilizer is so heavy.” “Fertilizer” is something that you put on the ground to make the dirt (the soil) better so that you can grow your plants better and more quickly. Usually fertilizer is made from either chemicals or animal waste; that’s why fertilizer often has a very bad smell to it.
Giuseppe says, “Let me get that” – let me lift that up. Joni says, “Thanks. I didn’t know we had so many large bags of seeds, too.” A “seed” is a small, hard piece of the plant that you put into the ground to make a new plant grow. Giuseppe says, “Do you want me to help you with those?” Joni says, “Thanks a lot,” meaning yes, thank you. She says, “I also need someone to help me hoe this soil.” To “hoe” (hoe) means to use a special tool that has a long wooden piece that you hold onto and a piece of metal that is used to scrape. So it’s kind of like a shovel but smaller. Joni wants Giuseppe to help her hoe the soil. The “soil” is the dirt, the earth where you plant these seeds.
Giuseppe says, “I guess I could do that.” Joni says, “And how am I going to pull all of those weeds?” To “pull,” here, means to remove. “Weeds” are plants that you don’t want. They’re things that you don’t want to grow but are growing next to the plants that you do want. So these are called “weeds.” “Weed,” like the word “pot,” can also refer to marijuana, which is another kind of plant that you smoke – or at least that’s what I have been told!
Giuseppe says, “Honestly, I think we need reinforcements.” “Reinforcements” is something or someone that helps with a project and makes it stronger or makes something stronger. In this case, it means more people: “I think we need more people to help us.”
Joni says, “Good idea. You start working and I’ll go see if I can round up more help.” To “round up” something, in this sentence, means to find or bring something or someone. “I’m going to go round up some of my friends” – I’m going to go out and find them and bring them back. To “round up” is a phrasal verb that has a couple of different meanings in English. This time you can go to the Learning Guide to find some additional explanations!
Well, Joni then leaves and Giuseppe says, “I start working while she leaves? Hmm…I think she just pulled a fast one on me.” To “pull a fast one on someone” means to trick someone, to make someone do something that he normally wouldn’t want to do, or to make someone believe something that isn’t true. That’s to “pull a fast one.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Joni: Smell that!
Giuseppe: Smell what?
Joni: Smell that fresh air. Aren’t you glad I got you to help me plant this garden? We’re going to have so much fun today.
Giuseppe: Uh huh. I’m glad to help, but I don’t exactly have a green thumb.
Joni: That’s okay. As long as you can tell a shovel from a lawn mower, you’ll be fine. Let’s start by moving these pots next to the bushes.
Giuseppe: Okay, your wish is my command.
Joni: Oh, this bag of fertilizer is so heavy.
Giuseppe: Let me get that.
Joni: Thanks. I didn’t know we had so many large bags of seeds, too.
Giuseppe: Do you want me to help you with those?
Joni: Thanks a lot. I’ll also need someone to help me hoe this soil.
Giuseppe: I guess I could do that.
Joni: And how am I going to pull all of these weeds?
Giuseppe: Honestly, I think we need reinforcements.
Joni: Good idea. You start working and I’ll go see if I can round up more help. [She leaves.]
Giuseppe: I start working while she leaves? Hmm…I think she just pulled a fast one on me.
[end of dialogue]
The script was written by someone who would never pull a fast one on you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
fresh air – air outside that smells clean and good
* I love the smell of fresh air after it has rained.
to plant – to put seeds in the ground so that plants will grow
* Where did you plant the carrots?
garden – a small piece of land that is used to grow plants, usually either flowers, fruits, or vegetables
* This year, our garden has lots of strawberries and corn.
green thumb – the ability to make things grow well; the ability to work well with plants
* Randy has a green thumb, so his garden always looks fantastic.
to tell (something) from (something) – to distinguish or differentiate something from something else; to see or understand the differences between two things; to know that two things are not the same
* How can you tell a boy bird from a girl bird?
shovel – a tool for working the garden that has a long, wooden piece to hold onto and a large, mostly flat piece of metal at one end that is used to make holes, picking up dirt and moving it somewhere else
* I need to use a shovel to dig a hole where I can plant this tree.
lawn mower – a large machine, usually powered by gasoline, that is used to cut grass, making it short and neat looking
* Our neighbors like to cut their grass early in the morning, but their lawn mower is noisy and it wakes us up.
pot – a round container that holds dirt and one or more plants; a container that is used for growing plants
* Meghan has several pots with pretty flowers by her front door.
bush – a large, short plant that has many branches and leaves
* Are there a lot of rose bushes at the park?
your wish is my command – an expression used to show that one will do whatever another person wants one to do
* Isabelle’s husband always does whatever she asks him to, simply saying, “Your wish is my command.”
fertilizer – something that is put on the ground to make the soil (dirt) better and help plants grow better and more quickly, usually made from chemicals or animal waste
* If your plants don’t grow very quickly, try adding some fertilizer and see if that helps.
seed – a very small, hard piece of a plant that, when put in the dirt, makes a new plant grow
* Do you eat the seeds in grapes, or do you spit them out?
to hoe – to use a tool for working the garden that has a long, wooden piece to hold onto and a large, flat piece of metal at one end that is used to scrape
* Yevi hoed his garden to make it ready for planting.
soil – dirt; the earth that is found on the ground and used to grow plants
* Is the soil behind your house good for growing vegetables?
weed – an unwanted plant; a plant that one does not want to have growing in a particular place
* Is this a lettuce plant or is it a weed?
reinforcement – something or someone that helps with a project and makes something stronger and better
* When the firefighters saw how big the fire was, they called to ask for reinforcements.
to round up (something or someone) – to find, gather, and bring something or someone
* We need to round up volunteers to pick up garbage on the beach this weekend.
to pull a fast one – to trick someone; to make someone do something that he or she normally wouldn’t want to do; to make someone believe something that isn’t true
* I went to the outdoor market to buy a new watch, but the seller pulled a fast one and gave me an empty box instead.
Comprehension Questions
1. Which of these would you not want to have in your garden?
a) Bushes.
b) Seeds.
c) Weeds.
2. What does Giuseppe mean when he says, “she just pulled a fast one on me”?
a) She planted her garden very quickly.
b) She left the garden very quickly to go get help.
c) She tricked him into doing the work.
Answers at bottom.
What Else Does It Mean?
to plant
The verb “to plant,” in this podcast, means to put seeds in the ground so that plants will grow: “In which month should we begin planting cucumbers?” The phrase “to plant an idea” means to give someone an idea that develops over time: “The first time I tasted crepes, it planted the idea of opening my own crepe restaurant.” The phrase “to plant (something) on (someone or something)” means to put something somewhere: “He planted a kiss on his girlfriend’s cheek.” Or, “She planted her books on the desk.” Finally, the phrase “to plant (something) on (someone or something)” means to hide something that is illegal: “Becca said that she didn’t know the drugs were in her suitcase, so someone must have planted them on her.”
to round up
In this podcast, the phrase “to round up” means to find, gather, and bring something or someone: “We want to buy a new car, but we don’t know whether we’ll be able to round up enough money.” The phrase “to round up/down to the nearest 5/10” means to take a number and change it so that it goes up or down to the nearest number that ends in a 5 or 0: “If you’re asked to round up 743 to the nearest 5, the correct answer is 745. If you’re asked to round it up to the nearest 10, the correct answer is 750.” The phrase “to round (something) out” means to make something more complete: “Although he was studying physics, he rounded out his education by studying philosophy and Portuguese, too.”
Culture Note
Many Americans enjoy having gardens in their “yards” (the outdoor areas behind and around a home), but people who live in apartments or homes without big yards often don’t have “room” (space or area) for a garden. These people often participate in a “community garden.”
A community garden is an area that is shared by many people for growing flowers, vegetables, and fruits. In some community gardens, the area is “split” (or divided into smaller parts) into “plots” (an area of land for one person or family to use) and each person who owns a plot gets the “produce” (things that are taken from a garden to eat) that is grown in that plot. In other community gardens, everyone works together to plant and “harvest” (take the parts of a plant that can be eaten when they are ready) the plots and then they share the produce.
Often schools have gardens, too. These are similar to community gardens, except that students are “working the plots” (gardening). They learn about gardens and “agriculture” (the business of growing plants for food and material) and then they get to enjoy the produce when it is ready.
Gardens make “communities” (areas where groups of people live together) more beautiful. In poor “inner-city neighborhoods” (areas where people live in the center of the city, usually without very much money), organizations sometimes have “community beautification programs” that create gardens in “vacant lots” (areas of land that are not being used and do not have buildings). The gardens are beautiful and many people think that they make the neighborhoods safer and friendlier.
Comprehension Answers
1 - c
2 - c