= 0435
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 435: Describing Aches and Pains.
This is English as a Second Language Podcast episode 435. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
Visit our website at eslpod.com. You can download a Learning Guide for this episode that will help you improve your English even faster.
This episode is called “Describing Aches and Pains.” It’s a dialogue between Nivia and Michael that uses a lot of vocabulary we use when talking about the body and when we have pain in our body. Sounds like fun! Let’s get started.
[start of dialogue]
Nivia: Why are you walking funny?
Michael: Oh, I pulled a muscle in my right leg while playing with my kids last weekend. It’s hard to walk without feeling a twinge of pain.
Nivia: I’m sorry to hear that. Why are you sitting in that awkward position?
Michael: I strained my back while exercising. Initially, I felt a sharp pain and I thought it was something serious, but it doesn’t hurt much now. There’s just a dull pain when I sit up straight. That’s why I’m sitting like this, leaning to the side.
Nivia: That’s too bad. Why are you holding your arms that way?
Michael: I got up in the middle of the night last night to go to the bathroom and bumped into the door. I got a huge bruise on my arm. It feels better if I hold it over my head.
Nivia: Why are you shaking your fingers that way?
Michael: I helped my daughter finish her science project for school. I – I mean we – glued over 100 wooden sticks together. My fingers are really sore and stiff, and they won’t stop throbbing.
Nivia: I’m afraid to ask you any more questions. I don’t think any man could survive any more injuries than what you already have!
[end of dialogue]
Our dialogue begins with Nivia saying to Michael, “Why are you walking funny?” Here, “funny” just means unusual, oddly, we might even say “weirdly.” “Why are you walking funny?” – why are you not walking normally? Michael said, “Oh, I pulled a muscle in my right leg while playing with my kids last weekend.” To “pull a muscle” means to hurt a part of your body – in your arms, in your legs, in your back, in your neck, wherever you have a muscle. The “muscle” is what connects bones together, and allows you to move your bones. So, “pulling a muscle” means injuring or harming your muscle. Michael says, “It’s hard to walk without feeling a twinge of pain.” Well, “pain,” you probably know, is when something feels uncomfortable; it hurts. A “twinge” is a sudden feeling, but it doesn’t last very long. So, Michael is saying he feels twinges of pain when he walks; it’s not constant, it’s not all the time but it happens quickly and then it goes away.
Nivia says, “I’m sorry to hear that. Why are you sitting in that awkward position?” “Awkward” means not relaxed, uncomfortable. Michael says, “I strained my back while exercising.” To “strain” (strain) means to hurt part of your body because you were working too hard, or because you tried to do something that was too difficult. I never strain my back because I never work too hard! But Michael strained his back while exercising. “Initially,” he says, “I felt a sharp pain.” “Sharp,” here, means very strong; it may not last for a long time, but it’s a very strong pain. We might say it’s a very “acute” (acute) pain. He says he “felt a sharp pain, and thought it was something serious, but it doesn’t hurt much now.” Now, he says, “There’s just a dull (dull) pain” when he tries to sit up straight – when he tries to sit normally. “Dull” is the opposite of sharp; it describes a pain that is not strong, but it lasts a long time. “Dull” has a couple of different meanings in English; take a look at the wonderful Learning Guide that Dr. Lucy Tse prepares for some additional explanations.
Michael says that’s the reason, or “That’s why I’m sitting like this, leaning to the side.” To “lean” (lean) means to put your body in one direction, not straight. You’re usually resting against another object, such as the wall. So, if you lean against the wall, you’re standing up but your shoulders are touching the wall; the wall is supporting you. In English, people refer to the famous tower in the City of Pisa, in Italy, as the Leaning Tower of Pisa, because the building is not vertical completely. It goes off to one side; it leans to one side.
Nivia says, “That’s too bad (that’s unfortunate). Why are you holding your arms that way?” Michael says, “I got up in the middle of the night last night to go to the bathroom and bumped into the door.” To “bump into” something means to accidentally hit something with your body. Normally, you don’t bump into a thing on purpose; you’re not trying to do it. The expression “to bump into” can also means something very different if you are talking about a person. You may say, “I bumped into an old friend of mine at the coffee shop yesterday.” There, it means I met or saw someone that I wasn’t expecting to see; I wasn’t planning on it, it just was a coincidence.
Well, poor Michael bumped into the door and he got a huge bruise on his arm. A “bruise” (bruise) is an often painful spot on your skin. Usually it has a different color; it’s either dark purple, or brown, maybe even a little green. It’s caused by bleeding underneath your skin – there’s blood underneath the skin. It often happens when you are hit very hard by someone or by something. If you are in a fight – a physical fight with someone and that person hits you, for example, with their fist – with their hands, you may have a bruise the next day, you may have this spot on your skin.
So, Michael has a bruise on his arm. Nivia says, “Why are you shaking your fingers that way?” Michael says, “I helped my daughter finish her science project for school.” Young children are often given “homework,” things to do at home for their school. A “science project” is usually something that you make at home that shows some sort of scientific principle or applies some sort of scientific principle (idea). Parents often help their children with their schoolwork, including their science projects. Michael says, “I – I mean we...” – of course, the child should be doing the project but parents sometimes do more than the child does. He says, “I – I mean we – glued over 100 wooden sticks together.” To “glue” something means to connect two things or to make two things stick together using a white liquid (or a clear liquid) that will dry between the two pieces and keep them together. You often use glue, for example, in school. Children will use glue to put pieces of paper together, or other things. This is a science project where they had to glue some small wooden sticks. For some reason, these are popular in schools. They’re sometimes called “popsicle sticks” because it’s the same small wooden stick that you get with a certain kind of frozen desert called a “Popsicle.”
Well, Michael was gluing together all these sticks, and his fingers got very sore and stiff. “Sore” (sore) means in pain, usually because you’ve worked your part of the body too hard – the part that is sore. It’s what may happen, for example, after you strain – after you work your arms or your legs too hard. Let’s say you’re running and you’re not used to running, the next day your muscles may be sore – they may hurt. “Sore” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations. “Stiff” means unable to move easily, inflexible – not flexible. So, your arm may be stiff, that means it’s hard to move it up and down or left and right because you injured it – because you hurt it. He says his fingers “won’t stop throbbing.” To “throb” means to have pain that starts and stops repeatedly, almost like in a rhythm. So if you hit your thumb, for example, it may hurt – it may throb. It may have this strange sort of pulse, sort of rhythm that causes you pain.
Nivia says, “I’m afraid to ask you any more questions. I don’t think any man could survive any more injuries than what you already have!” To “survive” means to continue to exist even though it’s a difficult situation. An “injury” is a problem with some part of your body, usually caused by an accident, or, perhaps, someone was fighting you. If you run too fast and you hurt your legs, that would be an injury. Or, in the case of Michael, if he was straining his fingers and now they’re sore, that could be called an injury.
One more thing before we conclude. The name of this episode was “Describing Aches and Pains.” An “ache” is a kind of pain; usually it’s a dull pain. It’s not necessarily serious, however.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Nivia: Why are you walking funny?
Michael: Oh, I pulled a muscle in my right leg while playing with my kids last weekend. It’s hard to walk without feeling a twinge of pain.
Nivia: I’m sorry to hear that. Why are you sitting in that awkward position?
Michael: I strained my back while exercising. Initially, I felt a sharp pain and I thought it was something serious, but it doesn’t hurt much now. There’s just a dull pain when I sit up straight. That’s why I’m sitting like this, leaning to the side.
Nivia: That’s too bad. Why are you holding your arms that way?
Michael: I got up in the middle of the night last night to go to the bathroom and bumped into the door. I got a huge bruise on my arm. It feels better if I hold it over my head.
Nivia: Why are you shaking your fingers that way?
Michael: I helped my daughter finish her science project for school. I – I mean we – glued over 100 wooden sticks together. My fingers are really sore and stiff, and they won’t stop throbbing.
Nivia: I’m afraid to ask you any more questions. I don’t think any man could survive any more injuries than what you already have!
[end of dialogue]
We hope the script for this episode did not cause you any pain. It was written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
funny – oddly; in an unusual way; weirdly
* She talked funny after her appointment at the dentist’s office.
to pull a muscle – to hurt the part of one’s body that connects bones together and allows one’s body to move
* He pulled a muscle in his back when carried very heavy boxes.
twinge – a sudden feeling or sensation that doesn’t last for very long
* Bertha feels a twinge of guilt every time she says “no” to a homeless person who asks her for money.
pain – physical discomfort, usually due to an injury; the feeling of one’s body hurting
* Were you in a lot of pain when you broke your arm?
awkward – uncomfortable; not relaxed
* I feel awkward whenever I go to a party where I don’t know anyone.
to strain – to hurt part of one’s body because one made it work too hard, or because one tried to do something that was too difficult
* Vreneli strained her eyes by looking at the computer screen all day.
sharp – acute; very strong, but lasting for only a short time
* A sharp pain runs up his leg every time he puts weight on his right foot.
dull – a pain that is not very strong, but lasts for a long time
* She’s had dull pain from a bad headache all week.
to lean – to be inclined; to rest one’s body toward one direction, often resting against a wall or something else
* The cashier started to lean against the wall because she was tired of standing but not allowed to sit down while working.
to bump into (something) – to accidentally hit something with one’s body
* While walking through the dark house at night, he accidentally bumped into the table and an expensive vase fell down and broke.
bruise – a painful dark purple, brown, or greenish spot on the skin, caused by bleeding underneath the skin, usually because one was hit very hard by something or someone
* Kelly fell off of her bicycle last week that caused a big bruise on her knee.
to glue – to connect two things or to make two things stick together by using a clear or white liquid that dries between the two pieces
* Do you think we can glue together the broken pieces of the plate?
sore – in pain, usually because part of one’s body has worked too hard
* We were really sore after our 13-mile hike.
stiff – unable to move easily; inflexible
* His legs were so stiff after his long bike ride that he almost couldn’t walk.
to throb – to have a pain that starts and stops repeatedly in a rhythm
* That loud music has given me a throbbing headache!
to survive – to be able to continue to exist, especially in a difficult situation
* How long could a human being survive in the desert without water?
injury – a problem with part of one’s body, usually caused by an accident or an attack
* When the car hit the tree, the driver had a few injuries but everyone else was all right.
Comprehension Questions
1. Why is Michael leaning?
a) Because he has a twinge of pain in his leg.
b) Because he strained his back.
c) Because he enjoys awkward positions.
2. What kind of pain would you expect from a bruise?
a) A sharp pain.
b) A dull pain.
c) An awkward pain.
Answers at bottom.
What Else Does It Mean?
dull
The word “dull,” in this podcast, means a pain that is not very strong, but lasts for a long time: “I have a dull pain in my tooth, so I guess I should see the dentist.” The word “dull” also means boring or uninteresting: “Our history class is so dull that most of the students fall asleep during the lecture.” If something has a “dull” color, it is dark and not bright: “I want to paint the room a cheerful yellow instead of this dull gray.” The word “dull” can also mean not sharp or not able to cut: “This knife is too dull to cut a tomato!” Finally, as a verb, “to dull (something)” means to lessen or to make something less clear or active: “Do you think that watching television dulls children’s creativity?”
sore
In this podcast, the word “sore” means in pain, usually because part of one’s body has worked too hard: “If your body is sore, you might want to get a massage.” A “sore throat” is the condition where one’s throat hurts, usually when one is sick or because one has shouted too much: “I think I’m getting a cold because I’ve had a sore throat since this morning.” A “sore loser” is a person who becomes very angry when he or she loses a game: “Hamrad is a sore loser who started yelling at the other player when he lost a game of chess.” Finally, the phrase “to stick out like a sore thumb” means to be noticed because something or someone is different from everything or everyone else: “He wore jeans to the party and stuck out like a sore thumb because everyone else was dressed formally.”
Culture Note
When Americans are in pain, they usually go to their “primary care physician,” or the doctor who normally takes care of them. He or she might give a “referral” (recommendation) to a “specialist” (someone who has a lot of information or experience in a particular field or area) who can treat the pain.
For example, after an accident or injury, someone might need to see a “physical therapist,” who is a medical professional who helps someone “regain” (get again) physical movement and “abilities” (being able to do something), especially after an injury. If you break your arm and it is in a “cast” (something that prevents part of one’s body from moving while a broken bone heals) for several weeks or months, the muscle becomes weaker, but a physical therapist can help you regain movement in the arm.
Other people who are in pain might “turn to” (look for a solution in) “alternative medicine,” or treatments that are not offered my most doctors. They might use “acupuncture” (the practice of putting small needles in one’s skin) or “hypnosis” (the practice of having someone say things while one is sleeping in order to change one’s behavior) to reduce or “eliminate” (get rid of) pain. They might also try special “massages,” having people touch their muscles in specific ways.
People who are in “chronic pain” (pain that will not go away, even with medical treatment) might see a “pain management specialist,” who is a doctor who specializes in treating pain. Pain management specialists usually use a combination of alternative medicine and “prescription medications” (drugs that can be taken only with a doctor’s written permission) to treat pain.
Comprehension Answers
1 - b
2 - b