
= 从历史中认识到的教训
:toc: left
:toclevels: 3
:sectnums:

---


==

https://news.creaders.net/china/2023/09/10/2646569.html

https://news.creaders.net/china/2023/09/10/2646601.html


往往人的见解越成熟，在政治上的幻想就越少. 清醒的人不会指望独裁领袖行善，只会指望他不搞破坏。

从城市到乡村都布满了政府的眼线。城市开始运行一种“网格化管理”的社区制度；同时民间的聚众、讨薪和上访等行为受到严密管控；而司法上也越来越多地出现因言论导致的“寻衅滋事”和“颠覆国家政权”等罪，甚至有人提出，“妄议中央”也可以成为一项罪名。

为推行一带一路，媒体制作了一首童谣，并聘用外国儿童进行演唱。但这首歌在网上遭遇恶评，*人们对将儿童作为政治工具感到反感.*

习在上台前是一个能见度不高的官员，整个政治履历平平，并无值得夸耀的政绩。这不能给他以安全感。这样的资历让他难以得到各阶层的认可，而他指望在上台后去弥补这一切.

人们逐渐在习身上看出某种欠缺 -- *缺乏领袖魅力. 这种欠缺十分致命，因为这是一种领袖人物的天赋和素质，这项天赋对掌权者来说十分重要，甚至比掌握住军权更重要.*

历史中的伟大人物必然是魅力型领袖，而政治开创者也往往是魅力型领袖；政治家们通常都渴望这种魅力，因为它能赋予法律之外的合法性和号召力.

而这正是习所无法跨越的鸿沟, 他和魅力型领袖的任何一条特质都无法匹配。曾有记者采访他在梁家河当知青时的邻居，他评价习为“一个不爱交流，也不爱说笑的人”。记者在香港采访了一位习在当地方官时, 与他接触过的人，他评价习道：“很乏味，没人会记得他”。

习的团队在他登基后试图补救这一切，他们搜罗了一切魅力特质往习身上堆砌. 他们还亟需为习近平打造一个思想体系。*然而中国的政治路线基本已被毛泽东思想和邓小平理论的所涵盖，自江泽民的三个代表开始，价值体系已经沦为一种概念拼凑，显然中国领袖的思想魅力在褪色。*

习离开稿件就很困窘，无法自如地回应预设范围之外的问题。这与其它领袖在外事场合中矫健的谈锋形成鲜明的对比。

为避免更多的挫折，习只能尽少地表现自己，他的工作和生活都被刻意地低调处理。这自然能让他少出岔子，但另一方面也让他的政治形象越发苍白。

*他时不时地颁布一两条严苛的法令，以此来给社会做压力测试；如果民众反应强烈，就把法案稍作调整；如果没有抵抗，就不妨加重力道。*

宗教宣扬精神救赎，让人们不向世俗权力臣服，这本身就与一党制权威相对立。自2014 年开始，政府以“三改一拆”的名义开始拆除各地的基督教堂和十字架, 并在教堂内安装了监控。

习旨在**用领导批示，行政命令，和军警镇压来取代法制。**

政府对一切群体都采取着高压的姿态，例如在习近平任期内发生的深圳工人维权事件，和妇女反对歧视的抗议等，都被政府以雷霆手段镇压和抓捕。很多人权律师同时也是基督徒，这足见宗教会在无形中传达普世价值。


有一个显著现象就是, *对民企的打击往往和政治打击并轨.* 政府在几年间抓捕了数位“言行不审慎”的企业家，其中包括重庆的李怀庆，河北的孙大午，北京的耿潇男等，这些企业家都存在政治上的言论不当，并且为维权者和异议分子发声。这再次反映出习最根本的顾虑，就是经济自由化可能催生民主变革. 他上台后遭遇了不少反对之声，其中很多就来自于律师和企业家之流；*经济自由和思想自由一样，都会让人产生政治诉求.*

而对那些无法在政治上定罪的民企，他频繁出台法规，收紧企业的经营许可，加强生产流程审核；同时将税收和社保缴纳比率大幅上调，此外还在信贷上提高了他们的融资门槛；规定私企要建立党支部，让他们养一批官方眼线去监控自己。

企业在这种整顿之下异常艰难，**他们看出政府在刻意制造经营困境和流动性枯竭，而究其根本是为了对私营企业进行侵蚀和吞并；因为每当企业难以周转时，后面就会出现官方的影子。**很多人或许记得2015，16年的P2P 的爆雷潮，中国曾出现大批金融难民；但人们并不知道**很多P2P公司被政府做了清算接管，不过接管的只有资产，而不包括债务。**

那些财雄势大的金融寡头，它们披着私企的外衣，背后却盘踞着一帮政治权贵；他们垄断着中国的经济命脉，并以此干预朝政。这成为了习最大的执政阻力，他一直试图瓦解这些势力。**主张发展混合所有制经济，让国有资本，集体资本，非公有资本交叉持股。**政府宣称这是为了让所有制结构优化，但**目的是提供一条兼并私企的方案。**如中国联通这类**业绩不堪的国企，通过混改方案让众多互联网公司入股，但在吸收了资金之后，联通公司仍被国资控制。**

至2018年，有不少签署了股权转让的上市公司, 被国资接收；其中最突出的案例是安邦和海航集团. 海航旧股东的股权在一番清算后被“依法”清零，至于依据什么法律只字不提，只说是企业野蛮生长的结果，但中国的法律并没有关于“野蛮生长”的罪行。.

习就是要逼迫企业出让股权。**他提出了“共同富裕”和“第三次分配”这种诡谲的论调；**这种口号带有共产主义原教旨的气味，*让他更方便把矛头对准私营企业, 并给全民画饼充饥.* “共同富裕”表面是向富有的民企筹资，去解决政府的财政赤字。但习近平并没有给它们留下翻身的余地，**他不惜让大公司市值缩水，也不在乎行业凋敝导致大规模失业. **这一颠覆性的计划, *其实是以打击私企的方式来扩大国企，以便让他全盘掌握经济资源.* 习要简化社会结构的意愿；他一直不喜欢多元化，希望一切都服从于政治上的一元性.

教育培训业让年轻人接受西方教育，让他们学习外语，成为了留学生和移民人口的孵化器；不但造成了劳动力的流失，还带走了国家的外汇。习关闭了课外培训，并取消英语考试. 公共教育也开始全面排除西方文化，甚至是鲁迅这类具有进步思想的文章也要剔除。这个举措是为了削弱素质教育，培养年轻人的劳工意识基础。

为配合这项经济规划，政府对传统学制进行了改革. 这项改革将高中教育分为“普通高中+特色高中+职业高中”三类，并通过“中考”实行分流。他要让劳动力进入实体工厂，为财政创造更多的现金流。

把国企再度合并为具有高级产业优势的“大型央企”。这个合并的浪潮从2015 年的南车北车合并开始，然后持续有2016 年武钢和宝钢重组，17年神华集团和国电电力合并，18 年两个中核公司合并，19 年保利集团和中丝集团，中国宝武和马钢，招商局和辽宁港合并；以及20 年中国化工和中化集团这两个巨头合并。*央企合并的趋势在逐年扩大，习想要集中产业项目，并让这些企业成为新的经济骨干，去取代权贵手中的巨型公司。*

*习的蓝图: 三个要素：1.劳工，2.产业，和 3.资本，分别对应着三个层面—— 1.今日的青少年，就是未来的制造业劳工；2.对民企的兼并，就是创造产业集中；3.对商业寡头的制裁，就是筹集新国企的资本。*

削弱其它行业去提高制造业 的比重是反经济规律的，越发达的经济体制造业比重越低，而第三产业占比越高。此外经济多元化能抗击风险，即便是工业4.0，也不代表各个行业的劳动力都要转型去做厂工。










== 张千帆



==== *民权不张，公权必然无限膨胀.*

- "专制"和"法治"本来就互不相容，无论是个人还是集体专制, 都是法治的对立面. *既然臣民和国家统治者之间无法形成平等契约关系，民主宪政不可能在中国发芽.*

- 人民的劳动成果, 遭到各级官员和极少数既得利益者的攫取与瓜分，*人民收入的增长, 跟不上财政收入的增长.*

- **人人都有不可剥夺与不可让渡的内在尊严，**国家的义务是通过宪法与法律制度, 尊重与保护人的尊严；对尊严的任何践踏都是不合法的，一个长期践踏尊严的政府, 则是一个不合法的政府。

- 所谓"专制"，无非是号称掌握国家权力的一群人, 代替人民统治国家，而拒绝通过周期性选举等宪政机制对人民负责。

- 国家越大，可供动用的资源越多，专制统治就越稳定. 统治集团利用国家机器攫取巨大垄断利益。

- 为了维持自己的形象，专制政权热衷于自我吹捧，不择手段封杀批评。

- 自鸦片战争以降，**中国的战败和屈辱固然是列强恃强凌弱的结果，但同样也是愚顽不化的清廷和社会保守势力一再拒绝改革的结果。然而，中国历史教材对自己的过错鲜有提及，而把全部责任推给了"帝国主义"，进而仇视这些国家的民主宪政制度。这些靠自由民主发展壮大的国家只对自己的选民负责，并不对不决定本国政府命运的外国负责，更不会对它们本无好感、鄙视有加的专制政权和臣民负责。** +
鸦片战争部分是执迷不悟的最高统治者一再闭关锁国的结果，火烧圆明园则是由中国官兵虐杀外国使团所引发，但是一个不知反省的失败民族却对自己的所有失当视而不见。**虽然现政权不需要对百年历史负责，但是为了把中国打扮成一个可怜无辜、饱受欺凌、乞求"解放"的弱国，硬是从官方教科书里抹去了不利于国家形象的历史真相，把百年历史打扮成一部"可歌可泣"、"前仆后继的英勇奋斗"史；执政者出于自己的需要, 将清政府简单描绘为对外腐败无能、丧权辱国，不断将禁烟等对外策略之争升格为"爱国"与"卖国"的路线之争，夸大中国的外交失败并抹杀自民国以来的外交成就，利用民族虚荣心兜售军国主义历史观，煽动敌视西方的民族情绪以维持自己对民主宪政的抵制。** +
中国人时常抗议日本历史教科书否认"南京大屠杀"的真相，却不知自己的历史教科书问题比日本严重多少倍。*中国近代史教科书没有摆脱过政治干预，是一部为了政治目的挑挑拣拣、乔装打扮、自我炫耀、逃避责任的伪史。*

- 一群政治上的奴隶是不会受人尊重的，也不可能以相互尊重的方式平等待人. 而造成奴役状态的根源显然不在于"帝国主义". 五四运动之后，在新生苏维埃政权的积极撮合下，中国很快从无政府主义的极端, 走向极权主义极端。*一个没有政治人格的国家, 自然无法抵御专制主义政治思想的变种入侵. 所谓的"爱国主义"实际上建立在"个体人格空壳化"的基础上. 每个人成为一颗没有独立价值、没有内在尊严的尘埃。在个人自身失去个人独立的道德价值之后，国民就更容易心甘情愿地听从"大救星"的命令相互残害。*

- "革命"学说把一切罪恶都推给"帝国主义"、"封建主义"和一切"反革命势力"，惟独自己才是一贯正确的先进力量，因而可以采取一切手段消灭革命的障碍。**在这套"学说"之下，每个人都因为接受"先进"思想而变成可以无所不为的上帝，不论什么伤天害理的行为都可以获得正当理由；**任何人和自己过不去都是"进步"的障碍、民族的敌人、国家的罪犯，必欲除之而后快。(毛泽东的思想.)

- 这些形形色色的"革命"学说, 不过是个人或集团暴力夺取国家权力的挡箭牌，假借种种"思想"、"理论"、"主义"将自己膨胀的私欲包装起来。

- **权力对"是非"的垄断是徒劳的，因为权力本身就是高度流动、变化无常的.** 昨天还坐在市委书记的高位上"反腐倡廉"，明天可能就变成囚笼里的贪官。这样必然造成是非观念的混乱乃至丧失，仅剩下无所不在的权力和金钱崇拜。







- 专制教育体制从来压制独立思考和信仰。*专制者用自己炮制的"信仰"代替全体国民的信仰.* +
-它禁止实质问题的自由与公开讨论，使得整个社会生活在愚昧、麻木、偏见之中。

- 用人为扭曲的历史观, 不断制造假想的敌人和民族危机感，让自己成为理所当然的民族守护人。
- 人为制造族群矛盾, 进而以此作为维持集权专制的借口。

- 专制者的专横, 使所有说理都成为与虎谋皮的纸上谈兵. 几乎任何主张在专制社会都不可能付诸现实. 社会变革成为少数人的专利。

- 在全能政府的对面，是一群无能的人民 (没有"公民社会"的存在). 中国一直未能完成"现代公民"转型。**公民通过自己参与制定的法律统治自己，**作为权利主体承担国家义务，在纳税基础上享受公共服务，**并在有权控制和监督公权力行为的制度前提下接受政府统治，**从而真正成为亚里士多德意义上的既不愿奴役他人、也不接受他人奴役的"君子"。




==== 愚弄人民

- 官方在正统意识形态彻底破产之后, 一直在寻求可接受的替代品，但最后必然发现, 惟一可以利用的是国人尚剩的一点民族自尊感。




==== 什么样的体制, 就造就什么样的人民

- **专制社会的人民往往显得过于自信、轻信乃至狂妄，不仅因为他们从小被灌输一种过于简单的善恶观，并认定它是唯一正确的真理，**而且由于舆论受到严格控制、他们在此基础上形成的世界观过度单一. 独立人格缺失本来就是专制社会的常态. 多数国民染上了这种性格，便造就了一个悲剧民族.

- *专制造就国民的病态人格，病态人格反过来维持和加固专制.*

- 专制的维系, 是建立在臣民的普遍恐惧基础上的. 使每个人都变成在自己的职位、待遇、名利、家庭面前畏首畏尾。当权力变成可以兑换一切的通货，任何道德或法律规则都显得苍白无力。整个国家成为趋炎附势的竞技场。
- 一个不讲理的政府, 培育了一个不讲理的民族，犬儒、势利、权力崇拜成了社会每天呼吸的空气。
- 当一个民族泯灭了是非观念和基本耻感，那么无论发生什么惊天动地的事情都不再稀罕。

- 西方的"左派"立场未必正确，但是至少操守应该肯定，因为他们是敢于批评政府和舆论主流的少数派。中国的"左派"恰好相反.



==== 什么样的人民, 造就什么样的体制

- 要建立宪政，人民首先要树立自己的尊严。**个人尊严是国家宪政的前提，不可想象一个奴才治国的奴隶国家, 能制定和施行一部人人自由的宪法。**要打破专制的窠臼，首先必须唤醒普罗大众作为公民的主人意识。

- *宪法赋予了民主权利而自己却不知珍惜, 是可耻的.*






























'''




== 中国现代历史


1895中日甲午战后，清廷指派袁世凯训练中国第一支现代化军队. 这段历练使袁有机会在军队培值党羽，奠定日后的权力基础。


溥仪退位前一个月, 孙逸仙被推举为临时大总统, 但其武装力量无法与袁世凯相抗衡. 所以很快将头衔让出给袁世凯.

孙派提出要求:  +
1. 为了象征民国的创建, 袁世凯必须远离他的北方根据地, 而到南京就职.  +
2. 令袁世凯公开主张“共和国为最良国体”. +

对第一个要求, 袁世凯拒绝. 借口: 北方日军情不稳，需要他坐镇北京. 的确, 当时北京、天津、保定等地相继发生叛乱与暴动，不过有人认为, 这些乱象也许是袁本人所鼓动的，借以证明北京不可一日无他。








242
















