
= 傅世宁医学通识
:toc: left
:toclevels: 3
:sectnums:

'''


== ★ 医学的目的 : 是先保证让人活下来, 然后才有其他治疗可能.

ICU 重症医学科 : 工作就是把所有最危急的病人的生命体征, 先稳定下来，再送回其他科室继续原发病的治疗。

医学存在的目的, 是先保证人活着. 先活下来，然后才有其他可能。

医学界的一个共识就是, 艾滋病、癌症，很快就能成为慢性病，人不会因为这些病很快死亡。



== ★ 不怕难题有多难，就怕没有解决方法.

学医之后我体会到 : 不怕难题有多难，怕的是没有办法解决。只要有办法，我总会一步一步地搞定它。


每个病人都是不同的个体，治疗的反应因人而异，结果也不同。

医学(包括医学开拓) 面临的一个现实就是"不确定"。


.案例
====
在几十年前，心脏外科就面临着一个难题，就是没办法把心脏里的血引出来，这样就不可能打开心脏做手术。

到了1954年，有个美国医生 Lillehei (李拉海) 认为，不能眼睁睁看着这些孩子死。他设计了一种大胆的手术方案。给孩子做手术的时候，让他的父亲躺在边上，把孩子的血管和父亲的血管连在一起。这样，孩子心脏里的血就能引出来，流到父亲体内，用父亲的肺给血液加上氧，再打回孩子的身体。这么做，手术的风险也从一条命增加到了两条命。

李拉海医生不做，没人会说什么。但是一旦失败，父子俩人的命都没了，而且李拉海的职业生涯也会到此结束。
====


.案例
====
慢性心衰, 也就是心脏功能逐渐衰竭. 到最后，病人甚至连平躺都成了奢望。想要治愈只能心脏移植。全球每年有约100万严重的心衰患者，需要进行心脏移植手术。但是，哪有那么多供体给病人呢？

为了解决这个问题，美国的医生们最先研发出了人工心脏。在找到合适的心脏供体之前，代替心脏工作。
====




== ★★ 一切医疗只起"支持"的作用, 核心治愈靠人体自身的修复.

真正治好病的，是病人自己。所有的医疗行为，只是起到支持的作用。*医疗的本质是支持生命自我修复。* +
首先是人体的自我修复，然后才是医学的支持。*人体的自我修复是核心，是关键。*

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|人体的自我修复, 主要靠细胞分裂。
|- 骨折之后，骨折的地方会长出骨痂，逐渐让断裂的部分愈合，靠的也是细胞分裂。
- 秋水仙碱本来是一种治疗痛风的药，小剂量可以治病，但是超过剂量很容易中毒，甚至死亡。这种毒根本没有解药。*服用致死量的秋水仙碱，会阻断细胞的分裂，让细胞在分裂中期死亡。细胞不再分裂了，不再产生新的细胞了，这就剥夺了疾病治愈最基本的环节——自我修复。*

|一切医疗都是用来支持"人体的自我修复"
|在疾病面前，*尤其是大病，医疗的支持作用是必不可少的。因为这个时候，人体的自我修复垮了。医疗的支持，就是给自我修复赢得时间、创造条件，等待自我修复最终发挥作用、战胜疾病。*

- ICU，也就是重症医学科，是疾病最重、距离死亡最近的地方。里面几乎所有的救命手段都是支持。
.. 呼吸机 : 是支持肺，让肺休息，等待自愈.
.. 床旁的血液净化 : 是支持肾，替代肾脏的功能，等待自愈.
.. ECMO 魔肺 : 是对心脏和肺，提供最高级别的支持.

*所有这些顶级的医疗设备，都是为了先把命保住，给自我修复赢得时间、创造条件，然后等待"人体的自我修复"发挥作用。*

- 得了肺炎，先用抗生素杀死大部分细菌，但是总有耐药的，没被杀死的细菌。怎么办？这个时候，人体的白细胞发挥作用 (即自我修复)，消灭剩下的细菌，让肺炎痊愈。
- **同样是肺炎，但是白血病病人, 或者艾滋病病人, 就没有这么幸运了，**会非常难治，这些病人甚至会因为肺炎去世。*因为这类病人的白细胞吞噬功能差，自我修复能力低下*，因此，再强大的抗生素效果也不好。

- *如果癌症细胞可以逃过人体免疫细胞的监视，那么说明这个时候自我修复垮了。如果不能够恢复这种自我修复，病人再怎么手术、放疗，效果都不好。* +
让免疫细胞获得识别和杀伤癌细胞的能力, 就是癌症治疗方法之一。
|===

'''

== 人体有"代偿机制", 这就导致 -> 疾病不是突然发生的，而是突然发现的

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|很多病没有症状，一旦发现就是中晚期. 所有严重的慢性疾病都不是突然发生的，而是突然发现的。
|- 很多胃癌的病人, 早期没有明显症状。幽门螺旋杆菌感染, 可以导致胃癌. 世界卫生组织把这种细菌列为一级致癌物。 +
*一级致癌物指的是 : 有明确证据表明可以致癌的物质*，比如雾霾、烟草、槟榔、黄曲霉素等等。
- 结肠癌，从一个良性的腺瘤, 逐步演变成恶性肿瘤，通常需要15年。
- 女性持续的高危型HPV感染, 到发生宫颈癌，一般需要大约十几年（高危型，就是最容易引起宫颈癌的病毒类型）。
- 中国人死亡原因第一的心脑血管病，*也是从青壮年开始，血管上就开始出现斑块，经过20-30年的进展，血管逐步狭窄。当狭窄超过一定范围，才会出现"心脏病"或"脑血管病"的症状。*

这种无症状的进展是多么漫长。但是，一旦出现症状，多数都是中晚期。 +
*之所以人体能够在疾病状态下，十几年甚至几十年都不出现明显的症状，是因为人体有一种"代偿机制"。* 代偿, 是慢病进展过程中, 人体的妥协.

|*代偿, 即是代替、补偿。身体某些组织或者器官持续受损，已经没办法修复原样了，人体就调动没有受损的部分，加快补充或者代替受损的部分完成工作。*
|- 幽门螺旋杆菌会持续攻击胃的细胞，引起胃炎，细胞就会死亡。这个时候，人体就会启动代偿机制，让深层的干细胞加速分裂，赶紧补充死亡的细胞。这样就防止发生严重的穿孔、出血。 +
所以，人体的代偿, 能够让器官在持续损伤的状态下，基本上能够满足功能，也就是凑合着用，所以才不会出现明显的症状。*只有到了疾病晚期，代偿不动或者超过极限了，症状才会出现。*

代偿的最终目的, 是保证器官的基本功能，也就是为了保命。 +
*所有的慢性病，人体都会启动代偿。*

- 比如高血压。血压持续增高，心脏射血的负担就会增加。所以，心肌就会变得肥厚，射血才更有劲。这是代偿。
- 甚至冠心病病人，血管狭窄了、堵了，这根堵了的血管周围的小血管, 就会变粗、变长，甚至长出新生的血管，替代这根堵了的血管给心肌供血，防止发生致命性的心肌梗死。这也是代偿。

*这种机制让我们在没办法去除持续损伤因素的情况下，先妥协着活下来。这本身是有利的一面，但它也有另一面，即同时也掩盖了病情。*
|===

代偿带给我们疾病防治的建议:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|建议 |Header 2

|既然很多慢性病在早期没有症状，我们就要主动筛查。
|开展了癌症的早期筛查。

- 比如结肠癌、直肠癌的发病率下降，主要原因就是推广"结肠镜"检查。 +
从2000年到2015年，美国50岁以上的成年人接受结肠镜检查的比例从21%升高到了60%。

|从源头上预防, 或者从中间环节阻断，可以有效防止慢病的发展。
|- 比如宫颈癌。绝大多数是HPV病毒感染，整个发展链条是 : 先引起慢性炎症，然后到不典型增生，最后才发展成宫颈癌。 +
-> 从链条的"源头上"预防HPV感染 : 接种宫颈癌疫 +
-> 从链条的"中间过程"中, 预防HPV感染 : 对于已经发生感染的，在不同的阶段进行针对性的治疗，就是阻断中间环节，避免最终发展成癌症。

但是，很多病我们很难从源头上预防，也很难完全阻断。 +
比如冠心病。尽管我们严格控制血压、血糖、血脂、不吸烟，但是还是有相当比例的人群得了冠心病。而且尽管严格用药，也会有相当比例病人的病情依然在进展。

|巧妙地放大代偿机制。
|- 冠心病是有血管狭窄了。那么，狭窄血管周围的小血管就会变粗、变长，甚至产生新血管，代替那些狭窄的血管完成供血任
务。这是代偿。 +
放大代偿，就是主动帮助小血管长出来。通过适度运动就可以帮助形成这些小血管。
|===








-


== "病"和"症状"不是一回事

所有不舒服的感觉，都叫症状。广义的症状, 还包括到医院检查发现的各种异常。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|有时候病比较复杂，会出现一系列的症状。
|- 比如"脑梗塞"这种病，它会出现三个症状引起咱们注意。这三个症状加在一起有个名字，叫做“120” : +
-> 1：看1张脸。有没有口角歪斜、脸不对称。 +
-> 2：两只胳膊平举。看看有没有胳膊无力、下垂。 +
-> 0：聆听病人的语言。看看是不是说话不利索。 +
*如果人同时出现这三个症状，90%以上的可能性就是脑梗塞。*

|不要把"症状"当成"病"来治.
|- **人在大出血的时候，血压低是一种自我保护，血压低下来出血速度才会慢。**如果快速输液，把血压提上来，那么出血反而更快了，结果就是加速了伤员的死亡。所以这个时候应该少输液，让血压维持在一个较低的水平，抓紧时间手术，止血才是关键。

这个病例说明： +
-> 症状对人具有保护作用，就像低血压可以减慢出血速度一样。 +
-> *如果盲目地干预症状，有可能会南辕北辙。*

所以，正确区分"病"和"症"就很重要。不要把"症状"当成"病"来治.

- 得了慢性感染，比如肺结核，很多人会出现"缺铁"的症状，会出现"缺铁性贫血"。这种缺铁现象, 就是人体的一种自我保护。因为微生物要存活需要铁，但是微生物却不能自己合成铁，只能从人体获得。所以，感染的时候人体会减少铁的吸收，故意造成一种缺铁状态，就是为了限制细菌的生长。如果盲目补铁，反而会加重病情。

- 怀孕的女性在即将分娩的前几天，血液里有个凝血指标, 会快速大幅度上升，有时候甚至升高几十倍，表示血液容易凝固。 这还是为了自我保护，防止未来几天生孩子的时候，产道损伤可能发生的大出血。 等到生完孩子，安全了，这个指标也会迅速恢复正常。


|但症状具有"双刃剑"效应
|- 伤员大出血的例子, 血压低是为了保命，但是血压过低或者持续时间过长，会引起器官的缺血，导致器官功能衰竭，接下来也会引起死亡。
- 过敏是人体接触到异物，免疫系统产生的排斥性反应，目的是为了让咱们远离过敏物质。但是，有些人的过敏反应特别强烈，会出现休克、气道痉挛、水肿，严重的会引起窒息和死亡。

|要区分哪些是病，哪些是症. "病"需要治，但"症状"却未必需要处理。(即不要头疼医头, 脚痛医脚)
|- 骨刺不是病，而是症状。真正的病，是人的骨骼和关节的老化。
- 高血压是怎么来的呢？**随着年龄增高、肥胖或者有些说不清的原因，血管会逐步狭窄、硬化、血流阻力增加。**这个时候，为了保证器官的正常供血，血压就会增高，这就是"原发性高血压"。高血压只是为了在血流阻力增加的情况下，让器官仍然能够保持一定血流的保护性反应。 +
所以我(傅世宁)认为，把"原发性高血压"定义成一种病，不如把它看成是一种症状更贴切。真正的病是隐藏起来的，引起血流阻力增加的病理改变。 +
+
症状具有双刃剑效应，如果症状严重或者持续存在，就一定会带来后续的损害。血压持续增高，必须口服降压药，防止血压持续异常引起后续的心脏、脑血管受损。但是你要记得，治疗高血压更重要的应该从改变生活方式，降低血流的阻力着手，而不能单纯依靠药物降压。(治标与治本的区别.) 别跟症状死磕，而是要找到病根，治病。

明白了哪些问题是"症"，哪些问题是"病"，接下来的治疗才更有针对性。

|===






== 医学思维: 提出假设-收集证据-验证假设的循环 ("麦肯锡方法"就是遵循的这个路径)

.案例
====
有一个胖胖的已经生过小孩的中年女性说她右上腹疼痛。
没经验的医生怕遗漏，可能就会把所有肚子疼的相关检查都做了。
而高手会马上假设她会不会是胆囊炎呢？然后让病人做一个超声、血常规，立刻就能确诊了。

因为，有的专家把这类病人的特点总结成了4个以“F”打头的英文单词： +
- Female（女性） +
- Forties（40岁左右） +
- Fat（肥胖） +
- Fertile（生过几次孩子）

**符合“F4”特点的病人, 患"胆囊炎"的概率比其他病人高。**这个病人又恰好是**右上腹疼，所以医生会优先考虑是不是胆囊问题。**
====

.案例
====
大出血的时候，病人就会血压低。血压低才能让出血速度慢下来，这是人体的保命反应。但是这个大出血的病人，血压不低，而是越来越高。我立刻想到这个病人可能是脑水肿，也就是脑子肿了。*大脑里压力高了，所以人体会拼命让血压升高，以对抗大脑里面的高压，给大脑供血。*
====

高手会保持开放性，一旦有证据表明最初的假设不对，会立刻校正，提出新假设，寻找新证据，再来一次新的验证。不会钻牛角尖。 +
福尔摩斯说过一句话：一旦你排除了所有的不可能，那么剩下的不管多么难以置信，就是真相。

但是低手就容易产生惯性思维。认准一种假设之后，往往容易主观上丢弃不符合假设的证据，而不是修正假设来适应证据。

'''

== ---------- ----------

'''


== 找不到发病机制, 找不到病因，也就没有治疗方法.

我们通常把人体解剖学、生理学、病理学这三门基础学科的成立，看做是现代医学诞生的标志。 即 : 不仅要找"发病部位"，还要研究"发病机制", 和"致病因子". 致病因子就是引起疾病的物质实体。

比如非典:
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|发病部位 :
|肺

|发病机制 :
|

|致病因子 :
|蝙蝠身上的“非典”病毒
|===


- 寻找传染病的"病因"还是最简单的。有些病可以找到"发病部位"，但是找不到确切的"发病机理"。比如渐冻人。*找不到病因，也就没有治疗方法。*
- 也有有的病研究了几十年，找了几十年的病因，最后发现它根本不是病。比如同性恋。
- 甚至还有很多病一点线索都没有，连诊断都做不出来。

所以，**治病必须打断发病机制，改变细胞或者器官的功能。**而承载这个改变机能任务的, 就是"药"。

- 抗生素通过杀死或抑制细菌，治疗感染，是打断发病机制；
- 退烧药通过调节体温, 调节中枢的功能，达到退烧；
- 口服避孕药通过抑制排卵，防止怀孕；
- 紧急避孕药, 阻止受精卵在子宫内膜着床，达到避孕。



== 每一种药，都代表了特定年代的医学认知水平

药的实质, 就是医学解决方案的物质载体。

比如阿莫西林，它背后是体现着一整套复杂的认知体系。比如嗓子疼和细菌的关系，细菌的结构，药物杀灭细菌的机制，药在人体怎么代谢，半衰期是多少等等。 每一种药，都代表了不同年代的认知水平。所以只有医学整体认知水平提高了，才可能交付出更好的载体，也就是更好的药。


对于药的安全性和有效性，法律监管只能保证它是一个“合格”的药。但是，让药更安全、更有效、副作用更小，最终依靠的是整体医学认知水平的提高。





== 要让病人能有尊严地活着


临床医生要做的, 就是结合医生自己的临床经验 + 患者的期望意愿, 来给病人制定最佳的治疗方案.

现代医学已经认识到 : 单纯地延长存活时间是远远不够的，维护患者的尊严，支持患者的生活意义，提高患者的生命质量，是医学最重要的使命。 +
不关心人的科学是傲慢，没有科学依据的关心是滥情。如果你不能切实地帮助患者，你的关心，就没有价值。(但很多时候是做不到实质性的帮助的，只能安慰，你不是上帝，不可能解决所有的问题. 所以关心依然是有价值的.)

很多病，会让人失去尊严。

癌症晚期的病人最怕的不是死亡，而是疼痛. 有的病人痛不欲生，甚至抑郁自杀。

晚期癌痛，医生们就用药物或者手术，让病人不那么疼。让病人在不疼中，有尊严地走完生命的最后时光，对于他们来说，比多活几天更重要。


医学从来都具有"科学"和"人文"的双重性格。只有伴随着"科学"的人文, 才是真人文。




== 让病人追求自己独特的意义

有的人们为了实现自己的价值，他们并没有选择医生认为的最有利的方案。

- 一个乳腺癌的女性坚持要怀孕，怀孕可能会加重她的病情，缩短她的生命。但在她看来，能有个后代, 就是她生命的全部意义。


== 医患不是甲方乙方，而是"阶段性"的联盟.

不应把医疗, 单纯看做是消费. 因为医疗这个行业, 带有特殊性。每一个病人都是不同的个体，即使是同一种病，治疗过程也不相同，达不到完全的标准化流程。同时，治疗结果也是不确定的。如果把医疗看做是消费，那怎么评价质量呢？如果我对这次消费不满意，可以退款吗？

- 医生具有技术优势，掌握诊断技术、病因、预后（预测疾病的可能病程和结局）、治疗方案, 及预防策略。
- 患者的优势在于 : 提供治疗的体会、本人生活习惯，以及其他有助于诊断和治疗的关键信息。(即提供医学实验的效果反馈)

*医患之间, 其实只有阶段性关系。只要有更好的治疗方法，病人可以随时换医院、换医生，而且不论治疗多久，这种医患关系早晚是要终结的。*


== 中国推行的医院间的分级诊疗，本质就是分工协作

- 乡镇卫生院、社区服务中心 : 保障基础的医疗保健，慢病管理、健康教育, 可以完成疾病的首诊。
- 大医院和专科医院 : 对于疑难病、复杂病、急性病有能力有经验。

大医院和基层医院相互转诊，急性病在大医院得到有效治疗后，还可以转到基层医院继续康复。

这就是基层首诊、双向转诊、急慢分治、上下联动。






'''

== ---------- ----------

'''


== 人的处境, 会大大影响人的心理

你知道每天有多少外地病人, 进京看病吗？每天至少有70多万。这么算下来，每年就是两个多亿。这些人风餐露宿，整宿守在医院门口，就为了一张专家号。你能想象病人排了一宿的队之后，见到医生是什么感觉吗？就像见了神一样。(所以古代, 带有宗教色彩的农民起义, 都把宗教神棍当做神仙看待, 因为他们声称能看病.)


== 早诊断, 是经济收益最大的方法

很多病根本没症状，是去医院检查以后才发现的。

实际上，几乎多数癌症, 都经历了一个漫长的没有症状的过程。

- 肺癌可以在体内潜伏20多年，然后突然转变为侵袭性的癌症.
- 科学家推测，在90岁以上去世的人当中，如果能够给他们进行尸体解剖，很可能多数人体内, 都有癌症或者癌前病变，只是生前没有感觉而已。

- 我们每个人从出生开始，得冠心病的风险就在不断增加。*婴儿一出生，血管就开始逐渐地老化，到了成年，血管壁上开始出现
斑块，血管会慢慢硬化变窄。当血管继续狭窄，超过70%、80%，甚至90%的时候，人就开始出现"心绞痛"的症状了。*


治病的代价远远大于预防。疾病预防，永远是性价比最高的举措。






== 人会生病的原因

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|我们的基因是不完美的 :
|癌症，各种遗传病、慢性病，都跟基因有关。

|人体设计是不完美的 :
|**进化的逻辑是让利益和风险平衡，而不是让利益最大化。所以导致了人体器官性状的不完美。**可以说，几乎人体的每个器官, 都有不完美的地方。

你知道人类到今天可以得多少种病吗？到目前为止，世界卫生组织（WHO）一共收录了26000多条疾病的名称。但肯定还有很多未知的病不在这个疾病清单里。

- 胃酸几乎能杀灭所有的细菌，但是它却不能消灭"幽门螺旋杆菌". 而这种细菌会让我们得胃炎、胃溃疡，甚至得胃癌的几率明显增加。
- 我们人体的免疫系统, 可以攻击病毒、细菌、癌细胞，但是它有时也会误伤我们自身 -- 产生"自身免疫病"，比如红斑狼疮、类风湿关节炎等等。
- 心脏很重要, 但心脏自身的血管却非常细，细了就容易窄甚至堵，结果就是心绞痛和心肌梗死。
- 人类排泄废物是用两个通道：一个尿道，一个肠道。一个液体，一个固体。多一套系统，也就多一层风险。医院现在要分"泌尿科"和"消化科", 来处理两条道上的问题。

|人类与环境适应的不完美 :
|"人类进化"的速度, 永远赶不上"人类生活环境"变化的速度，一个重要的结果就是带来了病。

- 不用使劲跑就可以获得高脂肪、高热量的食物, 同时也带来了肥胖、高血脂、高尿酸等一系列代谢性疾病。肥胖又增加了人类患癌的风险。
|===



== 内共生

目前所有的研究, 也只能反应内共生与疾病关系的冰山一角.

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|内共生
|真核细胞里的线粒体, 是由细菌演化而来的。真核细胞和它内部的细菌是"内共生"关系。

- 如"5-羟色胺"是让人产生快乐的物质。人体自身合成的5-羟色胺只占总量的5%，另外95%是由细菌合成的。
- 肠道。为了和细菌作战，人体给肠道配备了最王牌的部队。有七成以上的免疫细胞集中在肠道，包括巨噬细胞、T细胞、NK细胞、B细胞；还有七成以上的免疫球蛋白A（IgA）是由肠道制造的。可以说肠道是人的免疫系统和细菌作战的最大战场。

|打破内共生就会带来病
|很多药物包括化疗药物、抗生素，很多食物包括糖，都会干扰"内共生"。内共生关系一旦被打破, 就会带来病。

1.细菌移位会带来病。也就是说，细菌跑到不该去的地方了。细菌如果在它应该待的地方，就是正常菌，或者不会引起严重的问
题；如果细菌跑到其他地方，就会变成有害菌。

- 阿尔茨海默症，在这些病人的大脑里，发现了牙周炎的细菌和一些引起口腔溃疡的白色念珠菌。

2.内共生被打破，有害的微生物就会趁虚而入，这样也会带来病。

- 很多女生用含有杀菌剂的洗液冲洗阴道，那么接下来反而会引起真菌感染，引起"真菌性阴道炎"。
- ICU 中, 因为严重感染必须大剂量应用抗生素的病人，就很容易继发耐药菌的细菌感染, 或者深部真菌感染。

3.内共生被打破，导致"细菌合成化学物质"异常，也会带来病。

- 大脑细胞完成信号传递功能，涉及到主要20多种化学物质，这些化学物质中, 很多都是由肠道细菌参与合成的。如果肠道菌群紊乱，就会引起精神问题，比如焦虑、抑郁、自闭症等等。

|怎么重建或者恢复内共生呢？
|1.如果不是严重的或者关键部位的细菌感染，就少用抗生素。因为抗生素是对内共生破坏最大的药物。

- 健康人不要动不动就用含杀菌剂的任何洗液或者漱口水。

2.孩子的成长过程别太干净，要让孩子多和大自然接触.

- 产妇能顺产就不要剖腹产。现在研究认为，经过女性产道的婴儿, 可以迅速建立起第一道多样性更好的肠道菌群。

3.多吃膳食纤维丰富的食物。比如苹果、梨、魔芋、黑麦、黄豆、青豆、枸杞、石榴、椰子、冬
菇。

4.少吃糖。

|===




== 免疫系统的问题

[.small]
[options="autowidth" cols="1a,1a"]
|===
|免疫系统 |Header 2

|认不出“坏人”
|- 流感病毒, 为了逃避人体免疫，会不断地变换病毒表面的H蛋白。H蛋白就是一种辨别物质，H蛋白变了，人体免疫也就认不出来了。
- 水痘-带状疱疹病毒，它可以藏在神经节里。很多病毒可以藏在细胞里，让免疫细胞找不到。
- 癌细胞有个机制能逃过人体免疫，就是伪造一张“身份证”，骗过免疫系统的检查。

有时候，即使认出来了，癌细胞也会释放一些物质麻痹免疫细胞，让免疫细胞的杀伤能力大大降低。

|认不出“自己人”, 把“自己人”当“坏人”
|1.人类自身免疫病有100多种，但是机理都相似，都是人体免疫不断地攻击自身的细胞。

- 红斑狼疮这个病，眼睛、皮肤、造血系统、肺部、肾脏，几乎人体的每一个器官，每时每刻都在遭受着自身免疫的攻击.

*在临床上，各个学科的难题通常都会涉及到自身免疫问题。有专家说过，当你遇到解释不通的临床问题时，就想想会不会是自身免疫出了问题。*

'''

2.过敏 : 就是免疫系统把本来无害的物质辨别为“敌人”，产生过度的反应。

- 过敏性鼻炎、荨麻疹、湿疹、哮喘这些病都是过敏。

|打不过“坏人”
|免疫功能低下。

- 比如艾滋病、白血病、糖尿病、尿毒症。这些病有的是免疫细胞的数目减少，有的是功能降低.

|===


== 癌症

==== 癌症的链条

[.small]
[options="autowidth" cols="1a,1a,1a"]
|===
|链条环节 || ← 针对此环节的治癌方法

|DNA 错误的图纸
|正常的基因突变成癌基因.

正常细胞生长分裂, 需要"生长信号"，同时还有"抑制信号"防止过度生长。癌细胞一个最大的特点就是"生长信号"多，而且对"抑制信号"不敏感。所以，癌细胞长得快，不停地长。

|← 靶向药


|失效的自检体系
|人体有一种"细胞凋亡机制"，目的是让这些不合格细胞自我销毁。细胞的凋亡就是细胞的程序性死亡，它是人体防止细胞癌变的一种主要机制 -- 由抑癌基因（ tumor suppressor genes）控制。P53就是一种抑癌基因。 +
如果抑癌基因发生突变, 那本该自杀的细胞就会不死。
|←


|灵活的能量供应
|正常情况下，一个细胞和它最近的毛细血管的距离, 不能超过100微米，也就是0.1毫米。太远了营养够不着.

但是，癌细胞特别灵活。癌症的时候，促进血管形成的信号增多，而抑制血管形成的信号减少。这样，就有持续的新生血管形成，源源不断地给肿瘤组织供血。这就好比是，“癌症跑车”上路，既然找不到固定的加油站，那么就自带移动的加油枪，随时供应燃料.

所以在临床上，多数恶性肿瘤通常都是血流丰富。医生们甚至用这个特点区分良性和恶性。

|← 血管内皮生长因子抑制剂，就是针对癌症组织血管丰富的特点，抑制血管生长，也就抑制了肿瘤的生长。


|失明的警察
|正常情况下, 免疫细胞就是警察，它们会主动寻找和攻击癌细胞。但癌细胞会伪造一张“假身份证”，躲过警察的检查. 这种机制叫做免疫逃逸。
|← 免疫治疗药物PD-1抑制剂，就是恢复警察的火眼金睛和战斗力.


|篡改生死簿
|正常细胞的分裂次数是有极限的, 所以细胞是有寿命的。但癌细胞可以无限次分裂。
|←


|自由游移
|正常细胞就是按照基因编码，不会乱长。胃里的细胞永远也不会长到鼻子上去。 +
但是癌细胞不同，它们能在组织内部和组织间灵活移动，也就是癌症容易发生侵袭和转移的原因。
|←

|===

而所有的癌症治疗方法, 就是针对上述这6大环节的 (切断链条). 所有治疗的前提，都是基于医学对于这六大环节的认知越来越清晰。


==== 癌症发生的原因

2017年《科学》（Science）杂志发表了一篇研究, 认为 : 引起癌症基因突变的因素中，最主要原因是染色体复制过程中发生的随机错误，这个因素占到了66%。而环境因素和遗传因素，加一起也只占34%。

- 骨癌的基因突变：随机错误占了99.5%，遗传占0.5%，与环境因素完全无关。
- 甲状腺癌，随机错误占98%，遗传占1.5%，环境因素仅占微不足道的0.5%。
- 非何杰金氏淋巴瘤、脑部肿瘤、前列腺癌、睾丸癌，这些癌症的基因突变中，随机因素都占到了95%以上。

细胞分裂是人体的一种自我修复机制，细胞分裂带来了随机错误。

人的基因组有31.6亿个碱基对，每次分裂这31.6亿个碱基对都要复制一次。细胞的每一次分裂都带来了基因突变. 所以，细胞分裂次数越多，癌基因发生的几率也就越大。只要活得足够长，每个人都会得癌症。癌症是长寿必须付出的代价。

数据显示，40岁以上的人患癌症的风险呈指数倍增长。如果人的寿命达到85岁，累计癌症发生风险高达36%。

《科学》（Science）杂志上的一篇研究指出，中年人食管的上皮细胞，尽管在显微镜下看起来形态和正常细胞一模一样，但是进行
基因分析发现，已经有一半以上的细胞都发生了和癌症相关的基因突变。

将癌症推迟的方法就是:
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|减少器官损伤, 即减少细胞修复次数 :
|- 戒烟、戒酒、减肥、多运动、多吃全谷物食品、蔬菜、水果、豆类，少吃糖、少吃红肉（比如猪肉、牛肉、羊肉）
- 避免乙肝病毒、丙肝病毒、幽门螺旋杆菌、HPV病毒感染。已经感染了，要治疗或者定期复查。

|定期进行疾病筛查。早期发现，早期治疗.
|避免这些良性的病变, 进一步发展成为恶性的癌症。 +
超过一定年龄之后定期进行科学的筛查，是发达国家总结出来的可行的癌症预防方法。

- 美国明尼苏达大学癌症检查中心，对45岁以上无症状的普通人, 每年做一次"乙状结肠镜"检查，见到"腺瘤"就切除。("腺瘤"就是一种癌前病变，长期发展就可以变成癌症。) 这样做的结果，就是结肠癌、直肠癌发病率比预期的减少了85%。

|===

== 冠心病：不只是器官问题，而是全身病

冠心病是因为血管窄了、堵了，引起心绞痛和心肌梗死。但是，为什么有些冠心病的病人容易脑血管也出问题呢？为什么有些男病人容易出现性功能障碍呢？原因是 -- 冠心病反映全身血管问题. 换言之, 是先有血管问题(因), 后有冠心病(果).

血管内皮就会受损，血液里的脂质就会沉积，就像河道的淤泥一样。时间久了，还会形成斑块，血管就会越来越狭窄。正如交通体系拥堵一样, 一旦一个部位出问题了，窄了，那么其他部位的血管，能好到哪儿去呢？ 动脉血管出问题了，长斑块，变狭窄，影响血流了 :

- 如果出现在"肾动脉"，就会导致肾动脉狭窄；
- 如果"脑血管"病变了，就容易发生脑血栓、脑出血；
- 如果发生在供应"肠道"的动脉里，就会引起肠道功能异常。完全堵死了，还会出现肠坏死。
- 如果供应"男性器官"的血流减少了，离阳痿还远吗？
- 当供应心脏的动脉血管——冠状动脉长斑块，变狭窄了，如果超过一定程度，就是冠心病。

这些病本质上都是动脉血管出问题了。(动脉血管问题是肇事的"因", 上面这些病只是后到的"果"而已)

有了冠心病的病人，很可能也容易发生脑血管病，或者其他动脉缺血引起的病。


医生想到：既然冠心病是因为血管里有地方窄了，那把这个最窄的地方扩张起来，不就可以了吗？但是问题很快来了，大约50%的病人，他们好不容易拓宽的地方，慢慢又重新窄了。 +
到了1987年，法国有位医生说，如果拓宽后再放个金属支架撑起来，就不会变窄了吧？ -- 这就是冠脉介入手术。

但是，对于"稳定性心绞痛"的病人，和单纯吃药比起来，吃药加上支架并不能降低病人发生心肌梗死的几率和死亡率。

*"稳定性心绞痛"就是冠脉血管狭窄了。严重的，如果狭窄在70%以上，就会影响血流。病人累的时候，心肌需氧增多，但是血流又供不上，就容易发生心肌缺血缺氧，就会疼。这就是稳定性心绞痛。*

为什么放支架, 并没有降低这部分病人发生心肌梗死的几率呢？

*引起冠心病的主要问题，是年龄，是不健康的生活方式，还有高血压、高血脂、糖尿病、肥胖等等。所以，如果这些因素持续存在，单纯放支架解决了一个部位的狭窄问题，但是预防不了其他部位继续狭窄。就像交通拥堵一样。在高峰期，单纯拓宽一个桥、一个路口没用，因为流量大这个根本问题还存在，那么还会引起其他的路、其他的桥继续拥堵。*
同样，冠心病可能是一个矛盾最集中的点而已。得了冠心病，很可能其他部位的血管也好不到哪里去。


已经证实的可以降低冠心病死亡率和心肌梗死的药物，包括：

- 抗血栓的药物，如阿司匹林；
- 降血脂的药物，如他汀；
- 减慢心率、降低心肌氧耗的药物，如倍他乐克等；
- 降低血压、改善心肌重构的药物，如某某普利、某某沙坦。

这四种药物，是治疗冠心病的基础药物。



给西直门桥拓宽、改造。这就好比是介入手术。介入手术尽管解决不了全局问题，但是介入手术可
以解决矛盾最集中、最危急的情况。


心绞痛变得没有规律了，我们也称为"不稳定性心绞痛"。药物已经控制不住了，不处理的话很容易发生心肌梗死。这个时候做介入手术，放支架，也是非常有必要的。 +
有些病人吃药控制不住心绞痛的症状。对于这类病人，介入手术对于改善症状也非常必要。

最后，咱们还有其他方法，这就是冠状动脉搭桥手术。它尤其适合那些合并了糖尿病的严重冠心病病人。



== 压力会导致的胃溃疡


把两只猴子 a,b 分别捆在两把椅子上，每20秒钟椅子会自动放电一次。但是，给其中一个猴子a开关, 如果它能在快要放电的时候准确地按下开关，那么两只猴子就可以同时避免挨电。按错了，就一起挨电。几天过去了，其中一只猴子得了胃溃疡，另外一只安然无恙。是哪只猴子病了呢？是积极主动，按压开关的这只猴子a呢？还是消极被动，默默承受的那只猴子b呢？答案是，负责按压开关的 a猴子病了。







== 临床诊治指南

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|临床诊治指南
|临床诊治指南，它的定义是：针对特定的临床情况，系统制订出的帮助临床医生和患者做出恰当处理的推荐意见。

指南,是一套标准化的方案，对医生治病的每一个环节都有建议。比如，怎么检查、怎么治疗、怎么手术、怎么用药、剂量多少、联合
用什么药。几乎所有的常见病都有这么细的指南。 +
同时，对于同一种病，不论这种病有多简单，都会用到多个不同的指南。

- 就拿"阑尾炎"这种外科医生入门级的手术来说，也至少要用到4个指南。麻醉有《麻醉学操作指南》；手术有《阑尾炎诊治指南》；术后要用到《抗菌药物在围手术期的预防应用指南》；如果感染严重，还会用到《抗菌药物临床应用指南》。
- 冠心病的病人，可能要用到至少10个指南。包括《高血压管理指南》、《中国心血管病预防指南》等等。

|指南用规范的流程, 解决水平差异问题。
|指南就是这么重要。它几乎涵盖到了临床上所有的常见病，以及常见病里所有的类型。指南对于每个环节都有清晰的指示。一个医生规范地应用指南，就可以保证病的基本治疗。*按照这个方案做，就可以避免不同操作者的水平差异带来的治疗差异，还能保证效果、降低风险。* +

- 遇到心脏骤停的病人，我们应该立刻心肺复苏，不能等。这个时候，无论是大医院的医生，还是卫生院的护士，只要掌握了这个指南，心肺复苏的操作手法就基本一致。
- 同样是心肺复苏，ICU的医生和急诊科的医生最有经验，因为抢救太多了。

在临床工作中，越是常见病，研究也就越透彻，它的指南就越规范、越厉害。不按指南操作的风险也就越高。

*指南的第一个特点，它是地板，保证了最基本、最规范的治疗。 但是，每个病人又是千差万别的个体，所以指南只是地板，它不是天花板。*

|循证医学
|制定指南用到的科学方法，叫做"循证医学"。循证，也就是让证据说话，把证据转化为最好的临床指导建议。所以，只要有关键的新证据出现，指南就要迭代升级。

- 《心肺复苏指南》，每年都会迭代一次。

|===






142





