
= 话语输出影响力
:toc:

---

== 为什么沟通能力极其重要? -> 否则就无法调动人力资源，让大家协助你实现自己的目标.

要想成为精英，沟通能力和表达能力一定不能少，否则就无法调动人力资源，让大家协助你实现自己的目标。

*演讲是领导力的一部分；其次，在战争中，沟通能力和表达能力非常重要。*

- 西点在录取时，对学生的品行和领导力有相当高的要求。*对于领导力的衡量，主要看高中生们在中学时所担任的社会职务和演讲比赛的结果*。

- 在美国陆军学院（即西点军校), 和安纳波利斯美国海军学院, 每年录取的 1100~1200 名学生中，有 700 多名是参加过辩论比赛的. +
每一年的新生(1200 名)中，大约有 300 名过去是学生会主席, 或者全年级的班长, 另外大约 700 人是演讲队成员，占新生人数的一大半。

---

== 为什么我们只追求"逻辑自洽"? -> 因为很多事情的评判没有"硬标准"

[cols="1,1a"]
|===
|硬标准 |解释框架

|什么叫硬标准？能定量, 定性, 能证实, 能证伪的.
|*解释框架没有标准答案，只要形成逻辑自洽*(公说公有理，婆说婆有理)，有人认同，就可以。 +
解释框架无所谓对错，因为根本无法证伪。
|===

- 文案、创意这东西，确实没有什么说得清的评判标准. 等你职位升上去了，你的标准就是标准。

- 广告的效果, 也无法证伪. 产品销量蹿升, 是谁的功劳？ 广告创意, 媒介投放, 渠道, 产品本身的质量, 这几个因素的功劳贡献比例是多少, 你怎么知道? 因为结论无法证伪 ——客户无法再用几亿重试一次. +
正因为这个“不确定性”，我做广告20多年，越做越糊涂，越做越没自信。我真的做对了吗？别人真的做错了吗？或者说，那只是我们自以为的“对”？  +
广告不是复制先例就能成功的行当。


---


==== 对于没有"硬标准"的东西, 怎么看待/处理? -> 你要提供自己的评判标准

做广告这一行，每天都会经历自我否定，以及被别人否定。我没见过哪个人能经常遇见夸奖和赞美，无论资历深浅。

我们想出100个idea来，就知道有99个生来就要被杀死的，因为最终执行的方案必然只能是1个. 你在想出来它们的那一刻, 就知道它们最终会被杀掉, 坏的好的都可能被杀。事实上，你自己想出来100个idea，会自己先杀掉90个; 剩下的10个，会被你的领导杀死5个; 最后5个再拿去被客户杀。

每个人的观点, 都是不一样的. 千人有千个评判标准. +
顶层策略有"对错", 底层执行有"好坏". *策略的对错问题，要努力探讨清楚。而执行上的好坏的问题则不需要, 因为后者是很"主观"的, 每个人都不同.* 事实上只要"顶层策略"做对了，就已经成功一大半了。

如果不得不在"底层执行"上争执, 那就按两条原则:  +
1.对外, 谁出的钱(是甲方)听谁的。 +
2.对内, 谁级别高(是最终负责人)听谁的；

我的做法是努力在提案之初, 先帮大家设定一个标准, 在开始提案时，先告诉客户，我们是怎么考虑的，我们认为这个名字应该符合哪几个标准. 因为很多人的脑子在这个时候是空白的，他根本不知道听完之后该怎么判断. 你先告诉他有以下三个标准，不管他接不接受，都会记住这三个标准。接下来你再提出自己方案时，他会下意识地用你刚才所说的三个标准来衡量他看到的东西。

*你要以适当的方式展示自己碾轧性的优势，你要让客户知道你确实是个专家，让他知道那些文案不是乱写的。我们必须消弭那些底层的不信任，如果纵容不管，没有碾轧回去，以后会出很大的问题。*


---


== 如何将事情讲得非常清楚?

==== 演讲要点一般不要超过三条 -> 超过三条大家根本记不住

- 很多人演讲时，恨不能把一肚子话一口气倒给听众。其实**大部分人在听报告时，都很难集中注意力超过20 分钟。** +
因此，*再好的演说家都很难把 10 件事一次性讲清楚，能把一件事讲透或者三五个要点提到，目的就达到了。*
+
如果听众真有兴趣，他们以后还会来听的，到那时再把更多的信息传递给他们也不迟。 +
如果听众没有兴趣，即使讲再多的内容，也会成为最后一次演讲。


- 对于任何演讲者，都**不要指望一次演讲能够讲清楚 10 件事，真能把一件事讲清楚，目的就达到了。**

- 把报告做得简短点，重点突出即可。听众能够专心听 5 分钟，记得里面一两个重要的观点，报告的目的就完全达到了。

- 我做报告时，演讲要点一般不会超过三条，超过三条大家根本记不住。


---

==== 你的每段话, 都要有其目的


我代表基金做了一个简短的讲话。一般来讲,参加基金年会的人数并不多，主要是我们现有的投资人、未来潜在的投资人, 以及我们所投资公司的创始人三类。 +
我一共只有 5 张 PPT，每张 PPT 用两分钟时间讲完，大致讲了 5 个方面的内容。

[cols="1,3a"]
|===
|Header 1 |Header 2

|第一张 PPT： +
*我们是谁，过去几年做了什么事情*
|这张 PPT 的**目的既是对过去的一个总结，和对现有的投资人一个交代，也是为了吸引新的投资人给基金投资。** +
在这张 PPT"里，我介绍了几个数据：

1. 我们过去投了多少家公司。
2. 目前所投资公司的估值增长了多少。
3. 有多少公司成功退出了(钱收回来了)。
4. 有多少公司失败了。（这一条一定不要省略，无论是投资人还是办企业的人都是聪明人，任何报喜不报忧的行为只能让他们心存疑虑。 +
很多时候，*先把坏消息告诉大家，然后再说好消息，效果会更好*。如果坏消息不是很坏，说出来反而能起到好的作用。）

这张 PPT 要传递的第二个信息, 就是用一句话概括“我们”的特点，即我们对技术的高度敏感性。很多时候，话说多了反而没有重点，把上面这几点意思表达到位就非常好了。

|第二张 PPT： +
*我们提供什么*
|即使是钱，也分聪明钱和傻钱。*对于创业者，除了钱，我们还提供两方面的帮助。*

1. 第一，提供一种连接。我们首先会为创业公司提供和硅谷企业, 以及硅谷其他投资机构, 的连接服务。其次，对于那些想进入中国市场的公司，我们会提供解决方案。
2. 第二，对创业者提供一种"技术上"和"管理上"的帮助。因为我们的合伙人都是技术专家出身.

|第三张 PPT： +
*我们投资的哲学*
|看重创始人，也就是“投人”。我还展开讲了“投人”的三点重要性：

1. 一流的人可以把二流的项目做成一流；反之，二流的人会把一流的项目做成二流或三流。
2. 世界是瞬息万变的，任何成功的初创企业最终的成功产品，相比当初创始人的想法都会有很大变化。世界需要“变色龙”，只有一流的人才善于往好的方向改变。
3. 人的诚信很重要。

在风险投资领域有一条金科玉律——*投资就是投人。诚信比能力更重要*。 +
在风险投资中，当你把几百万元、几千万元，甚至更多的钱，在没有任何抵押的情况下交给一个不认识的人，让他创业，这个人首先必须让你信得过。创业者如果骗投资人的钱，通常投资人是毫无办法的。

我见过不少创业者，一旦办公司办得不顺，就把公司的技术和产品拿出去再办一个公司，去融新的资金。同时他们会对原来的公司进行破产清盘，这样投资人的钱就不用还了。

国内一个非常有名的早期投资人，或许是被这种没有诚信的创业者坑苦了，在后来给创业者投钱时都要加上一个霸王条款一如果你拿了我的钱把公司办砸了，只要你还打算继续办公司，我给你的投资永远算到你的新公司里。


|第四张 PPT： +
*我们对项目的看法*
|我帮你解决了钱的问题之后，*你只要告诉我，当你实现了自己的想法后，世界会有什么明显的、正面的变化。*

对于那些做所谓“me too”（我也能行）项目的人，这一条就通不过，因为他们即使达成了目标，也只不过使行业中多了一个竞争对手，对世界没有什么帮助。

出于对这个原则的坚守，我们几乎不投资那些炒作概念的公司，那些最终把公司做得很大的人，都是有明确愿景和方向的，不是随大溜去盲从、去热炒概念，也不会挤进过热的市场。 +
前几年那些大量做视频的公司、团购的公司、O2O 的公司，以及现在的大部分自媒体，都不符合我们这个要求。

|第五张 PPT： +
*我们对所谓"趋势"的看法*
|所有 IT 行业的人都习惯于把“趋势”二字挂在嘴边，有些人还在大会小会上到处预测趋势。当然，几年后你回过头来验证他们所说的话，常常是不准确的。

**预测常常是靠不住的，因此，我们在投资时从来不去赌未来的趋势。什么方向的公司可以投资，什么领域里的公司不可以，完全是创业者告诉我们的。**

如果很多人几乎同时看到了类似的问题、有相似的想法，这就是所谓的趋势。这种趋势，不是哪个专家先知先觉的结果，而是自下而上总结出来的。

好的体制要让动力来自底层，刹车掌握在高层手里。对于创新也是如此，动力应该来自底层的每一个创业者，而制动应来自掌握资金和资源的人。因此，*风险投资所做的事情，就是对创业者的想法进行正确的判断。对于趋势，我们从不预测，但是我们会知道趋势所在，因为创业者会告诉我们。*
|===

在战术层面，我的**后四张 PPT 都是在支持第一张 PPT 的内容**，这样**整个 10 分钟的报告就传递出一个统一的信息 -- 我们为什么过去做得不错，以后为什么有信心能够做得更好。**这样既能让现有投资人放心，也要让未来投资人动心。

---

== "说服他人"的方法是什么?

==== 单纯话语说服不了怎么办? -> 用事实证明后, 再来说

仅仅靠好想法本身, 未必能够说服他人，而拿出不可辩驳的事实后，任何人都难以无视事实。

- 当时陆奇还在雅虎，要说服杨致远等人接受他对雅虎产品的新设计，*陆奇私下里做了很多功课，把杨致远等人可能问的所有问题，都事先让手底下的人做了模拟实验*。这样，他便证明了自己的方案比过去的可以给雅虎带来更多的收益。

---

==== 要说服他人 -> 我们需要找同盟军 : 1. 能捍卫我们思想的人, 2. 能理性地帮助我们找到证据的人.

聪明人总是善于借力的。一个人的成功，也要靠他调动资源的能力。我们常常是需要两类同盟军 :

[cols="1,3a"]
|===
|Header 1 |Header 2

|1.像赫胥黎那样捍卫我们思想的人
|像赫胥黎这样的人，他们不完美，甚至看法并不和我们完全一致，却能够坚持不懈地帮我们传播想法。

|2.能理性地帮助我们找到证据的人
|达尔文的进化论, 在很长的时间里内在的逻辑也不是非常严谨，更糟糕的是有许多和新的科学发现相矛盾的地方。所幸的是，有一大批科学家不断地用最新的科学发现修正进化论、解释进化论.
|===

---


== 如何对应你不太熟悉的提问? -> 无法给出精确的数据答案, 就给出"值"的预估范围

- 最有价值含量的沟通, 是在第一时间直接给出答案，然后补充解释。而不要说没有信息量的废话!


|===
|我问 |他回答 | 他的问题点

|我问一位资深律师: “最近在国内，专利从申请到批准的周期是多长？
|“我们主要负责专利的书写和申请，审批的速度不很清楚，这要看情况，有的很快就批准了，有的要修改补充材料，个别的拖了很长时间。”
|**这个回答的问题在哪里呢？它是没有信息量的废话！我当然知道**专利律师是书写和申请专利的，不是专利局的审批人员；也知道不同专利被批准的时间不一样长。

|“大约有多少比例的专利能在两年内被批准？平均是多长时间？最长的是多长时间，那些情况是否是个案？”
|“不知道，我只负责一部分专利的申请，这些数据可能要找专利局的人去了解。”
|我当然知道专利局会有统计数据. 但是作为一个在行业里工作多年的律师，对这种基本数据是应该了解的。

|“不用管专利局那边的数据，就你的公司过去的经验，哪怕是那些你负责的案子，总体情况是怎样的呢？”这位律师颇有歉意地对我讲：“哎呀，我还真没统计过。”
|
|如果你是一个老板，也未必会提拔这样的人当领导，负责起一个部门。

|===

- *事实上我问这个问题时并不关心准确的细节，只想了解一个大致范围而已。他可以直接回答一个动态范围.*

- 我曾经问过爱奇艺创始人龚宇一个类似的问题，让他就某一位网红的一期视频节目的收入做一个估算，*虽然这里面有好多变数我们不知道，他也没有见过那位网红，但是他能马上告诉我一个比较准确的范围*，这样大家就能知道一件事情是不是值得在爱奇艺或者类似的网站上做。这就是管理者和被管理者在掌握大局上的区别。

- 如果这位工程师无法给出整体的回答，他至少也应该给出自己所说的每一种具体情况下的具体答案，而不是讲了一堆废话。

---
















