
= 问题_(你是创始人)_你如何管理员工与定位自己
:toc:

---

== 你是创始人, 你招人主要考量他的什么?

==== 价值观方面

- 围绕你对你公司赋予的价值观要求, 去招聘最合适的人(应聘者必须能认同你公司的价值观).

---

==== 能力方面

- 你录用的人, 应该高出现有员工的平均水平，否则你公司越大(人员越多)，人员的平均素质就会越被拉低。

---

==== 薪水方面

- 你是高盛老板, 你之所以给员工那么多的奖金，既不更多，也不更少，这是由市场决定的。如果你高盛中每个人(员工)出去创业都能成功，高盛就会自动地将分成比例提高。这反过来说明了外面创业的失败率.

---

== 导致创业失败的因素有哪些?


==== 你在自己不懂的事情上创业


- *很多媒体常常颠倒因果关系。* 盖茨、佩奇、布林和扎克伯格退学创业能够成功，是因为他们找到了挣钱的方法，然后才退学; 而不是反过来，因为退学，所以创业成功。

- 不要做自己不懂的事情. 巴菲特不投科技公司，因为他说他看不懂。但在一个科技公司能够长期稳定盈利后，他就能看懂它们的商业模式了。巴菲特旗下的 Berkshire Hathaway Corporation, 投资的公司数量并不多，因为他没有精力搞懂那么多家公司。

- 公司每年从投入几十亿元做广告。这让广告公司挣得盆满鉢满。那与其让广告公司挣钱，为什么不如自己成立一家或者收购一家广告公司? -- 如果这个逻辑成立的话，那今天世界上最大的广告公司应该是可口可乐广告公司, 或者宝洁广告公司，但是结果却不是，这里面必然有它的原因。



---


==== 你既没有从精神上, 也没有从物质上, 做好准备

没有钱是万万不能的. 现实往往是，"置之死地"后大部分情况是死掉了。

---

==== 为什么你在原组织的光环, 会很快消失? -> 你带不走原组织的"隐性资源"

你过去在开展业务时，使用了大量的原来组织的隐含资源(包括原组织的信誉).

- 投资人把钱放在高盛. 市场差时, 投资人鉴于高盛大机构的品质和信誉, 不会撤资. 但你自己干时(作为基金管理者),  投资人就会撤资.
- 这些被采访的大公司, 其实对是否有必要接受采访是很清楚的，它们看重的其实是媒体人后面的那块牌子(比如是央视)(权威媒体的影响力)，而不是媒体人自己个人的知名度。

- 缪贤犯了错误，想逃到燕国去，蔺相如说：“不可，*当初燕王对你好，因为你是赵国的宠臣，对方其实是冲着赵国来的，并非冲着你，今天你落魄了跑去投奔，一文不值(就对他没有利用价值了)*."

缪贤思维的误区在于，他搞错了燕王对他好的原因。大公司的光环无疑会给公司里的一些人很多方便，他们更容易建立起广泛的人脉，但是他们需要分清楚, 对方的善意是冲着自己来的，还是冲着你背后的公司来的。

---

==== 如何跳脱出"个人创造力的有限性" 问题 ? -> 打造出能不断引进新人的平台

只卖个人的能力(而不创造出平台, 来盈利的话), 始终是有尽头的.

成功创业了的媒体人的共性, 他们其实都不是在做个人自媒体，而是用自己的经验和影响力打造了一个新的平台，(比如罗振宇、马东，以及虎嗅、嘉宾传媒的几个创业者都是如此)。*打造平台，就不会有吃光个人老本的担心，因为平台可以引进新人。*

打造平台, 要做两点内容:

1. 培养一批新人，通过这些新人将自己的专业特长放大。 +
为什么只能拉拢新人? 因为你很难拉拢已成名的专业的媒体人，成名的人不会去替他人做嫁衣裳，因此很少看到一个资深媒体人到另一个同行创办的平台上去发展。因此，去平台的都是新人。
2. 将其他行业的人(教育界, 企业家界等等), 塑造成媒体上的明星。(想想德云社, 造星平台)





---

== 你是ceo, 你如何定位自己?

==== 你想度过什么样的人生历史? -> 我为什么来? 我想在这得到什么? 我只呆多久? 我何时离开? 去往哪?

- 任何想进阶的人都, 不应该被动地工作，就像算盘珠子，拨一拨，动一动。想成为领导者，要平实地学习做一个领导，走出自己的一亩三分地.

- 钱是靠挣出来的，不是靠省出来的. *一个人很难用5元钱办成10元钱的事情*，有工夫费这个省钱的心思，不如多花点工夫去挣到10元钱。

- 要想多挣钱，就**要讲究挣钱的效率**(利用"杠杆效应")，而通过延长工作时间挣钱，这种方法显然不可取. 个人就算工作两倍的时间，最多多挣一倍的钱；而挣大钱的人，单位时间挣钱的效率可以比普通人高出三五倍、几十倍，甚至更多。

- 哈佛商学院无论哪门课，它都贯彻“用别人的钱挣钱”这个宗旨。老师们总是讲，你自己的钱是留给你安身立命的，你如果想做事情，那么就让别人来掏钱。当然，*为了做到这一点，你需要会销售，会把你的产品、你的想法卖给别人，让别人乐意掏钱。如果做不到这一点，那么学也是白上了。*

- 相反，很多缺乏真才实学的梦想家，为了自己创业，一方面花光工薪阶层父母的积蓄，另一方面让妻子省吃俭用，化妆品、衣服都舍不得买，孩子暑期也不能出去玩儿，这种人最好不要创业。 +
*今天不是一个缺钱的时代，如果不能让别人投资，要么是项目不好，要么是不会销售，无论是哪一种，可以想象将来成功的可能性较小*。 +
+
为什么从陌生人那里拿钱要比从父母那里拿钱重要呢？原因很简单: *从父母那里拿钱, 是在占亲情的便宜，如果一个人习惯于占这种便宜，不仅他的谋生本领和奋斗精神要差很多*，而且见识也很难超出上一代人。 +
*人在社会上打拼也好，混事也罢，父母不可能照顾他们一辈子，亲朋好友也不可能总是帮忙；从陌生人那里拿钱也好，“骗钱”也罢，是自己立足于社会必要的历练过程。哈佛教大家“骗钱”，其实是从一开始就让大家习惯于这种历练。*

- *我们在任何时候都应该想一想，当我们离开时, 我要给自己带走什么, 及, 我要给这个团队留下什么。*


---

==== 如何避免"一锤在手，满眼都是钉"? -> 有多元化的思维模式

- 工程师们的问题在于：一锤在手，满眼都是钉。今天，有点儿工程经验又懂一点统计的软件工程师，常常把什么事情都看成是大数据的问题.

---

==== 身为管理者的你, 为什么一定要了解底层的业务细节? -> 如果你不了解, 你怎么知道你手下的人告诉你的是真的呢？

一个有效的管理者，如果做到了第5级(基层员工是第1级)，他需要了解第3级的工作；做到了第6级，就需要了解第4级的工作。

---



























