
= 人性, 心理规律, 心理学, 心理情绪的复盘
:sectnums:
:toc:

---

== *人性*

==== 一人难称百人心

人上一百，形形色色shai。 人上一万，无边无沿

---

==== 善操理者-不能有全功，善处身者-不能无过失。

善操理者-不能有全功，善处身者-不能无过失。

善于处理事理, 尚且不能完全成功，   +
善于修身的人, 尚且不能没有过失。

---

====  有不虞之誉，有求全之毁.

有不虞之誉，有求全之毁.

- 虞：预料。
- 有意料不到的赞誉，也有过分苛求的诋毁。所以毁誉不必太在意。

---

==== 圣人（君子）论迹不论心，论心世上无圣人

圣人（君子）论迹不论心，论心世上无圣人

出自：  +
百善孝为先，论心不论迹，论迹贫家无孝子；   +
万恶淫为首，论迹不论心，论心终古少完人。

一切善事里，孝敬父母榜首，但这个主要看心，不是看表面行为，不是说锦衣玉食给父母就是孝顺，假如这样的话，那么清贫的人家就没有孝子了。

一切的恶事里，以好色为榜首，但这个主要看行为，不是看心，假如按心念论，世人都免不了面对美色动心，这样的话，世上就没有一个完美无缺的人了。

---

== ----- -----

---

== *心理规律*

==== 人的可塑性极强，你现在使用大脑的方式只是一种习惯。（李中莹）

---

==== ★ 无论你知不知道了坏消息，它都存在那儿，所以你的心情应该都是一样的才对。刘备正是看穿了这一点，所以就“喜怒不形于色”。

被人辱骂而产生不良心情，这种心情只是一种幻觉而已。因为如果你第二天就收到一个坏消息，你前面日子的好心情就只是幻觉， 这个好心情只不过是你在还没有收到坏消息前，所处于的“未知状态”罢了。 但坏消息已经存在在那儿了。换言之， 无论你知不知道了坏消息，它都存在那儿，所以你的心情应该都是一样的才对。

刘备正是看穿了这一点，所以就“喜怒不形于色”。 即，无论知道了喜（好消息）还是怒（坏消息），该消息早已经存在着了，所以的确也没什么好高兴，或好生气的。

---

==== 社交就像吃饭、睡觉一样重要自然。不要对它抱着过高的期待和目标，把它放低一点，让它成为你生命中一件自然而然的事情，把它跟你的形象、评价、标准松绑。

2021 年的一项研究，提出了社交中最常见的三种恐惧。分别是哪三种呢？

[cols="1a,3a"]
|===
|Header 1 |Header 2

|1.对不确定性的恐惧。
|许多人会有一种根深蒂固的信念，认为跟陌生人谈话或交流是一件不确定的事情，是具备高风险的，很容易产生尴尬、拘谨、不愉快，从而导致不欢而散。

|2.对对方感受的恐惧。
|人们容易认为别人不喜欢自己，也就是前面讲过的：会努力从整个交流过程中去找“自己的不足”，再把这个不足无限放大。

但事实上，对方也是选手，也在期待着你的打分。


|3.对交流技巧的恐惧。
|许多人对自我有一个认知：他们认为自己是缺乏足够的社交技巧的，既不知道如何跟陌生人交谈，也不知道如何开始谈话和结束谈话，因此容易缺乏自信。
|===

换言之，几乎所有人在社交之中，都存在一个现象，就是高估了社交的难度，低估了自己的社交能力。

*实际上，对于内向、敏感、社恐的人，最缺乏的能力是什么？不是分析和思考的能力，而是不去分析和思考、“头脑一热”的能力。*

*很多时候阻碍我们去社交，去正常地、自然地跟别人交流的是什么呢？是实实在在存在的障碍吗？不是的，是我们脑海中所描绘出来的、虚假的恐惧和焦虑。*

要破除这种负面循环，让自己迈出一步，再迈出一步 —— 用一个正向的、良性的循环，去替代掉它。

*社交就像吃饭、睡觉一样重要，同样，也应该像吃饭、睡觉一样自然。 +
不要对它抱着过高的期待和目标，把它放低一点，让它成为你生命中一件自然而然的事情，把它跟你的形象、评价、标准松绑。*

什么是一席之交呢？ 举个例子：你参加一个活动，认识一个陌生人，刚好有共同话题，于是聊了一会，度过了一段舒服的时光，临别了各自致意，也不用保留联系方式，随缘看下次能不能碰到 —— 这就是一席之交。 +
简而言之，就是毫无压力，“用完即走”的陌生人社交，不用担心会对自己造成任何维系的成本和心理压力。

这种一席之交至少会有三种方面的作用：

1. 提高心理上的安全感，因为对方不太可能跟你产生交集，因此你可以不用太拘谨；
2. 开阔眼界，在交流中带来新信息的刺激；
3. 获得各种可能性和机会，打开对某个领域、某个行业、某种兴趣和生活方式的视野。


---


==== 在所有的社交沟通之后，人们估算的对方对自己的喜欢程度，平均会比实际的喜欢程度低10%。

Liking gap 指的就是：“我认为别人喜欢我的程度” 和 “别人实际喜欢我的程度” 之间的差距。

一项 2018 年的研究发现：人们总是会低估别人对自己的喜欢程度。在所有的社交沟通之后，人们估算的对方对自己的喜欢程度，平均会比实际的喜欢程度低10%。 (Boothby et al., 2018)

---


==== 事实上, “被误解”才是世间常态，“你懂我”的几率则像中彩。


在人际互动中，我们常常会产生“被洞悉错觉（Transparency illusion）”，误以为自己的表情、肢体、语言、眼神已经传达了自己真实的意思（并没有），甚至误以为即使一言不发别人也该“了解自己的想法”（怎可能）。但事实上, “被误解”才是世间常态，“你懂我”的几率则像中彩。

被误解的原因：
1. 醒醒吧，**你的表达能力并没有你想象的那么好，银屏上的演员经过多年严苛训练，方能通过一颦一笑让我们感同身受。**
作为不能自如控制脸部表情肌的普通人，你的“冷酷脸”可能看起来更像“生气”，“关心脸”可能更像“烦躁”，“友善脸”可能更像“软弱”……

2. 你那些不假思索脱口而出的话，也可能未必能精确表达出你心底真正想表达的想法.

你真的指望别人通过你那蒙娜丽莎般的脸、含混不清的话、手舞足蹈的动作，看透你的内心深处的喜好和善意吗？

---

==== 女孩儿起身道：“他来了。我该走了。”“别这时候走啊！他已经看到你了，你这时候走，就跟咱们有什么事儿似的。哪怕打个招呼呢！” (不要给人以错觉,  误解)

女孩儿起身道：“他来了。我该走了。”“别这时候走啊！**他已经看到你了，你这时候走，就跟咱们有什么事儿似的。哪怕打个招呼呢！**” (不要给人以错觉,  误解)

---


== 关系的进阶

==== 清晰地表达需要, 能带来双方关系的正向循环, 走向下一个阶段.

2017 年发表在《人格与社会心理学公报》上的一项研究：撒娇女人可能真的会更容易好命。这里的“撒娇”指的是“在关系中，直接、清晰地提出需要”.

亲密关系中, 一个人表达需要的方式，能直接影响着两个人接下来互动的走向（Cutrona, 1995 )：

- **清晰地表达需要, 能带来正向循环 : 清晰提出需求, 能促进伴侣给予相应的情感、信息等支持, 师你们走向下一个新的关系阶段。** 当然, 对方可能不满足你, 就会让你产生"防御机制".
- *但不让对方猜你的心理, 只会带来负面循环 : 对方猜不准，你很失望. 对方对你的不清晰表达也会失望.*

---




