
= 先建立起"信任"后, 才会有"情感"
:toc:
:sectnums:

---


== ----- -----

---

== *情感是流动的*

==== 吵架这件事本身并不严重，严重的是一方失去了申诉、辩论和判决的权利。两人的关系本是平等的，现在却有了高低。

吵架这件事本身并不严重，严重的是一方失去了申诉、辩论和判决的权利。两人的关系本是平等的，现在却有了高低。

夫妻之间应该建立一种就矛盾冲突进行讨论的机制（平等地位、就事论事, 相同权利）。如果双方用吵架去做这件事，很快地，焦点就不是本来要讨论的事情，而是“对方的态度如何不对”的问题了（**用错误的手段方法去解决问题，导致一波未平，一波又起。 手段上又产生了问题**）。

---

我并不是想跟你争个你高我低，你说咱们俩之间争这个有什么意思？夫妻之间，在人面前，还是自自然然平平和和的为好。夫妻俩非得在外人面前争个你高我低，或者展览不和，或者表演亲热，都只能让人觉着俗气。

---

==== 人与人的关系不是变热就是变冷，没有保持不变的中间的关系。

关系就如逆水行舟，如果没有得到改善、维持和发展，就会随着时间而衰退。**人与人的关系不是变热就是变冷，没有保持不变的中间的关系。**

---

==== 感情是流动的，因而必须要有不流动的合同来规范我们的行为。


---


==== ★ #人的价值，在遭受诱惑的一瞬间被显现。#

---

==== ★ 称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。

权，然后知轻重；度，然后知长短。物皆然，心为甚。::
-> 权：本指秤锤，这里用作动词，指称物。 +
-> **称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。**

- 其实我并没有傻到每次约会都带女儿，我只是想试一下，他对我女儿的态度。
- 人的价值，在遭受诱惑的一瞬间被显现。

---

==== 人不知亲-穷知亲, 心不知近-苦知近

人不知亲-穷知亲, 心不知近-苦知近

平时你不知道谁对你好，直到你遇到困难的时候；平时你不知道谁跟你亲，直到你穷困潦倒的时候.  +
指人在穷苦的时候，才能知道谁和自己最亲近。


---

==== 相形不如论心，论心不如择术

相形/不如论心，论心/不如择术

观察人的相貌, 不如考察他的思想; 考察他的思想, 不如鉴别他立身处世的方法。

---

== ----- -----

---

== *人在当时环境下的的情感抉择, 决定其人生历史走向*

---

==== 人性管理更具有稳定性。而不像技术那样迭代极快，积累的经验很快就会过时无用。

作为历史长河中的一条连贯到未来的线，技术是永远在发展的，这决定了你有限的生命，不可能解决所有的技术问题。所以你只能占据这条无限的发展线上的一段时间，掌握住一段技术前沿，然后把技术交接给后来人。(任何一个奥运冠军退役,  但体育技术却不会停下脚步.)

你去哪呢？ 管理岗位。因为人性是自古不变的，更具有稳定性。历史书中的人性故事，对现在也是有启迪的。所积累的管人经验能用到老。而不像技术那样迭代极快，积累的经验很快就会过时无用。


---

==== 历史大事件不重要，每一个历史人物在大事件中发生的他们命运角度的改变，从原来的命运方向发生了锐角转折，转折点，才是你应该从中感悟到的重点。

历史是什么？每一个历史事件就是角度的转变，让人的命运直线的方向，产生角度上的偏转转变。**人生转折点，就是一个个锐角，就好像三棱镜让光线发生了偏折一样，设向了不同角度的方向。**

所以你在看史书时，**历史大事件不重要，每一个历史人物在大事件中发生的他们命运角度的改变，从原来的命运方向发生了锐角转折，转折点，才是你应该从中感悟到的重点。** 这才是正确的看史书的方式。

因为**脱离了人物命运的历史事件，是无用的信息**，是字典式的信息。和读者没有任何价值联系。**而只有从历史人物的命运转折中得到的启发，才是对你唯一真正有联系，有价值的营养内容。**

所以，这就是你读历史与官场小说时，正确的方法，与要得到的东西.

---

看历史，别记事，要看人。因为事在人为。人的个性和性格, 决定所有的历史事实走向。

---
