= 0659
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 659: Finding Love on Valentine’s Day.
This is English as a Second Language Podcast episode 659. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
You know our website is eslpod.com, but did you that know it’s www.eslpod.com, huh? I bet you didn’t!
This episode is called “Finding Love on Valentine’s Day.” It’s a dialogue between Tony and Chelsea about finding love on Valentine’s Day. Let’s get started.
[start of dialogue]
Tony: Another Valentine’s Day! I really hate Valentine’s Day.
Chelsea: What’s your problem?
Tony: I’m sick of seeing heart-shaped boxes, stuffed animals, and cupid decorations everywhere. Lovey-dovey couples on the street and nothing but sentimental movies on TV – that’s what I have a problem with.
Chelsea: You’re just jaded because you don’t have a valentine on Valentine’s Day.
Tony: Do you blame me? This is the third year I’m spending Valentine’s Day alone. That’s enough to make any man feel jaded.
Chelsea: There are plenty of women you could go out with. Just open your eyes and look around.
Tony: All of the women I know are either psycho or attached. I’ve given up on dating.
Chelsea: How will you find a Miss Right with an attitude like that?
Tony: I’ve told you. I’ve given up.
Chelsea: Well, I think you should open your eyes. Your valentine may be right under your nose!
[end of dialogue]
Tony is friends with Chelsea, and Tony has a problem. He says, “Another Valentine’s Day!” Valentine’s Day, also known as Saint Valentine’s Day, is traditionally a day that celebrates love and affection, especially romantic love. Tony says, “I really hate Valentine’s Day.” Chelsea says, “What’s your problem?” meaning what’s wrong, why are you so strange. Depending on the intonation, the way you pronounce that phrase, it could be considered a criticism. If somebody says, “What’s your problem man?” they’re indicating that you are acting strange or unusual, and perhaps you should be careful that you could get hurt. But here, Chelsea is just saying what’s the matter, what is the situation, why do you hate Valentine’s Day.
Tony says, “I’m sick of seeing heart-shaped boxes.” “To be sick of (something)” means that you are tired of it; you no longer want to, in this case, see heart-shaped boxes, stuffed animals, and cupid decorations everywhere. “Heart-shaped” means made in the shape or the form of a heart; of course, that symbolizes love traditionally. “Stuffed animals” are small – usually small, they can be big – toys that are in the shape of an animal, and they’re very soft. They’re often given to young children, however some men give them to their girlfriends or wives as a romantic gesture. “Cupid decorations” refers to the Roman god Cupid, who was the son of Venus and Mars. In Latin, the word “cupido” means desire, as in sexual, romantic desire. That’s what’s the idea behind the cupid decorations. Traditionally, Cupid is shown in art as a small boy who has a bow and arrows. An “arrow” is a long, thin piece of wood that is sharp at one end, and you use the “bow” to shoot the arrows into the hearts of poor humans, who then fall in love. There was a great song by I think it was Sam Cooke: “Cupid pull back your bow and let your arrow go straight to my lover’s heart for me.” It’s better when Sam sings it!
On Valentine’s Day you will often see “decorations,” things that people put up to make somewhere look different. For example, at Christmas you put up a tree and you may put up lights around your house. These would be Christmas decorations. Tony doesn’t like any of this; he says he doesn’t like seeing lovey-dovey couples on the street and nothing but sentimental movies on TV. “Lovey-dovey” is sort of an informal way of saying two people who love each other very much and often show that love in public. They’re kissing each other and they’re holding hands and they’re hugging each other. You know, the sort of things that girls usually love and guys don’t. Well, that’s a lovey-dovey couple, and Tony says he has a problem with that; he doesn’t like that. He also doesn’t like sentimental movies. Something that is “sentimental” has a lot of emotions, a lot of feelings. Usually it’s used somewhat as a criticism; you’re saying it’s too emotional, there’s too much obvious emotion or feelings expressed in the movie or the song, whatever it happens to be.
You may wonder why Tony hates Valentine’s Day so much, and Chelsea tells us in the next sentence. She says, “You’re just jaded because you don’t have a valentine on Valentine’s Day.” “To be jaded” (jaded) means that you are no longer excited by or interested in something that seems to interest everyone else. Usually this is because you have had a lot of exposure – you have a lot of experience with that thing. This is perhaps not quite the case for Tony, even though Chelsea says he’s jaded. I’m not sure if that is exactly his situation, but in any case, he certainly is upset or unhappy because he doesn’t have a valentine on Valentine’s Day. A “valentine” (with a small “v”) is used as a noun to mean a romantic partner, someone you are involved with: your boyfriend or girlfriend, your husband or wife. Those would be your valentines. Well, you should only really have one valentine, at least one at a time!
Tony says, “Do you blame me?” meaning are you saying that it is my fault, do think that I am the one who is responsible for this situation. “To blame” (blame) someone is to say that they did something wrong. We use this expression to show that we feel that we are rational, logical, that we are justified in saying the things we are saying. Tony says, “This is the third year I’m spending Valentine’s Day alone. That’s enough to make any man feel jaded.” Again, we often use this word when you have too much exposure to a situation; Tony seems to have not very much exposure. But it can sometimes be used just to mean bored or uninterested in something. Tony is unhappy because he doesn’t have a valentine, and has not had one for three years.
Chelsea says, “There are plenty of women you could go out with.” “To go out with,” in this case, means to date, to have a romantic relationship with, to make your boyfriend or girlfriend. “Just open your eyes and look around,” she says. Now Tony – you have to understand not too smart, okay – doesn’t really understand what Chelsea’s saying to him. Chelsea says, “Just open your eyes and look around.”
Tony says, “All of the women I know are either psycho or attached.” “Psycho” is an informal word meaning crazy, someone with a lot of mental or intellectual problems, someone who doesn’t act rationally. If you are “attached” in this case it means that you have a strong connection with someone else. Really, it means that these women already have boyfriends; those are the only women he knows. He says, “I’ve given up on dating.” I should mention that “attached” has some other meanings as well, and those are in our wonderful Learning Guide. So, Tony says he has given up on dating. “To give up” is a two-word phrasal verb, which means in this case to stop doing something usually because you have not been very successful; you have failed many times. “I’m going to give up cooking, because I’m not very good at it.” True story!
Chelsea says, “How will you find a Miss Right with an attitude like that?” This is kind of a play on words; that is, Chelsea is sort of using a traditional expression, “Mr. Right,” and using the feminine – the female “Miss.” Normally we talk about a woman meeting “Mr. Right,” meaning the perfect husband, the perfect man to be her husband. Chelsea says that Tony can meet Miss Right, the perfect woman. Again, that’s not the normal use of it, but she’s sort of playing with that. She says, “How will you find a Miss Right with an attitude like that (with the way that you are acting)?” Tony says, “I’ve told you. I’ve given up.” Chelsea says, “Well, I think you should open your eyes. Your valentine may be right under your nose!” Something that is “right under your nose” means that it is easily available. It is, in fact, very close to you, but you don’t see it, you don’t notice it, and obviously Tony doesn’t realize that Chelsea is not just his friend, Chelsea perhaps wants to be his valentine and Tony is just too much of a man to understand reality. Isn’t that true ladies?
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Tony: Another Valentine’s Day! I really hate Valentine’s Day.
Chelsea: What’s your problem?
Tony: I’m sick of seeing heart-shaped boxes, stuffed animals, and cupid decorations everywhere. Lovey-dovey couples on the street and nothing but sentimental movies on TV – that’s what I have a problem with.
Chelsea: You’re just jaded because you don’t have a valentine on Valentine’s Day.
Tony: Do you blame me? This is the third year I’m spending Valentine’s Day alone. That’s enough to make any man feel jaded.
Chelsea: There are plenty of women you could go out with. Just open your eyes and look around.
Tony: All of the women I know are either psycho or attached. I’ve given up on dating.
Chelsea: How will you find Miss Right with an attitude like that?
Tony: I’ve told you. I’ve given up.
Chelsea: Well, I think you should open your eyes. Your valentine may be right under your nose!
[end of dialogue]
If you’ve given up on learning English, you need to listen to the wonderful scripts written by our scriptwriter Dr. Lucy Tse, who is not psycho, although she may be attached.
I’m Jeff McQuillan. From Los Angeles, California, I am Jeff McQuillan. Did I say that already? Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
Valentine’s Day – a holiday on February 14th that celebrates love and affection, especially romantic love
* Don’t forget to buy flowers and chocolates for your wife on Valentine’s Day!
What’s your problem? – What’s wrong?; a phrase used to ask someone why their behavior is so strange or unusual
* What’s your problem? Why are you staring at me like that?
heart-shaped – in the shape of a heart, used to symbolize love
* Where can I buy those little heart-shaped candies?
stuffed animal – a soft toy in the shape of an animal, covered in fabric filled with something very soft, often given to young children
* When Erica was a young child, she carried her favorite stuffed animal everywhere she went.
cupid – the god of love and desire; a cartoon character of a small boy with wings who shoots arrows at people to make them fall in love
* Her boyfriend gave her a card with pictures of flying cupids on it.
lovey-dovey – showing a lot of love and affection for another person, usually in public where other people can see
* Many teenagers are uncomfortable seeing lovey-dovey movies with their parents.
couple – pair; two people, especially when involved in a romantic relationship with each other
* They invited three couples to their home for a dinner party.
sentimental – with a lot of emotion and feelings, often too much
* Seeing old photographs makes Jenna sentimental about her childhood.
jaded – no longer excited by or interested in something that interests other people, often because one has had too much exposure to it or involvement in it
* After 20 years of business travel, Eva has become jaded about flying in an airplane.
valentine – a romantic partner on Valentine’s Day; a person one is involved with romantically on Valentine’s Day
* Who was your valentine last year?
Do you blame me? – a phrase used when one feels that one’s words or actions are justified and rational and expects other people to agree
* - It wasn’t very nice of you to lie to your parents.
* - Do you blame me? If I told them the truth, they never would have let me out of the house again!
to go out with (someone) – to date someone to create or maintain a romantic relationship
* What do you think Bennett would say if I asked him to go out with me?
psycho – crazy; with a lot of mental or intellectual problems; acting in irrational, unpredictable ways
* Dei went psycho after the death of his twin brother.
attached – with a strong dependence on another person; with a very strong connection to another person; with a strong need to be with someone
* Even though Tomas is almost 50 years old, he’s still really attached to his mother.
to give up – to stop doing or using something, usually because one has been unsuccessful
* This science assignment is too hard. I give up!
Miss Right – the hypothetical woman one has been searching for in order to have a romantic relationship; the imaginary woman who meets all of one’s needs and who one wants to spend the rest of one’s life with
* Do you think I’ll ever find Miss Right, or should I settle for someone else?
right under (one’s) nose – a phrase used to show that the thing someone is looking for is readily available and very nearby, but that person doesn’t notice
* I looked all over the house for my keys, but they were in my pocket, right under my nose the whole time!
Comprehension Questions
1. Which of these would be most interesting to a child?
a) Heart-shaped boxes.
b) Stuffed animals.
c) Cupid decorations.
2. According to Tony, what’s wrong with the movies on TV?
a) They’re too long.
b) They’re too emotional.
c) They’re too old.
Answers at bottom.
What Else Does It Mean?
sentimental
The word “sentimental,” in this podcast, means with a lot of emotion and feelings: “Slow jazz songs make me feel really sentimental.” The phrase “sentimental reasons” can refer to things one does because of one’s emotions, especially when the action isn’t very rational: “Midas keeps old ticket stubs for sentimental reasons.” The phrase “sentimental value” refers to the way people keep things that are financially worthless, but carry important memories or feelings: “Please be careful with that vase. It has a lot of sentimental value because my grandmother gave it to me before she died.” The word “sentiment” refers to one’s opinion about something: “Political sentiments change over time.” Finally, the phrase “My sentiments exactly” is used when one fully agrees with what another person has said”: “When Tyrone finished his excellent speech, I thought, ‘My sentiments exactly!’”
attached
In this podcast, the word “attached” means with a strong dependence on another person or with a strong need to be with someone: “Why are you so attached to your pets?” The word “attached” also means to be connected to another object: “Are you sure the check was attached to the bill?” Or, “Please fill out the attached form and mail it back to us by the 15th.” The same word can be used when sending files via email: “Please review the attached report and send me your feedback.” Finally, the phrase “to attach a condition” means to agree to do something only if something else happens: “I’ll sign the rental agreement if I can attach one condition: you have to clean the carpets professionally before we move in.”
Culture Note
Normally, Valentine’s Day is a romantic holiday celebrated by adults involved in a romantic relationship. Nevertheless, many American children celebrate the holiday, especially at school.
Young “elementary school” (usually first through sixth grade, or 6-11 years old) students are encouraged to exchange Valentine’s Day cards. These are small cards, usually pink or red, that are often decorated with cartoon characters. They have small printed message, like “I think you’re great,” or “Will you be my valentine?” Sometimes the students make small “valentine mailboxes” with their name, and these are put somewhere in the classroom. Children are expected to give Valentine’s Day cards to all the other children in their class – not just to their best friends.
Children also enjoy eating sweet foods on Valentine’s Day. They often eat “cupcakes” (small, individual cakes, like muffins) with white, pink, or red “frosting” (a thick, sweet paste put on top of cakes for decoration) and “sprinkles” (very small pieces of colored, sugared candy put on top of frosting for decoration). They also eat a lot of small “candy hearts” (very hard, sweet candies in the shape of hearts) in “pastel” (pale, not bright) colors with tiny messages printed on them, like “I love you” and “Be mine.”
Sometimes children make valentines for their parents or other “caregivers” (the person who is primarily responsible for taking care of a child). They usually cut a heart shape out of “construction paper” (thick paper sold in many different colors for children’s’ art projects) and then use “markers” (thick, colored pens) and glue to decorate them and put loving messages on them.
Comprehension Answers
1 - b
2 - b