= 0666
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 666: Traveling to Less Popular Sites.
This is English as a Second Language Podcast episode 666. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, an 8- to 10-page PDF file that will improve your English – and bring happiness to everyone around you!
This episode is a dialogue between Vanessa and Justin. It’s a travel episode that will be using vocabulary related to going to places that are not very popular for vacations. Let’s get started.
[start of dialogue]
Vanessa: Put away that guidebook. I want our vacation to be exciting and unique, not cookie cutter. Tourists all visit the same sites. I want to explore and go to some places off the beaten path.
Justin: That would be fine except we’ve never traveled to Podville before and we don’t speak the language. How are we going to make our way around if we don’t plan out our trip?
Vanessa: We’ll be fine. Stop worrying. We spend too much time planning. Let’s just fly by the seat of our pants.
Justin: You really want to just go unprepared? That’s just not sensible. Anything could happen.
Vanessa: I’m not going to lose sleep over it. We just need to meet some locals and they’ll be able to tell us about the hidden, secluded, and offbeat sites. Those are the ones I want to see.
Justin: You can explore all you like, but I’m bringing some insurance.
Vanessa: What insurance?
Justin: I’m bringing two guidebooks and this phone number.
Vanessa: Phone number for what?
Justin: The phone number for the American embassy. That’s where I plan to go for help when you get lost off the beaten path!
[end of dialogue]
Vanessa begins our dialogue by saying to Justin, “Put away that guidebook.” “Put away” means stop using it, put it down, put it back into your bag. A “guidebook” (one word) is a small book that describes interesting things to do and places to visit when you are traveling. So you might buy a guidebook to Los Angeles; it would have hotels and restaurants, places where you can visit. It’s often very useful to have a book like this when you are traveling to tell you what you should see and where you should go. Vanessa says, “I want our vacation to be exciting and unique,” meaning different, unlike anything else, “not,” she says, “cookie cutter.” “Cookie (cookie) cutter (cutter)” is when everything is the same, when it isn’t original, when it is a copy of something else. Literally, a cookie cutter is a small piece of plastic or metal in a certain shape, and when you are small sweets for dessert called “cookies” you often make them in a certain shape, and to make sure that they all look the same, for example at Christmas time you might have a cookie cutter that looks like Santa Claus, you use the cookie cutter to make sure all the cookies look exactly the same. But we use it more generally as a term meaning unoriginal, just like everything or everyone else.
Vanessa, who’s very hard to please I think – very hard to make happy, maybe Justin should be looking for someone else at this point! Vanessa says, “Tourists all visit the same sites.” A “site” (site) is a place or a location that is visited, especially by a “tourist,” someone vacationing in a certain area. Notice it’s pronounced the same as “sight” (sight), which refers to your ability to see. Vanessa says, “I want to explore,” meaning I want to experience an area not by reading it in a book, but by going out and walking around, discovering on my own what is there. She says she wants to go to some places off the beaten path. This expression, “to be off the beaten (beaten) path (path),” is to go somewhere that is unusual or uncommon, somewhere that is not popular. A “path” is the same as a trail; it’s a place where you walk. A “beaten path” would be one where a lot of people have gone before you. So if you go up into, say, the mountains, you may see a path where other people have walked before you. “Unbeaten path” would be a path where people have not gone before you and therefore it is not common, not usual. That’s what Vanessa wants; she wants excitement – just like all women, don’t you think?
Justin says, “That would be fine (that would be okay) except we’ve never traveled to Podville before (Podville is not a real place) and we don’t speak the language (we don’t speak the language they speak in Podville). How are we going to make our way around if we don’t plan out our trip?” “To make your way around” means to be able to go somewhere that you are not familiar with perhaps, but not get lost, to be able to find out where you have to go in an unfamiliar place. “To plan out” is a two-word phrasal verb meaning to have a plan for what you are going to do; have an idea about where you’re going to go first, what time you’re going to go, and so forth. You have the details of what you are going to do. “Plan” has a couple of different meanings, some of them are found in the Learning Guide.
So, Justin thinks they should plan out their trip. Vanessa says, “We’ll be fine (we’ll be okay). Stop worrying. We spend too much time planning (too much time thinking about what we want to do). Let’s just fly by the seat of our pants.” “Let’s just” means why don’t we or I want to have us do this. What she wants them to do is to fly by the seat of their pants (pants). Well, your “pants” are things that you wear that go on your legs, and the “seat of your pants” would be where you sit down, that part of your pants – your behind, your rear, what we might informally call your “butt” (butt). However, the expression “to fly by the seat of your pants” means to do things without planning, to do things spontaneously. That is, you don’t worry about it, you just go and you do something because you feel like doing it; there’s no planning involved. You’re not, of course, actually flying up in an airplane; it’s just an expression, to do something without planning it.
Justin says, “You really want to just go unprepared? That’s just not sensible.” Something that is “sensible” is something that is reasonable, something that makes sense, that is logical. Justin says, “Anything could happen.” Vanessa says, “I’m not going to lose sleep over it.” “To lose sleep over (something)” means to spend a lot of time worrying about it, being very anxious about it. You’re so anxious, you’re so worried, you can’t even sleep because you keep thinking about it. But Vanessa is not going to lose sleep over this thing or about this thing. She says, “We just need to meet some locals and they’ll be able to tell us about the hidden, secluded, and offbeat sites.” “Locals” (locals) are people who live permanently in a certain area. If you come to Los Angeles, I would be a local; I am someone who lives here. You would be a tourist or a vacationer; a traveler, we might say.
Vanessa wants to meet some locals so she can ask them about hidden, secluded, offbeat sites. Something that is “hidden” is something that you cannot see. More generally, it’s something that is secret; not a lot of people know about it. “Secluded” (secluded) is very private and quiet, away from other people, a place that is not close to anyone else. “Offbeat” (one word) means somewhat unusual, something that is interesting but not the normal kind of thing you might go see. So that’s what Vanessa wants, the hidden, secluded, and offbeat sites. “Those are the ones I want to see.”
Justin says, “You can explore all you like (all you want), but I’m bringing some insurance.” “Insurance” is normally something you buy from a company in case you have an accident or something goes wrong. You can have health insurance; if you get sick the insurance will pay for your medical care. Here, “insurance” is used more generally to mean something that will protect you from problems, something that will give you a guarantee in case something goes wrong that things will be okay. Vanessa asks, “What insurance?” Justin says, “I’m bringing two guidebooks and this phone number.” Vanessa says, “Phone number for what (which phone number)?” Justin says, “The phone number for the American embassy.” An “embassy” (embassy) is the official presence of another country in your country. Usually the embassies are located in the capital of the country, so in Washington, D.C. there is a Russian embassy. That’s the building where the Russian representatives – the “diplomats,” we would call them – are working and perhaps some of them living. Embassies are usually considered, in some ways, property of the other country and are protected by international law. The U.S. embassy, or American embassy, would be the American place in a country where the American diplomats and representatives are. Justin says, “That’s where I plan to go for help when you get lost off the beaten path!” “To get lost” means to become confused and not know where you are, usually because you are somewhere that you are not used to – that you are not familiar with. Justin says he’s going to call the American embassy when Vanessa gets lost off the beaten path, going somewhere that is not popular.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Vanessa: Put away that guidebook. I want our vacation to be exciting and unique, not cookie cutter. Tourists all visit the same sites. I want to explore and go to some places off the beaten path.
Justin: That would be fine except we’ve never traveled to Podville before and we don’t speak the language. How are we going to make our way around if we don’t plan out our trip?
Vanessa: We’ll be fine. Stop worrying. We spend too much time planning. Let’s just fly by the seat of our pants.
Justin: You really want to just go unprepared? That’s just not sensible. Anything could happen.
Vanessa: I’m not going to lose sleep over it. We just need to meet some locals and they’ll be able to tell us about the hidden, secluded, and offbeat sites. Those are the ones I want to see.
Justin: You can explore all you like, but I’m bringing some insurance.
Vanessa: What insurance?
Justin: I’m bringing two guidebooks and this phone number.
Vanessa: Phone number for what?
Justin: The phone number for the American embassy. That’s where I plan to go for help when you get lost off the beaten path!
[end of dialogue]
There’s nothing cookie cutter about the scripts for our podcast, that’s because they’re written by someone who never flies by the seat of her pants, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
guidebook – a small book that describes interesting things to do, places to visit, restaurants to eat in, and other activities for a particular city, region, or country, written for tourists
* This guidebook has more than 20 pages of restaurant recommendations for Manhattan alone!
unique – unlike anything else; different
* Kaitlin likes to give handmade gifts because they’re unique.
cookie cutter – with everything being the same; with many identical copies of something
* I’d hate to live in one of those new housing developments, where all the homes are cookie cutter.
site – a place or location, especially a place to visit as a tourist
* This was the site of the first store in this town.
to explore – to learn about a place by going there and walking around it and through it, experiencing it instead of reading about it in a book
* Lauren dreams of becoming an astronaut so that she can explore outer space.
off the beaten path – places, sights, and activities that are unusual or uncommon and that most visitors are unaware of
* This city has a lot of museums that are off the beaten path, but really interesting for the people who visit.
to make (one’s) way around – to be able to navigate an unfamiliar place, area, or region; to be able to move in an area without getting lost
* We moved to Pittsburgh more than two months ago, but I still can’t make my way around without a map.
to plan out – to have a plan for what one will do and when
* Do you plan out your family’s meals, or do you just decide what to cook each evening based on what you want to eat that day?
to fly by the seat of (one’s) pants – to be spontaneous; to do things without planning or worrying about them ahead of time, often when one doesn’t have all the necessary information or skills
* The previous head of the committee didn’t leave any papers or instructions for Noemi, so she had to fly by the seat of her pants for the first few months.
sensible – practical; reasonable and rational; logical
* Spending all our money on a trip to Las Vegas wasn’t very sensible, but it was a lot of fun.
to lose sleep over (something) – to spend a lot of time worrying about something so that it interferes with one’s ability to sleep well
* Yes, there are a few errors in the report, but don’t lose sleep over it. We can make those corrections in the next version.
local – a local resident; a person who is from a particular place or has lived there for a long time; not a tourist or visitor
* If you want to try authentic regional foods, eat where the locals eat.
hidden – secret; not seen or known by many people, often because someone does not want it to be obvious or well-known
* People say this house is connected to the church by a hidden underground tunnel.
secluded – away from other people, very quiet and private; without many people
* They watched the sunset on a secluded, romantic beach.
offbeat – unusual, quirky and interesting
* Pierre has an offbeat sense of humor, and sometimes people don’t understand his jokes.
insurance – a guarantee; something one does or has to protect oneself from problems and risks
* Carrie thinks having an umbrella in her purse is good insurance against rain.
embassy – a country’s official presence in another country, usually a large building with an ambassador and other staff members
* If you want to apply for a resident visa, you first need to go to the embassy.
to get lost – to become confused or disoriented and not know where one is, usually because one has moved into an area one is unfamiliar with
* When we hike in the woods, we should always take a whistle and a cell phone, just in case we get lost.
Comprehension Questions
1. Which of these sites could most likely be described as “unique”?
a) A cookie cutter place.
b) An embassy.
c) An offbeat site.
2. What does Vanessa mean when she says, “I’m not going to lose sleep over it”?
a) She isn’t worried about not having a plan.
b) She can’t sleep well if they don’t have a plan.
c) She thinks they’ll be able to find a hotel room.
Answers at bottom.
What Else Does It Mean?
to plan out
The phrase “to plan out,” in this podcast, means to have a plan for what one will do and when: “Akira planned out every detail of the wedding, from the invitations to the napkins.” A “floor plan” refers to the layout of a building: “I really like this floor plan, because the kitchen is next to the laundry room.” A “game plan” is one’s plan for being successful: “What’s the company’s game plan for increasing sales next year?” A “master plan” is a more detailed plan that provides total control in a difficult situation: “Passing that law is part of his master plan to improve healthcare.” Finally, an “installment plan” is an arrangement where someone can pay the money owed through several small, usually monthly payments: “We didn’t have enough cash to pay for a new washing machine, but fortunately, the store offered us an installment plan.”
to get lost
In this podcast, the phrase “to get lost” means to become confused or disoriented and not know where one is, usually because one has moved into an area one is unfamiliar with: “It’s really easy to get lost in that part of town, because there aren’t very many street signs.” The phrase “get lost!” is a rude, informal phrase used to tell someone to go away: “Ingrid got in trouble for telling her little brother to ‘get lost.’” The phrase “to get lost in (something)” means to become very distracted by something and unaware of anything else: “I miss the days when I had time to get lost in a good book for hours.” The phrase “to get lost in (something)” can also mean to be forgotten or unnoticed because something else gets the attention: “The speech wasn’t very good, because the main ideas got lost in the details.”
Culture Note
Each year, publisher Houghton Mifflin publishes an “anthology” (a collection of small pieces written by many different people) called “The Best American Travel Writing” and each year has a guest editor who writes the introduction. Many of these guest editors are famous American “travel writers” (people who write about their travels and other cultures).
In 2000, Bill Bryson was the guest editor. He has written many “humorous” (funny) books about his travels, including The Lost Continent: Travels in Small-Town America and A Walk in the Woods: Rediscovering America on the Appalachian Trail.
Paul Theroux was the anthology’s guest editor in 2001. His best-known novel, The Great Railway Bazaar: By Train Through Asia, “recounts” (describes) his experience as he traveled across Asia by train for four months.
Frances Mayes, who was the anthology’s guest editor in 2002, wrote a very popular book called Under the Tuscan Sun: At Home in Italy. That book is a “memoir” (a book about someone’s life and experiences), but also an example of travel writing, because it talks about her experience buying and living in an Italian “villa” (house).
The guest editor in 2006, Tim Cahill, is the “founding” (original; present when an organization or business begins) editor of Outside magazine and he often writes for National Geographic Adventure magazine. People enjoy reading his “tales” (stories) of “adventure travel” (very exciting and possibly dangerous types of travel). For example, he drove from Argentina to Alaska in “just under” (slightly less than) 24 days – more quickly than anyone else had ever done.
Author Bill Buford was the guest editor in 2010. Much of his work focuses on food and travel. For example, his article Extreme Chocolate: The Quest (Search) for the Perfect Bean describes his experience traveling with the founder of Dagoba Chocolates.
Comprehension Answers
1 - c
2 - a