= 0693
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 693: Following a Dress Code.
This is English as a Second Language Podcast episode 693. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
We invite you – I invite you to go to our website at eslpod.com. There, you will find a Learning Guide for this episode, and your life will be better after that.
This episode is a dialogue between Tae and Nicole. They’re going to be talking about a “dress code,” when certain organizations have requirements for how you must dress. Let’s get started.
[start of dialogue]
Tae: What are you doing? Why are you taking all of my clothes out of my suitcase? I just finished packing that.
Nicole: You’ve packed all of the wrong things. We’re going on a luxury cruise and all you’ve packed are shorts and t-shirts.
Tae: I’m going on vacation and I don’t have to dress to impress.
Nicole: You’ve never been on a cruise like this one, but I have, and there’s a dress code. You’ll need formal wear for some of the dinners.
Tae: I’m not wearing a suit and tie on vacation.
Nicole: No, not a suit and tie. There’ll be a dance the final night of the cruise that’s black tie, so you’ll need your tuxedo. I’m bringing a few cocktail dresses myself. Don’t worry. You can go semi-formal the rest of the evenings.
Tae: This is ridiculous. I have to wear business attire 300 days out of the year and you’re making me dress up when I finally go on a vacation.
Nicole: You don’t have to dress up the entire time. You can go California casual during the day. I’m just asking that you look presentable a few hours each day. Is that so hard?
Tae: I knew there was a catch when you booked this vacation. It’s less a vacation for me than a dress-up party for you!
[end of dialogue]
Tae begins by saying to Nicole, “What are you doing? Why are you taking all of my clothes out of my suitcase? I just finished packing that.” So, Tae and Nicole are going on a trip somewhere, and Tae has put all of his clothes into his “suitcase,” which is a big bag or container for your clothing when you travel; it could also be called a piece of “luggage.” He says, “I just finished packing that.” “To pack” (pack) means, in this case, to put things into a bag or a suitcase so that you can take them with you when you travel. “Pack” has a couple of other meanings, as well. Take a look at our Learning Guide for this episode to get more information.
Nicole says, “You’ve packed all of the wrong things. We’re going on a luxury cruise and all you’ve packed are shorts and t-shirts.” A “cruise” is when you get on a big boat and you sleep on the boat – really, it’s a ship – and you go with all these other people on the ship and you usually travel for three or four days, maybe a week or two weeks. Everyone has their own room, and it is for some people very enjoyable. I have to say I have been on a couple of short, three-day cruises from Los Angeles down to Ensenada, Mexico, and I didn’t like them very much. I didn’t like the food; I didn’t like being on a big ship…eh, but some people love it. And so, if you like that sort of thing, that’s great. Not for me. Anyway, Nicole says they’re going on a luxury cruise. “Luxury” usually means very expensive, something that’s very nice. But Tae has just packed shorts and t-shirts, so he doesn’t have anything very nice to wear.
Tae said, “I’m going on vacation and I don’t have to dress to impress.” This is an expression: “to dress to impress” means to choose your clothing so that other people will have a good opinion of you. If you are going to an interview for a job, you should dress to impress; you should want the other person to think that you are very professional, that you take this interview seriously, and so forth, and by wearing the right clothing then you can impress the other person. “To impress” means to give a good opinion to someone else about you.
Nicole says, “You’ve never been on a cruise like this one, but I have, and there’s a dress code.” “Code” (code) is another name for a rule or law; here, it refers to the rules that the ship has about how you dress. It’s called a “dress code.” Many businesses have dress codes; you can’t come in without a tie, women can’t wear miniskirts, men can’t wear miniskirts – I mean some of them can be very difficult to follow! My old school, where I went grade school and high school, had a dress code. The boys all had to wear shirts and ties and black pants and black shoes and black socks. That was the dress code. Well, the ship for the luxury cruise has a dress code. Nicole says that Tae will need formal wear for some of the dinners. “Formal wear” (wear) is clothing that is used for very special occasions. A wedding, a funeral, an important party such as an anniversary, these would be times for formal wear. Also, some restaurants require formal wear.
Tae says, “I’m not wearing a suit and tie on vacation.” A “tie” is what a typically man puts on; it’s a long piece of fabric – of cloth – that is in the front from your neck down to, say, your waist. A “suit” refers to a jacket and pants that go together that are very formal looking. The word “suit” can be used both for a man and a woman, but “suit and tie” usually refers to what a man would wear.
Nicole says, “No, not a suit and tie. There’ll be a dance the final night of the cruise that’s black tie.” “Black tie” means that it will be a very formal, a very fancy event, and the men will have to wear tuxedos. A “tuxedo” (tuxedo) is a special type of suit that men wear for very formal occasions such as a wedding, but only the men who are participating in the wedding; the groom and the best man, for example, typically would wear a tux or a tuxedo. We call it a “tux” (tux) for short. If you are going to the Academy Awards in Hollywood to receive an Oscar for your latest movie, then you would wear, if you were a man, a tuxedo. I plan on wearing a tuxedo when I am given an award for my singing at the Grammy Awards, they’re called here in the U.S.; I’m just waiting for my invitation!
Nicole says, “I’m bringing a few cocktail dresses myself.” A “cocktail (cocktail) dress” is a short or long dress worn by women for a special occasion. A “cocktail” is actually another word for an alcoholic drink, but a “cocktail dress” is a formal dress that a woman would wear. Nicole says, “Don’t worry. You can go semi-formal rest of the evenings.” “Semi” means half or partly, so “semi-formal” means not completely formal but not completely the opposite, what we would call “casual.” The opposite of “formal,” when we’re talking about clothing, is “casual.”
Tae says, “This is ridiculous,” meaning this is silly, this is something very strange, something that people would laugh at. He says, “I have to wear business attire 300 days out of the year and you’re making me dress up when I finally go on vacation.” “Business attire” is another term for business clothing, the kind of clothes you would wear to your office or wherever you work. “Attire” (attire) is just another word for clothing. Tae is complaining that he has to dress up most of the days of the year in order to go to work, and now, when he’s going on vacation, he doesn’t want to dress up. “To dress up” is a two-word – everyone say it with me – phrasal verb that means to wear clothing that is nicer than what you normally wear, or what you would wear on the weekend let’s say. Tae doesn’t want to dress up for vacation.
Nicole says, “You don’t have to dress up the entire (or the whole) time”, that is, not every day on the vacation. “You can go California casual during the day.” “California casual” means that you wear clothing that is not quite as nice as a suit and tie, but not jeans and t-shirts either; it’s sort of semi-formal. California has the reputation of being more relaxed in terms of how people dress. If you go to Hawaii, people are really relaxed – the island of Hawaii. California, however, is more casual, less formal in terms of the way people dress here, in part because the weather is hotter and so it doesn’t makes sense to dress up as much. At least that’s my opinion. Nicole says, “I’m just asking that you look presentable a few hours each day.” “To look presentable” means to look nice, to look clean, so that other people can see you. When I get up in the morning, I go outside of my house and I get my newspaper, which was delivered to my house. I try to look presentable; I try to have at least some clothes on so that if one of my neighbors saw me I wouldn’t be too embarrassed. That’s “to be presentable,” to look nice, to have clean clothing, and so forth.
Tae says, “I knew there was a catch when you booked this vacation.” A “catch” (catch) here means a trick, something that is hidden, something that you don’t know about but you only find out later. It sounds great, but then when you find the real truth it isn’t so great. So, a “catch” is the thing that you didn’t know about that isn’t so wonderful, and Tae says that he knew there was a catch when Nicole booked, or made the reservations – the plans for their vacation on this luxury cruise. He says, “It’s less a vacation for me than a dress-up party for you!” He’s saying that it isn’t really a vacation; it’s an opportunity for Nicole to dress up, to wear nice clothing.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Tae: What are you doing? Why are you taking all of my clothes out of my suitcase? I just finished packing that.
Nicole: You’ve packed all of the wrong things. We’re going on a luxury cruise and all you’ve packed are shorts and t-shirts.
Tae: I’m going on vacation and I don’t have to dress to impress.
Nicole: You’ve never been on a cruise like this one, but I have, and there’s a dress code. You’ll need formal wear for some of the dinners.
Tae: I’m not wearing a suit and tie on vacation.
Nicole: No, not a suit and tie. There’ll be a dance the final night of the cruise that’s black tie, so you’ll need your tuxedo. I’m bringing a few cocktail dresses myself. Don’t worry. You can go semi-formal the rest of the evenings.
Tae: This is ridiculous. I have to wear business attire 300 days out of the year and you’re making me dress up when I finally go on a vacation.
Nicole: You don’t have to dress up the entire time. You can go California casual during the day. I’m just asking that you look presentable a few hours each day. Is that so hard?
Tae: I knew there was a catch when you booked this vacation. It’s less a vacation for me than a dress-up party for you!
[end of dialogue]
There’s no catch here at ESL Podcast. You listen to the wonderful scripts by Dr. Lucy Tse and your English will get better.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
to pack – to put things into a bag or suitcase, usually so that one can take them with one while traveling
* Don’t forget to pack your toothbrush and deodorant for the camping trip!
luxury cruise – a vacation where one is on a very large ship, eating nice food, wearing nice clothes, enjoying entertainment, and relaxing
* This luxury cruise features performances by some very famous singers.
to dress to impress – to choose what one will wear based on how one will be perceived by other people; to try to make sure other people have a good opinion of oneself by wearing clothing that they will admire
* When you have your first interview, it’s important to dress to impress.
dress code – rules about what one can and cannot wear or what one is expected to wear or not wear
* The elementary school has a dress code that doesn’t allow students to wear t-shirts with rude words printed on them.
formal wear – clothing used for very special occasions
* If this is an event with formal wear, the women will probably be wearing long dresses, not short ones.
suit and tie – the clothing worn by most businessmen, consisting of pants with a matching suit jacket, a shirt with buttons on the front, and a long piece of fabric tied around one’s neck so that it hangs down in the front
* I could never work in a bank because I would hate having to wear a suit and tie every day.
black tie – an event where people are supposed to wear very nice, fancy, formal clothing, including tuxedos for men
* She wants to have a black tie wedding at a luxury hotel, but he wants to have an informal, outdoor wedding on the beach.
tuxedo – a special type of suit that men wear for formal occasions, with black pants and a matching black suit jacket, a white shirt with buttons on the front, and a small bow tied around the neck
* Mike decided to rent a tuxedo for the awards ceremony instead of buying one, since he’s probably never need to wear one again.
cocktail dress – a short or long dress worn by a woman for a special occasion, often made with special, fine fabrics
* Dasha bought a beautiful red cocktail dress with lace and beading.
semi-formal – somewhat formal; between formal and casual
* Is it okay for women to wear pants to a semi-formal event?
ridiculous – very silly and not logical; something that other people will laugh at and think is very strange or inappropriate
* He looks ridiculous in his clown costume, with curly orange hair, a red nose, and huge shoes.
business attire – clothing worn in a professional work environment
* Shorts and sandals definitely are not appropriate business attire in this company.
to dress up – to wear clothes that are nicer than what one normally wears
* Her husband asked her to dress up for their date next Friday, but he still hasn’t told her where they’re going to go.
California casual – the type of informal clothing often worn by people in California, nicer than jeans but not as nice as business casual
* Yes, you can wear a button-down shirt and slacks to a California casual event, but don’t wear a tie.
presentable – looking nice, clean, and pretty enough to be seen by other people
* Sure, you can come over for breakfast anytime, but please give me enough time to brush my hair and make myself presentable.
catch – trick; something that is hidden or obscured and makes an offer less attractive
* Are you really offering to sell your brand-new pickup truck for just $5,000? What’s the catch?
Comprehension Questions
1. Which of these styles is the most formal?
a) Black tie.
b) Business attire.
c) California casual.
2. What does Tae mean when he says, “I knew there was a catch when you booked this vacation”?
a) He thinks Nicole tricked him.
b) He doesn’t want to carry Nicole’s suitcase.
c) He wants to pack by himself.
Answers at bottom.
What Else Does It Mean?
to pack
The verb “to pack,” in this podcast, means to put things into a bag or suitcase, usually so that one can take them with one while traveling: “Please try to pack everything in just one small suitcase.” The verb “to pack” can also mean for many people or animals to go into a small area: “Hundreds of people packed into the auditorium to hear the speaker.” The phrasal verb “to pack down” means to press something into a container to make room for more: “Did you remember to pack down the brown sugar while you were measuring it?” “To pack (something) away” means to store something because it won’t be needed for a long time: “Where did you pack away the Christmas decorations?” Finally, the phrase “to pack a gun” means to carry a gun: “You’re a banker! Why do you need to pack a gun?”
catch
In this podcast, the word “catch” means a trick, or something that is hidden or obscured and makes an offer less attractive: “This book promises to teach us how to make thousands of dollars – the only catch is that it costs almost that much!” A “catch” is normally the act of being able to grab a ball or another object that is thrown to one before it falls on the ground: “A good baseball player needs to be able to catch balls, too, not just hit them with the bat.” The phrase “a good catch” describes a relationship or a marriage where the other person is very wealthy, successful, or beautiful: “Do you believe she really loves you, or does she just think you’re a good catch?”
Culture Note
Dressing for Business
In general, American workplaces are much less formal than they used to be, but there are still “expectations” (what people believe should happen) for how people should dress.
Most people dress up for interviews. That usually means a suit and tie, and women are often expected to wear a suit with a skirt, not pants. Interviewees should wear only “modest” (not too fancy or expensive) jewelry and makeup. However, the expectations “vary” (are different) by industry. An interview for a “blue collar job” (a job where one uses one’s hands and does not need a very high level of education) probably doesn’t require a suit and tie, but the interviewee should still dress nicely.
Many offices allow people to wear “business casual” clothing. This term is hard to define, especially for women. For men, business casual usually means wearing “slacks” (nice pants) or “khaki pants” (light-colored cotton pants) and a “button-down shirt” (a shirt with a collar and buttons in the front), but not a tie. Women have more options, as they can wear dresses, skirts and “blouses” (shirts with a collar and buttons in the front), or pants and “sweater sets” (a tank top or short-sleeved shirt and a matching long-sleeved shirt that has buttons in the front, but left completely or partially open). Shorts, “tank tops” (shirts that expose one’s shoulders), and sandals are not appropriate for business casual.
Many offices that require more formal business attire allow their employees to dress more casually on “casual Fridays.” Unless there is an important meeting, employees can wear “business casual” clothing on Fridays as long as they continue to wear suits or other more formal clothing during the rest of the week.
Comprehension Answers
1 - a
2 - a