
= 2-14 统治策略
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== (古罗马) 对敌战争的策略

proved quite successful.


'''

=== 分而治之

One was to divide and conquer. The Romans always tried to defeat one enemy at a time and avoid waging war against a coalition. Thus they often attempted to turn their enemies against each other.


'''

=== 打是为了谈, 用己方的胜利来作为谈判筹码

Another tactic was to negotiate from strength. Even after suffering enormous defeats in battle, Rome would continue a war until it won a major engagement and reach a position from which to negotiate for peace with momentum on its side.


'''

===  建立殖民地, 作为边防线

Yet another successful strategy was to establish colonies in recently conquered lands to serve as the first line of defense if a region revolted against Rome.


'''

===  建立盟友

Romans also transformed former enemies into loyal allies who could enjoy self-government as long as they honored Rome’s other alliances and provided troops in times of war. Some even received Roman citizenship.


'''

==  伊斯兰的统治策略

=== 在穆斯林还对管理国家缺乏经验的时候, 就暂时利用非穆斯林人, 直到他们失去利用价值为止.

Within the running of the state, too, many government officials in these early decades—in positions from tax collector to scribe at the court of the ruler—were non-Muslim holdovers from the Byzantines and Persians. They helped the early Muslim rulers establish and administer a government the size of which they had never experienced.

But by the eighth century they were rapidly being shunned in favor of Arabs. In some cases, non-Muslims were passed over for the best positions.


'''

===  先暂时利用前朝文化, 来安抚前朝遗老, 之后再慢慢”去前朝化”

The culture started to change after the second Islamic civil war in the early 690s. The victors, a branch of the Umayyad family, began to make the empire look increasingly Arab. Their governmental reforms included the gradual removal of signs and symbols associated with the old Byzantine and Persian rulers, such as Christian crosses on coins ).



'''

===  扩张领土时, 优先通过和平协议的方式, 而非武力战争

Calling these events the “Arab-Muslim conquests” is somewhat misleading, however. While the first years of expansion did see several major battles, most of the territory came under Islamic control through peace agreements. Cities and regions agreed to terms of surrender that protected their residents, many of their belongings, and their right to practice their religion. 


'''

===  对方只要缴税, 就能其继续保有其宗教信仰自由

Especially during the seventh century, the Muslims maintained a policy of noninterference toward the religious practices of subject populations. As long as they paid taxes to their new Muslim government, the conquered could live in the Islamic state and still practice their religion somewhat freely.


'''

===  穆斯林一般不与非穆斯林结婚, 因此阻碍了穆斯林信徒数量的发展

What was it like for Indigenous peoples of captured territories to live under Islamic rule during the Umayyad and Abbasid periods? What is surprising is that the majority of these inhabitants were not Muslims themselves.

For example, a Muslim generally could not marry a non-Muslim under Islamic law, but if such a marriage occurred, a Muslim woman’s future husband had to convert to Islam to marry her, and the children of a Muslim husband had to be raised as Muslim. Thus, it seems likely that the process of conversion to Islam at this time was quite slow and that the Muslims remained a numeric minority for centuries even though they wielded the majority of power in the empire.



'''

== 蒙元的统治策略

=== 四等人制, 用流动性的外族, 来统治汉族. 因为流动性, 外族对汉人就没有情感联系, 也不可能建立起深耕权势

Kublai Khan’s most drastic change was to replace the Confucian system of class distinctions based on economic function with one based on ethnicity. 

At the top of the Yuan class structure were Mongols, followed by non-Chinese people, who were Europeans or previous steppe inhabitants like the Jurchen, Tangut, and Khitan. 

The bottom two classes were Chinese people: those of Han ethnicity who had been ruled by the Jin in the north, and the remaining Song Chinese who lived in the south. Mongols could not marry people from these bottom two classes.






In the Yuan dynasty, although some Chinese officials maintained their positions at the local level, the most lucrative and prestigious jobs were held primarily by Mongols and non-Chinese outsiders.

The Song Chinese, who were at the bottom of the four-class system, were governed by two administrators, one a Chinese person and one a Mongol or non-Chinese person. Both were imperial appointees. The Chinese administrator was under the supervision of and responsible to his counterpart. People in all these positions were rotated periodically, so they could not build up a power base. 




Some non-Chinese administrators over the Song had not intended to work in the Yuan government. They came seeking some favor, often the right to trade, in exchange for which the emperors required them to perform administrative tasks. Among these bureaucrats taken as hostages, most were Muslim traders from other parts of the Mongol Empire. Regardless of how well they did their jobs, such bureaucrats were not likely to bond with the population and create a power base from which to challenge imperial authority.


'''

===  短暂恢复科举制, 但用配额来限制汉人录取人数

Following Kublai’s death in 1294, his system’s flaws became apparent. In 1315, his great-grandson Buyantu reinstated the mandarin exam system. Non-Chinese people took different (and shorter) exams than the Chinese people, and between 25 and 50 percent of those who passed had to be non-Chinese people. The effect of this quota was magnified because Song Chinese people made up more than 90 percent of the population, according to Yuan censuses. Between the differences in the exams and the quota system, it was much easier for Mongols and non-Chinese to pass than for Chinese.



'''

==  (西班牙) encomienda system 监护制 (16世纪初, 对殖民地开始执行)

By 1502, they had created the encomienda system.


The term encomienda comes from the Spanish word encomendar, which means “to entrust.” The encomienda was a system of entrusting valuable territories and peoples to those who had proven to the crown that they were worthy of that trust. The Spanish government gave each grantee, known as an encomendero, the right to demand labor from Indigenous people living in a specific area. In exchange, the Spaniards were supposed to provide guidance, education, and leadership to these Native Americans. 

While encomiendas did not technically include the ownership of any land, encomenderos often took possession of lands where the people under their control lived. Sometimes the system of forced labor even devolved into what was functionally, if not legally, slavery.




The Spanish often mistreated Native Americans, but writers from Spain’s colonial rivals, most notably the English, frequently exaggerated Spanish cruelty to justify their own colonial abuses.


'''

==  (西班牙) 探索美洲时, 所采用的模式 → encomendero

Spain’s exploration of the new continents continued, led by conquistadors. Some of these explorers were nobles or had military training and had fought against the Muslims in Spain; others were landless and wished to improve their lot in life.


One instrument by which the Spanish government compensated conquistadors was the encomienda, a hereditary grant that entitled the holder, called an encomendero, to the labor of a specified number of conquered people, or to a tribute of precious metals or agricultural produce.



'''

==  (葡萄牙) 进行联盟, 以分化瓦解敌人(印度)

Establishing a pattern that they and other Europeans later replicated throughout India, the Portuguese sought to divide and conquer by entering into alliance with some local rulers to the disadvantage of others, a strategy made easier in later decades by the weakening of the Mughal Empire.


'''

==  (法国) 与北美原住民结盟

The French probably enjoyed the friendliest relationships with Native Americans of any European colonizers. Unlike their rivals, they usually attempted to solve the shortage of labor by allying themselves with Native Americans.

Also, because few French women came to New France, many French colonists married Native American women, leading to the creation of a multicultural and multiracial society.


In 1627, Cardinal Richelieu, chief minister to King Louis XIII, provided a spiritual justification for Franco-Indian partnerships in the Ordonnance of 1627. The Ordonnance read in part, "The descendants of the French who are accustomed to this country [New France], together with all the Indians who will be brought to the knowledge of the faith and will profess it, shall be deemed and renowned natural Frenchmen, and as such may come to live in France when they want, and acquire, donate, and succeed and accept donations and legacies, just as true French subjects, without being required to take letters of declaration of naturalization."


'''

==  殖民地地位, 在工业化时代时, 发生了变化 → 母国人不再到殖民地定居了, 不像早期时英国人移民到北美那样

The new colonies were quite different from those that European powers had established in the sixteenth and seventeenth centuries. It was not generally expected that large numbers of Europeans would relocate to Africa or Asia and make permanent homes there, and the colonies were not intended to have quite the same relationship to the home country that earlier “settler colonies” had had. The U.S. treatment of the Philippines and Filipinos was fundamentally different from what North American colonists had experienced from Great Britain, for example. The industrial nations intended to exploit the resources and people of the colonies they established, not settle them.


Politically: Repeated breach of pledges to give the natives a fair and reasonable share in the higher administration of their own country, which has much shaken confidence in the good faith of the British word. Political aspirations and the legitimate claim to have a reasonable voice in the legislation and the imposition and disbursement of taxes, met to a very slight degree, thus treating the natives of India not as British subjects, in whom representation is a birthright. Consequent on the above, an utter disregard of the feelings and views of the natives.


The natives call the British system Sakar ki Churi, the knife of sugar. That is to say, there is no oppression, it is all smooth and sweet, but it is the knife, notwithstanding.


There were some exceptions. The North African colony of Algeria, which France had taken control of in 1830, was incorporated as part of France in 1848. Many French people and other Europeans immigrated to the coastal regions of Algeria and Tunisia with government encouragement in the nineteenth century. Many Europeans also settled in the British and Dutch colonies in southern Africa. However, this was not the imperial norm.



'''

