
= 4-14 中国
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 元朝, 滥发纸币, 导致通货膨胀

Yuan China’s economic growth had at best stagnated, thanks to a decline in consumer purchasing power caused by inflation and heavy taxation.

The use of paper currency was a major contributor to inflation. While paper money was theoretically convertible to metal or silk, the Yuan government issued much more of it than it had metal or silk to redeem it with. Kublai decreed that currency must be used in transactions with the government. This meant the population could not escape increasing inflation, however, as successive Yuan governments issued more paper currency to pay their bills and forced the population to obtain such money to pay their taxes.


'''

==  禁止对外贸易, 闭关锁国 (明, 朱元璋时)

Japan was not the only nation that turned inward in the seventeenth century. China did so as well.

To prevent the dangerous effect of outside ideas and potential challenges to his rule, Hongwu decided that Chinese contact with foreign lands would consist primarily of visits by vassals from tributary states.

In 1371, all private foreign trade was forbidden. Several years later, all foreign trade officially came to an end when the Maritime Trade Intendancies’ offices in the port cities of Ningbo, Guangzhou, and Quanzhou, through which all tribute goods were to flow, were closed. Harbors were filled with rocks and wooden stakes to prevent ships from using them. Ships were destroyed or left to rot in their docks.

A shore patrol was instituted to catch anyone attempting to engage in trade. Though the punishment was death, smugglers widely violated the rule.



By cutting off access to foreign trade outside the tribute system, the Ming government greatly reduced its tax revenue, which left it constantly short of funds. Hongwu’s reforms, which were intended to reduce the cost of government, were largely unsuccessful.


'''

==  七下西洋 (明, 永乐, 宣德 1430)

Hongwu’s son, the third emperor of the Ming dynasty, dispatched Zheng He, a trusted palace eunuch, on a series of six voyages throughout the Indian Ocean. The purpose of these voyages was to demonstrate the wealth and power of China by distributing gifts to foreign rulers, thus prompting them to pledge themselves as vassals and offer tribute to the Ming emperor.

In 1430, the Xuande Emperor, the Yongle emperor’s grandson, ordered Zheng He to undertake his seventh and final voyage. These forays were China’s last significant effort to make contact with overseas lands for many decades, however. Factions at court worried about the effect of outsiders and their ideas on the empire, as well as the cost of the trips. Following Zheng He’s death, his charts and records were destroyed, and the ships of the fleet were left to rot.



'''

==  重新放开对外贸易 (1567)

In 1567, the Ming dynasty reversed the policy that had prohibited foreign trade, and soon European merchant ships began arriving again.


China’s economy boomed, and many Chinese peasants began to focus on producing goods for the foreign market. In Jingdezhen in Jiangxi province, people mass-produced porcelain.


'''

== 经济破产, 导致明朝被推翻 (1644)

The days of the Ming were numbered. The cost of supporting the imperial family had grown astronomically. With the imperial government lacking sufficient funds to pay the army, Chinese soldiers were laid off.

In 1627–1628, hungry, impoverished, and angry soldiers and peasants rose up in revolt in northern China. By 1632, violence had spread to other provinces. This made it even harder for government officials to collect taxes, which Beijing had raised in 1639, angering people even more. In April 1644, Li Zicheng’s peasant army seized Beijing.


It was not until 1683 that all of China was brought under Manchu control.


'''

==  一战时, 中国派劳工, 帮助美英一方

In Asia, the coming of the war caused nations to take sides.


The Allies rejected offers of military troops from China at the beginning of the war. By 1916, however, the situation had changed, and Britain and France allowed Chinese laborers to come to Europe. China had been willing to send combat troops, hoping to gain leverage in treaty negotiations after the war and support for ousting Japan from its borders, but Japan, which had taken control of Qingdao and hoped to establish itself as the unquestioned military power in Asia, would not permit it. Thus, approximately 130,000 Chinese laborers arrived in Europe, to repair equipment and dig trenches but not to fight.


'''

==  收回西藏 (1951)

In 1951, representatives of the PRC and the Tibetan government signed the Seventeen Point Agreement making the region once again part of China, an event described by the CCP as the “liberation of Tibet.” In 1959, the Dalai Lama, the ruler of Tibet and leader of Tibetan Buddhism, fled to India with other members of the Tibetan government, who maintained that the agreement with China had been made under duress.


'''

==  The Great Leap Forward 大跃进 (1957年底 - 1960年代初) → 集体化成公社, 从农村榨取资源, 来供应工业发展, 结果造成大饥荒

In imitation of the Soviet model, Mao instituted a Five-Year Plan in China in 1953 and embarked on nearly seven hundred industrial projects, more than one hundred with the assistance of the Soviet Union.


He also began the collectivization of agriculture by forcing peasants to labor together on state-owned farms instead of tending to farms worked by individual families.

Although the first Five-Year Plan was successful, the second Five-Year Plan proved a disaster. This plan, also known as the Great Leap Forward, began in 1958.

The proceeds of agriculture would fund industry.



Collectivization efforts were intensified, and by the end of 1958 more than twenty-five thousand communes had been created, each consisting of several thousand families on average.

Communes were large units of production. All tools, livestock, food, and other valuable items belonged to the commune as a whole instead of to individuals or families, and the commune’s leaders determined what work each member would do. Members worked together to grow crops in warm months and build construction projects during the winter.

Food was prepared in communal kitchens, and everyone ate together in communal dining halls. Communes also operated schools and hospitals for their members.




Grain produced by communes in the countryside fed city dwellers and industrial workers. Communes began to exaggerate their grain production levels to win political favor. Even as they strove to grow more food, laborers were also ordered to engage in extra projects like dam construction.

The requisitioning of grain to feed the cities produced disaster in rural China. crops. Famine set in, and people ate bark, leaves, and clay. Some Chinese historians place the death toll at five million, while Western historians believe thirty to fifty million people died between 1959 and 1961.



Farm laborers were also ordered to produce steel in backyard furnaces hastily built in the countryside. To meet quotas, they stripped the countryside of wood and burned their own furniture to fuel the furnaces. In the end, the steel produced was of such low quality that it was worthless.


Deng especially began to reverse some of Mao’s more damaging policies by, for example, allowing peasants to sell grain surpluses. Given positive incentives to produce more food, the peasants did so, alleviating food shortages.

Mao was sensitive to failure, however, and resented the successes of Zhou, Deng, and Liu. When Marshall Peng Dehuai, the Minister of Defense and a longtime associate of Mao, criticized his handling of the Great Leap Forward, Mao dismissed him from his position and replaced him with Lin Biao.



'''

==  the Cultural Revolution 文化大革命 (1966.05 - 1976.10) → ① 利用红卫兵来铲除毛泽东思想的敌人. ② 然后, 红卫兵利用完了, 就被毛抛弃, 令他们下放到农村.

In 1966, Mao abruptly warned that “revisionists” were seeking to alter the direction of the CCP. He called on the younger generation of Chinese people—high school and university students and young factory workers—to engage in “class struggle” and save the revolution. In July 1966 he launched the event known as the Chinese Cultural Revolution.



In August 1966, millions of Red Guards rallied in Beijing as Mao and Lin Biao encouraged them to purge the country of “bourgeois” elements by attacking the “Four Olds”: old customs, old culture, old habits, and old ideas.

Red Guards then attacked and killed their teachers and school administrators. Provided with food and lodging at government expense, Red Guards rampaged through the country, destroying books, works of art, temples, monasteries, tombs, and historical sites. They beat people and forced them to confess to having bourgeois thoughts. No one knows how many were killed during the Cultural Revolution; it may have been as many as two million.



Liu Shaoqi and Deng Xiaoping, who displayed insufficient revolutionary fervor, were removed from positions of power.


In 1968, the Red Guards were themselves dismissed as Mao sought to curb their power. They were sent to the countryside along with other urban youth to learn from the peasants.


In 1969, Lin Biao was named Mao’s successor. Two years later, Lin died in a plane crash while attempting to flee to the Soviet Union. He may have feared that Mao suspected him of plotting against him and planned to punish him.


'''

== 四人帮掌权期

As Mao retreated into depression and ill health, his role was increasingly taken over by “The Gang of Four,” consisting of Mao’s wife Jiang Qing, his chosen successor Wang Hongwen, Zhang Chunqiao, and Yao Wenyuan. However, they were primarily concerned with ensuring ideological purity and the continuation of “revolutionary” political thought. Crucial matters such as the economy were left in the hands of Premier Zhou Enlai.

Zhou, however, was dying of cancer and needed help. He returned Deng Xiaoping to power to assist him.


Following Zhou’s death in January 1976, the Gang of Four managed to oust Deng Xiaoping from power once more, but this time he did not remain away for long.

Following Mao’s death on September 9, 1976, his successor Hua Guofeng had the Gang of Four arrested and Deng returned to power.


'''

==  邓小平改革开放 (1978.12)

In 1978, he replaced Hua as leader of China and argued that the country needed to focus on modernizing and building its economy instead of continuing to pursue revolution by following the teachings of Mao. The Chinese system of higher education returned to normal as Deng reinstated entrance examinations, which had been suspended during the Cultural Revolution.


Beginning in the late 1980s, relations with the Soviet Union also began to improve.


'''