
= 5-03 美国 (20世纪)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== 美国在第一次世界大战前, 一直维持”孤立主义”

Isolationism had been a consistent practice of U.S. foreign policy, and the United States planned to maintain it, while at the same time selling products to both the Allied powers of Britain and France and the Central powers of Germany and Austria-Hungary. It was clear from the outset, however, that “the vast majority of American trade went to the Allies,” partly because of Britain’s substantial role in U.S. naval, merchant, and credit operations but also because the British blockade made it difficult for anyone to trade with Germany.

U.S. banks were soon extending loans and lines of credit to both sides as well, although approximately $2 billion had been extended to the Allies by the spring of 1917 and a mere $27 million to the Central powers.



Among the American public, there was little support for or interest in entering this European war. Not hampered by censorship of the news as the combatant powers were, American readers could easily learn about the casualty numbers and the horror of the war.


However, his commitment to the freedom of the seas and the rights of neutral nations in times of war soon put him on a collision course with Germany.

In 1917, germany announced in January of that year that it would engage in unrestricted submarine warfare. This meant that any ship in a war zone was a target for sinking even if it were sailing under the flag of a neutral power, so U.S. merchant ships were now subject to being torpedoed.

'''

==  美国决定参战(一战) 的原因

=== ① 德国的无限制潜艇战, 威胁了航海自由.



Germany made this decision because it felt that Britain would be forced to pull out of the war if the lifeline of cargo coming to it from the United States were cut off. Germany had suffered food shortages beginning in 1915. By 1917, as a result of the British blockade and the enlistment of male farm laborers for war, the nation’s urban population was starving, and its troops were on reduced rations. Unless Britain withdrew from the war soon, Germany would be forced to surrender.

Obviously, Germany knew this decision would anger the United States and could well cause it to enter the war itself, but it was a gamble its leaders were prepared to take. They fully believed that Germany could achieve victory if it could force the British to surrender before the United States could enter the war.



'''

===  ② 德国与墨西哥做交易, 想要用美国领土做回报, 割让给墨西哥

Further exacerbating tensions between Germany and the United States was the publication on March 1, 1917, of the Zimmermann Telegram. This message had been sent to Mexico by Germany’s foreign minister, Arthur Zimmermann, offering a deal. Germany wanted the Mexican government, in the event of war with the United States, to actively cause more disturbances along the border, keeping even more U.S. troops there and thus unavailable for deployment to Europe.

In return for Mexico’s cooperation, upon its victory, Germany would grant it the region of Texas, New Mexico, and Arizona, territory it had lost in 1848 as a result of war with the United States.


'''

===  ③ 如果德国占领欧洲, 美国银行贷款给欧洲国家的钱, 就收不回来了.

U.S. banks, which realized the loans they had extended to the European Allies would go unpaid if Germany won, already supported their country’s involvement, as did businesses that hoped U.S. assistance would encourage the Allies to grant them greater access to global markets.


Even the victorious nations faced economic problems. Britain and France had borrowed billions to finance the war and had sizable debts to repay, many to the United States.



In April 1917, the United States entered the conflict on the side of the Allied powers.


'''

==  美国通过 <间谍法>(1917) 和 <煽动叛乱法>(1918)

The U.S. government’s effort to squash criticism of the war began in 1917 with the Espionage Act. It set limits on what could be mailed, banning any type of anti-war newspaper or pamphlet.


In 1918, Congress passed the Sedition Act. This forbade “disloyal, profane, scurrilous, and abusive” language about the decision to enter the war, the draft, the flag, and armed forces’ uniforms. It was not about what might be true, but about what could be seen as disloyal. Anti-war speech was considered disloyal and therefore seditious. People were unable to openly question why the United States was in the war or speak out against it without risking imprisonment or hefty fines.

Today we see the Sedition Act as a violation of the First Amendment of the U.S. Constitution, which promises protections for free speech. Despite this, the Supreme Court upheld the act.



Poets published work that put the inhumanity and suffering of the war on full display. No heroic charges were celebrated in their stanzas.


'''

== 一战后, 美国经济的繁荣

The United States did not suffer the physical devastation of war that the other Allies did. It emerged from the conflict in a position of economic power, a creditor nation to be repaid for its wartime loans to Britain and France. Thus, the 1920s were a decade of prosperity for the country.


'''

==  为了解决大萧条问题, 罗斯福施行新政

In the United States, new president Franklin D. Roosevelt unveiled a comprehensive reform plan in 1933. This New Deal was designed to restore faith in the banking system, create work-relief programs to put the unemployed to work, increase the bargaining and consumer power of industrial workers, and provide an overall enhanced quality of life.


'''

===  保障储户在银行中的存款安全 → 联邦存款保险公司 (FDIC)

Overhauls to the banking system included more regulations on U.S. banks and regular audit controls. The creation of the Federal Deposit Insurance Corporation (FDIC) in 1933 meant that depositors could feel their money on deposit was safe.


The Federal Deposit Insurance Corporation (FDIC) was created in 1933 to insure depositor monies in banks. Originally it covered $5,000 per depositor, but it now covers $250,000 per depositor.


'''

===  建立”社保养老”工程

The United States also adopted programs that already existed elsewhere. For example, the Social Security Administration was created in 1935 to provide an old-age pension program for the country. Germany had such a program for several decades, and Britain had already enacted many programs as part of its welfare state that the United States was slow to adopt.


The Social Security program was begun in 1935 to oversee Old-Age and Survivors Insurance (OASI), unemployment insurance, and aid to families.


'''

=== 最低工资

The federal minimum wage was established in 1938 as an increase over the minimum wages in many industries, though some workers, such as domestic workers, were left out.



'''

==  二战前, 美国执行<中立法案>, 禁止向交战国出口武器, 和提供贷款

In the 1930s, the United States wanted to insulate itself from conflicts in the rest of the world. Aroused by dramatic hearings into the causes of the country’s entry into World War I, Congress passed the Neutrality Acts in 1935, 1936, and 1937, forbidding the export of arms and the making of loans to belligerent nations. These acts effectively handcuffed the government.

President Franklin D. Roosevelt, who took office in 1933 just two months after Hitler became chancellor of Germany, was prevented from rendering much assistance to China against Japan, to Ethiopia against Italy, or to Republican Spain against fascist General Franco. But the 1937 Neutrality Act granted Roosevelt a little leeway. The United States could render nonmilitary assistance such as oil to a belligerent nation if that nation could both pay cash for the goods and carry them home itself.



'''

==  为防备二战, 而扩充军备

To beef up the defenses of the United States, Roosevelt pressed Congress to approve a two-ocean navy in 1938 and began to funnel aid to Britain and China within the confines of what was allowable.


'''

==  国会废除<中立法案>, 允许他国以”现购自运”的方式, 购买美国军事装备. (1939.11)

As the world watched Hitler annex Czechoslovakia and then invade Poland, Roosevelt sought to offer more substantial military assistance to Britain and France.
After much debate, in November 1939 Congress repealed provisions of earlier Neutrality Acts and authorized trade in military hardware on a cash-and-carry basis.


'''

==  租借法案 (1941.3)

In one ten-day period in July 1940, German submarines sank eleven British destroyers, prompting the British prime minister, Winston Churchill, to appeal to the United States for help. Liberally interpreting the Neutrality Act of 1939, Roosevelt agreed to exchange fifty World War I–era destroyers for lease rights at British naval bases in Newfoundland and the Caribbean.

In March 1941, the president persuaded Congress to approve the Lend-Lease Act, which allowed the government to “sell, transfer title to, exchange, lease, lend or otherwise dispose of, to any such government any defense article.” The United States could now provide these materials to any country deemed vital to its own defense. It was a way to aid those countries already fighting but without taking direct military action.



The Lend-Lease program sent material and foodstuffs to forty Allied nations, mainly Britain and the Soviet Union. Government efforts to spur production led to nearly full employment in many nations. In the United States, unemployment dropped from 15 percent in 1939 to 1 percent in 1943 as seventeen million new civilian jobs were created.


'''

== 曼哈顿计划 (1942.8) → 研究原子弹 (1945.7月成功)

In December 1938, German physicists Otto Hahn and Fritz Strassmann accidentally split atoms and discovered nuclear fission.


By the late 1930s, British and other scientists became convinced that an atomic bomb was possible, and teams of physicists, some of them refugees from Nazi Germany, assembled and began experiments with nuclear chain reactions, the catalysts of an atomic explosion.

In August 1942, the U.S. government boosted this effort with its top-secret Manhattan Project. At dozens of sites across the United States, from Los Alamos in New Mexico to Oak Ridge in Tennessee and Hanford in Washington State, 600,000 workers embarked on a frenetic race to build the world’s first atomic bomb.



Meanwhile, Germany and Japan were also attempting to build their own.

The German effort was hindered by technical and other problems. For example, top German scientists had fled Germany, and some were assisting the Manhattan Project. Further, Hitler preferred to support the development of V2 bombers for the air war with England rather than an atomic bomb.

In 1941, the Japanese commissioned physicist Yoshio Nishina to begin working on an atomic bomb, calling the project Ni-Go. But lacking any information shared by the Germans and suffering under successful U.S. air raids, the project did not make much progress.




Eventually, in July 1945, the Manhattan Project bore fruit, and a bomb was successfully detonated in the Trinity Test at Alamogordo, New Mexico. William L. Laurence, the official historian of the project, described this first successful trial of an atomic weapon: "On that moment hung eternity. Time stood still. Space contracted to a pinpoint. It was as though the earth had opened and the skies split. One felt as though they had been privileged to witness the Birth of the World—to be present at the moment of Creation when the Lord Said: Let there be light."

President Roosevelt had died suddenly in April 1945, succeeded by Vice President Harry S. Truman. It fell to Truman to decide whether to use the new weapon or not.



Truman had known little about the Manhattan Project before becoming president and now relied on the advice of his experts.


'''

=== 科学家"对核武器对人类意味着什么"的观点

When it became clear that the Manhattan Project had been successful, a panel of scientists led by Robert Oppenheimer, the project’s head, made recommendations about the weapon they had created in a report dated June 16, 1945.


The opinions of our scientific colleagues on the initial use of these weapons are not unanimous. We can propose no technical demonstration likely to bring an end to the war.


The war has to be brought speedily to a successful conclusion and attacks by atomic bombs may very well be an effective method of warfare. We feel, however, that such attacks on Japan could not be justified, at least not unless the terms which will be imposed after the war on Japan were made public in detail and Japan were given an opportunity to surrender.

If Japan still refused to surrender our nation might then, in certain circumstances, find itself forced to resort to the use of atomic bombs. Such a step, however, ought not to be made at any time without seriously considering the moral responsibilities which are involved.



The atomic bombs at our disposal represent only the first step in this direction, and there is almost no limit to the destructive power which will become available in the course of their future development. Thus a nation which sets the precedent of using these newly liberated forces of nature for purposes of destruction may have to bear the responsibility of opening the door to an era of devastation on an unimaginable scale.

If after this war a situation is allowed to develop in the world which permits rival powers to be in uncontrolled possession of these new means of destruction, the cities of the United States as well as the cities of other nations will be in continuous danger of sudden annihilation.



The added material strength which this lead gives to the United States brings with it the obligation of restraint and if we were to violate this obligation our moral position would be weakened in the eyes of the world and in our own eyes. It would then be more difficult for us to live up to our responsibility of bringing the unloosened forces of destruction under control.


If you had been President Truman, would you have ordered the bomb to be dropped? Why or why not?


'''