
= 重要地理交通基建建设=
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== (埃及) 苏伊士运河

Britain’s second area of interest in Africa was Egypt, an excellent source of cotton for its textile mills. The possibility of building a canal across the Isthmus of Suez, which divided Asia from Africa, had intrigued Europeans since the fifteenth century. Linking the Mediterranean and Red Seas would allow ships to reach the Indian and Pacific Oceans without sailing around the tip of Africa, greatly easing trade with South and East Asia. Construction began in 1859, and the Suez Canal opened to shipping in 1869.




Britain had initially opposed the canal. It threatened British domination over the main water route to Asia, which passed the British Cape Colony, and it made its prized colony of India more accessible —and more vulnerable. Britain’s attitude changed, however.

In 1875, unable to pay his debts, Ismail Pasha sold Egypt’s shares in the Suez Canal to Britain. He was also forced to allow British and French officials to manage Egypt’s financial affairs.


'''