= 1759
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 454.
This is English as a Second Language Podcast’s English Café episode 454. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide, an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
Today we’re going to talk about a movie called The Shawshank Redemption, as well as one of the largest office buildings in the world, the Pentagon. And, as always, we’ll answer a few of the questions you have sent to us. Let’s get started.
The Shawshank Redemption is a movie about a man named Andy Dufresne, who goes to prison for killing his wife and her lover. It was released, or first shown, in the theaters in 1994, and was based on Stephen King’s 1982 short story, “Rita Hayworth and the Shawshank Redemption.” The movie is set, or takes place, in a prison in the state of Maine, which is located in the northeastern part of the United States. The name of the prison is Shawshank (Shawshank). Shawshank is not a real prison, just the name of the prison in the story.
The Shawshank Redemption is the story of how two men, Andy and his friend Red, are able to find redemption while they are in prison for committing murder. “Redemption” (redemption) is when someone does something very bad or is a bad person, and then changes and begins to live a better life and be a good person. The movie starred Tim Robbins as Andy and Morgan Freeman as the “narrator” of the story, the person who tells the story, named Red.
The film begins in 1947 with Andy being convicted – or found guilty of committing a crime – of murdering his wife and her lover. Andy, a banker (someone who works at a bank) says that he is innocent and did not kill his wife or her lover. He is found guilty anyway and told that he must serve two life sentences. The term “sentence” here means the amount of time served in prison. Of course, we also use “sentence” in grammar to describe the expression of a complete thought with a subject and a verb, but here it means the amount of time you have to spend in prison.
So, Andy has to stay in prison for two lifetimes. This is obviously not possible. So it really means that he has to stay in prison for the rest of his life until he dies, similar to what marriage is for many people. Giving someone two life sentences is more to show that what they did was very wrong. Andy is sent to Shawshank Prison, which is known as the place where the worst criminals go.
When Andy arrives at Shawshank, most people – including another prisoner, named Red – don’t think that he will survive very long, that he will be able to last very long. Andy is clearly a wealthy man, a man with a lot of money, who is used to a comfortable life away from criminals. What they don’t know, however, is how strong Andy is psychologically and emotionally, and how smart he is. Andy hopes and believes that he will get out of prison. He uses his intelligence to stay alive and to be as comfortable as possible.
Andy makes friends with Red, who has been imprisoned for most of his life. Red murdered someone when he was a young man and was sent to Shawshank in 1927. He was up for parole in 1947 and 1957, but was not allowed to leave prison. When we say someone is “up for parole” (parole), we mean that he has a chance of being released from prison early because of good behavior. Certain prisoners can be released, or let out of prison, before the end of their sentence if they have behaved well in prison – if they have not caused any more problems in prison.
But Red is denied parole. He is unable to leave prison. Another word for prisoner is “inmate” (inmate). In the movie, when an inmate wants to get something in prison, he asks Red to get it for him. Andy wants to get a rock hammer, which is a very small tool that is used to break rocks. He says that he wants to use it to carve rocks in his free time. He asks Red to get him the rock hammer. Red does.
Later, Andy asks Red to get him a poster of a beautiful woman to hang on the wall of his prison cell – the place where he stays in prison. Red does this as well. He first gets him a picture of a famous movie actress during this time, Rita Hayworth. That’s why the original Stephen King short story is called “Rita Hayworth and the Shawshank Redemption.”
After a few years, the guards learned that Andy knows a lot about investing money and saving money on taxes. The word “taxes” refers to the amount of money that each person must pay the government every year. The guards begin to ask Andy for help, and soon Andy is giving advice to all the guards about how they can save money. The “warden” (warden) – the person in charge of the prison – learns that Andy is helping the guards and decides that he’d like Andy to help him as well.
He sends Andy to work in the prison library and sets up a place in the library for Andy to help the guards. Andy decides he wants to build a better library for the prisoners. He begins to write letters to the government of the state of Maine, asking them for money and donated books. After six years of letters, some money and donations finally begin to arrive. Andy builds a big library for the prisoners and begins helping some of them study to get their high school diploma. A “diploma” (diploma) is the paper a student receives when he or she graduates, or finishes school.
Andy helps a number of prisoners, including one named Tommy, who arrived at the prison in 1955. Now, Tommy is a young man who has been in and out of prison for most of his life. When he hears Andy’s story, he tells Red and the other prisoners that he knows someone in a different prison who said that he was the person who murdered Andy’s wife. Andy finds out that it might be possible to prove that he is innocent, that he didn’t murder his wife, and so he asks the warden to help him.
The warden says he will not help Andy, and Andy seems to lose all hope. What happens next surprises everyone at the prison. I won’t tell you what it is, but the prisoners learn that Andy was right when he said, “Hope is a good thing, maybe the best of things, and no good thing ever dies.” There are several well-known lines, or sentences, from the movie. One of my favorites is by Red near the end of the movie, where he says that you have to “get busy living or get busy dying.”
Andy seemed like an unlikely person to survive in prison, especially one as hard as Shawshank. However, Andy changed many of the people that he met in prison, especially Red. He helped Red find redemption and become a better man by showing him that the world offered him so many choices, and just because his body was imprisoned didn’t mean that his mind had to be as well.
Shawshank Redemption was nominated for seven Academy Awards, including the award for best picture and best actor for Morgan Freeman, who played Red. The movie didn’t win any awards at the Academy Awards, however it won other awards around the world, showing how well-loved the movie was worldwide. You can see the movie on television here in the United States. It seems to be on almost weekly on some channel or another. I’ve seen it probably 15 or 20 times. I really like it and think you will too, if you have not seen it already.
Let’s turn now to the largest office building in the world, the Pentagon. The Pentagon (Pentagon) is located in Arlington, Virginia, just across the Potomac River from Washington, D.C., our nation’s capital. It is a five-sided building that provides the offices for the U.S. Department of Defense, as well as for many members of the United States military, including the Navy, the Army and the Air Force.
Until 1941, the United States War Department – which later changed its name to the Department of Defense – had offices in 17 different buildings all around Washington, D.C. President Franklin D. Roosevelt wanted all the members of the War Department to be in one office building so that they could communicate with each other better. He asked people to design a building that could “house” (house), or provides space for, the department.
At first he wanted the building to have no windows, so that it would be really safe. He was told that this didn’t make sense. So, he agreed that the building could have windows. Eventually he chose a design for the building as a geometric pentagon – a building with five sides – and that’s why the building is called the Pentagon.
Some people – like the chairman of the Commission of Fine Arts, whose job it was to give advice to the president about art and architecture projects – said that the building was a terrible idea and would take away from Washington D.C.’s beauty. Roosevelt ignored this and went ahead with the building.
The site where the building would be located was a swamp. A “swamp” (swamp) is an area of very wet ground that stays wet all the time because the water collects, or gathers, there. Because of this, builders brought in 5.5 million cubic yards – that’s 4.2 million cubic meters – of dirt to create a stable, or strong and unmoving, ground.
They also added more than 41,000 concrete pillars underneath the building to add support to the building. A “pillar” (pillar) is a tall, vertical (that is, going up and down) support used in a building like a really thick strong pole. If you have seen photographs of the famous ancient Greek building the Parthenon in Athens, you have seen its pillars that go all around the building.
The site, or place, of the Pentagon is next to Arlington National Cemetery, which is the place where members of the U.S. military, as well as some presidents, are buried – where their bodies are placed after they die. It was important that a tall building not block the view from the cemetery, so the Pentagon could be no taller than 77 feet, 3.5 inches – that’s 23.5 meters for those of you on the metric system.
Construction began on the Pentagon on September 11th, 1941. Three months later, the United States entered World War II. This made it even more important that the War Department have their office building completed. So, over 13,000 people worked day and night to finish the Pentagon. They completed the building in only 15 months, in January of 1943. The secretary of the War Department, the person who was in charge of the department, was able to move into his office in May of 1942, however, since that portion of the building was completed early.
When it was finished, the Pentagon was the largest office building in the world. It cost 83 million dollars to build and was 23 acres large, with a five-acre courtyard, or outdoor space, in the center of the building. It has enough office space for 25,000 people on the five floors of the building. There are 17 and a half miles of hallway in the Pentagon, but because of the design, a person can get from anywhere in the building in less than seven minutes.
In addition to office space, the Pentagon has cafeterias, snack bars, a shopping plaza, and bus, taxi, and metro stops. The Pentagon was supposed to become a hospital or other service building after World War II, but it was kept as the headquarters for the military because of the Cold War. The Cold War was the political tension between the United States and the then Soviet Union from the 1950s until the 1990s. Today, the Pentagon remains the headquarters for the Department of Defense and the Navy, Army, and Air Force.
Anyone interested in visiting the Pentagon is able to tour with a guide so long as they have registered in advance for a tour. On the hour-long tour, visitors will learn about the history and mission, or professional goals, of the Pentagon. They will also see the site where, on September 11, 2001, the Pentagon was attacked and 189 people lost their lives. The building has been repaired, but there is a memorial, or an area where an event or people are remembered, at the site of the attack.
Now let’s answer a few of your questions.
Our first question comes from Jose (Jose) Roberto (Roberto) in Brazil. Roberto – rather, Jose Roberto – wants to know the difference between “to go ahead” and “straight ahead.” “To go ahead” is a phrasal verb meaning to begin, to start, usually after getting permission.
For example, someone asks you if she can use your computer. If you think it’s okay, you would say, “Oh, sure – go ahead,” meaning “Yes, you may.” It means “to begin,” but there’s also a sense that there’s some permission involved, that you are asking the person – or rather, the person is asking you – and you are saying, “Yes, you can do that.”
“Straight ahead” is an expression you use when telling someone how to get to a certain place. It’s an expression we use when giving directions. “Straight ahead” means to go forward in the direction that you are facing right now – to go in a straight line without turning right or left.
If you ask someone where the bathroom is, and the person says, “Oh, it’s straight ahead,” he means you can walk straight – you won’t need to turn left or right – and you will find it will be right in front of you. If the person says it’s “on your right” or “on your left,” that means it’s not straight ahead. You have to turn either left or right to get there or to find it.
You can combine the verb “to go” with “straight ahead” when telling someone where they should walk or drive. If someone says, “You just go straight ahead,” he means you should move in that direction straight in front of you, not turning left or right. “Go ahead” isn’t related to giving directions, but rather to giving permission to someone in some activity.
Our second question comes from Mohammed (Mohammed) in San Diego, California. Mohammed’s question has to do with two words, “cheesy” (cheesy) and “quirky” (quirky). These are both adjectives describing something. Let’s start with “cheesy.” “Cheesy” is usually used to describe something that seems to involve too much emotion, often something that is what we might describe as “melodramatic” – something that seems to have too much sadness or too much sentiment, too much emotion.
If you describe a movie as being “cheesy,” you mean that the characters weren’t very believable. Their emotions expressed in the movie were not believable. It didn’t seem real. If you say a movie or a television show is cheesy, you’re criticizing that movie or television show. You’re saying it wasn’t of a very high quality.
The adjective “quirky” means strange or weird, but often in a good way. If you say the movie was “quirky,” you’re not criticizing the movie. You’re saying that it was strange. It was different. It was a little weird, but probably in a way that you enjoyed, or at least that didn’t bother you. “Quirky,” then, is either a neutral or positive way of describing some movie or some character or some book, whereas “cheesy” is always a negative adjective when you’re describing something.
Finally, David (David) in El Salvador wants to know the meaning of the expression he saw in a movie called Charlie and the Chocolate Factory. The expression was that someone seemed “a few quarters short of a buck.” “To be a few quarters short of a buck” means basically to be crazy, to be insane, not to be very smart, perhaps, or to not have emotional stability. Usually it just means a crazy person. If you say, “He’s a few quarters short of a buck,” you mean he’s a little nuts. He’s a little insane.
Why do we use this expression? Well a “buck” (buck) is an informal term for a dollar. One dollar is a “buck.” So, if someone pays 5,000 bucks for a car, that person has paid $5,000 dollars for a car. A “quarter” is 25 cents. It’s 25 percent – or a quarter – of a dollar. One dollar is 100 cents in the United States, and that would be the same as four quarters, each of which is worth 25 cents. The expression “to be short of” something, as in “a few quarters short of a buck,” means to be slightly less than or to have fewer than some number that you would normally have or that you would need.
We often use the expression “to be short of” something when you don’t have enough of something. “I’m a little short of cash today.” That means I don’t have very much money with me. I don’t have enough money for what I want to do or what I need to pay. To say someone is “a few quarters short of a buck” means they don’t have four quarters. They may have three quarters or two quarters or only one quarter, but not enough to equal a dollar – not enough to equal a buck.
You can think of the expression as meaning that the person doesn’t have enough to be considered, in this case, normal or sane. They somehow lack, or don’t have, what they need in order to be completely mentally competent or “sane,” we would say. The opposite of “insane” is “sane” (sane). “I’m saying my neighbor is insane. He’s a few quarters short of a buck.”
If you have a question or comment, go ahead and email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
redemption – when someone does something very bad or is a bad person but then changes and begins to live a good life and be a good person
* Yentzu lived a life of crime, but found redemption after her daughter was born.
to be convicted – to be found guilty of committing a crime
* Matthias was convicted of robbery after the jury saw him on the store’s security video taking money from the cash register.
sentence – the amount of time a person is required to spend in prison
* He received a sentence of 15 years for robbing the bank.
parole – being released from prison early because of good behavior, but still being required to follow certain rules for a period of time
* Mathias was offered parole after five years because he followed all of the rules in prison.
inmate – prisoner; a person in jail
* The inmates were allowed one hour of outdoor exercise each day before returning to their cells.
tax – the amount of money one pays the government based on how much money they or their business earns and what things or services they purchase
* Masha’s income taxes are quite high because she earns a lot of money as an attorney.
warden – the person in charge of running a prison; the person who manages a prison
* The warden of the prison made sure that the guards treated all prisoners fairly.
diploma – a piece of paper a student receives after he or she graduates or completes high school or college
* Many doctors hang their diplomas on the wall to show patients which medical school they attended.
swamp – an outdoor area of very wet ground that stays wet all the time because of its low location, causing water collect there
* When walking through a swamp, it’s important to wear rubber boots so that your feet don’t get wet.
stable – strong and unmoving; firm and not flimsy
* The table is not very stable because one of the legs is shorter than the others.
Cold War – the political tension between the United States and the former Soviet Union from the 1950s to the 1990s
* During the Cold War, many people were scared that either the Soviet Union or the United States would fire missiles at the other country.
mission – the professional goals of an organization or company
* The company said that its mission was to provide the safest and best quality cars for its customers.
to go ahead – to start or continue, often after getting permission
* A: Can I try riding your new bike?
B: Sure, go ahead.
straight ahead – toward the direction one is facing, moving forward and in a straight line, without turning
* You can see the church from here. It’s straight ahead, about a block down this street.
cheesy – involving too much emotion, often related to tenderness and sadness; sentimental; melodramatic; corny
* Lia’s friends thought Mike’s love letter was cheesy, but Lia thought it was romantic.
quirky – strange in a good way; weird but not unpleasant
* Do you like independent films with quirky characters or do you prefer mainstream films?
a few quarters short of a buck – crazy; insane; not mentally normal
* We always thought Moses was a few quarters short of a buck, but who knew he would spend all of his money buying 5,000 candy bars?
What Insiders Know
Oddly-Shaped Buildings in the U.S.
Every country has “unique” (not like any other) buildings that are easily “identifiable” (easy to recognize). Here are two examples of “oddly-shaped” (with a strange shape) buildings in the U.S.
The Kansas City Public Library (Kansas City, Kansas)
The Kansas City Public Library is located in “the heart of” (the center of) Kansas City and the building is designed to “resemble” (look like) books standing next to each other, like on a bookshelf. The citizens of the city were asked to pick the most highly influential books that represent their hometown, and those books became the focus of the building’s design. Those books include J.R.R. Tolkien’s The Lord of the Rings, E.B. White’s Charlotte’s Web, William Shakespeare’s play Romeo and Juliet, and many others. Those titles appear on the side of the building as “book spines” (the part of the book with the book’s name).
The Longaberger Company Headquarters (Newark, Ohio)
The Longaberger Company, famous for manufacturing “maple wood” (a type of light-colored wood) “baskets” (container to hold other things, with an open top) and other home products, has its headquarters in Newark, Ohio. Its building is designed to look like the company’s biggest-selling product called the “Medium Market Basket,” which is a “picnic basket” (basket made to hold a meal that will be eaten outdoors). The building has become a famous local “landmark” (building or structure that is easy to recognize and known to many people). The company’s founder, Dave Longaberger, wanted all of the Longaberger buildings to be shaped the same way, but only its headquarters was completed at the time of his death in 1999.