= 1756
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 451.
This is English as a Second Language Podcast’s English Café episode 451. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in Business and Daily English that you will enjoy, I think. You can also download the Learning Guide for this episode and every episode. The Learning Guide contains lots of additional information, including a complete transcript of this episode, vocabulary words, definitions, sample sentences, cultural notes, and a comprehension quiz on what you’re listening to now.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed. We’re going to listen to them and explain what they are talking about.
Today we’re going to talk about a somewhat or rather unusual topic for a Café: hair. We’re not just going to be talking about any hair, but what we call “facial hair” – beards and moustaches on men. Why? Well, you’ll find out, now, won’t you? Just keep listening. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is facial hair. “Facial” (facial) relates to your face, so “facial hair,” logically, is the hair that grows on your face. Normally when we talk about facial hair, we’re talking about the hair a man grows on his face on purpose, because he wants to grow the hair. It doesn’t sound like a very interesting topic, but as we’ll hear, there are people – especially here in the crazy city of Los Angeles – who think it is important and spend a lot of time thinking and talking about it.
We’ll begin by listening to one such crazy person – I mean, one very interesting person – by the name of Daniel Winter. Mr. Winter is a barber here in Los Angeles. A “barber” (barber) is a man who cuts other men’s hair. The more general term – for both men and women who cut people’s hair – popular nowadays is “stylist.” But “barber” usually refers to a man who only cuts men’s hair.
We’ll listen first as he talks about the growing popularity of facial hair among men in many large cities. Try to understand as much as you can, then we’ll go back and explain what he said. Let’s listen:
[recording]
“Bigger corporations, like huge companies that are geared more towards fashion, are now hiring models with beards and tattoos, going for a little bit more of an alternative look, and it’s really like starting to spill over into the general public.”
[end of recording]
Winter begins by talking about “bigger corporations” and “huge companies.” These would be businesses that have a lot of people working for them and/or making a lot of money. He says, “Bigger corporations, like” – that is – “huge companies that are geared more towards fashion, are now hiring models with beards and tattoos.” The expression “to be geared toward” something means to be focused on something, to be interested in this particular area. A company “geared more towards fashion” would be a company that sells things related to fashion, things such as clothing.
Normally when we talk about “fashion,” we’re referring to companies that make and sell clothing (dresses, pants, shirts, shoes) and jewelry (rings, necklaces, and so forth). Fashion companies typically hire, or give jobs to, models. A “model” is a person who wears the company’s clothing or jewelry and shows you what it looks like. Of course, models are always very beautiful – or, in speaking of men, we would say very “handsome” – because the company wants you to think that if you wear their clothing, you’ll look like that, too.
For men’s clothing, according to Mr. Winter – who, in addition to being a barber, is apparently an expert on employment in the fashion business – companies are hiring models with “beards and tattoos.” A “beard” (beard) is facial hair that grows over a man’s cheeks (the sides of his face) and chin (the bottom of his face, below his mouth). A “tattoo” (tattoo) is a permanent drawing on your skin, made by putting ink into the skin with a small needle. Although he doesn’t mention it, the other common form of facial hair is a “moustache” (moustache). A “moustache” is hair between your nose and your mouth.
In the past, it would be unusual to see models with beards and tattoos, but our expert, Mr. Winter, says that now companies in fashion are interested in models with beards and tattoos because they want to have “more of an alternative look.” In this context, the word “alternative” (alternative) refers to a way of dressing and acting that is different from the “normal” or typical person in that society or culture. As an adjective, it is used to refer to anything that is not typical or normal or usual. Beards and tattoos are, I guess, popular in what people think of as alternative styles of dressing and such, and companies are now hiring models to reflect that.
Winter says that those alternative styles, and particularly having beards and tattoos, are “starting to spill over into the general public.” Normally we use that phrase “to spill over” when we’re talking about liquids. If you have a large container that’s full of water and you start pouring the water into a smaller container, that smaller container will fill up, and if you continue to pour water into it, the water will spill over – the water won’t have anywhere else to go, so it will spill over the edges, outside of the container.
Here Mr. Winter is using that phrase to describe how beards and tattoos are spilling over from alternative fashion into the general public. People who don’t necessarily think of themselves as alternative are now becoming more interested in beards and tattoos. Well, I’m part of the general public, and I’m not interested in wearing a beard or getting a tattoo, but I guess Mr. Winter is talking about somebody else. In any case, let’s listen to Mr. Winter once again.
[recording]
“Bigger corporations, like huge companies that are geared more towards fashion, are now hiring models with beards and tattoos, going for a little bit more of an alternative look, and it’s really like starting to spill over into the general public.”
[end of recording]
Mr. Winter apparently studied history, literature, and anthropology as part of his beauty school studies, because he will now tell us why facial hair is so popular and the historical roots of this popularity. Do tell us, Mr. Winter!
[recording]
“Facial hair was associated with masculinity, sexual vitality, and overall awesomeness. You look at Greek mythology, and almost every god had some form of facial hair, whether it had been a full beard or some sort of goatee.”
[end of recording]
Professor Winter says that historically – in the past – facial hair was associated with “masculinity, sexual vitality, and overall awesomeness.” Well, quite an analysis. Let’s figure out what he means here. “Masculinity” (masculinity) refers to all the characteristics of being male, of being a man. Masculinity usually means being strong and aggressive, whereas “femininity” (femininity) refers to the characteristics of being female or a woman, usually meaning being soft and beautiful.
So beards are, of course, associated with masculinity because in general, men can grow facial hair and women do not, although of course there are some women with facial hair – but we won’t talk about that here. The professor then says that facial hair is also associated with sexual vitality. “Sexual vitality” (vitality) is sexual health and strength, I guess.
And he says facial hair is associated with – and this is my favorite part of his lecture – an “overall awesomeness.” “Awesome” (awesome) is the current word in English for what we might have described in previous generations as “cool” or “hip” or perhaps “rad.” If you say, “That was awesome!” you mean that was wonderful, that was great. You can even add a “totally,” so you get something that is “totally awesome.” “Awesomeness,” which is not a common term, just means something that is really, really great.
Winter, not tired yet of showing us with his deep knowledge of world culture, then says that we should consider Greek mythology in thinking about facial hair. Why? Well, says the good barber, the stories and myths of ancient Greece included many gods with – you guessed it! – facial hair. He says that almost every god, every powerful being in Greek mythology, had some form of facial hair.
According to Winter, this facial hair could be a full beard or a type of goatee. A “goatee” (goatee) is a small, sometimes pointed area of hair just on a man’s chin. A beard usually covers most of the face, but a goatee is hair just on the chin. It has that name because a goatee looks a little bit like the pointed hair found on the chin of a goat, a kind of animal.
Let’s listen to Dr. Winter one more time.
[recording]
“Facial hair was associated with masculinity, sexual vitality, and overall awesomeness. You look at Greek mythology, and almost every god had some form of facial hair, whether it had been a full beard or some sort of goatee.”
[end of recording]
Finally, let’s get a woman’s perspective, or opinion, on all this talk about beards and moustaches. We’re going to hear from Alana Beck, who co-founded, or began along with some other people, something called the L.A. Facial Hair Society.
The word “society” here just means group or organization. It is rather an old-fashioned word nowadays, but you still see it in the names of some organizations, such as the American Cancer Society or the National Geographic Society. The L.A. Facial Hair Society is trying to create a community here in Los Angeles for people who like facial hair, because what better way to make friends than by meeting with other people who like beards and moustaches?
Let’s listen to Lana, a person with perhaps just a little bit too much time on her hands. That expression, “to have too much time on your hands,” means that you aren’t busy enough and are therefore doing things that are unnecessary or silly. Lana has done both. But, okay – let’s hear what she has to say anyway.
[recording]
“I only date guys that have beards. I don’t do moustaches. There’s a manliness to it that’s very attractive.”
[end of recording]
Ms. Beck says that she “dates,” or sees romantically, only men with beards. If a man doesn’t have a beard, she isn’t interested in dating him, so I guess me and Lana aren’t going to go out on a date, a fact that will make my wife happy. Beck – no relation, I think, to the singer Beck – says that she doesn’t “do” moustaches, meaning she won’t date anyone with a moustache.
Beck says that facial hair has a certain manliness. “Manliness” (manliness) is a word like masculinity. It refers to the characteristics of being a man, of being strong and powerful. She says that because facial hair is associated with manliness, it is very attractive to her.
Let’s listen one more time as she explains.
[recording]
“I only date guys that have beards. I don’t do moustaches. There’s a manliness to it that’s very attractive.”
[end of recording]
So now you know everything you need to know about facial hair in Los Angeles and probably a good deal, or a lot, of what you don’t need to know.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Peter (Peter) in an unknown country, a mysterious country, a secret country. Peter wants to know the difference between “sin” and “transgression.” “Sin” (sin) is an act that is considered wrong according to some religious point of view. In the most popular religion in the United States, Christianity, a sin is doing something that is against the law or the desires of the Christian God.
Other religions also have this sense of sin. The word we typically use with “sin” is “commit.” We talk about someone “committing a sin.” We don’t normally say, “doing a sin” or “making a sin.” We use that very special verb, “to commit.” “Transgression” (transgression) is any act that breaks, or goes against, a law or a rule of any kind. A transgression isn’t necessarily breaking a religious law. It’s breaking any kind of law or rule.
The word “transgression” can also be used in a religious context, but it’s a more general term to describe when someone breaks a rule, when someone does something wrong. Sometimes a “transgression” is an act that won’t get you arrested. It’s not something against the law. It’s something against the common custom, the way people typically act in a certain culture or society.
The word “sin,” then, is usually connected with breaking some sort of moral or religious law. “Transgression” is a more general term meaning breaking or going against any rule or law.
Our second question is from Pedro (Pedro) in Brazil. Pedro has a question about the words “totally” and “definitely.” We mentioned a little earlier about “totally” in the expression “totally awesome,” so this is a good time to talk a little bit more about the meanings of the word “totally.”
“Totally” can mean completely, absolutely – “to a very full extent,” we might say. For example, “The house was totally destroyed by fire.” The fire destroyed the house completely, totally, we could say. It’s also used, as I pointed out earlier, to mean something like “very” or “a lot.” “This is totally awesome, dude.” This is really great, man.
“Totally” is sometimes used as a response when someone says something that you agree with completely. “We’re going to go to the beach, and we’re going to have a good time, and it’s going to be fun.” And your friend says, “Yeah, man, totally.” It’s an informal use that is more common among younger people, but you will hear people say that.
The other word Pedro asks about is “definitely” (definitely). “Definitely” means without a doubt – when there is no doubt, no question, about something. “We are definitely going to the beach today.” There’s no doubt about it. It is absolutely certain. You could also say, in that same sentence, “We are totally going to go to the beach.” However, it’s much more informal and might even be said as sort of a joke.
Sometimes old people like me use language that is used by teenagers to be a little bit humorous, to try to be a little funny. “I am totally going to go and eat as much as I can at the buffet.” A “buffet” is a restaurant where you can eat as much food as you want for the same price. “I am totally going to do that.” It means really the same as “I am definitely going to do that.” I am absolutely going to do that.
Unlike the use of “totally” in that situation, however, “definitely” is more common and a little bit more formal. “Definitely” can also be used as a response to a question when you want to say yes. “Do you want to go with me to the movie?” “Definitely” – meaning “Yes, I definitely want to go, no doubt about it.”
Finally, Valerie (Valerie) in Singapore wants to know about the use of the word “ever,” especially in the expression, “I ever go there.” “Ever” means at any time. It can also mean “at all.” It’s typically used for emphasis. Often, you can delete the word “ever,” and the sentence means the same thing.
For example, “Have you been to this restaurant?” “Have you ever been to this restaurant?” In the second sentence, “ever” is adding some emphasis, almost as though you were making sure that the person understood “at any time in the past.” “Even once,” you might also say. “Have you ever been in love?” Even once in your life, have you been in love? Once again, it’s more for emphasis than it is for changing the meaning of the sentence or, in that case, the question.
Is it possible, then, to say something like, “I ever go there?” Well, in American English, no. In American English, we would not say “I ever go there” to mean I go there a lot. “Ever” doesn’t mean often or a lot in American English. If we wanted to say, “I often go there,” we would say, “I often go there” or “I go there often.” We would not say, “I go there ever” or “I ever go there” in American English. Again, in Englishes in other countries that have different influences, that might be acceptable, but it is not something we would say in the United States, typically.
There’s another expression with “ever,” which is “as ever.” “As ever” means as always, or simply, “always.” “You are looking beautiful tonight, my beautiful wife, as ever.” “As ever” means you always look beautiful. It’s expected that you are beautiful. You look that way all the time. “She’s as beautiful as ever.” Just as beautiful as she was 10 years ago or 20 years ago. That’s another use of the word “ever” when combined with the word “as.”
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. Please keep in mind, or remember, that we get lots and lots of emails every week, and that sometimes it takes a long time for us to answer your question, and unfortunately, some questions we don’t have time to answer. But we’ll do our best to answer as many as we can.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
to be geared more towards – to be aimed at something; to be interested in something; to intend to do something
* Justin initially studied chemistry, but now he’s geared more towards civil engineering.
fashion – the industry based on how people use clothing, shoes, and jewelry to express themselves and influence how they are viewed by others
* Which skirt length was most popular in fashion in the 1980s?
beard – facial hair that grows over a man’s cheeks and chin
* How often do you trim your beard?
tattoo – a permanent drawing on one’s skin, made by putting ink into the skin with a small needle
* Greg got a tattoo with the name of his girlfriend, but then they broke up and he regretted his decision.
alternative – a lifestyle and a subculture where people do things that aren’t commonly accepted in society
* Iago has embraced the alternative lifestyle. He has bright pink hair and pierced ears, and he likes doing things that surprise other people.
to spill over – to reach a point where something cannot be contained and moves into another area, affecting other people or things
* Passengers affected by the flight cancellations are spilling over into other airlines, creating significant delays.
masculinity – all the characteristics of being male (a man); manliness
* The other guys are questioning Sam’s masculinity, just because he isn’t very assertive.
sexual vitality – sexual health and strength, the ability to engage in sexual activities and be interested in it
* When Blake got older, he decided to see his doctor about his diminishing sexual vitality.
Greek mythology – the stories and teachings of ancient Greece, whose people believed that there were many gods with special powers that affected humans in their daily life
* In Greek mythology, Zeus is the god of sky and thunder.
facial hair – hair that grows on the face, especially a man’s face
* Karen doesn’t like kissing men with facial hair, because it tickles.
goatee – a small, sometimes pointed patch of hair only on a man’s chin
* Damian spends a lot of time trimming and shaping his goatee.
mustache – a strip of facial hair only on the upper lip, between the lip and the nose
* He has a long mustache that he twirls into a curve at each end.
manliness – all the characteristics of being male (a man); manliness
* Do you think a man can cry, but still demonstrate manliness?
sin – an act or behavior that is considered wrong according to the Christian religion; an immoral act
* It is a sin to steal or to murder.
transgression – an act or behavior that goes against a law or rule; an offense
* All students need to know the rules and the consequences of any transgressions.
totally – completely; absolutely; to a full extent
* I totally understand what you mean when you say that you’re tired of working in a job that you don’t enjoy. I feel the same way.
definitely – without doubt; certainly
* Will you definitely be coming to watch the game tomorrow, or is it still possible that you’ll be going out of town?
What Insiders Know
Facial Hair Competitions
With the growing interest in facial hair, some men have begun to compete for the best beards and mustaches. Most competitions have three main categories (mustaches, partial beard, and full beard), and subcategories for specific types of facial hair within each of those categories. Many competitions also have a “freestyle” category for facial hair that is unusual and does not fit into traditional categories.
The World Beard and Moustache Championships is an international competition that has been attracting men from around the world since 1990. They compete in many different categories reflecting different lengths and styles of facial hair. Many of the competitors use “hair styling products” (gels, mousses, and sprays to help hair maintain a certain shape and style) to “sculpt” (change the shape of) their facial hair.
The Mr. Fur Face Contest is the “longest running” (happening for the longest period of time) beard contest in the United States. It has been held in Anchorage, Alaska each year since 1950. The winners receive “titles” (names and honors) such as Mr. Brown Bear for a brown beard, Mr. Polar Bear for a white beard, and Mr. Soup Strainer for a mustache. A “strainer” is a “colander” or a bowl that works like a filter, letting a liquid through but not letting solids through, much like a mustache could filter soup.
An organization named Beard Team USA organizes the annual National Beard and Moustache Championships and represents the United States at international beard and moustache competitions. Membership is free and “open to anyone” (anyone can join the organization).