= 1770
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 465.
This is English as a Second Language Podcast’s English Café episode 465. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. The Learning Guide gives you a complete transcript of everything we say, as well as vocabulary words, definitions, sample sentences, cultural notes, and a whole lot more.
On this Café, we’re going to talk about a popular folk song called “If I Had a Hammer” that was written in the 1940s, but became extremely popular in the 1960s. We’re also going to talk about what a “social worker” does in the U.S. and how to become one. And, as always, we’ll answer a few of your questions. Let’s get started.
Our first topic today is a famous popular song in the U.S. In 1949, a singer and songwriter named Pete Seeger wrote a song with the title “If I Had a Hammer.” He wrote it with another musician by the name of Lee Hays. Seeger and Hays were part of a band called the Weavers. Seeger was an incredible songwriter, especially of folk music. A “folk (folk) song” is a song that usually has a pretty simple or easy tune, or music and words, but that often has a very important meaning. When I say “tune” (tune), I’m talking about the music that goes along with the song’s words.
Sometimes we use the term “folk songs” to refer to the traditional songs of a country’s culture, songs that may have been sung for hundreds of years in that culture. The term can also refer to a more modern style of music in which the songs are about problems in today’s culture or society. That’s what Pete Seeger’s folk songs are mostly about – problems that exist in the world right now.
In 1949, when Seeger and Hays wrote “If I Had a Hammer,” one problem in American society, at least according to the songwriters, was related to labor rights. “Labor” (labor) refers to work or working. So, “labor rights” is the idea that all workers should be treated in a fair way and get a just, or fair, amount of money for their work. Labor rights also include the idea of working a reasonable number of hours each week. “Reasonable” is another word for fair.
What exactly is fair and reasonable when it comes to labor rights? Well, that depends on who you are, of course. In the 1930s and 1940s in the U.S., there were a lot of laws that were passed by the government that were designed to protect workers so that they not only were not injured or hurt, but that they had fair wages and fair working conditions.
In the song “If I Had a Hammer,” Seeger and Hays talk about tools that workers used in their jobs, such as a hammer and a bell. A “tool” is something you use to do something else with. You could talk about a software program as being a tool to help you do your work. Here we’re talking about tools that are used in building things or tools that are used in some other profession.
The tools that Seeger and Hays talked about were a hammer and a bell. A “hammer” is what you use to hit nails with. “Nails” are the small little pieces of metal that you hit with the hammer, usually to put them into wood or other kinds of material when you are building something. A “bell” is an object that makes a sound something like this:
[sound of a bell]
That’s a bell.
The song “If I Had a Hammer” used the image of these simple tools to talk about greater or more important problems in American society. “If I Had a Hammer” was, I guess, what we would term “moderately successful” for this band called the Weavers. When I say “moderately successful,” I mean it was popular, but not the most popular song in the country. However, in 1962, another group, this one called Peter, Paul and Mary, re-recorded, or recorded this song again. When they released the song, or began to sell it, their version of the song became a huge hit. It became really successful, very popular.
Part of the reason for this was that in 1962, the Civil Rights Movement was beginning to become more important in American politics. The Civil Rights Movement was an effort that people made to get the same protection for African Americans and other minorities as white people had in society. You’ve probably heard of the Reverend Dr. Martin Luther King Jr., who was one of the most important leaders of this Civil Rights Movement.
Because of what was going on at the time, the lyrics, or words, to the song took a whole new meaning for people. They meant something different, perhaps, than what Seeger and Hays had written them to mean. Let’s take a look at the lyrics now and see how they related to the ideas of the Civil Rights movement. The first part of the song goes:
If I had a hammer,
I’d hammer in the morning,
I’d hammer in the evening,
All over this land,
I’d hammer out danger,
I’d hammer out a warning,
I’d hammer out love between
my brothers and my sisters,
All over this land.
. . . and so on. Now, what does all that mean? Well, the first verse, or part of the song, talks about a hammer, which as we just mentioned is used to hit nails by someone who is building things. The person in the song is going to use this hammer “all over this land,” meaning everywhere in the country. But the second verse of the song uses this phrasal verb “to hammer out.” Here things get a little confusing. The writers of the song use this verb to mean a couple of different things.
The first definition of the phrasal verb “to hammer out” is related to the idea of changing something or of getting rid of something you don’t want. We use the verb “to hammer out” when we want to get rid of what we call a “dent” in a piece of metal. A dent is like a bump or curve in a piece of metal. For example, if you drive a car, and another car hits the side of your car – the outside of your car – the outside of your car, which is made of metal, will probably get a dent in it. When you need to get rid of that dent, that damage, to straighten out the metal or to change its shape, you have to “hammer out” the dent.
The idea is that by hitting the metal, you are changing the shape or form of something. You can see how this use of the verb is related more generally to the idea of change. In fact, we often use now the phrasal verb “to hammer out” to mean to come to an agreement – to discuss a difficult issue until we are able to agree on something. We’re getting, if you will, rid of our differences, or “hammering out” our differences, so that we can come to an agreement.
In the song “If I Had a Hammer,” you hear about hammering out not disagreements, but danger. “Danger” (danger) is something that could hurt you, something that could harm you. We also hear about “hammering out love between my brothers and my sisters.” Both of these phrases seem to relate to the idea of changing the situation into something different, something better. We hammer out danger to get rid of danger, to no longer have that danger, and we hammer out love to change the situation so that now there is love.
So, it’s a little confusing because hammering out love really would probably mean getting rid of the problems that prevent us from having love. But then the song talks, even more confusingly, about hammering out a warning. This use of “hammer out” is a little more difficult to understand. It’s a little unclear even to me. Remember, though, that the words of a song are like those of a poem in that they’re used sometimes in new or uncommon ways.
“To hammer out a warning” seems to mean to communicate a warning. A “warning” (warning) is information you give someone that there is something that may hurt or harm him – that there is some danger coming. “To hammer out a warning” probably means, then, to let people know about something, to communicate something. In the 1960s, it became popular for people to use the expression “brothers and sisters” to talk about people of all different races and backgrounds – the idea that there should be only love and not hate between us.
The next two verses of the song use many of the same lines, but instead of a hammer, we have a bell.
If I had a bell,
I’d ring it in the morning,
I’d ring it in the evening,
All over this land,
I’d ring out danger,
I’d ring out a warning,
I’d ring out love between
my brothers and my sisters,
All over this land.
I need – I need a band, you know? I need, like, instruments behind me, right? Anyway, when you make a sound with a bell, we say that you “ring” the bell. So, when I do this with a bell:
[sound of a bell]
I’m “ringing” the bell. That’s the verb that we use. In this verse, we hear about “ringing a bell” in the morning and in the evening, “all over this land.” Just as we mentioned previously, “all over this land” is everywhere. Then we hear a phrasal verb “to ring out.” “To ring out” normally means to ring a bell very loudly in order to announce something to a large group of people, to communicate to a large group of people.
The song uses that common meaning of “to ring out,” when it talks about “ringing out a warning” and perhaps when it talks about “ringing out love,” but it also uses this phrasal verb in a way similar to the phrasal verb “to hammer out” – it uses it to mean “change” when it says “ring out danger.”
Up to this point, the lyrics of the song talk about what the singer would do if he or she had these tools. This person would help bring the society together by changing and/or letting people know about bad things like danger and good things like love. The song continues with the singer’s statement that this is not just an idea anymore. This is not just a dream. Instead, the singer says that we have these tools and that we can make our society a better place.
Well I got a hammer,
And I got a bell,
And I got a song to sing,
All over this land.
It’s the hammer of Justice,
It’s the bell of Freedom,
It’s the song about Love between
my brothers and my sisters,
All over this land.
Well, that’s not actually in the song, but it makes it sound better, I think. Anyway, back to the lyrics – the hammer is not actually a hammer that people have in their houses, in their tool boxes that they use for building things. No, this is a “hammer of Justice.” “Justice” (justice) means fairness, but it can also refer to the law, or more specifically, the court system in a country.
Remember, we’re talking about the Civil Rights Movement, and so the song is saying that the law exists to protect people from danger. The government is supposed to protect people. The law is also there to promote love and peace in society. The bell, once again like the hammer, is not a real bell. It’s the “bell of Freedom.” “Freedom” means, among other things, the ability to say what you’d like without someone interfering or stopping you – at least, that’s one possible idea for freedom.
The idea of freedom being rung out, as though with a bell, is most commonly heard in another popular American song, “My Country Tis of Thee.” “My Country Tis of Thee” talks about the United States as a free country. The lyrics of that song say that freedom rings out from every mountainside across the country. The connection of this song to the more traditional, older song “My Country Tis of Thee” is intentional – that is, Pete Seeger wanted people to make that connection. He wanted people to see that this was an American thing to do, a good thing to do.
“If I Had a Hammer” became the number 10 song on a list of the most popular songs in the U.S. in October of 1962. This was most certainly in great part because of how much the song related to one of the more important social issues of that time, the Civil Rights Movement. You can also find a version of the song, I’m sure, on YouTube or somewhere on the Internet. It’s a song that many Americans are still familiar with, at least Americans who can remember the 1960s and 70s, although it’s not as popular as it once was.
Let’s change topics now and talk briefly about a kind of career or work that some people do, not just in the U.S., but in other countries: social work. “Social work” refers to helping people solve certain kinds of problems in their lives, either because they have experienced some dramatic change in their life that they are unable to manage, or handle their problems, or more commonly because of problems in their family. Someone who works in the area of social work is called, logically, a “social worker.”
There are many different kinds of social workers in the U.S. Some social workers work specifically with children and families. One of their jobs is to protect children who may live in an unsafe home, a home where there perhaps is violence or other problems in the family, especially between one of the parents – the mother or the father – and his or her child. The government, in fact, may send a social worker to investigate if it thinks there is a problem, especially if it involves the physical safety of the child.
Social workers also sometimes help families find ways to get enough food and to have a place to live. Many times in American schools, there will be a social worker who works in the school to help children and their families who have trouble or who have perhaps difficulties at home. Other social workers help people who are sick learn how to deal with or handle their illnesses, and also to help them change things in their lives to make it easier for them to live with their illness.
They also help people who have family members in what is called a “hospice.” A “hospice” (hospice) is a special kind of medical care for someone who is dying and for whom there really isn’t anything the doctors can do. These social workers help the families deal with, or handle, their daily problems when one of the family members is in a hospice.
Yet another kind of social worker is called a “clinical social worker.” A clinical social worker works in a “clinic” (clinic), often, or a hospital. A clinic is like a small medical facility. Social workers, especially clinical social workers, often work with people who have mental illnesses or behavioral problems.
A “mental illness” is a medical problem that affects a person’s mind and emotions, not their physical body necessarily. A “behavioral problem” is a way of acting that is not thought to be normal or as a usual way of acting, and often these behavioral problems are caused by some sort of mental or emotional issue. Clinical social workers sometimes help these people with medicine in addition to giving them other kinds of help.
Because of the many different kinds of social workers out there, social workers can be found in many different places. They work, as I mentioned, in hospitals and schools and clinics, and often in government offices. Most jobs for social workers require that the person go to university or college and get at the very least what’s called a “bachelors degree in social work.” A bachelor’s degree usually takes four years to complete after high school.
During their studies, students learn a lot about the psychological part of people’s lives. “Psychological” refers to the person’s mind and emotions, and how their emotions and their mind affect their life, I guess you could say. Although it is possible to get a job with just a bachelor’s degree in social work, many social workers have a master’s degree. This is an additional two years, typically, of training that students have to complete after their bachelor’s degree.
In the master’s degree, as well as in the bachelor’s degree, there’s typically what’s called a “practicum” for the students. A “practicum” (practicum) is normally an unpaid job. You don’t get paid for doing it, but you’re working in a real office or an actual school or hospital, not only learning things about social work, but also actually trying to help the people you’re working with. It’s not just a situation for studying, it’s a situation for taking what you’ve learned and applying it to a specific situation.
People who get a masters degree in social work are also required to complete two years of what is called “supervised experience.” “Supervised experience” means they have to work for an organization where there is someone who can help them and make sure that they’re doing the right things. Each state has different requirements in order to get a social worker’s license, but all states have some sort of test that you have to take in order to get a license to work as a social worker.
Being a social worker requires a lot of patience. It requires someone who can really listen to people and who care about helping people, of course. People who are social workers say that it is a very rewarding job. In other words, they feel like they get a lot from their job even though it can often be very difficult.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Yoshiko (Yoshiko) in Japan. Yoshiko wants to know the difference between “to dismantle” and “to disassemble.” Both “to dismantle” (dismantle) and “to disassemble” (disassemble) mean to take something apart – to take a whole and break it down, if you will, into its parts.
“To dismantle” usually refers to some sort of machine, like the engine of your automobile. You can dismantle something. Sometimes we use “dismantle” specifically to refer to a situation where you’re taking it apart and you are not planning on putting it back together again. That’s one possible difference between “dismantle” and “disassemble.”
“To disassemble” is often used when you are talking about furniture or a toy for a child, for example. You may be disassembling it in order to fix it or in order to change it. So, you’re not just taking it apart and throwing it away; you’re disassembling it for some specific reason such as fixing it or changing it. Having said all that, many people use these two words interchangeably. I wouldn’t worry too much about the difference between “disassemble” and “dismantle” as long as you understand that it refers to taking something apart.
“Dismantle” might be used in a more general way to refer to stopping some sort of program. If someone says, “We’re going to dismantle this department in the company,” the person would be talking about changing it or breaking it apart, so that this person would work in a different department, and that person would work in another department, and so forth. So, you can sometimes use dismantle in a larger sense to talk about organizations or structures that aren’t necessarily physical.
Our next question comes from Lucelia in Brazil. Lucelia wants to know the difference between “guilt” (guilt) and “blame” (blame). “Guilt” is when you do something wrong and then you feel badly about it. If you hit someone, you may feel guilty later. “Guilt” is the noun. It’s the feeling or emotion of being sorry for what you did or feeling bad that you did something wrong or illegal or unethical.
“Blame” is different. “Blame” is when you assign responsibility to someone for something bad that went wrong. So, for example, if you kill someone, you will probably have guilt – you’ll feel bad about it. But you could also blame someone else for the fact that you killed somebody. You could say, “Well it’s not my fault, because my father wasn’t very nice to me, and I had all these emotional problems, and therefore I had to kill someone.” You’re blaming another person. You’re saying this other person is responsible for my problems.
You could blame someone for a traffic accident. If someone is driving too fast and they hit you, you could blame them for the problem. You’re saying that person is responsible for this problem. “Blame” is always used when talking about something bad that has happened. When we assign responsibility for that bad thing that has happened, we are “blaming” someone. “To blame” is the verb; the noun is “blame.”
One other common expression with “blame” is “to take the blame.” “To take the blame” is to accept responsibility for something bad that has happened, even though you may not have been the cause of it. You may take the blame in order to protect another person, for example.
Finally, Adrey (Adrey) in Russia wants to know the meaning of the expression “to cross the great divide.” “To cross” something is to go through or over something, such as a road or a river or even a mountain.
The expression “the great divide” (divide) refers to some important boundary, something that separates two places or two concepts or two ideas. In this expression, it refers to life and death. In other words, it refers to, if you will, the boundary – the line – between life and death. “To cross the great divide,” then, means basically to die, to go from being alive to being dead. You could say it’s a poetic way of saying that someone has died, although it might be used sarcastically, perhaps, to talk about someone who has died, if that’s possible, and I guess it is.
You can also use this expression when talking about important differences between two different groups. For example, men and women often think very differently about things. So, if you were to “cross the great divide,” you would be able somehow to understand how someone of the opposite sex thinks or acts. I don’t think that’s actually possible but, well, some people try.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
folk song – a traditional song that has a simple tune and words, but that often has an important meaning or tells a story
* John Denver sang many famous folk songs including, “Leaving on a Jet Plane.”
tune – the music that goes along with the words of a song
* The song had a really happy tune so everyone tapped their feet and clapped their hands.
labor rights – the idea that all workers should be treated in a fair way, including getting paid a fair amount of money, working in a safe environment, and working limited hours
* The workers said that they would not do any more work until their bosses began obeying the laws that protected their labor rights.
reasonable – fair; sensible; practical
* I think that $10 is a reasonable price for a large pizza.
civil rights movement – the effort to get the same protection under the law and in society for African Americans and other minority people that white people had
* During the civil rights movement, many people spoke out about the unfair treatment of African Americans.
to hammer out – to change something; to cause something to disappear; to cause; to give
* There’s a dent in this old military helmet, but I don’t think I’ll hammer it out.
justice – the law; the court system that enforces the law
* The family of the murdered man wanted the killer to face justice and be punished for his crime.
hospice – a special kind of medical care for someone who is dying
* When Amir’s grandmother entered hospice care, he stayed by her side as much as possible because he knew she did not have long to live.
mental illness – a serious medical problem that affects a person’s mind and emotions
* Depression is a mental illness that, for many people, can be helped by taking medication.
behavioral problem – a way of acting that is not expected or acceptable, and is sometimes caused by emotional problems
* Sadia’s teacher told her parents that her biting and hitting were serious behavioral problems in the classroom.
psychological – related to one’s mind, particularly one’s thoughts and emotions
* Studies show that spending time in the sun has a positive psychological effect and can make people happier.
practicum – an unpaid job in a real-life setting where a student gets experience working with regular people and using what they have learned in school
* Minal was very excited about her practicum where she would be working in a women’s health clinic.
supervised experience – a job where one is watched by a superior or boss who is available for guidance and help
* When Daichi was going through his supervised experience, he met with his boss once a week to discuss his patients.
to dismantle – to take apart into pieces a machine or structure
* The international agreement says that both countries have to dismantle their nuclear bombs.
to disassemble – to take something apart, usually something that had once been put together
* I put together the bookcase incorrectly and had to disassemble it before trying again.
guilt – having committed a crime or done something illegal; the feeling of having done something wrong
* All of us feel some level of guilt for not realizing earlier that Molina had a problem.
blame – responsibility for something bad or wrong that occurred or exists
* Instead of trying to find someone to blame, let’s focus on fixing the problem.
to cross the great divide – to die; to cross the space or difference between two groups that is difficult to ignore or overcome; to travel a part of the continental divide formed by the Rocky Mountains in the United States
* None of us wants to cross the great divide without saying goodbye to our loved ones.
What Insiders Know
Mickey Spillane’s Mike Hammer
One of the most famous characters in popular American writing is Mike Hammer. Mike Hammer is a “fictional character” (not real person appearing in stories or books) created by the American author Mickey Spillane. Mike Hammer’s character first appeared in the 1947 book I, the Jury, which was then made into a movie “twice” (two times) – one in 1953 and another in 1982.
While many famous fictional detectives are “depicted” (shown or represent through drawing or writing) as “hard-boiled” (strong and tough without showing any emotion) and “cynical” (someone who believes that people are not basically good and sincere), Mike Hammer’s character is often described as violent, someone with genuine “rage” (anger; hate) toward violent crime.
Many fictional detectives are depicted as heroes “bending” (not strictly following) and “manipulating” (using planned actions to one’s own advantage) the law, Mike Hammer looks at the law as a “hindrance” (something that slows something down) to “justice” (fairness). He doesn’t respect the police because they are not able to do certain things because of certain laws, sometimes letting “guilty” (having committed a crime) people get away. In Spillane’s fifth novel, The Big Kill, Hammer describes himself a misanthrope. A “misanthrope” is a person who dislikes other people and avoids human society.
There have been 20 different novels featuring Mike Hammer, as well as a radio series that “aired” (was broadcasted) from 1952 to 1954. A number of television shows have also been created based on Mike Hammer: Mickey Spillane’s Mike Hammer (1958 – 1960), Mickey Spillane’s Mike Hammer (January 1984 – January 1985), The New Mike Hammer (September 1986 – May 1987) and Mike Hammer, Private Eye (September 1997 – June 1998).