= 1784
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 479.
This is English as a Second Language Podcast’s English Café episode 479. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide, an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to talk about the 11th president of the United States, James K. Polk. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café is another one of the American presidents, one about whom most Americans don’t know very much, although his presidency – his time as president – was an important one in the nineteenth century. His name is James K. Polk. James Polk was born in November in the year 1795 in the state of North Carolina. North Carolina is one of the original 13 states on the eastern coast of the United States.
Polk was the oldest child of 10 children. (Not a very big family, really; I’m the youngest of 11 children – now, that’s a big family! But okay, so he had a sort of big family, Mr. Polk.) As a boy, Polk was sick a lot. He had poor health. Later in life, he would say that as a child he was “worn with disease.” “To be worn (worn) with” something means to be damaged by something or perhaps to be tired out by something.
Many historians believe that Polk worked so hard to be successful as an adult because he wanted to make up for being weak as a child. “To make up for” something means to do something good in order to make something bad in your past seem less important. The most common use of this expression would be between a husband and wife. The husband says something stupid, and the wife gets angry. The husband then has to “make up for” his stupid remark by buying his wife chocolate or roses. That’s the formula I use.
Polk and his family moved to the state of Tennessee in 1806. Tennessee is located in the middle section of the United States, but it is not on the Atlantic Ocean – it is “inland,” we would say. Because Polk was such a sickly child, he was not able to go to school. Instead, his mother and some private tutors came in and taught him at home. So he was what we would nowadays call a “home-schooled” child. A “tutor” (tutor) is a teacher who works usually just with one student. We would say he works with a student “one-on-one.”
Polk was very intelligent and hardworking, and therefore was a very good student. He was such a good student that he was accepted into the University of North Carolina and graduated from there in 1818 at the top of his class. When you graduate “at the top of your class,” you are the smartest student. You are the student who received the best grades. I did not graduate at the top of my class, but not at the bottom of my class, either. Somewhere in between.
Anyway, after Polk graduated from the university, he moved to Nashville, Tennessee, to become a lawyer. Nashville is nowadays famous for a particular kind of American music, country music. Polk became a lawyer after studying the law for two years and passing the bar. To become a lawyer in the United States, you have to take a special exam, a test, and that test is called the “bar exam.”
The word “bar” is used to describe the place where you go and get an alcoholic drink. But we’re not talking about that kind of bar. The bar here refers to the legal profession, the people who practice law. The word actually comes from a part of a courtroom that separates the part where just the judges and jury and lawyers are and the general public – people who are just there to watch a legal proceeding, a legal case. The bar is sort of like a fence – or a “railing,” we would call it – that separates the different parts of the courtroom.
However, the same word is also used to describe the legal profession, lawyers in general, and the “bar exam” is, therefore, the examination that allows you to become a lawyer in a certain state. Polk “passed the bar,” we would say, and became a lawyer. He began also to get involved in politics. He believed that being a lawyer was a good way to enter the political world, and there are still many lawyers who become politicians – or, I should say, many politicians who were once lawyers.
In 1824, Polk married a woman by the name of Sarah Childress. Sarah was the daughter of a very rich Tennessee farmer. She herself was well-educated, which was somewhat unusual for women at that time. She was also a very charismatic woman. “Charismatic” (charismatic) describes a person who has a quality that makes other people want to be around him or her and follow what he or she says. A charismatic person is a person with a very strong and appealing or interesting personality, someone you want to get to know, someone that you would naturally like.
Polk’s wife was charismatic, but Polk was not. However, the fact that his wife was a charismatic person certainly helped Polk himself and his political career. Polk didn’t have very many friends, whereas Sarah, his wife, had lots of friends. The two never had any children, and Sarah focused all of her attention on Polk and his political career. She in fact became, as do many wives, Polk’s confidant. A “confidant” (confidant) is a person that you can talk to and share your secrets with, a person who you can trust.
Polk’s wife was so involved in his work that when he eventually became president of the United States, many people called her the “Presidentress.” “Presidentress” is not a real word in English, but it is used in this case to describe, I guess, a woman president. In addition to the president, there was the presidentress. We sometimes use that suffix “-tress” to describe a female version of something. You can think of the word “actor” and “actress.” An “actress” is a woman, and “actor” can be a man, although more recently we’ve use the word in English to describe both men and women who act.
Although Polk didn’t have many friends, he did have some important and powerful friends, including Andrew Jackson. Andrew Jackson was our seventh president. He was president from 1827 until 1839, and he was also from Tennessee, where Polk was living. Polk was a strong supporter of Jackson even before they became friends, and Jackson became a strong supporter of Polk. The support turned out to be very important in Polk’s political career.
In 1823, Polk was elected to the Tennessee House of Representatives. This is a part of the state government. Then, in 1825, just two years later, he was elected to the United States House of Representatives representing part of the state of Tennessee in Washington, D.C., in our national government. He was part of the U.S. House of Representatives from 1825 until 1839.
In 1835, he became the leader of the U.S. House of Representatives. We call the leader the “Speaker of the House.” The Speaker of the House” is the most powerful person in the U.S. House of Representatives. The Speaker of the House typically comes from the political party that has the most votes in the U.S. House of Representatives, what we would call the “majority party.”
In 1839, Polk left the U.S. House of Representatives to become the governor or leader of the state of Tennessee. He was not reelected in 1841 or in 1843, however, so he decided to leave state politics and return to national politics. This opportunity came about in a 1844, when he was nominated to be the presidential candidate for the Democratic party. A “candidate” (candidate), in this case, is a person who represents a political group, what we would call a “political party,” in an election.
Even though Polk was fairly well-known in the world of politics, most people in the United States had never heard of him. He was what we would call a “dark horse candidate” for the presidency. A “dark horse” is a person who is not expected to do very well at a competition or in a race or, in this case, in an election. Polk was a dark horse candidate because he wasn’t very well-known when he first was nominated. However, he surprised everyone by winning the election and became our 11th president.
During the election, there were two main political issues that everyone was talking about. The first was the annexation of Texas. “Annexation” (annexation) is when basically one country takes over a piece of land and says it is now part of their own country – takes over a piece of land from another country.
Now, in the case of Texas, things were a little bit different in the sense that at the time that Polk became president, Texas was its own country. It was no longer part of another country. It had been part of the country of Mexico, but beginning in 1836, Texas was its own country, its own republic.
When we use the word “annexation,” sometimes it describes a situation where one country takes over another part of the country or another country without the people living there wanting that to happen. In other words, they do it by force. In the case of the annexation of Texas, it was not a situation where the United States sent in the army and took over Texas, but rather that Texas decided to become part of the United States.
The other big issue in the election of 1844 involved land on the Pacific Ocean that is now the states of Oregon and Washington. During the early part of the nineteenth century, as the population of the United States grew, more and more people started moving west, and in particular to the, what was then called, “Oregon Territory.” This is basically in what is the “Pacific Northwest,” we would call it, of the modern map of the United States. People began to move into this area, but Great Britain – England – also thought this land belonged to them.
So, beginning in about 1818, the U.S. and England decided to share this territory, but everyone knew this was not a permanent solution. Polk thought he had a permanent solution, and that was for the United States to simply take over this territory. Now, Polk didn’t want to take over the entire Oregon Territory, which at that time included what are now some of the areas in the country of Canada. Instead, he wanted the U.S. to take over everything below a certain line, below a certain latitude.
A “latitude” (latitude) is a measurement that is used to say how far a place is north or south of the equator. It’s an imaginary line that separates the earth into different sections, north to south. We also sometimes call it a “parallel.” So, the 45th parallel would be halfway between the equator and the north (or if it’s in the southern hemisphere, south) pole.
The Oregon Territory, as I mentioned, was a very large piece of territory, a large piece of land, that went all the way up to what is modern-day Alaska. The northern edge or northern border of the territory was at the latitude 54’40. So, Polk created a saying, a phrase – what we would call a “slogan” (slogan) – for his campaign, which was “Fifty-four forty or fight.” In other words, the United States should take possession of the entire Oregon Territory from Great Britain, or if Great Britain didn’t want to do that, we would fight Great Britain for that territory.
This slogan became very popular, and one which the majority of American voters liked. And so, Polk was elected president. Now, when he became president, he did two things. First, he helped the then-Republic of Texas become a state, so Texas became part of the United States during Polk’s presidency. He also negotiated with Great Britain to basically divide the Oregon Territory.
He did not insist that the U.S. take possession of the entire territory. Instead, the U.S. and Great Britain decided to divide the territory at the 49th parallel, and that is the now-border between the United States and the country of Canada. Canada, of course, was under control of the country of Great Britain during this period.
I mentioned that Texas became part of the United States during Polk’s presidency. However, that was not a peaceful process. Remember that Texas was once part of the country of Mexico, and Mexico was not very happy about this area becoming part of the United States. It didn’t want the land to become part of the U.S., and so there was a war between the United States and Mexico.
Part of the problem was that Polk didn’t only want the area of Texas to become part of the U.S. He also wanted what is now part of the states of New Mexico, Arizona, and California to become part of the U.S. Polk offered to buy the land from Mexico, but Mexico wasn’t interested. And so, Polk sent the United States Army into Mexico and there was a war between the two countries. The Mexican-American War, as it’s called in English in the U.S., lasted from 1846 to 1848.
The U.S. Army was much larger and more powerful than the Mexican army, so it wasn’t difficult for the U.S. to move its army through the country and eventually force the Mexican government to give them the land that Polk had wanted. Eventually there was a treaty negotiated between the countries of Mexico and the United States. It’s called the Treaty of Guadalupe Hidalgo. A “treaty” (treaty) is an agreement between two countries. “To negotiate” means to sit down and reach an agreement. To say, “Okay, we’ll do this and you do that.”
Mexico did not have a lot of choice, however, since the United States Army was in Mexico and had basically forced the Mexicans to give up the land that was north of the Rio Grande River. The U.S. did pay Mexico something for that land, however, about $15 million. The importance of Polk’s presidency, then, was that he really established the modern-day borders of the continental United States – that is, the part of the U.S. that doesn’t include the states of Alaska and Hawaii – and that’s probably his greatest or most important achievement.
When Polk’s term of office ended in 1849, he decided to retire. He wasn’t going to be president again even though he could have run for reelection. Instead, he returned to Nashville, Tennessee, and died that same year, in 1849, of a deadly disease called cholera. Many historians don’t consider Polk as one of our greatest presidents. However, in his own terms, he was a very successful president. He certainly changed the future of the United States significantly through the expansion of U.S. territory to the west.
Now let’s answer a few of your questions.
Our first question comes from Claudia (Claudia) in the country of Austria. Claudia wants to know the meanings of the words “beach,” “shore,” and “coast.” Let’s start with “beach” (beach).
A “beach” is an area of land on the edge of a body of water such as a lake or ocean. Usually when we use the word “beach,” we’re talking about an area that has a lot of sand or small rocks that you can walk on. People go to the beach to get a suntan or to jump into the water to swim. There are many beautiful beaches in the United States, especially here in California.
The “shore” (shore) describes any land that is along the edge of a body of water such as a lake or an ocean. When we use the word “shore,” we’re describing the edge of the land next to the water. It doesn’t mean that there is a beach there. You could have a shore that has a beach. You could have a store that doesn’t have the beach. It could be, for example, just rocks.
Finally, “coast” (coast) is another word to describe the land that is next to an ocean. We don’t use “coast” for a lake, typically. We use “coast” only to describe where an ocean is next to a large piece of land. So, here in the United States, we talk about the West Coast – that would be the states of California, Oregon, and Washington. You could also talk about the East Coast. Those would be the states that are along the Atlantic Ocean in the eastern part of the U.S. “Coast” is a more general term to talk about areas of land that are next to oceans.
Alexey (Alexey) from Russia wants to know the difference between “concept” and “conception.” “Concept” (concept) refers to an idea – a general “notion,” we might say – about something. “I have a concept of time.” I have an idea of what time is and what it represents. You could have a concept of teamwork, of how you work with other people in your company. “Concept” refers to your idea of it, what’s in your head. “Concept” can also be used to indicate a plan – what you hope to do in the future, an idea of what you want to do in the future.
“Conception” (conception) refers to the beginning or the origin of something, including an idea. The word comes from the verb “to conceive” (conceive). “To conceive” means to think of something. So, your conception of an idea is when you first thought of it, your process of thinking of a new idea.
The verb “conceive” and the related noun “conception” is also related to a biological concept. “To conceive” means to, for a woman, a female, to become pregnant – when you first see the formation of a child inside of a woman’s body. We talk about the “conception” of human life, when human life begins inside of what is known as the “womb” (womb). Biologically, it’s when the sperm of a man unites to the egg of a woman. If you don’t understand that, you should probably talk to your mother or father.
Our final question comes from Maman (Maman) in the country of Niger. The question has to do with a very common word in English, “hey” (hey). We use the word “hey” to attract someone’s attention – to get someone to pay attention to us.
So, for example, if you want to get the attention of a person sitting across the table from you, you might say, “Hey!” Now that’s very informal. “Excuse me” would be a more formal way of getting someone’s attention. “Hey” is used informally and might be considered a little rude, depending on the circumstances. We also use “hey” to express surprise and sometimes anger, like, “Hey! What are you doing?” That would be a use where “hey” is used to express our dislike of something, our anger about something. It can be used, then, in both a positive and a negative way.
More recently, “hey” has become popular as a way of saying “hi” or “hello.” Instead of walking up to someone and saying “hi,” you might say “hey.” Again, it’s very informal and you would probably only do that with someone that you know fairly well. “Hey” is one of those words that has then many different uses in English, depending on the way that the person says it.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
to make up for – to do or have something good to make something bad seem less important
* The airline made up for the four-hour delay by giving each passenger a coupon for free food or drinks at the airport.
tutor – a teacher who works one-on-one with a student or with a small group of students, usually focusing on a particular subject or preparing for an exam
* When Ivan started getting bad grades in math, his parents hired a math tutor to work with him at home three times a week.
charismatic – a quality a person has that makes other people want to be around him or her and follow what he or she does or says
* Because she was so charismatic, Ansu could make friends wherever she went. People just loved being around her.
confidant – a person with whom one can share secrets and private things, knowing that he or she won’t tell anyone else
* Many people who live public lives have confidants to discuss private thoughts.
Speaker of the House – the leader of the House of Representatives and is from the political party with the most elected representatives
* When it was time for a vote, the Speaker of the House called for silence and each Representative voted for or against the bill.
candidate – a person who applies for a job or is selected to represent a political group in an election
* Based on her experience as a lawyer in a well-known law firm in New York, many people thought that Kemba was an excellent candidate for the job.
dark horse – a person whom no one expects to do well surprising everyone by winning or succeeding
* The skier from South Africa was a dark horse in the race but managed to win the gold medal.
annexation – when one country takes over a piece of land and claims that it is now part of their own country
* Many politicians at the time said that Germany’s annexation of Austria was the true beginning of World War II.
latitude – a measurement that is used to say how far a place is north or south of the equator (an imaginary line dividing the Earth into equal parts north and south)
* In the summer, parts of Iceland have twenty hours of daylight because of its latitude.
slogan – a short and easy-to-remember phrase that is used in campaigns and advertising
* One of the most successful advertising slogans for Las Vegas has been, “What happens in Vegas, stays in Vegas.”
to negotiate – to try to reach an agreement with another person
* Every night, Girard and his mother negotiated how many books they would read at bedtime before he had to go to sleep.
beach – an area of land along the edge of the sea, lake, or other large body of water with sand or small rocks
* When we returned from the beach, we had sand in our clothes and salt in our hair.
shore – the land along the edge of a sea, lake, or other large body of water
* After two weeks at sea, we were happy to see the New England shore.
coast – the part of the land near the sea; the edge of the land next to the sea
* We stayed on a small island off the coast of the Arabian Sea.
concept – an idea; a general notion; a plan or intention
* What is your concept for this party, something formal or casual?
conception – the origination or start of something in the mind; the action of becoming pregnant with a child
* Our architectural and construction firm will take care of building your new home, from conception to completion.
hey – used to attract attention or express surprise, interest, or annoyance; word used as a friendly greeting
* Hey, were you just trying to ask Michael’s girlfriend for a date?
What Insiders Know
The President’s Scholars Program
In 1964, the U.S. government established the Presidential Scholars Program. The program was created to “recognize” (give attention to) and celebrate “distinguished” (successful and outstanding) graduating American high school “seniors” (secondary school students in their last year of high school).
Each year, there are about three million “graduating” (finishing their studies) high school students. Of these, 2,600 are selected as “candidates” (people who could win a competition or election), and finally, 141 students are “chosen” (selected) as Presidential Scholars.
The Presidential Scholars are invited to Washington D.C. to meet past Presidential Scholars, many of them successful authors, scientists, business leaders, teachers, and government officials. The Scholars are also given tours of museums and “monuments” (structures built to remember a person or event), and attend a “ceremony” (formal event with certain rituals).
The selection process is not easy. The candidates are required to “submit” (give for consideration) candidacy materials, including “essays” (pieces of writing about specific topics), “self-assessments” (evaluations of oneself), “transcripts” (official school document showing which school courses were completed and grades received), and much more. They are then evaluated on their “academic achievement” (how well they performed in school), personality, “leadership” (ability to be a leader), their essays, and other “extracurricular activities” (activities not related to school subjects, such as sports, music, community service, and art).
Many past Presidential Scholars have gone on to distinguish themselves in their careers. For example, previous scholar Rita Dove became the “Poet Laureate” (national poet) of the United States and winner of the Pulitzer Prize for Poetry. Another past winner, Todd Park, became the Chief Technology Officer of the United States, and another past scholar, Kristin Forbes, became a business professor at the Massachusetts Institute of Technology (MIT).