= 1771
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 466.
This is English as a Second Language Podcast’s episode 466. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also take a look at our ESL Podcast Store, which has some additional courses in English for you.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed, that is. Today we’re going to talk about being a twin, or one of two people who are born at the same time from the same mother. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is being a twin. We’re going to start by listening to Joan Friedman, who is a psychotherapist. A “psychotherapist” is a crazy person who tries to tell other crazy people how they should live their lives. I’m joking, of course. A “psychotherapist” is someone who trains for many years to try to understand people’s emotional and psychological problems.
It’s become popular more recently, instead of saying problems, to say “issues.” The word “issue” is normally one we use to talk about a topic, especially an important topic in politics. However, when someone says “I have issues,” or “She has mommy issues,” or “They have twin issues,” they’re referring instead to some sort of psychological problems that they have, some sort of difficulty that relates to this particular part of their lives.
Joan Friedman is a psychotherapist who specializes in twin issues. A “twin” (twin) is one of two babies that are born at approximately the same time – usually one comes out of the mother’s womb before the other. Babies who are born at the same time are called “twins.” There are two kinds of twins. There are what we call “identical twins” that typically look very much like each other – two boys or two girls.
There are also what are called “fraternal twins.” This could be two boys, two girls, or a boy and girl, and when they are fraternal twins, they do not look exactly like the other. I have two brothers who are identical twins, and two nieces who I think are fraternal twins. In any case, the person we’re listening to now is herself a twin. She’s going to talk about her own experience as a twin growing up with a twin sister. Let’s listen and then we’ll explain what she said.
“We were very much stars and got a lot of attention, and people always knew we were the Friedman twins, but then as we became older and you wanted to have your own identity, people really didn’t know who we were, and it was a sense of sort of like being noticed, but not being known.”
Ms. Friedman begins by talking about herself and her sister. She says, “We were very much stars and got a lot of attention and people always knew we were the Friedman twins.” When we say someone is a “star” (star), we mean the person is considered someone special. Nowadays when we talk about the “stars” here in Hollywood, we’re talking about movie actors and actresses, musicians, and television actors. These are, if they become very popular and famous, considered “stars.”
When Friedman talks about “being a star,” she’s talking really about how people noticed them, how they were popular, how everybody knew about them. I should also mention that the word “star” can also refer to the bright lights up in the sky that are made like our sun and shine brightly at night, except here in Los Angeles, where we have so much light pollution – where there are so many lights in the city – you can often not see the stars very well, but back to Ms. Friedman.
She says that she and her sister were stars when they grew up. They got a lot of attention. “But then as we became older,” she says, “and you wanted to have your own identity, people didn’t really know who we were.” When Friedman talks about “identity” (identity), she’s referring to how one views oneself. “Identity” refers to how you and I define ourselves. My identity, for example, consists of being a husband and being a podcaster and being a linguistics professor, or at least a former linguistics professor. That’s part of my personal and professional identity.
As twins, the Friedmans wanted to have their own identity – each being different from the other – but people didn’t really know who they were, she says. Friedman says that there was a sense or feeling of being noticed. She says, “It was a sense of sort of like being noticed, but not being known.”
“To be noticed” means to be seen. People see you and they recognize you. They know who you are. They say, “Oh that’s John,” or “That’s Julie.” Somebody sees that you’re there when they notice you, but doesn’t necessarily know you – doesn’t have any special information about you and your personality, what you’re interested in. That’s what Friedman means when she says that people noticed them, but they were not known. Let’s listen to the recording one more time.
“We were very much stars and got a lot of attention, and people always knew we were the Friedman twins, but then as we became older and you wanted to have your own identity, people really didn’t know who we were, and it was a sense of sort of like being noticed, but not being known.”
Next, Friedman is going to talk about how people raise twins – that is, how parents treat or act toward their twins as they are growing up. She’s going to talk about how people treat twins differently than they might treat what we might call a “singleton” – a person who is born, like most of us, without a twin. Let’s listen.
“People just project a lot of their own concerns to separate twins, that you’re breaking that twin connection, you’re going to, in some way, interfere with their loving one another. I find this often happens across cultures. If you give them experiences where they learn to be on their own, where they learn to rely on themselves, they develop a resilience so that they can feel they can be their own persons. If not, then they develop this overdependence, or really a codependence, because they've never been without each other.”
Freeman begins by saying, “People just project a lot of their own concerns to separate twins.” I’m not exactly sure what she means here, but I’ll try to explain as best I can. When we use the verb “to project” (project) when talking about relationships or psychological issues or problems, the verb means to assume or imagine that your feelings, your opinions, your beliefs are true for this other person.
So, we think that the other person thinks the way we do, or we think the other person is like us, and therefore that we somehow understand that person. Friedman is saying that people project their own concerns onto twins, meaning that they believe the things they’re concerned about will be the same thing that those twins are concerned or worried about or should be concerned about. She then gives an example. She talks about “breaking the twin connection.”
One concern that people might project onto twins – think that twins are concerned about – is that the twins need to keep this sort of deep psychological connection/relationship with each other. What I think she’s saying (and it’s somewhat difficult to know exactly since she is a psychotherapist, after all) is that we often think that we’re going to somehow get in the way of twins, or rather that twins are going to hurt the relationship that they have with each other, if they are treated separately.
I think the thing that we’re missing here is the idea that Friedman has that you should treat your babies – your children who are twins – not as a pair, not as a set, but as individual human beings who have their own personalities and identities. She’s saying that if you do this, you are not interfering or getting in the way of the twins loving each other.
She continues, “I find this often happens across cultures.” What I think she means here is that she has noticed this pattern of behavior, this way of treating twins, in different cultures, although we don’t know what cultures she’s talking about. She continues, “If you give them” – meaning the twins – “experiences where they learn to be on their own, where they learn to rely on themselves, they develop a resilience.” “To be on your own” means to be independent, to do things without anyone helping you. Friedman says when twins do this, they can develop a “resilience.”
“Resilience” (resilience) means strength, especially the ability to recover from difficulties and challenges – to get over your problems and continue strong in whatever you were doing. Someone who loses a job or gets a divorce but is able to find perhaps a better career and other relationships might have the quality of resilience. We might say that person has resilience. Or a young child who grows up in a family that is perhaps not loving or caring but who nevertheless is successful in life. We may say that child has resilience.
Friedman is talking about the resilience that twins can develop if they are treated as separate individuals. She says, “They develop a resilience so that they can feel they can be their own persons,” meaning they can be independent and not considered part of the relationship of being a twin.
“If not,” she says, “then they develop this overdependence, or really a codependence, because they’ve never been without each other.” “Dependence” comes from the word “depend,” meaning to rely on or to need for support. “Overdependence” would be a situation where you are relying on someone too much. The other person is helping you so much that it’s somehow hurting your development or in some ways psychologically unhealthy.
“Codependence” is a word that has become popular in English in the last 25, 30 years or so. “Codependence” is an unhealthy psychological condition in which someone is too dependent on another person, especially for emotional support – so much so that he or she cannot even live their life without the other person or function properly without the other person. Friedman wants to make sure that twins are given opportunities to avoid developing this type of codependence on each other. Let’s listen once again.
“People just project a lot of their own concerns to separate twins, that you’re breaking that twin connection, you’re going to, in some way, interfere with their loving one another. I find this often happens across cultures. If you give them experiences where they learn to be on their own, where they learn to rely on themselves, they develop a resilience so that they can feel they can be their own persons. If not, then they develop this overdependence, or really a codependence, because they've never been without each other.”
Finally, Friedman is going to give us some advice. This, of course, is what we pay psychotherapists to do, is to give us advice on how to live our lives, and Friedman will not disappoint. She is going to give us some advice. Let’s listen.
“I have certain things that I always tell parents, which is, of course, not to dress them alike, and not to give them alliterative names like Tom and Tony and Natalie and Nancy, but to give them different names. Make sure you take separate pictures of each twin. If they grow up and never see a picture of themselves by themselves, it’s very difficult for them to think about them as separate. And alone time is really what I feel is the most . . . if you take one to the grocery store, take the other one to the park, which gives you a sense of a connection with both babies.”
She begins by saying, “I have certain things that I always tell parents.” She’s referring, of course, to the parents of twins. She says that she tells the parents “not to dress them alike.” To dress two people alike would mean to put the same clothing on two different people, or the same kind of clothing, clothing that looks the same. This is very common with twins, at least here in the U.S. They’ll both have the same kind of shirt on or the same pants or the same colors. I’m quite sure my mother did this to my older brothers who are twins. I don’t think it damaged them psychologically, but I could be wrong.
She continues saying that “parents should also not give their children alliterative names like Tom and Tony and Nancy and Natalie.” “Alliterative” comes from the word “alliteration” (alliteration). “Alliteration” is what we might describe as a literary device or tool that involves using words that start with the same sound. In English, especially in English poetry and in good English writing, alliteration is often found.
If you name your children “Tom” and “Tony,” since both words begin with a “t” sound, then you are using “alliterative names.” My mother named her twins “Mike” and “Mark” – both with an “m” sound. However, my sister did not name her two twins the same name, so I guess she must have been listening to Ms. Friedman.
She also tells parents, “Make sure you take separate pictures of each twin. If they grow up and never see a picture of themselves by themselves” – that is, alone – “it’s very difficult for them to think about them” (I think she means “themselves”) “as separate.” I’m not sure what evidence Friedman has that this is true, but that’s what she says.
She continues, “Alone time is really what I feel is the most” – I think she means here “the most important.” The idea is that the twins have time alone with the parents, not just the two of them together. That’s not always possible, of course, especially if the children are young and there’s only one parent looking after them.
She says, “If you take one to the grocery store, take the other one to the park.” In other words, don’t take your twins always together when you go out. Take them sometimes separately to one place or another. She says this gives you, as a parent, a sense of connection to the individual babies, to each twin. Let’s listen one more time.
“I have certain things that I always tell parents, which is, of course, not to dress them alike, and not to give them alliterative names like Tom and Tony and Natalie and Nancy, but to give them different names. Make sure you take separate pictures of each twin. If they grow up and never see a picture of themselves by themselves, it’s very difficult for them to think about them as separate. And alone time is really what I feel is the most . . . if you take one to the grocery store, take the other one to the park, which gives you a sense of a connection with both babies.”
So, now you know everything you need to know about raising – and, I guess, being – a twin. Interestingly enough, I grew up in the Twin Cities – two cities that are right next to each other across the river: Minneapolis and St. Paul. So, I guess I’m a twin in a way. In fact, our professional baseball team is called the Minnesota Twins.
And some of the most famous studies in the U.S. that have been conducted on twins have been done by researchers at the University of Minnesota. So, I guess I could listen to Friedman’s advice as well, but I won’t.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Mayuko (Mayuko) in Japan. Mayuko wants to know the meaning of three verbs: “to revoke,” “to nullify,” and “to rescind.” These three words do have similar meanings. So, let’s try to figure out how we use each one.
We’ll start with “to revoke.” “To revoke” (revoke) is used when you give someone permission to do something. When you say it is okay for him to do something, and then later you say no, you can’t do that anymore. “To revoke,” then, means to no longer give permission for someone to do something.
For example, in the U.S., each state and territory “issues” – that is, gives – people who qualify driver’s licenses, but if you break the law by doing something such as drinking and driving, the state or territory can revoke your license. They can “withdraw,” we might say, the permission they gave you to drive.
“To revoke” can also mean to stop giving something to someone because he did something wrong. Again, an example: if you get a scholarship from a university because it thinks you’re a great student with wonderful grades or marks, and then the university discovers that you lied on your application, that you are a terrible student, the university could revoke your scholarship. The university will stop giving you money.
“To nullify” is somewhat different. “To nullify” (nullify) means to make something that used to have some use or some kind of value no longer have that use or value. Let’s say you buy a new phone – an Android or iPhone, say – and the company you buy it from gives you a one-year warranty. A “warranty” is a promise from the company to fix your phone if it breaks for, let’s say, the first year after you buy it.
But usually warranties have what are called “terms and conditions,” which are the rules that you have to follow in order to be able to use the warranty. If you break one of those rules – by, for example, opening up the phone and looking inside of it – your actions could “nullify” the warranty. They can make what once had value, what was once worth something – your warranty – worthless, without value. It basically changes the agreement you had with the company with the warranty.
Finally, “to rescind” (rescind) means the same as “to revoke” – something very similar, but it is probably a little less common in daily conversation. Although, to be honest, none of these words is very common in conversational English. “To rescind” can mean the same as “to revoke” in the sense of withdrawing permission for someone to do something.
Usually “rescind” is used when someone in power cancels or changes a law, rule, or agreement. The legislative body of the U.S. government called Congress, which is the Senate and the House of Representatives, can rescind legislation. It can rescind laws. It can cancel or remove them so that they are no longer laws.
A more common use of “rescind,” perhaps, in daily conversation is with the word “offer.” “To rescind an offer” is to propose something to someone, to offer them something, and then change your mind and say, “No, I’m sorry, I’m not going to offer that to you anymore.” “My girlfriend said she would marry me, but then she found out I was not really that smart, so she rescinded her offer of marriage.”
Our next question comes from “Jaydee” (Jaydee) from a mystery country. We really need a list of mystery countries to use when we get a question from someone whose country we don’t have. Perhaps some of you could send us your suggestions for mystery countries. Anyway, Jaydee wants to know the meaning of the word “waste.”
As a noun, “waste” usually refers to material or things that are no longer wanted, what we might also call “junk,” “trash,” “garbage,” or “rubbish.” When used in this context, waste is often found with another word to specify your to give you exactly the kind of waste it is.
So, you will sometimes see things such as “industrial waste,” “nuclear waste,” “toxic waste” (that is poisonous waste), “hazardous waste” (which is dangerous waste). “Waste” is a bit more formal of a word to refer to junk or trash – things you don’t want – but basically it refers to things that you don’t want and want to get rid of, want to “throw out,” we might say.
You can also talk about a “waste of space,” meaning that a thing or a person is not very useful. This is usually said insultingly about, for example, someone in your office who doesn’t really do very much and is basically useless. That could be a case where you would say this person is a “waste of space.” It’s a very negative thing to say, however, a very insulting thing to say.
“Waste” can also be a verb meaning to not use something properly, or in such a way that instead of being useful, it’s basically ruined or thrown away, almost as if it were junk or garbage. Here in California, we are told by the state government not to waste water by putting water on our lawns to keep them green or by using water unnecessarily in our houses. The opposite of “waste” in this case would be “conserve,” as a verb, which is to save water, to not use it improperly.
Mothers often tell their children not to “waste food,” meaning the children should eat it and not throw it out just because perhaps they don’t like the taste of it. This, I think in general, is a good rule for children, unless their mother is a really terrible cook, but that’s a different story.
Finally, we have a question from Pukar from the country of Nepal. I’m not sure where in Nepal Pukar is from, but I will say that a lot of Americans, at least of my generation, have heard of Nepal in part because there was a song in the 1970s that was called “Kathmandu.” And Kathmandu is the capital of Nepal. But anyway, Pukar wants to know the meaning of what is originally a French expression that is commonly used in English: “bon voyage.”
The expression “bon voyage” means good journey or good trip. It’s used to wish someone who is about to travel a good trip, a good journey. Usually, we use this expression when the person is traveling very far, going a great distance. You don’t say “bon voyage” if someone is just going to the gas station or Starbucks – unless, of course, you’re making a joke.
Now, we also have a word in English that’s spelled the same as “voyage,” which “voyage” (voyage). A “voyage” also means a journey or a trip. A voyage is typically a very long trip, perhaps one of several days or weeks. It’s not a word we use that much anymore. It’s something you would probably see more often in a history book talking about some of the great European explorers. For example, you might read about Drake’s voyage or Magellan’s voyage around the world.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California. I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
star – a person who is very good at doing something and is famous or at least recognized for doing something well
* Saeed has always been a star in the classroom, while his brother has been a star in sports.
twins – two people who are born to the same mother at the same time
* When Justin first started dating Samantha, he sometimes mistook her for her twin.
identity – how one views and defines oneself; the characteristics and way of thinking that makes one who one is
* Gregorio had always viewed himself as an athlete, but after the car accident left him paralyzed, he had to create a new identity for himself.
to be noticed – to be seen or observed; to be easily seen by others
* Most of those trees were never really noticed by passersby until they were cut down one day.
to project – to put an image onto a large screen; to imagine that one’s own opinions, feelings, or beliefs are true for another person
* Anthropologists have to learn to avoid projecting their own values onto people from other cultures.
to interfere with – to have some affect or influence on someone or something, especially a negative influence
* Please don’t interfere with these experiments, as any changes might affect the results.
resilience – an ability to overcome hardship and recover from difficulties or challenges
* Vladislav showed a lot of resilience when he recovered from his battle with cancer.
to be (one’s) own person – to understand oneself and be comfortable pursuing one’s interests and passions, without worrying too much about other people’s opinions or expectation
* Francesca couldn’t wait to move out of her parents’ home and be her own person.
co-dependence – an unhealthy psychological condition in which someone is too reliant on another person for emotional support, so much so that he or she cannot function well without that other person
* They’re seeing a psychologist in the hopes that he can help them work through their issues of co-dependence.
to dress alike – to put two or more people in the same clothing or very similar clothing
* Sometimes little girls like to dress alike with their best friends.
alliterative – using alliteration, the literary tool or technique of using words that start with the same sound
* They want to pick an alliterative name for their business, like “Crazy Coffee.”
alone time – time spent by oneself, without being around other people
* After a long and stressful week at work, Hannah just wanted some alone time when no one would place any demands on her.
to revoke – to no longer give permission to do something; to no longer allow the doing or the operation of something
* If the police catch you drinking and driving, your license will be revoked.
to nullify – to invalidate; to make something no longer of use or value
* This new data nullifies all of our earlier conclusions.
to rescind – to revoke; to cancel, especially a law, order, or agreement
* The policy was so unpopular that the management team decided to rescind it.
waste – material that is not wanted; the unusable parts of something; garbage
* The factory is looking for ways to make its waste less harmful to humans.
bon voyage – a French expression meaning “good journey,” used to express good wishes to someone before he or she goes on a journey
* A: I’m going on my vacation to South Africa next week.
B: Bon voyage!
What Insiders Know
The Olsen Twins
The Olsen twins are “arguably” (many, but not all people, believe it is true) the most-recognized twins in American television and film. Born in 1986, Mary-Kate and Ashley started their acting career when they were just “infants” (young babies) in a television show called Full House. Due to “restrictions” (limitations) on how long children can work, and how “fussy” (difficult to work with) young children can be, TV shows often hire twins to “portray” (show; illustrate) a single character on TV. So the Olsen twins were used “interchangeably” (with one being used in place of the other without any special preparation or announcement) to portray a single character.
When they were just six years old, they began starring together as twins in many TV shows and films. Most of their work was popular with “preteen” (between 10 and 13 years old) girls. They quickly became some of the wealthiest women in the “entertainment industry” (the people and organizations involved in making TV shows, films, music, video games, etc.). In 2007, they were said to have a “collective” (combined; together) “net worth” (the sum of all things they own of value minus all debts) of $100 million.
When Mary-Kate and Ashley turned 18, they began producing products for preteens and teenagers. They “launched” (began to produce and market) “product lines” (groups of related products) for clothing, “fragrances” (scents, like perfumes), home “décor” (objects used to change the appearance of a room), and more. In recent years, they’ve become “fashion icons” (people who are famous for wearing a certain type of clothing) and they’ve launched their own “clothing brands” (types of clothing sold under one or more names).