= 0001
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners and welcome to EnglishPod! My name is Marco. +
A: I’m Amira. +
M: And Amira and I are here today /with a great, great lesson 精彩的课程 for you. +
A: Yes, we are. +
M: Today we’re gonna be talking about a restaurant. Amira, why don’t you give us a little bit more details? +
A: Well, we’re talking about a situation in a restaurant /and two people are involved – the waiter and the customer. And I don’t wanna say anymore. +
M: Okay, don’t say anymore, let’s just listen to this dialogue /and we’ll be back later to explain it.


[.small]
[options="autowidth" cols="1a"]
|===
|Header 1

|A: Good evening. My name is Fabio, I’ll be your
waiter for tonight. May I take your order? +
B: No, I’m still working on it. This menu is not even
in English. What’s good here? +
A: For you sir, I would recommend spaghetti and
meatballs. +
B: Does it come with coke and fries? +
A: It comes with either soup or salad and a compli-
mentary glass of wine, Sir. +
B: I’ll go with the spaghetti and meatballs, salad and
the wine. +
A: Excellent choice, your order will be ready soon. +
B: How soon is soon? +
A: Twenty minutes? +
B: You know what? I’ll just go grab a burger across
the street. 
|===





A: Oh-oh, what a waiter? +
M: What a waiter? He is really angry at this customer /and I can’t blame him, I would be angry too.  +
A: Yeah, so, I’ve seen Marco you have chosen some interesting expressions 表达 for us here.
What is the first one?  +
M: Well, the first one is _I’m still working on it_. +
A: I’m still working on it. +
M: I’m still working on it. +
A: I’m still working on it. +
M: Why don’t we listen to some other examples on how you can use this word /and then we’ll come back /and explain it?  

Example one.  +
A: Did you finish reading the magazine? +
B: I’m still working it. 

Example two.  +
C: Did you fix my car? +
D: I’m still working on it. 


M: Hm. +
A: Uh, so, you could say “I’m still working on it” means… +
M: I still need more time. +
A: Fantastic 极好的，非常棒的. +
M: Great. Okay, it’s clear 很清楚. +
A: I have another one for you guys, it’s a phrase commonly used /and you’ll hear it all the time – coke and fries.  +
M: Coke and fries. +
A: Coke and fries. +
M: Coke and fries. It’s a short way of saying “Coca-Cola and French fries”. +
A: So, that’s basically America’s fast food. +
M: Yeah. Burger 汉堡包，夹心牛肉饼, coke and fries. +
A: Okay. +
M: Hehe. 

A: What’s next on the menu? +
M: On the menu we have a complementary glass of wine. +
A: Complementary glass of wine. +
M: Complementary glass of wine. +
A: Complementary means… +
M: That it’s free. +
A: Free. +
M: Yes. +
A: We love that, ha? +
M: Yeah, we definitely like free things. 

A: Well, um, I have another one for us here, another interesting phrase – I’ll go with. +
M: I’ll go with. +
A: I’ll go with. +
M: I’ll go with. +
A: So, basically, it’s another way of saying “I’m choosing”. +
M: Yeah, I’ll choose or I’ll take. +
A: I’ll take. +
M: Uhu. +
A: Okay, very good. +
M: Alright, `主` the next word that I wanna take a look at /`系` is grab. +
A: Grab. +
M: Grab. +
A: Grab. +
M: Okay, now let’s listen to some other examples of _how we could use (v.) grab in different situations_ /and then we’ll come back and explain it.

Example one.  +
A: On your way home /can you grab some milk? 

Example two.  +
B: Wait for me please, I need to grab my coat. 

Example three.  +
C: Let’s grab a cup of coffee. 


A: Alright, well, I would understand that /_go grab_ means *go get quickly* 快去快回;迅速去拿一下,办一下. +
M: To *go get* (去取某个东西，或者去完成某个简单的任务) quickly, yeah. 

[.my1]
.案例
====
.Go get quickly
“快去快回”​​ 或 ​​“迅速去拿一下/办一下”​​。

- The client is on their way. ​​*Go get*​​ the meeting reports ​​*quickly*. 客户快到了。​​快去​​把会议报告​​拿过来​​。


在标准语法中，更完整的说法应该是：

•“​​Go and get​​ it quickly.” 
•“​​Go to get​​ it quickly.”

但**#在​​日常急速的口语​​中，人们常常会省略连接词（如 and, to），将多个动词直接并列使用，#**形成一种非常有力、直接的命令。这种用法在母语者中非常普遍。

​​类似的高频口语结构还有：​​

- *Go grab...​​ (快去抓/拿...)* 
“Go grab me a coffee.” (快去给我弄杯咖啡。)

- *Come get...​​ (快来拿...)* 
“Dinner’s ready! Come get it!” (饭好了！快来吃！)

- *Run go get...​​ (跑着去拿...）* - 比“go get”更强调紧迫。 
“*Run go get* the first aid kit!” (快跑着去拿急救箱！)
====


A: Yeah. Alright everyone, so, now it’s time /to listen _one more time_ to the dialogue /and listen carefully /and try to understand why the waiter doesn’t like the customer. Let’s listen.  

[.small]
[options="autowidth" cols="1a"]
|===
|Header 1

|A: Good evening. My name is Fabio, I’ll be your
waiter for tonight. May I take your order? +
B: No, I’m still working on it. This menu is not even
in English. What’s good here? +
A: For you sir, I would recommend spaghetti and
meatballs. +
B: Does it come with coke and fries? +
A: It comes with either soup or salad and a compli-
mentary glass of wine, Sir. +
B: I’ll go with the spaghetti and meatballs, salad and
the wine. +
A: Excellent choice, your order will be ready soon. +
B: How soon is soon? +
A: Twenty minutes? +
B: You know what? I’ll just go grab a burger across
the street. 
|===

A: Marco, why did this waiter get angry at the customer? +
M: Well, he basically wasted the waiter’s time. I mean this guy comes into the restaurant,
he is not very polite /and he’s asking all these questions, _in the end_ he just gets up 起立 /and says “Uh, I’ll just go grab a burger /across the street”.   +
A: Yeah, and I also think that /this guy was a lot more casual (a.)随便的，非正式的；漫不经心的，随意的;不认真的，马虎的 than the place he was in,
right?  +
M: Yeah, yeah, I think _it was a nice, uh, fancy (a.)优质的；高档的;太花哨的 restaurant_ 高档餐厅, so, I think he was in the wrong
place.  

A: Yeah, so, how many times, Marco, tell me /do you really have fast food a week? +
M: Fast food, let’s see, uh, Monday, Tuesday, Wednesday… no, I’m just kidding. +
A: Oh my God. +
M: No, no, um, I think I get fast food /maybe once a week… once or twice a week. Alright, 
`主` talking about fast food `谓` made me hungry, so, I think I’m gonna go grab something to eat myself.  +
A: Yeah, me too. 

M: Alright, I hope you guys enjoyed the lesson today /and remember that `主` all of this vocabulary 词汇 `系` is useful for your everyday needs.  +
A: Yes, well, actually /here in EnglishPod /we *focus on* phrases and words 后定说明 that are high frequency /and *that means (v.) that* /you can use (v.) them everyday in your practical life.

[.my2]
实际上，在今天的英语播客中，我们关注的是频率较高的短语和单词，这意味着你可以在日常实际生活中使用它们。  

M: Exactly 正是如此，一点不错, and *be sure* to go to our website at englishpod.com /where you can find many
other resources /and _you can leave your questions and comment_ at our community forum 社区论坛. +
A: So, thank you very much for listening, we’ll be back tomorrow /with another great lesson for you, so, until then… 在那之前 Bye! +
M: Bye! 

'''
