= 0006
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone and welcome to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: How are you, Erica? +
E: Marco, I’m doing really well! How about you? +
M: I’m doing great! I’m really excited, because today we’re talking about travel. +
E: That’s right, we’re gonna give you some real English to talk about travel. +
M: Exactly, English that you would use in everyday life, that you hear in movies, it TV 
shows. +
E: English people actually use. +
M: Exactly, so, why don’t you tell us a little bit about this lesson for today? +
E: Okay, so, today we are going to listen as a husband and wife get ready to go on a trip. +
M: Alright, that sounds a little bit complicated. +
E: Aha. +
M: Hehe. +
E: Well, let’s look at our two preview words. +
Voice: Vocabulary preview. +
M: Okay, so, the first word that we have is road trip. +
E: Road trip. +
M: Road trip. +
E: Road trip. +
M: Okay, so, road trips are really fun and interesting, right? +
E: Road trips are great. You get to get in a car with your family and drive on a vacation. +
M: Yeah, that was a really fun and they’re really popular in North America. +
E: Really popular. I’ve been on a million road trips. +
M: Hehe, Alright, we’ll talk about that a little bit later on, but now let’s take a look at our 
second word and it’s the car’s packed. +
E: The car is packed. +
M: The car’s packed. +
E: The car is packed. +
M: So, when your car is packed it means that… +
E: Everything you need is inside the car. +
M: Alright, so, your bags, your food, everything that you need for your trip. +
E: Exactly. +
M: Perfect! Okay, so, those were our two preview words and now we are ready to listen to 
the dialogue for the first time. +
E: Okay, this dialogue will be at normal speed, it will be fast, but don’t worry if you don’t 
understand everything. +
M: After ten minutes we promise you will understand everything in this lesson. +
A: So, are we all ready to go? +
B: Yup, I think so. The car’s packed; we have 
munchies and music, and the map’s in the car. +
A: Did you get the camera? +
B: Got it! Did you fill up the tank? +
A: Yup, it’s all set. +
B: You’re sure we’re not forgetting anything? +
A: I’m sure... we’ve got all our bases covered. +
B: Well… let’s get going then! I love road trips! +
B: Um... do you think we can make a pit stop? +
A: But we’ve only been on the road for ten minutes. +
B: I know, but I forgot to go to the bathroom before 
we left.
 
E: Well, she forgot to go to the bathroom. +
M: Yeah, I hate it when this happens. +
E: This happens to me on almost every road trip. +
M: Hehe. Okay, great, so, now it’s time for our “language takeaway”. We have three 
words for our language takeaway today. +
Voice: Language takeaway. +
E: And the first word is munchies. +
M: Munchies. +
E: Munchies. +
M: So, munchies are… +
E: Snacks. +
M: Snacks, food. +
E: Food, chips. +
M: Chips, cookies. +
E: Chocolate bars. +
M: All that good stuff. +
E: I love munchies. +
M: Hehe. And they’re really good when you’re taking a road trip. +
E: Indeed. +
M: Okay, so, let’s take a look at our second language takeaway word for today and it is fill 
up the tank. +
E: Fill up the tank. +
M: Fill up the tank. +
E: Fill up the tank. So, this is to… +
M: Put gas in your car. +
E: Put gas in the gas tank. +
M: In the gas tank, exactly. +
E: Alright, our last language takeaway today is… +
M: Pit stop. +
E: Pit stop. +
M: Pit stop. +
E: Make a pit stop. +
M: It’s a quick stop for you to get some gas, food, go to the bathroom. +
E: Yeah, a pit stop, a quick stop. +
M: Great, so, now it’s time for “Putting it together”. +
Voice: Putting it together. +
M: Okay, so, we have two great phrases for you today. Let’s take a look at the first one. +
E: We’ve got all our bases covered. +
M: We’ve got all our bases covered. +
E: We’ve got all our bases covered. +
M: This is a really great phrase and it’s really useful, right? +
E: Yeah, let’s listen to a couple of examples. +
Voice: Example one. +
A: We’ve got all our bases covered in case the hurricane hits. +
Voice: Example two. +
B: Okay, I have my keys, wallet and passport. Looks like I have all my bases covered. +
M: Okay, it’s clear now, but you can use this in a lot of different situations, right? +
E: You can use this in many situations. If I’m at work I could say “Alright, we’ve got a really 
good marketing plan, we’ve got all our bases covered”. +
M: Exactly, you have everything ready. +
E: You’re all prepared. +
M: Perfect! Alright, now let’s take a look at our second phrase and it’s let’s get going. +
E: Let’s get going. +
M: Let’s get going. +
E: Let’s get going. +
M: Alright, so, when you say “Let’s get going” it just means… +
E: Let’s start. +
M: Let’s start, let’s go. +
E: Yeah. +
M: Okay, but the interesting thing about this phrase is you can change it a little bit and it 
means something different. +
E: Aha, let’s listen to a couple of examples. +
Voice: Example one. +
A: I have the chicken, so, let’s get cooking. +
Voice: Example two. +
B: This house is really scary. Let’s get out of here! +
Voice: Example three. +
C: I have another meeting in twenty minutes, so, let’s get down to business. +
E: So, let’s get down to business, Marco. +
M: Let’s get down to business, let’s listen to the dialogue one more time, but this time… +
E: It’ll be a little bit slower and you’ll understand much better. +
A: So, are we all ready to go? +
B: Yup, I think so. The car’s packed; we have 
munchies and music, and the map’s in the car. +
A: Did you get the camera? +
B: Got it! Did you fill up the tank? +
A: Yup, it’s all set. +
B: You’re sure we’re not forgetting anything? +
A: I’m sure... we’ve got all our bases covered. +
B: Well… let’s get going then! I love road trips! +
B: Um... do you think we can make a pit stop? +
A: But we’ve only been on the road for ten minutes. +
B: I know, but I forgot to go to the bathroom before 
we left. +
E: So, that was a little more clear this time, wasn’t it? +
M: Yeah, you can definitely understand better about… what we’ve been talking about. +
E: Yep. +
M: Okay, so, now it’s time to look at “fluency builder”. Erica, why don’t you explain what 
fluency builder is? +
E: In fluency builder we give you some great useful phrases to help you express your ideas 
clearly. +
M: Okay, great, so, let’s look at fluency builder. +
Voice: Fluency builder. +
E: Alright, so, we all know how to ask the question “Are we ready to go?” +
M: That’s right, you can say “Can we go now?” +
E: Or you can say “Are we ready to go?” +
M: Exactly, but there’s another way that we can say this and we heard it in our dialogue, 
so, let’s listen.
Phrase 1: So, are we all ready to go? So, are we all ready to go? +
E: Wow! That sounds really good, it sounds a lot more fluent. +
M: Fluent, exactly. +
E: Yeah. Okay, so, another simple phrase that we all know how to say is “It is ready”. +
M: It is prepared. +
E: It is ready. +
M: Right. +
E: So, these examples are fine, they’re right. +
M: Uhu. Yeah, they’re correct English, no problem. +
E: But there’s another way to say this that we heard in the dialogue and it sounds a lot 
more fluent.
Phrase 1: Yep, it’s all set. Yep, it’s all set. +
E: It’s all set, that sounds much better. +
M: Yes, and we’re all set to listen to this dialogue for a third time and this time it’s gonna be 
at its normal speed. +
A: So, are we all ready to go? +
B: Yup, I think so. The car’s packed; we have 
munchies and music, and the map’s in the car. +
A: Did you get the camera? +
B: Got it! Did you fill up the tank? +
A: Yup, it’s all set. +
B: You’re sure we’re not forgetting anything? +
A: I’m sure... we’ve got all our bases covered. +
B: Well… let’s get going then! I love road trips! +
B: Um... do you think we can make a pit stop? +
A: But we’ve only been on the road for ten minutes. +
B: I know, but I forgot to go to the bathroom before 
we left.
 
M: So, Erica, you said you’ve been on a million road trips, what was that all about? Where 
have you been? +
E: Okay, well, maybe not a million road trips. +
M: Hehe. +
E: But many road trips. Every summer I used to go on a road trip with my family and we 
would drive many many hours, probably eight hours in one day up to Northern Canada. +
M: Oh, wow! Nice. +
E: Yeah, and then we would go camping and we would sleep outside and we would have a 
campfire at night, it was great. +
M: Oh, family road trip. +
E: Yeah, but maybe eight hours in a car is a little too long. +
M: Well, yeah. Well, I’ve been on a different kind of road trip with some, uh, buddies of 
mine, some friends. We would drive to Las Vegas. +
E: Really? +
M: Yeah, so, that’s really fun – a bunch of crazy guys in a car going to Las Vegas and then 
just having fun and talking about everything, so, that’s a much different experience than a
family road trip. +
E: Maybe that sounds a little bit more fun. +
M: Hehe. Yeah, eight hours in a car is not really that boring with all your friends. Alright, 
folks, we’re out of time for today, but be sure to visit our website at englishpod.com and
leave all your questions and comments. +
E: Okay, well, thanks for listening and until next time… Good bye! +
M: Bye! +
