= 0018
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! Welcome to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And today with Erica we have a very aggressive lesson for you today. +
E: That’s true. We’ve got a revolutionary lesson. +
M: Yes, today at EnglishPod we’re protesting. So, Erica, why don’t you tell us what a 
protest is? +
E: Well, uh, when you protest something, you go into the streets and show your 
disagreement. +
M: Right. And you yell and you have signs and everyone’s just protesting. +
E: And the news comes and if it… if it’s not clear now, it’ll be clearer after the dialogue, I’m 
sure. +
M: Definitely, definitely. So, why don’t we start with our “vocabulary preview”? +
Voice: Vocabulary preview. +
E: We heave two words in our vocabulary preview today. The first is bankrupt. +
M: Bankrupt. +
E: Bankrupt. +
M: Bankrupt. +
E: So, if a company goes bankrupt, what happens? +
M: It means that company doesn’t have any more money. +
E: So, it can’t pay salaries. +
M: It can’t pay anything. +
E: Can’t pay its bills. Yeah, uh, so, basically, if it’s bankrupts, it’s probably going to close. +
M: Exactly. +
E: Okay, our second word today is bailout. +
M: Bailout. +
E: Bailout. +
M: Bailout. +
E: B-A-I-L, bailout. +
M: So, bailout is when the government gives money to a company that is about to go 
bankrupt. +
E: That’s true. It’s emergency money that will help save the company. Well, these two 
words are taken directly from our dialogue. And in today’s dialogue we’re going to bring you
live to a newscast. +
M: Right, so, why don’t we just listen to the dialogue? +
A: This is Action 5 News reporter Sarah O’Connell 
reporting live from Washington, D. C. where a
protest has broken out. Thousands of angry citi-
zens are protesting against the proposed bailout
of the auto manufacturing industry! Sir, sir, Sarah
O’Connell, Action 5 news. Can you tell us what’s
happening? +
B: Yeah, yeah, we’re here because we feel this is 
an injustice! The financial irresponsibility of big
business has to stop! We’re there to show the
government that we don’t like the way that they’re
spending our tax dollars! +
A: Sir but what exactly is making everyone so angry? +
B: It’s an absolute outrage, Sarah, the US govern- 
ment wants to give 25 billion dollars of taxpayers’
money to the auto industry. These are companies
that have been mismanaged and are now nearly
bankrupt. +
A: I see. But, many supporters of the bailout argue 
that it could help save the jobs of millions of hard-
working Americans. +
B: That maybe true, and I for one don’t want to see 
anyone lose their job, but how can these CEOs
ask for a bailout when they’re making millions of
dollars? And then, they have the nerve to fly to
Washington in private jets! This costs hundreds
of thousands of dollars! And they’re asking for
money! That is just not right! +
A: Good point. This is Sarah O’Connell reporting live 
from Washington D. C., back to you, Tom. +
M: Wow, these people are really angry. +
E: I think they’re furious. +
M: Hehe. Well, I think they have some good points and we’ll talk about that later, but now… +
E: It’s time for “language takeaway”. +
Voice: Language takeaway. +
E: There’s some great language in this dialogue. A lot of language we use to express our 
anger. +
M: Right. And one of those words and the first one for language takeaway is injustice. +
E: Injustice. +
M: Injustice. +
E: An injustice. +
M: So, an injustice is something that isn’t fair. +
E: It’s totally unfair. +
M: It’s unfair, yeah. +
E: Uhu. +
M: This is an injustice. Let’s look at our second word - outrage. +
E: Outrage. +
M: Outrage. +
E: An outrage. +
M: So, Erica, why don’t you give us an example on how you would use outrage? +
E: There’s no more coffee! This is an outrage! +
M: Yeah, that ???. That’s an outrage! Okay. +
E: Let’s go to our next word now. +
M: Break out. +
E: Break out. +
M: Break out. +
E: Break out. +
M: So, we have some great examples on how we use break out, so, let’s listen. +
Voice: Example one. +
A: War is broken out in the Antarctica as countries of the world fight for control of the icy 
continent. +
Voice: Example two. +
B: Officials are warning that fight ??? could break out in the water regions. +
Voice: Example three. +
C: A forest fire broke out last night. +
E: Well, this is a wonderful phrasal verb that means… +
M: To begin suddenly. +
E: Okay, so, I think that’s pretty clear. +
M: Yeah. +
E: Yeah. +
M: Break out. +
E: Let’s go to our next word now. +
M: Mismanaged. +
E: Mismanaged. +
M: Mismanaged. +
E: So, when something is mismanaged, it’s… +
M: Not managed properly. +
E: Managed poorly. +
M: Poorly, right. +
E: Yeah. Our final word today is… +
M: Have the nerve to. +
E: Have the nerve to. +
M: Have the nerve to. +
E: I think this one also is a little bit difficult to understand. +
M: Yeah, but we have some great examples prepared for you, so, let’s listen to them. +
Voice: Example one. +
A: I’ve been in love with you since the third grade, but I didn’t have the nerve to tell you. +
Voice: Example two. +
B: I don’t believe it! You have the nerve to ask me for money when you know I’ve just lost 
my job. +
Voice: Example three. +
C: What?! You have the nerve to bring your new girlfriend to visit my mother! +
E: So, have the nerve to is like dare to do something, right? +
M: Yeah, how dare you. +
E: Yeah. +
M: Have the nerve to. It’s like I can’t believe you would do that. +
E: Uh-Yeah, I think that’s quicklier. [NOTE: it sounds like quickly + quicker; it’s kind of a 
casual but a bit controversial way of saying more quickly; sometimes quicklier means
“faster than quickly”] +
M: Uhu. +
E: Yeah. +
M: Okay. +
E: A lot of great words in our dialogue today, um, and also we have some really interesting 
grammar in today’s dialogue. +
M: Right, so, today let’s look at some “grammar breakdown”. +
Voice: Grammar breakdown. +
E: In this section, grammar breakdown, uh, we show you a particular grammar structure 
and explain a little bit about how that structure affects meaning. So, it’s not really about
getting the grammar perfectly right; it’s about understanding the meaning. +
M: Right. And in today’s lesson we saw some really great examples on how we used the 
present perfect tense. +
E: Let’s listen to an example from the dialogue. 
Example 1: where a protest has broken out; where a protest has broken out. +
E: See the verb here break out like “a protest has broken out” - happened in the past, 
right? +
M: Right. +
E: And it’s still going on now. +
M: Exactly. +
E: So, present perfect is used when we’re talking at… about event that happened in the 
past… +
M: Uhu. +
E: And it’s continuing on now. +
M: Exactly. +
E: Or is continuing to affect now. +
M: Exactly. +
E: Okay, I think that’s pretty clear. +
M: Yeah, but now, if you want to indicate or if you want to demonstrate that the action has 
finished, the event is over, then you would say it like this…
Example 2: a protest broke out; a protest broke out. +
M: This form… you see that the protest is over; it happened yesterday already. +
E: Right. And I think it’s really emphasizing the fact that it is no longer affecting the present 
moment. +
M: Exactly. So, remember the difference between present perfect and simple past. Now, 
if you want to know more about these tenses: present perfect and simple past, be sure
to go to our website at englishpod.com; in the grammar section you can find some more
great examples and a really clear explanation on how these tenses are formed. But now we
are ready to listen to our dialogue a second time. +
A: This is Action 5 News reporter Sarah O’Connell 
reporting live from Washington, D. C. where a
protest has broken out. Thousands of angry citi-
zens are protesting against the proposed bailout
of the auto manufacturing industry! Sir, sir, Sarah
O’Connell, Action 5 news. Can you tell us what’s
happening? +
B: Yeah, yeah, we’re here because we feel this is 
an injustice! The financial irresponsibility of big
business has to stop! We’re there to show the
government that we don’t like the way that they’re
spending our tax dollars! +
A: Sir but what exactly is making everyone so angry? +
B: It’s an absolute outrage, Sarah, the US govern- 
ment wants to give 25 billion dollars of taxpayers’
money to the auto industry. These are companies
that have been mismanaged and are now nearly
bankrupt. +
A: I see. But, many supporters of the bailout argue 
that it could help save the jobs of millions of hard-
working Americans. +
B: That maybe true, and I for one don’t want to see 
anyone lose their job, but how can these CEOs
ask for a bailout when they’re making millions of
dollars? And then, they have the nerve to fly to
Washington in private jets! This costs hundreds
of thousands of dollars! And they’re asking for
money! That is just not right! +
A: Good point. This is Sarah O’Connell reporting live 
from Washington D. C., back to you, Tom. +
M: Okay, Erica, so, what do you think about this situation? +
E: About the bailout of the auto industry. +
M: Yes. +
E: I think it’s a bad idea. +
M: Why? +
E: There’re so many reasons, I mean… I don’t think it’s fair for us as taxpayers. Well, I 
guess I’m not really an American taxpayer. +
M: Hehe. +
E: But I don’t think it’s fair for the taxpayers to have to pay for the mismanagement of 
these companies. I mean they’ve got so much debt; they’ve produced cars that nobody
really wants to buy and now they are in trouble and it’s not our money that should be spend
on saving them. +
M: Yeah, I would agree with you on that, but you do have to take into consideration the fact 
that if these companies go bankrupt, thousands of people will lose their jobs. And not only
the people that work at the factories, but also the people that work for other companies
that supply these factories. +
E: Yeah, I… I mean I see what you’re saying, Marco, but at the same time we can't support 
an industry that isn't working properly. I mean if one of… of these companies goes
bankrupt, it’s… it’s gonna be terrible, but it will force the other two companies, perhaps, to
manage themselves better, to streamline and become more efficient. I just think it will be
better in the future. +
M: Uhu, well, it could be, but also maybe all three companies can go bankrupt. It would be 
sad, because the American car… the American auto industry is a symbol of prosperity.
It’s… +
E: Yeah. +
M: It’s also the symbol of like… the American culture in general. +
E: I guess it’s true. +
M: So… so it would be a shame for it to go bankrupt, because everyone owns a car in the 
United States or most people. And it’s just something that we can’t lose. But it is an
interesting topic and we also want to know your opinions about this. +
E: Yeah, listeners, please come to our website at englishpod.com and tell us what you 
think about this bailout and about this lesson. +
M: On the website we’ll post a link to the news article, where you can read a little bit more 
about this, because this is actually going on now. +
E: That’s true. Well, everyone, thanks for listening and until next time… Good bye! +
M: Bye! 
 
