= 0020
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


E: Well, hello everyone! And welcome to EnglishPod! My name's Erica. +
M: And I'm Marco. +
E: So, Marco, how're you doing today? +
M: I'm doing great and I'm really looking forward to our lesson, because we're going to the 
eye doctor today. +
E: Okay, so, we've got an elementary lesson about going to the eye doctor. +
M: Yes! +
E: Well, let's get started then with our “vocabulary preview”. +
Voice: Vocabulary preview. +
E: We have three words today in our vocabulary preview. All three words come from our 
dialogue. Our first word is struggle. +
M: Struggle. +
E: Struggle. +
M: Struggle. +
E: So, Marco, when I struggle to do something, what does that mean? +
M: It means it's difficult, it means that you have a hard time, so you can't really do it very 
quickly. +
E: So, what you have to try really hard. +
M: You have to try really hard. +
E: Yeah, to do something that's difficult. +
M: Yes. +
E: Okay, our next word is… +
M: Blurry. +
E: Blurry. +
M: Blurry. +
E: Blurry. B-L-U-R-R-Y. +
M: Blurry. Whenever something is blurry, you can't really see it well. +
E: It's not clear. +
M: Right. +
E: That's right, everything will be blurry. +
M: Uhu. +
E: Okay. And our final word is… +
M: Prescription. +
E: Prescription. +
M: Prescription. +
E: Often when you go to the doctor and you need some medicine, he writes out a 
prescription. +
M: Right, a little paper that says all the medicine that you need and then you can go to the 
drug store and buy it. +
E: Exactly. +
M: Uhu. +
E: Okay, so, those three words you'll hear in today's dialogue and I think it's time we listen 
to the dialogue. +
A: Hello, Arthur. What seems to be the problem? +
B: Hey doc. Well, I think I might need glasses. I’m 
getting headaches, and I really struggle to see
things that are far away. But I have always had
20/20 vision. +
A: Sounds like you may be far-sighted. OK, then, 
cover your left eye and read the chart in front of
you. +
B: Mmm. . . X, E, R, 3, a question mark, and I can’t 
quite make out the other symbol but I think it’s the
peace sign. +
A: Wow, Arthur! You’re as blind as a bat! +
B: Yeah, I know, my vision is really blurry at times. +
A: Ok then, head on over to the other room and pick 
out some frames while I fill out your prescription. +
B: Thanks doc! +
A: Arthur, that’s the bathroom. 
 
E: Well, this guy really has poor vision, hey? +
M: Hehe. +
E: Well, actually, you know what, I've walked in to the bathroom, the men's bathroom, 
actually, instead of the women's bathroom. And that's not 'cause I wasn't wearing my
glasses. +
M: It's because you weren't paying attention. +
E: That's true. +
M: Hehe. Okay, let's take a look today at out “language takeaway”. +
Voice: Language takeaway. +
M: The first word on our language takeaway for today is twenty/twenty (20/20) vision. +
E: 20/20 vision. +
M: 20/20 vision. +
E: If I have 20/20 vision… +
M: It means that you have perfect vision. +
E: Which I do not have. +
M: Hehe. No, me neither, so, I… I usually wear glasses as well. +
E: Yeah. +
M: But, yeah, people that have 20/20 vision don't need glasses, they can see clearly with… +
E: And perfectly. +
M: And perfectly. +
E: Yeah. Next word is far-sighted. +
M: Far-sighted. +
E: Far-sighted. +
M: Far-sighted. +
E: So, if I'm far-sighted, I can't see very well, right? +
M: So, if you're far-sighted, you can't see things that are near. +
E: So, you can see things that are faraway. +
M: Right. +
E: But thing that are close are blurry. Okay. +
M: And the opposite would be… +
E: Near-sighted. +
M: And which is… +
E: You can see things that are close well… +
M: But not far. +
E: Yeah. +
M: Hehe. +
E: Okay. +
M: Far-sighted and near-sighted. +
E: Okay, so, our next word is make out. +
M: Make out. +
E: Make out. +
M: Make out. +
E: Make out, that's kind of a funny little phrase. And let's listen to a few examples of this 
phrase, so we can understand how it's used. +
Voice: Example one. +
A: I can’t make out what this says. The writing is too small. +
Voice: Example two. +
B: If you look carefully, you can almost make out a few of the stars in the sky. +
Voice: Example three. +
C: Can you see what’s written on the sign there? +
D: No, I can’t quite make it out. +
M: Okay, so, basically, make out is to see clearly. +
E: Exactly. +
M: Uhu, make out. +
E: To see. +
M: Okay. And our last word for language takeaway today is blind as a bat. +
E: Blind as a bet. +
M: Blind as a bet. +
E: So, this is a really funny sounding expression, one of these weird English idioms. +
M: Yeah, it's a really common expression that just means that you can't see. +
E: Exactly, so, it's not like you actually are blind, right? +
M: But you just really can't see very well. +
E: Okay. Alright, we saw four great words today in our language takeaway, now I think we 
can listen to our dialogue another time. +
M: But this time it's gonna be slower, so we can pick up all these great words that we just 
talked about. +
A: Hello, Arthur. What seems to be the problem? +
B: Hey doc. Well, I think I might need glasses. I’m 
getting headaches, and I really struggle to see
things that are far away. But I have always had
20/20 vision. +
A: Sounds like you may be far-sighted. OK, then, 
cover your left eye and read the chart in front of
you. +
B: Mmm. . . X, E, R, 3, a question mark, and I can’t 
quite make out the other symbol but I think it’s the
peace sign. +
A: Wow, Arthur! You’re as blind as a bat! +
B: Yeah, I know, my vision is really blurry at times. +
A: Ok then, head on over to the other room and pick 
out some frames while I fill out your prescription. +
B: Thanks doc! +
A: Arthur, that’s the bathroom. 
 
M: Alright, great stuff on our dialogue and with this we can start now with “Putting it 
together”. +
Voice: Putting it together. +
E: So, we saw a couple of useful phrases in this dialogue and I think we can show you how 
to use these phrases in a few different ways. +
M: Right, um, the first one that we have today is what seems to be. +
E: So, we heard in the dialogue the doctor said… +
M: “What seems to be the problem?” +
E: We can use this same expression in a number of different ways. Let's listen. +
Voice: Example one. +
A: What seems to be the problem? +
Voice: Example two. +
B: What seems to be the matter? +
Voice: Example three. +
C: What seems to be the trouble? +
M: Okay, so, with these examples we can see how we can use the phrase what seems to 
be in many different ways. +
E: Yeah, it's a great way of asking “What's the problem?” +
M: So, now let's take a look at another phrase. +
E: We heard in the dialogue the doctor said “Head on over to the other room”. +
M: Right, and with this phrase head on we can combine it with other prepositions to 
indicate another place. +
E: Exactly, let's hear three examples. +
Voice: Example one. +
A: Head on in. +
Voice: Example two. +
B: Head on out. +
Voice: Example three. +
C: Head on up. +
M: Okay, so, for example, we can say “Head on into the house, it's gonna rain soon”. +
E: Or we can say “Hey guys, let's head on out to the park”. +
M: Uhu, or I can also say “Head on up to my room, I’ll be there in a second”. +
E: Great! Those are some cool phrases. +
M: Right, and they're really useful. +
E: So, why don't we listen to our dialogue and maybe we'll hear them again. +
A: Hello, Arthur. What seems to be the problem? +
B: Hey doc. Well, I think I might need glasses. I’m 
getting headaches, and I really struggle to see
things that are far away. But I have always had
20/20 vision. +
A: Sounds like you may be far-sighted. OK, then, 
cover your left eye and read the chart in front of
you. +
B: Mmm. . . X, E, R, 3, a question mark, and I can’t 
quite make out the other symbol but I think it’s the
peace sign. +
A: Wow, Arthur! You’re as blind as a bat! +
B: Yeah, I know, my vision is really blurry at times. +
A: Ok then, head on over to the other room and pick 
out some frames while I fill out your prescription. +
B: Thanks doc! +
A: Arthur, that’s the bathroom. 
 
M: Okay, so, talking about going to the eye doctor today, I have a question for our 
listeners. +
E: A challenge for our listeners. +
M: A challenge. What's it called when you can't distinguish colors? +
E: So, like when you can't tell the difference between read and blue and green. +
M: Right, so, what is that condition called? So… +
E: There's like a technical term, we want the technical term. +
M: Hehe. We want the technical term. So, we'll be looking for it on our comments' page and 
be sure to… if you know the answer, post it. +
E: At englishpod.com, also if you have questions about today's lesson or any other lesson, 
please come and visit our website and, uh, ask us. +
M: Yeah, we hope to see you there, but until then it's… +
E: Good bye! +
M: Bye! 
 
