= 0026
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone and welcome to EnglishPod! Happy New Year! My name is Marco. +
E: And I’m Erica. +
M: Happy New Year! +
E: Happy New Year, Marco! +
M: It’s December thirty-first and we are on New Year’s Eve. +
E: That’s right and since it’s New Year’s Eve, we’re talking about New Year’s resolutions. +
M: Right, in many places it’s very common to make a promise for the New Year. +
E: Yeah. +
M: Something that you will change. +
E: A promise to yourself. +
M: To yourself. +
E: To change something. +
M: And that’s what our dialogue is about today, so, why don’t we take a look at our 
“vocabulary preview” for this lesson? +
Voice: Vocabulary preview. +
M: Okay, on vocabulary preview today we only have one word. +
E: Eating habits. +
M: Eating habits. +
E: Eating habits. +
M: So, what are eating habits? +
E: The regular way you eat. +
M: Right. +
E: So, if you eat healthy or if you eat lots of unhealthy food. +
M: Or even maybe what time you eat, right? If you eat everyday at certain time. +
E: Yeah. +
M: Eating habits. +
E: Okay. +
M: So, we’re ready to listen to our dialogue today and it’s gonna be a little bit fast, but don’t 
worry about it. +
E: We’ll come back and explain all of the key vocabulary after. +
A: So, did I tell you about my New Year’s resolution? 
I’ve decided to go on a diet. +
B: And you’re going to completely transform your 
eating habits, right? +
A: Exactly! I’m going to cut out all that junk I eat; no 
more chips, no more soda, no more fried food. +
B: I’ve heard this one before. +
A: But this time I’m going to stick to it. I really mean 
it! Trust me, Carol, I’m going to be a new man in
one year’s time! +
B: Well, I guess we’ll just have to wait and see. +
A: Thanks, honey, that was a great meal. I’m stuffed. 
Do we have any chips left?
 
E: So, Marco, do you think this guy will be successful in changing his eating habits? +
M: Hehe. Well, I guess he’ll never change, but this gives us a great opportunity to look at 
some great vocabulary in this lesson in “language takeaway”. +
Voice: Language takeaway. +
M: Our first word on language takeaway is junk. +
E: Junk. +
M: Junk. +
E: Junk. +
M: So, junk comes from junk food. +
E: Exactly. +
M: Unhealthy food. +
E: Yeah, fries, chips. +
M: Hamburgers. +
E: Yeah. +
M: All that junk. +
E: All that junk. +
M: Hehe. Okay, our second word for language takeaway – transform. +
E: Transform. +
M: Transform. +
E: Meaning… +
M: To change. +
E: Yep. +
M: Change. +
E: Uhu, so, this guy is going to transform his eating habits. +
M: He’s going to change his eating habits. +
E: Yeah, our third word is… +
M: Stuffed. +
E: Stuffed. +
M: Stuffed. +
E: I’m stuffed. +
M: So, we have some great examples on how we can use staffed and you’ll get the 
meaning from it. +
Voice: Example one. +
A: Come on! Have one more piece of cake. +
B: Oh, I can’t. I’m stuffed. +
Voice: Example two. +
C: Oh, I ate way too much! I’m stuffed! +
M: Okay, I’m stuffed. +
E: The feeling you get if you eat too much food. +
M: Right, I’m full. +
E: Yeah. +
M: Alright, so, these are some great words that you can use talking about food… +
E: And eating habits. +
M: And eating habits. Ah, and now we can listen to our dialogue a second time and this time 
like always it’s gonna be slow. +
A: So, did I tell you about my New Year’s resolution? 
I’ve decided to go on a diet. +
B: And you’re going to completely transform your 
eating habits, right? +
A: Exactly! I’m going to cut out all that junk I eat; no 
more chips, no more soda, no more fried food. +
B: I’ve heard this one before. +
A: But this time I’m going to stick to it. I really mean 
it! Trust me, Carol, I’m going to be a new man in
one year’s time! +
B: Well, I guess we’ll just have to wait and see. +
A: Thanks, honey, that was a great meal. I’m stuffed. 
Do we have any chips left?
 
E: There’s a lot of great language in this dialogue, isn’t there? +
M: Yeah, a lot of great language that we can take a look at with our “fluency builder”. +
Voice: Fluency builder. +
E: The first phrase we have for you is… +
M: Stick to it. +
E: Stick to it. +
M: Stick to it. +
E: Yes, we’ve got some examples of how this phrase is used, so, let’s listen. +
Voice: Example one. +
A: Quitting smoking is so hard. +
B: Stick to it! It’s good for you! +
Voice: Example two. +
C: I can’t solve this math problem! +
D: Stick to it! I’m sure you’ll get it! +
M: So, stick to it, right? +
E: Basically means keep doing it. +
M: Right. Even though English learning can be hard… +
E: You should stick to it. +
M: Stick to it. +
E: Yeah. +
M: Exactly. Okay, let’s look at our second phrase for fluency builder – I mean it. +
E: Mean it. +
M: Mean it. Well, this is a great way of saying… +
E: I’m serious. +
M: I’m serious. +
E: Yeah. +
M: I mean it. +
E: I’m not joking. +
M: I’m not joking. +
E: Uhu. +
M: Right. +
E: Yeah. And our final phrase in fluency builder… +
M: Cut out. +
E: Cut out. +
M: Cut out. +
E: Again, we’ve got some examples of this phrase as native speakers use it, let’s listen. +
Voice: Example one. +
A: You have to cut out the salt from your diet. No more chips, no more French fries, no 
more popcorn. +
Voice: Example two. +
B: It’s time for me to focus on my work. I’m going to cut out everything else from my life! +
M: Okay, so, cut out means… +
E: To remove. +
M: Completely remove. +
E: Take it away. +
M: Take it away. +
E: Yeah. +
M: Okay, some great language, some great phrases in our dialogue today. So, why don’t we 
listen to it a third time? And we’ll come back in a little bit. +
A: So, did I tell you about my New Year’s resolution? 
I’ve decided to go on a diet. +
B: And you’re going to completely transform your 
eating habits, right? +
A: Exactly! I’m going to cut out all that junk I eat; no 
more chips, no more soda, no more fried food. +
B: I’ve heard this one before. +
A: But this time I’m going to stick to it. I really mean 
it! Trust me, Carol, I’m going to be a new man in
one year’s time! +
B: Well, I guess we’ll just have to wait and see. +
A: Thanks, honey, that was a great meal. I’m stuffed. 
Do we have any chips left?
 
M: Okay, so, New Year’s resolutions are really common and popular thing in North America. +
E: It’s tradition to make a promise to yourself on New Year’s and stick to it throughout the 
whole year. +
M: Right, but the funny thing is that very few people actually stick to their New Year’s 
resolution. +
E: That’s true. +
M: The most common ones are I’m gonna quit smoking. +
E: Yeah. +
M: That never happens. +
E: No. +
M: I’m gonna go on a diet. +
E: Like this guy. +
M: Hehe. I’m gonna quit drinking. +
E: Aha. +
M: That almost never happens either. On New Year’s Eve you’re still drinking. +
E: I mean it’s… it’s a bad time, oh, come on! +
M: Hehe. And another really common one is I’m going to join a gym. +
E: That’s why gym membership sales are so high in January. +
M: Right, everyone joins a gym in January, but by… +
E: Come February… +
M: Yeah, and very few people in a gym. +
E: Yeah, so, Marco, do you have a New Year’s rev… resolution for this year? +
M: Yes, I have a New Year’s resolution and I resolve to continue bringing everyone some 
great lessons. +
E: Oh, that’s… that’s so good. +
M: And I think I can stick to that one. +
E: Yes, well, I… I do hope that you do stick to that one, Marco. +
M: We will, we will, but today we’re out of time. So, please go to our website and leave all 
your questions and comments… +
E: At englishpod.com. +
M: And, uh, we’ll see you there, but until then it’s… +
E: Good bye! +
M: Bye! 
 
