= 0041
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And today we’re going back to the movies. +
E: That’s right, we’ve got a great lesson today and I’m really excited about this dialogue. I 
think it’s fantastic. +
M: Hehe. We have an original EnglishPod production of a movie trailer. +
E: So, what is a movie trailer? +
M: Well, whenever you go to the cinema… +
E: Uhu. +
M: Um, before the movie starts you have previews of upcoming movies. +
E: So, like almost an advertisement for a future movie. +
M: Exactly. +
E: Okay. +
M: So, that’s a movie trailer and that’s what we’re bringing you today. +
E: A lot of great language you’ll commonly hear in action movies. +
M: Right, so, let’s start with “vocabulary preview”. +
Voice: Vocabulary preview. +
E: We have one word today – possess. +
M: Possess. +
E: Possess. +
M: Possess. +
E: So, when you possess something, you… +
M: Have it. +
E: Aha. +
M: It’s in your possession. You… +
E: Simple. +
M: You have it, right? +
E: Yep. +
M: So, in this dialogue our actors possess something very important. +
E: Uhu. +
M: So, let’s listen to the dialogue for the first time and it’s going to be a little bit fast and a 
little bit difficult to understand. +
E: But don’t worry, we’ll come back and explain all of the key language later. +
A: In a digital world, even the strongest must fight for 
survival. Two people, possess a secret so valu-
able, so powerful, they have to defend it at all
costs. +
B: I don’t care where they are, I don’t care what it 
takes... you find them and bring them to me! +
A: They only had one chance! And their chance was 
to fight back! +
D: You wanna play rough? Okay, say hello to my little 
friend! +
A: With a little help from a Governor... +
C: Listen to me! We have to get them outta there! 
No matter what! +
A: Nothing will prevent them from doing their job! 
Double the action. +
D: Get down! +
A: Triple the excitement. +
D: Get down again! +
A: This summer... nothing will stand in their way. +
B: I’m going to make him an offer he can’t refuse. +
A: Two hosts, one podcast, coming to a theater near 
you.
 
M: Wow, so, it sounds like a really good movie. +
E: I know. When is it coming out? +
M: Uh, I think in two thousand fifteen (2015). +
E: Okay, I’ll put that in my calendar. +
M: Hehe. Okay, let’s take a look at the vocabulary we saw in this dialogue in language 
takeaway. +
Voice: Language takeaway. +
M: In language takeaway today we have three words. What’s our first one? +
E: Survival. +
M: Survival. +
E: Survival. +
M: Survival. +
E: Well, survival is continuing to live even in really hard times. +
M: It comes from the verb to survive. +
E: Aha. +
M: Right? So, survival is the noun form. +
E: Right, so… so maybe you are lost in… in… +
M: The jungle. +
E: The jungle and you have to fight for survival. +
M: Right, you have to try to survive. +
E: Aha. +
M: Okay, our next word – defend. +
E: Defend. +
M: Defend. +
E: Defend. +
M: So, let’s listen to some examples of defend, so you can understand the meaning. +
Voice: Example one. +
A: We have to defend the castle. The army is trying to kill the king! +
Voice: Example two. +
B: The soldiers defended the base in the difficult battle. +
Voice: Example three. +
C: These new machine guns will defend us. +
M: So, basically, it’s to protect, right? +
E: Right, to protect from something that is really harmful. +
M: Okay, so, you would defend your children. +
E: Aha. +
M: You would defend your… +
E: Your house. +
M: Your house. +
E: Or your castle. +
M: Your dog, your cat. +
E: Yeah. +
M: Okay. And our last word on language takeaway – rough. +
E: Rough. +
M: Rough. +
E: R-O-U-G-H. Rough. +
M: Right, it’s got that “ugh”… +
E: Yep. +
M: Sound. +
E: Aha. +
M: So, it basically means… so when something is rough, it’s a little bit violent… +
E: And hard… +
M: Hard. +
E: Yeah. +
M: For example, boxing is a rough sport. +
E: Or hockey is also a rough sport. +
M: Exactly, so, you have rough sports or maybe even a person can be a little bit rough. +
E: Yes. Or that person can play rough. +
M: Play rough, exactly. +
E: Uhu. +
M: So, rough. Okay, so, we’re ready to listen to our dialogue again. +
E: And this time it’ll be a little bit slower, so, you can understand the language a little bit 
more clearly. +
A: In a digital world, even the strongest must fight for 
survival. Two people, possess a secret so valu-
able, so powerful, they have to defend it at all
costs. +
B: I don’t care where they are, I don’t care what it 
takes... you find them and bring them to me! +
A: They only had one chance! And their chance was 
to fight back! +
D: You wanna play rough? Okay, say hello to my little 
friend! +
A: With a little help from a Governor... +
C: Listen to me! We have to get them outta there! 
No matter what! +
A: Nothing will prevent them from doing their job! 
Double the action. +
D: Get down! +
A: Triple the excitement. +
D: Get down again! +
A: This summer... nothing will stand in their way. +
B: I’m going to make him an offer he can’t refuse. +
A: Two hosts, one podcast, coming to a theater near 
you.
 
M: So, we saw some interesting phrases in this dialogue. Let’s take a look at them in 
“fluency builder”. +
Voice: Fluency builder. +
M: The first phrase that we saw – at all costs. +
E: At all costs. +
M: At all costs. +
E: At all costs. +
M: So, let’s listen to some examples before we explain “at all costs”. +
Voice: Example one. +
A: I’ll protect my kids at all costs. +
Voice: Example two. +
B: We have to get this project done at all costs. +
Voice: Example three. +
C: You find those criminals at all costs. +
E: Well, if you’re going to protect your kids at all costs, you’re going to protect them even if 
it’s a really hard. +
M: Right, it doesn’t matter how hard it is or what you have to do. +
E: Exactly. +
M: You’ll do it. +
E: Uhu. +
M: At all costs. Now we have, um… now let’s take a look at our second phrase for fluency 
builder and it’s very similar to at all costs. +
E: Yeah, really similar. +
M: No matter what. +
E: No matter what. +
M: No matter what. +
E: No matter what. +
M: For example, I’m going to go on vacation no matter what my boss says. +
E: Nothing’s gonna stop you. +
M: Right, if he says no, I’m still going on my vacation. +
E: And I’m gonna protect my kids no matter what. +
M: Exactly, no matter what. +
E: I don’t have kids, though. +
M: Hehe. But you will protect them no matter what. +
E: If I had them. +
M: Hehe. Okay. Uh, and our last phrase – stand in their way. +
E: Stand in their way. +
M: Stand in their way. +
E: Stand in their way. +
M: So, let’s listen to some examples of “stand in someone’s way”. +
E: Uhu. +
M: And then we’ll come back and explain it. +
Voice: Example one. +
A: Don’t let anything stand in the way of your goals. +
Voice: Example two. +
B: I’m going to find that guy and nothing is going to stand in my way. +
Voice: Example three. +
C: I don’t care what happens. I’m gonna get that money and you’d better not stand in my 
way. +
M: So, when something stands in your way, it’s… +
E: It’s preventing you from reaching your goal. +
M: From reaching your goal, right? Or we can also have somebody standing in your way 
physically. +
E: Like really you’re standing close to me and I can’t pass through the door. +
M: Right, right. +
E: Yeah. +
M: So, maybe that person is at the door and… is standing in my way. I can’t go in. +
E: Yeah. +
M: Okay. +
E: But here we’re not really talking about a real thing, right? That you can touch. +
M: Right, it’s more of some obstacle that’s preventing you from reaching you goals or from 
doing what you want to do. +
E: Yep. +
M: So, now we can listen to our dialogue again and now you can understand these words 
that we’ve just talked about. +
A: In a digital world, even the strongest must fight for 
survival. Two people, possess a secret so valu-
able, so powerful, they have to defend it at all
costs. +
B: I don’t care where they are, I don’t care what it 
takes... you find them and bring them to me! +
A: They only had one chance! And their chance was 
to fight back! +
D: You wanna play rough? Okay, say hello to my little 
friend! +
A: With a little help from a Governor... +
C: Listen to me! We have to get them outta there! 
No matter what! +
A: Nothing will prevent them from doing their job! 
Double the action. +
D: Get down! +
A: Triple the excitement. +
D: Get down again! +
A: This summer... nothing will stand in their way. +
B: I’m going to make him an offer he can’t refuse. +
A: Two hosts, one podcast, coming to a theater near 
you.
 
E: I know that you’re a big movie fan, right? +
M: Yeah, I’m a big movie fan I usually watch maybe three or five movies a week. +
E: Really? +
M: Yeah-yeah. +
E: Wow! Many students of English like to watch movies as a way to improve their English. +
M: That’s one of the best ways to learn English… +
E: Uhu. +
M: As through songs and movies. +
E: What do you think of some useful movies that people can watch to practice English? +
M: Well, I would recommend children’s movies. +
E: Really? +
M: Yeah, they have simple vocabulary, but they have very common language. +
E: Uhu. +
M: And also what’s happening in the movie is very easy to understand and to follow. +
E: So. You can see the action and then hear the word. +
M: Exactly. +
E: Uhu. +
M: So, if you like to watch movies, rent a DVD or go buy a DVD, watch it in the original 
language… +
E: Yeah. +
M: With English subtitles. +
E: So, you should watch it in English. +
M: With English subtitles. +
E: Yeah, and what is subtitles? +
M: Subtitles are the words that you see at the bottom of the screen that translate… +
E: Okay. +
M: What the people are saying. +
E: Okay. +
M: Yeah, that’s the best thing to do. Try that exercise. If you have a pen and paper with 
you, it’s much better. You can pause the movie, write down the word you don’t understand
and then maybe review it later. +
E: That’s a really good tip. I always tell my students that they should watch movies, listen 
to music, read the newspaper and write down at least five new words or phrases a week. +
M: Yeah, yeah. +
E: Yeah. +
M: It’s a really good exercising, you’ll improve a lot. +
E: Yes. So, everyone, we want you to go and watch a movie in English. Turn on the 
subtitles and write down some new vocabulary. +
M: Exactly. And if you have any comments or questions or maybe even suggestions, you 
can come to our website at englishpod.com and leave them in our community page. +
E: Yeah, Marco and I are always around to help you and we love to hear about what you’re 
learning and what movies you’re watching. +
M: Exactly. So, we’re out of time today. We’ll see you guys next time. Until then it’s… +
E: Good bye. +
M: Bye. 
 
