= 0042
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And today with Erica we’re bringing you a great lesson about time. +
E: We need more of it. +
M: We need more time, right? +
E: Yeah. +
M: So, we’re gonna be teaching you how you can ask for more time. +
E: If you’re working on a project at work and you can’t finish it on time, you have to ask 
your boss for more time. +
M: Right, so, today in our dialogue Casey needs more time to put together a press kit. +
E: What’s a press kit? +
M: Good question. A press kit is something the marketing department will put together, 
basically, pictures, logos, um, all… information about the company. +
E: Uhu. +
M: So, when a newspaper or a magazine wants to write an article about them, so, they 
have something already prepared that they could give the newspaper or magazine. +
E: Okay. +
M: Okay, so, let’s listen to our dialogue for the first time and as always it’s gonna be at a 
normal speed, so, it might be a little bit difficult to understand. +
E: We’ll come back in one minute and tell you about some of the key language. +
A: So, Casey, how are things going with the photos 
for the press kit? +
B: Yeah, I’ve been meaning to talk to you about that. 
I might need to ask for an extension on that dead-
line. +
A: You’ve had over a month to get this finalized! Why 
are things delayed? +
B: Well, the thing is, we ran into a lot of problems. . . +
A: I’m not looking for excuses here. I just want to get 
this finished on time! +
B: I know, and I apologize for the delay. But some 
things were just beyond my control. I had trouble
booking the photographer, and then Michael was
sick for three weeks, so I couldn’t include him in
the photos, and the design team lost all the files,
so I had to re-do the pictures. +
A: I’m not going to put this off any longer, Casey! I 
want those photos ASAP!
 
M: Alright, so, Casey is in trouble, I think. +
E: Yeah, I think her boss is pretty upset. +
M: Yeah, well, let’s take a look at some of the language that we saw in this dialogue in 
“language takeaway”. +
Voice: Language takeaway. +
M: First word today is deadline. +
E: Deadline. +
M: Deadline. +
E: Deadline. +
M: So, Erica, what’s a deadline? +
E: It is the last possible date to do something. +
M: So, for example, when we were in school… +
E: Uhu. +
M: Our teacher would send us homework and say it was for Friday. +
E: So, the deadline was Friday. +
M: Was Friday. +
E: Uhu. +
M: Right? Or when you’re at work you have projects that you have to finish by a certain 
date. That’s your deadline. +
E: Exactly. +
M: Okay, let’s look at our next word – extension. +
E: Extension. +
M: Extension. +
E: Extension. +
M: So, extension and deadline go together, right? +
E: Exactly, if you can’t reach your deadline or you can’t make your deadline, you must 
ask for an extension. +
M: An extension. So, you ask for more time. +
E: Yeah, an extension is moving the deadline in the future. +
M: Alright, interesting. Let’s look at our next word – ran into. +
E: Ran into. +
M: Ran into. +
E: Ran into some problems. +
M: So, we ran into some problems in this dialogue. Let’s listen to some more examples of 
run into, so we can understand the meaning. +
Voice: Example one. +
A: We’ve ran into a storm on our way home. +
Voice: Example two. +
B: If you’re not careful now, you’re going to run into a lot of problems later. +
Voice: Example three. +
C: I ran into some trouble with my computer. +
M: Okay, good examples, so, it’s clear now, right? +
E: Right, if you run into problems, you meet some problems. +
M: Right. Many students say it in that way “I met some problems”. +
E: Yeah, but that’s wrong. +
M: Right. So, you would say “I ran into some problems”. +
E: Right, “I met some problems” is wrong, wrong, wrong. +
M: Okay, don’t say “met some problems”. +
E: I ran into some problems. +
M: I ran into, okay. And our last word for language takeaway – delayed. +
E: Delayed. +
M: Delayed. +
E: Delayed. +
M: So, when something is delayed, it’s… +
E: Late. +
M: Late. +
E: And the opposite is… +
M: On time. +
E: Yeah, so, your flight was delayed. +
M: Or your flight was on time. +
E: The project was delayed. +
M: Or your project was on time. +
E: Clear. +
M: Alright. So, now let’s go back to the dialogue. Let’s listen to it again. +
E: And this time it’ll be a little bit slower, so you can understand some of these phrases we 
just talked about. +
A: So, Casey, how are things going with the photos 
for the press kit? +
B: Yeah, I’ve been meaning to talk to you about that. 
I might need to ask for an extension on that dead-
line. +
A: You’ve had over a month to get this finalized! Why 
are things delayed? +
B: Well, the thing is, we ran into a lot of problems. . . +
A: I’m not looking for excuses here. I just want to get 
this finished on time! +
B: I know, and I apologize for the delay. But some 
things were just beyond my control. I had trouble
booking the photographer, and then Michael was
sick for three weeks, so I couldn’t include him in
the photos, and the design team lost all the files,
so I had to re-do the pictures. +
A: I’m not going to put this off any longer, Casey! I 
want those photos ASAP!
 
M: Okay, so, there were some really useful phrases that we saw in this dialogue. +
E: Yeah, some wonderful phrases that you can use when you want to ask for more time. +
M: Okay, so, let’s look at these phrases in “fluency builder”. +
Voice: Fluency builder. +
M: Alright, what’s our first phrase? +
E: I’ve been meaning to talk to you. +
M: I’ve been meaning to. +
E: I’ve been meaning to. +
M: Okay, we have some really great examples of how you can combine I’ve been 
meaning to with different verbs. +
E: Yeah, let’s listen. +
Voice: Example one. +
A: I’m sorry I haven’t called you yet; I’ve been meaning to, but I’ve been busy. +
Voice: Example two. +
B: I’ve been meaning to tell you, but John quit yesterday. +
Voice: Example three. +
C: I’ve been meaning to see that film for a while. +
M: I’ve been meaning to go to that restaurant, but I haven’t had time. +
E: So, you’ve been wanting to for a long time. +
M: Right. I’ve been thinking about it. +
E: Yeah. +
M: I’ve been planning to do it. +
E: But you just haven’t done it. +
M: I haven’t done it. +
E: Yeah. +
M: Maybe because I haven’t had time or money. +
E: Uhu. +
M: Okay. Good phrase. +
E: Our next phrase is… beyond my control. +
M: Beyond my control. +
E: It’s beyond my control. +
M: So, it means that I can’t control it. +
E: You can’t do anything about it. +
M: Can’t do anything about it. The weather is beyond my control. +
E: Right. Or relate with this project: because Jane was sick for one month, it was beyond 
my control. +
M: Okay. +
E: Uhu. +
M: It wasn’t you fault. +
E: No. +
M: Okay. And our last phrase for fluency builder – put this off. +
E: Put this off. +
M: Put this off. +
E: Put this off. +
M: So, let’s listen to some more examples of put this off before we explain the meaning. +
Voice: Example one. +
A: I’ve been putting off this project for a week and it’s due tomorrow! +
Voice: Example two. +
B: Can we put off our meeting to next week; I’m too busy right now. +
Voice: Example three. +
C: I’ve been putting off my e-mail all day and now I have fifty messages to respond to! +
E: So, Marco, when you put something off, you… +
M: Leave it for later. +
E: Okay. +
M: Right? So, maybe I have to write a report today… +
E: Uhu. +
M: But I’m gonna put it off till tomorrow. +
E: So, you’re gonna do it tomorrow. +
M: I’ll do it tomorrow. Okay, so we’ve seen some great words and some really good 
phrases, so, now let’s listen to our dialogue for the last time and then we’ll come back and
talk some more. +
E: Uhu. +
A: So, Casey, how are things going with the photos 
for the press kit? +
B: Yeah, I’ve been meaning to talk to you about that. 
I might need to ask for an extension on that dead-
line. +
A: You’ve had over a month to get this finalized! Why 
are things delayed? +
B: Well, the thing is, we ran into a lot of problems. . . +
A: I’m not looking for excuses here. I just want to get 
this finished on time! +
B: I know, and I apologize for the delay. But some 
things were just beyond my control. I had trouble
booking the photographer, and then Michael was
sick for three weeks, so I couldn’t include him in
the photos, and the design team lost all the files,
so I had to re-do the pictures. +
A: I’m not going to put this off any longer, Casey! I 
want those photos ASAP!
 
E: Well, Marco, do you think that Casey’s reasons for being late are good? +
M: I think so, because it wasn’t really her fault, the whole situation with, uh, photographer 
and then one of her coworkers was sick for three weeks. +
E: Yeah. +
M: It’s not really her fault, right? +
E: Right, but maybe the boss thinks that she’s making excuses. +
M: Yeah, maybe she’s making excuses. That’s really common like, for example, when we 
were kids, you would say “oh, you know, my dog ate my homework”. +
E: Right, but… that… really happened to me once. +
M: Hehe. Your dog ate your homework? +
E: My cat ate my homework. +
M: Your cat ate your homework. +
E: Yeah. +
M: And what did your teacher say? +
E: Well, actually I was a really good student, so, my teacher believed me. +
M: Hehe. Well, my teacher wouldn’t have believed me. +
E: Really? +
M: No, no, she would’ve… she would’ve called my parents most likely. +
E: Yeah, well, my… my cat really did eat my homework. And… I just left it on the table and 
it chewed it at all. +
M: That’s weird. Why would your cat do that? +
E: I don’t know. +
M: A lot weir excuses out there. +
E: Yeah. +
M: I was abducted by aliens. +
E: Aha. +
M: My mom accidentally mailed my homework to Africa. +
E: Really? +
M: Yeah, that was… +
E: Was it happen to you? +
M: Creative… +
E: Aha. +
M: Writing. +
E: Oh, Okay. +
M: Creative excuses. +
E: Well, I wanna hear from our listeners. I wanna know what excuses they’ve used for being 
late with something. +
M: So, send us your excuses, send us your comments and questions. Go to our website at 
englishpod.com, where Erica and I are always there to answer you questions. +
E: That’s right, Marco, and this is an elementary lesson, right? +
M: Exactly. +
E: But we also have intermediate and upper-intermediate and advanced lessons for 
you more fluent English speakers. +
M: Exactly, so, if you’re listening to us on iTunes, be sure to visit our website and come 
see what else we have to offer. +
E: Well, I think we’re out of time, but until next time… it's… Good bye! +
M: Bye! 
 
