= 0044
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And we’re bringing you another great elementary lesson for all our elementary 
learners. +
E: You know what, Marco, I think this lesson is so useful. This is language that you can 
actually use every single day. +
M: Exactly, everyday. Exactly, because today we’re gonna be teaching you small talk. +
E: So, what is small talk? +
M: Well, small talk is small conversation that you would have with people that you don’t 
know very well, but you still wanna be polite… +
E: Yes! +
M: Right? And you want to maybe… just… chat a little bit. Okay, so, let’s listen to our 
dialogue and as always it’s gonna be a little bit fast, but don’t worry about it. +
E: Cause we’ll come back in a minute and help you with some of the difficult language. +
A: Morning. +
B: Hi there Mr. Anderson! How are you on this fine 
morning? +
A: Fine, thank you. +
B: It sure is cold this morning, isn’t it? I barely even 
get out of bed! +
A: Yeah. It’s pretty cold, alright. +
B: Did you catch the news this morning? I heard that 
there was a fire on Byron Street. +
A: No, I didn’t hear about that. +
B: Did you happen to watch the football game last 
night? The Patriots scored in the last minute! +
A: No, I don’t like football. +
B: Oh. . . By the way, I saw you with your daughter at 
the office Christmas party. She is really beautiful! +
A: She’s my wife! Oh, here’s my floor! Nice talking 
to you. Goodbye. +
B: Sir this is the 56th floor! We are on the 70th! +
A: That’s okay, I’ll take the stairs! 
 
M: Okay, I think this guy was a little bit annoying. +
E: Yeah, Mr. Anderson really didn’t wanna talk to him, did he? +
M: Yeah, I think that was pretty obvious, he left the elevator in a hurry. Okay, let’s take a 
look at our language today in “language takeaway”. +
Voice: Language takeaway. +
M: Alright, what do we have today in language takeaway? +
E: Well, we’ve got four words and phrases and our first one is barely even. +
M: Barely even. +
E: Barely even. +
M: So, how do we use barely even? It’s a little bit difficult. +
E: It’s really similar to like almost couldn’t or almost nothing or almost can’t. So, we 
use it usually in a negative sense. For example, I could say “I was so busy today I could
barely even eat my lunch”. +
M: Okay, so, I can maybe say “it was so dark I could barely even see”. +
E: Yeah! +
M: Okay. +
E: Yeah, or “I’m so poor I can barely even pay my rent”. +
M: Okay, good. Barely even. +
E: Uhu. +
M: Alright, let’s take a look at our next one - catch. +
E: Catch. +
M: Catch. +
E: Did you catch the news? +
M: So, by did you catch the news you mean did you hear the news. +
E: Exactly. So, how else can we use this, did you catch? +
M: A really common one is “I didn’t catch your name”. +
E: Yeah, I didn’t hear you name. +
M: I didn’t hear you name. +
E: Yeah. Yeah, and we can also say “I didn’t catch what he said”. +
M: I didn’t catch what he said, yeah. +
E: Yeah. +
M: So, I didn’t hear. +
E: Yeah. +
M: Okay. Let’s look at our next word - by the way. +
E: By the way. +
M: By the way. +
E: By the way. +
M: Okay, so, let’s listen to some examples first of how we can by the way and then we’ll 
come back and talk more about it. +
Voice: Example one. +
A: Are you going to be at the meeting today? +
B: Yeah, I’ll be there. Oh, by the way, did you hear what happened today? +
Voice: Example two. +
C: By the way, I almost forgot to tell you, Maggie called. +
E: Okay, so, I see that when we say by the way, um, we’re introducing a point after we’ve 
already talked about something. +
M: Exactly. And maybe it’s not even related to the topic we were talking about. +
E: No, it’s a different topic. +
M: Different topic, right? +
E: It’s like saying “oh, I almost forgot to tell you”. +
M: Exactly. +
E: Uhu. +
M: So, it’s like “oh, Erica, don’t forget we have a meeting today, oh, and by the way, I like 
your new haircut”. +
E: Thanks, Marco. +
M: Alright, see? +
E: Yeah. +
M: That’s the way you would use by the way. Okay and our last word on language 
takeaway - take the stairs. +
E: Take the stairs. +
M: Take the stairs. +
E: Take the stairs. +
M: So, does it mean you’re gonna take them somewhere ??? +
E: No, no, you… No, you’re not taking them home with you. +
M: Hehe. It means you’re gonna go up the stairs. +
E: Uhu. +
M: Okay, so, take the stairs. +
E: Yes, and a lot of people might say use the stairs or go up the stairs, but our 
EnglishPod learners, they know, right? +
M: To use take the stairs. +
E: Yep. +
M: Take the stairs. Okay, so now we’re ready to listen to our dialogue again. We’re gonna 
slow it down a little bit. +
E: And this will help you to catch these phrases a little bit better. +
A: Morning. +
B: Hi there Mr. Anderson! How are you on this fine 
morning? +
A: Fine, thank you. +
B: It sure is cold this morning, isn’t it? I barely even 
get out of bed! +
A: Yeah. It’s pretty cold, alright. +
B: Did you catch the news this morning? I heard that 
there was a fire on Byron Street. +
A: No, I didn’t hear about that. +
B: Did you happen to watch the football game last 
night? The Patriots scored in the last minute! +
A: No, I don’t like football. +
B: Oh. . . By the way, I saw you with your daughter at 
the office Christmas party. She is really beautiful! +
A: She’s my wife! Oh, here’s my floor! Nice talking 
to you. Goodbye. +
B: Sir this is the 56th floor! We are on the 70th! +
A: That’s okay, I’ll take the stairs! 
 
M: Okay, so, now let’s take a look at ways to start up some small talk in “putting it 
together”. +
Voice: Putting it together. +
E: So, Marco, today we’ve got some great patterns or structures that you can use, uh, in 
s… in your small talk. +
M: Yeah, exactly, we saw some great patterns. Let’s start with the first one. It sure is cold 
this morning. +
E: It sure is cold. +
M: It sure is cold. +
E: It sure is cold. +
M: Okay, so, we can change it up a little bit and say it sure is hot. +
E: Uhu, or it sure is late. +
M: Okay, this sure is interesting. +
E: Uhu, or you could say he sure is smart. +
M: So, basically, you can change the adjective. +
E: Yes. +
M: Cold, hot, smart, hard… +
E: Yeah. +
M: …difficult. +
E: And when you say sure is, uh, this is a great way of emphasizing that you believe this 
adjective to be true. +
M: Okay, sure is. Now, what would be the answer to this? +
E: Well, in the dialogue, uh, Mr. Anderson said yeah, it’s pretty cold, alright. +
M: It’s pretty cold, alright. +
E: It’s pretty cold, alright. +
M: So, again, using the examples we used before we can say oh, it’s pretty hot, alright. +
E: Uhu, or it’s pretty late, alright. +
M: Or he’s pretty smart, alright. +
E: Uhu, or this is pretty interesting, alright. +
M: So, it means you’re agreeing with that person. +
E: Exactly. +
M: Okay, great. +
E: So, Marco, these things it sure is blank and yeah, it’s blank, alright. These can go 
together really well, can’t they? +
M: Yeah, as a question and answer format. +
E: Uhu. +
M: They go well. +
E: So, why don’t we listen to some examples of how these two phrases work together? +
Voice: Example one. +
A: It sure is a nice day today. +
B: Yeah. It’s nice, alright. +
Voice: Example two. +
C: The bus is sure late today. +
D: Yeah. It’s late, alright. +
Voice: Example three. +
E: This class is really hard. +
F: Yeah. It’s hard, alright. +
M: Okay, so, now let’s take a look at our next word in putting it together. Did you happen 
to? +
E: Did you happen to? +
M: Did you happen to? +
E: Did you happen to? +
M: Did you happen to see Bob this morning? +
E: I didn’t happen to see Bob. +
M: Hehe. So, it means like… +
E: Like did you by chance. +
M: By chance. Did you by chance see Bob… +
E: Yeah, yeah. +
M: …or something. +
E: Yeah. +
M: Okay, another example would be “did you happen to go to that restaurant I 
recommended?” +
E: Mm, or maybe “do you happen to have a pen?” +
M: “Do you happen to know where the bathroom is?” +
E: Yeah, that’s a really useful one. +
M: That’s a v… useful one. That’s basically how you would use this structure. Did you 
happen to. Do you happen to. So, now let’s listen to our dialogue for the third time and
I’m sure that you’ll be able to understand everything. +
A: Morning. +
B: Hi there Mr. Anderson! How are you on this fine 
morning? +
A: Fine, thank you. +
B: It sure is cold this morning, isn’t it? I barely even 
get out of bed! +
A: Yeah. It’s pretty cold, alright. +
B: Did you catch the news this morning? I heard that 
there was a fire on Byron Street. +
A: No, I didn’t hear about that. +
B: Did you happen to watch the football game last 
night? The Patriots scored in the last minute! +
A: No, I don’t like football. +
B: Oh. . . By the way, I saw you with your daughter at 
the office Christmas party. She is really beautiful! +
A: She’s my wife! Oh, here’s my floor! Nice talking 
to you. Goodbye. +
B: Sir this is the 56th floor! We are on the 70th! +
A: That’s okay, I’ll take the stairs! 
 
E: Alright, Marco, that was a really useful dialogue for daily life, wasn’t it? +
M: Yeah, I think you can find a lot of useful language there… +
E: Uhu. +
M: And that you can apply tomorrow. +
E: Yeah. Well, speaking of useful things, let’s talk a little bit about our website. +
M: Yeah, be sure to go to our website at englishpod.com where you can find other 
lessons as well. Maybe you’re an intermediate student or advanced. +
E: Yes! So, we’ve got intermediate, advanced, upper-intermediate lessons on our 
website. +
M: And a lot of other resources that you can explore. So, be sure to come to our website 
and leave all your comments, because Erica and I are always there and we’re really happy
to answer all of your questions. +
E: Okay, everyone! Well, we’re out of time, but until next time… Good bye! +
M: Bye! 
 
