= 0046
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! Welcome to another great lesson with us here at EnglishPod. My name 
is Marco. +
E: And I'm Erica. +
M: And today we're gonna be talking about an ER, an emergency room. +
E: Exactly, we're bringing you our very own ER drama here at EnglishPod. +
M: Yeah, doctor shows are very popular with people. Medical terms and all that staff. +
E: Yeah, so, we're gonna teach you some words that you might hear commonly in, uh, 
medical shows on TV or in movies. Um, this is really common language in television. +
M: Or even in at a hospital, right? +
E: Well, yeah! But… But let's hope our listeners don't have to face this. +
M: Okay, so, let's preview some words in “vocabulary preview”. +
Voice: Vocabulary Preview. +
M: Alright, so, what's our first word? +
E: Okay, the first word is CPR. +
M: CPR. +
E: CPR. +
M: So, that's pretty easy. What does that mean? +
E: Um, well, it… It's short for Cardio Pulmonary Resuscitation. +
M: Okay. +
E: Uh, that means anything to you? +
M: Hehe. Well, cardio is related to the heart. +
E: Aha +
M: Pulmonary refers to the lungs. +
E: Yep! +
M: Resuscitation means to come back to life. +
E: Yes! So, basically, CPS is… Um, you know, when someone stops breathing… +
M: Uhu. +
E: You put your mouth on their mouth and you breathe inside their lungs. +
M: Okay, to give them air. +
E: Ex… Yeah. +
M: Okay. +
E: So, CPR. +
M: That's CPR, okay. So, let's take a look at our next word - BP. +
E: BP. +
M: So, BP is short for… +
E: Blood Pressure. +
M: Blood pressure. +
E: Yeah. +
M: That's just the way that doctors use it in the emergency room. +
E: Exactly, pretty simple. +
M: Okay, so blood pressure. And our last word - Acute Respiratory Failure. +
E: Acute Respiratory Failure. +
M: So, what is that exactly? It sounds complicated. +
E: Um, basically, it's really serious… that you stop breathing. +
M: You stop breathing. +
E: Yeah. +
M: Okay. So, if you going to Acute Respiratory Failure then the doctor or somebody has to 
perform CPR. +
E: Right! +
M: Alright, cool. Okay, so, we've… So, we've previewed these three great words, now let's 
listen to our dialogue for the first time. It's gonna be really fast and you gonna have a lot of
drama in it, so, uh, don't worry if you don't understand everything. +
E: Yeah, we're gonna come back and teach you some of the important language. +
A: Help! Are you a doctor? My poor little Frankie has 
stopped breathing! Oh my gosh, Help me! I tried
to perform CPR, but I just don’t know if I could
get any air into his lungs! Oh, Frankie! +
B: Ellen, get him hooked up to a monitor! Someone 
page Dr. Howser. Get the patient to hold still, I
can’t get a pulse! Okay, he’s on the monitor.
His BP is falling! He’s flatlining! +
A: NOOOOOO! Frankie! Nurse! Do something! +
B: Someone get her out of here! Get me the de- 
fibrillator. Okay, clear! Again! Clear! Come on!
dammit! I’m not letting you go! Clear! I’ve got a
pulse! +
C: Okay, what’s happening? +
B: The patient is in acute respiratory failure, I think 
we’re going to have to intubate! +
C: Alright! Tube’s in! Bag him! Someone give him 
10 cc’s of adrenaline! Let’s go, people move,
move! +
A: Doctor, oh, thank god! How is he? +
B: We managed to stabilize Frankie, but he’s not 
out of the woods yet; he’s still in critical condi-
tion. We’re moving him to intensive care, but… +
A: Doctor, just do whatever it takes. I just want my 
little Frankie to be okay. I couldn’t imagine life
without my little hamster!
 
M: Wow! So much drama over a little hamster. +
E: Yeah, a little pet, hey? +
M: A little pet, the little hamster. +
E: Well, um, you know what, I can relate to this owner and, um, I'm gonna tell you a little 
bit more about that later. +
M: Yeah, I know you have a really good story about this. +
E: Yeah, but in the mean time, let's look at some great language in “language 
takeaway”. +
Voice: Language takeaway. +
M: Alright, so, let's take a look at our first word - intubate. +
E: Intubate. +
M: Intubate. +
E: Intubate. +
M: So, this is a medical procedure. +
E: Exactly! Um, when a patient can't breathe properly sometimes the doctor takes a log 
tube… +
M: Uhu. +
E: And puts it in to their mouth, um, and down their pipes, I guess, down their breathing 
tube… +
M: Right. +
E: So that they can breathe better. +
M: Okay, so, that's to intubate. +
E: Yes. +
M: Okay, so, once they've intubated the patient, they start to bag him. +
E: Yeah, bag him. +
M: Bag him. +
E: Bag him. +
M: Does that mean they like put a bag over that person' head or something? +
E: No, no, no, no, no… So, there is a bag attached to this intubation tube and you squeeze 
it to put air into the lungs. +
M: Okay, so, you squeeze this bag and it puts air… +
E: Yeah. +
M: Through the tube. +
E: I think this is just medical slang. +
M: Yeah, I guess, bag him…??? +
E: Yeah, but you hear it all the time on TV, so… +
M: Right. +
E: It's important our listeners know it. +
M: Okay. Let's look at our next word - critical condition. +
E: Critical condition. +
M: Critical condition. +
E: The patient's in critical condition. +
M: This condition means it's serious. +
E: Right, if a patient is in critical condition, um, they're either really really hurt, um, or 
really really sick and they could die pretty soon. +
M: Okay. So, you don't want to be in critical condition. +
E: No. +
M: Let's take a look at our next word - stabilize. +
E: Stabilize. +
M: Stabilize. +
E: Stabilize. +
M: So, when the doctors stabilize a patient they take that patient out of danger. +
E: Exactly! When a patient is stabilized, um, they probably won't die in five minutes. +
M: Okay. +
E: But they could still be really sick. They could be in critical condition, right? +
M: But it's under control. +
E: Exactly! +
M: Okay. +
E: Yeah. +
M: Stabilize. +
E: Uhu. +
M: Let's look at our last word - ICU. +
E: ICU. +
M: ICU. +
E: Intensive Care Unit. +
M: Okay, that's what it means. +
E: Uhu. +
M: Intensive care unit. +
E: Yep. +
M: So, that's a place where patients who are in critical condition are taken. +
E: Right. +
M: So, what's the difference between ICU and a regular room? +
E: Well, I don't know I've never been in one. +
M: Hehe. +
E: Um, but I think like patients are monitored, ah, regularly and I think there's, you know, 
maybe more… maybe there're… uh, more nurses and fewer patients, so, there's just a
higher lever of care. +
M: A higher lever of care. +
E: Yeah. +
M: Okay. Okay, so, it's time for us to listen to our dialogue again. Now try to catch all of 
these medical terms that we've just talked about and then we'll come back and explain a
few phrases. +
A: Help! Are you a doctor? My poor little Frankie has 
stopped breathing! Oh my gosh, Help me! I tried
to perform CPR, but I just don’t know if I could
get any air into his lungs! Oh, Frankie! +
B: Ellen, get him hooked up to a monitor! Someone 
page Dr. Howser. Get the patient to hold still, I
can’t get a pulse! Okay, he’s on the monitor.
His BP is falling! He’s flatlining! +
A: NOOOOOO! Frankie! Nurse! Do something! +
B: Someone get her out of here! Get me the de- 
fibrillator. Okay, clear! Again! Clear! Come on!
dammit! I’m not letting you go! Clear! I’ve got a
pulse! +
C: Okay, what’s happening? +
B: The patient is in acute respiratory failure, I think 
we’re going to have to intubate! +
C: Alright! Tube’s in! Bag him! Someone give him 
10 cc’s of adrenaline! Let’s go, people move,
move! +
A: Doctor, oh, thank god! How is he? +
B: We managed to stabilize Frankie, but he’s not 
out of the woods yet; he’s still in critical condi-
tion. We’re moving him to intensive care, but… +
A: Doctor, just do whatever it takes. I just want my 
little Frankie to be okay. I couldn’t imagine life
without my little hamster!
 
M: Okay, so, there're some really good phrasal verbs in this dialogue. +
E: Yeah, a couple of good phrasal verbs. +
M: Okay, so, let's take a look at these phrasal verbs in “putting it together”. +
Voice: Putting it together. +
M: Alright, so, what's our first phrasal verb today? +
E: Hook up. +
M: Hook up. +
E: Hook up. +
M: So, to hook up. +
E: So, when we… When we talk about hooking something up, um, we are usually talking 
about electronics. Right, Marco? +
M: Yeah, you usually hook up your TV… +
E: Yeah. +
M: Or your computer. +
E: Yeah. +
M: So, why don't we listen to some examples of how we would use hook up? +
Voice: Example one. +
A: I finally got a Nintendo V. Come on, help me hook it up to the TV. +
Voice: Example two. +
B: I don’t know how to hook up this new DVD-player. Can you help me? +
Voice: Example three. +
C: I just hooked up my new HDTV. Wanna come over and watch a movie? +
E: Great, so, you can see that there're few different, um, variations of this pattern here 
with the word hook up, because it's a phrasal verb. +
M: Exactly. +
E: And I think the same patterns could apply to our next phrasal verb. +
M: Hold still. +
E: Hold still. +
M: Hold still. +
E: Hold still. +
M: So the doctor needed the patient to hold still. +
E: Right, to stop moving. +
M: Stop moving, exactly. +
E: Uhu. +
M: Okay, let's listen to some more examples of hold still because again it's a really great 
phrasal verb that you can change up a little bit. +
Voice: Example one. +
A: If you don’t hold still, I can’t see if you have something in your eye. +
Voice: Example two. +
B: Hold still while she cuts your hair or else she might make a mistake. +
Voice: Example three. +
C: Hold still! You have a bee on your back! +
M: Okay, hold still. Great word. +
E: Yep. +
M: Hehe. +
E: Alright, one final phrase for you - out of the woods. +
M: Out of the woods. +
E: Outta the woods. +
M: Out of the woods. +
E: So, when someone's out of the woods, they're… +
M: Free from danger. +
E: Aha, safe. +
M: Okay, safe. +
E: Yeah. +
M: I guess it's kind of a saying. +
E: Yeah. +
M: Like “I'm out of the woods”. +
E: Yeah. +
M: I'm… +
E: Yeah. +
M: I'm free. I'm… I'm safe. +
E: I guess there're two variance of this phrase. We can say “I'm out of the woods” or “we're 
out of the woods” OR “I guess we're not out of the woods yet”. +
M: Aha. +
E: Yep. +
M: So, okay. Out of the woods. +
E: Uhu. +
M: Okay, so, now it's time for us to listen to our dialogue again and when we come back 
Erica's gonna tell us about her ER story. +
A: Help! Are you a doctor? My poor little Frankie has 
stopped breathing! Oh my gosh, Help me! I tried
to perform CPR, but I just don’t know if I could
get any air into his lungs! Oh, Frankie! +
B: Ellen, get him hooked up to a monitor! Someone 
page Dr. Howser. Get the patient to hold still, I
can’t get a pulse! Okay, he’s on the monitor.
His BP is falling! He’s flatlining! +
A: NOOOOOO! Frankie! Nurse! Do something! +
B: Someone get her out of here! Get me the de- 
fibrillator. Okay, clear! Again! Clear! Come on!
dammit! I’m not letting you go! Clear! I’ve got a
pulse! +
C: Okay, what’s happening? +
B: The patient is in acute respiratory failure, I think 
we’re going to have to intubate! +
C: Alright! Tube’s in! Bag him! Someone give him 
10 cc’s of adrenaline! Let’s go, people move,
move! +
A: Doctor, oh, thank god! How is he? +
B: We managed to stabilize Frankie, but he’s not 
out of the woods yet; he’s still in critical condi-
tion. We’re moving him to intensive care, but… +
A: Doctor, just do whatever it takes. I just want my 
little Frankie to be okay. I couldn’t imagine life
without my little hamster! +
M: Okay, Erica, so, what happened? What emergency did you have? +
E: Well, it was with my cat. +
M: Your cat. +
E: Yes! I had some people over for diner and, uh, it was maybe 1.30 in the morning. +
M: Uhu. +
M: And I went downstairs to let them out, um, and show them where the taxies were. And 
then I came up and I saw that the cat was gone, um, and it turned out that the cat fell out
of the window. +
M: Fell out of the window. +
E: Yeah! +
M: Alright, but our listeners have to know what story… what floor do you live on. +
E: Uh, the twentieth floor. +
M: The twentieth. +
E: Yeah! So, this is really dangerous, right? +
M: That's really high up. +
E: Yeah, um… So, I went outside and I was calling for my cat and it was like “Mr. Thin, 
where are you?” +
M: How did you know he fell out? +
E: I just knew. +
M: Yeah? +
E: Yeah. +
M: Mother's instinct. +
E: I guess so. And… +
M: Uhm. +
E: So, he was… he was calling back to me and I saw and picked him up and brought him 
into the house and… then we did bring him to the Vet and it was, you know, 2:30 – 3:00 in
the morning at this time and the Vet was like not very happy that he… we woke 'em up out
of bed. +
M: Hehe. But that was a really good emergency though. +
E: Yeah, so anyway, um, we brought him to the Vet. He was in critical condition for a couple 
of days. +
M: Uhu. +
E: Um, and then we had to keep him in the Vet.. uh, the Vet's ICU for about a week. +
M: Oh. +
E: Uh, he broke his back. He broke his… two of his legs, um… +
M: Wow! +
E: Yeah, and, so, he was in the hospital for three weeks and then at home, um, on bed 
rest for another three weeks, but… +
M: Wow! +
E: Now he's good as new. +
M: Good as new. +
E: Yeah. +
M: He used up one of his, uh, seven lives. +
E: Yes. +
M: Nine lives. +
E: Nine? Nine, yeah. +
M: I don't know. +
E: Um, I think maybe eight of his nine lives. +
M: Eight? He's only one… got one left. +
E: Yeah. +
M: Wow! That's an interesting story. I guess that's the inspiration under this dialogue. +
E: Exactly. +
M: Hehe. +
E: Sometimes, uh, we anglos really treats our cats and our hamsters and our dogs like 
they are children. +
M: Yeah, yeah. No, that's good. +
E: Yeah. +
M: Well, I'm glad Mr. Thin is okay and he is walking and good as new. +
E: Yep, good as new. +
M: So, maybe our users have some stories about, uh, their pets… +
E: Yes. +
M: Being taken to the hospital. +
E: I wanna hear. +
M: Yeah, that should be interesting. I've never had a pet actually break a leg or anything, 
so… don't have any pet stories this time. But, we wanna hear what you think, so, come to
englishpod.com, leave all your questions and comments and your stories. +
E: Yes. +
M: And we'll be there to answer them. +
E: Well, guys, thanks for listening and until next time… +
M: Good bye! +
E: Bye! 
 
