= 0050
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And we’re bringing you the third part of our suspense series of New guy in town. +
E: That’s right. What’s gonna happen today? +
M: Well, I don’t know, there’re still so many things that could happen. This guy is kind of 
weird. +
E: I know. Is he a vampire? Or like what’s going on? +
M: Yeah, and I would like to thank all our listeners for contributing and sending out their 
ideas of what they think happens in this third part. +
E: Yeah, I especially like the story about the rabbit. +
M: Yeah, the rabbit. That was a good one. +
E: Yeah, yeah. +
M: As promised we took the idea of one of our listeners and created the dialogue around it. +
E: Yes. +
M: And this time it was the contribution of Babardwan. +
E: Yeah, he gave us a great idea for this dialogue. +
M: Exactly, he gave us a really good idea, so thank you Babar and, um, this one is for you. 
In this dialogue we’re gonna be looking at some hospitality vocabulary. +
E: Yeah. Some… some phrases you can use, um, when you welcome someone to your 
house. Alright, well, um, we’ve got some language to preview, so, let’s turn now to
“vocabulary preview”. +
Voice: Vocabulary preview. +
M: On vocabulary preview we have the word appetite. +
E: Appetite. +
M: Appetite. +
E: Appetite. +
M: So, Erica, tell us about appetite. +
E: When you have an appetite, you… you’re… you’re hungry or you… you have a desire to 
eat food, right? +
M: Alright, so you can have a big appetite, a small appetite. +
E: Ugu. Really hungry, a little bit hungry. +
M: Okay. Let’s look at our next word - poison. +
E: Poison. +
M: Poison. +
E: Poison. +
M: So, poison could be a noun or a verb. +
E: Exactly. So, when you poison someone, um, you put something in their food or maybe in 
their drink, um, that makes them really sick and maybe even makes them die. +
M: Okay, so, to poison somebody. +
E: Yep, and the noun is actually the thing that you put inside the food or drink. +
M: So, usually poison is some sort of chemical substance. +
E: Yes. +
M: Snakes, for example, have poison. +
E: Yeah, in their teeth. +
M: Right, so, if you get bitten by a snake… +
E: You’ll get poisoned. +
M: You’ll get poisoned. Alright, so, let’s take a look at our dialogue for the first time and see 
why we’re talking about poison. Then we’ll come back and explain some great words. +
A: Please make yourselves at home. Let me take 
your coats. Dinner is almost ready; I hope you
brought your appetite +
B: Your house is lovely, Armand! Very interesting 
decor...very...Gothic. +
C: I think it’s amazing! You have such good taste, 
Armand. I’m thinking of re-decorating my house;
maybe you could give me a few pointers? +
A: It would be my pleasure. Please have a seat. Can 
I offer you a glass of wine? +
C: We would love some! +
A: Here you are. A very special merlot brought di- 
rectly from my home country. It has a unique in-
gredient which gives it a pleasant aroma and su-
perior flavor. +
C: Mmm... it’s delicious! +
B: It’s a bit bitter for my taste... almost tastes like... 
like... +
C: Ellen! Ellen! Are you okay? +
A: Did she pass out? +
C: Yeah... +
A: I hope that you didn’t poison her drink too much! 
You’ll ruin our meal!
 
M: Okay, so that was unexpected. +
E: I know, Lois, can you believe it? [NOTE: in the first part her name was Doris] +
M: Apparently Lois is helping Armand. +
E: I know. +
M: Maybe she’s a vampire. +
E: Alright, well, I really wonder what’s going to happen next. +
M: Well, see what happens next, but now let’s take a look at some of the language in 
“language takeaway”. +
Voice: Language takeaway. +
M: Alright, so we have a couple of words in language takeaway today, let’s start off with 
pointers. +
E: Pointers. +
M: Pointers. +
E: Pointers. +
M: So, to give somebody pointers… +
E: You give them some suggestions. +
M: Suggestions or tips. +
E: Exactly. +
M: Alright. So, suggestions or tips. Let’s listen to some examples of how you would use it. +
Voice: Example one. +
A: I want to dance salsa better. Can you give me a few pointers? +
Voice: Example two. +
B: I need some pointers on how to be a better manager. +
Voice: Example three. +
C: Let me give you a few pointers, so you can pass your exam. +
M: Alright, so pointers. It’s clear now. Let’s take a look at our next word - aroma. +
E: Aroma. +
M: Aroma. +
E: Aroma. This is a nice, round word, isn’t it? +
M: Yeah, aroma. +
E: Yeah. +
M: Well, this word makes you sound really educated. +
E: Yeah, yeah. +
M: Basically, it means… +
E: Smell. +
M: Smell. +
E: Yep. +
M: So, you could say, for example, "this coffee has a great aroma". +
E: Or maybe "this perfume has, uh, the aroma of roses and lavender". +
M: Nice, okay. Let’s take a look at our next word - bitter. +
E: Bitter. +
M: Bitter. +
E: B-I-T-T-E-R. Bitter. +
M: Okay, bitter. So, bitter is the opposite of… +
E: Sweet. +
M: Of sweet. +
E: So, it’s always hard to describe tastes, isn’t it? +
M: Yeah. +
E: But maybe we can… we can say a few foods that are bitter. +
M: Okay. +
E: So, chocolate, when it has no sugar is bitter. +
M: Okay. Or, for example, coffee without any sugar is also bitter. +
E: Yeah, and… sometimes red wine can be quite bitter. +
M: Uhu. +
E: Uhu. +
M: So, bitter. Okay, now let’s take a look at our last word - pass out. +
E: Pass out. +
M: Pass out. +
E: Pass out. +
M: It seems kind of easy. Pass… +
E: Uhu. +
M: And out. +
E: Yep. +
M: But it means something different. +
E: Yeah, when you put them together. +
M: What does it mean? +
E: Um, it means faint or become unconscious. +
M: Okay. +
E: So, imagine someone… when, you know, they’re… they’re standing up and then suddenly 
they start to move around and then fall over to the ground. +
M: Okay, pass out. +
E: Yes. +
M: This usually happens when you get really really drunk. +
E: Maybe… sometimes also when… maybe you’re pregnant you might pass out. +
M: Right. Okay, to lose consciousness. +
E: Yes. Marco and I have a coupe of examples of this word for you. +
Voice: Example one. +
A: I drank so much last night that I passed out at my friend’s house. +
Voice: Example two. +
B: She was standing in the sun too long, so she passed out right in front of me. +
Voice: Example three. +
C: My sister passes out whenever she sees blood. +
M: Alright, so, let’s listen to our dialogue again. Now we’re gonna slow it down a little bit. +
E: And you’ll be able to hear these words that we just talked about. +
A: Please make yourselves at home. Let me take 
your coats. Dinner is almost ready; I hope you
brought your appetite +
B: Your house is lovely, Armand! Very interesting 
decor...very...Gothic. +
C: I think it’s amazing! You have such good taste, 
Armand. I’m thinking of re-decorating my house;
maybe you could give me a few pointers? +
A: It would be my pleasure. Please have a seat. Can 
I offer you a glass of wine? +
C: We would love some! +
A: Here you are. A very special merlot brought di- 
rectly from my home country. It has a unique in-
gredient which gives it a pleasant aroma and su-
perior flavor. +
C: Mmm... it’s delicious! +
B: It’s a bit bitter for my taste... almost tastes like... 
like... +
C: Ellen! Ellen! Are you okay? +
A: Did she pass out? +
C: Yeah... +
A: I hope that you didn’t poison her drink too much! 
You’ll ruin our meal!
 
M: Alright, so, interesting story. +
E: Yes. +
M: We have some great phrases that we’ve used here, so, let’s take a look at them in 
“fluency builder”. +
Voice: fluency builder. +
E: We’ve got four phrases for you that are great to use when you want to welcome 
someone into your house or into your office or anywhere, really. +
M: Exactly. So, why don’t we take a look at the first one? +
E: Please make yourselves at home. +
M: Please make yourselves at home. +
E: Please make yourselves at home. +
M: So, this is a very common phrase when you invite somebody to your house. +
E: Yeah. +
M: You… you always use this phrase. +
E: Yeah, it’s… it’s like make yourself comfortable, relax, sit down. +
M: Yeah, don’t worry about it, like my house is your house. +
E: Exactly. Please make yourself at home. +
M: Okay, good one. Usually people arrive to a party or to a dinner with jackets, coats, 
scarves. +
E: Yeah, uhu. +
M: All that stuff. So, this next phrase is really handy. +
E: Let me take your coats. +
M: Let me take your coats. +
E: Let me take your coats. +
M: So that means "give me your coats and I’ll put them in the closet". +
E: Right. +
M: Let me take your coats. +
E: And then a good host would always offer a drink, right? +
M: Exactly, water… or in this case wine. +
E: So, they would say can I offer you a glass of wine? +
M: Uhu. Or sometimes you could say "can I offer you a glass… can I offer you something to 
drink?" +
E: Yeah. So, can I offer you a glass of wine? +
M: Can I offer you a glass of wine? +
E: Uhu. +
M: You offer me a glass of wine. I say "yeah, sure, I’ll take a… glass of wine". +
E: Alright, and then I would use our next phrase - here you are. +
M: Here you are. +
E: Here you are. +
M: Exactly, it doesn’t mean that "you are here". +
E: No. +
M: Hehe. It’s saying to someone "here it is", "take it". +
E: Yes, yes. +
M: Right. +
E: You know what, this is a really really great phrase. A lot of people who are learning 
English don’t say this. +
M: Uhu. +
E: But it’s really common, really natural and all… if you use it, you’ll sound really great. +
M: Uhu. Here you are. Exactly. +
E: Here you are. And… +
M: Here you are. +
E: You can use this anytime you give someone something. +
M: Right, so if you give somebody a pen or a pencil or a notebook. Here you are. Here it is. +
E: Uhu. Yeah. +
M: Okay. Great words, so, let’s listen to our dialogue one more time and then we’ll come 
back. +
A: Please make yourselves at home. Let me take 
your coats. Dinner is almost ready; I hope you
brought your appetite +
B: Your house is lovely, Armand! Very interesting 
decor...very...Gothic. +
C: I think it’s amazing! You have such good taste, 
Armand. I’m thinking of re-decorating my house;
maybe you could give me a few pointers? +
A: It would be my pleasure. Please have a seat. Can 
I offer you a glass of wine? +
C: We would love some! +
A: Here you are. A very special merlot brought di- 
rectly from my home country. It has a unique in-
gredient which gives it a pleasant aroma and su-
perior flavor. +
C: Mmm... it’s delicious! +
B: It’s a bit bitter for my taste... almost tastes like... 
like... +
C: Ellen! Ellen! Are you okay? +
A: Did she pass out? +
C: Yeah... +
A: I hope that you didn’t poison her drink too much! 
You’ll ruin our meal!
 
M: Okay, so, Armand is a pretty good host he offered them a Merlot. +
E: Yeah, which is a type of wine. +
M: A type of wine. +
E: Yeah. +
M: And this is really interesting because there’re many types of wines. +
E: Yes. +
M: Do you know any? +
E: I know a lot! +
M: Alright, so… +
E: Yeah. +
M: Give us some pointers here. +
E: Alright, merlot is probably like the most common red wine, right? +
M: Uhu. +
E: Um, and Merlot is actually the grape… variety… var… +
M: The grape variety. +
E: Varietal as it's called in wine-speak. +
M: Wow! Varietal. +
E: Yeah. Well, right now, um, I’m really liking to drink Tempranillo, which is a Spanish 
wine. +
M: Tempranillo. +
E: Yep. +
M: Really? +
E: Yeah. +
M: And, that… Is that also the type of grape? +
E: Yes. +
M: Oh, nice. +
E: Yeah. +
M: Usually we would say red wine or white wine, right? +
E: Yeah. +
M: But the varieties depending on the grapes is what gives them their names. +
E: Uhu. +
M: So, we also have a couple of other like maybe you have a Chardonnay. +
E: Uhu, white wine. +
M: White wine. You have a Cabernet Sauvignon. +
E: Red wine. +
M: Red wine again. +
E: Yeah. +
M: And my personal favorite is a Carménère. +
E: Oh, yeah, that’s a nice wine. +
M: That’s a nice wine. +
E: Yeah. +
M: And it’s not very common anymore. +
E: Yeah. +
M: Apparently, the grape isn’t growing very well in France anymore… +
E: Yeah. +
M: Or in Spain. +
E: Yeah. +
M: So, from what I understand it’s only in Chili and Argentina. +
E: Uhu. +
M: It’s a really good one. +
E: Actually, Argentina makes really good Carménère. +
M: Yeah. +
E: But, you know who else makes god wine? +
M: Who? +
E: Canadians. +
M: Really? +
E: Yes. +
M: Canadian wine. +
E: Yeah, um, you almost never find it outside of Canada, but there is one region in the 
western part of the country that makes really really good wines, especially some nice, uh,
Pinot Noir… +
M: Nice. +
E: And some good white wines. +
M: Wow. +
E: Um, Okanagan Valley, check it out. +
M: Nice! +
E: Yeah. +
M: Alright, well, what about in your countries? Do you produce any wine or maybe any 
other type of drink? +
E: Yes. +
M: Right? Many countries have their own types of drinks, so, we wanna about it. +
E: Yes. +
M: Tell us. +
E: And many countries have different traditions to be hospitable… +
M: Exactly. +
E: To be welcoming. +
M: Yeah, that’s a good one. +
E: Yeah. So, visit our website englishpod.com, leave all your comments, tell us about how 
you welcome people into your house. +
M: Alright, and we’ll be there to answer them, but we gotta go now, so… +
E: Until next time… Bye! +
M: Good bye! +
