
= 评判(v.)电影
:toc:
:toclevels: 4
:sectnums:


---

== **核心底层思考**

==== 拍电影, 做影评人, 都锻炼不了大脑成为"谋事者", 只是工具人 -- 琢磨"艺'的(虽然带到人性).

- 摄影是"视觉语言", 音乐是"听觉语言", 写文章是"文字语言". "内容创作"中, 无论何种工作，都是在考虑一个目的: 如何更逼真地描绘出你想讲的故事，它们的底层目的其实是完全同一的 -- 都是为了实现这同一个目的. -- 讲故事而已.

.标题
====
例如：电影节的工作，每天都要看四五部电影, 我得了“电影眼”病——眼睛又疼又累，走在路上不管看什么，都好像是在透过一个矩形银幕看电影。
====

- 这个工作也是把大量时间浪费在看垃圾上. 虚耗光阴. 即使是一直在看电影好片, 也是肤浅的. 视频的信息密度很低. 宁可去看书了.  +
所以影评**这个职业, 不会令你变成"谋事者"的身份. 依然在浪费大脑锻炼. 这个工作的注意力只盯着那狭窄的"如何讲故事"上, 一切手段(视觉语言, 听觉语言, 文字语言, 只为"讲好故事"服务 -- 所以依然只是个工具人的身份.**

- 好电影有很多, 你不需要都去看, 也没必要浪费那么多时间. 你只需要对少数好电影, 做分析和学习即可. **相当于英语中的"精度"做法. 而不要去做"泛读"或只在做"泛读".**

---

==== 我的架构建立方法 : 1.从要解决的"问题"出发, 2.寻找解决方法, 3.及判断该方法的ROI, 及创新程度

以"问题"为出发点, 来建立架构:

[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.我要解决什么问题?
|艺术中就是"心理学问题" -- 想达到的目的: 就是促使观众产生某种情绪.
|2.实现的各种方法, 有哪些?
|- 方法也只是工具, 要分析各自的利弊.
- 它们是否能达到你想实现的 最终效果和目的. 效果度高低如何?
- 这些方法, 是传统的, 还是创新的, 业界前沿的?
- 你为此付出的成本,是否大于收益? ROI如何?
|===

====== 即, 思考任何现象与事情, 要以这三点为框架来做思考:

1.它被人去做, 背后想要得到的"目的"是什么? (即背后动机)

2.能达到该"目的"的方法, 手段, 有哪些? +
你要分解它里面的所有元素, 知道它们的"语言方法"(视觉语言,听觉语言, 文字语言), 对传达"故事"各自起到怎样的作用? 它们对人的生理、心理、情感甚至潜意识, 各自会产生何种效果?
(这和我对"设计"进行分解, 分析各元素会给人带来何种情绪体验, 以形成自己的"方法论", 是异曲同工的.)

3.采用的"该方法", 投资回报率如何? 是亏本的, 还是赚到的? 即, 它真的起到作用了吗? 起到多少作用? 并且ROI如何, 回报与付出, 合算吗? +
以及, "该方法", 是依然属于"传统"的,  还是是"新技术, 新办法, 全新创新"的?


---

== ---------- ----------

---

你作为创作者(导演和编剧本人), 要思考这几个问题:

== **自己的"创作追求"是什么?**

==== 电影一定要表达出导演个人化的价值观, 和审美品味

[cols="1a,1a" options="autowidth" ]
|===
|优秀的导演 -> 富有自己的野心和想法 |烂导演 -> 只是在交"作业", 而不是在创造"作品"

|你作为导演, 就要为影片注入个人风格 (xx作品).
**既然由你来导演这部影片, 那一定就是反映的你的想法和价值观, 而不是别人的. 否则还要你来拍干嘛?** 随便找个人去拍就行. 很多自编自导型导演, 他们的作品无疑都能反映导演本人的思想、
品位、观点以及执念。 +
(想想为什么观众喜欢看 Zack Snyder 版的<正义联盟>)

|平庸的作品, 就是给人感觉: 它不是诞生于个人的独特想法，而是诞生在好莱坞流水线模式下，平庸、无趣. **他们的电影毫无"个人特色", 或者"作者表达"可言。**

差劲的导演只会这样拍 —— 一个主镜头，一个中景特写，再加上一系列的特写镜头——然后将这些镜头随随便便剪到一块儿，电影就算完成了。(**好的导演会在每部电影中注入自己的独特风格，由此打造的观影体验，远比看着画面简单地在特写镜头、中景镜头和主镜头之间来回切换, 要有趣得多。**)

.标题
====
差劲的导演, 他们只满足于拍摄“ 覆盖镜头”（coverage）。所谓的“覆盖镜头”，就是给每场戏的环境随随便便拍一个定场镜头，再加上一系列中特写镜头（medium close-up，即拍摄人物胸部以上的部分）和特写镜头（close-up），然后在这两类镜头之间机械地来回切换。 +
这种拍法效率高、很实用，但也毫无想象力可言，这正是阿尔弗雷德·希区柯克最鄙视的“看人说话的电影”（pictures of people talking）。
====

- 他们要么随便剪辑, 不是在引导观众。(**好的导演会通过各种手段, 不断影响观众的感知与预期 -- 引导我们的眼睛和情绪, 心情.**)
- 要么通过过度剪辑的特写镜头, 对观众进行过多的引导，让我们没有选择的余地。
|===

---


====== 有品味
并不是说风格端庄得体、画面好看就叫“有品位”. **品位就是一种"审慎但绝不沉闷的平衡感".**

---

==== 好的电影, 能够提出重要的问题 -> 人生的问题, 社会的问题

[cols="1a,1a" options="autowidth"]
|===
|“值得拍”的主题 |差的电影主题

|**“值得拍”的电影，会反映我们人生的问题(历史、现代生活、人性、希望、绝望等), 这个世界的问题. 传递强烈的情感 -- 让观众陷入难以抉择的难题中，反省自己根深蒂固的某些观念**, 让我们被电影重塑.

.标题
====
例如：表面上, 《不羁夜》（Boogie Nights）是对七十年代洛杉矶色情业工作者的淫猥一瞥，但实际上，它想表达的是个人在"站队文化"中寻找自我，反映人们的价值观与身份, 是如何随着科技的发展而变化，以及电影媒介本身的浪漫与脆弱。
====

.标题
====
例如： 表面上，《正午》是一部小镇警长式西部片，讲述警长努力在镇上寻求帮助却无人响应，最后只能孤身对抗犯罪团伙的故事。但它底层的内核主题, 是在控诉民粹主义盛行下的政治怯懦。
====

|====== 廉价心灵鸡汤

即: 只表现最浅薄的"真善美".

====== 灌输说教

即 : 主题过于直白、恨不得打在广告牌上直接告诉你. 这样的影片会让观众感觉在被灌输思想，而不是受到启发或获得娱乐。  (中国春晚的小品) +
一个好的剧本, 要让观众自己去思考，挖掘其中的深意。(展现而不讲述)

|===



---

==== 一定要保护自己对电影的设想

**导演每时每刻都要牢记, 一定要保护自己对电影的设想. 否则只要他犹豫不决, 放松信念和标准, 图方便求省事, 那拍出来的电影就很可能面目全非。** +
- 是满足于拍摄一个平庸的剧本，还是坚持多做一次重写？ +
- 是否愿意为了选出一个合适的演员, 而暂停制作？

导演必须处理好片拍期间的各种意外情况和问题. +
- 当一阵浓雾突然在镜头中出现时, 要作何反应？ +
- 当科帕卡瓦纳餐厅, 拒绝摄制组在入口处拍摄时, 又要如何应对？

优秀的导演: +
绝不会让你看出某天的天气, 是如何影响某个重要镜头的拍摄. +
也不会让你看出某个演员在某场戏中的演技, 不如另一个演员.

---

==== 导演必须展现出自信，能让整个团队有安全感.

---

== 演员的作用是什么? --只是一个诠释工具

**演员只是一个诠释工具，观众是通过他们来理解影片故事的意义与情感。** 演员在表演中仅作为"工具"而在——通过他们的脸、身体和声音, 和他们的精神活动，通过思考、分析、想象，来把角色演活。

---

== ---------- ----------

---

== **如何建立起观众的"心理代入感"?**

==== 方法: 坏的电影都在讲剧情; 好电影都在讲人(人性), 哪怕这些角色并不是人类。

这部电影只是一个剧情PPT，还是一个引人入胜的故事？我讨厌剧情，但我喜欢故事。

一部改编作品的失败，最大的原因在于编剧**一味照搬剧情和角色，没有仔细研究原作，去挖掘其中情感、内涵、隐喻，甚至是诗意。拜他们所赐，将原本富有深度和质感的作品, 被改编得平庸而肤浅。**

---

==== 方法: 要展现, 要不要去阐释 exposition

.标题
====
▶ exposition : +
/ˌekspəˈzɪʃn/  a full explanation of a theory, plan, etc. （理论、计划等的）解释，说明，阐述 /（产品的）展销；商品交易会；产品博览会 +
=> ex-向外 + -posit-放置 + -ion名词词尾
====

阐释（exposition）是编剧的一大禁忌。“阐释”就是通过对白, 来解释角色的背景, 或展现内在的情感。(#**你自己看电影, 能通过亲自体验与感悟, 得出你自己的启示;  而你去看"xx分钟带你看完xx电影"这种, 就是在听阐释. 就是经过别人过滤后出来的东西了, 对你有没有价值就很值得怀疑.**#)

====== 心理学原理:

为什么exposition是糟糕的?  原因它会带来这些负面作用:

[options="autowidth"]
|===
|Header 1 |Header 2

|-> 阐释会对影片的"可信度"造成负面影响.
|在现实生活中，真的会有人这样说“我做了×××（菜名），这是你最喜欢的一道菜”吗？

|-> 阐释会破坏影片的节奏
|特别是当角色突然停止行动，开始讨论他们早就心知肚明的事情，只为让观众了解情况。
|===

====== 具体方法:

用其他更好的方法来实现 exposition, 如:

[options="autowidth"]
|===
|Header 1 |Header 2

|边走边聊
|让角色在匆匆穿过走廊的时候快速对话.
|===

---

==== 方法:真实, 才会令人相信, 进而引发情感

====== 心理学原理

[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|-> 真情才会打动人
|一部电影一定要让观众觉得可信，细到每一个词、每一个眼神、每一个领带夹、每一个茶杯，**都要"真实可信"。只有这样, 才能激发出他们的情感, 而不会因为"太假"而引不出真情.**

- 例如：很多灾难特效大片, 打动不了观众, 就是因为它们都只是呈现灾难和奇观的载具.  这些电影只有剧情，没有故事；只有角色，没有人；只有刺激，没有感情。总而言之，没有可信度。

- 例如：最忌讳被观众发现表演痕迹的类型片，可能是喜剧片。很多演员都会告诉你，演喜剧的时候，千万不能一心想着逗人发笑。**如果观众感受到演员是在故意演给他们看, 他们就会出戏.**


|-> 你越没生活体验过的, 越能唬弄你
|动作戏要比文戏简单得多。你拿AK-47扫射过人群吗？你没有, 那我拍成什么都能糊弄你. 但如果我拍的是一对夫妇吵架的戏, 那你是有生活经验的, 所以这场戏逼不逼真，你一看便知。(观众生活中越没体验过的，越好糊弄，比如武侠片, 天马行空的武侠动作设计.  还有机器人, 外星人长什么样子的设计.)
|===

---

====== ▶ 具体方法: 研究人物

#**必须要对角色进行研究，研究一直都是优质表演的重要组成部分。**# 好演员, 在扮演角色之前要做海量的研究工作。他们一拿到剧本，#**要做的第一件事就是分析角色，拆解每个角色的对白和行为，理解角色说的每一句话、做的每一件事（或者不做的事情）背后的含义。**#

(正如郭德纲所说: 说三国, 发生了什么事情不重要, 重要的是分析人物背后的心理和动机, 这些底层原因, 才是导致各种表层事件发生的源泉. )

---

====== ▶ 具体方法: 要表演, 不要模仿

**演员要演出角色的心理状态，而不是单纯的模仿.** 要把自己放进角色里。你不是在演一个混蛋，而是要把你内心的那个混蛋展示出来。

因为 #**"模仿"并不属于"角色刻画"，不会为此揣摩角色的心理活动，也不会为他们塑造一个完整的内心世界。**# 从"角色模仿"到"角色刻画" 之间的距离还相差很远.  距离打造一个活生生的人、一个能透过屏幕与观众达成情感连接的人, 还差得远。(即: 神似>形似)

.标题
====
例如：一个演员要在电影中模仿尼克松, 轻而易举, 但如果只做到这一点, 那他在艺术性上绝不会比 <The Tonight Show 今夜秀> 中 Rich Little 的"尼克松模仿秀"高明到哪里去。
====

要想彻底演活一个角色，意味着你的走路、说话、**思考、生活方式, 都要和角色一致。**

---

====== ▶ 具体方法: 要"真情实感", 不要"情感主义emotionalism"

尽力保持克制，不到万不得已时千万不要哭，不要喊，更不要浮夸。否则，演员呈现的只有情感主义（emotionalism），而没有情感。 +
#**浮夸的说话风格和装模作样的动作，让他看上去更像是个搞笑演员在模仿，而不是在呈现一个真实角色。**#

电影并不需要演员像演话剧那样, 抑扬顿挫地讲话，或者动作举止夸张激烈。要让情绪自然流露。 +
舞台剧式表演, “鬼脸型”表演（mugging）, 他们只是把他们认为角色会做出的举动“演出来”，而不是让角色从他们体内长出来。 (香港电影<东成西就>就是如此浮夸.)

.标题
====
例如：导演不经任何排练，直接将 George Clooney 丢进场景中让他表演，Clooney 总是一脸“茫然不知所措”，这也非常符他饰演的这个角色的心境。
====

不管演员表演是以静制动，还是夸张戏剧化，衡量一个演员表演的好坏，应该看观众是否获得情感共鸣：演员的表演, 是帮助了我们进入银幕中的世界，还是让我们觉得出戏？(#**过程和手段不重要, 结果和效果才最重要.**#) +
问题不在于演员能不能演自己，而在于他的行为是否影响到了角色的塑造。演员用什么表演方法并不重要，重要的是最终效果. #important

---

====== ▶ 具体方法: 互动真实

你可以留心演员在不说话时，脸上是否会失去一些神采；或者当另一位演员在说话时，他能否像注意自己的台词一样, 注意对方的台词。

---

==== 方法: 攻心 : 让观众对主角的命运产生关心

====== 心理学原理:

**只有当你(观众)对这些人(角色)产生了关心, 你才会进一步关心和主角相关的一切.**

所以在电影的开场处, 就要让主角有足够的吸引力或角色深度，**让观众愿意跟随主角到天涯海角 (如同你对情人一样)**（或者至少跟到影片结束）。

即使是塑造令人讨厌的角色，好的编剧也要赋予他值得同情的点。**因为如果没有这些特点，编剧对这些角色, 就不会有兴趣去塑造. (即使是反派, 也要有魅力. 有魅力的反派更能衬托主角的魅力, 人是互相抬高的. 优秀的敌人能衬托出你更优秀.)**

.标题
====
例如：Angelina Jolie 在 <Salt 特工绍特> 中，她扮演了一个俄国间谍。这样的角色一般并不需要太多观众的共情，但**没有共情, 演员就很难与观众形成情感联系**，但 Angelina Jolie 想要搭建这种联系, 所以其实这个角色身上很多极端的地方, 都是她自己塑造的.
====

---

====== ▶ 具体方法: 人的魅力来源于"看不透", 和"难以预测", 这些心理学

角色让人真实可信, 又觉得难以预测 (难以预测才会带来性格魅力).
  神秘感起到了重要的作用：伟大的演员能不断勾起我们的好奇心.

既要"透明"到能让观众瞬间了解角色，又要"内敛"到让观众好奇角色下一步会怎么做。

---

==== 方法 :角色扮演 : 用“局内人”视角, 让观众更有代入感

====== 概念: 视角

电影视角: 我们身处谁的世界？又是通过谁的眼睛看世界？ 影片的视角是在变化，还是始终如一？ +
要清楚电影的视角：是谁在银幕世界中引领观众？我们是透过谁的眼睛和情感, 来看待故事中的矛盾冲突、悲欢离合、失败与成功的？**要确保“从剧本到片场”（再到银幕）全程视角一致。**


可采取的视角包括:
[cols="1a,1a" options="autowidth"]
|===
|Header 1 |Header 2


|某个角色的主观视角， <- “局内人风格”导演风格.
|
.标题
====
例如：《后窗》几乎全程都是通过主角视角来进行叙事。镜头全程陪伴杰弗里斯，我们只能见其所见，闻其所闻. 但在影片的某一个场景中，趁着杰弗里斯入睡，镜头向观众透露了一条关键信息。这条信息对于观众理解整个故事有着重要作用，但是主角自己并不知情。这是一招不着痕迹的作弊手法，目的是让观众对接下来的故事走向更加好奇。
====

.标题
====
例如：Paul Greengrass (<谍影重重>导演) 特别喜欢让摄影机紧跟主角行动，而且频频使用特写镜头. 他们的镜头紧紧跟随影片主角，让观众感觉自己不是一个安静的观察者，而更像是片中的一员。
====

|经典的全知、中立视角
|

|如上帝般, 冷眼旁观的视角 <- “局外人风格”导演风格.
|.标题
====
例如：《拆弹部队》的视角类似于第三方的记者视角，从来没出现全知视角（omniscient eye）——即镜头永远不会拉到一定距离之外，用“上帝视角”来观察银幕上发生的一切.
====
|===

通常来说，优秀的导演手法, 应该介于这两种极端之间 —— **私密但持重；客观但不冷淡；处在一定距离外冷静观察，但仍保持尊重与同情。**

---

====== ▶ 具体方法: 镜头目标, 声音, 都能表达出"以谁为视角?"

摄影机摆在哪里，镜头反映的是谁的视点，观众是通过谁的耳朵听声音，电影配乐是在传达谁的内心情感，都取决于角色和角色视角。

---

====== ▶ 具体方法: 好的艺术设计, 还能进入主角的视角

.标题
====
例如：<Black Swan> 中, 通过对镜子、窗子等带反射面的母题运用，来展现一位芭蕾舞女演员的心灵走向崩溃的过程。
====

---

==== 方法: 故事发生的环境真实

====== ▶ 心理学原理, 目的: 要真实到能够让观众相信, 并彻底沉浸其中.

一部电影可以漂亮过头吗？片中 Stanley Kubrick 对于画面的追求，远超他对故事内涵、情节驱动力和隐喻的追求。这是一种完美的不真实，**更多是为了凸显银幕上的美景，而不是由 Ryan O'Neal 饰演的主角。本末倒置了.**

这个世界好不好看不重要，重要的是它是否真实，是否能够让观众相信, 并彻底沉浸其中。(<天国王朝>中, 那些环境场景, 真的让人如同回到了中世纪的欧洲)

这就是普通的背景, 和优秀的艺术设计, 的区别 -- 前者是演员在静态背景下演戏，后者是在看得见、摸得着的世界中生活。

那些让人看完就忘的电影，里面所有的房子都带着千篇一律的白木桩围栏，所有的角色都穿着毫无特色的Dockers或者J.Jill 。这些片子的艺术指导, 没有为丰富"角色内涵"再做点儿什么，他们只是去商场买了点儿东西回来敷衍了事，除了搭建一个好看的背景供演员表演，他们什么也没做。

---

====== ▶ 心理学原理, 目的: 好的艺术设计, 要能帮助叙事，而不是分散观众的注意力

画面的背景中, 发生了什么？告诉了我们什么？画面的背景, 是在帮助叙事，还是分散了观众的注意力？

这些环境能反映生活在其中的角色的个人特点，就好像我们的房子能反映我们的性格一样。

---

====== ▶ 心理学原理, 目的: 艺术设计, 唤起了你的哪些感觉？它们反映出了怎样的情绪？


最好的艺术设计, 是难以察觉、不着痕迹的，观众可能根本意识不到它的存在。但艺术设计绝对不能完全消失，因为它有着"传递信息"和"表达情感"的作用。会对观众的"心理情绪"产生影响.

艺术设计的最终目的, 不是为了表面上的搭建物理场景，而是为了传递重要的"心理和情感信息"。 +
(后者才是本质目的，如同你建立自己的"设计方法论"时, 对"设计元素"的分解分析一样，看它们会带给人, 怎样不同的情绪体验, 这就是"各种元素"和"风格"所能起到的作用, 它们的价值所在.  #**如果这些东西不能给人带来你想要的情绪体验, 它们就没有存在价值. 正如<大逃杀>中的核心观点 -- 要成为有生存价值的成年人(元素).)**#

.标题
====
例如：为了凸显人物在政府机构面前的渺小无力，艺术指导故意突出建筑物的高大冷酷，给它们涂上了一层法西斯的色彩。
====

.标题
====
例如：Stanley Kubrick 的电影, 一直都是利用夸张设计, 来激起观众强烈情感反应的.  如《The Shining 闪灵》中阴森空荡的远望酒店. 酒店内新旧装饰元素的诡异交融、高得夸张的天花板、俗气的色彩搭配，以及反复出现的迷宫式设计母题 （motif），目的都是为了给观众, 营造出这样一种感觉 -- 好像被什么强大而邪恶的力量, 压得喘不过气来。
====

---

====== ▶ 具体方法: 不同颜色或色调, 会带来何种的象征意义和情感?  会触发观众相应的反应。

这些色彩是在帮助叙事，还是衬托、暗示当下已经很明显的情绪和信息？

.标题
====
例如：<Precious> 讲述的是一个被贫穷与家庭暴力围绕的女孩的成长故事。但导演依然使用了鲜艳的背景色, 目的是想要捕捉她在不屈不挠、努力求生中, 展现出的活力与乐观精神. “我们既要展现痛苦，也要展现美丽。”
====

---

====== 设计部门和美术部门最累

对细节的打磨，导致设计部门和美术部门通常都是最早开工. -- "我们会尽力为后来者设立一个高标杆，这样一来，任何人都没有理由偷懒", "这也是为什么我们把那么多的时间都花在素材积累上".

---



== ---------- ----------

---

== **如何持久地把握住观众的好奇心?**

==== 心理学原理: 一个好剧本，要做到能掐住观众的咽喉，一刻都不松手。

==== ▶ 具体方法: 逐渐将信息释放给观众

每隔一段时间，这个剧本就应该释放足够的信息 -> 让观众对接下来的故事发展保持好奇(吊胃口)，永远不觉得出戏、无聊或者毫无头绪。

.标题
====
例如：《唐人街》中，汤小心翼翼、一点一点地释放关于侦探杰克·盖特斯, 和他调查的洛杉矶富人家庭的信息，使观众全程保持精神集中，直到最终揭开真相。
====

.标题
====
例如：Manchester by the Sea 中，导演像折纸一样架构故事，随着折纸一点一点展开，我们也一步一步了解了钱德勒在几年前经历的惨剧。采用这个结构是因为钱德勒一直在想尽办法封闭这段记忆，埋藏过去的悔恨。换言之, 如果处理得当，影片的结构就是由角色的性格来决定的.
====

---

== ---------- ----------

---

== **如何让故事的推进更自然?**

==== ▶ 具体方法: 故事必须有"#起承转合#". 每个场景, 必有它要达成的目的

如果一部电影的展开, 只是从A点走到B点，再到C点再到D点，就犯了“ 章节化”（episodic）的问题. 就是**场景只是机械地串在一起，起承转合过于生硬**，缺乏连贯性，而不是自成一体、一气呵成。

每一场戏一定都是有它的目的的:  +
1.为了推进故事， +
2.揭露和角色有关的信息， +
3.为后来的剧情发展做铺垫。

**不能“推进剧情”或体现“角色发展”的场景, 都要删掉。**

---

==== ▶ 具体方法: 角色对故事阶段的推进, 背后必有 #动机支持#

演员**要弄清楚这些角色从何而来(想要获得的欲望需求是什么?)，要去向何方(行为动机指向哪里?)，以及在具体的某一刻，他们处在什么位置(每个阶段, 不同阶段的困境)。** (即角色意志的 过去, 现在, 和未来)

差的故事, 没有任何情节驱动力。编剧只是为了给主角找事做, 而给他强加不合情理的难题。#**缺乏"为什么要必须去做它"的动机, 观众就不会理解角色行为, 也就没有了共情.**#

---

==== ▶ 具体方法: 用环境, 来展现"潜台词"

如果离开冗长的对话场景，编剧就不能清晰地展现角色和角色动机，那就是一个坏剧本。

---


== ---------- ----------

---

== **如何塑造真实可信的角色, 和人物心理?**




