
= 评判(v.)电影
:toc:
:toclevels: 4
:sectnums:

---

== 核心底层思考

==== 拍电影, 做影评人, 都锻炼不了大脑成为"谋事者", 只是工具人 -- 琢磨"艺'的(虽然带到人性).

.标题
====
例如：电影节的工作，每天都要看四五部电影, 我得了“电影眼”病——眼睛又疼又累，走在路上不管看什么，都好像是在透过一个矩形银幕看电影。
====

- 这个工作也是把大量时间浪费在看垃圾上. 虚耗光阴. 即使是一直在看电影好片, 也是肤浅的. 视频的信息密度很低. 宁可去看书了.  +
所以影评**这个职业, 不会令你变成"谋事者"的身份. 依然在浪费大脑锻炼. 这个工作的注意力只盯着那狭窄的"如何讲故事"上, 一切手段(视觉语言, 听觉语言, 文字语言, 只为"讲好故事"服务 -- 所以依然只是个工具人的身份.**

- 好电影有很多, 你不需要都去看, 也没必要浪费那么多时间. 你只需要对少数好电影, 做分析和学习即可. **相当于英语中的"精度"做法. 而不要去做"泛读"或只在做"泛读".**

---

==== 我的架构建立方法 : 1.从要解决的"问题"出发, 2.寻找解决方法, 3.及判断该方法的ROI, 及创新程度

以"问题"为出发点, 来建立架构:

[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.我要解决什么问题?
|艺术中就是"心理学问题" -- 想达到的目的: 就是促使观众产生某种情绪.
|2.实现的各种方法, 有哪些?
|- 方法也只是工具, 要分析各自的利弊.
- 它们是否能达到你想实现的 最终效果和目的. 效果度高低如何?
- 这些方法, 是传统的, 还是创新的, 业界前沿的?
- 你为此付出的成本,是否大于收益? ROI如何?
|===

====== 即, 思考任何现象与事情, 要以这三点为框架来做思考:

1.它被人去做, 背后想要得到的"目的"是什么? (即背后动机)

2.能达到该"目的"的方法, 手段, 有哪些? +
你要分解它里面的所有元素, 知道它们的"语言方法"(视觉语言,听觉语言, 文字语言), 对传达"故事"各自起到怎样的作用? 它们对人的生理、心理、情感甚至潜意识, 各自会产生何种效果?
(这和我对"设计"进行分解, 分析各元素会给人带来何种情绪体验, 以形成自己的"方法论", 是异曲同工的.)

3.采用的"该方法", 投资回报率如何? 是亏本的, 还是赚到的? 即, 它真的起到作用了吗? 起到多少作用? 并且ROI如何, 回报与付出, 合算吗? +
以及, "该方法", 是依然属于"传统"的,  还是是"新技术, 新办法, 全新创新"的?


---

== ---------- ----------

---

你作为创作者(导演和编剧本人), 要思考这几个问题:

== 自己的"创作追求"是什么?

==== 电影一定要表达出导演个人化的价值观, 和审美品味

====== 优秀的导演 -> 富有自己的野心和想法
你作为导演, 就要为影片注入个人风格 (xx作品).
**既然由你来导演这部影片, 那一定就是反映的你的想法和价值观, 而不是别人的. 否则还要你来拍干嘛?** 随便找个人去拍就行. 很多自编自导型导演, 他们的作品无疑都能反映导演本人的思想、
品位、观点以及执念。 +
(想想为什么观众喜欢看 Zack Snyder 版的<正义联盟>)

====== 烂导演 -> 只是在交"作业", 而不是在创造"作品"
平庸的作品, 就是给人感觉: 它不是诞生于个人的独特想法，而是诞生在好莱坞流水线模式下，平庸、无趣.

差劲的导演只会这样拍 —— 一个主镜头，一个中景特写，再加上一系列的特写镜头——然后将这些镜头随随便便剪到一块儿，电影就算完成了。(**好的导演会在每部电影中注入自己的独特风格，由此打造的观影体验，远比看着画面简单地在特写镜头、中景镜头和主镜头之间来回切换, 要有趣得多。**)

- 他们要么随便剪辑, 不是在引导观众。(**好的导演会通过各种手段, 不断影响观众的感知与预期 -- 引导我们的眼睛和情绪, 心情.**)
- 要么通过过度剪辑的特写镜头, 对观众进行过多的引导，让我们没有选择的余地。

---

==== 好的电影, 能够提出重要的问题 -> 人生的问题, 社会的问题

**“值得拍”的电影，会反映我们人生的问题(历史、现代生活、人性、希望、绝望等), 这个世界的问题. 传递强烈的情感 -- 让观众陷入难以抉择的难题中，反省自己根深蒂固的某些观念**, 让我们被电影重塑.

.标题
====
例如：表面上, 《不羁夜》（Boogie Nights）是对七十年代洛杉矶色情业工作者的淫猥一瞥，但实际上，它想表达的是个人在"站队文化"中寻找自我，反映人们的价值观与身份, 是如何随着科技的发展而变化，以及电影媒介本身的浪漫与脆弱。
====

.标题
====
例如： 表面上，《正午》是一部小镇警长式西部片，讲述警长努力在镇上寻求帮助却无人响应，最后只能孤身对抗犯罪团伙的故事。但它底层的内核主题, 是在控诉民粹主义盛行下的政治怯懦。
====

---

==== 差的电影主题

====== 廉价心灵鸡汤

即: 只表现最浅薄的"真善美".

====== 灌输说教

即 : 主题过于直白、恨不得打在广告牌上直接告诉你. 这样的影片会让观众感觉在被灌输思想，而不是受到启发或获得娱乐。  (中国春晚的小品) +
一个好的剧本, 要让观众自己去思考，挖掘其中的深意。(展现而不讲述)

---




