= 1680
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast: English Café number 375.
This is English as a Second Language Podcast: English Café episode 375. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode that will help you improve your English even faster. You can also take a look at our ESL Podcast store with additional courses in English, as well as our ESL Podcast blog.
On this Café, we’re going to talk about a famous character in American popular culture, the Lone Ranger. We’re also going to talk about one of the most famous objects in U.S history, the Liberty Bell. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café with a discussion of the Lone Ranger. A “ranger” (ranger) is someone whose job it is to usually protect a certain area. A “park ranger” is a person who works at a national park and his or her job is to educate people about the park, but also to make sure the park is safe, to make sure no one is doing any damage to the park. In the state of Texas, however, which is located in the southwestern – south central part of the United States, the word “ranger” had a different meaning, especially in the 19th century, in the 1800’s. A “ranger” was a police officer and there was a group of police officers called the “Texas Rangers.” And their job was to protect people. They were sort of like a state-wide police force. The Texas Rangers still operate today. There’s also a baseball team called the Texas Rangers, but we’re not talking about baseball; we’re talking about police officers.
Today, we’re going to talk about a fictional character called “The Lone Ranger.” “Lone” (lone) means by himself or herself, someone who is not with anyone else. A “lone ranger” would be a ranger that is working individually, if you will. The Lone Ranger is a fictional character from a story that was actually written originally back in the early 1930s. The story was created for a radio program. In the story, there are actually six men, six Texas Rangers, and these rangers are attacked by criminals. Five of them are killed. One of them is saved by a Native American or American Indian, by the name of Tonto. Tonto recognizes this lone ranger as someone who saved his life before. So, he’s saving his life now – Tonto is saving the ranger’s life in return.
When the man was healthy again, after being hurt, he created a mask out of the clothing of his brother who was killed in the attack. A “mask” (mask) is a piece of cloth that covers most of your face. The Lone Ranger’s mask was a black mask. It had holes in it, of course, so he could see. The mask was used a disguise. A “disguise” (disguise) is something you wear so that people don’t know who you are, so that people don’t recognize you. So, we have this Lone Ranger, the only surviving member of the six who were attacked, plus his friend Tonto. The Lone Ranger and Tonto spend the rest of their lives fighting criminals, fighting the kind of people who killed the other five rangers. Tonto is what we would call the Lone Ranger’s “sidekick.” A “sidekick” (sidekick) – one word – is a person who is always with the main character, the main person, or the person who’s the star. Often on television, there will be someone who does interviews at night, at least, this is a pattern in American television, where late at night at 10:30, 11 o ‘clock, there’ll be these programs that have, typically, comedians – people who are funny – who interview other famous people. And often, the show begins with this comedian and a sidekick – another person – sometimes a comedian as well, who sort of is their helper, who is someone they can talk to. Tonto is the Lone Ranger’s sidekick, not because he’s funny, but because he’s loyal, because he is someone who will help the Lone Ranger, who has already helped the Lone Ranger by saving his life.
The story of the Lone Ranger, created, as I mentioned, for a radio show in 1933, became very popular in other areas as well. There were comic books, there were movies, there were television programs, all made about the Lone Ranger. Most people, including me, are familiar – if they’re familiar at all with the Lone Ranger – with the television show. The actor who played the Lone Ranger was a man by the name of Clayton Moore. In the show, the Lone Ranger was always wearing a black mask and always rode a white horse. And whenever he rode away on his white horse, named “Silver” – the horse’s name was Silver – the Lone Ranger would shout "Hi-yo, Silver! Away!" "Hi-yo" is just something that he said to get the horse to start riding or to go faster. Silver, of course, is the name of the horse and “away,” means let’s get out of here. Let’s leave. "Hi-yo, Silver! Away!" That’s what the Lone Ranger would say.
The theme music for the show, the music that they played at the beginning of the show, was a famous piece of music from an opera by Rossini. It was called the “William Tell” overture. If you play the William Tell overture, most Americans, at least of my age, will associate it with the Lone Ranger, and that’s what they’ll think of when they hear this music.
[music playing]
The Lone Ranger lived by a very strict moral code. A “code” (code) is a set of rules that guide a situation or that control a situation, in this case that guided the Lone Ranger’s life. When I say “strict,” (strict), I mean difficult things that were very difficult to achieve. “Strict” can also be used to describe a parent who doesn’t let their children do anything or who has a lot of rules for children. That could be a “strict” parent – a parent who doesn’t make any exceptions, who always makes the children follow the rules. A “strict moral code” would be a set of rules for yourself that are, perhaps, difficult to follow but that you always try to follow completely. The Lone Ranger in the stories was always prepared for anything and he never killed anyone unless it was absolutely necessary. He also only shot silver bullets out of his gun because he wanted to remind himself that life is precious. When we say something is “precious” (precious), we mean it’s very valuable. Silver, of course, was expensive back then as it is now. In fact, we call metals like gold and silver “precious metals” because they’re so expensive.
Well, the Lone Ranger thought life was precious and so he used his bullets very sparingly; that is, he wouldn’t use them very often, only when it was absolutely necessary. You can still sometimes see episodes of the Lone Ranger on television. You can also find some of the old movies that were based on the story of the Lone Ranger. The Lone Ranger, as you can probably guess, represents this idea of the individual going out and fighting crime, fighting bad things in the world. The good person on the white horse, which symbolizes, of course, purity, innocence – someone who is doing good, who is doing right – all of these symbols are part of the Lone Ranger story and some ways, part of this American notion of the person going out, being individual, being successful and doing good.
This is especially important in American “mythology,” we might call it, of the 19th century, of how the Americans who were moving west were going out into these new areas, these new territories, would face all of these dangers. There would be all of these threats to their safety and you wanted someone who was going to protect, someone who was going to be good and fight against evil. In many ways it’s a story, traditional in most countries, in most cultures, but, of course, it has, in the U.S, context, something associated with the Wild West or the Old West. And the Lone Ranger is certainly part of that.
Another symbol of America, one that most Americans are familiar with is called the “Liberty Bell.” The Liberty Bell is not fictional. It’s not something from a story. It’s a real object. A “bell” (bell) is a hollow metal object that has a small piece of metal inside of it, and when you move it back and forth, it makes a noise, something like this…
[bell ringing]
That’s an example of a large bell. That’s what the Liberty Bell is. It’s a large bell that you can find in the city of Philadelphia, Pennsylvania. Pennsylvania is on the east coast of the United States. Philadelphia was an important city in early American history. It’s where the Constitutional Convention was held, among other important meetings in the early life of the United States. “Liberty” (liberty) is another word for freedom.
The Liberty Bell has a close connection with some of the events of the early part of our history. Many historians believe that this bell was one of the bells that was rung or moved to make a loud ringing sound in 1776 in Philadelphia when the Declaration of Independence was created. The Declaration of Independence was the document that the early American colonists wrote to proclaim, to declare, their independence from Great Britain.
The bell has an interesting history. It was made in 1751 to be placed in the new government building called the States House in Philadelphia. That building was later renamed Independence Hall, of course, in honor of the Declaration of Independence. It was made in London, interestingly enough, and it had cracked when it was being tested. When I say “cracked,” I mean that there was like a line that had formed. The bell had broken, in effect. They had to remake the bell a couple of times in Philadelphia before they could actually use it. The bell weighs about 2,000 lbs. It’s a large bell, about 12 feet or 3.7 meters around the lip of the bill, around the bottom of the bell, what we would call the “circumference” of the bell. It’s about 3 feet or 1 meter from the bottom to the top of the bell.
The bell has an inscription on it. An “inscription” is usually a quote from some famous person that you put on an object. The inscription on the Liberty Bell is from the Bible, from the book of Leviticus. “Proclaim liberty throughout all the land unto all the inhabitants thereof.” That’s a rather old form of English – words that we don’t use very much anymore. “Proclaim” means to announce – “liberty throughout all the land,” meaning everywhere. “Unto,” or to, “all the inhabitants thereof” – “inhabitants” are people who live in a certain area. So, you can tell the bell had, from the beginning, an association with liberty. The bell was rung on July 8th 1776 to celebrate the first public reading of the Declaration of Independence. The Declaration itself was signed on July 4th.
In 1777, when the British troops, the British Army, entered the city of Philadelphia, the bell was hidden in another city, another town. And when it was returned to Philadelphia, to Independence Hall, it cracked again. It broke again. According to tradition, this happened in 1835 during the funeral of the Chief Justice of the United States – the highest judge who sits on our Supreme Court – another famous man by the name of John Marshall.
The name “Liberty Bell” was not used until about 1839. It was rung for the last time in 1846, in honor of George Washington’s birthday. And when it was rung in 1846, the crack became even more serious on the bell and it could no longer be used. For the bicentennial, for the 200th anniversary of the signing of the Declaration of Independence, in 1976, the bell was moved to a separate area, away from Independence Hall, not very far, about a hundred yards, about 90 meters from the building. Then in 2003, it was moved to another building, part of the Independence National Historic Park.
The Liberty Bell is something that, if you go to Philadelphia and you’re an American, you really have to visit. I would recommend you visiting it yourself if you go to Philadelphia. It’s a symbol of American freedom. It’s one of those things that will often appear on posters or other advertisements that are trying to be patriotic, that are trying to show - that are trying to show something traditionally associated with American patriotism.
So, we’ve learned about two famous American symbols today: one, a fictional character named “Lone Ranger,” and the other, a real physical object called “The Liberty Bell.” Now let’s answer some of the questions that you have sent to us.
Our first question comes from Tareq (Tareq) in Syria. The question has to do with the meaning of the word “uprising” versus “revolution” versus “rebellion.” An “uprising” (uprising) is an event when people usually attack, or go against those who are in authority, often, the government. It’s a revolt or a resistance movement, it might also be called. That’s an uprising. We talk about the Warsaw Uprising during World War II, when the Poles tried to defeat the Nazi forces by attacking them. When there are groups within a country that are trying to get rid of the government by violence, that might be called an uprising. Uprising has a generally positive meaning in English. When someone says “uprising” usually the idea is that the people who are fighting against the government are the good guys, the good people.
“Revolution” is any overthrow, any removal of those in power. Any overthrow of the government – the existing government – would be called a “revolution.” Usually, a revolution is done with violence. The American Revolution was a war to get rid of Great Britain. Many countries have experienced revolutions against, often, colonial rule; that is, rule by another country. That’s the pattern, at least here in the Americas.
“Rebellion” (rebellion) is any sort of resistance to authority, not necessarily the national government. It could be against the school principal, it could be against your parents, it could be against anyone who has authority. It might also be resistance against the traditions of a certain culture, or a certain area.
In many situations, these three words, “uprising,” “revolution,” and “rebellion,” have similar meanings but different levels of severity, that is how serious is this challenge. We can talk about teenage rebellion or student rebellion. That’s not very serious. An uprising would be something almost always that is violent. It may or may not be successful, however. An uprising is often the use of violence, but doesn’t always lead to success. A revolution is a larger event where typically, more parts of society are involved and therefore, might be a little more successful.
From the Middle East, we move to Taiwan where Polo (Polo) has a question about sentences that have the word “given” (given) in them. What does it mean to say, for example, “It’s a given,” or “Given that?” Well, given, let’s begin by saying, is the past participle of the verb “to give.” The past participle refers to things that have happened already. “I have given you a book.” It’s something that has already happened.
“Given,” however, can also be used to refer to certain information, a time, a place, a day that has been decided upon in advance. “We will arrive at the given time” - in other words, the time that you and I already decided that I would arrive at. Or “I can meet you any given day to have coffee.” There, “given” isn’t yet decided, but it’s something that you will and I will decide. So, something that’s decided or established can be given.
The expression “It’s a given” means that’s something that we already know, that’s something that we both agree upon or that’s something that we can assume to be true. For example, when you kick a dog – and I don’t recommend kicking a dog, but if you do kick a dog, the dog will probably bite you. It’s a given. In other words, it’s something that we will assume is true because it will almost certainly happen.
There’s also an expression “given that,” which is used in the same way that we might use “since” to begin a clause. “Given that my neighbor is an idiot, I don’t expect him to move his car when he should.” Since my neighbor is an idiot, I don’t expect him to move his car when he should. “Given that” is used to begin the clause, and it means the same as “since.”
Finally, we also have an expression, “your given name.” “Your given name” is your first name. We used to call it your “Christian name,” but that isn’t used very often anymore. Your “given name” is your first name. Your “family name,” of course, is the name of your family. So, my given name is Jeffrey Lawrence and my family name is McQuillan.
Our final question takes us to South America, to Brazil, where Marcese (Marcese) wants to know the difference between “vengeance” and “revenge.” Both words refer to violence against someone, but there is a slight difference. “Vengeance” (vengeance) is punishment that you feel another person deserves because they did something to you. So, it’s hurting, injuring or insulting another person because they have hurt, injured, or insulted you in the past.
“Revenge” (revenge) is a little more serious. Usually it’s punishing someone for something they did wrong, but it may not necessarily have been something they did to you and it may, in fact, be something that is much worse than the original injury. “Revenge” is usually something we talk about when someone has been killed, especially someone you love. Often, groups within a country or even two countries will have this unfortunate attitude toward each other, where one country or one group does something bad, then the other group does something even worse for revenge. “Vengeance” can also be quite violent, but it’s usually a little less serious than revenge. Vengeance is also a little less common of a word. It’s something that you might see associated, for example, with talking about the Bible or some sort of myth.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
ranger – someone whose job is to look after or protect a natural area, and may also help educate people who visit the area
* The park ranger makes sure that people only hike where allowed and stay away from dangerous areas.
mask – a piece of cloth that covers most of one's face, usually to hide one’s identity, but has holes so that one can see and breathe
* On Halloween, children like to wear masks to appear as monsters and ghosts.
lone – only; with no others
* Jerry’s home was the lone house remaining after the terrible fire.
sidekick – a close assistant or associate, often found in one’s company
* Batman’s sidekick is Robin, who helps him catch criminals and fight crime.
strict moral code – a set of rules of right and wrong that one follows closely, which guides one’s behavior
* Our school requires students to follow a strict moral code and anyone who violates that code will be punished or made to leave.
bell – a hollow, metal object that has a smaller piece of metal hanging inside it, allowing it to make a loud, ringing sound
* The church bell rang every hour, sending a beautiful sound through the village.
liberty – freedom; the ability to live without strong powers limiting one’s ability to think and behave as one wishes
* Prisoners in jail only have the liberty to make phone calls once a week.
to ring – for a bell to be moved so that it makes a loud sound; for a machine to make a sound, like a bell
* Would you please answer the door if the doorbell rings?
crack – damage to something in the form of a long line where the two sides separate, leaving a small space in between
* Lorenza dropped the plate and it developed a crack down the middle.
inscribed – cut or printed on a hard surface; carved onto a hard surface
* When Kara resigned as president of the organization, she received a watch from the other members with the dates of her service inscribed on the back.
to proclaim – to officially and publicly announce
* The mayor proclaimed September 24th to be an official city holiday to celebrate podcasting and podcasters.
inhabitant – person who lives in a place; a resident of a specific location
* We received a government notice that all inhabitants of this county need to pay new taxes next year.
uprising – an event when people go against those who have authority or power over them; a revolt; a resistance movement
* If we don’t address the employee’s complaints, we may have a widespread uprising to deal with.
revolution – the action of removing those in power in an existing government by the people being governed, usually with violence
* The revolution removed the dictator from power, but many people died in the process.
rebellion – going against authority, tradition, or control
* Do you think riding motorcycles and getting tattoos are common signs of rebellion among young people?
given – established information, such as a time, place, day, or date that is established in advance; with certain personality traits
* The job applicants are to arrive at the given time and be ready for an interview.
vengeance – the injury or insult of a person by someone who has been harmed by that person in the past; with force or violence; to an extreme
* Both sides wanted vengeance after the war, but tried to put aside those feelings to establish peace.
revenge – the punishing of someone for a wrong that that person did to oneself or to someone else
* Giles played a dirty trick on me last week and it’s now time for revenge.
What Insiders Know
Masked Superheroes
Many “superheroes” (men or women (or creatures) who fight crime, often with supernatural powers) in “comic books” (books with a series of pictures instead of just words) or television shows wish to remain “anonymous” (unknown), and they hide their real identity by wearing a mask. The Lone Ranger, for instance, wears a mask to hide the fact that he is really John Reid, a former Texas Ranger. He, like many other superheroes, would rather be identified by his actions, not by who he is, or was, in real life.
Another popular masked superhero is Spiderman, who not only wears a mask, but a full costume that covers his body. Spiderman was created by Marvel Comic’s Stan Lee, and first appeared in a comic book in the early 1960s. Before he was bitten by a special spider that gave him spider-like powers, such as the ability climb walls, Peter Parker was just a normal high school student. After he was bitten, however, Parker decided to use his powers for catching criminals and keeping his city safe.
Captain America is another superhero very popular in the United States. Although he has been featured in many movies, Captain America’s story began in a comic book published by Marvel Comics in the 1940s. This superhero was once a “fragile” (weak) young boy who was given a shot by a scientist that made him big and strong—the perfect American “soldier” (a person who works in the military). Although he is very strong and extremely fast, Captain America, whose real identity is Steve Rogers), has no “superhuman powers” (powers a normal human doesn’t have). He does, however, have an “indestructible” (not able to break or harm) “shield” (large piece of metal or other strong material held in one hand and in front of one’s body to protect it) that he uses to fight crime.
One “lesser-known” (not as famous) masked hero is The Comet, who is one of the first comic-book superheroes to die while fighting crime. Before his death, however, The Comet was able to “turn” (change) people to dust by just looking at them and fly through the air with the use of gas he had “injected” (placed inside one’s body with a needle) into his blood.