= 1691
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 386.
This is ESL Podcast’s English Café episode 386. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. On it, you can visit our ESL Podcast Store, which has some additional courses in business and daily English. You can also take a look at our ESL Podcast Blog. And why not follow us on Twitter at @eslpod and like us on Facebook at facebook.com/eslpod.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers – and yes, there are other native speakers here in the United States other than me – talking at a normal rate of speech. We’re going to listen to them then explain what they’re talking about.
Today, we’re going to discuss undocumented students, students who are here in the United States illegally, and what happens when they want to go to college. And as always, we’ll answer a few of your questions. Let’s get started.
Our first topic is undocumented students and college tuition. When we say a student is “undocumented,” we mean they don’t have the legal papers to be in this country, the legal permission to be here in the United States. “Tuition” (tuition) refers to how much money a student pays to study, in this case, at a college or a university. The United States has many undocumented students. They come to this country illegally. Many of them were brought by their parents when they were just babies or one or two years old.
They grew up here. They speak English. They don’t know any other culture other than the American culture. Many times, they don’t speak the language of their parents with complete fluency. So, in many ways, they are American but not legally American because they don’t have permission. Their parents did not have permission to bring them to this country.
Many people have proposed or suggested that we change our laws to allow these children who have been here a long time to say in the United States and to study. Recently, one of the states – the state of Maryland – decided to approve a law, to say “yes” to a law, that would allow undocumented students to study in the universities and colleges of that state without having to pay a lot of extra money.
What happens in most American colleges and universities that are owned by the government – that are public – is that if you are from a different state, or from a different country, you have to pay more money to study at that school. It’s what we call “out-of-state tuition.” “Out-of-state” means you are not from that state. If you’re from Minnesota and you travel to California to study and you want to study at a public college, you have to pay more money for tuition than someone who was born and raised in California. Why? Well, because the people of California pay taxes to support their schools and if you’re coming from another state, you haven’t paid taxes, your parents haven’t paid taxes, and therefore you have to pay extra, because the people of California have already paid their part. This is true for most states. In most states, you must be what we would call a “resident” (resident) of that state in order to get what we would call “in-state tuition.” “In-state” means that you’re a resident of that state. If you’re not, then you have to pay “out-of-state tuition.”
The problem with undocumented students is that, because they don’t have legal permission to be here, they have to pay out-of-state tuition, even though they may live in that state and have been raised in that state their entire lives. Maryland, as I mentioned previously, passed a law saying it was okay for those students to pay less tuition. We’ll start by listening to someone who was in favor of this idea, who wanted this law to be passed, to be approved. Her name is Anne Kaier. Let’s listen to Anne and then explain what she says.
[recording]
We’ve made ours even tougher to say to people: this is going to just the most deserving kids who’ve worked hard and played by the rules, and just want an opportunity for an in-state education.
[end of recording]
Anne starts by saying, “We’ve made ours even tougher.” “Ours” here refers to our law. She’s saying that we have made this law “even tougher to say to people.” “Tougher” (tougher) means more difficult, more strict. This law is very strict. It doesn’t allow just anyone to get cheaper tuition, to get in-state tuition. She’s saying, “We made the law more difficult than that, more difficult perhaps than other laws that have been proposed in other places.” She says, “This is going to just the most deserving kids.” The benefits are only for the most “deserving” (deserving) kids or young people – students. Someone who is “deserving” has worked very hard, has done all the right things, and therefore, deserves or should receive some of the benefit or reward.
“This law gives lower tuition only to deserving students,” she says, “who have worked hard and played by the rules.” The expression “to play by the rules” means to follow the rules, to do what you are supposed to do, to follow the law. Of course, other people would disagree with that because they’re here illegally. They haven’t played by the rules, but this is what one of the supporters of the law – one of the people who was in favor of or wanted the law to be approved – says.
She says that the people who will benefit from this law are the people who have worked hard and just want an opportunity for an in-state tuition. “To work hard” is to work a long time, to put all of your energy and focus into something. “In-state education,” we’ve already discussed, means that you pay what anyone else who was a resident of that state would pay. You don’t have to pay out-of state tuition, which is more expensive. Let’s listen to Anne one more time.
[recording]
We’ve made ours even tougher to say to people: this is going to just the most deserving kids who’ve worked hard and played by the rules, and just want an opportunity for an in-state education.
[end of recording]
Now we’re going to hear from someone who was not in favor of this law, who did not approve of the law. Her name is Kristen Williamson and she’s from an organization that typically opposes or is against laws that would help illegal immigrants. It’s called the Federation for American Immigration Reform, which if you take the first letter of each word, spells out FAIR (fair). Let’s listen to Kristen say why she thinks this is a bad law.
[recording]
It rewards law-breaking. It invites future law-breaking and is fundamentally unfair to those who have played by the rules.
[end of recording]
Kristen, who speaks very fas,t as you noticed, starts by saying “It,” meaning this law, “rewards law-breaking.” “To reward” (reward) means to give benefits to. It’s a positive thing. This law gives benefits to people who have broken the law. “It rewards law-breaking.” The expression “to break (break) the law,” means to do something illegal. If you are only supposed to drive your car 55 miles per hour, and you drive 75 miles an hour, you are breaking the law. You are doing something that is illegal – although very common here in California.
Miss Williamson believes that the law rewards law-breaking. It says to people who have done something illegal, “Good job! We’re going to give you something for breaking the law.” That’s her view. Even worse, she says, “It invites future law-breaking.” “To invite” here doesn’t mean to invite someone to a party, to ask someone to come to a party but rather, to encourage. It will make more people want to break the law. The reason being, she’s saying, is that when other people realize that you can go to college in Maryland even if you are an illegal student or an illegal immigrant, more people will decide that it’s okay to do that and will move to Maryland. Maryland, I should mention, is on the East Coast of the United States. It’s right next to Washington, D.C., our capital.
Williamson says that this law is “fundamentally unfair to those who have played by the rules.” “Fundamentally” means here very seriously, at a very basic, important level. “To be unfair” means not to be fair. “To be fair” means to be just, to treat people equally. A teacher has to treat all of her students fairly. She can’t say “I like this student,” and then “I don’t like that student so, I’ going to be nice to this student and not nice to that student.” Of course, teachers are human and they do exactly that many times, but we hope that they would be fair.
Ms. Williamson believes this law is fundamentally unfair to people who have “played by the rules.” Notice she uses the same expression that the person who was in favor of the law used, “to play by the rules.” Williamson is saying here that these people didn’t play by the rules because they didn’t come to the United States in a legal manner – in a legal way. Let’s listen to hear one more time.
[recording]
It rewards law-breaking. It invites future law-breaking and is fundamentally unfair to those who have played by the rules.
[end of recording]
Kristen is so angry she has even more to say about this law. Let’s listen one more time as she explains more why she doesn’t want this law in Maryland.
[recording]
Having an incentive like in-state tuition will only invite more illegal immigration into the state. And that means that Marylanders aren’t necessarily going to get a return on their investment, because these illegal aliens aren’t eligible to work in the country permanently.
[end of recording]
Ms. Williamson begins with the argument we mentioned earlier, about what this law will do in terms of having more illegal immigrants come to the state of Maryland. She says, “Having an incentive like in-state tuition will only invite more illegal immigration into the state.” An “incentive” (incentive) is something that encourages people to do something. It’s like a reward. Some parents try to give their children incentives to get good grades in school.
This, by the way, is according to most research, not a very good idea. Giving incentives for learning things often makes people not want to learn them because, after all, if someone is paying me to do it, it must not be something I would do without being paid. Other people disagree with that argument, but that’s one reason perhaps not to give incentives to someone.
Here we’re talking about giving incentives like in-state tuition to illegal immigrants. These incentives, according to Kristen, will encourage more people to come into Maryland. “And that means,” she says “that Marylanders” – people who live in Maryland – “aren’t necessarily going to get a return on their investment.” The expression “a return on your investment” means you get something for the money that you put into, say, a company or some other way of making money. If someone is going to start a new business and asked me to invest $10,000 – to give them $10,000 – I would say, “No.” I don’t give anybody $10,000, but let’s just use this as an example. If I did give them $10,000, and then at the end of the first year they gave me $15,000 back, that would be a very good “return on my investment.” I got all of my money back plus 50% more. That’s a pretty good return. The “return” is what you get back from the investment.
What Ms. Williamson is saying here is that the people of Maryland who pay their taxes aren’t going to get a good return on their investment – the money they pay in taxes to support the public schools – because these illegal aliens aren’t “eligible” to work in the country “permanently.”
There’s a couple of words there we need to explain. First, “aliens” (aliens) refers, in general, to people from other countries, from other places. In science fiction, we talk about aliens from other planets – from Mars, from Jupiter, from weird places like San Francisco, where no one really knows if there’s anyone human in that city. I’m just kidding. You see, Los Angeles and San Francisco – one is in the southern part of California, one is in the northern part of California, so they kind of don’t like each other very much. And since I’m in Los Angeles, I don’t like people from San Francisco.
But we’re not talking about aliens from the planet of San Francisco. We’re talking about people from other countries. “Illegal aliens” are people from other countries who are here in the U.S. without permission. Because they are “illegal,” they aren’t eligible to work. “To be eligible” (eligible) means that they have permission. They meet all of the requirements to work in this country. “Permanently” means for as long as they want. It’s the opposite of temporarily. If you’re only here temporarily, you’re only here for a short time. If you’re here permanently, you’re here for, basically, the rest of your life or for a very long period of time.
So, Ms. Williamson is saying here that even when we give these undocumented students the ability to attend our public colleges, paying only in-state tuition, we won’t be able to get the benefit of that investment because when they graduate, they still won’t be able to work in the state, and therefore they won’t be able to pay taxes like everyone else. Let’s listen to Ms. Williamson one more time.
[recording]
Having an incentive like in-state tuition will only invite more illegal immigration into the state. And that means that Marylanders aren’t necessarily going to get a return on their investment, because these illegal aliens aren’t eligible to work in the country permanently.
[end of recording]
The topic of illegal immigration or undocumented workers and undocumented students is a very controversial one in the United States. Some people get very angry about this issue. Many people think there are good arguments on both sides; that is, that both those who are for and against laws such as this have some good reasons for why they are for or against it.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Mohammed (Mohammed) in Sudan, in Africa. Mohammed wants to know the meaning of the expression “to stop thinking negatively.” “To stop” means to end, not to do something anymore. “To stop thinking negatively” means not to have bad opinions about things, not to believe that everything is going to get worse – that the world is a terrible place, that bad things will happen soon. Someone who thinks negatively never sees the positive or good side if things. It’s a person who believes things are always going to get worse – that bad things will happen. That is the meaning of the expression “to think negatively.”
So, to tell someone to “stop thinking negatively” would mean to think more positively. We would probably call someone who always is thinking negatively a “pessimist” (pessimist). A “pessimist” is someone who always sees the bad in a situation. We have an expression, “They always think the glass is half empty.” A glass of water, for example, that has 50% of it filled could be considered “half empty.” It could also be considered “half full.” If you’re a pessimist, you think the glass of water is half empty. If you’re an “optimist,” (optimist) you think the glass is half full. An “optimist” sees the positive in the world, sees the good things or expects good things to happen.
There was a movement, at least in the United States in the 20th century related to “positive thinking,” to getting people to think more positively about the world. Some people thought this was good for people psychologically, mentally. And so there was sort of a movement, a group of people – writers and others – who promoted or encouraged people to think positively. Sometimes it was referred to as having a “positive mental attitude,” to think positively. There’s an expression also we use – “Think good thoughts.” When you tell someone to “think good thoughts,” we mean to think positively, especially before some big event – something that’s going to happen soon in the future and you want it to go well. You’ll say to someone, “Think good thoughts!”
Ricardo (Ricardo) from Brazil wants to know the uses of the word “very” in expressions such as “In this very sea.” “Very” is a word with a lot of different possible uses. It’s hard to summarize them in just a couple of minutes.
One use of “very” is “extremely”: “I was very hungry.” I was extremely hungry. I was really, really, really hungry. “Very” can also be used to show emphasis or to show what we would call “identity” – to identify, to name a certain place. That’s the meaning that Ricardo is referring to in the expression, “In this very area,” or “On this very “sea” (sea), like an ocean. When we use “very” in that circumstance, in that situation, we are emphasizing,not the sea over there but this sea. It’s a way of showing emphasis.
“Very” can also mean real or actual. “We caught him in the very act of stealing.” That means that we found him – we discovered him – as he was stealing at that very moment, that actual moment, we might say. Some of these uses of “very” are very poetic. That is, you don’t hear them in conversation very often. They’re used by writers to provide some sophistication perhaps, as they express their thoughts. We do however, use expressions such as “In the very beginning” or “At the very end” to emphasize that it was immediately after something started. It was at the very beginning.
Finally, Fabio (Fabio) also from Brazil wants to know the meaning of the expression “smoking hot.” Something that is “hot” (hot) is something that has a very high temperature, often associated with fire. “Smoking” is from the word “smoke” which is what happens when you burn something. When you burn something, it produces a white, grey, or black, typically, smoke. If you burn a piece of paper, you will see the fire but you will also see smoke coming up from the paper.
The expression “smoking hot,” however, is used most often to refer to a person, usually a woman, who is very attractive, who is very sexy, who is very physically attractive. It’s an expression that we would use only informally, only with friends, and you wouldn’t use it in a business setting. Of course, you shouldn’t be talking about how physically attractive the other people in your business setting are to begin with.
It’s definitely a very positive thing. It’s something that a man would most often say about a woman to one of his other male friends. “She was smoking hot.” You could also just say, “She was hot,” which means she is very attractive, from a sexual point of view.
When someone uses the word “smokin’” especially when it’s spelled (smokin) – without the (g) – that can mean a couple of different things. If someone says, “What are you smokin’?” they mean, “Are you crazy?” The idea is that you are smoking some sort of illegal drug like marijuana. “What were you smokin’?” “What was he smokin’?” You’re saying that these people are crazy because in order to do what they did, they must have been on some sort of illegal drug. “Smoking hot,” however, refers to, as I mentioned previously, usually a woman who a man considers very attractive. It’s an informal expression, not something you would probably use with anyone in a formal situation.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. We won’t have time to answer all of your questions but we’ll do our best to answer them right here on this very podcast.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on the English Café.
English as a Second Language Podcast’s English Café is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
tough – difficult; strict; not easy or simple
* That was such a tough exam! I knew the answer to only two of the questions.
deserving – having worked very hard and done all the right things, so one should some benefit or reward
* Winston doesn’t think anyone is deserving of marrying his daughter.
to play by the rules – to follow the rules; to do what one is supposed to do
* Sometimes it seems like the people who play by the rules never become as successful or wealthy as the people who cheat a little bit.
in-state – within a state, usually used to describe going to a college or university in the state where one is a resident
* Their son is only 13 years old, but they’re considering moving to California soon so that he’ll be eligible for in-state tuition at the University of California in Berkeley when he’s ready to go to college.
law-breaking – the act of breaking the law or not following the law, doing something that is illegal because the law does not allow it
* Many job applications ask if you have ever been arrested for law-breaking.
fundamentally – at a very basic level
* There’s something fundamentally wrong with our healthcare system when millions of people do not have any insurance.
unfair – unjust; not treating all people equally or in the same way
* The boss yelled at Helen for arriving 10 minutes late, but he didn’t say a word when Piotr took a two-hour lunch. That’s unfair!
incentive – something that encourages people to do something, like a reward
* As an incentive, the company is going to give a free Caribbean vacation to the best-performing salesperson this year.
tuition – the amount of money paid to a college or university for one’s education
* Mariah’s parents are paying her tuition, but she has to pay for housing, meals, and books.
to get a return on (one’s) investment – for something to be profitable, so that one receives more than one pays
* If you want people to invest in your company, you’ll have to persuade them that they’ll get a good return on their investment.
illegal alien – a person who lives in a country without legal permission; a person who does not have the required immigration paperwork
* How many illegal aliens does the U.S. government send home every year?
eligible – meeting the requirements to have something or to participate in some program
* A family of three that makes less than $40,000 per year is eligible for government help to buy food.
permanently – for a long period of time, without an expectation of change in the fduture; not temporarily
* A tattoo will be on your body permanently. Are you sure you want one?
to think negatively – to be pessimistic; to always believe that bad things will happen
* I’m not thinking negatively, I’m just being realistic. If our business doesn’t become profitable soon, we’ll have to shut it down.
smoking hot – with a very high temperature associated with fire and smoke; a phrase used to describe a very sexy and attractive person, especially a woman
* Petunia lost 20 pounds, dyed her hair, stopped wearing glasses, and whitened her teeth, and now she’s smoking hot!
What Insiders Know
The Court Case United States v. Wong King Ark
In 1871, a Chinese woman gave birth to a baby boy in San Francisco, California. The Chinese parents named the boy Wong King Ark. Years later, upon return from a trip “abroad” (to another country), Wong Kim art was “denied re-entry” (not given permission to enter the country) to the United States. At that time, a law called the Chinese Exclusion Act limited immigration from China and did not allow immigrants from China to participate in the “naturalization process” (the process by which people living in the United States can become citizens).
Wong Kim Ark “challenged” (argued against something in court) the government’s decision, arguing that he had been born in the United States, so he should be a U.S. citizen. That “court case” (an argument heard and decided upon in a court of law) became known as United States v. Wong King Ark.
In 1898, the “Supreme Court” (the highest and most powerful court in the United States), “ruled in Wong Kim Ark’s favor” (decided that he was correct). The Court “clarified” (made clear) that everyone who is born in the United States is a U.S. citizen, “regardless of” (without giving importance to) where their parents are from. The Court stated that Wong Kim Ark had become a U.S. citizen “by virtue of” (as a result of) his birth on U.S. “soil” (land), and nothing that had happened since then, including the “enactment” (creation of a new law) of the Chinese Exclusion Act, could change that.
In recent years, some people have begun to argue that U.S. citizenship should not be given to the children of illegal aliens. They believe that people who do not have permission to live in this country should not be able to “claim” (get or have) U.S. citizenship for their children.