= 1677
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 372.
This is English as a Second Language Podcast’s English Café episode 372. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Take a look at our ESL Podcast Store and our ESL Podcast blog. Why not like us on Facebook at facebook.com/eslpod or follow us on Twitter at @eslpod?
On this Café, we’re going to continue or series on famous Americans, focusing on a very famous woman by the name of Amy Semple McPherson. We’re also going to continue talking about traditional American songs. We’re going to talk about a folk song called “Turkey in the Straw.” And as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on famous Americans. Today, we’re going to talk about a woman who is famous (for some people). She was much more famous a hundred years ago. Her name is Amy Semple McPherson. McPherson was born as Amy Elizabeth Kennedy, in Ontario, Canada, in 1890. But she spent most of her life right here in Los Angeles, California. McPherson married twice. Her first husband was named Mr. Semple. He died and then she married her second husband, a Mr. McPherson. She took both of their last names. She actually kept the name of her first husband. I’m not sure what her second husband thought of that idea. So, her name ended up being Amy Semple McPherson. She actually married a third time to a man by the name of Hutton, but she typically is not remembered by that name. Why was Amy Semple McPherson famous? Well, she was probably one of the most popular “evangelists” of her time.
An “evangelist” (evangelist) is a person who shares information with other people about a certain idea or a certain religion. In this case, the religion is Christianity and McPherson was an evangelist for Christianity in the United States. She tried to get people to become Christians. She tried to convert them. “To convert” (convert) is to change someone’s ideas about something, usually their religious ideas. McPherson tried to go out, talk to people, and get them to become Christians, or become more Christian. McPherson herself grew up in a religious family and didn’t like the fact that the public schools in the United States were teaching ideas about evolution – Darwin’s ideas about how humans came to be humans. Even as a high school student, she disagreed and talked against the idea of evolution. Remember, in the late 19th century, when she was growing up, evolution was still a somewhat of a new idea.
McPherson began to travel across Canada, the country where she was born, as well as the United States and basically worked as a preacher. A “preacher” (preacher) is someone who goes out and gives religious talks, often to large groups of people, usually at some sort of church but sometimes, just in some area where you can put a lot of people. During this time, in the late 19th, early 20th centuries, there was a very popular kind of religious preaching called “tent revivals.” “Tent” (tent) is a large temporary structure that you put up for many people to come into and sit down. You can also have a small tent where you sleep in at night if you go out into the woods or somewhere where there isn’t a hotel. I never do that but I hear people do that.
A “revival” (revival), in general, just means when something is dead and it comes back to life, or it’s almost dead and it comes back to life. That is probably more common. Once it dies, it usually doesn’t come back to life, unless you are the founder of Christianity. A “revival,” however, in this case, is a large religious Christian meeting, designed to “revive” or renew people’s interest in religion and their love for, in this case, the founder of the Christian religion, Jesus Christ. A “tent revival” is a revival, a big meeting, that takes place usually in a temporary location, a temporary tent that people come to, and they listen to the preacher and then they go home and they take the tent down.
Amy’s revival – Amy McPherson’s revivals had hundreds of people, often thousands of people in them. She had one in San Diego – south of Los Angeles – that had more than 30,000 people. Now, they didn’t probably all go into one tent but you get the idea. These were large religious meetings where McPherson and others would preach, would talk about Christianity, and get people excited about it. There were many preachers who led revivals in the late 19th, early 20th centuries, but Amy was unusual because she was a woman.
Most of the preachers, even today, are men. But to be a female preacher back in the early 20th century was quite unusual. Amy was also unusual because she was very smart about using what was then “modern” media, in this case, the radio. She would go on the radio and have radio programs. She used the radio to spread her message; that is, to get other people to hear what she was saying. It’s interesting if we look at radio and television in the United States during the early days of each medium of radio and then of television. Some of the most popular programs, originally, were religious programs - McPherson, for radio. For television, one of the most popular programs in the 1950’s in American television was a religious program by a Catholic bishop, a Catholic religious leader by the name of Fulton Sheen.
Anyway, Amy McPherson used the radio to make her message more popular. She also used films and magazines, other sort of techniques that were common here in Hollywood, here in Los Angeles, and that’s where she eventually moved. She came to Los Angeles and Los Angeles was the center of her operations. And that was very smart because Los Angeles was the center of the new entertainment industry, the movie and television businesses that were starting in the early 20th century.
McPherson came from a Pentecostal tradition within Christianity. “Pentecostals” are Protestant Christians who believed that, typically, the Bible should be interpreted literally and that it should involve a personal relationship with Jesus Christ. Now, Pentecostalism is much more complicated than that. But one of the things that separated Pentecostals from other Christian groups was they believed in a special religious experience called “speaking in tongues.” “Speaking in tongues” (tongues) is a religious experience in which, according to Pentecostals, the spirit of God, the Holy Spirit, speaks through you, and what you actually say isn’t necessarily human language. The sounds coming out of your mouth are not things you can typically understand but they are a manifestation, they are an indication of the fact that God is speaking through you. Pentecostals also had a strong belief – have a strong belief – in divine healing, the ability to make sick people or injured well again, often by putting their hands on them and saying a prayer. Amy McPherson often spoke in tongues but she’s better known for these healings, taking sick people and making them better, at least that’s what was reported by her followers and believers.
McPherson focused a lot on the role of women in Christianity, but her messages were, compared to a lot of feminists, a lot of women who were trying to change the view of women in society, considered very conservative. She wasn’t trying to change the role of women, the function of women in society in the same way that other women leaders were trying to do at this time.
McPherson managed to get a lot of money. She managed to, we would say, “raise” (raise) a lot of money, get a lot of money from people who gave her money to help her with her ministries; that is, with her religious work. She built a large church here in Los Angeles called “Angelus” (angelus). The Angelus Temple, it was called, was built right here in Los Angeles. It was a huge area, a huge building where more than 5,000 people could go to listen to McPherson. McPherson had religious services. She had meetings up to three times a day. The church later became known as the International Church of the Foursquare Gospel. “Foursquare” because it had four basic beliefs: that Jesus Christ “saves” – that is, that he can save you from your sins; that people are baptized with the Holy Spirit; that Jesus Christ heals people, makes sick people better; and that Christ, the founder of the Christian religion, will return again to Earth some day.
McPherson died in 1944, but the Foursquare Gospel Church continued after her death, led by her son Rolf. Today, the church is still around. In fact, the church that Amy built is still here in Los Angeles, located near an area called “Echo Park.” It’s not as popular as it used to be, and the church is not quite as big as it used to be. Now, I think, it only has room for about 3,000 people, not 5,000 people, but you can still go and see the church. In fact, I used to live only five or ten minutes from this church. I used to live in this area, this neighborhood called “Echo Park” here in L.A many years ago. The Church now has about 9 million members, which is still a pretty large group of people.
After McPherson died, many other preachers and evangelists tried to follow in her footsteps. The phrase “to follow in someone’s footsteps” (footsteps) means to do the same thing that someone else has done before you or to copy someone else. Many television evangelists nowadays, use modern media, not just radio and film, but television and the Internet, in order to build their churches with large followings; that is, with large groups of people who have the same beliefs. If you come to Los Angeles, you can go and see at least the outside of this famous church, and now you understand a little bit about its background.
Our next topic is a continuation of our series on famous American songs. Today, I’m going to talk about a traditional song called “Turkey in the Straw.” The music or melody for this song are ones that most Americans would instantly recognize. They don’t necessarily know the words to the song. I certainly didn’t know the exact words to this song before I started researching this Café.
The song “Turkey in the Straw” became popular in the early 19th century, in the 1820’s and 30’s. But nobody knows for sure who wrote it. That’s not unusual for these traditional songs. They often are written and changed over time and no one knows quite who started the song. The song was originally performed in “blackface.” “Blackface” (blackface) – one word – means that white performers would paint their faces black and pretend to be black, to be African American. This was not an uncommon form of entertainment for white people in the 19th century, here in the United States. Basically, they were making fun of black people, of course.
There are many other versions of this song, and the version that I’m going to sing now is not the only one that you can find or you might hear. Before I talk about the song, let me explain that a “turkey,” (turkey), if you don’t know, is a very large bird that Americans kill and eat every year for Thanksgiving. Turkeys make a sound which in English is “gobble” – “gobble, gobble, gobble.” As I say, we normally eat turkey, traditionally, on Thanksgiving. “Straw” (straw) and “hay” (hay), which is a word that appears in the song, are similar. They’re both basically dry stems of grass, dry pieces of grass that you might feed to an animal such as a cow. It’s something you would see on a farm, for sure.
Let me sing now one of the versions of “Turkey in the Straw” that are popular, and then we’ll talk a little bit about what it means.
Turkey in the straw, turkey in the hay,
Turkey in the straw, what do you say?
Funniest thing I ever saw,
It's a little tune called Turkey in the Straw.
Not the world’s greatest song, I admit. “Turkey in the Straw” doesn’t really mean anything. It just refers to a turkey standing in some straw. The lyrics say “Turkey in the straw, turkey in the hay,” and remember “hay” is the same as “straw.”” “Turkey in the straw, what do you say? Funniest thing I ever saw.” It’s the funniest thing I have ever seen. “It’s a little tune” – a little song – “called Turkey in the Straw.”
This main repeating part of the song called the “chorus” is mostly nonsensical. That is, it doesn’t really make any sense or have any meaning. The interesting part of the song is not so much the chorus, the repeating part of the song, but the verses, what you sing in between the repeating part, the repeating chorus. For example, one of the verses talks about having a girl who has one leg made of wood and how she isn’t very useful because she doesn’t have two regular legs. Well, that sounds kind of mean, kind of cruel, I guess, but that’s the sort of humor that might have been expressed in the verses of a song like “Turkey in the Straw.”
I mentioned earlier, that most Americans, even though they don’t know the lyrics or words to this song, know the music or the melody. The reason is that there are, in many American cities, what are called “ice cream trucks.” And “ice cream trucks” drive around very slowly through areas where there are a lot of houses and apartments and they play this song to let people know that the truck is there and if they want to come down and buy some ice cream, they can go down and buy a little bit of ice cream from this truck. Of course, children are the ones who are listening for the ice cream truck and are the ones that want to go and buy some ice cream So many ice cream trucks use this song, use this melody. And when children hear the song, they know that the ice cream truck is coming. So, Americans, especially American children, know this song, not because of the words but because of the music. I actually found a recording of an ice cream truck – a real ice cream truck – on the Internet, for free, a non-copyrighted version, I believe. Here’s what the typical American child knows about “Turkey in the Straw.” Here’s the version that they’ve heard many times. Notice this is not the same music for the chorus. This is the music for the verse. And this music is the one that is most popular.
[recording]
Hey, let’s go get some ice cream!
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Eric (Eric) in Germany. Eric wants to know the difference between, in meaning, for three words, “marriage,” “wedding,” and “wedlock.” “Marriage” (marriage) is the legal or religious state or situation, condition, where two people promise to live with each other as romantic partners, though that’s not required, and they, typically, are the foundation of the family. The family unit typically, traditionally, I should say, consisted of a married couple, a man and a woman who would have children. Marriage is a legal institution, in most countries. In other words, the government decides if you are married or not. And if you are, you get certain legal privileges, certain legal rights, that are not available to people who are not married. Marriage for many people is also a religious situation; that is, they are married in the particular religious institution that they belong to, typically, a church. That’s also a marriage.
When I say a “church,” I don’t mean the physical building of a church. I mean a group of people who have similar religious beliefs. In the United States, marriage can be both what we call “civil” (civil), which is the government, officially-approved status of marriage, and a religious wedding, where a religious organization decides that you are married or not.
A “wedding” (wedding) is the event. It’s the ceremony where you actually get married. So, you only have one wedding, typically. Well, if you end your marriage, if you get divorced, you can have another wedding, and another wedding, and another wedding, and another wedding, but when we’re talking about a single marriage, there is one wedding. It happens on one day, usually takes between 30 minutes and an hour, and it’s an official ceremony. In the United States, weddings can be performed by religious leaders, religious ministers, but also by certain government officials.
“Wedlock” (wedlock) is similar to marriage. Really it’s the same thing. Marriage and wedlock mean you are married. However, the word “wedlock” is not that common anymore. We don’t use it as much anymore. Most people don’t talk about wedlock unless it’s in an expression (which is also not very common anymore), “The child was born out of wedlock.” “To be born out of wedlock” means the child was born to a mother who is not married. Since that’s such a common occurrence in the United States, perhaps that’s one reason why we don’t use that expression anymore. So, that’s “marriage,” “wedlock,” and “wedding.”
Parviz (Parviz) in Iran wants to know the meaning of a very common word, “otherwise” (otherwise). “Otherwise” has a couple of meanings but they’re closely related. As an adverb, “otherwise,” can mean “unless things change.” It could also be, “If you don’t,” you might think of it. For example, “Wash the dog. Otherwise, he will get dirt all over the house.” “Otherwise” means if you don’t, or unless that happens, then something else will happen. “Study when you are in school. Otherwise, you will not get a good job after you graduate, after you finish.” You may end up being a podcaster. No parent wants their child to be a podcaster. So, kids, study in school. Otherwise, you’ll be like me.
“Otherwise” can also mean differently, in another way. “I can’t believe otherwise.” That means I can’t believe differently. I can’t believe something else. “John is a good person. How can you think otherwise?” How can you think differently than that?
Finally, “otherwise” can also be used as an adjective, but it is much less common to see it in this form as an adjective. In a sentence such as “I had hoped that the situation would be otherwise,” here, “otherwise” means different. So, it’s similar to the second definition I gave you when it’s used as an adverb. But it’s technically an adjective in that sentence or “If it were otherwise, we would not be here today.” If it were different, if the situation were different – that’s the idea.
Finally, Jean (Jean) in Brazil wants to know about pronunciation, especially when we have contractions. A “contraction” (contraction) is when you take two words and you combine them and you make them shorter. So, instead of saying “I will,” you would say, “I’ll,” or “we could have,” you would say, “we could’ve.” “Could’ve” is a contraction of could and have. This question actually, is about a line, a sentence from a song by a famous singer, at least, famous in 2012, you probably have heard of her, her name is Adele. The line in her song is “We could’ve had it all.” Here, “could’ve” means “we could have.” It’s a very common contraction.
In fact, it’s so common that some people don’t even realize it is a contraction. They spell it “could of” (of). But it’s not “could of.” It’s “could’ve.” And it’s spelled (could’ve) – all is basically one word. We have lots of different contractions in English and it is confusing because when they’re pronounced quickly, it’s sometimes difficult to understand them. For example, we can use the contraction “I’m” for “I am,” “we’re” for “we are.” That’s one that is particularly confusing because there’s also a verb “were” that’s pronounced the same (were) – without the apostrophe.
Other popular contractions, and there are many, would be something like “he’s” or “she’s” for “he is,” and “she is,” or “he’d” or “she’d” for “he had” or “she had.” We also have things like “can’t” for “cannot,” “won’t” for “will not,” “let’s” for “let us.” That last example is a bit of an exception. Most contractions are nouns plus verbs but “let us” is a verb and then a noun. Informal speech contains a lot of contractions and a lot of words that are pronounced very quickly. We try to slow things down a little here on ESL Podcast so that you can understand a little better about what is actually being said.
If you have a question about English, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
evangelist – a person who shares information about Christianity and the story of Jesus Christ because he or she wants to get other people to become Christians
* Kalil is an evangelist who goes from house to house to talk about his religion and to try to get others to join his church.
to convert – to change one’s religious or other beliefs; to become a member of a different religion
* Would you convert to another religion to marry someone of that religion?
tent revival – a large, religious Christian meeting held in a temporary shelter made of cloth and held up by posts, designed to confirm or renew people's interest in a religion
* Once a month, Sarah and her family go to a tent revival where they worship God and hear stories of how God has helped people like her.
Pentecostal – protestant Christians who believe that the Bible should be interpreted literally and who want to have a personal relationship with Jesus Christ
* Julie’s co-workers are all Pentecostals and they urge her to go to church with them.
to speak in tongues – when someone is overcome or overpowered by the power of God and begins making sounds that appear to be a language that is unknown to the speaker or anyone else
* During the church service, a woman began speaking in tongues and appeared not to know where she was.
divine healing – the ability to make sick or injured people well again, usually by putting one’s hands on them while saying a prayer
* Mindy’s parents tried divine healing for her illness, but when it didn’t work, took her to a doctor.
to follow in (someone’s) footsteps – to do what someone else has done; to copy someone else
* Bogdan’s father wants him to follow in his footsteps and become a lawyer, but Bogdan prefers a career in teaching.
following – a large group of people who share the beliefs of a leader; admirers; supporters
* The rapper MCQuillan has a large following among men ages 18 to 24.
blackface – musical performances by white singers who painted their faces black and pretended to be black, but in a way that would be considered very rude and unacceptable in modern times
* Don’t even think of doing a performance in blackface! That would be offensive!
turkey – a very large bird raise on farms for food, most often associated with Thanksgiving
* Paolo has a farm where he raises turkeys and chickens.
nonsensical – something that does not make sense; without meaning
* Calm down and speak more slowly! I can’t understand you if you keep speaking in this nonsensical way.
tune – a piece of music; the main notes of a pieces of music
* I can’t get this tune out of my head!
marriage – a situation where two romantic partners have made a legal and/or religious commitment to each other
* It’s always sad when a marriage ends, but it is especially sad when there are children involved.
wedding – an event or ceremony where two people celebrate the beginning of their marriage
* Carlos and Kelly’s wedding took place on the beach in front of 50 people.
wedlock – the state of being married
* Does it matter to you if your baby is born out of wedlock?
otherwise – unless things change; if the circumstance doesn’t change; in a different way or state; if things were different
* If it rains, we’ll have the party inside. Otherwise, we’ll have it in the backyard.
What Insiders Know
The Growth of Imitation Meat
If there is one thing that Americans love, it is meat. Whether it is chicken, “beef” (meat that comes from cows), or “pork” (meat from pigs), Americans enjoy meat so much that even those who cannot or will not eat real meat are always looking for a “substitute” (something to take its place) for it.
In the past few decades, being a “vegetarian” (person who does not eat meat) or a “vegan” (a person who will not eat anything that has come from any animal, including milk and eggs) has become very popular in general. Vegetarians and vegans will not eat meat, but that does not keep them from wanting the “flavor” (taste) of meat. This has caused a large growth in the “imitation meat industry,” or the businesses that create food items that look and taste like meat, but are actually made out of something else.
Most imitation meat is made from rice or “soy,” a food that comes from a bean, and is usually used to make “tofu” (a food made with soy and milk to form soft, white blocks). Some popular imitation meat products are “Tofurkey” (a tofu-based replacement for turkey), the “veggie burger” (a substitute for a meat patty, made instead with vegetables like corn and usually eaten on a “bun,” bread sliced in two), and “nut roast” (a dish made of nuts, grains, and tofu that is made to look and taste like roasted meat).
Americans buy millions of dollars worth of imitation meat each year, and its popularity continues to grow. Vegetarians and vegans buy imitation meat, but it is also bought and eaten by people who are trying to eat healthier foods or people whose religion does not allow them to eat meat.