= 1687
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 382.
This is English as a Second Language Podcast’s English Café episode 382. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website as ESLPod.com. Download this episode’s Learning Guide, an 8-10 page guide we proved for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to continue our series on famous songs – famous American songs – talking about a song called “Chicken Fat.” Yes, “Chicken Fat.” We’re also going to talk about a group called “Hell’s Angels” and who they are. And as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on famous songs. Today we’re going to talk about a song that I first learned when I was a child called “Chicken Fat.” “Chicken Fat” is a song by Robert Preston. Preston was an actor who is best known for his role – his acting performance, his character – in a very popular musical called “The Music Man.” A “musical” is a play or a movie where the characters often sing.
In 1961, Robert Preston was approached by, that is, he was asked by, the President’s Council on Physical Fitness to help them get the message out about the importance of doing physical activity. “Physical fitness” is the idea that you should have a healthy body, and especially under President John F. Kennedy, there was a movement, there was a plan, to get American children, especially, to be more physically active, to be more, we would say, “physically fit” (fit). So, to help encourage children to exercise more, they asked Preston to write a song, a song that would help young students do their exercises everyday at school.
The song he wrote was “Chicken Fat,” and it became what we would call a “surprise hit.” A “hit” (hit) is a song that becomes very popular or a television show that becomes very popular. We sometimes talk about the “hit song” or the “hit movie.” Well, this was a “surprise hit,” meaning people didn’t really expect it to become so popular. It wasn’t a rock and roll song. It wasn’t a love song. It wasn’t a traditional song. It was a song to help children exercise, as you’ll hear in a moment.
The song was distributed or given – sent – to schools across the United States, and many students of the 1960’s and 1970’s listened to this song as they did their daily calisthenics. “Calisthenics” (calisthenics) are exercises that make you stronger. They don’t involve, typically, weights or using machines. They are exercises that you can do anywhere on your own. The lyrics or words to the song mostly just describe the different exercises that the kids are supposed to do. Students listened to the song, typically during their P.E or Physical Education classes, and then they did the exercises as they listened to the song. The song was mostly for younger children. We’re not talking about teenagers or high school students.
The song was very professionally produced. It was very professionally made. They had an “orchestral accompaniment” for the song, meaning they had a full orchestra – a large group of people playing all sorts of instruments, the kind you would normally hear in a symphony orchestra – for example, the kind you would hear if you went to listen to a Beethoven Symphony with violins and horns and oboes and all sorts of different musical instruments. The orchestra accompanied or played with the singer, as in this case, he sang. I was unable to get an orchestra here in our recording studio today, so you’ll just have to hear me singing the song.
Before I sing the song, I want to tell you that a “push-up” (push-up) is a common type of strengthening exercise, an exercise to make you stronger. A “push-up” is when you lie on the ground with your stomach on the floor then you use your arms, by putting your hands flat against the floor, to push yourself up. That’s what a push-up is. It’s a very common exercise that children might do or young adults. Here’s the song, then:
Push up
Every morning
Ten times.
Push up
Starting low.
Once more on the rise.
Nuts to the flabby guys!
Go, you chicken fat, go away!
Go, you chicken fat, go!
It’s a lot better with the orchestra, really.
The lyrics tell the children to do their push-ups every morning ten times - so you raise your body and lower it ten times - “starting low,” meaning you start on the ground and you push yourself up. When you push yourself up, you’re “on the rise,” you’re going up. That’s the meaning of the phrase “once more on the rise.”
The next line is a little strange – “Nuts to the flabby guys.” “Flabby” (flabby) is an informal word to describe someone who’s fat, someone who’s overweight, and if you’re overweight, you’ll often have extra skin, or your skin gets stretched out, is really what’s happening. The person who is flabby is not considered to be very strong, to be very, what we would describe as “muscular” – to have strong muscles.
To say “nuts” (nuts) to something is sort of a way of saying that someone is crazy or someone is not worth taking seriously. “Nuts to the flabby guys” probably means that the singer and the people – the children doing the exercises – see themselves as separate from the flabby guys. They’re not one of them. They don’t want to be one of them.
Then, the main part of the song is “Go, you chicken fat, go away!” “Chicken fat,” of course, technically, would be the fatty, oily part of chicken meat, which has a lot of calories in it. When you eat chicken fat and other fatty, high-calorie foods, you’re more likely to become fat yourself, to become overweight.
So, the song might be saying that by exercising, you’re getting rid of that extra weight you gained, you got, because you were eating too much chicken fat. Another possible meaning – and I’m sure university professors and scholars have been debating this for many years – is that the singer is calling the students “chicken fat” – being sort of rude to them. I don’t think that’s actually what is happening. I think the singer is telling the students they can get rid of their fat – their chicken fat – by exercising. That’s why he says, “Go, you chicken fat, go away,” meaning, “Leave! We don’t want to have you anymore.”
This song was popular in the 60’s and 70’s. It is not a song that most people under the age of, I don’t know, maybe 45 would be familiar with anymore. Schools stopped using the song in the late 70’s, early 80’s.
I remember the song, not so much from my own school, but from my father. My father, as some of you may know, was a teacher. He was a physical education teacher, what we used to call a “gym (gym) teacher.” “Gym” is short for gymnasium – the place where you exercise and play sports. My father used to use this song with his schoolchildren – with the children in his classes. They would play this song and he would bring the record back home and we would listen to it at home. We didn’t exercise at home, of course, we were too busy watching television.
Maybe it’s too bad, maybe it’s unfortunate, that people under the age of 40, 45, don’t know this song, especially when you look at the statistics of how many Americans are overweight, how many of them are, basically, too fat. Let’s listen to the song once again. I kind of like it. I’ll sing the same verse, the same section, again. The song is actually quite long. It’s like six minutes long.
Push up
Every morning
Ten times.
Push up
Starting low.
Once more on the rise.
Nuts to the flabby guys!
Go, you chicken fat, go away!
Go, you chicken fat, go!
Our next topic is an interesting group that was popular more in the 60’s and 70’s and 80’s, but it’s still around. It’s called the Hell’s Angels. The full name of the group is “The Hells Angel’s Motorcycle Club.” This was a club created here in Southern California in 1948 by members of many different motorcycle clubs. “Motorcycles,” are bikes that have motors on them – cycles that have motors on them. They’re often associated with big men wearing leather coats and were quite popular, I think more popular, during the 60’s and 70’s or 50’s, 60’s, and 70’s than they are now. I’m not sure about how many motorcycles actually get sold. When I was growing up, riding a motorcycle for a man was a very cool thing to do, a very attractive thing to do.
This motorcycle club was called “Hell’s Angels” - or is called “Hell’s Angels” – it’s sort of an odd name. “Hell” is the place where, at least in the Christian religion, you go if you are bad – your soul goes if you are bad. An “angel” is someone who was created by God who doesn’t have a body – someone who is just a “spirit,” we would say. There are good angels and there are bad angels – at least, according to the Christian tradition. The term “Hell’s Angels” would refer to the bad angels – the angels of evil. Apparently, the name was taken from some of the groups, the name of some of the groups that fought in World War I and World War II.
People who want to become members of Hells Angels have to meet certain criteria, certain qualifications, although it isn’t exactly clear what those are. If you try to research it, it’s somewhat difficult to find out. However, becoming a member is apparently a very long process. It takes a long time. There are about 100 chapters or local clubs that are affiliated with or belong to the Hell’s Angels organization in more than 30 countries. So, it’s just not something here in the United States.
It seems to me that when most people think of Hell’s Angels, they think of the way the people in the club look, their physical appearance. I mentioned earlier that the image of a Hell’s Angels motorcycle rider would be a man, very large, maybe even a little fat, with big black motorcycles. They wear black leather clothing and helmets. A “helmet” (helmet) is basically a big hat that goes over your entire head to protect you. Hell’s Angels, at least in the popular imagination, typically have a lot of tattoos – permanent ink drawn on your skin. They often have long hair. They have long beards.
The organization uses patches, which are pieces of cloth with very fancy designs on them, that you put on other materials, especially jackets. The Hell’s Angels patches usually have red letters on a white background. The main logo – the main symbol – of Hell’s Angels is a skull, which is the bones of the human head. The skull is wearing a red and yellow helmet that has large yellow wings on the back.
The police and many government agencies consider the Hell’s Angels to be more than just a club. They consider, in many cases, for it to be a motorcycle gang. A “gang” (gang) is a group of people who are doing things that are dangerous, often illegal, against the law, doing things that are violent. But the organization itself says that its members simply love motorcycles and love to share their interest in motorcycles and that if anyone has committed a crime who’s a member of Hell’s Angels, it was the responsibility of that person, not the club itself.
Although some police consider Hell’s Angels to be, basically, a criminal organization, most of the people I know don’t think of it that way. That might be because “bikers,” people who ride motorcycles are, as I mentioned, becoming less popular. When I was younger, riding a motorcycle was considered cool. It was part of a masculine identity, a tough image. Today, when you see people on motorcycles, you see mostly 50-, 60-, and 70-year-old men riding the motorcycles, many of them with grey hair – very different from the image of a motorcycle rider, a biker, when I was growing up, where they were mostly younger men.
Those younger men have gotten older. They’re still riding motorcycles. But it hasn’t kept up in its popularity. Some motorcycle riders, some bikers, like to “let loose.” They like to relax, be a little wild on the weekend, and go out and ride their motorcycle. Most of them will probably be dead in a few years and we won’t have to worry too much about Hell’s Angels.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Rosalino (Rosalino). We’re not sure where Rosalino is from. We believe Rosalino is here on our planet. Rosalino wants to know the meaning of the word “through” (through) as we use it in the following sentences, “the whole night through,” and the expression, “the dance is through.”
“Through” in the first example – “the whole night through” – means during the entire length of time. Normally, it comes before the period of time we’re talking about. For example, “I studied through the night.” “I’m working through the day.” I’m working that entire time. Or “This sale will continue through the month of November.” In the expression “the whole night through,” through comes at the end, making it sound a little more poetic, a little more dramatic perhaps.
We can also use through to mean that something is finished, something is completed. “The dance is through.” That means the dance is over. It is no longer going on. “When is the class through?” That means when is the class over, when does it end, at what time or on what day does it end. Those are the meanings of “through” in the sample sentences or phrases that Rosalino gave us.
“Through” can also mean beyond or past. For example, “You can get to the restroom by walking through that door.” That means you have to go to the door, open it and then go beyond it, go past it. We can talk about cars that go “through a red light.” They’re supposed to stop at the red light but they don’t. They go through it. The more common expression there would be to “run” a light (run), but you can also say “go through the light.
“Through” can also mean in at one end and out at the other. For example, we’re going to go through Central Park. We’re in New York City and we want to walk from the Metropolitan Museum of Art to the American Museum of Natural History. The Metropolitan Museum of Art is on one side of Central Park and the American Museum of Natural History is on the other side. To get from one to the other, you have to “walk through” Central Park – or you could drive through Central Park too, but, we’re walking, we’re trying to save gas. It’s expensive, you know.
Our second question today is from Julian (Julian) in Andorra. I love the fact that Julian wrote us. We’ve never had a question from Andorra. I remember learning about the little country of Andorra, which is in Europe, when I was in school, and now I can say I know someone in Andorra.
Julian wants to know the meaning of two expressions. The first is “It’s a given” (given) and “It figures” (figures). “It’s a given” means that this is known to everyone. That’s one meaning. “It’s a given” means it’s without a doubt. “It’s a given that during the wintertime it will snow in Minnesota.” Everyone knows that.
Sometimes we use the expression to mean that we don’t need to talk about a certain topic or we can assume that a certain thing is true. For example, you’re hiring someone for a job. You’re trying to get someone to work for your company. And you know that they want to get money to help them move from the city where they’re living now to your city. So, you might say to them, “Well, it’s a given that we will pay for your relocation, for you moving from your city to our city. It’s a given.” You don’t even have to talk about it because you’re going to assume that that is true, and then you go on to talk about other things. So, “it’s a given” is often used when we want to skip over, we want not to waste our time talking about something that everyone already agrees to, that everyone already knows is true or believes is correct.
“It figures” is an expression we use to mean “not surprising,” something that is expected. Usually, what is expected, what is not surprising is something negative, something bad that happens. “It figures that all of the girls in my high school said ‘no’ to me when I asked them to go to the dance.” (Oooh, sad!) It figures. It’s not surprising but it’s a little sad. Both of these expressions are more common in conversational, in spoken English, than they are in written English. We might see them, however, especially if you’re reading dialog in a book, in a novel or a play.
Our last question is from Taiwan, from Titan (Titan), which is a great name – Titan! Titan wants to know how you pronounce two words: “glass” (glass) and “grass” (grass). Well, I just pronounced them. It is, however, difficult for some speakers of English as a second language to hear the difference and pronounce the difference with words that have l’s and r’s in them.
This of course, is well known to those of you who have that difficulty. “Glass” is something you drink out of. “Grass” is something that would be on the ground – on the lawn, in front of your house or in the back of your house. “Grass” is also an old, informal word for marijuana, a drug that you smoke to get high. I’m not, of course, suggesting that you go out and do that. I’m just giving you another meaning of the word. We don’t use that term very often anymore. That’s kind of an old fashioned word for marijuana. “Grass” is typically just the stuff that’s on the ground in front of your house.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQUillan. Copyright 2013 by the Center for Educational Development.
.
Glossary
surprise hit – a song, film, or other type of entertainment that becomes very popular when nobody expected it to
* Everyone was amazed when our small independent film became the surprise hit of the summer.
calisthenics – exercises designed to strengthen muscles and increase flexibility
* For forty years, my mother has done calisthenics each morning to keep herself healthy and in good shape.
orchestral accompaniment – with a full orchestra (a large group of all the instruments normally used to play symphonies and other types of classical music) playing in the background while someone sings
* This is a recording of Nat King Cole singing Christmas songs with full orchestral accompaniment.
push-up – a strengthening exercise where one lies on one’s stomach on the floor, while bending one’s arms at the elbows so that the flat parts of one’s hands are against the floor, and then one pushes up so that one’s weight is on the hands and toes
* Betty challenged her brother to a contest to see who could do more push-ups.
flabby – having soft, loose skin, without much muscle; being fat and having extra skin
* Before Jamal started jogging with his friends, he was a flabby teenager.
nuts to (something) – an old-fashioned phrase used to express disrespect, saying that someone is silly or crazy or not worth taking seriously
* Students were tired of Joel always making trouble for them, so they started putting signs on their lockers that read, “Nuts to bullies!”
angel – a spirit who serves God, and is usually shown as a creature that mostly looks like a human, but wears a long white robe or dress, with large wings, and can fly and lives in heaven
* Carla believes that Grandma now lives in heaven and is an angel who watches over their family.
helmet – a special round, hard hat that protects one's head, usually worn while riding a bicycle, motorcycle, or similar vehicle
* Monica is afraid to ride on her boyfriend’s motorcycle without wearing a helmet.
tattoo – a permanent ink drawing on one’s skin
* Darrel got a tattoo of his daughter’s name on his arm when she was born.
patch – a piece of cloth with elaborate or fancy designs that can be sewn onto other pieces of material, such as a jacket
* My military uniform has patches for each stage of training I successfully completed.
gang – a group of people who are engaged in dangerous or violent activities outside of the law
* Forrest’s parents moved out of South McVille to get them away from gangs.
biker – a person who rides motorcycles, usually as part of his or her lifestyle or as a hobby
* On Sundays, bikers ride down this street as they head for the desert roads.
to let loose – to relax and become a little bit wild
* You can’t study tonight. It’s Friday night and we’re all ready to let loose!
through – in at one end and out the other; beyond; past; during the entire length of time; finished
* We’ll know they’re through with the race when they go through the tunnel. We’ll wait here through the entire afternoon, if we have to, to see them finish.
it’s a given – it’s known to everyone; it’s without a doubt
* It’s a given that no matter where we take my mother to dinner, she’ll complain.
it figures – it’s not surprising; it’s expected
* It figures that as soon as I buy a new lawnmower, my neighbor buys a better and more expensive one.
What Insiders Know
Easy Rider
In the 1960’s, the United States was changing quickly socially. The new “generation” (group of people about the same age) had very different “values” (ideas of what is right and wrong) than their parents. These changes created a lot of “tension” (misunderstandings and problems) among different parts of the American population. The film Easy Rider was about the young people of this time.
The famous actor Peter Fonda wrote Easy Rider and it was released in 1969. The film is about two young Americans who “smuggle” (illegally move from one place to another) “cocaine” (an illegal drug that looks like white powder) from Mexico to Los Angeles, California. The two young men take the money they earn and ride their motorcycles across the southern United States. They want to go to New Orleans, Louisiana, for “Mardi Gras” (a large street party held every year). This type of film is called a “road movie” because it shows different parts of the country as characters in the movie experience it. After Easy Rider, road movies became more common.
These two men discover a different America than they had expected. They are invited to spend some time in a “commune” (a large community of people who live together and support each other without help from others). There were many communes in the United States at this time, but they were a new type of living arrangement. The communes were important parts of the “counterculture” (an attitude of a group of people that is completely different than what is considered normal) movement during this time.
Easy Rider also contains examples of racism similar to what was common in the southern United States at the time. The movie was a way of showing what was really happening in the country. It started a new type of filmmaking based on “realism” (showing how things really are).