= 0853
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 853: Reading an Obituary
This is English as a Second Language Podcast episode 853. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. How are you today? Oh, me? Pretty good, thanks for asking.
This episode, like all of our episodes, has a Learning Guide, and you can find that guide at ESLPod.com.
This is a dialog between Ivy and Stephan about reading an obituary, a notice in the newspaper or on the Internet about someone who’s died. Let’s get started.
[start of dialog]
Ivy: This is so sad!
Stephan: What is?
Ivy: I’m reading the obituary for one of my favorite actors as a child, Mr. McBoo. He had quite a life.
Stephan: Oh, yeah?
Ivy: Yeah, and this article has really done him justice. It’s a nice tribute to a man who touched so many lives. It says here that he’s survived by his wife and five children.
Stephan: Did he live to a ripe old age?
Ivy: He was 97 when he died. There’ll be a memorial service and funeral for him this Saturday. I think I’ll send some flowers.
Stephan: Really? You didn’t know him personally, did you?
Ivy: No, but it would be nice to be part of the funeral, in some small way. I wonder who’ll be giving the eulogies. I’m sure it’ll be somebody important.
Stephan: If you say so. I’ve never heard of him. Was he on a children’s show or something?
Ivy: You’ve never heard of Mr. McBoo?! Were you raised in a cave?
Stephan: Not quite. We didn’t have a TV in the home when I was growing up.
Ivy: Oh, you poor, poor man. You’ve been deprived of Mr. McBoo all your life. Don’t worry. I’ll fix that. I have all of his shows, so we can have a viewing marathon this weekend.
Stephan: Lucky me.
[end of dialog]
Ivy begins by saying to Stephan, “This is so sad!” Stephan says, “What is?” Ivy says, “I’m reading the obituary of one of my favorite actors as a child, Mr. McBoo. He had quite a life.” An “obituary” (obituary) is a short article or a short notice, printed in a newspaper, or nowadays, on the Internet, after someone dies, about that person. It will say the person’s name, usually, how old they were, the date they died, and something about them, who they were.
Ivy says that she’s reading the obituary of one of her favorite actors when she was young, a Mr. McBoo. “He had quite a life,” Ivy says. The expression “to have quite (quite) a life” means that it was an interesting or exciting life. Stephan says, “Oh yeah?” Ivy says, “Yeah, and this article has really done him justice.” “To do someone or something justice” is to do something very well, to be good enough for that something, to do what that someone or something deserves. So, if a book does someone justice, we mean it describes them accurately, correctly. It does what it should do in describing the life of that person. When I sing, I never do the song justice because I do a very bad job. So, you can use it in the negative as well. “It doesn’t do him justice.” Notice we use the verb “to do” – “to do (a person)” or “to do (a thing) justice (justice).”
Ivy says, “It’s a nice tribute to a man who touched so many lives.” A “tribute” (tribute) is something that is done or said to show respect for someone or to something, to show admiration. Sometimes, when someone is very famous and they get old, they will have a tribute on television to that person, where other people will stand up and they will talk about what a wonderful person that is. That’s a tribute. Ivy says that this obituary is a nice tribute to a man who “touched so many lives.” “To touch (touch) a life” means to affect someone, to have an impact on someone in a positive way.
Ivy says, “It says here that he” – Mr. McBoo – “is survived by his wife and his five children.” The expression “to be survived by someone” means that those are the people, usually your close relatives, who are still living. So, if I die and my wife is still living, my obituary would say that I was survived by my wife. That’s the close relation of mine who is still living. So, if you are survived by someone, those are people who continue to live even though you have died, and typically, that would be a spouse (your wife, your husband), your children, maybe brothers and sisters, cousins, perhaps even parents if someone dies young.
Stephan says, “Did he live to a ripe old age?” The expression “A ripe (ripe) old age” just means a very old age. Typically, we use this expression when the person not only has lived a long time, but they were in pretty good health even when they were old. They could still think clearly. They were still very much active. Ivy says, “He was 97 when he died. There’ll be a memorial service and funeral for him this Saturday.” A “memorial service” is usually an event where people come and they talk about the person who has died. They remember him. They share their own memories with other people. A “funeral” is typically a more formal event, often a religious event, where the body is either taken to a church and there is some sort of religious ceremony held, and/or to a cemetery where the body is put into the ground. A “cemetery” (cemetery) is a place where bodies are buried – after you die, of course.
Ivy says, “I think I’ll send some flowers.” It’s common when someone dies, especially if you’re not able to go to the memorial service or funeral yourself, to send flowers, and those flowers are usually put next to the body or somewhere in the room where the service is being held. Stephan says, “Really? You didn’t know him personally, did you?” When we say we know someone “personally,” we mean we have met that person. We have shook their hands. We’ve talked to them. We knew them personally. I know who the president of the United States is, but I don’t know him personally. He’s never come to my house for dinner, which is probably a good thing because I don’t cook very well.
Ivy says, “No” – no, I didn’t know him personally – “but it would be nice to be part of the funeral in some small way. I wonder who’ll be giving the eulogies.” A “eulogy” (eulogy) means a speech, usually delivered or given at a funeral where the speaker says nice things about the person who died. Sometimes, this is a done by a religious official. Sometimes, it’s done by a member of the family. It really depends on the situation. Not all memorial services or funerals have eulogies. Some do, some don’t.
Ivy says “I’m sure” the person who will be giving the eulogies will be “somebody important.” Stephan says, “If you say so.” This expression, “If you say so,” is used when you don’t really believe what the other person has said, but you don’t want to fight with them. You don’t want to argue with them. Someone may say, “Oh, this is the best Mexican food I’ve ever eaten!” and you go, “Well, if you say so,” meaning you don’t really agree. You don’t think it’s very good, but you don’t want to argue with the person.
Stephan says, “I’ve never heard of him [of Mr. McBoo]. Was he on a children’s show or something?” “Was he on a show that was for children?” The phrase “or something” means “or something else” – something similar. Ivy says, “You’ve never heard of Mr. McBoo!? Were you raised in a cave?” A “cave” (cave) is a large covered space, usually in a mountain or some other rocky area, some other hilly area, maybe even underground, that is often the home for certain animals. A “cave” is sort of like part of a mountain or a hill or in the ground that has been carved out, often through water going through it, or some other process over a long period of time. The expression, “Were you raised in cave,” however, really means “Did you grow up without any contact with the rest of the world?” It’s sort of a criticism, a funny way of saying, “How could you not know about this person?” Only someone who grew up in the middle of the forest or on an island or in a cave would not have heard of this person because he’s so famous. That’s the idea.
Stephan responds to Ivy, “Not quite,” meaning no, I didn’t grow up in a cave. “We didn’t have a TV in the home when I was growing up.” So, he didn’t have a television in his house. That’s not very common anymore, but it’s possible. Ivy says, “Oh, you poor, poor man.” She’s sort of being funny here – “You poor,” meaning unfortunate, “man.” “You’ve been deprived of Mr. McBoo all your life.” “To deprive” (deprive) means not to let someone have something that is necessary or perhaps is very enjoyable. Stephan has been deprived of Mr. McBoo. He hasn’t been able to find out about Mr. McBoo his entire life.
“Don’t worry,” Ivy says, “I’ll fix that.” I’ll take care of that situation. “I have all of his shows, so we can have a viewing marathon this weekend.” A “marathon” (marathon) is usually the word we use for a long race, for people who are running. However, more recently, it has been used to describe when a television channel has many different episodes of the same show on, on a single day, or on a single weekend. So, if we have a holiday weekend, a weekend where we have three days that we don’t work, one of those days might be a television marathon of a popular show. Usually, these are shows that were on a long time ago. So, in 2012, it would be, perhaps, shows like Star Trek or Seinfeld or Friends. There might be a marathon of those shows. So they show one show and then another one and then another one, and so forth.
Ivy wants to have a marathon of the old Mr. McBoo shows. Stephan says, “Lucky me.” This expression is used jokingly, sarcastically, we would say, to mean that you don’t feel very lucky. It means the opposite of what it says. It all depends on how you say it, but usually, it’s used as a joke. When someone says, “Oh, lucky me,” they mean I don’t feel so lucky. I have to experience this thing, but I’m not really happy about it. Stephan is not happy about having to watch all of these old children shows, and I kind of agree with Stephan. Mr. McBoo, by the way, is not a real person, was not a real actor, which means, of course, he didn’t really die.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Ivy: This is so sad!
Stephan: What is?
Ivy: I’m reading the obituary for one of my favorite actors as a child, Mr. McBoo. He had quite a life.
Stephan: Oh, yeah?
Ivy: Yeah, and this article has really done him justice. It’s a nice tribute to a man who touched so many lives. It says here that he’s survived by his wife and five children.
Stephan: Did he live to a ripe old age?
Ivy: He was 97 when he died. There’ll be a memorial service and funeral for him this Saturday. I think I’ll send some flowers.
Stephan: Really? You didn’t know him personally, did you?
Ivy: No, but it would be nice to be part of the funeral, in some small way. I wonder who’ll be giving the eulogies. I’m sure it’ll be somebody important.
Stephan: If you say so. I’ve never heard of him. Was he on a children’s show or something?
Ivy: You’ve never heard of Mr. McBoo?! Were you raised in a cave?
Stephan: Not quite. We didn’t have a TV in the home when I was growing up.
Ivy: Oh, you poor, poor man. You’ve been deprived of Mr. McBoo all your life. Don’t worry. I’ll fix that. I have all of his shows, so we can have a viewing marathon this weekend.
Stephan: Lucky me.
[end of dialog]
Her scripts touch many lives every day. I’m speaking about our own wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
obituary – a short article printed in an newspaper after someone’s death, summarizing that person’s life and accomplishments, like a very short biography
* According to the obituary, Janice had cancer for years before her death.
quite a life – an impressive life that one admires; a life filled with interesting, unusual, or exciting events and experiences
* Uncle Gabe led quite a life, having lived in more than six countries.
to do (someone or something) justice – to be deserving of someone or something; to be good enough for someone or something that is admired
* This scenery is so beautiful that it would be hard to do it justice in a painting.
tribute – something that is said or done as an honor to show respect or admiration for someone or something
* They built this statue as a tribute to the people who died in the rebellion.
to touch a life – to affect someone in a positive or beneficial way
* The best part of being a doctor is the ability to touch lives and make people feel better.
to be survived by – to be outlived by someone; for one or more members of one’s family to live longer than oneself
* Jona passed away last week, but he is survived by his two daughters.
a ripe old age – a very old age, especially when one is still in good health and able to think clearly
* If you keep exercising and eating well like you do now, you’ll live to a ripe old age.
memorial service – an event or ceremony where people speak about someone who recently died, sharing their memories and expressing their sadness
* Marliss had many friends, so hundreds of people attended her memorial service.
funeral – an event or ceremony where the body is buried underground, usually while a religious leader prays and says things about the life of the person who has died
* Is it really that important to wear black to a funeral?
personally – in person; as a friend or acquaintance; having met someone directly
* Do you know any celebrities personally?
eulogy – a speech, usually delivered at a funeral, in which the speaker says nice things about the person who has died, sharing information about that person’s life
* I was surprised that the eulogy focused so much on his career and hardly mentioned his family.
if you say so – a phrase used to show that one does not fully believe what another person has said, but that one will not argue strongly against it
* A: This is the best food I’ve ever tasted!
B: If you say so. I’m glad you like it, but I don’t think I’ll come to this restaurant again.
cave – a large, covered open space in a mountain or another rocky area, possibly underground, often the home for an animal
* Do any bears live in this cave?
to deprive – to not let someone have something that is necessary or very enjoyable
* Blake was deprived of a normal, happy childhood because he grew up in a war zone.
marathon – a race of runners, traveling a long distance; something that happens for a long period of time, especially watching many episodes of a TV show
* We spent most of the weekend on the couch for a movie marathon.
lucky me – a phrase used sarcastically, meaning that one does not feel fortunate in a particular situation and would prefer not to be in the current situation
* Oh, lucky me, I get to spend the weekend cleaning out the garage.
Comprehension Questions
1. What does Ivy mean when she says that Mr. McBoo touched many lives?
a) He had a lot of children.
b) He was a good masseuse.
c) He affected many people.
2. What does Ivy want to Stephan to do this weekend?
a) She wants him to watch the shows while he exercises.
b) She wants him to watch many of the shows, one after another.
c) She wants him to watch the shows with her daughter.
Answers at bottom.
What Else Does It Mean?
personally
The word “personally,” in this podcast, means in person, having met someone directly: “It’s better to end a relationship personally, not through a text message or an email.” The word “personally” can also mean in one’s opinion: “Personally, I prefer spending the weekend at the beach instead of the mountains.” Sometimes the word “personally” is used to talk about something that one has done by oneself, without help from others: “He’s too busy to sign those letters personally, so he asked his secretary to do it for him.” Finally, the phrase “to take (something) personally” means to become upset or offended by what someone says, because one believes it was said about oneself: “If Hannah arrives at your party a little late, don’t take it personally. She’s late for everything.”
lucky me
In this podcast, the phrase “lucky me” is used sarcastically, meaning that one does not feel fortunate in a particular situation and would prefer not to be in the current situation: “The dishwasher broke so I have to wash the dishes by hand. Lucky me.” The phrase “to be (someone’s) lucky day” means that it will be a good day for someone and that good things will happen to him or her that day: “Wow, I just found a $5 bill in my pocket! It must be my lucky day!” The phrase “to thank (one’s) lucky stars” means that someone was very fortunate and avoided a dangerous, difficult, or uncomfortable situation: “You should thank your lucky stars you weren’t in the office yesterday, because the boss was in a horrible mood.”
Culture Note
Premature Obituaries
In some “instances” (cases; occasions), the obituaries of famous people have been published “prematurely” (too soon; before something is supposed to happen). In other words, obituaries have been published while the “subject of the obituary” (the person who died) was still alive.
Sometimes a premature obituary is the result of an accident, as when a news station or newspaper writes obituaries prematurely to be prepared when famous people die, but accidentally publishes them too soon. A business newsmagazine accidentally published an obituary for Steve Jobs, the co-founder of Apple, three years before he died. Similarly, NBC mistakenly reported that Joe DiMaggio, a famous baseball player, had died in January 1999, because the news studio had prepared for his death when it was reported that he was sick. But he did not actually die until March of that year.
Other premature obituaries are the result of people who have disappeared or appear to have died, but then reappear. Mark Twain, a famous American author, was reported to have been “lost at sea” (to have died while in a boat, usually during a storm) when people “lost track of” (were no longer able to determine the location of) his boat. However, the boat was actually only delayed by “fog” (thick, low clouds that make it difficult to see).
Still other premature obituaries are caused by name confusion. For example, in 1993, actor Sean Connery was reported to have died, even though he was still alive. The former governor of Texas, John Connally, had “passed away” (died), and some people confused his name with the actor’s name.
Comprehension Answers
1 - c
2 - b