= 0881
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 881: Eating Genetically Modified Foods.
This is English as a Second Language Podcast episode 881. I'm your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and look at the ESL Podcast Blog as well as our special courses in daily and business English.
This episode is a dialog between Ralph and Nicky, about eating what is called genetically modified foods. Let’s get started.
[start of dialog]
Ralph: What’s that?
Nicky: It’s a bigger and better tomato. It’s been genetically modified.
Ralph: You’re not going to eat that, are you?
Nicky: Of course I am. I’m making a salad. Want one?
Ralph: No way. I don’t want to eat something that’s been genetically engineered in a laboratory. Who knows what kind of strange DNA it has.
Nicky: It’s perfectly safe. It’s been modified to grow faster, have more nutrients, and be resistant to disease and pests.
Ralph: And it may contain strange mutations as part of its genetic makeup that they didn’t tell you about. I really wouldn’t eat that if I were you.
Nicky: Where did you get this aversion to genetically modified foods? Scientists and farmers have always used selective breeding with animals and crops to bring you bigger and better food. This is nothing different.
Ralph: Of course it is. And just because it’s bigger, doesn’t mean it’s better. I’ll eat food that’s been modified by the only person I trust.
Nicky: Who’s that?
Ralph: Mother Nature!
[end of dialog]
Our dialog begins with Ralph saying to Nicky, “What’s that?” Nicky says “It's a bigger and better tomato.” A tomato is something that you might eat with a salad or on a sandwich, or use to make sauce for your pasta. Nicky says “It's a bigger and better tomato. It's been genetically modified.” “To modify” (modify) means to change something. “To genetically modify something” means to change the genes, if you will, the components of a plant or an animal that determine what kind of plant and animal that is. “Genes” (genes) are what we might call the building blocks of life. They’re the basic components, the elements that life is constructed on. It's hard to explain that in a very complete manner here, but that's what “genetically” means related to your genes.
Ralph says, “You're not going to eat that, are you?” Ralph doesn't think Nicky should eat it. Nicky says, “Of course I am. I'm making a salad. Want one?” – meaning do you want one? Ralph says, “No way.” “No way” is a very strong way of saying “No, absolutely not.” “No way. I don't want to eat something that's been genetically engineered in a laboratory.” “To engineer,” (engineer) as a verb, means to change, to usually change the structure of something. “Genetically engineered” would be something where scientists have changed the genetic makeup, the genetic composition of that particular plant or animal. A “laboratory” is a place where scientists do experiments.
Ralph says, “Who knows what kind of strange DNA it has.” “DNA” is the chemical substance that carries the genetic information. It's what carries the information from our genes that affects our eye color, our skin color, our physical makeup and so forth. Nicky says that, “This tomato is perfectly safe.” It's completely safe. “It's been modified to grow faster, have more nutrients and be resistant to disease and pests.”
So, Nicky is saying the tomato is safe. “It has been changed only to make it grow faster to give it more nutrients, and to make it resistant to disease and pests.” “Nutrients” (nutrients) is a general word used to describe the substances or the elements within a plant that help you grow, that animals eat, or humans eat that helps their body grow better. It could be a lot of different things. Each food would have different kinds of nutrients.
Nicky says that the tomato was also modified to be resistant to disease and pests. “To be resistant” means that you are not easily damaged by something, you are not easily harmed by something. “Disease” is the same as sickness or illness, when something is not growing and functioning the way it should. “Pests” (pests) are insects or small animals that destroy plants, that destroy the plants that we use to get food from. So pests are always bad things, whether they’re mosquitoes or rodents or any other sort of animal that is going to harm the plants that we are growing to eat.
Ralph says, “And it may contain strange mutations as part of its genetic makeup that they don't tell you about.” Ralph is saying that these genetically modified foods are dangerous because they may contain strange mutations. A “mutation” (mutation) is a genetic change that makes one individual different from another individual. But it's not, if you will, a change that you would expect to take place. So, usually mutation, when we're talking about science fiction, for example, is when something changes in some weird way, some strange way that is considered dangerous or unusual. Mutation is part of the way that the world works in terms of DNA and genes, but here Ralph is using the word as a negative, as a criticism of this genetically modified food. Ralph says that these mutations could be part of the tomatoes’ genetic makeup. We’ve already talked about what “genetic” refers to. “Makeup” (makeup) – one word – refers to composition what something is made of. Ralph says, “I really wouldn't eat that if I were you.” That's a common expression, “If I were you” – if I were in your situation, I would not do that.
Nicky says, “Where did you get this aversion to genetically modified foods?” An “aversion” (aversion) is a hatred or strong dislike of something, something that you would want to avoid. Nicky says, “Scientists and farmers have always used selective breeding with animals and crops to bring you bigger and better food. This is nothing different.” “Selective breeding” (breeding) is the practice of making plants or animals reproduce, or produce new plants or animals that have particular characteristics that you want to increase.
So, if you have two different kinds of dogs and you want to make a dog that is a mixture of these two kinds of dogs, well, you would put the two dogs together – one would have to be male and one would have to be female, of course – and let them do what they do, and then you would “breed” a new animal, a combination of these two different animals. “Selective breeding” is using that basic logic, that basic process with plants or animals, in order to produce plants or animals that have certain characteristics. That's what Nicky says farmers and scientists have been doing for many years and that this is nothing different.
Ralph says, “Of course it is.” “And just because it's bigger” – meaning, the tomato – “doesn't mean it's better. I'll eat food that's been modified by the only person I trust.” “To trust” means to believe, in this case, or to rely on. Nicky asked, “Who’s that?” – who is that person that you trust? Ralph responds, “Mother Nature.” Mother Nature is not a real person. We say “Mother Nature” to refer to the idea that the whole world, the natural world is somehow controlled by this female figure, I guess. Mother Nature refers to the way the environment is, the way nature is without people interfering with it, without men and women making changes to the environment. That's basically the idea behind this term “Mother Nature.”
Ralph treats Mother Nature as a real person that he can trust. What he's really saying here is that he only wants to eat food that is somehow natural, that doesn't have any sort of either chemicals, perhaps, or genetic modifications that would change the way the food is produced.
Now let’s listen to the dialogue this time at a normal speed.
[start of dialog]
Ralph: What’s that?
Nicky: It’s a bigger and better tomato. It’s been genetically modified.
Ralph: You’re not going to eat that, are you?
Nicky: Of course I am. I’m making a salad. Want one?
Ralph: No way. I don’t want to eat something that’s been genetically engineered in a laboratory. Who knows what kind of strange DNA it has.
Nicky: It’s perfectly safe. It’s been modified to grow faster, have more nutrients, and be resistant to disease and pests.
Ralph: And it may contain strange mutations as part of its genetic makeup that they didn’t tell you about. I really wouldn’t eat that if I were you.
Nicky: Where did you get this aversion to genetically modified foods? Scientists and farmers have always used selective breeding with animals and crops to bring you bigger and better food. This is nothing different.
Ralph: Of course it is. And just because it’s bigger, doesn’t mean it’s better. I’ll eat food that’s been modified by the only person I trust.
Nicky: Who’s that?
Ralph: Mother Nature!
[end of dialog]
The person I trust to produce the best podcast scripts on the Internet is our very own Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
genetically modified – with changes having been made to the genes (building blocks of life) within a plant or animal species
* In the future, will people be genetically modified to protect them from diseases?
genetically engineered – created to have some specific characteristics by controlling the genes (building blocks of life) within a plant or animal species
* This corn has been genetically engineered to need less water and grow taller.
laboratory – a room where scientists design and perform experiments, or where engineers build and test things
* Xavier spends long days at the laboratory, searching for a cure for cancer.
DNA – deoxyribonucleic acid; the chemical substance that carries genetic information within living things
* Piotr is going to request a DNA test to determine whether the little girl is really his daughter.
nutrient – a substance found in food or soil that animals or plants use to grow and develop
* Growing children need foods with a lot of nutrients, like whole grains and fresh fruits and vegetables.
resistant – not easily damaged by something; not easily harmed or negatively influenced by something
* This watch is water-resistant, so it’s okay to shower with it, but you probably shouldn’t leave it in the water for long periods of time.
disease – an illness; a sickness
* Polio, malaria, and many other diseases have been largely eliminated in North America.
pest – an insect or rodent (small animal) that destroys crops, spreads disease, and causes other types of harm or problems for humans
* Rats are a major pest in large cities.
mutation – a genetic change that makes one individual different from other individuals of the same species
* If a woman is exposed to certain chemicals while she is pregnant, it can result in mutations that cause birth defects in her baby.
genetic makeup – the genetic structure of a particular organism or individual
* Scientists are analyzing the genetic makeup of certain plants to try to make drugs that imitate their healing properties.
aversion – a strong dislike of something; hatred
* Lynn has a strong aversion to milk and doesn’t want to eat or drink anything that has milk in it.
selective breeding – the practice of making plants or animals reproduce with other plants or animals that have particular characteristics that one wants to increase
* Over thousands of years, humans have used selective breeding to make larger chickens that lay larger eggs more frequently.
to trust – to rely on someone; to believe that someone is good or honest and will not do anything to hurt oneself
* Can I trust you to keep a secret?
Mother Nature – the idea of the natural world as a woman who controls what happens and/or cares over all creatures
* Hurricanes, tornadoes, and earthquakes remind us of how powerful Mother Nature is.
Comprehension Questions
1. What kind of tomato is Nicky eating?
a) A tomato that is redder than other tomatoes.
b) A tomato that grew more quickly than other tomatoes.
c) A tomato that is less vulnerable to insects.
2. Whom does Ralph trust?
a) The natural world.
b) His mother.
c) Women who have been mothers.
Answers at bottom.
What Else Does It Mean?
pest
The word “pest,” in this podcast, means an insect or rodent (small animal) that destroys crops, spreads disease, and causes other types of harm or problems for humans: “Pests destroyed their wheat crop, so next year they’re planning to plant something else.” A “pest” is also an annoying person who will not leave one alone: “My little sister Dynee was a major pest when we were growing up, but now we’re good friends.” As a verb, “to pester” means to annoy someone repeatedly, possibly asking for something again and again: “Stop pestering your boss for a raise! Instead, focus on performing your job really well to earn a raise, instead of always just asking for one.” Or, “I hate the way marketers always call at mealtime to pester us with whatever they’re selling.”
to trust
In this podcast, the verb “to trust” means to rely on someone, or to believe that someone is good or honest and will not do anything to hurt oneself: “Do you trust your teenagers to behave while you and your wife are gone for the weekend?” The verb “to trust” also means to believe that something is true or accurate: “If we trust their numbers, the business appears to be doing very well.” The phrase “to trust (someone) with (something)” means to entrust, or to let someone have control over something because one knows they will treat it well: “I’m going to trust you with this expensive necklace, because I know you’ll be careful with it.” Finally, the phrase “tried and trusted” describes something that has been done many times and is proven to work well: “This software is a tried and trusted solution for identifying security threats to a website.”
Culture Note
Genetically Modified Crops
Several genetically modified “crops” (plants grown for food or clothing) have been approved for “consumption” (use, especially through eating). For example, “papaya” (a large, tropical fruit with orange flesh and large, round, black seeds) has been genetically modified to resist a virus that was threatening to “destroy” (ruin) the papaya industry in Hawaii. Today, 80% of the papaya grown in Hawaii is this genetically modified type. About 13% of the “zucchini” (a long, green vegetable) grown in the United States is also genetically modified for resistance to viruses.
Many “cooking oils” (liquid fat used for cooking other foods) are made from genetically modified crops, such as soybeans, and corn. “High fructose corn syrup” (a sugar substitute made from corn) and other products are also made from these genetically modified crops.
A lot of the sugar produced in the United States is also “derived” (made) from genetically modified crops, particularly sugar beets, which have been genetically modified to be more “tolerant to” (not affected by) “herbicides” (chemicals used to kill “weeds” (unwanted plants)). The sugar produced from genetically modified crops is chemically identical to “conventional” (produced in traditional ways, without the use of genetic modifications) sugar, but some people remain concerned about the “consequences” (what happens as a result) of consuming genetically modified foods.
As of 2012, no genetically modified animals have been approved for consumption, but the “FDA” (Food and Drug Administration, a U.S. government agency) is considering approval of genetically modified “salmon” (a type of fish with pink meat) for consumption.
Comprehension Answers
1 - c
2 - a