= 0887
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 887: A Destructive Storm.
This is English as a Second Language Podcast episode 887. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode.
This episode is a dialogue between Allen and Monica about a dangerous storm, when you have very bad weather. Let’s get started.
[start of dialog]
Allen: Are you all right?
Monica: Yes, we’re fine, but that blizzard really caught us off guard, especially this time of year. Have you seen the news?
Allen: I just watched it. Overnight, the storm felled over 30 trees in and around the town and toppled utility lines. City officials are saying that some residents may not get their electricity restored until the weekend.
Monica: That’s terrible, especially with these unseasonably cold temperatures. I heard the ferocious storm last night, but I didn’t expect that homes would actually be in danger of washing away.
Allen: I don’t know if any will actually be washed away unless we continue to get steady rain and snow, but those downed trees wrecked plenty of homes. It’ll take months for us to fully recover from this storm.
Monica: They’re calling it “The Storm of the Century.”
Allen: Well, if we just get one of these storms this century, then that’s more than enough!
[end of dialog]
Allen says to Monica, “Are you all right?” Are you okay? Monica says, “Yes, we’re fine, but that blizzard really caught us off guard, especially this time of year.” Apparently Allen is talking to Monica on the telephone. Monica says, “We’re fine.” We’re okay. “But that blizzard really caught us off guard.” A “blizzard” (blizzard) is a very strong storm, with a lot of cold air and fast-moving wind and most importantly a lot of snow. A blizzard is when it's snowing and the wind is blowing very hard, so you can't see as you walk outside because there's so much snow. Monica said the blizzard really “caught us off guard.” “To catch someone off guard” – “caught” is the past tense of “catch” – means for something to happen when a person is not expecting it and is completely unprepared for it. I was caught off guard when my girlfriend told me that she was leaving me for another man. I was caught off guard. I was completely surprised. And isn't that the way it typically is? Right, guys?
Well, Monica was caught off guard by this blizzard. She asks Allen if he’s seen the news – the newspapers or the news reports on television. Allen says, “I just watched it.” I just watched it on television. “Overnight”- through the night or during the night – “the storm felled over thirty trees in and around town and toppled utility lines.” “To fell” (fell) means to make a tree fall down, usually by cutting the tree down, but if you have very strong winds, you could also have trees that fall down from the wind. Allen says the storm also toppled utility lines. “To topple” (topple) means to knock something over, to knock something down.
A utility line is also called a power line. These are long cables, long wires that carry electricity and Internet and telephone signals and other electronic information from your house, or your building, to some other place. So, if you have electricity in your home or in your office, there must be some sort of line that connects the power from the city or the local power plant to your house. We would call that a utility line. Utility lines, at least, traditionally in the United States, were always put up on very tall poles. Now, in many places they bury the utility lines in the ground but traditionally and still in most places, in my neighborhood, for example, the utility lines are up on tall poles. That's the case in our story as well.
Allen says, “City officials are saying that some residents may not get their electricity restored until the weekend.” A “resident” is someone who lives in a particular area. I'm a resident of Los Angeles. I'm a resident of California. In the United States, the place where you are a resident, where you live permanently, is the place where you can vote, where you get your driver’s license, where you pay your taxes and so forth. “City officials,” according to Allen, “are saying that some residents may not get their electricity restored until the weekend.” “To restore” (restore) means to bring something back that perhaps has gone away, or was damaged. We’re going to restore this old building. It's falling apart. It's not the way it used to be. We’re going to make it the way it used to be. We’re going to bring it back to the condition that it used to be in. That's “to restore.” “To restore someone's electricity” would mean to give them back electricity that has been taken from them or that has not been delivered to them in this case, because of the toppled utility lines.
Monica says, “That's terrible, especially with these unseasonably cold temperatures.” Something that is “unseasonably” is something that doesn't normally happen during this time of year. We’re referring specifically to the weather. We describe whether as unseasonable if, for example, it's in the middle of the summer time and it's very cold or if it's in the middle of the winter and it's very hot. That would be unseasonable weather – weather that doesn't normally happen during that time of year that season. There are, of course, four seasons – summer, fall, winter, spring – summer, fall, winter, spring.
Monica says, “I heard the ferocious storm last night.” “Ferocious” (ferocious) is an adjective, typically used to describe someone who's very angry and perhaps very dangerous with a lot of energy. Here it describes a very strong storm, a storm that is causing a lot of damage. Monica says that she didn't expect that homes would actually be in danger of “washing away.”
Okay, this is quite a storm. It probably is a storm that has affected different parts of the country and so, it has different manifestations, different ways of showing itself, if you will. Monica describes the storm first as a blizzard. But then we also hear that utility lines were toppled, which could happen in a blizzard with strong winds. Now, however, she's talking about homes being washed away. “To wash away” means to be removed from where they are by a strong force of water. A river, for example, if it gets too much water in it, could wash away the houses on either side of it. The force of the water could push the houses into the river. That would be “to wash away.” Usually the term “wash away” is used when talking about a “food” (flood). A flood is when you have too much water in a river and in the case that I just described, that would be a flood.
Here, Monica is talking about houses being washed away, but of course that wouldn't be possible if it was a blizzard, unless she's talking about the storm that first went through the southern part of the United States and then the northern part, or first, the northern part and then the southern part. That's possible. You could have rain in one area of the country and snow, where it’s colder, in another area of the country and that does sometimes happen.
Allen says, “I don't know if any will actually be washed away,” any homes, that is – “unless we continue to get steady rain and snow.” “Steady” (steady) means consistent or constant, without any interruption, without a pause – something that happens over a long period of time without stopping. That would be steady. Allen is talking about steady rain and snow. “But,” he says, “those downed trees wrecked plenty of homes.” “To down a tree” is the same as “to fell a tree.” So, a “downed tree” is a fallen tree, a tree that has been knocked down either because it was cut down or because the wind blew it down. “To wreck” (wreck) means to ruin, to destroy, to damage something. Allen is saying that the trees fell on the houses and damaged the house.
This happened to me once. We had a bad storm, a lot of wind and part of the tree in front of my house fell on my house and fortunately, there was no damage. It didn't wreck my house.
Allen says, “It'll take months for us to fully recover from this storm.” “To recover” means something similar to restore. It means to return to the original condition after something has been damaged or injured. We often talk about recover when dealing with someone who's sick or ill. We hope they will “recover.” We hope they will get better. Monica says, “They're calling it the storm of the century.” This is a phrase that the newspapers and news programs on television like to use – “storm of the century.” Whenever you have a big storm, if it's a really big storm, the newspapers will say “It's the storm of the century,” meaning the most important or biggest storm in a hundred years. That is almost certainly not true in most cases of course. There can only be one storm that was bigger than all the others, but every year or two, we hear this description of something being the storm of the century when usually it isn't.
You'll also hear people talk about the “crime of the century,” when someone is murdered or there's some serious or terrible crime. Someone will call it “the crime of the century,” as if it were the worst crime in a hundred years.
Allen says, “Well, if we just get one of these storms this century, then that's more than enough.” Something that is “more than enough” is something that is too much, more than what you want, or more than what you need.
Now let’s listen to the dialog, this time at a normal speed
[start of dialog]
Allen: Are you all right?
Monica: Yes, we’re fine, but that blizzard really caught us off guard, especially this time of year. Have you seen the news?
Allen: I just watched it. Overnight, the storm felled over 30 trees in and around the town and toppled utility lines. City officials are saying that some residents may not get their electricity restored until the weekend.
Monica: That’s terrible, especially with these unseasonably cold temperatures. I heard the ferocious storm last night, but I didn’t expect that homes would actually be in danger of washing away.
Allen: I don’t know if any will actually be washed away unless we continue to get steady rain and snow, but those downed trees wrecked plenty of homes. It’ll take months for us to fully recover from this storm.
Monica: They’re calling it “The Storm of the Century.”
Allen: Well, if we just get one of these storms this century, then that’s more than enough!
[end of dialog]
She's a resident of beautiful Los Angeles, California, and she's our scriptwriter. I speak of course, of our very own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
blizzard – a very strong storm with cold and fast wind and a lot of snow, and limits one’s ability to see
* During the blizzard, there was so much snow that we couldn’t even see the front door from our driveway.
to catch (someone) off guard – for something to happen when a person is not expecting it and is completely unprepared for it
* When Melina announced that she was pregnant, it caught Doug off guard.
to fell – to make a tree fall down, especially by cutting it
* In the past, a man might spend a whole day felling a tree, but now modern equipment makes the job much easier.
to topple – to knock something over; to knock something down; to make something lose its balance and fall
* As Lyla walked by the table, she bumped it with her hip and accidentally toppled the stacks of books that had been on it.
utility line – power line; a long cable (wire) that carries electricity, Internet and/or telephone signals, usually hung high above the ground between poles
* If you see a utility line on the ground, stay away from it and call the power company right away.
resident – someone who lives in a particular area or in a particular building
* This apartment complex has more than 200 residents.
to restore – to bring something back to its previous state or condition, especially after is has been damaged
* Do you think anyone will be able to restore these photographs? They were damaged in the fire.
unseasonably – describing weather that is unusual during the current time of year, for example, too hot in the wintertime, or too dry during the rainy season
* The weather has been unseasonably wet this year, but it has been very good for farmers.
ferocious – very strong, angry, and dangerous, with a lot of energy and possibly causing damage
* How do circus performers learn to work with ferocious animals like lions?
to wash away – for a large amount of water to pick something up and carry it to another place, especially during a flood
* A lot of the best soil was washed away during the heavy rainstorms, so the famers will have to use a lot of artificial fertilizers before they plant the next crop.
steady – consistent or constant, without a break or pause, happening continuously over time without changing
* We’ve seen steady improvement in our sales figures over the past eight months.
downed – fallen; describing something that has been knocked over and is now lying down, especially a tree
* These downed trees may seem worthless, but they provide valuable food for insects and many small animals in the forest.
to wreck – to destroy; to ruin
* How did your son wreck his car?
to recover – to return to the original condition after something has been damaged or injured
* It might be months before Kaitlin fully recovers from the medical treatments.
The Storm of the Century – a very powerful, dangerous storm thought to be the biggest and worst storm in a 100-year period
* That was a big storm, but I doubt it was big or dangerous enough to be called the Storm of the Century.
more than enough – too much; more than one wants or needs
* The food was delicious, but I’ve had more than enough and can’t eat anymore.
Comprehension Questions
1. What are “unseasonably cold temperatures”?
a) Some of the coldest temperatures that have ever been recorded.
b) Cold temperatures that make people dream about other seasons.
c) Temperatures that are much colder than usual at this time of year.
2. What caused the most damage to homes?
a) Strong winds.
b) Flooding.
c) Fallen trees.
Answers at bottom.
What Else Does It Mean?
to wash away
The phrase “to wash away,” in this podcast, means for a large amount of water to pick something up and carry it to another place, especially during a flood: “Santiago’s sandals were washed away from the beach by the ocean waves.” The phrase “to wash (one’s) hands of (something)” means to say that one will no longer be involved in something and will have no responsibility for it: “They’re making terrible decisions, but I’ve washed my hands of the project, so if it fails, it will be their fault.” The phrase “to wash (something) down” means to drink a lot of water while eating or swallowing something: “Here, have some water to wash down that pill.” Finally, the phrase “to wash up” means to wash one’s hands and/or face: “Go into the bathroom and wash up before anybody realizes you’ve been crying.”
downed
In this podcast, the word “downed” means fallen and is used to describe something that has been knocked over and is now lying down, especially a tree: “The downed bodies were scattered all over the battlefield.” As a verb, “to down” means to eat or drink something very quickly: “He downed an entire pizza in less than 10 minutes!” A “hand-me-down” is a used piece of clothing that has been given to oneself by the original owner, usually an older relative: “As a child, Meghan always had to wear her big sister’s hand-me-downs.” Finally, the phrase “down-to-earth” describes someone who is very direct, realistic and practical: “We already have a lot of visionary employees, but now we need someone who is more down-to-earth and realistic about what can be done.”
Culture Note
Types of Storms
A “storm” is a large “disturbance” (change from the normal) in the “atmosphere” (the air surrounding the surface of planet earth), but there are many different types of storms. Probably the most common type of storm is a “thunderstorm,” but other names for it include “lightning storm,” “thundershower,” or “electrical storm.” This is a type of storm with large, dark clouds, strong wind, heavy rain, “lightning” (streaks of light in the sky that appear for short periods of time), and “thunder” (loud sounds heard shortly after lightning appears in the sky). If the storm includes “hail” (pieces of ice that fall from the sky, almost like rain), it is called a hailstorm. Sometimes the “hailstones” (single pieces of hail) can be as large as a golf ball.
A “downburst” is a strong “current” (movement of air or water) of air that moves downward from a large cloud. A “wet downburst” is created by a thunderstorm and is associated with a lot of rain. A “dry downburst” is also created by a thunderstorm, but is associated with very little rain. In the United States, downbursts “tend to occur” (usually happen) in the Great Lakes Region near the border with Canada.
During a “dust storm” or a “sand storm,” very strong wind moves a large amount of dust or sand from one place to another. Dust storms most often happen in “arid” (dry) areas where there has been poor “land management” (how people take care of the land), especially where fields have been left “uncovered” (without any plants, with the soil exposed to the wind). In the United States, dust storms are most common during dry summer months in “agricultural” (farming) areas in the Midwest.
Comprehension Answers
1 - c
2 - c