= 0888
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 888: Advertising in TV and Movies.
This is English as a Second Language Podcast episode 888. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast.
This episode is a dialog about advertising, or having commercial advertisements in the world of television and movies. Let’s get started.
[start of dialog]
Victoria: [clears her throat] Congratulations are in order. I just scored a product placement for our brand in the latest McQuillanator movie. Thank you, thank you very much.
Gerard: Really? That’s great! Will it have a prominent place in the movie?
Victoria: Well, you know how these things are. Our logo goes by in the blink of an eye, but millions of people are going to see it.
Gerard: So will the star be wearing our logo on his shirt or something?
Victoria: Something like that.
Gerard: But not that.
Victoria: No, it’s a little more subtle than that, but it’ll be embedded into an important scene.
Gerard: But where are they going to see it?
Victoria: Is that really important? The important thing is that our brand will be associated with a major Hollywood movie. What more could we ask for?
Gerard: Stop beating around the bush. Where in the movie will our logo appear?
Victoria: All right. It’ll be on the bottom of the star’s shoes, on the sole, and the audience will be able to see it when he’s running.
Gerard: Only if he’s running in slow motion, but he won’t be, right? If it goes by that quickly, it’ll be more like subliminal advertising.
Victoria: Exactly! I hadn’t thought of it that way, but hordes of people will be going out to buy our products and they won’t even know why. I’m even more of a genius than I thought!
[end of dialog]
Victoria begins by clearing her throat. “To clear your throat” is to do this [clears throat)]. You are making a low sound, almost like a cough, to get rid of anything that's in your throat that would prevent you from being heard clearly. I clear my throat before I record often.
Victoria begins by saying, “Congratulations are in order.” “To congratulate (congratulate) someone” means to say they've done a good job, to give them your best wishes after they have accomplished something. Someone who wins a race or wins a competition will be congratulated by other people – “Good job!” “Congratulations!” “Congratulations are in order” is a phrase used when you are talking to a group of people, typically, and you want to congratulate one person. You want to announce some achievement or accomplishment by this person, and tell him what a good job he did.
Victoria says, “I just scored a product placement for our brand in the latest McQuillanator movie.” We learn immediately then that Victoria is congratulating herself or telling other people to congratulate her because she's accomplished something. We don't normally ask other people to congratulate us, but Victoria does. This is Hollywood, after all.
She says “I just scored a product placement.” “To score” here means to get or to obtain something that is very good. “I scored us two tickets to the Bruce Springsteen concert.” I was able to get, I was able to buy, I was able to obtain, two tickets. “Product placement” is when a company's product appears usually in a television show or a movie. So, if you're watching a TV show like “Friends” or “24,” and you see somebody drinking a can of Coca-Cola, or drinking from a can of Coca-Cola, that would be an example of product placement. Usually the company pays to have its product in the movie or in the television program.
Victoria scored a product placement for our “brand,” she says. A “brand” (brand) is a type of product or related products that are sold under a single name. Coca-Cola is a brand name. It's the name of a group of products that are similar. Victoria scored a product placement for the company's brand in the latest McQuillanator movie. (And if you haven't seen the latest, the most recent, McQuillanator movie, I think you'll like it!) Victoria says “Thank you. Thank you very much.” She sort of making a joke. She's congratulating herself.
Gerard says, “Really? That’s great. Will it have a prominent place in the show?” “Prominent” means important or easily seen, easily noticed, so that people will see it easily. Victoria says, “Well, you know how these things are,” which means “you understand this kind of situation.” “Our logo goes by in the blink of an eye, but millions of people are going to see it.” A “logo” (logo) is a small image that represents the company. The expression “in the blink of an eye” means very quickly, almost without noticing it.
Victoria said the logo goes by “in the blink of an eye, but millions of people will see it.” Gerard says, “So, will the star be wearing our logo on his shirt or something?” He's asking if the main actor in this movie will be wearing something that has the logo of the company on his shirt. Victoria says, “Something like that,” meaning “Well not exactly, but something similar to that.” Gerard says “But not that,” meaning not that exact thing I just said, wearing the logo on his shirt. Victoria says, “No. It's a little more subtle than that.” “To be subtle” (subtle) means not obvious, not easily noticed, something that is there but you may have to look for it.
Victoria says, “The logo will be embedded into an important scene.” “To embed” (embed) means to put something inside of something else, almost to become part of it. The logo, then, will be embedded into an important scene, an important part of the movie. Gerard says, “But where are they going to see it?” Where are they going to see our logo, the thing that represents our company? Victoria says, “Is that really important? The important thing is that our brand will be associated with a major Hollywood movie.” “To be associated with” means to be connected to, to be related to. Their brand is going to be related or connected to a major, or very important, Hollywood movie. “What more could we ask for?” That question means “What could be better than this situation?” The idea of course, is nothing.
Gerard says, “Stop beating around the bush.” The expression “to beat (beat) around the bush (bush)” means to be very indirect in describing something or telling someone about something. You're trying to avoid saying exactly what you're talking about. “To beat around the bush” is always a bad thing. It's a negative way of describing what someone is doing in talking to you.
Gerard says, “Where in the movie will our logo appear?” In what part of the movie will we see our logo? Victoria replies, “All right. It will be on the bottom of the star’s shoes, on the sole, and the audience will be able to see it when he's running.” The bottom of your shoe is called the “sole (sole)” of your shoe. Of course, usually you can't see the bottom of someone's shoes. Victoria says that the logo will be on the sole of the shoe and people will see it when the star, the main character in the movie, is running with these shoes.
Gerard says, “Only if he's running in slow motion, but he won't be right?” “Slow motion” refers to playing a video recording at a slower speed so that it looks like the people are moving and talking very slowly – like our podcast English in slow motion. Gerard says, “But if it goes by that quickly, it will be more like subliminal advertising.” “Subliminal (subliminal) advertising” is advertising where the message only appears on the TV or movie screen very quickly, for less than a second. The idea is that people see the image, the message, and their brain captures it but they're not aware that they saw that message. That's called subliminal advertising.
Victoria says, “Exactly. I hadn't thought of it that way,” – in that manner – “but hordes of people will be going out to buy our products and they won't even know why.” Once again, the idea of subliminal advertising is that people get an idea, but they don't know where they saw it because they weren't consciously able to see the message or the image. Victoria is trying to make the best of a not very good situation by saying that “Oh yes. Our advertising will work and hordes of people will be going out to buy our products.”
“Hordes” means a large group of people, many people. Hordes is a word that you need to pronounce carefully. You need to have the “d” at the end of hordes otherwise you get the word “whores” which means something very different. It means a prostitute. And of course, you don't want to be talking about prostitutes when you mean a large group of people.
“I'm even more of a genius than I thought,” Victoria says. A “genius” (genius) is a very smart or intelligent person, someone who is smarter than the rest of us. In the twentieth century, we often talked about Einstein as being one of the geniuses of science. Victoria says that she is smarter then she even realized because she has created this subliminal advertising by putting the logo on the bottom of the star’s shoes.
Now let's listen to the dialog this time, at a normal speed.
[start of dialog]
Victoria: [clears her throat] Congratulations are in order. I just scored a product placement for our brand in the latest McQuillanator movie. Thank you, thank you very much.
Gerard: Really? That’s great! Will it have a prominent place in the movie?
Victoria: Well, you know how these things are. Our logo goes by in the blink of an eye, but millions of people are going to see it.
Gerard: So will the star be wearing our logo on his shirt or something?
Victoria: Something like that.
Gerard: But not that.
Victoria: No, it’s a little more subtle than that, but it’ll be embedded into an important scene.
Gerard: But where are they going to see it?
Victoria: Is that really important? The important thing is that our brand will be associated with a major Hollywood movie. What more could we ask for?
Gerard: Stop beating around the bush. Where in the movie will our logo appear?
Victoria: All right. It’ll be on the bottom of the star’s shoes, on the sole, and the audience will be able to see it when he’s running.
Gerard: Only if he’s running in slow motion, but he won’t be, right? If it goes by that quickly, it’ll be more like subliminal advertising.
Victoria: Exactly! I hadn’t thought of it that way, but hordes of people will be going out to buy our products and they won’t even know why. I’m even more of a genius than I thought!
[end of dialog]
Congratulations are in order for our wonderful scriptwriter, Dr. Lucy Tse. Congratulations Lucy, on another great script.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development
Glossary
to clear (one’s) throat – to make a low, deep sound, almost like a cough, to move the food or mucus (thick liquid) that is in one’s throat so that one’s voice will be clearer and easier to understand, and/or to get attention before one begins to speak
* The presenter cleared her throat nervously before she began speaking into the microphone.
congratulations are in order – a phrase used when someone has done something impressive or good and deserve recognition, appreciation, admiration, and praise from other people
* Did you hear that Ahmed just secured the company’s biggest deal ever? I think congratulations are in order!
to score – to get or obtain something that is very good or impressive, especially when it is difficult to do so
* How did you score front-row tickets for the concert?
product placement – the appearance of a company’s product in a television show or movie, intended to make people want to buy it, usually in exchange for a payment from that company
* Car makers pay a lot of money for product placement in action movies where they want the hero to drive their car.
brand – the name of a type of product or several related products sold by a particular company
* David always buys his favorite brand of cereal, but Yuki just buys whatever cereal is on sale.
prominent – famous and important; seen and noticed by many people
* What is that prominent building on the mountaintop?
logo – a small image that represents a company or organization
* We need to find a graphic designer who can create a new logo for our website, stationary, and business cards.
in the blink of an eye – very quickly, almost unnoticeably
* People who have a lot of money invested in the stock market can lose thousands of dollars in the blink of an eye.
subtle – very delicate, almost unnoticeable; not obvious
* This dessert is mostly chocolate, but it has a subtle flavor of cherries.
to be embedded – to be placed within something else, almost becoming a part of it
* How did those fossils become embedded in the rocks?
associated with – connected to; related to; thought about in connection with
* Street gangs are associated with drugs and violence.
to beat around the bush – to be very indirect, wanting to avoid saying something
* If you’re going to ask your boss for a raise, do it directly. Don’t waste her time by beating around the bush.
sole – the bottom of one’s shoe; the part of a shoe that touches the ground
* How do I get gum off the sole of my favorite shoes?
slow motion – referring to a video recording that is played very slowly so that one can see all the details
* The referees had to view the action in slow motion to determine whether a player had committed a foul.
subliminal advertising – messages that appear very quickly that encourage viewers or listeners to buy something without making those people aware of the message
* The company is considering flashing very quick images of its product on the screen as a form of subliminal advertising.
horde – many people; large groups of people
* If we offer free pizza, hodes of students will come to the meeting.
genius – a very smart or intelligent person, much smarter than others
* Albert Einstein was a genius in physics.
Comprehension Questions
1. What will be on the bottom of the star’s shoe?
a) A small image representing the company.
b) A photograph of the company’s products.
c) A popular advertising slogan.
2. Why does Gerard tell Victoria to “stop beating around the bush”?
a) Because he wants her to speak clearly and directly.
b) Because he wants her to stop being nervous.
c) Because he thinks she is bragging too much.
Answers at bottom.
What Else Does It Mean?
to score
The verb “to score,” in this podcast, means to get or obtain something that is very good or impressive, especially when it is difficult to do so: “It can be really hard to score a reservation at that popular restaurant.” The verb “to score” also means to make a point during a game: “How many points did Gerry score in the basketball game?” The phrase “to score points with (someone)” means to do something that another person will like, making that person want to do something nice in return: “Right before the big test, Samantha tried to score points with the teacher by bringing her cookies.” Finally, when talking about cooking, “to score” means to use a sharp knife to make shallow (not deep) cuts in the surface of a piece of meat so that flavors can get into it: “Score the steak and place it in soy sauce for about an hour.”
sole
In this podcast, the word “sole” means the bottom of one’s shoe, the part that touches the ground: “It’s time to replace these tennis shoes since they have holes in the sole.” A “sole” is also a type of white fish: “This sole would taste better with some lemon juice and pepper.” The word “sole” also means only or single: “Heather was the sole woman employed by the engineering firm.” Or, “The sole reason why we hired Jenna was because she was the owner’s daughter.” Finally, the word “sole” can mean belonging to only one person, not shared with anyone else: “As the journalist who wrote that article, I take sole responsibility for the contents and any mistakes it may contain.”
Culture Note
Movie Product Placement
Movies have “a long history of” (a lot of experience with) product placement, “dating back to” (from) the 1920s, when a “silent film” (a movie made without sound, before sound recordings were possible) called Wings included a product placement for Hershey’s chocolate.
The 1949 “classic” (very well known and admired by many people) film It’s a Wonderful Life had a product placement for National Geographic Magazine when a young boy who wanted to become an “explorer” (a person who travels to unknown places) was shown with the magazine.
The 1982 film E.T. had several examples of product placement. When the young boy wanted to “attract” (bring closer) the “alien” (a creature from another planet), he left a “trail” (long line) of Reese’s Pieces candies. Sales of the candies increased by 65% after the movie “appeared in theaters” (was first shown in movie theaters). In another scene, the alien became “drunk” (affected by alcohol) after drinking a can of Coors Beer.
The “James Bond films” (one of many films about a popular private detective) called GoldenEye (1995) and the Tomororw Never Dies (1997) contained “heavy” (a lot of) BMW product placement, with James Bond driving the “latest” (newest) car model.
The 2000 film Cast Away had extensive product placement for FedEx, with logos appearing in many scenes. Interestingly, FedEx did not pay for the product placement, but it did benefit from it when its “brand awareness” (people’s familiarity with a company’s products) increased internationally. The movie also had product placement for Wilson “volleyballs” (a white ball hit over a net by team members’ “wrists” (the body part connecting one’s hand and arm) and hands).
Comprehension Answers
1 -a
2 - a