= 0892
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 892: Preparing for a Busy Season.
This is English as a Second Language Podcast episode 892. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there today and become a Learning Guide member, where you’ll be able to, well, download the Learning Guide.
This episode is a dialogue between Yuko and Reza about getting ready for being busy at your work or whatever activity you do. Let’s get started.
[start of dialog]
Yuko: What’s all this?
Reza: We’re gearing up for the busy season. We don’t want to get caught with our pants down like we did last season.
Yuko: Last season, we had a unusual number of visitors because of the unseasonably warm weather. We can’t expect lightening to strike twice.
Reza: We have to prepare for every contingency. If we get a flood of visitors, we need to be able to handle the surge in traffic. These three months are our peak months anyway, so we should expect an upswing in business soon.
Yuko: But what if people don’t come in large numbers as you’re anticipating? All of these extra supplies will go to waste.
Reza: No, they won’t. Most of this stuff isn’t perishable, so we’ll just save it for the next time we get a rush of visitors. Or, maybe, I’ll just invite my buddies over at the end of the season and we’ll have a party.
Yuko: So when you said that we have to plan for every contingency, this was what you meant.
Reza: Exactly!
[end of dialog]
We begin with Yuko saying to Reza, “What's all this?” “All this” would mean there are a lot of things that you see and you want to know, in this case, what they are. Well, Reza says, “We’re gearing up for a busy season.” “To gear up for something” is an expression that means to prepare for something, to get ready for something. “To gear up for” would mean to prepare for some event, often something that will be difficult or that will require a lot of work. In this case, Reza says, “We’re gearing up for a busy season.” “Busy” means very occupied, lots of things to do. “Season” refers to a certain time of year, or a certain period when some particular activity happens. We have four seasons – fall, winter, spring and summer – but you could also have the baseball season, which is a period of time that lasts from early April to late October. We could talk about the Christmas season in December. So, season can mean any period of time.
Reza says they are gearing up for the busy season. “We don't want to get caught with our pants down like we did last season.” The expression “to get caught with your pants down” is a somewhat humorous, a somewhat funny expression that we use to mean to be found in an embarrassing situation, an uncomfortable situation that we weren't prepared for. If you can think of someone whose pants suddenly fall down to their ankles and you can, of course, well, see their underwear, this would be somewhat embarrassing. “To be caught with your pants down” means to be found in a situation that is embarrassing and that you weren’t prepared for.
Yuko says, “Last season, we had an unusual number of visitors because of the unseasonably warm weather.” Yuko is talking about “last season,” meaning last year or the last time they had a period related to this activity. And we’re not sure yet exactly what this activity is. Yuko says they had an unusual number of visitors because of the unseasonably warm weather. Something that is unseasonable is something that is not to be expected normally during that time of year. Typically, we’re talking about the weather. It's warmer than it is normally. It's unseasonably warm this Christmas time. Normally, it's colder, or it’s unseasonably cold in the summertime. Normally, it's warmer. So, when the weather is warmer or colder than it would normally be – if the temperature that is, were warmer or colder than it would normally be, we might call that “unseasonable weather.”
Yuko says they had unseasonably warm weather last season. She says, “We can't expect lightning to strike twice.” This is another old expression. “Lightning” is the electrical discharge that comes out of a cloud, a storm cloud. Usually with lightning, you have a loud sound called “thunder.” “To strike” just means here to hit. So, when we say “lightning strikes,” we mean lightning hits the ground or comes in contact with something on the ground, often a building or a tree or a pole. For some reason, it is believed, because lightning perhaps doesn't happen very often, that lightning will not hit the same place twice, at least in the same storm. So, what Yuko is saying in this expression, “We can expect lightning to strike twice,” is that this is a very unlikely event. It probably won't happen. The chances of it happening are very small, we might say.
Reza says, “We have to prepare for every contingency.” A “contingency” (contingency) is one of many possible events. You're not sure what's going to happen. It might rain today or it might be sunny. You have to be prepared for the contingency, the possibility, that it will rain. So, you bring an umbrella with you or you wear a raincoat. Reza says, “If we get a flood of visitors,” meaning if we get a lot of visitors, a lot of people coming to us, “we need to be able to handle the surge in traffic.” A “surge” (surge) is a sudden increase, a significant increase in something. “Traffic” (traffic) means, in this case, the number of people who are coming. We often talk about traffic related to cars and how crowded the roads are, but traffic can also mean, especially when talking about, for example, a store – it can mean the number of people who come in and out of the store. Reza says, “These three months are our peak months anyway, so we should expect an upswing in business soon.” The “peak” (peak) is the highest, in this case, the month where they get the most business, the most number of visitors. So, this is their peak month, or these three months are their “peak months,” their busiest months. Reza says, “We should expect an upswing in business soon.” An “upswing” (upswing) is an increase, a sudden increase, usually.
Yuko says, “But what if people don't come in large numbers as you’re anticipating?” “In large numbers” means a lot of them, a very high value, many. “Anticipate” means to expect, to predict, to believe that something will happen in the future. I anticipate I will meet a beautiful woman and fall in love and get married.
Wait a minute, I'm already married. I already met a beautiful woman and fell in love. Oh, isn’t that nice!
Well, Yuko is not talking about falling in love. She's talking about getting a large number of people that will come into wherever Yuko and Reza are working. Yuko says, “All of these extra supplies will go to waste.” “To go to waste” (waste) means not to be used, to be thrown out, to be put in the trash, to go to waste. Yuko is saying that, if we don't get a large number of people, then all of these extra supplies, all of these things that you bought, anticipating there would be a lot of people, will go to waste.
Reza says, “No, they won't. Most of this stuff isn't perishable.” “Perishable” (perishable) means it is likely to go bad. It is likely to spoil. It is likely that it won't be any good. Usually, this word is used when talking about food. If you have a gallon of milk and you put it out into the sun, eventually it will spoil. It will change in a way that you can no longer drink it. There are some foods that you can prepare in a certain way so that they will last a long time. Canned food, for example, could last months, even years in a can. You could still open it up and eat it. Perishable food is food that you cannot do that with, food that if you don't eat it in a day or two, or you don't keep it in, for example, the refrigerator, it will spoil. It will go bad.
Reza says that “Most of this stuff,” most of these things that he bought, “are not perishable. So, we’ll just save it for the next time we get a rush of visitors, or maybe,” he says, “I'll just invite my buddies,” my friends, “over at the end of the season and we’ll have a party.” Reza is suggesting that if they don't use all of these supplies, which appear to be food supplies, he will invite his friends over and they will eat them. Yuko says, “So, when you said that we have to plan for every contingency, this was what you meant?” Yuko is saying, “Oh, so, the possible situation that you were preparing for included not getting very many visitors and therefore having to have a party in order to eat all of the supplies.” Reza says, “Exactly,” meaning “Yes, that is exactly what I was thinking.”
Now let’s listen to the dialogue this time at a normal speed.
[start of dialog]
Yuko: What’s all this?
Reza: We’re gearing up for the busy season. We don’t want to get caught with our pants down like we did last season.
Yuko: Last season, we had a unusual number of visitors because of the unseasonably warm weather. We can’t expect lightening to strike twice.
Reza: We have to prepare for every contingency. If we get a flood of visitors, we need to be able to handle the surge in traffic. These three months are our peak months anyway, so we should expect an upswing in business soon.
Yuko: But what if people don’t come in large numbers as you’re anticipating? All of these extra supplies will go to waste.
Reza: No, they won’t. Most of this stuff isn’t perishable, so we’ll just save it for the next time we get a rush of visitors. Or, maybe, I’ll just invite my buddies over at the end of the season and we’ll have a party.
Yuko: So when you said that we have to plan for every contingency, this was what you meant.
Reza: Exactly!
[end of dialog]
She writes scripts in large numbers and all of them good. I speak of course, of our wonderful, own scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Comeback and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to gear up for – to get ready for; to prepare for
* The team members are gearing up for the big game on Friday.
busy season – a period of time each year when a business has more customers and more sales than at other times of year
* Early spring is the busy season for tax accountants, because most personal tax returns have to be filed by April 15.
to get caught with (one’s) pants down – to be found in an embarrassing or uncomfortable situation that one was not expecting and did not prepare for
* The students got caught with their pants down when the teacher surprised them with a test on their reading assignments up to that point in the term.
unseasonably warm – warmer than usual for a particular place at a particular time of year
* February was unseasonably warm in Colorado and it caused a lot of flooding.
for lightening to strike twice – for a rare or unusual event to happen two times; for something unlikely to happen again
* Why are you still buying lottery tickets? You won the jackpot last year, but I doubt lightning will strike twice.
contingency – one of many possible events when one does not know whether or when it will happen, but one can try to be prepared for it
* Does your homeowners insurance include contingencies for natural disasters, such as flooding, wildfires, and earthquakes?
a flood of – many; a large number of people or things appearing all at once
* The school was overwhelmed by the flood of new students last year.
surge – a sudden, significant increase
* After the terrorist attacks, there was a surge of interest in becoming a police officer.
traffic – a measure of the number of people coming to a store or another place; a measure of the number of people seen in a particular area
* Our store doesn’t see much traffic, but our website gets a lot of sales.
peak – greatest; biggest; with the maximum value; referring to the highest part of something
* None of the employees are allowed to take their lunch break during our peak hours, because we need everyone available to assist customers.
upswing – an increase
* What caused the upswing in students’ test scores three years ago?
in large numbers – with a great or high value; many
* When a storm is coming, people often buy flashlights and candles in large numbers, just in case they lose power.
to anticipate – to expect; to predict; to believe that something will happen in the future
* As the population grows older, we anticipate continued growth in the medical industry.
to go to waste – to be wasted; to not be used and to have to be thrown away
* Many grocery stores donate old bread, fruits, and vegetables to homeless shelters so that the food doesn’t go to waste.
perishable – likely to decay or spoil; likely to go bad
* Liquid milk is highly perishable, unless it has special packaging.
Comprehension Questions
1. What happened last season?
a) They weren’t prepared for so many visitors.
b) They didn’t have enough clothes, so visitors saw Reza naked.
c) They didn’t have doors for the bathrooms, so there was no privacy.
2. Why does Yuko say, “We can’t expect lightening to strike twice”?
a) Because she doesn’t think there will be another lightening storm.
b) Because she doesn’t think there will be as many visitors this year.
c) Because she doesn’t think they’ll have as much money as Reza is anticipating.
Answers at bottom.
What Else Does It Mean?
surge
The word “surge,” in this podcast, means a sudden, significant increase: “The government was surprised by the surge in applications for unemployment benefits.” Or, “Economists are predicting a surge in the cost of dairy products next summer.” Sometimes a “surge” refers to many people moving in a particular direction: “During the war, countries nearby had problems trying to accommodate the surge of people running away from the fighting.” A “surge” is also a sudden movement of a lot of electricity: “Storms can cause power surges.” A “surge protector” is a device used for plugging in computers and other valuable electronics so that they are not damaged by electrical surges: “Even if your computer is plugged into a surge protector, it’s still not a good idea to use it during a storm.”
to go to waste
In this podcast, the phrase “to go to waste” means to be wasted, or to not be used and to have to be thrown away: “Studies have shown that a very large percentage of fruits and vegetables purchased by American families go to waste without ever being eaten.” The phrase “to be a waste of (something)” is used to describe something that was not as useful or good as expected: “Going to that movie was a waste of time.” Or, “She spent more than $200 on that sweater, and it fell apart the first time she washed it. What a waste of money!” Finally, a “waste product” is something that a factory process makes, but has no useful value: “The factory used to produce a lot of nitrogen as a waste product of its other manufacturing processes, but now it sells it to local farmers.”
Culture Note
Seasonal Businesses
Many businesses are “seasonal,” with certain times of year when they are very busy, and other times of year when they have little work to do. A lot of seasonal businesses experience a surge in sales around certain holidays. For example, toy stores and “department stores” (stores that sell many types of clothing, shoes, accessories, and household goods) have a “busy season” (a busy period) in November and December, when many Americans purchase holiday gifts for their friends and family. The post office and “shipping services” (businesses that transport packages) have that same busy season, because many gifts and “holiday cards” (short notes with holiday wishes) are mailed across the country then.
Other seasonal businesses include stores that sell candy and flowers. Their busy times are the weeks and days before Valentine’s Day and Mother’s Day, when people are likely to send candy and flowers as gifts. There is also “a rush on” (high demand for) candy in the weeks before Halloween, when people buy candy to give to children who wear costumes and go “trick-or-treating” (knocking on doors to ask for candy as part of Halloween).
Accountants and “tax preparation firms” (business that help people “prepare” (fill out) and “file” (submit) their taxes are very busy in late winter and early spring. That is because most “tax returns” (documents submitted with one’s tax payments) are due on April 15.
“Travel agencies” (companies that help people plan trips and purchase tickets) have busy seasons during the times of year when most people like to travel. These seasons are often “over the holidays” (November through early January, from Thanksgiving through New Year’s Day) and during the summer, when families can travel because their children are “out of school” (when school is not in session).
Comprehension Answers
1 - a
2 - b