= 1360
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 55.
This is English as a Second Language Podcast’s English Café episode 55. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about genealogy – studying where you come from, who your ancestors were, who your grandparents and great-grandparents and great-great-grandparents were. We’re also going to talk about a very popular, well-known comedian and actor in the United States, at least in the twentieth century, a man by the name of Bill Cosby. And, as always, we’ll answer a few of your questions. Let's get started.
Our first topic on the Café is genealogy. “Genealogy” (genealogy) is the study of your family and where your family came from, in terms of your relatives. A “relative” is someone who has somewhat a genetic connection to you. Usually a relative is what we would call a “blood relative.” A “blood relative” is someone who is, as I say, genetically connected somehow to you. You could also have a relative who is not a blood relative, however – you could have someone who is a relative by marriage. So, if my sister marries someone else, that person is my relative, even though he's not a blood relative. He's a relative “by marriage,” we might say.
“Genealogy” studies your relatives – specifically, your relatives that came before you. So, you would study, or find out more about, not just your parents, but your grandparents and your great-grandparents. Notice, in English we add the word “great” before grandparents for each generation that you go back. So, my parents’ parents were my grandparents. Their parents are my great-grandparents. Their parents are my great-great-grandparents, and so forth. You just keep adding “greats” onto the word.
When you are using words like “uncle,” “aunt,” “niece,” and “nephew,” you also use the system of adding greats, but you don't use the word “grand.” “Grandfather,” “grandmother,” “grandparent” are only used for the parents of your parents. After the grandparents, then you have the great-grandparents. But if you have an uncle, for example, you have an uncle who is the uncle of your father, that would be your great-uncle. There's no “grand.” So my father's uncle is my great-uncle, and my great-uncle’s uncle is my great-great-uncle. So, it's the same system, but there is no use of the word “grand” as there is for grandparents.
“Genealogy” is a study of your grandparents and your great-great-great-great-great-great-great-grandparents. The study of genealogy became quite popular in the United States in the 1970s. Part of the reason is that there was a television program in the 1970s that was very popular. It was called Roots (roots). Roots was what is called a “miniseries,” where you have a television show that is on for more than one night. It's like a long movie that is divided up into three or four, maybe five days. It's not a complete television series that would go for 20 weeks or 30 weeks. It's a shorter television series. As I say, it's almost like a movie that has been divided up into different parts.
Roots was an incredibly popular, a very popular, miniseries. It was based on a book by the same name by a man named Alex Haley. In the story, the man is trying to find his relatives. However, this is an African American, a black man, who is trying to go back and see who his relatives were, including those who were slaves. You recall that African Americans – now called African Americans – came originally as slaves, most of them from Africa, back in the early centuries of American history up through the nineteenth century, the middle of the nineteenth century.
The name of the miniseries Roots can refer to a couple of different things. We use the word “roots” when describing the part of the tree or a plant that is below ground, that is in the earth. We also can use this word to talk about your family tree – where people came from in your family. And so, sometimes people talk about searching for their roots. They talking about “tracing their family tree.” “To trace” (trace) means to research, to investigate. If you think of your family as being like a tree where you have two original parents, I guess, and then they have children and they have children, they’re like parts of a tree – like branches of a tree.
We use this expression “to trace your family tree” to refer to someone who is investigating their genealogy – where their parents and grandparents came from. In the story Roots, we follow the family tree of the hero of the story, the main character in the story. The United States, you probably know, is a country of immigrants for the most part. Most people here have come from another country. Perhaps for that reason, knowing where you came from is so important. All of us seem to have a need to know where we’re from, because where we're from is part of our identity. It's in some ways part of who we are.
That's why some children, when they are adopted by new parents, when they grow up they want to find their biological parents. They want to know where they come from. This is a very common feeling, and I think it explains in part why genealogy has been so popular in the United States. People want to know where their relatives came from. The general term we use to refer to your older relatives that came before your generation would be “ancestor” (ancestor).
When you're talking about your ancestors, you're talking about your grandparents, your great-grandparents, and so forth. The sense of identity is very important for many Americans as it relates to their family tree. Many Americans refer to themselves by the country where their ancestors came from. In my family, we talk about being Irish American because my relatives, my ancestors, came originally from, for the most part, the country of Ireland. The term we use sometimes is “hyphenated Americans.” A “hyphen” (hyphen) is that little line that you see in between two words that are connected.
So, when you see “Irish-American,” you'll often see a hyphen in between the words “Irish” and “American.” Hyphenated Americans are Americans who identify themselves as being from another place as well. You could be French-American, you could be Mexican-American, and so forth. My father was very interested in genealogy. Beginning in the 1970s, we as a family spent a lot of time, when we were traveling in the United States, looking up – or trying to trace – our family tree. I remember going on vacations, and whenever we went on vacation (this is a true story) we would often go to the cemetery.
Now, a “cemetery” (cemetery) is a place where you put bodies, dead bodies. We would go to the cemeteries not because we wanted to look at dead bodies, but because cemeteries have information on something called a “tombstone.” A “tomb (tomb) stone” has information carved into it: the person's name, when they were born, and when they died. The word “tomb” is used to describe the place where you put a dead body.
Well, we would travel from place to place in different cities, and if my father thought that perhaps there were some McQuillan relatives in that area, we would go to the local cemetery and look for McQuillans. This is absolutely true. I actually did this when I was growing up. People would say, “Where did you go on vacation?” I’d say, “Oh, we went to a cemetery.”
When you're tracing your family tree, you usually look for what are called “vital records.” Instead of going to cemeteries, you can also go to government offices and look up vital records. (We did that too, by the way.) “Vital (vital) records” refers to official government documents related to your life. When you're born in the United States, you have to get a birth certificate. You have to register the birth with the government. That's one of your vital records.
When you die, there's something called a “death certificate.” That is an official government record. You can go and look this information up to find out when someone was born and when they died. When you get married, you have a marriage certificate. You have to go to the government and register, or record, your marriage. So, being born, getting married, and then dying (and after you get married it's kind of like dying). These are three areas that you would have vital records for, with the government.
Now, these records are typically kept by the local government. They’re not kept by the state government. So, every city or every county, which is a smaller area within a single state, has its own records. Usually these are kept at the county government offices. So, if you want to find out where I was born, you would have to go to the Ramsey County Public Records office, because that's where I was born. I was born in Ramsey County. If you want to find out about my marriage, you would have to go to the Los Angeles County Public Records, because I was married in Los Angeles County.
When I retire and I move to Hawaii, you'll have to go to the, I don't know, Oahu County Public Records, where you will find my death records. I'm just predicting, of course, that that's where I'll die. Hawaii’s a pretty good place to live, so why not die there. These are things that you would look at, then, when tracing your family tree – these vital records.
One group in the United States that has always been very interested in genealogy is the Mormon Church. The “Mormons” (Mormons) are a religious group very popular in the state of Utah. Utah is in the western part of the United States. In the Mormon religion, which is also called The Church of Jesus Christ Latter Day Saints, knowing who your ancestors were is very important for religious reasons. For this reason, the Mormon Church has some very good sources of information for records. Anyone who does genealogy or traces their family tree is probably familiar with the Mormons and their records when it comes to ancestors.
We’ll talk now not about our ancestors, but about a very famous American comedian – funny man. His name is Bill Cosby. Bill Cosby is a comedian. He started his career, he started his life of work in entertainment, as a comedian.
Originally, he was what we would call a “stand-up comedian.”A “stand-up (stand-up) comedian” is someone who stands up in front of a microphone and tells jokes. Usually, this is done in small bars called “comedy clubs.” Here in Los Angeles, there are lots of comedy clubs that have young comedians, stand-up comedians, trying to get rich and become famous as comedians. I've been to several comedy clubs here in Los Angeles. Stand-up comedians stand in front of a microphone and they tell a joke. “To tell a joke” means to speak the joke, say something funny.
Bill Cosby started as a stand-up comedian way back in the 1960s. And back in the 60s and 70s, it was common for comedians to have records, to have albums, recording their performances – recording their stand-up, we would call them, “routines” or “stand-up acts.” These were the performances that they gave. Bill Cosby had a very famous album which my older brothers owned and I remember listening to when I was a child in the 1970s. Bill Cosby became very famous for his comedy albums. Steve Martin is another comedian who became famous for his comedy albums.
A few years later, Cosby also had a cartoon series in the 1970s. Many people know his voice from the cartoons, and I certainly grew up with those cartoons as well. Bill Cosby's cartoon series was called Fat Albert and the Cosby Kids. It was actually supposed to be an educational cartoon, and that's important because Bill Cosby himself was very interested in education. He was so interested in education that he went back and got a doctoral degree in education from one of the best universities in the country, Columbia University. So, he took his interest in education very serious.
Fat Albert and the Cosby Kids was a very popular cartoon series for children then, in the 1970s. Bill Cosby's voice was used for the voice of the main character in the cartoon, a young boy by the name of Albert, who was very large. He was very overweight and that's why he was called “Fat Albert.” “Hey, hey, hey! It’s Fat Albert.” That was the voice, roughly. Bill Cosby did a much better job.
Cosby became even more famous in the 1980s for a television show called, simply, The Cosby Show. He was the star of the show. The show was interesting because it was about an African American – a black – family that was in the upper class of American society. “Upper (upper) class (class)” refers to someone who is rich, someone who has a lot of money.
In The Cosby Show, we see an African American family that has money, that is in the upper class. Most African Americans in the United States are not in the upper class, so, it was interesting to see that situation on television. The television show was so popular, it lasted for eight years.
Interestingly enough, although I know a lot about Bill Cosby, I have never watched The Cosby Show. I wasn't watching television a lot when I was in college during the 1980s, and so I didn't really see the show very much when I was younger. Older people like me remember Bill Cosby more from his comedy albums of the 60s and 70s and, of course, the Fat Albert cartoon series. Bill Cosby continues to give speeches, to give presentations, and to give performances in comedy. He is a very smart and very interesting comedian who has certainly had an effect on American popular culture.
Now let’s answer a question or two that you have sent to us.
Our question today comes from Luan (Luan) in Vietnam. Luan wants to know the meaning of the expression “to get down on your knees.” Your “knees” (knees) are located in the middle of your leg. It’s what connects the lower leg with the upper leg. “To get down on your knees,” then, would be to go down on the ground with your knees on the ground and your feet and lower leg on the ground.
The verb that we would use more commonly here would be “kneel” (kneel). “Kneel,” of course, comes from the word “knee” or “knees.” “To kneel” means to put your knees on the ground. We often associate kneeling with certain religious practices. In certain Christian churches, for example, kneeling is very common. The expression “Get down on your knees” is often followed by “and pray” – and ask God for some favor or some benefit or some good thing in your life. I'm not sure what the context is of the sentence that Luan is talking about here, but that's one way of using it.
“To get down on your knees” could also be used to indicate that you are asking a person for a favor, almost as though that person were a god. “Get down on your knees and beg for your favor.” “To beg” means to ask someone almost desperately, to hope that they will say yes. There is a song from the 1960s by Simon and Garfunkel called “Cecelia,” and one of the lines of the song is, “I'm down on my knees, I’m begging you please to come home. Come on home.” The person singing the song is down on his knees begging her – asking her, please – to come home. I guess Cecelia left the house for some reason.
There's a related expression here, which is “to get down on one knee.” This is a very different expression. “To get down on one knee” is to ask a woman to marry you. That's the traditional use of the expression. Why get down on one knee? Well, because, again, traditionally when a man proposed to a woman, when a man asked the woman to marry him, he would kneel in front of her on one knee. Not on both knees, since that has more of a religious significance, but on one knee.
That is what many American men, and probably men in other countries, have done when they have asked the woman they want to marry to marry them. Traditionally, a man gets down on one knee. He puts one knee on the ground and takes out a ring – a small, round, usually gold piece of jewelry that has a diamond on it – and asks the woman to marry him. And then, of course, the woman says, “Eeeh, I’ll think about it.”
You don't need to think about it. You can email us if you have a question. I'm not asking you to marry me, but if you have a question, I'm happy to answer it if we have time. Email us at eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
blood relative – someone who is related to you because they were born into your family, rather than to be related by marriage
* Sandy and Douglas grew up together in Houston, but I’m not sure if they are blood relatives.
miniseries – a television drama show that is shown in several parts
* Do you know how if this miniseries is has four or five episodes?
ancestor – a family relation from the past, usually those who are older than your grandparents
* She used to tell all of her friends that one of her ancestors was a king of Norway, but I don’t think anyone believed her.
to trace (one’s) family tree – to find out who one’s family relations are, from the past and present
* We both have the same last name but we’ll have to trace our family trees to know if we’re related at all.
hyphenated American – Americans whose family comes from another country or a specific cultural group
* It’s not uncommon for many proud Americans to identify themselves as hyphenated Americans and to recognize their heritage.
cemetery – graveyard; a place where dead people are buried
* Each time we drove by this cemetery when I was young, my older brother would tell me ghost stories to try to scare me.
birth certificate – an official document that records someone’s birth
* He was in shock when he saw on his birth certificate that his mother was only 17 when he was born.
Mormon – a member of the Mormon church, a religious group begun in the United States in the 19th century
* The official name for the Mormon church is the Church of Jesus Christ of the Latter-day Saints.
stand-up comedian – a person who tries to make people laugh by telling jokes in front of an audience
* Eddie took a year off from school to try to make it as a stand-up comedian.
to tell a joke – to say something that is intended to make people laugh
* He wanted to tell a joke at the beginning of his presentation, but I tried to convince him that it wasn’t a good idea at a serious meeting like this one.
album – a round, flat disk that has a collection of sound recordings
* We went to the used records store and bought some great old albums.
cartoon – a TV show or movie that is made with drawings, rather than real people
* After school, my brother always wanted to watch cartoons instead of doing his homework, but my mother never let him.
upper-class – the group of people in a society with the a lot of money and high status
* The principal of that private school told me that all of the upper-class families in town sent their children there, but that didn’t impress me.
to get down on (one’s) knees – to beg; to ask someone for something; to ask for forgiveness
* If you want Olivia to forgive you, you’ll have to get down on your knees to tell her how sorry you are.
to get down on one knee – to kneel; to ask someone to marry him or her
* Gina couldn’t believe it when her boyfriend got down on one knee in the middle of crowded restaurant to ask her to marry him.
What Insiders Know
“There’s a black sheep in every family.”
The expression, “black sheep,” is commonly used to describe a member of a family who is a “disgrace,” or who does bad things or is a failure. If there is someone in your family who has been in trouble with the police or who gambles and loses all his or her money, you may hear someone say of that person: “He (or she) is the black sheep of that family.”
The color black, in the U.S. and in other western societies, usually represents things that are bad or evil, while the color white is usually used for good or pure things. As you probably know, in old movies, the “villain,” or the bad person who causes trouble is traditionally dressed in black, while the “hero,” or the good person who saves others from the villain is dressed in white.
The color black is used in entertainment in other ways. If someone describes a movie as a “black comedy,” you know that it is a funny movie, but one that has a serious or tragic side. People can be “blacklisted,” which marks them as an undesirable person and they are not, for example, hired for a job or allowed to come into a place of business.
The word “black” has been used a lot to describe bad or sad events in history. In 1929, for example, the stock market in the U.S. “crashed,” or declined to a very low level very quickly. That day is now known as “Black Tuesday.”