= 1395
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Café number 90.
This is the English Café episode 90. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we're going to talk about a very popular event during the summertime, the county and state fair. We'll talk about what that is, and why they are so popular in many states in the U.S. We'll also talk about the person who created Spider-Man, a man by the name of Stan Lee. And as always, we'll answer a few of your questions. Let's get started!
If you haven't visited our website, you'll want to do that. Our web address is eslpod.com. Take a look at the Learning Guide for this episode, and check out our ESL Podcast Store, which has some additional premium courses you may be interested in.
Our first topic today is the state and county fair. A “fair” (fair) is when people come together and they are displaying or selling certain things. “To display” means to show; to let other people look at. You could have a book fair, where people would come and show their books and sell them.
When we talk about a state or county fair, however, we're talking about a very particular kind of event. Originally, in the past, these state fairs were related to the agriculture of a state. The “agriculture” (agriculture) refers to the animals and the plants that a particular state has, that people later eat. The animals are typically called “livestock” (livestock). “Livestock” are farm animals, animals that are on a farm such as a pig or a cow; those would be two examples of “livestock.”
The original state fairs were competitions. You would bring your pig or your cow and there would be some judges, and they would award the best pig or the best cow a prize. Usually it was what we call a “ribbon” (ribbon), which is just a little thing that you would give to the person to show that they had won. If you were the best, you usually got the “blue ribbon.” The “blue ribbon” was the “highest” prize, the best prize. But it wasn't money or, usually, anything that you received, it was just the recognition that they were saying you were the best. If you were second best, you would get the “red ribbon.” They also gave awards for people who made the best pie or some other food. State and county fairs still give away these prizes; they award these ribbons.
State fairs were very much related to the farms and the agriculture in a state. Later, they started adding other kinds of competitions and other kinds of entertainment; they would add rides for the children. A “ride” (ride) is usually a machine that you get into that goes very fast or goes up and down. Two examples would be a roller coaster, which is a bunch of cars on like a little train track, and it goes up and down. Another ride you might see at a fair is a Ferris wheel, and this is where you have a large wheel – round thing – that people get into little cars, we call them, little places where you can sit, and it goes – takes you all the way up and all the way back down so you go around in a circle.
I absolutely hate going on rides; I never really liked it as a child. I don't know, maybe something happened to me that I don't remember, but I'm not – I'm not a very good person to go with if you like going to the rides at a fair.
Now we have two different kinds of fairs in most U.S. states. One is called a “county fair,” and the other one is the “state fair.” Every, or almost every U.S. state is divided into smaller “regions,” smaller sections, and we call those “counties.” So for example, I live in Los Angeles – the city of Los Angeles. Los Angeles is in Los Angeles County, and they are many different counties in California. The only state that doesn't have counties has something that is really the same thing but they use a different name. That would be the state of Louisiana where they have parishes. But in most states we call these “counties,” and there's a county fair where they have competitions for the best pig and the best horse and the best pies, and they give awards to people who win. In many cases, those winners then go to the state fair, which is the fair for the entire state.
I don't know if every state has a state fair, but I think most of them probably do. The largest state fair in the United States, the one that is the longest and has the most people attending, would be the Minnesota State Fair. I am, as you may know, from Minnesota. It is the largest state fair probably because Minnesota is a very important state for agriculture in the United States. There are many plants that are grown in Minnesota, and there are many farm animals – a lot of livestock in Minnesota as well.
So, the Minnesota State Fair has always been a very big event; it is the biggest in the United States. It lasts for 12 days, so it is 12 days long. It's always at the end of August. There are probably about a million and a half people – 1.5 million people who go every year to the state fair. You have to understand that the population of Minnesota is only – for the entire state – about 5 million, perhaps. So when 1.5 million go to the state fair, that's a very high percentage. It's a very, very popular event.
The fair is “held,” it is located, in a particular area in St. Paul called the “State Fairgrounds.” “Fairgrounds” (fairgrounds – one word) are the places where you have the fair. In big states, or states that have big state fairs, there's one place that you have it every year, and they have buildings and so forth.
The Minnesota State Fair is one that I grew up going to. When I was a child and a teenager, I would always go to the state fair. My family lived only about a mile from the State Fairgrounds, so I could walk to the fair, and usually we would go two or three times to go on the rides, or for me, to watch other people go on the rides. It was always a lot of fun; there were lots of competitions, there were concerts and other kinds of entertainment. And of course, you could see the animals that won the prizes and so forth.
My favorite part of the State Fair was going on the machines – the big, what we would call, “tractors” that they use on a farm. A “tractor” (tractor) is a big machine that a farmer uses on the farm. I would love going and sitting in the seat of the big tractor. That was always a popular part of the state fair. So, if you are in Minnesota at the end of August, you can go to the Minnesota State Fair.
Most of the state fairs are at the end of the summer. Sometime they're in different parts of the year, but usually it's at the end of the summer or the early part of the fall. If you ever have a chance to go to a county or state fair here in the U.S., I think you would find it very interesting.
Our next topic is also very interesting, I think. It's about Stan Lee. Stan Lee is the person who created many famous comic book characters. A “comic book” is a book of drawings that has a story in it. Usually in the U.S., comic books are read by children and maybe teenagers. There are not a lot of very sophisticated comics; they exist, but the most popular ones are for children. In other countries, comic books are popular with adults and children. In the U.S. they're much less popular with adults, although there are some adults who read comic books.
The most, or one of the most famous comic book characters is the super hero Spider-Man. A “super hero” is an imaginary character, in the comic book, that is very strong or has some sort of special power. Spider-Man, you may know the story, is about a boy – a college student, who has special powers. He can be like a spider and he can catch people who are doing things wrong.
There is a new Spider-Man movie, which is now in the theaters in the United States – very popular. Well, the person who “created,” who started Spiderman and many other super heroes in the comic books is Stan Lee. Stan Lee was born in New York City. His actual last name was Stan Lieber (Lieber), but he changed it to Stan Lee.
He started with a very small publishing company, what we would call a “publishing house,” just like the house you live in. A “publishing house” is a company that makes books, in this case, comic books. There were other comic book companies when Stan Lee started his Marvel Comics, that's the name of his comic book company – Marvel (Marvel). “To marvel,” as a verb, means to look at something and be very impressed; to say, “Wow, that was wonderful!” “I marveled at the beautiful painting” – I looked at it and said it was great; it was wonderful. “Marvel” is the name, also, of Stan Lee's company, Marvel Comics. We have another word, “marvelous,” which means wonderful.
Lee had other people who were making his comics; of course, he didn't draw them all himself. And eventually, his publishing house created many popular super heroes. You may have seen movies with the X-Men, that was also created by Stan Lee and his company, and there are many others.
The other popular company that makes comic books in the United States, in addition to Marvel Comics, is called “DC Comics” (capital D, capital C). Superman, for example, is made by DC Comics. Stan Lee's super heroes – his comic book characters – are a little different from the typical characters that you will find in the other company – in DC Comics. They tend to be super heroes that have problems, that have difficulties, that sometimes make jokes. So, I think the Stan Lee characters are more interesting than, for example, Superman. Maybe someday I'll create a super hero for myself; we'll call it “ESL Podman”!
Now let's answer a few of your questions.
Our first question comes from Joseph (Joseph), originally from Slovakia but now living in Japan. Joseph wants to know when we use the expression “Mrs.,” “Miss,” and “Ms.” (Ms-period). Well, let's also include here “Mr.,” which is M-r-period.
“Mr.” can be used for any man who is either married or single, so any man can be called “Mr.” “Mrs.” (Mrs-period) is for a woman who is married. “Miss” (Miss – no period) is for a woman who is not married, an “unmarried” woman we would say. “Ms.” (Ms-period) is for any woman. Just like “Mr.” is for any man, married or unmarried, “Ms.” can be used for any woman, married or single.
“Miss” and “Mrs.” are not as popular anymore, especially in the business world. Usually you will just see “Ms,” but you will still read or hear the words “Mrs.” and “Miss,” especially in normal conversation or in a novel.
Felipe (Felipe) from Brazil wants to know what the expression “love in bloom” (bloom) means.
The expression “in bloom” is used to describe a flower, such as a rose, that is open and is at its most beautiful. So when we say, “the flowers are in bloom,” we mean they are open; you can see them. So, “love in bloom,” or, “love is in bloom,” means that there is a lot of romantic love in this area or in this situation. If you see many different couples walking down the street holding hands, you might say, “Love is in bloom,” there's a lot of romantic love here.
Our final question comes from Franfou (Franfou) in Canada. The question has to do with the meaning of the expression “in order (order) to (to).”
“In order to” means for the purpose of doing something. When you have a certain objective, something that you want to happen, we use this expression “in order to.” For example: “I go to the gym every day and exercise in order to lose weight” – to not be so fat. I do it “in order to lose weight”; that's the reason I'm doing it. Sometimes you will just hear people say, “to,” instead of “in order to”: “Why do I go to the gym? I go to the gym to lose weight.” I could also say, “in order to lose weight,” it means the same thing here.
In order to ask a question, you can email us. Our email address is eslpod@eslpod.com. Remember to send that to my new super hero, ESL Podman!
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on the English Café.
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
fair – an event (usually for a few days) where there are “rides” (see below), games, food, and agricultural, sewing, and cooking competitions, mostly for rural communities
* Asa’s cow won first place at the state fair last summer.
to display – to show something; to make something available for other people to look at to get information or to judge
* At the conference, each company had a table to display their new products.
agriculture – farming; the work of growing plants and raising animals for food
* Agriculture is an important part of Idaho’s economy, because people grow a lot of potatoes and corn there.
livestock – animals that are grown on a farm, usually for food or “wool” (the hair that grows on some animals, like sheep)
* Livestock on most farms includes horses, cows, pigs, goats, sheep, and chickens.
blue ribbon – the first-place award; the top award in a category
* Gertie won the blue ribbon for her delicious strawberry jam.
ride – a big machine that people ride on at fairs or amusement parks because it is fun and exciting; a big machine that people sit on while it moves very quickly in different directions
* My favorite ride at Disneyland is “Space Mountain.”
Ferris wheel – a popular ride at fairs; a large wheel with many seats on the outside that turns in a circle slowly so that people sitting in a seat are taken up into the air and then brought back down again and again
* There’s a fantastic view from the top of the Ferris wheel, but if you’re afraid of heights, you probably won’t like the ride.
county – local government in the U.S. that is smaller than a state but larger than a city
* How many counties are there in Nebraska?
to be held at (somewhere) – to be at a certain place; to be planned to happen at a place
* The wedding will be held this afternoon at St. Matthew’s Church.
fairgrounds – a large area outdoor area where state and county fairs are held
* The fairgrounds in our state have three barns and two stages for musical performances.
tractor – a vehicle that is very strong and has big wheels, usually used to push or pull heavy equipment and other things on farms
* A tractor doesn’t move very fast, but it is very powerful.
comic book – a small book or magazine that tells an interesting story with little text and a lot of colored drawings
* How many Superman comic books do you have?
publishing house – a company that publishes books or magazines; a company that edits, prints, and distributes books or magazines
* Some of his favorite books are printed by Ajax Publishing House.
to marvel – to be in awe of something; to admire something; to be impressed by something that is very good, surprising, and interesting
* Everyone marveled at the men who first walked on the moon.
to be in bloom – to be blooming; to have many open flowers
* Washington, DC is beautiful when its cherry trees are in bloom.
in order to – to; to do something or to have something happen; to be able to do something or have something happen
* We woke up at 3:30 a.m. in order to get to the airport by 4:30 for our 6:30 flight.
What Insiders Know
Food at State and County Fairs
One of the reasons that people like to go to state and county fairs is to eat the food! Many different kinds of food are sold at “food booths” (outdoor tents or stands) and most of these foods can’t be found at restaurants and stores.
Common fair foods include “hot dogs,” long sausages put into long pieces of bread and eaten with ketchup and mustard, and “corn dogs,” which are hot dogs that have been covered in cornbread and fried on a stick. “Curly fries,” or fried and salted curled strips of potato, are also very popular.
For dessert, people often eat “caramel apples,” which are apples that are covered in a sweet, soft, brown candy, or “cotton candy,” which is colored sugar that looks like a ball of pink or blue cotton and is served on a stick. “Elephant ears,” or large pieces of fried bread that are covered in cinnamon and sugar, are also very tasty. And there are usually “frozen bananas,” which are bananas that are put on a stick, dipped in chocolate and nuts, and frozen.
Fairs also have traditional foods that represent the state or county’s agriculture. There are often many milk products, like cheese, yogurt and ice cream, “corn on the cob” (boiled corn eaten off of the long part of the plant that it grows on), and meats. Fairs in areas with German “heritage,” or cultural influence and history, often serve special sausages. And fairs in areas with Chinese heritage have “stir fry,” or lightly fried vegetables, meat, and noodles served with rice.
When you go to a fair, it’s a good idea to go on the rides first. Many people who eat a lot of foods at fairs and then go on rides may regret it!