= 1399
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Café number 94.
This is ESL Podcast's English Café episode 94. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California, and it is a beautiful day here in L.A. The sun is shining, temperature about 75 degrees Fahrenheit, and a clear sky.
On this Café, we're going to be talking about a famous American – famous American news anchor named Katie Couric. We're also going to be talking about payday loans, when people get loans when they need money in an emergency. We'll talk about what that is and what some of the problems with that are here in the U.S. And as always, we'll answer a few of your questions. Let's get started!
Remember to visit our website at eslpod.com, and download a Learning Guide for this episode. You can get all of the vocabulary words, definitions, sample sentences, additional definitions that we don't cover here on the audio part of our podcast, as well as cultural notes, and a complete transcript of this entire episode.
Our episode today is going to talk about a famous American news anchor. An “anchor” (anchor) here means the person who reads the news during the nightly newscast – the news broadcast. I talked about newscasts and news anchors back in English Café number 34, back in May of 2006. So, if you haven't listened to that Café, you might want to do so to get some more information about this topic.
I'm going to talk about one of the more famous newscasters – news anchors – on the evening newscast – the national evening newscast here in the U.S. Her name is Katie Couric. Katie Couric is the only woman news anchor – solo woman news anchor. She is the first solo woman news anchor on one of our more important national networks.
Katie Couric began on another very popular news show that most Americans know about, called The Today Show. The Today Show is a morning news program. It's also what we would call a “talk show,” a show where you have someone who interviews interesting guests, usually not very serious topics – sometimes.
Katie Couric became famous on the NBC – one of the national networks – on the NBC Today Show. Last year, she moved to another network, CBS, and she started working as the solo anchor on the evening news.
Many people know about Katie Couric; she was, and has been, ranked among the world's most influential people by Time magazine. “Ranked” means to put in order – “to rank” something. ESL Podcast is ranked the number one ESL podcast in the world – well, we hope!
Katie Couric is, and has been, ranked among the most influential people in the U.S.; she has a very pleasant manner about her. When we say someone has a “pleasant manner,” we mean that they seem nice, that they're friendly, that they're easy to get along with. Katie Couric has that sort of personality that people like, we would say that people find appealing. “To find something appealing” means that you like it; it's something that you want to have or, in this case, want to watch.
Katie Couric was paid a lot of money to become the anchor on the CBS Evening News. Her salary offer was around 15 million dollars a year. A “salary offer” is what a company says it will pay you before you take the job, and you say yes, you “accept” the offer. She accepted the offer.
Some people have criticized Katie Couric because they don't think she has enough experience working as a newscaster. When she worked on The Today Show, many of the what they would call “segments” of the show – a “segment” is a part of a TV show – many of the segments of the shows that she was on were not very serious news. So, she's been criticized. She does have, however, experience as a journalist; she worked for the Atlanta newspaper, The Atlanta Journal Constitution. She also worked for one of the most famous news services in the U.S., called the “United Press International,” or “UPI.” She does, however, have experience with hard news – “hard news” would be serious news – and many people think she has the credentials to become the sole anchor.
The “credentials” here means the experience – she has the background to do what she is doing. We often use the word “credentials” when we are talking about a license or an educational degree. For example, to become a teacher in most U.S. states, you need to get a teaching credential; you have to go to school and get a license to teach in the public schools in the U.S. Here, “credentials” means mostly the background, the experience, the education of Katie Couric.
Unfortunately for CBS News, they have not been able to take advantage of Katie Couric's talents; at least they have not been able to get more people to watch their newscast. One of the problems with newscasts in the U.S. is that many younger people – people in their teens, 20s, 30s – do not like to watch the television news; they get their news from the Internet. So, the number of people watching the newscast – the news broadcast – has decreased in the last several years. So, we'll see if Katie Couric can turn that around. When we say we “turn something around,” we mean we change it. If it's getting worse, we change it so it's getting better; that's the idea of “turning something around” – making it better.
Our second topic is about payday loans. “Payday” (payday – one word) is, you may guess, the day that you get paid from your company where you work. However, there are many poor Americans who need money before they get paid, and so they take out – they get – they take out a loan. We use the verb “to take out” to mean to get. As a noun, “take out” means something different; it means going to a restaurant, buying food, and then bringing it home to eat, what in British English is called “take away.” But, as a verb, “to take out,” when we are talking about a loan, means to get a loan.
Now, what happens is people who need money, but have what we would call “bad credit,” go to one of these places that gives loans. People with “bad credit” are people who have problems paying their bills; they may have been late in paying their credit card bills; they may have had problems with a house or a car, not paying their loan correctly on time. These are people with “bad credit.”
Well, a bank does not want to lend – give money – to someone with bad credit, so there are new companies that have what we would call “storefront offices” that will lend money to people with bad credit. A “storefront office” is like a store in a mall where you would go; it's not a separate building, it's usually part of a number of other stores. These are places where you can walk in and get a loan, usually a short-term loan. The typical payday loan is a two-week or four-week loan.
The reason these new companies – these storefront payday loan companies – will lend you money is because you are promising them – you are giving them permission to take and sell something that is yours if you don't pay back the loan. We call this “collateral.” When you take out a loan, the bank or whoever is giving you the money will often ask for collateral (collateral). “Collateral” is like an insurance policy for the bank. If you have a house and you want money, you can borrow against your house – using your house as collateral. So, if you don't pay the loan back, the bank can come and take your house. “To borrow against something” means to use a car, a house, something valuable as collateral – as something that you will give the bank or the company if you don't pay your loan back.
The problem with these payday loans is that they have a very high interest rate – extremely high interest rate. The “interest rate” is what the company charges you; it's the price you pay for the loan.
These loans are small, usually less than $1,000, sometimes as little as 100 or $200, and therefore, a short time – what we would call a “short-term” (term). “Term” is just another word, in this case, for time, so a two-week time period – a two-week term. Even though they are short-term, they can have very high interest rates. In fact, the interest rate can be as high as 300 to 800% if you consider it by the year. So for example, you could take out a $100 loan, and in two weeks time, you have to pay the loan back plus, say, $20. Well, that's a 20% loan – a 20% interest rate for just two weeks.
But, if you aren't able to pay the loan back in two weeks, the amount you will have to pay will keep increasing – $40 in one-month, $80 in two months, and so forth. If you keep adding that $20 every two weeks, you will end up with a very high interest rate. By comparison, if you have a credit card – a Visa or a MasterCard – you'll probably be paying 18 to 20% a year on the money that you get from your credit card. These companies are charging interest rates of up to 800%, so it's a very big difference.
Many people have said that it should be illegal to charge such high interest; some people have called it “predatory.” The adjective “predatory” (predatory) comes from “predator.” A “predator” is someone who – or some animal that feeds on – that eats other animals. But we use the term more generally to mean someone who takes advantage of another person. “To take advantage of” means to use your power over someone to do something, often, not very nice. That would be a “predator.” So, “predatory lending practices,” when these companies charge so much interest, have been criticized by many people.
Unfortunately, for many poor Americans, this is the only way for them to get emergency money. If they need money before their next payday, they often have to take these payday loans – these short-term loans – from these companies because they don't have good credit, and they won't find a bank that will lend them the money.
Now let's answer a few of your questions.
Our first question comes from Pedro (Pedro) in Brazil. Pedro wants to know how to pronounce the word l-i-s-t-e-n. We pronounce this “listen.” Now, Pedro's question has to do with the “t” – why don't we pronounce the “t” in listen. Why isn't it not “lis-ten”?
Well, there is no easy answer to that question. You just have to realize that many words in English have what we may call a silent “t”; for example c-a-s-t-l-e is “castle,” not “cas-tle.” There are some words where you may hear the “t” being pronounced when it is said very slowly, but not when it is said in normal conversation. “Listen,” however, is never one of those cases. Similar words would be “fasten,” “soften,” and “mortgage,” at least in U.S. English pronunciation.
Moving over to Iran, Ladan (Ladan) wants to know the meaning of the term “godmother” and “godfather.” He also wants to know what a “stepson” and “half-brother” are.
Let's start with the terms “godmother” and “godfather.” These are words that are used among Christians – people who are a member of a Christian religion. When a child is born, in most Christian churches, he or she enters the church – is made a member of their church – through something called “baptism,” which involves putting water on the child, usually over their head.
A “godmother” and “godfather” are what we would call “sponsors.” They are, basically, additional parents, sort of like religious parents to the baby. So, in case something happens to his real parents – his real mother and father – the godmother and godfather are responsible for bringing up child in terms of their religious education. They're responsible for helping the child get a religious – Christian, in this case – education and formation. Most often, of course, the parents don't die, and so the godparents are usually just there for the day of the baptism.
It's considered an honor to be asked to be a godparent. Godparents are often good friends of the family; they could be other relatives, other brothers and sisters; they could be neighbors. That's the meaning of “godfather” and “godmother.”
A stepbrother is somewhat different. A “stepbrother” or “stepsister” is when you have two people whose parents get married. So for example, you have a man and women get married and they have a son, and then the man, the husband, dies in an accident. The woman marries again to a man who already has a son. The two sons would be stepbrothers. They don’t have any biological parents in common (they have different mothers and fathers), but they are related to each other because their mother or father is married to the mother or father of the other boy. The father – the second husband – would then call his wife’s son his stepson, and if it were a girl, it would be a stepdaughter. Similarly, the woman would call her second husband’s son her stepson.
Now it gets more complicated. Let’s say that this new couple – the woman and her second husband – have a third child together, another son. This third child would be the half-brother to the other two boys, because he shares one biological parent with each. So, stepbrothers and stepsisters are related only through marriage, because one of their parents has married again to someone who already had a son or daughter. Half-brothers and half-sisters share either a biological mother or father.
Ladan also wants to know what happens when parents adopt a child, who is not from either of them, what that child is called. We would refer to that child as the “adoptive child”; the parent would be the “adoptive parent.” The biological parents would be called the “birth parents.”
If you have a question for the English Café, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to rank – to put something in a list by its importance, size, age, or something else
* Please rank these issues from one to five in order of their importance to our country: education, employment, health, environment, and peace.
to find (something) appealing – to think that something is nice; to be attracted by something; to like something
* I find your offer very appealing, but I need to speak with my wife about it before I give you a final answer.
salary offer – the amount of money that a company offers to pay a person to begin working there
* Jake was disappointed by the salary offer, because it was $10,000 less than he was hoping for.
credentials – qualifications; the education, experience, skills, and other things that make one a good candidate for a job
* Henrietta has impressive academic credentials, but she has only one year of professional work experience.
hard news – information about serious and important things that are happening in the local community or in the world
* Are you interested in hard news, or do you prefer to read about the lives of people in Hollywood?
to turn (something) around – to improve something; to make something better; to take control of something that is doing poorly and help it do better
* When Yemeni became president, he turned the company around and now it’s making more money than ever before.
payday – the day when one is paid for one’s work
* I spent a lot of money this week and now I have only $86 until my next payday.
to take out a loan – to borrow money from a bank; to be given money temporarily by a bank, with an agreement to pay the money back with interest
* Shawna took out a $30,000 loan to pay for her graduate education.
bad credit – not being trusted by other companies and banks to pay back money because one hasn’t paid back money as agreed upon in the past
* The Chenis family aren’t able to get a loan to buy a new home because they have bad credit.
short-term – for a short period of time; in the near future
* Her short-term goal is to finish medical school, and her long-term goal is to become the best heart surgeon in the country.
collateral – something that one promises to give to a bank if one cannot pay back a loan; something that one promises to give to a bank or another institution or person if one cannot pay back the money that one has borrowed
* They had to use their house as collateral when they asked for a loan to start a new business.
to borrow against (something) – to receive a loan by offering to give the bank something else if one cannot repay the money
* If you want a loan to open a second business, you can borrow against the value of your first business.
predatory – aggressive; using other people’s weakness for a financial advantage; using another person’s weakness to benefit financially
* Many credit card companies use predatory practices to get college students to use their credit cards.
godfather/mother – godparent; a person who participates in a Christian ceremony for a baby (baptism) and promises to take care of the child and teach him or her about the Christian religion and faith
* Vanessa was honored when her friend asked her to be his baby’s godmother.
stepbrother/sister – a son or daughter of the person your mother or father married, who is not related to you by blood; a son or daughter from another marriage
* After her mother died, her father married a woman with three children, so now Hermione has two stepbrothers and one stepsister.
half-brother/sister – a person who has the same mother or same father as oneself, but not both
* Joe’s father remarried after the divorce, and he and his new wife just had a child, who is Joe’s half-sister.
What Insiders Know
“Infotainment” and “Yellow Journalism”
When most people want to watch the news on TV, they usually look for “hard news,” or stories about important things that are happening in the world. However, many news programs have very little hard news, and instead are full of “infotainment” and/or “yellow journalism.”
“Infotainment” is a word made by combining the words “information” and “entertainment.” It refers to TV news programs that combine a little bit of hard news with a lot of “soft news,” or unimportant stories, like interviews with actors or singers. Other common infotainment stories are about shopping, travel, TV shows, or gardening “tips” (suggestions). Infotainment stories are chosen because they help the TV news program get a bigger audience. They don’t necessarily help people learn about the important things that are happening in the world.
“Yellow journalism” is “journalism” (reporting) that is “scandalous” and “sensational,” meaning that it exaggerates things in unethical or unprofessional ways to get more people interested. Yellow journalism originally referred to newspapers, but today the phrase can be used to refer to TV news, too. Yellow journalism is often seen in “tabloid newspapers,” which are small newspapers that have stories about the problems in the lives of famous actors and actresses, or stories about “aliens” (people from other worlds) or other strange things.
Infotainment doesn’t have very much hard news, but it is “harmless,” meaning that it doesn’t hurt anyone. On the other hand, yellow journalism is usually “offensive,” meaning that it hurts people’s feelings, and it can hurt people’s professional “reputations,” or the way that the public thinks about those people.