= 1102
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,102 – Discussing Capital Punishment.
This is English as a Second Language Podcast episode 1,102. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download a Learning Guide for this episode that will give you a complete transcript of everything we say.
On this episode, we’re going to talk about capital punishment – when the government kills someone for committing a crime. Sounds happy. Let’s get started.
[start of dialogue]
Simon: What’s all that?
Hilary: It’s a news report about the upcoming execution of Perry Hickock.
Simon: That’s barbaric. We shouldn’t have capital punishment in this day and age.
Hilary: This guy killed an entire family while trying to rob them in their own home. He was convicted of multiple murders and given the death penalty. This is about justice.
Simon: This is about vengeance. He could have been given a life sentence without the possibility of parole. As it is, he has spent 22 years on death row.
Hilary: Oh, I see, you’re one those people who is soft on crime. You think our criminals should be coddled.
Simon: No, I don’t. But aside from my moral objections, executing someone with a lethal injection or the electric chair is inhumane. Many executions are botched each year.
Hilary: So what? These are people convicted of serious crimes. They deserve all the punishment they get.
Simon: I’m going to have to start calling you “Hang ’em high Hilary.”
Hilary: And I’ll have to start calling you “Soft-hearted Simon.”
[end of dialogue]
Our dialogue begins with Simon asking Hilary, “What’s all that?” Hilary says, “It’s a news report about the upcoming execution of Perry Hickock.” It appears that Hilary is reading the newspaper about an “upcoming execution.” “Upcoming” means in the near future, or simply in the future. An “execution” (execution) is when someone is killed, especially as a punishment for a crime that he or she has committed or done.
Simon says, “That’s barbaric,” referring to the execution, of course. “Barbaric” (barbaric) means not civilized, extremely cruel. Simon says, “We shouldn’t have capital punishment in this day and age.” “Capital” (capital) punishment” is the act of killing someone by a government, usually because a person has committed a crime. “This day and age” simply means “nowadays” – in the current time.
Hilary says, “This guy” – the man who is about to be executed – “killed an entire family while trying to rob them in their own home.” Hilary is saying that the man who is going to be executed killed an entire family, that means everyone in the family, while trying to rob them. “To rob” (rob) someone is to steal things from him or her.
Hilary continues, “He was convicted of multiple murders and given the death penalty. This is about justice.” “To be convicted” (convicted) means to be found guilty, usually by a judge and/or a jury – a group of people who decide if you are guilty or not of a crime. This person, according to Hilary, was “convicted of multiple,” meaning many, “murders and given the death penalty.” The “death penalty” is the same as capital punishment. It is killing someone for committing a crime. (The government, of course, killing someone.)
Hilary says, “This is about justice” (justice). How do we define justice? Well, Socrates, Plato, and other great philosophers have spent a lot of time trying to answer that question, but here it really means something that is fair, something that is considered right or correct, something that is morally or ethically correct. Nowadays it is often associated with the law or law enforcement. We have, for example, a “Department of Justice” in the United States that is responsible for legal issues at a national level for our government.
Simon disagrees with Hilary. He says this is not about justice. “This is about vengeance,” he says. “Vengeance” (vengeance) is revenge. When someone does something bad to you and you do something bad to that person, that is “vengeance” – a kind of revenge. We might also say informally “getting back at” someone. Simon continues, “He” – meaning Perry Hickock, the killer – “could have been given a life sentence without the possibility of parole.”
A “life sentence” is a punishment that puts you in jail for the rest of your life. The word “sentence” here does not refer to a subject and a verb, but rather the punishment that you get from the government for committing a crime. A “life sentence” is when you are sent to prison for the rest of your life. Now, even if you are given a life sentence for doing something terrible, committing some horrible crime, it is often possible to be released from prison before you die.
You can also get something called “parole” (parole). “Parole” is when a prisoner leaves prison, either before or after his sentence is completed. So, if you are given a life sentence, you may, if you act appropriately in prison and don’t cause any more problems, be given at some point “parole.”
Now why do we have life sentences without parole? Because some people think that certain prisoners should never be released from prison, and so these people are given life sentences “without parole,” meaning there is no possibility for them to be released from prison in the future, other than when they die and are sent out in a coffin. A “coffin” (coffin) is a box that we put a dead body in when we are going to bury the body, put the body in the ground.
Anyway, back to our story. Simon is saying that instead of killing this person, they could have given him a life sentence without parole. “As it is,” Simon says, meaning “instead,” “he has spent 22 years on death row.” “Death row” (row) is a part of a prison where people who are awaiting to be executed are kept. The idea is that they are kept in a different part of the prison.
Now, I don’t want to go into the whole topic of capital punishment here in the United States. I do want to say, however, that capital punishment is legal in some states but not others. So, of the 50 United States, some of the states have capital punishment, states such as, I think, currently, Texas. But many states, including California, do not have capital punishment. Instead of killing the person, they get a life sentence without parole. “Death row,” then, would be a part of a prison where people who are awaiting to be executed are living or are kept.
Hilary responds to Simon, “Oh, I see, you’re one of those people who are soft on crime.” If you are “soft (soft) on crime,” you don’t believe in punishing a criminal with a long sentence. You may believe in punishing criminals, but not as much as other people do. It’s a relative term. To say someone is soft on crime isn’t really a very meaningful criticism because it just depends on what your definition of “soft” is.
For some people, being “soft on crime” might be giving a prisoner 10 years in prison for a certain crime. For other people, it may be giving them 20 years. It just depends on the kind of punishment we’re talking about. Hilary says, “You think our criminals should be coddled” (coddled). “To coddle” someone is to treat them in a very gentle way, almost as you might treat a young child. Simon says, “No, I don’t. But aside from my moral objections, executing someone with a lethal injection or the electric chair is inhumane.”
Simon has “moral objections” to capital punishment, meaning he doesn’t believe capital punishment is ethical. It goes against his sense of right and wrong. “Lethal” (lethal) means deadly – something that will kill you. An “injection” (injection) is when you or someone else such as a nurse or a doctor puts a needle in your body and puts some sort of liquid inside your body. A “lethal injection” would be an injection that kills you, and that’s one way that some places carry out capital punishment.
Another way is the use of something called the “electric chair.” An “electric chair” is a chair in which a person is placed, and certain wires are attached to the person’s body and you turn on the electricity, and that’s how you kill the person. Simon says that both of these methods of capital punishment are “inhumane” (inhumane). “Inhumane” means cruel – causing unnecessary pain and suffering.
Simon says, “Many executions are botched each year.” “To botch” (botch) something means to do something wrong, to do it in such a way that it doesn’t work or it isn’t done properly. In this case, if an execution is botched, the person doesn’t actually die, or doesn’t die as quickly as you had planned.
Simon says, “I’m going to have to start calling you ‘Hang ’em high Hilary.’” “Hang ’em high” is an old phrase used to describe someone who is enthusiastic about killing someone by hanging them. “To hang” someone is to kill them by putting a rope around their neck and letting them hang in the air. By calling Hilary “Hang ’em high Hilary,” Simon is criticizing her, saying that she’s too enthusiastic for capital punishment.
Hilary says, “And I’ll have to start calling you “Soft-hearted Simon.” Someone who is “soft-hearted” is someone who doesn’t want to punish other people or hurt other people. Once again, Hilary is using this as an insult, saying that perhaps Simon is too nice to criminals.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Simon: What’s all that?
Hilary: It’s a news report about the upcoming execution of Perry Hickock.
Simon: That’s barbaric. We shouldn’t have capital punishment in this day and age.
Hilary: This guy killed an entire family while trying to rob them in their own home. He was convicted of multiple murders and given the death penalty. This is about justice.
Simon: This is about vengeance. He could have been given a life sentence without the possibility of parole. As it is, he has spent 22 years on death row.
Hilary: Oh, I see, you’re one those people who is soft on crime. You think our criminals should be coddled.
Simon: No, I don’t. But aside from my moral objections, executing someone with a lethal injection or the electric chair is inhumane. Many executions are botched each year.
Hilary: So what? These are people convicted of serious crimes. They deserve all the punishment they get.
Simon: I’m going to have to start calling you “Hang ’em high Hilary.”
Hilary: And I’ll have to start calling you “Soft-hearted Simon.”
[end of dialogue]
The scriptwriting is never botched here at ESL Podcast, thanks to our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
execution – the act of killing someone, especially as punishment for a crime he or she has committed
* In the past, executions were held in the center of the village where everyone could watch.
barbaric – extremely cruel; not civilized or refined; primitive; unsophisticated
* Don’t you agree that burning someone alive is barbaric?
capital punishment – the act of killing someone as a legally authorized punishment for what he or she has done
* Capital punishment is allowed only for the worst crimes.
to convict (someone) – to determine that someone is guilty; to determine that someone has committed a crime
* Have you ever been convicted of any crimes?
death penalty – capital punishments; a legal punishment of execution; the punishment of killing someone for committing a crime
* Mia believes the death penalty should be allowed for very violent criminals.
justice – fair and just behavior; the principle of treating everyone fairly or equally
* The speaker asked the audience: “How can the legal system claim to uphold justice when such a large majority of prisoners are racial minorities?”
vengeance – revenge; retribution; retaliation; punishment given in reaction to the bad things one has previously done
* Clark killed his father’s murderer in a terrible act of vengeance.
life sentence – a punishment that puts a person in jail for the rest of his/her life
* If Bo is given a life sentence, he will never be allowed out of the prison again.
parole – the temporary release of a prisoner, with that prisoner’s agreement to behave well and meet with officers regularly
* Piotr was supposed to be in prison for 30 years, but he got out on parole after just 12 years.
death row – the part of a prison that houses people who are waiting to be executed (killed)
* Life must be miserable for prisoners on death row, always wondering when they’ll receive their punishment and be executed.
soft on crime – giving only minimal punishments to criminals while making sure that those criminals receive all their rights
* When the legal system is soft on crime, crime rates tend to increase, because people don’t expect to receive a harsh punishment for their bad actions.
to coddle – to treat someone in a gentle, protective, and indulgent way, as one might treat a small child
* If you keep coddling your grown children, letting them live with you for free and paying for their car insurance and cell phone, they’ll never move out on their own.
moral – relating to evaluations of what is right and wrong, and whether people are good or bad
* My mother is a moral woman who never lies, cheats, or steals.
lethal injection – the practice of executing (killing) someone as a punishment by inserting a needle into the body to deliver poisonous drugs that kill quickly
* This lethal injection should stop the heart within two minutes.
electric chair – a chair that is used to execute (kill) someone by sending electricity through the chair and the body
* Would you rather die by hanging, or by sitting in an electric chair?
inhumane – cruel; without kind or fair treatment of others; causing unnecessary suffering
* That apartment is so dirty that having to live there would be inhumane!
to botch – to do something carelessly or clumsily so that it fails or does not work properly
* You can see that the paint job was botched by all of the smears on the floor.
hang ‘em high – a phrase used to show one’s enthusiasm for killing someone by hanging (wrapping a rope around one’s neck)
* In the Wild West, it was common for local officials to say, “Hang ‘em high” when men were caught committing a crime.
soft-hearted – with a lot of kindness, sympathy, and empathy, and not wanting to punish or hurt others, instead feeling pity for them
* Mothers who are too soft-hearted struggle to discipline their children.
Comprehension Questions
1. Which punishment would a soft-hearted person be most likely to support?
a) Capital punishment
b) The death penalty
c) A life sentence
2. Which of these people could be described as being “soft on crime”?
a) Someone who often commits minor crimes
b) Someone who thinks that executions are moral
c) Someone who does not want to punish criminals harshly
Answers at bottom.
What Else Does It Mean?
justice
The word “justice,” in this podcast, means fair and just behavior, and the principle of treating everyone fairly or equally: “The right to a fair trial is a critical part of justice in any nation.” Or, “The children have a strong sense of justice, always insisting that everyone’s portion of dessert be the same size.” The phrase “to do justice to (something)” means to do something as well as it should be done, or to represent something fully or fairly: “This is my best attempt to paint the landscape, but it doesn’t do justice to the natural beauty.” Finally, the phrase “justice has been served” means that someone has received a deserved punishment, or that someone has been treated fairly: “The judge sentenced him to 20 years in prison. Justice has been served.”
soft
In this podcast, the phrase “soft-hearted” means with a lot of kindness, sympathy, and empathy, and not wanting to punish or hurt others, instead feeling pity for them: “Janice is too soft-hearted to break up with her boyfriend. She always forgives him.” Someone who is “soft-spoken” has a quiet, pleasant voice that is not assertive: “Soft-spoken employees are less likely to receive raises or promotions.” The phrase “to soft-pedal” means to treat something as if it is less urgent or less important than it really is: “Why is management soft-pedaling the expansion? If we wait too long, we’ll miss this opportunity.” Finally, a “soft target” is a thing or person that is easy to criticize and/or will not present a defense: “Those small startup companies are soft targets for our sales strategies.”
Culture Note
Three-strike Laws
“Three-strike laws” are laws that “mandate” (require) “strict” (harsh; severe) punishments for “repeat offenders” (people who break the law more than once). The term is “taken” (adapted) from baseball, where players can get up to three “strikes” (instances where they swing at the ball, but miss), but on the third strike they are “out” (must leave the field). With a three-strike law, an “offender” (criminal) may receive a “relatively” (comparatively) “mild” (soft; gentle; not harsh) punishment the first two times he or she commits a crime, but the third time there is a “mandatory” (required) “prison sentence” (a length of time when one must stay in jail as punishment).
As of 2015, 24 states had three-strike laws. The laws are popular because they reduce “recidivism” (the rate at which criminals break the law again or end up in jail again), but they also have negative consequences. In many of the states, at least one of the three crimes has to be a violent crime, such as “assault” (attack), “rape” (sexual attack; forced sex), or murder. But in other states, such as California, people are sometimes given very long prison sentences for relatively minor crimes. For example, someone who steals from a store three times may end up in jail for many years. This leads to “overcrowding” (with too many people in a small area) in many jails and growing expenses for the state. And the “criminal record” (a history of being in jail) can make it very difficult for those “ex-offenders” (people who have committed a crime in the past) to find a good job or housing.
Comprehension Answers
1 - c
2 - c