= 1127
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,127 – Paying for College.
This is English as a Second Language Podcast episode 1,127. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store. While you’re there, you can also take a look at our ESL Podcast Blog. If you’re on Facebook, you can like us on Facebook. Go to facebook.com/eslpod.
On this episode, we’re going to listen to a dialogue between Chris and Marcella about getting enough money to go to college. Let’s get started.
[start of dialogue]
Chris: Which colleges are you applying to?
Marcella: None. I can’t afford to go to college. Even if I lived at home, tuition, fees, and books are just too expensive.
Chris: You could apply for financial aid.
Marcella: I don’t want to get a bunch of loans and be in debt for the next 10 to 20 years. It’s not worth it.
Chris: Loans aren’t so bad, especially ones that are federally subsidized. Apart from that, you could get need-based grants or work-study. Put all of that together and college can be affordable.
Marcella: I don’t want to go into debt of any kind.
Chris: You could go to a community college and transfer to a four-year university after two years. Community college tuition is much lower.
Marcella: But who has the time? I have to work full-time to pay my bills.
Chris: Then think about a program that has a service commitment.
Marcella: What do you mean?
Chris: There are teaching, military, or community service programs that will forgive or pay off your loans if you work for the organization for a few years after graduating.
Marcella: And be an indentured servant? No, thank you!
Chris: Okay, but most good jobs nowadays require a college degree.
Marcella: Not if you really have talent.
Chris: Talent?
Marcella: Yeah, haven’t you seen me mime? That’s my ticket to a great career.
Chris: I’m happy to hear you have such a practical plan mapped out for your future.
[end of dialogue]
Chris asks Marcella, “Which colleges are you applying to?” Which colleges are you trying to get into, are sending applications to? Marcella says, “None. I can’t afford to go to college.” Marcella says she “can’t afford to go to college,” meaning she doesn’t have any money. She says, “Even if I lived at home, tuition fees and books are just too expensive.” “Tuition” (tuition) is the money that you pay to a school, including a college or university, to be a student there. It’s the money you pay for your classes.
Usually, American universities charge a certain amount of money for a full-time student, which allows that student to take anywhere between three and five classes. Of course, you want to take as many classes as possible to get the most from your money. Not all colleges work that way. Some colleges will charge you for each class you take, so it doesn’t really make a difference, but that’s the idea of “tuition.” It’s money you pay to a school so that you can be a student there.
Chris says, “You could apply for financial aid.” “Financial aid” (aid) is money that is either given to a student by the college, an organization, or the government, or money that is loaned to a student by a bank or the government to pay for the costs of being a student. That would include tuition, living expenses, books, and so forth. The national or federal government has a financial aid program that it uses to give money to students all over the country.
Each state also typically has a financial aid program, so a student may be getting money from the federal government as well as the state government. And of course, individual universities also will sometimes give students money, although most of the financial aid comes from either the federal or the state government, either in the form of what we call “grants” (grants) or loans. A “grant” is money the government gives you and you don’t have to pay it back. It’s like a gift.
Marcella says, “I don’t want to get a bunch of loans and be in debt for the next 10 to 20 years. It’s not worth it.” A “loan” (loan) is, you probably know, money that someone gives you temporarily, with the idea that you will give that money back to the person. “To be in debt” (debt) – notice the “b” is silent – means to owe money to other people or to a bank. “To be in debt” means that you have to pay money back to people. It means that you have loans, that is. Marcella says she does not want to be in debt for the next 10 to 20 years. She says, “It’s not worth it” – it’s not something that I think is a good idea for my future.
Chris says, however, “Loans aren’t so bad,” meaning it’s not that bad for you to get a loan, “especially,” he continues, “ones that are federally subsidized.” “To be subsidized” (subsidized) means to receive financial support from some other organization, especially from the government. In “federally subsidized loans,” the government pays some of the interest on the loan. “Interest” on a loan is money you pay to borrow the money. It’s like the price of the loan. The “federally subsidized loans” are loans for which the U.S. national, or federal, government will pay a certain amount of the interest on it.
Chris says, “Apart from that,” meaning separate from that, “you could get need-based grants or work-study.” Something that is “need (need) – based (based)” is something that depends upon how much money you make or have. A “need-based grant” is money that the government gives you based upon how poor you are.
“Work-study” is a special program that, again, the government often pays for, where you work on the campus of the university or college. You work when you are a student for the college, doing things like cleaning and working in the library and helping out in the offices. That would be a work-study situation, and that’s a kind of financial aid. They only give those jobs to the students who need them.
Chris says, “Put all of that together,” meaning combine all of those things, “and college can be affordable.” Something that is “affordable” (affordable) is something that is not too expensive. It doesn’t cost too much money. You can pay for it. You have enough money for it. Marcella says, “I don’t want to go into debt of any kind.” Marcella doesn’t want to have any loans is what she’s saying.
Chris says, “You could go to a community college and transfer to a four-year university after two years. Community college tuition is much lower.” A “community college” – what we used to call a “junior college” in most states – is a college that usually has only two years of schooling available. Many times community colleges will offer what’s called an “AA” or an “Associate of Arts” degree or an “AS” – an “Associate of Science” degree. These are usually for specific kinds of jobs or things that don’t require a four-year university degree, a bachelor’s degree.
Sometimes people will study at community colleges to do all of their general education requirements before transferring or moving from the community college to a four-year college or university where they get their bachelor’s degree. This is very common in California because the tuition at community colleges is cheaper than the tuition at four-year universities, or universities that give bachelor’s degrees.
It’s quite common here in Los Angeles, for example, for international students to come over and study at a community college such as Santa Monica College, which is close to where I live, and then after two years, after taking their general classes and improving their English, they transfer to either USC (University of Southern California) or UCLA (the University of California, Los Angeles) or another university here in California.
When I say they take “general education classes,” I mean that they take classes that most universities require they take – English classes, math classes, usually some sort of science and history classes – classes that are usually required by most universities in order to graduate with a four-year degree.
Marcella says, “But who has the time? I have to work full-time to pay my bills.” Chris says, “Then think about a program that has a service commitment.” A “service commitment” is an agreement or a contract where you agree to work at a certain kind of job when you finish your education, and by agreeing to do that, the government or an organization will give you money.
This is common, for example, for teachers, because there are many schools, especially in cities like Los Angeles, that need teachers. The government may give you money to become a teacher, but you have to agree to work for one of the schools for a certain number of years. If you don’t, then you have to pay the money back to the government as a loan.
I got my teaching license back in Minnesota many years ago on one of these service commitment grants. Although I didn’t actually work long enough in the schools to meet the agreement, so I had to pay some of it back as a loan. But that’s not the point of the story. The point of the story is that you can sometimes get money by signing one of these service agreements for certain kinds of jobs.
There aren’t very many jobs that the government will do this for you. Sometimes it does it for doctors. They will pay the loans of doctors who agree to work in certain parts of the country that need doctors. Marcella says, “What do you mean?” And then Chris explains. “There are teaching, military, or community service programs that will forgive or pay off your loans if you work for the organization for a few years after graduating.” Chris mentions the military. The U.S. military will also give you money to go to college if you agree, of course, to go into the military for a certain number of years after.
The verb “to forgive a loan” refers to not requiring you to pay the loan back. So, if the government gives you a loan and forgives the loan, the government is saying you don’t have to give us the money that we gave you for the loan. “To pay off a loan” is to actually pay usually a bank that has loaned you the money, the money that you owe. But Marcella doesn’t like this idea, either. She says, “And be an indentured servant? No, thank you!” An “indentured servant” was a person who signs an agreement to work for another person without getting paid for a certain amount of time.
We don’t have indentured servants anymore. It’s not legal in the United States to have an indentured servant. It was something that was more popular in the nineteenth century and before. Wealthy families, for example, would pay immigrants to come and work on their farms or at their houses, and these workers would have to work for those people for a certain amount of time in order to, in effect, pay off the loan that the rich family gave the immigrants in order to come to the United States.
Chris says, “Okay, but most jobs nowadays require a college degree.” A “degree” is a document saying that you have completed certain requirements at the university. Marcella says, “Not if you really have talent.” She’s saying that not all jobs require a college degree if you have talent. Chris says, “Talent?” Marcella says, “Yeah, haven’t you seen me mime?” “To mime” (mime) is to use your body and your face and your hands to show some action without actually saying anything. Marcella thinks she has a talent for miming.
She says, “That’s my ticket to a great career.” Your “ticket” here refers to your path to success, the way that you’re going to make a lot of money. Chris says, “I’m happy to hear you have such a practical plan mapped out for your future.” “To map out” something is to plan it, to know what all the details are of the plan that you are going to carry out. We use this expression not just in talking about using physical map to find out how to get from one place in the city to another, but more generally to refer to someone making detailed plans about his or her future.
Chris, of course, is being a little sarcastic here. He’s making a joke. He doesn’t think that trying to become a professional mime is a very good plan for Marcella.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Chris: Which colleges are you applying to?
Marcella: None. I can’t afford to go to college. Even if I lived at home, tuition, fees, and books are just too expensive.
Chris: You could apply for financial aid.
Marcella: I don’t want to get a bunch of loans and be in debt for the next 10 to 20 years. It’s not worth it.
Chris: Loans aren’t so bad, especially ones that are federally subsidized. Apart from that, you could get need-based grants or work-study. Put all of that together and college can be affordable.
Marcella: I don’t want to go into debt of any kind.
Chris: You could go to a community college and transfer to a four-year university after two years. Community college tuition is much lower.
Marcella: But who has the time? I have to work full-time to pay my bills.
Chris: Then think about a program that has a service commitment.
Marcella: What do you mean?
Chris: There are teaching, military, or community service programs that will forgive or pay off your loans if you work for the organization for a few years after graduating.
Marcella: And be an indentured servant? No, thank you!
Chris: Okay, but most good jobs nowadays require a college degree.
Marcella: Not if you really have talent.
Chris: Talent?
Marcella: Yeah, haven’t you seen me mime? That’s my ticket to a great career.
Chris: I’m happy to hear you have such a practical plan mapped out for your future.
[end of dialogue]
We are all in debt to the wonderful Dr. Lucy Tse for her wonderful scripts. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
tuition – the amount of money that must be paid to a school, college, or university to be a student there
* In-state students pay lower tuition than out-of-state students.
financial aid – money loaned or given to a student to partially or fully pay for the costs associated with being a student
* Sheryl received enough financial aid to cover tuition and books, but she still needed her parents’ help for food, housing, and transportation.
loan – money that is given temporarily with the expectation that it will be repaid at a certain point in the future, with interest
* They applied for a business loan to buy some new equipment.
in debt – owing money to other people or institutions
* They’re in debt to the bank for $300,000 and can’t make their payments.
subsidized – receiving financial support, especially from the government, that makes an activity or position more financially attractive than it would otherwise be
* Many corn and wheat farmers are subsidized by the U.S. government.
need-based grant – a scholarship (money that is given to help a student pay for school) that is awarded to people who have few or no financial resources and can show a financial need for the funding
* If your parents make more than $100,000 per year, you probably aren’t eligible for a need-based grant.
work-study – a program that allows students work part-time while studying at a university, so that they can use the money earned to help pay for their education
* The university offers a work-study program to needy students, with students working in the offices of different academic departments.
affordable – not too expensive; at a price that one can pay
* Those designer jeans are so expensive! Try these generic ones instead. They’re more affordable.
community college – a junior college that serves the local community, usually with two-year degree programs and with many non-credit courses for community members
* The community college offers courses in foreign languages, art, dance, computer skills, and more for community members who want to continue to learn.
to transfer – to move to another place; to stop studying at one institution and begin studying at another one
* Jackson decided to transfer to a larger university, because he wanted the opportunity to study with more well-known researchers and professors.
service commitment – an agreement to do some type of work that helps other people and the community, especially to pay back the organization that has paid for one’s education
* If you accept that scholarship, you’ll have to fulfill the service commitment and agree to work for them for at least three years after graduation.
to forgive (a loan) – to not require that a loan be repaid; to allow a borrower to forget about paying back a loan
* Does the Peace Corps forgive your old student loans?
to pay off – to pay the full amount owed
* They have a 30-year mortgage, but they hope to pay it off early.
indentured servant – having signed an agreement, a person who is required to work for another person without pay for a specific period of time
* A few hundred years ago, wealth landowners would pay for immigrants to come to North America from Europe, and in exchange, they had to work as indentured servants for several years.
degree – a diploma; a document stating that one has completed the minimum requirements for a particular field of study at a particular university
* He has an undergraduate degree in mechanical engineering and a graduate degree in physics.
to mime – to use one’s face, body, and gestures (hand movements) to show some action or idea to an audience, without using words
* The clown is using his hands to mime that he is trapped inside an invisible box.
(one’s) ticket – one’s path to success, and especially the way in which one will earn a lot of money
* Getting this book published is my ticket to fame and fortune.
mapped out – planned; with the path and all details known
* Alyce has always wanted to be a doctor, and she has had her education mapped out since she was a child.
Comprehension Questions
1. Which of these needs to be repaid?
a) Loans
b) Need-based grants
c) Work-study
2. Why does Chris suggest that Marcella study at a community college?
a) Because the faculty and staff are friendlier
b) Because it is less expensive than a university
c) Because the coursework is more challenging
Answers at bottom.
What Else Does It Mean?
grant
The word “grant,” in this podcast, means a scholarship, or money that is given to help a student pay for school, with no expectation that it will be repaid: “Elliott received a research grant to study the effects of exercise on skin diseases.” A “needs-based grant” is awarded to people who have few or no financial resources to pay for school, and a “merit-based grant” is awarded to people with good grades and exceptional accomplishments. The phrase “to take (something) for granted” can mean to believe that something is true without checking it first: “We just took it for granted that the apartment would have an air conditioner, but it only has ceiling fans.” The phrase can also mean to assume that someone or something will always be available and to not show enough gratitude or appreciation for the person or thing: “Helena feels that she is being taken for granted, because no one thanks her for all of the work she does each week.”
(one’s) ticket
In this podcast, the phrase “(one’s) ticket” means one’s path to success, and especially the way in which one will earn a lot of money: “Demonstrating good behavior and self-improvement is his ticket to getting out of jail early.” The phrase “just the ticket” means that something is precisely what one needed: “During the marathon, a sports drink and an energy bar were just the ticket for having enough energy to finish the race.” A “big-ticket item” is something that is very expensive: “We’re living on a tight budget with no money for big-ticket items.” Finally, a “meal ticket” is a person or thing that one uses to have enough money for food and other needs: “They sold everything to put their daughter through school, so now they expect her to be their meal ticket when they retire.”
Culture Note
The FAFSA
The “Free Application for Federal Student Aid” (“FAFSA”) is a form that all “prospective” (soon to be; expected to be) and current college students are encouraged to fill out once per year. The U.S. government and colleges and universities throughout the United States use the information on the “completed” (filled out) FAFSA to make “determinations” (decisions) about financial aid. For example, the U.S. government uses information on the FAFSA to determine who is eligible for federal financial aid programs, such as Pell Grants, Stafford Loans, Perkins Loans, and work-study programs.
The FAFSA requests information about the student’s identity, income, and “assets” (things a person owns that can be sold for money). If the student is a “dependent” (someone whom others are financially responsible for), the FAFSA request information about the parents’ or other caregivers’ income and taxes. And if the student is married, information must be provided about the student’s “spouse” (husband or wife). The information must be “documented” (proven in writing), typically through “paystubs” (receipts for payments one has received), bank “statements” (written reports of activity in a bank account over a period of time), and “tax returns” (papers filed each year when paying one’s taxes).
Students can fill out the FAFSA for free in one of three ways: on paper, online, or even over the phone. Some companies will help students or fill out the FAFSA for students in exchange for payment of a fee.
Comprehension Answers
1 - a
2 - b