= 1103
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,103 – Sports Tryouts.
This is English as a Second Language Podcast episode 1,103. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode.
This episode is a dialogue between Marcela and Kenji about trying to become a member of a sports team. Let’s get started.
[start of dialogue]
Marcela: All right, you’re ready for these tryouts. You’ve passed your physical. You’ve trained for months. You’re going to make that team.
Kenji: It’s okay. I don’t need a pep talk. I’m just going to do the best I can.
Marcela: Yes, but you want to have your head in the right place. You’re going to dominate the field. You’re going to intimidate the other players.
Kenji: No, I only want to impress the coach. I’m going to play hard and hold nothing back.
Marcela: Yes, that’s fine, but you want to send a message to the other players that you’re a force to be reckoned with.
Kenji: I’m going to have faith in my abilities and hope for the best.
Marcela: At least try to look tough. Try scowling at the other players like you can’t wait to get them on the field so you can crush them.
Kenji: [sigh] I tell you what, why don’t you scowl for me? I think you’re much scarier than any player who’s ever played this game.
[end of dialogue]
Marcela begins our dialogue by saying to Kenji, “Alright, you’re ready for these tryouts.” A “tryout” (tryout) is an opportunity to demonstrate your ability to do something. Usually it is something you have to do in order to become a member of a sports team or perhaps even a musical group. A “tryout” is when you go in front of sometimes a coach or another judge who decides if you are good enough to be a member of this group or this team.
So, a “sports tryout” would involve you going and playing the sport in front of a group of coaches or in front of a coach who is going to decide whether you are good enough to be part of this sports team. Another word for a tryout that we often use when we’re talking about a musical production or a movie or a television show is “audition” (audition).
Marcela says to Kenji, “You’ve passed your physical.” A “physical,” as a noun, is a medical examination that determines whether you are healthy enough to participate – in this case, in a certain sport. Children often get physicals every year or every other year to make sure that they’re growing properly, that they don’t have any physical problems that they need to take care of. Adults should also get a physical once a year or every other year. I know I do.
Marcela says Kenji passed his physical, meaning his doctor determined that he was good enough to participate in this particular sport. Marcela says, “You’ve trained for months,” meaning you’ve been preparing physically for months. “You’re going to make that team.” “To make (make) a team” means to be selected to participate in a team, to be chosen as a member of a team.
Kenji says, “It’s okay. I don’t need a pep talk.” A “pep (pep) talk” is a speech that encourages one or more people to do a good job. It’s a way of motivating someone or a group of people. Sometimes, before a sports game, the coach of the team will talk to the team and give them a pep talk – try to get them motivated and enthusiastic about going out and winning the game.
Kenji says, “I’m just going to do the best I can.” Marcela says, “Yes, but you want to have your head in the right place.” The expression “to have your head (head) in the right place” means to be thinking about the right thing – to be focused, to be concentrated on what you are trying to do. It means to be psychologically prepared for a certain activity.
Marcela says, “You’re going to dominate the field.” “To dominate” (dominate) in this sentence means to be better than anyone else, to be the best. Marcela adds, “You’re going to intimidate the other players.” “To intimidate” (intimidate) means to scare someone, to frighten someone because you are stronger or more confident than he is. “Intimidation” is usually a bad thing.
Here Marcela is saying that Kenji should intimidate the other players, the other people on the team, in such a way that they are afraid of him because he’s such a good player, I think is the idea. Kenji says, “No, I only want to impress the coach.” “To impress” (impress) someone is to show someone that you have a lot of talent or skill – to have that person think that you are very good at what you do, to have a person admire you.
A “coach” (coach) is the person who is the head of a sports team, the person who is in charge of telling the players what to do and of making plans for how the team will play. Kenji says, “I’m going to play hard and hold nothing back.” “To play hard” means to try very hard to win a game or a competition, to put all the effort that you can into winning. “To hold nothing back” is something similar. It means to do something at the maximum level, to do something with the maximum effort that you can.
Marcela says, “Yes, that’s fine, but you want to send a message to the other players that you’re a force to be reckoned with.” “To send a message” to someone doesn’t mean to email them, necessarily. It means to communicate something very clearly to another person or group of people so that there is no possibility of them not understanding. You’re making something very clear to them.
Marcela is telling Kenji to send a message to the other players. What message? The message that he is “a force (force) to be reckoned (reckoned) with.” If you are a force to be reckoned with, you are someone who is too important or too powerful to be ignored. You are a person that the other people have to deal with somehow. They can’t ignore you. They have to do something about you. Marcela is telling Kenji to act in such a way that the other players know that he is a force to be reckoned with.
Kenji says, “I’m going to have faith in my abilities and hope for the best.” “To have faith in” something or someone is to believe in something or someone – to think that this thing or person is real and good even if you can’t see it or even if you don’t have all the information that you might need to know it for sure. It can also mean to trust in something or someone.
Marcela says, “At least try to look tough” (tough). “To look tough” means to look strong, to look like you are capable of doing things that are very difficult. In fact, we sometimes use this word “tough” as an adjective to mean difficult, but here it means to look strong. If you say, “That guy looks tough,” you mean he looks physically strong, maybe big enough to hurt you. My ex-girlfriend was like that.
Anyway, Marcela says, “Try scowling at the other players like you can’t wait to get them on the field so you can crush them.” Marcela is obviously trying to get Kenji to be tougher. She’s telling Kenji to scowl (scowl). “To scowl” is to make a mean expression on your face. Often it involves partially closing your eyes – not closing them all the way, but making this mean expression on your face.
“To crush” (crush) means to completely beat or defeat someone. For example, “The Los Angeles Dodgers crushed the San Francisco Giants 10 to nothing in the baseball game yesterday.” That’s just a hypothetical. If a team wins by a large score, we say the team “crushed” the other team. That’s what Marcela wants Kenji to do to the other players. Kenji sighs. He makes a sound indicating that he is tired, really, of hearing Marcela give him advice.
He says, “I tell you what.” “I tell you what” is an informal phrase used to make a suggestion or to present a new idea for another person to think about or to consider. You could also say, “I’ll tell you what.” “I will tell you what.” But the more informal and perhaps a little more common expression is “I tell you what.” Kenji says, “I tell you what, why don’t you scowl for me? I think you’re much scarier than any player who’s ever played this game.” Kenji is saying to Marcela that she seems to be tougher and scarier than any of the people who are on the sports team.
Now, we don’t know what kind of sport this is. It might be American football. It might be basketball. But in any case, Kenji doesn’t really want to hear Marcela’s advice and thinks that Marcela should perhaps just go out and try to be the one who scowls and is scary to the other players. I have to say, I wasn’t really very big into sports and sport teams when I was in school, although I was on my seventh- and eighth-grade volleyball team. Not exactly American football, but I thought we were pretty tough.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Marcela: All right, you’re ready for these tryouts. You’ve passed your physical. You’ve trained for months. You’re going to make that team.
Kenji: It’s okay. I don’t need a pep talk. I’m just going to do the best I can.
Marcela: Yes, but you want to have your head in the right place. You’re going to dominate the field. You’re going to intimidate the other players.
Kenji: No, I only want to impress the coach. I’m going to play hard and hold nothing back.
Marcela: Yes, that’s fine, but you want to send a message to the other players that you’re a force to be reckoned with.
Kenji: I’m going to have faith in my abilities and hope for the best.
Marcela: At least try to look tough. Try scowling at the other players like you can’t wait to get them on the field so you can crush them.
Kenji: [sigh] I tell you what, why don’t you scowl for me? I think you’re much scarier than any player who’s ever played this game.
[end of dialogue]
Our scriptwriter holds nothing back in writing the very best scripts for us here at ESL Podcast. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
tryout – audition; an opportunity to demonstrate one’s ability to earn an opportunity to participate in something, especially a sports team, a music group, or a theatrical performance
* More than 100 people attended the tryout, hoping to be selected for the basketball team.
physical – a medical exam, typically conducted once a year as a check-up to evaluate one’s health
* The school requires that all students complete a physical and have their doctor’s approval before participating in athletic activities.
to make a team – to be selected to participate in a team; to be chosen as the member of a team
* Only students with a GPA of at least 3.5 will make the debate team.
pep talk – a speech that encourages one or more people to do very well and helps them feel motivated and enthusiastic
* The vice-president gave all the sales representatives a pep talk to help them meet their sales goals.
to have (one’s) head in the right place – to concentrate and be thinking about the right thing, without distracting thoughts
* In high school, Kyle was a poor student, but once he got to college, he seemed to have his head in the right place and he was really focused on his studies.
to dominate – to do something better than anyone else; to be the best, most important, loudest, biggest, and/or strongest in a group
* This author’s books always dominate the lists of bestsellers.
to intimidate – to frighten someone, especially because one appears to be very strong and confident, with superior skills or talent
* All the other golfers became intimidated when they saw the youngest competitor make a hole in one.
to impress – to make someone feel respect and admiration, especially because one has done something very well or has a lot of talent or skill
* The job candidate impressed us with her direct and thorough answers to the interviewer’s questions.
coach – trainer; a person whose job is to help an athlete or team develop skills to perform as well as possible
* The gymnastics coach thinks that William could compete in the Olympics if he doesn’t suffer an injury.
to play hard – to try very hard to win a game or competition
* The other team is playing hard, but our players are bigger and stronger, so we will probably win.
to hold nothing back – to do something with maximum effort; to do something at an extreme or maximum level
* If you’re going to finally tell her how your feel, hold nothing back.
to send a message – to communicate something very clearly so that there is no possibility of misinterpretation or misunderstanding
* Firing low-performing employees sends a clear message to the rest of the staff.
a force to be reckoned with – something or someone that is a significant factor and must be dealt with, because it is too important or noteworthy to be ignored
* The new manager is a force to be reckoned with, with new ideas and plans.
to have faith in – to believe in something and think that is it real and good, even if that something that cannot be seen; to trust
* The Board of Directors must have faith in this proposal, or else they wouldn’t have approved the budget for it.
tough – physically strong and brave; capable of doing things that are too difficult or unpleasant for most other people
* Blaine thinks he’s tough enough to hike to the top of the mountain in just a day.
to scowl – to frown angrily; to make a mean, aggressive facial expression, turning down the corners of one’s mouth and partially closing one’s eyes
* The woman scowled when the dog peed on her carpet.
to crush – to beat a competitor very badly; to score a clear win; to strongly defeat
* Their team crushed ours, 39 to 8.
I tell you what – a phrase used to make a suggestion or to present a new idea for another person to consider
* I tell you what, let’s hear everything the presenters want to say before we make a final decision.
Comprehension Questions
1. What is a pep talk?
a) A motivational speech
b) Extra exercises to warm up
c) Secret information about one’s competitors
2. What does Marcela mean when she says that she wants Kenji to have his head in the right place?
a) She wants him to improve his skills for playing the game.
b) She wants him to accept all of her advice.
c) She wants his to think positive thoughts and be confident.
Answers at bottom.
What Else Does It Mean?
to hold nothing back
The phrase “to hold nothing back,” in this podcast, means to do something with maximum effort, or to do something at an extreme or maximum level: “Blake held nothing back when telling his boss all the reasons why he was quitting.” The phrase “to hold (someone) back” means to prevent someone from making progress: “The need to care for young children can hold women back in their career.” The phrase “to hold (something) back” can mean to not show an emotion: “They found it difficult to hold back tears while watching the movie.” Or, “Even though they knew laughing would be inappropriate, they couldn’t hold back their laughter.” Finally, the phrase “there’s no holding (someone) back” means that there is nothing one can do to prevent someone from doing something: “Once she made up her mind to sell the house, there was no holding her back.”
to crush
In this podcast, the verb “to crush” means to beat a competitor very badly or to strongly defeat them: “Nobody likes to watch one team crush another; games are always more interesting when the teams are more evenly matched.” The phrase “to crush (someone)” means to make someone feel very upset or disappointed: “Ali was crushed when he found out he wasn’t accepted into the program.” The phrase “to crush (someone’s) hopes/confidence/dreams” means to make someone lose all hope/confidence/dreams: “Getting a grade of “F” in biochemistry crushed Jacques’ dreams of becoming a medical researcher.” Finally, the phrase “to have a crush on (someone)” means to feel romantic feelings and love for another person, especially if one does not know that person well: “Is it common for elementary school students to have a crush on their teacher?”
Culture Note
Team Sports in Schools
Most American high schools offer opportunities for students to play team sports with their “peers” (classmates). Some of the teams are “open to everyone” (with everyone being allowed to play, regardless of experience or skill level), but others require that students try out and demonstrate their abilities before they are selected by the coach and/or team “captain” (the leader of a team).
The best players, usually “upperclassmen” (juniors and seniors; students in 11th and 12th grade), play on “varsity” teams. Players who are not as “talented” (with a lot of natural ability) or as skilled yet, usually younger students in 9th and 10th grade, play on “junior varsity” or “JV” teams. The JV athletes are training to become varsity players in a “subsequent” (later) year.
A “second-string” player is an individual who is not one of the starting players on the team, but serves as a “substitute,” or someone who can take the place of a regular player who is not able to play, “perhaps” (maybe) because of an “injury” (when one’s body is hurt).
High school sports teams “typically” (usually) practice after school and before dinner time, although some teams have evening practices. They may practice between one and four nights per week, depending on the “season” (time of year), ability level of the team, and upcoming games. Games are sometimes held in the evening, and sometimes on weekends. Teams usually play against the teams of other high schools. If the high schools are “nearby” (close), the families might be responsible for transporting the students to the game. If the students are competing against teams that are further way, or if they are in a “championship” (games played to determine which team is the best in an area), the school might provide bus transportation.
Comprehension Answers
1 - a
2 - c