= 1112
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,112 – Doing Impressions.
This is English as a Second Language Podcast episode 1,112. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com or download one of our Special Courses in Business and Daily English. You can also take a look at our ESL Podcast Blog. And why not like us on Facebook at facebook.com/eslpod.
This episode is a dialogue between Edison and Kay about imitating someone else’s voice. Let’s get started.
[start of dialogue]
Edison: [in a high-pitched woman’s voice] “I’m paying you less and working you harder. What are you complaining about?”
Kay: Ha, ha. You sound just like Justine! You really have a gift for doing impressions, but maybe we should shut the door.
Edison: Oh I’m not worried about Justine hearing me. She’s my boss, but she’s not the boss of me.
Kay: What would she say if she saw you imitating the way she walks and the gestures she makes?
Edison: We all know what they say: Imitation is the highest form of flattery. Right?
Kay: I’m not sure Justine would see it that way. It sounds more like mockery to me. I think it’s all in the tone.
Edison: It’s a simple parody of how she normally addresses the staff. It’s all done in good fun. It’s not mean-spirited.
Kay: Of course not, but she might take it the wrong way.
Edison: Then she would need to learn to laugh at herself. It’s healthy for the ego.
Kay: “Whatever you say, boss. You’re always right, boss.”
Edison: Who was that supposed to be?
Kay: Remember what you said about imitation being be the highest form of flattery . . .
Edison: That was supposed to be me? Me?!
[end of dialogue]
Edison begins our dialogue speaking in a high-pitched voice.” A “high-pitched (pitched) voice” is a voice that sounds very high. We normally associate a higher-pitched voice with a woman and a lower-pitched voice with a man. So, “high-” and “low-pitched” are the terms that we use. Edison, who is a man, speaks in a high-pitched voice in order to imitate, or sound like, another person at his job. He says, “I’m paying you less and working you harder. What are you complaining about?” He’s pretending as though he were this other woman by the name of Justine.
Edison is pretending that Justine is asking him what he is complaining about. “To complain” (complain) is to talk about things you don’t like about something, the problems with something. It could be your meal at a restaurant. It could be your job. It could be just about anything. Some people like to complain. They like to talk about the negative aspects of things or they like to tell other people about these problems in the hopes that they will be fixed.
Kay laughs at Edison’s imitation of Justine’s voice. She says, “You have a gift for doing impressions, but maybe we should shut the door.” “To do impressions” (impressions) is to imitate someone’s voice, usually to be funny, usually as entertainment. There are many famous comedians who imitate other famous people in order to make a joke about those people. Some people are very good at imitating, or sounding like, another person – that is, some people are very good at doing impressions.
Kay thinks, however, that she and Edison should shut or close the door so that, presumably, their boss doesn’t hear them making fun of her. Edison, however, says, “Oh, I’m not worried about Justine hearing me. She’s my boss but she’s not the boss of me.” This is an interesting phrase. “Not the boss (boss) of me” is used to assert your independence, to say to someone that that person doesn’t have authority over you. A “boss” is a person who is a manager, who is in charge of you at your workplace.
The expression “not the boss of me,” however, can be used in pretty much any context where one person is trying to tell another person what to do, as if the person had authority. You might say to your brother, “You’re not the boss of me” if your brother tells you how to act or behave. For some reason, Edison recognizes that Justine is his boss, but says that she’s not the boss of him, perhaps meaning that he can make his own decisions even though she is the boss.
Kay says, “What would she,” meaning Justine, “say if she saw you imitating the way she walks and the gestures she makes?” Doing impressions is usually related to imitating, or copying, someone’s voice, but you may also copy a person’s gestures. “Gestures” (gestures) are the movements that you make with your body, especially your hands.
Edison says, “We all know what they say: Imitation is the highest form of flattery. Right?” There’s an old expression: “Imitation is the highest” – or best – “form of flattery” (flattery). The “form of” something is a kind of something, a type of something. “Flattery” is when you tell another person how good they are in order to make them feel good, but often in order for the person to do you a favor or to get the person to do you a favor.
The expression “imitation is the highest form of flattery” – or “the best form of flattery” – refers to the idea that if you copy someone else, you’re not doing it because you want to steal something from him or her; you’re doing it almost as a compliment to that person, to say, “See, you’ve done such a great job, I’m going to do the same thing.” And in doing that, I am praising you in a way. I am telling you how good you are at what you did. Of course, if you are doing impressions of another person in order to make fun of that person, it is very unlikely that person will consider what you are doing “flattery.”
But back to our story. Kay says, “I’m not sure Justine would see it that way.” She doesn’t think that Justine would agree with Edison that this is a form of flattery. Kay says, “It sounds more like mockery to me. I think it’s all in the tone.” “Mockery” (mockery) comes from the verb “to mock” (mock), which means to make fun of someone in a cruel, mean way – to imitate someone in a way that makes them look bad or that makes fun of them, that we might also say “ridicules” them.
Kay is saying that Edison’s imitations and impressions are going to be interpreted by Justine as a mockery. She says, “I think it’s all in the tone” (tone). The “tone,” when referring to your voice, refers to the qualities of the voice, including whether it’s high-pitched or low-pitched, whether there is warmth, whether there is strength. It’s the particular way in which your voice sounds when you are saying something.
We all know that you can say something to someone that would make the person mad or happy depending on the tone. For example, if you said to your girlfriend, “Oh, you’re crazy,” you say it in such a way that you’re kidding or joking and your girlfriend knows it. But if you say to your girlfriend, “You’re crazy,” your girlfriend will probably have a different reaction because you’re using a different tone in your voice.
Edison says, “It’s a simple parody of how she normally addresses the staff.” A “parody” (parody) is an imitation of a person, but usually involves some sort of exaggeration in order to be funny. Normally, we think of this word “parody” as it relates to some performance on a television show or in a movie where they’re making fun of something in a way that exaggerates it.
So, for example, if a politician normally scratches his head when he talks, a parody of that perhaps would be a comedian who stands up and takes both hands and moves them up and down on the sides of his head in order to make fun of this politician. The comedian is exaggerating it. He’s trying to imitate the person in a way that would be funny. Parody doesn’t involve just physical actions – it can also be the language you use.
Edison says his impressions of Justine are “a simple parody,” or exaggeration for comic effect, “of how she normally addresses,” or talks to, “the staff” – the people who work at the company. “It’s all done in good fun. It’s not mean-spirited,” he says. “To do something in good fun” is to do something funny without being mean, without trying to hurt someone. The opposite of “in good fun” would be, in fact, “mean-spirited.” Something that is “mean-spirited” is something that is unkind or cruel, something that is funny but also not very nice.
Kay says, “Of course not,” meaning of course you’re not doing this in a mean-spirited kind of way, “but she might take it the wrong way.” “To take something the wrong way” is to understand something in the wrong way, especially in a way that makes you feel offended or angry. It means “to misinterpret” something, to take something the wrong way.
If someone says to you, “Wow, what happened to all of your hair?” Well, you might take that the wrong way. You might think the person is making fun of you because you are bald. I’m not sure what the right way to take that would be, however. Maybe there are some things you say that can only be taken one way, no matter how the person says it.
Anyway, Edison says that Justine “needs to learn to laugh at herself.” “To laugh at yourself” means to find things that you do funny, especially mistakes that you make.
Edison says, “It’s healthy for the ego.” Your “ego” (ego) is your sense of self-confidence, self-respect, how you believe yourself to be as a person. Kay says, “Whatever you say, boss. You’re always right, boss.” That’s Kay imitating someone. Edison says, “Who was that supposed to be?” Kay says, “Remember what you said about imitation being the highest form of flattery?”
Kay is obviously trying to imitate Edison and show him that sometimes doing impressions of other people are not funny and they don’t take them to be funny. They don’t take them as a form of flattery. Edison says, “That was supposed to be me? Me?!” He doesn’t think that Kay’s impression is very funny. Of course, Kay is trying to show him that making fun of other people by doing impressions of them can often be considered mean-spirited, even if you think it’s all in good fun.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Edison: [in a high-pitched woman’s voice] “I’m paying you less and working you harder. What are you complaining about?”
Kay: Ha, ha. You sound just like Justine! You really have a gift for doing impressions, but maybe we should shut the door.
Edison: Oh I’m not worried about Justine hearing me. She’s my boss, but she’s not the boss of me.
Kay: What would she say if she saw you imitating the way she walks and the gestures she makes?
Edison: We all know what they say: Imitation is the highest form of flattery. Right?
Kay: I’m not sure Justine would see it that way. It sounds more like mockery to me. I think it’s all in the tone.
Edison: It’s a simple parody of how she normally addresses the staff. It’s all done in good fun. It’s not mean-spirited.
Kay: Of course not, but she might take it the wrong way.
Edison: Then she would need to learn to laugh at herself. It’s healthy for the ego.
Kay: “Whatever you say, boss. You’re always right, boss.”
Edison: Who was that supposed to be?
Kay: Remember what you said about imitation being be the highest form of flattery . . .
Edison: That was supposed to be me? Me?!
[end of dialogue]
I have nothing to complain of when it comes to our wonderful scripts written by our wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
high-pitched – describing a voice with very high (not low or deep) sounds
* Every good horror movie needs a few high-pitched screams.
to complain – to talk about problems or the negative aspects of things, just to share one’s displeasure, without being constructive or presenting possible solutions
* Dimitri told Loren to stop complaining about her job and start looking for a new one that she’ll like better.
impression – an attempt to imitate (copy) another person’s actions, words, and behaviors, usually to entertain others
* Everyone laughed at the comedian’s impression of the Senator.
not the boss of me – a phrase used to assert one’s independence and rudely state that someone does not have authority over oneself
* You’re just my brother—you’re not the boss of me, so stop telling me what to do!
to imitate – to copy; to do what one sees, especially to do what another person is doing or to say what another person is saying
* Peter is trying to imitate the local Welsh accent, but he doesn’t sound someone from this area.
gesture – a movement made with one’s body, especially hands, to emphasize what one is saying or to express oneself without words
* Doogie is an angry driver who often makes rude gestures toward other cars on the freeway.
form of – type of; kind of
* If you were creating a new country, what form of government would you select?
flattery – a lot of praise given to make another person feel good and/or to further one’s own interests
* Do you really think that flattery will make the teacher give you a better grade?
mockery – an insincere imitation of someone or something, designed to make others laugh in a cruel, mean way
* The other children applauded for Vinnie when he won the award, but it was really a form or mockery, because none of them thought he deserved it.
tone – a description of the qualities of a voice, including its pitch (high or low), warmth, and strength
* The job applicant replied to the interviewer’s questions with a firm, assertive tone that conveyed confidence.
parody – an imitation of a person or thing that is bigger or broader than it should be, intended to be funny through exaggeration
* Wow, this book is like a parody of my teenage years!
in good fun – innocent and harmless, without trying to hurt anyone
* It was a mean joke, but he said it in good fun.
mean-spirited – unkind and cruel; inconsiderate; trying to hurt another person
* Their boss is a mean-spirited guy who never thanks them for their work and always tries to take the credit.
to take (something) the wrong way – to misinterpret something; to understand something in the wrong way, especially in a way that makes one feel offended or insulted
* Don’t take this the wrong way, but have you ever thought about getting a professional haircut instead of having your mother cut it?
to laugh at (oneself) – to find the humor in one’s own actions and mistakes; to be humble enough to not take oneself too seriously when one has done something silly or wrong
* When Sienna fell off the stage, she had to laugh at herself for her clumsiness.
ego – a person’s sense of self-respect, self-confidence, and self-worth; how important one believes one is
* Losing the game damaged his ego, but he’ll recover.
Comprehension Questions
1. Which of these verbs is most similar in meaning to “impersonate”?
a) Imitate
b) Flatter
c) Mock
2. What would happen if Justine takes it the wrong way?
a) She might misunderstand Edison’s intention.
b) She might fall in love with Justine.
c) She might begin to impersonate Edison.
Answers at bottom.
What Else Does It Mean?
gesture
The word “gesture,” in this podcast, means a movement made with one’s body, especially hands, to emphasize what one is saying or to express oneself without words: “In the U.S., a gesture formed by touching the tip of the thumb and forefinger to form a circle while holding up the other three fingers is as sign of approval or agreement, not an insult.” The word can also be used as a verb: “The student gestured to a picture to ask, ‘What’s this called in English?’” An “obscene gesture” is a very rude gesture: “Holding up your middle finger is an obscene gesture.” Finally, a “nice gesture” is something nice or kind that one does for another person: “Offering to pay for dinner was a nice gesture, don’t you think?”
tone
In this podcast, the word “tone” is a description of the qualities of a voice, including its pitch (high or low), warmth, and strength: “She was attracted to the strong, masculine tone of his voice.” The phrase “Don’t take that tone with me,” is used to strongly tell someone to speak more pleasantly and respectfully: “During the argument, he said to his daughter, ‘Don’t take that tone with me, young lady.’” The phrase “to set the tone” means to establish the mood or feel of an event or occasion: “The dean gave an excellent welcome to the new students, which set the tone for the rest of the school year.” Finally, a “ring tone” or a “busy tone” refer to the sounds that one hears when placing a call: “I tried calling your number, but I only heard a ring tone. It never transferred to voicemail.” And, “I’ve tried to call Angel several times, but all I get is the busy tone.”
Culture Note
Elvis Impersonators
American comics impersonate many different “celebrities” (famous people, especially musicians, actors, singers, and athletes), but Elvis Presley “holds a special place in the hearts of” (is a special case for) many impersonators. Elvis was a highly influential musician in the mid-1900s, and many people refer to him as “the King of Rock and Roll.”
Some impersonators focus “exclusively” (only) on looking like Elvis, “emulating” (copying with respect) his “hairdo” (style) and clothing, typically the white “pantsuit” (a single piece of clothing, like a shirt and pants that are attached to each other) with an “open collar” (exposing the neck and much of the upper chest) that Elvis is associated with. Others focus on sounding like Elvis, copying his voice, music, and way of speaking. And “still” (even more; additional) others combine both “elements” (pieces; parts) in their impersonation.
There are many competitions for Elvis impersonators, both professionals and “amateurs” (people who do something as a hobby, but not at the professional level). One of the best-known “contests” (competitions) is the Ultimate Elvis Tribute Artist Contest, which began in 2007. “Elvis tribute artists” (Elvis impersonators) participate in “preliminary rounds” (first-round competition, not yet the finals) at festivals around the world. Those who win those competitions can “advance” (go on) to the “semifinal” (almost final; nearly the last) round during Elvis Week in Memphis, Tennessee. The top 10 compete in the final round, and the winner receives the “coveted” (strongly desired) “title” (what someone may call himself or herself) of “Ultimate Elvis Tribute Artist,” a $20,000 cash prize, an opportunity to perform with others who are impersonating “music legends” (musicians who have become very famous), and more.
Comprehension Answers
1 - a
2 - a