= 1121
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,121 – Outdoor Sun Protection.
This is English as a Second Language Podcast episode 1,121. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Are you on Facebook? Hey, so am I. Go to facebook.com/eslpod and like our page. You can also, of course, go to our website at ESLPod.com and download other excellent courses in English that we offer.
This episode is a dialogue between June and Wally about making sure you protect your skin when you are outside and the sun is shining. Let’s get started.
[start of dialogue]
June: Wait! You forgot your sun hat.
Wally: I’m not wearing that hat. It looks ridiculous on me.
June: It’ll protect you from the sun’s rays. You’re too fair to be outdoors for long without protection. You don’t want to get another sunburn.
Wally: I’m wearing sunscreen. I’ll be fine.
June: This ChapStick has an SPF of 100. You’ll need that, too.
Wally: All right. Anything else?
June: Yes, these sunglasses will protect your eyes from the sun’s harmful ultraviolet rays.
Wally: Okay, I’m leaving now. I’m surprised you didn’t get me some protective clothing. My arms and legs are exposed.
June: I’m glad you reminded me. Here’s a sun cape. It’s made of a breathable fabric. Make sure you wear it every minute you’re outside. Promise?
Wally: [sigh]
[end of dialogue]
Here comes the sun
Here comes the sun, and I said
It’s alright . . .
Oh, sorry. On this episode, we listen to June and Wally talking about the fascinating subject of sun protection. Well, it’s not fascinating. It’s not really that interesting, but it is important and so we’re going to talk about it. June says to Wally, “Wait, you forgot your sun hat.” A “sun hat” is a large hat that sits on your head – where all hats go - but has what we call a large “brim” (brim). That’s the part of the hat that sticks straight out, and in this case would help protect your face from the sun so that you don’t get the sun coming down directly on your face, if you will.
Wally says, “I’m not wearing that hat. It looks ridiculous on me.” Wally means it looks funny. It looks stupid. It looks weird. June, however, says, “It’ll protect you from the sun’s rays.” The “rays” (rays) of the sun are the lines of light, I guess we could call them, that come from the sun. June says, “You’re too fair to be outdoors for long without protection. You don’t want to get another sunburn.” We talk about people’s skin being “fair” when it is, like my skin, very white and gets sunburned very easily.
“Sunburn” (sunburn) is when you are out in the sun too much and your skin turns red, and it can be very painful. June is telling Wally that he’s too fair to be outdoors for long without protection. In other words, his skin is too light. It’s too white. He will get sunburned unless he has some protection. The word “outdoors” (outdoors) – one word – refers to the opposite of being inside. You are either indoors or outdoors. You’re either in a building or a house, or you’re outside of a building or a house. I guess you could be in a car, too.
Wally is “too fair to be outdoors for long without protection,” June says. “Protection” here would be something that prevents you from getting hurt – in this case, something that prevents you from getting a sunburn. Wally says, “I’m wearing sunscreen. I’ll be fine.” “Sunscreen” (sunscreen) – one word – is a cream, lotion, or spray that you apply to your skin that has special chemicals that will protect your skin, will prevent the skin from getting sunburned even if you are outside in the sun.
Now, sunscreens have different ratings depending on how strong they are, how much protection they provide. This rating system is called the “SPF” – the “Sun Protection Factor,” or indicator. The highest, or one of the highest, SPF numbers you can get is 100. Someone like me, who has very fair skin, has to use a very high SPF sunscreen. June is worried more than just about Wally’s skin. She’s also worried about his lips, which can get sunburned as well.
That’s why she says, “This ChapStick has an SPF of 100. You’ll need that, too.” “ChapStick” (chapstick) is actually the name of a kind of lip covering, or lip “balm” (balm), to protect your lips from getting dry, or in this case, from getting sunburned. However, just like the word “Kleenex,” which is also the name of a kind of tissue, the word “ChapStick” is now often used to refer to any kind of lip balm – the way in some countries people talk about a “coca” when they are referring to any kind of soft drink.
Wally says, “All right. Anything else?” June says, “Yes, these sunglasses will protect your eyes from the sun’s harmful ultraviolet rays.” “Sunglasses” are special glasses that have dark lenses, dark pieces of glass or plastic that cover your eyes to make sure that you can see more easily when it is very sunny out and also that protect your eyes – at least, some sunglasses do. The sun has different kinds of light, different kinds of rays. One of them is “ultraviolet rays.” Ultraviolet rays or “ultraviolet light” is a kind of light that you can’t see – at least, human beings can’t see – but it can damage or hurt your skin and your eyes.
Wally says, “Okay, I’m leaving now.” He’s not very happy that June, who we guess is his mother, is telling him to do all of these things. He just wants to leave. He makes a little joke. He says, “I’m surprised you didn’t get me some protective clothing.” “Protective clothing” would be special clothing to protect you from the light of the sun. Wally says, “My arms and legs are exposed.” “To be exposed” (exposed) means not to be protected or hidden or covered.
June, however, responds, “I’m glad you reminded me. Here’s a sun cape.” A “cape” (cape) is a large piece of fabric that you put around your neck and you tie it to your neck. It covers your shoulders. You can think of the famous superhero, Superman. Superman has a cape that he wears, or at least I’m told he wears it. So, June has gotten Wally this special cape, which of course would look ridiculous, especially on a man, unless you’re Superman.
June also says the cape is “made of breathable fabric.” “Fabric” (fabric) refers to the material that clothing is made out of. “Breathable (breathable) fabric,” would be fabric that allows air to pass through easily so that you don’t sweat or get too hot. June wants Wally to wear this cape. She says, “Make sure you wear it every minute you’re outside. Promise?” The verb “to promise” (promise) means to agree that you will do something – to say that you will do it, and if you don’t do it, you will accept some sort of consequence.
When June says, “Promise?” she means, “Do you promise to do these things?” Wally doesn’t respond. He just sighs. He goes [sigh], which of course means he’s frustrated or angry with his mother.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
June: Wait! You forgot your sun hat.
Wally: I’m not wearing that hat. It looks ridiculous on me.
June: It’ll protect you from the sun’s rays. You’re too fair to be outdoors for long without protection. You don’t want to get another sunburn.
Wally: I’m wearing sunscreen. I’ll be fine.
June: This ChapStick has an SPF of 100. You’ll need that, too.
Wally: All right. Anything else?
June: Yes, these sunglasses will protect your eyes from the sun’s harmful ultraviolet rays.
Wally: Okay, I’m leaving now. I’m surprised you didn’t get me some protective clothing. My arms and legs are exposed.
June: I’m glad you reminded me. Here’s a sun cape. It’s made of a breathable fabric. Make sure you wear it every minute you’re outside. Promise?
Wally: [sigh]
[end of dialogue]
Our scriptwriter always wears sunscreen, and you should too. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
sun hat – a large hat that extends from the head on all sides in a large circle, used to protect one’s eyes and skin from the sun
* This sun hat is good for walking on the beach or working in the garden, but it gets in the way for more active activities, like playing volleyball.
ray – one of many lines of light that come from the sun
* If you place the couch in front of the window, the sun’s rays might make the fabric fade over time.
fair – light-colored; with pale skin, blond or red hair, and blue or green eyes
* Peter’s skin is too fair for him to wear bright colors.
outdoors – outside; not inside a building; in nature
* They want to have their wedding outdoors, but they’re worried it might rain.
protection – something that prevents injury, illness, or death; something that keeps someone safe in a dangerous situation
* A hardhat and protective glasses offer protection at a construction site.
sunburn – painful, red, and peeling skin caused by too much exposure to sunshine
* She had a sunburn on her face, arms, and hands.
sunscreen – a cream, lotion, or spray applied to the skin to provide protection from the sun and prevent sunburns
* Can you help me put sunscreen on my back on the skin around the swimsuit?
chapstick – a small tube of a cream or ointment rubbed over the lips to provide moisture and perhaps protection from the sun
* In cold winter months, using chapstick can prevent lips from getting dry and cracked.
SPF – sun protection factor; a measurement of how much protection something provides against damage from the sun
* Haileys’ daily moisturizer has an SPF 15, but when she plans to spend time outdoors, she uses a sunscreen with SPF 45.
sunglasses – eyeglasses with dark lenses (pieces of glass or plastic) to make it easier to see in bright light and to provide protection against damage from the sun
* Can you take off your sunglasses while we’re talking? I want to be able to see your eyes.
ultraviolet – a type of light and radiation produced by the sun that people can’t see, capable of causing cancer
* Ultraviolet light can cause cancer, but it can also be used to sanitize fruits and vegetables.
exposed – put in contact with something; not hidden or protected from something
* Some of the factory workers were exposed to dangerous chemicals in doing their jobs.
cape – cloak; a large piece of fabric attached to strings tied around the neck, so that the fabric flows over the person’s back
* Can Superman fly without his cape?
breathable fabric – a type of cloth that allows air to pass through easily, often used for exercise clothing
* To play soccer in the rain, you’ll need a rain jacket made of breathable fabric, or else you’ll get too hot and sweaty.
to promise – to state that one will do something, or to state that something will happen, so that one is held accountable for it
* While you’re overseas on business, promise you’ll call me every day.
Comprehension Questions
1. Which of these things does not prevent sunburn?
a) Sunscreen
b) Chapstick
c) Sunglasses
2. What does June mean when she says, “You’re too fair to be outdoors for long”?
a) Wally is too kind and gentle for life outdoors.
b) Wally’s skin is too pale to spend much time in the sunshine.
c) Wally isn’t strong enough to tolerate exercising outdoors.
Answers at bottom.
What Else Does It Mean?
fair
The word “fair,” in this podcast, means light-colored, with pale skin, blond or red hair, and blue or green eyes: “Most people from the northern regions are fair, with blond hair and blue eyes.” The word “fair” also means just or treating everyone equally: “It isn’t fair to always say ‘yes’ to one child while always saying ‘no’ to another one.” The phrase “fair share” describes the part that one receives and that one deserves: “As an original investor in the company, Bianca is demanding her fair share of the profits.” The phrase “a fair number of (something)” means a lot of something: “She has received a fair number of job offers, but she hasn’t accepted any of them yet.” Finally, as a noun, a “fair” is an outdoor festival, especially with an agricultural or farming theme: “Hank’s pig won first place at the county fair!”
cape
In this podcast, the word “cape” means a cloak, or a large piece of fabric attached to strings tied around the neck, so that the fabric flows over the person’s back: “The magician wore a long black cape throughout the show.” When talking about geography, a “cape” is a piece of land surrounded by water on three sides: “They went to the cape for the weekend so they could see the sun rise and set over the ocean.” “Cape Canaveral” is the area in Florida where U.S. space shuttles and satellites are launched or sent into outer space: “Hundreds of people went to Cape Canaveral to see the satellite lift off into space.” Finally, “Cape Cod” is a popular vacation destination in southern Massachusetts.
Culture Note
Sunless Tanning Options
Most Americans believe that a “tan” (a brown skin color from exposure to the sun) is attractive, “perhaps” (maybe) because they “associate it with” (think about it in connect with) someone who has energy and spends time outdoors. In the past, people would “sunbathe” (spend time lying in the sun to change the color of one’s skin) or go to “tanning salons” (businesses with special equipment that shines ultraviolet light on the body to simulate sunshine) to get a “sun-kissed look” (the appearance of someone who has spent time in the sun). But in recent years, people have become increasingly “aware” (with knowledge of something) of the damaging effects of the sun. So many people have begun to “turn to” (rely on) sunless tanning options.
Some sunless tanning options are creams, lotions, and other “cosmetics” (make-up and beauty products) that wash off. They can be applied to the skin to make it appear darker, but they last only until the skin is washed. “Tinted” (lightly colored) “moisturizers” (creams that help the skin be moist) and “bronzers” (powders and cream that add a brown or almost golden color to the skin) are popular products.
Other people want a “longer-term” (lasting longer) solution and prefer to get a “spray tan.” They go into a tanning salon, remove their clothing, and is sprayed with a liquid that colors the skin temporarily. A typical spray tan lasts for a few weeks, depending on one’s level of physical activity and “frequency” (how often one does something) of bathing.
Comprehension Answers
1 - c
2 - b