= 1124
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,124 – Hiding Money Offshore.
This is English as a Second Language Podcast episode 1,124. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com and check out our Special Courses in Business and Daily English in our ESL Podcast Store.
This episode is a dialogue between Sabrina and Luis about hiding your money so the government doesn’t find it. Let’s get started.
[start of dialogue]
Sabrina: Wait! Don’t deposit that money into our regular bank account. I’ll take care of it.
Luis: Okay, but why?
Sabrina: I’ve come up with a way for us to avoid paying so much in taxes each year. I’ve opened an offshore account in the Crook Islands. We can funnel our money into that account and it’ll be untraceable.
Luis: But that’s tax evasion.
Sabrina: The banks in the Crook Islands have ways of covering up the paper trail so no one will be the wiser.
Luis: That doesn’t make it legal.
Sabrina: They haven’t caught us yet.
Luis: You mean you’ve already started putting money into that account?
Sabrina: I’ve been depositing money into it for nearly a year.
Luis: And when were you going to tell me?
Sabrina: I’m telling you now. Trust me. These tax havens are very popular with the rich. We’re just taking a page from their book on how to save money.
Luis: We’re going to get caught. We should come clean now.
Sabrina: That’s why I didn’t tell you before! I knew you’d make a fuss about it.
Luis: And you were right. We need to quietly close the account and bring the money back.
Sabrina: Then we’ll have to pay taxes on it and maybe even a penalty, more than we would’ve had to pay in taxes originally.
Luis: Right, and that’s called poetic justice.
[end of dialogue]
Sabrina says to Luis, “Wait! Don’t deposit that money into our regular bank account. I’ll take care of it.” “To deposit” (deposit) money into a bank account means to put money into your account – to give the bank money that the bank will keep for you until you need it. A “bank account” (account) is basically an agreement or arrangement that you have with the bank, where you can give them money and they will hold it for you, or at least give it back to you when you want it.
The bank doesn’t actually keep all the money people give it. It, of course, lends the money to other people; it gives loans to people and then makes money on your money. Well, in our dialogue, Sabrina doesn’t want Luis to deposit a certain amount of money into their regular or normal bank account. Luis is confused. He says, “Okay, but why?” Sabrina says, “I’ve come up with a way,” meaning I have found or invented a way, “for us to avoid paying so much in taxes each year.”
“Taxes” (taxes) is the money you pay to the government. Usually it’s some percentage of your income – how much you make, how much money you earn each year. California, for example, has some of the highest taxes because not only does the national government make you pay taxes but most states also make you pay taxes. So, if you live in California, you pay relatively high taxes. Anyway, enough complaining about California.
Sabrina says, “I’ve opened an offshore account in the Crook Islands.” An “offshore (offshore) account” is one that is in another country, not the country you live in. It is possible to put your money in banks in other countries so that the government doesn’t know how much money you really have. Well, that’s what Sabrina’s idea is. She’s actually opened an offshore account in a fictional, imaginary place called the “Crook Islands.” The word “crook” (crook) is used in English to mean a thief, someone who steals something. So it’s a little joke here in our dialogue that Sabrina has put her money in a bank in the Crook Islands.
Sabrina continues, “We can funnel our money into that account and it’ll be untraceable.” “To funnel” (funnel) money is to send something to one place or one person even when it comes from different places. You could take the money that you make, plus your wife makes, plus your friends make and you could funnel it into a single account. You would put it all into one account. A “funnel” (funnel) as a noun is something you use to pour liquid into a container so that all the liquid goes into it. It’s like a cone, basically, if you remember your high school geometry.
Sabrina says that putting the money into this offshore account will make it “untraceable.” “Traceable” (traceable) means you can figure out where something comes from. “Untraceable” would mean that you could not figure out where something came from. Well, if your money is “untraceable,” it means the government can’t find it, can’t figure out what happened to it. Luis objects. He’s not sure this is a good idea. He says, “That’s a tax evasion.” “Tax evasion” (evasion) is illegally trying to avoid paying taxes to the government – by hiding your money, for example.
Don’t confuse tax evasion with “tax avoidance” (avoidance). “Tax avoidance” is when you legally try to pay the minimum amount of taxes possible. “Tax evasion” is when you illegally try to do the same thing. Sabrina says, “The banks in the Crook Islands have ways of covering up the paper trail so no one will be the wiser.” The phrasal verb “to cover up” means to hide something so that it cannot be seen, especially something illegal – to make sure that no one discovers illegal activities.
One of the problems very common in American politics is that politicians will do something wrong – something dumb, but something that is not illegal. However, because they don’t want anyone to know about it, they try to cover it up, and often that is illegal, especially if the government starts asking questions and you lie to the government. Well, the lying is illegal, and that is often what is a problem for some American politicians. Anyway, enough of America’s problems. Back to our dialogue.
Sabrina says that these banks in the Crook Islands have ways of covering up the “paper trail” (trail). The term “paper trail” refers to documents and other written evidence that shows where someone has been and what that person has done. Nowadays we don’t use paper as much. I guess you could call it the “electronic trail,” but we still call it the “paper trail.” It means evidence of things that you have done that, say, the police can discover and determine what exactly you did.
Sabrina says these banks cover up the paper trail “so no one will be the wiser” (wiser). “To be wise” (wise) means to be smart, to be knowledgeable. “No one will be the wiser” is a phrase meaning no one will find out what happened. No one will be able to discover the truth. Luis says, “That doesn’t make it legal.” Sabrina says, “They,” meaning the government, “haven’t caught us yet.” Luis says, “You mean you’ve already started putting money into that account?”
Sabrina responds, “I’ve been depositing money into it for nearly a year.” Luis says, “And when were you going to tell me?” So, Luis says this plan that Sabrina has is illegal. But Sabrina says, “Well, they haven’t caught us yet,” meaning they haven’t found out what we have been doing. Luis is surprised that Sabrina has already started putting money into this illegal account, and he asks, “When were you going to tell me?”
Sabrina says, “I’m telling you now. Trust me. These tax havens are very popular with the rich.” A “tax haven” (haven) is a place where you can put your money, a country where you can put your money and you don’t have to pay taxes on it, or you pay very little in tax. Sabrina says, “We are just taking a page from their book on how to save money.” The expression “to take a page from someone’s book” means to study what other people have done and do the same thing – to copy what someone else is doing.
Luis says, “We’re going to get caught.” “To get caught” means to have someone find out about something that you did wrong. Luis says, “We should come clean now.” “To come clean” means to admit what you did wrong, to say that you have done something illegal or wrong, to tell someone else. Sabrina says, “That’s why I didn’t tell you before. I knew you’d make a fuss about it.” “To make a fuss” (fuss) is to complain about something or to become angry about something. It’s to not react calmly, to get all excited about something in a bad way.
Luis says, “And you were right,” meaning yes, I am making a fuss about this; I am getting angry and complaining about it. He says, “We need to quietly close the account and bring the money back,” meaning take the money out of the bank in the Crook Islands and bring it back to the United States. Sabrina says, however, “Then we’ll have to pay taxes on it and maybe even a penalty, more than we would have had to pay in taxes originally.”
Sabrina is complaining that if they bring this money back to the United States, they may have to pay taxes on it plus what’s called a “penalty” (penalty). A penalty is a punishment for breaking a rule or a law. Sabrina complains this amount of money they will have to pay will be more than what they would have had to pay in taxes originally if they had not tried to hide their money.
Luis says, “Right,” meaning that’s correct, “and that’s called poetic justice.” The phrase “poetic (poetic) justice” refers to a negative consequence, a bad result that happens from something you do that is an appropriate punishment for your bad actions. So in this case, the couple – Sabrina and Luis – may have to pay more in taxes by bringing the money back than they would have had to pay if they had just paid their taxes legally here in the United States. Luis calls that “poetic justice” because they deserve it. It’s a deserved outcome, an appropriate punishment for what they did wrong.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sabrina: Wait! Don’t deposit that money into our regular bank account. I’ll take care of it.
Luis: Okay, but why?
Sabrina: I’ve come up with a way for us to avoid paying so much in taxes each year. I’ve opened an offshore account in the Crook Islands. We can funnel our money into that account and it’ll be untraceable.
Luis: But that’s tax evasion.
Sabrina: The banks in the Crook Islands have ways of covering up the paper trail so no one will be the wiser.
Luis: That doesn’t make it legal.
Sabrina: They haven’t caught us yet.
Luis: You mean you’ve already started putting money into that account?
Sabrina: I’ve been depositing money into it for nearly a year.
Luis: And when were you going to tell me?
Sabrina: I’m telling you now. Trust me. These tax havens are very popular with the rich. We’re just taking a page from their book on how to save money.
Luis: We’re going to get caught. We should come clean now.
Sabrina: That’s why I didn’t tell you before! I knew you’d make a fuss about it.
Luis: And you were right. We need to quietly close the account and bring the money back.
Sabrina: Then we’ll have to pay taxes on it and maybe even a penalty, more than we would’ve had to pay in taxes originally.
Luis: Right, and that’s called poetic justice.
[end of dialogue]
Many thanks to our wonderful scriptwriter, Dr. Lucy Tse, for her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to deposit – to put money into a bank account; to place funds in a bank account
* Does your employer deposit your paychecks electronically, or do you have to take a printed check into the bank?
bank account – an arrangement where a person or a business is the owner of money held by the bank, but is allowed to withdraw (take out) or deposit (put in) money as desired
* We use this bank account for day-to-day expenses, but we use a different bank account for major expenses, like home improvements and tax payments.
taxes – money paid to the government, usually calculated as a percentage of one’s income (money one receives for work) or assets (the things one owns)
* We thought our sales revenues were pretty good, but after paying expenses and taxes, very little was left over as profit.
offshore – overseas; in another country
* A lot of American companies are using offshore software development services, because they’re cheaper than the same services in the United States.
to funnel – to send something to a particular place or person, especially when it comes from many different places
* Let’s funnel all this paperwork to my administrative assistant and he’ll take care of all of it.
untraceable – with unknown origins; with the origins hidden so that people cannot determine where something has come from
* So many people have become sick from the disease so quickly that the source of it may be untraceable.
tax evasion – the practice of avoiding paying taxes by breaking the law or finding ways to work around the law
* Paying workers in cash can lead to tax evasion, because workers are able to hide those payments from the government.
to cover up – to hide something so that it cannot be seen; to try and prevent others from finding out about something bad that one has done
* The criminals did a good job of covering up their work. They didn’t leave any fingerprints at the scene of the crime.
paper trail – documents and other written evidence that shows where someone has been and what that person has done, allowing other people to find and follow that person
* The auditor’s job is to the follow the paper trail and determine whether the organization is spending the funds in appropriate ways.
no one will be the wiser – a phrase meaning that nobody will be aware of what one has done, or that one will be able to fool everyone or hide the truth from everyone
* It is the perfect lie. We won’t get in trouble, and no one will be the wiser.
tax havens – a place where one pays little or no taxes, especially when funds are kept there to avoid paying higher taxes in one’s own country
* The government is enacting laws to prevent large companies from using tax havens to reduce the amount of tax they must pay.
to take a page from (one’s) book – to copy another person’s actions; to study and learn from what another person is doing and then do the same thing
* We took a page from your book and hired a professional painter, rather than try to paint the house ourselves.
to get caught – to have one’s bad or illegal actions be discovered or revealed when one wanted to hide them; to be found out
* What happens if a student gets caught cheating?
to come clean – to admit one’s bad, wrong, or illegal actions; to truthfully state that one has done something wrong or broken the law
* Alberto felt guilty about what he had done, and when he finally came clean, he felt a sense of relief.
to make a fuss – to protest loudly and complain or become angry; to make something into a dramatic situation; to not react calmly or passively
* I don’t understand why you’re making a fuss about this. Just fix the problem and let’s move on.
penalty – a punishment for breaking a rule or law
* What is the maximum penalty for murder?
poetic justice – a deserved outcome; a negative consequence that is appropriate punishment for one’s bad actions
* When Jacque got fired, his employees thought it was poetic justice because he had fired so many of their co-workers in the past two years.
Comprehension Questions
1. What is Luis’s objection to Sabrina’s plan?
a) He thinks the banks on Crook Islands are not trustworthy.
b) He thinks it will be inconvenient to manage an international bank account.
c) He thinks they will get in trouble for not paying taxes.
2. What does Sabrina mean when she says, “no one will be the wiser”?
a) No one else has thought of her idea.
b) No one will realize what they have done.
c) No one will copy her actions.
Answers at bottom.
What Else Does It Mean?
paper trail
The phrase “paper trail,” in this podcast, means documents and other written evidence that shows where someone has been and what that person has done, allowing other people to find and follow that person: “Investigators followed an elaborate paper trail to identify the leader of the gang.” The phrase “to blaze a trail” means to create a trail or path that other people will follow: “The boy scouts spent last Saturday blazing a trail through the overgrown forest.” Or, “Early programmers blazed a trail for many of today’s most successful software companies.” Finally, the phrase “to be on the trail of (someone or something)” means to be very close to the point at which one will find or discover secret or hidden information: “The police are on the trail of the art thieves.”
to come clean
In this podcast, the phrase “to come clean” means to admit one’s bad, wrong, or illegal actions, or to truthfully state that one has done something wrong or broken the law: “After living with the lie for most of her life, Janet thought that life would be so much easier if she could just come clean and tell the truth.” The phrase “clean living” describes a healthy lifestyle: “Karina believes in clean living and never smokes, drinks alcohol, or eats junk food.” Finally, the phrase “a clean break” means a sudden and complete separation from someone or something: “They dated for four years, but then got in a fight and made a clean break, never speaking to each other again.”
Culture Note
Offshore Amnesty Programs
A “tax amnesty program” is a period of time when “taxpayers” (people who pay taxes, or who should pay taxes) are allowed to admit to a previous instance of tax evasion and pay a penalty that is less than what it normally is or should be. For instance, the taxpayer may be allowed to “disclose” (share information about) previously “unreported income” (money received that was not reported to the government) and pay the taxes owed on it without having to pay “interest” (a percentage of money calculated every month or year based on the amount owed) or “fines” (money that must be paid as a punishment).
The IRS offers “offshore amnesty programs” specifically for taxpayers who have hidden money in “offshore accounts” (bank accounts in other countries). The Offshore Voluntary Disclosure Program was offered in 2009 and 2011, and then as an “open-ended” (without an ending date; continuing until further notice) program in January 2012. In 2012, the IRS “commissioner” (head or leader of the agency) “announced” (stated) that the IRS had “collected” (arranged to received) more than five billion dollars in “back taxes” (taxes that should have been paid in the past, but weren’t) as a result of “voluntary” (according to a person’s will or desire, without being forced to do something) “disclosures” (telling others about secret information).
Why do taxpayers voluntarily disclose their offshore “holdings” (assets; things one owns that has value or worth)? Because the penalties they pay for voluntarily disclosure are “significantly” (a lot) less than the penalties they would pay if their “wrongdoings” (the bad things people have done) are discovered and “prosecuted” (taken to court) by the IRS.
Comprehension Answers
1 - c
2 - b