= 1132
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,132 – Defending Your Ideas at Work.
This is English as a Second Language Podcast episode 1,132. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode. Are you on Facebook? So are we. Go to facebook.com/eslpod.
In this episode, we’re going to talk about defending your ideas, or giving reasons for your ideas, when you’re at work. Let’s get started.
[start of dialogue]
Monica: That’s why I don’t think it’s doable. We should consider other ideas.
. . .
That was Monica. She’s my co-worker and my nemesis. She criticizes all of my ideas, but I’ve learned that the best defense is to not get defensive.
. . .
Kazuya: I appreciate your feedback. I understand your reservations, but let me show you these figures I’ve worked up, which I believe will address your concerns.
. . .
I knew Monica would attack my ideas, so I had come prepared.
. . .
Monica: That’s all very impressive, but I still think we need to consider other options.
. . .
Unfortunately, when Monica digs in her heels, I know that the only thing to do is to placate her. That plus a delaying tactic usually works.
. . .
Kazuya: Your comments have given me a lot to think about. We’re running short on time and we want to get to the other topics for discussion, so let’s come back to it next week.
. . .
Luckily, I know something else about Monica: She has a short attention span. By next week, she’ll be on to her next victim!
[end of dialogue]
We hear in this episode the voices of two different people at work. In addition, we hear comments from one of those people – Kazuya. The story begins with Monica saying, “That’s why I don’t think it’s doable. We should consider other ideas.” Now, Monica is talking to Kazuya, and Kazuya is going to talk to us, if you will, directly about the way that Monica is talking to him.
Monica says that something that she and Kazuya are talking about is not doable. “Doable” (doable) comes from combining two words – “able” and “do.” Something that is “doable” is something that you can or are able to do. Another word we might use here is “feasible” (feasible). Something that is doable is something that can be done, something that is not too difficult.
Monica is telling Kazuya that whatever idea he has is not doable. Then we hear Kazuya giving his commentary, his view of what Monica is saying. He says, “That was Monica. She’s my co-worker and my nemesis.” A “nemesis” (nemesis) is an enemy. It’s someone whom you can’t beat or win against, someone who creates problems for you. Kazuya is probably using this word somewhat jokingly. Normally we don’t describe people at work as our enemies, but that’s how Kazuya is describing Monica.
He says, “She criticizes all of my ideas, but I’ve learned that the best defense is not to get defensive.” “To criticize” someone is to say that his idea has problems, or the things that he is doing are wrong or perhaps simply not good enough, not of a high enough quality. Kazuya says that Monica always criticizes his ideas. She says his ideas aren’t good enough.
Kazuya says that he’s learned that “the best defense is not to get defensive.” “Defense” (defense) are things you do to protect yourself or to stop someone who is competing against you from winning. If you think of, say, a football game – an American football game – one side has the ball. They’re the offense. The other side is trying to stop them from moving down the field. They’re the defense. Most sports that have teams have offense and defense, or at least the teams are playing offense or defense during different parts of the game.
Kazuya says, “The best defense is not to get defensive.” “To get defensive” (defensive) is to be worried about someone else criticizing you and to try to explain why something isn’t your fault. Someone who is defensive often thinks that other people are criticizing him, and so he says things to make sure that people don’t think something is his fault.
Kazuya says to Monica, “I appreciate your feedback.” “Feedback” (feedback) is information that someone or something gives you to tell you how well you are doing something or whether other people like it. If you write an essay at school, or a long paper, and you give it to the professor, the professor may give you feedback on your paper. Notice we use the preposition “on” – you get feedback “on” something. The professor may say, “Oh, that was a great paper,” or he might say, “That was a terrible paper.” That’s usually what happened to me.
Kazuya continues, “I understand your reservations, but let me show you these figures I’ve worked up, which I believe will address your concerns.” The word “reservation” is used when you have an appointment at a certain restaurant or when you are going to stay in a certain hotel, but we also use the word “reservation” to mean “hesitation” – reasons for not wanting to do something. If someone says, “I have reservations about going on this trip,” she means, “I have doubts about it” – there are reasons why I don’t think it’s a good idea.
Kazuya says he understands Monica’s reservations. “But,” he says, “let me show you these figures I’ve worked up.” The word “figures” (figures) here means numbers, calculations. You added or subtracted or multiplied something and it gives you some information that’s important. “To work up” something or “to work something up” is a phrasal verb meaning to create or develop something. It could also mean to calculate some figures, as is the case in our story here. “To work something up” usually means to present what we call a “first draft” (draft) of something.
If you are working on the design of a website, you may work up some examples to show your client, your customer, so that that person can look at it and give you feedback on it. You see? It all works together. Kazuya says that the figures that he’s worked up will address Monica’s concerns. “To address (address) someone’s concerns” means to discuss or handle something, to take care of the particular problem. So, in this case, Kazuya will show Monica something that Monica can look at and see that Kazuya’s idea is a good one.
Kazuya then says to us, not to Monica, “I knew Monica would attack my ideas, so I had come prepared.” Monica says, “That’s all very impressive, but I still think we need to consider other options.” Monica is saying that what Kazuya did is very interesting, even something that is very good, but she still thinks that the company or the group needs to think about other possibilities other than what Kazuya said. That’s why Kazuya says to us, “Unfortunately, when Monica digs in her heels, I know the only thing to do is to placate her.”
The expression “to dig in your heels” (heels) means to become very stubborn, to refuse to change your opinion or decision even though other people want you to. The “heel” is the bottom back part of a shoe, and “to dig” means to create a little hole in the ground. You can imagine someone who digs in his heels outside – say, in the ground. He would be trying to prevent someone from moving him from his position. That’s where we get this expression “to dig in your heels.” Once again, it means to become very stubborn and refuse to change your opinion or decision. That’s how Kazuya describes Monica.
He says when this happens, when she digs in her heels, “the only thing to do is to placate her.” “To placate” (placate) means to make another person feel less angry or less mad by addressing his needs or addressing his concerns even though you think it really shouldn’t be necessary. If you come home late from work and you didn’t call your wife, you may need to placate her because she will be very angry at you. You need to say things that will make her less angry at you, and if you don’t know what to say, well, you probably won’t be married for very long.
Kazuya says that placating Monica is a good idea. “Plus,” he says, “a delaying tactic usually works.” “To delay” (delay) something is to not do it when you planned on doing it – to do it at a later time, to postpone it. We might also say a “tactic” (tactic) is a strategy, an approach, the way you do something. So, a “delaying tactic” is something you do to make something happen later than when you had planned on doing it or than when it should have been done. Kazuya is going to use a delaying tactic which we learn about in the next sentence.
He says to Monica, “Your comments have given me a lot to think about. We’re running short on time.” “To run short on time” means that you don’t have very much time left in a meeting, for example. He says, “We want to get to the other topics for discussion, so let’s come back to it next week.” Kazuya is suggesting that they stop talking about this topic right now – Kazuya’s ideas – and go on to something else so they can talk about it again the following week. That’s a delaying tactic. He’s making things last longer than they would have otherwise because he thinks that will help in getting his ideas approved by Monica.
Then Kazuya says at the end, “Luckily,” fortunately, “I know something about Monica. She has a short attention span.” Your “attention span” (span) is how long you can concentrate on one topic, how long you can focus on something without thinking about anything else. If you have a short attention span, you can’t focus on something for very long. We could say you have a long attention span, though usually the phrase you will hear most often is “short attention span.”
Kazuya concludes, “By next week, she’ll be on to her next victim.” A “victim” (victim) is a person who suffers from some problem or action. It’s a person who’s been hurt by something or someone. We can talk about “victims of crime” – people who have been hurt or injured in some way by another person. Someone may have stolen something from him or even killed him. We would call someone who has been killed a “murder victim.”
Well, we’re not talking about murder here – what Kazuya is saying is that by waiting till next week to talk about his ideas with Monica, Monica will have forgotten about this idea and will have gone “on to,” or put her focus or attention on, someone else in the office she doesn’t like or doesn’t agree with. That’s what Kazuya means by “her next victim” – someone else in the office that she can attack or criticize.
Now let’s listen to the dialogue (or the story) at a native rate of speech.
[start of dialogue]
Monica: That’s why I don’t think it’s doable. We should consider other ideas.
. . .
That was Monica. She’s my co-worker and my nemesis. She criticizes all of my ideas, but I’ve learned that the best defense is to not get defensive.
. . .
Kazuya: I appreciate your feedback. I understand your reservations, but let me show you these figures I’ve worked up, which I believe will address your concerns.
. . .
I knew Monica would attack my ideas, so I had come prepared.
. . .
Monica: That’s all very impressive, but I still think we need to consider other options.
. . .
Unfortunately, when Monica digs in her heels, I know that the only thing to do is to placate her. That plus a delaying tactic usually works.
. . .
Kazuya: Your comments have given me a lot to think about. We’re running short on time and we want to get to the other topics for discussion, so let’s come back to it next week.
. . .
Luckily, I know something else about Monica: She has a short attention span. By next week, she’ll be on to her next victim!
[end of dialogue]
The scripts from our wonderful scriptwriter always address your needs in improving your English – at least, we hope they do. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
doable – feasible; something that can be done; something that is not too difficult, challenging, or impossible
* My plane lands at 1:00 p.m., so it’s not doable to hold the meeting at 1:30.
nemesis – enemy; someone whom one cannot beat or outcompete; someone who creates problems for another person
* Growing up, the two brothers always viewed each other as their nemesis, but now that they’re adults, they’re very close.
to criticize – to say that something is not good enough or that it has problems; to be critical of something; to point out the disadvantages or negative aspects of something
* A lot of people are criticizing the company’s expansion plans, saying that it would be better for the company to remain small.
defense – a strategy or actions for protecting oneself and not letting another person or team win an advantage
* Yes, the project was terrible, but in her defense, it wasn’t her idea. She was just implementing it.
defensive – anxious to avoid criticism and quickly explain why something isn’t one’s fault
* Jerry gets very defensive when someone criticizes his writing style.
feedback – input; information about how good something is or whether others like it
* Please fill out the evaluation form. We’ll use your feedback to continue improving our conferences in the future.
reservation – hesitation; a reason for not wanting to do something, or for hesitating before deciding to do something
* Is it normal to have some reservations about getting married?
figures – numbers; calculations
* Some of the figures were wrong, but overall, he seems to understand the formulas.
to worked (something) up – to create, develop, or calculate something, but usually a first draft, without much revision
* Please show us the ads you’ve worked up so far, even though they aren’t finished.
to address – to discuss or deal with something; to handle something; to speak directly about a particular problem or situation
* Customer service representatives must be trained to address many types of complaints.
to dig in (one’s) heels – to become very stubborn and refuse to change one’s opinion or decision, even though other people would like one to
* The cashier dug in his heels and refused to give the customer a refund after the customer became angry and started shouting.
to placate – to do something that makes another person feel less mad or angry, and meets his or her needs or addresses his or her concerns, even though one thinks it should not be necessary
* The politician tried to placate the reporters by giving them more detailed answers.
delaying tactic – a strategy used to make something happen later than it normally would; something that one does to gain more time before something else happens
* We tried to distract the important visitors with a tour of the office as a delaying tactic until the person they had come to meet returned to the office.
attention span – how long someone can concentrate on a particular topic or thing without becoming distracted and beginning to think about something else
* Most audiences have a very short attention span, so professional speakers are taught to keep their speeches brief.
victim – a person who suffers from a crime, problem, or action; the person who is hurt by something or someone
* Sometimes victims don’t want to go to court because they are afraid of the person who hurt them.
Comprehension Questions
1. What does Kazuya mean when he says, “I understand your reservations”?
a) He understands that scheduling can be difficult.
b) He is familiar with Monica’s education and experience.
c) He understands that she has reasons for not agreeing with him.
2. What does Monica do when she digs in her heels?
a) She dresses very nicely.
b) She walks very slowly.
c) She is very stubborn.
Answers at bottom.
What Else Does It Mean?
defense
The word “defense,” in this podcast, means a strategy or actions for protecting oneself and not letting another person or team win an advantage: “The company’s best defense against new competitors is to continue to provide high-quality products at a low price.” When talking about sports, “defense” refers to the players and strategies used to prevent the other team from scoring points: “Both teams had good offense, but weak defense, so it was a high-scoring game.” When talking about countries and/or the military, “defense” refers to efforts to protect people from an attack and to fight back when attacked: “Any decrease in military spending will weaken our national defense.” Finally, “self-defense” refers to one’s ability to protect oneself from an attack: “The university encourages female students to take a self-defense course to learn to protect themselves.”
attention span
In this podcast, the phrase “attention span” means how long someone can concentrate on a particular topic or thing without becoming distracted and beginning to think about something else: “Young students have a short attention span, so teachers often introduce new ideas and activities every few minutes.” A “time span” is the amount of time between two dates or events: “They doubled the number of employees over a very short time span.” The phrase “life span” refers to the entire life of a person or animal: “Over its life span, this insect could produce thousands of eggs.” Finally, a “wing span” is the distance from the tip of one wing to the tip of another wing: “The wing span of an Andean condor can be more than 10 feet!”
Culture Note
Workplace Bullying
Many people experience “conflict” (fights; arguments; differences of opinion) at work, but sometimes it “crosses the line” (goes beyond the limits of something) and becomes workplace “bullying” (persistent, aggressive behavior that makes another person feels unimportant or worthless). Many researchers have agreed on five main types of bullying behaviors:
1. Bullies may try to “undermine” (make something weaker or less important) their co-workers’ professional status, making them seem “incompetent” (unable to do their job well), “unintelligent” (not smart), or “flaky” (not reliable or dependable).
2. Bullies may try to attack their co-workers on a personal level, saying mean or unkind things about them, calling them names, or making inappropriate jokes.
3. Bullies may try to “isolate” (make someone feel alone) their co-workers, ignoring them or preventing information from reaching them so that they do not feel they are part of the team.
4. Bullies may assign “excess” (too much) work to their co-workers, putting them under a lot of stress to meet difficult or impossible “deadlines” (dates and times when things are due and must be submitted), possibly while “interrupting” (doing things to make another person temporarily stop what he or she is doing) them.
5. Bullies may “destabilize” their co-workers, refusing to recognize when they do something well, “delegating” (giving someone responsibility for completing a task) unimportant work, or even changing the goals of a project without telling the person who is being bullied.
Unfortunately, it can be difficult to “prove” (make it clear that something is happening by providing evidence) these bullying behaviors, because the bullies are often able to do them within the “confines” (bounds; limits) of “corporate culture” (the accepted behaviors within a company). They often act very differently around their “superiors” (managers; the people to whom one reports) and the individuals whom they are bullying.
Comprehension Answers
1 - c
2 - c