= 1149
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English is a Second Language Podcast number 1,149 – Delaying Making a Decision.
This is English as a Second Language Podcast episode 1,149. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode. Have you downloaded our ESL Podcast Magazine, Learn English? Well, go to eslpod.com/apple or eslpod.com/android and download it today. It’s free.
This episode is a dialogue between Thomas and Eugenia about waiting to make an important decision. Let’s get started.
[start of dialogue]
Thomas: You’ve hemmed and hawed for weeks. It’s time to make a decision.
Eugenia: I know, but I need to sleep on it. This is a very big decision.
Thomas: You’ve dragged your feet for far too long. Are you having second thoughts?
Eugenia: No, no second thoughts. I just want to be absolutely sure I’m making the right choice. I’m on the fence between two options. We’ll have to live with this decision for years.
Thomas: I thought you’d already made a tentative decision days ago.
Eugenia: No, no, no. In my mind, the jury is still out.
Thomas: You can’t leave everyone hanging.
Eugenia: I know that, but how can I choose if I’m not 100 percent positive about either option.
Thomas: I understand that, but it’s now down to the wire. You’ve got to bite the bullet and decide.
Eugenia: I know. If only I had a few more days to think about it . . .
Thomas: Too late. They’re here.
Eugenia: The painters are here?
Thomas: Yes. So will this be a blue or green house?
Eugenia: How about stripes?
[end of dialogue]
Thomas says to Eugenia, “You’ve hemmed and hawed for weeks.” This somewhat unusual expression, “to hem (hem) and haw (haw),” means to be undecided about making a decision – in fact, to refuse to make a decision or to provide an answer because you’re still thinking about it. You’re still considering your options. Usually when we say someone is “hemming and hawing,” we mean he is being indecisive. He is not making up his mind, and we consider that a bad thing. It’s a criticism of that person.
Thomas says, “It’s time to make a decision.” Eugenia says, “I know, but I need to sleep on it.” When someone says he’s going to “sleep on it,” or if someone tells you to “sleep on it,” he means to think about something and make a decision tomorrow – to go to bed, if you will, and perhaps think about it. I think the idea here is that sometimes if we wait and allow our mind, unconsciously perhaps, to process information or to give our brain time to think about something, we will make a better decision. Eugenia says, “This is a very big decision.”
Thomas says, “You’ve dragged your feet for far too long.” “To drag your feet” means to do something very slowly. It means not to do something when you’re supposed to do it, to take much longer than you should take. Thomas says, “Are you having second thoughts?” The term “second thoughts” means doubts about your decision or doubts that will make you change your mind about a decision you’ve already made. Eugenia says, “No, no second thoughts. I just want to be absolutely sure I’m making the right choice.” “To be absolutely sure” about something means you don’t have any doubts. You know that this is correct. You’re certain that you are right.
Eugenia says, “I’m on the fence between two options.” “To be on the fence” (fence) means to be undecided, to not be sure which of two options you want. A “fence,” of course, is something that you put up around your property or around something that you don’t want someone to get into, or a place you don’t want someone to enter. At my house, for example, there is a fence between all of my neighbors. Interestingly enough, I didn’t put up the fences, so I guess my neighbors don’t want me in their yard more than I don’t want them in my yard or property.
Anyway, Eugenia is “on the fence between two options,” or choices. She says, “We’ll have to live with this decision for years.” When someone says, “We have to live with this,” he means we have to be able to tolerate this, or we have to be in this situation. We’re not going to be able to change it. There’s nothing we can do about it.
Thomas says, “I thought you’d already made a tentative decision days ago.” “Tentative” (tentative) means not final – temporary. Something that is tentative is something that you’re not certain about. You are saying yes to something, but you could change your mind in the future. That’s something that is “tentative.” Eugenia says, “No, no, no.” She didn’t make even a tentative decision days ago.
“In my mind,” she says, “the jury is still out.” This expression, “the jury (jury) is still out (out),” is used when you mean something is not yet decided, when a decision hasn’t been made either by you, or by perhaps a group of people. A “jury” is a group of usually 12 people who decide whether someone is guilty or innocent of a crime in a court. “To be out” means to be still thinking about it. That’s the expression we use when a jury hasn’t yet made its decision. We say the jury is still out. The phrase has become more commonly used to mean any decision that has not yet been made or to refer to a decision that has not yet been made.
Thomas says, “You can’t leave everyone hanging.” “To leave (leave) someone hanging” means not to let someone know the final decision about something, to make someone wait to find out something important that that person wants to know. If you ask a girl to marry you and she says, “Well, let me think about that. Let me sleep on it. I’ll tell you tomorrow,” she is leaving you hanging. She is not telling you her decision. She’s waiting to give you her decision, and you are anxious to get her decision. You want to know.
Eugenia says, “I know that,” meaning I know I’m leaving everyone hanging, “but how can I choose if I’m not 100 percent positive about either option.” The word “positive” (positive) here means sure, convinced, persuaded that you are correct about something. Thomas says, “I understand that, but it’s now down to the wire (wire).” When we say something is “down to the wire,” we mean it is right before a deadline. There’s no additional time left to make a decision or to do something.
If you say something is going right down to the wire, you mean that it isn’t going to be completed until right before the final moment, right before a deadline. Thomas says to Eugenia, “You’ve got to bite the bullet and decide.” The expression “to bite (bite) the bullet (bullet)” means to do something that is very challenging, or very difficult, or perhaps even very dangerous, but it’s something you have to do. It might be something that is as simple as making a difficult decision.
If you’ve asked your girlfriend to marry you and she doesn’t really want to, it will be difficult perhaps for her to tell you. But she has to bite the bullet and tell you. She has to do this difficult, challenging thing because it’s necessary. You need to know. You don’t want to be left hanging. Thomas is telling Eugenia that she has to bite the bullet. Eugenia says, “I know. If only I had a few more days to think about it.”
Thomas says, “Too late. They’re here,” meaning someone has arrived, perhaps someone related to the decision that Eugenia is supposed to make – and in fact, that’s exactly what is happening here. Eugenia says, “The painters are here?” “Painters” are people who put paint on your house, either on the inside or the outside of your house. Now we know this decision that Eugenia is supposed to make is related to painting her house. Thomas says, “Yes. So will this be a blue or green house?” Eugenia needs to decide if the painters are going to paint the house blue or green.
Eugenia says, “How about stripes?” “Stripes” (stripes) are parallel lines of different colors. You can think of the animal the zebra as having stripes, black and white lines on its body. You can have stripes on a shirt where there’s a line of black and a line of white, or a line of blue and a line of, I don’t know, grey. What Eugenia is suggesting is that, because she can’t decide if she wants to paint her house blue or green, she’s going to have blue and green stripes – lines that go up and down the wall, or from side to side, perhaps.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Thomas: You’ve hemmed and hawed for weeks. It’s time to make a decision.
Eugenia: I know, but I need to sleep on it. This is a very big decision.
Thomas: You’ve dragged your feet for far too long. Are you having second thoughts?
Eugenia: No, no second thoughts. I just want to be absolutely sure I’m making the right choice. I’m on the fence between two options. We’ll have to live with this decision for years.
Thomas: I thought you’d already made a tentative decision days ago.
Eugenia: No, no, no. In my mind, the jury is still out.
Thomas: You can’t leave everyone hanging.
Eugenia: I know that, but how can I choose if I’m not 100 percent positive about either option.
Thomas: I understand that, but it’s now down to the wire. You’ve got to bite the bullet and decide.
Eugenia: I know. If only I had a few more days to think about it . . .
Thomas: Too late. They’re here.
Eugenia: The painters are here?
Thomas: Yes. So will this be a blue or green house?
Eugenia: How about stripes?
[end of dialogue]
I am absolutely sure that the best scriptwriter on the Internet is our very own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to hem and haw – to be undecided and refuse to make a decision or provide an answer, because one is still considering the options
* While the politicians are hemming and hawing about whether they should provide more school funding, our schools continue to increase class sizes.
to sleep on it – to think about something overnight, while one is sleeping; to not make a decision until the morning
* I know you want to get a tattoo, but please don’t do it today. Sleep on it first.
to drag (one’s) feet – to procrastinate; to do something very slowly; to delay so that something does not happen when it should
* The consultants have been dragging their feet for weeks. If they don’t deliver the final report by Friday, let’s terminate the contract.
second thoughts – doubts about one’s decision that make one consider changing one’s mind
* Is it normal to have second thoughts on your wedding day?
absolutely sure – entirely convinced that one should proceed as planned; without any doubts or hesitation
* If you aren’t absolutely sure that you want to have this surgery, please do some more research and discuss the options with your doctor.
on the fence – undecided; not sure which of two options to choose
* The board of directors is still on the fence regarding which office location to open first.
option – choice; one of the things that one can select when making a decision
* This option provides unlimited Internet access, but it costs more than the other plan.
tentative – not certain, fixed, or final; provisional or temporary until a final decision can be made
* We’ve made a tentative decision to introduce the new product line, but we’re waiting to receive feedback from the focus groups before we make a final decision.
the jury is still out – a phrase meaning something is still undecided, or that a choice or decision has not yet been made
* The jury is still out on whether we’ll spend our summer vacation in Yosemite or Yellowstone.
to leave (someone) hanging – to keep someone in suspense; to not let someone know the final decision; to make someone continue to wait to find out about something
* Please don’t leave us hanging any longer. Who is the winner?
positive – sure; convinced that one is correct or that one is doing the right thing; without any doubts or hesitation
* Are you positive that this is the way back home?
down to the wire – immediately before a deadline; without any additional time to make a decision or complete something
* This proposal is due tomorrow at 9:00, so we are down to the wire.
to bite the bullet – to do something that is very challenging, difficult, intimidating, or scary
* It’s time to bite the bullet and tell the boss you’re quitting.
painter – a person who applies a thick, colored liquid over the surface of something in order to change its color
* Did you hire a painter to paint your kitchen, or did you do it yourself?
stripes – parallel strips (thick lines) of alternating colors (first one color and then another)
* Is it true that no two zebras have the same pattern of stripes?
Comprehension Questions
1. What does Thomas mean when he says, “You’ve hemmed and hawed for weeks”?
a) Eugenia has avoided thinking about this for too long.
b) Eugenia has been unhappy and stressed out for too long.
c) Eugenia has been trying to make a decision for too long.
2. What does Thomas mean when he says, “it’s now down to the wire”?
a) A decision has to be made immediately.
b) The two paint colors are extremely similar.
c) He is going to force her to make a decision.
Answers at bottom.
What Else Does It Mean?
positive
The word “positive,” in this podcast, means sure and convinced that one is correct or that one is doing the right thing, without any doubts or hesitation: “Are you positive this is the right answer?” The word “positive” can also describe someone who is optimistic, cheerful, and happy: “We need to hire someone who has a positive attitude even when work is stressful.” Sometimes the word “positive” means advantage: “Let’s think about the positives: if we do this, we’ll end up saving a lot of time and money in the long run.” The phrase “to be positive about” can mean to receive something well, or to like something: “The test audiences were really positive about the film.” Finally, the word “positive” can be used for emphasis: “The drought has been a positive disaster for local farmers.”
stripes
In this podcast, the word “stripes” means parallel strips of alternating colors: “Black and white stripes on the road indicate where it is safe for pedestrians to cross.” Or, “They bought curtains with yellow and brown stripes to match the colors of their furniture.” The phrase “to earn (one’s) stripes” means to get a particular position through hard work, education, experience, and dedication: “The astronaut earned her stripes by excelling in college and in the military.” The phrase “of all stripes” means of many different kinds: “People of all stripes were at the festival.” Finally, the “Stars and Stripes” refers to the United States flag: “Many people hang the Stars and Stripes in front of their homes on the days around Independence Day.”
Culture Note
Paint-by-Number Kits
People who want to be artists, but feel they “lack” (do not have) artistic “talents” (gifts; skills; abilities to do something) sometimes buy paint-by-number “kits” (a group of objects that are packaged and sold together for some particular purpose). These kits make painting easy by telling people exactly which color to paint, and where. The kits also include “tips” (suggestions for doing something well), such as instructions for different types of “brushstrokes” (how to hold and move a paintbrush).
A paint-by-number kit typically includes a “board” (a flat, stiff surface) or a piece of “canvas” (thick cloth used for painting) with light gray or blue lines that indicate which areas should be painted. Within each area is a number that “corresponds to” (matches up with) a particular paint color. The paints and “brushes” (tools used to apply paint to a surface) are included in the kit, “along with” (in addition to) a picture of the final painting.
The first paint-by-number kits were produced in 1950 under the Craft Master “brand” (the product name used to sell something). Each kit promised to give the buyer “a beautiful oil painting the first time you try.” The kits became very popular, and more than 12 million kits were sold.
In recent years, the paint-by-number kits have experienced a “resurgence” (renewed interest in something, or renewed popularity). People have begun “collecting” (searching for and storing) paint-by-number kits and the finished products from the 1950s. The Paint By Number Museum is the largest online collection of the “masterpieces” (great works of art) produced with paint-by-number kits.
Comprehension Answers
1 - c
2 - a