= 0752
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 752: Working With Unreliable People.
This is English as a Second Language Podcast episode 752. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website, you know what it is, eslpod.com. Go there, download the Learning Guide, enjoy life.
This episode is a dialogue between Paul and Jackie, and it’s going to be talking about people at work who don’t do what they are supposed to do. Sound familiar? Let’s get started.
[start of dialogue]
Paul: What time is it?
Jackie: It’s 2:30. The Cleveland office report should have been emailed to us by the end of the workday yesterday. What are we supposed to do now?
Paul: If we don’t get their report, we’ll have to hold up the production of the annual report and if that happens, somebody’s head is going to roll. This really leaves us in a lurch. Who’s responsible for the report in Cleveland?
Jackie: Noel Simmons.
Paul: Oh, no. I know Noel. I used to work with him in the Columbus office. He was always dropping the ball on his responsibilities and I was always having to cover for him.
Jackie: You must have had the patience of a saint! If he’s such a flake, why is he still working for this company?
Paul: Beats me, but I know we’re in for a long wait if he’s in charge. We have to do something. Get on the phone and see if you can light a fire under him. Unless we keep on him, we’ll never see that report.
Jackie: Okay, I’ll call the Cleveland office right now.
Paul: And Jackie?
Jackie: Yes?
Paul: If he gives you a line or some kind of excuse, let me talk to him.
Jackie: What’ll you do?
Paul: I’ll take him on a trip down memory lane. When I used to work with him, I wasn’t always so patient – or polite.
[end of dialogue]
We’re in a business office in this dialogue. Paul asks Jackie what time it is. Jackie says, “It’s 2:30,” 2:30 in the afternoon. She says, “The Cleveland office report should have been emailed to us by the end of the workday yesterday.” Cleveland is a city in the State of Ohio, which is in the eastern central part of the United States. Jackie says that office – the Cleveland office should have emailed them a report, “What are we supposed to do now?” What can we do now? What should we do now?
Paul says, “If we don’t get their report, we’ll have to hold up the production of the annual report.” “To hold up” here means to delay, to make something happen later than you originally planned because there has been some problem. In this case, the problem is that the other office didn’t finish their “report,” their set of papers they were supposed to prepare about something, we don’t know what. “To hold up” here, then, means to delay the “production,” or the making of the annual report. “Hold up” has other meanings, very different meanings, in English. You can find some of those in our Learning Guide. An “annual report” is a report that a large company produces, especially what we would call a “public company,” a publicly traded company, a company that people can buy stock in – partial ownership in. They’re required to produce an annual report that says what they did the past year: what business they did, what new projects they have, and so forth. “Annual” means every year. Paul says, “if that happens, somebody’s head is going to roll.” The expression “heads will roll” or “someone’s head is going to roll” (roll) means someone will be punished for this; someone is going to get into trouble for this, perhaps even fired from their job – lose their job. The expression comes from when you kill people by cutting off their heads. And, of course, after you cut off the head it would fall down on the ground and “roll,” turn around kind of like a ball – kind of like a soccer ball, always reminds me a little bit of that. Anyway, Paul says, “This really leaves us in a lurch.” “To be left in a lurch” (lurch) means that you have a big problem, a very difficult situation. “He left me in a lurch,” he left me with a very difficult situation. Paul says, “Who’s responsible for the report in Cleveland?” Who is the person who is supposed to be writing this report? Jackie says, “Noel Simmons.” Paul says, “Oh, no. I know Noel (I know this person). I used to work with him in the Columbus office.” Columbus is another city in Ohio. There are three cities in Ohio that begin with “C” – at least three: Columbus, Cleveland, and Cincinnati.
Well, Paul used to work with Noel in the Columbus office. He says Noel “was always dropping the ball on his responsibilities.” The expression “to drop the ball” means not to do what you are supposed to do, to be unreliable. The title of this episode is “Working With Unreliable People,” not reliable. “Reliable” means you can trust them, you can trust them to do what they are supposed to do. Well, Noel is unreliable; he’s always dropping the ball. Paul says, “I was always having to cover for him.” “To cover for (someone)” means to do something so that other people don’t know that this person has made a mistake. You are, perhaps, lying or doing something so that no one else discovers what your friend or your coworker did wrong. You’re helping them that way – at least you think you are.
Jackie says, “You must have had the patience of a saint!” “To be patient” means to be able to wait, to tolerate or put up with difficult situations without getting angry or without losing your temper. A “saint” is a holy person; someone, here, who represents a perfect person; someone who is very holy, someone who is very, very good. Jackie says, “You must have had the patience of a saint!” It’s an expression. She says, “If he’s such a flake, why is he still working for this company?” A “flake” (flake) is an unreliable person, someone who doesn’t do what they’re supposed to do. The State of California, the City of Los Angeles especially, is full of flakes, people who say they’re going to do something but don’t. At least, that’s the reputation that the city and state have with some people. Jackie wants to know why Noel, if he’s such a flake, is still working at the company. Why didn’t he get fired?
Paul says, “Beats me.” “Beats me” is an informal way of saying I don’t know, I don’t know the answer to that question. He says, “Beats me, but I know we’re in for a long wait if he’s in charge.” “To be in for” means to be expecting or deserving to have something done. “We’re in for a cold winter this year,” meaning we can expect a cold winter. In this case, Paul says they’re in for a long wait if he, Noel, is in charge. “To be in charge” means to be responsible for some project or some group; you’re the person who is the boss of that project: you make the decisions, and so forth. Paul says, “We have to do something. Get on the phone (call on the telephone) and see if you can light a fire under him.” The expression “to light a fire under (someone)” means to do or say something to get that person to work, to do something, especially if the person is lazy or unreliable. Usually it means applying some sort of pressure, doing something to push the person to get their job done. If you light a fire you will create heat, of course, and that will cause a person to get up and move if you actually lit a fire under someone. Well, that’s what you’re trying to do here. Paul says, “Unless we keep on him (keep on Noel), we’ll never see that report.” “To keep on (someone)” means to bother them repeatedly until they do what you want them to do. Another word for this would be “to nag” (nag). “Stop nagging me.” This is something husbands occasionally – not this husband – says about their wives. “My wife is always nagging me to do something,” always telling me to do something until I actually do it. Well, that’s what Paul says they have to do with Noel.
Jackie says, “Okay, I’ll call the Cleveland office right now.” Paul says, “And Jackie?” Jackie says, “Yes?” Actually, probably says something like “Yes?” Paul says, “If he gives you a line or some kind of excuse, let me talk to him.” When you say you’re “giving someone a line” (line) you mean you’re giving them an excuse, something that other people might say as an excuse. “Oh, I got busy,” or “Oh, my cat died and I had to go home and bury it,” put it in the ground, give it a funeral, and so forth. These are excuses, and many people try to give excuses when they don’t do what they’re supposed to do. So Paul says, “If he gives you a line (an excuse), let me talk to him.”
Jackie says, “What’ll you do?” What will you do? Paul says, “I’ll take him on a trip down memory lane.” A “lane” (lane) is like a small road. But the expression “to take a trip down memory lane” means to spend some time remembering things that have happened in the past. Normally, the expression means you’re taking a pleasant trip, if you will, you’re remembering good things that happened in the past. But in this case, Paul is making something of a joke. He’s going to remind Noel of bad things that happened in the past. He says, “When I used to work with him, I wasn’t always so patient – or polite.” “To be polite” (polite) means to be kind, to be nice. It’s the opposite of “rude” (rude), which means to be mean, not to be nice. Paul is saying that he’s going to treat Noel the way he used to treat him in the past. That is, he’s probably going to get angry with him.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Paul: What time is it?
Jackie: It’s 2:30. The Cleveland office report should have been emailed to us by the end of the workday yesterday. What are we supposed to do now?
Paul: If we don’t get their report, we’ll have to hold up the production of the annual report and if that happens, somebody’s head is going to roll. This really leaves us in a lurch. Who’s responsible for the report in Cleveland?
Jackie: Noel Simmons.
Paul: Oh, no. I know Noel. I used to work with him in the Columbus office. He was always dropping the ball on his responsibilities and I was always having to cover for him.
Jackie: You must have had the patience of a saint! If he’s such a flake, why is he still working for this company?
Paul: Beats me, but I know we’re in for a long wait if he’s in charge. We have to do something. Get on the phone and see if you can light a fire under him. Unless we keep on him, we’ll never see that report.
Jackie: Okay, I’ll call the Cleveland office right now.
Paul: And Jackie?
Jackie: Yes?
Paul: If he gives you a line or some kind of excuse, let me talk to him.
Jackie: What’ll you do?
Paul: I’ll take him on a trip down memory lane. When I used to work with him, I wasn’t always so patient – or polite.
[end of dialogue]
Our scriptwriter never drops the ball on her responsibilities. That’s because we have the wonderful Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
to hold up – to delay; to make something happen later than originally planned; to not complete something when it should have been finished
* Preparations for the outdoor wedding were held up by poor weather.
annual report – a written document produced once each year that shares information about a company's financial status and achievements during the past year
* They spend a lot of money on their annual report, because they use it as a tool to attract new investors.
(one’s) head is going to roll – for someone to be punished for one's actions, especially by being fired
* If we don't get this contract, heads are going to roll.
in a lurch – with a major problem; in a very difficult situation
* Shane and his wife lost their jobs on the same day, so now the family is in a lurch.
to drop the ball – to be unreliable; to not do what one is supposed to do; to be irresponsible
* Ollie really dropped the ball when he forgot to pick up his son from school.
to cover for (someone) – to lie or act a certain way to protect another person so that he or she doesn’t get in trouble for what he or she has or has not done
* As a teenager, Erwin always asked his twin brother to cover for him when he stayed out late at night.
the patience of a saint – with a lot of patience; never in a hurry; always willing to wait to do or have something, much more than other people
* A good kindergartener teacher needs to have the patience of a saint!
flake – a person who is very unreliable and does not do what he or she is supposed to do
* Nancy said she’d meet me here an hour ago, but she’s such a flake that I’m really not surprised she isn’t here.
beats me – an informal phrase used when one does not have an answer to another person’s question; I don’t know
* - Do you know why Adam decided to shave his head?
* - Beats me.
in for – expecting or deserving to have or do something
* We’re in for more expensive health insurance premiums if medical costs keep rising.
in charge – responsible for a project or group; with decision-making power over a project, program, or team
* Larry received such bad customer service that he asked to speak with the person in charge.
to light a fire under (someone) – to do or say something to motivate a person; to do or say something that makes someone do something, especially if he or she is very lazy and was not going to do that thing alone even though he or she should
* Karl was never a very good worker, but his daughter’s birth lit a fire under him and he began to work really hard to try to get a promotion.
to keep on (someone) – to nag; to bother someone repeatedly to make sure he or she does what needs to be done; to remind someone about something many times
* Do you have to keep on your kids to make them practice playing the violin so much, or do they choose to do it on their own?
line – a saying; an excuse; one sentence, especially one that is common and used by many people
* When the teacher asked Rajal why he didn’t write the essay, he gave her the line about how the dog ate his homework, but of course she didn’t believe it.
a trip down memory lane – time spent remembering what happened in the past
* Looking through photo albums is like taking a trip down memory lane.
polite – not rude; using kind, nice words that are appropriate for the place and audience
* Mitchell is a very polite young man who always says “please” and “thank you.”
Comprehension Questions
1. According to Paul, what will happen if the annual report is delayed?
a) There will be a lot of yelling.
b) The boss will shake his head in anger.
c) Someone will be fired.
2. What does Paul mean when he says that Noel was always dropping the ball?
a) He wasn’t a very good athlete.
b) He didn’t do what he was supposed to do.
c) He often fought with his co-workers.
Answers at bottom.
What Else Does It Mean?
to hold up
The phrase “to hold up,” in this podcast, means to delay something or to make something happen later than originally planned: “He’s holding up the press conference until everyone gets here.” The phrase “to hold up” also means to support or to keep something off the ground: “Is that bookshelf strong enough to hold up all those books?” The phrase “to hold up” means to steal money from someone, usually by pointing a gun so that the other person puts his or her hands up in the air: “Were the police able to catch the men who held up the pizza delivery boy?” Finally, the informal phrase “hold up” can be used to ask someone to stop doing something or to stop moving quickly so that one can catch up: “Hey, hold up! Can we talk for a minute before you continue?”
line
In this podcast, the word “line” means a saying or an excuse, especially one that is common and used by many people: “Sheila hates it when guys break up by using a line like, ‘It isn’t you, it’s me.’” A “line” can also refer to one row of text in a document: “There’s a typo in the second line of the fourth paragraph.” The phrase “to drop (someone) a line” means to communicate with someone by sending a brief note: “I know you’re busy, but please take the time to drop us a line and let us know how you’re doing.” Finally, the phrase “to be out of line” means to do something that is inappropriate: “That comment was out of line! Please tell her you’re sorry.”
Culture Note
The Unreliable Narrator
A “narrator” is the character or person who tells the story in a book, show, or play. A “first-person narrator” is a character in the story who tells the story from his or her perspective, using the word “I.” A “third-person narrator” is an “observer” (someone who sees what is happening, but does not participate in the action). A third-person narrator can be “omniscient” (knowing everything about what is happening and why, including what other characters think) or “focalized” (presenting information about a particular character, but unaware of other characters’ thoughts).
Narrators can also be “reliable” (dependable; able to be trusted) or “unreliable.” Some authors use “unreliable narrators” to “deceive” (trick; make someone believe something that is not true) the readers. This is often used in “mysteries” (stories where the readers wonder who did something and why, and do not find out until the end).
Sometimes the unreliability of the narrator is “clear” (obvious) at the beginning of the story, because what the narrator says obviously cannot be true. But in other cases authors make the narrator’s unreliability “apparent” (able to be seen) only later in the book. This “revelation” (realization; something that shows the truth) changes how the readers “interpret” (understand) the part of the story that they have already read, since it was presented by a narrator whom they now understand to be unreliable.
Sometimes it isn’t clear whether a narrator is reliable or not. Authors can use this technique to leave their readers “questioning” (wondering what is true) the narrator’s reliability. This might create a sense of mystery and allow their writing to be interpreted in one or more ways.
Comprehension Answers
1 - c
2 - b