= 0763
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 763: Dealing with an Apartment Super.
This is English as a Second Language Podcast episode 763. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode. But first, become a member of ESL Podcast to help us keep going.
This episode is a dialogue between George and Louise. It’s about having problems in your apartment and calling the person who’s responsible for fixing things in an apartment building, the super. Let’s get started.
[start of dialogue]
George: Did you call the super about fixing the leaky faucet?
Louise: I called him on Monday, but I haven’t heard back yet.
George: Well, call him again. This window is stuck and it won’t close.
Louise: I’ll call him, but I think he’s avoiding our calls.
George: He’s the worst super we’ve ever had. He’s in charge of the maintenance around this place, but instead, he hides out in his apartment. Whenever there’s a problem, he tells us he’s too busy to get to it right away. Too busy doing what, I’d like to know.
Louise: Maybe he is overworked. There are 25 units in this building, so it’s conceivable that he’s busy making repairs – somewhere.
George: That’s what he’s counting on, people like you who give him the benefit of the doubt. All the while he’s drinking coffee and reading the newspaper somewhere. Mark my words.
Louise: I’ll call him again. Maybe we’ll catch him in his apartment.
George: Save your energies.
Louise: Where are you going and what are you doing with that baseball bat?
George: I’m going to track down that super and bring him back here. Come hell or high water, he’s making those repairs – today!
[end of dialogue]
George begins our dialogue by asking Louise, “Did you call the super about fixing the leaky faucet?” The word “super” is short for “superintendent.” A “superintendent,” in this case, is a person who is responsible for fixing any problems that you have in an apartment building. So if you have, as does George and Louise, a leaky faucet, you would call this person and they would be responsible for fixing it or bringing someone in to fix it. A “faucet” is where the water comes out in a sink. If it’s “leaky,” that means water is coming out slowly even when it’s not supposed to.
Louise says that she called the super on Monday, but that she hasn’t heard back yet. “To hear back from (someone)” means to receive a message back from someone that you have tried to contact. Either you sent an email, or you’ve written a letter, or you called someone. They were supposed to call you back, or write you back, and you have not yet gotten a response. You haven’t heard back yet.
George says, “Well, call him again. The window is stuck and it won’t close.” The window won’t close down all the way, and that’s what George means when he says it’s stuck. It could be stuck (stuck) open, meaning you can’t close it, or it could be stuck closed, meaning you can’t open the window. Louise says, “I’ll call him, but I think he’s avoiding our calls,” meaning he’s not answering his phone on purpose. He’s doing it intentionally, we might say, because he doesn’t want to talk to us.
George says, “He’s the worst super we’ve ever had. He’s in charge of the maintenance around this place, but instead, he hides out in his apartment.” “Maintenance” is the work that you need to keep something in good condition, or to make sure it doesn’t get worse than it is right now. So in an apartment building, you might need to paint the walls every few years, or clean the carpets. You need to make sure the plumbing is working properly, the heating and/or air conditioning is working okay. All of these things may require maintenance; you may have to do something to make sure they’re working correctly. George says that the super hides out in his apartment. “To hide (hide) out” is a two-word phrasal verb meaning to spend your time where no one else can see you. It can mean, also, to be quiet, to remain hidden so that no one can find you. In this case, the super is hiding out in his apartment. He’s there and he doesn’t want anyone to know he’s there perhaps. George says, “Whenever there’s a problem, he tells us he’s too busy to get to it right away.” If there’s a problem the super says, “Oh, no. I’m sorry. I’m busy. I can’t do it right now. I can’t get to it,” meaning I can’t do what I need to do right now for that problem. George says, “Too busy doing what, I’d like to know,” meaning what is he doing that makes him so busy.
Louise says, “Maybe he is overworked.” “Overworked” means that you have too many things to do at your job; the boss has given you too much to do. That’s how I feel; I feel overworked! Louise says, “There are 25 units in this building, so it’s conceivable he’s busy making repairs – somewhere.” A “unit” (unit) in this situation means an apartment or a condominium in a large building. If there are 25 apartments in your building, we’d say there are 25 units; it’s the same thing. Louise says, “it’s conceivable (meaning it’s possible, it’s not likely but it could be) that he’s busy making repairs (he’s busy fixing things) somewhere else.”
George says, “That’s what he’s counting on.” That’s what he’s depending on, that’s what he’s relying on. “He’s counting on people like you who give him the benefit of the doubt.” The expression “to give (someone) the benefit of the doubt” means to assume the most positive thing when you don’t have all the information about what is happening, especially when there’s a problem or you think there might be a problem. So you call a plumber to come over and fix something in your bathroom, and the plumber doesn’t call you and they’re late. They’re supposed to be there at 9:00; it’s 10:00, 11:00, still no plumber. The plumber doesn’t come; the plumber doesn’t call. Now you could get angry, saying, “Oh, that terrible plumber. He’s lazy,” or, “He’s not a very good business person.” But, if you were to give him the benefit of the doubt you would think of another reason – a better excuse. Maybe he got into a car accident. Maybe there was a lot of traffic on the freeway, and he forgot his cell phone at home. Maybe he was appointed ambassador to Zimbabwe and is busy in Washington meeting with the president. You see there are all sorts of reasons why the plumber might not come on time. That’s giving someone the benefit of the doubt.
George says, “All the while (meaning at this time, while he is saying the same thing) he’s drinking coffee and reading the newspaper somewhere.” So he’s not really busy; he’s just relaxing somewhere reading the newspaper. Then George says, “Mark my words.” The expression “mark (mark) my words” is used to emphasize that what you have just said – what you have just told another person will come true, to remember that in the future. “Mark my words, the plumber went to a bar and got drunk.” That’s what happened. You’re saying that you don’t know that, probably, but that’s sort of your prediction. You want the person that you’re talking to to remember what you’re saying.
Louise says, “I’ll call him again. Maybe we’ll catch him in his apartment.” “To catch (someone)” in this case means to find someone before they leave, calling someone before they leave their apartment or before they leave their office. “Catch” has a couple of different meanings in English; take a look at our Learning Guide for some of those. George, however, says, “Save your energies.” “Save your energies” or “save your energy” is an informal phrase used to tell someone not to do something because it won’t be necessary or because it won’t really help the situation.
Louise says, “Where are you going and what are you going to do with that baseball bat?” A “baseball bat” is used in the game of baseball, of course, to hit the ball. Some people keep baseball bats in their houses as a form of defense, as a weapon to protect themselves, to hit someone who may come in and try to steal something from your house. It’s cheaper and less dangerous than a gun.
Well, George says that he’s going to track down the super and bring him back here. “To track (track) (someone) down” means to find them, especially if it is difficult to find them. Perhaps they’re hiding or they’re lost. George says, “Come hell or high water, he’s making those repairs – today!” The expression “come hell or high water” is an old one, which means no matter what happens, no matter how difficult the situation is I’m going to do this, or, in this case, I’m going to get the super to come back and fix the problems in the apartment no matter what – no matter what happens, come hell or high water. George, of course, is potentially going to use violence here; we might have to have another dialogue called getting out of jail or prison after beating someone with a baseball bat! I hope not.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
George: Did you call the super about fixing the leaky faucet?
Louise: I called him on Monday, but I haven’t heard back yet.
George: Well, call him again. This window is stuck and it won’t close.
Louise: I’ll call him, but I think he’s avoiding our calls.
George: He’s the worst super we’ve ever had. He’s in charge of the maintenance around this place, but instead, he hides out in his apartment. Whenever there’s a problem, he tells us he’s too busy to get to it right away. Too busy doing what, I’d like to know.
Louise: Maybe he is overworked. There are 25 units in this building, so it’s conceivable that he’s busy making repairs – somewhere.
George: That’s what he’s counting on, people like you who give him the benefit of the doubt. All the while he’s drinking coffee and reading the newspaper somewhere. Mark my words.
Louise: I’ll call him again. Maybe we’ll catch him in his apartment.
George: Save your energies.
Louise: Where are you going and what are you doing with that baseball bat?
George: I’m going to track down that super and bring him back here. Come hell or high water, he’s making those repairs – today!
[end of dialogue]
You can always count on a good script on ESL Podcast, thanks to our scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
super – superintendent; a person whose job is to maintain a building, especially an apartment building, making sure that everything works properly and fixing things that break
* The super wasn’t able to fix the light by our front door, so he’s going to call a professional electrician.
to hear back – to receive communication from someone after one has left a message for that person
* I’ve left seven messages on Alexey’s cell phone in the past 24 hours, but I still haven’t heard back from him. Do you think he’s avoiding me?
maintenance – the work or actions needed to keep something in good condition, or at least to avoid letting it fall into worse condition
* They never would have bought a 100-year-old house if they had realized how much maintenance it would require.
to hide out – to remain hidden, quiet, and secretive; to spend time where one cannot be seen or observed by other people
* You can’t hide out in the garage all night. At some point you need to go in and tell everyone what happened.
overworked – with too many things to do, especially in one’s job
* The customer service representatives are overworked. We need to hire more people to help answer the phones.
unit – one apartment or condo in a large building or complex
* How much do you charge for the two-bedroom units?
conceivable – possible, but not likely; able to be believed
* It’s conceivable that his relatives have died each week for the past month, but I think it’s more likely that he’s lying about it as an excuse so he doesn’t have to come to work.
to count on – to rely on; to depend on; to want or need something to exist or happen a certain way
* We’re counting on you to help us move this weekend. Please don’t forget!
to give (someone) the benefit of the doubt – to assume the most positive thing when one does not have full information about which possibility is real or true
* Either the client changed her mind or she was offended by the team’s presentation. But since she hasn’t complained, let’s give the team the benefit of the doubt.
all the while – while; simultaneously; at the same time, especially when used to show a strong contrast
* Olivia spent the evening cooking, feeding the baby, washing the dishes, bathing the kids, and reading bedtime stories, and all the while her husband was watching TV. Why doesn’t she ask him to help her?
mark my words – a phrase used to emphasize what one has just said and tell another person to pay attention, listen carefully, and remember it in the future
* Mark my words, the next World War will be fought over a lack of water.
to catch (someone) – to find or communicate with someone, especially before he or she leaves a place
* If you go right now, you might be able to catch Mariah in her office before she leaves for the day.
save your energies – an informal phrase used to tell someone not to do something, usually because one thinks it is unnecessary and will be a waste of time
* Jasmina was going to complain to the manager, but everyone told her to save her energies, because it wouldn’t do any good.
to track down – to find someone, especially if it will be difficult
* Zvonko is determined to track down whoever scratched his new car and make them pay for the damage.
come hell or high water – in spite of all obstacles; no matter what happens; no matter how difficult something is
* Come hell or high water, we’re going to make this business a success!
Comprehension Questions
1. Why does Louise think the super might be overworked?
a) Because the apartment building is very large.
b) Because the apartment building is 25 years old.
c) Because the super has another full-time job.
2. What does George mean when he says, “Mark my words”?
a) He wants Louise to correct his grammar.
b) He wants Louise to pretend to be the super so he can practice his speech.
c) He wants Louise to remember what he’s saying.
Answers at bottom.
What Else Does It Mean?
super
The word “super,” in this podcast, means a superintendent, or a person whose job is to maintain a building, making sure that everything works properly and fixing things that break: “If anything breaks, just let the super know.” As an adjective, the word “super” usually means very good, nice, or wonderful: “They made some super suggestions for the report.” Or, “Coming to this restaurant was a super idea.” Informally, the word “super” can also be used as an adverb to mean very or extremely: “I’m super hungry. When will dinner be ready?” Or, “Flying across the country makes him super tired.” Finally, “super-” can describe something that is bigger, better, or more powerful than something else: “Do you think the super-rich should pay higher taxes?”
to catch (someone)
In this podcast, the phrase “to catch (someone)” means to find or communicate with someone, especially before he or she leaves a place: “Professor Daines has office hours every Tuesday from 10:00 to 11:30 when students can catch him and ask questions about the course.” The phrase “to catch (someone)” can also mean to see someone doing something he or she isn’t supposed to do: “What would you do if you caught someone stealing something from the store?” The phrase “to catch (something)” can also mean to become infected and get sick: “Can you catch a cold from a mosquito bite?” Finally, the phrase “to catch (something)” can mean to see or hear something, especially referring to the news or an announcement: “Did you catch the report about the earthquake?”
Culture Note
Working as a Building Super or Building Manager
A building super is a “jack-of-all-trades” (a person who is fairly good at doing many different things, but not an expert in any area) who needs to know a little bit about “carpentry” (working with wood), electricity, “plumbing” (working with pipes that carry water), and “landscaping” (plants put around buildings for beauty). When something breaks in an apartment “complex” (a large building or several buildings, each with many apartments), the “tenants” (the people who pay money each month to live in a home or apartment) are supposed to “notify” (inform; let someone know) the super. If the super cannot fix it, he or she should schedule an appointment for a “professional” (someone who does the work as a full-time job) to “come in” (visit; come to the place) and do the work.
Some supers also work as “building managers.” A building manager needs to have good “interpersonal skills” (the ability to communicate and have good relationships with other people), because he or she is responsible for showing units to “prospective tenants” (people who may want to live in the unit in the future), collecting “rent” (money paid each month) from current tenants, and conducting “move-in and move-out inspections” (assessments of the condition of a unit before and after people live there). The building manager might also organize social events, such as holiday parties, for the tenants.
Often the super and/or building manager is a tenant who lives in the building and receives “free” (does not have to pay) or reduced rent “in exchange for” (in return for) performing basic maintenance work and interacting with the tenants.
Comprehension Answers
1 - a
2 - c