= 0784
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 784: Socializing With Clients.
This is English as a Second Language Podcast episode 784. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. How are you today? I’m fine, thank you for asking.
This episode, like all of our episodes, has a Learning Guide, and you can find that Learning Guide on our website, eslpod.com. Become a member and download the Learning Guide today.
This episode is a dialogue between Georgia and Dan about socializing with your clients, going out with your customers on a social occasion. Let’s get started.
[start of dialogue]
Georgia: Do you know what the best part is of my new promotion? The expense account! I can’t wait to wine and dine our clients.
Dan: The purpose of the expense account is to win over new clients and to keep our current clients happy. It’s not a personal slush fund, you know.
Georgia: I know. The point is to network and to build client relationships – blah-blah-blah.
Dan: Schmoozing is part of our job and it’s not something to be taken lightly.
Georgia: Of course not. But I’m looking forward to attending charity events to rub elbows with the business elite. Free food, free booze, and free entertainment. What more could I ask for?
Dan: Talk to me in three months after you’ve had a few too many plates of rubber chicken!
[end of dialogue]
Georgia begins our dialogue by saying, “Do you know what the best part is of my new promotion?” A “promotion” can mean a couple of different things. Here, it means when you get a better job at your company. You get more money, usually, and more responsibility. That’s a promotion. A “promotion” can also be something like a sale on an item in a store, but here it means getting a better job in your company. Going from vice-president to president, that would be a promotion.
Well, Georgia got a promotion, and the best part of it is the expense account. An “expense” is money that you have to pay for something for your work. An “account” is a way of keeping track of or a way of knowing how much you are spending. Here, we put the two together, “expense account,” and we’re talking about the money that a company will give you to spend on things that are related to company business. So when you travel, for example, well you need to eat – you need to go to a restaurant. The company will pay for that; it’s part of your expense account. It’s part of the money they give you for buying things related to your job.
Georgia says, “I can’t wait to wine and dine our clients.” “To wine (wine) and dine (dine)” means to go and entertain someone with wine – alcohol – and food. “To dine” means to eat, in this case. So, “to wine and dine” usually means taking someone – one of your customers, one of your clients – to a nice restaurant as part of your sales approach or to thank them for buying things from your company. A “client” (client) is, as I said, another word for a customer. Usually in a big company, or when you have a customer who buys a lot of things from your company, we call those customers “clients.”
Dan says, “The purpose of the expense account is to win over new clients.” “To win (someone) over” or “to win over (someone)” is a two-word – say it with me – phrasal verb meaning to persuade or convince someone; to get someone, in this case, to agree with you to buy something from your company. Well, Dan says the purpose the company has for giving Georgia an expense account is to get new clients – to win over new clients and to keep the current clients happy. The “current clients” are the clients you already have, your customers that you have right now. Dan says the expense account is not a personal slush fund. A “slush (slush) fund” is money that you can spend for any purpose, and often don’t have to tell anyone about it. Slush funds can sometimes be used for illegal purposes. A slush fund is any money the company spends that it doesn’t keep track of. Usually that’s not allowed; you have to say where all of your money is going. But, a slush fund would be money that the company doesn’t keep track of. Dan says that an expense account is definitely not a slush fund.
Georgia says, “I know. The point is to network and to build client relationships – blah-blah-blah.” “To network” (network) means to create business partnerships, to get know other people who might be clients in the future or who might help you or your company. It’s a verb that has become popular in the last 20-30 years or so, one of those words you will hear in the business world – to network. Another common business expression is “to build client relationships.” Well, a “relationship” is some connection you have with another person. “Client relationships” would be the communication and connection you have with your clients – with your customers. But Georgia, at the end, says, “blah-blah-blah.” What does that mean, “blah-blah-blah”? “Blah-blah-blah” (spelled blah-blah-blah) is an informal expression we use when we don’t want to provide all of the details, we don’t want to give a full description of something because you understand it or it’s boring and complex and we don’t really need to repeat it. Often it’s used sort of to dismiss or to say that these things aren’t very important. Your children may say, for example, to their friends, “Oh, my parents want me to clean my room and do my homework, blah-blah-blah.” You see, they don’t think it’s very important. It’s also suggesting that there are other things that you have told your children to do that they’re not saying because it’s sort of understood. The other person will know what they’re talking about, and also know that your children don’t find those things very important. Maybe you should talk to your children! Well, that’s the way Georgia feels, that yes, of course, the expense account is to help the business, but she doesn’t really believe that when she says, “blah-blah-blah.”
Dan says, “Schmoozing is part of our job and it’s not something to be taken lightly.” “To schmooze” (schmooze) means to have informal conversations with people, designed to make them feel comfortable. They’re not about, often, the business itself. When you’re talking to one of your clients, you may be schmoozing them by talking about the weather or a baseball game or how you both love bicycling or your last vacation to Mexico. Whatever it is, you’re talking about informal topics, usually not even related to your business, for the purpose of becoming friendly, perhaps of making them feel welcome or making them feel important. Dan says, “Schmoozing is part of our job and it’s not something to be taken lightly.” The expression “to take (something) lightly” or “to be taken lightly” means to be unimportant, not to be taken seriously. Dan says that schmoozing is something that’s serious, it’s not something to be taken lightly – to be considered not important, because it is important.
Georgia says, “Of course not. But I’m looking forward to attending charity events to rub elbows with the business elite.” A “charity” (charity) is a group that gives money to other groups, usually to help them to help poor people or people who need help. They often have events; they have a party to help raise money – to get more money for their organization. That would be a charity event. “To rub elbows” is an informal expression meaning to spend time with someone or to work closely with someone, especially if that person is an important person. The “elite” (elite) are a group of people who are considered the best in their field or the most important people in their field. Georgia says, “Free food, free booze, and free entertainment.” “Booze” (booze) is another word for alcohol: beer, wine, and so forth. Georgia says, “What more could I ask for?” That expression means I have everything that I need; I don’t need anything more if I have this.
Dan says, “Talk to me in three months after you’ve had a few too many plates of rubber chicken!” The expression “a few too many” means too many, it’s emphasizing that you will have too many of this thing – a few too many. “Plates of rubber chicken” means eating chicken – a “plate” would just be a meal or something that’s served to you at a dinner. Why do we say “rubber chicken”? Well, when you go to a big party – a big event and they have a meal, chicken is a very popular dish, because most people will eat chicken. “Rubber chicken” means the chicken is overcooked, or it doesn’t taste very good. When you try to cook for, say, 500 people, it’s difficult to make each meal good tasting, and what you often have is food that doesn’t taste very good, and that’s why we have the expression “rubber chicken.” When chicken is overcooked, of course, it gets hard and a little difficult to eat.
Now let’s listen to our dialogue, this time at a normal speed.
[start of dialogue]
Georgia: Do you know what the best part is of my new promotion? The expense account! I can’t wait to wine and dine our clients.
Dan: The purpose of the expense account is to win over new clients and to keep our current clients happy. It’s not a personal slush fund, you know.
Georgia: I know. The point is to network and to build client relationships – blah-blah-blah.
Dan: Schmoozing is part of our job and it’s not something to be taken lightly.
Georgia: Of course not. But I’m looking forward to attending charity events to rub elbows with the business elite. Free food, free booze, and free entertainment. What more could I ask for?
Dan: Talk to me in three months after you’ve had a few too many plates of rubber chicken!
[end of dialogue]
When you have one of the elite scriptwriters on the Internet, Dr. Lucy Tse, what more could you ask for?
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
promotion – a move from a lower-paying job with less power and fewer responsibilities into a higher-paying job with more power and responsibilities, usually because one has been performing one’s job well over a long period of time
* Everyone expected Jan to get the promotion to division manager, because he has been working as the assistant manager for years.
expense account – an amount of money a company uses to reimburse (replace money spent by) an employee for expenses related to his or her job
* If we spend a few minutes talking about business, I can put our lunch on my expense account and we won’t have to pay for it ourselves.
to wine and dine – to entertain someone with food and alcohol, usually at a nice restaurant
* Considering how much they wined and dined us last week, they must really want us to accept their proposal.
client – customer; an individual, company, or organization that receives professional services, often many times, and has a strong business relationship
* Most of his clients are in North America, but he has a few clients in Europe, too.
to win over – to persuade or convince; to make someone understand or agree with something
* Do you really think a dozen roses will be enough to win her over and make her decide she wants to marry you?
slush fund – money spent freely, without a specific purpose and without clear records or justification, often used for questionable or even illegal expenses
* The company maintains a slush fund for bribing dishonest politicians.
to network – to create and maintain professional relationships with individuals who may be able to help one in the future, especially to get a new job or to find a new client
* Everyone says that the key to finding a good job is to network with people who are working in the same industry.
client relationship – the ongoing interactions between a company and an individual or organization that buys products or services from that company
* We focus on building good client relationships that keep our clients coming back to us year after year.
blah-blah-blah – informal words used instead of providing a full description of something that is complex, lengthy, boring, or otherwise does not need to be repeated in full
* Adam’s parents are always telling him to do his homework, clean his room, blah-blah-blah.
to schmooze – to make small talk; to have informal conversations designed to make people feel comfortable, especially in a business setting
* If you schmooze with the right people, I’m sure you’ll end up with a job offer.
to be taken lightly – to be unimportant; to not receive serious consideration
* The company promises to never take customers’ complaints lightly, always investigating them fully.
charity event – a party or fundraiser used to bring many wealthy people together so that they donate a lot of money to a nonprofit organization
* This dinner is a charity event. Tickets cost $450 each, and all the money is used to build schools in rural Kentucky.
to rub elbows – to spend time with someone and/or to work closely with someone, especially when that person is famous and/or powerful
* As a costume designer, Harold gets to rub elbows with famous actors.
elite – a group of people considered the best or most important, usually because they have a lot of money, power, and influence
* Only the elite can afford to shop in these designer shops and boutiques.
booze – alcohol; alcoholic beverages, especially liquor
* When it comes to booze, scotch is his favorite, but he also likes vodka.
what more could I ask for – a phrase used to show that one has everything one wants and does not want or need any more
* I have a beautiful wife, two healthy kids, a great home, and a good job. What more could I ask for?
a few too many – too many; more than one should have or do
* In her job as a movie producer, Fatima has read a few too many bad scripts.
rubber chicken – unpleasant, tasteless food, especially when served at conferences or seminars
* Let’s skip the conference dinner. I know a great restaurant where the food is much better than the rubber chicken they’ll serve here.
Comprehension Questions
1. What does Dan mean when he says, “It’s not a personal slush fund”?
a) He wants Georgia to know the money is being spent to benefit the company.
b) He wants Georgia to know she is drinking too much alcohol.
c) He wants Georgia to start spending less money.
2. Why does Dan think Georgia will change her mind?
a) She won’t like the clients she has to spend time with.
b) She’ll get tired of the unpleasant food.
c) She’ll realize how difficult networking with clients can be.
Answers at bottom.
What Else Does It Mean?
to win over
The phrase “to win over,” in this podcast, means to persuade or convince, or to make someone understand or agree with something: “It might take months to win over the boss and convince him your proposal is a good one.” The phrase “to win the day” means to finally be successful after a long argument or disagreement: “In the end, Jack won the day and his wife agreed to sell the house.” The phrase “to win (something) hands down” means to win easily and in a definite way, without any doubt about who won: “Sahid has been training for months, so he’s going to win the competition hands down.” Finally, the phrase “to win (someone’s) heart” means to make someone fall in love with oneself: “His kindness and sense of humor helped him win her heart.”
a few too many
In this podcast, the phrase “a few too many” means too many or more of something than one should have or do, especially referring to how much alcohol someone has drunk: “Give me your keys. You’ve had a few too many, so I’m going to give you a ride home tonight.” Or, “Nila has seen a few too many romantic comedies and she doesn’t realize what a real-world romance is like.” The phrase “few and far between” describes something that is rare, unusual, and hard to find: “Dedicated employees like Hannah are few and far between.” Finally, the phrase “no fewer than” is used to emphasize that a number is very large: “I must have called you no fewer than 20 times last night. Where were you?”
Culture Note
Common Sites for Business Socializing
“Socializing” (interacting with other people in social situations) is an important part of modern business, and business socializing can “take place” (happen) almost anywhere. “Stereotypically” (generally thought to be true, even without any evidence for it), a lot of business socializing takes place “over golf” (while golfing). Businesspeople and especially bankers are expected to know how “to golf” (to play a game where a small white ball is hit long distances with long metal and wooden clubs (sticks) into holes in the ground) and “between holes” (while walking from one golf hole to another) the players “talk business” (discuss their business plans and negotiate agreements). Often the real business socialization takes place after the golf game “over drinks” (while drinking alcohol) at the “clubhouse” (the bar and restaurant associated with the golf course).
Business socializing also takes place at “country clubs,” which are large, “ornately” (very fancily) decorated buildings with comfortable chairs that are available only to “members” (people who are accepted and pay a monthly fee). Business people who are members of a country club can take their clients there to “impress” (make someone think one is important or powerful) them and talk business.
Business socializing can also take place in restaurants and bars, but it is important to choose a “locale” (place) that isn’t too loud or “rowdy” (with a lot of movement, noise, and possibly violence). It needs to be a “refined” (sophisticated; elegant) place that “facilitates” (makes possible) important discussions.
A lot of business socializing happens at conferences and seminars, especially during “receptions,” or events where all the attendees are invited to eat, drink, and possibly dance while “getting to know each other” (becoming familiar and friendly with other people).
Comprehension Answers
1 - a
2 - b