= 0795
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 795: Ordering Coffee and Tea.
This is English as a Second Language Podcast episode 795. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Download a Learning Guide from our website today. It gives you the complete transcript of everything we say, along with vocabulary words, definitions, sample sentences, culture notes, comprehension questions, a free trip to Hawaii. I mean everything is included in our Learning Guide – except that trip to Hawaii!
This episode is about ordering coffee and tea. I think I’ve had a little too much coffee this morning, but we’ll go ahead and start the dialogue now. Let’s get started.
[start of dialogue]
Jermaine: I’d like a decaf drip, to go.
Drew: Would you like our light or dark roast?
Jermaine: I’ll just have whatever’s freshly brewed.
Drew: Are you sure you don’t want to try an espresso, an Americano, or a latte?
Jermaine: No, just a decaf coffee.
Drew: Sure, no problem. Would you like it hot or cold?
Jermaine: Hot, please.
Drew: Would you like any room for cream?
Jermaine: No, thanks.
Drew: Would you like some sweetener? A couple of pumps of syrup maybe?
Jermaine: No, I’ll add a couple of packets of sugar myself.
Drew: Oh, I’m sorry. I added some foam from another drink to your coffee by accident. I’ll have to start over. Did you say you wanted the light or dark roast?
Jermaine: Forget it. Let’s keep it simple. Give me a cup of tea.
Drew: Would you like that hot or cold, sweetened or unsweetened, loose leaf or in a tea bag?
[end of dialogue]
This dialogue is about two of my favorite topics: coffee and tea. I’m not sure if I mentioned, but recently I started drinking coffee again. Now, those of you who’ve listened to many of our podcasts know that I’m usually – or have been, I should say, a tea drinker. I particularly like the Starbucks tea, the Vente Earl Grey Latte at seven pumps of vanilla, nonfat, no foam. However, more recently I’ve gone back to drinking coffee again. It used to bother my stomach, but for some reason, maybe I’m getting older and my stomach doesn’t care anymore, but I’ve been able to drink coffee a lot more. So, I’m very excited about this episode, talking about coffee and tea.
Jermaine begins by saying, “I’ll have a decaf drip, to go.” Now Jermaine is at a café or a coffee shop or a coffee house, a place where you would buy coffee and tea, so he’s ordering a cup of coffee. He says he wants a decaf drip, to go. “Decaf” is short for “decaffeinated,” that’s when you drink coffee that doesn’t have the caffeine that gets you awake or, for some people, overly excited. I don’t drink decaf coffee, unless it’s late at night and I know I need to go to sleep soon. “Coffee,” of course, is a drink made from putting hot water through grounded coffee beans. When we say something is “to go” we mean we are going to take it with us, we’re not going to drink it there at the café. In the United States, it’s very popular to get coffee to go; in other countries, it’s not as popular. But in the U.S., many, many people, maybe most people who go to a café or to a place like Starbucks get their drink to go, meaning they have a plastic or a paper cup and they’re able to take the drink with them in their car or wherever they’re going. “Drip” (drip) refers to coffee that is made usually in someone’s home, but in a Starbucks or in a café a drip coffee is the coffee that they’ve already made. It’s usually coffee that has been made in the last 30 to 60 minutes; it’s not coffee that they have to make specially for you. It usually changes; the kind of coffee changes every day depending on the café you go to. But a “drip coffee” is just the regular coffee, whatever it is that they’re serving today; you’re not asking for anything special.
So Jermaine asks for a decaf drip, to go. Drew says, “Would you like our light or dark roast?” The “roast” (roast) is how long the coffee beans have been cooked over a hot fire, and usually when you roast the coffee beans for a long time the beans get dark and it gives the coffee a different taste – a different flavor. You can have a dark roasted coffee, a medium roasted coffee, and a light roasted coffee, and the light roast doesn’t have as strong of a taste as the darker roast.
Jermaine says, “I’ll have whatever’s freshly brewed.” “To brew (brew) coffee” means to mix the coffee with hot water. We might also talk about brewing beer, but that’s when you have a different process of boiling some liquid in the process of making beer. But when we’re brewing coffee, it just means adding the hot water to the coffee or pouring the hot water through the coffee, which is the way it’s usually done. Jermaine says he wants whatever’s “freshly” brewed – recently brewed.
Drew says, “Are you sure you don’t want to try an espresso, an Americano, or a latte?” These three words: “espresso” (which many Americans pronounce “expresso” as though there were an “x” in there but there isn’t), “Americano,” and “latte” are Italian words, because the Italians, many people believe, have some of the best coffee or prepare some of the best coffee in the world. An “espresso” is a very dark, strong coffee that is made by pushing hot water through the coffee very quickly in a special machine called an “espresso machine.” Nowadays, many people have espresso machines in their houses. I have one, but I don’t usually drink espresso. An “Americano” is a drink made by taking the espresso and adding some additional hot water so that it isn’t quite as strong. In many countries, in Italy for example, when you order a coffee you’ll get an espresso. So if you want something more like an American coffee you have to ask for an Americano. A “latte” is coffee with milk; “latte” is the Italian word for milk. In this case it’s hot milk – steamed milk, and usually you add what are called “shots” of espresso. A “shot” is just a small amount of liquid.
But Jermaine doesn’t want any of that. He says, “No, just a decaf coffee.” “Drew says, “Sure, no problem. Would you like it hot or cold?” Some people like cold coffee. Jermaine says, “Hot, please.” Drew then says, “Would you like any room for cream?” “Cream” (cream) is something that comes from a cow; it has a lot of fat in it. It is the part of the milk that rises to the top of a milk container from cow’s milk, so it’s sort of a very fatty kind of milk. It’s a liquid that people often put in coffee; sometimes they just put in milk – regular milk. “Room” means space. In this case, when someone says “I want room for cream,” they mean they want the person working at the café, sometimes called a “barista,” to pour the coffee in a cup but leave room in the cup for some cream, and then the customer, the person buying the coffee, can add the amount of cream or milk that they want. In many cafés you can just say, “I’d like a coffee with room,” and you don’t even have to say “room for cream,” they understand what you mean. So if you really want to sound like a native speaker, you go into a café and you say, “Yeah, I’d like a large drip coffee with room, please,” and they’ll know that you want room for cream so they will leave some extra room in the cup.
Jermaine says, “No, thanks.” He doesn’t want room for cream. Drew says, “Would you like some sweetener?” “Sweetener” is something that, of course, makes the drink sweeter; sugar is the most obvious kind of way of sweetening a drink. But nowadays we have artificial sweeteners, things that kind of taste like sugar; they don’t really, but they make something sweeter. You can also make something sweeter by putting “syrup” in it, which is basically a liquid kind of sugar. Syrup (syrup) comes in many different flavors; you could have vanilla syrup, for example, in your coffee. I don’t like that, but some people do. Drew actually asks Jermaine if he wants a few pumps of syrup. A “pump” (pump) is just a small amount of syrup. It’s the way that they measure the amount of syrup in a café, because it comes from a bottle and the bottle on the top of it has a device called a “pump,” which is what you use to remove liquid from something by drawing it upwards.
Well, Jermaine doesn’t want any syrup. He says, “I’ll add a couple of packets of sugar myself.” A “packet” is a small container of something. Usually when you go to a café or some restaurants, you will get sugar or sweetener in a “packet,” a little container made out of paper. Drew says, “Oh, I’m sorry. I’ve added some foam from another drink to your coffee by accident.” “Foam” is when you have a lot of very small “bubbles,” little bits of air in the liquid, and this might happen if you are, for example, steaming the milk. You are heating the milk up very quickly by using hot air, and that air produces small bubbles of air that can cause foam on the top of the milk that you are steaming. Some people, when they have a latte drink or a drink with milk in it, don’t want the foam. But Drew has accidentally added foam to Jermaine’s drink. She tells Jermaine that she’ll start over, she’ll make his drink again. She says, “Did you say you wanted the light or dark roast?”
Jermaine says, “Forget it. Let’s keep it simple. Give me a cup of tea.” Drew says, “Would you like that hot or cold, sweetened or unsweetened, loose leaf or in a tea bag?” There are different ways of preparing tea, just as there are different ways of preparing coffee: hot and cold, sweetened or unsweetened – with sugar or without sugar. Also, the tea can be put into the hot water directly, or it can be put into a tea bag. When you use a tea bag, when you’re done making tea, when the tea has been in the hot water long enough you can then pull the tea out easily by just removing the bag. When you put tea in loose leaf, that means the tea goes right into the water; there’s no bag that you can use to take it out when you don’t want it there anymore. But people who drink their tea with loose leaf tea don’t really care, usually they just leave it in there until they’re done drinking and then they clean it out later.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jermaine: I’d like a decaf drip, to go.
Drew: Would you like our light or dark roast?
Jermaine: I’ll just have whatever’s freshly brewed.
Drew: Are you sure you don’t want to try an espresso, an Americano, or a latte?
Jermaine: No, just a decaf coffee.
Drew: Sure, no problem. Would you like it hot or cold?
Jermaine: Hot, please.
Drew: Would you like any room for cream?
Jermaine: No, thanks.
Drew: Would you like some sweetener? A couple of pumps of syrup maybe?
Jermaine: No, I’ll add a couple of packets of sugar myself.
Drew: Oh, I’m sorry. I added some foam from another drink to your coffee by accident. I’ll have to start over. Did you say you wanted the light or dark roast?
Jermaine: Forget it. Let’s keep it simple. Give me a cup of tea.
Drew: Would you like that hot or cold, sweetened or unsweetened, loose leaf or in a tea bag?
[end of dialogue]
You don’t need to add sweetener to our dialogues; they’re already sweet. That’s because they’re made by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. I don’t know what that means, either. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
decaf – decaffeinated; without caffeine (the substance that makes people feel alert and awake)
* Xander can only drink decaf in the evening, or else he has trouble falling asleep.
coffee – a drink made from passing hot water over ground coffee beans
* Hal begins each day with a cup of hot coffee.
to go – to be packaged so that one can eat or drink something outside of the store or restaurant where it is sold
* Are you going to sit at a table, or do you want this to go?
roast – a measure of how long the coffee beans have been cooked over a hot fire, especially how dark in color they appear
* This is a medium-roast coffee with flavors of chocolate and cinnamon.
drip – coffee that is brewed (made) by passing hot water over ground coffee beans; the way coffee is typically made in someone’s home
* This drip coffee is really bitter. I think you used too much coffee and not enough water.
espresso – very strong, dark coffee made by pushing steam (hot water vapor) through coffee beans very quickly
* Many people like to drink espresso after their meal.
Americano – a drink made by adding hot water to a small amount of espresso
* The coffee shop didn’t have any brewed coffee, so they made me an Americano for the same price.
latte – a drink made by putting espresso in a cup and then adding steamed milk that has a lot of air in it
* Jillian’s favorite drink is a vanilla latte.
room – space; an area that is set aside for some particular purpose
* Do you have room in your garage to store these boxes for a few months?
cream – a high-fat dairy product; the fatty substance that rises to the top of a container of cow’s milk
* Yevgeny’s doctor told him to try to lower his cholesterol by using nonfat milk instead of cream in his morning coffee.
sweetener – a substance that makes something taste sweeter, such as sugar, honey, and saccharin
* People with diabetes need to use artificial sweeteners instead of real sugar.
pump – the amount of liquid dispensed (released from a bottle) by pushing the top of the bottle down one time
* Becca uses one pump of lotion for her face and neck, and another pump for her elbows.
syrup – a thick, sweet liquid used to sweeten other foods
* Do you want some maple syrup on your pancakes?
packet – a small container made from paper or cardboard, usually containing a single portion (something meant to be used or eaten by one person at one time)
* Just pour the contents of the packet into a 20-ounce bottle of water to make lemonade.
sugar – glucose, fructose, sucrose, etc.; a sweet-tasting substance with the chemical formula CnH2nOn
* How many teaspoons of sugar are in a can of regular soda?
foam – many very small bubbles in a liquid; froth
* Why do these ocean waves have so much foam on them?
to start over – to begin again, usually because one’s first attempt failed
* About one minute into her speech for her Italian class, Candy forgot what she had planned to say. She asked, “Can I start over?”
loose leaf – small pieces of dried tea leaves that are put in hot water to make a cup of tea
* Randy used too much loose leaf tea, so the drink was really strong.
tea bag – small pieces of dried tea leaves that are held in a small paper bag that is put in hot water to make a cup of tea
* Mariah’s tea had a lot of small pieces floating in it, because the tea bag broke open.
Comprehension Questions
1. Which of these drinks contains milk?
a) Espresso
b) Americano
c) Latte
2. Which of these is a sweetener?
a) Cream
b) Sugar
c) Foam
Answers at bottom.
What Else Does It Mean?
drip
The word “drip,” in this podcast, means coffee that is brewed (made) by passing hot water over ground coffee beans: “This drip coffee maker has a timer, so that it can start making coffee before we wake up, to be sure the coffee is hot and ready when we get up.” Informally, when talking about medicine and healthcare, a “drip” can refer to an IV, or a small bag of liquid with a tube connected to a needle in a patient’s skin to transfer liquids into the blood: “When Jacques became dehydrated, the nurse put him on a saline drip.” Finally, a “drip” can also be the sound of a drop of liquid falling onto something else: “The drip from the kitchen sink is keeping me awake. Could you please fix it?”
room
In this podcast, the word “room” means empty space, or an area that is set aside for some particular purpose: “This conference facility has room for up to 200 attendees.” The phrase “leg room” refers to having enough space for one’s legs to relax comfortably when seated: “Bryan is almost seven feet tall, so he never has enough leg room when flying.” The phrase “elbow room” describes having enough space to move around comfortably: “Let’s move this meeting next door so we can have some elbow room.” Finally, the phrase “room for” can refer to an opportunity to have or do something or to make something happen: “Your speech was good, but I think there’s room for improvement.” Or, “He presented a lot of good reasons for supporting the organization, but there’s still room for argument.”
Culture Note
Independent Coffeehouses
In recent years, “coffeehouses” or “coffee shops” have become popular meeting places in the United States, especially in the “Pacific Northwest” (the northwestern part of the country, especially Oregon and Washington). Most coffeehouses have comfortable “couches” (soft seats for two to three people) and small tables “configured” (positioned) to “promote” (encourage) conversations in small groups. Modern coffeehouses have “soft” (quiet) music, often jazz, “dim” (not very bright) lighting, and interesting artwork on the walls. Sometimes the coffeehouse “features” (shows) “pieces” (artwork) by local artists, and those pieces may be available for purchase.
Almost all coffeehouses offer free “wi-fi” (an Internet connection that computers can connect to without cables). Customers are allowed to stay in the coffeehouse for a long time as long as they purchase something. Many self-employed people work in coffeehouses and/or meet with clients there. Students are often “found” (seen) studying at coffeehouses when they want a “change of environment” (wanting to do one’s activities in a different place from where one normally does those things).
Many “independent” (small, private businesses that are not part of a national or international chain) coffeehouses are “community-oriented” (thinking about the community) and host community events. For example, they might have “poetry readings” (opportunities for poets to read their poems aloud), “book signings” (opportunities for writers to sign their books for readers), and music performances. Some independent coffeehouses have special evenings for “crafts” (art done by hand) or “board games” (games played at a table with dice, cards, and other small pieces). Other independent coffeehouses invite politicians to speak to members of the community. These coffeehouses also encourage local organizations to “book” (reserve) space for their meetings.
Comprehension Answers
1 - c
2 - b